### ISSUE TITLE
Fastlane error - block in parse_header

### ISSUE THREAD

**Issue by adrianjez** [fastlane/fastlane#15244]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Our working solution just has stopped working. Attached output.

<details>
  <pre>/Library/Ruby/Gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:808:in `block in parse_header': [!] HTTPClient::KeepAliveDisconnected:  (HTTPClient::KeepAliveDisconnected)

from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'

from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:101:in `timeout'

from /Library/Ruby/Gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:801:in `parse_header'

from /Library/Ruby/Gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:784:in `read_header'

from /Library/Ruby/Gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:561:in `get_header'

from /Library/Ruby/Gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1299:in `do_get_header'

from /Library/Ruby/Gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1245:in `do_get_block'

from /Library/Ruby/Gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'

from /Library/Ruby/Gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1138:in `rescue in protect_keep_alive_disconnected'

from /Library/Ruby/Gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1131:in `protect_keep_alive_disconnected'

from /Library/Ruby/Gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'

from /Library/Ruby/Gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1104:in `follow_redirect'

from /Library/Ruby/Gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:854:in `request'

from /Library/Ruby/Gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:765:in `post'

from /Library/Ruby/Gems/2.3.0/gems/google-api-client-0.23.9/lib/google/apis/core/upload.rb:228:in `send_upload_command'

from /Library/Ruby/Gems/2.3.0/gems/google-api-client-0.23.9/lib/google/apis/core/upload.rb:254:in `execute_once'

from /Library/Ruby/Gems/2.3.0/gems/google-api-client-0.23.9/lib/google/apis/core/http_command.rb:104:in `block (2 levels) in execute'

from /Library/Ruby/Gems/2.3.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'

from /Library/Ruby/Gems/2.3.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'

from /Library/Ruby/Gems/2.3.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'

from /Library/Ruby/Gems/2.3.0/gems/google-api-client-0.23.9/lib/google/apis/core/http_command.rb:101:in `block in execute'

from /Library/Ruby/Gems/2.3.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'

from /Library/Ruby/Gems/2.3.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'

from /Library/Ruby/Gems/2.3.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'

from /Library/Ruby/Gems/2.3.0/gems/google-api-client-0.23.9/lib/google/apis/core/http_command.rb:93:in `execute'

from /Library/Ruby/Gems/2.3.0/gems/google-api-client-0.23.9/lib/google/apis/core/base_service.rb:360:in `execute_or_queue_command'

from /Library/Ruby/Gems/2.3.0/gems/google-api-client-0.23.9/generated/google/apis/androidpublisher_v2/service.rb:719:in `upload_edit_bundle'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/supply/lib/supply/client.rb:298:in `block in upload_bundle'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/supply/lib/supply/client.rb:80:in `call_google_api'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/supply/lib/supply/client.rb:297:in `upload_bundle'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/supply/lib/supply/uploader.rb:165:in `block in upload_bundles'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/supply/lib/supply/uploader.rb:163:in `each'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/supply/lib/supply/uploader.rb:163:in `upload_bundles'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/supply/lib/supply/uploader.rb:28:in `perform_upload'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/actions/upload_to_play_store.rb:33:in `run'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'

from Fastfile:27:in `block (2 levels) in parsing_binding'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/lane.rb:33:in `call'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/runner.rb:45:in `execute'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'

from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'

from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'

from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'

from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/bin/fastlane:23:in `<top (required)>'

from /usr/local/bin/fastlane:22:in `load'

from /usr/local/bin/fastlane:22:in `<main>'</pre>
</details>

### Environment

<details>
  <pre>[✔] 🚀 

[08:59:11]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

[08:59:12]: Generating fastlane environment output, this might take a few seconds...

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |

| --------------------------- | -------------------------------------------------------------- |

| OS                          | 10.14.3                                                        |

| Ruby                        | 2.3.7                                                          |

| Bundler?                    | false                                                          |

| Git                         | git version 2.21.0                                             |

| Installation Source         | /usr/local/bin/fastlane                                        |

| Host                        | Mac OS X 10.14.3 (18D109)                                      |

| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |

| OpenSSL Version             | LibreSSL 2.6.4                                                 |

| Is contained                | false                                                          |

| Is homebrew                 | false                                                          |

| Is installed via Fabric.app | false                                                          |

| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |

| Xcode Version               | 10.3                                                           |

### System Locale

| Variable | Value       |   |

| -------- | ----------- | - |

| LANG     | pl_PL.UTF-8 | ✅ |

| LC_ALL   |             |   |

| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

# This file contains the fastlane.tools configuration

# You can find the documentation at https://docs.fastlane.tools

#

# For a list of all available actions, check out

#

#     https://docs.fastlane.tools/actions

#

# For a list of all available plugins, check out

#

#     https://docs.fastlane.tools/plugins/available-plugins

#


# Uncomment the line if you want fastlane to automatically update itself

# update_fastlane


default_platform(:android)


platform :android do


  desc "Description of what the lane does"

  lane :custom_lane do

    # add actions here: https://docs.fastlane.tools/actions

  end


  desc 'Deploy a new internal version to the Google Play Store'

    lane :internal do |options|

      supply(

        track: 'internal',

        aab: options[:abb_file_path],

        skip_upload_apk: true

      )

  end


  desc 'Deploy a new closed version to the Google Play Store'

    lane :closed do |options|

      supply(

        track: 'closed',

        aab: options[:abb_file_path]

      )

  end


  desc 'Deploy a new alpha version to the Google Play Store'

    lane :alpha do |options|

      supply(

        track: 'alpha',

        aab: options[:abb_file_path]

      )

  end


  desc 'Deploy a new beta version to the Google Play Store'

    lane :beta do |options|

      supply(

        track: 'beta',

        aab: options[:abb_file_path]

      )

  end

end


```

</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby

# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app

# apple_id("[[APPLE_ID]]") # Your Apple email address



# For more information about the Appfile, see:

#     https://docs.fastlane.tools/advanced/#appfile

json_key_file("fastlane/json_key.json") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one

package_name("<>HIDDEN PACKAGE NAME<>") # e.g. com.krausefx.app

```

</details>

### fastlane gems

| Gem      | Version | Update-Status  |

| -------- | ------- | -------------- |

| fastlane | 2.129.0 | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |

| ------------------------- | ------------ |

| did_you_mean              | 1.0.0        |

| slack-notifier            | 2.3.2        |

| atomos                    | 0.1.3        |

| CFPropertyList            | 3.0.1        |

| claide                    | 1.0.3        |

| colored2                  | 3.1.2        |

| nanaimo                   | 0.2.6        |

| xcodeproj                 | 1.12.0       |

| rouge                     | 2.0.7        |

| xcpretty                  | 0.3.0        |

| terminal-notifier         | 2.0.0        |

| unicode-display_width     | 1.6.0        |

| terminal-table            | 1.8.0        |

| plist                     | 3.5.0        |

| public_suffix             | 2.0.5        |

| addressable               | 2.6.0        |

| multipart-post            | 2.0.0        |

| word_wrap                 | 1.0.0        |

| tty-screen                | 0.7.0        |

| tty-cursor                | 0.7.0        |

| tty-spinner               | 0.9.1        |

| babosa                    | 1.0.2        |

| colored                   | 1.2          |

| highline                  | 1.7.10       |

| commander-fastlane        | 4.4.6        |

| excon                     | 0.66.0       |

| faraday                   | 0.15.4       |

| unf_ext                   | 0.0.7.6      |

| unf                       | 0.1.4        |

| domain_name               | 0.5.20190701 |

| http-cookie               | 1.0.3        |

| faraday-cookie_jar        | 0.0.6        |

| fastimage                 | 2.1.5        |

| gh_inspector              | 1.1.3        |

| json                      | 1.8.3.1      |

| mini_magick               | 4.9.5        |

| multi_xml                 | 0.6.0        |

| rubyzip                   | 1.2.3        |

| security                  | 0.1.3        |

| xcpretty-travis-formatter | 1.0.0        |

| dotenv                    | 2.7.5        |

| bundler                   | 2.0.2        |

| faraday_middleware        | 0.13.1       |

| naturally                 | 2.2.0        |

| simctl                    | 1.6.5        |

| jwt                       | 2.1.0        |

| uber                      | 0.1.0        |

| declarative               | 0.0.10       |

| declarative-option        | 0.1.0        |

| representable             | 3.0.4        |

| retriable                 | 3.1.2        |

| mime-types-data           | 3.2019.0331  |

| mime-types                | 3.2.2        |

| multi_json                | 1.13.1       |

| signet                    | 0.11.0       |

| memoist                   | 0.16.0       |

| os                        | 1.0.1        |

| googleauth                | 0.6.7        |

| httpclient                | 2.8.3        |

| google-api-client         | 0.23.9       |

| google-cloud-env          | 1.2.1        |

| google-cloud-core         | 1.3.1        |

| digest-crc                | 0.4.1        |

| google-cloud-storage      | 1.16.0       |

| emoji_regex               | 1.0.1        |

| io-console                | 0.4.5        |

| libxml-ruby               | 2.9.0        |

| psych                     | 2.1.0.1      |

</details></pre>
</details>

**Comment by janpio** [comment]
What command did you run to get this error message?

**Comment by adrianjez** [comment]
I launched internal lane internal using this command: 
fastlane internal abb_file_path:"Correct_file_path"

I know that there is typo in variable name - but it is script internal key used to get path in lane definition using variable with typo: aab: options[:abb_file_path] - so it is not a reason
Lane definition
 desc 'Deploy a new internal version to the Google Play Store'
    lane :internal do |options|
      supply(
        track: 'internal',
        aab: options[:abb_file_path],
        skip_upload_apk: true
      )
  end

**Comment by janpio** [comment]
Can you please post the complete output and not just the stacktrace part?

**Comment by adrianjez** [comment]
MacBook-Pro:fastane username$ sh deploy2.sh 

[✔] 🚀 

[08:35:28]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

[08:35:29]: ------------------------------

[08:35:29]: --- Step: default_platform ---

[08:35:29]: ------------------------------

[08:35:29]: Driving the lane 'android internal' 🚀

[08:35:29]: --------------------

[08:35:29]: --- Step: supply ---

[08:35:29]: --------------------


+-------------------------+------------------------+

|            Summary for supply 2.129.0            |

+-------------------------+------------------------+

| track                   | internal               |

| aab                     | prdRelease_3.2.553.aab |

| skip_upload_apk         | true                   |

| package_name            | <HIDDEN_PACKAGE_NAME>  |

| json_key                | fastlane/json_key.json |

| skip_upload_aab         | false                  |

| skip_upload_metadata    | false                  |

| skip_upload_images      | false                  |

| skip_upload_screenshots | false                  |

| validate_only           | false                  |

| check_superseded_tracks | false                  |

| timeout                 | 300                    |

| deactivate_on_promote   | true                   |

+-------------------------+------------------------+


[08:35:31]: Preparing aab at path 'prdRelease_3.2.553.aab' for upload...

+------------------+------------------+

|            Lane Context             |

+------------------+------------------+

| DEFAULT_PLATFORM | android          |

| PLATFORM_NAME    | android          |

| LANE_NAME        | android internal |

+------------------+------------------+

[08:41:04]: HTTPClient::KeepAliveDisconnected: 


+------+------------------+-------------+

|           fastlane summary            |

+------+------------------+-------------+

| Step | Action           | Time (in s) |

+------+------------------+-------------+

| 1    | default_platform | 0           |

| 💥   | supply           | 335         |

+------+------------------+-------------+


[08:41:04]: fastlane finished with errors


Looking for related GitHub issues on fastlane/fastlane...


Found no similar issues. To create a new issue, please visit:

https://github.com/fastlane/fastlane/issues/new

Run `fastlane env` to append the fastlane environment to your issue

/Library/Ruby/Gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:808:in `block in parse_header': [!] HTTPClient::KeepAliveDisconnected:  (HTTPClient::KeepAliveDisconnected)

from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'

from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:101:in `timeout'

from /Library/Ruby/Gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:801:in `parse_header'

from /Library/Ruby/Gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:784:in `read_header'

from /Library/Ruby/Gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:561:in `get_header'

from /Library/Ruby/Gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1299:in `do_get_header'

from /Library/Ruby/Gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1245:in `do_get_block'

from /Library/Ruby/Gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'

from /Library/Ruby/Gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1138:in `rescue in protect_keep_alive_disconnected'

from /Library/Ruby/Gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1131:in `protect_keep_alive_disconnected'

from /Library/Ruby/Gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'

from /Library/Ruby/Gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1104:in `follow_redirect'

from /Library/Ruby/Gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:854:in `request'

from /Library/Ruby/Gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:765:in `post'

from /Library/Ruby/Gems/2.3.0/gems/google-api-client-0.23.9/lib/google/apis/core/upload.rb:228:in `send_upload_command'

from /Library/Ruby/Gems/2.3.0/gems/google-api-client-0.23.9/lib/google/apis/core/upload.rb:254:in `execute_once'

from /Library/Ruby/Gems/2.3.0/gems/google-api-client-0.23.9/lib/google/apis/core/http_command.rb:104:in `block (2 levels) in execute'

from /Library/Ruby/Gems/2.3.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'

from /Library/Ruby/Gems/2.3.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'

from /Library/Ruby/Gems/2.3.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'

from /Library/Ruby/Gems/2.3.0/gems/google-api-client-0.23.9/lib/google/apis/core/http_command.rb:101:in `block in execute'

from /Library/Ruby/Gems/2.3.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'

from /Library/Ruby/Gems/2.3.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'

from /Library/Ruby/Gems/2.3.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'

from /Library/Ruby/Gems/2.3.0/gems/google-api-client-0.23.9/lib/google/apis/core/http_command.rb:93:in `execute'

from /Library/Ruby/Gems/2.3.0/gems/google-api-client-0.23.9/lib/google/apis/core/base_service.rb:360:in `execute_or_queue_command'

from /Library/Ruby/Gems/2.3.0/gems/google-api-client-0.23.9/generated/google/apis/androidpublisher_v2/service.rb:719:in `upload_edit_bundle'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/supply/lib/supply/client.rb:298:in `block in upload_bundle'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/supply/lib/supply/client.rb:80:in `call_google_api'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/supply/lib/supply/client.rb:297:in `upload_bundle'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/supply/lib/supply/uploader.rb:165:in `block in upload_bundles'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/supply/lib/supply/uploader.rb:163:in `each'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/supply/lib/supply/uploader.rb:163:in `upload_bundles'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/supply/lib/supply/uploader.rb:28:in `perform_upload'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/actions/upload_to_play_store.rb:33:in `run'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'

from Fastfile:27:in `block (2 levels) in parsing_binding'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/lane.rb:33:in `call'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/runner.rb:45:in `execute'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'

from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'

from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'

from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'

from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'

from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.129.0/bin/fastlane:23:in `<top (required)>'

from /usr/local/bin/fastlane:22:in `load'

from /usr/local/bin/fastlane:22:in `<main>'

**Comment by janpio** [comment]
Seems like the connection between you and the Google API used to upload the file broke and returned and error. Usually that is only a temporary problem.

Can you recreate the problem every time?
