### ISSUE TITLE
Create Group for external testers

### ISSUE THREAD

**Issue by MostafaEl-Sayed** [fastlane/fastlane#15240]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Create new group for external testers 

#### Question Description

```
   app = Spaceship::ConnectAPI::App.find("#{options[:bundle_identfier]}")
    number = latest_testflight_build_number(
      app_identifier: ""#{options[:bundle_identfier]}""
     ) 
    build_array = Spaceship::ConnectAPI::Build.all(app_id: "#{options[:app_id]}", version: '1.0.0', build_number: number)
    first_build = build_array.first 
    my_groups = first_build.app.get_beta_groups(filter: {name: "GROUP1"})
    first_group = my_groups.first
    Spaceship::ConnectAPI.add_beta_groups_to_build(build_id: first_build.id, beta_group_ids: [first_group.id])
```
those lines get build already created, and add latest Distributed build into it, 
But if I don't have a group I have to create it, so I can create it ..!?

**Comment by janpio** [comment]
Ping @max-ott

**Comment by MostafaEl-Sayed** [comment]
@janpio If we are not able to create group, can we add a "Individual Tester"

**Comment by janpio** [comment]
I did not say that, and I do not know. 
I only know the normal `fastlane pilot` CLI: https://docs.fastlane.tools/actions/pilot/#add-a-new-tester

**Comment by marcferna** [comment]
Digging a bit more into this...I see that when I manually create an external group in ITC, it makes a POST request to `https://appstoreconnect.apple.com/iris/v1/betaGroups/ID`, with the following payload: `{"data":{"type":"betaGroups","attributes":{"name":"GROUP_NAME"},"relationships":{"app":{"data":{"type":"apps","id":"APP_ID"}}}}}`.

When I do `fastlane pilot import` or `fastlane pilot add` it does not make this call if the group does not exist nor makes the POST request to associate the user with any group (because the group does not exist).

Hope this helps - I'll dig a bit into the code as well

**Comment by marcferna** [comment]
Might something like this work?
```
def create_beta_group(app_id: nil, group_name: nil)
        body = {
          data: {
            type: "betaGroups",
            attributes: {
              name: group_name
            },
            relationships: {
              app: {
                data: {
                  type: "apps",
                  id: app_id
                }
              }
            }
          }
        }
        
        Client.instance.post("betaGroups", body)
      end
```

**Comment by MostafaEl-Sayed** [comment]
> Might something like this work?
> 
> ```
> def create_beta_group(app_id: nil, group_name: nil)
>   body = {
>     data: {
>       type: "betaGroups",
>       attributes: {
>         name: group_name
>       },
>       relationships: {
>         app: {
>           data: {
>             type: "apps",
>             id: app_id
>           }
>         }
>       }
>     }
>   }
> 
>   Client.instance.post("betaGroups", body)
> end
> ```
> 
> https://developer.apple.com/documentation/appstoreconnectapi/create_a_beta_group

Its not working also, it gave me an error.
