### ISSUE TITLE
Will fastlane/match support new certificate type `Developer ID Application`

### ISSUE THREAD

**Issue by vastopa** [fastlane/fastlane#15241]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
This question is related to fastlane/match managing specific types of certificates - specifically the `Developer ID Application` certificate used to notarize macOS apps not distributed through the AppStore

#### Question Description

With macOS Mojave, there is now the possibility to notarize macOS apps that are not distributed through the AppStore. Notarizing is only possible using a new Certificate type called `Developer ID Application` as shown in the picture below:
![image](https://user-images.githubusercontent.com/5408881/63964640-8c8bf180-ca65-11e9-8822-948c1d8d7b4c.png)

Will fastlane match ever support managing this type of certificate? In order to automate the notarization of my macOS app through my CI workflow, it would be much easier if match could generate/retrieve this type of certificate.

I see that there was a [related issue](https://github.com/fastlane/fastlane/issues/4252) closed in 2016 for this request - just wondering if it's possible to revisit this

Thanks in advance for your time - I hope I filled out the template correctly!

**Comment by janpio** [comment]
Yes, this definitely looks like something we want to get in there.

@joshdholtz can probably provide some input on if this is available via the APIs we are using in the background. (And @max-ott might know if this is even already possible and just not properly documented.)

**Comment by vastopa** [comment]
Match doesn't currently support macos for standard certificates or profiles (https://github.com/fastlane/fastlane/issues/11980) -> anyone know if there's progress or plans for this?

**Comment by janpio** [comment]
No known work in progress, so we would be very happy to accept PRs on that.

**Comment by vastopa** [comment]
Commenting so this issue stays open. Will look into what it will take to contribute to this effort hopefully sometime soon. If anyone has any tips/guidance for where to jump into for this feature, would be greatly appreciated!

**Comment by vastopa** [comment]
Please don't close this - hoping to take on this issue with a friend who is well-versed in Ruby. Will update the issue when I can with any proposal we come up with

**Comment by vastopa** [comment]
Please keep open

**Comment by judgeaxl** [comment]
@vastopa from what I can tell, as I also would like this, is that you need to first make `cert` support the new certificate type, and then `match`. I haven't worked in Ruby for some time so I'm not sure what the best approach is, but at least `Spaceship` already supports it from what I can tell, I used it to manually create a macOS certificate without going to the Apple website.

**Comment by judgeaxl** [comment]
Seems like one would change the `-development` switch in `cert/options` to either take the actual type, (Apple Development, Apple Distribution (AppStore), Mac installer, or Mac Developer ID), or add another switch to take that type, overriding `-development`. Then in `cert/runner` the `certificate_type` method needs to return the right type based on the new logic. Since cert still supports the old style iOS/Mac certs, it's probably a bit more work to come up with sensible option names.
`Match` would require almost the same changes, and be taught the new cert options.

**Comment by lazerwalker** [comment]
That sounds correct, based on when I was looking into this a few months ago.

**Comment by lazerwalker** [comment]
Pleas keep open!

**Comment by vastopa** [comment]
@lazerwalker the [latest release of fastlane](https://github.com/fastlane/fastlane/releases) supports macos certificates as well as notarization! 

Closing this issue
