### ISSUE TITLE
Gym tries to use adhoc certificate in spite of export_method set to app-store

### ISSUE THREAD

**Issue by Antol** [fastlane/fastlane#15249]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I built app with gym and export_method set to app-store, but got an error "No profile for team 'V49...' matching 'match AdHoc com.future' found..."

##### Command executed
**match** followed by **gym**

##### Complete output when running fastlane, including the stack trace and command used     
     
	+-----------------------+------------------------------------------+
	|                    Summary for match 2.129.0                     |
	+-----------------------+------------------------------------------+
	| username              | an...@gmail.com                          |
	| app_identifier        | ["com.future..."]                        |
	| team_id               | V4...                                    |
	| git_branch            | V4...                                    |
	| type                  | appstore                                 |
	| readonly              | true                                     |
	| storage_mode          | git                                      |
	| git_url               | git@gitlab.com:....git                   |
	| shallow_clone         | true                                     |
	| clone_branch_directly | true                                     |
	| keychain_name         | login.keychain                           |
	| force                 | false                                    |
	| force_for_new_devices | false                                    |
	| skip_confirmation     | false                                    |
	| skip_docs             | false                                    |
	| platform              | ios                                      |
	| verbose               | false                                    |
	+-----------------------+------------------------------------------+

	[16:58:57]: Cloning remote git repo...
	[16:59:09]: Checking out branch V49......
	[16:59:09]: 🔓  Successfully decrypted certificates repo
	[16:59:09]: Installing certificate...
	[16:59:09]: Setting key partition list... (this can take a minute if there are a lot of keys installed)
	[16:59:09]: 
	[16:59:09]: Could not configure imported keychain item (certificate) to prevent UI permission popup when code signing
	Check if you supplied the correct `keychain_password` for keychain: `/Users/.../Library/Keychains/login.keychain-db`
	security: SecKeychainItemSetAccessWithPassword: The user name or passphrase you entered is not correct.
	[16:59:09]: 
	[16:59:09]: Please look at the following docs to see how to set a keychain password:
	[16:59:09]:  - https://docs.fastlane.tools/actions/sync_code_signing
	[16:59:09]:  - https://docs.fastlane.tools/actions/get_certificates
	[16:59:10]: Setting key partition list... (this can take a minute if there are a lot of keys installed)
	[16:59:10]: 
	[16:59:10]: Could not configure imported keychain item (certificate) to prevent UI permission popup when code signing
	Check if you supplied the correct `keychain_password` for keychain: `/Users/.../Library/Keychains/login.keychain-db`
	security: SecKeychainItemSetAccessWithPassword: The user name or passphrase you entered is not correct.
	[16:59:10]: 
	[16:59:10]: Please look at the following docs to see how to set a keychain password:
	[16:59:10]:  - https://docs.fastlane.tools/actions/sync_code_signing
	[16:59:10]:  - https://docs.fastlane.tools/actions/get_certificates

	+-------------------+------------------------------------------------------------+
	|                             Installed Certificate                              |
	+-------------------+------------------------------------------------------------+
	| User ID           | V49...                                                 |
	| Common Name       | iPhone Distribution: ..., OOO (V49...) |
	| Organisation Unit | V49...                                                 |
	| Organisation      | ..., OOO                                   |
	| Country           | US                                                         |
	| Start Datetime    | 2019-08-30 10:10:48 UTC                                    |
	| End Datetime      | 2020-08-29 10:10:48 UTC                                    |
	+-------------------+------------------------------------------------------------+

	[16:59:10]: Installing provisioning profile...

	+---------------------+--------------------------------------------------+------------------------------------------------------------------------------------------------------------------+
	|                                                                              Installed Provisioning Profile                                                                               |
	+---------------------+--------------------------------------------------+------------------------------------------------------------------------------------------------------------------+
	| Parameter           | Environment Variable                             | Value                                                                                                            |
	+---------------------+--------------------------------------------------+------------------------------------------------------------------------------------------------------------------+
	| App Identifier      |                                                  | com.futu...                                                                                            |
	| Type                |                                                  | appstore                                                                                                         |
	| Platform            |                                                  | ios                                                                                                              |
	| Profile UUID        | sigh_com.future..._appstore              | 88239...c03427e9                                                                             |
	| Profile Name        | sigh_com.future..._appstore_profile-name | match AppStore com.future...                                                                             |
	| Profile Path        | sigh_com.future..._appstore_profile-path | /Users/.../Library/MobileDevice/Provisioning Profiles/88239...c03427e9.mobileprovision |
	| Development Team ID | sigh_com.future..._appstore_team-id      | V49...                                                                                                       |
	+---------------------+--------------------------------------------------+------------------------------------------------------------------------------------------------------------------+

	[16:59:10]: All required keys, certificates and provisioning profiles are installed 🙌
	[16:59:10]: Setting Provisioning Profile type to 'app-store'
	[16:59:10]: Cruising back to lane 'ios tf' 🚘
	[16:59:10]: ---------------------------
	[16:59:10]: --- Step: build_ios_app ---
	[16:59:10]: ---------------------------
	[16:59:10]: $ xcodebuild -showBuildSettings -workspace ./Mobile....xcworkspace -scheme Mobile... -configuration Release
	[16:59:14]: Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...
	[16:59:15]: Detected provisioning profile mapping: {:"com.future..."=>"match AppStore com.future..."}

	+-----------------------------------------------------------+--------------------------------------------------------------+
	|                                                 Summary for gym 2.129.0                                                  |
	+-----------------------------------------------------------+--------------------------------------------------------------+
	| scheme                                                    | Mobile...                                                    |
	| configuration                                             | Release                                                      |
	| export_method                                             | app-store                                                    |
	| export_options.provisioningProfiles.com.future... | match AppStore com.future...                                 |
	| workspace                                                 | ./Mobile....xcworkspace                                      |
	| destination                                               | generic/platform=iOS                                         |
	| output_name                                               | Mobile...                                                    |
	| build_path                                                | /Users/.../Library/Developer/Xcode/Archives/2019-08-30       |
	| clean                                                     | true                                                         |
	| output_directory                                          | ./build/                                                     |
	| silent                                                    | true                                                         |
	| skip_package_ipa                                          | false                                                        |
	| result_bundle                                             | false                                                        |
	| buildlog_path                                             | ~/Library/Logs/gym                                           |
	| suppress_xcode_output                                     | true                                                         |
	| skip_profile_detection                                    | false                                                        |
	| xcode_path                                                | /Applications/Xcode.app                                      |
	+-----------------------------------------------------------+--------------------------------------------------------------+

	[16:59:19]: ▸ ** ARCHIVE FAILED **
	** ARCHIVE FAILED **
	[16:59:19]: Exit status: 65

	+---------------+-------------------------+
	|            Build environment            |
	+---------------+-------------------------+
	| xcode_path    | /Applications/Xcode.app |
	| gym_version   | 2.129.0                 |
	| export_method | app-store               |
	| sdk           | iPhoneOS12.2.sdk        |
	+---------------+-------------------------+

	[16:59:19]: ▸ note: Using new build system
	[16:59:19]: ▸ note: Planning build
	[16:59:19]: ▸ note: Constructing build description
	[16:59:19]: ▸ Build system information
	[16:59:19]: ▸ error: No profile for team 'V49...' matching 'match AdHoc com.future...' found: Xcode couldn't find any provisioning profiles matching 'V49.../match AdHoc com.future...'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the General tab of the target editor. (in target 'Mobile...')
	[16:59:19]: 
	[16:59:19]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
	[16:59:19]: 📋  For the complete and more detailed error log, check the full log at:
	[16:59:19]: 📋  /Users/.../Library/Logs/gym/Mobile...-Mobile....log
	[16:59:19]: 
	[16:59:19]: Looks like fastlane ran into a build/archive error with your project
	[16:59:19]: It's hard to tell what's causing the error, so we wrote some guides on how
	[16:59:19]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
	[16:59:19]: Before submitting an issue on GitHub, please follow the guide above and make
	[16:59:19]: sure your project is set up correctly.
	[16:59:19]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
	[16:59:19]: the full commands printed out in yellow in the above log.
	[16:59:19]: Make sure to inspect the output above, as usually you'll find more error information there
	[16:59:19]: 
	[16:59:19]: Problem with build: Error building the application - see the log above
	+------------------------------------+-------------------------------------------------------------------+
	|                                              Lane Context                                              |
	+------------------------------------+-------------------------------------------------------------------+
	| DEFAULT_PLATFORM                   | ios                                                               |
	| PLATFORM_NAME                      | ios                                                               |
	| LANE_NAME                          | ios tf_release                                                    |
	| GET_INFO_PLIST_VALUE_CUSTOM_VALUE  | 1.6.1                                                             |
	| FL_CHANGELOG                       |                                                                   |
	| SIGH_PROFILE_TYPE                  | app-store                                                         |
	| MATCH_PROVISIONING_PROFILE_MAPPING | {"com.future..."=>"match AppStore com.future..."}                 |
	+------------------------------------+-------------------------------------------------------------------+

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.5                                     |
| Ruby                        | 2.5.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | ~/.rbenv/versions/2.5.0/bin/fastlane        |
| Host                        | Mac OS X 10.14.5 (18F132)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.0/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2p  14 Aug 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.128.0"
import_from_git(url: 'git@gitlab.com:....git', branch: 'v2', path: 'Fastfile')
default_platform :ios

platform :ios do

  lane :tf_release do
    tf(
      scheme: 'Mobile...',
      app_store_connect_team_id: '11...'
    )
  end

end


```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.129.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| bundler                   | 2.0.2        |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.1.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.11.1     |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.3        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.7.5        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.2.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.1        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| cocoapods                 | 1.7.5        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.66.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.1        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| httparty                  | 0.17.0       |
</details>

**Comment by Katsz** [comment]
The bundle of your app did sneak up in the logs (if it is critical for you).

AFAIK export_method is about only.. well.. export method. 
![image](https://user-images.githubusercontent.com/16171550/64044315-c82fd400-cba9-11e9-9624-cfe1a4348ec4.png)

There's no relationship to provision profile. Can you double check that correct provision selected in Xcode's target?
![image](https://user-images.githubusercontent.com/16171550/64044523-599f4600-cbaa-11e9-8292-a6e491a452bd.png)

**Comment by Antol** [comment]
Thank you @Katsz , you have a sharp eye :)
Yep, you are right. Provisioning profile in the project settings set to Adhoc. But it is very unclear based on the info in the fastlane logs, all the stuff there says only about AppStore profile.
I thought that match will set global var (MATCH_PROVISIONING_PROFILE_MAPPING) which profile to use, and gym will just take that var.
Now with that new info I made a recheck of gym parameters and it seems that skip_profile_detection set to true may fix that behavior, but it needs to be checked
