### ISSUE TITLE
can fastlane support personal teams?

### ISSUE THREAD

**Issue by huos3203** [fastlane/fastlane#15254]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

#### Question Description
Xcode already supports personal accounts (not developer accounts) running on a real machine. In this case, how do you use Fastlane to compile apps and run them on the real machine?

**Comment by janpio** [comment]
> personal accounts (not developer accounts)

What does this mean exactly? Can you illustrate?

**Comment by huos3203** [comment]
I don't have a developer account, but I can run App on a real machine through xcode. Now I want to do this through fastlane. but I don't know how to configure fastlane.

**Comment by janpio** [comment]
What exactly do you want to do with fastlane? Uploading to the App Store etc. is obviously out of the question as this requires a developer account, but everything else should work as normal.

**Comment by huos3203** [comment]
> What exactly do you want to do with fastlane? Uploading to the App Store etc. is obviously out of the question as this requires a developer account, but everything else should work as normal.

em, I want to build proj  and export ipa for iPad/iPhone by fastlane.  but I only have a personal account.

**Comment by janpio** [comment]
Yes, and that doesn't work right now? `gym` doesn't really need your Apple ID, it just needs a working Xcode on the machine as far as I know. (It gets interesting when talking about certificates... how does that work for private accounts?)

**Comment by huos3203** [comment]
> Yes, and that doesn't work right now? `gym` doesn't really need your Apple ID, it just needs a working Xcode on the machine as far as I know. (It gets interesting when talking about certificates... how does that work for private accounts?)

emm, I want to do that on client : 
e.g: ssh to remote  server -> fastlane comandline ->  ipa -> upload this ipa to file server ->  install iPad

**Comment by janpio** [comment]
Exactly, but how do you handle certificates with this private account in Xcode? You usually need a developer account to be able to create certificates.

**Comment by rickclephas** [comment]
Xcode automatically manages the certificates and provisioning profiles for a personal account.
According to the docs you will need to pass the `-allowProvisioningUpdates` option to `xcodebuild` via the `export_xcargs` option of gym.

https://docs.fastlane.tools/codesigning/xcode-project/#xcode-9-and-up

**Comment by huos3203** [comment]
> Xcode automatically manages the certificates and provisioning profiles for a personal account.
> According to the docs you will need to pass the `-allowProvisioningUpdates` option to `xcodebuild` via the `export_xcargs` option of gym.
> 
> https://docs.fastlane.tools/codesigning/xcode-project/#xcode-9-and-up

Thanks very much!!
