### ISSUE TITLE
Pilot always timeout when uploading to TestFlight

### ISSUE THREAD

**Issue by bentahyar** [fastlane/fastlane#15251]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When trying to upload my application to testflight using fastlane via Travis CI, it always times out. Here is my configuration for pilot in fastlane
`pilot(
      ipa:"MY_PATH_TO_IPA",
      username: "MY_USERNAME",
      team_id: "MY_TEAM_ID",
      team_name: "MY_TEAM_NAME",
      itc_provider: "MY_ITC_PROVIDER",
      app_identifier: "MY_APP_ID",
      apple_id: "MY_APPLE_ID",
      skip_waiting_for_build_processing: true,
      skip_submission: true
    )`
I have tried searching through the internet and found nothing on why it always timeout.

For notes, my step in lane is:
- sync_code_signing
- gym
- pilot
- upload_symbols_to_crashlytics
- slack

(sync_code_signing & gym works as intended)

##### Complete output when running fastlane, including the stack trace and command used
The output of timeout is 
`The job exceeded the maximum time limit for jobs, and has been terminated.`
Because 2 hours is the limitation for building, the build time out

**Comment by janpio** [comment]
That seems to be a limitation of Travis, not fastlane, right?
Can you upload locally the same app much faster?

**Comment by bentahyar** [comment]
but how come pilot takes 2 hours to upload to testflight?

if so, can i speed up the process?

**Comment by janpio** [comment]
I don't know. 

I asked you a question to be able to understand this better.

**Comment by bentahyar** [comment]
oh sorry i skipped the last message

yes i can upload much faster locally @janpio

**Comment by janpio** [comment]
Hm, so `pilot` is slower on Travis than on your local machine?

**Comment by bentahyar** [comment]
@janpio yess apparently...

should i use deliver instead? because my purpose is only to upload it to app store connect

**Comment by janpio** [comment]
Both use the same tool in the background, so it shouldn't matter.

**Comment by bentahyar** [comment]
update on this I can successfully upload my app to testflight using local machine, is there anything I should do to make it work on Travis? @JaniJegoroff

**Comment by janpio** [comment]
There is a `setup_travis` method, but I am not aware of any work it is doing for pilot/Testflight.
