### ISSUE TITLE
Unauthorised access when trying to upload to testflight

### ISSUE THREAD

**Issue by arthur798** [fastlane/fastlane#15264]
### Issue Description

So I am getting unauthorized access when trying to upload ios app to testflight, it started happening a few days ago and sometimes it lets me upload the build and sometimes I get the above error, not sure what could be the cause of this as it looks like it's login in normally to apple store connect. 
##### Complete output when running fastlane, including the stack trace and command used
```
[14:00:46]: Driving the lane 'ios upload_testflight' 🚀
[14:00:46]: ------------------------
[14:00:46]: --- Step: testflight ---
[14:00:46]: ------------------------
[14:00:46]: Login to App Store Connect (dasdasda)
[14:00:47]: Login successful
+------------------------------------+--------------------------------------+
|                               Lane Context                                |
+------------------------------------+--------------------------------------+
| PLATFORM_NAME                      | ios                                  |
| LANE_NAME                          | ios upload_testflight                |
| SIGH_PROFILE_TYPE                  | app-store                            |
| MATCH_PROVISIONING_PROFILE_MAPPING | {"app"=>"match      |
|                                    | app",      |
|                                    | "app2"=>"match app2"}                   |
+------------------------------------+--------------------------------------+
[14:00:47]: Unauthorized Access

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | testflight             | 776         |
| 2    | appicon                | 0           |
| 3    | security               | 0           |
|      | unlock-keychain -p     |             |
|      | Av60B60accM9p69k17rLQ  |             |
|      | 879pC7B0Ntb            |             |
| 4    | security               | 0           |
|      | unlock-keychain -p     |             |
|      | Av60B60accM9p69k17rLQ  |             |
|      | 879pC7B0Ntb            |             |
| 5    | match                  | 14          |
| 6    | security               | 0           |
|      | unlock-keychain -p     |             |
|      | Av60B60accM9p69k17rLQ  |             |
|      | 879pC7B0Ntb            |             |
| 7    | security               | 0           |
|      | unlock-keychain -p     |             |
|      | Av60B60accM9p69k17rLQ  |             |
|      | 879pC7B0Ntb            |             |
| 8    | resign                 | 40          |
| 9    | testflight             | 912         |
| 10   | testflight             | 804         |
| 11   | testflight             | 849         |
| 12   | testflight             | 833         |
| 13   | testflight             | 793         |
| 14   | testflight             | 816         |
| 15   | testflight             | 787         |
| 16   | testflight             | 805         |
| 17   | appicon                | 0           |
| 18   | security               | 0           |
|      | unlock-keychain -p     |             |
|      | Av60B60accM9p69k17rLQ  |             |
|      | 879pC7B0Ntb            |             |
| 19   | security               | 0           |
|      | unlock-keychain -p     |             |
|      | Av60B60accM9p69k17rLQ  |             |
|      | 879pC7B0Ntb            |             |
| 20   | match                  | 22          |
| 21   | security               | 0           |
|      | unlock-keychain -p     |             |
|      | Av60B60accM9p69k17rLQ  |             |
|      | 879pC7B0Ntb            |             |
| 22   | security               | 0           |
|      | unlock-keychain -p     |             |
|      | Av60B60accM9p69k17rLQ  |             |
|      | 879pC7B0Ntb            |             |
| 23   | resign                 | 40          |
| 💥   | testflight             | 1           |
| 💥   | testflight             | 1           |
| 💥   | testflight             | 1           |
| 27   | appicon                | 0           |
| 28   | security               | 0           |
|      | unlock-keychain -p     |             |
|      | Av60B60accM9p69k17rLQ  |             |
|      | 879pC7B0Ntb            |             |
| 29   | security               | 0           |
|      | unlock-keychain -p     |             |
|      | Av60B60accM9p69k17rLQ  |             |
|      | 879pC7B0Ntb            |             |
| 30   | match                  | 9           |
| 31   | security               | 0           |
|      | unlock-keychain -p     |             |
|      | Av60B60accM9p69k17rLQ  |             |
|      | 879pC7B0Ntb            |             |
| 32   | security               | 0           |
|      | unlock-keychain -p     |             |
|      | Av60B60accM9p69k17rLQ  |             |
|      | 879pC7B0Ntb            |             |
| 33   | resign                 | 39          |
| 💥   | testflight             | 1           |
| 💥   | testflight             | 1           |
+------+------------------------+-------------+

[14:00:47]: fastlane finished with errors
```

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                        |
| --------------------------- | -------------------------------------------- |
| OS                          | 10.14.2                                      |
| Ruby                        | 2.5.3                                        |
| Bundler?                    | true                                         |
| Git                         | git version 2.23.0                           |
| Installation Source         | ~/apps/shared/bundle/ruby/2.5.0/bin/fastlane |
| Host                        | Mac OS X 10.14.2 (18C54)                     |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.3/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2s  28 May 2019                  |
| Is contained                | false                                        |
| Is homebrew                 | false                                        |
| Is installed via Fabric.app | false                                        |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/  |
| Xcode Version               | 10.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# default_platform(:ios)

platform :ios do

  lane :code_sign do |options|

    unless options[:ipa]
      next
    end

    unless options[:bundle_id]
      next
    end

    unless options[:build_type]
      next
    end

    sh("security unlock-keychain -p #{ENV['MAC_USER_PASSWORD']} ~/Library/Keychains/login.keychain-db")
    sh("security unlock-keychain -p #{ENV['MAC_USER_PASSWORD']} ~/Library/Keychains/login.keychain")

    # Sync certificates and profiles
    # Creates if necessary
    match(
      force_for_new_devices: true,
      app_identifier: options[:bundle_id],
      type: options[:build_type],
      keychain_password: ENV['MAC_USER_PASSWORD']
    )

    # Get downloaded profile file path
    profile_path_env_var = "sigh_#{options[:bundle_id]}_#{options[:build_type]}_profile-path"
    profile_path = ENV[profile_path_env_var]

    sh("security unlock-keychain -p #{ENV['MAC_USER_PASSWORD']} ~/Library/Keychains/login.keychain-db")
    sh("security unlock-keychain -p #{ENV['MAC_USER_PASSWORD']} ~/Library/Keychains/login.keychain")

    # Re code sign .ipa
    resign(
      ipa: options[:ipa],
      signing_identity: "iPhone Distribution: Lavatech Limited (QRT6JJ823U)",
      provisioning_profile: profile_path,
      use_app_entitlements: true,
      bundle_id: options[:bundle_id],
      display_name: options[:display_name]
    )

  end

  lane :update_app_icon do |options|

    unless options[:xcassets_path]
      next
    end

    unless options[:appicon_image_path]
      next
    end

    appicon(
      appicon_devices: [:ipad, :iphone, :ios_marketing],
      appicon_image_file: options[:appicon_image_path],
      appicon_path: options[:xcassets_path]
    )

  end

  lane :upload_testflight do |options|

    testflight(
      ipa: options[:ipa],
      skip_submission: true,
      skip_waiting_for_build_processing: true,
      verbose: true
    )

  end

  lane :create_pem do |options|

    unless options[:bundle_id]
      next
    end

    unless options[:output_path]
      next
    end

    pem(
      app_identifier: options[:bundle_id],
      output_path: options[:output_path],
      force: true
    )

  end

end


platform :android do

  lane :update_android_app_icon do |options|

    unless options[:appicon_image_file]
      next
    end

    unless options[:appicon_path]
      next
    end

    android_appicon(
        appicon_image_file: options[:appicon_image_file],
        appicon_icon_types: [:launcher],
        # appicon_path: 'app/res/mipmap'
        appicon_path: options[:appicon_path]
    )

  end

  lane :upload_appcenter do |options|

    unless options[:apk]
      next
    end

    unless options[:app_name]
      next
    end

    appcenter_upload(
        app_name: options[:app_name],
        apk: options[:apk]
    )

  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
apple_id("email") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.129.0 | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status      |
| ------------------------- | ------- | ------------------ |
| fastlane-plugin-appcenter | 1.3.0   | 🚫 Update available |
| fastlane-plugin-appicon   | 0.14.1  | ✅ Up-To-Date       |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| bundler                   | 2.0.2        |
| rake                      | 12.3.3       |
| CFPropertyList            | 3.0.1        |
| concurrent-ruby           | 1.1.5        |
| i18n                      | 1.6.0        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 5.2.3        |
| builder                   | 3.2.3        |
| erubi                     | 1.8.0        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.4       |
| rails-dom-testing         | 2.0.3        |
| crass                     | 1.0.4        |
| loofah                    | 2.2.3        |
| rails-html-sanitizer      | 1.2.0        |
| actionview                | 5.2.3        |
| rack                      | 2.0.7        |
| rack-test                 | 1.1.0        |
| actionpack                | 5.2.3        |
| nio4r                     | 2.4.0        |
| websocket-extensions      | 0.1.4        |
| websocket-driver          | 0.7.1        |
| actioncable               | 5.2.3        |
| globalid                  | 0.4.2        |
| activejob                 | 5.2.3        |
| mini_mime                 | 1.0.2        |
| mail                      | 2.7.1        |
| actionmailer              | 5.2.3        |
| activejob-status          | 0.1.5        |
| activemodel               | 5.2.3        |
| arel                      | 9.0.0        |
| activerecord              | 5.2.3        |
| mimemagic                 | 0.3.3        |
| marcel                    | 0.3.3        |
| activestorage             | 5.2.3        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| net-ssh                   | 5.2.0        |
| net-scp                   | 2.0.0        |
| sshkit                    | 1.20.0       |
| airbrussh                 | 1.3.3        |
| rubyzip                   | 1.2.3        |
| apktools                  | 0.7.2        |
| atomos                    | 0.1.3        |
| awesome_print             | 1.8.0        |
| aws-eventstream           | 1.0.3        |
| aws-partitions            | 1.206.0      |
| aws-sigv4                 | 1.1.0        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.64.0       |
| aws-sdk-kms               | 1.24.0       |
| aws-sdk-s3                | 1.46.0       |
| babosa                    | 1.0.2        |
| bcrypt                    | 3.1.13       |
| bcrypt_pbkdf              | 1.0.1        |
| msgpack                   | 1.3.1        |
| bootsnap                  | 1.4.4        |
| capistrano                | 3.11.0       |
| capistrano-bundler        | 1.6.0        |
| capistrano-figaro-yml     | 1.0.5        |
| capistrano-passenger      | 0.2.0        |
| puma                      | 3.12.1       |
| capistrano3-puma          | 3.1.1        |
| numerizer                 | 0.1.1        |
| chronic_duration          | 0.10.6       |
| claide                    | 1.0.3        |
| coffee-script-source      | 1.12.2       |
| execjs                    | 2.7.0        |
| coffee-script             | 2.4.1        |
| method_source             | 0.9.2        |
| thor                      | 0.20.3       |
| railties                  | 5.2.3        |
| coffee-rails              | 4.2.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| connection_pool           | 2.2.2        |
| safe_yaml                 | 1.0.5        |
| crack                     | 0.4.3        |
| daemons                   | 1.3.1        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| delayed_job               | 4.1.8        |
| delayed_job_active_record | 4.1.4        |
| orm_adapter               | 0.5.0        |
| responders                | 3.0.0        |
| warden                    | 1.2.8        |
| devise                    | 4.7.0        |
| diff-lcs                  | 1.3          |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| ed25519                   | 1.2.4        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.66.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.1        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-appcenter | 1.3.0        |
| fastlane-plugin-appicon   | 0.14.1       |
| ffi                       | 1.11.1       |
| figaro                    | 1.1.1        |
| hashdiff                  | 1.0.0        |
| httparty                  | 0.16.4       |
| jbuilder                  | 2.9.1        |
| jquery-rails              | 4.3.5        |
| sprockets                 | 3.7.2        |
| sprockets-rails           | 3.2.1        |
| rails                     | 5.2.3        |
| loaf                      | 0.8.1        |
| pg                        | 1.1.4        |
| progress_job              | 0.0.4        |
| rack-protection           | 2.0.7        |
| rb-fsevent                | 0.10.3       |
| rb-inotify                | 0.10.0       |
| redis                     | 4.1.2        |
| rspec-support             | 3.8.2        |
| rspec-core                | 3.8.2        |
| rspec-expectations        | 3.8.4        |
| rspec-mocks               | 3.8.1        |
| rspec-rails               | 3.8.2        |
| sass-listen               | 4.0.0        |
| sass                      | 3.7.4        |
| tilt                      | 2.0.9        |
| sass-rails                | 5.1.0        |
| sidekiq                   | 5.2.7        |
| sidekiq-status            | 1.1.4        |
| turbolinks-source         | 5.2.0        |
| turbolinks                | 5.2.0        |
| uglifier                  | 4.1.20       |
| webmock                   | 3.6.2        |
</details>

*generated on:* **2019-09-03**
</details>

**Comment by janpio** [comment]
Uh, that output is not helpful. Can you run with `--verbose` and see if this outputs something more helpful?

**Comment by arthur798** [comment]
Nothing helpful actually however if I redeploy ruby on fails with bundle exec cap production deploy it works fine. Is it caching something? Everyday I just need to re-deploy it for it to work again
