### ISSUE TITLE
Prompt for passphrase of rsa key is not supported

### ISSUE THREAD

**Issue by filip982** [fastlane/fastlane#15268]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.23.0                          |
| Installation Source         | ~/.rbenv/versions/2.6.3/bin/fastlane        |
| Host                        | Mac OS X 10.14.6 (18G87)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.3/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2s  28 May 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.3                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_require 'dotenv'

before_all do
    Dotenv.overload '../.env'
end

default_platform(:ios)

platform :ios do
  desc "Update certificates"
  lane :update_certs do |options|
	# Set default type for local builds
    type = "development"
    
    # Read in value in case the user has specified input params
  	if options[:type]
      
      if options[:type].to_s.empty?
        UI.user_error!("The parameter type is not valid (empty or nil)!")
      end
      
  		type = options[:type]
  	end
    
    match(
      type: type,
      force_for_new_devices: true
    )
  end

  error do |lane, exception|
  	puts exception.message
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier ENV['APP_ID']
apple_id "______"
team_id "_______"

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.130.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                        | Version | Update-Status |
| ----------------------------- | ------- | ------------- |
| fastlane-plugin-download_file | 1.0.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.3.0        |
| bundler                       | 1.17.2       |
| etc                           | 1.0.1        |
| forwardable                   | 1.2.0        |
| CFPropertyList                | 3.0.1        |
| concurrent-ruby               | 1.1.5        |
| i18n                          | 0.9.5        |
| minitest                      | 5.11.3       |
| thread_safe                   | 0.3.6        |
| tzinfo                        | 1.2.5        |
| activesupport                 | 4.2.11.1     |
| public_suffix                 | 2.0.5        |
| addressable                   | 2.7.0        |
| atomos                        | 0.1.3        |
| babosa                        | 1.0.2        |
| claide                        | 1.0.3        |
| fuzzy_match                   | 2.0.4        |
| nap                           | 1.1.0        |
| cocoapods-core                | 1.7.5        |
| cocoapods-deintegrate         | 1.0.4        |
| cocoapods-downloader          | 1.2.2        |
| cocoapods-plugins             | 1.0.0        |
| cocoapods-search              | 1.0.0        |
| cocoapods-stats               | 1.1.0        |
| netrc                         | 0.11.0       |
| cocoapods-trunk               | 1.3.1        |
| cocoapods-try                 | 1.1.0        |
| colored2                      | 3.1.2        |
| escape                        | 0.0.4        |
| fourflusher                   | 2.3.1        |
| gh_inspector                  | 1.1.3        |
| molinillo                     | 0.6.6        |
| ruby-macho                    | 1.4.0        |
| nanaimo                       | 0.2.6        |
| xcodeproj                     | 1.12.0       |
| cocoapods                     | 1.7.5        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| declarative                   | 0.0.10       |
| declarative-option            | 0.1.0        |
| digest-crc                    | 0.4.1        |
| unf_ext                       | 0.0.7.6      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| dotenv                        | 2.7.5        |
| emoji_regex                   | 1.0.1        |
| excon                         | 0.66.0       |
| multipart-post                | 2.0.0        |
| faraday                       | 0.15.4       |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.6        |
| faraday_middleware            | 0.13.1       |
| fastimage                     | 2.1.5        |
| jwt                           | 2.1.0        |
| memoist                       | 0.16.0       |
| multi_json                    | 1.13.1       |
| os                            | 1.0.1        |
| signet                        | 0.11.0       |
| googleauth                    | 0.6.7        |
| httpclient                    | 2.8.3        |
| mime-types-data               | 3.2019.0331  |
| mime-types                    | 3.2.2        |
| uber                          | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| google-api-client             | 0.23.9       |
| google-cloud-env              | 1.2.1        |
| google-cloud-core             | 1.3.1        |
| google-cloud-storage          | 1.16.0       |
| json                          | 2.2.0        |
| mini_magick                   | 4.9.5        |
| multi_xml                     | 0.6.0        |
| plist                         | 3.5.0        |
| rubyzip                       | 1.2.3        |
| security                      | 0.1.3        |
| naturally                     | 2.2.0        |
| simctl                        | 1.6.5        |
| slack-notifier                | 2.3.2        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.6.0        |
| terminal-table                | 1.8.0        |
| tty-screen                    | 0.7.0        |
| tty-cursor                    | 0.7.0        |
| tty-spinner                   | 0.9.1        |
| word_wrap                     | 1.0.0        |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| xcpretty-travis-formatter     | 1.0.0        |
| fastlane-plugin-download_file | 1.0.0        |
</details>

*generated on:* **2019-09-04**
</details>

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by janpio** [comment]
What prompt? What passphrase? What key?

**Comment by filip982** [comment]
So when SSH key is used on github and passphrase have to be entered every time manually. If fastlane command includes cloning something then is stuck in the middle of that process, not showing any error or response.

**Comment by janpio** [comment]
Ok, so this is about one of the `git` actions, right?
Can you share a simple example?
