### ISSUE TITLE
Verification problem, I have program password

### ISSUE THREAD

**Issue by fdjkpoi** [fastlane/fastlane#15261]
![QQ图片20190903110620](https://user-images.githubusercontent.com/52192093/64141514-e95b2380-ce3a-11e9-8f11-fb1cc02155ea.png)
I want to re-enter the password, how to clear the account, every time I enter the account, skip the password, need to enter the verification code.

**Comment by fdjkpoi** [comment]
I have Application specific passwords, and I want to use them to log in.

**Comment by janpio** [comment]
> every time I enter the account, skip the password, need to enter the verification code.

What does that mean? The screenshot you posted asks for the 6 digit 2FA code to be entered.



> I have Application specific passwords, and I want to use them to log in.

Ok, follow the documentation on how to use it. What tool or action exactly do you want to use? As you deleted the issue template instead of filling it, we have no way of knowing what you are trying to do.
