### ISSUE TITLE
Can't upload In-App Purchase Items

### ISSUE THREAD

**Issue by MatMarras** [fastlane/fastlane#15279]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm using a Ruby script to create In-App Purchase items but ITC is firing this error:
**ITC.apps.iap.20.familyDetails.localeCode.unsupportedError**

We can't understand why, there is no information about this error in the entire repo. Agreements for Paid iOS application are ok. We started using this script at least one year ago. Two days ago it stopped working. 
##### Command executed

```
app.in_app_purchases.create!(
			type: Spaceship::Tunes::IAPType::NON_CONSUMABLE, 
			versions: {
			  "it-IT" => {
			    name: productName,
			    description: productDescription
			  }
			},
			reference_name: productName,
			product_id: productIdentifier,
			cleared_for_sale: true,
			review_notes: "",
			review_screenshot: screenPath, 
			pricing_intervals: 
			  [
			    {
			      country: "WW",
			      begin_date: nil,
			      end_date: nil,
			      tier: productTier
			    }
			  ] 
			)
```
##### Complete output when running fastlane, including the stack trace and command used

```
ITC.apps.iap.20.familyDetails.localeCode.unsupportedError ITC.apps.iap.20.familyDetails.localeCode.unsupportedError
/Users/user/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.130.0/spaceship/lib/spaceship/tunes/tunes_client.rb:230:in `handle_itc_response'
/Users/user/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.130.0/spaceship/lib/spaceship/tunes/tunes_client.rb:1400:in `create_iap!'
/Users/user/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-2.130.0/spaceship/lib/spaceship/tunes/iap.rb:76:in `create!'
```
<details>
</details>

### Environment

**STACK**
```
 Key                         | Value                                        |
| --------------------------- | -------------------------------------------- |
| OS                          | 10.14.5                                      |
| Ruby                        | 2.3.0                                        |
| Bundler?                    | false                                        |
| Git                         | git version 2.7.4 (Apple Git-66)             |
| Installation Source         | ~/.rvm/rubies/ruby-2.3.0/bin/fastlane        |
| Host                        | Mac OS X 10.14.5 (18F132)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.0/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2r  26 Feb 2019                  |
| Is contained                | false                                        |
| Is homebrew                 | false                                        |
| Is installed via Fabric.app | false                                        |
| Xcode Path                  | /Applications/Xcode7.app/Contents/Developer/ |
| Xcode Version               | 7.3.1                                        |
```

**Fastlane gems**

```
| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.130.0 | ✅ Up-To-Date  |
```

I have also tried with Ruby 2.2.3  and with Xcode 10 but is firing the same error.

**Comment by wtrd1234** [comment]
i meet the same error now. and i need help too.

here is my more infomation. 
i print it from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.130.0/spaceship/lib/spaceship/tunes/tunes_client.rb:1401:in `create_iap!' . the parameter "raw" .
 
i notice there is "ITC.apps.iap.20.familyDetails.localeCode.unsupportedError" in the block of name "com.newxx6". 
i tried to change  "com.newxx6" to "comnewxx6", tried to change name same to productID

but they didn't work.

-----

raw = {
	"data" => {
		"sectionErrorKeys" => ["ITC.apps.iap.20.familyDetails.localeCode.unsupportedError"], "sectionInfoKeys" => [], "sectionWarningKeys" => [], "value" => nil, "id" => nil, "adamId" => nil, "appAdamIds" => nil, "familyId" => nil, "addOnType" => "consumable", "isNewsSubscription" => false, "isReplaced" => false, "replacementAdamId" => nil, "referenceName" => {
			"value" => "com.newxx6", "isEditable" => false, "isRequired" => false, "errorKeys" => [], "maxLength" => nil, "minLength" => nil
		}, "productId" => {
			"value" => "com.newxx6", "isEditable" => false, "isRequired" => false, "errorKeys" => [], "maxLength" => nil, "minLength" => nil
		}, "clearedForSale" => {
			"value" => true, "isEditable" => false, "isRequired" => false, "errorKeys" => nil
		}, "pricingDurationType" => nil, "pricingIntervals" => [{
			"value" => {
				"tierStem" => "1", "priceTierEffectiveDate" => nil, "priceTierEndDate" => nil, "country" => "WW", "grandfathered" => nil
			},
			"isEditable" => false,
			"isRequired" => false,
			"errorKeys" => []
		}], "ungrandfatheredIntervals" => nil, "freeTrialDurationType" => nil, "bonusPeriodDurationType" => nil, "versions" => [{
			"id" => nil,
			"details" => {
				"value" => [{
					"value" => {
						"id" => nil, "name" => {
							**"value" => "com.newxx6", "isEditable" => false, "isRequired" => false, "errorKeys" => ["ITC.apps.iap.20.familyDetails.localeCode.unsupportedError"], "maxLength" => nil, "minLength" => nil**
						}, "description" => {
							"value" => "After Pay Success You can get 60 Gems", "isEditable" => false, "isRequired" => false, "errorKeys" => [], "maxLength" => nil, "minLength" => nil
						}, "publicationName" => nil, "localeCode" => "zh-CN", "status" => nil
					},
					"isEditable" => false,
					"isRequired" => false,
					"errorKeys" => nil,
					"isDeletable" => false
				}], "isEditable" => true, "isRequired" => false, "errorKeys" => nil
			},
			"contentHosting" => nil,
			"contentHostingData" => nil,
			"reviewNotes" => {
				"value" => " ", "isEditable" => false, "isRequired" => false, "errorKeys" => [], "maxLength" => nil, "minLength" => nil
			},
			"reviewScreenshot" => {
				"value" => {
					"assetToken" => "Purple123/v4/29/de/f7/29def7c8-db92-e4f9-562b-341bb0b3584d/pr_source.jpg", "sortOrder" => 0, "type" => "MZPFT.SortedScreenShot", "size" => 42312, "width" => 640, "height" => 920, "checksum" => "a1cdf05db694b0be2a8cd91eca91f51e", "url" => nil, "thumbNailUrl" => nil, "originalFileName" => "ftl_a1cdf05db694b0be2a8cd91eca91f51e_6.jpg"
				}, "isEditable" => false, "isRequired" => false, "errorKeys" => []
			},
			"merch" => {
				"images" => [{
					"id" => nil,
					"image" => {
						"value" => {
							"assetToken" => nil, "originalFileName" => nil, "width" => nil, "height" => nil, "checksum" => nil
						}, "isEditable" => true, "isRequired" => false, "errorKeys" => nil
					},
					"status" => nil
				}], "showByDefault" => true, "isActive" => false
			},
			"status" => nil,
			"canBeSubmitted" => false
		}], "missingRequiredPrivacyPolicyData" => false, "missingRequiredFamilyDetail" => false
	},
	"messages" => {
		"warn" => nil, "info" => nil, "error" => nil
	},
	"statusCode" => "ERROR"
}

**Comment by MatMarras** [comment]
I've successfully uploaded an in-app purchase using Application Loader Version 3.0 (620). Looking at the new [Apple Metadata specification (5.11) ](https://help.apple.com/asc/appsspec/en.lproj/static.html) I see that there is a clarification about the Locale:

> To remove a locale for an in-app purchase that was previously delivered, include the <locales> block in a new delivery and omit the locale you want to remove.

But I don't know if it is fastlane that needs to fix the new metadata specification or not.

**Comment by wtrd1234** [comment]
finally, I found my mistake. 

yes , **the wrong localCode. the wrong localCode. the wrong localCode**. 



my wrong localCode is "zh-CN" , but the correct string is "zh-Hans" in [Language Codes](https://help.apple.com/asc/appsspec/en.lproj/static.html#itce40fff472).

@MatMarras 
I noticed your localCode is "it-IT", but I can't found it on the list. you may change it.

**Comment by ZhLinda** [comment]
> finally, I found my mistake.
> 
> yes , **the wrong localCode. the wrong localCode. the wrong localCode**.
> 
> my wrong localCode is "zh-CN" , but the correct string is "zh-Hans" in [Language Codes](https://help.apple.com/asc/appsspec/en.lproj/static.html#itce40fff472).
> 
> @MatMarras
> I noticed your localCode is "it-IT", but I can't found it on the list. you may change it.

my wrong localCode is "zh-CN" , but the correct string is "zh-Hans" in Language Codes.

this fix my problem , thanks

**Comment by MatMarras** [comment]
> finally, I found my mistake.
> 
> yes , **the wrong localCode. the wrong localCode. the wrong localCode**.
> 
> my wrong localCode is "zh-CN" , but the correct string is "zh-Hans" in [Language Codes](https://help.apple.com/asc/appsspec/en.lproj/static.html#itce40fff472).
> 
> @MatMarras
> I noticed your localCode is "it-IT", but I can't found it on the list. you may change it.

Yes, that was my error too. Changing from "it-IT" to "it" fix the issue.

Thanks!
