### ISSUE TITLE
Fastlane doesn't seem to be able to find the apk from gradle (Flutter project)

### ISSUE THREAD

**Issue by point-source** [fastlane/fastlane#15278]
### Question Checklist

- [x] Updated fastlane to the latest version
> I am using 2.130.0
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)
> I performed [this search](https://github.com/fastlane/fastlane/issues?utf8=%E2%9C%93&q=is%3Aissue+Couldn%27t+find+any+new+signed+apk+files) but all results are too old to apply to current fastlane/flutter/supply as far as I can tell

#### What tool/action do you have a question about?
`bundle exec fastlane beta` while in a flutter project at appname/android/
> This should build an apk or bundle and upload it to the play store beta track (per my Fastfile)
#### Is this a question about documentation?
No, yes, maybe?
#### Is this a question about a third party plugin? (If so, please go to the plugin repository first)
No

#### Question Description

-I followed these steps exactly (multiple times): https://flutter.dev/docs/deployment/cd
-I have verified that supply can access my google account.
-The iOS version builds and uploads correctly via `bundle exec fastlane beta` while in the appname/ios/ folder
-Running `flutter build --release` succeeds

When I run `bundle exec fastlane beta` while in the appname/android/ folder, it appears to succeed but no apk is uploaded to google. Here is some output which I believe is relevant:

```
[16:14:05]: ▸ > Task :app:buildReleasePreBundle
[16:14:05]: ▸ > Task :app:collectReleaseDependencies
[16:14:05]: ▸ > Task :app:configureReleaseDependencies
[16:14:07]: ▸ > Task :app:packageReleaseBundle
[16:14:07]: ▸ > Task :app:validateSigningRelease UP-TO-DATE
[16:14:07]: ▸ > Task :app:signingConfigWriterRelease UP-TO-DATE
[16:14:11]: ▸ > Task :app:signReleaseBundle
[16:14:11]: ▸ > Task :app:bundleRelease
[16:14:11]: ▸ 288 actionable tasks: 19 executed, 269 up-to-date
[16:14:11]: Couldn't find any new signed apk files...
[16:14:11]: 
[16:14:11]: ----------------------------------
[16:14:11]: --- Step: upload_to_play_store ---
[16:14:11]: ----------------------------------

+-------------------------+-----------------------------------------------------------+
|                             Summary for supply 2.130.0                              |
+-------------------------+-----------------------------------------------------------+
| track                   | beta                                                      |
| package_name            | identifier.redacted                                      |
| metadata_path           | ./fastlane/metadata/android                               |
| json_key                | ../../../api-1234.json |
| skip_upload_apk         | false                                                     |
| skip_upload_aab         | false                                                     |
| skip_upload_metadata    | false                                                     |
| skip_upload_images      | false                                                     |
| skip_upload_screenshots | false                                                     |
| validate_only           | false                                                     |
| check_superseded_tracks | false                                                     |
| timeout                 | 300                                                       |
| deactivate_on_promote   | true                                                      |
+-------------------------+-----------------------------------------------------------+

[16:14:13]: Preparing to upload for language 'en-US'...
[16:14:13]: Uploading image file ./fastlane/metadata/android/en-US/images/featureGraphic.png...
[16:14:15]: Uploading image file ./fastlane/metadata/android/en-US/images/icon.png...
[16:14:18]: Uploading all changes to Google Play...
[16:14:21]: Successfully finished the upload to Google Play

+------+----------------------+-------------+
|             fastlane summary              |
+------+----------------------+-------------+
| Step | Action               | Time (in s) |
+------+----------------------+-------------+
| 1    | default_platform     | 0           |
| 2    | gradle               | 53          |
| 3    | upload_to_play_store | 9           |
+------+----------------------+-------------+

[16:14:21]: fastlane.tools finished successfully 🎉

```

I suspect that `Couldn't find any new signed apk files...` has something to do with the problem.

My env is:

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.23.0                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.6 (18G95)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.3                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Google Play"
  lane :beta do
    gradle(
      task: 'bundle',
      build_type: 'Release',
    )
    upload_to_play_store(track: 'beta')
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("../../../api-1234.json") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("identifier.redacted") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.130.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types                | 3.1          |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| highline                  | 1.7.10       |
| excon                     | 0.66.0       |
| CFPropertyList            | 3.0.1        |
| libxml-ruby               | 3.0.0        |
| plist                     | 3.5.0        |
| fastimage                 | 2.1.7        |
| addressable               | 2.7.0        |
| multi_json                | 1.13.1       |
| os                        | 1.0.1        |
| psych                     | 2.0.8        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.0904  |
| uber                      | 0.1.0        |
</details>

*generated on:* **2019-09-05**
</details>

So ultimately I'm wondering why it isn't finding and uploading the apk and how I can help it or fix it. Thanks!

**Comment by janpio** [comment]
> `Couldn't find any new signed apk files...`

This could happen when an identical signed APK is already present in the output folder where the APK is generated.

Can you run the lane with `--verbose` and see if this gives more helpful output plese?

**Comment by point-source** [comment]
Here is full output with the --verbose flag:

https://pastebin.com/G8eEztDq

**Comment by janpio** [comment]
What happens if you manually run `gradlew bundleRelease -p` in `/Users/user/Documents/GitHub/Company/App/user_app/android/` after deleting the previously genegrated APKs or bundles?

That being said, I am not 100% sure that it can actually deal with bundles automatically!
```
    gradle(
      task: 'bundle',
      build_type: 'Release',
    )
```
Did you check documentation if this should be possible?

**Comment by point-source** [comment]
gradlew output:

```
./gradlew bundleRelease -p ./
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :app
WARNING: API 'variant.getMergeResources()' is obsolete and has been replaced with 'variant.getMergeResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getMergeResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.

> Configure project :receive_sharing_intent
WARNING: API 'variant.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getPackageLibrary(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
288 actionable tasks: 12 executed, 276 up-to-date
```

Regarding my gradle config in fastlane, I originall had this:

```
    gradle(
      task: 'assemble',
      build_type: 'Release',
    )
```

This configuration produced the same error about not finding an apk. I switched to bundle as a troubleshooting step and forgot to change it back but I haven't found it to make a difference. This github issue suggests it should work either way: https://github.com/fastlane/fastlane/issues/15053

**Comment by janpio** [comment]
Yes, the code also confirms this.

Can you output the ENV vars GRADLE_APK_OUTPUT_PATH, GRADLE_ALL_APK_OUTPUT_PATHS or       GRADLE_AAB_OUTPUT_PATH, GRADLE_ALL_AAB_OUTPUT_PATHS between `gradle` and `upload_to_play_store` and see if they contain anything and if those paths and files exist?

**Comment by point-source** [comment]
Sure enough, that seems to be the issue:

```
INFO [2019-09-10 10:49:56.37]: GRADLE_APK_OUTPUT_PATH: 
INFO [2019-09-10 10:49:56.37]: GRADLE_ALL_APK_OUTPUT_PATHS: 
INFO [2019-09-10 10:49:56.37]: GRADLE_AAB_OUTPUT_PATH: 
INFO [2019-09-10 10:49:56.37]: GRADLE_ALL_AAB_OUTPUT_PATHS: 
WARN [2019-09-10 10:49:56.37]: Lane Context:
INFO [2019-09-10 10:49:56.37]: {:DEFAULT_PLATFORM=>:android, :PLATFORM_NAME=>:android, :LANE_NAME=>"android beta", :GRADLE_BUILD_TYPE=>"Release", :GRADLE_ALL_APK_OUTPUT_PATHS=>[], :GRADLE_ALL_AAB_OUTPUT_PATHS=>[]}
```

Not sure why that would be happening though. I have confirmed that there is an apk located at `/build/app/outputs/apk/release/app-release.apk`

**Comment by janpio** [comment]
Interesting, so we will have to look at the code that fills that variable:

https://github.com/fastlane/fastlane/blob/76e0b270ca1e0e4a262d8d0186917c709631513d/fastlane/lib/fastlane/actions/gradle.rb#L81-L89
https://github.com/fastlane/fastlane/blob/76e0b270ca1e0e4a262d8d0186917c709631513d/fastlane/lib/fastlane/actions/gradle.rb#L63-L72

From looking at that, there seems to be an additional `app/` in your path the code is not expecting, true?

**Comment by point-source** [comment]
Yes that is correct. However, if I create a brand new flutter project using `flutter create --ios-language=swift --android-language=kotlin --androidx apktest` and then build it, I get this output:

```
~/D/G/D/apktest> flutter build apk --release
You are building a fat APK that includes binaries for android-arm, android-arm64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Initializing gradle...                                              2.0s
Resolving dependencies...                                           8.3s
Running Gradle task 'assembleRelease'...                                
Calling mockable JAR artifact transform to create file: /Users/user/.gradle/caches/transforms-1/files-1.1/android.jar/9c7c8d0ee1781177dbef0307362a85d0/android.jar with input /Users/user/Library/Android/sdk/platforms/android-28/android.jar
Running Gradle task 'assembleRelease'...                                                                           
Running Gradle task 'assembleRelease'... Done                     175.9s (!)
Built build/app/outputs/apk/release/app-release.apk (10.3MB).
```

So even the flutter defaults place the apk there so as far as I can tell, it isn't something I misconfigured unless there is a setting I am missing on the fastlane side.

**Comment by janpio** [comment]
Can you create a plain Android project and build that and compare? (I don't have a working Android setup here right now)

**Comment by point-source** [comment]
Not sure what you mean. Like a plain kotlin project, not using flutter? I'm not sure that would be especially useful here since my project is written in flutter, but I am happy to try.

**Comment by janpio** [comment]
> Created and built a fresh kotlin project using Android Studio and it placed the apk in `/MyApplication/app/build/outputs/apk/release/app-release.apk` which I believe is consistent with what fastlane expects. So I think perhaps the fastlane code is not currently supporting flutter properly

That matches what I expected, we would have to add these paths to the matcher in the code I linked to above then.

But I noticed that the official guide you linked to above mentions this problem explicitly:

>  Set the apk argument to `../build/app/outputs/apk/release/app-release.apk` to use the apk flutter build already built.

https://flutter.dev/docs/deployment/cd#local-setup (7.)

So this is a known thing, but looking at this path could improve this step a bit and make this additional option unnecessary.

**Comment by point-source** [comment]
🤦 wow. I followed that guide three times. I know how I missed it though, when I got to that step, I would click on `follow the fastlane Android beta deployment guide` and miss the note after that because it began `Your edit could be as simple as` which to me implied that it was sample code / example code. Obviously that's my bad. Thanks for working through it with me.
