### ISSUE TITLE
Could not find any dSYM оn fastlane 2.130.0

### ISSUE THREAD

**Issue by Sega-Zero** [fastlane/fastlane#15270]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Latest fastlane cannot download dSYMs from appstore connect, but it exists.

##### Command executed
```ruby
lane :symbols do
    ENV['plist_version'] = "#{ver_major}.#{ver_minor}.#{build_num}"
    sh('find "../Pods/Target Support Files" -name Info.plist -exec /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $plist_version" {} \;')
 
    download_dsyms(version: ENV['plist_version'], build_number: ENV['plist_version'])
    upload_symbols_to_crashlytics(api_token: ENV["CRASHLYTICS_API_TOKEN"])
  end
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
--- Step: download_dsyms ---
----------------------------
Login to App Store Connect (****)
Login successful
Looking for dSYM files for 'com.app.id' on platform ios v1.0.0 (1.0.0)
Could not find any dSYM for 1.0.0 (1.0.0)
-------------------
--- Step: is_ci ---
-------------------
--------------------------
--- Step: fastlane env ---
--------------------------
$ fastlane env
Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>
### Stack
| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.4                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | ~/.rvm/gems/ruby-2.3.1/bin/fastlane         |
| Host                        | Mac OS X 10.14.4 (18E2034)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.1/lib                |
| OpenSSL Version             | OpenSSL 1.0.2r  26 Feb 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                      |
### System Locale
| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | ru_RU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |
### fastlane files:
<details><summary>`./Appfile`</summary>
```ruby
app_identifier "com.app.id"
apple_id "****"
itc_team_id "[REDACTED]"
team_id "[REDACTED]"
team_name "[REDACTED]"
```
</details>
### fastlane gems
| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.130.0 | ✅ Up-To-Date  |
### Loaded fastlane plugins:
**No plugins Loaded**
<details><summary><b>Loaded gems</b></summary>
| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 1.17.3       |
| CFPropertyList            | 3.0.1        |
| concurrent-ruby           | 1.1.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.11.1     |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.3        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.7.5        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.2.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.4.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| cocoapods                 | 1.7.5        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.66.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.1        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| ffi                       | 1.11.1       |
| mustache                  | 1.1.0        |
| open4                     | 1.3.4        |
| redcarpet                 | 3.5.0        |
| rb-fsevent                | 0.10.3       |
| rb-inotify                | 0.10.0       |
| sass-listen               | 4.0.0        |
| sass                      | 3.7.4        |
| sqlite3                   | 1.4.1        |
| liferaft                  | 0.0.6        |
| xcinvoke                  | 0.3.0        |
| jazzy                     | 0.10.0       |
</details>
*generated on:* **2019-09-04**
</details>
Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅
+------------------+-------------+
|          Lane Context          |
+------------------+-------------+
| DEFAULT_PLATFORM | ios         |
| PLATFORM_NAME    | ios         |
| LANE_NAME        | ios symbols |
+------------------+-------------+
bad URI(is not URI?): 

+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | default_platform                                              | 0           |
| 2    | git_branch                                                    | 0           |
| 3    | awk -F '=' '/PRODUCT_BUNDLE_IDENTIFIER = com.mango/ {print $2 | 0           |
| 4    | is_ci                                                         | 0           |
| 5    | clear_derived_data                                            | 0           |
| 6    | is_ci                                                         | 0           |
| 7    | delete_keychain                                               | 0           |
| 8    | create_keychain                                               | 0           |
| 9    | update_app_identifier                                         | 0           |
| 8    | find "../Pods/Target Support Files" -name Info.plist -exec /u | 0           |
| 💥   | download_dsyms                                                | 5           |
| 10   | is_ci                                                         | 0           |
| 11   | fastlane env                                                  | 3           |
+------+---------------------------------------------------------------+-------------+

fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Facing bad [!] bad URI(is not URI?): issue. 
    https://github.com/fastlane/fastlane/issues/14916 [closed] 16 💬
    2 weeks ago

➡️  [download_dsyms] Do not attempt to download Dsyms if the dsym_url is missing
    https://github.com/fastlane/fastlane/pull/15260 [closed] 3 💬
    18 hours ago

➡️  App Center deployment fails due to bad uri when app has spaces in the name
    https://github.com/fastlane/fastlane/issues/14882 [closed] 2 💬
    3 weeks ago

and 15 more at: https://github.com/fastlane/fastlane/search?q=bad%20URI%28is%20not%20URI%3F%29%3A%20&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/user/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/uri/rfc3986_parser.rb:18:in `rescue in split': [!] bad URI(is not URI?):  (URI::InvalidURIError)
	from /Users/user/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/uri/rfc3986_parser.rb:15:in `split'
	from /Users/user/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/uri/rfc3986_parser.rb:73:in `parse'
	from /Users/user/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/uri/common.rb:227:in `parse'
	from /Users/user/.rvm/gems/ruby-2.3.1/gems/fastlane-2.130.0/fastlane/lib/fastlane/actions/download_dsyms.rb:146:in `download_file'
	from /Users/user/.rvm/gems/ruby-2.3.1/gems/fastlane-2.130.0/fastlane/lib/fastlane/actions/download_dsyms.rb:128:in `download'
	from /Users/user/.rvm/gems/ruby-2.3.1/gems/fastlane-2.130.0/fastlane/lib/fastlane/actions/download_dsyms.rb:116:in `block (2 levels) in run'
	from /Users/user/.rvm/gems/ruby-2.3.1/gems/fastlane-2.130.0/fastlane/lib/fastlane/actions/download_dsyms.rb:78:in `each'
	from /Users/user/.rvm/gems/ruby-2.3.1/gems/fastlane-2.130.0/fastlane/lib/fastlane/actions/download_dsyms.rb:78:in `block in run'
	from /Users/user/.rvm/gems/ruby-2.3.1/gems/fastlane-2.130.0/fastlane/lib/fastlane/actions/download_dsyms.rb:62:in `each'
	from /Users/user/.rvm/gems/ruby-2.3.1/gems/fastlane-2.130.0/fastlane/lib/fastlane/actions/download_dsyms.rb:62:in `run'
	from /Users/user/.rvm/gems/ruby-2.3.1/gems/fastlane-2.130.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
	from /Users/user/.rvm/gems/ruby-2.3.1/gems/fastlane-2.130.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/user/.rvm/gems/ruby-2.3.1/gems/fastlane-2.130.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
	from /Users/user/.rvm/gems/ruby-2.3.1/gems/fastlane-2.130.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/user/.rvm/gems/ruby-2.3.1/gems/fastlane-2.130.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/user/.rvm/gems/ruby-2.3.1/gems/fastlane-2.130.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/user/.rvm/gems/ruby-2.3.1/gems/fastlane-2.130.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
	from Fastfile:325:in `block (2 levels) in parsing_binding'
	from /Users/user/.rvm/gems/ruby-2.3.1/gems/fastlane-2.130.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/user/.rvm/gems/ruby-2.3.1/gems/fastlane-2.130.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/user/.rvm/gems/ruby-2.3.1/gems/fastlane-2.130.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/user/.rvm/gems/ruby-2.3.1/gems/fastlane-2.130.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/user/.rvm/gems/ruby-2.3.1/gems/fastlane-2.130.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/user/.rvm/gems/ruby-2.3.1/gems/fastlane-2.130.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/user/.rvm/gems/ruby-2.3.1/gems/fastlane-2.130.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/user/.rvm/gems/ruby-2.3.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/user/.rvm/gems/ruby-2.3.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/user/.rvm/gems/ruby-2.3.1/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/user/.rvm/gems/ruby-2.3.1/gems/fastlane-2.130.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/user/.rvm/gems/ruby-2.3.1/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/user/.rvm/gems/ruby-2.3.1/gems/fastlane-2.130.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	from /Users/user/.rvm/gems/ruby-2.3.1/gems/fastlane-2.130.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/user/.rvm/gems/ruby-2.3.1/gems/fastlane-2.130.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Users/user/.rvm/gems/ruby-2.3.1/gems/fastlane-2.130.0/bin/fastlane:23:in `<top (required)>'
	from /Users/user/.rvm/gems/ruby-2.3.1/bin/fastlane:23:in `load'
	from /Users/user/.rvm/gems/ruby-2.3.1/bin/fastlane:23:in `<main>'
	from /Users/user/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:24:in `eval'
	from /Users/user/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:24:in `<main>'
 </pre>
</details>

**Comment by janpio** [comment]
Does the same command with `--verbose` give more information?

**Comment by Sega-Zero** [comment]
Not much.
```ruby
INFO [2019-09-04 14:31:12.96]: ----------------------------
INFO [2019-09-04 14:31:12.96]: --- Step: download_dsyms ---
INFO [2019-09-04 14:31:12.96]: ----------------------------
INFO [2019-09-04 14:31:13.11]: Login to App Store Connect (****)
Reading keychain entry, because either user or password were empty
Loading session from '/Users/user/.fastlane/spaceship/****/cookie'
Available session is not valid any more. Continuing with normal login.
Looking for App Store Connect Team with ID [REDACTED]
INFO [2019-09-04 14:31:16.27]: Login successful
INFO [2019-09-04 14:31:16.98]: Looking for dSYM files for 'com.app.id' on platform ios v1.x.x (1.x.x)
DEBUG [2019-09-04 14:31:19.05]: Found train (version): 1.x.y , comparing to supplied version: 1.x.x
DEBUG [2019-09-04 14:31:19.05]: Version 1.x.x doesn't match: 1.x.y
<lots of similar records>
DEBUG [2019-09-04 14:31:19.09]: Found train (version): 1.x.x , comparing to supplied version: 1.x.x
DEBUG [2019-09-04 14:31:19.61]: Found build version: 1.x.x , comparing to supplied build_number: 1.x.x
DEBUG [2019-09-04 14:31:19.61]: Build_version: 1.x.x matches 1.x.x, grabbing dsym_url
DEBUG [2019-09-04 14:31:20.56]: dsym_url: 
ERROR [2019-09-04 14:31:20.56]: Could not find any dSYM for 1.x.x (1.x.x)
INFO [2019-09-04 14:31:20.56]: -------------------
INFO [2019-09-04 14:31:20.56]: --- Step: is_ci ---
INFO [2019-09-04 14:31:20.56]: -------------------
INFO [2019-09-04 14:31:20.57]: --------------------------
INFO [2019-09-04 14:31:20.57]: --- Step: fastlane env ---
INFO [2019-09-04 14:31:20.57]: --------------------------

```

Looks like `dsym_url` is empty

**Comment by Sega-Zero** [comment]
I've checked Appstore Connect and this version indeed does not have a download link, but it also says this build contains symbols. Previous builds contains the download link, but it was built with 2.123.0 and 2.129.0 versions.
Maybe some kind of regression occured?

**Comment by SoftwareEngineerChris** [comment]
We're also facing this issue - an old build of ours from App Store Connect doesn't have a dSYM URL so its bailing out. Working round this by using the `min_version` e.g. `download_dsyms(min_version: "1.2.3")` to ignore that build.

**Comment by SoftwareEngineerChris** [comment]
Looks like this was fixed anyhow with PR #15260 - thanks folks!

**Comment by talasnaly** [comment]
> There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.
> Please make sure to update to the latest `fastlane` version and check if that solves the issue. Let us know if that works for you by adding a comment 👍
> Friendly reminder: contributions are always welcome! Check out [CONTRIBUTING.md](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md) for more information on how to help with `fastlane` and feel free to tackle this issue yourself 💪

Your blog is simply amazing, congratulations on your great work!

**Comment by rogerluan** [comment]
Closing since https://github.com/fastlane/fastlane/pull/15260 was merged 👍
