### ISSUE TITLE
Run tests on multiple physical devices. 

### ISSUE THREAD

**Issue by kincade71** [fastlane/fastlane#15272]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Scan

Yes

No

#### Question Description

How do your tests from Fastlane on multiple physical devices? 
The param Devices or Device only runs the simulator.

**Comment by rickclephas** [comment]
From looking at the source code the `device` and `devices` parameters will indeed only work for simulators.

I didn't test this myself but you should be able to use a physical device with the `destination` parameter.

```ruby
lane :tests do
  run_tests(workspace: "Example.xcworkspace",
            destination: ["platform=iOS,id=YOURDEVICEUDID"],
            scheme: "MyAppTests")
end
```

Replace `YOURDEVICEUDID` with the UDID of your device. 

To find the UDID of your device go to Window -> Devices and Simulators in Xcode and select your device. Then look for the Identifier value.
