### ISSUE TITLE
xchtmlreport : Error accessing file error on latest fastlane version 2.130.0

### ISSUE THREAD

**Issue by sandeepgs1984** [fastlane/fastlane#15276]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[17:04:05]: No such file or directory - xchtmlreport

+------+------------------------------------------+-------------+
|                       fastlane summary                        |
+------+------------------------------------------+-------------+
| Step | Action                                   | Time (in s) |
+------+------------------------------------------+-------------+
| 1    | Verifying fastlane version               | 0           |
| 2    | default_platform                         | 0           |
| 3    | Switch to ios cb_clear_derived_data lane | 0           |
| 4    | clear_derived_data                       | 2           |
| 5    | cocoapods                                | 10          |
| 6    | Switch to ios cb_unlock_keychain lane    | 0           |
| 7    | unlock_keychain                          | 0           |
| 8    | Switch to ios cbz_match_debug lane       | 0           |
| 9    | match                                    | 31          |
| 10   | Switch to ios cb_scan lane               | 0           |
| 11   | Switch to ios cbz_devices lane           | 0           |
| 12   | scan                                     | 491         |
| 💥   | xchtmlreport -r                          | 0           |
|      | test_output/CricbuzzMobile.test_result   |             |
+------+------------------------------------------+-------------+

[17:04:05]: fastlane finished with errors

[17:04:05]: Error accessing file, this might be due to fastlane's directory handling
[17:04:05]: Check out https://docs.fastlane.tools/advanced/#directory-behavior for more details

bundler: failed to load command: fastlane (/Users/cbz-sandeep/.rbenv/versions/2.5.0/bin/fastlane)
Errno::ENOENT: No such file or directory - xchtmlreport
  /Users/cbz-sandeep/.rbenv/versions/2.5.0/lib/ruby/2.5.0/open3.rb:199:in `spawn'
  /Users/cbz-sandeep/.rbenv/versions/2.5.0/lib/ruby/2.5.0/open3.rb:199:in `popen_run'
  /Users/cbz-sandeep/.rbenv/versions/2.5.0/lib/ruby/2.5.0/open3.rb:190:in `popen2e'
  /Users/cbz-sandeep/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/helper/sh_helper.rb:54:in `sh_control_output'
  /Users/cbz-sandeep/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/helper/sh_helper.rb:16:in `sh_no_action'
  /Users/cbz-sandeep/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/fast_file.rb:213:in `block in sh'
  /Users/cbz-sandeep/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/cbz-sandeep/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/fast_file.rb:212:in `sh'
  /Users/cbz-sandeep/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/fast_file.rb:206:in `sh'
  CBFiles/helpers:10:in `generate_report'
  Fastfile:74:in `block (2 levels) in parsing_binding'
  /Users/cbz-sandeep/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/cbz-sandeep/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/cbz-sandeep/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/cbz-sandeep/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/cbz-sandeep/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Users/cbz-sandeep/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/cbz-sandeep/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/cbz-sandeep/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/cbz-sandeep/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/cbz-sandeep/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/cbz-sandeep/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.130.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/cbz-sandeep/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/cbz-sandeep/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
  /Users/cbz-sandeep/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/cbz-sandeep/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.130.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Users/cbz-sandeep/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.130.0/bin/fastlane:23:in `<top (required)>'
  /Users/cbz-sandeep/.rbenv/versions/2.5.0/bin/fastlane:23:in `load'
  /Users/cbz-sandeep/.rbenv/versions/2.5.0/bin/fastlane:23:in `<top (required)>'</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                     |
| --------------------------- | --------------------------------------------------------- |
| OS                          | 10.14.4                                                   |
| Ruby                        | 2.5.0                                                     |
| Bundler?                    | true                                                      |
| Git                         | git version 2.6.4                                         |
| Installation Source         | ~/.rbenv/versions/2.5.0/bin/fastlane                      |
| Host                        | Mac OS X 10.14.4 (18E226)                                 |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.0/lib                               |
| OpenSSL Version             | OpenSSL 1.0.2r  26 Feb 2019                               |
| Is contained                | false                                                     |
| Is homebrew                 | false                                                     |
| Is installed via Fabric.app | false                                                     |
| Xcode Path                  | /Volumes/Development/Xcode-10.2.1.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                                    |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.4.0"

default_platform :ios

platform :ios do

  #
  #   --------------------------
  #   #     Fastlane hooks     #
  #   --------------------------
  # 

  before_all do

    # For non-interative mode
    keychain_entry_builder = CredentialsManager::AccountManager.new(user: ENV["MATCH_USERNAME"])
    password_builder = keychain_entry_builder.password
    ENV["FASTLANE_PASSWORD"] = "#{password_builder}"

    # As CI runs parallelly jobs, need unique folder for each task instead of default shared path 
    #ENV["GYM_DERIVED_DATA_PATH"] = "./Derived Data"
 
  end

  error do |lane, exception|
    
    # slack(
    #   message: "Oops 🤒 ," + exception.message,
    #   success: false
    # )

  end

  #
  #   --------------------------
  #   #      Public lanes      #
  #   --------------------------
  #

  desc "Perform Unit test case on an application in development environment \n --------------------"
  lane :cb_test do

    cb_clear_derived_data
    cocoapods
    cb_unlock_keychain
    cbz_match_debug(force_for_new_devices: true, readonly: false)

    begin
      cb_scan
    rescue
      begin
        generate_report
      rescue
        # Ignore any exceptions coming from xchtmlreport
      end

      raise  # Re-throw original fastlane-scan exception
    end

    generate_report 

  end

  desc "Generate ipa based on given buildType \n --------------------"
  lane :prepare_ipa do |options|

    buildType = options[:buildType].nil? ? "" : options[:buildType]
    archive_path = options[:archive_path]

  	cb_clear_derived_data
    cocoapods
    cb_unlock_keychain

    if buildType == "Development"
      cbz_match_debug(force_for_new_devices: true, readonly: false)
      cb_debug_gym
    elsif buildType == "Staging"
      cbz_match_stag(force_for_new_devices: true, readonly: false)
      cb_stag_gym
    elsif buildType == "Distribution"
      cbz_match_appstore(force_for_new_devices: true, readonly: false)
      cbz_match_adhoc(force_for_new_devices: true, readonly: false)
      cb_distribution_gym(archive_path: archive_path)
    else
      cbz_match_appstore(force_for_new_devices: true, readonly: false)
      cb_release_gym(archive_path: archive_path)
    end

  end

  desc "To make sure certificates and provisional profiles are installed \n --------------------"
  lane :cbz_match do |options|
  	forceCreateProfiles = options[:force_for_new_devices].nil? ? false : options[:force_for_new_devices]
    isReadOnly = options[:readonly].nil? ? true : options[:readonly]

    cbz_match_debug(force_for_new_devices: forceCreateProfiles, readonly: isReadOnly)
    cbz_match_debug_production(force_for_new_devices: forceCreateProfiles, readonly: isReadOnly)
    cbz_match_stag(force_for_new_devices: forceCreateProfiles, readonly: isReadOnly)
    cbz_match_adhoc(force_for_new_devices: forceCreateProfiles, readonly: isReadOnly)
    cbz_match_appstore(readonly: isReadOnly)
  end

  desc "Create an archive in build folder \n --------------------"
  lane :cb_archive do 

    cocoapods
    cbz_match
    cb_unlock_keychain

    xcarchive(
      archive_path: "build/CricbuzzMobile.xcarchive",
      workspace: "CricbuzzMobile.xcworkspace",
      scheme: "CricbuzzMobile",
      xcargs: "-UseNewBuildSystem=YES -destination=\"generic/platform=iOS build\""
    )

  end

  desc "Distribute app to Fabric and Testflight \n --------------------"
  lane :fabricAndTestflight do |options|
    release_notes = fabric
    cb_deploy_testflight(ipa_path:"./build/Cricbuzz.ipa", release_notes: release_notes)
  end

  desc "Distribute app through Fabric. \n Select environment, Add devices etc. \n --------------------"
  lane :fabric do |options|

    cocoapods

    is_ci_trigger = options[:IS_WEB_TRIGGER]
    buildType = "Release"
    shouldUpload = true
    user_emails = ""
    release_notes = ""

    if is_ci_trigger == true

      buildType = options[:TRIGGER_BUILD_TYPE]
      user_emails = options[:TRIGGER_EMAILS]
      release_notes = options[:TRIGGER_RELEASE_NOTES]
      shouldUpload = options[:TRIGGER_UPLOAD_TO_FABRIC]

    else

    	if options[:ipa_path].nil?
      		buildType = UI.select("Select your build environment: ", ["Release", "Development", "Distribution", "Staging"])
      	end

      	UI.message("Do you want to add any devices before build distribution? (y/n):")
      	shouldAddDevices = STDIN.gets.chomp.strip

      	if shouldAddDevices == "y" || shouldAddDevices == "Y"
        	add_devices(forceRefresh:false)
      	end

      	until release_notes.length > 0 do
        	release_notes = prompt(text: "Enter release notes", multi_line_end_keyword: "END")
      	end

      	until user_emails.length > 0 do
        	user_emails = prompt(text: "Enter user email addresses separated by comma")
      	end

    end

    if shouldUpload == false
      UI.important "skipping due to TRIGGER_UPLOAD_TO_FABRIC == false"
    end

    if buildType.nil? || buildType.empty?
      shouldUpload = false
      UI.important "skipping due to invalid buildType"
    end

    if shouldUpload == true

      if options[:ipa_path].nil?

        prepare_ipa(buildType: buildType)
        cb_deploy_crashlytics(
          release_notes: release_notes,
          user_emails: user_emails
        )

      else

        cb_deploy_crashlytics(
          ipa_path: options[:ipa_path],
          release_notes: release_notes,
          user_emails: user_emails
        )

      end

    end

    release_notes
  end


  desc "Distribute app through Testflight. \n Select environment, Add devices etc. \n --------------------"
  lane :cb_testflight do |options|

    is_ci_trigger = options[:IS_WEB_TRIGGER]
    buildType = "Release"
    shouldUpload = true
    release_notes = ""

    if is_ci_trigger == true

      buildType = options[:TRIGGER_BUILD_TYPE]
      release_notes = options[:TRIGGER_RELEASE_NOTES]
      shouldUpload = options[:TRIGGER_UPLOAD_TO_TESTFLIGHT]

    else

      buildType = "Release"

      until release_notes.length > 0 do
        release_notes = prompt(text: "Enter release notes", multi_line_end_keyword: "END")
      end

    end


    if shouldUpload == false
      UI.important "skipping due to TRIGGER_UPLOAD_TO_TESTFLIGHT == false"
    end

    if buildType.nil? || buildType.empty?
      shouldUpload = false
      UI.important "skipping due to invalid buildType"
    end
    

    if shouldUpload == true

      if options[:ipa_path].nil?
        prepare_ipa(buildType: "Release")
        cb_deploy_testflight("release_notes": release_notes)
      else
        cb_deploy_testflight(ipa_path: options[:ipa_path], release_notes: release_notes)
      end

    end

  end

  desc "Upload an IPA to Nexus \n --------------------"
    lane :cb_nexus_upload do |options|

        ipa_path = options[:ipa_path]
        build_version = get_ipa_info_plist_value(ipa: ipa_path, key: "CFBundleVersion")

        nexus_upload(
          nexus_version: 3,
          file: ipa_path,
          mount_path: "",
          repo_id: "maven-releases-cricbuzz",
          repo_group_id: "com.cricbuzz",
          repo_project_name: "ios",
          repo_project_version: build_version,
          repo_classifier: "dSYM", # Optional
          verbose: true
        )

    end

  desc "Register devices and refresh all provisioning profiles \n --------------------"
  lane :add_devices do |options|
    
    deviceIDRegex = /^([A-F0-9]{40})$/i
    addMore = "y"
    devices = Hash.new
    forceRefreshProfiles = options[:forceRefresh].nil? ? true : options[:forceRefresh]

    UI.header(" Register Devices ")

    # fetch device UDIDs and Names
    until addMore == "n" || addMore == "N" do

      deviceID = ""
      deviceName = ""

      until deviceIDRegex.match(deviceID) && deviceName.length > 0 do
        UI.message("Name: ")
          deviceName = STDIN.gets.chomp.strip
          UI.message("UDID: ")
          deviceID = STDIN.gets.chomp.strip
          if deviceIDRegex.match(deviceID) && deviceName.length > 0
            break
          else 
            UI.error("invalid "+ (deviceName.length <= 0 ? "Name" : "UDID") +", please enter correct value.")
          end
      end

      devices[deviceName] = deviceID

      UI.message("do you want to add more device? (y/n)")
      addMore = STDIN.gets.chomp.strip

    end

    # register devices
    register_devices(devices: devices)

    if forceRefreshProfiles
      # refresh all provisioning profiles
      cbz_match(force_for_new_devices: true, readonly: false)
    end

  end

  desc "Forcefully create provisioning profiles if not available and install \n --------------------"
  lane :recreate_profiles do
    # recreate and install all provisioning profiles
    cbz_match(force_for_new_devices: true, readonly: false)
  end

  desc "take snapshots"
  lane :cb_snapshot do
    snapshot
    frameit
  end
  
end

import("./CBFiles/deploy")
import("./CBFiles/match")
import("./CBFiles/scan")
import("./CBFiles/gym")
import("./CBFiles/helpers")

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.130.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| bundler                   | 2.0.2        |
| CFPropertyList            | 3.0.1        |
| concurrent-ruby           | 1.1.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.11.1     |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.3        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.7.5        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.2.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.4.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| cocoapods                 | 1.7.5        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.66.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.1        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.0904  |
| mime-types                | 3.3          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2019-09-05**
</details>
</pre>
</details>

**Comment by janpio** [comment]
`xchtmlreport` seems to come from a plugin: https://github.com/TitouanVanBelle/fastlane-plugin-xchtmlreport
What is `generate_report` in your `Fastfile`? That seems to throw the error.

**Comment by sandeepgs1984** [comment]
> `xchtmlreport` seems to come from a plugin: https://github.com/TitouanVanBelle/fastlane-plugin-xchtmlreport
> What is `generate_report` in your `Fastfile`? That seems to throw the error.

@janpio thanks.. will try that..

`generate_report` is a separate action written in other file which is like:

    def generate_report
        puts "Generating Test Report ..."
        sh 'xchtmlreport -r test_output/CricbuzzMobile.test_result'
        puts "Test Report Successfully generated"

        sh "if [ -d '../../Reports/' ]; then rm -r ../../Reports/; fi"
        sh "mkdir ../../Reports"
        sh "cp test_output/CricbuzzMobile.test_result/index.html ../../Reports"
        sh "rsync -a --include '*/' --include '*.html' --include '*.jpg' --exclude '*' test_output/CricbuzzMobile.test_result/ ../../Reports"
        sh "if [ -d '../../Reports/Attachments/' ]; then rm -r ../../Reports/Attachments/; fi"
    end

**Comment by janpio** [comment]
Oh, so you are not using the plugin but calling `xchtmlreport` directly. Sorry for the confusion.

Seems like `xchtmlreport` is not available on your system any more. This should not be connected to Fastlane in any way, but probably to an update of the tool that is offering that `xchtmlreport` program.

**Comment by sandeepgs1984** [comment]
yes, i need to wait for an update which offers `xchtmlreport` ....

and one more error related to fastlane installation:


[12:26:33]: fastlane finished with errors
[12:26:33]: -----------------------------------------------------------------------
[12:26:33]: SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write client hello
[12:26:33]: 
[12:26:33]: SSL errors can be caused by various components on your local machine.
[12:26:33]: 
[12:26:33]: The best solution is to use the self-contained fastlane version.
[12:26:33]: Which ships with a bundled OpenSSL,ruby and all gems - so you don't depend on system libraries
[12:26:33]:  - Use Homebrew
[12:26:33]:     - update brew with `brew update`
[12:26:33]:     - install fastlane using:
[12:26:33]:       - `brew cask install fastlane`
[12:26:33]:  - Use One-Click-Installer:
[12:26:33]:     - download fastlane at https://download.fastlane.tools
[12:26:33]:     - extract the archive and double click the `install`
[12:26:33]: -----------------------------------------------------------
[12:26:33]: for more details on ways to install fastlane please refer the documentation:
[12:26:33]: -----------------------------------------------------------
[12:26:33]:         🚀       https://docs.fastlane.tools          🚀   
[12:26:33]: -----------------------------------------------------------
[12:26:33]: 
[12:26:33]: You can also install a new version of Ruby
[12:26:33]: 
[12:26:33]: - Make sure OpenSSL is installed with Homebrew: `brew update && brew upgrade openssl`
[12:26:33]: - If you use system Ruby:
[12:26:33]:   - Run `brew update && brew install ruby`
[12:26:33]: - If you use rbenv with ruby-build:
[12:26:33]:   - Run `brew update && brew upgrade ruby-build && rbenv install 2.3.1`
[12:26:33]:   - Run `rbenv global 2.3.1` to make it the new global default Ruby version
[12:26:33]: - If you use rvm:
[12:26:33]:   - First run `rvm osx-ssl-certs update all`
[12:26:33]:   - Then run `rvm reinstall ruby-2.3.1 --with-openssl-dir=/usr/local`
[12:26:33]: 
[12:26:33]: If that doesn't fix your issue, please google for the following error message:
[12:26:33]:   'SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write client hello'
[12:26:33]: -----------------------------------------------------------------------

[!] SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write client hello


my setup is through `gemfile` for dependency installations, as this error suggests, install `fastlane` through `brew`, 
i tried by removing gem `fastlane` by keeping only gem `cocoapods`, still it throws an error saying gem `cocoapods` is missing

can you please help on this issue ?

**Comment by janpio** [comment]
As I said, `xchtmlreport` is not a fastlane thing. We never included it, and never will. It might come from Xcode or some other software - you are just shelling out to this (as is the plugin I linked to) to use it.

Really nothing we can do about that.
