### ISSUE TITLE
Fastlane AppCenter upload Failing due to SSL certificate verify failed with Proxy 

### ISSUE THREAD

**Issue by anilbondada** [fastlane/fastlane#15275]
Below is the Output of "fastlane env"

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.6 (18G95)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
opt_out_usage

default_platform(:ios)

platform :ios do
  desc "Builds app for Staging Environment "
  lane :staging do
	build_ios_app(
		scheme: "CortixApp-Staging",
		configuration: "Debug",
		clean: true,
		export_options: {
			method: "ad-hoc"
		}
	)

	appcenter_upload(
		api_token: “******”,
		owner_name: "cortixplatform",
		app_name: "Cortix-ios-native",
		ipa: "./build/CortixApp-Staging.ipa",
		notify_testers: true,
		destinations: "Dev Test",
	  	destination_type: "group",
	)
  end

  lane :prod do
	build_ios_app(
		scheme: "CORTIX",
		configuration: "Release",
		clean: true,
		export_options: {
			method: "app-store"
		}
	)
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile



```
</details>

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.130.0 | 💥 Check failed |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status  |
| ------------------------- | ------- | -------------- |
| fastlane-plugin-appcenter | 1.4.0   | 💥 Check failed |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 3.0.1        |
| CFPropertyList            | 2.3.5        |
| addressable               | 2.7.0        |
| addressable               | 2.5.1        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.7.5        |
| dotenv                    | 2.2.0        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.66.0       |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.5        |
| fastimage                 | 2.1.0        |
| fastlane-plugin-appcenter | 1.4.0        |
| gh_inspector              | 1.1.3        |
| google-api-client         | 0.23.9       |
| google-cloud-core         | 1.3.1        |
| google-cloud-env          | 1.2.1        |
| google-cloud-storage      | 1.16.0       |
| googleauth                | 0.6.7        |
| highline                  | 1.7.10       |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 2.1.0        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2019.0904  |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.9.5        |
| minitest                  | 5.4.3        |
| multi_json                | 1.13.1       |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.6        |
| naturally                 | 2.2.0        |
| nokogiri                  | 1.5.6        |
| os                        | 1.0.1        |
| os                        | 0.9.6        |
| plist                     | 3.5.0        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| retriable                 | 2.1.0        |
| rouge                     | 2.0.7        |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| signet                    | 0.11.0       |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-cursor                | 0.7.0        |
| tty-screen                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| uber                      | 0.1.0        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.6.0        |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.12.0       |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2019-09-05**
</details>

**Comment by janpio** [comment]
AppCenter is actually a plugin for fastlane, so you should probably create an issue over there: https://github.com/microsoft/fastlane-plugin-appcenter

They will probably also want to see the actual error message and output, as we would, so you should make sure to include that in your issue so they can properly debug and understand the problem.
