### ISSUE TITLE
2FA 6 digit when entered does not proceed

### ISSUE THREAD

**Issue by ppamorim** [fastlane/fastlane#15277]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I am experiencing the same problem reported by issue https://github.com/fastlane/fastlane/issues/14520.
I am running this script in my own machine and this script used to work fine a month ago.
I can normally access App Store Connect through the browser.
##### Command executed
```
fastlane deliver download_metadata -m ./metadata/#{folder} -u 'foo@bar.com' -a #{scheme}
```

##### Complete output when running fastlane, including the stack trace and command used

spaceship.log:
```
Logfile created on 2019-09-05 14:46:17 +0100 by logger.rb/66358
INFO  [14:46:17]: >> GET https://appstoreconnect.apple.com/olympus/v1/session: [undefined body] 
DEBUG [14:46:17]: << GET https://appstoreconnect.apple.com/olympus/v1/session: 401 Unauthenticated

Request ID: ZWGFGBGPSR7ROZE6IU4AMB3G.0.0

WARN  [14:46:17]: Auth lost
INFO  [14:46:17]: >> POST https://idmsa.apple.com/appleauth/auth/signin: {"accountName":"foo@bar.com","password":"***","rememberMe":true} 
DEBUG [14:46:18]: << POST https://idmsa.apple.com/appleauth/auth/signin: 409 {"authType"=>"hsa2"}
INFO  [14:46:18]: >> GET https://idmsa.apple.com/appleauth/auth: [undefined body] 
DEBUG [14:46:18]: << GET https://idmsa.apple.com/appleauth/auth: 200 {"trustedPhoneNumbers"=>[{"numberWithDialCode"=>"+353 ••• ••• ••30", "pushMode"=>"sms", "obfuscatedNumber"=>"••• ••• ••30", "id"=>1}], "securityCode"=>{"length"=>6, "tooManyCodesSent"=>false, "tooManyCodesValidated"=>false, "securityCodeLocked"=>false, "securityCodeCooldown"=>false}, "authenticationType"=>"hsa2", "recoveryUrl"=>"https://iforgot.apple.com/phone/add?prs_account_nm=foo%40bar.com&autoSubmitAccount=true&appId=100", "cantUsePhoneNumberUrl"=>"https://iforgot.apple.com/iforgot/phone/add?context=cantuse&prs_account_nm=foo%40bar.com&autoSubmitAccount=true&appId=100", "recoveryWebUrl"=>"https://iforgot.apple.com/password/verify/appleid?prs_account_nm=foo%40bar.com&autoSubmitAccount=true&appId=100", "repairPhoneNumberUrl"=>"https://gsa.apple.com/appleid/account/manage/repair/verify/phone", "repairPhoneNumberWebUrl"=>"https://appleid.apple.com/widget/account/repair?#!repair", "aboutTwoFactorAuthenticationUrl"=>"https://support.apple.com/kb/HT204921", "autoVerified"=>false, "showAutoVerificationUI"=>false, "managedAccount"=>false, "trustedPhoneNumber"=>{"numberWithDialCode"=>"+353 ••• ••• ••30", "pushMode"=>"sms", "obfuscatedNumber"=>"••• ••• ••30", "id"=>1}, "hsa2Account"=>true, "restrictedAccount"=>false, "supportsRecovery"=>true}
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.14.6 (18G87)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.6.3/lib            |
| OpenSSL Version             | OpenSSL 1.0.2r  26 Feb 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.3                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

Private

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.130.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status |
| ----------------------- | ------- | ------------- |
| fastlane-plugin-appicon | 0.14.1  | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 2.0.1        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.1        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.12.0       |
| unicode-display_width     | 1.6.0        |
| addressable               | 2.7.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| excon                     | 0.66.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| json                      | 2.2.0        |
| rubyzip                   | 1.2.3        |
| dotenv                    | 2.7.5        |
| faraday_middleware        | 0.13.1       |
| mime-types-data           | 3.2019.0904  |
| mime-types                | 3.3          |
| os                        | 1.0.1        |
| digest-crc                | 0.4.1        |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| fastlane-plugin-appicon   | 0.14.1       |
</details>

*generated on:* **2019-09-05**
</details>

### EDIT 1:

By adding this line below, I was able to bypass the `deliver`'s authentication system.

```
udid = sigh(
    development: false,
    app_identifier: appId,
    output_path: "/tmp")
  ENV["PROJECT_UDID"] = udid
```

I've added this to my script as a workaround but this is not ideal.

Thank you,
Pedro

**Comment by janpio** [comment]
Uhoh, that one again. We didn't really figure out what was going on the last time :/

Which ones of the two lines did you add? Where did you add it? This looks like it's calling an action, but the command that is giving you problem was a sub CLI of `fastlane deliver`?

> udid = sigh(
>     development: false,
>     app_identifier: appId,
>     output_path: "/tmp")
>   ENV["PROJECT_UDID"] = udid

**Comment by ppamorim** [comment]
@janpio All of them, I had to add this before the deliver script to force the authentication.

**Comment by janpio** [comment]
Hm, I don't understand how calling `sigh` to get a `udid` would influence authentication.



> Where did you add it? This looks like it's calling an action, but the command that is giving you problem was a sub CLI of `fastlane deliver`?

**Comment by ppamorim** [comment]
`udid` has nothing to do with this. I only called this function to singin in my account and bypass the `deliver` one, so it's a workaround.

**Comment by janpio** [comment]
Oh ok, so you are using the "login" part of `sigh` becaues it works while the `deliver` one does not work?

**Comment by ppamorim** [comment]
Yes.
