### ISSUE TITLE
Migration React Native v0.65 - Fastlane build fail for iOS "Archive failed" (Exit Status: 65) only on CircleCI

### ISSUE THREAD

**Issue by vincentnavetat** [fastlane/fastlane#15280]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Working on migrating a mobile app from React Native 0.59.0 to 0.60.5 and to support AndroidX. The updated app works fine on both iOS and Android and the CircleCI build for Android is working fine.

The CircleCI build for iOS using Fastlane fails on CircleCI during the archive. When running `bundle exec fastlane ios build_release` locally it works fine.

##### Command executed
`bundle exec fastlane ios build_release`

##### Complete output when running fastlane, including the stack trace and command used

Complete output: https://gist.github.com/vincentnavetat/17adcdf4cd410f52e30e410d457d656f

<details>
  <pre>
▸ Touching MyApp.app.dSYM
** ARCHIVE FAILED **
[06:34:07]: Exit status: 65
[06:34:07]:
[06:34:07]: Maybe the error shown is caused by using the wrong version of Xcode
[06:34:07]: Found multiple versions of Xcode in '/Applications/'
[06:34:07]: Make sure you selected the right version for your project
[06:34:07]: This build process was executed using '/Applications/Xcode-10.2.1.app'
[06:34:07]: If you want to update your Xcode path, either
[06:34:07]:
[06:34:07]: - Specify the Xcode version in your Fastfile
[06:34:07]: ▸ xcversion(version: "8.1") # Selects Xcode 8.1.0
[06:34:07]:
[06:34:07]: - Specify an absolute path to your Xcode installation in your Fastfile
[06:34:07]: ▸ xcode_select "/Applications/Xcode8.app"
[06:34:07]:
[06:34:07]: - Manually update the path using
[06:34:07]: ▸ sudo xcode-select -s /Applications/Xcode.app
[06:34:07]:

+---------------+--------------------------------+
|               Build environment                |
+---------------+--------------------------------+
| xcode_path    | /Applications/Xcode-10.2.1.app |
| gym_version   | 2.130.0                        |
| export_method | app-store                      |
| sdk           | iPhoneOS12.2.sdk               |
+---------------+--------------------------------+

[06:34:07]: ▸ Touch /Users/distiller/Library/Developer/Xcode/DerivedData/MyApp-crgfinutbidjbqcbnlrwjwautwhq/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/BuildProductsPath/Release-iphoneos/MyApp.app.dSYM
[06:34:07]: ▸     cd /Users/distiller/mobile-app/ios
[06:34:07]: ▸     export PATH="/Applications/Xcode-10.2.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode-10.2.1.app/Contents/Developer/usr/bin:/Users/distiller/.gem/ruby/2.4.6/bin:/Users/distiller/.rubies/ruby-2.4.6/lib/ruby/gems/2.4.0/bin:/Users/distiller/.rubies/ruby-2.4.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
[06:34:07]: ▸     /usr/bin/touch -c /Users/distiller/Library/Developer/Xcode/DerivedData/MyApp-crgfinutbidjbqcbnlrwjwautwhq/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/BuildProductsPath/Release-iphoneos/MyApp.app.dSYM
[06:34:07]:
[06:34:07]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[06:34:07]: 📋  For the complete and more detailed error log, check the full log at:
[06:34:07]: 📋  /Users/distiller/Library/Logs/gym/MyApp-MyApp.log
[06:34:07]:
[06:34:07]: Looks like fastlane ran into a build/archive error with your project
[06:34:07]: It's hard to tell what's causing the error, so we wrote some guides on how
[06:34:07]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[06:34:07]: Before submitting an issue on GitHub, please follow the guide above and make
[06:34:07]: sure your project is set up correctly.
[06:34:07]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
[06:34:07]: the full commands printed out in yellow in the above log.
[06:34:07]: Make sure to inspect the output above, as usually you'll find more error information there
[06:34:07]:
+------------------------------------+---------------------------------------------------------------+
|                                            Lane Context                                            |
+------------------------------------+---------------------------------------------------------------+
| DEFAULT_PLATFORM                   | ios                                                           |
| PLATFORM_NAME                      | ios                                                           |
| LANE_NAME                          | ios build_release                                             |
| ORIGINAL_DEFAULT_KEYCHAIN          | "/Users/distiller/Library/Keychains/fastlane_tmp_keychain-db" |
| SIGH_PROFILE_TYPE                  | app-store                                                     |
| MATCH_PROVISIONING_PROFILE_MAPPING | {"com.mypap.app"=>"match AppStore com.mypap.app"}           |
+------------------------------------+---------------------------------------------------------------+
[06:34:07]: Error building the application - see the log above

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 3    | setup_circle_ci            | 0           |
| 4    | sync_code_signing          | 1           |
| 💥   | build_app                  | 279         |
+------+----------------------------+-------------+

[06:34:07]: fastlane finished with errors

[!] Error building the application - see the log above
  </pre>
</details>

### Environment

<details>
  <pre> 

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                              |
| --------------------------- | -------------------------------------------------- |
| OS                          | 10.14.4                                            |
| Ruby                        | 2.4.6                                              |
| Bundler?                    | true                                               |
| Git                         | git version 2.21.0                                 |
| Installation Source         | ~/.gem/ruby/2.4.6/bin/fastlane                     |
| Host                        | Mac OS X 10.14.4 (18E226)                          |
| Ruby Lib Dir                | ~/.rubies/ruby-2.4.6/lib                           |
| OpenSSL Version             | OpenSSL 1.0.2r  26 Feb 2019                        |
| Is contained                | false                                              |
| Is homebrew                 | false                                              |
| Is installed via Fabric.app | false                                              |
| Xcode Path                  | /Applications/Xcode-10.2.1.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   | en_GB.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# frozen_string_literal: true

# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version '2.67.0'

default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc 'Runs all the tests'
  lane :test do
    run_tests(scheme: "MyApp", skip_build: true)
  end

  desc 'Submit a new Beta Build to Apple TestFlight'
  desc 'This will also make sure the profile is up to date'
  lane :beta do
    sync_code_signing type: 'appstore' # see code signing guide for more information
    build_app scheme: 'MyApp'
    upload_to_testflight
  end

  desc 'Deploy a new version to the App Store'
  lane :release do
    sync_code_signing type: 'appstore' # see code signing guide for more information
    build_app scheme: 'MyApp'
    deliver(force: true)
    # frameit
  end

  desc "Build Release"
  lane :build_release do
    sync_code_signing type: 'appstore' # see code signing guide for more information
    build_app scheme: 'MyApp'
  end

  desc "Refresh DSyms"
  lane :refresh_dsyms do
    download_dsyms(min_version: "1.55.0")
    upload_symbols_to_bugsnag              # Upload them to Bugsnag
    clean_build_artifacts
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "[...]" # The bundle identifier of your app
apple_id "[...]" # Your Apple email address

team_id "[...]" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.130.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status |
| ----------------------- | ------- | ------------- |
| fastlane-plugin-bugsnag | 1.4.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| bundler                   | 2.0.2        |
| CFPropertyList            | 3.0.1        |
| concurrent-ruby           | 1.1.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.11.1     |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| httpclient                | 2.8.3        |
| json                      | 2.2.0        |
| algoliasearch             | 1.26.1       |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.3        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.8.0.beta.2 |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.2.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.4.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| cocoapods                 | 1.8.0.beta.2 |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.66.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.1        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| mime-types-data           | 3.2019.0904  |
| mime-types                | 3.3          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| google-cloud-storage      | 1.16.0       |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| git                       | 1.5.0        |
| xml-simple                | 1.1.5        |
| fastlane-plugin-bugsnag   | 1.4.1        |
</details>

*generated on:* **2019-09-06**
</details>

 </pre>
</details>

**Comment by janpio** [comment]
The output you posted includes everything _but_ the relevant lines which could maybe help understand what is going on. Please post the _complete_ output.

**Comment by vincentnavetat** [comment]
@janpio My bad, sorry. The output was too long for github, so I put everything into this gist: https://gist.github.com/vincentnavetat/17adcdf4cd410f52e30e410d457d656f

Thank you for taking a look.

**Comment by janpio** [comment]
Ugh, that is indeed a lot of output and nothing helpful in it :/ Sorry.

**Comment by Zeneixe** [comment]
Is there a way more output can be generated to help you figure this out?

**Comment by janpio** [comment]
This is not really a fastlane problem per se, bu how the project interacts with `xcodebuild` (the Xcode CLI): `set -o pipefail && xcodebuild -workspace ./MyApp.xcworkspace -scheme MyApp -destination 'generic/platform=iOS' -archivePath /Users/distiller/Library/Developer/Xcode/Archives/2019-09-06/MyApp\ 2019-09-06\ 08.14.34.xcarchive archive | tee /Users/distiller/Library/Logs/gym/MyApp-MyApp.log | xcpretty` is the command that was being run, and somehow this fails.

**Comment by rogerluan** [comment]
The user @xCTAPx is having the same issue as OP.

His `fastlane env`:

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.7                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.28.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.7 (19H2)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.0.1                                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | ru_RU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
platform :ios do
    desc "Push a new beta build to TestFlight"
    lane :beta do
    cert
    sigh
    increment_build_number(xcodeproj: "jobseeker.xcodeproj")
    build_app(workspace: "jobseeker.xcworkspace", scheme: "jobseeker",
    clean: true, export_method: "app-store",
    export_xcargs: "-allowProvisioningUpdates")
    upload_to_testflight
    end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("ru.project.jobseeker.mobile") # The bundle identifier of your app
apple_id("sudkurve@mail.ru") # Your Apple email address

itc_team_id("121921731") # App Store Connect Team ID
team_id("WP4HN85B8U") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.163.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.4        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.76.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.14.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-storage      | 1.29.1       |
| emoji_regex               | 3.0.0        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.381.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.109.1      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.83.0       |
| nanaimo                   | 0.3.0        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.19.0       |
| json                      | 2.3.1        |
| google-cloud-env          | 1.4.0        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>


*generated on:* **2020-10-15**
</details>

Same log as OP.
