### ISSUE TITLE
Gitlab CI/CD using docker Permission Denied

### ISSUE THREAD

**Issue by ronjunevaldoz** [fastlane/fastlane#15286]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Command executed

![image](https://user-images.githubusercontent.com/4947998/64523089-170a0600-d32e-11e9-9ed0-edeb7d6ca88f.png)
![image](https://user-images.githubusercontent.com/4947998/64523111-27ba7c00-d32e-11e9-8b5a-688b4690f335.png)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> Trying to setup fastlane using this example https://about.gitlab.com/2019/01/28/android-publishing-with-gitlab-and-fastlane/ </pre>
</details>

### Environment

<details>
  <pre> 

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.130.0 | ✅ Up-To-Date  |

</pre>
</details>

**Comment by janpio** [comment]
Your `gradlew` doesn't seem to have the right permissions. Did you commit it to git? If so, it might be worth to let gradle build it by itself on the machine on CI. Otherwise you could try to fix the permissions manually before running it.

**Comment by ronjunelopez** [comment]
> Your `gradlew` doesn't seem to have the right permissions. Did you commit it to git? If so, it might be worth to let gradle build it by itself on the machine on CI. Otherwise you could try to fix the permissions manually before running it.

No, I didt not run gradlew myself, it was from pipeline. I'm tying to setup the fastlane using dockerfile and gilab ci/cd yml. Also using this reference https://about.gitlab.com/2019/01/28/android-publishing-with-gitlab-and-fastlane/

**Comment by ronjunelopez** [comment]
Fixed it by adding to before_script
 ```
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew
```
if you have any other options, please share. Thanks

**Comment by MadLittleMods** [comment]
@ronjunelopez You can check it into your repo with execute permissions, https://stackoverflow.com/a/40979016/796832
