### ISSUE TITLE
Fastlane Getting Freeze at Running script '[CP] Embed Pods Frameworks'

### ISSUE THREAD

**Issue by SiddharthPromact** [fastlane/fastlane#15290]
### New Issue Checklist

- [x] Updated fastlane to the latest version (2.130.0)
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

- Using Fastlane with azure pipeline Build getting a freeze at **Running script '[CP] Embed Pods Frameworks**  we aren't able to do further action on the build as it gets stuck on given run script

##### Command executed
fastlane test build_number:$(BUILD_NUMBER) version_number:"1.1.$(BUILD_NUMBER)"

##### Complete output when running Fastlane, including the stack trace and command, used
        As log file is too large can't able to put it over here i am attaching image path [https://ibb.co/qFbqqfz](https://ibb.co/qFbqqfz) you can check it here.

<details>
  <pre> Using Fastlane with azure pipeline Build getting a freeze at **Running script '[CP] Embed Pods Frameworks**</pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.20.1 (Apple Git-117)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.6 (18G95)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.2.1                                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
#update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
#fastlane_version "2.62.1"

default_platform :ios
platform :ios do  

  before_all do
	certificates
  end
  
  lane :certificates do
    match(git_url: "<MY_CERTIFICATE_GIT>", app_identifier: [<"MY_DEV_IDENTIFIER">, <"MY_QA_IDENTIFIER">], type: "adhoc",readonly: true)
  end

  lane :test do |options|
    increment_build_number(build_number: options[:build_number])
    increment_version_number(version_number: options[:version_number])   
    clear_derived_data
    clean_build_artifacts 
    gym(scheme: "Dev", clean: true)
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"

  lane :dev do |options|
    increment_build_number(build_number: options[:build_number])
    increment_version_number(version_number: options[:version_number])
    # match(type: "adhoc") # more information: https://codesigning.guide
    # sigh(adhoc: true)
    gym(scheme: "Dev", clean: true)    
      testfairy(api_key: options[:testfairy_key],
      ipa: "./output/gym/PROJECTNAME.ipa",
      comment: "Build #{lane_context[SharedValues::BUILD_NUMBER]}",
      testers_groups: "PROJECTNAME-ios",
      auto_update: "on",
      notify: "on"
      )  
  end  

  lane :staging do |options|
    increment_build_number(build_number: options[:build_number])
    increment_version_number(version_number: options[:version_number])    
    gym(scheme: "Staging", clean: true) # Build your app - more options available       
    
      testfairy(api_key: options[:testfairy_key],
      ipa: "./output/gym/PROJECTNAME.ipa",
      comment: "Build #{lane_context[SharedValues::BUILD_NUMBER]}",
      testers_groups: "<PROJECTNAME>-ios-qa",
      auto_update: "on",
      notify: "on"
      )     
  end


  desc "Deploy a new version to the App Store"
  lane :appplestore do |options|
    increment_build_number(build_number: options[:build_number])
    increment_version_number(version_number: options[:version_number])
    match(git_url: <"MY_GIT_CERTIFICATE_URL">,app_identifier: [<"MY_PROD_IDENTIFIER">],type: "appstore", readonly: true)
    gym(scheme: "Production") # Build your app - more options available
    pilot(
      skip_waiting_for_build_processing: true
      )
  # frameit
  end    

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier <"MY_DEV_IDENTIFIER"> # The bundle identifier of your app

team_id <"TEAM_ID"> # Developer Portal Team ID

    for_platform :ios do
        for_lane :staging do
            app_identifier <"MY_QA_IDENTIFIER">
        end
    end

    for_platform :ios do
        for_lane :appplestore do
            app_identifier <"MY_PROD_IDENTIFIER">
        end
    end

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.130.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.1        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.66.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.3.1      |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.0.2        |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| psych                     | 2.1.0.1      |
</details>

*generated on:* **2019-09-11**
</details>

**Comment by SiddharthPromact** [comment]
> It seems like you have not included the output of `fastlane env`
> 
> To make it easier for us help you resolve this issue, please update the issue to include the output of `fastlane env` 👍

FASTLANE ENV ADDED

**Comment by janpio** [comment]
No, without the log we can't do anything. Put it into a Github gist or on pastebin or somewhere and paste the link.

Can you pinpoint the problem to a line in your `Fastfile`?

**Comment by SiddharthPromact** [comment]
> No, without the log we can't do anything. Put it into a Github gist or on pastebin or somewhere and paste the link.
> 
> Can you pinpoint the problem to a line in your `Fastfile`?

As log file is too large & due to some privacy issue i can't able to put it over here i am attaching issue screenshot in given link [https://ibb.co/qFbqqfz](url) you can check it here.

**Comment by janpio** [comment]
If this is just an output from Cocoapods, this doesn't seem like anything caused by fastlane. Can you build locally with fastlane?

**Comment by SiddharthPromact** [comment]
@janpio Fastlane working fine in the local machine only hangs in the **azure pipeline** only. can you guide me for it?

**Comment by janpio** [comment]
Not really, you will have to talk to the Azure Devops Pipelines people about that.

You might try running your lane with `--verbose` at the end, this could theoretically give some additional output but I don't expect this to help in this case.

**Comment by janpio** [comment]
Fastlane definitely didn't change anything there, as it just calls out to an Xcode CLI. Maybe that got updated on Azure Devops Pipelines, or some library is interacting with it in a funky way.

**Comment by SiddharthPromact** [comment]
@janpio My issue resolved. Due to the keychain locked it was stuck. So I am closing this issue

**Comment by rogerluan** [comment]
Hi @SiddharthPromact , thank you for that last bit of information, related to Keychain. I'm facing the same issue, do you remember how you fixed the keychain issue? I thought my CI machines were just slow, but realized that fastlane is getting stuck on the same step and then my build is timing out after 80 minutes stuck in that phase.

Appreciate any input you can give 🙏

**Comment by SteffenSr** [comment]
@rogerluan I managed to get past the freeze at "Running script '[CP] Embed Pods Frameworks" by adding the action `setup_ci` to my lane, as the first statement. I running my Fastlane iOS deployment in Github Action and I'm using Match with a private GitHub repo.
