### ISSUE TITLE
Xcode 11 GM breaks xcov file creation

### ISSUE THREAD

**Issue by reshadf** [fastlane/fastlane#15295]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: [`xcode 11 GM Seed`]
- Last working version: [`xcode 10.3`]

### Regression Description
xcov can't create the xcov coverage report using xcode 11 GM

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>bundler: failed to load command: fastlane (/Users/[redacted]/.rvm/gems/ruby-2.6.2/bin/fastlane)
RuntimeError: [!] Error creating your coverage report - see the log above
  /Users/[redacted]/.rvm/gems/ruby-2.6.2/gems/xcov-1.5.0/lib/xcov/error_handler.rb:20:in `handle_error'
  /Users/[redacted]/.rvm/gems/ruby-2.6.2/gems/xcov-1.5.0/lib/xcov/manager.rb:45:in `parse_xccoverage'
  /Users/[redacted]/.rvm/gems/ruby-2.6.2/gems/xcov-1.5.0/lib/xcov/manager.rb:30:in `run'
  /Users/[redacted]/.rvm/gems/ruby-2.6.2/gems/fastlane-2.130.0/fastlane/lib/fastlane/actions/xcov.rb:8:in `run'
  /Users/[redacted]/.rvm/gems/ruby-2.6.2/gems/fastlane-2.130.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
  /Users/[redacted]/.rvm/gems/ruby-2.6.2/gems/fastlane-2.130.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/[redacted]/.rvm/gems/ruby-2.6.2/gems/fastlane-2.130.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
  /Users/[redacted]/.rvm/gems/ruby-2.6.2/gems/fastlane-2.130.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Users/[redacted]/.rvm/gems/ruby-2.6.2/gems/fastlane-2.130.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Users/[redacted]/.rvm/gems/ruby-2.6.2/gems/fastlane-2.130.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/[redacted]/.rvm/gems/ruby-2.6.2/gems/fastlane-2.130.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
  Fastfile:37:in `block in parsing_binding'
  /Users/[redacted]/.rvm/gems/ruby-2.6.2/gems/fastlane-2.130.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/[redacted]/.rvm/gems/ruby-2.6.2/gems/fastlane-2.130.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/[redacted]/.rvm/gems/ruby-2.6.2/gems/fastlane-2.130.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/[redacted]/.rvm/gems/ruby-2.6.2/gems/fastlane-2.130.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/[redacted]/.rvm/gems/ruby-2.6.2/gems/fastlane-2.130.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Users/[redacted]/.rvm/gems/ruby-2.6.2/gems/fastlane-2.130.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/[redacted]/.rvm/gems/ruby-2.6.2/gems/fastlane-2.130.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/[redacted]/.rvm/gems/ruby-2.6.2/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/[redacted]/.rvm/gems/ruby-2.6.2/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/[redacted]/.rvm/gems/ruby-2.6.2/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/[redacted]/.rvm/gems/ruby-2.6.2/gems/fastlane-2.130.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/[redacted]/.rvm/gems/ruby-2.6.2/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/[redacted]/.rvm/gems/ruby-2.6.2/gems/fastlane-2.130.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
  /Users/[redacted]/.rvm/gems/ruby-2.6.2/gems/fastlane-2.130.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/[redacted]/.rvm/gems/ruby-2.6.2/gems/fastlane-2.130.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Users/[redacted]/.rvm/gems/ruby-2.6.2/gems/fastlane-2.130.0/bin/fastlane:23:in `<top (required)>'
  /Users/[redacted]/.rvm/gems/ruby-2.6.2/bin/fastlane:23:in `load'
  /Users/[redacted]/.rvm/gems/ruby-2.6.2/bin/fastlane:23:in `<top (required)>'</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by joshdholtz** [comment]
@reshadf Already working on trying to get this resolved 😊

**Comment by chinnasamymca** [comment]
Is there any update on this ?

**Comment by jereme** [comment]
Any updates here?

**Comment by zulkis** [comment]
This bug is still existing on Xcode 11.1.
Any updates on it?

**Comment by willdeberry** [comment]
Hate to be that guy, but any updates or ETA by chance?

**Comment by mildm8nnered** [comment]
I'm also seeing this, with Xcode 11, and xcov 1.6

At this point, we're disabling xcov for now - would be great to get a fix

**Comment by morpheby** [comment]
@mildm8nnered feel free to try out this fork https://github.com/morpheby/xcov/tree/update

If it works for you and it’s ok by @joshdholtz I’ll be happy to create a PR to `xcov-core`

**Comment by mildm8nnered** [comment]
@morpheby - thanks, but that doesn't seem to work for me Mojave 10.14.6, Xcode 11.0

```
[01:43:01]: Skipping file blacklisting as no ignore file was found at path ./fastlane/.xcovignore

+-----------------------------+-----------------------------------------------------------------------------------------------------------------+
|                                                            Summary for xcov 1.6.0                                                             |
+-----------------------------+-----------------------------------------------------------------------------------------------------------------+
| workspace                   | XXXXXX.xcworkspace                                                                                        |
| scheme                      | XXXXXXX                                                                                                    |
| output_directory            | xcov_output                                                                                                     |
| include_targets             | XXXXXX.app                                                                                             |
| derived_data_path           | test-build                                                                                                      |
| skip_slack                  | true                                                                                                            |
| html_report                 | true                                                                                                            |
| markdown_report             | false                                                                                                           |
| json_report                 | false                                                                                                           |
| minimum_coverage_percentage | 0                                                                                                               |
| slack_username              | xcov                                                                                                            |
| slack_message               | Your *xcov* coverage report                                                                                     |
| ignore_file_path            | ./fastlane/.xcovignore                                                                                          |
| include_test_targets        | false                                                                                                           |
| only_project_targets        | false                                                                                                           |
| disable_coveralls           | false                                                                                                           |
| ideFoundationPath           | /Volumes/Macintosh HD —                                                                                         |
|                             | Data/Applications/Xcode11.app/Contents/Developer/../Frameworks/IDEFoundation.framework/Versions/A/IDEFoundation |
| legacy_support              | false                                                                                                           |
+-----------------------------+-----------------------------------------------------------------------------------------------------------------+

[01:43:02]: Copying .xccovarchive to xcov_output/action_0.xccovarchive
[01:43:02]: Copying .xccovreport to xcov_output/action_0.xccovreport
[01:43:02]: $ /Users/martin/.rvm/gems/ruby-2.6.3/bundler/gems/xcov-1854621f69ae/lib/xcov-core/bin/xcov-core -s xcov_output/action_0.xccovreport -o xcov_output/tmp/report.json20191023-47696-1doci2k --ide-foundation-path /Volumes/Macintosh HD — Data/Applications/Xcode11.app/Contents/Developer/../Frameworks/IDEFoundation.framework/Versions/A/IDEFoundation
[01:43:02]: ▸ Loading...
[01:43:02]: ▸ IDEFoundation could not be loaded
IDEFoundation could not be loaded
[01:43:02]: Exit status: 66
```

**Comment by morpheby** [comment]
@mildm8nnered Would you mind please running `sudo xcode-select -s /Applications/Xcode11.app` (if that’s where your Xcode is)?

**Comment by mildm8nnered** [comment]
@morpheby 

```
Martins-MacBook-Pro martin$ xcode-select -p 
/Volumes/Macintosh HD - Data/Applications/Xcode11.app/Contents/Developer
```

I guess the spaces could be causing problems. 

`/Users/martin/.rvm/gems/ruby-2.6.3/bundler/gems/xcov-1854621f69ae/lib/xcov-core/bin/xcov-core -s xcov_output/action_0.xccovreport -o xcov_output/tmp/report.json20191023-47696-1doci2k --ide-foundation-path /Volumes/Macintosh HD - Data/Applications/Xcode11.app/Contents/Developer/../Frameworks/IDEFoundation.framework/Versions/A/IDEFoundation`

Looks dodgy to me

If I just run the same command with quoted spaces, it seems to run ok

`/Users/martin/.rvm/gems/ruby-2.6.3/bundler/gems/xcov-1854621f69ae/lib/xcov-core/bin/xcov-core -s xcov_output/action_0.xccovreport -o xcov_output/tmp/report.json20191023-47696-1doci2k --ide-foundation-path /Volumes/Macintosh\ HD\ -\ Data/Applications/Xcode11.app/Contents/Developer/../Frameworks/IDEFoundation.framework/Versions/A/IDEFoundation`

**Comment by mildm8nnered** [comment]
@morpheby - on my Continuous Integration machines, the path to Xcode 11 does not contain any spaces - it looks like xcov succeeded on those, so in actual fact I think your branch is good for Xcode 11 in the general case

**Comment by mildm8nnered** [comment]
xcov 1.7 appears to resolve this issue for me
