### ISSUE TITLE
Clarification about selecting the fastlane usage

### ISSUE THREAD

**Issue by nihp** [fastlane/fastlane#15294]
Can we able to select more than 2 while running fastlane init.

So how can I integrate 1, 2 at the same time

```
What would you like to use fastlane for?
1. 📸  Automate screenshots
2. 👩‍✈️  Automate beta distribution to TestFlight
3. 🚀  Automate App Store distribution
4. 🛠  Manual setup - manually setup your project to automate your tasks
```

**Comment by janpio** [comment]
The `init` workflow is just a help, you can just add the other workflow to your `Fastfile` afterwards. Reading docs.fastlane.tools will probably be the easiest way to figure this out.

You can also run `fastlane init` twice for the same codebase (different branches) and then combine the created files easily.

**Comment by nihp** [comment]
Yes, Thanks for your clarification. 

But if we run and the setup process in once while running the Fastlane init will helps.

I have another question:

I am using the iOS setup for Fastlane. If I use android also, the Fastfile and Appfile are generated in Android folder. I am I right?  So the iOS and Android not get conflicted.

**Comment by janpio** [comment]
That depends on your local setup. If Android and iOS are separate projects, yes, you will have two different configurations. But you can also set it up in a way that puts the fastlane config into the parent folder and the `Fastfile` contains both setups - all the actions just need to learn about the path of the projects then (all actions assume a standard path, but you can also always supply your own custom one).

**Comment by nihp** [comment]
Can you give me a sample configuration file of Fastfile for both android and iOS? I have one application  I have setup configuration for iOS but how I can integrate the same fastfile for android. Do I need any changes to mention the platform in Fastfile?

Also the android and iOS path of my project is not same. But it is one project with different folder.
