### ISSUE TITLE
build_app action fails non-deterministically when xcodebuild resolves dependencies

### ISSUE THREAD

**Issue by sharplet** [fastlane/fastlane#15301]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Under Xcode 11 when using Swift package dependencies, it looks like most `xcodebuild` actions automatically resolve dependencies, without any way to explicitly control this behaviour. Importantly, this includes any use of `xcodebuild -showBuildSettings`. Because querying the build settings now triggers dependency resolution, and the `build_app` action [uses a timeout & exponential backoff](https://github.com/fastlane/fastlane/blob/a9abea14b2aec266d906d3a6b7d82b82ab9e9725/fastlane_core/lib/fastlane_core/project.rb#L352-L364) when calling `xcodebuild -showBuildSettings`, dependency resolution now seems to be nondeterministically leaving Xcode's `SourcePackages` directory inside DerivedData in an inconsistent state. This sometimes results in builds taking longer than expected, or complete failure of builds.

I've filed feedback FB7259016 ("Swift package resolution happens at inappropriate times when using xcodebuild") regarding there being no way to disable or manually control when dependency resolution occurs.

In the meantime, one possible workaround could be for fastlane to provide a way to manually specify the settings it's currently querying for, to avoid triggering dependency resolution unintentionally. For now I've kind of just accepted that I will have non-deterministic builds until `xcodebuild` provides more control over this behaviour.

##### Command executed

This occurs in the `build_app` action when it's fetching build settings.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
+------------------------+---------+-------------------------+
|                        Used plugins                        |
+------------------------+---------+-------------------------+
| Plugin                 | Version | Action                  |
+------------------------+---------+-------------------------+
| fastlane-plugin-sentry | 1.5.0   | sentry_upload_dsym      |
|                        |         | sentry_upload_sourcemap |
|                        |         | sentry_finalize_release |
|                        |         | sentry_upload_file      |
|                        |         | sentry_create_release   |
+------------------------+---------+-------------------------+

[09:13:06]: ------------------------------
[09:13:06]: --- Step: default_platform ---
[09:13:06]: ------------------------------
[09:13:06]: Driving the lane 'ios build' 🚀
[09:13:06]: -----------------------------
[09:13:06]: --- Step: setup_circle_ci ---
[09:13:06]: -----------------------------
[09:13:06]: Creating temporary keychain: "fastlane_tmp_keychain".
[09:13:06]: Found keychain '~/Library/Keychains/fastlane_tmp_keychain', creation skipped
[09:13:06]: If creating a new Keychain DB is required please set the `require_create` option true to cause the action to fail
[09:13:06]: Enabling match readonly mode.
[09:13:06]: Skipping Log Path setup as FL_OUTPUT_DIR is unset
[09:13:06]: -------------------
[09:13:06]: --- Step: match ---
[09:13:06]: -------------------
[09:13:06]: Successfully loaded '/Users/distiller/project/fastlane/Matchfile' 📄

+--------------+----------------------------------------------------------+
|               Detected Values from './fastlane/Matchfile'               |
+--------------+----------------------------------------------------------+
| storage_mode | git                                                      |
| git_url      | git@github.com:vanda-pharmaceuticals/ruthinium-certs.git |
| type         | development                                              |
+--------------+----------------------------------------------------------+

+----------------------------+----------------------------------------------------------+
|                               Summary for match 2.131.0                               |
+----------------------------+----------------------------------------------------------+
| type                       | appstore                                                 |
| app_identifier             | ["com.vandapharma.testapp", "com.vandapharma.Ruthinium"] |
| readonly                   | true                                                     |
| skip_provisioning_profiles | false                                                    |
| username                   | ruthinium.developer@vandapharma.com                      |
| team_id                    | 5R95LM4NX7                                               |
| storage_mode               | git                                                      |
| git_url                    | git@github.com:vanda-pharmaceuticals/ruthinium-certs.git |
| git_branch                 | master                                                   |
| shallow_clone              | false                                                    |
| clone_branch_directly      | false                                                    |
| keychain_name              | fastlane_tmp_keychain                                    |
| force                      | false                                                    |
| force_for_new_devices      | false                                                    |
| skip_confirmation          | false                                                    |
| skip_docs                  | false                                                    |
| platform                   | ios                                                      |
| verbose                    | false                                                    |
+----------------------------+----------------------------------------------------------+

[09:13:06]: Cloning remote git repo...
[09:13:06]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[09:13:07]: 🔓  Successfully decrypted certificates repo
[09:13:07]: Installing certificate...
[09:13:07]: Setting key partition list... (this can take a minute if there are a lot of keys installed)
[09:13:08]: Setting key partition list... (this can take a minute if there are a lot of keys installed)

+-------------------+---------------------------------------------------------------+
|                               Installed Certificate                               |
+-------------------+---------------------------------------------------------------+
| User ID           | 5R95LM4NX7                                                    |
| Common Name       | iPhone Distribution: Vanda Pharmaceuticals, Inc. (5R95LM4NX7) |
| Organisation Unit | 5R95LM4NX7                                                    |
| Organisation      | Vanda Pharmaceuticals, Inc.                                   |
| Country           | US                                                            |
| Start Datetime    | 2019-08-22 21:14:40 UTC                                       |
| End Datetime      | 2020-08-21 21:14:40 UTC                                       |
+-------------------+---------------------------------------------------------------+

[09:13:08]: Installing provisioning profile...
[09:13:08]: Installing provisioning profile...

+---------------------+----------------------------------------------------+------------------------------------------------------------------------------------------------------------------+
|                                                                               Installed Provisioning Profile                                                                                |
+---------------------+----------------------------------------------------+------------------------------------------------------------------------------------------------------------------+
| Parameter           | Environment Variable                               | Value                                                                                                            |
+---------------------+----------------------------------------------------+------------------------------------------------------------------------------------------------------------------+
| App Identifier      |                                                    | com.vandapharma.testapp                                                                                          |
| Type                |                                                    | appstore                                                                                                         |
| Platform            |                                                    | ios                                                                                                              |
| Profile UUID        | sigh_com.vandapharma.testapp_appstore              | b58a5395-8c8f-49d5-9a18-2f2933c63cf7                                                                             |
| Profile Name        | sigh_com.vandapharma.testapp_appstore_profile-name | match AppStore com.vandapharma.testapp                                                                           |
| Profile Path        | sigh_com.vandapharma.testapp_appstore_profile-path | /Users/distiller/Library/MobileDevice/Provisioning Profiles/b58a5395-8c8f-49d5-9a18-2f2933c63cf7.mobileprovision |
| Development Team ID | sigh_com.vandapharma.testapp_appstore_team-id      | 5R95LM4NX7                                                                                                       |
+---------------------+----------------------------------------------------+------------------------------------------------------------------------------------------------------------------+

+---------------------+------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+
|                                                                                Installed Provisioning Profile                                                                                 |
+---------------------+------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+
| Parameter           | Environment Variable                                 | Value                                                                                                            |
+---------------------+------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+
| App Identifier      |                                                      | com.vandapharma.Ruthinium                                                                                        |
| Type                |                                                      | appstore                                                                                                         |
| Platform            |                                                      | ios                                                                                                              |
| Profile UUID        | sigh_com.vandapharma.Ruthinium_appstore              | 135ac6dd-1987-43e2-bc48-c989a0492d42                                                                             |
| Profile Name        | sigh_com.vandapharma.Ruthinium_appstore_profile-name | match AppStore com.vandapharma.Ruthinium                                                                         |
| Profile Path        | sigh_com.vandapharma.Ruthinium_appstore_profile-path | /Users/distiller/Library/MobileDevice/Provisioning Profiles/135ac6dd-1987-43e2-bc48-c989a0492d42.mobileprovision |
| Development Team ID | sigh_com.vandapharma.Ruthinium_appstore_team-id      | 5R95LM4NX7                                                                                                       |
+---------------------+------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+

[09:13:08]: All required keys, certificates and provisioning profiles are installed 🙌
[09:13:08]: Setting Provisioning Profile type to 'app-store'
[09:13:08]: -----------------------
[09:13:08]: --- Step: build_app ---
[09:13:08]: -----------------------
[09:13:08]: $ xcodebuild -showBuildSettings -workspace Ruthinium.xcworkspace -scheme Staging
[09:13:11]: Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...
[09:13:17]: Command timed out after 6 seconds on try 2 of 4, trying again with a 12 second timeout...
xcodebuild: error: Could not resolve package dependencies:
  terminated(128): /Applications/Xcode-11.GM.Seed.app/Contents/Developer/usr/bin/git -C /Users/distiller/Library/Developer/Xcode/DerivedData/Ruthinium-gbczldmpqdkdvlgrtgujyjyzdfnt/SourcePackages/repositories/RxSwift-86674848 rev-parse --verify 'delete-uiwebview^{commit}' output:
    fatal: Needed a single revision
    

[09:13:29]: Command timed out after 12 seconds on try 3 of 4, trying again with a 24 second timeout...
xcodebuild: error: Could not resolve package dependencies:
  Error Domain=NSCocoaErrorDomain Code=260 "The folder “RxSwift” doesn’t exist." UserInfo={NSFilePath=/Users/distiller/Library/Developer/Xcode/DerivedData/Ruthinium-gbczldmpqdkdvlgrtgujyjyzdfnt/SourcePackages/checkouts/RxSwift, NSUserStringVariant=(
    Folder
), NSUnderlyingError=0x7fd3c52f5030 {Error Domain=NSOSStatusErrorDomain Code=-43 "fnfErr: File not found"}}
  Error Domain=NSCocoaErrorDomain Code=260 "The folder “RxSwift” doesn’t exist." UserInfo={NSFilePath=/Users/distiller/Library/Developer/Xcode/DerivedData/Ruthinium-gbczldmpqdkdvlgrtgujyjyzdfnt/SourcePackages/checkouts/RxSwift, NSUserStringVariant=(
    Folder
), NSUnderlyingError=0x7fd3c55bd540 {Error Domain=NSOSStatusErrorDomain Code=-43 "fnfErr: File not found"}}
  An unknown error occurred. '/Users/distiller/Library/Developer/Xcode/DerivedData/Ruthinium-gbczldmpqdkdvlgrtgujyjyzdfnt/SourcePackages/checkouts/RxSwift' exists and is not an empty directory (-4)

[!] Xcodeproj doesn't know about the following attributes {"dependencyFile"=>"$(DERIVED_FILE_DIR)/apollo.d"} for the 'PBXShellScriptBuildPhase' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
[09:13:47]: Detected provisioning profile mapping: {:"com.vandapharma.testapp"=>"match AppStore com.vandapharma.testapp", :"com.vandapharma.Ruthinium"=>"match AppStore com.vandapharma.Ruthinium"}
[!] Xcodeproj doesn't know about the following attributes {"dependencyFile"=>"$(DERIVED_FILE_DIR)/apollo.d"} for the 'PBXShellScriptBuildPhase' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new

+---------------------------------------------------------------+--------------------------------------------------------------+
|                                                   Summary for gym 2.131.0                                                    |
+---------------------------------------------------------------+--------------------------------------------------------------+
| workspace                                                     | Ruthinium.xcworkspace                                        |
| export_method                                                 | app-store                                                    |
| export_options.provisioningProfiles.com.vandapharma.testapp   | match AppStore com.vandapharma.testapp                       |
| export_options.provisioningProfiles.com.vandapharma.Ruthinium | match AppStore com.vandapharma.Ruthinium                     |
| destination                                                   | generic/platform=iOS                                         |
| output_name                                                   | Ruthinium                                                    |
| build_path                                                    | /Users/distiller/Library/Developer/Xcode/Archives/2019-09-12 |
| scheme                                                        | Staging                                                      |
| clean                                                         | false                                                        |
| output_directory                                              | .                                                            |
| silent                                                        | false                                                        |
| skip_package_ipa                                              | false                                                        |
| result_bundle                                                 | false                                                        |
| buildlog_path                                                 | ~/Library/Logs/gym                                           |
| skip_profile_detection                                        | false                                                        |
| xcode_path                                                    | /Applications/Xcode-11.GM.Seed.app                           |
+---------------------------------------------------------------+--------------------------------------------------------------+

[09:13:47]: $ set -o pipefail && xcodebuild -workspace Ruthinium.xcworkspace -scheme Staging -destination 'generic/platform=iOS' -archivePath /Users/distiller/Library/Developer/Xcode/Archives/2019-09-12/Ruthinium\ 2019-09-12\ 09.13.47.xcarchive archive | tee /Users/distiller/Library/Logs/gym/Ruthinium-Staging.log | xcpretty
xcodebuild: error: Could not resolve package dependencies:
  An unknown error occured.

[09:13:52]: ▸ xcodebuild: error: Could not resolve package dependencies:
[09:13:52]: ▸   Error Domain=NSCocoaErrorDomain Code=260 "The folder “RxSwift” doesn’t exist." UserInfo={NSFilePath=/Users/distiller/Library/Developer/Xcode/DerivedData/Ruthinium-gbczldmpqdkdvlgrtgujyjyzdfnt/SourcePackages/checkouts/RxSwift, NSUserStringVariant=(
[09:13:52]: ▸     Folder
[09:13:52]: ▸ ), NSUnderlyingError=0x7fb1760cb840 {Error Domain=NSOSStatusErrorDomain Code=-43 "fnfErr: File not found"}}
xcodebuild: error: Could not resolve package dependencies:
  Error Domain=NSCocoaErrorDomain Code=260 "The folder “RxSwift” doesn’t exist." UserInfo={NSFilePath=/Users/distiller/Library/Developer/Xcode/DerivedData/Ruthinium-gbczldmpqdkdvlgrtgujyjyzdfnt/SourcePackages/checkouts/RxSwift, NSUserStringVariant=(
    Folder
), NSUnderlyingError=0x7fb1760cb840 {Error Domain=NSOSStatusErrorDomain Code=-43 "fnfErr: File not found"}}
[09:13:52]: Exit status: 74
[09:13:52]: 
[09:13:52]: Maybe the error shown is caused by using the wrong version of Xcode
[09:13:52]: Found multiple versions of Xcode in '/Applications/'
[09:13:52]: Make sure you selected the right version for your project
[09:13:52]: This build process was executed using '/Applications/Xcode-11.GM.Seed.app'
[09:13:52]: If you want to update your Xcode path, either
[09:13:52]: 
[09:13:52]: - Specify the Xcode version in your Fastfile
[09:13:52]: ▸ xcversion(version: "8.1") # Selects Xcode 8.1.0
[09:13:52]: 
[09:13:52]: - Specify an absolute path to your Xcode installation in your Fastfile
[09:13:52]: ▸ xcode_select "/Applications/Xcode8.app"
[09:13:52]: 
[09:13:52]: - Manually update the path using
[09:13:52]: ▸ sudo xcode-select -s /Applications/Xcode.app
[09:13:52]: 

+---------------+------------------------------------+
|                 Build environment                  |
+---------------+------------------------------------+
| xcode_path    | /Applications/Xcode-11.GM.Seed.app |
| gym_version   | 2.131.0                            |
| export_method | app-store                          |
| sdk           | iPhoneOS13.0.sdk                   |
+---------------+------------------------------------+

[09:13:52]: ▸   Apollo: https://github.com/apollographql/apollo-ios.git @ 0.15.1
[09:13:52]: ▸   NVActivityIndicatorView: https://github.com/Quantum2/NVActivityIndicatorView.git @ 4.7.1
[09:13:52]: ▸   Starscream: https://github.com/daltoniam/Starscream @ 3.1.0
[09:13:52]: ▸   Action: https://github.com/RxSwiftCommunity/Action.git @ 4.0.1
[09:13:52]: ▸   SQLite.swift: https://github.com/stephencelis/SQLite.swift.git @ 0.12.2
[09:13:52]: 
[09:13:52]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[09:13:52]: 📋  For the complete and more detailed error log, check the full log at:
[09:13:52]: 📋  /Users/distiller/Library/Logs/gym/Ruthinium-Staging.log
[09:13:52]: 
[09:13:52]: Looks like fastlane ran into a build/archive error with your project
[09:13:52]: It's hard to tell what's causing the error, so we wrote some guides on how
[09:13:52]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[09:13:52]: Before submitting an issue on GitHub, please follow the guide above and make
[09:13:52]: sure your project is set up correctly.
[09:13:52]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
[09:13:52]: the full commands printed out in yellow in the above log.
[09:13:52]: Make sure to inspect the output above, as usually you'll find more error information there
[09:13:52]: 
+------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                    Lane Context                                                                                     |
+------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM                   | ios                                                                                                                                            |
| PLATFORM_NAME                      | ios                                                                                                                                            |
| LANE_NAME                          | ios build                                                                                                                                      |
| ORIGINAL_DEFAULT_KEYCHAIN          | "/Users/distiller/Library/Keychains/fastlane_tmp_keychain-db"                                                                                  |
| SIGH_PROFILE_TYPE                  | app-store                                                                                                                                      |
| MATCH_PROVISIONING_PROFILE_MAPPING | {"com.vandapharma.testapp"=>"match AppStore com.vandapharma.testapp", "com.vandapharma.Ruthinium"=>"match AppStore com.vandapharma.Ruthinium"} |
+------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------+
[09:13:52]: Error building the application - see the log above

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 2    | setup_circle_ci  | 0           |
| 3    | match            | 2           |
| 💥   | build_app        | 44          |
+------+------------------+-------------+

[09:13:52]: fastlane finished with errors

[!] Error building the application - see the log above
Exited with code 1
</pre>
</details>

### Environment

<details>
  <pre>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.17.1                                             |
| Installation Source         | .git/safe/../../bin/fastlane                                   |
| Host                        | Mac OS X 10.14.6 (18G95)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.0                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_AU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# -*- mode: ruby -*-
# vim: set ft=ruby:

default_platform(:ios)

APP_IDENTIFIERS = %w(com.example.Redacted com.example.Redacted-beta)

platform :ios do
  desc "Set up CI"
  lane :setup do
    setup_circle_ci
    match(app_identifier: APP_IDENTIFIERS)
  end

  desc "Build the app"
  lane :build do |options|
    setup_circle_ci
    match(type: "appstore", app_identifier: APP_IDENTIFIERS)
    build_app(workspace: "Redacted.xcworkspace", **options)
  end

  desc "Push a new Staging build to TestFlight"
  lane :staging do |options|
    next_build_number(target: "Redacted", **options) do
      build(scheme: "Staging")
      upload_to_testflight
    end

    upload_symbols
  end

  desc "Push a new Production build to TestFlight"
  lane :prod do |options|
    next_build_number(target: "Redacted", **options) do
      build(scheme: "Redacted (Production)")
      upload_to_testflight
    end

    upload_symbols
  end

  desc "Bump version"
  lane :bump_version do |options|
    next_build_number(target: "Redacted", **options)
  end

  desc "Upload debug symbols to Sentry"
  lane :upload_symbols do
    auth_token = ENV.fetch("SENTRY_AUTH_TOKEN")
    download_dsyms
    sentry_upload_dsym(
      auth_token: auth_token,
      org_slug: "redacted",
      project_slug: "ios",
    )
  end
end

def next_build_number(options = {})
  skip_ci = options.fetch(:skip_ci, "true") == "true"
  target = options.fetch(:target)
  type = options.fetch(:type, "build")

  case type
  when "build"
    increment_build_number
  else
    increment_version_number(bump_type: type)
    increment_build_number
  end

  result = yield if block_given?

  version = get_version_number(target: target)
  build = get_build_number

  commit_message = [
    "Bump version to #{version} (#{build})",
    skip_ci ? "[skip ci]" : nil,
  ].compact.join("\n\n")

  commit_version_bump(message: commit_message)
  add_git_tag(tag: "#{version}+#{build}")
  push_to_git_remote

  result
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby:

#
# App Store Connect / Developer Portal
#
itc_team_id("redacted") # App Store Connect Team ID
team_id("redacted") # Developer Portal Team ID

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.131.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                 | Version | Update-Status |
| ---------------------- | ------- | ------------- |
| fastlane-plugin-sentry | 1.5.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 2.0.2        |
| io-console                | 0.4.5        |
| CFPropertyList            | 3.0.1        |
| concurrent-ruby           | 1.1.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.11.1     |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| httpclient                | 2.8.3        |
| json                      | 2.2.0        |
| algoliasearch             | 1.26.1       |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.3        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.8.0.beta.2 |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.2.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.4.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| cocoapods                 | 1.8.0.beta.2 |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.66.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.1        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| mime-types-data           | 3.2019.0904  |
| mime-types                | 3.3          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| google-cloud-storage      | 1.16.0       |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.4        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-sentry    | 1.5.0        |
</details>

*generated on:* **2019-09-12**
</details>
</pre>
</details>

**Comment by sharplet** [comment]
I was able to temporarily work around this issue by doing the following:

1. Adding a build step prior to running `fastlane` that calls `xcodebuild -showBuildSettings` to trigger resolving dependencies as a side effect;
2. Setting `FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT` to a sufficiently high number of seconds (say 30) to give it a chance to get past the resolve dependencies step.

Ideally `xcodebuild` would provide an explicit way to control or disable this behaviour. I'll report back if I get a response on my feedback.

**Comment by janpio** [comment]
Thanks for reporting this @sharplet and reporting your research here.

Did I understand correctly that you are currently _not_ aware of a rela workaround that could be added to `build_app`/`gym` that would put fastlane back into a "good" state?

**Comment by sharplet** [comment]
I think exposing action parameters for the values that `build_app`/`gym` is currently querying `xcodebuild -showBuildSettings` for might be a reasonable workaround. That way users can effectively turn off this behaviour by being explicit about a few more parameters.

**Comment by janpio** [comment]
Can you suggest a possible API and post an example how "being explicit about a few more parameters" would look like? I think I currently don't fully understand (but thanks for educating me!).

**Comment by sharplet** [comment]
@janpio Sure. Here's a specific example: https://github.com/fastlane/fastlane/blob/0865c5904dc35a7fb41458962802b13d99f8171b/gym/lib/gym/generators/build_command_generator.rb#L105

`Gym.project.app_name` internally calls `Project#build_settings`, triggering the call to `xcodebuild -showBuildSettings`. This is just used to construct a sensible file name for xcodebuild logs, and one possible solution (not necessarily the best one) would be to allow the user to configure a manual log path. Alternatively, this could perhaps use the project file's base name or something.

**Comment by janpio** [comment]
Ok, so it is basically about trying to avoid the side effects of `xcodebuild -showBuildSettings` that are now present.

**Comment by bguidolim** [comment]
@sharplet @janpio this is the same issue of #15454 
My PR #15505 should fix that.
