### ISSUE TITLE
Snapshot and simulators not found

### ISSUE THREAD

**Issue by nekfeu** [fastlane/fastlane#15306]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When I launch a fastlane snapshot, my simulators are found (--verbose says 19 simulators found), but I have this error : 

`File /Users/kevinempociello/Library/Developer/CoreSimulator/Devices/5ADE9DF8-BB93-4AE9-B333-8AF6A0732D69/device.plist not readable! (IOError)`

I'm trying to run my UITests on a iPhone 6 Plus.
So, I checked on my simulators list, and yes, I have an iPhone 6 plus, but its identifier is not 5ADE9DF8-BB93-4AE9-B333-8AF6A0732D69 but EB2DC3A0-3C64-4962-A192-2B8DFA9E53B4.

So why fastlane is trying to find the wrong identifier ? Because of iOS versioning ?
My simulators are on iOS 12.2 and 12.4.

##### Command executed

sudo fastlane snapshot

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> ➜  NekRx sudo fastlane snapshot
[✔] 🚀
[17:38:35]: fastlane detected a Gemfile in the current directory
[17:38:35]: however it seems like you don't use `bundle exec`
[17:38:35]: to launch fastlane faster, please use
[17:38:35]:
[17:38:35]: $ bundle exec fastlane snapshot
[17:38:35]:
[17:38:35]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[17:38:37]: Successfully loaded '/Users/kevinempociello/DEV/NekRx/fastlane/Snapfile' 📄

+----------------------------+-------------------+
|   Detected Values from './fastlane/Snapfile'   |
+----------------------------+-------------------+
| devices                    | ["iPhone 6 Plus"] |
| languages                  | ["en-US"]         |
| scheme                     | NekRx UITests     |
| output_directory           | ./screenshots     |
| clear_previous_screenshots | true              |
+----------------------------+-------------------+

[17:38:37]: $ xcodebuild -showBuildSettings -workspace ./NekRx.xcworkspace -scheme NekRx\ UITests

+----------------------------+------------------------------------------+
|                     Summary for snapshot 2.131.0                      |
+----------------------------+------------------------------------------+
| workspace                  | ./NekRx.xcworkspace                      |
| output_directory           | /Users/kevinempociello/DEV/NekRx/screen  |
|                            | shots                                    |
| devices                    | ["iPhone 6 Plus"]                        |
| languages                  | ["en-US"]                                |
| launch_arguments           | [""]                                     |
| output_simulator_logs      | false                                    |
| skip_open_summary          | false                                    |
| skip_helper_version_check  | false                                    |
| clear_previous_screenshots | true                                     |
| reinstall_app              | false                                    |
| erase_simulator            | false                                    |
| localize_simulator         | false                                    |
| app_identifier             | com.nekkar.NekRx                         |
| buildlog_path              | ~/Library/Logs/snapshot                  |
| clean                      | false                                    |
| scheme                     | NekRx UITests                            |
| number_of_retries          | 1                                        |
| stop_after_first_error     | false                                    |
| result_bundle              | false                                    |
| concurrent_simulators      | true                                     |
| xcode_path                 | /Applications/Xcode.app                  |
+----------------------------+------------------------------------------+

[17:38:39]: Clearing previously generated screenshots
[17:38:39]: Building and running project - this might take some time...
[17:38:39]: Patching simulators '/Users/kevinempociello/Library/Preferences/com.apple.iphonesimulator.plist' to scale to 100%

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Library/Ruby/Gems/2.3.0/gems/CFPropertyList-3.0.1/lib/cfpropertylist/rbCFPropertyList.rb:333:in `load': [!] File /Users/kevinempociello/Library/Developer/CoreSimulator/Devices/5ADE9DF8-BB93-4AE9-B333-8AF6A0732D69/device.plist not readable! (IOError)
	from /Library/Ruby/Gems/2.3.0/gems/CFPropertyList-3.0.1/lib/cfpropertylist/rbCFPropertyList.rb:238:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/simctl-1.6.5/lib/simctl/device.rb:233:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/simctl-1.6.5/lib/simctl/device.rb:233:in `plist'
	from /Library/Ruby/Gems/2.3.0/gems/simctl-1.6.5/lib/simctl/device.rb:38:in `devicetype'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/snapshot/lib/snapshot/test_command_generator.rb:96:in `block in get_device_type_with_simctl'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/snapshot/lib/snapshot/test_command_generator.rb:93:in `map'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/snapshot/lib/snapshot/test_command_generator.rb:93:in `get_device_type_with_simctl'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/snapshot/lib/snapshot/test_command_generator.rb:61:in `verify_devices_share_os'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/snapshot/lib/snapshot/test_command_generator.rb:36:in `destination'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/snapshot/lib/snapshot/test_command_generator.rb:15:in `generate'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:85:in `launch_simultaneously'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:70:in `block (3 levels) in take_screenshots_simultaneously'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:69:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:69:in `block (2 levels) in take_screenshots_simultaneously'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:46:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:46:in `each_with_index'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:46:in `block in take_screenshots_simultaneously'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:45:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb:45:in `take_screenshots_simultaneously'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/snapshot/lib/snapshot/runner.rb:45:in `work'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/snapshot/lib/snapshot/commands_generator.rb:40:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/snapshot/lib/snapshot/commands_generator.rb:104:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/snapshot/lib/snapshot/commands_generator.rb:14:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>' </pre>
</details>

### Environment

<details>
  <pre> <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.20.1 (Apple Git-117)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.6 (18G95)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.3                                                           |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Create app on Apple Developer and App Store Connect site"
  lane :create_app do
    produce
  end

  desc "Take screenshots"
  lane :screenshot do
    snapshot
  end

  desc "Create IPA"
  lane :build do
    enable_automatic_code_signing
    increment_build_number
    gym
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.nekkar.NekRx") # The bundle identifier of your app
apple_id("kevin.empociello@hotmail.fr") # Your Apple email address
itc_team_id(82505800)

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.131.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.66.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.0.2        |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| json                      | 2.2.0        |
| io-console                | 0.4.5        |
| rubyzip                   | 1.2.4        |
| CFPropertyList            | 3.0.1        |
| libxml-ruby               | 2.9.0        |
| atomos                    | 0.1.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| claide                    | 1.0.3        |
| fastimage                 | 2.1.7        |
| addressable               | 2.7.0        |
| psych                     | 2.1.0.1      |
| mime-types                | 3.3          |
| mime-types-data           | 3.2019.0904  |
</details>

*generated on:* **2019-09-13**
</details> </pre>
</details>

**Comment by janpio** [comment]
Hm, quickly looked into this:

https://github.com/fastlane/fastlane/blob/f32b007ff45e648b37b6c9c2037ac481f36b7780/snapshot/lib/snapshot/test_command_generator.rb#L87-L96

The last line of code from fastlane involved here is 96, then line 38 from this:
https://github.com/plu/simctl/blob/26e8d151b489c8b278f0e1d2ad810d79021714e8/lib/simctl/device.rb#L37-L39

then 233 here:
https://github.com/plu/simctl/blob/26e8d151b489c8b278f0e1d2ad810d79021714e8/lib/simctl/device.rb#L233

_Probably_ the `device_names` fastlane is using is already broken or containing info that will lead to error.

This comes from here:
https://github.com/fastlane/fastlane/blob/f32b007ff45e648b37b6c9c2037ac481f36b7780/snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb#L59-L70

Do you maybe have a broken simulator somewhere that could be selected here for some reason? Can you try to clean that up? Is probably easier than us continue debugging where it might get a device that it should not use :/

**Comment by nekfeu** [comment]
@janpio first, thank you so much for the time spent on my problem !

I looked into the files, Fastlane is using ** simctl** to get the simulators, that's pretty normal.
So if my device_names are wrong, it's certain that Fastlane will block. 

So I tried to use simctl on my own first to get the devices list with :
`$ xcrun simctl list`
But the simulator identifier used by Fastlane is not listed !

Even if I try some things like : 
`xcrun simctl erase 5ADE9DF8-BB93-4AE9-B333-8AF6A0732D69`
(which is the identifier used by Fastlane, the one causing the bug). The system tell me 
`Invalid device`

I'm sure that Fastlane is not inventing this identifier. So we can imagine that the Ruby code and the command system simctl are not finding the same simulators list. 
Do you have an idea how to compare these two methods ?

**Comment by janpio** [comment]
I _think_ this is the underlying function: https://github.com/fastlane/fastlane/blob/cf52a29dc62e07c2b5a690b4b74e0b45c7754af8/fastlane_core/lib/fastlane_core/device_manager.rb#L14-L66

**Comment by nekfeu** [comment]
Okay, actually 
`xcrun simctl list devices`
and 
`sudo xcrun simctl list devices`

don't display the same devices. The identifier was coming from this difference.
Stop to use : `sudo fastlane snapshot` and use `fastlane snapshot` was the solution. 
Even if from this point, fastlane wasn't able to get access to some files (little chmod(s) and it was okay).

I'm facing a last problem, the UITests are running well with `fastlane snapshot` (I can see it in the simulators), but fastlane is not taking any screenshot. 
Everything is executing well, expect the red cross in the language section. 

<details>
INFO [2019-09-21 00:08:46.37]: ▸ All tests
INFO [2019-09-21 00:08:46.37]: ▸ Test Suite NYL2PronosUITests.xctest started
INFO [2019-09-21 00:08:46.38]: ▸ NYL2PronosUITests
INFO [2019-09-21 00:08:58.09]: ▸     ✓ testExample (11.713 seconds)
INFO [2019-09-21 00:08:58.10]: ▸ 	 Executed 1 test, with 0 failures (0 unexpected) in 11.713 (11.715) seconds
INFO [2019-09-21 00:08:58.10]: ▸
INFO [2019-09-21 00:08:58.37]: ▸ 2019-09-21 00:08:58.371 xcodebuild[53523:2991315] [MT] IDETestOperationsObserverDebug: 25.976 elapsed -- Testing started completed.
INFO [2019-09-21 00:08:58.37]: ▸ 2019-09-21 00:08:58.372 xcodebuild[53523:2991315] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
INFO [2019-09-21 00:08:58.37]: ▸ 2019-09-21 00:08:58.372 xcodebuild[53523:2991315] [MT] IDETestOperationsObserverDebug: 25.976 sec, +25.976 sec -- end
INFO [2019-09-21 00:08:58.48]: ▸ Test Succeeded

+----------+-------+
| snapshot results |
+----------+-------+
| Device   | en-US |
+----------+-------+
| iPhone 8 |  ❌   |
+----------+-------+

INFO [2019-09-21 00:09:04.55]: Generating HTML Report
INFO [2019-09-21 00:09:04.55]: Successfully created HTML file with an overview of all the screenshots: '/Users/kevinempociello/DEV/NYL2Pronos-iOS/NYL2Pronos/fastlane/screenshots/screenshots.html'
INFO [2019-09-21 00:09:05.93]: Successfully generated documentation at path '/Users/kevinempociello/DEV/NYL2Pronos-iOS/NYL2Pronos/fastlane/README.md'

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | default_platform    | 0           |
| 2    | capture_screenshots | 124         |
+------+---------------------+-------------+

INFO [2019-09-21 00:09:05.94]: fastlane.tools finished successfully 🎉

</details>

**Comment by janpio** [comment]
> Okay, actually
> `xcrun simctl list devices`
> and
> `sudo xcrun simctl list devices`
> 
> don't display the same devices. The identifier was coming from this difference.

Interesting. Do you know why this might be the case?
Anything we can do to work around this?

For your other problem best open a new issue and include your testing script.

**Comment by nekfeu** [comment]
The solution was to remove the sudo. 
and use : `fastlane snapshot` instead.

From this point, various files was only available for root and not for my user.
I changed these files rights with `chmod`, and my `fastlane snapshot` worked !
