### ISSUE TITLE
sigh is not working with the new `apple developer` / `apple distribution` certificates introduced with Xcode 11

### ISSUE THREAD

**Issue by Nonnus** [fastlane/fastlane#15300]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
* On of my lanes builds an ad-hoc version of my company app, for this we use sigh to manage generate provisioning profiles, until now it has been working fine but on our Xcode 11 branch we noticed the `iOS distribution` certificate we were using was not available on Xcode 11 and the only option to generate new ones is `apple development` and `apple distribution`.

* After generating an `apple distribution` certificate and updating our project to use that certificate we found out that sigh always fails to generate provisioning profiles and complains about "not find a matching code signing identity for type 'AdHoc'"

* We also tried re-generating an "old" `ios distribution` certificate and try to run our lane but this time while `sigh` was able to generate provisioning profiles but then fails when code signing with error `error: exportArchive: Provisioning profile "com.hellofresh.HelloFresh.mainwidget AdHoc" doesn't include signing certificate "Apple Distribution: Hellofresh GmbH (2A7X7KDSR2)".`

(ps: I am aware we could use match, this is not what this issue is about)

##### Command executed
`bundle exec fastlane upload_fabric configuration:Fabric`

##### Complete output when running fastlane, including the stack trace and command used

running on Xcode 10.3 (works fine as expected):
```
[15:35:07]: [0;32;49m------------------[0m
[15:35:07]: [0;32;49m--- Step: sigh ---[0m
[15:35:07]: [0;32;49m------------------[0m

+-------------------------------------+---------------------------+
|                    [0;32;49mSummary for sigh 2.130.0[0m                     |
+-------------------------------------+---------------------------+
| username                            | xxx     |
| app_identifier                      | com.hellofresh.HelloFresh |
| adhoc                               | true                      |
| force                               | true                      |
| developer_id                        | false                     |
| development                         | false                     |
| skip_install                        | false                     |
| team_id                             | xxx                |
| ignore_profiles_with_different_name | false                     |
| skip_fetch_profiles                 | false                     |
| skip_certificate_verification       | false                     |
| platform                            | ios                       |
| readonly                            | false                     |
+-------------------------------------+---------------------------+

[15:35:07]: Starting login with user 'xxx'
[15:35:08]: Successfully logged in
[15:35:08]: Fetching profiles...
[15:35:09]: Verifying certificates...
[15:35:11]: [0;32;49mFound 1 matching profile(s)[0m
[15:35:11]: [0;33;49mRecreating the profile[0m
[15:35:15]: [0;33;49mCreating new provisioning profile for 'com.hellofresh.HelloFresh' with name 'com.hellofresh.HelloFresh AdHoc' for 'ios' platform[0m
[15:35:17]: [0;33;49mDownloading provisioning profile...[0m
[15:35:17]: [0;32;49mSuccessfully downloaded provisioning profile...[0m
[15:35:18]: Installing provisioning profile...
[0;32;49m/Users/device.de_ci/.jenkins/workspace/Upload_Fabric/HelloFresh/fastlane/provisioning_profiles/AdHoc_com.hellofresh.HelloFresh.mobileprovision[0m
[15:35:18]: Setting Provisioning Profile type to 'ad-hoc'
```

running on Xcode 11 (does not work):
```
[15:23:30]: [0;32;49m------------------[0m
[15:23:30]: [0;32;49m--- Step: sigh ---[0m
[15:23:30]: [0;32;49m------------------[0m

+-------------------------------------+---------------------------+
|                    [0;32;49mSummary for sigh 2.130.0[0m                     |
+-------------------------------------+---------------------------+
| username                            | xxx     |
| app_identifier                      | com.hellofresh.HelloFresh |
| adhoc                               | true                      |
| force                               | true                      |
| developer_id                        | false                     |
| development                         | false                     |
| skip_install                        | false                     |
| team_id                             | xxx                |
| ignore_profiles_with_different_name | false                     |
| skip_fetch_profiles                 | false                     |
| skip_certificate_verification       | false                     |
| platform                            | ios                       |
| readonly                            | false                     |
+-------------------------------------+---------------------------+

[15:23:30]: Starting login with user 'xxx'
[15:23:31]: Successfully logged in
[15:23:31]: Fetching profiles...
[15:23:32]: Verifying certificates...
[15:23:34]: [0;32;49mFound 1 matching profile(s)[0m
[15:23:34]: [0;33;49mRecreating the profile[0m
[15:23:37]: [0;32;49m-----------------------------------[0m
[15:23:37]: [0;32;49m--- Step: clean_build_artifacts ---[0m
[15:23:37]: [0;32;49m-----------------------------------[0m
[15:23:37]: [0;32;49mCleaned up build artifacts 🐙[0m
+--------------------------------+-------------------+
|                    [0;33;49mLane Context[0m                    |
+--------------------------------+-------------------+
| DEFAULT_PLATFORM               | ios               |
| PLATFORM_NAME                  | ios               |
| LANE_NAME                      | ios upload_fabric |
| VERSION_NUMBER                 | 3.25              |
| LATEST_BUILD_NUMBER            | 10388             |
| LATEST_TESTFLIGHT_BUILD_NUMBER | 10388             |
| BUILD_NUMBER                   | 10391             |
+--------------------------------+-------------------+
[15:23:37]: [0;31;49mCould not find a matching code signing identity for type 'AdHoc'. It is recommended to use match to manage code signing for you, more information on https://codesigning.guide. If you don't want to do so, you can also use cert to generate a new one: https://fastlane.tools/cert[0m
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.6.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.18.0                          |
| Installation Source         | /usr/local/lib/ruby/gems/2.6.0/bin/fastlane |
| Host                        | Mac OS X 10.14.6 (18G95)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.6.1/lib            |
| OpenSSL Version             | OpenSSL 1.0.2q  20 Nov 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.0                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.131.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                      | Version | Update-Status |
| --------------------------- | ------- | ------------- |
| fastlane-plugin-test_center | 3.8.3   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                         | Version      |
| --------------------------- | ------------ |
| did_you_mean                | 1.3.0        |
| bundler                     | 2.0.1        |
| CFPropertyList              | 3.0.1        |
| public_suffix               | 2.0.5        |
| addressable                 | 2.7.0        |
| atomos                      | 0.1.3        |
| babosa                      | 1.0.2        |
| claide                      | 1.0.3        |
| colored                     | 1.2          |
| colored2                    | 3.1.2        |
| colorize                    | 0.8.1        |
| highline                    | 1.7.10       |
| commander-fastlane          | 4.4.6        |
| declarative                 | 0.0.10       |
| declarative-option          | 0.1.0        |
| digest-crc                  | 0.4.1        |
| unf_ext                     | 0.0.7.6      |
| unf                         | 0.1.4        |
| domain_name                 | 0.5.20190701 |
| dotenv                      | 2.7.5        |
| emoji_regex                 | 1.0.1        |
| excon                       | 0.66.0       |
| multipart-post              | 2.0.0        |
| faraday                     | 0.15.4       |
| http-cookie                 | 1.0.3        |
| faraday-cookie_jar          | 0.0.6        |
| faraday_middleware          | 0.13.1       |
| fastimage                   | 2.1.7        |
| gh_inspector                | 1.1.3        |
| jwt                         | 2.1.0        |
| memoist                     | 0.16.0       |
| multi_json                  | 1.13.1       |
| os                          | 1.0.1        |
| signet                      | 0.11.0       |
| googleauth                  | 0.6.7        |
| httpclient                  | 2.8.3        |
| mime-types-data             | 3.2019.0904  |
| mime-types                  | 3.3          |
| uber                        | 0.1.0        |
| representable               | 3.0.4        |
| retriable                   | 3.1.2        |
| google-api-client           | 0.23.9       |
| google-cloud-env            | 1.2.1        |
| google-cloud-core           | 1.3.1        |
| google-cloud-storage        | 1.16.0       |
| json                        | 2.2.0        |
| mini_magick                 | 4.9.5        |
| multi_xml                   | 0.6.0        |
| plist                       | 3.5.0        |
| rubyzip                     | 1.2.4        |
| security                    | 0.1.3        |
| naturally                   | 2.2.0        |
| simctl                      | 1.6.6        |
| slack-notifier              | 2.3.2        |
| terminal-notifier           | 2.0.0        |
| unicode-display_width       | 1.6.0        |
| terminal-table              | 1.8.0        |
| tty-screen                  | 0.7.0        |
| tty-cursor                  | 0.7.0        |
| tty-spinner                 | 0.9.1        |
| word_wrap                   | 1.0.0        |
| nanaimo                     | 0.2.6        |
| xcodeproj                   | 1.12.0       |
| rouge                       | 2.0.7        |
| xcpretty                    | 0.3.0        |
| xcpretty-travis-formatter   | 1.0.0        |
| xctest_list                 | 1.1.8        |
| fastlane-plugin-test_center | 3.8.3        |
</details>

*generated on:* **2019-09-13**
</details>

**Comment by Westacular** [comment]
It seems that... although Fastlane has added support for the new cert types to the underlying Spaceship library, they're handled as a new separate type of certificate, and no changes have been made to `sigh` to support the new types.

(Related issue for development profiles: https://github.com/fastlane/fastlane/issues/15214)

**Comment by fishercraigj** [comment]
+1 same issue

**Comment by joshdholtz** [comment]
Will have a fix out for this in the next day!
