### ISSUE TITLE
Though we are using XCODE11, "match" command in fastlane is still generating older certs for apple ID (iPhone Developer) instead of generating new certs (Apple Development)

### ISSUE THREAD

**Issue by BSaheta** [fastlane/fastlane#15318]
Though we are using XCODE11, "match" command in fastlane is still generating older certs for apple ID (iPhone Developer) instead of generating new certs (Apple Development).

Is there  any additional argument which we need to pass to match command to tell that to generate Apple Development certs instead of iPhone Developer certs?

**Comment by janpio** [comment]
These new kinds of certificates are probably not supported by fastlane yet, sorry. I think I remember some previous issues about those, but I am currently not aware of the state of that work.

**Comment by BSaheta** [comment]
Is anyone else facing this issue? Any update on this?

**Comment by leetal** [comment]
We are....

**Comment by yusuftor** [comment]
@leetal How do you force match to download the updated provisioning profile? When I try `fastlane match development --force` it just overwrites the one in the dev portal.

**Comment by bguidolim** [comment]
You should use the  `--generate_apple_certs` in your match action.
