### ISSUE TITLE
Support of new StatusBar overrides in iOS 13 when running Snapshot

### ISSUE THREAD

**Issue by NickAtGit** [fastlane/fastlane#15319]
### Feature Request
Support of new StatusBar overrides in iOS 13
#### Motivation Behind Feature
Because it's the new way to do it

#### Feature Description
`xcrun simctl status_bar <device> override --time "9:41" --batteryState charged --batteryLevel 100`  more info: `xcrun simctl help status_bar`

**Comment by rickclephas** [comment]
There is already some progress at #15124

**Comment by pronebird** [comment]
`has-pr` was added by I couldn't find a PR. Was it implemented already?

**Comment by bouk** [comment]
I've got a PR: https://github.com/fastlane/fastlane/pull/16419
