### ISSUE TITLE
Error 65 | error: unable to spawn process (No such file or directory) (in target 'SnapKit' from project 'Pods')

### ISSUE THREAD

**Issue by Kamik423** [fastlane/fastlane#15311]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

When attempting to run snapshots (for example even in [Textor](https://github.com/louisdh/textor)) the compilation fails

#### Question Description

Attempting to run `fastlane snapshot` will start compiling sources and crash at

```
▸ Compiling SnapKit-dummy.m

❌  error: unable to spawn process (No such file or directory) (in target 'SnapKit' from project 'Pods')


▸ Compiling SnapKit_vers.c

❌  error: unable to spawn process (No such file or directory) (in target 'SnapKit' from project 'Pods')


▸ Compiling SnapKit-dummy.m

❌  error: unable to spawn process (No such file or directory) (in target 'SnapKit' from project 'Pods')


▸ Compiling SnapKit_vers.c

❌  error: unable to spawn process (No such file or directory) (in target 'SnapKit' from project 'Pods')


Testing failed:
	unable to spawn process (No such file or directory)
	Testing cancelled because the build failed.

** TEST FAILED **


The following build commands failed:
	CompileC /var/folders/qj/3w7qyh196b9gbm386_4030rh0000gn/T/snapshot_derived20190914-66610-1p0gn0k/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SnapKit.build/Objects-normal/x86_64/SnapKit-dummy.o /Users/hans/Documents/programming/xcode/hexer/Pods/Target\ Support\ Files/SnapKit/SnapKit-dummy.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /var/folders/qj/3w7qyh196b9gbm386_4030rh0000gn/T/snapshot_derived20190914-66610-1p0gn0k/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SnapKit.build/Objects-normal/x86_64/SnapKit_vers.o /var/folders/qj/3w7qyh196b9gbm386_4030rh0000gn/T/snapshot_derived20190914-66610-1p0gn0k/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SnapKit.build/DerivedSources/SnapKit_vers.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)
[21:50:10]: Exit status: 65
[21:50:10]: Tests failed while running on: iPhone 8
[21:50:10]: For more detail about the test failures, check the logs here:
[21:50:10]: /Users/hans/Library/Logs/snapshot/Hexer-Hexer UI Tests.log
[21:50:10]:
[21:50:10]: You can also find the test result data here:
[21:50:10]: /var/folders/qj/3w7qyh196b9gbm386_4030rh0000gn/T/snapshot_derived20190914-66610-1p0gn0k/Logs/Test
[21:50:10]:
[21:50:10]: You can find the incomplete screenshots here:
[21:50:10]: /Users/hans/Library/Caches/tools.fastlane/screenshots
[21:50:10]: /Users/hans/Documents/programming/xcode/hexer/screenshots
[21:50:10]: Caught error... 65
```

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.21.0 (Apple Git-122)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.6 (18G84)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | ~/Applications/Xcode.app/Contents/Developer/                   |
| Xcode Version               | 11.0                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "Hexer.xcworkspace", scheme: "Hexer UI Tests")
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.hans.Hexer") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.131.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.60.0       |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.3.1      |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.4        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| psych                     | 2.1.0.1      |
</details>

*generated on:* **2019-09-14**
</details>

**Comment by janpio** [comment]
Can you reproduce this in a new, plain project?

**Comment by Kamik423** [comment]
After doing some tweaking I finally got it to work. I am not sure what the issue was. I think something related to schemes.

Sorry. This probably won't help out people in the future...
