### ISSUE TITLE
Feature Request: Set release name when uploading to Play Store

### ISSUE THREAD

**Issue by kschults** [fastlane/fastlane#15317]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I would like to provide a release name when creating or promoting a release using `upload_to_play_store`. This issue is copied from https://github.com/fastlane/fastlane/issues/13643, which was auto-closed.

**Comment by rickclephas** [comment]
To answer @janpio's question from the closed issue.
Supply is currently using V2 of the API which doesn't provide this functionality.
When #14573 is fixed this could be implemented with the V3 API.

**Comment by kschults** [comment]
@rickclephas Thanks for the info. Would love to have this feature included once the V3 API is incorporated.

**Comment by rickclephas** [comment]
Nope it's a feature request.

**Comment by kschults** [comment]
Hey Fastlane, now that #14573 is done, can work move forward on this?

**Comment by rickclephas** [comment]
I believe this has already been included during the migration to the V3 API.
The `version_name` option should control the name of the release.
Checkout the [migration docs](https://docs.fastlane.tools/actions/supply/#migration-from-androidpublisherv2-to-androidpublisherv3-in-fastlane-21350).

**Comment by kschults** [comment]
Yup, looks like it's now available. Thanks!
