### ISSUE TITLE
JENKINS : Permission denied [app/path/gradlew]

### ISSUE THREAD

**Issue by TBoonkwan** [fastlane/fastlane#15314]
<img width="958" alt="Screen Shot 2562-09-16 at 15 10 17" src="https://user-images.githubusercontent.com/34676434/64942797-3526b780-d894-11e9-873a-3c8248c79aeb.png">
<img width="930" alt="Screen Shot 2562-09-16 at 15 10 34" src="https://user-images.githubusercontent.com/34676434/64942799-3952d500-d894-11e9-8b4f-329ffbdaa902.png">

**Comment by janpio** [comment]
Fix the file permissions of `gradlew` before executing it.

Please also don't delete the issue template before posting here, we really need that information to being able to understand and help you.
