### ISSUE TITLE
register_device action asks for team selection although I defined team_id

### ISSUE THREAD

**Issue by PhilippOtto89** [fastlane/fastlane#15316]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Hey,

I use register_devices to automatically add a device to the developer center. I pass the team_id as a parameter but still the command line prompts me for a team selection.

Am I doing something wrong here or is this maybe a bug?

Thanks guys!!!

##### Command executed
        module Fastlane
          module Actions
            class RegisterConnectedDeviceAction < Action
              def self.run(params)
                [...]

                Fastlane::Actions::RegisterDeviceAction.run(
                  name: registered_device_name,
                  udid: selected_device_uuid,
                  team_id: "E23DE1CDR1"
                )
              end

              [...]

          end
        end

##### Complete output when running fastlane, including the stack trace and command used
Multiple teams found on the Developer Portal, please enter the number of the team you want to use: 
1) E23DE1CDR1 "CompanyName" (In-House)
2) ...

### Environment
fastlane v 2.130.0

**Comment by rickclephas** [comment]
The `register_device` action converts the `team_id` option to the environment variable `FASTLANE_TEAM_ID`:
https://github.com/fastlane/fastlane/blob/1a50a980c3999c74669355d4fe74338169327b9e/fastlane/lib/fastlane/actions/register_device.rb#L46-L55

I guess that since you are calling the run method directly this code is never executed.

Could you try setting the environment variable before the call to `run`?
```ruby
ENV["FASTLANE_TEAM_ID"] = "YOUR_TEAM_ID"
```

**Comment by PhilippOtto89** [comment]
Thanks for your answer! I think you're right. I changed the call to

`other_action.register_device(
          [...]
        )`

and it works properly. Thanks again!
