### ISSUE TITLE
Can't save IAP details

### ISSUE THREAD

**Issue by dominiclvrpl** [fastlane/fastlane#15329]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

$app = Spaceship::Application.find('xxxxxxxxxx')
purchase = $app.in_app_purchases.find("xxxxxxx")
p = purchase.edit
p.review_notes="test"
p.review_screenshot="/Users/xxxxx/Desktop/640x920ss-80.png"
p.save!

causes Error in playground
so i can not save IAP changes
In other issues like https://github.com/fastlane/fastlane/issues/9826 says that if you provide review_notes and review_screenshot before saving, everything works fine. But not in my case

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>Spaceship::Tunes::Error: ITC.response.error.OPERATION_FAILED
from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/tunes/tunes_client.rb:230:in `handle_itc_response'</pre>
</details>

### Environment

<details>
  <pre><details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.5                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.20.1 (Apple Git-117)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.5 (18F132)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.3                                                           |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.131.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 2.0.2        |
| faraday_middleware        | 0.13.1       |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| json                      | 2.2.0        |
| io-console                | 0.4.5        |
| excon                     | 0.66.0       |
| rubyzip                   | 1.2.4        |
| CFPropertyList            | 3.0.1        |
| libxml-ruby               | 2.9.0        |
| atomos                    | 0.1.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| claide                    | 1.0.3        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| fastimage                 | 2.1.7        |
| addressable               | 2.7.0        |
| psych                     | 2.1.0.1      |
</details>

*generated on:* **2019-09-18**
</details>
</pre>
</details>

**Comment by janpio** [comment]
Ping @max-ott

**Comment by dominiclvrpl** [comment]
> @dominiclvrpl just run the exact same code for one of our test apps and could save them without any issues.
> 
> ```
> iap = app.in_app_purchases.find("031019.1123.itc")
> p = iap.edit
> p.review_notes = "test"
> p.review_screenshot = "/Users/xxxxx/Desktop/iphone65-en-US-1.jpg"
> p.save!
> => nil // response
> ```
> 
> Are you sure there are not any other errors? (Wrong screenshot size, missing name, price etc.) Does it work through App Store Connect manually?

@max-ott yes its work through App Store Connect manually!
Screenshot is exact same as the purchases screenshot, wich is approved now in my app.
There is no missing informations because i access to it by command
$app.in_app_purchases.find("product_Id")
so i get my ready_for_sale product from app store connect, and try only to change review_notes and review_screenshot

**Comment by dominiclvrpl** [comment]
@max-ott So the reason why i tryin to change IAP details is to change pricing intervals.
When i try it, im getting Spaceship::Tunes::Error: ITC.response.error.OPERATION_FAILED
In applestoreconnect my purchase is going in status Waiting for upload, and its got two Information fields
The first one is old - wich was before iap edit. It has status Approved
The second one is new, and has status Download Pending. 
Also button Turn off content hosting enables. And label "If you turn off content hosting, the new version of the in-app purchase and all changes made to the localization will be deleted." near the button. So when i click it, all changes dissapears. 

Maybe this information would help.

**Comment by dominiclvrpl** [comment]
Ping @max-ott

**Comment by max-ott** [comment]
Changing prices for live iaps does currently not work with the latest version of spaceship.
