### ISSUE TITLE
get_version_number can't find MARKETING_VERSION when target value is inherited from project settings

### ISSUE THREAD

**Issue by ilendemli** [fastlane/fastlane#15322]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
get_version_number can't find MARKETING_VERSION when target value is inherited from project settings and fails with the following error:
`[!] Unable to find Xcode build setting: MARKETING_VERSION`

##### Command executed
bundle exec fastlane run get_version_number

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                    |
| --------------------------- | -------------------------------------------------------- |
| OS                          | 10.14.6                                                  |
| Ruby                        | 2.4.5                                                    |
| Bundler?                    | true                                                     |
| Git                         | git version 2.21.0 (Apple Git-122)                       |
| Installation Source         | ~/.rvm/gems/ruby-2.4.5/bin/fastlane                      |
| Host                        | Mac OS X 10.14.6 (18G95)                                 |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.5/lib                             |
| OpenSSL Version             | OpenSSL 1.1.1b  26 Feb 2019                              |
| Is contained                | false                                                    |
| Is homebrew                 | false                                                    |
| Is installed via Fabric.app | false                                                    |
| Xcode Path                  | /Applications/Xcode-11.GM.Seed.2.app/Contents/Developer/ |
| Xcode Version               | 11.0                                                     |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

defaults = { :projectFile => "App.xcodeproj" }

private_lane :basic do
	appicon(
		appicon_devices: [:ipad, :iphone, :ios_marketing],
		appicon_path: "App/Supporting Files/Assets.xcassets"
	)
end

lane :generate_app_icon do
	basic
end

lane :beta do |options|
	options[:scheme] = "App INT"

	create_temporary_keychain_if_needed
	match(type: "appstore", app_identifier: ["com.example.app"])

	build options
	testflight_upload options

	postToSlack(options)
end

lane :store do |options|
	options[:scheme] = "App PROD"

	create_temporary_keychain_if_needed
	match(type: "appstore", app_identifier: ["com.example.app"])
	
	build options
	testflight_upload options
	
	postToSlack(options)
end

private_lane :build do |options|
	ensure_git_status_clean
	cocoapods(repo_update: true)
	increment_build_number
	gym(scheme: options[:scheme], output_directory: "./build", output_name: get_output_name(options), xcargs: "-allowProvisioningUpdates", export_xcargs: "-allowProvisioningUpdates")
	sh("cd .. && pod deintegrate")
	git_commit(path: ".", message: "New Build: " + get_tag_name(options))
	push_to_git_remote
end

private_lane :testflight_upload do |options|
	pilot(skip_waiting_for_build_processing: true)
end

before_all do |lane, options|
	xcode_install(version: "11.0")
end

after_all do |lane, options|
	notification(subtitle: "🎉 Succeeded", message: "yay")
end

error do |lane, exception, options|
	sh("cd .. && pod deintegrate")
	notification(subtitle: "💩 Error", message: "damn")
	cleanup_temporary_keychain
end

def get_tag_name(options)
  return get_version_number(xcodeproj: options[:xcodeproj], target: options[:scheme]) + "_b" + get_build_number
end

def get_output_name(options)
	return options[:scheme] + "_b" + get_build_number + ".ipa"
	cleanup_temporary_keychain
end

def create_temporary_keychain_if_needed
	# only do this when running on CI
	if !Helper.ci?
	  UI.message("Currently not running on CI system, skipping keychain setup")
	  return
	end
	password = "" # we don't need a password, as the keychain gets removed after each run anyway
	keychain_name = "fastlane_tmp_keychain"
	ENV["MATCH_KEYCHAIN_NAME"] = keychain_name
	ENV["MATCH_KEYCHAIN_PASSWORD"] = password
	cleanup_temporary_keychain
	UI.message("creating temp keychain")
	create_keychain(
	  name: keychain_name,
	  default_keychain: true,
	  unlock: true,
	  timeout: 3600,
	  lock_when_sleeps: true,
	  password: password
	)
  end

  def cleanup_temporary_keychain
	# only do this when running on CI
	if !Helper.ci?
	  UI.message("Currently not running on CI system, skipping keychain cleanup")
	  return
	end
	home_dir = ENV["HOME"]
	keychain_path = "#{home_dir}/Library/Keychains/fastlane_tmp_keychain-db"#Helper.keychain_path("fastlane_tmp_keychain-db")
	UI.message("looking for temp keychain at: #{keychain_path}")
	if File.exists?(keychain_path)
	  UI.message("found temp keychain")
	  delete_keychain(keychain_path: keychain_path)
	else
	  UI.message("no temp keychain found")
	end
  end

def postToSlack(options)
 slack(
  message: "App successfully uploaded to Store, will now be processing!",
  use_webhook_configured_username_and_icon: true,
  channel: "general",  # Optional, by default will post to the default channel configured for the POST URL.
  slack_url: "hookurl", # appuptodate channel default channel hook
  payload: {  # Optional, lets you specify any number of your own Slack attachments.
	"Build Type" => options[:scheme],
	"Build Date" => Time.new.to_s,
	"Build number" => get_build_number,
	"Additional Parameters" => "will be processing now...",
  })
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.example.app" # The bundle identifier of your app
apple_id "example@app.com" # Your Apple email address
itc_team_id "12345678"

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.131.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status |
| ----------------------- | ------- | ------------- |
| fastlane-plugin-appicon | 0.14.1  | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 2.0.1        |
| CFPropertyList            | 3.0.1        |
| concurrent-ruby           | 1.1.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.11.1     |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.3        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.7.5        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.2.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.1        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| cocoapods                 | 1.7.5        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.66.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.1        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.0904  |
| mime-types                | 3.3          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.4        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-appicon   | 0.14.1       |
| xcode-install             | 2.6.0        |
</details>

*generated on:* **2019-09-17**
</details>

**Comment by janpio** [comment]
Ok, we recently had PRs that improved/enabled `MARKETING_VERSION` in the first place, so it was to be expected that some edge cases were missed here. 

Can you explain exactly what is going on here and how it works?

The current code looks like this:
https://github.com/fastlane/fastlane/blob/1a50a980c3999c74669355d4fe74338169327b9e/fastlane/lib/fastlane/actions/get_version_number.rb#L19-L27

If I understood you correctly, we need another fallback that gets the data from somewhere else?

**Comment by ilendemli** [comment]
> Ok, we recently had PRs that improved/enabled `MARKETING_VERSION` in the first place (e.g. #15285), so it was to be expected that some edge cases were missed here.
> 
> Can you explain exactly what is going on here and how it works?
> 
> The current code looks like this:
> 
> https://github.com/fastlane/fastlane/blob/1a50a980c3999c74669355d4fe74338169327b9e/fastlane/lib/fastlane/actions/get_version_number.rb#L19-L27
> 
> If I understood you correctly, we need another fallback that gets the data from somewhere else?

I have seen those PRs. As I understood this part of the code looks in the target build settings and gets the MARKETING_VERSION value from there, but in Xcode you can have set the MARKETING_VERSION for the project itself and inherit the value from the targets, in this case, a fallback to the project build settings is necessary. something like this returns the correct value for me, but then there are Debug and Release configurations:
```
project.build_configurations.each do |configuration|
	value = configuration.build_settings["MARKETING_VERSION"]
end
```

**Comment by janpio** [comment]
Ok, then my understanding was correct enough.

Looking forward to see a PR of your branch ;)

**Comment by ilendemli** [comment]
PR is open and ready to be reviewed :)

**Comment by adamirowe** [comment]
This would be very helpful for our project as well. Thank you for submitting @ilendemli.

**Comment by adamirowe** [comment]
Did this get closed by this being merged in? https://github.com/fastlane/fastlane/pull/15285

**Comment by emreberge** [comment]
> Did this get closed by this being merged in? #15285

Don't think so I'm on `2.133.0` and still getting the error: Unable to find Xcode build setting: MARKETING_VERSION

**Comment by ilendemli** [comment]
No, the changes are awaiting review and has not been merged yet.

**Comment by bgold0** [comment]
It looks like this issue was merged but I am still have this error on `2.134.0`

**Comment by adamirowe** [comment]
Yeah, I'm still getting `$(inherited)` here. Any advice on how to proceed?

**Comment by janpio** [comment]
Open a new issue and describe your full problem you are having.

**Comment by seboslaw** [comment]
Also having this issue

**Comment by luowei** [comment]
我是使用 Xcodeproj 库顺利的解决了xcode11下fastlane 通过get_version_number获取不到版本号的问题。如下：
在Gemfile里添加：`gem "xcodeproj"`
```
project_version = get_version_number(xcodeproj: "xxxx.xcodeproj", target: "xxxx")
project = Xcodeproj::Project.open('../xxxx.xcodeproj')
target = project.targets.first
if project_version !~ /\d+\./
  target.build_configurations.each do |configuration|
    project_version = configuration.build_settings["MARKETING_VERSION"]
  end
end
```
