### ISSUE TITLE
Unauthorized access on doing fastlane produce

### ISSUE THREAD

**Issue by ari89-dev** [fastlane/fastlane#15320]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> fastlane produce is not working for me. Getting unauthorized access error </pre>
</details>

### Environment

<details>
  <pre> fastlane produce is not working for me. Getting unauthorized access error. </pre>
</details>

**Comment by janpio** [comment]
Please fill the issue template with the information it asks for instead of ignoring it.
