### ISSUE TITLE
First release in Android

### ISSUE THREAD

**Issue by bakikocak** [fastlane/fastlane#15336]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Should first release in Android be done manually?

#### Question Description
I am about to release a brand new Android App and I would like to know whether I should submit the first apk manually instead of using Fastlane. I have searched over the internet and documentation but could not find any info related to first apk release.

**Comment by janpio** [comment]
The first release can be done with fastlane. 

You have to upload the first apk or bundle manually though, so Google Play Console connects your app to the bundle ID / package name which is used as the identifier for uploading and releasing an app. Google unfortunately does not have an API for that.
