### ISSUE TITLE
[Frameit] The keyword, title and device frame sometimes have a vertical offset with "stack_title" : true

### ISSUE THREAD

**Issue by funnel20** [fastlane/fastlane#15332]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
This issue is similar to https://github.com/fastlane/fastlane/issues/10440 which focused on "stack_title" : false.
Now we have set "stack_title" to true, meaning the keyword is above the title. And these 2 text fields are stacked above the device frame.
The issue is that the vertical distances between the 2 text fields and between the title and the top of the frame. This depends whether the strings in the text fields have pixels below (e.g. the "g") the baseline of the text, or above it (like the "k").

The comparison between these 2 screenshots shows this clearly, by the dashed lines that we added:

![iPhone-Xs-Max---before](https://user-images.githubusercontent.com/2139844/65135871-f5cca800-da06-11e9-8cb7-5d2441f1749a.png)

I'll try to create the same solution with the `trim_boxes` as in https://github.com/fastlane/fastlane/issues/10440 for this vertical stacked situation.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | ~/.rvm/gems/ruby-2.2.4/bin/fastlane         |
| Host                        | Mac OS X 10.14.6 (18G95)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.2.4/lib                |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.3                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
#
#  Fastfile
#  myTifi
#
#  Created by Martijn Koopman on 27/09/17.
#  Copyright © 2017 iMKapps. All rights reserved.
#
#  $Rev: 4769 $
#  $Date:: 2019-04-26 #$

before_all do
    # Set Xcode version
    ENV['DEVELOPER_DIR'] = '/Applications/Xcode 10.1.app/Contents/Developer'
end

# Create a lane for SnapShot:
# Run this via Terminal via: fastlane screenshots
lane :screenshots do
    # Generate screenshots for the App Store:
    snapshot
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.130.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                   | Version      |
| --------------------- | ------------ |
| executable-hooks      | 1.3.2        |
| bundler-unload        | 1.0.2        |
| rubygems-bundler      | 1.4.4        |
| bundler               | 1.16.0       |
| slack-notifier        | 2.3.2        |
| rouge                 | 2.0.7        |
| xcpretty              | 0.3.0        |
| terminal-notifier     | 2.0.0        |
| multipart-post        | 2.0.0        |
| word_wrap             | 1.0.0        |
| public_suffix         | 2.0.5        |
| tty-cursor            | 0.5.0        |
| tty-spinner           | 0.8.0        |
| babosa                | 1.0.2        |
| colored               | 1.2          |
| commander-fastlane    | 4.4.6        |
| faraday               | 0.15.4       |
| http-cookie           | 1.0.3        |
| faraday-cookie_jar    | 0.0.6        |
| gh_inspector          | 1.1.3        |
| mini_magick           | 4.9.5        |
| rubyzip               | 1.2.2        |
| security              | 0.1.3        |
| naturally             | 2.1.0        |
| simctl                | 1.6.3        |
| jwt                   | 2.1.0        |
| declarative-option    | 0.1.0        |
| representable         | 3.0.4        |
| mime-types-data       | 3.2016.0521  |
| mime-types            | 3.1          |
| signet                | 0.11.0       |
| memoist               | 0.16.0       |
| os                    | 0.9.6        |
| googleauth            | 0.6.7        |
| httpclient            | 2.8.3        |
| google-api-client     | 0.23.9       |
| google-cloud-env      | 1.0.5        |
| google-cloud-core     | 1.3.0        |
| digest-crc            | 0.4.1        |
| google-cloud-storage  | 1.16.0       |
| emoji_regex           | 0.1.1        |
| tty-screen            | 0.6.4        |
| json                  | 2.1.0        |
| highline              | 1.7.10       |
| excon                 | 0.60.0       |
| CFPropertyList        | 2.3.6        |
| plist                 | 3.4.0        |
| atomos                | 0.1.3        |
| claide                | 1.0.2        |
| colored2              | 3.1.2        |
| nanaimo               | 0.2.6        |
| xcodeproj             | 1.10.0       |
| unf                   | 0.1.4        |
| domain_name           | 0.5.20170404 |
| faraday_middleware    | 0.12.2       |
| fastimage             | 2.1.1        |
| terminal-table        | 1.8.0        |
| unicode-display_width | 1.3.0        |
| addressable           | 2.5.2        |
| multi_json            | 1.13.1       |
| psych                 | 2.0.8        |
| retriable             | 3.1.1        |
| uber                  | 0.1.0        |
| declarative           | 0.0.10       |
</details>

*generated on:* **2019-09-18**
</details>

**Comment by funnel20** [comment]
Working on it.
For proper debugging, added the yellow highlight again by adding the follow temporary lines to `text_image.combine_options do |i|` of `put_title_into_background()` in `editor.rb`:
```
i.background 'yellow'
i.alpha 'remove'
```

This show the problem of the differents heights (and vertical offsets) of the 2 keyword text fields between the left and right screenshot:

<img width="1005" alt="iPhone Xs Max - before highlighted" src="https://user-images.githubusercontent.com/2139844/65318424-dae06c00-db9d-11e9-9ddd-ba377d9c480d.png">

The solution from https://github.com/fastlane/fastlane/issues/10440 had a condition in `put_title_into_background()` to only adjust the trim box for side-by-side text images (i.e. when `stack_title` is false).

Removing this condition also applies it for the stacked texts with the desired result:

<img width="1011" alt="Screenshot 2019-09-20 at 11 44 23" src="https://user-images.githubusercontent.com/2139844/65317910-fdbe5080-db9c-11e9-8bb3-7afca6b3ea0b.png">
 
**Problem solved?**
For these particular texts yes.

But for others not, e.g.:

<img width="1006" alt="Different trimboxes per screenshots" src="https://user-images.githubusercontent.com/2139844/65319353-b6858f00-db9f-11e9-9a36-e4a4f8ab2d7c.png">

Why? Because `put_title_into_background()` is called for each screenshot. So the trim box adjustment is only done for the 2 text fields on each _individual_ screenshot.
The left image shows that the title "are" is corrected to the proper height of the keyword "We".
The right image shows that keyword "You" is corrected to the proper height of the title "they".
But there is no adjustment between both screenshots.

The **proper solution** should be that the trim boxes of _all_ screenshots are analysed before adjusting them. At least for each device frame and language, as they are shown next to each other in the App Store.
With the current architecture of frameit this is not possible, as each screenshot is edited individually and has no knowledge of the others.
Has anybody any suggestions?

**Comment by janpio** [comment]
Ugh, that sounds like a nasty problem. No way to work around having to adds this new inter-screenshot coordination?

**Comment by funnel20** [comment]
This new analysis with the consistency of text field heights between screenshots also applies to issue #10440. 

So there are 2 issues here:
1. This current issue on a per screenshot basis for stack_title is false. 
As mentioned this can be solved by removing the condition. That will close this issue. 
2. The new issue with the consistency of text field heights between screenshots. Shall I open a new issue?

**Comment by funnel20** [comment]
A possible work-around for the inter-screenshot coordination might be to use hard coded strings for each locale, that will be used to determine the maximum top and bottom boundaries of the text fields. For example “Wy” for English. And “Åy” for Danish.
Of course these are too short, since longer strings will shrink the font size. So these 2 characters should be temporarily appended (or replace the last 2) in order to have a similar width of the text field. 
After this determination of the trim box height, the original strings can be used with this dimension. 
Because these same hard coded 2 characters are used in all screenshots for the same language, I expect that all text fields will have the same height and vertical offset. 
What do you think?

**Comment by janpio** [comment]
>     2\. Shall I open a new issue?

Yes please, more structure is always better.



>  What do you think?

Interesting theory, if this really works - why not 🤷‍♀

**Comment by funnel20** [comment]
I created issue #15356 for the inter-screenshot coordination.

**Comment by funnel20** [comment]
**Solution to this issue**

Remove the condition to only adjust the trim box for side-by-side text images (i.e. when stack_title is false) in _editor.rb_.

**Improvement**
While running in --verbose, the UI.Verbose() statements display a reference to the trim box object, instead of the data:

> Trim box for key "keyword" is adjusted to align bottom: #<Frameit::Trimbox:0x007fb0ac494da0>

This has been solved by adding a new method `json_string_format` to Class _trim_box.rb_ that returns the trimbox parameters in a human readable JSON string format:

> Trim box for key "keyword" is adjusted to align bottom: {"width" : 857, "height" : 87 , "offset_x" : 2463, "offset_y" : 1025}

**Comment by funnel20** [comment]
Hey @janpio , what needs to be to done to get this PR merged?

**Comment by janpio** [comment]
As always: Someone has to spend the time to make sure it doesn't break anything and be confident enough in the changes it makes.

**Comment by funnel20** [comment]
I totally understand that. 
I only removed 1 condition in the logic, while supplying quite some proof of the result, incl. all screenshot comparisons. So this shouldn't be too much work to verify, let alone take 5 weeks.
We really miss this solution in our fastlane workflow.

**Comment by janpio** [comment]
cc @joshdholtz @mollyIV

**Comment by funnel20** [comment]
Guys, what needs to be done to get my PR reviewed (a few lines of code)?

Waiting 10 weeks without any progress, while there are weekly releases, doesn't feel like a reward for investing time in improving your product.

**Comment by funnel20** [comment]
@janpio @joshdholtz @mollyIV And 10 weeks became almost 2 years.....🤔

**Comment by joshdholtz** [comment]
Omg 😱 Will get this on my list for today!

**Comment by funnel20** [comment]
@joshdholtz That would be awesome.

**Comment by funnel20** [comment]
@joshdholtz I've added 7 new issues for Frameit: https://github.com/fastlane/fastlane/issues/created_by/funnel20

My major concern is that current logic about "latest" is not appropriate anymore (see: https://github.com/fastlane/fastlane/issues/19006 ), where multiple generations of the same device should live next to each other, as indicated by issue https://github.com/fastlane/fastlane/issues/18975 about iPad Pro 12.9". 

I would really want to offer my help in improving frameit , but I'm very hesitant based in lacking support from the repo owners. 
The work I did in the past always took ages to get feedback on, or even implemented. Such as this PR which is open for almost 2 years.

**Comment by funnel20** [comment]
> Omg 😱 Will get this on my list for today!

😴

**Comment by janpio** [comment]
He just said he would put it on his list, not that he would be able to work through his list instantly 🤣

**Comment by funnel20** [comment]
@janpio  Is frameit applying for https://killedbygoogle.com ?
There was even no response on [my offer](https://github.com/fastlane/fastlane/issues/15332#issuecomment-868995974) to help.

**Comment by joshdholtz** [comment]
@funnel20 Sorry! There is always so many things coming in and it's hard to balance it all.

It's be happy to collaborate and review a PR if you want to take a stab at it 🤷‍♂️ Otherwise I'll make sure this gets moved up near the top of my list again

**Comment by funnel20** [comment]
@joshdholtz PR https://github.com/fastlane/fastlane/pull/15359 is open for almost 2 years. I've asked several times for approval of that. 
Either I don't understand your process, or either Google doesn't follow it.
Moreover, on the 7 new issues https://github.com/fastlane/fastlane/issues/created_by/funnel20 that I entered 2 months ago, was zero response. They are all closed by the bot.
So apparently my contributions are not appreciated.
