### ISSUE TITLE
Could not find action, lane or variable 'appcenter_upload'

### ISSUE THREAD

**Issue by dfiggtns** [fastlane/fastlane#15335]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
What tool/action do you have a question about? 
appcenter_upload
Is this a question about documentation?
No
Is this a question about a third party plugin? (If so, please go to the plugin repository first)
Yes. Done, but no joy, which is why I'm here.

#### Question Description

I've tried to install this plugin following the instructions in the readme and I get the following output:

    Plugin 'fastlane-plugin-appcenter' was added to './fastlane/Pluginfile'
    Make sure to commit your Gemfile, Gemfile.lock and Pluginfile to version control
    Installing plugin dependencies...
    Successfully installed plugins

but I get the following error:

    Could not find action, lane or variable 'appcenter_upload'. Check out the documentation for more details: https://docs.fastlane.tools/actions

when I run the following command:

    bundle exec fastlane appcenter

I've checked out the documentation, but there's no mention of appcenter_upload on the page.

My gemfile is:

    source "https://rubygems.org"

    gem "fastlane"
    gem "cocoapods"

    plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
    eval_gemfile(plugins_path) if File.exist?(plugins_path)

My fastfile lane is:

    lane :appcenter do
       appcenter_upload(
        api_token: "????",
        apk: "../path-to-apk/myapp.apk",
        app_name: "MyApp",
        app_os: 'Android',
        owner_name: "MyOwner",
      )
    end

So I have a couple of questions:

1. Is appcenter_upload available in fastlane yet?
2. If it is, why is fastlane not finding the appcenter_upload action when the appcenter plugin has supposedly been added?

**Comment by dfiggtns** [comment]
Out from fastlane env:

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.18.0                          |
| Installation Source         | ~/.rbenv/versions/2.5.1/bin/fastlane        |
| Host                        | Mac OS X 10.14.6 (18G95)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2p  14 Aug 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.3                                        |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.131.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| bundler                   | 1.16.4       |
| CFPropertyList            | 3.0.1        |
| concurrent-ruby           | 1.1.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.11.1     |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.3        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.7.5        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.2.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.4.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| cocoapods                 | 1.7.5        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.66.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.1        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.0904  |
| mime-types                | 3.3          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.4        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>


*generated on:* **2019-09-19**
</details>

**Comment by janpio** [comment]
> Is appcenter_upload available in fastlane yet?

It is not, as it is a plugin that provides that functionality. 

But you seem to have installed it, so it should work. What does you `Pluginfile `look like?

**Comment by dfiggtns** [comment]
The Pluginfile in both the android and ios platforms is:

    # Autogenerated by fastlane
    #
    # Ensure this file is checked in to source control!

    gem 'fastlane-plugin-appcenter'

**Comment by janpio** [comment]
Can you please post the full output you are getting when running a lane?

**Comment by dfiggtns** [comment]
When I run the command from platforms/android (I get the same output in platforms/ios too):

    bundle exec fastlane add_plugin appcenter

the output is:

    [15:47:16]: It seems like you wanted to load some plugins, however they couldn't be loaded
    [15:47:16]: Please follow the troubleshooting guide: https://docs.fastlane.tools/plugins/plugins-troubleshooting/
    [15:47:16]: Plugin 'fastlane-plugin-appcenter' was added to './fastlane/Pluginfile'
    [15:47:16]: Make sure to commit your Gemfile, Gemfile.lock and Pluginfile to version control
    Installing plugin dependencies...
    Successfully installed plugins

**Comment by dfiggtns** [comment]
@janpio I've posted the output you asked for. Do you have any ideas what could be wrong?

**Comment by janpio** [comment]
No, that looks pretty much standard and nothing pops out. I guess something might be funky with your rubies and the gem is landing in the wrong one or something like that, sorry - no idea how to debug this from here.

**Comment by dfiggtns** [comment]
Any idea what would cause this message?

fast_file.rb:154:in `method_missing' Fastfile:33:in `block (2 levels) in parsing_binding'

**Comment by janpio** [comment]
This is a red herring, it can actually just not find the plugin's action which leads to this error message.
