### ISSUE TITLE
Match not setting provisioning profile for Gym as expected

### ISSUE THREAD

**Issue by hammadzz** [fastlane/fastlane#15338]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Using `match` does not set the provisioning profile for `gym` as would be expected. It seems it is because the provisioning profile is unset in xcodeproj. See env output below for details.

To fix it I can manually open up the xcodeproj and select the profile from the dropdown under release. I would then need to save this change to xcodeproj. But that defeats the point.

Another fix from fastlane is to use `update_project_provisioning` to select the profile. I don't like this fix either. Using `match` with `gym` should just work as expected per the documentation.

### Error
```"FBApp" requires a provisioning profile. Select a provisioning profile for the "Release" build configuration in the project editor. (in target 'FBApp')```

As stated earlier the fix is to use `update_project_provisioning` to set the provisioning profile after match downloads and installs it.

##### Command executed

`bundle exec fastlane ios my_poc`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.5.6                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.23.0                          |
| Installation Source         | ~/.rbenv/versions/2.5.6/bin/fastlane        |
| Host                        | Mac OS X 10.14.6 (18G95)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.6/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2s  28 May 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.3                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# iOS
#----------------------------------------------------#
platform :ios do |options|
  project_name = ENV.fetch('PROJECT_NAME', 'FBApp')
  scheme = ENV.fetch('SCHEME', 'FBApp')
  team_id = CredentialsManager::AppfileConfig.try_fetch_value(:team_id)
  app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)

  xcodeproj = "./ios/#{project_name}.xcodeproj"
  workspace = "./ios/#{project_name}.xcworkspace"
  
  before_all do
    if is_ci?
      setup_circle_ci
    end
  end

  lane :debugg do | options |
    puts "xcodeproj #{xcodeproj}"
    puts "workspace #{workspace}"
    puts "scheme #{scheme}"
    puts "team_id #{team_id}"
    puts "app_identifier #{app_identifier}"
  end

  lane :my_poc do | options |
    debugg
    disable_automatic_code_signing(path: xcodeproj)
    match(
      type: "appstore", 
      app_identifier: app_identifier,
      shallow_clone: true,
      clone_branch_directly: true
    )
    # Uncomment to fix the provisioning profile not set issue
    # update_project_provisioning(
    #   xcodeproj: xcodeproj,
    #   target_filter: "GdApp",
    #   profile:ENV["sigh_com.rbc.ventures.garbageday_appstore_profile-path"],
    #   build_configuration: "Release"
    # )
    gym(
      workspace: workspace,
      scheme: scheme,
      configuration: "Release",
      clean: true,
      export_method: "app-store",
      output_directory:"./build/",
      export_options: {
        method: "app-store",
        provisioningProfiles: { 
          "com.foo.bar" => ENV["sigh_com.foo.bar_appstore_profile-name"]
        }
      },
      codesigning_identity:"iPhone Distribution: FooBar Inc (XXXXXXXXPT)",
      output_name: "poc_appstore_build.ipa"
    )
  end

end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# Android
#----------------------------------------------------#
package_name "com.foo.bar"

# iOS
#----------------------------------------------------#
app_identifier "com.foo.bar"
team_id "XXXXXXXXPT"
itc_team_id "XXXXX04"
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.131.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                         | Version | Update-Status |
| ---------------------------------------------- | ------- | ------------- |
| fastlane-plugin-android_change_string_app_name | 0.1.1   | ✅ Up-To-Date  |
| fastlane-plugin-versioning_android             | 0.1.0   | ✅ Up-To-Date  |
| fastlane-plugin-appcenter                      | 1.4.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                            | Version      |
| ---------------------------------------------- | ------------ |
| did_you_mean                                   | 1.2.0        |
| bundler                                        | 2.0.2        |
| CFPropertyList                                 | 3.0.1        |
| public_suffix                                  | 2.0.5        |
| addressable                                    | 2.7.0        |
| atomos                                         | 0.1.3        |
| babosa                                         | 1.0.2        |
| claide                                         | 1.0.3        |
| colored                                        | 1.2          |
| colored2                                       | 3.1.2        |
| highline                                       | 1.7.10       |
| commander-fastlane                             | 4.4.6        |
| declarative                                    | 0.0.10       |
| declarative-option                             | 0.1.0        |
| digest-crc                                     | 0.4.1        |
| unf_ext                                        | 0.0.7.6      |
| unf                                            | 0.1.4        |
| domain_name                                    | 0.5.20190701 |
| dotenv                                         | 2.7.5        |
| emoji_regex                                    | 1.0.1        |
| excon                                          | 0.66.0       |
| multipart-post                                 | 2.0.0        |
| faraday                                        | 0.15.4       |
| http-cookie                                    | 1.0.3        |
| faraday-cookie_jar                             | 0.0.6        |
| faraday_middleware                             | 0.13.1       |
| fastimage                                      | 2.1.7        |
| gh_inspector                                   | 1.1.3        |
| jwt                                            | 2.1.0        |
| memoist                                        | 0.16.0       |
| multi_json                                     | 1.13.1       |
| os                                             | 1.0.1        |
| signet                                         | 0.11.0       |
| googleauth                                     | 0.6.7        |
| httpclient                                     | 2.8.3        |
| mime-types-data                                | 3.2019.0904  |
| mime-types                                     | 3.3          |
| uber                                           | 0.1.0        |
| representable                                  | 3.0.4        |
| retriable                                      | 3.1.2        |
| google-api-client                              | 0.23.9       |
| google-cloud-env                               | 1.2.1        |
| google-cloud-core                              | 1.3.1        |
| google-cloud-storage                           | 1.16.0       |
| json                                           | 2.2.0        |
| mini_magick                                    | 4.9.5        |
| multi_xml                                      | 0.6.0        |
| plist                                          | 3.5.0        |
| rubyzip                                        | 1.2.4        |
| security                                       | 0.1.3        |
| naturally                                      | 2.2.0        |
| simctl                                         | 1.6.6        |
| slack-notifier                                 | 2.3.2        |
| terminal-notifier                              | 2.0.0        |
| unicode-display_width                          | 1.6.0        |
| terminal-table                                 | 1.8.0        |
| tty-screen                                     | 0.7.0        |
| tty-cursor                                     | 0.7.0        |
| tty-spinner                                    | 0.9.1        |
| word_wrap                                      | 1.0.0        |
| nanaimo                                        | 0.2.6        |
| xcodeproj                                      | 1.12.0       |
| rouge                                          | 2.0.7        |
| xcpretty                                       | 0.3.0        |
| xcpretty-travis-formatter                      | 1.0.0        |
| mini_portile2                                  | 2.4.0        |
| nokogiri                                       | 1.10.4       |
| fastlane-plugin-android_change_string_app_name | 0.1.1        |
| fastlane-plugin-appcenter                      | 1.4.0        |
| fastlane-plugin-versioning_android             | 0.1.0        |
</details>

*generated on:* **2019-09-19**
</details>

**Comment by parkycai** [comment]
Same here. Any updates?

**Comment by hammadzz** [comment]
@parkycai I do have a workaround that is using `update_project_provisioning` see my fastfile in the original post under Environment.

**Comment by parkycai** [comment]
> @parkycai I do have a workaround that is using `update_project_provisioning` see my fastfile in the original post under Environment.

Unfortunately, that didn't work for me either.

**Comment by smolster** [comment]
I've had this issue with fastlane forever, and it seems it's actually intended functionality, though I don't know why.

`match` seems to **only** handle provisioning for the archiving/exporting phase, but NOT the build phase. So, you're calling match, but the build step of your `gym` call is just using whatever provisioning is specified in your xcodeproj.

It'd be great it if someone from the team could elaborate on why this is the decided functionality!

It feels like running `match` before running `gym` should ensure that both the build phase and the export phase use the correct provisioning profiles retrieved using `match`.
