### ISSUE TITLE
CircleCI: Could not find fastlane in current directory.

### ISSUE THREAD

**Issue by trickeyd** [fastlane/fastlane#15341]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
I am using fastlane with CircleCI. When I attempt to do so i am greeted with the following errors:

```
 Could not find fastlane in current directory. Make sure to have your fastlane configuration files inside a folder called "fastlane". Would you like to set fastlane up?
```

and

```
bundler: failed to load command: fastlane (/usr/local/bundle/bin/fastlane)
FastlaneCore::Interface::FastlaneCrash: [!] Could not retrieve response as fastlane runs in non-interactive mode
```
#### Question Description
Everything seems to be present and in line with all the docs i have read - I need to figure out how to proceed with the automated build.
The error links to 3 issues here, but all have been closed without resolution due to the user's question not being well formed enough.

Before running fastlane i use the following commands which execute without a problem (circleci yml):
- run: gem install bundler
- run: bundle install
- run: bundle update fastlane

Then i list the directory which clearly shows the fastlane folder is present, and i list contents of the folder itself which shows the FastFile inside.

Finally i invoke:
`bundle exec fastlane` (i actually call a particular lane but both fail in the same way)

I get the following:

```
[⠋] 🚀 [⠙] 🚀 [⠹] 🚀 [⠸] 🚀 [⠼] 🚀 [⠴] 🚀 [✔] 🚀 
[15:49:49]: Sending anonymous analytics information
[15:49:49]: Learn more at https://docs.fastlane.tools/#metrics
[15:49:49]: No personal or sensitive data is sent.
[15:49:49]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
[15:49:49]: Could not find fastlane in current directory. Make sure to have your fastlane configuration files inside a folder called "fastlane". Would you like to set fastlane up?

Looking for related GitHub issues on fastlane/fastlane...

➡️   Could not find fastlane in current directory. Make sure to have your fastlane configuration files inside a folder called "fastlane". Would you like to set fastlane up?
    https://github.com/fastlane/fastlane/issues/14974 [closed] 5 💬
    2 weeks ago

➡️  Fastlain Android screengrab. Could not retrieve response as fastlane runs in non-interactive mode
    https://github.com/fastlane/fastlane/issues/14869 [closed] 6 💬
    25 Jul 2019

➡️  FastLane 2.124 FastlaneCore::Interface::FastlaneCrash: [!] Could not retrieve response as fastlane runs in non-interactive mode
    https://github.com/fastlane/fastlane/issues/14835 [closed] 6 💬
    25 Jul 2019

and 40 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode&type=Issues&utf8=✓

bundler: failed to load command: fastlane (/usr/local/bundle/bin/fastlane)
FastlaneCore::Interface::FastlaneCrash: [!] Could not retrieve response as fastlane runs in non-interactive mode
  /usr/local/bundle/gems/fastlane-2.131.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!'
  /usr/local/bundle/gems/fastlane-2.131.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:155:in `verify_interactive!'
  /usr/local/bundle/gems/fastlane-2.131.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:133:in `confirm'
  /usr/local/bundle/gems/fastlane-2.131.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /usr/local/bundle/gems/fastlane-2.131.0/fastlane/lib/fastlane/commands_generator.rb:359:in `ensure_fastfile'
  /usr/local/bundle/gems/fastlane-2.131.0/fastlane/lib/fastlane/commands_generator.rb:107:in `block (2 levels) in run'
  /usr/local/bundle/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /usr/local/bundle/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /usr/local/bundle/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /usr/local/bundle/gems/fastlane-2.131.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /usr/local/bundle/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /usr/local/bundle/gems/fastlane-2.131.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
  /usr/local/bundle/gems/fastlane-2.131.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /usr/local/bundle/gems/fastlane-2.131.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /usr/local/bundle/gems/fastlane-2.131.0/bin/fastlane:23:in `<top (required)>'
  /usr/local/bundle/bin/fastlane:23:in `load'
  /usr/local/bundle/bin/fastlane:23:in `<top (required)>'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/version for documentation about this command.
Exited with code 1
```

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | debian_based 10.1                                       |
| Ruby                        | 2.4.7                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.20.1                                      |
| Installation Source         | /usr/local/bundle/bin/fastlane                          |
| Host                        | Debian GNU/Linux 10 debian_based 10.1 (4.15.0-1043-aws) |
| Ruby Lib Dir                | /usr/local/lib                                          |
| OpenSSL Version             | OpenSSL 1.1.1c  28 May 2019                             |
| Is contained                | false                                                   |
| Is homebrew                 | false                                                   |
| Is installed via Fabric.app | false                                                   |

### System Locale

| Variable | Value   |   |
| -------- | ------- | - |
| LANG     | C.UTF-8 | ✅ |
| LC_ALL   |         |   |
| LANGUAGE |         |   |

### fastlane files:

**No Fastfile found**

<details><summary>`./Appfile`</summary>

```ruby

# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.131.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.66.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.0.2        |
| faraday_middleware        | 0.13.1       |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| CFPropertyList            | 3.0.1        |
| addressable               | 2.7.0        |
| fastimage                 | 2.1.7        |
| json                      | 2.2.0        |
| rubyzip                   | 1.2.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| mime-types-data           | 3.2019.0904  |
| mime-types                | 3.3          |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| openssl                   | 2.0.9        |
| io-console                | 0.4.6        |
| psych                     | 2.2.2        |
</details>

**Comment by janpio** [comment]
Can you please post the full output of your CI run? The error messages you posted contradict themselves, if the first would be true you could not get the second one. We will have to look into what is going on here.

**Comment by trickeyd** [comment]
Thanks for our swift reply. Apologies for not getting back sooner but have been off the grid for a few days.

Yeah - I agree that they seem to contradict each other that is why I have been so confused.

This is the circleci yml that is breaking:
`
build:
    docker:
      - image: circleci/ruby:2.4-node
    working_directory: ~/project
    steps:
      - checkout:
          path: ~/project
      - run: gem install bundler
      - run: bundle install
      - run: bundle update fastlane
      - run: yarn version --patch
`

**yarn version --patch** hooks then calls: 

`
ls -a
ls fastlane
bundle exec fastlane update_version v:$npm_package_version && git add ./ios/Velocity/Info.plist && yarn config set version-git-message '[skip ci] version:%s'
`


And this is the output:
`
ls -a
.			   .github		ci2.sh
..			   .gitignore		e2e
.buckconfig		   .npmignore		endpoints.md
.circleci		   .npmrc		fastlane
.editorconfig		   .snyk		index.js
.env			   .vscode		ios
.env.blme.production	   .watchmanconfig	jest.mocks.js
.env.blme.staging	   Appfile		local.log
.env.eliteclub.production  BUSINESS_SETUP.md	metro.config.js
.env.eliteclub.staging	   Gemfile		package.json
.env.lux.production	   Gemfile.lock		rename-to-tsx.sh
.env.lux.staging	   QUEUE.md		rn-cli.config.js
.env.velocity.beta	   README.md		scripts
.env.velocity.production   ReactotronConfig.js	set_env.sh
.env.velocity.staging	   android		src
.env.vive.production	   app.json		template
.env.vive.staging	   asset_source		test-preprocessor.js
.env.whitelabel.staging    assets		tsconfig.json
.flowconfig		   babel.config.js	tslint.json
.git			   business.sh		yarn.lock
.gitattributes		   ci.sh
ls fastlane
FastFile  Matchfile  README.md
bundle exec fastlane update_version v:6.3.10 && git add ./ios/Velocity/Info.plist && yarn config set version-git-message '[skip ci] version:%s'
[⠋] 🚀 [⠙] 🚀 [⠹] 🚀 [⠸] 🚀 [⠼] 🚀 [⠴] 🚀 [✔] 🚀 
[16:04:22]: Sending anonymous analytics information
[16:04:22]: Learn more at https://docs.fastlane.tools/#metrics
[16:04:22]: No personal or sensitive data is sent.
[16:04:22]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
[16:04:22]: Could not find fastlane in current directory. Make sure to have your fastlane configuration files inside a folder called "fastlane". Would you like to set fastlane up?

Looking for related GitHub issues on fastlane/fastlane...

➡️  CircleCI: Could not find fastlane in current directory.
    https://github.com/fastlane/fastlane/issues/15341 [open] 2 💬
    4 days ago

➡️  Fastlain Android screengrab. Could not retrieve response as fastlane runs in non-interactive mode
    https://github.com/fastlane/fastlane/issues/14869 [closed] 6 💬
    22 hours ago

➡️  FastLane 2.124 FastlaneCore::Interface::FastlaneCrash: [!] Could not retrieve response as fastlane runs in non-interactive mode
    https://github.com/fastlane/fastlane/issues/14835 [closed] 6 💬
    22 hours ago

and 41 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode&type=Issues&utf8=✓

bundler: failed to load command: fastlane (/usr/local/bundle/bin/fastlane)
FastlaneCore::Interface::FastlaneCrash: [!] Could not retrieve response as fastlane runs in non-interactive mode
  /usr/local/bundle/gems/fastlane-2.131.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!'
  /usr/local/bundle/gems/fastlane-2.131.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:155:in `verify_interactive!'
  /usr/local/bundle/gems/fastlane-2.131.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:133:in `confirm'
  /usr/local/bundle/gems/fastlane-2.131.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /usr/local/bundle/gems/fastlane-2.131.0/fastlane/lib/fastlane/commands_generator.rb:359:in `ensure_fastfile'
  /usr/local/bundle/gems/fastlane-2.131.0/fastlane/lib/fastlane/commands_generator.rb:107:in `block (2 levels) in run'
  /usr/local/bundle/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /usr/local/bundle/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /usr/local/bundle/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /usr/local/bundle/gems/fastlane-2.131.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /usr/local/bundle/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /usr/local/bundle/gems/fastlane-2.131.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
  /usr/local/bundle/gems/fastlane-2.131.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /usr/local/bundle/gems/fastlane-2.131.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /usr/local/bundle/gems/fastlane-2.131.0/bin/fastlane:23:in `<top (required)>'
  /usr/local/bundle/bin/fastlane:23:in `load'
  /usr/local/bundle/bin/fastlane:23:in `<top (required)>'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/version for documentation about this command.
Exited with code 1
`

**Comment by trickeyd** [comment]
Hey - I'm not sure I understand the relevance of the linked issue. What am I missing?

I have just come back to this and have tried a few more things today, but am no closer to understanding what the problem is. 

Are there any thoughts from you guys? Or is there any more info I can supply that might help?

Thanks!

**Comment by trickeyd** [comment]
Just to update: I finally managed to get past the error by using the following environment:
    macos:
      xcode: "10.0"

I had tried every combination of docker images imaginable, and none of them worked. In the end I just had to just use the above and manually install everything I needed.

I still have no clue what caused the error...
