### ISSUE TITLE
how to automatic selected the authentication phone

### ISSUE THREAD

**Issue by Wbqqqq** [fastlane/fastlane#15344]
today，I add  the other phone to my apple acount, when i  use  fastlane  to upload appfile ,it ask to me must input 'sms' to select one of the phones, how I  edit the config flie to automatic selected the authentication phone? or I must  input "sms" ?

**Comment by rickclephas** [comment]
For that you probably want to use an application specific password:
https://docs.fastlane.tools/best-practices/continuous-integration/#application-specific-passwords

**Comment by janpio** [comment]
If you really need 2FA via SMS on a specific phone, you can set the `SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER` environment variable to that phone number. (Which we seem to have forgotten to properly document, but the output is probably telling you about.)

**Comment by Wbqqqq** [comment]
thanks，bros
