### ISSUE TITLE
Frameit private method `select' called for nil:NilClass

### ISSUE THREAD

**Issue by tgreco** [fastlane/fastlane#15350]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I am running frameit on a 1280x800 screenshot with force_device_type "Mac" but getting an error: private method `select' called for nil:NilClass

##### Command executed

I have tried  fastlane frameit --force_device_type "Mac" as well as fastlane frameit
##### Complete output when running fastlane, including the stack trace and command used

```
[⠋] 🚀 /Volumes/Hybrid/Users/macbook/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/tty-screen-0.6.4/lib/tty/version.rb:3: warning: already initialized constant TTY::Screen::VERSION
/Volumes/Hybrid/Users/macbook/.rvm/gems/ruby-2.4.1@global/gems/tty-screen-0.6.4/lib/tty/version.rb:3: warning: previous definition of VERSION was here
[⠋] 🚀 /Volumes/Hybrid/Users/macbook/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.131.0/spaceship/lib/spaceship/test_flight/build.rb:91: warning: already initialized constant Spaceship::TestFlight::Build::BUILD_STATES
/Volumes/Hybrid/Users/macbook/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/test_flight/build.rb:91: warning: previous definition of BUILD_STATES was here
/Volumes/Hybrid/Users/macbook/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/connect_api/models/build.rb:40: warning: already initialized constant Spaceship::ConnectAPI::Build::ESSENTIAL_INCLUDES
/Volumes/Hybrid/Users/macbook/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.131.0/spaceship/lib/spaceship/connect_api/models/build.rb:40: warning: previous definition of ESSENTIAL_INCLUDES was here
/Volumes/Hybrid/Users/macbook/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/connect_api/models/build.rb:43: warning: already initialized constant Spaceship::ConnectAPI::Build::ProcessingState::PROCESSING
/Volumes/Hybrid/Users/macbook/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.131.0/spaceship/lib/spaceship/connect_api/models/build.rb:43: warning: previous definition of PROCESSING was here
/Volumes/Hybrid/Users/macbook/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/connect_api/models/build.rb:44: warning: already initialized constant Spaceship::ConnectAPI::Build::ProcessingState::FAILED
/Volumes/Hybrid/Users/macbook/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.131.0/spaceship/lib/spaceship/connect_api/models/build.rb:44: warning: previous definition of FAILED was here
/Volumes/Hybrid/Users/macbook/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/connect_api/models/build.rb:45: warning: already initialized constant Spaceship::ConnectAPI::Build::ProcessingState::INVALID
/Volumes/Hybrid/Users/macbook/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.131.0/spaceship/lib/spaceship/connect_api/models/build.rb:45: warning: previous definition of INVALID was here
/Volumes/Hybrid/Users/macbook/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/connect_api/models/build.rb:46: warning: already initialized constant Spaceship::ConnectAPI::Build::ProcessingState::VALID
/Volumes/Hybrid/Users/macbook/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.131.0/spaceship/lib/spaceship/connect_api/models/build.rb:46: warning: previous definition of VALID was here
/Volumes/Hybrid/Users/macbook/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.131.0/spaceship/lib/spaceship/connect_api.rb:52: warning: already initialized constant Spaceship::ConnectAPI::Platform::IOS
/Volumes/Hybrid/Users/macbook/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/connect_api.rb:52: warning: previous definition of IOS was here
/Volumes/Hybrid/Users/macbook/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.131.0/spaceship/lib/spaceship/connect_api.rb:53: warning: already initialized constant Spaceship::ConnectAPI::Platform::MAC_OS
/Volumes/Hybrid/Users/macbook/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/connect_api.rb:53: warning: previous definition of MAC_OS was here
/Volumes/Hybrid/Users/macbook/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.131.0/spaceship/lib/spaceship/connect_api.rb:54: warning: already initialized constant Spaceship::ConnectAPI::Platform::TV_OS
/Volumes/Hybrid/Users/macbook/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/connect_api.rb:54: warning: previous definition of TV_OS was here
/Volumes/Hybrid/Users/macbook/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.131.0/spaceship/lib/spaceship/connect_api.rb:55: warning: already initialized constant Spaceship::ConnectAPI::Platform::WATCH_OS
/Volumes/Hybrid/Users/macbook/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/connect_api.rb:55: warning: previous definition of WATCH_OS was here
/Volumes/Hybrid/Users/macbook/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.131.0/spaceship/lib/spaceship/connect_api.rb:57: warning: already initialized constant Spaceship::ConnectAPI::Platform::ALL
/Volumes/Hybrid/Users/macbook/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/connect_api.rb:57: warning: previous definition of ALL was here
[✔] 🚀 
[08:09:31]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
/Volumes/Hybrid/Users/macbook/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.131.0/fastlane_core/lib/fastlane_core/module.rb:6: warning: already initialized constant FastlaneCore::ROOT
/Volumes/Hybrid/Users/macbook/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/fastlane_core/lib/fastlane_core/module.rb:6: warning: previous definition of ROOT was here
/Volumes/Hybrid/Users/macbook/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.131.0/fastlane_core/lib/fastlane_core/module.rb:7: warning: already initialized constant FastlaneCore::Boolean
/Volumes/Hybrid/Users/macbook/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/fastlane_core/lib/fastlane_core/module.rb:7: warning: previous definition of Boolean was here
/Volumes/Hybrid/Users/macbook/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/frameit/lib/frameit/frame_downloader.rb:7: warning: already initialized constant Frameit::FrameDownloader::HOST_URL
/Volumes/Hybrid/Users/macbook/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.131.0/frameit/lib/frameit/frame_downloader.rb:7: warning: previous definition of HOST_URL was here
/Volumes/Hybrid/Users/macbook/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/frameit/lib/frameit/device_types.rb:3: warning: already initialized constant Frameit::Color::BLACK
/Volumes/Hybrid/Users/macbook/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.131.0/frameit/lib/frameit/device_types.rb:3: warning: previous definition of BLACK was here
/Volumes/Hybrid/Users/macbook/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/frameit/lib/frameit/device_types.rb:4: warning: already initialized constant Frameit::Color::SILVER
/Volumes/Hybrid/Users/macbook/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.131.0/frameit/lib/frameit/device_types.rb:4: warning: previous definition of SILVER was here
/Volumes/Hybrid/Users/macbook/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/frameit/lib/frameit/device_types.rb:5: warning: already initialized constant Frameit::Color::ROSE_GOLD
/Volumes/Hybrid/Users/macbook/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.131.0/frameit/lib/frameit/device_types.rb:5: warning: previous definition of ROSE_GOLD was here
/Volumes/Hybrid/Users/macbook/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/frameit/lib/frameit/device_types.rb:6: warning: already initialized constant Frameit::Color::GOLD
/Volumes/Hybrid/Users/macbook/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.131.0/frameit/lib/frameit/device_types.rb:6: warning: previous definition of GOLD was here
/Volumes/Hybrid/Users/macbook/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/frameit/lib/frameit/device_types.rb:7: warning: already initialized constant Frameit::Color::RED
/Volumes/Hybrid/Users/macbook/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.131.0/frameit/lib/frameit/device_types.rb:7: warning: previous definition of RED was here
/Volumes/Hybrid/Users/macbook/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/frameit/lib/frameit/device_types.rb:8: warning: already initialized constant Frameit::Color::YELLOW
/Volumes/Hybrid/Users/macbook/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.131.0/frameit/lib/frameit/device_types.rb:8: warning: previous definition of YELLOW was here
/Volumes/Hybrid/Users/macbook/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/frameit/lib/frameit/device_types.rb:9: warning: already initialized constant Frameit::Color::WHITE
/Volumes/Hybrid/Users/macbook/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.131.0/frameit/lib/frameit/device_types.rb:9: warning: previous definition of WHITE was here
/Volumes/Hybrid/Users/macbook/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/frameit/lib/frameit/device_types.rb:10: warning: already initialized constant Frameit::Color::CORAL
/Volumes/Hybrid/Users/macbook/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.131.0/frameit/lib/frameit/device_types.rb:10: warning: previous definition of CORAL was here
/Volumes/Hybrid/Users/macbook/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/frameit/lib/frameit/device_types.rb:11: warning: already initialized constant Frameit::Color::BLUE
/Volumes/Hybrid/Users/macbook/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.131.0/frameit/lib/frameit/device_types.rb:11: warning: previous definition of BLUE was here
/Volumes/Hybrid/Users/macbook/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/frameit/lib/frameit/device_types.rb:15: warning: already initialized constant Frameit::Orientation::PORTRAIT
/Volumes/Hybrid/Users/macbook/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.131.0/frameit/lib/frameit/device_types.rb:15: warning: previous definition of PORTRAIT was here
/Volumes/Hybrid/Users/macbook/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/frameit/lib/frameit/device_types.rb:16: warning: already initialized constant Frameit::Orientation::LANDSCAPE
/Volumes/Hybrid/Users/macbook/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.131.0/frameit/lib/frameit/device_types.rb:16: warning: previous definition of LANDSCAPE was here
/Volumes/Hybrid/Users/macbook/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.131.0/credentials_manager/lib/credentials_manager/account_manager.rb:8: warning: already initialized constant CredentialsManager::AccountManager::DEFAULT_PREFIX
/Volumes/Hybrid/Users/macbook/.rvm/gems/ruby-2.4.1@global/gems/fastlane-2.131.0/credentials_manager/lib/credentials_manager/account_manager.rb:8: warning: previous definition of DEFAULT_PREFIX was here
[08:09:34]: Using device frames version 'latest'
[08:09:34]: private method `select' called for nil:NilClass
```

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.6                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | ~/.rvm/rubies/ruby-2.4.1/bin/fastlane       |
| Host                        | Mac OS X 10.13.6 (17G8030)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0h  27 Mar 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/XCode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.131.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.4.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.2       |
| io-console                | 0.4.6        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.2       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| json                      | 2.0.2        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 0.1.1        |
| openssl                   | 2.0.3        |
| psych                     | 2.2.2        |
</details>

**Comment by janpio** [comment]
Can you run with `--verbose` to see if you get any additional useful output? What you are currently getting doesn't help very much to identify what is going on unfortunately :/
