### ISSUE TITLE
Google api error: replacingBundleWithApk

### ISSUE THREAD

**Issue by pvanny1124** [fastlane/fastlane#15360]
### Question Checklist

- [x ] Updated fastlane to the latest version
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ]x I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
trying to upload my signed apk file to google play as an internal release and I get this error: 

`replacingBundleWithApk: You cannot insert a bundle with the same version code as an APK in the edit. - You cannot insert a bundle with the same version code as an APK in the edit.`

this is all I'm doing:
```
lane :internal do
  upload_to_play_store(
    track: 'internal',
    apk: './app/release/app-release.apk'
  )
end
```

**Comment by rickclephas** [comment]
I guess what this error means to say is that you already uploaded a bundle with the same version code. Make sure to increase the version code of your app for every upload.
