### ISSUE TITLE
Difficulties sending direct message through slack

### ISSUE THREAD

**Issue by kamvoick** [fastlane/fastlane#15362]
### Question Checklist

- [x ] Updated fastlane to the latest version
- [ x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
I'm having a problem with sending direct message by the slack. So, my slack action look like this:
```
slack(
       pretext: "<@UCXXXXXXX> test Project: <#{ENV['CI_PROJECT_URL']}|#{ENV['CI_PROJECT_PATH']}>",
       username: "@myUsername",
       slack_url: ENV["SLACK_URL_USER"],
       message: "CI: Your unit tests on #{ENV['CI_COMMIT_REF_NAME']} failed",
       success: false,
       link_names: true,
       default_payloads: [])
```
and i'd like to send this notification directly to user assigned to username. Problem is no matter what i'd put on username (@username @fullname <@userID>) this doesn't work and the message is sent to the channel which was set by the ENV["SLACK_URL_USER"], but when user is mentioned in pretext by userId slack recognizes him properly, same with chanel. 

#### Question Description
So of course my workaround is to put slack's webhook connected to current user and checking if the user that push the commit(CI, email) is the one that should receive notification under a connected slack's url. Which is not great, but it works, at least

Thanks

**Comment by rickclephas** [comment]
According to the docs the `username` option is to override the webhook's username property.
https://docs.fastlane.tools/actions/slack/#parameters

To send a message to a specific user you should set the `channel` option to the `@username`.

**Comment by kamvoick** [comment]
this unfortunately doesn't work either

**Comment by rickclephas** [comment]
Alright so it seems the Slack API has changed quite a bit since this action has been created.
With the current webhooks it isn't possible to change the channel.

> You **cannot override** the default channel (chosen by the user who installed your app), username, or icon when you're using Incoming Webhooks to post messages. Instead, these values will always inherit from the associated Slack app configuration.

https://api.slack.com/incoming-webhooks

You can use the "Incoming WebHooks" apps which allows you to change the channel.
Though it doesn't allow you to use a username.
https://slack.com/apps/A0F7XDUAZ-incoming-webhooks

As a side note Slack is also deprecating the use of usernames:
https://api.slack.com/methods/chat.postMessage#post_to_an_im_channel

@janpio I guess this action needs an update to correctly work with the new Slack API (and support the new messaging format).

**Comment by janpio** [comment]
Thanks @rickclephas. Are you up to updating the current documentation in the action file or even attempt the upgrade?

**Comment by rickclephas** [comment]
@janpio sure I will take a look at this when I have some time. 
I see that the current package hasn't been updated for over 2 years. https://github.com/stevenosloan/slack-notifier

So we probably need a new package or maybe none at all? 
After all it's only an HTTP wrapper.

**Comment by janpio** [comment]
Less gems is always nice, if there is nothing existing and maintained out there to make our lives easier especially.

**Comment by rickclephas** [comment]
@janpio I created a new issue where we can discuss the implementation of the new Slack action.

**Comment by crazymanish** [comment]
Hi @kamvoick 
You can send a direct message now:) Please let me know if you need any help! 😍
https://github.com/crazymanish/fastlane-plugin-slack_bot

Thanks, @joshdholtz for unlocking the issue! 🙏🏻

**Comment by crazymanish** [comment]
cc: @rickclephas
