### ISSUE TITLE
Frameit doesn't apply font for Chinese language

### ISSUE THREAD

**Issue by maxkazakov** [fastlane/fastlane#15368]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Font for Chinese described in framefile.json is not applied

##### Command executed
fastlane beauty_screens --verbose

##### Complete output when running fastlane, including the stack trace and command used
INFO [2019-09-24 19:10:09.73]: ------------------------------
INFO [2019-09-24 19:10:09.73]: --- Step: default_platform ---
INFO [2019-09-24 19:10:09.73]: ------------------------------
INFO [2019-09-24 19:10:09.73]: Driving the lane 'ios beauty_screens' 🚀
INFO [2019-09-24 19:10:09.74]: -------------------------------
INFO [2019-09-24 19:10:09.74]: --- Step: frame_screenshots ---
INFO [2019-09-24 19:10:09.74]: -------------------------------
INFO [2019-09-24 19:10:09.82]: Framing screenshots at path ./fastlane/screenshots/zh-Hans (via frameit)
INFO [2019-09-24 19:10:09.82]: Using device frames version 'latest'
DEBUG [2019-09-24 19:10:09.83]: Parsing config file '/Users/maxkazakov/src/HowMuch/fastlane/screenshots/Framefile.json'
DEBUG [2019-09-24 19:10:09.93]: Looking for Apple iPhone XS Max Silver and found 1 template(s)
DEBUG [2019-09-24 19:10:13.49]: Falling back to text in Framefile.json as there was nothing specified in the keyword.strings file
DEBUG [2019-09-24 19:10:14.53]: No custom font specified for ./iPhone Xs Max-MainScreen.png, using the default one
DEBUG [2019-09-24 19:10:14.54]: Adding text '只需将相机指向一个价格即可获得所需的货币'
DEBUG [2019-09-24 19:10:16.69]: Text for image ./iPhone Xs Max-MainScreen.png is quite long, reducing font size by 41.4%

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.0                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.6 (18G95)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.0                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

default_platform(:ios)

  lane :beauty_screens do 
    frame_screenshots(silver: true, path: "./fastlane/screenshots/zh-Hans")
  end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.maxkazakov.Howmuch" # The bundle identifier of your app
apple_id "kazakov.maxim.a@icloud.com" # Your Apple email address

itc_team_id "118815123" # iTunes Connect Team ID
team_id "U8743T8Z48" # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.131.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.1        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.66.0       |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.1          |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.0        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| libxml-ruby               | 3.0.0        |
| psych                     | 2.0.8        |
</details>

*generated on:* **2019-09-24**
</details>

### Framefile
```
{
    "default": {
        "title": {
            "fonts": [
                {
                    "font": "./fonts/wts11.ttf",
                    "supported": [
                        "zh-Hans"
                    ]
                }
            ],
            "color": "#333333"
        },
        "background": "./background.png",
        "padding": 50,
        "title_min_height": 150
    },
    "data": [
        {
            "filter": "MainScreen"
        },
        {
            "filter": "ManualEditingScreen"
        },
        {
            "filter": "SettingsScreen"
        }
    ]
}
```

What I get is
<img width="440" alt="Screenshot 2019-09-24 at 19 13 36" src="https://user-images.githubusercontent.com/17107905/65519688-c8e52d00-deff-11e9-8f3c-56464a1ba3df.png">

Font for Chinese is a valid font. It seems like frameit just doesn't apply this font for Chinese text because when I look at the screen for another language (Spanish) symbols for numbers ("150") look the same:
<img width="368" alt="Screenshot 2019-09-24 at 19 20 28" src="https://user-images.githubusercontent.com/17107905/65520051-6b051500-df00-11e9-9d3b-bc2b319e7965.png">

I've also tried to move title font information from "default" section to "data" section but screens are the same and output still contains messages like
>  No custom font specified for ./iPhone Xs Max-MainScreen.png, using the default one

**Comment by janpio** [comment]
Can you please create a minimal reproduction that we can use to actually test this? Thanks.

**Comment by maxkazakov** [comment]
> Can you please create a minimal reproduction that we can use to actually test this? Thanks.

Sure. Here is an example. 
run ` fastlane beauty_screens --verbose`
[frameit_test.zip](https://github.com/fastlane/fastlane/files/3666594/frameit_test.zip)
