### ISSUE TITLE
Application Loader is no longer included with Xcode11

### ISSUE THREAD

**Issue by iHTCboy** [fastlane/fastlane#15363]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

[Xcode 11 Release Notes | Apple Developer Documentation](https://developer.apple.com/documentation/xcode_release_notes/xcode_11_release_notes)

> Xcode supports uploading apps from the Organizer window or from the command line with xcodebuild or xcrun altool. Application Loader is no longer included with Xcode. (29008875)

##### Command executed
[fastlane_core/helper.rb](https://github.com/fastlane/fastlane/blob/7cab8341ec663eb58bb27af0bade422a8d561836/fastlane_core/lib/fastlane_core/helper.rb)

```
# Then check for iTMSTransporter in the Xcode path
        [
          "../Applications/Application Loader.app/Contents/MacOS/itms",
          "../Applications/Application Loader.app/Contents/itms",
          "../SharedFrameworks/ContentDeliveryServices.framework/Versions/A/itms" # For Xcode 11
        ].each do |path|
```

In Xcode11 no such file or directory:

`/Applications/Xcode.app/Contents/Developer/../Applications/Application\ Loader.app/Contents/itms/bin/iTMSTransporter`

**Comment by janpio** [comment]
Does `../SharedFrameworks/ContentDeliveryServices.framework/Versions/A/itms` exist?

**Comment by iHTCboy** [comment]
@janpio thanks, `../SharedFrameworks/ContentDeliveryServices.framework/Versions/A/itms` exist with Xcode11 !

**Comment by lionhylra** [comment]
To be more accurate, `../SharedFrameworks/ContentDeliveryServices.framework/Versions/A/itms` exists in Xcode 11.1 but not Xcode 11.0

**Comment by lionhylra** [comment]
@iHTCboy I have a Xcode 11.1 updated from App Store, it contains ContentDeliveryServices.framework.
I also have a Xcode 11.0 installed from xcversion, it doesn't. It's weird.

**Comment by iHTCboy** [comment]
@lionhylra  My Xcode11.0 from AppStore.  maybe is update from Xcode10.3,
