### ISSUE TITLE
Update Match to use the Xcode 11 compatible provisioning profiles

### ISSUE THREAD

**Issue by yusuftor** [fastlane/fastlane#15369]
I've had to resort to manually uploading builds because Match doesn't support provisioning profiles for Xcode 11. This is the same issue as #15031 but it looks like literally nothing has been done. Can we get a fix for this asap please? This should be top priority as everyone is now upgrading to Xcode 11!

**Comment by aastlind** [comment]
Getting this error as well.

Gym log:
Code Signing Error: Provisioning profile "match AppStore com.mydomain.app" doesn't support the iCloud.com.mydomain.app iCloud Container.
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 13.0'

**Comment by janpio** [comment]
> Can we get a fix for this asap please? This should be top priority as everyone is now upgrading to Xcode 11!

Of course, looking forward to reviewing your Pull Request that fixes this super important problem asap.
