### ISSUE TITLE
Using SharedValues from one lane to another lane

### ISSUE THREAD

**Issue by hrushie** [fastlane/fastlane#15374]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
I want to use sharedVariable generated in one lane in another lane even it is executed separately.

#### Question Description

Hello Team, I am using Fastlane for most of the tasks we have in our Jenkins pipeline for iOS and android. In my setup for each task such as Build, Unit Test I have a separate lane and each lane is gets called respective stages. Example in Build stage I will call a build lane to execute or in Test stage I will call build lane to execute. like the same way I am calling the lanes separately for all the stages in the pipeline. Is there any way that I can use a SharedValues generated by one lane in another lane called in separate Fastlane command?

If I cannot user the sharedVariables in different lane then can I store that sharedVariable somewhere and access it again from another lane?

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                |
| --------------------------- | ------------------------------------ |
| OS                          | 10.14.6                              |
| Ruby                        | 2.4.3                                |
| Bundler?                    | false                                |
| Git                         | git version 2.15.1                   |
| Installation Source         | ~/.rbenv/versions/2.4.3/bin/fastlane |
| Host                        | Mac OS X 10.14.6 (18G95)             |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.3/lib          |
| OpenSSL Version             | OpenSSL 1.0.2s  28 May 2019          |
| Is contained                | false                                |
| Is homebrew                 | false                                |
| Is installed via Fabric.app | false                                |
| Xcode Path                  | /Library/Developer/CommandLineTools/ |
| Xcode Version               |                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
require 'net/http'
require 'uri'
min_fastlane_version("2.70.0")

default_platform(:android)

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs the build to create apk"
  lane :build do
    gradle(task: "assembleDEDebug")

    puts lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]

    #analysis

    post_build

  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "cleanTest test jacocoTestReport --continue --info")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleDEdebug")
    upload_to_play_store
  end

  lane :analysis do
    sonar(
    project_key: "TEST-GMA5-android",
    project_version: "1.0",
    project_name: "TEST GMA5 android",
    branch_name: "DE"
    )
  end

  desc "post build tasks for GMA builds"
  lane :post_build do
  
  
    appcenter_upload(
      api_token: "a33ba900b83a4301c493b4c1a1fbd38235ddca06",
      owner_name: "mcd-gma5_de",
      app_name: "ANDROID-TEST",
      apk: "/Users/mc60177/GMADevOps/Repos/core-android-Aug21/app/build/outputs/apk/qa/debug/app-qa-debug.apk",
      destinations: "DEVOPS",
      release_notes: sh("cat ../release_notes.txt"),
      should_clip: true,
      notify_testers: true # Set to false if you don't want to notify testers of your new release (default: `false`)
      )
      UI.important "AppCenter Upload Successfull."
    #puts lane_context[SharedValues::APPCENTER_DOWNLOAD_LINK]
    #puts lane_context[SharedValues::APPCENTER_BUILD_INFORMATION]

    appurl = lane_context[SharedValues::APPCENTER_DOWNLOAD_LINK]

    webex(
      AppCenterLink: lane_context[SharedValues::APPCENTER_DOWNLOAD_LINK],
      message: sh("cat ../release_notes.txt"),
      Appdetails: lane_context[SharedValues::APPCENTER_BUILD_INFORMATION]
    )

    #sh('''curl -X POST -H "Content-Type: application/json" -d "{"markdown" : "$appurl"}" ''')
    #sh('''curl -X POST -H "Content-Type: application/json" -d '{ \"text" : "This is a message from a Cisco Webex Teams incoming webhook." }' https://api.ciscospark.com/v1/webhooks/incoming/Y2lzY29zcGFyazovL3VzL1dFQkhPT0svNTYxM2YyYjItM2Y3OS00OTZlLWFjODgtOTVhZWIxYjg0MTg2''')
    
    
    artifactory(
      username: "svc_vet_artifactory_no_overwrite",
      password: "Bigmac123",
      endpoint: "https://artifactrepository.mcd.com/artifactory",
      file: "/Users/mc60177/GMADevOps/Repos/core-android-Aug21/app/build/outputs/apk/qa/debug/app-qa-debug.apk",  # File to upload
      repo: "GMA",       # Artifactory repo
      repo_path: "GMA/Android/DE/DE.apk"   # Path to place the artifact including its filename
    )
  # You can define as many lanes as you want
  end

  

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("de.mcdonalds.mcdonaldsinfoapp") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.130.0 | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-appcenter | 1.4.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.1        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.66.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.0.2        |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| openssl                   | 2.0.5        |
| json                      | 2.2.0        |
| io-console                | 0.4.6        |
| addressable               | 2.7.0        |
| psych                     | 2.2.2        |
| fastlane-plugin-appcenter | 1.4.0        |
</details>

*generated on:* **2019-09-25**
</details>

**Comment by hrushie** [comment]
@janpio

**Comment by janpio** [comment]
Please don't @ mention maintainers - we reply when we got to it (or do not reply, if we don't).

You want to use `SharedValues` across fastlane runs, correct? That is not possible as the `SharedValues` are not persisted in any way. Depending on your testing setup, you could possibly write things into ENV vars and read them in the next run. If not, you will have to find some other way to persist data.

**Comment by hrushie** [comment]
Thank you for the suggetions. right now I am saving values in the txt file. is there any way that I can save the variables in the .env file from fastlane?

**Comment by janpio** [comment]
`.env` is just a file as well, so you can write whatever you want in there.
