### ISSUE TITLE
Submit app to TestFlight on behalf of our users. Any way to avoid password prompts?

### ISSUE THREAD

**Issue by musdy** [fastlane/fastlane#15370]
Hello! 

We are trying to give our users the ability to be able to push their apps to both TestFlight and Google Play. (In other words, using Fastlane to push apps that are created by other users on our platform.) We are doing this by asking them to give us access from Apple Store Connect API. This is all working, except when we try to send the build to TestFlight, it asks for Appstore username and password. 

Is there a way to avoid that prompt?  We are able to solve all other issues like certificate, profile with the p12 file we create.

Thanks for the help!

**Comment by janpio** [comment]
> We are doing this by asking them to give us access from Apple Store Connect API.

What does this mean exactly? How are you supplying the authentication information?
