### ISSUE TITLE
Unable to import new Apple Distribution private key to repo

### ISSUE THREAD

**Issue by GLJeffery** [fastlane/fastlane#15389]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Due to Apple's new certificates from Xcode 11, I have been trying to manually encrypt updated provisioning profiles and certificates into our fastlane repo. However, whenever I export the Private Key as a .p12 for the new Apple Distribution certificate, it's not able to be read/downloaded anywhere (if I run match on another computer, the private key will not make it, just the cert)

##### Command executed

I've been following the steps here: https://docs.fastlane.tools/advanced/other/#manually-manage-the-fastlane-match-repo

The provisioning profile downloads and it tries to download the correct cert that I manually uploaded, but the private key doesn't come with it.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.4                                     |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0 (Apple Git-122)          |
| Installation Source         | ~/.rbenv/versions/2.5.1/bin/fastlane        |
| Host                        | Mac OS X 10.14.4 (18E226)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2s  28 May 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.0                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.131.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                                | Version | Update-Status |
| ----------------------------------------------------- | ------- | ------------- |
| fastlane-plugin-badge                                 | 1.3.0   | ✅ Up-To-Date  |
| fastlane-plugin-aws_s3                                | 1.6.0   | ✅ Up-To-Date  |
| fastlane-plugin-versioning                            | 0.3.4   | ✅ Up-To-Date  |
| fastlane-plugin-get_unprovisioned_devices_from_hockey | 0.1.1   | ✅ Up-To-Date  |
| fastlane-plugin-rome                                  | 0.3.8   | ✅ Up-To-Date  |
| fastlane-plugin-sentry                                | 1.5.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                                   | Version      |
| ----------------------------------------------------- | ------------ |
| did_you_mean                                          | 1.2.0        |
| slack-notifier                                        | 2.3.2        |
| rouge                                                 | 2.0.7        |
| xcpretty                                              | 0.3.0        |
| terminal-notifier                                     | 2.0.0        |
| terminal-table                                        | 1.8.0        |
| multipart-post                                        | 2.0.0        |
| word_wrap                                             | 1.0.0        |
| public_suffix                                         | 2.0.5        |
| babosa                                                | 1.0.2        |
| colored                                               | 1.2          |
| highline                                              | 1.7.10       |
| commander-fastlane                                    | 4.4.6        |
| http-cookie                                           | 1.0.3        |
| faraday-cookie_jar                                    | 0.0.6        |
| gh_inspector                                          | 1.1.3        |
| mini_magick                                           | 4.9.5        |
| multi_xml                                             | 0.6.0        |
| security                                              | 0.1.3        |
| xcpretty-travis-formatter                             | 1.0.0        |
| jwt                                                   | 2.1.0        |
| uber                                                  | 0.1.0        |
| declarative                                           | 0.0.10       |
| declarative-option                                    | 0.1.0        |
| representable                                         | 3.0.4        |
| retriable                                             | 3.1.2        |
| multi_json                                            | 1.13.1       |
| signet                                                | 0.11.0       |
| memoist                                               | 0.16.0       |
| googleauth                                            | 0.6.7        |
| httpclient                                            | 2.8.3        |
| google-api-client                                     | 0.23.9       |
| nanaimo                                               | 0.2.6        |
| colored2                                              | 3.1.2        |
| claide                                                | 1.0.3        |
| CFPropertyList                                        | 3.0.1        |
| atomos                                                | 0.1.3        |
| xcodeproj                                             | 1.12.0       |
| unicode-display_width                                 | 1.6.0        |
| plist                                                 | 3.5.0        |
| addressable                                           | 2.7.0        |
| tty-screen                                            | 0.7.0        |
| tty-cursor                                            | 0.7.0        |
| tty-spinner                                           | 0.9.1        |
| excon                                                 | 0.66.0       |
| faraday                                               | 0.15.4       |
| unf_ext                                               | 0.0.7.6      |
| unf                                                   | 0.1.4        |
| domain_name                                           | 0.5.20190701 |
| fastimage                                             | 2.1.7        |
| json                                                  | 2.2.0        |
| rubyzip                                               | 1.2.4        |
| dotenv                                                | 2.7.5        |
| bundler                                               | 2.0.2        |
| faraday_middleware                                    | 0.13.1       |
| naturally                                             | 2.2.0        |
| simctl                                                | 1.6.6        |
| mime-types-data                                       | 3.2019.0904  |
| mime-types                                            | 3.3          |
| os                                                    | 1.0.1        |
| digest-crc                                            | 0.4.1        |
| google-cloud-env                                      | 1.2.1        |
| google-cloud-core                                     | 1.3.1        |
| google-cloud-storage                                  | 1.16.0       |
| emoji_regex                                           | 1.0.1        |
| openssl                                               | 2.1.0        |
| date                                                  | 1.0.0        |
| fileutils                                             | 1.0.2        |
| mini_portile2                                         | 2.4.0        |
| nokogiri                                              | 1.10.4       |
| ipaddr                                                | 1.2.0        |
| psych                                                 | 3.0.2        |
| badge                                                 | 0.11.0       |
| fastlane-plugin-badge                                 | 1.3.0        |
| apktools                                              | 0.7.2        |
| fastlane-plugin-aws_s3                                | 1.6.0        |
| fastlane-plugin-versioning                            | 0.3.4        |
| fastlane-plugin-get_unprovisioned_devices_from_hockey | 0.1.1        |
| fastlane-plugin-rome                                  | 0.3.8        |
| fastlane-plugin-sentry                                | 1.5.0        |
</details>

*generated on:* **2019-09-26**
</details>

**Comment by spidfire** [comment]
I think I got a related (or same) issue. During the process it gets a Bad request in spaceship/portal/portal_client.rb:690  in create_provisioning_profile

Not sure if this is the case but my first observation:
When I took a look in the file I saw a call to [`/profile/createProvisioningProfile.action`](https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/portal/portal_client.rb#L689) while when I went there manually https://developer.apple.com/account/resources/profiles/add
