### ISSUE TITLE
Action increment_version_number no longer works with Xcode 11's version string change

### ISSUE THREAD

**Issue by matcartmill** [fastlane/fastlane#15383]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
With Xcode 11, Apple changed the version number (eg. 4.110.5) from being a Plist property to being a Project property. The Plist now references the project version by using `$(MARKETING_VERSION)`.

This breaks the `increment_version_number` action given that it reads the `$(MARKETING_VERSION)` as a string. The only way around this is to revert the Plist change manually, but any subsequent changes to the version in Xcode will break this again.

##### Command executed
`increment_version_number`

##### Complete output when running fastlane, including the stack trace and command used
```
[12:15:12]: --------------------------------------
[12:15:12]: --- Step: increment_version_number ---
[12:15:12]: --------------------------------------
[12:15:13]: Before being able to increment and read the version number from your Xcode project, you first need to setup your project properly. Please follow the guide at https://developer.apple.com/library/content/qa/qa1827/_index.html
+-----------------------------+--------------------+
|                   Lane Context                   |
+-----------------------------+--------------------+
| DEFAULT_PLATFORM            | ios                |
| PLATFORM_NAME               | ios                |
| LANE_NAME                   | ios release_branch |
| GIT_REPO_WAS_CLEAN_ON_START | true               |
| VERSION_NUMBER              | 4.1.0              |
| BUILD_NUMBER                | 2                  |
+-----------------------------+--------------------+
[12:15:13]: Your current version ($(MARKETING_VERSION)) does not respect the format A or A.B or A.B.C
```

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.6.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.21.0                          |
| Installation Source         | ~/.rbenv/versions/2.6.2/bin/fastlane        |
| Host                        | Mac OS X 10.14.6 (18G87)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.2/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2r  26 Feb 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.0                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform :ios
fastlane_version '2.131.0'

fastlane_require 'json'

platform :ios do

  # --------------------------------------------------
  # Set Up & Tear Down
  # --------------------------------------------------

  before_all do |lane, options|
  end

  after_all do |lane, options|
  end

  # --------------------------------------------------
  # Lanes
  # --------------------------------------------------

  import 'utils/shared_utils.rb'
  import 'lanes/build.rb'
  import 'lanes/bump.rb'
  import 'lanes/cicd.rb'
  import 'lanes/codecoverage.rb'
  import 'lanes/config.rb'
  import 'lanes/install.rb'
  import 'lanes/release.rb'
  import 'lanes/symbols.rb'
  import 'lanes/testflight.rb'
  import 'lanes/tests.rb'

  # --------------------------------------------------
  # Error Handling
  # --------------------------------------------------

  error do |lane, exception, options|
   if ENV["SLACK_URL"]
     slack(
           message: exception.message,
           success: false
         )
   end
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id 'xxxxxx'
app_identifier 'xxxxxx'

for_lane :beta do
  app_identifier 'xxxxxx'
end
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.131.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status  |
| ------------------------- | ------- | -------------- |
| fastlane-plugin-appconfig | 0.4.0   | 💥 Check failed |
| fastlane-plugin-aws_s3    | 1.6.0   | ✅ Up-To-Date   |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 2.0.2        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| CFPropertyList            | 3.0.1        |
| concurrent-ruby           | 1.1.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.11.1     |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| rubyzip                   | 1.2.4        |
| apktools                  | 0.7.2        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.0.3        |
| aws-sigv4                 | 1.1.0        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 2.11.338     |
| aws-sdk-resources         | 2.11.338     |
| aws-sdk                   | 2.11.338     |
| babosa                    | 1.0.3        |
| byebug                    | 11.0.1       |
| claide                    | 1.0.3        |
| clamp                     | 1.3.0        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.7.5        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.2.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.4.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| cocoapods                 | 1.7.5        |
| coderay                   | 1.1.2        |
| colored                   | 1.2          |
| colorize                  | 0.8.1        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.66.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.1        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.0904  |
| mime-types                | 3.3          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| git                       | 1.5.0        |
| fastlane-plugin-appconfig | 0.4.0        |
| fastlane-plugin-aws_s3    | 1.6.0        |
| oauth                     | 0.5.4        |
| jira-ruby                 | 1.6.0        |
| method_source             | 0.9.2        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.3       |
| pry                       | 0.12.2       |
| pry-byebug                | 3.7.0        |
| slather                   | 2.4.7        |
</details>

*generated on:* **2019-09-26**
</details></pre>
</details>

**Comment by janpio** [comment]
Do you see a way to fix this problem?

We had changes regarding `$(MARKETING_VERSION)` before, so this is probably related.

**Comment by lukecharman** [comment]
This is broken for me too, as of Fastlane 2.133.0.

**Comment by matcartmill** [comment]
Seems like the core of the problem is that `agvtool` hasn't been updated to support `$(MARKETING_VERSION)`, and simply just returns that as a string when read from the Plist.

One thought I have is adding some additional logic to the action's ruby script that, when the string is equal to `$(MARKETING_VERSION)`, it would search the project file for the key and validate the property value against the existing `version_regex` that's there.

The main issue I see there is that the marketing version can be different between the `Debug` build and the `Release` build.

@janpio do you know if Fastlane already has a way to read in Project Settings? I don't mind doing the work and contributing to the project, just need to know where to start.

**Comment by janpio** [comment]
Sorry, my knowledge there is minimal unfortunately. We probably are using `xcodeproj` and I assume that already has whatever you are asking for - they do everything ;) That's where I would start to look.

**Comment by matcartmill** [comment]
@janpio Okay. Using the `xcodeproj` gem I'm able to get what I need. I will try and get a PR opened soon for review.

**Comment by matcartmill** [comment]
@janpio @joshdholtz Looking for a bit of guidance here WRT to my attempt at a PR. I've got two solutions for this and I'm not sure which is more appropriate.

**Solution 1**
In `increment_version_number.rb`, instead of gathering the version code from `agvtool`, we can instead leverage the `GetVersionNumber` action in Fastlane. 

The drawback to this solution, however, is that because it does handle `$(MARKETING_VERSION)` appropriately, we don't know if it was originally a different string. The reason this could be an issue is that `agvtool` overrides the `$(MARKETING_VERSION)` string in the Info plist and sets it to version string like it always has. 

For instance, if a developer has setup their project to really take advantage of the `$(MARKETING_VERSION)` property, `agvtool` currently overrides that. So ultimately, I'm not sure what would break. However, `agvtool` is not something we own, so I'm not sure that we should be overly concerned. Seems like something Apple should fix.

**Solution 2**
Continue using `agvtool` to get the current version string. This does return `$(MARKETING_VERSION)`, so we will know how to update the project and Info plist files after the version update in order to not break anything. After `agvtool` has updated the files, we can go back in and modify the altered values to re-add `$(MARKETING_VERSION)` to the info plist.

However, it means that we're essentially copying logic from the `GetVersionNumber` action, which means we'd have two sets of logic to maintain with getting version numbers from the project.

I'm leaning more towards Solution 1 as I don't think we should be responsible for "correcting" / altering `agvtool`s behavior, but wanted to fun it by some of core team first.

**Comment by SaundersB** [comment]
I'm seeing this issue too after updating fastlane.

**Comment by powtac** [comment]
Not related to fastlane but I experienced a similar behavior: Xcode 11.1 changes the app version while compiling from `2.3.20` into `2.3.20..0` when checking the source code I discovered that `CFBundleShortVersionString` was updated by Xcode from `<string>$(MARKETING_VERSION)</string>` to `<string>$(MARKETING_VERSION)..0</string>`.

**Comment by cgathergood** [comment]
I can validate that the command `xcrun agvtool what-marketing-version` fails.

Running on Xcode 11.1

Did you find a workaround for `increment_version_number`? Thanks

**Comment by null09264** [comment]
The `get_version_number` command has been updated to support Xcode 11 so we can taking this temp workaround for now:

```ruby
version = get_version_number()
increment_version_number(version_number: version)
increment_version_number()
```
Be noted that this updates the default `$MARKETING_VERSION` to the actual version number string. Please make sure this won't cause you any issue beforehand.

**Comment by Jusung** [comment]
What if I want to get version number via "get_info_plist_value" command instead of get_version_number()?
Because then I have to change versioning system in Xcode Build Setting from none to Apple Generic . But I don't want it. @null09264

**Comment by ppamorim** [comment]
Any idea how to solve this in my situation below?

```ruby
infoPlistPath = "./my_app/#{infoPlist}.plist"
versionNumber = get_info_plist_value(path: infoPlistPath, key: "CFBundleShortVersionString")
buildNumber = get_info_plist_value(path: infoPlistPath, key: "CFBundleVersion")
```

**Comment by combinatorial** [comment]
Why not use `get_build_number`?

**Comment by Jusung** [comment]
@combinatorial 
I knew it. But I didn't use it because it gave me version number instead of build number.
So I had to manually extract it via get_info_plist_value from plist file.
It's weird. 🤪

**Comment by ppamorim** [comment]
@Jusung How to set Apple Generic?

**Comment by sudiptasahoo** [comment]
@ppamorim You can find it inside Project Settings > **Build Settings**

![image](https://user-images.githubusercontent.com/4083862/69501127-eb0f2180-0f27-11ea-9a2b-3781772902f2.png)

Reference: https://developer.apple.com/library/archive/qa/qa1827/_index.html

**Comment by sudiptasahoo** [comment]
I have got the following workaround in Bash script.

`
# Extracting App Marketing Version
APP_MARKETING_VERSION=`sed -n '/MARKETING_VERSION/{s/MARKETING_VERSION = //;s/;//;s/^[[:space:]]*//;p;q;}' ./${**PATH_TO_YOUR_PROJECT_XCODEPROJ_FILE**}/project.pbxproj`
`
In case you also need App Build Number, use the following bash script:
# Extracting App Build Number extraction method
APP_BUILD_NO=`sed -n '/CURRENT_PROJECT_VERSION/{s/CURRENT_PROJECT_VERSION = //;s/;//;s/^[[:space:]]*//;p;q;}' ./${**PATH_TO_YOUR_PROJECT_XCODEPROJ_FILE**}/project.pbxproj`
`

Now use the variable **APP_MARKETING_VERSION** & **APP_BUILD_NO** in your workflow.

**Comment by Jusung** [comment]
Thanks @sudiptasahoo

**Comment by nishabe** [comment]
Experiencing the same issue with Xcode 11.

**Comment by Jusung** [comment]
@nishabe Yes, it is. You have to fix it using among of above solutions.

**Comment by raphaelhovsepyan** [comment]
I use `increment_version_number_in_xcodeproj` action from [Versioning fastlane Plugin](https://github.com/SiarheiFedartsou/fastlane-plugin-versioning). It works it `MARKETING_VSERION`

```
// Add plugin
fastlane add_plugin versioning
```
```
// Add action to your lane
increment_version_number_in_xcodeproj(bump_type: "patch", target: "your_target_name")
```
