### ISSUE TITLE
Screengrab Android how to prevent print list packages

### ISSUE THREAD

**Issue by IevgenGoltsev** [fastlane/fastlane#15382]
So I noticed that currently Screengrab prints out installed packages on a device.
Is there some parameter to remove it from output?

**Comment by janpio** [comment]
Can you share what exactly you mean?
Why is this a problem?
How do you imagine what you are asking for should work?

**Comment by IevgenGoltsev** [comment]
Hello.
Well, this is definitely not a problem, but previously it didn't happen (cannot say version number unfortunately).
That just makes console output quite big.
