### ISSUE TITLE
Error 65 on latest Xcode 11.1.0 CircleCI Image

### ISSUE THREAD

**Issue by oleksandr-dziuban** [fastlane/fastlane#15396]
### Issue Description
With latest Xcode 11.1.0 circleci image it looks like we have issue with Xcode versions. It always throws an error: 

```
Exit status: 65
[02:48:36]: 
[02:48:36]: Maybe the error shown is caused by using the wrong version of Xcode
[02:48:36]: Found multiple versions of Xcode in '/Applications/'
[02:48:36]: Make sure you selected the right version for your project
[02:48:36]: This build process was executed using '/Applications/Xcode-11.GM.Seed.2.app'
[02:48:36]: If you want to update your Xcode path, either
[02:48:36]: 
[02:48:36]: - Specify the Xcode version in your Fastfile
[02:48:36]: ▸ xcversion(version: "8.1") # Selects Xcode 8.1.0
[02:48:36]: 
[02:48:36]: - Specify an absolute path to your Xcode installation in your Fastfile
[02:48:36]: ▸ xcode_select "/Applications/Xcode8.app"
[02:48:36]: 
[02:48:36]: - Manually update the path using
[02:48:36]: ▸ sudo xcode-select -s /Applications/Xcode.app
```
I tried to specify Xcode version with ```xcversion(version: "11.1") ```, but nothing happen.
Previous image with Xcode 10.2.1 works fine.

##### Command executed
```bundle exec fastlane build```

##### Complete output when running fastlane, including the stack trace and command used

```
** ARCHIVE FAILED **


The following build commands failed:
	CompileC /Users/distiller/Library/Developer/Xcode/DerivedData/Brandgility-ccncokfacuuibwcjplhtkspodqby/Build/Intermediates.noindex/ArchiveIntermediates/Brandgility/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/Yoga.build/Objects-normal/armv7/event.o /Users/distiller/mobile-web-app/node_modules/react-native/ReactCommon/yoga/yoga/event/event.cpp normal armv7 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
[02:48:36]: Exit status: 65
[02:48:36]: 
[02:48:36]: Maybe the error shown is caused by using the wrong version of Xcode
[02:48:36]: Found multiple versions of Xcode in '/Applications/'
[02:48:36]: Make sure you selected the right version for your project
[02:48:36]: This build process was executed using '/Applications/Xcode-11.GM.Seed.2.app'
[02:48:36]: If you want to update your Xcode path, either
[02:48:36]: 
[02:48:36]: - Specify the Xcode version in your Fastfile
[02:48:36]: ▸ xcversion(version: "8.1") # Selects Xcode 8.1.0
[02:48:36]: 
[02:48:36]: - Specify an absolute path to your Xcode installation in your Fastfile
[02:48:36]: ▸ xcode_select "/Applications/Xcode8.app"
[02:48:36]: 
[02:48:36]: - Manually update the path using
[02:48:36]: ▸ sudo xcode-select -s /Applications/Xcode.app
[02:48:36]: 

+---------------+--------------------------------------+
|                  Build environment                   |
+---------------+--------------------------------------+
| xcode_path    | /Applications/Xcode-11.GM.Seed.2.app |
| gym_version   | 2.131.0                              |
| export_method | app-store                            |
| sdk           | iPhoneOS13.0.sdk                     |
+---------------+--------------------------------------+

[02:48:36]: ▸          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[02:48:36]: ▸          "/Users/distiller/mobile-web-app/ios/Pods/Target Support Files/yoga/yoga-prefix.pch"
[02:48:36]: ▸ warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.0.99. (in target 'react-native-version-number' from project 'Pods')
[02:48:36]: ▸ warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 6.0, but the range of supported deployment target versions is 8.0 to 13.0.99. (in target 'RSKImageCropper' from project 'Pods')
[02:48:36]: 
[02:48:36]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[02:48:36]: 📋  For the complete and more detailed error log, check the full log at:
[02:48:36]: 📋  /Users/distiller/Library/Logs/gym/Brandgility-Brandgility.log
[02:48:36]: 
[02:48:36]: Looks like fastlane ran into a build/archive error with your project
[02:48:36]: It's hard to tell what's causing the error, so we wrote some guides on how
[02:48:36]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[02:48:36]: Before submitting an issue on GitHub, please follow the guide above and make
[02:48:36]: sure your project is set up correctly.
[02:48:36]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
[02:48:36]: the full commands printed out in yellow in the above log.
[02:48:36]: Make sure to inspect the output above, as usually you'll find more error information there
[02:48:36]: 
+------------------------------------+-------------------------------------------------------------------------+
|                                                 Lane Context                                                 |
+------------------------------------+-------------------------------------------------------------------------+
| DEFAULT_PLATFORM                   | ios                                                                     |
| PLATFORM_NAME                      | ios                                                                     |
| LANE_NAME                          | ios build                                                               |
| ORIGINAL_DEFAULT_KEYCHAIN          | "/Users/distiller/Library/Keychains/login.keychain-db"                  |
| SIGH_PROFILE_TYPE                  | app-store                                                               |
| MATCH_PROVISIONING_PROFILE_MAPPING | {"com.elateral.brandgility"=>"match AppStore com.elateral.brandgility"} |
+------------------------------------+-------------------------------------------------------------------------+
[02:48:36]: Error building the application - see the log above

+------+---------------------------------+-------------+
|                   fastlane summary                   |
+------+---------------------------------+-------------+
| Step | Action                          | Time (in s) |
+------+---------------------------------+-------------+
| 1    | opt_out_usage                   | 0           |
| 2    | Verifying fastlane version      | 0           |
| 3    | default_platform                | 0           |
| 4    | setup_circle_ci                 | 0           |
| 5    | Switch to ios certificates lane | 0           |
| 6    | is_ci                           | 0           |
| 7    | match                           | 2           |
| 💥   | gym                             | 70          |
```
<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.21.0 (Apple Git-122)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.6 (18G95)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.0                                                           |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
opt_out_usage
fastlane_version "2.131.0"

default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    match(
      type: 'appstore',
      readonly: is_ci
    )
  end

  desc "Build release iOS application"
  lane :build do
    certificates
    gym(
      scheme: "Brandgility",
      xcargs: "-allowProvisioningUpdates",
      export_xcargs: "-allowProvisioningUpdates"
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    build
    pilot(
      skip_waiting_for_build_processing: true
    )
  end

  desc "Deploy a new version to the App Store"
  lane :deploy do
    build
    deliver(force: true)
  end

  desc "Notify Slack channel"
    lane :slackmessage do
      version = get_version_number(
        xcodeproj: "Brandgility.xcodeproj",
        target: "Brandgility"
      )
      changelog = changelog_from_git_commits(
        date_format: "short",
        commits_count: 2,
        merge_commit_filtering: "exclude_merges",
      )
      slack(
        message: "Release v" + version + " (iOS Beta TestFlight)",
        default_payloads: [:test_result],
        payload: {
          "Changelog" => changelog
        },
        attachment_properties: {
          thumb_url: "https://www.internetsociety.org/wp-content/uploads/2017/02/Apple.png",
        }
      )
    end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier 'com.elateral.brandgility'
apple_id 'oleksandr.dziuban@gmail.com'

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.131.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.17.2       |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| tty-screen                | 0.7.0        |
| json                      | 2.2.0        |
| io-console                | 0.4.5        |
| excon                     | 0.66.0       |
| rubyzip                   | 1.2.4        |
| CFPropertyList            | 3.0.1        |
| libxml-ruby               | 2.9.0        |
| plist                     | 3.5.0        |
| atomos                    | 0.1.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| claide                    | 1.0.3        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| faraday_middleware        | 0.13.1       |
| babosa                    | 1.0.3        |
| fastimage                 | 2.1.7        |
| unicode-display_width     | 1.6.0        |
| addressable               | 2.7.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| os                        | 1.0.1        |
| psych                     | 2.1.0.1      |
| mime-types                | 3.3          |
| mime-types-data           | 3.2019.0904  |
</details>

*generated on:* **2019-09-27**
</details> </pre>
</details>

**Comment by Maxwell2022** [comment]
same with `xcode 10.3.0`

**Comment by oleksandr-dziuban** [comment]
@Maxwell2022 Yep, xcode 10.2.1 image works fine. All next versions are failing with this error...

**Comment by Maxwell2022** [comment]
It looks like it's fixed for us now, `10.3.0` is working again. I think it's an issue with CircleCI, they were updating their XCode images to support the new XCode 11.

**Comment by oleksandr-dziuban** [comment]
@Maxwell2022 I had same issues with Xcode 11, where did you see that CircleCI updated something?

**Comment by Maxwell2022** [comment]
I had problems with ruby versions on xcode agent early this week: https://twitter.com/atmarc/status/1177547547965054977

**Comment by oleksandr-dziuban** [comment]
Ruby works fine if you specify ruby version from https://circleci.com/docs/2.0/testing-ios/ macos images

**Comment by Maxwell2022** [comment]
yes, I know but they removed the version 2.4 on the `xcode 10.3.0` image without saying anything because they were working to set up Xcode 11 that was requiring a different version. It broke all our builds. So I know they are/were tweaking the Xcode agents recently

Yesterday I had the same issue that you are referencing in this ticket but this morning it was fixed without doing anything

**Comment by oleksandr-dziuban** [comment]
Ok, thanks, I will try xcode 11.1 image and close this issue if circile image resolved. Thanks

**Comment by oleksandr-dziuban** [comment]
Nope, same error on xcode 11.1.0 circleci image

**Comment by Maxwell2022** [comment]
@oleksandr-dziuban I would ping https://twitter.com/atmarc on twitter if I were you

**Comment by Zeneixe** [comment]
Same problem here, we tried xcode 11 too

**Comment by oleksandr-dziuban** [comment]
Yep, just `event.cpp` cannot be compiled 
This line show the reason:
`okfacuuibwcjplhtkspodqby/Build/Intermediates.noindex/ArchiveIntermediates/Brandgility/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/Yoga.build/Objects-normal/armv7/event.o /Users/distiller/mobile-web-app/node_modules/react-native/ReactCommon/yoga/yoga/event/event.cpp normal armv7 c++ com.apple.compilers.llvm.clang.1_0.compiler`

**Comment by Zeneixe** [comment]
We have this issue only on our RN 0.61.2 branch, the other (0.59.x) is fine

**Comment by bguidolim** [comment]
@oleksandr-dziuban try to set `generate_apple_certs` as `true` on your match action.

**Comment by oleksandr-dziuban** [comment]
Will try, thanks @bguidolim

**Comment by oleksandr-dziuban** [comment]
@bguidolim Unfortunately, this solution doesn't work. This is not a signing issue, it is compilation issue of Yoga.cpp file. I have added this issue to Yoga framework repo too..

**Comment by adamsythe** [comment]
has anyone managed to get their IOS app running on circle?

**Comment by oleksandr-dziuban** [comment]
@adamsythe Unfortunately no, it is still doesn't work...

**Comment by oleksandr-dziuban** [comment]
On CircleCi we still have Error 65 when building iOS app.
I have checked the build flow with detailed logs and fount that we have issue in this line

```bash
Building library libReact-jsiexecutor.a
[15:22:29]: ▸ Building library libReact-jsiexecutor.a
[15:22:30]: ▸ Compiling log.cpp
[15:22:30]: ▸ ❌  error: non-portable path to file ‘“/Users/distiller/mobile-web-app/ios/Pods/Target Support Files/yoga/yoga-prefix.pch”’; specified path differs in case from file name on disk [-Werror,-Wnonportable-include-path]
[15:22:30]: ▸ Compiling experiments.cpp
[15:22:30]: ▸ Compiling event.cpp
[15:22:30]: ▸ Compiling Yoga.cpp
[15:22:30]: ▸     The iOS deployment target ‘IPHONEOS_DEPLOYMENT_TARGET’ is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.1.99. (in target ‘react-native-version-number’ from project ‘Pods’)
[15:22:30]: ▸     The iOS deployment target ‘IPHONEOS_DEPLOYMENT_TARGET’ is set to 6.0, but the range of supported deployment target versions is 8.0 to 13.1.99. (in target ‘RSKImageCropper’ from project ‘Pods’)
[15:22:30]: ▸ ** ARCHIVE FAILED **
[15:22:30]: ▸ The following build commands failed:
[15:22:30]: ▸     CompileC /Users/distiller/Library/Developer/Xcode/DerivedData/Brandgility-ccncokfacuuibwcjplhtkspodqby/Build/Intermediates.noindex/ArchiveIntermediates/Brandgility/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/Yoga.build/Objects-normal/armv7/event.o /Users/distiller/mobile-web-app/node_modules/react-native/ReactCommon/yoga/yoga/event/event.cpp normal armv7 c++ com.apple.compilers.llvm.clang.1_0.compiler
[15:22:30]: ▸ (1 failure)
```

**Comment by oleksandr-dziuban** [comment]
Yoga library cannot be compiled
ios/Pods/Target Support Files/yoga/yoga-prefix.pch in this file we have incorrect path on Xcode 11 image

**Comment by oleksandr-dziuban** [comment]
I have finally found the reason. I had Pods folder under the git to speed up CI builds.
I have deleted it and added Pods to gitignore. Also reinstalled all pods, deleted whole pods cache.
Now on CI I do `pod install` before iOS app build.
Everything is cool, closing the issue.

**Comment by cameronehrlich** [comment]
Updating to ruby 2.6.4 fixed the issue for me.

**Comment by nicovanniekerk** [comment]
Finally!! after struggling with this for weeks, I made the following change to the build_app step in Fastlane and the builds started working. granted the above "don't cache pods" and "update ruby" probably helped as well.

we had, , xcargs: "-UseModernBuildSystem=NO"
changed to , xcargs: "-UseModernBuildSystem=YES"

BUILDS WOrKING!!
