### ISSUE TITLE
CI tests are currently failing because of faraday 0.16.x update

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#15398]
This is more a FYI than a real issue: `faraday` recently released 0.16.x which change a few things around, some of which seem to cause our tests to fail. 

I reported the behavior on their repo at https://github.com/lostisland/faraday/issues/1036 and we will see if a) we downgrade and pin 0.15.4 (which was fine) or b) we wait for them to release a 0.16.2 that fixes these issues.

PS: We still love faraday <3

**Comment by yenda** [comment]
It is not just CI though, currently auth with spaceship is broken as in #15397
Pinning faraday to 0.15.4 in Gemfile does solve the issue

**Comment by janpio** [comment]
Thanks for that tip.

I created and merged https://github.com/fastlane/fastlane/pull/15399 so `master` passes again. We will see if we need to do a hotfix here (ping @joshdholtz)

**Comment by LondonAtlas** [comment]
There is still a runtime error after typing an code sent via SMS:

`bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
RuntimeError: [!] can't modify frozen String
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/client.rb:811:in `force_encoding'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/client.rb:811:in `log_response'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/client.rb:846:in `block in send_request'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/client.rb:620:in `with_retry'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/client.rb:844:in `send_request'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/client.rb:688:in `request'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:290:in `store_session'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:98:in `handle_two_step_for_device'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:42:in `handle_two_step'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:18:in `handle_two_step_or_factor'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/client.rb:494:in `send_shared_login_request'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/tunes/tunes_client.rb:127:in `send_login_request'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/client.rb:770:in `do_login'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/client.rb:384:in `login'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/client.rb:346:in `login'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/pilot/lib/pilot/manager.rb:23:in `login'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/pilot/lib/pilot/manager.rb:16:in `start'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/pilot/lib/pilot/build_manager.rb:17:in `upload'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:16:in `run'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
  Fastfile:36:in `block (2 levels) in parsing_binding'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.131.0/bin/fastlane:23:in `<top (required)>'
  /usr/local/bin/fastlane:22:in `load'
  /usr/local/bin/fastlane:22:in `<top (required)>'`

**Comment by LondonAtlas** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.21.0 (Apple Git-122)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.6 (18G103)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.0                                                           |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Download dsyms"
  lane :dsyms do
    download_dsyms                  # Download dSYM files from iTC
    upload_symbols_to_crashlytics   # Upload them to Crashlytics
    clean_build_artifacts           # Delete the local dSYM files
  end


  desc "Push a new beta build to TestFlight"
  lane :beta do |options|
    increment_build_number
    version = get_version_number(target: "App")
    build_number = get_build_number
    
    match(type: "appstore", readonly: true)
    gym
    pilot(skip_waiting_for_build_processing: true)
    # download_dsyms(version: "latest")
    sh('git commit -am "New Beta Build"')
    sh('git push')
    add_git_tag(
      tag: "#{get_version_number(target: "App")}-#{get_build_number}"
    )
    upload_symbols_to_crashlytics
    clean_build_artifacts
    
    notification(message: "Finished Building & Uploading")
    
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.app") # The bundle identifier of your app
apple_id("email@email.com") # Your Apple email address

itc_team_id("...") # App Store Connect Team ID
itc_team_id("...") # App Store Connect Team ID
team_id("...") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.131.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 2.0.1        |
| io-console                | 0.4.5        |
| CFPropertyList            | 3.0.1        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.67.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.16.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.1        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.0904  |
| mime-types                | 3.3          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>


*generated on:* **2019-09-28**
</details>

In case this helps

**Comment by janpio** [comment]
Please create a new issue instead of abusing this existing one @LondonAtlas. But https://github.com/fastlane/fastlane/issues/15397 includes a workaround that you should be able to apply.

**Comment by LondonAtlas** [comment]
Apologies. That #15397 did work, thank you for the help.
