### ISSUE TITLE
Use isign to replace some macOS only tools

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#15406]
https://github.com/yihuang/isign via https://github.com/fastlane/fastlane/issues/11687#issuecomment-536252797

- What parts of fastlane could this help with?
	- Resigning?
	- Signing in the first place?
	- Building?
	- Anything else that Xcode does?
- Investigate if this also works on Windows

Ping @yihuang

---

https://github.com/saucelabs/isign is the original source.

**Comment by yihuang** [comment]
To use fastlane in non-mac system, you need to get rid of the keychain first, which means managing all the private keys and certificates on your own.
