### ISSUE TITLE
Error Using appcenter_upload

### ISSUE THREAD

**Issue by bl718w** [fastlane/fastlane#15405]
### New Issue Checklist

- [ x ] Updated fastlane to the latest version
- [ x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Tried uploading IPA to Appcenter with appcenter_upload and getting a weird error.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>/home/travis/.rvm/gems/ruby-2.4.1/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response/follow_redirects.rb:6:in `<module:FaradayMiddleware>': [!] superclass must be a Class (Faraday::DeprecatedConstant given) (TypeError)
        from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response/follow_redirects.rb:4:in `<top (required)>'
        from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-plugin-appcenter-1.4.0/lib/fastlane/plugin/appcenter/helper/appcenter_helper.rb:35:in `block in connection'
        from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.16.1/lib/faraday/connection.rb:89:in `initialize'
        from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.16.1/lib/faraday.rb:84:in `new'
        from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.16.1/lib/faraday.rb:84:in `new'
        from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-plugin-appcenter-1.4.0/lib/fastlane/plugin/appcenter/helper/appcenter_helper.rb:27:in `connection'
        from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-plugin-appcenter-1.4.0/lib/fastlane/plugin/appcenter/helper/appcenter_helper.rb:366:in `get_app'
        from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-plugin-appcenter-1.4.0/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:210:in `get_or_create_app'
        from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-plugin-appcenter-1.4.0/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:237:in `run'
        from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
        from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
        from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
        from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
        from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
        from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/fastlane/lib/fastlane/one_off.rb:42:in `run'
        from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/fastlane/lib/fastlane/one_off.rb:22:in `execute'
        from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/fastlane/lib/fastlane/commands_generator.rb:221:in `block (2 levels) in run'
        from /home/travis/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from /home/travis/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        from /home/travis/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        from /home/travis/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
        from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
        from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/bin/fastlane:23:in `<top (required)>'
        from /home/travis/.rvm/gems/ruby-2.4.1/bin/fastlane:23:in `load'
        from /home/travis/.rvm/gems/ruby-2.4.1/bin/fastlane:23:in `<main>'
        from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
        from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'</pre>
</details>

### Environment

<details>
  <pre>[05:22:24]: [33mGenerating fastlane environment output, this might take a few seconds...[0m
<details><summary>? fastlane environment ?</summary>

### Stack

| Key                         | Value                                              |
| --------------------------- | -------------------------------------------------- |
| OS                          | 10.14.4                                            |
| Ruby                        | 2.4.5                                              |
| Bundler?                    | true                                               |
| Git                         | git version 2.21.0                                 |
| Installation Source         | ~/.rvm/gems/ruby-2.4.5/bin/fastlane                |
| Host                        | Mac OS X 10.14.4 (18E226)                          |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.5/lib                       |
| OpenSSL Version             | OpenSSL 1.1.1a  20 Nov 2018                        |
| Is contained                | false                                              |
| Is homebrew                 | false                                              |
| Is installed via Fabric.app | false                                              |
| Xcode Path                  | /Applications/Xcode-10.2.1.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ? |
| LC_ALL   | en_US.UTF-8 | ? |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

require 'fileutils'

platform :ios do
...
...
      appcenter_upload(
         api_token: ENV["APPCENTER_TOKEN"],
         owner_name: ENV["APPCENTER_ACCOUNT"],
         app_name: "<app name>",
         ipa: "<ipa file>",
         notify_testers: true
      )
...
...
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.131.0 | ? Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-aws_s3    | 1.6.0   | ? Up-To-Date  |
| fastlane-plugin-appcenter | 1.4.0   | ? Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 2.0.1        |
| CFPropertyList            | 3.0.1        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| rubyzip                   | 1.3.0        |
| apktools                  | 0.7.3        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.0.3        |
| aws-sigv4                 | 1.1.0        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 2.11.363     |
| aws-sdk-resources         | 2.11.363     |
| aws-sdk                   | 2.11.363     |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.67.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.16.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.1        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.0904  |
| mime-types                | 3.3          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-appcenter | 1.4.0        |
| fastlane-plugin-aws_s3    | 1.6.0        |
</details>

*generated on:* **2019-09-29**
</details>
[05:22:24]: [33mTake notice that this output may contain sensitive information, or simply information that you don't want to make public.[0m
[05:22:24]: [32mOpen https://github.com/fastlane/fastlane/issues/new to submit a new issue ?[0m
</pre>
</details>

**Comment by bl718w** [comment]
After looking through earlier builds that was successful, I found the culprit was a bad component:  faraday (0.16.1).  Downgraded to faraday (0.15.4) and works fine.  Please fix later release.

**Comment by janpio** [comment]
See https://github.com/fastlane/fastlane/issues/15397
