### ISSUE TITLE
CI should consistently output environment information

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#15409]
The list of installed bundles is only visible, if they are actually installed and not taken from cache. CI should add explicit steps that output the bundles, ruby version and other relevant information so it is easier to understand what is going on when debugging failing tests.

**Comment by Katsz** [comment]
Feature you are requesting is not relevant to fastlane, as for me.
But you always can fetch all information you need by printing something like
`puts Gem.loaded_specs.values.map {|x| "#{x.name} #{x.version}"` which will show you full list of gems loaded in runtime.

**Comment by janpio** [comment]
This is a request for our CI we use to build fastlane. Recent problems showed us it is very relevant indeed.
