### ISSUE TITLE
fastlane finished with errors

### ISSUE THREAD

**Issue by mattmillen888** [fastlane/fastlane#15418]
```
/Users/testmac/Sites/_matt_first_app/ios-project-template/fastlane/libs/encryption.rb:32:in `decrypt': [!] undefined method `each_child' for Dir:Class (NoMethodError)
	from /Users/testmac/Sites/_matt_first_app/ios-project-template/fastlane/libs/signing.rb:8:in `create_signing_configuration'
	from Fastfile:32:in `build'
	from Fastfile:13:in `block (2 levels) in parsing_binding'
	from /Users/testmac/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/testmac/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/testmac/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/testmac/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/testmac/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/testmac/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/testmac/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/testmac/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/testmac/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/testmac/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/testmac/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/testmac/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/testmac/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.131.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/testmac/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/testmac/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	from /Users/testmac/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/testmac/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Users/testmac/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.131.0/bin/fastlane:23:in `<top (required)>'
	from /Users/testmac/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/testmac/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.16.3                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.6 (18G95)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.0                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
require './libs/encryption.rb'
require './libs/signing.rb'

default_platform(:ios)

platform :ios do

  lane :test do
    run_tests(scheme: 'iOSProject')
  end

  lane :staging do
    build("../signing/staging", "Staging" ,"ad-hoc")
    staging_upload
  end

  lane :release do
    build("../signing/release", "Release" ,"app-store")
    upload_to_testflight(skip_submission: true)
  end

  lane :encrypt do
    key = prompt(
      text: "Encryption key: ",
      secure_text: true
    )
    encrypt("../signing/staging", key)
    encrypt("../signing/release", key)
  end

  def build(folder, configuration, export_method)
    create_signing_configuration(folder, ENV['FILE_DECRYPTION_KEY'])

    increment_build_number(build_number: number_of_commits(all: true))

    build_ios_app(
      scheme: 'iOSProject',
      export_method: export_method,
      configuration: configuration
    )

    clear_signing_configuration(folder)
  end

  def staging_upload()
    hockey(
      api_token: ENV['HOCKEYAPP_API_TOKEN'],
      ipa: lane_context[SharedValues::IPA_OUTPUT_PATH],
      dsym: lane_context[SharedValues::DSYM_OUTPUT_PATH]
    )
  end
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.131.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| jwt                       | 2.1.0        |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| multi_json                | 1.12.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| libxml-ruby               | 3.0.0        |
| psych                     | 2.0.8        |
</details>

*generated on:* **2019-10-01**
</details>

**Comment by janpio** [comment]
Please don't just delete the issue template, fill it - otherwise we do not have the context to be able to help you. I have no idea what command you were trying to run here etc.
