### ISSUE TITLE
fastlane env failure when git not installed

### ISSUE THREAD

**Issue by ffrevol** [fastlane/fastlane#15414]
### New Issue Checklist

- [ x] Updated fastlane to the latest version
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Running "fastlane env" command failed  if git is not installed on the environment.
What's my case on my CI gitlab-runner container.

##### Command executed

# fastlane env

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
# fastlane env
[✔] 🚀
[13:48:38]: fastlane detected a Gemfile in the current directory
[13:48:38]: however it seems like you don't use `bundle exec`
[13:48:38]: to launch fastlane faster, please use
[13:48:38]:
[13:48:38]: $ bundle exec fastlane env
[13:48:38]:
[13:48:38]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[13:48:38]: Generating fastlane environment output, this might take a few seconds...

[13:48:38]: Error accessing file, this might be due to fastlane's directory handling
[13:48:38]: Check out https://docs.fastlane.tools/advanced/#directory-behavior for more details

Traceback (most recent call last):
	15: from /usr/local/bin/fastlane:23:in `<main>'
	14: from /usr/local/bin/fastlane:23:in `load'
	13: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.131.0/bin/fastlane:23:in `<top (required)>'
	12: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	11: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	10: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	 9: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	 8: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.131.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 7: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 6: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 5: from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 4: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/commands_generator.rb:263:in `block (2 levels) in run'
	 3: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/environment_printer.rb:4:in `output'
	 2: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/environment_printer.rb:24:in `get'
	 1: from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/environment_printer.rb:214:in `print_system_environment'
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/environment_printer.rb:214:in ``': No such file or directory - git (Errno::ENOENT)
</pre>
</details>

### Environment

<details>
  <pre>  docker container with ubuntu 16.04 </pre>
</details>

**Comment by janpio** [comment]
Thanks for reporting this, although not very common we should handle that better.

Open for Pull Requests here.
