### ISSUE TITLE
Changelog not being truncated correctly

### ISSUE THREAD

**Issue by grav** [fastlane/fastlane#15412]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When uploading to AppStore Connect, I get the message from fastlane, that the changelog will be truncated. But nevertheless I receive an error 500 from AppStore Connect:

```
[20:57:10]: Waiting for App Store Connect to finish processing the new build (5.7.0 - 20190928.1) for IOS
[20:57:41]: Waiting for App Store Connect to finish processing the new build (5.7.0 - 20190928.1) for IOS
[20:58:12]: Successfully finished processing the build 5.7.0 - 20190928.1 for IOS
[20:58:12]: Changelog has been truncated since it exceeds Apple's 4000 character limit. It currently contains 4100 characters.

[!] Could not set changelog: Server error got 500
##[error]Error: fastlane failed with return code: 1
```

If I instead manually truncate the changelog (using `| head -c 3900`), it seems to work fine. (I haven't tried going up to 4000 bytes since we're on a slow CI).

My suspicion is, either Apple actually allows less than 4k, or there's an issue with number of bytes and number of unicode characters.

**Comment by janpio** [comment]
What action exactly are you using?

**Comment by grav** [comment]
We're using Azure Pipelines with the Apple App Store extensions. So it's just executing fastlane from command line. Here's some more from the log:

```
fastlane pilot upload -u *** -i /Users/vsts/agent/2.155.1/work/1/s/appstore/MyApp.ipa --changelog [snip]  -q [snip] -a [snip] --distribute_external true --groups [snip]
```
