### ISSUE TITLE
can't modify frozen String

### ISSUE THREAD

**Issue by electic** [fastlane/fastlane#15415]
Sigh fails with the error 'can't modify frozen String'. The version of spaceship is 2.131.0.

- [x ] Updated fastlane to the latest version
- [ x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

`/Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/spaceship/lib/spaceship/client.rb:811:in `force_encoding': [!] can't modify frozen String (RuntimeError)
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/spaceship/lib/spaceship/client.rb:811:in `log_response'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/spaceship/lib/spaceship/client.rb:846:in `block in send_request'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/spaceship/lib/spaceship/client.rb:620:in `with_retry'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/spaceship/lib/spaceship/client.rb:844:in `send_request'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/spaceship/lib/spaceship/client.rb:688:in `request'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:290:in `store_session'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:189:in `handle_two_factor'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:20:in `handle_two_step_or_factor'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/spaceship/lib/spaceship/client.rb:494:in `send_shared_login_request'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/spaceship/lib/spaceship/portal/portal_client.rb:28:in `send_login_request'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/spaceship/lib/spaceship/client.rb:770:in `do_login'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/spaceship/lib/spaceship/client.rb:384:in `login'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/spaceship/lib/spaceship/client.rb:346:in `login'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/spaceship/lib/spaceship/portal/spaceship.rb:25:in `login'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/spaceship/lib/spaceship/portal/spaceship.rb:103:in `login'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/sigh/lib/sigh/runner.rb:19:in `run'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/sigh/lib/sigh/manager.rb:8:in `start'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/fastlane/lib/fastlane/actions/get_provisioning_profile.rb:19:in `run'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
	from Fastfile:126:in `block (2 levels) in parsing_binding'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Users/electic/.rvm/gems/ruby-2.4.1/gems/fastlane-2.131.0/bin/fastlane:23:in `<top (required)>'
	from /Users/electic/.rvm/gems/ruby-2.4.1/bin/fastlane:23:in `load'
	from /Users/electic/.rvm/gems/ruby-2.4.1/bin/fastlane:23:in `<main>'
	from /Users/electic/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/electic/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'`

**Comment by electic** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.21.0 (Apple Git-122)          |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane         |
| Host                        | Mac OS X 10.14.6 (18G95)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0g  2 Nov 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.0                                        |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
ENV['DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS'] = '-t DAV'

# Minimum version of fastlane
fastlane_version "1.32.1"

default_platform :ios

platform :ios do
  desc "Download and refresh profiles"

  private_lane :set_build_number do
    build_number = version_number
    increment_build_number(
      build_number: build_number,
      xcodeproj: 'Coinhub.xcodeproj'
    )
  end

  private_lane :set_version_number do
    increment_version_number
  end

  private_lane :code_sign do |options|
  end

  private_lane :version_number do
    Time.now.strftime('%s%3N')
  end

  #
  # Public Lanes
  #

  lane :update_certs do
    match(type: "development", app_identifier: "com.electic.coinhub", force_for_new_devices: true)
    match(type: "adhoc", app_identifier: "com.electic.coinhub", force_for_new_devices: true)
    match(type: "appstore", app_identifier: "com.electic.coinhub")
  end

  lane :provision do
    produce(
      app_name: 'CoinHub',
      language: 'English',
      app_version: '1.5.4',
      sku: '1001'
    )

    cert
    sigh(force: true)
  end

  desc "Create production"
  lane :build do
    build_number = version_number
    gym(
      scheme: "CoinHub",
      include_symbols: false,
      clean: true,
      workspace: 'Coinhub.xcworkspace',
      include_bitcode: false,
      output_directory: "fastlane/build",
      output_name: "CoinHub-#{build_number}.ipa",
      export_xcargs: "-allowProvisioningUpdates"
    )
  end

  lane :upload_dsyms do
    upload_symbols_to_bugsnag # Upload them to Bugsnag
  end

  lane :refresh_dsyms do
    version_number = get_version_number(xcodeproj: "Coinhub.xcodeproj")

    download_dsyms(version: version_number)                  # Download dSYM files from iTC
    upload_symbols_to_bugsnag              	    # Upload them to Bugsnag
    clean_build_artifacts                  	    # Delete the local dSYM files
  end

  desc "Deliver to iTunes"
  lane :upload do
    deliver
  end

  desc "Deliver beta"
  lane :beta do |options|
    set_build_number

    if options[:increment_version_number]
      set_version_number
    end

    changelog = File.read("changelog_testflight.log")

    build
    sigh
    pilot(distribute_external: false, wait_for_uploaded_build: true, changelog: 'Bug fixes and improvements.')
  end

  desc "Deliver beta to itunes"
  lane :beta_external do |options|
    set_build_number

    if options[:increment_version_number]
      set_version_number
    end

    changelog = File.read("changelog_testflight.log")

    build
    sigh
    pilot(distribute_external: true, changelog: 'Bug fixes and improvements.', groups: "External Testers")
    #upload_symbols_to_bugsnag
  end

desc "Deliver beta to itunes"
  lane :beta_qa do |options|
    set_build_number

    if options[:increment_version_number]
      set_version_number
    end

    changelog = File.read("changelog_testflight.log")

    build
    sigh
    pilot(distribute_external: true, wait_for_uploaded_build: true, changelog: 'Bug fixes and improvements.', groups: "QA Group")
    #upload_symbols_to_bugsnag
  end

  error do |lane, exception|
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.electic.coinhub" # The bundle identifier of your app
apple_id "info@electic.com" # Your Apple email address

team_id "X9ZRCHK95K" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.131.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status |
| ----------------------- | ------- | ------------- |
| fastlane-plugin-bugsnag | 1.4.1   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.0       |
| CFPropertyList            | 3.0.1        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.67.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.16.2       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.1        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.0904  |
| mime-types                | 3.3          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| git                       | 1.5.0        |
| xml-simple                | 1.1.5        |
| fastlane-plugin-bugsnag   | 1.4.1        |
</details>


*generated on:* **2019-09-30**
</details>

**Comment by janpio** [comment]
See https://github.com/fastlane/fastlane/issues/15397 - known issue and trying to get it fixed. Temporary workaround is in there as well.
