### ISSUE TITLE
Fastlane can't add plugin [Firebase App Distribution]

### ISSUE THREAD

**Issue by TBoonkwan** [fastlane/fastlane#15419]
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

<img width="1280" alt="Screen Shot 2562-10-01 at 13 54 03" src="https://user-images.githubusercontent.com/34676434/65940583-10fdd580-e453-11e9-841f-372daf95da8e.png">
<img width="1280" alt="Screen Shot 2562-10-01 at 13 58 41" src="https://user-images.githubusercontent.com/34676434/65940803-a6996500-e453-11e9-8dd6-778c5043f427.png">
<img width="1280" alt="Screen Shot 2562-10-01 at 13 58 54" src="https://user-images.githubusercontent.com/34676434/65940804-a6996500-e453-11e9-9b14-37b0c269e065.png">

**Comment by janpio** [comment]
Please don't delete the issue template, but fill it with the information is asks for to be able to help you. Please also post the actual text, not just a screenshot. Thanks.
