### ISSUE TITLE
add background mode service

### ISSUE THREAD

**Issue by sante85** [fastlane/fastlane#15428]
#### Motivation Behind Feature
add background mode feature by command

#### Feature Description
automatic add feature asap push-notification
can i add a PR?

**Comment by janpio** [comment]
Of course, we are always welcoming PRs.

**Comment by sante85** [comment]
I sensi via mail a RB script

Il ven 4 ott 2019, 16:46 Jan Piotrowski <notifications@github.com> ha
scritto:
