### ISSUE TITLE
Match with Google Cloud: Impossible to run in noninteractive mode (CI)

### ISSUE THREAD

**Issue by jfaust** [fastlane/fastlane#15426]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

As of https://github.com/fastlane/fastlane/commit/ac161c41398f3d841247f420d22f80a6dd2f2d71, it seems like it's impossible to use `fastlane match` with Google Storage in a noninteractive shell. This is because of a new use of `UI.confirm()`, which immediately bails in a noninteractive context.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
[17:09:53]: -----------------------------
[17:09:53]: --- Step: update_fastlane ---
[17:09:53]: -----------------------------
[17:09:53]: Looking for updates for fastlane...
[17:09:55]: Nothing to update ✅
[17:09:55]: 
[17:09:55]: Please help us test early releases of fastlane by opting into nightly builds 🌃
[17:09:55]: Just replace your `update_fastlane` call with
[17:09:55]: 
[17:09:55]: ▸ update_fastlane(nightly: true)
[17:09:55]: 
[17:09:55]: Nightly builds are reviewed and tested just like the public releases 🚂
[17:09:55]: 
[17:09:55]: ------------------------------
[17:09:55]: --- Step: default_platform ---
[17:09:55]: ------------------------------
[17:09:55]: Driving the lane 'ios ios_dev_certs' 🚀
[17:09:55]: ----------------------------------------------
[17:09:55]: --- Step: Switch to ios ios_get_certs lane ---
[17:09:55]: ----------------------------------------------
[17:09:55]: Cruising over to lane 'ios ios_get_certs' 🚖
Getting certs for XXXXXXXXX: development
[17:09:55]: -------------------
[17:09:55]: --- Step: match ---
[17:09:55]: -------------------
WARNING: You are running Ruby 2.3.7, which is nearing end-of-life.
The Google Cloud API clients work best on supported versions of Ruby. Consider upgrading to Ruby 2.4 or later.
See https://www.ruby-lang.org/en/downloads/branches/ for more info on the Ruby maintenance schedule.
To suppress this message, set the GOOGLE_CLOUD_SUPPRESS_RUBY_WARNINGS environment variable.
[17:09:55]: Successfully loaded 'XXXXXXXXX' 📄

+--------------------------+------------------------+
|        Detected Values from './Matchfile'         |
+--------------------------+------------------------+
| storage_mode             | google_cloud           |
| google_cloud_bucket_name | XXXXXXXXX   |
| google_cloud_project_id  | XXXXXXXXX              |
| type                     | development            |
| app_identifier           | XXXXXXXXX |
| username                 | XXXXXX    |
+--------------------------+------------------------+

+----------------------------+----------------------------+
|                Summary for match 2.132.0                |
+----------------------------+----------------------------+
| type                       | development                |
| app_identifier             | ["XXXXXXXXX"] |
| readonly                   | true                       |
| shallow_clone              | true                       |
| force                      | false                      |
| generate_apple_certs       | false                      |
| skip_provisioning_profiles | false                      |
| username                   | XXXXXX        |
| storage_mode               | google_cloud               |
| git_branch                 | master                     |
| clone_branch_directly      | false                      |
| google_cloud_bucket_name   | XXXXXXXXX       |
| google_cloud_project_id    | XXXXXXXXX                  |
| keychain_name              | login.keychain             |
| force_for_new_devices      | false                      |
| skip_confirmation          | false                      |
| skip_docs                  | false                      |
| platform                   | ios                        |
| verbose                    | false                      |
+----------------------------+----------------------------+

[17:09:55]: Did you already create a Google Cloud Storage bucket?
+------------------+-------------------+
|             Lane Context             |
+------------------+-------------------+
| DEFAULT_PLATFORM | ios               |
| PLATFORM_NAME    | ios               |
| LANE_NAME        | ios ios_dev_certs |
+------------------+-------------------+
[17:09:55]: Could not retrieve response as fastlane runs in non-interactive mode

+------+----------------------------------+-------------+
|                   fastlane summary                    |
+------+----------------------------------+-------------+
| Step | Action                           | Time (in s) |
+------+----------------------------------+-------------+
| 1    | update_fastlane                  | 2           |
| 2    | default_platform                 | 0           |
| 3    | Switch to ios ios_get_certs lane | 0           |
| 💥   | match                            | 0           |
+------+----------------------------------+-------------+

[17:09:55]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  CircleCI: Could not find fastlane in current directory.
    https://github.com/fastlane/fastlane/issues/15341 [open] 3 💬
    a week ago

➡️  Fastlain Android screengrab. Could not retrieve response as fastlane runs in non-interactive mode
    https://github.com/fastlane/fastlane/issues/14869 [closed] 6 💬
    a week ago

➡️  FastLane 2.124 FastlaneCore::Interface::FastlaneCrash: [!] Could not retrieve response as fastlane runs in non-interactive mode
    https://github.com/fastlane/fastlane/issues/14835 [closed] 6 💬
    a week ago

and 41 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/administrator/.gems/gems/fastlane-2.132.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': [!] Could not retrieve response as fastlane runs in non-interactive mode (FastlaneCore::Interface::FastlaneCrash)
	from /Users/administrator/.gems/gems/fastlane-2.132.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:156:in `verify_interactive!'
	from /Users/administrator/.gems/gems/fastlane-2.132.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:134:in `confirm'
	from /Users/administrator/.gems/gems/fastlane-2.132.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/administrator/.gems/gems/fastlane-2.132.0/match/lib/match/storage/google_cloud_storage.rb:296:in `ensure_bucket_is_selected'
	from /Users/administrator/.gems/gems/fastlane-2.132.0/match/lib/match/storage/google_cloud_storage.rb:99:in `initialize'
	from /Users/administrator/.gems/gems/fastlane-2.132.0/match/lib/match/storage/google_cloud_storage.rb:38:in `new'
	from /Users/administrator/.gems/gems/fastlane-2.132.0/match/lib/match/storage/google_cloud_storage.rb:38:in `configure'
	from /Users/administrator/.gems/gems/fastlane-2.132.0/match/lib/match/storage.rb:14:in `block in backends'
	from /Users/administrator/.gems/gems/fastlane-2.132.0/match/lib/match/storage.rb:36:in `for_mode'
	from /Users/administrator/.gems/gems/fastlane-2.132.0/match/lib/match/runner.rb:32:in `run'
	from /Users/administrator/.gems/gems/fastlane-2.132.0/fastlane/lib/fastlane/actions/sync_code_signing.rb:13:in `run'
	from /Users/administrator/.gems/gems/fastlane-2.132.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
	from /Users/administrator/.gems/gems/fastlane-2.132.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/administrator/.gems/gems/fastlane-2.132.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
	from /Users/administrator/.gems/gems/fastlane-2.132.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/administrator/.gems/gems/fastlane-2.132.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/administrator/.gems/gems/fastlane-2.132.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/administrator/.gems/gems/fastlane-2.132.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:14:in `match_and_copy_provisioning_profile'
	from Fastfile:26:in `block (3 levels) in parsing_binding'
	from Fastfile:24:in `each'
	from Fastfile:24:in `block (2 levels) in parsing_binding'
	from /Users/administrator/.gems/gems/fastlane-2.132.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/administrator/.gems/gems/fastlane-2.132.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	from /Users/administrator/.gems/gems/fastlane-2.132.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
	from /Users/administrator/.gems/gems/fastlane-2.132.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:33:in `block (2 levels) in parsing_binding'
	from /Users/administrator/.gems/gems/fastlane-2.132.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/administrator/.gems/gems/fastlane-2.132.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/administrator/.gems/gems/fastlane-2.132.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/administrator/.gems/gems/fastlane-2.132.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/administrator/.gems/gems/fastlane-2.132.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/administrator/.gems/gems/fastlane-2.132.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/administrator/.gems/gems/fastlane-2.132.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/administrator/.gems/gems/fastlane-2.132.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/administrator/.gems/gems/fastlane-2.132.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	from /Users/administrator/.gems/gems/fastlane-2.132.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/administrator/.gems/gems/fastlane-2.132.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Users/administrator/.gems/gems/fastlane-2.132.0/bin/fastlane:23:in `<top (required)>'
	from /Users/administrator/.gems/bin/fastlane:22:in `load'
	from /Users/administrator/.gems/bin/fastlane:22:in `<main>'
</pre>
</details>

**Comment by jfaust** [comment]
Pinging @rickclephas and @joshdholtz since they were involved in https://github.com/fastlane/fastlane/pull/15310

**Comment by evelyne24** [comment]
Breaks CI, lol.
