### ISSUE TITLE
How can I refresh match development certs with xcode 11 support?

### ISSUE THREAD

**Issue by yusuftor** [fastlane/fastlane#15429]
I want to update my provisioning profiles to be able to be used with Xcode 11. I'm using the latest version of fastlane, and tried doing this:

`fastlane match development --generate_apple_certs --force`

But that still doesn't generate them for use in Xcode 11. Am I missing something?

**Comment by alphatroya** [comment]
I think you should nuke older development certs in your repo. After that calling the command will create a new version certificate.

**Comment by LaVielle** [comment]
Yep, I'd say the same as @alphatroya 
Nuke your current certs
```
fastlane match nuke development
```

Then regenerate fresh certs
```
fastlane match development
```

After that and the warning in xcode "provisioning profile doesn't include signing certificate..." is gone 🥳

**Comment by yusuftor** [comment]
Nuking it worked, thanks!
