### ISSUE TITLE
Update Slack action to support current API

### ISSUE THREAD

**Issue by rickclephas** [fastlane/fastlane#15431]
#### Motivation Behind Feature

The current implementation of the Slack action is using an [outdated gem](https://github.com/stevenosloan/slack-notifier).
This is causing issues like #15362 and doesn't support the new [layout blocks](https://api.slack.com/messaging/composing/layouts).

#### Feature Description

Replace the Slack action with an HTTP wrapper which allows for more customisation.

#### Alternatives or Workarounds

It is currently only possible to send basic messages to a webhook (which doesn't allow the use of a dynamic channel).

**Comment by rickclephas** [comment]
We should definitely make sure that the new Slack action is backwards compatible with the current one so that users keep getting their messages.

@janpio I found a [gem](https://github.com/slack-ruby/slack-ruby-client) which is very extensive but IMHO that seems overkill. 
The Fastlane action only needs to post messages. 
That can be accomplished with the [chat.postMessage](https://api.slack.com/methods/chat.postMessage) API endpoint.

I propose we create an HTTP wrapper with options that match the top arguments for the JSON request.
We would also keep the `default_payloads` option to easily add common info.
We should also keep any other options which we can map to the "new" Slack API arguments.

**Comment by janpio** [comment]
Sounds like a plan - and as you mentioned yourself full backwards compatibility to the existing action is kind of a requirement.

**Comment by rickclephas** [comment]
@fastlane-bot nope isn't fixed.

**Comment by rickclephas** [comment]
@fastlane-bot I would still like to have this.

**Comment by rickclephas** [comment]
@fastlane-bot haven't had time for this yet but still something I would like.

**Comment by kamvoick** [comment]
@rickclephas is it going to be updated any time soon?

**Comment by rickclephas** [comment]
@kamvoick hi sorry I am currently quite busy with work. I am afraid I won't be able to update the Slack action anytime soon 😔

**Comment by brunomunizaf** [comment]
I'm trying to match that basic-but-cool looking of the tests results on slack notifications but it seems that output_style doesn't change that. Is this related to what you said "...doesn't support the new layout blocks." @rickclephas ?

**Comment by crazymanish** [comment]
Hi @rickclephas @brunomunizaf @kamvoick  
You can send a direct message now:) Please let me know if you need any help! 😍
https://github.com/crazymanish/fastlane-plugin-slack_bot

Thanks, @joshdholtz for unlocking the issue! 🙏🏻
