### ISSUE TITLE
Why is Xcode 11 resultBundlePath `.xcresult` symlinked?

### ISSUE THREAD

**Issue by crsantos** [fastlane/fastlane#15438]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

This is mostly a question related with `Scan`

#### Question Description

As of Xcode 11, the `.xcreport` format changed and in order to generate code coverage, we need to run the following :

```bash
xcrun xccov view --report --json Example.xcresult
```

I was doing some tests to generate a `json` file with coverage data but I need the final output path that `Scan` defines as `test_result`, so I was checking if I can use `Scan.cache[:result_bundle_path]` (not even sure if that's reliable/will change, but I found no other way).

It's something like; `./fastlane/test_output/MyLibName.test_result`

The thing is, that cached value is a **symlink**, to the real `./fastlane/test_output/MyLibName.test_result.xcresult`.

**Problem**

It's impossible to run `xcrun xccov view --report` against that symlink, or against something that doesn't have the extension `.xcresult`, the xcov tool triggers an error saying: 

`Error: unrecognized file format`.

**So my 2 questions are:**

- Is Scan that is doing this symlink? I couldn't find a symlink being created inside fast lane Scan src-code ([but maybe I didn't dig a lot](https://github.com/fastlane/fastlane/blob/155c5506b9625c1397433fe6b45b67ca7463a64f/scan/lib/scan/test_command_generator.rb))
    - If it isn't `Scan`,  does anyone have an idea how is that symlinking? Because on DerivedData there's no such symlink. It's a regular `.xcresult` bundle.
- Do I have another way of retrieving the output path of that `.xcresult`, the bundle itself?
     -  If I had the previous dir, maybe I can do some glob pattern match to find the file (like `../*.result`) but I have no guarantee that's the one that contains the last test data for that test run.

Any ideas are welcome.

### `fastlane env` output

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.5.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.19.1                          |
| Installation Source         | ~/.asdf/installs/ruby/2.5.3/bin/fastlane    |
| Host                        | Mac OS X 10.14.6 (18G95)                    |
| Ruby Lib Dir                | ~/.asdf/installs/ruby/2.5.3/lib             |
| OpenSSL Version             | OpenSSL 1.0.2p  14 Aug 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.0                                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
<<redacted>>
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.129.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| bundler                   | 2.0.2        |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.1.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.12.2       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.11.1     |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| httpclient                | 2.8.3        |
| json                      | 2.2.0        |
| algoliasearch             | 1.27.1       |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| cork                      | 0.3.0        |
| nap                       | 1.1.0        |
| open4                     | 1.3.4        |
| claide-plugins            | 0.9.2        |
| fuzzy_match               | 2.0.4        |
| cocoapods-core            | 1.8.1        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.2.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.4.1        |
| cocoapods-try             | 1.1.0        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| cocoapods                 | 1.8.1        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| faraday-http-cache        | 2.0.0        |
| git                       | 1.5.0        |
| kramdown                  | 2.1.0        |
| kramdown-parser-gfm       | 1.1.0        |
| no_proxy_fix              | 0.1.2        |
| sawyer                    | 0.8.2        |
| octokit                   | 4.14.0       |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| danger                    | 6.0.9        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| multi_xml                 | 0.6.0        |
| httparty                  | 0.17.0       |
| gitlab                    | 4.12.0       |
| danger-gitlab             | 7.0.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.66.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.1        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.0        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| mini_magick               | 4.9.5        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.3        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| xcode-install             | 2.6.0        |
</details>

*generated on:* **2019-10-05**
</details>

**Comment by crsantos** [comment]
Not sure if this log in the console helps:

```shell
--- xcodebuild: WARNING: Failed to create symlink at ./fastlane/test_output/MyLib.test_result.xcresult - a file already exists.
```

**Comment by crsantos** [comment]
Didn’t have an answer and couldn’t find a clue in source code. 
Solved this problem by going back 1 directory and matching  `../*.xcresult`

**Comment by xavierjurado** [comment]
> Is Scan that is doing this symlink?

No, it's Xcode. As far as I can tell Xcode 11.x automatically creates a symlink if you invoke `xcodebuild` with a `-resultBundlePath` that uses a non-standard file extension (ie: something other than `xcresult`).

In my opinion we should change Fastlane to use the standard file extension now that it's somewhat documented (https://help.apple.com/xcode/mac/current/#/devc38fc7392).

> Do I have another way of retrieving the output path of that .xcresult, the bundle itself?

As a workaround I guess you could append ".xcresult" to the path you got from `Scan.cache[:result_bundle_path]` . For the particular use case of invoking xccov though, you could also do the following:

`xcrun xccov view --report --json *.xcresult`

**Comment by crsantos** [comment]
Thanks @xavierjurado for following this up.

I ended up matching `../*.xcresult`

Not sure if it's safer than appending `.xcresult` but it's been working.

If this is an Xcode behaviour, I guess I can close this issue now.

Many thanks.
