### ISSUE TITLE
Spaceship login on linux server fail

### ISSUE THREAD

**Issue by keiko15678** [fastlane/fastlane#15446]
### Question Checklist

- [yes] Updated fastlane to the latest version
- [yes] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [yes] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [yes] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Spaceship::Portal.login(account, password)
Spaceship.login(account,password)

#### Question Description

I am trying to login spaceship on a server using a ruby script, which is called by another php when my website is visited. When the ruby script is called, I do receive a 2FA code on my phone, but there is no way for me to input it... I did a try catch and this is what i got:

```
["/usr/local/lib/ruby/gems/2.6.0/gems/highline-1.7.10/lib/highline.rb:868:in `get_line'", "/usr/local/lib/ruby/gems/2.6.0/gems/highline-1.7.10/lib/highline.rb:891:in `get_response'", "/usr/local/lib/ruby/gems/2.6.0/gems/highline-1.7.10/lib/highline.rb:264:in `ask'", "/usr/local/lib/ruby/2.6.0/forwardable.rb:230:in `ask'", "/usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.133.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:196:in `ask_for_2fa_code'", "/usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.133.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:145:in `handle_two_factor'", "/usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.133.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:20:in `handle_two_step_or_factor'", "/usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.133.0/spaceship/lib/spaceship/client.rb:494:in `send_shared_login_request'", "/usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.133.0/spaceship/lib/spaceship/portal/portal_client.rb:28:in `send_login_request'", "/usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.133.0/spaceship/lib/spaceship/client.rb:770:in `do_login'", "/usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.133.0/spaceship/lib/spaceship/client.rb:384:in `login'", "/usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.133.0/spaceship/lib/spaceship/client.rb:346:in `login'", "/usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.133.0/spaceship/lib/spaceship/portal/spaceship.rb:25:in `login'", "/www/wwwroot/ssltest.dra7.cn/updateProfile.rb:20:in `<main>'"]
```

Although I am relatively new to using fastlane/ruby and stuff, but I am fairly sure that this is an issue with 2FA login, where I don't have a way to input the code. My script also works perfectly fine on a mac, and even on my server's terminal (where I have a way to input the code when fastlane asks for login). I have already tried setting FASTLANE_SESSION using spaceauth (maybe I did it wrong) and it did'nt work either. I am not using any fastfile/appfile, I am just trying to login to the Apple Developer Portal and then update my provisioning profiles, where I am just stuck at the login because I cannot input the 2FA code. Please help!!

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key | Value |
| fastlane | 2.133.0 |
| OS | Linux iZj6cfq59j2auoo2i8v5krZ 4.19.43-13.2.al7.x86_64 #1 SMP Tue Jun 18 23:05:54 CST 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Ruby | 2.6.4 |
| Bundler? | false |
| Git | git version 1.8.3.1 |
| Installation Source | /usr/local/bin/fastlane |
| Host | \S
Kernel \r on an \m Linux iZj6cfq59j2auoo2i8v5krZ 4.19.43-13.2.al7.x86_64 #1 SMP Tue Jun 18 23:05:54CST 2019 x86_64 x86_64 x86_64 GNU/Linux (4.19.43-13.2.al7.x86_64) |
| Ruby Lib Dir | /usr/local/lib |
| OpenSSL Version | OpenSSL 1.0.2k  26 Jan 2017 |
| Is contained | false |
| Is homebrew | false |
| Is installed via Fabric.app | false |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.133.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.1        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.1        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.67.0       |
| faraday                   | 0.15.4       |
| faraday_middleware        | 0.13.1       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.3       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| jwt                       | 2.1.0        |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.1        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| json                      | 2.2.0        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.0904  |
| mime-types                | 3.3          |
| retriable                 | 3.1.2        |
| declarative-option        | 0.1.0        |
| declarative               | 0.0.10       |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| google-api-client         | 0.23.9       |
| forwardable               | 1.2.0        |
| logger                    | 1.4.1        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.3.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.8        |
| zlib                      | 1.0.0        |
| rexml                     | 3.2.2        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>

**Comment by janpio** [comment]
Please show the full output you are getting from that code. 
You should be able to check the fastlane code for these two functions to figure out how to exactly use them.

**Comment by keiko15678** [comment]
I will post the output when I can get a hand on it. I’m wondering is there is anyway for me to make fastlane (or the script) wait and let me input the code (perhaps that is not fastlane related)?

**Comment by janpio** [comment]
That is exactly how fastlane itself uses `spaceship`, but how _you_ implement that depends totally on your code and use case.
