### ISSUE TITLE
Screenshot are failing. 

### ISSUE THREAD

**Issue by basilfarraj** [fastlane/fastlane#15447]
fastlane seems to be looping to take screenshots till timeout. Anyone can figure out why using the attached log file?

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                        |
| --------------------------- | -------------------------------------------- |
| OS                          | 10.13.6                                      |
| Ruby                        | 2.3.1                                        |
| Bundler?                    | false                                        |
| Git                         | git version 2.10.2                           |
| Installation Source         | ~/.rbenv/versions/2.3.1/bin/fastlane         |
| Host                        | Mac OS X 10.13.6 (17G65)                     |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.1/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                  |
| Is contained                | false                                        |
| Is homebrew                 | false                                        |
| Is installed via Fabric.app | false                                        |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer// |
| Xcode Version               | 10.1                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.118.1 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                   | Version      |
| --------------------- | ------------ |
| did_you_mean          | 1.0.0        |
| slack-notifier        | 2.3.2        |
| atomos                | 0.1.3        |
| claide                | 1.0.2        |
| colored2              | 3.1.2        |
| nanaimo               | 0.2.6        |
| xcodeproj             | 1.8.1        |
| rouge                 | 2.0.7        |
| xcpretty              | 0.3.0        |
| terminal-notifier     | 2.0.0        |
| plist                 | 3.1.0        |
| multipart-post        | 2.0.0        |
| word_wrap             | 1.0.0        |
| public_suffix         | 2.0.5        |
| babosa                | 1.0.2        |
| colored               | 1.2          |
| commander-fastlane    | 4.4.6        |
| http-cookie           | 1.0.3        |
| faraday-cookie_jar    | 0.0.6        |
| gh_inspector          | 1.1.3        |
| mini_magick           | 4.5.1        |
| multi_xml             | 0.6.0        |
| rubyzip               | 1.2.2        |
| security              | 0.1.3        |
| google-cloud-env      | 1.0.5        |
| google-cloud-core     | 1.3.0        |
| declarative           | 0.0.10       |
| declarative-option    | 0.1.0        |
| representable         | 3.0.4        |
| httpclient            | 2.8.3        |
| google-api-client     | 0.23.9       |
| digest-crc            | 0.4.1        |
| google-cloud-storage  | 1.16.0       |
| tty-spinner           | 0.9.0        |
| tty-cursor            | 0.6.1        |
| tty-screen            | 0.6.5        |
| faraday               | 0.15.4       |
| json                  | 2.2.0        |
| highline              | 1.7.10       |
| io-console            | 0.4.5        |
| excon                 | 0.62.0       |
| CFPropertyList        | 3.0.0        |
| mini_portile2         | 2.1.0        |
| nokogiri              | 1.6.8.1      |
| memoist               | 0.16.0       |
| googleauth            | 0.6.7        |
| signet                | 0.11.0       |
| unf                   | 0.1.4        |
| domain_name           | 0.5.20180417 |
| faraday_middleware    | 0.13.1       |
| fastimage             | 2.1.5        |
| bundler               | 2.0.1        |
| terminal-table        | 1.8.0        |
| unicode-display_width | 1.5.0        |
| addressable           | 2.6.0        |
| retriable             | 3.1.2        |
| mime-types            | 3.2.2        |
| mime-types-data       | 3.2018.0812  |
| multi_json            | 1.13.1       |
| jwt                   | 2.1.0        |
| os                    | 1.0.0        |
| psych                 | 3.1.0        |
| uber                  | 0.1.0        |
</details>

[11:59:34]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
/Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/highline-1.7.10/lib/highline.rb:730:in `gsub': [!] invalid byte sequence in US-ASCII (ArgumentError)
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/highline-1.7.10/lib/highline.rb:730:in `format_statement'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/highline-1.7.10/lib/highline.rb:621:in `say'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/highline-1.7.10/lib/highline.rb:261:in `ask'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/highline-1.7.10/lib/highline.rb:227:in `agree'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.118.1/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:134:in `confirm'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.118.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.118.1/fastlane/lib/fastlane/environment_printer.rb:13:in `output'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.118.1/fastlane/lib/fastlane/commands_generator.rb:263:in `block (2 levels) in run'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.118.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.118.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.118.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.118.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.118.1/bin/fastlane:23:in `<top (required)>'
        from /Users/admin/.rbenv/versions/2.3.1/bin/fastlane:23:in `load'
        from /Users/admin/.rbenv/versions/2.3.1/bin/fastlane:23:in `<main>'

[fastlane.log](https://github.com/fastlane/fastlane/files/3694552/fastlane.log)

**Comment by janpio** [comment]
Please fill the issue template instead of just deleting it. We need all the information asked for in there so we can properly debug any problems.

**Comment by basilfarraj** [comment]
Updated fastlane env. Thanks !
