### ISSUE TITLE
[setup_ci] setup_keychain should be called with all CI providers

### ISSUE THREAD

**Issue by tlvenn** [fastlane/fastlane#15445]
### Problem:

I am running fastlane (2.131.0) with Github Actions and while the CI is properly detected, nothing is happening. When a different provider than `travis` or `circleci` is given, the action results in a noop.

### Expected:

If a CI is detected, setup_keychain should be called in all cases and only after, depending of the provider, more tasks could be executed with a `case/when statement`.

**Comment by janpio** [comment]
Ping @mollyIV

**Comment by svenmuennich** [comment]
I just opened PR #15542 that changes `setup_ci` as proposed above.

**Comment by mollyIV** [comment]
Hello 👋 

We cannot possible provide a support for every CI provider out of the box. We have dedicated lanes for Travis (`setup_travis`), CircleCI (`setup_circle_ci`) and Jenkins (`setup_jenkins`).

> I am running fastlane (2.131.0) with Github Actions and while the CI is properly detected, nothing is happening.

@tlvenn could you please provide more details: 
* what fastlane lanes you are running (including `fastlane env` would be helpful)
* what is the expected result

> If a CI is detected, setup_keychain should be called in all cases

@tlvenn could you please explain why would we want that? 🤔 Are we sure that creating a temp keychain on some CI providers would not break stuff?

**Comment by tlvenn** [comment]
Hi @mollyIV,
 
I am using match and my understanding and experience with it is that for it to work, you definitely need a keychain that simply does not exist at all in most CI.

Right now this action simply does nothing at all if you are not specifying `travis` or `circle_ci` as a provider. I understand it was factored out of the `setup_travis` & `setup_circle_ci` actions but there is no reason it could not be used without it.

> https://github.com/fastlane/fastlane/blob/d27dd65f975c067fa4e91df4d283e68c5ab2a949/fastlane/lib/fastlane/actions/setup_ci.rb#L10-L16

The whole purpose of this action is to setup a temp keychain and force match in readonly which is clearly communicated in the documentation so I believe the expectation are pretty clear.

If for some reason your CI is already providing a keychain, you should simply not use this action.

I really don't see any harm in making sure it calls `setup_keychain` in all cases. Am i missing something here ?

**Comment by tlvenn** [comment]
And as far as I can tell, only `setup_travis` and `setup_circle_ci` are actually calling `setup_ci`
>https://github.com/fastlane/fastlane/search?q=setup_ci&unscoped_q=setup_ci

So the integration for jenkins with `setup_jenkins` which provides a keychain already does not call `setup_ci` at all.

**Comment by svenmuennich** [comment]
Since #15542 is still pending we should probably keep this issue open.

**Comment by vascofg** [comment]
Guess it can be closed now
