### ISSUE TITLE
No authentication parameters where specified (Google)

### ISSUE THREAD

**Issue by viktor-morin** [fastlane/fastlane#15457]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I following following guide:
https://docs.fastlane.tools/getting-started/android/setup/#collect-your-google-credentials

After downloaded the JSON file, fixed the path I write 

> fastlane supply init

I then get the error message:

> No authentication parameters were specified. These must be provided in otder to authenticate with Google

I have just followed the steps, so I'm a missing something or whats wrong here?
I'm trying to setup a flow for both Android and Apple, so my app isn't published yet.

##### Command executed

> fastlane supply init

##### Complete output when running fastlane, including the stack trace and command used

```
fastlane supply init

[✔]
[17:15:33] Download metadata, images, screenshots...

[!] No authentication parameters were specified. These must be provided in otder to authenticate with Google
```

### Environment

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.17.3       |
| etc                       | 1.0.1        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.1        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.67.0       |
| faraday                   | 0.15.4       |
| faraday_middleware        | 0.13.1       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.0904  |
| mime-types                | 3.3          |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| json                      | 2.2.0        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |

**Comment by viktor-morin** [comment]
> It seems like you have not included the output of `fastlane env`
> To make it easier for us help you resolve this issue, please update the issue to include the output of `fastlane env` 👍

It's included :)

**Comment by janpio** [comment]
No it's not, this is just a small part of the actual output.

Do you maybe get more output when you use `--verbose` at the end of the command?




> fixed the path I write

What do you mean by that?

**Comment by viktor-morin** [comment]
> No it's not, this is just a small part of the actual output.
> 
> Do you maybe get more output when you use `--verbose` at the end of the command?
> 
> > fixed the path I write
> 
> What do you mean by that?

Sorry, I meant that the path to the JSON file is correct.
See verbose prints below

> flutter supply init --verbose

INFO [2019-10-09 22:16:00.72]: 🕗  Downloading metadata, images, screenshots...

Traceback (most recent call last):

19: from /Users/viktormorin/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'

18: from /Users/viktormorin/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'

17: from /Users/viktormorin/.rvm/rubies/ruby-2.6.3/bin/fastlane:23:in `<main>'

16: from /Users/viktormorin/.rvm/rubies/ruby-2.6.3/bin/fastlane:23:in `load'

15: from /Users/viktormorin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.133.0/bin/fastlane:23:in `<top (required)>'

14: from /Users/viktormorin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'

13: from /Users/viktormorin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.133.0/supply/lib/supply/commands_generator.rb:12:in `start'

12: from /Users/viktormorin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.133.0/supply/lib/supply/commands_generator.rb:59:in `run'

11: from /Users/viktormorin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'

10: from /Users/viktormorin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.133.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'

9: from /Users/viktormorin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'

8: from /Users/viktormorin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'

7: from /Users/viktormorin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'

6: from /Users/viktormorin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.133.0/supply/lib/supply/commands_generator.rb:53:in `block (2 levels) in run'

5: from /Users/viktormorin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.133.0/supply/lib/supply/setup.rb:11:in `perform_download'

4: from /Users/viktormorin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.133.0/supply/lib/supply/setup.rb:109:in `client'

3: from /Users/viktormorin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.133.0/supply/lib/supply/client.rb:17:in `make_from_config'

2: from /Users/viktormorin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.133.0/supply/lib/supply/client.rb:126:in `service_account_authentication'

1: from /Users/viktormorin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.133.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'

/Users/viktormorin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.133.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': No authentication parameters were specified. These must be provided in order to authenticate with Google (FastlaneCore::Interface::FastlaneError)

19: from /Users/viktormorin/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'

18: from /Users/viktormorin/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'

17: from /Users/viktormorin/.rvm/rubies/ruby-2.6.3/bin/fastlane:23:in `<main>'

16: from /Users/viktormorin/.rvm/rubies/ruby-2.6.3/bin/fastlane:23:in `load'

15: from /Users/viktormorin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.133.0/bin/fastlane:23:in `<top (required)>'

14: from /Users/viktormorin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'

13: from /Users/viktormorin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.133.0/supply/lib/supply/commands_generator.rb:12:in `start'

12: from /Users/viktormorin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.133.0/supply/lib/supply/commands_generator.rb:59:in `run'

11: from /Users/viktormorin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'

10: from /Users/viktormorin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.133.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'

9: from /Users/viktormorin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'

8: from /Users/viktormorin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'

7: from /Users/viktormorin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'

6: from /Users/viktormorin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.133.0/supply/lib/supply/commands_generator.rb:53:in `block (2 levels) in run'

5: from /Users/viktormorin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.133.0/supply/lib/supply/setup.rb:11:in `perform_download'

4: from /Users/viktormorin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.133.0/supply/lib/supply/setup.rb:109:in `client'

3: from /Users/viktormorin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.133.0/supply/lib/supply/client.rb:17:in `make_from_config'

2: from /Users/viktormorin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.133.0/supply/lib/supply/client.rb:126:in `service_account_authentication'

1: from /Users/viktormorin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.133.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'

/Users/viktormorin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.133.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] No authentication parameters were specified. These must be provided in order to authenticate with Google (FastlaneCore::Interface::FastlaneError)

> fastlane env --verbose

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0 (Apple Git-122)          |
| Installation Source         | ~/.rvm/rubies/ruby-2.6.3/bin/fastlane       |
| Host                        | Mac OS X 10.14.6 (18G103)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.3/lib                |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.0                                        |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.133.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.17.3       |
| etc                       | 1.0.1        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.1        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.67.0       |
| faraday                   | 0.15.4       |
| faraday_middleware        | 0.13.1       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.0904  |
| mime-types                | 3.3          |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| json                      | 2.2.0        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>


*generated on:* **2019-10-09**
</details>

**Comment by viktor-morin** [comment]
> execute "fastlane supply init" inside android directory not in project folder

Thanks, stupid of me... solved the issue :)
