### ISSUE TITLE
faslane supply command to download store listing

### ISSUE THREAD

**Issue by vanniktech** [fastlane/fastlane#15451]
During the set up phase of `fastlane supply init` I can download the entire store listing.

It would be super nice to trigger this. For instance: `fastlane supply --download-store-listing`.

My use case is that every now and then my PO does change something and before creating a release, I want to download the store listing and make sure that nothing gets overridden.

**Comment by janpio** [comment]
How do you suggest it should handle existing local data?

**Comment by vanniktech** [comment]
I'd assume to just overwrite it. You can get the history from Git.

**Comment by vanniktech** [comment]
Still an issue.

**Comment by vanniktech** [comment]
Yo still an issue

**Comment by vanniktech** [comment]
Yeah an issue

**Comment by vanniktech** [comment]
I've given up on fastlane supply. Feel free to close this issue.
