### ISSUE TITLE
Firebase distribution using Fastlane

### ISSUE THREAD

**Issue by golanshy** [fastlane/fastlane#15458]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I implemented the CI using Firebase App Distribution & Fastlane on GitLab CI/CD and I get the following error which I don’t understand why and I was wondering if you can assist me:

```
Error: unsupported distribution file format, should be .ipa or .apk
```

From the output of this line sh("ls -l #{apk_path}”) you can see that the apk file exists in the right path so I don’t understand the error.

The problem only occur when the script is run on Gitlab CI, when running on my local machine it doesn't fail

##### Command executed

```
def uploadToFirebaseAppDistribution(appId, apk_path, slackMessage)

  UI.message("uploadToFirebaseAppDistribution: #{apk_path}")
  sh("ls -l #{apk_path}")

  firebase_app_distribution(
              app: appId,
              apk_path: "#{apk_path}",
              groups: "openpayd-mobile-testers",
              release_notes: changelog_from_git_commits(commits_count: 1)
  )
  slackIt(slackMessage)
  return true
end
```

##### Complete output when running fastlane, including the stack trace and command used

```
[15:07:11]: uploadToFirebaseAppDistribution: /builds/ozan/mobile/openpayd-android/app/build/outputs/apk/openPaydDev/debug/OpenPaydAndroid.apk
[15:07:11]: --------------------------------------------------------------------
[15:07:11]: Step: ls -l /builds/ozan/mobile/openpayd-android/app/build/outputs/apk/openPaydDev/debug/OpenPaydAndroid.apk
[15:07:11]: --------------------------------------------------------------------
[15:07:11]: $ ls -l /builds/ozan/mobile/openpayd-android/app/build/outputs/apk/openPaydDev/debug/OpenPaydAndroid.apk
[15:07:11]: ▸ -rw-r--r-- 1 root root 10766858 Oct  8 15:07 /builds/ozan/mobile/openpayd-android/app/build/outputs/apk/openPaydDev/debug/OpenPaydAndroid.apk
[15:07:11]: ----------------------------------------
[15:07:11]: --- Step: changelog_from_git_commits ---
[15:07:11]: ----------------------------------------
[15:07:11]: Collecting the last 1 Git commits

no message

[15:07:11]: ---------------------------------------
[15:07:11]: --- Step: firebase_app_distribution ---
[15:07:11]: ---------------------------------------
[15:07:13]: ▸ Error: unsupported distribution file format, should be .ipa or .apk
+-------------------------------------+------------------------------------------------------------------------------------------------------+
|                                                                Lane Context                                                                |
+-------------------------------------+------------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM                    | android                                                                                              |
| PLATFORM_NAME                       | android                                                                                              |
| LANE_NAME                           | android deploy_lane                                                                                  |
| GRADLE_BUILD_TYPE                   | Debug                                                                                                |
| GRADLE_FLAVOR                       | openPaydDev                                                                                          |
| GRADLE_ALL_APK_OUTPUT_PATHS         | ["/builds/ozan/mobile/openpayd-android/app/build/outputs/apk/openPaydDev/debug/OpenPaydAndroid.apk"] |
| GRADLE_ALL_AAB_OUTPUT_PATHS         | []                                                                                                   |
| GRADLE_ALL_OUTPUT_JSON_OUTPUT_PATHS | ["/builds/ozan/mobile/openpayd-android/app/build/outputs/apk/openPaydDev/debug/output.json"]         |
| GRADLE_APK_OUTPUT_PATH              | /builds/ozan/mobile/openpayd-android/app/build/outputs/apk/openPaydDev/debug/OpenPaydAndroid.apk     |
| GRADLE_OUTPUT_JSON_OUTPUT_PATH      | /builds/ozan/mobile/openpayd-android/app/build/outputs/apk/openPaydDev/debug/output.json             |
| FL_CHANGELOG                        | no message                                                                                           |
+-------------------------------------+------------------------------------------------------------------------------------------------------+
[15:07:14]: Shell command exited with exit status 1 instead of 0.

Error: unsupported distribution file format, should be .ipa or .apk


+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | Verifying fastlane version                                    | 0           |
| 2    | default_platform                                              | 0           |
| 3    | git_branch                                                    | 0           |
| 4    | git_branch                                                    | 0           |
| 5    | git_branch                                                    | 0           |
| 6    | gradle                                                        | 132         |
| 7    | git_branch                                                    | 0           |
| 8    | ls -l /builds/ozan/mobile/openpayd-android/app/build/outputs/ | 0           |
| 9    | changelog_from_git_commits                                    | 0           |
| 💥   | firebase_app_distribution                                     | 2           |
+------+---------------------------------------------------------------+-------------+

[15:07:14]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Execution fails on fastlane-0.1.14
    https://github.com/fastlane/fastlane/issues/79 [closed] 5 💬
    22 Sep 2016

➡️  Documentation - ipa vs. ipa (shenzhen)?
    https://github.com/fastlane/fastlane/issues/72 [closed] 2 💬
    22 Sep 2016

➡️  Extension Support
    https://github.com/fastlane/fastlane/issues/76 [closed] 6 💬
    11 Dec 2016

and 15342 more at: https://github.com/fastlane/fastlane/search?q=Shell%20command%20exited%20with%20exit%20status%201%20instead%20of%200.%0A%0A%1B%5B1m%1B%5B31mError%3A%1B%5B39m%1B%5B22m%20unsupported%20distribution%20file%20format%2C%20should%20be%20.ipa%20or%20.apk%0A&type=Issues&utf8=✓

/builds/ozan/mobile/openpayd-android/vendor/ruby/2.3.0/gems/fastlane-2.133.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': [!] Shell command exited with exit status 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)

Error: unsupported distribution file format, should be .ipa or .apk

	from /builds/ozan/mobile/openpayd-android/vendor/ruby/2.3.0/gems/fastlane-2.133.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /builds/ozan/mobile/openpayd-android/vendor/ruby/2.3.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	from /builds/ozan/mobile/openpayd-android/vendor/ruby/2.3.0/gems/fastlane-plugin-firebase_app_distribution-0.1.2/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb:28:in `run'
	from /builds/ozan/mobile/openpayd-android/vendor/ruby/2.3.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
	from /builds/ozan/mobile/openpayd-android/vendor/ruby/2.3.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /builds/ozan/mobile/openpayd-android/vendor/ruby/2.3.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
	from /builds/ozan/mobile/openpayd-android/vendor/ruby/2.3.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /builds/ozan/mobile/openpayd-android/vendor/ruby/2.3.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /builds/ozan/mobile/openpayd-android/vendor/ruby/2.3.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /builds/ozan/mobile/openpayd-android/vendor/ruby/2.3.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:135:in `uploadToFirebaseAppDistribution'
	from Fastfile:50:in `block (2 levels) in parsing_binding'
	from /builds/ozan/mobile/openpayd-android/vendor/ruby/2.3.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /builds/ozan/mobile/openpayd-android/vendor/ruby/2.3.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /builds/ozan/mobile/openpayd-android/vendor/ruby/2.3.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /builds/ozan/mobile/openpayd-android/vendor/ruby/2.3.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /builds/ozan/mobile/openpayd-android/vendor/ruby/2.3.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /builds/ozan/mobile/openpayd-android/vendor/ruby/2.3.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /builds/ozan/mobile/openpayd-android/vendor/ruby/2.3.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /builds/ozan/mobile/openpayd-android/vendor/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /builds/ozan/mobile/openpayd-android/vendor/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /builds/ozan/mobile/openpayd-android/vendor/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /builds/ozan/mobile/openpayd-android/vendor/ruby/2.3.0/gems/fastlane-2.133.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /builds/ozan/mobile/openpayd-android/vendor/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /builds/ozan/mobile/openpayd-android/vendor/ruby/2.3.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	from /builds/ozan/mobile/openpayd-android/vendor/ruby/2.3.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /builds/ozan/mobile/openpayd-android/vendor/ruby/2.3.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /builds/ozan/mobile/openpayd-android/vendor/ruby/2.3.0/gems/fastlane-2.133.0/bin/fastlane:23:in `<top (required)>'
	from /builds/ozan/mobile/openpayd-android/vendor/ruby/2.3.0/bin/fastlane:22:in `load'
	from /builds/ozan/mobile/openpayd-android/vendor/ruby/2.3.0/bin/fastlane:22:in `<main>'
ERROR: Job failed: command terminated with exit code 1
```

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.133.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.1.2   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| io-console                                | 0.4.5        |
| CFPropertyList                            | 3.0.1        |
| public_suffix                             | 2.0.5        |
| addressable                               | 2.7.0        |
| atomos                                    | 0.1.3        |
| babosa                                    | 1.0.3        |
| bundler                                   | 2.0.2        |
| claide                                    | 1.0.3        |
| colored                                   | 1.2          |
| colored2                                  | 3.1.2        |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| declarative                               | 0.0.10       |
| declarative-option                        | 0.1.0        |
| digest-crc                                | 0.4.1        |
| unf_ext                                   | 0.0.7.6      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| dotenv                                    | 2.7.5        |
| emoji_regex                               | 1.0.1        |
| excon                                     | 0.67.0       |
| multipart-post                            | 2.0.0        |
| faraday                                   | 0.15.4       |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.6        |
| faraday_middleware                        | 0.13.1       |
| fastimage                                 | 2.1.7        |
| gh_inspector                              | 1.1.3        |
| jwt                                       | 2.1.0        |
| memoist                                   | 0.16.0       |
| multi_json                                | 1.13.1       |
| os                                        | 1.0.1        |
| signet                                    | 0.11.0       |
| googleauth                                | 0.6.7        |
| httpclient                                | 2.8.3        |
| mime-types-data                           | 3.2019.0904  |
| mime-types                                | 3.3          |
| uber                                      | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| google-api-client                         | 0.23.9       |
| google-cloud-env                          | 1.2.1        |
| google-cloud-core                         | 1.3.1        |
| google-cloud-storage                      | 1.16.0       |
| json                                      | 2.2.0        |
| mini_magick                               | 4.9.5        |
| multi_xml                                 | 0.6.0        |
| plist                                     | 3.5.0        |
| rubyzip                                   | 1.3.0        |
| security                                  | 0.1.3        |
| naturally                                 | 2.2.0        |
| simctl                                    | 1.6.6        |
| slack-notifier                            | 2.3.2        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.6.0        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.7.0        |
| tty-cursor                                | 0.7.0        |
| tty-spinner                               | 0.9.1        |
| word_wrap                                 | 1.0.0        |
| nanaimo                                   | 0.2.6        |
| xcodeproj                                 | 1.12.0       |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.0        |
| fastlane-plugin-firebase_app_distribution | 0.1.2        |
</details>

*generated on:* **2019-10-08**
</details>
[15:56:34]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[15:56:34]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅
$ bundle exec fastlane add_plugin firebase_app_distribution
+-------------------------------------------+---------+---------------------------+
|                                  Used plugins                                   |
+-------------------------------------------+---------+---------------------------+
| Plugin                                    | Version | Action                    |
+-------------------------------------------+---------+---------------------------+
| fastlane-plugin-firebase_app_distribution | 0.1.2   | firebase_app_distribution |
+-------------------------------------------+---------+---------------------------+

[15:56:36]: Make sure to commit your Gemfile, Gemfile.lock and Pluginfile to version control
Installing plugin dependencies...
Successfully installed plugins
$ bundle exec fastlane android deploy_lane appId:"${OpenPaydDev_APP_ID}"
+-------------------------------------------+---------+---------------------------+
|                                  Used plugins                                   |
+-------------------------------------------+---------+---------------------------+
| Plugin                                    | Version | Action                    |
+-------------------------------------------+---------+---------------------------+
| fastlane-plugin-firebase_app_distribution | 0.1.2   | firebase_app_distribution |
+-------------------------------------------+---------+---------------------------+

<details>
  <pre> Golan Shay golanshy@gmail.com </pre>
</details>

**Comment by janpio** [comment]
You should probably ask in the repository of the plugin you are using: https://github.com/fastlane-community/fastlane-plugin-firebase_app_distribution

**Comment by claudioviola** [comment]
Hey @golanshy 

How do you manage the the authentication with firebase?

When I run this command from shell
`fastlane run firebase_app_distribution app:y_app_id apk_path:./app/build/outputs/apk/release/app-release.apk`

I've been facing this error
`Error: failed to fetch app information. HTTP Error: 403, The caller does not have permission`

First I run this
`export GOOGLE_APPLICATION_CREDENTIALS=/Users/my/..../android/secure/firebase-service-account-key.json`

I follow this guide to create json key
https://firebase.google.com/docs/app-distribution/authenticate-service-account.md?platform=android

Can you help me?
