### ISSUE TITLE
macOS Catalina bad interpreter: No such file or directory 

### ISSUE THREAD

**Issue by duanhjlt** [fastlane/fastlane#15460]
I installed Catalina, but i got error when i run fastlane.

```
$ fastlane --version

-bash: /usr/local/bin/fastlane: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby: bad interpreter: No such file or directory
```

**Comment by jcharr1** [comment]
I had this issue after upgrading to Catalina with several gems. What I had to do is uninstall all my user gems, delete the contents of my user gems directory, and then reinstall the gems. The key was that it wasn't enough to just uninstall them through gem. I had to manually delete the directory contents too.

**Comment by T-Jedsada** [comment]
me too please

**Comment by alindaj6** [comment]
@jcharr1 can you tell me what are you doing in detail to make the fastlane working again?
i am really stuck now

**Comment by jcharr1** [comment]
@alindaj6 how did you install fastlane? Directly with `gem` or with `brew`?

**Comment by jcharr1** [comment]
For example, I have my GEM_HOME setup to be in my user folder (~/.gem) so I can install gems without using `sudo`. So in my case, what I did was:

1) run `gem uninstall -aIx`. This should uninstall all your installed gems and their binaries. Though this doesn't seem to completely get rid of them.
2) So next I went into my gem install directory and deleted the contents of it. For me this is `~/.gem`. If you don't know where your gem install directory is, you can find it by running `gem env` and looking at the Installation Directory near the top of the output.
3) Then I reinstalled the gems I needed with `gem install fastlane bundler cocoapods`. After reinstalling, fastlane and cocoapods stopped throwing bad interpreter error.

**Comment by alindaj6** [comment]
this is my gem env
`/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19/rbconfig.rb:229: warning: Insecure world writable dir /Users/anggasetiawan/Documents/Work in PATH, mode 040777
RubyGems Environment:
  - RUBYGEMS VERSION: 3.0.6
  - RUBY VERSION: 2.6.3 (2019-04-16 patchlevel 62) [universal.x86_64-darwin19]
  - INSTALLATION DIRECTORY: /Library/Ruby/Gems/2.6.0
  - USER INSTALLATION DIRECTORY: /Users/anggasetiawan/.gem/ruby/2.6.0
  - RUBY EXECUTABLE: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
  - GIT EXECUTABLE: /usr/local/bin/git
  - EXECUTABLE DIRECTORY: /usr/bin
  - SPEC CACHE DIRECTORY: /Users/anggasetiawan/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Library/Ruby/Site
  - RUBYGEMS PLATFORMS:
    - ruby
    - universal-darwin-19
  - GEM PATHS:
     - /Library/Ruby/Gems/2.6.0
     - /Users/anggasetiawan/.gem/ruby/2.6.0
     - /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/anggasetiawan/.rbenv/shims
     - /Users/anggasetiawan/.rbenv/bin
     - /Users/anggasetiawan/.asdf/shims
     - /Users/anggasetiawan/.asdf/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Library/Apple/usr/bin
     - /Library/Apple/bin
     - /opt/X11/bin
     - /Library/Frameworks/Mono.framework/Versions/Current/Commands
     - /Applications/Wireshark.app/Contents/MacOS
     - /Users/anggasetiawan/.rbenv/bin
     - /Users/anggasetiawan/flutter/bin
     - $HOME/.fastlane/bin
     - $PATH
     - $HOME/.gem/bin
     - $PATH
     - /usr/local/sbin
     - $PATH
     - /usr/local/sbin
     - $PATH
     - /usr/local/opt/ruby/bin
     - $PATH
     - /Users/anggasetiawan/.composer/vendor/bin`

**Comment by alindaj6** [comment]
and this is what happen when i do `gem uninstall -aIx`
`gem uninstall -aIx                                                        
ERROR:  While executing gem ... (Gem::InstallError)
    CFPropertyList is not installed in GEM_HOME, try:
	gem uninstall -i /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0 CFPropertyList`

**Comment by jcharr1** [comment]
@alindaj6 it looks like you installed fastlane through Homebrew. Is that correct? If so, try reinstalling fastlane with `brew reinstall fastlane`, and see if that helps.

**Comment by duanhjlt** [comment]
[#15183](https://github.com/fastlane/fastlane/issues/15183#issuecomment-526746222)

I got it working now.

**Comment by alindaj6** [comment]
@jcharr1 it is working now, like @duanhjlt said i change the `Command Line Tools` to use the Xcode 11, before i use the 10.3.
thanks @jcharr1

**Comment by dipendra-sharma** [comment]
I solved it with commands as mentioned.

`gem unistall fastlane`
`sudo gem install fastlane -NV -n /usr/local/bin`

**Comment by nurianmo** [comment]
I solved it using:
```
brew cask uninstall fastlane
brew cask install fastlane
```

and adding:
```
export PATH="$HOME/.fastlane/bin:$PATH" 
```
to my ~/.zshrc  and tehn restart the terminal

**Comment by fortydegrees** [comment]
> I solved it using:
> 
> ```
> brew cask uninstall fastlane
> brew cask install fastlane
> ```
> 
> and adding:
> 
> ```
> export PATH="$HOME/.fastlane/bin:$PATH" 
> ```
> 
> to my ~/.zshrc and then restart the terminal

tried a lot of things like reinstalling ruby and cocoapods and xcode etc and this is simply the thing that worked, for anyone else discovering this issue

**Comment by Grappetite-tauqeer** [comment]
Just gem uninstall -aIx then gem install fastlane bundler cocoapods worked for me. Thank you guys

**Comment by gurjindersinghkhalsa** [comment]
Run the below command 
gurjindersingh$ sudo gem install -n /usr/local/bin cocoapods 
Now set the command line tools under locations in Xcode prefrence.

**Comment by douira** [comment]
> 2. So next I went into my gem install directory and deleted the contents of it. 
What @jcharr1 posted was the only thing that fixed it for me. All the other reinstalling and other stuff didn't work!

**Comment by abilashsuresan** [comment]
> For example, I have my GEM_HOME setup to be in my user folder (~/.gem) so I can install gems without using `sudo`. So in my case, what I did was:
> 
> 1. run `gem uninstall -aIx`. This should uninstall all your installed gems and their binaries. Though this doesn't seem to completely get rid of them and it didn't fix the error for me after reinstalling.
> 2. So next I went into my gem install directory and deleted the contents of it. For me this is `~/.gem`. If you don't know where your gem install directory is, you can find it by running `gem env` and looking at the Installation Directory near the top of the output.
> 3. Then I reinstalled the gems I needed with `gem install fastlane bundler cocoapods`. After reinstalling, fastlane and cocoapods stopped throwing bad interpreter error.

Thanks, 
This helped me.
I need to do `bundle install` also to work after step 3.

**Comment by shuvaramva** [comment]
> For example, I have my GEM_HOME setup to be in my user folder (~/.gem) so I can install gems without using `sudo`. So in my case, what I did was:
> 
> 1. run `gem uninstall -aIx`. This should uninstall all your installed gems and their binaries. Though this doesn't seem to completely get rid of them and it didn't fix the error for me after reinstalling.
> 2. So next I went into my gem install directory and deleted the contents of it. For me this is `~/.gem`. If you don't know where your gem install directory is, you can find it by running `gem env` and looking at the Installation Directory near the top of the output.
> 3. Then I reinstalled the gems I needed with `gem install fastlane bundler cocoapods`. After reinstalling, fastlane and cocoapods stopped throwing bad interpreter error.

One more update on this for me, that i had to do.
Step #3: I had to do sudo gem install fastlane bundler cocoapods, as there were some file that needed permission.

Thanks,

**Comment by Balake** [comment]
FYI, using the latest fastlane gem (2.141.0), gitlab ci jobs get stuck at the end. See [here](https://github.com/fastlane/fastlane/issues/15955)

**Comment by nahttoter** [comment]
Hi all,
I have similiar issue with Catalina once try to call _fastlane init_

_ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]_

_fastlane env
-bash: /usr/local/bin/fastlane: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby: bad interpreter: No such file or directory_

So it seems like fastlane tries to use older version of ruby 2.3 rather my files at  /System/Library/Frameworks/Ruby.framework/Versions/2.3/
How can I properly change the visible path?

**Comment by cristianbanarescu** [comment]
> For example, I have my GEM_HOME setup to be in my user folder (~/.gem) so I can install gems without using `sudo`. So in my case, what I did was:
> 
> 1. run `gem uninstall -aIx`. This should uninstall all your installed gems and their binaries. Though this doesn't seem to completely get rid of them and it didn't fix the error for me after reinstalling.
> 2. So next I went into my gem install directory and deleted the contents of it. For me this is `~/.gem`. If you don't know where your gem install directory is, you can find it by running `gem env` and looking at the Installation Directory near the top of the output.
> 3. Then I reinstalled the gems I needed with `gem install fastlane bundler cocoapods`. After reinstalling, fastlane and cocoapods stopped throwing bad interpreter error.

Thanks man! It really helped me!!
