### ISSUE TITLE
[Spaceship] PortalClient uses wrong team_id to request devices list for creating provisioning profile

### ISSUE THREAD

**Issue by Antol** [fastlane/fastlane#15461]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I have 2 targets in the app with 2 different bundle ids in different teams. I manage Certs and Provisioning Profiles via fastlane match. 
I have a lane that automatically goes through all targets and configurations and tries to generate all needed certs and provs. It works OK for the first target and generated all artifacts correctly but for the second target it fails with error:    
    
    [!] Apple provided the following error info:
     	There were errors in the data supplied. Please correct and re-submit.
     	There are no current IOS devices on this team matching the provided device IDs.

After some digging in the sources, I found that this function in `portal_client.rb` uses incorrect team_id (I've added line `puts "T:#{team_id}"` there for clarity):

    def devices(mac: false, include_disabled: false)
      paging do |page_number|
        puts "T:#{team_id}"
        r = request(:post, "account/#{platform_slug(mac)}/device/listDevices.action", {
          teamId: team_id,
          pageNumber: page_number,
          pageSize: page_size,
          sort: 'name=asc',
          includeRemovedDevices: include_disabled
        })

        result = parse_response(r, 'devices')
        csrf_cache[Spaceship::Portal::Device] = self.csrf_tokens

        result
      end
    end

It seems like PortalClient sets its `@current_team_id` on the first run for the first target and uses it despite of explicit parameter in match call

##### Command executed

This code is a simplified example, but it replicates the problem:    
    
    lane :imitate_problem do 
      sync_code_signing(
        username: "taras@gmail.com",
        app_identifier: "com.xcart", 
        team_id: "CDVQN43CH",
        git_branch: "CDVQN43CH",
        type: "adhoc",
        readonly: false, 
        force: false,
        force_for_new_devices: true
      )

      sync_code_signing(
        username: "antol@gmail.com",
        app_identifier: "com.xcartstore", 
        team_id: "7M9PEFJ8Z",
        git_branch: "7M9PEFJ8Z",
        type: "adhoc",
        readonly: false, 
        force: false,
        force_for_new_devices: true
      )
    end

sync_code_signing is an official alias for match. 
As you can see I have explicit parameter `team_id`

##### Complete output when running fastlane, including the stack trace and command used

	➜  store-ios git:(67-prepare-for-xcart-app-store) bundle exec fastlane imitate_problem
	[✔] 🚀
	[17:50:51]: ----------------------------------------
	[17:50:51]: --- Step: Verifying fastlane version ---
	[17:50:51]: ----------------------------------------
	[17:50:51]: Your fastlane version 2.133.0 matches the minimum requirement of 2.128.0  ✅
	[17:50:54]: ------------------------------
	[17:50:54]: --- Step: default_platform ---
	[17:50:54]: ------------------------------
	[17:50:54]: Driving the lane 'ios imitate_problem' 🚀
	[17:50:54]: -------------------------------
	[17:50:54]: --- Step: sync_code_signing ---
	[17:50:54]: -------------------------------

	+----------------------------+----------------------------------------------+
	|                         Summary for match 2.133.0                         |
	+----------------------------+----------------------------------------------+
	| username                   | taras@gmail.com                              |
	| app_identifier             | ["com.xcart"]                                |
	| team_id                    | CDVQN43CH                                    |
	| git_branch                 | CDVQN43CH                                    |
	| type                       | adhoc                                        |
	| readonly                   | false                                        |
	| force                      | false                                        |
	| force_for_new_devices      | true                                         |
	| generate_apple_certs       | true                                         |
	| skip_provisioning_profiles | false                                        |
	| storage_mode               | git                                          |
	| git_url                    | git@gitlabstore/store-ios.git                |
	| shallow_clone              | true                                         |
	| clone_branch_directly      | true                                         |
	| keychain_name              | login.keychain                               |
	| skip_confirmation          | false                                        |
	| skip_docs                  | false                                        |
	| platform                   | ios                                          |
	| verbose                    | false                                        |
	+----------------------------+----------------------------------------------+

	[17:50:54]: Cloning remote git repo...
	[17:50:59]: Checking out branch CDVQN43CH...
	[17:50:59]: 🔓  Successfully decrypted certificates repo
	[17:50:59]: Verifying that the certificate and profile are still valid on the Dev Portal...
	[17:51:03]: Installing certificate...

	+-------------------+---------------------------------------------------+
	|                         Installed Certificate                         |
	+-------------------+---------------------------------------------------+
	| User ID           | CDVQN43CH                                         |
	| Common Name       | iPhone Distribution: BREINS, OOO (CDVQN43CH)      |
	| Organisation Unit | CDVQN43CH                                         |
	| Organisation      | BREINS, OOO                                       |
	| Country           | US                                                |
	| Start Datetime    | 2019-08-23 12:33:52 UTC                           |
	| End Datetime      | 2020-08-22 12:33:52 UTC                           |
	+-------------------+---------------------------------------------------+

	T:CDVQN43CH
	[17:51:09]: Installing provisioning profile...

	+---------------------+-----------------------------------+--------------------------------------------------------------+
	|                                             Installed Provisioning Profile                                             |
	+---------------------+-----------------------------------+--------------------------------------------------------------+
	| Parameter           | Environment Variable              | Value                                                        |
	+---------------------+-----------------------------------+--------------------------------------------------------------+
	| App Identifier      |                                   | com.xcart                                                    |
	| Type                |                                   | adhoc                                                        |
	| Platform            |                                   | ios                                                          |
	| Profile UUID        | sigh_com.xcart_adhoc              | 581999b5-2adb-4e59-ac7a-..                                   |
	| Profile Name        | sigh_com.xcart_adhoc_profile-name | match AdHoc com.xcart                                        |
	| Profile Path        | sigh_com.xcart_adhoc_profile-path | /Users/antol/Library/MobileDevice/Provisioning               |
	|                     |                                   | Profiles/581999b5-2adb-4e59-ac7a-...mobileprovisi            |
	|                     |                                   | on                                                           |
	| Development Team ID | sigh_com.xcart_adhoc_team-id      | CDVQN43CH                                                    |
	+---------------------+-----------------------------------+--------------------------------------------------------------+

	[17:51:10]: All required keys, certificates and provisioning profiles are installed 🙌
	[17:51:10]: Setting Provisioning Profile type to 'ad-hoc'
	[17:51:10]: -------------------------------
	[17:51:10]: --- Step: sync_code_signing ---
	[17:51:10]: -------------------------------

	+----------------------------+----------------------------------------------+
	|                         Summary for match 2.133.0                         |
	+----------------------------+----------------------------------------------+
	| username                   | antol@gmail.com                              |
	| app_identifier             | ["com.xcartstore"]                           |
	| team_id                    | 7M9PEFJ8Z                                    |
	| git_branch                 | 7M9PEFJ8Z                                    |
	| type                       | adhoc                                        |
	| readonly                   | false                                        |
	| force                      | false                                        |
	| force_for_new_devices      | true                                         |
	| generate_apple_certs       | true                                         |
	| skip_provisioning_profiles | false                                        |
	| storage_mode               | git                                          |
	| git_url                    | git@gitlabstore/store-ios.git                |
	| shallow_clone              | true                                         |
	| clone_branch_directly      | true                                         |
	| keychain_name              | login.keychain                               |
	| skip_confirmation          | false                                        |
	| skip_docs                  | false                                        |
	| platform                   | ios                                          |
	| verbose                    | false                                        |
	+----------------------------+----------------------------------------------+

	[17:51:10]: Cloning remote git repo...
	[17:51:34]: Checking out branch 7M9PEFJ8Z...
	[17:51:34]: 🔓  Successfully decrypted certificates repo
	[17:51:34]: Verifying that the certificate and profile are still valid on the Dev Portal...
	Available session is not valid any more. Continuing with normal login.
	[17:51:38]: Installing certificate...
	[⠸] Setting key partition list... (this can take a minute if there are a lot of keys installed) [17:51:39]:
	[17:51:39]: Could not configure imported keychain item (certificate) to prevent UI permission popup when code signing
	Check if you supplied the correct `keychain_password` for keychain: `/Users/antol/Library/Keychains/login.keychain-db`
	security: SecKeychainItemSetAccessWithPassword: The user name or passphrase you entered is not correct.
	[17:51:39]:
	[17:51:39]: Please look at the following docs to see how to set a keychain password:
	[17:51:39]:  - https://docs.fastlane.tools/actions/sync_code_signing
	[17:51:39]:  - https://docs.fastlane.tools/actions/get_certificates
	[✔] Setting key partition list... (this can take a minute if there are a lot of keys installed)
	[⠙] Setting key partition list... (this can take a minute if there are a lot of keys installed) [17:51:40]:
	[17:51:40]: Could not configure imported keychain item (certificate) to prevent UI permission popup when code signing
	Check if you supplied the correct `keychain_password` for keychain: `/Users/antol/Library/Keychains/login.keychain-db`
	security: SecKeychainItemSetAccessWithPassword: The user name or passphrase you entered is not correct.
	[17:51:40]:
	[17:51:40]: Please look at the following docs to see how to set a keychain password:
	[17:51:40]:  - https://docs.fastlane.tools/actions/sync_code_signing
	[17:51:40]:  - https://docs.fastlane.tools/actions/get_certificates
	[✔] Setting key partition list... (this can take a minute if there are a lot of keys installed)

	+-------------------+-------------------------------------------------------------+
	|                              Installed Certificate                              |
	+-------------------+-------------------------------------------------------------+
	| User ID           | 7M9PEFJ8Z                                                   |
	| Common Name       | Apple Distribution: Software Limited (7M9PEFJ8Z )           |
	| Organisation Unit | 7M9PEFJ8Z                                                   |
	| Organisation      | Software Limited                                            |
	| Country           | CY                                                          |
	| Start Datetime    | 2019-10-09 12:58:39 UTC                                     |
	| End Datetime      | 2020-10-08 12:58:39 UTC                                     |
	+-------------------+-------------------------------------------------------------+

	+-------------------------------------+----------------------------+
	|                     Summary for sigh 2.133.0                     |
	+-------------------------------------+----------------------------+
	| app_identifier                      | com.xcartstore             |
	| username                            | antol@gmail.com            |
	| force                               | false                      |
	| cert_id                             | 5T7YQ6AN65                 |
	| provisioning_name                   | match AdHoc com.xcartstore |
	| ignore_profiles_with_different_name | true                       |
	| team_id                             | 7M9PEFJ8Z                  |
	| platform                            | ios                        |
	| adhoc                               | true                       |
	| developer_id                        | false                      |
	| development                         | false                      |
	| skip_install                        | false                      |
	| skip_fetch_profiles                 | false                      |
	| skip_certificate_verification       | false                      |
	| readonly                            | false                      |
	+-------------------------------------+----------------------------+

	[17:51:41]: Starting login with user 'antol@gmail.com'
	Available session is not valid any more. Continuing with normal login.
	[17:51:45]: Successfully logged in
	[17:51:45]: Fetching profiles...
	[17:51:46]: Verifying certificates...
	[17:51:46]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
	[17:51:50]: Creating new provisioning profile for 'com.xcartstore' with name 'match AdHoc com.xcartstore' for 'ios' platform
	T:CDVQN43CHN
	[17:51:52]: An error occurred while verifying your certificates and profiles with the Apple Developer Portal.
	[17:51:52]: If you already have your certificates stored in git, you can run `fastlane match` in readonly mode
	[17:51:52]: to just install the certificates and profiles without accessing the Dev Portal.
	[17:51:52]: To do so, just pass `readonly: true` to your match call.
	+------------------------------------+----------------------------------------+
	|                                Lane Context                                 |
	+------------------------------------+----------------------------------------+
	| DEFAULT_PLATFORM                   | ios                                    |
	| PLATFORM_NAME                      | ios                                    |
	| LANE_NAME                          | ios imitate_problem                    |
	| SIGH_PROFILE_TYPE                  | ad-hoc                                 |
	| MATCH_PROVISIONING_PROFILE_MAPPING | {"com.xcart"=>"match AdHoc com.xcart"} |
	+------------------------------------+----------------------------------------+
	[17:51:52]: {"responseId"=>"4735b26c-68e3-41a1-85d3-b3aa83e132d8", "resultCode"=>35, "resultString"=>"There were errors in the data supplied. Please correct and re-submit.", "userString"=>"There are no current IOS devices on this team matching the provided device IDs.", "creationTimestamp"=>"2019-10-09T13:51:52Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developer.apple.com/services-account/QH65B2/account/ios/profile/createProvisioningProfile.action", "httpCode"=>200, "validationMessages"=>[{"validationKey"=>"deviceIds", "validationUserMessage"=>"There are no current IOS devices on this team matching the provided device IDs."}]}

	+------+----------------------------+-------------+
	|                fastlane summary                 |
	+------+----------------------------+-------------+
	| Step | Action                     | Time (in s) |
	+------+----------------------------+-------------+
	| 1    | Verifying fastlane version | 0           |
	| 2    | Verifying fastlane version | 0           |
	| 3    | import_from_git            | 2           |
	| 4    | default_platform           | 0           |
	| 5    | sync_code_signing          | 16          |
	| 💥    | sync_code_signing          | 42          |
	+------+----------------------------+-------------+

	[17:51:52]: fastlane finished with errors

	Looking for related GitHub issues on fastlane/fastlane...

	➡️  [Regression] Breaking change when importing a new cert in 2.113.0, worked in 2.112.0
	    https://github.com/fastlane/fastlane/issues/14039 [closed] 72 💬
	    4 weeks ago

	➡️  Crash when there are no devices on the portal
	    https://github.com/fastlane/fastlane/issues/2004 [closed] 9 💬
	    06 Dec 2016

	➡️  Apple site reporting 'undergoing maintenance'
	    https://github.com/fastlane/fastlane/issues/8209 [closed] 116 💬
	    15 Feb 2017

	and 2 more at: https://github.com/fastlane/fastlane/search?q=Apple%20provided%20the%20following%20error%20info%3A%0A%09There%20were%20errors%20in%20the%20data%20supplied.%20Please%20correct%20and%20re-submit.%0A%09There%20are%20no%20current%20IOS%20devices%20on%20this%20team%20matching%20the%20provided%20device%20IDs.&type=Issues&utf8=✓

	🔗  You can ⌘ + double-click on links to open them directly in your browser.

	[!] Apple provided the following error info:
		There were errors in the data supplied. Please correct and re-submit.
		There are no current IOS devices on this team matching the provided device IDs.

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15                                       |
| Ruby                        | 2.5.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.21.0 (Apple Git-122)          |
| Installation Source         | ~/.rbenv/versions/2.5.0/bin/fastlane        |
| Host                        | Mac OS X 10.15 (19A583)                     |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.0/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_IE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.128.0"
default_platform :ios

platform :ios do

  lane :imitate_problem do 
    sync_code_signing(
      username: "taras.evchenko@gmail.com",
      app_identifier: "com.xcart", 
      team_id: "CDVQN43CHN",
      git_branch: "CDVQN43CHN",
      type: "adhoc",
      readonly: false, 
      force: false,
      force_for_new_devices: true
    )

    sync_code_signing(
      username: "antol.peshkov@gmail.com",
      app_identifier: "com.xcartstore", 
      team_id: "7M9PEFJ8ZU",
      git_branch: "7M9PEFJ8ZU",
      type: "adhoc",
      readonly: false, 
      force: false,
      force_for_new_devices: true
    )
  end

end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.133.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| bundler                   | 2.0.1        |
| fileutils                 | 1.0.2        |
| CFPropertyList            | 3.0.1        |
| concurrent-ruby           | 1.1.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.11.1     |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.7.5        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.2.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.1        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| cocoapods                 | 1.7.5        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.67.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.1        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.0904  |
| mime-types                | 3.3          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.4.5        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| git                       | 1.2.9.1      |
| liquid                    | 4.0.0        |
| thor                      | 0.19.1       |
| generamba                 | 1.5.0        |
| httparty                  | 0.17.0       |
</details>

*generated on:* **2019-10-09**
</details>

**Comment by kennyljv** [comment]
This issue is valid, also having it on the latest fastlane version 2.137.0. Multiple team id with multiple bundle id.
