### ISSUE TITLE
upload_to_testflight failing with "The set property option -D for property ... is missing a value"

### ISSUE THREAD

**Issue by kentcb** [fastlane/fastlane#15464]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Trying to use `upload_to_testflight` gives me:

```
[14:54:46]: ----------------------------------
[14:54:46]: --- Step: upload_to_testflight ---
[14:54:46]: ----------------------------------
[14:54:46]: Login to App Store Connect (<<redacted>>)
[14:54:47]: Login successful
[14:54:49]: Ready to upload new build to TestFlight (App: <<redacted>>)...
[14:54:57]: [Transporter Error Output]: The set property option -D for property "qj@hfd!TUb6LjodpkyMGENpybTHmMH" is missing a value.
[14:54:57]: Transporter transfer failed.
[14:54:57]: 
[14:54:57]: The set property option -D for property "qj@hfd!TUb6LjodpkyMGENpybTHmMH" is missing a value.
```

##### Command executed

I first found it when executing a Fastfile, but can reproduce with this:
```
fastlane run upload_to_testflight
```

##### Complete output when running fastlane, including the stack trace and command used
<details>
<pre>
kent$ fastlane run upload_to_testflight
[14:54:44]: fastlane detected a Gemfile in the current directory
[14:54:44]: however it seems like you don't use `bundle exec`
[14:54:44]: to launch fastlane faster, please use
[14:54:44]: 
[14:54:44]: $ bundle exec fastlane run upload_to_testflight
[14:54:44]: 
[14:54:44]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[14:54:46]: ----------------------------------
[14:54:46]: --- Step: upload_to_testflight ---
[14:54:46]: ----------------------------------
[14:54:46]: Login to App Store Connect (&lt;&lt;redacted&gt;&gt;)
[14:54:47]: Login successful
[14:54:49]: Ready to upload new build to TestFlight (App: &lt;&lt;redacted&gt;&gt;)...
[14:54:57]: [Transporter Error Output]: The set property option -D for property "qj@hfd!TUb6LjodpkyMGENpybTHmMH" is missing a value.
[14:54:57]: Transporter transfer failed.
[14:54:57]: 
[14:54:57]: The set property option -D for property "qj@hfd!TUb6LjodpkyMGENpybTHmMH" is missing a value.
[14:54:57]: [iTMSTransporter] [2019-10-10 14:54:53 AEST] <main>  INFO: Configuring logging...

[14:54:57]: [iTMSTransporter] [2019-10-10 14:54:53 AEST] <main>  INFO: Logging level set to eXtreme

[14:54:57]: [iTMSTransporter] [2019-10-10 14:54:53 AEST] <main>  INFO: Transporter is searching for new software components.

[14:54:57]: [iTMSTransporter] [2019-10-10 14:54:53 AEST] <main>  INFO: INFO: using cached repository.xml file.

[14:54:57]: [iTMSTransporter] [2019-10-10 14:54:54 AEST] <main>  INFO: Update check complete.

[14:54:57]: [iTMSTransporter] [2019-10-10 14:54:57 AEST] <main> DEBUG: Attempting refresh of configuration data from https://contentdelivery.itunes.apple.com/transporter/Defaults.properties

[14:54:57]: [iTMSTransporter] [2019-10-10 14:54:57 AEST] <main> DEBUG: Configuration refresh successful.

[14:54:57]: [iTMSTransporter] [2019-10-10 14:54:57 AEST] <main> DEBUG: Saving configuration to local path: /Users/kent/Library/Caches/com.apple.amp.itmstransporter/Defaults.properties

[14:54:57]: [iTMSTransporter] [2019-10-10 14:54:57 AEST] <main> ERROR: The set property option -D for property "qj@hfd!TUb6LjodpkyMGENpybTHmMH" is missing a value.

[14:54:57]: [iTMSTransporter] [2019-10-10 14:54:57 AEST] <main> DBG-X: Returning 1

[14:54:57]: iTunes Transporter output above ^
[14:54:57]: The set property option -D for property "qj@hfd!TUb6LjodpkyMGENpybTHmMH" is missing a value.
Return status of iTunes Transporter was 1: The set property option -D for property "qj@hfd!TUb6LjodpkyMGENpybTHmMH" is missing a value.
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
[14:54:57]: Going to upload updated app to App Store Connect
[14:54:57]: This might take a few minutes. Please don't interrupt the script.
[14:55:04]: [Transporter Error Output]: The set property option -D for property "qj@hfd!TUb6LjodpkyMGENpybTHmMH" is missing a value.
[14:55:04]: Transporter transfer failed.
[14:55:04]: 
[14:55:04]: The set property option -D for property "qj@hfd!TUb6LjodpkyMGENpybTHmMH" is missing a value.
[14:55:04]: [iTMSTransporter] [2019-10-10 14:55:01 AEST] <main>  INFO: Configuring logging...

[14:55:04]: [iTMSTransporter] [2019-10-10 14:55:01 AEST] <main>  INFO: Logging level set to eXtreme

[14:55:04]: [iTMSTransporter] [2019-10-10 14:55:01 AEST] <main>  INFO: Transporter is searching for new software components.

[14:55:04]: [iTMSTransporter] [2019-10-10 14:55:01 AEST] <main>  INFO: INFO: using cached repository.xml file.

[14:55:04]: [iTMSTransporter] [2019-10-10 14:55:01 AEST] <main>  INFO: Update check complete.

[14:55:04]: [iTMSTransporter] [2019-10-10 14:55:04 AEST] <main> DEBUG: Attempting refresh of configuration data from https://contentdelivery.itunes.apple.com/transporter/Defaults.properties

[14:55:04]: [iTMSTransporter] [2019-10-10 14:55:04 AEST] <main> DEBUG: Configuration refresh successful.

[14:55:04]: [iTMSTransporter] [2019-10-10 14:55:04 AEST] <main> DEBUG: Saving configuration to local path: /Users/kent/Library/Caches/com.apple.amp.itmstransporter/Defaults.properties

[14:55:04]: [iTMSTransporter] [2019-10-10 14:55:04 AEST] <main> ERROR: The set property option -D for property "qj@hfd!TUb6LjodpkyMGENpybTHmMH" is missing a value.

[14:55:04]: [iTMSTransporter] [2019-10-10 14:55:04 AEST] <main> DBG-X: Returning 1

[14:55:04]: iTunes Transporter output above ^
[14:55:04]: The set property option -D for property "qj@hfd!TUb6LjodpkyMGENpybTHmMH" is missing a value.
Return status of iTunes Transporter was 1: The set property option -D for property "qj@hfd!TUb6LjodpkyMGENpybTHmMH" is missing a value.
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.

[!] Error uploading ipa file, for more information see above
</pre>
</details>

### Environment

<details>
<pre>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0 (Apple Git-122)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.6 (18G95)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Prevent Fastlane from overwriting README.md
skip_docs

default_platform(:ios)

platform :ios do
  desc 'Builds a signed IPA and push it to TestFlight'
  lane :upload_beta do
    # We need to disable automatic code signing...
    disable_automatic_code_signing

    # ...and explicitly specify the provisioning profile to use because this is not a development build.
    update_project_provisioning(
      xcodeproj: 'Runner.xcodeproj',
      target_filter: 'Runner',
      build_configuration: 'Release',
      profile: ENV["PROVISIONING_PROFILE_PATH"],
      code_signing_identity: 'iPhone Distribution',
    )

    # Build and archive the app again. This assumes the correct certificate and provisioning profile is installed.
    build_ios_app(
      workspace: 'Runner.xcworkspace',
      scheme: 'Runner',
      configuration: 'Release',
      export_method: 'ad-hoc',
    )

    upload_to_testflight
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("<<redacted>>") # The bundle identifier of your app
apple_id("<<redacted>>") # Your Apple email address

itc_team_id("<<redacted>>") # App Store Connect Team ID

team_id("<<redacted>>") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.133.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.1        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.67.0       |
| faraday                   | 0.12.1       |
| faraday_middleware        | 0.11.0.1     |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.14.6       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.0904  |
| mime-types                | 3.1          |
| multi_json                | 1.13.1       |
| signet                    | 0.10.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| libxml-ruby               | 3.0.0        |
| psych                     | 2.0.8        |
</details>

*generated on:* **2019-10-10**
</details>
</pre>
</details>

**Comment by janpio** [comment]
Can you please run with `--verbose` and see if you get more information?

**Comment by kentcb** [comment]
@janpio Sure. Here's a verbose log with sensitive info redacted:

```
kent$ fastlane run upload_to_testflight --verbose
[10:59:07]: fastlane detected a Gemfile in the current directory
[10:59:07]: however it seems like you don't use `bundle exec`
[10:59:07]: to launch fastlane faster, please use
[10:59:07]: 
[10:59:07]: $ bundle exec fastlane run upload_to_testflight --verbose
[10:59:07]: 
[10:59:07]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2019-10-14 10:59:08.75]: Checking if there are any plugins that should be loaded...
Successfully loaded Appfile at path '/Users/kent/Repository/<<redacted>>/ios/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/kent/Repository/<<redacted>>/ios/fastlane/Appfile'
-------
INFO [2019-10-14 10:59:09.01]: ----------------------------------
INFO [2019-10-14 10:59:09.01]: --- Step: upload_to_testflight ---
INFO [2019-10-14 10:59:09.01]: ----------------------------------
Successfully loaded Appfile at path '/Users/kent/Repository/<<redacted>>/ios/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/kent/Repository/<<redacted>>/ios/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/kent/Repository/<<redacted>>/ios/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/kent/Repository/<<redacted>>/ios/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/kent/Repository/<<redacted>>/ios/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/kent/Repository/<<redacted>>/ios/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/kent/Repository/<<redacted>>/ios/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/kent/Repository/<<redacted>>/ios/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/kent/Repository/<<redacted>>/ios/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/kent/Repository/<<redacted>>/ios/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/kent/Repository/<<redacted>>/ios/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/Users/kent/Repository/<<redacted>>/ios/fastlane/Appfile'
-------
WARN [2019-10-14 10:59:09.18]: To not be asked about this value, you can specify it using 'username'
 [2019-10-14 10:59:09.18]: Your Apple ID Username: kent.boogaart@<<redacted>>.com
INFO [2019-10-14 10:59:17.49]: Login to App Store Connect (kent.boogaart@<<redacted>>.com)
Reading keychain entry, because either user or password were empty
Loading session from '/Users/kent/.fastlane/spaceship/kent.boogaart@<<redacted>>.com/cookie'
Multiple App Store Connect teams found, please enter the number of the team you want to use: 
Note: to automatically choose the team, provide either the App Store Connect Team ID, or the Team Name in your fastlane/Appfile:
Alternatively you can pass the team name or team ID using the `FASTLANE_ITC_TEAM_ID` or `FASTLANE_ITC_TEAM_NAME` environment variable

  itc_team_id "119257442"

or

  itc_team_name "<<redacted>> Australia Pty Ltd"

1) "<<redacted>> Australia Pty Ltd" (<<redacted>>)
2) "<<redacted>> Ltd - <<redacted>>" (<<redacted>>)
1
INFO [2019-10-14 10:59:20.11]: Login successful
DEBUG [2019-10-14 10:59:20.13]: App identifier (com.<<redacted>>.appstore)
INFO [2019-10-14 10:59:21.54]: Ready to upload new build to TestFlight (App: <<redacted>>)...
DEBUG [2019-10-14 10:59:21.54]: App Platform (ios)
INFO [2019-10-14 10:59:21.91]: Wrote XML data to '/var/folders/hh/hvdpph0d13g1jplfy2sy74f80000gn/T/d20191014-63582-uo4o1e/<<redacted>>.itmsp'
DEBUG [2019-10-14 10:59:22.19]: /Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/itms/java/bin/java -Djava.ext.dirs=/Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/itms/java/lib/ext -XX:NewSize=2m -Xms32m -Xmx1024m -Xms1024m -Djava.awt.headless=true -Dsun.net.http.retryPost=false -jar /Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/itms/lib/itmstransporter-launcher.jar -m provider -u kent.boogaart@<<redacted>>.com -p YourPassword 2>&1
DEBUG [2019-10-14 10:59:25.18]: [Transporter]: INFO: Configuring logging...
DEBUG [2019-10-14 10:59:25.19]: [Transporter]: INFO: Logging level set to eXtreme
DEBUG [2019-10-14 10:59:25.20]: [Transporter]: INFO: Transporter is searching for new software components.
DEBUG [2019-10-14 10:59:25.20]: [Transporter]: INFO: INFO: using cached repository.xml file.
DEBUG [2019-10-14 10:59:25.52]: [Transporter]: INFO: Update check complete.
DEBUG [2019-10-14 10:59:28.15]: [Transporter]: DEBUG: Attempting refresh of configuration data from https://contentdelivery.itunes.apple.com/transporter/Defaults.properties
DEBUG [2019-10-14 10:59:28.37]: [Transporter]: DEBUG: Configuration refresh successful.
DEBUG [2019-10-14 10:59:28.37]: [Transporter]: DEBUG: Saving configuration to local path: /Users/kent/Library/Caches/com.apple.amp.itmstransporter/Defaults.properties
ERROR [2019-10-14 10:59:28.38]: [Transporter Error Output]: The set property option -D for property "qj@hfd!TUb6LjodpkyMGENpybTHmMH" is missing a value.
ERROR [2019-10-14 10:59:28.39]: Transporter transfer failed.
WARN [2019-10-14 10:59:28.39]: 
ERROR [2019-10-14 10:59:28.39]: The set property option -D for property "qj@hfd!TUb6LjodpkyMGENpybTHmMH" is missing a value.
WARN [2019-10-14 10:59:28.61]: [iTMSTransporter] [2019-10-14 10:59:25 AEST] <main>  INFO: Configuring logging...

WARN [2019-10-14 10:59:28.61]: [iTMSTransporter] [2019-10-14 10:59:25 AEST] <main>  INFO: Logging level set to eXtreme

WARN [2019-10-14 10:59:28.61]: [iTMSTransporter] [2019-10-14 10:59:25 AEST] <main>  INFO: Transporter is searching for new software components.

WARN [2019-10-14 10:59:28.61]: [iTMSTransporter] [2019-10-14 10:59:25 AEST] <main>  INFO: INFO: using cached repository.xml file.

WARN [2019-10-14 10:59:28.61]: [iTMSTransporter] [2019-10-14 10:59:25 AEST] <main>  INFO: Update check complete.

WARN [2019-10-14 10:59:28.61]: [iTMSTransporter] [2019-10-14 10:59:28 AEST] <main> DEBUG: Attempting refresh of configuration data from https://contentdelivery.itunes.apple.com/transporter/Defaults.properties

WARN [2019-10-14 10:59:28.61]: [iTMSTransporter] [2019-10-14 10:59:28 AEST] <main> DEBUG: Configuration refresh successful.

WARN [2019-10-14 10:59:28.61]: [iTMSTransporter] [2019-10-14 10:59:28 AEST] <main> DEBUG: Saving configuration to local path: /Users/kent/Library/Caches/com.apple.amp.itmstransporter/Defaults.properties

WARN [2019-10-14 10:59:28.61]: [iTMSTransporter] [2019-10-14 10:59:28 AEST] <main> ERROR: The set property option -D for property "qj@hfd!TUb6LjodpkyMGENpybTHmMH" is missing a value.

WARN [2019-10-14 10:59:28.61]: [iTMSTransporter] [2019-10-14 10:59:28 AEST] <main> DBG-X: Returning 1

INFO [2019-10-14 10:59:28.61]: iTunes Transporter output above ^
ERROR [2019-10-14 10:59:28.61]: The set property option -D for property "qj@hfd!TUb6LjodpkyMGENpybTHmMH" is missing a value.
Return status of iTunes Transporter was 1: The set property option -D for property "qj@hfd!TUb6LjodpkyMGENpybTHmMH" is missing a value.
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
DEBUG [2019-10-14 10:59:28.61]: Inferred provider id  for team <<redacted>> Australia Pty Ltd.
INFO [2019-10-14 10:59:28.69]: Going to upload updated app to App Store Connect
INFO [2019-10-14 10:59:28.69]: This might take a few minutes. Please don't interrupt the script.
DEBUG [2019-10-14 10:59:28.91]: /Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/itms/java/bin/java -Djava.ext.dirs=/Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/itms/java/lib/ext -XX:NewSize=2m -Xms32m -Xmx1024m -Xms1024m -Djava.awt.headless=true -Dsun.net.http.retryPost=false -jar /Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/itms/lib/itmstransporter-launcher.jar -m upload -u kent.boogaart@<<redacted>>.com -p YourPassword -f /var/folders/hh/hvdpph0d13g1jplfy2sy74f80000gn/T/d20191014-63582-uo4o1e/<<redacted>>.itmsp -t DAV,Signiant -k 100000 2>&1
DEBUG [2019-10-14 10:59:31.92]: [Transporter]: INFO: Configuring logging...
DEBUG [2019-10-14 10:59:31.93]: [Transporter]: INFO: Logging level set to eXtreme
DEBUG [2019-10-14 10:59:31.94]: [Transporter]: INFO: Transporter is searching for new software components.
DEBUG [2019-10-14 10:59:31.94]: [Transporter]: INFO: INFO: using cached repository.xml file.
DEBUG [2019-10-14 10:59:32.27]: [Transporter]: INFO: Update check complete.
DEBUG [2019-10-14 10:59:36.77]: [Transporter]: DEBUG: Attempting refresh of configuration data from https://contentdelivery.itunes.apple.com/transporter/Defaults.properties
DEBUG [2019-10-14 10:59:37.42]: [Transporter]: DEBUG: Configuration refresh successful.
DEBUG [2019-10-14 10:59:37.42]: [Transporter]: DEBUG: Saving configuration to local path: /Users/kent/Library/Caches/com.apple.amp.itmstransporter/Defaults.properties
ERROR [2019-10-14 10:59:37.44]: [Transporter Error Output]: The set property option -D for property "qj@hfd!TUb6LjodpkyMGENpybTHmMH" is missing a value.
ERROR [2019-10-14 10:59:37.45]: Transporter transfer failed.
WARN [2019-10-14 10:59:37.45]: 
ERROR [2019-10-14 10:59:37.45]: The set property option -D for property "qj@hfd!TUb6LjodpkyMGENpybTHmMH" is missing a value.
WARN [2019-10-14 10:59:37.68]: [iTMSTransporter] [2019-10-14 10:59:31 AEST] <main>  INFO: Configuring logging...

WARN [2019-10-14 10:59:37.68]: [iTMSTransporter] [2019-10-14 10:59:31 AEST] <main>  INFO: Logging level set to eXtreme

WARN [2019-10-14 10:59:37.68]: [iTMSTransporter] [2019-10-14 10:59:31 AEST] <main>  INFO: Transporter is searching for new software components.

WARN [2019-10-14 10:59:37.68]: [iTMSTransporter] [2019-10-14 10:59:31 AEST] <main>  INFO: INFO: using cached repository.xml file.

WARN [2019-10-14 10:59:37.68]: [iTMSTransporter] [2019-10-14 10:59:32 AEST] <main>  INFO: Update check complete.

WARN [2019-10-14 10:59:37.68]: [iTMSTransporter] [2019-10-14 10:59:36 AEST] <main> DEBUG: Attempting refresh of configuration data from https://contentdelivery.itunes.apple.com/transporter/Defaults.properties

WARN [2019-10-14 10:59:37.68]: [iTMSTransporter] [2019-10-14 10:59:37 AEST] <main> DEBUG: Configuration refresh successful.

WARN [2019-10-14 10:59:37.68]: [iTMSTransporter] [2019-10-14 10:59:37 AEST] <main> DEBUG: Saving configuration to local path: /Users/kent/Library/Caches/com.apple.amp.itmstransporter/Defaults.properties

WARN [2019-10-14 10:59:37.68]: [iTMSTransporter] [2019-10-14 10:59:37 AEST] <main> ERROR: The set property option -D for property "qj@hfd!TUb6LjodpkyMGENpybTHmMH" is missing a value.

WARN [2019-10-14 10:59:37.68]: [iTMSTransporter] [2019-10-14 10:59:37 AEST] <main> DBG-X: Returning 1

INFO [2019-10-14 10:59:37.68]: iTunes Transporter output above ^
ERROR [2019-10-14 10:59:37.68]: The set property option -D for property "qj@hfd!TUb6LjodpkyMGENpybTHmMH" is missing a value.
Return status of iTunes Transporter was 1: The set property option -D for property "qj@hfd!TUb6LjodpkyMGENpybTHmMH" is missing a value.
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
/Users/kent/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.133.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Error uploading ipa file, for more information see above (FastlaneCore::Interface::FastlaneError)
	from /Users/kent/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.133.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/kent/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.133.0/pilot/lib/pilot/build_manager.rb:37:in `upload'
	from /Users/kent/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:16:in `run'
	from /Users/kent/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
	from /Users/kent/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/kent/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
	from /Users/kent/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/kent/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/kent/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/one_off.rb:42:in `run'
	from /Users/kent/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/one_off.rb:22:in `execute'
	from /Users/kent/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/commands_generator.rb:221:in `block (2 levels) in run'
	from /Users/kent/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/kent/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/kent/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/kent/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/kent/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.133.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/kent/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/kent/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	from /Users/kent/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/kent/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Users/kent/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.133.0/bin/fastlane:23:in `<top (required)>'
	from /Users/kent/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/kent/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```

**Comment by janpio** [comment]
Hm, nothing pops out, and `property option -D for property "qj@hfd!TUb6LjodpkyMGENpybTHmMH"` doesn't make any sense to me.

**Comment by kentcb** [comment]
@janpio I've debugged through this and found it's because our password starts with `-`. This means the Java command that is generated has this in it:

```
-p -the_rest_of_our_password
```
And this trips up Java's CLI parser. Should the `shellescape` be handling this? It's not clear to me how. I tried the obvious thing (wrapping the value in quotes) but that didn't work.

**Comment by janpio** [comment]
I am also not sure how shelling out here works for the Java thing that is happening there. I would try to get the command working outside of Fastlane context, and then try all the variations I can thing of (warp in `"`, warp in `'`, use `\` before the `-`) until one works. If this doesn't give results, I would start googling how to actually use `-` in params for that command ;)
