### ISSUE TITLE
[scan] Support for -testPlan and .xctestplan

### ISSUE THREAD

**Issue by daveanderson** [fastlane/fastlane#15462]
#### Motivation Behind Feature
Xcode 11 supports test plans which simplify configuration. I don't believe that everything that `scan` supports is also supported by test plans, so I would be interested in the niceties of `scan` being available for running tests configured as an .xctestplan

#### Feature Description
Evolve scan to support the use of .xctestplan files to define (and override) the parts of running tests that are redundant between xctestplan and scan, while continuing to support the xcpretty and any other scan-specific features that xctestplans do NOT support.

#### Alternatives or Workarounds
```
xcodebuild -workspace Project.xcworkspace -scheme ProjectUITests -destination 'platform=iOS Simulator,OS=13.1,name=iPhone 11 Pro' test -testPlan UITestPlan
```

**Comment by pradyhk** [comment]
workaround : xcargs: "-testPlan testPlanToUse",
