### ISSUE TITLE
When using multiple trusted numbers, the 2 factor auth code is never sent.

### ISSUE THREAD

**Issue by Daniel-Griffiths** [fastlane/fastlane#15468]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When running `fastlane deliver` or `fastlane spaceauth` it prompts me to enter a 2 factor code. The issue is that the code is never sent to my phone. The account in question has multiple trusted numbers so it could be due to that.

I also tried using the `SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER` env to specify a default phone number but I still never received the code.

##### Command executed

Tried both

```
fastlane deliver --verbose --ipa "app.ipa" --skip_screenshots --skip_metadata
```

And...

```
fastlane spaceauth
```

With the following env values defined

```
DELIVER_USERNAME="XXXX@XXXX.com"
DELIVER_PASSWORD="XXXX"
SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER="+XX XXXX XXXXXX"
```

My OS is Mac OS Catalina

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15                                       |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0 (Apple Git-122)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.15 (19A583)                     |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.28.3  | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2019-10-10**
</details>

**Comment by janpio** [comment]
Please post the full output you are getting when running these commands. Thanks.

**Comment by Daniel-Griffiths** [comment]
Thanks for the reply @janpio the terminal output is as follows

```
danielgriffiths@Daniels-MBP mobile % fastlane deliver --verbose --ipa "app.ipa" --skip_screenshots --skip_metadata
WARN [2019-10-14 13:00:41.97]: To not be asked about this value, you can specify it using 'username'
 [2019-10-14 13:00:41.97]: Your Apple ID Username: ***@***.com
INFO [2019-10-14 13:01:00.57]: Login to iTunes Connect (***@***.com)
Two Factor Authentication for account '***@***.com' is enabled
If you're running this in a non-interactive session (e.g. server or CI)
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification
Please enter the 6 digit code: 
```

It asks for the 6 digit number but it never actually get's sent

**Comment by janpio** [comment]
> fastlane 	2.28.3 	💥 Check failed

Your fastlane version in ancient and doesn't support this at all. You should update. (Strange that `fastlane env` does not tell you that itself.)

**Comment by Daniel-Griffiths** [comment]
Ah! That's probably the issue! I will verify this shortly.

The interesting thing is that I installed this by following the docs: https://docs.fastlane.tools/getting-started/ios/setup/

I guess `brew cask install fastlane` installed a very old version for some reason 🤔 

Thank again.

**Comment by Daniel-Griffiths** [comment]
I can confirm that installing via homebrew always downloads version `2.28.4` but installing via rubygems get's me the latest version.

**Comment by janpio** [comment]
Great that we fixed that for you.

Could you please create a new issue for this problem? Someone will hopefully investigate that and figure out what is going on.

**Comment by Daniel-Griffiths** [comment]
Of course! Thanks again for the help. 😄
