### ISSUE TITLE
Error updating fastlane: signet requires Ruby version >= 2.4.0.

### ISSUE THREAD

**Issue by gdingenen** [fastlane/fastlane#15467]
### New Issue Checklist

- [] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm unable to update fastlane after a fresh installation of fastlane.
The following error is logged:
signet requires Ruby version >= 2.4.0

##### Command executed
fastlane update_fastlane --capture_output

##### Complete output when running fastlane, including the stack trace and command used
fastlane could not check for updates error: execution expired
Updating installed gems
Updating fastlane
Gems updated: signet
Gems already up-to-date: fastlane
ERROR:  Error installing fastlane:
	signet requires Ruby version >= 2.4.0.
Cleaning up installed gems...
Clean Up Complete

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.6 (18G95)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.28.3  | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| addressable               | 2.5.1        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.6        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| google-api-client         | 0.9.28       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 2.1.0        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.9.5        |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.6        |
| naturally                 | 2.2.0        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 2.0.7        |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| simctl                    | 1.6.6        |
| slack-notifier            | 2.3.2        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 2.0.0        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-cursor                | 0.7.0        |
| tty-screen                | 0.7.0        |
| tty-screen                | 0.5.0        |
| tty-spinner               | 0.9.1        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.12.0       |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2019-10-10**
</details>

**Comment by getaaron** [comment]
Hi 👋 you're using Ruby version 2.2.4. You need to upgrade to Ruby 2.4 or later.

**Comment by gdingenen** [comment]
I had a higher version of Ruby installed. But Fastlane used a bundled version of Ruby which was version 2.2.4.

After removing my main Fastlane installation and reinstalling it with `sudo gem install fastlane -NV` and updating the project's Fastlane with `bundle update fastlane` I managed to resolve this issue.

**Comment by mobdevlion** [comment]
I had same issue. In case that you have no root access, you can use this tutorial:
https://hackernoon.com/the-only-sane-way-to-setup-fastlane-on-a-mac-4a14cb8549c8

**Comment by vinbhai4u** [comment]
I am still not able to install fastlane.  Followed suggestion from @mobdevlion & @burtsevyg :(

**Comment by burtsevyg** [comment]
@vinbhai4u What is your environment?

**Comment by vinbhai4u** [comment]
got it to working using

```
rvm install 2.4.1
rvm use 2.4.1
```

**Comment by lundcm** [comment]
Used `brew cask install fastlane`, per the fastlane docs, to install fastlane and an old version of ruby got bundled with it. I had a lot of issues with it, but the upgrade brought me here. I removed that installation and installed with `sudo gem install fastlane -NV` from @gdingenen's suggestion. All the issues I was having are gone.

**Comment by NicolasCombe5555** [comment]
I had this same problem while following a tutorial on medium, i eventually found an answer thanks to you, here is what i did: https://stackoverflow.com/questions/58775795/fastlane-nokogiri-requires-ruby-version-2-3-0-error
