### ISSUE TITLE
upload_to_play_store Connection reset by peer

### ISSUE THREAD

**Issue by idanhaviv** [fastlane/fastlane#15472]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
upload_to_play_store(track: 'internal', skip_upload_apk: true, timeout: 3000, skip_upload_images: true, skip_upload_screenshots: true)
errors with 'Connection reset by peer' with no additional data.
I tried calling upload_to_play_store(track: 'internal', skip_upload_apk: true) with the same results.

<details>
  <pre>
+-------------------------+------------------------------------------------------------------------------------------------+
|                                                Summary for supply 2.133.0                                                |
+-------------------------+------------------------------------------------------------------------------------------------+
| track                   | internal                                                                                       |
| skip_upload_apk         | true                                                                                           |
| timeout                 | 3000                                                                                           |
| skip_upload_images      | true                                                                                           |
| skip_upload_screenshots | true                                                                                           |
| aab                     | ******/android/app/build/outputs/bundle/release/app  |
|                         | -release.aab                                                                                   |
| package_name            | ******                                                                         |
| metadata_path           | ./fastlane/metadata/android                                                                    |
| json_key                | key.json                                                                                       |
| skip_upload_aab         | false                                                                                          |
| skip_upload_metadata    | false                                                                                          |
| validate_only           | false                                                                                          |
| check_superseded_tracks | false                                                                                          |
| deactivate_on_promote   | true                                                                                           |
+-------------------------+------------------------------------------------------------------------------------------------+

[07:39:46]: Preparing to upload for language 'en-US'...
[07:39:47]: Preparing aab at path '****/android/app/build/outputs/bundle/release/app-release.aab' for upload...
+-------------------------------------+------------------------------------------------------------------------------------------------+
|                                                             Lane Context                                                             |
+-------------------------------------+------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM                    | android                                                                                        |
| PLATFORM_NAME                       | android                                                                                        |
| LANE_NAME                           | android beta                                                                                   |
| GRADLE_BUILD_TYPE                   | Release                                                                                        |
| GRADLE_ALL_APK_OUTPUT_PATHS         | []                                                                                             |
| GRADLE_ALL_AAB_OUTPUT_PATHS         | ["******/android/app/build/outputs/bundle/release/a  |
|                                     | pp-release.aab"]                                                                               |
| GRADLE_ALL_OUTPUT_JSON_OUTPUT_PATHS | []                                                                                             |
| GRADLE_AAB_OUTPUT_PATH              | *****/android/app/build/outputs/bundle/release/app  |
|                                     | -release.aab                                                                                   |
+-------------------------------------+------------------------------------------------------------------------------------------------+
[07:43:30]: HTTPClient::KeepAliveDisconnected: Connection reset by peer

+------+----------------------+-------------+
|             fastlane summary              |
+------+----------------------+-------------+
| Step | Action               | Time (in s) |
+------+----------------------+-------------+
| 1    | default_platform     | 0           |
| 2    | gradle               | 5           |
| 3    | gradle               | 46          |
| 💥   | upload_to_play_store | 225         |
+------+----------------------+-------------+

[07:43:30]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
Traceback (most recent call last):
        66: from ****/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
        65: from ****/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
        ....
         1: from *****/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:804:in `block in parse_header'
*****/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:813:in `rescue in block in parse_header': [!] HTTPClient::KeepAliveDisconnected: Connection reset by peer (HTTPClient::KeepAliveDisconnected)
</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.21.0 (Apple Git-122)          |
| Installation Source         | ~/.rvm/rubies/ruby-2.6.3/bin/fastlane       |
| Host                        | Mac OS X 10.14.6 (18G103)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.3/lib                |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.0                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform(:android)

platform :android do
  desc "Submit a new Beta Build to Play Store"
  lane :beta do
    store_password = prompt(text: "Signing Store Password: ", secure_text: true)
    key_password = prompt(text: "Alias Key Password: ", secure_text: true)
    releaseFilePath = File.join(Dir.pwd, "..", "my-release-key.keystore")
    gradle(task: 'clean')
    gradle(
      task: 'bundle',
      build_type: 'Release',
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => releaseFilePath,
        "android.injected.signing.store.password" => store_password,
        "android.injected.signing.key.alias" => "my-key-alias",
        "android.injected.signing.key.password" => key_password,
      }
    )
    upload_to_play_store(
      track: 'internal', skip_upload_apk: true, timeout: 3000, skip_upload_images: true, skip_upload_screenshots: true
    )
  end
end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.133.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.17.3       |
| etc                       | 1.0.1        |
| forwardable               | 1.2.0        |
| CFPropertyList            | 3.0.1        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.67.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.1        |
| signet                    | 0.12.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.1009  |
| mime-types                | 3.3          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2019-10-11**
</details>

**Comment by janpio** [comment]
This seems to be a connection problem between you and the server. Super hard to debug. Can you try in a different network and see if it persists?

**Comment by idanhaviv** [comment]
@janpio it worked now from a different network. 
I know it's a hard to debug situation, but I have a feeling that it wasn't purely a network thing since it occurred to me multiple times on several networks with no real network issue as it looked in the browser and other platforms. 

thanks
