### ISSUE TITLE
Frameit produces a portrait image for a landscape screenshot

### ISSUE THREAD

**Issue by mrgrauel** [fastlane/fastlane#15476]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
* Frameit produces a portrait screenshot for a landscape image
  * Framed: [iPad Pro (12 9-inch) (2nd generation)-1_stream_framed](https://user-images.githubusercontent.com/148758/66648497-fa623600-ec2b-11e9-97f9-2d1cb4bf47a5.png)
  * Screenshot: [iPad Pro (12 9-inch) (2nd generation)-1_stream](https://user-images.githubusercontent.com/148758/66648539-0b12ac00-ec2c-11e9-9ba8-24867cfbd747.png)

##### Command executed
`frameit(path: lane_context[SharedValues::SNAPSHOT_SCREENSHOTS_PATH], white: true)`

No error message just the wrong result

### Environment

<details>
  <pre>
 <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15                                       |
| Ruby                        | 2.6.5                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.23.0                          |
| Installation Source         | /usr/local/lib/ruby/gems/2.6.0/bin/fastlane |
| Host                        | Mac OS X 10.15 (19A583)                     |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.6.5/lib            |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version '2.129.0'
fastlane_require 'json'
fastlane_require 'net/http'

default_platform :ios

before_all do
  clear_derived_data
  update_fastlane(nightly: false)
end

platform :ios do

    # Build
    lane :build_development do
        xcode_select(ENV["XCODE_PATH"])
        scan
    end

    lane :build_release do
        xcode_select(ENV["XCODE_PATH"])
        increment_build_number(build_number: ENV["CI_PIPELINE_ID"].to_i + 16000)
        gym
    end

    # Testflight
    lane :upload_nightly do
        upload_to_testflight
    end

    lane :upload_appstore do
        upload_to_testflight(
                             distribute_external: true,
                             reject_build_waiting_for_review: true,
                             groups: ['Mitarbeiter', 'Test-Dienstleister', 'Public Beta']
                             )
    end

    # Firebase
    lane :firebase do
        get_version_number
        ENV['DOWNLOAD_DSYMS_MIN_VERSION'] = lane_context[SharedValues::VERSION_NUMBER]
        download_dsyms(build_number: (ENV["CI_PIPELINE_ID"].to_i + 16000).to_s)
        upload_symbols_to_crashlytics
        clean_build_artifacts
    end

    # AppStore
    lane :submit do
        get_version_number
        deliver(
                submit_for_review: true,
                reject_if_possible: true,
                automatic_release: true,
                skip_metadata: true,
                skip_screenshots: true,
                build_number: (ENV["CI_PIPELINE_ID"].to_i + 16000).to_s,
                app_version: lane_context[SharedValues::VERSION_NUMBER]
                )
    end

    lane :metadata do
        get_version_number
        mainpath = ENV['MAINPATH']
        update_metadata("#{Dir.pwd}/#{mainpath}/metadata", ENV['LANGUAGES'].split(','))
        deliver(
                submit_for_review: false,
                app_version: lane_context[SharedValues::VERSION_NUMBER],
                metadata_path: "./fastlane/#{mainpath}/metadata",
                skip_metadata: false,
                screenshots_path: "./fastlane/#{mainpath}/metadata",
                skip_screenshots: true
                )
    end

    # Screenshots
    screenshot_locales = ["cs","da","de-DE","el","en-AU","en-CA","en-GB","en-US","es-ES","es-MX","fr-CA","fr-FR", "hi", "hr","hu-HU","id","it","nl-NL","pl-PL","pt-BR","pt-PT","ro","ru","sk","tr","uk-UA"]
    devices            = ["iPhone 8 Plus", "iPhone Xs Max", "iPad Pro (12.9-inch) (2nd generation)", "iPad Pro (12.9-inch) (3rd generation)"]

    lane :update_screenshots_placemarks do
        screenshot_locales.each { | locale |
            metadata = parse_locale_metadata("../SnapshotData/configuration_wetter_app.json", locale)
            localities_result = fetch_localities_result(metadata["language"], metadata["region"], metadata["localities"])
            File.write("../SnapshotData/#{metadata["identifier"]}.json", JSON.pretty_generate(localities_result))
        }
    end

    lane :screenshots do |options|
        app = ENV['SCREENSHOTS_APP']
        locale = ENV['SCREENSHOTS_LOCALE']

        if app == "rainfallradar"
            screenshots_rainfallradar_app(locale: locale)
        elsif app == "weatherandradar"
            screenshots_weatherandradar_app(locale: locale)
        else
            raise "invalid app identifier"
        end
    end

    lane :screenshots_rainfallradar_app do |options|
        screenshots_capture(locale: options[:locale],
                            configuration: "Debug RegenRadar Pro",
                            app_identifier: "de.wetteronline.RegenRadarpro",
                            metadata_path: "../SnapshotData/configuration_rainfallradar_app.json",
                            devices: devices,
                            clear_previous_screenshots: true)
    end

    lane :screenshots_weatherandradar_app do |options|
        screenshots_capture(locale: options[:locale],
                            configuration: "Debug Pro",
                            app_identifier: "de.wetteronline.WetterApppro",
                            metadata_path: "../SnapshotData/configuration_wetter_app.json",
                            devices: devices,
                            clear_previous_screenshots: true)
        screenshots_frame()
    end

    private_lane :screenshots_capture do |options|
        xcode_select(ENV["XCODE_PATH"])

        scheme = "SnapshotUI"
        devices = options[:devices]
        configuration = options[:configuration]
        app_identifier = options[:app_identifier]
        clear_previous_screenshots = options[:clear_previous_screenshots]

        locale = options[:locale]
        metadata = parse_locale_metadata(options[:metadata_path], locale)

        launch_arguments = parse_locale_launch_arguments(metadata["screenshots"])

        clear_derived_data

        scan(scheme: scheme,
             configuration: configuration,
             app_identifier: app_identifier,
             devices: devices,
             reinstall_app: true,
             clean: true,
             build_for_testing: true,
             suppress_xcode_output: false)

        snapshot(scheme: scheme,
                configuration: configuration,
                app_identifier: app_identifier,
                languages: [metadata["identifier"]],
                erase_simulator: true,
                devices: devices,
                test_without_building: true,
                launch_arguments: launch_arguments,
                clear_previous_screenshots: clear_previous_screenshots,
                derived_data_path: lane_context[SharedValues::SCAN_DERIVED_DATA_PATH])
    end

    private_lane :screenshots_frame do
        frameit(path: lane_context[SharedValues::SNAPSHOT_SCREENSHOTS_PATH],
                white: true)
    end
end

# Private Methods

def parse_locale_metadata(filePath, locale)
    if File.file?(filePath) == false
        raise "no config file at path: #{filePath}"
    end

    file = File.read(filePath)
    configurationLocales = JSON.parse(file)

    configurationLocales.find { | configurationLocale |
        locale == configurationLocale["identifier"]
    }
end

def parse_locale_launch_arguments(screenshots)
    launch_arguments = []
    counter = 1

    screenshots.each { | screenshot |
        identifier     = screenshot["identifier"]
        locality_index = screenshot["locality_index"]
        warning        = screenshot["warning"]

        launch_argument_set = [
        "-WOScreenshotsContentIdentifier #{identifier}",
        "-WOScreenshotsNamingPrefix #{counter}",
        "-WOWarningMode #{warning}"
        ]

        if locality_index.nil? == false
            launch_argument_set << "-WOScreenshotsLocalityIndex #{locality_index}"
        end

        launch_arguments << launch_argument_set.join(" ")
        counter += 1
    }
    return launch_arguments
end

def fetch_localities_result(language, region, localities)
    results = Array.new()
    localities.each { | locality |
        result = fetch_locality_result(language, region, locality)
        results.push(result)
    }
    return results
end

def fetch_locality_result(language, region, locality)
    url = "https://api.wetteronline.de/search?mv=1&format=json&area=cities&lang=#{language}&region=#{region}&name=#{locality}"
    uri = URI.parse(URI.escape(url))
    response = Net::HTTP.get(uri)
    array = JSON.parse(response)

    if array.empty?
        raise "Could not fetch json for locality #{locality}"
    end

    return array.first # always take the first value
end

def update_metadata(metadata_path, languages)
    metadata = Hash.new
    languages.each { | language |
        path = "#{metadata_path}/#{language}"
        dataFilePath = "#{path}/_data.json"
        if File.file?(dataFilePath)
            file = File.read(dataFilePath)
            json = JSON.parse(file)

            release_notes = json["release_notes"].to_s.empty? ? json["release_notes_default"] : json["release_notes"]

            File.open("#{path}/description.txt", "w") { |file| file.write(json["description"])}
            File.open("#{path}/keywords.txt", "w") { |file| file.write(json["keywords"])}
            File.open("#{path}/marketing_url.txt", "w") { |file| file.write(json["marketing_url"])}
            File.open("#{path}/name.txt", "w") { |file| file.write(json["name"])}
            File.open("#{path}/privacy_url.txt", "w") { |file| file.write(json["privacy_url"])}
            File.open("#{path}/release_notes.txt", "w") { |file| file.write(release_notes)}
            File.open("#{path}/support_url.txt", "w") { |file| file.write(json["support_url"])}
            File.open("#{path}/subtitle.txt", "w") { |file| file.write(json["subtitle"])}
            File.open("#{path}/promotional_text.txt", "w") { |file| file.write(json["promotional_text"])}
        end
    }
end
# More information about multiple platforms in fastlane: https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id "xxxx@xxxx.de" # Your Apple email address
team_name "xxx"
team_id "xxx"

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.133.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.1        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.1        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.67.0       |
| faraday                   | 0.15.4       |
| faraday_middleware        | 0.13.1       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.2.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.0904  |
| mime-types                | 3.3          |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| emoji_regex               | 1.0.1        |
| digest-crc                | 0.4.1        |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| google-cloud-storage      | 1.16.0       |
</details>

*generated on:* **2019-10-11**
</details>
 </pre>
</details>

**Comment by mrgrauel** [comment]
It seems to be that the screenshots orientation is wrong evaluated, but am not sure why this happens.

https://github.com/fastlane/fastlane/blob/266fbfb860fae15433015fe15b4d5aa9fc3c9ec0/frameit/lib/frameit/screenshot.rb#L93

**Comment by janpio** [comment]
Shouldn't the original screenshot be rotated 90 degrees counter clock wise? It displays like this to me in Chrome:

![image](https://user-images.githubusercontent.com/183673/66717617-37205f80-eddb-11e9-9c6d-09d9e7068619.png)

**Comment by mrgrauel** [comment]
I dunno 🤷‍♂  On Safari it's displayed in landscape on firefox and chrome it's portrait. If I understand the implementation correct fastlane does not read exif data it just checks the image size to determine the rotation value.

**Comment by janpio** [comment]
That is indeed possible, have to check the code. (The exif rotation information is quite a mess I just read somewhere.) `frameit` is possibly built only for screenshots as taken by fastlane tools, which probably does not involve this behavior.

**Comment by mrgrauel** [comment]
I took the screenshots with fastlane/snapshot.

**Comment by janpio** [comment]
Oh - there goes my nice theory.

**Comment by mrgrauel** [comment]
The Fastfile is included in the issue description. It's automated via GitLab CI with a runner on an macOS 10.15 (19A583) and Xcode 11.1 (11A1027).

**Comment by matrouthier** [comment]
I have the same problem.  I had to go and rotate the screenshots in Photoshop.  I'm not sure what introduced the problem.  Something changed in either XCode 11.1 or macOS Catalina.

**Comment by janpio** [comment]
Uh, a confirmation that the created screenshots are different from older Xcode vs. current Xcode would be a great help here - then this is not actually a frameit problem but probably snapshot.

**Comment by mrgrauel** [comment]
I'd do it but I can't build the project with Xcode 10.3 anymore and to use an old variation would help cause this cannot be build with Xcode 11 to compare. 🤔

**Comment by matrouthier** [comment]
> this is not actually a frameit problem but probably snapshot.
Yes, probably the output of snapshot is different now, but it's still legal and valid images.  I suspect a difference in the exif.  It is a slightly different output, but not a bug.

**Comment by pidjay** [comment]
I was actually looking into how I could have my landscape screenshots be rotated. I found out that it was supported at some point thanks to [this PR](https://github.com/fastlane-old/snapshot/pull/49/files), but that's on the old repo (and using the old UI testing framework and JS).

Assuming that `Snapshot` should output the images in their correct orientation and not just `frameit`, here is what seems to be missing (and here I have no context as to why it's only partially implemented):
- a way to let the Ruby script know how to rotate each screenshot (cf [here](https://github.com/fastlane-old/snapshot/pull/49/files#diff-7db7a5bb5e9bc1f93082a4a303640373R45-R51));
- a call to `ScreenshotRotate` from [`runner.rb`](https://github.com/fastlane-old/snapshot/pull/49/files#diff-3fb73584d1309360dcbb20bc31d82968R134)

**Comment by StefaniOSApps** [comment]
The reason is, the "XMP-Orientation" is not set by `capture_screenshots`. If you rotate the image left and than right manual and try again - it works. To solve this Issue the "XMP-Orientation" must be add by `capture_screenshots`.  ⚠️

**Comment by simonnickel** [comment]
Is there any issue created for the screenshot output to be fixed?

Should this be labelled as tool: snapshot ?

**Comment by StefaniOSApps** [comment]
@simonnickel 
As already mentioned, the **XMP Orientation** property is not written by `capture screenshots`. Therefore, there is also an bug in the presentation of the _screenshot preview_.

@janpio yes, we need the label **tool: snapshot**

**Comment by JulesMoorhouse** [comment]
Any progress on this?

**Comment by youjinp** [comment]
I've written a script to be place between `fastlane/snapshot` and `fastlane/frameit` in the meantime. Excuse my lack of bash proficiency.

```sh

while [[ "$#" -gt 0 ]]; do case $1 in
  -p|--screenshots-path) path="$2"; shift;;
  *) echo "Unknown parameter passed: $1"; exit 1;;
esac; shift; done

[[ -z "$path" ]] && { echo "Please provide the path to the screenshots with --screenshots-path"; exit 1; }

for file in $path/*/*.png
do 

    rotation=$(identify -format '%[EXIF:Orientation]' "$file")

    echo --------------------------------------------------
    echo checking file $(basename "$file")

    case $rotation in
        1)
            echo "XMP orientation is 0deg, doing nothing"
        ;;

        8)
            echo "XMP orientation is 90deg"
            echo "rotating image by 270deg CW.."
            convert "$file" -rotate 270 "$file"
            echo "resetting XMP orientation..."
            exiftool -Orientation=1 -overwrite_original -n "$file" 
            echo "done."
        ;;

        3)
            echo "XMP orientation is 180deg"
            echo "rotating image by 180deg CW.."
            convert "$file" -rotate 180 "$file"
            echo "resetting XMP orientation..."
            exiftool -Orientation=1 -overwrite_original -n "$file"
            echo "done."
        ;;

        6)
            echo "XMP orientation is 270deg"
            echo "rotating image by 90deg CW"
            convert "$file" -rotate 90 "$file"
            echo "resetting XMP orientation..."
            exiftool -Orientation=1 -overwrite_original -n "$file"
            echo "done."
        ;;
        *) echo "Unsupported XMP orientation: $rotation"; exit 1;;
    esac
done
```

usage
```sh
./script -p /path/to/screenshots
```

I hope this is helpful

**Comment by chwo** [comment]
The issue still exists with the current fastlane version `2.140.0`

**Comment by mrgrauel** [comment]
It also exists in `2.141.0`

**Comment by bixcorp** [comment]
It also exists in 2.142.0

**Comment by christoff-1992** [comment]
@youjinp - Is there any prerequisites to running the script you have kindly provided in the interim? I have tested this for the output of the snapshot files as the webpages displays them incorrectly however all the images receive the "Unsupported XMP orientation" message.

**Comment by QYL** [comment]
This problem still exists, and I wrote a private lane to deal with it before I run frameit action. Add this code in your Fastfile:

`  
  screenshot_path = "./screenshots"

  private lane :rotate_screenshot do
    screenshots = Dir.glob("#{screenshot_path}/**/*.{png,PNG}").uniq
    screenshots.each do |full_path|
        if full_path.downcase.include?("landscape")
          exec( "sips -r 90 '#{full_path}'")
        end
    end
  end
`
However, this requires you to add "landscape" to the file name of your screenshots to avoid unwanted rotation. If you want to rotate all the screenshots, just delete the "if" code block.

**Comment by QYL** [comment]
This problem still exists, and I wrote a private lane to deal with it before I run frameit action. Add this code in your Fastfile:

```
  #Relative to the Fastfile, not the same as the path to pass to frameit.
  screenshot_path = "./screenshots"

  lane :rotate_screenshots do
    screenshots = Dir.glob("#{screenshot_path}/**/*.{png,PNG}").uniq
    screenshots.each do |full_path|
        if full_path.downcase.include?("landscape")
          puts "Rotating screenshot:#{full_path}"
          system( "sips -r 90 '#{full_path}'") 
        end
    end
  end
```
However, this requires you to add "landscape" to the file name of your screenshots to avoid unwanted rotation. If you want to rotate all the screenshots, just delete the "if" code block and keep `system( "sips -r 90 '#{full_path}'")`. Also, you might need to adjust the degree you want to rotate accordingly.

**Comment by lighthouse16** [comment]
The issue still exists with the current fastlane version 2.145.0

**Comment by l1ghthouse** [comment]
The issue still exists with the current fastlane version 2.147.0

**Comment by StefaniOSApps** [comment]
always exits ...

**Comment by StefaniOSApps** [comment]
still exists
