### ISSUE TITLE
fastlane add_plugin firebase_app_distribution is failing

### ISSUE THREAD

**Issue by pollux-** [fastlane/fastlane#15485]
```
sudo fastlane add_plugin firebase_app_distribution
+------------------------+---------+------------------------+
|                       Used plugins                        |
+------------------------+---------+------------------------+
| Plugin                 | Version | Action                 |
+------------------------+---------+------------------------+
| fastlane-plugin-fireb  | 0.1.4   | firebase_app_distribu  |
| ase_app_distribution   |         | tion                   |
+------------------------+---------+------------------------+

[22:39:01]: Make sure to commit your Gemfile, Gemfile.lock and Pluginfile to version control
Installing plugin dependencies...
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/unf_ext-0.0.7.6/ext/unf_ext
/Users/sreekumarav/.fastlane/bin/bundle/bin/ruby -r ./siteconf20191012-78196-102onto.rb extconf.rb
checking for main() in -lstdc++... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/sreekumarav/.fastlane/bin/bundle/bin/$(RUBY_BASE_NAME)
	--with-static-libstdc++
	--without-static-libstdc++
	--with-stdc++lib
	--without-stdc++lib
/Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:541:in `try_link0'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:556:in `try_link'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:735:in `try_func'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:966:in `block in have_library'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:321:in `open'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:321:in `open'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:961:in `have_library'
	from extconf.rb:6:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/unf_ext-0.0.7.6/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/unf_ext-0.0.7.6 for inspection.
Results logged to /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/unf_ext-0.0.7.6/gem_make.out

An error occurred while installing unf_ext (0.0.7.6), and Bundler cannot continue.
Make sure that `gem install unf_ext -v '0.0.7.6'` succeeds before bundling.
```

I did try this also, install unf_ext -v '0.0.7.6'. No luck.

Can someone help me with this?

**Mac Os Mojave:10.14.6**

**Comment by janpio** [comment]
Did you report this at the repo of the plugin already?

**Comment by pollux-** [comment]
@janpio  I appreciate your time on this.


<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.6 (18G95)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.3                                        |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.3"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end

  desc "Deploying Beta to firbase"
      lane :distribute do
      gradle(task: "assembleRelease")
          firebase_app_distribution(
              app: "1:717023762309:android:1a7c9bca3ad336709656ec",
              testers: "sreekumar.av@ymedialabs.com, sreevijayan.ak@gmail.com",
              release_notes: "Lots of amazing new features to test out!",
              firebase_cli_path: "/usr/local/bin"
          )

      end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "com.koin.sample" # e.g. com.krausefx.app
```
</details>

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.28.3  | 💥 Check failed |


### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status  |
| ----------------------------------------- | ------- | -------------- |
| fastlane-plugin-firebase_app_distribution | 0.1.4   | 💥 Check failed |


<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| slack-notifier                            | 1.5.1        |
| atomos                                    | 0.1.3        |
| claide                                    | 1.0.3        |
| colored2                                  | 3.1.2        |
| nanaimo                                   | 0.2.6        |
| xcodeproj                                 | 1.12.0       |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| terminal-notifier                         | 1.7.1        |
| unicode-display_width                     | 1.1.3        |
| terminal-table                            | 1.7.3        |
| CFPropertyList                            | 2.3.5        |
| multipart-post                            | 2.0.0        |
| word_wrap                                 | 1.0.0        |
| tty-screen                                | 0.5.0        |
| colored                                   | 1.2          |
| commander-fastlane                        | 4.4.6        |
| faraday                                   | 0.12.1       |
| unf_ext                                   | 0.0.7.4      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20170404 |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.6        |
| gh_inspector                              | 1.1.3        |
| uber                                      | 0.0.15       |
| representable                             | 2.3.0        |
| retriable                                 | 2.1.0        |
| mime-types                                | 3.1          |
| hurley                                    | 0.2          |
| little-plugger                            | 1.1.4        |
| logging                                   | 2.2.2        |
| jwt                                       | 1.5.6        |
| memoist                                   | 0.16.0       |
| os                                        | 0.9.6        |
| signet                                    | 0.7.3        |
| googleauth                                | 0.5.1        |
| httpclient                                | 2.8.3        |
| google-api-client                         | 0.9.28       |
| json                                      | 1.8.1        |
| mini_magick                               | 4.5.1        |
| multi_xml                                 | 0.6.0        |
| rubyzip                                   | 1.3.0        |
| security                                  | 0.1.3        |
| xcpretty-travis-formatter                 | 0.0.4        |
| bundler                                   | 1.14.6       |
| faraday_middleware                        | 0.11.0.1     |
| highline                                  | 1.7.10       |
| excon                                     | 0.67.0       |
| plist                                     | 3.5.0        |
| babosa                                    | 1.0.3        |
| fastimage                                 | 2.1.7        |
| fastlane-plugin-firebase_app_distribution | 0.1.4        |
</details>


*generated on:* **2019-10-13**
</details>

**Comment by janpio** [comment]
Anecdata:

```
C:\Users\Jan\Documents\throwaway\fastlaneFirebase>fastlane add_plugin firebase_app_distribution
 [✔] 🚀
[22:29:57]: fastlane detected a Gemfile in the current directory
[22:29:57]: however it seems like you don't use `bundle exec`
[22:29:57]: to launch fastlane faster, please use
[22:29:57]:
[22:29:57]: $ bundle exec fastlane add_plugin firebase_app_distribution
[22:29:57]:
[22:29:57]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[22:29:57]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
[22:30:01]: Plugin 'fastlane-plugin-firebase_app_distribution' was added to './fastlane/Pluginfile'
[22:30:01]: It looks like fastlane plugins are not yet set up for this project.
[22:30:01]: fastlane will modify your existing Gemfile at path 'C:/Users/Jan/Documents/throwaway/fastlaneFirebase/Gemfile'
[22:30:01]: This change is necessary for fastlane plugins to work
[22:30:01]: Should fastlane modify the Gemfile at path 'C:/Users/Jan/Documents/throwaway/fastlaneFirebase/Gemfile' for
you? (y/n)
y
[22:30:09]: Successfully modified 'C:/Users/Jan/Documents/throwaway/fastlaneFirebase/Gemfile'
[22:30:09]: Make sure to commit your Gemfile, Gemfile.lock and Pluginfile to version control
Installing plugin dependencies...
'Successfully installed plugins'

C:\Users\Jan\Documents\throwaway\fastlaneFirebase>
```

Works just fine for me.

Your ruby is pretty old, maybe update?

**Comment by pollux-** [comment]
@janpio I updated the Ruby and also did this:

 `sudo gem install json -v '2.2.0' --source 'https://rubygems.org/'`

Working perfectly fine 😄   Awesome. Thank you so much
