### ISSUE TITLE
ensure_git_branch return wrong result with right branch

### ISSUE THREAD

**Issue by iTofu** [fastlane/fastlane#15481]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm trying to build app with fastlane. But a fastlane `ensure_git_branch ` action is unexpected.

##### Command executed

```shell
bundle exec fastlane testflight
```

##### Complete output when running fastlane, including the stack trace and command used

Fastfile:
```swift
func testflightLane() {
  // ...

  let version = getVersionNumber(xcodeproj: xcodeproj, target: target)
  echo(message: "App Version: \(version)")
  sh(command: "git push origin -d \(version) &>/dev/null || true")
  sh(command: "git branch -D \(version) &>/dev/null || true")
  sh(command: "git checkout -b \(version)")
  // sh(command: "git branch")
  // sh(command: "bundle exec fastlane run ensure_git_branch branch:2.36.10")
  ensureGitBranch(branch: version)

  // ...
}
```

Output:
```shell
[17:08:32]: -------------------------------------

[17:08:32]: --- Step: ensure_git_status_clean ---

[17:08:32]: -------------------------------------

[17:08:32]: $ git status --porcelain

[17:08:32]: Git status is clean, all good! 💪

[17:08:32]: --------------------------------

[17:08:32]: --- Step: get_version_number ---

[17:08:32]: --------------------------------

[17:08:32]: App Version: 2.36.10

[17:08:32]: ------------------------------------------------------------

[17:08:32]: --- Step: git push origin -d 2.36.10 &>/dev/null || true ---

[17:08:32]: ------------------------------------------------------------

[17:08:32]: $ git push origin -d 2.36.10 &>/dev/null || true

[17:08:33]: -------------------------------------------------------

[17:08:33]: --- Step: git branch -D 2.36.10 &>/dev/null || true ---

[17:08:33]: -------------------------------------------------------

[17:08:33]: $ git branch -D 2.36.10 &>/dev/null || true

[17:08:33]: -------------------------------------

[17:08:33]: --- Step: git checkout -b 2.36.10 ---

[17:08:33]: -------------------------------------

[17:08:33]: $ git checkout -b 2.36.10

[17:08:33]: ▸ Switched to a new branch '2.36.10'

[17:08:33]: -------------------------------

[17:08:33]: --- Step: ensure_git_branch ---

[17:08:33]: -------------------------------

+------------------------------------+---------------------------------------------------+

|                                      Lane Context                                      |

+------------------------------------+---------------------------------------------------+

| LANE_NAME                          | testflight                                        |

| SIGH_PROFILE_TYPE                  | app-store                                         |

| MATCH_PROVISIONING_PROFILE_MAPPING | {"xxx"=>"match AppStore xxx"} |

| GIT_REPO_WAS_CLEAN_ON_START        | true                                              |

| VERSION_NUMBER                     | 2.36.10                                           |

+------------------------------------+---------------------------------------------------+

[17:08:33]: Git is not on a branch matching `2.36.10`. Current branch is `origin/dev`! Please ensure the repo is checked out to the correct branch.
```

git log:
```
* commit a4cfc30363cbaaf14c19eea284cc43991bcd068b (HEAD -> 2.36.10, origin/dev, dev)
```

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |

| --------------------------- | ------------------------------------------- |

| OS                          | 10.14.6                                     |

| Ruby                        | 2.6.3                                       |

| Bundler?                    | true                                        |

| Git                         | git version 2.20.1 (Apple Git-117)          |

| Installation Source         | ~/.rvm/gems/ruby-2.6.3/bin/fastlane         |

| Host                        | Mac OS X 10.14.6 (18G95)                    |

| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.3/lib                |

| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |

| Is contained                | false                                       |

| Is homebrew                 | false                                       |

| Is installed via Fabric.app | false                                       |

| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |

| Xcode Version               | 10.3                                        |

### System Locale

| Variable | Value       |   |

| -------- | ----------- | - |

| LANG     | en_US.UTF-8 | ✅ |

| LC_ALL   | en_US.UTF-8 | ✅ |

| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

```ruby

// This file contains the fastlane.tools configuration

// You can find the documentation at https://docs.fastlane.tools

//

// For a list of all available actions, check out

//

//     https://docs.fastlane.tools/actions

//



import Foundation



class Fastfile: LaneFile {

  let cerURL = "xxx"



  let appID = "xxx"

  let xcodeproj = "xxx.xcodeproj"

  let target = "xxx"

  let workspace = "xxx"

  let scheme = "xxx"



  let itcUsername = "xxx"



  let acAPIToken = "xxx" // full access

  let acOwnerName = "xxx"

  let acAppName = "xxx"

  let acDSYM = "xxx.app.dSYM.zip"



  func testflightLane() {

    desc("Push a new beta build to TestFlight")



    _matchCer(type: .appstore, readonly: true, forceForNewDevices: false)



    ensureGitStatusClean()



    let version = getVersionNumber(xcodeproj: xcodeproj, target: target)

    echo(message: "App Version: \(version)")

    sh(command: "git push origin -d \(version) &>/dev/null || true")

    sh(command: "git branch -D \(version) &>/dev/null || true")

    sh(command: "git checkout -b \(version)")

    ensureGitBranch(branch: version)



    incrementBuildNumber()

    commitVersionBump(message: "Version Bump", xcodeproj: xcodeproj)

    pushToGitRemote()



    cocoapods()



    buildApp(workspace: workspace, scheme: scheme)



    uploadToTestflight(username: itcUsername)



    _appcenterUploadDSYM()

  }



  func registerDeviceLane(withOptions options: [String: String]) {

    desc("Register a new device. Passing parameters: udid:xxx name:xxx match(optional):xxx('true', 'false'(default))")



    guard let udid = options["udid"], let name = options["name"] else { return }



    registerDevice(name: name, udid: udid, username: itcUsername)



    if (options["match"] as NSString?)?.boolValue ?? false {

      _matchCer(type: .development, readonly: false, forceForNewDevices: true)

      _matchCer(type: .adhoc, readonly: false, forceForNewDevices: true)

    }

  }



  func matchCerLane(withOptions options: [String: String]) {

    desc("Match certificate. Passing parameters: type:xxx('development', 'appstore', 'adhoc') readonly(optional):xxx('true', 'false'(default))")



    guard let type = options["type"] else { return }



    _matchCer(type: type, readonly: (options["readonly"] as NSString?)?.boolValue ?? false, forceForNewDevices: true)

  }



  func appcenterUploadDSYMLane() {

    desc("Upload the dSYM file to AppCenter(https://appcenter.ms)")



    _appcenterUploadDSYM()

  }

}



extension Fastfile {

  private func _matchCer(type: CerType, readonly: Bool, forceForNewDevices: Bool) {

    _matchCer(type: type.rawValue, readonly: readonly, forceForNewDevices: forceForNewDevices)

  }



  private func _matchCer(type: String, readonly: Bool, forceForNewDevices: Bool) {

    match(type: type,

          readonly: readonly,

          appIdentifier: [appID],

          username: itcUsername,

          gitUrl: cerURL,

          forceForNewDevices: forceForNewDevices)

  }



  private func _appcenterUploadDSYM() {

    appcenterUpload(apiToken: acAPIToken,

                    ownerName: acOwnerName,

                    appName: acAppName,

                    dsym: acDSYM,

                    uploadDsymOnly: true)

  }

}



enum CerType: String {

  case development

  case appstore

  case adhoc

}



```

</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |

| -------- | ------- | ------------- |

| fastlane | 2.133.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |

| ------------------------- | ------- | ------------- |

| fastlane-plugin-appcenter | 1.4.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |

| ------------------------- | ------------ |

| did_you_mean              | 1.3.0        |

| bundler                   | 1.17.3       |

| etc                       | 1.0.1        |

| forwardable               | 1.2.0        |

| CFPropertyList            | 3.0.1        |

| concurrent-ruby           | 1.1.5        |

| i18n                      | 0.9.5        |

| minitest                  | 5.12.2       |

| thread_safe               | 0.3.6        |

| tzinfo                    | 1.2.5        |

| activesupport             | 4.2.11.1     |

| public_suffix             | 2.0.5        |

| addressable               | 2.7.0        |

| atomos                    | 0.1.3        |

| babosa                    | 1.0.3        |

| claide                    | 1.0.3        |

| fuzzy_match               | 2.0.4        |

| nap                       | 1.1.0        |

| cocoapods-core            | 1.7.5        |

| cocoapods-deintegrate     | 1.0.4        |

| cocoapods-downloader      | 1.2.2        |

| cocoapods-plugins         | 1.0.0        |

| cocoapods-search          | 1.0.0        |

| cocoapods-stats           | 1.1.0        |

| netrc                     | 0.11.0       |

| cocoapods-trunk           | 1.4.1        |

| cocoapods-try             | 1.1.0        |

| colored2                  | 3.1.2        |

| escape                    | 0.0.4        |

| fourflusher               | 2.3.1        |

| gh_inspector              | 1.1.3        |

| molinillo                 | 0.6.6        |

| ruby-macho                | 1.4.0        |

| nanaimo                   | 0.2.6        |

| xcodeproj                 | 1.12.0       |

| cocoapods                 | 1.7.5        |

| colored                   | 1.2          |

| highline                  | 1.7.10       |

| commander-fastlane        | 4.4.6        |

| declarative               | 0.0.10       |

| declarative-option        | 0.1.0        |

| digest-crc                | 0.4.1        |

| unf_ext                   | 0.0.7.6      |

| unf                       | 0.1.4        |

| domain_name               | 0.5.20190701 |

| dotenv                    | 2.7.5        |

| emoji_regex               | 1.0.1        |

| excon                     | 0.67.0       |

| multipart-post            | 2.0.0        |

| faraday                   | 0.15.4       |

| http-cookie               | 1.0.3        |

| faraday-cookie_jar        | 0.0.6        |

| faraday_middleware        | 0.13.1       |

| fastimage                 | 2.1.7        |

| jwt                       | 2.1.0        |

| memoist                   | 0.16.0       |

| multi_json                | 1.13.1       |

| os                        | 1.0.1        |

| signet                    | 0.11.0       |

| googleauth                | 0.6.7        |

| httpclient                | 2.8.3        |

| mime-types-data           | 3.2019.0904  |

| mime-types                | 3.3          |

| uber                      | 0.1.0        |

| representable             | 3.0.4        |

| retriable                 | 3.1.2        |

| google-api-client         | 0.23.9       |

| google-cloud-env          | 1.2.1        |

| google-cloud-core         | 1.3.1        |

| google-cloud-storage      | 1.16.0       |

| json                      | 2.2.0        |

| mini_magick               | 4.9.5        |

| multi_xml                 | 0.6.0        |

| plist                     | 3.5.0        |

| rubyzip                   | 1.3.0        |

| security                  | 0.1.3        |

| naturally                 | 2.2.0        |

| simctl                    | 1.6.6        |

| slack-notifier            | 2.3.2        |

| terminal-notifier         | 2.0.0        |

| unicode-display_width     | 1.6.0        |

| terminal-table            | 1.8.0        |

| tty-screen                | 0.7.0        |

| tty-cursor                | 0.7.0        |

| tty-spinner               | 0.9.1        |

| word_wrap                 | 1.0.0        |

| rouge                     | 2.0.7        |

| xcpretty                  | 0.3.0        |

| xcpretty-travis-formatter | 1.0.0        |

| fastlane-plugin-appcenter | 1.4.0        |

| psych                     | 3.1.0        |

</details>

*generated on:* **2019-10-12**

</details>

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by iTofu** [comment]
* When I run fastlane in Jenkins:
  ```
  [19:27:17]: ------------------------

  [19:27:17]: --- Step: git_branch ---

  [19:27:17]: ------------------------

  [19:27:17]: origin/dev
  ```
  ```
  // Fastfile:
  git_branch
  ```

* But if I run `fastlane run git_branch` on my terminal directly I got:
  ```
  ➜  xxx git:(2.36.10) fastlane run git_branch
  [✔] 🚀
  +--------------------+---------+------------------+
  |                  Used plugins                   |
  +--------------------+---------+------------------+
  | Plugin             | Version | Action           |
  +--------------------+---------+------------------+
  | fastlane-plugin-a  | 1.4.0   | appcenter_upload |
  | ppcenter           |         |                  |
  +--------------------+---------+------------------+

  [19:27:53]: ------------------------
  [19:27:53]: --- Step: git_branch ---
  [19:27:53]: ------------------------
  [19:27:53]: Result: 2.36.10
  ```

* And git log was:
  ```
  * commit a4cfc30363cbaaf14c19eea284cc43991bcd068b (HEAD -> 2.36.10, origin/dev, dev)
  ```

**Comment by janpio** [comment]
The output and code you posted in your initial message do not match.

**Comment by iTofu** [comment]
Sorry for the code, I've fixed it now.

About the second message, I didn't switch the branches, action 'git_branch' told me I was on branch 'origin/dev', but same action told me I was on branch '2.36.10' if I put it in Jenkins. So I guess maybe I did something wrong for Jenkins configuration.
