### ISSUE TITLE
Could not find option 'code_signing_identity' in the list of available options: xcodeproj, profile, target_filter, build_configuration_filter, build_configuration, certificate

### ISSUE THREAD

**Issue by pratikq23** [fastlane/fastlane#15498]
### Question Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
update_project_provisioning configuration error

#### Question Description
Could not find option 'code_signing_identity' in the list of available options: xcodeproj, profile, target_filter, build_configuration_filter, build_configuration, certificate

**Comment by skannatrib** [comment]
I am seeing the same issue after updating to fastlane 2.134.0 while running the 'update_project_provisioning' command.

It also says 
'You passed invalid parameters to 'update_project_provisioning'.
Check out the error below and available options by running `fastlane action update_project_provisioning`.

Not sure why it can't find the 'code_signing_identity' option.

**Comment by skdev03** [comment]
I am seeing the same issue after updating to fastlane 2.134.0 while running 'update_project_provisioning' command. It used to work fine before.

It also says
'You passed invalid parameters to 'update_project_provisioning'.
Check out the error below and available options by running `fastlane action update_project_provisioning`.

Not sure why it can not find the 'code_signing_identity' option.

**Comment by janpio** [comment]
Do you have a code example that can be used to reproduce this?

**Comment by skdev03** [comment]
code_signing_identity = 'iPhone Developer'

desc "Updates the xcode settings to match the correct provisioning profiles for a specified target"
  private_lane :update_provisioning_settings do |options|
    update_project_provisioning(
      xcodeproj: "#{scheme}/#{scheme}.xcodeproj",
      profile: options[:profile_path],
      target_filter: ".*#{options[:target_filter]}.*", # matches name or type of a target
      build_configuration: build_configuration,
      code_signing_identity: code_signing_identity
    )
  end

Fastlane version:
fastlane -v
fastlane installation at path:
/Users/sk/.rvm/gems/ruby-2.4.1@tronc/gems/fastlane-2.134.0/bin/fastlane
-----------------------------
[✔] 🚀 
fastlane 2.134.0

**Comment by skdev03** [comment]
I have a sample code.

code_signing_identity = 'iPhone Distribution'
build_configuration = 'Release'

desc "Updates the xcode settings to match the correct provisioning profiles for a specified target"
  private_lane :update_provisioning_settings do |options|
    update_project_provisioning(
      xcodeproj: "#{scheme}/#{scheme}.xcodeproj",
      profile: options[:profile_path],
      target_filter: ".*#{options[:target_filter]}.*", # matches name or type of a target
      build_configuration: build_configuration,
      code_signing_identity: code_signing_identity
    )
  end

**Comment by skdev03** [comment]
Figured out the issue.

"brew cask install fastlane" installed fastlane 2.28.3 instead of 2.134.0. Not sure what is the issue with "update_project_provisioning" in fastlane 2.28.3. 

"sudo gem install fastlane -NV" installed the latest version of fastlane, but it is at a different path (/Users/sk/.rvm/gems/ruby-2.4.1/gems/fastlane-2.134.0/bin/fastlane) than the path set by brew cask install fastlane.

So exporting the path to /Users/sk/.rvm/gems/ruby-2.4.1/gems/fastlane-2.134.0/bin/fastlane fixed the issue.

export PATH="$HOME/.rvm/gems/default/bin:$PATH"

**Comment by skdev03** [comment]
This issue seems to be a little bit related to https://github.com/fastlane/fastlane/issues/15562 too.
