### ISSUE TITLE
Fastlane Change Build.Gradle Permissions

### ISSUE THREAD

**Issue by DavidUps** [fastlane/fastlane#15510]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When I execute Fastlane N, Fastlane modificate the  permissions of app/build.gradle, so I can't compile.
##### Command executed

Fastlane beta (Generate version for Google)
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> /Users/N.java:53: error: cannot find symbol
import com.N.DaggerNApplicationComponent;
                                                      ^
  symbol:   class DaggerYudonpayApplicationComponent
  location: package com.N.di.components
Note: Processing class NEntity
Note: Processing class YEntity
Note: Processing class ZEntity
Note: Processing class CEntity
Note: Processing class Vntity
Note: Creating DefaultRealmModule
Note: /Users/N/platform/utils/TouchID.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
3 warnings

> Task :app:compileProDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileProDebugJavaWithJavac'.
> java.lang.NoClassDefFoundError: javax/annotation/Generated

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
32 actionable tasks: 8 executed, 24 up-to-date </pre>
</details>

### Environment

<details>
  <pre> 
### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15                                                          |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.21.0 (Apple Git-122)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15 (19A583)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.1                                                           |

### System Locale

 </pre>
</details>

**Comment by janpio** [comment]
Please make sure your issue includes enough information for us to help you. Currently your `fastlane env` information and the actual _full_ output is missing.

**Comment by DavidUps** [comment]
i can´t give this information sorry
