### ISSUE TITLE
Xcode 11 error: exportArchive: IPA processing failed

### ISSUE THREAD

**Issue by Greeeeyyyss** [fastlane/fastlane#15523]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Command executed
fastlane gym --verbose --export_method ad-hoc

##### Complete output when running fastlane, including the stack trace and command used
```
 xcodebuild -exportArchive -exportOptionsPlist /var/folders/5w/qzqcg8655_v42j05r_v6mm7c0000z_/T/gym_config20191021-32863-k44hyr.plist -archivePath '/Users/mgarcia/Library/Developer/Xcode/Archives/2019-10-21/OjO 2019-10-21 11.35.09.xcarchive' -exportPath /var/folders/5w/qzqcg8655_v42j05r_v6mm7c0000z_/T/gym_output20191021-32863-1jhav88
2019-10-21 11:42:22.492 xcodebuild[38783:179387] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/5w/qzqcg8655_v42j05r_v6mm7c0000z_/T/OjO QA_2019-10-21_11-42-22.491.xcdistributionlogs'.
error: exportArchive: IPA processing failed

Error Domain=IDEFoundationErrorDomain Code=1 "IPA processing failed" UserInfo={NSLocalizedDescription=IPA processing failed}

** EXPORT FAILED **
ERROR [2019-10-21 11:42:25.69]: Exit status: 70
```

Looking at the IDEDistributionPipeline.log:

```
/Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2031:in `GetMachOImagesFromOToolInfoForFile'
/Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2116:in `MakeFileSystemNode'
/Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2144:in `block in MakeFileSystemNode'
/Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2143:in `each'
/Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2143:in `MakeFileSystemNode'
/Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2144:in `block in MakeFileSystemNode'
/Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2143:in `each'
/Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2143:in `MakeFileSystemNode'
/Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2144:in `block in MakeFileSystemNode'
/Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2143:in `each'
/Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2143:in `MakeFileSystemNode'
/Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1783:in `initialize'
/Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2843:in `new'
/Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2843:in `ProcessIPA'
/Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:3811:in `<main>'
Removing temporary directory /var/folders/5w/qzqcg8655_v42j05r_v6mm7c0000z_/T/ipatool20191021-11655-1qwwafg...
$ rm -r /var/folders/5w/qzqcg8655_v42j05r_v6mm7c0000z_/T/ipatool20191021-11655-1qwwafg
2019-10-21 01:17:52 +0000 [MT] /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool exited with 1
2019-10-21 01:17:52 +0000 [MT] ipatool JSON: {
    alerts =     (
                {
            code = 3620;
            description = "Configuration issue: platform AppleTVSimulator.platform doesn't have any non-simulator SDKs; ignoring it";
            info =             {
            };
            level = WARN;
        },
                {
            code = 3620;
            description = "Configuration issue: platform WatchSimulator.platform doesn't have any non-simulator SDKs; ignoring it";
            info =             {
            };
            level = WARN;
        },
                {
            code = 3620;
            description = "Configuration issue: platform iPhoneSimulator.platform doesn't have any non-simulator SDKs; ignoring it";
            info =             {
            };
            level = WARN;
        }
    );
}

```
### Environment

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.4                                     |
| Ruby                        | 2.6.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0 (Apple Git-122)          |
| Installation Source         | ~/.rbenv/versions/2.6.2/bin/fastlane        |
| Host                        | Mac OS X 10.14.4 (18E226)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.2/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.1                                        |

**Comment by xinsight** [comment]
I'm experiencing a similar issue. Seems to be related to architectures.

There are some warnings in with `ipatool` - one related to `archs` which is suspicious.

```
2019-10-21 16:34:27 +0000 [MT] Running /Applications/Xcode11GM2/Xcode.app/Contents/Developer/usr/bin/ipatool '/var/folders/sx/d2l3hmnd5p367ljm7wgw3xj00000gp/T/XcodeDistPipeline.~~~SebyB4/Root' '--json' '/var/folders/sx/d2l3hmnd5p367ljm7wgw3xj00000gp/T/ipatool-json-filepath-~~~AtY9QQ' '--output' '/var/folders/sx/d2l3hmnd5p367ljm7wgw3xj00000gp/T/IDEIPAProcessor.AppThinning.~~~G3Wx6l' '--toolchain' '/Applications/Xcode11GM2/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr' '--platforms' '/Applications/Xcode11GM2/Xcode.app/Contents/Developer/Platforms' '--app-store-tools-build-version' '11A420a' '--compile-bitcode'
2019-10-21 16:34:27 +0000  ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
2019-10-21 16:34:27 +0000  /Applications/Xcode11GM2/Xcode.app/Contents/Developer/usr/bin/ipatool:1326: warning: assigned but unused variable - archs
2019-10-21 16:34:27 +0000  /Applications/Xcode11GM2/Xcode.app/Contents/Developer/usr/bin/ipatool:3486: warning: shadowing outer local variable - c
```

And then later on ipatool craps out because it expects 4 different architectures (tv, watch, iphone, ipad?) but only finds one (iphone).

```
2019-10-21 16:34:27 +0000  Scanning IPA...
2019-10-21 16:34:29 +0000  Assertion failed: Expected 4 archs in otool output:
```

**Comment by xinsight** [comment]
Pretty sure, this issue is related to a weird version of ruby (`ruby 2.3.7p456` in my case).

**Comment by jeffremer** [comment]
Something similar to this just happened to me. In my case it was related to adding a new framework via Carthage. The issue ended up being that our project's build phases had previously been slightly misconfigured and the Copy Frameworks build phase was being called after the Run Script build phase that uses Carthage's `copy-frameworks` command to copy and also strip frameworks of the simulator architectures (i386).

**Comment by xinsight** [comment]
Thank you @jeffremer! Your build phases tip was key. Some joker added a carthage module as an "embedded framework" after `carthage copy-frameworks` and that was causing `ipatool` to barf. I just moved the embedded framework to the copy frameworks steps and the error is gone.

**Comment by Greeeeyyyss** [comment]
@jeffremer  @xinsight I found out the framework that was causing this issue. Apparently it was mentioned in the logs. It was CardConnectSDK which has x86_64 arch that is in embedded framework, if removed the error goes away. Thank you for your insights. I'll be closing this ticket.

**Comment by ernichechelski** [comment]
I just want to thank you. This post save my life 😅

**Comment by nharbo** [comment]
I know it's kinda what insight says, but I had a bit of a hard time understanding what to do.
For me I had a Carthage dependency added to a module (target) under "Embed Frameworks", which it shouldn't be. So I removed this, and now it works.
You can see in the log from the Organizer what dependency that fails - for me it was looking like this:
```
Scanning IPA...
2019-11-29 09:32:10 +0000  Assertion failed: Expected 4 archs in otool output:
/var/folders/h4/2jg9lmp167n9qzmld14hxf400000gn/T/IDEDistributionOptionThinning.~~~9JfkuN/Payload/xxxxx.app/Frameworks/{YOUR TARGET}.framework/Frameworks/xxxxx.framework/xxxxx:
Mach header

```

**Comment by miktav** [comment]
My app included my framework using Carthage. My framework included a binary framework (TwilioChatClient.framework), also using Carthage. This binary framework was included in both the "Link Binary With Libraries" and "Embed Frameworks" sections of my framework.

My app build failed with "IPA processing failed" and "Expected 4 archs in otool output". 

In order to fix my app build, I had to remove the binary framework (TwilioChatClient.framework) from the "Embed Frameworks" section of my framework.
