### ISSUE TITLE
Fastlane 2.134.0 try to get signet 12.0

### ISSUE THREAD

**Issue by Gabriel-diez** [fastlane/fastlane#15522]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Fastlane is still trying to get Signet version 12.0 instead of 11.0 on ruby 2.3 on bundle install or update.
If you clone fastlane via github and use bundle install, it use the correct signet version, otherwise as dependency in a Gemfile is still trying to get version 12.0 of Signet.

##### Command executed

```
> bundle install
> bundle update
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>

```
> bundle install
Gem::InstallError: signet requires Ruby version >= 2.4.0.
An error occurred while installing signet (0.12.0), and Bundler cannot continue.
Make sure that gem install signet -v '0.12.0' --source 'https://rubygems.org/' succeeds before bundling.

> In Gemfile:
> fastlane was resolved to 2.134.0, which depends on
> google-cloud-storage was resolved to 1.16.0, which depends on
> google-api-client was resolved to 0.23.9, which depends on
> googleauth was resolved to 0.6.7, which depends on signet

```
 </pre>
</details>

### Environment

<details>
  <pre>
I am using ruby 2.3.8 on ubuntu.

```
> ruby -v
ruby 2.3.8p459 (2018-10-18 revision 65136) [x86_64-linux]
```

</pre>
</details>

**Comment by Sega-Zero** [comment]
Came here with the same issue. 
```ruby
Gem::RuntimeRequirementNotMetError: signet requires Ruby version >= 2.4.0. The
current ruby version is 2.3.1.112.
An error occurred while installing signet (0.12.0), and Bundler cannot continue.
Make sure that `gem install signet -v '0.12.0' --source 'http://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  fastlane was resolved to 2.134.0, which depends on
    google-cloud-storage was resolved to 1.16.0, which depends on
      google-api-client was resolved to 0.23.9, which depends on
        googleauth was resolved to 0.6.7, which depends on
          signet

```

I don't use google cloud storage, why would I need to upgrade my macos default ruby 2.3.1 to 2.4.0?

**Comment by janpio** [comment]
cc @joshdholtz

**Comment by dazuma** [comment]
signet 0.12.0 requires Ruby 2.4 or later, but signet 0.11.0 remains compatible with older Rubies. If you are using bundler, run `bundle update` (not `bundle install` or `bundle update fastlane`) to ensure your entire bundle (including upstream dependencies like signet) is locked to versions that are compatible with your current Ruby.

**Comment by Sega-Zero** [comment]
@dazuma `bundle update` will probably work on a local machine, but what should we do when using Travis-CI for example, which implicitly installs gems on launch using `bundle install --jobs=3 --retry=3`? 
Also, what about clean install on a new machine with ruby 2.3?

**Comment by dazuma** [comment]
In that case, avoid checking `Gemfile.lock` into source control. `bundle install` will act like `bundle update`—i.e. it will do a full dependency resolution—if there is no `Gemfile.lock` present. Same thing with a clean install with Ruby 2.3 (i.e. assuming there is no `Gemfile.lock` file present initially): an initial `bundle install` should work just fine. Generally, I suspect you're running into these problems because someone locked the bundle using a newer >=2.4 Ruby, and then you're trying to reuse the same `Gemfile.lock` on Ruby 2.3.

**Comment by Sega-Zero** [comment]
I, personally, never put a lock file to version control. And I had a failure above when trying to run the build on a ci machine with ruby 2.3

**Comment by Gabriel-diez** [comment]
@dazuma the outpout I posted in the issue is a fresh install of fastlane using bundle install that I did I to replicate the issue I have on my CI and It doesn't work.

**Comment by dazuma** [comment]
Does the CI machine build with multiple ruby versions using the same git checkout? If it's running tests with a newer Ruby version (e.g. 2.6), and then switches to an older version (e.g. 2.3) then you must either force your CI to run `bundle update` _instead of_ `bundle install`, _or_ you need to clean up the `Gemfile.lock` before switching to the next Ruby version. In general, Gemfile.lock files may not be compatible if you switch to a different version of Ruby (for a variety of reasons), and so you need to delete it or use `bundle update` to rebuild it.

@Gabriel-diez you said: "I also try "bundle update" without Gemfile.lock on my CI and both commands don't work." Are you sure the error happened when you ran `bundle update`, or did it actually happen when your CI service ran `bundle install`? If it did happen when you ran `bundle update`, can you post the error? It might be a different problem.
