### ISSUE TITLE
there is no web session to update

### ISSUE THREAD

**Issue by y0ung1019** [fastlane/fastlane#15534]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I use fastlane for upload testflight.
So, a make a beta script as below(fastlane env)
I don't know why fastlane doesn't load web session of my apple connect account.

I want to know the method to test appstore connect using fastlane.

##### Command executed

`fastlane beta`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [[15:35:20]: -------------------------------------------------
[15:35:20]: --- Step: Verifying required fastlane version ---
[15:35:20]: -------------------------------------------------
[15:35:20]: Your fastlane version 2.28.3 matches the minimum requirement of 2.28.3  ✅
[15:35:20]: ------------------------------
[15:35:20]: --- Step: default_platform ---
[15:35:20]: ------------------------------
[15:35:20]: Driving the lane 'ios beta' 🚀
[15:35:20]: -------------------
[15:35:20]: --- Step: match ---
[15:35:20]: -------------------
[15:35:20]: Successfully loaded '/Users/Workspace/project path/fastlane/Matchfile' 📄

+---------+--------------------------------------+
|  Detected Values from './fastlane/Matchfile'   |
+---------+--------------------------------------+
| git_url | github url |
|         |                     |
+---------+--------------------------------------+

+-----------------------+--------------------------------------+
|                   Summary for match 2.28.3                   |
+-----------------------+--------------------------------------+
| type                  | appstore                             |
| git_url               | git hub url |
|                       |                     |
| git_branch            | master                               |
| app_identifier        | my identifier                 |
| keychain_name         | login.keychain                       |
| readonly              | false                                |
| verbose               | false                                |
| force                 | false                                |
| skip_confirmation     | false                                |
| shallow_clone         | false                                |
| force_for_new_devices | false                                |
| skip_docs             | false                                |
| platform              | ios                                  |
+-----------------------+--------------------------------------+

[15:35:20]: Cloning remote git repo...
[15:35:23]: 🔓  Successfully decrypted certificates repo
[15:35:23]: To not be asked about this value, you can specify it using 'username'
[15:35:23]: Your Apple ID Username: my id
[15:35:29]: Verifying that the certificate and profile are still valid on the Dev Portal...
Multiple teams found on the Developer Portal, please enter the number of the team you want to use:
1) company (Company/Organization)
2) indivisual (Individual)
1
[15:35:33]: Installing certificate...

+-------------------+-----------------------------------------------------+
|                          Installed Certificate                          |
+-------------------+-----------------------------------------------------+
| User ID           | company                                          |
| Common Name       | iPhone Distribution: company |
| Organisation Unit | company                                          |
| Organisation      | company                                   |
| Country           | US                                                  |
| Start Datetime    | Oct 22 11:30:35 2019 GMT                            |
| End Datetime      | Oct 21 11:30:35 2020 GMT                            |
+-------------------+-----------------------------------------------------+

[15:35:34]: Installing provisioning profile...

+---------------------+------------------------+------------------------+
|                    Installed Provisioning Profile                     |
+---------------------+------------------------+------------------------+
| Parameter           | Environment Variable   | Value                  |
+---------------------+------------------------+------------------------+
| App Identifier      |                        | identi    |
| Type                |                        | appstore               |
| Platform            |                        | ios                    |
| Profile UUID        | sigh_xyz.. | 336378e6-6df8-4c3f-9d  |
|                     | ace_appstore           | 12-2ecb9156024a        |
| Profile Name        | sigh_xyz.. | match AppStore         |
|                     | ace_appstore_profile-  |    |
|                     | name                   |                        |
| Profile Path        | sigh_xyz.. | /Users//Libra  |
|                     | ace_appstore_profile-  | ry/MobileDevice/Provi  |
|                     | path                   | sioning                |
|                     |                        | Profiles/336378e6-6df  |
|                     |                        | 8-4c3f-9d12-2ecb91560  |
|                     |                        | 24a.mobileprovision    |
| Development Team ID | sigh_xyz.. |             |
|                     | ace_appstore_team-id   |                        |
+---------------------+------------------------+------------------------+

[15:35:35]: All required keys, certificates and provisioning profiles are installed 🙌
[15:35:35]: Setting Provisioning Profile type to 'app-store'
[15:35:35]: -------------------
[15:35:35]: --- Step: pilot ---
[15:35:35]: -------------------
[15:35:35]: To not be asked about this value, you can specify it using 'username'
[15:35:35]: Your Apple ID Username: id
[15:35:39]: Login to iTunes Connect (id)
Multiple iTunes Connect teams found, please enter the number of the team you want to use:
Note: to automatically choose the team, provide either the iTunes Connect Team ID, or the Team Name in your fastlane/Appfile:
Alternatively you can pass the team name or team ID using the `FASTLANE_ITC_TEAM_ID` or `FASTLANE_ITC_TEAM_NAME` environment variable

  itc_team_id ""

or

  itc_team_name "company"

1) company ()
2) indivisual ()
1
+-------------------+-----------+
|         Lane Context          |
+-------------------+-----------+
| DEFAULT_PLATFORM  | ios       |
| PLATFORM_NAME     | ios       |
| LANE_NAME         | ios beta  |
| SIGH_PROFILE_TYPE | app-store |
+-------------------+-----------+
[15:35:45]: there is no web session to update

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying required  | 0           |
|      | fastlane version    |             |
| 2    | default_platform    | 0           |
| 3    | match               | 14          |
| 💥   | pilot               | 10          |
+------+---------------------+-------------+

[15:35:45]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  The request could not be completed because: Unauthorized Access
   https://github.com/fastlane/fastlane/issues/15411 [open] 19 💬
   a day ago

➡️  iTMSTransporter using Signiant upload method even with `-t DAV` override
   https://github.com/fastlane/fastlane/issues/15375 [open] 40 💬
   21 hours ago

➡️  Changelog not generating
   https://github.com/fastlane/fastlane/issues/15141 [closed] 9 💬
   3 weeks ago

and 33 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09there%20is%20no%20web%20session%20to%20update&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.

[!] The request could not be completed because:
	there is no web session to update] </pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0 (Apple Git-122)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.6 (18G95)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.3"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
#     cocoapods
#  carthage
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(type: "appstore") # more information: https://codesigning.guide
    #gym(scheme: "myScheme") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "myScheme") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "my identifier" # The bundle identifier of your app
apple_id "my id" # Your Apple email address

team_id "my team id" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.28.3  | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.13.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.17.0       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.13.1       |
</details>

*generated on:* **2019-10-23**
</details> </pre>
</details>

**Comment by y0ung1019** [comment]
I uninstall fastlane 
`brew cask uninstall fastlane`
and re init fastlane
it works for me.

**Comment by anthlasserre** [comment]
Still have the same error...

**Comment by y0ung1019** [comment]
I think reinstall fastlane using ruby install.
`sudo gem install fastlane -NV`
after update ruby version my ruby version is 
`ruby 2.6.5p114`

**Comment by anthlasserre** [comment]
I think it's because I installed it with `brew cask install fastlane`...
Maybe it can compromise fastlane installation because `brew cask install fastlane` use gem to install it finally. I would be better to install it directly by gem.
I have fixed the error like this:
- Uninstall fastlane
`brew cask uninstall fastlane`
- Install fastlane by gem
`sudo gem install fastlane -NV`
- Add this lines in ~/.bash_profile
`export FASTLANE_PATH="/usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/bin"`
`export PATH="$FASTLANE_PATH:$PATH"`
`source ~/.bash_profile`
And now I have the latest version 🎉

**Comment by Mammadbayli** [comment]
@anthlasserre this solved the problem!

**Comment by joelrorseth** [comment]
I ran into the same issue. It seems the Homebrew installation is very old https://github.com/fastlane/fastlane/issues/15496, and I ran into several other inexplicable issues over the last few days.

Reinstalling fastlane via Ruby @anthlasserre worked for me, although I did not need to add `FASTLANE_PATH` since I am using rvm.

**Comment by atereshkov** [comment]
Worked for me @anthlasserre

**Comment by linder3hs** [comment]
thanks
