### ISSUE TITLE
Is there any way to execute fastlane without user interaction?

### ISSUE THREAD

**Issue by sk8darr** [fastlane/fastlane#15537]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Documentation or any way to do it

#### Question Description
Is there any way to use the fastlane script without waiting for user interaction?
Something like:
`bundle exec fastlane init -pl android -k /path/to/json -p com.company.app` etc
where -pl is platform, -k the path to json file, -p the package name, etc.
or can i write manually the config files that fastlane init generates?

### fastlane env
[fastlane_env.txt](https://github.com/fastlane/fastlane/files/3764317/fastlane_env.txt)

**Comment by debeltranc** [comment]
Absolutely! that's how Fastlane runs in scripts and [Continuous Integrations tools](https://docs.fastlane.tools/best-practices/continuous-integration/)!
You can find help in the command line using `fastlane action <youraction>` and checking at the [documentation article of the action you're interested in](https://docs.fastlane.tools/actions/), normally in the docs you can find examples. Some parameters are also CLI parameters or Environment Variables, or both.

**Comment by sk8darr** [comment]
Thanks.

But specifically with the init function. Is anything else generated apart from the Appfile and FastFile files? or can I generate the files manually?

**Comment by debeltranc** [comment]
In that case no, because `fastlane init` purpose is to guide you through the creation of some files Fastlane needs to work, which will require a little bit of fine tuning and in the end to be commited to a source code repository. Also is intended to be a one time thing.

**Comment by sk8darr** [comment]
So, there is no way to do the whole fastlane process with a single click and a form (a frontend web page for fastlane) without modifying the source code...
That is the real reason for my question.

**Comment by janpio** [comment]
The only thing `fastlane init` does is that it creates some files in the end after asking you a few questions - you so can totally just create the files manually and have the same end result.

**Comment by sk8darr** [comment]
Yes, I tried to create the files manually and it worked perfectly. Thank you!
