### ISSUE TITLE
Android    keystore file at sub-folder -- need two copy keystore !!??

### ISSUE THREAD

**Issue by CMingTseng** [fastlane/fastlane#15550]
this is my project structure

 .
├── MyApplication
    ├── app
    ├── fastlane
    ├── keystore
     |         ├── mykey.jks
    └── gradle

my  Appfile profile @ fastlane 

_________
ENV["KEYSTORE_PATH"]="keystore/mykey.jks"
______

my app/build.gradle 

____
signingConfigs {
        debug {
            storeFile file("../keystore/debug.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }
        release {
            storeFile file("../keystore/release.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }
    }
__

but when i run fastlane build  get error

the profile can not pass build 

it mean that  fastlane need keystore  at two location !! ??

i try ti fixed  ENV["KEYSTORE_PATH"]="keystore/mykey.jks"

like : 

if 
../keystore/mykey.jks   <-- show error path { /users/me/workspace/myapplicatin/../keystore/mykey.jks } !!?

else if  

\keystore/mykey.jks   <-- show error path { /users/me/workspace/myapplicatin/app/keystore/mykey.jks } !!?

else if

/keystore/mykey.jks   <-- show error path { /users/me/workspace/myapplicatin/keystore/mykey.jks } !!?

else 

app/keystore/mykey.jks <-- show error path { /users/me/workspace/myapplicatin/app/app/keystore/mykey.jks } !!?

those error  mean that    i must put two keystore  folder ? ( one is level the same app  , one is app sub-folder !! )

i try  it !!  (two keystore folder  ) 

the  fastlane build pass !!!

what is wrong ?

THX

**Comment by janpio** [comment]
None of this seems to be related to Fastlane. What action are you using? What is your `fastlane env` output? What error are you getting by fastlane?
