### ISSUE TITLE
What is max length and valid characters for upload_to_testflight changelog?

### ISSUE THREAD

**Issue by aquacode** [fastlane/fastlane#15559]
### Question Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

This refers to fastlane action upload_to_testflight changelog parameter.
I received the following error:

Could not set changelog: An attribute value has invalid text. - Text for whatsNew contains invalid characters/formats.

I cannot locate documentation on the maximum length and valid characters allowed.

**Comment by aquacode** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15                                       |
| Ruby                        | 2.6.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.21.0 (Apple Git-122)          |
| Installation Source         | ~/.rbenv/versions/2.6.1/bin/fastlane        |
| Host                        | Mac OS X 10.15 (19A602)                     |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2r  26 Feb 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.1                                        |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform(:ios)

platform :ios do

  desc "iOS Fastlane for builds and release"

  before_all do
    setup_circle_ci
  end

  lane :adhoc do
    match(app_identifier: ["<REDACTED"], type: "adhoc", readonly: true)
    gym(
      scheme: "<REDACTED",
      export_method: "ad-hoc",
      configuration: "Adhoc"
    )
  end

  lane :release do
    match(app_identifier: ["<REDACTED"], type: "appstore", readonly: true)
    gym(scheme: "<REDACTED", export_method: "app-store")
    betweenValues = sh("head", "-n", "1", "../releaseinfo")
    puts betweenValues
    changelog = changelog_from_git_commits(between: "#{betweenValues}", merge_commit_filtering: "exclude_merges", date_format: "short")
    upload_to_testflight(changelog: changelog)
    newBuildNumber = increment_build_number(xcodeproj: "<REDACTED")
    commit_version_bump(
        xcodeproj:"<REDACTED",
        message:"[skip ci] <REDACTED>"
    )
    push_to_git_remote
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("<REDACTED") # The bundle identifier of your app
apple_id("<REDACTED") # Your Apple email address

itc_team_id("<REDACTED") # App Store Connect Team ID
team_id("<REDACTED") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.134.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 1.17.2       |
| etc                       | 1.0.1        |
| forwardable               | 1.2.0        |
| CFPropertyList            | 3.0.1        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.67.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.17.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.14.1       |
| os                        | 1.0.1        |
| signet                    | 0.12.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.1009  |
| mime-types                | 3.3          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>


*generated on:* **2019-10-28**
</details>

**Comment by mollyIV** [comment]
Hello @aquacode 👋 

> I cannot locate documentation on the maximum length and valid characters allowed.

According to the documentation from [App Store Connect Help](https://help.apple.com/app-store-connect/en.lproj/static.html), the limit is **4000** characters:

> What’s New in this Version | A description of the changes in this version of the app such as new features, UI improvements, or bug fixes. Limited to 4000 characters.

I also had a look at our codebase: 

https://github.com/fastlane/fastlane/blob/dce03348675149d986224d99e39e1fbd36bbcf3f/pilot/lib/pilot/build_manager.rb#L222-L231

The changelog is truncated when it is longer than 4000 characters.

Unfortunately I didn't find an info about valid characters allowed.

**Comment by aquacode** [comment]
Thanks. This is the closest thing to documentation for that field that I was able to find as well:
https://help.apple.com/app-store-connect/#/devf29afbb74
Here I notice that for the Description field for releasing the app the following text:

> A description of the app, detailing the features and functionality. Limited to 4000 characters. The description should be in plain text, with line breaks as needed. HTML format is not supported.

I suppose one can assume it is the same requirement for "What's New in this Version" but I'm not certain.

Also, I could not find any documentation on whether or not "What to Test" actually _becomes_ "What's New in this Version" but it seems to be the case.

**Comment by aquacode** [comment]
Only additional information I was able to find regarding this issue is that certain special characters (not documented) including HTML formatting is NOT allowed in the changelog string.
