### ISSUE TITLE
[Question] Skip action-summaries

### ISSUE THREAD

**Issue by tscharke** [fastlane/fastlane#15569]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
In need this in a general case. Means for `match`, `gym`, `cocopods`, aso.

#### Question Description
I wanna skip **all action-summaries** to avoid displaying detail information on my CI-System.
During my search here in the code, I found the environment-variable `FASTLANE_SKIP_ACTION_SUMMARY`. Unfortunately it was not possible for me to set them correctly to get an effect. I tried…

- `ENV['FASTLANE_SKIP_ACTION_SUMMARY'] = true`
- `ENV['FASTLANE_SKIP_ACTION_SUMMARY'] = "true"`
- `ENV['FASTLANE_SKIP_ACTION_SUMMARY'] = 1`
- `ENV['FASTLANE_SKIP_ACTION_SUMMARY'] = "1"`
- I do it on top of my `FASTFILE`, before calling an action (e.g. `match`)

it didn't work out.

Can someone tell me what I'm doing wrong? Or is this environment-variable no longer available?

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.18.0                          |
| Installation Source         | ~/.rvm/gems/ruby-2.3.3/bin/fastlane         |
| Host                        | Mac OS X 10.14.6 (18G103)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.3/lib                |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.3                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
opt_out_usage

platform :ios do
  private_lane :ci_certificates do
    create_keychain(
      name: ENV['CI_KEYCHAIN_NAME'],
      password: ENV['CI_KEYCHAIN_PASSWORD'],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )
    match(
      keychain_name: ENV['CI_KEYCHAIN_NAME'],
      keychain_password: ENV['CI_KEYCHAIN_PASSWORD'],
      app_identifier: ENV['APP_IDENTIFIER'],
      type: ENV['MATCH_TYPE'],
      readonly: true,
      shallow_clone: true,
      verbose: false,
      clone_branch_directly: true,
    )
  end

  private_lane :certificates do
    match(
      app_identifier: ENV['APP_IDENTIFIER'],
      type: ENV['MATCH_TYPE'],
      readonly: true,
      shallow_clone: true,
      verbose: false,
      clone_branch_directly: true,
    )
  end

  private_lane :build do
    # Run lane 'ci_certificates' or 'certificates' depends on the system we’re using
    ENV['CI'] ? ci_certificates : certificates

    cocoapods(
      repo_update: true,
      podfile: "./ios/Podfile"
    )

    # Build the MyAwesomeProject
    gym(
      scheme: 'App1',
      workspace: './ios/App1.xcworkspace',
      silent: true,
      clean: true,
      configuration: 'Development',
      output_directory: './fastlane/builds/',
      output_name: 'App1.ipa',
      export_options: {
          method: "development",
          provisioningProfiles: {
              ENV['APP_IDENTIFIER'] => ENV["sigh_#{ENV['APP_IDENTIFIER']}_#{ENV['MATCH_TYPE']}_profile-name"],
          }
      },
    )
  end


  lane :buildAndShip do
    build
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

app_identifier ENV['APP_IDENTIFIER']
apple_id ENV['APPLE_ID']
itc_team_id ENV['APPLE_TEAM_ID']

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.134.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday                   | 0.17.0       |
| faraday_middleware        | 0.13.1       |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| tty-screen                | 0.7.0        |
| json                      | 2.2.0        |
| io-console                | 0.4.5        |
| excon                     | 0.67.0       |
| CFPropertyList            | 3.0.1        |
| plist                     | 3.5.0        |
| atomos                    | 0.1.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| claide                    | 1.0.3        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| babosa                    | 1.0.3        |
| fastimage                 | 2.1.7        |
| bundler                   | 2.0.2        |
| unicode-display_width     | 1.6.0        |
| dotenv                    | 2.7.5        |
| addressable               | 2.7.0        |
| os                        | 1.0.1        |
| psych                     | 2.1.0        |
| mime-types                | 3.3          |
| mime-types-data           | 3.2019.0904  |
</details>

*generated on:* **2019-10-30**
</details>

**Comment by Katsz** [comment]
It in fact supported. And it does work for me each time. But neither `ENV['FASTLANE_SKIP_ACTION_SUMMARY'] = true` nor `ENV['FASTLANE_SKIP_ACTION_SUMMARY'] = 1` are valid statements, which makes me wonder..

Can you provide exact place where you putting those lines?

**Comment by Katsz** [comment]
And while we are on it, if 
```bash
$ fastlane buildAndShip
``` 
shows summary, will
```bash
$ FASTLANE_SKIP_ACTION_SUMMARY=1 fastlane buildAndShip
```  
behave exactly the same?

**Comment by tscharke** [comment]
@Katsz I have to call `fastlane ios buildAndShip` and yes, both commands showing the summary.

I set the environment-variable in in different places inside my `Fastfile`.

Some examples:
- On top in the very first line.
- Inside my public lane and before calling the private lane…
```ruby
  lane :buildAndShip do
    ENV['FASTLANE_SKIP_ACTION_SUMMARY'] = true
    build
  end
```
- Inside the private lane `build ` as the first statement.
- Before every action-call, e.g.
```ruby
  private_lane :certificates do
    ENV['FASTLANE_SKIP_ACTION_SUMMARY'] = true
    match(
      app_identifier: ENV['APP_IDENTIFIER'],
      type: ENV['MATCH_TYPE'],
      readonly: true,
      shallow_clone: true,
      verbose: false,
      clone_branch_directly: true,
    )
  end
```

**Comment by tscharke** [comment]
Only for clarifying: 

- `ENV['FASTLANE_SKIP_ACTION_SUMMARY'] = "true"` is a valid statement and
- `ENV['FASTLANE_SKIP_ACTION_SUMMARY'] = true` is not?

**Comment by tscharke** [comment]
And if I do `FASTLANE_SKIP_ACTION_SUMMARY=1 fastlane env` wouldn't I have to see the variable?

**Comment by Katsz** [comment]
`ENV['FASTLANE_SKIP_ACTION_SUMMARY'] = true` supposed to fail with `TypeError (no implicit conversion of true into String)`. ENV is not exactly `Hash`, but special singleton object in ruby. But it seems like you are using some kind of CI and `.env` file, which may shadow ruby's ENV.

Could you provide output of `Fastlane::UI.message ENV.class`  please?

**Comment by Katsz** [comment]
> And if I do `FASTLANE_SKIP_ACTION_SUMMARY=1 fastlane env` wouldn't I have to see the variable?

No, you wouldn’t . `fastlane env` is another story.
By setting `FASTLANE_SKIP_ACTION_SUMMARY=1` before `fastlane ios buildAndShip` you will export `FASTLANE_SKIP_ACTION_SUMMARY` in current shell session. 

When ruby begins execution it should grab shell env as well.

And by the way, you are using pretty outdated ruby 2.3.3. I've confirmed that `TypeError` is reproducible at 2.3.3 and ruby version should not be a part of the problem, but it just nice thing to do once in a while (3 years passed from 2.3.3 release) to update ruby :wink:. Take a look at [rbenv](https://github.com/rbenv/rbenv) some day.

**Comment by Katsz** [comment]
@tscharke
I just realised that fastlane has `dotenv` support. Now it starting to make sense. 
As I said, `ENV['...'] = true` is invalid statement which should fail with `TypeError`. But `.env` can be whatever syntax you wish. `dotenv` will just skip invalid lanes.

Do you use `.env` for something else beside `FASTLANE_SKIP_ACTION_SUMMARY`? If so, can you create sample project as follows:
<details><summary>Fastfile</summary>

```ruby
lane :test do
    sh("cat .env", log: true)
    puts "ENV['FASTLANE_SKIP_ACTION_SUMMARY'] = #{ENV['FASTLANE_SKIP_ACTION_SUMMARY']}"
    just_some_lane_to_generate_summary()
end

lane :just_some_lane_to_generate_summary do
end
```

</details>
<details><summary>.env</summary>

```ruby
some invalid lanes
that will not affect
FASTLANE_SKIP_ACTION_SUMMARY = true
any further lane
```

</details>
Will it work as intended? 

```bash
$ fastlane test --capture_output
INFO [2019-10-31 15:19:32.14]: ----------------------
INFO [2019-10-31 15:19:32.14]: --- Step: cat .env ---
INFO [2019-10-31 15:19:32.14]: ----------------------
INFO [2019-10-31 15:19:32.14]: $ cat .env
INFO [2019-10-31 15:19:32.15]: ▸ some invalid lanes
INFO [2019-10-31 15:19:32.15]: ▸ that will not affect
INFO [2019-10-31 15:19:32.15]: ▸ FASTLANE_SKIP_ACTION_SUMMARY = true
INFO [2019-10-31 15:19:32.15]: ▸ any further lane
INFO [2019-10-31 15:19:32.15]: ENV['FASTLANE_SKIP_ACTION_SUMMARY'] = true
INFO [2019-10-31 15:19:32.15]: ---------------------------------------------------------------
INFO [2019-10-31 15:19:32.15]: --- Step: Switch to just_some_lane_to_generate_summary lane ---
INFO [2019-10-31 15:19:32.15]: ---------------------------------------------------------------
INFO [2019-10-31 15:19:32.15]: Cruising over to lane 'just_some_lane_to_generate_summary' 🚖
INFO [2019-10-31 15:19:32.15]: Cruising back to lane 'test' 🚘
INFO [2019-10-31 15:19:32.15]: fastlane.tools finished successfully 🎉
```

(no summary as you can see)

**Comment by tscharke** [comment]
At first thank you very much @Katsz for you work and that you're helping me 🙏

I don't understand all special things about ruby in detail yet😉. To focus on my topic (Skip action-summaries) I hopefully avoiding all „special“ cases and use no `.env`-files anymore.

Inspired by your `Fastfile` I copied, pasted and modified it to figured out some (more) things…

1. I update my ruby to use a never version.
2. I set `ENV['FASTLANE_SKIP_ACTION_SUMMARY']`inside my `Fastfile` (no `.env`-file anymore).
3. I use the wrong syntax and set `ENV['FASTLANE_SKIP_ACTION_SUMMARY'] = true` to see the error:

```bash
Error in your Fastfile at line 2
    1:	lane :test do
 => 2:	  ENV['FASTLANE_SKIP_ACTION_SUMMARY'] = true
    3:	
     4:	  puts "1. ENV['FASTLANE_SKIP_ACTION_SUMMARY'] = #{ENV['FASTLANE_SKIP_ACTION_SUMMARY']}"
no implicit conversion of true into String
fastlane finished with errors
```

Now I understand to set a variable correctly, I try it out with this `Fastfile`:

```ruby
lane :test do
  ENV['FASTLANE_SKIP_ACTION_SUMMARY'] = 'true'
  puts "1. ENV['FASTLANE_SKIP_ACTION_SUMMARY'] = #{ENV['FASTLANE_SKIP_ACTION_SUMMARY']}"
  just_some_lane_to_generate_summary
end

lane :just_some_lane_to_generate_summary do
  ENV['FASTLANE_SKIP_ACTION_SUMMARY'] = 'true'
  puts "2. ENV['FASTLANE_SKIP_ACTION_SUMMARY'] = #{ENV['FASTLANE_SKIP_ACTION_SUMMARY']}"
  match(
      app_identifier: 'de.dermeer.van.fastlaneInActions',
      type: 'development',
      readonly: true,
      shallow_clone: true,
      clone_branch_directly: true,
    )
end
```

As you can see I set `ENV['FASTLANE_SKIP_ACTION_SUMMARY'] = 'true'`. To make sure it's stetted in all lanes I do the setting of this variable twice and run `fastlane test` without the option `--capture_output`. And this is the result:

```bash
[14:45:16]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[14:45:17]: Driving the lane 'test' 🚀
[14:45:17]: 1. ENV['FASTLANE_SKIP_ACTION_SUMMARY'] = true
[14:45:17]: ---------------------------------------------------------------
[14:45:17]: --- Step: Switch to just_some_lane_to_generate_summary lane ---
[14:45:17]: ---------------------------------------------------------------
[14:45:17]: Cruising over to lane 'just_some_lane_to_generate_summary' 🚖
[14:45:17]: 2. ENV['FASTLANE_SKIP_ACTION_SUMMARY'] = true
[14:45:17]: -------------------
[14:45:17]: --- Step: match ---
[14:45:17]: -------------------

+----------------------------+--------------------------------------+
|                     Summary for match 2.134.0                     |
+----------------------------+--------------------------------------+
| app_identifier             | ["de.dermeer.van.fastlaneInActions"] |
| type                       | development                          |
| readonly                   | true                                 |
| shallow_clone              | true                                 |
| clone_branch_directly      | true                                 |
| generate_apple_certs       | false                                |
| skip_provisioning_profiles | false                                |
| storage_mode               | git                                  |
| git_branch                 | master                               |
| keychain_name              | login.keychain                       |
| force                      | false                                |
| force_for_new_devices      | false                                |
| skip_confirmation          | false                                |
| skip_docs                  | false                                |
| platform                   | ios                                  |
| verbose                    | false                                |
+----------------------------+--------------------------------------+
```

As you can see the **Summary for match** is showing furthermore  😞

I tried different values, means I do…
1. `ENV['FASTLANE_SKIP_ACTION_SUMMARY'] = 'true'` -> Shows summary
2. `ENV['FASTLANE_SKIP_ACTION_SUMMARY'] = '1'` -> Shows summary

If I run `fastlane test --capture_output` (with the option `capture_output`) I see more output but no summary - that's is true 😉

Here's my latest `fastlane env:
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.6.5                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | ~/.rbenv/versions/2.6.5/bin/fastlane        |
| Host                        | Mac OS X 10.14.6 (18G103)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.5/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.3                                        |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
lane :test do
  ENV['FASTLANE_SKIP_ACTION_SUMMARY'] = 'true'
  puts "1. ENV['FASTLANE_SKIP_ACTION_SUMMARY'] = #{ENV['FASTLANE_SKIP_ACTION_SUMMARY']}"
  just_some_lane_to_generate_summary
end

lane :just_some_lane_to_generate_summary do
  ENV['FASTLANE_SKIP_ACTION_SUMMARY'] = 'true'
  puts "2. ENV['FASTLANE_SKIP_ACTION_SUMMARY'] = #{ENV['FASTLANE_SKIP_ACTION_SUMMARY']}"
  match(
      app_identifier: 'de.dermeer.van.fastlaneInActions',
      type: 'development',
      readonly: true,
      shallow_clone: true,
      clone_branch_directly: true,
    )
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier ENV['APP_IDENTIFIER']
apple_id ENV['APPLE_ID']
itc_team_id ENV['APPLE_TEAM_ID']

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.134.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.1        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.13.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.68.0       |
| faraday                   | 0.17.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.1009  |
| mime-types                | 3.3          |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.4.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>


*generated on:* **2019-11-01**
</details>

**Comment by Katsz** [comment]
Uh-oh) 
Neither `.env` nor `ENV` was the reason, sorry for misleading you😅. It was that simple after all:

So, `FASTLANE_SKIP_ACTION_SUMMARY` is intended to skip lane stacktrace, and used by `Fastlane::LaneManagerBase.print_table(actions)`. On the other hand `Summary for match` is generated by `FastlaneCore::PrintTable.print_values(config: nil, title: nil, hide_keys: [], mask_keys: [], transform: :newline)` which doesn't care about skipping __action__ summary.

Long story short there is no way (I believe) to skip summary for `match`, as well as `gym`, `cert`, `sign`, `create_app_on_managed_play_store` and so on and so forth. 

I suggest you to take a look at 
https://github.com/fastlane/fastlane/blob/0c6a6d24098b9f6d7b16e4328a2048c6da4fa8df/fastlane/lib/fastlane/lane_manager_base.rb#L33-L35
and implement similar skip (with different ENV key) in https://github.com/fastlane/fastlane/blob/0c6a6d24098b9f6d7b16e4328a2048c6da4fa8df/fastlane_core/lib/fastlane_core/print_table.rb#L7-L12
 It would be great little contribution. I will differently use it myself 😄

**Comment by tscharke** [comment]
@Katsz No reason to apologize. You’ve help me a lot and I updated my ruby-version 😃

I’ll take a look into the codes and have to dig deeper (into ruby) to create a PR. Give me a little time 😉
