### ISSUE TITLE
Match git_basic_authorization doesn't work for GitHub

### ISSUE THREAD

**Issue by antonyalkmim** [fastlane/fastlane#15560]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm trying to setup Fastlane match with Github Actions C.I. but I can't clone my private repo with my certificates. I read the docs and I did find the `git_basic_authorization` to use in CLI, we just need to set the access token and use it. But the problem is that GitHub API uses the pattern `Authorization: token MYTOKEN` and Fastlane match uses the pattern `Authorization: basic MYTOKEN`. 

Here its the LOC where its implemented in match: 
https://github.com/fastlane/fastlane/blob/0c6a6d24098b9f6d7b16e4328a2048c6da4fa8df/match/lib/match/storage/git_storage.rb#L72

and here is The GitHub basic authentication docs: https://developer.github.com/v3/#authentication
 `curl -H "Authorization: token OAUTH-TOKEN" https://api.github.com`

##### Command executed
`fastlane match development`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
[07:52:24]: -------------------
[07:52:24]: --- Step: match ---
[07:52:24]: -------------------
[07:52:24]: Successfully loaded '*****/Matchfile' 📄

+-------------------------+-----------------------------------------------------------+
|                     Detected Values from './fastlane/Matchfile'                     |
+-------------------------+-----------------------------------------------------------+
| git_url                 | --     |
| app_identifier          | ["-",                                      |
|                         | "-"] |
| force_for_new_devices   | true                                                      |
| type                    | development                                               |
| git_basic_authorization | *****                  |
+-------------------------+-----------------------------------------------------------+

+----------------------------+-----------------------------------------------------------+
|                               Summary for match 2.134.0                                |
+----------------------------+-----------------------------------------------------------+
| type                       | development                                               |
| readonly                   | true                                                      |
| generate_apple_certs       | true                                                      |
| skip_provisioning_profiles | false                                                     |
| app_identifier             | ["-",                                      |
|                            | "-"] |
| team_id                    | -                                                |
| team_name                  | -                                        |
| storage_mode               | git                                                       |
| git_url                    | ----     |
| git_branch                 | master                                                    |
| shallow_clone              | false                                                     |
| clone_branch_directly      | false                                                     |
| git_basic_authorization    | MYTOKEN                                                  |
| keychain_name              | login.keychain                                            |
| force                      | false                                                     |
| force_for_new_devices      | true                                                      |
| skip_confirmation          | false                                                     |
| skip_docs                  | false                                                     |
| platform                   | ios                                                       |
| verbose                    | false                                                     |
+----------------------------+-----------------------------------------------------------+

[07:52:24]: Cloning remote git repo...
[07:52:24]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
Cloning into '/var/folders/vt/fnhm01q57fd0l35gh_0ntvv48035kf/T/d20191029-53184-f3i25b'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
[07:52:25]: Exit status: 128
[07:52:25]: Error cloning certificates repo, please make sure you have read access to the repository you want to use
[07:52:25]: Run the following command manually to make sure you're properly authenticated:
[07:52:25]: $ git clone https://github.com/**** /var/folders/vt/fnhm01q57fd0l35gh_0ntvv48035kf/T/d20191029-53184-f3i25b -c http.extraheader='AUTHORIZATION: basic MYTOKEN'
[07:52:25]: Error cloning certificates git repo, please make sure you have access to the repository - see instructions above

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | update_fastlane  | 1           |
| 2    | default_platform | 0           |
| 3    | cocoapods        | 2           |
| 💥   | match            | 0           |
| 5    | is_ci            | 0           |
+------+------------------+-------------+

[07:52:25]: fastlane finished with errors

[!] Error cloning certificates git repo, please make sure you have access to the repository - see instructions above

</pre>
</details>

### Environment
<details>
  <pre></pre>
</details>

**Comment by antonyalkmim** [comment]
I realized that this was not my problem. I didn't find in Fastlane documentation that I need to encode the token like `Base64.decode64("myusername:mypersonaltoken")` and use it as my basic auth token. Would be good if we update the docs and add this tip.

```
// Matchfile
git_basic_authorization Base64.decode64("gitusername:personalaccesstoken")
```

**Comment by LamourBt** [comment]
@antonyalkmim Hey there I think I'm facing the same issue as you. Did you get it working? I've posted a question [here](https://stackoverflow.com/questions/58632584/fastlane-match-failed-to-connect-using-personal-access-token-and-username)

**Comment by antonyalkmim** [comment]
@LamourBt Could you check your git clone command in your logs? Maybe its ignoring your token. Also double check if this user has access to certificate repo.

**Comment by LamourBt** [comment]
Here is the log 
```Please make sure you have the correct access rights
and the repository exists.
[13:52:56]: Exit status: 128
[13:52:56]: Error cloning certificates repo, please make sure you have read access to the repository you want to use
[13:52:56]: Run the following command manually to make sure you're properly authenticated:
[13:52:56]: $ git clone <REPO URL> /var/folders/1b/gl7yt7ds26vcyr1pkgld6l040000gn/T/d20191030-906-615jnh -c http.extraheader='AUTHORIZATION: basic <Token>
'```
The personal token was issued from a GitHub account that has access to the certificate repo. @antonyalkmim

**Comment by antonyalkmim** [comment]
@LamourBt try access your repo via cli: 
```
curl -v -H "Authorization: basic <BASE64_TOKEN>" https://api.github.com/repos/<owner>/<repo>
```

**Comment by LamourBt** [comment]
This worked but I think I found the issue for some reason in the log I see that base64 is separated in  two lines instead of one.  Such as 

```
git clone https://github.com/<owner>/<repo>.git /var/folders/1b/gl7yt7ds26vcyr1pkgld6l040000gn/T/d20191030-906-615jnh -c http.extraheader='AUTHORIZATION: basic bGFtb3V8238nQ6Dc5OTcyNjZiYmIzMjdiN287328NjYyNmQ1YuiqZkZGY4
ZGEEE==
'
```

@antonyalkmim

**Comment by Jerland2** [comment]
> I realized that this was not my problem. I didn't find in Fastlane documentation that I need to encode the token like `Base64.encode64("myusername:mypersonaltoken")` and use it as my basic auth token. Would be good if we update the docs and add this tip.
> 
> ```
> // Matchfile
> git_basic_authorization Base64.encode64("gitusername:personalaccesstoken")
> ```

It is worth noting to future viewers, that you should encode your basic auth header manually (outside of CI/CD), then add the converted (base64) value as the secret key.
