### ISSUE TITLE
get_version_number doesn't work with 11.1.0 when using ${MARKETING_VERSION)

### ISSUE THREAD

**Issue by bgold0** [fastlane/fastlane#15565]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

`get_version_number` plugin doesn't get version number on XCode 11.1.0

I currently have the following:

    <key>CFBundleShortVersionString</key>
    <string>$(MARKETING_VERSION)</string>

##### Command executed

`get_version_number(target: 'MyApp')` => `$(MARKETING_VERSION)` instead of version.

**Comment by tizaks** [comment]
Where are you defining `MARKETING_VERSION`? I've seen this behaviour as well, but only when attempting to set that build setting in an `xcconfig` file.
