### ISSUE TITLE
Ability to upload assets to existing github release

### ISSUE THREAD

**Issue by peppy** [fastlane/fastlane#15577]
#### Motivation Behind Feature

I manage a [project](https://github.com/ppy/osu) which uses fastlane for iOS and android builds as well as some non-fastlane-based tools for Windows / macOS / linux builds. These are all compiled into a single github [releases](https://github.com/ppy/osu/releases) (which remains as draft until all build steps finish).

Currently [set_github_release](https://docs.fastlane.tools/actions/set_github_release/) allows creation and asset upload in one single command. This works well in cases a single lane is doing the full release, but not so well when multiple components are involved in the release process.

#### Feature Description

I propose a separate command be added which specifically targets the uploading of assets (ie. extracting the upload portion out of `set_github_release` itself to allow for manual uploading to an existing release).

#### Alternatives or Workarounds

An alternative would be to modify `set_github_release` to be able to handle the release-already-exists case, and instead modify that existing release (via [PATCH support](https://developer.github.com/v3/repos/releases/#edit-a-release). This would still fulfill my usage criteria as it would allow uploading new resources in that process.

**Comment by janpio** [comment]
Thanks for the suggestion. Can you spec out what the command would look like (name, options etc) so someone could possibly take a shot at implementing this?

**Comment by peppy** [comment]
## `add_github_asset`

Adds a new asset to an existing github release.

Arguments:
- `release_name` an existing release, used to retrieve or form the `upload_url`
- `upload_assets` path to assets to be appended to the release (same as `set_github_release`)

Should [perform an upload](https://developer.github.com/v3/repos/releases/#upload-a-release-asset), erroring if the file already exists in the target release.
