### ISSUE TITLE
`fastlane update` updates fastlane, then tries to execute `lane :update`

### ISSUE THREAD

**Issue by Katsz** [fastlane/fastlane#15575]
### New Issue Checklist

- [Sort-of] Updated fastlane to the latest version 
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
`fastlane update` not only updates fastlane (`2.133.0 -> 2.134.0` that is) but tries to invoke `lane :update` despite there is not such lane. However running `fastlane update_fastlane` works as intended.
`gem 'whatever' is already installed` indicates that Fastfile loaded before update executed, 

##### Command executed
`fastlane update`

##### Complete output when running fastlane, including the stack trace and command used
``` bash
$ fastlane update --capture_output
[✔] 🚀 
[14:49:43]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2019-10-31 14:41:53.41]: Checking if there are any plugins that should be loaded...
INFO [2019-10-31 14:41:53.55]: gem 'xcodeproj' is already installed
INFO [2019-10-31 14:41:53.55]: gem 'rest-client' is already installed
INFO [2019-10-31 14:41:53.59]: gem 'json' is already installed
INFO [2019-10-31 14:41:53.66]: -----------------------------
INFO [2019-10-31 14:41:53.66]: --- Step: update_fastlane ---
INFO [2019-10-31 14:41:53.66]: -----------------------------
INFO [2019-10-31 14:41:53.66]: Looking for updates for fastlane...
INFO [2019-10-31 14:41:56.82]: Nothing to update ✅
INFO [2019-10-31 14:41:56.82]: -----------------------------
INFO [2019-10-31 14:41:56.82]: --- Step: update_fastlane ---
INFO [2019-10-31 14:41:56.82]: -----------------------------
INFO [2019-10-31 14:41:56.82]: Looking for updates for fastlane...
INFO [2019-10-31 14:41:56.82]: Nothing to update ✅
ERROR [2019-10-31 14:41:56.82]: Could not find lane 'update'. Available lanes: <list of actual lanes>
INFO [2019-10-31 14:41:56.82]: Successfully generated documentation at path '<redacted>/fastlane/README.md'
ERROR [2019-10-31 14:41:56.83]: fastlane finished with errors
```

```bash
$ fastlane update_fastlane --capture_output
[✔] 🚀 
[14:57:26]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2019-10-31 14:57:27.32]: Checking if there are any plugins that should be loaded...
INFO [2019-10-31 14:57:27.42]: -----------------------------
INFO [2019-10-31 14:57:27.42]: --- Step: update_fastlane ---
INFO [2019-10-31 14:57:27.42]: -----------------------------
INFO [2019-10-31 14:57:27.42]: Looking for updates for fastlane...
INFO [2019-10-31 14:57:29.14]: Nothing to update ✅
```
### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                             |
| --------------------------- | ------------------------------------------------- |
| OS                          | 10.14.6                                           |
| Ruby                        | 2.6.0                                             |
| Bundler?                    | false                                             |
| Git                         | git version 2.21.0 (Apple Git-122)                |
| Installation Source         | ~/.rbenv/versions/2.6.0/bin/fastlane              |
| Host                        | Mac OS X 10.14.6 (18G87)                          |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.0/lib                       |
| OpenSSL Version             | OpenSSL 1.0.2s  28 May 2019                       |
| Is contained                | false                                             |
| Is homebrew                 | false                                             |
| Is installed via Fabric.app | false                                             |
| Xcode Path                  | /Applications/Xcode11.1GM.app/Contents/Developer/ |
| Xcode Version               | 11.1                                              |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# --- Init --
fastlane_require 'xcodeproj'
fastlane_require 'rest-client'
fastlane_require 'json'
<400 more lines of ruby that doesn't make any difference>
```
</details>

**Comment by janpio** [comment]
Hmmm, is this a bug or a feature?

**Comment by Katsz** [comment]
Well, it's bug at least because it tries to update twice. :thinking:
