### ISSUE TITLE
Error packaging up the application

### ISSUE THREAD

**Issue by saravana-kr** [fastlane/fastlane#15578]
[maphabitMobileApp-maphabitMobileApp.log](https://github.com/fastlane/fastlane/files/3797606/maphabitMobileApp-maphabitMobileApp.log)

I have attached the Log file for the error.

**Comment by janpio** [comment]
Please do not delete the issue template, we need it to be able to try to help you.

**Comment by saravana-kr** [comment]
Sorry , will raise a new issue with the template intact.
