### ISSUE TITLE
Fastlane session is expired every day when releasing an app to TestFlight via Azure DevOps

### ISSUE THREAD

**Issue by Mikilll94** [fastlane/fastlane#15581]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I am publishing my app to TestFlight via Azure DevOps. In order to do that you have to create a service connection.

![image](https://user-images.githubusercontent.com/17653648/68058068-3737bf00-fcf8-11e9-82e1-9facedf681f8.png)

My apple id account uses 2FA. I am generating a Fastlane session using this command
```
fastlane spaceauth -u [my_apple_id_email]
```

Unfortunately every new day I am receiving an error:

`
"Fastlane session is not available anymore. Continuing with normal login."
`

Any my release fails because it cannot bypass 2FA.

![image](https://user-images.githubusercontent.com/17653648/68058570-c1345780-fcf9-11e9-9dbc-d693b86c97a3.png)

Docs says that the Fastlane session should be valid for one month but this is not true. From my observations, I think that the Fastlane session expires after one day, not after one month.

Why is this working like that? Is there any possibility to set the duration of Fastlane session. Because right now it is very annoying that I have log every day on Azure DevOps and update Fastlane session in service connection.

**Comment by Mikilll94** [comment]
@fastlane-bot 
I will do that later. Right now I don't have access to the machine where Fastlane is installed.

But it doesn't matter in this issue. This a problem with a session in the newest version of Fastlane.

**Comment by Katsz** [comment]
There was some changes on the Apple's side of things few months ago. It seems like sessions are quite short now. 

Your account uses 2FA by choice or because  it is `Account Holder`? Maybe you will be better creating another apple id with `Developer` role and add it to your team(s)? Developer will not be enforced to add 2FA. We took that road, works like a charm.

**Comment by Mikilll94** [comment]
@Katsz 
Ok, I will try adding this new account with "Developer" role.

My account has "App Manager role". I have enabled 2FA by choice. Unfortunately, I have noticed that if you turn on 2FA, you cannot turn it off, which is very stupid.
