### ISSUE TITLE
Can't disable auto release option for iOS Appstore builds

### ISSUE THREAD

**Issue by ramtrk** [fastlane/fastlane#15593]
Once the "Automatically release this version after App Review, no earlier than" option is set earlier, can't move this to "Manually release this version" option by calling APIAppstoreAction with values {automatic_release: false, auto_release_date: nil}.

I am using fastlane version 2.122.0.
Please help me to solve this issue.

Note: Its is working when already set to automatic_release: true then call the API with {automatic_release: false, auto_release_date: nil}. 

**NOT WORKING only when already set to "Automatically release this version after App Review, no earlier than"**

**Comment by janpio** [comment]
Please don't delete the issue template, but fill it. It is there for a reason.
