### ISSUE TITLE
Add option to scan for using prebuilt xctestrun without workspace/project

### ISSUE THREAD

**Issue by Cyberbeni** [fastlane/fastlane#15595]
### Feature Request
It would be cool if scan supported the option to use xctestrun instead of workspace/project

#### Motivation Behind Feature
Running UI tests on iPhones/iPads that are stored in a less secure place (to allow easier access to the devices in case they need manual reboot) would security benefit from not having to access the codebase but only the xctestrun file.

#### Feature Description
If xctestrun file is provided then scan should work without specifying workspace/project path

**Comment by Cyberbeni** [comment]
.

**Comment by Cyberbeni** [comment]
Yes, this is still valid.

So I'm using this project as an example: https://github.com/Cyberbeni/TypedNotificationCenter
First I build the test: `xcodebuild build-for-testing -project TypedNotificationCenter.xcodeproj -scheme TypedNotificationCenter\ macOS -derivedDataPath ./dd`
Then I move the `dd` directory to another location, then I can run the test with xcodebuild with the following command: `xcodebuild test-without-building -xctestrun ./dd/Build/Products/TypedNotificationCenter\ macOS_macosx10.15-x86_64.xctestrun -destination 'platform=OS X,arch=x86_64'`
Which would translate to the following fastlane command: `fastlane scan xctestrun:./dd/Build/Products/TypedNotificationCenter\ macOS_macosx10.15-x86_64.xctestrun`
But this results in the following prompt: `Couldn't automatically detect the project file, please provide a path:`

**Comment by Cyberbeni** [comment]
👀 Do notifications have emojis, Josh?

**Comment by Cyberbeni** [comment]
I'm starting to think that @joshdholtz is not getting notifications about this 🤔

**Comment by joshdholtz** [comment]
I’m here. I just have a lot of other notifications that come my way and a big list of existing tasks I’m trying to finish up 😇 And more fastlane projects than just this repo 😉

**Comment by Cyberbeni** [comment]
Cool, no worries.

**Comment by Cyberbeni** [comment]
.

**Comment by minuscorp** [comment]
I'll add it to my wishlist asap

**Comment by Cyberbeni** [comment]
.

**Comment by minuscorp** [comment]
I've been working with a regression and other feature, still in my to-do list, my apologies 🙇🏻‍♂️

**Comment by minuscorp** [comment]
Still a thing, sorry, just finished my previous PR

**Comment by Cyberbeni** [comment]
.

**Comment by laszloagardi** [comment]
Do you have an ETA for this issue?

**Comment by minuscorp** [comment]
In currently working on another Swift issue, I'll try to work with it ASAP
