### ISSUE TITLE
Resigned app with bitcode enabled crashes at launch

### ISSUE THREAD

**Issue by francybiga** [fastlane/fastlane#15594]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When resigning an IPA with bitcode embedded using `sigh`, the resign process ends without errors but, after installing the IPA on a device using Xcode, the app **crashes at launch**. 
I cannot retrieve a crashlog from device, the only hint I have is this log from the `Console.app` on my mac.

```
Failed to start job for application<it.prima.prima>: <NSError: 0x15f21fa10; domain: NSPOSIXErrorDomain; code: 3; reason: "No such process"> {
    userInfo = {
        RBLaunchdOperation = launch_get_running_pid_4SB;
        RBLaunchdJobLabel = UIKitApplication:it.prima.prima[028c][rb-legacy];
    }
}
```
Which is not very helpful. 

After several atttempts I figured out that this happens only when resigning an app with bitcode embedded. If I disable bitcode and perform a resign with the same provisioning profile and without changing any other parameter, the app launches correctly.

I also tried other tools for resigning and I get the same behaviour so probabily it's not a problem directly related to `sigh` but maybe emitting a warning when attempting to resign an IPA with bitcode enabled could help identifying the problem.

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15                                                          |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.21.0 (Apple Git-122)                             |
| Installation Source         | ~/Workspace/Prima/vendor/bundle/ruby/2.6.0/bin/fastlane        |
| Host                        | Mac OS X 10.15 (19A602)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode_11.1.app/Contents/Developer/               |
| Xcode Version               | 11.1                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | it_IT.UTF-8 | ✅ |
| LC_ALL   |             | 🚫 |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.134.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.1.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.3.0        |
| bundler                                   | 2.0.1        |
| etc                                       | 1.0.1        |
| CFPropertyList                            | 3.0.1        |
| public_suffix                             | 2.0.5        |
| addressable                               | 2.7.0        |
| atomos                                    | 0.1.3        |
| babosa                                    | 1.0.3        |
| claide                                    | 1.0.3        |
| colored                                   | 1.2          |
| colored2                                  | 3.1.2        |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| declarative                               | 0.0.10       |
| declarative-option                        | 0.1.0        |
| digest-crc                                | 0.4.1        |
| unf_ext                                   | 0.0.7.6      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| dotenv                                    | 2.7.5        |
| emoji_regex                               | 1.0.1        |
| excon                                     | 0.68.0       |
| multipart-post                            | 2.0.0        |
| faraday                                   | 0.17.0       |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.6        |
| faraday_middleware                        | 0.13.1       |
| fastimage                                 | 2.1.7        |
| gh_inspector                              | 1.1.3        |
| jwt                                       | 2.1.0        |
| memoist                                   | 0.16.0       |
| multi_json                                | 1.14.1       |
| os                                        | 1.0.1        |
| signet                                    | 0.12.0       |
| googleauth                                | 0.6.7        |
| httpclient                                | 2.8.3        |
| mime-types-data                           | 3.2019.1009  |
| mime-types                                | 3.3          |
| uber                                      | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| google-api-client                         | 0.23.9       |
| google-cloud-env                          | 1.3.0        |
| google-cloud-core                         | 1.4.1        |
| google-cloud-storage                      | 1.16.0       |
| json                                      | 2.2.0        |
| mini_magick                               | 4.9.5        |
| multi_xml                                 | 0.6.0        |
| plist                                     | 3.5.0        |
| rubyzip                                   | 1.3.0        |
| security                                  | 0.1.3        |
| naturally                                 | 2.2.0        |
| simctl                                    | 1.6.6        |
| slack-notifier                            | 2.3.2        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.6.0        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.7.0        |
| tty-cursor                                | 0.7.0        |
| tty-spinner                               | 0.9.1        |
| word_wrap                                 | 1.0.0        |
| nanaimo                                   | 0.2.6        |
| xcodeproj                                 | 1.13.0       |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.0        |
| fastlane-plugin-firebase_app_distribution | 0.1.4        |
| xcode-install                             | 2.5.0        |
</details>

*generated on:* **2019-11-05**
</details>

**Comment by vovander** [comment]
I have the same issue. When i build ipa locally on my mac - it's ok! But on remote ci machine - app will crash at launch. Also bitecode is enabled for this project. I have used 2.136.0 version
