### ISSUE TITLE
Simulator is being erased when localisation is turned on

### ISSUE THREAD

**Issue by zeusent** [fastlane/fastlane#15598]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When running snapshot with `localize_simulator` set to `true` my simulators are being erased before launching.

I've looked over the code and I found the line that's responsible for that. I've added a comment in there as well:

https://github.com/fastlane/fastlane/commit/f410f2a6d9d20ae8e6747db978cae7142a03d781#r35820202

Now, is this on purpose or is it a flaw? I've edited out those lines on my local fastlane instalation and it seems to work fine without erasing the simulator. But maybe I don't know the whole picture

**Comment by janpio** [comment]
This is a better link to the current code: https://github.com/fastlane/fastlane/blob/89398d50c025dfd03fff813e26fcc5bd6f65a91c/snapshot/lib/snapshot/simulator_launchers/simulator_launcher_base.rb#L59

From looking at the code, it seems that some things require the simulator to be erased to make sure they work - unfortunately there is no clear comment. @webventil also used that when adding dark mdoe stuff just 2 months ago - maybe he remembers? Or even @ohayon from 2 years back?
