### ISSUE TITLE
mismatch between 'export_method'

### ISSUE THREAD

**Issue by shelbygold** [fastlane/fastlane#15599]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

I try to run fastlane and keep getting the error that the export_methods do not match. I do not know how to change this so that they match I have looked everywhere but can't find anything on how to get past this issue.

I have looked through documentation and wasn't able to find an answer to help with my question. 

#### Question Description

![Screen Shot 2019-11-05 at 4 42 37 PM](https://user-images.githubusercontent.com/48368538/68255725-503bbb00-ffeb-11e9-9b37-ae79d95537b7.png)
![Screen Shot 2019-11-05 at 4 42 37 PM](https://user-images.githubusercontent.com/48368538/68255740-5af65000-ffeb-11e9-8b20-53a51264d10c.png)

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15                                                          |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.21.0 (Apple Git-122)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15 (19A573a)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.0                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

update_fastlane(nightly: true)

default_platform(:ios)

platform :ios do
  desc "Push a new beta builds for the entire Suite to TestFlight"
  lane :beta do |options|
    if options[:fortify]
      puts "Fortify Upload"
      increment_build_number(xcodeproj: "Fortify.xcodeproj")
      build_app(workspace: "Fortify.xcworkspace", scheme: "Fortify")
      upload_to_testflight(skip_waiting_for_build_processing: true, apple_id: "1304648824", app_identifier: "com.impact.fortify")  
      # upload_symbols_to_crashlytics(dsym_path: "./App.dSYM.zip")
    end

    if options[:turn]
      puts "Turn Upload"
      increment_build_number(xcodeproj: "Turn/Turn.xcodeproj")
      build_app(workspace: "Fortify.xcworkspace", scheme: "Turn")
      upload_to_testflight(skip_waiting_for_build_processing: true, apple_id: "1373353624", app_identifier: "com.impact.turn")
      # upload_symbols_to_crashlytics(dsym_path: "./App.dSYM.zip")
    end

    if options[:lift]
      puts "Lift Upload"
      increment_build_number(xcodeproj: "Lift/Lift.xcodeproj")
      build_app(workspace: "Fortify.xcworkspace", scheme: "Lift")
      upload_to_testflight(skip_waiting_for_build_processing: true, apple_id: "1377309571", app_identifier: "com.impact.Lift")
      # upload_symbols_to_crashlytics(dsym_path: "./App.dSYM.zip")
    end
  end
end

platform :ios do
  desc "Push a new Fortify beta build to TestFlight"
  lane :fortifyBeta do
  	increment_build_number(xcodeproj: "Fortify.xcodeproj")
    build_app(workspace: "Fortify.xcworkspace", scheme: "Fortify")
    upload_to_testflight(skip_waiting_for_build_processing: true, apple_id: "1304648824", app_identifier: "com.impact.fortify")
    # upload_symbols_to_crashlytics(dsym_path: "./App.dSYM.zip")
  end
end

platform :ios do
  desc "Push a new Turn beta build to TestFlight"
  lane :turnBeta do
  	increment_build_number(xcodeproj: "Turn/Turn.xcodeproj")
    build_app(workspace: "Fortify.xcworkspace", scheme: "Turn")
    upload_to_testflight(skip_waiting_for_build_processing: true, apple_id: "1373353624", app_identifier: "com.impact.turn")
    # upload_symbols_to_crashlytics(dsym_path: "./App.dSYM.zip")
  end
end

platform :ios do
  desc "Push a new Lift beta build to TestFlight"
  lane :liftBeta do
  	increment_build_number(xcodeproj: "Lift/Lift.xcodeproj")
    build_app(workspace: "Fortify.xcworkspace", scheme: "Lift")
    upload_to_testflight(skip_waiting_for_build_processing: true, apple_id: "1377309571", app_identifier: "com.impact.Lift")
    # upload_symbols_to_crashlytics(dsym_path: "./App.dSYM.zip")
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.impact.fortify") # The bundle identifier of your app
apple_id("shelbywgold@icloud.com") # Your Apple email address

itc_team_id("118863986") # App Store Connect Team ID
team_id("2M3472WPFA") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.134.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.68.0       |
| faraday                   | 0.17.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.1009  |
| mime-types                | 3.3          |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.4.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>

*generated on:* **2019-11-05**
</details>

**Comment by janpio** [comment]
What code are you running exactly? And what do you have selected in Xcode?
