### ISSUE TITLE
update_info_plist - set ITSAppUsesNonExemptEncryption true

### ISSUE THREAD

**Issue by joacim-boive** [fastlane/fastlane#15591]
### Question Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
We generate the Xcode project on each build, since we use Cordova.
So I can't set the info.plist file to include ITSAppUsesNonExemptEncryption

#### Question Description
I would like to use the update_info_plist action during build to do this for us, but can't figure out the syntax (Not a Ruby dev ;) ).

How can I use the action to Set/Add ITSAppUsesNonExemptEncryption as a boolean to true in the info.plist file?

**Comment by Katsz** [comment]
You could run `fastlane action update_info_plist` to get complete documentation.
```ruby
set_info_plist_value(path: "path/to/Info.plist", key: "ITSAppUsesNonExemptEncryption", value: false)
``` 
Should do the trick 😉

**Comment by Katsz** [comment]
If you are looking for setting multiple values at once, you may want to take a look at `update_info_plist`, namely pass `block` parameter 
```ruby
update_info_plist(
            plist_path: "path/to/Info.plist",
            block: proc do |plist|
              # raw value - int/bool/string 
              plist['ITSAppUsesNonExemptEncryption'] = false
              # array
              plist['UISupportedInterfaceOrientations'] = ["UIInterfaceOrientationPortrait", "UIInterfaceOrientationLandscapeLeft"]
              # dictionary
              plist['NSAppTransportSecurity'] = {"NSAllowsArbitraryLoads" => true }
            end
)
```

**Comment by joacim-boive** [comment]
> You could run `fastlane action update_info_plist` to get complete documentation.
> 
> ```ruby
> set_info_plist_value(path: "path/to/Info.plist", key: "ITSAppUsesNonExemptEncryption", value: false)
> ```
> 
> Should do the trick 😉

Haha! Too Easy! :)
