### ISSUE TITLE
unknown keyword: default_value_dynamic with firebase_app_distribution

### ISSUE THREAD

**Issue by magneticrob** [fastlane/fastlane#15602]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When I run `fastlane action firebase_app_distribution` it seems to fail early and gives me a stacktrace.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>### Captured Output

Command Used: `action firebase_app_distribution`
<details><summary>Output/Log</summary>

```

DEBUG [2019-11-06 15:33:50.23]: Checking if there are any plugins that should be loaded...
DEBUG [2019-11-06 15:33:50.30]: Loading 'fastlane-plugin-firebase_app_distribution' plugin
INFO [2019-11-06 15:33:50.44]: gem 'fastlane-plugin-firebase_app_distribution' is already installed
+------------------------+---------+------------------------+
|                       Used plugins                        |
+------------------------+---------+------------------------+
| Plugin                 | Version | Action                 |
+------------------------+---------+------------------------+
| fastlane-plugin-fireb  | 0.1.4   | firebase_app_distribu  |
| ase_app_distribution   |         | tion                   |
+------------------------+---------+------------------------+

Loading documentation for firebase_app_distribution:

+---------------------------------------------------------+
|                firebase_app_distribution                |
+---------------------------------------------------------+
| Release your beta builds with Firebase App Distribution |
|                                                         |
| Release your beta builds with Firebase App Distribution |
|                                                         |
| Created by Stefan Natchev                               |
+---------------------------------------------------------+


Looking for related GitHub issues on fastlane/fastlane...
Search query: unknown keyword: default_value_dynamic

URL: https://api.github.com/search/issues?q=unknown%20keyword%3A%20default_value_dynamic+repo:fastlane/fastlane
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
DEBUG [2019-11-06 15:33:51.73]: All plugins are up to date


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15                                       |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.15 (19A583)                     |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.3                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "xxx"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later

lane :qalocal do

	gym(
	  scheme: "debug",
	  export_options: {
	    method: "development",
	    provisioningProfiles: { 
	      "xxx" => "xxx"
	    }
	  }
	)

	# upload to Fabric
	firebase_app_distribution(
	  app: "xxx",
	  groups: "qa-team"
	)

end```
</details>

<details><summary>`./Appfile`</summary>

```ruby
# The Appfile can be used to specify information that's used across all fastlane
# tools, like your username or the app's bundle identifier.
#
# For more details, check out the documentation at:
# https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

# app_identifier "com.your.app" # the bundle identifier of your app
# apple_id "apple@fastlane.tools" # Your Apple ID
```
</details>

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.28.3  | 💥 Check failed |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status  |
| ----------------------------------------- | ------- | -------------- |
| fastlane-plugin-firebase_app_distribution | 0.1.4   | 💥 Check failed |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| CFPropertyList                            | 3.0.1        |
| CFPropertyList                            | 2.3.5        |
| addressable                               | 2.7.0        |
| atomos                                    | 0.1.3        |
| babosa                                    | 1.0.3        |
| bigdecimal                                | 1.2.6        |
| bundler                                   | 1.14.6       |
| claide                                    | 1.0.3        |
| colored                                   | 1.2          |
| colored2                                  | 3.1.2        |
| commander-fastlane                        | 4.4.6        |
| declarative                               | 0.0.10       |
| declarative-option                        | 0.1.0        |
| digest-crc                                | 0.4.1        |
| domain_name                               | 0.5.20170404 |
| dotenv                                    | 2.7.5        |
| emoji_regex                               | 1.0.1        |
| excon                                     | 0.68.0       |
| faraday                                   | 0.17.0       |
| faraday-cookie_jar                        | 0.0.6        |
| faraday_middleware                        | 0.13.1       |
| fastimage                                 | 2.1.7        |
| fastlane-plugin-firebase_app_distribution | 0.1.4        |
| gh_inspector                              | 1.1.3        |
| google-api-client                         | 0.9.28       |
| googleauth                                | 0.5.1        |
| highline                                  | 1.7.10       |
| http-cookie                               | 1.0.3        |
| httpclient                                | 2.8.3        |
| hurley                                    | 0.2          |
| io-console                                | 0.4.3        |
| json                                      | 1.8.1        |
| jwt                                       | 2.1.0        |
| jwt                                       | 1.5.6        |
| libxml-ruby                               | 3.0.0        |
| little-plugger                            | 1.1.4        |
| logging                                   | 2.2.2        |
| memoist                                   | 0.16.0       |
| mime-types                                | 3.1          |
| mime-types-data                           | 3.2019.1009  |
| mini_magick                               | 4.9.5        |
| mini_magick                               | 4.5.1        |
| minitest                                  | 5.4.3        |
| multi_json                                | 1.14.1       |
| multi_xml                                 | 0.6.0        |
| multipart-post                            | 2.0.0        |
| nanaimo                                   | 0.2.6        |
| naturally                                 | 2.2.0        |
| nokogiri                                  | 1.5.6        |
| os                                        | 1.0.1        |
| os                                        | 0.9.6        |
| plist                                     | 3.5.0        |
| power_assert                              | 0.2.2        |
| psych                                     | 2.0.8        |
| public_suffix                             | 2.0.5        |
| rake                                      | 10.4.2       |
| rdoc                                      | 4.2.0        |
| representable                             | 2.3.0        |
| retriable                                 | 3.1.2        |
| retriable                                 | 2.1.0        |
| rouge                                     | 2.0.7        |
| rubygems-update                           | 2.5.2        |
| rubyzip                                   | 1.3.0        |
| security                                  | 0.1.3        |
| signet                                    | 0.7.3        |
| simctl                                    | 1.6.6        |
| slack-notifier                            | 2.3.2        |
| slack-notifier                            | 1.5.1        |
| sqlite3                                   | 1.3.13       |
| terminal-notifier                         | 2.0.0        |
| terminal-notifier                         | 1.7.1        |
| terminal-table                            | 1.7.3        |
| test-unit                                 | 3.0.8        |
| tty-cursor                                | 0.7.0        |
| tty-screen                                | 0.7.0        |
| tty-screen                                | 0.5.0        |
| tty-spinner                               | 0.9.1        |
| uber                                      | 0.1.0        |
| uber                                      | 0.0.15       |
| unf                                       | 0.1.4        |
| unf_ext                                   | 0.0.7.4      |
| unicode-display_width                     | 1.6.0        |
| unicode-display_width                     | 1.1.3        |
| word_wrap                                 | 1.0.0        |
| xcodeproj                                 | 1.13.0       |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 0.0.4        |
</details>

*generated on:* **2019-11-06**
</details></pre>
</details>

**Comment by magneticrob** [comment]
Also, my version of fastlane is 2.28.3. The latest version in this repositories releases is 2.134.0. I may be confused here and just have an old version - I downloaded using the installer from fastlane.tools earlier today.

**Comment by Katsz** [comment]
Take a look at #15496.

**Comment by janpio** [comment]
Version problem is explained in https://github.com/fastlane/fastlane/issues/15496
The action you are using is not part of fastlane itself, but a plugin: https://github.com/fastlane-community/fastlane-plugin-firebase_app_distribution So if you have a problem with that, you should probably ask there.
