### ISSUE TITLE
Authorization failed: invalid_grant - Invalid JWT Signature.

### ISSUE THREAD

**Issue by olcayertas** [fastlane/fastlane#15600]
### Issue Description
I am trying to upload a bundle to Google Play Store and getting following error:
```
.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/signet-0.11.0/lib/signet/oauth_2/client.rb:1017:in `fetch_access_token': [!] Authorization failed.  Server message: (Signet::AuthorizationError)
{
  "error": "invalid_grant",
  "error_description": "Invalid JWT Signature."
}

.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/signet-0.11.0/lib/signet/oauth_2/client.rb:1036:in `fetch_access_token!'
.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/googleauth-0.6.7/lib/googleauth/signet.rb:69:in `fetch_access_token!'
.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.134.0/supply/lib/supply/client.rb:52:in `initialize'
.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.134.0/supply/lib/supply/client.rb:18:in `new'
.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.134.0/supply/lib/supply/client.rb:18:in `make_from_config'
.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.134.0/supply/lib/supply/uploader.rb:293:in `client'
.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.134.0/supply/lib/supply/uploader.rb:6:in `perform_upload'
.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/actions/upload_to_play_store.rb:33:in `run'
.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
from Fastfile:42:in `block (2 levels) in parsing_binding'
.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/lane.rb:33:in `call'
.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/lane.rb:33:in `call'
.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.134.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.134.0/bin/fastlane:23:in `<top (required)>'
.fastlane/bin/bundle/bin/fastlane:22:in `load'
.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```
I have tried to restart my computer but it didn't work.

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.1                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0 (Apple Git-122.2)        |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.15.1 (19B88)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.2                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :crashlyticsbeta do
    gradle(task: "clean assembleRelease")
    crashlytics
  end

  desc 'Deploy a new internal version to the Google Play Store'
  lane :internal do
    android_set_version_code(
      #version_code: 17, # optional, if not specified, Version Code will be incremented
      gradle_file: "app/build.gradle" # optional
    )
    gradle(task: "bundleReleaseJsAndAssets")
    gradle(task: "copyReleaseBundledJs")
    gradle(task: "bundleRelease")
    supply(track: 'internal', skip_upload_apk: true)
  end

  desc 'Deploy a new beta version to the Google Play Store'
  lane :beta do
    android_set_version_code(
      #version_code: 17, # optional, if not specified, Version Code will be incremented
      gradle_file: "app/build.gradle" # optional
    )
    gradle(task: "bundleRelease")
    supply(track: 'beta', skip_upload_apk: true)
    #supply(track: 'beta', track_promote_to: 'rollout', skip_upload_apk: true)
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("fastlane/***.json")
#package_name("***")
package_name("com.***")
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.134.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                             | Version | Update-Status |
| ---------------------------------- | ------- | ------------- |
| fastlane-plugin-versioning_android | 0.1.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                | Version      |
| ---------------------------------- | ------------ |
| slack-notifier                     | 2.3.2        |
| atomos                             | 0.1.3        |
| CFPropertyList                     | 2.3.5        |
| claide                             | 1.0.3        |
| colored2                           | 3.1.2        |
| nanaimo                            | 0.2.6        |
| xcodeproj                          | 1.12.0       |
| rouge                              | 2.0.7        |
| xcpretty                           | 0.3.0        |
| terminal-notifier                  | 2.0.0        |
| unicode-display_width              | 1.1.3        |
| terminal-table                     | 1.7.3        |
| plist                              | 3.2.0        |
| public_suffix                      | 2.0.5        |
| addressable                        | 2.5.1        |
| multipart-post                     | 2.0.0        |
| word_wrap                          | 1.0.0        |
| tty-screen                         | 0.7.0        |
| tty-cursor                         | 0.7.0        |
| tty-spinner                        | 0.9.1        |
| babosa                             | 1.0.2        |
| colored                            | 1.2          |
| highline                           | 1.7.8        |
| commander-fastlane                 | 4.4.6        |
| excon                              | 0.55.0       |
| faraday                            | 0.17.0       |
| unf_ext                            | 0.0.7.4      |
| unf                                | 0.1.4        |
| domain_name                        | 0.5.20170404 |
| http-cookie                        | 1.0.3        |
| faraday-cookie_jar                 | 0.0.6        |
| faraday_middleware                 | 0.13.1       |
| fastimage                          | 2.1.0        |
| gh_inspector                       | 1.1.3        |
| json                               | 1.8.1        |
| mini_magick                        | 4.9.5        |
| multi_xml                          | 0.6.0        |
| rubyzip                            | 1.3.0        |
| security                           | 0.1.3        |
| xcpretty-travis-formatter          | 0.0.4        |
| dotenv                             | 2.2.0        |
| bundler                            | 1.14.6       |
| naturally                          | 2.2.0        |
| simctl                             | 1.6.5        |
| jwt                                | 2.1.0        |
| uber                               | 0.0.15       |
| declarative                        | 0.0.10       |
| declarative-option                 | 0.1.0        |
| representable                      | 3.0.4        |
| retriable                          | 2.1.0        |
| mime-types-data                    | 3.2016.0521  |
| mime-types                         | 3.1          |
| multi_json                         | 1.12.1       |
| signet                             | 0.11.0       |
| memoist                            | 0.16.0       |
| os                                 | 0.9.6        |
| googleauth                         | 0.6.7        |
| httpclient                         | 2.8.3        |
| google-api-client                  | 0.23.9       |
| google-cloud-env                   | 1.2.0        |
| google-cloud-core                  | 1.3.0        |
| digest-crc                         | 0.4.1        |
| google-cloud-storage               | 1.16.0       |
| emoji_regex                        | 1.0.1        |
| libxml-ruby                        | 3.0.0        |
| psych                              | 2.0.8        |
| fastlane-plugin-versioning_android | 0.1.0        |
</details>

*generated on:* **2019-11-06**
</details></pre>
</details>

**Comment by janpio** [comment]
What code is causing this problem? What action are you executing via what lane?

**Comment by llmagicll** [comment]
I have the same issue with 2.134, 2.140 by exec fastlane supply init  --json_key KEY_PATH
```
Traceback (most recent call last):
	37: from SOMEPATH.rvm/gems/ruby-2.6.3/bin/fastlane:23:in `<main>'
	36: from SOMEPATH.rvm/gems/ruby-2.6.3/bin/fastlane:23:in `load'
	35: from SOMEPATH.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/bin/fastlane:23:in `<top (required)>'
	34: from SOMEPATH.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	33: from SOMEPATH.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	32: from SOMEPATH.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	31: from SOMEPATH.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	30: from SOMEPATH.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	29: from SOMEPATH.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	28: from SOMEPATH.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	27: from SOMEPATH.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	26: from SOMEPATH.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	25: from SOMEPATH.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	24: from SOMEPATH.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	23: from SOMEPATH.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	22: from SOMEPATH.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	21: from SOMEPATH.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	20: from SOMEPATH.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	19: from Fastfile:57:in `block (2 levels) in parsing_binding'
	18: from Fastfile:60:in `do_upload_googleplay'
	17: from SOMEPATH.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	16: from SOMEPATH.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	15: from SOMEPATH.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	14: from SOMEPATH.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	13: from SOMEPATH.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
	12: from SOMEPATH.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	11: from SOMEPATH.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
	10: from SOMEPATH.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/actions/upload_to_play_store.rb:33:in `run'
	 9: from SOMEPATH.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/supply/lib/supply/uploader.rb:7:in `perform_upload'
	 8: from SOMEPATH.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/supply/lib/supply/uploader.rb:419:in `client'
	 7: from SOMEPATH.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/supply/lib/supply/client.rb:18:in `make_from_config'
	 6: from SOMEPATH.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/supply/lib/supply/client.rb:18:in `new'
	 5: from SOMEPATH.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/supply/lib/supply/client.rb:52:in `initialize'
	 4: from SOMEPATH.rvm/gems/ruby-2.6.3/gems/googleauth-0.10.0/lib/googleauth/signet.rb:79:in `fetch_access_token!'
	 3: from SOMEPATH.rvm/gems/ruby-2.6.3/gems/googleauth-0.10.0/lib/googleauth/signet.rb:107:in `retry_with_error'
	 2: from SOMEPATH.rvm/gems/ruby-2.6.3/gems/googleauth-0.10.0/lib/googleauth/signet.rb:80:in `block in fetch_access_token!'
	 1: from SOMEPATH.rvm/gems/ruby-2.6.3/gems/signet-0.12.0/lib/signet/oauth_2/client.rb:1028:in `fetch_access_token!'
SOMEPATH.rvm/gems/ruby-2.6.3/gems/signet-0.12.0/lib/signet/oauth_2/client.rb:1013:in `fetch_access_token': [!] Authorization failed.  Server message: (Signet::AuthorizationError)
{
  "error": "invalid_grant",
  "error_description": "Invalid JWT Signature."
}
```

**Comment by olcayertas** [comment]
Solved the problem by recreating a JSON key in Google Cloud Platform Service accounts section for my current account.
