### ISSUE TITLE
Frameit with Japanes, Korean or Thai texts fails for some device sizes but works for others

### ISSUE THREAD

**Issue by zeusent** [fastlane/fastlane#15607]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Using frameit with Japanes texts fails for some device sizes but works for others.

##### Command executed
bundle exec fastlane frameit

##### Complete output when running fastlane, including the stack trace and command used
Bellow you can see two different outcomes: the first screenshot has the texts set correctly in the final image, the second one doesn't.

<details>
  <pre>[✔] 🚀 
[12:18:57]: Using device frames version 'latest'
[✔] Framing screenshot './fastlane/screenshots/ja/iPhone 8-3-Trends.png' 
[12:19:04]: Added frame: '/Users/{MY_USER}/Developer/iOS Projects/{MY_PROJECT}/fastlane/screenshots/ja/iPhone 8-3-Trends_framed.png'
[⠇] Framing screenshot './fastlane/screenshots/ja/iPhone 11 Pro-3-Trends.png' identify: geometry does not contain image `/var/folders/w3/pg8fvbf17v9cwkjm4d88vfzc0000gn/T/mini_magick20191107-89735-1j2e7qb.png' @ warning/attribute.c/GetImageBoundingBox/507.
[⠴] Framing screenshot './fastlane/screenshots/ja/iPhone 11 Pro-3-Trends.png' identify: geometry does not contain image `/var/folders/w3/pg8fvbf17v9cwkjm4d88vfzc0000gn/T/mini_magick20191107-89735-1z0znau.png' @ warning/attribute.c/GetImageBoundingBox/507.
[⠙] Framing screenshot './fastlane/screenshots/ja/iPhone 11 Pro-3-Trends.png' mogrify: geometry does not contain image `/var/folders/w3/pg8fvbf17v9cwkjm4d88vfzc0000gn/T/mini_magick20191107-89735-1j2e7qb.png' @ warning/transform.c/CropImage/643.
[⠇] Framing screenshot './fastlane/screenshots/ja/iPhone 11 Pro-3-Trends.png' mogrify: geometry does not contain image `/var/folders/w3/pg8fvbf17v9cwkjm4d88vfzc0000gn/T/mini_magick20191107-89735-1z0znau.png' @ warning/transform.c/CropImage/643.
[✔] Framing screenshot './fastlane/screenshots/ja/iPhone 11 Pro-3-Trends.png' 
[12:19:20]: Added frame: '/Users/{MY_USER}/Developer/iOS Projects/{MY_PROJECT}/fastlane/screenshots/ja/iPhone 11 Pro-3-Trends_framed.png'</pre>
</details>

And here's the output of the two:

| iPhone 8                         | iPhone 11 Pro                                                          |
| --------------------------- | -------------------------------------------------------------- |
| ![iPhone 8-3-Trends_framed](https://user-images.githubusercontent.com/777591/68378336-98c2b800-0154-11ea-9e1d-8fbb6af15104.png)                          | ![iPhone 11 Pro-3-Trends_framed](https://user-images.githubusercontent.com/777591/68378356-9fe9c600-0154-11ea-80c5-d65c05999b17.png)                                                        |

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.1                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.21.0 (Apple Git-122.2)                           |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.1 (19B88)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.2.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "{MY_PROJECT}.xcworkspace", scheme: "{MY_PROJECT}UITests")
    frameit(path: './fastlane/screenshots')
    deliver()
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.{MY_PROJECT}.{MY_PROJECT}") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.134.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.68.0       |
| faraday                   | 0.17.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.0.2        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.1009  |
| mime-types                | 3.3          |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.4.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.1        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.13.0       |
| json                      | 2.2.0        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>

*generated on:* **2019-11-07**
</details>

**Comment by zeusent** [comment]
No one? I’m glad to provide more details if needed, just let me know...

**Comment by janpio** [comment]
Thanks for the report @zeusent. Can you maybe provide a minimal reproduction (New app, minimal fastlane config required to get to this result) in a Github repo for us? Getting there by ourselves would require quite some time investment, so this would _really_ help.

**Comment by janpio** [comment]
@zeusent Did you mabye have the time to create a reproduction of this for us?
