### ISSUE TITLE
[Regression] Match[!] Can't find class 'adhoc`

### ISSUE THREAD

**Issue by algera** [fastlane/fastlane#15606]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information
Breaking version: 2.28.3
Last working version: 2.134.0

### Regression Description
Installing fastlane via Homebrew installs version 2.28.3
``` brew update && brew cask reinstall fastlane```
Q: Should this be 2.134.0?

This is having problems with match finding `adhoc`
Fastfile has this:
```match(type: "adhoc", app_identifier: "com.app.id")```
Output is this:
```[!] Can't find class 'adhoc' (RuntimeError)```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[17:41:10]: Installing provisioning profile...

Looking for related GitHub issues on fastlane/fastlane...

➡️  Notification extension is failing to access app group shared folder
   https://github.com/fastlane/fastlane/issues/14529 [closed] 16 💬
   2 weeks ago

➡️  "Can't find class 'adhoc' (RuntimeError)" when running "fastlane sigh" to download profiles
   https://github.com/fastlane/fastlane/issues/14014 [closed] 8 💬
   08 May 2019

➡️  "Can't find class 'adhoc' when generating new profiles with match
   https://github.com/fastlane/fastlane/issues/14152 [closed] 5 💬
   22 Apr 2019

and 50 more at: https://github.com/fastlane/fastlane/search?q=Can%27t%20find%20class%20%27adhoc%27&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/spaceship/lib/spaceship/portal/provisioning_profile.rb:177:in `factory': [!] Can't find class 'adhoc' (RuntimeError)
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/spaceship/lib/spaceship/portal/provisioning_profile.rb:275:in `block in all'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/spaceship/lib/spaceship/portal/provisioning_profile.rb:275:in `map!'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/spaceship/lib/spaceship/portal/provisioning_profile.rb:275:in `all'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/match/lib/match/spaceship_ensure.rb:54:in `profile_exists'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/match/lib/match/runner.rb:142:in `fetch_provisioning_profile'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/match/lib/match/runner.rb:40:in `block (2 levels) in run'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/match/lib/match/runner.rb:39:in `loop'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/match/lib/match/runner.rb:39:in `block in run'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/match/lib/match/runner.rb:38:in `each'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/match/lib/match/runner.rb:38:in `run'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/match/lib/match/commands_generator.rb:39:in `block (2 levels) in run'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:40:in `run!'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/match/lib/match/commands_generator.rb:130:in `run'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/match/lib/match/commands_generator.rb:12:in `start'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/me/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/bin/fastlane:20:in `<top (required)>'
	from /Users/me/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/me/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0 (Apple Git-122)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.6 (18G103)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

platform :ios do

  lane :a do

    match(type: "adhoc", app_identifier: "com.X")

  end

end
```
</details>

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.28.3  | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.13.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.17.0       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.13.1       |
</details>

*generated on:* **2019-11-06**
</details></pre>
</details>

**Comment by RockyAo** [comment]
I got the same error with fastlane 2.28.3

**Comment by algera** [comment]
With `verbose` on

<pre>
INFO [2019-11-06 19:15:26.15]: Installing provisioning profile...
WARN [2019-11-06 19:15:26.49]: Lane Context:
INFO [2019-11-06 19:15:26.49]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios alpha", :GIT_REPO_WAS_CLEAN_ON_START=>true, :BUILD_NUMBER=>"90"}
ERROR [2019-11-06 19:15:26.49]: Can't find class 'adhoc'
INFO [2019-11-06 19:15:26.49]: Successfully generated documentation at path '/Users/me/Projects/co/ios/fastlane/README.md'

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | default_platform       | 0           |
| 2    | ensure_git_status_cle  | 0           |
|      | an                     |             |
| 3    | git_pull               | 3           |
| 4    | cp ../../app.json.aaa  | 0           |
|      | ../../app.json         |             |
| 5    | increment_build_numbe  | 0           |
|      | r                      |             |
| 6    | commit_version_bump    | 0           |
| 7    | add_git_tag            | 0           |
| 8    | push_to_git_remote     | 3           |
| 💥   | match                  | 4           |
+------+------------------------+-------------+

ERROR [2019-11-06 19:15:26.50]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: Can't find class 'adhoc'
</pre>

**Comment by RockyAo** [comment]
@algera I solved this problem by reinstall fastlane.  

1、I try to use the command below to reinstall fastlane but I got an error when signet try to install. 
```swift
brew cask reinstall fastlane 
```
2、I uninstall the fastlane by homebrew and reinstall using gem. then everything solved

**Comment by floriannagel** [comment]
Same on Version 2.28.3
```
factory': [!] Can't find class 'adhoc' (RuntimeError)
```

Tried @RockyAo solution and reinstalled fastlane with
```
brew cask reinstall fastlane 
```
Nothing changed.. need match for a production build...

**Comment by algera** [comment]
Which version of fast lane is installed when going through `gem install`? 
`fastlane --version`

This may be a 2.28.3 problem only.  I am unable to install with `gem install` for a separate reason.,

**Comment by algera** [comment]
Related to https://github.com/fastlane/fastlane/issues/15496

**Comment by algera** [comment]
I was able to jettison Homebrew and switch to ruby-based installation via https://github.com/fastlane/fastlane/issues/15496#issuecomment-551127230

This remains valid but no longer a blocker for me.

**Comment by RockyAo** [comment]
@algera 

```swift
fastlane -v
fastlane installation at path:
/usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/bin/fastlane
-----------------------------
[✔] 🚀
fastlane 2.134.0
```

**Comment by janpio** [comment]
This is a result of a wrong version being installed, see https://github.com/fastlane/fastlane/issues/15496
