### ISSUE TITLE
TestRunner App not being created

### ISSUE THREAD

**Issue by MikeBenton2** [fastlane/fastlane#15609]
### Question Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
What tool/action do you have a question about?
Fastlane Gym
Is this a question about documentation?
No
Is this a question about a third party plugin? (If so, please go to the plugin repository first)
No

#### Question Description

So my company has been using Fastlane for awhile and I recently started to work on this. We currently use Microsofts AppCenter to test our apps, but I'm having issues uploading the app to the App Center after making a build with Gym. So normally when I make a build it produces an app in Derived Data called <Target Name>-Runner. When you go to edit schemes in Xcode you'll find this:
![Screen Shot 2019-11-07 at 11 04 07 AM](https://user-images.githubusercontent.com/49599249/68410468-631ad080-014e-11ea-9da0-b2fc57d4f08c.png)

I've tried using Gym to supplied this to both xcargs and export_xcargs
"build-for-testing"

But no luck still. I found this post and tried using xcodebuild, but that didn't work either. Is there a way for me to use Gym and produce that Runner app?

https://github.com/fastlane/fastlane/issues/12184

**Comment by janpio** [comment]
What kind of Runner app do you mean?
Did you maybe also change the Xcode version you are using?

Please also see the comment of @fastlane-bot

**Comment by MikeBenton2** [comment]
@janpio Closing this ticket due to user error.

**Comment by janpio** [comment]
User error is best error 🚀
