### ISSUE TITLE
Add a confirmation to push_to_git_remote

### ISSUE THREAD

**Issue by myihsan** [fastlane/fastlane#15615]
### Feature Request
Confirm with the user before using `master` branch if `local_branch` hasn't been set.

#### Motivation Behind Feature

`push_to_git_remote` uses `git_branch` to get the current branch if `local_branch` hasn't been set, 
and if `git_branch` failed, `push_to_git_remote` will use `master` branch automatically.

I don't know if this is a common need, but if `git_branch` failed because of some accidents, for example, an encoding issue, using `master` branch is possibly unexpected for the user.

So confirming with the user may be a solution for this kind of situation.

#### Feature Description

Add a `UI.confirm` before using `master` branch automatically as follow:

``` ruby
unless local_branch
  if UI.confirm('Failed to get the current branch, continue with "master" branch?')
    local_branch = 'master'
  else
    UI.user_error!('Failed to get the current branch.')
  end
end
```

#### Alternatives or Workarounds

Run `git_branch` first to check the result.

**Comment by myihsan** [comment]
@janpio 
Is there anything I can do for this issue?
Should I create a pull request with the code above?

**Comment by myihsan** [comment]
The issue is still relevant.

**Comment by myihsan** [comment]
@janpio
Could you tell me if we should do something about this issue?
If we should, I can create a pull request for it. If not, please close this issue by a human to let me know the decision.

**Comment by janpio** [comment]
The way you described it above, this would be a breaking change for all people that rely on the functionality right now. It might also not work at all in non interactive environments, right? I think this might need some polishing.

And yes, a Pull Request would definitely be nice - then we can decide on the actual code and not just an idea.
