### ISSUE TITLE
gradle error

### ISSUE THREAD

**Issue by DavidUps** [fastlane/fastlane#15613]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                |
| --------------------------- | ------------------------------------ |
| OS                          | 10.15.1                              |
| Ruby                        | 2.2.4                                |
| Bundler?                    | false                                |
| Git                         | git version 2.21.0 (Apple Git-122)   |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane  |
| Host                        | Mac OS X 10.15.1 (19B88)             |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib           |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016           |
| Is contained                | false                                |
| Is homebrew                 | true                                 |
| Is installed via Fabric.app | false                                |
| Xcode Path                  | /Library/Developer/CommandLineTools/ |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Google Play Beta"
  lane :beta do
    increment_version_code(gradle_file_path: "app/build.gradle")
    versionname = get_version_name(gradle_file_path:"app/build.gradle", ext_constant_name:"versionName")
    versioncode = get_version_code(gradle_file_path:"app/build.gradle", ext_constant_name:"versionCode")

    gradle(task: 'assemble', build_type: 'Pro')
    upload_to_play_store(track: 'beta', apk: 'app/build/outputs/apk/pro/release/app-pro-release.apk')
    add_git_tag( tag: "PlayStore_v#{versionname}-#{versioncode}-BETA")
  end

  desc "Submit a new Beta Build to Firebase PRE"
  lane :pre_firebase do
    
    gradle(task: "assemble", build_type: "Pre")

    firebase_app_distribution(
      app: "1:370593141663:android:83824edc02a779ff09a3aa",
      groups: "dev",
      release_notes: "Lots of amazing new features to test out!",
    )

    add_git_tag(tag: "Firebase_v#{versionname}-#{versioncode}-PRE")
  end

end```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "com.davidups.starwars" # e.g. com.krausefx.app
```
</details>

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.28.3  | 💥 Check failed |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status  |
| ----------------------------------------- | ------- | -------------- |
| fastlane-plugin-get_version_name          | 0.2.2   | 💥 Check failed |
| fastlane-plugin-increment_version_code    | 0.4.3   | 💥 Check failed |
| fastlane-plugin-get_version_code          | 0.2.0   | 💥 Check failed |
| fastlane-plugin-firebase_app_distribution | 0.1.4   | 💥 Check failed |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| slack-notifier                            | 1.5.1        |
| atomos                                    | 0.1.3        |
| claide                                    | 1.0.3        |
| colored2                                  | 3.1.2        |
| nanaimo                                   | 0.2.6        |
| xcodeproj                                 | 1.13.0       |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| terminal-notifier                         | 1.7.1        |
| unicode-display_width                     | 1.1.3        |
| terminal-table                            | 1.7.3        |
| CFPropertyList                            | 2.3.5        |
| multipart-post                            | 2.0.0        |
| word_wrap                                 | 1.0.0        |
| tty-screen                                | 0.5.0        |
| colored                                   | 1.2          |
| commander-fastlane                        | 4.4.6        |
| faraday                                   | 0.17.0       |
| unf_ext                                   | 0.0.7.4      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20170404 |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.6        |
| gh_inspector                              | 1.1.3        |
| uber                                      | 0.0.15       |
| representable                             | 2.3.0        |
| retriable                                 | 2.1.0        |
| mime-types                                | 3.1          |
| hurley                                    | 0.2          |
| little-plugger                            | 1.1.4        |
| logging                                   | 2.2.2        |
| jwt                                       | 1.5.6        |
| memoist                                   | 0.16.0       |
| os                                        | 0.9.6        |
| signet                                    | 0.7.3        |
| googleauth                                | 0.5.1        |
| httpclient                                | 2.8.3        |
| google-api-client                         | 0.9.28       |
| json                                      | 1.8.1        |
| mini_magick                               | 4.5.1        |
| multi_xml                                 | 0.6.0        |
| rubyzip                                   | 1.3.0        |
| security                                  | 0.1.3        |
| xcpretty-travis-formatter                 | 0.0.4        |
| bundler                                   | 1.14.6       |
| faraday_middleware                        | 0.13.1       |
| highline                                  | 1.7.10       |
| excon                                     | 0.68.0       |
| plist                                     | 3.5.0        |
| babosa                                    | 1.0.3        |
| fastimage                                 | 2.1.7        |
| fastlane-plugin-get_version_name          | 0.2.2        |
| fastlane-plugin-increment_version_code    | 0.4.3        |
| fastlane-plugin-get_version_code          | 0.2.0        |
| fastlane-plugin-firebase_app_distribution | 0.1.4        |
</details>

*generated on:* **2019-11-08**
</details>

**Comment by janpio** [comment]
You problem is that you are using a very old version. See https://github.com/fastlane/fastlane/issues/15496
