### ISSUE TITLE
Support for Passbook (Pass Type IDs, certificates)

### ISSUE THREAD

**Issue by maxx-cyber** [fastlane/fastlane#15628]
Come on guys, this feature request is always autoclosed by bot. This feature is needed as air for us. We support 200+ apple developer accounts in which we create Pass Type IDs and Certificates manually. It is a hell to manage its expiration.

**Comment by maxx-cyber** [comment]
Anybody?
It is feature request related to https://github.com/fastlane/fastlane/issues/2067 and https://github.com/fastlane/fastlane/issues/6799.

**Comment by janpio** [comment]
Thanks for your feature request @maxx-cyber - looking forward to reviewing your PR to add this functionality to Fastlane.

**Comment by maxx-cyber** [comment]
Any updates?

**Comment by njoerd114** [comment]
obviously not. you'd have to contribute to get this working. Let me have a look between the years and see if i can contribute. We only need this for one cert internally, but still would like to automate this.

**Comment by maxx-cyber** [comment]
Hi @njoerd114 
What do you mean when you said one cert internally?
Let me explain my case in details. We have white labeled apps. Due to Apple has forbidden white labeled apps in a single Apple Developer Program account, we publish apps in separate client's accounts. One app - one Apple Developer Program account. Currently we already have about 300 separate accounts and this number will grow at least to 600. Now we create Pass Type ID and Certificate in each of them manually and we don't have any mechanism to monitor pass type certificate expiration. It is a hell for us to setup and manage expiration manually.
I don't have appropriate expertise to develop this feature in fastlane by myself, but we really need it as an air. Please help.

**Comment by njoerd114** [comment]
we've got one situation where we need one single cert, but still monitoring certificate expiry is pita.
so that's why i wanted to automate this anyways. i don't want to imagine the pain of having to do this manually for 1000+ certs.

how comes there's nobody in your company that is able to contribute, though? should be an easy task... you don't need to implement this personally, perhaps you just need to have one of your devs have a look at it. - if not, as i already said: i'm going to have a look for it just after xmas, but can't make no promises right now as i did not even have a look at the code yet.

**Comment by maxx-cyber** [comment]
I'm afraid we don't have anyone who can look at it. After xmas sounds good. I will look forward to your reply.

**Comment by njoerd114** [comment]
I'm using a workaround for now - and we're saving the result directly to hashicorps vault, feel free to adopt this snippet to your needs:
```ruby
require 'spaceship'
require 'vault'

id = ENV["PASSKIT_ID"]
pass_name = ENV["PASSKIT_NAME"]
team_id = Spaceship::Portal.select_team

Vault.auth.approle(ENV["VAULT_APPROLE_ID"], ENV["VAULT_SECRET_ID"])
apple_login = Vault.logical.read("path/to/apple/developer/credentials")
apple_login = apple_login.data[:data]
puts "Logging into Apple Developer Portal as " + apple_login[:user]

Spaceship::Portal.login(apple_login[:user], apple_login[:password])
puts "Creating Certificate for Pass Identifier " + id
passbook = Spaceship::Portal.passbook.find(id)
if !passbook
    passbook = Spaceship::Portal.passbook.create!(bundle_id: id, name: pass_name)
end
csr, pkey = Spaceship::Portal.certificate.create_certificate_signing_request
csr = OpenSSL::X509::Request.new(csr) if csr.kind_of?(String)
r = Spaceship::Portal.client.request(:post, "account/ios/certificate/submitCertificateRequest.action", {
    teamId: team_id,
    type: "Y3B2F3TYSI",
    csrContent: csr.to_pem,
    passTypeId: passbook.passbook_id,
    specialIdentifierDisplayId: passbook.passbook_id
  })
response = Spaceship::Portal.client.parse_response(r, 'certRequest')
certificate_id = response['certificateId']
cert = Spaceship::Portal.certificate.find(certificate_id).download
password = ('a'..'z').to_a.shuffle[0,8].join
Vault.logical.write("some/path/in/vault" + id, data: {passTypeIdentifier: id, teamIdentifier: team_id, privateKey: pkey, certificate: cert, password: password})
puts "Success!"
```
