### ISSUE TITLE
[supply] Uploading metadata fails due to more than one release even when version code is specified

### ISSUE THREAD

**Issue by mduong** [fastlane/fastlane#15626]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

In using the new `supply` in 2.135.0 to upload a 'draft' release, there is an error at https://github.com/fastlane/fastlane/blob/master/supply/lib/supply/uploader.rb#L89 even though a version code is specified (although shouldn't be required as it uses the version code of the APK uploaded if only one). It looks like `releases` may need to filter by `version_code` before the `releases.size` check?

On a related note, the `version_code` option expects a String instead of an int. Should it be an int?

@joshdholtz

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[17:01:04]: ----------------------------------
[17:01:04]: --- Step: upload_to_play_store ---
[17:01:04]: ----------------------------------

+-------------------------+---------------------------------------------------------------------------------+
|                                        Summary for supply 2.135.0                                         |
+-------------------------+---------------------------------------------------------------------------------+
| track                   | beta                                                                            |
| release_status          | draft                                                                           |
| version_code            | 242                                                                             |
| skip_upload_images      | true                                                                            |
| skip_upload_metadata    | true                                                                            |
| skip_upload_screenshots | true                                                                            |
| mapping                 | /home/circleci/code/Betterment/build/outputs/mapping/release/mapping.txt        |
| apk                     | /home/circleci/code/Betterment/build/outputs/apk/release/Betterment-release.apk |
| package_name            | com.betterment                                                                  |
| metadata_path           | ./fastlane/metadata/android                                                     |
| json_key                | google-play-key.json                                                            |
| skip_upload_apk         | false                                                                           |
| skip_upload_aab         | false                                                                           |
| skip_upload_changelogs  | false                                                                           |
| GRADLE_ALL_APK_OUTPUT_PATHS         | ["/home/circleci/code/Betterment/build/outputs/apk/release/Betterment-release.apk"] |
| GRADLE_ALL_AAB_OUTPUT_PATHS         | []                                                                                  |
| GRADLE_ALL_OUTPUT_JSON_OUTPUT_PATHS | ["/home/circleci/code/Betterment/build/outputs/apk/release/output.json"]            |
| GRADLE_APK_OUTPUT_PATH              | /home/circleci/code/Betterment/build/outputs/apk/release/Betterment-release.apk     |
| GRADLE_OUTPUT_JSON_OUTPUT_PATH      | /home/circleci/code/Betterment/build/outputs/apk/release/output.json                |
+-------------------------------------+-------------------------------------------------------------------------------------+
[17:01:14]: More than one release found in this track. Please specify with the :version_code option to select a release.

+------+-----------------------------+-------------+
|                 fastlane summary                 |
+------+-----------------------------+-------------+
| Step | Action                      | Time (in s) |
+------+-----------------------------+-------------+
| 1    | default_platform            | 0           |
| 2    | ensure_git_status_clean     | 0           |
| 3    | Switch to android test lane | 0           |
| 4    | gradle                      | 134         |
| 5    | gradle                      | 94          |
| 💥   | upload_to_play_store        | 10          |
+------+-----------------------------+-------------+

[17:01:14]: fastlane finished with errors

[!] More than one release found in this track. Please specify with the :version_code option to select a release.
Exited with code 1</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by joshdholtz** [comment]
@mduong Thanks for the ping! Looking into and will comment more when I have thoughts 😊

**Comment by joshdholtz** [comment]
@mduong Yes yes, you are right! Not sure how the filter on version code didn't get moved above that 😇 Testing, fixing, testing, and then releasing fix for this

**Comment by joshdholtz** [comment]
@mduong Quick question for you! Do thing work for you if you don't specify `:version_code`? You actually don't need to specify version code when uploading an APK/AAB. The `:version_code` is supposed to be used when _not_ uploading APKs/AABs which is probably a bit unclear on my part 😱

**Comment by mduong** [comment]
Yup, I tried both and they both give me that error. I believe this happens because there's currently a release in my beta track and the lane that's being executed is uploading another release but a draft release so now there are 2 releases in the track. Previously, there was no 'draft' functionality so there was only ever one release per track when a new one was published.

**Comment by joshdholtz** [comment]
OHHHHHHH.... ohhh... oh? Interesting! Thanks for that info 😊 Back to testing 💪

**Comment by joshdholtz** [comment]
@mduong Fixed! PR coming out in about 5 minutes, will try to get it reviewed in 10 minutes after that, and then released in 30 minutes after that PR is merged 🚀

**Comment by mduong** [comment]
Thank you for the quick responses and quick fix!
