### ISSUE TITLE
Fastlane verifies default value when ENV variable set

### ISSUE THREAD

**Issue by mik9** [fastlane/fastlane#15629]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm using https://github.com/fastlane-community/fastlane-plugin-firebase_app_distribution plugin and configuring it with ENV variables.

`firebase_app_distribution` action has `firebase_cli_path` config item with `env_name`, `default_value` and `verify_block`.

When I set ENV variable:
```
ENV['FIREBASEAPPDISTRO_FIREBASE_CLI_PATH'] = "./firebase"
```

Fastlane tries to run `verify_block` on `default_value` anyway and it fails.
When I vall action like this:
```
firebase_app_distribution(app: "...", firebase_cli_path: "./firebase")
```

It works fine.

The issue is here: https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/configuration/configuration.rb#L141. `verify_default_value_matches_verify_block` does not run when value were passed for an option. But it does not check for ENV variable.

### Environment
<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.3.0        |
| slack-notifier                            | 2.3.2        |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.6.0        |
| terminal-table                            | 1.8.0        |
| plist                                     | 3.5.0        |
| multipart-post                            | 2.0.0        |
| word_wrap                                 | 1.0.0        |
| public_suffix                             | 2.0.5        |
| tty-screen                                | 0.7.0        |
| tty-cursor                                | 0.7.0        |
| tty-spinner                               | 0.9.1        |
| colored                                   | 1.2          |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| unf_ext                                   | 0.0.7.6      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.6        |
| faraday                                   | 0.17.0       |
| faraday_middleware                        | 0.13.1       |
| gh_inspector                              | 1.1.3        |
| json                                      | 2.2.0        |
| mini_magick                               | 4.9.5        |
| multi_xml                                 | 0.6.0        |
| rubyzip                                   | 1.3.0        |
| security                                  | 0.1.3        |
| xcpretty-travis-formatter                 | 1.0.0        |
| dotenv                                    | 2.7.5        |
| bundler                                   | 2.0.2        |
| jwt                                       | 2.1.0        |
| uber                                      | 0.1.0        |
| declarative                               | 0.0.10       |
| declarative-option                        | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| memoist                                   | 0.16.0       |
| multi_json                                | 1.13.1       |
| os                                        | 1.0.1        |
| googleauth                                | 0.6.7        |
| httpclient                                | 2.8.3        |
| google-api-client                         | 0.23.9       |
| digest-crc                                | 0.4.1        |
| google-cloud-storage                      | 1.16.0       |
| emoji_regex                               | 1.0.1        |
| nanaimo                                   | 0.2.6        |
| colored2                                  | 3.1.2        |
| claide                                    | 1.0.3        |
| CFPropertyList                            | 3.0.1        |
| atomos                                    | 0.1.3        |
| xcodeproj                                 | 1.12.0       |
| addressable                               | 2.7.0        |
| babosa                                    | 1.0.3        |
| excon                                     | 0.67.0       |
| fastimage                                 | 2.1.7        |
| naturally                                 | 2.2.0        |
| simctl                                    | 1.6.6        |
| mime-types-data                           | 3.2019.1009  |
| mime-types                                | 3.3          |
| signet                                    | 0.12.0       |
| google-cloud-env                          | 1.2.1        |
| google-cloud-core                         | 1.3.1        |
| fastlane-plugin-firebase_app_distribution | 0.1.4        |
</details>

**Comment by janpio** [comment]
> `verify_default_value_matches_verify_block` does not run when value were passed for an option. But it does not check for ENV variable.

I do not understand what you are saying here.

Can you provide a simple way to reproduce what you are describing? A `Fastfile` with 2 lanes for example, so we can easily reproduce?

**Comment by mik9** [comment]
Sorry. I meant `verify_default_value_matches_verify_block` runs verification on default value when ENV variable set. Example fastfile:

```
default_platform(:android)

platform :android do

  before_all do
    ENV['FIREBASEAPPDISTRO_FIREBASE_CLI_PATH'] = "./firebase"
  end

  desc "Submit a new Test Build to Crashlytics Beta and Firebase App distribution"
  lane :betaProd do
    # gradle(task: "assembleProductionRelease")
    firebase_app_distribution(app: "...")
  end
end
```

It uses `gem 'fastlane-plugin-firebase_app_distribution', '~> 0.1.2'` plugin. We setting `FIREBASEAPPDISTRO_FIREBASE_CLI_PATH` variable here but Fastlane will run verification on `/usr/bin/firebase`. 

Hope this helps. If it doesn’t I will be able to provide complete example in a week.

**Comment by mik9** [comment]
Attached reproduction sample [fastlane-default-bug.zip](https://github.com/fastlane/fastlane/files/3984828/fastlane-default-bug.zip).
Before trying to reproduce its important that you does *not* have valid firebase executable at `/usr/local/bin/firebase`.

Steps:
1. Unzip.
2. Run `fastlane betaProd`. You'll see next error:
```
firebase_cli_path: `/usr/local/bin/firebase` does not support the `appdistribution:distribute` command. Please download (https://appdistro.page.link/firebase-cli-download) or specify the path to the correct version of firebse
```
Fastlane tries to validate [default value](https://github.com/fastlane-community/fastlane-plugin-firebase_app_distribution/blob/a5b1b84e883d4251dc5db6f3ffd4a7c932947d87/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb#L92) despite we set [environment variable](https://github.com/fastlane-community/fastlane-plugin-firebase_app_distribution/blob/a5b1b84e883d4251dc5db6f3ffd4a7c932947d87/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb#L90) for this parameter.
3. Uncomment line 6 and run `fastlane betaProd` again. You'll see another error because fastlane will try to validate `firebase_cli_path: "./firebase"`.

Expected behavior: Step 2 and Step 3 should behave in a same way.
