### ISSUE TITLE
Transporter Error: Old Toolchain not supported anymore

### ISSUE THREAD

**Issue by Ahmadre** [fastlane/fastlane#15624]
### New Issue Checklist

- [ x ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Fastlane always worked for me, but today when I build my iOS app to testflight it gets the error on the bottom. Could someone update the XCode version to 11 ? Also for Android it's an old SDK for uploading and google is warning me too.

Greetings
Rebar

##### Command executed

```bash
   build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
   upload_to_testflight(skip_waiting_for_build_processing: true)
```

##### Complete output when running fastlane, including the stack trace and command used

```bash
[16:41:53]: Going to upload updated app to App Store Connect
[16:41:53]: This might take a few minutes. Please don't interrupt the script.
[16:42:46]: [Transporter Error Output]: ERROR ITMS-90534: "Invalid Toolchain. Your app was built with an unsupported version of Xcode or SDK. If you plan to submit this build to the App Store, make sure you are using the GM version of Xcode 10.1 and the SDK for iOS 12.1 and watchOS 5.1, Xcode 7.1 and the SDK for tvOS 9, or Xcode 6 and the SDK for macOS 10.9 or later. If you are using an Xcode beta version to test your app, make sure you are using the latest supported version. For more information about supported beta versions, view the App Store Connect What's New page (https://developer.apple.com/app-store-connect/whats-new/)."
[16:42:46]: [Transporter Warning Output]: WARNING ITMS-90703: "Deprecated Xcode Build. Due to resolved app archives issues, we have deprecated Xcode 11.2 on November 5, 2019. Download Xcode 11.2.1 or newer, rebuild your app and resubmit."
[16:42:46]: Transporter transfer failed.
[16:42:46]: WARNING ITMS-90703: "Deprecated Xcode Build. Due to resolved app archives issues, we have deprecated Xcode 11.2 on November 5, 2019. Download Xcode 11.2.1 or newer, rebuild your app and resubmit."
```

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre></pre>
</details>

**Comment by leopic** [comment]
The last line of the error will give you the answer, Apple deprecated Xcode 11.2, you must download Xcode 11.2.1 GM
```
[16:42:46]: WARNING ITMS-90703: "Deprecated Xcode Build.
Due to resolved app archives issues, we have deprecated Xcode 11.2 on November 5, 2019. 
Download Xcode 11.2.1 or newer, rebuild your app and resubmit."
```

**Comment by Ahmadre** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.1                                     |
| Ruby                        | 2.5.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.15.1 (19B88)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.3/lib            |
| OpenSSL Version             | OpenSSL 1.0.2p  14 Aug 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.2                                        |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.135.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.13.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.68.0       |
| faraday                   | 0.17.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.16.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.1009  |
| mime-types                | 3.3          |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.4.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| openssl                   | 2.1.2        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.5       |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
</details>


*generated on:* **2019-11-11**
</details>

Forgot my details. 

Oh thank you so much @leopic 😄 and sorry for taking your time

**Comment by Ahmadre** [comment]
<img width="751" alt="Bildschirmfoto 2019-11-11 um 17 44 08" src="https://user-images.githubusercontent.com/18512224/68604497-ea4ba980-04aa-11ea-9588-00ea21e6aa97.png">

That's weird....I don't get any updates...

**Comment by leopic** [comment]
Since it's a GM, is not in the App Store yet, you must get it from the Developer Portal, more info here https://stackoverflow.com/questions/44323009/cant-submit-apps-to-appstore-error-itms-90534-invalid-toolchain/58747930#58747930

**Comment by Ahmadre** [comment]
Oh Thank you sooo much ❤️ ! I'm relatively new to MacOS. I googled too, but didn't get the answer as fast as you ^^

**Comment by leopic** [comment]
It's all good, we are all learning here, have a good day.
