### ISSUE TITLE
[!] 785: unexpected token at '<!DOCTYPE html> (JSON::ParserError)

### ISSUE THREAD

**Issue by RSickenberg** [fastlane/fastlane#15631]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: [`2.135.1`]
- Last working version: [`2.134.0`]

### Regression Description

```
/Users/romainsickenberg/.rvm/gems/ruby-2.2.7/gems/json-2.2.0/lib/json/common.rb:156:in `parse': [!] 785: unexpected token at '<!DOCTYPE html> (JSON::ParserError)
<html lang="en">
<head>
    <style>
        body {
            font-family: "Helvetica Neue", "HelveticaNeue", Helvetica, Arial, sans-serif;
            font-size: 15px;
            font-weight: 200;
            line-height: 20px;
            color: #4c4c4c;
            text-align: center;
        }

        .section {
            margin-top: 50px;
        }
    </style>
</head>
<body>
<div class="section">
    <h1>&#63743;</h1>

    <h3>Gateway Timeout</h3>
    <p>Correlation Key: 2HTSJ7FXTHWSMDBAOZDAK4Z3</p>
</div>
</body>
</html>

'
	from /Users/romainsickenberg/.rvm/gems/ruby-2.2.7/gems/json-2.2.0/lib/json/common.rb:156:in `parse'
	from /Users/romainsickenberg/.rvm/gems/ruby-2.2.7/gems/fastlane-2.135.1/spaceship/lib/spaceship/client.rb:521:in `fetch_olympus_session'
	from /Users/romainsickenberg/.rvm/gems/ruby-2.2.7/gems/fastlane-2.135.1/spaceship/lib/spaceship/client.rb:490:in `send_shared_login_request'
	from /Users/romainsickenberg/.rvm/gems/ruby-2.2.7/gems/fastlane-2.135.1/spaceship/lib/spaceship/tunes/tunes_client.rb:127:in `send_login_request'
	from /Users/romainsickenberg/.rvm/gems/ruby-2.2.7/gems/fastlane-2.135.1/spaceship/lib/spaceship/client.rb:770:in `do_login'
	from /Users/romainsickenberg/.rvm/gems/ruby-2.2.7/gems/fastlane-2.135.1/spaceship/lib/spaceship/client.rb:384:in `login'
	from /Users/romainsickenberg/.rvm/gems/ruby-2.2.7/gems/fastlane-2.135.1/spaceship/lib/spaceship/client.rb:346:in `login'
```

### Environment

<details>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.1                                     |
| Ruby                        | 2.2.7                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.20.1                          |
| Installation Source         | ~/.rvm/gems/ruby-2.2.7/bin/fastlane         |
| Host                        | Mac OS X 10.15.1 (19B88)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.2.7/lib                |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.2.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    ensure_git_status_clean
    increment_build_number
    cocoapods(
        clean: true,
        podfile: "Podfile",
        try_repo_update_on_error: true
    )
    build_app(workspace: "project.xcworkspace", scheme: "Project")
    upload_to_testflight(skip_waiting_for_build_processing: true)

  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("SANITIZED") # The bundle identifier of your app
apple_id("SANITIZED") # Your Apple email address

itc_team_id("SANITIZED") # App Store Connect Team ID
team_id("SANITIZED") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.135.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.1       |
| CFPropertyList            | 3.0.1        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.7.0        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.2.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.1        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.2.0        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.13.0       |
| cocoapods                 | 1.7.0        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.68.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.17.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.1       |
| multi_json                | 1.14.1       |
| os                        | 1.0.1        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.1009  |
| mime-types                | 3.3          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.2        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2019-11-11**
</details>
</details>

# Comments
<pre>I'm aware it's due to Apple Gateway failure</pre>

**Comment by MartinGonzalez** [comment]
Is there any news about this? I'm getting this error too with version
`fastlane (2.103.1)`

**Comment by rkuncewicz** [comment]
Also getting this issue, started two days ago with fastlane version `2.107.0`. 
```
/Library/Ruby/Gems/2.3.0/gems/json-2.1.0/lib/json/common.rb:156:in `parse': [!] 765: unexpected token at '<!DOCTYPE html> (JSON::ParserError)
<html lang="en">
<head>
    <style>
        body {
            font-family: "Helvetica Neue", "HelveticaNeue", Helvetica, Arial, sans-serif;
            font-size: 15px;
            font-weight: 200;
            line-height: 20px;
            color: #4c4c4c;
            text-align: center;
        }

        .section {
            margin-top: 50px;
        }
    </style>
</head>
<body>
<div class="section">
    <h1>&#63743;</h1>

    <h3>Not Found</h3>
    <p>The requested page could not be found.</p>
</div>
</body>
</html>
```

**Comment by jbolter** [comment]
Anybody have any workarounds? We are experiencing this also.

**Comment by asishr14** [comment]
Same error on fastlane version 2.115.0



[!] 784: unexpected token at '<!DOCTYPE html> (JSON::ParserError)
<html lang="en">
<head>
    <style>
        body {
            font-family: "Helvetica Neue", "HelveticaNeue", Helvetica, Arial, sans-serif;
            font-size: 15px;
            font-weight: 200;
            line-height: 20px;
            color: #4c4c4c;
            text-align: center;
        }

        .section {
            margin-top: 50px;
        }
    </style>
</head>
<body>
<div class="section">
    <h1>&#63743;</h1>

    <h3>Not Found</h3>
    <p>The requested page could not be found.</p>
</div>
</body>
</html>

**Comment by jbolter** [comment]
It looks like the older version of fastlane that we were using (2.113.0) was using a URL that no longer works to authenticate with apple.  Upgraded to 2.135.2 and now we are able to build again.

**Comment by gruaig** [comment]
Still failing for me on  2.135.2.

**Comment by pnandala** [comment]
2.136 fixed this issue for me

**Comment by MartinGonzalez** [comment]
@RSickenberg considering closing this issue?

**Comment by RSickenberg** [comment]
@MartinGonzalez Yes!
