### ISSUE TITLE
ramifications of scan with skip_detect_devices

### ISSUE THREAD

**Issue by jamezilla** [fastlane/fastlane#15637]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
When using `scan`, what is the effect of running it with `skip_detect_devices`?
 
#### Question Description
We have a persistent issue when CI is under heavy load where `scan` times out like this:
```
$ xcodebuild -showBuildSettings -workspace ./MyWorkspace.xcworkspace -scheme Debug
Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...
Command timed out after 6 seconds on try 2 of 4, trying again with a 12 second timeout...
Command timed out after 12 seconds on try 3 of 4, trying again with a 24 second timeout...
Command timed out after 24 seconds on try 4 of 4
```
I suspect it's timing out on simulator detection. We're not specifying `device` or `devices` in the scan config, so it's possible adding the device explicitly will solve this issue, but I'm intrigued by `skip_detect_devices`. However, the docs just say `Should skip auto detecting of devices if none were specified` without explaining why you'd want to do that or what happens if you do.

**Comment by janpio** [comment]
The PR that added the functionality has some background: https://github.com/fastlane/fastlane/pull/13285

Here is the code that is executed if the `skip` is not defined:
https://github.com/fastlane/fastlane/blob/24fb2c9552a3367f41101764abf31ecc548e27d4/scan/lib/scan/detect_values.rb#L169-L185
