### ISSUE TITLE
Could not find release for version code '' to update changelog

### ISSUE THREAD

**Issue by RicardoBelchior** [fastlane/fastlane#15638]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Last week (7th nov) we successfully deployed our android release to the internal track (using fastlane 2.134.0)

Today, using fastlane 2.135.2, we tried to promote to production, but fastlane failed to deploy with the following error:

`Could not find release for version code '' to update changelog`

I suspect this is related to: https://github.com/fastlane/fastlane/issues/14573
@joshdholtz please have a look.

##### Command executed
`bundle exec fastlane android deploy flavor:mirror track:internal promote_to:production --verbose`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[14:47:13]: $ bundle exec fastlane android deploy flavor:mirror track:internal promote_to:production --verbose
[14:47:13]: 
[14:47:13]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2019-11-12 14:47:14.39]: Checking if there are any plugins that should be loaded...
DEBUG [2019-11-12 14:47:14.44]: Couldn't find xcodebuild at /Library/Developer/CommandLineTools//usr/bin/xcodebuild, check that it exists
Successfully loaded Appfile at path '/Users/macmini1/.jenkins/workspace/Android_Fastlane_Deploy/BuildType/Release/Publication/Mirror/fastlane/Appfile'
- json_key_file: 'json_key.json'
-------
Successfully loaded Appfile at path '/Users/macmini1/.jenkins/workspace/Android_Fastlane_Deploy/BuildType/Release/Publication/Mirror/fastlane/Appfile'
- json_key_file: 'json_key.json'
-------
DEBUG [2019-11-12 14:47:14.45]: Using flavor: mirror
DEBUG [2019-11-12 14:47:14.45]: Using track: internal
DEBUG [2019-11-12 14:47:14.45]: Using promote_to: production
INFO [2019-11-12 14:47:14.46]: -----------------------------
INFO [2019-11-12 14:47:14.46]: --- Step: update_fastlane ---
INFO [2019-11-12 14:47:14.46]: -----------------------------
INFO [2019-11-12 14:47:14.46]: Looking for updates for fastlane...
INFO [2019-11-12 14:47:16.57]: Nothing to update ✅
INFO [2019-11-12 14:47:16.58]: ----------------------------------------
INFO [2019-11-12 14:47:16.58]: --- Step: Verifying fastlane version ---
INFO [2019-11-12 14:47:16.58]: ----------------------------------------
INFO [2019-11-12 14:47:16.58]: Your fastlane version 2.135.2 matches the minimum requirement of 2.35.0  ✅
INFO [2019-11-12 14:47:16.58]: ------------------------------
INFO [2019-11-12 14:47:16.58]: --- Step: default_platform ---
INFO [2019-11-12 14:47:16.58]: ------------------------------
INFO [2019-11-12 14:47:16.58]: Driving the lane 'android deploy' 🚀
INFO [2019-11-12 14:47:16.59]: --------------------
INFO [2019-11-12 14:47:16.59]: --- Step: supply ---
INFO [2019-11-12 14:47:16.59]: --------------------
Successfully loaded Appfile at path '/Users/macmini1/.jenkins/workspace/Android_Fastlane_Deploy/BuildType/Release/Publication/Mirror/fastlane/Appfile'
- json_key_file: 'json_key.json'
-------
Successfully loaded Appfile at path '/Users/macmini1/.jenkins/workspace/Android_Fastlane_Deploy/BuildType/Release/Publication/Mirror/fastlane/Appfile'
- json_key_file: 'json_key.json'
-------
Successfully loaded Appfile at path '/Users/macmini1/.jenkins/workspace/Android_Fastlane_Deploy/BuildType/Release/Publication/Mirror/fastlane/Appfile'
- json_key_file: 'json_key.json'
-------
Successfully loaded Appfile at path '/Users/macmini1/.jenkins/workspace/Android_Fastlane_Deploy/BuildType/Release/Publication/Mirror/fastlane/Appfile'
- json_key_file: 'json_key.json'
-------
Successfully loaded Appfile at path '/Users/macmini1/.jenkins/workspace/Android_Fastlane_Deploy/BuildType/Release/Publication/Mirror/fastlane/Appfile'
- json_key_file: 'json_key.json'
-------
Successfully loaded Appfile at path '/Users/macmini1/.jenkins/workspace/Android_Fastlane_Deploy/BuildType/Release/Publication/Mirror/fastlane/Appfile'
- json_key_file: 'json_key.json'
-------
Successfully loaded Appfile at path '/Users/macmini1/.jenkins/workspace/Android_Fastlane_Deploy/BuildType/Release/Publication/Mirror/fastlane/Appfile'
- json_key_file: 'json_key.json'
-------

+-------------------------+-----------------------------+
|              Summary for supply 2.135.2               |
+-------------------------+-----------------------------+
| package_name            | com.mirror.news             |
| track                   | internal                    |
| track_promote_to        | production                  |
| skip_upload_apk         | true                        |
| skip_upload_aab         | true                        |
| skip_upload_metadata    | true                        |
| skip_upload_images      | true                        |
| skip_upload_screenshots | true                        |
| release_status          | completed                   |
| metadata_path           | ./fastlane/metadata/android |
| json_key                | json_key.json               |
| skip_upload_changelogs  | false                       |
| validate_only           | false                       |
| check_superseded_tracks | false                       |
| timeout                 | 300                         |
| deactivate_on_promote   | true                        |
+-------------------------+-----------------------------+

DEBUG [2019-11-12 14:47:16.60]: Fetching a new access token from Google...
INFO [2019-11-12 14:47:18.65]: Uploading all track and release changes to Google Play...
INFO [2019-11-12 14:47:20.49]: Successfully finished the upload to Google Play
INFO [2019-11-12 14:47:21.42]: -------------------
INFO [2019-11-12 14:47:21.42]: --- Step: slack ---
INFO [2019-11-12 14:47:21.42]: -------------------
INFO [2019-11-12 14:47:21.72]: Successfully sent Slack notification
WARN [2019-11-12 14:47:21.72]: Lane Context:
INFO [2019-11-12 14:47:21.72]: {:DEFAULT_PLATFORM=>:android, :PLATFORM_NAME=>:android, :LANE_NAME=>"android deploy"}
ERROR [2019-11-12 14:47:21.72]: Could not find release for version code '' to update changelog
INFO [2019-11-12 14:47:21.73]: Successfully generated documentation at path '/Users/macmini1/.jenkins/workspace/Android_Fastlane_Deploy/BuildType/Release/Publication/Mirror/fastlane/README.md'

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | update_fastlane            | 2           |
| 2    | Verifying fastlane version | 0           |
| 3    | default_platform           | 0           |
| 💥   | supply                     | 4           |
| 5    | slack                      | 0           |
+------+----------------------------+-------------+

ERROR [2019-11-12 14:47:21.73]: fastlane finished with errors
/Users/macmini1/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.135.2/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Could not find release for version code '' to update changelog (FastlaneCore::Interface::FastlaneError)
	from /Users/macmini1/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.135.2/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/macmini1/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.135.2/supply/lib/supply/uploader.rb:51:in `block in perform_upload_meta'
	from /Users/macmini1/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.135.2/supply/lib/supply/uploader.rb:46:in `each'
	from /Users/macmini1/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.135.2/supply/lib/supply/uploader.rb:46:in `perform_upload_meta'
	from /Users/macmini1/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.135.2/supply/lib/supply/uploader.rb:38:in `perform_upload'
	from /Users/macmini1/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.135.2/fastlane/lib/fastlane/actions/upload_to_play_store.rb:33:in `run'
	from /Users/macmini1/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.135.2/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
	from /Users/macmini1/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.135.2/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/macmini1/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.135.2/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
	from /Users/macmini1/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.135.2/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/macmini1/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.135.2/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/macmini1/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.135.2/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/macmini1/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.135.2/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:100:in `promote_app'
	from Fastfile:46:in `block (2 levels) in parsing_binding'
	from /Users/macmini1/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.135.2/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/macmini1/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.135.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/macmini1/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.135.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/macmini1/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.135.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/macmini1/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.135.2/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/macmini1/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.135.2/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/macmini1/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.135.2/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/macmini1/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/macmini1/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/macmini1/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/macmini1/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.135.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/macmini1/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/macmini1/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.135.2/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	from /Users/macmini1/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.135.2/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/macmini1/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.135.2/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Users/macmini1/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.135.2/bin/fastlane:23:in `<top (required)>'
	from /Users/macmini1/.rbenv/versions/2.6.3/bin/fastlane:23:in `load'
	from /Users/macmini1/.rbenv/versions/2.6.3/bin/fastlane:23:in `<main>'
Build step 'Execute shell' marked build as failure
Finished: FAILURE
</pre>
</details>

### Environment

<details>
  <pre> It ran on my CI machine, so it's hard to get it. Let me know if you really want it. </pre>
</details>

**Comment by joshdholtz** [comment]
Looking into!

**Comment by joshdholtz** [comment]
Okay, I think I got a fix for this now! PR coming soon.

**Comment by Knupper** [comment]
> Okay, I think I got a fix for this now! PR coming soon.

Is this really fixed? Because i got the same error today when i used `upload_to_play_store(track: 'beta', track_promote_to: 'prod')`
