### ISSUE TITLE
[supply] Add support for Playstore's Internal App Sharing

### ISSUE THREAD

**Issue by gneokleous** [fastlane/fastlane#15636]
#### Motivation Behind Feature
Allow distribution of APKs and AABs without manipulating version codes.

#### Feature Description
Google Developers API has added support for the recent feature `internal app sharing`. 

**Internal App Sharing**
Allows uploading an artifact without having to change version codes. The most important thing is that enables App Bundles to be distributed without rolling a unique artifact in any of the release tracks.

Explanation: https://support.google.com/googleplay/android-developer/answer/9303479?hl=en-GB

Google Developers API v3 Support Docs: https://developers.google.com/android-publisher/api-ref/internalappsharingartifacts.

There was another issue for this feature request: https://github.com/fastlane/fastlane/issues/14924 and closed due to inactivity. Also it requires changes that have been made as part of #15269.  

#### Alternatives or Workarounds
Current solution is manually uploading the binary files at:  [Uploading Link](https://play.google.com/apps/publish/internalappsharing/)

**Comment by joshdholtz** [comment]
@gneokleous I like this! I'm currently working on some backlogged `screengrab` PRs and issues but I can look into adding this once I'm done with these other things 🙃

**Comment by PaulWoitaschek** [comment]
That would be great! This would really simplify the CI->Testers workflow

**Comment by ktae13-npnf** [comment]
Hi, I needed this feature, and made it work on my local machine. I am preparing for PR for the first time, but hoping I could create PR within couple days. It is going to use `Google API Client 0.34.1` for the sharing. Please let me know if it could be a trouble.

**Comment by derrikammons** [comment]
Please create your PR and get it approved @ktae13-npnf.  We need this, too!

**Comment by ktae13-npnf** [comment]
PR created!!!
https://github.com/fastlane/fastlane/pull/15696

**Comment by Luckygirlllll** [comment]
@ktae13-npnf  I'm interested in this feature as well, what should I do to be able to use it in the fastlane? how exactly lane should look like?

**Comment by ktae13-npnf** [comment]
@Luckygirlllll, as you know, it's in PR right now, and @joshdholtz will make changes for better structure. Let's wait a few more days until his change applies.

**Comment by charlesdurham** [comment]
Just adding another "This is an awesome feature" comment 😄
