### ISSUE TITLE
Gradle properties.versionCode not being used

### ISSUE THREAD

**Issue by alexcroox** [fastlane/fastlane#15633]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I was running into `Google Api Error: apkNotificationMessageKeyUpgradeVersionConflict: APK specifies a version code that has already been used.` and I couldn't work out why as I was using the following:

```
gradle(
      task: "assemble",
      build_type: "Release",
      project_dir: "./android",
      properties: {
        "versionName" => "2.0.0",
        "versionCode" => 200,
        "android.injected.signing.store.file" => "keystore.jks",
        "android.injected.signing.store.password" => ENV["FASTLANE_KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => "upload",
        "android.injected.signing.key.password" => ENV["FASTLANE_KEY_PASSWORD"]
      }
    )
```

and I could see in the output it was being passed in the command:

```
--------------------
[23:22:18]: --- Step: gradle ---
[23:22:18]: --------------------
[23:22:18]: $ /Users/alex/Projects/sml/android/gradlew assembleRelease -p ./android -PversionName=2.0.0 -PversionCode=200 ...
```
However this seems to be completely ignored, and the only value gradle would actually use for the apk sits inside `app/build.gradle`

```
android {
    compileSdkVersion 28
    defaultConfig {
        ...
        versionCode 1 << This will be used no matter what, if I delete this line I get a gradle error
        versionName "1.0"
        ...
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
```

<details>
  <pre>***</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.21.0 (Apple Git-122.2)        |
| Installation Source         | ~/.rvm/gems/ruby-2.6.3/bin/fastlane         |
| Host                        | Mac OS X 10.14.6 (18G1012)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.3/lib                |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.2.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   | en_GB.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.28.3"

default_platform :ios

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/***"
    setup_circle_ci
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    # Automatically handle codesigning https://codesigning.guide
    match(type: "appstore")

    # Testflight needs different build number every time
    increment_build_number(
      xcodeproj: "ios/App/App.xcodeproj" ,
      build_number: ENV["CIRCLE_BUILD_NUM"] || 1
    )

    # Build the app
    gym(
      scheme: "App",
      workspace: "ios/App/App.xcworkspace",
    )

    # Upload to testflight
    pilot

    slack(
      message: "IOS: Successfully uploaded new Beta build to TestFlight"
    )
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # Automatically handle codesigning https://codesigning.guide
    match(type: "appstore", readonly: is_ci)

    app_version = load_json(json_path: "app-version.json")

    increment_version_number(version_number: app_version["version"])

    # Build the app
    gym(
      scheme: "App",
      workspace: "ios/App/App.xcworkspace",
    )

    # Upload to app store and submit for review
    deliver(force: false)

    slack(
      message: "IOS: Successfully submitted new update to App Store"
    )
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end

platform :android do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/***"
  end

  desc "Submit a new Beta Build to Google Play Store"
  lane :beta do
    app_version = load_json(json_path: "app-version.json")

    gradle(task: 'clean', project_dir: './android')

    gradle(
      task: "assemble",
      build_type: "Release",
      project_dir: "./android",
      properties: {
        "versionName" => "2.0.0",
        "versionCode" => 200,
        "android.injected.signing.store.file" => "keystore.jks",
        "android.injected.signing.store.password" => ENV["FASTLANE_KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => "upload",
        "android.injected.signing.key.password" => ENV["FASTLANE_KEY_PASSWORD"]
      }
    )

    supply(
      package_name: "**.**.**",
      track: "internal",
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "**.**.**" # The bundle identifier of your app
apple_id "****" # Your Apple email address

team_id "JUAJ7692VV" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.135.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-load_json | 0.0.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 2.0.2        |
| CFPropertyList            | 3.0.1        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.68.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.17.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.1       |
| multi_json                | 1.14.1       |
| os                        | 1.0.1        |
| signet                    | 0.12.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.1009  |
| mime-types                | 3.3          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.4.1        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.13.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-load_json | 0.0.1        |
</details>

*generated on:* **2019-11-11**
</details></pre>
</details>

**Comment by alexcroox** [comment]
For now I have worked around this by using this plugin:

https://github.com/beplus/fastlane-plugin-versioning_android

```
gradle(task: 'clean', project_dir: './android')

    android_set_version_name(
      version_name: app_version["version"],
      gradle_file: "./android/app/build.gradle"
    )

    android_set_version_code(
      version_code: ENV["CIRCLE_BUILD_NUM"] || 20001,
      gradle_file: "./android/app/build.gradle"
    )

    gradle(
      task: "assemble",
      build_type: "Release",
      project_dir: "./android",
      properties: {
        "versionName" => app_version["version"],
        "versionCode" => ENV["CIRCLE_BUILD_NUM"] || 20001,
        "android.injected.signing.store.file" => "keystore.jks",
        "android.injected.signing.store.password" => ENV["FASTLANE_KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => "upload",
        "android.injected.signing.key.password" => ENV["FASTLANE_KEY_PASSWORD"]
      }
    )
```

I'll leave this issue open in case there is something glaring I'm missing that can be fixed without a plugin.

**Comment by janpio** [comment]
Do you think this is a problem in Fastlane? Because if we are sending the correct parameter to `gradlew`, there is not much we could do differently, right?
