### ISSUE TITLE
[supply] when promoting to rollout release notes are not being updated.

### ISSUE THREAD

**Issue by mhdtouban** [fastlane/fastlane#15639]
### Question Checklist

- [yes] Updated fastlane to the latest version
- [yes] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [yes] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [yes] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
**Supply**

#### Question Description
When uploading the app to beta track release notes are being uploaded but when promoting it to rollout the release notes are not being uploaded. Here are the lanes to deploy and promote:

```
  desc "Deploy a new version to Google Play Beta track"
  desc 'Options:'
  desc ' - `brand` (required).'
  lane :deploy_to_store do |options|
    flavor = ANDROID_PRODUCTION_FLAVORS[options[:brand]]
     if flavor
        upload_to_play_store(
          package_name: ANDROID_PRODUCTION_PACKAGE_NAMES[options[:brand]],
          json_key: get_google_play_api_access_key(options[:brand]),
          metadata_path: 'fastlane/'+options[:brand]+'/metadata/android',
          track: 'beta',
          aab: '/home/circleci/react_courier/output/'+flavor.sub(flavor[0],flavor[0].downcase)+'Release.aab',
        )
      else
          UI.user_error!("Incorrect brand provided")
      end
  end
```

```
  desc "Promote specific brand app from beta track to production with a rollout %"
  desc 'Options:'
  desc ' - `rollout` (required).'
  desc ' - `brand` (required).'
  lane :promote_app_to_production do |options|
      if options[:rollout]
        supply(
          package_name: ANDROID_PRODUCTION_PACKAGE_NAMES[options[:brand]],
          json_key: get_google_play_api_access_key(options[:brand]),
          track: 'beta',
          track_promote_to: 'rollout',
          rollout: options[:rollout],
          skip_upload_apk: true,
          skip_upload_aab: true,
          skip_upload_metadata: false,
          skip_upload_images: true,
          skip_upload_screenshots: true,
         )
     else
         UI.user_error!("Parameter rollout must be provided")
     end
  end
```

**Comment by joshdholtz** [comment]
Looking into!

**Comment by joshdholtz** [comment]
@mhdtouban I'm having a hard time replicating this 🤔 Is `rollout` still a valid track? I think what you are looking to do is go from `beta` to `production` and specify a value in the `rollout` option, right? And pre-thanks for helping me understand this 😊

**Comment by mhdtouban** [comment]
thanks for looking into that @joshdholtz right I want to promote the app from beta to production and according to docs the track has to be rollout and the user fraction is provided with a rollout parameter. https://docs.fastlane.tools/actions/supply/#parameters

**Comment by mhdtouban** [comment]
this has already worked out but the release notes were only uploaded to beta track and weren't uploaded when promoting to production aka running promote_app_to_production

**Comment by joshdholtz** [comment]
Can you try changing your `track_promote_to: 'rollout'` to `track_promote_to: 'production'` and see if that takes the release notes with you? When I to go from `beta` to `production`, my release notes ended up going with my app 🤔

**Comment by mhdtouban** [comment]
the thing when you do track_promote_to: 'production' the user fraction (rollout parameter) won't work and thus you end up having a full release

**Comment by joshdholtz** [comment]
Ah, really? I thought that was working for me 😱 Lemme try again!

**Comment by mhdtouban** [comment]
yeah this is pretty confusing and caused us having a major release rollout to 100% of our users.. the docs needs to be much clearer since it says

`rollout: The percentage of the user fraction when uploading to the rollout track`

but also the track description doesn't list the rollout track:

`The default available tracks are: production, beta, alpha, internal`

**Comment by joshdholtz** [comment]
I see the issue now! 😱 Going to fix and then update the docs too

**Comment by mhdtouban** [comment]
@joshdholtz I saw your changes now and updated doc. Just a question here, if we want to release to prod with user fraction we would use the production track with the rollout parameter and the release_status would be `inProgress` and when we want to have a complete rollout we update the  release_status to `completed`? Also, the release notes would be uploaded when we set release_status to `completed`   Let me know if am missing anything here.

**Comment by joshdholtz** [comment]
If you wanted to do a rollout production (in the next version which will be `2.136.0`), you would set...
```
track: “beta”,
track_promote_to: “production”,
rollout: 0.5
```

or something to that effect ☝️ That will promote **with** a rollout (unlike in the current live version)
