### ISSUE TITLE
Snapshot are stuck on simulator after update. -Update: Only one device at a time works!

### ISSUE THREAD

**Issue by basilfarraj** [fastlane/fastlane#15640]
### Issue Description
After updating Xcode to 11.2.1, when trying to take the screenshots, I get two annoying errors, and all my snapshot tests fail.

**These are the two main errors:**
```
Testing failed:
SnapshotUITests:
SnapshotUITests-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: The request to open "com.myapp.SnapshotUITests.xctrunner" failed. The request was denied by service delegate (SBMainWorkspace) for reason: Busy ("Application failed preflight checks"). (Underlying error: The operation couldn’t be completed. Application failed preflight checks)))
```

**and this:**
```
(error = Error Domain=FBSOpenApplicationServiceErrorDomain Code=1 "The request to open "com.myapp.SnapshotUITests.xctrunner" failed." UserInfo={BSErrorCodeDescription=RequestDenied, NSLocalizedDescription=The request to open "com.myapp.SnapshotUITests.xctrunner" failed., NSUnderlyingError=0x7f8e71fc57c0 {Error Domain=FBSOpenApplicationErrorDomain Code=6 "Application failed preflight checks" UserInfo={BSErrorCodeDescription=Busy, NSLocalizedFailureReason=Application failed preflight checks}}, FBSOpenApplicationRequestID=0x7863, NSLocalizedFailureReason=The request was denied by service delegate (SBMainWorkspace) for reason: Busy ("Application failed preflight checks").})
```
Tried to reset the simulators, didn't help.

##### Command executed
```
 sh -c set -o pipefail && xcodebuild -workspace ./Radiov2.xcworkspace -scheme SnapshotUITests -derivedDataPath '/var/folders/2j/wml7hm8927d_rwhhz2wjsznh0000gn/T/snapshot_derived20191112-675-1a8fy79' -destination 'platform=iOS Simulator,name=iPad Pro (12.9-inch) (2nd generation),OS=13.2.2' -destination 'platform=iOS Simulator,name=iPad Pro (12.9-inch) (3rd generation),OS=13.2.2' FASTLANE_SNAPSHOT=YES build test | tee -a /Users/admin/Library/Logs/snapshot/WLS3788583528-SnapshotUITests.log | xcpretty
```

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>
9-11-12 22:38:37.559 xcodebuild[18563:766046]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/var/folders/2j/wml7hm8927d_rwhhz2wjsznh0000gn/T/snapshot_derived20191112-14217-k12aug/Logs/Test/Run-SnapshotUITests-2019.11.12_22-35-08-+0200.xcresult/Staging/5_Test/Diagnostics/SnapshotUITests-783567FD-263D-4C8C-A591-9544DEE12DCC/SnapshotUITests-6B4CCA7E-39BE-43ED-A357-534778E091EB/Session-SnapshotUITests-2019-11-12_223837-m4Ocon.log
2019-11-12 22:38:37.560 xcodebuild[18563:763388] [MT] IDETestOperationsObserverDebug: (416E48B8-BE59-4BAF-AC07-45F2CF9C526B) Beginning test session SnapshotUITests-416E48B8-BE59-4BAF-AC07-45F2CF9C526B at 2019-11-12 22:38:37.560 with Xcode 11B53 on target <DVTiPhoneSimulator: 0x7f8e72b255f0> {
SimDevice: iPad Pro (12.9-inch) (3rd generation) (13E33F5D-D591-4F67-B700-12CB8EB8EC2F, iOS 13.2, Booted)
} (13.2.2 (17B102))
2019-11-12 22:38:37.583 xcodebuild[18563:766050]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/var/folders/2j/wml7hm8927d_rwhhz2wjsznh0000gn/T/snapshot_derived20191112-14217-k12aug/Logs/Test/Run-SnapshotUITests-2019.11.12_22-35-08-+0200.xcresult/Staging/4_Test/Diagnostics/SnapshotUITests-657BBF8C-5517-46AA-8DC4-423FC33810B5/SnapshotUITests-7EFA516F-4DE2-43C6-A753-686B9299F5C8/Session-SnapshotUITests-2019-11-12_223837-rmwaGL.log
2019-11-12 22:38:37.583 xcodebuild[18563:763388] [MT] IDETestOperationsObserverDebug: (4FC43560-3179-4A18-94BB-0700C0EBF7A2) Beginning test session SnapshotUITests-4FC43560-3179-4A18-94BB-0700C0EBF7A2 at 2019-11-12 22:38:37.583 with Xcode 11B53 on target <DVTiPhoneSimulator: 0x7f8e728b76e0> {
SimDevice: iPad Pro (12.9-inch) (2nd generation) (D3E2E315-6F1F-4639-BD98-24D4609D6B3E, iOS 13.2, Booted)
} (13.2.2 (17B102))
2019-11-12 22:38:37.760 xcodebuild[18563:763388] [MT] IDETestOperationsObserverDebug: (4FC43560-3179-4A18-94BB-0700C0EBF7A2) Finished requesting crash reports. Continuing with testing.
2019-11-12 22:38:37.818 xcodebuild[18563:763388] [MT] IDETestOperationsObserverDebug: (416E48B8-BE59-4BAF-AC07-45F2CF9C526B) Finished requesting crash reports. Continuing with testing.
2019-11-12 22:38:54.597 xcodebuild[18563:766055]  iOSSimulator: 13E33F5D-D591-4F67-B700-12CB8EB8EC2F: Failed to launch app with identifier: com.myapp.SnapshotUITests.xctrunner and options: {
"activate_suspended" = 1;
arguments =     (
"-NSTreatUnknownArgumentsAsOpen",
NO,
"-ApplePersistenceIgnoreState",
YES
);
environment =     {
"CA_ASSERT_MAIN_THREAD_TRANSACTIONS" = 0;
"CA_DEBUG_TRANSACTIONS" = 0;
"DYLD_FALLBACK_FRAMEWORK_PATH" = "";
"DYLD_FRAMEWORK_PATH" = "/var/folders/2j/wml7hm8927d_rwhhz2wjsznh0000gn/T/snapshot_derived20191112-14217-k12aug/Build/Products/Debug-iphonesimulator";
"DYLD_INSERT_LIBRARIES" = "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libMainThreadChecker.dylib";
"DYLD_LIBRARY_PATH" = "/var/folders/2j/wml7hm8927d_rwhhz2wjsznh0000gn/T/snapshot_derived20191112-14217-k12aug/Build/Products/Debug-iphonesimulator";
"MTC_CRASH_ON_REPORT" = 1;
NSUnbufferedIO = YES;
"OS_ACTIVITY_DT_MODE" = YES;
"SQLITE_ENABLE_THREAD_ASSERTIONS" = 1;
XCTestConfigurationFilePath = "/var/folders/2j/wml7hm8927d_rwhhz2wjsznh0000gn/T/snapshot_derived20191112-14217-k12aug/Logs/Test/Run-SnapshotUITests-2019.11.12_22-35-08-+0200.xcresult/Staging/5_Test/Diagnostics/SnapshotUITests-783567FD-263D-4C8C-A591-9544DEE12DCC/SnapshotUITests-6B4CCA7E-39BE-43ED-A357-534778E091EB/LaunchSessions/416E48B8-BE59-4BAF-AC07-45F2CF9C526B/remote-container/tmp/SnapshotUITests-416E48B8-BE59-4BAF-AC07-45F2CF9C526B.xctestconfiguration";
"__XCODE_BUILT_PRODUCTS_DIR_PATHS" = "/var/folders/2j/wml7hm8927d_rwhhz2wjsznh0000gn/T/snapshot_derived20191112-14217-k12aug/Build/Products/Debug-iphonesimulator";
"__XPC_DYLD_FRAMEWORK_PATH" = "/var/folders/2j/wml7hm8927d_rwhhz2wjsznh0000gn/T/snapshot_derived20191112-14217-k12aug/Build/Products/Debug-iphonesimulator";
"__XPC_DYLD_LIBRARY_PATH" = "/var/folders/2j/wml7hm8927d_rwhhz2wjsznh0000gn/T/snapshot_derived20191112-14217-k12aug/Build/Products/Debug-iphonesimulator";
};
stderr = "/dev/ttys008";
stdout = "/dev/ttys008";
"wait_for_debugger" = 0;
} (error = Error Domain=FBSOpenApplicationServiceErrorDomain Code=1 "The request to open "com.myapp.SnapshotUITests.xctrunner" failed." UserInfo={BSErrorCodeDescription=RequestDenied, NSLocalizedDescription=The request to open "com.myapp.SnapshotUITests.xctrunner" failed., NSUnderlyingError=0x7f8e73a95b10 {Error Domain=FBSOpenApplicationErrorDomain Code=6 "Application failed preflight checks" UserInfo={BSErrorCodeDescription=Busy, NSLocalizedFailureReason=Application failed preflight checks}}, FBSOpenApplicationRequestID=0xf206, NSLocalizedFailureReason=The request was denied by service delegate (SBMainWorkspace) for reason: Busy ("Application failed preflight checks").})
2019-11-12 22:38:54.631 xcodebuild[18563:766055]  iOSSimulator: D3E2E315-6F1F-4639-BD98-24D4609D6B3E: Failed to launch app with identifier: com.myapp.SnapshotUITests.xctrunner and options: {
"activate_suspended" = 1;
arguments =     (
"-NSTreatUnknownArgumentsAsOpen",
NO,
"-ApplePersistenceIgnoreState",
YES
);
environment =     {
"CA_ASSERT_MAIN_THREAD_TRANSACTIONS" = 0;
"CA_DEBUG_TRANSACTIONS" = 0;
"DYLD_FALLBACK_FRAMEWORK_PATH" = "";
"DYLD_FRAMEWORK_PATH" = "/var/folders/2j/wml7hm8927d_rwhhz2wjsznh0000gn/T/snapshot_derived20191112-14217-k12aug/Build/Products/Debug-iphonesimulator";
"DYLD_INSERT_LIBRARIES" = "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libMainThreadChecker.dylib";
"DYLD_LIBRARY_PATH" = "/var/folders/2j/wml7hm8927d_rwhhz2wjsznh0000gn/T/snapshot_derived20191112-14217-k12aug/Build/Products/Debug-iphonesimulator";
"MTC_CRASH_ON_REPORT" = 1;
NSUnbufferedIO = YES;
"OS_ACTIVITY_DT_MODE" = YES;
"SQLITE_ENABLE_THREAD_ASSERTIONS" = 1;
XCTestConfigurationFilePath = "/var/folders/2j/wml7hm8927d_rwhhz2wjsznh0000gn/T/snapshot_derived20191112-14217-k12aug/Logs/Test/Run-SnapshotUITests-2019.11.12_22-35-08-+0200.xcresult/Staging/4_Test/Diagnostics/SnapshotUITests-657BBF8C-5517-46AA-8DC4-423FC33810B5/SnapshotUITests-7EFA516F-4DE2-43C6-A753-686B9299F5C8/LaunchSessions/4FC43560-3179-4A18-94BB-0700C0EBF7A2/remote-container/tmp/SnapshotUITests-4FC43560-3179-4A18-94BB-0700C0EBF7A2.xctestconfiguration";
"__XCODE_BUILT_PRODUCTS_DIR_PATHS" = "/var/folders/2j/wml7hm8927d_rwhhz2wjsznh0000gn/T/snapshot_derived20191112-14217-k12aug/Build/Products/Debug-iphonesimulator";
"__XPC_DYLD_FRAMEWORK_PATH" = "/var/folders/2j/wml7hm8927d_rwhhz2wjsznh0000gn/T/snapshot_derived20191112-14217-k12aug/Build/Products/Debug-iphonesimulator";
"__XPC_DYLD_LIBRARY_PATH" = "/var/folders/2j/wml7hm8927d_rwhhz2wjsznh0000gn/T/snapshot_derived20191112-14217-k12aug/Build/Products/Debug-iphonesimulator";
};
stderr = "/dev/ttys005";
stdout = "/dev/ttys005";
"wait_for_debugger" = 0;
} (error = Error Domain=FBSOpenApplicationServiceErrorDomain Code=1 "The request to open "com.myapp.SnapshotUITests.xctrunner" failed." UserInfo={BSErrorCodeDescription=RequestDenied, NSLocalizedDescription=The request to open "com.myapp.SnapshotUITests.xctrunner" failed., NSUnderlyingError=0x7f8e71fc57c0 {Error Domain=FBSOpenApplicationErrorDomain Code=6 "Application failed preflight checks" UserInfo={BSErrorCodeDescription=Busy, NSLocalizedFailureReason=Application failed preflight checks}}, FBSOpenApplicationRequestID=0x7863, NSLocalizedFailureReason=The request was denied by service delegate (SBMainWorkspace) for reason: Busy ("Application failed preflight checks").})
2019-11-12 22:39:10.627 xcodebuild[18563:763388] [MT] IDETestOperationsObserverDebug: 33.097 elapsed -- Testing started completed.
2019-11-12 22:39:10.627 xcodebuild[18563:763388] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2019-11-12 22:39:10.627 xcodebuild[18563:763388] [MT] IDETestOperationsObserverDebug: 33.097 sec, +33.097 sec -- end
2019-11-12 22:39:10.629 xcodebuild[18563:763388] Error Domain=FBSOpenApplicationServiceErrorDomain Code=1 "The request to open "com.myapp.SnapshotUITests.xctrunner" failed." UserInfo={BSErrorCodeDescription=RequestDenied, NSLocalizedDescription=The request to open "com.myapp.SnapshotUITests.xctrunner" failed., NSUnderlyingError=0x7f8e73a95b10 {Error Domain=FBSOpenApplicationErrorDomain Code=6 "Application failed preflight checks" UserInfo={BSErrorCodeDescription=Busy, NSLocalizedFailureReason=Application failed preflight checks}}, FBSOpenApplicationRequestID=0xf206, NSLocalizedFailureReason=The request was denied by service delegate (SBMainWorkspace) for reason: Busy ("Application failed preflight checks").}
2019-11-12 22:39:11.011 xcodebuild[18563:763388] [MT] IDETestOperationsObserverDebug: 33.481 elapsed -- Testing started completed.
2019-11-12 22:39:11.011 xcodebuild[18563:763388] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2019-11-12 22:39:11.012 xcodebuild[18563:763388] [MT] IDETestOperationsObserverDebug: 33.481 sec, +33.481 sec -- end
2019-11-12 22:39:11.014 xcodebuild[18563:763388] Error Domain=FBSOpenApplicationServiceErrorDomain Code=1 "The request to open "com.myapp.SnapshotUITests.xctrunner" failed." UserInfo={BSErrorCodeDescription=RequestDenied, NSLocalizedDescription=The request to open "com.myapp.SnapshotUITests.xctrunner" failed., NSUnderlyingError=0x7f8e71fc57c0 {Error Domain=FBSOpenApplicationErrorDomain Code=6 "Application failed preflight checks" UserInfo={BSErrorCodeDescription=Busy, NSLocalizedFailureReason=Application failed preflight checks}}, FBSOpenApplicationRequestID=0x7863, NSLocalizedFailureReason=The request was denied by service delegate (SBMainWorkspace) for reason: Busy ("Application failed preflight checks").}
Testing failed:
SnapshotUITests:
SnapshotUITests-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: The request to open "com.myapp.SnapshotUITests.xctrunner" failed. The request was denied by service delegate (SBMainWorkspace) for reason: Busy ("Application failed preflight checks"). (Underlying error: The operation couldn’t be completed. Application failed preflight checks)))

** TEST FAILED **
ERROR [2019-11-12 22:39:19.83]: [31mExit status: 65[0m
WARN [2019-11-12 22:39:19.93]: [33mTests failed while running on: iPad Pro (12.9-inch) (2nd generation), iPad Pro (12.9-inch) (3rd generation)[0m
WARN [2019-11-12 22:39:19.93]: [33mFor more detail about the test failures, check the logs here:[0m
WARN [2019-11-12 22:39:19.94]: [33m/Users/admin/Library/Logs/snapshot/WLS3788583528-SnapshotUITests.log[0m
WARN [2019-11-12 22:39:19.94]: [33m [0m
WARN [2019-11-12 22:39:19.94]: [33mYou can also find the test result data here:[0m
WARN [2019-11-12 22:39:19.94]: [33m/var/folders/2j/wml7hm8927d_rwhhz2wjsznh0000gn/T/snapshot_derived20191112-14217-k12aug/Logs/Test[0m
WARN [2019-11-12 22:39:19.94]: [33m [0m
WARN [2019-11-12 22:39:19.94]: [33mYou can find the incomplete screenshots here:[0m
WARN [2019-11-12 22:39:19.94]: [33m/Users/admin/Library/Caches/tools.fastlane/screenshots[0m
WARN [2019-11-12 22:39:19.94]: [33m/Users/admin/myapp/server_builds/p1_543d249b-4e9b-4705-9973-f745e8e8d145/myappradiong-ios/fastlane/screenshots[0m
ERROR [2019-11-12 22:39:19.94]: [31mCaught error... 65[0m

+---------------------------------------+-------+
|               snapshot results                |
+---------------------------------------+-------+
| Device                                | en-US |
+---------------------------------------+-------+
| iPhone 8 Plus                         |  ❌   |
| iPhone Xs Max                         |  ❌   |
| iPad Pro (12.9-inch) (2nd generation) |  ❌   |
| iPad Pro (12.9-inch) (3rd generation) |  ❌   |
+---------------------------------------+-------+
</pre>
</details>

### Environment

<details>
<summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                        |
| --------------------------- | -------------------------------------------- |
| OS                          | 10.15.1                                      |
| Ruby                        | 2.4.0                                        |
| Bundler?                    | false                                        |
| Git                         | git version 2.10.2                           |
| Installation Source         | ~/.rbenv/versions/2.4.0/bin/fastlane         |
| Host                        | Mac OS X 10.15.1 (19B88)                     |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.0/lib                  |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                  |
| Is contained                | false                                        |
| Is homebrew                 | false                                        |
| Is installed via Fabric.app | false                                        |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer// |
| Xcode Version               | 11.2.1                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.134.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.1        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.13.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.68.0       |
| faraday                   | 0.17.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.0.2        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.1009  |
| mime-types                | 3.3          |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.1       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| emoji_regex               | 1.0.1        |
| openssl                   | 2.1.2        |
| json                      | 2.2.0        |
| io-console                | 0.4.8        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.5       |
| plist                     | 3.5.0        |
| psych                     | 3.1.0        |
</details>

*generated on:* **2019-11-13**

</details>

********UPDATE**********
Only one device on the list works. If I add more than one, it returns:

Timed out while requesting automation session for com.myapp.bundle.name and then it points to the swift file where I call the XCUIApplication.launch() method and says: failed to get automation session for com.myapp.bundle..

**Comment by basilfarraj** [comment]
It seems like when I open the tests on the simulator it gets stuck. I updated the simulator, fastlane is on latest, snapshot is on latest.
Any help is appreciated.

**Comment by basilfarraj** [comment]
Update: 
If I add only one device to the Snapfile - it works. But if I add more than one, it fails with error:

> Timed out while requesting automation session for *com.myapp.bundle.name* and then it points to the swift file where I call the XCUIApplication.launch() method and says: failed to get automation session for com.myapp.bundle..

* I'm not using concurrent simulators
* Tried iOS 13.2.2 and 13.1
* Xcode 11.2.1

**Comment by Cyberbeni** [comment]
Had similar issue with the testcenter plugin when using parallel testruns. It works on macOS 10.14.6 with Xcode 11.2.1 and macOS 10.15.2 with Xcode 11.3, only Xcode 11.2.1 on macOS 10.15.2 produces error.

**Comment by dim4ikhot** [comment]
I'm experiencing the same behavior on macOS 10.15.2 with Xcode 11.3 and fastlane 2.140.0. Can anyone help or at least explain why this happening?

**Comment by Cyberbeni** [comment]
@dim4ikhot do you have multiple Xcode versions installed? Xcode 11.3.1 is supposed to fix that:

> Fixed an issue that would cause Xcode to time out waiting for Simulator.app to become ready, when multiple copies of Xcode are installed. (57050823, 57676897)

Same behavior = exact same error message besides the bundle id?
