### ISSUE TITLE
Updating provisioning profiles is failing for templated profiles

### ISSUE THREAD

**Issue by Ajaykn21** [fastlane/fastlane#15650]
Hi, we are using fastlane in our application and updating the provisioning profile is failing with error.
**Please login using Spaceship::Portal.login('user', 'password')**

Here is the sequence of steps I am using
### Fetching the profile
```
profile = @spaceship.provisioning_profile.all.detect{ |item| item.name == profileName }
```
### Adding devices
```
profile.devices += newDevices
```
### Save the changes to the profile.
```
profile.update!
```

This is working fine in case of normal profiles which doesn't have any template. 
` "isTemplateProfile": false,`
But failing for the templated profiles.

When searched in the stack trace its failing because for the templated profiles, ProvisioningProfileTemplate.factory without passing existing client (ref: https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/portal/provisioning_profile.rb#L549)
Any reason, we can't have `ProvisioningProfileTemplate.set_client(client).factory(..)`

Just like `certificate.set_client(client).factory(..)` (ref: https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/portal/provisioning_profile.rb#L518)

I don't have any context how this works..

Stack trace here:
```
/usr/local/bundle/gems/**fastlane-2.129.0/**spaceship/lib/spaceship/portal/**portal_base.rb:11:in `client'**
/usr/local/bundle/gems/fastlane-2.129.0/spaceship/lib/spaceship/**base.rb:233:in `initialize'**
/usr/local/bundle/gems/fastlane-2.129.0/spaceship/lib/spaceship/**base.rb:210:in `new'**
/usr/local/bundle/gems/fastlane-2.129.0/spaceship/lib/spaceship/**base.rb:210:in `factory'**
/usr/local/bundle/gems/fastlane-2.129.0/spaceship/lib/spaceship/portal/**provisioning_profile.rb:549:in `template'**
/usr/local/bundle/gems/fastlane-2.129.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:555:in `template_name'
/usr/local/bundle/gems/fastlane-2.129.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:460:in `block in update!'
/usr/local/bundle/gems/fastlane-2.129.0/spaceship/lib/spaceship/client.rb:620:in `with_retry'
/usr/local/bundle/gems/fastlane-2.129.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:450:in `update!'
```

fastlane version: 2.129.0..

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.21.0 (Apple Git-122.2)                           |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.6 (18G103)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.2                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.129.0 | ✅ Up-To-Date  |

*generated on:* **2019-11-14**
</details>

**Comment by janpio** [comment]
Can you please show the complete code and the complete error you are getting? I tried to format your isse and make it readable, but I am still not really sure what you are doing and what is happening exactly.

**Comment by Ajaykn21** [comment]
@janpio Thanks for responding.
Here is the code I am using.
`
spaceship = Spaceship::Launcher.new
spaceship.login(username, password)
spaceship.client.team_id = "myTeamId"
profileName = 'test-adhoc'
newDevices = [ { :name => "Test - iPhone 7 Plus", :udid => "<device-udid>"} ] 
profile = spaceship.provisioning_profile.all.detect{ |item| item.name == profileName }
profile.devices += newDevices
updatedProfile = profile.update!
`

The above code is working for the profiles which has `"isTemplateProfile": false`,
please refer the below screenshot.
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/40024974/69027660-0dc6a500-0a13-11ea-893c-8b33f774df44.png">

But for some profiles , I am getting the stack trace as below.
when verified in the code, I think, those profiles has `isTemplateProfile` as true, it seems.
`
/usr/local/bundle/gems/**fastlane-2.129.0/**spaceship/lib/spaceship/portal/**portal_base.rb:11:in `client'**
/usr/local/bundle/gems/fastlane-2.129.0/spaceship/lib/spaceship/**base.rb:233:in `initialize'**
/usr/local/bundle/gems/fastlane-2.129.0/spaceship/lib/spaceship/**base.rb:210:in `new'**
/usr/local/bundle/gems/fastlane-2.129.0/spaceship/lib/spaceship/**base.rb:210:in `factory'**
/usr/local/bundle/gems/fastlane-2.129.0/spaceship/lib/spaceship/portal/**provisioning_profile.rb:549:in `template'**
/usr/local/bundle/gems/fastlane-2.129.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:555:in `template_name'
/usr/local/bundle/gems/fastlane-2.129.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:460:in `block in update!'
/usr/local/bundle/gems/fastlane-2.129.0/spaceship/lib/spaceship/client.rb:620:in `with_retry'
/usr/local/bundle/gems/fastlane-2.129.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:450:in `update!'
`

**Comment by Ajaykn21** [comment]
@janpio @max-ott 
does the current issue has something to do with #15678 

any thoughts on this.
