### ISSUE TITLE
Fir.im upload success,but fastlane Error

### ISSUE THREAD

**Issue by ZhengGuiMing** [fastlane/fastlane#15658]
### Question Checklist

i use fastlane and fir.im，the ipa upload success but fastlane error, the error_code 100108
![截屏2019-11-15上午10 26 24](https://user-images.githubusercontent.com/15683503/68912335-da75e300-0792-11ea-99bb-8760edc8a28c.png)

- [x] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

**Comment by ZhengGuiMing** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                        |
| --------------------------- | -------------------------------------------- |
| OS                          | 10.15.1                                      |
| Ruby                        | 2.7.0                                        |
| Bundler?                    | true                                         |
| Git                         | git version 2.21.0 (Apple Git-122.2)         |
| Installation Source         | ~/.rvm/gems/ruby-2.7.0-preview1/bin/fastlane |
| Host                        | Mac OS X 10.15.1 (19B88)                     |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.7.0-preview1/lib        |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                  |
| Is contained                | false                                        |
| Is homebrew                 | false                                        |
| Is installed via Fabric.app | false                                        |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/  |
| Xcode Version               | 11.2.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

default_platform(:ios)

platform:ios do
    desc "Release_EP_PP 企业版"
    lane :Release_EP_PP do
        ENV["ENV_PARAM"] = "PP"
        ENV["CONFIGURATION_TYPE"] = "Release_EP_PP"
        ENV["MATCH_TYPE"] = "enterprise"
        ENV["MATCH_CERT"] = "iPhone Distribution: WM Motor Technology Co., Ltd."
        increment_Version_Info
        gym_WM
        # uploadToPgyer
        uploadToFirim
    end


    desc "Debug_EP_QA 企业版"
    lane :Debug_EP_QA do
        ENV["ENV_PARAM"] = "QA"
        ENV["CONFIGURATION_TYPE"] = "Debug_EPQA"
        ENV["MATCH_TYPE"] = "development"
        ENV["MATCH_CERT"] = "iPhone Developer: Fang Wang (5CG97ASSTB)"
        increment_Version_Info
        gym_WM
        # uploadToPgyer
    end


    desc "Release_EP_QA 企业版"
    lane :Release_EP_QA do
        ENV["ENV_PARAM"] = "QA"
        ENV["CONFIGURATION_TYPE"] = "Release_EP_QA"
        ENV["MATCH_TYPE"] = "enterprise"
        ENV["MATCH_CERT"] = "iPhone Distribution: WM Motor Technology Co., Ltd."
        increment_Version_Info
        gym_WM
        # uploadToPgyer
        uploadToFirim
    end

    desc "Release_EP_DEV 企业版"
    lane :Release_EP_DEV do
        ENV["ENV_PARAM"] = "DEV"
        ENV["CONFIGURATION_TYPE"] = "Release_EP_DEV"
        ENV["MATCH_TYPE"] = "enterprise"
        ENV["MATCH_CERT"] = "iPhone Distribution: WM Motor Technology Co., Ltd."
        increment_Version_Info
        gym_WM
        # uploadToPgyer
        uploadToFirim
    end

    desc "Release_EP_P 企业版"
    lane :Release_EP_P do
        ENV["ENV_PARAM"] = "Release"
        ENV["CONFIGURATION_TYPE"] = "Release_EP_P"
        ENV["MATCH_TYPE"] = "enterprise"
        ENV["MATCH_CERT"] = "iPhone Distribution: WM Motor Technology Co., Ltd."
        increment_Version_Info
        gym_WM
        # uploadToPgyer
        uploadToFirim
    end

    desc "Release AppStore"
    lane :Release do
        ENV["ENV_PARAM"] = "Release"
        ENV["CONFIGURATION_TYPE"] = "Release"
        ENV["MATCH_TYPE"] = "app-store"
        ENV["MATCH_CERT"] = "iPhone Distribution: WM Motor Technology Co., Ltd. (JUU7AHEVWB)"
        increment_Version_Info
        gym_WM
        uploadToBugly
        uploadToTestflight
    end

    #desc "TEST"
    #lane :TEST do
    #    ENV["ENV_PARAM"] = "Enterprise"
    #    ENV["CONFIGURATION_TYPE"] = "Release_EP_PP"
    #    ENV["MATCH_TYPE"] = "enterprise"
    #    ENV["MATCH_CERT"] = "iPhone Distribution: WM Motor Technology Co., Ltd."
    #    ENV["APP_NAME"] = "201807241910_1.0Enterprise"
    #    # increment_Version_Info
    #    # gym_WM
    #    uploadToPgyer
    #end

    desc "获取指定的版本号, 兼容适配用"
    lane :checkout_Version_Info do
        tempVersionn = "Release_" + ENV["VERSION_NAME"]
        git checkout tempVersionn
        increment_version_number version_number: ENV["VERSION_NAME"]
    end


    desc "增加build,只要编译就增加一次, 不能手动调用"
    lane :increment_Version_Info do
        version_number = get_version_number(target:"Clover")
        build_number = Time.new.strftime("%Y%m%d%H%M")
        
        increment_build_number build_number: build_number
        temVersion = version_number[-2,2]
        puts "-----temVersion:" + temVersion
        if temVersion.eql?("QA") || temVersion.eql?("PP")
                version_number = version_number[0,version_number.length - 2]
                puts "-----version_number:" + version_number
        end
        # QA 标示,方便crash分析
        # if ENV["ENV_PARAM"].eql?("Release")
        increment_version_number version_number: version_number
        exp_app_name = build_number + "_" + version_number + ENV["ENV_PARAM"]
        # else
        #     version_number = version_number + ENV["ENV_PARAM"]
        #     increment_version_number version_number: version_number
        #     exp_app_name = build_number + "_" + version_number
        # end
        
        ENV["APP_NAME"] = exp_app_name
        puts "----------- Version_INFO_START ---------------"
        puts "版本号:" + version_number
        puts "build号:" + build_number
        puts "ipa Name:" + exp_app_name + ".ipa"
        puts "----------- Version_INFO_END   ---------------"
    end

    desc "增加build Only"
    lane :increase_Build_Only do
        version_number = get_version_number(target:"Clover")
        build_number = Time.new.strftime("%Y%m%d%H%M")
        
        increment_build_number build_number: build_number
        
        puts "----------- Version_INFO_START ---------------"
        puts "版本号:" + version_number
        puts "build号:" + build_number
        puts "----------- Version_INFO_END   ---------------"
    end

    desc "增加Version,正式版本发布的时候,增加一次"
    lane :increase_VersionName do 
        # 小版本号,直接调用一次
        # increment_version_number
        # 大版本号,手动设置
        increment_version_number version_number: "1.3.0"
    end

    desc "根据参数编译工程,不能直接调用"
    lane :gym_WM do
    gym(
        scheme: "Clover",
        workspace: "Clover.xcworkspace",
        include_bitcode: false,
        output_name: ENV["APP_NAME"]+".ipa",
    #use_legacy_build_api:true,
        # configuration: "Release_QA",
        configuration: ENV["CONFIGURATION_TYPE"],
        codesigning_identity: ENV["MATCH_CERT"],
        export_method: ENV["MATCH_TYPE"],
        clean: true,
        output_directory: "build"
    )
    end

    desc "提交到testflight"
    lane :uploadToTestflight do
        ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"
        pilot(skip_submission: true,
            skip_waiting_for_build_processing: true,
            ipa: "./build/safa_"+ENV["APP_NAME"]+".ipa"
            #ipa: "./build/safa_201909241715_1.2.0Release.ipa"
            )  
    end

    desc "提交到bugly"
    lane :uploadToBugly do
        temsh = "./uptobugly.sh " + ENV["APP_NAME"] + ".ipa " + ENV["CONFIGURATION_TYPE"] + " " + ENV["APP_NAME"]+".app.dSYM.zip \""+ ENV["MATCH_CERT"] + "\""
        puts "sh 命令:" + temsh
        sh temsh
    end

    desc "提交到蒲公英"
    lane :uploadToPgyer do
        temsh = "./uptopgye.sh " + ENV["APP_NAME"] + ".ipa " + ENV["CONFIGURATION_TYPE"] + " " + ENV["APP_NAME"]+".app.dSYM.zip \""+ ENV["MATCH_CERT"] + "\""
        # temsh = "./uptopgye.sh " + "201704261602_1.2.3Enterprise" + ".ipa"    
        puts "sh 命令:" + temsh
        sh temsh
        # sh "./uptopgye.sh"
    end

    desc "提交到fir_im"
    lane :uploadToFirim do
        # uploadToPgyer
        # 上传ipa到fir.im服务器，在fir.im获取firim_api_token
        ENV["ENV_PARAM"] = "QA"
        if ENV["ENV_PARAM"].eql?("QA")
            app_short_url = "https://fir.im/p3md"
        end

        if ENV["ENV_PARAM"].eql?("PP")
            app_short_url = "https://fir.im/m2a5"
        end

        if ENV["ENV_PARAM"].eql?("DEV")
            app_short_url = "https://fir.im/6v9q"
        end
     
        firim(
            # app_name:"小威随行" + "DEV",
            ipa: "./build/safa_201911141824_1.3.0QA.ipa",
            app_short:app_short_url,
            app_passwd:"123456",
            # ipa: "./build/safa_"+ENV["APP_NAME"]+".ipa",
            app_name:"小威随行" + ENV["ENV_PARAM"],
            firim_api_token: "ba2cad588fbff2582318060abceec297"
        )
    end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.wisdomlife.jvs" # The bundle identifier of your app
apple_id "it_hq@wm-motor.com" # Your Apple email address
team_id "JUU7AHEVWB"

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.135.2 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-firim      | 0.2.0   | ✅ Up-To-Date  |
| fastlane-plugin-versioning | 0.4.0   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version      |
| -------------------------- | ------------ |
| did_you_mean               | 1.3.0        |
| executable-hooks           | 1.6.0        |
| bundler-unload             | 1.0.2        |
| rubygems-bundler           | 1.4.5        |
| bundler                    | 2.1.0.pre.1  |
| CFPropertyList             | 3.0.1        |
| public_suffix              | 2.0.5        |
| addressable                | 2.7.0        |
| atomos                     | 0.1.3        |
| babosa                     | 1.0.3        |
| claide                     | 1.0.3        |
| colored                    | 1.2          |
| colored2                   | 3.1.2        |
| highline                   | 1.7.10       |
| commander-fastlane         | 4.4.6        |
| declarative                | 0.0.10       |
| declarative-option         | 0.1.0        |
| digest-crc                 | 0.4.1        |
| unf_ext                    | 0.0.7.6      |
| unf                        | 0.1.4        |
| domain_name                | 0.5.20190701 |
| dotenv                     | 2.7.5        |
| emoji_regex                | 1.0.1        |
| excon                      | 0.68.0       |
| multipart-post             | 2.0.0        |
| faraday                    | 0.17.0       |
| http-cookie                | 1.0.3        |
| faraday-cookie_jar         | 0.0.6        |
| faraday_middleware         | 0.13.1       |
| fastimage                  | 2.1.7        |
| gh_inspector               | 1.1.3        |
| jwt                        | 2.1.0        |
| memoist                    | 0.16.1       |
| multi_json                 | 1.14.1       |
| os                         | 1.0.1        |
| signet                     | 0.12.0       |
| googleauth                 | 0.6.7        |
| httpclient                 | 2.8.3        |
| mime-types-data            | 3.2019.1009  |
| mime-types                 | 3.3          |
| uber                       | 0.1.0        |
| representable              | 3.0.4        |
| retriable                  | 3.1.2        |
| google-api-client          | 0.23.9       |
| google-cloud-env           | 1.3.0        |
| google-cloud-core          | 1.4.1        |
| google-cloud-storage       | 1.16.0       |
| json                       | 2.2.0        |
| mini_magick                | 4.9.5        |
| multi_xml                  | 0.6.0        |
| plist                      | 3.5.0        |
| rubyzip                    | 1.3.0        |
| security                   | 0.1.3        |
| naturally                  | 2.2.0        |
| simctl                     | 1.6.6        |
| slack-notifier             | 2.3.2        |
| terminal-notifier          | 2.0.0        |
| unicode-display_width      | 1.6.0        |
| terminal-table             | 1.8.0        |
| tty-screen                 | 0.7.0        |
| tty-cursor                 | 0.7.0        |
| tty-spinner                | 0.9.1        |
| word_wrap                  | 1.0.0        |
| nanaimo                    | 0.2.6        |
| xcodeproj                  | 1.13.0       |
| rouge                      | 2.0.7        |
| xcpretty                   | 0.3.0        |
| xcpretty-travis-formatter  | 1.0.0        |
| firim                      | 0.2.1        |
| fastlane-plugin-firim      | 0.2.0        |
| fastlane-plugin-versioning | 0.4.0        |
</details>


*generated on:* **2019-11-15**
</details>

**Comment by ZhengGuiMing** [comment]
@fastlane-bot  I have uploaded ### fastlane env here, please help me look at it.

**Comment by janpio** [comment]
Unfortunately you did not.

But as `firim` is not a default action of fastlane, you probably installed a plugin to get this functionality. You should open an issue at the plugin's repository and see if they can help you out.

**Comment by jicheng1014** [comment]
try this  plugin https://github.com/FIRHQ/fastlane-plugin-fir_cli     this fir_cli fastlane plugin is maintained by fir.im official.
