### ISSUE TITLE
[supply] Update to Google Play Developer API v3 (v2 end of life Dec 2019) - wrong changelog file name

### ISSUE THREAD

**Issue by ma-re-k** [fastlane/fastlane#15652]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version:  `2.135.2`
- Last working version:  `2.134.0`

### Regression Description

Related to: #14573
@joshdholtz
According to supply documentation filename containing changelogs for Google Play upload should match exactly the **version code** of the APK: 

![image](https://user-images.githubusercontent.com/55884892/68858587-a2fd2d00-06e5-11ea-9fb7-a720853d9c51.png)

Looks like from version 2.135.2 supply is looking for file named [version name].txt instead of [version code].txt 
##### Complete output when running fastlane, including the stack trace and command used

![image](https://user-images.githubusercontent.com/55884892/68860029-f02ece00-06e8-11ea-928c-c0e56fea5bb9.png)

**Comment by joshdholtz** [comment]
@ma-re-k Thanks for pointing that out! I will update the docs to reflect the code which should be the "version name" 😊

**Comment by ma-re-k** [comment]
Wow, that was quick reply :). 
Previously it was working with **version code**. That's why I raised it as regression. Users will have to modify their scripts after update to new fastlane version. Is there any reason why you changed filename from **version_code.txt** to **version_name.txt**?

**Comment by joshdholtz** [comment]
@ma-re-k Ahhh, was it previously version code? I thought it was version name 😱 I trust you but I'll go back and look to verify because this shouldn't have been a breaking change 😊

**Comment by ma-re-k** [comment]
yes. It was **version code** before. Thanks for checking this.

**Comment by zolhaj** [comment]
Can confirm it was **version_code**. We came upon this issue in 2.135.2 today 😅

**Comment by joshdholtz** [comment]
@zolhaj Thanks for the confirmation! I will get a fix out for this this morning. Will be in `2.136.0` 👌

**Comment by zolhaj** [comment]
Sorry, on double checking it seems that 2.135.1 doesn't upload release notes.
It looks like the Google Play app will show the release notes from a previous version in the same track when no release notes are uploaded.
