### ISSUE TITLE
upload_symbols_to_crashlytics to FIREBASE

### ISSUE THREAD

**Issue by madjuju** [fastlane/fastlane#15656]
### Question Checklist

- [ x] Updated fastlane to the latest version
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.1                                     |
| Ruby                        | 2.6.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.21.0 (Apple Git-122.2)        |
| Installation Source         | ~/.rvm/gems/ruby-2.6.0/bin/fastlane         |
| Host                        | Mac OS X 10.15.1 (19B88)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.1c  28 May 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.2.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | fr_FR.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do
    # Screenshots
    ENV["SNAPSHOT_EXECUTE_CONCURRENT_SIMULATORS"] = "false"
    ENV["SNAPSHOT_LOCALIZE_SIMULATOR"] = "true"
    ENV["SNAPSHOT_CLEAN"] = "true"
    ENV["SNAPSHOT_ERASE_SIMULATOR"] = "false"
    ENV["SNAPSHOT_REINSTALL_APP"] = "false"
    ENV["SNAPSHOT_NUMBER_OF_RETRIES"] = "1"

    # TestFlight
    ENV['MATCH_TYPE'] = "appstore"
    ENV['GYM_CLEAN'] = "true"
    ENV['PILOT_SKIP_WAITING_FOR_BUILD_PROCESSING'] = "true"
  end


####----------------DYSM download & upload to firebase crashlitycs -----------------------
lane :refresh_dsyms do
  username = "store@coolncamp.com",
  app_identifier = ENV['BUNDLE_ID'],
  download_dsyms(version: 'latest', output_directory: "./ipa"),                 # Download dSYM files from iTC
  upload_symbols_to_crashlytics(gsp_path: "./coolncamp/mb_xxxxx/GoogleService-Info.plist", binary_path: "./ipa" , dsym_path: "./ipa/com.xxxxxx-2.3.6-1.dSYM.zip")   # Upload them to Crashlytics
  clean_build_artifacts           # Delete the local dSYM files
#
end



### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.135.2 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                                | Version | Update-Status |
| ------------------------------------- | ------- | ------------- |
| fastlane-plugin-appicon               | 0.14.1  | ✅ Up-To-Date  |
| fastlane-plugin-appicon               | 0.14.1  | ✅ Up-To-Date  |
| fastlane-plugin-translation           | 1.1.4   | ✅ Up-To-Date  |
| fastlane-plugin-google_sheet_localize | 0.3.06  | ✅ Up-To-Date  |
| fastlane-plugin-localization          | 0.2.0   | ✅ Up-To-Date  |
| fastlane-plugin-badge                 | 1.3.0   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                                   | Version      |
| ------------------------------------- | ------------ |
| did_you_mean                          | 1.3.0        |
| executable-hooks                      | 1.6.0        |
| bundler-unload                        | 1.0.2        |
| rubygems-bundler                      | 1.4.5        |
| bundler                               | 2.0.2        |
| CFPropertyList                        | 3.0.1        |
| public_suffix                         | 2.0.5        |
| addressable                           | 2.7.0        |
| atomos                                | 0.1.3        |
| babosa                                | 1.0.3        |
| curb                                  | 0.9.10       |
| fastimage                             | 2.1.7        |
| colored                               | 1.2          |
| highline                              | 1.7.10       |
| commander-fastlane                    | 4.4.6        |
| dotenv                                | 2.7.5        |
| emoji_regex                           | 1.0.1        |
| excon                                 | 0.68.0       |
| multipart-post                        | 2.0.0        |
| faraday                               | 0.17.0       |
| unf_ext                               | 0.0.7.6      |
| unf                                   | 0.1.4        |
| domain_name                           | 0.5.20190701 |
| http-cookie                           | 1.0.3        |
| faraday-cookie_jar                    | 0.0.6        |
| faraday_middleware                    | 0.13.1       |
| gh_inspector                          | 1.1.3        |
| jwt                                   | 2.1.0        |
| memoist                               | 0.16.1       |
| multi_json                            | 1.14.1       |
| os                                    | 1.0.1        |
| signet                                | 0.12.0       |
| googleauth                            | 0.6.7        |
| httpclient                            | 2.8.3        |
| mime-types-data                       | 3.2019.1009  |
| mime-types                            | 3.3          |
| declarative                           | 0.0.10       |
| declarative-option                    | 0.1.0        |
| uber                                  | 0.1.0        |
| representable                         | 3.0.4        |
| retriable                             | 3.1.2        |
| google-api-client                     | 0.23.9       |
| digest-crc                            | 0.4.1        |
| google-cloud-env                      | 1.3.0        |
| google-cloud-core                     | 1.4.1        |
| google-cloud-storage                  | 1.16.0       |
| json                                  | 2.2.0        |
| mini_magick                           | 4.9.5        |
| multi_xml                             | 0.6.0        |
| plist                                 | 3.5.0        |
| rubyzip                               | 1.3.0        |
| security                              | 0.1.3        |
| naturally                             | 2.2.0        |
| simctl                                | 1.6.6        |
| slack-notifier                        | 2.3.2        |
| terminal-notifier                     | 2.0.0        |
| unicode-display_width                 | 1.6.0        |
| terminal-table                        | 1.8.0        |
| tty-screen                            | 0.7.0        |
| tty-cursor                            | 0.7.0        |
| tty-spinner                           | 0.9.1        |
| word_wrap                             | 1.0.0        |
| claide                                | 1.0.3        |
| colored2                              | 3.1.2        |
| nanaimo                               | 0.2.6        |
| xcodeproj                             | 1.13.0       |
| rouge                                 | 2.0.7        |
| xcpretty                              | 0.3.0        |
| xcpretty-travis-formatter             | 1.0.0        |
| badge                                 | 0.11.0       |
| fastlane-plugin-appicon               | 0.14.1       |
| fastlane-plugin-badge                 | 1.3.0        |
| mini_portile2                         | 2.4.0        |
| nokogiri                              | 1.10.5       |
| google_drive                          | 3.0.3        |
| fastlane-plugin-google_sheet_localize | 0.3.06       |
| fastlane-plugin-localization          | 0.2.0        |
| fastlane-plugin-translation           | 1.1.4        |
</details>


*generated on:* **2019-11-14**
</details>
### Question Subject
<!-- upload_symbols_to_crashlytics-->

#### Question Description
<!-- lane :refresh_dsyms do
  username = "xxxxx@xxxxxx.com",
  app_identifier = ENV['BUNDLE_ID'],
  download_dsyms(version: 'latest', output_directory: "./ipa"),                 # Download dSYM files from iTC
  upload_symbols_to_crashlytics(gsp_path: "./xxxxx/mb_xxxxx/GoogleService-Info.plist", binary_path: "./ipa" , dsym_path: "./ipa/xxxxxxx-2.3.6-1.dSYM.zip")   # Upload them to Crashlytics
  clean_build_artifacts           # Delete the local dSYM files
#
end -->

The problem is 
 Successfully downloaded dSYM file for 2.3.6 - 1 to './ipa/com.xxx.xxx-2.3.6-1.dSYM.zip'
[15:55:11]: -------------------------------------------
[15:55:11]: --- Step: upload_symbols_to_crashlytics ---
[15:55:11]: -------------------------------------------
Extracting '/Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa/com.xxx.xxx-2.3.6-1.dSYM.zip'...
[15:55:13]: $ unzip -qo /Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa/xxx.xxx-2.3.6-1.dSYM.zip
[15:55:13]: Uploading 'e54d0908-3f6b-3983-bfdc-cfbaaef21260.dSYM'...
[15:55:13]: Permission denied - /Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa
[15:55:13]: Uploading '44354924-5644-34f1-8207-0508e1cdbd9c.dSYM'...
[15:55:13]: Permission denied - /Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa
[15:55:13]: Uploading 'b4421476-a22d-3527-9db9-4487cca09672.dSYM'...
[15:55:13]: Permission denied - /Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa
[15:55:13]: Uploading 'b11bf809-622c-3de4-a333-dac2a73dbdca.dSYM'...
[15:55:13]: Permission denied - /Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa
[15:55:13]: Uploading '9e445418-d14a-375e-8c4c-95f6aa439c3c.dSYM'...
[15:55:13]: Permission denied - /Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa
[15:55:13]: Uploading 'aab87360-52b0-3cf8-a599-52fe421a1dbe.dSYM'...
[15:55:13]: Permission denied - /Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa
[15:55:13]: Uploading '388bbd6d-889f-31bb-8fc3-d9974fac245f.dSYM'...
[15:55:13]: Permission denied - /Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa
[15:55:13]: Uploading 'b6b57875-12b3-3a9e-b4ae-a85d254b89ef.dSYM'...
[15:55:13]: Permission denied - /Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa
[15:55:13]: Uploading 'ffb32f36-d322-3336-baf4-5c3a35c2a0c2.dSYM'...
[15:55:13]: Permission denied - /Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa
[15:55:13]: Uploading '01cff3e0-80dc-30c7-b58c-e23c044a08da.dSYM'...
[15:55:13]: Permission denied - /Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa
[15:55:13]: Uploading '45a06a25-df21-34e0-abe2-131e337be1fe.dSYM'...
[15:55:13]: Permission denied - /Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa
[15:55:13]: Successfully uploaded dSYM files to Crashlytics 💯
[15:55:13]: -----------------------------------
[15:55:13]: --- Step: clean_build_artifacts ---
[15:55:13]: -----------------------------------
[15:55:13]: Cleaned up build artifacts 🐙


But nothing is uploaded sur Firebase Crashlytics

**Comment by janpio** [comment]
What is your question @madjuju?

**Comment by madjuju** [comment]
--- Step: upload_symbols_to_crashlytics ---
INFO [2019-11-18 15:57:11.19]: -------------------------------------------
INFO [2019-11-18 15:57:11.19]: Extracting '/Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa/com.pcb.coolncamp-2.3.6-1.dSYM.zip'...
INFO [2019-11-18 15:57:11.19]: $ unzip -qo /Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa/com.pcb.coolncamp-2.3.6-1.dSYM.zip
INFO [2019-11-18 15:57:11.25]: Uploading 'e54d0908-3f6b-3983-bfdc-cfbaaef21260.dSYM'...
DEBUG [2019-11-18 15:57:11.25]: upload_dsym using command: /Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa -gsp /Users/julien/mobile/V2-Cool-n-Camp-iOS/coolncamp/mb_coolncamp/GoogleService-Info.plist -p ios /private/var/folders/sr/n8r9brmx55g3sqs_jq7f2ym80000gn/T/d20191118-4273-awnbm9/e54d0908-3f6b-3983-bfdc-cfbaaef21260.dSYM
ERROR [2019-11-18 15:57:11.25]: Permission denied - /Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa
INFO [2019-11-18 15:57:11.25]: Uploading '44354924-5644-34f1-8207-0508e1cdbd9c.dSYM'...
DEBUG [2019-11-18 15:57:11.25]: upload_dsym using command: /Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa -gsp /Users/julien/mobile/V2-Cool-n-Camp-iOS/coolncamp/mb_coolncamp/GoogleService-Info.plist -p ios /private/var/folders/sr/n8r9brmx55g3sqs_jq7f2ym80000gn/T/d20191118-4273-awnbm9/44354924-5644-34f1-8207-0508e1cdbd9c.dSYM
ERROR [2019-11-18 15:57:11.25]: Permission denied - /Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa
INFO [2019-11-18 15:57:11.25]: Uploading 'b4421476-a22d-3527-9db9-4487cca09672.dSYM'...
DEBUG [2019-11-18 15:57:11.25]: upload_dsym using command: /Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa -gsp /Users/julien/mobile/V2-Cool-n-Camp-iOS/coolncamp/mb_coolncamp/GoogleService-Info.plist -p ios /private/var/folders/sr/n8r9brmx55g3sqs_jq7f2ym80000gn/T/d20191118-4273-awnbm9/b4421476-a22d-3527-9db9-4487cca09672.dSYM
ERROR [2019-11-18 15:57:11.25]: Permission denied - /Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa
INFO [2019-11-18 15:57:11.25]: Uploading '7947b67b-f285-3301-86cf-3a7261575006.dSYM'...
DEBUG [2019-11-18 15:57:11.25]: upload_dsym using command: /Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa -gsp /Users/julien/mobile/V2-Cool-n-Camp-iOS/coolncamp/mb_coolncamp/GoogleService-Info.plist -p ios /private/var/folders/sr/n8r9brmx55g3sqs_jq7f2ym80000gn/T/d20191118-4273-awnbm9/7947b67b-f285-3301-86cf-3a7261575006.dSYM
ERROR [2019-11-18 15:57:11.25]: Permission denied - /Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa
INFO [2019-11-18 15:57:11.25]: Uploading '9e445418-d14a-375e-8c4c-95f6aa439c3c.dSYM'...
DEBUG [2019-11-18 15:57:11.25]: upload_dsym using command: /Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa -gsp /Users/julien/mobile/V2-Cool-n-Camp-iOS/coolncamp/mb_coolncamp/GoogleService-Info.plist -p ios /private/var/folders/sr/n8r9brmx55g3sqs_jq7f2ym80000gn/T/d20191118-4273-awnbm9/9e445418-d14a-375e-8c4c-95f6aa439c3c.dSYM
ERROR [2019-11-18 15:57:11.25]: Permission denied - /Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa
INFO [2019-11-18 15:57:11.26]: Uploading 'aab87360-52b0-3cf8-a599-52fe421a1dbe.dSYM'...
DEBUG [2019-11-18 15:57:11.26]: upload_dsym using command: /Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa -gsp /Users/julien/mobile/V2-Cool-n-Camp-iOS/coolncamp/mb_coolncamp/GoogleService-Info.plist -p ios /private/var/folders/sr/n8r9brmx55g3sqs_jq7f2ym80000gn/T/d20191118-4273-awnbm9/aab87360-52b0-3cf8-a599-52fe421a1dbe.dSYM
ERROR [2019-11-18 15:57:11.26]: Permission denied - /Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa
INFO [2019-11-18 15:57:11.26]: Uploading '388bbd6d-889f-31bb-8fc3-d9974fac245f.dSYM'...
DEBUG [2019-11-18 15:57:11.26]: upload_dsym using command: /Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa -gsp /Users/julien/mobile/V2-Cool-n-Camp-iOS/coolncamp/mb_coolncamp/GoogleService-Info.plist -p ios /private/var/folders/sr/n8r9brmx55g3sqs_jq7f2ym80000gn/T/d20191118-4273-awnbm9/388bbd6d-889f-31bb-8fc3-d9974fac245f.dSYM
ERROR [2019-11-18 15:57:11.26]: Permission denied - /Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa
INFO [2019-11-18 15:57:11.26]: Uploading 'f348e3b3-6a3f-3dd6-abfd-a3903405cb49.dSYM'...
DEBUG [2019-11-18 15:57:11.26]: upload_dsym using command: /Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa -gsp /Users/julien/mobile/V2-Cool-n-Camp-iOS/coolncamp/mb_coolncamp/GoogleService-Info.plist -p ios /private/var/folders/sr/n8r9brmx55g3sqs_jq7f2ym80000gn/T/d20191118-4273-awnbm9/f348e3b3-6a3f-3dd6-abfd-a3903405cb49.dSYM
ERROR [2019-11-18 15:57:11.26]: Permission denied - /Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa
INFO [2019-11-18 15:57:11.26]: Uploading 'b6b57875-12b3-3a9e-b4ae-a85d254b89ef.dSYM'...
DEBUG [2019-11-18 15:57:11.26]: upload_dsym using command: /Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa -gsp /Users/julien/mobile/V2-Cool-n-Camp-iOS/coolncamp/mb_coolncamp/GoogleService-Info.plist -p ios /private/var/folders/sr/n8r9brmx55g3sqs_jq7f2ym80000gn/T/d20191118-4273-awnbm9/b6b57875-12b3-3a9e-b4ae-a85d254b89ef.dSYM
ERROR [2019-11-18 15:57:11.26]: Permission denied - /Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa
INFO [2019-11-18 15:57:11.26]: Uploading '01cff3e0-80dc-30c7-b58c-e23c044a08da.dSYM'...
DEBUG [2019-11-18 15:57:11.26]: upload_dsym using command: /Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa -gsp /Users/julien/mobile/V2-Cool-n-Camp-iOS/coolncamp/mb_coolncamp/GoogleService-Info.plist -p ios /private/var/folders/sr/n8r9brmx55g3sqs_jq7f2ym80000gn/T/d20191118-4273-awnbm9/01cff3e0-80dc-30c7-b58c-e23c044a08da.dSYM
ERROR [2019-11-18 15:57:11.26]: Permission denied - /Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa
INFO [2019-11-18 15:57:11.26]: Uploading '45a06a25-df21-34e0-abe2-131e337be1fe.dSYM'...
DEBUG [2019-11-18 15:57:11.26]: upload_dsym using command: /Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa -gsp /Users/julien/mobile/V2-Cool-n-Camp-iOS/coolncamp/mb_coolncamp/GoogleService-Info.plist -p ios /private/var/folders/sr/n8r9brmx55g3sqs_jq7f2ym80000gn/T/d20191118-4273-awnbm9/45a06a25-df21-34e0-abe2-131e337be1fe.dSYM
ERROR [2019-11-18 15:57:11.26]: Permission denied - /Users/julien/mobile/V2-Cool-n-Camp-iOS/ipa
INFO [2019-11-18 15:57:11.27]: Successfully uploaded dSYM files to Crashlytics 💯
INFO [2019-11-18 15:57:11.27]: ----------------------
