### ISSUE TITLE
Android Uploading to crashlytics. where can I find api_token, build_secret and crashlytics_path?

### ISSUE THREAD

**Issue by claudioviola** [fastlane/fastlane#15664]
### Question Checklist

- [ X] Updated fastlane to the latest version
- [ X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

#### Question Description
My project already use Crashlytics for crash report, so it include already the  google-service.json
Now I'm gonna to upload APK of beta in Crashlytics and I'm gonna to use this command in Fastfile
` crashlytics(
      crashlytics_path: "...",
      api_token: "...",
      build_secret: "...",
      apk_path: "..."
    )
`
Some questions:
1. Where is the  `crashlytics-devtools.jar`? Where it should be located?
2. Where can I find `api_token`? (Maybe is it the key located in google-service.json file?)
3. Where can I find `build_secret`? (Maybe is it the Web Api key located in General Setting page?)

I attached some screenshots
![Schermata 2019-11-15 alle 16 53 22](https://user-images.githubusercontent.com/6689594/68956852-2774ac00-07c9-11ea-92a3-225ddd23f03d.png)
![Schermata 2019-11-15 alle 16 52 38](https://user-images.githubusercontent.com/6689594/68956977-6b67b100-07c9-11ea-9364-7a44ccd624d2.png)

**Comment by janpio** [comment]
> Where is the `crashlytics-devtools.jar`? Where it should be located?

How is this related to the other questions you are asking? I do not see the context.

> * Where can I find `api_token`? (Maybe is it the key located in google-service.json file?)
> 
> * Where can I find `build_secret`? (Maybe is it the Web Api key located in General Setting page?)

This probably used to be displayed on the Crashlytics page somehow.

I know that Crashlytics used to have a binary installed on the user's computer, and `api_token` and `build_secret` were the first two params:

https://github.com/fastlane/fastlane/blob/89398d50c025dfd03fff813e26fcc5bd6f65a91c/fastlane/lib/fastlane/helper/crashlytics_helper.rb#L45-L48

**Comment by claudioviola** [comment]
Hey @janpio 
thanks for support

> How is this related to the other questions you are asking? I do not see the context unfortunately. 

I don't know what is crashlytics-devtools.jar but it is mentioned from Fastlane documentation. 
Context is: How do I setup the crashlytics command in Fastlane script to upload the apk and ipa?

> This probably used to be displayed on the Crashlytics page somehow.

I'm trying to figure out where there are placed, and asking if someone knows where are placed

>I know that Crashlytics used to have a binary installed on the user's computer

How do I download and  use this binary? Should be it included in `android` folder of my react-native project? 

Thank you again
Claudio

**Comment by claudioviola** [comment]
@timothy-volvo could you help me?
I saw an issue by you about crashlytics command.
Thanks

**Comment by claudioviola** [comment]
Definetly I understood `crashlytics` command included in Fastlane makes the upload to Fabric Crashlytics Beta. Instead I need to upload in Firebase Crashlytics App Distribution
Issue closed
