### ISSUE TITLE
[iOS] Getting asked for apple security questions when running pilot

### ISSUE THREAD

**Issue by adkaushik** [fastlane/fastlane#15660]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x]  I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x]  I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

This issue did not happen previously, but when executing pilot, build fails in circle ci with an error asking for security questions
 Pilot command fails to submit app to itunesconnect / appstoreconnect, with the following error.

<pre> [Invalid 2 step response {"securityQuestions"=>{"questions"=>[{"id"=>136, "question"=>"Question number 1?", "number"=>2, "userDefined"=>false}, {"id"=>145, "question"=>"Question number 2?", "number"=>3, "userDefined"=>false}]}, "crResetEnabled"=>false, "resetSecurityQuestionsSupportLink"=>"http://support.apple.com"}] 
 </pre>

##### Command executed

pilot

##### Complete output when running fastlane, including the stack trace and command used

<details>
Login to iTunes Connect
Service key is empty

[Invalid 2 step response {"securityQuestions"=>{"questions"=>[{"id"=>136, "question"=>"Question number 1?", "number"=>2, "userDefined"=>false}, {"id"=>145, "question"=>"Question number 2?", "number"=>3, "userDefined"=>false}]}, "crResetEnabled"=>false, "resetSecurityQuestionsSupportLink"=>"http://support.apple.com"}] 

</details>

### Environment

<details>
  <pre></pre>
</details>

**Comment by carloscuesta** [comment]
Yes, I'm having the same issue in Travis-CI. It's a little bit weird but I tried to log in with the account that uses the CI to ship the apps and the recovery questions had been requested upon website login 😕

**Comment by janpio** [comment]
Uh, can you please provide some more information - what exactly is happening when? What is output exactly? Please post the complete output.

Can you please also post your `fastlane env` output?

**Comment by carloscuesta** [comment]
In my particular case I'm using `fastlane@2.106.0`

And the error I've got is:

```
/Users/travis/.rvm/gems/ruby-2.4.5/gems/fastlane-2.106.0/spaceship/lib/spaceship/two_step_client.rb:45:in `handle_two_step':

[!] Invalid 2 step response {"securityQuestions"=>{"questions"=>[{"id"=>130, "question"=>"What was the name of your best friend as a teenager?", "number"=>1, "userDefined"=>false}, {"id"=>147, "question"=>"What is the name of your favourite sports team?", "number"=>3, "userDefined"=>false}]}, "crResetEnabled"=>false, "resetSecurityQuestionsSupportLink"=>"http://support.apple.com/kb/HT6170"} (RuntimeError)
```

**Comment by carloscuesta** [comment]
I'm updating to `fastlane@2.136.0` to see if the issue persists

**Comment by carloscuesta** [comment]
Seems that upgrading to `2.136.0` has fixed the issue ❤️ 🚀

**Comment by adkaushik** [comment]
Updating to the latest fastlane version 2.137 did fix the issue
