### ISSUE TITLE
unable to create provisioning profile using spaceship::Launcher 

### ISSUE THREAD

**Issue by littlewhitetwo** [fastlane/fastlane#15662]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
i use spaceship as library, and i found that it is  unable to create provisioning profile using spaceship::Launcher , and it would report "Please login using `Spaceship::Portal.login('user', 'password')` (RuntimeError)" 

##### Command executed
save the following code  as spacetest.rb
```
require 'fastlane'
require 'spaceship'

USERNAME = 'YOUR_APPLE_ID'
PASSWORD = 'YOUR_PASSWORD'

def test()

  bundle_id = 'YOUR_BUNDLE_ID'       #a registered bundle_id 

  client = Spaceship::Launcher.new( USERNAME, PASSWORD )
  client.select_team

  cert = client.certificate.production.all.first
  if cert == nil
      puts("#{__callee__} apple  no certification for bundle_id: #{bundle_id} ")
      return
  end

  profile = client.provisioning_profile.ad_hoc.create!(
                      bundle_id: bundle_id , certificate: cert, name: "dev12")

  puts profile

end

if $PROGRAM_NAME == __FILE__
  test
end
```

##### Complete output when running fastlane, including the stack trace and command used

```
Traceback (most recent call last):
	5: from ./spacetest.rb:35:in `<main>'
	4: from ./spacetest.rb:25:in `test'
	3: from /home/xxxx/.rvm/gems/ruby-2.6.3/gems/fastlane-2.135.2/spaceship/lib/spaceship/portal/provisioning_profile.rb:264:in `create!'
	2: from /home/xxxx/.rvm/gems/ruby-2.6.3/gems/fastlane-2.135.2/spaceship/lib/spaceship/portal/app.rb:111:in `find'
	1: from /home/xxxx/.rvm/gems/ruby-2.6.3/gems/fastlane-2.135.2/spaceship/lib/spaceship/portal/app.rb:85:in `all'
/home/xxxx/.rvm/gems/ruby-2.6.3/gems/fastlane-2.135.2/spaceship/lib/spaceship/portal/portal_base.rb:11:in `client': Please login using `Spaceship::Portal.login('user', 'password')` (RuntimeError)
```

<details>
  <pre>   N/A </pre>
</details>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | debian_based buster/sid                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.17.1                                             |
| Installation Source         | ~/.rvm/gems/ruby-2.6.3/bin/fastlane                            |
| Host                        | Ubuntu 18.04.3 LTS debian_based buster/sid (4.15.0-67-generic) |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.3/lib                                   |
| OpenSSL Version             | OpenSSL 1.1.1  11 Sep 2018                                     |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   | zh_CN.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| fastlane            | 2.135.2 | ✅ Up-To-Date  |
| credentials_manager | 1.0.0   | ✅ Up-To-Date  |
| spaceship           | 1.0.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 2.0.2        |
| rake                      | 13.0.1       |
| CFPropertyList            | 3.0.1        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| ast                       | 2.4.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.3        |
| coderay                   | 1.1.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander                 | 4.4.6        |
| commander-fastlane        | 4.4.6        |
| concurrent-ruby           | 1.1.5        |
| safe_yaml                 | 1.0.5        |
| crack                     | 0.4.3        |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.68.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.17.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.1       |
| multi_json                | 1.14.1       |
| os                        | 1.0.1        |
| signet                    | 0.12.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.1009  |
| mime-types                | 3.3          |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| digest-crc                | 0.4.1        |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.4.1        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.13.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| credentials_manager       | 1.0.0        |
| tzinfo                    | 2.0.0        |
| et-orbi                   | 1.2.2        |
| raabro                    | 1.1.6        |
| fugit                     | 1.3.3        |
| hashdiff                  | 1.0.0        |
| jaro_winkler              | 1.5.4        |
| kgio                      | 2.11.2       |
| method_source             | 0.9.2        |
| minitest                  | 5.13.0       |
| minitest-around           | 0.5.0        |
| minitest-focus            | 1.1.2        |
| mustermann                | 1.0.3        |
| oj                        | 3.9.2        |
| ox                        | 2.11.0       |
| parallel                  | 1.19.0       |
| parser                    | 2.6.5.0      |
| pry                       | 0.12.2       |
| rack                      | 2.0.7        |
| rack-cors                 | 1.0.6        |
| rack-protection           | 2.0.7        |
| rack-test                 | 1.1.0        |
| rainbow                   | 3.0.0        |
| raindrops                 | 0.19.0       |
| ruby-progressbar          | 1.10.1       |
| rubocop                   | 0.76.0       |
| rubocop-performance       | 1.5.1        |
| rufus-scheduler           | 3.6.0        |
| semantic_logger           | 4.6.0        |
| shotgun                   | 0.9.2        |
| tilt                      | 2.0.10       |
| sinatra                   | 2.0.7        |
| sinatra-logger            | 0.3.2        |
| unicorn                   | 5.5.1        |
| vcr                       | 5.0.0        |
| webmock                   | 3.7.6        |
</details>

*generated on:* **2019-11-15**
<details>
  <pre>   </pre>
</details>

**Comment by janpio** [comment]
cc @max-ott

**Comment by max-ott** [comment]
@littlewhitetwo could you please try what the error message tells you? `Spaceship::Portal.login('user', 'password')` I'm not aware that `Spaceship::Launcher` works anymore.

**Comment by max-ott** [comment]
@littlewhitetwo Could you still try using `Spaceship::Portal` to see if it works there?

**Comment by littlewhitetwo** [comment]
@max-ott
 of course it works. so, is Spaceship::Launcher   deprecated ?

**Comment by joshdholtz** [comment]
@littlewhitetwo @max-ott I actually had no idea that `Spaceship::Launcher` was a thing 🤔 I would probably suggest switching to `Spaceship::Portal` and `Spaceship::Tunes` if possible 😇 `Spaceship::Launcher` is really old and probably will get deprecated soon

**Comment by littlewhitetwo** [comment]
@joshdholtz  thanks a lot.
