### ISSUE TITLE
screengrab crashes after upgrade to 2.136.0 from 2.126.0

### ISSUE THREAD

**Issue by henningBunk** [fastlane/fastlane#15674]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information
- Breaking version: `2.136.0`
- Last working version: `2.135.2`

### Regression Description
fastlane screengrab is crashing after update to 2.136.0. it happens on macos catalina and mojave. 2.135.2 worked fine.

`/Library/Ruby/Gems/2.3.0/gems/fastlane-2.136.0/fastlane_core/lib/fastlane_core/fastlane_pty.rb:24:in `spawn': [!] No such file or directory - fork failed (FastlaneCore::FastlanePtyError)
`

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>fastlane screengrab                        165ms  Mon Nov 18 17:08:20 2019
[✔] 🚀
[17:08:43]: fastlane detected a Gemfile in the current directory
[17:08:43]: however it seems like you don't use `bundle exec`
[17:08:43]: to launch fastlane faster, please use
[17:08:43]:
[17:08:43]: $ bundle exec fastlane screengrab
[17:08:43]:
[17:08:43]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[17:08:43]: Successfully loaded '/a/path/Screengrabfile' 📄

+-----------------------------+---------------------------------------------------------+
|                        Detected Values from './Screengrabfile'                        |
+-----------------------------+---------------------------------------------------------+
| launch_arguments            | ["isScreengrab true"]                                   |
| build_tools_version         | 27.0.1                                                  |
| reinstall_app               | false                                                   |
| app_apk_path                | a/path/an.apk                                           |
| tests_apk_path              | another/path/aTest.apk                                  |
| app_package_name            | my.company                                              |
| tests_package_name          | my.company.test                                         |
| use_tests_in_packages       | ["my.company.app.tests"]                                |
| test_instrumentation_runner | my.company.RxTestRunner                                 |
| output_directory            | fastlane/screenshots                                    |
| clear_previous_screenshots  | false                                                   |
| skip_open_summary           | true                                                    |
+-----------------------------+---------------------------------------------------------+

[17:08:43]: The `aapt` command could not be found relative to your provided ANDROID_HOME at //Users/my.name/Library/Android/sdk
[17:08:43]: Please ensure that the Android SDK is installed and you have the build tools downloaded

+-----------------------------+---------------------------------------------------------+
|                            Summary for screengrab 2.136.0                             |
+-----------------------------+---------------------------------------------------------+
| android_home                | //Users/my.name/Library/Android/sdk                |
| build_tools_version         | 27.0.1                                                  |
| locales                     | ["en-US"]                                               |
| clear_previous_screenshots  | false                                                   |
| output_directory            | fastlane/screenshots                                    |
| skip_open_summary           | true                                                    |
| app_package_name            | my.company.app                            |
| tests_package_name          | my.company.app.test                                    |
| use_tests_in_packages       | ["my.company.app.tests"]                     |
| launch_arguments            | ["isScreengrab true"]                                   |
| test_instrumentation_runner | my.company.RxTestRunner                  |
| ending_locale               | en-US                                                   |
| use_adb_root                | false                                                   |
| app_apk_path                | a/path/an.apk                                           |
| tests_apk_path              | another/path/aTest.apk                                  |
| device_type                 | phone                                                   |
| exit_on_test_failure        | true                                                    |
| reinstall_app               | false                                                   |
| use_timestamp_suffix        | true                                                    |
| clean_status_bar            | false                                                   |
+-----------------------------+---------------------------------------------------------+

[17:08:44]: $ //Users/my.name/Library/Android/sdk/platform-tools/adb devices -l
[17:08:44]: ▸ List of devices attached
[17:08:44]: ▸ emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:1
[17:08:44]: $ //Users/my.name/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell echo \$EXTERNAL_STORAGE
[17:08:44]: ▸ /sdcard
[17:08:44]: Cleaning screenshots on device
[17:08:44]: $ //Users/my.name/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell rm -rf /sdcard/de.wetteronline.wetterapppro/screengrab
ls: /data/data/de.wetteronline.wetterapppro/app_screengrab: Permission denied
[17:08:44]: Exit status: 1
ls: /data/user/0/de.wetteronline.wetterapppro/files/de.wetteronline.wetterapppro/screengrab/en-US/images/screenshots: Permission denied
[17:08:44]: Exit status: 1
[17:08:44]: The `aapt` command could not be found on your system, so your app APK could not be validated
[17:08:44]: $ //Users/my.name/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop ro.build.version.sdk
[17:08:44]: ▸ 29
[17:08:44]: $  dump badging wetterApp/build/outputs/apk/googleWetterappPro/uitest/wetterApp-google-wetterapp-pro-uitest.apk
No such file or directory - fork failed

Looking for related GitHub issues on fastlane/fastlane...

➡️  Non-macOS platform support (Windows + Linux)
    https://github.com/fastlane/fastlane/issues/11687 [open] 82 💬
    3 weeks ago

➡️  iTMSTransporter using Signiant upload method even with `-t DAV` override
    https://github.com/fastlane/fastlane/issues/15375 [closed] 41 💬
    a week ago

➡️  [pilot] Uploading an IPA to TestFlight fails under Linux
    https://github.com/fastlane/fastlane/issues/14256 [closed] 29 💬
    01 Aug 2019

and 9 more at: https://github.com/fastlane/fastlane/search?q=No%20such%20file%20or%20directory%20-%20fork%20failed&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.136.0/fastlane_core/lib/fastlane_core/fastlane_pty.rb:24:in `spawn': [!] No such file or directory - fork failed (FastlaneCore::FastlanePtyError)
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.136.0/fastlane_core/lib/fastlane_core/fastlane_pty.rb:24:in `spawn'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.136.0/fastlane_core/lib/fastlane_core/command_executor.rb:52:in `execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.136.0/screengrab/lib/screengrab/runner.rb:399:in `enable_clean_status_bar'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.136.0/screengrab/lib/screengrab/runner.rb:75:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.136.0/screengrab/lib/screengrab/commands_generator.rb:49:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.136.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.136.0/screengrab/lib/screengrab/commands_generator.rb:67:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.136.0/screengrab/lib/screengrab/commands_generator.rb:19:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.136.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.136.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.6 (18G103)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.2.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.136.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version   | Update-Status  |
| ----------------------------------------- | --------- | -------------- |
| fastlane-plugin-firebase_app_distribution | undefined | 💥 Check failed |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.1        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.10.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.64.0       |
| faraday                   | 0.17.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.3.1      |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.4        |
| bundler                   | 2.0.2        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.0        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| psych                     | 2.1.0.1      |
</details>

*generated on:* **2019-11-18**
</details></pre>
</details>

**Comment by henningBunk** [comment]
Just tested the more recent version 2.135.2 and it works too. I will update above.

**Comment by cpaianoiwsinc** [comment]
Same situation for me on osx mojave, fastlane screengrab does this now

**Comment by micHar** [comment]
Had exactly the same issue. I reinstalled fastlane gem after updating macOs to Catalina and ended up with the newest version which failed with this error. Downgraded to version suggested by @henningBunk and it works.

**Comment by Hiroto-N** [comment]
Looks like it was an issue to do with the new clean status bar functionality trying to use aapt when fastlane doesn't find it - it can be mitigated by setting the ANDROID_HOME env variable or passing android_home to screengrab, but above PR will handle it better I think.

**Comment by henningBunk** [comment]
I have ANDROID_HOME set and when I set it up I made sure that `aapt` is available. 

Turned out that the build tools version that was set in the `Screengrabfile` wasn't up to date with the version used on the CI runners so `aapt` went missing some time ago without anyone noticing.

Now 2.136.2 is working again and I can get rid of my selfmade statusbar cleanup 👍

**Comment by cpaianoiwsinc** [comment]
That was it; I had been using fastlane screengrab for so long I didn't even have a build_tools_version specified in my Screengrabfile, nor did I have an ANDROID_HOME location set.  I took care of these things, noted aapt running on 2.135.2, upgraded to 2.136.0, and all is still working nicely.  Thank you!

**Comment by henningBunk** [comment]
Thanks for fixing this.
