### ISSUE TITLE
Fastlane Match not working on Github Actions

### ISSUE THREAD

**Issue by lawgimenez** [fastlane/fastlane#15682]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When I run fastlane match on my own local macOS machine it is working successfully. Meaning it can get the certificates/profiles on my private Github repository.

On Github Actions, when it runs `fastlane beta` it just hangs on `Cloning git repo` and it will be stuck on that forever.

Here's the `fastlane env` on my machine
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.1                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.1 (19B88)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.2.1                                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
ENV["MATCH_PASSWORD"] = "password"
# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build app"
  lane :beta do
  	match(
      type: "development",
      git_basic_authorization: Base64.encode64("<Github Personal Key"),
      readonly: true,
      keychain_name: "login.keychain",
      keychain_password: ENV["MATCH_PASSWORD"]
    )
  	build_app(scheme: "Scheme",
            workspace: "Scheme.xcworkspace",
            include_bitcode: true)
  	changelog_from_git_commits
    # add actions here: https://docs.fastlane.tools/actions
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("[[<BUNDLE ID>]]") # The bundle identifier of your app
apple_id("[[<TEAM ID>]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.136.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.68.0       |
| faraday                   | 0.17.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.1009  |
| mime-types                | 3.3          |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.1       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.4.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>

*generated on:* **2019-11-20**
</details>

The `fastlane env` on Github Action below:
### Stack
19

20
| Key                         | Value                                       |
21
| --------------------------- | ------------------------------------------- |
22
| OS                          | 10.15.1                                     |
23
| Ruby                        | 2.6.5                                       |
24
| Bundler?                    | false                                       |
25
| Git                         | git version 2.23.0                          |
26
| Installation Source         | /usr/local/lib/ruby/gems/2.6.0/bin/fastlane |
27
| Host                        | Mac OS X 10.15.1 (19B88)                    |
28
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.6.5/lib            |
29
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
30
| Is contained                | false                                       |
31
| Is homebrew                 | false                                       |
32
| Is installed via Fabric.app | false                                       |
33
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
34
| Xcode Version               | 11.1 

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by J2Marin** [comment]
👋  been though the same issue not long time ago

You need to specify git_basic_authorization in your match command. Worth checking: https://docs.fastlane.tools/actions/match/ 

> git_basic_authorization | Use a basic authorization header to access the git repo (e.g.: access via HTTPS, **GitHub Actions**, etc), usually a string in Base64

**Comment by lawgimenez** [comment]
@J2Marin Am I doing it correctly?

On my Matchfile I got
`git_url("https://github.com/<username>/fastlane-certs")`

And on my Fastfile I got
```match(
      type: "development",
      git_basic_authorization: Base64.encode64("<Github username>:<Github Personal Access Token>"),
      readonly: true,
      keychain_name: "login.keychain",
      keychain_password: ENV["MATCH_PASSWORD"]
    )```

**Comment by lawgimenez** [comment]
I got it to work by using `Base64.strict_encode64`

**Comment by iAmrMohamed** [comment]
you can add your  `git_basic_authorization` as an environment variable with the key `MATCH_GIT_BASIC_AUTHORIZATION` and  it can be pre encoded you don't need to encode it each time and you don't need to add `git_basic_authorization` in `match` parameters anymore

for the encoding you can get the encoded value once by calling this swift line from a playground or something 
```swift
"YOUR_TOKEN".data(using: .utf8)?.base64EncodedString()
```

**Comment by crewshin** [comment]
I can not get this to work for the life of me. I'm passing in ALL THE ENVVARSSSS ;)

Matchfile:
```ruby
git_url("https://github.com/Blahh/blahh.git")
storage_mode("git")
type("development")
app_identifier(["blahhhh"])
username("blahhh@gmail.com")
```

Build.yml
```ruby
name: Build and Deploy

on:
  push:
    branches:    
      - dev

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run fastlane firebase_beta
      env:
        APPLE_ACCOUNT: ${{ secrets.FASTLANE_USER }}
        FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        MATCH_REPO: ${{ secrets.MATCH_REPO }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}
        FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
        DELIVER_USER: ${{ secrets.DELIVER_USER }}
        DELIVER_PASSWORD: ${{ secrets.DELIVER_PASSWORD }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

        SIGNING_ID: ${{ secrets.SIGNING_ID }}
      run: |
        fastlane firebase_beta
```

Fastfile:
```ruby
lane :update_signing do
    match(git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"]) # <-- base64 encoded and stored in secrets.
end

lane :build_archive do |options|
    clear_derived_data()
    type = options[:type] || "development"
    update_signing(type: type) unless options[:skip_update_signing]

    silent = options[:silent_gym] || false
    runner_id = options[:runner_id] || "0"
    use_bitcode = options[:use_bitcode] || false

    if type == "appstore"
      export_method = "app-store"
      configuration = config_release
    else
      export_method = "development"
      configuration = config_debug
    end

    gym(scheme: scheme, output_name: flavor, output_directory: "builds", configuration: configuration, include_bitcode: use_bitcode, export_team_id: team_id, export_method: export_method, export_options: {
        compileBitcode: use_bitcode,
        uploadBitcode: use_bitcode
      }, silent: silent, xcargs: "-parallelizeTargets")
end

lane :firebase_beta do |options|
    force_match = options[:force_match] || false
    silent_gym = options[:silent_gym] || false
    versionNumber = options[:version_number] || get_version_number()
    build_number = options[:build_number] || get_build_number()
    type = options[:type] || "development"

    increment_build_number

    build_archive(type: type, silent_gym: silent_gym, build_number: build_number) unless options[:skip_build]

    commit = last_git_commit

    firebase_app_distribution(
      app: "1:0000000000000:ios:00000000000000", 
      release_notes: commit[:message],
      groups: "Beta Testers"
      )
end
```

Error:

```shell
Cloning into '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20200110-1342-1m32z17'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
[!] Error cloning certificates git repo, please make sure you have access to the repository - see instructions above
[23:07:27]: Exit status: 128
[23:07:27]: Error cloning certificates repo, please make sure you have read access to the repository you want to use
[23:07:27]: Run the following command manually to make sure you're properly authenticated:
[23:07:27]: $ git clone *** /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20200110-1342-1m32z17 -c http.extraheader='AUTHORIZATION: basic ***'
```

I feel like I'm passing in all requirements... but I guess I'm not positive. Since Github has actions now this might be a nice section to add to the docs.
