### ISSUE TITLE
[Regression] Cannot find changelog because no version code given - please specify :version_code

### ISSUE THREAD

**Issue by tpaik18** [fastlane/fastlane#15681]
#15191 # New Regression Checklist

- [ x] Updated fastlane to the latest version
- [ x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information
- Breaking version: 2.136
- Last working version: 2.121.1

### Regression Description
When uploading my change log to Play Store, supply fails with 
`[17:56:54]: Cannot find changelog because no version code given - please specify :version_code`

I thought this broke in fastlane 2.135 and would be fixed with 2.136, but it still fails with 2.136. 
Not sure why I have to explicitly set version_code. The changelog files in the metadata folder are already named like 40031.txt, where 40031 is the version code. Can we upload all of the changelog files by default when version_code is not specified? 

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>[17:55:39]: ----------------------------------
[17:55:39]: --- Step: ******_to_play_store ---
[17:55:39]: ----------------------------------

+-------------------------+------------------------------------------------------------------------+
|                                    Summary for supply 2.136.0                                    |
+-------------------------+------------------------------------------------------------------------+
| track                   | internal                                                               |
| json_key                | google_play_key.json                                                   |
| skip_******_images      | true                                                                   |
| skip_******_screenshots | true                                                                   |
| aab                     | /tmp/repo/FluStudy_us/android/app/build/outputs/bundle/release/app.aab |
| package_name            | org.******now.fluathome_us                                             |
| release_status          | completed                                                              |
| metadata_path           | ./fastlane/metadata/android                                            |
| skip_******_apk         | false                                                                  |
| skip_******_aab         | false                                                                  |
| skip_******_metadata    | false                                                                  |
| skip_******_changelogs  | false                                                                  |
| validate_only           | false                                                                  |
| check_superseded_tracks | false                                                                  |
| timeout                 | 300                                                                    |
| deactivate_on_promote   | true                                                                   |
+-------------------------+------------------------------------------------------------------------+

[17:55:40]: Preparing aab at path '/tmp/repo/FluStudy_us/android/app/build/outputs/bundle/release/app.aab' for ******...
[17:56:44]: Updating track 'internal'...
[17:56:45]: Uploading all track and release changes to Google Play...
[17:56:47]: Successfully finished the ****** to Google Play
[17:56:48]: Preparing to ****** for language 'en-US'...
[17:56:48]: Could not find changelog for '40031' and language 'en-US' at path ./fastlane/metadata/android/en-US/changelogs/40031.txt...
[17:56:48]: Uploading all meta changes to Google Play...
[17:56:50]: Successfully finished the ****** to Google Play
[17:56:50]: ---------------------------------------------------
[17:56:50]: --- Step: Switch to android slack_announce lane ---
[17:56:50]: ---------------------------------------------------
[17:56:50]: Cruising over to lane 'android slack_announce' 🚖
[17:56:50]: -------------------
[17:56:50]: --- Step: slack ---
[17:56:50]: -------------------
[17:56:50]: Successfully sent Slack notification
[17:56:50]: Cruising back to lane 'android internal' 🚘
[17:56:50]: ----------------------------------------------------------
[17:56:50]: --- Step: Switch to android prepare_release_notes lane ---
[17:56:50]: ----------------------------------------------------------
[17:56:50]: Cruising over to lane 'android prepare_release_notes' 🚖
[17:56:50]: ---------------------------------------------
[17:56:50]: --- Step: google_play_track_version_codes ---
[17:56:50]: ---------------------------------------------
[17:56:51]: Found '40031' version codes in track 'internal'
[17:56:51]: --------------------------------------------------------
[17:56:51]: --- Step: mkdir -p metadata/android/en-US/changelogs ---
[17:56:51]: --------------------------------------------------------
[17:56:51]: $ mkdir -p metadata/android/en-US/changelogs
[17:56:51]: --------------------------------------------------------------------
[17:56:51]: Step: echo "Build 31" > metadata/android/en-US/changelogs/40031.txt
[17:56:51]: --------------------------------------------------------------------
[17:56:51]: $ echo "Build 31" > metadata/android/en-US/changelogs/40031.txt
[17:56:51]: Cruising back to lane 'android internal' 🚘
[17:56:51]: ----------------------------------
[17:56:51]: --- Step: ******_to_play_store ---
[17:56:51]: ----------------------------------

+-------------------------+------------------------------------------------------------------------+
|                                    Summary for supply 2.136.0                                    |
+-------------------------+------------------------------------------------------------------------+
| track                   | internal                                                               |
| json_key                | google_play_key.json                                                   |
| skip_******_apk         | true                                                                   |
| skip_******_aab         | true                                                                   |
| skip_******_metadata    | false                                                                  |
| skip_******_images      | true                                                                   |
| skip_******_screenshots | true                                                                   |
| aab                     | /tmp/repo/FluStudy_us/android/app/build/outputs/bundle/release/app.aab |
| package_name            | org.******now.fluathome_us                                             |
| release_status          | completed                                                              |
| metadata_path           | ./fastlane/metadata/android                                            |
| skip_******_changelogs  | false                                                                  |
| validate_only           | false                                                                  |
| check_superseded_tracks | false                                                                  |
| timeout                 | 300                                                                    |
| deactivate_on_promote   | true                                                                   |
+-------------------------+------------------------------------------------------------------------+

[17:56:52]: Uploading all track and release changes to Google Play...
[17:56:53]: Successfully finished the ****** to Google Play
[17:56:54]: Preparing to ****** for language 'en-US'...
+-------------------------------------+----------------------------------------------------------------------------+
|                                                   Lane Context                                                   |
+-------------------------------------+----------------------------------------------------------------------------+
| DEFAULT_PLATFORM                    | android                                                                    |
| PLATFORM_NAME                       | android                                                                    |
| LANE_NAME                           | android internal                                                           |
| GRADLE_ALL_APK_OUTPUT_PATHS         | []                                                                         |
| GRADLE_ALL_AAB_OUTPUT_PATHS         | ["/tmp/repo/FluStudy_us/android/app/build/outputs/bundle/release/app.aab"] |
| GRADLE_ALL_OUTPUT_JSON_OUTPUT_PATHS | []                                                                         |
| GRADLE_AAB_OUTPUT_PATH              | /tmp/repo/FluStudy_us/android/app/build/outputs/bundle/release/app.aab     |
+-------------------------------------+----------------------------------------------------------------------------+
[17:56:54]: Cannot find changelog because no version code given - please specify :version_code

+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | opt_out_usage                                                 | 0           |
| 2    | default_platform                                              | 0           |
| 3    | gradle                                                        | 132         |
| 4    | ******_to_play_store                                          | 70          |
| 5    | Switch to android slack_announce lane                         | 0           |
| 6    | slack                                                         | 0           |
| 7    | Switch to android prepare_release_notes lane                  | 0           |
| 8    | google_play_track_version_codes                               | 1           |
| 9    | mkdir -p metadata/android/en-US/changelogs                    | 0           |
| 10   | echo "Build 31" > metadata/android/en-US/changelogs/40031.txt | 0           |
| 💥   | ******_to_play_store                                          | 2           |
+------+---------------------------------------------------------------+-------------+

[17:56:54]: fastlane finished with errors

[!] Cannot find changelog because no version code given - please specify :version_code
Exited with code 1</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.1                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.23.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.1 (19B88)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.2.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
opt_out_usage

default_platform(:android)

platform :android do
  desc "Build signed release aab and deploy to Internal track"
  lane :internal do
    track = "internal"
    gradle(
      task: "clean bundleRelease",
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => ENV["FEVER_SIGNING_STORE_FILE"],
        "android.injected.signing.store.password" => ENV["FEVER_SIGNING_STORE_PWD"],
        "android.injected.signing.key.alias" => ENV["FEVER_SIGNING_KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["FEVER_SIGNING_KEY_PWD"],
      }
    )
    build_number = Helper.backticks("cat ../app/version.properties | grep \"VERSION_CODE\" | cut -d'=' -f2").strip
    upload_to_play_store(
      track: track,
      json_key: "google_play_key.json",
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
    slack_announce(
      destination: "Play Store #{track} track",
      build_number: build_number
    )
    prepare_release_notes(
      track: track,
      build_number: build_number
    )
    upload_to_play_store(
      # only upload the metadata, e.g. release notes
      track: track,
      json_key: "google_play_key.json",
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_metadata: false,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  lane :prepare_release_notes do |options|
    build_number = options[:build_number]
    versions = google_play_track_version_codes(
      track: options[:track]
    )
    whats_new = "Build #{build_number}"
    metadata_dir="metadata/android/en-US/changelogs"
    sh("mkdir -p #{metadata_dir}")
    versions.each do |version|
      sh("echo \"#{whats_new}\" > #{metadata_dir}/#{version}.txt")
    end 
  end
    
  lane :slack_announce do |options|
    build_number = options[:build_number]
    destination = options[:destination]
    ENV["SLACK_URL"] = ENV["SLACK_WEBHOOK"]
    slack(
      message: "flu@home Chills build #{build_number} has been uploaded to #{destination} :rocket:",
      default_payloads: [:git_branch, :last_git_commit_hash],
      payload: {
        "Built by" => ENV["CIRCLE_USERNAME"],
        "Description" => ENV["BUILD_DESCRIPTION"],
        "Release Type" => ENV["EXPO_RELEASE_CHANNEL"],
        "Build log" => ENV["CIRCLE_BUILD_URL"]
      }
    )
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("google_play_key.json") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("org.auderenow.fluathome_us") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.136.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 2.0.2        |
| CFPropertyList            | 3.0.1        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.68.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.17.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.1       |
| multi_json                | 1.14.1       |
| os                        | 1.0.1        |
| signet                    | 0.12.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.1009  |
| mime-types                | 3.3          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.4.1        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.13.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2019-11-19**
</details></pre>
</details>

**Comment by JerellDR** [comment]
I'm having the same issue.

**Comment by gulsharan** [comment]
This error is thrown by the `supply` action because of the following (looks like a recent update)

**Reason:** (from supply action [help doc](https://docs.fastlane.tools/actions/supply/))

`:skip_upload_changelogs`: Changelogs were previously included with the `:skip_upload_metadata` but is now its own option

**Here's the change that fixed it for me:**

Add `skip_upload_changelogs: true` to the supply action invocation in your Fastfile

![image](https://user-images.githubusercontent.com/577631/69289768-34c3d900-0bc3-11ea-9b66-a418155aac35.png)

**Comment by tpaik18** [comment]
Thanks @gulsharan but I can't change that to true because I'm trying to upload changelogs in this step.

**Comment by gulsharan** [comment]
Ah! It worked for me because I had `skip_upload_metadata` as true, so skipping upload change-log was fine for my use-case. I think you will need to supply the `version_code` parameter instead.

**Comment by tpaik18** [comment]
@gulsharan I could do that as a workaround, but this is a regression. My changelog files are already named by version code as specified in https://docs.fastlane.tools/actions/supply/#changelogs-whats-new, and the upload of changelogs was working fine without a `version_code` parameter prior to 2.135.

**Comment by gulsharan** [comment]
@tpaik18 I am afraid I am by no means a Fastlane expert. Hopefully someone else can give you some useful pointers.

**Comment by 476rick** [comment]
I don't get how I can work around? I'm having the same issues on fastlane 2.137.0

I'm using the following code:

`  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease", properties: { 'versionCode' => 69 })
    supply(
        track:"alpha",
        skip_upload_changelogs: true,
        skip_upload_metadata: true,
        skip_upload_mimages: true, 
        skip_upload_screenshots: true,
        version_code: 69
    )
  end
`

I just want this to work. I will fix the insertion of the correct versionCode automatic later on.

**Comment by jbcorreia** [comment]
Sometimes when promoting from beta you would lose the changelog in that process, not sure if this change has anything to do with that...

I submit the changelog with the Beta release, so when doing the promote to Production I can skip the changelog upload as this is already there.

Cheers,
Joao

**Comment by xhairbait** [comment]
Just wondering, because I'm only trying to upload images but I don't want to supply a version code of an apk/aab I'm not ready to upload, why did we change it so you have to supply a version_code to upload screenshots/images?
