### ISSUE TITLE
Fastlane Match and Gym always freeze at Running script '[CP] Embed Pods Frameworks'

### ISSUE THREAD

**Issue by lawgimenez** [fastlane/fastlane#15695]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Fastlane Match and Gym always freeze at Running script '[CP] Embed Pods Frameworks'. But when I run on my local Xcode archive is successful. But on Github Actions it seems it won't proceed at all.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by janpio** [comment]
Does it work locally with fastlane or does it also fail there?

**Comment by lawgimenez** [comment]
Yes it works locally on my machine. But will freeze on Github Actions.

**Comment by thall90** [comment]
I am seeing this on a Jenkins CI build as well.

**Comment by tutipeti** [comment]
@thall90 I've seen this many times before on our Jenkins slaves - each time there was a popup on the machine asking for access to the certificates in the keychain. Not sure how @lawgimenez would get around that with GitHub Actions though 🤔

**Comment by lawgimenez** [comment]
@tutipeti no idea how, I'm new to Fastlane and their documentation is so severely lacking.

**Comment by janpio** [comment]
We are happy to accept you pull requests in https://github.com/fastlane/docs or in the action files in this repository 🚀

**Comment by isloop** [comment]
Me too.

> Yes it works locally on my machine. But will freeze on Github Actions.

My environment is as follows.
cocoapods v1.8.4
fastlane v2.140.0

**Comment by vandyshev** [comment]
Please, use `setup_ci(provider: "travis")` or [create_keychain](https://docs.fastlane.tools/actions/create_keychain/#create_keychain) before match and gym

**Comment by pajama** [comment]
> Please, use `setup_ci(provider: "travis")` or [create_keychain](https://docs.fastlane.tools/actions/create_keychain/#create_keychain) before match and gym

@vandyshev are you suggesting this would work with github actions? I don't see that in the list of providers for the fastlane docs.

**Comment by vandyshev** [comment]
@pajama It worked for me 2 months ago. All the `setup_ci(provider: "travis")` did - it's is a `create_keychain`. You can try `create_keychain` manually.
