### ISSUE TITLE
HTML report generated is empty not showing screenshots or any body in it

### ISSUE THREAD

**Issue by isabelrios** [fastlane/fastlane#15690]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

After all the screenshots are taken and the process finish correctly the HTML report is created but it is empty. 

```
 /MyPath/Library/Android/sdk/platform-tools/adb -s emulator-5554 pull /data/user/0/<app package>/files/<app package>/screengrab/fr-FR/images/screenshots /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/d20191120-19603-18h7ul8
[14:04:40]: Screenshots copied to fastlane/metadata/android/phoneScreenshots
[14:04:40]: Generating HTML Report
[14:04:40]: Successfully created HTML file with an overview of all the screenshots: '~/fenix/fastlane/metadata/android/screenshots.html'
[14:04:40]: Captured 26 screenshots! 📷✨
```

This used to work for me before the latest update to 2.136 and before using AndroidX.

I have noticed also that if I run more than one language, the previous screenshots are removed, only the latest one are available. Looks like the folder structure for each language is not kept. For example for French, I don't see the folder 'fr-FR' copied to my current directory, only 'phoneScreenshots' folder is created with all the screenshots under it. 

Before update:
![Screenshot 2019-11-21 at 10 44 39](https://user-images.githubusercontent.com/1897507/69326438-13f39600-0c4c-11ea-992a-67449d7fc57b.png)

Now:
![Screenshot 2019-11-21 at 10 47 34](https://user-images.githubusercontent.com/1897507/69326601-5b7a2200-0c4c-11ea-947a-1c52efa1cf2a.png)

I have tried to manually change the directories but so far no luck. Any idea about the issue, what should I modify? is it something known pending to be fixed?

Thank you in advance!

##### Command executed

sudo fastlane screengrab
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.1                                     |
| Ruby                        | 2.4.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.19.1                          |
| Installation Source         | ~/.rvm/rubies/ruby-2.4.2/bin/fastlane       |
| Host                        | Mac OS X 10.15.1 (19B88)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.2/lib                |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.2                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.136.0 | ✅ Up-To-Date  |

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by VitaminPSG** [comment]
Screengrab is migrated to AndroidX. But I still have issue with `report` and `output_directory`. - 
- `report` is empty.
- `output_directory` is  common for all locales. It means that screenshots for next locale overwrite previous locale.

**Comment by franzwarning** [comment]
Getting this same error on Android as well

**Comment by isabelrios** [comment]
I have not seen any fix or any workaround to get the screenshots on Android X as reported here, opening the issue again...

**Comment by janpio** [comment]
Sorry, I might need some more information:

Which fastlane versions worked? Which did not work?
Where did what exactly get changed to Androidx?
Did you try with the most recent fastlane version to see if this is fixed?

**Comment by Jeehut** [comment]
FYI: I'm seeing the exact same issue with the setup I reported in https://github.com/fastlane/fastlane/issues/15981. Note that _this_ issue appeared **after** I fixed the issue reported in the linked ticket.

**Comment by isabelrios** [comment]
Thanks @Jeehut! I can see the html report created successfully after I have updated to latest fastlane including your PR :)
