### ISSUE TITLE
SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER not recognising my phone number

### ISSUE THREAD

**Issue by wintermoon9** [fastlane/fastlane#15700]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
It seems the matcher for SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER is not able to recognise my phone number.

##### Command executed
I am trying to set SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER environmental variable to a number with the following format: 

+91 xxxxxxxxxx 

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 

```
Environment variable `SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER` is set, automatically requesting 2FA token via SMS to that number
SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER = *************

... 

Could not find a matching phone number to ************* in [{"numberWithDialCode"=>"+91 •••••• •••60", "pushMode"=>"sms", "obfuscatedNumber"=>"•••••• •••60", "id"=>1}].
Make sure your environment variable is set to the correct phone number.
If it is, please open an issue at https://github.com/fastlane/fastlane/issues/new and include this output so we can fix our matcher. Thanks.
```
 </pre>
</details>

**Comment by janpio** [comment]
Did you try setting the env variable without the space?

Can you please create a list of the exact value you set the ENV var to, and what exactly it output? Might very well be that Apple handles your phone number in _another_ special way that we might have to add there.

**Comment by wintermoon9** [comment]
I also tried it without the space:

+91xxxxxxxxxx

Here is my output:

Could not find a matching phone number to ************* in [{"numberWithDialCode"=>"+91 •••••• •••60", "pushMode"=>"sms", "obfuscatedNumber"=>"•••••• •••60", "id"=>1}].

Thanks!

**Comment by janpio** [comment]
So the things you mentioned:
+91xxxxxxxxxx
+91 •••••• •••60
•••••• •••60

Which can be reformatted as:
```
+91 xxxxxx xxxx
+91 •••••• •••60
    •••••• •••60
```

This shows that your real number has 1 number less than what Apple sends back. Is that correct?

**Comment by wintermoon9** [comment]
Yes I verified my number is correct and it seems it's one number less.

**Comment by janpio** [comment]
Hm, I wanted to start working on this and added your number to the test: https://github.com/fastlane/fastlane/pull/15743 Surprisingly it did find the phone number from the Apple response correctly and everything worked. So it seems I might be missing something :/

Does the `+91 xxxxxxxxxx` you are using as EVN var include a leading 0 for the actual number or something like that?

Can you maybe take a screenshot of your Apple ID web interface thing where it has the phone number under "TRUSTED PHONE NUMBERS"? (Of course feel free to replace one or two numbers with a black block to hide it.)

If you feel comfortable about that, send me an email to piotrowski@gmail.com with the actual number with no `x` and screenshot with no black bars.

**Comment by janpio** [comment]
@wintermoon9 Did you have time to look at my response? I would like to reproduce and fix this for you.
