### ISSUE TITLE
Failed to Submit app using Xcode 11.2

### ISSUE THREAD

**Issue by sanoj00b** [fastlane/fastlane#15704]
### New Issue Checklist

- [ ] Updated fastlane to the latest version - YES
- [ ] I read the [Contribution Guidelines] - YES (https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools) - YES 
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues) YES

##### Command executed
deliver

##### Complete output when running fastlane, including the stack trace and command used

ERROR ITMS-90534: "Invalid Toolchain. Your app was built with an unsupported SDK or version of Xcode. If you plan to submit this build to the App Store, make sure you are using the versions listed in https://help.apple.com/xcode/mac/current/#/devf16aefe3b or later."
Return status of iTunes Transporter was 1: ERROR ITMS-90534: "Invalid Toolchain. Your app was built with an unsupported SDK or version of Xcode. If you plan to submit this build to the App Store, make sure you are using the versions listed in https://help.apple.com/xcode/mac/current/#/devf16aefe3b or later."
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.

### Environment

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.21.0 (Apple Git-122.2)                           |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.6 (18G1012)                                     |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.2   

Its completed almost all the steps in last while uploading binary at that time is failing.

> [14:56:07]: Uploading binary to App Store Connect
> [14:56:17]: iTunes Transporter successfully finished its job
> [14:56:17]: Going to upload updated app to App Store Connect
> [14:56:17]: This might take a few minutes. Please don't interrupt the script.

**Comment by AminFadul** [comment]
Xcode 11.2 is deprecated officially by apple due to some critical issues 
you need to upgrade to Xcode 11.2.1 and make sure that your command line tools is also updated to 11.2.1
