### ISSUE TITLE
Running tns prepare ios work in shell but not in fastlane sh

### ISSUE THREAD

**Issue by douira** [fastlane/fastlane#15709]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Running `bundle exec fastlane ios build` results in the error. Running `fastlane ios build` works fine. However, fastlane warns me use use the gemfile instead. This is the same issue as this https://github.com/fastlane/fastlane/issues/14618 which was closed due to inactivity.

##### Command executed
`bundle exec fastlane ios build`

There relevant fastfile line is `sh("tns", "prepare", "ios", "--release", "--clean", "--env.production")`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> douira@douirasMBP ns-project % bundle exec fastlane ios build
[✔] 🚀 
+---------------------------+---------+-----------+
|                  Used plugins                   |
+---------------------------+---------+-----------+
| Plugin                    | Version | Action    |
+---------------------------+---------+-----------+
| fastlane-plugin-load_json | 0.0.1   | load_json |
+---------------------------+---------+-----------+

[18:26:27]: ----------------------------------------
[18:26:27]: --- Step: Verifying fastlane version ---
[18:26:27]: ----------------------------------------
[18:26:27]: Your fastlane version 2.137.0 matches the minimum requirement of 2.136.0  ✅
[18:26:27]: Driving the lane 'ios build' 🚀
[18:26:27]: ----------------------------------------------------------------
[18:26:27]: --- Step: tns prepare ios --release --clean --env.production ---
[18:26:27]: ----------------------------------------------------------------
[18:26:27]: $ tns prepare ios --release --clean --env.production
[18:26:31]: ▸ Xcode is installed and is configured properly.
[18:26:31]: ▸ xcodeproj is installed and is configured properly.
[18:26:31]: ▸ WARNING: WARNING: CocoaPods is not installed or is not configured properly.
[18:26:31]: ▸ You will not be able to build your projects for iOS if they contain plugin with CocoaPod file.
[18:26:31]: ▸ To be able to build such projects, verify that you have installed CocoaPods.
[18:26:31]: ▸ CocoaPods update is not required.
[18:26:31]: ▸ Your current CocoaPods version is newer than 1.0.0.
[18:26:31]: ▸ Python installed and configured correctly.
[18:26:31]: ▸ The Python 'six' package is found.
[18:26:31]: ▸ Xcode version 11.2.1 satisfies minimum required version 10.
[18:26:31]: ▸ Your environment is not configured properly and you will not be able to execute local builds. To continue, choose one of the following options:
[18:26:31]: ▸ Run $ tns preview command to enjoy NativeScript without any local setup.
[18:26:31]: ▸ Run $ tns setup command to run the setup script to try to automatically configure your environment for local builds.
[18:26:31]: ▸ In order to test your application use the $ tns login command to log in with your account and then $ tns cloud build command to build your app in the cloud.
[18:26:31]: ▸ Verify that your environment is configured according to the system requirements described at http://docs.nativescript.org/setup/ns-cli-setup/ns-setup-os-x.html#system-requirements.
+---------------+-----------+
|       Lane Context        |
+---------------+-----------+
| PLATFORM_NAME | ios       |
| LANE_NAME     | ios build |
+---------------+-----------+
[18:26:31]: Exit status of command 'tns prepare ios --release --clean --env.production' was 127 instead of 0.
Xcode is installed and is configured properly.
xcodeproj is installed and is configured properly.
WARNING: WARNING: CocoaPods is not installed or is not configured properly. 
 You will not be able to build your projects for iOS if they contain plugin with CocoaPod file.
To be able to build such projects, verify that you have installed CocoaPods. 

CocoaPods update is not required.
Your current CocoaPods version is newer than 1.0.0.
Python installed and configured correctly.
The Python 'six' package is found.
Xcode version 11.2.1 satisfies minimum required version 10.
Your environment is not configured properly and you will not be able to execute local builds. To continue, choose one of the following options: 
Run $ tns preview command to enjoy NativeScript without any local setup.
Run $ tns setup command to run the setup script to try to automatically configure your environment for local builds.
In order to test your application use the $ tns login command to log in with your account and then $ tns cloud build command to build your app in the cloud.
Verify that your environment is configured according to the system requirements described at http://docs.nativescript.org/setup/ns-cli-setup/ns-setup-os-x.html#system-requirements.

+------+------------------------------------+-------------+
|                    fastlane summary                     |
+------+------------------------------------+-------------+
| Step | Action                             | Time (in s) |
+------+------------------------------------+-------------+
| 1    | Verifying fastlane version         | 0           |
| 💥   | tns prepare ios --release --clean  | 4           |
|      | --env.production                   |             |
+------+------------------------------------+-------------+

[18:26:31]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

bundler: failed to load command: fastlane (/Users/douira/.gems/bin/fastlane)
FastlaneCore::Interface::FastlaneShellError: [!] Exit status of command 'tns prepare ios --release --clean --env.production' was 127 instead of 0.
Xcode is installed and is configured properly.
xcodeproj is installed and is configured properly.
WARNING: WARNING: CocoaPods is not installed or is not configured properly. 
 You will not be able to build your projects for iOS if they contain plugin with CocoaPod file.
To be able to build such projects, verify that you have installed CocoaPods. 

CocoaPods update is not required.
Your current CocoaPods version is newer than 1.0.0.
Python installed and configured correctly.
The Python 'six' package is found.
Xcode version 11.2.1 satisfies minimum required version 10.
Your environment is not configured properly and you will not be able to execute local builds. To continue, choose one of the following options: 
Run $ tns preview command to enjoy NativeScript without any local setup.
Run $ tns setup command to run the setup script to try to automatically configure your environment for local builds.
In order to test your application use the $ tns login command to log in with your account and then $ tns cloud build command to build your app in the cloud.
Verify that your environment is configured according to the system requirements described at http://docs.nativescript.org/setup/ns-cli-setup/ns-setup-os-x.html#system-requirements.

  /Users/douira/.gems/gems/fastlane-2.137.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!'
  /Users/douira/.gems/gems/fastlane-2.137.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /Users/douira/.gems/gems/fastlane-2.137.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
  /Users/douira/.gems/gems/fastlane-2.137.0/fastlane/lib/fastlane/helper/sh_helper.rb:16:in `sh_no_action'
  /Users/douira/.gems/gems/fastlane-2.137.0/fastlane/lib/fastlane/fast_file.rb:219:in `block in sh'
  /Users/douira/.gems/gems/fastlane-2.137.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/douira/.gems/gems/fastlane-2.137.0/fastlane/lib/fastlane/fast_file.rb:218:in `sh'
  /Users/douira/.gems/gems/fastlane-2.137.0/fastlane/lib/fastlane/fast_file.rb:212:in `sh'
  Fastfile:31:in `block (2 levels) in parsing_binding'
  /Users/douira/.gems/gems/fastlane-2.137.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/douira/.gems/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/douira/.gems/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/douira/.gems/gems/fastlane-2.137.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/douira/.gems/gems/fastlane-2.137.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Users/douira/.gems/gems/fastlane-2.137.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/douira/.gems/gems/fastlane-2.137.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/douira/.gems/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/douira/.gems/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/douira/.gems/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/douira/.gems/gems/fastlane-2.137.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/douira/.gems/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/douira/.gems/gems/fastlane-2.137.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
  /Users/douira/.gems/gems/fastlane-2.137.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/douira/.gems/gems/fastlane-2.137.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Users/douira/.gems/gems/fastlane-2.137.0/bin/fastlane:23:in `<top (required)>'
  /Users/douira/.gems/bin/fastlane:23:in `load'
  /Users/douira/.gems/bin/fastlane:23:in `<top (required)>'</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.1                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.0                                             |
| Installation Source         | ~/.gems/bin/fastlane                                           |
| Host                        | Mac OS X 10.15.1 (19B88)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.2.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.136.0"

#update_fastlane

#packageJson = load_json(json_path: "package.json")
#appId = packageJson["nativescript"]["id"]
#variant = packageJson["variants"][appId]

#UI.message "Using Variant '#{appId}' with display name '#{variant["name"]}'"

desc "test lane"
lane :test do
  print "TEST SUCCESSFUL!"
end

platform :ios do

  desc "Fetch certificates and provisioning profiles"
  lane :certificates do
    match(type: "development")
    match(type: "appstore")
  end

  desc "Build and run iOS app locally"
  lane :build_local_dev do
    sh("tns", "run", "ios")
  end

  desc "Build the iOS application."
  lane :build do
    sh("tns", "prepare", "ios", "--release", "--clean", "--env.production")

    match(type: "appstore")

    update_app_identifier(
      xcodeproj: "./platforms/ios/nsproject.xcodeproj",
      info_plist: "nsproject/nsproject-Info.plist",
      app_identifier: appId
    )

    build_ios_app(
      scheme: "nsproject",
      workspace: "./platforms/ios/nsproject.xcworkspace",
      export_method: "app-store",
      output_directory: "./ios-output"
    )
  end

  desc "Increment App Version" #( and push)
  lane :increment_version do
      ensure_git_status_clean

      increment_build_number(xcodeproj: "./platforms/ios/nsproject.xcworkspace")

      #commit_version_bump(xcodeproj: "./platforms/ios/nsproject.xcworkspace")

      #add_git_tag

      #push_to_git_remote
  end

  desc "Ship to Testflight."
  lane :beta do
    #build

    changelog_from_git_commits(merge_commit_filtering: "exclude_merges")

    upload_to_testflight(
      groups: "All Testers"
    )
  end

end

platform :android do

  desc "Build the Android application."
  lane :build do
  end

  desc "Ship to Playstore Alpha track."
  lane :alpha do
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id "info@company.com"

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.137.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-load_json | 0.0.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.69.1       |
| faraday                   | 0.17.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.0.2        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.1009  |
| mime-types                | 3.3          |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.1       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.4.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.1        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.13.0       |
| json                      | 2.2.0        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| fastlane-plugin-load_json | 0.0.1        |
</details>

*generated on:* **2019-11-25**
</details> </pre>
</details>

**Comment by janpio** [comment]
> [18:26:31]: Exit status of command 'tns prepare ios --release --clean --env.production' was 127 instead of 0.



> WARNING: WARNING: CocoaPods is not installed or is not configured properly.

Cocoapods is probably not available in the `bundle exec` context. Not sure how to fix that.

**Comment by douira** [comment]
No, this has not been fixed, there is just no solution yet. It would be nice if somebody would stop the bot from closing this as long as the issue is not fixed.

**Comment by nitrotm** [comment]
Well, I had to add `cocoapods` to my project's `Gemfile`.

**Comment by douira** [comment]
no this has not been fixed, the problem is just that apparently nobody has looked at it. (and they are relying on the bot cleaning up the issues they've ignored)

**Comment by janpio** [comment]
@douira Did you look into my reply or what @nitrotm posted?

**Comment by douira** [comment]
Thanks, I’m not working on the project this issue was relevant for anymore so I’m not going to push the issue any further.
