### ISSUE TITLE
Missing app icon...

### ISSUE THREAD

**Issue by SteveLobdell** [fastlane/fastlane#15712]
### New Issue Checklist

- [ X] Updated fastlane to the latest version
- [ X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Command executed
fastlane deliver - "Missing App Icon. An app icon measuring 1024 by 1024 pixels in PNG format..."  I have an app icon in my asset catalog measuring 1024x1024 with no alpha channel.  I've actually uploaded it manually to itunes connect.  When I execute fastlane deliver I get this error about my app icon.

##### Complete output when running fastlane, including the stack trace and command used
--capture_output didn't do anything, didn't run my lanes

### Environment

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.13.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.69.1       |
| faraday                   | 0.17.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.1009  |
| mime-types                | 3.3          |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.1       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.4.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| CFPropertyList            | 3.0.1        |
| json                      | 2.2.0        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| fastlane-plugin-appicon   | 0.14.1       |
</details>

**Comment by SteveLobdell** [comment]
Hey bot, that's like the only think I have included...

**Comment by max-ott** [comment]
@SteveLobdell Without your Fastfile, commands or the full stack trace it's really hard to help here.

**Comment by SteveLobdell** [comment]
fastfile:

 platform :ios do
 desc "Submit production"
  lane :test do

    deliver(
      username: "stevelobdell@gmail.com",
    )

    upload_to_testflight(
      username: "stevelobdell@gmail.com",
      build_number: '2'
    )

 end
end

command:
bundle exec fastlane ios test

output:

[00:45:09]: Successfully uploaded screenshots to App Store Connect
[00:45:10]: Uploading app icon...
[00:45:15]: Uploading binary to App Store Connect
[00:45:15]: Going to upload updated app to App Store Connect
[00:45:15]: This might take a few minutes. Please don't interrupt the script.
[00:45:34]: [Transporter Error Output]: ERROR ITMS-90704: "Missing App Icon. An app icon measuring 1024 by 1024 pixels in PNG format must be included in the Asset Catalog of apps built for iOS, iPadOS, or watchOS. Without this icon, apps cannot be submitted for review. For details, see https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/app-icon/."
[00:45:34]: [Transporter Error Output]: ERROR ITMS-90189: "Redundant Binary Upload. You've already uploaded a build with build number '1' for version number '2.0'. Make sure you increment the build string before you upload your app to App Store Connect. Learn more in Xcode Help (http://help.apple.com/xcode/mac/current/#/devba7f53ad4)."
[00:45:34]: Transporter transfer failed.
[00:45:34]: 
[00:45:34]: ERROR ITMS-90704: "Missing App Icon. An app icon measuring 1024 by 1024 pixels in PNG format must be included in the Asset Catalog of apps built for iOS, iPadOS, or watchOS. Without this icon, apps cannot be submitted for review. For details, see https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/app-icon/."
ERROR ITMS-90189: "Redundant Binary Upload. You've already uploaded a build with build number '1' for version number '2.0'. Make sure you increment the build string before you upload your app to App Store Connect. Learn more in Xcode Help (http://help.apple.com/xcode/mac/current/#/devba7f53ad4)."

**Comment by SteveLobdell** [comment]
Also, as I mentioned the icon is in the icon asset catalog, and also in fastlane/metadata/app_icon.png

**Comment by SteveLobdell** [comment]
Sorry, I'm an idiot.  I didn't rebuild the app after updating and was just trying to deliver the same files over and over.  Thanks!
