### ISSUE TITLE
Add support for Catalyst

### ISSUE THREAD

**Issue by IngmarStein** [fastlane/fastlane#15719]
#### Motivation Behind Feature

Apple advertises Catalyst as the easiest way to bring iPad apps to macOS. https://developer.apple.com/mac-catalyst/

#### Feature Description

If the `SUPPORTS_MACCATALYST` build setting is set to `YES`, fastlane could allow a user to choose whether they want to build for iOS or macOS, resulting in either an ipa file or an app bundle.
Ideally, snapshot would also allow snapshotting on macOS, adhering to https://help.apple.com/app-store-connect/#/devd274dd925, but that could be a follow-up request (see #11092).

#### Alternatives or Workarounds

Currently, it's possible to perform some actions (like `run_tests`) on Catalyst-enabled projects by passing `platform=macOS,arch=x86_64,variant=Mac Catalyst` as `destination`.
However, this fails for other actions like `build_ios_app` which assume that an iOS project always produces an ipa or app bundle. For example, https://github.com/fastlane/fastlane/blob/a934ee6dc08c62098f0f28f9a91cefae8d568bd6/gym/lib/gym/runner.rb#L23 fails with `The generated archive is invalid`.

**Comment by IngmarStein** [comment]
😢

**Comment by joshdholtz** [comment]
Re-opening!! Actively working on this 😊
