### ISSUE TITLE
Set release notes for ios and android

### ISSUE THREAD

**Issue by Omaryasirm** [fastlane/fastlane#15710]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
How to set release notes for ios and android

#### Question Description
I'm relatively new to fastlane and would like some help on how to set the release notes. I've tried everything for android and ios but just can't seem to get it to work.

For Ios this is what I have tried.
    `changelog_from_git_commits(commits_count: 1)
deliver(
      release_notes: {
        'default' => lane_context[SharedValues::FL_CHANGELOG]
      } 
    )`

For Android, the docs said to use crashlytics but I can't seem to find the api_token in firebase console, also not sure about how to set the apk_path as i use bundles not apks.

Any help would really be appreciated.

**Comment by max-ott** [comment]
You might want to check out the official docs. https://docs.fastlane.tools/getting-started/android/beta-deployment/#release-notes and https://docs.fastlane.tools/getting-started/ios/beta-deployment/#release-notes
