### ISSUE TITLE
xcodebuild -showBuildSettings` called twice for Scan

### ISSUE THREAD

**Issue by pradyhk** [fastlane/fastlane#15717]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Scan runs xcodebuild -showBuildSettings twice in succession with identical arguments. Scan is called around 27 times in CI for full build and every time scan is called it executes below command twice with same arguments . Each time command is executed, it takes around 40-60 seconds . And for full build it is getting executed 54 times ( 27*2) adding around 50 minutes of extra time.

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>[22:32:11 $ xcodebuild -showBuildSettings -workspace Enterprise.xcworkspace -scheme Enterprise
22:33:16 $ xcodebuild -showBuildSettings -workspace Enterprise.xcworkspace -scheme Enterprise
22:34:15 ]</pre>
</details>

### Environment
<details>
 fastlane_version "2.132.0"
 Ruby                        | 2.5.3 
</details>

**Comment by janpio** [comment]
We're happy to review and accept Pull Requests that improve this behavior.

**Comment by pradyhk** [comment]
@janpio i have created for this issue : 
https://github.com/fastlane/fastlane/pull/15732

**Comment by ojizero** [comment]
@pradyhk I think you can close this issue since your PR is merged correct?

**Comment by rogerluan** [comment]
Correct @ojizero ! 🤗 

Closing this now, since https://github.com/fastlane/fastlane/pull/15732 got merged and released already 🚀
