### ISSUE TITLE
version.rb Malformed version number string undefined (ArgumentError)

### ISSUE THREAD

**Issue by shnaz** [fastlane/fastlane#15715]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Command executed

Everything finishes as expected, the APK/IPA is built and sent to hockeyApp etc etc. But I still get this error in the end.

This error appeared after I had updated fastlane to latest 2.137.0, using `sudo gem install fastlane`.

##### Complete output when running fastlane, including the stack trace and command used

/Library/Ruby/Site/2.3.0/rubygems/version.rb:208:in `initialize': Malformed version number string undefined (ArgumentError)
<details>
  <pre> 
/Library/Ruby/Site/2.3.0/rubygems/version.rb:208:in `initialize': Malformed version number string undefined (ArgumentError)
	from /Library/Ruby/Site/2.3.0/rubygems/version.rb:199:in `new'
	from /Library/Ruby/Site/2.3.0/rubygems/version.rb:199:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/plugins/plugin_update_manager.rb:29:in `block in show_update_status'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/plugins/plugin_update_manager.rb:26:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/plugins/plugin_update_manager.rb:26:in `show_update_status'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/commands_generator.rb:43:in `ensure in start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/commands_generator.rb:53:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.137.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
</pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.17.2 (Apple Git-113)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.6 (17G5019)                                     |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.1                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.137.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.13.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday                   | 0.17.0       |
| faraday_middleware        | 0.13.1       |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.16.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| signet                    | 0.11.0       |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| os                        | 0.9.6        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| CFPropertyList            | 3.0.1        |
| claide                    | 1.0.3        |
| addressable               | 2.7.0        |
| babosa                    | 1.0.3        |
| excon                     | 0.69.1       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| dotenv                    | 2.7.5        |
| multi_json                | 1.14.1       |
| memoist                   | 0.16.1       |
| emoji_regex               | 1.0.1        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| psych                     | 2.1.0.1      |
</details>

*generated on:* **2019-11-26**
</details> </pre>
</details>

**Comment by Dids** [comment]
This is very likely coming from a plugin. For me, it ended up being `fastlane-plugin-souyuz`, which broke at version `0.9.0` (invalid version in the plugin spec file), and downgrading back to `0.8.1` fixed it.

**Comment by shnaz** [comment]
@Dids Thanks for the input. Do you have any tricks that I can try to find this "faulty" plugin? Or how did you find the plugin in your case?

Thanks in advance :)

**Comment by Dids** [comment]
Check `fastlane/Pluginfile` (if you have one), then Google for each plugin listed there.
Most of them will be available on GitHub, where you can then go to Releases for each project and see if there's been a recent update that broke it.

**Comment by shnaz** [comment]
I found it, it was one called 'fastlane-plugin-appicon' in my case. 
Thank you a lot, @Dids!
