### ISSUE TITLE
react-native gradle setup for injected signing

### ISSUE THREAD

**Issue by ssilverr** [fastlane/fastlane#15726]
### Question Checklist

- [ ✅] Updated fastlane to the latest version
- [✅] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [✅] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [✅] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

I'm trying to use the `gradle` action to build a signed apk, but the properties override does not work as expected
#### Question Description

according to the gradle docs, I can do it like this:
```
gradle(
  task: "assemble",
  build_type: "Release",
  print_command: false,
  properties: {
    "android.injected.signing.store.file" => "myKeystoreFile.keystore",
    "android.injected.signing.store.password" => "myKeystoreFile_password",
    "android.injected.signing.key.alias" => "myKeystoreAlias",
    "android.injected.signing.key.password" => "myKeystoreAlias_password",
  }
)
```

But then I get this error:
> Keystore file '/Users/myUser/testApp/android/myKeystoreFile.keystore' not found for signing config 'externalOverride'.

My myKeystoreFile is under /android/app

But if I move it up a folder to /android, then:
>'/Users/myUser/testApp/android/app/myKeystoreFile.keystore' specified for property 'signingConfig.storeFile' does not exist.

If i copy myKeystoreFile to both places, gradle / fastlane succeeds, and I get a signed apk. But that's not exactly a desirable option, is it. 

So, instead if I follow the singing config setup in react-native, but leave out the gradle.properties part, and change the gradle action to:

```
desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(
      task: "assemble",
      build_type: "Release",
      print_command: false,
      properties: {
        "MYAPP_UPLOAD_STORE_FILE" => ENV["KEYSTORE_FILE"],
        "MYAPP_UPLOAD_STORE_PASSWORD" => ENV["KEYSTORE_PW"],
        "MYAPP_UPLOAD_KEY_ALIAS" => ENV["ALIAS"],
        "MYAPP_UPLOAD_KEY_PASSWORD" => ENV["ALIAS_PW"]
      }
      )
  end
```

And it works! 
With the myKeystoreFile under android/app

Is this s bug? How should I set up gradle file to work with what's in the fasltane docs? 

Gradle version:  5.5

<details>
  <summary>signing config in app/build.gradle: </summary>

  ```
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
        release {
            if (project.hasProperty('MYAPP_UPLOAD_STORE_FILE')) {
                storeFile file(MYAPP_UPLOAD_STORE_FILE)
                storePassword MYAPP_UPLOAD_STORE_PASSWORD
                keyAlias MYAPP_UPLOAD_KEY_ALIAS
                keyPassword MYAPP_UPLOAD_KEY_PASSWORD
            }
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://facebook.github.io/react-native/docs/signed-apk-android.
            signingConfig signingConfigs.release
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
```

</details>

**Comment by janpio** [comment]
> ```
> properties: {
>     "android.injected.signing.store.file" => "myKeystoreFile.keystore",
>     "android.injected.signing.store.password" => "myKeystoreFile_password",
>     "android.injected.signing.key.alias" => "myKeystoreAlias",
>     "android.injected.signing.key.password" => "myKeystoreAlias_password",
>   }
> )
> ```
> 
> 
> But then I get this error:
> 
> > Keystore file '/Users/myUser/testApp/android/myKeystoreFile.keystore' not found for signing config 'externalOverride'.
> 
> 
> My myKeystoreFile is under /android/app

Wouldn't it make sense to change the property values to add `app/` as a suffix to all the paths then?

**Comment by ssilverr** [comment]
@janpio 

I've tried that as well, then it would write something like:

>'/Users/myUser/testApp/`android/app/app/`myKeystoreFile.keystore' specified for property 'signingConfig.storeFile' does not exist.

**Comment by janpio** [comment]
This is confusing me a bit:

> not found for signing config 'externalOverride'.

Does that mean anything to you? Can you find it in your project?

**Comment by ssilverr** [comment]
Not really, and it's not in the project. But since we use `android.inject...`, it would make sence to me, that this an externalOverride?

**Comment by janpio** [comment]
Can you reproduce this with a vanilla React Native project that you could put on GitHub so we can reproduce this properly?
