### ISSUE TITLE
Update frames_generator to get the latest images for iPad Pro 12.9 (3rd gen)

### ISSUE THREAD

**Issue by ainame** [fastlane/fastlane#15725]
### Feature Request

Update `frameit/frames_generator/Rakefile` to make it work properly. Actually it doesn't follow the latest directory structure. Now iPad Pro's directory has an additional nested directory. Once it's solved, `frames_generator` can process the latest iPad Pro's images.

Previous

```
$ tree Tablets/
Tablets/
├── Apple\ iPad\ Air\ 2
...
├── Apple\ iPad\ Pro
│   ├── Apple\ iPad\ Pro.sketch
│   ├── Device
│   │   ├── Apple\ iPad\ Pro\ Gold.png
...
│   └── Device\ with\ Shadow
│       ├── Apple\ iPad\ Pro\ Gold.png
...
```

Current
```
$ tree Tablets/
Tablets/
├── Apple\ iPad
├── Apple\ iPad\ Pro
│   ├── Apple\ iPad\ Pro.sketch
│   ├── Device
│   │   ├── Device\ with\ Pencil
│   │   │   ├── Apple\ iPad\ Pro\ 11"\ Silver\ -\ Landscape.png
...
│   │   └── Device\ without\ Pencil
│   │       ├── Apple\ iPad\ Pro\ 11"\ Silver\ -\ Landscape.png
...
│   └── Device\ with\ Shadow
│       ├── Device\ with\ Pencil
│       │   ├── Apple\ iPad\ Pro\ 11"\ Silver\ -\ Landscape.png
...
│       └── Device\ without\ Pencil
│           ├── Apple\ iPad\ Pro\ 11"\ Silver\ -\ Landscape.png
...
```

#### Motivation Behind Feature

Since iPad Pro 12.9 inch (3rd generation) came out last year, `frameit` hasn't officially supported that latest iPad Pro due to the Facebook's site lacking the support of it. So several issues related to that have been raised already.

* https://github.com/fastlane/fastlane/issues/14713
* https://github.com/fastlane/fastlane/issues/14812
* https://github.com/fastlane/frameit-frames/issues/7
* https://github.com/fastlane/frameit-frames/pull/8

However, I just noticed that the Facebook design team updated the zip file including the latest iPad Pro last month. So it's time to update https://github.com/fastlane/frameit-frames as well as updating `frameit/frames_generator/Rakefile` to get it right for the new directory structure for iPad Pro.

#### Feature Description

* Fix `frames_generator/Rakefile` to provide device frame images for iPad Pro 12.9 inch (3rd generation) (See https://github.com/ainame/fastlane/compare/e407b329f41498a55fa63c22b55de81355eb1e65...386c666a3)
* Update `fastlane/frameit-frames` accordingly

The biggest drawback of this would be `frames_generator` also can no longer generate the previous generation of iPad Pro 12.9 inch (**2nd** generation) unless someone has old zip files because Facebook design's zip file no longer contains older generations' images. 

That drawback might not be a problem as Apple says _Always use the latest-generation product images for which your app is currently developed_  [here](https://developer.apple.com/app-store/marketing/guidelines/). That is also pointed out here https://github.com/fastlane/frameit-frames/pull/8#issuecomment-489454304  

Additionally accordingly to [the guideline](https://help.apple.com/app-store-connect/#/devd274dd925), screenshots for iPad Pro 12.9 inch 2nd gen isn't mandatory. We can alternatively upload images for either "11 inch (iPad Pro)", "10.5 inch (7th generation iPad, iPad Pro, iPad Air)", or "9.7 inch (iPad, iPad mini)"

So fastlane team can choose from followings

* Drop older generation iPad Pro (2nd gen) support by `frames_generator` and announce that `fastlane` users still can use older one with additional steps
* Keep supporting both 2nd and 3rd gen with using images previously uploaded to `fastlane/frameit-frames`
* etc...

#### Alternatives or Workarounds

Some people are already doing workarounds which they just download images from Apple's Market Resources site or some website directly and update offsets.json manually.

* https://github.com/fastlane/frameit-frames/pull/8
* https://github.com/fastlane/fastlane/issues/14713#issuecomment-504708205

Both wouldn't meet frame_generator's automation and the latter one had unclear license issue.

**Comment by janpio** [comment]
Thank you @ainame, your writeup of the situation is lovely and I will show it to the relevant people to get a decision here - I assume we will go with adding this new image and remove the old one that is not included at Facebook Design any more.

**Comment by JulesMoorhouse** [comment]
@janpio what did they say?

**Comment by ainame** [comment]
@janpio Any updates?

**Comment by joshdholtz** [comment]
@ainame Heyyy! I just came across this issue and I will take care of it this week 😊 Sorry for not seeing earlier!

**Comment by ainame** [comment]
That's great!! Thank you very much🙇

**Comment by chwo** [comment]
@joshdholtz Are there any updates on this?

**Comment by jhandguy** [comment]
I also need this, anything I can do to help?
