### ISSUE TITLE
upload_to_play_store failing with ssl_connect error

### ISSUE THREAD

**Issue by kchauhan1984** [fastlane/fastlane#15730]
Fastlane build is successful but upload_to_play_store is failing with below error.

```
INFO [2019-11-25 07:53:19.81]: [32mSuccessfully generated documentation at path '/tmp/workspace/android_play_store_build_new/fastlane/README.md'[0m

+------+----------------------+-------------+
|             [32mfastlane summary[0m              |
+------+----------------------+-------------+
| Step | Action               | Time (in s) |
+------+----------------------+-------------+
| 1    | default_platform     | 0           |
| 2    | gradle               | 116         |
| 3    | gradle               | 143         |
| 4    | gradle               | 120         |
| 💥   | [31mupload_to_play_store[0m | 0           |
+------+----------------------+-------------+

ERROR [2019-11-25 07:53:19.81]: [31mfastlane finished with errors[0m
ERROR [2019-11-25 07:53:19.81]: [31m-----------------------------------------------------------------------[0m
ERROR [2019-11-25 07:53:19.81]: [31mSSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate in certificate chain)[0m

**Comment by kchauhan1984** [comment]
here is fastlane environment.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                        |
| --------------------------- | ------------------------------------------------------------ |
| OS                          | debian_based stretch/sid                                     |
| Ruby                        | 2.5.5                                                        |
| Bundler?                    | false                                                        |
| Git                         | git version 2.7.4                                            |
| Installation Source         | /usr/local/bin/fastlane                                      |
| Host                        | Ubuntu 16.04.6 LTS debian_based stretch/sid (4.4.0-1096-aws) |
| Ruby Lib Dir                | /usr/lib                                                     |
| OpenSSL Version             | OpenSSL 1.1.1c  28 May 2019                                  |
| Is contained                | false                                                        |
| Is homebrew                 | false                                                        |
| Is installed via Fabric.app | false                                                        |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.134.0 | 🚫 Update available |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.1        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.1        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.13.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.68.0       |
| faraday                   | 0.17.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.0.2        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.1009  |
| mime-types                | 3.3          |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.4.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| stringio                  | 0.0.1        |
| openssl                   | 2.1.2        |
| strscan                   | 1.0.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| etc                       | 1.0.0        |
| io-console                | 0.4.6        |
| zlib                      | 1.0.0        |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
</details>


*generated on:* **2019-11-27**
</details>
[21:11:57]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[21:11:57]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅

#######################################################################
# fastlane 2.137.0 is available. You are on 2.134.0.
# You should use the latest version.
# Please update using `sudo gem install fastlane`.
#######################################################################

**Comment by janpio** [comment]
>  ERROR [2019-11-25 07:53:19.81]: �[31mSSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate in certificate chain)�[0m

Is there a proxy in the chain that tries to inject its own self signed certificate? Corporate environment maybe?

**Comment by kchauhan1984** [comment]
yes its via corporate proxy

**Comment by janpio** [comment]
Then you will have to fix that, because this breaks the SSL connection.
