### ISSUE TITLE
[Scan] - Add support for disabling "KeyboardContinuousPathEnabled"

### ISSUE THREAD

**Issue by AlexTrott** [fastlane/fastlane#15742]
### Feature Request
Add a new config option for Scan which allows for test to run with "Slide to type" disabled.

#### Motivation Behind Feature

With the release of iOS 13, newly recreated/reset simulators all have "Slide to type" enabled by default.
This new functionality now causes an issue when executing XCUITest via `scan` which interact with textfields. As they will see the following screen when interacting with the UITextField for the first time.

<img width="559" alt="Screen Shot 2019-11-30 at 4 42 32 PM" src="https://user-images.githubusercontent.com/595623/69903404-853ff100-1390-11ea-96d8-0f9b546d7627.png">

This will then cause the XCUITest to fail, due to the inability to interact with the keyboard.

#### Feature Description

Offer developers the ability to disable slide to type when using scan, this would look something like this in the fastfile
```
  scan(
    reset_simulator: true,
    disable_slide_to_type: true
  )
```

Which I think would then require an update in scan's runner.rb, which would be something like this (Copied reset_simulators)
```
      if Scan.config[:disable_slide_to_type]
        Scan.devices.each do |device|
          FastlaneCore::Simulator.disable_slide_to_type(udid: device.udid)
        end
      end
```

Which would then require a final change in fastlane_core/device_manager.rb which would do the following:

```
def disable_slide_to_type(uuid)
    # go to the simulator preferences 
    ## /Users/{USERNAME}/Library/Developer/CoreSimulator/Devices/{UUID}/data/Library/Preferences 
   
   # Create a new file called: com.apple.keyboard.ContinuousPath.plist

   # Add the following:
   ## Key: KeyboardContinuousPathEnabled
   ## Type: Boolean
   ## Value: NO
end
```

Example plist file:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>KeyboardContinuousPathEnabled</key>
	<false/>
</dict>
</plist>
```

Which will then execute the test on the newly refreshed simulator with slide to type disabled.

##### Workaround:
The only work around I know, is to reset the simulator before executing scan, and then finding the simulator UUID and manually doing this.

##### Plugins:
I have not found any plugins which do this.

**Comment by janpio** [comment]
Should we maybe do the opposite - by default go back to the old behavior of _not_ having this, but then having an option to enable it again?

**Comment by AlexTrott** [comment]
Yeah, I feel like that makes more sense. 
I’m happy with either way though, as long as the option exist in some form.

**Comment by AlexTrott** [comment]
@janpio I've raised a PR which should resolve this issue
