### ISSUE TITLE
'<module:Faraday>': superclass mismatch for class ConnectionFailed (TypeError)

### ISSUE THREAD

**Issue by phil-Juwelo** [fastlane/fastlane#15740]
Hi,
i have installed MacOS catalina and yesterday i had problems using fastlane, and i got it working.
Today i restarted my Macbook and i got this error while executing fastlane env:

> /Users/phil/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday-0.17.1/lib/faraday/error.rb:95:in `<module:Faraday>': superclass mismatch for class ConnectionFailed (TypeError)

I reinstalled fastlane deleted all gems but i still get this error message.
is there a way to install an old version of fastlane or better to fix this error?

thanks.
phil

**Comment by jongha** [comment]
In this case, ```fastlane env``` also gives the same error.

**Comment by alexanderwanyoike** [comment]
Getting the same error with both `fastlane init` and `fastlane env`

**Comment by juancruzgs** [comment]
I got the same error after installing it via HomeBrew:
```
brew cask install fastlane
```

To fix it I had uninstall and installed it again via RubyGems:
```
brew cask uninstall fastlane
sudo gem install fastlane -NV
```

**Comment by v-mitim** [comment]
Same for me.
As a temporary workaround after installing fastlane via `gem install`:
```
rm -rf $HOME/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday-0.*
rm -rf $HOME/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/specifications/faraday-0.*
gem install faraday -v 0.17.0 --install-dir $HOME/.fastlane/bin/bundle/lib/ruby/gems/2.2.0
```

**Comment by phil-Juwelo** [comment]
hi,
the solution from @miketimofeev works fine for me, now i just got some configuration issues, but fastlane is working again :)

**Comment by miketimofeev** [comment]
@phil-Juwelo I'd prefer to leave this issue open because it's just a temporary solution

**Comment by 5SMNOONMS5** [comment]
same problem here!

**Comment by sergsadovyi** [comment]
Solution of @miketimofeev worked for me after `brew cast install fastlane`

```
rm -rf $HOME/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday-0.*
rm -rf $HOME/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/specifications/faraday-0.*
gem install faraday -v 0.17.0 --install-dir $HOME/.fastlane/bin/bundle/lib/ruby/gems/2.2.0
```

**Comment by xiaofengzs** [comment]
Perfectly solved this problem

**Comment by janoist1** [comment]
Worked for me too! 🎉

**Comment by kcw-grunt** [comment]
> Solution of @miketimofeev worked for me after `brew cask install fastlane`
> 
> ```
> rm -rf $HOME/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday-0.*
> rm -rf $HOME/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/specifications/faraday-0.*
> gem install faraday -v 0.17.0 --install-dir $HOME/.fastlane/bin/bundle/lib/ruby/gems/2.2.0
> ```

Hot damn
