### ISSUE TITLE
Cannot find changelog because no version code given - please specify :version_code 

### ISSUE THREAD

**Issue by bharatbiswal** [fastlane/fastlane#15745]
```
  desc "Deploy a new version to the Google Play"
  lane :deploy do | options |
    supply(
        track: 'production',
        package_name: options[:package_name],
        skip_upload_metadata: true,
        skip_upload_images: true,
        skip_upload_screenshots: true
    )
    upload_to_play_store
```

after updating fast lane to  2.137.0
I m getting the error " Cannot find changelog because no version code given - please specify :version_code "

so I added version_code: 107 to my supply .
but still I am getting the same error

**Comment by bharatbiswal** [comment]
I m new to this environment .
I m using Circel CI as the release tool.

Can you please guide me to get the  fastlane env  out put

**Comment by janpio** [comment]
Execute `fastlane env` via the Circle config and copy/paste the output here.

**Comment by shr3jn** [comment]
I'm facing the same issue

**Comment by tmtrademarked** [comment]
I'm facing a similar issue here when I use fastlane to promote from the alpha channel to the beta channel. This used to work fine before the recent updates to Supply to support the v3 developer API, which makes me suspect that something in that change isn't quite working as expected for that use case.

Here's an example of the `upload_to_play_store` I'm using for my configuration:
```
upload_to_play_store(
      package_name: "totally.real.package",
      track: "alpha",
      track_promote_to: "beta",
      deactivate_on_promote: false,
      metadata_path: "fastlane/release/",
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
    )
```

What Supply *used* to be able to do was find the version code from the APK/AAB currently in the source channel. It seems like something may have broken from there?

And for completeness, my `fastlane env`:
```
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                |
| --------------------------- | ------------------------------------ |
| OS                          | 10.14.6                              |
| Ruby                        | 2.6.1                                |
| Bundler?                    | true                                 |
| Git                         | git version 2.20.1 (Apple Git-117)   |
| Installation Source         | ~/.rbenv/versions/2.6.1/bin/fastlane |
| Host                        | Mac OS X 10.14.6 (18G1012)           |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.1/lib          |
| OpenSSL Version             | OpenSSL 1.1.0j  20 Nov 2018          |
| Is contained                | false                                |
| Is homebrew                 | false                                |
| Is installed via Fabric.app | false                                |
| Xcode Path                  | /Library/Developer/CommandLineTools/ |
| Xcode Version               |                                      |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

MANUALLY REDACTED

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "./keys/play_publish_key.json"

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.137.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 1.17.3       |
| etc                       | 1.0.1        |
| forwardable               | 1.2.0        |
| CFPropertyList            | 3.0.1        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.70.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.17.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.1       |
| multi_json                | 1.14.1       |
| os                        | 1.0.1        |
| signet                    | 0.12.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.1009  |
| mime-types                | 3.3          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.4.1        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.13.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>


*generated on:* **2019-12-04**
</details>
```

**Comment by tmtrademarked** [comment]
It turns out I just missed the memo in the documentation - there's a new option called `skip_upload_changelogs`. If you don't specify this, it defaults to false, which means supply will try to upload your changelogs - which obviously needs a version code specified. I bet if I set that to false, my build will go back to working.

I'll give that a try and report back on the thread.

**Comment by edmundojr** [comment]
@tmtrademarked passing `skip_upload_changelogs` on `promote_alpha_to_beta` and `promote_beta_to_production` worked for me, thanks!

**Comment by bharatbiswal** [comment]
I am still getting the same error
Below is my supply in fast file.

supply(
        track: 'production',
        package_name: "com.xxxxx.xxxxx",
        skip_upload_metadata: true,
        skip_upload_images: true,
        skip_upload_changelogs: true,
        version_code: 119,
        version_name: "1.0.1-20191218-4",
        apk: "/home/circleci/code/app/build/outputs/apk/awcc/release/app-xxxxx-release.apk"
    )

**Comment by b-yng** [comment]
In my case, I'm promoting from our internal track to production and want to include metadata for release notes. To fix the issue, I'm supplying the `version_code` argument. Here's what that lane looks like now:
``` ruby
  lane :promote_prod do |options|
    versions = google_play_track_version_codes(track: "internal")
    version_code = versions[0]
    
    upload_to_play_store(
      track: 'internal',
      track_promote_to: 'production',
      skip_upload_apk: true,
      skip_upload_metadata: false,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_aab: true,
      version_code: version_code
    )
  end
```
