### ISSUE TITLE
Error no provisioning profiles found

### ISSUE THREAD

**Issue by kohenkatz** [fastlane/fastlane#15750]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When using fastlane with `match` and `gym` to download certificates and provisioning profiles and build, `match` tells me that all certificates and profiles are in place and the `Detected provisioning profile mapping` is correct but `gym` fails with ` error: No profiles for 'com.example.myapptarget1.main' were found`. Additionally. even when running with `export_method: "app-store"`. the error message still refers to `iOS App Development provisioning profiles`.

This last worked with Xcode 10 and Fastlane 2.131.0 and is broken when using Xcode 11, but upgrading from Fastlane 2.131.0 to 2.137.0 does not fix the problem (despite the Xcode 11 fixes in 2.132.0.)

Things I have tried:

1. I tried using a separate keychain instead of the default so that I could isolate whether the certificates were there properly or not, based on the code for creating a keychain on some of the CI platforms. It did not make a difference. (NOTE: I am simulating running this on GitLab CI because that is where I want it to run, so I set variables to cause `is_ci?` to be `true` even though I'm actually running from the command line.)
1. I tried adding `exportOptions.provisioningProfiles` to the `build_app` command, but the provisioning profile names I am giving are the same as the names that `match` already provided, and I got the same errors.
1. I tried adding options such as `generate_apple_certs: true` for Xcode 11 even though the defaults for these are supposed to be what I need.
1. I tried running `bundle exec fastlane match --generate_apple_certs` on another Mac to see if it would generate anything new, but that didn't help either.
1. I tried forcing creation of new-Xcode-11-style "Apple" certs by running `bundle exec fastlane nuke development` to clear out all development certs followed by the command above, and that also did not help.

##### Command executed

For development build:

```
bundle exec fastlane build --env=myapptarget1
```

For App Store build:

```
bundle exec fastlane build --env=myapptarget1 release:"true"
```

##### Complete output when running fastlane, including the stack trace and command used

For App Store build:

<details>
  <pre>
My-iMac:callerios64 myuser$ bundle exec fastlane build --env=myapptarget1 release:"true"
[✔] 🚀
[01:23:09]: ------------------------------
[01:23:09]: --- Step: default_platform ---
[01:23:09]: ------------------------------
[01:23:09]: Loading from './fastlane//../.env.myapptarget1'
[01:23:09]: Driving the lane 'ios build' 🚀
[01:23:09]: ----------------------------------
[01:23:09]: --- Step: ensure_xcode_version ---
[01:23:09]: ----------------------------------
[01:23:09]: $ xcversion selected
[01:23:11]: ▸ Xcode 11.2.1
[01:23:11]: ▸ Build version 11B500
[01:23:11]: Selected Xcode version is correct: 11.2.1
[01:23:11]: -------------------
[01:23:11]: --- Step: is_ci ---
[01:23:11]: -------------------
[01:23:11]: ------------------------------------------------------
[01:23:11]: --- Step: Switch to ios setup_keychain_for_ci lane ---
[01:23:11]: ------------------------------------------------------
[01:23:11]: Cruising over to lane 'ios setup_keychain_for_ci' 🚖
[01:23:11]: Creating temporary keychain: "fastlane_tmp_keychain".
[01:23:11]: -----------------------------
[01:23:11]: --- Step: create_keychain ---
[01:23:11]: -----------------------------
[01:23:11]: Found keychain '~/Library/Keychains/fastlane_tmp_keychain', creation skipped
[01:23:11]: If creating a new Keychain DB is required please set the `require_create` option true to cause the action to fail
[01:23:12]: $ security list-keychains -d user
[01:23:12]: ▸ "/Users/myuser/Library/Keychains/fastlane_tmp_keychain-db"
[01:23:12]: Found keychain '/Users/myuser/Library/Keychains/fastlane_tmp_keychain-db' in list-keychains, adding to search list skipped
[01:23:12]: Running Match to fetch certificates and provisioning profiles
[01:23:12]: -------------------------------
[01:23:12]: --- Step: sync_code_signing ---
[01:23:12]: -------------------------------
[01:23:12]: Successfully loaded '/Users/myuser/builds/RYKRgMRp/0/myorg/myapp/fastlane/Matchfile' 📄

+----------------+--------------------------------------------------------------------+
|                          Detected Values from './fastlane/Matchfile'                |
+----------------+--------------------------------------------------------------------+
| git_url        | git@myserver.example.com:myorg/keystore.git                        |
| type           | development                                                        |
| app_identifier | ["com.example.myapptarget1.main", "com.example.myapptarget2.main"] |
| username       | build-server-user@example.com                                      |
+----------------+--------------------------------------------------------------------+

+----------------------------+------------------------------------------------------------------------------+
|                                         Summary for match 2.137.0                                         |
+----------------------------+------------------------------------------------------------------------------+
| type                       | appstore                                                                     |
| keychain_name              | fastlane_tmp_keychain                                                        |
| keychain_password          | ********                                                                     |
| generate_apple_certs       | true                                                                         |
| readonly                   | false                                                                        |
| skip_provisioning_profiles | false                                                                        |
| app_identifier             | ["com.example.myapptarget1.main", "com.example.myapptarget2.main"]           |
| username                   | build-server-user@example.com                                                |
| storage_mode               | git                                                                          |
| git_url                    | git@myserver.example.com:myorg/keystore.git                                  |
| git_branch                 | master                                                                       |
| shallow_clone              | false                                                                        |
| clone_branch_directly      | false                                                                        |
| force                      | false                                                                        |
| force_for_new_devices      | false                                                                        |
| skip_confirmation          | false                                                                        |
| skip_docs                  | false                                                                        |
| platform                   | ios                                                                          |
| verbose                    | false                                                                        |
+----------------------------+------------------------------------------------------------------------------+

[01:23:12]: Cloning remote git repo...
[01:23:12]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[01:23:13]: 🔓  Successfully decrypted certificates repo
[01:23:13]: Verifying that the certificate and profile are still valid on the Dev Portal...
[01:23:14]: Installing certificate...

+-------------------+-----------------------------------------------------+
|                          Installed Certificate                          |
+-------------------+-----------------------------------------------------+
| User ID           | **********                                          |
| Common Name       | iPhone Distribution: MyCompany LLC (**********)     |
| Organisation Unit | **********                                          |
| Organisation      | MyCompany LLC                                       |
| Country           | US                                                  |
| Start Datetime    | 2019-04-17 15:38:41 UTC                             |
| End Datetime      | 2020-04-16 15:38:41 UTC                             |
+-------------------+-----------------------------------------------------+

[01:23:15]: Installing provisioning profile...
[01:23:16]: Installing provisioning profile...

+---------------------+--------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------+
|                                                                                      Installed Provisioning Profile                                                                                       |
+---------------------+--------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------+
| Parameter           | Environment Variable                                         | Value                                                                                                                |
+---------------------+--------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------+
| App Identifier      |                                                              | com.example.myapptarget1.main                                                                                        |
| Type                |                                                              | appstore                                                                                                             |
| Platform            |                                                              | ios                                                                                                                  |
| Profile UUID        | sigh_com.example.myapptarget1.main_appstore                  | 00193571-1e4a-45af-af39-170866da2179                                                                                 |
| Profile Name        | sigh_com.example.myapptarget1.main_appstore_profile-name     | match AppStore com.example.myapptarget1.main                                                                         |
| Profile Path        | sigh_com.example.myapptarget1.main_appstore_profile-path     | /Users/myuser/Library/MobileDevice/Provisioning Profiles/00193571-1e4a-45af-af39-170866da2179.mobileprovision        |
| Development Team ID | sigh_com.example.myapptarget1.main_appstore_team-id          | **********                                                                                                           |
+---------------------+--------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------+

+---------------------+----------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------+
|                                                                                       Installed Provisioning Profile                                                                                        |
+---------------------+----------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------+
| Parameter           | Environment Variable                                           | Value                                                                                                                |
+---------------------+----------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------+
| App Identifier      |                                                                | com.example.myapptarget2.main                                                                                        |
| Type                |                                                                | appstore                                                                                                             |
| Platform            |                                                                | ios                                                                                                                  |
| Profile UUID        | sigh_com.example.myapptarget2.main_appstore                    | d4c4bdf1-d0f1-4c34-a466-d9cb97b6327a                                                                                 |
| Profile Name        | sigh_com.example.myapptarget2.main_appstore_profile-name       | match AppStore com.example.myapptarget2.main                                                                         |
| Profile Path        | sigh_com.example.myapptarget2.main_appstore_profile-path       | /Users/myuser/Library/MobileDevice/Provisioning Profiles/d4c4bdf1-d0f1-4c34-a466-d9cb97b6327a.mobileprovision        |
| Development Team ID | sigh_com.example.myapptarget2.main_appstore_team-id            | **********                                                                                                           |
+---------------------+----------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------+

[01:23:17]: All required keys, certificates and provisioning profiles are installed 🙌
[01:23:17]: Setting Provisioning Profile type to 'app-store'
[01:23:17]: Enabling match readonly mode.
[01:23:17]: Cruising back to lane 'ios build' 🚘
[01:23:17]: ----------------------
[01:23:17]: --- Step: carthage ---
[01:23:17]: ----------------------
[01:23:17]: $ carthage bootstrap --platform all --cache-builds
[01:23:17]: ▸ *** Checking out Quick at "v2.2.0"
[01:23:17]: ▸ *** Checking out Nimble at "v8.0.4"
[01:23:17]: ▸ *** Checking out sentry-cocoa at "4.1.0"
[01:23:17]: ▸ *** Checking out libPhoneNumber-iOS at "0.9.15"
[01:23:19]: ▸ *** xcodebuild output can be found in /var/folders/xs/z9_s87_d2njcsfb38xmqpgz00000gn/T/carthage-xcodebuild.HT6vCK.log
[01:23:20]: ▸ *** Valid cache found for libPhoneNumber-iOS, skipping build
[01:23:20]: ▸ *** Valid cache found for Nimble, skipping build
[01:23:20]: ▸ *** Valid cache found for Quick, skipping build
[01:23:20]: ▸ *** Valid cache found for sentry-cocoa, skipping build
[01:23:27]: ▸ *** Valid cache found for WebRTC-bitcode, skipping build
[01:23:27]: -----------------------
[01:23:27]: --- Step: build_app ---
[01:23:27]: -----------------------
[01:23:27]: Successfully loaded '/Users/myuser/builds/RYKRgMRp/0/myorg/myapp/fastlane/Gymfile' 📄

+---------------------+---------------------+
| Detected Values from './fastlane/Gymfile' |
+---------------------+---------------------+
| output_directory    | ./build             |
+---------------------+---------------------+

[01:23:27]: $ xcodebuild -showBuildSettings -scheme myapptarget1-release -project ./myapp.xcodeproj
[01:23:30]: Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...
[01:23:35]: Detected provisioning profile mapping: {:"com.example.myapptarget1.main"=>"match AppStore com.example.myapptarget1.main", :"com.example.myapptarget2.main"=>"match AppStore com.example.myapptarget2.main"}

+-------------------------------------------------------------------------+------------------------------------------------------------------+
|                                                          Summary for gym 2.137.0                                                           |
+-------------------------------------------------------------------------+------------------------------------------------------------------+
| scheme                                                                  | myapptarget1-release                                             |
| clean                                                                   | true                                                             |
| output_directory                                                        | ./build                                                          |
| export_method                                                           | app-store                                                        |
| export_options.provisioningProfiles.com.example.myapptarget1.main   | match AppStore com.example.myapptarget1.main                         |
| export_options.provisioningProfiles.com.example.myapptarget2.main | match AppStore com.example.myapptarget2.main                           |
| export_options.signingStyle                                             | manual                                                           |
| project                                                                 | ./myapp.xcodeproj                                                |
| destination                                                             | generic/platform=iOS                                             |
| output_name                                                             | myapptarget1                                                       |
| build_path                                                              | /Users/myuser/Library/Developer/Xcode/Archives/2019-12-03        |
| silent                                                                  | false                                                            |
| skip_package_ipa                                                        | false                                                            |
| result_bundle                                                           | false                                                            |
| buildlog_path                                                           | ~/Library/Logs/gym                                               |
| skip_profile_detection                                                  | false                                                            |
| xcode_path                                                              | /Applications/Xcode.app                                          |
+-------------------------------------------------------------------------+------------------------------------------------------------------+

[01:23:35]: $ set -o pipefail && xcodebuild -scheme myapptarget1-release -project ./myapp.xcodeproj -destination 'generic/platform=iOS' -archivePath /Users/myuser/Library/Developer/Xcode/Archives/2019-12-03/myapptarget1\ 2019-12-03\ 01.23.35.xcarchive clean archive | tee /Users/myuser/Library/Logs/gym/myapptarget1-myapptarget1-release.log | xcpretty
[01:23:39]: ▸ Clean Succeeded
[01:23:40]: ▸ ❌  error: No profiles for 'com.example.myapptarget1.main' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.example.myapptarget1.main'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'myapptarget1' from project 'myapp')
[01:23:40]: ▸ ** ARCHIVE FAILED **
▸ Clean Succeeded

❌  error: No profiles for 'com.example.myapptarget1.main' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.example.myapptarget1.main'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'myapptarget1' from project 'myapp')

** ARCHIVE FAILED **
[01:23:40]: Exit status: 65

+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.137.0                 |
| export_method | app-store               |
| sdk           | iPhoneOS13.2.sdk        |
+---------------+-------------------------+

[01:23:40]: ▸ note: Using new build system
[01:23:40]: ▸ note: Planning build
[01:23:40]: ▸ note: Constructing build description
[01:23:40]: ▸ error: No profiles for 'com.example.myapptarget1.main' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.example.myapptarget1.main'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'myapptarget1' from project 'myapp')
[01:23:40]:
[01:23:40]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[01:23:40]: 📋  For the complete and more detailed error log, check the full log at:
[01:23:40]: 📋  /Users/myuser/Library/Logs/gym/myapptarget1-myapptarget1-release.log
[01:23:40]:
[01:23:40]: Looks like fastlane ran into a build/archive error with your project
[01:23:40]: It's hard to tell what's causing the error, so we wrote some guides on how
[01:23:40]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[01:23:40]: Before submitting an issue on GitHub, please follow the guide above and make
[01:23:40]: sure your project is set up correctly.
[01:23:40]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
[01:23:40]: the full commands printed out in yellow in the above log.
[01:23:40]: Make sure to inspect the output above, as usually you'll find more error information there
[01:23:40]:
+------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                        Lane Context                                                                                                         |
+------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM                   | ios                                                                                                                                                                                    |
| ENVIRONMENT                        | myapptarget1                                                                                                                                                                             |
| PLATFORM_NAME                      | ios                                                                                                                                                                                    |
| LANE_NAME                          | ios build                                                                                                                                                                              |
| ORIGINAL_DEFAULT_KEYCHAIN          | "/Users/myuser/Library/Keychains/fastlane_tmp_keychain-db"                                                                                                                      |
| SIGH_PROFILE_TYPE                  | app-store                                                                                                                                                                              |
| MATCH_PROVISIONING_PROFILE_MAPPING | {"com.example.myapptarget1.main"=>"match AppStore com.example.myapptarget1.main", "com.example.myapptarget2.main"=>"match AppStore com.example.myapptarget2.main"} |
+------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
[01:23:40]: Error building the application - see the log above

+------+------------------------------------------+-------------+
|                       fastlane summary                        |
+------+------------------------------------------+-------------+
| Step | Action                                   | Time (in s) |
+------+------------------------------------------+-------------+
| 1    | default_platform                         | 0           |
| 2    | ensure_xcode_version                     | 1           |
| 3    | is_ci                                    | 0           |
| 4    | Switch to ios setup_keychain_for_ci lane | 0           |
| 5    | create_keychain                          | 0           |
| 6    | sync_code_signing                        | 5           |
| 7    | carthage                                 | 10          |
| 💥   | build_app                                | 12          |
+------+------------------------------------------+-------------+

[01:23:40]: fastlane finished with errors
</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                                            |
| --------------------------- | -------------------------------------------------------------------------------- |
| OS                          | 10.14.4                                                                          |
| Ruby                        | 2.6.5                                                                            |
| Bundler?                    | true                                                                             |
| Git                         | git version 2.21.0 (Apple Git-122.2)                                             |
| Installation Source         | ~/builds/RYKRgMRp/0/myorg/myapp/vendor/bundle/ruby/2.6.0/bin/fastlane |
| Host                        | Mac OS X 10.14.4 (18E2034)                                                       |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.6.5/lib                                                 |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                                                      |
| Is contained                | false                                                                            |
| Is homebrew                 | false                                                                            |
| Is installed via Fabric.app | false                                                                            |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                                      |
| Xcode Version               | 11.2.1                                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools

default_platform(:ios)

platform :ios do

  desc "Set up Keychain for manual run"
  lane :setup_keychain do |options|
    UI.message("Running Match to fetch certificates and provisioning profiles")
    sync_code_signing(
      type: options.fetch(:signing_type, "appstore"), # fallback to appstore if not set
    )

    UI.message("Enabling match readonly mode.")
    ENV["MATCH_READONLY"] = true.to_s
  end

  desc "Set up Keychain for CI"
  private_lane :setup_keychain_for_ci do |options|
    unless ENV["MATCH_KEYCHAIN_NAME"].nil?
      UI.message("Skipping Keychain setup as a keychain was already specified")
      return
    end

    keychain_name = "fastlane_tmp_keychain"
    ENV["MATCH_KEYCHAIN_NAME"] = keychain_name
    ENV["MATCH_KEYCHAIN_PASSWORD"] = ENV['KEYCHAIN_PASSWORD']

    UI.message("Creating temporary keychain: \"#{keychain_name}\".")
    create_keychain(
      name: keychain_name,
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true,
      password: ENV['KEYCHAIN_PASSWORD'],
    )

    UI.message("Running Match to fetch certificates and provisioning profiles")
    sync_code_signing(
      type: options.fetch(:signing_type, "appstore"), # fallback to appstore if not set
      keychain_name: keychain_name,
      keychain_password: ENV['KEYCHAIN_PASSWORD'],
      generate_apple_certs: true,
    )

    UI.message("Enabling match readonly mode.")
    ENV["MATCH_READONLY"] = true.to_s
  end

  desc "Build"
  lane :build do |options|
    if options[:release] then
      # Make sure the working directory does not have uncommitted changes
      ensure_git_status_clean
    end

    # Make sure we are building with the XCode version specified in `.xcode-version`
    ensure_xcode_version

    signing_type = (options[:release] ? "appstore" : "development")
    # Make sure we have certs and provisioning profiles
    if is_ci?
      setup_keychain_for_ci(signing_type: signing_type)
    else
      setup_keychain(signing_type: signing_type)
    end

    # Make sure we have dependencies
    carthage(
      platform: 'ios',
      command: 'bootstrap',
      cache_builds: true,
    )

    # Build the app
    build_app(
      scheme: (options[:release] ? ENV['APP_SCHEME_APPSTORE'] : ENV['APP_SCHEME_DEVELOPMENT']),
      clean: true,
      output_directory: "./build",
      export_method: (options[:release] ? "app-store" : "development"),
    )
  end

  desc "Build both schemes"
  lane :build_all do
    setup_keychain(signing_type: "development")
    sh 'fastlane build --env=myapptarget1'
    sh 'fastlane build --env=myapptarget2'
  end

end


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier(ENV['APP_IDENTIFIER']) # Read from .env file
apple_id("build-server-user@example.com")

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.137.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 2.0.2        |
| CFPropertyList            | 3.0.1        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.70.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.17.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.1       |
| multi_json                | 1.14.1       |
| os                        | 1.0.1        |
| signet                    | 0.12.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.1009  |
| mime-types                | 3.3          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.4.1        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.13.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-sentry    | 1.5.0        |
| xcode-install             | 2.6.0        |
</details>

*generated on:* **2019-12-03**
</details>

**Comment by grifotv** [comment]
Looks like there are two new certificate types `Apple Development` and `Apple Distribution` instead of the former `iOS...` - you can see next to each the message "For use in Xcode 11 or later.":

![Screenshot 2019-12-04 at 12 37 24](https://user-images.githubusercontent.com/435351/70143284-106ffe00-1693-11ea-9b6f-45ed24cdba19.png)

I'm wondering if you have created certificates for `Apple Development` / `Apple Distribution` or `iOS App Development` / `iOS Distribution`.

I guess my main question is if `match` can manage `Apple Development` / `Apple Distribution` certificates. Does anyone know?

Potentially related:
- https://stackoverflow.com/questions/56953216/xcode-11-beta-unable-to-install-app-on-device-ending-with-certificate-issue/58145207#58145207
- https://stackoverflow.com/questions/58662457/xcode-11-2-unable-to-install-app-file-to-device
- https://forums.developer.apple.com/thread/125466

**Comment by kohenkatz** [comment]
@grifotv I thought that is what `generate_apple_certs: true` is supposed to do, which I already mentioned that I tried. I wonder if it is not properly using that option. I will have to test that more.

**Comment by kohenkatz** [comment]
So it turns out that `match` will properly generate the new type of certificates *only* if you nuke the old type first. You cannot have both the old type and new type at the same time in the match repository.

However, that doesn't solve my problem.

Looking at the logs (posted above) again, I see something weird: `gym` is correctly providing the `AppStore` provisioning profiles, but the `xcodebuild` error is complaining that it cannot find `iOS App Development` profiles. I wonder why it is trying to find a development profile for a production build...

**Comment by kohenkatz** [comment]
I found https://github.com/fastlane/fastlane/issues/12849#issuecomment-404978983 which gave me the clue I needed.

Here is what the `build` lane of my `fastfile` now looks like:

```ruby
  desc "Build"
  lane :build do |options|
    if options[:release] then
      # Make sure the working directory does not have uncommitted changes
      ensure_git_status_clean
    end

    # Make sure we are building with the XCode version specified in `.xcode-version`
    ensure_xcode_version

    signing_type = (options[:release] ? "appstore" : "development")
    # Make sure we have certs and provisioning profiles
    if is_ci?
      # If running on CI, uses a separate keychain
      setup_keychain_for_ci(signing_type: signing_type)
    else
      # If running on a user's machine, uses the default keychain
      setup_keychain(signing_type: signing_type)
    end

    # Make sure we have dependencies
    carthage(
      platform: 'ios',
      command: 'bootstrap',
      cache_builds: true,
    )

    disable_automatic_code_signing(path: "myapp.xcodeproj")

    # Build the app
    build_app(
      scheme: (options[:release] ? ENV['APP_SCHEME_APPSTORE'] : ENV['APP_SCHEME_DEVELOPMENT']),
      clean: true,
      output_directory: "./build",
      export_method: (options[:release] ? "app-store" : "development"),
      xcargs: {
        PROVISIONING_PROFILE_SPECIFIER: ENV["sigh_#{ENV['APP_IDENTIFIER']}_#{signing_type}"]
      }
    )

    enable_automatic_code_signing(path: "myapp.xcodeproj")

  end
```

The most important change is `xcargs.PROVISIONING_PROFILE_SPECIFIER`, which uses the app identifier (loaded from `.env` since I have multiple targets). The reason `disable_automatic_code_signing` is needed is because otherwise Xcode complains that you can't have it enabled and also specify a profile.

I still don't understand why it isn't picking the correct one automatically though, and I suspect that may be a bug.
