### ISSUE TITLE
I want to build testflight group 

### ISSUE THREAD

**Issue by chhsh122** [fastlane/fastlane#15753]
I want to build testflight group  . I use Fastlane deliver but I found  apple had changed api . so I use spaceship such as Spaceship::TestFlight::Group.new and Spaceship::ConnectAPI::BetaAppLocalization.new  and Spaceship::ConnectAPI::BetaGroup.new .its all  failed

**Comment by max-ott** [comment]
Not sure where you got those "commands", but they do not really look that they should work. You might want to checkout the respective `spaceship` files: https://github.com/fastlane/fastlane/tree/master/spaceship/lib/spaceship/test_flight
