### ISSUE TITLE
Can I leave the bundel id unchanged?

### ISSUE THREAD

**Issue by MiaoMiaoai** [fastlane/fastlane#15754]
### Question Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

#### Question Description

I don't want to change the bundel id，Can you do that？

**Comment by max-ott** [comment]
Hi @MiaoMiaoai I'm not sure how your issue is related to `fastlane`. Could you please provide some more context?

**Comment by MiaoMiaoai** [comment]
@max-ott   When I use: fastlane sigh resign /Users/hanshaobo/Desktop/text/xxx.ipa --signing_identity "iPhone Distribution: xxx" -p "xxxx.mobileprovision".
This will change the bundel id of the IPA, but I don't want to change it.

**Comment by philCc** [comment]
@MiaoMiaoai You need to check what is [App ID] in your xxxx.mobileprovision
If you do not want to change the bundle ID, you need to keep both bundle IDs the same
