### ISSUE TITLE
App Analytics Impressions got via Spaceship doesn't match with AppStoreConnect Data

### ISSUE THREAD

**Issue by syedsmith** [fastlane/fastlane#15765]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Command executed
lane :appAnalytics do
  puts "appAnalytics"
  Spaceship::Tunes.login(ENV[‘fastlane_username’],ENV[‘fastlane_password’])
  #appAnalytics = Spaceship::Tunes::AppAnalytics.new(apple_id: ENV[‘apple_id’] )
  app = Spaceship::Tunes::Application.find(ENV[‘apple_id’]) 
  analytics = app.analytics 
  appAnalytics = {  'units' => analytics.app_units ,
                     'view' => analytics.app_views ,
                      'impressions' => analytics. app_impressions,
                       'sales' => analytics.app_sales. ,
                        'iap' => analytics.app_in_app_purchases ,
                         'installs' => analytics. app_installs,
                          'sessions' => analytics. app_sessions,
                           'activeDevices' => analytics.app_active_devices ,
                            'crashes' => analytics.app_crashes  }

  puts appAnalytics
end

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by max-ott** [comment]
@syedsmith Please provide more information about the issue, because otherwise we will not be able to help you. Most of those issues are related to the timezones.

**Comment by syedsmith** [comment]
@max-ott Code executed is provided above, impressions count for one my app on November 26 was around 5452 in AppStore Connect but spaceship returned me as 10658.
The same mismatch also occurred on November 22 with AppStore connect impression count as 5794 and spaceship impression count as  11588.

And It would be better, if we can mention custom date range via spaceship

**Comment by max-ott** [comment]
You can change the range etc. directly in `spaceship`. Please check out the source code for that. As we get the numbers directly from Apple, I'm pretty sure the numbers are not wrong, but it's a simple issue with comparing different sets.
