### ISSUE TITLE
Spaceship: can we list/insert/update/delete inapp products/subscriptions?

### ISSUE THREAD

**Issue by anthony3444** [fastlane/fastlane#15767]
Hi guys!

My question is really simple. Is it possible with Spaceship to list all the inapp products + subscriptions from our App? Is it possible to add/delete/update too?

Thank you very much guys!

**Comment by max-ott** [comment]
Hi @anthony3444 some parts are available, but you have to go through the code / pull requests. https://github.com/fastlane/fastlane/pull/7834 is a pretty good starting point.
