### ISSUE TITLE
Testflight separate upload and actual distribution

### ISSUE THREAD

**Issue by YannickBiet** [fastlane/fastlane#15762]
#### Motivation Behind Feature
Currently if we want to distribute an artifact via testflight we must use the upload_to_testflight action, waiting for build processing, setting the changelog + set the testers groups

Build processing is taking up to hours now, and this is stucking our CI/CD to send on the fly the builds for QA.

#### Feature Description
My idea is to separate the lane that actually build and upload to testflight and would trigger another CI job that would just check/wait for build processing before setting changelog and actually distribute the build to testers

If there's an existing workaround i would be glad to discuss about it !

**Comment by max-ott** [comment]
You might want to look into https://github.com/fastlane/watchbuild and build your custom lane/action.

**Comment by YannickBiet** [comment]
ok i will check it. thanks for the report of existing :)
