### ISSUE TITLE
Unable to Reply to Resolution Center For BETA REVIEW(betaNotes) via Spaceship reply_resolution_center, Please check on this

### ISSUE THREAD

**Issue by syedsmith** [fastlane/fastlane#15763]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by max-ott** [comment]
This is working as intended. The method currently does not provide access to reply to beta review.
