### ISSUE TITLE
TestFlight Feedback Automation

### ISSUE THREAD

**Issue by mattbischoff** [fastlane/fastlane#15771]
#### Motivation Behind Feature
As [TestFlight has added the ability to receive annotated feedback](https://developer.apple.com/app-store-connect/whats-new/?id=testerfeedback) from testers, it would be nice to be able to access and automate those from within TestFlight.

What I’d like to see ideally is a way for me to tell fastlane to grab the latest pieces of Feedback from TestFlight and send them to my issue tracker of choice. Say GitHub Issues.

See also this twitter thread: https://twitter.com/joshdholtz/status/1202022122501083136?s=21

#### Feature Description

Since I’m not super familiar with the APIs involved and how this would be implemented, I’d like to leave the specifics up to folks with more knowledge than me.

There shouldn’t be any drawbacks for existing users as this is a brand new feature.

#### Alternatives or Workarounds
 
Currently I’m doing this manually.

**Comment by max-ott** [comment]
Check out https://github.com/fastlane/fastlane/pull/15793 for screenshot support.

**Comment by tbodt** [comment]
Since it wasn't super clear the first time I read this issue: basic support for this was added in #15793.
