### ISSUE TITLE
[screengrab] What is a contribution guide?

### ISSUE THREAD

**Issue by plastiv** [fastlane/fastlane#15776]
### Question Checklist

- [x] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Capturing screenshots on android with screengrab v2.0 doesn't work and I can contribute a fix. What do you use to health check changes at screengrab subproject?

#### Question Description
I have checkout sources and running 

```
cd screengrab/example
fastlane screengrab
```

results in errors. It looks like long abandoned, unless I'm missing something. There is no contrib README for this project. Is there a CI? What should I run locally to verify the setup and changes before contributing to it. Thanks in advance. 

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                |
| --------------------------- | ------------------------------------ |
| OS                          | 10.14.6                              |
| Ruby                        | 2.6.5                                |
| Bundler?                    | false                                |
| Git                         | git version 2.24.0                   |
| Installation Source         | ~/.rbenv/versions/2.6.5/bin/fastlane |
| Host                        | Mac OS X 10.14.6 (18G95)             |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.5/lib          |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019          |
| Is contained                | false                                |
| Is homebrew                 | false                                |
| Is installed via Fabric.app | false                                |
| Xcode Path                  | /Library/Developer/CommandLineTools/ |
| Xcode Version               |                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version("1.46.1")

default_platform(:android)

platform(:android) do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc("Runs all the tests")
  lane(:test) do
    gradle(task: "test")
  end

  desc("Submit a new Beta Build to Crashlytics Beta")
  lane(:beta) do
    gradle(task: "assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc("Deploy a new version to the Google Play")
  lane(:deploy) do
    gradle(task: "assembleRelease")
    supply
  end

  desc("Assemble the debug app and tests APKs")
  lane(:assemble) do
    gradle(task: "assemble assembleAndroidTest", gradle_path: '../gradlew')
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
package_name "tools.fastlane.localetester"

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.137.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                      | Version | Update-Status |
| --------------------------- | ------- | ------------- |
| fastlane-plugin-ruby        | 0.1.3   | ✅ Up-To-Date  |
| fastlane-plugin-clubmate    | 0.1.0   | ✅ Up-To-Date  |
| fastlane-plugin-slack_train | 0.2.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                         | Version      |
| --------------------------- | ------------ |
| did_you_mean                | 1.3.0        |
| slack-notifier              | 2.3.2        |
| atomos                      | 0.1.3        |
| CFPropertyList              | 3.0.2        |
| claide                      | 1.0.3        |
| colored2                    | 3.1.2        |
| nanaimo                     | 0.2.6        |
| xcodeproj                   | 1.13.0       |
| rouge                       | 2.0.7        |
| xcpretty                    | 0.3.0        |
| terminal-notifier           | 2.0.0        |
| unicode-display_width       | 1.6.0        |
| terminal-table              | 1.8.0        |
| plist                       | 3.5.0        |
| public_suffix               | 2.0.5        |
| addressable                 | 2.7.0        |
| multipart-post              | 2.0.0        |
| word_wrap                   | 1.0.0        |
| tty-screen                  | 0.7.0        |
| tty-cursor                  | 0.7.0        |
| tty-spinner                 | 0.9.1        |
| babosa                      | 1.0.3        |
| colored                     | 1.2          |
| highline                    | 1.7.10       |
| commander-fastlane          | 4.4.6        |
| excon                       | 0.70.0       |
| faraday                     | 0.17.1       |
| unf_ext                     | 0.0.7.6      |
| unf                         | 0.1.4        |
| domain_name                 | 0.5.20190701 |
| http-cookie                 | 1.0.3        |
| faraday-cookie_jar          | 0.0.6        |
| faraday_middleware          | 0.13.1       |
| fastimage                   | 2.1.7        |
| gh_inspector                | 1.1.3        |
| json                        | 2.1.0        |
| mini_magick                 | 4.9.5        |
| multi_xml                   | 0.6.0        |
| rubyzip                     | 1.3.0        |
| security                    | 0.1.3        |
| xcpretty-travis-formatter   | 1.0.0        |
| dotenv                      | 2.7.5        |
| bundler                     | 1.17.2       |
| naturally                   | 2.2.0        |
| simctl                      | 1.6.6        |
| jwt                         | 2.1.0        |
| uber                        | 0.1.0        |
| declarative                 | 0.0.10       |
| declarative-option          | 0.1.0        |
| representable               | 3.0.4        |
| retriable                   | 3.1.2        |
| mime-types-data             | 3.2019.1009  |
| mime-types                  | 3.3          |
| multi_json                  | 1.14.1       |
| signet                      | 0.12.0       |
| memoist                     | 0.16.2       |
| os                          | 1.0.1        |
| googleauth                  | 0.6.7        |
| httpclient                  | 2.8.3        |
| google-api-client           | 0.23.9       |
| google-cloud-env            | 1.3.0        |
| google-cloud-core           | 1.4.1        |
| digest-crc                  | 0.4.1        |
| google-cloud-storage        | 1.16.0       |
| emoji_regex                 | 1.0.1        |
| forwardable                 | 1.2.0        |
| logger                      | 1.3.0        |
| stringio                    | 0.0.2        |
| ipaddr                      | 1.2.2        |
| openssl                     | 2.1.2        |
| ostruct                     | 0.1.0        |
| strscan                     | 1.0.0        |
| date                        | 2.0.0        |
| fileutils                   | 1.1.0        |
| etc                         | 1.0.1        |
| io-console                  | 0.4.7        |
| zlib                        | 1.0.0        |
| rexml                       | 3.1.9        |
| psych                       | 3.1.0        |
| mutex_m                     | 0.1.0        |
| fastlane-plugin-ruby        | 0.1.3        |
| fastlane-plugin-clubmate    | 0.1.0        |
| fastlane-plugin-slack_train | 0.2.0        |
</details>

*generated on:* **2019-12-07**
</details>

**Comment by janpio** [comment]
The individual subprojects have no own contribution guides or CI, everything is done from the top level. So whatever is broken in the subfolders can or should be fixed. As the general CI is green right now, we either might be missing some failures or tests in the CI, or something is differnet on your environment.

**Comment by plastiv** [comment]
I think CI is currently lacking as it executes ruby code only and skips android companion library and sample project compilation, execution and running tests. 

Was it on purpose that CI pipeline doesn't have android environment (java, android sdk, android emulator)? Would you be willing to accept work on adding them?

**Comment by janpio** [comment]
No, that was probably not on purpose - if this helps to increase the overall quality of fastlane we of course would love to accept any contributions or changes there!

**Comment by plastiv** [comment]
Thank you for your time to read and respond 👍 I got my answer there is nothing more to keep this issue open.
