### ISSUE TITLE
Google Api Error: releasesTooManyCompletedReleases when rolling out to 100% of production with retained APKs

### ISSUE THREAD

**Issue by Plastix** [fastlane/fastlane#15772]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Supply is returning a Google Play API error when trying to rollout our staged release to 100% of production. We also have quite a few retained APKs which are part of each release which may be related.

##### Command executed

`fastlane rollout`

The relevant part of our Ruby Fastfile is as follows:
```Ruby
    lane :rollout do |options|
      supply_options = {
        package_name: APPLICATION_ID
        json_key: key_file,
        track: 'production',
        version_code: version_code,
        rollout: 1,
        skip_upload_apk: true,
        skip_upload_aab: true,
        metadata_path: METADATA_PATH
      }

      supply(supply_options)
    end
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[07:47:39]: Sending anonymous analytics information
[07:47:39]: Learn more at https://docs.fastlane.tools/#metrics
[07:47:39]: No personal or sensitive data is sent.
[07:47:39]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
[07:47:39]: ---------------------------
[07:47:39]: --- Step: opt_out_usage ---
[07:47:39]: ---------------------------
[07:47:39]: Disabled upload of used actions
[07:47:39]: ------------------------------
[07:47:39]: --- Step: default_platform ---
[07:47:39]: ------------------------------
[07:47:39]: Driving the lane 'android rollout' 🚀
[07:47:39]: ---------------------------------------------
[07:47:39]: --- Step: google_play_track_version_codes ---
[07:47:39]: ---------------------------------------------
[07:47:41]: Found '673, 73701, 362400, 383300, 682100, 1211063, 673, 73701, 362400, 383300, 682100, 1210962' version codes in track 'production'
[07:47:41]: Verified version code is included in 'production' track.
[07:47:41]: --------------------
[07:47:41]: --- Step: supply ---
[07:47:41]: --------------------

+-------------------------+--------------------------------+
|                Summary for supply 2.137.0                |
+-------------------------+--------------------------------+
| package_name            | com.myapp                      |
| json_key                | /usr/src/app/key.json          |
| track                   | production                     |
| version_code            | 1211063                        |
| rollout                 | 1.0                            |
| skip_upload_apk         | true                           |
| skip_upload_aab         | true                           |
| metadata_path           | /usr/src/app/fastlane/metadata |
| release_status          | completed                      |
| skip_upload_metadata    | false                          |
| skip_upload_changelogs  | false                          |
| skip_upload_images      | false                          |
| skip_upload_screenshots | false                          |
| validate_only           | false                          |
| check_superseded_tracks | false                          |
| timeout                 | 300                            |
| deactivate_on_promote   | true                           |
+-------------------------+--------------------------------+

[07:47:43]: Updating 673's rollout to '1.0' on track 'production'...
+------------------+-----------------+
|            Lane Context            |
+------------------+-----------------+
| DEFAULT_PLATFORM | android         |
| PLATFORM_NAME    | android         |
| LANE_NAME        | android rollout |
+------------------+-----------------+
[07:47:43]: Google Api Error: releasesTooManyCompletedReleases: Too many completed releases specified. - Too many completed releases specified.

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | opt_out_usage          | 0           |
| 2    | default_platform       | 0           |
| 3    | google_play_track_ver  | 2           |
|      | sion_codes             |             |
| 💥   | supply                 | 1           |
+------+------------------------+-------------+

[07:47:43]: fastlane finished with errors

[!] Google Api Error: releasesTooManyCompletedReleases: Too many completed releases specified. - Too many completed releases specified.
[07:47:43]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables</pre>
</details>

### Environment

<details>
<pre>
[✔] 🚀 
[23:09:52]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[23:09:52]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
[23:09:53]: Sending anonymous analytics information
[23:09:53]: Learn more at https://docs.fastlane.tools/#metrics
[23:09:53]: No personal or sensitive data is sent.
[23:09:53]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
[23:09:53]: Generating fastlane environment output, this might take a few seconds...
🚫 fastlane environment 🚫

### Stack

| Key                         | Value                                                  |
| --------------------------- | ------------------------------------------------------ |
| OS                          | debian_based 8.7                                       |
| Ruby                        | 2.4.0                                                  |
| Bundler?                    | false                                                  |
| Git                         | git version 2.1.4                                      |
| Installation Source         | /usr/local/bundle/bin/fastlane                         |
| Host                        | Debian GNU/Linux 8 debian_based 8.7 (4.9.125-linuxkit) |
| Ruby Lib Dir                | /usr/local/lib                                         |
| OpenSSL Version             | OpenSSL 1.0.1t  3 May 2016                             |
| Is contained                | false                                                  |
| Is homebrew                 | false                                                  |
| Is installed via Fabric.app | false                                                  |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

`./fastlane/Fastfile`

```ruby
Ommitted :)

```

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.137.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<b>Loaded gems</b>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.13.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.70.0       |
| faraday                   | 0.17.1       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.0.2        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.14.6       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.1009  |
| mime-types                | 3.3          |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.4.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| openssl                   | 2.0.2        |
| io-console                | 0.4.6        |
| psych                     | 2.2.2        |
</details>

</pre>
</details>

Please let me know if I'm doing something wrong or if you need more information from me!h

**Comment by janpio** [comment]
> We also have quite a few retained APKs which are part of each release which may be related.

Can you provide more information what this actually means?

**Comment by Plastix** [comment]
@janpio I'll do my best to explain. Every Android app has a minimum SDK requirement which is the oldest version of Android that the app supports. For example, an Android app may have a min SDK of 21 meaning that it only runs on Android 5.0 devices and higher.

Android developers can bump their min SDK meaning that they drop support for an older version of Android. Normally this means that users on older SDKs trying to download the app from the Google Play store will get a message that their device is no longer supported. Google Play supports a feature where old binaries can be "retained" so that they are still served to users. This means that users on old version of Android can still download an old version of app but they will not receive updates.

See: https://developer.android.com/google/play/publishing/multiple-apks.html

In the bug report mentioned above, we have a few retained APKs which corresponding to min SDK changes. The highest version in the version codes list printed out by fastlane is the new binary being released while the other ones are being retained.

**Comment by Plastix** [comment]
We're still having this issue. Any idea what is going on? Thanks!

**Comment by Plastix** [comment]
With some experimentation I was able to fix this. It turns out that rollout needs our list of retained APK codes in order to complete successfully. I think this is some undocumented limitation of the new Google Play Dev API V3.
