### ISSUE TITLE
possible to run test cases via testng.xml (maven project) for automating mobile app (Appium project) via fastlane?

### ISSUE THREAD

**Issue by shivani-rana** [fastlane/fastlane#15782]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

**Comment by shivani-rana** [comment]
I want use fastlane for Appium Java project for running test cases. Is there a way to execute test cases via fastlane from testng.xml?

**Comment by minuscorp** [comment]
Not that I know. Fastlane is focused for iOS and Android projects, specially compiling, testing and deployment. I haven't seen any support for Appium neither iOS nor Android.

**Comment by shivani-rana** [comment]
Thanks for your quick response!
is it not possible to run test cases via testng.xml(maven project) for automating mobile app(Appium project) via fastlane?
Please let me know

**Comment by janpio** [comment]
If you have a shell command that does that, you can of course just use the `sh` action in fastlane to execute that shell command.

**Comment by shivani-rana** [comment]
desc "Run maven tests"
  lane :run_maven_tests do 
  Dir.chdir("..") do
    sh "cd /Users/XXXX/eclipse-workspace/automation"
    sh "pwd"
    sh "mvn clean test -Dsurefire.suiteXmlFiles=testng.xml"

   end


Hi,
Thanks janpio.
I am able to run test cases via fastlane through testng.xml but in real devices. I want to try on simulators. can some one pls help

**Comment by shivani-rana** [comment]
[IDB] Connecting idb service to '75EC8AED-2BF5-4C95-BA8A-0E844E4539C2'
[XCUITest] idb will not be used for Simulator interaction. Original error: 'idb' has not been found in PATH. Is it installed? Read https://www.fbidb.io for more details
[BaseDriver] Event 'simStarted' logged at 1575957764130 (11:32:44 GMT+0530 (IST))
[XCUITest] Verifying application platform
[XCUITest] CFBundleSupportedPlatforms: ["iPhoneOS"]
[XCUITest] *********************************
[XCUITest] Simulator architecture appears to be unsupported by the '/Users/shivani.rana/eclipse-workspace/automation/src/main/resources/Accenture_Cloud.app' application. Make sure the correct deployment target has been selected for its compilation in Xcode.
[XCUITest] Don't be surprised if the application fails to launch.
[XCUITest] *********************************

**Comment by janpio** [comment]
> [XCUITest] idb will not be used for Simulator interaction. Original error: 'idb' has not been found in PATH. Is it installed? Read https://www.fbidb.io for more details

Sounds like it doesn't like your environment for some reason.
