### ISSUE TITLE
versionCode as a lane context parameter 

### ISSUE THREAD

**Issue by philjoseph** [fastlane/fastlane#15781]
#### Motivation Behind Feature
I am incrementing the versionCode (Android build number) using the increment_version_code plugin so it is dynamic and would be great to have acessible through the lane context variables. This is important for example (but not only) to create dynamically release notes (see issue https://github.com/fastlane/fastlane/issues/15779)

#### Feature Description
Make it accessible via `lane_context[SharedValues::GRADLE_VERSION_CODE]`

#### Alternatives or Workarounds
I did not found alternatives :(

**Comment by janpio** [comment]
What action specifically do you think should expose this?

**Comment by philjoseph** [comment]
gradle

**Comment by philjoseph** [comment]
I believe it shall be within the gradle action and better to add versionName as well. 
May be generalized to gym with the build number and marketting version

**Comment by janpio** [comment]
Does the `gradle` command line tool surface this information somehow?
