### ISSUE TITLE
Fastlane/Sigh is creating tons of provisioning profiles over time

### ISSUE THREAD

**Issue by dbocksteger-ww** [fastlane/fastlane#15792]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
- Sigh
- Code Signing
- Provisidning Profiles

#### Question Description
We're having heavy problems using Gastland-sigh for automating code-signing, because it's creating tons of profiles over time. 

![image002](https://user-images.githubusercontent.com/56717658/70503886-249d7a80-1b2d-11ea-85fe-98846a298e9d.jpg)

Is it possible to pass a parameter to sigh to only download *but not* create new profiles?

We'd love to get a failing build when something is wrong with the existing profile instead of Gastland creating a new one.

**Comment by janpio** [comment]
You might be looking for `readonly: true`: https://docs.fastlane.tools/actions/sigh/#parameters (near the bottom)
