### ISSUE TITLE
Error loading plugin 'fastlane-plugin-aws_s3': Unable to activate apktools-0.7.2,

### ISSUE THREAD

**Issue by KyleBing** [fastlane/fastlane#15791]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.1                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.21.0 (Apple Git-122)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.1 (19B88)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Library/Developer/CommandLineTools/                           |
| Xcode Version               |                                                                |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
# lane_context[SharedValues::IPA_OUTPUT_PATH] lane_context[SharedValues::BUILD_NUMBER] https://docs.fastlane.tools/advanced/#lane-context
# CredentialsManager : https://github.com/fastlane/fastlane/tree/master/credentials_manager
# clipboard clipboard(value: lane_context[SharedValues::HOCKEY_DOWNLOAD_LINK] || "")
# twitter https://github.com/rb-de0/fastlane-plugin-twitter


#
# Global Variables
#

PROJECT_NAME = "Provenance.xcworkspace"
COMMIT_MSG = "fastlane build bump [ci skip]"

# Carthage

CARTHAGE_PATHS = ["./"]
CARTHAGE_PLATFORMS = "iOS,tvOS"

# Building
SCHEMES =  ["Provenance-Release", "ProvenanceTV-Release"]

# Testing
TEST_SCHEMES = []
TEST_DEVICES = ["iPad Air"]

REQUIRED_XCODE_VERSION = '10.2'.freeze

default_platform(:ios)
$dev_domain = ENV['DEV_DOMAIN'] || 'com.provenance-emu'

## Fastlane imports
# The URL of the repository to import the Fastfile from.
FASTLANE_GIT_URL = 'git@github.com:Provenance/ios-scripts.git'
# The branch to checkout on the repository
FASTLANE_GIT_BRANCH = 'HEAD'
# The directory of the Fastfile's in the repository
FASTLANE_GIT_PATH = 'Fastlane'
# The version to checkout on the repository. 
# Multiple conditions can be used to select the latest version within constraints.
# eg; [">= 1.1.0", "< 2.0.0"] 
FASTLANE_GIT_VERSION = [">= 1.0.0", "< 2.0.0"]
IMPORTS = ["Build", "Carthage", "Certs", "Rome", "Publish", "CI", "Badge", "Testing", "Install", "Enviroment"]
FASTLANE_IMPORT_LOCAL = true

platform :ios do

  IMPORTS.each do |import|
    unless FASTLANE_IMPORT_LOCAL
        import_from_git(
            url: FASTLANE_GIT_URL,
            branch: FASTLANE_GIT_BRANCH, 
            path: "Fastlane/Fastfile+#{import}", 
            version: FASTLANE_GIT_VERSION
        )
    else
        import("Fastfile+#{import}")
    end
  end

  before_all do
    git_pull(only_tags: true)
  end

  # after_all do
  #   push_git_tags
  # end

  private_lane :verify_xcode_version do
    UI.message 'Verifying correct XCode version'
    ensure_xcode_version(version: REQUIRED_XCODE_VERSION)
  end

  # error block is executed when a error occurs
  # error do |lane, exception|
  #   if is_ci?
  #     slack(
  #       # message with short human friendly message
  #       message: exception.to_s,
  #       success: false,
  #       # Output containing extended log output
  #       payload: { "Output" => exception.error_info.to_s }
  #     )
  #   end
  # end
end

def load_keys
  return if is_ci?

  begin
    import('keys')
    $dev_domain = ENV['DEV_DOMAIN']
  rescue StandardError => exception
    if UI.interactive?
      shouldSetup = UI.confirm 'Fastlane enviroment is not configured. Setup now?'
      if shouldSetup
        UI.message 'This feature not yet implimented. Manually edit fastlane/keys using keys.template as an example.'
      end
    end
    raise exception
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# import("keys")

apple_id(ENV["APPLE_ID"]) # Your Apple email address

# TODO If not blank
itc_team_id(ENV["ITC_TEAM_ID"]) # iTunes Connect Team ID
team_id(ENV["DEV_TEAM_ID"]) # Developer Portal Team ID

# app_identifier "com.default.id"

# for_lane :enterprise do
#   app_identifier "com.forlane.enterprise"
# end

# for_platform :mac do
#   app_identifier "com.forplatform.mac"

#   for_lane :release do
#     app_identifier "com.forplatform.mac.forlane.release"
#   end
# end

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile
# Use different bundle identifiers per lane

# for_lane 'ios alpha' do
#   app_identifier "org.wikimedia.wikipedia.tfalpha"
# end
#
# for_lane 'ios beta' do
#   app_identifier "org.wikimedia.wikipedia.tfbeta"
# end
#
# for_lane 'ios store' do
#   app_identifier "org.wikimedia.wikipedia"
# end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.137.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version   | Update-Status      |
| -------------------------- | --------- | ------------------ |
| fastlane-plugin-rome       | 0.3.8     | ✅ Up-To-Date       |
| fastlane-plugin-aws_s3     | undefined | 💥 Check failed     |
| fastlane-plugin-versioning | 0.3.4     | 🚫 Update available |
| fastlane-plugin-badge      | 1.3.0     | ✅ Up-To-Date       |

<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version      |
| -------------------------- | ------------ |
| did_you_mean               | 1.3.0        |
| slack-notifier             | 2.3.2        |
| rouge                      | 2.0.7        |
| xcpretty                   | 0.3.0        |
| terminal-notifier          | 2.0.0        |
| unicode-display_width      | 1.6.0        |
| terminal-table             | 1.8.0        |
| plist                      | 3.5.0        |
| public_suffix              | 2.0.5        |
| addressable                | 2.7.0        |
| multipart-post             | 2.0.0        |
| word_wrap                  | 1.0.0        |
| tty-screen                 | 0.7.0        |
| colored                    | 1.2          |
| highline                   | 1.7.10       |
| commander-fastlane         | 4.4.6        |
| unf_ext                    | 0.0.7.6      |
| unf                        | 0.1.4        |
| domain_name                | 0.5.20190701 |
| http-cookie                | 1.0.3        |
| faraday-cookie_jar         | 0.0.6        |
| faraday                    | 0.17.1       |
| faraday_middleware         | 0.13.1       |
| fastimage                  | 2.1.7        |
| gh_inspector               | 1.1.3        |
| mini_magick                | 4.9.5        |
| multi_xml                  | 0.6.0        |
| rubyzip                    | 1.3.0        |
| security                   | 0.1.3        |
| xcpretty-travis-formatter  | 1.0.0        |
| dotenv                     | 2.7.5        |
| bundler                    | 2.0.2        |
| jwt                        | 2.1.0        |
| uber                       | 0.1.0        |
| declarative                | 0.0.10       |
| declarative-option         | 0.1.0        |
| representable              | 3.0.4        |
| retriable                  | 3.1.2        |
| mime-types                 | 3.3          |
| os                         | 1.0.1        |
| googleauth                 | 0.6.7        |
| httpclient                 | 2.8.3        |
| google-api-client          | 0.23.9       |
| digest-crc                 | 0.4.1        |
| google-cloud-storage       | 1.16.0       |
| emoji_regex                | 1.0.1        |
| nanaimo                    | 0.2.6        |
| colored2                   | 3.1.2        |
| claide                     | 1.0.3        |
| CFPropertyList             | 3.0.2        |
| atomos                     | 0.1.3        |
| xcodeproj                  | 1.13.0       |
| tty-cursor                 | 0.7.0        |
| tty-spinner                | 0.9.2        |
| babosa                     | 1.0.3        |
| excon                      | 0.70.0       |
| json                       | 2.2.0        |
| naturally                  | 2.2.0        |
| simctl                     | 1.6.6        |
| mime-types-data            | 3.2019.1009  |
| multi_json                 | 1.14.1       |
| signet                     | 0.12.0       |
| memoist                    | 0.16.2       |
| google-cloud-env           | 1.3.0        |
| google-cloud-core          | 1.4.1        |
| forwardable                | 1.2.0        |
| logger                     | 1.3.0        |
| stringio                   | 0.0.2        |
| ipaddr                     | 1.2.2        |
| openssl                    | 2.1.2        |
| ostruct                    | 0.1.0        |
| strscan                    | 1.0.0        |
| date                       | 2.0.0        |
| fileutils                  | 1.1.0        |
| etc                        | 1.0.1        |
| io-console                 | 0.4.7        |
| zlib                       | 1.0.0        |
| libxml-ruby                | 3.1.0        |
| rexml                      | 3.1.9        |
| psych                      | 3.1.0        |
| mutex_m                    | 0.1.0        |
| fastlane-plugin-rome       | 0.3.8        |
| jmespath                   | 1.4.0        |
| aws-eventstream            | 1.0.3        |
| aws-sigv4                  | 1.1.0        |
| aws-sdk-core               | 2.11.349     |
| aws-sdk-resources          | 2.11.349     |
| aws-sdk                    | 2.11.349     |
| fastlane-plugin-versioning | 0.3.4        |
| curb                       | 0.9.10       |
| badge                      | 0.11.0       |
| fastlane-plugin-badge      | 1.3.0        |
</details>

*generated on:* **2019-12-10**
</details>

**Comment by janpio** [comment]
Can you please fill the issue template instead of fully deleting it? Thanks.
