### ISSUE TITLE
fastlane deliver download_metadata crash

### ISSUE THREAD

**Issue by patricksuo** [fastlane/fastlane#15806]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre>
+--------------------------------------+-----------------------------------+
|                         deliver 2.137.0 Summary                          |
+--------------------------------------+-----------------------------------+
| app_identifier                       | com.bytedance.gameflow.supei.demo |
| username                             | supei@bytedance.com               |
| force                                | true                              |
| screenshots_path                     | ./screenshots                     |
| metadata_path                        | ./metadata                        |
| app_version                          | 1.0.2                             |
| ipa                                  | gameflow_ci_ipa.ipa               |
| platform                             | ios                               |
| edit_live                            | false                             |
| use_live_version                     | false                             |
| skip_binary_upload                   | false                             |
| skip_screenshots                     | false                             |
| skip_metadata                        | false                             |
| skip_app_version_update              | false                             |
| overwrite_screenshots                | false                             |
| submit_for_review                    | false                             |
| reject_if_possible                   | false                             |
| automatic_release                    | false                             |
| phased_release                       | false                             |
| reset_ratings                        | false                             |
| run_precheck_before_submit           | true                              |
| precheck_default_rule_level          | warn                              |
| individual_metadata_items            | []                                |
| ignore_language_directory_validation | false                             |
| precheck_include_in_app_purchases    | true                              |
+--------------------------------------+-----------------------------------+

Looking for related GitHub issues on fastlane/fastlane...

➡️  [Deliver] reject_version_if_possible!: undefined method can_reject_version for nil:NilClass
    https://github.com/fastlane/fastlane/issues/15759 [open] 1 💬
    a week ago

➡️  [Swift] undefined method `each' for nil:NilClass - Cannot Create Group Within FastlaneSwiftRunner Project
    https://github.com/fastlane/fastlane/issues/15184 [open] 15 💬
    a day ago

➡️  Supply crashes with a nil reference error
    https://github.com/fastlane/fastlane/issues/15718 [open] 6 💬
    a day ago

and 374 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60version%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	13: from /Users/bytedance/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
	12: from /Users/bytedance/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
	11: from /Users/bytedance/.rvm/rubies/ruby-2.6.3/bin/fastlane:23:in `<main>'
	10: from /Users/bytedance/.rvm/rubies/ruby-2.6.3/bin/fastlane:23:in `load'
	 9: from /Users/bytedance/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/bin/fastlane:23:in `<top (required)>'
	 8: from /Users/bytedance/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	 7: from /Users/bytedance/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
	 6: from /Users/bytedance/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/deliver/lib/deliver/commands_generator.rb:182:in `run'
	 5: from /Users/bytedance/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	 4: from /Users/bytedance/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 3: from /Users/bytedance/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 2: from /Users/bytedance/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 1: from /Users/bytedance/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
/Users/bytedance/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/deliver/lib/deliver/commands_generator.rb:171:in `block (2 levels) in run': undefined method `version' for nil:NilClass (NoMethodError)
	13: from /Users/bytedance/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
	12: from /Users/bytedance/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
	11: from /Users/bytedance/.rvm/rubies/ruby-2.6.3/bin/fastlane:23:in `<main>'
	10: from /Users/bytedance/.rvm/rubies/ruby-2.6.3/bin/fastlane:23:in `load'
	 9: from /Users/bytedance/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/bin/fastlane:23:in `<top (required)>'
	 8: from /Users/bytedance/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	 7: from /Users/bytedance/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
	 6: from /Users/bytedance/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/deliver/lib/deliver/commands_generator.rb:182:in `run'
	 5: from /Users/bytedance/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	 4: from /Users/bytedance/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 3: from /Users/bytedance/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 2: from /Users/bytedance/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 1: from /Users/bytedance/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
/Users/bytedance/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/deliver/lib/deliver/commands_generator.rb:171:in `block (2 levels) in run': [!] undefined method `version' for nil:NilClass (NoMethodError)
 </pre>
</details>

**Comment by patricksuo** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.5                                     |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0 (Apple Git-122.2)        |
| Installation Source         | ~/.rvm/rubies/ruby-2.6.3/bin/fastlane       |
| Host                        | Mac OS X 10.14.5 (18F132)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.3/lib                |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.2.1                                      |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.137.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.17.3       |
| etc                       | 1.0.1        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.1        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.13.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.17.1       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.1009  |
| mime-types                | 3.3          |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.1       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.4.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| excon                     | 0.70.0       |
| json                      | 2.2.0        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>


*generated on:* **2019-12-15**
</details>

**Comment by patricksuo** [comment]
@KrauseFx  @maxkomarychev  
do u have any idea?

**Comment by patricksuo** [comment]
and cc  @joshdholtz  because you are currently working on this project.

**Comment by joshdholtz** [comment]
@patricksuo Will add this onto my list of things next week👌 And Felix is working on other projects these days so no need to mention him 😇

**Comment by patricksuo** [comment]
FYI: This problem happen only when there is an ipa file in the fastlane working directory.

**Comment by patricksuo** [comment]
ping

**Comment by patricksuo** [comment]
@joshdholtz  could you disable the fastlane-bot and keep this issue opening until it is resolved?

**Comment by patricksuo** [comment]
ping
