### ISSUE TITLE
Failed to install fastlane

### ISSUE THREAD

**Issue by tangzhentao** [fastlane/fastlane#15800]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Failed to install fastlane.
##### Command executed

sudo gem install fastlane -NV
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>Getting SRV record failed: DNS result has no information for _rubygems._tcp.gems.ruby-china.com
HEAD https://gems.ruby-china.com/api/v1/dependencies
200 OK
GET https://gems.ruby-china.com/api/v1/dependencies?gems=fastlane
200 OK
Getting SRV record failed: DNS result has no information for _rubygems._tcp.gems.ruby-china.com
GET https://gems.ruby-china.com/quick/Marshal.4.8/fastlane-2.137.0.gemspec.rz
200 OK
GET https://gems.ruby-china.com/api/v1/dependencies?gems=CFPropertyList,addressable,babosa,bundler,colored,commander-fastlane,dotenv,emoji_regex,excon,faraday,faraday-cookie_jar,faraday_middleware,fastimage,gh_inspector,google-api-client,google-cloud-storage,highline,json,jwt,mini_magick,multi_xml,multipart-post,plist,public_suffix,rubyzip,security,simctl,slack-notifier,terminal-notifier,terminal-table,tty-screen,tty-spinner,word_wrap,xcodeproj,xcpretty,xcpretty-travis-formatter
200 OK
GET https://gems.ruby-china.com/api/v1/dependencies?gems=atomos,claide,colored2,nanaimo
200 OK
GET https://gems.ruby-china.com/api/v1/dependencies?gems=unicode-display_width
200 OK
GET https://gems.ruby-china.com/api/v1/dependencies?gems=googleauth,http-cookie,httpclient,mime-types,naturally,representable,retriable,rouge,signet,tty-cursor
200 OK
GET https://gems.ruby-china.com/api/v1/dependencies?gems=digest-crc,domain_name,google-cloud-core,memoist,mini_mime,multi_json,os
200 OK
GET https://gems.ruby-china.com/api/v1/dependencies?gems=unf
200 OK
GET https://gems.ruby-china.com/api/v1/dependencies?gems=unf_ext
200 OK
GET https://gems.ruby-china.com/api/v1/dependencies?gems=declarative,declarative-option,uber
200 OK
GET https://gems.ruby-china.com/api/v1/dependencies?gems=google-cloud-env,mime-types-data
200 OK
GET https://gems.ruby-china.com/quick/Marshal.4.8/unf_ext-0.0.7.6.gemspec.rz
200 OK
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.6/.document
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.6/.gitignore
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.6/.travis.yml
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.6/CHANGELOG.md
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.6/Gemfile
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.6/LICENSE.txt
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.6/README.md
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.6/Rakefile
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.6/ext/unf_ext/extconf.rb
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.6/ext/unf_ext/unf.cc
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.6/ext/unf_ext/unf/normalizer.hh
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.6/ext/unf_ext/unf/table.hh
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.6/ext/unf_ext/unf/trie/char_stream.hh
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.6/ext/unf_ext/unf/trie/node.hh
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.6/ext/unf_ext/unf/trie/searcher.hh
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.6/ext/unf_ext/unf/util.hh
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.6/lib/unf_ext.rb
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.6/lib/unf_ext/version.rb
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.6/test/helper.rb
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.6/test/normalization-test.txt
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.6/test/test_unf_ext.rb
/Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.6/unf_ext.gemspec
Building native extensions.  This could take a while...
current directory: /Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.6/ext/unf_ext
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20191212-4759-1n2rv2p.rb extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/include/ruby.h
ERROR:  Error installing fastlane:
	ERROR: Failed to build gem native extension.

    Building has failed. See above output for more information on the failure.
extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.6 for inspection.
Results logged to /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-18/2.3.0/unf_ext-0.0.7.6/gem_make.out </pre>
</details>

### Environment

<details>
  <pre> macOS 0.14.6 (18G95) Xcode Version 11.2 (11B52) </pre>
</details>

**Comment by crobertsbmw** [comment]
I was running into the same issue. I got it installed by using the homebrew method, but then I ran into a Class Mismatch error when trying to call `fastlane init`.

**Comment by tangzhentao** [comment]
update macOS to 10.15.2 (19C57)
retry
success

**Comment by crobertsbmw** [comment]
I will try updating. But couldn't there be a legitimate reason for someone to want to use fast lane and not want to update to macOS 10.15.2?

**Comment by Leandros** [comment]
I'm still on 10.14.2. Running into the same issue.
