### ISSUE TITLE
fastlane supply init: [!] Google Api Error: forbidden: Forbidden - Forbidden

### ISSUE THREAD

**Issue by janoist1** [fastlane/fastlane#15803]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Command executed
`fastlane supply init`

App is created in Play Store with matching package name.

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>
[✔] 🚀 
Successfully loaded Appfile at path '/Users/.../mobile/fastlane/Appfile'
- json_key_file: './android/google-play-dev-dc9a3730ef54.json'
- app_identifier: 'com...'
- apple_id: '...'
-------
INFO [2019-12-13 13:56:54.39]: 🕗  Downloading metadata, images, screenshots...
DEBUG [2019-12-13 13:56:54.40]: Fetching a new access token from Google...
WARN [2019-12-13 13:56:54.58]: To not be asked about this value, you can specify it using 'package_name'
 [2019-12-13 13:56:54.58]: The package name of the application to use: com...
/Users/ist1/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.137.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Google Api Error: forbidden: Forbidden - Forbidden (FastlaneCore::Interface::FastlaneError)
	from /Users/ist1/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.137.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/ist1/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.137.0/supply/lib/supply/client.rb:94:in `rescue in call_google_api'
	from /Users/ist1/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.137.0/supply/lib/supply/client.rb:80:in `call_google_api'
	from /Users/ist1/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.137.0/supply/lib/supply/client.rb:138:in `begin_edit'
	from /Users/ist1/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.137.0/supply/lib/supply/setup.rb:11:in `perform_download'
	from /Users/ist1/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.137.0/supply/lib/supply/commands_generator.rb:53:in `block (2 levels) in run'
	from /Users/ist1/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/ist1/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/ist1/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/ist1/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.137.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/ist1/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/ist1/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.137.0/supply/lib/supply/commands_generator.rb:59:in `run'
	from /Users/ist1/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.137.0/supply/lib/supply/commands_generator.rb:12:in `start'
	from /Users/ist1/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	from /Users/ist1/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.137.0/bin/fastlane:23:in `<top (required)>'
	from /Users/ist1/.rbenv/versions/2.4.0/bin/fastlane:22:in `load'
	from /Users/ist1/.rbenv/versions/2.4.0/bin/fastlane:22:in `<main>'
</pre>
</details>

### Environment
<details>
  <pre>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.1                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0 (Apple Git-122.2)        |
| Installation Source         | ~/.rbenv/versions/2.4.0/bin/fastlane        |
| Host                        | Mac OS X 10.15.1 (19B88)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.0/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.2.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   | en_GB.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.3"

default_platform :ios

platform :ios do
  before_all do
    #cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    ENV["ENV"] = "beta"
    ENV["APP_ENV"] = "beta"
    ENV["NODE_ENV"] = "beta"
    ENV['ENVFILE'] = '.env.beta'

    #get_certificates           # invokes cert
    #get_provisioning_profile   # invokes sigh
    #build_app

    xcode_select '/Applications/Xcode.app'

    # match(type: "appstore") # more information: https://codesigning.guide

    increment_build_number(xcodeproj: './ios/novus.xcodeproj')

    #gym # Build your app - more options available
    gym(scheme: 'novus', workspace: './ios/novus.xcworkspace', export_xcargs: "-allowProvisioningUpdates")
    #gym(scheme: 'novus', project: './ios/novus.xcodeproj')
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    ENV["env"] = "production"
    ENV['ENVFILE'] = '.env.production'

    # match(type: "appstore")
    # snapshot
    #gym # Build your app - more options available
    gym(scheme: 'novus', project: './ios/novus.xcodeproj')
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

platform :android do:

  desc "Submit a new Beta Build"
  lane :beta do
    increment_version_code(
        gradle_file_path: "project/build.gradle",
        #ext_constant_name: "test"
        #app_folder_name:"app"
    )
  end
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby

json_key_file "./android/google-play-dev-dc9a3730ef54.json"

app_identifier "com.heroteam.novus" # The bundle identifier of your app
apple_id "istvan@heroteam.io" # Your Apple email address

#team_id "heroteam" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.137.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                 | Version | Update-Status |
| -------------------------------------- | ------- | ------------- |
| fastlane-plugin-increment_version_code | 0.4.3   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                    | Version      |
| -------------------------------------- | ------------ |
| did_you_mean                           | 1.1.0        |
| atomos                                 | 0.1.3        |
| CFPropertyList                         | 3.0.2        |
| claide                                 | 1.0.3        |
| colored2                               | 3.1.2        |
| nanaimo                                | 0.2.6        |
| xcodeproj                              | 1.13.0       |
| rouge                                  | 2.0.7        |
| xcpretty                               | 0.3.0        |
| terminal-notifier                      | 2.0.0        |
| terminal-table                         | 1.8.0        |
| plist                                  | 3.5.0        |
| multipart-post                         | 2.0.0        |
| word_wrap                              | 1.0.0        |
| public_suffix                          | 2.0.5        |
| tty-screen                             | 0.7.0        |
| tty-cursor                             | 0.7.0        |
| tty-spinner                            | 0.9.2        |
| babosa                                 | 1.0.3        |
| colored                                | 1.2          |
| highline                               | 1.7.10       |
| commander-fastlane                     | 4.4.6        |
| unf_ext                                | 0.0.7.6      |
| unf                                    | 0.1.4        |
| domain_name                            | 0.5.20190701 |
| http-cookie                            | 1.0.3        |
| faraday-cookie_jar                     | 0.0.6        |
| faraday                                | 0.17.1       |
| faraday_middleware                     | 0.13.1       |
| fastimage                              | 2.1.7        |
| gh_inspector                           | 1.1.3        |
| mini_magick                            | 4.9.5        |
| multi_xml                              | 0.6.0        |
| rubyzip                                | 1.3.0        |
| security                               | 0.1.3        |
| xcpretty-travis-formatter              | 1.0.0        |
| naturally                              | 2.2.0        |
| simctl                                 | 1.6.6        |
| jwt                                    | 2.1.0        |
| uber                                   | 0.1.0        |
| declarative                            | 0.0.10       |
| declarative-option                     | 0.1.0        |
| representable                          | 3.0.4        |
| retriable                              | 3.1.2        |
| signet                                 | 0.12.0       |
| memoist                                | 0.16.2       |
| os                                     | 1.0.1        |
| googleauth                             | 0.6.7        |
| httpclient                             | 2.8.3        |
| google-api-client                      | 0.23.9       |
| google-cloud-env                       | 1.3.0        |
| google-cloud-core                      | 1.4.1        |
| digest-crc                             | 0.4.1        |
| google-cloud-storage                   | 1.16.0       |
| emoji_regex                            | 1.0.1        |
| openssl                                | 2.0.2        |
| json                                   | 2.3.0        |
| io-console                             | 0.4.6        |
| excon                                  | 0.71.0       |
| mini_portile2                          | 2.1.0        |
| nokogiri                               | 1.7.2        |
| bundler                                | 2.1.0.pre.3  |
| unicode-display_width                  | 1.6.0        |
| dotenv                                 | 2.7.5        |
| addressable                            | 2.7.0        |
| multi_json                             | 1.14.1       |
| psych                                  | 2.2.2        |
| mime-types                             | 3.3          |
| mime-types-data                        | 3.2019.1009  |
| fastlane-plugin-increment_version_code | 0.4.3        |
</details>

*generated on:* **2019-12-13**
</details>
</pre>
</details>

**Comment by janoist1** [comment]
Anyone else facing this?
Any idea why is this? I've gone through that others said might be wrong here https://github.com/fastlane/fastlane/issues/14268, no luck...

**Comment by SchlagerKhan** [comment]
@janoist1 Did you find any solution to this?

I've tried both to follow the documentation, setting the service account role to `Service Account User` and to `Project Owner`. I've also given it Admin permissions in the Google Play Console.

I cannot find what I'm doing wrong.

This is my output of `fastlane supply init --verbose`:

<details>

```
Successfully loaded Appfile at path '/Users/.../android/fastlane/Appfile'
- json_key_file: ...
- package_name: ...
-------
INFO [2020-03-12 06:53:32.55]: 🕗  Downloading metadata, images, screenshots...
DEBUG [2020-03-12 06:53:32.56]: Fetching a new access token from Google...
Traceback (most recent call last):
        30: from /usr/local/bin/fastlane:23:in `<main>'
        29: from /usr/local/bin/fastlane:23:in `load'
        28: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/bin/fastlane:23:in `<top (required)>'
        27: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
        26: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/supply/lib/supply/commands_generator.rb:12:in `start'
        25: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/supply/lib/supply/commands_generator.rb:59:in `run'
        24: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        23: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        22: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        21: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        20: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        19: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/supply/lib/supply/commands_generator.rb:53:in `block (2 levels) in run'
        18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/supply/lib/supply/setup.rb:11:in `perform_download'
        17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/supply/lib/supply/client.rb:138:in `begin_edit'
        16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/supply/lib/supply/client.rb:80:in `call_google_api'
        15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/supply/lib/supply/client.rb:138:in `block in begin_edit'
        14: from /Library/Ruby/Gems/2.6.0/gems/google-api-client-0.36.4/generated/google/apis/androidpublisher_v3/service.rb:200:in `insert_edit'
        13: from /Library/Ruby/Gems/2.6.0/gems/google-api-client-0.36.4/lib/google/apis/core/base_service.rb:360:in `execute_or_queue_command'
        12: from /Library/Ruby/Gems/2.6.0/gems/google-api-client-0.36.4/lib/google/apis/core/http_command.rb:102:in `execute'
        11: from /Library/Ruby/Gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
        10: from /Library/Ruby/Gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
         9: from /Library/Ruby/Gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
         8: from /Library/Ruby/Gems/2.6.0/gems/google-api-client-0.36.4/lib/google/apis/core/http_command.rb:110:in `block in execute'
         7: from /Library/Ruby/Gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
         6: from /Library/Ruby/Gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
         5: from /Library/Ruby/Gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
         4: from /Library/Ruby/Gems/2.6.0/gems/google-api-client-0.36.4/lib/google/apis/core/http_command.rb:113:in `block (2 levels) in execute'
         3: from /Library/Ruby/Gems/2.6.0/gems/google-api-client-0.36.4/lib/google/apis/core/http_command.rb:310:in `execute_once'
         2: from /Library/Ruby/Gems/2.6.0/gems/google-api-client-0.36.4/lib/google/apis/core/http_command.rb:193:in `process_response'
         1: from /Library/Ruby/Gems/2.6.0/gems/google-api-client-0.36.4/lib/google/apis/core/api_command.rb:117:in `check_status'
/Library/Ruby/Gems/2.6.0/gems/google-api-client-0.36.4/lib/google/apis/core/http_command.rb:228:in `check_status': forbidden: The caller does not have permission (Google::Apis::ClientError)
        17: from /usr/local/bin/fastlane:23:in `<main>'
        16: from /usr/local/bin/fastlane:23:in `load'
        15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/bin/fastlane:23:in `<top (required)>'
        14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
        13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/supply/lib/supply/commands_generator.rb:12:in `start'
        12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/supply/lib/supply/commands_generator.rb:59:in `run'
        11: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
         9: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
         8: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
         7: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
         6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/supply/lib/supply/commands_generator.rb:53:in `block (2 levels) in run'
         5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/supply/lib/supply/setup.rb:11:in `perform_download'
         4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/supply/lib/supply/client.rb:138:in `begin_edit'
         3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/supply/lib/supply/client.rb:79:in `call_google_api'
         2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/supply/lib/supply/client.rb:94:in `rescue in call_google_api'
         1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.143.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Google Api Error: forbidden: The caller does not have permission - The caller does not have permission (FastlaneCore::Interface::FastlaneError)
```

</details>

**Comment by vgekht** [comment]
I have the same issue: "[!] Google Api Error: forbidden: The caller does not have permission - The caller does not have permission"
after -> fastlane supply init
fastlane 2.143.0

I created a ticket today in a support channel
