### ISSUE TITLE
中文文档支持.

### ISSUE THREAD

**Issue by zengyuios** [fastlane/fastlane#15805]
### Question Checklist

- [x] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

YES
I hope to have a Chinese version of the document, because an English idiot like me, who lives by translation, has a lot of difficulty in reading the document, and many powerful functions of the tool are not used. Seeing the document with a little understanding, it takes a lot of time to study one by one.

I hope that the author is free, you can put document translation on the agenda, thank you!

希望能有一个中文版本的文档，因为像我这样的英文白痴，靠着翻译过活的，阅读文档很吃力，而且工具很多强大的功能都没用上，文档看得一知半解，自己一个个研究时间要耗费很大。
期望作者有空了，可以吧文档翻译提上日程，谢谢!

**Comment by max-ott** [comment]
Hi @zengyuios as this is an open source project we live on the support of the community. Maybe other Chinese-speaking folks can help with pull requests for translating the documentation.

**Comment by zengyuios** [comment]
Thank you!
fastlane is a great tool, so I hope more people will use it!
The above are just a little bit of my advice, or a little bit of my feeling after using it! Thank you for replying to me!
