### ISSUE TITLE
Fastlane 2.131.0 Exit status: 165

### ISSUE THREAD

**Issue by saranyaj86** [fastlane/fastlane#15814]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by saranyaj86** [comment]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.21.0 (Apple Git-122.2)        |
| Installation Source         | ~/.rvm/gems/ruby-2.6.3/bin/fastlane         |
| Host                        | Mac OS X 10.14.6 (18G103)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.3/lib                |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.3                                        |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.131.0"

default_platform :ios

workspace = "Compass.xcworkspace"
token = "ad87b323e7785261ee3e333b499b665e0477e462"
secret = "035b6cd61c7c05b9c6c2fd957a388e43a21a9e799f18c71246b6e90e19eac5c1"

# Branches that should run acceptance tests, case sensitive list
acceptance_test_branches = ['master', 'QA', 'test/']

platform :ios do

  desc "Runs compass tests"
  lane :test_compass do
    scan(workspace: workspace,
      scheme: "CompassTests",
      clean: true,
      fail_build: true,
      code_coverage: true,
      derived_data_path: "./build",
      device: "iPad Air (12.2)",
      include_simulator_logs: false)
  end

  desc "Generates code coverage report for Compass"
  lane :code_coverage_compass do
  slather(
    cobertura_xml: true,
    build_directory: "./build/",
    output_directory: "./reports/compass/",
    scheme: "Compass",
    workspace: workspace,
    proj: "./Compass/Compass.xcodeproj",
  )
  end

  desc "Runs beers tests"
  lane :test_beers do
    scan(workspace: workspace,
      scheme: "BeersTests",
      clean: false,
      fail_build: true,
      code_coverage: true,
      derived_data_path: "./build",
      device: "iPad Air (12.2)",
      include_simulator_logs: false)
  end

  desc "Runs beers iPad UI Tests"
  lane :test_beers_ui_pad do
    scan(workspace: workspace,
      scheme: "Compass-Beers-UITests",
      clean: false,
      fail_build: true,
      code_coverage: true,
      derived_data_path: "./build",
      devices: "iPad Air (12.2)")
  end

  desc "Runs beers iPhone UI Tests"
  lane :test_beers_ui_phone do
    scan(workspace: workspace,
      scheme: "Compass-Beers-UITests",
      clean: false,
      fail_build: true,
      code_coverage: true,
      derived_data_path: "./build",
      devices: "iPhone 7 (12.2)")
  end

  desc "Generates code coverage report for Beers"
  lane :code_coverage_beers do
  slather(
    cobertura_xml: true,
    build_directory: "./build/",
    output_directory: "./reports/beers/",
    scheme: "Beers",
    workspace: workspace,
    proj: "./Beers/Beers.xcodeproj",
  )
  end

  desc "Runs wines tests"
  lane :test_wines do
  scan(workspace: workspace,
    scheme: "Wines",
    clean: false,
    fail_build: true,
    code_coverage: true,
    derived_data_path: "./build",
    device: "iPad Air (12.2)",
    include_simulator_logs: false)
  end

  desc "Runs wines iPad UI Tests"
  lane :test_wines_ui_pad do
    scan(workspace: workspace,
      scheme: "Compass-Wines-UITests",
      clean: false,
      fail_build: true,
      code_coverage: true,
      derived_data_path: "./build",
      devices: "iPad Air 2 (12.2)")
  end

  desc "Runs wines iPhone UI Tests"
  lane :test_wines_ui_phone do
    scan(workspace: workspace,
      scheme: "Compass-Wines-UITests",
      clean: false,
      fail_build: true,
      code_coverage: true,
      derived_data_path: "./build",
      devices: "iPhone 8 (12.2)")
  end

  desc "Runs Beers iPad Analytics Tests"
  lane :test_beers_pad_firebase_analytics do
    scan(workspace: workspace,
      scheme: "BeersAnalytics",
      clean: false,
      fail_build: true,
      code_coverage: true,
      derived_data_path: "./build",
      devices: "iPad Air 2 (12.2)", include_simulator_logs: true)
  end

  desc "Runs Beers iPhone Analytics Tests"
  lane :test_beers_phone_firebase_analytics do
    scan(workspace: workspace,
      scheme: "BeersAnalytics",
      clean: false,
      fail_build: true,
      code_coverage: true,
      derived_data_path: "./build",
      devices: "iPhone 7 (12.2)", include_simulator_logs: true)
  end

  desc "Runs Wines iPad Analytics Tests"
  lane :test_wines_pad_firebase_analytics do
    scan(workspace: workspace,
      scheme: "WinesAnalytics",
      clean: false,
      fail_build: true,
      code_coverage: true,
      derived_data_path: "./build",
      devices: "iPad Air 2 (12.2)", include_simulator_logs: true)
  end

  desc "Runs Wines iPhone Analytics Tests"
  lane :test_wines_phone_firebase_analytics do
    scan(workspace: workspace,
      scheme: "WinesAnalytics",
      clean: false,
      fail_build: true,
      code_coverage: true,
      derived_data_path: "./build",
      devices: "iPhone 7 (12.2)", include_simulator_logs: true)
  end

  desc "Generates code coverage report for Wines"
  lane :code_coverage_wines do
  slather(
    cobertura_xml: true,
    build_directory: "./build/",
    output_directory: "./reports/wines/",
    scheme: "Wines",
    workspace: workspace,
    proj: "./Wines/Wines.xcodeproj",
  )
  end

  desc "Report code coverage statistics"
  lane :updateStatistics do
    sh "../scripts/update-wiki-stats.sh"
  end

  desc "Create and Submit a new Wines Build to Fabric"
  lane :wines_deploy do
    setup_circle_ci
    ENV["PROFILE_UDID"] = ENV["PROFILE_UUID"]

    import_certificate(
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      certificate_path: "fastlane/certificates/CBIEnterpriseCertificate.p12",
      certificate_password: ENV["CERTIFICATE_PASSWORD"] || "default",
    )

    gym(workspace: workspace,
      scheme: 'Wines',
      export_method: "enterprise",
      xcargs: "ARCHIVE=YES",
      export_options: {
        provisioningProfiles: {
          "com.cbrands.compass.beers" => "CBIEnterpriseWildcard21AUG2020",
          "com.cbrands.compass.beersDEV" => "CBIEnterpriseWildcard21AUG2020",
          "com.cbrands.compass.beersUAT" => "CBIEnterpriseWildcard21AUG2020",
          "com.cbrands.compass.beersQA" => "CBIEnterpriseWildcard21AUG2020"
        }
      }
    )

  crashlytics(api_token: token,
    build_secret: secret,
    notes_path: "Wines/releasenotes.txt")

    upload_symbols_to_crashlytics(api_token: token,
      dsym_path: "./Wines.app.dSYM.zip")

    firebase_app_distribution(
      app: ENV["APPID"],
      groups: ENV['GROUPS'],
      release_notes_file: "Wines/releasenotes.txt",
      firebase_cli_path: "./node_modules/.bin/firebase",
      firebase_cli_token: ENV["FIREBASE_TOKEN"])
  end

  desc "Create and Submit a new Beers Build to Fabric"
  lane :beers_deploy do
    setup_circle_ci
    ENV["PROFILE_UDID"] = ENV["PROFILE_UUID"]

    import_certificate(
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      certificate_path: "fastlane/certificates/CBIEnterpriseCertificate.p12",
      certificate_password: ENV["CERTIFICATE_PASSWORD"] || "default",
    )

    gym(workspace: workspace,
      scheme: 'Beers',
      export_method: "enterprise",
      xcargs: "ARCHIVE=YES",
      export_options: {
        provisioningProfiles: {
          "com.cbrands.sales" => "CBIEnterpriseWildcard21AUG2020",
          "com.cbrands.salesDEV" => "CBIEnterpriseWildcard21AUG2020",
          "com.cbrands.salesUAT" => "CBIEnterpriseWildcard21AUG2020",
          "com.cbrands.salesQA" => "CBIEnterpriseWildcard21AUG2020"
        }
      }
    )

    crashlytics(api_token: token,
      build_secret: secret,
      notes_path: "Beers/releasenotes.txt")

    upload_symbols_to_crashlytics(api_token: token,
      dsym_path: "./Beers.app.dSYM.zip")

    firebase_app_distribution(
      app: ENV["APPID"],
      groups: ENV['GROUPS'],
      release_notes_file: "Beers/releasenotes.txt",
      firebase_cli_path: "./node_modules/.bin/firebase",
      firebase_cli_token: ENV["FIREBASE_TOKEN"])
  end

  # You can define as many lanes as you want

  after_all do |lane|
  # This block is called, only if the executed lane was successful

  # slack(
  #   message: "Successfully deployed new App Update."
  # )
  end

  error do |lane, exception|
  # slack(
  #   message: exception.message,
  #   success: false
  # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://github.com/fastlane/fastlane#metrics

```
</details>

**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.131.0 | 🚫 Update available |


### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.1.4   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.3.0        |
| executable-hooks                          | 1.6.0        |
| bundler-unload                            | 1.0.2        |
| rubygems-bundler                          | 1.4.5        |
| bundler                                   | 1.17.3       |
| etc                                       | 1.0.1        |
| forwardable                               | 1.2.0        |
| CFPropertyList                            | 3.0.1        |
| concurrent-ruby                           | 1.1.5        |
| i18n                                      | 0.9.5        |
| minitest                                  | 5.11.3       |
| thread_safe                               | 0.3.6        |
| tzinfo                                    | 1.2.5        |
| activesupport                             | 4.2.11.1     |
| public_suffix                             | 2.0.5        |
| addressable                               | 2.7.0        |
| atomos                                    | 0.1.3        |
| babosa                                    | 1.0.2        |
| claide                                    | 1.0.3        |
| clamp                                     | 1.3.1        |
| fuzzy_match                               | 2.0.4        |
| nap                                       | 1.1.0        |
| cocoapods-core                            | 1.7.5        |
| cocoapods-deintegrate                     | 1.0.4        |
| cocoapods-downloader                      | 1.2.2        |
| cocoapods-plugins                         | 1.0.0        |
| cocoapods-search                          | 1.0.0        |
| cocoapods-stats                           | 1.1.0        |
| netrc                                     | 0.11.0       |
| cocoapods-trunk                           | 1.4.0        |
| cocoapods-try                             | 1.1.0        |
| colored2                                  | 3.1.2        |
| escape                                    | 0.0.4        |
| fourflusher                               | 2.3.1        |
| gh_inspector                              | 1.1.3        |
| molinillo                                 | 0.6.6        |
| ruby-macho                                | 1.4.0        |
| nanaimo                                   | 0.2.6        |
| xcodeproj                                 | 1.12.0       |
| cocoapods                                 | 1.7.5        |
| colored                                   | 1.2          |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| declarative                               | 0.0.10       |
| declarative-option                        | 0.1.0        |
| digest-crc                                | 0.4.1        |
| unf_ext                                   | 0.0.7.6      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| dotenv                                    | 2.7.5        |
| emoji_regex                               | 1.0.1        |
| excon                                     | 0.66.0       |
| multipart-post                            | 2.0.0        |
| faraday                                   | 0.15.4       |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.6        |
| faraday_middleware                        | 0.13.1       |
| fastimage                                 | 2.1.7        |
| jwt                                       | 2.1.0        |
| memoist                                   | 0.16.0       |
| multi_json                                | 1.13.1       |
| os                                        | 1.0.1        |
| signet                                    | 0.11.0       |
| googleauth                                | 0.6.7        |
| httpclient                                | 2.8.3        |
| mime-types-data                           | 3.2019.0904  |
| mime-types                                | 3.3          |
| uber                                      | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| google-api-client                         | 0.23.9       |
| google-cloud-env                          | 1.2.1        |
| google-cloud-core                         | 1.3.1        |
| google-cloud-storage                      | 1.16.0       |
| json                                      | 2.2.0        |
| mini_magick                               | 4.9.5        |
| multi_xml                                 | 0.6.0        |
| plist                                     | 3.5.0        |
| rubyzip                                   | 1.2.4        |
| security                                  | 0.1.3        |
| naturally                                 | 2.2.0        |
| simctl                                    | 1.6.6        |
| slack-notifier                            | 2.3.2        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.6.0        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.7.0        |
| tty-cursor                                | 0.7.0        |
| tty-spinner                               | 0.9.1        |
| word_wrap                                 | 1.0.0        |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.0        |
| fastlane-plugin-firebase_app_distribution | 0.1.4        |
| mini_portile2                             | 2.4.0        |
| nokogiri                                  | 1.10.4       |
| slather                                   | 2.4.7        |
</details>


*generated on:* **2019-12-18**
</details>

**Comment by janpio** [comment]
Please update to the newest version and let us know if this fixes the problem.
