### ISSUE TITLE
Spaceship::Testflight::Group is using the wrong API

### ISSUE THREAD

**Issue by racer1988** [fastlane/fastlane#15810]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Using TestFlight::Group module always gives a NOT FOUND error from Fastlane

Seems to me because module declares: https://appstoreconnect.apple.com/testflight/v2/ in https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/test_flight/client.rb#L18

while [Docs](https://developer.apple.com/documentation/appstoreconnectapi/list_beta_groups) from apple declare to use `https://api.appstoreconnect.apple.com/v1/betaGroups`

##### Command executed
eg: `Spaceship::TestFlight::Group.internal_group(app_id: app.apple_id)`

##### Complete output when running fastlane, including the stack trace and command used

```
Spaceship::UnexpectedResponse: <!DOCTYPE html><html lang="en">
<head>
<title></title>
<link rel="stylesheet" href="/styles/main.css">
<style type='text/css'>
    /*include ../../dist/styles/main.css*/
</style>
</head>

<body><div id="wrapper" class="j42">
<h2>Not Found</h2></div>

<div class="footer">
    <p>Copyright &copy; <span id='year'>2015</span> Apple Inc. All rights reserved.</p>
    <ul><li><a href="https://www.apple.com/legal/internet-services/itunes/">Terms of Service</a></li><li><a href="https://www.apple.com/legal/privacy">Privacy Policy</a></li></ul>
</div>


<script type='text/javascript'>(function() {
    var isIos = navigator.userAgent.match(/(iPod|iPhone|iPad)/);
    document.body.setAttribute( 'class', (!isIos) ? 'otherBrowser' : 'isMobileSafari' )
    var yearEl = document.getElementById('year');
    if (yearEl) { yearEl.textContent = new Date().getFullYear(); }
})();
</script>

</body>
</html>
from /Users/x/.gem/ruby/2.6.5/gems/fastlane-2.137.0/spaceship/lib/spaceship/test_flight/client.rb:321:in `handle_response'
```

### Environment
```
| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.2                                     |
| Ruby                        | 2.6.5                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.24.0                          |
| Installation Source         | ~/.gem/ruby/2.6.5/bin/fastlane              |
| Host                        | Mac OS X 10.15.2 (19C57)                    |
| Ruby Lib Dir                | ~/.rubies/ruby-2.6.5/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.3
```

**Comment by janpio** [comment]
cc @max-ott

**Comment by geraldeersteling** [comment]
I concur, I've disabled these endpoints for a long time already. 
Is there any follow up on this?

**Comment by racer1988** [comment]
Does this means there is currently no way to get Testlight Groups via Spaceship?

**Comment by max-ott** [comment]
@racer1988 I'm no real TestFlight expert, but if it's not working with the old API Apple probably changed stuff and it has not been yet adapted / added to spaceship. Feel free to create a pull request and add it. If you are unsure, check out the source code to see if there are any references to TestFlight groups.

**Comment by virus2016** [comment]
@racer1988 No way to create groups at the moment. Still able to add users to and existing group.

**Comment by racer1988** [comment]
@virus2016 could you explain me how to add a tester group to a build?

I have been trying to do that for a while but it’s impossible to fetch the groups as Apple replies 404 to the Spaceship Group. 

I would like to try to modify spaceship to use the new api but first would like to know if you can show me how you get groups at the moment

**Comment by virus2016** [comment]
Hi @racer1988,

I have found having to create the group in the GUI (Apple connect platform) under testflight of your app first. Then you can add users to the list.

**Comment by racer1988** [comment]
@virus2016 please try

`Spaceship::TestFlight::Group.internal_group(app_id: app.apple_id)`

Does this works for you?

I already have the builds uploaded and the groups defined and users added to them.
I need to fetch and assign groups to build. This is not currently possible.

**Comment by virus2016** [comment]
@racer1988 Nope, doesn't work for me. <h2>Not Found</h2> comes back

**Comment by racer1988** [comment]
It's clear that the group endpoint is not valid anymore and new development via ConnectAPI is needed to restore the functionality.

I currently tried working with a quick request based solution and I can make it work.

I hope I can come back to this and contribute to the connect api.
Thanks
