### ISSUE TITLE
Uploading App Previews (trailers) implementation.

### ISSUE THREAD

**Issue by xhairbait** [fastlane/fastlane#15815]
- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I previously made a ticket about being able to upload App Previews (trailers) and how to get it working.
See link to old ticket below.
https://github.com/fastlane/fastlane/issues/14535#issue-430711077

I noticed in app_version_spec.rb
The following section is commented out, and was wondering why, and if it is possible to have these uncommented?

```ruby
    # describe "Modifying the app trailers", :trailers do
    #   let(:ipad_trailer_path) { "path_to_trailer.mov" }
    #   let(:ipad_trailer_preview_path) { "path_to_trailer_preview.jpg" }
    #   let(:ipad_external_valid_trailer_preview_path) { "path_to_my_screenshot.jpg" }
    #   let(:ipad_external_invalid_trailer_preview_path) { "path_to_my_invalid_screenshot.jpg" }
    #   before do
    #     allow(Spaceship::UploadFile).to receive(:from_path) do |path|
    #       r = du_uploadtrailer_correct_mov if path == ipad_trailer_path
    #       r = du_uploadtrailer_preview_correct_jpg if path == ipad_trailer_preview_path
    #       r = du_uploadtrailer_preview_correct_jpg if path == ipad_external_valid_trailer_preview_path
    #       r
    #     end

    #     allow(Spaceship::Utilities).to receive(:grab_video_preview) do |path|
    #       r = ipad_trailer_preview_path if path == ipad_trailer_path
    #       r
    #     end

    #     allow(Spaceship::Utilities).to receive(:portrait?) do |path|
    #       r = true if path == ipad_trailer_preview_path
    #       r = true if path == ipad_external_invalid_trailer_preview_path
    #       r = true if path == ipad_external_valid_trailer_preview_path
    #       r
    #     end

    #     allow(Spaceship::Utilities).to receive(:resolution) do |path|
    #       r = [900, 1200] if path == ipad_trailer_path
    #       r = [768, 1024] if path == ipad_trailer_preview_path
    #       r = [700, 1000] if path == ipad_external_invalid_trailer_preview_path
    #       r = [768, 1024] if path == ipad_external_valid_trailer_preview_path
    #       r
    #     end

    #     json = JSON.parse(du_read_fixture_file("upload_trailer_response_success.json"))
    #     allow(client.du_client).to receive(:upload_trailer).and_return(json)

    #     json = JSON.parse(du_read_upload_trailer_preview_response_success)
    #     allow(client.du_client).to receive(:upload_trailer_preview).and_return(json)
    #   end

    #   def trailers(device)
    #     version.trailers["English"].select { |s| s.device_type == device }
    #   end

    #   def ipad_trailers
    #     trailers("ipad")
    #   end

    #   it "cannot add a trailer to iphone35" do
    #     expect do
    #       version.upload_trailer!(ipad_trailer_path, "English", 'iphone35')
    #     end.to raise_error "No app trailer supported for iphone35"
    #   end

    #   it "requires timestamp with a specific format" do
    #     expect do
    #       version.upload_trailer!(ipad_trailer_path, "English", 'ipad', "00:01.000")
    #     end.to raise_error "Invalid timestamp 00:01.000"
    #     expect do
    #       version.upload_trailer!(ipad_trailer_path, "English", 'ipad', "01.000")
    #     end.to raise_error "Invalid timestamp 01.000"
    #   end

    #   it "can add a new trailer" do
    #     # remove existing
    #     version.upload_trailer!(nil, "English", 'ipad')

    #     count = ipad_trailers.count
    #     expect(count).to eq(0)
    #     version.upload_trailer!(ipad_trailer_path, "English", 'ipad')
    #     count_after = ipad_trailers.count
    #     expect(count_after).to eq(count + 1)
    #     expect(count_after).to eq(count + 1)
    #     trailer = ipad_trailers[0]
    #     expect(trailer.video_asset_token).to eq("VideoSource40/v4/e3/48/1a/e3481a8f-ec25-e19f-5048-270d7acaf89a/pr_source.mov")
    #     expect(trailer.picture_asset_token).to eq("Purple69/v4/5f/2b/81/5f2b814d-1083-5509-61fb-c0845f7a9374/pr_source.jpg")
    #     expect(trailer.descriptionXML).to match(/FoghornLeghorn/)
    #     expect(trailer.preview_frame_time_code).to eq("00:00:05:00")
    #     expect(trailer.video_url).to eq(nil)
    #     expect(trailer.preview_image_url).to eq(nil)
    #     expect(trailer.full_sized_preview_image_url).to eq(nil)
    #     expect(trailer.device_type).to eq("ipad")
    #     expect(trailer.language).to eq("English")
    #   end

    #   it "can modify the preview of an existing trailer and automatically generates a new screenshot preview" do
    #     json = JSON.parse(du_read_upload_trailer_preview_2_response_success)
    #     allow(client.du_client).to receive(:upload_trailer_preview).and_return(json)

    #     count = ipad_trailers.count
    #     expect(count).to eq(1)
    #     version.upload_trailer!(ipad_trailer_path, "English", 'ipad', "06.12")
    #     count_after = ipad_trailers.count
    #     expect(count_after).to eq(count)
    #     trailer = ipad_trailers[0]

    #     expect(trailer.video_asset_token).to eq(nil)
    #     expect(trailer.picture_asset_token).to eq("Purple70/v4/5f/2b/81/5f2b814d-1083-5509-61fb-c0845f7a9374/pr_source.jpg")
    #     expect(trailer.descriptionXML).to eq(nil)
    #     expect(trailer.preview_frame_time_code).to eq("00:00:06:12")
    #     expect(trailer.video_url).to eq("http://a1713.phobos.apple.com/us/r30/PurpleVideo7/v4/be/38/db/be38db8d-868a-d442-87dc-cb6d630f921e/P37134684_default.m3u8")
    #     expect(trailer.preview_image_url).to eq("https://is1-ssl.mzstatic.com/image/thumb/PurpleVideo5/v4/b7/41/5e/b7415e96-5ad5-6cf5-9323-15122145e53f/Job21976428-61a9-456b-af46-26c1303ae607-91524171-PreviewImage_AppTrailer_quicktime-Time1438426738374.png/500x500bb-80.png")
    #     expect(trailer.full_sized_preview_image_url).to eq("https://is1-ssl.mzstatic.com/image/thumb/PurpleVideo5/v4/b7/41/5e/b7415e96-5ad5-6cf5-9323-15122145e53f/Job21976428-61a9-456b-af46-26c1303ae607-91524171-PreviewImage_AppTrailer_quicktime-Time1438426738374.png/900x1200ss-80.png")
    #     expect(trailer.device_type).to eq("ipad")
    #     expect(trailer.language).to eq("English")
    #   end

    #   it "can add a new trailer given a valid externally provided preview screenshot" do
    #     # remove existing
    #     version.upload_trailer!(nil, "English", 'ipad')

    #     expect do
    #       version.upload_trailer!(ipad_trailer_path, "English", 'ipad', '12.34', ipad_external_invalid_trailer_preview_path)
    #     end.to raise_error "Invalid portrait screenshot resolution for device ipad. Should be [768, 1024]"
    #   end

    #   it "can add a new trailer given a valid externally provided preview screenshot" do
    #     # remove existing
    #     version.upload_trailer!(nil, "English", 'ipad')

    #     count = ipad_trailers.count
    #     expect(count).to eq(0)
    #     version.upload_trailer!(ipad_trailer_path, "English", 'ipad', '12.34', ipad_external_valid_trailer_preview_path)
    #     count_after = ipad_trailers.count
    #     expect(count_after).to eq(count + 1)
    #     trailer = ipad_trailers[0]
    #     expect(trailer.video_asset_token).to eq("VideoSource40/v4/e3/48/1a/e3481a8f-ec25-e19f-5048-270d7acaf89a/pr_source.mov")
    #     expect(trailer.picture_asset_token).to eq("Purple69/v4/5f/2b/81/5f2b814d-1083-5509-61fb-c0845f7a9374/pr_source.jpg")
    #     expect(trailer.descriptionXML).to match(/FoghornLeghorn/)
    #     expect(trailer.preview_frame_time_code).to eq("00:00:12:34")
    #     expect(trailer.video_url).to eq(nil)
    #     expect(trailer.preview_image_url).to eq(nil)
    #     expect(trailer.full_sized_preview_image_url).to eq(nil)
    #     expect(trailer.device_type).to eq("ipad")
    #     expect(trailer.language).to eq("English")
    #   end

    #   # IDEA: can we detect trailer source change ?

    #   it "remove the video trailer" do
    #     count = ipad_trailers.count
    #     expect(count).to eq(1)
    #     version.upload_trailer!(nil, "English", 'ipad')
    #     count_after = ipad_trailers.count
    #     expect(count_after).to eq(count - 1)
    #   end
    # end
```

##### Complete output when running fastlane, including the stack trace and command used
I have the fastlane repo copied locally but I'm unsure how to actually run fastlane locally to be able to test the above mentioned commented code when it is uncommented.

One thing I'm not sure of is what folder structure I would need my deliver direction setup with to place trailers into them so they are automatically pulled.

Is this an Example how the folder structure should be?:
```
screenshots/
trailers?/en-US/1_ipadPro_english_01.000.mov?
metadata
Deliverfile
```

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.137.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday                   | 0.17.0       |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.3.1      |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.6.0        |
| bundler                   | 2.0.1        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| psych                     | 2.1.0.1      |
</details>

**Comment by max-ott** [comment]
@xhairbait The `spec` are test files and add no functionality to `spaceship` or `fastlane`.

To run/test `fastlane` locally, create a gemfile and add this line:

`gem "fastlane", path: "/path/to/fastlane"`

Then run `bundle install` to install it and `bundle exec YOUR COMMAND` to run you script.

**Comment by xhairbait** [comment]
Thank you for the info @max-ott

**Comment by q351941406** [comment]
+1

**Comment by xhairbait** [comment]
@max-ott should I name my local gem file something other than "fastlane" (like fastlane_local) or is it okay that it matches the actual gem name?

**Comment by max-ott** [comment]
@xhairbait Depends on your usage, you can use either of them.
