### ISSUE TITLE
Can no longer run fastlane under Catalina

### ISSUE THREAD

**Issue by kentcb** [fastlane/fastlane#15827]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I cannot run any fastlane command (including `fastlane env`) because I get the following security prompt:

![image](https://user-images.githubusercontent.com/1901832/71330586-920fc900-2579-11ea-9863-e6de3275eda9.png)

As text for accessibility and search:

> "libxml_ruby.bundle" cannot be opened because the developer cannot be verified.
>
> macOS cannot verify that this app is free from malware.
>
> Homebrew Cask downloaded this file on 5 October 2018 from fastlane.tools

I've already seen [this similar issue](https://github.com/fastlane/fastlane/issues/14860) and tried the workaround:

![image](https://user-images.githubusercontent.com/1901832/71330612-b9ff2c80-2579-11ea-8595-9b7c9ab08f6a.png)

However, it has no effect. No matter how many times I click **Allow Anyway**, I just get prompted again on the next run.

##### Command executed

It doesn't really matter: `fastlane env`, `fastlane help`, whatever - I get the same problem.

##### Complete output when running fastlane, including the stack trace and command used

Here's the output from `fastlane env --capture_output` if I click **Cancel** on both security prompts:

```
[11:48:17]: Seems like launching fastlane takes a while - please run
[11:48:17]: 
[11:48:17]: $ [sudo] gem cleanup
[11:48:17]: 
[11:48:17]: to uninstall outdated gems and make fastlane launch faster
[11:48:17]: Alternatively it's recommended to start using a Gemfile to lock your dependencies
[11:48:17]: To get started with a Gemfile, run
[11:48:17]: 
[11:48:17]: $ bundle init
[11:48:17]: $ echo 'gem "fastlane"' >> Gemfile
[11:48:17]: $ bundle install
[11:48:17]: 
[11:48:17]: After creating the Gemfile and Gemfile.lock, commit those files into version control
[11:48:17]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
WARN [2019-12-23 11:48:18.99]: Generating fastlane environment output, this might take a few seconds...
DEBUG [2019-12-23 11:48:19.31]: Checking if there are any plugins that should be loaded...
WARN [2019-12-23 11:48:19.36]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
INFO [2019-12-23 11:48:19.36]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅
```

### Environment

As mentioned above, I can't do this.

**Comment by kentcb** [comment]
Please ignore the bot: I cannot run `fastlane env`. See the issue for details.

**Comment by kentcb** [comment]
Tried uninstalling and reinstalling via brew but got this during the re-install:

```
Gems updated: slack-notifier atomos claide nanaimo xcodeproj rouge xcpretty terminal-notifier tty-screen tty-cursor tty-spinner commander-fastlane excon faraday faraday_middleware gh_inspector mini_magick rubyzip naturally simctl jwt memoist signet
Gems already up-to-date: fastlane
ERROR:  Error installing fastlane:
	signet requires Ruby version >= 2.4.0.
```

This is despite the fact that I have Ruby `2.6.3p62` installed. Apparently this issue is a thing and the only workaround I could find was uninstalling with brew and installing with `sudo gem install fastlane -NV` instead. Now `usr/local/bin/fastlane env` works just fine. However, this doesn't address the underlying issue. Installing with brew seems fundamentally broken.

**Comment by unfrgivn** [comment]
@kentcb did you get anywhere with this?  I'm encountering the same issue + versions as you
