### ISSUE TITLE
gym option "--silent" misunderstand

### ISSUE THREAD

**Issue by guzuqing** [fastlane/fastlane#15826]
the option doc show --silent :
Hide all information that's not necessary while building
but it doesn't , only thing it does is hide the printed command itself

i truly want the option '--silent' to reduce  the  command "xcodebuild" log,only show the error or warnning. like xcodebuild -quiet  do      which  is "do not print any output except for warnings and errors"

**Comment by guzuqing** [comment]
donot need  fastlane env

**Comment by codefei** [comment]
We hope this feature can be supported
