### ISSUE TITLE
Could not find action, lane or variable 'build_app'

### ISSUE THREAD

**Issue by AndreyMolochko** [fastlane/fastlane#15835]
Like issue was https://github.com/fastlane/fastlane/issues/15335
When i run lane i have this error :
Could not find action, lane or variable 'build_app'. Check out the documentation for more details: https://docs.fastlane.tools/actions.
There are actions _build_app_ and _build_ios_app_ in documentation. But when I run command `fastlane options` these commands are absent. I used the latest version of fastlane.

**Comment by AndreyMolochko** [comment]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description


##### Complete output when running fastlane, including the stack trace and command used




<details>
  <pre>[17:54:26]: fastlane finished with errors

[!] Could not find action, lane or variable 'build_app'. Check out the documentation for more details: https://docs.fastlane.tools/actions
</pre>
</details>

### Environment



<details>
  <pre>[17:54:26]: fastlane finished with errors

[!] Could not find action, lane or variable 'build_app'. Check out the documentation for more details: https://docs.fastlane.tools/actions
</pre>
</details>

**Comment by janpio** [comment]
What command did you run?
What is the content of that lane in your Fastfile?
What is you `fastlane env` output?

**Comment by mrinal-roy-au2** [comment]
I also had the same problem.

**Comment by anushkmittal** [comment]
bump. same issue

**Comment by jorgelub12** [comment]
Bump, same here !

**Comment by janpio** [comment]
Same questions for all of you then:

https://github.com/fastlane/fastlane/issues/15835#issuecomment-569326427

**Comment by mullerpeter** [comment]
Same issue on Mac OS 10.15 with fastlane installed via homebrew. 
Installing fastlane via gem solved it. 
`sudo gem install fastlane -NV`
