### ISSUE TITLE
[⠋] 🚀 bundler: failed to load command: fastlane (/Users/distiller/.gem/ruby/2.4.6/bin/fastlane)

### ISSUE THREAD

**Issue by oTranXuanDiep** [fastlane/fastlane#15832]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Command executed

![Screen Shot 2019-12-24 at 4 31 22 PM](https://user-images.githubusercontent.com/17880912/71406459-da5ae400-266a-11ea-9cf6-9b856de338ac.png)
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> CircleCI build failed when i change ruby version to v2.4.6 </pre>
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.138.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.21.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.6 (18G103)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | ~/Downloads/Xcode.app/Contents/Developer/                      |
| Xcode Version               | 10.2.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.14.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday                   | 0.17.1       |
| faraday_middleware        | 0.13.1       |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| simctl                    | 1.6.7        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| signet                    | 0.11.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.2        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.2        |
| tty-screen                | 0.7.0        |
| json                      | 2.3.0        |
| io-console                | 0.4.5        |
| excon                     | 0.71.1       |
| CFPropertyList            | 3.0.2        |
| libxml-ruby               | 2.9.0        |
| plist                     | 3.5.0        |
| claide                    | 1.0.3        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| babosa                    | 1.0.3        |
| fastimage                 | 2.1.7        |
| bundler                   | 2.1.1        |
| unicode-display_width     | 1.6.0        |
| googleauth                | 0.6.7        |
| addressable               | 2.7.0        |
| multi_json                | 1.14.1       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| psych                     | 2.1.0.1      |
| retriable                 | 3.1.2        |
| mime-types                | 3.3          |
| mime-types-data           | 3.2019.1009  |
</details>

*generated on:* **2019-12-24**
</details>

* I found the same issue https://github.com/fastlane/fastlane/issues/12301, but its not worked for me

**Comment by janpio** [comment]
How did you install fastlane?
Did you follow the documentation?

**Comment by oTranXuanDiep** [comment]
@janpio Yes, of course

**Comment by janpio** [comment]
Can you share your Circle CI config?

**Comment by oTranXuanDiep** [comment]
@janpio  This is circleci/config.yml file. Thanks
`
version: 2

jobs:
  build-and-test:

    macos:
      xcode: "10.2.1"

    shell: /bin/bash --login -eo pipefail

    steps:

      - checkout

      - restore_cache:
          keys:
            - submodule-cache
      - run:
          name: Check out Git submodules
          command: git submodule update --init --recursive
      - save_cache:
          key: submodule-cache
          paths:
            - ~/.gitclones

      - run:
          name: Install tools
          command: |
            bundle install
            brew update
            brew install awscli jq swiftlint

      - restore_cache:
          keys:
            - carthage-cache
      - run:
          name: Download pre-built dependencies
          command: script/download_archives_or_build.sh
      - save_cache:
          key: carthage-cache
          paths:
            - ~/Library/Caches/org.carthage.CarthageKit

      - run:
          name: Run tests
          command: bundle exec fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: MyScheme
      - store_artifacts:
          path: fastlane/test_output
          destination: fastlane/test_output
workflows:
  version: 2
  build:
    jobs:
      - build-and-test
`

**Comment by janpio** [comment]
Nothing obvious pops out to me, sry :/

Can you run it locally?

**Comment by ExternalReality** [comment]
You are likely not setting the appropriate working directory. Please check that you CCI job is set to the right working directory.
