### ISSUE TITLE
Clarification: How can I automate the command fastlane ios beta

### ISSUE THREAD

**Issue by nihp** [fastlane/fastlane#15843]
I am using fastlane to upload the build in tstflight.

Every time I need to manually run the 'fastlane ios beta' command to upload the build in testflight.

Here I have some questions kindly clarify

1. Can I able to automate the build without running **fastlane ios beta**
2. Also, before uploading to the testflight I need to verify the build in the real device. How can it possible?
3. If I use the same certificate to archive the build via Xcode means, Shall I able to install it in the real device.

**Comment by john-mejia** [comment]
Having a hard time understanding exactly what you mean - can you try to be more specific with what exactly you're trying to achieve?

**Comment by nihp** [comment]
Now we need to run the fastlane ios beta for every time to upload a build. But can I able to automate that.

**Comment by debeltranc** [comment]
Your question is too wide to be properly answered, I am assuming here that when you talk about `fastlane ios beta` you are talking about this piece of example in the documentation:
```lane :beta do
  sync_code_signing(type: "appstore")    # see code signing guide for more information
  build_app(scheme: "MyApp")
  upload_to_testflight
  slack(message: "Successfully distributed a new beta build")
end```

> Can I able to automate the build without running fastlane ios beta

Yes you can, this is a custom lane (I assume you know what a lane is). You can use actions as you like either from the fastfile or directly from a command line interface.

> Also, before uploading to the testflight I need to verify the build in the real device. How can it possible?

There are many options, the first one is straight from Xcode, no need to use Fastlane, then use your team's git flow. If you are talking about tests, Fastlane supports tools like appium, you can even upload to testflight to a internal tester group and test from there. The answer to this depends on what is your intention here, honestly. 

> If I use the same certificate to archive the build via Xcode means, Shall I able to install it in the real device.

I don't really understand this question, but I assume that you are struggling with code signing here, so please refer to Apple's and Fastlane's docs about code signing as this is a long topic on its own.

**Comment by nihp** [comment]
@debeltranc 



> Yes you can, this is a custom lane (I assume you know what a lane is). You can use actions as you like either from the fastfile or directly from a command line interface.

If I use actions means in which case it will trigger a build.(i.e) If I push my code changes to my git repo or I need to do any other thing to trigger this.



> The answer to this depends on what is your intention here, honestly.

Here I not need to handle it for tester initially. First I need to verify and if all things works good I need to upload the build for tester. 

For [3] 

In this case can I test it in real device if I generate ipa via Xcode with the same certificate which I used to upload build to testflight.

**Comment by debeltranc** [comment]
> If I use actions means in which case it will trigger a build.(i.e) If I push my code changes to my git repo or I need to do any other thing to trigger this.

I suspect you need a [CI engine](https://docs.fastlane.tools/best-practices/continuous-integration/) to do this, Fastlane does help wrapping some build and deploy steps, but it's not a CI/CD engine, read the link attached.

> First I need to verify and if all things works good then I need to upload the build for tester

This is a personal opinion: you don't need Fastlane for this, just build to device/simulator using Xcode. Now this but automatically sounds like unit and integration tests, [Fastlane supports some testing actions](https://docs.fastlane.tools/actions/#testing) that you might want to take look at.

> In this case can I test it in real device if I generate ipa via Xcode with the same certificate which I used to upload build to testflight.

This question has nothing to do with Fastlane and all I can tell you is that you shouldn't be able install a IPA file signed with a distribution certificate outside of the app store/Testflight. You may want to take a look at Ad-Hoc certificates in Apple docs.

I won't answer any more question in this issue unless you can show that you are trying to do something.

**Comment by nihp** [comment]
@debeltranc 

Thanks for your clarifications

**Comment by nihp** [comment]
@debeltranc 

Can you explain this little bit more

 You can use actions as you like either from the fastfile or directly from a command line interface.
