### ISSUE TITLE
[match] import does not support new Apple Distribution and Development certificates

### ISSUE THREAD

**Issue by terenceyan** [fastlane/fastlane#15857]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

```match import``` command does not appear to support the new Xcode 11 Development and Distribution certificate types. 

##### Command executed

I followed the usual ```match import``` as documented [here](https://docs.fastlane.tools/actions/match/#import)

##### Complete output when running fastlane, including the stack trace and command used

Taking a look at the importer, it doesn't look like it supports the new certificate types at all. 
https://github.com/fastlane/fastlane/blob/d9f057726f406a634a086a9b3c9be93146e74141/match/lib/match/importer.rb#L55-L62

Which uses ```Spaceship::ConnectAPI``` to fetch certificates for validation and those certificate models hasn't been updated to support Apple Distribution and Development certificates either.
https://github.com/fastlane/fastlane/blob/d9f057726f406a634a086a9b3c9be93146e74141/spaceship/lib/spaceship/connect_api/models/certificate.rb#L24-L32

### Environment

<details>
  <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.14.6                                          |
| Ruby                        | 2.6.5                                            |
| Bundler?                    | true                                             |
| Git                         | git version 2.21.0 (Apple Git-122.2)             |
| Installation Source         | ~/.rvm/gems/ruby-2.6.5/bin/fastlane              |
| Host                        | Mac OS X 10.14.6 (18G2022)                       |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.5/lib                     |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-11.3.app/Contents/Developer/ |
| Xcode Version               | 11.3                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.139.0 | ✅ Up-To-Date  |
</details>

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.17.3       |
| etc                       | 1.0.1        |
| forwardable               | 1.2.0        |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| coderay                   | 1.1.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.71.1       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.17.3       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.0.1        |
| signet                    | 0.12.0       |
| googleauth                | 0.10.0       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.4.1        |
| google-cloud-storage      | 1.25.0       |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.7        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.2        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.14.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-teams     | 0.2.0        |
| method_source             | 0.9.2        |
| pry                       | 0.12.2       |
</details>

**Comment by furkissh** [comment]
Same issue here, I can successfully create new certificates & profiles with match. But import not working on certificates. 
Xcode can't see the new certificates after I run `match development --readony` command.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.6.5                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0 (Apple Git-122.2)        |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.14.6 (18G1012)                  |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.5/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.3                                        |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.139.0 | ✅ Up-To-Date  |

*generated on:* **2020-01-08**
</details>

**Comment by terenceyan** [comment]
Later in the week, I'll make an attempt to try and add support for these new certificate types in ```Spaceship::ConnectAPI```. The API is returning these new certificates, but the type is missing from Apple's ConnectAPI documentation.

**Comment by ClaireDavis** [comment]
any update on this?

**Comment by rogerluan** [comment]
Closing this ticket as https://github.com/fastlane/fastlane/pull/16041 got merged and released a long time ago 🤗 🚀
