### ISSUE TITLE
Coding signing using old provisioning profile

### ISSUE THREAD

**Issue by ivanchaukn** [fastlane/fastlane#15853]
### Issue Description

For some reason the code signing part kept referring to a provisioning profile that has already been revoked and deleted locally. Is there some cache that I should delete? I tried running xcclean and clear_derived_data but I'm still getting the same problem.

I'm using match to handle all my certificates and profiles and I manually set the provisioning profiles for my release builds to the appstore distribution profile.

##### Command executed
`fastlane beta`

```
default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore", readonly: true)
    build_ios_app(export_method: 'app-store', scheme: "production")
    upload_to_testflight
  end
end
```

##### Complete output when running fastlane, including the stack trace and command used
```
[12:30:32]: ▸ Check dependencies
[12:30:32]: ▸ Code Signing Error: No profile for team 'TEAM_ID' matching 'OLD_PROFILE_NAME' found:  Xcode couldn't find any provisioning profiles matching 'TEAM_ID/OLD_PROFILE_NAME. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the Signing & Capabilities tab of the target editor.
[12:30:32]: ▸ Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 13.2'
[12:30:32]: ▸ Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 13.2'
[12:30:32]: ▸ Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 13.2'
```

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.2                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.21.0 (Apple Git-122.2)                           |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.2 (19C57)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.3                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore", readonly: true)
    build_ios_app(export_method: 'app-store', scheme: "production")
    upload_to_testflight
  end
end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.139.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.13.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.2        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.71.1       |
| faraday                   | 0.17.1       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.7        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.9.0        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.3       |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.4.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>

*generated on:* **2020-01-04**
</details>

**Comment by alexcroox** [comment]
I think I might be running into this issue too (fastlane version 2.139.0)

```
match(type: "development")

    # Build the app
    gym(
      scheme: "App",
      clean: true,
      export_method: 'development'
    )
```

```
-----------------
[19:54:22]: --- Step: gym ---
[19:54:22]: -----------------
[19:54:22]: $ xcodebuild -showBuildSettings -workspace ios/App/App.xcworkspace -scheme App
[19:54:24]: Detected provisioning profile mapping: {:"xxx.xxx.xxx"=>"match Development xxx.xxx.xxx"}

+------------------------------------------------------+--------------------------------------------------------------+
|                                               Summary for gym 2.139.0                                               |
+------------------------------------------------------+--------------------------------------------------------------+
| scheme                                               | App                                                          |
| clean                                                | true                                                         |
| export_method                                        | ***********                                                  |
| skip_profile_detection                               | true                                                         |
| export_options.compileBitcode                        | false                                                        |
| export_options.provisioningProfiles.xxx.xxx.xxx | match Development xxx.xxx.xxx                           |
| workspace                                            | ios/App/App.xcworkspace                                      |
| destination                                          | generic/platform=iOS                                         |
| output_name                                          | App                                                          |
| build_path                                           | /Users/distiller/Library/Developer/Xcode/Archives/2020-01-05 |
| output_directory                                     | output/gym                                                   |
| silent                                               | false                                                        |
| skip_package_ipa                                     | false                                                        |
| result_bundle                                        | false                                                        |
| buildlog_path                                        | output/buildlogs/gym                                         |
| xcode_path                                           | /Applications/Xcode-11.2.1.app                               |
+------------------------------------------------------+--------------------------------------------------------------+
```

```
+---------------+--------------------------------+
|               Build environment                |
+---------------+--------------------------------+
| xcode_path    | /Applications/Xcode-11.2.1.app |
| gym_version   | 2.139.0                        |
| export_method | ***********                    |
| sdk           | iPhoneOS13.2.sdk               |
+---------------+--------------------------------+

[19:55:18]: ▸ === BUILD TARGET App OF PROJECT App WITH CONFIGURATION Release ===
[19:55:18]: ▸ Check dependencies
[19:55:18]: ▸ Code Signing Error: No profile for team 'JUAJxxxxxx' matching 'match AppStore xxx.xxx.xxx' found:  Xcode couldn't find any provisioning profiles matching 'JUAJxxxxxx/match AppStore xxx.xxx.xxx'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the Signing & Capabilities tab of the target editor.
```

As you can see everything leading up to the gym execution states **Development**, but the error is **AppStore**. Searching my logs the only place AppStore is mentioned is in that 2 line error.
