### ISSUE TITLE
Unexpected applicationNotFound: No application was found for the given package name

### ISSUE THREAD

**Issue by markymc** [fastlane/fastlane#15858]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

@janpio [asked me to create this issue](https://github.com/fastlane/fastlane/issues/15648#issuecomment-562955131) due to my [comment](https://github.com/fastlane/fastlane/issues/15648#issuecomment-562912434) about this problem.

In a nutshell, I had uploaded an AAB to the Play Console under our internal test track, but received the `Google Api Error: applicationNotFound: No application was found for the given package name. - No application was found for the given package name.` error.

This was unexpected, as an existing build was already there. As noted in my comment: "I'm wondering if it's because our app is showing as "Processing update" on the Dashboard page, which is related to the new app review process at Google it seems."

##### Command executed

A Fastlane lane that built and used `supply` to upload the build to the Play Store.

##### Complete output when running fastlane, including the stack trace and command used

I'm sorry I don't have this now.

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.19.1                          |
| Installation Source         | ~/.rbenv/versions/2.5.1/bin/fastlane        |
| Host                        | Mac OS X 10.14.6 (18G1012)                  |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2o  27 Mar 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.2.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_version '2.137.0'

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "./ios/MyApp.xcodeproj")
    build_app(workspace: "./ios/MyApp.xcworkspace", scheme: "MyApp")
    # upload_symbols_to_crashlytics
    upload_to_testflight
  end
end

platform :android do
  desc 'Push a new beta build to Google Play'
  lane :beta do
    increment_version_code(gradle_file_path: 'android/app/build.gradle')
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')
    supply(track: 'internal', json_key: 'android/myapp-android-upload-key.json', package_name: 'com.myapp.myapp')
  end
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.139.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                 | Version | Update-Status |
| -------------------------------------- | ------- | ------------- |
| fastlane-plugin-increment_version_code | 0.4.3   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                    | Version      |
| -------------------------------------- | ------------ |
| did_you_mean                           | 1.2.0        |
| slack-notifier                         | 2.3.2        |
| rouge                                  | 2.0.7        |
| xcpretty                               | 0.3.0        |
| terminal-notifier                      | 2.0.0        |
| terminal-table                         | 1.8.0        |
| plist                                  | 3.5.0        |
| CFPropertyList                         | 3.0.2        |
| multipart-post                         | 2.0.0        |
| word_wrap                              | 1.0.0        |
| public_suffix                          | 2.0.5        |
| tty-screen                             | 0.7.0        |
| babosa                                 | 1.0.3        |
| colored                                | 1.2          |
| highline                               | 1.7.10       |
| commander-fastlane                     | 4.4.6        |
| excon                                  | 0.71.1       |
| http-cookie                            | 1.0.3        |
| faraday-cookie_jar                     | 0.0.6        |
| faraday_middleware                     | 0.13.1       |
| fastimage                              | 2.1.7        |
| gh_inspector                           | 1.1.3        |
| mini_magick                            | 4.9.5        |
| multi_xml                              | 0.6.0        |
| rubyzip                                | 1.3.0        |
| security                               | 0.1.3        |
| xcpretty-travis-formatter              | 1.0.0        |
| dotenv                                 | 2.7.5        |
| jwt                                    | 2.1.0        |
| uber                                   | 0.1.0        |
| declarative                            | 0.0.10       |
| declarative-option                     | 0.1.0        |
| representable                          | 3.0.4        |
| retriable                              | 3.1.2        |
| signet                                 | 0.12.0       |
| memoist                                | 0.16.2       |
| os                                     | 1.0.1        |
| googleauth                             | 0.10.0       |
| httpclient                             | 2.8.3        |
| google-api-client                      | 0.36.3       |
| emoji_regex                            | 1.0.1        |
| nanaimo                                | 0.2.6        |
| colored2                               | 3.1.2        |
| claide                                 | 1.0.3        |
| atomos                                 | 0.1.3        |
| xcodeproj                              | 1.14.0       |
| unicode-display_width                  | 1.6.0        |
| addressable                            | 2.7.0        |
| tty-cursor                             | 0.7.0        |
| tty-spinner                            | 0.9.2        |
| faraday                                | 0.17.3       |
| unf_ext                                | 0.0.7.6      |
| unf                                    | 0.1.4        |
| domain_name                            | 0.5.20190701 |
| json                                   | 2.3.0        |
| bundler                                | 1.16.6       |
| naturally                              | 2.2.0        |
| simctl                                 | 1.6.7        |
| mini_mime                              | 1.0.2        |
| multi_json                             | 1.14.1       |
| digest-crc                             | 0.4.1        |
| google-cloud-env                       | 1.3.0        |
| google-cloud-core                      | 1.4.1        |
| google-cloud-storage                   | 1.25.0       |
| openssl                                | 2.1.0        |
| date                                   | 1.0.0        |
| fileutils                              | 1.0.2        |
| mini_portile2                          | 2.3.0        |
| nokogiri                               | 1.8.5        |
| ipaddr                                 | 1.2.0        |
| psych                                  | 3.0.2        |
| fastlane-plugin-increment_version_code | 0.4.3        |
</details>

*generated on:* **2020-01-07** </pre>
</details>

**Comment by fredattack** [comment]
hi markync, 
Did you find a solution for this? 
I add to upload manually the first build, but i would like to use this method for the next release. 

THX

**Comment by markymc** [comment]
@fredattack After getting approval from Google things seemed to be working fine. So perhaps just wait until you get approval?

**Comment by minuscorp** [comment]
Is this still an issue? Or can be closed

**Comment by markymc** [comment]
I can't confirm I'm afraid. Perhaps it can be closed until someone else reports it?

**Comment by minuscorp** [comment]
Let's close this for now and wait if someone else raises it again in the future 😄
