### ISSUE TITLE
 Plugin 'GetVersionName' overwrites already loaded action 'get_version_name'

### ISSUE THREAD

**Issue by YogeshByndoor** [fastlane/fastlane#15852]
[✔] 🚀
[19:32:11]: fastlane detected a Gemfile in the current directory
[19:32:11]: However, it seems like you didn't use `bundle exec`
[19:32:11]: To launch fastlane faster, please use
[19:32:11]:
[19:32:11]: $ bundle exec fastlane env
[19:32:11]:
[19:32:11]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[19:32:14]: Generating fastlane environment output, this might take a few seconds...
[19:33:15]: Plugin 'GetVersionName' overwrites already loaded action 'get_version_name'
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                        |
| --------------------------- | ---------------------------- |
| OS                          | UNKNOWN                      |
| Ruby                        | 2.6.4                        |
| Bundler?                    | false                        |
| Git                         | git version 2.21.0.windows.1 |
| Installation Source         | C:/Ruby26-x64/bin/fastlane   |
| Host                        | Unknown  ()                  |
| Ruby Lib Dir                | C:/Ruby26-x64/lib            |
| OpenSSL Version             | OpenSSL 1.1.1c  28 May 2019  |
| Is contained                | false                        |
| Is homebrew                 | false                        |
| Is installed via Fabric.app | false                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.139.0 | 💥 Check failed |

### Loaded fastlane plugins:

| Plugin                           | Version | Update-Status  |
| -------------------------------- | ------- | -------------- |
| fastlane-plugin-get_version_name | 0.2.2   | 💥 Check failed |
| fastlane-plugin-get_version_name | 0.2.2   | 💥 Check failed |

<details><summary><b>Loaded gems</b></summary>

| Gem                              | Version      |
| -------------------------------- | ------------ |
| did_you_mean                     | 1.3.0        |
| slack-notifier                   | 2.3.2        |
| atomos                           | 0.1.3        |
| CFPropertyList                   | 3.0.2        |
| claide                           | 1.0.3        |
| colored2                         | 3.1.2        |
| nanaimo                          | 0.2.6        |
| xcodeproj                        | 1.14.0       |
| rouge                            | 2.0.7        |
| xcpretty                         | 0.3.0        |
| terminal-notifier                | 2.0.0        |
| unicode-display_width            | 1.6.0        |
| terminal-table                   | 1.8.0        |
| plist                            | 3.5.0        |
| public_suffix                    | 2.0.5        |
| addressable                      | 2.7.0        |
| multipart-post                   | 2.0.0        |
| word_wrap                        | 1.0.0        |
| tty-screen                       | 0.7.0        |
| tty-cursor                       | 0.7.0        |
| tty-spinner                      | 0.9.2        |
| babosa                           | 1.0.3        |
| colored                          | 1.2          |
| highline                         | 1.7.10       |
| commander-fastlane               | 4.4.6        |
| unf_ext                          | 0.0.7.6      |
| unf                              | 0.1.4        |
| domain_name                      | 0.5.20190701 |
| http-cookie                      | 1.0.3        |
| faraday-cookie_jar               | 0.0.6        |
| faraday_middleware               | 0.13.1       |
| fastimage                        | 2.1.7        |
| gh_inspector                     | 1.1.3        |
| mini_magick                      | 4.9.5        |
| multi_xml                        | 0.6.0        |
| rubyzip                          | 1.3.0        |
| security                         | 0.1.3        |
| xcpretty-travis-formatter        | 1.0.0        |
| dotenv                           | 2.7.5        |
| bundler                          | 1.17.2       |
| jwt                              | 2.1.0        |
| uber                             | 0.1.0        |
| declarative                      | 0.0.10       |
| declarative-option               | 0.1.0        |
| representable                    | 3.0.4        |
| retriable                        | 3.1.2        |
| mini_mime                        | 1.0.2        |
| multi_json                       | 1.14.1       |
| signet                           | 0.12.0       |
| httpclient                       | 2.8.3        |
| google-api-client                | 0.36.3       |
| emoji_regex                      | 1.0.1        |
| excon                            | 0.71.1       |
| faraday                          | 0.17.3       |
| json                             | 2.3.0        |
| naturally                        | 2.2.0        |
| simctl                           | 1.6.7        |
| os                               | 1.0.1        |
| memoist                          | 0.16.2       |
| googleauth                       | 0.10.0       |
| digest-crc                       | 0.4.1        |
| google-cloud-env                 | 1.3.0        |
| google-cloud-core                | 1.4.1        |
| google-cloud-storage             | 1.25.0       |
| forwardable                      | 1.2.0        |
| logger                           | 1.3.0        |
| stringio                         | 0.0.2        |
| ipaddr                           | 1.2.2        |
| openssl                          | 2.1.2        |
| ostruct                          | 0.1.0        |
| strscan                          | 1.0.0        |
| fiddle                           | 1.0.0        |
| date                             | 2.0.0        |
| fileutils                        | 1.1.0        |
| etc                              | 1.0.1        |
| zlib                             | 1.0.0        |
| mini_portile2                    | 2.4.0        |
| nokogiri                         | 1.10.4       |
| rexml                            | 3.1.9        |
| psych                            | 3.1.0        |
| mutex_m                          | 0.1.0        |
| fastlane-plugin-get_version_name | 0.2.2        |
</details>

*generated on:* **2020-01-02**
</details>
[19:35:15]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[19:35:15]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅

**Comment by janpio** [comment]
Uh, do not use the plugin then? Which plugin is this in the first place?
