### ISSUE TITLE
upload_to_app_store："Selecting the latest build..." Then "ITC.response.error.OPERATION_FAILED"

### ISSUE THREAD

**Issue by fabcz** [fastlane/fastlane#15859]
### Question Checklist

- [✅] Updated fastlane to the latest version
- [✅] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [✅] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [✅] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

upload_to_app_store

#### fastlane env
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.1                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.21.0 (Apple Git-122.2)                           |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.1 (19B88)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.2.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

default_platform :ios

platform :ios do
  before_all do
    sh 'chmod 755 ../CIScript/preBuild.sh'
    sh '../CIScript/preBuild.sh'
    sh 'export FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT=30'

    # 设置当前打包时间
    set_info_plist_value(path: "./EasiPass/Supporting Files/Info.plist", key: "BuildTimestamp", value: Time.new.strftime("%m-%d %H:%M"))

    # 累加当前 build
    oldBuild = get_info_plist_value(path: "./EasiPass/Supporting Files/Info.plist", key: "CFBundleVersion")
    if (oldBuild.length == 8)
      currentTime = Time.new.strftime("%y%m%d")
      newBuild = ""
      if (currentTime.eql?(oldBuild[0..5]))
        lastNum = (oldBuild[-2..-1].to_i + 1).to_s
        newBuild = currentTime + (lastNum.length == 2 ? lastNum : ("0" + lastNum))
      else
        newBuild = currentTime + "01"
      end
      set_info_plist_value(path: "./EasiPass/Supporting Files/Info.plist", key: "CFBundleVersion", value: newBuild)
    end
  
  end

 desc "打包、上传、提审、备份、标签 一条龙🐲"
  lane :production do |options|

    if (options[:InitServerURLKey])
      set_info_plist_value(path: "./EasiPass/Supporting Files/Info.plist", key: "InitServerURLKey", value: options[:InitServerURLKey])
    end

    if (options[:Archive])
        gym(
          scheme: "EasiPass",
          clean: true,
          silent: true,
          build_path: "./build/",
          output_directory: "./build/",
          configuration: "Release")
    end

    if (options[:Upload] || options[:SubmitReview])
      upload_to_app_store(
        force: true,
        skip_screenshots: true,
        ipa: "./build/EasiPass.ipa",
        precheck_include_in_app_purchases: false,
        run_precheck_before_submit: false,
        skip_binary_upload: !options[:Upload],
        app_version: get_info_plist_value(path: "./EasiPass/Supporting Files/Info.plist", key: "sys-clientVersion"),
        submit_for_review: options[:SubmitReview],
        submission_information: {    
          export_compliance_encryption_updated: false,
          export_compliance_uses_encryption: false,
          content_rights_contains_third_party_content: false,
          add_id_info_uses_idfa: false},
        release_notes: {
          'zh-Hans' => options[:ReleaseNote],
          'zh-Hant' => options[:ReleaseNote],
          'en-AU' => options[:ReleaseNote],
          'en-US' => options[:ReleaseNote],
          'en-GB' => options[:ReleaseNote]}
      )
    end

    if (options[:Backup])
        #读取 Build 值
        verion_number = get_info_plist_value(path: "./EasiPass/Supporting Files/Info.plist", key: "sys-clientVersion")
        build_number = get_info_plist_value(path: "./EasiPass/Supporting Files/Info.plist", key: "CFBundleVersion")
        #复制的目录
        work_path = Pathname.getwd.dirname.to_s
        output_path = work_path + "/Release/"
        sh("rm", "-rf", output_path)
        upload_path = output_path + verion_number + "." + build_number
        sh("mkdir", output_path)
        sh("mkdir", upload_path)
        #sh 执行命令必须全路径
        ipa_path = work_path + "/build/EasiPass.ipa"
        ipa_appstore_upload = upload_path + "/EasiPass" + verion_number +"_AppStore.ipa" 
        sh("cp", ipa_path, ipa_appstore_upload)
        # 备份符号表
        symbol_path = work_path + "/build/EasiPass.app.dSYM.zip"
        symbol_upload = upload_path + "/EasiPass" + verion_number +".app.dSYM.zip" 
        sh("cp", symbol_path, symbol_upload)
    end
  end

  after_all do |lane, options|
    # 提交代码
    if options[:BuildFor] 
      if (options[:BuildFor].include?"origin")
        git_commit(path: "./EasiPass/Supporting Files/Info.plist", message: "[Modify] 更新打包时间、提升 buildnumber")
      end
    else
      git_commit(path: "./EasiPass/Supporting Files/Info.plist", message: "[Modify] 更新打包时间、提升 buildnumber")
    end
    
  end

  error do |lane, exception|
    
  end
end




```
</details>

<details><summary>`./fastlane/Appfile`</summary>
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.139.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                | Version | Update-Status |
| --------------------- | ------- | ------------- |
| fastlane-plugin-pgyer | 0.2.2   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.13.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.71.1       |
| faraday                   | 0.17.1       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.1       |
| os                        | 1.0.1        |
| googleauth                | 0.9.0        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.3       |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.4.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| CFPropertyList            | 3.0.1        |
| json                      | 2.2.0        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| fastlane-plugin-pgyer     | 0.2.2        |
</details>

*generated on:* **2020-01-07**
</details>

Console Output
```
[21:19:05]: Making sure the latest version on App Store Connect matches '3.0.10' from the ipa file...
[21:19:11]: [32m'3.0.10' is the latest version on App Store Connect[0m
[21:19:29]: Activating languages zh-Hans, zh-Hant, en-AU, en-US, en-GB...
[21:19:39]: Uploading metadata to App Store Connect
[21:19:43]: [32mSuccessfully uploaded set of metadata to App Store Connect[0m
[21:19:43]: Uploading binary to App Store Connect
[21:19:44]: Going to upload updated app to App Store Connect
[21:19:44]: [32mThis might take a few minutes. Please don't interrupt the script.[0m
[21:26:38]: [32miTunes Transporter successfully finished its job[0m
[21:26:38]: [32m--------------------------------------------------------------------[0m
[21:26:38]: [32mSuccessfully uploaded package to App Store Connect. It might take a few minutes until it's visible online.[0m
[21:26:38]: [32m--------------------------------------------------------------------[0m
[21:26:38]: [32mFinished the upload to App Store Connect[0m
[21:26:46]: Selecting the latest build...
+-----------------------------------+----------------------------------------------------------------------------------------+
|                                                        [33mLane Context[0m                                                        |
+-----------------------------------+----------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM                  | ios                                                                                    |
| PLATFORM_NAME                     | ios                                                                                    |
| LANE_NAME                         | ios production                                                                         |
| GET_INFO_PLIST_VALUE_CUSTOM_VALUE | 3.0.10                                                                                 |
| IPA_OUTPUT_PATH                   | /Users/slave/ci/workspace/EasiCare_iOS/EasiCare_iOS_Master/build/EasiPass.ipa          |
| DSYM_OUTPUT_PATH                  | /Users/slave/ci/workspace/EasiCare_iOS/EasiCare_iOS_Master/build/EasiPass.app.dSYM.zip |
| XCODEBUILD_ARCHIVE                | ./build/EasiPass 2020-01-06 21.15.53.xcarchive                                         |
+-----------------------------------+----------------------------------------------------------------------------------------+
[21:26:47]: [31mITC.response.error.OPERATION_FAILED[0m

+------+------------------------------------------------+-------------+
|                          [32mfastlane summary[0m                           |
+------+------------------------------------------------+-------------+
| Step | Action                                         | Time (in s) |
+------+------------------------------------------------+-------------+
| 1    | default_platform                               | 0           |
| 2    | chmod 755 ../CIScript/preBuild.sh              | 0           |
| 3    | ../CIScript/preBuild.sh                        | 0           |
| 4    | export FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT=30 | 0           |
| 5    | set_info_plist_value                           | 0           |
| 6    | get_info_plist_value                           | 0           |
| 7    | set_info_plist_value                           | 0           |
| 8    | gym                                            | 191         |
| 9    | get_info_plist_value                           | 0           |
| 💥   | [31mupload_to_app_store[0m                            | 479         |
+------+------------------------------------------------+-------------+

[21:26:47]: [31mfastlane finished with errors[0m
```

**Comment by MarkChrisLevy** [comment]
@fabcz Try today - yesterday I had the same issue, but today it works fine, so very likely it wasn't Fastlane fault, but rater some issue with Apple.

**Comment by fabcz** [comment]
@MarkChrisLevy  Finally, I manually submitted a review in the App Store Connect, and I will try again the next time I submit a review, Thank for your reply.

**Comment by fabcz** [comment]
@MarkChrisLevy I tried then had same problem

**Comment by mohamedfarid1993** [comment]
@fabcz I have the same issue in more than one project, did you find a solution ?

**Comment by fabcz** [comment]
@mohamedfarid1993 I haven't found a solution yet

**Comment by rgbdelta** [comment]
@fabcz 
I have a fastlane plugin here that uses the official app store connect api to upload your app. You just need to configure an api key for it. It's new but app uploading is really quick and hasn't given me any problems.

https://github.com/blitzm-systems/Connected
