### ISSUE TITLE
How to make a spaceship script? (And Documentation Suggestions/Feedback)

### ISSUE THREAD

**Issue by thejeff77** [fastlane/fastlane#15854]
### Question Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

Hey all, I've been reading and searching the docs for a long time, and I'm having trouble figuring out how to create a spaceship script. 

The docs clearly show how to play around with it using "spaceship playground" - I.E. run "fastlane spaceship", which is great for figuring out commands, however I would love to create a script. 

The docs even say that "as most fastlane users won't need the spaceship playground"...

So.. it would be amazing to have any info on how to script this. For example: can I login with the playground, then just run a bash script that starts with "fastlane spaceship" and the commands will run fine? 

Thanks for any help or links - googling "create fastlane script" or "create fastlane spaceship script" are surprisingly useless. 

Further helpful information on the main page would be:
 - how to pass in command line vars to a script. 
 - How to create a new version (in addition to (or instead of) a new app which happens once ever) (app.create_version!("1.0.0"))
 - Links to the extended API docs located at: https://www.rubydoc.info/github/fastlane/spaceship
 - Put these links on the main page! lol - https://github.com/fastlane/fastlane/blob/master/spaceship/docs/README.md

If you can help me with some of my scripting questions, and/or provide feedback, I'd like to fix up the docs a bit to add more info that I would have found extremely helpful as a first time user. Seems like finding some simple stuff is a bit harder than it should be in my opinion (trying to figure this out for the first time). 

Thanks! And I look forward to any reply!

**Comment by thejeff77** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.2                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.14.1                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.2 (19C57)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.3                                                           |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "PracticePlayer.xcodeproj")
    build_app(scheme: "PracticePlayer")
    upload_to_app_store
  end
end

```
</details>

<details><summary>`./Appfile`</summary>

```ruby
app_identifier("com.MFE.PracticePlayer") # The bundle identifier of your app
apple_id("inflatedwizard@gmail.com") # Your Apple email address

itc_team_id("119057288") # App Store Connect Team ID
team_id("ZAR5QX7MAH") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.139.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.14.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.2        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.71.1       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.7        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.10.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.3       |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.4.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.25.0       |
| emoji_regex               | 1.0.1        |
| CFPropertyList            | 3.0.2        |
| faraday                   | 0.17.3       |
| json                      | 2.3.0        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>


*generated on:* **2020-01-05**
</details>

**Comment by debeltranc** [comment]
Spaceship is just the underlying ruby gem that most Fastlane actions use, what I've done in the past is just create a ruby script and importing the gem into my code, i.e:
`require "spaceship"`

While I agree with you that the documentation is rather limited and some stuff like in app purchases and the likes is present but undocumented, I've had no problem digging into the source code. Also to use Spaceship directly instead of Fastlane you should have a very specific use case, hence the lack of available information. Have you seen this [documentation pages](https://github.com/fastlane/fastlane/tree/master/spaceship/docs)? While it might not seem to be too much, it's a really good starting point.

**Comment by thejeff77** [comment]
Cool thanks guys, figured it out. 

My confusion from reading the docs was related to the intro - I.E. "It powers parts of fastlane". 

It wasn't clear to me that this wasn't a plugin or something you have to add or use. 

Might be cool to add something in like "To use this, you don't have to do anything! Just install and setup fastlane for your app: <Fastlane init guide>. You'd reference this library to make any custom or advanced workflows you want via fastlane's custom action feature for anything that isn't already built into fastlane for you.

Or "if you don't have fastlane, you're missing the point"

I dunno, just a few tidbits. It was definitely my misunderstanding, but sometimes the new guy's impression of confusions can help future comers.
