### ISSUE TITLE
Setting environment variables for `capture_screenshots`?

### ISSUE THREAD

**Issue by janoist1** [fastlane/fastlane#15868]
Is it possible to set environment variables for `capture_screenshots`?

I've tried the following which did not work:
```
...
lane :release do
    ENV["env"] = "production"
    ENV['ENVFILE'] = '.env.production'
    capture_screenshots
...
```

`fastlane env`:
```
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.1                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0 (Apple Git-122.2)        |
| Installation Source         | ~/.rbenv/versions/2.4.0/bin/fastlane        |
| Host                        | Mac OS X 10.15.1 (19B88)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.0/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.2.1                                      |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   | en_GB.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.3"

default_platform :ios

platform :ios do
  before_all do
    #cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    ENV["ENV"] = "beta"
    ENV["APP_ENV"] = "beta"
    ENV["NODE_ENV"] = "beta"
    ENV['ENVFILE'] = '.env.beta'

    #get_certificates           # invokes cert
    #get_provisioning_profile   # invokes sigh
    #build_app

    xcode_select '/Applications/Xcode.app'

    # match(type: "appstore") # more information: https://codesigning.guide

    increment_build_number(xcodeproj: './ios/novus.xcodeproj')

    #gym # Build your app - more options available
    gym(scheme: 'novus', workspace: './ios/novus.xcworkspace', export_xcargs: "-allowProvisioningUpdates")
    #gym(scheme: 'novus', project: './ios/novus.xcodeproj')
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    ENV["env"] = "production"
    ENV['ENVFILE'] = '.env.production'

    # match(type: "appstore")
    # snapshot
    #gym # Build your app - more options available
    # gym(scheme: 'novus', project: './ios/novus.xcodeproj')
    # deliver(force: true)
    # frameit

    capture_screenshots                  # generate new screenshots for the App Store
    # sync_code_signing(type: "appstore")  # see code signing guide for more information
    # build_app(scheme: "MyApp")
    # upload_to_app_store                  # upload your app to App Store Connect
    # slack(message: "Successfully uploaded a new App Store build")

    # build_app(scheme: "MyApp",
    #         workspace: "Example.xcworkspace",
    #         include_bitcode: true)
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

platform :android do

  desc "Submit a new Beta Build"
  lane :beta do
    increment_version_code(
        gradle_file_path: "project/build.gradle",
        #ext_constant_name: "test"
        #app_folder_name:"app"
    )
  end
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby

json_key_file "./android/api-8722831967664452581-915374-888b18ff251a.json"

app_identifier "com.heroteam.novus" # The bundle identifier of your app
apple_id "istvan@heroteam.io" # Your Apple email address

package_name "com.heroteam.novus"

#team_id "heroteam" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.140.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                 | Version | Update-Status |
| -------------------------------------- | ------- | ------------- |
| fastlane-plugin-increment_version_code | 0.4.3   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                    | Version      |
| -------------------------------------- | ------------ |
| did_you_mean                           | 1.1.0        |
| atomos                                 | 0.1.3        |
| CFPropertyList                         | 3.0.2        |
| claide                                 | 1.0.3        |
| colored2                               | 3.1.2        |
| nanaimo                                | 0.2.6        |
| xcodeproj                              | 1.13.0       |
| rouge                                  | 2.0.7        |
| xcpretty                               | 0.3.0        |
| terminal-notifier                      | 2.0.0        |
| terminal-table                         | 1.8.0        |
| plist                                  | 3.5.0        |
| multipart-post                         | 2.0.0        |
| word_wrap                              | 1.0.0        |
| public_suffix                          | 2.0.5        |
| tty-screen                             | 0.7.0        |
| tty-cursor                             | 0.7.0        |
| tty-spinner                            | 0.9.2        |
| babosa                                 | 1.0.3        |
| colored                                | 1.2          |
| highline                               | 1.7.10       |
| commander-fastlane                     | 4.4.6        |
| excon                                  | 0.71.0       |
| unf_ext                                | 0.0.7.6      |
| unf                                    | 0.1.4        |
| domain_name                            | 0.5.20190701 |
| http-cookie                            | 1.0.3        |
| faraday-cookie_jar                     | 0.0.6        |
| faraday                                | 0.17.1       |
| faraday_middleware                     | 0.13.1       |
| fastimage                              | 2.1.7        |
| gh_inspector                           | 1.1.3        |
| mini_magick                            | 4.9.5        |
| multi_xml                              | 0.6.0        |
| rubyzip                                | 1.3.0        |
| security                               | 0.1.3        |
| xcpretty-travis-formatter              | 1.0.0        |
| naturally                              | 2.2.0        |
| simctl                                 | 1.6.6        |
| jwt                                    | 2.1.0        |
| uber                                   | 0.1.0        |
| declarative                            | 0.0.10       |
| declarative-option                     | 0.1.0        |
| representable                          | 3.0.4        |
| retriable                              | 3.1.2        |
| mini_mime                              | 1.0.2        |
| signet                                 | 0.12.0       |
| memoist                                | 0.16.2       |
| os                                     | 1.0.1        |
| googleauth                             | 0.9.0        |
| httpclient                             | 2.8.3        |
| google-api-client                      | 0.36.4       |
| google-cloud-env                       | 1.3.0        |
| google-cloud-core                      | 1.4.1        |
| digest-crc                             | 0.4.1        |
| google-cloud-storage                   | 1.16.0       |
| emoji_regex                            | 1.0.1        |
| openssl                                | 2.0.2        |
| json                                   | 2.3.0        |
| io-console                             | 0.4.6        |
| mini_portile2                          | 2.1.0        |
| nokogiri                               | 1.7.2        |
| bundler                                | 2.1.0.pre.3  |
| unicode-display_width                  | 1.6.0        |
| dotenv                                 | 2.7.5        |
| addressable                            | 2.7.0        |
| multi_json                             | 1.14.1       |
| psych                                  | 2.2.2        |
| fastlane-plugin-increment_version_code | 0.4.3        |
</details>

*generated on:* **2020-01-09**
</details>
```

Thanks.

**Comment by janpio** [comment]
Where should these env vars be available?

**Comment by janoist1** [comment]
Thanks for coming back, but I'm no longer using Fastlane's `screenshot` due to switching to Detox testing which allows me to make cross platform screenshots.
