### ISSUE TITLE
[gym] Exporting .ipa from .xcarchive requires project path

### ISSUE THREAD

**Issue by MartinGonzalez** [fastlane/fastlane#15876]
- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I want to export from an existing .xcarchive a .ipa file without specifying the project. When I run gym with `skip_build_archive: true` and `skip_archive: true` it's asking me where the project is.

##### Command executed
```ruby
gym({
    export_team_id: 'MY_TEAM_ID',
    skip_build_archive: true,
    skip_archive: true,
    output_directory: './ios/ad-hoc',
    include_symbols: false,
    output_name: 'ad-hoc.ipa',
    archive_path: "/Users/martingonzalez/Library/Developer/Xcode/Archives/2020-01-10/4.6.4-2.xcarchive",
    export_options: {
      method: 'ad-hoc',
      provisioningProfiles: { 
        "com.mycompany.myproduct" => "com.mycompany.myproduct AdHoc",       
      }
    }
  })
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [18:42:56]: Driving the lane 'test_gym' 🚀
[18:42:56]: -----------------
[18:42:56]: --- Step: gym ---
[18:42:56]: -----------------
[18:42:56]: Couldn't automatically detect the project file, please provide a path: </pre>
</details>

### Environment

```
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                |
| --------------------------- | ------------------------------------ |
| OS                          | 10.14.6                              |
| Ruby                        | 2.6.5                                |
| Bundler?                    | true                                 |
| Git                         | git version 2.20.1 (Apple Git-117)   |
| Installation Source         | ~/.rbenv/versions/2.6.5/bin/fastlane |
| Host                        | Mac OS X 10.14.6 (18G2022)           |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.5/lib          |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019          |
| Is contained                | false                                |
| Is homebrew                 | false                                |
| Is installed via Fabric.app | false                                |
| Xcode Path                  | /Library/Developer/CommandLineTools/ |
| Xcode Version               |                                      |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
lane :test_gym do
  gym({
    export_team_id: 'MY_TEAM_ID',
    skip_build_archive: true,
    skip_archive: true,
    output_directory: './ios/ad-hoc',
    include_symbols: false,
    output_name: 'ad-hoc.ipa',
    archive_path: "/Users/martingonzalez/Library/Developer/Xcode/Archives/2020-01-10/4.6.4-2.xcarchive",
    export_options: {
      method: 'ad-hoc',
      provisioningProfiles: { 
        "com.mycompany.myproduct" => "com.mycompany.myproduct AdHoc",       
      }
    }
  })
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.140.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                         | Version | Update-Status  |
| ------------------------------ | ------- | -------------- |
| fastlane-plugin-etermax_builds | 4.14.1  | 💥 Check failed |
| fastlane-plugin-browserstack   | 0.3.1   | ✅ Up-To-Date   |

<details><summary><b>Loaded gems</b></summary>

| Gem                            | Version      |
| ------------------------------ | ------------ |
| did_you_mean                   | 1.3.0        |
| bundler                        | 1.17.2       |
| etc                            | 1.0.1        |
| forwardable                    | 1.2.0        |
| rake                           | 13.0.1       |
| CFPropertyList                 | 3.0.2        |
| public_suffix                  | 2.0.5        |
| addressable                    | 2.7.0        |
| ast                            | 2.4.0        |
| atomos                         | 0.1.3        |
| aws-eventstream                | 1.0.3        |
| aws-sigv4                      | 1.1.0        |
| jmespath                       | 1.4.0        |
| aws-sdk-core                   | 2.11.8       |
| aws-sdk-resources              | 2.11.8       |
| aws-sdk                        | 2.11.8       |
| babosa                         | 1.0.3        |
| claide                         | 1.0.3        |
| colored                        | 1.2          |
| colored2                       | 3.1.2        |
| colorize                       | 0.8.1        |
| highline                       | 1.7.10       |
| commander-fastlane             | 4.4.6        |
| declarative                    | 0.0.10       |
| declarative-option             | 0.1.0        |
| diff-lcs                       | 1.3          |
| digest-crc                     | 0.4.1        |
| unf_ext                        | 0.0.7.6      |
| unf                            | 0.1.4        |
| domain_name                    | 0.5.20190701 |
| dotenv                         | 2.7.5        |
| emoji_regex                    | 1.0.1        |
| excon                          | 0.71.1       |
| multipart-post                 | 2.0.0        |
| faraday                        | 0.17.3       |
| http-cookie                    | 1.0.3        |
| faraday-cookie_jar             | 0.0.6        |
| faraday_middleware             | 0.13.1       |
| fastimage                      | 2.1.7        |
| gh_inspector                   | 1.1.3        |
| jwt                            | 2.1.0        |
| memoist                        | 0.16.2       |
| multi_json                     | 1.14.1       |
| os                             | 1.0.1        |
| signet                         | 0.12.0       |
| googleauth                     | 0.10.0       |
| httpclient                     | 2.8.3        |
| mini_mime                      | 1.0.2        |
| uber                           | 0.1.0        |
| representable                  | 3.0.4        |
| retriable                      | 3.1.2        |
| google-api-client              | 0.36.4       |
| google-cloud-env               | 1.3.0        |
| google-cloud-errors            | 1.0.0        |
| google-cloud-core              | 1.5.0        |
| google-cloud-storage           | 1.25.1       |
| json                           | 2.3.0        |
| mini_magick                    | 4.10.1       |
| multi_xml                      | 0.6.0        |
| plist                          | 3.5.0        |
| rubyzip                        | 1.3.0        |
| security                       | 0.1.3        |
| naturally                      | 2.2.0        |
| simctl                         | 1.6.7        |
| slack-notifier                 | 2.3.2        |
| terminal-notifier              | 2.0.0        |
| unicode-display_width          | 1.6.0        |
| terminal-table                 | 1.8.0        |
| tty-screen                     | 0.7.0        |
| tty-cursor                     | 0.7.0        |
| tty-spinner                    | 0.9.2        |
| word_wrap                      | 1.0.0        |
| nanaimo                        | 0.2.6        |
| xcodeproj                      | 1.14.0       |
| rouge                          | 2.0.7        |
| xcpretty                       | 0.3.0        |
| xcpretty-travis-formatter      | 1.0.0        |
| http-accept                    | 1.7.0        |
| mime-types-data                | 3.2019.1009  |
| mime-types                     | 3.3          |
| netrc                          | 0.11.0       |
| rest-client                    | 2.1.0        |
| fastlane-plugin-browserstack   | 0.3.1        |
| http-form_data                 | 2.2.0        |
| ffi                            | 1.11.3       |
| ffi-compiler                   | 1.0.1        |
| http-parser                    | 1.2.1        |
| http                           | 4.3.0        |
| hashie                         | 3.6.0        |
| mini_portile2                  | 2.4.0        |
| nokogiri                       | 1.10.7       |
| xml-simple                     | 1.1.5        |
| unity_test_results             | 0.1.1        |
| fastlane-plugin-etermax_builds | 4.14.1       |
| jaro_winkler                   | 1.5.4        |
| parallel                       | 1.19.1       |
| parser                         | 2.6.5.0      |
| rainbow                        | 3.0.0        |
| rspec-support                  | 3.9.0        |
| rspec-core                     | 3.9.0        |
| rspec-expectations             | 3.9.0        |
| rspec-mocks                    | 3.9.0        |
| rspec                          | 3.9.0        |
| ruby-progressbar               | 1.10.1       |
| rubocop                        | 0.77.0       |
| rubocop-rspec                  | 1.37.0       |
</details>
```

**Comment by ahimik** [comment]
Have you managed to export an ipa from existing xcarchive finally?

**Comment by MartinGonzalez** [comment]
> Have you managed to export an ipa from existing xcarchive finally?

Yes, but it was not the way I thought it was.
I thought I could export an unsigned xcarchive and after sign it with resign, but you need to export the .ipa from the xcarchive using gym again.

**Comment by ahimik** [comment]
Could you please elaborate a bit more on this?
I think I've raised exactly the same issue:
I am trying to export and sign an ipa from existing xcarchive.
I don't need to build it and I don't have the project installed on my machine.
This is how my `Gymfile` looks like:

```
output_directory("./")
include_symbols(true)
include_bitcode(false)
export_method("app_store")
skip_build_archive(true)
skip_archive(true)
archive_path("./my-archive.xcarchive")
output_name("./my-app.ipa")
```

and the `fastlane gym ` command gives me the following output:

`Couldn't automatically detect the project file, please provide a path:`

**Comment by MartinGonzalez** [comment]
My thought was:
- Ok, I build the archive using the project path and do not sign it
- After build I have my archive where from it I can extract an AdHoc, Appstore and Inhouse

But it does not work like that or I think it doesn't.
One of the main problem was that if you don't sign it while exporting archive when you upload the ipa to AppStore it will give you a warning of Swift Libraries.

My pipe now is. 
- Build and export an adhoc archive
- resign for enterprise
- Build from previous archive with Appstore signing.

But in AppStore part you will need the path to the project, I don't know why

**Comment by ahimik** [comment]
@MartinGonzalez , thanks for your quick answers.
Unfortunately I didn't manage to create an IPA with Fastlane, so I've finally arrived with the following solution:

- Export IPA with signing using XCode command: `xcodebuild -exportArchive -archivePath ...`
- Upload build to TestFlight using `Fastlane pilot` command
