### ISSUE TITLE
`factory': [!] Can't find class 'adhoc' (RuntimeError)

### ISSUE THREAD

**Issue by gbarnett** [fastlane/fastlane#15870]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I have downloaded the latest version of fastlane and out of the box running sigh causes the following error: 
`.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/spaceship/lib/spaceship/portal/provisioning_profile.rb:177:in `factory': [!] Can't find class 'adhoc' (RuntimeError)`

##### Command executed
`fastlane sigh`
Other fastlane commands work correctly, such as `register_device`. 
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>`-------
### Captured Output

Command Used: ``
<details><summary>Output/Log</summary>

```

DEBUG [2020-01-09 10:28:18.04]: Checking if there are any plugins that should be loaded...
INFO [2020-01-09 10:28:18.08]: ------------------------------
INFO [2020-01-09 10:28:18.08]: --- Step: default_platform ---
INFO [2020-01-09 10:28:18.08]: ------------------------------
INFO [2020-01-09 10:28:18.08]: Welcome to fastlane! Here's what your app is setup to do:
+--------+---------------------+------------------------+
|                Available lanes to run                 |
+--------+---------------------+------------------------+
| Number | Lane Name           | Description            |
+--------+---------------------+------------------------+
| 1      | ios release         | Push a new release     |
|        |                     | build to the App       |
|        |                     | Store                  |
| 2      | ios register        | Register a single      |
|        |                     | device or a file       |
|        |                     | containing a list of   |
|        |                     | devices. For           |
|        |                     | information on how to  |
|        |                     | structure the file,    |
|        |                     | see                    |
|        |                     | http://devimages.appl  |
|        |                     | e.com/downloads/devic  |
|        |                     | es/Multiple-Upload-Sa  |
|        |                     | mples.zip  (app:       |
|        |                     | "prod" | "beta")       |
|        |                     | (filename: string |    |
|        |                     | (name: string, udid:   |
|        |                     | string))               |
| 3      | ios generateProfile | Generate a             |
|        |                     | provisioning profile   |
|        |                     | for development and    |
|        |                     | adHoc                  |
| 4      | ios upload          | Upload provisioning    |
|        |                     | profile to app center  |
| 0      | cancel              | No selection, exit     |
|        |                     | fastlane!              |
+--------+---------------------+------------------------+
WARN [2020-01-09 10:28:18.09]: Which number would you like run?

Looking for related GitHub issues on fastlane/fastlane...
Search query: Could not retrieve response as fastlane runs in non-interactive mode

URL: https://api.github.com/search/issues?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode+repo:fastlane/fastlane
➡️  Could not retrieve response as fastlane runs in non-interactive mode
   https://github.com/fastlane/fastlane/issues/15548 [closed] 8 💬
   a week ago

➡️  Match with Google Cloud: Impossible to run in noninteractive mode (CI)
   https://github.com/fastlane/fastlane/issues/15426 [closed] 3 💬
   5 weeks ago

➡️  CircleCI: Could not find fastlane in current directory.
   https://github.com/fastlane/fastlane/issues/15341 [closed] 7 💬
   10 Nov 2019

and 44 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0 (Apple Git-122.2)        |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.6 (18G95)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.3                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    OMITTED
    upload_to_app_store
  end

  desc "Register a single device or a file containing a list of devices." + 
        "\nFor information on how to structure the file, see  http://devimages.apple.com/downloads/devices/Multiple-Upload-Samples.zip" + 
        "\n (app: \"prod\" | \"beta\") (filename: string | (name: string, udid: string))"
  lane :register do |options|
    if options[:filepath]
      if options[:filepath]
        UI.message "Registering devices from file: " + options[:filepath] + " to apple developer portal..."
        register_devices(
          devices_file:
            options[:filepath]
        )
        UI.success "Device registered successfully"
      end
    elsif options[:name]
      if options[:udid]
        UI.message "Registering single device with <name: " + options[:name] + ", udid: " + options[:udid]  + "> to apple developer portal..."
        register_device(
          name: options[:name], 
          udid: options[:udid]
        )
        UI.success "Device registered successfully"
      else 
        UI.error "Missing udid key"
      end
    else 
      UI.error "Parameters missing or incorrect: either need filepath or both name and udid."
    end
  end 

  desc "Generate a provisioning profile for development and adHoc"
  lane :generateProfile do |options|
    sigh(
      adhoc: true,
      filename: "adhoc_test.mobileprovision",
      app_identifier: OMITTED,
      provisioning_name: "Testing Automation"
    )
  end

  desc "Upload provisioning profile to app center"
  lane :upload do |options| 
    if options[:alpha]
      
    elsif options[:beta]

    else 
      UI.message "No application specified"
    end
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
OMITTED
# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.28.3  | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.14.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.71.1       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.13.1       |
</details>

*generated on:* **2020-01-09**` </pre>
</details>

### Environment

<details>
  <pre> `<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0 (Apple Git-122.2)        |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.6 (18G95)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.3                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    OMITTED
    upload_to_app_store
  end

  desc "Register a single device or a file containing a list of devices." + 
        "\nFor information on how to structure the file, see  http://devimages.apple.com/downloads/devices/Multiple-Upload-Samples.zip" + 
        "\n (app: \"prod\" | \"beta\") (filename: string | (name: string, udid: string))"
  lane :register do |options|
    if options[:filepath]
      if options[:filepath]
        UI.message "Registering devices from file: " + options[:filepath] + " to apple developer portal..."
        register_devices(
          devices_file:
            options[:filepath]
        )
        UI.success "Device registered successfully"
      end
    elsif options[:name]
      if options[:udid]
        UI.message "Registering single device with <name: " + options[:name] + ", udid: " + options[:udid]  + "> to apple developer portal..."
        register_device(
          name: options[:name], 
          udid: options[:udid]
        )
        UI.success "Device registered successfully"
      else 
        UI.error "Missing udid key"
      end
    else 
      UI.error "Parameters missing or incorrect: either need filepath or both name and udid."
    end
  end 

  desc "Generate a provisioning profile for development and adHoc"
  lane :generateProfile do |options|
    sigh(
      adhoc: true,
      filename: "adhoc_test.mobileprovision",
      app_identifier: OMITTED,
      provisioning_name: "Testing Automation"
    )
  end

  desc "Upload provisioning profile to app center"
  lane :upload do |options| 
    if options[:alpha]
      
    elsif options[:beta]

    else 
      UI.message "No application specified"
    end
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
OMITTED
# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.28.3  | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.14.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.71.1       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.13.1       |
</details>

*generated on:* **2020-01-09**
</details>` </pre>
</details>

**Comment by joshdholtz** [comment]
@gbarnett Looks like you are running the the `brew cask install fastlane` version. This has recently been replaced by `brew install fastlane`. If you could run `brew cask uninstall fastlane` and run `brew install fastlane` that should fix your issue 😊

**Comment by gbarnett** [comment]
Thank you!

**Comment by joshdholtz** [comment]
Not a problem!
