### ISSUE TITLE
Fastlane 2.140.0 iOS Signing Error - errSecInternalComponent is back

### ISSUE THREAD

**Issue by techopsway2b1** [fastlane/fastlane#15877]
I am having code signing problems and ultimately breaking our build for shipping to testflight.  This was working perfectly fine about 6 weeks ago but we upgraded fastlane to 2.140(Although this issue started happening on 2.137), MacOS 10.14.6 and XCode 10.1 to 11.3. 

We are getting the errSecInternalComponent error which means fastlane cant access the keychain manager on MacOS.  Here is our full error:

`build	10-Jan-2020 21:51:10	
build	10-Jan-2020 21:51:10	[13:51:10]: ▸ [35m    /usr/bin/codesign --force --sign 446929AE6F7B202B356B92AB85D9CD9CC0DA14F0 --preserve-metadata=identifier,entitlements,flags --timestamp=none /Users/mobile-builder/Library/Developer/Xcode/DerivedData/greenlight-fbtyoekkugakbwdpmekznrwlndiu/Build/Intermediates.noindex/ArchiveIntermediates/greenlight/InstallationBuildProductsLocation/Applications/greenlight.app/Frameworks/Instabug.framework[0m
build	10-Jan-2020 21:51:10	[13:51:10]: ▸ [35m/Users/mobile-builder/Library/Developer/Xcode/DerivedData/greenlight-fbtyoekkugakbwdpmekznrwlndiu/Build/Intermediates.noindex/ArchiveIntermediates/greenlight/InstallationBuildProductsLocation/Applications/greenlight.app/Frameworks/Instabug.framework: replacing existing signature[0m
build	10-Jan-2020 21:51:10	[13:51:10]: ▸ [35m/Users/mobile-builder/Library/Developer/Xcode/DerivedData/greenlight-fbtyoekkugakbwdpmekznrwlndiu/Build/Intermediates.noindex/ArchiveIntermediates/greenlight/InstallationBuildProductsLocation/Applications/greenlight.app/Frameworks/Instabug.framework: errSecInternalComponent[0m
build	10-Jan-2020 21:51:10	[13:51:10]: ▸ [35mCommand /usr/bin/codesign failed with exit code 1[0m
build	10-Jan-2020 21:51:10	[13:51:10]: `

Prior to the environment upgrade we saw this same issue and solved it within the bash script that invokes the fastlane command:

`  security unlock-keychain -p $LOGIN_KEYCHAIN_PASSWORD login.keychain-db
  bundle exec fastlane beta`

We are using the following commands in our Fastlane file:

`platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    #increment_build_number(
    #  build_number: latest_testflight_build_number + 1,
    #  xcodeproj: "greenlight.xcodeproj"
    #)
    build_app(
      scheme: "greenlight",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.way2b1.greenlight" => "GreenlightProfile",
        }
      }
    )
    upload_to_testflight
  end
end`

We are a complete loss here and would really appreciate some advice to move forward.  This is breaking our production deployment processes.

Thanks,

DK

**Comment by techopsway2b1** [comment]
Here is the fastlane env output.  Thanks!
[fastlane-env.txt](https://github.com/fastlane/fastlane/files/4049816/fastlane-env.txt)

**Comment by techopsway2b1** [comment]
Additional error that might shed some light on this issue.  I have opened up a ticket with Instabug support.  Completely at a loss here.

`build	15-Jan-2020 01:17:45	
build	15-Jan-2020 01:17:45	+---------------+-------------------------+
build	15-Jan-2020 01:17:45	|            [32m[33mBuild environment[0m            |
build	15-Jan-2020 01:17:45	+---------------+-------------------------+
build	15-Jan-2020 01:17:45	| xcode_path    | /Applications/Xcode.app |
build	15-Jan-2020 01:17:45	| gym_version   | 2.140.0                 |
build	15-Jan-2020 01:17:45	| export_method | app-store               |
build	15-Jan-2020 01:17:45	| sdk           | iPhoneOS13.2.sdk        |
build	15-Jan-2020 01:17:45	+---------------+-------------------------+
build	15-Jan-2020 01:17:45	
build	15-Jan-2020 01:17:45	[17:14:36]: ▸ [35mCode Signing ./Instabug.framework/Instabug with Identity iPhone Distribution: WAY2B1.COM, Inc. (8N24VSH5QG)[0m
build	15-Jan-2020 01:17:45	[17:14:36]: ▸ [35m/usr/bin/codesign --force --sign 446929AE6F7B202B356B92AB85D9CD9CC0DA14F0 --preserve-metadata=identifier,entitlements ./Instabug.framework/Instabug[0m
build	15-Jan-2020 01:17:45	[17:14:36]: ▸ [35m./Instabug.framework/Instabug: replacing existing signature[0m
build	15-Jan-2020 01:17:45	[17:14:36]: ▸ [35m./Instabug.framework/Instabug: errSecInternalComponent[0m
build	15-Jan-2020 01:17:45	[17:14:36]: ▸ [35mCommand /bin/sh failed with exit code 1[0m
build	15-Jan-2020 01:17:45	[17:14:36]: `

**Comment by ButkiewiczP** [comment]
I'm also receiving this same error. Other projects that don't include Instabug are building just fine.

**Comment by techopsway2b1** [comment]
We've been able to resolve our particular build issue. It seems like it may not be Instabug specific but caused by other misconfigurations in our environment.

To resolve the errSecInternalComponent, we needed to:
- Ensure the XCode application and codesign binary (/usr/bin/codesign) were both always allowed access to the certificate and private key in the macOS Keychain
    - to do this
        - open keychain and find the private key in question
        - right-click and select get info
        - go to the tab labeled Access Control
        - verify xcode and codesign are always allowed access, if not add them
- make sure that the keychain was unlocked as part of our build scripts
    - security unlock-keychain -p $KEYCHAIN_PASSWORD_ENV_VAR login.keychain
    - please note your keychain and environment variables may vary

We also found that Fastlane created its own provisioning profile. In order to get Fastlane to sign, we had to our configure our project's .pbxproj file to reference the new profile and associated certificate (Apple Distribution ...), set an explicit mapping in fastlane/Fastfile via export_options provisioningProfiles, and set an explicit mapping in fastlane/Gymfile via export_options provisioningProfiles.

We found that signing occurs at two parts: during archive creation and archive export. We had to tell Fastlane to use the same provisioning profile each time. This is the profile referenced above.

We were able to resolve our build issues without Instabug initially. Our builds continued to succeed even after re-adding Instabug back.
