### ISSUE TITLE
How to automate getting login session for Apple ID?

### ISSUE THREAD

**Issue by igorek9191** [fastlane/fastlane#15880]
My question is how to automate getting login session for Apple ID with fastlane in Jenkins's pipeline?

According to documentation, at first I should manually execute such command

`fastlane spaceauth -u user@email.com`

and then paste the session value to FASTLANE_SESSION environment variable in pipeline.

But I don't want to make it manually all the time. How to automate this process ?

**Comment by max-ott** [comment]
Please check out the official docs for `Jenkins` integration: https://docs.fastlane.tools/best-practices/continuous-integration/jenkins/

**Comment by igorek9191** [comment]
> Please check out the official docs for `Jenkins` integration: https://docs.fastlane.tools/best-practices/continuous-integration/jenkins/

Didn't find appropriate answer to me

**Comment by max-ott** [comment]
https://docs.fastlane.tools/best-practices/continuous-integration/

**Comment by igorek9191** [comment]
> https://docs.fastlane.tools/best-practices/continuous-integration/

max-ott, I saw your documentation, I've mentioned it in my question. But I didn't find an answer for my question in your doc. Could you please provide explicit answer for me? Of course if it's present in your doc ?

**Comment by max-ott** [comment]
Fastlane is open source. Issues are primarily for issues and bugs. We cannot really provide support or consulting work for free. There are also ton of free tutorials and videos on how to set this up available on the web.
