### ISSUE TITLE
Struggling to get `screengrab` working after reading all the docs

### ISSUE THREAD

**Issue by andybee** [fastlane/fastlane#15886]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
* Screengrab
* I've read all the documentation and issues I can find for Screengrab but, so far, not found a solution.

#### Question Description
I'm familiar with using Fastlane for iOS projects and in particular using Snapshot for screenshots. This is my first exploration in to both Android and screen grab, so apologies if I've made some huge glaring omission - but I've followed the documentation carefully and hit upon a few key issues and still been unable to generate screenshots successfully.

I have a bare bones Android app and I'm attempting to just take a single screenshot of it's launch phase. I've setup Espresso as per the docs and whilst I can run most of the tests OK in Android Studio, it will fail on the specific calls to screengrab, but I understand from GitHub issues that this is expected behaviour as it's not running in the way it expects when fastlane triggers the test.

I had issues adding the rules required to the test due to the project being in Kotlin and various updates to the framework since the docs where last updated, here's the closest I manage to get to compile and run:

```
package com.example.myfirstapp

import androidx.test.rule.ActivityTestRule
import org.junit.BeforeClass
import org.junit.ClassRule
import org.junit.Rule
import org.junit.Test
import tools.fastlane.screengrab.Screengrab
import tools.fastlane.screengrab.UiAutomatorScreenshotStrategy
import tools.fastlane.screengrab.locale.LocaleTestRule

class ScreenshotTest {

    @Rule @JvmField
    var activityRule: ActivityTestRule<MainActivity> = ActivityTestRule(MainActivity::class.java)

    @Test
    fun useAppContext() {
        Screengrab.setDefaultScreenshotStrategy(UiAutomatorScreenshotStrategy())
        Screengrab.screenshot("default")
    }

}
```

I've included the following in the build.gradle:

```androidTestImplementation 'tools.fastlane:screengrab:1.2.0'```

And the debug manifest includes the following:

```
<uses-permission android:name="android.permission.DISABLE_KEYGUARD"/>
<uses-permission android:name="android.permission.WAKE_LOCK"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.CHANGE_CONFIGURATION" tools:ignore="ProtectedPermissions" />
```

However when run via Fastlane I get the following error:

```
[10:55:40]: ▸ java.lang.RuntimeException: Unable to capture screenshot.
[10:55:40]: ▸ 	at tools.fastlane.screengrab.FileWritingScreenshotCallback.screenshotCaptured(FileWritingScreenshotCallback.java:56)
```

Taking a look at that line, seems to be related to filesystem access to write the screenshot file. I note these lines during fast lane's startup:

```
[10:55:25]: Cleaning screenshots on device
ls: /sdcard/com.example.myfirstapp/screengrab: No such file or directory
[10:55:25]: Exit status: 1
ls: /data/data/com.example.myfirstapp/app_screengrab: No such file or directory
[10:55:25]: Exit status: 1
ls: /data/user/0/com.example.myfirstapp/files/com.example.myfirstapp/screengrab/en-US/images/screenshots: No such file or directory
[10:55:25]: Exit status: 1
```

But I initially assumed these were just because I've never actually taken any screenshots, so the path is empty?

I've found similar (outdated) issues that often revolve around the specific version/runtime of the emulator. I've tried in a Pixel 3 emulator and an older Nexus 7 emulator, with API level 29.

Any ideas on what I'm doing wrong? Thanks in advance.

**Comment by andybee** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.6.5                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.23.0                          |
| Installation Source         | /usr/local/lib/ruby/gems/2.6.0/bin/fastlane |
| Host                        | Mac OS X 10.14.6 (18G2022)                  |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.6.5/lib            |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.2.1                                      |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
platform :ios do
  lane :screenshots do
    update_app_identifier(
      plist_path: 'ios/Demo/Info.plist',
      app_identifier: app_identifier
    )
    update_info_plist(
      plist_path: 'ios/Demo/Info.plist',
      display_name: display_name
    )
    snapshot
  end
end

platform :android do
  lane :screenshots do
    build_android_app(
      project_dir: 'android',
      task: 'assemble',
      build_type: 'debug'
    )
    build_android_app(
      project_dir: 'android',
      task: 'assemble',
      build_type: 'AndroidTest'
    )
    capture_android_screenshots(
      app_apk_path: 'android/app/build/outputs/apk/debug/app-debug.apk',
      tests_apk_path: 'android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk',
      app_package_name: 'com.example.myfirstapp'
    )
  end
end

```
</details>

**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.140.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.1        |
| bundler                   | 2.1.0        |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.71.1       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.17.3       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.0.1        |
| signet                    | 0.12.0       |
| googleauth                | 0.10.0       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.0        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.25.1       |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.7        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.2        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.14.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>


*generated on:* **2020-01-13**
</details>

**Comment by andybee** [comment]
I've found rolling back to API Level 28 resolves this issue (I get a screenshot), but would still be curious to know if this is a bug or an error on my part.

**Comment by jsbentley34** [comment]
No bug

**Comment by Diegolotr99** [comment]
Rolling back to API Level 28 should not be a proper solution just a workaround, as the Screengrab **should** work with the latest Android API level...or at least investigate what is the issue. Hope there is a fix soon!

**Comment by jl-gogovapps** [comment]
I'm also experiencing this.  My output looks just like the screenshot in https://github.com/fastlane/fastlane/issues/15886#issuecomment-588337548.  

@Diegolotr99 Were you able to overcome this issue? 

I'm not even seeing the output as described in the original ticket
```
[10:55:40]: ▸ java.lang.RuntimeException: Unable to capture screenshot.
```

**Comment by Diegolotr99** [comment]
> I'm also experiencing this. My output looks just like the screenshot in [#15886 (comment)](https://github.com/fastlane/fastlane/issues/15886#issuecomment-588337548).
> 
> @Diegolotr99 Were you able to overcome this issue?
> 
> I'm not even seeing the output as described in the original ticket
> 
> ```
> [10:55:40]: ▸ java.lang.RuntimeException: Unable to capture screenshot.
> ```

@jl-gogovapps I am still having the same issue...I even updated to the latest version of fastlane a few days ago...and still getting the exact same errors...

**Comment by jl-gogovapps** [comment]
I just had a bit of luck downgrading to `tools.fastlane:screengrab:1.2.0`, but I have to manually pull them from the `/sdcard` directory
