### ISSUE TITLE
Plugin not visible on the available plugins list

### ISSUE THREAD

**Issue by dotdoom** [fastlane/fastlane#15897]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Description

Looks like `flutter` plugin is no longer on the Fastlane "Available Plugins" page.
There were no updates to plugin since December 2019 and it was visible in the list. Is there any problem that I am not seeing?

**Comment by dotdoom** [comment]
[RubyGems](https://rubygems.org/gems/fastlane-plugin-flutter), [GitHub](https://github.com/dotdoom/fastlane-plugin-flutter).

**Comment by joshdholtz** [comment]
On it!

**Comment by joshdholtz** [comment]
@dotdoom This _mmaaayyyyy_ be an inconsistency in the RubyGems search API 🤔 I'm getting inconsistent results when searching for "flutter" (see below). I have to do a bit more research here but it looks like the times that the docs were built were off of the results with "flutter" missing 😔

### Ran `fastlane seach_plugins flutter` and got all of these results in less than a minute

```
+---------------+------------------------------------------------------+-----------+
|                            fastlane plugins 'flutter'                            |
+---------------+------------------------------------------------------+-----------+
| Name          | Description                                          | Downloads |
+---------------+------------------------------------------------------+-----------+
| flutter       | Flutter actions plugin for Fastlane                  | 15911     |
| flutter       | Flutter actions plugin for Fastlane                  | 15911     |
| flutter_build | Build your flutter project directly from your lane.  | 2035      |
+---------------+------------------------------------------------------+-----------+
```

```
+---------------+------------------------------------------------------+-----------+
|                            fastlane plugins 'flutter'                            |
+---------------+------------------------------------------------------+-----------+
| Name          | Description                                          | Downloads |
+---------------+------------------------------------------------------+-----------+
| flutter       | Flutter actions plugin for Fastlane                  | 15911     |
| flutter_build | Build your flutter project directly from your lane.  | 2035      |
+---------------+------------------------------------------------------+-----------+
```

```
+---------------+------------------------------------------------------+-----------+
|                            fastlane plugins 'flutter'                            |
+---------------+------------------------------------------------------+-----------+
| Name          | Description                                          | Downloads |
+---------------+------------------------------------------------------+-----------+
| flutter_build | Build your flutter project directly from your lane.  | 2035      |
+---------------+------------------------------------------------------+-----------+
```

**Comment by joshdholtz** [comment]
Maybe its a Ruby issue? 🤔 Its always returning the same number of plugins but looks like its getting filtered out somehow 😱 This is really, really, weird

**Comment by dotdoom** [comment]
Huh! It might have been a temporary issue. I have tried yesterday and got empty results from "gem search" twice out of ~2000 attempts.

Would it be possible for the team to rebuild the page sooner than the next release happens, to have a plugin there? And for future safety, perhaps make the tool retry a few times to get the largest set, unless RubyGems recommends something else.

**Comment by dotdoom** [comment]
@joshdholtz 
A friendly ping!

**Comment by dotdoom** [comment]
Help?

**Comment by dotdoom** [comment]
Hello! It has been at least 12 days since the plugin is gone from the list. Can I please have some update?
