### ISSUE TITLE
How to upload to appstore + testflight at the same time

### ISSUE THREAD

**Issue by john-mejia** [fastlane/fastlane#15899]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Using deliver/pilot/spaceship to upload a new build and submit it for external testing at the same time

#### Question Description
I'm going down a rabbit hole at the moment with spaceship trying to build a workflow that works for my team. It feels like it would be a common workflow so I wanted to ask before I reinvented multiple wheels here.

**I'm trying to do the following:**

1. Build App
2. Submit to Appstore (create new submission) * But not submit for review
3. Submit for external test-flight testing and assign to a group.

**What I've tried so far:**
1. I can build the app and submit to app store
2. Using spaceship, I can find that build and submit for external testing.
3. Using spaceship, I can later submit this app for review and release accordingly.

Pilot and Deliver both want to upload IPA's which seems wasteful for this use case since it's the same IPA.

**Comment by max-ott** [comment]
Hi @john-mejia you will probably need to build this workflow yourself. Each tool (`deliver`, `pilot` etc) has their very own/specific use case. 

With `spaceship` you can build out your own workflow exactly the way you want, so I'd say this is the way to go.

**Comment by john-mejia** [comment]
Thanks @max-ott - I'd love to contribute some of the work if it makes sense for the tools. For example I'm writing a lane that will simply release the current approved version and I imagine that would belong in deliver.

**Comment by max-ott** [comment]
This sounds more like examples and best practices to me, not sure what the best place to store them is.

**Comment by debeltranc** [comment]
Seems like I arrived a bit late to this conversation but I hope this is still useful. The trick here is that you can only promote a version of an application for release only if is in TestFlight already, so deliver uploads to TestFlight first and then creates a release in App Store connect.
If you weren't in need to release your test version for external testing just using deliver would've been enough, but there's still a workaround using Fastlane (i.e. you should not need to use Spaceship directly for this).
You can use gym and then pilot to build and submit your application to TestFlight, a lane in your Fastfile similar to this would work:
```ruby
    #signing part of your lane
    gym #plus any parameters you might need here
    pilot(
        distribute_external: true, #This is the key, this will setup a build to be distributed for external testing
        changelog: "What to test?",
        beta_app_review_info: {
            #More metadata for beta testing submission, more details in the docs
        },
        localized_app_info: {
            "default": {
                #More stuff here
            }
        },
        localized_build_info: {
            "default": {
                #More stuff here
            }
        },
    )
    deliver(
        build_number: "abcdefghijklmn" #The build number of the version you just submitted in the previous action, this won't upload a build file again.
        #More parameters to complete your release submission
     )
```

**Comment by john-mejia** [comment]
Thanks @debeltranc - I think the added complexity on my part is that we do all of these things on different days as part of our release process. 

Another issue is I don’t want to wait for Apple to process builds as I am on a cloud CI environment and don’t want to keep a build running all this time, so I can’t make both calls from one lane. 

We were able to do everything with spaceship and it wasn’t too bad, this gives us complete control(or as much as Apple will let us) of our release including pausing and resuming the phased rollouts.  

The big downside is that if apple does take a longer than X amount of time to process a build, then some of the automation wouldn’t work here since we’re assuming some sort of reasonable timing from Apple for TestFlight/App Store reviews. 

I’m closing this out since I have answers and a solution in place, but if you think I can still do this with the built in lanes I’d be happy to stick to those.
