### ISSUE TITLE
Can't execute fastlane spaceauth -u user@email.com in Jenkins's pipeline

### ISSUE THREAD

**Issue by igorek9191** [fastlane/fastlane#15894]
Trying to execute such command in Jenkins to get login session from Apple:
`fastlane spaceauth -u user@email.com`

the result
```
/Library/Ruby/Gems/2.3.0/gems/highline-1.7.10/lib/highline/question.rb:413:in `remove_whitespace': [31m[!] undefined method `strip' for nil:NilClass[0m (NoMethodError)
	from /Library/Ruby/Gems/2.3.0/gems/highline-1.7.10/lib/highline.rb:873:in `get_line'
	from /Library/Ruby/Gems/2.3.0/gems/highline-1.7.10/lib/highline.rb:891:in `get_response'
	from /Library/Ruby/Gems/2.3.0/gems/highline-1.7.10/lib/highline.rb:264:in `ask'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `ask'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.135.2/spaceship/lib/spaceship/two_step_or_factor_client.rb:196:in `ask_for_2fa_code'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.135.2/spaceship/lib/spaceship/two_step_or_factor_client.rb:145:in `handle_two_factor'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.135.2/spaceship/lib/spaceship/two_step_or_factor_client.rb:20:in `handle_two_step_or_factor'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.135.2/spaceship/lib/spaceship/client.rb:494:in `send_shared_login_request'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.135.2/spaceship/lib/spaceship/tunes/tunes_client.rb:127:in `send_login_request'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.135.2/spaceship/lib/spaceship/client.rb:770:in `do_login'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.135.2/spaceship/lib/spaceship/client.rb:384:in `login'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.135.2/spaceship/lib/spaceship/client.rb:346:in `login'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.135.2/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.135.2/spaceship/lib/spaceship/spaceauth_runner.rb:18:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.135.2/spaceship/lib/spaceship/commands_generator.rb:43:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.135.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.135.2/spaceship/lib/spaceship/commands_generator.rb:49:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.135.2/spaceship/lib/spaceship/commands_generator.rb:14:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.135.2/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.135.2/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'

```

**Comment by igorek9191** [comment]
> It seems like you have not included the output of `fastlane env`
> To make it easier for us help you resolve this issue, please update the issue to include the output of `fastlane env`

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.21.0 (Apple Git-122.2)                           |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.6 (18G95)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.3                                                           |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.135.2 | 🚫 Update available |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.66.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday                   | 0.17.0       |
| faraday_middleware        | 0.13.1       |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.0.2        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| json                      | 2.2.0        |
| io-console                | 0.4.5        |
| CFPropertyList            | 3.0.1        |
| libxml-ruby               | 2.9.0        |
| atomos                    | 0.1.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| claide                    | 1.0.3        |
| fastimage                 | 2.1.7        |
| addressable               | 2.7.0        |
| psych                     | 2.1.0.1      |
| mime-types                | 3.3          |
| mime-types-data           | 3.2019.1009  |
</details>


*generated on:* **2020-01-14**
</details>

**Comment by max-ott** [comment]
Could you please try to upgrade your ruby and fastlane to the latest versions?

**Comment by igorek9191** [comment]
just close
