### ISSUE TITLE
How can I let Fastlane know where to find my iOS and Android screenshots?

### ISSUE THREAD

**Issue by janoist1** [fastlane/fastlane#15891]
I'm generating screenshots using Detox framework for both iOS and Android. I'm trying to submit an app to iOS (first), I have placed the screenshots into the `screenshots` directory, however Fastlane won't find them (when running `upload_to_app_store`).

How can I let Fastlane know where to find my iOS and Android screenshots?

**Comment by max-ott** [comment]
You will need to put them in the correct folder structure for the different languages. I recommend downloading them from an existing app, to see the right structure, if possible.
