### ISSUE TITLE
ConnectAPI fails: The URL path is not valid - '/iris/v1/

### ISSUE THREAD

**Issue by racer1988** [fastlane/fastlane#15904]
EDIT: 

The Documentation topic is still valid, but my main issue is that ConnectAPI doesn't work or is not working on its own?

```
Spaceship::ConnectAPI.get_app
Spaceship::UnexpectedResponse: The URL path is not valid - '/iris/v1/apps/' is not a valid URL
```

### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
*What tool/action do you have a question about?*

Spaceship::ConnectAPI

*Is this a question about documentation?*

yes

*Is this a question about a third party plugin? (If so, please go to the plugin repository first)*

no

#### Question Description

All .md files of the Docs always suggest to login using `Tunes`

https://github.com/fastlane/fastlane/blob/master/spaceship/docs/AppStoreConnect.md

However in order to use the new `https://api.appstoreconnect.apple.com` we must use JWT token.
after reading the code I see we can manually create a JWT Token for the api with
`Spaceship::ConnectAPI::Token`
or using the ENV variables `SPACESHIP_CONNECT_API_KEY_ID` etc..
but it's really unclear to me what should be the access point for all these operation.

From the docs it looks like the entry point is always `find` a app or a `tester` and then go down from there.

I would like to extend Spaceship::ConnectAPI with a PR to support other features like
https://developer.apple.com/documentation/appstoreconnectapi/add_builds_to_a_beta_group

However it would be great to have docs explaining how to use the appstoreconnect api from the current Spaceship::ConnectAPI module.

Thanks for the explanation on what is the root idea behind it

**Comment by racer1988** [comment]
I would like to understand how the ConnectAPI works because for me it looks like it does not 😢 

Standard use tries Tunes (and fails)
```
Spaceship::ConnectAPI.get_app
DEBUG: init Tunes Client
Spaceship::UnexpectedResponse: The URL path is not valid - '/iris/v1/apps/' is not a valid URL
from fastlane/spaceship/lib/spaceship/connect_api/client.rb:134:in `handle_response'
```

JWT can be done manually, but still fails

```
Spaceship::ConnectAPI.token = Spaceship::ConnectAPI::Token.create(key_id: "X", issuer_id: "X", filepath: "X")
Spaceship::ConnectAPI.get_app
DEBUG: init CONNECT API
Spaceship::UnexpectedResponse: The URL path is not valid - '/iris/v1/apps/' is not a valid URL
fastlane/spaceship/lib/spaceship/connect_api/client.rb:134:in `handle_response'
```

Thans

**Comment by racer1988** [comment]
From debugging it seems to me that the problem is that the request is sent via the wrong client.

```
module Spaceship
  class Client

def send_request(method, url_or_path, params, headers, &block)
        response = @client.send(method, url_or_path, params, headers, &block)
```

is called, where @client is `Faraday::Connection:` and somehow references `/iris/`

This still happens after removing all reference to /iris/ from the entire Fastlane Repo.

**Comment by racer1988** [comment]
@max-ott this is a follow up on #15810

Is ConnectAPI module not actually working yet or I am missing something?

**Comment by max-ott** [comment]
You cannot simply switch out the front part and expect all other fastlane/spaceship stuff to work. The ConnectAPI from Apple’s end is extremely limited. Please stick with the standard Spaceship::Tunes except for TestFlight in the meantime.

**Comment by racer1988** [comment]
Ok Thanks @max-ott

**Comment by max-ott** [comment]
The `ConnectAPI` is quite different from the standard `Tunes` one due to the design by Apple.

Here is a hint how to get started / how commands look like:

```
bundle exec irb

require "spaceship"

token = Spaceship::ConnectAPI::Token.create(
	key_id: "3ZWKF934939",
	issuer_id: "59h6de122-112l-47r2-z021-6h5f4f11gg1",
	filepath: File.absolute_path("/Users/dev/AuthKey_3ZWKF934939.p8")
)

Spaceship::ConnectAPI.token = token

Spaceship::ConnectAPI.get_feedback(filter: { "build.app": "123456789", "build.preReleaseVersion": "acd6a4fd-0543-494e-a792-64401056499e" }, includes: "screenshots")
```
