### ISSUE TITLE
Provide latest build number for CLI "fastlane pilot distribute"

### ISSUE THREAD

**Issue by Blackjacx** [fastlane/fastlane#15908]
### Question Subject
```shell
fastlane pilot distribute -q <itc_team_id> --distribute_external "true" --notify_external_testers "true" --demo_account_required "true" -a <bundle_id> -g <tester_groups> -w <changelog>
```

#### Question Description
I use the command above to notify testers about already uploaded builds.

The command figures out the latest version - build number - combination and adds the specified tester groups to this build.

BUT figuring out the build number takes very long and I already have it locally. Can I provide it myself to the command? This would bring us a massive speed boost. I sadly didn't find any documentation related to this... :(

**Comment by Blackjacx** [comment]
I think its not necessary since it only a question related to ne most up to date fastlane.

**Comment by bguidolim** [comment]
@Blackjacx you need to set the build number before build with [increment_build_number](https://docs.fastlane.tools/actions/increment_build_number/#increment_build_number) action.

**Comment by Blackjacx** [comment]
> @Blackjacx you need to set the build number before build with [increment_build_number](https://docs.fastlane.tools/actions/increment_build_number/#increment_build_number) action.

Hey there this we do of course. The question is about providing the latest build number when distributing the build to testers, not about the upload. The build is already uploaded (and processed by apple) when I run the command above.

I reformulated my question and added the complete command we use to add testers to the latest build.

**Comment by Blackjacx** [comment]
Is there anybody who can help me on this topic?

**Comment by Blackjacx** [comment]
This is still an issue and it would be nice I could get an answer. I could tray to implement it myself and file a PR... Would that be an option?

**Comment by tmm1** [comment]
You can add `--build_number`

https://github.com/fastlane/fastlane/pull/16221

**Comment by Blackjacx** [comment]
This is amazing! Thanks man. This saves sooo much time for us, since we batch-distribute 15 apps and counting 👍
