### ISSUE TITLE
Families Policy Google Play

### ISSUE THREAD

**Issue by Luke-SF** [fastlane/fastlane#15903]
#### Motivation Behind Feature
Every app must have the families policy (18+) set now.

#### Feature Description
There seems to be no way to set metadata of the families-policy, which is required on Google Play now. There should be a way to set or change the values in this section.

#### Alternatives or Workarounds
Manually setting in play.

**Comment by max-ott** [comment]
The Google Play Publishing API only provides a limited feature set: https://developers.google.com/android-publisher/api-ref

Setting the family policy (or pretty much everything besides pure metadata, screenshots and bundles) is not supported. The only alternative would be web-scrapping, which is not really an option.

Feel free to open a pull request, if you start on such an endeavour and the team will be more than happy to help.
