### ISSUE TITLE
Match certificates named 'Apple Distribution: ' don't show up in Xcode 10.3

### ISSUE THREAD

**Issue by bestimmaa** [fastlane/fastlane#15907]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Since `fastlane nuke` and recreating my profiles and certificates with fastlane match I can't select any of the installed signing certificates in XCode 10.3 when exporting after archiving the app.
The certificate shows up in the 'General' and 'Build Settings' tab of XCode however.

Fastlane shows the same error as Xcode does: 

`
No signing certificate "iOS Distribution" found: No "iOS Distribution" signing certificate matching team ID "xxx" with a private key was found. (in target 'xxx')
`

Match was run on my machine successfully and the new certificate shows up in my keychain as valid. I suspect this is due to the renaming of the certificates. The old ones were called 'iPhone Distribution: xxx (xxx)", the new ones are "Apple Distribution: xxx (xxx)". If I ask XCode to recreate a certificate it will be named 'iPhone Distribution..." as well.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.21.0 (Apple Git-122)                             |
| Installation Source         | ~/work/xxx-ios/vendor/bundle/ruby/2.3.0/bin/fastlane    |
| Host                        | Mac OS X 10.14.6 (18G2022)                                     |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.1                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  MY_APP_ID = "xxx"
  MY_PROFILE = "xxx"
  MY_TEAM = "xxx"

  desc "Run unit tests"
  lane :tests do
    run_tests(scheme: "xxx_development")
  end

  desc "Write the git changelog to file"
  lane :write_changelog_to_file do
    file = File.open("git_changelog.txt", "w")
    file.puts changelog_from_git_commits
    file.close
  end

  desc "Distribute a DEV build to Firebase App Distribution"
  lane :development_firebase do
    
    xcversion(version: "10.3")

    # Setup code signing
    match(type: "adhoc", app_identifier:"xxx", readonly: false)
    


    # Compile
    gym(scheme:"xxx_development", export_team_id:"xxx", export_method:'ad-hoc')

    # Make sure to have FIREBASE_TOKEN set as ENV for this step to work
      
    firebase_app_distribution(
        app: "xxx",
        groups: "dev-testers",
        release_notes: changelog_from_git_commits
    )

    upload_symbols_to_crashlytics(
      dsym_path: "./bin/xxx.app.dSYM.zip"
    )

  end

  desc "Distribute a STAGING build to Firebase App Distribution"
  lane :staging_firebase do
    
    xcversion(version: "10.3")

    # Setup code signing
    match(type: "adhoc", app_identifier:"xxx", readonly: false)
    
    # Override project settings for code signing - just in case
    update_project_provisioning(
      xcodeproj: "xxx.xcodeproj",
      target_filter: "xxx", # matches name or type of a target
      build_configuration: "Staging",
      profile: ENV["sigh_com.xxx.staging_adhoc_profile-path"],
      code_signing_identity: "Apple Distribution: xxx (xxx)"
    )
    increment_build_number({
      build_number: ENV["BITRISE_BUILD_NUMBER"]
    })

    # Compile
    gym(scheme:"xxx_staging", export_team_id:"xxx", export_method:'ad-hoc')


    firebase_app_distribution(
        app: "xxx",
        groups: "staging-testers",
        release_notes: changelog_from_git_commits
    )

    upload_symbols_to_crashlytics(
      dsym_path: "./bin/xxx.app.dSYM.zip"
    )   

  end


  lane :check_appstore_version do

    # Read x.x.x styled version from Xcode project  
    version = get_version_number(
      xcodeproj: "xxx.xcodeproj",
      target: "xxx",
      configuration: "Release"
    )
    
    # Make sure that 'version' exists on AppStore Connect
    deliver(skip_binary_upload: true, app_version: version, skip_metadata:true, skip_screenshots:true,app_identifier: "com.xxx.xxx.xxx")
  end 

  desc "Upload a production build to AppStore Connect. You still have to submit it for review."
  lane :release do

  check_appstore_version
    
  increment_build_number({
      build_number: ENV["BITRISE_BUILD_NUMBER"]
  })
  
   sync_code_signing(type: “appstore”, app_identifier: "xxx", readonly: true)
   
   build_app(scheme: “xxx_production”)

   upload_to_testflight(
      skip_submission: true,
      skip_waiting_for_build_processing: true
   ) 
   upload_to_app_store(
      force: true,
      skip_binary_upload: true,
      build_number: ENV["BITRISE_BUILD_NUMBER"],
      submit_for_review: false
    )
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
apple_id("xxx") # Your Apple email address
itc_team_id("xxx") # App Store Connect Team ID


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.140.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.1.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.0.0        |
| bundler                                   | 2.0.1        |
| CFPropertyList                            | 3.0.2        |
| public_suffix                             | 2.0.5        |
| addressable                               | 2.7.0        |
| atomos                                    | 0.1.3        |
| babosa                                    | 1.0.3        |
| claide                                    | 1.0.3        |
| colored                                   | 1.2          |
| colored2                                  | 3.1.2        |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| declarative                               | 0.0.10       |
| declarative-option                        | 0.1.0        |
| digest-crc                                | 0.4.1        |
| unf_ext                                   | 0.0.7.6      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| dotenv                                    | 2.7.5        |
| emoji_regex                               | 1.0.1        |
| excon                                     | 0.71.1       |
| multipart-post                            | 2.0.0        |
| faraday                                   | 0.17.3       |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.6        |
| faraday_middleware                        | 0.13.1       |
| fastimage                                 | 2.1.7        |
| gh_inspector                              | 1.1.3        |
| jwt                                       | 2.1.0        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.14.1       |
| os                                        | 1.0.1        |
| signet                                    | 0.11.0       |
| googleauth                                | 0.9.0        |
| httpclient                                | 2.8.3        |
| mini_mime                                 | 1.0.2        |
| uber                                      | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| google-api-client                         | 0.32.1       |
| google-cloud-env                          | 1.2.1        |
| google-cloud-core                         | 1.3.2        |
| google-cloud-storage                      | 1.21.1       |
| json                                      | 2.3.0        |
| mini_magick                               | 4.10.1       |
| multi_xml                                 | 0.6.0        |
| plist                                     | 3.5.0        |
| rubyzip                                   | 1.3.0        |
| security                                  | 0.1.3        |
| naturally                                 | 2.2.0        |
| simctl                                    | 1.6.7        |
| slack-notifier                            | 2.3.2        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.6.1        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.7.0        |
| tty-cursor                                | 0.7.0        |
| tty-spinner                               | 0.9.2        |
| word_wrap                                 | 1.0.0        |
| nanaimo                                   | 0.2.6        |
| xcodeproj                                 | 1.14.0       |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.0        |
| fastlane-plugin-firebase_app_distribution | 0.1.4        |
| xcode-install                             | 2.6.1        |
</details>

*generated on:* **2020-01-17**
</details>

</pre>
</details>

**Comment by janpio** [comment]
As far as I remember those certificates were only introduced with Xcode 11, so they are probably just not present with Xcode 10.x. 

Any reason you don't use Xcode 11?

**Comment by bestimmaa** [comment]
This was my guess @janpio, thank you. We postponed the upgrade to the new SDK for some time now, seems like a good reason to finally do it.
