### ISSUE TITLE
Allow me to get exit status from swiftlint without the lane giving me a nice message.

### ISSUE THREAD

**Issue by Alfredo-Moreira** [fastlane/fastlane#15901]
```
def self.handle_swiftlint_error(ignore_exit_status, exit_status)
        if ignore_exit_status
          failure_suffix = 'which would normally fail the build.'
          secondary_message = 'fastlane will continue because the `ignore_exit_status` option was used! 🙈'
        else
          failure_suffix = 'which represents a failure.'
          secondary_message = 'If you want fastlane to continue anyway, use the `ignore_exit_status` option. 🙈'
        end
```

This section of the code takes the swiftlint status code and shows a nice message and a zero status code when it should have returned non-zero. I want the ability to choose if I want the nice message, or just pass me what swift lint says.

Something like get_exit_status: true|false to get the variable exit_status

**Comment by max-ott** [comment]
Hi there, feel free to open a pull request and we are more than happy to review it.

**Comment by janpio** [comment]
Did I deduce correctly that you want a feature for the existing `swiftlint` action?

**Comment by Alfredo-Moreira** [comment]
@janpio 
def self.handle_swiftlint_error(ignore_exit_status, exit_status)
        if ignore_exit_status
          failure_suffix = 'which would normally fail the build.'
          secondary_message = 'fastlane will continue because the `ignore_exit_status` option was used! 🙈'
        else
          failure_suffix = 'which represents a failure.'
          secondary_message = 'If you want fastlane to continue anyway, use the `ignore_exit_status` option. 🙈'
        end

The lane handles errors for you and always exist with exit code 0. Instead, it sends you a message stating that it failed but exited with code 0. I want to be able to bypass that based on a flag, and get the exit_status variable of that function. So I can fail a job when it runs in Jenkins. I hope I explained it correctly.

**Comment by janpio** [comment]
Not really, I do not know where this code is from (is it just from fastlane to show something or something you wrote?) and sill am not sure if you want to modify the existing action.

**Comment by Alfredo-Moreira** [comment]
@janpio I'm running this action as a shell command. Shell takes any non-zero exit code as a failure. Currently, the way this action is set up successful and unsuccessful swift lint runs exit code 0. Unless I'm parsing the output to see what was the result to shell it was successful. 
My case scenario to why iIwant to propose this change is: I'm approaching this as a DevOps and not as Dev. I can run the action in a Jenkins pipeline with 'def result = sh(script:'fastlane swiftlint',returnStatus:true)'.This allows me to run a shell command and even if it doesn't exit with a status code 0, it will not cause the Jenkins pipeline because it is encapsulated in the result variable. Thus by doing a simple if(result) statement I can set the status of the status gate in a PR as passed or not, while still allowing the rest of the PR build to continue. The result variable currently is always 0 which does not allow me to do what I need.

**Comment by janpio** [comment]
Ok, so you are looking for a change in fastlane that the exit code of "running this action as a shell command" will be influenced by the result/output of the `swiftlint` action?

What command are you executing on the command line? No `Fastfile` involved?
