### ISSUE TITLE
Unable to upload the build to testflight because of 2FA 

### ISSUE THREAD

**Issue by nihp** [fastlane/fastlane#15909]
While trying to upload the build I got this error and failed to upload.

**Too many verification codes have been sent. Enter the last code you received or try again later.**

Can anyone elaborate how I am getting this. Before I not get this 2FA error while uploading

```
Environment variable `SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER` is set, automatically requesting 2FA token via SMS to that number

SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER = xxxxxxx

Successfully requested text message to xxxxxxx

Please enter the 6 digit code you received at xxxxxxxx:

"Too many verification codes have been sent. Enter the last code you received or try again later."}

Requesting session...

Error: Incorrect verification code

Environment variable 
```

**Comment by janpio** [comment]
> Too many verification codes have been sent. Enter the last code you received or try again later.

Did you do what it tells you to do?

**Comment by nihp** [comment]
No. 

Any option to skip 2FA in this case?

**Comment by nihp** [comment]
Once I tried with the Authcode too. But it failed to proceed.

`{"code"=>"-xxxxxx", "message"=>"Too many verification codes have been sent. Enter the last code you received or try again later."}`

**Comment by janpio** [comment]
Your account is now effectively blocked until you enter one code successfully, maybe when you log in manually. Only then Apple will let you proceed normally as before.

**Comment by nihp** [comment]
Okay. I have fixed the above. 

Can I able to skip or disable the 2FA.

I have switched to account holder to admin account. So the above get fixed

**Comment by bguidolim** [comment]
@nihp Please take a look on this doc: https://docs.fastlane.tools/best-practices/continuous-integration/#authentication-with-apple-services

**Comment by nihp** [comment]
@bguidolim Thanks
