### ISSUE TITLE
Error using 'fastlane_require' in combination with 'require' for Gem Redcarpet

### ISSUE THREAD

**Issue by oklimberg** [fastlane/fastlane#15919]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When using Redcarpet to strip down Markdown form strings, you need to require 'readcarpet' and 'redcarpet/render_strip'. Previously it was possible to use `fastlane_require "readcarpet"` to make sure the user gets an appropriate error message in combination with `require "redcarpet/render_strip"` to actually use the class `Redcarpet::Render::StripDown`.
This results now in an error. It is also not possible to use ´fastlane_require´ for both dependencies, since only one is a Gem. I had to revert to using plain `require` for both dependencies losing the nice error message in case the Gemfile does not contain `gem "redcarpet"` 

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>$ bundle exec fastlane ios showBug
[✔] 🚀

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
bundler: failed to load command: fastlane (/Users/XXX/.gem/ruby/2.6.0/bin/fastlane)
NameError: [!] uninitialized constant Redcarpet::Render::Base
Did you mean?  Base64
  /Users/XXX/.gem/ruby/2.6.0/gems/redcarpet-3.5.0/lib/redcarpet/render_strip.rb:5:in `<module:Render>'
  /Users/XXX/.gem/ruby/2.6.0/gems/redcarpet-3.5.0/lib/redcarpet/render_strip.rb:2:in `<module:Redcarpet>'
  /Users/XXX/.gem/ruby/2.6.0/gems/redcarpet-3.5.0/lib/redcarpet/render_strip.rb:1:in `<top (required)>'
  /Users/XXX/.gem/ruby/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/fast_file.rb:34:in `require'
  /Users/XXX/.gem/ruby/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/fast_file.rb:34:in `block in initialize'
  /Users/XXX/.gem/ruby/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/fast_file.rb:29:in `each'
  /Users/XXX/.gem/ruby/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/fast_file.rb:29:in `initialize'
  /Users/XXX/.gem/ruby/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/lane_manager.rb:16:in `new'
  /Users/XXX/.gem/ruby/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/lane_manager.rb:16:in `cruise_lane'
  /Users/XXX/.gem/ruby/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/XXX/.gem/ruby/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/XXX/.gem/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/XXX/.gem/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/XXX/.gem/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/XXX/.gem/ruby/2.6.0/gems/fastlane-2.140.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/XXX/.gem/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/XXX/.gem/ruby/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
  /Users/XXX/.gem/ruby/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/XXX/.gem/ruby/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Users/XXX/.gem/ruby/2.6.0/gems/fastlane-2.140.0/bin/fastlane:23:in `<top (required)>'
  /Users/XXX/.gem/ruby/2.6.0/bin/fastlane:23:in `load'
  /Users/XXX/.gem/ruby/2.6.0/bin/fastlane:23:in `<top (required)>'</pre>
</details>

### Environment

<details>
  <pre><details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.6.5                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.24.1                          |
| Installation Source         | ~/.gem/ruby/2.6.0/bin/fastlane              |
| Host                        | Mac OS X 10.14.6 (18G2022)                  |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.5/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.3                                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_require 'redcarpet'
require 'redcarpet/render_strip'

default_platform(:ios)

platform :ios do
  desc "Example lane to show bug with fastlane_require"
  lane :showBug do
    # add actions here: https://docs.fastlane.tools/actions
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::StripDown, quote: true)
	plain = markdown.render("**This** _is_ an [example](http://example.org/).")
	UI.message("#{plain}")
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.140.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 2.1.2        |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.71.1       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.17.3       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.0.1        |
| signet                    | 0.12.0       |
| googleauth                | 0.10.0       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.0        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.25.1       |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.7        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.1        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.2        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.14.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| redcarpet                 | 3.5.0        |
</details>

*generated on:* **2020-01-21**
</details>

<details><summary>🚫 RubyGems environment 🚫</summary>
RubyGems Environment:
  - RUBYGEMS VERSION: 3.0.3
  - RUBY VERSION: 2.6.5 (2019-10-01 patchlevel 114) [x86_64-darwin18]
  - INSTALLATION DIRECTORY: /Users/XXX/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0
  - USER INSTALLATION DIRECTORY: /Users/XXX/.gem/ruby/2.6.0
  - RUBY EXECUTABLE: /Users/XXX/.rbenv/versions/2.6.5/bin/ruby
  - GIT EXECUTABLE: /usr/local/bin/git
  - EXECUTABLE DIRECTORY: /Users/XXX/.rbenv/versions/2.6.5/bin
  - SPEC CACHE DIRECTORY: /Users/XXX/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/XXX/.rbenv/versions/2.6.5/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-18
  - GEM PATHS:
     - /Users/XXX/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0
     - /Users/XXX/.gem/ruby/2.6.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/XXX/.rbenv/versions/2.6.5/bin
     - /usr/local/Cellar/rbenv/1.1.2/libexec
     - /Users/XXX/.gem/ruby/2.6.0/bin
     - /Users/XXX/.rbenv/shims
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Users/XXX/Library/Android/sdk/tools
     - /Users/XXX/Library/Android/sdk/platform-tools
     - ~/sdk/flutter/bin
     - /Users/XXX/.rbenv/bin</pre>
</details>
</pre>
</details>

**Comment by janpio** [comment]
What does "previously" mean - can you pin it to a specific fastlane version where this behavior changed?

**Comment by oklimberg** [comment]
I updated from version 2.130.0 to 2.140.0.
To do so, I also had to update ruby from version 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18] to ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]

I will try to pinpoint the exact version in the next few days.

**Comment by oklimberg** [comment]
Hi and sorry for the long delay.
The issue was introduced in version 2.132.0 and is still present in version 2.142.0.
