### ISSUE TITLE
Request: Call actions as hooks

### ISSUE THREAD

**Issue by kuteninja** [fastlane/fastlane#15916]
#### Motivation Behind Feature
I need to start storing metrics for our builds, and I wouldn't like to instrument each of our Fastfiles manually since users could modify the lanes. I'd rather add the metrics on our fastlane plugin and then just update all projects.

I've seen that you have metrics for each action completed, but it seems to be very coupled to the fastlane-core, I'd like to have hooks to attach my own scripts ie. OnActionStart, OnActionCompleted, OnActionFailed

#### Feature Description
Add a hook / catchable event when any action starts/completes/fails. 
- It could be used to send a slack message, to process metrics, or some other kind of automation.
- It should receive as much information possible from the actual action (ie. action name, parameters, execution time, error code, output string / path to logfile)

#### Alternatives or Workarounds
Export your own metrics methods so that we could call them and use those to analyze our builds, or document how to call actions or run custom code on an action start / end event.

**Comment by max-ott** [comment]
Hi @kuteninja sounds like a very interesting idea. I don't think this will have high chances to get added to the fastlane core so I recommend creating your own plugin / action for this or fork fastlane. You can also open a pull request and we can help you with that.

**Comment by janpio** [comment]
> I've seen that you have metrics for each action completed, but it seems to be very coupled to the fastlane-core,

What do you refer to here @kuteninja?

> Add a hook / catchable event when any action starts/completes/fails.

That should be possible as all actions use https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/action.rb, or probably even in some other layer when the action is called. Probably something similar even already exists (where stuff gets executed before each action) - but finding the correct code might involve quite a lot of reading of the fastlane source. If you are willing to do that, please let us know how it goes!

(Also possible that you can achieve this via a plugin. In Ruby you can monkey patch prety much everything, so changing part of fastlane itself via a plugin should theoretically be possible. Not sure if it is worth the effort though or if there are easier solutions)

**Comment by kuteninja** [comment]
> What do you refer to here @kuteninja?

I'm refering to the fastlane-core metrics section on the readme ([here](https://github.com/fastlane/fastlane#metrics)), and the folder it links to ([here](https://github.com/fastlane/fastlane/tree/master/fastlane_core/lib/fastlane_core/analytics)).

When fastlane ends, it know how much time it has spent on each action and which actions were used, probably due to some of this metrics code. It would be enough for my particular case to expose this information and allow me to push them to graphite or a similar service. However I think that hooks would be far more customizable for the majority of people.

**Comment by janpio** [comment]
Thanks.

I am not super sure if this is still active though, in the past most of the Analytics stuff was removed. @joshdholtz?

**Comment by joshdholtz** [comment]
@kuteninja We got rid of most of that but you could do something like this at the top of your `Fastfile` (or somewhere after where `fastlane` gets required) 👇 

```rb
module Extensions
  def run(options)
    puts "before - #{self.name}"
    super
    puts "after - #{self.name}"
  end
end

Fastlane::ActionsList.all_actions do |action|
  action.singleton_class.prepend Extensions
end
```

This will wrap the extension `run` implementation on each action where you can do whatever you want before/after with storing metrics. I would be very clear to users that this is what you are doing though. And I also don't know how this works with external actions or plugins 🙃

**Comment by kuteninja** [comment]
The Extensions work greatly, I'll close the issue 😄

**Comment by janpio** [comment]
Ugh, ruby... 🙈
