### ISSUE TITLE
[gradle] Generated path /apk not found in android folder

### ISSUE THREAD

**Issue by Sanjeevs1995** [fastlane/fastlane#15915]
When i take build for the flutter app using fastlane, the apk is being generated in a build folder outside android folder.

The message after successful build of android is 

> *Couldn't find any new signed apk files...*

The generated paths are all empty.

```
[16:41:09]: To not be asked about this value, you can specify it using 'file_path'
[16:41:09]: Path to the uploaded file: ^C+-----------------------------+-----------------------+


**|                    Lane Context                     |
+-----------------------------+-----------------------+
| PLATFORM_NAME               |                       |
| LANE_NAME                   | build                 |
| VERSION_NUMBER              | $(FLUTTER_BUILD_NAME) |
| GRADLE_BUILD_TYPE           | Release               |
| GRADLE_ALL_APK_OUTPUT_PATHS | []                    |
| GRADLE_ALL_AAB_OUTPUT_PATHS | []                    |**
```

But i found a generated apk outside the android folder in path 

> **build/app/outputs/apk/release/app-release.apk**

Will be the generated apk path be constant or will change with the future releases of flutter?
How to solve this issue?

Also the github issue for the same has been closed due to lack of inactivity.
ref: https://github.com/fastlane/fastlane/issues/15278

  [1]: https://i.stack.imgur.com/5xer4.png

**Comment by Sanjeevs1995** [comment]
fastlane env

fastlane version:2.140
| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.6.5                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0 (Apple Git-122)          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.14.6 (18G95)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.6.5/lib            |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.1                                        |

**Comment by janpio** [comment]
I am not sure what you are asking for as you deleted the issue template and did not include much of the information required to make an assessment.

What command are you running?
What action is being executed?
What is the full output you are getting, including all error messages?
What is the _full_ `fastlane env` output of the system you are using?

**Comment by Sanjeevs1995** [comment]
@janpio i am executing the command bundle exec fastlane <lane name>. In that i have written these to generate build.

`    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')`

the output is mentioned in the issue
