### ISSUE TITLE
Use externally defined `apple_id` in Pilot when supplying application specific password

### ISSUE THREAD

**Issue by colejd** [fastlane/fastlane#15923]
#### Motivation Behind Feature
This request concerns Pilot. According to [the docs](https://docs.fastlane.tools/actions/pilot/#use-an-application-specific-password-to-upload), when you supply an application specific password via the `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` environment variable, you must also supply `apple_id` as a parameter to `pilot`. If you have `apple_id` specified elsewhere, for example in `Appfile`, `pilot` will produce some confusing output:
```
[16:16:33]: -------------------
[16:16:33]: --- Step: pilot ---
[16:16:33]: -------------------
[16:16:33]: Login to App Store Connect (some-email@domain.com)
-------------------------------------------------------------------------------------
Please provide your Apple Developer Program account credentials
The login information you enter will be stored in your macOS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` environment variable
See more information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
-------------------------------------------------------------------------------------
```

This seems to indicate that `pilot` respects the definition of `apple_id` in `Appfile`, but doesn't recognize that I want to authenticate with an application specific password, since it's asking for the account's password.

More to the point, it appears that `pilot` cannot use an application specific password unless the `apple_id` parameter is specified, e.g.:

```
pilot(
  apple_id: "some-email@domain.com",
  skip_waiting_for_build_processing: true,
)
```

#### Feature Description

My request is to enable `pilot` to utilize application specific passwords if `apple_id` is already defined, such that you don't have to define it again in the method call.

#### Alternatives or Workarounds
As above, specify the `apple_id` in the call to `pilot`.

**Comment by colejd** [comment]
I'm realizing now that `apple_id` is not supposed to be an email, but an identifier, so the foundation for this is fundamentally flawed.

**Comment by janpio** [comment]
Yeah, these naming overlaps are a pain and impossible to clean up properly (as the same "string" is used to describe two fundamentally different things by Apple), sorry for the confusion.
