### ISSUE TITLE
Release an ios app that is in a "pending release" state (manual release)

### ISSUE THREAD

**Issue by ISDr** [fastlane/fastlane#15921]
### New Issue Checklist

- [ x] Updated fastlane to the latest version
- [ x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I want to confirm if it is safe to use the release! method in app_version to release an app that is in a pending release state, e.g. "Pending Developer Release". Could this be added as a deliver option? i.e. skip the submission bits and just do the release of a version that's already approved?

https://github.com/fastlane/fastlane/blob/8de6f50478a1953ddc86f32453cd225d4c29ed23/spaceship/lib/spaceship/tunes/app_version.rb#L675

I saw in issues below that this is not supported:
https://github.com/fastlane/fastlane/issues/13625
https://github.com/fastlane/fastlane/issues/9065

However, I have just run a test, and called the release! function in app_version for an edit_version that was pending developer release, and the release of the update went through. 

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by max-ott** [comment]
Hi there, I'm not sure what this issue is for? You tested it and it worked, so what is the exact question? If there's a problem/issue, please open a new issue with an exact description and steps to reproduce the issue, so the community can help you.
