### ISSUE TITLE
Apple Pay Certificate Creation

### ISSUE THREAD

**Issue by nesfahani** [fastlane/fastlane#15925]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I am looking to create Apple Pay certificates with Fastlane.

I saw some answers from a couple years ago saying it wasn't supported yet, but am curious on the current state as I saw ApplePay in certificate.rb and tried using it using the commands below

I also messed around with the source a bit, and got to the following line in portal_client.rb, where I took out the parameter "specialIdentifierDisplayId" and it ended up giving me the same error but instead of an AppId it complained that "There is no identifier with ID 'null' on this team. Which tells me it is using this specialIdentifierDisplayId even though the comment says its only for web push certs

So is it possible to create Apple Pay certs using Fastlane today? If not, I may be interested in working on it and eventually creating a PR

```

  r = request(:post, "account/#{platform_slug(mac)}/certificate/submitCertificateRequest.action", {
        teamId: team_id,
        type: type,
        csrContent: csr,
        appIdId: app_id, # optional
        specialIdentifierDisplayId: app_id, # For requesting Web Push certificates

```

##### Command executed

```

csr, pkey = Spaceship::Certificate.create_certificate_signing_request
Spaceship::Certificate.ApplePay.create!(csr: csr, bundle_id:"com.whatever")

```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> There is no identifier with ID '<appId>' on this team. </pre>
</details>

### Environment

<details>
  <pre>  </pre>
</details>

**Comment by max-ott** [comment]
As far as I know this is currently not supported by `spaceship`. Feel free to open a pull request and I'm more than happy to test it.

**Comment by nesfahani** [comment]
I will look into what would be needed to make this work, thanks for getting back
