### ISSUE TITLE
xcargs examples in docs

### ISSUE THREAD

**Issue by thejeff77** [fastlane/fastlane#15932]
### Question Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
This is a question about documentation.

I need to pass OTHER_SWIFT_FLAGS and GCC_PREPROCESSOR_DEFINITIONS via fastlane snapshot and I'm having trouble. 

First off, I set these in my target application, but it seems to get blown away (not passed) via fastlane snapshot, so I'm not sure if snapshot is running in release mode or what.

The option available for fastlane snapshot is xcargs, but I find the documentation lacking in description for how I would do this. The example shows a single option, not multiple and no example on how to pass the option - ex via () or plain, or within a string, etc.. (see more below)

There is a similar post here for building with fastlane using the custom_build_args option, however  this isn't available via shapshot's Snapfile config options. 

https://github.com/fastlane/fastlane/issues/2619

What I've tried:

Variations of: 

`xcargs "OTHER_SWIFT_FLAGS = \"$(inherited) -DDEBUG -DLOCALIZE\" GCC_PREPROCESSOR_DEFINITIONS=\"$(inherited) DEBUG=1 LOCALIZE=1\""`

Furthermore the xcargs description on the fastlane snapshot documentation could use some help, as it leaves a lot of room for interpretation. 

Description:

Pass additional arguments to xcodebuild for the test phase. Be sure to quote the setting names and values e.g. OTHER_LDFLAGS="-ObjC -lstdc++"

As there is no example command, it makes it tough to figure out what this means - some options from the other settings could come up with some options for what this might mean:

xcargs( OTHER_LDFLAGS="-ObjC -lstdc++")
xcargs OTHER_LDFLAGS="-ObjC -lstdc++"
xcargs "OTHER_LDFLAGS='-ObjC -lstdc++'"

Multiple:
xcargs(OTHER_LDFLAGS="-ObjC -lstdc++" SOME_OTHER_ONE="-SomeOther")
xcargs("OTHER_LDFLAGS='-ObjC -lstdc++' SOME_OTHER_ONE='-SomeOther'")
xcargs OTHER_LDFLAGS="-ObjC -lstdc++" SOME_OTHER_ONE="-SomeOther"

Thank you for any clarification or help!

**Comment by thejeff77** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.2                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.14.1                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.2 (19C57)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.3.1                                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"

  lane :release do
    #increment_build_number(xcodeproj: "PracticePlayer.xcodeproj")
    #increment_version_number(
    #	bump_type: "patch",
    #	xcodeproj: "PracticePlayer.xcodeproj"
    #)
    
    build_app(scheme: "PracticePlayer")
    deliver(
      # skip_screenshots: false,
      app_identifier: "com.MFE.PracticePlayerPro",
      # screenshots_path: "screenshots-pro",
      # metadata_path: "metadata-pro"
    )
  end

  lane :screenshots do
    capture_screenshots
    upload_to_app_store
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.MFE.PracticePlayerPro") # The bundle identifier of your app
apple_id("inflatedwizard@gmail.com") # Your Apple email address

itc_team_id("119057288") # App Store Connect Team ID
team_id("ZAR5QX7MAH") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.140.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.14.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.2        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.71.1       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.7        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.10.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.3       |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.4.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.25.0       |
| emoji_regex               | 1.0.1        |
| CFPropertyList            | 3.0.2        |
| faraday                   | 0.17.3       |
| json                      | 2.3.0        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>


*generated on:* **2020-01-25**
</details>

**Comment by thejeff77** [comment]
Also it appears that default values are not populated for many keys that have them. Ex Dark Mode, and others.

**Comment by thejeff77** [comment]
hello would love to keep this open - simple documentation request.

**Comment by ppamorim** [comment]
Please add a documentation for this, it's so hard to setup these options...

**Comment by thejeff77** [comment]
@ppamorim I have a workaround that may help you out. This still needs docs but this other approach should help you out. 

Create another UI Test Target, and add your tests that apply to snapshots to this project/target. For me this resulted in two UI Test projects, one for snapshots and one for all the rest.

As the snapshot setup states, the UI Test Target for snapshots should be a shared one (see docs)

Then just change options for the additional target in the build settings, as it is separated out. For me I now have Release/Debug/Snapshot options (as opposed to the standard Debug/Release). 

This should allow you to add any custom flags required to the snapshot-only tests that you need. 

Good luck, hope this helps.

**Comment by ppamorim** [comment]
@thejeff77 That's beyond possible, my workspace is already massive. We are not going to create new targets just because Fastlane has a deficiency.

**Comment by ppamorim** [comment]
@thejeff77 Please check this out: https://github.com/fastlane/fastlane/issues/16136
