### ISSUE TITLE
macOS Notarization Process

### ISSUE THREAD

**Issue by mRs-** [fastlane/fastlane#15930]
### Feature Request
As a mac developer I would like to publish apps with fastlane outside of the appstore.

#### Motivation Behind Feature
Easy handling of CI Interactions with Fastlane for creating apps outside of the store.
Ditching the old makefiles for handling this approach. It would be much cleaner to have a neat DSL for this.

#### Feature Description
Currently I'm using a Makefile to do this task. 

Here are the current steps described in the Makefile:
``` 
zip: 
	ditto -c \
	-k \
	--keepParent \
	$(BUILD_FOLDER)/$(APP_NAME).app $(BUILD_FOLDER)/$(APP_NAME)_notarization.zip

notarize_upload: 
	xcrun altool \
	--notarize-app \
	--primary-bundle-id $(PRIMARY_BUNDLE_ID) \
	-f $(BUILD_FOLDER)/$(APP_NAME)_notarization.zip \
	-u $(USER_NAME) \
	-p $(PASSWORD) \
	--output-format xml > $(UPLOAD_INFO_PLIST)

define wait_while_notarizing
	while true; do \
		xcrun altool \
		--notarization-info `/usr/libexec/PlistBuddy -c "Print :notarization-upload:RequestUUID" $(UPLOAD_INFO_PLIST)` \
		-u $(USER_NAME) \
		-p $(PASSWORD) \
		--output-format xml > $(REQUEST_INFO_PLIST) ;\
		if [ `/usr/libexec/PlistBuddy -c "Print :notarization-info:Status" $(REQUEST_INFO_PLIST)` != "in progress" ]; then \
			break ;\
		fi ;\
		sleep 10 ;\
	done
endef

notarize_wait:
	sleep 10;
	xcrun altool \
	--notarization-info `/usr/libexec/PlistBuddy -c "Print :notarization-upload:RequestUUID" $(UPLOAD_INFO_PLIST)` \
	-u $(USER_NAME) \
	-p $(PASSWORD) \
	--output-format xml > $(REQUEST_INFO_PLIST)
	$(call wait_while_notarizing)

staple: 
	xcrun stapler staple $(BUILD_FOLDER)/$(APP_NAME).app

notarize: 
	$(MAKE) zip 
	$(MAKE) notarize_upload
	$(MAKE) notarize_wait
	$(MAKE) staple
```

* Package it to a zip with ditto
* Upload to Apple and getting back the current UUID
* Wait for notarization from apple, look every 10 seconds for an update
* Staple the notarized Application

Currently only the .app file is notarized. The next step would be to add .dmg as well for the notarization.

#### Alternatives or Workarounds
Currently I'm using my makefile or Xcode to do this steps.

**Comment by mRs-** [comment]
It's not finished yet

**Comment by Cyberbeni** [comment]
https://docs.fastlane.tools/actions/notarize/

**Comment by mRs-** [comment]
This is looking good! Is this already implemented in the core of Fastlane?

**Comment by Cyberbeni** [comment]
Yes, it was originally a plugin and got moved to Fastlane.

**Comment by mRs-** [comment]
Awesome! Issue Closed!
