### ISSUE TITLE
uploading Flutter app to playstore beta fails due to version code

### ISSUE THREAD

**Issue by maheshmnj** [fastlane/fastlane#15936]
I am trying to upload a my flutter app to playstoe in beta using fastlane.The Google play console already contains the app in beta with version code 2,With Version Code I understand what follows after + in pubspec.yaml if I am not wrong e.g  ```version: 1.0.0+2```  **version code is 2** and in the play console my apks have version code as these its little confusing for me.

![image](https://user-images.githubusercontent.com/31410839/73153485-06e69d80-40fa-11ea-9d8c-daca1aa312e5.png)

This is the lane that I am using to deploy the app using  command 
```fastlane deploy```

```
desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    supply(
      apk:'../build/app/outputs/apk/release/app-release.apk',
      track: 'beta',
      json_key: "~/Documents/api.json",
      skip_upload_images: true,
      skip_upload_screenshots:true,
      version_code:4
      )
  end
```

This is the error that I get when deploying the app
```
[!] Google Api Error: releaseValidationErrorKeyApkNoUpgradePaths: You cannot rollout this release because it does not allow any existing users to upgrade to the newly added APKs. - You cannot rollout this release because it does not allow any existing users to upgrade to the newly added APKs
```
This is the ```faslane env``` output
```
[✔] 🚀 
[11:45:56]: fastlane detected a Gemfile in the current directory
[11:45:56]: However, it seems like you didn't use `bundle exec`
[11:45:56]: To launch fastlane faster, please use
[11:45:56]: 
[11:45:56]: $ bundle exec fastlane env
[11:45:56]: 
[11:45:56]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[11:45:56]: Generating fastlane environment output, this might take a few seconds...
[11:45:57]: Installing Ruby gem 'fastlane-plugin-get_version_number'...
[11:46:20]: Found gem "fastlane-plugin-get_version_name" instead of the required name "fastlane-plugin-get_version_number"
[11:46:20]: Successfully installed 'fastlane-plugin-get_version_number'
[11:46:20]: Error loading plugin 'fastlane-plugin-get_version_number': cannot load such file -- fastlane/plugin/get_version_number
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                                   |
| --------------------------- | ----------------------------------------------------------------------- |
| OS                          | debian_based buster/sid                                                 |
| Ruby                        | 2.5.5                                                                   |
| Bundler?                    | false                                                                   |
| Git                         | git version 2.17.1                                                      |
| Installation Source         | /home/linuxbrew/.linuxbrew/Cellar/fastlane/2.140.0/libexec/bin/fastlane |
| Host                        | Ubuntu 18.04.3 LTS debian_based buster/sid (4.15.0-74-generic)          |
| Ruby Lib Dir                | /home/linuxbrew/.linuxbrew/Cellar/ruby@2.5/2.5.5_1/lib                  |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                                             |
| Is contained                | false                                                                   |
| Is homebrew                 | false                                                                   |
| Is installed via Fabric.app | false                                                                   |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_IN:en    | 🚫 |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    supply(
      apk:'../build/app/outputs/apk/release/app-release.apk',
      track: 'beta',
      json_key: "~/Documents/api.json",
      skip_upload_images: true,
      skip_upload_screenshots:true,
      version_code:4
      )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("~/Documents/api.json") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("com.thoughtframeworks.iborganic") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.140.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                 | Version   | Update-Status  |
| -------------------------------------- | --------- | -------------- |
| fastlane-plugin-increment_version_code | 0.4.3     | ✅ Up-To-Date   |
| fastlane-plugin-get_version_number     | undefined | 💥 Check failed |

<details><summary><b>Loaded gems</b></summary>

| Gem                                    | Version      |
| -------------------------------------- | ------------ |
| slack-notifier                         | 2.3.2        |
| atomos                                 | 0.1.3        |
| CFPropertyList                         | 3.0.2        |
| claide                                 | 1.0.3        |
| colored2                               | 3.1.2        |
| nanaimo                                | 0.2.6        |
| xcodeproj                              | 1.14.0       |
| rouge                                  | 2.0.7        |
| xcpretty                               | 0.3.0        |
| terminal-notifier                      | 2.0.0        |
| unicode-display_width                  | 1.6.0        |
| terminal-table                         | 1.8.0        |
| plist                                  | 3.5.0        |
| public_suffix                          | 2.0.5        |
| addressable                            | 2.7.0        |
| multipart-post                         | 2.0.0        |
| word_wrap                              | 1.0.0        |
| tty-screen                             | 0.7.0        |
| tty-cursor                             | 0.7.0        |
| tty-spinner                            | 0.9.2        |
| babosa                                 | 1.0.3        |
| colored                                | 1.2          |
| highline                               | 1.7.10       |
| commander-fastlane                     | 4.4.6        |
| excon                                  | 0.71.1       |
| faraday                                | 0.17.3       |
| unf_ext                                | 0.0.7.6      |
| unf                                    | 0.1.4        |
| domain_name                            | 0.5.20190701 |
| http-cookie                            | 1.0.3        |
| faraday-cookie_jar                     | 0.0.6        |
| faraday_middleware                     | 0.13.1       |
| fastimage                              | 2.1.7        |
| gh_inspector                           | 1.1.3        |
| json                                   | 2.3.0        |
| mini_magick                            | 4.10.1       |
| multi_xml                              | 0.6.0        |
| rubyzip                                | 1.3.0        |
| security                               | 0.1.3        |
| xcpretty-travis-formatter              | 1.0.0        |
| dotenv                                 | 2.7.5        |
| bundler                                | 2.1.4        |
| naturally                              | 2.2.0        |
| simctl                                 | 1.6.7        |
| jwt                                    | 2.1.0        |
| uber                                   | 0.1.0        |
| declarative                            | 0.0.10       |
| declarative-option                     | 0.1.0        |
| representable                          | 3.0.4        |
| retriable                              | 3.1.2        |
| mini_mime                              | 1.0.2        |
| multi_json                             | 1.14.1       |
| signet                                 | 0.12.0       |
| memoist                                | 0.16.2       |
| os                                     | 1.0.1        |
| googleauth                             | 0.10.0       |
| httpclient                             | 2.8.3        |
| google-api-client                      | 0.36.4       |
| google-cloud-env                       | 1.3.0        |
| google-cloud-core                      | 1.4.1        |
| digest-crc                             | 0.4.1        |
| google-cloud-storage                   | 1.25.1       |
| emoji_regex                            | 1.0.1        |
| fastlane-plugin-increment_version_code | 0.4.3        |
</details>

*generated on:* **2020-01-27**
</details>
[11:46:21]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[11:46:21]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅
```

Please let me know if you need some additional information

**Comment by max-ott** [comment]
Version code needs to increment and as far as I know allows only for real numbers and no decimals. If you have version codes 4002 already, next version code needs to be 4003. Any version code below does not allow the user to upgrade (see the error message).

So if you change your version code from `4` to `4003` the upload should work. (Not sure how you got those "high" numbers in the first place)

**Comment by maheshmnj** [comment]
> Version code needs to increment and as far as I know allows only for real numbers and no decimals. If you have version codes 4002 already, next version code needs to be 4003. Any version code below does not allow the user to upgrade (see the error message).
> 
> So if you change your version code from `4` to `4003` the upload should work. (Not sure how you got those "high" numbers in the first place)

I think those version codes in google play console are different from what we have in pubspec.yaml(which is **2**),earlier I simply dropped my apks in to the playconsole and it was available automatically with those version code I even tried with version code 4003 but it still gave same error

**Comment by maheshmnj** [comment]
these were the apk's that I uploaded from the play console they had the following version code with this I understand that the last digit of the version code e.g 4001 corresponds to version code 1 ,4002 corressponds to version code 2 and so on,Now I would like to upload with version 3

![image](https://user-images.githubusercontent.com/31410839/73178870-269cb680-4138-11ea-91a9-15c77c4d2035.png)

**Comment by maheshmnj** [comment]
These are the apks that I uploaded to play console manually they have these version codes now

![image](https://user-images.githubusercontent.com/31410839/73179428-5a2c1080-4139-11ea-87d7-fa977a229bdc.png)

**Comment by max-ott** [comment]
I think you are mixing things up. Google Play Dev Console is not creating stuff automatically for you.

## 1) Release Name
> Name to identify release in the Play Console only, such as an internal code name or build version.

<img width="480" alt="Screenshot 2020-01-27 at 14 47 12" src="https://user-images.githubusercontent.com/6481790/73179602-065b0080-4114-11ea-9adc-9011d0a9c83b.png">

You can include this with your APK/AAB, but also always change this later on in the dev console.

## 2) Version Code
Needs to increment ALWAYS, regardless of the release. So release `1.0.0` might have version code `101`. Release `2.0.1` needs to have APKs added with version code > 101 (102, 201, 2000 etc.)

Your `pubspec.yaml` needs to have a version code higher then the last existing one.

**Comment by maheshmnj** [comment]
So I am changing only the version code so should I Change the version name as well
now I have ```version: 1.0.0+3``` so should I change it to something like this 1.0.1+1 and is there anyway I can automatically increment the version code without causing problems please take a look at my fastfile above

**Comment by janpio** [comment]
This seems to be a problem how you use Flutter, nothing related to fastlane. You have to change your project so your `versionCode` is increased as this is what is probably blocking your upload.

(In general the release number could/should be `x.y.z` while the version code should just be an integer `123`)

**Comment by tianhaoz95** [comment]
@maheshmnj 
I have been struggling with this 2 days ago so I wrote this: https://github.com/tianhaoz95/fastlane-plugin-flutter_version

Then I was able to do this:

https://github.com/tianhaoz95/photochat/blob/9b390db2b28279fb576ecec9e5a7862f62143a77/photochatapp/android/fastlane/Fastfile#L20-L33
