### ISSUE TITLE
Improve Snapshot Performance & Run Behavior

### ISSUE THREAD

**Issue by thejeff77** [fastlane/fastlane#15938]
### Feature Request

Hey all, I figured I'd start a discussion on this for a few reasons:

1. The comment in the documentation "If you find a better way to do any of this, please submit an issue on GitHub or even a pull request :+1:" in reference to language and device type configuration on a simulator from: https://docs.fastlane.tools/actions/snapshot/    - and I think I have a better way.
2. I think I have a better way for #1, at least for the language.
3. I just migrated from a homegrown solution to fastlane snapshot, and fastlane snapshot is _much_ slower ( like 3x slower ), although I'm still going to use it because of the integration/support, easy config, integration with fastlane and convenient summary report (html report). But I figure that some of my input may make a difference, at least in starting a conversation about implementation options that may not be know or currently utilized.

So to start this off, I'll make a couple observations:
1. The fastlane snapshot implementation seems to re-compile the project for every language. I have this setup to run in parallel, so it will re-build, then run on 4 simulators at once for that locale. Please correct me if I'm wrong. I also have the re-install app setting enabled (not sure if this is the reason it re-compiles?) - so I'm curious why it re-compiles so much?
2. Fastlane snapshot seems to modify the simulator before launch in order to set simulator options, specifically the .plist file. I'm only assuming this solution came from this post which has been around for a while: https://stackoverflow.com/questions/57988687/how-to-use-dark-mode-in-simulator-ios-13   which mentions the mutation of files in the simulator location before launch. 

So, now to describe alternatives.

It is possible to manipulate the simulator language, locale, and dark mode (and much more) using launch arguments to the application. Before switching to fastlane, I had a UITest that would launch the app in every language and gather screenshots for it. I'd have to run this for every simulator myself, as I had no easy way of specifying which simulator to use. 

Some details about discovering the launch arg for dark mode are here: https://stackoverflow.com/questions/59447982/how-to-set-dark-mode-in-xcuiapplication-in-swift-uitests/59638786#59638786

Most notably the answerer's use of:
`defaults read NSGlobalDomain` with an additional parameter to discover available launch options for the simulator.

I've also included code below about how I would launch the simulator for each language, and auto-detect the languages for the main app bundle (would be an awesome setting!!!)

This approach is a bit different, as it runs every language on one simulator at a time instead of running one language on all needed simulators in parallel. (I.E. loops through simulator first and language is the sub-loop, whereas snapshot loops through language first (build with lang), and loops through simulators - or runs the simulators in parallel. )  Obviously the performance  will vary on if you have more simulators than languages or more languages than simulators for each approach. 

Some potential implications of an updated approach are:
- One build, run all languages on every simulator in parallel. Avoid a rebuild the app for each language.
- No more need to modify the .plist file (not sure what performance impact this has - need to reset the simulator?)

Anyway I don't have any experience with Ruby, and limited time for Open Source contributions so I figured I'd at least throw this out there to start a potentially exciting conversation about the future of fastlane snapshot.

```

    func testRunInAllLanguages() {

        let supportedLocalizations = getSupportedLocalizations()
        for nextLocalization in supportedLocalizations! {
            guard let nextLocalization = nextLocalization as? String else {
                continue
            }
            let app = XCUIApplication()
            let launchArguments = getLaunchOptions(forLanguage: nextLocalization)
            app.launchArguments = launchArguments!
            app.launch()
            // call test code/function here.
            app.terminate()
        }
    }

    func getLaunchOptions(forLanguage language: String?) -> [String]? {
        var localeCode = ""
        var langCode = ""
        if (language?.count ?? 0) == 2 {
            // en
            langCode = "(\(language ?? ""))" // (en)
            localeCode = "\(language ?? "")_\(language ?? "")" // en_en
        } else if (language?.count ?? 0) >= 5 {
            // zh-Hans
            langCode = "(\((language as NSString?)?.substring(to: 2) ?? ""))" // (zh)
            localeCode = language?.replacingOccurrences(of: "-", with: "_") ?? "" // zh_Hans
        }

        var launchArguments: [String] = []
        launchArguments.append("-AppleLanguages")
        launchArguments.append(langCode)
        launchArguments.append("-AppleLocale")
        launchArguments.append(localeCode)
        launchArguments.append("-AppleInterfaceStyle")
        launchArguments.append("Dark")
        return launchArguments
    }

    func getSupportedLocalizations() -> [AnyHashable]? {
        let bundles = Bundle.allBundles
        var found = false

        var supportedLocalizations: [AnyHashable] = []
        for bundle in bundles {
            let id = bundle.bundleIdentifier
            let locs = bundle.localizations
            if let id = id  {
                if id.contains("your.bundle.id.here") {
                    found = true
                    for localization in locs {
                        if !(localization == "Base") {
                            supportedLocalizations.append(localization)
                        }
                    }
                }
            }
        }

        if found {
            return supportedLocalizations
        }
        assertionFailure("Oops, can't find localizations")
        return nil
    }
```

#### Motivation Behind Feature
Drastically speed up snapshots!
Save thousands in infrastructure provisioning & payments due to reduced instance time

**Comment by janpio** [comment]
That sounds great @thejeff77. There might very well be reasons for the current behavior, or your setup would enforce some limitations the current system does not - I do not know. If anyone wants to take a shot at understanding the current codebase (ruby is basically English... quite easy to get started with) and implementing some of your suggestions in a Pull Request I am sure the community would take a closer look and see if that is actually the case. 🚀

**Comment by tedgonzalez** [comment]
What I did is to build once using scan then run snapshots with `test_without_building`. Works fine so far. See more details below:
https://medium.com/wandercodes/optimize-fastlane-snapshot-by-more-than-50-2859d5176530

Let me know if this cannot work for you.

**Comment by thejeff77** [comment]
activity

**Comment by thejeff77** [comment]
@tedgonzalez although this looks like it may work, it requires a lot of custom configuration in the Fastfile on top of what was already there, which adds a lot of complexity to the otherwise simple Fastfile setup of needing nothing added to it at all for "fastlane snapshot" to do its job. Your way seems to require a custom lane in the fastfile, so "fastlane snapshot" wouldn't work the same way on its own.

**Comment by thejeff77** [comment]
activity
