### ISSUE TITLE
match change_password re-encrypts with MATCH_PASSWORD instead of new password

### ISSUE THREAD

**Issue by chrisballinger** [fastlane/fastlane#15942]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When using `fastlane match change_password` if you have `MATCH_PASSWORD` set as an environmental variable, it will overwrite the "new password" you are trying to set, and re-encrypt everything to the old password.

Workaround:

`unset MATCH_PASSWORD` before running `bundle exec match change_password`

**Comment by janpio** [comment]
Interesting, would you describe that as a bug? Did the output clearly tell you what was going on when doing that?

**Comment by chrisballinger** [comment]
I'd definitely say it's a bug. The prompt asks you to enter a new password, and the old password is read from `MATCH_PASSWORD`. Then the new password you entered at the prompt is ignored, and it uses `MATCH_PASSWORD` instead.

**Comment by chrisballinger** [comment]
Still an issue

**Comment by chrisballinger** [comment]
Pretty sure this still isn't fixed
