### ISSUE TITLE
Using fastlane to clone a third-party repository into a project.

### ISSUE THREAD

**Issue by alexdneprin** [fastlane/fastlane#15944]
Can I use Fastlane to clone files(any) from the third-party repository into x-code project?

I tried using the following code: import_from_git(....)
But that did not work.

Tell me, is this possible?

**Comment by janpio** [comment]
`import_from_git` is to import a `Fastfile` into a fastlane project.

There are several source control related actions available in fastlane: https://docs.fastlane.tools/actions/#source-control 

But if the one you need is not one of the, you can always use `sh` to run any command: https://docs.fastlane.tools/actions/sh/
