### ISSUE TITLE
How can I automate build without running fastlane ios beta while my app is in developing and in testing stage

### ISSUE THREAD

**Issue by nihp** [fastlane/fastlane#15950]
I am uploading the build in testflight using **fastlane ios beta** now. 

My goal is I am developing an app and then distributing the app every two weeks for my stake holders. 

Here I need to run **fastlane ios beta** for every time.  Can I able to make this simple and can anyone suggest any thought how can I made it very simple without running the command **fastlane ios beta**

I need a good solution for this. Can anyone let me know your thoughts on this.

**Comment by max-ott** [comment]
I'm not sure what exactly you are looking for? If you are looking into continuous integration (CI/CD), you might want to look into https://docs.fastlane.tools/best-practices/continuous-integration/

If you do not want to trigger this automatically, when exactly should get a build triggered and how? Sounds more like you want to have a server (?) or service create a build every two weeks for you. That is not something that `fastlane` can do by itself. You'll need some kind of backend for that.
