### ISSUE TITLE
gym action doesn't export archive

### ISSUE THREAD

**Issue by OlexandrStepanov** [fastlane/fastlane#15965]
### Regression Information
- Breaking version: 2.141.0    
- Last working version: 2.140.0       

### Regression Description

After upgrading to 2.141.0 next command is not executed as part of `gym` action after successful archive:
`/usr/bin/xcrun .../xcbuild-safe.sh -exportArchive ...`

Effectively, this means that package (*.ipa file) has been not created and there is nothing to distribute.
The action itself succeeds though without any error.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
DEBUG [2020-02-03 18:39:48.51]: Loading 'fastlane-plugin-appcenter' plugin
INFO [2020-02-03 18:39:48.51]: gem 'fastlane-plugin-appcenter' is already installed
DEBUG [2020-02-03 18:39:48.72]: Using build_number: 111
INFO [2020-02-03 18:39:48.72]: ------------------------------
INFO [2020-02-03 18:39:48.72]: --- Step: default_platform ---
INFO [2020-02-03 18:39:48.72]: ------------------------------
INFO [2020-02-03 18:39:48.73]: Driving the lane 'ios build' 🚀
INFO [2020-02-03 18:39:48.73]: ----------------------------------
INFO [2020-02-03 18:39:48.73]: --- Step: mkdir ./dist || true ---
INFO [2020-02-03 18:39:48.73]: ----------------------------------
INFO [2020-02-03 18:39:48.73]: $ mkdir ./dist || true
INFO [2020-02-03 18:39:48.73]: ▸ mkdir: ./dist: File exists
INFO [2020-02-03 18:39:48.74]: -------------------------------------
INFO [2020-02-03 18:39:48.74]: --- Step: mkdir ./reports || true ---
INFO [2020-02-03 18:39:48.74]: -------------------------------------
INFO [2020-02-03 18:39:48.74]: $ mkdir ./reports || true
INFO [2020-02-03 18:39:48.74]: ▸ mkdir: ./reports: File exists
INFO [2020-02-03 18:39:48.74]: -----------------------------------------
INFO [2020-02-03 18:39:48.74]: --- Step: mkdir ./DerivedData || true ---
INFO [2020-02-03 18:39:48.74]: -----------------------------------------
INFO [2020-02-03 18:39:48.74]: $ mkdir ./DerivedData || true
INFO [2020-02-03 18:39:48.75]: ▸ mkdir: ./DerivedData: File exists
INFO [2020-02-03 18:39:48.75]: -------------------------------------
INFO [2020-02-03 18:39:48.75]: --- Step: export LANG=en_US.UTF-8 ---
INFO [2020-02-03 18:39:48.75]: -------------------------------------
INFO [2020-02-03 18:39:48.75]: $ export LANG=en_US.UTF-8
INFO [2020-02-03 18:39:48.76]: -----------------------------------------
INFO [2020-02-03 18:39:48.76]: --- Step: export LANGUAGE=en_US.UTF-8 ---
INFO [2020-02-03 18:39:48.76]: -----------------------------------------
INFO [2020-02-03 18:39:48.76]: $ export LANGUAGE=en_US.UTF-8
INFO [2020-02-03 18:39:48.76]: ---------------------------------------
INFO [2020-02-03 18:39:48.76]: --- Step: export LC_ALL=en_US.UTF-8 ---
INFO [2020-02-03 18:39:48.76]: ---------------------------------------
INFO [2020-02-03 18:39:48.76]: $ export LC_ALL=en_US.UTF-8
INFO [2020-02-03 18:39:48.77]: -----------------------------------------------------
INFO [2020-02-03 18:39:48.77]: Step: xcodebuild -resolvePackageDependencies -workspace ../ProjectX.xcworkspace -scheme ProjectX
INFO [2020-02-03 18:39:48.77]: -----------------------------------------------------
INFO [2020-02-03 18:39:48.77]: $ xcodebuild -resolvePackageDependencies -workspace ../ProjectX.xcworkspace -scheme ProjectX
INFO [2020-02-03 18:39:50.36]: ▸ Resolve Package Graph
INFO [2020-02-03 18:39:50.65]: ▸ Resolved source packages:
INFO [2020-02-03 18:39:50.65]: ▸ KeychainAccess: https://github.com/kishikawakatsumi/KeychainAccess @ 4.1.0
INFO [2020-02-03 18:39:50.65]: ▸ RxSwift: https://github.com/ReactiveX/RxSwift @ 5.0.1
INFO [2020-02-03 18:39:50.65]: ▸ Lottie: gitlab@gitlab.zeo.lcl:mackeeper/lottie-ios.git @ master
INFO [2020-02-03 18:39:50.65]: ▸ SwiftyBeaver: https://github.com/OlexandrStepanov/SwiftyBeaver @ master
INFO [2020-02-03 18:39:50.65]: ▸ Alamofire: https://github.com/Alamofire/Alamofire @ 4.9.1
INFO [2020-02-03 18:39:50.65]: ▸ RxDataSources: https://github.com/RxSwiftCommunity/RxDataSources @ 4.0.1
INFO [2020-02-03 18:39:50.65]: ▸ OHHTTPStubs: https://github.com/AliSoftware/OHHTTPStubs/ @ master
INFO [2020-02-03 18:39:50.65]: ▸ MapleBacon: https://github.com/JanGorman/MapleBacon @ 5.6.10
INFO [2020-02-03 18:39:50.66]: ▸ resolved source packages: KeychainAccess, RxSwift, Lottie, SwiftyBeaver, Alamofire, RxDataSources, OHHTTPStubs, MapleBacon
INFO [2020-02-03 18:39:50.67]: ------------------------------------
INFO [2020-02-03 18:39:50.67]: --- Step: increment_build_number ---
INFO [2020-02-03 18:39:50.67]: ------------------------------------
There does not seem to be a CURRENT_PROJECT_VERSION key set for this project.  Add this key to your target's expert build settings.

INFO [2020-02-03 18:39:50.90]: $ cd /Users/dev/builds/vcEFkxA2/0/DMD/iOS/projectx && agvtool new-version -all 111 && cd -
INFO [2020-02-03 18:39:51.09]: ▸ Setting version of project ProjectX to:
INFO [2020-02-03 18:39:51.09]: ▸ 111.
INFO [2020-02-03 18:39:51.12]: ▸ Also setting CFBundleVersion key (assuming it exists)
INFO [2020-02-03 18:39:51.16]: ▸ Updating CFBundleVersion in Info.plist(s)...
INFO [2020-02-03 18:39:51.19]: ▸ Updated CFBundleVersion in "ProjectX.xcodeproj/../ProjectX/Resources/Info.plist" to 111
INFO [2020-02-03 18:39:51.21]: ▸ Updated CFBundleVersion in "ProjectX.xcodeproj/../ProjectXTests/Info.plist" to 111
INFO [2020-02-03 18:39:51.23]: ▸ Updated CFBundleVersion in "ProjectX.xcodeproj/../ProjectXUITests/Info.plist" to 111
INFO [2020-02-03 18:39:51.23]: ▸ /Users/dev/builds/vcEFkxA2/0/DMD/iOS/projectx
INFO [2020-02-03 18:39:51.24]: -----------------------------------------
INFO [2020-02-03 18:39:51.24]: --- Step: update_project_provisioning ---
INFO [2020-02-03 18:39:51.24]: -----------------------------------------
INFO [2020-02-03 18:39:51.24]: You’re updating provisioning profiles directly in your project, but have you considered easier ways to do code signing?
INFO [2020-02-03 18:39:51.24]: https://docs.fastlane.tools/codesigning/GettingStarted/
INFO [2020-02-03 18:39:51.24]: Parsing mobile provisioning profile from '/Users/dev/Library/MobileDevice/Provisioning Profiles/5f44ed51-88a1-4c40-85e3-069e60ed2ac8.mobileprovision'
INFO [2020-02-03 18:39:51.25]: Going to update project './ProjectX.xcodeproj' with UUID
INFO [2020-02-03 18:39:51.35]: Updating target ProjectX...
WARN [2020-02-03 18:39:51.35]: Skipping configuration Debug as it doesn't match the filter 'Release'
INFO [2020-02-03 18:39:51.35]: Updating configuration Release...
WARN [2020-02-03 18:39:51.35]: Skipping configuration QA as it doesn't match the filter 'Release'
INFO [2020-02-03 18:39:51.35]: Updating target ProjectXTests...
WARN [2020-02-03 18:39:51.35]: Skipping configuration Debug as it doesn't match the filter 'Release'
INFO [2020-02-03 18:39:51.35]: Updating configuration Release...
WARN [2020-02-03 18:39:51.35]: Skipping configuration QA as it doesn't match the filter 'Release'
INFO [2020-02-03 18:39:51.35]: Updating target ProjectXUITests...
WARN [2020-02-03 18:39:51.35]: Skipping configuration Debug as it doesn't match the filter 'Release'
INFO [2020-02-03 18:39:51.35]: Updating configuration Release...
WARN [2020-02-03 18:39:51.35]: Skipping configuration QA as it doesn't match the filter 'Release'
INFO [2020-02-03 18:39:51.40]: Successfully updated project settings in './ProjectX.xcodeproj'
INFO [2020-02-03 18:39:51.42]: -----------------
INFO [2020-02-03 18:39:51.42]: --- Step: gym ---
INFO [2020-02-03 18:39:51.42]: -----------------
DEBUG [2020-02-03 18:39:51.43]: Parsing project file '/Users/dev/builds/vcEFkxA2/0/DMD/iOS/projectx/ProjectX.xcodeproj' to find selected provisioning profiles
DEBUG [2020-02-03 18:39:51.43]: Finding provision profiles for 'Release'
WARN [2020-02-03 18:39:51.48]: Resolving Swift Package Manager dependencies...
INFO [2020-02-03 18:39:51.48]: $ xcodebuild -resolvePackageDependencies -workspace ./ProjectX.xcworkspace -scheme ProjectX -configuration Release
INFO [2020-02-03 18:39:52.86]: ▸ Resolve Package Graph
INFO [2020-02-03 18:39:53.14]: ▸ Resolved source packages:
INFO [2020-02-03 18:39:53.14]: ▸   OHHTTPStubs: https://github.com/AliSoftware/OHHTTPStubs/ @ master
INFO [2020-02-03 18:39:53.14]: ▸   MapleBacon: https://github.com/JanGorman/MapleBacon @ 5.6.10
INFO [2020-02-03 18:39:53.15]: ▸   Alamofire: https://github.com/Alamofire/Alamofire @ 4.9.1
INFO [2020-02-03 18:39:53.15]: ▸   KeychainAccess: https://github.com/kishikawakatsumi/KeychainAccess @ 4.1.0
INFO [2020-02-03 18:39:53.15]: ▸   SwiftyBeaver: https://github.com/OlexandrStepanov/SwiftyBeaver @ master
INFO [2020-02-03 18:39:53.15]: ▸   RxDataSources: https://github.com/RxSwiftCommunity/RxDataSources @ 4.0.1
INFO [2020-02-03 18:39:53.15]: ▸   RxSwift: https://github.com/ReactiveX/RxSwift @ 5.0.1
INFO [2020-02-03 18:39:53.15]: ▸ resolved source packages: OHHTTPStubs, MapleBacon, Lottie, Alamofire, KeychainAccess, SwiftyBeaver, RxDataSources, RxSwift
INFO [2020-02-03 18:39:53.16]: $ xcodebuild -showBuildSettings -workspace ./ProjectX.xcworkspace -scheme ProjectX -configuration Release
DEBUG [2020-02-03 18:39:56.19]: Finding provision profiles for 'Release'
DEBUG [2020-02-03 18:39:56.22]: Finding provision profiles for 'Release'
DEBUG [2020-02-03 18:39:56.25]: Merging provisioning profile mappings
DEBUG [2020-02-03 18:39:56.25]: -------------------------------------
...............
INFO [2020-02-03 18:43:39.85]: ▸ Archive Succeeded
DEBUG [2020-02-03 18:43:40.11]: Stored the archive in: /Users/dev/Library/Developer/Xcode/Archives/2020-02-03/ProjectX 2020-02-03 18.39.56.xcarchive
INFO [2020-02-03 18:43:40.12]: Mapping dSYM(s) using generated BCSymbolMaps
INFO [2020-02-03 18:43:40.15]: $ dsymutil --symbol-map /Users/dev/Library/Developer/Xcode/Archives/2020-02-03/ProjectX\ 2020-02-03\ 18.39.56.xcarchive/BCSymbolMaps/D527E769-F3D7-3043-9839-2EEBEB85A197.bcsymbolmap /Users/dev/Library/Developer/Xcode/Archives/2020-02-03/ProjectX\ 2020-02-03\ 18.39.56.xcarchive/dSYMs/ProjectX.app.dSYM
INFO [2020-02-03 18:43:40.60]: $ dsymutil --symbol-map /Users/dev/Library/Developer/Xcode/Archives/2020-02-03/ProjectX\ 2020-02-03\ 18.39.56.xcarchive/BCSymbolMaps/58A5D5DB-7C8D-3C91-9018-36C367A5DD52.bcsymbolmap /Users/dev/Library/Developer/Xcode/Archives/2020-02-03/ProjectX\ 2020-02-03\ 18.39.56.xcarchive/dSYMs/ProjectX.app.dSYM
INFO [2020-02-03 18:43:40.99]: Compressing 1 dSYM(s)
INFO [2020-02-03 18:43:40.99]: $ cd '/Users/dev/Library/Developer/Xcode/Archives/2020-02-03/ProjectX 2020-02-03 18.39.56.xcarchive/dSYMs' && zip -r '/Users/dev/builds/vcEFkxA2/0/DMD/iOS/projectx/fastlane/dist/ProjectX.app.dSYM.zip' *.dSYM
INFO [2020-02-03 18:43:42.20]: ▸ updating: ProjectX.app.dSYM/ (stored 0%)
INFO [2020-02-03 18:43:42.20]: ▸ updating: ProjectX.app.dSYM/Contents/ (stored 0%)
INFO [2020-02-03 18:43:42.20]: ▸ updating: ProjectX.app.dSYM/Contents/Resources/ (stored 0%)
INFO [2020-02-03 18:43:42.20]: ▸ updating: ProjectX.app.dSYM/Contents/Resources/DWARF/ (stored 0%)
INFO [2020-02-03 18:43:42.20]: ▸ updating: ProjectX.app.dSYM/Contents/Resources/DWARF/ProjectX (deflated 70%)
INFO [2020-02-03 18:43:42.20]: ▸ updating: ProjectX.app.dSYM/Contents/Info.plist (deflated 52%)
INFO [2020-02-03 18:43:42.20]: Successfully exported and compressed dSYM file
INFO [2020-02-03 18:43:42.21]: Successfully generated documentation at path '/Users/dev/builds/vcEFkxA2/0/DMD/iOS/projectx/fastlane/README.md'
DEBUG [2020-02-03 18:43:42.22]: All plugins are up to date
INFO [2020-02-03 18:43:42.22]: fastlane.tools finished successfully 🎉
DEBUG [2020-02-03 18:43:42.22]: All plugins are up to date
</pre>
</details>

### Environment

<details>
  <pre><details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 10.14.6                                                 |
| Ruby                        | 2.5.5                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.21.1 (Apple Git-122.3)                    |
| Installation Source         | /usr/local/Cellar/fastlane/2.141.0/libexec/bin/fastlane |
| Host                        | Mac OS X 10.14.6 (18G103)                               |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.5/2.5.5_1/lib                  |
| OpenSSL Version             | OpenSSL 1.1.1c  28 May 2019                             |
| Is contained                | false                                                   |
| Is homebrew                 | false                                                   |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 11.3.1                                                  |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do
	sh 'mkdir ./dist || true'
  sh 'mkdir ./reports || true'
  sh 'mkdir ./DerivedData || true'
  
	sh 'export LANG=en_US.UTF-8'
	sh 'export LANGUAGE=en_US.UTF-8'
	sh 'export LC_ALL=en_US.UTF-8'
  
  # sh 'xcodebuild -resolvePackageDependencies -workspace ../ProjectX.xcworkspace -scheme ProjectX'
end


platform :ios do
  
  desc "Run SwiftLint on the project for code style and convensions check. Only diagnose, not autocorrect mode"
  lane :lint do
    swiftlint(
      mode: :lint,
      config_file: ".swiftlint.main.yml"     # The path of the configuration file (optional)
    )
  end
  
  desc "Run Unit and UI tests"
  lane :test do
    
    ENV["SKIP_SWIFTLINT"] = "YES"
    ENV["SKIP_SWIFTGEN"] = "YES"
    
  	# Run tests
  	test_args = {
  		scheme: ENV["XCODE_SCHEME"],
  		clean: true,
      device: "iPhone X",
      force_quit_simulator: true,
      prelaunch_simulator: true,
  		derived_data_path: "./fastlane/DerivedData",
  		code_coverage: false,
  		output_directory: "./fastlane/reports"
  	}

		test_args[:workspace] = "./" + ENV["XCODE_WORKSPACE"]

    begin
  	  scan(test_args)
    rescue => ex
      on_error(ex)
    end
    
  end
  
  desc "Builds the project and produces an .ipa. Pass in the build_number as a param. Default is 1."
  desc "Docs on how to pass in parameters are here: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Advanced.md#passing-parameters"
  lane :build do |options|
  	# Set default build number for local builds
  	build_number = "1"

  	# Read in value in case the user has specified input params
  	if options[:build_number]
  		build_number = options[:build_number]
  	end

  	increment_build_number(
  		build_number: build_number,
  		xcodeproj: "./" + ENV["XCODE_PROJECT"]
  	)

    begin
        gym
    rescue => ex
        on_error(ex)
    end
    
  end
  
  desc "Deploys the built IPA and symbols on MS AppCenter"
  lane :deploy_appcenter do |options|
    
  	appcenter_token = "1"
  	# Read in value in case the user has specified input params
  	if options[:token]
  		appcenter_token = options[:token]
  	end
  
    last_deploy_tag = "last_deploy"
  
    # Create changelog for deployment
    changelog_from_git_commits(pretty: "* %s",
                               merge_commit_filtering: "exclude_merges",
                               tag_match_pattern: "*" + last_deploy_tag + "*")
  
  
    # Tag the current commit to create changelog on next deploy
    add_git_tag(
      tag: last_deploy_tag,
      force: 1
    )
  
    appcenter_upload(
      api_token: appcenter_token,
      owner_name: ENV["APPCENTER_OWNER_NAME"],
      app_name: ENV["APPCENTER_APP_NAME"],
      ipa: "fastlane/dist/" + ENV["PRODUCT_NAME"] + ".ipa",
      dsym: "fastlane/dist/" + ENV["PRODUCT_NAME"] + ".app.dSYM.zip",
      destinations: ENV["APPCENTER_DISTRIBUTE_DESTINATIONS"],
      destination_type: ENV["APPCENTER_DISTRIBUTE_DESTINATION_TYPE"],
      release_notes: lane_context[SharedValues::FL_CHANGELOG],
      should_clip: false,
      notify_testers: true
    )

    slack(
      message: "iOS build succeeded!",
      success: true,
      slack_url: ENV["SLACK_WEBHOOK_URL"]
    )

  end

end

def on_error(exception)
  slack(
    message: "iOS build failed: " + exception.to_s,
    success: false,
    slack_url: ENV["SLACK_WEBHOOK_URL"]
  )
  UI.user_error!(exception.to_s)
end


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.company.ProjectX"
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.141.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-appcenter | 1.8.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.14.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.72.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.7        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.10.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.0        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| fastlane-plugin-appcenter | 1.8.0        |
</details>

*generated on:* **2020-02-03**
</details></pre>
</details>

**Comment by joshdholtz** [comment]
@OlexandrStepanov Thanks for reporting! Will look into as soon as I can for you!
