### ISSUE TITLE
Android X - HTML report generated is empty not showing screenshots or any body in it

### ISSUE THREAD

**Issue by isabelrios** [fastlane/fastlane#15969]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: 2.136 and before using AndroidX.
- Last working version: Previous version

### Regression Description

After all the screenshots are taken and the process finish correctly the HTML report is created but it is empty.

```
/MyPath/Library/Android/sdk/platform-tools/adb -s emulator-5554 pull /data/user/0//files//screengrab/fr-FR/images/screenshots /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/d20191120-19603-18h7ul8
[14:04:40]: Screenshots copied to fastlane/metadata/android/phoneScreenshots
[14:04:40]: Generating HTML Report
[14:04:40]: Successfully created HTML file with an overview of all the screenshots: '~/fenix/fastlane/metadata/android/screenshots.html'
[14:04:40]: Captured 26 screenshots! 📷✨
```

This used to work for me before the latest update to 2.136 and before using AndroidX.

I have noticed also that if I run more than one language, the previous screenshots are removed, only the latest one are available. Looks like the folder structure for each language is not kept. For example for French, I don't see the folder 'fr-FR' copied to my current directory, only 'phoneScreenshots' folder is created with all the screenshots under it.
 have tried to manually change the directories but so far no luck. Any idea about the issue, what should I modify? is it something known pending to be fixed?

Thank you in advance!

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

Please see issue #15690 reporting this issue several months ago with all the info. The behaviour is exactly the same.
You will notice that I'm using Fastlane 2.137.0, the reason is that I can't update to Fastlane 2.141.0 because it gives errors when trying to pull the screenshots from the device.

**Comment by janpio** [comment]
Reopened original issue https://github.com/fastlane/fastlane/issues/15690
