### ISSUE TITLE
Expand Gym stderror/stdout filters to add useful parts of the gym log in case of build/archive failure

### ISSUE THREAD

**Issue by giantslogik** [fastlane/fastlane#15967]
#### Motivation Behind Feature
This feature will make the errors appear on CI web console rather than in the gym log on a remote build server.

#### Feature Description
Most cases when the archiving fails: The CI fastlane log (in my case jenkins) contains something like:

      ** ARCHIVE FAILED **
      The following build commands failed:
       .....
       Exit status: 65

The actual error is in the gym log at buildlog_path:
for eg.
       error Unable to resolve module `react-native-screens` from `node_modules/react-navigation-tabs/src/navigators/createBottomTabNavigator.js`: react-native-screens could not be found within the project.
       ....
       + exit 2

**Displaying the last 100 lines before the error from gym log to stdout/err will work.**

#### Alternatives or Workarounds
Check the gym log manually.

Note: I have seen this for a number of archiving errors, especially the exit status 65 cases. In another case the gym log reported i was missing Xcode system resources, while the CI console had the exit status 65.

**Comment by janpio** [comment]
Can you show a longer example that gives some context? 

I think the `xcodebuild` logs that are printed are actually via `xcpretty`, which might influence what is being printed (and which can be disabled via `disable_xcpretty`).

**Comment by giantslogik** [comment]
On Jenkins CI full log.
<details>
  <pre> 06:50:03 ▸ Copying /Users/User/.jenkins/workspace/iosbuild/fonts/Nunito\ Sans-BoldItalic.ttf
06:50:03 ▸ Copying /Users/User/.jenkins/workspace/iosbuild/fonts/Nunito\ Sans-Bold.ttf
06:50:03 ▸ Copying /Users/User/.jenkins/workspace/iosbuild/fonts/Nunito\ Sans-BlackItalic.ttf
06:50:03 ▸ Copying /Users/User/.jenkins/workspace/iosbuild/fonts/Nunito\ Sans-Black.ttf
06:50:03 ▸ Copying /Users/User/.jenkins/workspace/iosbuild/App.js
06:50:03 ▸ Compiling LaunchScreen.xib
06:50:03 ▸ Processing Info.plist
06:50:03 ▸ Running script 'Bundle React Native code and images'
06:50:03     the transform cache was reset.
06:50:03 
06:50:03 ❌  error: File /Users/User/.jenkins/workspace/iosbuild/ios/derived/Build/Intermediates.noindex/ArchiveIntermediates/MyApp Release/BuildProductsPath/Release-iphoneos/MyApp.app/main.jsbundle does not exist. This must be a bug with
06:50:03 
06:50:03 
06:50:03 ▸ Generating 'MyApp.app.dSYM'
06:50:03     The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.2.99. (in target 'RnTestExceptionHandler' from project 'Pods')
06:50:03 ** ARCHIVE FAILED **
06:50:03 
06:50:03 
06:50:03 The following build commands failed:
06:50:03 	PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/User/.jenkins/workspace/iosbuild/ios/derived/Build/Intermediates.noindex/ArchiveIntermediates/MyApp\ Release/IntermediateBuildFilesPath/MyApp.build/Release-iphoneos/MyApp.build/Script-00DD1BFF1BD5951E006B06BC.sh
06:50:03 (1 failure)
06:50:03 [04:50:03]: Exit status: 65
06:50:03 
06:50:03 +---------------+-------------------------+
06:50:03 |            Build environment            |
06:50:03 +---------------+-------------------------+
06:50:03 | xcode_path    | /Applications/Xcode.app |
06:50:03 | gym_version   | 2.141.0                 |
06:50:03 | export_method | ad-hoc                  |
06:50:03 | sdk           | iPhoneOS13.2.sdk        |
06:50:03 +---------------+-------------------------+
06:50:03 
06:50:03 [04:50:03]: ▸ warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.2.99. (in target 'RnTestExceptionHandler' from project 'Pods')
06:50:03 [04:50:03]: ▸ Result bundle written to path:
06:50:03 [04:50:03]: ▸ 	/Users/User/.jenkins/workspace/iosbuild/ios/outputs/MyApp.result
06:50:03 [04:50:03]: 
06:50:03 [04:50:03]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
</pre>
</details>

In the gym log:
<details>
  <pre> export XPCSERVICES_FOLDER_PATH=MyApp.app/XPCServices
    export YACC=yacc
    export arch=undefined_arch
    export variant=normal
    /bin/sh -c /Users/User/.jenkins/workspace/iosbuild/ios/derived/Build/Intermediates.noindex/ArchiveIntermediates/MyApp\\\ Release/IntermediateBuildFilesPath/MyApp.build/Release-iphoneos/MyApp.build/Script-00DD1BFF1BD5951E006B06BC.sh
+ DEST='/Users/User/.jenkins/workspace/iosbuild/ios/derived/Build/Intermediates.noindex/ArchiveIntermediates/MyApp Release/BuildProductsPath/Release-iphoneos/MyApp.app'
+ [[ Release = *Debug* ]]
+ [[ -n '' ]]
+ case "$CONFIGURATION" in
+ DEV=false
+++ dirname ../node_modules/react-native/scripts/react-native-xcode.sh
++ cd ../node_modules/react-native/scripts/..
++ pwd
+ REACT_NATIVE_DIR=/Users/User/.jenkins/workspace/iosbuild/node_modules/react-native
+ PROJECT_ROOT=/Users/User/.jenkins/workspace/iosbuild/node_modules/react-native/../..
+ cd /Users/User/.jenkins/workspace/iosbuild/node_modules/react-native/../..
+ '[' -z '' ']'
+ export NVM_DIR=/Users/User/.nvm
+ NVM_DIR=/Users/User/.nvm
+ [[ -n '' ]]
+ [[ -s index.ios.js ]]
+ ENTRY_FILE=index.js
+ [[ -s /Users/User/.nvm/nvm.sh ]]
++ command -v brew
+ [[ -x /usr/local/bin/brew ]]
++ brew --prefix nvm
+ [[ -s /usr/local/Cellar/nvm/0.35.2/nvm.sh ]]
+ [[ -x /Users/User/.nodenv/bin/nodenv ]]
++ command -v brew
+ [[ -x /usr/local/bin/brew ]]
++ brew --prefix nodenv
+ [[ -x /usr/local/Cellar/nodenv/1.3.1/bin/nodenv ]]
+ [[ ! -x node ]]
+ [[ -d /Users/User/.anyenv/bin ]]
+ source /Users/User/.jenkins/workspace/iosbuild/node_modules/react-native/scripts/node-binary.sh
++ '[' -z node ']'
++ type node
+ '[' -z '' ']'
+ export NODE_ARGS=
+ NODE_ARGS=
+ '[' -z '' ']'
+ export CLI_PATH=/Users/User/.jenkins/workspace/iosbuild/node_modules/react-native/cli.js
+ CLI_PATH=/Users/User/.jenkins/workspace/iosbuild/node_modules/react-native/cli.js
+ '[' -z '' ']'
+ BUNDLE_COMMAND=bundle
+ [[ -z '' ]]
+ CONFIG_ARG=
+ BUNDLE_FILE='/Users/User/.jenkins/workspace/iosbuild/ios/derived/Build/Intermediates.noindex/ArchiveIntermediates/MyApp Release/BuildProductsPath/Release-iphoneos/MyApp.app/main.jsbundle'
+ node /Users/User/.jenkins/workspace/iosbuild/node_modules/react-native/cli.js bundle --entry-file index.js --platform ios --dev false --reset-cache --bundle-output '/Users/User/.jenkins/workspace/iosbuild/ios/derived/Build/Intermediates.noindex/ArchiveIntermediates/MyApp Release/BuildProductsPath/Release-iphoneos/MyApp.app/main.jsbundle' --assets-dest '/Users/User/.jenkins/workspace/iosbuild/ios/derived/Build/Intermediates.noindex/ArchiveIntermediates/MyApp Release/BuildProductsPath/Release-iphoneos/MyApp.app' --sourcemap-output ./sourcemap.ios.map
warning: the transform cache was reset.
Loading dependency graph, done.
error Unable to resolve module `react-native-screens` from `node_modules/react-navigation-tabs/src/navigators/createBottomTabNavigator.js`: react-native-screens could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*. Run CLI with --verbose flag for more details.
Error: Unable to resolve module `react-native-screens` from `node_modules/react-navigation-tabs/src/navigators/createBottomTabNavigator.js`: react-native-screens could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
    at ModuleResolver.resolveDependency (/Users/User/.jenkins/workspace/iosbuild/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:186:15)
    at ResolutionRequest.resolveDependency (/Users/User/.jenkins/workspace/iosbuild/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/User/.jenkins/workspace/iosbuild/node_modules/metro/src/node-haste/DependencyGraph.js:282:16)
    at Object.resolve (/Users/User/.jenkins/workspace/iosbuild/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at /Users/User/.jenkins/workspace/iosbuild/node_modules/metro/src/DeltaBundler/traverseDependencies.js:426:31
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/User/.jenkins/workspace/iosbuild/node_modules/metro/src/DeltaBundler/traverseDependencies.js:423:18)
    at /Users/User/.jenkins/workspace/iosbuild/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/User/.jenkins/workspace/iosbuild/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
+ [[ false != true ]]
+ [[ ! -f /Users/User/.jenkins/workspace/iosbuild/ios/derived/Build/Intermediates.noindex/ArchiveIntermediates/MyApp Release/BuildProductsPath/Release-iphoneos/MyApp.app/main.jsbundle ]]
+ echo 'error: File /Users/User/.jenkins/workspace/iosbuild/ios/derived/Build/Intermediates.noindex/ArchiveIntermediates/MyApp Release/BuildProductsPath/Release-iphoneos/MyApp.app/main.jsbundle does not exist. This must be a bug with'
error: File /Users/User/.jenkins/workspace/iosbuild/ios/derived/Build/Intermediates.noindex/ArchiveIntermediates/MyApp Release/BuildProductsPath/Release-iphoneos/MyApp.app/main.jsbundle does not exist. This must be a bug with
+ echo 'React Native, please report it here: https://github.com/facebook/react-native/issues'
React Native, please report it here: https://github.com/facebook/react-native/issues
+ exit 2

GenerateDSYMFile /Users/User/.jenkins/workspace/iosbuild/ios/derived/Build/Intermediates.noindex/ArchiveIntermediates/MyApp\ Release/BuildProductsPath/Release-iphoneos/MyApp.app.dSYM /Users/User/.jenkins/workspace/iosbuild/ios/derived/Build/Intermediates.noindex/ArchiveIntermediates/MyApp\ Release/InstallationBuildProductsLocation/Applications/MyApp.app/MyApp (in target 'MyApp' from project 'MyApp')
    cd /Users/User/.jenkins/workspace/iosbuild/ios
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil /Users/User/.jenkins/workspace/iosbuild/ios/derived/Build/Intermediates.noindex/ArchiveIntermediates/MyApp\ Release/InstallationBuildProductsLocation/Applications/MyApp.app/MyApp -o /Users/User/.jenkins/workspace/iosbuild/ios/derived/Build/Intermediates.noindex/ArchiveIntermediates/MyApp\ Release/BuildProductsPath/Release-iphoneos/MyApp.app.dSYM

warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.2.99. (in target 'RnTestExceptionHandler' from project 'Pods')

Result bundle written to path:
	/Users/User/.jenkins/workspace/iosbuild/ios/outputs/MyApp.result
 </pre>
</details>

**Comment by revolter** [comment]
I think that `xcodebuild`s output is too verbose, but it would be great if we could filter out the errors and present them in terminal. It would save us a looot of time.

@joshdholtz, Would you happen to have any idea for this?
