### ISSUE TITLE
Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" and key 'method': expected one of {}

### ISSUE THREAD

**Issue by zakabluk** [fastlane/fastlane#15964]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I lanched fastalene "fastlane build"  and expect get local app file.
But I got error.
```
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/3c/mlppx6h92875_71f3w39c8v00000gn/T/gym_config20200203-9409-1rhcgra.plist -archivePath '/Users/hq/Library/Developer/Xcode/Archives/2020-02-03/BLU 2020-02-03 17.00.39.xcarchive' -exportPath /var/folders/3c/mlppx6h92875_71f3w39c8v00000gn/T/gym_output20200203-9409-fu1vea
497 2020-02-03 17:02:27.381 xcodebuild[10097:747090] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/3c/mlppx6h92875_71f3w39c8v00000gn/T/BLU_2020-02-03_17-02-27.380.xcdistributionlogs'.
498 2020-02-03 17:02:27.488 xcodebuild[10097:747090] [MT] IDEDistributionMethodManager: -[IDEDistributionMethodManager orderedDistributionMethodsForTask:archive:]: Error = Error Domain=IDEDistributionMethodManagerErrorDomain Code=2 "Unknown Distribution Error" UserInfo={NSLocalizedDescription=Unknown Distribution Error}
499 error: exportArchive: exportOptionsPlist error for key 'method': expected one of {}, but found app-store
500 Error Domain=IDEFoundationErrorDomain Code=1 "exportOptionsPlist error for key 'method': expected one of {}, but found app-store" UserInfo={NSLocalizedDescription=exportOptionsPlist error for key 'method': expected one of {}, but found app-store}
```
My fastlane file is simple:
```
  desc "Build application"
  lane :build do
    install_provisioning_profile(path: ENV["PROVISIONING_PROFILE"])
    import_certificate(certificate_path: ENV["CERT_PATH"],
                       certificate_password: ENV["CERT_PWD"],
                       keychain_name: ENV["KEYCHAIN_NAME"],
                       keychain_password: ENV["HQ_PWD"])
    gym(
      scheme: ENV["SCHEME"],
      clean: true,
      output_directory: "build",
      export_options: {
        method: 'app-store'
      }
    )
```
In detaile logs of fastlane I find out strange message:
```
e' from project 'BLU')
    cd /Users/zakabluk/Documents/git/githubBLU/mobile-ios/app/BLU
    builtin-RegisterExecutionPolicyException /Users/zakabluk/Library/Developer/Xcode/DerivedData/BLU-gvvvkwpjdlklocherkkkepucneic/Build/Intermediates.noindex/ArchiveIntermediates/BLU/InstallationBuildProductsLocation/Applications/BLU.app
note: Execution policy exception registration failed and was skipped: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (in target 'BLU' from project 'BLU')

```
maybe this help for understand my issue.

```

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15                                                          |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.22.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15 (19A603)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.2.1                                                         |

```

TRace from fastlane build --verbose

`
ERROR [2020-02-04 17:12:34.28]: fastlane finished with errors
Traceback (most recent call last):
        34: from /usr/local/bin/fastlane:23:in `<main>'
        33: from /usr/local/bin/fastlane:23:in `load'
        32: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/bin/fastlane:23:in `<top (required)>'
        31: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
        30: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        29: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
        28: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        27: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        26: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        25: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        24: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        23: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
        22: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        21: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
        20: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        19: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        16: from Fastfile:31:in `block (2 levels) in parsing_binding'
        15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
        12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
        11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
        10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
         9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
         8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/actions/build_app.rb:66:in `run'
         7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/gym/lib/gym/manager.rb:19:in `work'
         6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/gym/lib/gym/runner.rb:35:in `run'
         5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/gym/lib/gym/runner.rb:148:in `package_app'
         4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/command_executor.rb:89:in `execute'
         3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/gym/lib/gym/runner.rb:152:in `block in package_app'
         2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/gym/lib/gym/error_handler.rb:112:in `handle_package_error'
         1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/ui/interface.rb:163:in `build_failure!': Error packaging up the application (FastlaneCore::Interface::FastlaneBuildFailure)
        34: from /usr/local/bin/fastlane:23:in `<main>'
        33: from /usr/local/bin/fastlane:23:in `load'
        32: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/bin/fastlane:23:in `<top (required)>'
        31: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
        30: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        29: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
        28: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        27: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        26: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        25: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        24: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        23: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
        22: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        21: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
        20: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        19: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        16: from Fastfile:31:in `block (2 levels) in parsing_binding'
        15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
        12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
        11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
        10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
         9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
         8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/actions/build_app.rb:66:in `run'
         7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/gym/lib/gym/manager.rb:19:in `work'
         6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/gym/lib/gym/runner.rb:35:in `run'
         5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/gym/lib/gym/runner.rb:148:in `package_app'
         4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/command_executor.rb:89:in `execute'
         3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/gym/lib/gym/runner.rb:152:in `block in package_app'
         2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/gym/lib/gym/error_handler.rb:112:in `handle_package_error'
         1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/ui/interface.rb:163:in `build_failure!': [!] Error packaging up the application (FastlaneCore::Interface::FastlaneBuildFailure)

`

**Comment by zakabluk** [comment]
I have Fixed when:

For target and progect set: skip install - yes (Build settings) .

Delete exceed rows for entitlements . 

and changed script for Strip Architectures:

    # This removes the unsupported archetypes from frameworks on the build phase.
    echo "Target architectures: $ARCHS"
    APP_PATH="${TARGET_BUILD_DIR}/${WRAPPER_NAME}"
    find "$APP_PATH" -name '*.framework' -type d | while read -r FRAMEWORK
    do
    FRAMEWORK_EXECUTABLE_NAME=$(defaults read "$FRAMEWORK/Info.plist" CFBundleExecutable)
    FRAMEWORK_EXECUTABLE_PATH="$FRAMEWORK/$FRAMEWORK_EXECUTABLE_NAME"
    echo "Executable is $FRAMEWORK_EXECUTABLE_PATH"
    echo $(lipo -info "$FRAMEWORK_EXECUTABLE_PATH")
    FRAMEWORK_TMP_PATH="$FRAMEWORK_EXECUTABLE_PATH-tmp"
    # remove simulator's archs if location is not simulator's directory
    case "${TARGET_BUILD_DIR}" in
    *"iphonesimulator")
      echo "No need to remove archs"
      ;;
    *)
      if $(lipo "$FRAMEWORK_EXECUTABLE_PATH" -verify_arch "i386") ; then
      lipo -output "$FRAMEWORK_TMP_PATH" -remove "i386" "$FRAMEWORK_EXECUTABLE_PATH"
      echo "i386 architecture removed"
      rm "$FRAMEWORK_EXECUTABLE_PATH"
      mv "$FRAMEWORK_TMP_PATH" "$FRAMEWORK_EXECUTABLE_PATH"
      fi
      if $(lipo "$FRAMEWORK_EXECUTABLE_PATH" -verify_arch "x86_64") ; then
      lipo -output "$FRAMEWORK_TMP_PATH" -remove "x86_64" "$FRAMEWORK_EXECUTABLE_PATH"
      echo "x86_64 architecture removed"
      rm "$FRAMEWORK_EXECUTABLE_PATH"
      mv "$FRAMEWORK_TMP_PATH" "$FRAMEWORK_EXECUTABLE_PATH"
      fi
      ;;
    esac
    echo "Completed for executable $FRAMEWORK_EXECUTABLE_PATH"
    echo $(lipo -info "$FRAMEWORK_EXECUTABLE_PATH")
    done

**Comment by ciekawy** [comment]
wonder if its possible to automate this by configuring or triggering the script from `Fastfile` ...
