### ISSUE TITLE
Error "Unknown method 'params'" when running cocoapods with clean_install:true

### ISSUE THREAD

**Issue by daanoz** [fastlane/fastlane#15960]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Saw a "Deprecated" notice when I was using the `clean` flag, so tried to migrate to `clean_install` but I keep getting this "Unknown method 'params'" error message... Already tried reinstalling fastlane, cocoapods & bundler, but it doesn't seem to make a difference.

##### Command executed
fastlane run cocoapods clean_install:true

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> DEBUG [2020-02-01 16:17:11.99]: Checking if there are any plugins that should be loaded...
DEBUG [2020-02-01 16:17:12.12]: Using clean_install: true
INFO [2020-02-01 16:17:12.13]: -----------------------
INFO [2020-02-01 16:17:12.13]: --- Step: cocoapods ---
INFO [2020-02-01 16:17:12.13]: -----------------------
INFO [2020-02-01 16:17:12.15]: gem 'cocoapods' is already installed
ERROR [2020-02-01 16:17:12.15]: Unknown method 'params' </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.2                                     |
| Ruby                        | 2.4.5                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0 (Apple Git-122)          |
| Installation Source         | ~/.rbenv/versions/2.4.5/bin/fastlane        |
| Host                        | Mac OS X 10.15.2 (19C57)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.5/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2q  20 Nov 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version '2.117.1'
identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)


platform :ios do
  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    match(app_identifier: identifier, type: 'development', readonly: false)
  end
end


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.mycompany.app"
apple_id "apple@mycompany.com"
package_name "com.mycompany.app"
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.141.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.14.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.72.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.7        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.10.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.0        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| openssl                   | 2.0.9        |
| json                      | 2.3.0        |
| io-console                | 0.4.6        |
| psych                     | 2.2.2        |
</details>

*generated on:* **2020-02-01**
</details>

**Comment by janpio** [comment]
What version of cocoapods are you using?

**Comment by daanoz** [comment]
```
$ pod --version 
1.8.4
```

**Comment by janpio** [comment]
Versions >1.7 should have and use `clean_install`, so you should be good there.

Can you run with `--verbose` and post the complete output please?

**Comment by janpio** [comment]
There is actually a PR that seems to fix this problem: https://github.com/fastlane/fastlane/pull/15947

**Comment by daanoz** [comment]
Ah great 👍, missed that one, only checked the issues.
