### ISSUE TITLE
Deliver: is it possible to "manually release" via fastlane?

### ISSUE THREAD

**Issue by sgolovine** [fastlane/fastlane#15977]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Tool: Deliver
Documentation Question: No
Third Party Plugin Question: No

#### Question Description

If I were to upload an IPA to App Store Connect using `deliver`, specifying that    `submit_for_review: true` and `automatic_release: false`, can I use fastlane to manually release the version to the app store once it's approved?

**Comment by giantslogik** [comment]
I've tried this and this and it doesn't work. 

On the other hand though could be a general xcode 11.3+fastlane+deliver problem.

**Comment by Hiroto-N** [comment]
You can do it using spaceship - [the Spaceship docs](https://github.com/fastlane/fastlane/blob/master/spaceship/docs/AppStoreConnect.md) has a bit more details, but in essence something like the following should work:

```ruby

:lane release_app do |options|
  Spaceship::Tunes.login # assuming FASTLANE_USER and FASTLANE_PASSWORD are set
  Spaceship::Tunes.select_team(team_id) # if required
  
  app = Spaceship::Tunes::Application.find("com.my.app")
  edit_version = app.edit_version
  
  # ...  some validation of version etc ...
  
  edit_version.release!
end
```

**Comment by sgolovine** [comment]
Thanks, I'll give that a try
