### ISSUE TITLE
Getting a deprecation notice for authentication via URL query parameters because of Octokit

### ISSUE THREAD

**Issue by eygraber** [fastlane/fastlane#15979]
I started getting emails from GitHub saying that I am using a deprecated authentication method via OCtokit. Fastlane is the only thing in my project that uses Octokit. They released a new version that fixes this.

[See here for more details](https://github.com/octokit/octokit.rb/issues/1191)

**Comment by eygraber** [comment]
I don't use fastlane locally, and cannot access my CI right now to get that output. This is a pretty cut and dry issue. I don't think you need the output to deal with it.

**Comment by janpio** [comment]
What action are you using? We have quite a few of them, and multiple could talk to Github.

**Comment by eygraber** [comment]
As far as I can tell, we only use `set_github_release` and `get_github_release`
