### ISSUE TITLE
frameit is broken for me in release 2.141.0

### ISSUE THREAD

**Issue by matrouthier** [fastlane/fastlane#15972]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: 2.141.0
- Last working version: 2.137.0, I'm not sure about versions in between

### Regression Description

when running frameit, an error prevents the completion of the process.
The error message is: 
461 : unexpected token at [And then a long json blob]

The json data contains an unterminated field (comma is missing) :
"originGeometry": +45+50

Something of interest : I have replaced the frameit folder from version 2.137.0 and patched it in version 2.141.0 and it worked fine.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>416: unexpected token at '{
  "image": {
    "name": "/var/folders/zg/q2sjz47n79x50pmndjkh37mr0000gn/T/mini_magick20200204-2402-z9p45e.png[0]",
    "format": "PNG",
    "formatDescription": "Portable Network Graphics",
    "mimeType": "image/png",
    "class": "DirectClass",
    "geometry": {
      "width": 1174,
      "height": 2363,
      "x": 0,
      "y": 0
    },
    "units": "Undefined",
    "type": "TrueColorAlpha",
    "endianess": "Undefined",
    "colorspace": "sRGB",
    "depth": 8,
    "baseDepth": 8,
    "channelDepth": {
      "alpha": 8,
      "red": 8,
      "green": 8,
      "blue": 8
    },
    "pixels": 2774162,
    "imageStatistics": {
      "all": {
        "min": "0",
        "max": "255",
        "mean": "150.568",
        "standardDeviation": "117.41",
        "kurtosis": "-1.76432",
        "skewness": "-0.357689"
      }
    },
    "channelStatistics": {
      "alpha": {
        "min": "0",
        "max": "255",
        "mean": "250.498",
        "standardDeviation": "33.2413",
        "kurtosis": "51.869",
        "skewness": "7.32447"
      },
      "red": {
        "min": "0",
        "max": "255",
        "mean": "209.395",
        "standardDeviation": "85.8252",
        "kurtosis": "1.14886",
        "skewness": "-1.67541"
      },
      "green": {
        "min": "0",
        "max": "255",
        "mean": "202.201",
        "standardDeviation": "86.5189",
        "kurtosis": "0.513266",
        "skewness": "-1.41334"
      },
      "blue": {
        "min": "0",
        "max": "255",
        "mean": "186.175",
        "standardDeviation": "102.245",
        "kurtosis": "-1.03567",
        "skewness": "-0.909505"
      }
    },
    "alpha": "#00000000",
    "renderingIntent": "Perceptual",
    "gamma": 0.45455,
    "chromaticity": {
      "redPrimary": {
        "x": 0.64,
        "y": 0.33
      },
      "greenPrimary": {
        "x": 0.3,
        "y": 0.6
      },
      "bluePrimary": {
        "x": 0.15,
        "y": 0.06
      },
      "whitePrimary": {
        "x": 0.3127,
        "y": 0.329
      }
    },
    "backgroundColor": "#FFFFFFFF",
    "borderColor": "#DFDFDFFF",
    "matteColor": "#BDBDBDFF",
    "transparentColor": "#00000000",
    "interlace": "None",
    "intensity": "Undefined",
    "compose": "Over",
    "pageGeometry": {
      "width": 1265,
      "height": 2466,
      "x": 45,
      "y": 50
    },
    "originGeometry": +45+50
    "dispose": "Undefined",
    "iterations": 0,
    "compression": "Zip",
    "orientation": "Undefined",
    "properties": {
      "date:create": "2020-02-04T22:37:36-05:00",
      "date:modify": "2020-02-04T22:37:36-05:00",
      "png:bKGD": "chunk was found (see Background color, above)",
      "png:caNv": "width=1265, height=2466, x_offset=45, y_offset=50",
      "png:cHRM": "chunk was found (see Chromaticity, above)",
      "png:gAMA": "gamma=0.45454544 (See Gamma, above)",
      "png:IHDR.bit-depth-orig": "8",
      "png:IHDR.bit_depth": "8",
      "png:IHDR.color-type-orig": "6",
      "png:IHDR.color_type": "6 (RGBA)",
      "png:IHDR.interlace_method": "0 (Not interlaced)",
      "png:IHDR.width,height": "1174, 2363",
      "png:sRGB": "intent=0 (Perceptual Intent)",
      "png:text": "2 tEXt/zTXt/iTXt chunks were found",
      "png:tIME": "2020-02-04T17:37:36Z",
      "signature": "6fcc3cc42c2aaf38e6f4091ed20ad88cfab4091bb419d5ecf19468458e1523b3"
    },
    "artifacts": {
      "filename": "/var/folders/zg/q2sjz47n79x50pmndjkh37mr0000gn/T/mini_magick20200204-2402-z9p45e.png[0]"
    },
    "tainted": false,
    "filesize": "217752B",
    "numberPixels": "2.77416M",
    "pixelsPerSecond": "39.6309MB",
    "userTime": "0.070u",
    "elapsedTime": "0:01.069",
    "version": "ImageMagick 6.9.9-19 Q16 x86_64 2017-10-27 http://www.imagemagick.org"
  }
}
]'</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by joshdholtz** [comment]
@matrouthier Which frameit folder did you replace? 🤔 This is a very strange error

**Comment by matrouthier** [comment]
I copied `/Library/Ruby/Gems/2.6.0/gems/fastlane-2.137.0/frameit` over `/Library/Ruby/Gems/2.6.0/gems/fastlane-2.141.0/frameit` and it did not produce the error anymore.

**Comment by gki** [comment]
I'm facing same error.

here is `fastlane env` output.
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.3                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.22.0                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.15.3 (19D76)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.0/lib            |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.3.1                                      |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | ja_JP.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_app_store
  end

  lane :screenshots do
    frameit(path: './fastlane/screenshots/', white: true)
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("my identifier") # The bundle identifier of your app
apple_id("my apple id") # Your Apple email address

itc_team_id("1234567") # App Store Connect Team ID
team_id("MYTEAMID") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.141.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                   | Version      |
| --------------------- | ------------ |
| did_you_mean          | 1.1.0        |
| rouge                 | 2.0.7        |
| xcpretty              | 0.3.0        |
| terminal-notifier     | 2.0.0        |
| multipart-post        | 2.0.0        |
| word_wrap             | 1.0.0        |
| public_suffix         | 2.0.5        |
| colored               | 1.2          |
| commander-fastlane    | 4.4.6        |
| http-cookie           | 1.0.3        |
| faraday-cookie_jar    | 0.0.6        |
| faraday_middleware    | 0.13.1       |
| gh_inspector          | 1.1.3        |
| multi_xml             | 0.6.0        |
| rubyzip               | 1.3.0        |
| security              | 0.1.3        |
| jwt                   | 2.1.0        |
| uber                  | 0.1.0        |
| declarative-option    | 0.1.0        |
| representable         | 3.0.4        |
| mini_mime             | 1.0.2        |
| signet                | 0.12.0       |
| httpclient            | 2.8.3        |
| google-api-client     | 0.36.4       |
| tty-spinner           | 0.9.3        |
| tty-cursor            | 0.7.1        |
| tty-screen            | 0.7.0        |
| faraday               | 0.17.3       |
| openssl               | 2.1.0        |
| json                  | 2.3.0        |
| highline              | 1.7.10       |
| io-console            | 0.4.6        |
| excon                 | 0.72.0       |
| CFPropertyList        | 3.0.2        |
| mini_portile2         | 2.3.0        |
| nokogiri              | 1.8.1        |
| plist                 | 3.5.0        |
| atomos                | 0.1.3        |
| colored2              | 3.1.2        |
| nanaimo               | 0.2.6        |
| xcodeproj             | 1.14.0       |
| claide                | 1.0.3        |
| googleauth            | 0.10.0       |
| google-cloud-env      | 1.3.0        |
| google-cloud-errors   | 1.0.0        |
| google-cloud-core     | 1.5.0        |
| digest-crc            | 0.4.1        |
| google-cloud-storage  | 1.25.1       |
| unf                   | 0.1.4        |
| domain_name           | 0.5.20190701 |
| babosa                | 1.0.3        |
| fastimage             | 2.1.7        |
| bundler               | 1.16.3       |
| terminal-table        | 1.8.0        |
| unicode-display_width | 1.6.1        |
| addressable           | 2.7.0        |
| multi_json            | 1.14.1       |
| memoist               | 0.16.2       |
| os                    | 1.0.1        |
| psych                 | 3.0.2        |
| retriable             | 3.1.2        |
| declarative           | 0.0.10       |
</details>


*generated on:* **2020-02-11**
</details>

**Comment by gki** [comment]
Also, tested some versions.

2.141.0 -> Failed.
2.139.0 -> Failed by the same error with 2.141.0
2.138.0 -> No error.
2.137.0 -> No error.

**Comment by motoko89** [comment]
I run into the same issue, both for 2.140.0 ad 2.142.0
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.3                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.22.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.3 (19D76)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.3.1                                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.142.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.14.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.2        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.71.0       |
| faraday                   | 0.17.1       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.9.0        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.4.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>


*generated on:* **2020-02-20**
</details>

**Comment by tehsven** [comment]
This commit appears to be the culprit: https://github.com/fastlane/fastlane/commit/6a31aafa26062eded4e5a6cb38a49cb9aba4d0ef

I manually reverted that change locally and got `fastlane frameit` working without the `unexpected token at` error.
