### ISSUE TITLE
Permission denied @ dir_s_mkdir - /var/empty/.fastlane[0m (Errno::EACCES)

### ISSUE THREAD

**Issue by prejithp-repo** [fastlane/fastlane#15989]
Getting error while connecting my jenkins with fastlane

```
/usr/lib/ruby/2.5.0/fileutils.rb:232:in `mkdir': [31m[!] Permission denied @ dir_s_mkdir - /var/empty/.fastlane[0m (Errno::EACCES)
	from /usr/lib/ruby/2.5.0/fileutils.rb:232:in `fu_mkdir'
	from /usr/lib/ruby/2.5.0/fileutils.rb:210:in `block (2 levels) in mkdir_p'
	from /usr/lib/ruby/2.5.0/fileutils.rb:208:in `reverse_each'
	from /usr/lib/ruby/2.5.0/fileutils.rb:208:in `block in mkdir_p'
	from /usr/lib/ruby/2.5.0/fileutils.rb:193:in `each'
	from /usr/lib/ruby/2.5.0/fileutils.rb:193:in `mkdir_p'
	from /usr/lib/ruby/gems/2.5.0/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/module.rb:28:in `fastlane_user_dir'
	from /usr/lib/ruby/gems/2.5.0/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/analytics/analytics_session.rb:58:in `did_show_message?'
	from /usr/lib/ruby/gems/2.5.0/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/analytics/analytics_session.rb:22:in `action_launched'
	from /usr/lib/ruby/gems/2.5.0/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
	from /usr/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /usr/lib/ruby/gems/2.5.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	from /usr/lib/ruby/gems/2.5.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /usr/lib/ruby/gems/2.5.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /usr/lib/ruby/gems/2.5.0/gems/fastlane-2.141.0/bin/fastlane:23:in `<top (required)>'
	from /usr/bin/fastlane:26:in `load'
	from /usr/bin/fastlane:26:in `<main>'

OUTPUT OF fastlane env
-----------------------------------------------------------------------------

bash-4.4# fastlane env
[✔] 🚀 
[09:40:08]: fastlane detected a Gemfile in the current directory
[09:40:08]: However, it seems like you didn't use `bundle exec`
[09:40:08]: To launch fastlane faster, please use
[09:40:08]: 
[09:40:08]: $ bundle exec fastlane env
[09:40:08]: 
[09:40:08]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[09:40:09]: Generating fastlane environment output, this might take a few seconds...
cat: can't open '/etc/issue.net': No such file or directory
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                                                                             |
| --------------------------- | ----------------------------------------------------------------------------------------------------------------- |
| OS                          | Linux 6abff6f11ace 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 Linux                     |
| Ruby                        | 2.5.7                                                                                                             |
| Bundler?                    | false                                                                                                             |
| Git                         | git version 2.18.2                                                                                                |
| Installation Source         | /usr/bin/fastlane                                                                                                 |
| Host                        | Linux 6abff6f11ace 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 Linux (4.15.0-74-generic) |
| Ruby Lib Dir                | /usr/lib                                                                                                          |
| OpenSSL Version             | LibreSSL 2.7.5                                                                                                    |
| Is contained                | false                                                                                                             |
| Is homebrew                 | false                                                                                                             |
| Is installed via Fabric.app | false                                                                                                             |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("codepath.demos.helloworlddemo") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.141.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.72.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.7        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.10.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.0        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| stringio                  | 0.0.1        |
| openssl                   | 2.1.2        |
| strscan                   | 1.0.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| etc                       | 1.0.0        |
| io-console                | 0.4.6        |
| zlib                      | 1.0.0        |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
</details>

*generated on:* **2020-02-11**
</details>
[09:40:13]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[09:40:13]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅

**Comment by prejithp-repo** [comment]
[04:45:19]: fastlane detected a Gemfile in the current directory
[04:45:19]: However, it seems like you didn't use `bundle exec`
[04:45:19]: To launch fastlane faster, please use
[04:45:19]: 
[04:45:19]: $ bundle exec fastlane env
[04:45:19]: 
[04:45:19]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[04:45:20]: Sending anonymous analytics information
[04:45:20]: Learn more at https://docs.fastlane.tools/#metrics
[04:45:20]: No personal or sensitive data is sent.
[04:45:20]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
[04:45:20]: Generating fastlane environment output, this might take a few seconds...
cat: can't open '/etc/issue.net': No such file or directory
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                                                                             |
| --------------------------- | ----------------------------------------------------------------------------------------------------------------- |
| OS                          | Linux 4cd2af32cd62 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 Linux                     |
| Ruby                        | 2.5.7                                                                                                             |
| Bundler?                    | false                                                                                                             |
| Git                         | git version 2.18.2                                                                                                |
| Installation Source         | /usr/bin/fastlane                                                                                                 |
| Host                        | Linux 4cd2af32cd62 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 Linux (4.15.0-74-generic) |
| Ruby Lib Dir                | /usr/lib                                                                                                          |
| OpenSSL Version             | LibreSSL 2.7.5                                                                                                    |
| Is contained                | false                                                                                                             |
| Is homebrew                 | false                                                                                                             |
| Is installed via Fabric.app | false                                                                                                             |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.140.0 | 🚫 Update available |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.72.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.10.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.0        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| stringio                  | 0.0.1        |
| openssl                   | 2.1.2        |
| strscan                   | 1.0.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| etc                       | 1.0.0        |
| io-console                | 0.4.6        |
| zlib                      | 1.0.0        |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
</details>


*generated on:* **2020-02-10**
</details>
[04:45:21]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[04:45:21]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅

#######################################################################
# fastlane 2.141.0 is available. You are on 2.140.0.
# You should use the latest version.
# Please update using `sudo gem install fastlane`.
#######################################################################

2.141.0 macOS and Catalyst support for gym, match, cert, and sigh
* [match] add mac and catalyst support for match (#15918) via Josh Holtz
* [gym, deliver, actions] allow gym to create .pkg for macOS apps and Catalyst apps for App Store upload and new `build_mac_app` action (#12195) via Josh Holtz
* [spaceship] delete beta feedback (#15940) via Tim Sneed
* [match] Change http_auth_header capitalization (#15928) via sakul1991
* [gym, scan] resolve SwiftPM dependencies before fetching build settings (#15505) via Bruno Guidolim
* [fastlane] import multiple files from git (#15804) via Pavlo Pakholka
* [spaceship] replenish IAP status (#15872) via Rdd7
* [action] introduce milestone support for create_pull_request action (#15873) via Kohki Miki
* [action] rix return type of set_github_release action, since it might contain non-string value (#15883) via knothole
* [snapshot] add support for disabling "KeyboardContinuousPathEnabled" (#15933) via Andreas Ganske

---

- _match_
  - options
    - `platform` now supports `macos`
    - `type` now supports `developer_id`
    - `additional_cert_types` (new option) for which supports `mac_installer_distribution` and `developer_id_installer`
- _gym_
  - behavior
    - `gym`, `build_app`, and `build_mac_app` will now attempt to sign and package an macOS app with `productbuild` command to create a `.pkg` for App Store distribution
  - options
    - `skip_package_pkg` (new option) will prevent making `.pkg` for macOS apps
    - `catalyst_platform` (new option) is needed when building Catalyst apps (valid values are `ios` and `macos`)
   - `installer_cert_name` (new option) for signing and packaging macOS apps (`gym` will try to find 
automatically fill this option for you so you don't have to)
  - lane contexts
    - `PKG_OUTPUT_PATH` the path of the newly generated `.pkg` file
  - actions
    - `build_app` is an exact alias of `gym`
    - `build_mac_app` is a new alias that only supports macOS options for `gym`
    - `build_ios_app` now only supports iOS options for `gym`

**Comment by prejithp-repo** [comment]
bash-4.4# fastlane env
[✔] 🚀 
[08:26:19]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[08:26:20]: Sending anonymous analytics information
[08:26:20]: Learn more at https://docs.fastlane.tools/#metrics
[08:26:20]: No personal or sensitive data is sent.
[08:26:20]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
[08:26:20]: Generating fastlane environment output, this might take a few seconds...
cat: can't open '/etc/issue.net': No such file or directory
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                                                                             |
| --------------------------- | ----------------------------------------------------------------------------------------------------------------- |
| OS                          | Linux 6abff6f11ace 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 Linux                     |
| Ruby                        | 2.5.7                                                                                                             |
| Bundler?                    | false                                                                                                             |
| Git                         | git version 2.18.2                                                                                                |
| Installation Source         | /usr/bin/fastlane                                                                                                 |
| Host                        | Linux 6abff6f11ace 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 Linux (4.15.0-74-generic) |
| Ruby Lib Dir                | /usr/lib                                                                                                          |
| OpenSSL Version             | LibreSSL 2.7.5                                                                                                    |
| Is contained                | false                                                                                                             |
| Is homebrew                 | false                                                                                                             |
| Is installed via Fabric.app | false                                                                                                             |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.141.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.72.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.7        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.10.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.0        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| stringio                  | 0.0.1        |
| openssl                   | 2.1.2        |
| strscan                   | 1.0.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| etc                       | 1.0.0        |
| io-console                | 0.4.6        |
| zlib                      | 1.0.0        |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
</details>


*generated on:* **2020-02-11**
</details>
[08:26:23]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[08:26:23]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅

**Comment by prejithp-repo** [comment]
bash-4.4# fastlane env
[✔] 🚀 
[08:28:42]: fastlane detected a Gemfile in the current directory
[08:28:42]: However, it seems like you didn't use `bundle exec`
[08:28:42]: To launch fastlane faster, please use
[08:28:42]: 
[08:28:42]: $ bundle exec fastlane env
[08:28:42]: 
[08:28:42]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[08:28:42]: Generating fastlane environment output, this might take a few seconds...
cat: can't open '/etc/issue.net': No such file or directory
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                                                                             |
| --------------------------- | ----------------------------------------------------------------------------------------------------------------- |
| OS                          | Linux 6abff6f11ace 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 Linux                     |
| Ruby                        | 2.5.7                                                                                                             |
| Bundler?                    | false                                                                                                             |
| Git                         | git version 2.18.2                                                                                                |
| Installation Source         | /usr/bin/fastlane                                                                                                 |
| Host                        | Linux 6abff6f11ace 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 Linux (4.15.0-74-generic) |
| Ruby Lib Dir                | /usr/lib                                                                                                          |
| OpenSSL Version             | LibreSSL 2.7.5                                                                                                    |
| Is contained                | false                                                                                                             |
| Is homebrew                 | false                                                                                                             |
| Is installed via Fabric.app | false                                                                                                             |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("codepath.demos.helloworlddemo") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.141.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.72.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.7        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.10.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.0        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| stringio                  | 0.0.1        |
| openssl                   | 2.1.2        |
| strscan                   | 1.0.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| etc                       | 1.0.0        |
| io-console                | 0.4.6        |
| zlib                      | 1.0.0        |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
</details>


*generated on:* **2020-02-11**
</details>
[08:28:45]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[08:28:45]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅

**Comment by prejithp-repo** [comment]
Its not working!!!. i updated the fastlane to the latest version. Still i am facing the same issue

**Comment by lacostej** [comment]
Your HOME directory is set to `/var/empty`. Check the configuration of your jenkins agent.
