### ISSUE TITLE
Support for App-Specific Password Use on Spaceship?

### ISSUE THREAD

**Issue by nancy-gomez** [fastlane/fastlane#15985]
#### Motivation Behind Feature
Hello, we have an old account we've been using that still has 2FA off. We use this account to build, download profiles, upload to testflight/ appstore, and interact with the portal (add devices, refresh profiles, update profile device/cert list, generate a list of upcoming expiring certificates across all teams). So lots of important stuff. We wanted to make a new user in order to safely test changes in the permissions / settings etc and in the process we have learned that 2FA on new accounts can not be disabled. So we plan to eventually migrate to use this new account but we have realized a large portion of the stuff we do will no longer work because the app-specific password is only valid for specific use-cases. Is it possible to add support to Spaceship which can utilize the app specific password in order to perform all these actions?

#### Feature Description
We would like Spaceship to utilize app-specific password to sign in. We want to avoid storing the actual password in the keychain. We'd also like to avoid utilizing the session token. We want to be able to provide username + app-specific password to interact with the developer portal. I saw that the documentation here: https://docs.fastlane.tools/best-practices/continuous-integration/ mentioned
"All other actions interacting with Apple's APIs do not accept application specific passwords." I'm wondering if this is a limitation on the support within fastlane or a limitation on the type of authentication these API endpoints allow?

#### Alternatives or Workarounds
We are still using our super old account, but the fear is now that Apple could alter this account, which would then break all our builds as everyone is utilizing and we'd have no way to prepare for that.

**Comment by janpio** [comment]
> I'm wondering if this is a limitation on the support within fastlane or a limitation on the type of authentication these API endpoints allow?

This is a limitation of the API endpoints that Apple offers (or that fastlane uses).

**Comment by nancy-gomez** [comment]
I knew it :( do you have any suggestions for best practices documented regarding using the `FASTLANE_SESSION` / `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` environment variable? 

I also wanted to figure out how to suggest an edit on the fastlane docs, in order to actually use the `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` for an action such as `upload_to_testflight`, I needed to also pass `apple_id` and the `skip_waiting_for_build_processing` but this wasn't specified in the docs :( How might I be able to add this info for other users?

**Comment by janpio** [comment]
Docs have an "Edit on Github" button on the top right, just edit the file and send a PR.

I am pretty sure the `apple_id` + `skip_waiting_for_build_processing` thing is/was documented somewhere (I wrote the code for it to work), but I honestly can not find it right now :/

**Comment by nancy-gomez** [comment]
I'll see if I can put in the time to add this info on all aliases and continue the best practices where you left off :) We're lucky enough to have an old account that has no 2FA, but looks like reaching out to apple support has proved they don't plan to allow new accounts to opt out anymore.

Thank you so much for the information. ❤️
