### ISSUE TITLE
Set only one target by provisioningProfiles options - doesn't work

### ISSUE THREAD

**Issue by zakabluk** [fastlane/fastlane#15982]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
I have to targets into progect.  I want do build only for one target -  "com.ar.blu" => "BLU (Distribution)". I set in Fastfile

```
    gym(
      scheme: ENV["SCHEME"],
      clean: true,
      output_directory: "build",
      export_options: {
        method: 'app-store',
        skip_profile_detection: true,
        signingStyle: "manual",
        provisioningProfiles: {
        "com.ar.blu" => "BLU (Distribution)"
        }

      }
    )
```
But during build I see that 

```
[17:13:15]: $ xcodebuild -showBuildSettings -workspace ./BLU.xcworkspace -scheme BLUairspace
 [17:13:18]: Detected provisioning profile mapping: {:"com.ar.blu"=>"BLU (Distribution)", :"com.ar.rethin"=>"Minolta (Distribution)"}
 +-----------------------------------------------------------+-------------------------------------------------------+
 |                                              Summary for gym 2.141.0                                              |
 +-----------------------------------------------------------+-------------------------------------------------------+
 | scheme                                                    | BLUairspace                                           |
 | clean                                                     | true                                                  |
 | output_directory                                          | build                                                 |
 | export_options.method                                     | app-store                                             |
 | export_options.provisioningProfiles.com.ar.blu     | BLU (Distribution)                             |
 | export_options.provisioningProfiles.com.ar.rethin | Minolta (Distribution)                         |
 | workspace                                                 | ./BLU.xcworkspace                             |
```
and 

```
[17:14:52]: Generated plist file with the following values:
 [17:14:52]: ▸ -----------------------------------------
 [17:14:52]: ▸ {
 [17:14:52]: ▸   "method": "app-store",
 [17:14:52]: ▸   "provisioningProfiles": {
 [17:14:52]: ▸     "com.ar.realityblu": "BLU (Distribution)",
 [17:14:52]: ▸     "com.ar.rethinkreality": "Minolta (Distribution)"
 [17:14:52]: ▸   },
 [17:14:52]: ▸   "signingStyle": "manual"
 [17:14:52]: ▸ }
 [17:14:52]: ▸ -----------------------------------------
```

Why this happens if I set directly provisoning profile?

**Comment by jmtorralvo** [comment]
@zakabluk Could it hapenned because fastlane is getting the default values stored in xCode?

**Comment by jmtorralvo** [comment]
I'm having a similar problem. This is the fastlane command i'm using:


generateIPA(
    bundleId: 'com.hivehome.hive.internal.56.testing',
    type: 'enterprise',
    teamId: 'XXXXXXXXX',
    matchType: 'match iosdev ',
    provisioningProfiles: {
      'com.hivehome.hive.internal.57' => 'match InHouse com.hivehome.hive.internal.57',
      'com.hivehome.hive.internal.56.testing' => 'match iosdev com.hivehome.hive.internal.56.testing',
      'com.hivehome.hive.internal.59' => 'match InHouse com.hivehome.hive.internal.59'
    },
    schemeType: 'globalEngAppBeta'
  )

Basically do this:

def generateIPA(
  bundleId: nil,
  type: nil,
  teamId: nil,
  matchType: nil,
  provisioningProfiles: nil,
  schemeType: nil
  )
  ipa = gym(
    scheme: schemeType,
    export_method: type,
    clean: true,
    workspace: 'globalEngApp.xcworkspace',
    output_name: 'globalEngApp.ipa',
    include_bitcode: false,
    export_options: {
      compileBitcode: false,
      uploadBitcode: false,
      provisioningProfiles: provisioningProfiles
    },
    xcargs: "PROVISIONING_PROFILE_SPECIFIER='#{matchType + bundleId}' DEVELOPMENT_TEAM='#{teamId}' -UseNewBuildSystem='NO'",
  )
end


But i see this on Travis:

-----------------+
| scheme                                                                    | globalEngAppBeta                                                                                                                          |
| export_method                                                             | enterprise                                                                                                                                |
| clean                                                                     | true                                                                                                                                      |
| workspace                                                                 | globalEngApp.xcworkspace                                                                                                                  |
| output_name                                                               | globalEngApp                                                                                                                              |
| include_bitcode                                                           | false                                                                                                                                     |
| export_options.compileBitcode                                             | false                                                                                                                                     |
| export_options.uploadBitcode                                              | false                                                                                                                                     |
| export_options.provisioningProfiles.com.hivehome.hive.internal.57         | match InHouse com.hivehome.hive.internal.57                                                                                               |
| export_options.provisioningProfiles.com.hivehome.hive.internal.56.testing | match InHouse com.hivehome.hive.internal.56.testing                                                                                       |
| export_options.provisioningProfiles.com.hivehome.hive.internal.59         | match InHouse com.hivehome.hive.internal.59                                                                                               |
### | export_options.provisioningProfiles.com.hivehome.hive.engineerapp.dev     | match AppStore com.hivehome.hive.engineerapp.dev                                                                                          |
| xcargs                                                                    | PROVISIONING_PROFILE_SPECIFIER='match iosdev com.hivehome.hive.internal.56.testing' DEVELOPMENT_TEAM='FN97ZKPGAG' -UseNewBuildSystem='NO' |
| destination                                                               | generic/platform=iOS                                                                                                                      |
| build_path                                                                | /Users/travis/Library/Developer/Xcode/Archives/2020-02-10                                                                                 |
| output_directory                                                          | .                                                                                                                                         |
| silent                                                                    | false                                                                                                                                     |
| skip_package_ipa                                                          | false                                                                                                                                     |
| result_bundle                                                             | false                                                                                                                                     |
| buildlog_path                                                             | ~/Library/Logs/gym                                                                                                                        |
| skip_profile_detection                                                    | false                                                                                                                                     |
| xcode_path                                                                | /Applications/Xcode-10.1.app                         



I don't know why 'com.hivehome.hive.engineerapp.dev ' appear there. It's a provision profile even for a different Team ID.
