### ISSUE TITLE
What is the best way to install fastlane

### ISSUE THREAD

**Issue by Ricardo1980** [fastlane/fastlane#15984]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Hi,

I don't have a clear idea about this. What is the best way to install fastlane?
Very often I have problems with versions and plugins...
I'm using Catalina.
Should I use RubyGems or Homebrew?

Some people say I shouldn't use ruby included in the operating system, and they recommend rvm (for having different versions of ruby) and bundler (to manage gems).
Is that the best way?
When using rvm, should I use "sudo gem install fastlane -NV" or "gem install fastlane -NV"?

Thanks a lot.

**Comment by Cyberbeni** [comment]
Use bundler and keep your ruby version up to date.

**Comment by Ricardo1980** [comment]
@Cyberbeni Thanks.
But, if I do that, does that mean I will use ruby included with Catalina?
I have read that is not a good idea.
