### ISSUE TITLE
Time-sensitive `Gym::DetectValues` tests make the CI fail

### ISSUE THREAD

**Issue by Jeehut** [fastlane/fastlane#15987]
The tests on my PR #15986 just failed because there are some tests which fail when started at the end of the day but end at the beginning of the next day, due to a check of the day in the tests. See these two tests run on Circle CI which failed although there were clearly no changes related to it in my PR:
https://app.circleci.com/jobs/github/fastlane/fastlane/40527
https://app.circleci.com/jobs/github/fastlane/fastlane/40530

Here's an excerpt (just in case the links don't work later in the future):
```
Gym Gym::DetectValues Xcode config handling fetches the custom build path from the Xcode config
     Failure/Error: expect(path).to eq("/test/path/#{day}")

       expected: "/test/path/2020-02-06"
            got: "/test/path/2020-02-07"

       (compared using ==)
     # ./gym/spec/detect_values_spec.rb:14:in `block (4 levels) in <top (required)>'


```

**Comment by Jeehut** [comment]
@fastlane-bot No need for `fastlane env` info for this issue.

**Comment by macblazer** [comment]
I will take a stab at fixing this.
