### ISSUE TITLE
fist upload to testflight the beta_app_feedback_email not filled

### ISSUE THREAD

**Issue by csc-EricWu** [fastlane/fastlane#15980]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.2                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.23.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.2 (19C57)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.3.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

upload_to_testflight(
ipa: "#{ipaPath}",
app_identifier: "#{app_identifier}",
beta_app_feedback_email: "7588585@qq.com",
# email: "7588585@qq.com",
username: "7588585@qq.com",
changelog: "功能完整性测试",
# changelog: "MyApp version #{short_version} build #{build} update",
distribute_external: true,
groups: ["All"],
demo_account_required: true,
beta_app_review_info: {
  contact_email: "7588585@qq.com",
  contact_first_name: "#{contact_first_name}",
  contact_last_name: "#{contact_last_name}",
  contact_phone: "#{contact_phone}",
  demo_account_name: "#{contact_phone}",
  demo_account_password: "123456",
  notes: "",
},
localized_app_info: {
  "default": {
    feedback_email: "7588585@qq.com",
    marketing_url: "",
    privacy_policy_url: "",
    description: "",
  },
# "en-GB": {
#   feedback_email: "7588585@qq.com",
#   marketing_url: "",
#   privacy_policy_url: "",
#   description: "",
# }
# },
# localized_build_info: {
#   "default": {
#     whats_new: "update",
#   },
# "en-GB": {
#   whats_new: "update",
# }
},

```
</details>

<details><summary>`./Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.141.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                   | Version | Update-Status |
| ---------------------------------------- | ------- | ------------- |
| fastlane-plugin-clean_testflight_testers | 0.3.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                      | Version      |
| ---------------------------------------- | ------------ |
| did_you_mean                             | 1.3.0        |
| slack-notifier                           | 2.3.2        |
| rouge                                    | 2.0.7        |
| xcpretty                                 | 0.3.0        |
| terminal-notifier                        | 2.0.0        |
| terminal-table                           | 1.8.0        |
| plist                                    | 3.5.0        |
| public_suffix                            | 2.0.5        |
| addressable                              | 2.7.0        |
| multipart-post                           | 2.0.0        |
| word_wrap                                | 1.0.0        |
| tty-screen                               | 0.7.0        |
| babosa                                   | 1.0.3        |
| colored                                  | 1.2          |
| highline                                 | 1.7.10       |
| commander-fastlane                       | 4.4.6        |
| faraday                                  | 0.17.3       |
| unf_ext                                  | 0.0.7.6      |
| unf                                      | 0.1.4        |
| domain_name                              | 0.5.20190701 |
| http-cookie                              | 1.0.3        |
| faraday-cookie_jar                       | 0.0.6        |
| faraday_middleware                       | 0.13.1       |
| fastimage                                | 2.1.7        |
| gh_inspector                             | 1.1.3        |
| multi_xml                                | 0.6.0        |
| rubyzip                                  | 1.3.0        |
| security                                 | 0.1.3        |
| xcpretty-travis-formatter                | 1.0.0        |
| dotenv                                   | 2.7.5        |
| bundler                                  | 1.17.2       |
| naturally                                | 2.2.0        |
| simctl                                   | 1.6.7        |
| jwt                                      | 2.1.0        |
| memoist                                  | 0.16.2       |
| multi_json                               | 1.14.1       |
| os                                       | 1.0.1        |
| signet                                   | 0.12.0       |
| googleauth                               | 0.10.0       |
| digest-crc                               | 0.4.1        |
| mini_mime                                | 1.0.2        |
| google-cloud-storage                     | 1.25.1       |
| emoji_regex                              | 1.0.1        |
| nanaimo                                  | 0.2.6        |
| colored2                                 | 3.1.2        |
| claide                                   | 1.0.3        |
| CFPropertyList                           | 3.0.2        |
| atomos                                   | 0.1.3        |
| xcodeproj                                | 1.14.0       |
| unicode-display_width                    | 1.6.1        |
| tty-cursor                               | 0.7.1        |
| tty-spinner                              | 0.9.3        |
| excon                                    | 0.72.0       |
| json                                     | 2.3.0        |
| mini_magick                              | 4.10.1       |
| httpclient                               | 2.8.3        |
| retriable                                | 3.1.2        |
| declarative-option                       | 0.1.0        |
| declarative                              | 0.0.10       |
| uber                                     | 0.1.0        |
| representable                            | 3.0.4        |
| google-api-client                        | 0.36.4       |
| google-cloud-errors                      | 1.0.0        |
| google-cloud-env                         | 1.3.0        |
| google-cloud-core                        | 1.5.0        |
| forwardable                              | 1.2.0        |
| logger                                   | 1.3.0        |
| stringio                                 | 0.0.2        |
| ipaddr                                   | 1.2.2        |
| openssl                                  | 2.1.2        |
| ostruct                                  | 0.1.0        |
| strscan                                  | 1.0.0        |
| date                                     | 2.0.0        |
| fileutils                                | 1.1.0        |
| etc                                      | 1.0.1        |
| io-console                               | 0.4.7        |
| zlib                                     | 1.0.0        |
| libxml-ruby                              | 3.1.0        |
| rexml                                    | 3.1.9        |
| psych                                    | 3.1.0        |
| mutex_m                                  | 0.1.0        |
| fastlane-plugin-clean_testflight_testers | 0.3.0        |
</details>

*generated on:* **2020-02-06**
</details>

![image](https://user-images.githubusercontent.com/13517061/73905880-cb0ebd80-48db-11ea-8dff-4ca40982188c.png)

**Comment by csc-EricWu** [comment]
Did anyone meet? It's a complete mistake

**Comment by csc-EricWu** [comment]
No solution

**Comment by daniel-toth-leeder** [comment]
Experiencing the same problem, `beta_app_feedback_email` is not being filled in Appstoreconnect.
