### ISSUE TITLE
Match Fails to Import Certificates

### ISSUE THREAD

**Issue by ratbum** [fastlane/fastlane#15998]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I've been going round in circles trying to get my signing certificates to decrypt successfully, but invariably I get a message telling me that the password is wrong, so to get round this, I've tried creating an entirely new certificate repo. This is where this issue starts.

So, I've exported the known-good certificates from my keychain, and then run `fastlane match import`. This happily accepts all the input - until it gets to the password, where it fails, telling me `wrong final block length \n Couldn't decrypt the repo, please make sure you enter the right password!`. I'm confused as to why it's says `decrypt` here since I was trying to add the certs - and therefore _presumably_ to encrypt them.

##### Command executed
`fastlane match import`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>ios-certificates2 tl-test % fastlane match import --verbose
[✔] 🚀
[11:20:21]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
 [2020-02-10 11:20:22.65]: Certificate (.cer) path:
/Users/tom/Developer/ios-certificates2/Certificates.cer
 [2020-02-10 11:20:27.88]: Private key (.p12) path:
/Users/tom/Developer/ios-certificates2/Certificates.p12
WARN [2020-02-10 11:20:30.57]: To not be asked about this value, you can specify it using 'git_url'
 [2020-02-10 11:20:30.57]: URL to the git repo containing all the certificates: git@github.com:company-uk/ios-certificates2.git
WARN [2020-02-10 11:20:35.37]: To not be asked about this value, you can specify it using 'username'
 [2020-02-10 11:20:35.37]: Your Apple ID Username: tom@company.com
INFO [2020-02-10 11:20:38.51]: Cloning remote git repo...
INFO [2020-02-10 11:20:38.51]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
INFO [2020-02-10 11:20:38.51]: $ git clone git@github.com:company-uk/ios-certificates2.git /var/folders/9d/fvn5549161d6nbd0_q0cj5m00000gn/T/d20200210-10240-dps1rg
INFO [2020-02-10 11:20:38.52]: ▸ Cloning into '/var/folders/9d/fvn5549161d6nbd0_q0cj5m00000gn/T/d20200210-10240-dps1rg'...
INFO [2020-02-10 11:20:39.90]: ▸ remote: Enumerating objects: 27, done.
INFO [2020-02-10 11:20:39.90]: ▸ remote: Counting objects: 100% (27/27), done.
INFO [2020-02-10 11:20:39.98]: ▸ remote: Compressing objects: 100% (20/20), done.
INFO [2020-02-10 11:20:39.99]: ▸ remote: Total 27 (delta 4), reused 27 (delta 4), pack-reused 0
INFO [2020-02-10 11:20:39.99]: ▸ Receiving objects: 100% (27/27), 25.68 KiB | 25.68 MiB/s, done.
INFO [2020-02-10 11:20:39.99]: ▸ Resolving deltas: 100% (4/4), done.
WARN [2020-02-10 11:20:40.04]: Enter the passphrase that should be used to encrypt/decrypt your certificates
WARN [2020-02-10 11:20:40.04]: This passphrase is specific per repository and will be stored in your local keychain
WARN [2020-02-10 11:20:40.04]: Make sure to remember the password, as you'll need it when you run match on a different machine
 [2020-02-10 11:20:40.04]: Passphrase for Git Repo: *********************************************************
 [2020-02-10 11:20:42.44]: Type passphrase again: **********************************************************
ERROR [2020-02-10 11:20:42.95]: wrong final block length
DEBUG [2020-02-10 11:20:42.95]: Error decrypting '/var/folders/9d/fvn5549161d6nbd0_q0cj5m00000gn/T/d20200210-10240-dps1rg/certs/development/RJA3P323L75.cer'
ERROR [2020-02-10 11:20:42.95]: Couldn't decrypt the repo, please make sure you enter the right password!
keychain: "/Users/tom/Library/Keychains/login.keychain-db"
version: 512
class: "inet"
attributes:
    0x00000007 <blob>="match_git@github.com:company-uk/ios-certificates2.git"
    0x00000008 <blob>=<NULL>
    "acct"<blob>=<NULL>
    "atyp"<blob>="dflt"
    "cdat"<timedate>=0x32303230303231303131323034325A00  "20200210112042Z\000"
    "crtr"<uint32>=<NULL>
    "cusi"<sint32>=<NULL>
    "desc"<blob>=<NULL>
    "icmt"<blob>=<NULL>
    "invi"<sint32>=<NULL>
    "mdat"<timedate>=0x32303230303231303131323034325A00  "20200210112042Z\000"
    "nega"<sint32>=<NULL>
    "path"<blob>=<NULL>
    "port"<uint32>=0x00000000
    "prot"<blob>=<NULL>
    "ptcl"<uint32>=0x00000000
    "scrp"<sint32>=<NULL>
    "sdmn"<blob>=<NULL>
    "srvr"<blob>="match_git@github.com:company-uk/ios-certificates2.git"
    "type"<uint32>=<NULL>
password has been deleted.
WARN [2020-02-10 11:20:43.02]: Enter the passphrase that should be used to encrypt/decrypt your certificates
WARN [2020-02-10 11:20:43.02]: This passphrase is specific per repository and will be stored in your local keychain
WARN [2020-02-10 11:20:43.02]: Make sure to remember the password, as you'll need it when you run match on a different machine
Traceback (most recent call last):ase for Git Repo:
	19: from /Users/tom/.asdf/installs/ruby/2.6.5/bin/fastlane:23:in `<main>'
	18: from /Users/tom/.asdf/installs/ruby/2.6.5/bin/fastlane:23:in `load'
	17: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/bin/fastlane:23:in `<top (required)>'
	16: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	15: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/commands_generator.rb:25:in `start'
	14: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/commands_generator.rb:186:in `run'
	13: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	12: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	11: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	10: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 9: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 8: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/commands_generator.rb:145:in `block (2 levels) in run'
	 7: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/importer.rb:49:in `import_cert'
	 6: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:44:in `decrypt_files'
	 5: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:74:in `iterate'
	 4: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:74:in `each'
	 3: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:76:in `block in iterate'
	 2: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:47:in `block in decrypt_files'
	 1: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:147:in `decrypt_specific_file'
/Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:147:in `final': wrong final block length (OpenSSL::Cipher::CipherError)
	21: from /Users/tom/.asdf/installs/ruby/2.6.5/bin/fastlane:23:in `<main>'
	20: from /Users/tom/.asdf/installs/ruby/2.6.5/bin/fastlane:23:in `load'
	19: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/bin/fastlane:23:in `<top (required)>'
	18: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	17: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/commands_generator.rb:25:in `start'
	16: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/commands_generator.rb:186:in `run'
	15: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	14: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	13: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	12: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	11: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	10: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/commands_generator.rb:145:in `block (2 levels) in run'
	 9: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/importer.rb:49:in `import_cert'
	 8: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:44:in `decrypt_files'
	 7: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:74:in `iterate'
	 6: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:74:in `each'
	 5: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:76:in `block in iterate'
	 4: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:47:in `block in decrypt_files'
	 3: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:138:in `decrypt_specific_file'
	 2: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:153:in `rescue in decrypt_specific_file'
	 1: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:147:in `decrypt_specific_file'
/Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:147:in `final': wrong final block length (OpenSSL::Cipher::CipherError)
	23: from /Users/tom/.asdf/installs/ruby/2.6.5/bin/fastlane:23:in `<main>'
	22: from /Users/tom/.asdf/installs/ruby/2.6.5/bin/fastlane:23:in `load'
	21: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/bin/fastlane:23:in `<top (required)>'
	20: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	19: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/commands_generator.rb:25:in `start'
	18: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/commands_generator.rb:186:in `run'
	17: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	16: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	15: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	14: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	13: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	12: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/commands_generator.rb:145:in `block (2 levels) in run'
	11: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/importer.rb:49:in `import_cert'
	10: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:44:in `decrypt_files'
	 9: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:74:in `iterate'
	 8: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:74:in `each'
	 7: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:76:in `block in iterate'
	 6: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:47:in `block in decrypt_files'
	 5: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:138:in `decrypt_specific_file'
	 4: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:153:in `rescue in decrypt_specific_file'
	 3: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:138:in `decrypt_specific_file'
	 2: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:156:in `rescue in decrypt_specific_file'
	 1: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': Error decrypting '/var/folders/9d/fvn5549161d6nbd0_q0cj5m00000gn/T/d20200210-10240-dps1rg/certs/development/RJA3P323L75.cer' (FastlaneCore::Interface::FastlaneCrash)
	34: from /Users/tom/.asdf/installs/ruby/2.6.5/bin/fastlane:23:in `<main>'
	33: from /Users/tom/.asdf/installs/ruby/2.6.5/bin/fastlane:23:in `load'
	32: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/bin/fastlane:23:in `<top (required)>'
	31: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	30: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/commands_generator.rb:25:in `start'
	29: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/commands_generator.rb:186:in `run'
	28: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	27: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	26: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	25: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	24: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	23: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/commands_generator.rb:145:in `block (2 levels) in run'
	22: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/importer.rb:49:in `import_cert'
	21: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:44:in `decrypt_files'
	20: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:74:in `iterate'
	19: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:74:in `each'
	18: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:76:in `block in iterate'
	17: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:46:in `block in decrypt_files'
	16: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:53:in `rescue in block in decrypt_files'
	15: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:44:in `decrypt_files'
	14: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:74:in `iterate'
	13: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:74:in `each'
	12: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:76:in `block in iterate'
	11: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:47:in `block in decrypt_files'
	10: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/encryption/openssl.rb:102:in `password'
	 9: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/change_password.rb:50:in `ask_password'
	 8: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/change_password.rb:50:in `loop'
	 7: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/match/lib/match/change_password.rb:51:in `block in ask_password'
	 6: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	 5: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:148:in `password'
	 4: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/2.6.0/forwardable.rb:230:in `ask'
	 3: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/highline-1.7.10/lib/highline.rb:264:in `ask'
	 2: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/highline-1.7.10/lib/highline.rb:899:in `get_response'
	 1: from /Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/highline-1.7.10/lib/highline/system_extensions.rb:250:in `get_character'
/Users/tom/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/highline-1.7.10/lib/highline/system_extensions.rb:250:in `getbyte': Interrupt
</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.3                                     |
| Ruby                        | 2.6.5                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.24.1                          |
| Installation Source         | ~/.asdf/installs/ruby/2.6.5/bin/fastlane    |
| Host                        | Mac OS X 10.15.3 (19D76)                    |
| Ruby Lib Dir                | ~/.asdf/installs/ruby/2.6.5/lib             |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.3.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.141.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.72.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.7        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.10.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.0        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| json                      | 2.3.0        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>

*generated on:* **2020-02-10**
</details></pre>
</details>

**Comment by janpio** [comment]
Error message is from here, so _something_ is being decrypted:

https://github.com/fastlane/fastlane/blob/a1d4ea0ca3261197ecf06d8248f5199b171f0004/match/lib/match/encryption/openssl.rb#L42-L60

From the code that uses it, I think it is decrypting the Git repo as a whole:
https://github.com/fastlane/fastlane/blob/a1d4ea0ca3261197ecf06d8248f5199b171f0004/match/lib/match/importer.rb#L44-L49

Not sure what is going wrong here though :/
