### ISSUE TITLE
How to specify snapshot device OS or use the latest

### ISSUE THREAD

**Issue by tedgonzalez** [fastlane/fastlane#15996]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
 Snapshot

#### Question Description

This is my snapshot code using Xcode 11.3.1
```
snapshot(
    clean: true,
    clear_previous_screenshots: true,
    devices: [
      "iPhone X",
      "iPhone Xs Max"
    ],
    erase_simulator: true,
    dark_mode: false,
    languages: [
      "en-US",
      "nb-NO"
    ],
    number_of_retries: 0,
    scheme: "someScheme"
  )
```
The default simulator I have is 13.3 but when running snapshot, I get: 

> Using device named 'iPhone X' with version '12.4' because no match was found for version '13.2'

Is there a way to specify simulator e.g. iPhone X (13.3) ? Thanks! :)

**Comment by tedgonzalez** [comment]
Update, I installed 13.2 simulators now I get this which works for me 
> Using device named 'iPhone X' with version '13.3' because no match was found for version '13.2'

**Comment by tedgonzalez** [comment]
activity

**Comment by tedgonzalez** [comment]
activity

**Comment by tedgonzalez** [comment]
activity

**Comment by tedgonzalez** [comment]
activity

**Comment by tedgonzalez** [comment]
activity

**Comment by tedgonzalez** [comment]
activity

**Comment by rogerluan** [comment]
@tedgonzalez looks like you're interested in using the `ios_version` option explained here https://docs.fastlane.tools/actions/snapshot/

Have you tried that?
