### ISSUE TITLE
Change Fastlane get_version_number function output

### ISSUE THREAD

**Issue by alexcoward** [fastlane/fastlane#15993]
#### Motivation Behind Feature
The output of the current get_version_number function when used with an Xcode project (iOS) includes text other than the version number. If a user wishes to use this function to find ONLY the version number with no extraneous text, the user must use grep or another tool to parse the output specifically looking for the version number. The output of the get_version_number function may change in the future requiring users to adapt their use of grep to the output itself, and this can be frustrating for users. 

#### Feature Description
The output of the get_version_number function should be ONLY the version number, in the following format MAJOR.MINOR.PATCH:
1.2.3

#### Alternatives or Workarounds
Use grep, etc to parse output of get_version_number looking for only the version number and assign that to a variable to use within the build script.

**Comment by janpio** [comment]
This will most probably not happen, we strive to not change existing functionality.

But what you describe does not sound right as well. Can you please open an new issue to describe what you are getting vs. what you expect to get?

**Comment by alexcoward** [comment]
Ok I understand. Yes, give me a few days I will open a new issue describing the output I am getting from get_version_number.
