### ISSUE TITLE
Scan is not able to parse simulator version from simctl list

### ISSUE THREAD

**Issue by dratkevich** [fastlane/fastlane#15997]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Currently `scan` is relying on iOS version to be a part of simulator name in parentheses (https://github.com/fastlane/fastlane/blob/f32b007ff45e648b37b6c9c2037ac481f36b7780/scan/lib/scan/detect_values.rb) but starting from ?(unknown) version of xCode (most likely 11.3.1) version is not a part of simulator name in the list when running `xcrun simctl list`. 
In this case first (oldest) iOS version is being used by fastlane.

##### Command executed

```
scan(
        scheme:xxx,
        derived_data_path: xxx,
        devices: ['iPhone SE','iPhone X','iPhone Xs Max','iPad (5th generation)','iPad Air','iPad (6th generation)','iPad Pro (12.9-inch) (2nd generation)'],
        max_concurrent_simulators: 4)
```
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
...
IDETestOperationsObserverDebug: (2D4D5B8B-7F25-4D0C-9850-640A239A91BC) Beginning test session UITests-2D4D5B8B-7F25-4D0C-9850-640A239A91BC at 2020-02-10 09:55:44.618 with Xcode 11C504 on target <DVTiPhoneSimulator: 0x7f8a4d8262f0> {
 		SimDevice: iPhone SE (F822C8A6-4B1E-478F-97A0-9F7758573733, iOS 10.3, Shutdown) 
...
[MT] IDETestOperationsObserverDebug: (A0584156-5F62-49BC-9D46-6B25D36E03C8) Beginning test session UITests-A0584156-5F62-49BC-9D46-6B25D36E03C8 at 2020-02-10 09:55:44.636 with Xcode 11C504 on target <DVTiPhoneSimulator: 0x7f8a4d866ea0> {
 		SimDevice: iPhone X (B1DD6DD9-C5E8-4B18-99D6-E70C8077592D, iOS 13.3, Shutdown)
</pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.3                                     |
| Ruby                        | 2.6.5                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.1 (Apple Git-122.3)        |
| Installation Source         | ~/.rbenv/versions/2.6.5/bin/fastlane        |
| Host                        | Mac OS X 10.15.3 (19D76)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.5/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.3.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.141.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| CFPropertyList            | 3.0.1        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.72.0       |
| faraday                   | 0.17.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.1       |
| os                        | 1.0.1        |
| googleauth                | 0.9.0        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.14.0       |
| json                      | 2.2.0        |
| bundler                   | 2.0.2        |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.4.1        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>

*generated on:* **2020-02-10**
</details> </pre>
</details>

**Comment by tedgonzalez** [comment]
+1

**Comment by tedgonzalez** [comment]
activity

**Comment by tedgonzalez** [comment]
activity

**Comment by tedgonzalez** [comment]
activity

**Comment by tedgonzalez** [comment]
activity

**Comment by minuscorp** [comment]
Is this still an issue?
