### ISSUE TITLE
`load_plugins` does not respect bundler groups

### ISSUE THREAD

**Issue by manuyavuz-pointr** [fastlane/fastlane#15992]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I have a Gemfile with a few fastlane plugins that are separated with bundler groups. Gemfile has the following:

```
group :ios, optional: true do
  gem 'fastlane-plugin-firebase_test_lab'
end

group :android, optional: true do
  gem 'fastlane-plugin-run_tests_firebase_testlab'
end
```

I would expect plugin loader to try to validate only plugins from enabled groups. However, it prints failure messages for the plugin from disabled group `:android`.

##### Command executed

`bundle exec fastlane`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> (base) ➜  fastlane-load-plugins-sample git:(master) ✗ bundle exec fastlane ios custom_lane
[✔] 🚀
[21:54:01]: Missing gem 'fastlane-plugin-run_tests_firebase_testlab', please add the following to your local Gemfile:
[21:54:01]:
[21:54:01]: ▸ gem "fastlane-plugin-run_tests_firebase_testlab"
[21:54:01]:
[21:54:01]: Error loading plugin 'fastlane-plugin-run_tests_firebase_testlab': Add 'gem "fastlane-plugin-run_tests_firebase_testlab"' to your Gemfile and restart fastlane
+---------------------------+-----------+---------------------------+
|                           Used plugins                            |
+---------------------------+-----------+---------------------------+
| Plugin                    | Version   | Action                    |
+---------------------------+-----------+---------------------------+
| fastlane-plugin-firebase  | 1.0.5     | firebase_test_lab_ios_xc  |
| _test_lab                 |           | test                      |
| fastlane-plugin-run_test  | undefined | No actions found          |
| s_firebase_testlab        |           |                           |
+---------------------------+-----------+---------------------------+

[!] No actions were found while loading one or more plugins
    Please use `bundle exec fastlane` with plugins
    More info - https://docs.fastlane.tools/plugins/using-plugins/#run-with-plugins

[21:54:01]: ------------------------------
[21:54:01]: --- Step: default_platform ---
[21:54:01]: ------------------------------
[21:54:01]: Driving the lane 'ios custom_lane' 🚀

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
+------+------------------+-------------+

[21:54:01]: fastlane.tools finished successfully 🎉 </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.15.2                                          |
| Ruby                        | 2.6.5                                            |
| Bundler?                    | true                                             |
| Git                         | git version 2.20.1 (Apple Git-117)               |
| Installation Source         | /usr/local/lib/ruby/gems/2.6.0/bin/fastlane      |
| Host                        | Mac OS X 10.15.2 (19C57)                         |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.6.5/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-10.3.app/Contents/Developer/ |
| Xcode Version               | 10.3                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.141.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                     | Version   | Update-Status  |
| ------------------------------------------ | --------- | -------------- |
| fastlane-plugin-firebase_test_lab          | 1.0.5     | ✅ Up-To-Date   |
| fastlane-plugin-run_tests_firebase_testlab | undefined | 💥 Check failed |

<details><summary><b>Loaded gems</b></summary>

| Gem                               | Version      |
| --------------------------------- | ------------ |
| did_you_mean                      | 1.3.0        |
| bundler                           | 1.17.3       |
| etc                               | 1.0.1        |
| forwardable                       | 1.2.0        |
| CFPropertyList                    | 3.0.2        |
| public_suffix                     | 2.0.5        |
| addressable                       | 2.7.0        |
| atomos                            | 0.1.3        |
| babosa                            | 1.0.3        |
| claide                            | 1.0.3        |
| colored                           | 1.2          |
| colored2                          | 3.1.2        |
| highline                          | 1.7.10       |
| commander-fastlane                | 4.4.6        |
| declarative                       | 0.0.10       |
| declarative-option                | 0.1.0        |
| digest-crc                        | 0.4.1        |
| unf_ext                           | 0.0.7.6      |
| unf                               | 0.1.4        |
| domain_name                       | 0.5.20190701 |
| dotenv                            | 2.7.5        |
| emoji_regex                       | 1.0.1        |
| excon                             | 0.72.0       |
| multipart-post                    | 2.0.0        |
| faraday                           | 0.17.3       |
| http-cookie                       | 1.0.3        |
| faraday-cookie_jar                | 0.0.6        |
| faraday_middleware                | 0.13.1       |
| fastimage                         | 2.1.7        |
| gh_inspector                      | 1.1.3        |
| jwt                               | 2.1.0        |
| memoist                           | 0.16.2       |
| multi_json                        | 1.14.1       |
| os                                | 1.0.1        |
| signet                            | 0.12.0       |
| googleauth                        | 0.6.7        |
| httpclient                        | 2.8.3        |
| mini_mime                         | 1.0.2        |
| uber                              | 0.1.0        |
| representable                     | 3.0.4        |
| retriable                         | 3.1.2        |
| google-api-client                 | 0.32.1       |
| google-cloud-env                  | 1.3.0        |
| google-cloud-errors               | 1.0.0        |
| google-cloud-core                 | 1.5.0        |
| google-cloud-storage              | 1.15.0       |
| json                              | 2.3.0        |
| mini_magick                       | 4.10.1       |
| multi_xml                         | 0.6.0        |
| plist                             | 3.5.0        |
| rubyzip                           | 1.3.0        |
| security                          | 0.1.3        |
| naturally                         | 2.2.0        |
| simctl                            | 1.6.8        |
| slack-notifier                    | 2.3.2        |
| terminal-notifier                 | 2.0.0        |
| unicode-display_width             | 1.6.1        |
| terminal-table                    | 1.8.0        |
| tty-screen                        | 0.7.1        |
| tty-cursor                        | 0.7.1        |
| tty-spinner                       | 0.9.3        |
| word_wrap                         | 1.0.0        |
| nanaimo                           | 0.2.6        |
| xcodeproj                         | 1.15.0       |
| rouge                             | 2.0.7        |
| xcpretty                          | 0.3.0        |
| xcpretty-travis-formatter         | 1.0.0        |
| fastlane-plugin-firebase_test_lab | 1.0.5        |
| mime-types-data                   | 3.2019.1009  |
| mime-types                        | 3.3.1        |
</details>

*generated on:* **2020-02-07**
</details>

**Comment by janpio** [comment]
I do not know bundler groups. Can you link to some relevant documentation or explanation?
How should fastlane know that the `:android` group is disabled here?

**Comment by manuyavuz** [comment]
Hi,

Some documentation here:
https://bundler.io/v1.12/groups.html
https://bundler.io/v2.0/guides/faq.html#why-is-bundler-downloading-gems-from-without-groups

Mainly, when you use groups, bundler does dependency resolution for all gems listed in Gemfile, and lists all of them in `Gemfile.lock`, but only installs the subset belonging to groups that you selected.

When `bundle install` is run with a combination of `--with` and `--without` options, bundler save them in `.bundle/config` file, and future `bundle install` commands act accordingly.

So I can see sth like this in my config when I only enable `:android` for example:
```
without
Set for your local app (.bundle/config): [:ios]

with
Set for your local app (.bundle/config): [:android]
```

**Comment by manuyavuz** [comment]
@janpio raised a question on Bundler for this specific use case: https://github.com/rubygems/bundler/issues/7628

**Comment by janpio** [comment]
Today I learned - thanks for the links and explanation! 

Also great that you went ahead and opened an issue at bundler, I wouldn't be surprised if they came back with an existing command or method ;) Let us know here if this indeed happens, then we'll see how we can add this to fastlane. Edge case, but interesting one for sure.

**Comment by manuyavuz** [comment]
@janpio I digged in a little bit more into bundler's codebase.

Logic exists under https://github.com/rubygems/bundler/blob/master/lib/bundler/definition.rb

**Comment by janpio** [comment]
Whatever works - Bundler API is pretty stable in general I think. So go fir it if you want!
