### ISSUE TITLE
Feature Request: Managing Testers with Supply

### ISSUE THREAD

**Issue by booker-dragon** [fastlane/fastlane#16003]
### Feature Request
Managing Testers with Supply

#### Motivation Behind Feature
To fully automate distributing app to new tester, I would like to manage all testers in a file and let supply to add testers to the track

#### Feature Description
With `Edit.Testers` API, we should be able to manage testers
I would love to see a new action to accept track name, file of testers list or array of tester email to update the track testers

#### Alternatives or Workarounds
No ideas

**Comment by janpio** [comment]
That would indeed be awesome! If someone creates a Pull Request with this functionality, the team will be more than happy to review it.
