### ISSUE TITLE
How to handle plugin installation interaction on jenkins

### ISSUE THREAD

**Issue by dland512** [fastlane/fastlane#16001]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Installing plugins on jenkins machine

Not about docs

Not specific to a 3rd party plugin

#### Question Description

I am using fastlane to build an iOS app on jenkins. I am able to build the .ipa file just fine. After that I would like to upload it to Microsoft app center. I'm using the [appcenter](https://github.com/microsoft/fastlane-plugin-appcenter) plugin for that.

The problem is that when I run `fastlane add_plugin appcenter` it prompts me for confirmation before installing and when running under jenkins that results in an error.

```
Could not retrieve response as fastlane runs in non-interactive mode
```

A lot of people are having this issue but I haven't seen any good fixes. Is that any way to tell the `add_plugin` command to suppress the prompt and just install? Or is there another more creative way to handle this issue?

Here is my env data:

```
fastlane env
[23:27:42]: [33mfastlane detected a Gemfile in the current directory[0m
[23:27:42]: [33mHowever, it seems like you didn't use `bundle exec`[0m
[23:27:42]: [33mTo launch fastlane faster, please use[0m
[23:27:42]: 
[23:27:42]: [36m$ bundle exec fastlane env[0m
[23:27:42]: 
[23:27:42]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
[23:27:42]: [31mWARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables[0m
[23:27:43]: [33mGenerating fastlane environment output, this might take a few seconds...[0m
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.2                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.21.0 (Apple Git-122.2)                           |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.2 (19C57)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.3                                                           |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
    desc "Builds iOS app and uploads it to app center"

    lane :generate_profile do
        match(
            type: "adhoc",
            app_identifier: ENV["IOS_APP_ID"],
            team_id: ENV["IOS_TEAM_ID"],
            git_url: ENV["CERT_REPO"],
            readonly: false,
            generate_apple_certs: false
        )
    end

    lane :download_profile do
        match(
            type: "adhoc",
            app_identifier: ENV["IOS_APP_ID"],
            team_id: ENV["IOS_TEAM_ID"],
            git_url: ENV["CERT_REPO"],
            readonly: true,
            generate_apple_certs: false,
            keychain_password: ENV["KEYCHAIN_PASSWORD"]
        )
    end

    lane :build do
        disable_automatic_code_signing

        unlock_keychain(
            path: "login.keychain",
            password: ENV['KEYCHAIN_PASSWORD']
        )

        settings_to_override = {
            :BUNDLE_IDENTIFIER => ENV["IOS_APP_ID"],
            :PROVISIONING_PROFILE_SPECIFIER => ENV["IOS_ADHOC_PROFILE"],
            :DEVELOPMENT_TEAM => ENV["IOS_TEAM_ID"]
        }

        build_ios_app(
            scheme: "MyScheme",
            xcargs: settings_to_override,
            export_options: {
                provisioningProfiles: { 
                    ENV["IOS_APP_ID"] => ENV["IOS_ADHOC_PROFILE"]
                },
                method: "ad-hoc"
            }
        )
    end

    lane :upload do
        appcenter_upload(
            api_token: ENV["DEV_CTR_API_TOKEN"],
            owner_name: ENV["DEV_CTR_OWNER_NAME"],
            owner_type: ENV["DEV_CTR_OWNER_TYPE"],
            app_name: ENV["DEV_CTR_APP_NAME"],
            file: ENV["IOS_IPA_PATH"],
            notify_testers: false
        )
    end
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.141.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.72.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.10.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.0        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| CFPropertyList            | 3.0.2        |
| json                      | 2.3.0        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>

*generated on:* **2020-02-10**
</details>
```

**Comment by janpio** [comment]
Why do you not add the plugin to your configuration locally? `bundle exec fastlane add_plugin appcenter`, then commit your `Gemfile` etc and `bundle install` should take care of the installation on CI.

(If I am not misunderstanding the question)

**Comment by dland512** [comment]
Great, thank you, that worked. I didn't realize the Gemfile kept plugin references as well but it makes sense.
