### ISSUE TITLE
upload_to_testflight submits changelog even though changelog was not passed in

### ISSUE THREAD

**Issue by tpaik18** [fastlane/fastlane#16000]
### New Regression Checklist

- [x ] Updated fastlane to the latest version
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information
- Breaking version: [e.g. `2.141`]
- Last working version: [e.g. `2.137`]

### Regression Description
Here is my Fastfile that was working fine when running with fastlane 2.137: 
https://github.com/AudereNow/audere/blob/a0ff3561a1d15d26461cb02e81d051a115efe17b/FluStudy_us/ios/fastlane/Fastfile

As you can see from the file, it generates a `changelog` from git commits in order to put into our team's Slack announcement for the build, but it does not upload this changelog in `upload_to_testflight`. 

Then I upgraded fastlane to 2.141.0 in build 56, and suddenly our git commit changelog was showing up in TestFlight's "What to Test", which was not desired behavior. I believe this is due to https://github.com/fastlane/fastlane/pull/15617. 

Tried two workarounds: 
(1) in build 57, renamed the variable `changelog` to `changelist` as in https://github.com/AudereNow/audere/commit/100e040ffad1746206511ded26f715bed60ce968
This did not work and the git changelog was still showing up in TestFlight. 
(2) in build 58, explicitly set `changelog: ""` as in https://github.com/AudereNow/audere/commit/21ddd248fe79427dac0abf399d825fe7c06eef85 
This makes the changelog not appear in TestFlight. However, upload_to_testflight keeps waiting for build processing to finish instead of honoring `skip_waiting_for_build_processing: true`. Both of our CircleCI builds failed today due to timing out during `upload_to_testflight`. 

Expected behavior: 
Fastfile of https://github.com/AudereNow/audere/blob/a0ff3561a1d15d26461cb02e81d051a115efe17b/FluStudy_us/ios/fastlane/Fastfile does not result in changelog getting sent to TestFlight, nor does it result in a long "waiting for processing". 

##### Complete output when running fastlane, including the stack trace and command used

Here is the output from build 56 which is before I started to patch the Fastfile. It illustrates the problem of "Waiting for processing" which should not be happening. Same "Waiting for processing" happening in builds 57-60. Build 60 waited for processing for about 4 hours before failing. 

<details>
  <pre>[20:12:57]: Successfully exported and compressed dSYM file
[20:12:57]: Successfully exported and signed the ipa file:
[20:12:57]: /Users/distiller/repo/FluStudy_us/ios/output/gym/fluathome.ipa
[20:12:57]: ----------------------------------
[20:12:57]: --- Step: ******_to_testflight ---
[20:12:57]: ----------------------------------
[20:12:57]: Login to App Store Connect (*****@******now.org)
[20:13:00]: Login successful
[20:13:01]: Ready to ****** new build to TestFlight (App: ********)...
[20:13:03]: Going to ****** updated app to App Store Connect
[20:13:03]: This might take a few minutes. Please don't interrupt the script.
[20:14:18]: iTunes Transporter successfully finished its job
[20:14:18]: --------------------------------------------------------------------
[20:14:18]: Successfully ******ed package to App Store Connect. It might take a few minutes until it's visible online.
[20:14:18]: --------------------------------------------------------------------
[20:14:18]: Successfully ******ed the new binary to App Store Connect
[20:14:18]: If you want to skip waiting for the processing to be finished, use the `skip_waiting_for_build_processing` option
[20:14:18]: Note that if `skip_waiting_for_build_processing` is used but a `changelog` is supplied, this process will wait for the build to appear on AppStoreConnect, update the changelog and then skip the remaining of the processing steps.
[20:14:18]: Waiting for processing on... app_id: ********, app_version: 1.0.5, build_version: 56, platform: IOS
[20:14:19]: Read more information on why this build isn't showing up yet - https://github.com/fastlane/fastlane/issues/14997
[20:14:19]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[20:14:49]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[20:15:19]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[20:15:50]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[20:16:20]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[20:16:50]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[20:17:20]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[20:17:51]: Waiting for App Store Connect to finish processing the new build (1.0.5 - 56) for IOS
[20:17:52]: Successfully set the changelog for build
</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
opt_out_usage

default_platform :ios

platform :ios do 
  before_all do
    setup_circle_ci
  end

####### Certificates #######

  desc "Installs the certificates and profiles locally"
  lane :certificates do |options|
    if options[:use_temporary_keychain]
      create_temporary_keychain
    end
  
    readonly = (options[:refresh_certificates] ? false : true)
    force_for_new_devices = !readonly
  
    match(
      git_branch: "master",
      app_identifier: "org.auderenow.fluathome-us.dev",
      team_id: "***",
      type: "development",
      readonly: readonly,
      force_for_new_devices: force_for_new_devices
    )
  
    match(
      git_branch: "master",
      app_identifier: "org.auderenow.fluathome-us",
      team_id: "***",
      type: "appstore",
      readonly: readonly
    )
  
    if options[:use_temporary_keychain]
      sh "security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k #{ENV["KEYCHAIN_NAME"]} #{ENV["KEYCHAIN_PASSWORD"]}"
    end
  end
  
  private_lane :create_temporary_keychain do
    keychain_name = "temporary_keychain"
    ENV["KEYCHAIN_NAME"] = keychain_name
    ENV["KEYCHAIN_PASSWORD"] = keychain_name
    ENV["MATCH_KEYCHAIN_NAME"] = keychain_name 
    ENV["MATCH_KEYCHAIN_PASSWORD"] = keychain_name
  
    create_keychain(
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )
  end
  
  ####### Builds #######
  
  desc "Submit a new build to TestFlight"
  lane :beta do 
    if is_ci 
      match(type:"appstore")
    else 
      certificates(
        use_temporary_keychain: true,
        refresh_certificates: false
      )
    end
    changelist = changelog_from_git_commits(
      # http://git-scm.com/docs/pretty-formats
      # - <short hash> <commit title>
      pretty: "- %h %s",
      tag_match_pattern: "chills_v1\.0\.*"
    )
    build_app(
      scheme: "fluathome Production",
      include_bitcode: true,
      export_method: "app-store"
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      changelog: ""
    )
    slack_announce(
      destination: "TestFlight", 
      changelist: changelist
    )
    git_tag
  end
  
  private_lane :git_tag do 
    version = get_version_number
    build = get_build_number
    release_type = ENV["EXPO_RELEASE_CHANNEL"]
    add_git_tag(
      tag: "chills_v#{version}_#{release_type}_#{build}",
      message: ENV["BUILD_DESCRIPTION"]
    )
    begin 
      push_to_git_remote
    rescue 
      UI.important "Push of tag appears to have failed, but tag may have been created."
    end 
  end 

  private_lane :slack_announce do |options|
    version = get_version_number
    build = get_build_number
    destination = options[:destination]
    changelist = options[:changelist]
    lasttag = Helper.backticks("git describe --match \"chills_v1\\.0\\.*\" --abbrev=0 --tags")
    ENV["SLACK_URL"] = ENV["SLACK_WEBHOOK"]
    slack(
      message: "flu@home Chills #{version} build #{build} has been uploaded to #{destination} :rocket:",
      default_payloads: [:git_branch, :last_git_commit_hash],
      payload: {
        "Built by" => ENV["CIRCLE_USERNAME"],
        "Description" => ENV["BUILD_DESCRIPTION"],
        "Release Type" => ENV["EXPO_RELEASE_CHANNEL"],
        "Changelog since #{lasttag}" => changelist,
        "Build log" => ENV["CIRCLE_BUILD_URL"]
      }
    )
  end

  desc "Increment build number and commit to current branch"
  lane :increment_build_number_and_commit do |options|
    versionBump = options[:versionBump]
    ensure_git_status_clean
    build_num = increment_build_number
    # Increment Android build number too so it's always in sync
    android_build_file = "FluStudy_us/android/app/version.properties"
    Helper.backticks("rm ../../../#{android_build_file}")
    Helper.backticks("echo VERSION_CODE=#{build_num} > ../../../#{android_build_file}")
    if versionBump 
      version = increment_version_number
      Helper.backticks("yarn version --patch --no-git-tag-version")
      message = "Build script incrementing Chills version to #{version}, build number to #{build_num}"
      include = ["FluStudy_us/package.json", "#{android_build_file}"]
    else 
      message = "Build script incrementing Chills build number to #{build_num}"
      include = ["#{android_build_file}"]
    end
    commit_version_bump(
      message: message, 
      xcodeproj: "fluathome.xcodeproj",
      include: include
    )
    push_to_git_remote(
      tags: false
    )
  end

  desc "Provision a device for running flu@home from source" 
  lane :register_new_device do |options|
    udid = Helper.backticks("system_profiler SPUSBDataType | sed -n -E -e '/(iPhone|iPad)/,/Serial/s/ *Serial Number: *(.+)/\\1/p'")
    if udid.length < 24
      UI.error "Error: Could not find udid for connected device. First connect your phone to this Mac."
    else 
      UI.message "Your device udid is: #{udid}" 
    end
    name = options[:name]
    username = options[:username]
    if name.to_s.empty?
      name = UI.input("Enter the device name: ")
    end
    if username.to_s.empty?
      username = UI.input("Enter the Apple ID email address you use for Audere's App Store Connect: ")
    end
    register_device(
      name: name,
      udid: udid,
      username: username
    )
    match(
      type: "development",
      force_for_new_devices: true
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id("***@***.org") # Your Apple email address
itc_team_id("***") # App Store Connect Team ID
team_id("***") # Developer Portal Team ID

for_lane :debug do
    app_identifier "org.auderenow.fluathome-us.dev"
end

for_lane :production do
    app_identifier "org.auderenow.fluathome-us"
end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.141.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.0.2        |
| jwt                       | 2.1.0        |
| emoji_regex               | 1.0.1        |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.14.0       |
| unicode-display_width     | 1.6.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| excon                     | 0.72.0       |
| faraday                   | 0.17.3       |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.7        |
| httpclient                | 2.8.3        |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| os                        | 1.0.1        |
| memoist                   | 0.16.2       |
| googleauth                | 0.10.0       |
| mini_mime                 | 1.0.2        |
| retriable                 | 3.1.2        |
| declarative-option        | 0.1.0        |
| declarative               | 0.0.10       |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| google-api-client         | 0.36.4       |
| digest-crc                | 0.4.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.25.1       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>

*generated on:* **2020-02-10**
</details></pre>
</details>

**Comment by rpassis** [comment]
Hi there,

I just noticed this issue and wanted to take a look to see where the regression may have been introduced (the original PR was created by me).

I noticed that the `upload_to_testflight.rb` action looks for a changelog in the shared environment via the line below (see [here](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/upload_to_testflight.rb#L8))

`changelog = Actions.lane_context[SharedValues::FL_CHANGELOG]`

If you look at the `changelog_from_git_commit` action you will notice that it sets that global variable when it is run as per code [here](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/changelog_from_git_commits.rb).

So I think what you will find is that if you run your changelog action after uploading the build to Testflight, you should see the behavior you expect. Could you please give this a try and post back here?

**Comment by tpaik18** [comment]
@rpassis That worked very well, thank you! I do feel though that looking for `changelog` in the shared environment is not what users would expect, so I hope we can go back to the behavior of changelog only used by `upload_to_testflight` if it is explicitly passed as argument.

**Comment by tpaik18** [comment]
@rpassis That worked very well, thank you! I do feel though that looking for `changelog` in the shared environment is not what users would expect, so I hope we can go back to the behavior of changelog only used by `upload_to_testflight` if it is explicitly passed as argument.

**Comment by rpassis** [comment]
@tpaik18 I do agree with you however this was not introduced by #15617, it is just a side-effect of the change we made there. FWIW I think it is unlikely that the `changelog_from_git_commits` action will change as it has been around for a long time and it is likely to break a lot of other people's scripts that assume the value will be set globally.
