### ISSUE TITLE
Support running fastlane inside a folder that is sibling to `fastlane` folder

### ISSUE THREAD

**Issue by manuyavuz-pointr** [fastlane/fastlane#16018]
### Feature Request

It would be nice to have if fastlane supports running `fastlane` from command line when current folder is a sibling to `fastlane` folder. Suppose following folder structure:

```
- repo
  - fastlane
    - Fastfile
  - sibling
    - sibling_subfolder
```

I should be able to run the following:
```
cd sibling
fastlane my_lane
cd sibling_subfolder
fastlane my_lane
```

#### Motivation Behind Feature

For people who are used to using `bundle`, `rake`, `thor` or `pod` commands from cli, it's a little bit inconvenient to not be able to run `fastlane` similarly. All of these libraries work if command is triggered from subfolders. They search backward towards parent folders, and take the first `Gemfile`, `Rakefile`, or `Podfile` as the source file for library.

#### Feature Description

I don't know if this is fundamentally opposing to how fastlane has built. But assuming lanes are always starting with pwd being the `fastlane` folder, it should not cause any problems in terms of backwards compatibility.

#### Alternatives or Workarounds

I have to `cd` to the folder which includes `fastlane` folder to be able to run a lane.

#### Implementation idea

It seems to me that if we just change this method and also glob over parents, it would provide the mentioned support.

https://github.com/fastlane/fastlane/blob/d56b0602298e1a58743c50b1f94fde7467d53589/fastlane_core/lib/fastlane_core/fastlane_folder.rb#L8-L16

Thanks for amazing tool!

**Comment by janpio** [comment]
Yes, that could probably work. I can also not think of a reason why this would be counter to what fastlane wants to be, besides maybe that it could be confusing to the user. We probably would also want to make sure to output any non standard path (`./fastlane`) when it is used as the developer should definitely be made aware of it.

Can you create a pull request maybe?
