### ISSUE TITLE
Get app version and status using fastlane?

### ISSUE THREAD

**Issue by ahimik** [fastlane/fastlane#16017]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Hi there,

I wonder if there is a way to get the latest app **version** and **status** using fastlane functionality without having Xcode Project set up on my machine?
I need to get both the latest version of the app which is on sale and the one which is currently in a progress and not submitted for review yet(I do undestand that I can get the latest pre-release version using AppStore Connect API but this is not the goal).

After I ran `fastlane init` I couldn't find any version information in metadata folder. I've also found https://docs.fastlane.tools/actions/get_version_number/ action but couldn't make it work since it requires XCode Project.

Here are the requirements:
- Get current app version which is not submitted for review yet.
- Get latest released app version(which is already on sale)
- Get latest released app version status(on sale, removed from sale etc..)

Thanks in advance.

**Comment by janpio** [comment]
The building blocks for all of that certainly are present in fastlane, or in the subproject `spaceship`. But you might very well have to invest some time in finding it and decoupling it from e.g. Xcode projects that might just be used to get the package name and similar.

**Comment by john-mejia** [comment]
How much of the app do you have available to provide to fastlane? You can do this pretty easily with spaceship.

```
## Get the version that is in edit mode (not yet submitted)
  version = Spaceship::Tunes::Application.find(APP_ID).edit_version

## Get latest live version
  version = Spaceship::Tunes::Application.find(APP_ID).live_version
## Get app status
  version.app_status
```

You would be calling spaceship from within your own lanes.

**Comment by ahimik** [comment]
Thanks for the suggestions. They are really helpful.
I've got less than 10 apps but the problem is that I am not familiar with Ruby and I am not sure I want to maintain my own version of FastLane. 
I'll use another workaround for now: I will retrieve that data directly from AppStoreConnect web site.
I understand they can change their site anytime so my app will be broken so in a meanwhile I'll start looking into your suggestions and FastLane code.
I am also afraid that it might be a bit slow listing all apps and statuses using FastLane. Hope I am wrong.

**Comment by john-mejia** [comment]
@ahimik - this doesn't mean you will be maintaining your own version of fastlane. Spaceship currently exists in fastlane. 

The only custom work you will do is create a new lane, in that lane you will make spaceship calls. You will call this lane just like you call any other lane. 

By hitting the API directly, it will be much slower and you will be essentially re-writing the work that spaceship has already done for you. 

Here are some good docs you can check out:
Spaceship docs: https://github.com/fastlane/fastlane/tree/master/spaceship

Good luck!

**Comment by janpio** [comment]
(Spaceship is really using the same APIs the website is using by the way - so by using Spaceship directly you safe the overhead of that)

**Comment by ahimik** [comment]
Haha! @john-mejia thanks for letting me know! I just looked into FastLane code and realized tham I am doing absolutely the same requests in the same way as you already did in FastLane... Thanks again, this will make my life easier.
