### ISSUE TITLE
Permission Issue with fastlane through Jenkins (`/` is not writable.)

### ISSUE THREAD

**Issue by prejithp-repo** [fastlane/fastlane#16012]
### New Issue Checklist
My fastlane setup is in a docker container, open jdk8 image. 

Fastlane version is 2.134.0

When i run fastlane command from jenkins pipeline, it projects an error '/' is not writable. When i run fastlane command without jenkins pipeline it workis fine. 
i run my container with the command 
docker run -dit -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/jenkins/workspace:/application --privileged <imagename>:latest

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> fastlane env
bundle exec fastlane env

[Pipeline] sh
+ bundle exec fastlane env
`/` is not writable.
Bundler will use `/tmp/bundler20200213-107-1x5tjfb107' as your home directory temporarily.
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
Gem::Exception: can't find executable fastlane for gem fastlane. fastlane is not currently included in the bundle, perhaps you meant to add it to your Gemfile?
  /var/lib/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/rubygems_integration.rb:374:in `block in replace_bin_path'
  /var/lib/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/rubygems_integration.rb:402:in `block in replace_bin_path'
  /usr/local/bin/fastlane:23:in `<top (required)>'
[Pipeline] }
[Pipeline] // script
 </pre>
</details>

### Environment

<details>
  <pre>
My jenkins Pipeline out is below:

 [Pipeline] sh
+ bundle exec fastlane env
`/` is not writable.
Bundler will use `/tmp/bundler20200213-107-1x5tjfb107' as your home directory temporarily.
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
Gem::Exception: can't find executable fastlane for gem fastlane. fastlane is not currently included in the bundle, perhaps you meant to add it to your Gemfile?
  /var/lib/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/rubygems_integration.rb:374:in `block in replace_bin_path'
  /var/lib/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/rubygems_integration.rb:402:in `block in replace_bin_path'
  /usr/local/bin/fastlane:23:in `<top (required)>'
[Pipeline] }
[Pipeline] // script

My command line output of fastlane env is below

[05:02:45]: fastlane detected a Gemfile in the current directory
[05:02:45]: however it seems like you don't use `bundle exec`
[05:02:45]: to launch fastlane faster, please use
[05:02:45]: 
[05:02:45]: $ bundle exec fastlane env
[05:02:45]: 
[05:02:45]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[05:02:46]: Sending anonymous analytics information
[05:02:46]: Learn more at https://docs.fastlane.tools/#metrics
[05:02:46]: No personal or sensitive data is sent.
[05:02:46]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
[05:02:46]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                     |
| --------------------------- | --------------------------------------------------------- |
| OS                          | debian_based 10.2                                         |
| Ruby                        | 2.5.5                                                     |
| Bundler?                    | false                                                     |
| Git                         | git version 2.20.1                                        |
| Installation Source         | /usr/local/bin/fastlane                                   |
| Host                        | Debian GNU/Linux 10 debian_based 10.2 (4.15.0-74-generic) |
| Ruby Lib Dir                | /usr/lib                                                  |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                               |
| Is contained                | false                                                     |
| Is homebrew                 | false                                                     |
| Is installed via Fabric.app | false                                                     |

### System Locale

| Variable | Value   |   |
| -------- | ------- | - |
| LANG     | C.UTF-8 | ✅ |
| LC_ALL   |         |   |
| LANGUAGE |         |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.134.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.1        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.72.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.1009  |
| mime-types                | 3.3.1        |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.3.0        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| stringio                  | 0.0.1        |
| openssl                   | 2.1.2        |
| strscan                   | 1.0.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| etc                       | 1.0.0        |
| io-console                | 0.4.6        |
| zlib                      | 1.0.0        |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
</details>

*generated on:* **2020-02-13**
</details>
[05:02:47]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[05:02:47]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅
 </pre>
</details>

**Comment by debeltranc** [comment]
In both cases, i.e. when it works and when it doesn't, are you running the Fastlane command inside the docker container? what command are you trying to run?
The error you are making reference to is a bundler error and not a Fastlane error though ([see this](https://github.com/rubygems/bundler/issues/6663))

**Comment by prejithp-repo** [comment]
Looking for related GitHub issues on fastlane/fastlane...

➡️  [33mPermission denied @ dir_s_mkdir - /var/empty/.fastlane[0m (Errno::EACCES)[0m
    https://github.com/fastlane/fastlane/issues/15989 [[31mopen[0m] 2 💬
    2 days ago

➡️  [33m`mkdir': [!] Permission denied @ dir_s_mkdir - fastlane/metadata (Errno::EACCES)[0m
    https://github.com/fastlane/fastlane/issues/12180 [[32mclosed[0m] 3 💬
    03 Jul 2018

➡️  [33mFails to generate snapshots[0m
    https://github.com/fastlane/fastlane/issues/13031 [[32mclosed[0m] 2 💬
    05 Oct 2018

and 9 more at: https://github.com/fastlane/fastlane/search?q=Permission%20denied%20%40%20dir_s_mkdir%20-%20%2F.fastlane&type=Issues&utf8=✓

/usr/lib/ruby/2.5.0/fileutils.rb:232:in `mkdir': [31m[!] Permission denied @ dir_s_mkdir - /.fastlane[0m (Errno::EACCES)
	from /usr/lib/ruby/2.5.0/fileutils.rb:232:in `fu_mkdir'
	from /usr/lib/ruby/2.5.0/fileutils.rb:210:in `block (2 levels) in mkdir_p'
	from /usr/lib/ruby/2.5.0/fileutils.rb:208:in `reverse_each'
	from /usr/lib/ruby/2.5.0/fileutils.rb:208:in `block in mkdir_p'
	from /usr/lib/ruby/2.5.0/fileutils.rb:193:in `each'
	from /usr/lib/ruby/2.5.0/fileutils.rb:193:in `mkdir_p'
	from /var/lib/gems/2.5.0/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/module.rb:28:in `fastlane_user_dir'
	from /var/lib/gems/2.5.0/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/analytics/analytics_session.rb:58:in `did_show_message?'
	from /var/lib/gems/2.5.0/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/analytics/analytics_session.rb:22:in `action_launched'
	from /var/lib/gems/2.5.0/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
	from /var/lib/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /var/lib/gems/2.5.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	from /var/lib/gems/2.5.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /var/lib/gems/2.5.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /var/lib/gems/2.5.0/gems/fastlane-2.141.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
[Pipeline] }
[Pipeline] // script
[Pipeline] }


I got this output. Fastlane is working fine locally. If i run fastlane deploy it gives  correct result without any error. If i run through jenkins pipeline it reflects to the above mentioned permission issue . Is this bundler error??
