### ISSUE TITLE
Follow up on #790, TeamCity Integration

### ISSUE THREAD

**Issue by mrk-han** [fastlane/fastlane#16021]
### Feature Request

TeamCity Integration / (OR perhaps Plugin Help)

#### Motivation Behind Feature
Recently stumbled upon #790 and could not find any follow up. Perhaps it was lost? Or maybe a feature request was never made. I know this is quite old, but we were just wondering if there was any work done to enable better usage with TeamCity.

We are looking to better control things like artifacts and stuff in fastlane instead of using the TeamCity UI, and I guess you could say we are just in the research phase :) 

#### Feature Description
See https://github.com/fastlane/fastlane/issues/790

**Comment by janpio** [comment]
This used to exist: https://docs.fastlane.tools/plugins/available-plugins/#fast_city Unfortunately the repo seems to be gone. Documentation still seems to exist: https://www.rubydoc.info/gems/fastlane-plugin-fast_city/0.8.18
