### ISSUE TITLE
verify_build searches for wrong Authority for provision_type

### ISSUE THREAD

**Issue by bonkey** [fastlane/fastlane#16020]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Running `verify_build` doesn't find IPA correctly signed.

The issue got found in a bigger pipeline, however, it fails in a simple command-line the same way.

`verify_build` looks for `/\AAuthority=i(Phone|OS)/` when `codesign -vv -d` returns:

```
...
Authority=Apple Distribution: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Authority=Apple Worldwide Developer Relations Certification Authority
Authority=Apple Root CA
...
```

https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/verify_build.rb#L49

##### Command executed

```ruby
  def validate_all!
    Fastlane::Actions::VerifyBuildAction.run(
      provisioning_type: 'distribution',
      ipa_path: @build_env.ipa_path,
      app_name: @build_env.app_name,
      bundle_identifier: @build_env.bundle_id,
      team_identifier: @build_env.team.team_id
    )
    # ...
  end
```

```shell
fastlane run verify_build bundle_identifier:$BUNDLE_ID ipa_path:$PATH provisioning_type:"distribution"
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
fastlane run verify_build bundle_identifier:ecg.move.CA ipa_path:/Users/dbauke/Projects/ios-client/output/MotorsCA.ipa provisioning_type:"distribution"
[✔] 🚀
+----------------------------+---------+-------------------+
|                       Used plugins                       |
+----------------------------+---------+-------------------+
| Plugin                     | Version | Action            |
+----------------------------+---------+-------------------+
| fastlane-plugin-simctl     | 0.2.1   | simctl            |
| fastlane-plugin-trainer    | 0.4.1   | trainer           |
+----------------------------+---------+-------------------+

[17:40:47]: --------------------------
[17:40:47]: --- Step: verify_build ---
[17:40:47]: --------------------------
caution: excluded filename not matched:  __MACOSX/*
caution: excluded filename not matched:  *.DS_Store

+-------------------+-------------------------------------------------------------------------------------------+
|                                       Summary for verify_build 2.141.0                                        |
+-------------------+-------------------------------------------------------------------------------------------+
| bundle_identifier | XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                          |
| authority         | ["XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", "Apple Worldwide Developer Relations  |
|                   | Certification Authority", "Apple Root CA"]                                                |
| team_identifier   | 4ANFEUTV3A                                                                                |
| app_name          | XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                          |
| provisioning_uuid | XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                          |
| team_name         | XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                          |
+-------------------+-------------------------------------------------------------------------------------------+

[!] Mismatched provisioning_type. Required: 'distribution'; Found: ''
  </pre>
</details>

### Environment

<details>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.15.3                                          |
| Ruby                        | 2.6.5                                            |
| Bundler?                    | true                                             |
| Git                         | git version 2.25.0                               |
| Installation Source         | ~/.rbenv/versions/2.6.5/bin/fastlane             |
| Host                        | Mac OS X 10.15.3 (19D76)                         |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.5/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-11.3.app/Contents/Developer/ |
| Xcode Version               | 11.3                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.141.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status  |
| -------------------------- | ------- | -------------- |
| fastlane-plugin-laadkisten | 2.0.0   | 💥 Check failed |
| fastlane-plugin-simctl     | 0.2.1   | ✅ Up-To-Date   |
| fastlane-plugin-trainer    | 0.4.1   | ✅ Up-To-Date   |

<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version      |
| -------------------------- | ------------ |
| bundler                    | 2.1.4        |
| rake                       | 13.0.1       |
| CFPropertyList             | 3.0.2        |
| concurrent-ruby            | 1.1.6        |
| i18n                       | 0.9.5        |
| minitest                   | 5.14.0       |
| thread_safe                | 0.3.6        |
| tzinfo                     | 1.2.6        |
| activesupport              | 4.2.11.1     |
| public_suffix              | 2.0.5        |
| addressable                | 2.7.0        |
| httpclient                 | 2.8.3        |
| json                       | 2.3.0        |
| algoliasearch              | 1.27.1       |
| ast                        | 2.4.0        |
| atomos                     | 0.1.3        |
| awesome_print              | 1.8.0        |
| babosa                     | 1.0.3        |
| claide                     | 1.0.3        |
| colored2                   | 3.1.2        |
| cork                       | 0.3.0        |
| nap                        | 1.1.0        |
| open4                      | 1.3.4        |
| claide-plugins             | 0.9.2        |
| clamp                      | 1.3.1        |
| fuzzy_match                | 2.0.4        |
| cocoapods-core             | 1.8.4        |
| cocoapods-deintegrate      | 1.0.4        |
| cocoapods-downloader       | 1.3.0        |
| cocoapods-plugins          | 1.0.0        |
| cocoapods-search           | 1.0.0        |
| cocoapods-stats            | 1.1.0        |
| netrc                      | 0.11.0       |
| cocoapods-trunk            | 1.4.1        |
| cocoapods-try              | 1.1.0        |
| escape                     | 0.0.4        |
| fourflusher                | 2.3.1        |
| gh_inspector               | 1.1.3        |
| molinillo                  | 0.6.6        |
| ruby-macho                 | 1.4.0        |
| nanaimo                    | 0.2.6        |
| xcodeproj                  | 1.15.0       |
| cocoapods                  | 1.8.4        |
| colored                    | 1.2          |
| highline                   | 1.7.10       |
| commander-fastlane         | 4.4.6        |
| multipart-post             | 2.0.0        |
| faraday                    | 0.17.3       |
| faraday-http-cache         | 2.0.0        |
| rchardet                   | 1.8.0        |
| git                        | 1.6.0        |
| kramdown                   | 2.1.0        |
| kramdown-parser-gfm        | 1.1.0        |
| no_proxy_fix               | 0.1.2        |
| sawyer                     | 0.8.2        |
| octokit                    | 4.16.0       |
| unicode-display_width      | 1.6.1        |
| terminal-table             | 1.8.0        |
| danger                     | 6.2.2        |
| ox                         | 2.13.2       |
| danger-junit               | 1.0.0        |
| danger-plugin-api          | 1.0.0        |
| jaro_winkler               | 1.5.4        |
| parallel                   | 1.19.1       |
| parser                     | 2.7.0.2      |
| rainbow                    | 3.0.0        |
| ruby-progressbar           | 1.10.1       |
| rubocop                    | 0.79.0       |
| danger-rubocop             | 0.7.1        |
| mini_portile2              | 2.4.0        |
| nokogiri                   | 1.10.8       |
| slather                    | 2.4.7        |
| danger-slather             | 0.0.6        |
| thor                       | 0.20.3       |
| danger-swiftlint           | 0.24.1       |
| danger-xcode_summary       | 0.5.1        |
| declarative                | 0.0.10       |
| declarative-option         | 0.1.0        |
| digest-crc                 | 0.4.1        |
| unf_ext                    | 0.0.7.6      |
| unf                        | 0.1.4        |
| domain_name                | 0.5.20190701 |
| dotenv                     | 2.7.5        |
| emoji_regex                | 1.0.1        |
| excon                      | 0.72.0       |
| http-cookie                | 1.0.3        |
| faraday-cookie_jar         | 0.0.6        |
| faraday_middleware         | 0.13.1       |
| fastimage                  | 2.1.7        |
| jwt                        | 2.1.0        |
| memoist                    | 0.16.2       |
| multi_json                 | 1.14.1       |
| os                         | 1.0.1        |
| signet                     | 0.12.0       |
| googleauth                 | 0.10.0       |
| mini_mime                  | 1.0.2        |
| uber                       | 0.1.0        |
| representable              | 3.0.4        |
| retriable                  | 3.1.2        |
| google-api-client          | 0.36.4       |
| google-cloud-env           | 1.3.0        |
| google-cloud-errors        | 1.0.0        |
| google-cloud-core          | 1.5.0        |
| google-cloud-storage       | 1.25.1       |
| mini_magick                | 4.10.1       |
| multi_xml                  | 0.6.0        |
| plist                      | 3.5.0        |
| rubyzip                    | 1.3.0        |
| security                   | 0.1.3        |
| naturally                  | 2.2.0        |
| simctl                     | 1.6.8        |
| slack-notifier             | 2.3.2        |
| terminal-notifier          | 2.0.0        |
| tty-screen                 | 0.7.1        |
| tty-cursor                 | 0.7.1        |
| tty-spinner                | 0.9.3        |
| word_wrap                  | 1.0.0        |
| rouge                      | 2.0.7        |
| xcpretty                   | 0.3.0        |
| xcpretty-travis-formatter  | 1.0.0        |
| fastlane-plugin-laadkisten | 2.0.0        |
| fastlane-plugin-simctl     | 0.2.1        |
| trainer                    | 0.9.1        |
| fastlane-plugin-trainer    | 0.4.1        |
| rubocop-performance        | 1.5.2        |
| ruby-git                   | 0.2.2        |
| semantic                   | 1.6.1        |
| xcode-install              | 2.6.3        |
| xcpretty-json-formatter    | 0.1.1        |
</details>

*generated on:* **2020-02-14**
</details>
</details>

**Comment by lemonkey** [comment]
I'm seeing this as well.

**Comment by lemonkey** [comment]
What's odd is that provisioning_type is as valid parameter for the verify_build() fastlane function, yet it's being ignored. :(

**Comment by lemonkey** [comment]
However my standalone lane test is successful with the same validate_build parameters used during the build, so there must be another environment variable at play here.

**Comment by rpassis** [comment]
Just had this happen to us as well. The issues is where validation happens - it uses a regex that expects `Authority=i(Phone|OS)` but the new multi-platform certificates use `Authority=Apple Distribution`.
