### ISSUE TITLE
I keep getting this issue with Android:  Build failed with an exception `javax/xml/bind/JAXBException`

### ISSUE THREAD

**Issue by h36ahmed** [fastlane/fastlane#16026]
Hi, I tried to implement fastlane for android and I keep getting the following issue when I run `assemble` gradle task from terminal using the command `fastlane internal`.

Build failed with an exception `javax/xml/bind/JAXBException`

How can I solve this? Any help will be appreciated.

My Java Version is 12.0.2
Fastlane version  is 2.141.0

```
# Ensure that your git status is not dirty
    ensure_git_status_clean


    gradle(
      task: "clean assemble", 
      flavor: "qa",
      build_type: "release"
    )

    upload_to_play_store(track: 'internal')
    notification(subtitle: "Successfully distributed a new internal build",
                 message: "Successfully distributed a new internal build")
```

**Comment by h36ahmed** [comment]
### Stack

| Key                         | Value                                        |
| --------------------------- | -------------------------------------------- |
| OS                          | 10.14.6                                      |
| Ruby                        | 2.7.0                                        |
| Bundler?                    | false                                        |
| Git                         | git version 2.21.1 (Apple Git-122.3)         |
| Installation Source         | ~/.rvm/gems/ruby-2.7.0-preview1/bin/fastlane |
| Host                        | Mac OS X 10.14.6 (18G95)                     |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.7.0-preview1/lib        |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                  |
| Is contained                | false                                        |
| Is homebrew                 | false                                        |
| Is installed via Fabric.app | false                                        |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/  |
| Xcode Version               | 11.3.1                                       |

**Comment by janpio** [comment]
Please do not delete the issue template. We need the information we are asking for, to understand what is going on. In your case for example, we have no idea what exactly is failing where and why.

**Comment by h36ahmed** [comment]
I solved the issue. This is how I solved it. It has all to do with Java version installed on the macbook. I had to reconfigure Java to 1.8

Setup Java:

* There maybe a chance that your java setup may not allow you to build the app
* Follow this [tutorial](https://dev.to/blacksourcez/setup-java-development-environment-for-macos-2pdg)

Deployment:

In order to deploy, simply run the commands in the terminal below:

* `jenv versions` to make sure that you have the correct package. It should be something like this, `openjdk64-1.8.0.`, but not exactly.
* If not, please do a command to select that package `jenv shell openjdk64-1.8.0`. Again the command is not going to be exact. Depends on the package number but it should be along the version `1.8.0`
* `jenv versions` check again to see if you have selected it
