### ISSUE TITLE
Generate Assets Packs for on demand resource tags and update Firebase

### ISSUE THREAD

**Issue by CRoig** [fastlane/fastlane#16037]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
What tool/action do you have a question about?  gym
Is this a question about documentation?  yes

#### Question Description

I am working on an iOS app which contains a huge amount of on demand resources (up to 6Gb). I am using fastlane as my CI tool. Although the xcode project settings is set to do not embed the assets in the binary (and post it on an external url), I am getting a huge ipa with everything packed. How I have to configure `gym` to generate the assets pack for me to upload to my managed host? Is there any possibility to automatically upload such assets pack to an S3 bucket?

**Comment by janpio** [comment]
> Although the xcode project settings is set to do not embed the assets in the binary (and post it on an external url)

How?

> Is there any possibility to automatically upload such assets pack to an S3 bucket?

Anything that is possible in Ruby, is possible in fastlane - and that can definitely be done. Question is how you tackle it.

**Comment by CRoig** [comment]
> How? 
There are some XCode project configuration that are missing such as the bitcode ones. Any way, not a big deal.

>  Question is how you tackle it.
I managed to make it work but inspecting .xcarchive. The problem now is internal routing. I am doing some test.

**Comment by fahadhaq** [comment]
Could you please let me know which command you are using to generate the asset packs using fastlane? Thanks in advance.I have looked through the doc but wasn't able to see anything that would help.

**Comment by CRoig** [comment]
I used export options of `gym`

```
gym(scheme: scheme, 
    export_method: "ad-hoc", 
    archive_path: "./Archive",
    export_options: { 
	compileBitcode: false, 
	uploadBitcode: false,
	embedOnDemandResourcesAssetPacksInBundle: false,
	onDemandResourcesAssetPacksBaseURL: $assets_remote_path
    }
)
```

Once `gym` finishes, I could find assets pack on `Archive.xcarchive/Producs/OnDemandResources`. I am pushing them into my server. But the problem I am facing now is `AssetPackManifestTemplate.plist` on the `<my_app>.app` points to my local Derived Data. Thus, the installed app can not access tags. 😢

**Comment by CRoig** [comment]
Update: My last comment was no accurate. It is true that OnDemandResources are included oon the xcarchive, but those "folders" are not able to be used since they are unsigned. They need to be signed to be converted in "files" which are able to be consumed by app from a server.

I am tuning `gym` export params to achieve my goal. I will close the issue if I find a solution. In the meanwhile, I would appreciate any help.

Thanks

**Comment by CRoig** [comment]
Continuing my investigation I found out the path where asset packs are generated. They area placed on a temporal folder. Appearing on the generated `xcodebuild` command:

```
/usr/bin/xcrun /Users/<user>/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fastlane-2.142.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/0c/zjyj2w4d0cxg0vjv6ftdk6wc0000gr/T/gym_config20200303-17713-1g895h.plist' -archivePath /Users/<user>/Library/Developer/Xcode/Archives/2020-03-03/BetVictor\ 2020-03-03\ 14.30.14.xcarchive -exportPath '/var/folders/0c/zjyj2w4d0cxg0vjv6ftdk6wc0000gr/T/gym_output20200303-17713-1tn62w9' 
```
Is there any way to override `/var/folders/0c/zjyj2w4d0cxg0vjv6ftdk6wc0000gr/T/gym_output20200303-17713-1tn62w9` ???

Or at least to identify that folder to copy it

**Comment by jonnyjorvik** [comment]
Having the same issue. I've tried setting `output_directory`, `build_path` and `result_bundle: true` and none of these options seems to produce a set of signed ODR (i.e. like doing it via XCode `Archive` would).

**Comment by fahadhaq** [comment]
@jonnyjorvik try the following suggestion to see if it helps. I haven't had a chance to test mine again but I couldn't get the singed ORD files either.

https://github.com/fastlane/fastlane/pull/16117#issuecomment-597037954

**Comment by fahadhaq** [comment]
So my issue was I was using Legacy build system win Fastlane to create the On Demand resources and when running my app from Xcode I was using the new build system. That is why I couldn't access my Resources and nothing was downloading. Hope this will help someone. Make sure the build systems are same when creating and running the app
