### ISSUE TITLE
Match with Multiple Bundle Ids and Multiple Team Ids

### ISSUE THREAD

**Issue by kwstasna** [fastlane/fastlane#16036]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Hello, I have a question about how `match` works with multiple bundle identifiers each bundle refer to different team id. Is it possible to have those two Bundle identifiers on the same git repo ? 

(Working on different repos works just fine)

**Comment by janpio** [comment]
Does this answer you question?
https://docs.fastlane.tools/actions/match/#multiple-teams
