### ISSUE TITLE
a better way to use sigh and gym?

### ISSUE THREAD

**Issue by xinsight** [fastlane/fastlane#16045]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

When running shell commands, is there an easier way to use `sigh` with `gym` together?

#### Question Description

For various reasons I cannot use `match`, so I am using `sigh` to download a suitable provisioning profile. And then am using `gym` to build with that provisioning profile. I am doing this from a Jenkins pipeline so I am essentially running shell commands in groovy. As I am not in a ruby environment, the results of `sigh` are not stashed in the `shared_lane` or environment variables, so I need to extract the uuid of the provisioning profile, and then pass that to gym. It's a more than a little awkward - is there a better way?

```
// download provisioning profile
sh("""fastlane sigh \
--username=${APPLE_USERNAME} \
--team_id=${ENTERPRISE_TEAM_ID} \
--app_identifier=${cfg.bundle_id} \
--filename=${provisioningProfile}
""")

// sigh doesn't tell us anything, so we need to "decrypt" (decode) and inspect the mobileprovision
sh "/usr/bin/security cms -D -i ${provisioningProfile} -o ${provisioningProfilePlain}"
def uuid = sh(script: "/usr/libexec/PlistBuddy -c 'print UUID' ${provisioningProfilePlain}", returnStdout: true).trim()

// create a plist for xcode with the bundle id and provisioning profile
def exportOptions = "exportOptions.plist"
def json = "{\\\"provisioningProfiles\\\":{\\\"${cfg.bundle_id}\\\":\\\"${uuid}\\\"}}"
sh "echo ${json} | plutil -convert xml1 -o ${exportOptions} -"

// finally we can build
sh("""fastlane gym \
--configuration=${debug} \
--export_options=${exportOptions} \
--skip_profile_detection=true \
--archive_path=${env.ARCHIVES_PATH} \
--derived_data_path=${env.DERIVED_DATA_PATH} \
--include_symbols=true \
--include_bitcode=false \
--scheme=\"${cfg.scheme}\" \
--output_directory=${cfg.output_directory} \
--output_name=${cfg.output_name} \
--export_method=enterprise \
--xcpretty_report_junit=fastlane/report.junit \
--xcpretty_report_html=fastlane/report.html
""")
```

One improvement would be a command to get a UUID from a provisioning profile. (I can work on this if it doesn't exist already.) But a better improvement would be the ability to pass a provisioning profile uuid into `gym`, instead of having to create a plist and pass the filename in `export_options`. Thoughts?

**Comment by janpio** [comment]
Have you checked the environment variables? The `uuid` might also be available in `SIGH_UUID`.

**Comment by xinsight** [comment]
AFAIK, child processes cannot set the environment of the parent process.

If you have a script called `setenv.rb`:

```ruby
#!/usr/bin/env ruby  
ENV["FOO"] = "bar"
```

It will not set the environment variable `FOO` in the parent process.

```bash
./setenv.rb && env | grep FOO # nothing is returned
```

(The only way this would work, is if the script dumped something that could then be executed by the shell. e.g. if the output was `export FOO="bar"` - but that's not how any fastlane commands currently work.)

But even if was easier to get the provisioning profile UUID from the environment, my question still stands, as it still seems *crazy complicated* to pass the UUID on to `gym` with a plist and the export_options parameter.
