### ISSUE TITLE
fastlane-bot should not close PRs

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#16048]
Ohoh, something seems to funky with @fastlane-bot :

![image](https://user-images.githubusercontent.com/183673/74819948-77e83200-5301-11ea-86c0-affbb0a3fbf3.png)

https://github.com/fastlane/fastlane/pull/15349#event-3049593605
https://github.com/fastlane/fastlane/pull/15359#event-3049593563
https://github.com/fastlane/fastlane/pull/15364#event-3049593519
https://github.com/fastlane/fastlane/pull/15475#event-3049593317
...

It should really not close PRs that are waiting for review and merge.

@mollyIV?

**Comment by janpio** [comment]
Reopened the PRs manually.

**Comment by mollyIV** [comment]
Hey @janpio 👋 

Recently we merged this one: https://github.com/fastlane/fastlane/pull/15890. 

According to the config file, we close the PRs 7 days after adding a `'status: needs-attention'` label.:

```yaml
days-before-stale: 30
days-before-close: 7
```

so it is working as expected 👍 

To not get the PR closed, we shall remove the `'status: needs-attention'` label. We can also think about increasing a time interval for closing the PR (counting it from marking it as stale).

**Comment by janpio** [comment]
This never applied to _pull requests_ before, only to _issues_. Pull Requests with code should never be closed and thrown away.

**Comment by mollyIV** [comment]
Unfortunately there's no such option to just disable closing of PRs in a [`stale` GitHub Action](https://github.com/actions/stale) for now. So if we do not want to close the prs that are stale, we should remove our [`stale.yml` workflow file](https://github.com/fastlane/fastlane/blob/master/.github/workflows/stale.yml) from this repo. 

Please confirm and I will do that 🤚 

However maybe increasing a time interval for closing the PRs, let's say 60 days from a time it's being marked as stale, could do the job too 🤔 Please note that change would apply to the issues too.

**Comment by janpio** [comment]
No, we have much older PRs open unfortunately - and we do not want to keep issues around as long.

Shame. Seems we need to fork the action... 🤷‍♂

**Comment by mollyIV** [comment]
🎁 https://github.com/fastlane/fastlane/pull/16051
