### ISSUE TITLE
Xcode 11 with Swift Package ARCHIVE failed at Gym where Scan works well

### ISSUE THREAD

**Issue by HevaWu** [fastlane/fastlane#16046]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

After adding swift package into our project, our fastlane deploy always failed at `gym` command. But `scan` works well. 

##### Command executed

```
gym(
      scheme: scheme,
      output_directory: '.build/beta',
      configuration: 'Enterprise',
      export_options: "./ExportOptions_AppDeploy.plist",
      xcconfig: "our config"
    )
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
There is a achive failed first

** ARCHIVE FAILED **

The following build commands failed:
	SwiftCodeGeneration normal arm64
	CompileSwift normal armv7
	CompileSwift normal arm64
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
	CompileSwift normal armv7
	CompileSwift normal arm64
(6 failures)

Then for our swift packages. we got some error like ⬇️
"method does not override any method from its superclass"
"CompileSwift normal arm64 (in target 'our swift package' from project 'our swift package')"
 </pre>
</details>

I've checked the error log, all of the error are related to our `local swift package`. For the local one, should we add more settings at `gym` part? Since `scan` works well 🤔 

### Environment

<details>
  <pre> 
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.4                                     |
| Ruby                        | 2.7.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.23.0                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.14.4 (18E226)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.0/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.3                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
  desc "Runs all the tests"
  lane :test do
    install
    scan(workspace: workspace, scheme: scheme, sdk: sdk, devices: devices)
  end

  desc "Deploy a new beta build to the App Deploy"
  lane :beta do
    ensure_git_status_clean
    install
    ipa = gym(
      scheme: scheme,
      output_directory: '.build/beta',
      configuration: 'Enterprise',
      export_options: "AppDeploy.plist",
      xcconfig: "Beta.xcconfig"
    )
  end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.142.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.10.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.0        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| uri                       | 0.10.0       |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.15.0       |
| unicode-display_width     | 1.6.1        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| excon                     | 0.72.0       |
| bundler                   | 2.1.2        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| forwardable               | 1.3.1        |
| logger                    | 1.4.2        |
| cgi                       | 0.1.0        |
| timeout                   | 0.1.0        |
| stringio                  | 0.1.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.2.0        |
| strscan                   | 1.0.3        |
| date                      | 3.0.0        |
| delegate                  | 0.1.0        |
| fileutils                 | 1.4.1        |
| io-console                | 0.5.3        |
| zlib                      | 1.1.0        |
| singleton                 | 0.1.0        |
| rexml                     | 3.2.3        |
| open3                     | 0.1.0        |
| yaml                      | 0.1.0        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>

*generated on:* **2020-02-19**
</details>
 </pre>
</details>

**Comment by HevaWu** [comment]
I updated the `Fastlane env` part, please help checking it again ~

**Comment by HevaWu** [comment]
After reading the log carefully, we found maybe this is because one of our swift package settings are wrong. This might not the fastlane issue. So I will close this ticket. 

It's very interested that `scan` passed but `gym` failed. 
Sorry for bothering. mm

**Comment by maxhis** [comment]
@HevaWu hello Heva, can you share your workaround? I'm facing the same issue. Which part of your swift package settings are wrong?

**Comment by HevaWu** [comment]
Hi @maxhis ,

The precondition for this issue is:
- use the Swift Package in your project
- `scan` works well, but `gym` fails 

So in my case, we are using `scan` under `Test/Debug` env, and using `gym` for `Beta/Alpha/RC` deploy. I fix my problem by ⬇️ 

```swift
// as-is
SWIFT_ACTIVE_COMPILATION_CONDITIONS = BETA

// to-be
SWIFT_ACTIVE_COMPILATION_CONDITIONS = $(inherited) BETA
```

### **Details about our problem**

After reading our crash log, our crash log shows some info like: ⬇️ where `APIKit` is the Swift Package we are using. 
```
❌  /SourcePackages/checkouts/APIKit/Sources/APIKit/BodyParameters/MultipartFormDataBodyParameters.swift:170:22: property does not override any property from its superclass

        override var hasBytesAvailable: Bool {
                                      ^~~~~~~~~~~~~~
```

By go inside to check this package source code. We find they are using the `SWIFT_PACKAGE` build flags ⬇️ 

```swift
#if SWIFT_PACKAGE
    class AbstractInputStream: InputStream {
        init() {
            super.init(data: Data())
        }
    }
#endif
```

This flag which have conflicts with our client settings at the `SWIFT_ACTIVE_COMPILATION_CONDITIONS` part. It seems it cannot recognize the `SWIFT_PACKAGE` definition, so it cannot find the correct superclass. 

By fixing this problem, do ⬇️  

```swift
// as-is
SWIFT_ACTIVE_COMPILATION_CONDITIONS = BETA

// to-be
SWIFT_ACTIVE_COMPILATION_CONDITIONS = $(inherited) BETA
```

You could find the details crash log in this issue ->
https://github.com/ishkawa/APIKit/issues/280

Here is some related issue about `inherited` settings ->
https://github.com/CocoaPods/CocoaPods/issues/6625

Hope this could help you ~ 😆

**Comment by maxhis** [comment]
Thanks for your detail description of the issue, @HevaWu ! Although I'm using CocoaPods, it seems you point out the right direction for me.🙏
