### ISSUE TITLE
Fastlane cannot update itself (from 2.138.0)

### ISSUE THREAD

**Issue by alakoring** [fastlane/fastlane#16056]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

So I lied — I did not actually update fastlane because that is the bug. It no longer does.

Fastlane should always be able to update itself. It seems to have introduced a bad dependency, and no longer is able to update.

I'm running macOS Mojave 10.14.6. I have never needed to install special software to run fastlane.

ERROR:  Error installing fastlane:
	signet requires Ruby version >= 2.4.0.

ruby --version
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]

##### Command executed

sudo gem install fastlane

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
ERROR:  While executing gem ... (OptionParser::InvalidOption)
    invalid option: --capture_output
</pre>
</details>

### Environment

<details>
  <pre><details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.21.0 (Apple Git-122.2)                           |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.6 (18G3020)                                     |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.2.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

# Assume Slack is configured by the SLACK_URL environment variable

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.138.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.14.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.71.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday                   | 0.17.0       |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.2        |
| json                      | 1.8.3.1      |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.1       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.3        |
| jwt                       | 2.1.0        |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 0.1.1        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| psych                     | 2.1.0.1      |
</details>

*generated on:* **2020-02-19**
</details></pre>
</details>

**Comment by max-ott** [comment]
I think the error message is pretty clear. You need ruby 2.4.0. Could you please update and then try it again?

**Comment by alakoring** [comment]
I had actually tried that last month. It was horribly confusing (I now have to learn about Ruby tooling like RVM?), forced me to be an admin user (not just a sudo-er), required downloading a bunch of other stuff that was not Ruby, and did not work.

Somehow today `brew install ruby` did work. So at least I can go forward.

However, I still believe it is a bug for fastlane to rely on external stuff that it cannot update itself. If it runs on Mojave, it needs to run on a stock Mojave. Please don’t assume that your users have any knowledge of Ruby, its ecosystem, or even the broader open source ecosystem.

**Comment by max-ott** [comment]
More than happy to review your pull request that removes the 3rd party dependencies or adds those “magic” self-updating mechanisms. Fastlane is open-source, so we’re living from contributions from the community.

**Comment by alakoring** [comment]
OK, something is weird.

```
bash-3.2$ sudo gem install fastlane
Password:
Successfully installed fastlane-2.143.0
Parsing documentation for fastlane-2.143.0
Done installing documentation for fastlane after 4 seconds
1 gem installed
bash-3.2$ fastlane --version
fastlane installation at path:
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.138.0/bin/fastlane
-----------------------------
[✔] 🚀 
fastlane 2.138.0

#######################################################################
# fastlane 2.143.0 is available. You are on 2.138.0.

```

Fastlane is not properly updating, if it still thinks it is out of date right after an update.

(I appreciate all the people who contribute to fastlane, but I miss the days when it was a product and not an open source project. I was once able to use it to automate things without knowing anything about Ruby.)
