### ISSUE TITLE
`supply` tries to set `:apk` even if `:aab` is explicitly provided (or if the file doesn't exist)

### ISSUE THREAD

**Issue by dhleong** [fastlane/fastlane#16069]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

If you run `gradle()`, it will populate APK output paths, which `supply()` uses to fill `:apk`. However, if you subsequently run `gradle()` with `"clean"` to generate a bundle, the APK paths are still cached, and `supply` throws an error

##### Command executed

In one lane, I'm currently building an APK for distribution to Firebase, and a bundle for uploading to the Play Store, so I don't have a single command here. However, I glanced through the code for `upload_to_play_store` and I believe my assessment above is correct. Probably, we should skip using the `SharedValues::GRADLE_APK_OUTPUT_PATH` etc if they don't exist.

##### Complete output when running fastlane, including the stack trace and command used

(omitted, see above)

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 10.15.3                                                 |
| Ruby                        | 2.5.5                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.21.1 (Apple Git-122.3)                    |
| Installation Source         | /usr/local/Cellar/fastlane/2.141.0/libexec/bin/fastlane |
| Host                        | Mac OS X 10.15.3 (19D76)                                |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.5/2.5.5_1/lib                  |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                             |
| Is contained                | false                                                   |
| Is homebrew                 | false                                                   |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 11.3.1                                                  |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:android)

REPO = "interspace/veetoo"
BETA_NOTES_FILE = ".last-beta-notes"
APK_PATH = "../app/build/outputs/apk/prod/release/app-prod-release.apk"
AAB_PATH = "../app/build/outputs/bundle/prodRelease/app-prod-release.aab"

platform :android do
  before_all do
    gradle = File.open("../build.gradle").read
    versionName = gradle.match(/versionName: "(.*)"/) { |m| m.captures[0] }
    versionCode = gradle.match(/versionCode: (\d*),/) { |m| m.captures[0] }
    Actions.lane_context["GIT_TAG"] = "ff/#{versionName}"
    Actions.lane_context["VERSION_NAME"] = versionName
    Actions.lane_context["VERSION_CODE"] = versionCode
    Actions.lane_context["RELEASE_NOTES_PATH"] = "metadata/android/en-US/changelogs/#{versionCode}.txt"

    # ensure a github token:
    if not ENV["GITHUB_TOKEN"]
      UI.message "Trying to read GH token from #{ENV["HOME"]}/.config/hub"
      config = File.open("#{ENV["HOME"]}/.config/hub").read
      ENV["GITHUB_TOKEN"] = config.match(/oauth_token: (.*)$/) { |m| m.captures[0] }
    end
    UI.user_error! "No GITHUB_TOKEN found." unless ENV["GITHUB_TOKEN"]

  end

  desc "Verify version has been updated"
  private_lane :verify_version do |options|
    versionName = Actions.lane_context["VERSION_NAME"]
    versionCode = Actions.lane_context["VERSION_CODE"]

    tagExists = git_tag_exists(tag: Actions.lane_context["GIT_TAG"])

    if tagExists
      UI.user_error! "Tag for version #{versionName} already exists!"
    else
      UI.message "New version #{versionName} ##{versionCode}"
    end

    not tagExists
  end

  desc "Create release notes in vim"
  private_lane :release_notes_vim do
    UI.user_error! "Release notes for ##{Actions.lane_context["VERSION_CODE"]} already exist!" if File.exists?(Actions.lane_context["RELEASE_NOTES_PATH"]) && !File.exists?(BETA_NOTES_FILE)

    notes = File.open(BETA_NOTES_FILE).read if File.exists?(BETA_NOTES_FILE)

    if not notes
      notes = changelog_from_git_commits(
        pretty: "- %s",
      ).downcase
      notes = "hello there! here's what we've got today:\n\n#{notes}\n\nenjoy!\n\n*byte team"

      system({"VIM_RELEASE_NOTES" => notes},
             'vim', BETA_NOTES_FILE,
             "-c", "silent put=$VIM_RELEASE_NOTES")
    else
      # notes file exists already; just edit it
      system('vim', BETA_NOTES_FILE)
    end
    system('reset')

    if not File.exists?(BETA_NOTES_FILE)
      UI.user_error! "No release notes written"
    end

    # copy to correct path
    sh "cp", BETA_NOTES_FILE, Actions.lane_context["RELEASE_NOTES_PATH"]

    next unless verify_release_notes

    File.exists?(BETA_NOTES_FILE)
  end

  desc "Ensure that release notes for the current version exist"
  private_lane :verify_release_notes do
    notes = File.open(Actions.lane_context["RELEASE_NOTES_PATH"]).read
    UI.user_error! "No release notes for v#{"VERSION_CODE"}!" unless notes
    Actions.lane_context["RELEASE_NOTES"] = notes
  end

  desc "Create a github release with the tag and release notes"
  private_lane :github_release do
    next unless verify_release_notes

    # verify this is a new release
    UI.user_error! "Release #{Actions.lane_context["GIT_TAG"]} already exists!" if git_tag_exists(tag: Actions.lane_context["GIT_TAG"])

    # create the tag
    add_git_tag(
      tag: Actions.lane_context["GIT_TAG"],
      message: Actions.lane_context["RELEASE_NOTES"]
    )
    push_to_git_remote(tags: true)

    # find assets (TODO: contribute from lanes?)
    assets = []
    if File.exists?(APK_PATH)
      # use the absolute path, since github_release seems like it
      # runs in the project root
      assets << File.realpath(APK_PATH)
    else
      UI.important "APK not found"
    end

    UI.important assets

    # create the release
    set_github_release(
      repository_name: REPO,
      name: Actions.lane_context["GIT_TAG"],
      tag_name: Actions.lane_context["GIT_TAG"],
      api_token: ENV["GITHUB_TOKEN"],
      description: Actions.lane_context["RELEASE_NOTES"],
      upload_assets: assets,
    )
  end

  desc "Submit a new Beta Build to Firebase App Distribution"
  private_lane :firebase do
    verify_release_notes
    gradle(task: "clean assembleProdRelease")

    apk = File.realpath(APK_PATH)
    firebase_app_distribution(
      app: "1:236591221969:android:35d4d211a6d01aca",
      groups_file: "beta-data/firebase-ff-beta.groups",
      release_notes: Actions.lane_context["RELEASE_NOTES"],
      apk_path: apk
    )

    # explicitly clear apk paths from context to prevent
    # upload_to_play_store from trying to use them
    Actions.lane_context[SharedValues::GRADLE_ALL_APK_OUTPUT_PATHS] = nil
    Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH] = nil
  end

  desc "Deploy a new version to the Google Play Alpha track"
  private_lane :alpha do
    verify_release_notes
    gradle(task: "clean bundleProdRelease")

    aab = File.realpath(AAB_PATH)
    upload_to_play_store(
      track: 'alpha',
      aab: aab,
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
    )
  end

  desc "Fetch release notes from a github release"
  private_lane :fetch_github_release do
    release = get_github_release(
      url: REPO,
      version: Actions.lane_context["GIT_TAG"],
      api_token: ENV["GITHUB_TOKEN"],
    )
    Actions.lane_context["RELEASE_NOTES"] = release['body']
    File.open(Actions.lane_context["RELEASE_NOTES_PATH"], 'w') { |f|
      f.puts Actions.lane_context["RELEASE_NOTES"]
    }
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "testProdRelease")
  end

  desc "Promote the Google Play Alpha track to Production"
  lane :promote do
    upload_to_play_store(
      track: 'alpha',
      track_promote_to: 'production',
      version_code: Actions.lane_context["VERSION_CODE"],
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
    )
  end

  desc "Partially Promote the Google Play Alpha track to Production"
  lane :promote_partial do |options|
    upload_to_play_store(
      track: 'alpha',
      track_promote_to: 'production',
      release_status: 'inProgress',
      rollout: options[:percent] || "0.2",
      version_code: Actions.lane_context["VERSION_CODE"],
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
    )
  end

  desc "One-stop test and deploy for Firebase ONLY"
  lane :deploy_firebase do
    next unless verify_version
    next unless release_notes_vim
    test
    firebase
    github_release

    File.delete(BETA_NOTES_FILE)
    UI.message "Done!"
  end

  desc "Test and deploy from CI --- requires release notes already created"
  lane :deploy_ci do
    fetch_github_release
    next unless verify_release_notes

    test
    firebase
    alpha
    UI.message "Done!"
  end

  desc "One-stop test and deploy"
  lane :deploy do
    next unless verify_version
    next unless release_notes_vim

    test
    firebase
    alpha
    github_release

    File.delete(BETA_NOTES_FILE)
    UI.message "Done!"
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file(".publishing/play-service-key.json") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("co.byte") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.142.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.1.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| slack-notifier                            | 2.3.2        |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.6.1        |
| terminal-table                            | 1.8.0        |
| plist                                     | 3.5.0        |
| CFPropertyList                            | 3.0.2        |
| public_suffix                             | 2.0.5        |
| addressable                               | 2.7.0        |
| multipart-post                            | 2.0.0        |
| word_wrap                                 | 1.0.0        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| babosa                                    | 1.0.3        |
| colored                                   | 1.2          |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| excon                                     | 0.72.0       |
| faraday                                   | 0.17.3       |
| unf_ext                                   | 0.0.7.6      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.6        |
| faraday_middleware                        | 0.13.1       |
| fastimage                                 | 2.1.7        |
| gh_inspector                              | 1.1.3        |
| json                                      | 2.3.0        |
| mini_magick                               | 4.10.1       |
| multi_xml                                 | 0.6.0        |
| rubyzip                                   | 1.3.0        |
| security                                  | 0.1.3        |
| xcpretty-travis-formatter                 | 1.0.0        |
| dotenv                                    | 2.7.5        |
| bundler                                   | 2.1.4        |
| jwt                                       | 2.1.0        |
| uber                                      | 0.1.0        |
| declarative                               | 0.0.10       |
| declarative-option                        | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| mini_mime                                 | 1.0.2        |
| multi_json                                | 1.14.1       |
| signet                                    | 0.12.0       |
| memoist                                   | 0.16.2       |
| os                                        | 1.0.1        |
| googleauth                                | 0.10.0       |
| httpclient                                | 2.8.3        |
| google-api-client                         | 0.36.4       |
| google-cloud-env                          | 1.3.0        |
| google-cloud-errors                       | 1.0.0        |
| google-cloud-core                         | 1.5.0        |
| digest-crc                                | 0.4.1        |
| google-cloud-storage                      | 1.25.1       |
| emoji_regex                               | 1.0.1        |
| nanaimo                                   | 0.2.6        |
| colored2                                  | 3.1.2        |
| claide                                    | 1.0.3        |
| atomos                                    | 0.1.3        |
| xcodeproj                                 | 1.15.0       |
| tty-screen                                | 0.7.1        |
| naturally                                 | 2.2.0        |
| simctl                                    | 1.6.8        |
| fastlane-plugin-firebase_app_distribution | 0.1.4        |
</details>

*generated on:* **2020-02-21**
</details>

**Comment by dhleong** [comment]
Another idea is if `gradle` is fun with the clean task we should clear any previously-set outputs?

**Comment by janpio** [comment]
Are you saying that if you run `gradle` and it does not output an APK, it should unset any potentially already present values in the `SharedValues`?

**Comment by dhleong** [comment]
> Are you saying that if you run gradle and it does not output an APK, it should unset any potentially already present values in the SharedValues?

Or rather, if running `gradle` *deletes* an APK that was previously output, the lane state should be updated to reflect that. You could run `gradle("assemble")` then `gradle("bundle")` and both APK and AAB might exist, but if you ran `gradle("clean assemble")` then `gradle("clean bundle")`, the APK would be removed by the second clean, and having the APK in the lane context might lead subsequent actions to think it exists when it has, in fact, been deleted.

**Comment by janpio** [comment]
Uh, are there any other commands than `clean` that could get rid of the file? Will `clean` always get rid of the file? (My Android days were a bunch of years ago...)

**Comment by dhleong** [comment]
`clean` is the default, but people can make their own commands so there's probably no way to actually predict based on that. Sorry for the noise; it was a long day yesterday.

It may be safest to just verify that the paths actually exist after running the gradle command? I'm not terribly familiar with ruby but this might be the culprit:

```ruby
        Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH] = File.expand_path(last_apk_path) if last_apk_path
```

If I'm reading this correct, but it seems that if `last_apk_path` is `nil`, the context will be left unchanged?

**Comment by janpio** [comment]
Almost, this basically says "if `last_apk_path` ha been set before, write it to the `SharedValues`". There is no checking if the file exists yet - but adding that could potentially solve the problem you are describing I think.
