### ISSUE TITLE
The version number has been previously used

### ISSUE THREAD

**Issue by saroar** [fastlane/fastlane#16064]
### New Issue Checklist

- [x] Updated fastlane to the latest version > DONE
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md) > DID
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools) > DID
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues) > DID

```
bundle exec fastlane -v
fastlane installation at path:
/Users/alif/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.142.0/bin/fastlane
-----------------------------
[✔] 🚀 
fastlane 2.142.0
```

### Issue Description
```
[!] The request could not be completed because:
     The version number has been previously used. There are one or more errors on the page.
```
same version and build upload via Xcode working fine

##### Command executed
```
[!] The request could not be completed because:
     The version number has been previously used. There are one or more errors on the page.
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
// 🍏   fastlane --capture_output
[14:47:22]: fastlane detected a Gemfile in the current directory
[14:47:22]: However, it seems like you didn't use `bundle exec`
[14:47:22]: To launch fastlane faster, please use
[14:47:22]: 
[14:47:22]: $ bundle exec fastlane --capture_output
[14:47:22]: 
[14:47:22]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2020-02-21 14:47:24.61]: Checking if there are any plugins that should be loaded...
INFO [2020-02-21 14:47:26.36]: ------------------------------
INFO [2020-02-21 14:47:26.36]: --- Step: default_platform ---
INFO [2020-02-21 14:47:26.36]: ------------------------------
INFO [2020-02-21 14:47:26.37]: Welcome to fastlane! Here's what your app is set up to do:
WARN [2020-02-21 14:47:26.37]: Which number would you like run?
👨  💻  (master) AddaIOS
</pre>
</details>

### Environment
<details>
  <pre> 
### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.6 (18G3020)                  |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.3.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    build_app(workspace: "AddaIOS.xcworkspace", scheme: "AddaIOS")
    upload_to_app_store
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.Addabuz") # The bundle identifier of your app
apple_id("saroarkhandoker@yahoo.com") # Your Apple email address

itc_team_id("119123163") # App Store Connect Team ID
team_id("6989658CU5") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.138.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.14.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.71.1       |
| faraday                   | 0.17.0       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.14.6       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.1009  |
| mime-types                | 3.1          |
| multi_json                | 1.14.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.0        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| libxml-ruby               | 3.0.0        |
| psych                     | 2.0.8        |
</details>
// 🍏   fastlane env --capture_output
[14:48:56]: fastlane detected a Gemfile in the current directory
[14:48:56]: However, it seems like you didn't use `bundle exec`
[14:48:56]: To launch fastlane faster, please use
[14:48:56]: 
[14:48:56]: $ bundle exec fastlane env --capture_output
[14:48:56]: 
[14:48:56]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
WARN [2020-02-21 14:48:58.75]: Generating fastlane environment output, this might take a few seconds...
DEBUG [2020-02-21 14:48:59.12]: Checking if there are any plugins that should be loaded...
WARN [2020-02-21 14:48:59.20]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
INFO [2020-02-21 14:48:59.20]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅
</pre>
</details>

**Comment by janpio** [comment]
Can you please update your fastlane to the recent version?
Also, you did not post the full output you are getting or the code you are actually running. Right now we have no possibility to understand what you are doing.

**Comment by saroar** [comment]
// 🍏  fastlane update_fastlane
Password:
Updating installed gems
Updating fastlane
Gems updated: signet
Gems already up-to-date: fastlane
ERROR:  Error installing fastlane:
	signet requires Ruby version >= 2.4.0.
Cleaning up installed gems...
Clean Up Complete
👨  💻  (master) AddaIOS
// 🍏  ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]

i try but it version still same > not changing :(

**Comment by saroar** [comment]
fixed update issue
