### ISSUE TITLE
Frameit title color is grey not the color I chose

### ISSUE THREAD

**Issue by SRowley90** [fastlane/fastlane#16067]
### New Issue Checklist

- [ x] Updated fastlane to the latest version
- [ x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When running frameit the text colour is not respected and is a light shade of grey. Full Framefile.json can be seen below which should result in a pinky/purple colour on the text.

```
{
  "device_frame_version": "latest",
  "default": {
    "padding": 50,
    "show_complete_frame" : true,
    "background": "./background.jpg",
    "title": {
        "color": "#830154"
    }
  },
  "data": [
    {
      "filter": "0JourneyList"
    },
    {
      "filter": "1JourneyDetail"
    },
    {
      "filter": "2ComponentDetail"
    },
    {
      "filter": "3EnquiriesList"
    },
    {
      "filter": "4Payments"
    },
    {
      "filter": "5Contact"
    }
  ]
}
```

##### Command executed
fastlane frameit

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
Sams-MacBook-Pro:screenshots sam.rowley$ fastlane frameit
[✔] 🚀 
[15:54:22]: fastlane detected a Gemfile in the current directory
[15:54:22]: However, it seems like you didn't use `bundle exec`
[15:54:22]: To launch fastlane faster, please use
[15:54:22]: 
[15:54:22]: $ bundle exec fastlane frameit
[15:54:22]: 
[15:54:22]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[15:54:23]: Using device frames version 'latest'
[⠇] Framing screenshot './en-GB/iPhone 8-4Payments.png' composite: invalid profile length `/var/folders/zn/84q6_g9j15d1pjm2ddkhfxjjyn0kws/T/mini_magick20200221-56915-1qffjeg.png' @ warning/png.c/MagickPNGWarningHandler/1748.
[⠋] Framing screenshot './en-GB/iPhone 8-4Payments.png' convert: invalid profile length `/var/folders/zn/84q6_g9j15d1pjm2ddkhfxjjyn0kws/T/mini_magick20200221-56915-vrbv48.png' @ warning/png.c/MagickPNGWarningHandler/1748.
[✔] Framing screenshot './en-GB/iPhone 8-4Payments.png' 
[15:54:28]: Added frame: '/path/to/image/screenshots/en-GB/iPhone 8-4Payments_framed.png'
[⠧] Framing screenshot './en-GB/iPhone 8-0JourneyList.png' composite: invalid profile length `/var/folders/zn/84q6_g9j15d1pjm2ddkhfxjjyn0kws/T/mini_magick20200221-56915-dbis1x.png' @ warning/png.c/MagickPNGWarningHandler/1748.
[⠏] Framing screenshot './en-GB/iPhone 8-0JourneyList.png' convert: invalid profile length `/var/folders/zn/84q6_g9j15d1pjm2ddkhfxjjyn0kws/T/mini_magick20200221-56915-y06npc.png' @ warning/png.c/MagickPNGWarningHandler/1748.
[✔] Framing screenshot './en-GB/iPhone 8-0JourneyList.png' 
[15:54:34]: Added frame: '/path/to/image/screenshots/en-GB/iPhone 8-0JourneyList_framed.png'
[⠏] Framing screenshot './en-GB/iPhone 8-5Contact.png' composite: invalid profile length `/var/folders/zn/84q6_g9j15d1pjm2ddkhfxjjyn0kws/T/mini_magick20200221-56915-1adbg71.png' @ warning/png.c/MagickPNGWarningHandler/1748.
[⠙] Framing screenshot './en-GB/iPhone 8-5Contact.png' convert: invalid profile length `/var/folders/zn/84q6_g9j15d1pjm2ddkhfxjjyn0kws/T/mini_magick20200221-56915-1t1duwp.png' @ warning/png.c/MagickPNGWarningHandler/1748.
[✔] Framing screenshot './en-GB/iPhone 8-5Contact.png' 
[15:54:39]: Added frame: 'screenshots/en-GB/iPhone 8-5Contact_framed.png'
[⠋] Framing screenshot './en-GB/iPhone 8-2ComponentDetail.png' composite: invalid profile length `/var/folders/zn/84q6_g9j15d1pjm2ddkhfxjjyn0kws/T/mini_magick20200221-56915-vmzd4d.png' @ warning/png.c/MagickPNGWarningHandler/1748.
[⠹] Framing screenshot './en-GB/iPhone 8-2ComponentDetail.png' convert: invalid profile length `/var/folders/zn/84q6_g9j15d1pjm2ddkhfxjjyn0kws/T/mini_magick20200221-56915-by0e4k.png' @ warning/png.c/MagickPNGWarningHandler/1748.
[✔] Framing screenshot './en-GB/iPhone 8-2ComponentDetail.png' 
[15:54:45]: Added frame: '/path/to/image/screenshots/en-GB/iPhone 8-2ComponentDetail_framed.png'
[⠏] Framing screenshot './en-GB/iPhone 8-3EnquiriesList.png' composite: invalid profile length `/var/folders/zn/84q6_g9j15d1pjm2ddkhfxjjyn0kws/T/mini_magick20200221-56915-1fy6gxt.png' @ warning/png.c/MagickPNGWarningHandler/1748.
[⠋] Framing screenshot './en-GB/iPhone 8-3EnquiriesList.png' convert: invalid profile length `/var/folders/zn/84q6_g9j15d1pjm2ddkhfxjjyn0kws/T/mini_magick20200221-56915-1hmdihu.png' @ warning/png.c/MagickPNGWarningHandler/1748.
[✔] Framing screenshot './en-GB/iPhone 8-3EnquiriesList.png' 
[15:54:50]: Added frame: '/path/to/image/screenshots/en-GB/iPhone 8-3EnquiriesList_framed.png'
[⠴] Framing screenshot './en-GB/iPhone 8-1JourneyDetail.png' composite: invalid profile length `/var/folders/zn/84q6_g9j15d1pjm2ddkhfxjjyn0kws/T/mini_magick20200221-56915-5f8axq.png' @ warning/png.c/MagickPNGWarningHandler/1748.
[⠧] Framing screenshot './en-GB/iPhone 8-1JourneyDetail.png' convert: invalid profile length `/var/folders/zn/84q6_g9j15d1pjm2ddkhfxjjyn0kws/T/mini_magick20200221-56915-14whgo7.png' @ warning/png.c/MagickPNGWarningHandler/1748.
[✔] Framing screenshot './en-GB/iPhone 8-1JourneyDetail.png' 
[15:54:56]: Added frame: '/path/to/image/screenshots/en-GB/iPhone 8-1JourneyDetail_framed.png'
 </pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15                                       |
| Ruby                        | 2.5.5                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.15 (19A582a)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.5/2.5.5_1/lib      |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.142.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status      |
| ------------------------- | ------- | ------------------ |
| fastlane-plugin-appcenter | 1.2.0   | 🚫 Update available |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.72.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday                   | 0.17.3       |
| faraday_middleware        | 0.13.1       |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 2.1.4        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| signet                    | 0.12.0       |
| googleauth                | 0.10.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| unicode-display_width     | 1.6.1        |
| plist                     | 3.5.0        |
| addressable               | 2.7.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| fastimage                 | 2.1.7        |
| json                      | 2.3.0        |
| dotenv                    | 2.7.5        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| multi_json                | 1.14.1       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| digest-crc                | 0.4.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| fastlane-plugin-appcenter | 1.2.0        |
</details>

*generated on:* **2020-02-21**
</details>

**Comment by janpio** [comment]
Does it work if you do not supply empty `filters`?

**Comment by SRowley90** [comment]
Just coming back to this after the weekend and I have it working now. I'm not sure exactly what the issue is but it's something to do with the background.jpg file supplied. I reverted to using the example one from the MindNode example and the text is coloured.

**Comment by janpio** [comment]
Great!

If you figure out what is going on, feel free to open a new issue. These kinds of side effects are of course not what we want really, so knowing about it would help.

**Comment by EricWiener** [comment]
I had the exact same issue when using a white jpg. When I switched to the one from the example it worked. I'll open a new issue once I get things figured out.

**Comment by mibzman** [comment]
I can confirm that both #FFFFFF and #FFFEFF cause the text to break. FFFFFE, FFFFEF, FFEFFF, FEFFFF, and EFFFFF work fine.

I've found that #FEFFFF is close enough to white for my purposes.

**Comment by janpio** [comment]
Wow interesting find. Can you please open an issue about this that links back to here?
