### ISSUE TITLE
Can't run Fastlane plugin from another Ruby file (class)

### ISSUE THREAD

**Issue by anass-at** [fastlane/fastlane#16060]
I'm trying to call **Fastlane** plugins from another ruby (class) file  included inside **Fastfile** with **require_relative** 
but it results the below error:
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
NoMethodError: [!] undefined method `build_app' for Fastlane::Actions:Module

**Comment by anass-at** [comment]
how this can help , please explanation.

> It seems like you have not included the output of `fastlane env`
> To make it easier for us help you resolve this issue, please update the issue to include the output of `fastlane env` 👍

how this can help , please explanation.

**Comment by anass-at** [comment]
I have no issue with Fastlane env , Im just asking how to call plugins in another file.

**Comment by anass-at** [comment]
> It seems like you have not included the output of `fastlane env`
> To make it easier for us help you resolve this issue, please update the issue to include the output of `fastlane env` 👍

I have no issue with Fastlane env , Im just asking how to call plugins in another file.

**Comment by janpio** [comment]
Please do not delete the issue template. We need the information to be able to help you.

What code are you running?
What version of Fastlane? Which plugin? 
Which version of the plugin?
