### ISSUE TITLE
Frameit title_min_height has incorrect behaviour

### ISSUE THREAD

**Issue by okalentiev** [fastlane/fastlane#16066]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

According to documentation `title_min_height` parameter specifies minimum height for the title. And when specified as a percentage, it calculates it as the percentage of height.

Looking at [this code](https://github.com/fastlane/fastlane/blob/master/frameit/lib/frameit/editor.rb#L217) though, it uses a minimum of width and height and then uses that to calculate the minimum height. This results in weight being used every time, therefore, causing the `title_min_height` to be the same for every device. In my case, it causes height to be the same for iPhone 8 and 11 Max screenshots. I tested this with different percentages and the height from the top of the screen to the frame always stays the same. This seems wrong to me because the final height of the screenshots is different per device.

_Notice same height (311) on both screenshots._
<img width="1132" alt="75040024-318a0300-54ba-11ea-845a-aa0392334d86" src="https://user-images.githubusercontent.com/4539292/75040484-07851080-54bb-11ea-817f-7f28ed40160b.png">
<img width="712" alt="75039511-22ef1c00-54b9-11ea-9b42-08b896f2d0d9" src="https://user-images.githubusercontent.com/4539292/75040492-09e76a80-54bb-11ea-9d72-1bc0e70b141f.png">

I might be misunderstanding something, but if someone can confirm that this is the issue I can fix it. 

Also, I believe that this issue is partly related to this one: https://github.com/fastlane/fastlane/issues/11160

##### Command executed
`bundle exec frameit`

**Framefile.json:**
```
{
    "device_frame_version": "latest",
    "default": {
      "title": {
        "color": "#FFFFFF",
        "font": "../../Resources/fonts/BrownPro-Bold.otf"
      },
      "background": "./background.jpg",
      "padding": 50,
      "show_complete_frame": true,
      "stack_title" : false,
      "frame": "WHITE",
      "font_scale_factor": 0.09,
      "title_min_height": "25%"
    },
  
    "data": [
      {
        "filter": "01"
      },
      {
        "filter": "02"
      },
      {
        "filter": "03"
      },
      {
        "filter": "04"
      }
    ]
  }
```

**Comment by janpio** [comment]
That is possible. Really no one understand the full feature set and configuration options of frameit and what side effects they might have, so this very well might be unintentional or a bug.

**Comment by asketsystem** [comment]
Sent from Yahoo Mail for iPhone


On Friday, February 21, 2020, 2:13 PM, fastlane bot <notifications@github.com> wrote:


It seems like you have not included the output of fastlane env
To make it easier for us help you resolve this issue, please update the issue to include the output of fastlane env 👍

**Comment by asketsystem** [comment]
Sent from Yahoo Mail for iPhone


On Saturday, February 22, 2020, 3:28 PM, asketsystem1@gmail.com wrote:




Sent from Yahoo Mail for iPhone


On Friday, February 21, 2020, 2:13 PM, fastlane bot <notifications@github.com> wrote:


It seems like you have not included the output of fastlane env
To make it easier for us help you resolve this issue, please update the issue to include the output of fastlane env 👍

**Comment by okalentiev** [comment]
> If you take "percentage of the height" as "percentage of the total image height", isn't your result not exactly what you would expect?

Not really. The height of the iPhone 8 Plus and iPhone 11 Pro Max is different, but the `title_min_height` persists the same.

The screenshot sizes are _1242 x 2208_ for 8 Plus and _1242 x 2688_ for 11 Pro Max. If I specify `title_min_height` in percentage, I expect frameit to use _2208_ and _2688_ as the numbers to take the percentage from. Currently, the code uses width. _25% of 1242 = 310.5_ is what you see on my screenshots.

**Comment by janpio** [comment]
Oh right, the "percentage of the total image height" should actually be different for these as the "total image height" depends on the device. Good point. Hmm...

**Comment by okalentiev** [comment]
Yes, looks like an issue to me and can be easily fixed, but would be nice to have a bit more confidence. It might be a breaking change if some implementations depend on current behaviour.

@bvirlet I noticed that you made the original change in PR https://github.com/fastlane/fastlane/pull/11014, maybe you can help us understand the behaviour? Any input would be much appreciated 🙌

**Comment by bvirlet** [comment]
@okalentiev I believe you are correct. It seems that this logic from `title_min_height` was copied over from the `scale_padding` method below, but it doesn't make sense. While the padding needs to take in account both the width and the height, `title_min_height` only depends on the height. Can you submit a PR?

`frameit` could really use some unit tests (that would require splitting some logic out of the editor into some kind of `layout_manager`, and it could use regression tests as well…) I have found the time to start working on any of these yet.
