### ISSUE TITLE
undefined method `strip' for nil:NilClass

### ISSUE THREAD

**Issue by sunglimp** [fastlane/fastlane#16076]
fastlane env
[✔] 🚀
[15:06:01]: Generating fastlane environment output, this might take a few seconds...
[15:06:01]: undefined method `strip' for nil:NilClass
[15:06:01]: Error rendering markdown table using the following text:
[15:06:01]: | Key | Value |
| fastlane | 2.142.0 |
| OS | Linux staging.birdapps.org 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux |
| Ruby | 2.6.3 |
| Bundler? | true |
| Git | git version 1.8.3.1 |
| Installation Source | /usr/local/rvm/gems/ruby-2.6.3/bin/fastlane |
| Host | \S
Kernel \r on an \m Linux staging.birdapps.org 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux (3.10.0-693.2.2.el7.x86_64) |
| Ruby Lib Dir | /usr/local/rvm/rubies/ruby-2.6.3/lib |
| OpenSSL Version | OpenSSL 1.0.2k  26 Jan 2017 |
| Is contained | false |
| Is homebrew | false |
| Is installed via Fabric.app | false |
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key | Value |
| fastlane | 2.142.0 |
| OS | Linux staging.birdapps.org 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux |
| Ruby | 2.6.3 |
| Bundler? | true |
| Git | git version 1.8.3.1 |
| Installation Source | /usr/local/rvm/gems/ruby-2.6.3/bin/fastlane |
| Host | \S
Kernel \r on an \m Linux staging.birdapps.org 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux (3.10.0-693.2.2.el7.x86_64) |
| Ruby Lib Dir | /usr/local/rvm/rubies/ruby-2.6.3/lib |
| OpenSSL Version | OpenSSL 1.0.2k  26 Jan 2017 |
| Is contained | false |
| Is homebrew | false |
| Is installed via Fabric.app | false |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_IN:en    | 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.142.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.17.3       |
| etc                       | 1.0.1        |
| forwardable               | 1.2.0        |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.72.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.17.3       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.0.1        |
| signet                    | 0.12.0       |
| googleauth                | 0.10.0       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.0        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.25.1       |
| json                      | 2.1.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.1        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2020-02-25**
</details>
[15:06:02]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[15:06:02]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue

**Comment by max-ott** [comment]
Hi there, not sure what the issue is. Could you please follow our guidelines for reporting problems and include all required information?

**Comment by jalone87** [comment]
Reproduced also in Fastlane 2.143.0, ruby 2.3.0
