### ISSUE TITLE
Reconsider default value for gym skip_package_pkg

### ISSUE THREAD

**Issue by keeshux** [fastlane/fastlane#16073]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: `2.141.0`
- Last working version: `2.140.0` (guess)

### Regression Description

The introduction of #12195 in 2.141.0 broke my existing setup for deploying "Development" macOS builds.

`gym` failed with a highly misleading "Archive Invalid" error message. By looking at the .rb files, I learned that `gym` was failing at `pkg_path` here (I didn't need a .pkg):

https://github.com/fastlane/fastlane/blob/5f50d3c74aebf0953bf53d3be6db4cf472fa6a8f/gym/lib/gym/generators/package_command_generator_xcode7.rb#L102

So I set `skip_package_pkg true` in `Gymfile` (default is `false`) and the issue went away.

I therefore wonder if it makes sense to default to `skip_package_pkg true` instead, if anything for backwards compatibility.

Output omitted because the overall picture should be clear.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
[00:04:19]: ▸ -----------------------------------------
[00:04:19]: $ /usr/bin/xcrun /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/cn/wkjj4p693v50qjwgwj2c234r0000gn/T/gym_config20200227-42837-kmpohq.plist' -archivePath /Users/keeshux/Library/Developer/Xcode/Archives/2020-02-27/Passepartout\ 2020-02-27\ 00.02.52.xcarchive -exportPath '/var/folders/cn/wkjj4p693v50qjwgwj2c234r0000gn/T/gym_output20200227-42837-mwqb5j' 
[00:04:27]: The generated archive is invalid, this can have various reasons:
[00:04:27]: Usually it's caused by the `Skip Install` option in Xcode, set it to `NO`
[00:04:27]: For more information visit https://developer.apple.com/library/ios/technotes/tn2215/_index.html
[00:04:27]: Also, make sure to have a valid code signing identity and provisioning profile installed
[00:04:27]: Follow this guide to setup code signing https://docs.fastlane.tools/codesigning/GettingStarted/
[00:04:27]: If your intention was only to export an ipa be sure to provide a valid archive at the archive path.
[00:04:27]: This error might also happen if your workspace/project file is not in the root directory of your project.
[00:04:27]: To workaround that issue, you can wrap your calls to gym with
[00:04:27]: `Dir.chdir('../path/to/dir/containing/proj') do`
[00:04:27]: For an example you can check out
[00:04:27]: https://github.com/artsy/emission-nebula/commit/44fe51a7fea8f7d52f0f77d6c3084827fe5dd59e
+------------------+-----------------------------+
|                  Lane Context                  |
+------------------+-----------------------------+
| DEFAULT_PLATFORM | mac                         |
| ENVIRONMENT      | secret-codesign,dev-archive |
| PLATFORM_NAME    | mac                         |
| LANE_NAME        | mac create_archive          |
| BUILD_NUMBER     | 477                         |
+------------------+-----------------------------+
[00:04:27]: Archive invalid

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | default_platform       | 0           |
| 2    | Switch to mac          | 0           |
|      | prepare_archive lane   |             |
| 3    | cocoapods              | 2           |
| 4    | get_build_number       | 0           |
| 5    | number_of_commits      | 0           |
| 6    | increment_build_numbe  | 0           |
|      | r                      |             |
| �   | gym                    | 100         |
+------+------------------------+-------------+

[00:04:27]: fastlane finished with errors
</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.3                                     |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.20.0                          |
| Installation Source         | /usr/local/lib/ruby/gems/2.6.0/bin/fastlane |
| Host                        | Mac OS X 10.15.3 (19D76)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.6.3/lib            |
| OpenSSL Version             | OpenSSL 1.0.2r  26 Feb 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.3.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)

import("../Submodules/fastlane-ci-templates/include/Fastfile.include")

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.algoritmico.macos.Passepartout") # The bundle identifier of your app


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.142.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-appcenter | 1.8.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 2.0.2        |
| CFPropertyList            | 3.0.2        |
| concurrent-ruby           | 1.1.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.13.0       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.11.1     |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| httpclient                | 2.8.3        |
| json                      | 2.3.0        |
| algoliasearch             | 1.27.1       |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.8.4        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.3.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.4.1        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| cocoapods                 | 1.8.4        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.72.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.17.3       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.0.1        |
| signet                    | 0.12.0       |
| googleauth                | 0.10.0       |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.0        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.25.1       |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.1        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-appcenter | 1.8.0        |
</details>

*generated on:* **2020-02-24**
</details>

**Comment by joshdholtz** [comment]
@keeshux Hey! I appreciate you bringing this up 😊 And my apologies for the issue 😔 I thought I called this out in the release notes for `2.140.0` but maybe I didn't call it out good enough why we decided to go that why and that it would be a breaking change 😬

The reason we chose to go with `false` was so that `gym`'s defaults build for both iOS and macOS were similar in how they would package the app for App Store distribution. It made since (at that time) to go with `false`.

I think I would prefer to keep it as `false` but maybe document things a little better? Would love to hear your thoughts!

**Comment by keeshux** [comment]
@joshdholtz first off thanks guys for such a bless as fastlane.

I believe that the best solution would be printing an extra message in those cases where `pkg_path` is nil, but `skip_package_pkg` is not set in the `Gymfile`. Basically suggest to enable the flag rather than leaving the developer figuring out. That would be a harmless cue/fix for those like me who have fastlane updates automated.

If you find this solution adequate, I may draft a quick PR.
