### ISSUE TITLE
supply - Could not find release for version code to update changelog

### ISSUE THREAD

**Issue by cunneen** [fastlane/fastlane#16071]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Supply was previously working to upload my APK with Fastlane v2.135.0 ; after upgrading to v2.142.0 it ceased working with the error:

```
Could not find release for version code '1128299' to update changelog
```

After downgrading to v2.135.0 it worked again with the exact same command.

##### Command executed

```
$ fastlane supply app-release.apk --json_key Google\ Play\ Android.json --package_name my.package.name --version_code 1128299 --version_name 4 --skip-upload-changelogs --release_status draft
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
$ fastlane supply app-release.apk --json_key Google\ Play\ Android.json --package_name my.package.name --version_code 1128299 --version_name 4 --skip-upload-changelogs --release_status draft
[✔] 🚀 
[23:26:31]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

+-------------------------+------------------------------------------------------------------------------------------------+
|                                                Summary for supply 2.142.0                                                |
+-------------------------+------------------------------------------------------------------------------------------------+
| json_key                | Google Play Android.json                                                                       |
| package_name            | my.package.name                                                                                |
| version_code            | 1128299                                                                                        |
| version_name            | 4                                                                                              |
| skip_upload_changelogs  | true                                                                                           |
| skip_upload_images      | true                                                                                           |
| release_status          | draft                                                                                          |
| track                   | production                                                                                     |
| metadata_path           | ./metadata                                                                                     |
| skip_upload_apk         | false                                                                                          |
| skip_upload_aab         | false                                                                                          |
| skip_upload_metadata    | false                                                                                          |
| skip_upload_screenshots | false                                                                                          |
| validate_only           | false                                                                                          |
| check_superseded_tracks | false                                                                                          |
| timeout                 | 300                                                                                            |
| deactivate_on_promote   | true                                                                                           |
+-------------------------+------------------------------------------------------------------------------------------------+

<b>[!] Could not find release for version code '1128299' to update changelog</b>
$ gem uninstall fastlane --all --executables
Successfully uninstalled fastlane-2.133.0
Successfully uninstalled fastlane-2.141.0
Removing bin-proxy
Removing fastlane
Successfully uninstalled fastlane-2.142.0

$ gem install fastlane --version 2.135.0 --no-document
Fetching: fastlane-2.135.0.gem (100%)
Successfully installed fastlane-2.135.0
1 gem installed

$ fastlane supply app-release.apk --json_key Google\ Play\ Android.json --package_name my.package.name --version_code 1128299 --version_name 4 --skip-upload-changelogs --release_status draft
[✔] 🚀 
[23:28:07]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

+-------------------------+------------------------------------------------------------------------------------------------+
|                                                Summary for supply 2.135.0                                                |
+-------------------------+------------------------------------------------------------------------------------------------+
| json_key                | Google Play Android.json                                                                       |
| package_name            | my.package.name                                                                                |
| version_code            | 1128299                                                                                        |
| version_name            | 4                                                                                              |
| skip_upload_changelogs  | true                                                                                           |
| skip_upload_images      | true                                                                                           |
| release_status          | draft                                                                                          |
| track                   | production                                                                                     |
| metadata_path           | ./metadata                                                                                     |
| skip_upload_apk         | false                                                                                          |
| skip_upload_aab         | false                                                                                          |
| skip_upload_metadata    | false                                                                                          |
| skip_upload_screenshots | false                                                                                          |
| validate_only           | false                                                                                          |
| check_superseded_tracks | false                                                                                          |
| timeout                 | 300                                                                                            |
| deactivate_on_promote   | true                                                                                           |
+-------------------------+------------------------------------------------------------------------------------------------+

[23:28:10]: Uploading all track and release changes to Google Play...
[23:28:12]: Successfully finished the upload to Google Play
[23:28:14]: Preparing to upload for language 'en-AU'...
[23:28:16]: Uploading screenshot ./metadata/en-AU/images/phoneScreenshots/E_android-4in-1080x1920-port.png...
[23:28:20]: Uploading screenshot ./metadata/en-AU/images/phoneScreenshots/E_android-4in-1920x1080-land.png...
[23:28:25]: Uploading screenshot ./metadata/en-AU/images/sevenInchScreenshots/E_android-7in-1280x800-land.png...
[23:28:28]: Uploading screenshot ./metadata/en-AU/images/sevenInchScreenshots/E_android-7in-800x1280-port.png...
[23:28:32]: Uploading screenshot ./metadata/en-AU/images/tenInchScreenshots/E_android-10in-1152x2048-port.png...
[23:28:35]: Uploading screenshot ./metadata/en-AU/images/tenInchScreenshots/E_android-10in-1280x720-land.png...
[23:28:39]: Uploading screenshot ./metadata/en-AU/images/tenInchScreenshots/E_android-10in-2048x1152-land.png...
[23:28:43]: Uploading screenshot ./metadata/en-AU/images/tenInchScreenshots/E_android-10in-720x1280-port.png...
[23:28:46]: Uploading all meta changes to Google Play...
[23:28:48]: Successfully finished the upload to Google Play

 </pre>
</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.5.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.24.1                          |
| Installation Source         | ~/.rbenv/versions/2.5.3/bin/fastlane        |
| Host                        | Mac OS X 10.14.6 (18G3020)                  |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.3/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.3.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.135.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.14.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.72.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday                   | 0.17.3       |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.7        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.1009  |
| mime-types                | 3.3.1        |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| emoji_regex               | 1.0.1        |
| json                      | 2.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.16.0       |
| openssl                   | 2.1.2        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
</details>

*generated on:* **2020-02-23**
</details>

**Comment by cunneen** [comment]
Actually although 2.135.0 appears to work, the APK doesn't seem to have made it to Google Play.

**Comment by Tokenyet** [comment]
`fastlane supply init` give me **version name** in `changelog`, like `1.0.5`, but I need to provide the **version code** to update changelog, like `24`. Is this the expected behavior for fastlane? I'm new on fastlane, and also confused on this issue.

**Comment by maxammann** [comment]
Same question here. Not sure how to configure the action:

```
[18:07:19]: ----------------------------------
[18:07:19]: --- Step: upload_to_play_store ---
[18:07:19]: ----------------------------------

+-------------------------+-----------------------------+
|              Summary for supply 2.143.0               |
+-------------------------+-----------------------------+
| version_code            | 100008                      |
| version_name            | 2020.3.2                    |
| track                   | alpha                       |
| json_key_data           | ********                    |
| package_name            | tuerantuer.app.integreat    |
| release_status          | completed                   |
| metadata_path           | ./fastlane/metadata/android |
| skip_upload_apk         | false                       |
| skip_upload_aab         | false                       |
| skip_upload_metadata    | false                       |
| skip_upload_changelogs  | false                       |
| skip_upload_images      | false                       |
| skip_upload_screenshots | false                       |
| validate_only           | false                       |
| check_superseded_tracks | false                       |
| timeout                 | 300                         |
| deactivate_on_promote   | true                        |
+-------------------------+-----------------------------+

+------------------+--------------------------+
|                Lane Context                 |
+------------------+--------------------------+
| DEFAULT_PLATFORM | android                  |
| PLATFORM_NAME    | android                  |
| LANE_NAME        | android playstore_upload |
+------------------+--------------------------+
[18:07:20]: Could not find release for version code '100008' to update changelog
```

**Comment by maxammann** [comment]
related? https://github.com/fastlane/fastlane/issues/15681
