### ISSUE TITLE
Is there any possibility to read environment variable from file at path?

### ISSUE THREAD

**Issue by igorkotkovets** [fastlane/fastlane#16081]
### Question Subject

I develop white label tvOS app and can  *gym* the app. But also I have multiple brands, which has their unique "app ID", "server url" and other parameters. Brands resources are in the separate git project, which connected as submodule to the tvOS project.
------------- Project.xcproject
------------- fastlane/Fastfile
---------------------- Appfile
------------- brands/development
--------------------- pilot
--------------------- demo

My plan was to define parameters in brands/pilot/.env.pilot , brands/development/.env.development, brands/demo/.env.demo files
But *.dotenv* plugin requires to locate these env files in the root folder of the project

So is there a possibility to load environment variables from path brands/pilot/.env.pilot ?

**Comment by Katsz** [comment]
You can either add symlink to your `.env` file, or mess with Fastfile like that:
```ruby
fastlane_require 'dotenv'

before_all do
  Dotenv.overload 'brands/pilot/.env.whatever'
end
```

Neither of above is the prettiest solution I would say, but 🤷‍♂

**Comment by igorkotkovets** [comment]
Thank you @Katsz . Elegant and simple.
But there is the issue that `.brands/brand/.env.whatever` path depends of selected brand. So it can be `.brands/development/.env`, `.brands/pilot/.env` or whatever.

So if I run build with `$ fastlane build_brand --env demo`
then I have to access variables from:
```
before_all do
  Dotenv.overload 'brands/demo/.env.demo'
end
```

Is there a method to read passed `--env` argument?

**Comment by Katsz** [comment]
`Fastlane::Actions.lane_context[Fastlane::Actions::SharedValues::ENVIRONMENT]` should do.
