### ISSUE TITLE
[deliver] submit_build, promote build to production: undefined method `select_build' for nil:NilClass

### ISSUE THREAD

**Issue by tipa** [fastlane/fastlane#16084]
### Issue Description
I am creating this issue because https://github.com/fastlane/fastlane/issues/13809 and https://github.com/fastlane/fastlane/issues/15029 still haven't been fixed. I am hitting this problem when using the "AppStorePromote" task in Azure pipelines. The build has previously been successfully uploaded and added to the TestTrack with the "AppStoreRelease" task

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
Successfully installed fastlane-2.142.0
Parsing documentation for fastlane-2.142.0
Installing ri documentation for fastlane-2.142.0
Done installing documentation for fastlane after 20 seconds
1 gem installed
/usr/local/opt/ruby/bin/gem update fastlane -i /Users/runner/.gem-cache
Updating installed gems
Nothing to update
fastlane deliver submit_build -u *** -a com.redacted --skip_binary_upload true --skip_metadata true --skip_screenshots true --automatic_release --force
/usr/local/lib/ruby/gems/2.7.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:14: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
[14:21:00]: Seems like launching fastlane takes a while - please run
[14:21:00]: 
[14:21:00]: $ [sudo] gem cleanup
[14:21:00]: 
[14:21:00]: to uninstall outdated gems and make fastlane launch faster
[14:21:00]: Alternatively it's recommended to start using a Gemfile to lock your dependencies
[14:21:00]: To get started with a Gemfile, run
[14:21:00]: 
[14:21:00]: $ bundle init
[14:21:00]: $ echo 'gem "fastlane"' >> Gemfile
[14:21:00]: $ bundle install
[14:21:00]: 
[14:21:00]: After creating the Gemfile and Gemfile.lock, commit those files into version control
[14:21:00]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[14:21:06]: Sending anonymous analytics information
[14:21:06]: Learn more at https://docs.fastlane.tools/#metrics
[14:21:06]: No personal or sensitive data is sent.
[14:21:06]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
[14:21:06]: Login to App Store Connect (***)
/usr/local/lib/ruby/gems/2.7.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:14: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/usr/local/lib/ruby/gems/2.7.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:14: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
[14:21:07]: Login successful

+--------------------------------------+-----------------------+
|                   deliver 2.142.0 Summary                    |
+--------------------------------------+-----------------------+
| username                             | *** |
| app_identifier                       | com.redacted            |
| skip_binary_upload                   | true                  |
| skip_metadata                        | true                  |
| skip_screenshots                     | true                  |
| automatic_release                    | true                  |
| force                                | true                  |
| submit_for_review                    | true                  |
| build_number                         | latest                |
| screenshots_path                     | ./screenshots         |
| metadata_path                        | ./metadata            |
| platform                             | ios                   |
| edit_live                            | false                 |
| use_live_version                     | false                 |
| skip_app_version_update              | false                 |
| overwrite_screenshots                | false                 |
| reject_if_possible                   | false                 |
| phased_release                       | false                 |
| reset_ratings                        | false                 |
| run_precheck_before_submit           | true                  |
| precheck_default_rule_level          | warn                  |
| individual_metadata_items            | []                    |
| ignore_language_directory_validation | false                 |
| precheck_include_in_app_purchases    | true                  |
+--------------------------------------+-----------------------+

[14:21:08]: Running precheck before submitting to review, if you'd like to disable this check you can set run_precheck_before_submit to false
[14:21:08]: Making sure we pass precheck 👮‍♀️ 👮 before we submit  🛫

+--------------------------+-----------------------+
|           Summary for precheck 2.142.0           |
+--------------------------+-----------------------+
| default_rule_level       | warn                  |
| include_in_app_purchases | true                  |
| app_identifier           | com.redacted            |
| username                 | *** |
+--------------------------+-----------------------+

[14:21:08]: Checking app for precheck rule violations
[14:21:11]: Reading in-app purchases. If you have a lot, this might take a while
[14:21:11]: You can disable IAP checking by setting the `include_in_app_purchases` flag to `false`
[14:21:11]: Done reading in-app purchases
[14:21:11]: ✅  Passed: No negative  sentiment
[14:21:11]: ✅  Passed: No placeholder text
[14:21:11]: ✅  Passed: No mentioning  competitors
[14:21:11]: ✅  Passed: No future functionality promises
[14:21:11]: ✅  Passed: No words indicating test content
[14:21:11]: ✅  Passed: No curse words
[14:21:11]: ✅  Passed: No words indicating your IAP is free
[14:21:11]: 😵  Failed: Incorrect, or missing copyright date-> using a copyright date that is any different from this current year, or missing a date
[14:21:15]: ✅  Passed: No broken urls
+-----------+----------------+
|     Potential problems     |
+-----------+----------------+
| Field     | Failure reason |
+-----------+----------------+
| copyright | missing: 2020  |
+-----------+----------------+
[14:21:15]: precheck 👮‍♀️ 👮  found one or more potential metadata problems, but this won't prevent fastlane from completing 👍
[14:21:15]: Selecting the latest build...
[14:21:17]: Selecting build  (1.0.27)...

Looking for related GitHub issues on fastlane/fastlane...

➡️  [pilot] undefined method `id' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/15138 [closed] 47 💬
    22 hours ago

➡️  [deliver] submit_build, promote build to production: undefined method `select_build' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/13809 [closed] 36 💬
    4 weeks ago

➡️  Promoting iOS app to App Store throws NoMethodError: [!] undefined method `candidate_builds' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/15029 [closed] 7 💬
    28 Oct 2019

and 3 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60select_build%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/runner/.gem-cache/gems/fastlane-2.142.0/deliver/lib/deliver/submit_for_review.rb:49:in `select_build': \e[31m[!] undefined method `select_build' for nil:NilClass\e[0m (NoMethodError)
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/deliver/lib/deliver/submit_for_review.rb:7:in `submit!'
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/deliver/lib/deliver/runner.rb:183:in `submit_for_review'
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/deliver/lib/deliver/runner.rb:50:in `run'
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/deliver/lib/deliver/commands_generator.rb:94:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/deliver/lib/deliver/commands_generator.rb:182:in `run'
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `load'
	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `<main>'
/Users/runner/.gem-cache/gems/fastlane-2.142.0/deliver/lib/deliver/submit_for_review.rb:49:in `select_build': undefined method `select_build' for nil:NilClass (NoMethodError)
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/deliver/lib/deliver/submit_for_review.rb:7:in `submit!'
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/deliver/lib/deliver/runner.rb:183:in `submit_for_review'
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/deliver/lib/deliver/runner.rb:50:in `run'
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/deliver/lib/deliver/commands_generator.rb:94:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/deliver/lib/deliver/commands_generator.rb:182:in `run'
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `load'
	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `<main>'
##[error]Error: fastlane failed with return code: 1
</pre>
</details>

#

<details>
  <pre>Successfully installed fastlane-2.142.0
Parsing documentation for fastlane-2.142.0
Installing ri documentation for fastlane-2.142.0
Done installing documentation for fastlane after 21 seconds
1 gem installed
/usr/local/opt/ruby/bin/gem update fastlane -i /Users/runner/.gem-cache
Updating installed gems
Nothing to update
fastlane deliver submit_build -u *** -a com.redacted -n 1.0.27 --skip_binary_upload true --skip_metadata true --skip_screenshots true --automatic_release --force
/usr/local/lib/ruby/gems/2.7.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:14: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
[14:58:02]: Seems like launching fastlane takes a while - please run
[14:58:02]: 
[14:58:02]: $ [sudo] gem cleanup
[14:58:02]: 
[14:58:02]: to uninstall outdated gems and make fastlane launch faster
[14:58:02]: Alternatively it's recommended to start using a Gemfile to lock your dependencies
[14:58:02]: To get started with a Gemfile, run
[14:58:02]: 
[14:58:02]: $ bundle init
[14:58:02]: $ echo 'gem "fastlane"' >> Gemfile
[14:58:02]: $ bundle install
[14:58:02]: 
[14:58:02]: After creating the Gemfile and Gemfile.lock, commit those files into version control
[14:58:02]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[14:58:09]: Sending anonymous analytics information
[14:58:09]: Learn more at https://docs.fastlane.tools/#metrics
[14:58:09]: No personal or sensitive data is sent.
[14:58:09]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
[14:58:09]: Login to App Store Connect (***)
/usr/local/lib/ruby/gems/2.7.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:14: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/usr/local/lib/ruby/gems/2.7.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:14: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
[14:58:12]: Login successful

+--------------------------------------+-----------------------+
|                   deliver 2.142.0 Summary                    |
+--------------------------------------+-----------------------+
| username                             | *** |
| app_identifier                       | com.redacted            |
| build_number                         | 1.0.27                |
| skip_binary_upload                   | true                  |
| skip_metadata                        | true                  |
| skip_screenshots                     | true                  |
| automatic_release                    | true                  |
| force                                | true                  |
| submit_for_review                    | true                  |
| screenshots_path                     | ./screenshots         |
| metadata_path                        | ./metadata            |
| platform                             | ios                   |
| edit_live                            | false                 |
| use_live_version                     | false                 |
| skip_app_version_update              | false                 |
| overwrite_screenshots                | false                 |
| reject_if_possible                   | false                 |
| phased_release                       | false                 |
| reset_ratings                        | false                 |
| run_precheck_before_submit           | true                  |
| precheck_default_rule_level          | warn                  |
| individual_metadata_items            | []                    |
| ignore_language_directory_validation | false                 |
| precheck_include_in_app_purchases    | true                  |
+--------------------------------------+-----------------------+

[14:58:13]: Running precheck before submitting to review, if you'd like to disable this check you can set run_precheck_before_submit to false
[14:58:13]: Making sure we pass precheck 👮‍♀️ 👮 before we submit  🛫

+--------------------------+-----------------------+
|           Summary for precheck 2.142.0           |
+--------------------------+-----------------------+
| default_rule_level       | warn                  |
| include_in_app_purchases | true                  |
| app_identifier           | com.redacted            |
| username                 | *** |
+--------------------------+-----------------------+

[14:58:13]: Checking app for precheck rule violations
[14:58:18]: Reading in-app purchases. If you have a lot, this might take a while
[14:58:18]: You can disable IAP checking by setting the `include_in_app_purchases` flag to `false`
[14:58:18]: Done reading in-app purchases
[14:58:19]: ✅  Passed: No negative  sentiment
[14:58:19]: ✅  Passed: No placeholder text
[14:58:19]: ✅  Passed: No mentioning  competitors
[14:58:19]: ✅  Passed: No future functionality promises
[14:58:19]: ✅  Passed: No words indicating test content
[14:58:19]: ✅  Passed: No curse words
[14:58:19]: ✅  Passed: No words indicating your IAP is free
[14:58:19]: ✅  Passed: Incorrect, or missing copyright date
[14:58:21]: ✅  Passed: No broken urls
[14:58:21]: precheck 👮‍♀️ 👮  finished without detecting any potential problems 🛫
[14:58:21]: Selecting existing build-number: 1.0.27

Looking for related GitHub issues on fastlane/fastlane...

➡️  [pilot] undefined method `id' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/15138 [closed] 47 💬
    22 hours ago

➡️  [deliver] submit_build, promote build to production: undefined method `select_build' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/13809 [closed] 36 💬
    4 weeks ago

➡️  Promoting iOS app to App Store throws NoMethodError: [!] undefined method `candidate_builds' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/15029 [closed] 7 💬
    28 Oct 2019

and 2 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60candidate_builds%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/runner/.gem-cache/gems/fastlane-2.142.0/deliver/lib/deliver/submit_for_review.rb:39:in `select_build': \e[31m[!] undefined method `candidate_builds' for nil:NilClass\e[0m (NoMethodError)
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/deliver/lib/deliver/submit_for_review.rb:7:in `submit!'
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/deliver/lib/deliver/runner.rb:183:in `submit_for_review'
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/deliver/lib/deliver/runner.rb:50:in `run'
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/deliver/lib/deliver/commands_generator.rb:94:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/deliver/lib/deliver/commands_generator.rb:182:in `run'
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `load'
	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `<main>'
/Users/runner/.gem-cache/gems/fastlane-2.142.0/deliver/lib/deliver/submit_for_review.rb:39:in `select_build': undefined method `candidate_builds' for nil:NilClass (NoMethodError)
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/deliver/lib/deliver/submit_for_review.rb:7:in `submit!'
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/deliver/lib/deliver/runner.rb:183:in `submit_for_review'
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/deliver/lib/deliver/runner.rb:50:in `run'
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/deliver/lib/deliver/commands_generator.rb:94:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/deliver/lib/deliver/commands_generator.rb:182:in `run'
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	from /Users/runner/.gem-cache/gems/fastlane-2.142.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `load'
	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `<main>'
##[error]Error: fastlane failed with return code: 1
</pre>
</details>

#

**Comment by max-ott** [comment]
Could you please post the latest `deliver` steps/commands you are using?

**Comment by tipa** [comment]
I think they are in the "Details" I posted, so
`fastlane deliver submit_build -u *** -a com.redacted --skip_binary_upload true --skip_metadata true --skip_screenshots true --automatic_release --force`
and 
`fastlane deliver submit_build -u *** -a com.redacted -n 1.0.27 --skip_binary_upload true --skip_metadata true --skip_screenshots true --automatic_release --force`

Or do you need some other info?
