### ISSUE TITLE
Cannot invite or reinvite, beta tester invitations api changed

### ISSUE THREAD

**Issue by typeoneerror** [fastlane/fastlane#16087]
🔑

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

The endpoint for beta invites looks to have changed.
Also it appears that invites in the app store aren't working either at the moment, so perhaps this is related. None of our internal testers can get an invite.

```
[16] pry(#<Spaceship::Playground>)> manjot
=> <Spaceship::TestFlight::Tester
	tester_id="3baf051a-093d-4324-95f6-5a9be7asdasd",
	email="someemail@gmail.com",
	first_name="Manjot",
	last_name="Khela",
	status="invited",
	status_mod_time=2020-02-26 19:57:27 +0000,
	latest_install_info={},
	latest_installed_date=nil,
	session_count=0,
	groups=["ITC.apps.tf.labels.internalTesters"]>
[17] pry(#<Spaceship::Playground>)> manjot.resend_invite(app_id: '1480071104')

Spaceship::UnexpectedResponse: <!DOCTYPE html><html lang="en">
<head>
<title></title>
<link rel="stylesheet" href="/styles/main.css">
<style type='text/css'>
    /*include ../../dist/styles/main.css*/
</style>
</head>

<body><div id="wrapper" class="j42">
<h2>Not Found</h2></div>
...
```

### Environment

<details>
  <pre>
### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.142.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                 | Version | Update-Status |
| ---------------------- | ------- | ------------- |
| fastlane-plugin-sentry | 1.6.0   | ✅ Up-To-Date  |
</pre>
</details>

**Comment by max-ott** [comment]
As far as I know this is already known and the documentation should get changed/removed for that part. This is now only possible through the `Connect::API` and I'm not sure if those endpoints are already implemented.

**Comment by userException** [comment]
Not sure if this is related to my issue bu asking here before creating a new one. I used a CSV file to import my testers to the iTunes account, with this command: fastlane pilot import. This was the output:

[12:38:10]: Successfully added tester mobiledev@ccc.net to app ABC Utility in group(s) QA;BETA
[12:38:15]: Successfully added tester betadev@ccc.com to app ABC Utility in group(s) BETA
[12:38:15]: Successfully imported 2 testers from ./testers.csv

At this point, it all seems good but when I list the testers using, fastlane pilot list, all I see are the anonymouse installs via public links:

|          All Testers (2)          |
+-----------+------+-------+--------+
| First     | Last | Email | Groups |
+-----------+------+-------+--------+
| Anonymous |      |       | CP-iOS |
| Anonymous |      |       | CP-iOS |
+-----------+------+-------+--------+
