### ISSUE TITLE
Your current version ($(MARKETING_VERSION)) does not respect the format A or A.B or A.B.C

### ISSUE THREAD

**Issue by yusuftor** [fastlane/fastlane#16093]
I keep getting the error `Your current version ($(MARKETING_VERSION)) does not respect the format A or A.B or A.B.C` when I run `increment_version_number` in my fastfile. I've seen other people on here have reported it, but I can't find a solution. My version number is in the format A.B.C so I don't get why it isn't working. This only stopped working when I had upgraded to Xcode 11. Please fix this!

**Comment by janpio** [comment]
Please don't delete the issue template, we need its information to be able to help you.
