### ISSUE TITLE
Operation Not Permitted: com.apple.siri.remembers

### ISSUE THREAD

**Issue by ryantstone** [fastlane/fastlane#16097]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I have a workspace that is currently a blank iOS application and a framework that is being developed before the application is started. I ran `fastlane init` and started setting up the `fastfile` but haven't gotten far due to application permissions.

##### Command executed
`fastlane scan` or ` bundle exec fastlane metadata_extractor_tests`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[09:45:51]: Could not read the "SUPPORTED_PLATFORMS" build setting, assuming that the project supports iOS only.
[09:45:52]: Found simulator "iPhone 8 (13.0)"

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
Traceback (most recent call last):
        14: from /Users/ryanstone/.rbenv/versions/2.6.3/bin/fastlane:23:in `<main>'
        13: from /Users/ryanstone/.rbenv/versions/2.6.3/bin/fastlane:23:in `load'
        12: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/bin/fastlane:23:in `<top (required)>'
        11: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
        10: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/scan/lib/scan/commands_generator.rb:15:in `start'
         9: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/scan/lib/scan/commands_generator.rb:75:in `run'
         8: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
         7: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
         6: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
         5: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
         4: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
         3: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/scan/lib/scan/commands_generator.rb:44:in `block (2 levels) in run'
         2: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/scan/lib/scan/manager.rb:12:in `work'
         1: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/scan/lib/scan/manager.rb:30:in `test_summary_filenames'
/Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/scan/lib/scan/manager.rb:30:in `[]': Operation not permitted - /Users/ryanstone/Library/Application Support/com.apple.siri.remembers (Errno::EPERM)
        14: from /Users/ryanstone/.rbenv/versions/2.6.3/bin/fastlane:23:in `<main>'
        13: from /Users/ryanstone/.rbenv/versions/2.6.3/bin/fastlane:23:in `load'
        12: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/bin/fastlane:23:in `<top (required)>'
        11: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
        10: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/scan/lib/scan/commands_generator.rb:15:in `start'
         9: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/scan/lib/scan/commands_generator.rb:75:in `run'
         8: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
         7: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
         6: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
         5: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
         4: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
         3: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/scan/lib/scan/commands_generator.rb:44:in `block (2 levels) in run'
         2: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/scan/lib/scan/manager.rb:12:in `work'
         1: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/scan/lib/scan/manager.rb:30:in `test_summary_filenames'
/Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/scan/lib/scan/manager.rb:30:in `[]': [!] Operation not permitted - /Users/ryanstone/Library/Application Support/com.apple.siri.remembers (Errno::EPERM)
</pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.1                                     |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0 (Apple Git-122)          |
| Installation Source         | ~/.rbenv/versions/2.6.3/bin/fastlane        |
| Host                        | Mac OS X 10.15.1 (19B88)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.3/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2s  28 May 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.0                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :metadata_extractor_tests do
    run_tests(workspace: "RecipeApp.xcworkspace",
      devices: ["iPhone 8 (13.0)"],
      scheme: "MetadataExtractorTests")
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.142.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.72.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| signet                    | 0.13.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.11.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.0        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| unicode-display_width     | 1.6.1        |
| addressable               | 2.7.0        |
| json                      | 2.3.0        |
| bundler                   | 2.1.4        |
| multi_json                | 1.14.1       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.5       |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>

*generated on:* **2020-02-29**
</details></pre>
</details>

**Comment by janpio** [comment]
Can you please share the full output you are getting? 
(Right now it doesn't give any indication what could be causing the error)

**Comment by ryantstone** [comment]
```
[20:41:51]: [33mfastlane detected a Gemfile in the current directory[0m
[20:41:51]: [33mHowever, it seems like you didn't use `bundle exec`[0m
[20:41:51]: [33mTo launch fastlane faster, please use[0m
[20:41:51]: 
[20:41:51]: [36m$ bundle exec fastlane scan[0m
[20:41:51]: 
[20:41:51]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
Select Scheme: 
1. MetadataExtractorTests
2. MetadataExtractor
?  
[20:41:59]: [33mResolving Swift Package Manager dependencies...[0m
[20:41:59]: [36m$ xcodebuild -resolvePackageDependencies -workspace ./RecipeApp.xcworkspace -scheme MetadataExtractorTests[0m
[20:42:00]: ▸ [35mResolve Package Graph[0m
[20:42:00]: ▸ [35mResolved source packages:[0m
[20:42:00]: ▸ [35m  Prelude: https://github.com/pointfreeco/swift-prelude @ master[0m
[20:42:00]: ▸ [35m  SwiftSoup: https://github.com/scinfu/SwiftSoup @ 2.3.0[0m
[20:42:00]: ▸ [35mresolved source packages: Prelude, SwiftSoup[0m
[20:42:00]: [36m$ xcodebuild -showBuildSettings -workspace ./RecipeApp.xcworkspace -scheme MetadataExtractorTests[0m
[20:42:01]: [33mCould not read the "SUPPORTED_PLATFORMS" build setting, assuming that the project supports iOS only.[0m
[20:42:02]: Found simulator "iPhone 8 (13.0)"

Looking for related GitHub issues on fastlane/fastlane...

➡️  [33mOperation Not Permitted: com.apple.siri.remembers[0m
    https://github.com/fastlane/fastlane/issues/16097 [[31mopen[0m] 1 💬
    9 hours ago

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
        14: from /Users/ryanstone/.rbenv/versions/2.6.3/bin/fastlane:23:in `<main>'
        13: from /Users/ryanstone/.rbenv/versions/2.6.3/bin/fastlane:23:in `load'
        12: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/bin/fastlane:23:in `<top (required)>'
        11: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
        10: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/scan/lib/scan/commands_generator.rb:15:in `start'
         9: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/scan/lib/scan/commands_generator.rb:75:in `run'
         8: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
         7: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
         6: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
         5: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
         4: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
         3: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/scan/lib/scan/commands_generator.rb:44:in `block (2 levels) in run'
         2: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/scan/lib/scan/manager.rb:12:in `work'
         1: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/scan/lib/scan/manager.rb:30:in `test_summary_filenames'
/Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/scan/lib/scan/manager.rb:30:in `[]': Operation not permitted - /Users/ryanstone/Library/Application Support/com.apple.siri.remembers (Errno::EPERM)
        14: from /Users/ryanstone/.rbenv/versions/2.6.3/bin/fastlane:23:in `<main>'
        13: from /Users/ryanstone/.rbenv/versions/2.6.3/bin/fastlane:23:in `load'
        12: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/bin/fastlane:23:in `<top (required)>'
        11: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
        10: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/scan/lib/scan/commands_generator.rb:15:in `start'
         9: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/scan/lib/scan/commands_generator.rb:75:in `run'
         8: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
         7: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
         6: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
         5: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
         4: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
         3: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/scan/lib/scan/commands_generator.rb:44:in `block (2 levels) in run'
         2: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/scan/lib/scan/manager.rb:12:in `work'
         1: from /Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/scan/lib/scan/manager.rb:30:in `test_summary_filenames'
/Users/ryanstone/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/scan/lib/scan/manager.rb:30:in `[]': [!] Operation not permitted - /Users/ryanstone/Library/Application Support/com.apple.siri.remembers (Errno::EPERM)
```

**Comment by pnc** [comment]
Hi @ryantstone! I just got this error too. I was trying to use `fastlane frameit` outside a project, so my current working directory was my home directory. The frameit code recurses all subdirectories to find a `Framefile.json` (which is… probably a bug[1]), and hits this protected Siri directory.

Can you share the output of `pwd` and `find . -name Framefile.json` from the same terminal you're using to run `fastlane`? You might be in your home directory unexpectedly, rather than the project directory.

[1] Fastlane folks: how do the other Fastlane tools restrict themselves to looking in a subdirectory called `fastlane` or so? Any chance you can link me to the code that does this so I can do an idiomatic patch?

**Comment by ryantstone** [comment]
> Can you share the output of `pwd` and `find . -name Framefile.json` from the same terminal you're using to run `fastlane`? You might be in your home directory unexpectedly, rather than the project directory.

Sorry for the delay in getting back this. I'm not using Frameit so there is no `Framefile.json` and the output of `pwd` is my application working directory in this case `/Users/ryanstone/Development/Recipe_App`

**Comment by kyubuns** [comment]
Hello @ryantstone and @pnc
Sorry on fastlane's github, but I'm having the same problem with other tools ( `Operation Not Permitted: com.apple.siri.members` )
Was there a time when you put the beta version of macOS in?
I think it's probably a System Integrity Protection bug that occurred there.
If you can find a solution, please let me know.
