### ISSUE TITLE
fastlane spaceauth UnauthorizedAccessError

### ISSUE THREAD

**Issue by itdaren** [fastlane/fastlane#16106]
Here is the log:
Please enter the 6 digit code:
131742
Requesting session...
Could not login to App Store Connect
Please check your credentials and try again.
This could be an issue with App Store Connect,
Please try unsetting the FASTLANE_SESSION environment variable
(if it is set) and re-run `fastlane spaceauth`

Exception type: Spaceship::UnauthorizedAccessError

**Comment by cnxzcxy** [comment]
plenty of accounts got same error since yesterday, and nothing usefull found so far

**Comment by cnxzcxy** [comment]
here are env content after fastlane upgrade

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                        |
| --------------------------- | -------------------------------------------- |
| OS                          | 10.14.6                                      |
| Ruby                        | 2.7.0                                        |
| Bundler?                    | false                                        |
| Git                         | git version 2.20.1 (Apple Git-117)           |
| Installation Source         | ~/.rvm/gems/ruby-2.7.0-preview1/bin/fastlane |
| Host                        | Mac OS X 10.14.6 (18G95)                     |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.7.0-preview1/lib        |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                  |
| Is contained                | false                                        |
| Is homebrew                 | false                                        |
| Is installed via Fabric.app | false                                        |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/  |
| Xcode Version               | 10.3                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.142.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 2.1.4        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.72.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.2.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.13.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.11.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.0        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>


*generated on:* **2020-03-02**
</details>

**Comment by janpio** [comment]
Probably similar to: ts-node app\load\load.ts --folder ..\database-schema-examples\postgres --db postgres://postgres:postgres@localhost:5432/public --template clean-load

**Comment by zhangyake** [comment]
error log:
```
Spaceship::UnauthorizedAccessError: Unauthorized Access
from /usr/local/rvm/gems/ruby-2.5.5/gems/fastlane-2.142.0/spaceship/lib/spaceship/client.rb:857:
in `block in send_request'
```

**Comment by max-ott** [comment]
Please provide exact steps to reproduce the issue with information on the Apple ID. 

I just tried the following with an Apple ID that has devices added to it. 

-> Enter Apple ID
-> Enter Password
-> Confirm login on trusted device
-> Enter PIN shown on trusted device
-> Login successful

**Comment by ajaykn** [comment]
I guess this is related to #16108

**Comment by cena-luo** [comment]
> Please provide exact steps to reproduce the issue with information on the Apple ID.
> 
> I just tried the following with an Apple ID that has devices added to it.
> 
> -> Enter Apple ID
> -> Enter Password
> -> Confirm login on trusted device
> -> Enter PIN shown on trusted device
> -> Login successful

Thank you very much, it help me ..
