### ISSUE TITLE
How set the parameters "price_tier" and  "reset_ratings" value?

### ISSUE THREAD

**Issue by yicel** [fastlane/fastlane#16104]
### Question Checklist

- [ *] Updated fastlane to the latest version
- [ *] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ *] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ *] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

#### Question Description
How set the metadata  parameters "price_tier" and  "reset_ratings" value? what's the  "reset_ratings"'s  value can be use? could you list them for me?  I'm not find the values list for the "reset_ratings"  in the docs.  thanks!

**Comment by janpio** [comment]
What action are you talking about?
