### ISSUE TITLE
Build app errors out because the system keychain is locked 

### ISSUE THREAD

**Issue by reshadf** [fastlane/fastlane#16107]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

when running build_app we get the following error when it is archiving ( in the CI Gitlab )
```
▸ Running script 'Fabric'
▸ Running script '[CP] Embed Pods Frameworks'
** ARCHIVE FAILED **


The following build commands failed:
	PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/app-macserver/Library/Developer/Xcode/DerivedData/app-fhlternuzcqwkmcjzzppzdkftzpt/Build/Intermediates.noindex/ArchiveIntermediates/app/IntermediateBuildFilesPath/ProActive.build/Release-iphoneos/ProActive.build/Script-183AF38B37D8F214753B6F75.sh
(1 failure)
 Exit status: 65
```

edit: opening the keychain might not have anything to do with it. Re-running the command a few times occasionally succeeds. 

I think this is because it tries to open the System keychain and it is not able to. This was not a problem before but we encountered this problem out of the blue a few months back. We managed to work around by manually unlocking but this is not workable, obviously. Is there something we are doing wrong or is this a bug? I feel like the latter since it occurred in ( I think ) a release a while back. Unfortunately, I am not sure if it was an OS  or Fastlane release. 

##### Command executed

```
lane :release do
  scan(derived_data_path: “~/Library/Developer/Xcode/DerivedData/“, build_for_testing: true, skip_build: true, scheme: "AppUITests")
  reset_simulators
  capture_ios_screenshots(
    launch_arguments: ["--uitesting"]
  )
  get_push_certificate
  sync_code_signing(type: "appstore", readonly: true)
  build_app(scheme: "App",
            workspace: "App.xcworkspace",
            include_bitcode: true)

  deliver(
    submit_for_review: true,
    force: true,
    screenshots_path: "./screenshots"
  )
end
```

### Environment

  <pre> <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.6.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.13.0                          |
| Installation Source         | ~/.rvm/gems/ruby-2.6.2/bin/fastlane         |
| Host                        | Mac OS X 10.14.6 (18G87)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.2/lib                |
| OpenSSL Version             | OpenSSL 1.1.1c  28 May 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.3.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later

lane :lint do

  swiftlint(
    mode: :lint,                            # SwiftLint mode: :lint (default) or :autocorrect
    executable: "Pods/SwiftLint/swiftlint", # The SwiftLint binary path (optional). Important if you've installed it via CocoaPods
    output_file: "swiftlint-result.html",   # The path of the output file (optional)
    config_file: ".swiftlint-ci.yml",       # The path of the configuration file (optional)
    ignore_exit_status: false               # Allow fastlane to continue even if SwiftLint returns a non-zero exit status
  )
end

lane :test do
  reset_simulators

  scan(
   scheme: "app",
   workspace: "app.xcworkspace",
   skip_build: true,
   only_testing: ["appTests"]
  )
  xcov(
    workspace: "app.xcworkspace",
    scheme: "app",
    output_directory: "xcov_report"
  )
end

lane :add_device do
      device_name = prompt(text: "Enter the device name: ")
      device_udid = prompt(text: "Enter the device UDID: ")
      device_hash = {}
      device_hash[device_name] = device_udid
      register_devices(
        devices: device_hash
      )
    refresh_profiles
  end

# A helper lane for refreshing provisioning profiles.
lane :refresh_profiles do
  match(
    app_identifier: ["nl.app.app.dev"],
    force_for_new_devices: true
 )
end

lane :devAPN do
  get_push_certificate(
  force: false, # create a new profile, even if the old one is still valid
  app_identifier: "nl.app.app.dev", # optional app identifier,
  save_private_key: true,
  new_profile: proc do |profile_path| # this block gets called when a new profile was generated
      puts profile_path # the absolute path to the new PEM file
      # insert the code to upload the PEM file to the server
    end
  )
end

lane :beta do
#  cocoapods

  get_push_certificate
  sync_code_signing(type: "appstore")
#  match(type: "appstore")

  # build your iOS app
  gym(
    scheme: "app",
    export_method: "app-store",
    clean: true,
    xcargs: "-allowProvisioningUpdates"
  )

  # upload to Testflight
  pilot(skip_waiting_for_build_processing: true)

  # slack(
  #   slack_url: "https://hooks.slack.com/services/IDS"
  # )
end

lane :pre_release do
  get_push_certificate
  sync_code_signing(type: "appstore")
  build_app(scheme: "app",
            workspace: "app.xcworkspace",
            include_bitcode: true)
end

lane :release do
  scan(derived_data_path: “~/Library/Developer/Xcode/DerivedData/“, build_for_testing: true, skip_build: true, scheme: "appUITests")
  reset_simulators
  capture_ios_screenshots(
    launch_arguments: ["--uitesting"]
  )
  get_push_certificate
  sync_code_signing(type: "appstore", readonly: true)
  build_app(scheme: "app",
            workspace: "app.xcworkspace",
            include_bitcode: true)

  deliver(
    submit_for_review: true,
    force: true,
    screenshots_path: "./screenshots"
  )
end



lane :refresh_dsyms do
  # Download dSYM files from iTC
  download_dsyms(
    version: "latest"
  )
  # Upload to firebase
  upload_symbols_to_crashlytics(
    gsp_path: "./app/GoogleService-Info.plist"
  )
  # Upload them to Sentry

  clean_build_artifacts           # Delete the local dSYM files
end

lane :sentry_staging_dsyms do |options|
  if options[:simulator]
    @pathToFile = sh("mdfind \"com_apple_xcode_dsym_uuids == *\" | grep iphonesimulator")
  else
    @pathToFile = sh("mdfind \"com_apple_xcode_dsym_uuids == *\" | grep iphoneos")
  end

  @file = File.dirname(@pathToFile)
  sh("zip -r #{@file}/debugDsym.zip #{@pathToFile}")
  
  sh("rm -f #{@file}/debugDsym.zip")
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "nl.app.app" # The bundle identifier of your app
apple_id "username@app.nl" # Your Apple email address


# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.139.0 | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                 | Version | Update-Status |
| ---------------------- | ------- | ------------- |
| fastlane-plugin-sentry | 1.6.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 2.0.2        |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| cork                      | 0.3.0        |
| nap                       | 1.1.0        |
| open4                     | 1.3.4        |
| claide-plugins            | 0.9.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.17.3       |
| faraday-http-cache        | 2.0.0        |
| git                       | 1.5.0        |
| kramdown                  | 2.1.0        |
| kramdown-parser-gfm       | 1.1.0        |
| no_proxy_fix              | 0.1.2        |
| sawyer                    | 0.8.2        |
| octokit                   | 4.15.0       |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| danger                    | 6.1.0        |
| mime-types-data           | 3.2019.1009  |
| mime-types                | 3.3.1        |
| multi_xml                 | 0.6.0        |
| httparty                  | 0.17.3       |
| gitlab                    | 4.13.1       |
| danger-gitlab             | 7.0.0        |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.71.1       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.0.1        |
| signet                    | 0.12.0       |
| googleauth                | 0.10.0       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.36.4       |
| digest-crc                | 0.4.1        |
| google-cloud-env          | 1.3.0        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.25.1       |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.7        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.2        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.14.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| xcresult                  | 0.2.0        |
| xcov                      | 1.7.0        |
| danger-xcov               | 0.4.1        |
| fastlane-plugin-sentry    | 1.6.0        |
| http-accept               | 1.7.0        |
| netrc                     | 0.11.0       |
| rest-client               | 2.1.0        |
</details>

*generated on:* **2020-03-02**
</details> </pre>

**Comment by lemonkey** [comment]
I'm also seeing something strange on CircleCI when I wasn't having any issues before upgrading my image to Xcode 11.3.1. During my Carthage embed libraries build phase it just hangs when it was fine before without any other modifications to my fastfile/gym/etc. logic.
