### ISSUE TITLE
Application specific password is ignored

### ISSUE THREAD

**Issue by mikeKane** [fastlane/fastlane#16110]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
I am running the notarization action 

#### Question Description
I am running this lane but it keeps failing bc of Ann authentication session. If I log the output inside of notarize.rb I can see its using my Apple ID which means its not using the application generated password. 

I am setting that like this 
```
$FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD="MYPASSWORD"
```

Is this not correct?

```
platform :mac do 
  lane :beta do |options|
    notarize(
        package:options[:dmg_path],
        bundle_id: "me.connectify.Speedify"    
    )
  end
end
```

**Comment by mikeKane** [comment]
Not sure its needed here?

**Comment by janpio** [comment]
> `$FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD="MYPASSWORD"`

Where are you doing this?
What does the output of the action/command look like?

**Comment by mikeKane** [comment]
It accepted it without error.

I fixed this passing in the env var with the creds and it works now
