### ISSUE TITLE
download_dsyms execution expired time and again

### ISSUE THREAD

**Issue by nobre84** [fastlane/fastlane#16115]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Download dsyms from app store connect fails most of the time. This affects different team members, in different locations/environments/ISPs. The message is only `execution expired`. It was reported before in #12424 but apart from some suggestion regarding DNS issues, nothing was discovered.
After a couple retries it works. The zip file was available in App Store Connect when retrying. It had just been uploaded on the first try so it probably had to wait a little bit. Is there a chance Apple is blocking repeated requests for this ? A possible solution could be to wait more between tries as it polls every 30 seconds or so.

##### Command executed
```
download_dsyms(
      app_identifier: app_identifier,
      build_number: build,
      wait_for_dsym_processing: true
    )
```

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre> 
[13:36:56]: Cruising over to lane 'ios upload_dsym' 🚖
[13:36:56]: -------------------------------------------------------------
[13:36:56]: --- Step: cd .. && git rev-list HEAD --count | tr -d "\n" ---
[13:36:56]: -------------------------------------------------------------
[13:36:56]: $ cd .. && git rev-list HEAD --count | tr -d "\n"
[13:36:56]: ▸ 3508
[13:36:56]: ----------------------------------------
[13:36:56]: --- Step: cd .. && rm -rf *.dSYM.zip ---
[13:36:56]: ----------------------------------------
[13:36:56]: $ cd .. && rm -rf *.dSYM.zip
[13:36:56]: ----------------------------
[13:36:56]: --- Step: download_dsyms ---
[13:36:56]: ----------------------------
[13:36:56]: Login to App Store Connect ()
[13:36:58]: Login successful
[13:36:59]: Looking for dSYM files for 'com.xxxx.v2.internal' on platform ios (3508)
[13:37:19]: Waiting for dSYM file to appear...
[13:37:51]: Waiting for dSYM file to appear...
[13:38:21]: Waiting for dSYM file to appear...
[13:39:52]: -------------------
[13:39:52]: --- Step: slack ---
[13:39:52]: -------------------
[13:39:53]: Successfully sent Slack notification
+--------------------+-----------------------------------------------------------------+
|                                     Lane Context                                     |
+--------------------+-----------------------------------------------------------------+
| DEFAULT_PLATFORM   | ios                                                             |
| PLATFORM_NAME      | ios                                                             |
| LANE_NAME          | ios beta                                                        |
| IPA_OUTPUT_PATH    | app.ipa              |
| DSYM_OUTPUT_PATH   | App.app.dSYM.zip     |
| XCODEBUILD_ARCHIVE | App  |
|                    | 2020-03-03 12.37.31.xcarchive                                   |
+--------------------+-----------------------------------------------------------------+
[13:39:53]: execution expired

+------+------------------------------------------+-------------+
|                       fastlane summary                        |
+------+------------------------------------------+-------------+
| Step | Action                                   | Time (in s) |
+------+------------------------------------------+-------------+
| 1    | default_platform                         | 0           |
| 2    | curl -sL https://sentry.io/get-cli/ |    | 0           |
|      | bash >> /dev/null ||:                    |             |
| 3    | slack                                    | 0           |
| 4    | Switch to ios setup_beta lane            | 0           |
| 5    | Switch to ios build lane                 | 0           |
| 6    | build_ios_app                            | 1011        |
| 7    | slack                                    | 0           |
| 8    | slack                                    | 0           |
| 9    | killall Charles | bash >> /dev/null ||:  | 0           |
| 10   | Switch to ios deploy lane                | 0           |
| 11   | pilot                                    | 2558        |
| 12   | slack                                    | 0           |
| 13   | slack                                    | 0           |
| 14   | Switch to ios upload_dsym lane           | 0           |
| 15   | cd .. && git rev-list HEAD --count | tr  | 0           |
|      | -d "\n"                                  |             |
| 16   | cd .. && rm -rf *.dSYM.zip               | 0           |
| 💥   | download_dsyms                           | 175         |
| 18   | slack                                    | 0           |
+------+------------------------------------------+-------------+

[13:39:53]: fastlane finished with errors
 </pre>
</details>

### Environment

<details>
  <pre> 

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.14.5                                         |
| Ruby                        | 2.5.1                                           |
| Bundler?                    | true                                            |
| Git                         | git version 2.21.0 (Apple Git-122.2)            |
| Installation Source         | ~/.rbenv/versions/2.5.1/bin/fastlane            |
| Host                        | Mac OS X 10.14.5 (18F132)                       |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.1/lib                     |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                     |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | false                                           |
| Xcode Path                  | /Applications/Xcode11.3.app/Contents/Developer/ |
| Xcode Version               | 11.3                                            |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform :ios

platform :ios do
    

  desc "Submit a new QA Build to TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    slack_msg("⏳ V2 Internal - build started", [ :git_branch ])
    test
    setup_beta
    build
    slack_msg("⏳ V2 Internal - build completed")
    slack_msg("⏳ V2 Internal - upload started")
    kill_charles
    deploy
    slack_msg("⏳ V2 Internal - upload completed")
slack_msg("⏳ V2 Internal - fetching dSYMs")
    upload_dsym
    slack_msg("⏳ V2 Internal - dSYMs uploaded")
    slack_qa
   
  end

  lane :upload_dsym do |options|
    build = options.fetch(:build, build_number)

    sh('cd .. && rm -rf *.dSYM.zip')
      
    download_dsyms(
      app_identifier: app_identifier,
      build_number: build,
      wait_for_dsym_processing: true
    )
    sentry_upload_cli
  end
  
  after_all do |lane|
      
  end

  error do |lane, exception|
      slack(pretext: "💥 iOS lane #{lane} failed with an exception:```#{exception.message}```",
            success: false)
  end
end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.140.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| bundler                   | 1.17.1       |
| fileutils                 | 1.0.2        |
| CFPropertyList            | 3.0.2        |
| concurrent-ruby           | 1.1.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.12.0       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.11.1     |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| httpclient                | 2.8.3        |
| json                      | 2.3.0        |
| algoliasearch             | 1.27.0       |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.8.0        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.2.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.4.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.14.0       |
| cocoapods                 | 1.8.0        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.71.1       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.17.3       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.0.1        |
| signet                    | 0.12.0       |
| googleauth                | 0.10.0       |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.0        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.25.1       |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.7        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.1        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.2        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2020-03-03**
</details>

 </pre>
</details>

**Comment by jsilarow** [comment]
I'm having the same issue here 

`WARN [2020-04-03 08:42:31.18]: Lane Context:
INFO [2020-04-03 08:42:31.18]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios refresh_dsyms"}
ERROR [2020-04-03 08:42:31.18]: execution expired
INFO [2020-04-03 08:42:31.18]: Successfully generated documentation at path '/Users/user/Sources/COMPANY/sport/fastlane/README.md'

+------+-------------------------------+-------------+
|                  fastlane summary                  |
+------+-------------------------------+-------------+
| Step | Action                        | Time (in s) |
+------+-------------------------------+-------------+
| 1    | update_fastlane               | 2           |
| 2    | default_platform              | 0           |
| 3    | Switch to ios env_worlds lane | 0           |
| 4    | last_git_commit               | 0           |
| 💥   | download_dsyms                | 67          |
+------+-------------------------------+-------------+

DEBUG [2020-04-03 08:42:31.19]: All plugins are up to date
ERROR [2020-04-03 08:42:31.19]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: execution expired

URL: https://api.github.com/search/issues?q=execution%20expired+repo:fastlane/fastlane
Could not access the GitHub API, you may have better luck via the website.
https://github.com/fastlane/fastlane/search?q=execution expired&type=Issues&utf8=✓
ERROR [2020-04-03 08:43:31.21]: Error finding relevant GitHub issues: undefined method `name' for #<Net::OpenTimeout: execution expired>
DEBUG [2020-04-03 08:43:31.21]: All plugins are up to date
Traceback (most recent call last):
	43: from /Users/user/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `<main>'
	42: from /Users/user/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `eval'
	41: from /Users/user/.rvm/gems/ruby-2.7.0/bin/fastlane:23:in `<main>'
	40: from /Users/user/.rvm/gems/ruby-2.7.0/bin/fastlane:23:in `load'
	39: from /Users/user/.rvm/gems/ruby-2.7.0/gems/fastlane-2.144.0/bin/fastlane:23:in `<top (required)>'
	38: from /Users/user/.rvm/gems/ruby-2.7.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	37: from /Users/user/.rvm/gems/ruby-2.7.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	36: from /Users/user/.rvm/gems/ruby-2.7.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	35: from /Users/user/.rvm/gems/ruby-2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	34: from /Users/user/.rvm/gems/ruby-2.7.0/gems/fastlane-2.144.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	33: from /Users/user/.rvm/gems/ruby-2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	32: from /Users/user/.rvm/gems/ruby-2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	31: from /Users/user/.rvm/gems/ruby-2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	30: from /Users/user/.rvm/gems/ruby-2.7.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	29: from /Users/user/.rvm/gems/ruby-2.7.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	28: from /Users/user/.rvm/gems/ruby-2.7.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	27: from /Users/user/.rvm/gems/ruby-2.7.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	26: from /Users/user/.rvm/gems/ruby-2.7.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	25: from /Users/user/.rvm/gems/ruby-2.7.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	24: from /Users/user/.rvm/gems/ruby-2.7.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	23: from ../fastlane_orig/Fastfile:55:in `block (2 levels) in parsing_binding'
	22: from /Users/user/.rvm/gems/ruby-2.7.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	21: from /Users/user/.rvm/gems/ruby-2.7.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	20: from /Users/user/.rvm/gems/ruby-2.7.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	19: from /Users/user/.rvm/gems/ruby-2.7.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	18: from /Users/user/.rvm/gems/ruby-2.7.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
	17: from /Users/user/.rvm/gems/ruby-2.7.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	16: from /Users/user/.rvm/gems/ruby-2.7.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
	15: from /Users/user/.rvm/gems/ruby-2.7.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/actions/download_dsyms.rb:77:in `run'
	14: from /Users/user/.rvm/gems/ruby-2.7.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/actions/download_dsyms.rb:77:in `each'
	13: from /Users/user/.rvm/gems/ruby-2.7.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/actions/download_dsyms.rb:93:in `block in run'
	12: from /Users/user/.rvm/gems/ruby-2.7.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/actions/download_dsyms.rb:93:in `each'
	11: from /Users/user/.rvm/gems/ruby-2.7.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/actions/download_dsyms.rb:133:in `block (2 levels) in run'
	10: from /Users/user/.rvm/gems/ruby-2.7.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/actions/download_dsyms.rb:148:in `download'
	 9: from /Users/user/.rvm/gems/ruby-2.7.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/actions/download_dsyms.rb:169:in `download_file'
	 8: from /Users/user/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/net/http.rb:1241:in `get'
	 7: from /Users/user/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/net/http.rb:1483:in `request'
	 6: from /Users/user/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/net/http.rb:932:in `start'
	 5: from /Users/user/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
	 4: from /Users/user/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/net/http.rb:958:in `connect'
	 3: from /Users/user/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/timeout.rb:105:in `timeout'
	 2: from /Users/user/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/net/http.rb:960:in `block in connect'
	 1: from /Users/user/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/net/http.rb:960:in `open'
/Users/user/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/net/http.rb:960:in `initialize': execution expired (Net::OpenTimeout)`

**Comment by Sai-Teja** [comment]
Any update?

**Comment by Sai-Teja** [comment]
This was due to a old version of ruby.

Add `require 'resolv-replace'` to the beginning of your fastlane file to fix this.

Reference: https://stackoverflow.com/questions/42036133/ruby-netopentimeout-execution-expired/42043142
