### ISSUE TITLE
fastlane deliver download_metadata failed with Ruby 2.7.0p0 on macOS

### ISSUE THREAD

**Issue by al-cheb** [fastlane/fastlane#16113]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
`fastlane deliver download_metadata` command is faling when using with Ruby 2.7.0p0(related Frozen String). Revert Ruby 2.7.0p0 to 2.6.5p114 version works as expected.

##### Command executed
`fastlane deliver download_metadata --app_identifier {APPID} --force true`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
Looking for related GitHub issues on fastlane/fastlane...
➡️  can't modify frozen String: "true" for enterprise builds
    https://github.com/fastlane/fastlane/issues/16055 [open] 28 💬
    3 days ago
➡️  can't modify frozen String: " after "Would you like fastlane to manage your app's metadata? (y/n)"
    https://github.com/fastlane/fastlane/issues/16098 [closed] 2 💬
    2 days ago
➡️  can't modify frozen String
    https://github.com/fastlane/fastlane/issues/15415 [closed] 3 💬
    30 Nov 2019
and 6 more at: https://github.com/fastlane/fastlane/search?q=can%27t%20modify%20frozen%20String%3A%20%22%22&type=Issues&utf8=✓
🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	16: from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `<main>'
	15: from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `load'
	14: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.142.0/bin/fastlane:23:in `<top (required)>'
	13: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	12: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.142.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
	11: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.142.0/deliver/lib/deliver/commands_generator.rb:182:in `run'
	10: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	 9: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.142.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 8: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 7: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 6: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 5: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.142.0/deliver/lib/deliver/commands_generator.rb:176:in `block (2 levels) in run'
	 4: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.142.0/deliver/lib/deliver/setup.rb:63:in `generate_metadata_files'
	 3: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.142.0/deliver/lib/deliver/setup.rb:63:in `each'
	 2: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.142.0/deliver/lib/deliver/setup.rb:64:in `block in generate_metadata_files'
	 1: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.142.0/deliver/lib/deliver/setup.rb:64:in `each'
/usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.142.0/deliver/lib/deliver/setup.rb:70:in `block (2 levels) in generate_metadata_files': can't modify frozen String: "" (FrozenError)
	16: from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `<main>'
	15: from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `load'
	14: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.142.0/bin/fastlane:23:in `<top (required)>'
	13: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	12: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.142.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
	11: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.142.0/deliver/lib/deliver/commands_generator.rb:182:in `run'
	10: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	 9: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.142.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 8: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 7: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 6: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 5: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.142.0/deliver/lib/deliver/commands_generator.rb:176:in `block (2 levels) in run'
	 4: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.142.0/deliver/lib/deliver/setup.rb:63:in `generate_metadata_files'
	 3: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.142.0/deliver/lib/deliver/setup.rb:63:in `each'
	 2: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.142.0/deliver/lib/deliver/setup.rb:64:in `block in generate_metadata_files'
	 1: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.142.0/deliver/lib/deliver/setup.rb:64:in `each'
/usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.142.0/deliver/lib/deliver/setup.rb:70:in `block (2 levels) in generate_metadata_files': \e[31m[!] can't modify frozen String: ""\e[0m (FrozenError) </pre>
</details>

### Environment

<details>
  <pre> 
<details><summary>✅ fastlane environment ✅</summary>
### Stack
| Key                         | Value                                              |
| --------------------------- | -------------------------------------------------- |
| OS                          | 10.15.3                                            |
| Ruby                        | 2.7.0                                              |
| Bundler?                    | false                                              |
| Git                         | git version 2.25.0                                 |
| Installation Source         | /usr/local/lib/ruby/gems/2.7.0/bin/fastlane        |
| Host                        | Mac OS X 10.15.3 (19D76)                           |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.7.0/lib                   |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                        |
| Is contained                | false                                              |
| Is homebrew                 | false                                              |
| Is installed via Fabric.app | false                                              |
| Xcode Path                  | /Applications/Xcode_11.3.1.app/Contents/Developer/ |
| Xcode Version               | 11.3.1                                             |
### System Locale
| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |
### fastlane files:
**No Fastfile found**
**No Appfile found**
### fastlane gems
| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.142.0 | ✅ Up-To-Date  |
### Loaded fastlane plugins:
**No plugins Loaded**
<details><summary><b>Loaded gems</b></summary>
| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.72.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.13.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.11.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.0        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| uri                       | 0.10.0       |
| unicode-display_width     | 1.6.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| json                      | 2.3.0        |
| bundler                   | 2.1.4        |
| digest-crc                | 0.5.0        |
| forwardable               | 1.3.1        |
| logger                    | 1.4.2        |
| cgi                       | 0.1.0        |
| timeout                   | 0.1.0        |
| stringio                  | 0.1.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.2.0        |
| strscan                   | 1.0.3        |
| date                      | 3.0.0        |
| delegate                  | 0.1.0        |
| fileutils                 | 1.4.1        |
| io-console                | 0.5.3        |
| zlib                      | 1.1.0        |
| singleton                 | 0.1.0        |
| mini_portile2             | 2.1.0        |
| nokogiri                  | 1.6.8.1      |
| racc                      | 1.4.16       |
| rexml                     | 3.2.3        |
| open3                     | 0.1.0        |
| yaml                      | 0.1.0        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |

[14:10:24]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
/usr/local/lib/ruby/gems/2.7.0/gems/highline-1.7.10/lib/highline.rb:624: warning: Using the last argument as keyword parameters is deprecated
</pre>
</details>

**Comment by raulrom13** [comment]
The same error in version 2.7 of ruby 🤕

**Comment by al-cheb** [comment]
@janpio Any updates?

**Comment by janpio** [comment]
Did someone investigate the problem and submit a PR? If so, I am happy to take a look and possibly merge it.

**Comment by Johennes** [comment]
Seems like a possible fix is to replace `content << "\n"` with `content += "\n"` in `~/.gem/ruby/2.7.0/gems/fastlane-2.145.0/deliver/lib/deliver/setup.rb`. At least that made it work for me.

**Comment by jknlsn** [comment]
> Seems like a possible fix is to replace `content << "\n"` with `content += "\n"` in `~/.gem/ruby/2.7.0/gems/fastlane-2.145.0/deliver/lib/deliver/setup.rb`. At least that made it work for me.

This worked for me too, thanks for the tip!

**Comment by al-cheb** [comment]
@Johennes Could you please create a PR?

**Comment by Johennes** [comment]
I did (one week ago): #16285 🙂
