### ISSUE TITLE
Fastlane error with app having arabic title with space

### ISSUE THREAD

**Issue by nithinnizam** [fastlane/fastlane#16114]
### New Issue Checklist

- [x] Updated fastlane to the latest version -> Checked
- [x] I read the [Contribution Guidelines] (https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)
-> Done
### Issue Description

I have been using fastlane on circleci machine for some time now. For one of our apps, it was working fine until yesterday. We changed the app title today to an arabic text with a space character and all of a sudden, fastlane is throwing an error. 

![Screenshot 2020-03-03 at 9 50 26 PM](https://user-images.githubusercontent.com/2194225/75795923-02687100-5d99-11ea-9491-7ac6afff3e36.png)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by max-ott** [comment]
@nithinnizam Could you please add full stack trace as well as environment details?
