### ISSUE TITLE
Changelogs are no longer showing up in TestFlight

### ISSUE THREAD

**Issue by puls** [fastlane/fastlane#16129]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

With no changes on our end, our TestFlight builds no longer have changelogs included. We have a custom action to generate the changelog that sets `SharedValues::FL_CHANGELOG` (#16000 has something to say about this but it appears to be supported behavior) and it clearly works, since the rest of the lane wouldn't run if it wasn't set.

##### Command executed

```ruby
  desc "Submit a new beta build to TestFlight"
  lane :internal_beta do
    ensure_git_status_clean(show_uncommitted_changes: true)
    custom_changelog
    if lane_context[SharedValues::FL_CHANGELOG].match(/\A\s*(- Bump build number [^\n+])?\s*\z/)
      print("No changes since last tag, bailing")
    else
      match(type: "appstore")
      increment_build_number
      git_commit(path: ".", message: "Bump build number")
      add_git_tag(tag: "ios-#{lane_context[SharedValues::BUILD_NUMBER]}")
      build_ios_app(scheme: "(Scheme name)", configuration: "Beta", include_bitcode: true)
      upload_to_testflight(distribute_external: false, notify_external_testers: false)
      upload_dsyms
    end
  end
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
[18:00:20]: Successfully finished processing the build 1.2 - 181 for IOS
[18:00:21]: Successfully set the changelog for build
[18:00:21]: Distributing new build to testers: 1.2 - 181
[18:00:21]: Successfully distributed build to Internal testers 🚀
 </pre>

But then, in TestFlight:
<img width="771" alt="Screen Shot 2020-03-05 at 6 14 01 PM" src="https://user-images.githubusercontent.com/9763/76043688-22b93c80-5f0d-11ea-9181-cab1cb6c4ca6.png">
</details>

### Environment

<details>
  <pre>
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                           |
| --------------------------- | --------------------------------------------------------------- |
| OS                          | 10.15.3                                                         |
| Ruby                        | 2.6.3                                                           |
| Bundler?                    | true                                                            |
| Git                         | git version 2.25.0                                              |
| Installation Source         | ~/Development/quill/xcode/vendor/bundle/ruby/2.6.0/bin/fastlane |
| Host                        | Mac OS X 10.15.3 (19D76)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib  |
| OpenSSL Version             | LibreSSL 2.8.3                                                  |
| Is contained                | false                                                           |
| Is homebrew                 | false                                                           |
| Is installed via Fabric.app | false                                                           |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                     |
| Xcode Version               | 11.3.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>
(contains sensitive information)
</details>

<details><summary>`./fastlane/Appfile`</summary>
(contains sensitive information)
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.142.0 | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-sentry    | 1.6.0   | ✅ Up-To-Date  |
| fastlane-plugin-semaphore | 0.2.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 1.17.2       |
| etc                       | 1.0.1        |
| forwardable               | 1.2.0        |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.72.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.17.3       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.0.1        |
| signet                    | 0.12.0       |
| googleauth                | 0.10.0       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.0        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.25.1       |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.1        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-semaphore | 0.2.0        |
| fastlane-plugin-sentry    | 1.6.0        |
</details>

*generated on:* **2020-03-05**
</details></pre>
</details>

**Comment by janpio** [comment]
> With no changes on our end

Same version of fastlane as well? Then the only reason can be a change on the server side of Apple unfortunately :/

**Comment by puls** [comment]
What should I do?

**Comment by majdi21** [comment]
I'm setting up fastlane and so far this is the only thing I can't figure out. I'm simply using the following command. The build uploads fine, but the 'What to Test' section is always empty. I tested the last update (fastlane 2.144.0) and it still doesn't work.

upload_to_testflight(
      skip_waiting_for_build_processing: false,
      changelog: "testing with new fastlane"
    )

Any help would be much appreciated. If anybody knows that this truely is an apple issue, please share the information you have.

**Comment by puls** [comment]
This is definitely still a problem.

**Comment by grevolution** [comment]
Any update on the issue? Is it the Apple backend issue or pilot?

**Comment by puls** [comment]
Still an issue.

**Comment by YannDanthu** [comment]
Same problem for me.

**Comment by rensakura** [comment]
Same problem here.

**Comment by pke** [comment]
I can report this is still a problem.
The changelog is not submitted, neither through the testflight action nor CLI pilot with `--changelog`.
This is with the previous and current fastlane version.
So it might be a change on Apples side.

**Comment by YannDanthu** [comment]
I think I manage to make it work by setting the context value before calling `upload_to_testflight`

```
Actions.lane_context[SharedValues::FL_CHANGELOG] = changeLog

upload_to_testflight(
    ipa: "path_to_app_file.ipa",
    changelog: changeLog
)
```

**Comment by pke** [comment]
@YannDanthu this approach does not work either on my side.

**Comment by pke** [comment]
It seems now I have gotten a changelog to show up in testflight! I'll investigate further.

**Comment by din** [comment]
I have the same issue.

**Comment by thiagodelmotte-mb** [comment]
Same problem here.

**Comment by thiagodelmotte-mb** [comment]
Not resolved.

**Comment by KortVea** [comment]
same problem

**Comment by lazarolima-mb** [comment]
Same problem here.

**Comment by puls** [comment]
Still a problem.

**Comment by taschik** [comment]
this seems to still be an issue, the changelog that shows up in Firebase AppDistribution doesn't show up in Testflight.

**Comment by tomires** [comment]
Can confirm this is still an issue. Tested with **changelog_from_git_commits** action, which sets FL_CHANGELOG value.

**Comment by taschik** [comment]
I found a nice workaround that worked for me:

Just use `localized_build_info` in your `upload_to_testflight()`
```
localized_build_info: {
    "default": {
        whats_new: options[:changelog],
    }
},
```
e.g.
```
upload_to_testflight(
      app_identifier: ENV['APP_IDENTIFIER'],
      ipa: "#{OUTPUT_DIRECTORY}#{PROJECT_NAME}.ipa",
      # The following is set to false in order to set the changelog
      # If using github runners, please set to false otherwise it 
      # will get really expensive!!!
      # skip_waiting_for_build_processing: true,
      skip_waiting_for_build_processing: false,
      verbose: true,
      uses_non_exempt_encryption: true,
      notify_external_testers: false,
      username:  ENV["APPLE_ID"],
      team_id: options[:apple_team_id],
      apple_id: options[:apple_app_id],
      itc_provider: ENV["sigh_#{options[:app_identifier]}_#{options[:match_type]}_team-id"],
      localized_build_info: {
        "default": {
          whats_new: options[:changelog],
        }
      },
      groups: [BUILD_FOR_PRODUCTION ? 'production_builds' : 'develop_builds']
    )
```

**Comment by tomires** [comment]
@taschik Doesn't work for me unfortunately. Even if I specify the value directly (e,g, _whats_new: "Update"_), it does not seem to get propagated to the respective field in TF app. But I will do further research on the topic, thank you for the suggestion.

**Comment by taschik** [comment]
@tomires it could be that the app needs to be approved for beta testing in order to do that. But I am not sure about it. Give that a try.

**Comment by tomires** [comment]
By beta testing approval, do you mean the _Missing Compliance_ check? I found that this is taken care of by default (and so far has worked flawlessly save for an occasional timeout), however just to be on the safe side (and as per your example), I have added a definition for _skip_waiting_for_build_processing: false_. Unfortunately it didn't seem to have any effect on the end result. 

My Fastfile looks as follows:
```
default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    make_filtered_changelog_from_git_commits
    enable_automatic_code_signing
    update_project_team(path: "Unity-iPhone.xcodeproj", teamid: ENV['TF_TEAMID'])
    increment_build_number(build_number: latest_testflight_build_number(version: "1.0") + 1)
    build_app(scheme: "Unity-iPhone")
    upload_to_testflight(
      uses_non_exempt_encryption: false,
      skip_waiting_for_build_processing: false,
      localized_build_info: {
        "default": {
          whats_new: lane_context[SharedValues::FL_CHANGELOG],
        }
      },
    )
  end
end
```

**make_filtered_changelog_from_git_commits** is a verbatim copy of https://docs.fastlane.tools/actions/changelog_from_git_commits/ for now

**Comment by Eddpt** [comment]
+1 also facing this problem.

What worked for me was sending a first build to external testers (which requires review) and then cancel said review.

I did this by passing `groups` along with `changelog`.

Afterwards, I cancelled the review and went back to just passing `changelog`. I can now see in the logs:
```
[...] Successfully set the changelog for build
```

@tomires is your app perhaps a somewhat new one which was never sent for review? Mine was, and sending it for external test review once seemed to fix the problem.

**Comment by tomires** [comment]
That is correct, it was never sent for external review. I will research more information on external testing, thank you!

**Comment by pjivers-bom** [comment]
I'm having the same issue.

**Comment by JohnCoates** [comment]
Thanks for the tip, @Eddpt! Submitting for external review and immediately canceling also worked for me.

**Comment by VictoryShoe** [comment]
@Eddpt Holy macaroni, this worked for me too.

In case anyone else is using the TestFlight website:

- Under External Groups, add a new group and then scroll down to click "Add Build" and fill in all the information. 
- Afterwards, I removed the build and deleted the group. 

This time when I ran my Fastfile, the changelog was successfully updated on the latest build.

**Comment by sergeyzhilkin** [comment]
it is still a problem, field "What to Test" is always empty

**Comment by Ewg777** [comment]
Same problem here

**Comment by KrauseFx** [comment]
Looks like this problem still persists, thanks everyone

**Comment by Ewg777** [comment]
Making the user an [App Manager](https://developer.apple.com/support/roles/) resolved the issue

**Comment by sergeyzhilkin** [comment]
actually I solved this problem:
1. use this key 
--wait_for_uploaded_build "true"
if you use this flag with  "false" value do not expect to see something in "What to test" field. 

2. if you are using api key  (i.e. --api_key_path /path/to/your/appstore_api_key)
make sure that it has enough permissions, in my case it was a message in fastlane output that api key is not authorized to access changelog or something like this

**Comment by ivan-gaydamakin** [comment]
Was same issue.

But for fix that, I made:
- Changed user with access "App Manager"
- Used this action:
```
In case anyone else is using the TestFlight website:
- Under External Groups, add a new group and then scroll down to click “Add Build” and fill in all the information.
- Afterwards, I removed the build and deleted the group.
This time when I ran my Fastfile, the changelog was successfully updated on the latest build.
```

Used code for example:
```
        changelog = changelog_from_git_commits(
          commits_count: 10,
          quiet: true,
          merge_commit_filtering: "exclude_merges"
        )
        puts "What to test:\n#{changelog}"

        upload_to_testflight(
          team_id: team_id,
          app_identifier: bundle_id,
          changelog: changelog,
        )
```

**Comment by axelson** [comment]
Eddpt's solution worked for me too: https://github.com/fastlane/fastlane/issues/16129#issuecomment-757020428

**Comment by pke** [comment]
This seems to be completely random. Now after not changing any fastlane configs it stopped working again.
There is really no way to tell what is going on with this functionality.

**Comment by gungorbasa** [comment]
I think external group names are the issue. I had a complex name like `Motion Coach & Biomarkers Platform
 ` as one of our external groups and it was failing. Most likely `&` or `empty_space` in the name causes this problem. The only thing I did was to remove that specific group and send my builds to a group named `Internal`.

Now, changelog shows up both on appstore connect and testflight app.

For running `upload_to_testflight`
Previously: I had `groups: ["Motion Coach & Biomarkers Platform", "Internal"]`
Now: I have `groups: ["Internal"]`

**Comment by pke** [comment]
This still is very random all. We are using only internal group and while CL has shown up before it isn't anymore

**Comment by Banck** [comment]
A few weeks ago the changelog was working fine. But recently it stopped working again.
I've noticed that immediately after build fastlane gets that build finished processing:

```
[01:20:37]: Successfully uploaded the new binary to App Store Connect
[01:20:37]: If you want to skip waiting for the processing to be finished, use the `skip_waiting_for_build_processing` option
[01:20:37]: Note that if `skip_waiting_for_build_processing` is used but a `changelog` is supplied, this process will wait for the build to appear on AppStoreConnect, update the changelog and then skip the remaining of the processing steps.
[01:20:37]: Waiting for processing on... app_id: ***, app_version: 1.0.0, build_version: 17, platform: IOS
[01:20:38]: Successfully finished processing the build 1.0.0 - 17 for IOS
[01:20:39]: Successfully set the changelog for build
```
Although in fact the build is being processed for some time

**Comment by pke** [comment]
In our case when it was not working we tried to publish to an unknown tester group. Then the changelog does not appear in any of the groups.

**Comment by lee5783** [comment]
https://github.com/fastlane/fastlane/issues/16129#issuecomment-757020428
Thank you. This workaround solution works for me
