### ISSUE TITLE
Screengrab: can't get screenshots from device

### ISSUE THREAD

**Issue by ArtyomZuev** [fastlane/fastlane#16122]
### New Regression Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: [e.g. `2.143.0`]
- Last working version: [e.g. `2.142.0`]

### Regression Description
I'm trying to automate my screenshot test. On the old version "2.142.0" there was an issue #16094 (which was troubling me, but not so bad). Then i tried newer "2.143.0" version. I can't get screenshots from device, it's been arguing for permissions.

I'm not sure, but something like #16090 is here, but maybe some other issue. 
There're two sepparated ways to track it:
1) I don't have directory for my screenshots and html file (see "log_1");
2) I've got directory and html file (see "log_2).

Plus I can't get "--capture_output" in my command "fastlane screengrab" somehow, sorry. That's why I'm sending logs.

##### Log_1
<details>
  <pre>[17:41:06]: Pulling captured screenshots for locale en-US from the device
ls: /data/data/com.whisperarts.kids.breastfeeding/app_screengrab: Permission denied
[17:41:07]: Exit status: 1
ls: /data/data/com.whisperarts.kids.breastfeeding/screengrab: Permission denied
[17:41:07]: Exit status: 1
ls: /data/user/0/com.whisperarts.kids.breastfeeding/files/com.whisperarts.kids.breastfeeding/screengrab/en-US/images/screenshots: Permission denied
[17:41:07]: Exit status: 1
ls: /data/data/com.whisperarts.kids.breastfeeding/files/com.whisperarts.kids.breastfeeding/screengrab/en-US/images/screenshots: Permission denied
[17:41:07]: Exit status: 1
[17:41:07]: Generating HTML Report
[17:41:07]: Successfully created HTML file with an overview of all the screenshots: '/home/android/Desktop/androidProjects/breastfeeding-android/fastlane/screenshots/screenshots.html'
[17:41:07]: Captured 0 new screenshots! 📷✨</pre>
</details>

##### Log_2
<details>
  <pre>[17:45:38]: Pulling captured screenshots for locale en-US from the device
ls: /data/data/com.whisperarts.kids.breastfeeding/app_screengrab: Permission denied
[17:45:38]: Exit status: 1
ls: /data/data/com.whisperarts.kids.breastfeeding/screengrab: Permission denied
[17:45:38]: Exit status: 1
ls: /data/user/0/com.whisperarts.kids.breastfeeding/files/com.whisperarts.kids.breastfeeding/screengrab/en-US/images/screenshots: Permission denied
[17:45:38]: Exit status: 1
ls: /data/data/com.whisperarts.kids.breastfeeding/files/com.whisperarts.kids.breastfeeding/screengrab/en-US/images/screenshots: Permission denied
[17:45:38]: Exit status: 1
[17:45:38]: Generating HTML Report

[17:45:38]: Error accessing file, this might be due to fastlane's directory handling
[17:45:38]: Check out https://docs.fastlane.tools/advanced/#directory-behavior for more details

Traceback (most recent call last):
	14: from /usr/local/bin/fastlane:23:in `<main>'
	13: from /usr/local/bin/fastlane:23:in `load'
	12: from /var/lib/gems/2.5.0/gems/fastlane-2.143.0/bin/fastlane:23:in `<top (required)>'
	11: from /var/lib/gems/2.5.0/gems/fastlane-2.143.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	10: from /var/lib/gems/2.5.0/gems/fastlane-2.143.0/screengrab/lib/screengrab/commands_generator.rb:19:in `start'
	 9: from /var/lib/gems/2.5.0/gems/fastlane-2.143.0/screengrab/lib/screengrab/commands_generator.rb:67:in `run'
	 8: from /var/lib/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	 7: from /var/lib/gems/2.5.0/gems/fastlane-2.143.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 6: from /var/lib/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 5: from /var/lib/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 4: from /var/lib/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 3: from /var/lib/gems/2.5.0/gems/fastlane-2.143.0/screengrab/lib/screengrab/commands_generator.rb:49:in `block (2 levels) in run'
	 2: from /var/lib/gems/2.5.0/gems/fastlane-2.143.0/screengrab/lib/screengrab/runner.rb:78:in `run'
	 1: from /var/lib/gems/2.5.0/gems/fastlane-2.143.0/screengrab/lib/screengrab/reports_generator.rb:29:in `generate'
/var/lib/gems/2.5.0/gems/fastlane-2.143.0/screengrab/lib/screengrab/reports_generator.rb:29:in `write': No such file or directory @ rb_sysopen - fastlane/screenshots/screenshots.html (Errno::ENOENT)</pre>
</details>

### Environment

<details>
  <pre>
[✔] 🚀 
[17:46:15]: fastlane detected a Gemfile in the current directory
[17:46:15]: However, it seems like you didn't use `bundle exec`
[17:46:15]: To launch fastlane faster, please use
[17:46:15]: 
[17:46:15]: $ bundle exec fastlane env
[17:46:15]: 
[17:46:15]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[17:46:16]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | debian_based buster/sid                                 |
| Ruby                        | 2.5.5                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.20.1                                      |
| Installation Source         | /usr/local/bin/fastlane                                 |
| Host                        | Ubuntu 19.10 debian_based buster/sid (5.3.0-40-generic) |
| Ruby Lib Dir                | /usr/lib                                                |
| OpenSSL Version             | OpenSSL 1.1.1c  28 May 2019                             |
| Is contained                | false                                                   |
| Is homebrew                 | false                                                   |
| Is installed via Fabric.app | false                                                   |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end
end


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.143.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.1        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.72.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.13.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.11.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.5.1        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-eventstream           | 1.0.3        |
| aws-sigv4                 | 1.1.1        |
| aws-sdk-core              | 2.11.460     |
| aws-sdk-resources         | 2.11.460     |
| aws-sdk                   | 2.11.460     |
| stringio                  | 0.0.1        |
| openssl                   | 2.1.2        |
| strscan                   | 1.0.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| etc                       | 1.0.0        |
| io-console                | 0.4.6        |
| zlib                      | 1.0.0        |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
</details>

*generated on:* **2020-03-05**
</details>
[17:46:16]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[17:46:16]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅</pre>
</details>

**Comment by joshdholtz** [comment]
@ArtyomZuev Will look into and get back to you soon!

**Comment by plastiv** [comment]
@ArtyomZuev have you enabled adb root flag? `Permission denied` hints for missing root. Check for more: https://github.com/fastlane/fastlane/pull/15635

**Comment by joshdholtz** [comment]
Yeah yeah, this could be it ☝️ Try setting `use_adb_root: true`. This _does_ only work (I think) with AVDs that use system images that are `Google APIs` (and not `Google Play`)

## This will work
![Screen Shot 2020-03-05 at 11 52 23 AM](https://user-images.githubusercontent.com/401294/76010012-c8ea4f80-5ed7-11ea-9d16-f48f00f3f932.png)

## This won't work
![Screen Shot 2020-03-05 at 11 53 08 AM](https://user-images.githubusercontent.com/401294/76010070-e3bcc400-5ed7-11ea-90d0-946978f93fff.png)

**Comment by ArtyomZuev** [comment]
@joshdholtz, yeah, I tried this one, my device was created with "Google Play", not "API" one.
Tried to root a new emulator, it did a trick, by only with permissions. Not it's arguing for not detecting directories and files. Maybe it can't create screenshots at all. 

###Log
`[09:43:55]: Pulling captured screenshots for locale en-US from the device
ls: /data/data/com.whisperarts.kids.breastfeeding/app_screengrab: No such file or directory`

I checked my setup for fastlane and screengrab at my application and script. I didn't notice any setting that I write wrong, all by guide.

**Comment by plastiv** [comment]
Running successfuly on previous version hints me that you don't use latest companion library. Just to confirm are you using `tools.fastlane:screengrab:2.0.0`? As it is the version introduced storing file at internal over external storage. Check `FileWritingCallback` change from https://github.com/fastlane/fastlane/commit/2f1815d0ed4c0c542f62ab721c52e639fdda696e#diff-543bbda0715a82d981c7df3152009b20 for more info.

**Comment by henningBunk** [comment]
I am having the same error. Latest working versions for me are:

fastlane: 2.141.0   
screengrab: 1.2.0 
emulator: sdk 28 with Play services (not store)
<details><pre>
[14:29:56]: ▸ OK (10 tests)
[14:29:57]: Pulling captured screenshots from the device
[14:29:57]: $ //Users/henning.bunk/Library/Android/sdk/platform-tools/adb -s emulator-5554 pull /sdcard/de.wetteronline.wetterapppro/screengrab /var/folders/1z/r9tnh30d2295kv_vs7q1f47r0000gp/T/d20200306-65147-o1x82z
ls: /data/data/de.wetteronline.wetterapppro/app_screengrab: No such file or directory
[14:29:57]: Exit status: 1
ls: /data/user/0/de.wetteronline.wetterapppro/files/de.wetteronline.wetterapppro/screengrab/de_DE/images/screenshots: No such file or directory
[14:29:57]: Exit status: 1
[14:29:58]: Screenshots copied to fastlane/screenshots/de-DE/images/phoneScreenshots
[14:29:58]: Generating HTML Report
[14:29:58]: Successfully created HTML file with an overview of all the screenshots: '/Users/henning.bunk/repos/android/wetter-app/fastlane/screenshots/screenshots.html'
[14:29:58]: Captured 9 screenshots! 📷✨
</details></pre>
Using fastlane 2.143.0 and screengrab 1.2.0 I get:
<details><pre>
[13:46:41]: ▸ OK (10 tests)
[13:46:42]: Pulling captured screenshots for locale de_DE from the device
ls: /data/data/my.app/app_screengrab: No such file or directory
[13:46:42]: Exit status: 1
ls: /data/data/my.app/screengrab: No such file or directory
[13:46:42]: Exit status: 1
ls: /data/user/0/my.app/files/my.app/screengrab/de_DE/images/screenshots: No such file or directory
[13:46:42]: Exit status: 1
ls: /data/data/my.app/files/my.app/screengrab/de_DE/images/screenshots: No such file or directory
[13:46:42]: Exit status: 1
[13:46:42]: Generating HTML Report
[13:46:42]: Successfully created HTML file with an overview of all the screenshots: '/Users/me/repos/android/app/fastlane/screenshots/screenshots.html'
[13:46:42]: Captured 0 new screenshots! 📷✨
</pre></details>

Using fastlane 2.141.0 and screengrab 2.0.0. I get:
<details><pre>
[14:04:26]: ▸ OK (10 tests)
[14:04:27]: Pulling captured screenshots from the device
ls: /sdcard/de.wetteronline.wetterapppro/screengrab: No such file or directory
[14:04:27]: Exit status: 1
ls: /data/data/de.wetteronline.wetterapppro/app_screengrab: No such file or directory
[14:04:27]: Exit status: 1
ls: /data/user/0/de.wetteronline.wetterapppro/files/de.wetteronline.wetterapppro/screengrab/de_DE/images/screenshots: No such file or directory
[14:04:27]: Exit status: 1
[14:04:27]: Make sure you've used Screengrab.screenshot() in your tests and that your expected tests are being run.
</pre></details>

Using fastlane 2.143.0 and screengrab 2.0.0. I get:
<details><pre>
[14:10:29]: ▸ OK (10 tests)
[14:10:29]: Pulling captured screenshots for locale de_DE from the device
ls: /sdcard/my.app/screengrab: No such file or directory
[14:10:30]: Exit status: 1
ls: /data/data/my.app/app_screengrab: No such file or directory
[14:10:30]: Exit status: 1
ls: /data/data/my.app/screengrab: No such file or directory
[14:10:30]: Exit status: 1
ls: /data/user/0/my.app/files/my.app/screengrab/de_DE/images/screenshots: No such file or directory
[14:10:30]: Exit status: 1
ls: /data/data/my.app/files/my.app/screengrab/de_DE/images/screenshots: No such file or directory
[14:10:30]: Exit status: 1
[14:10:30]: Generating HTML Report
[14:10:30]: Successfully created HTML file with an overview of all the screenshots: '/Users/me/repos/android/app/fastlane/screenshots/screenshots.html'
[14:10:30]: Captured 0 new screenshots! 📷✨
</pre></details>

Using an sdk 29 emulator (regardless the screengrab and fastlane version) I get:
`java.lang.RuntimeException: Error while connecting UiAutomation`

All tests were started with the adb root option.

**Comment by plastiv** [comment]
@henningBunk can you check on device into which folder screenshots are actually written?

I have noticed in your output that fastlane tries to pull screenshots from `/data/user/0/my.app/files/my.app/screengrab/de_DE/images/screenshots` folder. Are you passing `de_DE` into `fastlane screengrab --locales "de_DE"`?

Both documentation https://docs.fastlane.tools/actions/screengrab/#parameters and screenshot writing code https://github.com/fastlane/fastlane/blob/master/screengrab/screengrab-lib/src/main/java/tools.fastlane.screengrab/FileWritingScreenshotCallback.java#L114 suggests to use different separator `de-DE`.

**Comment by henningBunk** [comment]
Hey @plastiv 
thank you very much for your answer. Very good catch with a sharp eye! using `de-DE` as a parameter instead of `de_DE` helped me fix my problem. Hope that OP also gets help since I guess my problem wasnt related as I initialy thought.

**Comment by joshdholtz** [comment]
Oh hmmm 🤔 So we could maybe improve this by checking to make sure its a valid language?

**Comment by ArtyomZuev** [comment]
@plastiv, sorry for the late response. It was screengrab 1.2.0 at last. Now it's working perfect. 
Still need root and proper emulator on a side, but actualy making screenshots and grabing them. :)
