### ISSUE TITLE
Only upload screenshots with deliver

### ISSUE THREAD

**Issue by userException** [fastlane/fastlane#16124]
As per this thread: https://github.com/fastlane/fastlane/issues/14126, I tried sending the empty string in "deliver" to just upload the screenshots. But it did not work. Here is the lane:

    desc "Uploads screenshots only to appstore"
    lane :uploadScreenshots do 
        deliver(
            ipa: "",
            overwrite_screenshots: true,
            skip_binary_upload: true,
            skip_metadata: true,
            skip_screenshots: false,
            submit_for_review: false)
    end

**Error:**

[19:11:02]: --- Step: default_platform ---
[19:11:02]: ------------------------------
[19:11:02]: Driving the lane 'ios uploadScreenshots' 🚀
[19:11:02]: Error setting value '' for option 'ipa'
[19:11:02]: You passed invalid parameters to 'deliver'.

**Comment by janpio** [comment]
Have you tried setting the path to a valid ipa file? It should probably just not do anything with it.

**Comment by userException** [comment]
hmm, I also thought that a .ipa must exist at some point when I want to upload screenshots but yesterday, I found this when my CI server created a new VM, took the clone of my code, created a new app on the appstore via "produce" and took the screenshots via snapshot, to just upload them without a build. Since there was no .ipa file yet as gym/build didn't execute till then, it failed.

**Comment by janpio** [comment]
Yeah, I mean setting _any_ ipad and test out if the code then works and just does not do anything with said ipa file. Very possible this is currently just not taken into account, but could be if we know it works.

**Comment by userException** [comment]
Ok, I'll try this with a valid build path as well.
