### ISSUE TITLE
[FrameIt] How to make keyword and title with different font size respectively?

### ISSUE THREAD

**Issue by david-young-fax** [fastlane/fastlane#16128]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm using FrameIt to add frame to my app screenshots. I want to make the keyword and title with different font size. However they are all the same and I cannot make them different.

##### Command executed

fastlane frameit

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [✔] 🚀 
[06:16:40]: fastlane detected a Gemfile in the current directory
[06:16:40]: However, it seems like you didn't use `bundle exec`
[06:16:40]: To launch fastlane faster, please use
[06:16:40]: 
[06:16:40]: $ bundle exec fastlane frameit
[06:16:40]: 
[06:16:40]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[06:16:41]: Using device frames version 'latest'
[✔] Framing screenshot './iphone_6s_plus_home_page.png' 
[06:16:59]: Added frame: '/Users/chenkaty/Documents/FaxGun/fastlane/screenshots/ja/iphone_6s_plus_home_page_framed.png'
 </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15                                       |
| Ruby                        | 2.5.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.25.0                          |
| Installation Source         | ~/.rbenv/versions/2.5.0/bin/fastlane        |
| Host                        | Mac OS X 10.15 (19A583)                     |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.0/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.3.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.143.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.14.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 2.0.1        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-eventstream           | 1.0.3        |
| aws-sigv4                 | 1.1.1        |
| aws-sdk-core              | 2.11.460     |
| aws-sdk-resources         | 2.11.460     |
| aws-sdk                   | 2.11.460     |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| unicode-display_width     | 1.6.0        |
| addressable               | 2.7.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.3        |
| excon                     | 0.72.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| fastimage                 | 2.1.7        |
| json                      | 2.2.0        |
| dotenv                    | 2.7.5        |
| multi_json                | 1.14.1       |
| signet                    | 0.13.0       |
| os                        | 1.0.1        |
| memoist                   | 0.16.2       |
| googleauth                | 0.11.0       |
| digest-crc                | 0.4.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.25.1       |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
</details>

*generated on:* **2020-03-06**
</details>

**Comment by david-young-fax** [comment]
![iphone_6s_plus_home_page_framed](https://user-images.githubusercontent.com/53920743/76031653-110a8000-5f73-11ea-92ee-1097cbffdcc9.png)

The above is the generated framed screenshot. You can see the keyword & title are the same size. 

I'm expecting the tittle (Send from iPhone) smaller than keyword (Send Fax)

**Comment by janpio** [comment]
I don't really see an option described on https://docs.fastlane.tools/actions/frameit/ that would enable this. There is `font_scale_factor`, but I expect this applies to both elements the same way. 

You can set different fonts, but that of course does not really influence the font size. _Theoretically_ you could probably create a font with tiny characters, but I am not sure how viable that is.

Otherwise it seems this is a feature request, that needs to be implemented by someone.
