### ISSUE TITLE
Move AppStoreInfo.plist to build output directory if generated

### ISSUE THREAD

**Issue by Ashton-W** [fastlane/fastlane#16131]
#### Motivation Behind Feature
If the `exportOptions.plist` contains the key `generateAppStoreInformation` set to `true`, xcodebuild will produce a file `AppStoreInfo.plist` in it's output directory. **gym** does not currently move this file to the final output directory, it stays in the temporary directory.
If the user is generating this file, they want it in the output directory.

#### Feature Description
From `xcodebuild -help`:
> 	generateAppStoreInformation : Bool
>
>		For App Store exports, should Xcode generate App Store Information for uploading with iTMSTransporter? Defaults to NO.
It's used for uploading using iTMSTransporter on Windows and Linux. On macOS it can be generated on demand during upload.

The file `AppStoreInfo.plist` is generated in the xcodebuild output directory if the `exportOptions.plist` contains the key `generateAppStoreInformation` set to `true`. **gym** should move this file to the gym output directory, like it does a few other metadata files like App Thinning Report, if present.

#### Alternatives or Workarounds
You can instead use `sh` to run the `swinfo` tool outside of xcodebuild to analyze an already built IPA file. If doing this you should set `generateAppStoreInformation` to `false` because the file takes time to generate. There is no easy way to find the temporary directory gym uses to collect xcodebuild output in your script, but the file is in there as expected.

```ruby
# these options appear to match xcodebuild behaviour, but the file isn't identical because it includes env
sh "xcrun swinfo -f App.ipa -o AppStoreInfo.plist -prettyprint true --plistFormat binary"
```

**Comment by janpio** [comment]
> It's used for uploading using iTMSTransporter on Windows and Linux.

Unrelated: Do you have a link to get more information about iTMSTransporter for Windows and Linux?

**Comment by Ashton-W** [comment]
> Unrelated: Do you have a link to get more information about iTMSTransporter for Windows and Linux?

https://help.apple.com/itc/transporteruserguide/en.lproj/static.html
