### ISSUE TITLE
Supply Exits Without Error When Promoting From Empty Track

### ISSUE THREAD

**Issue by kyledecot** [fastlane/fastlane#16137]
When using supply to promote from an alpha track to a production track where the alpha track does not contain any APK I would expect fastlane to raise an error and exit w/ a non-zero code however it does not. 

```
[13:32:04]: Uploading all track and release changes to Google Play...
[13:32:06]: Successfully finished the upload to Google Play
[13:32:07]: Preparing to upload for language 'en-US'...
[13:32:08]: Uploading all meta changes to Google Play...
[13:32:09]: Successfully finished the upload to Google Play
[13:32:09]: Result: true
```

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.3                                     |
| Ruby                        | 2.6.5                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.21.0                          |
| Installation Source         | ~/.rbenv/versions/2.6.5/bin/fastlane        |
| Host                        | Mac OS X 10.15.3 (19D76)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.5/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.3.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.135.0 | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                 | Version | Update-Status      |
| ---------------------- | ------- | ------------------ |
| fastlane-plugin-root   | 0.1.0   | 💥 Check failed     |
| fastlane-plugin-sentry | 1.5.0   | 🚫 Update available |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 2.0.2        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| CFPropertyList            | 3.0.1        |
| concurrent-ruby           | 1.1.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.10       |
| builder                   | 3.2.3        |
| activemodel               | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| jwt                       | 2.1.0        |
| mixpanel-ruby             | 2.2.0        |
| app_store_connect         | 0.14.0       |
| ast                       | 2.4.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.0.3        |
| aws-partitions            | 1.230.0      |
| aws-sigv4                 | 1.1.0        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.72.0       |
| aws-sdk-kms               | 1.28.0       |
| aws-sdk-s3                | 1.36.1       |
| aws-sdk-ssm               | 1.44.0       |
| babosa                    | 1.0.3        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.17.0       |
| sawyer                    | 0.8.2        |
| buildkit                  | 1.4.0        |
| claide                    | 1.0.3        |
| clamp                     | 0.6.5        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.6.2        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.2.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.1        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.13.0       |
| cocoapods                 | 1.6.2        |
| coderay                   | 1.1.2        |
| colored                   | 1.2          |
| colorize                  | 0.8.1        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.68.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| memoist                   | 0.16.1       |
| multi_json                | 1.14.1       |
| os                        | 1.0.1        |
| signet                    | 0.12.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.1009  |
| mime-types                | 3.3          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.4.1        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.1.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| httparty                  | 0.16.2       |
| koala                     | 3.0.0        |
| oauth                     | 0.5.4        |
| rest-client               | 2.0.2        |
| ruby-trello               | 2.1.0        |
| semantic                  | 1.6.1        |
| fastlane-plugin-root      | 0.1.0        |
| fastlane-plugin-sentry    | 1.5.0        |
| jaro_winkler              | 1.5.2        |
| method_source             | 0.9.0        |
| parallel                  | 1.17.0       |
| parser                    | 2.6.3.0      |
| powerpack                 | 0.1.2        |
| pry                       | 0.11.3       |
| rainbow                   | 3.0.0        |
| ruby-progressbar          | 1.10.0       |
| rubocop                   | 0.58.2       |
| root-ruby-style           | 0.0.1        |
| synx                      | 0.2.1        |
| thor                      | 0.18.1       |
| testflight                | 1.0.3        |
| xcode-install             | 2.2.0        |
</details>

*generated on:* **2020-03-06**
</details>

**Comment by janpio** [comment]
Can you try updating to a recent version of fastlane? Not that we start debugging only to find out it is actually solved in a newer version.
