### ISSUE TITLE
aws-sdk with version 2, upgrade to v3

### ISSUE THREAD

**Issue by raulrom13** [fastlane/fastlane#16130]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

It's impossible to do a bundle update because I need aws-sdk v3 and fastlane uses aws-sdk v2. This cause incompatibilities in my gemfile.

##### Command executed

bundle update

**Comment by janpio** [comment]
We are happy to review and merge Pull Requests. Do you feel up to do this update and run the test suite (happens automatically when a PR is opened) to make sure everything still works? That would be awesome 🚀

**Comment by liamnichols** [comment]
The fix in #16143 handles this nicely, and reduces the dependency footprint which is great!

In the meantime, I was able to resolve the issue by adding `gem 'aws-sdk', '~> 3.0'` to my Gemfile.

**Comment by raulrom13** [comment]
Thanks.
