### ISSUE TITLE
deliver's automatic_release has no effect

### ISSUE THREAD

**Issue by nobre84** [fastlane/fastlane#16135]
Related issues: #15181, #15593
Was just caught offguard by this with a premature release after setting `automatic_release` to false. 
It's still an issue in fastlane 2.143.0, and the autobot aggressively closing unresolved issues is not making it any better, unfortunately.

**Comment by janpio** [comment]
We are happy to review and merge Pull Requests that fix this problem, unfortunately no one investigated yet what is going on here and created a Pull Request to fix it. It would be awesome if you would do so.
