### ISSUE TITLE
Exit status 74 (xcrun simctl spawn), for "run_tests"

### ISSUE THREAD

**Issue by userException** [fastlane/fastlane#16134]
```
desc "Execute all Unit tests"
lane :unitTests do

  run_tests(scheme: "CPUnitTests",
  devices: ["iPhone X"],
  clean: true,
  include_simulator_logs: true)

end
```

This lane works fine on my local machine but fails on a remote VM with this error:
**$ xcrun simctl spawn --standalone 1AOD089F-1092-4269—A745-90648A 9F088F log collect --output /Users/anka/Desktop/tempClone/fastlane/test_output/system_logs—iPhone\ 8_i05_13.3.logarchive 2>/dev/null**

If I just remove the "include_simulator_logs" flag, it works like a charm. I could not decipher what exactly this null path is. It would be great if you guys can figure this out so I can see the logs on the remote VM.

**Comment by janpio** [comment]
Can you please post the complete output you are getting? Right now I do not fully understand what is going on.

**Comment by userException** [comment]
[
<img width="659" alt="Screenshot 2020-03-06 at 6 26 54 PM" src="https://user-images.githubusercontent.com/3499123/76138232-e3edc880-606b-11ea-8a52-d2718d6985bb.png">
](url)

Here is an image of the issue, which I saved yesterday. If you need the full output, I'll get it in some time. Thanks for the quick replies..

**Comment by janpio** [comment]
This looks relevant: https://github.com/fastlane/fastlane/issues/8909

**Comment by userException** [comment]
hmm, so what I could get from the conversation in #8909 is, fastlane now ensures that a "mkdir" command creates a directory for the "dev/null" path. This dates back to 2017, strange why I am still getting this in fastlane 2.142.0. Please correct me, if I understood it incorrectly.

**Comment by janpio** [comment]
Sorry, can you check this is actually correct?

I think this is the code running here: https://github.com/fastlane/fastlane/blob/99479b562dd9bbc58773edd90966504fd979d641/fastlane_core/lib/fastlane_core/device_manager.rb#L285-L333 Not very debug friendly unfortunately. 

Can you try to run the same command with `--verbose` and see if you get additional output that could help understand what is causing the error?
