### ISSUE TITLE
How to add ENABLE_ONLY_ACTIVE_RESOURCES

### ISSUE THREAD

**Issue by ppamorim** [fastlane/fastlane#16136]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

I would like to add the flag `ENABLE_ONLY_ACTIVE_RESOURCES=NO` on the `gym` command.

#### Question Description
The script below tries to add the flag above to keep all assets inside the binary.

```ruby
gym(
    scheme: "MyApp",
    configuration: "Debug",
    silent: true,
    skip_archive: true,
    skip_codesigning: true,
    include_bitcode: false,
    derived_data_path: "/Users/me/Library/Developer/Xcode",
    xcargs: "ENABLE_ONLY_ACTIVE_RESOURCES=NO")
```

Unfortunately it's not working, the assets are still getting removed. Any idea of what can be done to keep the assets?

Similar issue: https://github.com/fastlane/fastlane/issues/14213

Thank you.

EDIT:

Basically what I am doing is to build the project with `Gym` first and then run `snapshot` to take screenshots concurrently. We have thousands of screenshots and it takes ages to take with the current setup because the app has to compile from scratch for each platform and device model.

Example:

```ruby
lane :screenshots do

  schemes = Array[//...]
  schemesScreenshot = Array[//...] 

  # Build apps
  schemes.each_with_index do |scheme, index|
    gym(
      scheme: scheme,
      configuration: "Debug",
      silent: true,
      skip_archive: true,
      skip_codesigning: true,
      include_bitcode: false,
      derived_data_path: "/Users/me/Library/Developer/Xcode",
      xcargs: "ENABLE_ONLY_ACTIVE_RESOURCES=YES")
  end

  # Build UI test for screenshot
  schemesScreenshot.each_with_index do |scheme, index|
    begin
      retries ||= 0
      puts "Trying to take snapshot. Retries: #{ retries }"
      snapshot(
        workspace: "MyApp.xcworkspace",
        scheme: scheme,
        derived_data_path: "/Users/me/Library/Developer/Xcode",
        output_simulator_logs: false,
        skip_open_summary: true,
        erase_simulator: false,
        clear_previous_screenshots: true,
        test_without_building: true,
        reinstall_app: true,
        concurrent_simulators: true,
        stop_after_first_error: false)
    rescue
      retry if (retries += 1) < 3
    end
  end

end
```

The devices being in use from the simulator are: `iPhone 6s Plus`, `iPhone 11`, `iPad Pro 2gen` and `iPad Pro 3gen`. On `iPhone 6s Plus` all app icons are gone.

If I set `test_without_building` as false, it is build the app for each device which is terribly slow. With the solution above everything speed up a lot.

**Comment by ppamorim** [comment]
@janpio Hi, any idea why `gym` is making the binary with only 2x images? Mostly of my images are vectors in PDF.

**Comment by janpio** [comment]
Sorry, no idea about `ENABLE_ONLY_ACTIVE_RESOURCES=NO` and also do not understand your question. In relation to the original issue? If so, how?

**Comment by ppamorim** [comment]
@janpio It's, I was trying to add `ENABLE_ONLY_ACTIVE_RESOURCES` to try to disable the Xcode default that only build for active resources.

The problem is that `gym` is not including the image size for older devices, like `1x`. But I am a bit confused since I am working purely with vectors.

Note the mic button has a icon on iPhone 11 but nothing on iPhone 6S.
<img width="1198" alt="Screenshot 2020-03-06 at 23 43 17" src="https://user-images.githubusercontent.com/5521682/76130999-a9047a00-6004-11ea-98d7-cbce4091d8e6.png">

**Comment by ppamorim** [comment]
Sorted!

Just replaced the build step with this:

```ruby
schemes.each do |scheme|
    gym(
      workspace: "T_Pro_Dictate.xcworkspace",
      scheme: scheme,
      configuration: "Debug",
      derived_data_path: "/Users/me/Library/Developer/Xcode",
      skip_package_ipa: true,
      skip_archive: true,
      destination: "generic/platform=iOS Simulator") # Important line!
  end
```

Now the app is building with all assets.

**Comment by janpio** [comment]
Can you explain what exactly this does and how it works? Future readers via Google might be interested in that ;)

**Comment by ppamorim** [comment]
@janpio In my project we have different schemes used to configure multiple apps from a base app. With the older solution I had to compile the app, from scratch, for each snapshot run and for each device. The whole process could take up to 4 hours. With my new solution I was able to take the screenshots for around 1 hour, 3 minutes and 37 seconds.
For my next improvement is to compile the UI test just once. Do you think it's possible?

**Comment by janpio** [comment]
> For my next improvement is to compile the UI test just once. Do you think it's possible?

I don't know. Best create a new issue and see if anyone else has an idea.
