### ISSUE TITLE
[FrameIt] Cannot generate framed screenshot correctly for iPads + certain languages

### ISSUE THREAD

**Issue by david-young-fax** [fastlane/fastlane#16140]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I can generate:
- iphone/ipad framed screenshot for languages like French
- iphone framed screenshots for Japanese

However I cannot generate:
- ipad framed screenshots for Japanese (and a couple of languages like Chinese etc)

##### Command executed

fastlane frameit

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
[10:44:11]: fastlane detected a Gemfile in the current directory
[10:44:11]: However, it seems like you didn't use `bundle exec`
[10:44:11]: To launch fastlane faster, please use
[10:44:11]: 
[10:44:11]: $ bundle exec fastlane frameit
[10:44:11]: 
[10:44:11]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[10:44:12]: Using device frames version 'latest'
[✔] Framing screenshot './ja/iphone_xs_max_1_home_page.png' 
[10:44:30]: Added frame: '/Users/chenkaty/Documents/FaxGun/fastlane/screenshots/ja/iphone_xs_max_1_home_page_framed.png'
[⠙] Framing screenshot './ja/iPadPro12.9-inch2ndGeneration_home_page.png' identify: geometry does not contain image `/var/folders/n1/qp1sbb_j1f1_s7ds03wjxmrw0000gn/T/mini_magick20200307-68816-m21bj1.png' @ warning/attribute.c/GetImageBoundingBox/507.
[⠇] Framing screenshot './ja/iPadPro12.9-inch2ndGeneration_home_page.png' identify: geometry does not contain image `/var/folders/n1/qp1sbb_j1f1_s7ds03wjxmrw0000gn/T/mini_magick20200307-68816-169jn50.png' @ warning/attribute.c/GetImageBoundingBox/507.
[⠙] Framing screenshot './ja/iPadPro12.9-inch2ndGeneration_home_page.png' mogrify: geometry does not contain image `/var/folders/n1/qp1sbb_j1f1_s7ds03wjxmrw0000gn/T/mini_magick20200307-68816-m21bj1.png' @ warning/transform.c/CropImage/643.
[⠸] Framing screenshot './ja/iPadPro12.9-inch2ndGeneration_home_page.png' mogrify: geometry does not contain image `/var/folders/n1/qp1sbb_j1f1_s7ds03wjxmrw0000gn/T/mini_magick20200307-68816-169jn50.png' @ warning/transform.c/CropImage/643.
[✔] Framing screenshot './ja/iPadPro12.9-inch2ndGeneration_home_page.png' 
[10:45:08]: Added frame: '/Users/chenkaty/Documents/FaxGun/fastlane/screenshots/ja/iPadPro12.9-inch2ndGeneration_home_page_framed.png'
[⠏] Framing screenshot './ja/ipad_pro_3rd_gen_home_page.png' identify: geometry does not contain image `/var/folders/n1/qp1sbb_j1f1_s7ds03wjxmrw0000gn/T/mini_magick20200307-68816-t1wxlr.png' @ warning/attribute.c/GetImageBoundingBox/507.
[⠦] Framing screenshot './ja/ipad_pro_3rd_gen_home_page.png' identify: geometry does not contain image `/var/folders/n1/qp1sbb_j1f1_s7ds03wjxmrw0000gn/T/mini_magick20200307-68816-1q4v0j1.png' @ warning/attribute.c/GetImageBoundingBox/507.
[⠇] Framing screenshot './ja/ipad_pro_3rd_gen_home_page.png' mogrify: geometry does not contain image `/var/folders/n1/qp1sbb_j1f1_s7ds03wjxmrw0000gn/T/mini_magick20200307-68816-t1wxlr.png' @ warning/transform.c/CropImage/643.
[⠙] Framing screenshot './ja/ipad_pro_3rd_gen_home_page.png' mogrify: geometry does not contain image `/var/folders/n1/qp1sbb_j1f1_s7ds03wjxmrw0000gn/T/mini_magick20200307-68816-1q4v0j1.png' @ warning/transform.c/CropImage/643.
[✔] Framing screenshot './ja/ipad_pro_3rd_gen_home_page.png' 
[10:45:47]: Added frame: '/Users/chenkaty/Documents/FaxGun/fastlane/screenshots/ja/ipad_pro_3rd_gen_home_page_framed.png'
[✔] Framing screenshot './ja/iphone6Plus_1_home_page.png' 
[10:46:07]: Added frame: '/Users/chenkaty/Documents/FaxGun/fastlane/screenshots/ja/iphone6Plus_1_home_page_framed.png'

 </pre>
</details>

### Environment

<details>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15                                       |
| Ruby                        | 2.5.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.25.0                          |
| Installation Source         | ~/.rbenv/versions/2.5.0/bin/fastlane        |
| Host                        | Mac OS X 10.15 (19A583)                     |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.0/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.3.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.143.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.14.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 2.0.1        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-eventstream           | 1.0.3        |
| aws-sigv4                 | 1.1.1        |
| aws-sdk-core              | 2.11.460     |
| aws-sdk-resources         | 2.11.460     |
| aws-sdk                   | 2.11.460     |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| unicode-display_width     | 1.6.0        |
| addressable               | 2.7.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.3        |
| excon                     | 0.72.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| fastimage                 | 2.1.7        |
| json                      | 2.2.0        |
| dotenv                    | 2.7.5        |
| multi_json                | 1.14.1       |
| signet                    | 0.13.0       |
| os                        | 1.0.1        |
| memoist                   | 0.16.2       |
| googleauth                | 0.11.0       |
| digest-crc                | 0.4.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.25.1       |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
</details>

*generated on:* **2020-03-07**
</details></details>

**Comment by david-young-fax** [comment]
Framefile JSON: 

{
  "default": {
    "keyword": {
      "fonts": [
        {
          "font": "./fonts/NotoSans-Bold.ttf",
          "supported": ["ca", "cs", "da", "de-DE", "el", "en-US", "es-ES", "es-MX", "fi", "fr-FR", "hr", "hu", "id", "it", "ms", "nl-NL", "no", "pl", "pt-BR", "pt-PT", "ro", "ru", "sk", "sv", "th", "tr", "uk", "vi"]
        },
        {
          "font": "./fonts/NotoSansCJKtc-Bold.ttf",
          "supported": ["zh-Hant", "ja", "ko"]
        },
        {
          "font": "./fonts/msyh.ttf",
          "supported": ["zh-Hans"]
        },
        {
          "font": "./fonts/NotoKufiArabic-Bold.ttf",
          "supported": ["ar-SA"]
        },
        {
          "font": "./fonts/NotoSansHebrew-Bold.ttf",
          "supported": ["he"]
        },
        {
          "font": "./fonts/NotoSansDevanagari-Bold.ttf",
          "supported": ["hi"]
        }
      ]
    },
    "title": {
      "fonts": [
        {
          "font": "./fonts/NotoSans-Regular.ttf",
          "supported": ["ca", "cs", "da", "de-DE", "el", "en-US", "es-ES", "es-MX", "fi", "fr-FR", "hr", "hu", "id", "it", "ms", "nl-NL", "no", "pl", "pt-BR", "pt-PT", "ro", "ru", "sk", "sv", "th", "tr", "uk", "vi"]
        },
        {
          "font": "./fonts/NotoSansCJKtc-Regular.ttf",
          "supported": ["zh-Hant", "ja", "ko"]
        },
        {
          "font": "./fonts/msyh.ttf",
          "supported": ["zh-Hans"]
        },
        {
          "font": "./fonts/NotoKufiArabic-Regular.ttf",
          "supported": ["ar-SA"]
        },
        {
          "font": "./fonts/NotoSansHebrew-Regular.ttf",
          "supported": ["he"]
        },
        {
          "font": "./fonts/NotoSansDevanagari-Regular.ttf",
          "supported": ["hi"]
        }
      ],
      "color": "#000000"
    },
    "background": "./background.jpg",
    "padding": 50,
    "debug_mode": true,
    "stack_title": true
  },

  "data": [
    {
      "filter": "home_page",
      "keyword": {
        "color": "#000000"
      }
    },
    {
      "filter": "receive",
      "keyword": {
        "color": "#000000"
      }
    },
    {
      "filter": "track",
      "keyword": {
        "color": "#000000"
      }
    },
    {
      "filter": "upload",
      "keyword": {
        "color": "#000000"
      }
    },
    {
      "filter": "preview",
      "keyword": {
        "color": "#000000"
      }
    },
    {
      "filter": "email",
      "keyword": {
        "color": "#000000"
      }
    },
    {
      "filter": "print",
      "keyword": {
        "color": "#000000"
      }
    },
    {
      "filter": "clear",
      "keyword": {
        "color": "#000000"
      }
    },
    {
      "filter": "country_code",
      "keyword": {
        "color": "#000000"
      }
    }
  ]
}

**Comment by david-young-fax** [comment]
Japanese title.strings:


"home_page" = "携帯電話から送信 高速で簡単";

"receive" = "FAX番号を取得してどこからでも受信";

"track" = "送受信されたすべてのドキュメント";

"upload" = "さまざまな形式のドキュメント";

"preview" = "文書を送信する前に";

"email" = "メールボックスにドキュメントを保存する";

"print" = "電話からドキュメントを受信しました";

"clear" = "きれいできれいなファックス文書";

"country_code" = "世界中で支えられている国々";

**Comment by david-young-fax** [comment]
Japanese keyword.strings:


"home_page" = "ファックス送信";

"receive" = "受け取る";

"track" = "追跡";

"upload" = "アップロードする";

"preview" = "プレビュー";

"email" = "Eメール";

"print" = "印刷する";

"clear" = "晴れ";

"country_code" = "120+";

**Comment by david-young-fax** [comment]
![Uploading ipad_pro_3rd_gen_home_page.png…]()

**Comment by david-young-fax** [comment]
Output, which is weird:

![ipad_pro_3rd_gen_home_page_framed](https://user-images.githubusercontent.com/53920743/76135538-a59fdb80-6062-11ea-97ec-6c076b2a1752.png)
![iPadPro12 9-inch2ndGeneration_home_page_framed](https://user-images.githubusercontent.com/53920743/76135540-a9cbf900-6062-11ea-9dd1-cc66f1aa4947.png)

**Comment by david-young-fax** [comment]
This the warning during the generation. It cannot add the keyword/title text correctly. I have the font correctly installed, and it can generate iphone version. I really don't know what could be the problem

[⠏] Framing screenshot './ja/ipad_pro_3rd_gen_home_page.png' identify: geometry does not contain image `/var/folders/n1/qp1sbb_j1f1_s7ds03wjxmrw0000gn/T/mini_magick20200307-68816-t1wxlr.png' @ warning/attribute.c/GetImageBoundingBox/507.

**Comment by bvirlet** [comment]
@david-young-fax can you try with Fastlane 2.142.0 (just to make sure #14628 is not the issue here)

**Comment by david-young-fax** [comment]
@bvirlet  I just tried fastlane 2.142.0, it doesn't work and still output errors like below:

[✔] 🚀 
[03:09:31]: fastlane detected a Gemfile in the current directory
[03:09:31]: However, it seems like you didn't use `bundle exec`
[03:09:31]: To launch fastlane faster, please use
[03:09:31]: 
[03:09:31]: $ bundle exec fastlane frameit
[03:09:31]: 
[03:09:31]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[03:09:34]: Using device frames version 'latest'
[✔] Framing screenshot './ja/iphone_xs_max_1_home_page.png' 
[03:09:54]: Added frame: '/Users/chenkaty/Documents/FaxGun/fastlane/screenshots/ja/iphone_xs_max_1_home_page_framed.png'
[⠦] Framing screenshot './ja/ipad_pro_3rd_gen_1_home_page.png' identify: geometry does not contain image `/var/folders/n1/qp1sbb_j1f1_s7ds03wjxmrw0000gn/T/mini_magick20200310-68506-1fomggx.png' @ warning/attribute.c/GetImageBoundingBox/507.
[⠹] Framing screenshot './ja/ipad_pro_3rd_gen_1_home_page.png' identify: geometry does not contain image `/var/folders/n1/qp1sbb_j1f1_s7ds03wjxmrw0000gn/T/mini_magick20200310-68506-b25938.png' @ warning/attribute.c/GetImageBoundingBox/507.
[⠦] Framing screenshot './ja/ipad_pro_3rd_gen_1_home_page.png' mogrify: geometry does not contain image `/var/folders/n1/qp1sbb_j1f1_s7ds03wjxmrw0000gn/T/mini_magick20200310-68506-1fomggx.png' @ warning/transform.c/CropImage/643.
[⠙] Framing screenshot './ja/ipad_pro_3rd_gen_1_home_page.png' mogrify: geometry does not contain image `/var/folders/n1/qp1sbb_j1f1_s7ds03wjxmrw0000gn/T/mini_magick20200310-68506-b25938.png' @ warning/transform.c/CropImage/643.
[✔] Framing screenshot './ja/ipad_pro_3rd_gen_1_home_page.png' 
[03:10:44]: Added frame: '/Users/chenkaty/Documents/FaxGun/fastlane/screenshots/ja/ipad_pro_3rd_gen_1_home_page_framed.png'
[✔] Framing screenshot './ja/iphone6Plus_1_home_page.png' 
[03:11:05]: Added frame: '/Users/chenkaty/Documents/FaxGun/fastlane/screenshots/ja/iphone6Plus_1_home_page_framed.png'
[⠏] Framing screenshot './ja/iPad Pro (12.9-inch) 2nd_gen_1_home_page.png' identify: geometry does not contain image `/var/folders/n1/qp1sbb_j1f1_s7ds03wjxmrw0000gn/T/mini_magick20200310-68506-er3hbm.png' @ warning/attribute.c/GetImageBoundingBox/507.
[⠸] Framing screenshot './ja/iPad Pro (12.9-inch) 2nd_gen_1_home_page.png' identify: geometry does not contain image `/var/folders/n1/qp1sbb_j1f1_s7ds03wjxmrw0000gn/T/mini_magick20200310-68506-144m2kx.png' @ warning/attribute.c/GetImageBoundingBox/507.
[⠇] Framing screenshot './ja/iPad Pro (12.9-inch) 2nd_gen_1_home_page.png' mogrify: geometry does not contain image `/var/folders/n1/qp1sbb_j1f1_s7ds03wjxmrw0000gn/T/mini_magick20200310-68506-er3hbm.png' @ warning/transform.c/CropImage/643.
[⠼] Framing screenshot './ja/iPad Pro (12.9-inch) 2nd_gen_1_home_page.png' mogrify: geometry does not contain image `/var/folders/n1/qp1sbb_j1f1_s7ds03wjxmrw0000gn/T/mini_magick20200310-68506-144m2kx.png' @ warning/transform.c/CropImage/643.
[✔] Framing screenshot './ja/iPad Pro (12.9-inch) 2nd_gen_1_home_page.png' 
[03:11:53]: Added frame: '/Users/chenkaty/Documents/FaxGun/fastlane/screenshots/ja/iPad Pro (12.9-inch) 2nd_gen_1_home_page_framed.png'

#######################################################################
# fastlane 2.143.0 is available. You are on 2.142.0.
# You should use the latest version.
# Please update using `sudo gem install fastlane`.
#######################################################################
# Run `sudo gem cleanup` from time to time to speed up fastlane
#######################################################################

2.143.0 Frameit Android and Match S3 Storage
* [frameit] support for Android (#15087) via Josh Holtz
* [screengrab] fix screengrab folder name (#16094) via Josh Holtz
* [match] add Amazon S3 storage. (#15200) via Josh Holtz
* [match] fixed match import looking for old certificate types only (#16041) via Josh Holtz
* [frameit] take in account effective_text_height for available text height (#14628) via Bruno Virlet
* [scan] set an extension of resultBundlePath as ".xcresult" when using Xcode 11 (#16044) via Atsuto Yamashita
* [pilot] removes raising exception when build_beta_detail is nil (#16068) via Rogerio de Paula Assis

Please update using `sudo gem install fastlane`

**Comment by david-young-fax** [comment]
@bvirlet @janpio Any suggestions?

**Comment by lighthouse16** [comment]
I have the same issue with the languages ko, ja, hi, th, he, zh-Hant, zh-Hans using Fastlane 2.145.0. Did you found a solution in the meantime @david-young-fax ?

**Comment by ablyes** [comment]
Same issue for me with : 
fastlane 2.145.0
With : chinese, japanese, russian.

**Comment by david-young-fax** [comment]
@lighthouse16  no I haven't found a solution yet. I tried to look into the code of fastlane, but I'm not familiar with Ruby and I have been quite busy on other things. 

Anyone could help debug this issue? I think likely it's a bug somewhere in fastlane. @bvirlet @janpio

**Comment by bvirlet** [comment]
@david-young-fax could you provide a .zip of your fastlane screenshot (with everything needed to run `frameit` to allow reproduction of the problem)?

**Comment by david-young-fax** [comment]
@bvirlet  sure, please see the attached zip:
- You can create a "screenshots" folder and unzip it there
- And then run "fastlane frameit" outside the "screenshot" folder. 
- Then it will reproduce the problem

[screenshots.zip](https://github.com/fastlane/fastlane/files/4470835/screenshots.zip)

And I think I found the bug, it might be related to the configuration settings:
- If you remove the font "NotoSans-Bold.ttf" in Framefile.json, it can produce Japanese screenshot correctly. 
- Something is wrong when loading the fonts and the logic behind is not really reflecting the Framefile.json configuration file.

**Comment by ablyes** [comment]
Good analysis !
You're right, when I remove the regular font (for en, pt, fr, it ....) from Framefile.json the frame process is done correctly for the iPads.

**Comment by bvirlet** [comment]
I believe the problem is with the font. Could you try a .otf font ?

**Comment by wellavelino** [comment]
same issue here =/
@bvirlet also on Android the same is happening (I'm using .otf)

**Comment by bvirlet** [comment]
I have reproduced the issue and have a fix for it. In the meantime, try to ensure your screenshot names do not have any language in them. In your case `iphone6Plus_3_track_framed` contains `tr`. Rename it in a different way and you should be good.
