### ISSUE TITLE
Custom actions called through other_action don't run in the correct directory

### ISSUE THREAD

**Issue by sirghi** [fastlane/fastlane#16145]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I have _action_b_ called from _action_a_ called from _lane_one_ and I'm printing the `Dir.pwd` at the beginning of each action. While it correctly outputs the root directory inside _action_a_, it's printing the Fastlane folder inside _action_b_.

Looking through the code I can see other_action is passing the Fastlane folder path:
https://github.com/fastlane/fastlane/blob/5e23f949f4c943f484d48249a39f2662b56f466d/fastlane/lib/fastlane/other_action.rb#L12-L26

That method will call inside to:
https://github.com/fastlane/fastlane/blob/5e23f949f4c943f484d48249a39f2662b56f466d/fastlane/lib/fastlane/runner.rb#L218-L229

As we can see, since we're not passing in nil as the _custom_dir_, the code doesn't append `..`, so the _custom_dir_ remains unchanged, running the other action inside the fastlane folder, rather than the root folder (the failed intention is even confirmed by the comments inside other_action.rb).

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.3                                     |
| Ruby                        | 2.6.5                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.21.1 (Apple Git-122.3)        |
| Installation Source         | ~/.rbenv/versions/2.6.5/bin/fastlane        |
| Host                        | Mac OS X 10.15.3 (19D76)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.5/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.3.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.143.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status  |
| ----------------------------------------- | ------- | -------------- |
| fastlane-plugin-tenant_config             | 1.0.0   | 💥 Check failed |
| fastlane-plugin-firebase_app_distribution | 0.1.4   | ✅ Up-To-Date   |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.3.0        |
| bundler                                   | 1.17.2       |
| etc                                       | 1.0.1        |
| forwardable                               | 1.2.0        |
| fileutils                                 | 1.1.0        |
| CFPropertyList                            | 3.0.2        |
| concurrent-ruby                           | 1.1.6        |
| i18n                                      | 0.9.5        |
| minitest                                  | 5.14.0       |
| thread_safe                               | 0.3.6        |
| tzinfo                                    | 1.2.6        |
| activesupport                             | 4.2.11.1     |
| public_suffix                             | 2.0.5        |
| addressable                               | 2.7.0        |
| httpclient                                | 2.8.3        |
| json                                      | 2.3.0        |
| algoliasearch                             | 1.27.1       |
| atomos                                    | 0.1.3        |
| aws-eventstream                           | 1.0.3        |
| aws-sigv4                                 | 1.1.1        |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 2.11.462     |
| aws-sdk-resources                         | 2.11.462     |
| aws-sdk                                   | 2.11.462     |
| babosa                                    | 1.0.3        |
| claide                                    | 1.0.3        |
| clamp                                     | 1.3.1        |
| fuzzy_match                               | 2.0.4        |
| nap                                       | 1.1.0        |
| netrc                                     | 0.11.0       |
| ffi                                       | 1.12.2       |
| ethon                                     | 0.12.0       |
| typhoeus                                  | 1.3.1        |
| cocoapods-core                            | 1.9.0        |
| cocoapods-deintegrate                     | 1.0.4        |
| cocoapods-downloader                      | 1.3.0        |
| cocoapods-plugins                         | 1.0.0        |
| cocoapods-search                          | 1.0.0        |
| cocoapods-stats                           | 1.1.0        |
| cocoapods-trunk                           | 1.4.1        |
| cocoapods-try                             | 1.1.0        |
| colored2                                  | 3.1.2        |
| escape                                    | 0.0.4        |
| fourflusher                               | 2.3.1        |
| gh_inspector                              | 1.1.3        |
| molinillo                                 | 0.6.6        |
| ruby-macho                                | 1.4.0        |
| nanaimo                                   | 0.2.6        |
| xcodeproj                                 | 1.15.0       |
| cocoapods                                 | 1.9.0        |
| redcarpet                                 | 3.5.0        |
| cocoapods-acknowledgements                | 1.1.3        |
| cocoapods-translations                    | 1.0.0        |
| colored                                   | 1.2          |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| declarative                               | 0.0.10       |
| declarative-option                        | 0.1.0        |
| diffy                                     | 3.3.0        |
| digest-crc                                | 0.5.1        |
| unf_ext                                   | 0.0.7.6      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| dotenv                                    | 2.7.5        |
| emoji_regex                               | 1.0.1        |
| excon                                     | 0.72.0       |
| multipart-post                            | 2.0.0        |
| faraday                                   | 0.17.3       |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.6        |
| faraday_middleware                        | 0.13.1       |
| fastimage                                 | 2.1.7        |
| jwt                                       | 2.1.0        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.14.1       |
| os                                        | 1.0.1        |
| signet                                    | 0.13.0       |
| googleauth                                | 0.11.0       |
| mini_mime                                 | 1.0.2        |
| uber                                      | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| google-api-client                         | 0.36.4       |
| google-cloud-env                          | 1.3.1        |
| google-cloud-errors                       | 1.0.0        |
| google-cloud-core                         | 1.5.0        |
| google-cloud-storage                      | 1.25.1       |
| mini_magick                               | 4.10.1       |
| multi_xml                                 | 0.6.0        |
| plist                                     | 3.5.0        |
| rubyzip                                   | 1.3.0        |
| security                                  | 0.1.3        |
| naturally                                 | 2.2.0        |
| simctl                                    | 1.6.8        |
| slack-notifier                            | 2.3.2        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.6.1        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.7.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| word_wrap                                 | 1.0.0        |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.0        |
| fastlane-plugin-firebase_app_distribution | 0.1.4        |
| mime-types                                | 1.25.1       |
| rest-client                               | 1.6.14       |
| fastlane-plugin-tenant_config             | 1.0.0        |
| mini_portile2                             | 2.4.0        |
| nokogiri                                  | 1.10.9       |
| google_drive                              | 2.1.3        |
| slather                                   | 2.4.7        |
| xcode-install                             | 2.6.3        |
</details>

*generated on:* **2020-03-09**
</details> </pre>
</details>

**Comment by sirghi** [comment]
Any input from anyone?

**Comment by sirghi** [comment]
Ping

**Comment by minuscorp** [comment]
Is this still an issue?

**Comment by sirghi** [comment]
Hi. Yes, this is still an issue.

**Comment by minuscorp** [comment]
Can you link me an example fastlane project so I can test the same exact environment as you do?

**Comment by sirghi** [comment]
Sorry for taking so long. Here it is, [pwd.zip](https://github.com/fastlane/fastlane/files/4729800/pwd.zip). You'll see that _action_1_ and _action_2_ output different `pwd`'s

**Comment by sirghi** [comment]
Maybe @minuscorp will have a chance to look at it.

**Comment by minuscorp** [comment]
Yeah, sorry for the huge delay, work is pushing hard and have little to no time to church this but I will. 🙇🏻‍♂️

**Comment by minuscorp** [comment]
We have a PR on the go!
