### ISSUE TITLE
when I use spaceship to login my apple account Enter the correct verification code but return 401

### ISSUE THREAD

**Issue by value94** [fastlane/fastlane#16149]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

when I use spaceship to login my apple account Enter the correct verification code but return 401.

send data :

<struct Faraday::Request method=:post, path="https://idmsa.apple.com/appleauth/auth/verify/trusteddevice/securitycode", params={}, headers={"User-Agent"=>"Spaceship 2.143.0", "Content-Type"=>"application/json", "X-Apple-Id-Session-Id"=>"D506105694D974FB0F642F3B4F2192D4", "X-Apple-Widget-Key"=>"e0b80c3bf78523bfe80974d320935bfa30add02e1bff88ec2166c6bd5a706c42", "Accept"=>"application/json", "scnt"=>"008158310f29106cd6713dec8ffa0d25"}, body="{\"securityCode\":{\"code\":\"289682\"}}", options=#<Faraday::RequestOptions timeout=300, open_timeout=300>>

HTTP return:

{:method=>:post, :body=>{"service_errors"=>[{"code"=>"-21669", "title"=>"Incorrect Verification Code", "message"=>"Incorrect verification code.", "suppressDismissal"=>false}], "hasError"=>true}, :url=>#<URI::HTTPS https://idmsa.apple.com/appleauth/auth/verify/trusteddevice/securitycode>, :request=>#<Faraday::RequestOptions timeout=300, open_timeout=300>, :request_headers=>{"User-Agent"=>"Spaceship 2.143.0", "Content-Type"=>"application/json", "X-Apple-Id-Session-Id"=>"D506105694D974FB0F642F3B4F2192D4", "X-Apple-Widget-Key"=>"e0b80c3bf78523bfe80974d320935bfa30add02e1bff88ec2166c6bd5a706c42", "Accept"=>"application/json", "scnt"=>"008158310f29106cd6713dec8ffa0d25", "Cookie"=>"aa=D506105694D974FB0F642F3B4F2192D4; acn01=VDBHD7RPuYvPFUjyzhRy3ZtxKOCCGAANBzhPi/2K; crsc=RvhDOYq6NIfnKKUuFz9zkOC3DulSBjOHCNqC/VM7cvlLzZUCOTC1CoBfm29E7MC/KyA6oR6UpxRrt+Ym1GiYAA0HOI595kI=; dslang=US-EN; site=USA"}, :ssl=>#<Faraday::SSLOptions verify=true>, :response=>#<Faraday::Response:0x000055d633b601c0 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:post @body={"service_errors"=>[{"code"=>"-21669", "title"=>"Incorrect Verification Code", "message"=>"Incorrect verification code.", "suppressDismissal"=>false}], "hasError"=>true} @url=#<URI::HTTPS https://idmsa.apple.com/appleauth/auth/verify/trusteddevice/securitycode> @request=#<Faraday::RequestOptions timeout=300, open_timeout=300> @request_headers={"User-Agent"=>"Spaceship 2.143.0", "Content-Type"=>"application/json", "X-Apple-Id-Session-Id"=>"D506105694D974FB0F642F3B4F2192D4", "X-Apple-Widget-Key"=>"e0b80c3bf78523bfe80974d320935bfa30add02e1bff88ec2166c6bd5a706c42", "Accept"=>"application/json", "scnt"=>"008158310f29106cd6713dec8ffa0d25", "Cookie"=>"aa=D506105694D974FB0F642F3B4F2192D4; acn01=VDBHD7RPuYvPFUjyzhRy3ZtxKOCCGAANBzhPi/2K; crsc=RvhDOYq6NIfnKKUuFz9zkOC3DulSBjOHCNqC/VM7cvlLzZUCOTC1CoBfm29E7MC/KyA6oR6UpxRrt+Ym1GiYAA0HOI595kI=; dslang=US-EN; site=USA"} @ssl=#<Faraday::SSLOptions verify=true> @response=#<Faraday::Response:0x000055d633b601c0 ...> @response_headers={"server"=>"Apple", "date"=>"Tue, 10 Mar 2020 05:55:51 GMT", "content-type"=>"application/json;charset=UTF-8", "transfer-encoding"=>"chunked", "connection"=>"close", "x-apple-i-request-id"=>"f356a8a2-2a6f-42b1-84d3-35c7106f4eaf", "x-frame-options"=>"DENY", "x-content-type-options"=>"nosniff", "x-xss-protection"=>"1; mode=block", "strict-transport-security"=>"max-age=31536000; includeSubDomains", "content-security-policy"=>"default-src *; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.apple.com https://*.cdn-apple.com http://*.apple-mapkit.com https://*.apple-mapkit.com ; object-src 'self' http://*.apple-mapkit.com https://*.apple-mapkit.com; style-src 'unsafe-inline' https://*.apple.com https://*.cdn-apple.com http://*.apple-mapkit.com https://*.apple-mapkit.com ; img-src 'self' data: https://*.apple.com https://*.cdn-apple.com https://*.icloud.com https://*.mzstatic.com http://*.apple-mapkit.com https://*.apple-mapkit.com ; media-src * data:; connect-src 'self' http://*.apple-mapkit.com https://*.apple-mapkit.com;", "x-buildversion"=>"R6-1", "set-cookie"=>"dslang=US-EN; Domain=apple.com; Path=/; Secure; HttpOnly, site=USA; Domain=apple.com; Path=/; Secure; HttpOnly", "pragma"=>"no-cache", "expires"=>"Thu, 01 Jan 1970 00:00:00 GMT", "cache-control"=>"no-cache, no-store, no-store", "x-apple-i-ercd"=>"-21669", "content-language"=>"en-US-x-lvariant-USA", "vary"=>"Accept-Encoding"} @status=400 @reason_phrase="">>, :response_headers=>{"server"=>"Apple", "date"=>"Tue, 10 Mar 2020 05:55:51 GMT", "content-type"=>"application/json;charset=UTF-8", "transfer-encoding"=>"chunked", "connection"=>"close", "x-apple-i-request-id"=>"f356a8a2-2a6f-42b1-84d3-35c7106f4eaf", "x-frame-options"=>"DENY", "x-content-type-options"=>"nosniff", "x-xss-protection"=>"1; mode=block", "strict-transport-security"=>"max-age=31536000; includeSubDomains", "content-security-policy"=>"default-src *; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.apple.com https://*.cdn-apple.com http://*.apple-mapkit.com https://*.apple-mapkit.com ;object-src 'self' http://*.apple-mapkit.com https://*.apple-mapkit.com; style-src 'unsafe-inline' https://*.apple.com https://*.cdn-apple.com http://*.apple-mapkit.com https://*.apple-mapkit.com ; img-src 'self' data: https://*.apple.com https://*.cdn-apple.com https://*.icloud.com https://*.mzstatic.com http://*.apple-mapkit.com https://*.apple-mapkit.com ; media-src * data:; connect-src 'self' http://*.apple-mapkit.com https://*.apple-mapkit.com;", "x-buildversion"=>"R6-1", "set-cookie"=>"dslang=US-EN; Domain=apple.com; Path=/; Secure; HttpOnly, site=USA; Domain=apple.com; Path=/; Secure; HttpOnly", "pragma"=>"no-cache", "expires"=>"Thu, 01 Jan 1970 00:00:00 GMT", "cache-control"=>"no-cache, no-store, no-store", "x-apple-i-ercd"=>"-21669", "content-language"=>"en-US-x-lvariant-USA", "vary"=>"Accept-Encoding"}, :status=>400, :reason_phrase=>""}

##### Command executed

Spaceship::Portal.login(username, pwd)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre>| fastlane | 2.143.0 |
| OS | Linux QZ-A4-011 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Ruby | 2.6.4 |
| Bundler? | false |
| Git | git version 1.8.3.1 |
| Installation Source | ./fastlane |
| Host | \S
Kernel \r on an \m Linux QZ-A4-011 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux (3.10.0-957.el7.x86_64) |
| Ruby Lib Dir | /usr/local/ruby-2.6.4/lib |
| OpenSSL Version | OpenSSL 1.0.2k  26 Jan 2017 |
| Is contained | false |
| Is homebrew | false |
| Is installed via Fabric.app | false |
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key | Value |
| fastlane | 2.143.0 |
| OS | Linux QZ-A4-011 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Ruby | 2.6.4 |
| Bundler? | false |
| Git | git version 1.8.3.1 |
| Installation Source | ./fastlane |
| Host | \S
Kernel \r on an \m Linux QZ-A4-011 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux (3.10.0-957.el7.x86_64) |
| Ruby Lib Dir | /usr/local/ruby-2.6.4/lib |
| OpenSSL Version | OpenSSL 1.0.2k  26 Jan 2017 |
| Is contained | false |
| Is homebrew | false |
| Is installed via Fabric.app | false |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.143.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.14.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.71.1       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.1.2        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.7        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.10.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.0        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-eventstream           | 1.0.3        |
| aws-sigv4                 | 1.1.1        |
| aws-sdk-core              | 2.11.463     |
| aws-sdk-resources         | 2.11.463     |
| aws-sdk                   | 2.11.463     |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.7       |
| rexml                     | 3.1.9        |
| babosa                    | 1.0.3        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
 </pre>
</details>

**Comment by janpio** [comment]
See https://github.com/fastlane/fastlane/issues/16108
