### ISSUE TITLE
Installing Ruby gem 'cocoapods' fails

### ISSUE THREAD

**Issue by krischik** [fastlane/fastlane#16151]
### Question Checklist

- [✓] Updated fastlane to the latest version
- [✓] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [✓] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [✓] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Building with cocoapods / Installing Ruby gem 'cocoapods' fails

#### Question Description

I try to incorporate cocoapods into my fastlane build. Acording to the [documentation][1] that should be as easy as adding a single line to my Fastfile:

```
    cocoapods
```

This should then call `pod install` for me. But that doesn't seem to be the case. Instead of just calling `pod install` the fastlane try's to install cocoapods which then fails:

```
    [16:32:36]: Installing Ruby gem 'cocoapods'...
    Building native extensions.  This could take a while...
    +------------------+-----------------+
    |            Lane Context            |
    +------------------+-----------------+
    | DEFAULT_PLATFORM | ios             |
    | PLATFORM_NAME    | ios             |
    | LANE_NAME        | ios kptapp_TEST |
    +------------------+-----------------+
    [16:32:52]: ERROR: Failed to build gem native extension.

        current directory: /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/ffi-1.12.2/ext/ffi_c
    /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/bin/ruby -r ./siteconf20200309-76244-14k7phf.rb extconf.rb
    checking for ffi.h... *** extconf.rb failed ***
    Could not create Makefile due to some reason, probably lack of necessary
    libraries and/or headers.  Check the mkmf.log file for more details.  You may
    need configuration options.
```

What is particularly strange: cocoapods is already installed:

```
    >which pod                   
    /usr/local/bin/pod
```

No need to install it. As said the documentation doesn't say anything about this. Is there a way to skip the installation and just use the already installed cocoapods?

  [1]: https://docs.fastlane.tools/actions/cocoapods/

**Comment by krischik** [comment]
> It seems like you have not included the output of `fastlane env`

Sorry bot, that contains quite a bit of confidential information. Well, I can offer this sanitised version:

 <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                                |
| --------------------------- | -------------------------------------------------------------------- |
| OS                          | 10.15.3                                                              |
| Ruby                        | 2.2.4                                                                |
| Bundler?                    | false                                                                |
| Git                         | git version 2.25.1                                                   |
| Installation Source         | /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/bin/fastlane |
| Host                        | Mac OS X 10.15.3 (19D76)                                             |
| Ruby Lib Dir                | /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib          |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                                           |
| Is contained                | true                                                                 |
| Is homebrew                 | false                                                                |
| Is installed via Fabric.app | false                                                                |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                          |
| Xcode Version               | 11.3.1                                                               |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.28.3"

default_platform :ios

platform :ios do
  before_all do |lane|
    if lane != :clean
      cocoapods(
	ansi: true,
	clean: false,
	podfile: "./Podfile",
	use_bundle_exec: false,
	verbose: true
      )
    end
  end

  lane :clean do
    cocoapods(
      ansi: true,
      clean: true,
      podfile: "./Podfile", 
      use_bundle_exec: false,
      verbose: true
    )
    sh("rm", "-r", "Build")
  end

end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
```
</details>

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.28.3  | 💥 Check failed |


### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| activesupport             | 4.2.11.1     |
| addressable               | 2.5.1        |
| algoliasearch             | 1.27.1       |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.4        |
| concurrent-ruby           | 1.1.6        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| fuzzy_match               | 2.0.4        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.9.28       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.9.5        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nap                       | 1.1.0        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.6        |
| tty-screen                | 0.5.0        |
| tzinfo                    | 1.2.6        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.4        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>


*generated on:* **2020-03-10**
</details>

**Comment by krischik** [comment]
Noted something interesting. `fastlane env` says:

```
| Key                         | Value                                                                |
| --------------------------- | -------------------------------------------------------------------- |
| Ruby                        | 2.2.4                                                                |
```

But:

```
>ruby --version
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]
```

Looks like fastlane is using the wrong ruby.

**Comment by janpio** [comment]
What command and lane are you running?
What is the full output?

This could influence what is available or not in the context of fastlane, and also define the ruby version.

**Comment by krischik** [comment]
> What command and lane are you running?

The name of the lane is confidential as it contains the project name.
But does it matter? The build fails in the `before_all` and never actually reaches the lane.

> What is the full output?

I can't give your the full output as it contains confidential informations. So all I can only offer a sanitised output:

<details>

```
[11:49:50]: [32m-------------------------------------------------[0m
[11:49:50]: [32m--- Step: Verifying required fastlane version ---[0m
[11:49:50]: [32m-------------------------------------------------[0m
[11:49:50]: Your fastlane version 2.28.3 matches the minimum requirement of 2.28.3  ✅
[11:49:50]: [32m------------------------------[0m
[11:49:50]: [32m--- Step: default_platform ---[0m
[11:49:50]: [32m------------------------------[0m
[11:49:50]: [33mPlatform 'deploy' is not officially supported. Currently supported platforms are [:ios, :mac, :android].[0m
[11:49:50]: [32mDriving the lane 'ios …' 🚀[0m
[11:49:50]: [32m-----------------------[0m
[11:49:50]: [32m--- Step: cocoapods ---[0m
[11:49:50]: [32m-----------------------[0m
[11:49:50]: [33mInstalling Ruby gem 'cocoapods'...[0m
Building native extensions.  This could take a while...
+------------------+-----------------+
|            [33mLane Context[0m            |
+------------------+-----------------+
| DEFAULT_PLATFORM | ios             |
| PLATFORM_NAME    | ios             |
| LANE_NAME        | ios … |
+------------------+-----------------+
[11:50:01]: [31mERROR: Failed to build gem native extension.

    current directory: /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/ffi-1.12.2/ext/ffi_c
/usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/bin/ruby -r ./siteconf20200311-46926-1n2ugca.rb extconf.rb
checking for ffi.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/bin/$(RUBY_BASE_NAME)
	--with-ffi_c-dir
	--without-ffi_c-dir
	--with-ffi_c-include
	--without-ffi_c-include=${ffi_c-dir}/include
	--with-ffi_c-lib
	--without-ffi_c-lib=${ffi_c-dir}/lib
	--enable-system-libffi
	--disable-system-libffi
	--with-libffi-config
	--without-libffi-config
	--with-pkg-config
	--without-pkg-config
/usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/2.2.0/mkmf.rb:587:in `try_cpp'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/2.2.0/mkmf.rb:1060:in `block in have_header'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/2.2.0/mkmf.rb:321:in `open'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/2.2.0/mkmf.rb:321:in `open'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/2.2.0/mkmf.rb:1059:in `have_header'
	from extconf.rb:10:in `system_libffi_usable?'
	from extconf.rb:34:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/ffi-1.12.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/ffi-1.12.2 for inspection.
Results logged to /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/ffi-1.12.2/gem_make.out
[0m

+------+---------------------+-------------+
|             [32mfastlane summary[0m             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying required  | 0           |
|      | fastlane version    |             |
| 2    | default_platform    | 0           |
| 💥   | [31mcocoapods[0m           | 10          |
+------+---------------------+-------------+

[11:50:01]: [31mfastlane finished with errors[0m

Looking for related GitHub issues on fastlane/fastlane...

/usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/ext/builder.rb:92:in `run': [31m[!] ERROR: Failed to build gem native extension. (Gem::Ext::BuildError)

    current directory: /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/ffi-1.12.2/ext/ffi_c
/usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/bin/ruby -r ./siteconf20200311-46926-1n2ugca.rb extconf.rb
checking for ffi.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/bin/$(RUBY_BASE_NAME)
	--with-ffi_c-dir
	--without-ffi_c-dir
	--with-ffi_c-include
	--without-ffi_c-include=${ffi_c-dir}/include
	--with-ffi_c-lib
	--without-ffi_c-lib=${ffi_c-dir}/lib
	--enable-system-libffi
	--disable-system-libffi
	--with-libffi-config
	--without-libffi-config
	--with-pkg-config
	--without-pkg-config
/usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/2.2.0/mkmf.rb:587:in `try_cpp'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/2.2.0/mkmf.rb:1060:in `block in have_header'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/2.2.0/mkmf.rb:321:in `open'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/2.2.0/mkmf.rb:321:in `open'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/2.2.0/mkmf.rb:1059:in `have_header'
	from extconf.rb:10:in `system_libffi_usable?'
	from extconf.rb:34:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/ffi-1.12.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/ffi-1.12.2 for inspection.
Results logged to /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/ffi-1.12.2/gem_make.out
[0m
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/ext/ext_conf_builder.rb:48:in `block in build'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/2.2.0/tempfile.rb:319:in `open'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/ext/ext_conf_builder.rb:31:in `build'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/ext/builder.rb:164:in `block (2 levels) in build_extension'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/ext/builder.rb:163:in `chdir'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/ext/builder.rb:163:in `block in build_extension'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/ext/builder.rb:162:in `build_extension'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/ext/builder.rb:201:in `block in build_extensions'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/ext/builder.rb:198:in `each'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/ext/builder.rb:198:in `build_extensions'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/installer.rb:748:in `build_extensions'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/installer.rb:297:in `install'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/resolver/specification.rb:97:in `install'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:166:in `block in install'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:156:in `each'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:156:in `install'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:250:in `install_gem'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/fastlane_require.rb:36:in `install_gem_if_needed'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/helper/gem_helper.rb:7:in `verify_gem!'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/actions/cocoapods.rb:5:in `run'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:226:in `chdir'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:22:in `block (2 levels) in parsing_binding'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:270:in `call'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:270:in `execute_flow_block'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:46:in `block in execute'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:40:in `run!'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/bin/fastlane:20:in `<top (required)>'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/bin/fastlane:22:in `load'
	from /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/bin/fastlane:22:in `<main>'
```

</details>

**Comment by janpio** [comment]
Are you calling `bundle exec fastlane ...` or `fastlane ...`?

**Comment by Kaspik** [comment]
`current directory: /usr/local/Caskroom/fastlane/latest/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems` - I don't think Ruby 2.2 is supported.

**Comment by krischik** [comment]
> Are you calling `bundle exec fastlane ...` or `fastlane ...`?

Just:

```
fastlane "ios" "…"
```

>  I don't think Ruby 2.2 is supported.

That's my suspicion as well. But i didn't install that old version of ruby. It's in the `fastlane_lib` directory — so it came with fastlane itself. Why would fastlane bundle an to old ruby?

Is there a an environment variable to specify which ruby to use.

As a side note: I which developers would stop bundling language runtimes.  I must have a dozen java runtimes on my computer alone.

**Comment by janpio** [comment]
Fastlane is not bundling Ruby 2.2, something is funky with your fastlane installation. Can you maybe try reinstalling the global fastlane by following the installation instructions (and not use Homebrew or similar)? That might fix the ruby thing, and thus also the other issue.

**Comment by krischik** [comment]
Before we march off into red herring territory: I only have one problem. Fastlane without cocoapods works just fine. Both the HomeBrew as well as the MacPorts.

No problems here.

Still, I'm going to try out alternative installations.

## Option 1: Using RubyGems

I'll take it you want me use this this documentation:

https://docs.fastlane.tools/getting-started/ios/setup

And install with this command (expanded for emphasis):

```
sudo /usr/bin/gem install --no-document --verbose fastlane
```

That doesn't work any more more with Catalina:

```
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /usr/bin directory.
```

Homebrew and MacPorts are the only installation options which still work and you might want to update the documentation.

## Option 2: Using gem from Homebrew

Since /usr/bin can't be written too any more I also tried to install fastlane with gem from homebrew:

```
/usr/local/opt/ruby/bin/gem install --no-document --verbose fastlane 
````

I can then build using `/usr/local/lib/ruby/gems/2.7.0/bin/fastlane` which does produce different  unrelated errors. So that might actually work once I sorted them out.

Of course that option of installation isn't mentioned on the website. 

## Final thoughts:

As said, homebrew installation is is one of the two suggested installations methods and the only suggested one which works with Catalina.

I have stumbled across the the installation script in my research:

https://github.com/Homebrew/homebrew-cask/blob/master/Casks/fastlane.rb

Ant it seems that it installs `https://fastlane.tools/fastlane.zip` form the fastlane website.

I downloaded that zip and had a look inside and it does include the ruby 2.2.

Since `fastlane.zip` has no version number I also checked the file date: **“2017-04-24 09:19:46”** — That zip is three years old and is probably in need of an update.

Or alternatively one could delete the outdated instruction. 

PS: As far as I'm concerned this bug can be closed. However I' not doing so as the documentation really needs to be updated.
