### ISSUE TITLE
google_play_track_version_codes notFound: Track not found

### ISSUE THREAD

**Issue by jsaadep** [fastlane/fastlane#16159]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

CI and local fastlane failed, it was working before, today it started reporting 
notFound: Track not found
this is specific to production and beta. works fine with internal

##### Command executed

This works
internal_version_codes = google_play_track_version_codes(package_name: "com.***.l***",track: "internal")

This fails:
  production_version_codes = google_play_track_version_codes(package_name: "com.***.***",track: "production")

This also fails:
  beta_version_codes = google_play_track_version_codes(package_name: "com.***.***",track: "beta")

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> INFO [2020-03-11 15:34:28.43]: -----------------------------
INFO [2020-03-11 15:34:28.43]: --- Step: update_fastlane ---
INFO [2020-03-11 15:34:28.43]: -----------------------------
INFO [2020-03-11 15:34:28.43]: Looking for updates for fastlane...
INFO [2020-03-11 15:34:34.06]: Nothing to update ✅
INFO [2020-03-11 15:34:34.06]: ------------------------------
INFO [2020-03-11 15:34:34.06]: --- Step: default_platform ---
INFO [2020-03-11 15:34:34.06]: ------------------------------
INFO [2020-03-11 15:34:34.06]: Driving the lane 'android send_bundle_to_google' 🚀
INFO [2020-03-11 15:34:34.07]: ---------------------------------------------
INFO [2020-03-11 15:34:34.07]: --- Step: google_play_track_version_codes ---
INFO [2020-03-11 15:34:34.07]: ---------------------------------------------
DEBUG [2020-03-11 15:34:34.08]: Fetching a new access token from Google...
INFO [2020-03-11 15:34:36.69]: Found '54' version codes in track 'internal'
INFO [2020-03-11 15:34:36.69]: ---------------------------------------------
INFO [2020-03-11 15:34:36.69]: --- Step: google_play_track_version_codes ---
INFO [2020-03-11 15:34:36.69]: ---------------------------------------------
DEBUG [2020-03-11 15:34:36.69]: Fetching a new access token from Google...
WARN [2020-03-11 15:34:39.04]: Lane Context:
INFO [2020-03-11 15:34:39.04]: {:DEFAULT_PLATFORM=>:android, :PLATFORM_NAME=>:android, :LANE_NAME=>"android send_bundle_to_google"}
ERROR [2020-03-11 15:34:39.04]: notFound: Track not found: production.
INFO [2020-03-11 15:34:39.04]: Successfully generated documentation at path '***/README.md'
DEBUG [2020-03-11 15:34:39.05]: All plugins are up to date
ERROR [2020-03-11 15:34:39.05]: fastlane finished with errors
DEBUG [2020-03-11 15:34:39.56]: All plugins are up to date</pre>
</details>

**Comment by androidseb** [comment]
I've run into this issue myself and I made a PR to fix it:
https://github.com/fastlane/fastlane/pull/16161

In the meantime, I added a workaround in my Fastfile:
```
lane :get_google_play_track_version_codes do |options|
  track_version_codes = []
  begin
    track_version_codes = google_play_track_version_codes(
      package_name: options[:package_name],
      track: options[:track],
      json_key: options[:json_key],
    )
  rescue => gptvcError
    puts gptvcError.to_s
    if (gptvcError.class != Google::Apis::ClientError || gptvcError.status_code != 404)
      raise gptvcError
    end
  end
  track_version_codes
end
```

Simply call get_google_play_track_version_codes instead of google_play_track_version_codes and it should work for now, although it will report a catched error during the lane execution.

I hope this helps!

**Comment by jsaadep** [comment]
@androidseb Thank you for the workaround until PR is merged
