### ISSUE TITLE
upload_to_play_store_internal_app_sharing not sending bundle

### ISSUE THREAD

**Issue by romainbraun** [fastlane/fastlane#16154]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When running
`fastlane run upload_to_play_store_internal_app_sharing aab:"path/to/bundle.aab" json_key:"path/to/key.json"` everything seems to run smoothly and the command returns
`Successfully uploaded AAB to Internal App Sharing URL: https://play.google.com/apps/test/[...]`
However following the link returns a 404, and visiting the internal app sharing page in the play console doesn't show any uploaded build.

Uploading builds to internal lanes works fine, and uploading builds to internal app sharing manually through the play console works fine too.

The fastlane user has a release manager permissions level.

##### Command executed

`fastlane run upload_to_play_store_internal_app_sharing aab:"android/app/build/outputs/bundle/release/app-release.aab" json_key:"android/play_console.json"`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [[✔] 🚀
+----------------------------+---------+-------------------------------------------------------------------------------------+
|                                                        Used plugins                                                        |
+----------------------------+---------+-------------------------------------------------------------------------------------+
| Plugin                     | Version | Action                                                                              |
+----------------------------+---------+-------------------------------------------------------------------------------------+
| fastlane-plugin-versioning | 0.4.0   | get_version_number_from_git_branch increment_build_number_in_xcodeproj              |
|                            |         | get_version_number_from_plist get_build_number_from_plist ci_build_number           |
|                            |         | get_version_number_from_xcodeproj increment_version_number_in_xcodeproj             |
|                            |         | increment_version_number_in_plist get_app_store_version_number get_info_plist_path  |
|                            |         | get_build_number_from_xcodeproj increment_build_number_in_plist                     |
+----------------------------+---------+-------------------------------------------------------------------------------------+

[12:38:56]: -------------------------------------------------------
[12:38:56]: --- Step: upload_to_play_store_internal_app_sharing ---
[12:38:56]: -------------------------------------------------------
[12:38:56]: To not be asked about this value, you can specify it using 'package_name'
[12:38:56]: The package name of the application to use: [redacted]
[12:44:00]: Successfully uploaded AAB to Internal App Sharing URL: https://play.google.com/apps/test/[redacted]
[12:44:00]: Result: https://play.google.com/apps/test/[redacted]
+------------+--------------+----------------+
|          Plugin updates available          |
+------------+--------------+----------------+
| Plugin     | Your Version | Latest Version |
+------------+--------------+----------------+
| versioning | 0.4.0        | 0.4.2          |
+------------+--------------+----------------+
[12:44:00]: To update all plugins, just run
[12:44:00]: $ bundle exec fastlane update_plugins </pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.23.0                          |
| Installation Source         | ~/.rvm/rubies/ruby-2.6.3/bin/fastlane       |
| Host                        | Mac OS X 10.14.6 (18G87)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.3/lib                |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.2.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
MY_APP_ID = "[App ID]"
MY_APP_STAGING_ID = "[App ID]"
MY_PROFILE = "match AppStore [App ID]"
MY_STAGING_PROFILE = "match AppStore [App ID]"
MY_TEAM = "[Team ID]"

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "..."
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a staging build to Testflight"
  lane :staging do
    setup_circle_ci
    match(
      app_identifier: MY_APP_STAGING_ID,
      type: "appstore",
      git_url: "[certificates URL]",
      readonly: true
    )
    # set env vars
    set_info_plist_value(
      path: "ios/App/Info.plist",
      key: "CFBundleDisplayName",
      value: "App Staging"
    )
    build_no = ENV["CIRCLE_BUILD_NUM"]
    increment_build_number(
      build_number: build_no,
      xcodeproj: "ios/App.xcodeproj",
    )
    settings_to_override = {
      "-UseNewBuildSystem": "NO",
      :BUNDLE_IDENTIFIER => MY_APP_STAGING_ID,
      :PROVISIONING_PROFILE_SPECIFIER => MY_STAGING_PROFILE,
      :DEVELOPMENT_TEAM => MY_TEAM
    }
    gym(
      workspace: "ios/App.xcworkspace",
      scheme: "App",
      sdk: "iphoneos13.2",
      clean: true,
      silent: false,
      xcargs: settings_to_override,
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          MY_APP_STAGING_ID => MY_STAGING_PROFILE
       }
      }
    )
    pilot(
      skip_waiting_for_build_processing: true
    )
    slack(
     message: "New staging build uploaded to TestFlight (Staging) - build " + build_no.to_s
    )
  end

  desc "Submit a new production Build to TestFlight"
  lane :production do |options|
    setup_circle_ci
    match(
      app_identifier: MY_APP_ID,
      type: "appstore",
      git_url: "[Certificates URL]",
      readonly: true
    )
    update_app_identifier(
      xcodeproj: "ios/App.xcodeproj",
      plist_path: "App/Info.plist",
      app_identifier: MY_APP_ID
    )
    build_no = ENV["CIRCLE_BUILD_NUM"]
    increment_build_number(
      build_number: build_no,
      xcodeproj: "ios/App.xcodeproj"
    )
    increment_version_number_in_plist(
      bump_type: options[:build_type],
      xcodeproj: "ios/App.xcodeproj",
      target: "App"
    )
    settings_to_override = {
      "-UseNewBuildSystem": "NO",
      :BUNDLE_IDENTIFIER => MY_APP_ID,
      :PROVISIONING_PROFILE_SPECIFIER => MY_PROFILE,
      :DEVELOPMENT_TEAM => MY_TEAM
    }
    gym(
      workspace: "ios/App.xcworkspace",
      scheme: "App",
      sdk: "iphoneos13.2",
      clean: true,
      silent: false,
      xcargs: settings_to_override,
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          MY_APP_ID => MY_PROFILE,
        }
      }
    )
    pilot(
      skip_waiting_for_build_processing: true
    )
    branch_name = ENV["CIRCLE_BRANCH"]
    sh("git", "branch", "--set-upstream-to=origin/#{branch_name}")
    git_pull
    git_commit(path: "./ios/**/*.plist", message: "Bump ios version [ci skip]", skip_git_hooks: true)
    push_to_git_remote
    slack(
     message: "New app update uploaded to TestFlight (Production) - build " + build_no.to_s
    )
  end
end

platform :android do
  before_all do
    ENV["SLACK_URL"] = "[Slack URL]"
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a staging build to the Play Console"
  lane :staging do
    build_no = ENV["CIRCLE_BUILD_NUM"]
    gradle(task: 'clean', project_dir: 'android/')

    gradle(task: 'bundle', build_type: 'Release', project_dir: 'android/')

    # supply(track: 'internal', track_promote_to: 'internal', json_key: 'android/play_console.json', package_name: '[Package ID]')

    download_link = upload_to_play_store_internal_app_sharing(package_name: '[Package ID]', json_key: 'android/play_console.json')
    
    slack(
     message: "New staging build uploaded to the Play Store (Internal) - build " + build_no.to_s,
     attachment_properties: {
       title: "Click to download build",
       title_link: download_link
     }
    )
  end

  desc "Increments build number and send a prod build to the play console"
  lane :production do |options|
    build_no = ENV["CIRCLE_BUILD_NUM"]
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'bundle', build_type: 'Release', project_dir: 'android/', flags: "-Pbuild_type=" + options[:build_type])
    supply(track: 'beta', track_promote_to: 'beta', json_key: 'android/play_console.json', package_name: '[Package ID]')
    branch_name = ENV["CIRCLE_BRANCH"]
    sh("git", "branch", "--set-upstream-to=origin/#{branch_name}")
    git_pull
    git_commit(path: ['./android/gradle.properties'], message: 'Bump android version code and name [ci skip]')
    push_to_git_remote
    slack(
     message: "New prod build uploaded to the Play Store (Beta) - build " + build_no.to_s
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier "" # The bundle identifier of your app
apple_id "" # Your Apple email address
team_id "" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
for_platform :ios do
  for_lane :prod do
    app_identifier ''
  end
  for_lane :staging do
    app_identifier ''
  end
end


```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.143.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status      |
| -------------------------- | ------- | ------------------ |
| fastlane-plugin-versioning | 0.4.0   | 🚫 Update available |

<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version      |
| -------------------------- | ------------ |
| did_you_mean               | 1.3.1        |
| executable-hooks           | 1.6.0        |
| bundler-unload             | 1.0.2        |
| rubygems-bundler           | 1.4.5        |
| bundler                    | 2.0.2        |
| CFPropertyList             | 3.0.2        |
| public_suffix              | 2.0.5        |
| addressable                | 2.7.0        |
| atomos                     | 0.1.3        |
| aws-eventstream            | 1.0.3        |
| aws-sigv4                  | 1.1.1        |
| jmespath                   | 1.4.0        |
| aws-sdk-core               | 2.11.460     |
| aws-sdk-resources          | 2.11.460     |
| aws-sdk                    | 2.11.460     |
| babosa                     | 1.0.3        |
| claide                     | 1.0.3        |
| colored2                   | 3.1.2        |
| cork                       | 0.3.0        |
| nap                        | 1.1.0        |
| open4                      | 1.3.4        |
| claide-plugins             | 0.9.2        |
| colored                    | 1.2          |
| highline                   | 1.7.10       |
| commander-fastlane         | 4.4.6        |
| multipart-post             | 2.0.0        |
| faraday                    | 0.17.3       |
| faraday-http-cache         | 2.0.0        |
| git                        | 1.5.0        |
| kramdown                   | 2.1.0        |
| kramdown-parser-gfm        | 1.1.0        |
| no_proxy_fix               | 0.1.2        |
| sawyer                     | 0.8.2        |
| octokit                    | 4.14.0       |
| unicode-display_width      | 1.6.1        |
| terminal-table             | 1.8.0        |
| danger                     | 6.1.0        |
| dotenv                     | 2.7.5        |
| emoji_regex                | 1.0.1        |
| excon                      | 0.72.0       |
| unf_ext                    | 0.0.7.6      |
| unf                        | 0.1.4        |
| domain_name                | 0.5.20190701 |
| http-cookie                | 1.0.3        |
| faraday-cookie_jar         | 0.0.6        |
| faraday_middleware         | 0.13.1       |
| fastimage                  | 2.1.7        |
| gh_inspector               | 1.1.3        |
| jwt                        | 2.1.0        |
| memoist                    | 0.16.2       |
| multi_json                 | 1.14.1       |
| os                         | 1.0.1        |
| signet                     | 0.13.0       |
| googleauth                 | 0.11.0       |
| httpclient                 | 2.8.3        |
| mini_mime                  | 1.0.2        |
| declarative                | 0.0.10       |
| declarative-option         | 0.1.0        |
| uber                       | 0.1.0        |
| representable              | 3.0.4        |
| retriable                  | 3.1.2        |
| google-api-client          | 0.36.4       |
| digest-crc                 | 0.5.1        |
| google-cloud-env           | 1.3.1        |
| google-cloud-errors        | 1.0.0        |
| google-cloud-core          | 1.5.0        |
| google-cloud-storage       | 1.25.1       |
| json                       | 2.3.0        |
| mini_magick                | 4.10.1       |
| multi_xml                  | 0.6.0        |
| plist                      | 3.5.0        |
| rubyzip                    | 1.3.0        |
| security                   | 0.1.3        |
| naturally                  | 2.2.0        |
| simctl                     | 1.6.8        |
| slack-notifier             | 2.3.2        |
| terminal-notifier          | 2.0.0        |
| tty-screen                 | 0.7.1        |
| tty-cursor                 | 0.7.1        |
| tty-spinner                | 0.9.3        |
| word_wrap                  | 1.0.0        |
| nanaimo                    | 0.2.6        |
| xcodeproj                  | 1.15.0       |
| rouge                      | 2.0.7        |
| xcpretty                   | 0.3.0        |
| xcpretty-travis-formatter  | 1.0.0        |
| danger-device_grid         | 0.2.0        |
| fastlane-plugin-versioning | 0.4.0        |
</details>

*generated on:* **2020-03-10**
</details>

**Comment by ramirosilvajumia** [comment]
Hi. I'm having the same exact problem. Did you found a solution? Thanks

**Comment by MaoChhaya** [comment]
@andrewhavens Could you please check this action? I have an issue on this action too everything is ok, but the following link is error 404

**Comment by andrewhavens** [comment]
@MaoChhaya We’ve been using this action to successfully upload APKs (not bundles) so I’m not sure if anything needs to change specific to bundles.

**Comment by ramirosilva1992** [comment]
@MaoChhaya @andrewhavens we have been using this action for a while on our Jenkins job and we upload a bundle. The funny thing is, the url on the Jenkins console opens a 404 page, but, since we are sending automatically that url to the team slack, that url (opened from slack) works. Go figure!

**Comment by MaoChhaya** [comment]
Thank @andrewhavens and @ramirosilva1992 it works file both APKs and AAB(bundles). I didn't configure user access to the internal sharing app that's why I got status 404.

**Comment by SanjuSona-19** [comment]
@andrewhavens <https://github.com/andrewhavens>   @ramirosilva1992
<https://github.com/ramirosilva1992> Respected sir,
Since one week i am working in fastlane screengrab, i have worked with most
of the tools in fastlane like match, deliver, supply, etc., but this
screengrab is bothering me alot. I have followed the complete fastlane
screengrab documentation and also the github issues but i can't solve my
screengrab issue. I have raised the issue in github, the link is as
follows, I hope you will help me to solve this problem as soon as possible.
i will be waiting for your reply sir, please do consider my request

https://github.com/fastlane/fastlane/issues/16580

In advance thankyou sir

Regards
Sanjana V


In advance thankyou sir

**Comment by huxaiphaer** [comment]
Am still facing the same issue.
