### ISSUE TITLE
How to increment version number according to last approved ios version

### ISSUE THREAD

**Issue by igorek9191** [fastlane/fastlane#16150]
I know that there is `increment_version_number ` lane, but it increments version that is placed in `Info.plist` file. It means that after every uploading to TestFlight developer has to update `Info.plist` file with new version.

Also, Fastlane has `commit_version_bump` lane, which is updating `Info.plist` locally, but I also need to update remote repo, because I'm using CI/CD pipeline to build app, which is triggered by pushing new code to a branch.  I'm afraid that it could be a situation of infinity triggering of build pipeline.

So, how I could make +1 (to last digit) to the last approved version in TestFlight, which is currently 2.4.1 ?

**Comment by romainbraun** [comment]
This is what I do to increment and push:

```
    build_no = ENV["CIRCLE_BUILD_NUM"]
    increment_build_number(
      build_number: build_no,
      xcodeproj: "ios/App.xcodeproj"
    )
    increment_version_number_in_plist(
      bump_type: options[:build_type],
      xcodeproj: "ios/App.xcodeproj",
      target: "App"
    )
    branch_name = ENV["CIRCLE_BRANCH"]
    sh("git", "branch", "--set-upstream-to=origin/#{branch_name}")
    git_pull
    git_commit(path: "./ios/**/*.plist", message: "Bump ios version [ci skip]", skip_git_hooks: true)
    push_to_git_remote
```

Using [ci skip] in the commit message prevents the push from triggering a new build (On CircleCI)

**Comment by Katsz** [comment]
Working-ish increment may be by fetching last TF version via `Spaceship::ConnectAPI.get_builds`, but if build was just sent it will not be visible for few minutes in TF api.
