### ISSUE TITLE
[match] Explicit certificate id for match import

### ISSUE THREAD

**Issue by stefanomondino** [fastlane/fastlane#16152]
#### Motivation Behind Feature
We develop apps for different organizations. 
Sometimes, they do not grant us access to their developer portals, but only provide us distribution certificates and provisioning profiles directly.
This forces us to manually install certificates on every machine that can run fastlane (we have a multi-node CI Jenkins environment)
`match import` requires access to Apple Developer Portal to lookup proper certificate id, and it's not working for our scenario
#### Feature Description

`match import` could accept an optional parameter containing the certificate id (`cert_id`) .
If `cert_id` is provided, the whole communication with the Developer Portal can be skipped (as it seems to be used only to retrieve a valid certificate id and nothing more) and the certificate can be imported into git

Drawbacks: user can provide wrong certificate id. 

#### Alternatives or Workarounds

The only alternative I see is to manually run commands through the ruby console to manually encrypt certificates. Surely not a straightforward approach.
Otherwise, we have to go with manual installation on every Jenkins node.

**Comment by janpio** [comment]
Sounds like a reasonable request. This is the code active there:
https://github.com/fastlane/fastlane/blob/ad1cf01e24191db83d45d1187b0ce3e1c025fe75/match/lib/match/importer.rb#L66-L75

You can e.g. search for `params[:storage_mode]` to get an idea where the option has to be added everywhere and how, then you basically put all this code behind a conditional of that value not existing (and probably output a stern warning to the developer that they should know what they are doing here, or stuff will break).

**Comment by stefanomondino** [comment]
@janpio there's a second problem, however: using this approach is reasonable but useful if you're not able to include (and encrypt) a provisioning profile tied to the certificate you're importing.
I've put together a custom action by copypasting the core `import` method from match and manually editing the parts I needed.
```ruby
class CustomImportAction < Action
      def self.run(params)
        # fastlane will take care of reading in the parameter and fetching the environment variable:
        #        UI.message "Parameter API Token: #{params[:api_token]}"
        cert_path = params[:cert_path]
        p12_path = params[:p12_path]
        profile_path = params[:profile_path]
        matching_cert_id = params[:matching_cert_id]
        # Get and verify cert and p12 path
        cert_path ||= UI.input("Certificate (.cer) path:")
        p12_path ||= UI.input("Private key (.p12) path:")
        profile_path ||= UI.input("Provisioning Profile (.mobileprovision) path:")
        matching_cert_id ||= UI.input("Certificate id:")
        cert_path = File.absolute_path(cert_path)
        p12_path = File.absolute_path(p12_path)
        profile_path = File.absolute_path(profile_path)

        UI.user_error!("Certificate does not exist at path: #{cert_path}") unless File.exist?(cert_path)
        UI.user_error!("Private key does not exist at path: #{p12_path}") unless File.exist?(p12_path)
        UI.user_error!("Provisioning profile does not exist at path: #{profile_path}") unless File.exist?(profile_path)
        # Base64 encode contents to find match from API to find a cert ID
        cert_contents_base_64 = Base64.strict_encode64(File.open(cert_path).read)

        # Storage
        storage = Match::Storage.for_mode(params[:storage_mode], {
          git_url: params[:git_url],
          shallow_clone: params[:shallow_clone],
          skip_docs: params[:skip_docs],
          git_branch: params[:git_branch],
          git_full_name: params[:git_full_name],
          git_user_email: params[:git_user_email],
          clone_branch_directly: params[:clone_branch_directly],
          type: params[:type].to_s,
          platform: params[:platform].to_s,
          google_cloud_bucket_name: params[:google_cloud_bucket_name].to_s,
          google_cloud_keys_file: params[:google_cloud_keys_file].to_s,
          google_cloud_project_id: params[:google_cloud_project_id].to_s,
          readonly: params[:readonly],
          username: params[:username],
          team_id: params[:team_id],
          team_name: params[:team_name],
        })
        storage.download

        # Encryption
        encryption = Match::Encryption.for_storage_mode(params[:storage_mode], {
          git_url: params[:git_url],
          working_directory: storage.working_directory,
        })
        encryption.decrypt_files if encryption
        UI.success("Repo is at: '#{storage.working_directory}'")

        # Map match type into Spaceship::ConnectAPI::Certificate::CertificateType
        cert_type = Match.cert_type_sym(params[:type])

        case cert_type
        when :development
          certificate_type = Spaceship::ConnectAPI::Certificate::CertificateType::IOS_DEVELOPMENT + "," + Spaceship::ConnectAPI::Certificate::CertificateType::DEVELOPMENT
        when :distribution, :enterprise
          certificate_type = Spaceship::ConnectAPI::Certificate::CertificateType::IOS_DISTRIBUTION + "," + Spaceship::ConnectAPI::Certificate::CertificateType::DISTRIBUTION
        else
          UI.user_error!("Cert type '#{cert_type}' is not supported")
        end

        output_dir = File.join(storage.prefixed_working_directory, "certs", cert_type.to_s)

        # Make dir if doesn't exist
        FileUtils.mkdir_p(output_dir)
        dest_cert_path = File.join(output_dir, "#{matching_cert_id}.cer")
        dest_p12_path = File.join(output_dir, "#{matching_cert_id}.p12")

        output_dir = File.join(storage.prefixed_working_directory, "profiles", params[:type].to_s)
        dest_profile_path = File.join(output_dir, "#{profile_type_name(params[:type].to_s)}_#{params[:app_identifier].first.to_s}.mobileprovision")

        # Copy files
        IO.copy_stream(cert_path, dest_cert_path)
        IO.copy_stream(p12_path, dest_p12_path)
        IO.copy_stream(profile_path, dest_profile_path)
        files_to_commit = [dest_cert_path, dest_p12_path, dest_profile_path]

        # Encrypt and commit
        encryption.encrypt_files if encryption
        storage.save_changes!(files_to_commit: files_to_commit)
      end
```

**Comment by janpio** [comment]
> there's a second problem, however: using this approach is reasonable but useful if you're not able to include (and encrypt) a provisioning profile tied to the certificate you're importing

Sorry, did not get that. Can you elaborate please?

**Comment by stefanomondino** [comment]
@janpio sorry for bad explanation :D 

Having the `match import` action available helps developers who already have created distribution certificates to encrypt and import into git and use match from that point on, since there's a strict limit on new certificates creation.
`match import` doesn't have (yet) features for importing **provisioning profiles** because it assumes you always have credentials to authenticate and communicate with Apple's Developer Portal: once you have imported your certificate, classic `match` will create a provisioning profile for you (linked to the certificate you've just imported).

I've suggested a (hopefully) good feature but didn't realized it's incomplete: importing a certificate bypassing the Developer Portal is surely useful but completely pointless if, once you're actually *running* `match`, you don't have any provisioning profile in your git: how are you supposed to sign your app without it? `match` would fail trying to create it since it wouldn't be able to connect to the portal. 

It would work if match, **in readonly mode**, would be able to simply checkout from git certificates **and** provisioning profile, that's what my (naive) script is doing.

**Comment by stefanomondino** [comment]
> there's a second problem, however: using this approach is reasonable but useful if you're not able to include (and encrypt) a provisioning profile tied to the certificate you're importing

I meant USELESS, not useful :D sorry

**Comment by janpio** [comment]
I am pretty sure I _used_ to know all this - thanks for reminding me.

You would want an extended `import` feature where you can also supply the provisioning profile then?

**Comment by stefanomondino** [comment]
@janpio yes, in my opinion it would be useful to use match with external provided certificates without having access to developer portal.
I'd like to also point out that this is a really common scenario for a digital agency dealing with external partners and clients (like the one I'm working at), probably less common in product companies.

To do so, `match import` would need:
1) `certificate_id`: I didn't found any documentation about its real purpose, but current importer is using it to doublecheck certificate with the dev portal and to name the actual certificate (and p12) inside the repository. 
2) `provisioning_profile_path`: the path of the provisioning profile to import.

The custom action I've provided few comments ago already does this, but I got rid of the Spaceship part connecting to the app store.

**Comment by janpio** [comment]
> 1. I didn't found any documentation about its real purpose, but current importer is using it to doublecheck certificate with the dev portal and to name the actual certificate (and p12) inside the repository.

That is exactly what it is used for - match expects the files to be named that way in the repository, so it used it to rename whatever you provide.

I haven't used `import` for quite some time, does it generate the provisioning profile when you use it already or only later if you try to use `match` to provide certificates etc?

**Comment by stefanomondino** [comment]
@janpio no, it doesn't generate any provisioning. It's only importing the certificate and that's it.

Later on, with `match`, provisioning profiles are generated unless a `readonly` flag is provided (and that's what I would actually like to accomplish :) ).

[this](https://github.com/stefanomondino/Jenkins-Murray/blob/master/Jenkins/jenkins/fastlane/actions/custom_import.rb) is the custom action I've put together, to be used with this command

```
 bundle exec fastlane run custom_import --verbose git_url:"<git_url>" type:"appstore" git_branch:"master" app_identifier:"<your_app_id>" cert_path:"Signing/Certificate.cer" p12_path:"Signing/Certificate.p12" profile_path:"Signing/Profile.mobileprovision" matching_cert_id:"<some_cert_id>"
```

**Comment by janpio** [comment]
Would maybe a second command to "import provisioning profile" be useful here?

**Comment by stefanomondino** [comment]
@janpio yes, it could work, as long as the original `import` command has an option to skip validation with apple by providing explicit cert_id when needed.

**Comment by sraka1** [comment]
Importing provisioning profiles is now supported with https://github.com/fastlane/fastlane/pull/16188. This seems like a useful option. Btw, isn't the certificate ID included in the certificate itself, both as part of the name and as the "User ID" and "Organisational unit" fields?

**Comment by stefanomondino** [comment]
@sraka1 where are you actually looking for those fields? if I only have a local certificate, the only "id" data I can see if i open it as a raw text file is the Team ID, which is not the certificate id. But maybe I'm missing something.

**Comment by stefanomondino** [comment]
@joshdholtz As you asked in #16188, here's the feature request for explicit match cert id that should bypass the developer portal validation.

here's the rough implementation I put together in a custom action: 
https://github.com/stefanomondino/Jenkins-Murray/blob/master/Jenkins/jenkins/fastlane/actions/custom_import.rb

The only problem I see with this approach is that user could end up in unpredictable scenarios by entering wrong certificate ID.

**Comment by joshdholtz** [comment]
@stefanomondino Thanks for that! I’m totally fine with adding an option but a user input ID if I’m not able to get one from the cert itself. I think it scared me a little but in the initial implementation because I thought it would lead to more confusion/trouble but I may have been wrong 🤷‍♂️ 

So if I can find a way to get the ID automatically, would be cool with requesting the ID from your client/customer?

**Comment by stefanomondino** [comment]
@joshdholtz are you kiddin me? that would be **AWESOME**!!
every time I have to video-call my clients and navigate them through the developer portal, explain them why Apple has this sadistic way to handle app signing and provisioning and finally get that string out, hoping that someone else doesn't revoke the certificate the day after :D 
It would save me even more time <3 
Thank you so much in advance!

**Comment by joshdholtz** [comment]
@stefanomondino Perfect! I have milestone I need to hit for something else today but I will get that out in the next release which should be over the weekend 🚀

**Comment by sraka1** [comment]
> @sraka1 where are you actually looking for those fields? if I only have a local certificate, the only "id" data I can see if i open it as a raw text file is the Team ID, which is not the certificate id. But maybe I'm missing something.

I was under the impression that when using the primary distribution certificate, the certificate ID is the same as the team ID. But looking again, this doesn't seem to be the case.

As for what can happen if the wrong ID is given, [in one place match infers the ID from the filename.](https://github.com/fastlane/fastlane/blob/d0cb7d7a369a153d1e235799a4311ffc9c94d85f/match/lib/match/runner.rb#L205) This would then also be wrong.

@joshdholtz do you see anything critically wrong with this? Should a way be included to fix a wrong input, without the user having to manually decrypt & encrypt the fastlane git files?

**Comment by joshdholtz** [comment]
Opening this back up! I don’t remember if we added this yet but I want to take a look 😊
