### ISSUE TITLE
Run on real device

### ISSUE THREAD

**Issue by vyakimchik** [fastlane/fastlane#16163]
### Feature Request

Please, review this feature request once again: https://github.com/fastlane/fastlane/issues/1635. The reason why it's needed is that some apps work with the camera which doesn't start on a simulator, but there is a need to take a screenshot of that screen. Thanks!

**Comment by janpio** [comment]
We are happy to review and merge a Pull Request containing code that makes this possible.

**Comment by vyakimchik** [comment]
Thanks for the response! I'll keep it in mind.
