### ISSUE TITLE
Using fastlane to build and run on locally connected device

### ISSUE THREAD

**Issue by AdamGerthel** [fastlane/fastlane#16172]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
I'm looking for guidance on how to  to build and install my app on a connected iOS device, using `build_app`.

#### Question Description
I've have spent a few days setting up fastlane for my project and I have one missing piece of the puzzle, namely that I want to be able to build and install the app on a connected iOS device. I can currently do this via xcode, but since I want to be able to temporarily change a few values before building (adding badges, changing version and build number), and also set a few env-variables before building, I'd *much* rather be able to make a custom lane for it.

Basically, this is the gist of my lane:

```ruby
build_app(
  workspace: "./ios/app.xcworkspace",
  scheme: "app",
  clean: true,
  configuration: "Debug",
  build_path: "./ios/builds",
  output_directory: "./ios/builds",
  output_name: "app.ipa",
)

install_on_device(ipa: "./ios/builds/app.ipa")
```
I've changed the appname to "app" to make my example as clear. In reality, I'm also using `increment_version_number` and `increment_build_number` as well, but that shouldn't affect anything, and doesn't either, if I run those, and then build from xcode.

For App Store deployment, I have an almost identical lane which starts with `match` and ends with `upload_to_testflight` instead of `install_on_device`. The only difference in the `build_app` options between the two lanes is that `configuration` is set to "Release" in the latter. That lane works without any hickups.

#### Problem description 💥

The build process crashes with the following message:

```
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/43/gcg6r2110dqdhhl8q33m0v640000gn/T/gym_config20200314-30223-mgfi4k.plist -archivePath './ios/builds/untold 2020-03-14 11.18.49.xcarchive' -exportPath /var/folders/43/gcg6r2110dqdhhl8q33m0v640000gn/T/gym_output20200314-30223-6e2475
2020-03-14 11:26:53.994 xcodebuild[35082:18031904] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/43/gcg6r2110dqdhhl8q33m0v640000gn/T/untold_2020-03-14_11-26-53.993.xcdistributionlogs'.
error: exportArchive: No profiles for 'com.gotterdammerung.untold.dev' were found

Error Domain=IDEProfileLocatorErrorDomain Code=1 "No profiles for 'com.gotterdammerung.untold.dev' were found" UserInfo={IDEDistributionIssueSeverity=3, NSLocalizedDescription=No profiles for 'com.gotterdammerung.untold.dev' were found, NSLocalizedRecoverySuggestion=Xcode couldn't find any iOS App Store provisioning profiles matching 'com.gotterdammerung.untold.dev'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.}

** EXPORT FAILED **
[11:26:55]: Exit status: 70
```

Obviously this has something to do with the provisioning profiles, **but I don't understand why xcode can perfom the build, but fastlane cannot**, when essentially, I'm not changing any settings. This is the setting in xcode for "Debug":

![Screenshot 2020-03-14 at 11 20 41](https://user-images.githubusercontent.com/1490370/76680514-4d7c5280-65e9-11ea-937c-7a1f5d68bfc4.png)

I don't have the same issue when using "Release" and deploying the app to app store. 

I've also tried to use `match(type: "development")`, much like I do on my production/upload lane, but then I'm instead getting this error:

```
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/43/gcg6r2110dqdhhl8q33m0v640000gn/T/gym_config20200314-35968-1x87atr.plist -archivePath './ios/builds/untold 2020-03-14 11.40.16.xcarchive' -exportPath /var/folders/43/gcg6r2110dqdhhl8q33m0v640000gn/T/gym_output20200314-35968-1vut1ok
2020-03-14 11:49:02.738 xcodebuild[40984:18060737] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/43/gcg6r2110dqdhhl8q33m0v640000gn/T/untold_2020-03-14_11-49-02.737.xcdistributionlogs'.
error: exportArchive: Provisioning profile "match Development com.gotterdammerung.untold.dev" doesn't include signing certificate "Apple Distribution: Gotterdammerung AB (SA276PYN8C)".

Error Domain=IDEProfileQualificationErrorDomain Code=5 "Provisioning profile "match Development com.gotterdammerung.untold.dev" doesn't include signing certificate "Apple Distribution: Gotterdammerung AB (SA276PYN8C)"." UserInfo={NSLocalizedDescription=Provisioning profile "match Development com.gotterdammerung.untold.dev" doesn't include signing certificate "Apple Distribution: Gotterdammerung AB (SA276PYN8C)"., IDEDistributionIssueSeverity=3,
```

Help! 🙏

**Comment by richardtop** [comment]
Related #16169
