### ISSUE TITLE
Why is the "buildNumber" argument required for addGitTag() for Fastlane.swift?

### ISSUE THREAD

**Issue by neilsekhon** [fastlane/fastlane#16171]
### Question Checklist

- [y ] Updated fastlane to the latest version
- [y ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [y ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ y] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
 addGitTag()
 no
 no

#### Question Description

According to the docs, the add_git_tag action can be executed without passing any arguments. This will add a simple tag with default values. This is working as expected when I use the normal version of Fastlane. However in Fastlane.swift, the buildNumber parameter of type Any is a required argument for addGitTag(). I modified the code in fastlane/swift/Fastlane.swift to make the buildNumber parameter of type Any? and set the default value to nil. With this code change, everything worked as expected. Was this a coding error or is there a reason that buildNumber was a required argument?

**Comment by janpio** [comment]
`Fastlane.swift` is autogenerated. This is most probably a translation error, because somehow the settings of `add_git_tag` in the ruby version are not exact enough.
