### ISSUE TITLE
use_adb_root feature fails when there's more than one device connected even when setting specific_device

### ISSUE THREAD

**Issue by adheus** [fastlane/fastlane#16170]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Using `use_adb_root true` option in the Screengrabfile fails when there's more than one device connected even though the user sets `specific_device` into the Screengrabfile too. I think the command could be updated to `adb -s $specific_device root` instead of the generic `adb root`.

Screengrabfile:
```
app_apk_path 'app/build/outputs/apk/***.apk'
tests_apk_path 'app/build/outputs/apk/androidTest/***.apk'
skip_open_summary true
reinstall_app true
clear_previous_screenshots true
use_adb_root true
specific_device emulator-5554
locales ['en-US']
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[✔] 🚀 
[16:17:17]: Successfully loaded '/Users/***/Screengrabfile' 📄

+----------------------------+-------------------------------------------------+
|                   Detected Values from './Screengrabfile'                    |
+----------------------------+-------------------------------------------------+
| app_apk_path               | app/build/outputs/apk/***.apk                                          |
| tests_apk_path             | app/build/outputs/apk/androidTest/***.apk                                         |
| skip_open_summary          | true                                            |
| reinstall_app              | true                                            |
| clear_previous_screenshots | true                                            |
| use_adb_root               | true                                            |
| locales                    | ["en-US"]                                       |
| specific_device            | emulator-5554                                   |
+----------------------------+-------------------------------------------------+

+-----------------------------+-------------------------------------------------+
|                        Summary for screengrab 2.143.0                         |
+-----------------------------+-------------------------------------------------+
| tests_package_name          | ***.test                           |
| android_home                | /Users/***/Library/Android/sdk               |
| locales                     | ["en-US"]                                       |
| clear_previous_screenshots  | true                                            |
| output_directory            | fastlane/metadata/android                       |
| skip_open_summary           | true                                            |
| app_package_name            | ***                              |
| test_instrumentation_runner | androidx.test.runner.AndroidJUnitRunner         |
| ending_locale               | en-US                                           |
| use_adb_root                | true                                            |
| app_apk_path                | app/build/outputs/apk/***.apk                                          |
| tests_apk_path              | app/build/outputs/apk/***.apk                                         |
| specific_device             | emulator-5554                                   |
| device_type                 | phone                                           |
| exit_on_test_failure        | true                                            |
| reinstall_app               | true                                            |
| use_timestamp_suffix        | true                                            |
+-----------------------------+-------------------------------------------------+

[16:17:18]: Limiting the test classes run by `screengrab` to just those that generate screenshots can make runs faster.
[16:17:18]: Consider using the :use_tests_in_classes or :use_tests_in_packages option, and organize your tests accordingly.
[16:17:18]: Clearing phoneScreenshots within fastlane/metadata/android
[16:17:18]: $ /Users/***/sdk/platform-tools/adb -s emulator-5554 shell echo \$EXTERNAL_STORAGE
[16:17:18]: ▸ /sdcard
[16:17:18]: $ /Users/***/sdk/platform-tools/adb root
adb: unable to connect for root: more than one device/emulator
[16:17:18]: Exit status: 1

[!] Exit status: 1
</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.3                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.21.1 (Apple Git-122.3)                           |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.3 (19D76)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.3.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.143.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.72.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-eventstream           | 1.0.3        |
| aws-sigv4                 | 1.1.1        |
| aws-sdk-core              | 2.11.463     |
| aws-sdk-resources         | 2.11.463     |
| aws-sdk                   | 2.11.463     |
| CFPropertyList            | 3.0.2        |
| unicode-display_width     | 1.7.0        |
| json                      | 2.3.0        |
| bundler                   | 2.1.4        |
| multi_json                | 1.14.1       |
| signet                    | 0.13.0       |
| os                        | 1.0.1        |
| memoist                   | 0.16.2       |
| googleauth                | 0.11.0       |
| google-cloud-env          | 1.3.1        |
| digest-crc                | 0.5.1        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>

*generated on:* **2020-03-13**
</details></pre>
</details>

**Comment by janpio** [comment]
Sounds like a plan:
https://github.com/fastlane/fastlane/blob/6ca5443925d66f3a8e8eb7bdc29efda1355db59b/screengrab/lib/screengrab/runner.rb#L64-L67
Do you want to submit a Pull Request for this?

**Comment by adheus** [comment]
Sure, it would be pleasure!
