### ISSUE TITLE
Incorrect screen size

### ISSUE THREAD

**Issue by fulldecent** [fastlane/fastlane#16173]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

During the step upload_to_app_store

Unsupported screen size [1620, 2160] for path '/Users/williamentriken/Developer/impostor/fastlane/screenshots/de-DE/iPad (7th generation)-01Configuration.png'

##### Command executed

`bundle exec fastlane`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
bundle exec fastlane
...
[11:53:59]: Driving the lane 'ios screenshots' 🚀
[11:54:00]: ---------------------------------
[11:54:00]: --- Step: capture_screenshots ---
[11:54:00]: ---------------------------------
[11:54:00]: Successfully loaded '/Users/williamentriken/Developer/impostor/fastlane/Snapfile' 📄
...
+------------+-------+-------+-------+-------+-----+-----+-------+-----+---------+-------+
|                                    snapshot results                                    |
+------------+-------+-------+-------+-------+-----+-----+-------+-----+---------+-------+
| Device     | de-DE | en-US | es-ES | fr-FR | ja  | ko  | nl-NL | ru  | zh-Hans | pt-BR |
+------------+-------+-------+-------+-------+-----+-----+-------+-----+---------+-------+
| iPhone 8   |  💚   |  💚   |  💚   |  💚   |  💚 |  💚 |  💚   |  💚 |  💚     |  💚   |
| iPhone 8   |  💚   |  💚   |  💚   |  💚   |  💚 |  💚 |  💚   |  💚 |  💚     |  💚   |
| Plus       |       |       |       |       |     |     |       |     |         |       |
| iPhone 11  |  💚   |  💚   |  💚   |  💚   |  💚 |  💚 |  💚   |  💚 |  💚     |  💚   |
| iPhone 11  |  💚   |  💚   |  💚   |  💚   |  💚 |  💚 |  💚   |  💚 |  💚     |  💚   |
| Pro        |       |       |       |       |     |     |       |     |         |       |
| iPhone 11  |  💚   |  💚   |  💚   |  💚   |  💚 |  💚 |  💚   |  💚 |  💚     |  💚   |
| Pro Max    |       |       |       |       |     |     |       |     |         |       |
| iPad Pro   |  💚   |  💚   |  💚   |  💚   |  💚 |  💚 |  💚   |  💚 |  💚     |  💚   |
| (9.7-inch  |       |       |       |       |     |     |       |     |         |       |
| )          |       |       |       |       |     |     |       |     |         |       |
| iPad (7th  |  💚   |  💚   |  💚   |  💚   |  💚 |  💚 |  💚   |  💚 |  💚     |  💚   |
| generatio  |       |       |       |       |     |     |       |     |         |       |
| n)         |       |       |       |       |     |     |       |     |         |       |
| iPad Pro   |  💚   |  💚   |  💚   |  💚   |  💚 |  💚 |  💚   |  💚 |  💚     |  💚   |
| (11-inch)  |       |       |       |       |     |     |       |     |         |       |
| iPad Pro   |  💚   |  💚   |  💚   |  💚   |  💚 |  💚 |  💚   |  💚 |  💚     |  💚   |
| (12.9-inc  |       |       |       |       |     |     |       |     |         |       |
| h) (3rd    |       |       |       |       |     |     |       |     |         |       |
| generatio  |       |       |       |       |     |     |       |     |         |       |
| n)         |       |       |       |       |     |     |       |     |         |       |
+------------+-------+-------+-------+-------+-----+-----+-------+-----+---------+-------+
...
[12:31:24]: Successfully created HTML file with an overview of all the screenshots: '/Users/williamentriken/Developer/impostor/fastlane/screenshots/screenshots.html'
[12:31:26]: ---------------------------------
[12:31:26]: --- Step: upload_to_app_store ---
[12:31:26]: ---------------------------------
[12:31:26]: Login to App Store Connect (apple.com@phor.net)
[12:31:27]: Login successful

+--------------------------------------+----------------------------------------------------------------+
|                                        deliver 2.143.0 Summary                                        |
+--------------------------------------+----------------------------------------------------------------+
| skip_binary_upload                   | true                                                           |
| skip_metadata                        | true                                                           |
| screenshots_path                     | /Users/williamentriken/Developer/impostor/fastlane/screenshots |
| metadata_path                        | ./fastlane/metadata                                            |
| username                             | xxx                                             |
| app_identifier                       | net.phor.Impostor                                              |
| platform                             | ios                                                            |
| edit_live                            | false                                                          |
| use_live_version                     | false                                                          |
| skip_screenshots                     | false                                                          |
| skip_app_version_update              | false                                                          |
| force                                | false                                                          |
| overwrite_screenshots                | false                                                          |
| submit_for_review                    | false                                                          |
| reject_if_possible                   | false                                                          |
| automatic_release                    | false                                                          |
| phased_release                       | false                                                          |
| reset_ratings                        | false                                                          |
| team_id                              | xxx                                                         |
| dev_portal_team_id                   | xxx                                                     |
| run_precheck_before_submit           | true                                                           |
| precheck_default_rule_level          | warn                                                           |
| individual_metadata_items            | []                                                             |
| ignore_language_directory_validation | false                                                          |
| precheck_include_in_app_purchases    | true                                                           |
+--------------------------------------+----------------------------------------------------------------+

+---------------------------+----------------------------------------------------------------+
|                                        Lane Context                                        |
+---------------------------+----------------------------------------------------------------+
| DEFAULT_PLATFORM          | ios                                                            |
| PLATFORM_NAME             | ios                                                            |
| LANE_NAME                 | ios screenshots                                                |
| SNAPSHOT_SCREENSHOTS_PATH | /Users/williamentriken/Developer/impostor/fastlane/screenshots |
+---------------------------+----------------------------------------------------------------+
[12:31:29]: Unsupported screen size [1620, 2160] for path '/Users/williamentriken/Developer/impostor/fastlane/screenshots/de-DE/iPad (7th generation)-01Configuration.png'

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | default_platform    | 0           |
| 2    | capture_screenshots | 2140        |
| 💥   | upload_to_app_store | 2           |
+------+---------------------+-------------+

[12:31:29]: fastlane finished with errors

[!] Unsupported screen size [1620, 2160] for path '/Users/williamentriken/Developer/impostor/fastlane/screenshots/de-DE/iPad (7th generation)-01Configuration.png'

</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 10.15.3                                                    |
| Ruby                        | 2.6.5                                                      |
| Bundler?                    | true                                                       |
| Git                         | git version 2.21.1 (Apple Git-122.3)                       |
| Installation Source         | ~/Developer/impostor/vendor/bundle/ruby/2.6.0/bin/fastlane |
| Host                        | Mac OS X 10.15.3 (19D76)                                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.6.5/lib                           |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                                |
| Is contained                | false                                                      |
| Is homebrew                 | false                                                      |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
| Xcode Version               | 11.3.1                                                     |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "Impostor.xcworkspace", scheme: "ImpostorUITests")
    upload_to_app_store(skip_binary_upload: true, skip_metadata: true)
  end

  desc "Uplaod screenshots"
  lane :fd_uploadscreenshots do
    upload_to_app_store
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("net.phor.Impostor") # The bundle identifier of your app
apple_id("xxx") # Your Apple email address

itc_team_id("xxx") # App Store Connect Team ID
team_id("xxx") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.143.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 2.1.4        |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.0.3        |
| aws-sigv4                 | 1.1.1        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 2.11.463     |
| aws-sdk-resources         | 2.11.463     |
| aws-sdk                   | 2.11.463     |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.5.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.72.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.17.3       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.0.1        |
| signet                    | 0.13.0       |
| googleauth                | 0.11.0       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.25.1       |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2020-03-15**
</details>

**Comment by janpio** [comment]
> Unsupported screen size [1620, 2160] for path '/Users/williamentriken/Developer/impostor/fastlane/screenshots/de-DE/iPad (7th generation)-01Configuration.png'

What is the real, expected screen size?

**Comment by fulldecent** [comment]
# Underlying issue

The 7th edition is available in Xcode but it is not available on App Store Connect. So the screenshots you are creating cannot be uploaded. Thanks Apple.

# Workaround:

```sh
rm **/*7th*
```
