### ISSUE TITLE
Force scan to fail if requested simulator does not exist

### ISSUE THREAD

**Issue by tedgonzalez** [fastlane/fastlane#16184]
### Feature Request
Currently if you request scan to run on a particular simulator if that simulator is not found scan will fallback to a default simulator. I would like to be able to fail scan early if the required simulator is not found.

### Motivation Behind Feature
I need the ability for scan to fail early as a mechanism for ensuring that the required simulator is indeed installed on a particular CI machine. This is because we may require a test to run on a particular simulator e.g. a UI test suite run on a particularly sized device.

### Feature Description
I imagine this could be done as an optional argument to scan (i.e. ensure_device_found) which would default to false so that it would not be a breaking change.

### Alternatives or Workarounds
I've searched for alternatives but didn't find any would love to hear about workarounds if there are known ones available.

source: https://github.com/fastlane/fastlane/issues/15706

**Comment by janpio** [comment]
Sounds useful. Are you up to create a Pull Request for this?

Is the "fallback" visible in the output? If so, could you post that please? Will make it much easier to find the code that needs to be adapted here.

**Comment by tedgonzalez** [comment]
Hi this is the output shown:
```
No simulators found that are equal to the version of specifier (12.4) and greater than or equal to the version of deployment target (0)
Ignoring 'iPhone 6s (12.4)', couldn’t find matching simulator
Ignoring 'iPhone Xs (13.3)', couldn’t find matching simulator
Ignoring ' iPad (7th generation)', couldn’t find matching simulator
```

No time yet, but I will try based on your suggestion! Up for grabs for anyone :)

**Comment by janpio** [comment]
First line is from here:
https://github.com/fastlane/fastlane/blob/425f4f6aebc9fe1938652f03314382f5a03f895c/scan/lib/scan/detect_values.rb#L113-L125

Further lines are from here:
https://github.com/fastlane/fastlane/blob/425f4f6aebc9fe1938652f03314382f5a03f895c/scan/lib/scan/detect_values.rb#L133-L167

I assume you have further output that says `Couldn't find any matching simulators for 'foo' - falling back to default simulator` @tedgonzalez?
That would be coming from here:
https://github.com/fastlane/fastlane/blob/425f4f6aebc9fe1938652f03314382f5a03f895c/scan/lib/scan/detect_values.rb#L169-L185

I think implementing what you are asking for would mean to understand that code (and how it works together) and then implementing a way to override that fallback and fail instead if a param is set.

**Comment by tedgonzalez** [comment]
Activity

**Comment by tedgonzalez** [comment]
Activity

**Comment by alexito4** [comment]
This would be very useful indeed. If you require some tests to run on specific devices the automated fallback causes more issues than helps.

**Comment by tedgonzalez** [comment]
Activity

**Comment by tedgonzalez** [comment]
Activity

**Comment by tedgonzalez** [comment]
Activity

**Comment by rogerluan** [comment]
JW, does setting `skip_detect_devices` as `true` achieve the same result as the one you're expecting?

**Comment by tedgonzalez** [comment]
Just confirmed that skip_detect_devices didn't work
