### ISSUE TITLE
[pod_lib_lint] Add "analyze" option

### ISSUE THREAD

**Issue by macblazer** [fastlane/fastlane#16187]
### Feature Request

Add "analyze" as an option to the `pod_lib_lint` action that maps to the "--analyze" option in CocoaPods.  The "--analyze" option was added to [CocoaPods v1.6.1](https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md#161-2019-02-21) on 2019-02-17 and triggers Xcode's built in static code analysis tool to be run as part of the lint.

#### Motivation Behind Feature

While creating or updating shared code in pods, running static code analysis can help to find more issues with the code that can be fixed before shipping.

#### Feature Description

This would be a purely optional parameter to `pod_lib_lint` that is backwards compatible.  The default behavior would be to not run the static analyzer which is the same as the current behavior.

Invoking `pod_lib_lint` with `analyze: true` in addition to other desired parameters would run the static code analysis tool.

`pod_lib_lint(analyze: true)`

#### Alternatives or Workarounds

The only workaround is to use the `sh` action and run the whole `pod lib lint --analyze` (plus other parameters) command.

**Comment by janpio** [comment]
Sounds useful. Are you up to creating a Pull Request for this?

**Comment by macblazer** [comment]
Yes, I should be able to get this one done.  👍
