### ISSUE TITLE
Omit timestamp and colors from logs

### ISSUE THREAD

**Issue by spacesuitdiver** [fastlane/fastlane#16186]
### Feature Request
I was wondering if it's already possible or might be a quick addition to allow for logging to omit timestamps and colors from logs

#### Motivation Behind Feature
Our logger already adds timestamps so when you download the logs the timestamp is there twice. The colors also seem to just add extra cruft in the logs.

**Comment by janpio** [comment]
Yes:

Color: https://docs.fastlane.tools/faqs/#disable-colored-output
Timestamp: https://docs.fastlane.tools/advanced/fastlane/#output-environment-variables
