### ISSUE TITLE
How to specify team when multiple teams exist in developer portal

### ISSUE THREAD

**Issue by yuzushioh** [fastlane/fastlane#16199]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
I am wondering if there is a way to specify which team to use when multiple teams exist in developer portal in CLI? It gives me `Multiple teams found on the Developer Portal, please enter the number of the team you want to use: ` everytime I run commands

**Comment by Katsz** [comment]
`team_id` or `ENV['FASTLANE_TEAM_ID']`, as you'd expect. Whenever you stumbled across those kind of questions feel free to run `fastlane action %whatever%`. There's output of `fastlane action match` for example:
```
<...>
| team_id                | The ID of your         | FASTLANE_TEAM_ID       | *              |
|                        | Developer Portal team  |                        |                |
|                        | if you're in multiple  |                        |                |
|                        | teams                  |                        |                |
<...>
```

**Comment by yuzushioh** [comment]
@Katsz Thank you for replaying. It works perfectly now. Thank you!
