### ISSUE TITLE
Option to read keychain password from a file?

### ISSUE THREAD

**Issue by petemounce** [fastlane/fastlane#16193]
### Feature Request

I'd like to be able to supply the keychain password like `fastlane match development --keychain-password-file "some-file-that-I-will-make-via-mktemp-and-delete-immediately-afterwards"`.

In https://github.com/fastlane/fastlane/blob/master/match/lib/match/options.rb#L186-L191 there's an option to supply the keychain password via a flag or environment variable.

In CI, this is not ideal, because:
* someone can do `env | sort | grep password` and expose the secret
* it's tricky to arrange for a password (which can contain inconvenient shell-string-escaping characters) to be assigned into a variable safely

    ```bash
    MATCH_KEYCHAIN_PASSWORD=$(fetch_login_keychain_password) fastlane match development
    ```

    I would want to single-quote the subshell, but then it won't be expanded. Or I could mandate to my users to not use inconvenient characters (but then, people will).

#### Motivation Behind Feature

This 
* makes the CI UX simpler to work with.
* enables a more secure way of working with (really impactful-if-leaked) secrets.

##### 👎 Quote wrapping 1

```bash
MATCH_KEYCHAIN_PASSWORD="'"$(echo "\")"'"
```

```
$ echo $MATCH_KEYCHAIN_PASSWORD
'foo'
```

Actually, I'm going to stop there in case I put a bunch of effort into this issue and it goes unnoticed. I'll happily add more illustrations if you'd like.

**Comment by Katsz** [comment]
You can create one-off keychain for match instead, when running on CI. See https://github.com/fastlane/fastlane/issues/12291#issuecomment-391538653. 

<details> <summary>Or this</summary> 

![image](https://user-images.githubusercontent.com/16171550/77234247-daad4180-6bbd-11ea-92ea-099fac03f614.png)
</details>

**Comment by tedgonzalez** [comment]
activity

**Comment by tedgonzalez** [comment]
activity

**Comment by tedgonzalez** [comment]
activity

**Comment by tedgonzalez** [comment]
activity

**Comment by tedgonzalez** [comment]
activity

**Comment by rogerluan** [comment]
@petemounce You seem to raise valid concerns. In fact, if a CI log is not a secure place, a lot of damage can be done there 🤔 I'm curious though, how are you intending to create the temporary file, and delete it immediately afterwards? Can't that "evil person that has access to your CI" dump the file itself in the meantime too? Where is the data of that file coming from?

**Comment by petemounce** [comment]
@rogerluan it's about minimising the risk and layering defenses; the risk is really hard to totally eliminate. This particular ask is about minimising the risk of reasons the secret might be exposed to a CI log, where the potential audience of those is greater than the set of people with access to change how CI or build automation behaves. 

(If someone gets _malicious_ access to a CI runner, they can elevate their privileges to what that runner has access to, which for a code signing equipped runner is basically game over because now that person can sign arbitrary binaries with my company cert, exfiltrate those (or worse, publish them as if my company did), and my company is liable. That population of people is smaller; compromising a machine is harder than reading a log.)

A bash trap would be how I'd delete it afterwards, if bash. 

```bash
secret="$(mktemp)"
trap rm secret EXIT ERR INT QUIT
set +o xtrace
read_secret_from_secure_store "${secret}"
fastlane ....
```

Or if powershell, a try/catch/finally for more control.

In my case, the data would be coming from hashicorp vault, but it could equally come from git-crypt, a cloud provider secrets store; there are variations.
