### ISSUE TITLE
Undefined method `strip' for nil:NilClass error after a sucess upload_to_testflight

### ISSUE THREAD

**Issue by welersonMelo** [fastlane/fastlane#16201]
🔑 Hello, guys.
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I have executed fastfile and the **upload_to_testflight** command and it is actually doing the upload of the .ipa file properly. However, after return 

> Successfully uploaded the new binary to App Store Connect

 it's returning an error: 

> status: undefined method `strip' for nil:NilClass

It's doing what I want at all. But the right feed back is important to me in the sense that I'm using an automatic CI for lot of people.

##### Command executed

```
upload_to_testflight(
    skip_submission: true,
    ipa: options[:ipa_path],
    app_platform: "ios",
    username: "***",
    team_id: "***",
    apple_id: "***"
  )
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
[32m---------------------------------------- [0
[32m--- Step: Verifying fastlane version --- [0

[32m---------------------------------------- [0

Your fastlane version 2.143.0 matches the minimum requirement of 2.68.0  ✅

[32mDriving the lane 'testflight_deploy'    [0
[32m---------------------------------- [0m
[32m--- Step: upload_to_testflight --- [0m
[32m---------------------------------- [0m
[32mReady to upload new build to TestFlight (App: ***)... [0m
Fetching password for transporter from environment variable named `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`

Going to upload updated app to App Store Connect
[32mThis might take a few minutes. Please don't interrupt the script. [0m
[32miTunes Transporter successfully finished its job [0m
[32m-------------------------------------------------------------------- [0m
[32mSuccessfully uploaded package to App Store Connect. It might take a few minutes until it's visible online. [0m

[32m-------------------------------------------------------------------- [0m
[32mSuccessfully uploaded the new binary to App Store Connect [0m

: Login to App Store Connect (***)
Available session is not valid any more. Continuing with normal login.
Two-factor Authentication (6 digits code) is enabled for account '***'
More information about Two-factor Authentication: https://support.apple.com/en-us/HT204915

If you're running this in a non-interactive session (e.g. server or CI)
 check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification

(Input `sms` to escape this prompt and select a trusted phone number to send the code as a text message)

(You can also set the environment variable `SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER` to automate this)
 (Read more at: https://github.com/fastlane/fastlane/blob/master/spaceship/docs/Authentication.md#auto-select-sms-via-spaceship-2fa-sms-default-phone-number)

Please enter the 6 digit code:
 +---------------+-------------------+
 |            [33mLane Context [0m            |
 +---------------+-------------------+
 | PLATFORM_NAME |                   |
 | LANE_NAME     | testflight_deploy |
 +---------------+-------------------+

 +------+----------------------------+-------------+
 |                 [32mfastlane summary [0m                 |
 +------+----------------------------+-------------+
 | Step | Action                     | Time (in s) |
 +------+----------------------------+-------------+
 | 1    | Verifying fastlane version | 0           |
|      |  [31mupload_to_testflight [0m       | 158         |
 +------+----------------------------+-------------+

 [31mfastlane finished with errors [0m
:
Looking for related GitHub issues on fastlane/fastlane...

 ➡️   [33mundefined method `strip' for nil:NilClass [0m
  https://github.com/fastlane/fastlane/issues/16076 [ [31mopen [0m] 2   
    2 weeks ago

 **/usr/local/Cellar/fastlane/2.143.0/libexec/gems/highline-1.7.10/lib/highline/question.rb:413:in `remove_whitespace':  [31m[!] undefined method `strip' for nil:NilClass [0m (NoMethodError)**

...

(sorry I got the output from the CI UI directly)
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 10.14.6                                                 |
| Ruby                        | 2.5.7                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.21.1 (Apple Git-122.3)                    |
| Installation Source         | /usr/local/Cellar/fastlane/2.143.0/libexec/bin/fastlane |
| Host                        | Mac OS X 10.14.6 (18G84)                                |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.5/2.5.7/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                             |
| Is contained                | false                                                   |
| Is homebrew                 | false                                                   |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 11.3.1                                                  |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | pt_BR.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.143.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.72.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.13.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.11.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.5.1        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-eventstream           | 1.0.3        |
| aws-sigv4                 | 1.1.1        |
| aws-sdk-core              | 2.11.462     |
| aws-sdk-resources         | 2.11.462     |
| aws-sdk                   | 2.11.462     |
</details>

*generated on:* **2020-03-23**
<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by etienneyoufeel** [comment]
I have the same problem. Happen with the new version of fastlane.

**Comment by Kiruel** [comment]
I have the same problem. Happen with the new version of fastlane (2.146.1)

**Comment by Kiruel** [comment]
Ok after some test  I find the workarround here. @welersonMelo you need to refresh your FASTLANE_SESSION with the command `fastlane spaceauth -u user@email.com`. You will find all the information here https://docs.fastlane.tools/best-practices/continuous-integration/#application-specific-passwords in spaceauth section.

**Comment by welersonMelo** [comment]
@Kiruel, we were doing this already. 
But thank you, anyway.
