### ISSUE TITLE
How to make the resigned ipa receive the same push notification as the original ipa?

### ISSUE THREAD

**Issue by WuxiTianyiNetworkTechnology** [fastlane/fastlane#16213]
When I resigned, I registered a new certificate and appid, opened the APNs function of the appid, and added a new APNs certificate. Then I created mobileprovision and signed the original ipa with the new appid, new mobileprovision, and new certificate. However, ipa cannot receive push notification after resignature.

 I use other people's tools to achieve this function, but I don't know if fastlane can achieve this function,and why two apps with different bundleID can receive the same push notification. please enlighten me. thank you very much!

**Comment by max-ott** [comment]
I don't think that's possible. The whole concept of code signing is that you cannot do this exact thing: Resign an app and still send push. Push certificates are tied to bundle IDs.
