### ISSUE TITLE
Where should I store the android Keystore for CI?

### ISSUE THREAD

**Issue by lukemcgregor** [fastlane/fastlane#16212]
I am trying to work out how to setup CI for the android portion of a react native project. I already use Fastlane for my iOS build but I'm trying to set up a similar flow for the android part.

With iOS match is used to encrypt and store the certificates to sign builds. Im wondering if there is a similar thing I should be using to store the android Keystore for signing builds. If there isn't a specific tool for this is there a way I can/should use match to store this key?

How are other people distributing the Keystore between CI servers?

**Comment by max-ott** [comment]
The only real part that `fastlane` touches when it comes to Android is the publishing / uploading with `supply`. I don't think this is the right place to get opinions/best practices on Android CI/CD.

**Comment by lukemcgregor** [comment]
That may be but from my perspective it's really hard to understand what fastlane does or doesn't do. It appears to provide tools to help implementing a complete CI stack for iOS, theres also a section on android in the docs, isn't it reasonable to assume that what fastlane provides for android is similar?

**Comment by warrify** [comment]
@lukemcgregor  We use Gitlab CI but this should work for most CI Systems.

We base64 encoded the keystore file and stored the result in a Gitlab File Environment variable. ```bash 
base64 -i release.jks > release.jks.b64
```
(Basically Gitlab creates the file and sets the path as the value of the environment variable). We then just go ahead and base64 decode the file into another file which we use as the keystore.

```bash 
base64 -d -i "$ANDROID_KEYSTORE_ENV_VAR" > release.jks
```

hope this helps
