### ISSUE TITLE
Unsupported screen size for manually taken screenshots (using iPhone simulator)

### ISSUE THREAD

**Issue by randex** [fastlane/fastlane#16219]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Can't add frames to screenshots that I took manually using iPhone simulator.

#### Question Description

Unfortunately I'm not able to use `snapshot` to automate screenshotting because my project is pretty old and for UI tests to work I have to rewrite some stuff first. So I thought I could take screenshots manually and then add text and frames to all of them using `frameit`. I need 6.5" display screenshots first, so I tried iPhone 11 Pro Max and iPhone XS Max simulators, but this is the result I get every time

```
screenshots % fastlane frameit silver
[13:54:39]: Using device frames version 'latest'
[13:54:39]: Framing screenshot './Simulator Screen Shot - iPhone Xs Max - 2020-03-28 at 13.45.14.png'
[13:54:39]: Unsupported screen size [1242, 2688] for path './Simulator Screen Shot - iPhone Xs Max - 2020-03-28 at 13.45.14.png'
[13:54:39]: Framing screenshot './Simulator Screen Shot - iPhone Xs Max - 2020-03-28 at 13.43.15.png'
[13:54:39]: Unsupported screen size [1242, 2688] for path './Simulator Screen Shot - iPhone Xs Max - 2020-03-28 at 13.43.15.png'
[13:54:39]: Framing screenshot './background.png'
[13:54:39]: Unsupported screen size [3000, 3000] for path './background.png'
[13:54:39]: Framing screenshot './Simulator Screen Shot - iPhone Xs Max - 2020-03-28 at 13.43.08.png'
[13:54:39]: Unsupported screen size [1242, 2688] for path './Simulator Screen Shot - iPhone Xs Max - 2020-03-28 at 13.43.08.png'
[13:54:39]: Framing screenshot './Simulator Screen Shot - iPhone Xs Max - 2020-03-28 at 13.43.55.png'
[13:54:39]: Unsupported screen size [1242, 2688] for path './Simulator Screen Shot - iPhone Xs Max - 2020-03-28 at 13.43.55.png'
```
Don't mind `background.png` in the log.
Even tried to provide `Framefile.json` looking like this
```
{
  "device_frame_version": "latest",
  "default": {
    "background": "./background.jpg"
  }
}
```

And also tried to use `force_device_type` property but it didn't seem to work. 
Searched here and found #13355. Looks like you fixed it, so I don't really understand what I'm doing wrong...

**Comment by randex** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.4                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.24.1 (Apple Git-126)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.15.4 (19E266)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.4                                        |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.28.3  | 💥 Check failed |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.73.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.13.1       |
</details>


*generated on:* **2020-03-28**
</details>

**Comment by dmytro-me** [comment]
Your fastlane  2.28.3 is quite old and probably unaware of Xs resolution. It seems you have installed it via brew cask, remove fastlane and install it using gem method.

**Comment by randex** [comment]
Oh, I thought both ways to install fastlane will install the same version. It worked when I reinstalled using gem. Thanks!
