### ISSUE TITLE
Given project for action get_version_number

### ISSUE THREAD

**Issue by raptorxcz** [fastlane/fastlane#16215]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I have multiple projects in one folder. I trying to get version from one project. When I use action `get_version_number` it ignores project I put into arguments.

In documentation https://docs.fastlane.tools/actions/get_version_number/ is for key `xcodeproj` this definition:
> Path to the main Xcode project to read version number from, optional. By default will use the first Xcode project found within the project root directory

I looked into source code https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/get_version_number.rb and I found, that action `get_version_number` always selects first project. This is wrong.

##### Command executed
`get_version_number`

**Comment by tedgonzalez** [comment]
activity

**Comment by tedgonzalez** [comment]
activity

**Comment by tedgonzalez** [comment]
activity

**Comment by greculrc** [comment]
> There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.
> 
> Please make sure to update to the latest `fastlane` version and check if that solves the issue. Let us know if that works for you by adding a comment 👍
> 
> Friendly reminder: contributions are always welcome! Check out [CONTRIBUTING.md](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md) for more information on how to help with `fastlane` and feel free to tackle this issue yourself 💪

What a great and, of course, well written post. It`s so useful…

**Comment by tedgonzalez** [comment]
activity

**Comment by tedgonzalez** [comment]
activity

**Comment by rogerluan** [comment]
I investigated this a bit and it seems to be a misunderstanding of the documentation slash misleading behavior of the actual code. The documentation says:

>Path to the main Xcode project to read version number from

The way it is consumed in the code is as if this path contained the containing directory of the xcodeproj file. So it will search in this given directory, looking for the first `xcodeproj` that it can find 😅  I agree this is totally misleading, though. We should not only update how the logic works but also the docs.

I'll add this to my to-do list 👍

**Comment by rogerluan** [comment]
I've opened a PR fixing this behavior @raptorxcz @tedgonzalez - https://github.com/fastlane/fastlane/pull/17574

Would you mind help testing it? 😃

**Comment by CSHawley** [comment]
Can we possibly accelerate this? This fix is definitely of interest to us folks with multi-project workspaces 😃

**Comment by tedgonzalez** [comment]
@CSHawley you may test the PR #17574
