### ISSUE TITLE
fastlane finished with errors  [!] Response body ERROR: <html> <head><title>302 Found</title></head> <body bgcolor="white"> <center><h1>302 Found</h1></center> <hr><center>nginx/1.14.0 (Ubuntu)</center> </body> </html>

### ISSUE THREAD

**Issue by bullerliu** [fastlane/fastlane#16214]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by bullerliu** [comment]
希望解答

**Comment by max-ott** [comment]
Not sure what the issue is. Please re-open a new issue with the required details in the issue template so that you give the community a chance to help.
