### ISSUE TITLE
match always creates new certificates for appstore, fails on readonly [XCode 11]

### ISSUE THREAD

**Issue by warrify** [fastlane/fastlane#16210]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

We set up match in our project. Initially we ran `bundle exec fastlane match nuke` which deleted all certificates and profiles. After that I set up an S3 Bucket for storage and created a Matchfile. Running `bundle exec fastlane match appstore` created the corresponding certificates, keys and profiles which showed up both in S3 and my keystore. I am then able to run gym locally and my app gets signed with the correct key. However whenever I run match again it first downloads all certificates and keys and then tries to create a new code signing identity. When I add the readonly flag it fails with the following output.

##### Command executed

```bash
bundle exec fastlane ios certificates
```
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
bundle exec fastlane ios certificates --verbose                               
[✔] 🚀 
INFO [2020-03-26 17:05:22.60]: Successfully loaded custom action '/Users/user/Documents/app-name/app/fastlane/actions/commit_timestamp.rb'.
DEBUG [2020-03-26 17:05:22.60]: Checking if there are any plugins that should be loaded...
DEBUG [2020-03-26 17:05:22.60]: Loading 'fastlane-plugin-versioning_android' plugin
INFO [2020-03-26 17:05:22.60]: gem 'fastlane-plugin-versioning_android' is already installed
+------------------------------------+---------+----------------------------------------------------+
|                                           Used plugins                                            |
+------------------------------------+---------+----------------------------------------------------+
| Plugin                             | Version | Action                                             |
+------------------------------------+---------+----------------------------------------------------+
| fastlane-plugin-versioning_android | 0.1.0   | android_get_version_name android_set_version_code  |
|                                    |         | android_set_version_name android_get_version_code  |
+------------------------------------+---------+----------------------------------------------------+

Successfully loaded Appfile at path '/Users/user/Documents/app-name/app/fastlane/Appfile'
- app_identifier: '...'
- apple_id: '...'
- itc_team_id: '...'
- team_id: '...'
- package_name: '...'
-------
INFO [2020-03-26 17:05:22.89]: ----------------------------------------
INFO [2020-03-26 17:05:22.89]: --- Step: Verifying fastlane version ---
INFO [2020-03-26 17:05:22.89]: ----------------------------------------
INFO [2020-03-26 17:05:22.89]: Your fastlane version 2.144.0 matches the minimum requirement of 2.53.1  ✅
INFO [2020-03-26 17:05:22.89]: --------------------------------
INFO [2020-03-26 17:05:22.89]: --- Step: ensure_bundle_exec ---
INFO [2020-03-26 17:05:22.89]: --------------------------------
INFO [2020-03-26 17:05:22.89]: Using bundled fastlane ✅
INFO [2020-03-26 17:05:22.91]: Driving the lane 'ios certificates' 🚀
INFO [2020-03-26 17:05:23.09]: -------------------
INFO [2020-03-26 17:05:23.09]: --- Step: match ---
INFO [2020-03-26 17:05:23.09]: -------------------
INFO [2020-03-26 17:05:23.10]: Successfully loaded '/Users/user/Documents/app-name/app/fastlane/Matchfile' 📄

+----------------------+------------------------------------------+
|           Detected Values from './fastlane/Matchfile'           |
+----------------------+------------------------------------------+
| username             | ...                                      |
| keychain_name        | match.keychain                           |
| keychain_password    | ...                                      |
| storage_mode         | s3                                       |
| s3_region            | eu-west-1                                |
| s3_access_key        | ...                                      |
| s3_secret_access_key | ...                                      |
| s3_bucket            | ...                                      |
| platform             | ios                                      |
| generate_apple_certs | true                                     |
| skip_docs            | true                                     |
| verbose              | true                                     |
+----------------------+------------------------------------------+

+----------------------------+------------------------------------------+
|                       Summary for match 2.144.0                       |
+----------------------------+------------------------------------------+
| app_identifier             | ["..."]                                  |
| type                       | appstore                                 |
| readonly                   | true                                     |
| generate_apple_certs       | true                                     |
| skip_provisioning_profiles | false                                    |
| username                   | ...                                      |
| team_id                    | ...                                      |
| storage_mode               | s3                                       |
| git_branch                 | master                                   |
| shallow_clone              | false                                    |
| clone_branch_directly      | false                                    |
| s3_region                  | eu-west-1                                |
| s3_access_key              | ...                                      |
| s3_secret_access_key       | ...                                      |
| s3_bucket                  | ...                                      |
| keychain_name              | match.keychain                           |
| keychain_password          | ********                                 |
| force                      | false                                    |
| force_for_new_devices      | false                                    |
| skip_confirmation          | false                                    |
| skip_docs                  | true                                     |
| platform                   | ios                                      |
| verbose                    | true                                     |
+----------------------------+------------------------------------------+

DEBUG [2020-03-26 17:05:23.53]: Downloading file from S3 'https://bucket-name.s3.eu-west-1.amazonaws.com/123ABC/certs/development/456DEF.cer' on bucket bucket-name
DEBUG [2020-03-26 17:05:23.66]: Downloading file from S3 'https://bucket-name.s3.eu-west-1.amazonaws.com/123ABC/certs/development/456DEF.p12' on bucket bucket-name
DEBUG [2020-03-26 17:05:23.78]: Downloading file from S3 'https://bucket-name.s3.eu-west-1.amazonaws.com/123ABC/certs/distribution/789GHI.cer' on bucket bucket-name
DEBUG [2020-03-26 17:05:23.90]: Downloading file from S3 'https://bucket-name.s3.eu-west-1.amazonaws.com/123ABC/certs/distribution/789GHI.p12' on bucket bucket-name
DEBUG [2020-03-26 17:05:24.02]: Downloading file from S3 'https://bucket-name.s3.eu-west-1.amazonaws.com/123ABC/profiles/appstore/AppStore_com.app-name.mobileprovision' on bucket bucket-name
DEBUG [2020-03-26 17:05:24.15]: Downloading file from S3 'https://bucket-name.s3.eu-west-1.amazonaws.com/123ABC/profiles/development/Development_com.app-name.debug.mobileprovision' on bucket bucket-name
DEBUG [2020-03-26 17:05:24.27]: Downloading file from S3 'https://bucket-name.s3.eu-west-1.amazonaws.com/123ABC/profiles/development/Development_com.app-name.mobileprovision' on bucket bucket-name
DEBUG [2020-03-26 17:05:24.39]: Downloading file from S3 'https://bucket-name.s3.eu-west-1.amazonaws.com/123ABC/profiles/development/Development_com.app-name.staging.mobileprovision' on bucket bucket-name
DEBUG [2020-03-26 17:05:24.51]: Downloading file from S3 'https://bucket-name.s3.eu-west-1.amazonaws.com/README.md' on bucket bucket-name
DEBUG [2020-03-26 17:05:24.63]: Downloading file from S3 'https://bucket-name.s3.eu-west-1.amazonaws.com/match_version.txt' on bucket bucket-name
DEBUG [2020-03-26 17:05:24.74]: Successfully downloaded files from S3 to /var/folders/8d/n13w2vb511l4zt05wthynp880000gn/T/d20200326-81819-rakzvy
INFO [2020-03-26 17:05:24.78]: 🔓  Decrypted '456DEF.p12'
INFO [2020-03-26 17:05:24.81]: 🔓  Decrypted '456DEF.cer'
INFO [2020-03-26 17:05:24.85]: 🔓  Decrypted '789GHI.p12'
INFO [2020-03-26 17:05:24.88]: 🔓  Decrypted '789GHI.cer'
INFO [2020-03-26 17:05:24.92]: 🔓  Decrypted 'AppStore_com.app-name.mobileprovision'
INFO [2020-03-26 17:05:24.95]: 🔓  Decrypted 'Development_com.app-name.mobileprovision'
INFO [2020-03-26 17:05:24.99]: 🔓  Decrypted 'Development_com.app-name.debug.mobileprovision'
INFO [2020-03-26 17:05:25.02]: 🔓  Decrypted 'Development_com.app-name.staging.mobileprovision'
INFO [2020-03-26 17:05:25.02]: 🔓  Successfully decrypted certificates repo
WARN [2020-03-26 17:05:25.02]: Couldn't find a valid code signing identity for distribution... creating one for you now
WARN [2020-03-26 17:05:25.03]: Lane Context:
INFO [2020-03-26 17:05:25.03]: {:PLATFORM_NAME=>:ios, :LANE_NAME=>"ios certificates"}
ERROR [2020-03-26 17:05:25.03]: No code signing identity found and can not create a new one because you enabled `readonly`

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | ensure_bundle_exec         | 0           |
| 💥   | match                      | 1           |
+------+----------------------------+-------------+

DEBUG [2020-03-26 17:05:25.07]: All plugins are up to date
ERROR [2020-03-26 17:05:25.07]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: No code signing identity found and can not create a new one because you enabled `readonly`

URL: https://api.github.com/search/issues?q=No%20code%20signing%20identity%20found%20and%20can%20not%20create%20a%20new%20one%20because%20you%20enabled%20%60readonly%60+repo:fastlane/fastlane
➡️  can't modify frozen String: "true" for enterprise builds
    https://github.com/fastlane/fastlane/issues/16055 [open] 35 💬
    3 weeks ago

➡️  Match command with certificate uploaded on Git error " No code signing identity found and can not create a new one because you enabled `readonly`"
    https://github.com/fastlane/fastlane/issues/14912 [closed] 11 💬
    26 Sep 2019

➡️  [Regression] Breaking change when importing a new cert in 2.113.0, worked in 2.112.0
    https://github.com/fastlane/fastlane/issues/14039 [closed] 72 💬
    10 Sep 2019

and 21 more at: https://github.com/fastlane/fastlane/search?q=No%20code%20signing%20identity%20found%20and%20can%20not%20create%20a%20new%20one%20because%20you%20enabled%20%60readonly%60&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
DEBUG [2020-03-26 17:05:26.22]: All plugins are up to date
bundler: failed to load command: fastlane (/Users/user/Documents/app-name/app/vendor/bundle/ruby/2.6.0/bin/fastlane)
FastlaneCore::Interface::FastlaneCrash: [!] No code signing identity found and can not create a new one because you enabled `readonly`
  /Users/user/Documents/app-name/app/vendor/bundle/ruby/2.6.0/gems/fastlane-2.144.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!'
  /Users/user/Documents/app-name/app/vendor/bundle/ruby/2.6.0/gems/fastlane-2.144.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /Users/user/Documents/app-name/app/vendor/bundle/ruby/2.6.0/gems/fastlane-2.144.0/match/lib/match/runner.rb:158:in `fetch_certificate'
  /Users/user/Documents/app-name/app/vendor/bundle/ruby/2.6.0/gems/fastlane-2.144.0/match/lib/match/runner.rb:92:in `run'
  /Users/user/Documents/app-name/app/vendor/bundle/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/actions/sync_code_signing.rb:13:in `run'
  /Users/user/Documents/app-name/app/vendor/bundle/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
  /Users/user/Documents/app-name/app/vendor/bundle/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/user/Documents/app-name/app/vendor/bundle/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
  /Users/user/Documents/app-name/app/vendor/bundle/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Users/user/Documents/app-name/app/vendor/bundle/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Users/user/Documents/app-name/app/vendor/bundle/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/user/Documents/app-name/app/vendor/bundle/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:39:in `block (2 levels) in parsing_binding'
  /Users/user/Documents/app-name/app/vendor/bundle/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/user/Documents/app-name/app/vendor/bundle/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/user/Documents/app-name/app/vendor/bundle/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/user/Documents/app-name/app/vendor/bundle/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/user/Documents/app-name/app/vendor/bundle/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Users/user/Documents/app-name/app/vendor/bundle/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/user/Documents/app-name/app/vendor/bundle/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/user/Documents/app-name/app/vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/user/Documents/app-name/app/vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/user/Documents/app-name/app/vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/user/Documents/app-name/app/vendor/bundle/ruby/2.6.0/gems/fastlane-2.144.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/user/Documents/app-name/app/vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/user/Documents/app-name/app/vendor/bundle/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
  /Users/user/Documents/app-name/app/vendor/bundle/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/user/Documents/app-name/app/vendor/bundle/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Users/user/Documents/app-name/app/vendor/bundle/ruby/2.6.0/gems/fastlane-2.144.0/bin/fastlane:23:in `<top (required)>'
  /Users/user/Documents/app-name/app/vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `load'
  /Users/user/Documents/app-name/app/vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `<top (required)>'
 </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.3                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.21.1 (Apple Git-122.3)                           |
| Installation Source         | ~/Documents/app-name/app/vendor/bundle/ruby/2.6.0/bin/fastlane  |
| Host                        | Mac OS X 10.15.3 (19D76)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.3.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
min_fastlane_version '2.53.1'
skip_docs # don't generate a Readme.md in the fastlane folder
ensure_bundle_exec # fails if not called via bundle exec

platform :ios do
  private_lane :copy_firebase do |options|
    # see: https://medium.com/@gregoire.frileux/how-to-manage-multiple-environments-dev-staging-prod-for-firebase-with-react-native-app-205c7c1a5e35
    filename =
      'GoogleService-Info.plist'

    destination = 'ios/AppName'

    configuration = options[:configuration]

    source = "ios/Firebase/#{configuration}/#{filename}"

    Dir.chdir('..') { sh('cp', source, destination) }
  end

  private_lane :build do |options|
    configuration = options[:configuration]

    build_number = commit_timestamp(seconds: 10)

    increment_build_number(
      build_number: build_number, xcodeproj: 'ios/AppName.xcodeproj'
    )

    copy_firebase(configuration: configuration)

    build_ios_app(configuration: configuration)
  end

  lane :prepare_debug do
    copy_firebase(configuration: 'Debug')
  end

  lane :certificates do
    match(app_identifier: '...', type: 'appstore', readonly: true)
  end

  lane :test_flight do
    certificates

    ipa_path = build(configuration: 'Release')

    upload_to_testflight(
      demo_account_required: true,
      ipa: ipa_path,
      uses_non_exempt_encryption: false,
      beta_app_review_info: {
        ...
      }
    )
  end

  lane :release do
    certificates

    ipa_path = build(configuration: 'Release')

    puts 'TODO: upload to app store connect'
  end
end

platform :android do
  private_lane :copy_gradle_properties do
    Dir.chdir('..') do
      sh(
        command:
          "cat #{
            ENV['ANDROID_RELEASE_GRADLE_PROPERTIES']
          } >> android/app/gradle.properties",
        log: false
      )
    end
  end

  private_lane :build do |options|
    build_type = options[:build_type]

    copy_gradle_properties

    build_android_app(task: 'clean', project_dir: 'android/')

    build_number = commit_timestamp(seconds: 10)

    android_set_version_code(
      version_code: build_number, gradle_file: 'android/app/build.gradle'
    )

    android_set_version_name(
      version_name: '2.1.4', gradle_file: 'android/app/build.gradle'
    )

    build_android_app(
      task: 'bundle', build_type: build_type, project_dir: 'android/'
    )

    aab_path = Actions.lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH]
    aab_path
  end

  lane :internal do
    aab_path = build(build_type: 'Release')

    upload_to_play_store(
      track: 'internal', aab: aab_path, skip_upload_apk: true
    )
  end

  lane :alpha do
    upload_to_play_store(track: 'internal', track_promote_to: 'alpha')
  end

  lane :release do
    upload_to_play_store(track: 'alpha', track_promote_to: 'production')
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier '...' # The bundle identifier of your app
apple_id '....' # Your Apple email address
itc_team_id '...' # App Store Connect Team ID
team_id '...' # Developer team id

package_name '...'
json_key_file ENV['GOOGLE_PLAY_ACCESS_KEY'] # used by supply to authenticate with google play

```
</details>

<details><summary>`./fastlane/Matchfile`</summary>

```ruby
username '...'
keychain_name ENV['MATCH_KEYCHAIN_NAME']
keychain_password ENV['MATCH_KEYCHAIN_PASSWORD']

storage_mode 's3'
s3_region ENV['AWS_DEFAULT_REGION']
s3_access_key ENV['AWS_ACCESS_KEY_ID']
s3_secret_access_key ENV['AWS_SECRET_ACCESS_KEY']
s3_bucket ENV['S3_BUCKET_NAME']

platform 'ios'

generate_apple_certs true

skip_docs true
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.144.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                             | Version | Update-Status |
| ---------------------------------- | ------- | ------------- |
| fastlane-plugin-versioning_android | 0.1.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                | Version      |
| ---------------------------------- | ------------ |
| did_you_mean                       | 1.3.0        |
| bundler                            | 2.1.4        |
| CFPropertyList                     | 3.0.2        |
| concurrent-ruby                    | 1.1.6        |
| i18n                               | 0.9.5        |
| minitest                           | 5.14.0       |
| thread_safe                        | 0.3.6        |
| tzinfo                             | 1.2.6        |
| activesupport                      | 4.2.11.1     |
| public_suffix                      | 2.0.5        |
| addressable                        | 2.7.0        |
| httpclient                         | 2.8.3        |
| json                               | 2.3.0        |
| algoliasearch                      | 1.27.1       |
| atomos                             | 0.1.3        |
| aws-eventstream                    | 1.0.3        |
| aws-partitions                     | 1.288.0      |
| aws-sigv4                          | 1.1.1        |
| jmespath                           | 1.4.0        |
| aws-sdk-core                       | 3.92.0       |
| aws-sdk-kms                        | 1.30.0       |
| aws-sdk-s3                         | 1.61.1       |
| babosa                             | 1.0.3        |
| claide                             | 1.0.3        |
| fuzzy_match                        | 2.0.4        |
| nap                                | 1.1.0        |
| netrc                              | 0.11.0       |
| ffi                                | 1.12.2       |
| ethon                              | 0.12.0       |
| typhoeus                           | 1.3.1        |
| cocoapods-core                     | 1.9.1        |
| cocoapods-deintegrate              | 1.0.4        |
| cocoapods-downloader               | 1.3.0        |
| cocoapods-plugins                  | 1.0.0        |
| cocoapods-search                   | 1.0.0        |
| cocoapods-stats                    | 1.1.0        |
| cocoapods-trunk                    | 1.4.1        |
| cocoapods-try                      | 1.1.0        |
| colored2                           | 3.1.2        |
| escape                             | 0.0.4        |
| fourflusher                        | 2.3.1        |
| gh_inspector                       | 1.1.3        |
| molinillo                          | 0.6.6        |
| ruby-macho                         | 1.4.0        |
| nanaimo                            | 0.2.6        |
| xcodeproj                          | 1.15.0       |
| cocoapods                          | 1.9.1        |
| colored                            | 1.2          |
| highline                           | 1.7.10       |
| commander-fastlane                 | 4.4.6        |
| declarative                        | 0.0.10       |
| declarative-option                 | 0.1.0        |
| digest-crc                         | 0.5.1        |
| unf_ext                            | 0.0.7.6      |
| unf                                | 0.1.4        |
| domain_name                        | 0.5.20190701 |
| dotenv                             | 2.7.5        |
| emoji_regex                        | 1.0.1        |
| excon                              | 0.73.0       |
| multipart-post                     | 2.0.0        |
| faraday                            | 0.17.3       |
| http-cookie                        | 1.0.3        |
| faraday-cookie_jar                 | 0.0.6        |
| faraday_middleware                 | 0.13.1       |
| fastimage                          | 2.1.7        |
| jwt                                | 2.1.0        |
| memoist                            | 0.16.2       |
| multi_json                         | 1.14.1       |
| os                                 | 1.0.1        |
| signet                             | 0.13.2       |
| googleauth                         | 0.11.0       |
| mini_mime                          | 1.0.2        |
| uber                               | 0.1.0        |
| representable                      | 3.0.4        |
| retriable                          | 3.1.2        |
| google-api-client                  | 0.36.4       |
| google-cloud-env                   | 1.3.1        |
| google-cloud-errors                | 1.0.0        |
| google-cloud-core                  | 1.5.0        |
| google-cloud-storage               | 1.25.1       |
| mini_magick                        | 4.10.1       |
| multi_xml                          | 0.6.0        |
| plist                              | 3.5.0        |
| rubyzip                            | 1.3.0        |
| security                           | 0.1.3        |
| naturally                          | 2.2.0        |
| simctl                             | 1.6.8        |
| slack-notifier                     | 2.3.2        |
| terminal-notifier                  | 2.0.0        |
| unicode-display_width              | 1.7.0        |
| terminal-table                     | 1.8.0        |
| tty-screen                         | 0.7.1        |
| tty-cursor                         | 0.7.1        |
| tty-spinner                        | 0.9.3        |
| word_wrap                          | 1.0.0        |
| rouge                              | 2.0.7        |
| xcpretty                           | 0.3.0        |
| xcpretty-travis-formatter          | 1.0.0        |
| fastlane-plugin-versioning_android | 0.1.0        |
| prettier                           | 0.18.0       |
</details>

*generated on:* **2020-03-26**
</details>

**Comment by joshdholtz** [comment]
@warrify Thanks for reporting this! I will look into this for you 😊

**Comment by philmcmahon** [comment]
We're also experiencing this issue.

`fastlane match development --s3_region eu-west-1  --s3_access_key <key>  --s3_secret_access_key <secret> --s3_bucket <bucket> --verbose --team_id <id> --storage_mode s3`

works, but after running that this command fails with the error described above:

`fastlane match development --s3_region eu-west-1  --s3_access_key <key>  --s3_secret_access_key <secret> --s3_bucket <bucket> --verbose --team_id <id> --storage_mode s3 --readonly`

**Comment by rromanchuk** [comment]
Just got this for a release lane, @joshdholtz since i can repro consistently ill dig in. Not sure the regression is just `2.7.0` related because it was working before. 

[update] to repo you must trigger a profile re-install, so maybe it was always broken in 2.7.0, but it wasn't until new TOS required new dist profiles. 

The in place modification `.gsub!`  of value true threw the frozen warning.  Using a copy fixes the problem `v = v.gsub()`.  It's probably from `Symbol#to_s` returning frozen strings now.

`~/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/base.rb:298`

```ruby
def inspect_value
  self.attributes.map do |k|
        v = self.send(k).inspect
        v.gsub!("\n", "\n\t") # to align nested elements

        "\t#{k}=#{v}"
  end.join(", \n")
end
```

Here were the values (i forgot to print the keys) 

> "[redacted cert id]"
> "Distribution"
> "Issued"
> 2019-10-10 05:56:52 UTC
> 2020-10-09 05:46:52 UTC
> "team"
> "[redacted itc_team_name]"
> "[redacted team id]"
> "[redacted itc_team_id]"
> true

**Comment by odanu** [comment]
I can confirm having the same issue, with `development`.
Running:
```fastlane match development```
than
```fastlane match development --readonly```
fails finding the development certificate.

**Comment by warrify** [comment]
Nice #16335 got labeled for inclusion in next release. Looking forward to checking it out 👍

**Comment by mmadjer** [comment]
Hi, We got the same issue using Github though. Any update on this?

**Comment by springcoil** [comment]
I was able to fix this by doing the following in my Fastfile. 
```     generate_apple_certs: "false",
      type: "development"
    )
```
Previously I had appstore twice, and generate_apple_certs: "true".

**Comment by mmadjer** [comment]
I'll give that a try.
And do you still used/set `readonly: true`?
