### ISSUE TITLE
FASTLANE_SESSION for GitHub Actions

### ISSUE THREAD

**Issue by BalazsSzamody** [fastlane/fastlane#16224]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Authorise Github-hosted runner.

#### Question Description

I am an iOS Dev from Australia. And I am in a bit of a pickle with GitHub Actions. I would like to use it for building and uploading to TestFlight, however as the Runner is located in Atalanta in the US (or at least that's what the 2FA pop-up shows), and I am in Sydney I can't use `spaceauth` to provide a `FASTLANE_SESSION` token. I know it's not really an issue with Fastlane, and it's more like a limitation forced by Apple, but if any of you have faced similar issues, solved it and allowed to share the solution it would be highly appreciated.

Or maybe if someone could recommend a safe free VPN service in the US that is ok to use for spaceauth.

Thanks in advance

**Comment by max-ott** [comment]
Did you check out https://docs.fastlane.tools/best-practices/continuous-integration/ ?

**Comment by BalazsSzamody** [comment]
@max-ott Yes I checked it, that is why I know that there is a limitation, that is why I was asking **if maybe** someone has a working workaround for it.

> Please note:
>
> An Apple ID session is only valid for a certain region, meaning if your CI system is in a different region than your local machine, you might run into issues
An Apple ID session is only valid for up to a month, meaning you'll have to generate a new session every month. Usually you'd only know about it when your build starts failing
Unfortunately there is nothing fastlane can do better in this regard, as these are technical limitations on how App Store Connect sessions are handled.
