### ISSUE TITLE
`IMG_APPEARS_CORRUPT` on screenshots upload using deliver

### ISSUE THREAD

**Issue by wckd1** [fastlane/fastlane#16229]
### Question Checklist

- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] Updated fastlane to the latest version
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
`bundle exec fastlane metadata` failed with error:
`[!] [IMG_APPEARS_CORRUPT] That file is corrupt. It may help to open it in an image editor and resave it before trying again. (Spaceship::UnexpectedResponse)`

#### Question Description
Fastfile:
`lane :metadata do
    deliver(
        force: true,
        app_identifier: ENV['APP_ID'],
        username: ENV['APPLE_ID'],
        team_id: ENV['TEAM_ID'],
        metadata_path: "./fastlane/metadata",
        overwrite_screenshots: true,
        screenshots_path: "./screenshots",
        skip_binary_upload: true
    )
end`

Screenshots was successfully uploaded manually, but failed using `fastline delivery`.

<details>
<summary>Output</summary>

[✔] Activating language en-US... 
[✔] Uploading metadata to App Store Connect 
[17:50:38]: Successfully uploaded set of metadata to App Store Connect
[17:50:40]: Starting with the upload of screenshots...
[17:50:40]: Removing all previously uploaded screenshots...
[✔] Activating language en-US... 
[17:50:42]: Uploading 2 screenshots for language en-US
[17:50:42]: Uploading './screenshots/en-US/iPhone 8 Plus-Screen1.png'...
[17:50:45]: Uploading './screenshots/en-US/iPhone XS Max-Screen1.png'...

[17:50:51]: [IMG_APPEARS_CORRUPT] That file is corrupt. It may help to open it in an image editor and resave it before trying again.

[17:50:51]: fastlane finished with errors

Traceback (most recent call last):
	38: from /Users/rk.dev/gem/bin/fastlane:26:in `<main>'
	37: from /Users/rk.dev/gem/bin/fastlane:26:in `load'
	36: from /Users/rk.dev/gem/gems/fastlane-2.144.0/bin/fastlane:23:in `<top (required)>'
	35: from /Users/rk.dev/gem/gems/fastlane-2.144.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	34: from /Users/rk.dev/gem/gems/fastlane-2.144.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	33: from /Users/rk.dev/gem/gems/fastlane-2.144.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	32: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	31: from /Users/rk.dev/gem/gems/fastlane-2.144.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	30: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	29: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	28: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	27: from /Users/rk.dev/gem/gems/fastlane-2.144.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	26: from /Users/rk.dev/gem/gems/fastlane-2.144.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	25: from /Users/rk.dev/gem/gems/fastlane-2.144.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	24: from /Users/rk.dev/gem/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	23: from /Users/rk.dev/gem/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	22: from /Users/rk.dev/gem/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	21: from /Users/rk.dev/gem/gems/fastlane-2.144.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	20: from Fastfile:129:in `block (2 levels) in parsing_binding'
	19: from /Users/rk.dev/gem/gems/fastlane-2.144.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	18: from /Users/rk.dev/gem/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	17: from /Users/rk.dev/gem/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	16: from /Users/rk.dev/gem/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	15: from /Users/rk.dev/gem/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
	14: from /Users/rk.dev/gem/gems/fastlane-2.144.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	13: from /Users/rk.dev/gem/gems/fastlane-2.144.0/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
	12: from /Users/rk.dev/gem/gems/fastlane-2.144.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:17:in `run'
	11: from /Users/rk.dev/gem/gems/fastlane-2.144.0/deliver/lib/deliver/runner.rb:38:in `run'
	10: from /Users/rk.dev/gem/gems/fastlane-2.144.0/deliver/lib/deliver/runner.rb:121:in `upload_metadata'
	 9: from /Users/rk.dev/gem/gems/fastlane-2.144.0/deliver/lib/deliver/upload_screenshots.rb:49:in `upload'
	 8: from /Users/rk.dev/gem/gems/fastlane-2.144.0/deliver/lib/deliver/upload_screenshots.rb:49:in `each'
	 7: from /Users/rk.dev/gem/gems/fastlane-2.144.0/deliver/lib/deliver/upload_screenshots.rb:51:in `block in upload'
	 6: from /Users/rk.dev/gem/gems/fastlane-2.144.0/deliver/lib/deliver/upload_screenshots.rb:51:in `each'
	 5: from /Users/rk.dev/gem/gems/fastlane-2.144.0/deliver/lib/deliver/upload_screenshots.rb:64:in `block (2 levels) in upload'
	 4: from /Users/rk.dev/gem/gems/fastlane-2.144.0/spaceship/lib/spaceship/tunes/app_version.rb:518:in `upload_screenshot!'
	 3: from /Users/rk.dev/gem/gems/fastlane-2.144.0/spaceship/lib/spaceship/tunes/tunes_client.rb:876:in `upload_screenshot'
	 2: from /Users/rk.dev/gem/gems/fastlane-2.144.0/spaceship/lib/spaceship/du/du_client.rb:22:in `upload_screenshot'
	 1: from /Users/rk.dev/gem/gems/fastlane-2.144.0/spaceship/lib/spaceship/du/du_client.rb:105:in `upload_file'
/Users/rk.dev/gem/gems/fastlane-2.144.0/spaceship/lib/spaceship/du/du_client.rb:133:in `parse_upload_response': [!] [IMG_APPEARS_CORRUPT] That file is corrupt. It may help to open it in an image editor and resave it before trying again. (Spaceship::UnexpectedResponse)
</details>

**Comment by max-ott** [comment]
What's the file format?

**Comment by wckd1** [comment]
Screenshots are made by `snapshot` and framed by `frameit`. It's `.png`.
I tried to resave it in `.jpg` and it works, but quality is really bad and has a lot of glitches.

**Comment by eAi** [comment]
For anyone else that comes across this: I saw this error because I didn't have Xcode installed on the machine doing the upload. I think the error is happening because Fastlane is trying to convert the icon using some tool and failing because it isn't installed.
