### ISSUE TITLE
bundler: failed to load command: fastlane (/usr/local/bin/fastlane) TypeError: [!] no implicit conversion of nil into String

### ISSUE THREAD

**Issue by wtb2015** [fastlane/fastlane#16232]
### Question Checklist

- [ x] Updated fastlane to the latest version
- [ x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
fast lane screen-grab
no

#### Question Description
 Error Message: bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
TypeError: [!] no implicit conversion of nil into String
------------------------------
Documentation has been read 3 or 4 times and have worked on this problem for 3 days now but screen grab continues to produce the same error and it is not clear what the problem is. Can you give a suggestion please ? The other similar questions were closed with no clear answer. 
-------------------------------------------------------------------
bundle exec fastlane screengrab
[✔] 🚀 
[23:11:55]: Successfully loaded '/Users/imac-1604/StudioProjects/english-quiz/fastlane/Screengrabfile' 📄

+----------------------------+--------------------------------------------------------------------------+
|                           Detected Values from './fastlane/Screengrabfile'                            |
+----------------------------+--------------------------------------------------------------------------+
| app_package_name           | com.english_alps.EnglishQuiz.fastlane                                    |
| locales                    | ["en-US", "fr-FR", "it-IT", "ru-RU", "es-ES", "de-DE", "ar-AR", "fa-FA"] |
| clear_previous_screenshots | true                                                                     |
+----------------------------+--------------------------------------------------------------------------+

+-----------------------------+--------------------------------------------------------------------------+
|                                     Summary for screengrab 2.144.0                                     |
+-----------------------------+--------------------------------------------------------------------------+
| tests_package_name          | com.english_alps.EnglishQuiz.fastlane.test                               |
| locales                     | ["en-US", "fr-FR", "it-IT", "ru-RU", "es-ES", "de-DE", "ar-AR", "fa-FA"] |
| clear_previous_screenshots  | true                                                                     |
| output_directory            | fastlane/metadata/android                                                |
| skip_open_summary           | false                                                                    |
| app_package_name            | com.english_alps.EnglishQuiz.fastlane                                    |
| test_instrumentation_runner | androidx.test.runner.AndroidJUnitRunner                                  |
| ending_locale               | en-US                                                                    |
| use_adb_root                | false                                                                    |
| device_type                 | phone                                                                    |
| exit_on_test_failure        | true                                                                     |
| reinstall_app               | false                                                                    |
| use_timestamp_suffix        | true                                                                     |
+-----------------------------+--------------------------------------------------------------------------+

[23:11:55]: Limiting the test classes run by `screengrab` to just those that generate screenshots can make runs faster.
[23:11:55]: Consider using the :use_tests_in_classes or :use_tests_in_packages option, and organize your tests accordingly.
[23:11:55]: Clearing phoneScreenshots within fastlane/metadata/android

Looking for related GitHub issues on fastlane/fastlane...

➡️  bundler: failed to load command: fastlane  TypeError: [!] no implicit conversion of nil into String
    https://github.com/fastlane/fastlane/issues/15714 [closed] 6 💬
    a week ago

➡️  How to upload Multiple apps screenshots and meta data upload to appstore 
    https://github.com/fastlane/fastlane/issues/15885 [closed] 5 💬
    2 weeks ago

➡️  no implicit conversion of nil into String
    https://github.com/fastlane/fastlane/issues/14830 [closed] 4 💬
    02 Aug 2019

and 79 more at: https://github.com/fastlane/fastlane/search?q=no%20implicit%20conversion%20of%20nil%20into%20String&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
TypeError: [!] no implicit conversion of nil into String
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/helper/adb_helper.rb:27:in `expand_path'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/helper/adb_helper.rb:27:in `initialize'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/screengrab/lib/screengrab/runner.rb:84:in `new'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/screengrab/lib/screengrab/runner.rb:84:in `select_device'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/screengrab/lib/screengrab/runner.rb:57:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/screengrab/lib/screengrab/commands_generator.rb:49:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/screengrab/lib/screengrab/commands_generator.rb:67:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/screengrab/lib/screengrab/commands_generator.rb:19:in `start'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.144.0/bin/fastlane:23:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>'
imac-1604@192 english-quiz % fastlane env
[✔] 🚀 
[23:20:12]: fastlane detected a Gemfile in the current directory
[23:20:12]: However, it seems like you didn't use `bundle exec`
[23:20:12]: To launch fastlane faster, please use
[23:20:12]: 
[23:20:12]: $ bundle exec fastlane env
[23:20:12]: 
[23:20:12]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[23:20:14]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.4                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.1 (Apple Git-126)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.4 (19E266)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.4                                                           |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Capture screenshots and upload to Play Store" 
  lane :screenshots do
    capture_android_screenshots
    upload_to_play_store
  end

  desc "Build debug and test APK for screenshots"
  lane :build_for_screengrab do
    build_android_app(
      task: 'assemble',
      build_type: 'Debug'
    )
    build_android_app(
      task: 'assemble',
      build_type: 'AndroidTest'
    )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("/Users/imac-1604/StudioProjects/english-quiz/fastlane/api-7297105794346112168-295115-eeb35579595e.json") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("com.english_alps.EnglishQuiz.fastlane") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.144.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.73.0       |
| faraday                   | 0.17.3       |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.0.1        |
| googleauth                | 0.11.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.5.1        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-eventstream           | 1.0.3        |
| aws-sigv4                 | 1.1.1        |
| aws-sdk-core              | 3.92.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.61.1       |
| CFPropertyList            | 3.0.2        |
| unf_ext                   | 0.0.7.7      |
| json                      | 2.3.0        |
| signet                    | 0.13.2       |
| aws-partitions            | 1.290.0      |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-03-30**
</details>

**Comment by staale** [comment]
I had this issue, turned out that the gc_keys.json file was missing.

**Comment by wtb2015** [comment]
Thanks for the input. 
Below is the output from the validate_play_store_json_key command which shows fastlane is able to validate the play_store_json_key. 

imac-1604@192 fastlane % sudo bundle exec  fastlane run validate_play_store_json_key json_key /Users/imac-1604/StudioProjects/english-quiz/fastlane/api-1234eb3e.json
[✔] 🚀 
[10:23:40]: ------------------------------------------
[10:23:40]: --- Step: validate_play_store_json_key ---
[10:23:40]: ------------------------------------------

+----------+--------------------------------------------------------------------------------------------------------+
|                                     Summary for validate_play_store_json_key                                      |
+----------+--------------------------------------------------------------------------------------------------------+
| json_key | /Users/imac-1604/StudioProjects/english-quiz/fastlane/api-1234eb3e.json |
| timeout  | 300                                                                                                    |
+----------+--------------------------------------------------------------------------------------------------------+

[10:23:40]: Successfully established connection to Google Play Store.

**Comment by wtb2015** [comment]
This error appears to be very similar to  https://github.com/fastlane/fastlane/issues/12789 which was related to a race condition when the machine was under load and the issue went away when the machine was not under load.

This error is occurring with me on a Virtual Mac and therefore might also be a race condition. 

Running without Bundler the error is :

/usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/helper/adb_helper.rb:27:in `expand_path': no implicit conversion of nil into String (TypeError)

**Comment by wtb2015** [comment]
missing in .zprofile were the following two lines:
export ANDROID_HOME=~/Library/Android/sdk
--
export ANDROID_SDK_ROOT=~/Library/Android/sdk
