### ISSUE TITLE
[frameit] Android: Unsupported screen size

### ISSUE THREAD

**Issue by Schnodderbalken** [fastlane/fastlane#16236]
### Issue Description
I used fastlane to create Screenshots of our application. At first I tried with an emulated Google Pixel 2 but then I got errors saying:

```
Unsupported screen size [1080, 1920] for path './metadata/android/en-US/images/phoneScreenshots/1Web_1585647128330.png'
```

I had a look at the code (https://github.com/milhauscz/fastlane/blob/2a7e5c827342d0458774b3a1ef7b148c43c31705/frameit/spec/device_spec.rb) and saw these lines:

```describe "valid Android screen sizes" do
it "should detect Google Pixel 3 XL in portrait and landscape based on priority" do
    expect_screen_size_from_file("pixel-portrait{1440x2960}.png", Platform::ANDROID).to eq(Devices::GOOGLE_PIXEL_3_XL)
    expect_screen_size_from_file("pixel-landscape{2960x1440}.png", Platform::ANDROID).to eq(Devices::GOOGLE_PIXEL_3_XL)
end
```

but no line indicating that the resolution of the **Pixel 2** was a valid input for frameit.
So I reran the whole procedure with an emulated **Pixel 3 XL**.
To my surprise I got the very same error (this time with the display resolution of the Pixel 3):

```
Unsupported screen size [1440, 2960] for path './1Web_1585662570754.png'
```

The funny thing is that we have the very same application running on iOS where everything works fine. I use the same Framefile and Screengrabfile in both projects.

**Content of my Framefile.json**:
<details>
  <pre> 
{
  "device_frame_version": "latest",
  "default": {
    "title": {
      "color": "#ffffff",
      "font": "../Roboto/Roboto-Black.ttf"
    },
    "background": "./background.png",
    "padding": 50,
    "show_complete_frame": false,
    "stack_title" : false,
    "title_below_image": false,
    "title_min_height" : 400,
    "font_scale_factor": 0.15,
    "frame": "WHITE"
  },
  "data": [
    {
      "filter": "1Web",
      "frame": "WHITE"
    },
    {
      "filter": "2Web",
      "frame": "WHITE"
    }
  ]
}
 </pre>
</details>

The Framefile is actually being read. When I put a syntax error into it and execute `fastlane frameit android` I get the respective error.

I haven't found any helping issues here. The only similar issues were related to iOS but never to android.

##### Command executed
`fastlane frameit android`

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre> 
[✔] 🚀 
[11:37:33]: fastlane detected a Gemfile in the current directory
[11:37:33]: However, it seems like you didn't use `bundle exec`
[11:37:33]: To launch fastlane faster, please use
[11:37:33]: 
[11:37:33]: $ bundle exec fastlane frameit android
[11:37:33]: 
[11:37:33]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[11:37:34]: Using device frames version 'latest'
[11:37:34]: Unsupported screen size [1440, 2960] for path './4EdgeDetection_1585662618141.png'
[11:37:34]: Unsupported screen size [1440, 2960] for path './5PerfectSize_1585662630571.png'
[11:37:34]: Unsupported screen size [2960, 1440] for path './1Web_1585662570754 Kopie.png'
[11:37:34]: Unsupported screen size [1440, 2960] for path './2Web_1585662579645.png'
[11:37:34]: Unsupported screen size [1440, 2960] for path './1Web_1585662570754.png'
 </pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.1                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.21.1 (Apple Git-122.3)                           |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.1 (19B88)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.3.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.141.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><pre><summary><b>Loaded gems</b></summary>
| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.13.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.72.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.13.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.11.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.5.1        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| bundler                   | 2.1.4        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>

*generated on:* **2020-04-01**
</details>

### So my basic question: 
How is it possible that the tool that is meant to create those screenshots is capable of creating ones with a false resolution? And where is documented which resolutions are valid? What am I doing wrong? Which resolution do my screenshots have to have in order for frameit to accept them?

Btw: if you wonder why I am not on the latest version of fastlane - the newest version (2.144.0) produces this error: https://github.com/fastlane/fastlane/issues/16122 so I had to downgrade to 2.141.0

**Comment by wellavelino** [comment]
Was wondering how do we execute frame it android from Fastlane?
