### ISSUE TITLE
Fastlane supply - android metadata upload fails

### ISSUE THREAD

**Issue by Glasi731** [fastlane/fastlane#16239]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

We are trying to use fastlane to automate binary and metadata uploads for our android project.
Building works like a charm, also uploading the binaries is  working if upload of metadata is disabled.

When running `fastlane android deployPaidRelease` th metadata upload fails for some reason `badRequest: The requested language is not currently supported: und.`.

See the attached Fastfile and Appfile for details (we use two flavors with different metadata directories).

Here the fastlane directory tree:
<details><pre>
.
├── Appfile
├── Fastfile
├── README.md
├── metadata-free
│   └── android
│       ├── de-DE
│       │   ├── changelogs
│       │   │   └── 3.11.2.txt
│       │   ├── full_description.txt
│       │   ├── images
│       │   │   ├── phoneScreenshots
│       │   │   ├── sevenInchScreenshots
│       │   │   ├── tenInchScreenshots
│       │   │   ├── tvScreenshots
│       │   │   └── wearScreenshots
│       │   ├── short_description.txt
│       │   ├── title.txt
│       │   └── video.txt
│       ├── en-US
│       │   ├── changelogs
│       │   │   └── 3.11.2.txt
│       │   ├── full_description.txt
│       │   ├── images
│       │   │   ├── phoneScreenshots
│       │   │   ├── sevenInchScreenshots
│       │   │   ├── tenInchScreenshots
│       │   │   ├── tvScreenshots
│       │   │   └── wearScreenshots
│       │   ├── short_description.txt
│       │   ├── title.txt
│       │   └── video.txt
│       ├── es-ES
│       │   ├── changelogs
│       │   │   └── 3.11.2.txt
│       │   ├── full_description.txt
│       │   ├── images
│       │   │   ├── phoneScreenshots
│       │   │   ├── sevenInchScreenshots
│       │   │   ├── tenInchScreenshots
│       │   │   ├── tvScreenshots
│       │   │   └── wearScreenshots
│       │   ├── short_description.txt
│       │   ├── title.txt
│       │   └── video.txt
│       ├── fr-FR
│       │   ├── changelogs
│       │   │   └── 3.11.2.txt
│       │   ├── full_description.txt
│       │   ├── images
│       │   │   ├── phoneScreenshots
│       │   │   ├── sevenInchScreenshots
│       │   │   ├── tenInchScreenshots
│       │   │   ├── tvScreenshots
│       │   │   └── wearScreenshots
│       │   ├── short_description.txt
│       │   ├── title.txt
│       │   └── video.txt
│       ├── it-IT
│       │   ├── changelogs
│       │   │   └── 3.11.2.txt
│       │   ├── full_description.txt
│       │   ├── images
│       │   │   ├── phoneScreenshots
│       │   │   ├── sevenInchScreenshots
│       │   │   ├── tenInchScreenshots
│       │   │   ├── tvScreenshots
│       │   │   └── wearScreenshots
│       │   ├── short_description.txt
│       │   ├── title.txt
│       │   └── video.txt
│       ├── ja-JP
│       │   ├── changelogs
│       │   │   └── 3.11.2.txt
│       │   ├── full_description.txt
│       │   ├── images
│       │   │   ├── phoneScreenshots
│       │   │   ├── sevenInchScreenshots
│       │   │   ├── tenInchScreenshots
│       │   │   ├── tvScreenshots
│       │   │   └── wearScreenshots
│       │   ├── short_description.txt
│       │   ├── title.txt
│       │   └── video.txt
│       ├── ko-KR
│       │   ├── changelogs
│       │   │   └── 3.11.2.txt
│       │   ├── full_description.txt
│       │   ├── images
│       │   │   ├── phoneScreenshots
│       │   │   ├── sevenInchScreenshots
│       │   │   ├── tenInchScreenshots
│       │   │   ├── tvScreenshots
│       │   │   └── wearScreenshots
│       │   ├── short_description.txt
│       │   ├── title.txt
│       │   └── video.txt
│       ├── nl-NL
│       │   ├── changelogs
│       │   │   └── 3.11.2.txt
│       │   ├── full_description.txt
│       │   ├── images
│       │   │   ├── phoneScreenshots
│       │   │   ├── sevenInchScreenshots
│       │   │   ├── tenInchScreenshots
│       │   │   ├── tvScreenshots
│       │   │   └── wearScreenshots
│       │   ├── short_description.txt
│       │   ├── title.txt
│       │   └── video.txt
│       ├── pt-BR
│       │   ├── changelogs
│       │   │   └── 3.11.2.txt
│       │   ├── full_description.txt
│       │   ├── images
│       │   │   ├── phoneScreenshots
│       │   │   ├── sevenInchScreenshots
│       │   │   ├── tenInchScreenshots
│       │   │   ├── tvScreenshots
│       │   │   └── wearScreenshots
│       │   ├── short_description.txt
│       │   ├── title.txt
│       │   └── video.txt
│       └── pt-PT
│           ├── changelogs
│           │   └── 3.11.2.txt
│           ├── full_description.txt
│           ├── images
│           │   ├── phoneScreenshots
│           │   ├── sevenInchScreenshots
│           │   ├── tenInchScreenshots
│           │   ├── tvScreenshots
│           │   └── wearScreenshots
│           ├── short_description.txt
│           ├── title.txt
│           └── video.txt
├── metadata-paid
│   └── android
│       ├── de-DE
│       │   ├── changelogs
│       │   │   └── 3.11.2.txt
│       │   ├── full_description.txt
│       │   ├── images
│       │   │   ├── phoneScreenshots
│       │   │   ├── sevenInchScreenshots
│       │   │   ├── tenInchScreenshots
│       │   │   ├── tvScreenshots
│       │   │   └── wearScreenshots
│       │   ├── short_description.txt
│       │   ├── title.txt
│       │   └── video.txt
│       ├── en-US
│       │   ├── changelogs
│       │   │   └── 3.11.2.txt
│       │   ├── full_description.txt
│       │   ├── images
│       │   │   ├── phoneScreenshots
│       │   │   ├── sevenInchScreenshots
│       │   │   ├── tenInchScreenshots
│       │   │   ├── tvScreenshots
│       │   │   └── wearScreenshots
│       │   ├── short_description.txt
│       │   ├── title.txt
│       │   └── video.txt
│       ├── es-ES
│       │   ├── changelogs
│       │   │   └── 3.11.2.txt
│       │   ├── full_description.txt
│       │   ├── images
│       │   │   ├── phoneScreenshots
│       │   │   ├── sevenInchScreenshots
│       │   │   ├── tenInchScreenshots
│       │   │   ├── tvScreenshots
│       │   │   └── wearScreenshots
│       │   ├── short_description.txt
│       │   ├── title.txt
│       │   └── video.txt
│       ├── fr-FR
│       │   ├── changelogs
│       │   │   └── 3.11.2.txt
│       │   ├── full_description.txt
│       │   ├── images
│       │   │   ├── phoneScreenshots
│       │   │   ├── sevenInchScreenshots
│       │   │   ├── tenInchScreenshots
│       │   │   ├── tvScreenshots
│       │   │   └── wearScreenshots
│       │   ├── short_description.txt
│       │   ├── title.txt
│       │   └── video.txt
│       ├── it-IT
│       │   ├── changelogs
│       │   │   └── 3.11.2.txt
│       │   ├── full_description.txt
│       │   ├── images
│       │   │   ├── phoneScreenshots
│       │   │   ├── sevenInchScreenshots
│       │   │   ├── tenInchScreenshots
│       │   │   ├── tvScreenshots
│       │   │   └── wearScreenshots
│       │   ├── short_description.txt
│       │   ├── title.txt
│       │   └── video.txt
│       ├── ja-JP
│       │   ├── changelogs
│       │   │   └── 3.11.2.txt
│       │   ├── full_description.txt
│       │   ├── images
│       │   │   ├── phoneScreenshots
│       │   │   ├── sevenInchScreenshots
│       │   │   ├── tenInchScreenshots
│       │   │   ├── tvScreenshots
│       │   │   └── wearScreenshots
│       │   ├── short_description.txt
│       │   ├── title.txt
│       │   └── video.txt
│       ├── ko-KR
│       │   ├── changelogs
│       │   │   └── 3.11.2.txt
│       │   ├── full_description.txt
│       │   ├── images
│       │   │   ├── phoneScreenshots
│       │   │   ├── sevenInchScreenshots
│       │   │   ├── tenInchScreenshots
│       │   │   ├── tvScreenshots
│       │   │   └── wearScreenshots
│       │   ├── short_description.txt
│       │   ├── title.txt
│       │   └── video.txt
│       ├── nl-NL
│       │   ├── changelogs
│       │   │   └── 3.11.2.txt
│       │   ├── full_description.txt
│       │   ├── images
│       │   │   ├── phoneScreenshots
│       │   │   ├── sevenInchScreenshots
│       │   │   ├── tenInchScreenshots
│       │   │   ├── tvScreenshots
│       │   │   └── wearScreenshots
│       │   ├── short_description.txt
│       │   ├── title.txt
│       │   └── video.txt
│       ├── pt-BR
│       │   ├── changelogs
│       │   │   └── 3.11.2.txt
│       │   ├── full_description.txt
│       │   ├── images
│       │   │   ├── phoneScreenshots
│       │   │   ├── sevenInchScreenshots
│       │   │   ├── tenInchScreenshots
│       │   │   ├── tvScreenshots
│       │   │   └── wearScreenshots
│       │   ├── short_description.txt
│       │   ├── title.txt
│       │   └── video.txt
│       └── pt-PT
│           ├── changelogs
│           │   └── 3.11.2.txt
│           ├── full_description.txt
│           ├── images
│           │   ├── phoneScreenshots
│           │   ├── sevenInchScreenshots
│           │   ├── tenInchScreenshots
│           │   ├── tvScreenshots
│           │   └── wearScreenshots
│           ├── short_description.txt
│           ├── title.txt
│           └── video.txt
└── report.xml
</pre>
</details>

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>INFO [2020-04-02 09:36:43.26]: ----------------------------------
INFO [2020-04-02 09:36:43.26]: --- Step: upload_to_play_store ---
INFO [2020-04-02 09:36:43.26]: ----------------------------------
DEBUG [2020-04-02 09:36:43.26]: Fetching a new access token from Google...
INFO [2020-04-02 09:36:44.64]: Preparing apk at path '/Users/thomas/git/android/Windfinder_AndroidStudio/windfinder/build/outputs/apk/paid/release/windfinder-paid-release.apk' for upload...
INFO [2020-04-02 09:37:08.39]: 	Version Code: 163
INFO [2020-04-02 09:37:08.39]: Updating track 'internal'...
INFO [2020-04-02 09:37:10.23]: Preparing to upload for language 'android'...
WARN [2020-04-02 09:37:10.38]: Lane Context:
INFO [2020-04-02 09:37:10.38]: {:DEFAULT_PLATFORM=>:android, :PLATFORM_NAME=>:android, :LANE_NAME=>"android deployPaidRelease", :GRADLE_ALL_APK_OUTPUT_PATHS=>["/Users/thomas/git/android/Windfinder_AndroidStudio/windfinder/build/outputs/apk/paid/release/windfinder-paid-release.apk"], :GRADLE_ALL_AAB_OUTPUT_PATHS=>[], :GRADLE_ALL_OUTPUT_JSON_OUTPUT_PATHS=>["/Users/thomas/git/android/Windfinder_AndroidStudio/windfinder/build/outputs/apk/paid/release/output.json"], :GRADLE_ALL_MAPPING_TXT_OUTPUT_PATHS=>["/Users/thomas/git/android/Windfinder_AndroidStudio/windfinder/build/outputs/mapping/paidRelease/mapping.txt"], :GRADLE_APK_OUTPUT_PATH=>"/Users/thomas/git/android/Windfinder_AndroidStudio/windfinder/build/outputs/apk/paid/release/windfinder-paid-release.apk", :GRADLE_OUTPUT_JSON_OUTPUT_PATH=>"/Users/thomas/git/android/Windfinder_AndroidStudio/windfinder/build/outputs/apk/paid/release/output.json", :GRADLE_MAPPING_TXT_OUTPUT_PATH=>"/Users/thomas/git/android/Windfinder_AndroidStudio/windfinder/build/outputs/mapping/paidRelease/mapping.txt"}
ERROR [2020-04-02 09:37:10.38]: badRequest: The requested language is not currently supported: und.
INFO [2020-04-02 09:37:10.38]: Successfully generated documentation at path '/Users/thomas/git/android/Windfinder_AndroidStudio/fastlane/README.md'
ERROR [2020-04-02 09:37:10.39]: fastlane finished with errors
</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.4                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.1 (Apple Git-126)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.4 (19E266)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.4                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :testPaid do
    gradle(task: "test",
    flavor: "paid",
    build_type: "Debug"
    )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assemblePaidRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new paid version to the Google Play Store"
  lane :deployPaidRelease do
    gradle(task: "licensePaidReleaseReport clean assemblePaidRelease")
    upload_to_play_store(metadata_path: './fastlane/metadata-paid', track: 'internal',  skip_upload_images: 'true', skip_upload_screenshots: 'true')
  end

  desc "Deploy a new free version to the Google Play Store"
    lane :deployFreeRelease do
      gradle(task: "licenseFreeReleaseReport clean assembleFreeRelease")
      upload_to_play_store(metadata_path: './fastlane/metadata-free', track: 'internal',  skip_upload_images: 'true', skip_upload_screenshots: 'true')
    end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("api-keyfile.json") # Path to the json secret file - See windfinder keepass for valid keyfile
package_name("com.studioeleven.windfinderpaid")

for_lane :deployFreeRelease do
   package_name("com.studioeleven.windfinder")
end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.144.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.14.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.72.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.7        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.10.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.0        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.292.0      |
| aws-eventstream           | 1.0.3        |
| aws-sigv4                 | 1.1.1        |
| aws-sdk-core              | 3.92.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.61.1       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-04-02**
</details></pre>
</details>

**Comment by Glasi731** [comment]
No idea, I already did a search for the string "und". Beside some description text content there no occurrence was found.

**Comment by evaisse** [comment]
Same error here, using the expo publish:android toolchain. 

My app is on en French store (maybe it's related)

**Comment by iomy** [comment]
Same error here. 
`badRequest: The requested language is not currently supported: und.`
supply was working fine  a couple of weeks before. Supported languages  ["en-US", "de-DE", "fr-FR","zh-CN"]

**Comment by Glasi731** [comment]
Thanks @iomy for the hint. When adding the /android path fragment everything works. The error message was quite misleading.
