### ISSUE TITLE
update_fastlane happens again and again

### ISSUE THREAD

**Issue by SwitchDoors** [fastlane/fastlane#16247]
### Question Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

#### Question Description
When i use update_fastlane in before_all, command line said that fastlane updated. But if i run again i see previous version of fastlane. And update happens again, and again. I expect that it's updated once. Why its heppen?

--- Step: update_fastlane ---
-----------------------------
Looking for updates for fastlane...
Updating fastlane from 2.136.0 to 2.144.0...   
Finished updating fastlane
Cleaning up old versions...
fastlane.tools successfully updated! I will now restart myself...

**Comment by ugenlik** [comment]
Are you using a gemfile or do you have rbenv ? Maybe your GemFile or GemFile.lock  sets fastlane to the version 2.136.0 and when you run bundle install or a similar command it uses that version?

**Comment by SwitchDoors** [comment]
> Are you using a gemfile or do you have rbenv ? Maybe your GemFile or GemFile.lock sets fastlane to the version 2.136.0 and when you run bundle install or a similar command it uses that version?

yes it seems like that. But if i change gemfile.lock it needs to be installed some gems for newer version of fastlane. How can i done it automatically?

**Comment by SwitchDoors** [comment]
If i run bundle_install after update_fastlane, it's also instal bundle with previous version of fastlane

**Comment by max-ott** [comment]
Don't manually change the `.lock` file. Simply delete it and run `bundle install`.

**Comment by SwitchDoors** [comment]
@max-ott or i used bundle update in teamcity configuration, it soved my problem. 
But can i use "delete .lock & bundle install" or "bundle update" in fastfile some way?
Don't wanna add it in every configuration in teamcity

**Comment by SwitchDoors** [comment]
I used bundle update in build configuration before run lane, it's worked for me
