### ISSUE TITLE
Frameit title shrinks really small

### ISSUE THREAD

**Issue by SRowley90** [fastlane/fastlane#16242]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When framing an screenshot the title text shrinks really small. This was working in the past until recently. I'm not sure if it's after updating to a newer version of Fastlane. I did roll back my branch to a known working commit and that now has the same issue, so i'm assuming it's something in my environment. See the image below:

![iPad Air 2-0JourneyList_framed](https://user-images.githubusercontent.com/1169516/78356357-4b356480-75a7-11ea-9b3a-a7b091ce388a.png)

##### Command executed
bundle exec fastlane frameit

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
Sams-MacBook-Pro:screenshots sam.rowley$ bundle exec fastlane frameit
[✔] 🚀 
[12:23:00]: Using device frames version 'latest'
[✔] Framing screenshot './en-GB/iPad Air 2-0JourneyList.png' 
[12:23:16]: Added frame: '/pathToScreenshots/screenshots/en-GB/iPad Air 2-0JourneyList_framed.png'
</pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15                                       |
| Ruby                        | 2.5.5                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.15 (19A582a)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.5/2.5.5_1/lib      |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.144.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status      |
| ------------------------- | ------- | ------------------ |
| fastlane-plugin-appcenter | 1.2.0   | 🚫 Update available |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday                   | 0.17.3       |
| faraday_middleware        | 0.13.1       |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 2.1.4        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.293.0      |
| aws-eventstream           | 1.0.3        |
| aws-sigv4                 | 1.1.1        |
| aws-sdk-core              | 3.92.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.61.1       |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| unicode-display_width     | 1.7.0        |
| plist                     | 3.5.0        |
| addressable               | 2.7.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| excon                     | 0.73.0       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| fastimage                 | 2.1.7        |
| json                      | 2.3.0        |
| dotenv                    | 2.7.5        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| multi_json                | 1.14.1       |
| signet                    | 0.13.2       |
| os                        | 1.1.0        |
| memoist                   | 0.16.2       |
| googleauth                | 0.11.0       |
| digest-crc                | 0.5.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-env          | 1.3.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| fastlane-plugin-appcenter | 1.2.0        |
</details>

*generated on:* **2020-04-03**
</details>

**Comment by tedgonzalez** [comment]
Try using fastlane 2.142.0 as a quick fix
There was a change in 2.143.0 that affected it https://github.com/fastlane/fastlane/pull/14628

**Comment by SRowley90** [comment]
That's perfect for a quick fix for now. Thank you.
