### ISSUE TITLE
Support for prelaunch_simulator to launch all simulators passed in devices

### ISSUE THREAD

**Issue by kerrmarin** [fastlane/fastlane#16246]
#### Motivation Behind Feature
When running a set of tests I can prelaunch a simulator but if we're testing on a large number of devices it would be helpful to prelaunch them all, otherwise prelaunching doesn't offer such a great time saving.

#### Feature Description
When calling `run_tests` with `prelaunch_simulator` set to `true`, all simulators passed in the `devices` should be launched.

#### Alternatives or Workarounds
I did a quick google but couldn't find anything. A workaround could be to have another step before `run_tests` that launches all the simulators you need.

**Comment by kerrmarin** [comment]
Thanks @fastlane-bot! This hasn't been fixed yet though. Please don't close the issue :)

**Comment by miquelalvarado** [comment]
This would be a great improvement, indeed 🙏

**Comment by buukfairyyp** [comment]
You’re doing a great job Man,Keep it up.

**Comment by kerrmarin** [comment]
Thanks @fastlane-bot! This hasn't been fixed yet though. Please don't close the issue :)
