### ISSUE TITLE
[match] Mismatch between imported profile name and searched for profile name.

### ISSUE THREAD

**Issue by DDamian** [fastlane/fastlane#16243]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When I run 'import' command for 'enterprise' type certificate and provide cert+key+profile, it names the uploaded profile to be Enterprise_[*|bundle_id]

It's in match/importer.rb, line 87, where cert_type is 'enterprise'.
https://github.com/fastlane/fastlane/blob/d306f7df8487e3ce53e6784ad0ad0667e66216db/match/lib/match/importer.rb#L87

Then, when I run fastlane match enterprise, it searches in repository for profile named InHouse_[*|bundle_id]. It doesn't find it, because such profile wasn't created.

It's in match/generator.rb, line 102, where type is 'enterprise'
https://github.com/fastlane/fastlane/blob/d306f7df8487e3ce53e6784ad0ad0667e66216db/match/lib/match/generator.rb#L96-L104

I believe in importer.rb, we should use this method from generator.rb `self.profile_type_name(type)` to generate profile name prefix.

##### Command executed

fastlane match import (with type enterprise)

fastlane match enterprise

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by ugenlik** [comment]
Same happening to me for appstore , fastlane match import is creating `Distribution_com.blablalba` profile in repo, but running gym throws an error saying `No matching provisioning profiles found for 'AppStore_com.blablabla`

**Comment by bdolewski** [comment]
I think it may be also connected to my issue https://github.com/fastlane/fastlane/issues/16257
After importing enterprise certificate to my repo I can see on the repo under:
```/profiles/enterprise/Enterprice_bundle_id.mobileprovision```

However while calling `fastlane match` it seems to search for ```InHouse_bundle_id.mobileprovision```

**Comment by bdolewski** [comment]
I have a workaround for this. I cloned my private repo used my `match`. Then I renamed my Enterprise profile such as:

```
cd profiles/enterprise
mv Enterprise_com.blablabla InHouse_com.blablabla
```

And `fastlane match` worked back again. So this is definitely a bug in importer.

**Comment by sraka1** [comment]
@joshdholtz I think this is a common occurrence with the new provisioning file importer and could be addressed as part of the changes for cert_id parameter for imports...

**Comment by dabo248** [comment]
> Same happening to me for appstore , fastlane match import is creating Distribution_com.blablalba profile in repo, but running gym throws an error saying No matching provisioning profiles found for 'AppStore_com.blablabla

Renaming them from Distribution_com.XYZ to AppStore_com.XYZ by hand has worked for me.

**Comment by jsramraj** [comment]
I have the same problem for the appstore and the enterprise type profiles. During import, the profiles are stored as `profiles/distribution/Distribution_com.mycompany.myapp` for **appstore** and as `profiles/enterprise/Enterprise__com.mycompany.myapp` for **enterprise**.

But when I run the fastlane match command, it looks for the file `profiles/distribution/Appstore_com.mycompany.myapp` for **appstore** and `profiles/enterprise/InHouse__com.mycompany.myapp` for **enterprise**
