### ISSUE TITLE
Cert type 'developer_id_application' is not supported

### ISSUE THREAD

**Issue by kbilyk-svitla** [fastlane/fastlane#16240]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
In addition to bug with `fastlane match developer_id` it is impossible even to upload generated certificates and provisioning profiles for `developer_id`.

##### Command executed
`bundle exec fastlane match import`

##### Complete output when running fastlane, including the stack trace and command used

<details>

```
[16:41:13]: Successfully loaded '[REDACTED]/fastlane/Matchfile' 📄

+-------------------+----------------------------------------------------------------------------------------------------------------+
|                                            Detected Values from './fastlane/Matchfile'                                             |
+-------------------+----------------------------------------------------------------------------------------------------------------+
| app_identifier    | [[REDACTED], [REDACTED]]                                                                                       |
| git_url           | [REDACTED]                                                                                                     |
| type              | developer_id                                                                                                   |
| platform          | macos                                                                                                          |
| username          | [REDACTED]                                                                                                     |
| keychain_password | [REDACTED]                                                                                                     |
+-------------------+----------------------------------------------------------------------------------------------------------------+

[16:41:13]: Certificate (.cer) path:
[REDACTED]
[16:41:26]: Private key (.p12) path:
[REDACTED]
[16:41:38]: Provisioning profile (.mobileprovision or .provisionprofile) path or leave empty to skip this file:
[REDACTED]
[16:41:55]: Cloning remote git repo...
[16:41:55]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[16:41:57]: 🔓  Successfully decrypted certificates repo
[16:41:57]: Repo is at: '/var/folders/92/xjxp368d1sj04vzq_4mj4d280000gp/T/d20200402-15341-2039r1'

[!] Cert type 'developer_id_application' is not supported
```

</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.5                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.21.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.5 (19F53f)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.4                                                           |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform(:ios)
platform :ios do
  ENV['GIT_TAG_GROUPING'] = "test-builds"
  ENV['MATCH_TYPE'] = "appstore"

  before_all do
    import("lanes/add_tag.rb")
    import("lanes/delete_last_tag.rb")
    import("lanes/notifications.rb")
    import("lanes/update_build_number.rb")
  end

  desc "Send notification to Slack about opened Pull Request with URL to it."
  lane :opened_pr_notification do
    slack(
      message: "New Pull Request is ready for Code Review!",
      success: true,
      channel: ENV['SLACK_CHANNEL'],
      slack_url: ENV['SLACK_URL'],
      payload: {
        "URL" => ENV['PULL_REQUEST_URL']
      },
      default_payloads: [:test_result, :git_author]
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Run pod install
    cocoapods(
      use_bundle_exec: true,
      deployment: true,
      try_repo_update_on_error: true
    )

    # Increment build
    update_build_number

    # Create Keychain for Code Signing
    create_keychain(
      name: ENV['MATCH_KEYCHAIN_NAME'],
      password: ENV['MATCH_KEYCHAIN_PASSWORD'],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true
    )

    # Code Signing using match
    sync_code_signing

    # XCode build app
    build_app(
      workspace: ENV['WORKSPACE'],
      scheme: ENV['SCHEME']
    )

    # Generate the changelog based on your last commits
    changelog_from_git_commits(
      merge_commit_filtering: "exclude_merges"
    )

    # Adding tag
    add_tag

    # Upload to TestFlight
    upload_to_testflight(
      changelog: Actions.lane_context[SharedValues::FL_CHANGELOG]
    )

    # Send a success notification to Slack
    closed_pr_notification
  end

  error do |lane, exception|
    error_notification
    # If build number shared value exists - there where build number change so tag might be created
    if Actions.lane_context[Actions::SharedValues::BUILD_NUMBER]
      delete_last_tag
      update_build_number(
        decrease: true
      )
    end
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier ENV['APP_IDENTIFIER'] # The bundle identifier of your app
apple_id ENV['APPLE_ID'] # Your Apple email address

itc_team_id ENV['ITC_TEAM_ID'] # App Store Connect Team ID
team_id ENV['TEAM_ID'] # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.144.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.72.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| os                        | 1.0.1        |
| googleauth                | 0.10.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.292.0      |
| aws-eventstream           | 1.0.3        |
| aws-sigv4                 | 1.1.1        |
| aws-sdk-core              | 3.92.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.61.1       |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.15.0       |
| unicode-display_width     | 1.6.1        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| faraday                   | 0.17.3       |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| memoist                   | 0.16.2       |
| digest-crc                | 0.4.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.25.1       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

**Comment by addisonwebb** [comment]
I believe this issue is fixed by #16211.

**Comment by addisonwebb** [comment]
This can be closed. The fix was implemented in #16211 and released in [2.146.0](https://github.com/fastlane/fastlane/releases/tag/2.146.0).

**Comment by kbilyk-svitla** [comment]
@addisonwebb I've tested your changes and successfully uploaded developer_id provisioning profiles with certificates but I can't sync them back to the machine that will run CI actions.

When I run the command `bundle exec fastlane match --verbose --readonly` I get:

```
ERROR [2020-04-22 17:07:23.68]: No matching provisioning profiles found for 'Direct_com.***'
ERROR [2020-04-22 17:07:23.68]: A new one cannot be created because you enabled `readonly`
ERROR [2020-04-22 17:07:23.68]: If you are certain that a profile should exist, double-check the recent changes to your match repository
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
```

It seems like match expects some 'Direct_com.***' provisioning profiles and after uploading my I get:

```
certificates/profiles/developer_id_application/Developer_id_application_com.***
```

Moreover if to run command without `--verbose` match will generate some 'Direct_com.***' provisioning profiles at path:

```
certificates/profiles/developer_id/Direct_com.***
```

Please, notice the difference in folders: uploaded are located in `developer_id_application` and generated in `developer_id`.

Unfortunately I can't use generated one as they generates incorrectly for Catalyst app. 

So my hope is on you)

P.S.: @joshdholtz you might be interested also.

**Comment by addisonwebb** [comment]
@kbilyk-svitla I would say this appears to be a different issue and would probably be best to file a new issue for this problem.

**Comment by kbilyk-svitla** [comment]
@addisonwebb formally you are right: it is now possible to import developer_id certificates/provisioning profiles but it is still impossible to use them)

**Comment by addisonwebb** [comment]
If you don't need the provisioning profile you can try setting the `skip_provisioning_profiles` parameter to `true`. https://docs.fastlane.tools/actions/match/#parameters

**Comment by kbilyk-svitla** [comment]
@addisonwebb yes, but I need them. I need to build the app for future notarisation and it is not possible without provisioning profiles as far as I know.

**Comment by addisonwebb** [comment]
@kbilyk-svitla I'm not sure if this helps, but I have been able to successfully use the update in #16211 to deploy an AppKit-based, notarized macOS application.

I'm not familiar with the signing requirements for other setups like Catalyst apps.

**Comment by kbilyk-svitla** [comment]
@addisonwebb please double check the generated and imported provisioning profiles name:

generated: `Direct`
imported: `Developer_id_application`

So it might be that you've succeeded because of 2 reasons:

1. You've not removed provisioning profiles from Xcode and they just worked for you (that was my mistake whet I've tested on local machine)
2. Match used generated `Direct` named profiles and it worked without imported ones.

**Comment by addisonwebb** [comment]
@kbilyk-svitla So it looks like it is possible to sign a Developer ID app with no provisioning profile (my situation) and with a provisioning profile if you need certain features like CloudKit. https://developer.apple.com/support/developer-id/

#16211 addressed the main problem of importing Developer ID certificates and they can be used successfully when no provisioning profile is needed. Let's create a new ticket to capture this new issue where match does not work in the situation when a user needs to sign their app with a Developer ID certificate and use a provisioning profile.

**Comment by rogerluan** [comment]
>Let's create a new ticket to capture this new issue where match does not work in the situation when a user needs to sign their app with a Developer ID certificate and use a provisioning profile.

☝️ 💯 👏  Yes, please! 

I'll close this ticket now, since https://github.com/fastlane/fastlane/pull/16211 got merged and released a long time ago 😊 thanks guys!
