### ISSUE TITLE
Spaceship : Why not using appstoreconnect apis for GET and POST?

### ISSUE THREAD

**Issue by inforeqd512** [fastlane/fastlane#16252]
### Question Checklist

- [Yes ] Updated fastlane to the latest version
- [Yes ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [Yes] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [Yes ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Spaceship GET https://api.appstoreconnect.apple.com/v1/devices exists
but why not POST https://api.appstoreconnect.apple.com/v1/devices

#### Question Description

For eg to get a list of devices and add a device, since appstoreconnect apis provide
GET https://api.appstoreconnect.apple.com/v1/devices and 
POST https://api.appstoreconnect.apple.com/v1/devices

am trying to understand why spaceship uses 
appstoreconnect apis for : GET https://api.appstoreconnect.apple.com/v1/devices
but dev portal apis for: POST https://api.appstoreconnect.apple.com/v1/devices

why not use the one so that just providing the JWT will be enough to get all the data and perform all the updates required?

Also will not need so many URLs to be whitelisted in enterprise proxy/firewall?

**Comment by inforeqd512** [comment]
Maybe we can help by contributing to move it faster on the appstoreconnect api. if that is what is the reason for not moving to the POST as described above

**Comment by max-ott** [comment]
@inforeqd512 feel free to open a pull request and add the desired functionality.
