### ISSUE TITLE
fastlane login got Unauthorized Access (Spaceship::UnauthorizedAccessError)

### ISSUE THREAD

**Issue by simpleway2016** [fastlane/fastlane#16250]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
If you're running this in a non-interactive session (e.g. server or CI)
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification

(Input `sms` to escape this prompt and select a trusted phone number to send the code as a text message)

(You can also set the environment variable `SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER` to automate this)
(Read more at: https://github.com/fastlane/fastlane/blob/master/spaceship/docs/Authentication.md#auto-select-sms-via-spaceship-2fa-sms-default-phone-number)

Please enter the 6 digit code:
412849
Requesting session...
/usr/local/rvm/gems/ruby-2.4.6/gems/fastlane-2.144.0/spaceship/lib/spaceship/client.rb:857:in `block in send_request': Unauthorized Access (Spaceship::UnauthorizedAccessError)
	from /usr/local/rvm/gems/ruby-2.4.6/gems/fastlane-2.144.0/spaceship/lib/spaceship/client.rb:625:in `with_retry'
	from /usr/local/rvm/gems/ruby-2.4.6/gems/fastlane-2.144.0/spaceship/lib/spaceship/client.rb:849:in `send_request'
	from /usr/local/rvm/gems/ruby-2.4.6/gems/fastlane-2.144.0/spaceship/lib/spaceship/client.rb:693:in `request'
	from /usr/local/rvm/gems/ruby-2.4.6/gems/fastlane-2.144.0/spaceship/lib/spaceship/client.rb:518:in `fetch_olympus_session'
	from /usr/local/rvm/gems/ruby-2.4.6/gems/fastlane-2.144.0/spaceship/lib/spaceship/client.rb:496:in `send_shared_login_request'
	from /usr/local/rvm/gems/ruby-2.4.6/gems/fastlane-2.144.0/spaceship/lib/spaceship/portal/portal_client.rb:28:in `send_login_request'
	from /usr/local/rvm/gems/ruby-2.4.6/gems/fastlane-2.144.0/spaceship/lib/spaceship/client.rb:775:in `do_login'
	from /usr/local/rvm/gems/ruby-2.4.6/gems/fastlane-2.144.0/spaceship/lib/spaceship/client.rb:384:in `login'
	from /usr/local/rvm/gems/ruby-2.4.6/gems/fastlane-2.144.0/spaceship/lib/spaceship/client.rb:346:in `login'
	from /usr/local/rvm/gems/ruby-2.4.6/gems/fastlane-2.144.0/spaceship/lib/spaceship/portal/spaceship.rb:25:in `login'
	from /usr/local/rvm/gems/ruby-2.4.6/gems/fastlane-2.144.0/spaceship/lib/spaceship/portal/spaceship.rb:103:in `login'
	from test3.rb:4:in `<main>'

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.17.3       |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.1        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.13.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.73.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.0.4        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.1       |
| os                        | 1.0.1        |
| googleauth                | 0.9.0        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.4.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.294.0      |
| aws-eventstream           | 1.0.3        |
| aws-sigv4                 | 1.1.1        |
| aws-sdk-core              | 3.92.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.61.2       |
| faraday                   | 0.17.3       |
| openssl                   | 2.0.9        |
| io-console                | 0.4.6        |
| psych                     | 2.2.2        |
</details>

*generated on:* **2020-04-04**
</details>

**Comment by max-ott** [comment]
Please check out the solutions mentioned here: https://github.com/fastlane/fastlane/issues/16108
