### ISSUE TITLE
[supply] Mismatch between expected changelog file names in supply setup vs supply uploader

### ISSUE THREAD

**Issue by joshsnelling** [fastlane/fastlane#16253]
🔑

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
During setup, supply creates changelog files named after the version name for a current listing in Google Play (e.g. `2.4.8`). After making changes to the changelogs and running supply to upload changes to Google Play, the supply uploader fails to upload them because it can't find changelog files named after the version code (e.g. `20000338`).

Based on the Google Play Developer API spec, I believe the supply uploader is correctly looking for changlogs based on the version codes, which leads me to believe a change should be made to the supply setup `store_release_listing` method. I've put in place a local fix that I'm happy to submit as a PR, but I'd like feedback on the overall issue and the proposed fix before I do. Here's my proposal:

![supply_setup_changelog_name_fix_proposal](https://user-images.githubusercontent.com/3750657/78452543-d3744200-7659-11ea-8630-55878c881ff9.png)

This will iterate over all version codes associated with a release and will save out changelog files named after each one. All changelog files will contain the same content for a given release. This will allow the supply uploader to find the correct changelog file and upload it to Google Play.

If it's agreed that this fix is valid, I'll submit as a PR. Otherwise, please let me know if the existing behavior is what's intended and if there's something I've overlooked about changelog naming in general that I should be doing differently when using supply. Thanks!

##### Command executed
`fastlane supply init`
`fastlane supply`

###### BEFORE FIX

`fastlane supply init`
<details>
  <pre>...
[09:38:17]: Found '2.4.8' in 'production' track.
[09:38:17]: 🔨  Downloading changelogs (en-US, 2.4.8)
[09:38:17]: Writing to metadata/en-US/changelogs/2.4.8.txt...
...</pre>
</details>

`fastlane supply`

<details>
  <pre>...
[09:39:46]: Preparing to upload for language 'en-US'...
[09:39:46]: Could not find changelog for '20000338' and language 'en-US' at path ./metadata/en-US/changelogs/20000338.txt...
...</pre>
</details>

###### AFTER FIX

`fastlane supply`
<details>
   <pre>...
[10:16:41]: Found '2.4.8' in 'production' track.
[10:16:41]: 🔨  Downloading changelogs (en-US, 2.4.8)
[10:16:41]: Writing to metadata/en-US/changelogs/20000338.txt...
...</pre>
</details>

`fastlane supply`
<details>
   <pre>...
[10:17:21]: Preparing to upload for language 'en-US'...
[10:17:22]: Updating changelog for '20000338' and language 'en-US'...
...</pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 10.15.4                                                 |
| Ruby                        | 2.5.8                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.24.1 (Apple Git-126)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.144.0/libexec/bin/fastlane |
| Host                        | Mac OS X 10.15.4 (19E266)                               |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.5/2.5.8/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1f  31 Mar 2020                             |
| Is contained                | false                                                   |
| Is homebrew                 | false                                                   |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 11.4                                                    |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.144.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.73.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.13.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.11.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.5.1        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.286.0      |
| aws-eventstream           | 1.0.3        |
| aws-sigv4                 | 1.1.1        |
| aws-sdk-core              | 3.92.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.61.1       |
</details>

*generated on:* **2020-04-04**
</details> </pre>
</details>

**Comment by max-ott** [comment]
Hi @joshsnelling Please directly submit a PR mentioning this issue. Working with screenshots it not really great to repro and test locally.

**Comment by joshsnelling** [comment]
@max-ott PR submitted
