### ISSUE TITLE
sh: 1: ./fastlane/FastlaneRunner: Exec format error on Linux

### ISSUE THREAD

**Issue by Wei18** [fastlane/fastlane#16261]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I use fastlane executable (swift version) and running on Linux, but I hit `sh: 1: ./fastlane/FastlaneRunner: Exec format error`, and it works on MacOS.

##### Complete output when running fastlane, including the stack trace and command used

<details>

```
$ bundle exec fastlane --verbose nothing
[✔] 🚀 
DEBUG [2020-04-06 05:04:58.71]: Checking if there are any plugins that should be loaded...
DEBUG [2020-04-06 05:04:58.71]: Loading 'fastlane-plugin-google_chat' plugin
INFO [2020-04-06 05:04:58.71]: gem 'fastlane-plugin-google_chat' is already installed
DEBUG [2020-04-06 05:04:58.72]: Loading 'fastlane-plugin-firebase_app_distribution' plugin
INFO [2020-04-06 05:04:58.72]: gem 'fastlane-plugin-firebase_app_distribution' is already installed
+-------------------------------------------+---------+---------------------------+
|                                  Used plugins                                   |
+-------------------------------------------+---------+---------------------------+
| Plugin                                    | Version | Action                    |
+-------------------------------------------+---------+---------------------------+
| fastlane-plugin-google_chat               | 0.1.1   | google_chat               |
| fastlane-plugin-firebase_app_distribution | 0.1.4   | firebase_app_distribution |
+-------------------------------------------+---------+---------------------------+

INFO [2020-04-06 05:04:58.75]: loading manifest: /home/builder/workspace/serviceapp-ios/vendor/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/swift/upgrade_manifest.json
DEBUG [2020-04-06 05:04:58.87]: No missing groups found, so we don't need to worry about adding new groups
DEBUG [2020-04-06 05:04:58.88]: Fastlane.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.72/0.9.72
DEBUG [2020-04-06 05:04:58.88]: DeliverfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.19/0.9.19
DEBUG [2020-04-06 05:04:58.88]: GymfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.18/0.9.18
DEBUG [2020-04-06 05:04:58.88]: MatchfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.14/0.9.14
DEBUG [2020-04-06 05:04:58.88]: PrecheckfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.11/0.9.11
DEBUG [2020-04-06 05:04:58.88]: ScanfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.27/0.9.27
DEBUG [2020-04-06 05:04:58.88]: ScreengrabfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.13/0.9.13
DEBUG [2020-04-06 05:04:58.88]: SnapshotfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.7/0.9.7
DEBUG [2020-04-06 05:04:58.89]: LaneFileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2020-04-06 05:04:58.89]: ControlCommand.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2020-04-06 05:04:58.89]: RubyCommand.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2020-04-06 05:04:58.89]: RubyCommandable.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2020-04-06 05:04:58.89]: Runner.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2020-04-06 05:04:58.89]: SocketClient.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2020-04-06 05:04:58.89]: SocketClientDelegateProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2020-04-06 05:04:58.89]: SocketResponse.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2020-04-06 05:04:58.89]: ArgumentProcessor.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2020-04-06 05:04:58.89]: main.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2020-04-06 05:04:58.89]: RunnerArgument.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2020-04-06 05:04:58.89]: Checking for new user-provided tool configuration files
INFO [2020-04-06 05:04:58.91]: FastlaneSwiftRunner project is up-to-date
DEBUG [2020-04-06 05:04:58.91]: Waiting for 5 seconds for a connection from FastlaneRunner
INFO [2020-04-06 05:04:59.16]: $ ./fastlane/FastlaneRunner lane nothing logMode verbose swiftServerPort 2000 > /dev/null
INFO [2020-04-06 05:04:59.17]: ▸ sh: 1: ./fastlane/FastlaneRunner: Exec format error
#<Thread:0x000055a6acdfc070@/home/builder/workspace/serviceapp-ios/vendor/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/swift_lane_manager.rb:104 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	4: from /home/builder/workspace/serviceapp-ios/vendor/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/swift_lane_manager.rb:105:in `block in cruise_swift_lane_in_thread'
	3: from /home/builder/workspace/serviceapp-ios/vendor/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
	2: from /home/builder/workspace/serviceapp-ios/vendor/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	1: from /home/builder/workspace/serviceapp-ios/vendor/ruby/2.6.0/gems/fastlane-2.144.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/home/builder/workspace/serviceapp-ios/vendor/ruby/2.6.0/gems/fastlane-2.144.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': Exit status of command './fastlane/FastlaneRunner lane nothing logMode verbose swiftServerPort 2000 > /dev/null' was 2 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
sh: 1: ./fastlane/FastlaneRunner: Exec format error
#<Thread:0x00007f86e00fc440@/home/builder/workspace/serviceapp-ios/vendor/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/swift_lane_manager.rb:228 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	5: from /home/builder/workspace/serviceapp-ios/vendor/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/swift_lane_manager.rb:231:in `block in start_socket_thread'
	4: from /home/builder/workspace/serviceapp-ios/vendor/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/server/socket_server.rb:38:in `start'
	3: from /home/builder/workspace/serviceapp-ios/vendor/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/server/socket_server.rb:147:in `listen'
	2: from /usr/local/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
	1: from /home/builder/workspace/serviceapp-ios/vendor/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/server/socket_server.rb:148:in `block in listen'
/home/builder/workspace/serviceapp-ios/vendor/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/server/socket_server.rb:148:in `accept': execution expired (Timeout::Error)
	5: from /home/builder/workspace/serviceapp-ios/vendor/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/swift_lane_manager.rb:231:in `block in start_socket_thread'
	4: from /home/builder/workspace/serviceapp-ios/vendor/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/server/socket_server.rb:38:in `start'
	3: from /home/builder/workspace/serviceapp-ios/vendor/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/server/socket_server.rb:146:in `listen'
	2: from /home/builder/workspace/serviceapp-ios/vendor/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/server/socket_server.rb:151:in `rescue in listen'
	1: from /home/builder/workspace/serviceapp-ios/vendor/ruby/2.6.0/gems/fastlane-2.144.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/home/builder/workspace/serviceapp-ios/vendor/ruby/2.6.0/gems/fastlane-2.144.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': fastlane failed to receive a connection from the FastlaneRunner binary after 5 seconds, shutting down (FastlaneCore::Interface::FastlaneError)
WARN [2020-04-06 05:05:03.91]: Lane Context:
INFO [2020-04-06 05:05:03.92]: {:LANE_NAME=>"nothing"}
ERROR [2020-04-06 05:05:03.92]: fastlane failed to receive a connection from the FastlaneRunner binary after 5 seconds, shutting down
DEBUG [2020-04-06 05:05:03.92]: All plugins are up to date
ERROR [2020-04-06 05:05:03.92]: fastlane finished with errors
DEBUG [2020-04-06 05:05:03.92]: All plugins are up to date

#######################################################################
# fastlane 2.145.0 is available. You are on 2.144.0.
# You should use the latest version.
# Please update using `bundle update fastlane`.
#######################################################################
bundler: failed to load command: fastlane (/home/builder/workspace/serviceapp-ios/vendor/ruby/2.6.0/bin/fastlane)
FastlaneCore::Interface::FastlaneError: [!] fastlane failed to receive a connection from the FastlaneRunner binary after 5 seconds, shutting down
  /home/builder/workspace/serviceapp-ios/vendor/ruby/2.6.0/gems/fastlane-2.144.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'
  /home/builder/workspace/serviceapp-ios/vendor/ruby/2.6.0/gems/fastlane-2.144.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /home/builder/workspace/serviceapp-ios/vendor/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/server/socket_server.rb:151:in `rescue in listen'
  /home/builder/workspace/serviceapp-ios/vendor/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/server/socket_server.rb:146:in `listen'
  /home/builder/workspace/serviceapp-ios/vendor/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/server/socket_server.rb:38:in `start'
  /home/builder/workspace/serviceapp-ios/vendor/ruby/2.6.0/gems/fastlane-2.144.0/fastlane/lib/fastlane/swift_lane_manager.rb:231:in `block in start_socket_thread'
```
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                     |
| --------------------------- | --------------------------------------------------------- |
| OS                          | debian_based 9.9                                          |
| Ruby                        | 2.6.3                                                     |
| Bundler?                    | true                                                      |
| Git                         | git version 2.11.0                                        |
| Installation Source         | ~/workspace/serviceapp-ios/vendor/ruby/2.6.0/bin/fastlane |
| Host                        | Debian GNU/Linux 9 debian_based 9.9 (4.19.76-linuxkit)    |
| Ruby Lib Dir                | /usr/local/lib                                            |
| OpenSSL Version             | OpenSSL 1.1.0k  28 May 2019                               |
| Is contained                | false                                                     |
| Is homebrew                 | false                                                     |
| Is installed via Fabric.app | false                                                     |

### System Locale

| Variable | Value   |   |
| -------- | ------- | - |
| LANG     | C.UTF-8 | ✅ |
| LC_ALL   | C.UTF-8 | ✅ |
| LANGUAGE |         |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

```swift
// This file contains the fastlane.tools configuration
// You can find the documentation at https://docs.fastlane.tools
//
// For a list of all available actions, check out
//
//     https://docs.fastlane.tools/actions
//

import Foundation

class Fastfile: LaneFile {    
    
    func beforeAll() {
        
        if Util.shared.config.gitlabCIJobURL.isEmpty { cocoapods() }
        
    }
    
    func nothingLane() {
        
        desc()
        
        echo(message: "[po] \(function) -> ")
        
    }

}

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.144.0 | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-google_chat               | 0.1.1   | ✅ Up-To-Date  |
| fastlane-plugin-firebase_app_distribution | 0.1.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.3.0        |
| bundler                                   | 2.0.2        |
| CFPropertyList                            | 3.0.2        |
| concurrent-ruby                           | 1.1.5        |
| i18n                                      | 0.9.5        |
| minitest                                  | 5.13.0       |
| thread_safe                               | 0.3.6        |
| tzinfo                                    | 1.2.5        |
| activesupport                             | 4.2.11.1     |
| public_suffix                             | 2.0.5        |
| addressable                               | 2.7.0        |
| httpclient                                | 2.8.3        |
| json                                      | 2.3.0        |
| algoliasearch                             | 1.27.1       |
| atomos                                    | 0.1.3        |
| aws-eventstream                           | 1.0.3        |
| aws-partitions                            | 1.287.0      |
| aws-sigv4                                 | 1.1.1        |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.92.0       |
| aws-sdk-kms                               | 1.30.0       |
| aws-sdk-s3                                | 1.61.1       |
| babosa                                    | 1.0.3        |
| claide                                    | 1.0.3        |
| fuzzy_match                               | 2.0.4        |
| nap                                       | 1.1.0        |
| cocoapods-core                            | 1.8.1        |
| cocoapods-deintegrate                     | 1.0.4        |
| cocoapods-downloader                      | 1.2.2        |
| cocoapods-plugins                         | 1.0.0        |
| cocoapods-search                          | 1.0.0        |
| cocoapods-stats                           | 1.1.0        |
| netrc                                     | 0.11.0       |
| cocoapods-trunk                           | 1.4.1        |
| cocoapods-try                             | 1.1.0        |
| colored2                                  | 3.1.2        |
| escape                                    | 0.0.4        |
| fourflusher                               | 2.3.1        |
| gh_inspector                              | 1.1.3        |
| molinillo                                 | 0.6.6        |
| ruby-macho                                | 1.4.0        |
| nanaimo                                   | 0.2.6        |
| xcodeproj                                 | 1.15.0       |
| cocoapods                                 | 1.8.1        |
| colored                                   | 1.2          |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| declarative                               | 0.0.10       |
| declarative-option                        | 0.1.0        |
| digest-crc                                | 0.5.1        |
| unf_ext                                   | 0.0.7.6      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| dotenv                                    | 2.7.5        |
| emoji_regex                               | 1.0.1        |
| excon                                     | 0.73.0       |
| multipart-post                            | 2.0.0        |
| faraday                                   | 0.17.3       |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.6        |
| faraday_middleware                        | 0.13.1       |
| fastimage                                 | 2.1.7        |
| jwt                                       | 2.1.0        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.14.1       |
| os                                        | 1.0.1        |
| signet                                    | 0.13.0       |
| googleauth                                | 0.11.0       |
| mini_mime                                 | 1.0.2        |
| uber                                      | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| google-api-client                         | 0.36.4       |
| google-cloud-env                          | 1.3.1        |
| google-cloud-errors                       | 1.0.0        |
| google-cloud-core                         | 1.5.0        |
| google-cloud-storage                      | 1.25.1       |
| mini_magick                               | 4.10.1       |
| multi_xml                                 | 0.6.0        |
| plist                                     | 3.5.0        |
| rubyzip                                   | 1.3.0        |
| security                                  | 0.1.3        |
| naturally                                 | 2.2.0        |
| simctl                                    | 1.6.8        |
| slack-notifier                            | 2.3.2        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.7.0        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.7.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| word_wrap                                 | 1.0.0        |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.0        |
| fastlane-plugin-firebase_app_distribution | 0.1.4        |
| fastlane-plugin-google_chat               | 0.1.1        |
</details>

*generated on:* **2020-04-06**
</details>

**Comment by janpio** [comment]
I don't think you are supposed to use Swift on Linux.

**Comment by Wei18** [comment]
I think Swift can work on Ubuntu Linux, but not sure how to do, how to work or not.
