### ISSUE TITLE
latest_testflight_build_number and versions with leading zeros

### ISSUE THREAD

**Issue by zmeyc** [fastlane/fastlane#16260]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

If version number contains leading zeros, for example "20.03.2", they will be stripped when uploading to TestFlight and the version will turn into "20.3.2" which is expected.

But latest_testflight_build_number will not find the build when referenced as "20.03.2".

It should probably normalize the version before checking (compare parts as integers).

```
    version_number = "20.03.2"

    increment_build_number(
      build_number: latest_testflight_build_number(
        initial_build_number: 1,
        version: version_number
      ) + 1,
    )
```

```
INFO [2020-04-05 21:33:43.21]: Login successful
INFO [2020-04-05 21:33:44.03]: Fetching the latest build number for version 20.03.2
WARN [2020-04-05 21:33:44.84]: Could not find a build for version 20.03.2 on ios platform on App Store Connect
INFO [2020-04-05 21:33:44.84]: Using initial build number of 1
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by max-ott** [comment]
Thanks for the find! More than happy to review your pull request fixing this issue. I don't think trailing zeros are commonly used in versioning.
