### ISSUE TITLE
Failed to use iOS custom Simulator. Extra space in name.

### ISSUE THREAD

**Issue by dmytro-me** [fastlane/fastlane#16264]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I have created additional simulator for Xcode 11.4 to capture screenshots using dark mode. I named it "iPad Air (3rd generation) Dark".  I'm using exactly one space symbol between "iPad Air (3rd generation)" and "Dark".

My Snapfile has the following section: 

<pre>
# A list of devices you want to take the screenshots from
 devices([
   "iPad Air (3rd generation) Dark",
   "iPad (7th generation)"
 ])
</pre>

The dark simulator has a name with single space after closing parentheses.
<pre>
$xcrun simctl list | grep Dark
    iPad Air (3rd generation) Dark (2B0E9B5D-3680-42B1-BC44-26B380921500) (Shutdown) 
</pre>

However fastlane fails to accept new simulator because it is unable to find its name in device list. Please note that in the list of available simulators this simulator has a two spaces after  last closing parentheses.

In the fastlane error message custom simulator has the following name:
<pre>iPad Air (3rd generation)  Dark</pre>

##### Command executed

`fastlane run snapshot`

##### Complete output when running fastlane, including the stack trace and command used

<details>

  <pre>fastlane run snapshot                 
[✔] 🚀 
[15:08:09]: fastlane detected a Gemfile in the current directory
[15:08:09]: However, it seems like you didn't use `bundle exec`
[15:08:09]: To launch fastlane faster, please use
[15:08:09]: 
[15:08:09]: $ bundle exec fastlane run snapshot
[15:08:09]: 
[15:08:09]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[15:08:10]: ----------------------
[15:08:10]: --- Step: snapshot ---
[15:08:10]: ----------------------
[15:08:10]: Successfully loaded '/Users/dmp/Work/x/x/fastlane/Snapfile' 📄

+----------------------------+-------------------------------------------------------------+
|                        Detected Values from './fastlane/Snapfile'                        |
+----------------------------+-------------------------------------------------------------+
| devices                    | ["iPad Air (3rd generation) Dark", "iPad (7th generation)"] |
| languages                  | ["en-US"]                                                   |
| scheme                     |  xx                                    |
| output_directory           | ./screenshots                                               |
| clear_previous_screenshots | true                                                        |
+----------------------------+-------------------------------------------------------------+

[15:08:10]: Error setting value '["iPad Air (3rd generation) Dark", "iPad (7th generation)"]' for option 'devices'

[!] Device 'iPad Air (3rd generation) Dark' not in list of available simulators 'iPhone 5s, iPhone 6 Plus, iPhone 6, iPhone 6s, iPhone 6s Plus, iPhone SE, iPhone 7, iPhone 7 Plus, iPhone 8, iPhone 8 Plus, iPhone X, iPad Air, iPad Air 2, iPad Pro (9.7-inch), iPad Pro (12.9-inch), iPad (5th generation), iPad Pro (12.9-inch) (2nd generation), iPad Pro (10.5-inch), iPhone 8, iPhone 8 Plus, iPhone 11, iPhone 11 Pro, iPhone 11 Pro Max, iPad Pro (9.7-inch), iPad (7th generation), iPad Pro (11-inch) (2nd generation), iPad Pro (12.9-inch) (4th generation), iPad Air (3rd generation), iPad Air (3rd generation)  Dark, Apple TV, Apple TV 4K, Apple TV 4K (at 1080p), Apple Watch Series 4 - 40mm, Apple Watch Series 4 - 44mm, Apple Watch Series 5 - 40mm, Apple Watch Series 5 - 44mm'</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.5                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.1 (Apple Git-126)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.5 (19F53f)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.4                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("") # The bundle identifier of your app
apple_id("dmp@") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.145.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.13.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.11.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.5.1        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.287.0      |
| aws-eventstream           | 1.0.3        |
| aws-sigv4                 | 1.1.1        |
| aws-sdk-core              | 3.92.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.61.1       |
| CFPropertyList            | 3.0.2        |
| excon                     | 0.73.0       |
| json                      | 2.3.0        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-04-06**
</details></pre>
</details>

**Comment by janpio** [comment]
Is that standard naming for these simulators?

**Comment by dmytro-me** [comment]
This isn't a built-in simulator to Xcode, but when you create simulator tailored for you (for example a Simulator with Dark mode enabled) you may assign any name to it, there is no naming convention. 

The problem is in simulators() function, device_manager.rb. I will try to fix it and submit PR.
