### ISSUE TITLE
not able to upload new version to Testflight  Error:The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.

### ISSUE THREAD

**Issue by macharlachiranjeevi** [fastlane/fastlane#16270]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by janpio** [comment]
Please fill the issue template instead of just providing an issue title. We need the full output etc.
