### ISSUE TITLE
Add inAppUpdatePriority option to the upload_to_play_store (supply) action

### ISSUE THREAD

**Issue by romychab** [fastlane/fastlane#16279]
#### Motivation Behind Feature

Google Play Developer API allows specifying the update priority of the android application when creating a new release (see inAppUpdatePriority field in Edits.tracks.releases). 'inAppUpdatePriority' can take int values from 0 (lowest priority) to 5 (highest priority). This priority can be used in the android app for handling/delivering non-critical or critical updates to the users (https://developer.android.com/guide/playcore/in-app-updates). If the priority is set correctly android application can check for available updates + their priorities using client library and then a standard user-friendly system dialog can be shown to the user with the suggestion to update the application. 

#### Feature Description
As a result of specifying inAppUpdatePriority and implementing checking this priority in the android app end-users can see the following standard screen (image is taken from the official android documentation):

![screen](https://developer.android.com/images/app-bundle/immediate_flow.png)

Actually I'm not ruby developer so the code example is in Java:
```java
AndroidPublisher publisher = new AndroidPublisher(httpTransport, factory, credentials);

// ... uploading APK here and getting version code
// ------

TrackRelease release = new TrackRelease()
    .setVersionCodes(versionCodes)
    .setInAppUpdatePriority(/* value from 0 to 5 here */); 

Track track = new Track().setReleases(singletonList(release));

publisher.edits().tracks()
    .update(APP_PACKAGE, editId, TRACK_PRODUCTION, track)
    .execute();
```
This feature would not break anything for existing users.

#### Alternatives or Workarounds
It seems there is no way to do this with existing Fastlane actions & plugins (at least I couldn't find how to do this in the Fastlane documentation and also there is no such option in [sources](https://github.com/fastlane/fastlane/blob/master/supply/lib/supply/options.rb)).

**Comment by mwajeeh** [comment]
Seems like in-app-update feature is completely missing in supply. Any ETA on this?

**Comment by mrea1** [comment]
I would really love this feature! Did a little digging...

The ruby AndroidPublisher library has a `in_app_update_priority` field on the TrackRelease class 
https://github.com/googleapis/google-api-ruby-client/blob/bc980737e8d1cfc1807ddfc5c3b27a2927c7c7c4/generated/google/apis/androidpublisher_v3/classes.rb#L2095

**Comment by janpio** [comment]
> Seems like in-app-update feature is completely missing in supply. Any ETA on this?

As soon as someone implemented it, created a Pull Request for it that got reviewed and merged <3

**Comment by jomisj** [comment]
@janpio I have created a pull request for this feature (https://github.com/fastlane/fastlane/pull/16452). Can you please review and let me know if something could be improved?

**Comment by rogerluan** [comment]
Closing this ticket as https://github.com/fastlane/fastlane/pull/16452 was already merged and released 🚀
