### ISSUE TITLE
Cannot set empty changelog for upload_to_testflight

### ISSUE THREAD

**Issue by larryonoff** [fastlane/fastlane#16278]
### Question Checklist

- [ X ] Updated fastlane to the latest version
- [ X ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ X ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ X ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question
Our lane runs `changelog_from_git_commits` and then `upload_to_testflight`. We don't set any change logs for `upload_to_testflight`, but it's set by `changelog_from_git_commits`, i.e. using `Actions.lane_context[SharedValues::FL_CHANGELOG]`. As result `skip_waiting_for_build_processing` is enabled, what is not what we expect.

Is there any options to disable this auto-behaviour for `upload_to_testflight`?

linked issue #15983

**Comment by larryonoff** [comment]
The issue is still actual. Nobody reacted on it.

**Comment by danez** [comment]
We are having the exact same issue as described in the ticket.

I tried setting changelog to nil, but that did not help.

```
pilot(skip_waiting_for_build_processing: true, changelog: nil)
```
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.4                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.26.2                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.4 (19E287)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.4.1                                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
...

platform :ios do
  desc "Download private keys and certificates for code signing"
  lane :get_code_signing do
    match(type: "development", readonly: true)
    match(type: "appstore", readonly: true)
  end

  desc "Submit a new Snapshot Build to Apple Testflight"
  lane :build_snapshot do |options|
    scheme = 'Snapshot' + get_scheme_from_options(options, 'build_snapshot')
    inject_scheme_config_env_vars!(scheme)

    reset_git_repo(disregard_gitignore: false, force: true) unless !is_ci?
    ensure_git_status_clean
    ensure_git_branch

    version = Time.now.strftime("%Y%m%d.%H%M%S")
    set_javascript_package_version(version)
    set_ios_app_version(version)

    changelog = changelog_from_git_commits(
      between: ["HEAD~3", "HEAD"],
      merge_commit_filtering: "exclude_merges",
      pretty: "- %s"
    )

    send_pre_release_notification(scheme)
    unlock_keychain_on_ci

    match(type: "appstore")
    if scheme == 'SnapshotOffice'
      add_badge(alpha: true, dark: true)
    else
      add_badge(alpha: true)
    end
    app_identifier = SCHEME_TO_APP_ID_MAP[scheme]
    persist_graphql(scheme, app_identifier, version)
    strip_simulator_archs
    gym(scheme: scheme, clean: false)
    restore_simulator_archs
    update_bugsnag(scheme, version)
    pilot(skip_waiting_for_build_processing: true, changelog: nil)

    send_post_release_notification(scheme, changelog)
  end
...
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# iOS
apple_id "user"
team_id "1234567"

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.148.1 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status      |
| ----------------------- | ------- | ------------------ |
| fastlane-plugin-bugsnag | 1.4.2   | ✅ Up-To-Date       |
| fastlane-plugin-badge   | 1.1.0   | 🚫 Update available |


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 1.17.2       |
| etc                       | 1.0.1        |
| forwardable               | 1.2.0        |
| CFPropertyList            | 3.0.2        |
| concurrent-ruby           | 1.1.6        |
| i18n                      | 0.9.5        |
| minitest                  | 5.14.0       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.7        |
| activesupport             | 4.2.11.1     |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| httpclient                | 2.8.3        |
| json                      | 2.3.0        |
| algoliasearch             | 1.27.2       |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.318.0      |
| aws-sigv4                 | 1.1.3        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.96.1       |
| aws-sdk-kms               | 1.31.0       |
| aws-sdk-s3                | 1.65.0       |
| babosa                    | 1.0.3        |
| curb                      | 0.9.10       |
| fastimage                 | 2.1.7        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.73.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.1.0        |
| signet                    | 0.14.0       |
| googleauth                | 0.12.0       |
| mini_mime                 | 1.0.2        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| digest-crc                | 0.5.1        |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.1       |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.16.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| badge                     | 0.9.1        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| netrc                     | 0.11.0       |
| ffi                       | 1.12.2       |
| ethon                     | 0.12.0       |
| typhoeus                  | 1.4.0        |
| cocoapods-core            | 1.9.1        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.3.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| cocoapods-trunk           | 1.5.0        |
| cocoapods-try             | 1.2.0        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| cocoapods                 | 1.9.1        |
| fastlane-plugin-badge     | 1.1.0        |
| rchardet                  | 1.8.0        |
| git                       | 1.7.0        |
| xml-simple                | 1.1.5        |
| fastlane-plugin-bugsnag   | 1.4.2        |
| vault                     | 0.13.0       |
</details>


*generated on:* **2020-05-20**
</details>

**Comment by larryonoff** [comment]
The issue that `Actions.lane_context[SharedValues::FL_CHANGELOG]` is used.

**Comment by acoutts** [comment]
Could this be related to my issue? I am actually trying to add a changelog but none is applied even though I pass in the `changelog` parameter.

https://github.com/fastlane/fastlane/issues/16575

**Comment by danez** [comment]
I worked around the issue by making sure that `changelog_from_git_commits` is called after `pilot`.
