### ISSUE TITLE
screengrab not considering frameit folder location

### ISSUE THREAD

**Issue by wellavelino** [fastlane/fastlane#16289]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm happy to open a pull request on frameit, but first I need to understand if this was made on purpose :) 

When using screengrab it pulls screenshots to:
`found this piece of code on: screengrab/runner.rb:353`
```
 # We then replace the last segment of the screenshots directory path with the device_type
 # specific name, as expected by supply
 #
 # (Moved to: fastlane/metadata/android/en-US/images/phoneScreenshots)`
```
I understand that has to be in that locally for supply to be able to upload those. But frameit requires the screenshots to be in the same folder as title.strings/keyword.strings.

My actual folder structure is

This is one specific folder for one language 
`fastlane/screenshots/language/
```
|____title.xml
|____images
| |____phoneScreenshots
| | |____screenShot3_Macros_1586444424911.png
| | |____screenShot1_TicketList_1586444420940_framed.png
| | |____screenShot3_Macros_1586444424911_framed.png
| | |____screenShot4_Notifications_1586444420200.png
| | |____screenShot2_TicketDetails_1586444424182.png
| | |____screenShot4_Notifications_1586444420200_framed.png
| | |____screenShot2_TicketDetails_1586444424182_framed.png
| | |____screenShot1_TicketList_1586444420940.png
|____title.strings
|____mock.xml

```
##### Command executed
note that language is generated using an array of languages.
```
 LANGUAGES = %w[ko ja en-US ar-SA fr-FR pl cs sv nl-NL zh-TW no en-GB bg fi da
               zh-CN pt-BR tr it ru de-DE es-ES ro th id el hi hu vi he]  
   desc "Creates localized mocks, takes screenshots"
   lane :capture_screenshots do
    #update_screenshot_mock_localizations
    # build_for_screengrab
     # screengrab
     LANGUAGES.each do |language|
       frameit(use_platform: 'ANDROID', path: "./fastlane/screenshots/#{language}/images/phoneScreenshots")
     end
   end
```

##### Complete output when running fastlane, including the stack trace and command, used

<details>
  <pre>couldn't get it returned nothing. </pre>
</details>

### Environment

<details>
  <pre> <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                    |
| --------------------------- | -------------------------------------------------------- |
| OS                          | 10.15.3                                                  |
| Ruby                        | 2.6.5                                                    |
| Bundler?                    | true                                                     |
| Git                         | git version 2.21.0                                       |
| Installation Source         | ~/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bin/fastlane |
| Host                        | Mac OS X 10.15.3 (19D76)                                 |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.5/lib                              |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                              |
| Is contained                | false                                                    |
| Is homebrew                 | false                                                    |
| Is installed via Fabric.app | false                                                    |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/              |
| Xcode Version               | 11.3.1                                                   |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_IE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

# Define languages
LANGUAGES = %w[ko ja en-US ar-SA fr-FR pl cs sv nl-NL zh-TW no en-GB bg fi da
               zh-CN pt-BR tr it ru de-DE es-ES ro th id el hi hu vi he]

platform :android do
   desc "Build debug and test APK for screenshots"
   lane :build_for_screengrab do
     build_android_app(
      task: 'assemble',
      build_type: 'Debug'
    )
     build_android_app(
       task: 'assemble',
      build_type: 'AndroidTest'
    )
   end
   
   desc "Creates localized mocks, takes screenshots"
   lane :capture_screenshots do
     #update_screenshot_mock_localizations
    # build_for_screengrab
     # screengrab
     LANGUAGES.each do |language|
       frameit(use_platform: 'ANDROID', path: "./fastlane/screenshots/#{language}/images/phoneScreenshots")
     end
   end
end

def update_screenshot_mock_localizations
  puts "Generating localized mocks"
  sh "../scripts/localization/update_screenshot_mock_localizations.rb"
end

  # desc "Submit a new Beta Build to Crashlytics Beta"
  # lane :beta do
  #   gradle(task: "clean assembleRelease")
  #   crashlytics

  #   # sh "your_script.sh"
  #   # You can also use other beta testing services here
  # end

  # desc "Deploy a new version to the Google Play"
  # lane :deploy do
  #   gradle(task: "clean assembleRelease")
  #   upload_to_play_store
# end

 # desc "Runs all the tests"
 #  lane :test do
 #    gradle(task: "test")
 #  end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("com.wellington.android") # e.g. com.krausefx.app



```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.144.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 2.0.1        |
| etc                       | 1.0.1        |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| ansi                      | 1.5.0        |
| ast                       | 2.4.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.0.3        |
| aws-partitions            | 1.292.0      |
| aws-sigv4                 | 1.1.1        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.92.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.61.1       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| cork                      | 0.3.0        |
| nap                       | 1.1.0        |
| open4                     | 1.3.4        |
| claide-plugins            | 0.9.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.17.3       |
| faraday-http-cache        | 2.0.0        |
| rchardet                  | 1.8.0        |
| git                       | 1.6.0        |
| kramdown                  | 2.1.0        |
| kramdown-parser-gfm       | 1.1.0        |
| no_proxy_fix              | 0.1.2        |
| sawyer                    | 0.8.2        |
| octokit                   | 4.18.0       |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| danger                    | 6.3.2        |
| danger-plugin-api         | 1.0.0        |
| ruby-ll                   | 2.1.2        |
| oga                       | 3.2          |
| danger-android_lint       | 0.0.8        |
| ox                        | 2.13.2       |
| danger-checkstyle_format  | 0.1.1        |
| danger-junit              | 1.0.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.5.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.73.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.1.0        |
| signet                    | 0.13.2       |
| googleauth                | 0.11.0       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.25.1       |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.9       |
| zendesk_i18n_dev_tools    | 1.1.16       |
</details>

*generated on:* **2020-04-10**
</details> </pre>
</details>

**Comment by wellavelino** [comment]
I have half PR done here, I would like some input. 
With this change, I'm considering that people that use frameit also use screengrab (which won't be always true).
In this case, would it be ok in have an extra parameter to run it?

`frameit(use_platform: "ANDROID, path:'path', consider_screengrab = bool) `

where `consider_screengrab` will set the path to `images/screenShots`

**Comment by Prater33** [comment]
Thanks for sharing such information with us keep sharing such informative post glad to see such post [provitalize](https://www.provitalize.us/)

**Comment by rogerluan** [comment]
Closing as this PR got merged already 🎉 (long time ago heh)
