### ISSUE TITLE
Match: Certificate mismatch in Xcode when using match in multiple projects

### ISSUE THREAD

**Issue by ashitanojoe** [fastlane/fastlane#16282]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

We are using match in 2 different projects, each pointing to a separate git repository for match storage. The match repositories are set up using the same Apple Developer account, named "Fast Lane". This results in 2 provisioning profile and 2 certificates in the Apple Developer Portal.

`match Development com.our.app1` using certificate named `Fast Lane`
`match Development com.our.app2` using certificate named `Fast Lane`

Although the above certificates have the same name, they are actually different certificates. This confuses Xcode. When I use `fastlane match development --readonly` on each of the projects, 2 different certificates with the exact same name are installed in keychain.

![image](https://user-images.githubusercontent.com/2426029/78863017-905c0980-7a73-11ea-8093-a6195962429c.png)

This confuses Xcode and results in it attempting to use the wrong certificate.

> Provisioning profile "match Development com.our.app1 doesn't include signing certificate "Apple Development: Fast Lane (XXXXXXXXXX)".

![image](https://user-images.githubusercontent.com/2426029/78860862-33118980-7a6e-11ea-8256-fc9bd05e6db3.png)

The expected behavior is that match create certificates that are distinguishable by the development environment that uses them. If this is by design, what is the proper way to use match in this scenario? Is having separate Apple Developer Portal accounts for each project the correct way to use match in this case, since a certificate is named after the account that created it?

### Environment

<details>
<summary> :no_entry_sign: fastlane environment :no_entry_sign: </summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.3                                     |
| Ruby                        | 2.6.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.10.1                          |
| Installation Source         | ~/.rbenv/versions/2.6.2/bin/fastlane        |
| Host                        | Mac OS X 10.15.3 (19D76)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.2/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2r  26 Feb 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.4                                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found :no_entry_sign: |

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.145.0 | :white_check_mark: Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 2.0.1        |
| etc                       | 1.0.1        |
| CFPropertyList            | 3.0.2        |
| concurrent-ruby           | 1.1.6        |
| i18n                      | 0.9.5        |
| minitest                  | 5.14.0       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.7        |
| activesupport             | 4.2.11.1     |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| httpclient                | 2.8.3        |
| json                      | 2.3.0        |
| algoliasearch             | 1.27.1       |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.296.0      |
| aws-sigv4                 | 1.1.1        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.94.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.61.2       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| netrc                     | 0.11.0       |
| ffi                       | 1.12.2       |
| ethon                     | 0.12.0       |
| typhoeus                  | 1.3.1        |
| cocoapods-core            | 1.9.1        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.3.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| cocoapods-trunk           | 1.4.1        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| cocoapods                 | 1.9.1        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.5.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.73.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.17.3       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.1.0        |
| signet                    | 0.14.0       |
| googleauth                | 0.11.0       |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.0       |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

  </pre>
</details>

**Comment by farfromrefug** [comment]
I am facing the same issue. Any workaround? Feeling pretty stuck with this.

**Comment by abouroubi** [comment]
I had the same problem, to resolve that you have to choose the right certificate in **Signing** category of the **Build Settings** tab of your **project**.

FYI, for this use case, if you read the docs, it's preferred to use the same repository with one branch only, match will use the same certificate for all your apps, and generate a new provisioning profile for each on of them.

**Comment by farfromrefug** [comment]
Ok can try the branch version. Modifying the project is not a possibility for menas it is auto generated

**Comment by ashitanojoe** [comment]
I worked around this issue by setting up separate developer accounts for each project, since certificates are named after the account that created it.
