### ISSUE TITLE
xcrun simctl status_bar support in fastlane

### ISSUE THREAD

**Issue by sharedRoutine** [fastlane/fastlane#16293]
### Feature Request

Xcode 11.4 comes with a new simctl command called status_bar which allows overriding the simulator status bar. However once a simulator is killed, those changes are undone.
Ideally you could run a command after fastlane has booted a simulator to update the status bar before taking screenshots. Unfortunately devices need to be booted.
Fastlane could take a parameter in Snapfile `status_bar_overrride("--time '9:41'");`

#### Motivation Behind Feature
SimularStatusMagic is the go to for changing the status bar but for every major version this needs to be updated to work properly. So Apple decided to build it into simctl. SimularStatusMagic will slowly be discontinued and fastlane should integrate an option to update the status bar for a simulator.

#### Feature Description
The easiest solution would be another variable for the Snapfile called status_bar_overrides passing the string to xcrun simctl status_bar $SIM_ID override $OVERRIDE_STR once it booted a device prior to executing the UI tests.
This will ensure that existing users don't have a profile as they don't have the key in the Snapfile.

#### Alternatives or Workarounds
None. I used SimularStatusMagic before but it breaks with iOS 13.4 (and probably earlier).

**Comment by falcon03** [comment]
Please reopen, this is a legitimate issue. Documentation needs to updated as well!

**Comment by sharedRoutine** [comment]
This issue is still present and no solution nor documentation has been provided. I‘m not sure if I can reopen the issue at this point, but otherwise I‘ll create a new one
