### ISSUE TITLE
[snapshot] alias add_photo => add_media

### ISSUE THREAD

**Issue by sbauch** [fastlane/fastlane#16290]
### Feature Request

would it make sense to rename or add an alias for snapshot's `add_photo` / `add_video` options?

happy to take a stab at it, but figured I'd check with maintainers first. It's really a cosmetic change, but one that may have saved me a few hours.

I'd been working on a custom action to use `xcrun simctl` to add contact `.vcf` files to simulators as I didn't catch the `add_photo` or `add_video` options (and i'm not dealing with photos or videos). #12347 started using `addmedia`, which is documented by Apple as:

> Add photos, live photos, videos, or contacts to the library of a device.
Usage: simctl addmedia <device> <path> [... <path>]
You can specify multiple files including a mix of photos, videos, and contacts.
You can also specify multiple live photos by providing the photo and video files. They will automatically be discovered and imported correctly.
Contacts support the vCard format.

#### Motivation Behind Feature

Better documentation mostly, and naming things to better match what they can be used for?

#### Feature Description

1. rename or the add_photos / add_videos option to add_media, or add an add_contacts option
2. rather than loop, just add all the files at once here with a space separated list - https://github.com/fastlane/fastlane/blob/bb678b06e186827c7dd202ea36fd8b3ea8c8485c/snapshot/lib/snapshot/simulator_launchers/simulator_launcher_base.rb#L89

#### Alternatives or Workarounds

I'm doing this currently, which is fine 🤷🏻‍♂️
```ruby
capture_screenshots(add_photos: Dir.glob('./vcfs/*.vcf').map(&File.method(:realpath)))
```

**Comment by janpio** [comment]
Yes, an alias would make a lot of sense here I think to make it clearer what this does.
