### ISSUE TITLE
Countries Availability - How do you set it via Deliver?

### ISSUE THREAD

**Issue by kobyle69** [fastlane/fastlane#16298]
### Question Checklist

- [V] Updated fastlane to the latest version
- [V] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [V] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [V] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Countries Availability - How do you set it via Deliver?

#### Question Description
Hi,

How can you set the Availability countries via Deliver or any other Fastlane method?

I've searched everywhere and came out short.

Thanks

**Comment by tedgonzalez** [comment]
It is not possible in the current version nor with the existing plugins

**Comment by kobyle69** [comment]
@tedgonzalez thanks, do you know if this will be included in the future?

**Comment by max-ott** [comment]
@kobyle69 You can set this directly with `spaceship`: https://github.com/fastlane/fastlane/tree/master/spaceship / https://github.com/fastlane/fastlane/blob/master/spaceship/docs/AppStoreConnect.md

**Comment by tedgonzalez** [comment]
@max-ott can you show an example how?
