### ISSUE TITLE
[Question] Send TestFlight for review, skipping binary upload

### ISSUE THREAD

**Issue by rogerluan** [fastlane/fastlane#16297]
### Question Checklist

- [x] I'm on version 2.144.0, latest is 2.145.0
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

TestFlight submission.

#### Question Description

Is there a way to skip the binary upload when submitting to TestFlight? e.g. `skip_binary_upload` parameter in `testflight` lane. I didn't find anything available, are there plans to support this (or workarounds)? I'd like to submit a build that I have already uploaded to external testers.

### Env

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                           |
| --------------------------- | --------------------------------------------------------------- |
| OS                          | 10.15.4                                                         |
| Ruby                        | 2.6.5                                                           |
| Bundler?                    | true                                                            |
| Git                         | git version 2.21.0 (Apple Git-122.2)                            |
| Installation Source         | ~/Documents/Projects/tellus-ios/.vendor/ruby/2.6.0/bin/fastlane |
| Host                        | Mac OS X 10.15.4 (19E287)                                       |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.5/lib                                     |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                                     |
| Is contained                | false                                                           |
| Is homebrew                 | false                                                           |
| Is installed via Fabric.app | false                                                           |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                     |
| Xcode Version               | 11.2.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

```ruby
    func submitLane() {
        desc("Submits a previously uploaded build to review, whenever it becomes ready. Useful when the release lane was aborted before it submitted the app for review.")
        deliver(username: iTunesConnect.appleID, skipBinaryUpload: true, skipScreenshots: true, skipMetadata: true, app: Target.main.bundleIdentifier(forEnvironment: .production))
    }
    private func submitToTestFlight(environment: Environment) {
        buildApp(environment: environment)
        testflight(username: iTunesConnect.appleID, appIdentifier: Target.main.bundleIdentifier(forEnvironment: environment), changelog: "Test all the things!", distributeExternal: true, groups: [ "boarding" ], rejectBuildWaitingForReview: true)
    }

    // NOTE: The rest of the file was removed
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.144.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| bundler                   | 2.1.4        |
| CFPropertyList            | 3.0.2        |
| ZenTest                   | 4.12.0       |
| RubyInline                | 3.12.5       |
| concurrent-ruby           | 1.1.6        |
| i18n                      | 0.9.5        |
| minitest                  | 5.14.0       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.6        |
| activesupport             | 4.2.11.1     |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| httpclient                | 2.8.3        |
| json                      | 2.3.0        |
| algoliasearch             | 1.27.1       |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.0.3        |
| aws-partitions            | 1.291.0      |
| aws-sigv4                 | 1.1.1        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.92.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.61.1       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| netrc                     | 0.11.0       |
| ffi                       | 1.12.2       |
| ethon                     | 0.12.0       |
| typhoeus                  | 1.3.1        |
| cocoapods-core            | 1.9.1        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.3.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| cocoapods-trunk           | 1.4.1        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| cocoapods                 | 1.9.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| cocoapods-binary          | 0.4.4        |
| dotenv                    | 2.7.5        |
| osx_keychain              | 1.0.2        |
| cocoapods-keys            | 2.1.0        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.5.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| emoji_regex               | 1.0.1        |
| excon                     | 0.73.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.17.3       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.1.0        |
| signet                    | 0.13.2       |
| googleauth                | 0.11.0       |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.25.1       |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| xcpretty-travis-formatter | 1.0.0        |
| mustache                  | 1.1.1        |
| open4                     | 1.3.4        |
| redcarpet                 | 3.5.0        |
| sassc                     | 2.2.1        |
| sqlite3                   | 1.4.2        |
| liferaft                  | 0.0.6        |
| xcinvoke                  | 0.3.0        |
| jazzy                     | 0.13.1       |
| psych                     | 3.0.3        |
</details>

*generated on:* **2020-04-12**
</details>

**Comment by rogerluan** [comment]
By running `bundle exec fastlane pilot help` I found out there's a lane called distribute that can be run like e.g. `bundle exec fastlane pilot distribute`, and it is documented as follows:

>distribute    Distribute a previously uploaded binary to Apple TestFlight

But after running it successfully, it logs:

>[02:58:08]: Distributing new build to testers: <app version and build number here>
>[02:58:08]: Successfully distributed build to Internal testers 🚀

I want to distribute to external testers, not internal. Is there a way to do exactly the same, but for external testers? Also, AFAIK when you upload a binary to TestFlight, it is automatically sent out to internal testers, so it's weird that it allows re-distributing to internal testers 🤔

**Comment by GRBurst** [comment]
you can call distribute like this to distribute to externals:

```
fastlane pilot distribute --distribute_external true -w "my changelog"
```

**Comment by GRBurst** [comment]
more information is provided if you run `fastlane pilot distribute --help` or `bundle exec fastlane pilot distribute --help`

**Comment by SebaRossi94** [comment]
Hi there, is there a way to perform this action through Fastfile?

**Comment by GRBurst** [comment]
@SebaRossi94  there is no action for this but you can just run it in a shell like this:

```ruby
    lane :promote do
        begin
            sh "fastlane pilot distribute --distribute_external true -g 'Beta' ..."
        rescue => exception
            puts exception
        end
    end
```

**Comment by rogerluan** [comment]
# Solution

> Note: I confirmed that this is not possible via fastlane Swift.

In your `.env` file inside `fastlane` directory:

```
PILOT_USERNAME="team@company.com"
PILOT_BETA_APP_REVIEW_INFO='{
  "contact_email": "team@company.com",
  "contact_first_name": "John",
  "contact_last_name": "Doe",
  "contact_phone": "+123456789",
  "demo_account_name": "+1234567890",
  "demo_account_password": "123456"
}'
PILOT_GROUPS=["your-pilot-group"]
PILOT_DISTRIBUTE_EXTERNAL=true
```

Then run:

```
[bundle exec] fastlane pilot distribute -a your_bundle_identifier_here
```

And this will submit your previously uploaded binary to TestFlight external testers.

**Comment by SebaRossi94** [comment]
Sorry for insisting here but i have another doubt.
I ran succesfully
`fastlane pilot distribute --app_version '[version]' --distribute_external true -w 'changelog -g '[group]''`
to publish the build from app_version variable to [group] setting the bundle identifier on AppFile.
The problem is that i can't set any end of line in the changelog text (i tried \n character and literally the release_notes were 'bla_1\nbla_2\nbla_3\n'
As far as i can see i can set all variables using .env file as @rogerluan said on last coment, but is there a way to get the release notes from a .txt file? i tried to set the release notes with `File.read()` on the Deliverfile with no success

**Comment by rogerluan** [comment]
@SebaRossi94 that's a bit off-topic hehe but happy to help. Check out https://docs.fastlane.tools/actions/deliver/#quick-start, you'll see there's a handy method (`fastlane deliver init`) that generates your app's metadata for you, fetching from iTunes Connect. You can push that to your version control system (such as git), if you want.

From there, you can edit those text files as you wish, and fastlane tools (deliver and others) will always look for the existence of these metadata files, and if they're available, you don't have to provide them via command line.

Hope it helped!

**Comment by SebaRossi94** [comment]
thanks @rogerluan i'll keep testing and let you know the results

**Comment by SebaRossi94** [comment]
Update here @rogerluan i managed to distribute to external testers using 
`sh(fastlane pilot distribute --app_version 'version' -g 'group1','group2')`
I had to do this because when adding 
```
PILOT_GROUPS=["group1","group2"]
PILOT_DISTRIBUTE_EXTERNAL=true
```
to .env file, for some reason the build wasn't distributed to these groups, idk if this is a bug or a misscoding from my side. Regards

**Comment by rogerluan** [comment]
Oh interesting, maybe something related to how you're separating the elements in the array, but I can't tell, looks correct to me (comma-separated, no spaces before or after the comma). Thanks for the update, glad it worked out for you!
