### ISSUE TITLE
Spaceship login error

### ISSUE THREAD

**Issue by forceramos** [fastlane/fastlane#16304]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I´m trying to connect to itunes using spaceship to bulk create some consumable products.
following this guide that worked some time ago [Automating IAP creation in iTunes Connect](https://goodkindoflazy.com/2017/12/11/automating-iap-creation-in-itunes-connect/).
But on the fist line, at login method, returns an error.
I searched the web and i found something about apple two step login. And for this cases we may create some system varables and use method "fastlane spaceauth" to login, but i did not found any exemples of how to use this method.

##### Command executed
Spaceship::Tunes.login("login", "pass")

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>
PS C:\apple_products> ruby .\test.rb
No such file or directory @ rb_sysopen - /tmp/spaceship1586831345_16204_22439120.log
Traceback (most recent call last):
        22: from ./test.rb:10:in `<main>'
        21: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
        20: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:346:in `login'
        19: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:384:in `login'
        18: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:775:in `do_login'
        17: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/tunes/tunes_client.rb:127:in `send_login_request'
        16: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:471:in `send_shared_login_request'
        15: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:682:in `request'
        14: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:791:in `log_request'
        13: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:841:in `extract_key_from_block'
        12: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:476:in `block in send_shared_login_request'
        11: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:547:in `itc_service_key'
        10: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:682:in `request'
         9: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:811:in `log_request'
         8: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:242:in `logger'
         7: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:242:in `new'
         6: from C:/Ruby26-x64/lib/ruby/2.6.0/logger.rb:387:in `initialize'
         5: from C:/Ruby26-x64/lib/ruby/2.6.0/logger.rb:387:in `new'
         4: from C:/Ruby26-x64/lib/ruby/2.6.0/logger.rb:671:in `initialize'
         3: from C:/Ruby26-x64/lib/ruby/2.6.0/logger.rb:736:in `set_dev'
         2: from C:/Ruby26-x64/lib/ruby/2.6.0/logger.rb:744:in `open_logfile'
         1: from C:/Ruby26-x64/lib/ruby/2.6.0/logger.rb:744:in `open'
C:/Ruby26-x64/lib/ruby/2.6.0/logger.rb:744:in `initialize': No such file or directory @ rb_sysopen - /tmp/spaceship1586831345_16204_22439120.log (Errno::ENOENT)
        24: from ./test.rb:10:in `<main>'
        23: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
        22: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:346:in `login'
        21: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:384:in `login'
        20: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:775:in `do_login'
        19: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/tunes/tunes_client.rb:127:in `send_login_request'
        18: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:471:in `send_shared_login_request'
        17: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:682:in `request'
        16: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:791:in `log_request'
        15: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:841:in `extract_key_from_block'
        14: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:476:in `block in send_shared_login_request'
        13: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:547:in `itc_service_key'
        12: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:682:in `request'
        11: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:811:in `log_request'
        10: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:242:in `logger'
         9: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:242:in `new'
         8: from C:/Ruby26-x64/lib/ruby/2.6.0/logger.rb:387:in `initialize'
         7: from C:/Ruby26-x64/lib/ruby/2.6.0/logger.rb:387:in `new'
         6: from C:/Ruby26-x64/lib/ruby/2.6.0/logger.rb:671:in `initialize'
         5: from C:/Ruby26-x64/lib/ruby/2.6.0/logger.rb:736:in `set_dev'
         4: from C:/Ruby26-x64/lib/ruby/2.6.0/logger.rb:742:in `open_logfile'
         3: from C:/Ruby26-x64/lib/ruby/2.6.0/logger.rb:746:in `rescue in open_logfile'
         2: from C:/Ruby26-x64/lib/ruby/2.6.0/logger.rb:752:in `create_logfile'
         1: from C:/Ruby26-x64/lib/ruby/2.6.0/logger.rb:752:in `open'
C:/Ruby26-x64/lib/ruby/2.6.0/logger.rb:752:in `initialize': No such file or directory @ rb_sysopen - /tmp/spaceship1586831345_16204_22439120.log (Errno::ENOENT)
        12: from ./test.rb:10:in `<main>'
        11: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
        10: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:346:in `login'
         9: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:384:in `login'
         8: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:775:in `do_login'
         7: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/tunes/tunes_client.rb:127:in `send_login_request'
         6: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:471:in `send_shared_login_request'
         5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:682:in `request'
         4: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:791:in `log_request'
         3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:841:in `extract_key_from_block'
         2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:476:in `block in send_shared_login_request'
         1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:537:in `itc_service_key'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/client.rb:558:in `rescue in itc_service_key': Could not receive latest API key from App Store Connect, this might be a server issue. (Spaceship::AppleTimeoutError)
  </pre>
</details>

### Environment

<details>
  <pre> 
PS C:\apple_products> fastlane env
 [✔] 🚀
[10:21:36]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[10:21:36]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
[10:21:40]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                        |
| --------------------------- | ---------------------------- |
| OS                          | UNKNOWN                      |
| Ruby                        | 2.6.6                        |
| Bundler?                    | false                        |
| Git                         | git version 2.23.0.windows.1 |
| Installation Source         | C:/Ruby26-x64/bin/fastlane   |
| Host                        | Unknown  ()                  |
| Ruby Lib Dir                | C:/Ruby26-x64/lib            |
| OpenSSL Version             | OpenSSL 1.1.1e  17 Mar 2020  |
| Is contained                | false                        |
| Is homebrew                 | false                        |
| Is installed via Fabric.app | false                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.145.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.16.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.73.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.0        |
| googleauth                | 0.12.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.5.1        |
| google-cloud-storage      | 1.26.0       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.296.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.1.1        |
| aws-sdk-core              | 3.94.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.61.2       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| fiddle                    | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| zlib                      | 1.0.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-04-14**
</details>
[10:21:40]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[10:21:40]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅
[10:21:40]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
 </pre>
</details>

**Comment by forceramos** [comment]
tried with both ruby 2.7.1 and this 2.6.6, same problems.

**Comment by max-ott** [comment]
I recommend creating a new account without 2 Factor Authentication. Also ruby does not seem to have access to the files folder (or is not working on Windows).
