### ISSUE TITLE
Build failing for 'snapshot' - but works for 'beta' - Authentication error

### ISSUE THREAD

**Issue by SteveBlackUK** [fastlane/fastlane#16301]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When I use 'fastlane beta' to build and upload to app store + test flight, everything works beautifully; however, when I build to get screenshots via 'fastlane snapshot' - I get a build failure due to athentication.

[07:45:57]: ▸   Authentication failed because no credentials were provided.

Not sure how to check what credentials are the issue - nothing in the error or logs that I can see.  Also, I would have assumed if the the build process works for 'beta' it would be the same for 'snapshot' - what's different?

I'm relatively inexperienced - so please let me know if you need any more info!

##### Command executed

fastlane snapshot
as well as
fastlane ios screenshot

##### Complete output when running fastlane, including the stack trace and command used
<details>

```
[✔] 🚀 
[07:45:45]: Successfully loaded '/Users/xxx/Dropbox/Challenges iOS app/fastlane/Snapfile' 📄

+------------------------+-----------------------+
|   Detected Values from './fastlane/Snapfile'   |
+------------------------+-----------------------+
| devices                | ["iPhone 11 Pro Max"] |
| languages              | ["en-US"]             |
| scheme                 | PZT     |
| output_directory       | ./screenshots         |
| number_of_retries      | 0                     |
| stop_after_first_error | true                  |
+------------------------+-----------------------+

[07:45:46]: Resolving Swift Package Manager dependencies...
[07:45:46]: $ xcodebuild -resolvePackageDependencies -workspace ./PZT.xcworkspace -scheme PZT
[07:45:47]: ▸ Resolve Package Graph
[07:45:47]: ▸ Resolved source packages:
[07:45:47]: ▸   SDWebImage: https://github.com/SDWebImage/SDWebImage.git @ 5.5.2
[07:45:47]: ▸ resolved source packages: SDWebImage
[07:45:48]: $ xcodebuild -showBuildSettings -workspace ./PZT.xcworkspace -scheme PZT

+----------------------------+--------------------------------------------------+
|                         Summary for snapshot 2.145.0                          |
+----------------------------+--------------------------------------------------+
| workspace                  | ./PZT.xcworkspace                   |
| output_directory           | /Users/xxx/Dropbox/Challenges iOS  |
|                            | app/screenshots                                  |
| devices                    | ["iPhone 11 Pro Max"]                            |
| languages                  | ["en-US"]                                        |
| launch_arguments           | [""]                                             |
| output_simulator_logs      | false                                            |
| skip_open_summary          | false                                            |
| skip_helper_version_check  | false                                            |
| clear_previous_screenshots | false                                            |
| reinstall_app              | false                                            |
| erase_simulator            | false                                            |
| localize_simulator         | false                                            |
| app_identifier             | com.myapp.myapp                     |
| buildlog_path              | ~/Library/Logs/snapshot                          |
| clean                      | false                                            |
| scheme                     | PZT |
| number_of_retries          | 0                                                |
| stop_after_first_error     | true                                             |
| result_bundle              | false                                            |
| concurrent_simulators      | true                                             |
| disable_slide_to_type      | false                                            |
| xcode_path                 | /Applications/Xcode.app                          |
+----------------------------+--------------------------------------------------+

[07:45:51]: Building and running project - this might take some time...
[07:45:51]: Patching simulators '/Users/xxx/Library/Preferences/com.apple.iphonesimulator.plist' to scale to 100%
[07:45:53]: Using device named 'iPhone 11 Pro Max' with version '13.3' because no match was found for version '13.2'
[07:45:53]: Running snapshot on: iPhone 11 Pro Max
[07:45:53]: $ set -o pipefail && xcodebuild -workspace ./PZT.xcworkspace -scheme PZT -derivedDataPath '/var/folders/qs/cyr14d9n3zj11p5bcnr4vdh00000gn/T/snapshot_derived20200414-81267-14yhnbm' -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=13.3' FASTLANE_SNAPSHOT=YES build test | tee /Users/xxx/Library/Logs/snapshot/Challenges-PZT.log | xcpretty 
[07:45:53]: ▸ Loading...
[07:45:57]: ▸ xcodebuild: error: Could not resolve package dependencies:
[07:45:57]: ▸   Authentication failed because no credentials were provided.
xcodebuild: error: Could not resolve package dependencies:
  Authentication failed because no credentials were provided.
[07:45:57]: Exit status: 74
[07:45:57]: Tests failed while running on: iPhone 11 Pro Max
[07:45:57]: For more detail about the test failures, check the logs here:
[07:45:57]: /Users/xxx/Library/Logs/snapshot/PZT.log
[07:45:57]:  
[07:45:57]: You can also find the test result data here:
[07:45:57]: /var/folders/qs/cyr14d9n3zj11p5bcnr4vdh00000gn/T/snapshot_derived20200414-81267-14yhnbm/Logs/Test
[07:45:57]:  
[07:45:57]: You can find the incomplete screenshots here:
[07:45:57]: /Users/xxx/Library/Caches/tools.fastlane/screenshots
[07:45:57]: /Users/xxx/Dropbox/PZT iOS app/screenshots
[07:45:57]: Caught error... 74

```

</details>

### Environment

<details>
  <pre> ### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.145.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.14.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.72.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.13.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.11.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.5.1        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.290.0      |
| aws-eventstream           | 1.0.3        |
| aws-sigv4                 | 1.1.1        |
| aws-sdk-core              | 3.92.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.61.1       |
| CFPropertyList            | 3.0.2        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</pre>
</details>

**Comment by janpio** [comment]
> [07:45:46]: Resolving Swift Package Manager dependencies...
> [07:45:46]: $ xcodebuild -resolvePackageDependencies -workspace ./PZT.xcworkspace -scheme PZT

> [07:45:57]: ▸ xcodebuild: error: Could not resolve package dependencies:
> [07:45:57]: ▸   Authentication failed because no credentials were provided.
> xcodebuild: error: Could not resolve package dependencies:
>   Authentication failed because no credentials were provided.

Any funny Swift dependencies that might require credentials?

**Comment by SteveBlackUK** [comment]
@janpio - not that I know of....particularly confusing to me is why fastlane beta would work fine - is there a different build path / setup required for snapshot vs beta?  

I've got one swift package dependency (SDWebImage, but doesn't require credentials that I recall) and this is my set of pods managed via cocoapods:

pod 'DZNEmptyDataSet'
pod 'lottie-ios'
pod 'Firebase/Analytics'
pod 'Firebase/Crashlytics'
pod 'paper-onboarding'

Is the best idea here to go pod by pod and try removing to see if it does the trick?  I keep coming back to the 'why would 'fastlane beta' work?' question though - is there a way to see what might be happening there that isn't with snapshot?  Don't recall setting up any credentials there (outside of the app store connect 2fa, but that wouldn't apply here anyway)...

**Comment by SteveBlackUK** [comment]
In the logfile produced, it seems to be repeating the below.  Potentially that points to an issue with SDWebImage.git?  Though doesn't seem to be any issue when I try to grab that directly / require being logged into github.  Think that might be the problem?  Suggestions on troubleshooting if so?  

Thanks for the help, as you can probably tell - this relative newbie may be in a bit over my head :)

```
User defaults from command line:
    IDEDerivedDataPathOverride = /var/folders/qs/cyr14d9n3zj11p5bcnr4vdh00000gn/T/snapshot_derived20200419-18006-s10kto

Build settings from command line:
    FASTLANE_SNAPSHOT = YES

Resolve Package Graph

Fetching https://github.com/SDWebImage/SDWebImage.git

User defaults from command line:
    IDEDerivedDataPathOverride = /var/folders/qs/cyr14d9n3zj11p5bcnr4vdh00000gn/T/snapshot_derived20200419-18006-s10kto

Build settings from command line:
    FASTLANE_SNAPSHOT = YES

Resolve Package Graph

Fetching https://github.com/SDWebImage/SDWebImage.git
```

**Comment by SteveBlackUK** [comment]
So I've uninstalled SDWebImage that I'd installed with Swift Package Manager in Xcode and re-installed it via CocoaPods and it now builds okay.   No authentication or anything set up via CocoaPods - so seems specific to SPM.

Hope it helps anyone else that comes across similar issues!
