### ISSUE TITLE
What is the correct way to escape / quote parameters passed to lanes?

### ISSUE THREAD

**Issue by mikebarlow** [fastlane/fastlane#16303]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
What is the correct way to escape / quote parameters passed to lanes?

#### Question Description
So our app is a "white label" react native app, which is powered by an internal API. Our build process starts with a NodeJS CLI app which pulls the apps information from our internal API. This information is then passed to fastlane to begin the signing / build / upload process.

Part of the API returns some copyright text to be used when submitting to the App Store, this however had some special characters in which cause the build process to fail. We wrapped the parameters in quotes like this

`fastlane ios release bundle_identifier:"com.foo.bar" copyright:"FooBar"`

However that doesn't seem to work, one of the parameters was a relative file path to a config file and it resulted in a path of `/our/broken/"file/path/here"` and the bundle identifier in the plist was saved as `<string>&quot;com.foo.bar&quot;</string>`.

Has anyone else run into the need for this / is there a recommended way to handle the need to escape parameters? I'm taking over on this from a previous developer and NodeJS / Ruby aren't my strong points so I've hit a brick wall with this.

Thanks

**Comment by mikebarlow** [comment]
**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.145.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.73.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.1.0        |
| googleauth                | 0.11.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| emoji_regex               | 1.0.1        |
| CFPropertyList            | 3.0.2        |
| json                      | 2.3.0        |
| signet                    | 0.14.0       |
| digest-crc                | 0.5.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-env          | 1.3.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.0       |
| aws-eventstream           | 1.0.3        |
| aws-sigv4                 | 1.1.1        |
| aws-partitions            | 1.295.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.93.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.61.2       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

**Comment by mikebarlow** [comment]
To avoid posting the mostly irrelevant fastfile, here is the line where we are trying to move the firebase config into the correct location.

The nodeJS app at the beginning downloads the config from the API in to a tmp folder and then moves it into the app for compiling. 

`FileUtils.mv(File.expand_path("../#{options[:firebase_config]}", __dir__), firebase_config_path)`

**Comment by max-ott** [comment]
Trying escaping with `\` or use single quotes `'`

**Comment by janpio** [comment]
I would suggest you just add some output of all the params and look at what they look like. This should help you to understand what your program is working with.
