### ISSUE TITLE
after update mac os catalina 10.15.4 get [!] no implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by rubenmeza** [fastlane/fastlane#16308]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
After I update my mac to catalina 10.15.4 and excute a lane that it was working well I get the error [!] no implicit conversion of nil into String (TypeError)

##### Command executed
fastlane android internal

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
➜ fastlane android internal --verbose       
[✔] 🚀 
DEBUG [2020-04-14 23:22:01.24]: Checking if there are any plugins that should be loaded...
Successfully loaded Appfile at path '/path/fastlane/Appfile'
- json_key_file: '/path/to/api.json'
- package_name: 'com.example.ap'
-------
INFO [2020-04-14 23:22:01.71]: Driving the lane 'android internal' 🚀
INFO [2020-04-14 23:22:01.72]: ----------------------------------------
INFO [2020-04-14 23:22:01.72]: --- Step: Switch to android abb lane ---
INFO [2020-04-14 23:22:01.72]: ----------------------------------------
INFO [2020-04-14 23:22:01.72]: Cruising over to lane 'android abb' 🚖
INFO [2020-04-14 23:22:01.73]: -------------------------------------------------------------------------------------------------------------------
INFO [2020-04-14 23:22:01.73]: Step: tns build android --env.uglify --release --env.snapshot --env.compileSnapshot --clean --env.production --env.hiddenSourceMap --aab --key-store-path ../certs/app.keystore --key-store-password '' --key-store-alias '' --key-store-alias-password ''
INFO [2020-04-14 23:22:01.73]: -------------------------------------------------------------------------------------------------------------------
INFO [2020-04-14 23:22:01.73]: $ tns build android --env.uglify --release --env.snapshot --env.compileSnapshot --clean --env.production --env.hiddenSourceMap --aab --key-store-path ../certs/app.keystore --key-store-password '' --key-store-alias '' --key-store-alias-password ''
WARN [2020-04-14 23:22:01.76]: Lane Context:
INFO [2020-04-14 23:22:01.76]: {:PLATFORM_NAME=>:android, :LANE_NAME=>"android internal"}
ERROR [2020-04-14 23:22:01.76]: no implicit conversion of nil into String
INFO [2020-04-14 23:22:01.76]: Successfully generated documentation at path '/path/fastlane/README.md'

+------+-------------------------------------------+-------------+
|                        fastlane summary                        |
+------+-------------------------------------------+-------------+
| Step | Action                                    | Time (in s) |
+------+-------------------------------------------+-------------+
| 1    | Switch to android abb lane                | 0           |
| 💥   | tns build android --env.uglify --release  | 0           |
|      | --env.snapshot --env                      |             |
+------+-------------------------------------------+-------------+

ERROR [2020-04-14 23:22:01.80]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: no implicit conversion of nil into String

URL: https://api.github.com/search/issues?q=no%20implicit%20conversion%20of%20nil%20into%20String+repo:fastlane/fastlane
➡️  bundler: failed to load command: fastlane (/usr/local/bin/fastlane) TypeError: [!] no implicit conversion of nil into String
    https://github.com/fastlane/fastlane/issues/16232 [closed] 3 💬
    2 weeks ago

➡️  bundler: failed to load command: fastlane  TypeError: [!] no implicit conversion of nil into String
    https://github.com/fastlane/fastlane/issues/15714 [closed] 6 💬
    3 weeks ago

➡️  How to upload Multiple apps screenshots and meta data upload to appstore 
    https://github.com/fastlane/fastlane/issues/15885 [closed] 5 💬
    4 weeks ago

and 80 more at: https://github.com/fastlane/fastlane/search?q=no%20implicit%20conversion%20of%20nil%20into%20String&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
        34: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
        33: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        32: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/bin/fastlane:23:in `<main>'
        31: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/bin/fastlane:23:in `load'
        30: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/bin/fastlane:23:in `<top (required)>'
        29: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
        28: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        27: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
        26: from /Users/rubenmezarazo/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        25: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        24: from /Users/rubenmezarazo/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        23: from /Users/rubenmezarazo/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        22: from /Users/rubenmezarazo/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        21: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
        20: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        19: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
        18: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        17: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        16: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        15: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        14: from Fastfile:38:in `block (2 levels) in parsing_binding'
        13: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        12: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
        11: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
        10: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/lane.rb:33:in `call'
         9: from Fastfile:17:in `block (2 levels) in parsing_binding'
         8: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/fast_file.rb:212:in `sh'
         7: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/fast_file.rb:218:in `sh'
         6: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
         5: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/fast_file.rb:219:in `block in sh'
         4: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/helper/sh_helper.rb:16:in `sh_no_action'
         3: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/helper/sh_helper.rb:54:in `sh_control_output'
         2: from /Users/rubenmezarazo/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/open3.rb:208:in `popen2e'
         1: from /Users/rubenmezarazo/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/open3.rb:213:in `popen_run'
/Users/rubenmezarazo/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/open3.rb:213:in `spawn': no implicit conversion of nil into String (TypeError)
        34: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
        33: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        32: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/bin/fastlane:23:in `<main>'
        31: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/bin/fastlane:23:in `load'
        30: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/bin/fastlane:23:in `<top (required)>'
        29: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
        28: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        27: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
        26: from /Users/rubenmezarazo/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        25: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        24: from /Users/rubenmezarazo/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        23: from /Users/rubenmezarazo/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        22: from /Users/rubenmezarazo/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        21: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
        20: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        19: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
        18: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        17: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        16: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        15: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        14: from Fastfile:38:in `block (2 levels) in parsing_binding'
        13: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        12: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
        11: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
        10: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/lane.rb:33:in `call'
         9: from Fastfile:17:in `block (2 levels) in parsing_binding'
         8: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/fast_file.rb:212:in `sh'
         7: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/fast_file.rb:218:in `sh'
         6: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
         5: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/fast_file.rb:219:in `block in sh'
         4: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/helper/sh_helper.rb:16:in `sh_no_action'
         3: from /Users/rubenmezarazo/.rvm/gems/ruby-2.6.5/gems/fastlane-2.145.0/fastlane/lib/fastlane/helper/sh_helper.rb:54:in `sh_control_output'
         2: from /Users/rubenmezarazo/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/open3.rb:208:in `popen2e'
         1: from /Users/rubenmezarazo/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/open3.rb:213:in `popen_run'
/Users/rubenmezarazo/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/open3.rb:213:in `spawn': [!] no implicit conversion of nil into String (TypeError)
  </pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.4                                     |
| Ruby                        | 2.6.5                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.15.0                          |
| Installation Source         | ~/.rvm/gems/ruby-2.6.5/bin/fastlane         |
| Host                        | Mac OS X 10.15.4 (19E287)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.5/lib                |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.4                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
platform :android do

    desc 'Build APK Android application.'
    lane :apk do
        sh(
            "tns",
            "build",
            "android",
            "--env.uglify",
            "--env.snapshot",
            "--env.compileSnapshot",
        )
    end

    desc 'Build ABB Android application.'
    lane :abb do
        sh(
            "tns",
            "build",
            "android",
            "--env.uglify",
            "--release",
            "--env.snapshot",
            "--env.compileSnapshot",
            "--clean",
            "--env.production",
            "--env.hiddenSourceMap",
            "--aab",
            "--key-store-path", "../certs/app.keystore",
            "--key-store-password", ENV["KEYSTORE_PASSWORD"],
            "--key-store-alias", ENV["KEYSTORE_ALIAS"],
            "--key-store-alias-password", ENV["KEYSTORE_ALIAS_PASSWORD"]
        )
    end

    desc 'Ship to Playstore Internal track.'
    lane :internal do
        abb

        changelog_from_git_commits

        upload_to_play_store(
            track: 'internal',
            json_key_data: ENV["PLAYSTORE_JSON_KEY_DATA"],
            aab: './platforms/android/app/build/outputs/bundle/release/app-release.aab',
            package_name: 'com.example.ap'
        )
    end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("/path/to/api.json")
package_name("com.example.app")

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.145.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.17.3       |
| etc                       | 1.0.1        |
| forwardable               | 1.2.0        |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.296.0      |
| aws-sigv4                 | 1.1.1        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.94.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.61.2       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.5.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.73.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.17.3       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.1.0        |
| signet                    | 0.14.0       |
| googleauth                | 0.12.0       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.0       |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.16.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2020-04-14**
</details></pre>
</details>

**Comment by janpio** [comment]
From looking at the output, it seems something with the `tns` command might have changed. Possible?

**Comment by rubenmeza** [comment]
> From looking at the output, it seems something with the `tns` command might have changed. Possible?

Hi @janpio, all `tns` commands are working fine if i execute them directly, and i been able to execute same code in another mac that is not updated and works well, so i think the issue happen after update mac os

**Comment by brozot** [comment]
The error is certainly coming form adb_helper.rb
the adb_path path is nil when it is passed to File.expand_path(adb_path)

```ruby
def initialize(adb_path: nil, adb_host: nil)
        android_home = ENV['ANDROID_HOME'] || ENV['ANDROID_SDK_ROOT'] || ENV['ANDROID_SDK']
        if (adb_path.nil? || adb_path == "adb") && android_home
          adb_path = File.join(android_home, "platform-tools", "adb")
        end
        
        self.adb_path = File.expand_path(adb_path)
        self.adb_host = adb_host
      end
```

Please try to define **android_home**,
 it has fixed the issue for me

**Comment by rubenmeza** [comment]
> The error is certainly coming form adb_helper.rb
> the adb_path path is nil when it is passed to File.expand_path(adb_path)
> 
> ```ruby
> def initialize(adb_path: nil, adb_host: nil)
>         android_home = ENV['ANDROID_HOME'] || ENV['ANDROID_SDK_ROOT'] || ENV['ANDROID_SDK']
>         if (adb_path.nil? || adb_path == "adb") && android_home
>           adb_path = File.join(android_home, "platform-tools", "adb")
>         end
>         
>         self.adb_path = File.expand_path(adb_path)
>         self.adb_host = adb_host
>       end
> ```
> 
> Please try to define **android_home**,
> it has fixed the issue for me

Hello, @brozot I have always had ANDROID_HOME defined, so I don't think that it was my issue, also I don't see adb_helper.rb file on stack trace error output

![Screen Shot 2020-04-21 at 13 57 44](https://user-images.githubusercontent.com/497410/79903705-2891b100-83d9-11ea-9a26-868bbfb95f40.png)

**Comment by flaviolazzarini** [comment]
I am facing the same problem. I doublechecked and I set the correct `$ANDROID_HOME` Path Variable inside of my `.zshrc` File. Interestingly if I set the `$ANDROID_HOME` variable with `export ANDROID_HOME=$ANDROID_HOME` in the active terminal, the lane works as expected 🤷🏻‍♂️. I'll use this as a workaround until I find out where the problem is.

**Comment by rubenmeza** [comment]
> I am facing the same problem. I doublechecked and I set the correct `$ANDROID_HOME` Path Variable inside of my `.zshrc` File. Interestingly if I set the `$ANDROID_HOME` variable with `export ANDROID_HOME=$ANDROID_HOME` in the active terminal, the lane works as expected 🤷🏻‍♂️. I'll use this as a workaround until I find out where the problem is.

Hi @flaviolazzarini  I was about to try to export the $ANDROID_HOME in the active terminal as you said and I realized that there is an update for Fastlane so I updated from 2.145.0  to 2.146.1 and now the commands are working fine, thank you all for your help, I close the issue  

`export ANDROID_HOME=$ANDROID_HOME`

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.4                                     |
| Ruby                        | 2.6.5                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.15.0                          |
| Installation Source         | ~/.rvm/gems/ruby-2.6.5/bin/fastlane         |
| Host                        | Mac OS X 10.15.4 (19E287)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.5/lib                |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.4                                        |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
platform :android do

    desc 'Build APK Android application.'
    lane :apk do
        sh(
            "tns",
            "build",
            "android",
            "--env.uglify",
            "--env.snapshot",
            "--env.compileSnapshot",
        )
    end

    desc 'Build ABB Android application.'
    lane :abb do
        sh(
            "tns",
            "build",
            "android",
            "--env.uglify",
            "--release",
            "--env.snapshot",
            "--env.compileSnapshot",
            "--clean",
            "--env.production",
            "--env.hiddenSourceMap",
            "--aab",
            "--key-store-path", "../certs/app.keystore",
            "--key-store-password", ENV["KEYSTORE_PASSWORD"],
            "--key-store-alias", ENV["KEYSTORE_ALIAS"],
            "--key-store-alias-password", ENV["KEYSTORE_ALIAS_PASSWORD"]
        )
    end

    desc 'Ship to Playstore Internal track.'
    lane :internal do
        abb

        changelog_from_git_commits

        upload_to_play_store(
            track: 'internal',
            json_key_data: ENV["PLAYSTORE_JSON_KEY_DATA"],
            aab: './platforms/android/app/build/outputs/bundle/release/app-release.aab',
            package_name: 'com.example.app'
        )
    end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("/path/to/api.json")
package_name("com.example.app")

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.146.1 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.17.3       |
| etc                       | 1.0.1        |
| forwardable               | 1.2.0        |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.312.0      |
| aws-sigv4                 | 1.1.3        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.95.0       |
| aws-sdk-kms               | 1.31.0       |
| aws-sdk-s3                | 1.64.0       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.5.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.73.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.17.3       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.1.0        |
| signet                    | 0.14.0       |
| googleauth                | 0.12.0       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.1       |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.16.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>


*generated on:* **2020-05-11**
</details>
