### ISSUE TITLE
Fastlane match + multiple apps + git branches

### ISSUE THREAD

**Issue by odanu** [fastlane/fastlane#16311]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
 fastlane match with git_branch
 No
 No

#### Question Description

Hey Hey!
Setup:
XCode 11.4, fastlane 2.145.0, 1 Team, 2 apps, 1 certificates repo(master, branch1, branch2).
We are having 2 apps, each having 3 app identifiers, having a separate certificates branch for each of the app. 
Doing a full cleanup including usage of `nuke` and manually deleting the certificates from keychain.
Running the following lane to create certificates, in both app root folders:
```
lane :create_certs do
    match(readonly: false, type: 'appstore', git_branch: CERTIFICATES_GIT_BRANCH)
    match(readonly: false, type: 'development', force_for_new_devices: true, git_branch: CERTIFICATES_GIT_BRANCH)
  end
```
When it runs in the first app, pointing to Branch1, everything goes smooth and well, all certificates and Prov. Prof. are created. When running in the second app root folder, pointing to Branch2, things start to go in the bad direction. Says: `Could not create another Development certificate, reached the maximum number of available Development certificates.` Besides that, a second Distribution certificate is created.

I googled all the possible sources, read the Bible and crossed the fingers and it looks like all the sources say that I am doing the right thing: when having more apps in the same team, using `git_branch` should help better managing certificates and profiles, by **reusing** the certificates.
So now, I am totally stuck and don't understand why it doesn't reuse and wants to create a new certificate?
Maybe that's because things changed since XCode 11?
Maybe my flow on using branches and `match` is wrong and I should somehow adjust it?

I was also already thinking maybe I just need to use single branch, and `match` will find the certificates to be reused by the 2 apps, and just create new profiles for each of the app?

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.3                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.1 (Apple Git-126)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.3 (19D76)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.4                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version '2.140.0'
default_platform(:ios)

SCHEME = ENV['APPLICATION_SCHEME']
TEST_CONFIG = ENV['TEST_CONFIGURATION']
BUILD_CONFIG = ENV['BUILD_CONFIGURATION']
CERTIFICATES_GIT_BRANCH = 'XXX'

platform :ios do

  before_all do
    setup_circle_ci
  end

  desc 'Clears all developer portal certificates. Note: Use locally only'
  lane :clear_all_certs do
    cli = "fastlane match nuke development --skip_confirmation true --git_branch #{CERTIFICATES_GIT_BRANCH}"
    sh(cli)
    cli = "fastlane match nuke distribution --skip_confirmation true --git_branch #{CERTIFICATES_GIT_BRANCH}"
    sh(cli)
  end

  desc 'Create certificates and provisioning profiles adding new devices. Note: Use locally only'
  lane :create_certs do
    match(readonly: false, type: 'appstore', git_branch: CERTIFICATES_GIT_BRANCH)
    match(readonly: false, type: 'development', force_for_new_devices: true, git_branch: CERTIFICATES_GIT_BRANCH)
  end

  desc 'Retrieve certificates. Note: Use locally only'
  lane :get_certs do
    get_certs('development')
    get_certs('appstore')
  end

  def get_certs(type)
      match(readonly: true, type: type, force_for_new_devices: true, git_branch: CERTIFICATES_GIT_BRANCH)
  end

end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.145.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.71.1       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.0.2        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| signet                    | 0.12.0       |
| os                        | 1.0.1        |
| googleauth                | 0.10.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.296.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.1.1        |
| aws-sdk-core              | 3.94.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.61.2       |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.14.0       |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.2        |
| faraday                   | 0.17.3       |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.7        |
| multi_json                | 1.14.1       |
| memoist                   | 0.16.2       |
| digest-crc                | 0.4.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.25.1       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-04-15**
</details>

**Comment by odanu** [comment]
It could be somehow related to [this one](https://github.com/fastlane/fastlane/issues/16210)

**Comment by QingyuHu** [comment]
I got the same problem. This is what i did.
when you run in the second app, set generate_apple_certs(false).
