### ISSUE TITLE
How to read Shell Curl output into a variable

### ISSUE THREAD

**Issue by userException** [fastlane/fastlane#16323]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

#### Question Description

In one of my lanes, I am trying to call a shell curl command to do something. The response of that curl is: {"app_url":"bs://05ab244fa8558ac74c12c435594c"}. Here is the command inside my lane:

#1
app_upload_response = sh("curl -u #{browserstackKey} -X POST 'https://api-cloud.browserstack.com/app-automate/upload' -F 'file=@../browserstack/builds/MyApp.ipa'")

#2
app_url = app_upload_response[:app_url]

The lane fails on #2, saying: "no implicit conversion of Symbol into Integer". I don't see where I am trying to convert a symbol to an integer? Please help.

**Comment by janpio** [comment]
What does `app_upload_response` look like after 1)?

**Comment by userException** [comment]
I was able to solve it via JSON. I was expecting the returned data from the CURL would be a hashmap but it was a plain json acceptable string ({"app_url":"bs://05ab244fa855812c435594c"})

After using JSON.parse(), I was able to convert it into a hash and then got the value of app_url key.
 
```
app_upload_response = `curl -u #{browserstackKey} -X POST 'https://api-cloud.browserstack.com/app-automate/xcuitest/test-suite' -F 'file=@../browserstack/derivedData/Build/Products/Debug-iphoneos/#{testSchemeName}.zip'`

jsonResponse = JSON.parse(app_upload_response)

browserstackTestURL = jsonResponse["test_url"]
```
