### ISSUE TITLE
gym uses provisioning profiles from match automatically

### ISSUE THREAD

**Issue by b-onc** [fastlane/fastlane#16327]
### Question Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

I'm using match and gym back to back, with more than 1 app ids:
```
  match(
    type: "adhoc",
    app_identifier: [
      id_one,
      id_two,
      id_three
    ],
    readonly: true
  )

  gym(
    project: "correct_project_path",
    scheme: "correct_scheme",
    configuration: "Debug",
    export_method: "ad-hoc",
    export_options: {
                      provisioningProfiles: { "id_one" => "match AdHoc id_one" }
                    }
  )
```

gym is disregarding what I pass in `export_options.provisioningProfiles` and uses what's coming from match: all 3 id's have mapping.

Is it possible to override what match passes, so id_two and id_three doesn't have matchings?

**Comment by b-onc** [comment]
There's this small part in the source code of `build_app`:
```ruby
if Actions.lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING]
          # Since Xcode 9 you need to explicitly provide the provisioning profile per app target
          # If the user is smart and uses match and gym together with fastlane, we can do all
          # the heavy lifting for them
          values[:export_options] ||= {}
          # It's not always a hash, because the user might have passed a string path to a ready plist file
          # If that's the case, we won't set the provisioning profiles
          # see https://github.com/fastlane/fastlane/issues/9490
          if values[:export_options].kind_of?(Hash)
```

Well, using a plist correctly overrides the options match passes, but this should be more apparent in documentation. For example, in https://docs.fastlane.tools/actions/gym/ there's the sentence:
> Note: If you use fastlane with match you don't need to provide those values manually.

This should be changed to:
> Note: If you use fastlane with match you don't need to provide those values manually, unless you pass a plist file into `export_options`

**Comment by janpio** [comment]
> This should be changed to:
> 
> > Note: If you use fastlane with match you don't need to provide those values manually, unless you pass a plist file into `export_options`

That sounds like a good idea. Can you make the change?

**Comment by b-onc** [comment]
@janpio I'd be glad. Will PR it shortly
