### ISSUE TITLE
Google Play Changes - App Content  / App Access - Test Users

### ISSUE THREAD

**Issue by esthor** [fastlane/fastlane#16324]
#### Motivation Behind Feature

If your app has a login or any restricted features, you need to now give Google a test user to login with. This is now like Apple's requirements (already covered by a feature of fastlane deploy's `review_information`)

![image](https://user-images.githubusercontent.com/11945900/79569577-d7ef2080-8085-11ea-9363-4e2a58dbd452.png)

#### Feature Description

Have a similar "review_information" feature in fastlane for Google's new requirements like we currently have for Apple. Here are the fields on Google Play:
![image](https://user-images.githubusercontent.com/11945900/79570530-98c1cf00-8087-11ea-8e1a-578f50eec30b.png)

a `review_information` folder for android metadata that could have a `demo_title.txt`, `demo_user.txt`, `demo_password.txt` and `demo_instructions.txt` and maybe a flag to turn it on or off, since answering this new question on Google Play is a requirement.

Not that I can see.

#### Alternatives or Workarounds

Manually enter it on Google Play.

Not that I am aware of.

**Comment by janpio** [comment]
Fastlane uses the https://developers.google.com/android-publisher and its ruby client. If this functionality is available there, it could potentially also be implemented in `supply`.

**Comment by esthor** [comment]
Thanks for the follow-up @janpio . I don't see it in the latest google play developer / android-publisher api. So, I guess we are SOL for the time-being. 🤷

**Comment by janpio** [comment]
Unfortunately the API is lacking quite often :/

**Comment by esthor** [comment]
Doesn't look like it's practically possible to integrate this with fastlane as Google doesn't currently expose an API for it. Gonna close the issue.

For those that arrive here from a search: It looks like you only have to set it once at an app level in Google Play, manually, not release level. So it stays there once set, for all releases (only really a problem if you need to update it for a bunch of apps regularly).
