### ISSUE TITLE
Pause a phased release using Spaceship

### ISSUE THREAD

**Issue by khose** [fastlane/fastlane#16325]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
How to pause a phased release using Spaceship.

#### Question Description
We would like to have control over the release once we have started rolling out our phased release.
For what we can read in the docs, this is possible using AppStoreConnect:

> While your app is in phased release, you can choose to pause the release for a total of 30 days, regardless of the number of pauses. If you remove your app from sale, your current phased release will stop and will not be available for that version again.

> You can pause your release for a total of 30 days. For example, if you pause your release for 10 days, and then resume, you will have 20 days left to pause the release a second time. If you resume a release that was previously paused, your phased release will pick up on the day it was left off when it was paused.

Looking at the source code, we couldn't find any place to control this.

``` ruby
  # Currently phased_release doesn't seem to have all the features enabled
  #
  #     => {"state"=>{"value"=>"NOT_STARTED", "isEditable"=>true, "isRequired"=>false, "errorKeys"=>nil},
  #        "startDate"=>nil,
  #        "lastPaused"=>nil,
  #        "pausedDuration"=>nil,
  #        "totalPauseDays"=>30,
  #        "currentDayNumber"=>nil,
  #        "dayPercentageMap"=>{"1"=>1, "2"=>2, "3"=>5, "4"=>10, "5"=>20, "6"=>50, "7"=>100},
  #        "isEnabled"=>true}
  #
```
There are some fields for that: `pausedDuration` and `totalPauseDays`, but looks like the client doesn't have the functionality right now. 

We would like to know if this is currently possible, what are the caveats around it. And if it's not in palce we can consider adding it to the repository.

Thanks in advance!

**Comment by janpio** [comment]
> And if it's not in palce we can consider adding it to the repository.

That sounds like a great idea. Please make sure to keep the existing code backwards compatible 👍

**Comment by khose** [comment]
Thanks @janpio . Let's see how we move this forward. Thanks!

**Comment by TragedyStar** [comment]
I want to know how to start phased release?

I found this method `Spaceship::TunesClient.release!`, but it seems not for phased release.

**Comment by TragedyStar** [comment]
> Thanks @janpio . Let's see how we move this forward. Thanks!

Any progress?
