### ISSUE TITLE
Download Fastlane in-app-purchase metadata

### ISSUE THREAD

**Issue by thejeff77** [fastlane/fastlane#16340]
### Question Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Downloading in app purchase metadata

#### Question Description

Hey there, I added a new version with in app purchases in app store connect and saved the new build. I then did:

> fastlane deliver download_metadata

And there aren't any in app purchases populated in the metadata folder from the download.

How do I populate in app purchases? Its hard to find any documentation on the app store metadata for fastlane. Perhaps its documented better somewhere on the spaceship github?

Thanks for any help!

@hjanuschka 
@KrauseFx

**Comment by max-ott** [comment]
As far as I know this is not supported by `deliver`. For more information on managing IAPs check out `spaceship`: https://github.com/fastlane/fastlane/pull/7834

Also, please don't ping members of the team directly.
