### ISSUE TITLE
AppStore new category names (Added early 2020) and matching MZGenre

### ISSUE THREAD

**Issue by exavi** [fastlane/fastlane#16355]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
What tool/action do you have a question about? deliver
Is this a question about documentation? yes & no
Is this a question about a third party plugin? no

#### Question Description
In February/March 2020 Apple announced some new categories for the iOS/iPadOS AppStore so they would be in line with the mac AppStore, one of these categories is named something along the lines of "Graphics & Design", as I've moved my app from another category to this one I faced the issue of not knowing which MZGenre it should be using since the newly introduced categories aren't listed on the docs, as a result, I have to keep changing categories from AppStore Connect on every release until this is updated.

Is there a way to query which values do the new categories map to?

I'm using this bit of the docs:

https://docs.fastlane.tools/actions/deliver/#available-categories

Apple's press release announcing them:

https://developer.apple.com/news/?id=02052020a

**Comment by max-ott** [comment]
You can always find the "latest" list of category strings directly on App Store Connect. Simply inspect the dropdown menu with your browser. The `value` field will include the correct string, just remove the part with `String:`

<img width="740" alt="Screenshot 2020-04-22 at 10 58 32" src="https://user-images.githubusercontent.com/6481790/79962441-5550d180-8488-11ea-9ac6-9c3b2bb31ce2.png">

**Comment by exavi** [comment]
I wasn't aware of this! Thank you very much!
