### ISSUE TITLE
supply apkNotificationMessageKeyNotSignedWithUploadCertificate even when signature of current store apk and upload apk match

### ISSUE THREAD

**Issue by ir2pid** [fastlane/fastlane#16361]
### New Issue Checklist

- [ x] Updated fastlane to the latest version
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Uploading using supply gives error
`[22:22:04]: Upload failed! Google Api Error: apkNotificationMessageKeyNotSignedWithUploadCertificate: APK has not been signed with the upload certificate. - APK has not been signed with the upload certificate.`

downloading a google play apk archive and running 
` keytool -list -printcert -jarfile "old.apk"`

gives the same SHA1, SHA256 and MD5 as running on the file which was being uploaded.

##### Command executed

```
upload_to_play_store(
          release_status: release_status,
          track: track,
          rollout: rollout,
          apk: apk,
          json_key: json_key,
          package_name: package_name,
          skip_upload_metadata: true,
          skip_upload_changelogs: true,
          skip_upload_images: true,
          skip_upload_screenshots: true,
        )
```
##### Complete output when running fastlane, including the stack trace and command used

```
[22:11:23]: ----------------------------------
[22:11:23]: --- Step: upload_to_play_store ---
[22:11:23]: ----------------------------------

+-------------------------+--------------------------------------------------------------------------------------+
|                                           Summary for supply 2.146.1                                           |
+-------------------------+--------------------------------------------------------------------------------------+
| release_status          | draft                                                                                |
| track                   | internal                                                                             |
| apk                     | /android/app-release  |
|                         | .apk                                                                                 |
| json_key                | /scripts/googleplay.json        |
| package_name            | com.xx.yy                                                             |
| skip_upload_metadata    | true                                                                                 |
| skip_upload_changelogs  | true                                                                                 |
| skip_upload_images      | true                                                                                 |
| skip_upload_screenshots | true                                                                                 |
| skip_upload_apk         | false                                                                                |
| skip_upload_aab         | false                                                                                |
| validate_only           | false                                                                                |
| check_superseded_tracks | false                                                                                |
| timeout                 | 300                                                                                  |
| deactivate_on_promote   | true                                                                                 |
+-------------------------+--------------------------------------------------------------------------------------+

[22:11:25]: Preparing apk at path '/android/app-release.apk' for upload...
[22:22:04]: Upload failed! Google Api Error: apkNotificationMessageKeyNotSignedWithUploadCertificate: APK has not been signed with the upload certificate. - APK has not been signed with the upload certificate.
[22:22:04]: --------------------------------------------
[22:22:04]: --- Step: Switch to android message lane ---
[22:22:04]: --------------------------------------------
[22:22:04]: Cruising over to lane 'android message' 🚖
[22:22:04]: -------------------
[22:22:04]: --- Step: teams ---
[22:22:04]: -------------------
[22:22:05]: Cruising back to lane 'android play_store' 🚘

+------+--------------------------------+-------------+
|                  fastlane summary                   |
+------+--------------------------------+-------------+
| Step | Action                         | Time (in s) |
+------+--------------------------------+-------------+
| 1    | opt_out_usage                  | 0           |
| 2    | default_platform               | 0           |
| 💥   | upload_to_play_store           | 640         |
| 4    | Switch to android message lane | 0           |
| 5    | teams                          | 1           |
+------+--------------------------------+-------------+

```
### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.18.0                          |
| Installation Source         | ~/.rvm/gems/ruby-2.5.1/bin/fastlane         |
| Host                        | Mac OS X 10.14.6 (18G2022)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.5.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.1a  20 Nov 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.3.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.146.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 2.1.2        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| gh_inspector              | 1.1.3        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| jwt                       | 2.1.0        |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.16.0       |
| unicode-display_width     | 1.7.0        |
| plist                     | 3.5.0        |
| addressable               | 2.7.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| excon                     | 0.73.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| fastimage                 | 2.1.7        |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| dotenv                    | 2.7.5        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| httpclient                | 2.8.3        |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| os                        | 1.1.0        |
| memoist                   | 0.16.2       |
| googleauth                | 0.12.0       |
| mini_mime                 | 1.0.2        |
| retriable                 | 3.1.2        |
| declarative-option        | 0.1.0        |
| declarative               | 0.0.10       |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| google-api-client         | 0.36.4       |
| digest-crc                | 0.5.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-env          | 1.3.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.0       |
| emoji_regex               | 1.0.1        |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.1.2        |
| aws-partitions            | 1.301.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.94.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.63.0       |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-04-22**
</details>

**Comment by max-ott** [comment]
Those error messages come directly from the API and as far as I know `supply` does not change anything with regards to the certificates.
