### ISSUE TITLE
Apple ID not being accepted by upload_to_testflight on CI

### ISSUE THREAD

**Issue by CodeWithOz** [fastlane/fastlane#16369]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I get this error when trying to upload to testflight using `upload_to_testflight` on GitHub Actions CI:
```
ERROR [2020-04-23 17:46:34.08]: Error setting value '***' for option 'apple_id'
ERROR [2020-04-23 17:46:34.08]: You passed invalid parameters to 'upload_to_testflight'.
ERROR [2020-04-23 17:46:34.08]: Check out the error below and available options by running `fastlane action upload_to_testflight`
ERROR [2020-04-23 17:46:34.08]: `apple_id` value is incorrect. The correct value should be taken from Apple ID property in the App Information section in App Store Connect.
```
The Apple ID is correct. I've followed [these instructions](https://docs.fastlane.tools/actions/upload_to_testflight/#use-an-application-specific-password-to-upload) to supply both the `apple_id` and `skip_waiting_for_build_processing` and the app-specific password environment variable, but the error persists.

##### Command executed

```
bundle exec fastlane ios beta_gh_actions
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
INFO [2020-04-23 17:46:33.89]: ▸ ** EXPORT SUCCEEDED **
ERROR [2020-04-23 17:46:34.08]: Error setting value '***' for option 'apple_id'
ERROR [2020-04-23 17:46:34.08]: You passed invalid parameters to 'upload_to_testflight'.
ERROR [2020-04-23 17:46:34.08]: Check out the error below and available options by running `fastlane action upload_to_testflight`
WARN [2020-04-23 17:46:34.08]: Lane Context:
ERROR [2020-04-23 17:46:34.08]: `apple_id` value is incorrect. The correct value should be taken from Apple ID property in the App Information section in App Store Connect.

+------+---------------------------------+-------------+
|                   fastlane summary                   |
+------+---------------------------------+-------------+
| Step | Action                          | Time (in s) |
+------+---------------------------------+-------------+
| 1    | create_keychain                 | 0           |
| 2    | is_ci                           | 0           |
| 3    | match                           | 1           |
| 4    | increment_build_number_in_plist | 17          |
| 5    | get_build_number_from_plist     | 8           |
| 6    | cordova                         | 116         |
+------+---------------------------------+-------------+

DEBUG [2020-04-23 17:46:34.23]: All plugins are up to date
ERROR [2020-04-23 17:46:34.23]: fastlane finished with errors
DEBUG [2020-04-23 17:46:34.23]: All plugins are up to date
bundler: failed to load command: fastlane (/usr/local/lib/ruby/gems/2.6.0/bin/fastlane)
FastlaneCore::Interface::FastlaneError: [!] `apple_id` value is incorrect. The correct value should be taken from Apple ID property in the App Information section in App Store Connect.
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.146.1/fastlane_core/lib/fastlane_core/configuration/config_item.rb:224:in `rescue in valid?'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.146.1/fastlane_core/lib/fastlane_core/configuration/config_item.rb:220:in `valid?'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.146.1/fastlane_core/lib/fastlane_core/configuration/config_item.rb:182:in `verify!'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.146.1/fastlane_core/lib/fastlane_core/configuration/configuration.rb:87:in `block in verify_value_exists'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.146.1/fastlane_core/lib/fastlane_core/configuration/configuration.rb:82:in `each'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.146.1/fastlane_core/lib/fastlane_core/configuration/configuration.rb:82:in `verify_value_exists'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.146.1/fastlane_core/lib/fastlane_core/configuration/configuration.rb:66:in `initialize'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.146.1/fastlane_core/lib/fastlane_core/configuration/configuration.rb:36:in `new'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.146.1/fastlane_core/lib/fastlane_core/configuration/configuration.rb:36:in `create'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/configuration_helper.rb:8:in `parse'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/runner.rb:237:in `block in execute_action'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:82:in `block (2 levels) in parsing_binding'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.146.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.146.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.146.1/bin/fastlane:23:in `<top (required)>'
  /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `load'
  /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `<top (required)>'
##[error]Process completed with exit code 1.
 </pre>
</details>

### Environment

<details>
  <pre> [18:31:58]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[18:32:04]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                              |
| --------------------------- | -------------------------------------------------- |
| OS                          | 10.15.4                                            |
| Ruby                        | 2.6.5                                              |
| Bundler?                    | false                                              |
| Git                         | git version 2.26.0                                 |
| Installation Source         | /usr/local/lib/ruby/gems/2.6.0/bin/fastlane        |
| Host                        | Mac OS X 10.15.4 (19E266)                          |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.6/2.6.5/lib               |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                        |
| Is contained                | false                                              |
| Is homebrew                 | false                                              |
| Is installed via Fabric.app | false                                              |
| Xcode Path                  | /Applications/Xcode_11.3.1.app/Contents/Developer/ |
| Xcode Version               | 11.3.1                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
platform :ios do
  desc "Manage ios builds"

  lane :simulate do
    match(type: "development")
    cordova(
      type: 'development',
      release: false,
      device: false,
      build_number: get_build_number_from_plist(
        xcodeproj: './platforms/ios/<app>.xcodeproj'
      )
    )
    sh('cordova run --emulator --noprepare --nobuild --target="iPhone-6, 12.1" --debug')
  end

  lane :beta do
    match(type: "appstore")
    increment_build_number_in_plist(
      xcodeproj: './platforms/ios/<app>.xcodeproj'
    )
    cordova(
      platform: 'ios',
      build_number: get_build_number_from_plist(
        xcodeproj: './platforms/ios/<app>.xcodeproj'
      )
    )
    changelog = File.read('../CHANGELOG.md')
    upload_to_testflight(
      ipa: "./platforms/ios/build/device/<app>.ipa",
      skip_waiting_for_build_processing: true,
      changelog: changelog
    )
  end

  # Build with Bitrise, match is handled on Bitrise
  lane :beta_bitrise do
    increment_build_number_in_plist(
      xcodeproj: './platforms/ios/<app>.xcodeproj'
    )
    cordova(
      platform: 'ios',
      build_number: get_build_number_from_plist(
        xcodeproj: './platforms/ios/<app>.xcodeproj'
      )
    )
    changelog = File.read('../CHANGELOG.md')
    upload_to_testflight(
      ipa: "./platforms/ios/build/device/<app>.ipa",
      skip_waiting_for_build_processing: true,
      changelog: changelog
    )
  end

  # Build with GitHub actions
  # see https://stackoverflow.com/questions/59111746/github-actions-fastlane-match-cant-decrypt-repo
  lane :beta_gh_actions do
    create_keychain(
      name: "temp",
      password: "temp",
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )
    match(
      type: "appstore",
      readonly: is_ci,
      keychain_name: "temp",
      keychain_password: "temp"
    )
    increment_build_number_in_plist(
      xcodeproj: './platforms/ios/<app>.xcodeproj'
    )
    cordova(
      platform: 'ios',
      build_number: get_build_number_from_plist(
        xcodeproj: './platforms/ios/<app>.xcodeproj'
      )
    )
    upload_to_testflight(
      ipa: "./platforms/ios/build/device/<app>.ipa",
      skip_waiting_for_build_processing: true,
    )
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# View this URL if you are a part of multiple teams in the Apple Developer Portal
# https://docs.fastlane.tools/advanced/Appfile/

app_identifier "com.app.app"

# TODO: Enter your Apple Developer Portal username
apple_id "***"

team_id "<TEAM_ID>"
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.146.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-cordova    | 2.2.1   | ✅ Up-To-Date  |
| fastlane-plugin-versioning | 0.4.3   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version      |
| -------------------------- | ------------ |
| did_you_mean               | 1.3.0        |
| slack-notifier             | 2.3.2        |
| rouge                      | 2.0.7        |
| xcpretty                   | 0.3.0        |
| terminal-notifier          | 2.0.0        |
| CFPropertyList             | 3.0.2        |
| public_suffix              | 2.0.5        |
| addressable                | 2.7.0        |
| multipart-post             | 2.0.0        |
| word_wrap                  | 1.0.0        |
| tty-screen                 | 0.7.1        |
| tty-cursor                 | 0.7.1        |
| tty-spinner                | 0.9.3        |
| babosa                     | 1.0.3        |
| colored                    | 1.2          |
| highline                   | 1.7.10       |
| commander-fastlane         | 4.4.6        |
| faraday                    | 0.17.3       |
| unf                        | 0.1.4        |
| domain_name                | 0.5.20190701 |
| http-cookie                | 1.0.3        |
| faraday-cookie_jar         | 0.0.6        |
| faraday_middleware         | 0.13.1       |
| fastimage                  | 2.1.7        |
| gh_inspector               | 1.1.3        |
| mini_magick                | 4.10.1       |
| multi_xml                  | 0.6.0        |
| rubyzip                    | 1.3.0        |
| security                   | 0.1.3        |
| xcpretty-travis-formatter  | 1.0.0        |
| dotenv                     | 2.7.5        |
| naturally                  | 2.2.0        |
| simctl                     | 1.6.8        |
| jwt                        | 2.1.0        |
| uber                       | 0.1.0        |
| declarative                | 0.0.10       |
| declarative-option         | 0.1.0        |
| representable              | 3.0.4        |
| retriable                  | 3.1.2        |
| mini_mime                  | 1.0.2        |
| httpclient                 | 2.8.3        |
| google-api-client          | 0.36.4       |
| emoji_regex                | 1.0.1        |
| nanaimo                    | 0.2.6        |
| colored2                   | 3.1.2        |
| claide                     | 1.0.3        |
| atomos                     | 0.1.3        |
| xcodeproj                  | 1.16.0       |
| unicode-display_width      | 1.7.0        |
| terminal-table             | 1.8.0        |
| plist                      | 3.5.0        |
| excon                      | 0.73.0       |
| unf_ext                    | 0.0.7.7      |
| json                       | 2.3.0        |
| bundler                    | 2.1.4        |
| multi_json                 | 1.14.1       |
| signet                     | 0.14.0       |
| os                         | 1.1.0        |
| memoist                    | 0.16.2       |
| googleauth                 | 0.12.0       |
| digest-crc                 | 0.5.1        |
| google-cloud-errors        | 1.0.0        |
| google-cloud-env           | 1.3.1        |
| google-cloud-core          | 1.5.0        |
| google-cloud-storage       | 1.26.0       |
| aws-eventstream            | 1.1.0        |
| aws-sigv4                  | 1.1.2        |
| aws-partitions             | 1.301.0      |
| jmespath                   | 1.4.0        |
| aws-sdk-core               | 3.94.0       |
| aws-sdk-kms                | 1.30.0       |
| aws-sdk-s3                 | 1.63.0       |
| mini_portile2              | 2.1.0        |
| nokogiri                   | 1.6.8.1      |
| fastlane-plugin-cordova    | 2.2.1        |
| fastlane-plugin-versioning | 0.4.3        |
</details>

*generated on:* **2020-04-23**
</details> </pre>
</details>

**Comment by Katsz** [comment]
Make sure you’re using ITC team id (numbers only, ie 110110011), not developer portal id (letters and numbers ie 1AAA1AAA1).

**Comment by CodeWithOz** [comment]
@Katsz thanks for the response. I'm not sure which value you're referring to. Yes I see the team ID which is numbers and letters, but I don't see another numbers-only team ID in App Store Connect. The only other thing I see is another **Apple ID** which is numbers-only for the specific app i.e. in App Store Connect > My Apps > (app name) > App Information (under the **App Store** tab). This is the same place where it shows **Bundle ID**, **SKU**, etc. Is that the ID you're referring to? Also, you called it a team ID - the problem I'm having appears to be with the actual Apple ID (email address). Are you saying I should pass the correct Apple ID (email) as the `apple_id` but instead change the value of `team_id` to this numbers-only value?

**Comment by Katsz** [comment]
AFAIK Apple isn’t  displaying ITC team id anywhere. However you can see all your team by running 
```ruby
$ irb
irb> require "fastlane"
irb> require "spaceship"
irb> Spaceship::Tunes.login
irb> Spaceship::Tunes.select_team
```

Or you can add few handy functions to your Fastfile if you will need it again

```ruby
def get_itc_teams(username: USERNAME)
    Spaceship::Tunes.login(username)
    itc_teams = Spaceship::Tunes.client.teams
    return itc_teams.map { |team| team["contentProvider"] }
end

def get_dev_teams(username: USERNAME, only_enterprise: nil)
    Spaceship::Portal.login(username)
    dev_teams = Spaceship::Portal.client.teams
    dev_teams = dev_teams.filter{ |x| (x["type"] != "In-House") ^ only_enterprise } unless only_enterprise.nil?
    return dev_teams
end
```

**Comment by demissieef** [comment]
> @Katsz thanks for the response. I'm not sure which value you're referring to. Yes I see the team ID which is numbers and letters, but I don't see another numbers-only team ID in App Store Connect. The only other thing I see is another **Apple ID** which is numbers-only for the specific app i.e. in App Store Connect > My Apps > (app name) > App Information (under the **App Store** tab). This is the same place where it shows **Bundle ID**, **SKU**, etc. Is that the ID you're referring to? Also, you called it a team ID - the problem I'm having appears to be with the actual Apple ID (email address). Are you saying I should pass the correct Apple ID (email) as the `apple_id` but instead change the value of `team_id` to this numbers-only value?

Thank you very much for your hard work.
