### ISSUE TITLE
Fastlane not building cocoapods

### ISSUE THREAD

**Issue by EricWiener** [fastlane/fastlane#16374]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

My app has been working successfully with Fastlane. However, between the last build and the current build, I am now unable to compile to release to Testflight. I am getting the error:
```
fatal error: module map file '/Users/xxx/Library/Developer/Xcode/DerivedData/MyApp-dquwvaaenvelplfebdxfllgbnecd/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/BuildProductsPath/Release-iphoneos/IceCream/IceCream.modulemap' not found
```

However, I can still compile and build a release bundle using XCode. I have tried clearing my pod cache, clearing derived data, clearing the build data, and removing my entire Podfolder. I am not sure why this issue is occurring and would greatly appreciate some feedback.

##### Command executed

```
fastlane ios beta
```
which failed on
```
build_app(workspace: "MyApp.xcworkspace",
      scheme: "MyApp",
      configuration: "Release",
    )
```

Most of my Pods are installed with local paths, but this pod is installed just with:
```
pod 'IceCream'
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
INFO [2020-04-24 09:59:34.46]: ▸ ❌  fatal error: module map file '/Users/xxx/Library/Developer/Xcode/DerivedData/MyApp-dquwvaaenvelplfebdxfllgbnecd/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/BuildProductsPath/Release-iphoneos/IceCream/IceCream.modulemap' not found

The following build commands failed:
INFO [2020-04-24 09:59:34.47]: ▸ 	CompileC /Users/xxx/Library/Developer/Xcode/DerivedData/MyApp-dquwvaaenvelplfebdxfllgbnecd/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/glog.build/Objects-normal/armv7/vlog_is_on.o /Users/xxx/repositories/MyApp/ios/Pods/glog/src/vlog_is_on.cc normal armv7 c++ com.apple.compilers.llvm.clang.1_0.compiler
INFO [2020-04-24 09:59:34.47]: ▸ 	CompileC /Users/xxx/Library/Developer/Xcode/DerivedData/MyApp-dquwvaaenvelplfebdxfllgbnecd/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/glog.build/Objects-normal/armv7/utilities.o /Users/xxx/repositories/MyApp/ios/Pods/glog/src/utilities.cc normal armv7 c++ com.apple.compilers.llvm.clang.1_0.compiler
INFO [2020-04-24 09:59:34.47]: ▸ 	CompileC /Users/xxx/Library/Developer/Xcode/DerivedData/MyApp-dquwvaaenvelplfebdxfllgbnecd/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/glog.build/Objects-normal/armv7/symbolize.o /Users/xxx/repositories/MyApp/ios/Pods/glog/src/symbolize.cc normal armv7 c++ com.apple.compilers.llvm.clang.1_0.compiler
INFO [2020-04-24 09:59:34.47]: ▸ 	CompileC /Users/xxx/Library/Developer/Xcode/DerivedData/MyApp-dquwvaaenvelplfebdxfllgbnecd/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/glog.build/Objects-normal/armv7/signalhandler.o /Users/xxx/repositories/MyApp/ios/Pods/glog/src/signalhandler.cc normal armv7 c++ com.apple.compilers.llvm.clang.1_0.compiler
INFO [2020-04-24 09:59:34.47]: ▸ 	CompileC /Users/xxx/Library/Developer/Xcode/DerivedData/MyApp-dquwvaaenvelplfebdxfllgbnecd/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/glog.build/Objects-normal/armv7/logging.o /Users/xxx/repositories/MyApp/ios/Pods/glog/src/logging.cc normal armv7 c++ com.apple.compilers.llvm.clang.1_0.compiler
INFO [2020-04-24 09:59:34.47]: ▸ 	CompileC /Users/xxx/Library/Developer/Xcode/DerivedData/MyApp-dquwvaaenvelplfebdxfllgbnecd/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/glog.build/Objects-normal/armv7/demangle.o /Users/xxx/repositories/MyApp/ios/Pods/glog/src/demangle.cc normal armv7 c++ com.apple.compilers.llvm.clang.1_0.compiler
INFO [2020-04-24 09:59:34.47]: ▸ 	CompileC /Users/xxx/Library/Developer/Xcode/DerivedData/MyApp-dquwvaaenvelplfebdxfllgbnecd/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/glog.build/Objects-normal/arm64/vlog_is_on.o /Users/xxx/repositories/MyApp/ios/Pods/glog/src/vlog_is_on.cc normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler
INFO [2020-04-24 09:59:34.47]: ▸ 	CompileC /Users/xxx/Library/Developer/Xcode/DerivedData/MyApp-dquwvaaenvelplfebdxfllgbnecd/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/glog.build/Objects-normal/arm64/utilities.o /Users/xxx/repositories/MyApp/ios/Pods/glog/src/utilities.cc normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler
INFO [2020-04-24 09:59:34.47]: ▸ 	CompileC /Users/xxx/Library/Developer/Xcode/DerivedData/MyApp-dquwvaaenvelplfebdxfllgbnecd/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/glog.build/Objects-normal/arm64/symbolize.o /Users/xxx/repositories/MyApp/ios/Pods/glog/src/symbolize.cc normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler
INFO [2020-04-24 09:59:34.47]: ▸ 	CompileC /Users/xxx/Library/Developer/Xcode/DerivedData/MyApp-dquwvaaenvelplfebdxfllgbnecd/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/glog.build/Objects-normal/arm64/signalhandler.o /Users/xxx/repositories/MyApp/ios/Pods/glog/src/signalhandler.cc normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler
INFO [2020-04-24 09:59:34.47]: ▸ 	CompileC /Users/xxx/Library/Developer/Xcode/DerivedData/MyApp-dquwvaaenvelplfebdxfllgbnecd/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/glog.build/Objects-normal/arm64/raw_logging.o /Users/xxx/repositories/MyApp/ios/Pods/glog/src/raw_logging.cc normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler
INFO [2020-04-24 09:59:34.47]: ▸ 	CompileC /Users/xxx/Library/Developer/Xcode/DerivedData/MyApp-dquwvaaenvelplfebdxfllgbnecd/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/glog.build/Objects-normal/arm64/demangle.o /Users/xxx/repositories/MyApp/ios/Pods/glog/src/demangle.cc normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.4                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.2 (Apple Git-127)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.4 (19E266)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.4.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    match(app_identifier: ['xxx', 'xxx'],
    type: "appstore",)
  end

  desc 'Increment build number'
  lane :bump_build_version do
    increment_build_number(xcodeproj: 'MyApp.xcodeproj')
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    changelog = prompt(
      text: "Changelog: ",
      multi_line_end_keyword: "END"
    )
    bump_build_version
    build_app(workspace: "MyApp.xcworkspace",
      scheme: "MyApp",
      configuration: "Release",
    )
    upload_to_testflight(
      // removed
    )
  end

  desc "Push an existing beta to production"
  lane :promote_beta do
    changelog = prompt(
      text: "Changelog: ",
      multi_line_end_keyword: "END"
    )
    deliver(
      submit_for_review: true,
      force: true, # Skip HTMl report verification
      skip_screenshots: true,
      skip_binary_upload: true,
      submit_for_review: true,
      # Comes from https://github.com/fastlane/fastlane/issues/5542#issuecomment-254201994
      submission_information: {
        // removed
      }
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("xxx") # The bundle identifier of your app
apple_id("xxx") # Your Apple email address

itc_team_id("xxx") # App Store Connect Team ID
team_id("xxx") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.146.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.73.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.0        |
| googleauth                | 0.11.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.5.1        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.294.0      |
| aws-eventstream           | 1.0.3        |
| aws-sigv4                 | 1.1.1        |
| aws-sdk-core              | 3.92.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.61.2       |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.15.0       |
| json                      | 2.3.0        |
| uber                      | 0.1.0        |
| retriable                 | 3.1.2        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-04-24**
</details>

**Comment by EricWiener** [comment]
To add to the above information, the pod IceCream does not specify a module map, but when compiling with XCode this isn't an issue. It is only an issue when using Fastlane

**Comment by EricWiener** [comment]
This is still an issue

**Comment by minuscorp** [comment]
Could you upload a reproducible project in order to us to debug the issue?
