### ISSUE TITLE
Supports `Developer ID Application (With Kext)`cert for match action

### ISSUE THREAD

**Issue by langyanduan** [fastlane/fastlane#16376]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Command executed

```
bundle exec fastlane match
```

*Matchfile*:

```
git_url("git@github.com:xxx/xxx.git")
git_branch("xxx")

storage_mode("git")

username("xxx@gmail.com")
type("developer_id")
app_identifier(["com.abc.www"])
platform("macos")
```

##### Complete output when running fastlane, including the stack trace and command used

```
...

[00:48:04]: Couldn't find a valid code signing identity for developer_id_application... creating one for you now

+----------------------+--------------------------------------------------+
|                        Summary for cert 2.146.1                         |
+----------------------+--------------------------------------------------+
| development          | false                                            |
| type                 | developer_id_application                         |
| generate_apple_certs | true                                             |
| force                | true                                             |
| username             | xxxxxxxxxxx@gmail.com                            |
| keychain_path        | /Users/xxxxx/Library/Keychains/login.keychain-db |
| platform             | ios                                              |
+----------------------+--------------------------------------------------+

[00:48:04]: Starting login with user 'xxx@gmail.com'
[00:48:10]: Successfully logged in

[!] You do not have permission to create this certificate. Only Team Admins can create Distribution certificates
 🔍 See https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/ManagingYourTeam/ManagingYourTeam.html for more information.
```

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                    |
| --------------------------- | -------------------------------------------------------- |
| OS                          | 10.15.2                                                  |
| Ruby                        | 2.6.3                                                    |
| Bundler?                    | true                                                     |
| Git                         | git version 2.24.1                                       |
| Installation Source         | ~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/bin/fastlane |
| Host                        | Mac OS X 10.15.2 (19C57)                                 |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.3/lib                              |
| OpenSSL Version             | OpenSSL 1.0.2s  28 May 2019                              |
| Is contained                | false                                                    |
| Is homebrew                 | false                                                    |
| Is installed via Fabric.app | false                                                    |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/              |
| Xcode Version               | 11.4.1                                                   |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.146.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 2.1.4        |
| psych                     | 3.1.0        |
| stringio                  | 0.0.2        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| rake                      | 11.3.0       |
| CFPropertyList            | 3.0.2        |
| concurrent-ruby           | 1.1.6        |
| i18n                      | 0.9.5        |
| minitest                  | 5.14.0       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.7        |
| activesupport             | 4.2.11.1     |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| httpclient                | 2.8.3        |
| json                      | 2.3.0        |
| algoliasearch             | 1.27.1       |
| ast                       | 2.4.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.302.0      |
| aws-sigv4                 | 1.1.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.94.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.63.0       |
| babosa                    | 1.0.3        |
| debug_inspector           | 0.0.3        |
| binding_of_caller         | 0.8.0        |
| builder                   | 3.2.4        |
| byebug                    | 11.1.3       |
| claide                    | 1.0.3        |
| climate_control           | 0.2.0        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| netrc                     | 0.11.0       |
| ffi                       | 1.12.2       |
| ethon                     | 0.12.0       |
| typhoeus                  | 1.3.1        |
| cocoapods-core            | 1.9.1        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.3.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| cocoapods-trunk           | 1.4.1        |
| cocoapods-try             | 1.2.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.16.0       |
| cocoapods                 | 1.9.1        |
| coderay                   | 1.1.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| docile                    | 1.3.2        |
| simplecov-html            | 0.10.2       |
| simplecov                 | 0.16.1       |
| sync                      | 0.5.0        |
| tins                      | 1.24.1       |
| term-ansicolor            | 1.7.1        |
| thor                      | 1.0.1        |
| coveralls                 | 0.8.23       |
| safe_yaml                 | 1.0.5        |
| crack                     | 0.4.3        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| diff-lcs                  | 1.3          |
| digest-crc                | 0.5.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.73.0       |
| fakefs                    | 0.8.1        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.17.3       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.1.0        |
| signet                    | 0.14.0       |
| googleauth                | 0.12.0       |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.0       |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| hashdiff                  | 0.3.9        |
| http-accept               | 1.7.0        |
| interception              | 0.5          |
| method_source             | 1.0.0        |
| mime-types-data           | 3.2019.1009  |
| mime-types                | 3.3.1        |
| parallel                  | 1.19.1       |
| parser                    | 2.7.1.1      |
| powerpack                 | 0.1.2        |
| pry                       | 0.13.1       |
| pry-byebug                | 3.9.0        |
| pry-rescue                | 1.5.0        |
| pry-stack_explorer        | 0.4.9.3      |
| rack                      | 1.6.13       |
| rack-protection           | 1.5.5        |
| rainbow                   | 2.2.2        |
| rb-readline               | 0.5.5        |
| rest-client               | 2.1.0        |
| rspec-support             | 3.5.0        |
| rspec-core                | 3.5.4        |
| rspec-expectations        | 3.5.0        |
| rspec-mocks               | 3.5.0        |
| rspec                     | 3.5.0        |
| rspec_junit_formatter     | 0.2.3        |
| ruby-progressbar          | 1.10.1       |
| rubocop                   | 0.49.1       |
| rubocop-require_tools     | 0.1.2        |
| tilt                      | 2.0.10       |
| sinatra                   | 1.4.8        |
| webmock                   | 2.3.2        |
| xcov                      | 1.4.3        |
| yard                      | 0.9.24       |
</details>

*generated on:* **2020-04-25**
</details> </pre>
</details>

---

I found some relevant code, but the specific functionality doesn't seem to be implemented.

`CertificateType` for `Developer ID Application (With Kext)`
> https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/connect_api/models/certificate.rb#L32

`MAC_CERTIFICATE_TYPE_IDS` for `Developer ID Application (With Kext)`
> https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/portal/certificate.rb#L198

Thank you so much for the work you do  @joshdholtz

**Comment by joshdholtz** [comment]
Hey! So _match_ does support the Developer ID Application but I’m not sure what the “Kext” part actually means 🤔 

I do see in your logs that it doesn’t look like you have permission to create certs 😬

```
You do not have permission to create this certificate. Only Team Admins can create Distribution certificates
```

I wonder if that is the issue?

**Comment by langyanduan** [comment]
I requested a kext signature through https://developer.apple.com/contact/kext/.

So now I can't create developer-id-application certificate, I can only create developer-id-application-with-kext certificate.

![image](https://user-images.githubusercontent.com/2404894/80271572-ea0b3780-86f3-11ea-9a08-b5afd6b21eb5.png)

---
Here is the relevant HTML code

```
<li class=""><span><input type="radio" name="certificate-type" id="DIVN2GW3XT"></span>
    <label for="DIVN2GW3XT">
        <div>
            <h5>Developer ID Application and Kernel Extension</h5></div>
        <p>This certificate is used to code sign your app or kernel extension for distribution outside of the Mac App Store.</p>
        <div><em></em></div>
    </label>
</li>
```

`MAC_CERTIFICATE_TYPE_IDS` already exists in the code:
> https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/portal/certificate.rb#L198

**Comment by joshdholtz** [comment]
OHHHHHHHHHHHH... 🤯 

That screenshot helps a lot 😊 I will add this!
