### ISSUE TITLE
Fastlane Swift: uploadToTestflight username should not be required

### ISSUE THREAD

**Issue by zackdotcomputer** [fastlane/fastlane#16389]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Fastlane swift's implementation of `uploadToTestflight` currently requires the `username` password to be defined. However, the underlying `upload_to_testflight` command does not - it supports caching auth via spaceauth or passing it via ENV variables. We should remove this requirement to feature-match the ruby implementation.

##### Command executed
```
uploadToTestflight()
```

##### Complete output when running fastlane, including the stack trace and command used
It fails to compile with the error: 

```
Fastfile.swift:26:32: missing argument for parameter 'username' in call
            uploadToTestflight()
                               ^
```

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.4                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.26.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.4 (19E287)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.4.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

```ruby
// This file contains the fastlane.tools configuration
// You can find the documentation at https://docs.fastlane.tools
//
// For a list of all available actions, check out
//
//     https://docs.fastlane.tools/actions
//

import Foundation

enum Scheme: String {
    case dev = "XXX Development"
    case preprod = "XXX PreProd"
}

class Fastfile: LaneFile {
    // MARK: - Helper functions

    private func doBuild(scheme: Scheme, uploadToTestflight doUpload: Bool = false) {
        incrementBuildNumber(buildNumber: buildNumber(), xcodeproj: "XXX.xcodeproj")
        buildApp(workspace: "XXX.xcworkspace", scheme: scheme.rawValue)
        if (doUpload) {
            uploadToTestflight()
        }
    }

    /**
     * @returns A build number of the format YYYYMMddTTT where TTT is the thousandths of the day elapsed - ranging from 0 to 999 - as three digits.
     *   Thus this method will return strings like "20200427842" for 8:10pm UTC on April 27th, 2020. These have the advantage of being monotonically
     *   and consistently increasing so that we can coordinate increasing build times no matter where in the world we are.
     */
    func buildNumber() -> String {
        let now = Date.init()

        let formatter = DateFormatter.init()
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.timeZone = TimeZone(secondsFromGMT: 0)
        formatter.timeStyle = .none
        formatter.dateFormat = "YYYYMMdd"
        let dayPortion = formatter.string(from: now)

        formatter.dateFormat = "HH mm SS"
        let timeComponents = formatter.string(from: now).split(separator: " ").map({ Int($0)! })
        let secondsElapsed = (((timeComponents[0] * 60) + timeComponents[1]) * 60) + timeComponents[2]
        let shardOfDay = Double(secondsElapsed) / (24 * 60 * 60)

        let numberFormatter = NumberFormatter.init()
        numberFormatter.maximumFractionDigits = 0
        numberFormatter.maximumIntegerDigits = 3
        numberFormatter.minimumIntegerDigits = 3
        let daySlice = numberFormatter.string(from: NSNumber(value: 1000 * shardOfDay))!

        return dayPortion + daySlice
    }

    // MARK: - Lanes

    func buildnumberLane() {
        println(message: buildNumber())
    }

	func devLane() {
        desc("Push a new dev build to TestFlight")
        doBuild(scheme: .dev, uploadToTestflight: false)
	}
}

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.146.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| bundler                   | 2.1.4        |
| CFPropertyList            | 3.0.2        |
| concurrent-ruby           | 1.1.6        |
| i18n                      | 0.9.5        |
| minitest                  | 5.14.0       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.7        |
| activesupport             | 4.2.11.1     |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| httpclient                | 2.8.3        |
| json                      | 2.3.0        |
| algoliasearch             | 1.27.1       |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.303.0      |
| aws-sigv4                 | 1.1.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.94.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.63.0       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| netrc                     | 0.11.0       |
| ffi                       | 1.12.2       |
| ethon                     | 0.12.0       |
| typhoeus                  | 1.3.1        |
| cocoapods-core            | 1.9.1        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.3.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| cocoapods-trunk           | 1.4.1        |
| cocoapods-try             | 1.2.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.16.0       |
| cocoapods                 | 1.9.1        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.5.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.73.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.17.3       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.1.0        |
| signet                    | 0.14.0       |
| googleauth                | 0.12.0       |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.0       |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2020-04-27**
</details></pre>
</details>

**Comment by joshdholtz** [comment]
It looks like Fastlane.swift doesn’t allow passing of ENV to any tools or actions. This actually requires some deeper thought and maybe a redesign on how the Fastlane.swift is bridged to Ruby 😬
