### ISSUE TITLE
Fastlane Spaceauth session only lasting 8 hours

### ISSUE THREAD

**Issue by DTX-Elliot** [fastlane/fastlane#16384]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
 Fastlane Spaceauth session expiring in 8 hours, not 30 days.

#### Question Description
Hi All, I have a question about Fastlane's Spaceauth integration with Azure Devops and the Apple App store release task. I followed the docs and various support pages to install fastlane on my Mac and run 
```
fastlane spaceauth -u <my-email-address>
```
This gives me the session which I paste into the fastlane session parameter of my Apple App store service connection on Azure Devops. This works as intended, however if I run a build 8 hours later, the build on the CI machine fails because Fastlane wants me to input my 2FA code since the session has expired. I found a few Github issue pages describing this issue and it seemed to get resolved by including the "DES" cookie for "idmsa.apple.com" in the session. I can see I have this cookie in the session yet it still only lasts for 8 hours. Is this expected and its a problem on Apple's end or am I doing something wrong? Thanks in advance.

**Comment by max-ott** [comment]
Please check out https://docs.fastlane.tools/best-practices/continuous-integration/ 

There are certain limitations from Apple's side.

**Comment by etienneyoufeel** [comment]
I have the same issue since couples days. (before never happen) I need to refresh my cookie every day. Can you re-open this issue ?

**Comment by Kiruel** [comment]
I have the same issue since couples days. (before never happen) I need to refresh my cookie every day. Can you re-open this issue ?
