### ISSUE TITLE
[Spaceship] App.get_builds limit parameter not respected

### ISSUE THREAD

**Issue by Steven0351** [fastlane/fastlane#16398]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Given an instance of `Spaceship::ConnectAPI::App`, if you call `get_builds(limit: 1)`, the limit is not respected and all the builds are enumerated.

Example:
```ruby
app = Spaceship::ConnectAPI::App.find("com.example")
one_build = app.get_builds(limit: 1)
# one_build.size equals the number of all available builds on App Store Connect
```
The code at fault appears to be [here](https://github.com/fastlane/fastlane/blob/a4b6c29681cd2b4b1c39109dec6a365b529cad72/spaceship/lib/spaceship/connect_api/models/app.rb#L79)
```ruby
resps = Spaceship::ConnectAPI.get_builds(filter: filter, includes: includes, limit: limit, sort: sort).all_pages
```
The limit parameter simply reduces the size of the page, _but_ `all_pages` is called regardless of a limit being defined or not. If this is the desired behavior, it seems to defeat the purpose of having a limit parameter defined on `App.get_builds` at all. Using the limit parameter in this context heavily impacts performance due to the increased number of network requests required to enumerate all the builds. For example, my organization has about 255 builds for a given application and by calling `app.get_builds(limit: 1)` 255 individual network requests are made. I think it's reasonable to expect that giving a limit would only yield the number of results defined at this level of the Spaceship API.

This can be worked around by calling into `Spaceship::ConnectAPI.get_builds` directly, but I think it makes sense to enable the same behavior on `App.get_builds` as well.

I would be willing to do the implementation work itself, but I wanted to open up an issue first since this kind of change warrants a discussion on the direction to be taken (imo).

##### Command executed

N/A, this is using `Spaceship` directly in code

##### Complete output when running fastlane, including the stack trace and command used

N/A, this is using `Spaceship` directly in code

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.4                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.1 (Apple Git-126)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.4 (19E287)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode-11.4.app/Contents/Developer/               |
| Xcode Version               | 11.4                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.146.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| gh_inspector              | 1.1.3        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| faraday                   | 0.17.3       |
| signet                    | 0.14.0       |
| googleauth                | 0.12.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.297.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.1.1        |
| aws-sdk-core              | 3.94.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.61.2       |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.16.0       |
| unicode-display_width     | 1.7.0        |
| addressable               | 2.7.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| excon                     | 0.73.0       |
| unf_ext                   | 0.0.7.7      |
| fastimage                 | 2.1.7        |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| dotenv                    | 2.7.5        |
| bundler                   | 2.0.2        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| multi_json                | 1.14.1       |
| memoist                   | 0.16.2       |
| os                        | 1.1.0        |
| digest-crc                | 0.5.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-env          | 1.3.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.0       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| ox                        | 2.13.2       |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-04-28**
</details> </pre>
</details>

**Comment by max-ott** [comment]
Thanks for the catch! I agree that `limit` should work similar to `filter` and help with trimming down the responses. I don't think @joshdholtz did this on purpose, but maybe he can chime in as he did most of the implementation!

**Comment by Steven0351** [comment]
It appears that all of the `App.get_*` methods behave the same way (calling `.all_pages` after retrieving the response).

**Comment by Steven0351** [comment]
This is still an issue; haven’t had time to dig into a good way to address this myself

**Comment by joshdholtz** [comment]
@Steven0351 Will fix today! Sorry about not seeing this!

**Comment by Steven0351** [comment]
No worries @joshdholtz, I had intentions of working on it myself when I opened the issues but I haven't been able to find the time. Thanks for picking it up!
