### ISSUE TITLE
Increment build version in AndroidManifest.xml (manual / auto-bump / retrieve Google play store version)

### ISSUE THREAD

**Issue by Tyler-V** [fastlane/fastlane#16406]
#### Motivation Behind Feature
Right now I'm not aware of any action available to bump the version code in the AndroidManifest.xml.

It would be nice if there was a simple action to bump the versionCode.

It would be really nice if there was a similar workflow to the ios lanes where you can set the AndroidManifest.xml to the latest version + 1 of the lane you specify (internal, alpha, beta, etc.)

`set_info_plist_value(path: "./App_Resources/iOS/Info.plist", key: "CFBundleVersion", value: (latest_testflight_build_number + 1).to_s)`

#### Feature Description
* We should be able to specify the location of the AndroidManifest.xml
* We should be able to specify a value, or if omitted it will bump the existing versionCode by 1

Bonus:
* We should be able to specify which track in the play store to retrieve the currently uploaded version and use that result + 1 to specify the new build version and update the AndroidManifest.xml

#### Alternatives or Workarounds
Good old manual entry!

I am using fastlane with Nativescript and loving what it does for me so far, this would be a seriously welcomed enhancement for quality of life when using this tool.

**Comment by wilsolutions** [comment]
There is a old plugin that you can use but again it is 3 or 4 years old:
```
    increment_version_code(
      gradle_file_path: "./app/build.gradle"
    )
```

**Comment by prathmeshranaut** [comment]
There is a plugin that does this: https://github.com/SiarheiFedartsou/fastlane-plugin-versioning
This can be a little buggy but I submitted PR to fix my use cases and those were pretty much the same as yours.
