### ISSUE TITLE
ERROR ITMS-90725: "SDK Version Issue. This app was built with the iOS 12.4 SDK. New apps for iPhone or iPad must be built with the iOS 13 SDK or later."

### ISSUE THREAD

**Issue by hnk-atheer** [fastlane/fastlane#16418]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [14:48:30]: [32mThis might take a few minutes. Please don't interrupt the script.[0m
[14:49:30]: [31m[Transporter Error Output]: ERROR ITMS-90725: "SDK Version Issue. This app was built with the iOS 12.4 SDK. New apps for iPhone or iPad must be built with the iOS 13 SDK or later."
[0m
[14:49:30]: [31mTransporter transfer failed.[0m
[14:49:30]: 
[14:49:30]: [31mERROR ITMS-90725: "SDK Version Issue. This app was built with the iOS 12.4 SDK. New apps for iPhone or iPad must be built with the iOS 13 SDK or later."
[0m
[14:49:30]: [33m[iTMSTransporter] [2020-05-01 14:49:30 PDT] <main> DBG-X:   parameter ErrorCode = 1102
Any Idea why this happeing?
I was able to upload IPA on Xcode and only get the warring but upload successfully proceed to TestFlight
<img width="838" alt="Screen Shot 2020-05-01 at 2 56 05 PM" src="https://user-images.githubusercontent.com/56893267/80844631-fbed4e80-8bbb-11ea-8dc1-4efaa131557b.png"> </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                          |
| --------------------------- | ---------------------------------------------- |
| OS                          | 10.14.6                                        |
| Ruby                        | 2.7.0                                          |
| Bundler?                    | false                                          |
| Git                         | git version 2.20.1 (Apple Git-117)             |
| Installation Source         | ~/.rvm/rubies/ruby-2.7.0-preview1/bin/fastlane |
| Host                        | Mac OS X 10.14.6 (18G3020)                     |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.7.0-preview1/lib          |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                    |
| Is contained                | false                                          |
| Is homebrew                 | false                                          |
| Is installed via Fabric.app | false                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/    |
| Xcode Version               | 10.3                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.146.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 2.1.4        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.72.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday                   | 0.17.3       |
| faraday_middleware        | 0.13.1       |
| gh_inspector              | 1.1.3        |
| json                      | 2.2.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| signet                    | 0.12.0       |
| os                        | 1.0.1        |
| googleauth                | 0.10.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.308.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.1.3        |
| aws-sdk-core              | 3.94.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.63.0       |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| unicode-display_width     | 1.6.1        |
| addressable               | 2.7.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| fastimage                 | 2.1.7        |
| dotenv                    | 2.7.5        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| multi_json                | 1.14.1       |
| memoist                   | 0.16.2       |
| digest-crc                | 0.4.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.25.1       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |

*generated on:* **2020-05-01**

</pre>
</details>

**Comment by max-ott** [comment]
It's not clear what your issue with regards to `fastlane` is. Please re-open a new issue clearly describing your problems and what you tried so far.
