### ISSUE TITLE
session cookie not valid, but 2FA working when Spaceship::Portal.login(username, password) 

### ISSUE THREAD

**Issue by StarKing-Lu** [fastlane/fastlane#16417]
# Logfile created on 2020-05-01 18:13:58 +0800 by logger.rb/56438
INFO  [18:13:58]: >> GET https://appstoreconnect.apple.com/olympus/v1/session: [undefined body] 
DEBUG [18:14:02]: << GET https://appstoreconnect.apple.com/olympus/v1/session: 401 Unauthenticated

Request ID: 7R5MZTYEABBCMVL3YAV4XZXOEE.0.0

WARN  [18:14:02]: Auth lost
INFO  [18:14:02]: >> POST https://idmsa.apple.com/appleauth/auth/signin: {"accountName":"shan39430@163.com","password":"***","rememberMe":true} 
DEBUG [18:14:03]: << POST https://idmsa.apple.com/appleauth/auth/signin: 409 {"authType"=>"hsa2"}
INFO  [18:14:03]: >> GET https://idmsa.apple.com/appleauth/auth: [undefined body] 
DEBUG [18:14:05]: << GET https://idmsa.apple.com/appleauth/auth: 201 {"trustedPhoneNumbers"=>[{"numberWithDialCode"=>"+86 \u2022\u2022\u2022 \u2022\u2022\u2022\u2022 \u2022\u202242", "obfuscatedNumber"=>"\u2022\u2022\u2022 \u2022\u2022\u2022\u2022 \u2022\u202242", "pushMode"=>"sms", "id"=>2}], "phoneNumber"=>{"numberWithDialCode"=>"\u2022\u2022\u2022 \u2022\u2022\u2022 \u2022\u2022\u2022\u2022 \u2022\u202242", "obfuscatedNumber"=>"\u2022\u2022\u2022 \u2022\u2022\u2022\u2022 \u2022\u202242", "pushMode"=>"sms", "id"=>2}, "securityCode"=>{"length"=>6, "tooManyCodesSent"=>false, "tooManyCodesValidated"=>false, "securityCodeLocked"=>false, "securityCodeCooldown"=>false}, "mode"=>"sms", "type"=>"verification", "authenticationType"=>"hsa2", "recoveryUrl"=>"https://iforgot.apple.com/phone/add?prs_account_nm=shan39430%40163.com&autoSubmitAccount=true&appId=142", "cantUsePhoneNumberUrl"=>"https://iforgot.apple.com/iforgot/phone/add?context=cantuse&prs_account_nm=shan39430%40163.com&autoSubmitAccount=true&appId=142", "recoveryWebUrl"=>"https://iforgot.apple.com/password/verify/appleid?prs_account_nm=shan39430%40163.com&autoSubmitAccount=true&appId=142", "repairPhoneNumberUrl"=>"https://gsa.apple.com/appleid/account/manage/repair/verify/phone", "repairPhoneNumberWebUrl"=>"https://appleid.apple.com/widget/account/repair?#!repair", "noTrustedDevices"=>true, "aboutTwoFactorAuthenticationUrl"=>"https://support.apple.com/kb/HT204921", "autoVerified"=>false, "showAutoVerificationUI"=>false, "supportsRecovery"=>true, "trustedPhoneNumber"=>{"numberWithDialCode"=>"+86 \u2022\u2022\u2022 \u2022\u2022\u2022\u2022 \u2022\u202242", "obfuscatedNumber"=>"\u2022\u2022\u2022 \u2022\u2022\u2022\u2022 \u2022\u202242", "pushMode"=>"sms", "id"=>2}, "hsa2Account"=>true, "restrictedAccount"=>false, "managedAccount"=>false}

**Comment by max-ott** [comment]
Could you please re-open a new issue with a clear description of what the problem is and all required information? Thanks!
