### ISSUE TITLE
fastlane not able to find the schemes from the xcodeproj

### ISSUE THREAD

**Issue by akashnimare** [fastlane/fastlane#16427]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
fastlane not able to find the schemes from the xcodeproj

#### Question Description

Was trying to put my app no Testflight and got this scheme error -

```
➜  appy-ios git:(master) fastlane gym
[20:35:00]: $ xcodebuild -list -workspace ./appy-ios.xcworkspace
[20:35:00]: Couldn't find any schemes in this project, make sure that the scheme is shared if you are using a workspace
[20:35:00]: Open Xcode, click on `Manage Schemes` and check the `Shared` box for the schemes you want to use
[20:35:00]: Afterwards make sure to commit the changes into version control
[!] No Schemes found
``` 
If I open the project using `Appy.xcodeproj`, I can see my scheme (Product > Manage Scheme) which was by default created by Xcode (btw `Shared` setting is on). Though I don't see any scheme if I open my click on `appy.xcworkspace`.

Here is the output of `xcodebuild -list`

```

➜  appy git:(fastlane-fixes) ✗ xcodebuild -list

Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list

Information about project "Appy":
    Targets:
        Appy
        AppyTests
        AppyUITests

    Build Configurations:
        Debug
        Release

    If no build configuration is specified and -scheme is not passed then "Release" is used.

    Schemes:
        Appy
```

I have gone through similar issues but haven't found a correct way to fix this issue. I wanted to know if there is any way to tell Fastlane to use `xcodeproj` schemes instead of picking it up from `xcworkspace`.

Output of `fastlane-env`

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.3                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.18.0                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.15.3 (19D76)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.4.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.3"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  carthage platform: 'iOS'
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide

    # increment_version_number(
    # bump_type: "patch" # Automatically increment patch version number
    # )

    # increment_version_number(
    #   bump_type: "minor" # Automatically increment minor version number
    # )

    # increment_version_number(
    #   bump_type: "major" # Automatically increment major version number
    # )

    increment_build_number(
      xcodeproj: './Appy.xcodeproj'
    )

    carthage(command: "bootstrap",
      platform: "iOS"
    )

    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.Appy" # The bundle identifier of your app
apple_id "XXXXXX@gmail.com" # Your Apple email address

team_id "[[DEV_PORTAL_TEAM_ID]]" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.28.3  | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.16.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.73.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.13.1       |
</details>

*generated on:* **2020-05-06**
</details>

**Comment by janpio** [comment]
> (btw `Shared` setting is on). Though I don't see any scheme if I open my click on `appy.xcworkspace`.

Wouldn't that mean that the sharing is not working in Xcode as well?

**Comment by akashnimare** [comment]
@janpio sorry, don't know how to cross-check that sharing thing.

**Comment by akashnimare** [comment]
@janpio hi, is there anything I need to add in the Fastfile? Been a long time, I'm having this issue and it's a big blocker :/

**Comment by minuscorp** [comment]
Maybe [this](https://developer.nevercode.io/docs/sharing-ios-project-schemes) help you

**Comment by akashnimare** [comment]
@minuscorp hey, I have aleady gone through these kinda articles and my scheme shared thing is on. Do you think the target thing is messing up here? I have re-checked the shared setting and committed to github again but getting the same error. Do I need add anything in the fastfile? I have tried adding the scheme name manually (to the gym) but it didn't work.

**Comment by janpio** [comment]
If I were you I would create a new project, and set it up cleanly from the beginning to see if sharing does what it is supposed to do there. If it does, something is funky about your project.

**Comment by akashnimare** [comment]
Will try, is there any sample ios-project where I can test out the Fastlane implementation. I found a couple of boilerplate but all are pretty old. I'm now passing the scheme to `gym` section manually and running `fastlane beta` to check if it works. I think `fastlane gym` won't work if you don't pass the workspace + scheme from the command line.

**Comment by akashnimare** [comment]
Okay, I just spot something, looks like I was using `v2.28.3` somewhere caused by https://github.com/fastlane/fastlane/issues/15496. Just updated the Fastlane to the latest version which is `v2.148.1`. Also, the one thing I have noticed is that even though I see one scheme in Xcode, it's not there in the `app.xcworkspace/xcshareddata`, this is strange 🤔 ?

**Comment by akashnimare** [comment]
Also, I would like to understand this -
> Afterwards make sure to commit the changes into version control

Do I need to commit the scheme folder in git? I have added `xcuserdata` in my gitignore.

**Comment by minuscorp** [comment]
when you link the `xcodeproj` it looks up for the schemes using:
```
xcodebuild -list -workspace ./MyApp.xcworkspace
xcodebuild -list -project ./MyApp.xcodeproj
```
depending on your environment, so it is not like a fastlane linked thingy, have you tried running those commands?

**Comment by akashnimare** [comment]
From me, the xcworkspace file was useless so removed it. Here is my latest configuration -

Fastfile -

fastlane_version "2.148.1"

default_platform :ios

platform :ios do
  #before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
#  carthage platform: 'iOS'
 # end

  #desc "Runs all the tests"
  #lane :test do
   # scan
  #end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide

    increment_build_number(
      xcodeproj: './Appname.xcodeproj'
    )

    #carthage(command: "bootstrap",
     # platform: "iOS"
    #)

	get_certificates           # invokes cert
    get_provisioning_profile

	# Automatic manage provisional profiles
     build_app(
     project: "appname.xcodeproj",
	   scheme: "AppScheme",
     export_xcargs: "-allowProvisioningUpdates")

    gym(
    	scheme: "Appname",
    	project: "appname.xcodeproj"
    ) # Build your app - more options available
    upload_symbols_to_crashlytics
    pilot(dev_portal_team_id: ENV[DEV_PORTAL_TEAM_ID], itc_team_id: ENV[ITC_TEAM_ID])

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
```


Appfile
```

app_identifier ENV["APP_IDENTIFIER"] # The bundle identifier of fold app
apple_id ENV["APPLE_ID] # Apple email address
team_id ENV[DEV_PORTAL_TEAM_ID] # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```

**Comment by akashnimare** [comment]
On a side-note is it possible to define the scheme + project on top-level so that I don't need to pass the same to `build_app` and `gym`? Also, `export_xcargs: "-allowProvisioningUpdates")` doesn't work as expected.

**Comment by minuscorp** [comment]
You can pass parameters into any lane with 
`lane :build |options| do ...`
And call it like `bundle exec fastlane build project:'MyProiect.xcodeproj' scheme:'MyApp'`
You can read those from the `options` hash: `options[:project]`
