### ISSUE TITLE
ERROR ITMS-90725: "SDK Version Issue. This app update was built with the iOS SDK. New apps for iPhone or iPad must be built with the iOS 13 SDK or later.

### ISSUE THREAD

**Issue by enggrakeshcse** [fastlane/fastlane#16424]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by janpio** [comment]
How is your question related to fastlane?

Seems you need to use the iOS 13 SDK as the error message tells you to.

**Comment by jjlehtinen** [comment]
Looks like something wrong in Apples end? We are hitting this as well.

**Comment by darwingittest** [comment]
Anyone had any luck find what is causing that issue?

**Comment by jjlehtinen** [comment]
Not yet, currently running the uploads manually. Will need to dig deeper into this. We are building using Unity as well, if that's of any relevance.

**Comment by apanagar** [comment]
I'm hitting this issue as well
