### ISSUE TITLE
Add an action retrieving a Google Play track's version name

### ISSUE THREAD

**Issue by philippeauriach** [fastlane/fastlane#16432]
#### Motivation Behind Feature
The same way as we can retrieve a track version code using the `google_play_track_version_codes` action, it could be nice to easily retrieve the version name for a specific track. In our case, as we use semantic versioning for our version names, in our release lane, we want to fetch latest version name from production track, bump it and set it in our android project for the new release build. This way every release creates a new bump automatically.

#### Feature Description
The code for this action is created locally and uses `Supply::Client.latest_version` method. It works fine and can be submitted as a PR if the action is interesting enough (as mentioned in the doc https://docs.fastlane.tools/create-action/)
```ruby
      def self.run(params)
        require 'supply'
        require 'supply/options'

        Supply.config = params
        track = params[:track]

        client = Supply::Client.make_from_config

        client.begin_edit(package_name: Supply.config[:package_name])
        version_names = client.latest_version(track)
        client.abort_current_edit

        if version_names.nil?
          UI.important("No version name found in track '#{track}'")
          nil
        else
          UI.success("Found '#{version_names.name}' version name in track '#{track}'")
          version_names.name
        end
      end
```

#### Alternatives or Workarounds
Not found any

**Comment by daman08** [comment]
This will be a great feature to add

**Comment by daman08** [comment]
Hello Philippe Auriach,

> ### Feature Request
> #### Motivation Behind Feature
> The same way as we can retrieve a track version code using the `google_play_track_version_codes` action, it could be nice to easily retrieve the version name for a specific track. In our case, as we use semantic versioning for our version names, in our release lane, we want to fetch latest version name from production track, bump it and set it in our android project for the new release build. This way every release creates a new bump automatically.
> 
> #### Feature Description
> The code for this action is created locally and uses `Supply::Client.latest_version` method. It works fine and can be submitted as a PR if the action is interesting enough (as mentioned in the doc https://docs.fastlane.tools/create-action/)
> 
> ```ruby
>       def self.run(params)
>         require 'supply'
>         require 'supply/options'
> 
>         Supply.config = params
>         track = params[:track]
> 
>         client = Supply::Client.make_from_config
> 
>         client.begin_edit(package_name: Supply.config[:package_name])
>         version_names = client.latest_version(track)
>         client.abort_current_edit
> 
>         if version_names.nil?
>           UI.important("No version name found in track '#{track}'")
>           nil
>         else
>           UI.success("Found '#{version_names.name}' version name in track '#{track}'")
>           version_names.name
>         end
>       end
> ```
> 
> #### Alternatives or Workarounds
> Not found any

Is is possible to get Version Code as part of above action code.

Daman

**Comment by philippeauriach** [comment]
Hi Daman,

There is already an action for the action code: google_play_track_version_codes

Philippe Auriach

**Comment by mortenholmgaard** [comment]
This would be a good feature - we need this!

**Comment by philippeauriach** [comment]
It is fixed by PR https://github.com/fastlane/fastlane/pull/15961 , see action google_play_track_release_names : https://docs.fastlane.tools/actions/google_play_track_release_names/
