### ISSUE TITLE
Set fastlane exit code/ propagate shell script exit code

### ISSUE THREAD

**Issue by kuhnroyal** [fastlane/fastlane#16436]
### Question Checklist

- [ x] Updated fastlane to the latest version
- [ x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Is it possible to set a custom exit code somehow, the exit code is always 1 when any error occurs even if the `sh` call results in a different exit code?
Since `exit 2` doesn't work and the `UI.user|shell_error!` functions don't seem to provide a way. 
I don't know a lot about ruby but I tried all the common ways with `raise/exit` but without any success.

### Fastlane env
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.4                                     |
| Ruby                        | 2.6.5                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.26.2                          |
| Installation Source         | ~/.rbenv/versions/2.6.5/bin/fastlane        |
| Host                        | Mac OS X 10.15.4 (19E287)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.5/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.4.1                                      |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
import_from_git(
    url: 'https://.../flutter/fastlane_flutter.git',
    version: '3.0.0',
)

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.146.1 | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                                 | Version | Update-Status |
| -------------------------------------- | ------- | ------------- |
| fastlane-plugin-increment_version_code | 0.4.3   | ✅ Up-To-Date  |
| fastlane-plugin-badge                  | 1.4.0   | ✅ Up-To-Date  |
| fastlane-plugin-changelog              | 0.15.0  | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                    | Version      |
| -------------------------------------- | ------------ |
| did_you_mean                           | 1.3.0        |
| bundler                                | 2.1.4        |
| CFPropertyList                         | 3.0.2        |
| concurrent-ruby                        | 1.1.6        |
| i18n                                   | 0.9.5        |
| minitest                               | 5.14.0       |
| thread_safe                            | 0.3.6        |
| tzinfo                                 | 1.2.6        |
| activesupport                          | 4.2.11.1     |
| public_suffix                          | 2.0.5        |
| addressable                            | 2.7.0        |
| httpclient                             | 2.8.3        |
| json                                   | 2.3.0        |
| algoliasearch                          | 1.27.1       |
| atomos                                 | 0.1.3        |
| aws-eventstream                        | 1.1.0        |
| aws-partitions                         | 1.301.0      |
| aws-sigv4                              | 1.1.2        |
| jmespath                               | 1.4.0        |
| aws-sdk-core                           | 3.94.0       |
| aws-sdk-kms                            | 1.30.0       |
| aws-sdk-s3                             | 1.63.0       |
| babosa                                 | 1.0.3        |
| curb                                   | 0.9.10       |
| fastimage                              | 2.1.7        |
| colored                                | 1.2          |
| highline                               | 1.7.10       |
| commander-fastlane                     | 4.4.6        |
| dotenv                                 | 2.7.5        |
| emoji_regex                            | 1.0.1        |
| excon                                  | 0.73.0       |
| multipart-post                         | 2.0.0        |
| faraday                                | 0.17.3       |
| unf_ext                                | 0.0.7.7      |
| unf                                    | 0.1.4        |
| domain_name                            | 0.5.20190701 |
| http-cookie                            | 1.0.3        |
| faraday-cookie_jar                     | 0.0.6        |
| faraday_middleware                     | 0.13.1       |
| gh_inspector                           | 1.1.3        |
| jwt                                    | 2.1.0        |
| memoist                                | 0.16.2       |
| multi_json                             | 1.14.1       |
| os                                     | 1.1.0        |
| signet                                 | 0.14.0       |
| googleauth                             | 0.12.0       |
| mini_mime                              | 1.0.2        |
| declarative                            | 0.0.10       |
| declarative-option                     | 0.1.0        |
| uber                                   | 0.1.0        |
| representable                          | 3.0.4        |
| retriable                              | 3.1.2        |
| google-api-client                      | 0.36.4       |
| digest-crc                             | 0.5.1        |
| google-cloud-env                       | 1.3.1        |
| google-cloud-errors                    | 1.0.0        |
| google-cloud-core                      | 1.5.0        |
| google-cloud-storage                   | 1.26.0       |
| mini_magick                            | 4.10.1       |
| multi_xml                              | 0.6.0        |
| plist                                  | 3.5.0        |
| rubyzip                                | 1.3.0        |
| security                               | 0.1.3        |
| naturally                              | 2.2.0        |
| simctl                                 | 1.6.8        |
| slack-notifier                         | 2.3.2        |
| terminal-notifier                      | 2.0.0        |
| unicode-display_width                  | 1.7.0        |
| terminal-table                         | 1.8.0        |
| tty-screen                             | 0.7.1        |
| tty-cursor                             | 0.7.1        |
| tty-spinner                            | 0.9.3        |
| word_wrap                              | 1.0.0        |
| claide                                 | 1.0.3        |
| colored2                               | 3.1.2        |
| nanaimo                                | 0.2.6        |
| xcodeproj                              | 1.16.0       |
| rouge                                  | 2.0.7        |
| xcpretty                               | 0.3.0        |
| xcpretty-travis-formatter              | 1.0.0        |
| badge                                  | 0.12.0       |
| fuzzy_match                            | 2.0.4        |
| nap                                    | 1.1.0        |
| netrc                                  | 0.11.0       |
| ffi                                    | 1.12.2       |
| ethon                                  | 0.12.0       |
| typhoeus                               | 1.3.1        |
| cocoapods-core                         | 1.9.1        |
| cocoapods-deintegrate                  | 1.0.4        |
| cocoapods-downloader                   | 1.3.0        |
| cocoapods-plugins                      | 1.0.0        |
| cocoapods-search                       | 1.0.0        |
| cocoapods-stats                        | 1.1.0        |
| cocoapods-trunk                        | 1.4.1        |
| cocoapods-try                          | 1.1.0        |
| escape                                 | 0.0.4        |
| fourflusher                            | 2.3.1        |
| molinillo                              | 0.6.6        |
| ruby-macho                             | 1.4.0        |
| cocoapods                              | 1.9.1        |
| fastlane-plugin-badge                  | 1.4.0        |
| fastlane-plugin-changelog              | 0.15.0       |
| fastlane-plugin-increment_version_code | 0.4.3        |
| mime-types-data                        | 3.2019.1009  |
| mime-types                             | 3.3.1        |
| httparty                               | 0.18.0       |
| gitlab                                 | 4.14.1       |
| semver2                                | 3.4.2        |
</details>

*generated on:* **2020-05-14**
</details>

**Comment by skantaman** [comment]
Same issue.
fastlane env:

> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.4                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.21.0 (Apple Git-122)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.4 (19E266)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.1                                                           |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | it_IT.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
fastlane_version "2.12.0"
xcode_select "/Applications/Xcode.app"


    lane :build_release do |options|
        begin

            env = "dev"
            if options[:env]
                env = options[:env]
            end
            abi = "03075"
            if options[:abi]
                abi = options[:abi]
            end
            brand = "0"
            if options[:brand]
                brand = options[:brand]
            end
            bn = "1"
            if options[:bn]
                bn = options[:bn]
            end
            vn = "0.0.1"
            if options[:vn]
                vn = options[:vn]
            end
            us = false
            if options[:us]
                us = options[:us]
            end
            flavor = "Abi"+abi+"_"+brand+env.capitalize

            gradle(
                task: "assemble",
                build_type:"Release",
                project_dir:"../"+ENV["ANDROIDDIR"]+"/",
                flavor:flavor,
                properties:{
                    "buildNumber" => "#{bn}",
                    "versionName" => "#{vn}",
                    "updateString" => "#{us}",
                    "abi"=>"#{abi}",
                    "brand"=>"#{brand}"
                }
            )
        rescue => ex
            UI.error (ex)
            UI.build_failure!("Build release fallita!!!!")
        end
    end
end
```
</details>

**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.148.1 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.1        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.72.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.13.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.11.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.5.1        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.286.0      |
| aws-eventstream           | 1.0.3        |
| aws-sigv4                 | 1.1.1        |
| aws-sdk-core              | 3.92.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.61.1       |
| CFPropertyList            | 3.0.2        |
| json                      | 2.3.0        |
| bundler                   | 2.0.2        |
| forwardable               | 1.2.0        |
| logger                    | 1.4.1        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.3        |
| date                      | 2.0.0        |
| fileutils                 | 1.3.0        |
| io-console                | 0.4.8        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.2.3        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.5.0        |
</details>


*generated on:* **2020-05-21**
</details>

>

**Comment by om1baaw** [comment]
Love it thank for the valuable information…
