### ISSUE TITLE
[Frameit] Does Frameit support formatting part of the text (bold or italics) inside title.strings texts?

### ISSUE THREAD

**Issue by Husseinovich** [fastlane/fastlane#16439]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Does Frameit for iOS support bold or italics as part of the title.strings texts?

#### Question Description
I just wanted to know whether Fastlane frameit for iOS supports formatting the texts inside titles.string file.

For example bold some texts in the middle or at the end:

"screen1" : "Build **awesome** stuff"
"screen2" : "Try out new awesome **custom feature**"

If not how would one achieve this case?

I know we can use keywords file but can keywords be inserted at any position? I know we can insert keyword in the beginning of the text, but can we insert in the middle of the text?

**Comment by janpio** [comment]
I do not think this functionality is available.
