### ISSUE TITLE
upload_to_app_store with submit_for_review(true) returns "ITC.response.error.OPERATION_FAILED" 

### ISSUE THREAD

**Issue by MoacirSchmidt** [fastlane/fastlane#16442]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
upload_to_app_store with submit_for_review(true) returns a generic error message "ITC.response.error.OPERATION_FAILED" 

If I set submit_for_review(false) everything goes ok (but, of course, app is not submitted for review in App Store and I am unable to complete the whole process unattended)

##### Command executed
bundle exec fastlane release --verbose

##### Complete output when running fastlane, including the stack trace and command used
<pre>
<details>DEBUG [2020-05-09 13:04:25.48]: Checking if there are any plugins that should be loaded...
[33mSuccessfully loaded Appfile at path '/Users/mac/projects/polygonus_mobile/polygonus_app/main/ios/fastlane/Appfile'[0m
-------
INFO [2020-05-09 13:04:25.66]: [32m------------------------------[0m
INFO [2020-05-09 13:04:25.66]: [32m--- Step: default_platform ---[0m
INFO [2020-05-09 13:04:25.66]: [32m------------------------------[0m
INFO [2020-05-09 13:04:25.66]: [32mDriving the lane 'ios release' 🚀[0m
INFO [2020-05-09 13:04:25.78]: [32m---------------------------------[0m
INFO [2020-05-09 13:04:25.78]: [32m--- Step: upload_to_app_store ---[0m
INFO [2020-05-09 13:04:25.78]: [32m---------------------------------[0m
INFO [2020-05-09 13:04:25.78]: [32mSuccessfully loaded '/Users/mac/projects/polygonus_mobile/polygonus_app/main/ios/fastlane/Deliverfile' 📄[0m
WARN [2020-05-09 13:04:25.78]: [33mNo values defined in './fastlane/Deliverfile'[0m
INFO [2020-05-09 13:04:25.78]: Login to App Store Connect ()
Reading keychain entry, because either user or password were empty
Loading session from '/Users/mac/.fastlane/spaceship/gmail.com/cookie'
Looking for App Store Connect Team with ID 
INFO [2020-05-09 13:04:27.32]: Login successful

+--------------------------------------------------------------------+--------------------------------+
|                                       [32mdeliver 2.146.1 Summary[0m                                       |
+--------------------------------------------------------------------+--------------------------------+
| submit_for_review                                                  | true                           |
| automatic_release                                                  | true                           |
| skip_metadata                                                      | true                           |
| skip_binary_upload                                                 | true                           |
| skip_screenshots                                                   | true                           |
| force                                                              | true                           |
| submission_information.add_id_info_serves_ads                      | false                          |
| submission_information.add_id_info_uses_idfa                       | false                          |
| submission_information.add_id_info_limits_tracking                 | true                           |
| submission_information.export_compliance_encryption_updated        | false                          |
| submission_information.export_compliance_uses_encryption           | false                          |
| submission_information.content_rights_contains_third_party_content | false                          |
| screenshots_path                                                   | ./fastlane/screenshots         |
| metadata_path                                                      | ./fastlane/metadata            |
| app_version                                                        | 4.01.10                        |
| username                                                           | mm       |
| app_identifier                                                     | br.com.xxxxxxxxxxxxxxxxxxxxxxx |
| ipa                                                                | Runner.ipa                     |
| platform                                                           | ios                            |
| edit_live                                                          | false                          |
| use_live_version                                                   | false                          |
| skip_app_version_update                                            | false                          |
| overwrite_screenshots                                              | false                          |
| reject_if_possible                                                 | false                          |
| phased_release                                                     | false                          |
| reset_ratings                                                      | false                          |
| team_id                                                            | Xxxxxxxx1                      |
| dev_portal_team_id                                                 | xxxxxxxxxi 	              |
| run_precheck_before_submit                                         | true                           |
| precheck_default_rule_level                                        | warn                           |
| individual_metadata_items                                          | []                             |
| ignore_language_directory_validation                               | false                          |
| precheck_include_in_app_purchases                                  | true                           |
+--------------------------------------------------------------------+--------------------------------+

INFO [2020-05-09 13:04:27.96]: Making sure the latest version on App Store Connect matches '4.01.10' from the ipa file...
INFO [2020-05-09 13:04:29.15]: [32m'4.01.10' is the latest version on App Store Connect[0m
INFO [2020-05-09 13:04:31.38]: Uploading app icon...
INFO [2020-05-09 13:04:34.91]: Running precheck before submitting to review, if you'd like to disable this check you can set run_precheck_before_submit to false
INFO [2020-05-09 13:04:34.91]: Making sure we pass precheck 👮‍♀️ 👮 before we submit  🛫

+--------------------------+--------------------------------+
|               [32mSummary for precheck 2.146.1[0m                |
+--------------------------+--------------------------------+
| default_rule_level       | warn                           |
| include_in_app_purchases | true                           |
| app_identifier           | br.xxxxxxxxxxxxxxxxxxxxxxxxxxx |
| username                 | xxxxxxxxxxxxxxxxxxxxxxxx       |
| team_id                  | xxxxxxxxxx                     |
+--------------------------+--------------------------------+

INFO [2020-05-09 13:04:34.92]: Checking app for precheck rule violations
INFO [2020-05-09 13:04:41.28]: Reading in-app purchases. If you have a lot, this might take a while
INFO [2020-05-09 13:04:41.28]: You can disable IAP checking by setting the `include_in_app_purchases` flag to `false`
INFO [2020-05-09 13:04:41.98]: Done reading in-app purchases
INFO [2020-05-09 13:04:42.85]: ✅  Passed: No negative  sentiment
INFO [2020-05-09 13:04:42.85]: ✅  Passed: No placeholder text
INFO [2020-05-09 13:04:42.85]: ✅  Passed: No mentioning  competitors
INFO [2020-05-09 13:04:42.85]: ✅  Passed: No future functionality promises
INFO [2020-05-09 13:04:42.85]: ✅  Passed: No words indicating test content
INFO [2020-05-09 13:04:42.87]: ✅  Passed: No curse words
INFO [2020-05-09 13:04:42.87]: ✅  Passed: No words indicating your IAP is free
DEBUG [2020-05-09 13:04:42.87]: custom_text excluded because no data was passed to it e.g.: custom_text(data: <data here>)
INFO [2020-05-09 13:04:42.87]: ✅  Passed: Incorrect, or missing copyright date
INFO [2020-05-09 13:04:44.58]: ✅  Passed: No broken urls
INFO [2020-05-09 13:04:44.59]: [32mprecheck 👮‍♀️ 👮  finished without detecting any potential problems 🛫[0m
INFO [2020-05-09 13:04:45.91]: Selecting the latest build...
WARN [2020-05-09 13:04:46.52]: [33m[33mLane Context:[0m
INFO [2020-05-09 13:04:46.52]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios release"}
ERROR [2020-05-09 13:04:46.52]: [31mITC.response.error.OPERATION_FAILED[0m
INFO [2020-05-09 13:04:46.52]: [32mSuccessfully generated documentation at path '/Users/mac/projects/polygonus_mobile/polygonus_app/main/ios/fastlane/README.md'[0m

+------+---------------------+-------------+
|             [32mfastlane summary[0m             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | default_platform    | 0           |
| 💥   | [31mupload_to_app_store[0m | 20          |
+------+---------------------+-------------+

ERROR [2020-05-09 13:04:46.53]: [31mfastlane finished with errors[0m

Looking for related GitHub issues on fastlane/fastlane...
Search query: The request could not be completed because:
	ITC.response.error.OPERATION_FAILED

URL: https://api.github.com/search/issues?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09ITC.response.error.OPERATION_FAILED+repo:fastlane/fastlane
➡️  [33m[Spaceship] cannot update IAP subscription which is already Approved[0m
    https://github.com/fastlane/fastlane/issues/15437 [[32mclosed[0m] 10 💬
    6 weeks ago

➡️  [33mfastlane init error[0m
    https://github.com/fastlane/fastlane/issues/9241 [[32mclosed[0m] 25 💬
    29 Aug 2017

➡️  [33mCan't update in-app purchase with spanish language[0m
    https://github.com/fastlane/fastlane/issues/9115 [[32mclosed[0m] 11 💬
    25 Sep 2017

and 5 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09ITC.response.error.OPERATION_FAILED&type=Issues&utf8=✓

</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.4                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.2 (Apple Git-127)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.4 (19E287)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.4.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    upload_to_app_store(
      submit_for_review: true,
      automatic_release: true,
      skip_metadata: true,
      skip_binary_upload: true,
      skip_screenshots: true,
      force: true,
      submission_information: {
        add_id_info_serves_ads: false,
        add_id_info_uses_idfa: false,
        add_id_info_limits_tracking: true,
        export_compliance_encryption_updated: false,
        export_compliance_uses_encryption: false,
        content_rights_contains_third_party_content: false
      }
    )
  end
end

```
</details>

<details><summary>`./Appfile`</summary>

```ruby
app_identifier("br.cxii") # The bundle identifier of your app
apple_id("moom") # Your Apple email address

itc_team_id("111") # App Store Connect Team ID
team_id("FCL") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.146.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.16.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.73.0       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday                   | 0.17.3       |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.0        |
| googleauth                | 0.12.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.5.1        |
| google-cloud-storage      | 1.26.1       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.311.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.1.3        |
| aws-sdk-core              | 3.95.0       |
| aws-sdk-kms               | 1.31.0       |
| aws-sdk-s3                | 1.64.0       |
| CFPropertyList            | 3.0.2        |
| json                      | 2.3.0        |
| forwardable               | 1.3.1        |
| logger                    | 1.4.2        |
| stringio                  | 0.1.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.3        |
| date                      | 3.0.0        |
| fileutils                 | 1.4.1        |
| io-console                | 0.5.6        |
| zlib                      | 1.1.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.2.4        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.6.0        |
</details>

*generated on:* **2020-05-09**
</details></pre>
</details>

**Comment by mlachmish** [comment]
I experience the same issue as well.

**Comment by AdamNSmith** [comment]
Same issue here.

**Comment by tedgonzalez** [comment]
Had a similar issue when using `upload_to_testflight`
```
[21:23:26]: [Transporter Error Output]: An error occurred while uploading the package: 390631214.itmsp.
[21:23:26]: [Transporter Error Output]: An exception has occurred: Connection reset
[21:26:37]: [Transporter Error Output]: An error occurred while uploading the package: 390631214.itmsp
[21:28:54]: Transporter transfer failed.
[21:28:54]: 
[21:28:54]: An error occurred while uploading the package: 390631214.itmsp.

An exception has occurred: Connection reset

An error occurred while uploading the package: 390631214.itmsp

[21:28:54]: [iTMSTransporter] [2020-05-11 21:28:54 CEST] <main> DBG-X:   parameter SessionExpiration = 2020-05-15T19:28:53.323Z
[21:28:54]: [iTMSTransporter] [2020-05-11 21:28:54 CEST] <main> DBG-X:   parameter Success = true
[21:28:54]: [iTMSTransporter] [2020-05-11 21:28:54 CEST] <main> DBG-X:   parameter StreamingSettings = {LogStreamingEnabled=true, MultipartUploadsEnabled=true, AssetDescriptionStreamingEnabled=false}
[21:28:54]: [iTMSTransporter] [2020-05-11 21:28:54 CEST] <main>  INFO: Transporter's command line arguments are: -m upload -u **** -p **hidden value** -f /var/folders/2k/l84x7xt146g31dwnf9zhk8sc0000gn/T/d20200511-76932-1fps27l/390631214.itmsp -t DAV,Signiant -k 100000 -itc_provider DnBNOR
[21:28:54]: [iTMSTransporter] 
[21:28:54]: [iTMSTransporter] 
[21:28:54]: [iTMSTransporter] 
[21:28:54]: [iTMSTransporter] Package Summary:
[21:28:54]: [iTMSTransporter]  
[21:28:54]: [iTMSTransporter] 1 package(s) were not uploaded because they had problems:
[21:28:54]: [iTMSTransporter] 	/var/folders/2k/l84x7xt146g31dwnf9zhk8sc0000gn/T/d20200511-76932-1fps27l/390631214.itmsp - Error Messages:
[21:28:54]: [iTMSTransporter] 		An error occurred while uploading the package: 390631214.itmsp.
[21:28:54]: [iTMSTransporter] 		An exception has occurred: Connection reset
[21:28:54]: [iTMSTransporter] 		An error occurred while uploading the package: 390631214.itmsp
[21:28:54]: [iTMSTransporter] [2020-05-11 21:28:54 CEST] <main> DBG-X: Returning 1
[21:28:54]: iTunes Transporter output above ^

[21:28:54]: An error occurred while uploading the package: 390631214.itmsp.
```

**Comment by donnes** [comment]
I don't know if it's not an _**App Store Connect API**_ problem, because a couple of hours ago I submitted an IPA using the `upload_to_testflight` action normally. =/

**Comment by mlachmish** [comment]
@tedgonzalez @donnes - The error we are experiencing is not related to `upload_to_testflight`.

We are using `deliver` or `upload_to_testflight` (after the ipa was already uploaded to testflight) with the submit_for_review flag set to true.
We get an "ITC.response.error.OPERATION_FAILED" error after Fastlane tries ti select the latest build for review.

**Comment by MoacirSchmidt** [comment]
I have tried a charles http debug and that message ("ITC.response.error.OPERATION_FAILED") comes from apple without any other useful information.

**Comment by tedgonzalez** [comment]
Thanks @mlachmish and @donnes. It works now for us, no change on our side. Maybe just a regional issue.

**Comment by davidmfinol** [comment]
I see the exact same error trying to `upload_to_app_store` to the Mac App Store.
Interestingly, I can upload iOS builds to the App Store with no problems, even though I am using the [same Deliverfile](https://github.com/finol-digital/Card-Game-Simulator/blob/master/fastlane/Deliverfile) for both iOS and Mac.
Also, I do see the uploaded Mac builds in App Store Connect, but I just have to manually select the build and click on Submit for Review.

**Comment by anhkhoi** [comment]
the same issue for me :(

**Comment by rogerluan** [comment]
Still happens on fastlane 2.148.0

**Comment by reishka** [comment]
I'm experiencing the same, as well. Multiple different apps being uploaded over the span of several hours all come back with ITC.response.error.OPERATION_FAILED

**Comment by rogerluan** [comment]
> Still happens on fastlane 2.148.0

It just worked successfully now. Same version, 2.148.0. Not sure if it is an intermittent issue, or if it was an issue on Apple's end and they fixed it.

**Comment by mlachmish** [comment]
We have a pipeline that runs a job that deliver to the app store on a daily basis.
I am constantly getting this error.

**Comment by MoacirSchmidt** [comment]
> > Still happens on fastlane 2.148.0
> 
> It just worked successfully now. Same version, 2.148.0. Not sure if it is an intermittent issue, or if it was an issue on Apple's end and they fixed it.

Are you sure the message was exactly the same? "ITC.response.error.OPERATION_FAILED" ??? And if the message is shown only when "submit_for_review" was true and everything works well at the same time when "submit_for_review" is false?

**Comment by rogerluan** [comment]
> > > Still happens on fastlane 2.148.0
> > 
> > 
> > It just worked successfully now. Same version, 2.148.0. Not sure if it is an intermittent issue, or if it was an issue on Apple's end and they fixed it.
> 
> Are you sure the message was exactly the same? "ITC.response.error.OPERATION_FAILED" ??? And if the message is shown only when "submit_for_review" was true and everything works well at the same time when "submit_for_review" is false?

Yup, exactly the same. `submit_for_review` was true for all my tests: the ones that failed (like 5+ times), and also the one that succeeded.

**Comment by alouanemed** [comment]
Same issue here.

**Comment by mlachmish** [comment]
We are still experiencing this issue consistently with every job.
Can someone from @fastlane comment about this?

**Comment by bizire** [comment]
Have the same issue:

**The request could not be completed because:
ITC.response.error.OPERATION_FAILED**

**Comment by alouanemed** [comment]
@fastlane-bot Still not yet resolved.

**Comment by Diego-F-Aguirre** [comment]
Same here, still seeing this issue.

**Comment by rogerluan** [comment]
Is everyone running the latest version of Fastlane? Just for the record, I was seeing this issue before, but it fixed itself since this message of mine in May https://github.com/fastlane/fastlane/issues/16442#issuecomment-631868006

Maybe if you guys share more about your environments, we can provide better help? @Diego-F-Aguirre , @alouanemed
