### ISSUE TITLE
How to enable testfilght group public_link with fastlane ?

### ISSUE THREAD

**Issue by csc-EricWu** [fastlane/fastlane#16451]
#### Alternatives or Workarounds

![image](https://user-images.githubusercontent.com/13517061/81650265-35e40d80-9464-11ea-91df-c1c2930cca1a.png)

**Comment by zhonghphuan** [comment]
How to enable testfilght group public_link with fastlane？

**Comment by zhonghphuan** [comment]
# 启用公测链接
    public_link = `echo curl -H "Authorization: Bearer #{jwt_token}" -H "Content-type: application/json" -X PATCH -d '{"data": {"type": "betaGroups","id": "#{groupid}","attributes": {"name": "#{groups}","publicLinkEnabled": true,"publicLinkLimitEnabled": false,"publicLinkLimit": null,"feedbackEnabled": true}}}' https://api.appstoreconnect.apple.com/v1/betaGroups/#{groupid} | jq '.data[0].attributes.publicLink'`
    puts "公测链接: #{public_link}"

**Comment by csc-EricWu** [comment]
我想删除之前的组，和组里的测试者，请问有好的实现方式吗？
