### ISSUE TITLE
Deliver Fails - "unable to verify WebDAV transport: Connection reset"

### ISSUE THREAD

**Issue by jsahoo** [fastlane/fastlane#16462]
### New Regression Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

I'm using Bitrise so I don't think I have control over the fastlane version, but presumably it's using the latest

### Regression Information

- Breaking version: deliver 2.148.0
- Last working version: deliver 2.147.0

### Regression Description

Deliver fails with the following output every time:

```
[18:18:12]: [Transporter Error Output]: unable to verify WebDAV transport: Connection reset
[18:19:44]: [Transporter Error Output]: An error occurred while uploading the package: XXXXXXX.itmsp.
[18:19:44]: [Transporter Error Output]: An exception has occurred: Connection reset
[18:21:33]: [Transporter Error Output]: An error occurred while uploading the package: XXXXXXX.itmsp
[18:21:34]: Transporter transfer failed.
[18:21:34]: 
[18:21:34]: unable to verify WebDAV transport: Connection reset
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by CovertLeopard** [comment]
FWIW, we are getting the exact same starting yesterday and we are still on 2.137.0.

**Comment by CovertLeopard** [comment]
Another note, we just ran a build again and it worked fine, so it appears to be an intermittent issue on Apple's side.

**Comment by jsahoo** [comment]
> Another note, we just ran a build again and it worked fine, so it appears to be an intermittent issue on Apple's side.


I just downgraded our Bitrise "Deploy to iTunes Connect" step to 2.16.3 from 2.17 which is still using Deliver 2.148 but this time it succeeded, so you're probably right that it's an intermittent issue on Apple's side. I'm gonna go ahead and close this out.
