### ISSUE TITLE
Will Frameit support RTL languages?

### ISSUE THREAD

**Issue by StevenMagdy** [fastlane/fastlane#16467]
Any plans for frameit to support RTL languages? based on the search, it was not mentioned since #14941, #7522, and #8131.

**Comment by janpio** [comment]
We would be very happy to review and accept a Pull Request if someone submits one.

**Comment by StevenMagdy** [comment]
Sadly #8131 appears to have fixed the issue but it was not merged.

**Comment by amitkot** [comment]
I've written a simple script for titles with RTL languages until Frameit gets builtin support.
I maintain a `title.strings.before` files that contains the original titles, and run this tool before running Frameit:

```bash
$ python3 reverse_titles.py
```

The script is here:
https://gist.github.com/amitkot/367f95ac1cb3ea73e20f80131e20c8e9
