### ISSUE TITLE
invalid option: --env=staging

### ISSUE THREAD

**Issue by alexpchin** [fastlane/fastlane#16461]
Since updating from `2.147.0` to `2.148.0` I now receive: invalid option: --env=staging

**Comment by Zaszczyk** [comment]
I also have this same problem

**Comment by DerGary** [comment]
Same Problem here

**Comment by Kaspik** [comment]
Seems like it might be related to https://github.com/fastlane/fastlane/pull/16096

**Comment by janpio** [comment]
What command are/were you running before? Lane or action? Got just the `=` removed?

**Comment by alubeck** [comment]
Yes, confirmative. Just remove the `=` do the trick.

**Comment by liamnichols** [comment]
@alubeck: Which command had you been running with `--env=foo` prior to this failing? I'm curious as I authored the change that probably caused this regression so sorry about that

**Comment by DerGary** [comment]
I am using the Microsoft Task for Azure DevOps Pipelines that does something like this:

```
fastlane deliver --force -u *** -a com.test -i /Users/username/Documents/myagent/_work/13/a/AppStore.ipa -j ios -m /Users/username/Documents/myagent/_work/13/s/metadata -w /Users/macdev/Documents/myagent/_work/13/s/screenshots -k *** -e *** --submit_for_review true --automatic_release true --app_rating_config_path metadata/ratings.json
```

and failed with:
```
[!] Could not find option 'env' in the list of available options: username, app_identifier, app_version, ipa, pkg, build_number, platform, edit_live, use_live_version, metadata_path, screenshots_path, skip_binary_upload, skip_screenshots, skip_metadata, skip_app_version_update, force, overwrite_screenshots, submit_for_review, reject_if_possible, automatic_release, auto_release_date, phased_release, reset_ratings, price_tier, app_rating_config_path, submission_information, team_id, team_name, dev_portal_team_id, dev_portal_team_name, itc_provider, run_precheck_before_submit, precheck_default_rule_level, individual_metadata_items, app_icon, apple_watch_app_icon, copyright, primary_category, secondary_category, primary_first_sub_category, primary_second_sub_category, secondary_first_sub_category, secondary_second_sub_category, trade_representative_contact_information, app_review_information, app_review_attachment_file, description, name, subtitle, keywords, promotional_text, release_notes, privacy_url, apple_tv_privacy_policy, support_url, marketing_url, languages, ignore_language_directory_validation, precheck_include_in_app_purchases, app
##[error]Error: fastlane failed with return code: 1
```

Strangly in the command line there is no env parameter so I don't know why it fails with this error. But maybe the output is only a log and is not the command line that is called underneith.

The Task is available here: https://github.com/microsoft/app-store-vsts-extension

In their Repository there is also an issue open to this problem: https://github.com/microsoft/app-store-vsts-extension/issues/152

As a workaround I configure the task to only ever install 1.147.0 instead of the newest version which currently works.

**Comment by milliamp** [comment]
As I have the same situation as @DerGary using Azure DevOps, however, I took my IPA and installed fastlane 2.148.1 locally and then ran the same command it runs
`fastlane deliver -a <appbundleid> -i "<ipafile>.ipa" -j ios --skip_metadata true --skip_screenshots true -e "<apple team name here>"`

Which results in the same error showing. I then used gem to install 2.146.1, ran the same command and it succeeded.

Here is the verbose output when running the above command locally with 2.148.1

```
$ /usr/local/Cellar/fastlane/2.148.1/bin/fastlane deliver -a <appbundleid> -i "<ipafile>.ipa" -j ios --skip_metadata true --skip_screenshots true -e "<teamname>" --verbose
[✔] 🚀 
[09:10:33]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
Traceback (most recent call last):
	20: from /usr/local/Cellar/fastlane/2.148.1/libexec/bin/fastlane:23:in `<main>'
	19: from /usr/local/Cellar/fastlane/2.148.1/libexec/bin/fastlane:23:in `load'
	18: from /usr/local/Cellar/fastlane/2.148.1/libexec/gems/fastlane-2.148.1/bin/fastlane:23:in `<top (required)>'
	17: from /usr/local/Cellar/fastlane/2.148.1/libexec/gems/fastlane-2.148.1/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	16: from /usr/local/Cellar/fastlane/2.148.1/libexec/gems/fastlane-2.148.1/deliver/lib/deliver/commands_generator.rb:17:in `start'
	15: from /usr/local/Cellar/fastlane/2.148.1/libexec/gems/fastlane-2.148.1/deliver/lib/deliver/commands_generator.rb:183:in `run'
	14: from /usr/local/Cellar/fastlane/2.148.1/libexec/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	13: from /usr/local/Cellar/fastlane/2.148.1/libexec/gems/fastlane-2.148.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	12: from /usr/local/Cellar/fastlane/2.148.1/libexec/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	11: from /usr/local/Cellar/fastlane/2.148.1/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	10: from /usr/local/Cellar/fastlane/2.148.1/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 9: from /usr/local/Cellar/fastlane/2.148.1/libexec/gems/fastlane-2.148.1/deliver/lib/deliver/commands_generator.rb:64:in `block (2 levels) in run'
	 8: from /usr/local/Cellar/fastlane/2.148.1/libexec/gems/fastlane-2.148.1/fastlane_core/lib/fastlane_core/configuration/configuration.rb:36:in `create'
	 7: from /usr/local/Cellar/fastlane/2.148.1/libexec/gems/fastlane-2.148.1/fastlane_core/lib/fastlane_core/configuration/configuration.rb:36:in `new'
	 6: from /usr/local/Cellar/fastlane/2.148.1/libexec/gems/fastlane-2.148.1/fastlane_core/lib/fastlane_core/configuration/configuration.rb:66:in `initialize'
	 5: from /usr/local/Cellar/fastlane/2.148.1/libexec/gems/fastlane-2.148.1/fastlane_core/lib/fastlane_core/configuration/configuration.rb:82:in `verify_value_exists'
	 4: from /usr/local/Cellar/fastlane/2.148.1/libexec/gems/fastlane-2.148.1/fastlane_core/lib/fastlane_core/configuration/configuration.rb:82:in `each'
	 3: from /usr/local/Cellar/fastlane/2.148.1/libexec/gems/fastlane-2.148.1/fastlane_core/lib/fastlane_core/configuration/configuration.rb:84:in `block in verify_value_exists'
	 2: from /usr/local/Cellar/fastlane/2.148.1/libexec/gems/fastlane-2.148.1/fastlane_core/lib/fastlane_core/configuration/configuration.rb:328:in `verify_options_key!'
	 1: from /usr/local/Cellar/fastlane/2.148.1/libexec/gems/fastlane-2.148.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/usr/local/Cellar/fastlane/2.148.1/libexec/gems/fastlane-2.148.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Could not find option 'env' in the list of available options: username, app_identifier, app_version, ipa, pkg, build_number, platform, edit_live, use_live_version, metadata_path, screenshots_path, skip_binary_upload, skip_screenshots, skip_metadata, skip_app_version_update, force, overwrite_screenshots, submit_for_review, reject_if_possible, automatic_release, auto_release_date, phased_release, reset_ratings, price_tier, app_rating_config_path, submission_information, team_id, team_name, dev_portal_team_id, dev_portal_team_name, itc_provider, run_precheck_before_submit, precheck_default_rule_level, individual_metadata_items, app_icon, apple_watch_app_icon, copyright, primary_category, secondary_category, primary_first_sub_category, primary_second_sub_category, secondary_first_sub_category, secondary_second_sub_category, trade_representative_contact_information, app_review_information, app_review_attachment_file, description, name, subtitle, keywords, promotional_text, release_notes, privacy_url, apple_tv_privacy_policy, support_url, marketing_url, languages, ignore_language_directory_validation, precheck_include_in_app_purchases, app (FastlaneCore::Interface::FastlaneError)
```

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 10.15.4                                                 |
| Ruby                        | 2.5.8                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.24.2 (Apple Git-127)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.148.1/libexec/bin/fastlane |
| Host                        | Mac OS X 10.15.4 (19E287)                               |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.5/2.5.8/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1f  31 Mar 2020                             |
| Is contained                | false                                                   |
| Is homebrew                 | false                                                   |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 11.4.1                                                  |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_NZ.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.148.1 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.16.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.73.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.0        |
| googleauth                | 0.12.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.5.1        |
| google-cloud-storage      | 1.26.1       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.317.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.1.3        |
| aws-sdk-core              | 3.96.1       |
| aws-sdk-kms               | 1.31.0       |
| aws-sdk-s3                | 1.65.0       |
</details>


*generated on:* **2020-05-21**
</details>

**Comment by liamnichols** [comment]
Thanks for that @milliamp and @DerGary .. I reproduced the same issue with the following:

```
$ bundle exec fastlane deliver -e test
```

Any args other than `-e` seem to be fine... I'll try digging a bit deeper

**Comment by liamnichols** [comment]
Commenting out 

```ruby
global_option('--env STRING[,STRING2]', String, 'Add environment(s) to use with `dotenv`')
```

From the deliver commands_generator.rb file fixes things... I was only defining that so that it appeared in the `fastlane deliver --help` docs but I guess it's having some other side effect that I need to dig into.

I guess the issue with `--env=staging` no longer working is also caused by the basic version of extracting params from `ARGV`:

https://github.com/fastlane/fastlane/blob/2ee51940859de18a3d232377e84004a5d7430eff/fastlane/lib/fastlane/cli_tools_distributor.rb#L131-L141

I guess commander also was able to support the `--key=value` syntax and that was an oversight as I was just matching my implementation to the docs

**Comment by liamnichols** [comment]
Looks like `Configuration` strips global options out of its checks... But this was specific for `:verbose` and would not have included the new `:env`

https://github.com/fastlane/fastlane/blob/2ee51940859de18a3d232377e84004a5d7430eff/fastlane_core/lib/fastlane_core/configuration/configuration.rb#L30-L35

**Comment by liamnichols** [comment]
So I _think_ (and I'm no expert here) that this is potentially a limitation of commander.

Lets take the following example to reproduce the issue:

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'commander-fastlane'
end

ARGV << 'deliver'
ARGV << '-e'
ARGV << 'test'

require 'commander/import'

program :name, 'Foo Bar'
program :version, '1.0.0'
program :description, 'Stupid command that prints foo or bar.'

global_option('--env STRING[,STRING2]', String, 'Global --env arg')

command :deliver do |c|
  c.option '-e STRING', String, 'Something to print'
  
  c.action do |args, options|
    puts "hash: #{options.__hash__}"
    puts "-e: #{options.e}"
    puts "--env: #{options.env}"
  end
end

run!
```

This is the output:

```
hash: {:env=>"test", :e=>"test"}
-e: test
--env: test
```

This is because Commander uses `OptionsParser` under the hood... OptionsParser would usually know how that it needs to stop automatically assigning `-e` as shorthand for `--env` (I think) but because Commander will first parse just the global options, then strip them from `ARGV` and then parse the command's options, it isn't able to do this so we end up with `:env=>"test"`. 

This is then what trips up when calling:

```ruby
FastlaneCore::Configuration.create(deliverfile_options, options.__hash__)
```

We can work around this by adding another check similar to the one used for `--verbose` in https://github.com/fastlane/fastlane/issues/16461#issuecomment-632026585... But I'm not sure if it's the right answer? 

Really It's kind of wrong to be declaring `--env` as a global_option in the commands_generator entirely, since this is supposed to always be stripped from in cli_tools_distributor anyway.. But without it, we're not able to include the arg in the help comments, unless there is another way that I'm aware of?

I see three options:

1. Remove the `global_option` and add it to help some other way (or not at all)
2. Add the validation work around in configuration.rb
3. Rollback the change

----

As for the `--env=value` vs `--env value`... We can update the logic for detecting `env_cl_param` to support it... Maybe there is a method I can pull from Commander or something to help.

cc @janpio

**Comment by alubeck** [comment]
Yes @liamnichols it was about `--env=foo`. So basically `fastlane some_lane_using_dotenv --env=foo`

**Comment by liamnichols** [comment]
Since this got closed it looks like it might not have been as urgent but if anybody does come with issues, here are the workarounds for the two issues:

1. Use `--env <STRING>` instead of `--env=<STRING>`
2. Use `DELIVER_TEAM_NAME=<STRING> fastlane deliver -other -args` instead of `fastlane deliver -e <STRING> --other --args` (cc @milliamp, @DerGary)

**Comment by sbourji** [comment]
I'm running into the same issue 
fastlane deliver --ipa xxxxxxc.ipa --submit_for_)review -u username  -e "XXXXX XXXXX, XX"
