### ISSUE TITLE
Cannot install plugins

### ISSUE THREAD

**Issue by treymerkley** [fastlane/fastlane#16473]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm getting a user error installing any plugin. I initially tested with appcenter, but versioning has the same issue.

##### Command executed

`fastlane add_plugin appcenter --verbose`
`fastlane update_plugins`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[trey@citron fastlane]$ fastlane add_plugin appcenter --verbose
 [✔] 🚀 
DEBUG [2020-05-18 17:07:04.09]: Checking if there are any plugins that should be loaded...
ERROR [2020-05-18 17:07:04.09]: It seems like you wanted to load some plugins, however they couldn't be loaded
ERROR [2020-05-18 17:07:04.09]: Please follow the troubleshooting guide: https://docs.fastlane.tools/plugins/plugins-troubleshooting/
Successfully loaded Appfile at path '/home/trey/git/org/my_project/my_project-android/fastlane/Appfile'
- package_name: 'com.my_project.app'
-------
DEBUG [2020-05-18 17:07:04.25]: Adding line: gem 'fastlane-plugin-appcenter'
INFO [2020-05-18 17:07:04.25]: Plugin 'fastlane-plugin-appcenter' was added to './Pluginfile'
WARN [2020-05-18 17:07:04.25]: Make sure to commit your Gemfile, Gemfile.lock and Pluginfile to version control
Installing plugin dependencies...
INFO [2020-05-18 17:07:04.25]: $ bundle install && echo 'Successfully installed plugins'
Using CFPropertyList 3.0.2
Using public_suffix 2.0.5
Using addressable 2.7.0
Using atomos 0.1.3
Using aws-eventstream 1.1.0
Using aws-partitions 1.317.0
Using aws-sigv4 1.1.3
Using jmespath 1.4.0
Using aws-sdk-core 3.96.1
Using aws-sdk-kms 1.31.0
Using aws-sdk-s3 1.65.0
Using babosa 1.0.3
Using bundler 1.17.3
Using claide 1.0.3
Using colored 1.2
Using colored2 3.1.2
Using highline 1.7.10
Using commander-fastlane 4.4.6
Using declarative 0.0.10
Using declarative-option 0.1.0
Using digest-crc 0.5.1
Using unf_ext 0.0.7.7
Using unf 0.1.4
Using domain_name 0.5.20190701
Using dotenv 2.7.5
Using emoji_regex 1.0.1
Using excon 0.73.0
Using multipart-post 2.0.0
Using faraday 1.0.1
Using http-cookie 1.0.3
Using faraday-cookie_jar 0.0.6
Using faraday_middleware 1.0.0
Using fastimage 2.1.7
Using gh_inspector 1.1.3
Using jwt 2.1.0
Using memoist 0.16.2
Using multi_json 1.14.1
Using os 1.1.0
Using signet 0.14.0
Using googleauth 0.12.0
Using httpclient 2.8.3
Using mini_mime 1.0.2
Using uber 0.1.0
Using representable 3.0.4
Using retriable 3.1.2
Using google-api-client 0.38.0
Using google-cloud-env 1.3.1
Using google-cloud-errors 1.0.0
Using google-cloud-core 1.5.0
Using google-cloud-storage 1.26.1
Using json 2.3.0
Using mini_magick 4.10.1
Using multi_xml 0.6.0
Using plist 3.5.0
Using rubyzip 1.3.0
Using security 0.1.3
Using naturally 2.2.0
Using simctl 1.6.8
Using slack-notifier 2.3.2
Using terminal-notifier 2.0.0
Using unicode-display_width 1.7.0
Using terminal-table 1.8.0
Using tty-screen 0.7.1
Using tty-cursor 0.7.1
Using tty-spinner 0.9.3
Using word_wrap 1.0.0
Using nanaimo 0.2.6
Using xcodeproj 1.16.0
Using rouge 2.0.7
Using xcpretty 0.3.0
Using xcpretty-travis-formatter 1.0.0
Using fastlane 2.148.1
Bundle complete! 1 Gemfile dependency, 72 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Successfully installed plugins
[trey@citron fastlane]$ fastlane update_plugins
 [✔] 🚀 
[17:07:24]: It seems like you wanted to load some plugins, however they couldn't be loaded
[17:07:24]: Please follow the troubleshooting guide: https://docs.fastlane.tools/plugins/plugins-troubleshooting/
Updating plugin dependencies...

[!] No plugins are installed
[trey@citron fastlane]$ fastlane update_plugins --verbose
 [✔] 🚀 
DEBUG [2020-05-18 17:07:30.46]: Checking if there are any plugins that should be loaded...
ERROR [2020-05-18 17:07:30.46]: It seems like you wanted to load some plugins, however they couldn't be loaded
ERROR [2020-05-18 17:07:30.46]: Please follow the troubleshooting guide: https://docs.fastlane.tools/plugins/plugins-troubleshooting/
Successfully loaded Appfile at path '/home/trey/git/org/my_project/my_project-android/fastlane/Appfile'
- package_name: 'com.my_project.app'
-------
Updating plugin dependencies...
Traceback (most recent call last):
        16: from /home/trey/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
        15: from /home/trey/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
        14: from /home/trey/.rvm/gems/ruby-2.6.3/bin/fastlane:23:in `<main>'
        13: from /home/trey/.rvm/gems/ruby-2.6.3/bin/fastlane:23:in `load'
        12: from /home/trey/.rvm/gems/ruby-2.6.3/gems/fastlane-2.148.1/bin/fastlane:23:in `<top (required)>'
        11: from /home/trey/.rvm/gems/ruby-2.6.3/gems/fastlane-2.148.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
        10: from /home/trey/.rvm/gems/ruby-2.6.3/gems/fastlane-2.148.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
         9: from /home/trey/.rvm/gems/ruby-2.6.3/gems/fastlane-2.148.1/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
         8: from /home/trey/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
         7: from /home/trey/.rvm/gems/ruby-2.6.3/gems/fastlane-2.148.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
         6: from /home/trey/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
         5: from /home/trey/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
         4: from /home/trey/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
         3: from /home/trey/.rvm/gems/ruby-2.6.3/gems/fastlane-2.148.1/fastlane/lib/fastlane/commands_generator.rb:321:in `block (2 levels) in run'
         2: from /home/trey/.rvm/gems/ruby-2.6.3/gems/fastlane-2.148.1/fastlane/lib/fastlane/plugins/plugin_manager.rb:195:in `update_dependencies!'
         1: from /home/trey/.rvm/gems/ruby-2.6.3/gems/fastlane-2.148.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/home/trey/.rvm/gems/ruby-2.6.3/gems/fastlane-2.148.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': No plugins are installed (FastlaneCore::Interface:
:FastlaneError)                                                                                                                                                              
        16: from /home/trey/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
        15: from /home/trey/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
        14: from /home/trey/.rvm/gems/ruby-2.6.3/bin/fastlane:23:in `<main>'
        13: from /home/trey/.rvm/gems/ruby-2.6.3/bin/fastlane:23:in `load'
        12: from /home/trey/.rvm/gems/ruby-2.6.3/gems/fastlane-2.148.1/bin/fastlane:23:in `<top (required)>'
        11: from /home/trey/.rvm/gems/ruby-2.6.3/gems/fastlane-2.148.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
        10: from /home/trey/.rvm/gems/ruby-2.6.3/gems/fastlane-2.148.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
         9: from /home/trey/.rvm/gems/ruby-2.6.3/gems/fastlane-2.148.1/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
         8: from /home/trey/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
         7: from /home/trey/.rvm/gems/ruby-2.6.3/gems/fastlane-2.148.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
         6: from /home/trey/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
         5: from /home/trey/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
         4: from /home/trey/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
         3: from /home/trey/.rvm/gems/ruby-2.6.3/gems/fastlane-2.148.1/fastlane/lib/fastlane/commands_generator.rb:321:in `block (2 levels) in run'
         2: from /home/trey/.rvm/gems/ruby-2.6.3/gems/fastlane-2.148.1/fastlane/lib/fastlane/plugins/plugin_manager.rb:195:in `update_dependencies!'
         1: from /home/trey/.rvm/gems/ruby-2.6.3/gems/fastlane-2.148.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/home/trey/.rvm/gems/ruby-2.6.3/gems/fastlane-2.148.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] No plugins are installed (FastlaneCore::Interf
ace::FastlaneError)                                                                                                                                                          
[trey@citron fastlane]$ </pre>
</details>

### Environment

<details>
  <pre> [trey@citron fastlane]$ fastlane env
 [✔] 🚀 
[17:19:34]: Generating fastlane environment output, this might take a few seconds...
cat: /etc/issue.net: No such file or directory
[17:19:34]: It seems like you wanted to load some plugins, however they couldn't be loaded
[17:19:34]: Please follow the troubleshooting guide: https://docs.fastlane.tools/plugins/plugins-troubleshooting/
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                                                                        |
| --------------------------- | ------------------------------------------------------------------------------------------------------------ |
| OS                          | Linux citron 5.4.39-1-MANJARO #1 SMP PREEMPT Wed May 6 10:36:44 UTC 2020 x86_64 GNU/Linux                    |
| Ruby                        | 2.6.3                                                                                                        |
| Bundler?                    | true                                                                                                         |
| Git                         | git version 2.26.2                                                                                           |
| Installation Source         | ~/.rvm/gems/ruby-2.6.3/bin/fastlane                                                                          |
| Host                        | Linux citron 5.4.39-1-MANJARO #1 SMP PREEMPT Wed May 6 10:36:44 UTC 2020 x86_64 GNU/Linux (5.4.39-1-MANJARO) |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.3/lib                                                                                 |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                                                                                  |
| Is contained                | false                                                                                                        |
| Is homebrew                 | false                                                                                                        |
| Is installed via Fabric.app | false                                                                                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             | 🚫 |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)
desc "test build"
lane :beta do
  # Adjust the `build_type` and `flavor` params as needed to build the right APK for your setup
  gradle(
    task: 'assemble',
    build_type: 'Release'
  )

    # ...
end

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  # # desc "Submit a new Beta Build to Crashlytics Beta"
  # lane :beta do
  #   gradle(task: "clean assembleRelease")
  #   crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  # end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

```
</details>

<details><summary>`./Appfile`</summary>

```ruby
json_key_file("") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("com.my_project.app") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.147.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.17.3       |
| etc                       | 1.0.1        |
| forwardable               | 1.2.0        |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.317.0      |
| aws-sigv4                 | 1.1.3        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.96.1       |
| aws-sdk-kms               | 1.31.0       |
| aws-sdk-s3                | 1.65.0       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.5.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.73.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 1.0.1        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.1.0        |
| signet                    | 0.14.0       |
| googleauth                | 0.12.0       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.1       |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.16.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2020-05-18**
</details>
[17:19:34]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[17:19:34]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅

#######################################################################
# fastlane 2.148.1 is available. You are on 2.147.0.
# You should use the latest version.
# Please update using `bundle update fastlane`.
#######################################################################

2.148.1 Improvements for plugin searching
* [fastlane] fix searching for plugins where the name contains “action” in it (#16470) via Josh Holtz

2.148.0 Improvements
* [deliver] add fix for app_version and build_number matching (#16091) via onurpolattimur
* [fastlane] load additional .env files from within CLIToolsDistributor (#16096) via Liam Nichols
* [match] improve match macOS support (#16456) via Davide De Rosa
* [gym] move AppStoreInfo.plist to build output directory if generated … (#16133) via Ashton Williams
* [actions] push_to_git_remote - raise an error if get current branch failed (#16141) via Jierong Li
* [deliver] fix crash when metadata_path is outside of the fastlane path (#16146) via Bruno Virlet
* [Fastlane.swift] add options to beforeAll (#16220) via Niil Öhlin
* [supply] added `in_app_update_priority` option to set the InAppUpdatePriority … (#16452) via jomisj
* [Ruby 2.7] fix deprecated warnings (#16409) via Jakub Kašpar
* [snapshot] fix warning in SnapshotHelper.swift (#16244) via Cédric Luthi
* [sigh][match] add :fail_on_name_taken in sigh, use in match (#16281) via Michal Laskowski
* [snapshot] erase simulator only when erase_simulator is true (#16299) via Theodore Gonzalez
* [spaceship][pilot] expire TestFlight Builds (#16332) via Steven Sherry
* [gym] add info on passing plist into export_options on gym (#16345) via Bahadır Öncel
* [doc][crashlytics] remove duplicated deprecation message (#16363) via JAEHYUN OH
* [scan] add `only_test_configurations` and `skip_test_configurations` options for use with test plans (#16367) via Rob Nadin
* [snapshot] add -only-testing and -skip-testing options from scan (#16312) via Jean Mainguy
* [screengrab] adding locales in all the paths where screenshots could be saved (#16370) via Nicolas Brosy
* [action] upload_symbols_to_crashlytics include Path Suggested by Carthage Instructions (#16401) via Stefan Herold
* [action] dd missing env_names to swiftlint action (#16445) via Tóth Balázs

Please update using `bundle update fastlane`
[trey@citron fastlane]$ </pre>
</details>

The first output will show 2.148.1 and the second 2.147. That's intentional, I was testing to see if an update broke it. While I'm on Linux, the app is an Android app and App Center shouldn't really need Xcode, so the lack of it on my system _shouldn't_ be a problem. Let me know what you need.

Thanks!

**Comment by janpio** [comment]
From the link in the output: https://docs.fastlane.tools/plugins/plugins-troubleshooting/#use-bundle-exec

Does this help?

**Comment by treymerkley** [comment]
It ended up being that my file tree was broken, thanks!
