### ISSUE TITLE
Gradlew file path is shown in full

### ISSUE THREAD

**Issue by coolraj80** [fastlane/fastlane#16474]
### Question Checklist

- [Y ] Updated fastlane to the latest version
- [ Y] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ Y] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ Y] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

gradlew

no

no

#### Question Description
Hi, i'm using Fastlane in GitLab for CI/CD.
The output of the build/test jobs are displaying the following:
 **$ /builds/path1/path2/path3/path4/project-name/gradlew assembleuat -p .**

Is there a way to hide the gradlew path in the output, and only display:
**$ gradlew assembleuat -p .**

Below is my FastFile content:

> opt_out_usage
> 
> lane :UAT_Build do
>   gradle(
>     task: 'assemble',
>     build_type: 'uat'
>   )
> end
> 
> lane :UAT_Tests do
>   gradle(
>     task: 'test',
>     build_type: 'uat'
>   )
> end

Thank you.

**Comment by coolraj80** [comment]
Please find below the output of fastlane env:

# fastlane env
[✔] 🚀
[02:40:01]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[02:40:02]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                         |
| --------------------------- | ------------------------------------------------------------- |
| OS                          | debian_based buster/sid                                       |
| Ruby                        | 2.5.1                                                         |
| Bundler?                    | false                                                         |
| Git                         | git version 2.17.1                                            |
| Installation Source         | /usr/local/bin/fastlane                                       |
| Host                        | Ubuntu 18.04.4 LTS debian_based buster/sid (4.19.76-linuxkit) |
| Ruby Lib Dir                | /usr/lib                                                      |
| OpenSSL Version             | OpenSSL 1.1.1  11 Sep 2018                                    |
| Is contained                | false                                                         |
| Is homebrew                 | false                                                         |
| Is installed via Fabric.app | false                                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.146.1 | 🚫 Update available |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.16.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.73.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.0        |
| googleauth                | 0.12.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.5.1        |
| google-cloud-storage      | 1.26.1       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.312.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.1.3        |
| aws-sdk-core              | 3.95.0       |
| aws-sdk-kms               | 1.31.0       |
| aws-sdk-s3                | 1.64.0       |
| ipaddr                    | 1.2.0        |
| openssl                   | 2.1.1        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| psych                     | 3.0.2        |
| webrick                   | 1.4.2        |
</details>


*generated on:* **2020-05-19**
</details>

**Comment by janpio** [comment]
I don't think that is an option right now.

Why are you interested in this?
