### ISSUE TITLE
team_name vs itc_team_name

### ISSUE THREAD

**Issue by sultanmyrza** [fastlane/fastlane#16485]
### Question Checklist

- [+] Updated fastlane to the latest version
- [+] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [+] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [+] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

#### Question Description

I'm new to fastlane and don't know difference between
```
team_name
team_id
```
and 
```
itc_team_name
itc_team_id
```

I know `team_name, team_id` can be obtained from here https://developer.apple.com/account/#/membership

But 

1. where I get `itc_team_name, itc_team_id`
2. is `team_name` always same as `itc_team_name`
3. if not why? and where to get `itc_team_name` (question 1)

**Comment by sultanmyrza** [comment]
Okay I have partial answer to my questions #2 `team_name` might be same as `itc_team_name` but `team_id` != `itc_team_id` 

I found out when run `bundle exec fastlane upload_to_testflight`

```
 The request could not be completed because:
        Could not set team ID to '895N****8K', only found the following available teams:

- 121225512 (B******d Incorporated)
- 121376417 (Sultanmyrza Kasymbekov)
- 119409974 (Tilek Mamutov)
```

**Comment by svanzoest** [comment]
I described this at https://github.com/fastlane/fastlane/issues/10796#issuecomment-352952685
