### ISSUE TITLE
Naming files for screenshot uploads

### ISSUE THREAD

**Issue by cupcakearmy** [fastlane/fastlane#16483]
### Question Checklist

- [x] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Naming files for screenshot uploads

#### Question Description

So... We create our screens for the app/play store in house, but they are a bit more then simple screenshots of the actual app, so they are made by our designers.

Now we want to upload those in a pipeline. I don't know how to name the screenshot files... i did not find anything in the docs besides [this issue reply](https://github.com/fastlane/fastlane/issues/9340#issuecomment-305842535) and that [according to the official](https://docs.fastlane.tools/actions/deliver/#uploading-screenshots-for-ipad-pro-129-inch-3rd-generation) docs you can use `ipadPro129`, but what about other devices? how should they be named? 

Maybe I've missed something but there seems to be no documentation about naming schemes for either the play or app store.

Thanks!

**Comment by max-ott** [comment]
All other screenshots have specific sizes so no special naming is required. Only for the 3rd generation iPad Pro screenshots, you'll need to include that in the filename.

**Comment by cupcakearmy** [comment]
I see, that makes sense! Smart.

Thank you 👍
