### ISSUE TITLE
Error: Could not find option 'env' in the list of available options: ...

### ISSUE THREAD

**Issue by sam-moshenko** [fastlane/fastlane#16487]
### Issue Description
I receive this error in azure pipelines:

> [!] Could not find option 'env' in the list of available options: ...

It worked before. The strange thing is that nothing seem to be changed in the project and azure pipelines, just some images updated and version increased. I don't even know where to search for the reason of the error. I can't find what is the 'env' option, and why it broke.

##### Command executed
fastlane deliver --force -u *** -a *** -i /Users/runner/runners/2.168.2/work/1/s/output/iphoneos/Release/***.ipa -j ios -m /Users/runner/runners/2.168.2/work/1/s/metadata/ --skip_screenshots true -e ***

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>/usr/local/opt/ruby/bin/gem install fastlane
(node:5844) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:5844) Warning: Use Cipheriv for counter mode of aes-256-ctr
Successfully installed fastlane-2.148.1
Parsing documentation for fastlane-2.148.1
Installing ri documentation for fastlane-2.148.1
Done installing documentation for fastlane after 20 seconds
1 gem installed
/usr/local/opt/ruby/bin/gem update fastlane -i /Users/runner/.gem-cache
Updating installed gems
Nothing to update
fastlane deliver --force -u *** -a *** -i /Users/runner/runners/2.168.2/work/1/s/output/iphoneos/Release/***.ipa -j ios -m /Users/runner/runners/2.168.2/work/1/s/metadata/ --skip_screenshots true -e ***
[15:10:55]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[15:10:59]: Sending anonymous analytics information
[15:10:59]: Learn more at https://docs.fastlane.tools/#metrics
[15:10:59]: No personal or sensitive data is sent.
[15:10:59]: You can disable this by adding `opt_out_usage` at the top of your Fastfile

[!] Could not find option 'env' in the list of available options: username, app_identifier, app_version, ipa, pkg, build_number, platform, edit_live, use_live_version, metadata_path, screenshots_path, skip_binary_upload, skip_screenshots, skip_metadata, skip_app_version_update, force, overwrite_screenshots, submit_for_review, reject_if_possible, automatic_release, auto_release_date, phased_release, reset_ratings, price_tier, app_rating_config_path, submission_information, team_id, team_name, dev_portal_team_id, dev_portal_team_name, itc_provider, run_precheck_before_submit, precheck_default_rule_level, individual_metadata_items, app_icon, apple_watch_app_icon, copyright, primary_category, secondary_category, primary_first_sub_category, primary_second_sub_category, secondary_first_sub_category, secondary_second_sub_category, trade_representative_contact_information, app_review_information, app_review_attachment_file, description, name, subtitle, keywords, promotional_text, release_notes, privacy_url, apple_tv_privacy_policy, support_url, marketing_url, languages, ignore_language_directory_validation, precheck_include_in_app_purchases, app
##[error]Error: fastlane failed with return code: 1
Finishing: Publish to the App Store Production track
</pre>
</details>

**Comment by janpio** [comment]
Possibly related: https://github.com/fastlane/fastlane/issues/16461

**Comment by sbourji** [comment]
Soory I opened  issue 16901, instead commenting here. I'm getting the same issue, I have been using this method for the past 2 years without issue. I did log the env in my posting
