### ISSUE TITLE
Arabic issue with imagemagick 

### ISSUE THREAD

**Issue by X901** [fastlane/fastlane#16497]
Hi , 
This is 1st time I tried Fastlane
I'm interesting on Snapshot, that way I use Fastlane
after I follow the instruction
everything finally working!
Final step was to add Arabic text but unfortunately, it didn't support Arabic correctly
see this image: https://a.cl.ly/yAu2EDo0

Then I was searching here and found that other people had the same issue [#7522](https://github.com/fastlane/fastlane/issues/7522)

Also, someone gives PR(#[8131](https://github.com/fastlane/fastlane/pull/8131
)) to fix this issue but it didn't approve 

Could you please support Arabic correctly?

I was surprised how this issue is known since 2016 and it didn't fix until now =(

**Comment by X901** [comment]
I found solution it work for now
on old days some application didn't suppourt arabic like Photoshop
so we used to use website or tools to reverse the text so it display correctly
one of website is this http://www.arabic-keyboard.org/photoshop-arabic/

when you write the text on the 1st box correctly 
the result will be reversed 

for example 
if you write 
"أهلا وسهلا"
it will become 
"ﻼﻬﺳﻭ ﻼﻫﺃ"

When you write it like this "ﻼﻬﺳﻭ ﻼﻫﺃ" on `title.strings` file
after it completed adding frames to images
the result will be correctly "أهلا وسهلا"

not a perfect solution , but it's a work around to make it work correctly at least .

**Comment by vaurinoey** [comment]
Thank you for the information and advice!

**Comment by fatihyildizhan** [comment]
@X901 Could you find a better solution? Also, are you able to generate screenshots? I have a problem with it. You may see the details from here: #16604

**Comment by X901** [comment]
> @X901 Could you find a better solution? Also, are you able to generate screenshots? I have a problem with it. You may see the details from here: #16604

with Arabic yup I can generate the images without any issue 

If I don't use the website with Arabic language , it will generate the images without the text as what happend with out with Japanese language

Unfortunately I don't find any other solution
