### ISSUE TITLE
fastlane failed to receive a connection from the FastlaneRunner binary after 5 seconds, shutting down

### ISSUE THREAD

**Issue by xlsmearlx** [fastlane/fastlane#16493]
### New Issue Checklist

- [x] Updated Fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Fastlane is failing while trying to run any lane.

##### Command executed

`bundle exec fastlane customLane --verbose`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> ➜  ios git:(feature/FastlaneSwift) ✗ bundle exec fastlane customLane --verbose                 
[✔] 🚀 
DEBUG [2020-05-22 14:40:14.03]: Checking if there are any plugins that should be loaded...
INFO [2020-05-22 14:40:14.19]: loading manifest: /Users/samuellagunes/.rvm/gems/ruby-2.7.0/gems/fastlane-2.148.1/fastlane/swift/upgrade_manifest.json
DEBUG [2020-05-22 14:40:14.28]: No missing groups found, so we don't need to worry about adding new groups
DEBUG [2020-05-22 14:40:14.28]: Actions.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.56/0.9.56
DEBUG [2020-05-22 14:40:14.28]: Fastlane.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.76/0.9.76
DEBUG [2020-05-22 14:40:14.28]: DeliverfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.19/0.9.19
DEBUG [2020-05-22 14:40:14.28]: GymfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.18/0.9.18
DEBUG [2020-05-22 14:40:14.28]: MatchfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.17/0.9.17
DEBUG [2020-05-22 14:40:14.28]: Plugins.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.56/0.9.56
DEBUG [2020-05-22 14:40:14.28]: PrecheckfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.11/0.9.11
DEBUG [2020-05-22 14:40:14.28]: ScanfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.29/0.9.29
DEBUG [2020-05-22 14:40:14.28]: ScreengrabfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.13/0.9.13
DEBUG [2020-05-22 14:40:14.28]: SnapshotfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.9/0.9.9
DEBUG [2020-05-22 14:40:14.28]: LaneFileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2020-05-22 14:40:14.28]: ControlCommand.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2020-05-22 14:40:14.28]: RubyCommand.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2020-05-22 14:40:14.28]: RubyCommandable.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2020-05-22 14:40:14.28]: Runner.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2020-05-22 14:40:14.28]: SocketClient.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2020-05-22 14:40:14.28]: SocketClientDelegateProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2020-05-22 14:40:14.28]: SocketResponse.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2020-05-22 14:40:14.28]: ArgumentProcessor.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2020-05-22 14:40:14.28]: main.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2020-05-22 14:40:14.28]: RunnerArgument.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2020-05-22 14:40:14.29]: Checking for new user-provided tool configuration files
INFO [2020-05-22 14:40:14.29]: FastlaneSwiftRunner project is up-to-date
DEBUG [2020-05-22 14:40:14.30]: Waiting for 5 seconds for a connection from FastlaneRunner
INFO [2020-05-22 14:40:14.55]: $ ./fastlane/FastlaneRunner lane customLane logMode verbose swiftServerPort 2000 > /dev/null
/Users/samuellagunes/.rvm/gems/ruby-2.7.0/gems/fastlane-2.148.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/samuellagunes/.rvm/gems/ruby-2.7.0/gems/fastlane-2.148.1/fastlane_core/lib/fastlane_core/ui/errors/fastlane_error.rb:9: warning: The called method `initialize' is defined here
#<Thread:0x00007f8ca28c09e8 /Users/samuellagunes/.rvm/gems/ruby-2.7.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/swift_lane_manager.rb:220 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        5: from /Users/samuellagunes/.rvm/gems/ruby-2.7.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/swift_lane_manager.rb:223:in `block in start_socket_thread'
        4: from /Users/samuellagunes/.rvm/gems/ruby-2.7.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/server/socket_server.rb:38:in `start'
        3: from /Users/samuellagunes/.rvm/gems/ruby-2.7.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/server/socket_server.rb:147:in `listen'
        2: from /Users/samuellagunes/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/timeout.rb:110:in `timeout'
        1: from /Users/samuellagunes/.rvm/gems/ruby-2.7.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/server/socket_server.rb:148:in `block in listen'
/Users/samuellagunes/.rvm/gems/ruby-2.7.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/server/socket_server.rb:148:in `accept': execution expired (Timeout::Error)
        5: from /Users/samuellagunes/.rvm/gems/ruby-2.7.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/swift_lane_manager.rb:223:in `block in start_socket_thread'
        4: from /Users/samuellagunes/.rvm/gems/ruby-2.7.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/server/socket_server.rb:38:in `start'
        3: from /Users/samuellagunes/.rvm/gems/ruby-2.7.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/server/socket_server.rb:146:in `listen'
        2: from /Users/samuellagunes/.rvm/gems/ruby-2.7.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/server/socket_server.rb:151:in `rescue in listen'
        1: from /Users/samuellagunes/.rvm/gems/ruby-2.7.0/gems/fastlane-2.148.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/samuellagunes/.rvm/gems/ruby-2.7.0/gems/fastlane-2.148.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': fastlane failed to receive a connection from the FastlaneRunner binary after 5 seconds, shutting down (FastlaneCore::Interface::FastlaneError)
WARN [2020-05-22 14:40:19.30]: Lane Context:
INFO [2020-05-22 14:40:19.30]: {:LANE_NAME=>"customLane"}
ERROR [2020-05-22 14:40:19.30]: fastlane failed to receive a connection from the FastlaneRunner binary after 5 seconds, shutting down
ERROR [2020-05-22 14:40:19.30]: fastlane finished with errors
Traceback (most recent call last):
        5: from /Users/samuellagunes/.rvm/gems/ruby-2.7.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/swift_lane_manager.rb:223:in `block in start_socket_thread'
        4: from /Users/samuellagunes/.rvm/gems/ruby-2.7.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/server/socket_server.rb:38:in `start'
        3: from /Users/samuellagunes/.rvm/gems/ruby-2.7.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/server/socket_server.rb:147:in `listen'
        2: from /Users/samuellagunes/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/timeout.rb:110:in `timeout'
        1: from /Users/samuellagunes/.rvm/gems/ruby-2.7.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/server/socket_server.rb:148:in `block in listen'
/Users/samuellagunes/.rvm/gems/ruby-2.7.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/server/socket_server.rb:148:in `accept': execution expired (Timeout::Error)
        5: from /Users/samuellagunes/.rvm/gems/ruby-2.7.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/swift_lane_manager.rb:223:in `block in start_socket_thread'
        4: from /Users/samuellagunes/.rvm/gems/ruby-2.7.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/server/socket_server.rb:38:in `start'
        3: from /Users/samuellagunes/.rvm/gems/ruby-2.7.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/server/socket_server.rb:146:in `listen'
        2: from /Users/samuellagunes/.rvm/gems/ruby-2.7.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/server/socket_server.rb:151:in `rescue in listen'
        1: from /Users/samuellagunes/.rvm/gems/ruby-2.7.0/gems/fastlane-2.148.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/samuellagunes/.rvm/gems/ruby-2.7.0/gems/fastlane-2.148.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': \e[31m[!] fastlane failed to receive a connection from the FastlaneRunner binary after 5 seconds, shutting down\e[0m (FastlaneCore::Interface::FastlaneError) </pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.4                                     |
| Ruby                        | 2.7.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.rvm/gems/ruby-2.7.0/bin/fastlane         |
| Host                        | Mac OS X 10.15.4 (19E287)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.7.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.1b  26 Feb 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.5                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

```ruby
// This file contains the fastlane.tools configuration
// You can find the documentation at https://docs.fastlane.tools
//
// For a list of all available actions, check out
//
//     https://docs.fastlane.tools/actions
//

import Foundation

class Fastfile: LaneFile {
	func customLane() {
	desc("Description of what the lane does")
		// add actions here: https://docs.fastlane.tools/actions
	}

	func testLane() {
		desc("This is a lane")
		// scan(scheme: "DataComponent", clean: true, codeCoverage: true)
    }
}

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.148.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| CFPropertyList            | 3.0.2        |
| concurrent-ruby           | 1.1.6        |
| i18n                      | 0.9.5        |
| minitest                  | 5.14.1       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.7        |
| activesupport             | 4.2.11.3     |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| httpclient                | 2.8.3        |
| json                      | 2.3.0        |
| algoliasearch             | 1.27.2       |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.320.0      |
| aws-sigv4                 | 1.1.3        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.96.1       |
| aws-sdk-kms               | 1.31.0       |
| aws-sdk-s3                | 1.66.0       |
| babosa                    | 1.0.3        |
| bundler                   | 2.1.2        |
| claide                    | 1.0.3        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| netrc                     | 0.11.0       |
| ffi                       | 1.12.2       |
| ethon                     | 0.12.0       |
| typhoeus                  | 1.4.0        |
| cocoapods-core            | 1.9.2        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.3.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| cocoapods-trunk           | 1.5.0        |
| cocoapods-try             | 1.2.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.16.0       |
| cocoapods                 | 1.9.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.5.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.73.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 1.0.1        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.1.0        |
| signet                    | 0.14.0       |
| googleauth                | 0.12.0       |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.1       |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| xcresult                  | 0.2.1        |
| xcov                      | 1.7.3        |
</details>

*generated on:* **2020-05-22**
</details> </pre>
</details>

### Fastfile.swift
<details> 
<pre>
import Foundation

class Fastfile: LaneFile {
	func customLane() {
	desc("Description of what the lane does")
		// add actions here: https://docs.fastlane.tools/actions
	}
}
</pre>
</details> 

### Attachments
Also I noticed that every time I executed any lane, an instance of FastlaneRunner remained in the activity monitor.

![Screen Shot 2020-05-22 at 1 18 17 PM](https://user-images.githubusercontent.com/1068598/82704336-f030fd00-9c3a-11ea-9317-5d6e3cd02876.png)

### UPDATE
After running `ps -A | grep -i fastlane` and kill every Fastlane process it started working again. But every time a run `bundle exec fastlane laneName` a new process is added to the list.

<img width="1039" alt="Screen Shot 2020-05-22 at 3 47 09 PM" src="https://user-images.githubusercontent.com/1068598/82708307-8bc66b80-9c43-11ea-9f99-a4564b2f1366.png">

**Comment by minuscorp** [comment]
Does some application work on TCP 2000 port? It might be the issue here, you can check it out in Mac with `sudo lsof -i -n -P | grep TCP` and lookup for port 2000
