### ISSUE TITLE
Could not find offset_information  Apple iPad Pro (12.9-inch) (4th generation)

### ISSUE THREAD

**Issue by smit1212** [fastlane/fastlane#16513]
While taking iPad Pro screenshots I'm getting below errors.

Couldn't find template for screenshot type 'Apple iPad Pro (12.9-inch) (4th generation) Space Gray'

Tried looking for offset information for 'portrait', Apple iPad Pro (12.9-inch) (4th generation) in '/Users/xxxxx/.fastlane/frameit/latest/offsets.json'
[00:30:57]: Could not find offset_information for './xxxx-gray.png'

**Comment by smit1212** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.4                                     |
| Ruby                        | 2.5.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.rvm/gems/ruby-2.5.0/bin/fastlane         |
| Host                        | Mac OS X 10.15.4 (19E287)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.5.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.0g  2 Nov 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.5                                        |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.148.1 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| executable-hooks          | 1.4.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.1       |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.320.0      |
| aws-sigv4                 | 1.1.3        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.96.1       |
| aws-sdk-kms               | 1.31.0       |
| aws-sdk-s3                | 1.66.0       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.5.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.73.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 1.0.1        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.1.0        |
| signet                    | 0.14.0       |
| googleauth                | 0.12.0       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.1       |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.16.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>


*generated on:* **2020-05-26**
</details>

**Comment by minuscorp** [comment]
Hmmmmm 🤔 
https://github.com/fastlane/fastlane/blob/9075249574c33b0f28735ac2003078d8db52260d/frameit/lib/frameit/device_types.rb#L131

**Comment by Nereidast** [comment]
Some issues might be covered under the Apple Limited Warranty, AppleCare+, or consumer law, in which case there’s no fee to replace your product. If your iPad has accidental damage, you’ll pay an AppleCare+ service fee, as shown below.

**Comment by minuscorp** [comment]
Some example screenshots would be useful for us to try to understand the issue

**Comment by REKURDennis** [comment]
I get the same error if I try to frame an iPad Pro screenshot. 
It seems, that the code searchs for "Apple iPad Pro (12.9-inch) (4th generation)", but according to https://github.com/fastlane/frameit-frames/tree/gh-pages/latest it does not exist.

**Comment by minuscorp** [comment]
It is not updated since 7 months ago, don't think to be related

**Comment by REKURDennis** [comment]
Exactly that is the problem. In https://github.com/fastlane/fastlane/commit/6fccfc062bae9cb1e435923ec5982efac78db474#diff-9a7418bad03e74c379cc4e6044fc26d4 you can see, that for 23 days frameit trys to use the frame "'Apple iPad Pro (12.9-inch) (4th generation) ...'" but in https://github.com/fastlane/frameit-frames/tree/gh-pages/latest such a frame has not been added.

As workaround you can go to your local frames folder copy the "Apple iPad Pro (12.9-inch) (3rd generation)" files rename the copy "Apple iPad Pro (12.9-inch) (4th generation)" and also modify the "offsets.json"-file accordingly.

**Comment by thislooksfun** [comment]
I can confirm, getting this right now. Running `frameit` is giving me

```
Couldn't find template for screenshot type 'Apple iPad Pro (12.9-inch) (4th generation) Space Gray'
Please run `fastlane frameit download_frames` to download the latest frames
```

To reproduce, just run `snapshot` with the device `iPad Pro (12.9-inch) (4th generation)`, then run `frameit`.

**Comment by renanccastro** [comment]
Would be good to have this included! We are also having the same problem.
