### ISSUE TITLE
Unable to upload IPA resigned with fastlane using wildcard profile

### ISSUE THREAD

**Issue by dennisfrett** [fastlane/fastlane#16515]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm using this app as an example: https://github.com/aTinyFish/WordOfTheDay.

When exporting it for App Store from Xcode using a wildcard profile for both the main app and the plugin, the `jtool --ent -arch arm64 /path/to/WordOfTheDay` contains:
```
...
	<key>application-identifier</key>
	<string>TEAMID.REDACTED_BUNDLE_ID</string>
...
```
Which I can successfully submit to Apple through the Transporter app.

If I resign using fastlane with the following command:
```
fastlane sigh resign WordOfTheDay.ipa -i IDENTITY -p /path/to/wildcard_provisioning.mobileprovision
```
with the same certificate and provisioning profile, `jtool` now gives:
```
	<key>application-identifier</key>
	<string>TEAMID.*</string>
```

I also tried this with the `--use_app_entitlements` flag added.

When uploading, I now get:
```
ERROR ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value 'TEAMID.*' for key 'application-identifier' in 'Payload/WordOfTheDay.app/PlugIns/com.aTinyFish.WordOfTheDay.Widget.appex/com.aTinyFish.WordOfTheDay.Widget' is not supported. This value should be a string starting with your TEAMID, followed by a dot '.', followed by the bundle identifier."
```
```
ERROR ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value 'TEAMID.*' for key 'application-identifier' in 'Payload/WordOfTheDay.app/WordOfTheDay' is not supported. This value should be a string starting with your TEAMID, followed by a dot '.', followed by the bundle identifier."
```

It seems like using a wildcard provisioning profile generates a wrong entry for the `application-identifier` entitlement.

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 10.15.4                                                 |
| Ruby                        | 2.5.8                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.26.0                                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.148.1/libexec/bin/fastlane |
| Host                        | Mac OS X 10.15.4 (19E287)                               |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.5/2.5.8/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1f  31 Mar 2020                             |
| Is contained                | false                                                   |
| Is homebrew                 | false                                                   |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 11.5                                                    |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.148.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.16.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.73.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.0        |
| googleauth                | 0.12.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.5.1        |
| google-cloud-storage      | 1.26.1       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.317.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.1.3        |
| aws-sdk-core              | 3.96.1       |
| aws-sdk-kms               | 1.31.0       |
| aws-sdk-s3                | 1.65.0       |
</details>

*generated on:* **2020-05-26**
</details>

**Comment by minuscorp** [comment]
I think you're missing arguments to resign the iOS, you can see more information in [here](https://docs.fastlane.tools/actions/resign/)

**Comment by dennisfrett** [comment]
> I think you're missing arguments to resign the iOS, you can see more information in [here](https://docs.fastlane.tools/actions/resign/)

HI, thanks for you reply. I think I added all the correct information, I entered the identity and provisioning profile interactively. I updated my original post with a command that includes this information.
Or do you mean another missing argument?

**Comment by minuscorp** [comment]
I mean, you _can_ sign with a wildcard profile an IPA? I'm not quite sure you can

**Comment by minuscorp** [comment]
Are you able to debug until this method:
https://github.com/fastlane/fastlane/blob/efd68a67a1dab647257983e965cbde19a0500c7c/sigh/lib/sigh/resign.rb#L22
Where is done the command, and see also if you can resign the ipa itself without fastlane with the same provision. Let's dig more into the issue

**Comment by dennisfrett** [comment]
I spent some type debugging and figured out the following:

 - When not passing`--use_app_entitlements`
All the entitlement information is extracted from the provisioning profile, never from the app. The full bundle identifier is never in the wildcard profile, so this causes the 'wrong' bundle id to end up in the new entitlements.

- When passing `--use_app_entitlements`
The entitlements are first extracted from the app itself. At this moment they contain the full bundle id. However, in the last step of the entitlements, all the bundle identifiers are patched with the one taken from the provisioning profile:
```
Replacing old bundle ID 'REDACTED_BUNDLE_ID' with new bundle ID '*' in patched entitlements
```

The behaviour when passing `--use_app_entitlements` is probably caused because it's possible to change the bundle identifiers when re-signing, and they need to be updated, if I understand it correctly?
However, we're not passing `--new_bundle_id`, so the script should not try to patch the bundle id?

To me it is not clear when we do _not_ want to use  `--use_app_entitlements`, so it's not clear to me if the behaviour here is a bug or expected.

I hope this information here helps to understand a bit more what the exact issue is and how it can maybe be resolved.

**Comment by minuscorp** [comment]
I'll try to investigate further this weekend
