### ISSUE TITLE
 Invalid option: --skip_upload_apk:

### ISSUE THREAD

**Issue by BianconeroIle** [fastlane/fastlane#16514]
I'm using fastlane version 2.137.0 and i'm trying to promote from beta to production track. 

#!/bin/bash

fastlane env

fastlane supply \
  --track beta \
  --track_promote_to production \
  --rollout 0.02 \
  --package_name com.something \
  --skip_upload_apk: true \
  --skip_upload_metadata: true, \
  --skip_upload_images: true, \
  --skip_upload_screenshots: true \
  --json_key "${}" \;

 invalid option: --skip_upload_apk:
 Please update using `sudo gem install fastlane`
 ERROR: Job failed: exit code 1

It's working for deployment scripts but not for promotion... any clue?

**Comment by Wood194** [comment]
Yes including the output is a must here. Try it once and you should get the solution

**Comment by BianconeroIle** [comment]
[09:57:04]: $ bundle exec fastlane supply --track beta --track_promote_to production --rollout 0.02 --package_name com.something p --json_key /builds/android/SUPPLY_JSON_KEY --skip_upload_apk: true --skip_upload_metadata: true, --skip_upload_images: true, --skip_upload_screenshots: true ;
 [09:57:04]: 
 [09:57:04]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
 invalid option: --skip_upload_apk:
 #######################################################################
 # fastlane 2.148.1 is available. You are on 2.137.0.
 # You should use the latest version.
 # Please update using `sudo gem install fastlane`.
 #######################################################################
 2.148.1 Improvements for plugin searching
 * [fastlane] fix searching for plugins where the name contains “action” in it (#16470) via Josh Holtz
 2.148.0 Improvements
 * [deliver] add fix for app_version and build_number matching (#16091) via onurpolattimur
 * [fastlane] load additional .env files from within CLIToolsDistributor (#16096) via Liam Nichols
 * [match] improve match macOS support (#16456) via Davide De Rosa
 * [gym] move AppStoreInfo.plist to build output directory if generated … (#16133) via Ashton Williams
 * [actions] push_to_git_remote - raise an error if get current branch failed (#16141) via Jierong Li
 * [deliver] fix crash when metadata_path is outside of the fastlane path (#16146) via Bruno Virlet
 * [Fastlane.swift] add options to beforeAll (#16220) via Niil Öhlin
 * [supply] added `in_app_update_priority` option to set the InAppUpdatePriority … (#16452) via jomisj
 * [Ruby 2.7] fix deprecated warnings (#16409) via Jakub Kašpar
 * [snapshot] fix warning in SnapshotHelper.swift (#16244) via Cédric Luthi
 * [sigh][match] add :fail_on_name_taken in sigh, use in match (#16281) via Michal Laskowski
 * [snapshot] erase simulator only when erase_simulator is true (#16299) via Theodore Gonzalez
 * [spaceship][pilot] expire TestFlight Builds (#16332) via Steven Sherry
 * [gym] add info on passing plist into export_options on gym (#16345) via Bahadır Öncel
 * [doc][crashlytics] remove duplicated deprecation message (#16363) via JAEHYUN OH
 * [scan] add `only_test_configurations` and `skip_test_configurations` options for use with test plans (#16367) via Rob Nadin
 * [snapshot] add -only-testing and -skip-testing options from scan (#16312) via Jean Mainguy
 * [screengrab] adding locales in all the paths where screenshots could be saved (#16370) via Nicolas Brosy
 * [action] upload_symbols_to_crashlytics include Path Suggested by Carthage Instructions (#16401) via Stefan Herold
 * [action] dd missing env_names to swiftlint action (#16445) via Tóth Balázs
 2.147.0 Dropped support for Ruby <= 2.3 and other improvements
 * [action] updating TestFairy action, based upon documentation and endpoint test. (#16425) via cdm2012
 * [frameit] automatically determine platform from fastfile (#16428) via Miloš Černilovský
 * [snapshot] add override_status_bar option (#16419) via Bouke van der Bijl
 * [action] fix shellescape in set_pod_key (#16421) via Arnaud Dorgans
 * [spaceship] add to_json for ConnectAPI models (#16422) via Theodore Dubois
 * [frameit] add iPad Pro 12.9 4th generation (#16444) via Bouke van der Bijl
 * [match] prompt for keychain password to set partition list for certificates to disable xcode prompt for password on sign (#16448) via Josh Holtz
 * [action] cocoapods: replace clean -> clean_install in example (#16435) via Marcin Stepnowski
 * [fastlane] drop Ruby 2.0, 2.1, 2.2 and 2.3 from gemspec (#16408) via Jakub Kašpar
 * [scan] add disable_xcpretty option that skips it post-xcodebuild too (#16375) via Marcelo Gobetti
 * [verify_xcode] add entry with TeamIdentifier=APPLECOMPUTER (#16395) via Teameh
 * [Fastlane.swift] adding --port setter to socket_server (#16381) via Ray Deck
 * [spaceship] fix error "can't modify frozen String" (#16403) via bill2004158
 * [git_branch] adding AppCenter for ENV variable check (#16404) via matemoln
 * [match] profile name parameter to specify your own provisioning profile name (#16386) via Josh Slebodnik
 * [Ruby 2.7] allow Faraday 1.0.0 and Faraday-middleware 1.0.0 with Ruby 2.7 fixes, fix base Ruby 2.3 tests (#16399) via Jakub Kašpar
 * [spaceship] add retrieve-create of iap shared secret to Spaceship::Tunes (#16326) via Michael Galperin
 * [frameit] change framefile.json load path to support Screengrab and Supply (#16306) via Wellington Avelino dos Santos
 * [fastlane] remove trailing spaces from custom_action_template file (#16366) via Akira Fukunaga
 * [snapshot] add -testPlan option from scan (#16350) via Jean Mainguy
 ## Migration Notes
 - Support for Ruby 2.0, 2.1, 2.2, and 2.3 has been dropped
   - Ruby 2.3 officially ended support March 31, 2019
 - _match_ will now prompt for keychain password when importing a new certificate
   - This will prevent the blocking prompt when Xcode signs a build
   - The password will only need to be entered once and will be stored in the keychain for future uses
 To see all new releases, open https://github.com/fastlane/fastlane/releases
 Please update using `sudo gem install fastlane`
 ERROR: Job failed: exit code 1

**Comment by Isabella2877** [comment]
Here is my lane to update rollout percentage on production track:

```
desc "Update production rollout - Usage: fastlane rollout_prod rollout:0.25"
lane :rollout_prod do |options|
  supply(
      track: 'production',          
      rollout: options[:rollout], # 0.25
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_changelogs: true,
    )
end
```

**Comment by alongaviaq** [comment]
Nice collection keep up the good work. [walgreenslistens](https://www.walgreenlistens.one/)
