### ISSUE TITLE
Exception type: Spaceship::UnauthorizedAccessError

### ISSUE THREAD

**Issue by tangs** [fastlane/fastlane#16510]
[✔] 🚀 
[04:12:46]: fastlane detected a Gemfile in the current directory
[04:12:46]: However, it seems like you didn't use `bundle exec`
[04:12:46]: To launch fastlane faster, please use
[04:12:46]: 
[04:12:46]: $ bundle exec fastlane spaceauth
[04:12:46]: 
[04:12:46]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
Logging into to App Store Connect (JamesShiporski113@hotmail.com)...
Two-factor Authentication (6 digits code) is enabled for account 'JamesShiporski113@hotmail.com'
More information about Two-factor Authentication: https://support.apple.com/en-us/HT204915

If you're running this in a non-interactive session (e.g. server or CI)
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification

Please enter the 6 digit code you received at +86 ••• •••• ••25:
296173
Requesting session...
Could not login to App Store Connect
Please check your credentials and try again.
This could be an issue with App Store Connect,
Please try unsetting the FASTLANE_SESSION environment variable
(if it is set) and re-run `fastlane spaceauth`

Exception type: Spaceship::UnauthorizedAccessError

Looking for related GitHub issues on fastlane/fastlane...

➡️  fastlane spaceauth return Unauthorized Access
    https://github.com/fastlane/fastlane/issues/16197 [closed] 3 💬
    26 Mar 2020

➡️  The request could not be completed because: Unauthorized Access
    https://github.com/fastlane/fastlane/issues/15411 [closed] 22 💬
    08 Mar 2020

➡️  fastlane cert got Unauthorized Access error
    https://github.com/fastlane/fastlane/issues/16108 [closed] 62 💬
    5 weeks ago

and 17 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09Unauthorized%20Access&type=Issues&utf8=✓

[!] The request could not be completed because:
	Unauthorized Access

[✔] 🚀 
[04:13:46]: fastlane detected a Gemfile in the current directory
[04:13:46]: However, it seems like you didn't use `bundle exec`
[04:13:46]: To launch fastlane faster, please use
[04:13:46]: 
[04:13:46]: $ bundle exec fastlane env
[04:13:46]: 
[04:13:46]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[04:13:47]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                        |
| --------------------------- | ------------------------------------------------------------ |
| OS                          | debian_based buster/sid                                      |
| Ruby                        | 2.5.1                                                        |
| Bundler?                    | false                                                        |
| Git                         | git version 2.17.1                                           |
| Installation Source         | /usr/local/bin/fastlane                                      |
| Host                        | Ubuntu 18.04.3 LTS debian_based buster/sid (4.15.0-1057-aws) |
| Ruby Lib Dir                | /usr/lib                                                     |
| OpenSSL Version             | OpenSSL 1.1.1  11 Sep 2018                                   |
| Is contained                | false                                                        |
| Is homebrew                 | false                                                        |
| Is installed via Fabric.app | false                                                        |

### System Locale

| Variable | Value   |   |
| -------- | ------- | - |
| LANG     | C.UTF-8 | ✅ |
| LC_ALL   |         |   |
| LANGUAGE |         |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

lane :register_ids do
	register_devices(
  		devices_file: "./ids.txt"
	)
end

#下载provisioning_profile
lane :adhoc_profile do
    #如果没有在Apple Developer创建证书的话，get_certificates会帮你自动创建证书
    #get_certificates
    sigh(
        username: 'JamesShiporski113@hotmail.com',
        app_identifier: 'net.fishing.*',
        force: true,
        provisioning_name: 'test_adhoc9',
        ignore_profiles_with_different_name: true,
        adhoc: true,
        filename: adhoc.mobileprovision
    )
end


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address
app_identifier("net.fishing.*")
apple_id("JamesShiporski113@hotmail.com")


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.148.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| emoji_regex               | 1.0.1        |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.16.0       |
| unicode-display_width     | 1.7.0        |
| excon                     | 0.73.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| faraday_middleware        | 1.0.0        |
| json                      | 2.3.0        |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| os                        | 1.1.0        |
| memoist                   | 0.16.2       |
| googleauth                | 0.12.0       |
| digest-crc                | 0.5.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-env          | 1.3.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.1       |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.1.3        |
| aws-partitions            | 1.315.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.95.0       |
| aws-sdk-kms               | 1.31.0       |
| aws-sdk-s3                | 1.64.0       |
| ipaddr                    | 1.2.0        |
| openssl                   | 2.1.1        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| psych                     | 3.0.2        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-05-25**
</details>
[04:13:48]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[04:13:48]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅

**Comment by shredder-rull** [comment]
I've faced with the same problem today. Fastlane version: 2.148.1

**Comment by jascha030** [comment]
Same issue here

**Comment by minuscorp** [comment]
Have you tried to use fastlane via bundle and report results back?

**Comment by shredder-rull** [comment]
Fixed for me after remove /Users/username/.fastlane/spaceship/{email}/cookie

**Comment by tangs** [comment]
> Fixed for me after remove /Users/username/.fastlane/spaceship/{email}/cookie

No way

**Comment by nicholascao404** [comment]
Same issue here

**Comment by GertjanSmits** [comment]
Also suddenly have this. No clue whats happening.

**Comment by notsubversion** [comment]
I was having the same problem. I removed the `cookie` file originally, but that didn't work. I had to remove the `{email}` directory as well.

It took 2 executions of fastlane to work though. The first time I didn't get the chance to enter the code, but the second run worked.

**Comment by dreadkopp** [comment]
Same here. Apples Phone bill is increasing :)
`<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 10.14                                                   |
| Ruby                        | 2.5.8                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.20.0                                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.148.1/libexec/bin/fastlane |
| Host                        | Mac OS X 10.14 (18A391)                                 |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.5/2.5.8/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1f  31 Mar 2020                             |
| Is contained                | false                                                   |
| Is homebrew                 | false                                                   |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 10.0                                                    |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.148.1 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.16.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.73.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.0        |
| googleauth                | 0.12.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.5.1        |
| google-cloud-storage      | 1.26.1       |
| emoji_regex               | 1.0.1        |
| json                      | 2.3.0        |
| bundler                   | 2.1.4        |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.1.3        |
| aws-partitions            | 1.320.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.96.1       |
| aws-sdk-kms               | 1.31.0       |
| aws-sdk-s3                | 1.66.0       |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
| webrick                   | 1.4.2        |
</details>


*generated on:* **2020-05-26**
</details>`

**Comment by minuscorp** [comment]
Might be there issues with apple auth, I tested it several times today without any issues. 🤔

**Comment by tanmays** [comment]
Suggestion by @notsubversion worked for me. 

Removing the `email` directory at 

``/Users/username/.fastlane/spaceship/{email}/``

 and then running it twice did the job.

**Comment by eytanschulman** [comment]
Having this issue, nothing working 😢 

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.4                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.26.2                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.4 (19E287)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.5                                                           |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(scheme: "RadiusTests")
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("net.multieducator.Radius") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.148.1 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.73.0       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| emoji_regex               | 1.0.1        |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.16.0       |
| faraday                   | 1.0.1        |
| faraday_middleware        | 1.0.0        |
| json                      | 2.3.0        |
| os                        | 1.1.0        |
| memoist                   | 0.16.2       |
| googleauth                | 0.12.0       |
| digest-crc                | 0.5.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-env          | 1.3.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.1       |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.1.3        |
| aws-partitions            | 1.320.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.96.1       |
| aws-sdk-kms               | 1.31.0       |
| aws-sdk-s3                | 1.66.0       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>


*generated on:* **2020-05-29**
</details>

**Comment by JGarcia-nc** [comment]
+1. Yesterday it was fine, my team was deploying Testflight builds with no problem. Today none of it's working and the workaround mentioned above aren't working.

**Comment by Ballrock** [comment]
Nothing was working too since today.

By despair i went to [Apple Developer](https://developer.apple.com/), relogged on it, retry my lane after and it worked again... 🤔  

Don't know... maybe a weird account state in Apple Auth Server that my login reset ?!

**Comment by eytanschulman** [comment]
> Nothing was working too since today.
> 
> 
> 
> By despair i went to [Apple Developer](https://developer.apple.com/), relogged on it, retry my lane after and it worked again... 🤔  
> 
> 
> 
> Don't know... maybe a weird account state in Apple Auth Server that my login reset ?!

What exactly did you do after you logged into Apple Developer?

**Comment by Sevyls** [comment]
I did get the uploaded archive listed in App Store Connect, but fastlane failed with the same error.
I did get the usual "Export Compliance" question though. Maybe some context?

**Comment by Ballrock** [comment]
@eytanschulman Absolutly nothing, that's the weirder, i just restart the lane the same way than before, after i succesfully logged on Apple Developer Website. 
Like i said, i don't exactly know what happened, i just shared this in case it could be useful for someone.

**Comment by chrmod** [comment]
Was facing same issue and non of provided walkarounds worked. Finally it worked when I've tried to used two-factor auth code from iPhone and not from Mac. Hope this helps.

**Comment by motoko89** [comment]
Thank you @tanmays , @chrmod , @Ballrock and all. I deleted the `{email}` folder and got the prompt to enter the code in my terminal, but I clicked "Allowed" on my Mac. It didn't work. I couldn't get the prompt afterward and the `{email}`folder didn't return either. So I logged into Apple Developer website on various browsers and tried again, tapping "Allowed" on my iPhone this time. It works!

**Comment by minuscorp** [comment]
Can we close this?

**Comment by Esxiel** [comment]
I'm still having problems with this even after logging onto Apple Developer on both my PC and mobile. I'm not even given a chance to put in any verification code when I run fastlane, it just exits 😢

**Comment by minuscorp** [comment]
> when I run fastlane, it just exits

There's a backtrace?

**Comment by madsrode** [comment]
I just tried the workarounds and none working.
Then tried to run `FASTLANE_SESSION=` in the terminal and then `spaceauth` again and it worked.

**Comment by ezheidtmann** [comment]
I've tried all workarounds mentioned:

 - Logging in to App Store Connect on desktop & mobile
 - Removing the directory in ~/.fastlane/spaceship/
 - Changing password and logging in again
 - Resetting FASTLANE_SESSION (it's not set)

I am seeing varying behavior when running `bundle exec fastlane spaceauth`:

 - Sometimes I'm asked to choose a trusted device, and sometimes I'm not
 - If I choose a device, sometimes I'm asked for a code and sometimes I'm not
 
But in all cases I see this output:

```
Could not login to App Store Connect
Please check your credentials and try again.
This could be an issue with App Store Connect,
Please try unsetting the FASTLANE_SESSION environment variable
(if it is set) and re-run `fastlane spaceauth`

Exception type: Spaceship::UnauthorizedAccessError
```

**Comment by boot-vue** [comment]
I hava this problem also.   after  delete  .fastlane  folder, it still perform the same.

after re-install os-system, it ok.   my os  is  ubuntu 18.04.

```
Logging into to App Store Connect (fenlaoliang08669@163.com)...
Could not login to App Store Connect
Please check your credentials and try again.
This could be an issue with App Store Connect,
Please try unsetting the FASTLANE_SESSION environment variable
(if it is set) and re-run `fastlane spaceauth`

Exception type: Spaceship::UnauthorizedAccessError

Looking for related GitHub issues on fastlane/fastlane...

➡️  Exception type: Spaceship::UnauthorizedAccessError
    https://github.com/fastlane/fastlane/issues/16510 [open] 24 💬
    an hour ago

➡️  fastlane spaceauth return Unauthorized Access
    https://github.com/fastlane/fastlane/issues/16197 [closed] 3 💬
    2 weeks ago

➡️  The request could not be completed because: Unauthorized Access
    https://github.com/fastlane/fastlane/issues/15411 [closed] 22 💬
    08 Mar 2020

and 18 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09Unauthorized%20Access&type=Issues&utf8=✓


[!] The request could not be completed because:
	Unauthorized Access

```

**Comment by sandeepbol** [comment]
I tried all the workarounds listed here. I get 2FA but spaceship doesn't wait for me to enter the code and exit with 

> [!] The request could not be completed because:
> 	Unauthorized Access
>

**Comment by thislooksfun** [comment]
I just had the same issue, for me it was (seemingly) because my credit card had expired. After I updated it the login worked just fine.

**Comment by AkihiroSuzukiJust** [comment]
Same issue.
After I update mac os version to 10.15.5, the problem occured.
I've tried all wordarounds above, but nothing worked.

**Comment by ratamaque0118** [comment]
After rebooting the OS,  the problem was resolved.
The problem was indeed present last Friday, but it's only now resolved.
I don't know why.

**Comment by nobitagamer** [comment]
I've tried all wordarounds above, and restarted OS but nothing worked. Still waiting for workaround here.

**Comment by damirstuhec** [comment]
I was using fastlane `v2.141.0` and seeing the same issue. **Updating to `v2.149.1` fixed it.**

**Comment by sandeepbol** [comment]
I was on *v2.149.1 *all the while. One fine day, the problem just goes away
on its own ;)

**Comment by nobitagamer** [comment]
Thanks! **v2.149.1** fixed my problem.
