### ISSUE TITLE
Add possibility to specify a root directory within git repository for match

### ISSUE THREAD

**Issue by pwszebor** [fastlane/fastlane#16524]
🔑
### Feature Request
Possibility to specify a search directory for match within git repository.
#### Motivation Behind Feature

Possibility to specify a path within match's git repository in which it searches for certificate files would allow to store other, unrelated certificate files in such repository. Currently it's impossible, because for such files, decryption always fails. My use case is to have one repository to store all certificates and keys for all platforms that my app supports. Currently, I can't, because fastlane match tries to decrypt all .p12 files it finds even though some of them are not iOS certificates.
#### Feature Description

fastlane match action could have another parameter called e.g.: storage_path that would then be used by classes that implement Storage interface to only download files that are inside the path specified by the parameter. Parameter would be optional, it would default to ".". This won't break anything for existing users. 
In the title, I mentioned git storage because I would be happy to provide implementation for this type of storage. 
#### Alternatives or Workarounds

Workarounds:
- storing match-encrypted files in a separate branch,
- using file extensions other that .p12, .cer for files that aren't match-encrypted.

**Comment by Watson166** [comment]
Add patterns to the sparse-checkout file to repopulate the working directory. ... Update the working directory to match the new patterns. ... If the skip-worktree bit is set, then the file is ignored in the working directory. ... contents of those files, which makes a sparse checkout helpful when working in a repository with many files
