### ISSUE TITLE
How to Specify a Derived Data Path with Swift Package Manager ?

### ISSUE THREAD

**Issue by sudachi808** [fastlane/fastlane#16526]
```bash
% bundle exec fastlane run scan scheme:"example" only_testing:"exampleTests" derived_data_path:"MyDerivedData"
[✔] 🚀 
[18:59:49]: ------------------
[18:59:49]: --- Step: scan ---
[18:59:49]: ------------------
[18:59:49]: Successfully loaded '/Users/sudachi808/Projects/example/fastlane/Scanfile' 📄
[18:59:49]: No values defined in './fastlane/Scanfile'
[18:59:49]: Resolving Swift Package Manager dependencies...
[18:59:49]: $ xcodebuild -resolvePackageDependencies -workspace ./example.xcworkspace -scheme example
[18:59:50]: ▸ Command line invocation:
[18:59:50]: ▸     /Applications/Xcode_11_5.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -workspace ./example.xcworkspace -scheme example
[18:59:51]: ▸ Resolve Package Graph
[18:59:51]: ▸ Fetching https://github.com/Brightify/Cuckoo.git

(snip)

```

I expected 

```bash
xcodebuild -resolvePackageDependencies -workspace ./example.xcworkspace -scheme example -derivedDataPath MyDerivedData
                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
and
```bash
/Applications/Xcode_11_5.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -workspace ./example.xcworkspace -scheme example -derivedDataPath MyDerivedData
                                                                                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

but, I got above.

Does anybody have the idea to resolve this problem?

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                                   |
| --------------------------- | ----------------------------------------------------------------------- |
| OS                          | 10.15.4                                                                 |
| Ruby                        | 2.6.3                                                                   |
| Bundler?                    | true                                                                    |
| Git                         | git version 2.24.3 (Apple Git-128)                                      |
| Installation Source         | ~/Projects/example/vendor/bundle/ruby/2.6.0/bin/fastlane |
| Host                        | Mac OS X 10.15.4 (19E287)                                               |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib          |
| OpenSSL Version             | LibreSSL 2.8.3                                                          |
| Is contained                | false                                                                   |
| Is homebrew                 | false                                                                   |
| Is installed via Fabric.app | false                                                                   |
| Xcode Path                  | /Applications/Xcode_11_5.app/Contents/Developer/                        |
| Xcode Version               | 11.5                                                                    |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | ja_JP.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.148.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 2.1.4        |
| rake                      | 12.3.3       |
| CFPropertyList            | 3.0.2        |
| concurrent-ruby           | 1.1.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.11.1     |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.322.0      |
| aws-sigv4                 | 1.1.3        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.96.1       |
| aws-sdk-kms               | 1.31.0       |
| aws-sdk-s3                | 1.66.0       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| cork                      | 0.3.0        |
| nap                       | 1.1.0        |
| open4                     | 1.3.4        |
| claide-plugins            | 0.9.2        |
| fuzzy_match               | 2.0.4        |
| cocoapods-core            | 1.7.5        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.2.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.1        |
| cocoapods-try             | 1.1.0        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.16.0       |
| cocoapods                 | 1.7.5        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.17.3       |
| faraday-http-cache        | 2.0.0        |
| git                       | 1.5.0        |
| kramdown                  | 2.1.0        |
| kramdown-parser-gfm       | 1.1.0        |
| no_proxy_fix              | 0.1.2        |
| sawyer                    | 0.8.2        |
| octokit                   | 4.14.0       |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| danger                    | 6.0.9        |
| mime-types-data           | 3.2020.0512  |
| mime-types                | 3.3.1        |
| multi_xml                 | 0.6.0        |
| httparty                  | 0.17.0       |
| gitlab                    | 4.12.0       |
| danger-gitlab             | 7.0.0        |
| danger-plugin-api         | 1.0.0        |
| danger-lgtm               | 1.0.4        |
| thor                      | 0.20.3       |
| danger-swiftlint          | 0.23.0       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.5.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.73.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.14.0       |
| fastimage                 | 2.1.7        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.1.0        |
| signet                    | 0.14.0       |
| googleauth                | 0.12.0       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.1       |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2020-05-28**
</details>

**Comment by Decke1r** [comment]
It's the location where Xcode stores all kinds of intermediate build results, generated indexes, [MyCFAVisit](https://www.mycfavisit.onl/) etc.

**Comment by zakkhoyt** [comment]
We are experiencing an error with scan on fastlane `2.149.0`. 

We are not providing derived data path at all and receive the error:

`xcodebuild: error: option '-derivedDataPath' may only be provided once`

Our lane looks like this:

```  
lane :unit_tests do |options|
    scan(
      scheme: "MyScheme",
      clean: true,
      force_quit_simulator: true,
      code_coverage: true,
      result_bundle: true,
      include_simulator_logs: true,
      output_files: "MyProj.html,MyProj.junit",
      fail_build: true,
      device: "iPhone 11 Pro Max",
      reset_simulator: true
    )
end

```

We rolled back to `2.148.1` which does work.

**Comment by Greppipa** [comment]
Very important tips you share with us keep sharing more. Thank you.
