### ISSUE TITLE
Succesfully ran upload_to_playstore action but still have to manually review the app

### ISSUE THREAD

**Issue by SebaRossi94** [fastlane/fastlane#16530]
### Question Checklist

- [Y ] Updated fastlane to the latest version
- [ Y] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ Y] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ Y] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
I managed to succesfully upload an apk exactly as i wanted except for only one thing, i still need to manually go to the playstore console and click review before my apk is published for internal track

#### Question Description
I want to fully automate the entire publishing process using all 4 stages that playstore offers (internal, alfa, beta, production). I managed to succesfully automate the entire process except for the first track. When i upload my apk to internal track i'm able to create a new version, upload the apk, upload the correct changelog but i can't submit the newly created version for review, to do that i have to log in manunally to playstore console and click the review button to confirm the publishing of the created version.

Fastfile is as follows:
```
lane : internal do |options|
upload_to_play_store(
track: "internal",
release_status: "draft",
apk: "path/to/apk.apk",
skip_upload_aab: true,
skip_upload_metadata: true,
skip_upload_images: true,
skip_upload_screenshots: true
)

slack(...)

mailgun(...)
```
Output has no errors and the result is the version created in playstore, the apk uploaded and the changelog as well, yet i have to go to the console and confirm the publishing by pressing review button.

**Comment by kohenkatz** [comment]
You need to change `release_status: "draft",` to `release_status: "complete",` (or leave it out entirely since `complete` is the default).
