### ISSUE TITLE
Add alias action names to GitHub labels

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#16535]
Currently we have `tools` labels like `supply`, but the new or multiple action names supplied by those tools are not present. Adding e.g. `upload_to_playstore` to the description fixes this.

**Comment by Mustiaifa** [comment]
In this post you’ll build a fairly simple and extensible kanban power-up for GitHub Projects that automates the triaging of new issues to project boards and to track issue statuses automatically.
