### ISSUE TITLE
The `aapt` command could not be found, so status bar could not be cleaned. Make sure android_home is configured for screengrab or ANDROID_HOME is set in the environment in mac

### ISSUE THREAD

**Issue by BaskarRammiya** [fastlane/fastlane#16549]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by BaskarRammiya** [comment]
I have added fastlane env
aapt is found in my system cannot able to recognise

**Comment by janpio** [comment]
You did not add your `fastlane env` output.
You also did not include any of the output you are getting as the template is asking for.
Right now we can not help you.

**Comment by BaskarRammiya** [comment]
export ANDROID_HOME=/Users/XXXX/Library/Android/sdk
export PATH="$PATH:/Users/XXXX/Library/Android/sdk/build-tools/x.x.x”
I am using these commands in ~/.bash_profile when I echo $PATH "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/XXXX/Library/Android/sdk/build-tools/x.x.x"
displayed

`[12:41:36]: The `aapt` command could not be found on your system, so your app APK could not be validated
[12:41:36]: Installing app APK
[12:41:36]: $ /Users/XXXXXX/Library/Android/sdk/platform-tools/adb -s XXXXX install -t -r XXXX.apk
[12:41:36]: ▸ Performing Push Install
[12:41:37]: ▸ XXXX.apk: 1 file pushed, 0 skipped. 9.8 MB/s (13938298 bytes in 1.354s)
[12:41:39]: ▸   pkg: /data/local/tmp/XXXX.apk
`
