### ISSUE TITLE
Fastlane Swift: Gemfile?

### ISSUE THREAD

**Issue by turtlemaster19** [fastlane/fastlane#16550]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

In Swift Fastlane, I find that it adds a bunch of files in a `swift` subdirectory, and still includes a Gemfile.

#### Question Description

Why is this the case? Is there any way to (at least) not use a Gemfile in _Swift_ Fastlane? I am using CircleCI in my project, too, so any commands there to update Fastlane to latest are acceptable, but I would prefer not to use a Gemfile in the Swift version.

**Comment by minuscorp** [comment]
You have to understand that Swift fastlane relies on fastlane, which relies on Ruby, so you will always need a Gemfile or a system installed fastlane in order to Swift fastlane work. Did I answer your question?

**Comment by turtlemaster19** [comment]
@minuscorp Can you check my understanding? If there is a Fastlane version already installed, and I use the update Fastlane function in my Fastfile, then I can safely delete the gemfile?

**Comment by Schnecik** [comment]
It’s that wonderful moment: You’ve poured days, weeks or maybe even months into building an app, and it’s finally ready to share with the world. All you have to do is submit it to the App Store.

**Comment by turtlemaster19** [comment]
If my comment above is correct, then I will close this. No use bothering anyone else!

I guess I wish that the status quo with the Swift version wasn't so complicated, but I'll take what I can get! 🤪
