### ISSUE TITLE
[slack] Fastlane got rickrolled?

### ISSUE THREAD

**Issue by sebastianludwig** [fastlane/fastlane#16552]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
The Slack notification icon: https://s3-eu-west-1.amazonaws.com/fastlane.tools/fastlane.png

#### Question Description

Is the change from the fastlane logo to Rick Astley intentional?

The icon is referenced here https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/slack.rb#L105-L108. Up until recently it was a fastlane icon. Now it's not anymore https://s3-eu-west-1.amazonaws.com/fastlane.tools/fastlane.png 

Do we have to worry about some leaked credentials?

**Comment by janpio** [comment]
I can not imagine how this could leak credentials. But seems someone accidentally or deliberately changed the image that was used as the default there.

**Comment by sebastianludwig** [comment]
Agreed that the image wouldn't actively leak credentials but since the image changed without the URL being changed I assume someone uploaded a new image to the S3 bucket. This could have either mean someone authorized is having a laugh _or_ someone unauthorized having access to the S3 bucket. If it's someone unauthorized I was wondering if they could have gotten access to more secrets that this one, that's all. But it's also none of my concerns ;-)

**Comment by janpio** [comment]
Ah, you mean on Fastlane side.

I am currently trying to find out the authorized/unauthorized thing, including if this bucket is used for anything else.

**Comment by joshdholtz** [comment]
@sebastianludwig Thanks for bringing that up! I'm not sure who owns that S3 bucket to be honest. No credentials have been leaked since we don't use S3 for anything. I'm going to change that action to point to a fastlane icon that is hosted from our website (which is hosted on GitHub). 

I'll still see if I can figure out who owns that 🤷‍♂️

**Comment by snatchev** [comment]
That URL was introduced in https://github.com/fastlane/fastlane/commit/266ace90675fad0fa0b1130d20babcabb2f0f6a1
