### ISSUE TITLE
[Fastlane.swift] Swift Package Manager support

### ISSUE THREAD

**Issue by UInt2048** [fastlane/fastlane#16566]
#### Motivation Behind Feature
There is a `swift` subdirectory in Swift Fastlane products exactly mirroring this directory: https://github.com/fastlane/fastlane/tree/master/fastlane/swift

This sounds like the perfect opportunity for a Swift package which could simply be imported in the Xcode project.

#### Feature Description
I'm considering opening a PR, but I wanted to get feedback first since a `Package.swift` would need to be created at the top-level directory of this repository. This file would make it so that these files would instead be imported from this repository in a package, which has the side benefit of preventing users from editing these files.

However, doing this would require users to `import Fastlane` in the Swift files they create using it, such as `Fastfile.swift`. To compensate for this, this feature shouldn't be made mandatory, but optional. Eventually, this could be the default behaviour for new users.

This won't break anything for existing users that still have the existing directory, but documentation would need to be updated.

#### Alternatives or Workarounds
The alternative is, of course, the existing behaviour where over 30 files are added to the user's repository that they can't edit or remove.

**Comment by turtlemaster19** [comment]
@joshdholtz Good to know. We probably would have to not include those in the package, and keep just those two the same way they are now.

Unless, of course, you have any better ideas? I don't really know how that process works, but I would prefer two files to thirty!

**Comment by joshdholtz** [comment]
Ha, agreed... Thirty is a lot of files!

One other thing to think about is that Swift Package would need need to stay in sync with the fastlane version. When an action/tool has updated options, the Swift interface gets updated. We would need to make sure that there is a proper error message when the Swift package is outdated for the version of fastlane being used. I forget how that all works but that is one other thing that would need to get looked at 😊 

I’m totally down for reviewing and testing a PR if you want to give this is a shot. There is a chance that it might not work out if you are okay with that but I’m down for trying if you are down 🙃

**Comment by UInt2048** [comment]
@fastlane-bot Still relevant.

**Comment by minuscorp** [comment]
@UInt2048 you can check out the PR using my branch and tell me your experience! 😁

**Comment by joshdholtz** [comment]
Reviewing this now!!!!! 😊

**Comment by rogerluan** [comment]
This can be closed @joshdholtz @minuscorp since #16844 was released 🚀
