### ISSUE TITLE
[Fastlane.swift] [snapshot] html_template path defaults to Josh's home folder

### ISSUE THREAD

**Issue by jhandguy** [fastlane/fastlane#16563]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: `2.149.x`
- Last working version: `2.148.x`

### Regression Description

Since the PR https://github.com/fastlane/fastlane/pull/15349, the new `html_template` option takes `File.join(Snapshot::ROOT, "lib", "snapshot/page.html.erb")` as a default value, which when generating the Swift API, defaults to `"/Users/josh/Projects/fastlane/fastlane/snapshot/lib/snapshot/page.html.erb"`.

As a result, `snapshot` fails with the error:
```
No such file or directory @ rb_sysopen - /Users/josh/Projects/fastlane/fastlane/snapshot/lib/snapshot/page.html.erb
```

**Comment by joshdholtz** [comment]
OMG... I’ll fix 😊

**Comment by jhandguy** [comment]
Should be fixed in the next release ✅
