### ISSUE TITLE
fastlane sigh repair doesn't work

### ISSUE THREAD

**Issue by nrbrook** [fastlane/fastlane#16573]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm trying to use fastlane sigh repair to repair expired profiles, but I encounter an error described below.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>% fastlane sigh repair
[✔] 🚀 
[22:07:20]: fastlane detected a Gemfile in the current directory
[22:07:20]: However, it seems like you didn't use `bundle exec`
[22:07:20]: To launch fastlane faster, please use
[22:07:20]: 
[22:07:20]: $ bundle exec fastlane sigh repair
[22:07:20]: 
[22:07:20]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[22:07:24]: Starting login with user 'nrbrook@gmail.com'
Available session is not valid any more. Continuing with normal login.
[22:07:26]: Successfully logged in
[22:07:27]: Going to repair 5 provisioning profiles
[22:07:27]: Repairing profile 'XC iOS: com.airturn.VirtualPED'...

Looking for related GitHub issues on fastlane/fastlane...

➡️  Undefined method `strip' for nil:NilClass error after a sucess upload_to_testflight
    https://github.com/fastlane/fastlane/issues/16201 [open] 4 💬
    4 weeks ago

➡️  [Swift] undefined method `each' for nil:NilClass - Cannot Create Group Within FastlaneSwiftRunner Project
    https://github.com/fastlane/fastlane/issues/15184 [open] 28 💬
    14 hours ago

➡️  [supply] added support for refresh tokens as an authentication method
    https://github.com/fastlane/fastlane/pull/16414 [open] 10 💬
    2 weeks ago

and 236 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60id%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	19: from /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `<main>'
	18: from /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `load'
	17: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.149.1/bin/fastlane:23:in `<top (required)>'
	16: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	15: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.149.1/sigh/lib/sigh/commands_generator.rb:16:in `start'
	14: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.149.1/sigh/lib/sigh/commands_generator.rb:139:in `run'
	13: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	12: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.149.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	11: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	10: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 9: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 8: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.149.1/sigh/lib/sigh/commands_generator.rb:96:in `block (2 levels) in run'
	 7: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.149.1/sigh/lib/sigh/repair.rb:26:in `repair_all'
	 6: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.149.1/sigh/lib/sigh/repair.rb:26:in `each'
	 5: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.149.1/sigh/lib/sigh/repair.rb:28:in `block in repair_all'
	 4: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.149.1/spaceship/lib/spaceship/portal/provisioning_profile.rb:418:in `repair!'
	 3: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.149.1/spaceship/lib/spaceship/portal/provisioning_profile.rb:450:in `update!'
	 2: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.149.1/spaceship/lib/spaceship/client.rb:626:in `with_retry'
	 1: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.149.1/spaceship/lib/spaceship/portal/provisioning_profile.rb:456:in `block in update!'
/usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.149.1/spaceship/lib/spaceship/portal/provisioning_profile.rb:456:in `map': undefined method `id' for nil:NilClass (NoMethodError)
	19: from /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `<main>'
	18: from /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `load'
	17: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.149.1/bin/fastlane:23:in `<top (required)>'
	16: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	15: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.149.1/sigh/lib/sigh/commands_generator.rb:16:in `start'
	14: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.149.1/sigh/lib/sigh/commands_generator.rb:139:in `run'
	13: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	12: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.149.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	11: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	10: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 9: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 8: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.149.1/sigh/lib/sigh/commands_generator.rb:96:in `block (2 levels) in run'
	 7: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.149.1/sigh/lib/sigh/repair.rb:26:in `repair_all'
	 6: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.149.1/sigh/lib/sigh/repair.rb:26:in `each'
	 5: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.149.1/sigh/lib/sigh/repair.rb:28:in `block in repair_all'
	 4: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.149.1/spaceship/lib/spaceship/portal/provisioning_profile.rb:418:in `repair!'
	 3: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.149.1/spaceship/lib/spaceship/portal/provisioning_profile.rb:450:in `update!'
	 2: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.149.1/spaceship/lib/spaceship/client.rb:626:in `with_retry'
	 1: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.149.1/spaceship/lib/spaceship/portal/provisioning_profile.rb:456:in `block in update!'
/usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.149.1/spaceship/lib/spaceship/portal/provisioning_profile.rb:456:in `map': \e[31m[!] undefined method `id' for nil:NilClass\e[0m (NoMethodError)</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.5                                     |
| Ruby                        | 2.7.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.26.2                          |
| Installation Source         | /usr/local/lib/ruby/gems/2.6.0/bin/fastlane |
| Host                        | Mac OS X 10.15.5 (19F101)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.7.1_2/lib          |
| OpenSSL Version             | OpenSSL 1.1.1f  31 Mar 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.5                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
  	increment_build_number(
	    build_number: latest_testflight_build_number + 1,
	    xcodeproj: "AirTurnApp.xcodeproj"
	  )
    build_app(scheme: "AirTurn App")
    upload_to_testflight
    download_dsyms(version: "latest") # download bitcode dSYMs
    upload_symbols_to_crashlytics(gsp_path: "./AirTurnApp/GoogleService-Info.plist") # upload dSYMs to firebase crashlytics
    clean_build_artifacts
  end
  desc "Push a new release build to TestFlight"
  lane :release do
  	increment_build_number(
	    build_number: latest_testflight_build_number + 1,
	    xcodeproj: "AirTurnApp.xcodeproj"
	  )
  	capture_screenshots                  # generate new screenshots for the App Store
  	# sync_code_signing(type: "appstore")  # see code signing guide for more information
  	build_app(scheme: "AirTurn App")
  	upload_to_app_store                  # upload your app to App Store Connect
    download_dsyms(version: "latest") # download bitcode dSYMs
  	upload_symbols_to_crashlytics(gsp_path: "./AirTurnApp/GoogleService-Info.plist") # upload dSYMs to firebase crashlytics
    clean_build_artifacts
  end
  desc "Create screenshots and upload"
  lane :screenshots do
    capture_screenshots
    upload_to_app_store
  end
  desc "Upload symbols to crashlytics"
  lane :refresh_dsyms do
    download_dsyms                  # Download dSYM files from iTC
    upload_symbols_to_crashlytics   # Upload them to Crashlytics
    clean_build_artifacts           # Delete the local dSYM files
  end
  lane :latest_dsyms do
  	download_dsyms(version: "latest") # download bitcode dSYMs
    upload_symbols_to_crashlytics # upload dSYMs to crashlytics
    clean_build_artifacts
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.airturn.AirTurn") # The bundle identifier of your app
apple_id("nrbrook@gmail.com") # Your Apple email address

itc_team_id("344358") # App Store Connect Team ID
team_id("6GTP8W5ZXK") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.149.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.73.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.1.2        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.0        |
| googleauth                | 0.12.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.5.1        |
| google-cloud-storage      | 1.26.1       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.319.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.1.3        |
| aws-sdk-core              | 3.96.1       |
| aws-sdk-kms               | 1.31.0       |
| aws-sdk-s3                | 1.66.0       |
| uri                       | 0.10.0       |
| forwardable               | 1.3.1        |
| logger                    | 1.4.2        |
| cgi                       | 0.1.0        |
| timeout                   | 0.1.0        |
| stringio                  | 0.1.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.2.0        |
| strscan                   | 1.0.3        |
| date                      | 3.0.0        |
| delegate                  | 0.1.0        |
| fileutils                 | 1.4.1        |
| io-console                | 0.5.6        |
| zlib                      | 1.1.0        |
| singleton                 | 0.1.0        |
| rexml                     | 3.2.3        |
| open3                     | 0.1.0        |
| yaml                      | 0.1.0        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.6.0        |
</details>

*generated on:* **2020-06-05**
</details></pre>
</details>

**Comment by Esteillia** [comment]
If only you could run a single command that took all your screenshots, on all your supported devices, in every supported language automagically.
