### ISSUE TITLE
Add configurable execution of 'Resolving Swift Package Manager dependencies' 

### ISSUE THREAD

**Issue by asifmohd** [fastlane/fastlane#16589]
### Feature Request
- An ability to disable the `Resolving Swift Package Manager dependencies` command

#### Motivation Behind Feature
It takes ~3 minutes on our locally hosted 2018 mac mini runners, to finish executing this command
`xcodebuild -resolvePackageDependencies -workspace workspace-path -scheme scheme-name`

The ability to execute this optionally would allow us to save ~3 mins on every CI build.

#### Feature Description
I think we should be able to add a config wrapper around the `Resolving Swift Package Manager dependencies`. [Source code link](https://github.com/fastlane/fastlane/blob/e70cf30d50d5653b762e570bbc355809dc0d06b2/fastlane_core/lib/fastlane_core/project.rb#L370)

This config would default to being true, but for developers who have not integrated swift PM, and do not intend to do so for a while, they will set this config to false using preferably an environment variable or a passed config to gym/scan.

#### Alternatives or Workarounds
No workaround or alternative available AFAIK

**Comment by bguidolim** [comment]
@asifmohd This command was added to avoid the timeout when trying to get the project configuration. It will run automatically by Xcode even if you try to suppress it.
