### ISSUE TITLE
Fastlane summary is printing curl command "Auth header" as plain text 🔥

### ISSUE THREAD

**Issue by crazymanish** [fastlane/fastlane#16585]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When running a curl command with Auth Header, Fastlane summary printing the Auth Header as plain-text.

##### Command executed
sh("curl -H 'AUTH_HEADER' some_url")

##### Complete output when running fastlane, including the stack trace and command used
I am pretty sure @joshdholtz don't need the complete output to fix this issue 😈

### Environment
This is more than enough for Josh.... 🤸🏻‍♂️ 🚀
<img width="548" alt="Screenshot 2020-06-09 at 02 06 14" src="https://user-images.githubusercontent.com/5364500/84092591-1fe05300-a9f8-11ea-8795-ffd5740b752c.png">

**Comment by joshdholtz** [comment]
Thank you!

**Comment by joshdholtz** [comment]
@crazymanish Question! Is that “Perfect” screenshot how its already behaving for you? Is _fastlane_ replace the command with `***` for you? Or did you make that image as an example of what it should look like?

**Comment by crazymanish** [comment]
> @crazymanish Question! Is that “Perfect” screenshot how its already behaving for you? Is _fastlane_ replace the command with `***` for you? Or did you make that image as an example of what it should look like?

I have merged two images into one :p 

In the first image, when curl command is executing...`***` is showing in the log which is perfect 💪🏻
In the second image, when Fastlane has done all the work...in the end summary table its showing 
entire curl command without `***` which is worried

**Comment by joshdholtz** [comment]
Hmmm... I’m actually not getting the `***` to show in my test 🤔 My `Fastfile` looks like this...

```rb

lane :sh_test do
  sh("curl -H 'Authorization: Bearer SOMETHING SECRET' https://api.github.com/user")
end
```

Are you doing something like this?

**Comment by crazymanish** [comment]
> Hmmm... I’m actually not getting the `***` to show in my test 🤔 My `Fastfile` looks like this...
> 
> ```ruby
> lane :sh_test do
>   sh("curl -H 'Authorization: Bearer SOMETHING SECRET' https://api.github.com/user")
> end
> ```
> 
> Are you doing something like this?

Strange...my screenshots/logs are from GitHub action output...can you run this test on GitHub action please... let me quickly try to run my fastfile in local to see what its printing :)

**Comment by joshdholtz** [comment]
Ohhhhhh... so that was run using `github_action`? I was just doing a raw `sh`

**Comment by crazymanish** [comment]
> Ohhhhhh... so that was run using `github_action`? I was just doing a raw `sh`

Yes, running on `github_action` :)

**Comment by joshdholtz** [comment]
@crazymanish Can you post a sample of your `Fastfile`? I’m still not able to figure out where `curl` is being called from 🤔

**Comment by crazymanish** [comment]
This is what I am doing...
- fetching random file of a Slack channel using
https://github.com/crazymanish/fastlane-plugin-slack_bot/blob/master/lib/fastlane/plugin/slack_bot/actions/fetch_files_slack.rb
- Downloading that file using Curl command 

```
lane :download_slack_channel_random_file do
  random_file_info = fetch_random_file
 download_file(random_file_info)
end

private_lane :fetch_random_file do
  files = fetch_files_slack(channel: ENV["SLACK_SOURCE_CHANNEL_ID"])
  files[:json]["files"].sample
end

private_lane :download_file do |options|
  auth_header="Authorization: Bearer #{ENV["SLACK_API_TOKEN"]}"
  file_url = options["url_private"]
  file_name = get_file_name(options)

  sh("curl -H '#{auth_header}' -o '#{file_name}' -s '#{file_url}'")
end
```

**Comment by crazymanish** [comment]
in my Fastfile, there is no ios/android platform if that helps 🤷🏻‍♂️
Just lanes (public & private lanes) :p 

basically I am not using because those lanes are not really related to ios/android platform 😉
```ruby 
default_platform :ios
platform :ios do

**Comment by joshdholtz** [comment]
Soooo... its hard to figure out what to automatically hide but you could do something like this...

```sh
sh(
  "curl -H '#{auth_header}' -o '#{file_name}' -s '#{file_url}'"
  step_name: "curl -H '***' -o '#{file_name}' -s '#{file_url}'"
)
```

**Comment by crazymanish** [comment]
> ```ruby
> sh(
>   "curl -H '#{auth_header}' -o '#{file_name}' -s '#{file_url}'"
>   step_name: "curl -H '***' -o '#{file_name}' -s '#{file_url}'"
> )
> ```

Nice! thanks... I will use that...I thought you can do some magic for curl command...always hides the Headers (-H) with `***`  

I was using below for time-being :p file_name & file_url was covering the entire Fastlane summary window...
sh( "curl -o '#{file_name}' -s '#{file_url}' -H '#{auth_header}'")

**Comment by joshdholtz** [comment]
I _could_ do some magic for curl but then people might request a whole bunch of others and that just wouldn’t scale well 😜

**Comment by crazymanish** [comment]
Agree! 💯

Okay then, still `step_name` is really helpful...Thank you so much looking into this issue :)
I will join you soon to fix some of the Fastlane bugs 😍

**Comment by joshdholtz** [comment]
Sounds great! Looking forward to it 😊 I’m going to close this issue then!
