### ISSUE TITLE
client-secret.json file is content is overwritten when i run firebase instrumentation tests lane

### ISSUE THREAD

**Issue by osborneomuya** [fastlane/fastlane#16591]
I am using fastlane to run instrumentation tests on firebase test lab.when i run the command bundle _exec fastlane instrumentation_tests_testlab_i get the error "**(gcloud.auth.activate-service-account) Could not read json file client-secret.json: No JSON object could be decoded**" and the contents of the client-secret.json file are erased.what is the cause of this error and how do i resolve it? 
I am on ubuntu 19.04.

**Comment by janpio** [comment]
What action or plugin are you using to trigger these tests?

**Comment by osborneomuya** [comment]
hi am using 
plugin: fastlane add_plugin run_tests_firebase_testlab
action: bundle exec fastlane instrumentation_tests_testlab

**Comment by janpio** [comment]
You might be better of asking in https://github.com/pink-room/fastlane-plugin-run_tests_firebase_testlab/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc then, as this is the plugin and action you are using. We can not tell you much about what this plugin does and why.

**Comment by Tor1res** [comment]
The path to the binary file containing instrumentation tests[ DQ Fan Feedback](https://www.dqfansurvey.us/).
