### ISSUE TITLE
brew installed zip contain Ruby 2.2.0?

### ISSUE THREAD

**Issue by pedia** [fastlane/fastlane#16595]
I noticed `brew cask install fastlane` download from https://fastlane.tools/fastlane.zip
This zip contain ruby 2.2.0:
> fastlane_lib/bundle/lib/ruby/2.2.0

```shell
fastlane env 
```
will error with:
> ffi need ruby>2.3.0

Is this right?

**Comment by janpio** [comment]
Ping @joshdholtz

**Comment by joshdholtz** [comment]
Hey! 

`brew cast install fastlane` is deprecated 🙂

Use `brew install fastlane` 💪

**Comment by pedia** [comment]
OK. It's great.

Worked with:
```shell
export GEM_HOME="$HOME/.gem"
gem install fastlane
```
