### ISSUE TITLE
Not possible to run fastlane - dependency aws-sdk-ruby error - aws new version is ready!

### ISSUE THREAD

**Issue by mortenholmgaard** [fastlane/fastlane#16598]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Just executing fastlane fails. Not on all my projects but one after one they start failing. 
It is because of this aws-sdk-ruby error https://github.com/aws/aws-sdk-ruby/issues/2327
(https://github.com/aws/aws-sdk-ruby/issues/2330) with was fixed yesterday. It was introduced in aws-sdk-ruby 1.33.0 but fixed in 1.34.1.
I can't figure out if I could do anything locally that would fix it or it requires a new fastlane release?

##### Command executed
```
bundle exec fastlane
```

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>

$ bundle exec fastlane
 [✔] 🚀
Traceback (most recent call last):
        19: from C:/tools/ruby26/bin/fastlane:23:in `<main>'
        18: from C:/tools/ruby26/bin/fastlane:23:in `load'
        17: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/fastlane-2.149.1/bin/fastlane:23:in `<top (required)>'
        16: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
        15: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:33:in `start'
        14: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane.rb:38:in `load_actions'
        13: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/actions/actions_helper.rb:93:in `load_default_actions'
        12: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/actions/actions_helper.rb:93:in `each'
        11: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/actions/actions_helper.rb:94:in `block in load_default_actions'
        10: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/actions/actions_helper.rb:94:in `require'
         9: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/actions/s3.rb:2:in `<top (required)>'
         8: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/actions/s3.rb:2:in `require'
         7: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/helper/s3_client_helper.rb:1:in `<top (required)>'
         6: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/helper/s3_client_helper.rb:1:in `require'
         5: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3.rb:8:in `<top (required)>'
         4: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/aws-sdk-s3-1.67.1/lib/aws-sdk-s3.rb:8:in `require'
         3: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/aws-sdk-kms-1.34.0/lib/aws-sdk-kms.rb:13:in `<top (required)>'

         2: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/aws-sdk-kms-1.34.0/lib/aws-sdk-kms.rb:13:in `require_relative'

         1: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/aws-sdk-kms-1.34.0/lib/aws-sdk-kms/client.rb:27:in `<top (required)>'
C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/aws-sdk-kms-1.34.0/lib/aws-sdk-kms/client.rb:27:in `require': cannot load such file -- aws-sdk-core/plugins/http_checksum.rb (LoadError)

</pre>
</details>

### Environment
`fastlane env` fails as well but I have manually include some details

<details>
  <pre>
fastlane version: 2.149.1
ruby 2.6.3p62 (2019-04-16 revision 67580)
</pre>
</details>

**Comment by janpio** [comment]
Ping @joshdholtz

**Comment by mortenholmgaard** [comment]
Manually adding `gem "aws-sdk-kms", ">= 1.34.1"` to Gemfile and `bundle update` to update the `Gemfile.lock` file seems to do the trick.
