### ISSUE TITLE
pilot failed with iTMSTransporter error

### ISSUE THREAD

**Issue by pedia** [fastlane/fastlane#16596]
## Short detail
Latest version of iTMSTransporter and fastlane.
```
WARN [2020-06-12 17:23:46.41]: [iTMSTransporter] -Djava.ext.dirs=/usr/local/itms/java/lib/ext is not supported.  Use -classpath instead.
WARN [2020-06-12 17:23:46.41]: [iTMSTransporter] Error: Could not create the Java Virtual Machine.
WARN [2020-06-12 17:23:46.41]: [iTMSTransporter] Error: A fatal exception has occurred. Program will exit.
INFO [2020-06-12 17:23:46.41]: iTunes Transporter output above ^
ERROR [2020-06-12 17:23:46.41]: The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
```

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Upload to test flight(pilot) failed.

##### Command executed
```
fastlane beta
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
INFO [2020-06-12 17:23:37.64]: -------------------
INFO [2020-06-12 17:23:37.64]: --- Step: pilot ---
INFO [2020-06-12 17:23:37.64]: -------------------
INFO [2020-06-12 17:23:37.64]: Login to App Store Connect (xx@yy.com.com)
Reading keychain entry, because either user or password were empty
Loading session from '$HOME/.fastlane/spaceship/xx@yy.com.com/cookie'
Looking for App Store Connect Team with ID XXXXXXXX
INFO [2020-06-12 17:23:42.47]: Login successful
DEBUG [2020-06-12 17:23:42.47]: App identifier (com.xx.yy)
INFO [2020-06-12 17:23:44.17]: Ready to upload new build to TestFlight (App: YYYYYYY)...
DEBUG [2020-06-12 17:23:44.17]: App Platform (ios)
INFO [2020-06-12 17:23:44.73]: Wrote XML data to '/var/folders/yb/4ld8w4jd2q76r0ym20jbby3w0000gn/T/d20200612-75256-x4pd0e/xxxxxxx.itmsp'
INFO [2020-06-12 17:23:44.73]: Fetching password for transporter from environment variable named `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`
INFO [2020-06-12 17:23:44.73]: Going to upload updated app to App Store Connect
INFO [2020-06-12 17:23:44.73]: This might take a few minutes. Please don't interrupt the script.
DEBUG [2020-06-12 17:23:44.73]: /usr/local/itms/java/bin/java -Djava.ext.dirs=/usr/local/itms/java/lib/ext -XX:NewSize=2m -Xms32m -Xmx1024m -Xms1024m -Djava.awt.headless=true -Dsun.net.http.retryPost=false -jar /usr/local/itms/lib/itmstransporter-launcher.jar -m upload -u xx@yy.com.com -p YourPassword -f /var/folders/yb/4ld8w4jd2q76r0ym20jbby3w0000gn/T/d20200612-75256-x4pd0e/xxxxxxx.itmsp -t DAV,Signiant -k 100000 2>&1
WARN [2020-06-12 17:23:46.41]: [iTMSTransporter] -Djava.ext.dirs=/usr/local/itms/java/lib/ext is not supported.  Use -classpath instead.

WARN [2020-06-12 17:23:46.41]: [iTMSTransporter] Error: Could not create the Java Virtual Machine.

WARN [2020-06-12 17:23:46.41]: [iTMSTransporter] Error: A fatal exception has occurred. Program will exit.

INFO [2020-06-12 17:23:46.41]: iTunes Transporter output above ^
ERROR [2020-06-12 17:23:46.41]: The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
WARN [2020-06-12 17:23:46.41]: Lane Context:
INFO [2020-06-12 17:23:46.41]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :IPA_OUTPUT_PATH=>"$HOME/ios/Runner.ipa", :XCODEBUILD_ARCHIVE=>"$HOME/Library/Developer/Xcode/Archives/2020-06-12/Runner 2020-06-12 17.22.37.xcarchive", :DSYM_OUTPUT_PATH=>"$HOME/ios/Runner.app.dSYM.zip"}
ERROR [2020-06-12 17:23:46.41]: Error uploading ipa file, for more information see above
INFO [2020-06-12 17:23:46.41]: Successfully generated documentation at path '$HOME/ios/fastlane/README.md'

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 3    | cocoapods                  | 2           |
| 4    | gym                        | 63          |
| 💥   | pilot                      | 8           |
+------+----------------------------+-------------+

ERROR [2020-06-12 17:23:46.42]: fastlane finished with errors
Traceback (most recent call last):
	29: from $HOME/.gem/bin/fastlane:23:in `<main>'
	28: from $HOME/.gem/bin/fastlane:23:in `load'
	27: from $HOME/.gem/gems/fastlane-2.149.1/bin/fastlane:23:in `<top (required)>'
	26: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	25: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	24: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	23: from $HOME/.gem/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	22: from $HOME/.gem/gems/fastlane-2.149.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	21: from $HOME/.gem/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	20: from $HOME/.gem/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	19: from $HOME/.gem/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	18: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	17: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	16: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	15: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	14: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	13: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	12: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	11: from Fastfile:35:in `block (2 levels) in parsing_binding'
	10: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	 9: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	 8: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	 7: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	 6: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
	 5: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 4: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
	 3: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/actions/upload_to_testflight.rb:16:in `run'
	 2: from $HOME/.gem/gems/fastlane-2.149.1/pilot/lib/pilot/build_manager.rb:37:in `upload'
	 1: from $HOME/.gem/gems/fastlane-2.149.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
$HOME/.gem/gems/fastlane-2.149.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': Error uploading ipa file, for more information see above (FastlaneCore::Interface::FastlaneError)
	29: from $HOME/.gem/bin/fastlane:23:in `<main>'
	28: from $HOME/.gem/bin/fastlane:23:in `load'
	27: from $HOME/.gem/gems/fastlane-2.149.1/bin/fastlane:23:in `<top (required)>'
	26: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	25: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	24: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	23: from $HOME/.gem/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	22: from $HOME/.gem/gems/fastlane-2.149.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	21: from $HOME/.gem/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	20: from $HOME/.gem/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	19: from $HOME/.gem/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	18: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	17: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	16: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	15: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	14: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	13: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	12: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	11: from Fastfile:35:in `block (2 levels) in parsing_binding'
	10: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	 9: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	 8: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	 7: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	 6: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
	 5: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 4: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
	 3: from $HOME/.gem/gems/fastlane-2.149.1/fastlane/lib/fastlane/actions/upload_to_testflight.rb:16:in `run'
	 2: from $HOME/.gem/gems/fastlane-2.149.1/pilot/lib/pilot/build_manager.rb:37:in `upload'
	 1: from $HOME/.gem/gems/fastlane-2.149.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
$HOME/.gem/gems/fastlane-2.149.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Error uploading ipa file, for more information see above (FastlaneCore::Interface::FastlaneError)
(envs) A19:ios $
(envs) A19:ios $ sh a.sh export FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD=issl-vkgp-whao-pjxq
^CTraceback (most recent call last):
	35: from $HOME/.gem/bin/fastlane:23:in `<main>'
	34: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:303:in `activate_bin_path'
	33: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:303:in `synchronize'
	32: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:305:in `block in activate_bin_path'
	31: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:242:in `finish_resolve'
	30: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/request_set.rb:435:in `resolve_current'
	29: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/request_set.rb:423:in `resolve'
	28: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver.rb:188:in `resolve'
	27: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/resolver.rb:42:in `resolve'
	26: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:78:in `resolve'
	25: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:137:in `process_topmost_state'
	24: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:319:in `attempt_to_activate'
	23: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:402:in `attempt_to_activate_new_spec'
	22: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:441:in `activate_spec'
	21: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:458:in `require_nested_dependencies_for'
	20: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:466:in `push_state_for_requirements'
	19: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:51:in `sort_dependencies'
	18: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:69:in `with_no_such_dependency_error_handling'
	17: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:52:in `block in sort_dependencies'
	16: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver.rb:277:in `sort_dependencies'
	15: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver.rb:277:in `with_index'
	14: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver.rb:277:in `sort_by'
	13: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver.rb:277:in `each'
	12: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver.rb:283:in `block in sort_dependencies'
	11: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver.rb:226:in `search_for'
	10: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver.rb:201:in `find_possible'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver/current_set.rb:10:in `find_all'
	 8: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/dependency.rb:280:in `matching_specs'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:847:in `stubs_for'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:788:in `installed_stubs'
	 5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:795:in `map_stubs'
	 4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:795:in `flat_map'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:795:in `each'
	 2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:798:in `block in map_stubs'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:774:in `gemspec_stubs_in'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/util.rb:129:in `glob_files_in_dir': Interrupt
 </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.4                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | ~/.gem/bin/fastlane                                            |
| Host                        | Mac OS X 10.15.4 (19E287)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.5                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.3"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.xx.yy" # The bundle identifier of your app
apple_id "xx@yy.com" # Your Apple email address

team_id "xxxxxxxx" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.149.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.13.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.73.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.0        |
| googleauth                | 0.12.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.2        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.5.1        |
| google-cloud-storage      | 1.26.2       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.329.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.1.4        |
| aws-sdk-core              | 3.99.1       |
| aws-sdk-kms               | 1.34.1       |
| aws-sdk-s3                | 1.68.1       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-06-12**
</details>

**Comment by janpio** [comment]
Have you tried restarting your computer? The JVM not being able to start often goes away on  restart.

**Comment by pedia** [comment]
No for restart computer.

Succeed after changed `fastlane_core/lib/fastlane_core/itunes_transporter.rb`:
```ruby
  # Generates commands and executes the iTMSTransporter by invoking its Java app directly, to avoid the crazy parameter
  # escaping problems in its accompanying shell script.
  class JavaTransporterExecutor < TransporterExecutor
    def build_upload_command(username, password, source = "/tmp", provider_short_name = "")
      [
        Helper.transporter_java_executable_path.shellescape,
        # "-Djava.ext.dirs=#{Helper.transporter_java_ext_dir.shellescape}",
        '-DWORootDirectory=',
        '-DWOLocalRootDirectory=',
        '-DWOUserDirectory=/',
        '-DWOEnvClassPath=',
        '-DWOApplicationClass=',
        '-DWOPlatform=MacOS',
        '-Dtransporter.client=Xcode',
        '-Dtransporter.client.version=11.5.0\(11E608c\)',
        '-p',
        '/usr/local/itms/modules',
        '--add-modules=java.activation,java.net.http,java.sql,java.xml,java.xml.bind',
        '--add-exports=java.base/sun.security.provider.certpath=ALL-UNNAMED',
        '--add-opens=java.xml/com.sun.org.apache.xalan.internal.xsltc.trax=ALL-UNNAMED',
        '-XX:NewSize=2m',
        '-Xms32m',
        '-Xmx1024m',
        '-Xms1024m',
        '-Djava.awt.headless=true',
        '-Dsun.net.http.retryPost=false',
        java_code_option,
        '-m upload',
        "-u #{username.shellescape}",
        "-p #{password.shellescape}",
        "-f #{source.shellescape}",
        additional_upload_parameters, # that's here, because the user might overwrite the -t option
        '-k 100000',
        ("-itc_provider #{provider_short_name}" unless provider_short_name.to_s.empty?),
        '2>&1' # cause stderr to be written to stdout
      ].compact.join(' ') # compact gets rid of the possibly nil ENV value
    end
```

- remove Djava.ext.dirs
- add `-DWOEnvClassPath=`
- Dir.chdir to `/usr/local/itms/modules` before start java

It's same as how Xcode call `itms`.

**Comment by janpio** [comment]
Can you open a PR that changes this everywhere if this works better?

**Comment by pedia** [comment]
I am not familiar with Ruby. 

The `upload command` copy from running XCode with `ps -axwwo user,pid,ppid,pgid,command | grep java`

**Comment by pedia** [comment]
@janpio 
Is any useful for an ugly PR(not familiar with Ruby)?

**Comment by janpio** [comment]
Absolutely. A secret: I also do not know ruby and have been active here for quite some time :)

**Comment by Martine1z** [comment]
I am also facing this issue, thanks for your information [prepaidgiftbalance](https://prepaidgiftbalance.net/)
