### ISSUE TITLE
[snapshot] Multiple iOS versions + interface appearance configurations in a single Snapfile

### ISSUE THREAD

**Issue by cyrillelegrand** [fastlane/fastlane#16594]
Hello,

I need to generate screenshots of my app in different configurations, for example :

- iPhone SE, iOS 11
- iPhone SE, iOS 13, Light Mode
- iPhone SE, iOS 13, Dark Mode
- iPhone X, iOS 13, Light Mode
- iPhone X, iOS 13, Dark Mode

For now it seems like I can only specify a global `dark_mode(true)` setting in my Snapfile, and no way to have multiple iOS versions for the same device.

I'd like to add that the goal is to make our CI server handle the screenshots on each build, so I cannot create non-default simulators there.

How can I achieve this without writting several Snapfiles and running them one after the other (which breaks the nice html report of all configurations)?

Thanks for any advice.

---

✅ fastlane environment ✅

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.4                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.24.0                          |
| Installation Source         | ~/.rbenv/versions/2.4.1/bin/fastlane        |
| Host                        | Mac OS X 10.15.4 (19E287)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2s  28 May 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.5                                        |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.149.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                | Version   | Update-Status  |
| --------------------- | --------- | -------------- |
| fastlane-plugin-badge | undefined | 💥 Check failed |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.73.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| json                      | 2.0.2        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.0.2        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| faraday                   | 0.17.3       |
| multi_json                | 1.13.1       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.9.0        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.2.0        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| openssl                   | 2.0.3        |
| io-console                | 0.4.6        |
| CFPropertyList            | 3.0.2        |
| babosa                    | 1.0.3        |
| addressable               | 2.7.0        |
| psych                     | 2.2.2        |
| jmespath                  | 1.4.0        |
| aws-eventstream           | 1.1.0        |
| aws-sdk-core              | 3.99.0       |
| aws-sdk-s3                | 1.68.0       |
| aws-sdk-kms               | 1.34.0       |
| aws-partitions            | 1.328.0      |
| aws-sigv4                 | 1.1.4        |
</details>

*generated on:* **2020-06-11**
</details>

**Comment by thislooksfun** [comment]
I second this. Being able to take both sets of screenshots in a single command would be great. Especially if you could mix and match (i.e.  being able to automatically generate an image set like [Safe Timer](https://apps.apple.com/app/apple-store/id1512032981?pt=121500132&ct=web&mt=8))

**Comment by M1urphy** [comment]
Thanks for sharing this information [dqfansurvey](https://www.dqfansurvey.org/)

**Comment by thislooksfun** [comment]
I looked through the latest documentation and was unable to find any way to do this, therefore I believe it is not yet implemented and should be kept open.
