### ISSUE TITLE
download_dsyms `build_number` parameter format wrong? (Spaceship related?)

### ISSUE THREAD

**Issue by ChristopherDrum** [fastlane/fastlane#16605]
### New Issue Checklist

- [x] Updated fastlane to the latest version (running 2.149.1)
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Trying to download dSYM files and submit for apple review an explicit build number.
[According to documentation](https://docs.fastlane.tools/actions/download_dsyms/) the command takes a version number and a build number in the form
`download_dsyms(version: "1.0.0", build_number: "345")`

As I understand it, in a CLI context this would be:
`fastlane run download_dsyms version:"1.0.0" build_number:"345" `

This absolutely fails for me every time, because I'm told that no dSYM files exist for build `345`  (in keeping with the above example) and which makes itself more clear when I run the command in `--vebose` mode
```
DEBUG [2020-06-15 11:04:30.75]: Found build version: 1.0.0.345 , comparing to supplied build_number: 345
DEBUG [2020-06-15 11:04:30.75]: build_version: 1.0.0.345 doesn't match: 345
```

**However I get success if I put the entire explicit build to find:**
`fastlane run download_dsyms version:"1.0.0" build_number:"1.0.0.345" `
(which is not what documentation says needs to be done)

This also works if I leave `version` off 
`fastlane run download_dsyms build_number:"1.0.0.345" `
Though it is much, much slower and does not short-circuit upon successful discovery of the specific dSYM file (script seems to continue looking, as though there could be multiple with the same build number? I don't think that is even possible 🤔 )

This *also* seems to be an issue with `deliver` because my submission attempt last Friday received the error `Build number: 345 does not exist` (I did not have an opportunity to test pushing the entire `1.0.0.345` build number; had to submit manually at that time and investigate this issue deeply after the weekend)

The [deliver documentation](https://docs.fastlane.tools/actions/deliver/) shows this example
```
  deliver(
    build_number: '830',
    submit_for_review: true,
    automatic_release: true,
    force: true, # Skip HTMl report verification
    skip_metadata: true,
    skip_screenshots: true,
    skip_binary_upload: true
  )
```
So, I don't know if the API has changed in an unexpected way recently, or if the documentation is just out of date. But there is definitely a mismatch between the two.

##### Command executed
`fastlane run download_dsyms version:"1.0.0" build_number:"345" `

##### Complete output when running fastlane, including the stack trace and command used
```
[11:20:49]: Looking for dSYM files for '<REDACTED>' on platform ios v1.0.0 (345)
[11:20:52]: No dSYM files found on App Store Connect - this usually happens when no recompiling has happened yet
```

**Comment by ChristopherDrum** [comment]
@fastlane-bot Sorry, buddy, but it isn't particularly relevant to this specific issue, I think.

**Comment by janpio** [comment]
Isn't the build number something you define yourself?

**Comment by ChristopherDrum** [comment]
@janpio Yes, of course. I'm saying that sending "build number" by itself, as it shows in the documentation, does not work. But sending a full "version" . "build_number" concatenated as a single string for that parameter does work.

**Comment by ChristopherDrum** [comment]
(apologies for the mistake here; I had NO idea you could set a build number to a multi-part, dot-separated value... I really thought it could only be a single-digit integer and so my misunderstanding on that led to my misunderstanding of this API usage)

**Comment by janpio** [comment]
Can or should we make this more obvious in the docs somehow? Seems your usage pattern is not the one we use there.
