### ISSUE TITLE
Error fastlane-plugin-firebase_app_distribution

### ISSUE THREAD

**Issue by renatosousa-git** [fastlane/fastlane#16600]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[16:25:53]: Error loading plugin 'fastlane-plugin-firebase_app_distribution': No such file or directory - which firebase
[16:25:53]: It seems like you wanted to load some plugins, however they couldn't be loaded
[16:25:53]: Please follow the troubleshooting guide: https://docs.fastlane.tools/plugins/plugins-troubleshooting/

### Stack

| Key                         | Value                        |
| --------------------------- | ---------------------------- |
| OS                          | UNKNOWN                      |
| Ruby                        | 2.7.0                        |
| Bundler?                    | false                        |
| Git                         | git version 2.25.1.windows.1 |
| Installation Source         | C:/tools/ruby27/bin/fastlane |
| Host                        | Unknown  ()                  |
| Ruby Lib Dir                | C:/tools/ruby27/lib          |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019  |
| Is contained                | false                        |
| Is homebrew                 | false                        |
| Is installed via Fabric.app | false                        |

</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by janpio** [comment]
Did you follow the troubleshooting guide linked?
What else did you try?

**Comment by Brow1n** [comment]
I'm trying to setup CI-CD for Firebase app distribution on my local system [MyKFCExperience](https://mykfcexperience.website/).

**Comment by renatosousa-git** [comment]
This solved for me

https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/issues/40

thank you very much.
