### ISSUE TITLE
Frameit with Arabic, Japanes, Korean or Thai texts fails. 

### ISSUE THREAD

**Issue by fatihyildizhan** [fastlane/fastlane#16604]
### New Issue Checklist

- [+] Updated fastlane to the latest version
- [+] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [+] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [+] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Using frameit with Japanes texts fails for some device sizes but works for others.

##### Complete output when running fastlane, including the stack trace and command used
bundle exec fastlane frameit

Bellow you can see two different outcomes: the first screenshot has the texts set correctly in the final image, the second one doesn't.

<details>
  <pre>[✔] 🚀 
[12:18:57]: Using device frames version 'latest'
[✔] Framing screenshot './fastlane/screenshots/ja/iPhone 8-3-Trends.png' 
[12:19:04]: Added frame: '/Users/{MY_USER}/Developer/iOS Projects/{MY_PROJECT}/fastlane/screenshots/ja/iPhone 8-3-Trends_framed.png'
[⠇] Framing screenshot './fastlane/screenshots/ja/iPhone 11 Pro-3-Trends.png' identify: geometry does not contain image `/var/folders/w3/pg8fvbf17v9cwkjm4d88vfzc0000gn/T/mini_magick20191107-89735-1j2e7qb.png' @ warning/attribute.c/GetImageBoundingBox/507.
[⠴] Framing screenshot './fastlane/screenshots/ja/iPhone 11 Pro-3-Trends.png' identify: geometry does not contain image `/var/folders/w3/pg8fvbf17v9cwkjm4d88vfzc0000gn/T/mini_magick20191107-89735-1z0znau.png' @ warning/attribute.c/GetImageBoundingBox/507.
[⠙] Framing screenshot './fastlane/screenshots/ja/iPhone 11 Pro-3-Trends.png' mogrify: geometry does not contain image `/var/folders/w3/pg8fvbf17v9cwkjm4d88vfzc0000gn/T/mini_magick20191107-89735-1j2e7qb.png' @ warning/transform.c/CropImage/643.
[⠇] Framing screenshot './fastlane/screenshots/ja/iPhone 11 Pro-3-Trends.png' mogrify: geometry does not contain image `/var/folders/w3/pg8fvbf17v9cwkjm4d88vfzc0000gn/T/mini_magick20191107-89735-1z0znau.png' @ warning/transform.c/CropImage/643.
[✔] Framing screenshot './fastlane/screenshots/ja/iPhone 11 Pro-3-Trends.png' 
[12:19:20]: Added frame: '/Users/{MY_USER}/Developer/iOS Projects/{MY_PROJECT}/fastlane/screenshots/ja/iPhone 11 Pro-3-Trends_framed.png'</pre>
</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.5                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.2 (Apple Git-127)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.5 (19F101)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.4.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./Fastfile`</summary>

ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: “appname.xcworkspace", scheme: “appname”)
  end
end

</details>

<details><summary>`./Appfile`</summary>

ruby
app_identifier("com.example.appname”) # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.149.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

*No plugins Loaded*

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.16.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.73.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.0        |
| googleauth                | 0.12.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.2        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.5.1        |
| google-cloud-storage      | 1.26.2       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.323.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.1.4        |
| aws-sdk-core              | 3.97.1       |
| aws-sdk-kms               | 1.33.0       |
| aws-sdk-s3                | 1.67.1       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

generated on: *2020-06-14*
</details>

<img width="210" alt="image" src="https://user-images.githubusercontent.com/602600/84603627-71755b80-ae98-11ea-81b9-0a7c5dfb21c2.png"><img width="210" alt="image" src="https://user-images.githubusercontent.com/602600/84603628-73d7b580-ae98-11ea-87d1-a8461ac15ccf.png">

**Comment by fatihyildizhan** [comment]
@fastlane-bot fastlane environment ✅

**Comment by giantramen** [comment]
Having a similar issue with Korean and Japenese, I tried multiple fonts, and am not seeing any text rendered on any screen size for those languages.

**Comment by fatihyildizhan** [comment]
Hi @janpio I think this issue is related to #16625 I also shared the Fastlane environment to help you to figure it out. If there is something to solve this issue, we would like to help you too.

**Comment by ElectrifyPowr** [comment]
We are also having this issue.
It is not just Arabic, Korean, Japanese, and Thai. Following are the language-codes/locales that result in unexpected framed screenshots:

- hy
- zh
- ja
- ko
- hi 
- am
- th
- ar
- bn
- fa
- gu
- ka
- km
- kn
- lo
- ml
- mr
- my
- ne
- pa
- si
- ta
- te

The only workaround we found so far was to remove the `keyword.strings` file. This results in no text in the screenshots, the device frames seem to be better placed but most frames still have some noticeable margin from the top.

**Comment by vinksnojoqs** [comment]
> There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.
> 
> Please make sure to update to the latest `fastlane` version and check if that solves the issue. Let us know if that works for you by adding a comment 👍
> 
> Friendly reminder: contributions are always welcome! Check out [CONTRIBUTING.md](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md) for more information on how to help with `fastlane` and feel free to tackle this issue yourself 💪

I also shared the Fastlane environment to help you to figure it out. If there is something to solve this issue, we would like to help you too.

**Comment by seanrogs** [comment]
What fonts are you using in your Framefile? Not all fonts have the full Unicode character set.

**Comment by rogerluan** [comment]
> What fonts are you using in your Framefile? Not all fonts have the full Unicode character set.

Ping @fatihyildizhan @vinksnojoqs @ElectrifyPowr ☝️ 


Also, is this a regression, or has it never worked before?

**Comment by fatihyildizhan** [comment]
I tried with many fonts. It never worked.  @rogerluan

**Comment by ElectrifyPowr** [comment]
Please re-open this issue, it's still not solved!

@seanrogs we specifically used the **NotoSans** font since it supports every locale we are using.

@rogerluan for us it has **never worked before** with the aforementioned locales.

**Comment by rogerluan** [comment]
Reopening upon request ☝️

**Comment by ElectrifyPowr** [comment]
Have there been any updates?

**Comment by fatihyildizhan** [comment]
Unfortunately no. I am no longer using it. I wish they could solve it.

**Comment by yunhao** [comment]
Frameit use ImageMagick to draw text. I try to use ImageMagick to perform a more complex image operation and encounter the same problem about text and fonts.

I think it's an issue from ImageMagick. Unlike many GUI image editor, ImageMagick won't automatically load system fonts. On macOS, they are `/System/Library/Fonts`, `/Library/Font` and `~/Library/Fonts`.

I haven't dig deep into the source code of Frameit and don't know if Frameit handles fonts properly. However, because it's an issue originated from ImageMagick, I don't think Frameit can solve the problem by itself.

ImageMagick/ImageMagick/issues/3110
