### ISSUE TITLE
Support `changelog_from_git_commits` in `upload_to_play_store`

### ISSUE THREAD

**Issue by kohenkatz** [fastlane/fastlane#16603]
#### Motivation Behind Feature
We use `changelog_from_git_commits` for our iOS apps and we are very happy with how it works. We would like to use it for our Android apps too.

#### Feature Description
Right now, the `upload_to_play_store` action can only read changelogs from the `metadata/LANG/changelogs/VERSION.txt` files. Running `changelog_from_git_commits` builds the changelog but then does not use it, resulting in having no changelog (or the `default.txt` changelog contents) uploaded to Google Play.

I believe that before reading the changelog files in the `metadata` directory, `supply` should check for the presence of `Actions.lane_context[SharedValues::FL_CHANGELOG]` and use it if present. If not present, then the existing behavior should be used.

(Alternatively, the `upload_to_play_store` should be able to accept a `changelog` parameter so we can do something like `upload_to_play_store(changelog: Actions.lane_context[SharedValues::FL_CHANGELOG])`, though that seems like a very bad idea since it requires the user to know the internals of the `changelog_from_git_commits` action.)

#### Alternatives or Workarounds
The one workaround I can think of would be to call `changelog_from_git_commits` and write the contents of `Actions.lane_context[SharedValues::FL_CHANGELOG]` into the changelog directory. There are several problems with this approach though: it requires writing multiple files if there are multiple languages present, it requires figuring out the correct version number to write (or overwriting the `default.txt` file), and it is a hack on top of a feature that the documentation implies should already be supported.

**Comment by kohenkatz** [comment]
related #15779

I will try to get a PR in for this at some point

**Comment by zmeggyesi** [comment]
Any movement on this?  
I'm using Fastlane to deploy a Flutter application to both iOS and Android simultaneously, via Gitlab CI, and being able to supply a generated changelog to both, without having to resort to various workarounds would be great.
