### ISSUE TITLE
Operation not permitted - Library/Application Support/MobileSync (Errno::EPERM)

### ISSUE THREAD

**Issue by HePengCheng520** [fastlane/fastlane#16611]
```
Traceback (most recent call last):
	13: from /usr/local/Cellar/fastlane/2.149.1/libexec/bin/fastlane:23:in `<main>'
	12: from /usr/local/Cellar/fastlane/2.149.1/libexec/bin/fastlane:23:in `load'
	11: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/bin/fastlane:23:in `<top (required)>'
	10: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	 9: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	 8: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	 7: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	 6: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 5: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 4: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 3: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 2: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:121:in `block (2 levels) in run'
	 1: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane/lib/fastlane/setup/setup.rb:56:in `start'
/usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane/lib/fastlane/setup/setup.rb:56:in `[]': [!] Operation not permitted - Library/Application Support/MobileSync (Errno::EPERM)

**Comment by HePengCheng520** [comment]
fastlane init                                  ok  18s  2.2.0 rb  10:07:37
[✔] 🚀
[⠼] Looking for iOS and Android projects in current directory...
Looking for related GitHub issues on fastlane/fastlane...

[⠼] Looking for iOS and Android projects in current directory...➡️  fastlane tests crash - access denied on mobile sync dir
    https://github.com/fastlane/fastlane/issues/16336 [closed] 1 💬
    18 Apr 2020

➡️   [!] Operation not permitted - Library/Application Support/MobileSync (Errno::EPERM)
    https://github.com/fastlane/fastlane/issues/15677 [closed] 0 💬
    18 Jan 2020

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	13: from /usr/local/Cellar/fastlane/2.149.1/libexec/bin/fastlane:23:in `<main>'
	12: from /usr/local/Cellar/fastlane/2.149.1/libexec/bin/fastlane:23:in `load'
	11: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/bin/fastlane:23:in `<top (required)>'
	10: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	 9: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	 8: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	 7: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	 6: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 5: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 4: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 3: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 2: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:121:in `block (2 levels) in run'
	 1: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane/lib/fastlane/setup/setup.rb:56:in `start'
/usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane/lib/fastlane/setup/setup.rb:56:in `[]': [!] Operation not permitted - Library/Application Support/MobileSync (Errno::EPERM)

**Comment by HePengCheng520** [comment]
> It seems like you have not included the output of `fastlane env`
> To make it easier for us help you resolve this issue, please update the issue to include the output of `fastlane env` 👍

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 10.15.5                                                 |
| Ruby                        | 2.5.8                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.12.0                                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.149.1/libexec/bin/fastlane |
| Host                        | Mac OS X 10.15.5 (19F96)                                |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.5/2.5.8/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1f  31 Mar 2020                             |
| Is contained                | false                                                   |
| Is homebrew                 | false                                                   |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 11.4                                                    |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.149.1 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.16.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.73.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.0        |
| googleauth                | 0.12.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.2        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.5.1        |
| google-cloud-storage      | 1.26.2       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.324.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.1.4        |
| aws-sdk-core              | 3.97.1       |
| aws-sdk-kms               | 1.33.0       |
| aws-sdk-s3                | 1.67.1       |
</details>


*generated on:* **2020-06-16**
</details>
[10:21:20]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[10:21:20]: 🙄  Wow, that's a lot of markdown text... should fastlane put it into your clipboard, so you can easily paste it on GitHub? (y/n)

**Comment by HePengCheng520** [comment]
> It seems like you have not included the output of `fastlane env`
> To make it easier for us help you resolve this issue, please update the issue to include the output of `fastlane env` 👍

How do I deal with this problem?

**Comment by janpio** [comment]
Please post the complete output and the command you are running. Right now we can only guess waht you are actually doing.

**Comment by HePengCheng520** [comment]
> Please post the complete output and the command you are running. Right now we can only guess waht you are actually doing.

When I execute fastlane init, the following error is printed, followed by env output，how do I solve this problem？


fastlane init                                   ok  3s  2.2.0 rb  11:15:00
[✔] 🚀
[⠹] Looking for iOS and Android projects in current directory...
Looking for related GitHub issues on fastlane/fastlane...

[⠙] Looking for iOS and Android projects in current directory...➡️  Operation not permitted - Library/Application Support/MobileSync (Errno::EPERM)
    https://github.com/fastlane/fastlane/issues/16611 [open] 4 💬
    10 hours ago

➡️  fastlane tests crash - access denied on mobile sync dir
    https://github.com/fastlane/fastlane/issues/16336 [closed] 1 💬
    a day ago

➡️   [!] Operation not permitted - Library/Application Support/MobileSync (Errno::EPERM)
    https://github.com/fastlane/fastlane/issues/15677 [closed] 0 💬
    18 Jan 2020

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	13: from /usr/local/Cellar/fastlane/2.149.1/libexec/bin/fastlane:23:in `<main>'
	12: from /usr/local/Cellar/fastlane/2.149.1/libexec/bin/fastlane:23:in `load'
	11: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/bin/fastlane:23:in `<top (required)>'
	10: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	 9: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	 8: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	 7: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	 6: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 5: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 4: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 3: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 2: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:121:in `block (2 levels) in run'
	 1: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane/lib/fastlane/setup/setup.rb:56:in `start'
/usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane/lib/fastlane/setup/setup.rb:56:in `[]': [!] Operation not permitted - Library/Application Support/MobileSync (Errno::EPERM)

fastlane env                                 1 err  8s  2.2.0 rb  11:19:05
[✔] 🚀
[11:22:49]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[11:22:52]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 10.15.5                                                 |
| Ruby                        | 2.5.8                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.12.0                                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.149.1/libexec/bin/fastlane |
| Host                        | Mac OS X 10.15.5 (19F96)                                |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.5/2.5.8/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1f  31 Mar 2020                             |
| Is contained                | false                                                   |
| Is homebrew                 | false                                                   |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 11.4                                                    |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.149.1 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.16.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.73.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.0        |
| googleauth                | 0.12.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.2        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.5.1        |
| google-cloud-storage      | 1.26.2       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.324.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.1.4        |
| aws-sdk-core              | 3.97.1       |
| aws-sdk-kms               | 1.33.0       |
| aws-sdk-s3                | 1.67.1       |
</details>


*generated on:* **2020-06-20**
</details>
[11:22:54]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[11:22:54]: 🙄  Wow, that's a lot of markdown text... should fastlane put it
into your clipboard, so you can easily paste it on GitHub? (y/n)

**Comment by janpio** [comment]
One of the suggested issues gives this solution:
https://github.com/fastlane/fastlane/issues/16336#issuecomment-615916657
