### ISSUE TITLE
GITHUB_TOKEN provided by Github Action does not work in fastlane action GithubApiAction

### ISSUE THREAD

**Issue by felginep** [fastlane/fastlane#16618]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When I want to use an action that interacts with Github (like `set_github_release` for instance), I can't make it work on Github Actions with the [GITHUB_TOKEN](https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token) provided by Github.

However, if I generate a [personal token](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line), and pass it to the `api_token` parameter, the command works fine.

To my understanding, it seems the action `GithubApiAction` uses a [Basic](https://github.com/fastlane/fastlane/blob/31ff25306872292d02459d226c8fd982912c1e8a/fastlane/lib/fastlane/actions/github_api.rb#L208) authorization whereas the curl example on the official github page uses a [Bearer](https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#example-calling-the-rest-api) authorization.

##### Command executed
Non working call:
```
set_github_release(
  repository_name: "my_repo",
  api_token: ..., # Token from github, i.e secrets.GITHUB_TOKEN
  ...
)
```

Working call:
```
set_github_release(
  repository_name: "my_repo",
  api_token: ..., # Personal access token
 ...
)
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> Repository my_repo cannot be found, please double check its name and that you provided a valid API token (GITHUB_API_TOKEN) </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.15.5                                          |
| Ruby                        | 2.6.6                                            |
| Bundler?                    | true                                             |
| Git                         | git version 2.27.0                               |
| Installation Source         | /usr/local/lib/ruby/gems/2.6.0/bin/fastlane      |
| Host                        | Mac OS X 10.15.5 (19F101)                        |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.6/2.6.6_1/lib           |
| OpenSSL Version             | OpenSSL 1.1.1f  31 Mar 2020                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode_11.5.app/Contents/Developer/ |
| Xcode Version               | 11.5                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.149.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-changelog | 0.15.0  | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 2.1.4        |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.329.0      |
| aws-sigv4                 | 1.1.4        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.100.0      |
| aws-sdk-kms               | 1.34.1       |
| aws-sdk-s3                | 1.68.1       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.5.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.74.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 1.0.1        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.1.0        |
| signet                    | 0.14.0       |
| googleauth                | 0.12.0       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.2        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.2       |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.16.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-changelog | 0.15.0       |
</details>

*generated on:* **2020-06-16**
</details>

**Comment by bguidolim** [comment]
AFAIK, the token provided by Actions has a very limite scope, you’re doing right using a personal token.

Btw, I would say it’s not a Fastlane issue.

**Comment by felginep** [comment]
The scope here is not the issue. The Github Action token can create a release or a pull request.

The issue is the authentication header in the HTTP call. If I use the _GithubApiAction_ and override the default headers, I can make it work with the GITHUB_TOKEN provided by Github:

<pre>
GithubApiAction.run(
    server_url: params[:api_url],
    api_token: "",
    headers: { 'Authorization' => "Bearer #{params[:github_token]}" } # <----- this line
    http_method: 'POST',
    path: "repos/#{params[:repo]}/pulls",
    body: payload,
    error_handlers: {
      '*' => proc do |result|
        UI.error("GitHub responded with #{result[:status]}: #{result[:body]}")
        return nil
      end
    }
  ) do |result|
    ...  
  end
end
</pre>

**Comment by sjcqs** [comment]
While Personal Access Token uses Basic authentication, GITHUB_TOKEN should be pass inside a Bearer's Authorization header.
https://github.com/fastlane/fastlane/blob/af31cde28495ab64b501e41bcf6ae1975b1ace7d/fastlane/lib/fastlane/actions/github_api.rb#L208

Here the permissions granted to a GITHUB_TOKEN: (cf [Permissions for the Github Token](https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#permissions-for-the-github_token))

Permission | Access type | Access by forked repos
-- | -- | --
actions | read/write | read
checks | read/write | read
contents | read/write | read
deployments | read/write | read
issues | read/write | read
metadata | read | read
packages | read/write | read
pull requests | read/write | read
repository projects | read/write | read
statuses | read/write | read

A GITHUB_TOKEN is a short-live token which is generated at the job start. It expires at when the job finishes. 
On the other hand, a PAT can only expires if it is manually removed by its owner. Leaking a PAT is a bigger liability than leaking a GITHUB_TOKEN. Both should not be leaked and should be kept secure (e.g in a Github secret) but the GITHUB_TOKEN is safer. 

A way to fix the issue could be to add an optional `github_token` parameter to the github related lanes which would be added as a Bearer.

**Comment by michaelst** [comment]
Any update on this issue, I am also running into this. Supporting the github actions bearer token would be great and I would be glad to do the PR if it will be accepted.

**Comment by rogerluan** [comment]
Reopening upon request https://github.com/fastlane/fastlane/issues/17614

**Comment by rogerluan** [comment]
That sounds good to me @dcacenabes ! Thanks for taking the lead here into investigating this issue 💪 Feel free to tag me once you open the PR 😊

**Comment by dcacenabes** [comment]
In order to run this now replace the api_token with api_bearer:

```
set_github_release(
  repository_name: "my_repo",
  api_bearer: ..., # Token from github, i.e secrets.GITHUB_TOKEN
  ...
)
```

**Comment by vguerci** [comment]
Or I guess that you can also simply set this env var on your workflow:
```yaml
        env:
          FL_GITHUB_RELEASE_API_BEARER: ${{ secrets.GITHUB_TOKEN }}
```
