### ISSUE TITLE
download_dsyms trying to use 2FA but doesn't allow to use app-specific password

### ISSUE THREAD

**Issue by stanma** [fastlane/fastlane#16616]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
There is a problem with [download_dsyms](https://docs.fastlane.tools/actions/download_dsyms/) functionality when it is used standalone in the lane. It tries to connect to App Store and requesting 2FA which is fine but totally ignores FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD even if it specified. Just falls back to the 4/6 digits code, which you can't get in the context of CI.

It works fine if you use it after submitting app to the Testflight (with upload_to_testflight) in the same lane (meaning session to the App Store already opened and was not closed) but sometimes it takes up to 30 minutes for App Store's side to recompile app and make dSyms available and if you're on CI you don't want process to wait for so long and bill you minutes.

So I'm using download_dsyms in cron job but then this problem with 2FA appears. There should be a workaround for this.

##### Command executed
bundle exec fastlane downloadDsymsFromTestflight app:XXX

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>
[✔] 🚀 
[14:05:44]: Sending anonymous analytics information
[14:05:44]: Learn more at https://docs.fastlane.tools/#metrics
[14:05:44]: No personal or sensitive data is sent.
[14:05:44]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
[14:05:44]: ----------------------------------------
[14:05:44]: --- Step: Verifying fastlane version ---
[14:05:44]: ----------------------------------------
[14:05:44]: Your fastlane version 2.149.1 matches the minimum requirement of 2.54.0  ✅
[14:05:44]: ------------------------------
[14:05:44]: --- Step: default_platform ---
[14:05:44]: ------------------------------
[14:05:44]: Driving the lane 'ios downloadDsymsFromTestflight' 🚀
[14:05:44]: --------------------------------
[14:05:44]: --- Step: get_version_number ---
[14:05:44]: --------------------------------
[14:05:48]: ----------------------------
[14:05:48]: --- Step: download_dsyms ---
[14:05:48]: ----------------------------
[14:05:49]: Login to App Store Connect (xxx@xxx.xxx)
-------------------------------------------------------------------------------------
Please provide your Apple Developer Program account credentials
You can also pass the password using the `FASTLANE_PASSWORD` environment variable
-------------------------------------------------------------------------------------
Password (for xxx@xxx.xxx): ******************************
Two-step Verification (4 digits code) is enabled for account 'xxx@xxx.com'
More information about Two-step Verification: https://support.apple.com/en-us/HT204152

Please select a trusted device to verify your identity
1. +•• •••• ••••••50	SMS	(1230473009)
</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key | Value |
| fastlane | 2.149.1 |
| OS | Linux 3c65e82475a9 4.19.76-linuxkit #1 SMP Thu Oct 17 19:31:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Ruby | 2.5.8 |
| Bundler? | true |
| Git | git version 2.14.5 |
| Installation Source | /var/task/vendor/bundle/ruby/2.5.0/bin/fastlane |
| Host | Amazon Linux AMI release 2018.03
Kernel \r on an \m Linux 3c65e82475a9 4.19.76-linuxkit #1 SMP Thu Oct 17 19:31:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux (4.19.76-linuxkit) |
| Ruby Lib Dir | /var/lang/lib |
| OpenSSL Version | OpenSSL 1.0.1k 8 Jan 2015 |
| Is contained | false |
| Is homebrew | false |
| Is installed via Fabric.app | false |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.54.0"

default_platform :ios

platform :ios do
  skip_docs

  desc 'Upload symbols to Crashlytics'
  lane :downloadDsymsFromTestflight do |options|
    app = options[:app]
    download_dsyms(
      username: "xxx@xxx.com",
      app_identifier: ENV["APPID"],
      team_id: ENV["TEAMID"],
      version: get_version_number(target: app),
      output_directory: '/tmp'
    ) 
    upload_symbols_to_crashlytics 
  end
end



# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://github.com/fastlane/fastlane#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier ENV["APPID"] # The bundle identifier of your app

apple_id ENV["USERNAME"] # Your Apple email address

team_id ENV["TEAMID"] # Developer Portal Team ID

itc_team_id ENV["TEAMID"]

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.149.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| bundler                   | 2.1.4        |
| CFPropertyList            | 3.0.2        |
| concurrent-ruby           | 1.1.6        |
| i18n                      | 0.9.5        |
| minitest                  | 5.14.1       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.7        |
| activesupport             | 4.2.11.3     |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| httpclient                | 2.8.3        |
| json                      | 2.3.0        |
| algoliasearch             | 1.27.3       |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.327.0      |
| aws-sigv4                 | 1.1.4        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.98.0       |
| aws-sdk-kms               | 1.33.0       |
| aws-sdk-s3                | 1.67.1       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| netrc                     | 0.11.0       |
| ffi                       | 1.13.1       |
| ethon                     | 0.12.0       |
| typhoeus                  | 1.4.0        |
| cocoapods-core            | 1.9.3        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.3.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| cocoapods-trunk           | 1.5.0        |
| cocoapods-try             | 1.2.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.16.0       |
| cocoapods                 | 1.9.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.5.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.73.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 1.0.1        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.1.0        |
| signet                    | 0.14.0       |
| googleauth                | 0.12.0       |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.2        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.2       |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2020-06-16**
</details>

Would be great to have a workaround for this.  Thank you.

**Comment by Gof123f** [comment]
This doesn't affect your 2FA login at all [Myloweslife](https://www.myloweslife.vip/)?

**Comment by caseyg1204** [comment]
@stanma did you find a work around for this?

**Comment by stanma** [comment]
> @stanma did you find a work around for this?

no. Still actual.
