### ISSUE TITLE
Frameit on Android cannot find title.strings and keyword.strings

### ISSUE THREAD

**Issue by RobertSasak** [fastlane/fastlane#16629]
#### Motivation Behind Feature
Frameit recent updat also support Android. Which is awesome! But there still bit of hassle to setup it correctly along side iOS screenshots. On iOS all screenshots per language are in a flat structure. All screenshots are in one folder. However on Android screenshots for one language are separated into several folders such as _phoneScreenshots_, _sevenInchScreenshots_ and _tenInchScreenshots_. And those folders are already under folder _images_.

Frameit expect _title.strings_ and _keyword.strings_ to live in the same folder as all screenshots. 
https://github.com/fastlane/fastlane/blob/master/frameit/lib/frameit/editor.rb#L500
```rb
strings_path = File.join(File.expand_path("..", screenshot.path), "#{type}.strings")
```

#### Feature Description
I propose to extend current implementation to also look for _title.strings_ and _keyword.strings_ in parent folders.
```rb
strings_path = File.join(File.expand_path("..", screenshot.path), "#{type}.strings")
strings_path = File.join(File.expand_path("../../", screenshot.path), "#{type}.strings") unless File.exist?(strings_path)
strings_path = File.join(File.expand_path("../../../", screenshot.path), "#{type}.strings") unless File.exist?(strings_path)
```

#### Alternatives or Workarounds
At the moment it is possible to have a multiple copies of _title.strings_ and _keyword.strings_ in all different subfolders (_phoneScreenshots_, _sevenInchScreenshots_ and _tenInchScreenshots_). However for a project with 10+ different translations this quick became a mess.

I do not think there is any drawback of checking parent folders for _title.strings_ and _keyword.strings_.

#### Big picture
It would be best to merge _title.strings_ and _keyword.strings_ for both Android and iOS into one folder in the future. However that might be difficult at the moment. I think having a separate copy of _title.strings_ and _keyword.strings_ is a good compromise at the moment.

**Comment by RobertSasak** [comment]
Here is a general issue of folder structure for Android. https://github.com/fastlane/fastlane/issues/16289

**Comment by janpio** [comment]
Looks like a reasonable suggestion.
