### ISSUE TITLE
latest_testflight_build_number can't authorize

### ISSUE THREAD

**Issue by quanght55** [fastlane/fastlane#16620]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Currently I use latest_testflight_build_number to increase build number of my application with my CI. However, it can not authorize to Apple to get latest build number. I already set FASTLANE_APPLICATION_SPECIFIC_PASSWORD. I'm sure that password is correct because I can use it to upload to testflight.
##### Command executed

fastlane run latest_testflight_build_number
##### Complete output when running fastlane, including the stack trace and command used

Login to App Store Connect (xxx@gmail.com)
The login credentials for 'xxx@gmail.com' seem to be wrong
The password was taken from the environment variable
Please make sure it is correct
<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> MacOS: 10.15 </pre>
  <pre> XCode: 11.3 </pre>
  <pre> fastlane: 2.149.1 </pre>
</details>

**Comment by stanma** [comment]
Basically the same issue as in mine - https://github.com/fastlane/fastlane/issues/16616 . Fastlane currently only supports FASTLANE_APPLICATION_SPECIFIC_PASSWORD for submitting to TestFlight seems.

Hope this will be addressed as you can't create Apple ID without 2FA anymore.

**Comment by Batistleman** [comment]
Have you found a solution for this?

**Comment by quanght55** [comment]
@Batistleman actually, i'm using work around for this, store current build number as a artifact on my CI. 

Trigger build -> get artifact + 1 -> Build and delivery -> store artifact again.

**Comment by Drarok** [comment]
Is there a way to _not_ auto-close this? I don't know when Apple stopped allowing accounts without 2FA, but that does indeed appear to be the case now.

`latest_testflight_build_number` appears to _require_ a username and password (and therefore 2FA token) – it refuses to use the API key supplied by `app_store_connect_api_key`.

**Comment by bsarrazin** [comment]
This is still an issue and prevents any kind of automation surrounding build numbers.
For example:

1. CI kicks off a build
2. lane checks remote build number
3. compares to local build number in repo
4. if remote build number is great or equal, lane bumps the build number and commits to repo
5. lane builds app and uploads to TestFlight
6. lane bumps build number one more time for the next build

It would be great if we could prioritize this bug (and reopen it) to allow `latest_testflight_build_number` to programatically authorize.

**Comment by rogerluan** [comment]
> Is there a way to _not_ auto-close this? I don't know when Apple stopped allowing accounts without 2FA, but that does indeed appear to be the case now.
> 
> `latest_testflight_build_number` appears to _require_ a username and password (and therefore 2FA token) – it refuses to use the API key supplied by `app_store_connect_api_key`.

This has been resolved here: https://github.com/fastlane/fastlane/pull/17413

You can now use `api_key` or `api_key_path` options as documented [here](https://docs.fastlane.tools/actions/latest_testflight_build_number/) 👍
