### ISSUE TITLE
Language support for App Store Connect

### ISSUE THREAD

**Issue by fatihyildizhan** [fastlane/fastlane#16625]
### Question Subject
We would like to support all App Store Connect languages. Fastlane is not supporting all of them yet. Is there a way to add this support manually?

When we try to run with like cs, cs_,cs- simulator stuck and nothing happens. There were no any crash or log. It just freezes. iOS natively supports Czech.

#### Question Description
Fastlane supports these: `ALL_LANGUAGES = ["da", "de-DE", "el", "en-AU", "en-CA", "en-GB", "en-US", "es-ES", "es-MX", "fi", "fr-CA", "fr-FR", "id", "it", "ja", "ko", "ms", "nl-NL", "no", "pt-BR", "pt-PT", "ru", "sv", "th", "tr", "vi", "zh-Hans", "zh-Hant"]`

Is there a way to run fastlane for these language codes?
```
catalan-ca
croation-hr
czech-cs
danish-da
arabic-ar
hebrew-he
hindi-hi
hungarian-hu
japanese-ja
korean-ko
polish-pl
romanian-ro
slovak-sk
thai-th
ukrainian-uk
```

This is Apple guide but fastlane has a different format. We couldn't figure it out how to add non-supported by default language.

https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/LanguageandLocaleIDs/LanguageandLocaleIDs.html

**Comment by fatihyildizhan** [comment]
@janpio Is there any news about this topic? If you may guide us, we also want to contribute. We just didn't know how and where to start.

**Comment by janpio** [comment]
I would also have to start looking/searching through the codebase where the fastlane languages come from. 

This is what I would do:
There a) might be an API call to Apple, it b) might just be defined somewhere. 
For a) we would need to figure out if there is another endpiont that has all of the languages.
For a) and b) we would need to figure out where this is used in the codebase and if these places can handle these other languages.

**Comment by joshdholtz** [comment]
@fatihyildizhan Ah, I missed this issue earlier! I will update the languages today/tomorrow 😊

**Comment by joshdholtz** [comment]
@fatihyildizhan Actually... it looks like all of your language codes are supported already 🤔 

| Your List | Supported Value |
| --- | --- |
| catalan-ca | ca |
| croation-hr | hr |
| czech-cs | cs |
| danish-da | da |
| arabic-ar | ar-SA |
| hebrew-he | he |
| hindi-hi | hi |
| hungarian-hu | hu |
| japanese-ja | ja |
| korean-ko | ko |
| polish-pl | pl |
| romanian-ro | ro |
| slovak-sk | sk |
| thai-th | th |
| ukrainian-uk | uk |

☝️ This should do it for you!

**Comment by fatihyildizhan** [comment]
@joshdholtz Yes, fastlane has support for these languages but when I launch the simulator it freezes. No crash and no logs.

Also, we are unable to take screenshots for these languages with frameit: #16604 

I will upgrade my fastlane version to yesterday's release and try it again. Thank you for your time.
