### ISSUE TITLE
Deliver overwrite_screenshots does not clear out all screenshots

### ISSUE THREAD

**Issue by changusmc** [fastlane/fastlane#16633]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Enabled `overwrite_screenshots` and I'm uploading screenshots to a sample app that already has images for phone and tablet for 21 languages from app (A).

The metadata for app (B) I'm uploading has only English for phone.

I can see that the phone screenshot for English was overwritten, however all the other languages and tablet images are still in App Store Connect for app (A)

##### Command executed

`fastlane deliver`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> +--------------------------------------+---------------------------+
|                     deliver 2.149.1 Summary                      |
+--------------------------------------+---------------------------+
| app_identifier                       | com.gedropbox.Reverie     |
| metadata_path                        | fastlane/metadata_to_test |
| screenshots_path                     | fastlane/metadata_to_test |
| overwrite_screenshots                | true                      |
| skip_binary_upload                   | true                      |
| app_version                          | 1.0                       |
| build_number                         | 1.0.0                     |
| ignore_language_directory_validation | true                      |
| force                                | true                      |
| username                             | changd@dropbox.com        |
| platform                             | ios                       |
| edit_live                            | false                     |
| use_live_version                     | false                     |
| skip_screenshots                     | false                     |
| skip_metadata                        | false                     |
| skip_app_version_update              | false                     |
| submit_for_review                    | false                     |
| reject_if_possible                   | false                     |
| automatic_release                    | false                     |
| phased_release                       | false                     |
| reset_ratings                        | false                     |
| run_precheck_before_submit           | true                      |
| precheck_default_rule_level          | warn                      |
| individual_metadata_items            | []                        |
| precheck_include_in_app_purchases    | true                      |
+--------------------------------------+---------------------------+

[09:05:15]: Making sure the latest version on App Store Connect matches '1.0'...
[09:05:16]: '1.0' is the latest version on App Store Connect
[09:05:31]: Will begin uploading metadata for '1.0' on App Store Connect
[09:05:31]: Uploading metadata to App Store Connect for version
[09:06:23]: Uploading app review information to App Store Connect
[09:06:26]: Will begin uploading snapshots for '1.0' on App Store Connect
[09:06:26]: Starting with the upload of screenshots...
[09:06:27]: Removing all previously uploaded screenshots...
[09:09:26]: Uploading 12 screenshots for language en-US
[09:09:26]: Uploading 'fastlane/metadata_to_test/en-US/1_iphone65_1.png'...
[09:09:28]: Uploading 'fastlane/metadata_to_test/en-US/1_iphone6Plus_1.png'...
[09:09:30]: Uploading 'fastlane/metadata_to_test/en-US/2_iphone65_2.png'...
[09:09:32]: Uploading 'fastlane/metadata_to_test/en-US/2_iphone6Plus_2.png'...
[09:09:34]: Uploading 'fastlane/metadata_to_test/en-US/3_iphone65_3.png'...
[09:10:14]: Uploading 'fastlane/metadata_to_test/en-US/3_iphone6Plus_3.png'...
[09:10:16]: Uploading 'fastlane/metadata_to_test/en-US/4_iphone65_4.png'...
[09:10:18]: Uploading 'fastlane/metadata_to_test/en-US/4_iphone6Plus_4.png'...
[09:10:20]: Uploading 'fastlane/metadata_to_test/en-US/5_iphone65_5.png'...
[09:10:21]: Uploading 'fastlane/metadata_to_test/en-US/5_iphone6Plus_5.png'...
[09:10:23]: Uploading 'fastlane/metadata_to_test/en-US/6_iphone65_6.png'...
[09:10:24]: Uploading 'fastlane/metadata_to_test/en-US/6_iphone6Plus_6.png'...
[09:10:26]: Successfully uploaded screenshots to App Store Connect
[09:10:26]: Running precheck before submitting to review, if you'd like to disable this check you can set run_precheck_before_submit to false
[09:10:26]: Running precheck 👮‍♀️ 👮
+--------------------------+-----------------------+
|           Summary for precheck 2.149.1           |
+--------------------------+-----------------------+
| default_rule_level       | warn                  |
| include_in_app_purchases | true                  |
| app_identifier           | com.gedropbox.Reverie |
| username                 | changd@dropbox.com    |
+--------------------------+-----------------------+

[09:10:26]: Checking app for precheck rule violations
[09:10:41]: Reading in-app purchases. If you have a lot, this might take a while
[09:10:41]: You can disable IAP checking by setting the `include_in_app_purchases` flag to `false`
[09:11:06]: Done reading in-app purchases
[09:11:09]: ✅  Passed: No negative  sentiment
[09:11:09]: ✅  Passed: No placeholder text
[09:11:09]: ✅  Passed: No mentioning  competitors
[09:11:09]: ✅  Passed: No future functionality promises
[09:11:09]: ✅  Passed: No words indicating test content
[09:11:09]: ✅  Passed: No curse words
[09:11:09]: ✅  Passed: No words indicating your IAP is free
[09:11:09]: 😵  Failed: Incorrect, or missing copyright date-> using a copyright date that is any different from this current year, or missing a date
[09:11:28]: 😵  Failed: No broken urls-> unreachable URLs in app metadata
+-------------------+----------------+
|         Potential problems         |
+-------------------+----------------+
| Field             | Failure reason |
+-------------------+----------------+
| copyright         | missing: 2020  |
| support URL: (uk) | empty url      |
| support URL: (pl) | empty url      |
+-------------------+----------------+
[09:11:28]: precheck 👮‍♀️ 👮  found one or more potential metadata problems, but this won't prevent fastlane from completing 👍

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | opt_out_usage              | 0           |
| 2    | Verifying fastlane version | 0           |
| 3    | default_platform           | 0           |
| 4    | deliver                    | 377         |
+------+----------------------------+-------------+

[09:11:28]: fastlane.tools just saved you 6 minutes! 🎉

 </pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.5                                     |
| Ruby                        | 2.4.6                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.23.0                |
| Installation Source         | ~/.rvm/gems/ruby-2.4.6/bin/fastlane         |
| Host                        | Mac OS X 10.15.5 (19F101)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.6/lib                |
| OpenSSL Version             | OpenSSL 1.1.1c  28 May 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.5                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.149.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| jwt                       | 2.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mini_mime                 | 1.0.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.16.0       |
| unicode-display_width     | 1.7.0        |
| addressable               | 2.7.0        |
| tty-screen                | 0.8.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| excon                     | 0.75.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| dotenv                    | 2.7.5        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| uber                      | 0.1.0        |
| retriable                 | 3.1.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| os                        | 1.1.0        |
| memoist                   | 0.16.2       |
| googleauth                | 0.13.0       |
| digest-crc                | 0.5.1        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-env          | 1.3.2        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.2       |
| emoji_regex               | 1.0.1        |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.0        |
| aws-partitions            | 1.331.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.100.0      |
| aws-sdk-kms               | 1.34.1       |
| aws-sdk-s3                | 1.69.0       |
| openssl                   | 2.0.9        |
| io-console                | 0.4.6        |
| psych                     | 2.2.2        |
</details>

*generated on:* **2020-06-19**
</details> </pre>
</details>

**Comment by changusmc** [comment]
I also see the similar behavior for `supply`, should I file a separate issue to track that?

**Comment by joshdholtz** [comment]
@changusmc Can you update to `2.150.0.rc2` and see if this is still an issue for you? Thanks! ❤️

**Comment by jl-gogovapps** [comment]
I ran into this as well.  Also doesn't seem like the screenshots can be removed via the UI either 🤦 .  I was not aware of a `overwrite_screenshots` option though.

side note - thanks for the great work @joshdholtz, much praise

**Comment by joshdholtz** [comment]
@jl-gogovapps You’re welcome! So you aren’t able to delete screenshots from the website either? What state is your app/version in?

**Comment by jl-gogovapps** [comment]
We have an existing app, so this is an update:

<img width="239" alt="Screen Shot 2020-06-25 at 8 43 21 PM" src="https://user-images.githubusercontent.com/44532602/85809001-8c5f8f80-b724-11ea-92e6-0a34ddad6e01.png">

**Comment by joshdholtz** [comment]
@jl-gogovapps That is so strange! So just to confirm... You can’t even delete from the website, right?

**Comment by jl-gogovapps** [comment]
That is correct.  Although I will say, I was not aware of the overwrite option even though I hadn't run into this before (we whitelabel apps, so I have many).

**Comment by joshdholtz** [comment]
There must be a bug with somewhere else in App Store Connect that isn’t allowing you to delete those 😔 

And ohhhhhhhhhhh... It looks like the old API would sometimes “replace” a screenshot, not just upload 😱 The new API doesn’t have that same style of functionality. So it seems like `overwrite_screenshots` is _kind of_ necessary for that same behavior 🤔

Thoughts?

**Comment by jl-gogovapps** [comment]
I'll give it a go tonight or tomorrow and report back.  Thanks!

**Comment by joshdholtz** [comment]
Closing this since this should be fixed now! Latest version is `2.150.1`
