### ISSUE TITLE
Failure information is limited in socket server

### ISSUE THREAD

**Issue by rhdeck** [fastlane/fastlane#16631]
### Feature Request

The socket server presently only remits a `failure_information` array with stack traces organized by cause. However, human-usable information, such as that raised by `FastlaneError` are not remitted or displayed on stdout or stderr, making it hard to help a user diagnose their problem. 

#### Feature Description
Basically, we should at a minimum add the `class` and `message` method results of the `StandardError` that is the basis for sending the `failure` payload in the socket server. These two in combination would allow a client to make the kinds of decisions that the `UI` class makes for remitting information to the user. 

The only canonical socket interface for Fastlane is Swift, which uses `payload` as a dictionary. As long as we _extend_ the shape rather than changing already-used keys, this will not break anything. 

#### Alternatives or Workarounds
Since this is a matter of information not coming over the transom, there is no workaround - can't hack what you don't have. 

I am putting together a PR to solve this issue.

**Comment by Siler177** [comment]
On the TCP level the tuple (source ip, source port, destination ip, destination port) must be unique for each simultaneous connection. That means a single client cannot open more than 65535 simultaneous connections to a server. But a server can (theoretically) serve 65535 simultaneous connections per client.
