### ISSUE TITLE
Android screengrab on windows

### ISSUE THREAD

**Issue by Vlastelin1** [fastlane/fastlane#16637]
What is wrong here or is it impossible in principle?
![Безымянный](https://user-images.githubusercontent.com/63870353/85211119-877a9480-b34e-11ea-968c-271689bbf616.png)

**Comment by janpio** [comment]
What happens if you type `appt` in your command line? If it gives you an error, you need to find your local path of it and att that to the `PATH` env var. (But Windows support might be spotty in general.)

**Comment by Vlastelin1** [comment]
> What happens if you type `appt` in your command line? If it gives you an error, you need to find your local path of it and att that to the `PATH` env var. (But Windows support might be spotty in general.)

What should be the path? I got a similar error on mac os. Why is this not in the guides?

**Comment by janpio** [comment]
Because when having a working Android SDK or Studio installation, this is usually taken care of.

I am happy to merge a PR to the documentation that includes these instructions when you figure it out. Fastlane is mostly driven by the community, so by people like you.



> What should be the path?

That depends on your system where you installed the Android SDK and tools.

**Comment by Vlastelin1** [comment]
> Because when having a working Android SDK or Studio installation, this is usually taken care of.
> 
> I am happy to merge a PR to the documentation that includes these instructions when you figure it out. Fastlane is mostly driven by the community, so by people like you.
> 
> > What should be the path?
> 
> That depends on your system where you installed the Android SDK and tools.

What did I forget or did wrong?
![1](https://user-images.githubusercontent.com/63870353/85944562-4f6fe480-b940-11ea-8117-dbe6200936fb.png)

**Comment by janpio** [comment]
The error message is about `aapt`. You need to make sure that is runnable directly in the command line.

**Comment by Vlastelin1** [comment]
> The error message is about `aapt`. You need to make sure that is runnable directly in the command line, then it will hopefully work via fastlane as well.

![Безымянный](https://user-images.githubusercontent.com/63870353/85945722-60bcef00-b948-11ea-9801-de77da458131.png)


I added to path %ANDROID_HOME%\build-tools\30.0.0
But error:
 The `adb` command could not be found relative to your provided ANDROID_HOME at E:\Android\Sdk
Please ensure that the Android SDK is installed and the platform-tools directory is present

[!] adb command not found
