### ISSUE TITLE
Server error got 500

### ISSUE THREAD

**Issue by gavrichards** [fastlane/fastlane#16643]
### New Release Candidate Issue Checklist

- [x] Updated fastlane to the latest release candidate version (2.150.0.rcX)
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Information

- Breaking version: [`2.150.0.rc1`]
- Last working version: [`2.149.1`]
- State of app: [`Prepare for Submission`]
- First version of app?: [`No`]

### Issue Description

The problem occurs at the `upload_to_app_store` stage.

It all seems to be looking good but the script stopped for a few minutes at this point:
```[fastlane] [10:31:42]: Making sure the latest version on App Store Connect matches '2.0.1'...
[fastlane] [10:32:39]: Successfully set the version to '2.0.1'
[fastlane] [10:32:40]: Loading './fastlane/metadata/en-US/description.txt'...
[fastlane] [10:32:40]: Loading './fastlane/metadata/en-US/keywords.txt'...
[fastlane] [10:32:40]: Loading './fastlane/metadata/en-US/release_notes.txt'...
[fastlane] [10:32:40]: Loading './fastlane/metadata/en-US/support_url.txt'...
[fastlane] [10:32:40]: Loading './fastlane/metadata/en-US/marketing_url.txt'...
[fastlane] [10:32:40]: Loading './fastlane/metadata/en-US/promotional_text.txt'...
[fastlane] [10:32:40]: Loading './fastlane/metadata/en-US/name.txt'...
[fastlane] [10:32:40]: Loading './fastlane/metadata/en-US/subtitle.txt'...
[fastlane] [10:32:40]: Loading './fastlane/metadata/en-US/privacy_url.txt'...
[fastlane] [10:32:40]: Loading './fastlane/metadata/en-US/apple_tv_privacy_policy.txt'...
[fastlane] [10:32:40]: Loading './fastlane/metadata/copyright.txt'...
[fastlane] [10:32:40]: Loading './fastlane/metadata/primary_category.txt'...
[fastlane] [10:32:40]: Loading './fastlane/metadata/secondary_category.txt'...
[fastlane] [10:32:40]: Loading './fastlane/metadata/primary_first_sub_category.txt'...
[fastlane] [10:32:40]: Loading './fastlane/metadata/primary_second_sub_category.txt'...
[fastlane] [10:32:40]: Loading './fastlane/metadata/secondary_first_sub_category.txt'...
[fastlane] [10:32:40]: Loading './fastlane/metadata/secondary_second_sub_category.txt'...
[fastlane] [10:32:40]: Loading './fastlane/metadata/review_information/first_name.txt'...
[fastlane] [10:32:40]: Loading './fastlane/metadata/review_information/last_name.txt'...
[fastlane] [10:32:40]: Loading './fastlane/metadata/review_information/phone_number.txt'...
[fastlane] [10:32:40]: Loading './fastlane/metadata/review_information/email_address.txt'...
[fastlane] [10:32:40]: Loading './fastlane/metadata/review_information/demo_user.txt'...
[fastlane] [10:32:40]: Loading './fastlane/metadata/review_information/demo_password.txt'...
[fastlane] [10:32:40]: Loading './fastlane/metadata/review_information/notes.txt'...
[fastlane] [10:32:48]: Will begin uploading metadata for '2.0.1' on App Store Connect
[fastlane] [10:32:48]: Uploading metadata to App Store Connect for localized version 'en-US'
[fastlane] [10:32:48]: Uploading metadata to App Store Connect for localized info 'en-US'
[fastlane] [10:32:50]: Uploading metadata to App Store Connect for version
[fastlane] [10:32:53]: Uploading app review information to App Store Connect
[fastlane] [10:32:55]: Will begin uploading snapshots for '2.0.1' on App Store Connect
[fastlane] [10:32:55]: Starting with the upload of screenshots...
[fastlane] [10:32:56]: Removing all previously uploaded screenshots for 'en-US' 'APP_IPHONE_55'...
[fastlane] [10:33:39]: Removing all previously uploaded screenshots for 'en-US' 'APP_IPHONE_65'...
```

It then appears to give up and continues with
```
[fastlane] [10:35:39]: ----------------------------------------
[fastlane] [10:35:39]: --- Step: Switch to ios cleanUp lane ---
[fastlane] [10:35:39]: ----------------------------------------
[fastlane] [10:35:39]: Cruising over to lane 'ios cleanUp' 🚖
[fastlane] [10:35:39]: Cruising back to lane 'ios release' 🚘
```

The only error given is
```
[fastlane] [10:35:39]: Server error got 500
```

### Spaceship Logs

<details>
  <pre># Logfile created on 2020-06-22 10:31:42 +0100 by logger.rb/66358
(...truncated...)
INFO  [10:32:55]: >> GET appScreenshotSets: [undefined body] 
DEBUG [10:32:56]: << GET appScreenshotSets: 200 {"data"=>[{"type"=>"appScreenshotSets", "id"=>"d46f8f36-e3ff-402d-b3f6-c5a97ffa6e46", "attributes"=>{"screenshotDisplayType"=>"APP_IPHONE_55"}, "relationships"=>{"appStoreVersionLocalization"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshotSets/d46f8f36-e3ff-402d-b3f6-c5a97ffa6e46/relationships/appStoreVersionLocalization", "related"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshotSets/d46f8f36-e3ff-402d-b3f6-c5a97ffa6e46/appStoreVersionLocalization"}}, "appScreenshots"=>{"meta"=>{"paging"=>{"total"=>3, "limit"=>10}}, "data"=>[{"type"=>"appScreenshots", "id"=>"b0c46436-bec8-4534-8f03-78f04d45e1c9"}, {"type"=>"appScreenshots", "id"=>"af0a96f6-acbb-4abf-ae83-9dabbd474979"}, {"type"=>"appScreenshots", "id"=>"3af6dcd8-75c5-49d6-bc89-66736786d8d8"}], "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshotSets/d46f8f36-e3ff-402d-b3f6-c5a97ffa6e46/relationships/appScreenshots", "related"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshotSets/d46f8f36-e3ff-402d-b3f6-c5a97ffa6e46/appScreenshots"}}}, "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshotSets/d46f8f36-e3ff-402d-b3f6-c5a97ffa6e46"}}, {"type"=>"appScreenshotSets", "id"=>"766a34d7-ffbc-4835-86f0-ddfecdb3f816", "attributes"=>{"screenshotDisplayType"=>"APP_IPHONE_65"}, "relationships"=>{"appStoreVersionLocalization"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshotSets/766a34d7-ffbc-4835-86f0-ddfecdb3f816/relationships/appStoreVersionLocalization", "related"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshotSets/766a34d7-ffbc-4835-86f0-ddfecdb3f816/appStoreVersionLocalization"}}, "appScreenshots"=>{"meta"=>{"paging"=>{"total"=>3, "limit"=>10}}, "data"=>[{"type"=>"appScreenshots", "id"=>"0469acf8-d283-43fc-b208-0178f511eb94"}, {"type"=>"appScreenshots", "id"=>"9d84fff5-daa3-4b31-b905-13dfdcbecd18"}, {"type"=>"appScreenshots", "id"=>"746b557d-bbc2-40ea-9ba4-133777742518"}], "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshotSets/766a34d7-ffbc-4835-86f0-ddfecdb3f816/relationships/appScreenshots", "related"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshotSets/766a34d7-ffbc-4835-86f0-ddfecdb3f816/appScreenshots"}}}, "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshotSets/766a34d7-ffbc-4835-86f0-ddfecdb3f816"}}, {"type"=>"appScreenshotSets", "id"=>"c354838b-97ba-4eab-98ff-799306815377", "attributes"=>{"screenshotDisplayType"=>"APP_IPAD_PRO_3GEN_129"}, "relationships"=>{"appStoreVersionLocalization"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshotSets/c354838b-97ba-4eab-98ff-799306815377/relationships/appStoreVersionLocalization", "related"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshotSets/c354838b-97ba-4eab-98ff-799306815377/appStoreVersionLocalization"}}, "appScreenshots"=>{"meta"=>{"paging"=>{"total"=>3, "limit"=>10}}, "data"=>[{"type"=>"appScreenshots", "id"=>"690f4e9c-22d8-4867-bc72-9cc29e89d4a2"}, {"type"=>"appScreenshots", "id"=>"ecf6a8b9-ea16-46ac-8e59-ebc49a401dce"}, {"type"=>"appScreenshots", "id"=>"5a5b3b2a-7a08-4f52-8201-89b3589117e1"}], "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshotSets/c354838b-97ba-4eab-98ff-799306815377/relationships/appScreenshots", "related"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshotSets/c354838b-97ba-4eab-98ff-799306815377/appScreenshots"}}}, "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshotSets/c354838b-97ba-4eab-98ff-799306815377"}}, {"type"=>"appScreenshotSets", "id"=>"86b8a135-1a24-4261-8887-29cbd74b9929", "attributes"=>{"screenshotDisplayType"=>"APP_IPAD_PRO_129"}, "relationships"=>{"appStoreVersionLocalization"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshotSets/86b8a135-1a24-4261-8887-29cbd74b9929/relationships/appStoreVersionLocalization", "related"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshotSets/86b8a135-1a24-4261-8887-29cbd74b9929/appStoreVersionLocalization"}}, "appScreenshots"=>{"meta"=>{"paging"=>{"total"=>3, "limit"=>10}}, "data"=>[{"type"=>"appScreenshots", "id"=>"64ee58ea-20c5-4739-9d69-0b2c9dbbc9cd"}, {"type"=>"appScreenshots", "id"=>"1e97f1a0-5255-4294-a43a-1d3456f41fe8"}, {"type"=>"appScreenshots", "id"=>"c1ed52e8-72ac-40e7-a6b4-f876de8c82b0"}], "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshotSets/86b8a135-1a24-4261-8887-29cbd74b9929/relationships/appScreenshots", "related"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshotSets/86b8a135-1a24-4261-8887-29cbd74b9929/appScreenshots"}}}, "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshotSets/86b8a135-1a24-4261-8887-29cbd74b9929"}}], "included"=>[{"type"=>"appScreenshots", "id"=>"b0c46436-bec8-4534-8f03-78f04d45e1c9", "attributes"=>{"fileSize"=>238151, "fileName"=>"ftl_7b9d8fa1fde74a0d009fdb85d582630e_039e4259ed3b47dee2f256bd2d4262f4.png", "sourceFileChecksum"=>"4f87de7f1c1db3cc534143837fec4de0", "imageAsset"=>{"templateUrl"=>"https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/21/b5/68/21b5687e-71f9-0620-b1c1-4cafe56b862c/pr_source.png/{w}x{h}bb.{f}", "width"=>1242, "height"=>2208}, "assetToken"=>"Purple123/v4/21/b5/68/21b5687e-71f9-0620-b1c1-4cafe56b862c/pr_source.png", "assetType"=>"SortedN56ScreenShot", "uploadOperations"=>nil, "assetDeliveryState"=>{"errors"=>[], "warnings"=>nil, "state"=>"COMPLETE"}, "uploaded"=>nil}, "relationships"=>{"appScreenshotSet"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/b0c46436-bec8-4534-8f03-78f04d45e1c9/relationships/appScreenshotSet", "related"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/b0c46436-bec8-4534-8f03-78f04d45e1c9/appScreenshotSet"}}}, "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/b0c46436-bec8-4534-8f03-78f04d45e1c9"}}, {"type"=>"appScreenshots", "id"=>"af0a96f6-acbb-4abf-ae83-9dabbd474979", "attributes"=>{"fileSize"=>194056, "fileName"=>"ftl_3e11794f24aa43f6c8abf79b27f822fa_a843f22c83c3a4a15b4a160f01255ece.png", "sourceFileChecksum"=>"6749bc6286eca9de1e94e4a47f12ef7e", "imageAsset"=>{"templateUrl"=>"https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/5d/8a/a3/5d8aa318-256f-c125-3380-f3d67756b01f/pr_source.png/{w}x{h}bb.{f}", "width"=>1242, "height"=>2208}, "assetToken"=>"Purple113/v4/5d/8a/a3/5d8aa318-256f-c125-3380-f3d67756b01f/pr_source.png", "assetType"=>"SortedN56ScreenShot", "uploadOperations"=>nil, "assetDeliveryState"=>{"errors"=>[], "warnings"=>nil, "state"=>"COMPLETE"}, "uploaded"=>nil}, "relationships"=>{"appScreenshotSet"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/af0a96f6-acbb-4abf-ae83-9dabbd474979/relationships/appScreenshotSet", "related"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/af0a96f6-acbb-4abf-ae83-9dabbd474979/appScreenshotSet"}}}, "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/af0a96f6-acbb-4abf-ae83-9dabbd474979"}}, {"type"=>"appScreenshots", "id"=>"3af6dcd8-75c5-49d6-bc89-66736786d8d8", "attributes"=>{"fileSize"=>125368, "fileName"=>"ftl_a7b12033a37751cde0526b4fa54da311_2adbd27484db29499ae372623d2794af.png", "sourceFileChecksum"=>"9cb0f18851cb36e5c5918ff423aa518d", "imageAsset"=>{"templateUrl"=>"https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/c7/f3/ed/c7f3ed77-4dd6-66be-149f-80c7d838a3b3/pr_source.png/{w}x{h}bb.{f}", "width"=>1242, "height"=>2208}, "assetToken"=>"Purple113/v4/c7/f3/ed/c7f3ed77-4dd6-66be-149f-80c7d838a3b3/pr_source.png", "assetType"=>"SortedN56ScreenShot", "uploadOperations"=>nil, "assetDeliveryState"=>{"errors"=>[], "warnings"=>nil, "state"=>"COMPLETE"}, "uploaded"=>nil}, "relationships"=>{"appScreenshotSet"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/3af6dcd8-75c5-49d6-bc89-66736786d8d8/relationships/appScreenshotSet", "related"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/3af6dcd8-75c5-49d6-bc89-66736786d8d8/appScreenshotSet"}}}, "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/3af6dcd8-75c5-49d6-bc89-66736786d8d8"}}, {"type"=>"appScreenshots", "id"=>"0469acf8-d283-43fc-b208-0178f511eb94", "attributes"=>{"fileSize"=>267886, "fileName"=>"ftl_615ece8ef030589d0e0d0afef8e99178_5a34ce6e0dae5baafc3485927ee93cf9.png", "sourceFileChecksum"=>"def9f0d2741fcede0b6e67097175bffe", "imageAsset"=>{"templateUrl"=>"https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/1d/51/43/1d514305-75e7-47a7-b91c-1cd5c74ad3d0/pr_source.png/{w}x{h}bb.{f}", "width"=>1242, "height"=>2688}, "assetToken"=>"Purple113/v4/1d/51/43/1d514305-75e7-47a7-b91c-1cd5c74ad3d0/pr_source.png", "assetType"=>"SortedD33ScreenShot", "uploadOperations"=>nil, "assetDeliveryState"=>{"errors"=>[], "warnings"=>nil, "state"=>"COMPLETE"}, "uploaded"=>nil}, "relationships"=>{"appScreenshotSet"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/0469acf8-d283-43fc-b208-0178f511eb94/relationships/appScreenshotSet", "related"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/0469acf8-d283-43fc-b208-0178f511eb94/appScreenshotSet"}}}, "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/0469acf8-d283-43fc-b208-0178f511eb94"}}, {"type"=>"appScreenshots", "id"=>"9d84fff5-daa3-4b31-b905-13dfdcbecd18", "attributes"=>{"fileSize"=>218186, "fileName"=>"ftl_762c4f10c12b62941860da1f27ef5961_9e104c2820c676ea89ffa126b44816c6.png", "sourceFileChecksum"=>"cb71df167131c26c762e4906e48c9d59", "imageAsset"=>{"templateUrl"=>"https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/17/e8/68/17e868de-0772-356e-b570-f0d43f61da40/pr_source.png/{w}x{h}bb.{f}", "width"=>1242, "height"=>2688}, "assetToken"=>"Purple123/v4/17/e8/68/17e868de-0772-356e-b570-f0d43f61da40/pr_source.png", "assetType"=>"SortedD33ScreenShot", "uploadOperations"=>nil, "assetDeliveryState"=>{"errors"=>[], "warnings"=>nil, "state"=>"COMPLETE"}, "uploaded"=>nil}, "relationships"=>{"appScreenshotSet"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/9d84fff5-daa3-4b31-b905-13dfdcbecd18/relationships/appScreenshotSet", "related"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/9d84fff5-daa3-4b31-b905-13dfdcbecd18/appScreenshotSet"}}}, "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/9d84fff5-daa3-4b31-b905-13dfdcbecd18"}}, {"type"=>"appScreenshots", "id"=>"746b557d-bbc2-40ea-9ba4-133777742518", "attributes"=>{"fileSize"=>135404, "fileName"=>"ftl_f6deb3e66f2e2a60849f52d315bd6af7_b235781226664972994dbc0848fdcb9c.png", "sourceFileChecksum"=>"7e577d42bd9106690ed02e78c5cad5dc", "imageAsset"=>{"templateUrl"=>"https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/7d/54/43/7d5443f0-116b-f548-243c-c1acecadfaf9/pr_source.png/{w}x{h}bb.{f}", "width"=>1242, "height"=>2688}, "assetToken"=>"Purple113/v4/7d/54/43/7d5443f0-116b-f548-243c-c1acecadfaf9/pr_source.png", "assetType"=>"SortedD33ScreenShot", "uploadOperations"=>nil, "assetDeliveryState"=>{"errors"=>[], "warnings"=>nil, "state"=>"COMPLETE"}, "uploaded"=>nil}, "relationships"=>{"appScreenshotSet"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/746b557d-bbc2-40ea-9ba4-133777742518/relationships/appScreenshotSet", "related"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/746b557d-bbc2-40ea-9ba4-133777742518/appScreenshotSet"}}}, "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/746b557d-bbc2-40ea-9ba4-133777742518"}}, {"type"=>"appScreenshots", "id"=>"690f4e9c-22d8-4867-bc72-9cc29e89d4a2", "attributes"=>{"fileSize"=>229284, "fileName"=>"ftl_7be7673656902778025ae6565e4eef52_1adc95946aebc11d25a46791b788e03a.png", "sourceFileChecksum"=>"e095496650f096bbe8d5316283c90129", "imageAsset"=>{"templateUrl"=>"https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/33/07/ee/3307eed1-9bde-5ee0-41b7-1bd81068e1be/pr_source.png/{w}x{h}bb.{f}", "width"=>2048, "height"=>2732}, "assetToken"=>"Purple113/v4/33/07/ee/3307eed1-9bde-5ee0-41b7-1bd81068e1be/pr_source.png", "assetType"=>"SortedJ320ScreenShot", "uploadOperations"=>nil, "assetDeliveryState"=>{"errors"=>[], "warnings"=>nil, "state"=>"COMPLETE"}, "uploaded"=>nil}, "relationships"=>{"appScreenshotSet"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/690f4e9c-22d8-4867-bc72-9cc29e89d4a2/relationships/appScreenshotSet", "related"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/690f4e9c-22d8-4867-bc72-9cc29e89d4a2/appScreenshotSet"}}}, "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/690f4e9c-22d8-4867-bc72-9cc29e89d4a2"}}, {"type"=>"appScreenshots", "id"=>"ecf6a8b9-ea16-46ac-8e59-ebc49a401dce", "attributes"=>{"fileSize"=>255250, "fileName"=>"ftl_98ec22f5cefe20e9ce4a895c386d0da9_684139e9ee1600c2fe50bb21d228c811.png", "sourceFileChecksum"=>"6ff3582dfe449372c473a5ad65dd5518", "imageAsset"=>{"templateUrl"=>"https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/f9/e0/d6/f9e0d612-78ee-44cf-532b-5009b80ca5a9/pr_source.png/{w}x{h}bb.{f}", "width"=>2048, "height"=>2732}, "assetToken"=>"Purple113/v4/f9/e0/d6/f9e0d612-78ee-44cf-532b-5009b80ca5a9/pr_source.png", "assetType"=>"SortedJ320ScreenShot", "uploadOperations"=>nil, "assetDeliveryState"=>{"errors"=>[], "warnings"=>nil, "state"=>"COMPLETE"}, "uploaded"=>nil}, "relationships"=>{"appScreenshotSet"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/ecf6a8b9-ea16-46ac-8e59-ebc49a401dce/relationships/appScreenshotSet", "related"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/ecf6a8b9-ea16-46ac-8e59-ebc49a401dce/appScreenshotSet"}}}, "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/ecf6a8b9-ea16-46ac-8e59-ebc49a401dce"}}, {"type"=>"appScreenshots", "id"=>"5a5b3b2a-7a08-4f52-8201-89b3589117e1", "attributes"=>{"fileSize"=>138219, "fileName"=>"ftl_015fadc370eaa9a9b39e1088cbd245e2_43c87c1cd0e73433b63de97a0a8be5e9.png", "sourceFileChecksum"=>"d687d7eb8d411ee677a0e2e492cd5b0b", "imageAsset"=>{"templateUrl"=>"https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/04/20/56/0420567d-9a95-e8e9-2e30-f01a8f6f9d80/pr_source.png/{w}x{h}bb.{f}", "width"=>2048, "height"=>2732}, "assetToken"=>"Purple123/v4/04/20/56/0420567d-9a95-e8e9-2e30-f01a8f6f9d80/pr_source.png", "assetType"=>"SortedJ320ScreenShot", "uploadOperations"=>nil, "assetDeliveryState"=>{"errors"=>[], "warnings"=>nil, "state"=>"COMPLETE"}, "uploaded"=>nil}, "relationships"=>{"appScreenshotSet"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/5a5b3b2a-7a08-4f52-8201-89b3589117e1/relationships/appScreenshotSet", "related"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/5a5b3b2a-7a08-4f52-8201-89b3589117e1/appScreenshotSet"}}}, "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/5a5b3b2a-7a08-4f52-8201-89b3589117e1"}}, {"type"=>"appScreenshots", "id"=>"64ee58ea-20c5-4739-9d69-0b2c9dbbc9cd", "attributes"=>{"fileSize"=>229284, "fileName"=>"ftl_7be7673656902778025ae6565e4eef52_422fab1bb064e3d924cdec46818d3b65.png", "sourceFileChecksum"=>"e095496650f096bbe8d5316283c90129", "imageAsset"=>{"templateUrl"=>"https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/5e/70/ef/5e70efda-6bd7-a992-9ef5-236796316aa6/pr_source.png/{w}x{h}bb.{f}", "width"=>2048, "height"=>2732}, "assetToken"=>"Purple123/v4/5e/70/ef/5e70efda-6bd7-a992-9ef5-236796316aa6/pr_source.png", "assetType"=>"SortedJ99ScreenShot", "uploadOperations"=>nil, "assetDeliveryState"=>{"errors"=>[], "warnings"=>nil, "state"=>"COMPLETE"}, "uploaded"=>nil}, "relationships"=>{"appScreenshotSet"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/64ee58ea-20c5-4739-9d69-0b2c9dbbc9cd/relationships/appScreenshotSet", "related"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/64ee58ea-20c5-4739-9d69-0b2c9dbbc9cd/appScreenshotSet"}}}, "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/64ee58ea-20c5-4739-9d69-0b2c9dbbc9cd"}}, {"type"=>"appScreenshots", "id"=>"1e97f1a0-5255-4294-a43a-1d3456f41fe8", "attributes"=>{"fileSize"=>255250, "fileName"=>"ftl_98ec22f5cefe20e9ce4a895c386d0da9_0c3d09ff450878327abb2d70d4791283.png", "sourceFileChecksum"=>"6ff3582dfe449372c473a5ad65dd5518", "imageAsset"=>{"templateUrl"=>"https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/97/d5/d9/97d5d93b-2ddc-253c-02fa-9772ab79007e/pr_source.png/{w}x{h}bb.{f}", "width"=>2048, "height"=>2732}, "assetToken"=>"Purple113/v4/97/d5/d9/97d5d93b-2ddc-253c-02fa-9772ab79007e/pr_source.png", "assetType"=>"SortedJ99ScreenShot", "uploadOperations"=>nil, "assetDeliveryState"=>{"errors"=>[], "warnings"=>nil, "state"=>"COMPLETE"}, "uploaded"=>nil}, "relationships"=>{"appScreenshotSet"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/1e97f1a0-5255-4294-a43a-1d3456f41fe8/relationships/appScreenshotSet", "related"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/1e97f1a0-5255-4294-a43a-1d3456f41fe8/appScreenshotSet"}}}, "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/1e97f1a0-5255-4294-a43a-1d3456f41fe8"}}, {"type"=>"appScreenshots", "id"=>"c1ed52e8-72ac-40e7-a6b4-f876de8c82b0", "attributes"=>{"fileSize"=>138219, "fileName"=>"ftl_015fadc370eaa9a9b39e1088cbd245e2_315abab326c204dcc8807e5fcaa92f5e.png", "sourceFileChecksum"=>"d687d7eb8d411ee677a0e2e492cd5b0b", "imageAsset"=>{"templateUrl"=>"https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/f7/f6/56/f7f65686-cf94-0ec6-2de1-35523cc5d945/pr_source.png/{w}x{h}bb.{f}", "width"=>2048, "height"=>2732}, "assetToken"=>"Purple123/v4/f7/f6/56/f7f65686-cf94-0ec6-2de1-35523cc5d945/pr_source.png", "assetType"=>"SortedJ99ScreenShot", "uploadOperations"=>nil, "assetDeliveryState"=>{"errors"=>[], "warnings"=>nil, "state"=>"COMPLETE"}, "uploaded"=>nil}, "relationships"=>{"appScreenshotSet"=>{"links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/c1ed52e8-72ac-40e7-a6b4-f876de8c82b0/relationships/appScreenshotSet", "related"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/c1ed52e8-72ac-40e7-a6b4-f876de8c82b0/appScreenshotSet"}}}, "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshots/c1ed52e8-72ac-40e7-a6b4-f876de8c82b0"}}], "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/appScreenshotSets?include=appScreenshots&filter%5BappStoreVersionLocalization%5D=b488e77e-6dbc-4d9f-a5e9-f8f819e8f512"}, "meta"=>{"paging"=>{"total"=>4, "limit"=>50}}}
INFO  [10:32:56]: >> DELETE appScreenshots/b0c46436-bec8-4534-8f03-78f04d45e1c9: [undefined body] 
DEBUG [10:32:56]: << DELETE appScreenshots/b0c46436-bec8-4534-8f03-78f04d45e1c9: 204 
INFO  [10:32:56]: >> DELETE appScreenshots/af0a96f6-acbb-4abf-ae83-9dabbd474979: [undefined body] 
DEBUG [10:33:38]: << DELETE appScreenshots/af0a96f6-acbb-4abf-ae83-9dabbd474979: 204 
INFO  [10:33:38]: >> DELETE appScreenshots/3af6dcd8-75c5-49d6-bc89-66736786d8d8: [undefined body] 
DEBUG [10:33:39]: << DELETE appScreenshots/3af6dcd8-75c5-49d6-bc89-66736786d8d8: 204 
INFO  [10:33:39]: >> DELETE appScreenshots/0469acf8-d283-43fc-b208-0178f511eb94: [undefined body] 
DEBUG [10:35:39]: << DELETE appScreenshots/0469acf8-d283-43fc-b208-0178f511eb94: 500 <HTML><HEAD>
<TITLE>Internal Server Error</TITLE>
</HEAD><BODY>
<H1>Internal Server Error - Write</H1>
The server encountered an internal error or misconfiguration and was unable to
complete your request.<P>
Reference&#32;&#35;4&#46;99e11602&#46;1592818539&#46;1c56e88a
</BODY></HTML>

</pre>
</details>

### Environment

<details>
  <pre>### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.5                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.5 (19F101)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.5                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version     | Update-Status |
| -------- | ----------- | ------------- |
| fastlane | 2.150.0.rc1 | ✅ Up-To-Date  |</pre>
</details>

### Mentioning

cc: @joshdholtz

**Comment by mjovkovic** [comment]
Hey, @gavrichards, we've got couple of those too, tried again a few hours later and submitted the app. It looks like a temporary issue on Apple's API. Try to deliver the app again and see if it works.

**Comment by gavrichards** [comment]
@mjovkovic thanks - tried again and it worked.
