### ISSUE TITLE
Two-Step MFA keeps asking for 6-digit code even when entering latest from SMS

### ISSUE THREAD

**Issue by willnix86** [fastlane/fastlane#16647]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When trying to `fastlane init swift` on an existing project, I enter my username (which has Two-Factor Auth enabled). I am then asked to input my 6 digit code, I do, I then see 'Requesting session...' but then see exactly the same message an a request for my 6 digit code again.

```
Two Factor Authentication for account 'XXXXXX' is enabled
Your session cookie has been expired.
Please enter the 6 digit code:
```

```
 {"responseId"=>"1d1ebcd4-8e1e-4630-add8-0072b4517020", "resultCode"=>1100, "resultString"=>"Your session has expired.  Please log in.", "userString"=>"Your session has expired.  Please log in.", "creationTimestamp"=>"2020-06-22T20:46:35Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developer.apple.com/services-account/QH65B2/account/listTeams.action", "httpCode"=>200}
[15:46:35]: An error occurred during the setup process. Falling back to manual setup!
```

##### Command executed
fastlane init swift

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> ### Captured Output

Command Used: `init swift`
<details><summary>Output/Log</summary>

```

DEBUG [2020-06-22 15:29:00.57]: Checking if there are any plugins that should be loaded...
INFO [2020-06-22 15:29:00.60]: Detected iOS/Mac project in current directory...
INFO [2020-06-22 15:29:00.60]: This setup will help you get up and running in no time.
INFO [2020-06-22 15:29:00.60]: fastlane will check what tools you're already using and set up
INFO [2020-06-22 15:29:00.60]: the tool automatically for you. Have fun! 
INFO [2020-06-22 15:29:00.60]: $ xcodebuild -list -workspace ./XXXXX.xcworkspace
INFO [2020-06-22 15:29:02.73]: $ xcodebuild -showBuildSettings -workspace ./LetsChat.xcworkspace -scheme DropDown
WARN [2020-06-22 15:29:04.01]: Your Apple ID (e.g. fastlane@krausefx.com): 

Looking for related GitHub issues on fastlane/fastlane...
Search query: Could not retrieve response as fastlane runs in non-interactive mode

URL: https://api.github.com/search/issues?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode+repo:fastlane/fastlane
➡️  Could not retrieve response as fastlane runs in non-interactive mode
   https://github.com/fastlane/fastlane/issues/15548 [closed] 8 💬
   27 Feb 2020

➡️  How to handle plugin installation interaction on jenkins
   https://github.com/fastlane/fastlane/issues/16001 [closed] 2 💬
   11 Apr 2020

➡️  `factory': [!] Can't find class 'adhoc' (RuntimeError)
   https://github.com/fastlane/fastlane/issues/15870 [closed] 3 💬
   10 Mar 2020

and 46 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.5                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.15.5 (19F101)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.5                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.28.3  | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.13.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.17.0       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.1       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.13.1       |
</details>

*generated on:* **2020-06-22**
</details></pre>
</details>

**Comment by marinagosson** [comment]
+1

**Comment by janpio** [comment]
@marinagosson Please open a new issue and fill the issue template.

**Comment by radoman93** [comment]
Same issue. Seems like the Faslane is not using available session and keeps asking for SMS 2FA

**Comment by willnix86** [comment]
Any more thoughts on my initial issue?

**Comment by FelipeLimaDeSouza** [comment]
I'm with the same problem. Any news about this?

**Comment by cbedoy** [comment]
@marinagosson I've faced same issue, but I fixed using ```fastlane match```.

https://docs.fastlane.tools/actions/match/
