### ISSUE TITLE
create a plugin which depends on another plugin.

### ISSUE THREAD

**Issue by shiyj** [fastlane/fastlane#16650]
HI, I want to create a plugin `PL1` which depends on plugin `PL2` `PL3` `PL4` `PL5` etc. .

But I don't want to use it by executing `fastlane add_plugin PL2 PL3 ...` repeatedly, how can i add all the dependency by just one command `fastlane add_plugin PL1`?

**Comment by shiyj** [comment]
> It seems like you have not included the output of `fastlane env`
> To make it easier for us help you resolve this issue, please update the issue to include the output of `fastlane env` 👍

NO,  this issue does not need it.

**Comment by minuscorp** [comment]
A plugin is just a gem, so add to your gemspec the dependency to that gem.

**Comment by shiyj** [comment]
> A plugin is just a gem, so add to your gemspec the dependency to that gem.

@minuscorp hi, thanks for your reply.  I have added all the dependencies in the `fastlane-plugin-mypluginaction.gemspec` file. but I need to call another plugin's action( eg.`fastlane-plugin-otherpluginaction`) in my plugin's action. if I don't add  this plugin in my `Pluginfile` , fastlane cannot load `fastlane-plugin-otherpluginaction` as a plugin, then I got an error message: `[!] Could not find action, lane or variable 'otherpluginaction'.`

Here is the code in my plugin's action

```ruby
    def call_another_plugin_action
      # it's OK when call fastlane's inner action
      upload_to_testflight(params)
      # Could not find this action
      otherpluginaction(params)
    end

    def method_missing(method_sym, *arguments, &_block)
      @runner.trigger_action_by_name(method_sym, '.', false, *arguments)
    end
```

**Comment by shiyj** [comment]
I solve this problem by adding a ruby file under `helper` folder:

```ruby

def inject_plugin_manager
  Fastlane::PluginManager.class_eval do
    alias_method :my_available_plugins, :available_plugins
    def available_plugins
      plugins = my_available_plugins
      dependnecies = ['fastlane-plugin-pl1','fastlane-plugin-pl2','fastlane-plugin-pl3','fastlane-plugin-pl4']
      dependnecies.each { |one| plugins << one unless plugins.include? one}
      plugins
    end
  end
  Fastlane.plugin_manager.load_plugins
end

inject_plugin_manager

```

But I don't think this is good solution. Can we add a `load_custom_plugin(name)` method to the `Fastlane::PluginManager`? so we can load a plugin which was not added in `Pluginfile` before our custom action run.

**Comment by minuscorp** [comment]
As I said, I don't think this is needed at all, in your gemspec your can require the other plugins and bundler will do the rest. You publish your repository with a gemspec and dependencies, fastlane will detect as such when yours is added.
