### ISSUE TITLE
[DELIVER] Support new App Store Connect APIs ✨

### ISSUE THREAD

**Issue by kdawgwilk** [fastlane/fastlane#16653]
#### Motivation Behind Feature

Just in the last few weeks, Apple broke some undocumented APIs that fastlane was using to interact with App Store Connect.  Fastlane should prefer to use documented public APIs where possible to avoid these kinds of situations in the future.

[What's new in App Store Connect](https://developer.apple.com/videos/play/wwdc2020/10651/
)
> We're excited to be adding two powerful new sets of API.  We'll be introducing a suite of app metadata API that will let you manage your presence on the App Store as well as a new power and performance API. They'll let you download the same aggregate data that drives the new power and performance analysis tools in Xcode.  In fact, just between these two new categories of API functionality, **we're adding over 200 new endpoints**.  For app metadata, you'll be able to do things like create new App Store versions, set pricing and availability, edit app and version metadata, associate builds to your App Store versions, and submit those versions for review.  

Another session later this week will go more in-depth [Expanding automation with the App Store Connect API](https://developer.apple.com/videos/play/wwdc2020/10004/)

#### Feature Description

This can be more fleshed out later in the week when the other session becomes available to give more concrete info on what APIs will be available

#### Alternatives or Workarounds

Continue to use undocumented APIs that might break in the future

**Comment by joshdholtz** [comment]
Please see https://github.com/fastlane/fastlane/pull/16640 and https://github.com/fastlane/fastlane/issues/16639 😊 

Its already mostly done and in available for testing in `2.150.0.rc2`
