### ISSUE TITLE
Password for login keychain logged in clear text

### ISSUE THREAD

**Issue by Landschaft** [fastlane/fastlane#16661]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
match 2.149.1 prompts for the user's login.keychain-db password. When the password is entered, match will log it in cleartext (INFO level) to standard output:

Example: Here I entered 'asdf' as password:

    WARN [2020-06-24 15:09:23.68]: This passphrase will be stored in your local keychain with the name fastlane_keychain_login and used in future runs
    WARN [2020-06-24 15:09:23.68]: This prompt can be avoided by specifying the 'keychain_password' option or 'MATCH_KEYCHAIN_PASSWORD' environment variable
      [2020-06-24 15:09:23.68]: Password for login keychain: ****
      [2020-06-24 15:09:28.45]: Type passphrase again: ****
    [⠋] Setting key partition list... (this can take a minute if there are a lot of keys installed) INFO [2020-06-24 15:09:29.73]: $ security set-key-partition-list -S apple-tool:,apple: -s -k asdf (...)/Library/Keychains/login.keychain-db 1> /dev/null

I would expect fastlane match to mask passwords in the logs.

##### Command executed

match

### Environment

<details>
  <pre> <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                             |
| --------------------------- | ----------------------------------------------------------------- |
| OS                          | 10.15.5                                                           |
| Ruby                        | 2.6.5                                                             |
| Bundler?                    | false                                                             |
| Git                         | git version 2.24.3 (Apple Git-128)                                |
| Installation Source         | /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.149.1/bin/fastlane |
| Host                        | Mac OS X 10.15.5 (19F101)                                         |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.6.5/lib                                  |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                                       |
| Is contained                | false                                                             |
| Is homebrew                 | false                                                             |
| Is installed via Fabric.app | false                                                             |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                       |
| Xcode Version               | 11.5                                                              |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.149.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.14.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.2        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.71.1       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday                   | 0.17.0       |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.3       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.7        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.9.0        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.4.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.306.0      |
| aws-eventstream           | 1.0.3        |
| aws-sigv4                 | 1.1.1        |
| aws-sdk-core              | 3.94.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.63.0       |
| forwardable               | 1.3.1        |
| logger                    | 1.4.2        |
| stringio                  | 0.1.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| json                      | 2.3.0        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.3        |
| date                      | 3.0.0        |
| fileutils                 | 1.4.1        |
| io-console                | 0.5.4        |
| zlib                      | 1.1.0        |
| rexml                     | 3.2.3        |
| etc                       | 1.1.0        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.6.0        |
</details>

*generated on:* **2020-06-24**
</details> </pre>
</details>

**Comment by Landschaft** [comment]
@janpio you classified this as feature but IMHO this is a _bug_. Secret information (such as passwords) must never be written in cleartext to any log files.

**Comment by ojizero** [comment]
@Landschaft quickly looking at the code this seems to only happen when logging is set to verbose, where it will log the command it is executing before doing so, is this the only case you're facing this issue or is it also happening when logging is set to non verbose?

Related [source file](https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/keychain_importer.rb#L51), and the flag `output` is set to `FastlaneCore::Globals.verbose?`

**Comment by Landschaft** [comment]
@ojizero thank you for having a look at this issue.

> is this the only case you're facing this issue or is it also happening when logging is set to non verbose?

You're right, setting `verbose: false` prevents the password from being output. This solves my issue.

I was mislead by the the `INFO` in the output

    [⠋] Setting key partition list... (this can take a minute if there are a lot of keys installed) INFO [2020-08-10 11:55:58.21]: $ security set-key-partition-list -S apple-tool:,apple: -s -k <...> <...>/login.keychain-db 1> /dev/null

into thinking this was a regular output.
