### ISSUE TITLE
Cloning Pods from another repo

### ISSUE THREAD

**Issue by cinder92** [fastlane/fastlane#16672]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
It is possible to pull `Pods` folder from another repo to current lane instead of using `cocoapods` command? 

#### Question Description
we have a project that `Pods` folder is under 400+mb size, and we don't want to upload Pods folder into iOS project, in order to keep source project repo smaller, and we are wondering if its possible to clone another repo which contains the `Pods` folder into the iOS folder, in that way the build timing will be small.

**Comment by bguidolim** [comment]
@cinder92 I would say it's not a Fastlane question, it's more about how you structured your project. It's always depends of your environment. Is it a CI env? If so, you can use the cache of your CI to do this.

**Comment by celochitaa** [comment]
> @cinder92 I would say it's not a Fastlane question, it's more about how you structured your project. It's always depends of your environment. Is it a CI env? If so, you can use the cache of your CI to do this.

Thanks for the clarification
