### ISSUE TITLE
undefined local variable or method `territory_ids' for Spaceship::ConnectAPI::App:Class

### ISSUE THREAD

**Issue by AmauriC** [fastlane/fastlane#16678]
### New Release Candidate Issue Checklist

- [x] Updated fastlane to the latest release candidate version (2.150.0.rcX)
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Information
- Breaking version: last rc
- First version of app?: Yes

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>/Users/amaurichampeaux/.rvm/gems/ruby-2.6.3/gems/fastlane-2.150.0.rc2/fastlane/lib/fastlane/actions/actions_helper.rb:48:in `execute_action'
/Users/amaurichampeaux/.rvm/gems/ruby-2.6.3/gems/fastlane-2.150.0.rc2/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
/Users/amaurichampeaux/.rvm/gems/ruby-2.6.3/gems/fastlane-2.150.0.rc2/fastlane/lib/fastlane/runner.rb:227:in `chdir'
/Users/amaurichampeaux/.rvm/gems/ruby-2.6.3/gems/fastlane-2.150.0.rc2/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
/Users/amaurichampeaux/.rvm/gems/ruby-2.6.3/gems/fastlane-2.150.0.rc2/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
/Users/amaurichampeaux/.rvm/gems/ruby-2.6.3/gems/fastlane-2.150.0.rc2/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
Fastfile:21:in `block (2 levels) in parsing_binding'
/Users/amaurichampeaux/.rvm/gems/ruby-2.6.3/gems/fastlane-2.150.0.rc2/fastlane/lib/fastlane/lane.rb:33:in `call'
/Users/amaurichampeaux/.rvm/gems/ruby-2.6.3/gems/fastlane-2.150.0.rc2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
/Users/amaurichampeaux/.rvm/gems/ruby-2.6.3/gems/fastlane-2.150.0.rc2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
/Users/amaurichampeaux/.rvm/gems/ruby-2.6.3/gems/fastlane-2.150.0.rc2/fastlane/lib/fastlane/runner.rb:45:in `execute'
/Users/amaurichampeaux/.rvm/gems/ruby-2.6.3/gems/fastlane-2.150.0.rc2/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
/Users/amaurichampeaux/.rvm/gems/ruby-2.6.3/gems/fastlane-2.150.0.rc2/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
/Users/amaurichampeaux/.rvm/gems/ruby-2.6.3/gems/fastlane-2.150.0.rc2/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
/Users/amaurichampeaux/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
/Users/amaurichampeaux/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
/Users/amaurichampeaux/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
/Users/amaurichampeaux/.rvm/gems/ruby-2.6.3/gems/fastlane-2.150.0.rc2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
/Users/amaurichampeaux/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
/Users/amaurichampeaux/.rvm/gems/ruby-2.6.3/gems/fastlane-2.150.0.rc2/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
/Users/amaurichampeaux/.rvm/gems/ruby-2.6.3/gems/fastlane-2.150.0.rc2/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
/Users/amaurichampeaux/.rvm/gems/ruby-2.6.3/gems/fastlane-2.150.0.rc2/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
/Users/amaurichampeaux/.rvm/gems/ruby-2.6.3/gems/fastlane-2.150.0.rc2/bin/fastlane:23:in `<top (required)>'
/Users/amaurichampeaux/.rvm/gems/ruby-2.6.3/bin/fastlane:23:in `load'
/Users/amaurichampeaux/.rvm/gems/ruby-2.6.3/bin/fastlane:23:in `<main>'
/Users/amaurichampeaux/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/Users/amaurichampeaux/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'

undefined local variable or method `territory_ids' for Spaceship::ConnectAPI::App:Class</pre>
</details>

### lane

<details>
  <pre>INFO [2020-06-25 18:05:16.51]: [DevCenter] App 'xxx' already exists, nothing to do on the Dev Center
INFO [2020-06-25 18:05:19.13]: Creating new app 'xxx' on App Store Connect
💥</pre>
</details>

### Mentioning

cc: @joshdholtz

**Comment by joshdholtz** [comment]
This is fixed in `2.150.0.rc3` 😊

**Comment by AmauriC** [comment]
Awesome, thanks 😊

After restarting the same lane it's ok.
