### ISSUE TITLE
Deliver: The attribute 'releaseType' can not be modified

### ISSUE THREAD

**Issue by changusmc** [fastlane/fastlane#16679]
### New Release Candidate Issue Checklist

- [x] Updated fastlane to the latest release candidate version (2.150.0.rcX)
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Information

- Breaking version: 2.150.0-rc1
- Last working version: 2.148.0
- State of app: Prepare for Submission
- First version of app?: Yes, 1.0

### Issue Description
The app in question is a sample app that is set to Manual release and is in Prepare for Submission. We don't ever plan on shipping this app. We use it as a canary to test our app text and image metadata a few days before the submission goes out as part of our release train.

```
Jun 24 18:40:38.447: DEBUG [11:40:33]: << PATCH appStoreVersions/da86bbe2-9df0-4246-8008-d4f71ef80e52: 409 {"errors"=>[{"id"=>"b86cc99a-7b7b-49e7-8a8b-223c7039bdc0", "status"=>"409", "code"=>"ENTITY_ERROR.ATTRIBUTE.INVALID.INVALID_STATE", "title"=>"An attribute value is not acceptable for the current resource state.", "detail"=>"The attribute 'releaseType' can not be modified.", "source"=>{"pointer"=>"/data/attributes/releaseType"}}]}
```

--

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>I'll check internally if I can share this, then will email you.</pre>
</details>

### Spaceship Logs

<details>
  <pre>I'll check internally if I can share this, then will email you.</pre>
</details>

### Environment

<details>
  <pre>I'll check internally if I can share this</pre>
</details>

### Mentioning

cc: @joshdholtz

Filing this separately from https://github.com/fastlane/fastlane/issues/16665

**Comment by joshdholtz** [comment]
@changusmc Does your app happen to be an arcade app or setup for pre-order?

**Comment by changusmc** [comment]
It's set up as a Productivity / Utilities app

It is free and not set up for pre-order.

**Comment by changusmc** [comment]
I sent the logs over in email. Also wanna update this issue that it's also happening for our Production builds.

**Comment by joshdholtz** [comment]
@changusmc Sent an email back to you! I don’t have access to that URL 😊

**Comment by changusmc** [comment]
This error was due to our 'service account' user somehow losing permissions, maybe someone accidentally updated it in App Store Connect. Once we gave it back 'App Manager' we were able to get further.

**Comment by neonaleon** [comment]
@joshdholtz 
"Does your app happen to be an arcade app or setup for pre-order?"
Just came across this issue, and my app does happen to be an arcade app. Is there a workaround for the releaseType?

**Comment by changusmc** [comment]
We're seeing this error again. Our service account is currently an admin.
```
Jul 10 23:38:17.223: INFO  [16:38:11]: >> PATCH appStoreVersions/aeaa57ef-0037-47f7-a22f-44ee65b13a14: {"data":{"type":"appStoreVersions","id":"aeaa57ef-0037-47f7-a22f-44ee65b13a14","attributes":{"copyright":"xxxx, Inc.","releaseType":"MANUAL"}}} 
Jul 10 23:38:17.223: DEBUG [16:38:11]: << PATCH appStoreVersions/aeaa57ef-0037-47f7-a22f-44ee65b13a14: 409 {"errors"=>[{"id"=>"ddb4af0b-4ffc-421c-951f-bc2555a2904d", "status"=>"409", "code"=>"ENTITY_ERROR.ATTRIBUTE.INVALID.INVALID_STATE", "title"=>"An attribute value is not acceptable for the current resource state.", "detail"=>"The attribute 'releaseType' can not be modified.", "source"=>{"pointer"=>"/data/attributes/releaseType"}}]}```

**Comment by oleksiisedun** [comment]
I am still facing this issue with the latest fastlane 2.152.0.

**Comment by Draknek** [comment]
I also hit this issue with fastlane 2.152.0.

It started working when I called `clear_derived_data` beforehand and added some extra arguments - unclear which of these helped but this is currently working for me 

```
clear_derived_data

    upload_to_app_store(
      pkg: "$pkg_path",
      skip_screenshots: true,
      force: true, # Skip HTML report verification
      app_identifier: "$appid",
      submit_for_review: false,
      run_precheck_before_submit: false,
      skip_metadata: true
    )
```

**Comment by oleksiisedun** [comment]
It's because you skipped metadata. And I got this issue when I am uploading metadata.

**Comment by joshdholtz** [comment]
@oleksiisedun Does your app happen to be in Apple Arcade by any chance or setup for pre-order?

**Comment by oleksiisedun** [comment]
@joshdholtz, for both questions the answer is no.

**Comment by joshdholtz** [comment]
@oleksiisedun That makes this harder I think 😔 Can you post your entire fastlane output here so I can try to see what’s going on?

**Comment by oleksiisedun** [comment]
The entire fastlane output is available at https://github.com/fastlane/fastlane/issues/16911.

**Comment by joshdholtz** [comment]
@oleksiisedun Thank you! I will go look now 😊
