### ISSUE TITLE
Getting 'CocoaPods not installed or not in valid state' when using sh

### ISSUE THREAD

**Issue by jlubeck** [fastlane/fastlane#16683]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
It looks like in order to publish my app to testflight with Flutter I first need to build the app with Flutter and then again with fastlane. I was trying to skip that step by using `sh` inside the Fastfile.

I have this on my Fastfile

```ruby
platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    sh(command:'flutter build ios')
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight
  end
end
```

And I'm getting an error that `CocoaPods not installed or not in valid state.`

But if I run `flutter build ios` outside of Fastlane it works just fine. 

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
jan@Jans-MacBook-Pro ios % fastlane beta             
[✔] 🚀 
[17:52:48]: fastlane detected a Gemfile in the current directory
[17:52:48]: However, it seems like you didn't use `bundle exec`
[17:52:48]: To launch fastlane faster, please use
[17:52:48]: 
[17:52:48]: $ bundle exec fastlane beta
[17:52:48]: 
[17:52:48]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[17:52:49]: ------------------------------
[17:52:49]: --- Step: default_platform ---
[17:52:49]: ------------------------------
[17:52:49]: Driving the lane 'ios beta' 🚀
[17:52:49]: -------------------------------
[17:52:49]: --- Step: flutter build ios ---
[17:52:49]: -------------------------------
[17:52:49]: $ flutter build ios
[17:52:50]: ▸ Changing current working directory to: /Users/jan/Projects/flutter/rpm
[17:52:52]: ▸ Building io.medek.rpm for device (ios-release)...
[17:52:53]: ▸ Automatically signing iOS for device deployment using specified development team in Xcode project: W75HA9QRB4
[17:52:53]: ▸ Warning: CocoaPods is installed but broken. Skipping pod install.
[17:52:53]: ▸ You appear to have CocoaPods installed but it is not working.
[17:52:53]: ▸ This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
[17:52:53]: ▸ This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
[17:52:53]: ▸ To re-install:
[17:52:53]: ▸ sudo gem install cocoapods
[17:52:53]: ▸ CocoaPods not installed or not in valid state.
+------------------+----------+
|        Lane Context         |
+------------------+----------+
| DEFAULT_PLATFORM | ios      |
| PLATFORM_NAME    | ios      |
| LANE_NAME        | ios beta |
+------------------+----------+
[17:52:53]: Exit status of command 'flutter build ios' was 1 instead of 0.
Changing current working directory to: /Users/jan/Projects/flutter/rpm
Building io.medek.rpm for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: W75HA9QRB4
Warning: CocoaPods is installed but broken. Skipping pod install.
  You appear to have CocoaPods installed but it is not working.
  This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
  This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
To re-install:
  sudo gem install cocoapods

CocoaPods not installed or not in valid state.

+------+-------------------+-------------+
|            fastlane summary            |
+------+-------------------+-------------+
| Step | Action            | Time (in s) |
+------+-------------------+-------------+
| 1    | default_platform  | 0           |
| 💥   | flutter build ios | 3           |
+------+-------------------+-------------+

[17:52:53]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Traceback (most recent call last):
	26: from /usr/local/Cellar/fastlane/2.149.1/libexec/bin/fastlane:23:in `<main>'
	25: from /usr/local/Cellar/fastlane/2.149.1/libexec/bin/fastlane:23:in `load'
	24: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/bin/fastlane:23:in `<top (required)>'
	23: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	22: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	21: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	20: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	19: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	18: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	17: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	16: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	15: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	14: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	13: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	12: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	11: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	10: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	 9: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	 8: from Fastfile:21:in `block (2 levels) in parsing_binding'
	 7: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane/lib/fastlane/fast_file.rb:210:in `sh'
	 6: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane/lib/fastlane/fast_file.rb:218:in `sh'
	 5: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 4: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane/lib/fastlane/fast_file.rb:219:in `block in sh'
	 3: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane/lib/fastlane/helper/sh_helper.rb:16:in `sh_no_action'
	 2: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	 1: from /usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/usr/local/Cellar/fastlane/2.149.1/libexec/gems/fastlane-2.149.1/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': [!] Exit status of command 'flutter build ios' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
Changing current working directory to: /Users/jan/Projects/flutter/rpm
Building io.medek.rpm for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: W75HA9QRB4
Warning: CocoaPods is installed but broken. Skipping pod install.
  You appear to have CocoaPods installed but it is not working.
  This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
  This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
To re-install:
  sudo gem install cocoapods

CocoaPods not installed or not in valid state.
 </pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 10.15.5                                                 |
| Ruby                        | 2.5.8                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.24.3 (Apple Git-128)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.149.1/libexec/bin/fastlane |
| Host                        | Mac OS X 10.15.5 (19F101)                               |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.5/2.5.8/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1f  31 Mar 2020                             |
| Is contained                | false                                                   |
| Is homebrew                 | false                                                   |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 11.5                                                    |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    #sh(command:'flutter build ios')
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("io.medek.rpm") # The bundle identifier of your app
apple_id("dev@medek.io") # Your Apple email address

itc_team_id("118920934") # App Store Connect Team ID
team_id("W75HA9QRB4") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.149.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.2        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.5.1        |
| google-cloud-storage      | 1.26.2       |
| emoji_regex               | 1.0.1        |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.17.0       |
| excon                     | 0.75.0       |
| os                        | 1.1.0        |
| memoist                   | 0.16.2       |
| googleauth                | 0.13.0       |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.1        |
| aws-partitions            | 1.334.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.102.0      |
| aws-sdk-kms               | 1.35.0       |
| aws-sdk-s3                | 1.70.0       |
</details>

*generated on:* **2020-06-25**
</details></pre>
</details>

**Comment by janpio** [comment]
> [17:52:48]: fastlane detected a Gemfile in the current directory
> [17:52:48]: However, it seems like you didn't use `bundle exec`
> [17:52:48]: To launch fastlane faster, please use
> [17:52:48]: 
> [17:52:48]: $ bundle exec fastlane beta

Have you tried this?

**Comment by janpio** [comment]
> Warning: CocoaPods is installed but broken. Skipping pod install.
>   You appear to have CocoaPods installed but it is not working.
>   This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
>   This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
> To re-install:
>   sudo gem install cocoapods
> CocoaPods not installed or not in valid state.

Also: Did you act on this in any way?

**Comment by jlubeck** [comment]
Hi @janpio I have tried `bundle exec fastlane beta` with the same result and I did re-install with `sudo gem install cocoapods` before posting this message

**Comment by bguidolim** [comment]
Accordingly to the log, seems to be a Flutter issue since the error happens in a `sh` command. Did you try to run this command without using Fastlane? Is it working?

**Comment by jlubeck** [comment]
Hi @bguidolim yes, I mentioned it my first message

> But if I run flutter build ios outside of Fastlane it works just fine.

**Comment by jlubeck** [comment]
Hi @bguidolim yes, I mentioned it my first message

> But if I run flutter build ios outside of Fastlane it works just fine.

**Comment by jorgefspereira** [comment]
Hi @janpio, I had the same issue and I fixed after uninstalling cocoapods and adding `gem "cocoapods"` to the Gemfile and installing it via `bundle install`. Hope it helps.
