### ISSUE TITLE
Two french phone numbers with same last two digits are not differenciated - pattern match are the same

### ISSUE THREAD

**Issue by ikodev** [fastlane/fastlane#16686]
# Issue Description
We are two developers with a similarity between our phone numbers.
06 ** ** ** 68

I discover that the SMS is always sent to the same phone number (Apple verification - 2FA).
So I am almost sure that a regexp (or else somewhere) always does a match for the same number, skipping the other one.
Maybe I am wrong but can you please make a short investigation ?

Moreover, even if we set SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER with the phone number that NEVER receive the SMS, it will be the other phone that will receive the SMS, same issue so.

##### Command executed
`bundle exec fastlane match appstore`

##### Complete output when running fastlane, including the stack trace and command used
No error displayed. The SMS is just sent to one only phone number.
However, fastlane display an anormal choices list : 
```
1. +33 ** ** ** 68
2. +33 ** ** ** 03
1. +33 ** ** ** 68
```

As you can see there is no "3." so that there is an exclusion or probably a merging process between the same pattern numbers.

I suggest to add another unique identification value when the regexp.match operate because I suppose that Apple does not provide the full clear phone numbers ?

Thank you for your help !

**Comment by ikodev** [comment]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.5                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.23.0                          |
| Installation Source         | ~/.rvm/gems/ruby-2.4.0/bin/fastlane         |
| Host                        | Mac OS X 10.15.5 (19F101)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.5                                        |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.149.1 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                             | Version | Update-Status |
| ---------------------------------- | ------- | ------------- |
| fastlane-plugin-cordova            | 2.2.1   | ✅ Up-To-Date  |
| fastlane-plugin-versioning_android | 0.1.0   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                                | Version      |
| ---------------------------------- | ------------ |
| did_you_mean                       | 1.1.0        |
| executable-hooks                   | 1.6.0        |
| bundler-unload                     | 1.0.2        |
| rubygems-bundler                   | 1.4.5        |
| bundler                            | 2.1.4        |
| CFPropertyList                     | 3.0.2        |
| public_suffix                      | 2.0.5        |
| addressable                        | 2.7.0        |
| atomos                             | 0.1.3        |
| aws-eventstream                    | 1.1.0        |
| aws-partitions                     | 1.335.0      |
| aws-sigv4                          | 1.2.1        |
| jmespath                           | 1.4.0        |
| aws-sdk-core                       | 3.102.1      |
| aws-sdk-kms                        | 1.35.0       |
| aws-sdk-s3                         | 1.71.1       |
| babosa                             | 1.0.3        |
| claide                             | 1.0.3        |
| coderay                            | 1.1.3        |
| colored                            | 1.2          |
| colored2                           | 3.1.2        |
| highline                           | 1.7.10       |
| commander-fastlane                 | 4.4.6        |
| declarative                        | 0.0.10       |
| declarative-option                 | 0.1.0        |
| digest-crc                         | 0.5.1        |
| unf_ext                            | 0.0.7.7      |
| unf                                | 0.1.4        |
| domain_name                        | 0.5.20190701 |
| dotenv                             | 2.7.5        |
| emoji_regex                        | 1.0.1        |
| excon                              | 0.75.0       |
| multipart-post                     | 2.0.0        |
| faraday                            | 1.0.1        |
| http-cookie                        | 1.0.3        |
| faraday-cookie_jar                 | 0.0.6        |
| faraday_middleware                 | 1.0.0        |
| fastimage                          | 2.1.7        |
| gh_inspector                       | 1.1.3        |
| jwt                                | 2.1.0        |
| memoist                            | 0.16.2       |
| multi_json                         | 1.14.1       |
| os                                 | 1.1.0        |
| signet                             | 0.14.0       |
| googleauth                         | 0.13.0       |
| httpclient                         | 2.8.3        |
| mini_mime                          | 1.0.2        |
| uber                               | 0.1.0        |
| representable                      | 3.0.4        |
| retriable                          | 3.1.2        |
| google-api-client                  | 0.38.0       |
| google-cloud-env                   | 1.3.2        |
| google-cloud-errors                | 1.0.1        |
| google-cloud-core                  | 1.5.0        |
| google-cloud-storage               | 1.26.2       |
| json                               | 2.3.0        |
| mini_magick                        | 4.10.1       |
| multi_xml                          | 0.6.0        |
| plist                              | 3.5.0        |
| rubyzip                            | 1.3.0        |
| security                           | 0.1.3        |
| naturally                          | 2.2.0        |
| simctl                             | 1.6.8        |
| slack-notifier                     | 2.3.2        |
| terminal-notifier                  | 2.0.0        |
| unicode-display_width              | 1.7.0        |
| terminal-table                     | 1.8.0        |
| tty-screen                         | 0.8.0        |
| tty-cursor                         | 0.7.1        |
| tty-spinner                        | 0.9.3        |
| word_wrap                          | 1.0.0        |
| nanaimo                            | 0.2.6        |
| xcodeproj                          | 1.17.0       |
| rouge                              | 2.0.7        |
| xcpretty                           | 0.3.0        |
| xcpretty-travis-formatter          | 1.0.0        |
| fastlane-plugin-cordova            | 2.2.1        |
| fastlane-plugin-versioning_android | 0.1.0        |
| method_source                      | 1.0.0        |
| pry                                | 0.13.1       |
</details>


*generated on:* **2020-06-26**
</details>

**Comment by max-ott** [comment]
How does it look like if you manually login on one of Apple‘s websites? How do they differentiate the 2 numbers?

**Comment by janpio** [comment]
> I suggest to add another unique identification value when the regexp.match operate because I suppose that Apple does not provide the full clear phone numbers ?

We indeed work with what Apple gives us - so @max-ott 's question is the right one. If it is clear on the Apple web UI, we should also be able to get the information. 

This action https://docs.fastlane.tools/actions/spaceship_logs/ might help us later to identify what exactly is going on.

**Comment by ikodev** [comment]
Hi, thank you for your answer.
By login manually onto Apple website with our main Apple Account (owner), our phone numbers are right in the Trusted list of phone numbers.

**Comment by max-ott** [comment]
@ikodev That's not really what we meant. If you try to login in an incognito browser window > Choose by phone number > How are the different phone numbers displayed by Apple? They also mask the phone numbers, I'm curious if they "expose" more digits or you get the same issue as with `fastlane`.

**Comment by ikodev** [comment]
Understood. I had exactly the same problem on Apple websites, our two phone numbers cannot be identified in the selection list (login form) such as they are displayed with same masks without exsposing more digits so.

**Comment by max-ott** [comment]
@ikodev I was afraid this would happen. We get the information from Apple and have no more information than that. I think it's not exclusive to French phone numbers. I recommend contacting Apple Developer support: https://developer.apple.com/support/ Also opening an issue over at the Feedback Assistant might help in the long term: https://feedbackassistant.apple.com/

**Comment by janpio** [comment]
We always assumed Apple would be smart about this and just show more digits until you can differentiate the numbers - but that does not seem to be the case :/

**Comment by ikodev** [comment]
Thank you @max-ott,
I was sure of that... :/
