### ISSUE TITLE
Missing com.apple.application-identifier Error when I upload a new build after installing MacOS Big Sur

### ISSUE THREAD

**Issue by elgawady14** [fastlane/fastlane#16681]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I can not upload a new build to AppStore because I get this error:
Provisioning profile "match AppStore com.xxx.xxx" doesn't include the com.apple.application-identifier entitlement."
##### Command executed
      gym(scheme: "xxx", workspace: "xxx.xcworkspace", codesigning_identity: "xxx", output_name: "xxx-#{build_number}.ipa") 
I have no idea why this entitlement is not included in the generated Fastlane Distribution Provisioning profile!

##### Complete output when running fastlane, including the stack trace and command used

<details>
  Issue occurred after installing macOS Big Sur!
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                     |
| --------------------------- | --------------------------------------------------------- |
| OS                          | 10.16                                                     |
| Ruby                        | 2.5.5                                                     |
| Bundler?                    | false                                                     |
| Git                         | git version 2.21.1 (Apple Git-122.3)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.140.0_1/libexec/bin/fastlane |
| Host                        | macOS 10.16 (20A4299v)                                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.5/2.5.5_1/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                               |
| Is contained                | false                                                     |
| Is homebrew                 | false                                                     |
| Is installed via Fabric.app | false                                                     |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/               |
| Xcode Version               | 11.3.1                                                    |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.149.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                | Version | Update-Status |
| --------------------- | ------- | ------------- |
| fastlane-plugin-badge | 1.4.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.14.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.2        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.71.1       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.7        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.10.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.332.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.0        |
| aws-sdk-core              | 3.100.0      |
| aws-sdk-kms               | 1.34.1       |
| aws-sdk-s3                | 1.69.0       |
| CFPropertyList            | 3.0.2        |
| digest-crc                | 0.4.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.25.1       |
| curb                      | 0.9.10       |
| badge                     | 0.12.0       |
| fastlane-plugin-badge     | 1.4.0        |
</details>

*generated on:* **2020-06-25**
</details>

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by SConaway** [comment]
Use the rc release. That solved the issue for me.

**Comment by elgawady14** [comment]
Thank you 🙏, I will give it a try!

**Comment by elgawady14** [comment]
@SConaway I still get the same error after upgrading to version `2.150.0.rc3`.

```
[21:05:12]: ▸ Archive Succeeded
[21:05:13]: Generated plist file with the following values:
[21:05:13]: ▸ -----------------------------------------
[21:05:13]: ▸ {
[21:05:13]: ▸   "provisioningProfiles": {
[21:05:13]: ▸     "com.ddd.ddd": "match AppStore com.ddd.ddd"
[21:05:13]: ▸   },
[21:05:13]: ▸   "method": "app-store",
[21:05:13]: ▸   "signingStyle": "manual"
[21:05:13]: ▸ }
[21:05:13]: ▸ -----------------------------------------
[21:05:13]: $ /usr/bin/xcrun /Users/name/.rvm/gems/ruby-2.6.3/gems/fastlane-2.150.0.rc3/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/8m/ls4z85rn31z3jgym1cw0ysbr0000gn/T/gym_config20200626-17439-ohpu6n.plist' -archivePath /Users/name/Library/Developer/Xcode/Archives/2020-06-26/ddd-60\ 2020-06-26\ 21.02.58.xcarchive -exportPath '/var/folders/8m/ls4z85rn31z3jgym1cw0ysbr0000gn/T/gym_output20200626-17439-wyr01j' 
xcrun: error: unable to read SDK settings for '/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk'
xcrun: error: unable to read SDK settings for '/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk'
RVM detected, forcing to use system ruby
Now using system ruby.
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/8m/ls4z85rn31z3jgym1cw0ysbr0000gn/T/gym_config20200626-17439-ohpu6n.plist -archivePath '/Users/name/Library/Developer/Xcode/Archives/2020-06-26/ddd-60 2020-06-26 21.02.58.xcarchive' -exportPath /var/folders/8m/ls4z85rn31z3jgym1cw0ysbr0000gn/T/gym_output20200626-17439-wyr01j
2020-06-26 21:05:14.618 xcodebuild[20015:349968] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/8m/ls4z85rn31z3jgym1cw0ysbr0000gn/T/ddd Release_2020-06-26_21-05-14.617.xcdistributionlogs'.
error: exportArchive: Provisioning profile "match AppStore com.ddd.ddd" doesn't include the com.apple.application-identifier entitlement.

Error Domain=IDEProfileQualificationErrorDomain Code=8 "Provisioning profile "match AppStore com.ddd.ddd" doesn't include the com.apple.application-identifier entitlement." UserInfo={NSLocalizedDescription=Provisioning profile "match AppStore com.ddd.ddd" doesn't include the com.apple.application-identifier entitlement., IDEProfileQualificationError_RequiredEntitlements={
    "application-identifier" = "ddd.com.ddd.ddd";
    "com.apple.application-identifier" = "ddd.com.ddd.ddd";
    "com.apple.developer.team-identifier" = ddd;
    "keychain-access-groups" =     (
        "ddd.com.ddd.ddd"
    );
}, IDEDistributionIssueSeverity=3, IDEProfileQualificationErrorMissingEntitlements=(
    "com.apple.application-identifier"
), IDEProfileQualificationError_Profile=<IDEEmbeddedProvisioningProfile 0x7f8610607350: name: match AppStore com.ddd.ddd, UUID: ddd, teamName: ddd Technologies, teamIdentifierPrefixes: (
    ddd
), entitlements: {
    "application-identifier" = "ddd.com.ddd.ddd";
    "aps-environment" = production;
    "beta-reports-active" = 1;
    "com.apple.developer.team-identifier" = ddd;
    "get-task-allow" = 0;
    "keychain-access-groups" =     (
        "ddd.*"
    );
}, appIdentifierName: ddd, applicationIdentifierPrefixes: (
    ddd
), dateCreated: 2020-06-25 14:47:38 +0000, dateExpired: 2021-06-25 14:36:44 +0000, certificateKinds: {(
    "1.2.840.113635.100.6.1.7",
    "1.2.840.113635.100.6.1.4"
)}, certificateSHA1Hashes: {(
    B747B10DE6EA2257EA24A42603D3E1316BC36717
)}, supportedUDIDs: {(
)}, isUniversal: 0, isXcodeManaged: 0, platforms: {(
    <DVTPlatform:0x7f860e554e20:'com.apple.platform.watchos':<DVTFilePath:0x7f860e554da0:'/Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform'>>,
    <DVTPlatform:0x7f86100077c0:'com.apple.platform.iphoneos':<DVTFilePath:0x7f86100073e0:'/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform'>>
)}, filePath: <DVTFilePath:0x7f861331a9f0:'/Users/name/Library/MobileDevice/Provisioning Profiles/f2945e60-d100-4ec6-ab7d-5f5ea96a6dae.mobileprovision'>>}

** EXPORT FAILED **
[21:05:15]: Exit status: 70
```

**Comment by SConaway** [comment]
Hmm. I guess one final attempt to fix this might be to rename the entitlements file to say `YourProject.entitlements.bak`, then recreate it in Xcode

**Comment by imWildCat** [comment]
Same here, "after upgrading to version 2.150.0.rc3."

**Comment by elgawady14** [comment]
@SConaway I have no entitlements file included because the app doesn’t use any capacities from capacities list!

**Comment by max-ott** [comment]
Not sure if we can already support beta Xcode and the new beta macOS. Focus currently is to get all endpoints going again after the App Store Connect changes. Please feel free to investigate and open a pull request.

**Comment by SConaway** [comment]
@elgawady14 Fair enough. If you look in Finder, though, you might find an entitlements file. Otherwise, I'm not sure, sorry.

@max-ott I have no issue with that, especially due to the change. I'm extremely unfamiliar with `ruby`, so I don't think I could do much good.

**Comment by elgawady14** [comment]
@SConaway The entitlements file mentioned in the error log (which is Included in the generated distribution provisioning profile by Fastlane) is different than the entitlements file which is bundled in the app once we add a new capability from Xcode.

In my case the app does not contain any entitlements files because no capability added for the app from capabilities list in Xcode.

**Comment by imWildCat** [comment]
There's a reference to workaround this issue: https://developer.apple.com/forums/thread/650490

However, I decided to install a Catalina along side Big Sur for now.

**Comment by elgawady14** [comment]
@imWildCat You can enable ‘Automatic Signing’ instead and let Xcode handle generating the provisioning profiles until a new Fastlane update fixes the bug.

**Comment by elgawady14** [comment]
The same problem occurred even after creating manually a new distribution provisioning profile from developer.apple.com!

**Comment by elgawady14** [comment]
For iOS, the entitlement is application-identifier, and for OS X the entitlement is com.apple.application-identifier.

**Comment by elgawady14** [comment]
Issue fixed in macOS Big Sur 11 Beta 2 Thanks Apple 😀

**Comment by elgawady14** [comment]
After updating macOS Big Sur to Beta 2; uploading to AppStore working well in Xcode `Version 12.0 beta (12A6159)` unlike Xcode `Version 11.3.1 (11C504)` which still not working also `Fastlane` still not working on macOS Big Sur to Beta 2.

**Comment by elgawady14** [comment]
Quick fix
Install the "Transporter" app from the MacOS app store.
OPEN Xcode 11.5 archive your project
Close Xcode 11.5 -> Command + Q
Open then Xcode 12 Beta
From Xcode's organizer, select your archive and press "Distribute App"
Instead of "Upload", select "Export" and proceed as usual.
Drop the exported .ipa into the transporter and press "Deliver".
And its Work!

**Comment by MoOx** [comment]
Another way to keep fastlane, is to have on your macOS 11 beta installation Xcode 11 & 12 and use both when relevant by doing something like this:


```ruby
    # use Xcode 11 to build
    ENV["DEVELOPER_DIR"] = "/Applications/Xcode.app"
    build_app
    # using macOS 11 beta requires to upload using xcode 12 beta
    ENV["DEVELOPER_DIR"] = "/Applications/Xcode-12.app"
    upload_to_testflight
```
