### ISSUE TITLE
Access forbidden error for ra/apps/manageyourapps/summary/v2 calls

### ISSUE THREAD

**Issue by siddhardhan** [fastlane/fastlane#16688]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I am new to fastlane and trying spaceship [playground ](https://github.com/fastlane/fastlane/tree/40fdd512072c4711011e727d22ca74a4281044f6/spaceship#playground) - when I try to run 'Spaceship::Tunes::Application.all' command as mentioned in [AppStoreConnect.md](https://github.com/fastlane/fastlane/blob/40fdd512072c4711011e727d22ca74a4281044f6/spaceship/docs/AppStoreConnect.md#applications) - i am getting 403 error for below api call. However, on app store connect portal - i am able to see my applications - wondering if there are any elevated access needed for this call. Please suggest.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>INFO  [14:40:20]: >> GET ra/apps/manageyourapps/summary/v2: [undefined body] 
DEBUG [14:40:21]: << GET ra/apps/manageyourapps/summary/v2: 403 {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["insufficient privileges"], "info"=>nil}, "statusCode"=>"ERROR"}
WARN  [14:40:21]: Access forbidden
WARN  [14:40:21]: Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 4)...
DEBUG [14:40:24]: << GET ra/apps/manageyourapps/summary/v2: 403 {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["insufficient privileges"], "info"=>nil}, "statusCode"=>"ERROR"}
WARN  [14:40:24]: Access forbidden
WARN  [14:40:24]: Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 3)...
DEBUG [14:40:27]: << GET ra/apps/manageyourapps/summary/v2: 403 {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["insufficient privileges"], "info"=>nil}, "statusCode"=>"ERROR"}
WARN  [14:40:27]: Access forbidden
WARN  [14:40:27]: Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 2)...
DEBUG [14:40:31]: << GET ra/apps/manageyourapps/summary/v2: 403 {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["insufficient privileges"], "info"=>nil}, "statusCode"=>"ERROR"}
WARN  [14:40:31]: Access forbidden
WARN  [14:40:31]: Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 1)...
DEBUG [14:40:34]: << GET ra/apps/manageyourapps/summary/v2: 403 {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["insufficient privileges"], "info"=>nil}, "statusCode"=>"ERROR"}</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.4                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.26.2                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.4 (19E287)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Library/Developer/CommandLineTools/                           |
| Xcode Version               |                                                                |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.149.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.17.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.75.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.0        |
| googleauth                | 0.13.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.2        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.5.1        |
| google-cloud-storage      | 1.26.2       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.333.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.0        |
| aws-sdk-core              | 3.101.0      |
| aws-sdk-kms               | 1.35.0       |
| aws-sdk-s3                | 1.70.0       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-06-26**
</details></pre>
</details>

**Comment by max-ott** [comment]
Please check out #16639 and #16652 This is related to the changes from Apple‘s end. The endpoint is no longer working, therefore you get the error.

I started (!) changing the docs, you can find the current alternative over at https://github.com/fastlane/fastlane/blob/2.150.0/spaceship/docs/AppStoreConnect.md#applications

**Comment by siddhardhan** [comment]
Thanks @max-ott. Started looking to alternative doc - can you please help on how to get the-key-id, the-issuer-id and AuthKey_the-key-id.p8 for generating token?

token = Spaceship::ConnectAPI::Token.create(
  key_id: 'the-key-id',
  issuer_id: 'the-issuer-id,
  filepath:  File.absolute_path("../AuthKey_the-key-id.p8")
)

Spaceship::ConnectAPI.token = token

**Comment by max-ott** [comment]
You can still login with the old method.

**Comment by siddhardhan** [comment]
thanks @max-ott - I tried to login with old method, but still having access forbidden issue. Please suggest.

**from spaceship playground:**

[18:07:20]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
Username: xxxxx@xxxx.xxx
Logging into to App Store Connect (xxxxx@xxxx.xxx)...
Successfully logged in to App Store Connect

Logging into the Developer Portal (xxxxx@xxxx.xxx)...
Successfully logged in to the Developer Portal

---------------------------------------
| Welcome to the spaceship playground |
---------------------------------------

Enter docs to open up the documentation
Enter exit to exit the spaceship playground
Enter _ to access the return value of the last executed command

Just enter the commands and confirm with Enter
[1] pry(#<Spaceship::Playground>)> **Spaceship::ConnectAPI::App.all**
Spaceship::AccessForbiddenError: Access forbidden
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/spaceship/lib/spaceship/client.rb:873:in `block in send_request'
[2] pry(#<Spaceship::Playground>)> 

**from log file**

# Logfile created on 2020-06-27 18:08:52 -0400 by logger.rb/66358
INFO  [18:08:52]: >> GET apps: [undefined body] 
DEBUG [18:08:52]: << GET apps: 403 {"errors"=>[{"id"=>"********", "status"=>"403", "code"=>"FORBIDDEN_ERROR", "title"=>"This request is forbidden for security reasons", "detail"=>"The API key in use does not allow this request"}]}
WARN  [18:08:52]: Access forbidden
WARN  [18:08:52]: Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 4)...
DEBUG [18:08:56]: << GET apps: 403 {"errors"=>[{"id"=>"********", "status"=>"403", "code"=>"FORBIDDEN_ERROR", "title"=>"This request is forbidden for security reasons", "detail"=>"The API key in use does not allow this request"}]}
WARN  [18:08:56]: Access forbidden
WARN  [18:08:56]: Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 3)...
DEBUG [18:08:59]: << GET apps: 403 {"errors"=>[{"id"=>"********", "status"=>"403", "code"=>"FORBIDDEN_ERROR", "title"=>"This request is forbidden for security reasons", "detail"=>"The API key in use does not allow this request"}]}
WARN  [18:08:59]: Access forbidden
WARN  [18:08:59]: Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 2)...
DEBUG [18:09:03]: << GET apps: 403 {"errors"=>[{"id"=>"********", "status"=>"403", "code"=>"FORBIDDEN_ERROR", "title"=>"This request is forbidden for security reasons", "detail"=>"The API key in use does not allow this request"}]}
WARN  [18:09:03]: Access forbidden
WARN  [18:09:03]: Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 1)...
DEBUG [18:09:06]: << GET apps: 403 {"errors"=>[{"id"=>"********", "status"=>"403", "code"=>"FORBIDDEN_ERROR", "title"=>"This request is forbidden for security reasons", "detail"=>"The API key in use does not allow this request"}]}
WARN  [18:09:06]: Access forbidden

**Comment by max-ott** [comment]
If you don’t login at all, you will get the error.

Please use Spaceship::Tunes.login before the other call.

**Comment by siddhardhan** [comment]
Sorry for the late response  - @max-ott.  I tried **Spaceship::Tunes.login** as you suggested.
I am getting Unauthorized Access Error now. Please suggest.

irb(main):009:0> all_apps = Spaceship::ConnectAPI::App.all
Traceback (most recent call last):
       11: from /usr/bin/irb:23:in `<main>'
       10: from /usr/bin/irb:23:in `load'
        9: from /Library/Ruby/Gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        8: from (irb):9
        7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/spaceship/lib/spaceship/connect_api/models/app.rb:34:in `all'
        6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:12:in `get_apps'
        5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/spaceship/lib/spaceship/connect_api/client.rb:81:in `get'
        4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/spaceship/lib/spaceship/client.rb:695:in `request'
        3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/spaceship/lib/spaceship/client.rb:851:in `send_request'
        2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/spaceship/lib/spaceship/client.rb:626:in `with_retry'
        1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/spaceship/lib/spaceship/client.rb:859:in `block in send_request'
Spaceship::UnauthorizedAccessError (Unauthorized Access)

**Comment by max-ott** [comment]
Please post full request.

**Comment by siddhardhan** [comment]
not sure i am doing wrong here.. now i started getting access forbidden error even my login shows successful.

WARN  [16:46:50]: Access forbidden
WARN  [16:46:50]: Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 3)...
DEBUG [16:46:53]: << GET ra/apps/manageyourapps/summary/v2: 403 {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["insufficient privileges"], "info"=>nil}, "statusCode"=>"ERROR"}
WARN  [16:46:53]: Access forbidden
WARN  [16:46:53]: Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 2)...
DEBUG [16:46:56]: << GET ra/apps/manageyourapps/summary/v2: 403 {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["insufficient privileges"], "info"=>nil}, "statusCode"=>"ERROR"}
WARN  [16:46:56]: Access forbidden
WARN  [16:46:56]: Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 1)...
DEBUG [16:46:59]: << GET ra/apps/manageyourapps/summary/v2: 403 {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["insufficient privileges"], "info"=>nil}, "statusCode"=>"ERROR"}
WARN  [16:46:59]: Access forbidden

**Comment by siddhardhan** [comment]
i checked issue#16108 and tried follow change password and sign out devices option - but still no luck. 

irb(main):003:0> Spaceship::Tunes.login('XXXXXXX', '********')
Two-factor Authentication (6 digits code) is enabled for account 'siddhardha.v.nandipati@jpmchase.com'
More information about Two-factor Authentication: https://support.apple.com/en-us/HT204915

If you're running this in a non-interactive session (e.g. server or CI)
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification

Please enter the 6 digit code you received at +1 (•••) •••-••XX:

after 6-digits validation is done - tried to list the apps

irb(main):005:0> Spaceship::Tunes::Application.all
Traceback (most recent call last):
       11: from /usr/bin/irb:23:in `<main>'
       10: from /usr/bin/irb:23:in `load'
        9: from /Library/Ruby/Gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        8: from (irb):5
        7: from (irb):5:in `rescue in irb_binding'
        6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/spaceship/lib/spaceship/tunes/application.rb:67:in `all'
        5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/spaceship/lib/spaceship/tunes/tunes_client.rb:255:in `applications'
        4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/spaceship/lib/spaceship/client.rb:695:in `request'
        3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/spaceship/lib/spaceship/client.rb:851:in `send_request'
        2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/spaceship/lib/spaceship/client.rb:626:in `with_retry'
        1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/spaceship/lib/spaceship/client.rb:873:in `block in send_request'

**full request details:**
INFO  [17:13:27]: >> GET ra/apps/manageyourapps/summary/v2: [undefined body] 
DEBUG [17:13:28]: << GET ra/apps/manageyourapps/summary/v2: 403 {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["insufficient privileges"], "info"=>nil}, "statusCode"=>"ERROR"}
WARN  [17:13:28]: Access forbidden
WARN  [17:13:28]: Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 4)...
DEBUG [17:13:31]: << GET ra/apps/manageyourapps/summary/v2: 403 {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["insufficient privileges"], "info"=>nil}, "statusCode"=>"ERROR"}
WARN  [17:13:31]: Access forbidden
WARN  [17:13:31]: Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 3)...
DEBUG [17:13:35]: << GET ra/apps/manageyourapps/summary/v2: 403 {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["insufficient privileges"], "info"=>nil}, "statusCode"=>"ERROR"}
WARN  [17:13:35]: Access forbidden
WARN  [17:13:35]: Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 2)...
DEBUG [17:13:38]: << GET ra/apps/manageyourapps/summary/v2: 403 {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["insufficient privileges"], "info"=>nil}, "statusCode"=>"ERROR"}
WARN  [17:13:38]: Access forbidden
WARN  [17:13:38]: Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 1)...
DEBUG [17:13:42]: << GET ra/apps/manageyourapps/summary/v2: 403 {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["insufficient privileges"], "info"=>nil}, "statusCode"=>"ERROR"}
WARN  [17:13:42]: Access forbidden

**Comment by siddhardhan** [comment]
i tried upgrade my fastlane version to 2.150.3. Also reset my password & sign out of devices option as mentioned in 16108. but still no luck. 

**Login**
irb(main):005:0> Spaceship::Tunes.login('XXXXX, '*****')
Two-factor Authentication (6 digits code) is enabled for account 'XXXXX'
More information about Two-factor Authentication: https://support.apple.com/en-us/HT204915

If you're running this in a non-interactive session (e.g. server or CI)
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification

Please enter the 6 digit code you received at +## (•••) •••-••##:

**list apps** (note: had to interupt this call as it is happening in continuous loop)
Spaceship::ConnectAPI::App.all
^CTraceback (most recent call last):
       14: from /usr/bin/irb:23:in `<main>'
       13: from /usr/bin/irb:23:in `load'
       12: from /Library/Ruby/Gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
       11: from (irb):6
       10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.3/spaceship/lib/spaceship/connect_api/models/app.rb:47:in `all'
        9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.3/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:12:in `get_apps'
        8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.3/spaceship/lib/spaceship/connect_api/client.rb:81:in `get'
        7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.3/spaceship/lib/spaceship/connect_api/client.rb:131:in `with_asc_retry'
        6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.3/spaceship/lib/spaceship/connect_api/client.rb:82:in `block in get'
        5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.3/spaceship/lib/spaceship/client.rb:696:in `request'
        4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.3/spaceship/lib/spaceship/client.rb:852:in `send_request'
        3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.3/spaceship/lib/spaceship/client.rb:626:in `with_retry'
        2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.3/spaceship/lib/spaceship/client.rb:641:in `rescue in with_retry'
        1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.3/spaceship/lib/spaceship/client.rb:641:in `sleep'

**Request Details**
WARN  [14:53:27]: Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 4)...
DEBUG [14:53:30]: << GET apps: 403 {"errors"=>[{"id"=>"######, "status"=>"403", "code"=>"FORBIDDEN_ERROR", "title"=>"This request is forbidden for security reasons", "detail"=>"The API key in use does not allow this request"}]}
WARN  [14:53:30]: Access forbidden
WARN  [14:53:30]: Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 3)...
DEBUG [14:53:33]: << GET apps: 403 {"errors"=>[{"id"=>"######", "status"=>"403", "code"=>"FORBIDDEN_ERROR", "title"=>"This request is forbidden for security reasons", "detail"=>"The API key in use does not allow this request"}]}
WARN  [14:53:33]: Access forbidden
WARN  [14:53:33]: Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 2)...
DEBUG [14:53:36]: << GET apps: 403 {"errors"=>[{"id"=>"######", "status"=>"403", "code"=>"FORBIDDEN_ERROR", "title"=>"This request is forbidden for security reasons", "detail"=>"The API key in use does not allow this request"}]}
WARN  [14:53:36]: Access forbidden
WARN  [14:53:36]: Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 1)...
DEBUG [14:53:40]: << GET apps: 403 {"errors"=>[{"id"=>"######", "status"=>"403", "code"=>"FORBIDDEN_ERROR", "title"=>"This request is forbidden for security reasons", "detail"=>"The API key in use does not allow this request"}]}
