### ISSUE TITLE
--submission_information does not seem to be optional for new apps

### ISSUE THREAD

**Issue by markmuniz** [fastlane/fastlane#16701]
### New Release Candidate Issue Checklist

- [x] Updated fastlane to the latest release candidate version (2.150.0.rc4)
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Information
- Breaking version: [`2.150.0.rc1`]
- Last working version: [`2.149.1`]
- State of app: [`Prepare for Submission`]
- First version of app?: [`Yes`]

### Issue Description
Running Deliver with `--submit_for_review true` and no `--submission_options` requires IDFA information to submit.

##### Complete output when running fastlane, including the stack trace and command used
`fastlane deliver --team_id 123456 --username test@test.com --app_identifier com.org.test --skip_metadata true --skip_screenshots true --skip_binary_upload true --submit_for_review true --run_precheck_before_submit false --verbose`
<details>
  <pre>+--------------------------------------+------------------------------------------+
|                           deliver 2.150.0.rc4 Summary                           |
+--------------------------------------+------------------------------------------+
| team_id                              | 123456                                   |
| username                             | test@test.com                            |
| app_identifier                       | com.org.test                             |
| skip_metadata                        | true                                     |
| skip_screenshots                     | true                                     |
| skip_binary_upload                   | true                                     |
| submit_for_review                    | true                                     |
| run_precheck_before_submit           | false                                    |
| screenshots_path                     | ./.fastlane/screenshots                  |
| metadata_path                        | ./.fastlane/metadata                     |
| platform                             | ios                                      |
| edit_live                            | false                                    |
| use_live_version                     | false                                    |
| skip_app_version_update              | false                                    |
| force                                | false                                    |
| overwrite_screenshots                | false                                    |
| reject_if_possible                   | false                                    |
| automatic_release                    | false                                    |
| phased_release                       | false                                    |
| reset_ratings                        | false                                    |
| precheck_default_rule_level          | warn                                     |
| individual_metadata_items            | []                                       |
| ignore_language_directory_validation | false                                    |
| precheck_include_in_app_purchases    | true                                     |
+--------------------------------------+------------------------------------------+

INFO [2020-06-29 11:36:45.51]: Selecting the latest build...
INFO [2020-06-29 11:36:45.51]: Waiting for processing on... app_id: 123456, app_version: , build_version: , platform: IOS
INFO [2020-06-29 11:36:45.87]: Successfully finished processing the build 1.0.0 - 1 for IOS
WARN [2020-06-29 11:36:45.87]: Uploaded app  - , but received build 1.0.0 - 1
INFO [2020-06-29 11:36:45.87]: Selecting build 1.0.0(1)...
INFO [2020-06-29 11:36:47.45]: Successfully selected build
DEBUG [2020-06-29 11:36:49.83]: Updating app store version for IDFA status of ''
DEBUG [2020-06-29 11:36:49.83]: Updated app store version for IDFA status of ''
Traceback (most recent call last):
	17: from /usr/local/bin/fastlane:23:in `<main>'
	16: from /usr/local/bin/fastlane:23:in `load'
	15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.0.rc4/bin/fastlane:23:in `<top (required)>'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.0.rc4/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.0.rc4/deliver/lib/deliver/commands_generator.rb:17:in `start'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.0.rc4/deliver/lib/deliver/commands_generator.rb:183:in `run'
	11: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.0.rc4/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 9: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 8: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 7: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.0.rc4/deliver/lib/deliver/commands_generator.rb:80:in `block (2 levels) in run'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.0.rc4/deliver/lib/deliver/runner.rb:49:in `run'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.0.rc4/deliver/lib/deliver/runner.rb:169:in `submit_for_review'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.0.rc4/deliver/lib/deliver/submit_for_review.rb:25:in `submit!'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.0.rc4/deliver/lib/deliver/submit_for_review.rb:120:in `update_idfa'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.0.rc4/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.0.rc4/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': Use of Advertising Identifier (IDFA) is required to submit (FastlaneCore::Interface::FastlaneError)
Add information to the :submission_information option...
  Docs: http://docs.fastlane.tools/actions/deliver/#compliance-and-idfa-settings
  Example: submission_information: { add_id_info_uses_idfa: false }
  Example: submission_information: {
    add_id_info_uses_idfa: true,
    add_id_info_limits_tracking: false,
    add_id_info_serves_ads: false,
    add_id_info_uses_idfa: false,
    add_id_info_tracks_install: false
  }
	17: from /usr/local/bin/fastlane:23:in `<main>'
	16: from /usr/local/bin/fastlane:23:in `load'
	15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.0.rc4/bin/fastlane:23:in `<top (required)>'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.0.rc4/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.0.rc4/deliver/lib/deliver/commands_generator.rb:17:in `start'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.0.rc4/deliver/lib/deliver/commands_generator.rb:183:in `run'
	11: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.0.rc4/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 9: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 8: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 7: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.0.rc4/deliver/lib/deliver/commands_generator.rb:80:in `block (2 levels) in run'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.0.rc4/deliver/lib/deliver/runner.rb:49:in `run'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.0.rc4/deliver/lib/deliver/runner.rb:169:in `submit_for_review'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.0.rc4/deliver/lib/deliver/submit_for_review.rb:25:in `submit!'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.0.rc4/deliver/lib/deliver/submit_for_review.rb:120:in `update_idfa'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.0.rc4/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.0.rc4/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Use of Advertising Identifier (IDFA) is required to submit (FastlaneCore::Interface::FastlaneError)
Add information to the :submission_information option...
  Docs: http://docs.fastlane.tools/actions/deliver/#compliance-and-idfa-settings
  Example: submission_information: { add_id_info_uses_idfa: false }
  Example: submission_information: {
    add_id_info_uses_idfa: true,
    add_id_info_limits_tracking: false,
    add_id_info_serves_ads: false,
    add_id_info_uses_idfa: false,
    add_id_info_tracks_install: false
  }
</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.5                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.5 (19F101)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.5                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version     | Update-Status |
| -------- | ----------- | ------------- |
| fastlane | 2.150.0.rc4 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.17.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.75.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.0        |
| googleauth                | 0.13.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.2        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.5.1        |
| google-cloud-storage      | 1.26.2       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.332.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.0        |
| aws-sdk-core              | 3.100.0      |
| aws-sdk-kms               | 1.34.1       |
| aws-sdk-s3                | 1.69.1       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-06-29**
</details>

### Mentioning

cc: @joshdholtz

**Comment by joshdholtz** [comment]
@markmuniz Hey 👋 Thanks for creating this issue 😊 

Sooooo... this is a weird topic. The newest App Store Connect update requires the selection for your app version if you are using IDFA or not. This is not something we are comfortable defaulting in fastlane since this is a touchy legal issue 😇 

1) I will update the error from this show some CLI usage as well as Fastfile usage
2) I will also be adding an easier to use option called something like `uses_idafa: false` in the near future to make this easier to use

I add something like this to my command if I’m using `deliver` with the CLI now 👇

```
--submission_information "{\"export_compliance_uses_encryption\": false, \"add_id_info_uses_idfa\": false }"

```

Thanks and let me know if you have any further questions!

**Comment by markmuniz** [comment]
Thanks for that information. I'm still getting the same error when setting the `submission_information` as you mentioned, even though `deliver` recognized the arguments.
```
+----------------------------------------------------------+------------------------------------------+
|                                     deliver 2.150.0.rc4 Summary                                     |
+----------------------------------------------------------+------------------------------------------+
| team_id                                                  | 123456                                   |
| username                                                 | test@test.com                            |
| app_identifier                                           | com.org.test                             |
| submission_information.export_compliance_uses_encryption | false                                    |
| submission_information.add_id_info_uses_idfa             | false                                    |
| skip_metadata                                            | true                                     |
| skip_screenshots                                         | true                                     |
| skip_binary_upload                                       | true                                     |
| submit_for_review                                        | true                                     |
| screenshots_path                                         | ./.fastlane/screenshots                  |
| metadata_path                                            | ./.fastlane/metadata                     |
| platform                                                 | ios                                      |
| edit_live                                                | false                                    |
| use_live_version                                         | false                                    |
| skip_app_version_update                                  | false                                    |
| force                                                    | false                                    |
| overwrite_screenshots                                    | false                                    |
| reject_if_possible                                       | false                                    |
| automatic_release                                        | false                                    |
| phased_release                                           | false                                    |
| reset_ratings                                            | false                                    |
| run_precheck_before_submit                               | true                                     |
| precheck_default_rule_level                              | warn                                     |
| individual_metadata_items                                | []                                       |
| ignore_language_directory_validation                     | false                                    |
| precheck_include_in_app_purchases                        | true                                     |
+----------------------------------------------------------+------------------------------------------+
```

**Comment by joshdholtz** [comment]
Oops! You may need an update I got locally. I'm out getting my mom some coffee at the moment 😛 But I can get that to you in about an hour or so?

**Comment by markmuniz** [comment]
That would be great, thanks!
