### ISSUE TITLE
Add support for Slather's JSON option

### ISSUE THREAD

**Issue by senmu** [fastlane/fastlane#16702]
#### Motivation Behind Feature
Slather has support for a barebones JSON report option. Fastlane's Slather action should be updated so this option can be used so others who find this basic reporting option useful can use it.

#### Feature Description
This feature should add an option to Slather Action that allows to use the `--json` option of Slather command.
This wouldn't break anything for existing users, just adding a functionality.

#### Alternatives or Workarounds
The alternative is using the command line to call Slather with `--json` instead of using the Fastlane action.

**Comment by rogerluan** [comment]
Closing this issue as https://github.com/fastlane/fastlane/pull/16703 was already merged and released 🚀
