### ISSUE TITLE
implement sortOrder Endpoint for 2.150.0 

### ISSUE THREAD

**Issue by bolom** [fastlane/fastlane#16708]
#### Motivation Behind Feature
Reorder Screenshot or Preview with new api

#### Feature Description
implement sortOrder endpoint for Screenshot and Preview

**Comment by joshdholtz** [comment]
Thank you!!

**Comment by joshdholtz** [comment]
Ohhhhh, I don't know if I added in sort order for preview! 😱 I need to add that yet.

**Comment by bolom** [comment]
@joshdholtz in ideal world it will be great to have something like that

```
app_screenshot_set.upload_screenshot(path: path, new_position)

app_preview_set.upload_preview(path: path, new_position)
```
