### ISSUE TITLE
upload_to_testflight Timeout received Spaceship::AccessForbiddenError: Access forbidden

### ISSUE THREAD

**Issue by Sevyls** [fastlane/fastlane#16712]
# New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Fastlane exits with errors, it seems a new API rate limiter is blocking access after 25 requests, 

#### Actual behavior:

My build jobs fail but the upload succeeds. 
Subsequent tasks in this job were not executed.

#### Expected behavior

My build job executes correctly with all tasks/steps.
A warning message instead of exiting, since the upload was correct.

##### Command executed
bundle exec fastlane --verbose beta

##### Complete output when running fastlane, including the stack trace and command used

```
...
INFO [2020-06-30 21:56:34.91]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
 INFO [2020-06-30 21:57:05.42]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
 INFO [2020-06-30 21:57:35.94]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
 INFO [2020-06-30 21:58:06.45]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
 INFO [2020-06-30 21:58:36.87]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
 INFO [2020-06-30 21:59:07.38]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
 INFO [2020-06-30 21:59:37.79]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
 INFO [2020-06-30 22:00:09.55]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
 INFO [2020-06-30 22:00:40.05]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
 INFO [2020-06-30 22:01:11.18]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
 INFO [2020-06-30 22:01:42.01]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
 INFO [2020-06-30 22:02:12.45]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
 INFO [2020-06-30 22:02:42.94]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
 INFO [2020-06-30 22:03:16.64]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 2) for IOS
 INFO [2020-06-30 22:03:47.55]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 2) for IOS
 INFO [2020-06-30 22:04:18.53]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 2) for IOS
 INFO [2020-06-30 22:04:49.30]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 2) for IOS
 INFO [2020-06-30 22:05:20.13]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 2) for IOS
 INFO [2020-06-30 22:05:51.36]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 2) for IOS
 INFO [2020-06-30 22:06:22.59]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 2) for IOS
 INFO [2020-06-30 22:06:53.41]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 2) for IOS
 INFO [2020-06-30 22:07:24.03]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 2) for IOS
 INFO [2020-06-30 22:07:55.19]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 2) for IOS
 INFO [2020-06-30 22:08:26.50]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 2) for IOS
 INFO [2020-06-30 22:08:57.83]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 2) for IOS
 INFO [2020-06-30 22:09:28.76]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 2) for IOS
 INFO [2020-06-30 22:09:59.78]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 2) for IOS
 INFO [2020-06-30 22:10:30.50]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 2) for IOS
 INFO [2020-06-30 22:11:01.24]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 2) for IOS
 INFO [2020-06-30 22:11:31.79]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 2) for IOS
 INFO [2020-06-30 22:12:02.39]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 2) for IOS
 INFO [2020-06-30 22:12:33.38]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 2) for IOS
 INFO [2020-06-30 22:13:04.41]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 2) for IOS
 INFO [2020-06-30 22:13:35.34]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 2) for IOS
 INFO [2020-06-30 22:14:06.47]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 2) for IOS
 INFO [2020-06-30 22:14:37.39]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 2) for IOS
 INFO [2020-06-30 22:15:08.01]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 2) for IOS
 INFO [2020-06-30 22:15:38.94]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 2) for IOS
 INFO [2020-06-30 22:16:09.86]: Waiting for App Store Connect to finish processing the new build (3.0.2 - 2) for IOS
 INFO [2020-06-30 22:16:40.58]: Successfully finished processing the build 3.0.2 - 2 for IOS
 Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 4)...
 Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 3)...
 Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 2)...
 Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 1)...
 WARN [2020-06-30 22:16:55.02]: Lane Context:
 INFO [2020-06-30 22:16:55.02]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :BUILD_NUMBER=>"2", :IPA_OUTPUT_PATH=>"/Users/xxx/builds/_yuGm8Bc/0/.../xxxxxxx.ipa", :XCODEBUILD_ARCHIVE=>"/Users/xxx/Library/Developer/Xcode/Archives/2020-06-30/xxx 2020-06-30 21.43.20.xcarchive", :DSYM_OUTPUT_PATH=>"/Users/xxx/builds/_yuGm8Bc/0/.../xxxxxxx.app.dSYM.zip"}
 ERROR [2020-06-30 22:16:55.02]: Access forbidden
 INFO [2020-06-30 22:16:55.02]: Successfully generated documentation at path '/Users/xxx/builds/_yuGm8Bc/0/.../xxxxxxx/fastlane/README.md'
 +------+------------------------------+-------------+
 |                 fastlane summary                  |
 +------+------------------------------+-------------+
 | Step | Action                       | Time (in s) |
 +------+------------------------------+-------------+
 | 1    | default_platform             | 0           |
 | 2    | increment_build_number       | 1           |
 | 3    | update_code_signing_settings | 0           |
 | 4    | build_app                    | 164         |
 | 💥   | upload_to_testflight         | 1860        |
 +------+------------------------------+-------------+
 DEBUG [2020-06-30 22:16:55.03]: All plugins are up to date
 ERROR [2020-06-30 22:16:55.03]: fastlane finished with errors </pre>
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                                                                       |
| --------------------------- | ----------------------------------------------------------------------------------------------------------- |
| OS                          | 10.15.5                                                                                                     |
| Ruby                        | 2.6.3                                                                                                       |
| Bundler?                    | true                                                                                                        |
| Git                         | git version 2.24.3 (Apple Git-128)                                                                          |
| Installation Source         | ~/builds/_yuGm8Bc/0/.../xxxxxxx/subdir/vendor/bundle/ruby/2.6.0/bin/fastlane |
| Host                        | Mac OS X 10.15.5 (19F101)                                                                                   |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib                                              |
| OpenSSL Version             | LibreSSL 2.8.3                                                                                              |
| Is contained                | false                                                                                                       |
| Is homebrew                 | false                                                                                                       |
| Is installed via Fabric.app | false                                                                                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                                                                 |
| Xcode Version               | 11.5                                                                                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_AT.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "xxx.xcodeproj")
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "xxx.xcodeproj")
    
    build_app(
      workspace: "xxx.xcworkspace",
      scheme: "xxx",
      export_options: {
        provisioningProfiles: {
          "at.xxxx.xxx" => "XC iOS: at.xxxx.xxx"
        }
    })
    
    upload_to_testflight
    git_commit(path: ["./xxx.xcodeproj"], message: "Increment build number")
    version = get_version_number(
      xcodeproj: "./xxx.xcodeproj",
      target: "xxx"
    )
    add_git_tag(prefix: version + "/")
    push_to_git_remote(tags: true)
    
    sentry_upload_dsym(
      auth_token: 'xxxxxx',
      org_slug: 'xxxx',
      project_slug: 'xxxx',
      dsym_path: './xxx.app.dSYM.zip'
    )
    
    refresh_dsyms
    upload_dsyms
    
  end
  
  lane :refresh_dsyms do
    download_dsyms(output_directory: './AppStore-dSYMs')
   
  end
  
  lane :upload_dsyms do
    sentry_upload_dsym(
      auth_token: 'xxxxx',
      org_slug: 'xxxx',
      project_slug: 'xxxx',
      dsym_path: './AppStore-dSYMs'
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("at.xxxx.xxx") # The bundle identifier of your app
apple_id("xxx@yyyyyy.at") # Your Apple email address

itc_team_id("xxxx") # App Store Connect Team ID
team_id("xxxx") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.149.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                 | Version | Update-Status |
| ---------------------- | ------- | ------------- |
| fastlane-plugin-sentry | 1.6.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 2.1.4        |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.337.0      |
| aws-sigv4                 | 1.2.1        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.102.1      |
| aws-sdk-kms               | 1.35.0       |
| aws-sdk-s3                | 1.72.0       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.5.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.75.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 1.0.1        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.1.0        |
| signet                    | 0.14.0       |
| googleauth                | 0.13.0       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.2        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.2       |
| json                      | 2.3.1        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.17.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-sentry    | 1.6.0        |
</details>

*generated on:* **2020-06-30**
</details>

**Comment by Sevyls** [comment]
updated original issue with fastlane env

**Comment by joshdholtz** [comment]
@Sevyls Hey 👋 This looks like it *may* be a permission issue with the Apple account you are using for _fastlane_ 🤔 Has this worked in the past? Did the Apple account's permission get adjusted? Do you know what permission it has right now?

Just from the logs it looks like you might have "Developer" access and it might not be able to update the meta information?

Thanks! ❤️

**Comment by Sevyls** [comment]
Hi @joshdholtz 
thanks for the quick reply.
I use a dedicated CI user here, yes it only has Developer access.

What meta information has to be updated here? Aas the deploy did work correctly, why is this necessary at all?
Is there some switch to disable that so that my build does go through?

Thank you

**Comment by joshdholtz** [comment]
@Sevyls A lot of users use `upload_to_testflight` to edit the changelog or distribute to users in TestFlight. I can't tell exactly how you are using from the information above so that was just an assumption 🙃 Are you using any of those features with `upload_to_testflight`?

**Comment by Sevyls** [comment]
@joshdholtz actually I did provide the Fastfile in fastfile env parts of the issue.
At the momemt I am not using these features, but may be using it in the future.
I just call `upload_to_testflight ` directly without any parameters.

**Comment by joshdholtz** [comment]
@Sevyls Ahhhhh, my bad! I must have missed it. I just woke up so still not fully thinking 🤦 

It looks like it might try to modify some attributes like `notify_external_testers` (which has a default of false). 🤔 But its hard to tell exactly which endpoint it got access forbidden for. 

1) Did this previously work for you or is this the first time you are setting this up?
2) If you aren't making use of any of the metadata things, I would usually set `skip_waiting_for_build_processing: true` which should cut time off your CI by about 20 minutes.

**Comment by Sevyls** [comment]
sorry, I did forget to paste the exception trace - here you go

```
Spaceship::AccessForbiddenError: [!] The request could not be completed because:
1580 	Access forbidden
1581   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/gems/fastlane-2.149.1/spaceship/lib/spaceship/client.rb:873:in `block in send_request'
1582   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/gems/fastlane-2.149.1/spaceship/lib/spaceship/client.rb:626:in `with_retry'
1583   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/gems/fastlane-2.149.1/spaceship/lib/spaceship/client.rb:851:in `send_request'
1584   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/gems/fastlane-2.149.1/spaceship/lib/spaceship/client.rb:695:in `request'
1585   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/gems/fastlane-2.149.1/spaceship/lib/spaceship/connect_api/client.rb:100:in `patch'
1586   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/gems/fastlane-2.149.1/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:78:in `patch_beta_app_review_detail'
1587   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/gems/fastlane-2.149.1/pilot/lib/pilot/build_manager.rb:419:in `update_review_detail'
1588   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/gems/fastlane-2.149.1/pilot/lib/pilot/build_manager.rb:223:in `update_beta_app_meta'
1589   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/gems/fastlane-2.149.1/pilot/lib/pilot/build_manager.rb:153:in `distribute'
1590   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/gems/fastlane-2.149.1/pilot/lib/pilot/build_manager.rb:61:in `upload'
1591   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/actions/upload_to_testflight.rb:16:in `run'
1592   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
1593   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
1594   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
1595   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
1596   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
1597   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
1598   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
1599   Fastfile:35:in `block (2 levels) in parsing_binding'
1600   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/lane.rb:33:in `call'
1601   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
1602   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
1603   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
1604   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
1605   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
1606   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
1607   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
1608   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
1609   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
1610   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/gems/fastlane-2.149.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
1611   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
1612   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
1613   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
1614   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
1615   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/gems/fastlane-2.149.1/bin/fastlane:23:in `<top (required)>'
1616   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `load'
1617   /Users/xxxxx//builds/_yuGm8Bc/0/xxxxx/xxxxx/xxxxx//vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `<top (required)>'
```

**Comment by Sevyls** [comment]
The issue may be with some Apple required US export form regarding encryption. It is randomly requested for every or every second build. I always have to set it manually, no matter what I configure in App Store Connect. I did not change anything at this stage regarding encryption parts of this app.

**Comment by joshdholtz** [comment]
@Sevyls Ah, thank you! It looks like it tried to call `update_review_detail` even though you didn't pass up any `beta_app_review_info` options 😔 That shouldn't be getting called since you didn't pass anything up for that. I will try to look into this today/tomorrow. 

I would still maybe suggest using `skip_waiting_for_build_processing: false` to cut that CI time if not using any of the meta updates that happen after processing is complete 😇

**Comment by Sevyls** [comment]
@joshdholtz Thank you for your quick reaction :-)

**Comment by Sevyls** [comment]
> 1. Did this previously work for you or is this the first time you are setting this up?

It did work with my personal App Store Connect account, but as I am trying to centralize a general account for it, you may call it the first time here. 

> 2. If you aren't making use of any of the metadata things, I would usually set `skip_waiting_for_build_processing: true` which should cut time off your CI by about 20 minutes.

Thanks, but I regard deploying to TestFlight and getting the email notification at the right moment once it is available in TestFlight as really useful. The issue with this export encryption form is really annoying, but I can't see any option to automate it at the moment.

**Comment by joshdholtz** [comment]
@Sevyls I'm not sure if you've tried this but you can set `ITSAppUsesNonExemptEncryption` to `NO` in your `Info.plist`. App Store Connect will detect that so that neither you (nor _fastlane_) need to set that.

More info here 👉  https://developer.apple.com/documentation/security/complying_with_encryption_export_regulations

Also... I think if you upgrade your users from "Developer" to "App Manager" that things should work for you. "Developer" only has TestFlight read access where "App Manager" has full access. 

If you are able to try "App Manager" that would be 💯 

### Developer

<img width="428" alt="Screen Shot 2020-07-01 at 7 25 08 AM" src="https://user-images.githubusercontent.com/401294/86243461-0d2aeb00-bb6c-11ea-8e12-a57c24639773.png">

### App Manager

<img width="427" alt="Screen Shot 2020-07-01 at 7 25 13 AM" src="https://user-images.githubusercontent.com/401294/86243473-11ef9f00-bb6c-11ea-8387-355ad57a6d43.png">

**Comment by Sevyls** [comment]
Thanks so much for this hint with the plist entry. I did set it in another project and assumed I had it set in this one too 🙈

Will try go increase the role permission for the CI user. Thanks again.

**Comment by Sevyls** [comment]
Thanks - both Info.plist with ITSAppUsesNonExemptEncryption and the user's permissions as App manager worked fine.

**Comment by joshdholtz** [comment]
@skevy Thanks for reporting back! I will update the docs to say "App Manager" is required 😊
