### ISSUE TITLE
Could not find 'slack-notifier' (>= 2.0.0, < 3.0.0) among 62 total gem(s) (Gem::MissingSpecError)

### ISSUE THREAD

**Issue by Lin-Bing** [fastlane/fastlane#16724]
ruby version 2.6.5
I'm in trouble when Upgraded to the latest version。Whenever I execute fastlane command，I got this。。。

/Users/xxxx/.rvm/rubies/ruby-2.6.5/bin/bin-proxy
/Users/xxxx/.rvm/rubies/ruby-2.6.5/bin/fastlane
Successfully installed fastlane-2.150.0
1 gem installed
xxxx-mini:ios xxxx$ fastlane --version
Traceback (most recent call last):
	10: from /Users/xxxx/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
	 9: from /Users/xxxx/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
	 8: from /Users/xxxx/.rvm/gems/ruby-2.6.5/bin/fastlane:23:in `<main>'
	 7: from /Users/xxxx/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems.rb:304:in `activate_bin_path'
	 6: from /Users/xxxx/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems.rb:304:in `synchronize'
	 5: from /Users/xxxx/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems.rb:305:in `block in activate_bin_path'
	 4: from /Users/xxxx/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:1417:in `activate'
	 3: from /Users/xxxx/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:1435:in `activate_dependencies'
	 2: from /Users/xxxx/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:1435:in `each'
	 1: from /Users/xxxx/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:1446:in `block in activate_dependencies'
/Users/xxxx/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'slack-notifier' (>= 2.0.0, < 3.0.0) among 62 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/Users/xxxx/.rvm/gems/ruby-2.6.5:/Users/xxxx/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0', execute `gem env` for more information

**Comment by joshdholtz** [comment]
@Lin-Bing Hey! Can you upload your `fastlane env` please? 🙂

**Comment by Lin-Bing** [comment]
I got the same error when run 'fastlane env'

yaochufadeMac-mini:ios yaochufa$ fastlane env
Traceback (most recent call last):
	10: from /Users/yaochufa/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
	 9: from /Users/yaochufa/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
	 8: from /Users/yaochufa/.rvm/gems/ruby-2.6.5/bin/fastlane:23:in `<main>'
	 7: from /Users/yaochufa/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems.rb:304:in `activate_bin_path'
	 6: from /Users/yaochufa/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems.rb:304:in `synchronize'
	 5: from /Users/yaochufa/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems.rb:305:in `block in activate_bin_path'
	 4: from /Users/yaochufa/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:1417:in `activate'
	 3: from /Users/yaochufa/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:1435:in `activate_dependencies'
	 2: from /Users/yaochufa/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:1435:in `each'
	 1: from /Users/yaochufa/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:1446:in `block in activate_dependencies'
/Users/yaochufa/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'slack-notifier' (>= 2.0.0, < 3.0.0) among 62 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/Users/yaochufa/.rvm/gems/ruby-2.6.5:/Users/yaochufa/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0', execute `gem env` for more information



===================================================
'gem env' is as follows。。。

yaochufadeMac-mini:ios yaochufa$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.0.8
  - RUBY VERSION: 2.6.5 (2019-10-01 patchlevel 114) [x86_64-darwin18]
  - INSTALLATION DIRECTORY: /Users/yaochufa/.rvm/gems/ruby-2.6.5
  - USER INSTALLATION DIRECTORY: /Users/yaochufa/.gem/ruby/2.6.0
  - RUBY EXECUTABLE: /Users/yaochufa/.rvm/rubies/ruby-2.6.5/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /Users/yaochufa/.rvm/gems/ruby-2.6.5/bin
  - SPEC CACHE DIRECTORY: /Users/yaochufa/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/yaochufa/.rvm/rubies/ruby-2.6.5/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-18
  - GEM PATHS:
     - /Users/yaochufa/.rvm/gems/ruby-2.6.5
     - /usr/local/lib/ruby/gems/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :sources => ["https://rubygems.org"]
     - "gempath" => ["/usr/local/lib/ruby/gems/2.3.0", "/usr/local/lib/ruby/gems/2.3.0"]
  - REMOTE SOURCES:
     - https://rubygems.org
  - SHELL PATH:
     - /Users/yaochufa/.rvm/gems/ruby-2.6.5/bin
     - /Users/yaochufa/.rvm/gems/ruby-2.6.5@global/bin
     - /Users/yaochufa/.rvm/rubies/ruby-2.6.5/bin
     - /Users/yaochufa/.rvm/bin
     - /Users/yaochufa/homebrew/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin

**Comment by joshdholtz** [comment]
Hmmm 🤔 Are you using a `Gemfile` to install fastlane? Or did you install with `gem install fastlane`?

**Comment by Lin-Bing** [comment]
> Hmmm 🤔 Are you using a `Gemfile` to install fastlane? Or did you install with `gem install fastlane`?



I downgraded the ruby verison from 2.6.5 to 2.4.0。 and reinstall fastlane using ‘sudo gem install fastlane -NV’。And the installation was successful with ‘successfully installed fastlane-2.150.0’。 But I got another error when run 'fastlane --version' 。the log is as follow。。

yaochufadeMac-mini:ios yaochufa$ sudo gem install fastlane -NV
。。。。
/Users/yaochufa/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.150.0/supply/lib/supply/uploader.rb
/Users/yaochufa/.rvm/rubies/ruby-2.4.0/bin/bin-proxy
/Users/yaochufa/.rvm/rubies/ruby-2.4.0/bin/fastlane
Successfully installed fastlane-2.150.0
13 gems installed

yaochufadeMac-mini:ios yaochufa$ fastlane --version
-bash: /usr/local/bin/fastlane: /usr/local/opt/ruby/bin/ruby: bad interpreter: No such file or directory

**Comment by Lin-Bing** [comment]
> Hmmm 🤔 Are you using a `Gemfile` to install fastlane? Or did you install with `gem install fastlane`?


YES， i did。
Is there something wrong with my ruby env？？？


I downgraded the ruby verison from 2.6.5 to 2.4.0。 and reinstall fastlane using ‘sudo gem install fastlane -NV’。And the installation was successful with ‘successfully installed fastlane-2.150.0’。 But I got another error when run 'fastlane --version' 。the log is as follow。。

yaochufadeMac-mini:ios yaochufa$ sudo gem install fastlane -NV
。。。。
/Users/yaochufa/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.150.0/supply/lib/supply/uploader.rb
/Users/yaochufa/.rvm/rubies/ruby-2.4.0/bin/bin-proxy
/Users/yaochufa/.rvm/rubies/ruby-2.4.0/bin/fastlane
Successfully installed fastlane-2.150.0
13 gems installed

yaochufadeMac-mini:ios yaochufa$ fastlane --version
/Users/yaochufa/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'slack-notifier' (>= 2.0.0, < 3.0.0) among 32 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/Users/yaochufa/.rvm/gems/ruby-2.4.0:/Users/yaochufa/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0', execute `gem env` for more information
	from /Users/yaochufa/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1446:in `block in activate_dependencies'
	from /Users/yaochufa/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1435:in `each'
	from /Users/yaochufa/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1435:in `activate_dependencies'
	from /Users/yaochufa/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1417:in `activate'
	from /Users/yaochufa/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems.rb:305:in `block in activate_bin_path'
	from /Users/yaochufa/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems.rb:304:in `synchronize'
	from /Users/yaochufa/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems.rb:304:in `activate_bin_path'
	from /Users/yaochufa/.rvm/rubies/ruby-2.4.0/bin/fastlane:23:in `<main>'
	from /Users/yaochufa/.rvm/rubies/ruby-2.4.0/bin/ruby_executable_hooks:24:in `eval'
	from /Users/yaochufa/.rvm/rubies/ruby-2.4.0/bin/ruby_executable_hooks:24:in `<main>'
