### ISSUE TITLE
2.150.0 deliver app_review_attachment_file failed, Server error got 500

### ISSUE THREAD

**Issue by lanyutc** [fastlane/fastlane#16729]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I am trying to upload attachment file by deliver, but it doesn't work

##### Command executed
fastlane deliver app_review_attachment_file

##### Complete output when running fastlane, including the stack trace and command used
+--------------------------------------+---------------------------------------------------------------+
|                                       deliver 2.150.0 Summary                                        |
+--------------------------------------+---------------------------------------------------------------+
| skip_binary_upload                   | true                                                          |
| skip_screenshots                     | true                                                          |
| app_review_attachment_file           | attachment_file.pdf |
| force                                | true                                                          |
| run_precheck_before_submit           | false                                                         |
| username                             | xxxxxx                                          |
| app_identifier                       | xxxxxx                                             |
| screenshots_path                     | ./screenshots                                                 |
| metadata_path                        | ./metadata                                                    |
| platform                             | ios                                                           |
| edit_live                            | false                                                         |
| use_live_version                     | false                                                         |
| skip_metadata                        | false                                                         |
| skip_app_version_update              | false                                                         |
| overwrite_screenshots                | false                                                         |
| submit_for_review                    | false                                                         |
| reject_if_possible                   | false                                                         |
| automatic_release                    | false                                                         |
| phased_release                       | false                                                         |
| reset_ratings                        | false                                                         |
| precheck_default_rule_level          | warn                                                          |
| individual_metadata_items            | []                                                            |
| ignore_language_directory_validation | false                                                         |
| precheck_include_in_app_purchases    | true                                                          |
+--------------------------------------+---------------------------------------------------------------+

: Uploading metadata to App Store Connect for version
: Uploading app review information to App Store Connect
: Uploading review attachment file to App Store Connect
[!] The request could not be completed because:
	Server error got 500

**Comment by joshdholtz** [comment]
Thanks for report! Will look into right away 👍
