### ISSUE TITLE
get_app_info_localizations returning Spaceship::ConnectAPI::Response 

### ISSUE THREAD

**Issue by nesfahani** [fastlane/fastlane#16726]
Hello, awesome work on the recent updates!
I just wanted to point out a small issue I see in the new releases ( I am on 2.150.0)

### Issue Description

I am trying to update the privacy policy url of an app like this:

 ```
app = Spaceship::ConnectAPI::App.find(options[:bundle_id])
app_info = app.fetch_edit_app_info
app_info.get_app_info_localizations.update(attributes: {privacyPolicyUrl: "test"})
```

but get_app_info_localizations seems to return a Response object instead of the app_info_localization model, so I can not update

### New Release Candidate Issue Checklist

- [X] Updated fastlane to the latest release candidate version (2.150.0.rcX)
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)
### Mentioning

cc: @joshdholtz

**Comment by nesfahani** [comment]
never mind my mistake!

**Comment by joshdholtz** [comment]
Ah, thanks!! ❤️ Will fix when I get up in the morning 🙂
