### ISSUE TITLE
Ipa size double compared to xcode

### ISSUE THREAD

**Issue by DeathStalker403** [fastlane/fastlane#16734]
### Question Checklist

- [X ] Updated fastlane to the latest version 
Using 1.4.9
- [ 👍] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ 👍] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ 👍] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Gym

No

No
#### Question Description

When i try to build using fastlane gym the ipa size is nearly  double than the normal xcode build. Previously we use to use jenkins xcode plugin but recently shifted to fastlane but the app size is bothering us too much now. Needed quick help on it as it a prod issue for us.

Thanks

**Comment by joshdholtz** [comment]
@DeathStalker403 Are you including bit code when you build through xcode?

**Comment by DeathStalker403** [comment]
No. Have skipped that as well the symbols. Also tried the app thinning for all variant. After skipping symbols and bitcode it was less by 20-30mb but our main ipa is around 280mb and when build from fastlane it goest to ~438mb.

**Comment by joshdholtz** [comment]
@DeathStalker403 Hmmm 🤔  So just to confirm... You did set `include_bitcode: false` and `include_symbols: false` when using _gym_, correct?

**Comment by DeathStalker403** [comment]
Correct

**Comment by joshdholtz** [comment]
Do you happen to know/have the `xcodebuild` command that your previous Jenkins setup executed to build your IPA?

**Comment by DeathStalker403** [comment]
This is what jenkins plugin used 

Archive

/usr/bin/xcodebuild -scheme boubyan -workspace /Users/DevSecOps/jenkins/workspace/MB-iOS/abc.xcworkspace -configuration Debug archive -archivePath /Users/DevSecops/jenkins/workspace/MB- 105/Debug/abc.xcarchive BUILD_DIR=/Users/DevSecOps/jenkins/workspace/MB- 105/Debug/ DEVELOPMENT TEAM-6TXXXX9XXX

Export

/usr/bin/xcodebuild exportArchive - archivePath Users/DevSecOpsſjenkins/workspace/MB-iOS/Release/abc.xcarchive -exportPath Users/DevSecOps jenkins/workspace/MB-iOS/Release-exportOptionsPlist Users/DevSecOpsſjenkins/workspace/MB-iOS/Release/app storeExportOptions.plist

**Comment by joshdholtz** [comment]
That command seems simple enough 🤔 Do you happen to have the output from your _fastlane_ / _gym_ commands? That should also show what `xcodebuild` commands that _gym_ is using. I just want to make sure there are not major differences there.

**Comment by DeathStalker403** [comment]
set -o pipefail && xcodebuild workspace ../abc.xcworkspace -scheme abc configuration Debug -destination 'generic/platform=iOS' archivePath /Users/DevSecOps/Library/Developer/Xcode/Archives/2020-07 PS/Library/Develop a platform-ios 02/abc-beta\ 2020-07-02\ 21.41.50.xcarchive CODE SIGNING ALLOWED="NO" clean archive tee /Users/DevSec0ps/Library/Logs/gym/abc-abc. log
xcpretty

This is what is building an unsigned ipa. Could be missing the skip bitcode and symbol as it was included back as

**Comment by DeathStalker403** [comment]
Clicked on close by mistake. Please ignore.

**Comment by joshdholtz** [comment]
Ha, I hit that close button by accident way too often 🤷‍♂️ 

And those `xcodebuild` commands look pretty similar 🤔 I'm not sure why the build out of _fastlane_ would be bigger...
The only things I can think of are:
1) new code/features/assets were added between when you moved from jenkins to fastlane
    - I'm not sure if this is the case at all? Just a thought
2) different version of xcode?
    - Also not sure
3) were there any other build settings that were tweaked between moving from jenkins to fastlane?

_gym_ really just wraps a simple `xcodebuild` command. I'm a bit confused 🤔

**Comment by DeathStalker403** [comment]
I think None of the above happened. As i was testing the commands on a sample code. It took me just 1/2 hr to migrate to fastlane for this project. So I'm pretty sure there is no chance them happening. Maybe 1% cauz u cannot be 100% accurate thou. 🤐

Here is what the lane looks like for gym. Please don't mind the indent and other stuff as we are in very restricted env i have to do a ocr for them. Maybe it can show what we are missing thou. Note: skip options not present as they were removed intentionally. 

lane build dev do 
build_app{
 clean: true, 
 workspace: "../abc.xcworkspace",
 configuration: "Debug",
scheme: "abc",
output directory: ../Debug' 
output name: "abc-beta. ipa 
export team id: "xxxxx", 
Xcargs:
"CODE SIGNING ALLOWED='NO"
} 
end

**Comment by DeathStalker403** [comment]
Dear Josh,
i think the issue might be related to not signing with gym. and with multiple targets we are unable to sign the ipa. 
Please can you direct on how to proceed?

**Comment by joshdholtz** [comment]
@DeathStalker403 Hey! 👋 Did you end up figuring out the issue?
