### ISSUE TITLE
useless FASTLANE_SKIP_UPDATE_CHECK for skip update

### ISSUE THREAD

**Issue by david-m-globant** [fastlane/fastlane#16737]
Hi team

Right now, the only way to omit update fastlane is add the option **_update_fastlane=no_update_**

`fastlane lane update_fastlane=no_update`

thanks [viktorbenei](https://discuss.bitrise.io/t/how-to-use-a-specific-version-of-fastlane/1001)

it's possible use FASTLANE_SKIP_UPDATE_CHECK to omit update ? 

Maybe if you add this line `return if Fastlane::Env.truthy?("FASTLANE_SKIP_UPDATE_CHECK")` bellow this [line](https://github.com/fastlane/fastlane/blob/86e6baadfad485a775a367e2c66922623766721d/fastlane/lib/fastlane/actions/update_fastlane.rb#L11)  

Thanks

**Comment by janpio** [comment]
That should already work: https://docs.fastlane.tools/advanced/fastlane/#skip-update-check-when-launching-fastlane
Does it not?

**Comment by david-m-globant** [comment]
Sorry guys, my Fastlane file has this first command `update_fastlane` so a remove that and works. Thanks anyway :D
