### ISSUE TITLE
How to run any Action from inside a custom Ruby class or module?

### ISSUE THREAD

**Issue by goetzc** [fastlane/fastlane#16736]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Use/call an Action from inside a custom class or module.

#### Question Description
Like https://github.com/fastlane/fastlane/issues/16060, I'm experiencing that calling any ~Plugin~ Action from inside a custom class or module does not work, contrary to calling it directly, which does work. I'm including the error message and a short example below.

How can this be archived? 

```sh
[12:19:14]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
bundler: failed to load command: fastlane (/home/goetz/.asdf/installs/ruby/2.7.1/bin/fastlane)
NoMethodError: [!] undefined method `sh' for Fastlane::FastFile::MyModule:Module
…
```

`./fastlane/Fastfile`:

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
# frozen_string_literal: true

platform :android do
  lane :test do
    MyModule.my_method
  end
end

module MyModule
  def self.my_method
    puts 'Calling the action'
    # NOTE: this is not specific to this particular action
    sh(…)
  end
end
```

**EDIT:** It does not only happen with Plugins, but with any build-in Action.

**Comment by goetzc** [comment]
It does also happen with any Action, not only when using Plugins.

Looks like the solution is similar to issues #826, so:

```ruby
module MyModule
  def self.my_method
    sh 'ls -lh'           # Does _not_ work
    Actions.sh 'ls -lh'   # Does work
  end
end
```

For Actions coming from Plugins, it has to be [called](https://github.com/fastlane/fastlane/issues/826#issuecomment-156267861) using the class name:

```ruby
module MyModule
  def self.my_method
    MyCustomAction.run(…)
  end
end
```

Anyway, how to call the action —from inside a custom call or module— using just the shorter friendly action name?

**Comment by goetzc** [comment]
No, bot, not resolved.

**Comment by goetzc** [comment]
Not resolved.

**Comment by goetzc** [comment]
Not resolved

**Comment by minuscorp** [comment]
Change `MyMdodule` for `::MyModule`, ultimately keep your code in a class, a module seems too much IMO.

**Comment by goetzc** [comment]
@minuscorp Using the scope resolution operator produces the same result. For the class/module, the reason is I don't need to keep a state.

**Comment by minuscorp** [comment]
Use static or class functions maybe?
