### ISSUE TITLE
Spaceship::UnexpectedResponse: [!] The URL path is not valid - The relationship 'appReviewAttachments' does not exist

### ISSUE THREAD

**Issue by mohsinahd** [fastlane/fastlane#16732]
While upload meta using `upload_to_app_store` function, I recently started to get following error:

**Spaceship::UnexpectedResponse: [!] The URL path is not valid - The relationship 'appReviewAttachments' does not exist**

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.5                                     |
| Ruby                        | 2.5.5                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.1 (Apple Git-122.3)        |
| Installation Source         | ~/.rbenv/versions/2.5.5/bin/fastlane        |
| Host                        | Mac OS X 10.15.5 (19F101)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.5/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.3.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
opt_out_usage
import 'IosFastfile'

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version     | Update-Status      |
| -------- | ----------- | ------------------ |
| fastlane | 2.150.0.rc5 | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status |
| ----------------------- | ------- | ------------- |
| fastlane-plugin-appicon | 0.15.0  | ✅ Up-To-Date  |
| fastlane-plugin-brew    | 0.1.1   | ✅ Up-To-Date  |
| fastlane-plugin-act     | 1.2.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| CFPropertyList            | 3.0.2        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| emoji_regex               | 1.0.1        |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.17.0       |
| unicode-display_width     | 1.7.0        |
| public_suffix             | 4.0.5        |
| tty-screen                | 0.8.0        |
| excon                     | 0.75.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| faraday_middleware        | 1.0.0        |
| json                      | 2.3.0        |
| declarative               | 0.0.20       |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| os                        | 1.1.0        |
| memoist                   | 0.16.2       |
| googleauth                | 0.13.0       |
| digest-crc                | 0.6.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-env          | 1.3.2        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.2       |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.1        |
| aws-partitions            | 1.337.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.103.0      |
| aws-sdk-kms               | 1.35.0       |
| aws-sdk-s3                | 1.72.0       |
| stringio                  | 0.0.1        |
| openssl                   | 2.1.2        |
| strscan                   | 1.0.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| etc                       | 1.0.0        |
| io-console                | 0.4.6        |
| zlib                      | 1.0.0        |
| ipaddr                    | 1.2.2        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.9       |
| psych                     | 3.0.2        |
| webrick                   | 1.4.2        |
| mime-types                | 3.3.1        |
| netrc                     | 0.11.0       |
| rest-client               | 2.0.2        |
| mime-types-data           | 3.2020.0512  |
| fastlane-plugin-appicon   | 0.15.0       |
| fastlane-plugin-brew      | 0.1.1        |
| fastlane-plugin-act       | 1.2.1        |
</details>

*generated on:* **2020-07-02**
</details>

**Comment by joshdholtz** [comment]
@mohsinahd This is fixed `2.150.1` already!

**Comment by mohsinahd** [comment]
Thanks for the quick response. I can confirm that latest release has fixed the problem.
