### ISSUE TITLE
Sudden failure with Pilot

### ISSUE THREAD

**Issue by nicklocking** [fastlane/fastlane#16746]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm getting a sudden new error when uploading builds to the App Store. No obvious cause, everything's been fine, no recent changes to fastfile, or anything else that would break this.

##### Command executed

`fastlane pilot upload --verbose`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>nicholass-mbp-2:client_mobile_ios nicholaslocking$ fastlane pilot upload --verbose
[✔] 🚀 
[15:38:16]: fastlane detected a Gemfile in the current directory
[15:38:16]: However, it seems like you didn't use `bundle exec`
[15:38:16]: To launch fastlane faster, please use
[15:38:16]: 
[15:38:16]: $ bundle exec fastlane pilot upload --verbose
[15:38:16]: 
[15:38:16]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
Successfully loaded Appfile at path '/Users/nicholaslocking/client_mobile_ios/fastlane/Appfile'
- app_identifier: 'xxxxx'
- itc_team_id: 'xxxxxx'
- apple_id: 'xxxxxxx'
-------
INFO [2020-07-03 15:38:19.03]: Login to App Store Connect (nick.locking@pray.com)
Reading keychain entry, because either user or password were empty
Loading session from '/Users/nicholaslocking/.fastlane/spaceship/nick.locking@pray.com/cookie'
Looking for App Store Connect Team with ID 118416291
INFO [2020-07-03 15:38:21.40]: Login successful
DEBUG [2020-07-03 15:38:21.40]: App identifier (com.prayapp.pray)
INFO [2020-07-03 15:38:24.42]: Ready to upload new build to TestFlight (App: 1161035371)...
DEBUG [2020-07-03 15:38:24.42]: App Platform (ios)
INFO [2020-07-03 15:38:25.91]: Wrote XML data to '/var/folders/pr/7wbdt92d2dx8_qnh6471g2v40000gn/T/d20200703-27806-1typ154/1161035371.itmsp'
DEBUG [2020-07-03 15:38:25.98]: xcrun iTMSTransporter -m provider -u nick.locking@pray.com -p YourPassword 2>&1
DEBUG [2020-07-03 15:38:26.90]: [Transporter]: INFO: An error occurred checking the HEAD for: https://contentdelivery.itunes.apple.com/transporter/repositories/j2se8/latest/repository.xml sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target Exception's name: javax.net.ssl.SSLHandshakeException, Exception's message: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
DEBUG [2020-07-03 15:38:27.01]: [Transporter]: INFO: An error occurred checking the HEAD for: https://contentdelivery.itunes.apple.com/transporter/repositories/j2se7/latest/repository.xml sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target Exception's name: javax.net.ssl.SSLHandshakeException, Exception's message: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
DEBUG [2020-07-03 15:38:27.15]: [Transporter]: INFO: An error occurred checking the HEAD for: https://contentdelivery.itunes.apple.com/transporter/repositories/j2se6/latest/repository.xml sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target Exception's name: javax.net.ssl.SSLHandshakeException, Exception's message: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
DEBUG [2020-07-03 15:38:27.26]: [Transporter]: INFO: An error occurred checking the HEAD for: https://contentdelivery.itunes.apple.com/transporter/repositories/j2se5/latest/repository.xml sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target Exception's name: javax.net.ssl.SSLHandshakeException, Exception's message: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
WARN [2020-07-03 15:38:27.28]: [iTMSTransporter] java.lang.reflect.InvocationTargetException

WARN [2020-07-03 15:38:27.28]: [iTMSTransporter] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

WARN [2020-07-03 15:38:27.28]: [iTMSTransporter] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

WARN [2020-07-03 15:38:27.28]: [iTMSTransporter] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

WARN [2020-07-03 15:38:27.28]: [iTMSTransporter] 	at java.lang.reflect.Method.invoke(Method.java:498)

WARN [2020-07-03 15:38:27.28]: [iTMSTransporter] 	at com.apple.transporter.launcher.Application.start(Application.java:220)

WARN [2020-07-03 15:38:27.28]: [iTMSTransporter] 	at com.apple.transporter.launcher.Application.main(Application.java:658)

WARN [2020-07-03 15:38:27.28]: [iTMSTransporter] Caused by: java.io.IOException: Could not connect to any repositories

WARN [2020-07-03 15:38:27.28]: [iTMSTransporter] 	at com.apple.transporter.misc.RemoteBundleRepository.getRepositoryUriAndEtag(RemoteBundleRepository.java:227)

WARN [2020-07-03 15:38:27.28]: [iTMSTransporter] 	at com.apple.transporter.misc.RemoteBundleRepository.loadResourcesFromRepository(RemoteBundleRepository.java:141)

WARN [2020-07-03 15:38:27.28]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.downloadNeededBundles(BootstrapperPhase1.java:249)

WARN [2020-07-03 15:38:27.28]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.bootstrap(BootstrapperPhase1.java:97)

WARN [2020-07-03 15:38:27.28]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.bootstrap(BootstrapperPhase1.java:59)

WARN [2020-07-03 15:38:27.28]: [iTMSTransporter] 	at com.apple.transporter.launcher.Launcher.launchBootstrapper(Launcher.java:37)

WARN [2020-07-03 15:38:27.28]: [iTMSTransporter] 	... 6 more

INFO [2020-07-03 15:38:27.28]: iTunes Transporter output above ^
ERROR [2020-07-03 15:38:27.28]: The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
DEBUG [2020-07-03 15:38:27.28]: Inferred provider id  for team Pray, Inc..
INFO [2020-07-03 15:38:27.36]: Going to upload updated app to App Store Connect
INFO [2020-07-03 15:38:27.36]: This might take a few minutes. Please don't interrupt the script.
DEBUG [2020-07-03 15:38:27.36]: xcrun iTMSTransporter -m upload -u nick.locking@pray.com -p YourPassword -f /var/folders/pr/7wbdt92d2dx8_qnh6471g2v40000gn/T/d20200703-27806-1typ154/1161035371.itmsp -t DAV,Signiant -k 100000 2>&1
DEBUG [2020-07-03 15:38:28.14]: [Transporter]: INFO: An error occurred checking the HEAD for: https://contentdelivery.itunes.apple.com/transporter/repositories/j2se8/latest/repository.xml sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target Exception's name: javax.net.ssl.SSLHandshakeException, Exception's message: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
DEBUG [2020-07-03 15:38:28.27]: [Transporter]: INFO: An error occurred checking the HEAD for: https://contentdelivery.itunes.apple.com/transporter/repositories/j2se7/latest/repository.xml sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target Exception's name: javax.net.ssl.SSLHandshakeException, Exception's message: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
DEBUG [2020-07-03 15:38:28.39]: [Transporter]: INFO: An error occurred checking the HEAD for: https://contentdelivery.itunes.apple.com/transporter/repositories/j2se6/latest/repository.xml sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target Exception's name: javax.net.ssl.SSLHandshakeException, Exception's message: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
DEBUG [2020-07-03 15:38:28.51]: [Transporter]: INFO: An error occurred checking the HEAD for: https://contentdelivery.itunes.apple.com/transporter/repositories/j2se5/latest/repository.xml sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target Exception's name: javax.net.ssl.SSLHandshakeException, Exception's message: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
WARN [2020-07-03 15:38:28.53]: [iTMSTransporter] java.lang.reflect.InvocationTargetException

WARN [2020-07-03 15:38:28.53]: [iTMSTransporter] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

WARN [2020-07-03 15:38:28.53]: [iTMSTransporter] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

WARN [2020-07-03 15:38:28.53]: [iTMSTransporter] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

WARN [2020-07-03 15:38:28.53]: [iTMSTransporter] 	at java.lang.reflect.Method.invoke(Method.java:498)

WARN [2020-07-03 15:38:28.53]: [iTMSTransporter] 	at com.apple.transporter.launcher.Application.start(Application.java:220)

WARN [2020-07-03 15:38:28.53]: [iTMSTransporter] 	at com.apple.transporter.launcher.Application.main(Application.java:658)

WARN [2020-07-03 15:38:28.53]: [iTMSTransporter] Caused by: java.io.IOException: Could not connect to any repositories

WARN [2020-07-03 15:38:28.53]: [iTMSTransporter] 	at com.apple.transporter.misc.RemoteBundleRepository.getRepositoryUriAndEtag(RemoteBundleRepository.java:227)

WARN [2020-07-03 15:38:28.53]: [iTMSTransporter] 	at com.apple.transporter.misc.RemoteBundleRepository.loadResourcesFromRepository(RemoteBundleRepository.java:141)

WARN [2020-07-03 15:38:28.53]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.downloadNeededBundles(BootstrapperPhase1.java:249)

WARN [2020-07-03 15:38:28.53]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.bootstrap(BootstrapperPhase1.java:97)

WARN [2020-07-03 15:38:28.53]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.bootstrap(BootstrapperPhase1.java:59)

WARN [2020-07-03 15:38:28.53]: [iTMSTransporter] 	at com.apple.transporter.launcher.Launcher.launchBootstrapper(Launcher.java:37)

WARN [2020-07-03 15:38:28.53]: [iTMSTransporter] 	... 6 more

INFO [2020-07-03 15:38:28.53]: iTunes Transporter output above ^
ERROR [2020-07-03 15:38:28.53]: The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
Traceback (most recent call last):
	14: from /usr/local/bin/fastlane:23:in `<main>'
	13: from /usr/local/bin/fastlane:23:in `load'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.1/bin/fastlane:23:in `<top (required)>'
	11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.1/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.1/pilot/lib/pilot/commands_generator.rb:18:in `start'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.1/pilot/lib/pilot/commands_generator.rb:166:in `run'
	 8: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 6: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 5: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 4: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.1/pilot/lib/pilot/commands_generator.rb:66:in `block (2 levels) in run'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.1/pilot/lib/pilot/build_manager.rb:37:in `upload'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': Error uploading ipa file, for more information see above (FastlaneCore::Interface::FastlaneError)
	14: from /usr/local/bin/fastlane:23:in `<main>'
	13: from /usr/local/bin/fastlane:23:in `load'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.1/bin/fastlane:23:in `<top (required)>'
	11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.1/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.1/pilot/lib/pilot/commands_generator.rb:18:in `start'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.1/pilot/lib/pilot/commands_generator.rb:166:in `run'
	 8: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 6: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 5: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 4: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.1/pilot/lib/pilot/commands_generator.rb:66:in `block (2 levels) in run'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.1/pilot/lib/pilot/build_manager.rb:37:in `upload'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.150.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Error uploading ipa file, for more information see above (FastlaneCore::Interface::FastlaneError)</pre>
</details>

### Environment

<details>
  <pre>### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.5                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.21.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.5 (19F101)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.5                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

xxx fastfile skipped xxx

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.150.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

Loaded gems

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.72.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.3       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.13.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.9.0        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| CFPropertyList            | 3.0.2        |
| faraday                   | 0.17.3       |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.1.3        |
| aws-partitions            | 1.310.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.94.1       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.63.1       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |

</pre>
</details>

**Comment by janpio** [comment]
Did it work with 2.150.x before or might this be related to updating to that version?
