### ISSUE TITLE
Cannot add_plugin aws_s3

### ISSUE THREAD

**Issue by ducnnguyen** [fastlane/fastlane#16762]
### New Release Candidate Issue Checklist

- [x] Updated fastlane to the latest release candidate version (2.150.0.rcX)
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Information

- Breaking version: 2.150.3
- Last working version: [e.g. `2.x.x`]
- State of app: [e.g. `Prepare for Submission`, `Developer Rejected`]
- First version of app?: [e.g. `Yes`]

### Issue Description
Cannot add_plugin aws_s3
`bundle exec fastlane add_plugin aws_s3`
##### Complete output when running fastlane, including the stack trace and command used
```
Installing plugin dependencies...
Bundler could not find compatible versions for gem "rubyzip":
  In snapshot (Gemfile.lock):
    rubyzip (= 2.3.0)

  In Gemfile:
    fastlane-plugin-aws_s3 was resolved to 1.8.0, which depends on
      apktools (~> 0.7) was resolved to 0.7.1, which depends on
        rubyzip (~> 1.1)

    fastlane (= 2.150.3) was resolved to 2.150.3, which depends on
      rubyzip (>= 2.0.0, < 3.0.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

<details>
  <pre>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.5                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.21.1 (Apple Git-122.3)                           |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.5 (19F101)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.3.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.150.3 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                 | Version   | Update-Status  |
| ---------------------- | --------- | -------------- |
| fastlane-plugin-badge  | 1.4.0     | ✅ Up-To-Date   |
| fastlane-plugin-aws_s3 | undefined | 💥 Check failed |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 2.1.4        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.17.0       |
| unicode-display_width     | 1.7.0        |
| public_suffix             | 4.0.5        |
| addressable               | 2.7.0        |
| tty-screen                | 0.8.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| excon                     | 0.75.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| json                      | 2.3.1        |
| mini_magick               | 4.10.1       |
| dotenv                    | 2.7.5        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| declarative               | 0.0.20       |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| os                        | 1.1.0        |
| memoist                   | 0.16.2       |
| googleauth                | 0.13.0       |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-env          | 1.3.2        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.2       |
| emoji_regex               | 3.0.0        |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.1        |
| aws-partitions            | 1.338.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.103.0      |
| aws-sdk-kms               | 1.36.0       |
| aws-sdk-s3                | 1.73.0       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.2.4        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
| curb                      | 0.9.10       |
| badge                     | 0.12.0       |
| fastlane-plugin-badge     | 1.4.0        |
</details>

*generated on:* **2020-07-06**
</details>
</pre>
</details>

### Spaceship Logs

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Mentioning

cc: @joshdholtz

**Comment by joshdholtz** [comment]
@ducnnguyen Looks like we are currently waiting on https://github.com/devunwired/apktools/pull/26 (by @giginet) to be merged in 😊 

You should be able to add 👇 to your `Gemfile` to fix this:
```rb
gem "apktools", git: "https://github.com/giginet/apktools.git", branch: "ruby-zip2"
```

Run `bundle update` and you should be good 🤞

**Comment by evschu** [comment]
I implemented the fix that @joshdholtz suggested and was able to build and upload an iOS app.

**Comment by ducnnguyen** [comment]
> @ducnnguyen Looks like we are currently waiting on [devunwired/apktools#26](https://github.com/devunwired/apktools/pull/26) (by @giginet) to be merged in 😊
> 
> You should be able to add 👇 to your `Gemfile` to fix this:
> 
> ```ruby
> gem "apktools", git: "https://github.com/giginet/apktools.git", branch: "ruby-zip2"
> ```
> 
> Run `bundle update` and you should be good 🤞

Thank you @joshdholtz. With your suggestion, now i can submit app to AppStore or upload ipa file to s3 successfully.

**Comment by zachawilson** [comment]
It appears that the dependencies were updated in apktools as requested in this commit: https://github.com/devunwired/apktools/commit/ad53af91ec625d66f5b353c7c18d8034df33bc2e

Included in https://github.com/devunwired/apktools/releases/tag/0.7.4
