### ISSUE TITLE
There is no resource of type 'appStoreReviewDetails' with id 'null'

### ISSUE THREAD

**Issue by ronpelayo** [fastlane/fastlane#16761]
### New Release Candidate Issue Checklist

- [X] Updated fastlane to the latest release candidate version (2.150.0.rcX)
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Information

- Breaking version: [e.g. `2.150.1.rc4`]
- Last working version: [e.g. `2.150.1.rc4`]

### Issue Description

Trying to upload metadata using spaceship command **fetch_app_store_review_detail** but it suddenly stop working.

Here's the code i used to fetch appstore review detail
`
Spaceship::ConnectAPI::App.all.collect do |app|

version = app.get_edit_app_store_version(platform: "IOS")

review_detail = version.fetch_app_store_review_detail`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre></pre>
</details>

### Spaceship Logs

<details>
  <pre>Traceback (most recent call last):
	6: from irb.rb:6:in `<main>'
	5: from irb.rb:6:in `collect'
	4: from irb.rb:48:in `block in <main>'
	3: from /Users/user/.gems/gems/fastlane-2.150.3/spaceship/lib/spaceship/connect_api/models/app_store_version.rb:126:in `fetch_app_store_review_detail'
	2: from /Users/user/.gems/gems/fastlane-2.150.3/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:579:in `get_app_store_review_detail'
	1: from /Users/user/.gems/gems/fastlane-2.150.3/spaceship/lib/spaceship/connect_api/client.rb:89:in `get'
/Users/user/.gems/gems/fastlane-2.150.3/spaceship/lib/spaceship/connect_api/client.rb:164:in `handle_response': The specified resource does not exist - There is no resource of type 'appStoreReviewDetails' with id 'null' (Spaceship::UnexpectedResponse)
</pre>
</details>

### Environment

<details>
  <pre><details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.5                                     |
| Ruby                        | 2.6.5                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.gems/bin/fastlane                        |
| Host                        | Mac OS X 10.15.5 (19F96)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.6.5/lib            |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.5                                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.150.3 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.14.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.72.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.7        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.10.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.0        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.336.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.1        |
| aws-sdk-core              | 3.102.1      |
| aws-sdk-kms               | 1.35.0       |
| aws-sdk-s3                | 1.72.0       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-07-06**
</details></pre>
</details>

### Mentioning

cc: @joshdholtz

**Comment by joshdholtz** [comment]
@ronpelayo Hey! So the API throws an error when you try to fetch the the `appStoreReviewDetails` if it doesn't exist. We do something like 👇 inside of `deliver` to either fetch or create/update.

https://github.com/fastlane/fastlane/blob/master/deliver/lib/deliver/upload_metadata.rb#L550-L561

```rb
      UI.message("Uploading app review information to App Store Connect")
      app_store_review_detail = begin
                                  version.fetch_app_store_review_detail
                                rescue => error
                                  UI.error("Error fetching app store review detail - #{error.message}")
                                  nil
                                end # errors if doesn't exist
      if app_store_review_detail
        app_store_review_detail.update(attributes: attributes)
      else
        version.create_app_store_review_detail(attributes: attributes)
      end
```

This behavior is somewhat new/different compared to the legacy API we migrated from so still workin on how to best handle these kinds of errors for our users that use `Spaceship::ConnectAPI` directly 😇 I don't want to completely hide the errors coming from the App Store Connect API by just returning `nil`. But this error is also a bit unintuitive to handle as is 😬

**Comment by ronpelayo** [comment]
it's working now I've change
`Spaceship::ConnectAPI.get_app(app_id: id).first` to `Spaceship::ConnectAPI::App.get(app_id: id)`

Thanks to the link you gave Josh.

Will close this now.

**Comment by ronpelayo** [comment]
Oh no I've tried it in another apple account and I did get the same issue but after I've added the age rating manually and rerun the script it worked.

**Comment by joshdholtz** [comment]
@ronpelayo The `appStoreReviewDetail` isn't always there 😔 In you that logic I posted above you can see that...
1. We try to fetch it but then rescue the error and return nil
2a. If not nil, we update
2b. If nil, we create

We could probably add some better logic into  `fetch_app_store_review_detail` to return `nil (and not raise an error) if `The specified resource does not exist` is returned from the API 🤔

**Comment by ronpelayo** [comment]
Yeah I've replaced my code with your code and it's working now if I run it the 2nd time. I will close it now. Thanks @joshdholtz  cheers!.
