### ISSUE TITLE
Deliver errors when password contains a dollar sign $

### ISSUE THREAD

**Issue by richard1505** [fastlane/fastlane#16777]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I found 2 issues when a password contains a dollar sign $.
1. When the password starts with a dollar sign, Deliver get's stuck. It keeps running and never ends. 
2. When the password contains a dollar sign, Deliver will say that the credentials are incorrect.

I'm pretty sure that it used to work before Apple changed their API's, but I'm not 100% sure.

I've tried by escaping the character, but no luck
I've also tried to run the iTMSTransporter directly by using
`xcrun iTMSTransporter -m upload -u username@email.com -p $mypassword -f /tmp/123456789.itmsp -t DAV,Signiant -k 100000 2>&1`
which works without any problems, so it seems to be something in Deliver.

##### Complete output when running fastlane, including the stack trace and command used
**Case 1**
fastlane fastlane-credentials remove --username username@email.com
export FASTLANE_PASSWORD="$mypassword"
fastlane deliver --ipa 'app.ipa' --force --automatic-release --skip_screenshots --skip_metadata -u username@email.com --verbose

It asks to fill in my password here, so I do so by typing: $mypassword

After the below output, nothing happens anymore and I have to kill the process

<details>
<pre>
[⠴] 🚀 /Users/username/.rvm/gems/ruby-2.7.0-preview1/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:14: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
[✔] 🚀 
[11:22:00]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
INFO [2020-07-07 11:22:01.91]: Login to App Store Connect (username@email.com)
/Users/username/.rvm/gems/ruby-2.7.0-preview1/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:14: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/Users/username/.rvm/gems/ruby-2.7.0-preview1/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:14: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
Reading keychain entry, because either user or password were empty
-------------------------------------------------------------------------------------
Please provide your Apple Developer Program account credentials
The login information you enter will be stored in your macOS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` environment variable
See more information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
-------------------------------------------------------------------------------------
Password (for username@email.com): *********
Looking for App Store Connect Team with ID ********
INFO [2020-07-07 11:23:39.59]: Login successful

+--------------------------------------+-------------------------------------------------+
|                                deliver 2.150.3 Summary                                 |
+--------------------------------------+-------------------------------------------------+
| ipa                                  | app.ipa |
| force                                | true                                            |
| automatic_release                    | true                                            |
| skip_screenshots                     | true                                            |
| skip_metadata                        | true                                            |
| username                             | username@email.com                        |
| app_identifier                       |                               |
| screenshots_path                     | ./screenshots                                   |
| metadata_path                        | ./metadata                                      |
| app_version                          | 8.3.0                                           |
| platform                             | ios                                             |
| edit_live                            | false                                           |
| use_live_version                     | false                                           |
| skip_binary_upload                   | false                                           |
| skip_app_version_update              | false                                           |
| overwrite_screenshots                | false                                           |
| submit_for_review                    | false                                           |
| reject_if_possible                   | false                                           |
| phased_release                       | false                                           |
| reset_ratings                        | false                                           |
| run_precheck_before_submit           | true                                            |
| precheck_default_rule_level          | warn                                            |
| individual_metadata_items            | []                                              |
| ignore_language_directory_validation | false                                           |
| precheck_include_in_app_purchases    | true                                            |
+--------------------------------------+-------------------------------------------------+

INFO [2020-07-07 11:23:40.21]: Making sure the latest version on App Store Connect matches '8.3.0'...
INFO [2020-07-07 11:23:41.43]: '8.3.0' is the latest version on App Store Connect
INFO [2020-07-07 11:23:42.38]: Uploading binary to App Store Connect
INFO [2020-07-07 11:23:42.75]: Wrote XML data to '/tmp/123456789.itmsp'
INFO [2020-07-07 11:23:42.81]: Going to upload updated app to App Store Connect
INFO [2020-07-07 11:23:42.81]: This might take a few minutes. Please don't interrupt the script.
DEBUG [2020-07-07 11:23:42.81]: xcrun iTMSTransporter -m upload -u username@email.com -p YourPassword -f /tmp/123456789.itmsp -t DAV,Signiant -k 100000 2>&1
DEBUG [2020-07-07 11:23:48.31]: [Transporter]: INFO: Configuring logging...
DEBUG [2020-07-07 11:23:48.32]: [Transporter]: INFO: Logging level set to eXtreme
DEBUG [2020-07-07 11:23:48.32]: [Transporter]: INFO: Transporter is searching for new software components.
DEBUG [2020-07-07 11:23:48.32]: [Transporter]: INFO: INFO: using cached repository.xml file.
DEBUG [2020-07-07 11:23:48.50]: [Transporter]: INFO: Update check complete.
DEBUG [2020-07-07 11:23:49.64]: [Transporter]: DEBUG: Attempting refresh of configuration data from https://contentdelivery.itunes.apple.com/transporter/Defaults.properties
DEBUG [2020-07-07 11:23:50.11]: [Transporter]: DEBUG: Configuration refresh successful.
DEBUG [2020-07-07 11:23:50.11]: [Transporter]: DEBUG: Saving configuration to local path: /Users/username/Library/Caches/com.apple.amp.itmstransporter/Defaults.properties

GETS STUCK HERE, NOTHING HAPPENS ANYMORE
</pre>
</details>

**Case 2**
fastlane fastlane-credentials remove --username username@email.com
export FASTLANE_PASSWORD="my$password"
fastlane deliver --ipa 'app.ipa' --force --automatic-release --skip_screenshots --skip_metadata -u username@email.com --verbose

<details>
<pre>
[⠼] 🚀 /Users/username/.rvm/gems/ruby-2.7.0-preview1/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:14: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
[✔] 🚀 
[11:09:32]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
INFO [2020-07-07 11:09:33.61]: Login to App Store Connect (username@email.com)
/Users/username/.rvm/gems/ruby-2.7.0-preview1/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:14: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/Users/username/.rvm/gems/ruby-2.7.0-preview1/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:14: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
Reading keychain entry, because either user or password were empty
The login credentials for 'username@email.com' seem to be wrong
The password was taken from the environment variable
Please make sure it is correct

Run `fastlane env` to append the fastlane environment to your issue
Traceback (most recent call last):
	26: from /Users/username/.rvm/gems/ruby-2.7.0-preview1/bin/ruby_executable_hooks:24:in `<main>'
	25: from /Users/username/.rvm/gems/ruby-2.7.0-preview1/bin/ruby_executable_hooks:24:in `eval'
	24: from /Users/username/.rvm/gems/ruby-2.7.0-preview1/bin/fastlane:23:in `<main>'
	23: from /Users/username/.rvm/gems/ruby-2.7.0-preview1/bin/fastlane:23:in `load'
	22: from /Users/username/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/bin/fastlane:23:in `<top (required)>'
	21: from /Users/username/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	20: from /Users/username/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/deliver/lib/deliver/commands_generator.rb:17:in `start'
	19: from /Users/username/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/deliver/lib/deliver/commands_generator.rb:183:in `run'
	18: from /Users/username/.rvm/gems/ruby-2.7.0-preview1/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	17: from /Users/username/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	16: from /Users/username/.rvm/gems/ruby-2.7.0-preview1/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	15: from /Users/username/.rvm/gems/ruby-2.7.0-preview1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	14: from /Users/username/.rvm/gems/ruby-2.7.0-preview1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	13: from /Users/username/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/deliver/lib/deliver/commands_generator.rb:80:in `block (2 levels) in run'
	12: from /Users/username/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/deliver/lib/deliver/commands_generator.rb:80:in `new'
	11: from /Users/username/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/deliver/lib/deliver/runner.rb:22:in `initialize'
	10: from /Users/username/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/deliver/lib/deliver/runner.rb:30:in `login'
	 9: from /Users/username/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
	 8: from /Users/username/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/spaceship/lib/spaceship/client.rb:348:in `login'
	 7: from /Users/username/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/spaceship/lib/spaceship/client.rb:386:in `login'
	 6: from /Users/username/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/spaceship/lib/spaceship/client.rb:778:in `do_login'
	 5: from /Users/username/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/spaceship/lib/spaceship/tunes/tunes_client.rb:127:in `send_login_request'
	 4: from /Users/username/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/spaceship/lib/spaceship/client.rb:473:in `send_shared_login_request'
	 3: from /Users/username/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/spaceship/lib/spaceship/client.rb:696:in `request'
	 2: from /Users/username/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/spaceship/lib/spaceship/client.rb:852:in `send_request'
	 1: from /Users/username/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/spaceship/lib/spaceship/client.rb:627:in `with_retry'
/Users/username/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/spaceship/lib/spaceship/client.rb:860:in `block in send_request': Unauthorized Access (Spaceship::UnauthorizedAccessError)
	23: from /Users/username/.rvm/gems/ruby-2.7.0-preview1/bin/ruby_executable_hooks:24:in `<main>'
	22: from /Users/username/.rvm/gems/ruby-2.7.0-preview1/bin/ruby_executable_hooks:24:in `eval'
	21: from /Users/username/.rvm/gems/ruby-2.7.0-preview1/bin/fastlane:23:in `<main>'
	20: from /Users/username/.rvm/gems/ruby-2.7.0-preview1/bin/fastlane:23:in `load'
	19: from /Users/username/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/bin/fastlane:23:in `<top (required)>'
	18: from /Users/username/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	17: from /Users/username/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/deliver/lib/deliver/commands_generator.rb:17:in `start'
	16: from /Users/username/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/deliver/lib/deliver/commands_generator.rb:183:in `run'
	15: from /Users/username/.rvm/gems/ruby-2.7.0-preview1/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	14: from /Users/username/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	13: from /Users/username/.rvm/gems/ruby-2.7.0-preview1/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	12: from /Users/username/.rvm/gems/ruby-2.7.0-preview1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	11: from /Users/username/.rvm/gems/ruby-2.7.0-preview1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	10: from /Users/username/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/deliver/lib/deliver/commands_generator.rb:80:in `block (2 levels) in run'
	 9: from /Users/username/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/deliver/lib/deliver/commands_generator.rb:80:in `new'
	 8: from /Users/username/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/deliver/lib/deliver/runner.rb:22:in `initialize'
	 7: from /Users/username/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/deliver/lib/deliver/runner.rb:30:in `login'
	 6: from /Users/username/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
	 5: from /Users/username/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/spaceship/lib/spaceship/client.rb:348:in `login'
	 4: from /Users/username/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/spaceship/lib/spaceship/client.rb:386:in `login'
	 3: from /Users/username/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/spaceship/lib/spaceship/client.rb:778:in `do_login'
	 2: from /Users/username/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/spaceship/lib/spaceship/tunes/tunes_client.rb:127:in `send_login_request'
	 1: from /Users/username/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/spaceship/lib/spaceship/client.rb:453:in `send_shared_login_request'
/Users/username/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/spaceship/lib/spaceship/client.rb:483:in `rescue in send_shared_login_request': \e[31m[!] The request could not be completed because: (Spaceship::InvalidUserCredentialsError)
	Invalid username and password combination. Used 'username@email.com' as the username.\e[0m
</pre>
</details>

### Environment
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                        |
| --------------------------- | -------------------------------------------- |
| OS                          | 10.15.5                                      |
| Ruby                        | 2.7.0                                        |
| Bundler?                    | false                                        |
| Git                         | git version 2.24.3 (Apple Git-128)           |
| Installation Source         | ~/.rvm/gems/ruby-2.7.0-preview1/bin/fastlane |
| Host                        | Mac OS X 10.15.5 (19F101)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.7.0-preview1/lib        |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                  |
| Is contained                | false                                        |
| Is homebrew                 | false                                        |
| Is installed via Fabric.app | false                                        |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/  |
| Xcode Version               | 11.5                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.150.3 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 2.1.4        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.2.0        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.10.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.308.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.1.3        |
| aws-sdk-core              | 3.94.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.63.0       |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.15.0       |
| unicode-display_width     | 1.6.1        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| excon                     | 0.72.0       |
| mini_magick               | 4.10.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| digest-crc                | 0.4.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.25.1       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-07-07**
</details>

**Comment by choli** [comment]
Just wanted to report this issue. If you would have reported that yesterday, you would have saved me a lot of time. This must have to do with the Apple API, as this was changed for 2.150.0. We had not changed our password in forever.

**Comment by joshdholtz** [comment]
👋 I will look into this today!

**Comment by natep** [comment]
We are also seeing this issue. Looking at our CI server logs, I can see that it was working fine under Fastlane 2.149.1. Then the next day it used 2.150.1 and failed, and hasn't worked since.

**Comment by joshdholtz** [comment]
Yup yup, that makes sense ☝️ I'm close to a solution here and I'll have a release push out as soon as I can 💪

**Comment by joshdholtz** [comment]
Hey, all! Got a fix here 👉 https://github.com/fastlane/fastlane/pull/16795

I will try to get this out in a release later this evening.

**Comment by YufeiG** [comment]
Thanks for fixing this! We hit this too and it broke between rc3 and rc4 when fastlane switched to using the transporter.

**Comment by joshdholtz** [comment]
Yeaaaaahhhhhhhh... that was my bad 😇 I just assume everybody has a the standard `12345` as their password 🤷‍♂️

**Comment by joshdholtz** [comment]
Merged and will be released in a new version later tonight!

**Comment by matthiaskmt** [comment]
Thanks for fixing it. Works as expected now.

**Comment by richard1505** [comment]
Yes all working fine. Thanks a lot!

**Comment by tmaly1980** [comment]
@joshdholtz I'm still experiencing this issue. I don't have a dollar sign in my passwords. I'm looking through https://github.com/fastlane/fastlane/pull/16795/files and don't understand the fix, how it would impact the password at all. Thoughts?

**Comment by joshdholtz** [comment]
@tmaly1980 Special characters get escaped really weirdly when passing in shell and then even weirder when escape for a shell being executed from Ruby. The fix in the PR tells ITMSTransporter to look directly at an environment variable instead of `fastlane` passing one through arguments that require weird escape rules.

Would you be able to give me a example password that has similar characteristics of yours that is failing? You can email it to me at me@joshholtz.com if you'd like. 

I just want to make sure I'm testing all the edge cases that I can 😇

**Comment by tmaly1980** [comment]
It was actually my error. The password was wrong. I have it scripted and
the username/password stored in a config file, but the confusing part was
that the Spaceship session was working while iTMSTransporter was failing
with a wrong password. I think the password was changed at some point while
the spaceship session was still valid. I think I'm good.
