### ISSUE TITLE
Add background containerized builds, deployments, or tests

### ISSUE THREAD

**Issue by AustinFuller** [fastlane/fastlane#16780]
#### Motivation Behind Feature
As a developer who deploys to the App Store every other day, the pilot lane can wait on processing from Apple for an unreasonably long amount of time. During this time, I switch computers to ensure that I don't run two instances of xcbuild (one in fastlane and one in Xcode) causing the deployment to fail. It would be really cool if fastlane could containerize the current deployment so that my git directory could mutate without affecting the running fastlane build. This would allow for completing a change and starting a deployment while being able to start a new development task as the deployment runs on the same computer.

#### Feature Description
When starting a fastlane command, a flag of `--containerize ${path to empty folder to run in}` could be passed, then fastlane would copy all the assets of the current root folder that it is in into that empty folder, run the provided commands, and then delete everything the provided directory. The folder path provided would be a destination that the user doesn't have tracked by git thus allowing for changing git branches without messing with the deployment. 

Note: for the above, I have never used nor understand the use of the `/tmp/` directory. The path of the folder mentioned above could be in the `/tmp/` folder. 
 
Drawbacks:
The main drawback would be the needed copy time from the existing directory to the destination directory. For my main project, it is about 950 mbs. On a fast machine, this only takes about 10 seconds, but on a standard hard drive, it could take minutes. 

The other drawback is that it would may break relative paths that reference things outside the root directory.

Breaking Change?:
This would be an additive change. Though, some may need extra work to support the change depending on dependencies. 

#### Alternatives or Workarounds
Workaround: I normally use two computers when I need to deploy. 
There aren't any existing actions or plugins that work in this case that I know of. 

Note: If a workaround exists for my use case, I'd love to use it. Thanks!

**Comment by AustinFuller** [comment]
I know things are crazy right now with v2.150.0 so skip over this for a while! 

I know I don't have a perfect handle on how fastlane works under the hood and understand if something like this isn't possible. 

Thanks!

**Comment by AustinFuller** [comment]
Bumping to keep open. I'm not certain I'm sharp enough to implement (especially in Ruby), but I think this would be really cool.

**Comment by AustinFuller** [comment]
fastlane-bot and I are battling. Let's see who wins.

**Comment by Goodwin7788** [comment]
Thanks for the information keep suggesting such informativw post would like to see some more post like this keep suggesting 
with us [how to download facetime on windows ](https://www.facetimeapp.net/facetime-for-pc/)

**Comment by rogerluan** [comment]
Hey @AustinFuller 👋 

Interesting request :) Personally, when I used to upload the build from my machine, I used to have 2 repo directories. When I needed to deploy, I'd `cd` to the secondary one and run _fastlane_ from there. Then I can `cd` to the primary repository and use it normally meanwhile (xcodebuild doesn't seem to conflict at all with this setup). The only limitation I think there is, is that you can't run 2 instances of fastlane simultaneously. But Xcode works just fine in the primary directory while the secondary one is building/deploying 😊 

But for a long time now, we've moved our deploys to CI so it doesn't have to be done in someone's machine 😉 

Let me know if that solves your problem. I know it's a dirty workaround, but with the current priorities, it doesn't look like this feature would be implemented any time soon, and I'm looking forward to solve your specific use case first 🤗

**Comment by AustinFuller** [comment]
@rogerluan This is a dope idea and I'm a bit embarrassed that I didn't think of it on my own. 

Related to deploying in CI, 🚀. I successfully set that up for a while and then my company switched from TravisCI to GitHub Actions. I hadn't had a chance to finish getting it set back up. 

Thanks for the reply! I can let @fastlane-bot win this battle now.

**Comment by rogerluan** [comment]
Sweet @AustinFuller , glad we could resolve your problem with minimum engineering efforts 😁 I love when solutions end up being simpler than expected 😊 

I'll close this issue before @fastlane-bot annoys us again 😉
