### ISSUE TITLE
Error when uploading ipa: iTMSTransporter  eval: line 253: unexpected EOF while looking for matching ``

### ISSUE THREAD

**Issue by thetruth4u** [fastlane/fastlane#16789]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Failed at `upload_to_testflight` action , it has been working fine but suddently stoped working 2 days ago

##### Command executed
I have a fastfile and has a lane for uploading ipa:
```
 $pilot_retry=0
lane :do_pilot do
       begin
        if $pilot_retry > 0 
            puts "Retrying upload ipa"
        end	
        upload_to_testflight(skip_waiting_for_build_processing:true)
       rescue => ex
            $pilot_retry +=1
            if $pilot_retry <= 3
                 do_pilot
           else 
               raise ex
           end
      end
 end
```

##### Complete output when running fastlane, including the stack trace and command used

```
[11:25:24]: Going to upload updated app to App Store Connect 
[11:25:24]: [32mThis might take a few minutes. Please don't interrupt the script.
[11:25:25]:  [33m[iTMSTransporter] /Applications/Xcode.app/Contents/Developer/usr/bin/iTMSTransporter: eval: line 253: unexpected EOF while looking for matching ``'
[11:25:25]: [33m[iTMSTransporter] /Applications/Xcode.app/Contents/Developer/usr/bin/iTMSTransporter: eval: line 254: syntax error: unexpected end of file
[11:25:25]: iTunes Transporter output above ^
[11:25:25]: [31mThe call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
```

### Environment

<details>
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.5                                     |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.21.0 (Apple Git-122.2)        |
| Installation Source         | /usr/local/lib/ruby/gems/2.6.0/bin/fastlane |
| Host                        | Mac OS X 10.14.5 (18F132)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.6.3/lib            |
| OpenSSL Version             | OpenSSL 1.0.2r  26 Feb 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.2.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do

    begin
            # Check if re-upload ipa
            if ENV["REUPLOAD"] == "1"
                reup
                next
            end

            # Check change logs
            changelog = changelog_from_git_commits(
                between: [ENV['GIT_PREVIOUS_SUCCESSFUL_COMMIT'], ENV['GIT_COMMIT']],
                pretty: "- (%h) [%aN] %s" 
            )
            changelog = "" if changelog.to_s.length == 0

            if ENV["BUILD_IF_CHANGE"] == "1" && changelog == ""
                puts "No new commits - stop building"
                next          
            end

            # Get latest version
            get_version_number(
                target:ENV["TARGET"]
            )

            # Increase build number
            increment_build_number(
                build_number: latest_testflight_build_number(app_identifier:ENV["APP_IDENTIFIER"]) + 1
            )

            # Run `pod install`
            cocoapods(try_repo_update_on_error: true, use_bundle_exec: true)

            # Notify slack
            # notify(changelog, "Building started ...", true)

            puts "remove FL_CHANGELOG"
            lane_context[SharedValues::FL_CHANGELOG] = nil
            puts lane_context[SharedValues::FL_CHANGELOG]


            # Update team target
            update_project_team(
                targets:[ENV["TARGET"]],
                path: ENV["PROJECT_FILE"],
                teamid: ENV["GYM_EXPORT_TEAM_ID"]
            )

            update_code_signing_settings(use_automatic_signing: true)

            build_app(
                clean: true,
                export_method: "app-store",
                xcargs: "-allowProvisioningUpdates"
            )

            # notify("Building done, started uploading to TF ...", true)
            do_pilot

            notify(changelog, "App Successfully uploaded to iTunesConnect", true)
            # notify("App Successfully uploaded to iTunesConnect", true)

    rescue => exception
            message = "Lane failed with exception : #{exception}"
            notify("", message, false)

            # Mark this is failed 	
	        puts "Make jenkins failed"
	        jenkins_is_failed	
    end
  end

  
 $pilot_retry=0
 lane :do_pilot do
       begin
        if $pilot_retry > 0 
            puts "Retrying upload ipa"
        end	
        upload_to_testflight(skip_waiting_for_build_processing:true)
       rescue => ex
            $pilot_retry +=1
            if $pilot_retry <= 3
                 do_pilot
           else 
               raise ex
           end
      end
 end


 lane :reup do
   begin
           puts "Re-uploading ipa to TF ..."
           do_pilot

           notify("", "[Reup] App Successfully uploaded to iTunesConnect", true)
     rescue => exception
           message = "Re-upload failed with exception : #{exception}"
           notify("", message, false)
           # Mark this is failed 	
	       puts "Make jenkins failed"
	       jenkins_is_failed
   end
 end

 lane :jenkins_success do
    puts "Just to make a jenkins job success"
 end

end

def notify(changelog, message, success)

    fields = []

    versionNumber = lane_context[SharedValues::VERSION_NUMBER] || ""
    if versionNumber != "" 
        fields.push({
            title: "Build version",
            value: versionNumber,
            short: true
        })
    end

    buildNumber = lane_context[SharedValues::BUILD_NUMBER] || ""
    if buildNumber != "" 
        fields.push({
            title: "Build number",
            value: buildNumber,
            short: true
        })
    end

    if changelog != ""
        fields.push({
            title: "Changes",
            value: changelog
        })
    end
    
    slack(
        message: "#{ENV["APP_NAME"]}: #{message}",
        success: success,
        slack_url: ENV["SLACK_URL"],
        default_payloads: [],
        attachment_properties: {
            fields: fields
        }
    )   
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile
# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

app_identifier(ENV["APP_IDENTIFIER"]) # The bundle identifier of your app
apple_id(ENV["APPLE_ID"]) # Your Apple email address
team_id(ENV["GYM_EXPORT_TEAM_ID"]) # Developer Portal Team ID
itc_team_id(ENV["ITC_TEAM_NAME"]) 

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.151.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 2.1.4        |
| rake                      | 13.0.1       |
| CFPropertyList            | 3.0.2        |
| concurrent-ruby           | 1.1.6        |
| i18n                      | 0.9.5        |
| minitest                  | 5.14.1       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.7        |
| activesupport             | 4.2.11.3     |
| public_suffix             | 4.0.5        |
| addressable               | 2.7.0        |
| httpclient                | 2.8.3        |
| json                      | 2.3.1        |
| algoliasearch             | 1.27.3       |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.339.0      |
| aws-sigv4                 | 1.2.1        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.103.0      |
| aws-sdk-kms               | 1.36.0       |
| aws-sdk-s3                | 1.73.0       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| netrc                     | 0.11.0       |
| ffi                       | 1.13.1       |
| ethon                     | 0.12.0       |
| typhoeus                  | 1.4.0        |
| cocoapods-core            | 1.9.3        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.3.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| cocoapods-trunk           | 1.5.0        |
| cocoapods-try             | 1.2.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.17.0       |
| cocoapods                 | 1.9.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 3.0.0        |
| excon                     | 0.75.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 1.0.1        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| jwt                       | 2.2.1        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.1.0        |
| signet                    | 0.14.0       |
| googleauth                | 0.13.0       |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.2        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.2       |
| mini_magick               | 4.10.1       |
| plist                     | 3.5.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>
</details>

**Comment by ksingh0590** [comment]
Have the same issue. 

The only difference we have noticed is fastlane being updated from 2.149.1  to 2.151.1 in our release pipeline

**Comment by kbarnett7** [comment]
Our team has experienced this same exact error in our Azure DevOps release pipeline using the [Apple App Store extension task](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.app-store). 

**Logs (scrubbed of sensitive info)**
```
2020-07-08T20:54:00.8029630Z Successfully installed fastlane-2.151.1
2020-07-08T20:54:00.8030800Z Parsing documentation for fastlane-2.151.1
2020-07-08T20:54:00.8031660Z Installing ri documentation for fastlane-2.151.1
2020-07-08T20:54:00.8032050Z Done installing documentation for fastlane after 22 seconds
2020-07-08T20:54:00.8032440Z 1 gem installed
2020-07-08T20:54:00.8354970Z [command]/usr/local/opt/ruby/bin/gem update fastlane -i /Users/runner/.gem-cache
2020-07-08T20:54:03.6918990Z Updating installed gems
2020-07-08T20:54:03.6919390Z Nothing to update
2020-07-08T20:54:03.7204240Z [command]fastlane pilot upload -u *** -i /Users/runner/work/r1/a/ourApp.ipa -q 000000 -r Our Team Name -a com.ourapp --skip_waiting_for_build_processing true
2020-07-08T20:54:09.0118360Z [20:54:09]: [33mSeems like launching fastlane takes a while - please run[0m
2020-07-08T20:54:09.0119590Z [20:54:09]: 
2020-07-08T20:54:09.0120280Z [20:54:09]: [36m$ [sudo] gem cleanup[0m
2020-07-08T20:54:09.0120530Z [20:54:09]: 
2020-07-08T20:54:09.0121260Z [20:54:09]: [33mto uninstall outdated gems and make fastlane launch faster[0m
2020-07-08T20:54:09.0122110Z [20:54:09]: [33mAlternatively it's recommended to start using a Gemfile to lock your dependencies[0m
2020-07-08T20:54:09.0123080Z [20:54:09]: [33mTo get started with a Gemfile, run[0m
2020-07-08T20:54:09.0123360Z [20:54:09]: 
2020-07-08T20:54:09.0123980Z [20:54:09]: [36m$ bundle init[0m
2020-07-08T20:54:09.0124670Z [20:54:09]: [36m$ echo 'gem "fastlane"' >> Gemfile[0m
2020-07-08T20:54:09.0125330Z [20:54:09]: [36m$ bundle install[0m
2020-07-08T20:54:09.0125580Z [20:54:09]: 
2020-07-08T20:54:09.0126310Z [20:54:09]: [33mAfter creating the Gemfile and Gemfile.lock, commit those files into version control[0m
2020-07-08T20:54:09.0127340Z [20:54:09]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
2020-07-08T20:54:18.1458230Z [20:54:18]: Sending anonymous analytics information
2020-07-08T20:54:18.1458750Z [20:54:18]: Learn more at https://docs.fastlane.tools/#metrics
2020-07-08T20:54:18.1459170Z [20:54:18]: No personal or sensitive data is sent.
2020-07-08T20:54:18.1459550Z [20:54:18]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
2020-07-08T20:54:18.1633440Z [20:54:18]: Login to App Store Connect (***)
2020-07-08T20:54:19.3448610Z [20:54:19]: Login successful
2020-07-08T20:54:21.3818930Z [20:54:21]: Ready to upload new build to TestFlight (App: 0000000000)...
2020-07-08T20:54:21.5714540Z [20:54:21]: Going to upload updated app to App Store Connect
2020-07-08T20:54:21.5715920Z [20:54:21]: This might take a few minutes. Please don't interrupt the script.
2020-07-08T20:54:25.3940190Z [20:54:25]: [iTMSTransporter] /Applications/Xcode_11.5.app/Contents/Developer/usr/bin/iTMSTransporter: eval: line 253: unexpected EOF while looking for matching ``'
2020-07-08T20:54:25.3940900Z 
2020-07-08T20:54:25.3941360Z [20:54:25]: [iTMSTransporter] /Applications/Xcode_11.5.app/Contents/Developer/usr/bin/iTMSTransporter: eval: line 254: syntax error: unexpected end of file
2020-07-08T20:54:25.3941800Z 
2020-07-08T20:54:25.3942020Z [20:54:25]: iTunes Transporter output above ^
2020-07-08T20:54:25.3942930Z [20:54:25]: The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
2020-07-08T20:54:25.4159740Z 
2020-07-08T20:54:25.4160530Z [!] Error uploading ipa file, for more information see above
2020-07-08T20:54:25.4418450Z ##[error]Error: fastlane failed with return code: 1
```

**Comment by thetruth4u** [comment]
@ksingh0590 May downgrade fastlane version fix this issue?  Weird thing is that I have two projects but just one got this issue the other is working normally.

**Comment by thetruth4u** [comment]
FYI I downgraded to 2.149.1 and it's working fine now

**Comment by kbarnett7** [comment]
Version **2.151.2** seems to have fixed the issue. We were able to successfully publish the .ipa file to TestFlight.
