### ISSUE TITLE
Unable to upload screenshots due to Un-supported locale: iMessage

### ISSUE THREAD

**Issue by changusmc** [fastlane/fastlane#16781]
### New Release Candidate Issue Checklist

- [x] Updated fastlane to the latest release candidate version (2.150.0.rcX)
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Information

- Breaking version: [e.g. `2.x.x`] 2.1.50.x
- Last working version: [e.g. `2.x.x`] 2.1.49.x
- State of app: [e.g. `Prepare for Submission`, `Developer Rejected`] Released
- First version of app?: [e.g. `Yes`] No

### Issue Description

We have an iMessage extension app and I used 2.1.50.3 to download screenshots with deliver.

Getting this error.

```Jul  7 16:31:43.716: DEBUG [09:31:38]: << POST appStoreVersionLocalizations: 409 {"errors"=>[{"id"=>"45daf101-4e14-469d-a3db-055bb79485da", "status"=>"409", "code"=>"ENTITY_ERROR.ATTRIBUTE.INVALID", "title"=>"An attribute value is invalid.", "detail"=>"Un-supported locale: iMessage", "source"=>{"pointer"=>"/data/attributes/locale"}}, {"id"=>"fdd5dca6-20da-4c71-8d51-b6fbc3cbe38b", "status"=>"409", "code"=>"ENTITY_ERROR.ATTRIBUTE.INVALID", "title"=>"An attribute value is invalid.", "detail"=>"The language specified is not listed for localization", "source"=>{"pointer"=>"/data/attributes/locale"}}]}```

## Screenshots dir structure:
```
changd-mbp:screenshots changd$ tree -d
.
├── da
├── de-DE
├── en-US
├── es-ES
├── es-MX
├── fr-FR
├── iMessage
│   ├── da
│   ├── de-DE
│   ├── en-US
│   ├── es-ES
│   ├── es-MX
│   ├── fr-FR
│   ├── id
│   ├── it
│   ├── ja
│   ├── ko
│   ├── ms
│   ├── nl-NL
│   ├── no
│   ├── pl
│   ├── pt-BR
│   ├── ru
│   ├── sv
│   ├── th
│   ├── uk
│   ├── zh-Hans
│   └── zh-Hant
├── id
├── it
├── ja
├── ko
├── ms
├── nl-NL
├── no
├── pl
├── pt-BR
├── ru
├── sv
├── th
├── uk
├── zh-Hans
└── zh-Hant

43 directories
```

##### Complete output when running fastlane, including the stack trace and command used
I can provide full logs in email, if needed.

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Spaceship Logs

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Mentioning

cc: @joshdholtz

**Comment by joshdholtz** [comment]
@changusmc This PR _may_ fix your issue 👉  https://github.com/fastlane/fastlane/pull/16752

If you could test out the `master` branch to see if that works for you that would be 💯

**Comment by changusmc** [comment]
Adding this to my Gemfile. Can you confirm this looks right?

```gem 'fastlane', :git => "git://github.com/fastlane/fastlane.git", :branch => "master"
```

**Comment by changusmc** [comment]
Looks like it was right.

`Using fastlane 2.150.3 (was 2.150.1) from git://github.com/fastlane/fastlane.git (at master@f18ef00)`

**Comment by joshdholtz** [comment]
@changusmc Yup yup, that's right! Sorry for slow response 😇

**Comment by changusmc** [comment]
Got the same error, sent you the logs in email.

**Comment by joshdholtz** [comment]
Thanks for trying! I will take a look 😊

**Comment by joshdholtz** [comment]
@changusmc Hey! I’ve been wracking my brain against this one and I can’t figure out how this happened 😔 

https://github.com/fastlane/fastlane/blob/bbc26e716010e48871e692436a4e2b22e259cc01/deliver/lib/deliver/upload_screenshots.rb#L98-L101

☝️ This should be jumping into the `iMessage` and `appleTV` directory instead of adding “iMessage” as a locale 🤔 Do you happen to have 

<hr/>

Mine looks like this which looks pretty similar to what your directory structure looks like👇 
```sh

[19:57:31]: Uploading './fastlane/screenshots/en-US/1_APP_IPHONE_55_1.png'...
[19:57:33]: Uploading './fastlane/screenshots/en-US/1_APP_IPHONE_65_1.png'...
[19:57:34]: Uploading './fastlane/screenshots/en-US/1_APP_WATCH_SERIES_4_1.png'...
[19:57:36]: Uploading './fastlane/screenshots/en-US/2_APP_IPAD_PRO_129_2.png'...
[19:57:38]: Uploading './fastlane/screenshots/en-US/2_APP_IPHONE_55_2.png'...
[19:57:40]: Uploading './fastlane/screenshots/en-US/2_APP_IPHONE_65_2.png'...
[19:57:41]: Uploading './fastlane/screenshots/en-US/3_APP_IPAD_PRO_129_3.png'...
[19:57:43]: Uploading './fastlane/screenshots/en-US/4_APP_IPAD_PRO_129_4.png'...
[19:57:45]: Uploading './fastlane/screenshots/en-US/5_APP_IPAD_PRO_129_5.png'...
[19:57:47]: Uploading './fastlane/screenshots/iMessage/en-US/0_IMESSAGE_APP_IPHONE_65_0.png'...
[19:57:49]: Successfully uploaded screenshots to App Store Connect
```

❓ Can you paste or email me your fastlane console output? I’m curious what the start of your run looks like and what languages its detecting. I’d also like to see that “deliver summary” that is in the logs.

Thanks!

**Comment by fatihyildizhan** [comment]
@changusmc How did you take ss for these languages. Can you please share the configuration?
I am unable to change iPhone language for some languages.

Issue: #16625

**Comment by changusmc** [comment]
@fatihyildizhan These sceenshots are taken by a 3rd party for us. I'm unsure what they do.

**Comment by joshdholtz** [comment]
@fatihyildizhan I just commented on your issue! Sorry about missing it 😔 I will update the supported languages in fastlane

@changusmc I think this issue can be closed now, right? 😊

**Comment by changusmc** [comment]
Yup can be closed. For posterity, I fixed this by splitting up the metadata and screenshots into separate directories.
