### ISSUE TITLE
Unable to upload build to test flight if app state is "Pending Developer Release"

### ISSUE THREAD

**Issue by ndillon1** [fastlane/fastlane#16785]
### New Release Candidate Issue Checklist

- [x] Updated fastlane to the latest release candidate version (2.150.0.rcX)
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Information

- Breaking version: `2.150.3`
- Last working version: `2.150.rc4
- State of app: Pending Developer Release
- First version of app?: No

### Issue Description
* Unable to upload a build if the app state is in prepare for submission

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>21:59:58]: fastlane finished with errors
Looking for related GitHub issues on fastlane/fastlane...
➡️  fastlane deliver: Potential server error received: 'Unexpected Error'
    https://github.com/fastlane/fastlane/issues/16621 [open] 120 💬
    a week ago
➡️  Having deliver/upload_to_app_store issues? Install 2.150.0.rc5
    https://github.com/fastlane/fastlane/issues/16639 [closed] 116 💬
    a day ago
➡️  [deliver][produce][spaceship] Update to use new App Store Connect API endpoints
    https://github.com/fastlane/fastlane/pull/16626 [closed] 138 💬
    14 hours ago
and 1 more at: https://github.com/fastlane/fastlane/search?q=The%20provided%20entity%20includes%20a%20relationship%20with%20an%20invalid%20value%20-%20You%20cannot%20create%20a%20new%20version%20of%20the%20App%20in%20the%20current%20state.&type=Issues&utf8=✓
🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/Users/vagrant/.rbenv/versions/2.6.3/bin/fastlane)
Spaceship::UnexpectedResponse: [!] The provided entity includes a relationship with an invalid value - You cannot create a new version of the App in the current state.
  /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.150.3/spaceship/lib/spaceship/connect_api/client.rb:164:in `handle_response'
  /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.150.3/spaceship/lib/spaceship/connect_api/client.rb:100:in `post'
  /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.150.3/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:721:in `post_app_store_version'
  /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.150.3/spaceship/lib/spaceship/connect_api/models/app.rb:149:in `ensure_version!'
  /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.150.3/deliver/lib/deliver/runner.rb:99:in `verify_version'
  /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.150.3/deliver/lib/deliver/runner.rb:36:in `run'
  /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.150.3/fastlane/lib/fastlane/actions/upload_to_app_store.rb:17:in `run'
  /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.150.3/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
  /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.150.3/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.150.3/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
  /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.150.3/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.150.3/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.150.3/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.150.3/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:85:in `block (2 levels) in parsing_binding'
  /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.150.3/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.150.3/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.150.3/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.150.3/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.150.3/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.150.3/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.150.3/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.150.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.150.3/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.150.3/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.150.3/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Users/vagrant/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.150.3/bin/fastlane:23:in `<top (required)>'
  /Users/vagrant/.rbenv/versions/2.6.3/bin/fastlane:23:in `load'
  /Users/vagrant/.rbenv/versions/2.6.3/bin/fastlane:23:in `<top (required)>'
Fastlane command: (bundle "_2.0.2_" "exec" "fastlane" "release") failed</pre>
</details>

**Comment by joshdholtz** [comment]
@ndillon1 👋 Hey! So I _thhhiiinnnnkkk_ I see where this is coming from... but I think I need to ask a few questions first 😊 

1) Are you uploading a different/newer version of your app? Or are you uploading same version that is pending for developer release?
2) Are you trying to **only** upload a binary? Or are you trying to do other metadata or screenshots too?

Thanks! ❤️

**Comment by ndillon1** [comment]
Hey! 
1. I'm uploading a newer version of the app i.e current version pending for release is v2.5.0 and I'm attempting to upload version 3.0.0. 
2. Binary without any metadata

**Comment by joshdholtz** [comment]
@ndillon1 Thanks for the quick response!

So deliver tries to ensure that that it can create a new version in App Store Connect that matches the version of your binary you are sending up. It _looks like_ that a new version can't be create if the app is in a "Pending Developer Release" style. That can be seen in that error message you got which comes directly from Apple.

You can bypass this now by setting `skip_app_version_update: true `.

I'm not sure if this is something we should override if the app is in "Pending Developer Release" if the user doesn't explicitly set it 🤔 

Thoughts?

**Comment by ndillon1** [comment]
I think it's best to not include overriding behaviour here as I suspect it may end up being a breaking change for those where the current flow works as expected. It's just not working when we  `skip_app_version_update` is set to `false` when I want the behaviour to act as if it were set to `true`. 

But happy for another opinion if someone else thinks a change needs to be made here.
