### ISSUE TITLE
Problems of the Ruby Version

### ISSUE THREAD

**Issue by 360fengdai** [fastlane/fastlane#16790]
### Issue Description

`fastlane/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh`line25-44

**I installed rvm ,had use rvm mannage ruby , why the code run `rvm use system`,system ruby no gem no fastlane no everything, can it run success? Is it your unnecessary and useless consideration?**

I comment out the code, everything is ok.

line25-44 code:
```
which rvm > /dev/null
if [[ $? -eq 0 ]]; then
  echo "RVM detected, forcing to use system ruby"
  [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
  rvm use system
fi

if which rbenv > /dev/null; then
  echo "rbenv detected, removing env variables"
  rbenv shell system
fi
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>

</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by DeathStalker403** [comment]
Hey, "system ruby no gem no fastlane no everything"
I think If you use the correct fastlane installation it wont redirect to system ruby. Go to the correct gem installation of fastlane and initate from there once . If it solves your problem put its location as system variable(symlink to usr/local/bin).

**Comment by 360fengdai** [comment]
> Hey, "system ruby no gem no fastlane no everything"
> I think If you use the correct fastlane installation it wont redirect to system ruby. Go to the correct gem installation of fastlane and initate from there once . If it solves your problem put its location as system variable(symlink to usr/local/bin).

how I install fastlane:
Gemfile:
gem 'fastlane'
then run bundle install

system ruby path:usr/bin/ruby
my default ruby path (rvm manager):/Users/xxx/.rvm/rubies/ruby-2.6.5/bin/ruby
Here's the problem

I run fastlane in terminal，everything is ok, because which ruby is rvm`s default 
when i use usr/bin/ruby(system ruby), it is not ok ,So I wonder why the system ruby is set up in the code instead of following the user's settings

stuck code in jenkins:
/usr/bin/xcrun .../xxx/xxx/xxx/xcbuild-safe.sh\
 -exportArchive -exportOptionsPlist '/tmp/gym_xxx.plist' \
 -archivePath xx.xcarchive -exportPath '/tmp/gym_xx'
i find xcbuild-safe.sh changed rvm ruby to system ruby，the previous scripts used the rvm ruby，like `bundle install`,
my shell code in jenkins:

#!/bin/zsh
which ruby #rvm ruby
rm -rf Gemfile.lock 
bundle install
rm -rf Podfile.lock #Pods
pod update --verbose
bundle exec fastlane TestFlightBuild # rvm ruby has changed to system ruby!!!

**Comment by DeathStalker403** [comment]
You said its stuck in jenkins right?. As per my experience for Jenkins you need to declare the system path again in the script first. As it is unable to read the correct location for tools for scripts. Faced the same issue. 

Use the following code 

export PATH=give path for default ruby bin directory ; path to fastlane installation 

which ruby #rvm ruby
rm -rf Gemfile.lock 
bundle install
rm -rf Podfile.lock #Pods
pod update --verbose
bundle exec fastlane TestFlightBuild # 


NOTE : DO NOT DECLARE YOUR SYSTEM PATH IN THE EXPORT LIKE
export PATH=give path for default ruby bin directory ; path to fastlane installation ; $PATH

**Comment by 360fengdai** [comment]
> You said its stuck in jenkins right?. As per my experience for Jenkins you need to declare the system path again in the script first. As it is unable to read the correct location for tools for scripts. Faced the same issue.
> 
> Use the following code
> 
> ```
> export PATH=give path for default ruby bin directory ; path to fastlane installation 
> which ruby #rvm ruby
> rm -rf Gemfile.lock 
> bundle install
> rm -rf Podfile.lock #Pods
> pod update --verbose
> bundle exec fastlane TestFlightBuild # 
> ```
> 
> NOTE : DO NOT DECLARE YOUR SYSTEM PATH IN THE EXPORT LIKE
> export PATH=give path for default ruby bin directory ; path to fastlane installation ; $PATH

I believe this is a way to solve the problem, but my question is why the Fastlane source code is written like this,look at the echo code:`echo "RVM detected, forcing to use system ruby"`,I use RVM to manage the default ruby, which means I want to use the default Ruby managed by RVM everywhere. So I think this is a error of fastlane for everyone who has installed RVM and use rvm manager ruby.

You can reproduce the problem like this in you command line：
`rvm use 2.6 --default`
 scripts will be run using the rvm default ruby now 
`which ruby`:/Users/xxx/.rvm/rubies/ruby-2.6.5/bin/ruby
`rvm use system`
`which ruby`:/usr/bin/ruby
all subsequent scripts will be run using the system ruby,they are very likely to be different versions

It's amazing that there are two Ruby environments in the same script file，the problem may not break out now like system ruby is same to rvm default ruby, but it will happen to another person like me in the future again！
