### ISSUE TITLE
Warning: Category 'MZGenre.XXXXX' from iTunesConnect as been deprecated. Please replace with 'XXXXX'

### ISSUE THREAD

**Issue by rogerluan** [fastlane/fastlane#16797]
### New Release Candidate Issue Checklist

- [x] Updated fastlane to the latest release candidate version (2.150.0.rcX)
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Information

- Breaking version: Probably 2.150.x
- Last working version: Not sure, I never used this before (check description)
- State of app: `Prepare for Submission`
- First version of app?: No

### Issue Description

I decided to I pull all the metadata using `bundle exec fastlane deliver init --use_live_version true` today. It populated the `primary_category.txt` with `MZGenre.Finance` and `secondary_category.txt` with `MZGenre.Business`, alongside `primary_first_sub_category.txt` (and 3 other similar files) with empty text files.

These categories were deprecated, and if I simply try to re-upload them to the App Store using deliver, I get a blue warning:

```bash
[16:02:53]: Category 'MZGenre.Finance' from iTunesConnect as been deprecated. Please replace with 'FINANCE'
[16:02:53]: Category 'MZGenre.Business' from iTunesConnect as been deprecated. Please replace with 'BUSINESS'
[16:02:53]: You can find more info at https://docs.fastlane.tools/actions/deliver/#reference
```

This ticket is just to track this warning :) `deliver init` should be pulling the updated categories.

PS: I just noticed that the warning message has a typo 🙈 
```diff
- [16:02:53]: Category 'MZGenre.Finance' from iTunesConnect as been deprecated. Please replace with 'FINANCE'
+ [16:02:53]: Category 'MZGenre.Finance' from iTunesConnect has been deprecated. Please replace with 'FINANCE'
```

### Environment

<details>
  <pre>

### Stack

| Key                         | Value                                                           |
| --------------------------- | --------------------------------------------------------------- |
| OS                          | 10.15.5                                                         |
| Ruby                        | 2.6.5                                                           |
| Bundler?                    | true                                                            |
| Git                         | git version 2.24.3 (Apple Git-128)                              |
| Installation Source         | ~/Documents/Projects/tellus-ios/.vendor/ruby/2.6.0/bin/fastlane |
| Host                        | Mac OS X 10.15.5 (19F101)                                       |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.5/lib                                     |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                                     |
| Is contained                | false                                                           |
| Is homebrew                 | false                                                           |
| Is installed via Fabric.app | false                                                           |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                     |
| Xcode Version               | 11.5                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane gems
| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.151.1 | ✅ Up-To-Date  |

Using Fastlane Swift
</pre>
</details>

### Mentioning

cc: @joshdholtz

**Comment by rogerluan** [comment]
I ran `fastlane env` and put only the relevant stuff, the project-specific files were omitted

**Comment by joshdholtz** [comment]
@rogerluan 👋 Thanks for reporting this! I will fix the typo and see what it takes to pull the new category names down. It didn't _break_ which is why I wasn't fixed in 2.150.X but this is good to have on my list to fix soon 😇

**Comment by rogerluan** [comment]
Lightning fast response @joshdholtz 😱 haha 

Thanks for the update! Makes sense to have this updated later down the road, I know 2.150.0 was an epic rush 😄 

No hurry at all, as it's just a warning (and something that most people just run into once per project) 👍

**Comment by joshdholtz** [comment]
This should be fixed in one of the recent versions 😊
