### ISSUE TITLE
SNAPSHOT - SUPPRESS OUTPUT LOGS WARNINGS during SCREENSHOTS capture.

### ISSUE THREAD

**Issue by NeelSaysHai** [fastlane/fastlane#16792]
#### Motivation Behind Feature
**FASTLANE SNAPSHOT LANE - SUPPRESS OUTPUT LOGS**

#### Feature Description

is there any way to suppress the logs warnings when running the SNAPSHOT lane during screenshots. similar to Xcode suppress_xcode_output: true

**Comment by NeelSaysHai** [comment]
@joshdholtz as suggested, created a new feature request.

**Comment by joshdholtz** [comment]
Thank you! That issue didn't have any changes to snapshot in it so it's cleaner to have this be it's own issue 🙂

**Comment by joshdholtz** [comment]
This should totally be possible, BTW 💪 I won't have time for it this week but somebody else might pick it up 🙃

**Comment by NeelSaysHai** [comment]
> This should totally be possible, BTW 💪 I won't have time for it this week but somebody else might pick it up 🙃

thanks @joshdholtz

**Comment by rogerluan** [comment]
I decided to take a stab on this one :) @joshdholtz thanks for adding the `you can do this` label 💪
