### ISSUE TITLE
Setting expire_previous_builds = true is not expiring previous builds

### ISSUE THREAD

**Issue by p-nicolaou** [fastlane/fastlane#16796]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Setting `expire_previous_builds = true` is not expiring previous builds.

#### Question Description

My lane:
```
private_lane :test_flight_distribution do
  upload_to_testflight(
    ipa: "./build/exports/ABC.ipa",
    expire_previous_builds: true,
    skip_submission: true,
    skip_waiting_for_build_processing: true,
    uses_non_exempt_encryption: false
  )
end
```

**Expectation**
Previous builds to become expired on TestFlight

**Actual Result**
Previous builds still available on TestFlight

**Comment by UPSersLogin** [comment]
See here: https://www.gitmemory.com/issue/fastlane/fastlane/16796/655691841

**Comment by jamesdixon** [comment]
@p-nicolaou I'm also running into the same issue with Fastlane 2.163.0. Were you ever able to resolve the issue?
