### ISSUE TITLE
IOS screenshot upload problem

### ISSUE THREAD

**Issue by Novice-XC** [fastlane/fastlane#16829]
Hello!When using Fastlane to submit application information to Apple store, the local screenshot shows that the upload is successful, but the screenshot is not shown in the webpage.

**Comment by max-ott** [comment]
Please make sure that you updated to the latest Fastlane version and add your `fastlane env` here. Otherwise it's super hard to help.

**Comment by Novice-XC** [comment]
> Please make sure that you updated to the latest Fastlane version and add your `fastlane env` here. Otherwise it's super hard to help.
Sorry, this problem has been solved after updating to the latest version. Thank you very much.
