### ISSUE TITLE
Spaceship::Tunes::Application.all doesn't contain newly created iOS app, preventing build upload

### ISSUE THREAD

**Issue by ktardif** [fastlane/fastlane#16823]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When attempting to deliver a build for an iOS app that was created via the App Store Connect website on July 10, 2020, deliver fails to find the bundle ID. The app does not yet have any builds and is still in Prepare for Submission state. The account used to access App Store Connect does have permissions to view the app (confirmed via accessing the App Store Connect website directly). The only major setting (name, bundle ID, etc aside) which had been changed from the defaults after creation was changing "Pricing and Availability" to restrict access to a specific organization. However, even changing this back doesn't make the app show up. The error returned was:

`[!] Could not find app with app identifier '...' in your App Store Connect account (...)`

I tracked this error message down to deliver/detect_values.rb (Deliver::DetectValues.find_app()):

`app = Spaceship::Tunes::Application.find(search_by, mac: options[:platform] == "osx")`

I've noticed that while Spaceship::Tunes::Application.all is missing this specific app, Spaceship::ConnectAPI::App.all is not. I've also verified the raw response from the endpoint the Tunes variant calls (ra/apps/manageyourapps/summary/v2, via TunesClient.applications()) and it's indeed missing from the response itself, so it's not an error in fastlane itself.

I'm not sure exactly what's causing this, as I've done this process before with other apps and not encountered this issue. The only difference is changing Pricing and Availability, but I can't find anything in the fastlane docs that this should change anything. I'm unsure if Apple changed something with the recent API updates and new apps are no longer showing up on the old endpoint, or if some other default setting on newer apps is causing this. I searched recent issues but didn't spot anything, but apologies if I missed anything obvious. Any help would be appreciated.

Running the following code was used to compare the output from both functions:

```ruby
require 'spaceship'

Spaceship::Tunes.login('...')
Spaceship::Tunes.select_team(team_id: '...')

puts("Tunes:")
Spaceship::Tunes::Application.all.each_with_index do |app, i|
  puts("\t#{i}) #{app.name}: #{app.bundle_id}")
end

#this shows the new app, but not the Tunes version
puts("ConnectAPI:")
Spaceship::ConnectAPI::App.all.each_with_index do |app, i|
  puts("\t#{i}) #{app.name}: #{app.bundle_id}")
end
```

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.151.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                 | Version | Update-Status      |
| ---------------------- | ------- | ------------------ |
| fastlane-plugin-sentry | 1.5.0   | 🚫 Update available |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| bundler                   | 1.16.1       |
| fileutils                 | 1.0.2        |
| rake                      | 13.0.1       |
| CFPropertyList            | 3.0.2        |
| concurrent-ruby           | 1.1.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.11.1     |
| public_suffix             | 4.0.5        |
| addressable               | 2.7.0        |
| ast                       | 2.4.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.341.0      |
| aws-sigv4                 | 1.2.1        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.103.0      |
| aws-sdk-kms               | 1.36.0       |
| aws-sdk-s3                | 1.74.0       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.7.5        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.2.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.4.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.17.0       |
| cocoapods                 | 1.7.5        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 3.0.0        |
| excon                     | 0.75.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 1.0.1        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| jwt                       | 2.2.1        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.0        |
| signet                    | 0.14.0       |
| googleauth                | 0.13.0       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.2        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.2       |
| json                      | 2.3.1        |
| mini_magick               | 4.10.1       |
| plist                     | 3.5.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-sentry    | 1.5.0        |
| kramdown                  | 2.1.0        |
| mime-types-data           | 3.2020.0512  |
| mime-types                | 3.3.1        |
| parallel                  | 1.19.1       |
| parser                    | 2.7.1.2      |
| rainbow                   | 3.0.0        |
| rest-client               | 2.0.2        |
| rexml                     | 3.2.4        |
| ruby-progressbar          | 1.10.1       |
| rubocop                   | 0.83.0       |
| semantic                  | 1.6.1        |
| xcode-install             | 2.6.1        |
</details>

**Comment by joshdholtz** [comment]
@ktardif Hey 👋 A lot of things in `Spaceship::Tunes` no longer work after the latest App Store Connect updates. That legacy API that `Spaceship::Tunes` is no longer up so a lot of its functionality has been transferred over into the `Spaceship::ConnectAPI` module. I’m still working on finishing up the docs (which will explain models, endpoints, and migrations). 

Sadly a lot of users will need to migration from using `Spaceship::Tunes` to `Spaceship::ConnectAPI`. The models and relationships are completely different so they could not be back ported. `Spaceship::ConnectAPI` also allows the use of the new JWT auth which will be the preferred method over the web auth that _fastlane_ currently uses 😇

**Comment by ktardif** [comment]
I see, that makes sense. Should this be classified as a bug then? Since `deliver` from fastlane itself is still using the old `Tunes` API to find apps instead of using `ConnectAPI`, this is preventing `deliver` from being able to deploy for certain apps, since it can't find them via the old `Tunes` API.

I had just found the `ConnectAPI` variant when looking around fastlane to try and troubleshoot the bundle ID not being picked up, so the code there is just something I used to compare their outputs, but seems like `deliver` should be switched to using `ConnectAPI` when searching for apps.

**Comment by ktardif** [comment]
As an update, the app is now appearing in both endpoints; I hadn't checked since last friday afternoon, so it could be that newly created apps won't show up on the old endpoint for some number of hours, or could have been some other delay in Apple's backend. I was able to successfully deploy a build as well.

I think it'd be most likely be best to switch that part of `deliver` over to the new `ConnectAPI` variant in order to avoid issues in the future. I can leave this ticket open if you'd like to track it for that purpose, otherwise I can close it if you have any existing ticket for that purpose.

**Comment by joshdholtz** [comment]
@ktardif `deliver` has been using `Spaceship::ConnectAPI` as of `2.150.0` so I think we can close close this? 😊

**Comment by ktardif** [comment]
@joshdholtz The offending location I mentioned above is still using the `Tunes` API:

https://github.com/fastlane/fastlane/blob/master/deliver/lib/deliver/detect_values.rb#L41

**Comment by joshdholtz** [comment]
@ktardif Ahhhhhh, I see! Thanks for catching that 💪 I will get that fixed today

**Comment by ktardif** [comment]
@joshdholtz Haha no problem, it was buried in my wall of text, just realized I didn't make it very clear.

As an aside unrelated to this issue itself, thank you very much for all your hard work; after taking over 2 iOS projects which were manually managed, fastlane has saved me countless hours of repetitive manual work.
