### ISSUE TITLE
[deliver] refactor `submission_information` into smaller more individual options that are easier to understand

### ISSUE THREAD

**Issue by joshdholtz** [fastlane/fastlane#16854]
`submission_information` offers too many options. A lot of these are needed now with the latest App Store Connect updates. This option should be split up into smaller parts so its easier to document and use.

**Comment by rogerluan** [comment]
Should we kick off a discussion on this? :) How do you see this working? A separate argument for each of `submission_information`'s current keys, or maybe group some related keys into separate Dictionary/Hash fields?
For example, we have `export_compliance*` keys, `content_rights*`, `add_id*` (ad tracking related info), and maybe more. @joshdholtz

**Comment by joshdholtz** [comment]
I think we separate it into 3 options like this 👇 We can then do validation of the individual hashes and document them better.

```rb
content_rights_contains_third_party_content: true, # nil, true, false
add_info: {
  "info_limits_tracking" : true,
  "info_serves_ads" : false,
  "info_tracks_action" : true,
  "info_tracks_install" : true,
  "info_uses_idfa" : true,
},
export_compliance: {
  "platform" : "ios",
  "compliance_required" : false,
  "encryption_updated" : false,
  "app_type" : nil,
  "uses_encryption" : false,
  "is_exempt" : false,
  "contains_third_party_cryptography" : false,
  "contains_proprietary_cryptography" : false, 
  "available_on_french_store" : false
}
```

**Comment by rogerluan** [comment]
Is there a list somewhere of all the possible keys and values for `submission_information` as of right now?

Do you know if this is a growing list of parameters? How has it changed in the past months/years?

**Comment by rogerluan** [comment]
We still need this, bot 😇

**Comment by rogerluan** [comment]
We still need this refactor

**Comment by funnel20** [comment]
> Is there a list somewhere of all the possible keys and values for `submission_information` as of right now?
> 
> Do you know if this is a growing list of parameters? How has it changed in the past months/years?

Yes there is, referring to the source code. See: https://github.com/fastlane/docs/issues/584#issuecomment-409503074

Don't shoot the messenger...

**Comment by rogerluan** [comment]
Thanks for these references @funnel20 ! I didn't know where to find them in the docs, although I had found them in the codebase earlier 😊 

I haven't had time to look into implementing this feature, but it's still on my list. 

If anyone feels like giving it a stab, please feel free to pick it up before me! I'll be happy to review the PR 😊

**Comment by joshdholtz** [comment]
Ah, I need to do this for a few reasons so I should be getting to this probably next week!

**Comment by rogerluan** [comment]
Don't close bot :)

**Comment by Saravia83c** [comment]
No

**Comment by rogerluan** [comment]
Bump

**Comment by rogerluan** [comment]
Bump
