### ISSUE TITLE
[iTMSTransporter] - Transporter transfer failed.

### ISSUE THREAD

**Issue by ibrahimyolbir** [fastlane/fastlane#16859]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
**❯ bundle exec fastlane ios beta --env staging **
With this command from the local computer (client) is builds in a way that I succeed building.but when i start the installation via gitlab i get this error in the last step.

**I added these files separately to the Fastfile file**
-   before_all do
    ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t Signiant"
  end

-       ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t Signiant"
-       ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"
-       ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = " "

**Network Log**

If you look at the log below, the endpoints used by apple have the response '200' so there is no block
```
10.1.87.11 - - [15/Jul/2020:13:51:54 +0200] "CONNECT contentdelivery02.itunes.apple.com:443 HTTP/1.1" 200 5515 "-"

 "iTMSTransporter/2.0.0 (Mac OS X; 10.15.5; x86_64; Java 1.8.0-u131-b11) SmartClient/0.1.0" TCP_TUNNEL:HIER_DIRECT

``` 

```
 [13:52:59]: Transporter transfer failed.
 [13:52:59]: 
 [13:52:59]: [iTMSTransporter] [2020-07-15 13:52:58 CEST] <main> DBG-X: Setting the throttle to 12500000 bytes per second.
 [13:52:59]: [iTMSTransporter] [2020-07-15 13:52:58 CEST] <Transport Protocol>  INFO: The Signiant transfer engine's status is CONNECTING
 [13:52:59]: [iTMSTransporter] Exception in thread "Transport Protocol Seeker" [2020-07-15 13:52:58 CEST] <Transport Protocol>  INFO: The Signiant transfer engine's status is DISCONNECTED
 [13:52:59]: [iTMSTransporter] java.lang.ArrayIndexOutOfBoundsException: 1
 [13:52:59]: [iTMSTransporter] 	at com.signiant.interactivetransfer.engine.TransferEngine$5.run(TransferEngine.java:3603)
 [13:52:59]: [iTMSTransporter] [2020-07-15 13:52:58 CEST] <main> ERROR: Could not start delivery: all transports failed diagnostics
 [13:52:59]: [iTMSTransporter] 
 [13:52:59]: [iTMSTransporter] 
 [13:52:59]: [iTMSTransporter] 
 [13:52:59]: [iTMSTransporter] Package Summary:
 [13:52:59]: [iTMSTransporter]  
 [13:52:59]: [iTMSTransporter] 1 package(s) were not uploaded because they had problems:
 [13:52:59]: [iTMSTransporter] 	/var/folders/l2/x8wzywcd47zfxfzbj03dlyf40000gp/T/d20200715-4418-rchkba/975830741.itmsp - Error Messages:
 [13:52:59]: [iTMSTransporter] 		Could not start delivery: all transports failed diagnostics
 [13:52:59]: [iTMSTransporter] [2020-07-15 13:52:59 CEST] <main> DBG-X: Returning 1
 [13:52:59]: iTunes Transporter output above ^
 [13:52:59]: Could not start delivery: all transports failed diagnostics
 Return status of iTunes Transporter was 1: Could not start delivery: all transports failed diagnostics
 The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.

```
<details><summary>🚫 All error Log 🚫</summary>

 [13:51:02]: ▸ -----------------------------------------
 [13:51:02]: ▸ {
 [13:51:02]: ▸   "method": "app-store"
 [13:51:02]: ▸ }
 [13:51:02]: ▸ -----------------------------------------

 [13:51:02]: $ /usr/bin/xcrun /Users/gitlabrunner/tmp-fastlane-ci-bundle/ruby/2.7.0/gems/fastlane-

2.128.1/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist 

'/var/folders/l2/x8wzywcd47zfxfzbj03dlyf40000gp/T/gym_config20200715-4418-n34us8.plist' -archivePath 

/Users/gitlabrunner/Library/Developer/Xcode/Archives/2020-07-15/[appname]\ 2020-07-15\ 13.36.51.xcarchive -exportPath 

'/var/folders/l2/x8wzywcd47zfxfzbj03dlyf40000gp/T/gym_output20200715-4418-1msaci4' APP_IDENTIFIER='se.xx.xxx.test' 

CODEPUSH_KEY='xxx' -allowProvisioningUpdates -allowProvisioningDeviceRegistration 

 [13:51:31]: Mapping dSYM(s) using generated BCSymbolMaps

 [13:51:31]: $ dsymutil --symbol-map /Users/gitlabrunner/Library/Developer/Xcode/Archives/2020-07-15/[appname]\ 2020-

07-15\ 13.36.51.xcarchive/BCSymbolMaps /Users/gitlabrunner/Library/Developer/Xcode/Archives/2020-07-15/[appname]\ 

2020-07-15\ 13.36.51.xcarchive/dSYMs/[appname].app.dSYM

 warning: /Users/gitlabrunner/Library/Developer/Xcode/Archives/2020-07-15/[appname]2020-07-15 

13.36.51.xcarchive/BCSymbolMaps/[appname]-armv7.bcsymbolmap: No such file or directory: not unobfuscating.

 warning: /Users/gitlabrunner/Library/Developer/Xcode/Archives/2020-07-15/[appname] 2020-07-15 

13.36.51.xcarchive/BCSymbolMaps/[appname]-arm64.bcsymbolmap: No such file or directory: not unobfuscating.

 [13:51:33]: Compressing 1 dSYM(s)

 [13:51:33]: $ cd '/Users/gitlabrunner/Library/Developer/Xcode/Archives/2020-07-15/[appname] 2020-07-15 

13.36.51.xcarchive/dSYMs' && zip -r 

'/Users/gitlabrunner/builds/xxxxxxxxx/0/reactnative/[appname]/[appname].app.dSYM.zip' *.dSYM

 [13:51:37]: ▸   adding: [appname].app.dSYM/ (stored 0%)
 [13:51:37]: ▸   adding: [appname].app.dSYM/Contents/ (stored 0%)
 [13:51:37]: ▸   adding: [appname].app.dSYM/Contents/Resources/ (stored 0%)
 [13:51:37]: ▸   adding: [appname].app.dSYM/Contents/Resources/DWARF/ (stored 0%)
 [13:51:37]: ▸   adding: [appname].app.dSYM/Contents/Resources/DWARF/[appname] (deflated 74%)
 [13:51:37]: ▸   adding: [appname].app.dSYM/Contents/Info.plist (deflated 52%)
 [13:51:37]: Successfully exported and compressed dSYM file
 [13:51:37]: Successfully exported and signed the ipa file:
 [13:51:37]: /Users/gitlabrunner/builds/xxxx/0/reactnative/[appname]/[appname].ipa
 [13:51:37]: ----------------------------------
 [13:51:37]: --- Step: upload_to_testflight ---
 [13:51:37]: ----------------------------------
 [13:51:37]: Login to App Store Connect (xx@xx.se)
 [13:51:38]: Login successful
 [13:51:42]: Ready to upload new build to TestFlight (App: xx)...
 [13:51:54]: iTunes Transporter successfully finished its job
 [13:51:54]: Going to upload updated app to App Store Connect
 [13:51:54]: This might take a few minutes. Please don't interrupt the script.
 [13:52:59]: Transporter transfer failed.
 [13:52:59]: 
 [13:52:59]: [iTMSTransporter] [2020-07-15 13:52:58 CEST] <main> DBG-X: Setting the throttle to 12500000 bytes per second.
 [13:52:59]: [iTMSTransporter] [2020-07-15 13:52:58 CEST] <Transport Protocol>  INFO: The Signiant transfer engine's status is CONNECTING
 [13:52:59]: [iTMSTransporter] Exception in thread "Transport Protocol Seeker" [2020-07-15 13:52:58 CEST] <Transport Protocol>  INFO: The Signiant transfer engine's status is DISCONNECTED
 [13:52:59]: [iTMSTransporter] java.lang.ArrayIndexOutOfBoundsException: 1
 [13:52:59]: [iTMSTransporter] 	at com.signiant.interactivetransfer.engine.TransferEngine$5.run(TransferEngine.java:3603)
 [13:52:59]: [iTMSTransporter] [2020-07-15 13:52:58 CEST] <main> ERROR: Could not start delivery: all transports failed diagnostics
 [13:52:59]: [iTMSTransporter] 
 [13:52:59]: [iTMSTransporter] 
 [13:52:59]: [iTMSTransporter] 
 [13:52:59]: [iTMSTransporter] Package Summary:
 [13:52:59]: [iTMSTransporter]  
 [13:52:59]: [iTMSTransporter] 1 package(s) were not uploaded because they had problems:
 [13:52:59]: [iTMSTransporter] 	/var/folders/l2/x8wzywcd47zfxfzbj03dlyf40000gp/T/d20200715-4418-rchkba/975830741.itmsp - Error Messages:
 [13:52:59]: [iTMSTransporter] 		Could not start delivery: all transports failed diagnostics
 [13:52:59]: [iTMSTransporter] [2020-07-15 13:52:59 CEST] <main> DBG-X: Returning 1
 [13:52:59]: iTunes Transporter output above ^
 [13:52:59]: Could not start delivery: all transports failed diagnostics
 Return status of iTunes Transporter was 1: Could not start delivery: all transports failed diagnostics
 The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.

 +-----------------------------------+--------------------------------------------------------------------------------------------------------+
 |                                                                Lane Context                                                                |
 +-----------------------------------+--------------------------------------------------------------------------------------------------------+
 | ENVIRONMENT                       | test                                                                                                   |
 | PLATFORM_NAME                     | ios                                                                                                    |
 | LANE_NAME                         | ios beta                                                                                               |
 | GET_INFO_PLIST_VALUE_CUSTOM_VALUE | 2.2.3                                                                                                  |
 | LATEST_BUILD_NUMBER               | 31                                                                                                     |
 | LATEST_TESTFLIGHT_BUILD_NUMBER    | 31                                                                                                     |
 | BUILD_NUMBER                      | 32                                                                                                     |
 | IPA_OUTPUT_PATH                   | /Users/gitlabrunner/builds/xx/0/reactnative/[appname]/[appname].ipa                             |
 | DSYM_OUTPUT_PATH                  | /Users/gitlabrunner/builds/xx/0/reactnative/[appname]/DGFonder.app.dSYM.zip                    |
 | XCODEBUILD_ARCHIVE                | /Users/gitlabrunner/Library/Developer/Xcode/Archives/2020-07-15/[appname] 2020-07-15 13.36.51.xcarchive |
 +-----------------------------------+--------------------------------------------------------------------------------------------------------+
 [13:52:59]: Error uploading ipa file, for more information see above
 +------+------------------------------------+-------------+
 |                    fastlane summary                     |
 +------+------------------------------------+-------------+
 | Step | Action                             | Time (in s) |
 +------+------------------------------------+-------------+
 | 1    | cocoapods                          | 35          |
 | 2    | update_app_identifier              | 0           |
 | 3    | get_info_plist_value               | 0           |
 | 4    | latest_testflight_build_number     | 3           |
 | 5    | increment_build_number             | 0           |
 | 6    | update_project_team                | 0           |
 | 7    | cd .. && ./scripts/patchInstall.sh | 26          |
 | 8    | build_ios_app                      | 893         |
 | 💥   | upload_to_testflight               | 82          |
 +------+------------------------------------+-------------+
 [13:52:59]: fastlane finished with errors
 [!] Error uploading ipa file, for more information see above
</details>

### Environment
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.3                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.2 (Apple Git-127)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.3 (19D76)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.4.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_require 'dotenv'
fastlane_require 'spaceship'

platform :ios do

  desc 'Push a new build to TestFlight'
  lane :beta do

  before_all do
    ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t Signiant"
  end
    cocoapods(
      podfile: 'ios/Podfile'
    )

    # To make sure the build numbers never collide, fetch current
    # build number from testflight for this version
    
    update_app_identifier(
      xcodeproj: 'ios/xxx.xcodeproj',
      plist_path:'../ios/xxx/Info.plist', 
      app_identifier: ENV['APP_IDENTIFIER']
    )
    
    version = get_info_plist_value(
      path:'ios/xxx/Info.plist', 
      key: 'CFBundleShortVersionString'
    )

    current_build_number = latest_testflight_build_number(
      app_identifier: ENV['APP_IDENTIFIER'],
      username: ENV['TESTFLIGHT_USERNAME'],
      team_id: ENV['FASTLANE_ITC_TEAM_ID'],
      version: version
    )
    increment_build_number(
      xcodeproj: 'ios/xxx.xcodeproj',
      build_number: current_build_number + 1
    )
    
    

    

    update_project_team(
      path: 'ios/xxx.xcodeproj',
      teamid: ENV['DEVELOPMENT_TEAM']
    )

    sh('cd .. && ./scripts/patchInstall.sh')
    
    build_ios_app(
      workspace: 'ios/xxx.xcworkspace',
      scheme: 'xxx',
      configuration: ENV['CONFIGURATION'],
      silent: false,
      xcargs: "APP_IDENTIFIER='" + ENV['APP_IDENTIFIER'] + "' CODEPUSH_KEY='" + ENV['CODEPUSH_KEY'] + "' -allowProvisioningUpdates -allowProvisioningDeviceRegistration"
    )
 
    upload_to_testflight(
      username: ENV['TESTFLIGHT_USERNAME'],
      skip_waiting_for_build_processing: true
    )
  end
end


platform :android do
  desc 'Submit a new Beta Build to Crashlytics Beta'
  lane :beta do
    
   

    gradle(
      project_dir: 'android',
      task: 'clean ' + ENV['GRADLE_BUILD_TASK'],
      properties: {
        "sign.xxx.android.keystore" => ENV['KEY_RELEASE_LOCATION'],
        "sign.xxx.android.storepass" => ENV['KEYSTORE_RELEASE_PASS'],
        "sign.xxx.android.alias" => ENV['KEY_RELEASE_ALIAS'],
        "sign.xxx.android.keypass" => ENV['KEY_RELEASE_PASS']
      }
    )
          firebase_app_distribution(
              app: ENV['FIREBASE_APP_ID_ANDROID'],
              testers: "xxx@gmail.com",
              release_notes: "",
              firebase_cli_path: "/usr/local/bin/firebase"
          )
  end

  lane :tag do
    version_tag = "android/" + android_get_version_name(
      gradle_file: "android/app/build.gradle" 
    )
    if !git_tag_exists(tag: version_tag)
      add_git_tag(
        tag: version_tag
      )
      push_git_tags()
    else 
      raise "Git tag " + version_tag + " already exists"
    end
  end

  lane :playstore do
    gradle(
      project_dir: 'android',
      task: 'clean ' + ENV['GRADLE_BUILD_TASK'],
      properties: {
        "sign.xxx.android.keystore" => ENV['KEY_RELEASE_LOCATION'],
        "sign.xxx.android.storepass" => ENV['KEYSTORE_RELEASE_PASS'],
        "sign.xxx.android.alias" => ENV['KEY_RELEASE_ALIAS'],
        "sign.xxx.android.keypass" => ENV['KEY_RELEASE_PASS']
      }
    )
    supply(
      track: 'production'
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# Android parameters
json_key_file("supply_key.json") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("se.xxx.android") # e.g. com.krausefx.app

# iOS parameters
# apple_id("xxx.xxx@xxx.se") # Your Apple email address

itc_team_id("xxx") # App Store Connect Team ID
team_id("xxx") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.128.1 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| faraday_middleware        | 0.14.0       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types                | 3.3.1        |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.5.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.17.0       |
| tty-screen                | 0.8.0        |
| excon                     | 0.75.0       |
| json                      | 2.3.0        |
| bundler                   | 2.1.4        |
| declarative               | 0.0.20       |
| mime-types-data           | 3.2020.0512  |
| google-cloud-env          | 1.3.2        |
| google-cloud-errors       | 1.0.1        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>

*generated on:* **2020-07-15**
</details>

**Comment by max-ott** [comment]
Please update to the latest fastlane version and try again.

**Comment by ibrahimyolbir** [comment]
The problem was caused by a proxy. I solved the problem by adding **'DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS'** as a variable to _'gitlab> Settings> CI / CD> variables'._

**Key =>**      DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS 

**Value =>**  -Dhttp.proxyHost=proxy.xxxx.com -Dhttp.proxyPort=3128 -Dhttps.proxyHost=proxy.xxxx.com -Dhttps.proxyPort=3128 -t DAV #

Type | Key(Click to sort Descending) | Value | Protected | Masked | Environments |  
-- | -- | -- | -- | -- | -- | --
Variable | DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS | ********************* |   |   | All (default) |
