### ISSUE TITLE
Running Cert on linux gets stuck on keychain_path despite creating the correct files

### ISSUE THREAD

**Issue by GForceWeb** [fastlane/fastlane#16850]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm trying to get my cert creation workflow up and running on Linux (more specifically Ubuntu via WSL). My Fastfile makes use of the produce, register_devices, cert, sigh & pem commands. My issue is that I can't get the cert commands to execute cleanly as they complain about the keychain and error out. With no keychain_path specified, it prompts me to enter the path to one. I tried copying a valid keychain file from my MacOS system and using that which produced the error I've included below. 

The cert command still produces the files I need, it just errors out at the keychain step preventing the rest of my fastfile from executing. What I'd like is just a way to just skip over the keychain steps and continue executing the fastfile as I use openssl commands on the cert files to create what I require automatically. I don't have any need for the keychain integration.

##### Command executed
fastlane appp

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [12:23:29]: fastlane detected a Gemfile in the current directory
[12:23:29]: However, it seems like you didn't use `bundle exec`
[12:23:29]: To launch fastlane faster, please use
[12:23:29]:
[12:23:29]: $ bundle exec fastlane appp
[12:23:29]:
[12:23:29]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
/var/lib/gems/2.7.0/gems/fastlane-2.151.2/fastlane_core/lib/fastlane_core/ui/interface.rb:141: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/var/lib/gems/2.7.0/gems/fastlane-2.151.2/fastlane_core/lib/fastlane_core/ui/errors/fastlane_error.rb:9: warning: The called method `initialize' is defined here
[12:23:31]: ----------------------------------------
[12:23:31]: --- Step: Verifying fastlane version ---
[12:23:31]: ----------------------------------------
[12:23:31]: Your fastlane version 2.151.2 matches the minimum requirement of 2.99.1  ✅
[12:23:31]: ------------------------------
[12:23:31]: --- Step: default_platform ---
[12:23:31]: ------------------------------
[12:23:31]: Driving the lane 'appp' 🚀
[12:23:31]: ------------------
[12:23:31]: --- Step: cert ---
[12:23:31]: ------------------

+----------------------+---------------------------------+
|                Summary for cert 2.151.2                |
+----------------------+---------------------------------+
| development          | true                            |
| username             | ************@gmail.com         |
| filename             | dev_com.************.app.cer  |
| force                | false                           |
| generate_apple_certs | true                            |
| keychain_path        | fastlane/**********.keychain-db |
| keychain_password    | ********                        |
| platform             | ios                             |
+----------------------+---------------------------------+

[12:23:31]: Starting login with user '************@gmail.com'
-------------------------------------------------------------------------------------
Please provide your Apple Developer Program account credentials
You can also pass the password using the `FASTLANE_PASSWORD` environment variable
-------------------------------------------------------------------------------------
/var/lib/gems/2.7.0/gems/highline-1.7.10/lib/highline.rb:624: warning: Using the last argument as keyword parameters is deprecated
/var/lib/gems/2.7.0/gems/highline-1.7.10/lib/highline.rb:624: warning: Using the last argument as keyword parameters is deprecated

Available session is not valid any more. Continuing with normal login.
[12:23:48]: Successfully logged in
+------------------+------+
|      Lane Context       |
+------------------+------+
| DEFAULT_PLATFORM | ios  |
| PLATFORM_NAME    |      |
| LANE_NAME        | appp |
+------------------+------+
[12:23:50]: No such file or directory - security

+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | Verifying fastlane version                                    | 0           |
| 2    | default_platform                                              | 0           |
| 💥   | cert                                                          | 19          |
+------+---------------------------------------------------------------+-------------+

[12:23:50]: fastlane finished with errors

[12:23:50]: Error accessing file, this might be due to fastlane's directory handling
[12:23:50]: Check out https://docs.fastlane.tools/advanced/#directory-behavior for more details </pre>
</details>

### Environment

<details>
  <pre> <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                                    |
| --------------------------- | ------------------------------------------------------------------------ |
| OS                          | debian_based bullseye/sid                                                |
| Ruby                        | 2.7.0                                                                    |
| Bundler?                    | false                                                                    |
| Git                         | git version 2.25.1                                                       |
| Installation Source         | /usr/local/bin/fastlane                                                  |
| Host                        | Ubuntu 20.04 LTS debian_based bullseye/sid (4.19.104-microsoft-standard) |
| Ruby Lib Dir                | /usr/lib                                                                 |
| OpenSSL Version             | OpenSSL 1.1.1f  31 Mar 2020                                              |
| Is contained                | false                                                                    |
| Is homebrew                 | false                                                                    |
| Is installed via Fabric.app | false                                                                    |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools

fastlane_version "2.99.1"
default_platform :ios



#LINUXTESTING
keychain_path = "fastlane/*****.keychain-db"
keychain_password = "******"

#Fill These based on the customer data

site_slug = "************"
app_name = "***********"
app_id = "com.*******.app"
username = "******"


##ONLY REQUIRED if using shared account with access to multiple teams. Leave blank otherwise
#To get Team ID, run fastlane appp and take the ID from the first prompt then Ctrl+C to cancel script
team_id = ""

#Android Keystore Variables ## Use fastlane android to generate these
custname = "*********"
countrycode = "**"


#Bitrise Slug - Not currently required. Will be needed for auto cert upload if I get it working
bitriseslug = ""

#Change to true if there's an existing push cert you need to overwrite
forcepush = "true"

## No More edits required below ##


# Folder Setups
app_name = app_name.downcase
app_name = app_name.gsub(' ','-')
app_name = app_name.delete('|')
app_name = app_name.delete('&')
app_name = app_name.delete("'")
app_folder = site_slug+"/"+app_name

Dir.chdir("..") do
    sh("mkdir -p #{app_folder}")
    sh("mkdir -p #{app_folder}/*******")
    sh("mkdir -p #{app_folder}/**********")
    sh("mkdir -p #{app_folder}/bitrise")
end


lane :appp do

    time = Time.new
    day = time.day
    month = time.month
    year = time.year
    date = "#{day}-#{month}-#{year}"

    # create app in account
    produce(
           username: "#{username}",
           app_identifier: "#{app_id}",
           app_name: "#{app_name}",
           company_name: "#{app_name}",
           skip_itc: true, # don't create app in itunes connect
           # enable_services: {
           #   in_app_purchase: "on"
           # }
           team_id: "#{team_id}",
    )

    #register_devices(
        devices: {
            "*********" => "****************",
            "***********" => "******************"
        },
        username: "#{username}"
    )
    # generate dev cert
    cert(
       development: true,
       username: "#{username}",
       output_path: "./#{app_folder}",
       filename: "dev_#{app_id}.cer",
       force: false,
       team_id: "#{team_id}",
       generate_apple_certs: true,
       keychain_path: "#{keychain_path}",
       keychain_password: "#{keychain_password}",

    )
    devcertid = lane_context[SharedValues::CERT_CERTIFICATE_ID]
    puts "#{devcertid}"
    # development provisioning profile
    sigh(
      development: true,
      app_identifier: "#{app_id}",
      username: "#{username}",
      skip_install: true,
      output_path: "./#{app_folder}",
      filename: "dev_#{app_id}.mobileprovision",
      team_id: "#{team_id}",
      # force: true
    )

    # generate prod cert
    cert(
        username: "#{username}",
        output_path: "./#{app_folder}",
        filename: "prod_#{app_id}.cer",
        force: false,
        team_id: "#{team_id}",
        generate_apple_certs: true,
        keychain_path: "#{keychain_path}",
        keychain_password: "#{keychain_password}",
    )
    prodcertid = lane_context[SharedValues::CERT_CERTIFICATE_ID]
    puts "#{prodcertid}"
    # push certs
    pem(
        app_identifier: "#{app_id}",
        username: "#{username}",
        p12_password: '******',
        generate_p12: true,
        output_path: "./#{app_folder}",
        force: "#{forcepush}",
        team_id: "#{team_id}",
    )
    # app store provisioning profile
    sigh(
        app_identifier: "#{app_id}",
        username: "#{username}",
        skip_install: true,
        filename: "prod_#{app_id}.mobileprovision",
        output_path: "./#{app_folder}",
        team_id: "#{team_id}",
    )

    # adhoc provisioning profile
    sigh(
      adhoc: true,
      app_identifier: "#{app_id}",
      skip_install: true,
      username: "#{username}",
      output_path: "./#{app_folder}",
      filename: "adhoc_#{app_id}.mobileprovision",
      team_id: "#{team_id}",
    )

end


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.151.2 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.17.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.75.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.2        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.1        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.0        |
| googleauth                | 0.13.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.2        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-storage      | 1.26.2       |
| emoji_regex               | 3.0.0        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.341.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.1        |
| aws-sdk-core              | 3.103.0      |
| aws-sdk-kms               | 1.36.0       |
| aws-sdk-s3                | 1.74.0       |
| uri                       | 0.10.0       |
| forwardable               | 1.3.1        |
| logger                    | 1.4.2        |
| cgi                       | 0.1.0        |
| timeout                   | 0.1.0        |
| stringio                  | 0.1.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.2.0        |
| strscan                   | 1.0.3        |
| date                      | 3.0.0        |
| delegate                  | 0.1.0        |
| fileutils                 | 1.4.1        |
| etc                       | 1.1.0        |
| io-console                | 0.5.3        |
| zlib                      | 1.1.0        |
| singleton                 | 0.1.0        |
| rexml                     | 3.2.3        |
| open3                     | 0.1.0        |
| yaml                      | 0.1.0        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.6.0        |
</details>

*generated on:* **2020-07-14**
</details> </pre>
</details>

**Comment by janpio** [comment]
Very possible that there is no Linux specific handling of that yet - the keychain stuff can not work on Linux, but the code probably does not know that yet as it is usually quite deeply integrated.
