### ISSUE TITLE
[spaceship] add ability to modify ‘isOptedInToDistributeIosAppOnMacAppStore‘ on ‘Spaceship::ConnectAPI::App’

### ISSUE THREAD

**Issue by joshdholtz** [fastlane/fastlane#16868]
Relevant discussion - https://github.com/fastlane/fastlane/discussions/16861

**Comment by reishka** [comment]
@joshdholtz Any idea on a ETA for this? We're currently managing 130+ apps and we don't want them available for macs just yet, since they haven't been through a QA cycle. Our only option at this point is to manually modify all the apps within the app store.

**Comment by joshdholtz** [comment]
Ah, I should be able to get to this into master today and released tomorrow for you!

**Comment by reishka** [comment]
@joshdholtz Thank you so much!
