### ISSUE TITLE
A problem for xcarchive encryption

### ISSUE THREAD

**Issue by WTFCSL** [fastlane/fastlane#16860]
A problem for xcarchive encryption
I have a process:
action1:archive my ***1.xcworkspace
action2: My own operation, for example, I will encrypt ***1.archive to generate ***2.archive
action3:export ***2.archive into .ipa package
But I read the actions document and found no such process. Can you provide a process like this, thank very much

**Comment by max-ott** [comment]
Hi there, I'm not sure how this is related with `fastlane`? Please clarify and open a new issue.
