### ISSUE TITLE
Cannot modify consumable IAPs that have been approved

### ISSUE THREAD

**Issue by sjmh** [fastlane/fastlane#16864]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

We're trying to update IAP's via fastlane that have been Approved by Apple.. All we get in return from the ASC is ITC.response.error.OPERATION_FAILED.  Doing this for new IAPs/Ready to Submit IAPs works fine.

I saw there were a few other issues about this, but they were all locked off.  If there are any pointers on where to get started in fixing this, I'd love to try and get a PR going.

**Comment by pfay-fc** [comment]
https://github.com/fastlane/fastlane/issues/15437#issuecomment-551038151 has some info about what might need to be done to get this working

**Comment by 954708775** [comment]
Same issues here, so it have been solved?
