### ISSUE TITLE
[fastlane_core] "Sending analytics" message appears even when analytics is disabled

### ISSUE THREAD

**Issue by bsiegel** [fastlane/fastlane#16874]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

In `fastlane_core`, the logic that emits the message about "sending analytics" in `AnalyticsSession` occurs before checking whether the opt_out flag is set in `AnalyticsIngesterClient`. This leads the customer to believe that analytics are still being sent even when the opt_out flag is provided.

I suggest that at the very beginning of `AnalyticsSession#action_launched`, the first thing to do would be to check whether the opt_out flag is provided and return immediately if true.

##### Command executed

I reproduced this using the `trainer` command which uses fastlane internally, but it should be reproducible with any fastlane tooling:

```bash
rm ~/.fastlane/.did_show_opt_info
FASTLANE_OPT_OUT_USAGE=YES fastlane
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
[✔] 🚀
[12:58:45]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[12:58:49]: Sending anonymous analytics information
[12:58:49]: Learn more at https://docs.fastlane.tools/#metrics
[12:58:49]: No personal or sensitive data is sent.
[12:58:49]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
/usr/local/lib/ruby/gems/2.7.0/gems/highline-1.7.10/lib/highline.rb:624: warning: Using the last argument as keyword parameters is deprecated
[12:58:49]: Could not find fastlane in current directory. Make sure to have your fastlane configuration files inside a folder called "fastlane". Would you
like to set fastlane up? (y/n)
  </pre>
</details>

### Environment

<details>
  <pre>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.5                                     |
| Ruby                        | 2.7.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.27.0                          |
| Installation Source         | /usr/local/lib/ruby/gems/2.7.0/bin/fastlane |
| Host                        | Mac OS X 10.15.5 (19F101)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.7.1_2/lib          |
| OpenSSL Version             | OpenSSL 1.1.1f  31 Mar 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.6                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.152.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.75.0       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.0.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.1.2        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.0        |
| googleauth                | 0.13.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.2        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.5.1        |
| google-cloud-storage      | 1.26.2       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.337.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.1        |
| aws-sdk-core              | 3.103.0      |
| aws-sdk-kms               | 1.35.0       |
| aws-sdk-s3                | 1.72.0       |
| uri                       | 0.10.0       |
| public_suffix             | 3.1.1        |
| faraday                   | 0.17.3       |
| faraday_middleware        | 0.14.0       |
| forwardable               | 1.3.1        |
| logger                    | 1.4.2        |
| cgi                       | 0.1.0        |
| timeout                   | 0.1.0        |
| stringio                  | 0.1.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.2.0        |
| strscan                   | 1.0.3        |
| date                      | 3.0.0        |
| delegate                  | 0.1.0        |
| fileutils                 | 1.4.1        |
| io-console                | 0.5.6        |
| zlib                      | 1.1.0        |
| singleton                 | 0.1.0        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.8       |
| racc                      | 1.4.16       |
| rexml                     | 3.2.3        |
| open3                     | 0.1.0        |
| yaml                      | 0.1.0        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.6.0        |
</details>

*generated on:* **2020-07-16**
</details>
</pre>
</details>

**Comment by bsiegel** [comment]
Still reproduces with fastlane-2.156.1

**Comment by bsiegel** [comment]
Still reproduces with fastlane-2.160.0

**Comment by aried3r** [comment]
@bsiegel, does this happen to you only on CI or also locally? Locally on macOS I do not face this problem and I cannot reproduce it locally. But we are also wondering if the output is wrong or if analytics are indeed not disabled.

```console
$ bundle exec fastlane download_symbols_and_upload_to_crashlytics
[✔] 🚀
[12:08:49]: ---------------------------
[12:08:49]: --- Step: opt_out_usage ---
[12:08:49]: ---------------------------
[12:08:49]: Disabled upload of used actions
```

but on GitHub actions we do:

```console
$ bundle exec fastlane download_symbols_and_upload_to_crashlytics
[19:11:57]: Sending anonymous analytics information
[19:11:57]: Learn more at docs.fastlane.tools/#metrics
[19:11:57]: No personal or sensitive data is sent.
[19:11:57]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
[19:11:57]: ---------------------------
[19:11:57]: --- Step: opt_out_usage ---
[19:11:57]: ---------------------------
[19:11:57]: Disabled upload of used actions
```

**Comment by bsiegel** [comment]
I verified in the code base that the opt-out is in fact honored, only the message is shown. Check the logic in `AnalyticsSession#action_launched`. It happens locally for me, I have not attempted to use fastlane in CI.

To clarify, this only happens the first time the command is run, because once the message is shown, the file `~/fastlane/.did_show_opt_info` is created which [suppresses the message in the future].(https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/analytics/analytics_session.rb#L22)

However if you remove that file, and run fastlane with the opt-out environment variable set, the message is still shown, which is misleading. To repro:

rm ~/.fastlane/.did_show_opt_info
FASTLANE_OPT_OUT_USAGE=YES fastlane
