### ISSUE TITLE
[Deliver] 'usesNonExemptEncryption' error even though all compliance parameters are being passed.

### ISSUE THREAD

**Issue by randyvarela5** [fastlane/fastlane#16881]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Ive been unable to complete an app delivery since 2.149.1 (before wwdc 2020 update). It appears that the compliance questions have changed their wording and the parameters in [appsubmission.rb](https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/tunes/app_submission.rb#L89) either dont account for all questions, or perhaps im not doing something correctly. 
```handle_response': [!] The request cannot be fulfilled because of the state of another resource. - Submit for review errors found. (Spaceship::UnexpectedResponse)
The provided entity is missing a required attribute - You must provide a value for the attribute 'usesNonExemptEncryption' with this request
```

Im almost positive that its getting stuck on this particular question:
![Screen Shot 2020-07-16 at 4 30 19 PM](https://user-images.githubusercontent.com/7034591/87808798-fa790d00-c81f-11ea-86a5-61c4bb6d30d3.png)

##### Command executed
`fastlane deliver --verbose`

<details>
  Ive documented all details and testing steps I took on #16645 . Since the issue reported there was similar and closed, I Creating a new bug here to get some traction on this issue.
</details>

### Environment

  desc 'Build IPA and upload to App Store, submit for review/scan.'
  lane :store do |options|
  	if (ENV['STORE_IPA'].length > 0)
  		pods environment:"store"
  		wearables environment:"store"

  		# Update provisioning with a find and replace
  		data = File.read("../###.xcodeproj/project.pbxproj")

  		if (ENV['IS_DEMO_TARGET'].downcase == "true")
  			match(
  				type: "enterprise",
  				app_identifier: ENV['STORE_IPA']
  			)

  			# Match for Today Extension
  			match(
  				type: "enterprise",
  				app_identifier: ENV['STORE_IPA'] + "###",
  				git_url: "###",
  				username: "###"
  			)

  			# match for wearables targets
  			if (ENV['WATCH_ENABLED'].downcase == "true")
  				match(
  					type: "enterprise",
  					app_identifier: ENV['STORE_WATCHKIT']
  				)

  				match(
  					type: "enterprise",
  					app_identifier: ENV['STORE_WATCHKIT_EXTENSION']
  				)
  			end

  			# Provisioning Profiles - Handle Enterprise and appstore for cases which include watch and those that don't.
  			sighEnvVar = "sigh_" + ENV['STORE_IPA'] + "_enterprise_profile-name"
  			replacementData = data.gsub("PROVISIONING_PROFILE_SPECIFIER = \"$(sigh_BUNDLETOKEN_appstore_profile-name)\";","PROVISIONING_PROFILE_SPECIFIER = \"" + ENV[sighEnvVar] + "\";")
  			replacementData = replacementData.gsub("PROVISIONING_PROFILE_SPECIFIER = \"$(sigh_BUNDLETOKEN_enterprise_profile-name)\";","PROVISIONING_PROFILE_SPECIFIER = \"" + ENV[sighEnvVar] + "\";")

  			# Today widget provisioning
  			sighEnvVar = "sigh_" + ENV['STORE_IPA'] + ".###_enterprise_profile-name"
  			replacementData = replacementData.gsub("PROVISIONING_PROFILE_SPECIFIER = \"$(sigh_BUNDLETOKEN.###_appstore_profile-name)\";","PROVISIONING_PROFILE_SPECIFIER = \"" + ENV[sighEnvVar] + "\";")
  			replacementData = replacementData.gsub("PROVISIONING_PROFILE_SPECIFIER = \"$(sigh_BUNDLETOKEN.###_enterprise_profile-name)\";","PROVISIONING_PROFILE_SPECIFIER = \"" + ENV[sighEnvVar] + "\";")

  			if (ENV['WATCH_ENABLED'].downcase == "true")
  				sighEnvVar = "sigh_" + ENV['STORE_WATCHKIT'] + "_enterprise_profile-name"
  				replacementData = replacementData.gsub("PROVISIONING_PROFILE_SPECIFIER = \"$(sigh_BUNDLETOKENWATCHKIT_enterprise_profile-name)\";","PROVISIONING_PROFILE_SPECIFIER = \"" + ENV[sighEnvVar] + "\";")

  				sighEnvVar = "sigh_" + ENV['STORE_WATCHKIT_EXTENSION'] + "_enterprise_profile-name"
  				replacementData = replacementData.gsub("PROVISIONING_PROFILE_SPECIFIER = \"$(sigh_BUNDLETOKENWATCHKITEXTENSION_enterprise_profile-name)\";","PROVISIONING_PROFILE_SPECIFIER = \"" + ENV[sighEnvVar] + "\";")
  			end

  			
  			replacementData = replacementData.gsub("DEVELOPMENT_TEAM = \"$(sigh_BUNDLETOKEN_appstore_team-id)\";","DEVELOPMENT_TEAM = ###;")
  			replacementData = replacementData.gsub("DEVELOPMENT_TEAM = \"$(sigh_BUNDLETOKEN_enterprise_team-id)\";","DEVELOPMENT_TEAM = ###;")
  			replacementData = replacementData.gsub("DEVELOPMENT_TEAM = \"$(sigh_BUNDLETOKEN.###_appstore_team-id)\";","DEVELOPMENT_TEAM = ###;")
  			replacementData = replacementData.gsub("DEVELOPMENT_TEAM = \"$(sigh_BUNDLETOKEN.###_enterprise_team-id)\";","DEVELOPMENT_TEAM = ###;")
  			replacementData = replacementData.gsub("DEVELOPMENT_TEAM = \"$(sigh_BUNDLETOKENWATCHKITEXTENSION_enterprise_team-id)\";","DEVELOPMENT_TEAM = ###;")
  			replacementData = replacementData.gsub("DEVELOPMENT_TEAM = \"$(sigh_BUNDLETOKENWATCHKIT_enterprise_team-id)\";","DEVELOPMENT_TEAM = ###;")

  			replacementData = replacementData.gsub("PRODUCT_BUNDLE_IDENTIFIER = \"###\"","PRODUCT_BUNDLE_IDENTIFIER = \"" + ENV['STORE_IPA'] + ".###\"")
  			replacementData = replacementData.gsub("PRODUCT_BUNDLE_IDENTIFIER = com.store.bundleidentifier","PRODUCT_BUNDLE_IDENTIFIER = " + ENV['STORE_IPA'])
  			replacementData = replacementData.gsub("_appstore","_enterprise")

  		else
  			replacementData = data.gsub("sigh_" + "BUNDLETOKENWATCHKITEXTENSION","sigh_" + ENV['STORE_WATCHKIT_EXTENSION'])
  			replacementData = replacementData.gsub("sigh_" + "BUNDLETOKENWATCHKIT","sigh_" + ENV['STORE_WATCHKIT'])
  			replacementData = replacementData.gsub("sigh_" + "BUNDLETOKEN" + "###","sigh_" + ENV['STORE_IPA'] + ".###")
  			replacementData = replacementData.gsub("sigh_" + "BUNDLETOKEN","sigh_" + ENV['STORE_IPA'])
  			replacementData = replacementData.gsub("PRODUCT_BUNDLE_IDENTIFIER = \"###\"","PRODUCT_BUNDLE_IDENTIFIER = \"" + ENV['STORE_IPA'] + ".###\"")
  			replacementData = replacementData.gsub("PRODUCT_BUNDLE_IDENTIFIER = com.store.bundleidentifier","PRODUCT_BUNDLE_IDENTIFIER = " + ENV['STORE_IPA'])
  		end

  		if (ENV['URBAN_AIRSHIP_PROD_KEY'].length > 0 && ENV['URBAN_AIRSHIP_PROD_KEY'] != "{UA_PROD_KEY}")
  			replacementData = replacementData.gsub("com.apple.Push = {
								enabled = 0;
							};","com.apple.Push = {
								enabled = 1;
							};")
  		end

  		File.open("../###.xcodeproj/project.pbxproj", "w") do |f|
 	 		f.write(replacementData)
		  end

  		plist environment:"store"
      number = options[:version_number]
      offset = ENV['VERSION_NUMBER_OFFSET']
      if (offset != nil && offset.length > 0)
        slice = number[0,4].to_i
        slice += offset.to_i
        number[0,4] = slice.to_s
      end
  		increment_build_number(build_number: options[:build_number])
  		increment_version_number(version_number: number)
  		branding environment:"prod"

  		# match is appstore expect for demo, which is enterprise
  		if (ENV['###'].downcase == "true")
  			gym(
  				scheme: "###",
  				output_name: "###" + ENV['BUILD_SUFFIX'],
  				output_directory: "./build/" + ENV['BUILD_SUFFIX'] +  "/downloads",
  				export_method: "enterprise"
  			)
  		else
  			match(
  				app_identifier: ENV['STORE_IPA']
  			)

  			# Match for Today Extension
  			produce(
  				app_identifier: ENV['STORE_IPA'] + "###",
  				username: ENV['MATCH_USERNAME'],
  				skip_itc: true,
  				app_name: ENV['TEAM_NAME'] + " Today Widget"
  			)
  			match(
  				app_identifier: ENV['STORE_IPA'] + "###"
  			)

  			# match for wearables targets
  			if (ENV['WATCH_ENABLED'].downcase == "true")
  				match(
  					app_identifier: ENV['STORE_WATCHKIT']
  				)

  				match(
  					app_identifier: ENV['STORE_WATCHKIT_EXTENSION']
  				)
  			end

  			gym(
  				scheme: "###",
  				output_name: "###" + ENV['BUILD_SUFFIX'],
  				output_directory: "./build/" + ENV['BUILD_SUFFIX'] +  "/downloads",
  				export_method: "app-store"
  			)
  		end

  		###
  		if (ENV['###'].downcase == "true")
  			puts "###, generating download page"
  			download_page environment:"store"
  		end
      #firebase environment:"Store"

		# Deliver to the store if option is selected
		if (options[:submit].upcase == "YES" && ENV['IS_DEMO_TARGET'].downcase != "true")
			puts "App Store Delivery Beginning..."
			puts "Downloading App Metadata from iTunes Connect"
			deliverCommand = "DELIVER_FORCE_OVERWRITE=true fastlane deliver download_metadata -u " + ENV['MATCH_USERNAME'] + " -a " + ENV['STORE_IPA']
			sh deliverCommand

			# Copy the nm notes file from the ###/Fastlane/ReleaseNotes directory
			if (File.exist?("../fastlane/ReleaseNotes/release_notes.txt"))
  				puts "Release Notes text file found, copying..."
  				FileUtils.cp_r Dir.glob("../fastlane/ReleaseNotes/release_notes.txt"), "../fastlane/metadata/en-US", :verbose => true, :remove_destination => true
  		end

        # Optional - Date in milliseconds for automatically releasing on pending approval
        # Cannot be used with Auto_Release, so set Auto_Release to false
        if (options[:release_date].to_s.empty? == false)
          ENV['DELIVER_RELEASE_DATE'] = options[:release_date]
          deliver(
          app_version: options[:version_number],
          submit_for_review: true,
          force: true,
          app_identifier: ENV['STORE_IPA'],
          username: ENV['MATCH_USERNAME'],
          auto_release_date: ENV['DELIVER_RELEASE_DATE']
        )
        else
          # Deliver the apps to the store and submit for review
          ENV['DELIVER_AUTO_RELEASE'] = (options[:release_type].upcase == "IMMEDIATE" ? "true" : "false")
          deliver(
          app_version: options[:version_number],
          submit_for_review: true,
          force: true,
          app_identifier: ENV['STORE_IPA'],
          username: ENV['MATCH_USERNAME'],
          automatic_release: ENV['DELIVER_AUTO_RELEASE']
        )
        end
      end
	else
  		puts "Store IPA not defined, skipping..."
      UI.user_error!(options[:client].upcase + " does not have a Store IPA defined.")
  	end
  end

 
 

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.152.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.1.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.3.0        |
| slack-notifier                            | 2.3.2        |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| terminal-notifier                         | 2.0.0        |
| terminal-table                            | 1.8.0        |
| plist                                     | 3.5.0        |
| public_suffix                             | 2.0.5        |
| addressable                               | 2.7.0        |
| multipart-post                            | 2.0.0        |
| word_wrap                                 | 1.0.0        |
| babosa                                    | 1.0.3        |
| colored                                   | 1.2          |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.6        |
| fastimage                                 | 2.1.7        |
| gh_inspector                              | 1.1.3        |
| rubyzip                                   | 2.3.0        |
| security                                  | 0.1.3        |
| xcpretty-travis-formatter                 | 1.0.0        |
| dotenv                                    | 2.7.5        |
| bundler                                   | 1.17.2       |
| jwt                                       | 2.1.0        |
| uber                                      | 0.1.0        |
| declarative-option                        | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| mini_mime                                 | 1.0.2        |
| httpclient                                | 2.8.3        |
| google-api-client                         | 0.38.0       |
| emoji_regex                               | 1.0.1        |
| nanaimo                                   | 0.2.6        |
| colored2                                  | 3.1.2        |
| claide                                    | 1.0.3        |
| CFPropertyList                            | 3.0.2        |
| atomos                                    | 0.1.3        |
| xcodeproj                                 | 1.17.0       |
| unicode-display_width                     | 1.7.0        |
| tty-screen                                | 0.8.0        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| excon                                     | 0.75.0       |
| faraday                                   | 0.17.3       |
| unf_ext                                   | 0.0.7.7      |
| faraday_middleware                        | 0.13.1       |
| json                                      | 2.3.0        |
| mini_magick                               | 4.10.1       |
| naturally                                 | 2.2.0        |
| simctl                                    | 1.6.8        |
| declarative                               | 0.0.20       |
| multi_json                                | 1.14.1       |
| signet                                    | 0.14.0       |
| os                                        | 1.1.0        |
| memoist                                   | 0.16.2       |
| googleauth                                | 0.13.0       |
| digest-crc                                | 0.5.1        |
| google-cloud-errors                       | 1.0.1        |
| google-cloud-env                          | 1.3.2        |
| google-cloud-core                         | 1.5.0        |
| google-cloud-storage                      | 1.26.2       |
| aws-eventstream                           | 1.1.0        |
| aws-sigv4                                 | 1.2.1        |
| aws-partitions                            | 1.336.0      |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.102.1      |
| aws-sdk-kms                               | 1.35.0       |
| aws-sdk-s3                                | 1.72.0       |
| forwardable                               | 1.2.0        |
| logger                                    | 1.3.0        |
| stringio                                  | 0.0.2        |
| ipaddr                                    | 1.2.2        |
| openssl                                   | 2.1.2        |
| ostruct                                   | 0.1.0        |
| strscan                                   | 1.0.0        |
| date                                      | 2.0.0        |
| fileutils                                 | 1.1.0        |
| etc                                       | 1.0.1        |
| io-console                                | 0.4.7        |
| zlib                                      | 1.0.0        |
| mini_portile2                             | 2.4.0        |
| nokogiri                                  | 1.10.7       |
| rexml                                     | 3.1.9        |
| psych                                     | 3.1.0        |
| mutex_m                                   | 0.1.0        |
| webrick                                   | 1.4.2        |
| fastlane-plugin-firebase_app_distribution | 0.1.4        |
</details>

*generated on:* **2020-07-17**
</details>
-->

<details>
  <pre> [all details are at the bottom of #16645 ] </pre>

```fastlane installation at path:
/usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.152.0/bin/fastlane
-----------------------------
[✔] 🚀 
fastlane 2.152.0
ALK-C07Z22QMJYW0:fastlane jenkins$ 

heres what my submission_information currently looks like inside my DeilverFile:

```
submission_information({
	export_compliance_available_on_french_store: false,
	export_compliance_ccat_file: false,
	export_compliance_contains_proprietary_cryptography: false,
	export_compliance_contains_third_party_cryptography: false,
	export_compliance_is_exempt: true,
	export_compliance_uses_encryption: true,
	export_compliance_app_type: "ios",
	export_compliance_encryption_updated: true,
	export_compliance_compliance_required: true,
	export_compliance_platform: true,
	add_id_info_uses_idfa: false
})
```
</details>

**Comment by scottasoutherland** [comment]
I'm also having this problem despite providing almost all of the export options

```
| submission_information.export_compliance_platform                          | ios                                                                                 |
| submission_information.export_compliance_compliance_required               | false                                                                               |
| submission_information.export_compliance_encryption_updated                | false                                                                               |
| submission_information.export_compliance_uses_encryption                   | true                                                                                |
| submission_information.export_compliance_is_exempt                         | true                                                                                |
| submission_information.export_compliance_contains_third_party_cryptography | true                                                                                |
| submission_information.export_compliance_contains_proprietary_cryptography | false                                                                               |
| submission_information.export_compliance_available_on_french_store         | false                                                                               |
| submission_information.add_id_info_serves_ads                              | false                                                                               |
| submission_information.add_id_info_tracks_action                           | true                                                                                |
| submission_information.add_id_info_tracks_install                          | true                                                                                |
| submission_information.add_id_info_limits_tracking                         | true                                                                                |
| submission_information.add_id_info_uses_idfa                               | true    
```

**Comment by randyvarela5** [comment]
adding `ITSAppUsesNonExemptEncryption`  and setting it to `NO` fixed this issue for me.  Its mentioned in the docs that it can be added as an option but its definitely required for me:

https://developer.apple.com/documentation/bundleresources/information_property_list/itsappusesnonexemptencryption

```
submission_information({
	export_compliance_uses_encryption: true,
	add_id_info_uses_idfa: false
})
```

**Comment by scottasoutherland** [comment]
Yes, the workaround seems to work for me as well, but i'm confused on why it's needed at all.

**Comment by randyvarela5** [comment]
me too. I thought for sure passing in all the parameters in, even ones that would not apply, would be overkill, but i guess not.

**Comment by ppamorim** [comment]
@randyvarela5 `ITSAppUsesNonExemptEncryption` set to  `NO` is not working for me.

**Comment by randyvarela5** [comment]
@ppamorim whats the error youre getting?

**Comment by ppamorim** [comment]
@randyvarela5 I can't replicate because I fixed the apps manually but it's the same error:

```
The provided entity is missing a required attribute - You must provide a value for the attribute 'usesNonExemptEncryption' with this request
```

To replicate the issue you need:

 - Have your apps without any exempt encryption configuration set (also no flag added in the info pList)

**Comment by randyvarela5** [comment]
@ppamorim what im doing to test is just incrementing the build number and running my app submission job, then when it fails, test changes out with `fastlane deliver` then just cancel the review if it submits successfully.

I also noticed that you have `submission_info = ` where I have `submission_information` maybe try that next time.
