### ISSUE TITLE
[Deliver][Submit] fastlane has already Submit for review success, but fastlane deliver returns failed

### ISSUE THREAD

**Issue by superatomu** [fastlane/fastlane#16918]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I read the Contribution Guidelines
- [x] I read docs.fastlane.tools
- [x] I searched for existing GitHub issues

### Issue Description
1.before we submit, the app store version state is **METADATA_REJECTED**
2.then we revise the metadata and use fastlane deliver to upload **a new build**
3.fastlane returns failed, but actually it has submit for review **success**.
4.the app store state is **WAITING_FOR_REVIEW** now.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.4                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.21.0 (Apple Git-122.2)        |
| Installation Source         | ~/.rvm/gems/ruby-2.4.0/bin/fastlane         |
| Host                        | Mac OS X 10.14.4 (18E224)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.3                                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
desc "submit build to appstore"
  lane :submit_review do |options|
    puts "begin"
    deliver(
        username: options[:username],
        app_identifier: options[:bundle_id],
        team_id: options[:team_id], 
        ipa: options[:ipa_name],
        force: true,
        skip_screenshots: true,
        skip_metadata: true,
        submit_for_review: true,
        automatic_release: false,
        phased_release: true,
        reset_ratings: false,
        reject_if_possible: true,
        submission_information: {
            add_id_info_limits_tracking: true,
            add_id_info_tracks_install: true,
            add_id_info_uses_idfa: true
        }
    )
    puts "end"
  end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.152.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 2.0.2        |
| rake                      | 13.0.1       |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 4.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.344.0      |
| aws-sigv4                 | 1.2.1        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.104.2      |
| aws-sdk-kms               | 1.36.0       |
| aws-sdk-s3                | 1.75.0       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.0.0        |
| excon                     | 0.75.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.17.3       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.14.0       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.2.1        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.0        |
| signet                    | 0.14.0       |
| googleauth                | 0.13.0       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.2       |
| json                      | 2.3.1        |
| mini_magick               | 4.10.1       |
| plist                     | 3.5.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.17.1       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2020-07-23**
</details>

### Environment
<details>

+----------------------------------------------------+------------------------+
|                           deliver 2.152.0 Summary                           |
+----------------------------------------------------+------------------------+
| username                                           | ******     |
| app_identifier                                     | ******       |
| team_id                                            |******                 |
| ipa                                                | ******       |
| force                                              | true                   |
| skip_screenshots                                   | true                   |
| skip_metadata                                      | true                   |
| submit_for_review                                  | true                   |
| automatic_release                                  | false                  |
| phased_release                                     | true                   |
| reset_ratings                                      | false                  |
| reject_if_possible                                 | true                   |
| submission_information.add_id_info_limits_tracking | true                   |
| submission_information.add_id_info_tracks_install  | true                   |
| submission_information.add_id_info_uses_idfa       | true                   |
| screenshots_path                                   | ./fastlane/screenshots |
| metadata_path                                      | ./fastlane/metadata    |
| app_version                                        | 7.6.21                 |
| platform                                           | ios                    |
| edit_live                                          | false                  |
| use_live_version                                   | false                  |
| skip_binary_upload                                 | false                  |
| skip_app_version_update                            | false                  |
| overwrite_screenshots                              | false                  |
| run_precheck_before_submit                         | true                   |
| precheck_default_rule_level                        | warn                   |
| ignore_language_directory_validation               | false                  |
| precheck_include_in_app_purchases                  | true                   |
+----------------------------------------------------+------------------------+
</details>

### Log Information

<details>
INFO [2020-07-23 18:04:47.34]: Waiting for App Store Connect to finish processing the new build (7.6.21 - 2410) for IOS
INFO [2020-07-23 18:05:04.87]: Waiting for App Store Connect to finish processing the new build (7.6.21 - 2410) for IOS
INFO [2020-07-23 18:05:21.87]: Waiting for App Store Connect to finish processing the new build (7.6.21 - 2410) for IOS
INFO [2020-07-23 18:05:38.37]: Waiting for App Store Connect to finish processing the new build (7.6.21 - 2410) for IOS
INFO [2020-07-23 18:05:55.63]: Waiting for App Store Connect to finish processing the new build (7.6.21 - 2410) for IOS
INFO [2020-07-23 18:06:12.43]: Successfully finished processing the build 7.6.21 - 2410 for IOS
INFO [2020-07-23 18:06:12.44]: Selecting build 7.6.21 (2410)...
INFO [2020-07-23 18:06:19.85]: Successfully selected build
DEBUG [2020-07-23 18:06:24.27]: Updating app store version for IDFA status of 'true'
DEBUG [2020-07-23 18:06:27.41]: Updated app store version for IDFA status of 'true'
DEBUG [2020-07-23 18:06:27.41]: Updating IDFA declaration
DEBUG [2020-07-23 18:06:31.94]: Updated IDFA declaration
INFO [2020-07-23 18:06:31.94]: Successfully updated IDFA declarations on App Store Connect
Timeout received! Retrying after 3 seconds (remaining: 4)...
WARN [2020-07-23 18:07:46.44]: Lane Context:
INFO [2020-07-23 18:07:46.44]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"submit_review"}
ERROR [2020-07-23 18:07:46.44]: **The request cannot be fulfilled because of the state of another resource. - Submit for review errors found.
Invalid submission state. - The version's state is not suitable for submission: Waiting for Review**

ERROR [2020-07-23 18:07:46.46]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: The request cannot be fulfilled because of the state of another resource. - Submit for review errors found.
Invalid submission state. - The version's state is not suitable for submission: Waiting for Review

URL: https://api.github.com/search/issues?q=The%20request%20cannot%20be%20fulfilled%20because%20of%20the%20state%20of%20another%20resource.%20-%20Submit%20for%20review%20errors%20found.%0AInvalid%20submission%20state.%20-%20The%20version%27s%20state%20is%20not%20suitable%20for%20submission%3A%20Waiting%20for%20Review+repo:fastlane/fastlane
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Users/ciserver/.rvm/gems/ruby-2.4.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/connect_api/client.rb:163:in `handle_response': [!] The request cannot be fulfilled because of the state of another resource. - Submit for review errors found. (Spaceship::UnexpectedResponse)
Invalid submission state. - The version's state is not suitable for submission: Waiting for Review
	from /Users/ciserver/.rvm/gems/ruby-2.4.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/connect_api/client.rb:99:in `post'
	from /Users/ciserver/.rvm/gems/ruby-2.4.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:816:in `post_app_store_version_submission'
	from /Users/ciserver/.rvm/gems/ruby-2.4.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/connect_api/models/app_store_version.rb:154:in `create_app_store_version_submission'
	from /Users/ciserver/.rvm/gems/ruby-2.4.0/gems/fastlane-2.152.0/deliver/lib/deliver/submit_for_review.rb:28:in `submit!'
	from /Users/ciserver/.rvm/gems/ruby-2.4.0/gems/fastlane-2.152.0/deliver/lib/deliver/runner.rb:176:in `submit_for_review'
	from /Users/ciserver/.rvm/gems/ruby-2.4.0/gems/fastlane-2.152.0/deliver/lib/deliver/runner.rb:52:in `run'
	from /Users/ciserver/.rvm/gems/ruby-2.4.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:17:in `run'
	from /Users/ciserver/.rvm/gems/ruby-2.4.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
	from /Users/ciserver/.rvm/gems/ruby-2.4.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/ciserver/.rvm/gems/ruby-2.4.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
	from /Users/ciserver/.rvm/gems/ruby-2.4.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/ciserver/.rvm/gems/ruby-2.4.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/ciserver/.rvm/gems/ruby-2.4.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/ciserver/.rvm/gems/ruby-2.4.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:4:in `block in parsing_binding'
	from /Users/ciserver/.rvm/gems/ruby-2.4.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/ciserver/.rvm/gems/ruby-2.4.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/ciserver/.rvm/gems/ruby-2.4.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/ciserver/.rvm/gems/ruby-2.4.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/ciserver/.rvm/gems/ruby-2.4.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/ciserver/.rvm/gems/ruby-2.4.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/ciserver/.rvm/gems/ruby-2.4.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/ciserver/.rvm/gems/ruby-2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/ciserver/.rvm/gems/ruby-2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/ciserver/.rvm/gems/ruby-2.4.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/ciserver/.rvm/gems/ruby-2.4.0/gems/fastlane-2.152.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/ciserver/.rvm/gems/ruby-2.4.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/ciserver/.rvm/gems/ruby-2.4.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	from /Users/ciserver/.rvm/gems/ruby-2.4.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/ciserver/.rvm/gems/ruby-2.4.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Users/ciserver/.rvm/gems/ruby-2.4.0/gems/fastlane-2.152.0/bin/fastlane:23:in `<top (required)>'
	from /Users/ciserver/.rvm/gems/ruby-2.4.0/bin/fastlane:23:in `load'
	from /Users/ciserver/.rvm/gems/ruby-2.4.0/bin/fastlane:23:in `<main>'
	from /Users/ciserver/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:24:in `eval'
	from /Users/ciserver/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:24:in `<main>'
Build step '执行 shell' marked build as failure
</details>

**Comment by sonjz** [comment]
noticed similar on 2.153.0.
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                    |
| --------------------------- | -------------------------------------------------------- |
| OS                          | 10.15.5                                                  |
| Ruby                        | 2.7.1                                                    |
| Bundler?                    | true                                                     |
| Git                         | git version 2.24.1 (Apple Git-126)                       |
| Installation Source         | ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bin/fastlane |
| Host                        | Mac OS X 10.15.5 (19F101)                                |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.1/lib                              |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                              |
| Is contained                | false                                                    |
| Is homebrew                 | false                                                    |
| Is installed via Fabric.app | false                                                    |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/              |
| Xcode Version               | 11.4                                                     |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.153.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| bundler                   | 2.1.4        |
| uri                       | 0.10.0       |
| rake                      | 13.0.1       |
| CFPropertyList            | 3.0.2        |
| concurrent-ruby           | 1.1.6        |
| i18n                      | 1.8.5        |
| minitest                  | 5.14.1       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.7        |
| zeitwerk                  | 2.4.0        |
| activesupport             | 6.0.3.2      |
| public_suffix             | 4.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.345.0      |
| aws-sigv4                 | 1.2.1        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.104.3      |
| aws-sdk-kms               | 1.36.0       |
| aws-sdk-s3                | 1.75.0       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.1        |
| dogstatsd-ruby            | 4.8.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.0.0        |
| excon                     | 0.75.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 1.0.1        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.2.1        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.0        |
| signet                    | 0.14.0       |
| googleauth                | 0.13.0       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.2       |
| json                      | 2.3.1        |
| mini_magick               | 4.10.1       |
| plist                     | 3.5.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.17.1       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| gli                       | 2.19.2       |
| hashie                    | 4.1.0        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.10      |
| url_escape                | 2009.06.24   |
| rack_fast_escape          | 2009.06.24   |
| picky                     | 4.31.3       |
| pidfile                   | 0.3.0        |
| require_all               | 3.0.0        |
| websocket-extensions      | 0.1.5        |
| websocket-driver          | 0.7.3        |
| slack-ruby-client         | 0.14.6       |
| thor                      | 1.0.1        |
| xml-simple                | 1.1.5        |
</details>


*generated on:* **2020-07-24**
</details>


```
The request cannot be fulfilled because of the state of another resource. - Submit for review errors found.
```

**Comment by joshdholtz** [comment]
@superatomu Thanks for reporting that! I have no encountered an app in that state with those issues so I will look into this 🤔 

@sonjz Do you happen to have any more of the output with that error? 😇 That rest of the output and stacktrace is super helpful!

**Comment by sonjz** [comment]
```
Successfully loaded '/Users/xxx/yyy/zzz/Deliverfile' 📄
deliver 2.153.0 Summary
Successfully set the version to '2020.7.24'
Will begin uploading metadata for '2020.7.24' on App Store Connect
Will begin uploading snapshots for '2020.7.24' on App Store Connect
Number of screenshots not deleted: 0
Will wait for screenshot image processing
Set env DELIVER_SKIP_WAIT_FOR_SCREENSHOT_PROCESSING=true to skip waiting for screenshots to process
Successfully uploaded screenshots to App Store Connect
Price Tier unchanged (tier 0)
This might take a few minutes. Please don't interrupt the script.
iTunes Transporter successfully finished its job
--------------------------------------------------------------------
Successfully uploaded package to App Store Connect. It might take a few minutes until it's visible online.
--------------------------------------------------------------------
Finished the upload to App Store Connect
Summary for precheck 2.153.0
precheck 👮‍♀️ 👮  finished without detecting any potential problems 🛫
Read more information on why this build isn't showing up yet - https://github.com/fastlane/fastlane/issues/14997
Successfully finished processing the build 2020.7.24 - 106 for IOS
Successfully selected build
Successfully updated IDFA declarations on App Store Connect
Successfully updated contents rights declaration on App Store Connect
bundler: failed to load command: fastlane (/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bin/fastlane)
Spaceship::UnexpectedResponse: [31m[!] The request cannot be fulfilled because of the state of another resource. - Submit for review errors found.
An unexpected error occurred - Unexpected error while submitting version.
  /Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.153.0/spaceship/lib/spaceship/connect_api/client.rb:163:in `handle_response'
  /Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.153.0/spaceship/lib/spaceship/connect_api/client.rb:99:in `post'
  /Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.153.0/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:825:in `post_app_store_version_submission'
  /Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.153.0/spaceship/lib/spaceship/connect_api/models/app_store_version.rb:155:in `create_app_store_version_submission'
  /Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.153.0/deliver/lib/deliver/submit_for_review.rb:26:in `submit!'
  /Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.153.0/deliver/lib/deliver/runner.rb:171:in `submit_for_review'
  /Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.153.0/deliver/lib/deliver/runner.rb:52:in `run'
  /Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.153.0/deliver/lib/deliver/commands_generator.rb:81:in `block (2 levels) in run'
  /Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.153.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.153.0/deliver/lib/deliver/commands_generator.rb:186:in `run'
  /Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.153.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
  /Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.153.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
  /Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.153.0/bin/fastlane:23:in `<top (required)>'
  /Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bin/fastlane:23:in `load'
  /Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bin/fastlane:23:in `<top (required)>'
```

**Comment by joshdholtz** [comment]
@sonjz I kind of wish the error returned by the App Store Connect API there had some info 😔 Right now it shows `The request cannot be fulfilled because of the state of another resource. - Submit for review errors found`. 

I'm going to do some digging to see if we can pull some more info from that error response 🤔 

Would you be able to go to the App Store Connect website and try and submit the app from there? I would like to know what errors the website is telling you?

**Comment by sonjz** [comment]
@joshdholtz hmm, i did exactly that 3 days ago after i received the error, and from what I recall, I was able to submit it for review without any issues or further manual edits.

i have received over a dozen similar apps since, and haven't seen the issue again.

i can comment here or reference this ticket if i see the issue again.

**Comment by joshdholtz** [comment]
That would be great if you could comment here if you see the issue again! Thanks for updating me ❤

**Comment by camilape** [comment]
Hi @joshdholtz I got a similar issue, I tried to upload screenshots this time and first I received the following error:

`[09:11:53]: Error processing screenshot '1_iPad Pro (12.9-inch) (2nd generation).png'. IMAGE_BAD_FILE_EXTENSION - IMAGE_BAD_FILE_EXTENSION` 

Then when I tried to resubmit again skipping the screenshots upload I got this error:

`The request cannot be fulfilled because of the state of another resource. - Submit for review errors found.
An attribute value is invalid. - Using advertising identifiers requires that you select the limits ad tracking option.
Idfa violation.
Screenshot uploads still in progress. - There are still screenshot uploads in progress.`

Could you please provide more information about it? I'm running on Fastlane 2.154.0

**Comment by joshdholtz** [comment]
@camilape Thanks for all the info!

>[09:11:53]: Error processing screenshot '1_iPad Pro (12.9-inch) (2nd generation).png'. IMAGE_BAD_FILE_EXTENSION - IMAGE_BAD_FILE_EXTENSION

This error comes from the App Store Connect API. Can you verify that your `png` actually is a `png`? I think the App Store Connect API verifies the content and maybe its actually a jpeg? 🤔 

>Using advertising identifiers requires that you select the limits ad tracking option. Idfa violation.

App Store Connect requires a bunch more info now. It looks like you may be missing `add_id_info_limits_tracking` in your `submission_information` (if `true` you need the other ones below it too)

```rb
submission_information: {
  export_compliance_uses_encryption: false,
  content_rights_contains_third_party_content: false,
  add_id_info_limits_tracking: false,
  add_id_info_serves_ads: false,
  add_id_info_tracks_action: false,
  add_id_info_tracks_install: false,
  add_id_info_uses_idfa: false
}
```
>Screenshot uploads still in progress. - There are still screenshot uploads in progress

I think this is related to the first issue with bad file extension. Once all your screenshots get uploaded successfully this should go away. You may want to run with `overwrite_screenshots: true` which will completely delete and rue-load all screenshots. It will remove all screenshots that are "still in progress".

**Comment by camilape** [comment]
@joshdholtz I'm going to try that, thank you so much for the quick reply.

**Comment by joshdholtz** [comment]
@camilape Did this end up working for you? 😊

**Comment by camilape** [comment]
@joshdholtz yes it worked, basically I was missing some additional submission_information, and you were right the screenshots were jpeg instead of png 🤦🏽‍♀️ It seems that Apple has more review policies now. Thank you so much for your help!
