### ISSUE TITLE
Cert taking much longer after recent updates

### ISSUE THREAD

**Issue by nesfahani** [fastlane/fastlane#16923]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
when running cert to create new certificates, it used to take a few minutes and now it takes between 10-20 minutes

our keychain does have a couple thousand entries, but as I said it would not take this long before, any ideas or similar experience?

##### Command executed
    cert(development: true, keychain_path: "xx/keychain-db")

##### Complete output when running fastlane, including the stack trace and command used

```
[11:55:57]: Starting login with user ''
[11:55:58]: Successfully logged in
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
[11:56:22]: Certificate XXXXXX (Development) can't be found on your local computer

(IN A LOOP)

[12:02:01]: Couldn't find an existing certificate... creating a new one
[12:02:10]: Using keychain password from keychain item fastlane_keychain_login2 in /xx/keychain-db
[✔] Setting key partition list... (this can take a minute if there are a lot of keys installed) 
[12:04:45]: Using keychain password from keychain item fastlane_keychain_login2 in /xx/login2.keychain-db
[✔] Setting key partition list... (this can take a minute if there are a lot of keys installed) 
[12:07:18]: Successfully generated XXXXXX which was imported to the local machine.
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
[12:07:43]: Verifying the certificate is properly installed locally...
[12:07:43]: Successfully installed certificate XXXXX
[12:07:43]: Use signing certificate ‘XXXX’ from now on!


+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 3    | xcversion                  | 0           |
| 4    | cert                       | 706         |
+------+----------------------------+-------------+
```

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by joshdholtz** [comment]
@nesfahani Thanks for reporting this! I’ve been seeing this too and its on my list of things to look at 😊
