### ISSUE TITLE
Spaceship: old script don't run anymore / new App Store Connect API? 

### ISSUE THREAD

**Issue by fishandphil** [fastlane/fastlane#16939]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information
- Breaking version: 2.152.0
- Last working version: Before App Store Connect was updated 

##### Complete output when running fastlane, including the stack trace and command used

We're running a very basic script which used to work before the App Store Connect update. We've read the documentation and it doesn't seem that things changed on the Fastlane/Spaceship side. 

```
#!/usr/bin/env ruby
require "spaceship"
Spaceship::Tunes.login("xxx@xxx.xxx", "xxx?")
Spaceship::Tunes.select_team
app = Spaceship::Tunes::Application.find(xxx)
v = app.edit_version
v.release_notes["en-US"] = "xxx"
v.save!
```

The save function throws the following error: 

```
Traceback (most recent call last):
	5: from spaceship.rb:34:in `<main>'
	4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/tunes/app_version.rb:412:in `save!'
	3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/tunes/tunes_client.rb:463:in `update_app_version!'
	2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/tunes/tunes_client.rb:1553:in `with_tunes_retry'
	1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/tunes/tunes_client.rb:470:in `block in update_app_version!'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/tunes/tunes_client.rb:228:in `handle_itc_response': Unexpected Error (Spaceship::Tunes::PotentialServerError)
```

Anyone can point us to a solution? It is a very basic operation that we're trying to do here.

Thank you

**Comment by esthor** [comment]
I'm having the same issue on the same line of code

**Comment by valerio-castelli** [comment]
Yes, I'm afraid you can no longer use the `edit_version`. We've changed our workflow to do something along these lines:
```
Spaceship::Tunes.login("xxx@xxx.xxx", "xxx?")
Spaceship::Tunes.select_team
app = Spaceship::ConnectAPI::App.find(<bundle_id>)
app_store_version = app.get_edit_app_store_version
localization = app_store_version.get_app_store_version_localizations(filter: { locale: 'en-US' }, limit: 1).first
localization.update(attributes: { 'whatsNew': "xxx" })
```

**Comment by max-ott** [comment]
```
...
app = Spaceship::Tunes::Application.find(xxx)
v = app.edit_version
...
```

No longer works. Thanks @valerio-castelli for the hint.

**Comment by atitovdev** [comment]
@max-ott well, edit_version no longer works, any suggestion what to with that?

**Comment by max-ott** [comment]
What @valerio-castelli posted should get you going:
```
app = Spaceship::ConnectAPI::App.find(<bundle_id>)
app_store_version = app.get_edit_app_store_version
localization = app_store_version.get_app_store_version_localizations(filter: { locale: 'en-US' }, limit: 1).first
localization.update(attributes: { 'whatsNew': "xxx" })
```

**Comment by patreu22** [comment]
Hey @max-ott 

Did you do anything else to make that snippet work? An app with an up-and-running app that is marked as "Ready for sale" in AppStoreConnect returns a nil for the app_store_version. I updated to the most recent fastlane version 2.159.0.
