### ISSUE TITLE
[Regression] Frameit for Android no longer detects screenshoot language ⇒ No custom fonts

### ISSUE THREAD

**Issue by amitkot** [fastlane/fastlane#16943]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: `2.146.0`
- Last working version: `2.145.0`

### Regression Description
https://github.com/fastlane/fastlane/pull/16316 changed the way in which screenshot detected, but this change does not fit the way Android screenshot files are organised. 
After the PR the screenshot parent folder is checked for the language name, which is then matched against the settings in Framefile.json. This is good for Fastline for iOS which has a rather flat directory structure.
In Android the directory structure is different, with language folder being 3 levels above the screenshot:
```
fastlane/metadata/android/en-US/images/phoneScreenshots/Nexus 6P-Portrait-eventTop.png
fastlane/metadata/android/en-US/images/phoneScreenshots/Nexus 6P-Portrait-profile.png
...
fastlane/metadata/android/en-US/images/sevenInchScreenshots/Nexus 6P-Portrait-eventTop.png
fastlane/metadata/android/en-US/images/sevenInchScreenshots/Nexus 6P-Portrait-profile.png
...
fastlane/metadata/android/iw-IL/images/phoneScreenshots/Nexus 6P-Portrait-eventTop.png
fastlane/metadata/android/iw-IL/images/phoneScreenshots/Nexus 6P-Portrait-profile.png
...
fastlane/metadata/android/iw-IL/images/sevenInchScreenshots/Nexus 6P-Portrait-eventTop.png
fastlane/metadata/android/iw-IL/images/sevenInchScreenshots/Nexus 6P-Portrait-profile.png
...
```

The change in the PR breaks Android compatibility by looking only at the directory above the screenshot: https://github.com/fastlane/fastlane/blob/54d8e84574dc94e0f900250c91da3e661abfaed3/frameit/lib/frameit/screenshot.rb#L126-L128

A simple fix would probably be to revert this change and instead search the 3 directory levels above the screenshot for the name of its language.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>> bundle exec fastlane frameit android --verbose
[✔] 🚀
INFO [2020-07-27 00:07:15.66]: Using device frames version 'latest'
DEBUG [2020-07-27 00:07:15.66]: Parsing config file 'PROJ_PATH/android/fastlane/metadata/android/Framefile.json'
[⠋] Framing screenshot './Nexus 6P-Portrait-profile.png' DEBUG [2020-07-27 00:07:15.72]: Looking for Nexus 6P and found 1 template(s)
[⠴] Framing screenshot './Nexus 6P-Portrait-profile.png' DEBUG [2020-07-27 00:07:17.30]: Falling back to text in Framefile.json as there was nothing specified in the keyword.strings file
[⠦] Framing screenshot './Nexus 6P-Portrait-profile.png' DEBUG [2020-07-27 00:07:18.38]: No custom font specified for ./Nexus 6P-Portrait-profile.png, using the default one
DEBUG [2020-07-27 00:07:18.40]: Adding text 'make it yours'
[⠇] Framing screenshot './Nexus 6P-Portrait-profile.png' DEBUG [2020-07-27 00:07:20.67]: Text for image ./Nexus 6P-Portrait-profile.png is quite long, reducing font size by 36.1%</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                                                       |
| --------------------------- | ------------------------------------------------------------------------------------------- |
| OS                          | 10.14.6                                                                                     |
| Ruby                        | 2.6.6                                                                                       |
| Bundler?                    | true                                                                                        |
| Git                         | git version 2.24.0                                                                          |
| Installation Source         | ~/src/xxx/android/vendor/bundle/ruby/2.6.0/bin/fastlane |
| Host                        | Mac OS X 10.14.6 (18G6020)                                                                  |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.6/lib                                                                 |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                                                                 |
| Is contained                | false                                                                                       |
| Is homebrew                 | false                                                                                       |
| Is installed via Fabric.app | false                                                                                       |
| Xcode Path                  | /Applications/Xcode-11.3.app/Contents/Developer/                                            |
| Xcode Version               | 11.3                                                                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.153.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.1.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.3.0        |
| bundler                                   | 2.0.2        |
| rake                                      | 13.0.1       |
| CFPropertyList                            | 3.0.2        |
| public_suffix                             | 4.0.5        |
| addressable                               | 2.7.0        |
| atomos                                    | 0.1.3        |
| aws-eventstream                           | 1.1.0        |
| aws-partitions                            | 1.345.0      |
| aws-sigv4                                 | 1.2.1        |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.104.3      |
| aws-sdk-kms                               | 1.36.0       |
| aws-sdk-s3                                | 1.75.0       |
| babosa                                    | 1.0.3        |
| claide                                    | 1.0.3        |
| colored                                   | 1.2          |
| colored2                                  | 3.1.2        |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| declarative                               | 0.0.20       |
| declarative-option                        | 0.1.0        |
| digest-crc                                | 0.6.1        |
| unf_ext                                   | 0.0.7.7      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| dotenv                                    | 2.7.6        |
| emoji_regex                               | 3.0.0        |
| excon                                     | 0.75.0       |
| multipart-post                            | 2.0.0        |
| faraday                                   | 1.0.1        |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.6        |
| faraday_middleware                        | 1.0.0        |
| fastimage                                 | 2.2.0        |
| gh_inspector                              | 1.1.3        |
| jwt                                       | 2.2.1        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.0        |
| signet                                    | 0.14.0       |
| googleauth                                | 0.13.0       |
| httpclient                                | 2.8.3        |
| mini_mime                                 | 1.0.2        |
| uber                                      | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| google-api-client                         | 0.38.0       |
| google-cloud-env                          | 1.3.3        |
| google-cloud-errors                       | 1.0.1        |
| google-cloud-core                         | 1.5.0        |
| google-cloud-storage                      | 1.26.2       |
| json                                      | 2.3.1        |
| mini_magick                               | 4.10.1       |
| plist                                     | 3.5.0        |
| rubyzip                                   | 2.3.0        |
| security                                  | 0.1.3        |
| naturally                                 | 2.2.0        |
| simctl                                    | 1.6.8        |
| slack-notifier                            | 2.3.2        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.7.0        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| word_wrap                                 | 1.0.0        |
| nanaimo                                   | 0.3.0        |
| xcodeproj                                 | 1.17.1       |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.0        |
| fastlane-plugin-firebase_app_distribution | 0.1.4        |
</details>

*generated on:* **2020-07-27**
</details></pre>
</details>

**Comment by janpio** [comment]
Ping @bvirlet

**Comment by bvirlet** [comment]
Thanks for reporting this @amitkot, and sorry for the regression.

Maybe we can do the check depending on the platform: if android, go up 3 directories. If ios, go up only 1. @janpio is there an easy way to check if we are running within the context of iOS or Android screenshots?

**Comment by janpio** [comment]
Sorry, no idea. Usually the lanes are split by ios and android, not sure if that always applies though if you e.g. call frameit directly.

**Comment by RobertSasak** [comment]
Issue still exist. Quick fix. Add two "parent" into 
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.154.0/frameit/lib/frameit/screenshot.rb
```
    def language
      @language ||= Pathname.new(path).parent.parent.parent.basename.to_s
    end
```
