### ISSUE TITLE
Error when trying to initialize Deliver.

### ISSUE THREAD

**Issue by kevint727** [fastlane/fastlane#16951]
When running: 

fastlane deliver init

Ruby version is: 2.6.3p62 
Fastlane Version is: 2.153.1

<details>
  <pre>I encounter the following error:

[10:26:50]: Writing to './fastlane/metadata/en-US/name.txt'
[10:26:50]: Writing to './fastlane/metadata/en-US/subtitle.txt'
[10:26:50]: Writing to './fastlane/metadata/en-US/privacy_url.txt'
[10:26:50]: Writing to './fastlane/metadata/en-US/apple_tv_privacy_policy.txt'
[10:26:50]: Writing to './fastlane/metadata/en-US/description.txt'
[10:26:50]: Writing to './fastlane/metadata/en-US/keywords.txt'
[10:26:50]: Writing to './fastlane/metadata/en-US/release_notes.txt'
[10:26:50]: Writing to './fastlane/metadata/en-US/support_url.txt'
[10:26:50]: Writing to './fastlane/metadata/en-US/marketing_url.txt'
[10:26:50]: Writing to './fastlane/metadata/en-US/promotional_text.txt'
[10:26:50]: Writing to './fastlane/metadata/primary_category.txt'
[10:26:50]: Writing to './fastlane/metadata/secondary_category.txt'
[10:26:50]: Writing to './fastlane/metadata/primary_first_sub_category.txt'
[10:26:50]: Writing to './fastlane/metadata/primary_second_sub_category.txt'
[10:26:50]: Writing to './fastlane/metadata/secondary_first_sub_category.txt'
[10:26:50]: Writing to './fastlane/metadata/secondary_second_sub_category.txt'
[10:26:50]: Writing to './fastlane/metadata/copyright.txt'
[10:26:51]: Writing to './fastlane/metadata/review_information/review_first_name.txt'
[10:26:51]: Writing to './fastlane/metadata/review_information/review_last_name.txt'
[10:26:51]: Writing to './fastlane/metadata/review_information/review_phone_number.txt'
[10:26:51]: Writing to './fastlane/metadata/review_information/review_email.txt'
[10:26:51]: Writing to './fastlane/metadata/review_information/review_demo_user.txt'
[10:26:51]: Writing to './fastlane/metadata/review_information/review_demo_password.txt'

Looking for related GitHub issues on fastlane/fastlane...

➡️  deliver download_metadata: [!] undefined method `+' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/16949 [open] 0 💬
    4 hours ago

➡️  fastlane env crashes with undefined method `strip' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/16748 [open] 1 💬
    3 weeks ago

➡️  [Swift] undefined method `each' for nil:NilClass - Cannot Create Group Within FastlaneSwiftRunner Project
    https://github.com/fastlane/fastlane/issues/15184 [open] 37 💬
    2 weeks ago

and 446 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60%2B%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	16: from /usr/local/bin/fastlane:23:in `<main>'
	15: from /usr/local/bin/fastlane:23:in `load'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.153.1/bin/fastlane:23:in `<top (required)>'
	13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.153.1/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.153.1/deliver/lib/deliver/commands_generator.rb:17:in `start'
	11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.153.1/deliver/lib/deliver/commands_generator.rb:186:in `run'
	10: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.153.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 8: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 7: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 6: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.153.1/deliver/lib/deliver/commands_generator.rb:118:in `block (2 levels) in run'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.153.1/deliver/lib/deliver/setup.rb:21:in `run'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.153.1/deliver/lib/deliver/setup.rb:49:in `generate_deliver_file'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.153.1/deliver/lib/deliver/setup.rb:131:in `generate_metadata_files'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.153.1/deliver/lib/deliver/setup.rb:131:in `each'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.153.1/deliver/lib/deliver/setup.rb:137:in `block in generate_metadata_files': undefined method `+' for nil:NilClass (NoMethodError)
	16: from /usr/local/bin/fastlane:23:in `<main>'
	15: from /usr/local/bin/fastlane:23:in `load'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.153.1/bin/fastlane:23:in `<top (required)>'
	13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.153.1/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.153.1/deliver/lib/deliver/commands_generator.rb:17:in `start'
	11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.153.1/deliver/lib/deliver/commands_generator.rb:186:in `run'
	10: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.153.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 8: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 7: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 6: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.153.1/deliver/lib/deliver/commands_generator.rb:118:in `block (2 levels) in run'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.153.1/deliver/lib/deliver/setup.rb:21:in `run'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.153.1/deliver/lib/deliver/setup.rb:49:in `generate_deliver_file'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.153.1/deliver/lib/deliver/setup.rb:131:in `generate_metadata_files'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.153.1/deliver/lib/deliver/setup.rb:131:in `each'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.153.1/deliver/lib/deliver/setup.rb:137:in `block in generate_metadata_files': [!] undefined method `+' for nil:NilClass (NoMethodError) </pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.6                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.6 (19G73)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.6                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform(:ios)

platform :ios do

ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "180"
ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "180"


desc "Create new deliverTest"
  lane :deliverTest do |options|
	startEnv = options[:startEnv]
	errorLog = Array.new
	def execute_for_all_envs(theEnv)
    		schemeList = Dir.glob(".env.*")
		schemeList = schemeList.sort
		if theEnv == nil 
			schemeList.each do |file|
      				Dotenv.overload(file)
      				yield
			end
   		else
			startIndex = schemeList.index(".env." + theEnv)
			schemeList = schemeList.drop(startIndex)
    			schemeList.each do |file|
      				Dotenv.overload(file)
     		 		yield
    			end
  		end
	end
  if ENV['SCHEME'] != nil
	begin
    		get_certificates(
    			username: "******",
			keychain_password: "********",
			team_name:ENV["FASTLANE_ITC_TEAM_NAME"],
			generate_apple_certs: true

		)
	rescue => ex
		d = DateTime.now		
		errorLog << (ENV['SCHEME'] + ":")
		errorLog << d.strftime("%m/%d/%Y %H:%M")
		errorLog << ex
		errorLog << "------------------------------------------------------"
		errorLog << "\n"
		
	end
  	
	begin
    		gym
	rescue => ex
		d = DateTime.now		
		errorLog << (ENV['SCHEME'] + ":")
		errorLog << d.strftime("%m/%d/%Y %H:%M")
		errorLog << ex
		errorLog << "------------------------------------------------------"
		errorLog << "\n"
	end
	begin
    		#upload_to_testflight(
    		#	changelog: "TestFlight deployment",
    		#	skip_waiting_for_build_processing: false
    	#)
	deliver(
	  		submit_for_review: false,
			force: true, 
    skip_metadata: false,
    skip_screenshots: true
		)
	rescue => ex
		d = DateTime.now		
		errorLog << (ENV['SCHEME'] + ":")
		errorLog << d.strftime("%m/%d/%Y %H:%M")
		errorLog << ex
		errorLog << "------------------------------------------------------"
		errorLog << "\n"
	end
    
  else 
  	execute_for_all_envs( startEnv ){deliverTest}
  end
	d = DateTime.now
	open('ErrorLog.out', 'a') { |f|
		#f.puts (d.strftime("%m/%d/%Y %H:%M"))
  		#f.puts "Error log:"
		f.puts "\n"
		f.puts (errorLog.join("\n"))
	}
  	#puts("Error log:")
	#puts(errorLog.join("\n"))
  end  
  
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
#app_identifier(ENV['BUNDLE_IDENTIFIER']) # The bundle identifier of your app

#apple_id(ENV['FASTLANE_USER'])
#team_name(ENV['FASTLANE_ITC_TEAM_NAME'])



#apple_id("*****") # Your Apple email address
#team_name ("****")
#user_name ("******")

#team_name(ENV['FASTLANE_ITC_TEAM_NAME'])
#username(ENV['FASTLANE_USER'])
#apple_id(ENV['FASTLANE_USER'])

#apple_id "*****"
#apple_id(ENV['FASTLANE_USER'])
#team_name(ENV['FASTLANE_ITC_TEAM_NAME'])
#team_name "******"

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile


```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.153.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-versioning | 0.4.3   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version      |
| -------------------------- | ------------ |
| did_you_mean               | 1.3.0        |
| slack-notifier             | 2.3.2        |
| rouge                      | 2.0.7        |
| xcpretty                   | 0.3.0        |
| terminal-notifier          | 2.0.0        |
| unicode-display_width      | 1.7.0        |
| terminal-table             | 1.8.0        |
| plist                      | 3.5.0        |
| public_suffix              | 4.0.5        |
| addressable                | 2.7.0        |
| multipart-post             | 2.0.0        |
| word_wrap                  | 1.0.0        |
| tty-cursor                 | 0.7.1        |
| tty-spinner                | 0.9.3        |
| babosa                     | 1.0.3        |
| colored                    | 1.2          |
| highline                   | 1.7.10       |
| commander-fastlane         | 4.4.6        |
| faraday                    | 1.0.1        |
| unf_ext                    | 0.0.7.7      |
| unf                        | 0.1.4        |
| domain_name                | 0.5.20190701 |
| http-cookie                | 1.0.3        |
| faraday-cookie_jar         | 0.0.6        |
| faraday_middleware         | 1.0.0        |
| gh_inspector               | 1.1.3        |
| mini_magick                | 4.10.1       |
| rubyzip                    | 2.3.0        |
| security                   | 0.1.3        |
| xcpretty-travis-formatter  | 1.0.0        |
| bundler                    | 2.1.4        |
| naturally                  | 2.2.0        |
| simctl                     | 1.6.8        |
| jwt                        | 2.2.1        |
| uber                       | 0.1.0        |
| declarative                | 0.0.20       |
| declarative-option         | 0.1.0        |
| representable              | 3.0.4        |
| retriable                  | 3.1.2        |
| mini_mime                  | 1.0.2        |
| signet                     | 0.14.0       |
| memoist                    | 0.16.2       |
| os                         | 1.1.0        |
| googleauth                 | 0.13.0       |
| httpclient                 | 2.8.3        |
| google-api-client          | 0.38.0       |
| google-cloud-errors        | 1.0.1        |
| google-cloud-core          | 1.5.0        |
| rake                       | 13.0.1       |
| digest-crc                 | 0.6.1        |
| google-cloud-storage       | 1.26.2       |
| emoji_regex                | 3.0.0        |
| nanaimo                    | 0.3.0        |
| colored2                   | 3.1.2        |
| claide                     | 1.0.3        |
| CFPropertyList             | 3.0.2        |
| atomos                     | 0.1.3        |
| xcodeproj                  | 1.17.1       |
| tty-screen                 | 0.8.1        |
| excon                      | 0.76.0       |
| fastimage                  | 2.2.0        |
| json                       | 2.3.1        |
| dotenv                     | 2.7.6        |
| multi_json                 | 1.15.0       |
| google-cloud-env           | 1.3.3        |
| aws-eventstream            | 1.1.0        |
| aws-sigv4                  | 1.2.1        |
| aws-partitions             | 1.345.0      |
| jmespath                   | 1.4.0        |
| aws-sdk-core               | 3.104.3      |
| aws-sdk-kms                | 1.36.0       |
| aws-sdk-s3                 | 1.75.0       |
| forwardable                | 1.2.0        |
| logger                     | 1.3.0        |
| stringio                   | 0.0.2        |
| ipaddr                     | 1.2.2        |
| openssl                    | 2.1.2        |
| ostruct                    | 0.1.0        |
| strscan                    | 1.0.0        |
| date                       | 2.0.0        |
| fileutils                  | 1.1.0        |
| etc                        | 1.0.1        |
| io-console                 | 0.4.7        |
| zlib                       | 1.0.0        |
| libxml-ruby                | 3.1.0        |
| rexml                      | 3.1.9        |
| psych                      | 3.1.0        |
| mutex_m                    | 0.1.0        |
| webrick                    | 1.4.2        |
| fastlane-plugin-versioning | 0.4.3        |
</details>

*generated on:* **2020-07-27**
</details> </pre>
</details>

**Comment by kevint727** [comment]
It also does not create the DeliverFile. If I use an old deliver file and metadata setup, it produces no errors but fails with:

INFO [2020-07-27 10:19:08.73]: Login successful

+---------------------------------------------------+---------------------------------------------------+
|                                        deliver 2.153.1 Summary                                        |
+---------------------------------------------------+---------------------------------------------------+
| submit_for_review                                 | false                                             |
| force                                             | true                                              |
| skip_metadata                                     | false                                             |
| skip_screenshots                                  | true                                              |
| ipa                                               | /Users/ktodd/BaZingiOS/fastlane/builds/DevSwitch  |
|                                                   | er.ipa                                            |
| app_identifier                                    | com.BaZing.BaZingDevSwitcherTest                  |
| screenshots_path                                  | ./fastlane/screenshots                            |
| app_version                                       | 6.500.11                                          |
| username                                          | mobile.dev@strategycorps.com                      |
| platform                                          | ios                                               |
| edit_live                                         | false                                             |
| use_live_version                                  | false                                             |
| metadata_path                                     | ./fastlane/metadata/DevSwitcher                   |
| skip_binary_upload                                | false                                             |
| skip_app_version_update                           | false                                             |
| overwrite_screenshots                             | false                                             |
| reject_if_possible                                | false                                             |
| automatic_release                                 | false                                             |
| phased_release                                    | false                                             |
| reset_ratings                                     | false                                             |
| price_tier                                        | 0                                                 |
| app_rating_config_path                            | ./fastlane/metadata/DevSwitcher/app_store_rating  |
|                                                   | _config.json                                      |
| submission_information.export_compliance_encrypt  | false                                             |
| ion_updated                                       |                                                   |
| submission_information.export_compliance_uses_en  | false                                             |
| cryption                                          |                                                   |
| submission_information.content_rights_contains_t  | true                                              |
| hird_party_content                                |                                                   |
| submission_information.content_rights_has_rights  | true                                              |
| submission_information.add_id_info_uses_idfa      | true                                              |
| submission_information.add_id_info_serves_ads     | false                                             |
| submission_information.add_id_info_tracks_instal  | true                                              |
| l                                                 |                                                   |
| submission_information.add_id_info_tracks_action  | true                                              |
| run_precheck_before_submit                        | true                                              |
| precheck_default_rule_level                       | warn                                              |
| ignore_language_directory_validation              | false                                             |
| precheck_include_in_app_purchases                 | true                                              |
+---------------------------------------------------+---------------------------------------------------+

INFO [2020-07-27 10:19:12.17]: Making sure the latest version on App Store Connect matches '6.500.11'...
INFO [2020-07-27 10:19:12.68]: '6.500.11' is the latest version on App Store Connect
INFO [2020-07-27 10:19:13.65]: Loading './fastlane/metadata/DevSwitcher/en-US/description.txt'...
INFO [2020-07-27 10:19:13.65]: Loading './fastlane/metadata/DevSwitcher/en-US/keywords.txt'...
INFO [2020-07-27 10:19:13.65]: Loading './fastlane/metadata/DevSwitcher/en-US/release_notes.txt'...
INFO [2020-07-27 10:19:13.65]: Loading './fastlane/metadata/DevSwitcher/en-US/support_url.txt'...
INFO [2020-07-27 10:19:13.65]: Loading './fastlane/metadata/DevSwitcher/en-US/marketing_url.txt'...
INFO [2020-07-27 10:19:13.65]: Loading './fastlane/metadata/DevSwitcher/en-US/promotional_text.txt'...
INFO [2020-07-27 10:19:13.66]: Loading './fastlane/metadata/DevSwitcher/en-US/name.txt'...
INFO [2020-07-27 10:19:13.66]: Loading './fastlane/metadata/DevSwitcher/en-US/subtitle.txt'...
INFO [2020-07-27 10:19:13.66]: Loading './fastlane/metadata/DevSwitcher/en-US/privacy_url.txt'...
INFO [2020-07-27 10:19:13.66]: Loading './fastlane/metadata/DevSwitcher/en-US/apple_tv_privacy_policy.txt'...
INFO [2020-07-27 10:19:13.66]: Loading './fastlane/metadata/DevSwitcher/copyright.txt'...
INFO [2020-07-27 10:19:13.66]: Loading './fastlane/metadata/DevSwitcher/primary_category.txt'...
INFO [2020-07-27 10:19:13.66]: Loading './fastlane/metadata/DevSwitcher/secondary_category.txt'...
INFO [2020-07-27 10:19:13.66]: Loading './fastlane/metadata/DevSwitcher/primary_first_sub_category.txt'...
INFO [2020-07-27 10:19:13.66]: Loading './fastlane/metadata/DevSwitcher/primary_second_sub_category.txt'...
INFO [2020-07-27 10:19:13.66]: Loading './fastlane/metadata/DevSwitcher/secondary_first_sub_category.txt'...
INFO [2020-07-27 10:19:13.66]: Loading './fastlane/metadata/DevSwitcher/secondary_second_sub_category.txt'...
DEBUG [2020-07-27 10:19:24.06]: Version '6.500.11' is the first version on App Store Connect
WARN [2020-07-27 10:19:24.06]: Will begin uploading metadata for '6.500.11' on App Store Connect
ERROR [2020-07-27 10:19:24.06]: Skipping 'release_notes'... this is the first version of the app
INFO [2020-07-27 10:19:24.06]: Uploading metadata to App Store Connect for version
INFO [2020-07-27 10:19:24.42]: Uploading metadata to App Store Connect for localized version 'en-US'
INFO [2020-07-27 10:19:24.81]: Uploading metadata to App Store Connect for localized info 'en-US'
INFO [2020-07-27 10:19:33.25]: Successfully generated documentation at path '/Users/ktodd/BaZingiOS/fastlane/README.md'

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 2    | get_certificates | 7           |
| 3    | gym              | 129         |
| 💥   | deliver          | 26          |
+------+------------------+-------------+

DEBUG [2020-07-27 10:19:33.25]: All plugins are up to date
INFO [2020-07-27 10:19:33.25]: fastlane.tools finished successfully 🎉
DEBUG [2020-07-27 10:19:33.25]: All plugins are up to date

If I tell it to skip metadata, it does upload successfully.

**Comment by markmuniz** [comment]
I'm having the same issue. Seems to have broken between `2.152.0` and `2.153.0`.

**Comment by kevint727** [comment]
Anyone have any insight into this?

**Comment by feef** [comment]
I had the same issue. I was initializing deliver for use with one of several already-live apps in my team. In this scenario, I think deliver isn't properly requesting the app identifier. I managed to get around it by specifying the app identifier during initialization:

`fastlane deliver init --app_identifier <BUNDLE_ID>`
