### ISSUE TITLE
[deliver] 'appStoreVersionLocalizations' API return 403

### ISSUE THREAD

**Issue by GCSNNB** [fastlane/fastlane#16952]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I want to use new app store connect api and had set environment.
but when I run deliver command, it will Stuck in 

> [14:05:12]: Making sure the latest version on App Store Connect matches '3.0'...
> [14:05:13]: '3.0' is the latest version on App Store Connect
> [14:05:13]: Loading './fastlane/metadata/primary_category.txt'...
> [14:05:13]: Loading './fastlane/metadata/secondary_category.txt'...
> [14:05:15]: Detected languages: ["zh-Hans", "zh-Hant", "en-US", "en-AU", "en-GB", "en-CA", "ja", "default"]
> 

The token has not expired yet.

I find it because of 'appStoreVersionLocalizations' request, and it response:
> {:status=>403, :body=>{"errors"=>[{"id"=>"9c018f1c-9791-4c25-ba80-328218a45860",  "status"=>"403", "code"=>"FORBIDDEN_ERROR", "title"=>"The given operation is not allowed", "detail"=>"The resource 'appStoreVersionLocalizations' does not allow 'GET_COLLECTION'. Allowed operations are: GET_INSTANCE, CREATE, UPDATE, DELETE"}]}, :response_headers=>{"server"=>"daiquiri/3.0.0", "date"=>"Tue, 28 Jul 2020 05:49:07 GMT", "content-type"=>"application/json", "content-length"=>"338", "connection"=>"keep-alive", "b3"=>"5c51956643a0a2690fbbd22b1679f76f-c2594a20c24a4f8a", "x-b3-traceid"=>"5c51956643a0a2690fbbd22b1679f76f", "x-b3-spanid"=>"c2594a20c24a4f8a", "cache-control"=>"no-cache,no-store,must-revalidate", "pragma"=>"no-cache", "expires"=>"0", "strict-transport-security"=>"max-age=31536000; includeSubDomains", "x-request-id"=>"LRIZKZSDUCRGSD532IVRM6PXN4", "x-rate-limit"=>"user-hour-lim:3600;user-hour-rem:3478;", "x-daiquiri-instance"=>"daiquiri:18493002:mr85p00it-hyhk04114201:7987:20J24"}}
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.5                                     |
| Ruby                        | 2.7.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.rvm/gems/ruby-2.7.0/bin/fastlane         |
| Host                        | Mac OS X 10.15.5 (19F101)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.7.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.5                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
#! /usr/bin/env ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.20.0"
fastlane_require "Xcodeproj"
default_platform :ios

$LOAD_PATH.unshift(File.dirname(__FILE__))
require './Packager/packager'

platform :ios do

  desc "Package an enterprise package"
  lane :enterprise_package_only do
    package_enterprise
  end

  desc "Package an External enterprise package"
  lane :enterprise_external_package_only do
    package_enterprise_external
  end

  desc "Package an profession package"
  lane :profession_package_only do
    package_profession
  end

  desc "Package an normal package"
  lane :normal_package_only do
    package_normal
  end

  desc "Package an test flight package"
  lane :test_flight_package_only do
    package_testflight
  end

  desc "Package an lite package"
  lane :lite_package_only do
    package_lite
  end

  desc "Submit a new Beta Build to Apple TestFlight, and upload to AppStore for review."
  lane :itunes do
    itunes_pilot_only
    itunes_deliver_only
  end

  desc "**Only** submit a new Beta Build to Apple TestFlight, **will not** upload to AppStore for review."
  lane :itunes_pilot_only do
    package_itunes_pilot_only
  end

  desc "**Only** upload to AppStore for review."
  lane :itunes_deliver_only do
    package_itunes_deliver_only
  end

  desc "Submit a new Beta Build to Apple TestFlight, and upload to AppStore for review."
  lane :itunes_pro do
    itunes_pro_pilot_only
    itunes_pro_deliver_only
  end

  desc "**Only** submit a new Beta Build to Apple TestFlight, **will not** upload to AppStore for review."
  lane :itunes_pro_pilot_only do
    package_itunes_pro_pilot_only
  end

  desc "**Only** upload to AppStore for review."
  lane :itunes_pro_deliver_only do
    package_itunes_pro_deliver_only
  end

  desc "**Only** submit a new Beta Build to Apple TestFlight, **will not** upload to AppStore for review."
  lane :itunes_test_pilot_only do
    package_itunes_test_pilot_only
  end

  desc "Submit a new Beta Build to Apple TestFlight, and upload to AppStore for review."
  lane :itunes_lite do
    itunes_lite_pilot_only
    itunes_lite_deliver_only
  end

  desc "**Only** submit a new Beta Build to Apple TestFlight, **will not** upload to AppStore for review."
  lane :itunes_lite_pilot_only do
    package_itunes_lite_pilot_only
  end

  desc "**Only** upload to AppStore for review."
  lane :itunes_lite_deliver_only do
    package_itunes_lite_deliver_only
  end

  desc "Translate to traditional Chinese"
  lane :to_hant do
    # need to install opencc https://github.com/BYVoid/OpenCC
    sh "opencc -c s2twp.json -i ../Resources/localizable/zh-Hans.lproj/Localizable.strings  -o ../Resources/localizable/zh-Hant-TW.lproj/Localizable.strings"
    sh "opencc -c s2HK.json -i ../Resources/localizable/zh-Hans.lproj/Localizable.strings  -o ../Resources/localizable/zh-Hant.lproj/Localizable.strings"
  end

  desc "Update App default JSON files"
  lane :update_json_only do
    package_update_json_only
  end
  
  desc "Upload to netease easy test platform with an enterprise package"
  lane :netease_easy_test do
    package_netease_easy_test
  end

  before_all do
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "20"
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful
  end

  error do |lane, exception|
  end

end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
#! /usr/bin/env ruby

app_identifier "com.netease.news" # The bundle identifier of your app
apple_id "newsapp@163.com" # Your Apple email address
team_id "MLC2R97395"  # Developer Portal Team ID
itc_team_id "104792803" # App Store Connect Team ID

for_lane :enterprise do
	app_identifier 'com.netease.newsent'
    apple_id "lixf@corp.netease.com"
	team_id "2BVXXELUQJ"
end

for_lane :enterprise_external do
	app_identifier 'com.netease.newsent'
    apple_id "lixf@corp.netease.com"
	team_id "2BVXXELUQJ"
end

for_lane :itunes_pro do
	app_identifier 'com.netease.newspro'
	apple_id "newsapp@163.com"
	team_id "MLC2R97395"
end

for_lane :itunes_pro_pilot_only do
    app_identifier 'com.netease.newspro'
    apple_id "newsapp@163.com"
    team_id "MLC2R97395"
end

for_lane :itunes_pro_deliver_only do
    app_identifier 'com.netease.newspro'
    apple_id "newsapp@163.com"
    team_id "MLC2R97395"
end

for_lane :itunes_lite do
    app_identifier 'com.netease.newslite'
    apple_id "newsapp@163.com"
    team_id "MLC2R97395"
end

for_lane :itunes_lite_pilot_only do
    app_identifier 'com.netease.newslite'
    apple_id "newsapp@163.com"
    team_id "MLC2R97395"
end

for_lane :itunes_lite_deliver_only do
    app_identifier 'com.netease.newslite'
    apple_id "newsapp@163.com"
    team_id "MLC2R97395"
end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.153.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| CFPropertyList            | 3.0.2        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday                   | 1.0.1        |
| faraday_middleware        | 1.0.0        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| uber                      | 0.1.0        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| signet                    | 0.14.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.2       |
| uri                       | 0.10.0       |
| nanaimo                   | 0.3.0        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.17.1       |
| public_suffix             | 4.0.5        |
| tty-screen                | 0.8.1        |
| excon                     | 0.76.0       |
| fastimage                 | 2.2.0        |
| json                      | 2.3.1        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.2        |
| jwt                       | 2.2.1        |
| declarative               | 0.0.20       |
| multi_json                | 1.15.0       |
| os                        | 1.1.0        |
| memoist                   | 0.16.2       |
| googleauth                | 0.13.0       |
| google-cloud-env          | 1.3.3        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| emoji_regex               | 3.0.0        |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.1        |
| aws-partitions            | 1.345.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.104.3      |
| aws-sdk-kms               | 1.36.0       |
| aws-sdk-s3                | 1.75.0       |
| forwardable               | 1.3.1        |
| logger                    | 1.4.2        |
| cgi                       | 0.1.0        |
| timeout                   | 0.1.0        |
| stringio                  | 0.1.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.2.0        |
| strscan                   | 1.0.3        |
| date                      | 3.0.0        |
| delegate                  | 0.1.0        |
| fileutils                 | 1.4.1        |
| io-console                | 0.5.3        |
| zlib                      | 1.1.0        |
| singleton                 | 0.1.0        |
| rexml                     | 3.2.3        |
| open3                     | 0.1.0        |
| yaml                      | 0.1.0        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.6.0        |
</details>

*generated on:* **2020-07-28**
</details>

**Comment by valerio-castelli** [comment]
We've been experiencing a similar issue for the past few days; admittedly, we've not verified the body of the response, but we do sometimes get a 403 when performing an `appStoreVersionLocalizations` request. 

On our side, usually a deletion of the session cookie and a change of IP address is enough to make the API work again, but only for a while. If it's useful, we've also determined that the API currently used by fastlane to retrieve the `appStoreVersionLocalizations` seems to be a private one that can only be called with user name & password authentication, and differs from the specification of its (slightly more limited) [public counterpart](https://developer.apple.com/documentation/appstoreconnectapi/list_all_app_store_version_localizations_for_an_app_store_version).

**Comment by GCSNNB** [comment]
> We've been experiencing a similar issue for the past few days; admittedly, we've not verified the body of the response, but we do sometimes get a 403 when performing an `appStoreVersionLocalizations` request.
> 
> On our side, usually a deletion of the session cookie and a change of IP address is enough to make the API work again, but only for a while. If it's useful, we've also determined that the API currently used by fastlane to retrieve the `appStoreVersionLocalizations` seems to be a private one that can only be called with user name & password authentication, and differs from the specification of its (slightly more limited) [public counterpart](https://developer.apple.com/documentation/appstoreconnectapi/list_all_app_store_version_localizations_for_an_app_store_version).
> 
> ### Environment

I'm not very sure, I thought fastlane has already adapted new app store connect api in this [commit](https://github.com/fastlane/fastlane/pull/16626/files)

**Comment by valerio-castelli** [comment]
> > We've been experiencing a similar issue for the past few days; admittedly, we've not verified the body of the response, but we do sometimes get a 403 when performing an `appStoreVersionLocalizations` request.
> > On our side, usually a deletion of the session cookie and a change of IP address is enough to make the API work again, but only for a while. If it's useful, we've also determined that the API currently used by fastlane to retrieve the `appStoreVersionLocalizations` seems to be a private one that can only be called with user name & password authentication, and differs from the specification of its (slightly more limited) [public counterpart](https://developer.apple.com/documentation/appstoreconnectapi/list_all_app_store_version_localizations_for_an_app_store_version).
> 
> I'm not very sure, I thought fastlane has already adapted new app store connect api in this [commit](https://github.com/fastlane/fastlane/pull/16626/files)

Unfortunately, that's not entirely the case. It's true that fastlane was recently adapted to the new App Store Connect API, but Apple decided to release two different, mutually incompatible implementations of this API:
- A private one that is used by the App Store Connect interface. This is the one that fastlane is currently using. You can see that this is the case because [fastlane's implementation](https://github.com/fastlane/fastlane/blob/54d8e84574dc94e0f900250c91da3e661abfaed3/spaceship/lib/spaceship/connect_api/tunes/tunes.rb#L626) of the `appStoreVersionLocalizations` call is performing a straight GET on the `appStoreVersionLocalizations` resource, which is the same call performed by the App Store Connect portal.
- A public one that is used by the App Store Connect API. If you look at the public [documentation](https://developer.apple.com/documentation/appstoreconnectapi/list_all_app_store_version_localizations_for_an_app_store_version), the URL for the GET method is different, since it's `appStoreVersions/{id}/appStoreVersionLocalizations` instead of just `appStoreVersionLocalizations`.

There are more differences between the two. For example, the private API requires the identifier of the appStoreVersion object to be set inside the request's body, while the public API needs it to be part of the REST URL. The supported options are also different, since the private API supports the `includes`, `filters`, `sort` and `limit` predicates, while the public API only supports `fields` (in place of `includes`) and `limit` with no support for `filters` and `sort`. 🙁

**Comment by GCSNNB** [comment]
@valerio-castelli Thanks! You’re correct.
