### ISSUE TITLE
Documentation: CI / Seperate Apple-ID for CI isn't correct anymore

### ISSUE THREAD

**Issue by creambyemute** [fastlane/fastlane#16956]
### Issue Description
The section about creating an Apple-ID without Two-Factor Auth enabled is no longer valid. There is no way to turn off Two-Factor Auth anymore on newly created accounts as per Apples Documentation.

**Comment by max-ott** [comment]
Thanks @creambyemute Could you open a pull request for that fixing the issue?

**Comment by creambyemute** [comment]
I haven't used fastlane much tbh. I'm just setting up the azure pipeline and we wanted to not go the session way, which we are now doing due to the new TFA enformement on new accounts.

If I'd edit it, I'd probably either
* Delete that section or
* Add a disclaimer this does not work for newly created accounts

**Comment by alex-benoit** [comment]
Just tried it an indeed 2FA is mandated for all new accounts now it seems - that really sucks :(

**Comment by EsaNuurtamo** [comment]
Ran in to the same problem. This article provides some additional solutions but none of them is good in my opinion:
https://drobinin.com/posts/keep-using-fastlane-with-apples-2fa-changes/

Application level password is not an option for us because we need to send other meta data.

**Comment by alex-benoit** [comment]
very interesting article - thanks for sharing

**Comment by rogerluan** [comment]
I'd like to encourage us to keep this discussing on going here https://github.com/fastlane/fastlane/discussions/17059
