### ISSUE TITLE
deliver lane screenshot upload failed

### ISSUE THREAD

**Issue by mganapathy** [fastlane/fastlane#16950]
Fastlane version: 2.153.0
deliver lane screenshot upload fails with following error.
Error log:
DEBUG [2020-07-27 04:25:02.53]: Version '3.10.1' is the first version on App Store Connect
WARN [2020-07-27 04:25:02.53]: [33mWill begin uploading metadata for '3.10.1' on App Store Connect[0m
ERROR [2020-07-27 04:25:02.53]: [31mSkipping 'release_notes'... this is the first version of the app[0m
INFO [2020-07-27 04:25:02.53]: Uploading metadata to App Store Connect for version
INFO [2020-07-27 04:25:03.08]: Uploading metadata to App Store Connect for localized version 'en-US'
INFO [2020-07-27 04:25:03.60]: Uploading metadata to App Store Connect for localized info 'en-US'
INFO [2020-07-27 04:25:09.11]: Uploading app review information to App Store Connect
ERROR [2020-07-27 04:25:09.56]: [31mError fetching app store review detail - The specified resource does not exist - There is no resource of type 'appStoreReviewDetails' with id 'null'[0m
call_with_default_configuration Exception is... The provided entity includes an unknown attribute - 'demo_account_name' is not an attribute on the resource 'appStoreReviewDetails'
The provided entity includes an unknown attribute - 'contact_phone' is not an attribute on the resource 'appStoreReviewDetails'
The provided entity includes an unknown attribute - 'demo_account_password' is not an attribute on the resource 'appStoreReviewDetails'
The provided entity includes an unknown attribute - 'contact_last_name' is not an attribute on the resource 'appStoreReviewDetails'
The provided entity includes an unknown attribute - 'demo_account_required' is not an attribute on the resource 'appStoreReviewDetails'
The provided entity includes an unknown attribute - 'contact_first_name' is not an attribute on the resource 'appStoreReviewDetails'
The provided entity includes an unknown attribute - 'contact_email' is not an attribute on the resource 'appStoreReviewDetails'
Logger: Upload screenshots lane completed 2020-07-27 04:25:10.036
@joshdholtz

**Comment by joshdholtz** [comment]
Will take a look at this morning!

**Comment by joshdholtz** [comment]
@mganapathy Oh, can you update to `2.153.1`? 😇

**Comment by mganapathy** [comment]
@joshdholtz - Thanks for your quick update! we will update to 2.153.1 and will let you know the status.

**Comment by sonjz** [comment]
wanted to confirm that I had 2.153.0 and had this exact issue with `Error fetching app store review detail - The specified resource does not exist - There is no resource of type 'appStoreReviewDetails' with id 'null'`.

i upgraded to latest fastlane 2.153.1 and reran the deliver and the issue was resolved.

**Comment by joshdholtz** [comment]
Closing this! ☝️

**Comment by mganapathy** [comment]
@joshdholtz - after upgrading 2.153.1 version deliver lane screenshot issue resolved now. Thanks!
