### ISSUE TITLE
[spaceship] toggle_phased_release not working

### ISSUE THREAD

**Issue by oonoo** [fastlane/fastlane#16978]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

The method toggle_phased_release is not working as I expect it. When I run the following code:
```
Spaceship::Tunes.login MY_APPLE_ID
app = Spaceship::Tunes::Application.find MY_APP_IDENTIFIER
app.edit_version.toggle_phased_release(enabled: true)
app.edit_version.save!
```

I get the error:
```
Potential server error received: 'Unexpected Error'. Retrying after 10 seconds (remaining: 2)...
Potential server error received: 'Unexpected Error'. Retrying after 10 seconds (remaining: 1)...
Unexpected Error
```

##### Command executed

FASTLANE_SKIP_UPDATE_CHECK=1 bundle exec fastlane debug_app --verbose
**debug_app** is my lane which has the code stated above.
### Captured Output

Command Used: `debug_app --capture_output`
<details><summary>Output/Log</summary>

```

INFO [2020-07-31 09:48:29.56]: Successfully loaded custom action '/Users/onno/projects/ios_passenger_app/fastlane/actions/issue_ids_since_last_tag.rb'.
INFO [2020-07-31 09:48:29.57]: Successfully loaded custom action '/Users/onno/projects/ios_passenger_app/fastlane/actions/convert_test_coverage_for_sonarqube.rb'.
INFO [2020-07-31 09:48:29.57]: Successfully loaded custom action '/Users/onno/projects/ios_passenger_app/fastlane/actions/check_for_git_merge_conflicts.rb'.
INFO [2020-07-31 09:48:29.57]: Successfully loaded custom action '/Users/onno/projects/ios_passenger_app/fastlane/actions/jirachangelog.rb'.
INFO [2020-07-31 09:48:29.57]: Successfully loaded custom action '/Users/onno/projects/ios_passenger_app/fastlane/actions/get_highest_build_number_from_git_tags.rb'.
INFO [2020-07-31 09:48:29.57]: Successfully loaded custom action '/Users/onno/projects/ios_passenger_app/fastlane/actions/select_xcode_from_file.rb'.
INFO [2020-07-31 09:48:29.57]: Successfully loaded custom action '/Users/onno/projects/ios_passenger_app/fastlane/actions/jira_set_fix_version.rb'.
INFO [2020-07-31 09:48:29.57]: Successfully loaded custom action '/Users/onno/projects/ios_passenger_app/fastlane/actions/update_certificates_for_ssl_pinning.rb'.
INFO [2020-07-31 09:48:29.57]: Successfully loaded custom action '/Users/onno/projects/ios_passenger_app/fastlane/actions/git_is_shallow_clone.rb'.
INFO [2020-07-31 09:48:29.57]: Successfully loaded custom action '/Users/onno/projects/ios_passenger_app/fastlane/actions/get_changed_files_from_git.rb'.
DEBUG [2020-07-31 09:48:29.57]: Checking if there are any plugins that should be loaded...
DEBUG [2020-07-31 09:48:29.57]: Loading 'fastlane-plugin-appcenter' plugin
INFO [2020-07-31 09:48:29.57]: gem 'fastlane-plugin-appcenter' is already installed
DEBUG [2020-07-31 09:48:29.59]: Loading 'fastlane-plugin-*****' plugin
INFO [2020-07-31 09:48:29.59]: gem 'fastlane-plugin-*****' is already installed


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                              |
| --------------------------- | ------------------------------------------------------------------ |
| OS                          | 10.15.5                                                            |
| Ruby                        | 2.5.3                                                              |
| Bundler?                    | true                                                               |
| Git                         | git version 2.24.3 (Apple Git-128)                                 |
| Installation Source         | ~/projects/ios_passenger_app/vendor/bundle/ruby/2.5.0/bin/fastlane |
| Host                        | Mac OS X 10.15.5 (19F101)                                          |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.3/lib                                        |
| OpenSSL Version             | OpenSSL 1.0.2s  28 May 2019                                        |
| Is contained                | false                                                              |
| Is homebrew                 | false                                                              |
| Is installed via Fabric.app | false                                                              |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                        |
| Xcode Version               | 11.6                                                               |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Opt out of sharing usage data with Fastlane (https://github.com/fastlane/enhancer)
# Uncomment the following line to opt out
opt_out_usage

# This is the minimum version number required.
fastlane_version '2.144.0'

require 'spaceship'

default_platform :ios
platform :ios do
  before_all do
    # Make sure the Xcode version specified in ".xcode-version" is installed.
    select_xcode_from_file
  end

  lane :debug_app do
    Spaceship::Tunes.login CredentialsManager::AppfileConfig.try_fetch_value :apple_id
    app = Spaceship::Tunes::Application.find CredentialsManager::AppfileConfig.try_fetch_value :app_identifier

    UI.message "the phased release BEFORE changing it: #{app.edit_version.phased_release}"

    app.edit_version.toggle_phased_release(enabled: true)
    app.edit_version.save!

    UI.message "the phased release AFTER changing it: #{app.edit_version.phased_release}"
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier *****
apple_id *****

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.154.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status  |
| ------------------------- | ------- | -------------- |
| fastlane-plugin-appcenter | 1.9.0   | ✅ Up-To-Date   |
| fastlane-plugin-*****   | 0.1.0   | 💥 Check failed |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| bundler                   | 2.1.4        |
| rake                      | 13.0.1       |
| CFPropertyList            | 3.0.2        |
| concurrent-ruby           | 1.1.6        |
| i18n                      | 0.9.5        |
| minitest                  | 5.14.1       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.7        |
| activesupport             | 4.2.11.3     |
| public_suffix             | 4.0.5        |
| addressable               | 2.7.0        |
| httpclient                | 2.8.3        |
| json                      | 2.3.1        |
| algoliasearch             | 1.27.3       |
| jwt                       | 2.1.0        |
| atlassian-jwt             | 0.2.0        |
| atomos                    | 0.1.3        |
| awesome_print             | 1.8.0        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.347.0      |
| aws-sigv4                 | 1.2.1        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.104.3      |
| aws-sdk-kms               | 1.36.0       |
| aws-sdk-s3                | 1.75.0       |
| babosa                    | 1.0.3        |
| builder                   | 3.2.4        |
| claide                    | 1.0.3        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.8.4        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.4.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.5.0        |
| cocoapods-try             | 1.2.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.13.0       |
| cocoapods                 | 1.8.4        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| diff-lcs                  | 1.4.4        |
| digest-crc                | 0.6.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.0.0        |
| excon                     | 0.76.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 1.0.1        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.0        |
| signet                    | 0.14.0       |
| googleauth                | 0.13.0       |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.27.0       |
| mini_magick               | 4.10.1       |
| plist                     | 3.5.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-appcenter | 1.9.0        |
| fastlane-plugin-*****   | 0.1.0        |
| filelock                  | 1.1.1        |
| find_a_port               | 1.0.1        |
| mime-types-data           | 3.2020.0512  |
| mime-types                | 3.3.1        |
| multi_xml                 | 0.6.0        |
| httparty                  | 0.18.1       |
| oauth                     | 0.5.4        |
| jira-ruby                 | 2.1.3        |
| randexp                   | 0.1.7        |
| rspec-support             | 3.9.3        |
| rspec-core                | 3.9.2        |
| rspec-expectations        | 3.9.2        |
| rspec-mocks               | 3.9.1        |
| rspec                     | 3.9.0        |
| sync                      | 0.5.0        |
| tins                      | 1.25.0       |
| term-ansicolor            | 1.7.1        |
| pact-support              | 1.15.1       |
| rack                      | 2.2.3        |
| thor                      | 0.20.3       |
| webrick                   | 1.6.0        |
| pact-mock_service         | 3.6.1        |
| rack-test                 | 1.1.0        |
| pact                      | 1.51.0       |
| pact-message              | 0.7.0        |
| table_print               | 1.5.7        |
| pact_broker-client        | 1.28.4       |
| xcode-install             | 2.6.6        |
</details>

*generated on:* **2020-07-31**
</details>

**Comment by john-mejia** [comment]
I'm pretty sure the issue here is related to using the old `Tunes` API for log in rather than the new `ConnectAPI`. I'm working through some of these issues myself but it doesn't seem it's fully documented just yet.
If you look at the docs now, you'll see how to log in

**Comment by oonoo** [comment]
@john-mejia I cannot really follow. I think some part of the Tunes Models no longer work. Maybe you mean the same.

When I run use Charles to see what request this is doing I get this:
curl -H 'User-Agent: Spaceship 2.154.0' -H 'Content-Type: application/json' -H 'Cookie: acn01=********; [REMOVED_SOME_CONTENT]' -H 'Accept: */*' -H 'Host: appstoreconnect.apple.com' --data-binary "ENDLESS_LONG_JSON" --compressed '**https://appstoreconnect.apple.com/WebObjects/iTunesConnect.woa/ra/apps/357852748/platforms/ios/versions/837242534**'

And when I do the same (enable phased release) on the website I get on Charles:
curl -H 'Host: appstoreconnect.apple.com' -H 'Cookie: *****; [REMOVED_SOME_CONTENT]' -H 'accept: application/vnd.api+json' -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36' -H 'content-type: application/vnd.api+json' -H 'origin: https://appstoreconnect.apple.com' -H 'sec-fetch-site: same-origin' -H 'sec-fetch-mode: cors' -H 'sec-fetch-dest: empty' -H 'referer: https://appstoreconnect.apple.com/apps/357852748/appstore/ios/version/inflight' -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8' --data-binary '{"data":{"type":"appStoreVersionPhasedReleases","attributes":{"phasedReleaseState":"INACTIVE"},"relationships":{"appStoreVersion":{"data":{"type":"appStoreVersions","id":"d759dfa7-8a2e-45a8-bbe4-05831aeb587c"}}}}}' --compressed '**https://appstoreconnect.apple.com/iris/v1/appStoreVersionPhasedReleases**'

So it looks like it the website is using another end point, sending other data and using another HTTP method. 

I noticed the UploadMetadata class can also change the phased release and as a workaround I copied that code in my own classes. What UploadMetadata does looks similare to what the website does.
