### ISSUE TITLE
[fastlane_core] add codesign partition ID to keychain when importing

### ISSUE THREAD

**Issue by jakubgs** [fastlane/fastlane#16989]
Currently only two partition IDs are included when importing keychain by `match`: `apple-tool:` and `apple:`
https://github.com/fastlane/fastlane/blob/0db46e0b6b7caed49abff200b7e78e119e805ad1/fastlane_core/lib/fastlane_core/keychain_importer.rb#L40-L46
But based on my research the lack of `codesign:` partition ID can still cause issues like:
```
errSecInternalComponent
Command /usr/bin/codesign failed with exit code
```
or also:
```
error: The specified item could not be found in the keychain.
```
For more details on this you can see:
* https://github.com/fastlane/fastlane/issues/15185
* https://stackoverflow.com/a/40870033
* https://github.com/status-im/nim-status-client/issues/335#issuecomment-651721381
* https://medium.com/@ceyhunkeklik/how-to-fix-ios-application-code-signing-error-4818bd331327

**Comment by jakubgs** [comment]
I have been seeing error like this in my builds:
```
....../Frameworks/libswiftCore.dylib: errSecInternalComponent
```
When running the build via SSH, but it builds fine via UI. The issue is I see no prompt via UI, so I can't fix it with `Always Allow`.

**Comment by jakubgs** [comment]
I'm going INSANE. Apple code signing is literally the worst thing in the world.

I've tried all of the following:

* Re-creating the keychain
* Adding `:codesign` partition to keaychain
* Running build with UI to click `Always allow` but the prompt doesn't show up
* Added XCode to applications allowed to access the keychain
* Made keychain `Allow all applications to access this item`

None of it work. I just keep getting `errSecInternalComponent` and it makes no sense.

**Comment by jakubgs** [comment]
Absolutely not.

**Comment by jakubgs** [comment]
That case was related to a CI environment that had other CI jobs running which were also modifying the keychain search list.
The issues I was having back then were related to main user keychain changing search list in middle of builds due to multiple executors. As far as I can tell adding the `:codesign` partition ID does help with specifically the `errSecInternalComponent` due to lack of interactive prompts for UI-less processes.

**Comment by rogerluan** [comment]
Got it!

>Have you tried forking fastlane and testing your own solution locally, to see if it does any good? Let me know if you need guidance on how to achieve this, I'd be happy to help 👍

Have you? 😃

**Comment by rogerluan** [comment]
If not, you can update `Gemfile` with the following, and run `bundle install`, `bundle update fastlane`, or `bundle update`:

```rb
gem "fastlane", :git => "https://github.com/fastlane/fastlane.git", :branch => "rogerluan-codesign-partition-id"
```

to test it! 😊
