### ISSUE TITLE
Not getting previews of appstore before uploading ipa

### ISSUE THREAD

**Issue by eladgel** [fastlane/fastlane#16980]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: [e.g. `2.154.0`]
- Last working version: [e.g. `2.152.0`]

### Regression Description
There is usually a preview that opens and asks me if I approve the metada for the current build

##### Complete output when running fastlane, including the stack trace and command used
upload_to_app_store

<details>
  <pre>NoMethodError: undefined method `latest_version' for #<Spaceship::ConnectAPI::App:0x00007f8464700838>
 /User_path/.rvm/gems/ruby-2.6.3/gems/fastlane-2.154.0/deliver/lib/deliver/html_generator.rb:54:in `render'
/User_path/.rvm/gems/ruby-2.6.3/gems/fastlane-2.154.0/deliver/lib/deliver/html_generator.rb:14:in `run'
/User_path/.rvm/gems/ruby-2.6.3/gems/fastlane-2.154.0/deliver/lib/deliver/runner.rb:198:in `validate_html'
/User_path/.rvm/gems/ruby-2.6.3/gems/fastlane-2.154.0/deliver/lib/deliver/runner.rb:119:in `upload_metadata'
/User_path/.rvm/gems/ruby-2.6.3/gems/fastlane-2.154.0/deliver/lib/deliver/runner.rb:42:in `run'
/User_path/.rvm/gems/ruby-2.6.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:17:in `run'
/User_path/.rvm/gems/ruby-2.6.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
/User_path/.rvm/gems/ruby-2.6.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
/User_path/.rvm/gems/ruby-2.6.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
/User_path/.rvm/gems/ruby-2.6.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
/User_path/.rvm/gems/ruby-2.6.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
/User_path/.rvm/gems/ruby-2.6.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
/User_path/.rvm/gems/ruby-2.6.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
Fastfile:83:in `block (2 levels) in parsing_binding'
/User_path/.rvm/gems/ruby-2.6.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/lane.rb:33:in `call'
/User_path/.rvm/gems/ruby-2.6.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
/User_path/.rvm/gems/ruby-2.6.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
/User_path/.rvm/gems/ruby-2.6.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
/User_path/.rvm/gems/ruby-2.6.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
/User_path/.rvm/gems/ruby-2.6.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
/User_path/.rvm/gems/ruby-2.6.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
/User_path/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
/User_path/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
/User_path/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
/User_path/.rvm/gems/ruby-2.6.3/gems/fastlane-2.154.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
/User_path/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
/User_path/.rvm/gems/ruby-2.6.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
/User_path/.rvm/gems/ruby-2.6.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
/User_path/.rvm/gems/ruby-2.6.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
/User_path/.rvm/gems/ruby-2.6.3/gems/fastlane-2.154.0/bin/fastlane:23:in `<top (required)>'
/User_path/.rvm/gems/ruby-2.6.3/bin/fastlane:23:in `load'
/User_path/.rvm/gems/ruby-2.6.3/bin/fastlane:23:in `<main>'</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.5                                     |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.20.1                          |
| Installation Source         | ~/.rvm/gems/ruby-2.6.3/bin/fastlane         |
| Host                        | Mac OS X 10.15.5 (19F101)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.3/lib                |
| OpenSSL Version             | OpenSSL 1.1.1c  28 May 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.6                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
team_id = CredentialsManager::AppfileConfig.try_fetch_value(:team_id)



#match(type: "development", app_identifier: "com.something.good.debug")



update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  lane :release_local do
        match(type: "appstore",app_identifier: "com.something.good")
      #capture_screenshots                  # generate new screenshots for the App Store
      sync_code_signing(type: "appstore")  # see code signing guide for more information
      build_app(scheme: "APP_NAME",
              workspace: "ios/APP_NAME.xcworkspace",
          configuration: "Release")
      upload_to_app_store                  # upload your app to App Store Connect
      slack(message: "Successfully uploaded a new App Store build")
      upload_symbols_to_crashlytics(dsym_path: lane_context[SharedValues::DSYM_OUTPUT_PATH])
        testfairy(
          api_key: ENV[TESTFAIRY_API_KEY],
          symbols_file:lane_context[SharedValues::DSYM_OUTPUT_PATH],
          comment: "Build #{lane_context[SharedValues::BUILD_NUMBER]}",
          auto_update:"on",
          notify:"on",
          testers_groups:"test"
        )
  end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.something.good"
team_id "AAAAAAAAAAAA" # Developer Portal Team ID
apple_id "email@email.om"


for_platform :ios do
  for_lane :release do
    app_identifier 'com.something.good'
  end
  for_lane :adhoc do
    app_identifier 'com.something.good.staging'
  end
  for_lane :development do
    app_identifier 'com.something.good.debug'
  end
end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.154.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday                   | 1.0.1        |
| faraday_middleware        | 1.0.0        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| uber                      | 0.1.0        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mini_mime                 | 1.0.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| slack-notifier            | 2.3.2        |
| nanaimo                   | 0.3.0        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.17.1       |
| unicode-display_width     | 1.7.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.5        |
| addressable               | 2.7.0        |
| tty-screen                | 0.8.1        |
| highline                  | 1.7.10       |
| excon                     | 0.76.0       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| fastimage                 | 2.2.0        |
| json                      | 2.3.1        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.4        |
| jwt                       | 2.2.1        |
| declarative               | 0.0.20       |
| retriable                 | 3.1.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| os                        | 1.1.0        |
| memoist                   | 0.16.2       |
| googleauth                | 0.13.1       |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-env          | 1.3.3        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.27.0       |
| emoji_regex               | 3.0.0        |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.1        |
| aws-partitions            | 1.349.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.104.3      |
| aws-sdk-kms               | 1.36.0       |
| aws-sdk-s3                | 1.75.0       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.7       |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| oj                        | 3.0.6        |
| bigdecimal                | 1.4.1        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-08-01**
</details></pre>
</details>

**Comment by dhermanns** [comment]
Same problem here...

**Comment by lacostej** [comment]
Here's the error I see in the logs
```
[08:48:45]: #<NoMethodError: undefined method `latest_version' for #<Spaceship::ConnectAPI::App:0x00007f8ec22aac80>>
[08:48:45]: /Users/lacostej/.rvm/gems/ruby-2.5.3/gems/fastlane-2.154.0/deliver/lib/deliver/html_generator.rb:54:in `render'
/Users/lacostej/.rvm/gems/ruby-2.5.3/gems/fastlane-2.154.0/deliver/lib/deliver/html_generator.rb:14:in `run'
/Users/lacostej/.rvm/gems/ruby-2.5.3/gems/fastlane-2.154.0/deliver/lib/deliver/runner.rb:198:in `validate_html'
/Users/lacostej/.rvm/gems/ruby-2.5.3/gems/fastlane-2.154.0/deliver/lib/deliver/runner.rb:119:in `upload_metadata'
/Users/lacostej/.rvm/gems/ruby-2.5.3/gems/fastlane-2.154.0/deliver/lib/deliver/runner.rb:42:in `run'
/Users/lacostej/.rvm/gems/ruby-2.5.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:17:in `run'
/Users/lacostej/.rvm/gems/ruby-2.5.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
/Users/lacostej/.rvm/gems/ruby-2.5.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
/Users/lacostej/.rvm/gems/ruby-2.5.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
/Users/lacostej/.rvm/gems/ruby-2.5.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
/Users/lacostej/.rvm/gems/ruby-2.5.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
/Users/lacostej/.rvm/gems/ruby-2.5.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
/Users/lacostej/.rvm/gems/ruby-2.5.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
../../../../../../../var/folders/3n/52m9bkhs7fl5mzc46rvdk2dh0000gp/T/fl_clone20200803-9392-1ffzm40/fastlane_setup.git/fastlane/Fastfile:747:in `block (2 levels) in parsing_binding'
/Users/lacostej/.rvm/gems/ruby-2.5.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/lane.rb:33:in `call'
/Users/lacostej/.rvm/gems/ruby-2.5.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
/Users/lacostej/.rvm/gems/ruby-2.5.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
/Users/lacostej/.rvm/gems/ruby-2.5.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
/Users/lacostej/.rvm/gems/ruby-2.5.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
/Users/lacostej/.rvm/gems/ruby-2.5.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
/Users/lacostej/.rvm/gems/ruby-2.5.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
/Users/lacostej/.rvm/gems/ruby-2.5.3/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
/Users/lacostej/.rvm/gems/ruby-2.5.3/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
/Users/lacostej/.rvm/gems/ruby-2.5.3/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
/Users/lacostej/.rvm/gems/ruby-2.5.3/gems/fastlane-2.154.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
/Users/lacostej/.rvm/gems/ruby-2.5.3/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
/Users/lacostej/.rvm/gems/ruby-2.5.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
/Users/lacostej/.rvm/gems/ruby-2.5.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
/Users/lacostej/.rvm/gems/ruby-2.5.3/gems/fastlane-2.154.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
/Users/lacostej/.rvm/gems/ruby-2.5.3/gems/fastlane-2.154.0/bin/fastlane:23:in `<top (required)>'
/Users/lacostej/.rvm/gems/ruby-2.5.3/bin/fastlane:23:in `load'
/Users/lacostej/.rvm/gems/ruby-2.5.3/bin/fastlane:23:in `<main>'
/Users/lacostej/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `eval'
/Users/lacostej/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `<main>'
[08:48:45]: Could not render HTML preview. Do you still want to continue?
```
