### ISSUE TITLE
Adding new team member via Spaceship fails due to 404 Not Found

### ISSUE THREAD

**Issue by nerdyc** [fastlane/fastlane#16992]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Starting around July 7th, I've been unable to use Spaceship to add new members to my team. The attempt fails with the error "Not Found". Tracing has shown this is because the iTunesConnect endpoint `ra/users/itc/create` returns a 404 response.

```
 {
  :status=>404,
  :body=>{"data"=>nil, "messages"=>{"error"=>["Not Found"], "info"=>nil, "warn"=>nil}, "statusCode"=>"ERROR"},
  ... 
}
```
(from calling `Faraday::Response.to_hash`)

##### Command executed

I've written an internal script that includes the following.

```
  # app store setup (SUCCESS)
  Spaceship::Tunes.login(username, password)
  Spaceship::Tunes.select_team(team_id: team_uuid)

  # send invite (FAILS)
  Spaceship::Tunes::Members.create!(firstname: options[:firstname], lastname: options[:lastname], email_address: options[:email_address], roles: roles)
```

It's `Spaceship::Tunes::Members.create!` that results in the 404 response failure.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 	
	2: from /Users/cniles/.gems/gems/fastlane-2.154.0/spaceship/lib/spaceship/tunes/members.rb:26:in `create!'
	1: from /Users/cniles/.gems/gems/fastlane-2.154.0/spaceship/lib/spaceship/tunes/tunes_client.rb:542:in `create_member!'
/Users/cniles/.gems/gems/fastlane-2.154.0/spaceship/lib/spaceship/tunes/tunes_client.rb:232:in `handle_itc_response': Not Found (Spaceship::Tunes::Error)
</pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.5                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Installation Source         | ~/.gems/bin/fastlane                     |
| Host                        | Mac OS X 10.15.5 (19F101)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.5                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.154.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.17.1       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.76.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.1        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-storage      | 1.27.0       |
| emoji_regex               | 3.0.0        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.351.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.1        |
| aws-sdk-core              | 3.104.3      |
| aws-sdk-kms               | 1.36.0       |
| aws-sdk-s3                | 1.75.0       |
| json                      | 2.3.1        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-08-04**
</details>
</pre>
</details>

**Comment by max-ott** [comment]
This is probably related to all the changes Apple is doing to App Store Connect with the "new" API. Not sure if @joshdholtz already migrated the `Members` endpoint. 😅

**Comment by joshdholtz** [comment]
Hmmmm, doesn't look like I did yet 🤔 I will add that today 🙃

**Comment by nerdyc** [comment]
🙏 for looking into this so quickly. I'll happily help verify the fix when it's ready.

**Comment by aln787** [comment]
@fastlane-bot it appears this issue hasn't been resolved.

**Comment by max-ott** [comment]
https://github.com/max-ott/fastlane/commit/7fa72df295866c4c8d7c5cadffcb47ac22eac405 adds support from adding & removing users. Will try to get this merged with the next release. cc @joshdholtz

**Comment by joshdholtz** [comment]
This was fixed and merged in https://github.com/fastlane/fastlane/pull/17315. This should be out in the next fastlane version this week!
