### ISSUE TITLE
can't match appstore provisioning profile from match import

### ISSUE THREAD

**Issue by Tobrek** [fastlane/fastlane#17003]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
An AppStore MobileProvision profile, imported with fastlane match import can't be found by fastlane match, because it is stored as Distribution_com.company.mobileprovision and search as AppStore_com.company.

[12:50:50]: No matching provisioning profiles found for 'AppStore_com.company'

##### Command executed
fastlane match import --git_branch company -u xxx -a com.company -b XXX --type appstore

execute as action
match(
		app_identifier: com.company,
		type: "appstore",
		username: xxx
		team_id: XXX
		git_branch: company
	)

##### Complete output when running fastlane, including the stack trace and command used
[me]$ fastlane match import --git_branch company -u xxx -a com.company -b XXX --type appstore
[✔] 🚀 
[11:15:31]: Successfully loaded '/.../myproject/fastlane/Matchfile' 📄                                                 

+-----------------------+-----------------------------------------------------------+
|                    Detected Values from './fastlane/Matchfile'                    |
+-----------------------+-----------------------------------------------------------+
| git_url               | git@.../ios-certificates.git                                       |
| git_branch            | baseCompany
| type                  | enterprise                                                |
| app_identifier        | ["com.baseComanpy.one", "com.baaseComany.two"] |
| readonly              | true                                                      |
| clone_branch_directly | true                                                      |
+-----------------------+-----------------------------------------------------------+

[11:15:31]: Certificate (.cer) path:
/.../ios_distribution.cer                                        
[11:15:43]: Private key (.p12) path:
/.../ios.p12                                        
[11:15:48]: Provisioning profile (.mobileprovision or .provisionprofile) path or leave empty to skip this file:
/.../ios.mobileprovision                                              
[11:15:53]: Cloning remote git repo...
[11:15:55]: Checking out branch company...
[11:15:55]: 🔓  Successfully decrypted certificates repo
[11:15:55]: Repo is at: '/var/folders/7x/1clhqpgj54vcbg9s6k65ysmm0000gn/T/d20200806-42450-wrp2my'
Available session is not valid any more. Continuing with normal login.
[11:16:00]: 🔒  Successfully encrypted certificates repo
[11:16:00]: Pushing changes to remote git repo...
[11:16:05]: Finished uploading files to Git Repo [git@.../ios-certificates.git]

log of match action execution:
[12:50:03]: -------------------
[12:50:03]: --- Step: match ---
[12:50:03]: -------------------
[12:50:03]: Successfully loaded '/.../fastlane/Matchfile' 📄

+-----------------------+-----------------------------------------------------------+
|                    Detected Values from './fastlane/Matchfile'                    |
+-----------------------+-----------------------------------------------------------+
| git_url               | git@.../ios-certificates.git                              |
| git_branch            | baseComany                                                |
| type                  | enterprise                                                |
| app_identifier        | ["com.baseComany.one", "com.baseComany.two"]              |
| readonly              | true                                                      |
| clone_branch_directly | true                                                      |
+-----------------------+-----------------------------------------------------------+

+----------------------------+-----------------------------------------------------+
|                            Summary for match 2.154.0                             |
+----------------------------+-----------------------------------------------------+
| app_identifier             | ["com.comapny"]                                     |
| type                       | appstore                                            |
| username                   | ****                                 |
| team_id                    | ****                                          |
| git_branch                 | company                                             |
| readonly                   | true                                                |
| generate_apple_certs       | true                                                |
| skip_provisioning_profiles | false                                               |
| storage_mode               | git                                                 |
| git_url                    | git@.../ios-certificates.git                        |
| shallow_clone              | false                                               |
| clone_branch_directly      | true                                                |
| keychain_name              | login.keychain                                      |
| force                      | false                                               |
| force_for_new_devices      | false                                               |
| skip_confirmation          | false                                               |
| skip_docs                  | false                                               |
| platform                   | ios                                                 |
| fail_on_name_taken         | false                                               |
| verbose                    | false                                               |
+----------------------------+-----------------------------------------------------+

[12:50:03]: Cloning remote git repo...
[12:50:05]: Checking out branch company..
[12:50:05]: 🔓  Successfully decrypted certificates repo
[12:50:05]: Installing certificate...
[12:50:05]: Keychain password for /.../login.keychain-db was not specified and not found in your keychain. Specify the 'keychain_password' option to prevent the UI permission popup when code signing
[12:50:05]: Setting key partition list... (this can take a minute if there are a lot of keys installed)
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
[12:50:05]: 
[12:50:05]: Could not configure imported keychain item (certificate) to prevent UI permission popup when code signing
Check if you supplied the correct `keychain_password` for keychain: `/.../login.keychain-db`
security: SecKeychainItemSetAccessWithPassword: The user name or passphrase you entered is not correct.
[12:50:05]: 
[12:50:05]: Please look at the following docs to see how to set a keychain password:
[12:50:05]:  - https://docs.fastlane.tools/actions/sync_code_signing
[12:50:05]:  - https://docs.fastlane.tools/actions/get_certificates

+-------------------+------------------------------------------+
|                    Installed Certificate                     |
+-------------------+------------------------------------------+
| User ID           | ****                               |
| Common Name       | iPhone Distribution: company (****) |
| Organisation Unit | ****                               |
| Organisation      | company                                  |
| Country           | DE                                       |
| Start Datetime    | 2020-02-24 14:40:29 UTC                  |
| End Datetime      | 2021-02-23 14:40:29 UTC                  |
+-------------------+------------------------------------------+

[12:50:05]: No matching provisioning profiles found for 'AppStore_com.company'
[12:50:05]: A new one cannot be created because you enabled `readonly`
[12:50:05]: If you are certain that a profile should exist, double-check the recent changes to your match repository
+-------------------------+--------------------------------------------------------------------------------------------------------+
|                                                           Lane Context                                                           |
+-------------------------+--------------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM        | ios                                                                                                    |
| PLATFORM_NAME           | ios                                                                                                    |
| LANE_NAME               | ios build                                                                                              |
| ACIDGETXCODEPROJECTNAME | /.../ios/company_project.xcodeproj   |
| VERSION_NUMBER          | 1.6.1                                                                                                  |
| ACIDGETGITTAGS          | master-1.6.1-76                                                                                        |
|                         | master-1.6.1-77                                                                                        |
|                         | master-1.6.1-78                                                                                        |
|                         | master-1.6.1-79                                                                                        |
| BUILD_NUMBER            | 79                                                                                                     |
| FL_CHANGELOG            |                                                                                                        |
| ACIDISREACTNATIVE       | true                                                                                                   |
| ACIDISTFLUTTER          | false                                                                                                  |
| ACIDGETACTIONFORGYM     | workspace                                                                                              |
| ACIDGETFILENAMEFORGYM   | /.../ios/company_project.xcworkspace |
+-------------------------+--------------------------------------------------------------------------------------------------------+
[12:50:05]: No matching provisioning profiles found and can not create a new one because you enabled `readonly`. Check the output above for more information.

### Environment

bundle exec fastlane env

[13:46:30]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables

[13:46:32]: Generating fastlane environment output, this might take a few seconds...

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.6                                     |
| Ruby                        | 2.6.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.28.0                          |
| Installation Source         | /usr/local/rvm/gems/ruby-2.6.1/bin/fastlane |
| Host                        | Mac OS X 10.15.6 (19G73)                    |
| Ruby Lib Dir                | /usr/local/rvm/rubies/ruby-2.6.1/lib        |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.4.1                                      |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

sry, no fastlane posted here. All i can say here is that before match, as described above, just appicon() is called.

</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.154.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                             | Version | Update-Status |
| ---------------------------------- | ------- | ------------- |
| fastlane-plugin-badge              | 1.4.0   | ✅ Up-To-Date  |
| fastlane-plugin-appicon            | 0.15.0  | ✅ Up-To-Date  |
| fastlane-plugin-android_versioning | 0.5.3   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                | Version      |
| ---------------------------------- | ------------ |
| did_you_mean                       | 1.3.0        |
| bundler                            | 2.1.4        |
| rake                               | 13.0.1       |
| CFPropertyList                     | 3.0.2        |
| concurrent-ruby                    | 1.1.6        |
| i18n                               | 0.9.5        |
| minitest                           | 5.14.1       |
| thread_safe                        | 0.3.6        |
| tzinfo                             | 1.2.7        |
| activesupport                      | 4.2.11.3     |
| public_suffix                      | 4.0.5        |
| addressable                        | 2.7.0        |
| httpclient                         | 2.8.3        |
| json                               | 2.3.1        |
| algoliasearch                      | 1.27.3       |
| atomos                             | 0.1.3        |
| aws-eventstream                    | 1.1.0        |
| aws-partitions                     | 1.351.0      |
| aws-sigv4                          | 1.2.1        |
| jmespath                           | 1.4.0        |
| aws-sdk-core                       | 3.104.3      |
| aws-sdk-kms                        | 1.36.0       |
| aws-sdk-s3                         | 1.75.0       |
| babosa                             | 1.0.3        |
| curb                               | 0.9.10       |
| fastimage                          | 2.2.0        |
| colored                            | 1.2          |
| highline                           | 1.7.10       |
| commander-fastlane                 | 4.4.6        |
| dotenv                             | 2.7.6        |
| emoji_regex                        | 3.0.0        |
| excon                              | 0.76.0       |
| multipart-post                     | 2.0.0        |
| faraday                            | 1.0.1        |
| unf_ext                            | 0.0.7.7      |
| unf                                | 0.1.4        |
| domain_name                        | 0.5.20190701 |
| http-cookie                        | 1.0.3        |
| faraday-cookie_jar                 | 0.0.6        |
| faraday_middleware                 | 1.0.0        |
| gh_inspector                       | 1.1.3        |
| jwt                                | 2.2.1        |
| memoist                            | 0.16.2       |
| multi_json                         | 1.15.0       |
| os                                 | 1.1.1        |
| signet                             | 0.14.0       |
| googleauth                         | 0.13.1       |
| mini_mime                          | 1.0.2        |
| declarative                        | 0.0.20       |
| declarative-option                 | 0.1.0        |
| uber                               | 0.1.0        |
| representable                      | 3.0.4        |
| retriable                          | 3.1.2        |
| google-api-client                  | 0.38.0       |
| digest-crc                         | 0.6.1        |
| google-cloud-env                   | 1.3.3        |
| google-cloud-errors                | 1.0.1        |
| google-cloud-core                  | 1.5.0        |
| google-cloud-storage               | 1.27.0       |
| mini_magick                        | 4.10.1       |
| plist                              | 3.5.0        |
| rubyzip                            | 2.3.0        |
| security                           | 0.1.3        |
| naturally                          | 2.2.0        |
| simctl                             | 1.6.8        |
| slack-notifier                     | 2.3.2        |
| terminal-notifier                  | 2.0.0        |
| unicode-display_width              | 1.7.0        |
| terminal-table                     | 1.8.0        |
| tty-screen                         | 0.8.1        |
| tty-cursor                         | 0.7.1        |
| tty-spinner                        | 0.9.3        |
| word_wrap                          | 1.0.0        |
| claide                             | 1.0.3        |
| colored2                           | 3.1.2        |
| nanaimo                            | 0.3.0        |
| xcodeproj                          | 1.17.1       |
| rouge                              | 2.0.7        |
| xcpretty                           | 0.3.0        |
| xcpretty-travis-formatter          | 1.0.0        |
| badge                              | 0.12.0       |
| fuzzy_match                        | 2.0.4        |
| nap                                | 1.1.0        |
| netrc                              | 0.11.0       |
| ffi                                | 1.13.1       |
| ethon                              | 0.12.0       |
| typhoeus                           | 1.4.0        |
| cocoapods-core                     | 1.9.3        |
| cocoapods-deintegrate              | 1.0.4        |
| cocoapods-downloader               | 1.4.0        |
| cocoapods-plugins                  | 1.0.0        |
| cocoapods-search                   | 1.0.0        |
| cocoapods-stats                    | 1.1.0        |
| cocoapods-trunk                    | 1.5.0        |
| cocoapods-try                      | 1.2.0        |
| escape                             | 0.0.4        |
| fourflusher                        | 2.3.1        |
| molinillo                          | 0.6.6        |
| ruby-macho                         | 1.4.0        |
| cocoapods                          | 1.9.3        |
| fastlane-plugin-android_versioning | 0.5.3        |
| fastlane-plugin-appicon            | 0.15.0       |
| fastlane-plugin-badge              | 1.4.0        |
| mustache                           | 1.1.1        |
| open4                              | 1.3.4        |
| redcarpet                          | 3.5.0        |
| sassc                              | 2.4.0        |
| sqlite3                            | 1.4.2        |
| liferaft                           | 0.0.6        |
| xcinvoke                           | 0.3.0        |
| jazzy                              | 0.13.5       |
</details>

*generated on:* **2020-08-06**
</details>

**Comment by JorisDuboisDPG** [comment]
We are facing the exact same issue at this moment. Thanks for creating this report.

**Comment by JorisDuboisDPG** [comment]
As a workaround, you can manually commit the following change:
rename `/profiles/distribution/Distribution_com.company` to `/profiles/appstore/AppStore_com.company`

**Comment by Tobrek** [comment]
Any news at this issue?

**Comment by Tobrek** [comment]
Thanks to @DunbarXX 
A fix was released as part of fastlane 2.159.0
