### ISSUE TITLE
Fastlane Match issue: A relationship in the provided entity is not allowed for this request

### ISSUE THREAD

**Issue by AndriiTsok** [fastlane/fastlane#17013]
We are experiencing an issue with Match for appstore.

>> No devices can be associated to Provisioning Profiles for the App Store.

An error occurred while verifying your certificates and profiles with the Apple Developer Portal.
If you already have your certificates stored in git, you can run `fastlane match` in readonly mode
to just install the certificates and profiles without accessing the Dev Portal.
To do so, just pass `readonly: true` to your match call.

bundler: failed to load command: fastlane (/Users/andriitsok/.bundle/ruby/2.6.0/bin/fastlane)
Spaceship::UnexpectedResponse: [!] {
  "errors" : [ {
    "id" : "5c9f46b9-6988-4355-9139-f09640b09e7d",
    "status" : "409",
    "code" : "ENTITY_ERROR.RELATIONSHIP.NOT_ALLOWED",
    "title" : "A relationship in the provided entity is not allowed for this request",
    "detail" : "No devices can be associated to Provisioning Profiles for the App Store."
  } ]
}
  /Users/andriitsok/.bundle/ruby/2.6.0/gems/fastlane-2.155.1/spaceship/lib/spaceship/connect_api/client.rb:158:in `handle_response'
  /Users/andriitsok/.bundle/ruby/2.6.0/gems/fastlane-2.155.1/spaceship/lib/spaceship/connect_api/provisioning/client.rb:82:in `proxy_post'
  /Users/andriitsok/.bundle/ruby/2.6.0/gems/fastlane-2.155.1/spaceship/lib/spaceship/connect_api/provisioning/client.rb:46:in `post'
  /Users/andriitsok/.bundle/ruby/2.6.0/gems/fastlane-2.155.1/spaceship/lib/spaceship/connect_api/provisioning/provisioning.rb:79:in `post_profiles'
  /Users/andriitsok/.bundle/ruby/2.6.0/gems/fastlane-2.155.1/spaceship/lib/spaceship/connect_api/models/profile.rb:73:in `create'
  /Users/andriitsok/.bundle/ruby/2.6.0/gems/fastlane-2.155.1/sigh/lib/sigh/runner.rb:170:in `create_profile!'
  /Users/andriitsok/.bundle/ruby/2.6.0/gems/fastlane-2.155.1/sigh/lib/sigh/runner.rb:42:in `run'
  /Users/andriitsok/.bundle/ruby/2.6.0/gems/fastlane-2.155.1/sigh/lib/sigh/manager.rb:8:in `start'
  /Users/andriitsok/.bundle/ruby/2.6.0/gems/fastlane-2.155.1/match/lib/match/generator.rb:103:in `generate_provisioning_profile'
  /Users/andriitsok/.bundle/ruby/2.6.0/gems/fastlane-2.155.1/match/lib/match/runner.rb:262:in `fetch_provisioning_profile'
  /Users/andriitsok/.bundle/ruby/2.6.0/gems/fastlane-2.155.1/match/lib/match/runner.rb:109:in `block (2 levels) in run'
  /Users/andriitsok/.bundle/ruby/2.6.0/gems/fastlane-2.155.1/match/lib/match/runner.rb:108:in `loop'
  /Users/andriitsok/.bundle/ruby/2.6.0/gems/fastlane-2.155.1/match/lib/match/runner.rb:108:in `block in run'
  /Users/andriitsok/.bundle/ruby/2.6.0/gems/fastlane-2.155.1/match/lib/match/runner.rb:107:in `each'
  /Users/andriitsok/.bundle/ruby/2.6.0/gems/fastlane-2.155.1/match/lib/match/runner.rb:107:in `run'
  /Users/andriitsok/.bundle/ruby/2.6.0/gems/fastlane-2.155.1/match/lib/match/commands_generator.rb:68:in `block (3 levels) in run'
  /Users/andriitsok/.bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/andriitsok/.bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/andriitsok/.bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/andriitsok/.bundle/ruby/2.6.0/gems/fastlane-2.155.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/andriitsok/.bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/andriitsok/.bundle/ruby/2.6.0/gems/fastlane-2.155.1/match/lib/match/commands_generator.rb:187:in `run'
  /Users/andriitsok/.bundle/ruby/2.6.0/gems/fastlane-2.155.1/match/lib/match/commands_generator.rb:25:in `start'
  /Users/andriitsok/.bundle/ruby/2.6.0/gems/fastlane-2.155.1/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
  /Users/andriitsok/.bundle/ruby/2.6.0/gems/fastlane-2.155.1/bin/fastlane:23:in `<top (required)>'
  /Users/andriitsok/.bundle/ruby/2.6.0/bin/fastlane:23:in `load'
  /Users/andriitsok/.bundle/ruby/2.6.0/bin/fastlane:23:in `<top (required)>'

Xcode 12 b4

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.0                                                           |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.27.0                                             |
| Installation Source         | ~/.bundle/ruby/2.6.0/bin/fastlane                              |
| Host                        | macOS 11.0 (20A5343i)                                          |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode-beta.app/Contents/Developer/               |
| Xcode Version               | 12.0                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build for App Store submission"
  lane :build_appstore do
    gym(
    export_method: "app-store",
    xcargs: "-allowProvisioningUpdates",
    include_bitcode:"true",
    include_symbols:"false",
    export_options: {
        method: "app-store",
        provisioningProfiles: { 
          "technology.tryon" => "match AppStore technology.tryon"
        }
    }
    )

  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("technology.tryon") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.155.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 2.1.4        |
| rake                      | 13.0.1       |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 4.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.352.0      |
| aws-sigv4                 | 1.2.1        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.104.3      |
| aws-sdk-kms               | 1.36.0       |
| aws-sdk-s3                | 1.75.0       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.0.0        |
| excon                     | 0.76.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 1.0.1        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.2.1        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| signet                    | 0.14.0       |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.27.0       |
| json                      | 2.3.1        |
| mini_magick               | 4.10.1       |
| plist                     | 3.5.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.17.1       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2020-08-06**
</details>

**Comment by bduyng** [comment]
@AndriiTsok I got the same problem and have to create the profile manually and just need to push it on match repo

**Comment by k-thorat** [comment]
I am getting this as well.  

Xcode 12 b4 and Fastlane 2.155.1

 "errors" : [ {
    "id" : "f61f4135-6a2d-400e-bf68-0772d1ec094d",
    "status" : "409",
    "code" : "ENTITY_ERROR.RELATIONSHIP.NOT_ALLOWED",
    "title" : "A relationship in the provided entity is not allowed for this request",
    "detail" : "No devices can be associated to Provisioning Profiles for the App Store."
  } ]

**Comment by jasperkuperus** [comment]
I've got the exact same issue. Just want to add that it works like a charm for `development` and only fails for `appstore`.

Another follow-up issue here: When Fastlane attempts to search for similar issues here on Github, that fails also:

```
Looking for related GitHub issues on fastlane/fastlane...
Search query: {
  "errors" : [ {
    "id" : "ccc1ba25-8527-4bd7-b6b4-354b4f012f5d",
    "status" : "409",
    "code" : "ENTITY_ERROR.RELATIONSHIP.NOT_ALLOWED",
    "title" : "A relationship in the provided entity is not allowed for this request",
    "detail" : "No devices can be associated to Provisioning Profiles for the App Store."
  } ]
}

URL: https://api.github.com/search/issues?q=%7B%0A%20%20%22errors%22%20%3A%20%5B%20%7B%0A%20%20%20%20%22id%22%20%3A%20%22ccc1ba25-8527-4bd7-b6b4-354b4f012f5d%22%2C%0A%20%20%20%20%22status%22%20%3A%20%22409%22%2C%0A%20%20%20%20%22code%22%20%3A%20%22ENTITY_ERROR.RELATIONSHIP.NOT_ALLOWED%22%2C%0A%20%20%20%20%22title%22%20%3A%20%22A%20relationship%20in%20the%20provided%20entity%20is%20not%20allowed%20for%20this%20request%22%2C%0A%20%20%20%20%22detail%22%20%3A%20%22No%20devices%20can%20be%20associated%20to%20Provisioning%20Profiles%20for%20the%20App%20Store.%22%0A%20%20%7D%20%5D%0A%7D+repo:fastlane/fastlane
ERROR [2020-08-07 10:03:24.35]: Error finding relevant GitHub issues: undefined method `map' for nil:NilClass
```

Maybe the Github search should be reported as a separate issue. Do let me know if that's the case.

**Comment by ir-fuel** [comment]
+1 Exactly the same issue here

```
[10:32:36]: Creating new provisioning profile for '.....' with name 'match AppStore .....' for 'ios' platform
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
[10:32:52]: An error occurred while verifying your certificates and profiles with the Apple Developer Portal.
[10:32:52]: If you already have your certificates stored in git, you can run `fastlane match` in readonly mode
[10:32:52]: to just install the certificates and profiles without accessing the Dev Portal.
[10:32:52]: To do so, just pass `readonly: true` to your match call.

Looking for related GitHub issues on fastlane/fastlane...

Traceback (most recent call last):
	26: from /usr/local/bin/fastlane:23:in `<main>'
	25: from /usr/local/bin/fastlane:23:in `load'
	24: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.155.1/bin/fastlane:23:in `<top (required)>'
	23: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.155.1/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	22: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.155.1/match/lib/match/commands_generator.rb:25:in `start'
	21: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.155.1/match/lib/match/commands_generator.rb:187:in `run'
	20: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	19: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.155.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	18: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	17: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	16: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	15: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.155.1/match/lib/match/commands_generator.rb:68:in `block (3 levels) in run'
	14: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.155.1/match/lib/match/runner.rb:107:in `run'
	13: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.155.1/match/lib/match/runner.rb:107:in `each'
	12: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.155.1/match/lib/match/runner.rb:108:in `block in run'
	11: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.155.1/match/lib/match/runner.rb:108:in `loop'
	10: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.155.1/match/lib/match/runner.rb:109:in `block (2 levels) in run'
	 9: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.155.1/match/lib/match/runner.rb:262:in `fetch_provisioning_profile'
	 8: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.155.1/match/lib/match/generator.rb:103:in `generate_provisioning_profile'
	 7: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.155.1/sigh/lib/sigh/manager.rb:8:in `start'
	 6: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.155.1/sigh/lib/sigh/runner.rb:42:in `run'
	 5: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.155.1/sigh/lib/sigh/runner.rb:170:in `create_profile!'
	 4: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.155.1/spaceship/lib/spaceship/connect_api/models/profile.rb:73:in `create'
	 3: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.155.1/spaceship/lib/spaceship/connect_api/provisioning/provisioning.rb:79:in `post_profiles'
	 2: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.155.1/spaceship/lib/spaceship/connect_api/provisioning/client.rb:46:in `post'
	 1: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.155.1/spaceship/lib/spaceship/connect_api/provisioning/client.rb:82:in `proxy_post'
/usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.155.1/spaceship/lib/spaceship/connect_api/client.rb:158:in `handle_response': \e[31m[!] { (Spaceship::UnexpectedResponse)
  "errors" : [ {
    "id" : "a80af33d-5aa5-41ec-9895-fc3eb7b86856",
    "status" : "409",
    "code" : "ENTITY_ERROR.RELATIONSHIP.NOT_ALLOWED",
    "title" : "A relationship in the provided entity is not allowed for this request",
    "detail" : "No devices can be associated to Provisioning Profiles for the App Store."
  } ]
}\e[0m
```

**Comment by ir-fuel** [comment]
This is with Xcode 11 btw. It's not related to the beta.

**Comment by nordfogel** [comment]
`sync_code_signing` from within our fastfile works like a charm with fastlane **2.153.0** but for **2.155.1** we constantly run into issues for our enterprise account, creating some in-house certificates:
```
{
  "errors" : [ {
    "id" : "588f6328-XXXX-YYYY-ZZZZ-72c8facg3da4",
    "status" : "409",
    "code" : "ENTITY_ERROR",
    "title" : "There is a problem with the request entity",
    "detail" : "There cannot be any devices associated to universal provisioning profiles."
  } ]
}
```

[Xcode 11.6]

**Comment by jasperkuperus** [comment]
> `sync_code_signing` from within our fastfile works like a charm with fastlane **2.153.0** but for **2.155.1** we constantly run into issues for our enterprise account, creating some in-house certificates:

Ah. Indeed, I upgraded this morning to *2.155.1*. So, upgrading to *2.154.0* did the trick for me:

```
gem uninstall fastlane --all
gem install fastlane --version 2.154.0
```

**Comment by bepicgco** [comment]
I have the or a simmilar issue I think.
Downgrading did not work for me.

[12:40:48]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Traceback (most recent call last):
	34: from /usr/local/bin/fastlane:23:in `<main>'
	33: from /usr/local/bin/fastlane:23:in `load'
	32: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.1/bin/fastlane:23:in `<top (required)>'
	31: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	30: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	29: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.1/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	28: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	27: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	26: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	25: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	24: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	23: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	22: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	21: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	20: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	19: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	16: from Fastfile:42:in `block (2 levels) in parsing_binding'
	15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.1/fastlane/lib/fastlane/actions/get_provisioning_profile.rb:19:in `run'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.1/sigh/lib/sigh/manager.rb:8:in `start'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.1/sigh/lib/sigh/runner.rb:42:in `run'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.1/sigh/lib/sigh/runner.rb:170:in `create_profile!'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.1/spaceship/lib/spaceship/connect_api/models/profile.rb:73:in `create'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.1/spaceship/lib/spaceship/connect_api/provisioning/provisioning.rb:79:in `post_profiles'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.1/spaceship/lib/spaceship/connect_api/provisioning/client.rb:46:in `post'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.1/spaceship/lib/spaceship/connect_api/provisioning/client.rb:82:in `proxy_post'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.1/spaceship/lib/spaceship/connect_api/client.rb:158:in `handle_response': [!] { (Spaceship::UnexpectedResponse)
  "errors" : [ {
    "id" : "5ef8fac5-f71a-428d-a1dc-83e56198cd33",
    "status" : "409",
    "code" : "ENTITY_ERROR",
    "title" : "There is a problem with the request entity",
    "detail" : "There cannot be any devices associated to universal provisioning profiles."
  } ]
}
build failed.

**Comment by jasperkuperus** [comment]
> 32: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.1/bin/fastlane:23:in `<top (required)>' 31: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'

I guess your downgrade didn't go as planned. You're still using `2.155.1`.

**Comment by joshdholtz** [comment]
Just woke up and looking into right away!

**Comment by bepicgco** [comment]
> > 32: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.1/bin/fastlane:23:in `<top (required)>' 31: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
> 
> @bepicgco I guess your downgrade didn't go as planned. You're still using `2.155.1`.

Thank you for noticing that. After getting the downgrade to work, my build does work again indeed!
I will update my report to reflect that.

**Comment by joshdholtz** [comment]
Found the issue! My apologies 😔 I should have a release out in an hour or so

**Comment by jasperkuperus** [comment]
> Found the issue! My apologies 😔 I should have a release out in an hour or so

Thanks a lot for the fast response!

**Comment by joshdholtz** [comment]
Sorry for injecting the issue 😇

**Comment by joshdholtz** [comment]
Making release now! Release will be out in about 25 minutes

**Comment by joshdholtz** [comment]
This is released in `2.155.2` 💪 Sorry again! ❤️

**Comment by Vyazovoy** [comment]
@joshdholtz , when will it be available in [RubyGems](https://rubygems.org/gems/fastlane)?

**Comment by joshdholtz** [comment]
@Vyazovoy Woah! It should have been up there 😱 Looking into it! I pressed the button

**Comment by joshdholtz** [comment]
Sorry about that! Try now 😊

**Comment by Vyazovoy** [comment]
Now it works. Thank you, Josh!

**Comment by joshdholtz** [comment]
Np! Sorry again. Not sure why that didn't go through 🤷‍♂️ Also, there will be a 2.155.3 coming later this evening with one more small fix 😉

**Comment by Batuhan-Akkaya** [comment]
How can i fix this error? I ran this command **sudo gem install fastlane** but still same problem
```
{
  "errors" : [ {
    "id" : "c6d74f18-4ca6-414c-8223-812540c6ff82",
    "status" : "409",
    "code" : "ENTITY_ERROR.RELATIONSHIP.NOT_ALLOWED",
    "title" : "A relationship in the provided entity is not allowed for this request",
    "detail" : "No devices can be associated to Provisioning Profiles for the App Store."
  } ]
}
```
