### ISSUE TITLE
fastlane swift runner error

### ISSUE THREAD

**Issue by On1Key** [fastlane/fastlane#17029]
#<Thread:0x00007f9448bf4300@/Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.3/fastlane/lib/fastlane/swift_lane_manager.rb:220 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.3/fastlane/lib/fastlane/swift_lane_manager.rb:223:in `block in start_socket_thread'
	8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.3/fastlane/lib/fastlane/server/socket_server.rb:38:in `start'
	7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.3/fastlane/lib/fastlane/server/socket_server.rb:158:in `listen'
	6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.3/fastlane/lib/fastlane/server/socket_server.rb:49:in `receive_and_process_commands'
	5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.3/fastlane/lib/fastlane/server/socket_server.rb:49:in `loop'
	4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.3/fastlane/lib/fastlane/server/socket_server.rb:62:in `block in receive_and_process_commands'
	3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.3/fastlane/lib/fastlane/server/socket_server.rb:81:in `parse_and_execute_command'
	2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.3/fastlane/lib/fastlane/server/command_parser.rb:12:in `parse'
	1: from /Library/Ruby/Gems/2.6.0/gems/json-2.3.1/lib/json/common.rb:263:in `parse'
/Library/Ruby/Gems/2.6.0/gems/json-2.3.1/lib/json/common.rb:263:in `parse': 784: unexpected token at '' (JSON::ParserError)
[18:36:25]: ▸ sh: line 1: 41011 Illegal instruction: 4  ./fastlane/FastlaneRunner lane ipaLane swiftServerPort 2000 > /dev/null
+-----------+---------+
|    Lane Context     |
+-----------+---------+
| LANE_NAME | ipaLane |
+-----------+---------+
[18:36:25]: 784: unexpected token at ''
#<Thread:0x00007f944912ccf0@/Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.3/fastlane/lib/fastlane/swift_lane_manager.rb:96 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.3/fastlane/lib/fastlane/swift_lane_manager.rb:97:in `block in cruise_swift_lane_in_thread'
	3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.3/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
	2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.3/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.3/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.3/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': Exit status of command './fastlane/FastlaneRunner lane ipaLane swiftServerPort 2000 > /dev/null' was 132 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
sh: line 1: 41011 Illegal instruction: 4  ./fastlane/FastlaneRunner lane ipaLane swiftServerPort 2000 > /dev/null
[18:36:25]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Traceback (most recent call last):
	9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.3/fastlane/lib/fastlane/swift_lane_manager.rb:223:in `block in start_socket_thread'
	8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.3/fastlane/lib/fastlane/server/socket_server.rb:38:in `start'
	7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.3/fastlane/lib/fastlane/server/socket_server.rb:158:in `listen'
	6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.3/fastlane/lib/fastlane/server/socket_server.rb:49:in `receive_and_process_commands'
	5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.3/fastlane/lib/fastlane/server/socket_server.rb:49:in `loop'
	4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.3/fastlane/lib/fastlane/server/socket_server.rb:62:in `block in receive_and_process_commands'
	3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.3/fastlane/lib/fastlane/server/socket_server.rb:81:in `parse_and_execute_command'
	2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.155.3/fastlane/lib/fastlane/server/command_parser.rb:12:in `parse'
	1: from /Library/Ruby/Gems/2.6.0/gems/json-2.3.1/lib/json/common.rb:263:in `parse'
/Library/Ruby/Gems/2.6.0/gems/json-2.3.1/lib/json/common.rb:263:in `parse': [!] 784: unexpected token at '' (JSON::ParserError)

**Comment by On1Key** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.4                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.4 (19E266)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.5                                                           |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

```ruby
// This file contains the fastlane.tools configuration
// You can find the documentation at https://docs.fastlane.tools
//
// For a list of all available actions, check out
//
//     https://docs.fastlane.tools/actions
//

import Foundation

class Fastfile: LaneFile {
    
     @discardableResult private func updateBuildNum() -> String{
        let timeFormat = DateFormatter()
        timeFormat.dateFormat = "YYYYMMddHHmmss"
        let buildNumber = timeFormat.string(from: Date())
        setInfoPlistValue(key: versionKey, value: buildNumber, path: infoPath)
        return buildNumber
    }
    private func buildIpaLane() {
        updateBuildNum()
        gym()
    }
    private func uploadPgyLane(withOptions options:[String: String]?) {
        var desc = ""
        if let des = options?[pgyerDesc] {
            desc = des + "\n"
        }
        pgyer(
            apiKey: pgyerApiKey,
            userKey: pgyerUserkey,
            updateDescription: "\(desc)update_shtfwz_\(getInfoPlistValue(key: versionKey, path: infoPath))"
            )
    }
    private func msgDingTalkLane(withOptions options:[String: String]?) {
        var desc = "update"
        if let des = options?[dingTalkDesc] {
            desc = des
        }
        let title = "[\(dingTalkKey)]upload"
        let format = DateFormatter()
        format.dateFormat = "MM-dd HH:mm:ss"
        let mdText =
        """
        #### \(title)
        > ###### \(format.string(from: Date()))
        """
        dingTalkMsgMdPush(title: title, token: dingTalkAccessToken, text: mdText)
    }
    func ipaLane() {
        buildIpaLane()
    }
    func pgyLane(withOptions options:[String: String]?) {
        buildIpaLane()
        uploadPgyLane(withOptions: options)
        msgDingTalkLane(withOptions: options)
    }
}

```
</details>

**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.155.3 | 💥 Check failed |


### Loaded fastlane plugins:

| Plugin                             | Version | Update-Status  |
| ---------------------------------- | ------- | -------------- |
| fastlane-plugin-pgyer              | 0.2.2   | 💥 Check failed |
| fastlane-plugin-ding_talk_msg_push | 0.1.2   | 💥 Check failed |


<details><summary><b>Loaded gems</b></summary>

| Gem                                | Version      |
| ---------------------------------- | ------------ |
| did_you_mean                       | 1.3.0        |
| slack-notifier                     | 2.3.2        |
| rouge                              | 2.0.7        |
| xcpretty                           | 0.3.0        |
| terminal-notifier                  | 2.0.0        |
| terminal-table                     | 1.8.0        |
| plist                              | 3.5.0        |
| addressable                        | 2.7.0        |
| multipart-post                     | 2.0.0        |
| word_wrap                          | 1.0.0        |
| tty-cursor                         | 0.7.1        |
| tty-spinner                        | 0.9.3        |
| babosa                             | 1.0.3        |
| colored                            | 1.2          |
| highline                           | 1.7.10       |
| commander-fastlane                 | 4.4.6        |
| unf                                | 0.1.4        |
| domain_name                        | 0.5.20190701 |
| http-cookie                        | 1.0.3        |
| faraday-cookie_jar                 | 0.0.6        |
| faraday                            | 1.0.1        |
| faraday_middleware                 | 1.0.0        |
| gh_inspector                       | 1.1.3        |
| mini_magick                        | 4.10.1       |
| rubyzip                            | 2.3.0        |
| security                           | 0.1.3        |
| xcpretty-travis-formatter          | 1.0.0        |
| bundler                            | 2.0.1        |
| naturally                          | 2.2.0        |
| simctl                             | 1.6.8        |
| uber                               | 0.1.0        |
| declarative-option                 | 0.1.0        |
| representable                      | 3.0.4        |
| retriable                          | 3.1.2        |
| mini_mime                          | 1.0.2        |
| httpclient                         | 2.8.3        |
| google-api-client                  | 0.38.0       |
| nanaimo                            | 0.3.0        |
| colored2                           | 3.1.2        |
| claide                             | 1.0.3        |
| CFPropertyList                     | 3.0.2        |
| atomos                             | 0.1.3        |
| xcodeproj                          | 1.17.1       |
| unicode-display_width              | 1.7.0        |
| public_suffix                      | 4.0.5        |
| tty-screen                         | 0.8.1        |
| excon                              | 0.76.0       |
| unf_ext                            | 0.0.7.7      |
| fastimage                          | 2.2.0        |
| json                               | 2.3.1        |
| dotenv                             | 2.7.6        |
| jwt                                | 2.2.1        |
| declarative                        | 0.0.20       |
| multi_json                         | 1.15.0       |
| signet                             | 0.14.0       |
| os                                 | 1.1.1        |
| memoist                            | 0.16.2       |
| googleauth                         | 0.13.1       |
| rake                               | 13.0.1       |
| digest-crc                         | 0.6.1        |
| google-cloud-errors                | 1.0.1        |
| google-cloud-env                   | 1.3.3        |
| google-cloud-core                  | 1.5.0        |
| google-cloud-storage               | 1.27.0       |
| emoji_regex                        | 3.0.0        |
| aws-eventstream                    | 1.1.0        |
| aws-sigv4                          | 1.2.1        |
| aws-partitions                     | 1.350.0      |
| jmespath                           | 1.4.0        |
| aws-sdk-core                       | 3.104.3      |
| aws-sdk-kms                        | 1.36.0       |
| aws-sdk-s3                         | 1.75.0       |
| forwardable                        | 1.2.0        |
| logger                             | 1.3.0        |
| stringio                           | 0.0.2        |
| ipaddr                             | 1.2.2        |
| openssl                            | 2.1.2        |
| ostruct                            | 0.1.0        |
| strscan                            | 1.0.0        |
| date                               | 2.0.0        |
| fileutils                          | 1.1.0        |
| etc                                | 1.0.1        |
| io-console                         | 0.4.7        |
| zlib                               | 1.0.0        |
| libxml-ruby                        | 3.1.0        |
| rexml                              | 3.1.9        |
| psych                              | 3.1.0        |
| mutex_m                            | 0.1.0        |
| webrick                            | 1.4.2        |
| fastlane-plugin-pgyer              | 0.2.2        |
| fastlane-plugin-ding_talk_msg_push | 0.1.2        |
</details>


*generated on:* **2020-08-11**
</details>

**Comment by saltyskip** [comment]
Bump

**Comment by rogerluan** [comment]
@On1Key please follow the guidelines on how to open an issue. I have no context on what you were trying to accomplish when this happened. Also, updating to the latest version of fastlane might help you.

@saltyskip could you share your experience as well, please? What were you doing when you faced the issue, and what's your environment like (`[bundle exec] fastlane env`) 🙏 

This will enable us to help you in a timely manner.
