### ISSUE TITLE
2 step verification session times out too fast

### ISSUE THREAD

**Issue by ir-fuel** [fastlane/fastlane#17027]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

the token I copy-pasted as described here:

https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification

Already stopped working after 48 hours

##### Complete output when running fastlane, including the stack trace and command used

```
[21:10:59]: Login to App Store Connect (***)
Session loaded from environment variable is not valid. Continuing with normal login.
Two-factor Authentication (6 digits code) is enabled for account '***'
More information about Two-factor Authentication: https://support.apple.com/en-us/HT204915

If you're running this in a non-interactive session (e.g. server or CI)
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification

Please enter the 6 digit code you received at +32 •••• •• •• 08:
```

### Environment

Fastlane on CircleCI
<details>
  <pre> </pre>
</details>

**Comment by rogerluan** [comment]
See this article https://drobinin.com/posts/keep-using-fastlane-with-apples-2fa-changes/
The author says the session lasts 6-8 hours, but that may be further decreased in certain scenarios. The session expiration is out of _fastlane's_ control.

If you read the whole article, you'll see that currently there's no good way to solve 2FA issues. Maybe you'll find a more suitable way to solve the 2FA issues in your specific project, by reading the article.

Related ticket: https://github.com/fastlane/fastlane/issues/16956

**Comment by ir-fuel** [comment]
Got it!

**Comment by alex-benoit** [comment]
It seems that the token is invalidated if you login with another browser with the same user. Try with a dedicated CI appstore connect email.

**Comment by ir-fuel** [comment]
@alex-benoit I tried this, but it still invalidates after a couple of days.

**Comment by evgeniisage** [comment]
I'm running app resigning and upload to App Store on a MAC agent hosted by Azure DevOps. The session token is added to an environment variable and service connection settings. Yesterday I updated the session token as it was due to expire and performed an upload of an app and it worked like a charm. Today when I tried to upload another app, I got the error message about the token being invalid. After I updated the environment variable and service connection settings with **the same exact session token**, I got the following output:

```
[17:30:56]: Login to App Store Connect (***)
Session loaded from environment variable **is not valid**. Continuing with normal login.
[17:30:58]: Login successful
[17:31:01]: Ready to upload new build to TestFlight (App: 1456359260)...
[17:31:01]: Fetching password for transporter from environment variable named `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`
[17:32:16]: iTunes Transporter successfully finished its job
[17:32:16]: Fetching password for transporter from environment variable named `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`
[17:32:16]: Going to upload updated app to App Store Connect
[17:32:16]: This might take a few minutes. Please don't interrupt the script.
[17:32:50]: iTunes Transporter successfully finished its job
[17:32:50]: --------------------------------------------------------------------
[17:32:50]: Successfully uploaded package to App Store Connect. It might take a few minutes until it's visible online.
```

How come the session is invalid but login still completed successfully? What can be done for the pipeline to start failing the day after updating the session token? This is quite annoying.

**Comment by rogerluan** [comment]
@ir-fuel @alex-benoit heads up that the App Store Connect API and _fastlane_ now support [JWT auth](https://docs.fastlane.tools/app-store-connect-api/#use-return-value-and-pass-in-as-an-option), it replaces the need for user/pass credentials, and thus 2FA :)
