### ISSUE TITLE
Changelog.txt is not used while sending build to TestFlight

### ISSUE THREAD

**Issue by bdolewski** [fastlane/fastlane#17030]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm using command `upload_to_testflight` and my `fastlane/changelog.txt` is filled with changes but nothing is visible on TestFlight app or AppStore Command

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 10.15.6                                                 |
| Ruby                        | 2.7.1                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.28.0                                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.155.3/libexec/bin/fastlane |
| Host                        | Mac OS X 10.15.6 (19G73)                                |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.7.1_2/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1f  31 Mar 2020                             |
| Is contained                | false                                                   |
| Is homebrew                 | false                                                   |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 11.6                                                    |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | pl_PL.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

app_scheme = "fsa_ios"
app_test_scheme = "fsa_ios"
app_xcodeproj = "#{app_scheme}.xcodeproj"
app_identifier = "com.fieldcode.fsa"
app_production_profile = "FSA AppStore TestFlight Profile"


platform :ios do
  desc "Change build number. Options: xcodeproj, build_number"
  lane :bump_build_number do |options|
    increment_build_number(
      xcodeproj: options[:xcodeproj],
      build_number: options[:build_number]
    )
  end

  desc "Apply tag to a build. Options: version_number, build_number"
  lane :apply_tag do |options|
    add_git_tag(
      tag: "build/v#{options[:version_number]}-build-#{options[:build_number]}"
    )
  end

  desc "Run unit tests"
  lane :unit_tests do
    scan
  end
  
  lane :lint do
    swiftlint(
      reporter: "json",
      output_file: "fastlane/swiftlint.json"
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :deploy_to_TestFlight do
    # Ensure that your git status is not dirty
    ensure_git_status_clean

    # Test it, don't submit App when tests fail
    unit_tests

    # Increment the build number (not the version number)
    newBuildNumber = latest_testflight_build_number + 1
    
    # Update build number
    bump_build_number(
      xcodeproj: app_xcodeproj,
      build_number: newBuildNumber
    )

    # Commit the version bump
    commit_version_bump(
      xcodeproj: app_xcodeproj,
      message: "Build number bump to #{newBuildNumber}"
    )

    build_app(
      scheme: app_scheme,
      export_options: {
        provisioningProfiles: {
          app_identifier => app_production_profile
        }
      })
    
    # Actual deploy to TestFlight
    upload_to_testflight
    
    # Add a git tag for this build. 
    apply_tag(
      version_number: get_version_number(xcodeproj: app_xcodeproj),
      build_number: newBuildNumber
    )
    
    # Push the new commit and tag back to your git remote
    #push_to_git_remote
  end
end


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.fieldcode.fsa") # The bundle identifier of your app

itc_team_id("120152161") # App Store Connect Team ID
team_id("C6VKYU7JHS") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.155.3 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.17.1       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.76.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.2        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.1        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-storage      | 1.27.0       |
| emoji_regex               | 3.0.0        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.353.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.1        |
| aws-sdk-core              | 3.104.3      |
| aws-sdk-kms               | 1.36.0       |
| aws-sdk-s3                | 1.76.0       |
| uri                       | 0.10.0       |
| forwardable               | 1.3.1        |
| logger                    | 1.4.2        |
| cgi                       | 0.1.0        |
| timeout                   | 0.1.0        |
| stringio                  | 0.1.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.2.0        |
| strscan                   | 1.0.3        |
| date                      | 3.0.0        |
| delegate                  | 0.1.0        |
| fileutils                 | 1.4.1        |
| io-console                | 0.5.6        |
| zlib                      | 1.1.0        |
| singleton                 | 0.1.0        |
| rexml                     | 3.2.3        |
| open3                     | 0.1.0        |
| yaml                      | 0.1.0        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.6.0        |
</details>

*generated on

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by tylerjames** [comment]
Having the same issue. It appears to have been uploaded according to the terminal output, but the changelog never appears anywhere in TestFlight or AppStoreConnect
