### ISSUE TITLE
Snapshot is not saving Screenshots.

### ISSUE THREAD

**Issue by fatihyildizhan** [fastlane/fastlane#17039]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Snapshot is running without an error but screenshots are not saving in the folder. 
I am using fastlane 2.156.0.

Tried with unchecked Delete option too.
<img width="788" alt="uncheck" src="https://user-images.githubusercontent.com/602600/89942395-2754f000-dc25-11ea-8150-2b6139856e06.png">

##### Command executed
`fastlane snapshot`

##### Complete output when running fastlane, including the stack trace and command used
```
[21:14:18]: ▸ All tests
[21:14:18]: ▸ Test Suite AppUITests.xctest started
[21:14:18]: ▸ AppUITests
[21:16:18]: ▸     ✓ testExample (119.415 seconds)
[21:16:18]: ▸    Executed 1 test, with 0 failures (0 unexpected) in 119.415 (119.418) seconds
[21:16:18]: ▸ 
[21:16:18]: ▸ 2020-08-11 21:16:18.610 xcodebuild[28881:393290] [MT] IDETestOperationsObserverDebug: 121.247 elapsed -- Testing started completed.
[21:16:18]: ▸ 2020-08-11 21:16:18.610 xcodebuild[28881:393290] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
[21:16:18]: ▸ 2020-08-11 21:16:18.610 xcodebuild[28881:393290] [MT] IDETestOperationsObserverDebug: 121.247 sec, +121.247 sec -- end
[21:16:18]: ▸ Test execute Succeeded
[21:16:19]: Clearing Status Bar Override
[21:16:19]: $ xcrun simctl status_bar 8252281D-34FE-4BE1-AB24-57B9FBAD22A1 clear &> /dev/null
```

<img width="942" alt="Screen Shot 2020-08-11 at 21 18 46" src="https://user-images.githubusercontent.com/602600/89934382-27e78980-dc19-11ea-8d01-869b142da2af.png">

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.6                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.6 (19G73)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.6                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "app.xcworkspace", scheme: "app")
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.apps.app") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.156.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.17.1       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.76.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.1        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-storage      | 1.27.0       |
| emoji_regex               | 3.0.0        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.354.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.1        |
| aws-sdk-core              | 3.104.3      |
| aws-sdk-kms               | 1.36.0       |
| aws-sdk-s3                | 1.77.0       |
| CFPropertyList            | 3.0.2        |
| json                      | 2.3.1        |
| bundler                   | 2.1.4        |
| forwardable               | 1.3.1        |
| logger                    | 1.4.2        |
| stringio                  | 0.1.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.3        |
| date                      | 3.0.0        |
| fileutils                 | 1.4.1        |
| io-console                | 0.5.4        |
| zlib                      | 1.1.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.2.3        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.6.0        |
</details>

*generated on:* **2020-08-11**
</details>

**Comment by fatihyildizhan** [comment]
@joshdholtz Hi Josh, Do you have any suggestion for this issue?

**Comment by joshdholtz** [comment]
@fatihyildizhan I will try to look into this afternoon to see if I can replicate 💪

**Comment by fatihyildizhan** [comment]
Hi @joshdholtz Do you have any suggestions? I am still taking snapshots manually and couldn't fix this issue.

This is my Snapfile
```
# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
 "iPhone 11 Pro Max",
  # "iPhone 11",
  # "iPhone 8 Plus",
  # "iPad Pro (12.9-inch) (4th generation)"
])

languages([
  "en-US"
])
ios_version("13.6")
localize_simulator(true)
concurrent_simulators(false)

# The name of the scheme which contains the UI Tests
scheme("ScreenShots")

# File > Workspace Settings > Project Relative Deriver Data Location
derived_data_path("/Users/fatihyildizhan/Library/Developer/Xcode/DerivedData/saydim-cyleehnzprrpkjbhwtoljefqskgy")
test_without_building(true)

# Where should the resulting screenshots be stored?
output_directory("./screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
# clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception.
override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments([
#    "-uiTest YES"
# ])

# For more information about all available options run
fastlane action snapshot
```

**Comment by fatihyildizhan** [comment]
Is there any difference between `fastlane ios screenshots` and `fastlane snapshot` ?

**Comment by SchneMa** [comment]
I'm having the same problem running `snapshot` or `ios screenshots`. with Fastlane 2.157.3. 
Running commands with sudo leads to the following error:
**[!] File /Users/admin/Library/Developer/CoreSimulator/Devices/DD9D3F42-AA53-4551-9617-BD7BC444D376/device.plist not readable!**
I tried it on several devices and with options: erase_simulator, clean, and reinstall_app.

any news on this?

**Comment by fatihyildizhan** [comment]
@SchneMa Can you please share your Snapfile too. It can be helpful.

I still couldn't fix it. I am manually taking the screenshots.

**Comment by SchneMa** [comment]
```
# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
 devices([
   "iPhone 8 Plus",
#   "iPhone X",
#   "iPad Pro (12.9-inch)",
 ])

 languages([
   "de-DE"
 ])

# The name of the scheme which contains the UI Tests
scheme("UITestProject")

# Where should the resulting screenshots be stored?
 output_directory("./screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception.
# override_status_bar(true)
erase_simulator true 
clean true 
reinstall_app true

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot

```

**Comment by StuSchwartz** [comment]
I am having the same issue with 2.160.0
Right now screenshots are dead.

**Comment by hankinsoft** [comment]
Me too - #17464 (I'll close that as a duplicate).

**Comment by joshdholtz** [comment]
Snapshots are working for me 😔  But I'll be looking more into this tomorrow to see if I can replicate what's going on!

**Comment by fatihyildizhan** [comment]
I have an extra function to take ss Today Widget on SnapshotHelper.swift but when I remove this func, I am not able to get screenshots too. 

This may help you to replicate.

```
 open class func todaySnapshot(_ name: String, screenshot: XCUIScreenshot, timeWaitingForIdle timeout: TimeInterval = 20) {
          guard var simulator = ProcessInfo().environment["SIMULATOR_DEVICE_NAME"], let screenshotsDir = screenshotsDirectory else { return }

          do {
              let regex = try NSRegularExpression(pattern: "Clone [0-9]+ of ")
              let range = NSRange(location: 0, length: simulator.count)
              simulator = regex.stringByReplacingMatches(in: simulator, range: range, withTemplate: "")

              let path = screenshotsDir.appendingPathComponent("\(simulator)-\(name).png")
              try screenshot.pngRepresentation.write(to: path)
          } catch let error {
              NSLog("Problem writing screenshot: \(name) to \(screenshotsDir)/\(simulator)-\(name).png")
              NSLog(error.localizedDescription)
          }
  }
```

**Comment by MetaImi** [comment]
For me the issue was the M1 processor. It runs as ARM64 arch, and in the snapshot helper (// SnapshotHelperVersion [1.20]) I had to modify the pathPrefix function at line 224 and extend the condition with arch(arm64) to pick up the location.
