### ISSUE TITLE
Deliver: A relationship value is not acceptable for the current resource state. - The specified pre-release build could not be added

### ISSUE THREAD

**Issue by ppamorim** [fastlane/fastlane#17041]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: 2.156.0
- Last working version: 2.155.3

### Regression Description

Downgrading to 2.155.3 solves the issue.

```
...
+--------------------------+----------------------------+
|             Summary for precheck 2.156.0              |
+--------------------------+----------------------------+
| default_rule_level       | warn                       |
| include_in_app_purchases | false                      |
| app_identifier           | com.foo.bar |
| username                 | foo@bar.com               |
+--------------------------+----------------------------+

[23:44:31]: Checking app for precheck rule violations
[23:44:40]: ✅  Passed: No negative  sentiment
[23:44:40]: ✅  Passed: No placeholder text
[23:44:40]: ✅  Passed: No mentioning  competitors
[23:44:40]: ✅  Passed: No future functionality promises
[23:44:40]: ✅  Passed: No words indicating test content
[23:44:40]: ✅  Passed: No curse words
[23:44:40]: ✅  Passed: No words indicating your IAP is free
[23:44:40]: ✅  Passed: Incorrect, or missing copyright date
[23:44:43]: ✅  Passed: No broken urls
[23:44:43]: precheck 👮‍♀️ 👮  finished without detecting any potential problems 🛫
[23:44:43]: Selecting existing build-number: XX
[23:44:43]: Selecting build X.X.X (XX)...
[23:44:44]: A relationship value is not acceptable for the current resource state. - The specified pre-release build could not be added.
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.6                                     |
| Ruby                        | 2.7.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.23.0                          |
| Installation Source         | ~/.gem/bin/fastlane                         |
| Host                        | Mac OS X 10.15.6 (19G73)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.7.1_2/lib          |
| OpenSSL Version             | OpenSSL 1.1.1f  31 Mar 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.6                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

POSSIBLE_IDENTIFIER_ARRAY = Array["com.foo.bar"]
POSSIBLE_PLIST_ARRAY = Array["Info_Bar"]
POSSIBLE_SCHEME_ARRAY = Array["Bar"]
POSSIBLE_SCHEME_NICKNAME_ARRAY = Array[ "bar"]

desc "Send to review"
lane :review do

  submit_for_review = UI.confirm("Submit for review?")
  skip_screenshots = UI.confirm("Skip screenshots?")
  automatic_release = UI.confirm("Automatic release?")
  phased_release = UI.confirm("Phased release?")

  POSSIBLE_IDENTIFIER_ARRAY.each_with_index do |identifier, index|

    infoPlistPath = "./Foo/#{POSSIBLE_PLIST_ARRAY[index]}.plist"
    scheme = POSSIBLE_SCHEME_ARRAY[index]

    versionNumber = get_version_number_from_xcodeproj(
      xcodeproj: "./Bar.xcodeproj",
      target: scheme)

    buildNumber = get_build_number_from_xcodeproj(
      xcodeproj: "./Bar.xcodeproj",
      target: scheme)

    begin
      schemeNickname = POSSIBLE_SCHEME_NICKNAME_ARRAY[index]
      deliver(
        username: "foo@bar.com",
        app_identifier: identifier,
        submit_for_review: submit_for_review,
        force: true,
        automatic_release: automatic_release,
        phased_release: phased_release,
        skip_binary_upload: true,
        skip_app_version_update: true, //Recently added
        metadata_path: "./fastlane/metadata/#{schemeNickname}",
        screenshots_path: "./fastlane/screenshots/#{schemeNickname}",
        app_version: versionNumber,
        build_number: buildNumber,
        skip_screenshots: skip_screenshots,
        precheck_include_in_app_purchases: false,
        languages: ['en-US', 'en-GB'],
        submission_information: $submission_info)
    rescue => ex
      puts ex
    end
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# HIDDEN
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.156.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-appicon    | 0.15.0  | ✅ Up-To-Date  |
| fastlane-plugin-versioning | 0.4.3   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version      |
| -------------------------- | ------------ |
| did_you_mean               | 1.4.0        |
| slack-notifier             | 2.3.2        |
| rouge                      | 2.0.7        |
| xcpretty                   | 0.3.0        |
| terminal-notifier          | 2.0.0        |
| unicode-display_width      | 1.7.0        |
| terminal-table             | 1.8.0        |
| plist                      | 3.5.0        |
| CFPropertyList             | 3.0.2        |
| addressable                | 2.7.0        |
| multipart-post             | 2.0.0        |
| word_wrap                  | 1.0.0        |
| tty-cursor                 | 0.7.1        |
| tty-spinner                | 0.9.3        |
| babosa                     | 1.0.3        |
| colored                    | 1.2          |
| highline                   | 1.7.10       |
| commander-fastlane         | 4.4.6        |
| unf_ext                    | 0.0.7.7      |
| unf                        | 0.1.4        |
| domain_name                | 0.5.20190701 |
| http-cookie                | 1.0.3        |
| faraday-cookie_jar         | 0.0.6        |
| faraday                    | 1.0.1        |
| faraday_middleware         | 1.0.0        |
| gh_inspector               | 1.1.3        |
| mini_magick                | 4.10.1       |
| rubyzip                    | 2.3.0        |
| security                   | 0.1.3        |
| xcpretty-travis-formatter  | 1.0.0        |
| naturally                  | 2.2.0        |
| simctl                     | 1.6.8        |
| uber                       | 0.1.0        |
| declarative-option         | 0.1.0        |
| representable              | 3.0.4        |
| retriable                  | 3.1.2        |
| mini_mime                  | 1.0.2        |
| signet                     | 0.14.0       |
| httpclient                 | 2.8.3        |
| google-api-client          | 0.38.0       |
| uri                        | 0.10.0       |
| nanaimo                    | 0.3.0        |
| colored2                   | 3.1.2        |
| claide                     | 1.0.3        |
| atomos                     | 0.1.3        |
| xcodeproj                  | 1.17.1       |
| public_suffix              | 4.0.5        |
| tty-screen                 | 0.8.1        |
| excon                      | 0.76.0       |
| fastimage                  | 2.2.0        |
| json                       | 2.3.1        |
| dotenv                     | 2.7.6        |
| bundler                    | 2.1.4        |
| jwt                        | 2.2.1        |
| declarative                | 0.0.20       |
| multi_json                 | 1.15.0       |
| os                         | 1.1.1        |
| memoist                    | 0.16.2       |
| googleauth                 | 0.13.1       |
| rake                       | 13.0.1       |
| digest-crc                 | 0.6.1        |
| google-cloud-errors        | 1.0.1        |
| google-cloud-env           | 1.3.3        |
| google-cloud-core          | 1.5.0        |
| google-cloud-storage       | 1.27.0       |
| emoji_regex                | 3.0.0        |
| aws-eventstream            | 1.1.0        |
| aws-sigv4                  | 1.2.1        |
| aws-partitions             | 1.349.0      |
| jmespath                   | 1.4.0        |
| aws-sdk-core               | 3.104.3      |
| aws-sdk-kms                | 1.36.0       |
| aws-sdk-s3                 | 1.75.0       |
| forwardable                | 1.3.1        |
| logger                     | 1.4.2        |
| cgi                        | 0.1.0        |
| timeout                    | 0.1.0        |
| stringio                   | 0.1.0        |
| ipaddr                     | 1.2.2        |
| openssl                    | 2.1.2        |
| ostruct                    | 0.2.0        |
| strscan                    | 1.0.3        |
| date                       | 3.0.0        |
| delegate                   | 0.1.0        |
| fileutils                  | 1.4.1        |
| io-console                 | 0.5.6        |
| zlib                       | 1.1.0        |
| singleton                  | 0.1.0        |
| rexml                      | 3.2.3        |
| open3                      | 0.1.0        |
| yaml                       | 0.1.0        |
| psych                      | 3.1.0        |
| mutex_m                    | 0.1.0        |
| webrick                    | 1.6.0        |
| fastlane-plugin-appicon    | 0.15.0       |
| benchmark                  | 0.1.0        |
| fastlane-plugin-versioning | 0.4.3        |
</details>

*generated on:* **2020-08-11**
</details>

**Comment by tmm1** [comment]
I also see this with 2.155.1

> Spaceship::UnexpectedResponse: [!] A relationship value is not acceptable for the current resource state. - The specified pre-release build could not be added.
>gems/ruby/2.6.0/gems/fastlane-2.155.1/spaceship/lib/spaceship/connect_api/client.rb:163:in `handle_response'

**Comment by tmm1** [comment]
In my case the build was already submitted. Removing from review and running deliver again worked.

**Comment by eXhausted** [comment]
I faced the same issue. The build was in processing when I tried to submit it. You need to pass `build_number: "latest"` to the `deliver` if you want to Fastlane to wait for processing. I found only one reference to this function in the submit code: https://github.com/fastlane/fastlane/blob/4a024011bd9ad788346d256d23e2ce28b0189101/deliver/lib/deliver/submit_for_review.rb#L47

**Comment by Thangaraj-M** [comment]
Getting this same error. The build is in Testing status only. When tried manually, it submitted successfully.

**Comment by tastafur** [comment]
me too fastlne 2.173.0
ERROR [2021-02-12 17:41:10.15]: A relationship value is not acceptable for the current resource state. - The specified pre-release build could not be added.

+------+---------------------------+-------------+
|                fastlane summary                |
+------+---------------------------+-------------+
| Step | Action                    | Time (in s) |
+------+---------------------------+-------------+
| 1    | default_platform          | 0           |
| 2    | setup_circle_ci           | 0           |
| 3    | app_store_connect_api_key | 0           |
| 4    | match                     | 1           |
| 5    | set_info_plist_value      | 0           |
| 6    | set_info_plist_value      | 0           |
| 7    | set_info_plist_value      | 0           |
| 8    | set_info_plist_value      | 0           |
| 9    | build_app                 | 1134        |
| 💥   | upload_to_app_store       | 747         |
+------+---------------------------+-------------+
