### ISSUE TITLE
upload_to_app_store failing when uploading no screenshots

### ISSUE THREAD

**Issue by pyrtsa** [fastlane/fastlane#17047]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: [e.g. `2.156.0`]
- Last working version: [e.g. `2.149.1`]

### Regression Description
In our setup we never had any screenshots to upload by Fastlane and `upload_to_app_store` worked fine. Having today updated to the latest Fastlane, uploads to App Store started failing with this error:

> Failed verification of all screenshots uploaded... 0 incomplete screenshot(s) still exist

This error is unexpected because we don't expect any screenshots to be uploaded so there's really nothing to verify about them either. (OTOH we never specified `skip_screenshots`.)

**As a workaround**, setting the environment variable `DELIVER_SKIP_SCREENSHOTS=true` made the upload pass.

The above error message was introduced by https://github.com/fastlane/fastlane/pull/16972, so I assume this to be a new regression in [`2.156.0`](https://github.com/fastlane/fastlane/releases/tag/2.156.0).

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
[13:55:26]: Will begin uploading snapshots for '3.2.1' on App Store Connect
[13:55:26]: Starting with the upload of screenshots...
[✔] Waiting for all the screenshots processed... 
[13:55:29]: Failed to upload all screenshots... Tries remaining: 4
[✔] Waiting for all the screenshots processed... 
[13:55:30]: Failed to upload all screenshots... Tries remaining: 3
[✔] Waiting for all the screenshots processed... 
[13:55:32]: Failed to upload all screenshots... Tries remaining: 2
[✔] Waiting for all the screenshots processed... 
[13:55:34]: Failed to upload all screenshots... Tries remaining: 1
[✔] Waiting for all the screenshots processed... 
...
[13:55:35]: Failed verification of all screenshots uploaded... 0 incomplete screenshot(s) still exist

+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| ...
| 💥   | upload_to_app_store                                           | 22          |
+------+---------------------------------------------------------------+-------------+

[13:55:35]: fastlane finished with errors

[!] Failed verification of all screenshots uploaded... 0 incomplete screenshot(s) still exist</pre>
</details>

### Environment

Essentially we have `skip_screenshots` at its default value of `false` but no screenshots to upload by Fastlane when this error happens.

**Comment by ainame** [comment]
Hi, I'm the one who made the changes. Thank you for this feedback.
Looking at the current code, as you pointed, it's going to fail if you don't have screenshots locally. It's checking whether the number of screenshots to be uploaded matches the number of screenshots correctly uploaded on App Store Connect. Meaning, that comparison will never succeed in your environment.

As you already figured out, setting `false` to `skip_screenshots` is a workaround for now. I'll have a think about how I can keep the previous behaviour.

**Comment by kuhnroyal** [comment]
This is also failing for me when I have no existing screenshots in AppStoreConnect but try to add new ones, something was nil, sadly lost the stacktrace.
Reverting back to 2.155.3 works temporarily.

**Comment by ainame** [comment]
I got a fix. I'm going to submit a PR for this.

**Comment by ainame** [comment]
🙇 https://github.com/fastlane/fastlane/pull/17051

**Comment by pyrtsa** [comment]
Thank you! Will test it soon.

**Comment by kaydenthomson** [comment]
Hi! 

We are using Fastlane 2.156.1 and seeing a similar issue. 

skip_screenshots is set to false

Screenshots attempting to upload have not changed from current screenshots on App Store Connect.

> Failed to upload all screenshots... Tries remaining: 1

> Waiting for all the screenshots processed...
> [!] Failed verification of all screenshots uploaded... 5 incomplete screenshot(s) still exist
> If you have issues, use the latest prerelease version of fastlane.
> Set the fastlane version input to "latest" to enable prerelease versions.
> Deploy failed, error: exit status 1

**Comment by nirre7** [comment]
We are having the same issue here, no new screenshots when running upload_to_app_store. 
We haven't set the skip_screenshots flag. 
On 2.156.1.

**Comment by ainame** [comment]
@kaydenthomson 

I think your case is not the same as what this issue reported.

> [!] Failed verification of all screenshots uploaded... 5 incomplete screenshot(s) still exist

From this error message, I can tell you have 5 screenshots that are error state or so on App Store Connect and `deliver` couldn't finish without those errors within 5 retries. You could check if there were errors from the link "View All Sizes in Media Manager" on App Store Connect.  

(I suppose we should show what kind of errors we got instead of showing only numbers. But it would be another improvement.)

**Comment by kaydenthomson** [comment]
@ainame 
Thank you for pointing that out! After checking App Store Connect and attempting a manual reupload of the same images on App Store Connect, we noticed an error with the alpha on the image.

Re-exporting the images without an alpha channel solved that issue.

Yes, I think logging the kind of error would have helped us identify the problem more quickly. 

With the new/fixed images we tried Fastlane again with the following result:
`[!] Failed verification of all screenshots uploaded... 0 incomplete screenshot(s) still exist`

**Comment by ainame** [comment]
@kaydenthomson 

It's nice that you could solve that part! 

I can't help further without more information but I'm _assuming_ it may be the case where you manually uploaded some screenshots in the past but you never put it under fastlane's control. So that the new verification process could fail... It is out of sync. 

If that's the case, setting `true` to `overwrite_screenshot` might resolve your issue. But be careful you may lose your screenshots that are kept only on App Store Connect. It would be good to run `fastlane deliver download_screenshots` to save what are there before using `overwrite_screenshot` option.

**Comment by ainame** [comment]
I managed to make improvements that cover both showing error details and not relying on numbers to support various use cases. I'll be submitting a PR shortly.

https://github.com/ainame/fastlane/compare/master...log-error-detail

**Comment by pyrtsa** [comment]
The fix works now. Thank you!
