### ISSUE TITLE
App-specific password not working for testflight uploads in CircleCI

### ISSUE THREAD

**Issue by ir-fuel** [fastlane/fastlane#17062]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Since 2FA sessions expire too quickly and I only access Testflight for build uploads I tried using an application specific password, however it seems it's not taken into account. I used `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` in the environment variables.

I'm running 2.156.1

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
 [16:47:04]: --- Step: upload_to_testflight ---
[16:47:04]: ----------------------------------
[16:47:04]: Login to App Store Connect (*@*.com)
Two-factor Authentication (6 digits code) is enabled for account '*@*.com'
More information about Two-factor Authentication: https://support.apple.com/en-us/HT204915

If you're running this in a non-interactive session (e.g. server or CI)
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification

Please enter the 6 digit code you received at +32 •••• •• : </pre>
</details>

### Environment

Running inside CircleCI

**Comment by dasoga** [comment]
@ir-fuel I'm facing same issue. 
My solution (for now) is creating a `fastlane spaceauth -u myuser@platform.org` session, paste it (wrapped with `' '`) in travis-ci.com (`FASTLANE_SESSION`) env var.

I'm just using `upload_to_testflight` command
Documentation:
`Note: The application specific password will not work if your action usage does anything else than uploading the binary, e.g. updating any metadata like setting release notes or distributing to testers, etc.`

But also it seems to be necessary add `FASTLANE_SESSION` env var.

**Comment by ir-fuel** [comment]
The solution is here:

https://docs.fastlane.tools/actions/upload_to_testflight/#use-an-application-specific-password-to-upload

**Comment by dasoga** [comment]
I got it worked 
Whit this implementation
`upload_to_testflight(skip_waiting_for_build_processing: true, apple_id: "12345678")`

Not need to set `FASTLANE_SESSION` env var.
