### ISSUE TITLE
set_changelog failing to update and ends in error: handle_response': [!] undefined method `status' for nil:NilClass

### ISSUE THREAD

**Issue by jbachand** [fastlane/fastlane#17071]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Updating changelog is failing to post. User logging in has admin access to appstoreconnect.

##### Command executed
fastlane run set_changelog team_id:"xxxxx" app_identifier:"com.xxxxx.app" changelog:"We release new features every 2 weeks."                 

##### Complete output when running fastlane, including the stack trace and command used
me@computer % fastlane run set_changelog team_id:"xxxxx" app_identifier:"com.xxxxx.app" changelog:"We release new features every 2 weeks."                 
[✔] 🚀 
[01:36:50]: ---------------------------
[01:36:50]: --- Step: set_changelog ---
[01:36:50]: ---------------------------
[01:36:50]: Login to App Store Connect (jeff@x.com)
[01:36:53]: Login successful
[01:36:57]: Fetching the latest version for this app
[01:36:58]: Going to update version 4.4.0
[01:36:58]: Going to update the changelog to:

We release new features every 2 weeks.

[01:37:01]: Updating changelog for existing version 4.4.0
[01:37:01]: Updating changelog for the 'en-US'

Looking for related GitHub issues on fastlane/fastlane...

➡️  NoMethodError: [!] undefined method `status' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/17066 [open] 0 💬
    14 hours ago

➡️  [!] undefined method `any?' for nil:NilClass (NoMethodError)
    https://github.com/fastlane/fastlane/issues/17048 [open] 10 💬
    5 days ago

➡️  [Swift] undefined method `each' for nil:NilClass - Cannot Create Group Within FastlaneSwiftRunner Project
    https://github.com/fastlane/fastlane/issues/15184 [open] 39 💬
    a day ago

and 269 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60status%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	27: from /Users/me/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
	26: from /Users/me/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
	25: from /Users/me/.rvm/gems/ruby-2.5.1/bin/fastlane:23:in `<main>'
	24: from /Users/me/.rvm/gems/ruby-2.5.1/bin/fastlane:23:in `load'
	23: from /Users/me/www/react-native/ios/vendor/bundle/ruby/2.5.0/gems/fastlane-2.156.1/bin/fastlane:23:in `<top (required)>'
	22: from /Users/me/www/react-native/ios/vendor/bundle/ruby/2.5.0/gems/fastlane-2.156.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	21: from /Users/me/www/react-native/ios/vendor/bundle/ruby/2.5.0/gems/fastlane-2.156.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	20: from /Users/me/www/react-native/ios/vendor/bundle/ruby/2.5.0/gems/fastlane-2.156.1/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	19: from /Users/me/www/react-native/ios/vendor/bundle/ruby/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	18: from /Users/me/www/react-native/ios/vendor/bundle/ruby/2.5.0/gems/fastlane-2.156.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	17: from /Users/me/www/react-native/ios/vendor/bundle/ruby/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	16: from /Users/me/www/react-native/ios/vendor/bundle/ruby/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	15: from /Users/me/www/react-native/ios/vendor/bundle/ruby/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	14: from /Users/me/www/react-native/ios/vendor/bundle/ruby/2.5.0/gems/fastlane-2.156.1/fastlane/lib/fastlane/commands_generator.rb:224:in `block (2 levels) in run'
	13: from /Users/me/www/react-native/ios/vendor/bundle/ruby/2.5.0/gems/fastlane-2.156.1/fastlane/lib/fastlane/one_off.rb:22:in `execute'
	12: from /Users/me/www/react-native/ios/vendor/bundle/ruby/2.5.0/gems/fastlane-2.156.1/fastlane/lib/fastlane/one_off.rb:42:in `run'
	11: from /Users/me/www/react-native/ios/vendor/bundle/ruby/2.5.0/gems/fastlane-2.156.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	10: from /Users/me/www/react-native/ios/vendor/bundle/ruby/2.5.0/gems/fastlane-2.156.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	 9: from /Users/me/www/react-native/ios/vendor/bundle/ruby/2.5.0/gems/fastlane-2.156.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	 8: from /Users/me/www/react-native/ios/vendor/bundle/ruby/2.5.0/gems/fastlane-2.156.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 7: from /Users/me/www/react-native/ios/vendor/bundle/ruby/2.5.0/gems/fastlane-2.156.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 6: from /Users/me/www/react-native/ios/vendor/bundle/ruby/2.5.0/gems/fastlane-2.156.1/fastlane/lib/fastlane/actions/set_changelog.rb:65:in `run'
	 5: from /Users/me/www/react-native/ios/vendor/bundle/ruby/2.5.0/gems/fastlane-2.156.1/fastlane/lib/fastlane/actions/set_changelog.rb:65:in `each'
	 4: from /Users/me/www/react-native/ios/vendor/bundle/ruby/2.5.0/gems/fastlane-2.156.1/fastlane/lib/fastlane/actions/set_changelog.rb:67:in `block in run'
	 3: from /Users/me/www/react-native/ios/vendor/bundle/ruby/2.5.0/gems/fastlane-2.156.1/spaceship/lib/spaceship/connect_api/models/app_store_version_localization.rb:49:in `update'
	 2: from /Users/me/www/react-native/ios/vendor/bundle/ruby/2.5.0/gems/fastlane-2.156.1/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:659:in `patch_app_store_version_localization'
	 1: from /Users/me/www/react-native/ios/vendor/bundle/ruby/2.5.0/gems/fastlane-2.156.1/spaceship/lib/spaceship/connect_api/client.rb:110:in `patch'
/Users/me/www/react-native/ios/vendor/bundle/ruby/2.5.0/gems/fastlane-2.156.1/spaceship/lib/spaceship/connect_api/client.rb:151:in `handle_response': [!] undefined method `status' for nil:NilClass (NoMethodError)

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.1                                     |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.21.1 (Apple Git-122.3)        |
| Installation Source         | ~/.rvm/gems/ruby-2.5.1/bin/fastlane         |
| Host                        | Mac OS X 10.15.1 (19B88)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.5.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.1a  20 Nov 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.3.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "x.xcodeproj")
    build_app(workspace: "x.xcworkspace", scheme: "x")
    upload_to_testflight
  end
  lane :release_status do
    whitelabel
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.x.app") # The bundle identifier of your app
apple_id("jeff@x.com") # Your Apple email address

itc_team_id("xxx") # App Store Connect Team ID
team_id("xxx") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.156.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 2.1.4        |
| rake                      | 13.0.1       |
| CFPropertyList            | 3.0.2        |
| concurrent-ruby           | 1.1.6        |
| i18n                      | 0.9.5        |
| minitest                  | 5.14.1       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.7        |
| activesupport             | 4.2.11.3     |
| public_suffix             | 4.0.5        |
| addressable               | 2.7.0        |
| httpclient                | 2.8.3        |
| json                      | 2.3.1        |
| algoliasearch             | 1.27.3       |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.357.0      |
| aws-sigv4                 | 1.2.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.104.3      |
| aws-sdk-kms               | 1.36.0       |
| aws-sdk-s3                | 1.78.0       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| netrc                     | 0.11.0       |
| ffi                       | 1.13.1       |
| ethon                     | 0.12.0       |
| typhoeus                  | 1.4.0        |
| cocoapods-core            | 1.9.3        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.3.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| cocoapods-trunk           | 1.5.0        |
| cocoapods-try             | 1.2.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.17.0       |
| cocoapods                 | 1.9.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.0.0        |
| excon                     | 0.76.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 1.0.1        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| jwt                       | 2.2.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| signet                    | 0.14.0       |
| googleauth                | 0.13.1       |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.27.0       |
| mini_magick               | 4.10.1       |
| plist                     | 3.5.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2020-08-19**
</details>

**Comment by TewWe** [comment]
@jbachand I'm quite sure, this is the same issue as I've tried to investigate a little bit: https://github.com/fastlane/fastlane/issues/17066#issuecomment-686462098

**Comment by katiany** [comment]
I'm facing the same issue here, even being an Admin user in the AppStore account and after updating to fastlane 2.161

I noticed that after manually deleting existing screenshots in AppStore before running it, fastlane could handle the upload without errors. However, new screenshots weren't uploaded.

Anyone have any clues on this?

**Comment by katiany** [comment]
I'm facing the same issue here, even being an Admin user in the AppStore account and after updating to fastlane 2.161

I noticed that after manually deleting existing screenshots in AppStore before running it, fastlane could handle the upload without errors. However, new screenshots weren't uploaded.

Anyone have any clue on this?

**Comment by rogerluan** [comment]
Hey everyone! 

As of release [v2.163.0](https://github.com/fastlane/fastlane/releases/tag/2.163.0), we released some fixes related to how the API key is handled, and this should provide better errors when they occur when using _spaceship_ (so instead of seeing only `handle_response': [!] undefined method `status' for nil:NilClass` you should see a more user-friendly error from Apple's API), and it should also fix some corner cases where the API key file was being handled wrong.

@katiany there was a screenshot-related fix last week, a day after you posted your comment. Mind updating _fastlane_ and checking again? If you still face issues, please create a separate issue so we can better track it, with your env info 🙏 

Thanks for your comprehension

**Comment by tbodt** [comment]
Just ran into this issue, posting to make sure it doesn't get auto closed

**Comment by tbodt** [comment]
Why is there even an auto issue closing bot

**Comment by tbodt** [comment]
bump

**Comment by tbodt** [comment]
http://web.archive.org/web/https://blog.benwinding.com/github-stale-bots/

**Comment by tbodt** [comment]
https://blog.benwinding.com/github-stale-bots/
