### ISSUE TITLE
Problem to change the 'dsym_path' on upload_symbols_to_crashlytics

### ISSUE THREAD

**Issue by mendesbarreto** [fastlane/fastlane#17070]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Some times I want to upload more than one dsym at once, but the ```upload_symbols_to_crashlytics``` is working only with my dsyms is on root folder

This code is working fine, but the dsym is on root folder:

```
      upload_symbols_to_crashlytics(gsp_path: ENV['CRASHLYTICS_GSP_PATH'])
```

This is what I want to do

```
      upload_symbols_to_crashlytics(dsym_path: "./dsym/*",
                                    gsp_path: ENV['CRASHLYTICS_GSP_PATH'])
```

##### Command executed

```shell
bundle exec fastlane refresh_dsyms --env prod

  lane :refresh_dsyms do
    begin
      download_dsyms(output_directory: ENV['DSYM_PATH_FOLDER'])
      upload_symbols_to_crashlytics(dsym_path: ENV['DSYM_PATH_FOLDER'] + "*", # == ./dsym/*
                                    gsp_path: ENV['CRASHLYTICS_GSP_PATH'],
                                    dsym_worker_threads: 5)
      clean_build_artifacts
    rescue => exception
      send_fail_message_to_slack("Refresh Dsym", "Imposable to refresh dsym files to crashlytics: #{exception}")
      raise exception
    end
  end


```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
[19:28:54]: Loading from './fastlane/.env.prod'
+---------------------------+---------+-------------------------------------------------------------------+
|                                              Used plugins                                               |
+---------------------------+---------+-------------------------------------------------------------------+
| Plugin                    | Version | Action                                                            |
+---------------------------+---------+-------------------------------------------------------------------+
| fastlane-plugin-changelog | 0.15.0  | read_changelog update_changelog emojify_changelog stamp_changelog |
+---------------------------+---------+-------------------------------------------------------------------+

[19:28:55]: ------------------------------
[19:28:55]: --- Step: default_platform ---
[19:28:55]: ------------------------------
[19:28:55]: Driving the lane 'ios refresh_dsyms' 🚀
[19:28:56]: Error setting value './dsym/*' for option 'dsym_path'
[19:28:56]: You passed invalid parameters to 'upload_symbols_to_crashlytics'.
[19:28:56]: Check out the error below and available options by running `fastlane action upload_symbols_to_crashlytics`
[19:28:56]: ------------------------------
[19:28:56]: --- Step: get_build_number ---
[19:28:56]: ------------------------------
[19:28:56]: ▸ 102
[19:28:56]: --------------------------------
[19:28:56]: --- Step: get_version_number ---
[19:28:56]: --------------------------------
+------------------+-------------------+
|             Lane Context             |
+------------------+-------------------+
| ENVIRONMENT      | prod              |
| DEFAULT_PLATFORM | ios               |
| PLATFORM_NAME    | ios               |
| LANE_NAME        | ios refresh_dsyms |
| BUILD_NUMBER     | 102               |
+------------------+-------------------+

+------+--------------------+-------------+
|            fastlane summary             |
+------+--------------------+-------------+
| Step | Action             | Time (in s) |
+------+--------------------+-------------+
| 1    | default_platform   | 0           |
| 2    | get_build_number   | 0           |
| 3    | get_version_number | 2           |
+------+--------------------+-------------+ 
 </pre>
</details>

### Environment

<details>
  <pre> 
| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.6                                     |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.28.0                          |
| Installation Source         | ~/.rbenv/versions/2.6.3/bin/fastlane        |
| Host                        | Mac OS X 10.15.6 (19G73)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.3/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.6                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |
</pre>
</details>

**Comment by Gaullts** [comment]
Unfortunately, there are a few cases that could cause your dSYM upload to fail, such as bitcode in your app or other unique project configurations. This guide provides some ways to troubleshoot when Crashlytics can't locate your app's dSYM.

**Comment by mendesbarreto** [comment]
> Unfortunately, there are a few cases that could cause your dSYM upload to fail, such as bitcode in your app or other unique project configurations. This guide provides some ways to troubleshoot when Crashlytics can't locate your app's dSYM.

Thank you for your replay @Gaullts =) .

But the problem is not on Crashlytics, because when I don't specify the directory and let the fastlane download the dsym on my root directory, he is capable of uploading all dsym with no problems...
