### ISSUE TITLE
Screengrab: No screenshots were detected

### ISSUE THREAD

**Issue by lolucosmin** [fastlane/fastlane#17084]
### New Issue Checklist

- [ x] Updated fastlane to the latest version
- [ x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Still I have that common issue with: "No screenshots were detected"
I updated the fastlane to last version.
I updated also the screengrab to last version: androidTestImplementation 'tools.fastlane:screengrab:2.0.0'
Android config:
    compileSdkVersion 30
    buildToolsVersion '30.0.2'
    targetSdkVersion 30

##### Command executed
I executed:
bundle exec fastlane screengrab

##### Complete output when running fastlane, including the stack trace and command used
[13:28:57]: ▸ Time: 12.116
[13:28:57]: [13:28:57]: ▸ OK (1 test)
[13:28:58]: ▸ [13:28:58]: Pulling captured screenshots for locale en-US from the device
[13:28:58]: ▸ ls: /sdcard/app.packagename/screengrab/en-US/images/screenshots: Permission denied
[13:28:58]: ▸ [13:28:58]: Exit status: 1
[13:28:58]: ▸ [13:28:58]: $ /home/lolu/Android/Sdk/platform-tools/adb -s emulator-5556 pull /data/user/0/app.packagename/files/app.packagename/screengrab/en-US/images/screenshots /tmp/d20200824-41472-1wvcm1p
[13:28:58]: ▸ adb: error: failed to stat remote object '/data/user/0/app.packagename/files/app.packagename/screengrab/en-US/images/screenshots': Permission denied
[13:28:58]: ▸ [13:28:58]: Exit status: 1
[13:28:58]: ▸ [13:28:58]: $ /home/lolu/Android/Sdk/platform-tools/adb -s emulator-5556 pull /data/data/app.packagename/files/app.packagename/screengrab/en-US/images/screenshots /tmp/d20200824-41472-1wvcm1p
[13:28:58]: ▸ adb: error: failed to stat remote object '/data/data/app.packagename/files/app.packagename/screengrab/en-US/images/screenshots': Permission denied
[13:28:58]: ▸ [13:28:58]: Exit status: 1
[13:28:58]: ▸ ls: /data/data/app.packagename/app_screengrab/en-US/images/screenshots: No such file or directory
[13:28:58]: ▸ [13:28:58]: Exit status: 1
[13:28:58]: ▸ ls: /data/data/app.packagename/screengrab/en-US/images/screenshots: No such file or directory
[13:28:58]: ▸ [13:28:58]: Exit status: 1
[13:28:58]: ▸ [13:28:58]: Make sure you've used Screengrab.screenshot() in your tests and that your expected tests are being run.
[13:28:58]: ▸ [13:28:58]: No screenshots were detected 📷❌
[13:28:58]: ▸ [13:28:58]: Failed to send metadata and screenshots in PROD for ORG 'app ... moving on

<details>
  <pre> In AS I see this message: "Using screenshot storage directory: /data/user/0/app.packagename/files/app.packagename/screengrab/en-US/images/screenshots". Looks like the path of directory is generated wrong.</pre>
</details>

### Stack

| Key                         | Value                                                           |
| --------------------------- | --------------------------------------------------------------- |
| OS                          | debian_based bullseye/sid                                       |
| Ruby                        | 2.7.0                                                           |
| Bundler?                    | true                                                            |
| Git                         | git version 2.25.1                                              |
| Installation Source         | /usr/local/bin/fastlane                                         |
| Host                        | Ubuntu 20.04.1 LTS debian_based bullseye/sid (5.4.0-42-generic) |
| Ruby Lib Dir                | /usr/lib                                                        |
| OpenSSL Version             | OpenSSL 1.1.1f  31 Mar 2020                                     |
| Is contained                | false                                                           |
| Is homebrew                 | false                                                           |
| Is installed via Fabric.app | false                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.156.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                      | Version | Update-Status |
| ------------------------------------------- | ------- | ------------- |
| fastlane-plugin-automated_test_emulator_run | 1.6.0   | ✅ Up-To-Date  |
| fastlane-plugin-firebase_app_distribution   | 0.1.4   | ✅ Up-To-Date  |

**Comment by lolucosmin** [comment]
So after I tested a lot of cases I have this situation:
1.With this configuration the screenshots are working:
    compileSdkVersion 29
    buildToolsVersion '29.0.3'
    targetSdkVersion 29
   
    fastlane: 2.154.0
    tools.fastlane:screengrab:1.2.0

So if I will update to last version all things are not working:
    compileSdkVersion 30
    buildToolsVersion '30.0.2'
    targetSdkVersion 30
   
    fastlane: 2.156.1
    tools.fastlane:screengrab:2.0.0

**Comment by koxon** [comment]
+1 using latest Android SDK 30 we also get screengrab error about writing path and permission

**Comment by lolucosmin** [comment]
Any news on this issue?

**Comment by wormoworm** [comment]
Also getting this issue, using Fastlane 2.157.2 and API 29 on Github Actions (macos agent).

**Comment by fatihyildizhan** [comment]
There is a similar problem with iOS Snapshot.

https://github.com/fastlane/fastlane/issues/17039

**Comment by lolucosmin** [comment]
> Also getting this issue, using Fastlane 2.157.2 and API 29 on Github Actions (macos agent).

Yes, but if you downgrade to fastlane: 2.154.0 and API 29 will works. Weird issue. I am waiting a new fastlane release, I hope they will fix this major issue.

**Comment by tmaly1980** [comment]
> > Also getting this issue, using Fastlane 2.157.2 and API 29 on Github Actions (macos agent).
> 
> Yes, but if you downgrade to fastlane: 2.154.0 and API 29 will works. Weird issue. I am waiting a new fastlane release, I hope they will fix this major issue.

Thanks for the suggestion, I'm attempting this now. I'm noticing the issue specifically only on CircleCI - locally I don't believe it's a problem.

**Comment by RobertSasak** [comment]
@lolucosmin @wormoworm As screengrab is very sensitive to different version of both fastlane, Android SDK would you mind to share your Github Action or Travis configuration. I realise that it would be much easier to create screenshot on build server in a stable environment. I think the whole community would benefit from it.

**Comment by StuSchwartz** [comment]
I am having the same issue with 2.160.0
Right now screenshots are dead.

**Comment by Shepard899** [comment]
Thanks for sharing this information keep sharing such informative post[ McDVoice Survey](https://www.mcdvoice.onl/)
