### ISSUE TITLE
How to change Build configuration(QA,Dev,Staging and Release) in a Scheme - via fastlane

### ISSUE THREAD

**Issue by kandavel** [fastlane/fastlane#17085]
@fastlaneTeam : Hi, i am facing an issue while giving gym command
my requirement is i have four different enviroment (QA,Dev,Staging and Release)
by manually i go to scheme -> edit sceme -> RUN -> Build configuartion -> set the environment
by manually i go to scheme -> edit sceme -> Archive -> Build configuartion -> set the environment

----

i want to achieve the same via Fastlane 
<img width="898" alt="Screenshot 2020-08-24 at 7 32 21 PM" src="https://user-images.githubusercontent.com/16301500/91053549-99273380-e640-11ea-9655-1da6b5916ccb.png">
<img width="895" alt="Screenshot 2020-08-24 at 7 32 13 PM" src="https://user-images.githubusercontent.com/16301500/91053569-9fb5ab00-e640-11ea-83a6-65782bc153b1.png">
<img width="898" alt="Screenshot 2020-08-24 at 7 32 02 PM" src="https://user-images.githubusercontent.com/16301500/91053578-a17f6e80-e640-11ea-97c8-deb599412edc.png">

 ,

**Comment by kandavel** [comment]
@joshdholtz:  can u suggest a solution  how can i change the scheme  both in Run and Archive - under the scheme

**Comment by hegedus90** [comment]
You select a build configuration during the build process using the `configuration` parameter. See the documentation of [build_app](http://docs.fastlane.tools/actions/build_app/#build_app) for more details.

**Comment by kandavel** [comment]
> You can select a build configuration by setting the `configuration` parameter. See the documentation of [build_app](http://docs.fastlane.tools/actions/gym/#build_app) for more details.



thanks for the solution 👍👍, previously i used the same parameter but it taking different configuaration , before executing gym command i have given clean build folder and derived data  and it is started working for me
