### ISSUE TITLE
Update `example_rating_config.json`

### ISSUE THREAD

**Issue by pedro380085** [fastlane/fastlane#17094]
With the new iTC update, the template [file](https://github.com/fastlane/fastlane/blob/master/deliver/assets/example_rating_config.json) has been deprecated.

```
Age rating 'CARTOON_FANTASY_VIOLENCE' from iTunesConnect has been deprecated. Please replace with 'violenceCartoonOrFantasy'
```

Thanks,

**Comment by gregorskii** [comment]
+1 this should be updated to provide a correct example and documentation of these ratings.

**Comment by joshdholtz** [comment]
Will get this updated! Thanks for letting me know 😊
