### ISSUE TITLE
[!] Please login using `Spaceship::Portal.login('user', 'password')`

### ISSUE THREAD

**Issue by bjzhlapple** [fastlane/fastlane#17108]
hello,I can not use "fastlane sigh -a xxx -u xxx -q "xxx" --force --adhoc", terminal puts  [!] Please login using `Spaceship::Portal.login('user', 'password')`.I tried a lot of method ,but does not worked. please look picture . thanks
![image](https://user-images.githubusercontent.com/37367777/91560168-f2a69f80-e96b-11ea-9dc0-5c7011903be2.png)

_Originally posted by @bjzhlapple in https://github.com/fastlane/fastlane/issues/16429#issuecomment-682495176_

**Comment by bjzhlapple** [comment]
I tried this but does not worked.
![image](https://user-images.githubusercontent.com/37367777/91560408-68127000-e96c-11ea-99f6-45d202cc2f93.png)

**Comment by fllink** [comment]
We encountered the same issue – downgrading to fastlane 2.156.1 resolved the issue on our side. I suspect the issue was introduced with #17042 as it was also not working in 2.157.0

**Comment by joshdholtz** [comment]
@bjzhlapple @fllink Hello! Have your tried updating to `2.157.1`? I pushed this out last night that should have this fixed 🤞

**Comment by joshdholtz** [comment]
@bjzhlapple Sorry, I just saw your screenshot stacktrace! I will look into right away for you 👍

**Comment by joshdholtz** [comment]
Found the issue! Fix coming out soon. Sorry about that!

**Comment by bjzhlapple** [comment]
> Found the issue! Fix coming out soon. Sorry about that!

非常感谢！Tanks very much,I am watting for new version.  hahahah

**Comment by bjzhlapple** [comment]
> We encountered the same issue – downgrading to fastlane 2.156.1 resolved the issue on our side. I suspect the issue was introduced with #17042 as it was also not working in 2.157.0

thanks a lot .

**Comment by joshdholtz** [comment]
@bjzhlapple This should be fixed for you in `2.157.2` now!

**Comment by fllink** [comment]
Thank you for the quick response, we encountered it in 2.157.1, sorry for being inaccurate.

**Comment by joshdholtz** [comment]
@fllink That was actually my bad! I woke up and refreshed issues right away and didn't give my brain some time to actually read things 😛 Were you able to test to see if `2.157.2` fixed everything for you? 😇

**Comment by bjzhlapple** [comment]
> @bjzhlapple This should be fixed for you in `2.157.2` now!

Thank you 😁
