### ISSUE TITLE
Pilot doesn’t accept iTunes connect team_id

### ISSUE THREAD

**Issue by srvv** [fastlane/fastlane#17103]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: 2.157.0
- Last working version: 2.156.1

### Regression Description

Passing iTunes connect team_id to pilot is no longer accepted it as prompts to select team with Dev portal team Ids. Since prompts are disabled on CI it results in a failure of _pilot_.

Though this would be a breaking change but providing Dev portal team Id doesn't work either as then it prompts to select team from iTunes connect id list.

On looking through the change log, I have found a change from iTunes client to AppStore connect client is causing this issue. 

From what I could glean from changelog, on [this change here](https://github.com/fastlane/fastlane/pull/17061#discussion_r478695859) the script failure occurs. 

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by treymcmeans** [comment]
Experiencing the same issue. Watching for resolution

**Comment by joshdholtz** [comment]
Working on fix now! Will have new version out before I go to bed for the night 😊

**Comment by joshdholtz** [comment]
@srvv @treymcmeans I _think_ I have a fix for you with #17104 🤞 Would either of you be able to switch to this branch to verify that it works for you?

### Testing Steps

Update `Gemfile` to 👇 and run `bundle install`, `bundle update fastlane`, or `bundle update`

```rb
gem "fastlane", :git => "https://github.com/fastlane/fastlane.git", :branch => "joshdholtz-spaceship-connect-api-separate-portal-tunes-team-id"
```

**Comment by srvv** [comment]
Thanks @joshdholtz for quickly fixing this issue. I can confirm that pilot is working fine with team_id on v2.157.1. 

Though there is a warning 'The current user is in 5 teams. Pass a team ID or call 'select_team' to choose a team. Using the first one for now.' But it picks the correct team based on the given team ID.

**Comment by joshdholtz** [comment]
@srvv Thanks for following up! I'll see if I can get rid of that warning of you 😊

**Comment by jffmrk** [comment]
Awesome, thanks for the fix - I was having trouble with this same thing the last few days. v2.157.2 is working for me. I can live with the warning message 👍
