### ISSUE TITLE
TestFlight internal_users fails 

### ISSUE THREAD

**Issue by tmaly1980** [fastlane/fastlane#17113]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When trying to assign existing internal test users to a newly published app (to submit to testflight), I just get a 404 page when retrieving the internal_users

##### Command executed
```
    client = Spaceship::Tunes.login
    client.team_id = "ITC_TEAM_ID"
    app = Spaceship::Tunes::Application.find("com.company.app")
    client = Spaceship::TestFlight::Base.client
    client.internal_users(app_id: app.apple_id)


```
##### Complete output when running fastlane, including the stack trace and command used

```
<!DOCTYPE html><html lang="en">
<head>
<title></title>
<link rel="stylesheet" href="/styles/main.css">
<style type='text/css'>
    /*include ../../dist/styles/main.css*/
</style>
</head>

<body><div id="wrapper" class="j42">
<h2>Not Found</h2></div>

<div class="footer">
    <p>Copyright &copy; <span id='year'>2015</span> Apple Inc. All rights reserved.</p>
    <ul><li><a href="https://www.apple.com/legal/internet-services/itunes/">Terms of Service</a></li><li><a href="https://www.apple.com/legal/privacy">Privacy Policy</a></li></ul>
</div>


<script type='text/javascript'>(function() {
    var isIos = navigator.userAgent.match(/(iPod|iPhone|iPad)/);
    document.body.setAttribute( 'class', (!isIos) ? 'otherBrowser' : 'isMobileSafari' )
    var yearEl = document.getElementById('year');
    if (yearEl) { yearEl.textContent = new Date().getFullYear(); }
})();
</script>

</body>
</html>
```

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                        |
| --------------------------- | -------------------------------------------- |
| OS                          | 10.15.4                                      |
| Ruby                        | 2.4.6                                        |
| Bundler?                    | false                                        |
| Git                         | git version 2.24.3 (Apple Git-128)           |
| Installation Source         | /usr/local/lib/ruby//gems/2.4.0/bin/fastlane |
| Host                        | Mac OS X 10.15.4 (19E287)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.4/2.4.6_1/lib       |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                  |
| Is contained                | false                                        |
| Is homebrew                 | false                                        |
| Is installed via Fabric.app | false                                        |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/  |
| Xcode Version               | 11.5                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.157.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                 | Version | Update-Status |
| -------------------------------------- | ------- | ------------- |
| fastlane-plugin-increment_version_code | 0.4.3   | ✅ Up-To-Date  |
| fastlane-plugin-appicon                | 0.15.0  | ✅ Up-To-Date  |
| fastlane-plugin-load_json              | 0.0.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                    | Version      |
| -------------------------------------- | ------------ |
| did_you_mean                           | 1.1.0        |
| slack-notifier                         | 2.3.2        |
| rouge                                  | 2.0.7        |
| xcpretty                               | 0.3.0        |
| terminal-notifier                      | 2.0.0        |
| terminal-table                         | 1.8.0        |
| multipart-post                         | 2.0.0        |
| word_wrap                              | 1.0.0        |
| babosa                                 | 1.0.3        |
| colored                                | 1.2          |
| commander-fastlane                     | 4.4.6        |
| http-cookie                            | 1.0.3        |
| faraday-cookie_jar                     | 0.0.6        |
| faraday                                | 1.0.1        |
| faraday_middleware                     | 1.0.0        |
| gh_inspector                           | 1.1.3        |
| rubyzip                                | 2.3.0        |
| security                               | 0.1.3        |
| bundler                                | 1.16.2       |
| declarative-option                     | 0.1.0        |
| representable                          | 3.0.4        |
| httpclient                             | 2.8.3        |
| google-api-client                      | 0.38.0       |
| nanaimo                                | 0.3.0        |
| colored2                               | 3.1.2        |
| claide                                 | 1.0.3        |
| CFPropertyList                         | 3.0.2        |
| atomos                                 | 0.1.3        |
| xcodeproj                              | 1.18.0       |
| unicode-display_width                  | 1.7.0        |
| plist                                  | 3.5.0        |
| public_suffix                          | 4.0.5        |
| addressable                            | 2.7.0        |
| tty-screen                             | 0.8.1        |
| tty-cursor                             | 0.7.1        |
| tty-spinner                            | 0.9.3        |
| highline                               | 1.7.10       |
| excon                                  | 0.76.0       |
| unf_ext                                | 0.0.7.7      |
| unf                                    | 0.1.4        |
| domain_name                            | 0.5.20190701 |
| fastimage                              | 2.2.0        |
| json                                   | 2.3.1        |
| mini_magick                            | 4.10.1       |
| xcpretty-travis-formatter              | 1.0.0        |
| dotenv                                 | 2.7.6        |
| naturally                              | 2.2.0        |
| simctl                                 | 1.6.8        |
| jwt                                    | 2.2.2        |
| uber                                   | 0.1.0        |
| declarative                            | 0.0.20       |
| retriable                              | 3.1.2        |
| mini_mime                              | 1.0.2        |
| multi_json                             | 1.15.0       |
| signet                                 | 0.14.0       |
| os                                     | 1.1.1        |
| memoist                                | 0.16.2       |
| googleauth                             | 0.13.1       |
| rake                                   | 13.0.1       |
| digest-crc                             | 0.6.1        |
| google-cloud-errors                    | 1.0.1        |
| google-cloud-env                       | 1.3.3        |
| google-cloud-core                      | 1.5.0        |
| google-cloud-storage                   | 1.28.0       |
| emoji_regex                            | 3.0.0        |
| aws-eventstream                        | 1.1.0        |
| aws-sigv4                              | 1.2.2        |
| aws-partitions                         | 1.362.0      |
| jmespath                               | 1.4.0        |
| aws-sdk-core                           | 3.105.0      |
| aws-sdk-kms                            | 1.37.0       |
| aws-sdk-s3                             | 1.79.1       |
| openssl                                | 2.0.9        |
| io-console                             | 0.4.6        |
| mini_portile2                          | 2.3.0        |
| nokogiri                               | 1.8.1        |
| psych                                  | 2.2.2        |
| oj                                     | 3.1.4        |
| bigdecimal                             | 1.3.2        |
| fastlane-plugin-increment_version_code | 0.4.3        |
| fastlane-plugin-appicon                | 0.15.0       |
| fastlane-plugin-load_json              | 0.0.1        |
</details>

*generated on:* **2020-08-30**
</details></pre>
</details>

**Comment by saitjr** [comment]
same issue

**Comment by billibala** [comment]
I think I ran into the same issue. In my case, I ran `fastlane pilot add` command.

```
[22:27:19]: --------------------------------------------------------------------
[22:27:19]: Step: fastlane pilot add native@sched.com -a <bundle ID> -r <team_name> -g ITC.apps.tf.labels.internalTesters
[22:27:19]: --------------------------------------------------------------------
[22:27:19]: $ fastlane pilot add native@sched.com -a <bundle ID> -r <team_name> -g ITC.apps.tf.labels.internalTesters
[22:27:23]: ▸ [22:27:23]: Login to App Store Connect (native@sched.com)
[22:27:24]: ▸ [22:27:24]: Login successful
[22:27:25]: ▸ [22:27:25]: Could not find an app by com.sched.bud20
[22:27:25]: ▸ 
[22:27:25]: ▸ [!] Some operations failed: Could not find an app by <bundle ID>
```

**Comment by max-ott** [comment]
A lot of stuff is still affected from the recent App Store Connect API changes. I'm not sure if @joshdholtz already advanced to the depths of TestFlight. In general I would advice to remove any ``Spaceship::Tunes`` calls and replace them properly with the new ``ConnectAPI``ones.

**Comment by billibala** [comment]
I find that session cookie seems to expire a lot faster now. In my case, I was able to get the same command working by supplying a new session cookie using `fastlane spaceauth`
