### ISSUE TITLE
spaceship undefined method `build_params'

### ISSUE THREAD

**Issue by gtsifrikas** [fastlane/fastlane#17132]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: [2.157.2]
- Last working version: [2.156.1]

### Regression Description
Problem with the `spaceship` and the `connect_api`.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
/Users/hudson/.rvm/gems/ruby-2.5.0@executor-0/gems/fastlane-2.157.1/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:294:in `get_builds': [!] undefined method `build_params' for nil:NilClass (NoMethodError)
16:10:07  	from /Users/hudson/.rvm/gems/ruby-2.5.0@executor-0/gems/fastlane-2.157.1/fastlane/lib/fastlane/actions/app_store_build_number.rb:67:in `get_build_number'
16:10:07  	from /Users/hudson/.rvm/gems/ruby-2.5.0@executor-0/gems/fastlane-2.157.1/fastlane/lib/fastlane/actions/app_store_build_number.rb:14:in `run'
16:10:07  	from /Users/hudson/.rvm/gems/ruby-2.5.0@executor-0/gems/fastlane-2.157.1/fastlane/lib/fastlane/actions/latest_testflight_build_number.rb:12:in `run'
16:10:07  	from /Users/hudson/.rvm/gems/ruby-2.5.0@executor-0/gems/fastlane-2.157.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
16:10:07  	from /Users/hudson/.rvm/gems/ruby-2.5.0@executor-0/gems/fastlane-2.157.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
16:10:07  	from /Users/hudson/.rvm/gems/ruby-2.5.0@executor-0/gems/fastlane-2.157.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
16:10:07  	from /Users/hudson/.rvm/gems/ruby-2.5.0@executor-0/gems/fastlane-2.157.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
16:10:07  	from /Users/hudson/.rvm/gems/ruby-2.5.0@executor-0/gems/fastlane-2.157.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
16:10:07  	from /Users/hudson/.rvm/gems/ruby-2.5.0@executor-0/gems/fastlane-2.157.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
16:10:07  	from /Users/hudson/.rvm/gems/ruby-2.5.0@executor-0/gems/fastlane-2.157.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
16:10:07  	from Fastfile:165:in `block (2 levels) in parsing_binding'
16:10:07  	from /Users/hudson/.rvm/gems/ruby-2.5.0@executor-0/gems/fastlane-2.157.1/fastlane/lib/fastlane/lane.rb:33:in `call'
16:10:07  	from /Users/hudson/.rvm/gems/ruby-2.5.0@executor-0/gems/fastlane-2.157.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
16:10:07  	from /Users/hudson/.rvm/gems/ruby-2.5.0@executor-0/gems/fastlane-2.157.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
16:10:07  	from /Users/hudson/.rvm/gems/ruby-2.5.0@executor-0/gems/fastlane-2.157.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
16:10:07  	from /Users/hudson/.rvm/gems/ruby-2.5.0@executor-0/gems/fastlane-2.157.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
16:10:07  	from /Users/hudson/.rvm/gems/ruby-2.5.0@executor-0/gems/fastlane-2.157.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
16:10:07  	from /Users/hudson/.rvm/gems/ruby-2.5.0@executor-0/gems/fastlane-2.157.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
16:10:07  	from /Users/hudson/.rvm/gems/ruby-2.5.0@executor-0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
16:10:07  	from /Users/hudson/.rvm/gems/ruby-2.5.0@executor-0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
16:10:07  	from /Users/hudson/.rvm/gems/ruby-2.5.0@executor-0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
16:10:07  	from /Users/hudson/.rvm/gems/ruby-2.5.0@executor-0/gems/fastlane-2.157.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
16:10:07  	from /Users/hudson/.rvm/gems/ruby-2.5.0@executor-0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
16:10:07  	from /Users/hudson/.rvm/gems/ruby-2.5.0@executor-0/gems/fastlane-2.157.1/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
16:10:07  	from /Users/hudson/.rvm/gems/ruby-2.5.0@executor-0/gems/fastlane-2.157.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
16:10:07  	from /Users/hudson/.rvm/gems/ruby-2.5.0@executor-0/gems/fastlane-2.157.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
16:10:07  	from /Users/hudson/.rvm/gems/ruby-2.5.0@executor-0/gems/fastlane-2.157.1/bin/fastlane:23:in `<top (required)>'
16:10:07  	from /Users/hudson/.rvm/gems/ruby-2.5.0@executor-0/bin/fastlane:23:in `load'
16:10:07  	from /Users/hudson/.rvm/gems/ruby-2.5.0@executor-0/bin/fastlane:23:in `<main>'
16:10:07  	from /Users/hudson/.rvm/gems/ruby-2.5.0@executor-0/bin/ruby_executable_hooks:24:in `eval'
16:10:07  	from /Users/hudson/.rvm/gems/ruby-2.5.0@executor-0/bin/ruby_executable_hooks:24:in `<main>'
</pre>
</details>

### Environment

From CI. Difficult to run an explicit command.

**Comment by gfpacheco** [comment]
Same here, output of my `fastlane env`:

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.5                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.5 (19F101)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.7                                                           |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  lane :fetch_certificates do
    match(type: "appstore")
    get_push_certificate
  end

  lane :inc_build_number do
    increment_build_number(xcodeproj: "ios/Vuse.xcodeproj", build_number: latest_testflight_build_number + 1)
  end

  lane :increment_version_number_if_needed do
    require "spaceship"
    require "versionomy"
    Spaceship::Tunes.login
    Spaceship::Tunes.select_team
    app = Spaceship::Tunes::Application.find(CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier))
    live_version = Versionomy.parse(app.live_version.version.sub("v.", ""))
    local_version = Versionomy.parse(get_version_number(xcodeproj: "ios/Vuse.xcodeproj"))

    if local_version <= live_version then
      increment_version_number(version_number: live_version.bump(:tiny).to_s)
    end
  end

  lane :build do
    build_app(workspace: "ios/Vuse.xcworkspace", scheme: "Vuse")
  end

  lane :reset_version_numbers do
    sh( "git", "checkout", "../ios/Vuse/Info.plist", "../ios/Vuse.xcodeproj/project.pbxproj")
  end

  lane :tag_version do |options|
    tag = "v" + options[:version]
    add_git_tag(tag: tag, force: true)
    push_git_tags(tag: tag, force: true)
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    fetch_certificates
    inc_build_number
    build
    reset_version_numbers
    upload_to_testflight
  end

  desc "Push a new build to Production"
  lane :production do
    fetch_certificates
    inc_build_number
    increment_version_number_if_needed
    build
    version = get_version_number(xcodeproj: "ios/Vuse.xcodeproj")
    reset_version_numbers
    upload_to_app_store(force: true, submit_for_review: true)
    tag_version(version: version)
  end

end

platform :android do

  lane :build do
    gradle(project_dir: "android/", task: "clean")
    gradle(project_dir: "android/", task: "bundle", build_type: "Release")
  end

  lane :commit_version_code_bump do
    git_commit(path: ['android/gradle.properties'], message: 'Bump Android versionCode')
    push_to_git_remote
  end

  lane :beta do
    build
    upload_to_play_store(track: "internal")
    commit_version_code_bump
  end

  lane :production do
    build
    upload_to_play_store(track: "production")
    commit_version_code_bump
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("studio.ae.vuseapp") # The bundle identifier of your app

itc_team_id("118579928") # App Store Connect Team ID
team_id("PGUD5RWNFH") # Developer Portal Team ID

# For Android
# package_name("studio.ae.vuseapp") # The package name of your app
# json_key_file("serviceAccountKey.json") # Play Store service account key

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.157.2 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 1.0.1        |
| faraday_middleware        | 1.0.0        |
| gh_inspector              | 1.1.3        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 2.0.2        |
| uber                      | 0.1.0        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| nanaimo                   | 0.3.0        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.18.0       |
| unicode-display_width     | 1.7.0        |
| public_suffix             | 4.0.6        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| excon                     | 0.76.0       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| fastimage                 | 2.2.0        |
| json                      | 2.3.1        |
| mini_magick               | 4.10.1       |
| dotenv                    | 2.7.6        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| declarative               | 0.0.20       |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| os                        | 1.1.1        |
| memoist                   | 0.16.2       |
| googleauth                | 0.13.1       |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-env          | 1.3.3        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.28.0       |
| emoji_regex               | 3.0.0        |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-partitions            | 1.363.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.105.0      |
| aws-sdk-kms               | 1.37.0       |
| aws-sdk-s3                | 1.79.1       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>


*generated on:* **2020-09-02**
</details>
