### ISSUE TITLE
Getting Server error got 500 while downloading and uploading of screenshots

### ISSUE THREAD

**Issue by kashif789us** [fastlane/fastlane#17139]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When I download or upload screenshots, I am getting error :

> Server error got 500.

 There is no error while uploading and downloading of metadata.

##### Command executed

`fastlane deliver init`

and

`fastlane kt_upload_screenshots`

where

kt_upload_screenshots is:

```
lane :kt_upload_screenshots do
  deliver(
     skip_metadata: true,
     skip_binary_upload: true,
     overwrite_screenshots: true
  )
  end

```

##### Complete output when running fastlane, including the stack trace and command used

<details>
<pre>

[✔] 🚀 
[09:58:58]: -----------------------------
[09:58:58]: --- Step: update_fastlane ---
[09:58:58]: -----------------------------
[09:58:58]: Looking for updates for fastlane...
[09:59:01]: Nothing to update ✅
[09:59:01]: ------------------------------
[09:59:01]: --- Step: default_platform ---
[09:59:01]: ------------------------------
[09:59:01]: Driving the lane 'ios kt_upload_screenshots' 🚀
[09:59:01]: ---------------------
[09:59:01]: --- Step: deliver ---
[09:59:01]: ---------------------
[09:59:01]: Successfully loaded ‘/…/fastlane/Deliverfile' 📄
[09:59:01]: No values defined in './fastlane/Deliverfile'
[09:59:01]: Login to App Store Connect (xxxxxxxxxxxxxx)
The current user is in x teams. Pass a team ID or call `select_team` to choose a team. Using the first one for now.
[09:59:06]: Login successful

+--------------------------------------+----------------------------+
|                      deliver 2.157.2 Summary                      |
+--------------------------------------+----------------------------+
| skip_metadata                        | true                       |
| skip_binary_upload                   | true                       |
| overwrite_screenshots                | true                       |
| team_id                              | xxxxx                  |
| username                             | xxxxxxx  |
| app_identifier                       | xxxxxxx |
| screenshots_path                     | ./fastlane/screenshots     |
| metadata_path                        | ./fastlane/metadata        |
| platform                             | ios                        |
| edit_live                            | false                      |
| use_live_version                     | false                      |
| skip_screenshots                     | false                      |
| skip_app_version_update              | false                      |
| force                                | false                      |
| submit_for_review                    | false                      |
| reject_if_possible                   | false                      |
| automatic_release                    | false                      |
| phased_release                       | false                      |
| reset_ratings                        | false                      |
| run_precheck_before_submit           | true                       |
| precheck_default_rule_level          | warn                       |
| ignore_language_directory_validatio  | false                      |
| n                                    |                            |
| precheck_include_in_app_purchases    | true                       |
+--------------------------------------+----------------------------+

[09:59:15]: Verifying the upload via the HTML file can be disabled by either adding
[09:59:15]: `force true` to your Deliverfile or using `fastlane deliver --force`
[09:59:15]: Does the Preview on path './fastlane/Preview.html' look okay for
you? (y/n)
y
[09:59:24]: HTML file confirmed...
[09:59:26]: Will begin uploading snapshots for '1.1.3' on App Store Connect
[09:59:26]: Starting with the upload of screenshots...
#<Thread:0x00007fddaa68f710@/Library/Ruby/Gems/2.6.0/gems/fastlane-2.157.2/deliver/lib/deliver/app_screenshot_iterator.rb:24 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.157.2/deliver/lib/deliver/app_screenshot_iterator.rb:25:in `block (3 levels) in each_app_screenshot_set'
	5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.157.2/spaceship/lib/spaceship/connect_api/models/app_store_version_localization.rb:78:in `get_app_screenshot_sets'
	4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.157.2/spaceship/lib/spaceship/connect_api/models/app_screenshot_set.rb:116:in `all'
	3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `get_app_screenshot_sets'
	2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.157.2/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:357:in `get_app_screenshot_sets'
	1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.157.2/spaceship/lib/spaceship/connect_api/api_client.rb:113:in `get'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.157.2/spaceship/lib/spaceship/connect_api/api_client.rb:180:in `handle_response': Server error got 500 (Spaceship::InternalServerError)
+------------------+---------------------------+
|                 Lane Context                 |
+------------------+---------------------------+
| DEFAULT_PLATFORM | ios                       |
| PLATFORM_NAME    | ios                       |
| LANE_NAME        | ios kt_upload_screenshots |
+------------------+---------------------------+
[09:59:34]: Server error got 500

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | update_fastlane  | 3           |
| 2    | default_platform | 0           |
| 💥   | deliver          | 32          |
+------+------------------+-------------+

[09:59:34]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  beta_pa path is relative to the fastlane directory, not the project directory
    https://github.com/fastlane/fastlane/issues/500 [closed] 4 💬
    22 Sep 2016

➡️  2.150.0 deliver app_review_attachment_file failed, Server error got 500
    https://github.com/fastlane/fastlane/issues/16729 [closed] 2 💬
    2 days ago

➡️  fastlane deliver: Potential server error received: 'Unexpected Error'
    https://github.com/fastlane/fastlane/issues/16621 [closed] 120 💬
    08 Jul 2020

and 18 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09Server%20error%20got%20500&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.

[!] The request could not be completed because:
	Server error got 500

</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.6                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.6 (19G2021)                                     |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.7                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :kt_upload_screenshots do
    # add actions here: https://docs.fastlane.tools/actions
  deliver(
     skip_metadata: true,
     skip_binary_upload: true,
     overwrite_screenshots: true
  )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier(“xxxxx”) # The bundle identifier of your app
# apple_id(“xxxxxx”) # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.157.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.76.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-storage      | 1.28.0       |
| emoji_regex               | 3.0.0        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.364.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.105.0      |
| aws-sdk-kms               | 1.37.0       |
| aws-sdk-s3                | 1.79.1       |
| nanaimo                   | 0.3.0        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.18.0       |
| json                      | 2.3.1        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-09-03**
</details>

**Comment by joshdholtz** [comment]
I will look into today! Seems like there were some recent API changes that may have gone through that are effecting us 🤷‍♂️

**Comment by kashif789us** [comment]
> I will look into today! Seems like there were some recent API changes that may have gone through that are effecting us 🤷‍♂️

Thank you.

**Comment by joshdholtz** [comment]
@kashif789us I did not run into any 500 errors on my side. I wonder if you there was a snag in the App Store Connect API when you tried 🤔 Are you able to try again?

**Comment by StarLard** [comment]
I'm also having this issue

**Comment by joshdholtz** [comment]
@StarLard Do you have console output wth a stack trace that you can send me?

**Comment by kashif789us** [comment]
> @kashif789us I did not run into any 500 errors on my side. I wonder if you there was a snag in the App Store Connect API when you tried 🤔 Are you able to try again?

Still the same error. Could this be app specific? 

I tried uploading screenshots directly on AppstoreConnect and they are not uploading, getting stuck during upload :|

**Comment by joshdholtz** [comment]
@kashif789us Can you inspect the requests in your browser to see if you see any 500s happening there too? 🤔

**Comment by kashif789us** [comment]
> @kashif789us Can you inspect the requests in your browser to see if you see any 500s happening there too? 🤔

I am receiving the following error when screenshot fails to upload on Appstore Connect:

<img width="2045" alt="Screenshot 2020-09-06 at 10 41 14 AM" src="https://user-images.githubusercontent.com/2913187/92319040-ae7f6300-f02d-11ea-9841-c0057e9d83b4.png">
