### ISSUE TITLE
`get_provisioning_profile` does not honor `FASTLANE_ITC_TEAM_ID`

### ISSUE THREAD

**Issue by ozgur** [fastlane/fastlane#17135]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

First of all, this might be related to https://github.com/fastlane/fastlane/issues/17125

I am setting the environment variable `ENV["FASTLANE_ITC_TEAM_ID"]` inside `before_all` however `get_provisioning_profile` still returns the following warning:

```
The current user is in 2 teams. Pass a team ID or call `select_team` to choose a team. Using the first one for now.
```

Here is some of the content of `Fastfile`:

```
before_all do |lane, options|
  ENV["FASTLANE_ITC_TEAM_ID"] = "some itc team id"
end

lane :build_and_sign_application do |options|
    enable_automatic_code_signing
    ...
    get_provisioning_profile(
      team_id: options[:team_id],
      username: options[:apple_id],
      force: true,
      adhoc: options[:adhoc],
      app_identifier: bundle_identifier
    )
    ...
end
```

Note: I don't have any `Appfile` because there are multiple teams attached to the account I am using and which one to be used is determined by a value in `options`.

This issue doesn't happen in **2.149**.

##### Command executed

```
    get_provisioning_profile(
      team_id: options[:team_id],
      username: options[:apple_id],
      force: true,
      adhoc: options[:adhoc],
      app_identifier: bundle_identifier
    )
```
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre></pre>
</details>

### Environment

<details>
  <pre>
18:14:57 | Key                         | Value                                       |
18:14:57 | --------------------------- | ------------------------------------------- |
18:14:57 | OS                          | 10.15.5                                     |
18:14:57 | Ruby                        | 2.6.0                                       |
18:14:57 | Bundler?                    | true                                        |
18:14:57 | Git                         | git version 2.23.0                          |
18:14:57 | Installation Source         | ~/.rbenv/versions/2.6.0/bin/fastlane        |
18:14:57 | Host                        | Mac OS X 10.15.5 (19F101)                   |
18:14:57 | Ruby Lib Dir                | ~/.rbenv/versions/2.6.0/lib                 |
18:14:57 | OpenSSL Version             | OpenSSL 1.1.0j  20 Nov 2018                 |
18:14:57 | Is contained                | false                                       |
18:14:57 | Is homebrew                 | false                                       |
18:14:57 | Is installed via Fabric.app | false                                       |
18:14:57 | Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
18:14:57 | Xcode Version               | 11.6                                        |
18:14:57 
18:14:57 
18:14:57 ### System Locale
18:14:57 
18:14:57 | Variable | Value       |   |
18:14:57 | -------- | ----------- | - |
18:14:57 | LANG     | en_US.UTF-8 | ✅ |
18:14:57 | LC_ALL   | en_US.UTF-8 | ✅ |
18:14:57 | LANGUAGE | en_US.UTF-8 | ✅ | 

18:14:57 **No Appfile found**
18:14:57 
18:14:57 
18:14:57 ### fastlane gems
18:14:57 
18:14:57 | Gem      | Version | Update-Status |
18:14:57 | -------- | ------- | ------------- |
18:14:57 | fastlane | 2.157.2 | ✅ Up-To-Date  |
18:14:57 
18:14:57 
18:14:57 ### Loaded fastlane plugins:
18:14:57 
18:14:57 | Plugin                                    | Version | Update-Status |
18:14:57 | ----------------------------------------- | ------- | ------------- |
18:14:57 | fastlane-plugin-versioning                | 0.4.3   | ✅ Up-To-Date  |
18:14:57 | fastlane-plugin-firebase_app_distribution | 0.2.0   | ✅ Up-To-Date  |
18:14:57 | fastlane-plugin-get_product_bundle_id     | 0.1.4   | ✅ Up-To-Date  |
18:14:57 
18:14:57 
18:14:57 
18:14:57 | Gem                                       | Version      |
18:14:57 | ----------------------------------------- | ------------ |
18:14:57 | did_you_mean                              | 1.3.0        |
18:14:57 | bundler                                   | 2.1.4        |
18:14:57 | rake                                      | 13.0.1       |
18:14:57 | CFPropertyList                            | 3.0.2        |
18:14:57 | concurrent-ruby                           | 1.1.7        |
18:14:57 | i18n                                      | 1.8.5        |
18:14:57 | minitest                                  | 5.14.2       |
18:14:57 | thread_safe                               | 0.3.6        |
18:14:57 | tzinfo                                    | 1.2.7        |
18:14:57 | zeitwerk                                  | 2.4.0        |
18:14:57 | activesupport                             | 6.0.3.2      |
18:14:57 | builder                                   | 3.2.4        |
18:14:57 | erubi                                     | 1.9.0        |
18:14:57 | mini_portile2                             | 2.4.0        |
18:14:57 | nokogiri                                  | 1.10.10      |
18:14:57 | rails-dom-testing                         | 2.0.3        |
18:14:57 | crass                                     | 1.0.6        |
18:14:57 | loofah                                    | 2.7.0        |
18:14:57 | rails-html-sanitizer                      | 1.3.0        |
18:14:57 | actionview                                | 6.0.3.2      |
18:14:57 | rack                                      | 2.2.3        |
18:14:57 | rack-test                                 | 1.1.0        |
18:14:57 | actionpack                                | 6.0.3.2      |
18:14:57 | public_suffix                             | 4.0.6        |
18:14:57 | addressable                               | 2.7.0        |
18:14:57 | atomos                                    | 0.1.3        |
18:14:57 | aws-eventstream                           | 1.1.0        |
18:14:57 | aws-partitions                            | 1.363.0      |
18:14:57 | aws-sigv4                                 | 1.2.2        |
18:14:57 | jmespath                                  | 1.4.0        |
18:14:57 | aws-sdk-core                              | 3.105.0      |
18:14:57 | aws-sdk-kms                               | 1.37.0       |
18:14:57 | aws-sdk-s3                                | 1.79.1       |
18:14:57 | babosa                                    | 1.0.3        |
18:14:57 | claide                                    | 1.0.3        |
18:14:57 | colored                                   | 1.2          |
18:14:57 | colored2                                  | 3.1.2        |
18:14:57 | highline                                  | 1.7.10       |
18:14:57 | commander-fastlane                        | 4.4.6        |
18:14:57 | declarative                               | 0.0.20       |
18:14:57 | declarative-option                        | 0.1.0        |
18:14:57 | digest-crc                                | 0.6.1        |
18:14:57 | unf_ext                                   | 0.0.7.7      |
18:14:57 | unf                                       | 0.1.4        |
18:14:57 | domain_name                               | 0.5.20190701 |
18:14:57 | dotenv                                    | 2.7.6        |
18:14:57 | method_source                             | 1.0.0        |
18:14:57 | thor                                      | 1.0.1        |
18:14:57 | railties                                  | 6.0.3.2      |
18:14:57 | dotenv-rails                              | 2.7.6        |
18:14:57 | emoji_regex                               | 3.0.0        |
18:14:57 | excon                                     | 0.76.0       |
18:14:57 | multipart-post                            | 2.0.0        |
18:14:57 | faraday                                   | 1.0.1        |
18:14:57 | http-cookie                               | 1.0.3        |
18:14:57 | faraday-cookie_jar                        | 0.0.7        |
18:14:57 | faraday_middleware                        | 1.0.0        |
18:14:57 | fastimage                                 | 2.2.0        |
18:14:57 | gh_inspector                              | 1.1.3        |
18:14:57 | jwt                                       | 2.2.2        |
18:14:57 | memoist                                   | 0.16.2       |
18:14:57 | multi_json                                | 1.15.0       |
18:14:57 | os                                        | 1.1.1        |
18:14:57 | signet                                    | 0.14.0       |
18:14:57 | googleauth                                | 0.13.1       |
18:14:57 | httpclient                                | 2.8.3        |
18:14:57 | mini_mime                                 | 1.0.2        |
18:14:57 | uber                                      | 0.1.0        |
18:14:57 | representable                             | 3.0.4        |
18:14:57 | retriable                                 | 3.1.2        |
18:14:57 | google-api-client                         | 0.38.0       |
18:14:57 | google-cloud-env                          | 1.3.3        |
18:14:57 | google-cloud-errors                       | 1.0.1        |
18:14:57 | google-cloud-core                         | 1.5.0        |
18:14:57 | google-cloud-storage                      | 1.28.0       |
18:14:57 | json                                      | 2.3.1        |
18:14:57 | mini_magick                               | 4.10.1       |
18:14:57 | plist                                     | 3.5.0        |
18:14:57 | rubyzip                                   | 2.3.0        |
18:14:57 | security                                  | 0.1.3        |
18:14:57 | naturally                                 | 2.2.0        |
18:14:57 | simctl                                    | 1.6.8        |
18:14:57 | slack-notifier                            | 2.3.2        |
18:14:57 | terminal-notifier                         | 2.0.0        |
18:14:57 | unicode-display_width                     | 1.7.0        |
18:14:57 | terminal-table                            | 1.8.0        |
18:14:57 | tty-screen                                | 0.8.1        |
18:14:57 | tty-cursor                                | 0.7.1        |
18:14:57 | tty-spinner                               | 0.9.3        |
18:14:57 | word_wrap                                 | 1.0.0        |
18:14:57 | nanaimo                                   | 0.3.0        |
18:14:57 | xcodeproj                                 | 1.18.0       |
18:14:57 | rouge                                     | 2.0.7        |
18:14:57 | xcpretty                                  | 0.3.0        |
18:14:57 | xcpretty-travis-formatter                 | 1.0.0        |
18:14:57 | fastlane-plugin-firebase_app_distribution | 0.2.0        |
18:14:57 | fastlane-plugin-get_product_bundle_id     | 0.1.4        |
18:14:57 | fastlane-plugin-versioning                | 0.4.3        |
18:14:57 | xcode-install                             | 2.6.6        |
 </pre>
</details>

**Comment by joshdholtz** [comment]
This _should_ be fixed in https://github.com/fastlane/fastlane/pull/17136 but its not released yet 🤞

**Comment by joshdholtz** [comment]
@ozgur  Would you be able to switch your `Gemfile` to point at _fastlane_’s master branch to see if this fixes it for you? 😇

**Comment by Theodoroyb** [comment]
> It seems like you have not included the output of `fastlane env`
> To make it easier for us help you resolve this issue, please update the issue to include the output of `fastlane env` 👍

Thank you for posting something like this

**Comment by ozgur** [comment]
@joshdholtz sorry for the late reply.

It looks like the problem has been resolved after I updated fastlane using **master** branch:

```
Using fastlane 2.159.0 (was 2.149.1) from https://github.com/fastlane/fastlane.git (at master@764fa07)
```

Thank you for your effort.
