### ISSUE TITLE
App Store Connect API issues: `release_to_all_users`, download_dsyms, get_version_number

### ISSUE THREAD

**Issue by milk531** [fastlane/fastlane#17140]
```ruby
Spaceship::Tunes.login(apple_id)
Spaceship::Tunes.select_team(team_id:itc_team_id)
app = Spaceship::Tunes::Application.find(app_identifier)
app.release_to_all_users!
```
will get error `{"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Not Found"], "info"=>nil}, "statusCode"=>"ERROR"}` , I look into the code in here https://github.com/fastlane/fastlane/blob/40fdd512072c4711011e727d22ca74a4281044f6/spaceship/lib/spaceship/tunes/tunes_client.rb#L1225
It seems that this url in this code is not avaliable any more?

**Comment by bvirlet** [comment]
I confirm a similar error in a custom script, using fastlane 2.152.0, Ruby 2.6.5.

```
      app = Spaceship::Tunes::Application.find(identifier)
      version = app.latest_version <-- error
```

**Comment by hstorz** [comment]
For me as well. Yesterday the build was ok, today I got this error.

**Comment by matt-l-w** [comment]
Same for me this morning.

```
Spaceship::UnexpectedResponse: [!] {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Not Found"], "info"=>nil}, "statusCode"=>"ERROR"}
  /Users/residently/builds/xCi9xvLs/0/residently/mobile-app/vendor/ruby/2.6.0/gems/fastlane-2.157.2/spaceship/lib/spaceship/client.rb:718:in `parse_response'
  /Users/residently/builds/xCi9xvLs/0/residently/mobile-app/vendor/ruby/2.6.0/gems/fastlane-2.157.2/spaceship/lib/spaceship/tunes/tunes_client.rb:456:in `app_version_data'
  /Users/residently/builds/xCi9xvLs/0/residently/mobile-app/vendor/ruby/2.6.0/gems/fastlane-2.157.2/spaceship/lib/spaceship/tunes/tunes_client.rb:447:in `app_version'
  /Users/residently/builds/xCi9xvLs/0/residently/mobile-app/vendor/ruby/2.6.0/gems/fastlane-2.157.2/spaceship/lib/spaceship/tunes/app_version.rb:291:in `find'
  /Users/residently/builds/xCi9xvLs/0/residently/mobile-app/vendor/ruby/2.6.0/gems/fastlane-2.157.2/spaceship/lib/spaceship/tunes/application.rb:126:in `live_version'
  Fastfile:55:in `live_version_name'
```

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                                    |
| --------------------------- | ------------------------------------------------------------------------ |
| OS                          | 10.15.2                                                                  |
| Ruby                        | 2.6.3                                                                    |
| Bundler?                    | true                                                                     |
| Git                         | git version 2.24.3 (Apple Git-128)                                       |
| Installation Source         | ~/builds/xCi9xvLs/1/residently/mobile-app/vendor/ruby/2.6.0/bin/fastlane |
| Host                        | Mac OS X 10.15.2 (19C57)                                                 |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib           |
| OpenSSL Version             | LibreSSL 2.8.3                                                           |
| Is contained                | false                                                                    |
| Is homebrew                 | false                                                                    |
| Is installed via Fabric.app | false                                                                    |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                              |
| Xcode Version               | 11.5                                                                     |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require 'spaceship'

default_platform(:ios)

def current_pipeline_build_number
  File.read('../PIPELINE_BUILD_NUMBER') rescue nil
end

def ci_tag_version
  ENV['CI_COMMIT_TAG'].chomp('-ios')
end

def working_version
  version = JSON.parse(File.read('../../package.json'))['version'].split('.')
  major = version[0]
  minor = version[1]
  patch = version[2]
  {
    major: major.to_i,
    minor: minor.to_i,
    patch: patch.to_i
  }
end

def working_version_name
  working_version.values.join('.')
end

def live_version_name
  app_id = 'com.residently.app'
  apple_id = CredentialsManager::AppfileConfig.try_fetch_value(:apple_id)
  team_id = CredentialsManager::AppfileConfig.try_fetch_value(:team_id)

  UI.message("Login to App Store Connect (#{apple_id})")
  Spaceship::Tunes.login(apple_id)
  Spaceship::Tunes.select_team(team_id: team_id)
  UI.message("Login successful")

  app = Spaceship::Tunes::Application.find(app_id)
  version = app.live_version.version
  parts = version.split('.')
  {
    major: parts[0].to_i,
    minor: parts[1].to_i,
    patch: parts[2].to_i
  }
end

PROJECT = "..."

platform :ios do

  def set_app_id
    app_id = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
    UI.message("\n\nBuilding AppId: #{app_id}")
    update_app_identifier(
      xcodeproj: PROJECT,
      plist_path: '...',
      app_identifier: app_id
    )
  end

  def set_build_number(build_number)
    UI.user_error!('Build number missing') unless build_number
    increment_build_number(xcodeproj: PROJECT, build_number: build_number)
    File.write('../PIPELINE_BUILD_NUMBER', build_number)
  end

  def set_version(version)
    increment_version_number(
      version_number: version,
      xcodeproj: PROJECT
    )
  end

  def staging_badge
    version = get_version_number(xcodeproj: PROJECT, target: "Residently")
    add_badge(
      shield: "staging-#{version}-orange",
      alpha_channel: true,
      custom: '../staging-badge.png'
    )
  end

  def next_staging_version
    live_version = live_version_name
    next_patch = live_version[:patch] + 1
    "#{live_version[:major]}.#{live_version[:minor]}.#{next_patch}"
  end

  desc "Build staging release"
  lane :staging_build do
    set_app_id
    set_build_number(ENV['CI_JOB_ID'])
    set_version(next_staging_version)
    staging_badge
    get_certificates
    get_provisioning_profile
    build_app(
      workspace: "...",
      scheme: "...",
      include_bitcode: true,
      export_xcargs: "-allowProvisioningUpdates"
    )
  end

  desc "Push staging build to TestFlight"
  lane :staging_deploy do
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
    upload_to_browserstack_app_live(
      browserstack_username: ENV["BROWSERSTACK_USERNAME"],
      browserstack_access_key: ENV["BROWSERSTACK_ACCESS_KEY"],
      file_path: "..."
    )
  end

  desc "Build production release"
  lane :production_build do
    set_app_id
    set_build_number(ENV['CI_JOB_ID'])
    set_version(ci_tag_version)
    get_certificates
    get_provisioning_profile
    build_app(
      workspace: "...",
      scheme: "...",
      include_bitcode: true,
      export_xcargs: "-allowProvisioningUpdates"
    )
  end

  desc "Push production build to TestFlight"
  lane :production_deploy do
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
    upload_to_browserstack_app_live(
      browserstack_username: ENV["BROWSERSTACK_USERNAME"],
      browserstack_access_key: ENV["BROWSERSTACK_ACCESS_KEY"],
      file_path: "..."
    )
  end

  desc "Promote latest build for review"
  lane :production_promote do
    build_number = current_pipeline_build_number
    unless build_number
      UI.user_error!("Build number missing")
    end

    UI.message("Promoting build number #{build_number}")
    deliver(
      build_number: build_number,
      submit_for_review: true,
      automatic_release: true,
      force: true, # Skip HTMl report verification
      skip_metadata: false,
      skip_screenshots: false,
      skip_binary_upload: true,
      submission_information: { add_id_info_uses_idfa: false }
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier('...') # The bundle identifier of your app
apple_id('...') # Your Apple email address

itc_team_id('...') # App Store Connect Team ID
team_id('...') # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

for_lane :staging_build do
  app_identifier('com.residently.app.staging')
end

for_lane :staging_deploy do
  app_identifier('com.residently.app.staging')
end
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.157.2 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                       | Version | Update-Status |
| ---------------------------- | ------- | ------------- |
| fastlane-plugin-badge        | 1.4.0   | ✅ Up-To-Date  |
| fastlane-plugin-browserstack | 0.3.1   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                          | Version      |
| ---------------------------- | ------------ |
| did_you_mean                 | 1.3.0        |
| bundler                      | 1.17.2       |
| etc                          | 1.0.1        |
| forwardable                  | 1.2.0        |
| rake                         | 13.0.1       |
| CFPropertyList               | 3.0.2        |
| public_suffix                | 4.0.6        |
| addressable                  | 2.7.0        |
| atomos                       | 0.1.3        |
| aws-eventstream              | 1.1.0        |
| aws-partitions               | 1.364.0      |
| aws-sigv4                    | 1.2.2        |
| jmespath                     | 1.4.0        |
| aws-sdk-core                 | 3.105.0      |
| aws-sdk-kms                  | 1.37.0       |
| aws-sdk-s3                   | 1.79.1       |
| babosa                       | 1.0.3        |
| curb                         | 0.9.10       |
| fastimage                    | 2.2.0        |
| colored                      | 1.2          |
| highline                     | 1.7.10       |
| commander-fastlane           | 4.4.6        |
| dotenv                       | 2.7.6        |
| emoji_regex                  | 3.0.0        |
| excon                        | 0.76.0       |
| multipart-post               | 2.0.0        |
| faraday                      | 1.0.1        |
| unf_ext                      | 0.0.7.7      |
| unf                          | 0.1.4        |
| domain_name                  | 0.5.20190701 |
| http-cookie                  | 1.0.3        |
| faraday-cookie_jar           | 0.0.7        |
| faraday_middleware           | 1.0.0        |
| gh_inspector                 | 1.1.3        |
| jwt                          | 2.2.2        |
| memoist                      | 0.16.2       |
| multi_json                   | 1.15.0       |
| os                           | 1.1.1        |
| signet                       | 0.14.0       |
| googleauth                   | 0.13.1       |
| httpclient                   | 2.8.3        |
| mini_mime                    | 1.0.2        |
| declarative                  | 0.0.20       |
| declarative-option           | 0.1.0        |
| uber                         | 0.1.0        |
| representable                | 3.0.4        |
| retriable                    | 3.1.2        |
| google-api-client            | 0.38.0       |
| digest-crc                   | 0.6.1        |
| google-cloud-env             | 1.3.3        |
| google-cloud-errors          | 1.0.1        |
| google-cloud-core            | 1.5.0        |
| google-cloud-storage         | 1.28.0       |
| json                         | 2.3.1        |
| mini_magick                  | 4.10.1       |
| plist                        | 3.5.0        |
| rubyzip                      | 2.3.0        |
| security                     | 0.1.3        |
| naturally                    | 2.2.0        |
| simctl                       | 1.6.8        |
| slack-notifier               | 2.3.2        |
| terminal-notifier            | 2.0.0        |
| unicode-display_width        | 1.7.0        |
| terminal-table               | 1.8.0        |
| tty-screen                   | 0.8.1        |
| tty-cursor                   | 0.7.1        |
| tty-spinner                  | 0.9.3        |
| word_wrap                    | 1.0.0        |
| claide                       | 1.0.3        |
| colored2                     | 3.1.2        |
| nanaimo                      | 0.3.0        |
| xcodeproj                    | 1.18.0       |
| rouge                        | 2.0.7        |
| xcpretty                     | 0.3.0        |
| xcpretty-travis-formatter    | 1.0.0        |
| badge                        | 0.12.0       |
| fastlane-plugin-badge        | 1.4.0        |
| http-accept                  | 1.7.0        |
| mime-types-data              | 3.2019.1009  |
| mime-types                   | 3.3.1        |
| netrc                        | 0.11.0       |
| rest-client                  | 2.1.0        |
| fastlane-plugin-browserstack | 0.3.1        |
</details>


*generated on:* **2020-09-03**
</details>

**Comment by AlbertMontserrat** [comment]
Same on my side. Also in the get version call...

```
[12:05:20]: --------------------------------
[12:05:20]: --- Step: get_version_number ---
[12:05:20]: --------------------------------
+-----------------------------+---------------------------------+
|                         Lane Context                          |
+-----------------------------+---------------------------------+
| DEFAULT_PLATFORM            | ios                             |
| PLATFORM_NAME               | ios                             |
| LANE_NAME                   | ios ci_itunesconnect_validation |
| GIT_REPO_WAS_CLEAN_ON_START | true                            |
| VERSION_NUMBER              | 3.64.0                          |
+-----------------------------+---------------------------------+
[12:05:27]: {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Not Found"], "info"=>nil}, "statusCode"=>"ERROR"}
```

Also yesterday it was fine.

**Comment by AlexTheLost** [comment]
Similar problem today. Probably change in apple api.
```
	5: from /var/lib/gems/2.7.0/gems/fastlane-2.135.2/spaceship/lib/spaceship/tunes/application.rb:145:in `analytics'
	4: from /var/lib/gems/2.7.0/gems/fastlane-2.135.2/spaceship/lib/spaceship/tunes/application.rb:125:in `live_version'
	3: from /var/lib/gems/2.7.0/gems/fastlane-2.135.2/spaceship/lib/spaceship/tunes/app_version.rb:291:in `find'
	2: from /var/lib/gems/2.7.0/gems/fastlane-2.135.2/spaceship/lib/spaceship/tunes/tunes_client.rb:447:in `app_version'
	1: from /var/lib/gems/2.7.0/gems/fastlane-2.135.2/spaceship/lib/spaceship/tunes/tunes_client.rb:456:in `app_version_data'
/var/lib/gems/2.7.0/gems/fastlane-2.135.2/spaceship/lib/spaceship/client.rb:709:in `parse_response': {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Not Found"]}, "statusCode"=>"ERROR"} (Spaceship::UnexpectedResponse)

```

**Comment by joshdholtz** [comment]
Will look into today!

**Comment by joshdholtz** [comment]
So this is actually already in the _fastlane_ codebase but I don’t have any apps that I can test this sample code on 🤷‍♂️ 
Can somebody give this a try? 😊 

```rb
Spaceship::ConnectAPI.login(“your@email.com”, team_name: “Your Team Name”)
# or Spaceship::ConnectAPI.login(“your@email.com”, portal_team_id: “324234”, tunes_team_id: “D32324”)

app = Spaceship::ConnectAPI::App.find(“com.bundle.id”)

version = app. get_pending_release_app_store_version(platform: Spaceship::ConnectAPI::Platform::IOS)
Spaceship::ConnectAPI.post_app_store_version_release_request(app_store_version_id: version.id)
```

If this works, I can make a better helper method for something like `app.release` or `version.release`

**Comment by matt-l-w** [comment]
@joshdholtz - getting an undefined method for `Spaceship::ConnectAPI.login` and I can't see it [here])https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/connect_api.rb) at all. Is it off `master`?

**Comment by joshdholtz** [comment]
Yup yup, this should be on the latest release! https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/connect_api/spaceship.rb#L80

You might need to add `require ‘spaceship’` before all of that 😊

**Comment by matt-l-w** [comment]
Great - got it, thanks.

App found okay but the call to `get_pending_release_app_store_version` returns `nil`

**Comment by joshdholtz** [comment]
@matt-l-w Hmmm 🤔 What does the status of your app say on the App Store Connect dashboard?

**Comment by matt-l-w** [comment]
@joshdholtz - was just troubleshooting that myself. Now it seems obvious! 🙈 
There is no pending version as fastlane bombed out before even being able to build/upload anything.

Other methods e.g. `get_latest_app_store_version` work fine.

**Comment by joshdholtz** [comment]
@matt-l-w OHHHHH, I thought you were trying to release to all users 😱 Are you all good then with `get_latest_app_store_version `? 😇 

But if you have any other questions about `Spaceship::ConnectAPI`, the Discussions is a good spot to look for and ask questions about it there. Feel free to ping me in the Discussion!

I _really_ need to get to updating docs but other things keep coming up 🤷‍♂️

**Comment by matt-l-w** [comment]
@joshdholtz No worries, I realised the context I was in too after I reread your ask!

Yeah, we can make use of this and the pointers to the methods on this `Spaceship::ConnectAPI::App` instance should sort us out for now. Thanks!

**Comment by joshdholtz** [comment]
@ccalabro Nooooo, that broke too?! I will look into that as well!

**Comment by joshdholtz** [comment]
I’ll try and get a release out by end of day but I’ll keep you all update!

**Comment by Kaspik** [comment]
Just posting here if it helps to debug. :)

```ruby
Spaceship::Tunes.login()
app = Spaceship::Tunes::Application.find(APP_ID)
appstore_app_version = app.live_version.version
project_app_version = get_version_number(xcodeproj: PROJECT_NAME, target: TARGET_NAME)
if appstore_app_version == project_app_version
   increment_version_number(xcodeproj: PROJECT_NAME, bump_type: "minor")
   sh "git add -A && git commit -m 'Increment app version'"
end
```

```sh
bundler: failed to load command: fastlane (/Users/kaspik/.rbenv/versions/2.7.1/bin/fastlane)
Spaceship::UnexpectedResponse: [!] {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Not Found"]}, "statusCode"=>"ERROR"}
  /Users/kaspik/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.157.2/spaceship/lib/spaceship/client.rb:718:in `parse_response'
  /Users/kaspik/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.157.2/spaceship/lib/spaceship/tunes/tunes_client.rb:456:in `app_version_data'
  /Users/kaspik/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.157.2/spaceship/lib/spaceship/tunes/tunes_client.rb:447:in `app_version'
  /Users/kaspik/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.157.2/spaceship/lib/spaceship/tunes/app_version.rb:291:in `find'
  /Users/kaspik/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.157.2/spaceship/lib/spaceship/tunes/application.rb:126:in `live_version'
  Fastfile:196:in `block (2 levels) in parsing_binding'
  /Users/kaspik/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.157.2/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/kaspik/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.157.2/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
  /Users/kaspik/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.157.2/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
  /Users/kaspik/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.157.2/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:50:in `block (2 levels) in parsing_binding'
  /Users/kaspik/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.157.2/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/kaspik/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.157.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/kaspik/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.157.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/kaspik/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.157.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/kaspik/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.157.2/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /Users/kaspik/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.157.2/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/kaspik/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.157.2/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/kaspik/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/kaspik/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/kaspik/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/kaspik/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.157.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/kaspik/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/kaspik/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.157.2/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  /Users/kaspik/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.157.2/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/kaspik/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.157.2/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Users/kaspik/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.157.2/bin/fastlane:23:in `<top (required)>'
  /Users/kaspik/.rbenv/versions/2.7.1/bin/fastlane:23:in `load'
  /Users/kaspik/.rbenv/versions/2.7.1/bin/fastlane:23:in `<top (required)>'
```

**Comment by matt-l-w** [comment]
@Kaspik for reference this is what we've updated to in our Fastfile

```rb
  Spaceship::ConnectAPI.login(apple_id, team_name: team_name)

  app = Spaceship::ConnectAPI::App.find(app_id)
  version = app.get_edit_app_store_version(platform: Spaceship::ConnectAPI::Platform::IOS)
  unless version
    UI.message("No editable app store version, falling back to live version")
    version = app.get_live_app_store_version(platform: Spaceship::ConnectAPI::Platform::IOS)
  end
```

This is the equivalent to the first half of your script where you're using the `live_version` method. We were also using this.

**Comment by joshdholtz** [comment]
✨  Update

I’ve got `download_dsyms` fixed and now I’m working on `get_version_number`. After this I’ll be doing a codebase wide search for any actions that reference `live_version` or `edit_verson` and also fixing those things as well.

Sorry again about any interruptions this is causing!

**Comment by joshdholtz** [comment]
✨ Updates

Both `download_dsyms` and `app_store_build_number` are both working again! Just need to update all the tests now 😝

PR should be up in about 45 minutes. New release probably a couple hours after that.

**Comment by joshdholtz** [comment]
🚀 Fix is up in https://github.com/fastlane/fastlane/pull/17148 and ready to test if anybody is able to test 🙏 

### Testing Steps

Update `Gemfile` and run `bundle update fastlane`, `bundle update`, or `bundle install`

```rb
gem "fastlane", :git => "https://github.com/fastlane/fastlane.git", :branch => "joshdholtz-fix-broken-live-version-edit-version-actions"
```

**Comment by ccalabro** [comment]
@joshdholtz `download_dsyms` works perfectly except for one thing, it always pulls versions from AppStore instead of Testflight, using this configuration:

`download_dsyms(version: 'latest', wait_for_dsym_processing: true)`

There are newest builds on TestFlight than on AppStore but it tries to download always the AppStore one. Something that wasn't doing before this change.

**Comment by joshdholtz** [comment]
@ccalabro Thanks for letting me know! I will look into 😊

**Comment by joshdholtz** [comment]
@ccalabro Hmmm, I'm a bit confused because the this is what was previously there before my changes 👇 

```rb
latest_version = app.edit_version(platform: platform) || app.live_version(platform: platform)
```

It got the builds filtered from this version 👆 Is your current "edit version" matching with the version you are testing in TestFlight?

**Comment by ccalabro** [comment]
@joshdholtz it's a little odd how it's configured. It's actually an application that is submitted only to Tesflight for internal testers. The AppStore version is 1.0 but isn't used (never submitted), TestFlight version is 0.1 and the current build number is 548 (and growing). It'd make sense as v1.0 is greater than v0.1, but it was working before these changes.

**Comment by joshdholtz** [comment]
@ccalabro Huh... I'm honestly not sure how that was working before 😬 This did migrated from the old iTunesConnect API to the new App Store Connect API so it sounds like those API might end up returning builds in different ways 🤔 Are you able to change the App Store version to `0.1`? That should fix things for you

**Comment by ccalabro** [comment]
@joshdholtz yep, that works. Thanks for your help!

**Comment by joshdholtz** [comment]
@ccalabro Thanks for testing it out!!

**Comment by rpassis** [comment]
Not sure if this is the best issue to comment on but it looks like we are missing `app.create_version!` on the new `ConnectAPI::App`

**Comment by joshdholtz** [comment]
@rpassis Here ya go! https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/connect_api/models/app.rb#L59-L69

**Comment by joshdholtz** [comment]
@rpassis We idon'thave that exact one right now but you can use this 👉 https://github.com/fastlane/fastlane/blob/76f9fc411118d51c2b715152d6926d273978e3dc/spaceship/lib/spaceship/connect_api/models/app.rb#L165-L181

**Comment by iliao58** [comment]
@joshdholtz what is the replacement for `release_to_all_users` in `Spaceship::ConnectAPI` ?

**Comment by joshdholtz** [comment]
@iliao58 See my comment from up above 🙂 

https://github.com/fastlane/fastlane/issues/17140#issuecomment-686493328

**Comment by joshdholtz** [comment]
I'll try to get updated doc out next week!

**Comment by iliao58** [comment]
@joshdholtz I started a discussion back then https://github.com/fastlane/fastlane/pull/16765#issuecomment-665211485 and https://github.com/fastlane/fastlane/discussions/16961 . `post_app_store_version_release_request` seems to work for full release without going through phased release. if an app is under phased release, I dont think this api would work. But I could be wrong as I haven't tested neither apis. Can you confirm?

**Comment by joshdholtz** [comment]
@iliao58 I actually cannot confirm at the moment 😬 I don't have an app that is in a state for me to test that out 😔

**Comment by nellthu** [comment]
I can confirm `download_dsyms` wasn't working for me either for the same reason but it is working now in 2.157.3. Thank you for the quick fix!

**Comment by polmum** [comment]
Hey,
I have an app in phased release, and the solution proposed by @joshdholtz  [here](https://github.com/fastlane/fastlane/issues/17140#issuecomment-686493328) doesn't seem to work.
First, the app is not considered as pending release, but as live, so I had to use the get_live_app_store_version method.
Second, calling post_app_store_version_release_request returns the following error:
`Spaceship::UnexpectedResponse: [!] A relationship value is not acceptable for the current resource state. - You cannot send the latest version of the App live in the current state.`

**Comment by joshdholtz** [comment]
@polmum Thanks for trying! I don't have an app in a phased release state myself so I will see how soon I can get one of my personal apps reviewed to the state.

I really only have one chance to observe the request but that should be enough for me to adjust _fastlane_ to work. So hopefully the app will get approved for that early next week 🤞 

I'm going to create a new issue for phased release.

**Comment by polmum** [comment]
Hey @joshdholtz,
I added the needed methods and api request, tested it successfully with my app, and created a pull request #17165. Let me know if the changes work for you.

**Comment by joshdholtz** [comment]
OMG MY HERO! Thank you 😊 I will review and get released as soon as possible! I'll still try to get one of my apps in a state to test this out early next week 😉

**Comment by polmum** [comment]
Sure, sounds good!
I forgot to mention how it would be used. I did not create any helper methods, so you have to update the phased release object:
```
version = app.get_live_app_store_version(platform: Spaceship::ConnectAPI::Platform::IOS)
version.fetch_app_store_version_phased_release.complete
```

You can also call `pause` and `resume`

**Comment by radko93** [comment]
Anyone would be able to point out what privilege API key has to have to run `download_dsyms`?

**Comment by joshdholtz** [comment]
@radko93 Are you talking about using the official App Store Connect API Key? If so... `download_dsyms` does not work with that yet. It still requires an Apple ID. I have a radar into the App Store Connect API team to add an endpoint for downloading of dsyms 🤞

**Comment by nafu** [comment]
> So this is actually already in the _fastlane_ codebase but I don’t have any apps (in the correct state) that I can test this sample code on 🤷‍♂️
> Can somebody give this a try? 😊
> 
> ```ruby
> require ‘spaceship’
> Spaceship::ConnectAPI.login(“your@email.com”, team_name: “Your Team Name”)
> # or Spaceship::ConnectAPI.login(“your@email.com”, portal_team_id: “324234”, tunes_team_id: “D32324”)
> 
> app = Spaceship::ConnectAPI::App.find(“com.bundle.id”)
> 
> version = app. get_pending_release_app_store_version(platform: Spaceship::ConnectAPI::Platform::IOS)
> Spaceship::ConnectAPI.post_app_store_version_release_request(app_store_version_id: version.id)
> ```
> 
> If this works, I can make a better helper method for something like `app.release` or `version.release`

@joshdholtz `post_app_store_version_release_request` works 👍

**Comment by joshdholtz** [comment]
@nafu Perfect, glad to hear! Thanks so much for reporting back 😊 

And hope all is well with you! ❤

**Comment by nafu** [comment]
@joshdholtz 

Can I try to add helper method?
I'd like to discuss which is better. `app.release`, `version.release` or both? (Maybe we should discuss in different place? 😅 )

**Comment by joshdholtz** [comment]
@nafu For sure! Want to create a Discussion and mention me in it?

**Comment by nafu** [comment]
@joshdholtz Yes ✨ My first time GitHub Discussion :octocat:

**Comment by nafu** [comment]
@joshdholtz Created discussion 👍 https://github.com/fastlane/fastlane/discussions/17246
