### ISSUE TITLE
PROMO_GRAPHIC images are no longer supported.

### ISSUE THREAD

**Issue by bensig** [fastlane/fastlane#17147]
[12:57:36]: fastlane finished with errors
[!] Google Api Error: badRequest: PROMO_GRAPHIC images are no longer supported. - PROMO_GRAPHIC images are no longer supported.

**Comment by HimaniPatelTH** [comment]
@bensig  i am facing same issue in android . any luck for solution ?

**Comment by reshadf** [comment]
we have the same issue. Tried to release today and bumped into this.

**Comment by HimaniPatelTH** [comment]
@reshadf  that solution worked . Thank you 👍
