### ISSUE TITLE
IPAD 25 character UDID, not getting added to provisioning profiles

### ISSUE THREAD

**Issue by wahmedswl** [fastlane/fastlane#17146]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Device list has been updated and new devices has been added having 25 character UDID. Those are added to Developer Portal but not being added in the Provisioning Profile.

##### Command executed

`match(app_identifier: app_identifier, type: match_profile, force_for_new_devices: true)`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by wahmedswl** [comment]
```add_devices``` and ```match(app_identifier: app_identifier, type: match_profile, force_for_new_devices: true)``` is called within same Lane.

**Comment by wahmedswl** [comment]
Hi, is there any place to dig into this issue any hint etc

Thanks

**Comment by davis29r** [comment]
Thanks for sharing this query with us ,
I faced similar kind of issue last time, I am still searching for some proper solution please suggest any solution for htis IPAD query 
[FaceTime](https://www.facetimeapp.net/)

**Comment by wahmedswl** [comment]
seems like its working fine when ```match(app_identifier: app_identifier, type: match_profile, force: true)```.
