### ISSUE TITLE
Spaceship::ConnectAPI - undefined method `team_id'

### ISSUE THREAD

**Issue by xxsnakerxx** [fastlane/fastlane#17157]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: `2.157.3`
- Last working version: `2.157.2`

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>
Traceback (most recent call last):
        34: from /Users/dimkol/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
        33: from /Users/dimkol/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        32: from /Users/dimkol/.rvm/gems/ruby-2.6.5/bin/fastlane:23:in `<main>'
        31: from /Users/dimkol/.rvm/gems/ruby-2.6.5/bin/fastlane:23:in `load'
        30: from /Users/dimkol/.rvm/gems/ruby-2.6.5/gems/fastlane-2.157.3/bin/fastlane:23:in `<top (required)>'
        29: from /Users/dimkol/.rvm/gems/ruby-2.6.5/gems/fastlane-2.157.3/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
        28: from /Users/dimkol/.rvm/gems/ruby-2.6.5/gems/fastlane-2.157.3/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        27: from /Users/dimkol/.rvm/gems/ruby-2.6.5/gems/fastlane-2.157.3/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
        26: from /Users/dimkol/.rvm/gems/ruby-2.6.5/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        25: from /Users/dimkol/.rvm/gems/ruby-2.6.5/gems/fastlane-2.157.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        24: from /Users/dimkol/.rvm/gems/ruby-2.6.5/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        23: from /Users/dimkol/.rvm/gems/ruby-2.6.5/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        22: from /Users/dimkol/.rvm/gems/ruby-2.6.5/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        21: from /Users/dimkol/.rvm/gems/ruby-2.6.5/gems/fastlane-2.157.3/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
        20: from /Users/dimkol/.rvm/gems/ruby-2.6.5/gems/fastlane-2.157.3/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        19: from /Users/dimkol/.rvm/gems/ruby-2.6.5/gems/fastlane-2.157.3/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        18: from /Users/dimkol/.rvm/gems/ruby-2.6.5/gems/fastlane-2.157.3/fastlane/lib/fastlane/runner.rb:45:in `execute'
        17: from /Users/dimkol/.rvm/gems/ruby-2.6.5/gems/fastlane-2.157.3/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        16: from /Users/dimkol/.rvm/gems/ruby-2.6.5/gems/fastlane-2.157.3/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        15: from /Users/dimkol/.rvm/gems/ruby-2.6.5/gems/fastlane-2.157.3/fastlane/lib/fastlane/lane.rb:33:in `call'
        14: from Fastfile:103:in `block (2 levels) in parsing_binding'
        13: from /Users/dimkol/.rvm/gems/ruby-2.6.5/gems/fastlane-2.157.3/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        12: from /Users/dimkol/.rvm/gems/ruby-2.6.5/gems/fastlane-2.157.3/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        11: from /Users/dimkol/.rvm/gems/ruby-2.6.5/gems/fastlane-2.157.3/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        10: from /Users/dimkol/.rvm/gems/ruby-2.6.5/gems/fastlane-2.157.3/fastlane/lib/fastlane/runner.rb:229:in `chdir'
         9: from /Users/dimkol/.rvm/gems/ruby-2.6.5/gems/fastlane-2.157.3/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
         8: from /Users/dimkol/.rvm/gems/ruby-2.6.5/gems/fastlane-2.157.3/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
         7: from /Users/dimkol/.rvm/gems/ruby-2.6.5/gems/fastlane-2.157.3/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
         6: from /Users/dimkol/.rvm/gems/ruby-2.6.5/gems/fastlane-2.157.3/fastlane/lib/fastlane/actions/sync_code_signing.rb:13:in `run'
         5: from /Users/dimkol/.rvm/gems/ruby-2.6.5/gems/fastlane-2.157.3/match/lib/match/runner.rb:94:in `run'
         4: from /Users/dimkol/.rvm/gems/ruby-2.6.5/gems/fastlane-2.157.3/match/lib/match/runner.rb:155:in `fetch_certificate'
         3: from /Users/dimkol/.rvm/gems/ruby-2.6.5/gems/fastlane-2.157.3/match/lib/match/runner.rb:141:in `prefixed_working_directory'
         2: from /Users/dimkol/.rvm/gems/ruby-2.6.5/gems/fastlane-2.157.3/match/lib/match/storage/s3_storage.rb:75:in `prefixed_working_directory'
         1: from /Users/dimkol/.rvm/gems/ruby-2.6.5/gems/fastlane-2.157.3/match/lib/match/storage/s3_storage.rb:184:in `currently_used_team_id'
/Users/dimkol/.rvm/gems/ruby-2.6.5/gems/fastlane-2.157.3/match/lib/match/spaceship_ensure.rb:28:in `team_id': [!] undefined method `team_id' for #<Spaceship::ConnectAPI::Client:0x00007f8a51add558> (NoMethodError)
  </pre>
</details>

### Environment

<details>
  <pre>
### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.6                                     |
| Ruby                        | 2.6.5                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.28.0                          |
| Installation Source         | ~/.rvm/gems/ruby-2.6.5/bin/fastlane         |
| Host                        | Mac OS X 10.15.6 (19G2021)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.5/lib                |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.7                                        |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.157.3 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                 | Version | Update-Status |
| -------------------------------------- | ------- | ------------- |
| fastlane-plugin-increment_version_code | 0.4.3   | ✅ Up-To-Date  |
| fastlane-plugin-versioning_android     | 0.1.0   | ✅ Up-To-Date  |
| fastlane-plugin-load_json              | 0.0.1   | ✅ Up-To-Date  |
| fastlane-plugin-bugsnag                | 2.0.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                    | Version      |
| -------------------------------------- | ------------ |
| did_you_mean                           | 1.3.0        |
| executable-hooks                       | 1.6.0        |
| bundler-unload                         | 1.0.2        |
| rubygems-bundler                       | 1.4.5        |
| bundler                                | 2.1.4        |
| rake                                   | 13.0.1       |
| CFPropertyList                         | 3.0.2        |
| concurrent-ruby                        | 1.1.6        |
| i18n                                   | 0.9.5        |
| minitest                               | 5.14.1       |
| thread_safe                            | 0.3.6        |
| tzinfo                                 | 1.2.7        |
| activesupport                          | 4.2.11.3     |
| public_suffix                          | 4.0.6        |
| addressable                            | 2.7.0        |
| httpclient                             | 2.8.3        |
| json                                   | 2.3.1        |
| algoliasearch                          | 1.27.3       |
| atomos                                 | 0.1.3        |
| aws-eventstream                        | 1.1.0        |
| aws-partitions                         | 1.364.0      |
| aws-sigv4                              | 1.2.2        |
| jmespath                               | 1.4.0        |
| aws-sdk-core                           | 3.105.0      |
| aws-sdk-kms                            | 1.37.0       |
| aws-sdk-s3                             | 1.79.1       |
| babosa                                 | 1.0.3        |
| claide                                 | 1.0.3        |
| fuzzy_match                            | 2.0.4        |
| nap                                    | 1.1.0        |
| netrc                                  | 0.11.0       |
| ffi                                    | 1.13.1       |
| ethon                                  | 0.12.0       |
| typhoeus                               | 1.4.0        |
| cocoapods-core                         | 1.9.3        |
| cocoapods-deintegrate                  | 1.0.4        |
| cocoapods-downloader                   | 1.3.0        |
| cocoapods-plugins                      | 1.0.0        |
| cocoapods-search                       | 1.0.0        |
| cocoapods-stats                        | 1.1.0        |
| cocoapods-trunk                        | 1.5.0        |
| cocoapods-try                          | 1.2.0        |
| colored2                               | 3.1.2        |
| escape                                 | 0.0.4        |
| fourflusher                            | 2.3.1        |
| gh_inspector                           | 1.1.3        |
| molinillo                              | 0.6.6        |
| ruby-macho                             | 1.4.0        |
| nanaimo                                | 0.3.0        |
| xcodeproj                              | 1.18.0       |
| cocoapods                              | 1.9.3        |
| colored                                | 1.2          |
| highline                               | 1.7.10       |
| commander-fastlane                     | 4.4.6        |
| declarative                            | 0.0.20       |
| declarative-option                     | 0.1.0        |
| digest-crc                             | 0.6.1        |
| unf_ext                                | 0.0.7.7      |
| unf                                    | 0.1.4        |
| domain_name                            | 0.5.20190701 |
| dotenv                                 | 2.7.6        |
| emoji_regex                            | 3.0.0        |
| excon                                  | 0.76.0       |
| multipart-post                         | 2.0.0        |
| faraday                                | 1.0.1        |
| http-cookie                            | 1.0.3        |
| faraday-cookie_jar                     | 0.0.7        |
| faraday_middleware                     | 1.0.0        |
| fastimage                              | 2.2.0        |
| jwt                                    | 2.2.2        |
| memoist                                | 0.16.2       |
| multi_json                             | 1.15.0       |
| os                                     | 1.1.1        |
| signet                                 | 0.14.0       |
| googleauth                             | 0.13.1       |
| mini_mime                              | 1.0.2        |
| uber                                   | 0.1.0        |
| representable                          | 3.0.4        |
| retriable                              | 3.1.2        |
| google-api-client                      | 0.38.0       |
| google-cloud-env                       | 1.3.3        |
| google-cloud-errors                    | 1.0.1        |
| google-cloud-core                      | 1.5.0        |
| google-cloud-storage                   | 1.28.0       |
| mini_magick                            | 4.10.1       |
| plist                                  | 3.5.0        |
| rubyzip                                | 2.3.0        |
| security                               | 0.1.3        |
| naturally                              | 2.2.0        |
| simctl                                 | 1.6.8        |
| slack-notifier                         | 2.3.2        |
| terminal-notifier                      | 2.0.0        |
| unicode-display_width                  | 1.7.0        |
| terminal-table                         | 1.8.0        |
| tty-screen                             | 0.8.1        |
| tty-cursor                             | 0.7.1        |
| tty-spinner                            | 0.9.3        |
| word_wrap                              | 1.0.0        |
| rouge                                  | 2.0.7        |
| xcpretty                               | 0.3.0        |
| xcpretty-travis-formatter              | 1.0.0        |
| rchardet                               | 1.8.0        |
| git                                    | 1.7.0        |
| xml-simple                             | 1.1.5        |
| fastlane-plugin-bugsnag                | 2.0.0        |
| fastlane-plugin-increment_version_code | 0.4.3        |
| fastlane-plugin-load_json              | 0.0.1        |
| fastlane-plugin-versioning_android     | 0.1.0        |

</pre>
</details>

**Comment by joshdholtz** [comment]
Looking into right away!
