### ISSUE TITLE
Precheck fails (Spaceship::UnexpectedResponse)

### ISSUE THREAD

**Issue by noxo** [fastlane/fastlane#17158]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
fastlane precheck command fails

##### Command executed
precheck(include_in_app_purchases: false)

##### Complete output when running fastlane, including the stack trace and command used
```
/Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/spaceship/lib/spaceship/client.rb:719:in `parse_response': [!] {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Not Found"], "info"=>nil}, "statusCode"=>"ERROR"} (Spaceship::UnexpectedResponse)
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/spaceship/lib/spaceship/tunes/tunes_client.rb:456:in `app_version_data'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/spaceship/lib/spaceship/tunes/tunes_client.rb:447:in `app_version'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/spaceship/lib/spaceship/tunes/app_version.rb:291:in `find'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/spaceship/lib/spaceship/tunes/application.rb:126:in `live_version'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/spaceship/lib/spaceship/tunes/application.rb:137:in `latest_version'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/precheck/lib/precheck/runner.rb:167:in `latest_app_version'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/precheck/lib/precheck/runner.rb:33:in `run'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/actions/check_app_store_metadata.rb:10:in `run'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:76:in `block (2 levels) in parsing_binding'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/bin/fastlane:23:in `<top (required)>'
	from /Users/dev/.rvm/gems/ruby-2.6.0/bin/fastlane:23:in `load'
	from /Users/dev/.rvm/gems/ruby-2.6.0/bin/fastlane:23:in `<main>'
	from /Users/dev/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `eval'
	from /Users/dev/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `<main>'
/Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/spaceship/lib/spaceship/client.rb:719:in `parse_response': {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Not Found"], "info"=>nil}, "statusCode"=>"ERROR"} (Spaceship::UnexpectedResponse)
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/spaceship/lib/spaceship/tunes/tunes_client.rb:456:in `app_version_data'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/spaceship/lib/spaceship/tunes/tunes_client.rb:447:in `app_version'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/spaceship/lib/spaceship/tunes/app_version.rb:291:in `find'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/spaceship/lib/spaceship/tunes/application.rb:126:in `live_version'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/spaceship/lib/spaceship/tunes/application.rb:137:in `latest_version'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/precheck/lib/precheck/runner.rb:167:in `latest_app_version'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/precheck/lib/precheck/runner.rb:33:in `run'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/actions/check_app_store_metadata.rb:10:in `run'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:76:in `block (2 levels) in parsing_binding'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.157.3/bin/fastlane:23:in `<top (required)>'
	from /Users/dev/.rvm/gems/ruby-2.6.0/bin/fastlane:23:in `load'
	from /Users/dev/.rvm/gems/ruby-2.6.0/bin/fastlane:23:in `<main>'
	from /Users/dev/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `eval'
	from /Users/dev/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `<main>'
```
### Environment
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.6                                     |
| Ruby                        | 2.6.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.rvm/gems/ruby-2.6.0/bin/fastlane         |
| Host                        | Mac OS X 10.15.6 (19G73)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.1a  20 Nov 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.5                                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.157.3 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 1.0.1        |
| faraday_middleware        | 1.0.0        |
| gh_inspector              | 1.1.3        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| uber                      | 0.1.0        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| nanaimo                   | 0.3.0        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.18.0       |
| unicode-display_width     | 1.7.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| excon                     | 0.76.0       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| fastimage                 | 2.2.0        |
| json                      | 2.3.1        |
| mini_magick               | 4.10.1       |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| declarative               | 0.0.20       |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| os                        | 1.1.1        |
| memoist                   | 0.16.2       |
| googleauth                | 0.13.1       |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-env          | 1.3.3        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.28.0       |
| emoji_regex               | 3.0.0        |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-partitions            | 1.364.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.105.0      |
| aws-sdk-kms               | 1.37.0       |
| aws-sdk-s3                | 1.79.1       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.1.0        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.10      |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

**Comment by noxo** [comment]
looks similar as #17150

**Comment by Katsz** [comment]
Got same exact error by calling `Spaceship::Tunes::Application::latest_version`

```ruby
irb(main):038:0> tunes_app.class
=> Spaceship::Tunes::Application
irb(main):039:0> tunes_app.latest_version
Spaceship::UnexpectedResponse ({"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Not Found"], "info"=>nil}, "statusCode"=>"ERROR"})
irb(main):040:0> 
```

It seems like apple messing with API as it was working few hours ago at `2.149.1` as well as `2.157.2`.

**Comment by vsharp** [comment]
Getting the same error when checking for latest version.

**Comment by joshdholtz** [comment]
I got this fixed in a local branch and will have a PR up in a few hours! Most of `Spaceship::Tunes` is no longer working and everything is getting migrated over to `Spaceship::ConnectAPI`.
