### ISSUE TITLE
This bundle is invalid. The value for key CFBundleShortVersionString in the Info.plist file must contain a higher version

### ISSUE THREAD

**Issue by mikedoubintchik** [fastlane/fastlane#17170]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I have my CFBundleShortVersionString set to 5.0.1, but TestFlight is thinking it's 4.9.0. The latest version in TestFlight and AppStore is 5.0.0. Version 4.9.0 is the previous version. I couldn't find 4.9.0 anywhere in my code. No iOS files are committed to the repo. I am starting from a fresh cloned version of the repo.

The error message is:

```
[19:13:07]: ERROR ITMS-90062: "This bundle is invalid. The value for key CFBundleShortVersionString [4.9.0] in the Info.plist file must contain a higher version than that of the previously approved version [5.0.0]. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring"
Return status of iTunes Transporter was 1: ERROR ITMS-90062: "This bundle is invalid. The value for key CFBundleShortVersionString [4.9.0] in the Info.plist file must contain a higher version than that of the previously approved version [5.0.0]. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring"
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
```

EDIT: If in the upload_to_testflight step I submit the generated IPA file from the build_ios_app step, then it does work.

##### Command executed

bundle exec fastlane deploy:ios

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.6                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | ~/Tools/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.4/bin/fastlane |
| Host                        | Mac OS X 10.15.6 (19G2021)                                     |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.7                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE

ENV['app_identifier'] = "com.bcbsnc.BCBSNC"
ENV['app_name_sanitized'] = "BlueConnect"
ENV['TEAMS_WEBHOOK'] = "https://outlook.office.com/webhook/2f6f8317-0008-48bf-9845-e58dd52cc546@8554e7b2-e668-4c1c-8d27-3b12f5c733ac/IncomingWebhook/e62e452a581f4314bae9ca765e28ed49/77343f59-1ab0-4dd7-b44a-2797e72644a0"

# Update Fastlane
update_fastlane

private_lane :clean do
	sh "cd .. && rm -rf www/* && rm -rf node_modules && rm -rf bower_components && rm -rf platforms/ && rm -rf plugins"
end

private_lane :prepare do
	# Yes, prepare is in there twice, I've seen where it will only install 1 os when you run prepare
	# but running it again will add the other. This is a safe operation so if it does add both the
  # second run will not hurt anything
  # cordova prepare populates platforms and plugins folders
	sh "cd .. && npm i && npx bower install && npx cordova prepare && npx cordova prepare"
end

private_lane :tag do |options|
  add_git_tag(
    tag: "#{ENV['next_version']}_#{ENV['next_build']}-#{ENV['BUILD_CONFIG']}",
    force: true
  )
end

private_lane :git do
  push_to_git_remote(
    remote: "origin",
    local_branch: "#{ENV['current_branch']}",
    remote_branch: "#{ENV['current_branch']}",
    force: true,
    tags: true,
    no_verify: true
  )
end

private_lane :notify_success do |options|
  title = options[:title]
  success = options[:success]
  build_number = options[:build_number]
  release = options[:release]
  teams(
    title: title,
    message: "",
    facts:[
      {
        "name" => "Built by",
        "value" => "Magical Unicorns 🦄🌈"
      },
      {
        "name" => "Platform",
        "value" => release
      },
      {
        "name" => "Build",
        "value" => build_number
      }
    ],
    teams_url: ENV['TEAMS_WEBHOOK']
  )
end

def notify_fail(exception)
  teams(
    title: "Failed to build app",
    message: "",
    facts:[
      {
        "name" => "Build Date",
        "value" => Time.new.to_s
      },
      {
        "name" => "Built by",
        "value" => "Magical Unicorns 🦄🌈"
      },
      {
        "name" => "Error",
        "value" => exception
      }
    ],
    teams_url: ENV['TEAMS_WEBHOOK']
  )
end

def on_error(exception)
  notify_fail(exception)
end

private_lane :promote_latest_testflight_build do
  puts "Promoting #{ENV['next_version']} (#{ENV['current_build']}) for review."

  deliver(
    submit_for_review: true,
    #automatic_release: true,
    force: true, # Skip HTMl report verification
    skip_metadata: true,
    skip_screenshots: true,
    skip_binary_upload: true,
    submission_information: {
      add_id_info_uses_idfa: false,
      content_rights_has_rights: true,
      content_rights_contains_third_party_content: true,
      export_compliance_platform: 'ios',
      export_compliance_compliance_required: false,
      export_compliance_encryption_updated: false,
      export_compliance_app_type: nil,
      export_compliance_uses_encryption: false,
      export_compliance_is_exempt: false,
      export_compliance_contains_third_party_cryptography: false,
      export_compliance_contains_proprietary_cryptography: false,
      export_compliance_available_on_french_store: false
    }
  )
end

lane :download_app_store_assets do
  deliver download_screenshots
  deliver download_metadata
end

platform :ios do
  desc 'Setting variables'
  before_all do
    ENV['DEPLOY_TARGET'] = ENV['DEPLOY_TARGET'] || UI.select("Which deploy target do you want to use?: ", ["TestFlight", "App Store"])
    ENV['BUILD_CONFIG'] = ENV['BUILD_CONFIG'] || UI.select("Which deploy target do you want to use?: ", ["ci", "staging", "prod", "prod:ci", "registration"])
		ENV['ios_path'] = "platforms/ios/"
		ENV['ios_project_path'] = "#{ENV['ios_path']}#{ENV['app_name_sanitized']}.xcodeproj"
		ENV['ios_workspace_path'] = "#{ENV['ios_path']}#{ENV['app_name_sanitized']}.xcworkspace"
    ENV['FASTLANE_USER'] = "mobiledistribution@bcbsnc.com"
    ENV['FASTLANE_PASSWORD'] = "Bcbsnc1!"
    ENV['MATCH_PASSWORD'] ="weboffice"

    # Versioning
    readme_yaml = File.read('../CHANGELOG.yml')
    readme_data = YAML.safe_load(readme_yaml)

    # Constants
    ENV['next_version'] = readme_data['upcoming']['version']
    ENV['current_build'] = "#{latest_testflight_build_number(version: ENV['next_version'], initial_build_number: 0).to_i}"
    ENV['next_build'] = "#{ENV['current_build'].to_i + 1}"
    ENV['current_branch'] = git_branch
  end

  desc 'Unlocking keychain'
	private_lane :unlock do
		sh 'security unlock-keychain -p weboffice'
  end

  desc 'Building WWW folder'
  private_lane :build_www do
    sh "cd .. && npm i "
    sh "cp ../envs/.env.#{ENV['BUILD_CONFIG']} ../.env"
    sh "cd .. && npx gulp build:#{ENV['BUILD_CONFIG']}"
  end

  desc 'Building Cordova App for iOS'
	private_lane :build do
    clean
    prepare
    build_www
    # set version and build numbers
    increment_version_number(version_number: ENV['next_version'], xcodeproj: ENV['ios_project_path'])
    increment_build_number(build_number: ENV['next_build'], xcodeproj: ENV['ios_project_path'])
    sh "npx cordova build ios --release --no-telemetry"
	end

  desc "Deploy iOS App to TestFlight"
  lane :deploy do
    begin
    # build app assets
    unlock
    build

    # app signing
    sync_code_signing(type: "appstore", readonly: true)
    update_code_signing_settings(
      path: ENV['ios_project_path'],
      team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
      targets: ["#{ENV['app_name_sanitized']}"],
      profile_name: 'match AppStore com.bcbsnc.BCBSNC',
      build_configurations: 'Release',
      code_sign_identity: 'Apple Distribution'
    )

    # create build
    ipa_name = "#{ENV['app_name_sanitized']}_#{ENV['BUILD_CONFIG']}_#{ENV['next_version']}.ipa"

    build_ios_app(
      scheme: ENV['app_name_sanitized'],
      workspace: ENV['ios_workspace_path'],
      silent: true,
      output_directory: ENV['ios_path'],
      output_name: "#{ipa_name}",
    )

    # Deploy to TestFlight
    if ENV['DEPLOY_TARGET'] == "TestFlight"
      puts "Submitting #{ENV['BUILD_CONFIG']} build to TestFlight"
      # stop VPN
      sh "launchctl unload /Library/LaunchAgents/com.paloaltonetworks.gp.pangp*"

      upload_to_testflight(
        skip_waiting_for_build_processing: true,
        changelog: "#{ENV['BUILD_CONFIG']} build #{ENV['next_version']}", # Test Details
      )

      # Notify
      notify_success(
        title: "🎉🎉 New BCM Deploy: #{ENV['next_version']} (#{ENV['next_build']}) #{ENV['BUILD_CONFIG']} 🎉🎉",
        success: true,
        build_number: "#{ENV['next_version']} (#{ENV['next_build']}) #{ENV['BUILD_CONFIG']}",
        release: "TestFlight"
      )

    # Deploy to App Store
    elsif ENV['DEPLOY_TARGET'] == "App Store"
      puts "submitting to app store"
    end

    # start VPN
    sh "launchctl load /Library/LaunchAgents/com.paloaltonetworks.gp.pangp*"
    rescue => exception
        on_error(exception)
    end
  end

  desc "Push latest TestFlight build for review"
  lane :release do
    begin
      # Versioning
      readme_yaml = File.read('../../CHANGELOG.yml')
      readme_data = YAML.safe_load(readme_yaml)

      # Constants
      current_version = readme_data['upcoming']['version']

      # Promote build
      set_changelog(
        changelog: "#{readme_data['upcoming']['user_facing'][0]}",
        version: current_version
      )
      promote_latest_testflight_build

      # Notify
      notify_success(
        title: ":tada: :tada: New BCM Prod Release: #{current_version} (#{ENV['current_build']})",
        success: true,
        build_number: "#{current_version} (#{ENV['current_build']})",
        release: "App Store"
      )

      puts "All done."
    rescue => exception
        on_error(exception)
    end
  end
end


platform :android do
  before_all do
    ENV['DEPLOY_TARGET'] = ENV['DEPLOY_TARGET'] || UI.select("Which deploy target do you want to use?: ", ["Alpha Store", "Play Store"])
    ENV['BUILD_CONFIG'] = ENV['BUILD_CONFIG'] || UI.select("Which deploy target do you want to use?: ", ["ci", "release", "registration"])
    ENV['CORDOVA_ANDROID_RELEASE_BUILD_PATH'] = "platforms/android/app/build/outputs/apk/debug/app-debug.apk"
  end

  desc "Deploy android app on play store"

  lane :deploy do
    cordova(
      platform: 'android',
      keystore_path: './prod.keystore',
      keystore_alias: 'prod',
      keystore_password: 'password'
    )
    supply(apk: ENV['CORDOVA_ANDROID_RELEASE_BUILD_PATH'])
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.bcbsnc.BCBSNC") # The bundle identifier of your app
apple_id("mobiledistribution@bcbsnc.com") # Your Apple email address

itc_team_id("389101") # App Store Connect Team ID
team_id("7R8JY68R4K") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.158.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status |
| ----------------------- | ------- | ------------- |
| fastlane-plugin-cordova | 3.0.0   | ✅ Up-To-Date  |
| fastlane-plugin-teams   | 0.2.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| bundler                   | 2.1.4        |
| rake                      | 13.0.1       |
| CFPropertyList            | 3.0.2        |
| concurrent-ruby           | 1.1.7        |
| i18n                      | 0.9.5        |
| minitest                  | 5.14.2       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.7        |
| activesupport             | 4.2.11.3     |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| httpclient                | 2.8.3        |
| json                      | 2.3.1        |
| algoliasearch             | 1.27.3       |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.365.0      |
| aws-sigv4                 | 1.2.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.105.0      |
| aws-sdk-kms               | 1.37.0       |
| aws-sdk-s3                | 1.79.1       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| netrc                     | 0.11.0       |
| ffi                       | 1.13.1       |
| ethon                     | 0.12.0       |
| typhoeus                  | 1.4.0        |
| cocoapods-core            | 1.9.3        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.4.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| cocoapods-trunk           | 1.5.0        |
| cocoapods-try             | 1.2.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.18.0       |
| cocoapods                 | 1.9.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.0.0        |
| excon                     | 0.76.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 1.0.1        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| jwt                       | 2.2.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| signet                    | 0.14.0       |
| googleauth                | 0.13.1       |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.28.0       |
| mini_magick               | 4.10.1       |
| plist                     | 3.5.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-cordova   | 3.0.0        |
| fastlane-plugin-teams     | 0.2.0        |
</details>

*generated on:* **2020-09-04**
</details> </pre>
</details>

**Comment by max-ott** [comment]
If you open the project / workspace in Xcode, what version / build numbers are shown?

**Comment by mikedoubintchik** [comment]
They are the correct ones in xcode, matching the info.plist file
