### ISSUE TITLE
Precheck fails (undefined method `copyright' for nil:NilClass (NoMethodError))

### ISSUE THREAD

**Issue by noxo** [fastlane/fastlane#17176]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [ x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
precheck fails in v2.158.0

##### Command executed
precheck(include_in_app_purchases: false)

##### Complete output when running fastlane, including the stack trace and command used

<details>
 <pre>

🔗  You can ⌘ + double-click on links to open them directly in your browser.

/Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/precheck/lib/precheck/rule_processor.rb:177:in `generate_version_items_to_check': [!] undefined method `copyright' for nil:NilClass (NoMethodError)
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/precheck/lib/precheck/rule_processor.rb:48:in `process_app_and_version'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/precheck/lib/precheck/runner.rb:102:in `check_for_rule_violations'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/precheck/lib/precheck/runner.rb:34:in `run'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/actions/check_app_store_metadata.rb:10:in `run'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:76:in `block (2 levels) in parsing_binding'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/bin/fastlane:23:in `<top (required)>'
	from /Users/dev/.rvm/gems/ruby-2.6.0/bin/fastlane:23:in `load'
	from /Users/dev/.rvm/gems/ruby-2.6.0/bin/fastlane:23:in `<main>'
	from /Users/dev/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `eval'
	from /Users/dev/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `<main>'
/Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/precheck/lib/precheck/rule_processor.rb:177:in `generate_version_items_to_check': undefined method `copyright' for nil:NilClass (NoMethodError)
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/precheck/lib/precheck/rule_processor.rb:48:in `process_app_and_version'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/precheck/lib/precheck/runner.rb:102:in `check_for_rule_violations'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/precheck/lib/precheck/runner.rb:34:in `run'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/actions/check_app_store_metadata.rb:10:in `run'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:76:in `block (2 levels) in parsing_binding'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/bin/fastlane:23:in `<top (required)>'
	from /Users/dev/.rvm/gems/ruby-2.6.0/bin/fastlane:23:in `load'
	from /Users/dev/.rvm/gems/ruby-2.6.0/bin/fastlane:23:in `<main>'
	from /Users/dev/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `eval'

</pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by joshdholtz** [comment]
Will look into right away!
