### ISSUE TITLE
`Match` creates Provisioning Profiles with wrong "Enabled Capabilities"

### ISSUE THREAD

**Issue by fzyzcjy** [fastlane/fastlane#17172]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I use `fastlane match appstore` to create suitable provisioning profiles and certificates. When looking at the profile (at https://developer.apple.com/account/resources/profiles/review/the_id_of_profile), I see:
```
Enabled Capabilities
Game Center, In-App Purchase
```

However, I do **NOT** use the two capabilities! Here is a screenshot of xcode of the project proving this:

![image](https://user-images.githubusercontent.com/5236035/92321225-e2bd4880-f05a-11ea-99b9-07943cd7724d.png)

Thus, how can I remove these two capabilities?

Thanks very much!

##### Command executed

fastlane match appstore

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[15:52:23]: -------------------
[15:52:23]: --- Step: match ---
[15:52:23]: -------------------
[15:52:23]: Successfully loaded '/Users/tom/QAPMain/Development/rzzsdxx_frontend/proj/ios/fastlane/Matchfile' 📄

+--------------+------------------------------------------------------+
|             Detected Values from './fastlane/Matchfile'             |
+--------------+------------------------------------------------------+
| git_url      | git@github.com:fzyzcjy/fastlane-ios-certificates.git |
| storage_mode | git                                                  |
| type         | development                                          |
+--------------+------------------------------------------------------+

+--------------------------------+------------------------------------------------------+
|                               Summary for match 2.158.0                               |
+--------------------------------+------------------------------------------------------+
| type                           | appstore                                             |
| readonly                       | false                                                |
| generate_apple_certs           | true                                                 |
| skip_provisioning_profiles     | false                                                |
| app_identifier                 | ["com.rzzsdxx.proj"]                                 |
| username                       | ch271828n@outlook.com                                |
| team_id                        | QSBDNU2Y9B                                           |
| storage_mode                   | git                                                  |
| git_url                        | git@github.com:fzyzcjy/fastlane-ios-certificates.git |
| git_branch                     | master                                               |
| shallow_clone                  | false                                                |
| clone_branch_directly          | false                                                |
| keychain_name                  | login.keychain                                       |
| force                          | false                                                |
| force_for_new_devices          | false                                                |
| skip_confirmation              | false                                                |
| skip_docs                      | false                                                |
| platform                       | ios                                                  |
| derive_catalyst_app_identifier | false                                                |
| fail_on_name_taken             | false                                                |
| verbose                        | false                                                |
+--------------------------------+------------------------------------------------------+

[15:52:23]: Cloning remote git repo...
[15:52:23]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[15:52:31]: Checking out branch master...
[15:52:31]: 🔓  Successfully decrypted certificates repo
[15:52:31]: Verifying that the certificate and profile are still valid on the Dev Portal...
[15:52:34]: Installing certificate...

+-------------------+----------------------------------------------+
|                      Installed Certificate                       |
+-------------------+----------------------------------------------+
| User ID           | QSBDNU2Y9B                                   |
| Common Name       | Apple Distribution: Jingyi Chen (QSBDNU2Y9B) |
| Organisation Unit | QSBDNU2Y9B                                   |
| Organisation      | Jingyi Chen                                  |
| Country           | CN                                           |
| Start Datetime    | 2020-09-06 06:53:48 UTC                      |
| End Datetime      | 2021-09-06 06:53:48 UTC                      |
+-------------------+----------------------------------------------+

[15:52:35]: Installing provisioning profile...

+---------------------+----------------------------------------+----------------------------------------+
|                                    Installed Provisioning Profile                                     |
+---------------------+----------------------------------------+----------------------------------------+
| Parameter           | Environment Variable                   | Value                                  |
+---------------------+----------------------------------------+----------------------------------------+
| App Identifier      |                                        | com.rzzsdxx.proj                       |
| Type                |                                        | appstore                               |
| Platform            |                                        | ios                                    |
| Profile UUID        | sigh_com.rzzsdxx.proj_appstore         | 5e17b5ee-ed8a-498e-bb39-a46c4c39259d   |
| Profile Name        | sigh_com.rzzsdxx.proj_appstore_profil  | match AppStore com.rzzsdxx.proj        |
|                     | e-name                                 |                                        |
| Profile Path        | sigh_com.rzzsdxx.proj_appstore_profil  | /Users/tom/Library/MobileDevice/Provi  |
|                     | e-path                                 | sioning                                |
|                     |                                        | Profiles/5e17b5ee-ed8a-498e-bb39-a46c  |
|                     |                                        | 4c39259d.mobileprovision               |
| Development Team ID | sigh_com.rzzsdxx.proj_appstore_team-i  | QSBDNU2Y9B                             |
|                     | d                                      |                                        |
+---------------------+----------------------------------------+----------------------------------------+

[15:52:37]: All required keys, certificates and provisioning profiles are installed 🙌
[15:52:37]: Setting Provisioning Profile type to 'app-store'
 </pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.3                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.3 (19D76)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.7                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :deploy do
    # TODO 关于push notification (`get_push_certificate`)
    # https://docs.fastlane.tools/getting-started/ios/appstore-deployment/#best-practices

    # https://docs.fastlane.tools/codesigning/getting-started/#using-cert-and-sigh
    # NOTE Xcode也需要设置 https://docs.fastlane.tools/codesigning/xcode-project/
    match(type: "appstore") # TODO type?

    # https://circleci.com/blog/deploy-flutter-android/
    Dir.chdir "../.." do
      sh("flutter", "packages", "get")
      # sh("flutter", "clean")
      sh("flutter", "build", "ios",
         # TODO
         # "--obfuscate", "--split-debug-info=build/split-debug-info",
         "--release",
         "--no-codesign"
      )
    end

    build_ios_app(
        # scheme is seen here https://flutter.dev/docs/deployment/ios#create-a-build-archive
        scheme: "Runner",
        # include_bitcode: true, # TODO 好像要bitcode才能优化？
    )

    # NOTE 暂时先不做，因为看起来会从app store自动拉取信息(即报错无法在connect中找到我这个app)，那我们第一次还是手动上传吧
    # Apple Store Connect的定义：... is a suite of web-based tools for managing apps sold on the App Store
    # upload_to_app_store

  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.rzzsdxx.proj") # The bundle identifier of your app
apple_id("ch271828n@outlook.com") # Your Apple email address

itc_team_id("122060207") # App Store Connect Team ID
team_id("QSBDNU2Y9B") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.158.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.76.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-storage      | 1.28.0       |
| emoji_regex               | 3.0.0        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.365.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.105.0      |
| aws-sdk-kms               | 1.37.0       |
| aws-sdk-s3                | 1.79.1       |
| nanaimo                   | 0.3.0        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.18.0       |
| json                      | 2.3.1        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-09-06**
</details> </pre>
</details>

**Comment by Katsz** [comment]
Strictly speaking you can't disable Game Center and In-app Purchase capabilities anymore. They are automatically added when you creating new bundle id. But they don't affect your app in any way, so you may just neglect them.

**Comment by Katsz** [comment]
>Just to be clear - this is not fastlane's fault, Game Center and In-app Purchase will be automatically enabled even if you are to create new bundle id from xcode or at developer.apple.com.

**Comment by fzyzcjy** [comment]
@Katsz Thanks very much!
