### ISSUE TITLE
upload_to_play_store_internal_app_sharing not uploading the build.

### ISSUE THREAD

**Issue by vadimleonov** [fastlane/fastlane#17178]
### Issue Description
I'm following [this lane](https://docs.fastlane.tools/actions/upload_to_play_store_internal_app_sharing/#parameters-legend-dynamic) written by @andrewhavens to upload Android build to the Internal App Sharing.

Everything works fine, the output always is like:

```
[12:36:13]: Successfully uploaded APK to Internal App Sharing URL: https://play.google.com/apps/test/generatedHashByGoogle/generatedHashByGoogle
[12:36:13]: Result: https://play.google.com/apps/test/generatedHashByGoogle/generatedHashByGoogle
```

But after copy-pasting the URL to the browser it returns me: `Not Found Error 404` and seems that the link is not working.
![image](https://user-images.githubusercontent.com/35032429/92375288-98df6b80-f109-11ea-8735-403f0b347e91.png)

I am also opened the `https://play.google.com/console/internal-app-sharing` to check if the build is uploaded or not, and I can't find any actual `apk` here.

Only **after** uploading the same `apk` manually to the `https://play.google.com/console/internal-app-sharing` the link generated by fastlane becomes working.

What is wrong here? 

### Command executed

<details>
<pre>
[12:46:18]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅
vadimsleonovs@Vadimss-MacBook-Pro fastlane-test % fastlane run upload_to_play_store_internal_app_sharing package_name:"package.id" json_key:"somePath/file.json" apk:"somePath/app-release.apk"
[✔] 🚀 
[12:46:56]: fastlane detected a Gemfile in the current directory
[12:46:56]: However, it seems like you didn't use `bundle exec`
[12:46:56]: To launch fastlane faster, please use
[12:46:56]: 
[12:46:56]: $ bundle exec fastlane run upload_to_play_store_internal_app_sharing package_name:com.mine.mods.mermaid json_key:/somePath/file.json apk:/somePath/app-release.apk
[12:46:56]: 
[12:46:56]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[12:47:02]: -------------------------------------------------------
[12:47:02]: --- Step: upload_to_play_store_internal_app_sharing ---
[12:47:02]: -------------------------------------------------------
[12:47:17]: Successfully uploaded APK to Internal App Sharing URL: https://play.google.com/apps/test/generatedHashByGoogle/generatedHashByGoogle
[12:47:17]: Result: https://play.google.com/apps/test/generatedHashByGoogle/generatedHashByGoogle
vadimsleonovs@Vadimss-MacBook-Pro fastlane-test %
</pre>
</details>

### Environment

<details>
<pre>
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 10.15.6                                                 |
| Ruby                        | 2.7.1                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.24.3 (Apple Git-128)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.158.0/libexec/bin/fastlane |
| Host                        | Mac OS X 10.15.6 (19G2021)                              |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.7.1_2/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1f  31 Mar 2020                             |
| Is contained                | false                                                   |
| Is homebrew                 | false                                                   |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 11.6                                                    |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.158.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.18.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.76.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.2        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-storage      | 1.28.0       |
| emoji_regex               | 3.0.0        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.365.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.105.0      |
| aws-sdk-kms               | 1.37.0       |
| aws-sdk-s3                | 1.79.1       |
| uri                       | 0.10.0       |
| json                      | 2.3.1        |
| forwardable               | 1.3.1        |
| logger                    | 1.4.2        |
| cgi                       | 0.1.0        |
| timeout                   | 0.1.0        |
| stringio                  | 0.1.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.2.0        |
| strscan                   | 1.0.3        |
| date                      | 3.0.0        |
| delegate                  | 0.1.0        |
| fileutils                 | 1.4.1        |
| io-console                | 0.5.6        |
| zlib                      | 1.1.0        |
| singleton                 | 0.1.0        |
| rexml                     | 3.2.3        |
| open3                     | 0.1.0        |
| yaml                      | 0.1.0        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.6.0        |
</details>

*generated on:* **2020-09-07**
</details>
</pre>
</details>

**Comment by dinhnhat0401** [comment]
@andrewhavens Could you please check this action?

**Comment by dinhnhat0401** [comment]
@vadimleonov I also had the same issue with the link.
But I realized that the internal app sharing APK is actually uploaded to the Google Play store successfully.
What I missed is add the tester email as an Internal Tester.
You can do it via Google Play Console.
This 404 error will be return if one of the bellow condition is correct:
- test device is not supported
- the account is not a tester account

Also remember to enable internal app sharing in your device Google Play.

**Comment by andysousa** [comment]
Were you able to resolve this?  I am seeing the exact same issue.  I created the service account, and it seems to upload my bundle correctly... but when i log into the console that release is nowhere to be found.  

Any advice?

**Comment by andrewhavens** [comment]
Pretty sure you aren't supposed to find the upload anywhere in the console. Internal app sharing just gives you a URL.

**Comment by andysousa** [comment]
Oh, i thought it would create a release on my internal testing in the play console... is that possibly a different action?

![image](https://user-images.githubusercontent.com/42151009/97239345-c2d81480-17c1-11eb-8d1b-2990143526fe.png)

**Comment by andysousa** [comment]
oops, i guess this was just the wrong action for what i was trying to do.  Accomplished what I wanted with
`upload_to_play_store(track: 'internal')`

**Comment by rogerluan** [comment]
> oops, i guess this was just the wrong action for what i was trying to do. Accomplished what I wanted with
> `upload_to_play_store(track: 'internal')`

@andysousa @vadimleonov does this solve your problem? 😊 Can we close this issue? :)

**Comment by andysousa** [comment]
No issues for me. Can't speak for the OP

**Comment by yaronlevi** [comment]
happens to me as well

**Comment by vadimleonov** [comment]
@rogerluan 
No, `upload_to_play_store(track: 'internal')` is different. @andysousa was trying to upload to the `Internal Testing`, but my  problem is about `Internal App Sharing`
![image](https://user-images.githubusercontent.com/35032429/101154140-ffebbe00-362d-11eb-862b-cf6425bb3846.png)

**Comment by vadimleonov** [comment]
@dinhnhat0401 Unfortunately it doesn't help me and I have no problems where I'm uploading the build manually. So there is no permissions problem
