### ISSUE TITLE
Fastlane Env outputs email, team id, developer id, app id. Cannot remove from github's closed issues

### ISSUE THREAD

**Issue by thejeff77** [fastlane/fastlane#17188]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Hey there! I've submitted bugs here before, but what I didn't know is that posting the results of "fastlane env" output my apple email address (which is hidden from github), my app identifier, my dev portal id, my team id and a bunch of other stuff that isn't relevant to the bugs I posted.

Now all this information is out there and searchable (and posted all together), including my email address....

After the bug is closed, there is no way to remove that information from the bug. It's searchable with google forever...

Can you guys find some way to help me remove this information?

Also please strongly consider updating fastlane env to not provide this information by default. There is no reason I can see to automatically include all of this information for every inclusion of fastlane env, especially without any sort of warning in the output or in the instructions for posting bugs or feature requests. 

example output here:

<details><summary>`./Appfile`</summary>
<div class="highlight highlight-source-ruby"><pre><span class="pl-en">app_identifier</span><span class="pl-kos">(</span><span class="pl-s">"com.someapp.SOMEAPP"</span><span class="pl-kos">)</span> <span class="pl-c"># The bundle identifier of your app</span>
<span class="pl-en">apple_id</span><span class="pl-kos">(</span><span class="pl-s">"companyemail@email.com"</span><span class="pl-kos">)</span> <span class="pl-c"># Your Apple email address</span>

<span class="pl-en">itc_team_id</span><span class="pl-kos">(</span><span class="pl-s">"109387265"</span><span class="pl-kos">)</span> <span class="pl-c"># App Store Connect Team ID</span>
<span class="pl-en">team_id</span><span class="pl-kos">(</span><span class="pl-s">"HEUSYNV53"</span><span class="pl-kos">)</span> <span class="pl-c"># Developer Portal Team ID</span>

##### Command executed
fastlane env

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

NO!

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by thejeff77** [comment]
Yep this is on purpose fastlane bot! The bug is a report about this sort of behavior...

**Comment by rogerluan** [comment]
Hey @thejeff77 👋 

I appreciate you taking time to post your concerns.

Regarding changing the default behavior of _fastlane_, sometimes this kind of information does help us debugging, for example when the reported issue is related to different teams and such. Plus, all of those info except the email are harmless to be exposed AFAICT, but I understand your concerns. 

We already hide actual sensitive information such as passwords and API tokens, but marking those identifiers and emails as sensitive would make using and debugging _fastlane_ a bit harder imo.

I advise you to review the `fastlane env` (and similar) command outputs before posting publicly anywhere on the internet, for better safety.

For now, please link me to the closed/past issues that are bothering you and I can see if I can clean those up for you.

**Comment by thejeff77** [comment]
keep it open fastlane bot

**Comment by rogerluan** [comment]
@thejeff77 please see my response above

**Comment by thejeff77** [comment]
@rogerluan thanks for the reply and information! Sorry I didn't reply before, I must have missed your initial reply somehow. I do appreciate your time in responding.

For me, I posted the outputs without knowing the impacts, this is more a request to someone on the team with more github permissions to help me clean sensitive env information from an old closed bug once-only. I'm more careful now. Could you or someone who can edit issues help with this? I'd be extremely grateful.

To give the potential benefit of a full reply, some more considerations (that apply to me here) may help give some good context and recommendations for future functionality:
- Often full build paths can contain a user's name or full name, which is included in the output
- Email is included which exposes Apple Id (as you mentioned already - is sensitive information)
- All output is aggregated into Google, Bing, etc popular search engines. 
- App Name / Bundle Identifier / User Name / Apple Id aggregated together can be used as potential attack vectors on apple services, used for phishing and attack campaigns on user's private appleId related emails, associating company information with usernames (which may be real names) and primary emails.
- Fastlane env provides no warnings about output containing sensitive information.
- Fastlane env provides no flags to exclude the username or AppleId email.
- Sensitive information posted via fastlane env cannot be removed or edited after an issue is closed, per my one time request for help here.

**Comment by rogerluan** [comment]
@thejeff77 I've responded to your email and cleaned up your data from GitHub 💪 Happy to help!

As to your points, I believe the most effective way to do this at a low engineering cost is to double down on warnings we give to users when we provide them the fastlane output. 
We currently have built-in ways to mark certain data as sensitive, but those are just hidden from console logs. So if you store that data in your Fastfile/Appfile and you provide those in the fastlane output without reviewing, it will be posted.
To clean up the output we'd have to use some sort of regex (for both Ruby and Swift languages), but those could break silently in the future, be just faulty in general (there're many ways you can write both Ruby and Swift code that may not be covered by all regexes), and is just painful to maintain. Hence why I suggest handing off this responsibility to each user individually.
Redacting path of files/directories is another task that can be daunting 😅 they can take pretty much any form, and often times it's quite helpful to be able to read the paths to debug issues. Plus, the username of your machine probably shouldn't be that much of an issue (even if it's e.g. `~/Users/NASA/TopSecretProjects/ProjectAlpha/` AFAICT it can be all fake 🤷 

I'm open to other suggestions on how we could automate this process, though.

**Comment by thejeff77** [comment]
Thanks @rogerluan I agree, additional warnings would be a good low-effort and reliable first (or only) action item here.

Ex: "WARNING: AppleId super-boss@nasa.com, TeamID: X123 are included in fastlane env output. Review output for sensitive data before posting."
