### ISSUE TITLE
Plugin works locally, but not on gitlab pipeline (plugins not loaded)

### ISSUE THREAD

**Issue by srockytfl** [fastlane/fastlane#17192]
Hi, I'm doing a simple Android pipeline with GitLab. I just add two simple plugins like get_version_code e increment_version_code and everything works well on my machine. But in the gitlab pipeline I have this error:
It seems like you wanted to load some plugins, however they couldn't be loaded
ERROR [2020-09-08 18:06:15.55]: Please follow the troubleshooting guide: https://docs.fastlane.tools/plugins/plugins-troubleshooting/

I've already read this troubleshooting guide many times and I also google the error but nothing.

Here is my fastlane env.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                     |
| --------------------------- | --------------------------------------------------------- |
| OS                          | 10.15.6                                                   |
| Ruby                        | 2.2.4                                                     |
| Bundler?                    | false                                                     |
| Git                         | git version 2.24.3 (Apple Git-128)                        |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane                       |
| Host                        | Mac OS X 10.15.6 (19G2021)                                |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                                |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                                |
| Is contained                | true                                                      |
| Is homebrew                 | false                                                     |
| Is installed via Fabric.app | false                                                     |
| Xcode Path                  | /Volumes/Dados/Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.5                                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

versionCode = get_version_code()

platform :android do

    desc "Temp"
    lane :temp do

      puts "versionCode: #{versionCode}"

      #increment_version_code()
    end

    desc "Builds the debug code"
    lane :buildDebug do
      gradle(task: "assembleDebug")
    end

    desc "Builds the release code"
    lane :buildRelease do
      gradle(task: "assembleRelease")
    end

    desc "Runs all the tests"
    lane :test do
      gradle(task: "test")
    end

    desc "Submit a new Internal Build to Play Store"
    lane :internal do
        puts "publish to internal: #{versionCode}"
        upload_to_play_store(
            track: 'internal',
            version_code: versionCode,
            apk: 'app/build/outputs/apk/release/app-release.apk')
    end

    desc "Promote Internal to Alpha"
    lane :promote_internal_to_alpha do
        puts "versionCode internal: #{versionCode}"
        #upload_to_play_store(track: 'internal', skip_upload_changelogs: true, track_promote_to: 'alpha')
    end

    desc "Promote Alpha to Beta"
    lane :promote_alpha_to_beta do
        upload_to_play_store(track: 'alpha', skip_upload_changelogs: true, track_promote_to: 'beta')
    end

    # `skip_upload_changelogs` from https://github.com/fastlane/fastlane/issues/15681#issuecomment-556617987
    desc "Promote Beta to Production"
    lane :promote_beta_to_production do
        upload_to_play_store(track: 'beta', skip_upload_changelogs: true,  track_promote_to: 'production')
    end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("Google/service-account-key.json") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("com.teste.helloandroidfastlane")
```
</details>

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.28.3  | 💥 Check failed |

### Loaded fastlane plugins:

| Plugin                                 | Version | Update-Status  |
| -------------------------------------- | ------- | -------------- |
| fastlane-plugin-get_version_code       | 0.2.0   | 💥 Check failed |
| fastlane-plugin-increment_version_code | 0.4.3   | 💥 Check failed |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| CFPropertyList                            | 2.3.5        |
| addressable                               | 2.5.1        |
| atomos                                    | 0.1.3        |
| babosa                                    | 1.0.3        |
| bigdecimal                                | 1.2.6        |
| bundler                                   | 1.14.6       |
| claide                                    | 1.0.3        |
| colored                                   | 1.2          |
| colored2                                  | 3.1.2        |
| commander-fastlane                        | 4.4.6        |
| domain_name                               | 0.5.20170404 |
| dotenv                                    | 2.2.0        |
| excon                                     | 0.76.0       |
| faraday                                   | 0.12.1       |
| faraday-cookie_jar                        | 0.0.6        |
| faraday_middleware                        | 0.11.0.1     |
| fastimage                                 | 2.1.0        |
| fastlane-plugin-firebase_app_distribution | 0.2.0        |
| fastlane-plugin-get_version_code          | 0.2.0        |
| fastlane-plugin-get_version_name          | 0.2.2        |
| fastlane-plugin-increment_version_code    | 0.4.3        |
| gh_inspector                              | 1.0.3        |
| google-api-client                         | 0.9.28       |
| googleauth                                | 0.5.1        |
| highline                                  | 1.7.8        |
| http-cookie                               | 1.0.3        |
| httpclient                                | 2.8.3        |
| hurley                                    | 0.2          |
| io-console                                | 0.4.3        |
| json                                      | 1.8.1        |
| jwt                                       | 1.5.6        |
| libxml-ruby                               | 3.0.0        |
| little-plugger                            | 1.1.4        |
| logging                                   | 2.2.2        |
| memoist                                   | 0.15.0       |
| mime-types                                | 3.1          |
| mime-types-data                           | 3.2016.0521  |
| mini_magick                               | 4.5.1        |
| minitest                                  | 5.4.3        |
| multi_json                                | 1.12.1       |
| multi_xml                                 | 0.6.0        |
| multipart-post                            | 2.0.0        |
| nanaimo                                   | 0.3.0        |
| nokogiri                                  | 1.5.6        |
| os                                        | 0.9.6        |
| plist                                     | 3.2.0        |
| power_assert                              | 0.2.2        |
| psych                                     | 2.0.8        |
| public_suffix                             | 2.0.5        |
| rake                                      | 10.4.2       |
| rdoc                                      | 4.2.0        |
| representable                             | 2.3.0        |
| retriable                                 | 2.1.0        |
| rouge                                     | 2.0.7        |
| rubygems-update                           | 2.5.2        |
| rubyzip                                   | 1.2.1        |
| security                                  | 0.1.3        |
| signet                                    | 0.7.3        |
| slack-notifier                            | 2.3.2        |
| slack-notifier                            | 1.5.1        |
| sqlite3                                   | 1.3.13       |
| terminal-notifier                         | 2.0.0        |
| terminal-notifier                         | 1.7.1        |
| terminal-table                            | 1.7.3        |
| test-unit                                 | 3.0.8        |
| tty-cursor                                | 0.7.1        |
| tty-screen                                | 0.8.1        |
| tty-screen                                | 0.5.0        |
| tty-spinner                               | 0.9.3        |
| uber                                      | 0.0.15       |
| unf                                       | 0.1.4        |
| unf_ext                                   | 0.0.7.4      |
| unicode-display_width                     | 1.1.3        |
| word_wrap                                 | 1.0.0        |
| xcodeproj                                 | 1.18.0       |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 0.0.4        |
</details>

*generated on:* **2020-09-08**
</details>

My Plugin file has this two lines:

gem 'fastlane-plugin-get_version_code'
gem 'fastlane-plugin-increment_version_code'

I also have GemFile and I always use "bundle exec" to call fastlane.

This simple lane works locally:

bundle exec fastlane temp

In my gitlab pipeline i do:

bundle update fastlane
bundle install
fastlane install_plugins --verbose
bundle exec fastlane internal --verbose

**Comment by FrancisLeigh** [comment]
Getting this to, would be great to get some more visibility on what is causing this issue!

**Comment by rogerluan** [comment]
Hey @srockytfl 👋 

Francis and I discussed some solution [here](https://github.com/fastlane/fastlane/issues/17376#issuecomment-704339770), could you check it out to see if that's what's happening in your case as well? 😃
