### ISSUE TITLE
Not Found error during login or latest_testflight_build_number

### ISSUE THREAD

**Issue by lewchuk-span** [fastlane/fastlane#17219]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I am using a lane that has the step `latest_testflight_build_number` included. Between earlier today (September 10, 2020 8:25:12 AM GMT-07:00) and now (Thursday, September 10, 2020 4:56:12 PM GMT-07:00) this step has started erroring with a `Page not found error`.

I've tried with:
- 2.152.0 and 2.152.9
- locally and on my CI system
- with two different iOS users

In all cases I get the same error.

##### Command executed
```
desc 'Build the IOS application to app store'
  private_lane :build_release do
    certificates
    clean_project
    increment_build_number(build_number: latest_testflight_build_number + 1)
    gym
  end

  desc 'Upload to app store'
  lane :release do
    build_release
    version = latest_testflight_build_number + 1
    submitted = false
    if ENV["DELIVER_SUBMIT_FOR_REVIEW"]
      submitted = ENV["DELIVER_SUBMIT_FOR_REVIEW"]
    end
    upload_to_app_store
    notify_slack(...)
  end
```

Command: `bundle exec fastlane ios release --env release`

##### Complete output when running fastlane, including the stack trace and command used
<details>
<pre>
[✔] 🚀 
[16:51:32]: Loading from './fastlane/.env.release'
[16:51:35]: ------------------------------
[16:51:35]: --- Step: default_platform ---
[16:51:35]: ------------------------------
[16:51:35]: Driving the lane 'ios release' 🚀
[16:51:35]: -----------------------------
[16:51:35]: --- Step: setup_circle_ci ---
[16:51:35]: -----------------------------
[16:51:35]: Not running on CI, skipping CI setup
[16:51:35]: ----------------------------------------------
[16:51:35]: --- Step: Switch to ios build_release lane ---
[16:51:35]: ----------------------------------------------
[16:51:35]: Cruising over to lane 'ios build_release' 🚖
[16:51:35]: ---------------------------------------------
[16:51:35]: --- Step: Switch to ios certificates lane ---
[16:51:35]: ---------------------------------------------
[16:51:35]: Cruising over to lane 'ios certificates' 🚖
[16:51:35]: -------------------
[16:51:35]: --- Step: match ---
[16:51:35]: -------------------

+--------------------------------+------------------------------------------+
|                         Summary for match 2.159.0                         |
+--------------------------------+------------------------------------------+
| type                           | appstore                                 |
| readonly                       | true                                     |
| generate_apple_certs           | true                                     |
| skip_provisioning_profiles     | false                                    |
| app_identifier                 | ****
| username                       | ****
| team_id                        | ****
| storage_mode                   | ****
| git_branch                     | master                                   |
| shallow_clone                  | false                                    |
| clone_branch_directly          | false                                    |
| force                          | false                                    |
| force_for_new_devices          | false                                    |
| skip_confirmation              | false                                    |
| skip_docs                      | false                                    |
| platform                       | ios                                      |
| derive_catalyst_app_identifier | false                                    |
| fail_on_name_taken             | false                                    |
| verbose                        | false                                    |
+--------------------------------+------------------------------------------+

[16:51:37]: 🔓  Successfully decrypted certificates repo
[16:51:37]: Installing certificate...

+-------------------+-----------------------------------------------+
|                       Installed Certificate                       |
+-------------------+-----------------------------------------------+
****
| Start Datetime    | 2020-06-05 10:05:49 UTC                       |
| End Datetime      | 2021-06-05 10:05:49 UTC                       |
+-------------------+-----------------------------------------------+

[16:51:37]: Installing provisioning profile...

+---------------------+-----------------------------------------------+-----------------------------------------------+
|                                           Installed Provisioning Profile                                            |
+---------------------+-----------------------------------------------+-----------------------------------------------+
| Parameter           | Environment Variable                          | Value                                         |
+---------------------+-----------------------------------------------+-----------------------------------------------+
****
| Type                |                                               | appstore                                      |
| Platform            |                                               | ios                                           |
****
+---------------------+-----------------------------------------------+-----------------------------------------------+

[16:51:38]: All required keys, certificates and provisioning profiles are installed 🙌
[16:51:38]: Setting Provisioning Profile type to 'app-store'
[16:51:38]: Cruising back to lane 'ios build_release' 🚘
[16:51:38]: ----------------------------------------------
[16:51:38]: --- Step: Switch to ios clean_project lane ---
[16:51:38]: ----------------------------------------------
[16:51:38]: Cruising over to lane 'ios clean_project' 🚖
[16:51:38]: --------------------------------
[16:51:38]: --- Step: clear_derived_data ---
[16:51:38]: --------------------------------
[16:51:38]: Derived Data path located at: /Users/stephen/Library/Developer/Xcode/DerivedData
[16:51:38]: Successfully cleared Derived Data ♻️
[16:51:38]: -----------------------
[16:51:38]: --- Step: cocoapods ---
[16:51:38]: -----------------------
[16:51:38]: $ bundle exec pod install
[16:51:43]: ▸ Detected React Native module pods for ****
[16:51:43]: ▸ Analyzing dependencies
[16:51:49]: ▸ Downloading dependencies
[16:51:49]: ▸ Generating Pods project
[16:51:49]: ▸ Integrating client project
[16:51:49]: ▸ Pod installation complete! There are 40 dependencies from the Podfile and 51 total pods installed.
[16:51:49]: ▸ - Use the `$(inherited)` flag, or
[16:51:49]: ▸ - Remove the build settings from the target.
[16:51:50]: Cruising back to lane 'ios build_release' 🚘
[16:51:50]: --------------------------------------------
[16:51:50]: --- Step: latest_testflight_build_number ---
[16:51:50]: --------------------------------------------
[16:51:50]: Login to App Store Connect (****)
[16:51:51]: ---------------------------------------------
[16:51:51]: --- Step: Switch to ios notify_error lane ---
[16:51:51]: ---------------------------------------------
[16:51:51]: Cruising over to lane 'ios notify_error' 🚖
[16:51:51]: -------------------
[16:51:51]: --- Step: slack ---
[16:51:51]: -------------------
[16:51:51]: Successfully sent Slack notification
[16:51:51]: -------------------
[16:51:51]: --- Step: slack ---
[16:51:51]: -------------------
[16:51:51]: Successfully sent Slack notification
[16:51:51]: Cruising back to lane 'ios build_release' 🚘
+------------------------------------+-------------------------------------------------------------------+
|                                              Lane Context                                              |
+------------------------------------+-------------------------------------------------------------------+
| ENVIRONMENT                        | release                                                           |
| DEFAULT_PLATFORM                   | ios                                                               |
| PLATFORM_NAME                      | ios                                                               |
| LANE_NAME                          | ios release                                                       |
| SIGH_PROFILE_TYPE                  | app-store                                                         |
+------------------------------------+-------------------------------------------------------------------+
[16:51:51]: 
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        body {
            font-family: "Helvetica Neue", "HelveticaNeue", Helvetica, Arial, sans-serif;
            font-size: 15px;
            font-weight: 200;
            line-height: 20px;
            color: #4c4c4c;
            text-align: center;
        }

        .section {
            margin-top: 50px;
        }
    </style>
</head>
<body>
<div class="section">
    <h1>&#63743;</h1>

    <h3>Not Found</h3>
    <p>The requested page could not be found.</p>
</div>
</body>
</html>

+------+----------------------------------+-------------+
|                   fastlane summary                    |
+------+----------------------------------+-------------+
| Step | Action                           | Time (in s) |
+------+----------------------------------+-------------+
| 1    | default_platform                 | 0           |
| 2    | setup_circle_ci                  | 0           |
| 3    | Switch to ios build_release lane | 0           |
| 4    | Switch to ios certificates lane  | 0           |
| 5    | match                            | 2           |
| 6    | Switch to ios clean_project lane | 0           |
| 7    | clear_derived_data               | 0           |
| 8    | cocoapods                        | 11          |
| 💥   | latest_testflight_build_number   | 1           |
| 10   | Switch to ios notify_error lane  | 0           |
| 11   | slack                            | 0           |
| 12   | slack                            | 0           |
+------+----------------------------------+-------------+

[16:51:51]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

bundler: failed to load command: fastlane (/Users/stephen/.gem/bin/fastlane)
Spaceship::UnexpectedResponse: [!] 
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        body {
            font-family: "Helvetica Neue", "HelveticaNeue", Helvetica, Arial, sans-serif;
            font-size: 15px;
            font-weight: 200;
            line-height: 20px;
            color: #4c4c4c;
            text-align: center;
        }

        .section {
            margin-top: 50px;
        }
    </style>
</head>
<body>
<div class="section">
    <h1>&#63743;</h1>

    <h3>Not Found</h3>
    <p>The requested page could not be found.</p>
</div>
</body>
</html>

  /Users/stephen/.gem/gems/fastlane-2.159.0/spaceship/lib/spaceship/client.rb:719:in `parse_response'
  /Users/stephen/.gem/gems/fastlane-2.159.0/spaceship/lib/spaceship/client.rb:126:in `user_details_data'
  /Users/stephen/.gem/gems/fastlane-2.159.0/spaceship/lib/spaceship/client.rb:71:in `teams'
  /Users/stephen/.gem/gems/fastlane-2.159.0/spaceship/lib/spaceship/tunes/tunes_client.rb:78:in `select_team'
  /Users/stephen/.gem/gems/fastlane-2.159.0/spaceship/lib/spaceship/connect_api/client.rb:66:in `login'
  /Users/stephen/.gem/gems/fastlane-2.159.0/spaceship/lib/spaceship/connect_api/spaceship.rb:82:in `login'
  /Users/stephen/.gem/gems/fastlane-2.159.0/fastlane/lib/fastlane/actions/app_store_build_number.rb:31:in `get_build_number'
  /Users/stephen/.gem/gems/fastlane-2.159.0/fastlane/lib/fastlane/actions/app_store_build_number.rb:14:in `run'
  /Users/stephen/.gem/gems/fastlane-2.159.0/fastlane/lib/fastlane/actions/latest_testflight_build_number.rb:12:in `run'
  /Users/stephen/.gem/gems/fastlane-2.159.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  /Users/stephen/.gem/gems/fastlane-2.159.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/stephen/.gem/gems/fastlane-2.159.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  /Users/stephen/.gem/gems/fastlane-2.159.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  /Users/stephen/.gem/gems/fastlane-2.159.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  /Users/stephen/.gem/gems/fastlane-2.159.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/stephen/.gem/gems/fastlane-2.159.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:101:in `block (2 levels) in parsing_binding'
  /Users/stephen/.gem/gems/fastlane-2.159.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/stephen/.gem/gems/fastlane-2.159.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
  /Users/stephen/.gem/gems/fastlane-2.159.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
  /Users/stephen/.gem/gems/fastlane-2.159.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:120:in `block (2 levels) in parsing_binding'
  /Users/stephen/.gem/gems/fastlane-2.159.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/stephen/.gem/gems/fastlane-2.159.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/stephen/.gem/gems/fastlane-2.159.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/stephen/.gem/gems/fastlane-2.159.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/stephen/.gem/gems/fastlane-2.159.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /Users/stephen/.gem/gems/fastlane-2.159.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/stephen/.gem/gems/fastlane-2.159.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/stephen/.gem/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/stephen/.gem/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/stephen/.gem/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/stephen/.gem/gems/fastlane-2.159.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/stephen/.gem/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/stephen/.gem/gems/fastlane-2.159.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  /Users/stephen/.gem/gems/fastlane-2.159.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/stephen/.gem/gems/fastlane-2.159.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Users/stephen/.gem/gems/fastlane-2.159.0/bin/fastlane:23:in `<top (required)>'
  /Users/stephen/.gem/bin/fastlane:23:in `load'
  /Users/stephen/.gem/bin/fastlane:23:in `<top (required)>'
</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.5                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.25.0                                             |
| Installation Source         | ~/.gem/bin/fastlane                                            |
| Host                        | Mac OS X 10.15.5 (19F101)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.7                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

default_platform(:ios)

private_lane :notify_error do |options|
  slack(
    message: "Fastlane failed distributing the App",
    success: false,
    ...
  )
end

error do |lane, exception|
  notify_error(error: exception.to_s)
end

private_lane :notify_slack do |options|
  messagePayload = {}
  if options[:payload]
    messagePayload = messagePayload.merge(options[:payload])
  end

  slack(
    message: options[:message],
    success: true,
    ...
  )
end

platform :ios do

  before_all do
    setup_circle_ci
  end

  desc 'Fetch certificates and provisioning profiles'
  private_lane :certificates do
    match
  end

  desc 'Clean project'
  private_lane :clean_project do
    clear_derived_data
    cocoapods
  end

  desc 'Build the IOS application to app store'
  private_lane :build_release do
    certificates
    clean_project
    increment_build_number(build_number: latest_testflight_build_number + 1)
    gym
  end

  desc 'Upload to app store'
  lane :release do
    build_release
    version = latest_testflight_build_number + 1
    upload_to_app_store
    notify_slack(...)
  end

  desc 'Update metadata'
  lane :update_metadata do
    upload_to_app_store(
      submit_for_review: false,
      overwrite_screenshots: true,
      skip_binary_upload: true,
    )
  end



end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.159.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 1.17.2       |
| etc                       | 1.0.1        |
| forwardable               | 1.2.0        |
| rake                      | 13.0.1       |
| CFPropertyList            | 3.0.2        |
| concurrent-ruby           | 1.1.6        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.6        |
| activesupport             | 4.2.11.1     |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| httpclient                | 2.8.3        |
| json                      | 2.3.1        |
| algoliasearch             | 1.27.1       |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.367.0      |
| aws-sigv4                 | 1.2.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.105.0      |
| aws-sdk-kms               | 1.37.0       |
| aws-sdk-s3                | 1.80.0       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| netrc                     | 0.11.0       |
| ffi                       | 1.12.2       |
| ethon                     | 0.12.0       |
| typhoeus                  | 1.3.1        |
| cocoapods-core            | 1.9.1        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.3.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| cocoapods-trunk           | 1.4.1        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.18.0       |
| cocoapods                 | 1.9.1        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.0.0        |
| excon                     | 0.76.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 1.0.1        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| jwt                       | 2.2.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| signet                    | 0.14.0       |
| googleauth                | 0.13.1       |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.28.0       |
| mini_magick               | 4.10.1       |
| plist                     | 3.5.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2020-09-10**
</details>

**Comment by lewchuk-span** [comment]
Seems like this may have been resolved on Apple's side? A build this morning with 159 succeeded at `Friday, September 11, 2020 8:00:18 AM GMT-07:00`. If others are also no longer hitting the issue we can probably close it. Is there a status page/issue tracker for the app store connect apis?

**Comment by sanpoChew** [comment]
all green according to this https://developer.apple.com/system-status/

I'm getting 500 errors from latest_testflight_build_number which I assume is the same issue

**Comment by lewchuk-span** [comment]
@sanpoChew I've confirmed for both my CI and my local setup that I no longer have this issue. My output doesn't have any status code in it, but it looked like a pretty standard `<h3>Not Found</h3>` page so I'd have expected it would be a 404 not 500.

**Comment by sanpoChew** [comment]
ah might have been a separate issue then, not getting 500's anymore though

**Comment by lewchuk-span** [comment]
One one else has chimed in that this is still an issue so I'm going to close.
