### ISSUE TITLE
Failed to open TCP connection to appstoreconnect.apple.com:443

### ISSUE THREAD

**Issue by abraaolevi** [fastlane/fastlane#17224]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

After updated fastlane to the latest version, the following error started to happen: `Failed to open TCP connection to appstoreconnect.apple.com:443 (getaddrinfo: nodename nor servname provided, or not known)`. At first, I thought it was a connectivity issue with Apple's API, but I can access the _appstoreconnect_ normally. Is it just a temporary connection problem or is it can be a bug?

##### Command executed

```shell
$ bundle exec fastlane myTest --env envfile
```

```ruby
# Fastfile lane
lane :myTest do
    Spaceship::ConnectAPI.login(ENV['username'])
    Spaceship::ConnectAPI.select_team

    app = Spaceship::ConnectAPI::App.find(ENV['bundle_id'])
end
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
[✔] 🚀
[17:06:53]: Loading from './.env.envfile'
[17:06:55]: ----------------------------------------
[17:06:55]: --- Step: Verifying fastlane version ---
[17:06:55]: ----------------------------------------
[17:06:55]: Your fastlane version 2.159.0 matches the minimum requirement of 2.100.0  ✅
[17:06:57]: ------------------------------
[17:06:57]: --- Step: default_platform ---
[17:06:57]: ------------------------------
[17:06:57]: Driving the lane 'ios myTest' 🚀
[17:06:57]: --------------------------------
[17:06:57]: --- Step: get_version_number ---
[17:06:57]: --------------------------------
[17:06:57]: Available session is not valid any more. Continuing with normal login.
+------------------+------------+
|         Lane Context          |
+------------------+------------+
| ENVIRONMENT      | envfile    |
| DEFAULT_PLATFORM | ios        |
| PLATFORM_NAME    | ios        |
| LANE_NAME        | ios myTest |
| VERSION_NUMBER   | 2.8.100    |
+------------------+------------+
[17:07:23]: Failed to open TCP connection to appstoreconnect.apple.com:443 (getaddrinfo: nodename nor servname provided, or not known)

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 3    | get_version_number         | 0           |
+------+----------------------------+-------------+

[17:07:23]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
bundler: failed to load command: fastlane (/Users/mini/fastlane_vendor/bundle/ruby/2.6.0/bin/fastlane)
Faraday::ConnectionFailed: [!] Failed to open TCP connection to appstoreconnect.apple.com:443 (getaddrinfo: nodename nor servname provided, or not known)
  /Users/mini/.rbenv/versions/2.6.6/lib/ruby/2.6.0/net/http.rb:949:in `rescue in block in connect'
  /Users/mini/.rbenv/versions/2.6.6/lib/ruby/2.6.0/net/http.rb:946:in `block in connect'
  /Users/mini/.rbenv/versions/2.6.6/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
  /Users/mini/.rbenv/versions/2.6.6/lib/ruby/2.6.0/timeout.rb:103:in `timeout'
  /Users/mini/.rbenv/versions/2.6.6/lib/ruby/2.6.0/net/http.rb:945:in `connect'
  /Users/mini/.rbenv/versions/2.6.6/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
  /Users/mini/.rbenv/versions/2.6.6/lib/ruby/2.6.0/net/http.rb:919:in `start'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:144:in `request_via_get_method'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:135:in `request_with_wrapped_block'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:128:in `perform_request'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:70:in `block in call'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/adapter.rb:60:in `connection'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:68:in `call'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/fastlane-2.159.0/spaceship/lib/spaceship/stats_middleware.rb:45:in `call'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/fastlane-2.159.0/spaceship/lib/spaceship/helper/rels_middleware.rb:17:in `call'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/faraday-cookie_jar-0.0.7/lib/faraday/cookie_jar.rb:24:in `call'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/faraday_middleware-1.0.0/lib/faraday_middleware/response_middleware.rb:36:in `call'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/faraday_middleware-1.0.0/lib/faraday_middleware/response_middleware.rb:36:in `call'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/rack_builder.rb:153:in `build_response'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/connection.rb:492:in `run_request'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/connection.rb:198:in `get'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/fastlane-2.159.0/spaceship/lib/spaceship/client.rb:855:in `block in send_request'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/fastlane-2.159.0/spaceship/lib/spaceship/client.rb:629:in `with_retry'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/fastlane-2.159.0/spaceship/lib/spaceship/client.rb:854:in `send_request'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/fastlane-2.159.0/spaceship/lib/spaceship/client.rb:698:in `request'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/fastlane-2.159.0/spaceship/lib/spaceship/client.rb:522:in `fetch_olympus_session'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/fastlane-2.159.0/spaceship/lib/spaceship/client.rb:494:in `send_shared_login_request'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/fastlane-2.159.0/spaceship/lib/spaceship/portal/portal_client.rb:28:in `send_login_request'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/fastlane-2.159.0/spaceship/lib/spaceship/client.rb:780:in `do_login'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/fastlane-2.159.0/spaceship/lib/spaceship/client.rb:388:in `login'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/fastlane-2.159.0/spaceship/lib/spaceship/client.rb:350:in `login'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/fastlane-2.159.0/spaceship/lib/spaceship/portal/spaceship.rb:25:in `login'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/fastlane-2.159.0/spaceship/lib/spaceship/connect_api/client.rb:52:in `login'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/fastlane-2.159.0/spaceship/lib/spaceship/connect_api/spaceship.rb:82:in `login'
  Fastfile:108:in `block (2 levels) in parsing_binding'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/fastlane-2.159.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/gems/fastlane-2.159.0/bin/fastlane:23:in `<top (required)>'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `load'
  /Users/mini/fastlane_vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `<top (required)>'
 </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.15.4                                          |
| Ruby                        | 2.6.6                                            |
| Bundler?                    | true                                             |
| Git                         | git version 2.24.2 (Apple Git-127)               |
| Installation Source         | ~/fastlane_vendor/bundle/ruby/2.6.0/bin/fastlane |
| Host                        | Mac OS X 10.15.4 (19E287)                        |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.6/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/      |
| Xcode Version               | 11.4.1                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
fastlane_version '2.100.0'
fastlane_require 'spaceship'
fastlane_require 'credentials_manager'
fastlane_require 'pp'

default_platform :ios

platform :ios do

    lane :myTest do
        Spaceship::ConnectAPI.login(ENV['username'])
        Spaceship::ConnectAPI.select_team

        app = Spaceship::ConnectAPI::App.find(ENV['bundle_id'])
    end

end
```
</details>

<details><summary>`./Appfile`</summary>

```ruby
app_identifier ENV['bundle_id'] # The bundle identifier of your app
apple_id ENV["username"] # Your Apple email address

team_id ENV["team_id"]  # Developer Portal Team ID
itc_team_id ENV["itc_team_name"]
# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.159.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 2.1.4        |
| rake                      | 13.0.1       |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.367.0      |
| aws-sigv4                 | 1.2.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.105.0      |
| aws-sdk-kms               | 1.37.0       |
| aws-sdk-s3                | 1.80.0       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| coderay                   | 1.1.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.0.0        |
| excon                     | 0.76.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 1.0.1        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.2.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| signet                    | 0.14.0       |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.28.0       |
| json                      | 2.3.1        |
| mini_magick               | 4.10.1       |
| plist                     | 3.5.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.18.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| fileutils                 | 1.4.1        |
| htmlentities              | 4.3.4        |
| mime-types-data           | 3.2020.0512  |
| mime-types                | 3.3.1        |
| multi_xml                 | 0.6.0        |
| httparty                  | 0.18.1       |
| method_source             | 1.0.0        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.9       |
| pry                       | 0.13.1       |
</details>

**Comment by max-ott** [comment]
Did you try this on different machines / networks?

**Comment by abraaolevi** [comment]
@max-ott in fact, the problem was in my network's DNS.

When I ran `ping appstoreconnect.apple.com`, the output was `ping: cannot resolve appstoreconnect.apple.com: Unknown host`. 

So I updated the public DNS server from my machine and it works now. 🎉
