### ISSUE TITLE
Fastlane.swift crashes after first installation

### ISSUE THREAD

**Issue by jmbrocal** [fastlane/fastlane#17222]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Hi folks!

It is my first time using Fastlane.swift. I followed the [getting stared guide](https://docs.fastlane.tools/getting-started/ios/fastlane-swift/), selecting the "manual setup" option.

When the installation process ended, I run `fastlane custom` to test the recently installation but it is crashing.

##### Command executed

fastlane custom

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
[✔] 🚀 
[17:44:15]: loading manifest: /Library/Ruby/Gems/2.6.0/gems/fastlane-2.159.0/fastlane/swift/upgrade_manifest.json
[17:44:15]: FastlaneSwiftRunner project is up-to-date
[17:44:15]: $ ./fastlane/FastlaneRunner lane custom swiftServerPort 2000 > /dev/null
[17:44:15]: ▸ Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /Users/jmbrocal/Workspace/iOS/mistica-ios/fastlane/swift/LaneFileProtocol.swift, line 121
#<Thread:0x00007f8427d878d8@/Library/Ruby/Gems/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/swift_lane_manager.rb:220 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/swift_lane_manager.rb:223:in `block in start_socket_thread'
	8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/server/socket_server.rb:38:in `start'
	7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/server/socket_server.rb:158:in `listen'
	6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/server/socket_server.rb:49:in `receive_and_process_commands'
	5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/server/socket_server.rb:49:in `loop'
	4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/server/socket_server.rb:62:in `block in receive_and_process_commands'
	3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/server/socket_server.rb:81:in `parse_and_execute_command'
	2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/server/command_parser.rb:12:in `parse'
	1: from /Library/Ruby/Gems/2.6.0/gems/json-2.3.1/lib/json/common.rb:263:in `parse'
/Library/Ruby/Gems/2.6.0/gems/json-2.3.1/lib/json/common.rb:263:in `parse': 784: unexpected token at '' (JSON::ParserError)
[17:44:15]: ▸ sh: line 1: 32158 Illegal instruction: 4  ./fastlane/FastlaneRunner lane custom swiftServerPort 2000 > /dev/null
#<Thread:0x00007f84233f5008@/Library/Ruby/Gems/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/swift_lane_manager.rb:96 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/swift_lane_manager.rb:97:in `block in cruise_swift_lane_in_thread'
	3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
	2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.159.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.159.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': Exit status of command './fastlane/FastlaneRunner lane custom swiftServerPort 2000 > /dev/null' was 132 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /Users/jmbrocal/Workspace/iOS/mistica-ios/fastlane/swift/LaneFileProtocol.swift, line 121
sh: line 1: 32158 Illegal instruction: 4  ./fastlane/FastlaneRunner lane custom swiftServerPort 2000 > /dev/null
+-----------+--------+
|    Lane Context    |
+-----------+--------+
| LANE_NAME | custom |
+-----------+--------+
[17:44:15]: 784: unexpected token at ''
[17:44:15]: fastlane finished with errors
 </pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.6                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.6 (19G73)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.7                                                           |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

```ruby
// This file contains the fastlane.tools configuration
// You can find the documentation at https://docs.fastlane.tools
//
// For a list of all available actions, check out
//
//     https://docs.fastlane.tools/actions
//

import Foundation

class Fastfile: LaneFile {
	func customLane() {
	desc("Description of what the lane does")
		// add actions here: https://docs.fastlane.tools/actions
	}
}

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.159.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 2.1.0        |
| rake                      | 13.0.1       |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.367.0      |
| aws-sigv4                 | 1.2.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.105.0      |
| aws-sdk-kms               | 1.37.0       |
| aws-sdk-s3                | 1.80.0       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.0.0        |
| excon                     | 0.76.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 1.0.1        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.2.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| signet                    | 0.14.0       |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.28.0       |
| json                      | 2.3.1        |
| mini_magick               | 4.10.1       |
| plist                     | 3.5.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.18.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2020-09-11**
</details>

**Comment by rogerluan** [comment]
@jmbrocal I opened a PR to fix this issue, it will probably be in this week's release 🙏 thanks for your report!
