### ISSUE TITLE
export_options causing mismatch on export_method 

### ISSUE THREAD

**Issue by jenskuhrjorgensen** [fastlane/fastlane#17231]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
`build_ios_app` fails when I use `export_options` but succeeds when I use `export_method`. 

I've create a vanilla React Native project with Fastlane 2.159.0 and when I build with the following configuration it succeeds:

```
  lane :custom_lane do
    build_ios_app(
          workspace: "AwesomeTSProject.xcworkspace",
          scheme: "AwesomeTSProject",
          configuration: "Release",
          export_method: "app-store",
    )
  end
```

But when I move `export_method` inside `export_options` (where I another project have bundled all the export configurations) it fails:

```
  lane :custom_lane do
    build_ios_app(
          workspace: "AwesomeTSProject.xcworkspace",
          scheme: "AwesomeTSProject",
          configuration: "Release",
          export_options: {
            method: "app-store",
          }
    )
  end
```
Even though the [documentation](https://docs.fastlane.tools/actions/build_ios_app/#parameters) says you can do it both ways. 

##### Command executed
`fastlane custom_lane`

##### Complete output when running fastlane, including the stack trace and command used
This is the summary for gym upon executing `fastlane custom_lane` which kind of indicates that it picks up on the `export_options.method`:

```
+------------------------------------------------------------------+---------------------------------------------------------+
|                                                  Summary for gym 2.158.0                                                   |
+------------------------------------------------------------------+---------------------------------------------------------+
| workspace                                                        | AwesomeTSProject.xcworkspace                            |
| scheme                                                           | AwesomeTSProject                                        |
| configuration                                                    | Release                                                 |
| export_options.method                                            | app-store                                               |
| export_options.provisioningProfiles.XXX | YYY                                 |
| catalyst_platform                                                | ios                                                     |
| destination                                                      | generic/platform=iOS                                    |
| output_name                                                      | AwesomeTSProject                                        |
| build_path                                                       | /Users/ZZZ/Library/Developer/Xcode/Archives/2020-09-14 |
| clean                                                            | false                                                   |
| output_directory                                                 | .                                                       |
| silent                                                           | false                                                   |
| skip_package_ipa                                                 | false                                                   |
| result_bundle                                                    | false                                                   |
| buildlog_path                                                    | ~/Library/Logs/gym                                      |
| skip_profile_detection                                           | false                                                   |
| skip_package_pkg                                                 | false                                                   |
| xcode_path                                                       | /Applications/Xcode.app                                 |
+------------------------------------------------------------------+---------------------------------------------------------+
```
But the lane fails with the following, where `export_method` seems to be empty:
```
[09:49:16]: There seems to be a mismatch between your provided `export_method` in gym
[09:49:16]: and the selected provisioning profiles. You passed the following options:
[09:49:16]:   export_method:
[09:49:16]:   Bundle identifier:  XXX
[09:49:16]:   Profile name:       YYY
[09:49:16]:   Profile type:       app-store
[09:49:16]: Make sure to either change the `export_method` passed from your Fastfile or CLI
[09:49:16]: or select the correct provisioning profiles by updating your Xcode project
[09:49:16]: or passing the profiles to use by using match or manually via the `export_options` hash
```

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 10.15.6                                                 |
| Ruby                        | 2.7.1                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.21.0 (Apple Git-122.2)                    |
| Installation Source         | /usr/local/Cellar/fastlane/2.159.0/libexec/bin/fastlane |
| Host                        | Mac OS X 10.15.6 (19G2021)                              |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.7.1_2/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1f  31 Mar 2020                             |
| Is contained                | false                                                   |
| Is homebrew                 | false                                                   |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 11.3                                                    |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
    build_ios_app(
          workspace: "AwesomeTSProject.xcworkspace",
          scheme: "AwesomeTSProject",
          configuration: "Release",
          #export_method: "app-store",
          export_options: {
            method: "app-store",
          }
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.159.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.18.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.76.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.2        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-storage      | 1.28.0       |
| emoji_regex               | 3.0.0        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.367.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.105.0      |
| aws-sdk-kms               | 1.37.0       |
| aws-sdk-s3                | 1.80.0       |
| uri                       | 0.10.0       |
| forwardable               | 1.3.1        |
| logger                    | 1.4.2        |
| cgi                       | 0.1.0        |
| timeout                   | 0.1.0        |
| stringio                  | 0.1.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.2.0        |
| strscan                   | 1.0.3        |
| date                      | 3.0.0        |
| delegate                  | 0.1.0        |
| fileutils                 | 1.4.1        |
| io-console                | 0.5.6        |
| zlib                      | 1.1.0        |
| singleton                 | 0.1.0        |
| rexml                     | 3.2.3        |
| open3                     | 0.1.0        |
| yaml                      | 0.1.0        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.6.0        |
</details>

*generated on:* **2020-09-14**
</details>

**Comment by jenskuhrjorgensen** [comment]
No bot!

**Comment by kyo504** [comment]
I've also faced with this issue. I thought it was quite weird because I thought those two values have the same effect.

**Comment by rogerluan** [comment]
Hey @jenskuhrjorgensen @kyo504  👋 

I spotted a bug where _fastlane_ is printing the empty export_method. However, that line is only printed once `gym` (aka `build_ios_app`) errors out. So the root cause of the error is the actual problem (however I'll still open a PR to fix the printing error 😊 )

I need more information about the provisioning profiles you guys are using to reproduce this issue, as I couldn't reproduce it myself. What kind of prov profile are you guys using, and how? e.g. providing inside `export_options`, via `match`, `automatic signing`, etc

**Comment by jenskuhrjorgensen** [comment]
Hi @rogerluan 

Sorry for the late answer. 

I'm not sure what information you need, but I'll try to provide some, and then please let me know if you need anything else.

I'm using a provisioning profile with the following properties:
```
Platform: iOS
Type: Universal Distribution
Enabled Capabilities: Game Center, In-App Purchase
```

I'm using it inside export_options:
```
  build_ios_app(
    workspace: "UILibExample.xcworkspace",
    scheme: "UILibExample",
    configuration: "Release",
    output_name: "UILibExample",
    output_directory: "#{ENV["PWD"]}/",
    build_path: "#{ENV["PWD"]}/",
    buildlog_path: "#{ENV['PWD']}/raw_xcode_logs",
    xcconfig: "fastlane/xcconfigs/release.xcconfig",
    export_options: {
      method: "enterprise",
      provisioningProfiles: {
        "com.xxx.yyy" => "UILib",
      }
    }
  )
```

And with `release.xcconfig`:
```
PRODUCT_BUNDLE_IDENTIFIER = com.xxx.yyy
PROVISIONING_PROFILE_SPECIFIER = UILib
CODE_SIGN_IDENTITY = iPhone Distribution: ZZZ A/S
DEVELOPMENT_TEAM = xxxxx
```
