### ISSUE TITLE
APP_STORE_CONNECT_API_KEY should redact key from logs

### ISSUE THREAD

**Issue by chrisballinger** [fastlane/fastlane#17239]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When using `pilot` with the new App Store Connect API, when you manually specify the API key like this:

```ruby
  api_key = app_store_connect_api_key(
    key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
    issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
    key_content: ENV["APP_STORE_CONNECT_KEY_CONTENT"]
  )
   pilot(
      api_key: api_key,
      distribute_external: false,
      skip_waiting_for_build_processing: true,
   )
```

It will print the `key` contents in plaintext in the logs for `pilot` under the key `APP_STORE_CONNECT_API_KEY`. It properly redacts `key_id`, and `issuer_id`.

I cannot attach any further environment information, but this affects fastlane 2.158.0.

**Comment by rogerluan** [comment]
I opened a PR for this @chrisballinger, could you help test it? 🙏 

https://github.com/fastlane/fastlane/pull/17256

Testing instructions in the PR 👍

**Comment by joshdholtz** [comment]
@chrisballinger Heyyyyy 👋 Long time no talk and hope all is well ❤️ Thanks for catching this!

@rogerluan And thanks for opening the PR! I'll also test and make sure this also gets out quick!
