### ISSUE TITLE
Spaceship: Analytics Gathering Script Stopped To Work

### ISSUE THREAD

**Issue by muccy** [fastlane/fastlane#17232]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Hi folks,
the script I wrote to gather data from iTC stopped to work a bunch of days ago. Updating to new versions of fastlane (2.159.0) didn't help.

I tried with a couple of different apps on different accounts but I get the same error:

```
{"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Not Found"], "info"=>nil}, "statusCode"=>"ERROR"}
```

##### Command executed

```ruby
platform :ios do
    desc "Get stats"
      lane :stats do | args |
        Spaceship::Tunes.login("<redacted>", "<redacted>")
        ENV['FASTLANE_ITC_TEAM_ID'] = '<redacted>'
        Spaceship::Tunes.select_team
        all_apps = Spaceship::Tunes::Application.all
        app = Spaceship::Tunes::Application.find("<redacted>")
        stats = app.analytics # this line crashes!
```

##### Complete output when running fastlane, including the stack trace and command used

I obtained this output with `--verbose` in order to show you the stacktrace:

<details>
  <pre> [✔] 🚀 
[10:08:56]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2020-09-14 10:08:57.97]: Checking if there are any plugins that should be loaded...
Successfully loaded Appfile at path '/var/www/statsStore/fastlane/Appfile'
-------
Successfully loaded Appfile at path '/var/www/statsStore/fastlane/Appfile'
-------
INFO [2020-09-14 10:08:57.99]: ------------------------------
INFO [2020-09-14 10:08:57.99]: --- Step: default_platform ---
INFO [2020-09-14 10:08:57.99]: ------------------------------
INFO [2020-09-14 10:08:58.91]: gem 'spaceship' is already installed
INFO [2020-09-14 10:08:58.99]: Driving the lane 'ios stats' 🚀
Loading session from '/var/www/.fastlane/spaceship/<redacted>/cookie'
Looking for App Store Connect Team with ID <redacted>
Error running script: {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Not Found"], "info"=>nil}, "statusCode"=>"ERROR"}
WARN [2020-09-14 10:09:04.03]: Lane Context:
INFO [2020-09-14 10:09:04.03]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios stats"}
ERROR [2020-09-14 10:09:04.03]: Error in your Fastfile at line 48

[...]

ERROR [2020-09-14 10:09:04.04]: fastlane finished with errors

[...]

Traceback (most recent call last):
	24: from /usr/local/bin/fastlane:23:in `<main>'
	23: from /usr/local/bin/fastlane:23:in `load'
	22: from /var/lib/gems/2.5.0/gems/fastlane-2.159.0/bin/fastlane:23:in `<top (required)>'
	21: from /var/lib/gems/2.5.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	20: from /var/lib/gems/2.5.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	19: from /var/lib/gems/2.5.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	18: from /var/lib/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	17: from /var/lib/gems/2.5.0/gems/fastlane-2.159.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	16: from /var/lib/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	15: from /var/lib/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	14: from /var/lib/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	13: from /var/lib/gems/2.5.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	12: from /var/lib/gems/2.5.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	11: from /var/lib/gems/2.5.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	10: from /var/lib/gems/2.5.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	 9: from /var/lib/gems/2.5.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	 8: from /var/lib/gems/2.5.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	 7: from /var/lib/gems/2.5.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	 6: from Fastfile:39:in `block (2 levels) in parsing_binding'
	 5: from /var/lib/gems/2.5.0/gems/fastlane-2.159.0/spaceship/lib/spaceship/tunes/application.rb:146:in `analytics'
	 4: from /var/lib/gems/2.5.0/gems/fastlane-2.159.0/spaceship/lib/spaceship/tunes/application.rb:126:in `live_version'
	 3: from /var/lib/gems/2.5.0/gems/fastlane-2.159.0/spaceship/lib/spaceship/tunes/app_version.rb:291:in `find'
	 2: from /var/lib/gems/2.5.0/gems/fastlane-2.159.0/spaceship/lib/spaceship/tunes/tunes_client.rb:447:in `app_version'
	 1: from /var/lib/gems/2.5.0/gems/fastlane-2.159.0/spaceship/lib/spaceship/tunes/tunes_client.rb:456:in `app_version_data'
/var/lib/gems/2.5.0/gems/fastlane-2.159.0/spaceship/lib/spaceship/client.rb:719:in `parse_response': [!] {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Not Found"], "info"=>nil}, "statusCode"=>"ERROR"} (Spaceship::UnexpectedResponse) </pre>
</details>

### Environment

<details>
  <pre> [✔️] 🚀 
[10:26:21]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[10:26:22]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | debian_based buster/sid                                        |
| Ruby                        | 2.5.1                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.17.1                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Ubuntu 18.04.4 LTS debian_based buster/sid (4.15.0-88-generic) |
| Ruby Lib Dir                | /usr/lib                                                       |
| OpenSSL Version             | OpenSSL 1.1.1  11 Sep 2018                                     |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US       | 🚫 |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>./fastlane/Fastfile</summary>

ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
fastlane_require 'spaceship'

platform :ios do
    desc "Get correct stats"
      lane :stats do | args |
        # connect to app store
        Spaceship::Tunes.login("<redacted>", "<redacted>")
        ENV['FASTLANE_ITC_TEAM_ID'] = '<redacted>'
        Spaceship::Tunes.select_team
        all_apps = Spaceship::Tunes::Application.all
        app = Spaceship::Tunes::Application.find("<redacted>")
        print("correct login\n")

        # set dates with argument params
        start_date = stringToDate(args[:start_date])
        end_date = stringToDate(args[:end_date])
        start_t = start_date.strftime("%Y-%m-%dT00:00:00Z")
        end_t = end_date.strftime("%Y-%m-%dT00:00:00Z")

        print(app.analytics)
        stats = app.analytics
        return
        path = '../assets/'
        print(end_date.year.to_s)
        print(dateIntToString(end_date.month))
        print(dateIntToString(end_date.day))
        file_name = 'ios_' + end_date.year.to_s + dateIntToString(end_date.month) + dateIntToString(end_date.day) +'.json';
        print(file_name)
        print("\n")

        print("gets all analytics raw data\n")
        # gets all analytics raw data for dates
        impressions = stats.app_impressions_interval(start_t, end_t)
        views = stats.app_views_interval(start_t, end_t)
        units = stats.app_units_interval(start_t, end_t)
        ia_purchase = stats.app_in_app_purchases_interval(start_t, end_t)
        sales = stats.app_sales_interval(start_t, end_t)
        paying_users = stats.app_paying_users_interval(start_t, end_t)
        installations = stats.app_installs_interval(start_t, end_t)
        sessions = stats.app_sessions_interval(start_t, end_t)
        active_devices = stats.app_active_devices_interval(start_t, end_t)
        active_devices_30 = stats.app_active_last_30_days_interval(start_t, end_t)
        crashes = stats.app_crashes_interval(start_t, end_t)
        # measure = stats.app_measure_interval(start_t, end_t)
        
        app_reviews = app.ratings.reviews

        # add raw data to result dictionary
        dictionary = {
          "impressions" => impressions,
          "views" => views,
          "units" => units,
          "inAppPurchase" => ia_purchase,
          "sales" => sales,
          "payingUsers" => paying_users,
          "installations" => installations,
          "sessions" => sessions,
          "activeDevices" => active_devices,
          "activeDevices30" => active_devices_30,
          "crashes" => crashes,
          "reviews" => []
        }
        print("dictionary created\n")

        # add raw reviews to dictionary
        for raw_review in app_reviews do
          response = nil

          # if developer has response we take the raw response
          if (raw_review.raw_developer_response != nil)
            response = {
              "responseId" => raw_review.raw_developer_response['responseId'],
              "response" => raw_review.raw_developer_response['response'],
              "lastModified" => raw_review.raw_developer_response['lastModified'],
              "isHidden" => raw_review.raw_developer_response['isHidden'],
              "pendingState" => raw_review.raw_developer_response['pendingState'],
              "review_id" => raw_review.raw_developer_response['review_id']
            }
          end

          # set raw review
          review = {
            "rating" => raw_review.rating,
            "id" => raw_review.id,
            "title" => raw_review.title,
            "review" => raw_review.review,
            "nickname" => raw_review.nickname,
            "store_front" => raw_review.store_front,
            "last_modified" => raw_review.last_modified,
            "helpful_views" => raw_review.helpful_views,
            "total_views" => raw_review.total_views,
            "edited" => raw_review.edited,
            "raw_developer_response" => response
          }
          
          dictionary['reviews'].push(review)
        end
        
        print("write file\n")
        File.write(path + file_name, dictionary.to_json)
      end

      def dateIntToString (myDate)
        if myDate < 10
          result = "0" + myDate.to_s
        else
          result = myDate.to_s
        end
        return result
      end

      def stringToDate (stringDate)
   year = stringDate[0, 4]
        month = stringDate[5, 2]
        day = stringDate[8, 2]
        date = Time.new(year, month, day)
        
        return date
      end
end

</details>

<details><summary>./fastlane/Appfile</summary>

ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.159.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

No plugins Loaded

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.72.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday                   | 1.0.1        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.13.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.11.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.5.1        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.365.0      |
| aws-eventstream           | 1.0.3        |
| aws-sigv4                 | 1.1.1        |
| aws-sdk-core              | 3.105.0      |
| aws-sdk-kms               | 1.37.0       |
| aws-sdk-s3                | 1.79.1       |
| ipaddr                    | 1.2.0        |
| openssl                   | 2.1.1        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| psych                     | 3.0.2        |
| webrick                   | 1.4.2        |
</details>

*generated on:* 2020-09-14
</details>
[10:26:22]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[10:26:22]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅ </pre>
</details>

**Comment by max-ott** [comment]
`Spaceship::Tunes` is now more or less deprecated and after Apple's changes has broken a lot of things. I don't think this is added yet. More than happy to review any PR using the new `ConnectAPI`.

**Comment by muccy** [comment]
Thank you very much. It is what I was fearing of. I will look into it, bye

**Comment by Michasells** [comment]
The Real-Time reports help troubleshoot your Google Analytics setup and show all current activity on your site. If you have active visitors on your website and you don’t see any data in your Real-Time reports, your tracking code is not sending any information to your Google Analytics account.

**Comment by max-ott** [comment]
The old code still works (nothing changed on the Analytics part really so far), but it breaks in `spaceship`, as we currently have a check if there's a `live_version` (there are no data for `edit_version` only apps)

Specifically this line is breaking as the check no longer works: https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/tunes/application.rb#L146

As a walk-around in the meantime, you can do the direct calls:

```
Spaceship::Tunes.client.time_series_analytics(['12345789'], ['impressionsTotal'], '2020-09-01T00:00:00Z', '2020-09-23T00:00:00Z', "DAY", view_by = nil) 
```

You can check https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/tunes/app_analytics.rb#L93 for reference. I'll work out with @joshdholtz how we can patch this.

**Comment by muccy** [comment]
Thank you very much Max, I've just tried the workaround and in fact it worked.

**Comment by White336** [comment]
Thanks  to share this piece of information here , we are glad to have some knowledge about spaceship analytics  through your post 
keep suggesting such informative post [AlaskasWorld](https://www.alaskasworld.me/)

**Comment by Martin-926** [comment]
Thanks fort he solution,its work for me [NavyArmyCCU Login](https://www.navyarmyccu.ltd/)

**Comment by Dinsen** [comment]
You can also use the AppAnalytics class directly:

```ruby
attrs = {}  
attrs[:apple_id] = "123456789"  
analytics = Spaceship::Tunes::AppAnalytics.factory(attrs)  
puts analytics.app_impressions
```
