### ISSUE TITLE
deliver issue: "Waiting for screenshot to appear before uploading..."

### ISSUE THREAD

**Issue by exavi** [fastlane/fastlane#17243]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: [e.g. `2.x.x`]
- Last working version: [e.g. `2.x.x`]

I can't quite specify when it last worked, but I know for sure, based on the uploads that I have done through Xcode's "Organizer" that it first failed for me on the 21st August, and it last worked on the 14th, so somewhere between that it broke.

I have tested it with recent versions and it seems to keep happening.

### Regression Description

When running deliver, it gets stuck uploading images, and it keeps repeating:
"Waiting for screenshot to appear before uploading..."

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[20:42:25]: Successfully exported and compressed dSYM file
[20:42:25]: Successfully exported and signed the ipa file:
[20:42:25]: /Users/exavi/git/sw/app/src/ios/app.ipa
[20:42:26]: ---------------------
[20:42:26]: --- Step: deliver ---
[20:42:26]: ---------------------
[20:42:26]: Successfully loaded '/Users/exavi/git/sw/app/src/ios/fastlane/Deliverfile' 📄

+-----------------------+-----------------------+
| Detected Values from './fastlane/Deliverfile' |
+-----------------------+-----------------------+
| app_identifier        | com.my.app  |
| username              | my@email.com     |
+-----------------------+-----------------------+

[20:42:26]: Login to App Store Connect (my@email.com)
Requesting session...
[20:43:51]: Login successful

+--------------------------------------+-----------------------------------------------+
|                               deliver 2.159.0 Summary                                |
+--------------------------------------+-----------------------------------------------+
| force                                | true                                          |
| ipa                                  | /Users/exavi/git/sw/app/src/ios/app.ipa |
| screenshots_path                     | ./fastlane/screenshots                        |
| metadata_path                        | ./fastlane/metadata                           |
| app_version                          | 1.7.1                                         |
| username                             | byexavi@gmail.com                             |
| app_identifier                       | app                          |
| platform                             | ios                                           |
| edit_live                            | false                                         |
| use_live_version                     | false                                         |
| skip_binary_upload                   | false                                         |
| skip_screenshots                     | false                                         |
| skip_metadata                        | false                                         |
| skip_app_version_update              | false                                         |
| overwrite_screenshots                | false                                         |
| submit_for_review                    | false                                         |
| reject_if_possible                   | false                                         |
| automatic_release                    | false                                         |
| phased_release                       | false                                         |
| reset_ratings                        | false                                         |
| dev_portal_team_id                   | somenumber                                    |
| run_precheck_before_submit           | true                                          |
| precheck_default_rule_level          | warn                                          |
| ignore_language_directory_validation | false                                         |
| precheck_include_in_app_purchases    | true                                          |
+--------------------------------------+-----------------------------------------------+

[20:43:54]: Making sure the latest version on App Store Connect matches '1.7.1'...
[20:43:55]: '1.7.1' is the latest version on App Store Connect
[20:43:55]: Unaccepted device screenshots are detected! 🚫 Screenshot file will be skipped. 🏃
[20:43:55]: 🏃 Skipping screenshot file: ./fastlane/screenshots/en-US/iPhone 11-01_Portrait_MainUI.png - Not an accepted App Store Connect device...
[20:43:55]: 🏃 Skipping screenshot file: ./fastlane/screenshots/en-US/iPhone 11-02_Portrait_SculptTool.png - Not an accepted App Store Connect device...
[20:43:55]: 🏃 Skipping screenshot file: ./fastlane/screenshots/en-US/iPhone 11-03_Portrait_Mesh.png - Not an accepted App Store Connect device...
[20:43:55]: 🏃 Skipping screenshot file: ./fastlane/screenshots/en-US/iPhone 11-04_Portrait_SculptLayers.png - Not an accepted App Store Connect device...
[20:43:55]: 🏃 Skipping screenshot file: ./fastlane/screenshots/en-US/iPhone 11-06_Portrait_DisplayMode.png - Not an accepted App Store Connect device...
[20:43:55]: 🏃 Skipping screenshot file: ./fastlane/screenshots/en-US/iPhone 11-06_Portrait_Tools.png - Not an accepted App Store Connect device...
[20:43:55]: 🏃 Skipping screenshot file: ./fastlane/screenshots/en-US/iPhone 11-09_Portrait_IBLs.png - Not an accepted App Store Connect device...
[20:43:55]: Loading './fastlane/metadata/en-US/description.txt'...
[20:43:55]: Loading './fastlane/metadata/en-US/keywords.txt'...
[20:43:55]: Loading './fastlane/metadata/en-US/release_notes.txt'...
[20:43:55]: Loading './fastlane/metadata/en-US/support_url.txt'...
[20:43:55]: Loading './fastlane/metadata/en-US/marketing_url.txt'...
[20:43:55]: Loading './fastlane/metadata/en-US/promotional_text.txt'...
[20:43:55]: Loading './fastlane/metadata/en-US/name.txt'...
[20:43:55]: Loading './fastlane/metadata/en-US/subtitle.txt'...
[20:43:55]: Loading './fastlane/metadata/en-US/privacy_url.txt'...
[20:43:55]: Loading './fastlane/metadata/es-ES/description.txt'...
[20:43:55]: Loading './fastlane/metadata/es-ES/keywords.txt'...
[20:43:55]: Loading './fastlane/metadata/es-ES/release_notes.txt'...
[20:43:55]: Loading './fastlane/metadata/es-ES/support_url.txt'...
[20:43:55]: Loading './fastlane/metadata/es-ES/marketing_url.txt'...
[20:43:55]: Loading './fastlane/metadata/es-ES/promotional_text.txt'...
[20:43:55]: Loading './fastlane/metadata/es-ES/name.txt'...
[20:43:55]: Loading './fastlane/metadata/es-ES/subtitle.txt'...
[20:43:55]: Loading './fastlane/metadata/es-ES/privacy_url.txt'...
[20:43:55]: Loading './fastlane/metadata/copyright.txt'...
[20:43:55]: Loading './fastlane/metadata/primary_category.txt'...
[20:43:55]: Loading './fastlane/metadata/secondary_category.txt'...
[20:43:55]: Loading './fastlane/metadata/primary_first_sub_category.txt'...
[20:43:55]: Loading './fastlane/metadata/primary_second_sub_category.txt'...
[20:43:55]: Loading './fastlane/metadata/secondary_first_sub_category.txt'...
[20:43:55]: Loading './fastlane/metadata/secondary_second_sub_category.txt'...
[20:43:55]: Loading './fastlane/metadata/review_information/first_name.txt'...
[20:43:55]: Loading './fastlane/metadata/review_information/last_name.txt'...
[20:43:55]: Loading './fastlane/metadata/review_information/phone_number.txt'...
[20:43:55]: Loading './fastlane/metadata/review_information/email_address.txt'...
[20:43:55]: Loading './fastlane/metadata/review_information/demo_user.txt'...
[20:43:55]: Loading './fastlane/metadata/review_information/demo_password.txt'...
[20:43:55]: Loading './fastlane/metadata/review_information/notes.txt'...
[20:43:57]: Will begin uploading metadata for '1.7.1' on App Store Connect
[20:43:57]: Uploading metadata to App Store Connect for version
[20:43:58]: Uploading metadata to App Store Connect for localized version 'en-US'
[20:43:58]: Uploading metadata to App Store Connect for localized version 'es-ES'
[20:43:59]: Uploading metadata to App Store Connect for localized info 'es-ES'
[20:43:59]: Uploading metadata to App Store Connect for localized info 'en-US'
[20:44:03]: Uploading app review information to App Store Connect
[20:44:05]: Will begin uploading snapshots for '1.7.1' on App Store Connect
[20:44:05]: Starting with the upload of screenshots...
[20:44:06]: Previous uploaded. Skipping './fastlane/screenshots/en-US/iPad Pro (11-inch) (2nd generation)-01_LandscapeLeft_MainUI.png'...
[20:44:06]: Previous uploaded. Skipping './fastlane/screenshots/en-US/iPad Pro (11-inch) (2nd generation)-02_LandscapeLeft_SculptTool.png'...
[20:44:06]: Previous uploaded. Skipping './fastlane/screenshots/en-US/iPad Pro (11-inch) (2nd generation)-03_LandscapeLeft_Mesh.png'...
[20:44:06]: Previous uploaded. Skipping './fastlane/screenshots/en-US/iPad Pro (12.9-inch) (4th generation)-01_LandscapeLeft_MainUI.png'...
[20:44:06]: Previous uploaded. Skipping './fastlane/screenshots/en-US/iPad Pro (12.9-inch) (4th generation)-02_LandscapeLeft_SculptTool.png'...
[20:44:06]: Previous uploaded. Skipping './fastlane/screenshots/en-US/iPad Pro (12.9-inch) (4th generation)-03_LandscapeLeft_Mesh.png'...
[20:44:06]: Previous uploaded. Skipping './fastlane/screenshots/en-US/iPad Pro (9.7-inch)-01_LandscapeLeft_MainUI.png'...
[20:44:06]: Previous uploaded. Skipping './fastlane/screenshots/en-US/iPad Pro (9.7-inch)-02_LandscapeLeft_SculptTool.png'...
[20:44:06]: Previous uploaded. Skipping './fastlane/screenshots/en-US/iPad Pro (9.7-inch)-03_LandscapeLeft_Mesh.png'...
[20:44:06]: Previous uploaded. Skipping './fastlane/screenshots/en-US/iPhone 11 Pro Max-01_Portrait_MainUI.png'...
[20:44:06]: Previous uploaded. Skipping './fastlane/screenshots/en-US/iPhone 11 Pro Max-02_Portrait_SculptTool.png'...
[20:44:06]: Previous uploaded. Skipping './fastlane/screenshots/en-US/iPhone 11 Pro Max-03_Portrait_Mesh.png'...
[20:44:06]: Previous uploaded. Skipping './fastlane/screenshots/en-US/iPhone 11 Pro Max-04_Portrait_SculptLayers.png'...
[20:44:06]: Previous uploaded. Skipping './fastlane/screenshots/en-US/iPhone 11 Pro-01_Portrait_MainUI.png'...
[20:44:06]: Previous uploaded. Skipping './fastlane/screenshots/en-US/iPhone 11 Pro-02_Portrait_SculptTool.png'...
[20:44:06]: Previous uploaded. Skipping './fastlane/screenshots/en-US/iPhone 11 Pro-03_Portrait_Mesh.png'...
[20:44:06]: Previous uploaded. Skipping './fastlane/screenshots/en-US/iPhone 11 Pro-04_Portrait_SculptLayers.png'...
[20:44:06]: Previous uploaded. Skipping './fastlane/screenshots/en-US/iPhone 8 Plus-01_Portrait_MainUI.png'...
[20:44:06]: Previous uploaded. Skipping './fastlane/screenshots/en-US/iPhone 8 Plus-02_Portrait_SculptTool.png'...
[20:44:06]: Previous uploaded. Skipping './fastlane/screenshots/en-US/iPhone 8 Plus-03_Portrait_Mesh.png'...
[20:44:06]: Previous uploaded. Skipping './fastlane/screenshots/en-US/iPhone 8-01_Portrait_MainUI.png'...
[20:44:06]: Previous uploaded. Skipping './fastlane/screenshots/en-US/iPhone 8-02_Portrait_SculptTool.png'...
Waiting for screenshot to appear before uploading...
Waiting for screenshot to appear before uploading...
Waiting for screenshot to appear before uploading...
Waiting for screenshot to appear before uploading...
Waiting for screenshot to appear before uploading...
Waiting for screenshot to appear before uploading...
Waiting for screenshot to appear before uploading...
Waiting for screenshot to appear before uploading...
Waiting for screenshot to appear before uploading...
Waiting for screenshot to appear before uploading...
^C+--------------------+-----------------------------------------------------------------------------+
|                                           Lane Context                                           |
+--------------------+-----------------------------------------------------------------------------+
| DEFAULT_PLATFORM   | ios                                                                         |
| PLATFORM_NAME      | ios                                                                         |
| LANE_NAME          | ios appstore                                                                |
| IPA_OUTPUT_PATH    | /Users/exavi/git/sw/app/src/ios/app.ipa                               |
| XCODEBUILD_ARCHIVE | /Users/exavi/Library/Developer/Xcode/Archives/2020-09-15/app 2020-09-15  |
|                    | 20.21.12.xcarchive                                                          |
| DSYM_OUTPUT_PATH   | /Users/exavi/git/sw/app/src/ios/app.app.dSYM.zip                      |
+--------------------+-----------------------------------------------------------------------------+

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 3    | cocoapods                  | 26          |
| 4    | gym                        | 1284        |
| 5    | deliver                    | 105         |
+------+----------------------------+-------------+

[20:44:12]: fastlane finished with errors</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.4                                     |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.15.4 (19E287)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.1/lib            |
| OpenSSL Version             | OpenSSL 1.0.2o  27 Mar 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.7                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | es_ES.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.60.1"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    # carthage
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "app", workspace: "app.xcworkspace")
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym(
        scheme: "app", 
        workspace: "app.xcworkspace",
		clean: true,
		export_method: "app-store",
		export_options: {
		      provisioningProfiles: { 
		        "something" => "AppStore Distribution"
		      }
		}
    )
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "something" # The bundle identifier of your app
apple_id "somethingelse" # Your Apple email address

team_id "somenumber" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.159.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 1.0.1        |
| faraday_middleware        | 1.0.0        |
| gh_inspector              | 1.1.3        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.16.1       |
| uber                      | 0.1.0        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mini_mime                 | 1.0.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| nanaimo                   | 0.3.0        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.18.0       |
| unicode-display_width     | 1.7.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| excon                     | 0.76.0       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| fastimage                 | 2.2.0        |
| json                      | 2.3.1        |
| mini_magick               | 4.10.1       |
| dotenv                    | 2.7.6        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| declarative               | 0.0.20       |
| retriable                 | 3.1.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| os                        | 1.1.1        |
| memoist                   | 0.16.2       |
| googleauth                | 0.13.1       |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-env          | 1.3.3        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.28.0       |
| emoji_regex               | 3.0.0        |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-partitions            | 1.367.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.105.0      |
| aws-sdk-kms               | 1.37.0       |
| aws-sdk-s3                | 1.80.0       |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-09-15**
</details>
</pre>
</details>

**Comment by da-mian** [comment]
Same issue

**Comment by dave-perry** [comment]
Also seeing the same issue.

**Comment by mackoj** [comment]
same here

**Comment by stephengilroy-grx** [comment]
Anyone have any insight on this one? Blocking us as well.

**Comment by Ben834** [comment]
We get the same issue here for all of our apps.

**Comment by rogerluan** [comment]
Hey guys, I faced this issue and dug into it a little bit to figure out _a_ solution. 

### Observation

Apparently this happens only when there are already screenshots in App Store Connect, and you're trying to upload more.

### Hypothesis 

I think this is happening because it can't upload more than 10 screenshots to App Store Connect.
So if you had e.g. 7 screenshots, trying to upload 7 screenshots again, 3 of them will succeed, and you will have 10 of them there, but the remaining 4 will be in a broken state where _fastlane_ thinks it was uploaded, but it was either not uploaded or rejected by App Store Connect.

### Workaround

I realized that if you set `overwriteScreenshots: true`, it will fix this issue.

**Pros:** it works. Your screenshots will be successfully uploaded. 
**Cons:** it will take longer. All your screenshots will be deleted and uploaded again, instead of looking at _fastlane_'s "smart screenshot upload checksum cache" 😅

**Comment by joshdholtz** [comment]
I think @rogerluan's solution to use `overwrite_screenshots: true` is the current best workaround.

But I will look into to see if I can replicate and figure out what's going on.

@ainame Have you seen this over on your end at all? Or have any idea what could be causing this? 😇

**Comment by ainame** [comment]
Let me have a look 👀  I personally have been using `overwrite_screenshots: true`, so that' why I haven't seen it?

**Comment by ainame** [comment]
I haven't figured it out yet but I feel like at first, we should log error messages getting from `rescue` block.

https://github.com/fastlane/fastlane/blob/53ce1fab1f616b981fc80d3abd97320f65187ba7/spaceship/lib/spaceship/connect_api/models/app_screenshot.rb#L100-L115

When I see the message "Waiting for..." on my local, it seems that the error is "500" error which is, of course, not good and would be something unexpected on the server-side. (If it's handled by the server-side properly, there must be better error status code returning in 4xx, I suppose.)

```diff
-             puts("Waiting for screenshot to appear before uploading...")
+             puts("Waiting for screenshot to appear before uploading... #{error}")
```

> [21:13:34]: Uploaded './fastlane/screenshots/es-ES/6.5_5.jpg'... (14.780984 secs)
> Waiting for screenshot to appear before uploading... Server error got 500
> Waiting for screenshot to appear before uploading... Server error got 500
> Waiting for screenshot to appear before uploading... Server error got 500
> Waiting for screenshot to appear before uploading... Server error got 500
> Waiting for screenshot to appear before uploading... Server error got 500
> Waiting for screenshot to appear before uploading... Server error got 500
> Waiting for screenshot to appear before uploading... Server error got 500 

(I somehow managed to replicate it but it's not the same step as what @rogerluan said. There is a small chance that it was just App Store Connect API's error 🤷‍♂️ )

**Comment by joshdholtz** [comment]
Oh goodness! I don't know if your results make me feel better or worse 😝

I'll try to replicate on my side and see which of these errors (if any) I get 😬

**Comment by ainame** [comment]
I think I might understand what is going on.

https://github.com/fastlane/fastlane/blob/53ce1fab1f616b981fc80d3abd97320f65187ba7/deliver/lib/deliver/upload_screenshots.rb#L131-L148

The above check code "index >= 10" still works without "overwrite_screenshots: true" if you append images to only the end of the set. But in the scenario below, "index" will kind of make a contradiction... 

Let's say we have already uploaded 6 screenshots for 6.5-inch screen like this. 

1. "6.5_1.jpg" (uploaded)
1. "6.5_2.jpg" (uploaded)
1. "6.5_3.jpg" (uploaded)
1. "6.5_4.jpg" (uploaded)
1. "6.5_5.jpg" (uploaded)
1. "6.5_6.jpg" (uploaded)

And then you happen to copy another lang's 6.5inch screenshots and paste to the directory ^ those screenshots are stored. It will be like this if sorted. (This would sound weird but was the easiest way to replicate this actually.)

1. "6.5_1 copy.jpg" (local)
1. "6.5_1.jpg" (uploaded)
1. "6.5_2 copy.jpg" (local)
1. "6.5_2.jpg" (uploaded)
1. "6.5_3 copy.jpg" (local)
1. "6.5_3.jpg" (uploaded)
1. "6.5_4 copy.jpg" (local)
1. "6.5_4.jpg" (uploaded)
1. "6.5_5 copy.jpg" (local)
1. "6.5_5.jpg" (uploaded)
1. "6.5_6 copy.jpg" (local)
1. "6.5_6.jpg" (uploaded)

With the current code, it's going to pick up the first 10 images from the above list to decide "skip" or "upload", which means -

* 5 local images; "6.5_1 copy.jpg", "6.5_2 copy.jpg", "6.5_3 copy.jpg", "6.5_4 copy.jpg" and "6.5_5 copy.jpg", are going to be newly uploaded
* "6.5_6 copy.jpg" and "6.5_6.jpg" will be just ignored
* Since 6 images "6.5_[1-6].jpg" have been uploaded already, at least one of those uploads must fail (it's concurrently working so can't tell which one fails)
* Unfortunately, [the loop](https://github.com/fastlane/fastlane/blob/53ce1fab1f616b981fc80d3abd97320f65187ba7/spaceship/lib/spaceship/connect_api/models/app_screenshot.rb#L113-L129) can't that fast exit by timeout (it's going to take up 20 mins on each error 🏃‍♂️ 🏃‍♂️ 🏃‍♂️ )  

I might be wrong but this is what I got so far. I can work on fixing this tomorrow🙂

**Comment by rogerluan** [comment]
I happen to remember what I did when I faced this issue, and it sounds a lot similar to your explanation @ainame :

I uploaded 7 images, named whatever. I didn't submit the app for review.
Then I renamed all the images (same assets, just renamed), and ran the lane again. It attempted to upload them all again, of course. But since `overwrite_screenshots` wasn't `true`, it uploaded only 3 of them, and there were already 7 of them in the store, so I got stuck in the `Waiting for screenshot to appear before uploading...` loop.

In your scenario, sounds like the rationale would be to check that there're more than 10 assets. But in mine, probably the image checksum/cache mechanism would need to be updated 🤔 I don't think that's the best way out, though, I honestly think that `overwrite_screenshots: true` is the right solution for **my** problem.
It'd be great if we knew what went wrong to everyone else 😄 but sounds like your problem might be similar to other people's scenarios 👍

**Comment by ainame** [comment]
I've got a fix for this on my forked repo. Will submit a PR soon🙂 
https://github.com/fastlane/fastlane/compare/master...ainame:fix-deliver-upload-screenshots

While working on it, I thought about a few things.

* Skipping screenshots uploads is cool but involves confusions to fastlane-users
  * I think the scenario rogerluan described can easily happen and people may tend to not update the option to overwrite at their first try
  * The ambiguity when not using `overwrite_sreenshots: true` for users is considerably big so that it's not 100% useful
  * Maybe we can better handle partial updates even with `overwrite_screenshots: false`
* `Spaceship::ConnectAPI` models can't really handle status code so that any errors were dealt as the same
  * It would be great if a wrapped error class has the direct access to status code https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/connect_api/api_client.rb#L180

I may propose some changes around the behaviour of screenshots updates at some point in order to not make this kind of confusions🤞

**Comment by ainame** [comment]
Submitted https://github.com/fastlane/fastlane/pull/17346 🙂

**Comment by ainame** [comment]
@rogerluan 

> Then I renamed all the images (same assets, just renamed), and ran the lane again. It attempted to upload them all again, of course. But since overwrite_screenshots wasn't true, it uploaded only 3 of them, and there were already 7 of them in the store, so I got stuck in the Waiting for screenshot to appear before uploading... loop.

I feel like this isn't exactly the same scenario as I expected. Because renaming file shouldn't change its file's MD5 checksum at all so that deliver should recognise the same file uploaded on App Store Connect even if the file name is different.

**Comment by rogerluan** [comment]
@ainame I initially thought so as well, however, first I thought that the checksum would change because of the metadata (filepath) change - but in fact it doesn't (I verified this via bash and not ruby, but should be the same behavior I hope 😇 )

```bash
find … -print0 | xargs -0 md5 

# Then renamed the file and repeated the command and they print the same md5 in fact
```

Then, on a second thought, although the checksums match - aren't we using the filepath as an identifier for the cache? 🤔 I didn't dig much into the code but I had the feeling that we were using like a key:value relation where the key was the filepath and the value was the checksum. 
I can be totally wrong tho, you have deeper knowledge of all this 😁 lmk if any of this makes sense :)

**Comment by ainame** [comment]
@rogerluan  `deliver` only relies on checksum to match up. There's no caching at all. It's just to classify "Skip uploading" or "Upload", in reality🙂 

https://github.com/fastlane/fastlane/blob/818b4e34edeb090fbc7d8c5bab9d3e45ce0483f0/deliver/lib/deliver/upload_screenshots.rb#L137-L138
