### ISSUE TITLE
[Spaceship] Running commands in lane returns: `You need to instantiate this module with test_flight_request_client`

### ISSUE THREAD

**Issue by john-mejia** [fastlane/fastlane#17258]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Spaceship commands through custom lane return:
`You need to instantiate this module with test_flight_request_client`

Running the same commands in spaceship directly work fine. I feel like this is something super simple but have not been to find any info in the docs or by searching.

##### Command executed
```
    Spaceship.login
    Spaceship.select_team
    
    app = Spaceship::ConnectAPI::App.find(APP_ID_APPSTORE)
    version = app.get_live_app_store_version
    phasedRelease = version.fetch_app_store_version_phased_release

    if new_state == 'PAUSED'
      phasedRelease.pause
      next
    end
    
    ## new_state == 'ACTIVE'
    phasedRelease.resume
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> DEBUG [2020-09-16 19:56:22.36]: Using pause: true
INFO [2020-09-16 19:56:22.45]: ------------------------------
INFO [2020-09-16 19:56:22.45]: --- Step: default_platform ---
INFO [2020-09-16 19:56:22.45]: ------------------------------
INFO [2020-09-16 19:56:22.45]: Driving the lane 'ios update_rollout_state' 🚀
Reading keychain entry, because either user or password were empty
Loading session from '/Users/johnmejia/.fastlane/spaceship/[redacted]/cookie'
INFO [2020-09-16 19:56:24.67]: -------------------
INFO [2020-09-16 19:56:24.67]: --- Step: is_ci ---
INFO [2020-09-16 19:56:24.67]: -------------------
WARN [2020-09-16 19:56:24.67]: Lane Context:
INFO [2020-09-16 19:56:24.67]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios update_rollout_state"}
ERROR [2020-09-16 19:56:24.67]: You need to instantiate this module with test_flight_request_client
INFO [2020-09-16 19:56:24.67]: Successfully generated documentation at path '/Users/johnmejia/workspace/iphone-application/fastlane/README.md'

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 2    | is_ci            | 0           |
+------+------------------+-------------+

+---------------------------+--------------+----------------+
|                 Plugin updates available                  |
+---------------------------+--------------+----------------+
| Plugin                    | Your Version | Latest Version |
+---------------------------+--------------+----------------+
| firebase_app_distribution | 0.2.0        | 0.2.1          |
+---------------------------+--------------+----------------+
INFO [2020-09-16 19:56:24.68]: To update all plugins, just run
INFO [2020-09-16 19:56:24.68]: $ bundle exec fastlane update_plugins

ERROR [2020-09-16 19:56:24.68]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: You need to instantiate this module with test_flight_request_client

URL: https://api.github.com/search/issues?q=You%20need%20to%20instantiate%20this%20module%20with%20test_flight_request_client+repo:fastlane/fastlane
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
bundler: failed to load command: fastlane (/Users/johnmejia/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/bin/fastlane)
TypeError: [!] You need to instantiate this module with test_flight_request_client
  /Users/johnmejia/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.160.0/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:13:in `test_flight_request_client'
  /Users/johnmejia/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.160.0/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:21:in `get_apps'
  /Users/johnmejia/.rbenv/versions/2.6.1/lib/ruby/2.6.0/forwardable.rb:230:in `get_apps'
  /Users/johnmejia/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.160.0/spaceship/lib/spaceship/connect_api/models/app.rb:56:in `all'
  /Users/johnmejia/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.160.0/spaceship/lib/spaceship/connect_api/models/app.rb:61:in `find'
  Fastfile:509:in `block (2 levels) in parsing_binding'
  /Users/johnmejia/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/johnmejia/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/johnmejia/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/johnmejia/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/johnmejia/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /Users/johnmejia/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/johnmejia/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/johnmejia/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/johnmejia/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/johnmejia/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/johnmejia/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.160.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/johnmejia/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/johnmejia/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  /Users/johnmejia/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/johnmejia/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Users/johnmejia/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.160.0/bin/fastlane:23:in `<top (required)>'
  /Users/johnmejia/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/bin/fastlane:23:in `load'
  /Users/johnmejia/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/bin/fastlane:23:in `<top (required)>' </pre>
</details>

### Environment

<details>
  <pre> <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                    |
| --------------------------- | -------------------------------------------------------- |
| OS                          | 10.15.6                                                  |
| Ruby                        | 2.6.1                                                    |
| Bundler?                    | true                                                     |
| Git                         | git version 2.24.3 (Apple Git-128)                       |
| Installation Source         | ~/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/bin/fastlane |
| Host                        | Mac OS X 10.15.6 (19G2021)                               |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.1/lib                              |
| OpenSSL Version             | OpenSSL 1.0.2q  20 Nov 2018                              |
| Is contained                | false                                                    |
| Is homebrew                 | false                                                    |
| Is installed via Fabric.app | false                                                    |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/              |
| Xcode Version               | 11.6                                                     |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.160.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status      |
| ----------------------------------------- | ------- | ------------------ |
| fastlane-plugin-badge                     | 1.4.0   | ✅ Up-To-Date       |
| fastlane-plugin-test_center               | 3.14.3  | ✅ Up-To-Date       |
| fastlane-plugin-firebase_app_distribution | 0.2.0   | 🚫 Update available |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.3.0        |
| bundler                                   | 1.17.3       |
| etc                                       | 1.0.1        |
| forwardable                               | 1.2.0        |
| rake                                      | 13.0.1       |
| CFPropertyList                            | 3.0.2        |
| concurrent-ruby                           | 1.1.7        |
| i18n                                      | 0.9.5        |
| minitest                                  | 5.14.2       |
| thread_safe                               | 0.3.6        |
| tzinfo                                    | 1.2.7        |
| activesupport                             | 4.2.11.3     |
| public_suffix                             | 4.0.6        |
| addressable                               | 2.7.0        |
| httpclient                                | 2.8.3        |
| json                                      | 2.3.1        |
| algoliasearch                             | 1.27.4       |
| atomos                                    | 0.1.3        |
| aws-eventstream                           | 1.1.0        |
| aws-partitions                            | 1.370.0      |
| aws-sigv4                                 | 1.2.2        |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.107.0      |
| aws-sdk-kms                               | 1.38.0       |
| aws-sdk-s3                                | 1.81.0       |
| babosa                                    | 1.0.3        |
| curb                                      | 0.9.10       |
| fastimage                                 | 2.2.0        |
| colored                                   | 1.2          |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| dotenv                                    | 2.7.6        |
| emoji_regex                               | 3.0.0        |
| excon                                     | 0.76.0       |
| multipart-post                            | 2.0.0        |
| faraday                                   | 1.0.1        |
| unf_ext                                   | 0.0.7.7      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.0.0        |
| gh_inspector                              | 1.1.3        |
| jwt                                       | 2.2.2        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.1        |
| signet                                    | 0.14.0       |
| googleauth                                | 0.13.1       |
| mini_mime                                 | 1.0.2        |
| declarative                               | 0.0.20       |
| declarative-option                        | 0.1.0        |
| uber                                      | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| google-api-client                         | 0.38.0       |
| digest-crc                                | 0.6.1        |
| google-cloud-env                          | 1.3.3        |
| google-cloud-errors                       | 1.0.1        |
| google-cloud-core                         | 1.5.0        |
| google-cloud-storage                      | 1.28.0       |
| mini_magick                               | 4.10.1       |
| plist                                     | 3.5.0        |
| rubyzip                                   | 2.3.0        |
| security                                  | 0.1.3        |
| naturally                                 | 2.2.0        |
| simctl                                    | 1.6.8        |
| slack-notifier                            | 2.3.2        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.7.0        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| word_wrap                                 | 1.0.0        |
| claide                                    | 1.0.3        |
| colored2                                  | 3.1.2        |
| nanaimo                                   | 0.3.0        |
| xcodeproj                                 | 1.18.0       |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.0        |
| badge                                     | 0.12.0       |
| fuzzy_match                               | 2.0.4        |
| nap                                       | 1.1.0        |
| netrc                                     | 0.11.0       |
| ffi                                       | 1.13.1       |
| ethon                                     | 0.12.0       |
| typhoeus                                  | 1.4.0        |
| cocoapods-core                            | 1.9.1        |
| cocoapods-deintegrate                     | 1.0.4        |
| cocoapods-downloader                      | 1.4.0        |
| cocoapods-plugins                         | 1.0.0        |
| cocoapods-search                          | 1.0.0        |
| cocoapods-stats                           | 1.1.0        |
| cocoapods-trunk                           | 1.5.0        |
| cocoapods-try                             | 1.2.0        |
| escape                                    | 0.0.4        |
| fourflusher                               | 2.3.1        |
| molinillo                                 | 0.6.6        |
| ruby-macho                                | 1.4.0        |
| cocoapods                                 | 1.9.1        |
| coderay                                   | 1.1.3        |
| colorize                                  | 0.8.1        |
| fastlane-plugin-badge                     | 1.4.0        |
| fastlane-plugin-firebase_app_distribution | 0.2.0        |
| trainer                                   | 0.9.1        |
| xctest_list                               | 1.2.1        |
| fastlane-plugin-test_center               | 3.14.3       |
| method_source                             | 1.0.0        |
| pry                                       | 0.13.1       |
| xcode-install                             | 2.6.6        |
</details>

*generated on:* **2020-09-16**
</details> </pre>
</details>

**Comment by joshdholtz** [comment]
@john-mejia Hey! There are new ways to auth into `Spaceship::ConnectAPI` and I will be writing up more doc next week for all of this! But this is what you are are probably wanting to do 👇 

## Simple call

```rb
Spaceship::ConnectAPI.login
```

## Complex call

This login call is slightly complex because the `Spaceship::ConnectAPI` needs to handle both web sessions to the portal and tunes. Each of these also has different team ids. So here are some examples you can do...

```rb
Spaceship::ConnectAPI.login("email@email.com", portal_team_id: "1242", tunes_team_id: "23432")
```

```rb
Spaceship::ConnectAPI.login("email@email.com", team_name: "YOUR_TEAM_NAME")
```

```rb
Spaceship::ConnectAPI.login("email@email.com", use_portal: false, tunes_team_id: "324")
```

```rb
Spaceship::ConnectAPI.login("email@email.com", use_tunesl: false, portal_team_id: "324")
```

```rb
# This will prompt for both team IDs if they aren't provider by arguments or environment variables
Spaceship::ConnectAPI.login 
```

More doc here - https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/connect_api/spaceship.rb#L63-L83

<hr/>

This is a change but the Connect API (web session and API Key session) are a big change so things needed to be handled differently 😊 I have a few more big changes I'm working on right now for match, cert, and sigh to convert to App Store Connect API before any legacy changes happen but after that I will be working on extensive documentation for all of these things!

**Comment by john-mejia** [comment]
Thanks @joshdholtz - this works now.
