### ISSUE TITLE
Binaries are uploading but never appear as builds in App Store Connect

### ISSUE THREAD

**Issue by tealshift** [fastlane/fastlane#17268]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Fastlane uploads my IPAs but the build does not ever appear in App Store Connect. (Fastlane shows the waiting for processing message a hundred times)

##### Command executed
```
match(app_identifier: app_ids)
build_app(workspace: "Workspace.xcworkspace",
            scheme: "App Release",
            export_options:  {
                method: "app-store",
                provisioningProfiles: app_ids)
            },
            silent: true
    )
upload_to_testflight(
            username: app_store_username,
            changelog: testNotes,
            skip_waiting_for_build_processing: true
        )

```
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.6                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.6 (19G2021)                                     |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.0                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

default_platform(:ios)

platform :ios do |options|

    desc <<~HEREDOC
        It is recommended to add to your shell config file (located at ~/.zshrc):
            PATH=$PATH:/usr/local/sbin
            PATH=$PATH:~/.gems/bin
            export PATH
            export GEM_HOME=~/.gems
            export LC_ALL=en_US.UTF-8
            export LANG=en_US.UTF-8
            export MATCH_PASSWORD=<certificates-encryption-password> # Get this from the team
            export FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT=60
            alias fl="bundle --quiet; bundle exec fastlane"
        HEREDOC
    lane :test do |options|
        UI.message "Testing..."
    end

    desc <<~HEREDOC
        Run this lane with `fl beta`
        This command does: `fl masterbump`, `fl configure`, codesign, build, commit, tag, and upload
        Running this will trigger automatic branching to generated beta branches that all start with "beta/".
        If run from master, master branch will be bumped as needed before configuring as a variant.
        If run from a beta branch, it will commit directly to that branch.
        All variant commits are tagged like: "betabuild/v1.2.3/guillotine-b2"
            Because git tags are global, all build commits can be tracked.
        HEREDOC
    lane :beta do |options|
        ensure_git_status_clean
        # update_fastlane # This command seems unable to actually update fastlane
        newVersion = ask_for_app_version(fromVersion: startingVersion)

        strategy = {
            selectVersion: newVersion,
            autoIncrementBuild: isMultivariant,
            findTargetBranch: true
        }
        if startingBranch == main_branch && version_greater_than(newVersion, startingVersion)
            bump_master(newVersion)
        end
        config = configureApp(variant, strategy, startingBranch)
        testNotes = ask_for_test_notes()
        deploy_beta(config, testNotes)
    end

    desc <<~HEREDOC
        Run this lane with `fl codesign app:<variant>`
        Runs fastlane Match for an app ID set.
        Use this to install the developer certificate for deployment.
        HEREDOC
    lane :codesign do |options|
        appVariant = acquire_variant(options[:app])
        codeSign({code: appVariant})
    end

    def deploy_beta(config, testNotes)
        if existing_git_tag(commit_tag(config))
            reset_git_repo
            switch_back_branch(config)
            UI.user_error! "#{commit_tag(config)} is already tagged in a commit!"
        end

        begin
            codeSign(config)
        rescue => ex # If the codesign build fails, undo the config.
            reset_git_repo
            switch_back_branch(config)
            raise ex
        end

        begin
            build_project(config)
        rescue => ex # If the xcode build fails, undo the increments and hit slack.
            alert_error_on_slack(ex, config)
            reset_git_repo
            switch_back_branch(config)
            raise ex
        end
        # Commit, push and switch back to starting branch.
        commit_variant_changes(config)
        switch_back_branch(config)

        upload_to_testflight(
            username: app_store_username,
            changelog: testNotes,
            skip_waiting_for_build_processing: true
        )
        alert_finished_on_slack(config) # Feel free to comment out if annoying
    end

    def codeSign(config)
        match(app_identifier: app_ids(config[:code]).keys)
    end

    def build_project(config)
        cocoapods(deployment: true)
        options = {
            method: "app-store",
            provisioningProfiles: app_ids(config[:code])
        }
        build_app(
            scheme: "WC Release",
            export_options: options,
            silent: true
        )
    end

    ####################
    #### USER INPUT ####


    def ask_for_app_version(fromVersion: get_current_project_version)
        version = UI.input "Current version is \"#{fromVersion}\". \
            \nPress [enter] to ACCEPT or enter a new version: "
        if version.length == 0
            return fromVersion
        end
        if version.split(".").length < 3
            UI.user_error! "\"#{version}\" is not formatted correctly. Build cancelled."
        end
        return version
    end

    def ask_for_build_number(config)
        build = fetch_current_buildnum(config)
        newBuild = UI.input "Latest build num is: #{build}. \n\
            Press [enter] to INCREMENT or enter a build number: "
        if newBuild.length < 1
            return build + 1
        end
        return newBuild.to_i
    end

    def ask_for_test_notes(didPatch: false)
        commitLog = changelog_from_git_commits(merge_commit_filtering: "exclude_merges")
        if commitLog.length < 1
            commitLog = changelog_from_git_commits(
                merge_commit_filtering: "exclude_merges",
                commits_count: 1
            )
        end
        notes = ""
        if didPatch
            notes = UI.input "What does this patch fix? Add TestFlight notes:"
        else
            notes = UI.input "What are we testing? Add TestFlight notes:"
        end
        if notes.length < 1
            return commitLog
        end
        return notes
    end

    def existing_git_tag(tag) # Rewrite of git_tag_exists so we don't get annoying red text
        system "git rev-parse -q --verify #{tag}"
        return $?.exitstatus == 0
    end

    ###############
    #### UTILS ####

    def patch_increment_on(version)  # "1.2.3" -> "1.2.4"
        versionNums = version.split(".")
        nextPatchNum = versionNums.pop().to_i + 1
        versionNums.push(nextPatchNum.to_s)
        return versionNums.join(".")
    end

    def version_greater_than(newVersion, version)  # "1.2.4" > "1.2.3" -> true
        return Gem::Version.new(newVersion) > Gem::Version.new(version)
    end
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.160.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 1.0.1        |
| faraday_middleware        | 1.0.0        |
| gh_inspector              | 1.1.3        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 2.1.4        |
| uber                      | 0.1.0        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| nanaimo                   | 0.3.0        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.18.0       |
| unicode-display_width     | 1.7.0        |
| public_suffix             | 4.0.6        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| excon                     | 0.76.0       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| fastimage                 | 2.2.0        |
| json                      | 2.3.1        |
| mini_magick               | 4.10.1       |
| dotenv                    | 2.7.6        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| declarative               | 0.0.20       |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| os                        | 1.1.1        |
| memoist                   | 0.16.2       |
| googleauth                | 0.13.1       |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-env          | 1.3.3        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.28.0       |
| emoji_regex               | 3.0.0        |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-partitions            | 1.371.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.107.0      |
| aws-sdk-kms               | 1.38.0       |
| aws-sdk-s3                | 1.81.0       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-09-18**
</details>

**Comment by tianjyan** [comment]
I have the same issue here. Self-Hosted Jenkins with fastlane 2.160.0 and Xcode 12 always prints `Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)`. But my Azure pipelines works properly with fastlane 2.151.2 and Xcode 11.7 (I use [macOS-10.15](https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.15-Readme.md) and default Xcode is 11.7).

I am still investigating this issue.

**Comment by tealshift** [comment]
Yes, you're right!
