### ISSUE TITLE
upload_to_play_store succeeds but build doesnt show up (XCode v12)

### ISSUE THREAD

**Issue by lukemcgregor** [fastlane/fastlane#17266]
### New Issue Checklist

- [y] Updated fastlane to the latest version
- [y] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [y] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [y] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I have a build pipeline in github actions to release to builds to test flight. Its been working fine since i set it up, however today when I do a build fastlane appears to run and upload to testflight but the build never shows up. I expect this is to do with the new XCode version 12 which was released yesterday (and is running on the build server).

##### Command executed
upload_to_testflight

##### Complete output when running fastlane, including the stack trace and command used

2020-09-17T21:34:43.4234180Z [21:34:43]: [32m----------------------------------[0m
2020-09-17T21:34:43.4235220Z [21:34:43]: [32m--- Step: upload_to_testflight ---[0m
2020-09-17T21:34:43.4236200Z [21:34:43]: [32m----------------------------------[0m
2020-09-17T21:34:43.4590800Z [21:34:43]: Login to App Store Connect 
2020-09-17T21:34:43.7262510Z Session loaded from environment variable is not valid. Continuing with normal login.
2020-09-17T21:34:45.2925210Z [21:34:45]: Login successful
2020-09-17T21:34:46.5585470Z [21:34:46]: [32mReady to upload new build to TestFlight (App:)...[0m
2020-09-17T21:34:47.2637860Z [21:34:47]: Fetching password for transporter from environment variable named `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`
2020-09-17T21:34:47.2638790Z [21:34:47]: Going to upload updated app to App Store Connect
2020-09-17T21:34:47.2641640Z [21:34:47]: [32mThis might take a few minutes. Please don't interrupt the script.[0m
2020-09-17T21:36:40.7231550Z [21:36:40]: [32miTunes Transporter successfully finished its job[0m
2020-09-17T21:36:40.8663590Z [21:36:40]: [32m--------------------------------------------------------------------[0m
2020-09-17T21:36:40.8664950Z [21:36:40]: [32mSuccessfully uploaded package to App Store Connect. It might take a few minutes until it's visible online.[0m
2020-09-17T21:36:40.8666450Z [21:36:40]: [32m--------------------------------------------------------------------[0m
2020-09-17T21:36:40.8704200Z [21:36:40]: [32mSuccessfully uploaded the new binary to App Store Connect[0m
2020-09-17T21:36:40.8705750Z [21:36:40]: [33m`skip_waiting_for_build_processing` used and no `changelog` supplied - skipping waiting for build processing[0m

### Environment (sanitized)
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.6                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.6 (19G2021)                                     |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.0                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

opt_out_usage

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci(
      force: true
    )
    match(
      type: "appstore", 
      readonly: true,
      git_url: ENV["MATCH_URL"],
      app_identifier: "com.app"
    )
    increment_build_number(
      build_number: ENV["GITHUB_RUN_NUMBER"],
      xcodeproj: "ios/app.xcodeproj"
    )
    get_certificates( # Create or get certificate, and install it
      output_path: "./ios-builds" # Download certificate in the build folder (you don't need to create the folder)
    )
    get_provisioning_profile( # Create or get provisioning profile
      output_path: "./ios-builds",  # Download provisioning profile in the build folder
      filename: "provisioning.mobileprovision" # Rename the local provisioning profile
    )
    update_project_provisioning( # Set the project provisioning profile (related in Xcode to the General > Signing Release section)
      xcodeproj: "ios/app.xcodeproj",
      target_filter: "app", # Name of your project
      profile: "./ios-builds/provisioning.mobileprovision",
      build_configuration: "Release"
    )
    update_project_team( # Set the right team on your project
      teamid: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
      path: "ios/app.xcodeproj",
    )
    gym(
      workspace: "ios/app.xcworkspace", 
      configuration: "Release",
      scheme: "app",
      clean: true,
      export_method: "app-store",
      output_directory: "./ios-builds",
      output_name: "app.ipa",
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end

platform :android do
  desc "Submit a new build to play store internal"
  lane :internal do
    gradle(
      project_dir: './android', 
      task: "clean assembleRelease",
      print_command: false,
      properties: {
        "versionCode" => ENV["GITHUB_RUN_NUMBER"],
        "versionName" => "1.0.#{ENV["GITHUB_RUN_NUMBER"]}",
        "android.injected.signing.store.file" => "key.keystore",
        "android.injected.signing.store.password" => ENV["KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["KEYSTORE_KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["KEYSTORE_KEY_PASSWORD"],
      }
    )
    upload_to_play_store(track: 'internal')
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
#android
json_key_file("./fastlane/key.json")
package_name("com.")

#ios
app_identifier("com.") # The bundle identifier of your app
apple_id("") # Your Apple email address

itc_team_id("") # App Store Connect Team ID
team_id("") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.160.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.14.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.72.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday                   | 1.0.1        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.287.0      |
| aws-eventstream           | 1.0.3        |
| aws-sigv4                 | 1.1.1        |
| aws-sdk-core              | 3.92.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.61.1       |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| os                        | 1.0.1        |
| memoist                   | 0.16.2       |
| googleauth                | 0.13.1       |
| google-cloud-env          | 1.3.3        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-09-18**
</details>

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by manhpham90vn** [comment]
same here

**Comment by ribamarsantos** [comment]
Same for me. I got on --versbose mode 
`undefined metho get_app_info_localizations for nil`

**Comment by nickyleach** [comment]
App Store Connect has been having issues today:
https://developer.apple.com/forums/thread/660664

**Comment by lukemcgregor** [comment]
All my builds started showing up on Saterday, so I guess the issue was apple.
