### ISSUE TITLE
[swift] 784: unexpected token at '' when running any lane in Fastlane Swift

### ISSUE THREAD

**Issue by rogerluan** [fastlane/fastlane#17275]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: 2.159.0
- Last working version: 2.158.0

### Regression Description

Running _fastlane_ Swift without using SPM crashes with the error:

>…
>Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /Users/rogerluan/Documents/Projects/tellus-ios/fastlane/swift/LaneFileProtocol.swift, line 121
>…
>784: unexpected token at ''
>…

Note that this was only possible after fixing some issues according to this comment: https://github.com/fastlane/fastlane/issues/17234#issuecomment-695099513

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[18:59:41]: ▸ Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /Users/rogerluan/Documents/Projects/tellus-ios/fastlane/swift/LaneFileProtocol.swift, line 121
#<Thread:0x00007fa552614988@/Users/rogerluan/Documents/Projects/tellus-ios/.vendor/ruby/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/swift_lane_manager.rb:220 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	9: from /Users/rogerluan/Documents/Projects/tellus-ios/.vendor/ruby/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/swift_lane_manager.rb:223:in `block in start_socket_thread'
	8: from /Users/rogerluan/Documents/Projects/tellus-ios/.vendor/ruby/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/server/socket_server.rb:38:in `start'
	7: from /Users/rogerluan/Documents/Projects/tellus-ios/.vendor/ruby/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/server/socket_server.rb:158:in `listen'
	6: from /Users/rogerluan/Documents/Projects/tellus-ios/.vendor/ruby/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/server/socket_server.rb:49:in `receive_and_process_commands'
	5: from /Users/rogerluan/Documents/Projects/tellus-ios/.vendor/ruby/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/server/socket_server.rb:49:in `loop'
	4: from /Users/rogerluan/Documents/Projects/tellus-ios/.vendor/ruby/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/server/socket_server.rb:62:in `block in receive_and_process_commands'
	3: from /Users/rogerluan/Documents/Projects/tellus-ios/.vendor/ruby/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/server/socket_server.rb:81:in `parse_and_execute_command'
	2: from /Users/rogerluan/Documents/Projects/tellus-ios/.vendor/ruby/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/server/command_parser.rb:12:in `parse'
	1: from /Users/rogerluan/Documents/Projects/tellus-ios/.vendor/ruby/2.6.0/gems/json-2.3.1/lib/json/common.rb:263:in `parse'
/Users/rogerluan/Documents/Projects/tellus-ios/.vendor/ruby/2.6.0/gems/json-2.3.1/lib/json/common.rb:263:in `parse': 784: unexpected token at '' (JSON::ParserError)
[18:59:41]: ▸ sh: line 1: 37728 Illegal instruction: 4  ./fastlane/FastlaneRunner lane submit version 2.30.14 swiftServerPort 2000 > /dev/null
#<Thread:0x00007fa552637e10@/Users/rogerluan/Documents/Projects/tellus-ios/.vendor/ruby/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/swift_lane_manager.rb:96 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	4: from /Users/rogerluan/Documents/Projects/tellus-ios/.vendor/ruby/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/swift_lane_manager.rb:97:in `block in cruise_swift_lane_in_thread'
	3: from /Users/rogerluan/Documents/Projects/tellus-ios/.vendor/ruby/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
	2: from /Users/rogerluan/Documents/Projects/tellus-ios/.vendor/ruby/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	1: from /Users/rogerluan/Documents/Projects/tellus-ios/.vendor/ruby/2.6.0/gems/fastlane-2.160.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/rogerluan/Documents/Projects/tellus-ios/.vendor/ruby/2.6.0/gems/fastlane-2.160.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': Exit status of command './fastlane/FastlaneRunner lane submit version 2.30.14 swiftServerPort 2000 > /dev/null' was 132 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /Users/rogerluan/Documents/Projects/tellus-ios/fastlane/swift/LaneFileProtocol.swift, line 121
sh: line 1: 37728 Illegal instruction: 4  ./fastlane/FastlaneRunner lane submit version 2.30.14 swiftServerPort 2000 > /dev/null
+-----------+--------+
|    Lane Context    |
+-----------+--------+
| LANE_NAME | submit |
+-----------+--------+
[18:59:41]: 784: unexpected token at ''
[18:59:41]: fastlane finished with errors
</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                           |
| --------------------------- | --------------------------------------------------------------- |
| OS                          | 10.15.6                                                         |
| Ruby                        | 2.6.5                                                           |
| Bundler?                    | true                                                            |
| Git                         | git version 2.24.3 (Apple Git-128)                              |
| Installation Source         | ~/Documents/Projects/tellus-ios/.vendor/ruby/2.6.0/bin/fastlane |
| Host                        | Mac OS X 10.15.6 (19G2021)                                      |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.5/lib                                     |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                                     |
| Is contained                | false                                                           |
| Is homebrew                 | false                                                           |
| Is installed via Fabric.app | false                                                           |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                     |
| Xcode Version               | 11.5                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

```ruby
<redacted>

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.160.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| bundler                   | 2.1.4        |
| rake                      | 13.0.1       |
| CFPropertyList            | 3.0.2        |
| ZenTest                   | 4.12.0       |
| RubyInline                | 3.12.5       |
| concurrent-ruby           | 1.1.6        |
| i18n                      | 0.9.5        |
| minitest                  | 5.14.1       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.7        |
| activesupport             | 4.2.11.3     |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| httpclient                | 2.8.3        |
| json                      | 2.3.1        |
| algoliasearch             | 1.27.3       |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.373.0      |
| aws-sigv4                 | 1.2.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.107.0      |
| aws-sdk-kms               | 1.38.0       |
| aws-sdk-s3                | 1.81.0       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| netrc                     | 0.11.0       |
| ffi                       | 1.13.1       |
| ethon                     | 0.12.0       |
| typhoeus                  | 1.4.0        |
| cocoapods-core            | 1.9.3        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.3.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| cocoapods-trunk           | 1.5.0        |
| cocoapods-try             | 1.2.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.18.0       |
| cocoapods                 | 1.9.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| cocoapods-binary          | 0.4.4        |
| dotenv                    | 2.7.6        |
| osx_keychain              | 1.0.2        |
| cocoapods-keys            | 2.2.1        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| emoji_regex               | 3.0.0        |
| excon                     | 0.76.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 1.0.1        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| jwt                       | 2.2.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| signet                    | 0.14.0       |
| googleauth                | 0.13.1       |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.28.0       |
| mini_magick               | 4.10.1       |
| plist                     | 3.5.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| xcpretty-travis-formatter | 1.0.0        |
| mustache                  | 1.1.1        |
| open4                     | 1.3.4        |
| redcarpet                 | 3.5.0        |
| sassc                     | 2.4.0        |
| sqlite3                   | 1.4.2        |
| liferaft                  | 0.0.6        |
| xcinvoke                  | 0.3.0        |
| jazzy                     | 0.13.4       |
</details>

*generated on:* **2020-09-18**
</details></pre>
</details>

**Comment by jhandguy** [comment]
Also experiencing this issue, cannot update to `2.159.0` 😱 
This is quite a critical one actually @joshdholtz & @minuscorp you might want to take a look at the linked PR 🚀
