### ISSUE TITLE
Problem with upload_symbols_to_crashlytics by using SPM Firebase Crashlytics

### ISSUE THREAD

**Issue by StefaniOSApps** [fastlane/fastlane#17279]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
 I may be describing more of a question than a problem (sorry :D), but ... it will affect a large number of users, so i would like to see the solution written in the readme (bug = missing information). 

Many users use Fastlane together with Firebase Crashlytics. DSYMs can be uploaded here. The path to `.../FirebaseCrashlytics/upload-symbols` is required for this. If someone uses prebuild cocoapods, the path is quite easy `./Pods/_Prebuild/FirebaseCrashlytics/upload-symbols`.

However, with `SPM` it is a bit more demanding. What is the local path when integrating Crashlytics with SPM?

**`Failed to find Fabric's upload_symbols binary at /Applications/Fabric.app/**/upload-symbols or ./Pods/**/upload-symbols. Please specify the location of the binary explicitly by using the binary_path option`**

If you need more information - no problem.

**Comment by max-ott** [comment]
Please use discussions for questions: https://github.com/fastlane/fastlane/issues/16811
