### ISSUE TITLE
Not Found error during produce & upload_to_testflight on itunes connect

### ISSUE THREAD

**Issue by AbdullahDiaa** [fastlane/fastlane#17292]
### New Issue Checklist

- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] Updated fastlane to the latest version
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Running `produce` command fails for itc, running same command with `skip_itc: true,` works perfectly, it happens also with `upload_to_testflight` command

##### Command executed

```    produce(
      app_identifier: "com.app",
      app_name: "APP",
      enable_services: {
        push_notification: "on"
      }     
    )

     upload_to_testflight
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 💥   | produce          | 4           |
+------+------------------+-------------+

[01:09:42]: fastlane finished with errors

  <pre> Looking for related GitHub issues on fastlane/fastlane...

Traceback (most recent call last):
	19: from /usr/local/Cellar/fastlane/2.160.0/libexec/bin/fastlane:23:in `<main>'
	18: from /usr/local/Cellar/fastlane/2.160.0/libexec/bin/fastlane:23:in `load'
	17: from /usr/local/Cellar/fastlane/2.160.0/libexec/gems/fastlane-2.160.0/bin/fastlane:23:in `<top (required)>'
	16: from /usr/local/Cellar/fastlane/2.160.0/libexec/gems/fastlane-2.160.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	15: from /usr/local/Cellar/fastlane/2.160.0/libexec/gems/fastlane-2.160.0/produce/lib/produce/commands_generator.rb:16:in `start'
	14: from /usr/local/Cellar/fastlane/2.160.0/libexec/gems/fastlane-2.160.0/produce/lib/produce/commands_generator.rb:233:in `run'
	13: from /usr/local/Cellar/fastlane/2.160.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	12: from /usr/local/Cellar/fastlane/2.160.0/libexec/gems/fastlane-2.160.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	11: from /usr/local/Cellar/fastlane/2.160.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	10: from /usr/local/Cellar/fastlane/2.160.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 9: from /usr/local/Cellar/fastlane/2.160.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 8: from /usr/local/Cellar/fastlane/2.160.0/libexec/gems/fastlane-2.160.0/produce/lib/produce/commands_generator.rb:40:in `block (2 levels) in run'
	 7: from /usr/local/Cellar/fastlane/2.160.0/libexec/gems/fastlane-2.160.0/produce/lib/produce/manager.rb:12:in `start_producing'
	 6: from /usr/local/Cellar/fastlane/2.160.0/libexec/gems/fastlane-2.160.0/produce/lib/produce/itunes_connect.rb:14:in `run'
	 5: from /usr/local/Cellar/fastlane/2.160.0/libexec/gems/fastlane-2.160.0/spaceship/lib/spaceship/connect_api/spaceship.rb:82:in `login'
	 4: from /usr/local/Cellar/fastlane/2.160.0/libexec/gems/fastlane-2.160.0/spaceship/lib/spaceship/connect_api/client.rb:66:in `login'
	 3: from /usr/local/Cellar/fastlane/2.160.0/libexec/gems/fastlane-2.160.0/spaceship/lib/spaceship/tunes/tunes_client.rb:78:in `select_team'
	 2: from /usr/local/Cellar/fastlane/2.160.0/libexec/gems/fastlane-2.160.0/spaceship/lib/spaceship/client.rb:71:in `teams'
	 1: from /usr/local/Cellar/fastlane/2.160.0/libexec/gems/fastlane-2.160.0/spaceship/lib/spaceship/client.rb:126:in `user_details_data'
/usr/local/Cellar/fastlane/2.160.0/libexec/gems/fastlane-2.160.0/spaceship/lib/spaceship/client.rb:719:in `parse_response': \e[31m[!]  (Spaceship::UnexpectedResponse)
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        body {
            font-family: "Helvetica Neue", "HelveticaNeue", Helvetica, Arial, sans-serif;
            font-size: 15px;
            font-weight: 200;
            line-height: 20px;
            color: #4c4c4c;
            text-align: center;
        }

        .section {
            margin-top: 50px;
        }
    </style>
</head>
<body>
<div class="section">
    <h1>&#63743;</h1>

    <h3>Not Found</h3>
    <p>The requested page could not be found.</p>
</div>
</body>
</html>

</pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 10.15.6                                                 |
| Ruby                        | 2.7.1                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.24.3 (Apple Git-128)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.160.0/libexec/bin/fastlane |
| Host                        | Mac OS X 10.15.6 (19G2021)                              |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.7.1_2/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1f  31 Mar 2020                             |
| Is contained                | false                                                   |
| Is homebrew                 | false                                                   |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 12.0                                                    |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.160.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.18.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.76.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.2        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-storage      | 1.28.0       |
| emoji_regex               | 3.0.0        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.370.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.107.0      |
| aws-sdk-kms               | 1.38.0       |
| aws-sdk-s3                | 1.81.0       |
| uri                       | 0.10.0       |
| forwardable               | 1.3.1        |
| logger                    | 1.4.2        |
| cgi                       | 0.1.0        |
| timeout                   | 0.1.0        |
| stringio                  | 0.1.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.2.0        |
| strscan                   | 1.0.3        |
| date                      | 3.0.0        |
| delegate                  | 0.1.0        |
| fileutils                 | 1.4.1        |
| io-console                | 0.5.6        |
| zlib                      | 1.1.0        |
| singleton                 | 0.1.0        |
| rexml                     | 3.2.3        |
| open3                     | 0.1.0        |
| yaml                      | 0.1.0        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.6.0        |
</details>

*generated on:* **2020-09-22**
</details>

**Comment by skrivitsky** [comment]
I have the same issue.

**Comment by tgalg** [comment]
I am seeing a similar error when just executing `client.teams` 

`Traceback (most recent call last):
        9: from /usr/bin/irb:23:in `<main>'
        8: from /usr/bin/irb:23:in `load'
        7: from /Library/Ruby/Gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        6: from (irb):4
        5: from (irb):4:in `rescue in irb_binding'
        4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/tunes/tunes_client.rb:78:in `select_team'
        3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/client.rb:69:in `teams'
        2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/client.rb:124:in `user_details_data'
        1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/client.rb:716:in `parse_response'
Spaceship::UnexpectedResponse ()
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        body {
            font-family: "Helvetica Neue", "HelveticaNeue", Helvetica, Arial, sans-serif;
            font-size: 15px;
            font-weight: 200;
            line-height: 20px;
            color: #4c4c4c;
            text-align: center;
        }

        .section {
            margin-top: 50px;
        }
    </style>
</head>
<body>
<div class="section">
    <h1>&#63743;</h1>

    <h3>Not Found</h3>
    <p>The requested page could not be found.</p>
</div>
</body>
</html>
`
### Stack

Key | Value
-- | --
OS | 10.15.6
Ruby | 2.6.3p62
Bundler? | false
Git | git version 2.24.3 (Apple Git-128)
Xcode Version | 11.7

**Comment by StefaniOSApps** [comment]
#17293

**Comment by StefaniOSApps** [comment]
I think the bug is gone. It works again for me. I'm not sure if it has something to do with doing the following:
```
gem update
gem cleanup
bundle update
bundle exec fastlane
```

**Comment by AbdullahDiaa** [comment]
I can confirm too bug has been fixed, seems to be **an issue on apple servers** and they fixed it.
