### ISSUE TITLE
"The requested page could not be found." HTML error returned when running download_dsyms

### ISSUE THREAD

**Issue by lukewlms** [fastlane/fastlane#17293]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I get a full HTML page error as a result when running `fastlane run download_dsyms`.  I've attempted to set the version number etc. specifically but I still get the same error below.

I also found [this issue](https://github.com/fastlane/fastlane/issues/13094) which notes that a similar error could be related to outages on Apple's side, but there's currently no issue with my logging into App Store Connect.

Other Fastlane commands seem to work ok and we just delivered a new app version with Fastlane on Friday.  

I've also verified that the dSYM is available for download in App Store Connect (App -> Activity -> General Information -> Download dSYM).  So I can work around this for now by manually downloading, then uploading via [Sentry CLI](https://docs.sentry.io/clients/cocoa/dsym/#use-sentry-cli).

```
[17:32:08]: ----------------------------
[17:32:08]: --- Step: download_dsyms ---
[17:32:08]: ----------------------------
[17:32:08]: Login to App Store Connect (lukecwilliams@gmail.com)

Looking for related GitHub issues on fastlane/fastlane...

Traceback (most recent call last):
	25: from /usr/local/bin/fastlane:23:in `<main>'
	24: from /usr/local/bin/fastlane:23:in `load'
	23: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/bin/fastlane:23:in `<top (required)>'
	22: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	21: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	20: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	19: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	17: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	16: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	15: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/commands_generator.rb:224:in `block (2 levels) in run'
	13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/one_off.rb:22:in `execute'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/one_off.rb:42:in `run'
	11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	 8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/actions/download_dsyms.rb:18:in `run'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/spaceship/lib/spaceship/connect_api/spaceship.rb:82:in `login'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/spaceship/lib/spaceship/connect_api/client.rb:66:in `login'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/spaceship/lib/spaceship/tunes/tunes_client.rb:78:in `select_team'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/spaceship/lib/spaceship/client.rb:71:in `teams'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/spaceship/lib/spaceship/client.rb:126:in `user_details_data'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.160.0/spaceship/lib/spaceship/client.rb:719:in `parse_response': [!]  (Spaceship::UnexpectedResponse)
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        body {
            font-family: "Helvetica Neue", "HelveticaNeue", Helvetica, Arial, sans-serif;
            font-size: 15px;
            font-weight: 200;
            line-height: 20px;
            color: #4c4c4c;
            text-align: center;
        }

        .section {
            margin-top: 50px;
        }
    </style>
</head>
<body>
<div class="section">
    <h1>&#63743;</h1>

    <h3>Not Found</h3>
    <p>The requested page could not be found.</p>
</div>
</body>
</html>

```

##### Command executed
→ `fastlane run download_dsyms`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 

### Environment

<details>
  <pre> 

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.6                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.6 (19G2021)                                     |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.0                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.55.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "mobile2mr") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "mobile2mr") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

lane :upload_symbols do
  download_dsyms
#  upload_symbols_to_sentry(...)
end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "***2mr" # The bundle identifier of your app
apple_id "***@gmail.com" # Your Apple email address

team_id "***" # Developer Portal Team ID

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.160.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.17.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.76.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-storage      | 1.28.0       |
| emoji_regex               | 3.0.0        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.372.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.107.0      |
| aws-sdk-kms               | 1.38.0       |
| aws-sdk-s3                | 1.81.0       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-09-21**

 </pre>
</details>

**Comment by reubits** [comment]
I'm having the same issue with the `pilot upload` command

**Comment by AbdullahDiaa** [comment]
issue should be fixed now, it seems to be an issue with Apple servers.

**Comment by lukewlms** [comment]
Can confirm this is working for me now.  I'd suggest adding a more descriptive error message here in Fastlane so it's not just an abstract webpage error result if Apple server can't be contacted.

**Comment by orlandogrodriguez** [comment]
I'm glad it was just an Apple issue, but I recall checking their (useless) system status page when I ran into these issues a couple of days ago and everything was green. A more descriptive message would be awesome, considering Apple's tendency to flake intermittently without letting anyone know.
