### ISSUE TITLE
[deliver] IDFA settings for new AppStore Connect API should be changed to top-level Bool param

### ISSUE THREAD

**Issue by Kaspik** [fastlane/fastlane#17300]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I think it would be nice to change how `deliver` uses parameter for IDFA. I'm aware of:
```
submission_information: {
   add_id_info_uses_idfa: false
}
```
but I believe it shouldn't be like that anymore. Previously IDFA was accepted/declined during submission, now it lives on the same level as Ratings, Phased rollout etc:
![Screen Shot 2020-09-23 at 0 50 16](https://user-images.githubusercontent.com/7204168/93945208-c138ae00-fd36-11ea-8ece-f3fda4914ad5.png)

We do have `phased_release` (`true`/`false`), we do have `reset_ratings` (`true`/`false`), we do have `automatic_release` (`true`/`false`) - is there an option to change the IDFA to be also just simple `true`/`false` top-level param, not part of extended dictionary? :) If that already exists in the new AppStore Connect API, then http://docs.fastlane.tools/actions/deliver/#deliver is outdated.

Thanks!

**Comment by Kaspik** [comment]
Let me know @joshdholtz what you think about this or if I'm missing something. :)

**Comment by max-ott** [comment]
It's definitely already implemented with the new `ConnectAPI`: https://github.com/fastlane/fastlane/blob/ab1c5a59cdf3bebd765d976eaaae5b50517bb451/spaceship/lib/spaceship/connect_api/models/idfa_declaration.rb

Docs need a rework on every end, so any support is welcome! 🙏

**Comment by Kaspik** [comment]
Needs docs updated. Will try over the weekend.

**Comment by joshdholtz** [comment]
@Kaspik I'm going to make a new `idfa` option this week and fixes this and then I will update the docs and add migration stuff 💪

**Comment by Kaspik** [comment]
Thanksss!

**Comment by Kaspik** [comment]
@joshdholtz Did this get fixed? :)

**Comment by joshdholtz** [comment]
@Kaspik Not yet 😞 I working on finishing up support for the new App Data Usage stuff that is going to be required here soon and then I should be able to get to this
