### ISSUE TITLE
AppStore demo account data not persisting with deliver

### ISSUE THREAD

**Issue by reishka** [fastlane/fastlane#17309]
Running fastlane version 2.160.0

Our apps require a demo account for apple review. We do not store the demo account credentials in our repository, and we don't supply the credentials along with metadata. Previously, when we did not supply a demo username or password, the existing username and password carried over to the edit version from the live version. This worked well for us. 

Now, it seems that when we upload metadata without the demo username or password, the username and password gets wiped out from the edit version (not carried over), and we have to go in and manually add it back it. We have about 150 branded apps, so this approach really isn't feasible. 

We're uploading the metadata by providing text files in metadata folders with upload_to_app_store. We don't have demo_username and demo_password files. 

I've tried adding empty files and I've tried adding the demo_account_required:true flag to upload_to_app_store, to no avail. 

Thoughts?

**Comment by max-ott** [comment]
AFAIK this is a change from Apple with the "new" App Store Connect. Username and Password do not seem to get persisted anymore. (Observed on ASC without using `deliver`). So I don't think this is a `fastlane` issue, but rather how Apple is handling this now.

**Comment by reishka** [comment]
@max-ott I'm actually not experiencing that same behaviour. If I log into ASC and create a new edit version from a live version that has demo account credentials & the "sign in required" box ticked, the credentials get carried forward along with the other metadata. (I reconfirmed this just now)

I also notice that if I set demo account credentials in an edit version (& tick the sign-in box), and then upload new metadata (without credentials), the demo account credentials get wiped out, which was not behaviour we experienced previously.

**Comment by TragedyStar** [comment]
@reishka I found the bug, and created a pr #17302

**Comment by reishka** [comment]
@TragedyStar That appears to have fixed an issue with uploading demo credentials, but existing credentials in an edit version still get wiped out if I upload metadata that doesn't contain a demo username/password. Just tried with fastlane ver 2.162.0

**Comment by TragedyStar** [comment]
> @TragedyStar That appears to have fixed an issue with uploading demo credentials, but existing credentials in an edit version still get wiped out if I upload metadata that doesn't contain a demo username/password. Just tried with fastlane ver 2.162.0

Oh, yes. We need another fix. The review attachment also be wiped out if upload metadata doesn't contain it.

I don't use `--skip_metadata` because I need create a phased release.
