### ISSUE TITLE
[deliver] Is there a way to set empty string for metadata ?

### ISSUE THREAD

**Issue by lanyutc** [fastlane/fastlane#17303]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
No change for the appStore, when I set an empty string to subtitle.txt and upload it to appStore by deliver

##### Command executed
fastlane deliver

### Environment

<details>
  <pre> fastlane 2.160.0 </pre>
</details>

I want to set empty string for some metadata, but deliver ignored uploading them.

**Comment by max-ott** [comment]
Please use discussions as per #16811 for questions.
