### ISSUE TITLE
supply init throws Google Api Error:  Invalid value at 'image_type' (TYPE_ENUM), "promoGraphic"

### ISSUE THREAD

**Issue by pal** [fastlane/fastlane#17327]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm trying to setup supply using the guide at https://docs.fastlane.tools/getting-started/android/setup/#setting-up-supply
I have already uploaded a version manually successfully, but get hit with an error when initializing supply.

##### Command executed
`bundle exec fastlane supply init`

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>[✔] 🚀 
[11:47:07]: 🕗  Downloading metadata, images, screenshots...
[11:47:09]: 📝  Downloading metadata (sv-SE)
[11:47:09]: Writing to fastlane/metadata/android/sv-SE/title.txt...
[11:47:09]: Writing to fastlane/metadata/android/sv-SE/short_description.txt...
[11:47:09]: Writing to fastlane/metadata/android/sv-SE/full_description.txt...
[11:47:09]: Writing to fastlane/metadata/android/sv-SE/video.txt...
[11:47:09]: 🖼️  Downloading images (sv-SE)
[11:47:09]: Downloading `featureGraphic` for sv-SE...
[11:47:09]: 	Downloaded - fastlane/metadata/android/sv-SE/images/featureGraphic.png
[11:47:09]: Downloading `icon` for sv-SE...
[11:47:11]: 	Downloaded - fastlane/metadata/android/sv-SE/images/icon.png
[11:47:11]: Downloading `promoGraphic` for sv-SE...
[11:47:11]: Google Api Error: invalid: Invalid value at 'image_type' (TYPE_ENUM), "promoGraphic" - Invalid value at 'image_type' (TYPE_ENUM), "promoGraphic"
[11:47:11]: Error downloading 'promoGraphic' for sv-SE...
[11:47:11]: Downloading `tvBanner` for sv-SE...
[11:47:11]: Downloading `phoneScreenshots` for sv-SE...
[11:47:13]: 	Downloaded - fastlane/metadata/android/sv-SE/images/phoneScreenshots/1_sv-SE.png
[11:47:14]: 	Downloaded - fastlane/metadata/android/sv-SE/images/phoneScreenshots/2_sv-SE.png
[11:47:14]: 	Downloaded - fastlane/metadata/android/sv-SE/images/phoneScreenshots/3_sv-SE.png
[11:47:14]: Downloading `sevenInchScreenshots` for sv-SE...
[11:47:15]: Downloading `tenInchScreenshots` for sv-SE...
[11:47:15]: Downloading `tvScreenshots` for sv-SE...
[11:47:15]: Downloading `wearScreenshots` for sv-SE...

[!] Unable to find latest version information from "production" track. Please specify track information by using the '--track' option.
</pre>
</details>

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.6                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.28.0                                             |
| Installation Source         | /Library/Ruby/Gems/2.6.0/bin/fastlane                          |
| Host                        | Mac OS X 10.15.6 (19G2021)                                     |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.0.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
package_name("nu.myapp.mobile") # e.g. com.krausefx.app
json_key_file "fastlane/service-account-key.json"

```
</details>

### fastlane gems

| Gem        | Version | Update-Status |
| ---------- | ------- | ------------- |
| fastlane   | 2.160.0 | ✅ Up-To-Date  |
| screengrab | 1.0.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| bundler                   | 2.1.4        |
| rake                      | 13.0.1       |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.376.0      |
| aws-sigv4                 | 1.2.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.108.0      |
| aws-sdk-kms               | 1.38.0       |
| aws-sdk-s3                | 1.81.1       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.0.0        |
| excon                     | 0.76.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 1.0.1        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.2.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| signet                    | 0.14.0       |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.0       |
| json                      | 2.3.1        |
| mini_magick               | 4.10.1       |
| plist                     | 3.5.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.18.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2020-09-28**
</details>

**Comment by curt-tophatter** [comment]
I am encountering this error as well.

**Comment by frozenzia** [comment]
We have this problem as well, but don't have a promographic.png in metadata which we could delete. Any other ideas?

**Comment by curt-tophatter** [comment]
FWIW the graphic I deleted was actually named `promoGraphic.jpeg`.

**Comment by goodpic** [comment]
Hello, I am having the same error and there is no promoGraphic in the directory.
If I set to skip uploading metadata and images in Fastfile, I could upload the build without any issue.

Do you know how I can prevent Supply to try to download promoGraphic?

## Workaround in Fastfile
```
desc "Submit a new beta build"
  lane :beta do
    gradle(task: "clean assembleRelease")

    upload_to_play_store(
      track: "alpha", # production, beta, alpha, internal
      skip_upload_images: true,
      skip_upload_metadata: true,
      skip_upload_screenshots: true,
    )
  end
```

## Error when "supply init"

```
❯ rm -Rf fastlane/metadata/android
❯ fastlane supply init
[14:40:08]: Downloading `promoGraphic` for en-GB...
[14:40:09]: Google Api Error: invalid: Invalid value at 'image_type' (type.googleapis.com/google.play.publishingapi.v3.AppImageType), "promoGraphic" - Invalid value at 'image_type' (type.googleapis.com/google.play.publishingapi.v3.AppImageType), "promoGraphic"
[14:40:09]: Error downloading 'promoGraphic' for en-GB...
```

```
$ fastlane beta

[14:14:09]: Preparing apk at path '/Users/jun/workspace/build-sample/android/app/build/outputs/apk/release/app-release.apk' for upload...
[14:14:57]: 	Version Code: 12
[14:14:57]: Updating track 'alpha'...
[14:14:59]: Preparing to upload for language 'en-GB'...
[14:15:00]: Uploading image file ./fastlane/metadata/android/en-GB/images/featureGraphic.png...
[14:15:02]: Uploading image file ./fastlane/metadata/android/en-GB/images/icon.png...
[14:15:08]: Uploading screenshot ./fastlane/metadata/android/en-GB/images/phoneScreenshots/1_en-GB.png...
[14:15:10]: Uploading screenshot ./fastlane/metadata/android/en-GB/images/phoneScreenshots/2_en-GB.png...
[14:15:15]: Uploading screenshot ./fastlane/metadata/android/en-GB/images/sevenInchScreenshots/1_en-GB.png...
[14:15:19]: Uploading screenshot ./fastlane/metadata/android/en-GB/images/tenInchScreenshots/1_en-GB.png...
[14:15:21]: Could not find changelog for '12' and language 'en-GB' at path ./fastlane/metadata/android/en-GB/changelogs/12.txt...
[14:15:22]: Uploading all changes to Google Play...
+-------------------------------------+---------------------------------------------------+
|                                      Lane Context                                       |
+-------------------------------------+---------------------------------------------------+
| DEFAULT_PLATFORM                    | android                                           |
| PLATFORM_NAME                       | android                                           |
| LANE_NAME                           | android beta                                      |
| GRADLE_ALL_APK_OUTPUT_PATHS         | ["/Users/jun/workspace/build-sample/androi  |
|                                     | d/app/build/outputs/apk/release/app-release.apk"  |
|                                     | ]                                                 |
| GRADLE_ALL_AAB_OUTPUT_PATHS         | []                                                |
| GRADLE_ALL_OUTPUT_JSON_OUTPUT_PATHS | []                                                |
| GRADLE_ALL_MAPPING_TXT_OUTPUT_PATHS | []                                                |
| GRADLE_APK_OUTPUT_PATH              | /Users/jun/workspace/build-sample/android/  |
|                                     | app/build/outputs/apk/release/app-release.apk     |
+-------------------------------------+---------------------------------------------------+
[14:15:58]: Google Api Error: Server error - Internal error encountered.

```

```
❯ fastlane --version
fastlane installation at path:
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.165.0/bin/fastlane
-----------------------------
[✔] 🚀
fastlane 2.165.0
❯ fastlane --env
```

**Comment by NathHorrigan** [comment]
@goodpic Did you find a work around for this?

**Comment by max-ott** [comment]
Could you please try using my branch over at https://github.com/fastlane/fastlane/pull/17518 and see if this solves the problem? Unfortunately we're not using `supply`, so I cannot test this. Make sure to use the correct gem in your `gemfile`:

`gem "fastlane", github: "fastlane/fastlane", branch: 'max-ott-patch-2-1'

**Comment by goodpic** [comment]
Sorry for my late reply @NathHorrigan and @max-ott 
I tried the current master branch which #17518 has been already merged and the issue was solved!
Thank you again for your help.

**Comment by rogerluan** [comment]
Looks like https://github.com/fastlane/fastlane/pull/17518 resolved this issue 😊 Thanks for contributing, everyone!
