### ISSUE TITLE
Fastlane crashes if HOME is not accessible

### ISSUE THREAD

**Issue by aberaud** [fastlane/fastlane#17325]
### Issue Description
**What's happening**: Fastlane crashes if HOME is not accessible or even just not writable.

**Expected behavior**: While this behavior might be relevant for "hand-made" runs of fastlane, fastlane is an automation tool that should have an appropriate behavior for CI systems.

The expected behavior is that fastlane should **fallback properly without crashing** if the HOME directory is not accessible or not available, or **provide an explicit command line option** to not read/write in the HOME directory - or any other directory outside of the project directory.

##### Command executed

`fastlane beta`
Any fastlane command would try to access and write to HOME.

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>
+ fastlane beta
[02:49:04]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m

Looking for related GitHub issues on fastlane/fastlane...

Looking for related GitHub issues on fastlane/fastlane...

➡️  [33mPermission denied @ dir_s_mkdir - /var/empty/.fastlane[0m (Errno::EACCES)[0m
    https://github.com/fastlane/fastlane/issues/15989 [[32mclosed[0m] 7 💬
    02 Jul 2020

➡️  [33mPermission Issue with fastlane through Jenkins (`/` is not writable.)[0m
    https://github.com/fastlane/fastlane/issues/16012 [[32mclosed[0m] 4 💬
    23 May 2020

➡️  [33mmkdir issue when running tests with scan in lockdown folder[0m
    https://github.com/fastlane/fastlane/issues/12585 [[32mclosed[0m] 2 💬
    01 Sep 2018

/usr/lib/ruby/2.5.0/fileutils.rb:232:in `mkdir': [31m[!] Permission denied @ dir_s_mkdir - /var/lib/jenkins[0m (Errno::EACCES)
	from /usr/lib/ruby/2.5.0/fileutils.rb:232:in `fu_mkdir'
	from /usr/lib/ruby/2.5.0/fileutils.rb:210:in `block (2 levels) in mkdir_p'
	from /usr/lib/ruby/2.5.0/fileutils.rb:208:in `reverse_each'
	from /usr/lib/ruby/2.5.0/fileutils.rb:208:in `block in mkdir_p'
	from /usr/lib/ruby/2.5.0/fileutils.rb:193:in `each'
	from /usr/lib/ruby/2.5.0/fileutils.rb:193:in `mkdir_p'
	from /var/lib/gems/2.5.0/gems/fastlane-2.160.0/fastlane_core/lib/fastlane_core/module.rb:28:in `fastlane_user_dir'
	from /var/lib/gems/2.5.0/gems/fastlane-2.160.0/fastlane_core/lib/fastlane_core/analytics/analytics_session.rb:58:in `did_show_message?'
	from /var/lib/gems/2.5.0/gems/fastlane-2.160.0/fastlane_core/lib/fastlane_core/analytics/analytics_session.rb:22:in `action_launched'
	from /var/lib/gems/2.5.0/gems/fastlane-2.160.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
	from /var/lib/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /var/lib/gems/2.5.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	from /var/lib/gems/2.5.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /var/lib/gems/2.5.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /var/lib/gems/2.5.0/gems/fastlane-2.160.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
</pre>
</details>

**Comment by aberaud** [comment]
Relevant issues: https://github.com/fastlane/fastlane/issues/16012 https://github.com/fastlane/fastlane/issues/15989

**Comment by aberaud** [comment]
This issue is still a problem. Please consider it.

Also `fastlane env` is irrelevant for this bug report.

**Comment by rogerluan** [comment]
I think this is a valid request. 

I looked into the code and found at least 3 places that are accessing HOME (via `fastlane_user_dir`): analytics (`faslane_core`), frameit tmp folder (`frameit`), and cookies caching (`spaceship`).
As of today you can avoid accessing HOME via`spaceship` by setting the env var `SPACESHIP_COOKIE_PATH`.
You can avoid accessing HOME via analytics by setting the env var `FASTLANE_OPT_OUT_USAGE` to true (although I discourage doing this because analytics help us improve _fastlane_).
And if you're not using frameit, it won't access HOME.

This can be a quick workaround for you.

However, I do think this problem should be properly fixed when time allows.

Hope this helps you @aberaud !

**Comment by aberaud** [comment]
👍

**Comment by rogerluan** [comment]
@aberaud did you try the workaround I mentioned? Did it work for you? lmk! 🤗

**Comment by aberaud** [comment]
Thank you for the followup ! I found a workaround :)

If someone have some time to work on this issue,
it would be a nice default behavior to not crash in case of a read-only/sandboxed build environnement. For instance, for a preference file, using the default preference value instead of crashing (so analytics could be sent by default if FASTLANE_OPT_OUT_USAGE is not used).
