### ISSUE TITLE
Fastlane match development -> undefined method `com' for nil:NilClass\e[0m (NoMethodError)

### ISSUE THREAD

**Issue by gilgamesharcadia** [fastlane/fastlane#17320]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Command executed
```fastlane match development```

##### Complete output when running fastlane, including the stack trace and command used
```
Traceback (most recent call last):
	18: from /Users/Admin/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `<main>'
	17: from /Users/Admin/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `eval'
	16: from /Users/Admin/.rvm/gems/ruby-2.7.0/bin/fastlane:23:in `<main>'
	15: from /Users/Admin/.rvm/gems/ruby-2.7.0/bin/fastlane:23:in `load'
	14: from /Users/Admin/.rvm/gems/ruby-2.7.0/gems/fastlane-2.160.0/bin/fastlane:23:in `<top (required)>'
	13: from /Users/Admin/.rvm/gems/ruby-2.7.0/gems/fastlane-2.160.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	12: from /Users/Admin/.rvm/gems/ruby-2.7.0/gems/fastlane-2.160.0/match/lib/match/commands_generator.rb:25:in `start'
	11: from /Users/Admin/.rvm/gems/ruby-2.7.0/gems/fastlane-2.160.0/match/lib/match/commands_generator.rb:187:in `run'
	10: from /Users/Admin/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	 9: from /Users/Admin/.rvm/gems/ruby-2.7.0/gems/fastlane-2.160.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 8: from /Users/Admin/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 7: from /Users/Admin/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 6: from /Users/Admin/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 5: from /Users/Admin/.rvm/gems/ruby-2.7.0/gems/fastlane-2.160.0/match/lib/match/commands_generator.rb:66:in `block (3 levels) in run'
	 4: from /Users/Admin/.rvm/gems/ruby-2.7.0/gems/fastlane-2.160.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:172:in `load_configuration_file'
	 3: from /Users/Admin/.rvm/gems/ruby-2.7.0/gems/fastlane-2.160.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:172:in `new'
	 2: from /Users/Admin/.rvm/gems/ruby-2.7.0/gems/fastlane-2.160.0/fastlane_core/lib/fastlane_core/configuration/configuration_file.rb:46:in `initialize'
	 1: from /Users/Admin/.rvm/gems/ruby-2.7.0/gems/fastlane-2.160.0/fastlane_core/lib/fastlane_core/configuration/configuration_file.rb:46:in `eval'
(eval):8:in `initialize': \e[31m[!] undefined method `com' for nil:NilClass\e[0m (NoMethodError)
```
<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.7.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.21.1 (Apple Git-122.3)        |
| Installation Source         | ~/.rvm/gems/ruby-2.7.0/bin/fastlane         |
| Host                        | Mac OS X 10.14.6 (18G103)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.7.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.3.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | es_ES.UTF-8 | ✅ |
| LC_ALL   | es_ES.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
require 'fileutils'

def create_directory(path) 
  FileUtils.mkdir_p path
  # system 'mkdir', '-p', path
end

$fastlane_generated_path = "#{ENV['HOME']}/Desktop/fastlane"
$logs_directory_path = "#{$fastlane_generated_path}/logs"
$ipa_directory_path = "#{$fastlane_generated_path}/ipa"
$cert_directory_path = "#{$fastlane_generated_path}/cert"
$provisioning_profile_directory_path = "#{$fastlane_generated_path}/provisioningProfile"

def publish_testflight(scheme) 
    puts "Publishing Testflight #{scheme}..."

    create_directory $logs_directory_path
    create_directory $ipa_directory_path
    create_directory $cert_directory_path
    create_directory $provisioning_profile_directory_path
    ipa_file_path = "#{$ipa_directory_path}/#{scheme}.ipa"

    get_certificates(output_path: $cert_directory_path)
    get_provisioning_profile(output_path: $provisioning_profile_directory_path)
    build_app(scheme: scheme, output_directory: $ipa_directory_path, output_name: scheme)
    upload_to_testflight(ipa: ipa_file_path, skip_waiting_for_build_processing: true)
end

default_platform(:ios)

platform :ios do
  lane :foo do
      publish_testflight "Foo"
  end
end


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id 'hardcoded'
app_identifier 'hardcoded'
team_id 'hardcoded'
itc_team_id 'hardcoded'
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.160.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| rake                      | 13.0.1       |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.375.0      |
| aws-sigv4                 | 1.2.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.107.0      |
| aws-sdk-kms               | 1.38.0       |
| aws-sdk-s3                | 1.81.0       |
| babosa                    | 1.0.3        |
| bundler                   | 2.1.2        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.0.0        |
| excon                     | 0.76.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 1.0.1        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.2.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| signet                    | 0.14.0       |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.0       |
| json                      | 2.3.1        |
| mini_magick               | 4.10.1       |
| plist                     | 3.5.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.18.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2020-09-25**
</details>

<details>

I'm trying to store the iOS provisioning profiles and certificates in a GitLab repository
by running the command `fastlane match development` or `fastlane match appstore` and I'm getting
the error above every time.

</details>

**Comment by anh1979** [comment]
Perhaps related to #17400? Just a guess.

**Comment by rogerluan** [comment]
@gilgamesharcadia was this resolved? Could you update _fastlane_ to the latest version and try again? 🙏

**Comment by eamonn-alphin** [comment]
this is an issue for me

**Comment by rogerluan** [comment]
Seems like fastlane is throwing an issue when parsing your `Matchfile` config file. Could you post its contents here? 🙏 
@gilgamesharcadia @eamonn-alphin

**Comment by eamonn-alphin** [comment]
I can't remember how I got it to work, I think I used "fastlane deliver --app-identifier "ca.mycompany.myIdentifier" --force, and oddly I don't have a matchFile...I"m still figuring this stuff out. I've found that using the fastLane standalone command (like fastLane snapshot or Fastlane deliver) BEFORE using my custom fastFile lanes seems to make it work.
