### ISSUE TITLE
[Fastlane.Swift] get_provisioning_profile error: You can't enable both :developer_id and :adhoc

### ISSUE THREAD

**Issue by tedgonzalez** [fastlane/fastlane#17343]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Using sample lane
```
    func fetcherLane() {
        getProvisioningProfile(
            appIdentifier: "XXX",
            username: "XXX",
            teamId: "XXX",
            teamName: "XXX",
            provisioningName: "XXX",
            ignoreProfilesWithDifferentName: true,
            certOwnerName: nil,
            skipFetchProfiles: true,
            skipCertificateVerification: true,
            readonly: true
        )
    }
```
You'll get error
```
You can't enable both :developer_id and :adhoc
```
similar to [May 2018 Issue 12506](https://github.com/fastlane/fastlane/issues/12506)

##### Command executed
```
bundle exec fastlane fetcher
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.15.6                                          |
| Ruby                        | 2.6.6                                            |
| Bundler?                    | true                                             |
| Git                         | git version 2.24.3 (Apple Git-128)               |
| Installation Source         | ~/.rvm/gems/ruby-2.6.6/bin/fastlane              |
| Host                        | Mac OS X 10.15.6 (19G2021)                       |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.6/lib                     |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-12.0.app/Contents/Developer/ |
| Xcode Version               | 12.0.1                                           |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

```ruby
// This file contains the fastlane.tools configuration
// You can find the documentation at https://docs.fastlane.tools
//
// For a list of all available actions, check out
//
//     https://docs.fastlane.tools/actions
//

import Foundation

class Fastfile: LaneFile {
    func fetcherLane() {
        getProvisioningProfile(
            appIdentifier: "XXX",
            username: "XXX", //environmentVariable(get: "APPLE_USERNAME"),
            teamId: "XXX",
            teamName: "XXX",
            provisioningName: "XXX",
            ignoreProfilesWithDifferentName: true,
            certOwnerName: nil,
            skipFetchProfiles: true,
            skipCertificateVerification: true,
            readonly: true
        )
    }
    func fetchAndResignLane(withOptions options:[String: String]?) {
        desc("Fetches the ipa file from `repository`, increments build number and resigns with `signing_identity`. Usage: `fastlane fetchAndResign app:befaring`")
        switch options?["app"] {
        case "befaring":
            xcversion(version: environmentVariable(get: "FL_XCODE_VERSION"))
            //let repository = "ssh://git@git.tech-01.net/nmb/ios_resigning.git"
            //sh(command: "rm -rf ../build && git clone --depth 1 \(repository) ../build")
            getProvisioningProfile(
                appIdentifier: "no.dnb.befaringspres",
                username: "theodore.partoza.gonzalez@dnb.no", //environmentVariable(get: "APPLE_USERNAME"),
                teamId: "YVFWMVJ9Y9",
                teamName: "DnB ASA",
                provisioningName: "BefaringProd",
                ignoreProfilesWithDifferentName: true,
                certOwnerName: nil,
                skipFetchProfiles: true,
                skipCertificateVerification: true,
                readonly: true
            )
            resign(
                ipa: "../build/Befaring.ipa",
                signingIdentity: "iPhone Distribution: DnB ASA (119504671)",
                provisioningProfile: "BefaringProd",
                version: "1" //environmentVariable(get: "BUILD_NUMBER")
            )

        default:
            echo(message: "Please specify app")
        }
	}
}

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.161.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 2.1.4        |
| rake                      | 13.0.1       |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.376.0      |
| aws-sigv4                 | 1.2.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.108.0      |
| aws-sdk-kms               | 1.38.0       |
| aws-sdk-s3                | 1.81.1       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.0.0        |
| excon                     | 0.76.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 1.0.1        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.2.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| signet                    | 0.14.0       |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.0       |
| json                      | 2.3.1        |
| mini_magick               | 4.10.1       |
| plist                     | 3.5.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.18.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| xcode-install             | 2.6.6        |
</details>

*generated on:* **2020-09-29**
</details> </pre>
</details>

**Comment by tedgonzalez** [comment]
### Workaround

Update `Fastlane.swift` file
```
public func getProvisioningProfile(adhoc: Bool = false,
                                   developerId: Bool = false,
                                   development: Bool = false,
                                   skipInstall: Bool = false,
                                   force: Bool = false,
                                   appIdentifier: String,
                                   username: String,
                                   teamId: String? = nil,
                                   teamName: String? = nil,
                                   provisioningName: String? = nil,
                                   ignoreProfilesWithDifferentName: Bool = false,
                                   outputPath: String = ".",
                                   certId: String? = nil,
                                   certOwnerName: String? = nil,
                                   filename: String? = nil,
                                   skipFetchProfiles: Bool = false,
                                   skipCertificateVerification: Bool = false,
                                   platform: Any = "ios",
                                   readonly: Bool = false,
                                   templateName: String? = nil,
                                   failOnNameTaken: Bool = false)
{
    var args = [
        RubyCommand.Argument(name: "development", value: development),
        RubyCommand.Argument(name: "skip_install", value: skipInstall),
        RubyCommand.Argument(name: "force", value: force),
        RubyCommand.Argument(name: "app_identifier", value: appIdentifier),
        RubyCommand.Argument(name: "username", value: username),
        RubyCommand.Argument(name: "team_id", value: teamId),
        RubyCommand.Argument(name: "team_name", value: teamName),
        RubyCommand.Argument(name: "provisioning_name", value: provisioningName),
        RubyCommand.Argument(name: "ignore_profiles_with_different_name", value: ignoreProfilesWithDifferentName),
        RubyCommand.Argument(name: "output_path", value: outputPath),
        RubyCommand.Argument(name: "cert_id", value: certId),
        RubyCommand.Argument(name: "cert_owner_name", value: certOwnerName),
        RubyCommand.Argument(name: "filename", value: filename),
        RubyCommand.Argument(name: "skip_fetch_profiles", value: skipFetchProfiles),
        RubyCommand.Argument(name: "skip_certificate_verification", value: skipCertificateVerification),
        RubyCommand.Argument(name: "platform", value: platform),
        RubyCommand.Argument(name: "readonly", value: readonly),
        RubyCommand.Argument(name: "template_name", value: templateName),
        RubyCommand.Argument(name: "fail_on_name_taken", value: failOnNameTaken)
    ]
    if adhoc { args.append(RubyCommand.Argument(name: "adhoc", value: adhoc)) }
    if developerId { args.append(RubyCommand.Argument(name: "developer_id", value: developerId)) }
    if development { args.append(RubyCommand.Argument(name: "development", value: development)) }
    if skipInstall { args.append(RubyCommand.Argument(name: "skip_install", value: skipInstall)) }
    if force { args.append(RubyCommand.Argument(name: "force", value: force)) }
    let command = RubyCommand(commandID: "", methodName: "get_provisioning_profile", className: nil, args: args)
    _ = runner.executeCommand(command)
}
```

**Comment by Wray888** [comment]
Thanks for the info [pupilpath](https://www.pupilpath.us/)

**Comment by minuscorp** [comment]
I guess this gets automatically updated, as all Swift interface, with each update of the core.

**Comment by rogerluan** [comment]
@joshdholtz I think I figured this out. Relevant code:

https://github.com/fastlane/fastlane/blob/4753b8dea25c9f9d9b7fc49101b4ee1e4590cb80/sigh/lib/sigh/options.rb#L12-L38

Turns out that in Swift, by omitting the arguments, since they're nonnull Bools, it forwards to ruby as non-optional `False`, so ruby detects as if the user was providing all the options.

IMO a reasonable solution would be to add `next if option.value == false` all those `conflict_block`s. However, `option` doesn't seem to have the runtime "value" of the option - does it? 🤔 

Another solution would be to make those 3 booleans optional. I'm not a fan of optional booleans 🙃 but we use them in other places where reasonable, not sure if you have a strong opinion here.

And a 3rd and last solution would be to simply remove the validation if we agree it's nonsense and is just hurting us 🙈 

Do you see other solutions? Thoughts on them? 

----

@tedgonzalez , @minuscorp is right - modifying the `Fastlane.swift` file will temporarily work for you but it will get overriden if you update _fastlane_ or decide to build the project according to _fastlane_'s runtime suggestion. It works, but it's just a local hotfix.

**Comment by minuscorp** [comment]
I'm with you @rogerluan, Optional Booleans are not a good practice in Swift. That being said we have to use a type that accepts `nil` and any other type, because `Either` doesn't solve the issue with `nil` unless we give it some sense that I can't see right now, I'd use Optional types. It can spread to other use cases in the Swift codebase and this is something that will be treated internally by the Swift core.

**Comment by rogerluan** [comment]
@minuscorp not sure if I follow your comment - do you mean we could create an optional Bool type, like `enum OptionalBoolean { case true, false, notSet }`? 🤔 

I think the solution `1` I posted above would be the best one if possible, and the solution `3` would be the 2nd best imo hehe these validations usually cause more problems than solve from the little experience I've had with them 😬

**Comment by minuscorp** [comment]
A custom enum is not ideal but might work. I'm quite unsure that we can interpret as a truth that if the value is false, shouldn't be skipped and not checked against conflicting value. I think we should use nil as an empty value that is there easiest way to do or as a not ideal solution the enum.

**Comment by tedgonzalez** [comment]
🚴🏼‍♂️

**Comment by rogerluan** [comment]
@minuscorp shall we just roll with an optional boolean? They're everywhere already, I realized 🤷 including fixing issues similar to this one.

**Comment by minuscorp** [comment]
I'm ok with that, not Swifty but works! 👌

**Comment by rogerluan** [comment]
After awhile, I dug a bit deeper into this issue and opened a proposal here 😊 https://github.com/fastlane/fastlane/pull/17981
Looking forward to hearing your thoughts @minuscorp ! 🤗

**Comment by minuscorp** [comment]
This probably could be closed with the latest PR 😇

**Comment by rogerluan** [comment]
@minuscorp I tested this on latest fastlane and it still doesn't work 😬 

<img width="711" alt="image" src="https://user-images.githubusercontent.com/8419048/120039702-bb891b80-bfdb-11eb-8be9-8edebbee5eaf.png">

Test code:

```swift
    func rogerLane() {
        getProvisioningProfile(
            appIdentifier: "XXX",
            username: "XXX",
            teamId: "XXX",
            teamName: "XXX",
            provisioningName: "XXX",
            ignoreProfilesWithDifferentName: true,
            certOwnerName: nil,
            skipFetchProfiles: true,
            skipCertificateVerification: true,
            readonly: true
        )
    }
```

If you check `Fastlane.swift` you'll see the new code is still using primitive bools insteado of the new enum:

<img width="987" alt="image" src="https://user-images.githubusercontent.com/8419048/120039834-ec695080-bfdb-11eb-86b7-9296ff3bda5c.png">

**Comment by minuscorp** [comment]
The issue there is that none of those `Bool` are optional, so there might be a config issue behind this specific case? Not sure.

**Comment by rogerluan** [comment]
They're not optional because they're booleans, ideally we'd like to work with as few optional booleans as possible (I think?) 🤷 we discussed this before here https://github.com/fastlane/fastlane/issues/17343#issuecomment-757188443 😂 idk if that's the change we wanna make haha

**Comment by minuscorp** [comment]
Maybe I can treat all booleans as `OptionalConfigItem`s without changing them on the Ruby side 🤔 . That'd fix this issue from the root.

**Comment by rogerluan** [comment]
Sounds like thhat'd do @minuscorp ! 💪

**Comment by minuscorp** [comment]
#18827 is created for this purpose!
