### ISSUE TITLE
Not an "iOS App Store" profile

### ISSUE THREAD

**Issue by AAverin** [fastlane/fastlane#17349]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)
https://github.com/fastlane/fastlane/issues/16191

### Issue Description
According to Firebase Distribution, it should be possible to use Ad Hoc provisioning profile to publish.

Having Ad Hoc provisioning profile set up, fastlane fails to upload to Firebase App Distribution with error:
```
Error Domain=IDEProfileQualificationErrorDomain Code=3 "Provisioning profile "___" is not an "iOS App Store" profile." UserInfo={IDEProfileQualificationError_Profile=<IDEEmbeddedProvisioningProfile ___: name: ___, UUID: ___, teamName: ___, t
```

##### Command executed
firebase_app_distrubution

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.3                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.3 (19D76)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.7                                                           |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :closed_beta do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight
  end

  lane :alpha do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    firebase_app_distribution(
        app: "1:306941469140:ios:6d6cb452a125fee7993641",
        testers_file: "../distribution/testers.txt"
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("photohound.app") # The bundle identifier of your app
apple_id("a.a.averin@gmail.com") # Your Apple email address

itc_team_id("122148764") # App Store Connect Team ID
team_id("J66XNU6Z6U") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.149.1 | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.2.3   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.3.0        |
| slack-notifier                            | 2.3.2        |
| atomos                                    | 0.1.3        |
| claide                                    | 1.0.3        |
| colored2                                  | 3.1.2        |
| nanaimo                                   | 0.2.6        |
| xcodeproj                                 | 1.15.0       |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.7.0        |
| terminal-table                            | 1.8.0        |
| plist                                     | 3.5.0        |
| public_suffix                             | 2.0.5        |
| addressable                               | 2.7.0        |
| multipart-post                            | 2.0.0        |
| word_wrap                                 | 1.0.0        |
| tty-screen                                | 0.7.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| babosa                                    | 1.0.3        |
| colored                                   | 1.2          |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| excon                                     | 0.73.0       |
| faraday                                   | 0.17.3       |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.6        |
| faraday_middleware                        | 0.13.1       |
| fastimage                                 | 2.1.7        |
| gh_inspector                              | 1.1.3        |
| mini_magick                               | 4.10.1       |
| multi_xml                                 | 0.6.0        |
| rubyzip                                   | 1.3.0        |
| security                                  | 0.1.3        |
| xcpretty-travis-formatter                 | 1.0.0        |
| dotenv                                    | 2.7.5        |
| bundler                                   | 2.1.4        |
| naturally                                 | 2.2.0        |
| simctl                                    | 1.6.8        |
| jwt                                       | 2.1.0        |
| uber                                      | 0.1.0        |
| declarative                               | 0.0.10       |
| declarative-option                        | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| mini_mime                                 | 1.0.2        |
| httpclient                                | 2.8.3        |
| google-api-client                         | 0.38.0       |
| emoji_regex                               | 1.0.1        |
| CFPropertyList                            | 3.0.2        |
| unf_ext                                   | 0.0.7.7      |
| json                                      | 2.3.0        |
| multi_json                                | 1.14.1       |
| signet                                    | 0.14.0       |
| os                                        | 1.1.0        |
| memoist                                   | 0.16.2       |
| googleauth                                | 0.12.0       |
| digest-crc                                | 0.5.1        |
| google-cloud-errors                       | 1.0.0        |
| google-cloud-env                          | 1.3.1        |
| google-cloud-core                         | 1.5.0        |
| google-cloud-storage                      | 1.26.0       |
| aws-eventstream                           | 1.1.0        |
| aws-sigv4                                 | 1.1.3        |
| aws-partitions                            | 1.304.0      |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.94.0       |
| aws-sdk-kms                               | 1.30.0       |
| aws-sdk-s3                                | 1.63.0       |
| forwardable                               | 1.2.0        |
| logger                                    | 1.3.0        |
| stringio                                  | 0.0.2        |
| ipaddr                                    | 1.2.2        |
| openssl                                   | 2.1.2        |
| ostruct                                   | 0.1.0        |
| strscan                                   | 1.0.0        |
| date                                      | 2.0.0        |
| fileutils                                 | 1.1.0        |
| etc                                       | 1.0.1        |
| io-console                                | 0.4.7        |
| zlib                                      | 1.0.0        |
| libxml-ruby                               | 3.1.0        |
| rexml                                     | 3.1.9        |
| psych                                     | 3.1.0        |
| mutex_m                                   | 0.1.0        |
| webrick                                   | 1.4.2        |
| fastlane-plugin-firebase_app_distribution | 0.2.3        |
</details>

*generated on:* **2020-09-30**
</details>
</pre>
</details>

**Comment by max-ott** [comment]
Could you please upload to the latest `fastlane` version?

**Comment by AAverin** [comment]
@max-ott 
Same error so far:
```
/usr/bin/xcrun /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/3t/sfnnltys29b8gwwrcjs74v_m0000gn/T/gym_config20201001-65409-7ixjtv.plist' -archivePath /Users/___/Library/Developer/Xcode/Archives/2020-10-01/Runner\ 2020-10-01\ 11.23.12.xcarchive -exportPath '/var/folders/3t/sfnnltys29b8gwwrcjs74v_m0000gn/T/gym_output20201001-65409-cmkdnf' 
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/3t/sfnnltys29b8gwwrcjs74v_m0000gn/T/gym_config20201001-65409-7ixjtv.plist -archivePath '/Users/___/Library/Developer/Xcode/Archives/2020-10-01/Runner 2020-10-01 11.23.12.xcarchive' -exportPath /var/folders/3t/sfnnltys29b8gwwrcjs74v_m0000gn/T/gym_output20201001-65409-cmkdnf
2020-10-01 11:24:03.049 xcodebuild[67872:3844561] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/3t/sfnnltys29b8gwwrcjs74v_m0000gn/T/Runner_2020-10-01_11-24-03.048.xcdistributionlogs'.
error: exportArchive: Provisioning profile "___ Firebase Distribution" is not an "iOS App Store" profile.

```

**Comment by AAverin** [comment]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.3                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.3 (19D76)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.7                                                           |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :closed_beta do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight
  end

  lane :alpha do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    firebase_app_distribution(
        app: "1:306941469140:ios:6d6cb452a125fee7993641",
        testers_file: "../distribution/testers.txt"
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("photohound.app") # The bundle identifier of your app
apple_id("a.a.averin@gmail.com") # Your Apple email address

itc_team_id("122148764") # App Store Connect Team ID
team_id("J66XNU6Z6U") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.149.1 | 🚫 Update available |


### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.2.3   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.3.0        |
| slack-notifier                            | 2.3.2        |
| atomos                                    | 0.1.3        |
| claide                                    | 1.0.3        |
| colored2                                  | 3.1.2        |
| nanaimo                                   | 0.2.6        |
| xcodeproj                                 | 1.15.0       |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.7.0        |
| terminal-table                            | 1.8.0        |
| plist                                     | 3.5.0        |
| public_suffix                             | 2.0.5        |
| addressable                               | 2.7.0        |
| multipart-post                            | 2.0.0        |
| word_wrap                                 | 1.0.0        |
| tty-screen                                | 0.7.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| babosa                                    | 1.0.3        |
| colored                                   | 1.2          |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| excon                                     | 0.73.0       |
| faraday                                   | 0.17.3       |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.6        |
| faraday_middleware                        | 0.13.1       |
| fastimage                                 | 2.1.7        |
| gh_inspector                              | 1.1.3        |
| mini_magick                               | 4.10.1       |
| multi_xml                                 | 0.6.0        |
| rubyzip                                   | 1.3.0        |
| security                                  | 0.1.3        |
| xcpretty-travis-formatter                 | 1.0.0        |
| dotenv                                    | 2.7.5        |
| bundler                                   | 2.1.4        |
| naturally                                 | 2.2.0        |
| simctl                                    | 1.6.8        |
| jwt                                       | 2.1.0        |
| uber                                      | 0.1.0        |
| declarative                               | 0.0.10       |
| declarative-option                        | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| mini_mime                                 | 1.0.2        |
| httpclient                                | 2.8.3        |
| google-api-client                         | 0.38.0       |
| emoji_regex                               | 1.0.1        |
| CFPropertyList                            | 3.0.2        |
| unf_ext                                   | 0.0.7.7      |
| json                                      | 2.3.0        |
| multi_json                                | 1.14.1       |
| signet                                    | 0.14.0       |
| os                                        | 1.1.0        |
| memoist                                   | 0.16.2       |
| googleauth                                | 0.12.0       |
| digest-crc                                | 0.5.1        |
| google-cloud-errors                       | 1.0.0        |
| google-cloud-env                          | 1.3.1        |
| google-cloud-core                         | 1.5.0        |
| google-cloud-storage                      | 1.26.0       |
| aws-eventstream                           | 1.1.0        |
| aws-sigv4                                 | 1.1.3        |
| aws-partitions                            | 1.304.0      |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.94.0       |
| aws-sdk-kms                               | 1.30.0       |
| aws-sdk-s3                                | 1.63.0       |
| forwardable                               | 1.2.0        |
| logger                                    | 1.3.0        |
| stringio                                  | 0.0.2        |
| ipaddr                                    | 1.2.2        |
| openssl                                   | 2.1.2        |
| ostruct                                   | 0.1.0        |
| strscan                                   | 1.0.0        |
| date                                      | 2.0.0        |
| fileutils                                 | 1.1.0        |
| etc                                       | 1.0.1        |
| io-console                                | 0.4.7        |
| zlib                                      | 1.0.0        |
| libxml-ruby                               | 3.1.0        |
| rexml                                     | 3.1.9        |
| psych                                     | 3.1.0        |
| mutex_m                                   | 0.1.0        |
| webrick                                   | 1.4.2        |
| fastlane-plugin-firebase_app_distribution | 0.2.3        |
</details>


*generated on:* **2020-10-01**
</details>

**Comment by AAverin** [comment]
@max-ott FYI, I have updated from brew, so if latest fastlane is not yet published there I will not have the latest latest version

**Comment by AAverin** [comment]
Even though brew says it's 2.161, for some reason 2.149.1 is still being run, even if I restart the terminal

**Comment by AAverin** [comment]
I did `bundle update` to 2.161, but error is still the same

**Comment by AAverin** [comment]
Resolved in https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/issues/163
