### ISSUE TITLE
app_store_connect_api_key doesn't work with key_content

### ISSUE THREAD

**Issue by SEGVeenstra** [fastlane/fastlane#17340]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When trying to create an `app_store_connect_api_key` using `key_content` `upload_to_testflight` will result in an error.
However, providing the key with `key_filepath` does work.

##### Command executed
```
app_store_connect_api_key(
  in_house: true
)
```
The rest is set with ENV VARS

##### Complete output when running fastlane, including the stack trace and command used
```
/usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/spaceship/lib/spaceship/connect_api/token.rb:57:in `initialize': [!] invalid curve name (OpenSSL::PKey::ECError)
	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/spaceship/lib/spaceship/connect_api/token.rb:57:in `new'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/spaceship/lib/spaceship/connect_api/token.rb:57:in `create'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/pilot/lib/pilot/manager.rb:33:in `api_token'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/pilot/lib/pilot/manager.rb:20:in `login'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/pilot/lib/pilot/manager.rb:16:in `start'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/pilot/lib/pilot/build_manager.rb:17:in `upload'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:28:in `block (2 levels) in parsing_binding'

##[error]Bash exited with code '1'.
Finishing: Run Fastlane Deploy
```

<details>
  <pre> I've tried providing the key with and without line breaks but still it didn't seem to make a difference</pre>
</details>

### Environment

<details>
  <pre> I don't have this, it's running on Azure DevOps</pre>
</details>

**Comment by joshdholtz** [comment]
@SEGVeenstra I’m glad `key_filepath` works but `key_content` should be working too! How are you trying to load it? Are you trying to load it from an environment variable or a string? One thing you will need to make sure that you do is that you keep the new lines (`\n`) in there. 

We should actually probably catch this error and spit out something a bit more useful 🤔

**Comment by SEGVeenstra** [comment]
> How are you trying to load it? Are you trying to load it from an environment variable or a string?

I'm setting an environment variable. The response (in 1.60) returned the key and it looked correct, but somehow didn't work.
Loading the same key with the path did.

I found some other suggestions like explicitly putting the `\n` in there after copying it from the file. Someone suggested to escape the `\n` by doing `\\n`, but that didn't help either.

The way I got the key in the env var was with Azure DevOps variables.
I just opened the file, copied the content, and pasted it in there.
It's a single line field so I thought the `\n` would be removed so I've also tried it with putting them manually.

**Comment by joshdholtz** [comment]
@SEGVeenstra Thanks for reply! I haven’t tested it on Azure DevOps myself yet 🤔 Putting `\n` in there _should_ work as of `2.161.0` (which it looks like you are on).  I’m not sure how Azure DevOps handles the insert of multi-line test.

I don’t know if this is how you added the `\n` but I would maybe deleting the lines in a text editor and replacing them with `\n` before copying them into Azure.

Maybe we should also support a Base64 encoded `key_content` to prevent this issue from happening 🤔

**Comment by SEGVeenstra** [comment]
> Putting \n in there should work as of 2.161.0 (which it looks like you are on).

Correct, I saw the change that was made recently so I tried that.

> I don’t know if this is how you added the \n but I would maybe deleting the lines in a text editor and replacing them with \n before copying them into Azure.

This is exactly how I did it ;)

> Maybe we should also support a Base64 encoded key_content to prevent this issue from happening

That sounds like a solid solution.

**Comment by Brandon-T** [comment]
I had this issue.. I just solved it by doing:

```ruby
app_store_connect_api_key(
  key_id: "#{ENV["KEY_ID"]}",
  issuer_id: "#{ENV["ISSUER_ID"]}",
  key_content: "#{ENV["KEY_CONTENTS"]}".gsub('\n', '\\n'),
  in_house: false,
)
```

That `gsub` function replaces all `\n` with an escaped `\\n`.. I haven't tested with Azure, but for Github secrets, we pasted the key exactly as we got it from Apple's developer portal, and I passed it as an ENV variable to Fastlane from Github secrets..

Then I invoke the above as the very first thing before my build runs. Finally, I do:

```ruby
upload_to_testflight(
      username: "#{ENV["APPLE_ID"]}",
      app_identifier: "#{ENV["APP_IDENTIFIER"]}",
      app_platform: "ios",
      apple_id: "#{ENV["APPSTORE_APP_ID"]}",
      ipa: "#{ENV["BUILD_NAME"]}.ipa",
      skip_waiting_for_build_processing: true,
      team_id: "#{ENV["TEAM_ID"]}"
    )
```

**Comment by SEGVeenstra** [comment]
@Brandon-T Thank you, but I already have a work around.
It would be nice if it gets a proper solution though.

**Comment by joshdholtz** [comment]
@SEGVeenstra This should have a proper solution in `2.162.0` - https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/app_store_connect_api_key.rb#L22

The `app_store_connect_api_key` has that same gsub that @Brandon-T mentioned ☝️

**Comment by joshdholtz** [comment]
Oh wait... I did already comment on this about that OMG

I think I will add a base64 encoded option though because why not

**Comment by joshdholtz** [comment]
Added new `is_key_content_base64` in #17401 which should fix some of their issues with setting the key content in ENV and CI 🤞

**Comment by tasvir-rohila-carsales** [comment]
@joshdholtz I'm getting `invalid curve name` error when calling `upload_to_testflight`. 
Prior to calling `upload_to_testflight` I get a valid `api_key` from 
```
api_key = app_store_connect_api_key(
        key_id: "#{ENV["KEY_ID"]}",
        issuer_id: "#{ENV["ISSUER_ID"]}",
        key_content: "#{ENV["KEY_CONTENT"]}",
        duration: "#{ENV["DURATION"]}",
        in_house: "#{ENV["IN_HOUSE"]}",
        is_key_content_base64: "#{ENV["IS_KEY_ENCODED"]}"
      )
```
I'm using `Fastlane 2.166.0.`

Do I need to manually remove the `\n` from the AppStore Connect Private Key before encoding it to a base64 string ?

Any advise would be highly appreciated.

**Comment by joshdholtz** [comment]
@tasvir-rohila-carsales Hey! My first suggestion would be to use the environment variables that `app_store_connect_api_key` has built in so you don't need to manually have all the options being interpolated 😊  Below is the table with a column of the environment variables names and this was generated by running `fastlane actions app_store_connect_api_key`

Secondly if you are Base64 encoding the the key you should not remove the `\n` or `\r`. The issue may have been that you are technically passing a string in to `is_key_content_base64_encoded`.

Try changing to the using the environment variables that the action attempts to load from by default and let me know how it goes!

```sh
+-----------------------+-----------------------------------+-----------------------------------+---------+
|                                    app_store_connect_api_key Options                                    |
+-----------------------+-----------------------------------+-----------------------------------+---------+
| Key                   | Description                       | Env Var                           | Default |
+-----------------------+-----------------------------------+-----------------------------------+---------+
| key_id                | The key ID                        | APP_STORE_CONNECT_API_KEY_KEY_ID  |         |
| issuer_id             | The issuer ID                     | APP_STORE_CONNECT_API_KEY_ISSUER  |         |
|                       |                                   | _ID                               |         |
| key_filepath          | The path to the key p8 file       | APP_STORE_CONNECT_API_KEY_KEY_FI  |         |
|                       |                                   | LEPATH                            |         |
| key_content           | The content of the key p8 file    | APP_STORE_CONNECT_API_KEY_KEY     |         |
| is_key_content_base64 | Whether :key_content is Base64    | APP_STORE_CONNECT_API_KEY_IS_KEY  | false   |
|                       | encoded or not                    | _CONTENT_BASE64                   |         |
| duration              | The token session duration        | APP_STORE_CONNECT_API_KEY_DURATI  |         |
|                       |                                   | ON                                |         |
| in_house              | Is App Store or Enterprise (in    | APP_STORE_CONNECT_API_KEY_IN_HOU  |         |
|                       | house) team? App Store Connect    | SE                                |         |
|                       | API cannot not determine this on  |                                   |         |
|                       | its own (yet)                     |                                   |         |
+-----------------------+-----------------------------------+-----------------------------------+---------+

```

**Comment by tasvir-rohila-carsales** [comment]
Hey @joshdholtz Thanks for your quick reply.
I tried your suggestions (of using built in `APP_STORE_CONNECT_API_KEY_*` environment variables). However the `api_key` returned by `app_store_connect_api_key()` works well with `match()` action which is performed before `upload_to_testflight` in my `Fastfile`, it fails with the same `invalid curve name` error.

FYI the output of api_key which gets passed to `match()` has boolean value for `:is_key_content_base64=>true`

Does the api_key get reset after `match()` action ?

**Comment by joshdholtz** [comment]
@tasvir-rohila-carsales 

It does not get reset so I'm not sure what going on 🧐 Can you post what your Fastfile looks like so I can see what is all going on?

Thanks!

**Comment by tasvir-rohila-carsales** [comment]
Hi @joshdholtz 
Here is a basic version of my Fastfile

```
require 'fileutils'

fastlane_version "2.144.0"

default_platform :ios

build_dir = "../../build"


# default version range of xcode to build with if one is not passed in
xcode_version = "~> 12.0"

# global variable that stores api_key returned by app_store_connect_api_key()
api_key = app_store_connect_api_key()

private_lane :set_xcode_version do
  xcode_version = ENV["XCODE_VERSION"]
  UI.user_error!("No XCODE_VERSION environment variable specified") if xcode_version == nil

  xcversion version: xcode_version 
end

platform :ios do

    set_xcode_version
    dev_setup

    export_method = "app-store"
    
    # Create the archive
    build_ios_app(
      scheme: scheme,
      derived_data_path: build_dir,
      output_directory: build_dir,
      clean: true,
      xcargs: "BUILD_NUMBER=#{build_number} #{marketing_version} #{swift_conditions} #{gcc_definitions} \"-quiet\" USER_INTERFACE_STYLE=#{user_interface_style}",
      output_name: ipa_name,
      export_team_id: "SQH3BRZ9MZ",
      export_method: export_method,
      codesigning_identity: "Apple Distribution: Carsales.com Ltd. (SQH3BRZ9MZ)"
    )

    changelog = changelog_from_git_commits(
      commits_count: 5,
      pretty: "[%an] %s"
    )

    upload_to_testflight(
        api_key: api_key,
        app_identifier: bundle_identifier,
        skip_submission: true,
        skip_waiting_for_build_processing: true,
        ipa: ipa_path,
        changelog: changelog
      )
  end
  
  desc "Setup match on developer machine"
  lane :dev_setup do |options|
    readonly = options[:readonly]
    readonly = true unless readonly != nil
    force_for_new_devices = options[:force_for_new_devices]
    
    do_match(readonly: readonly, force_for_new_devices: force_for_new_devices, type: "development")
    do_match(readonly: readonly, force_for_new_devices: force_for_new_devices, type: "adhoc")
  end
  
  private_lane :do_match do |options|
    # the MATCH_PASSWORD env var is used by Match. We're just reading it here to make sure the user specified it
    
    git_encryption_key = ENV["MATCH_PASSWORD"]
    UI.user_error!("MATCH_PASSWORD environment variable must be specified") unless git_encryption_key
    
    keychain_params = get_keychain_params
    keychain_path = keychain_params[:keychain_path]
    UI.user_error!("keychain_path is missing") unless keychain_path

    # Get/create the required certificates and provisioning profiles for development
    match(
      api_key: api_key,
      type: options[:type],
      keychain_name: keychain_path,
      readonly: options[:readonly],
      force_for_new_devices: options[:force_for_new_devices]
    )
  end

  private_lane :recreate_keychain do
    # set up login keychains
  end

  private_lane :get_keychain_params do
    # gets keychain params
  end

  lane :unlock_my_fastlane_keychain do
    options = get_keychain_params
    keychain_path = options[:keychain_path]
    keychain_password = options[:keychain_password]

    unlock_keychain(
      path: keychain_path,
      password: keychain_password
    )
  end
end
```

**Comment by tasvir-rohila-carsales** [comment]
Hey @joshdholtz 
Just a FYI, `upload_to_testflight()` works well if I provide a plain-text for `APP_STORE_CONNECT_API_KEY_KEY` environment variable.

Also under the hood, when does Fastlane generate the `JWT` ? 

I ask this because I got this failure even though the duration `APP_STORE_CONNECT_API_KEY_DURATI` was 1200 and the script took less than 20 minutes to run.

```
[09:48:27]	[Step 1/1] [!] The request could not be completed because:
[09:48:27]	[Step 1/1] 	Authentication credentials are missing or invalid. - Provide a properly configured and signed bearer token, and make sure that it has not expired. Learn more about Generating Tokens for API Requests https://developer.apple.com/go/?id=api-generating-tokens
```
