### ISSUE TITLE
match import fails when using s3 storage method

### ISSUE THREAD

**Issue by ryechus** [fastlane/fastlane#17344]
### Issue Description
When I try to import existing `.cer` and `.p12` files using the s3 storage method an error is thrown about a missing required option. I am specifying my S3 credentials, region, and bucket name in a Matchfile.

```
~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/aws-sdk-s3-1.81.0/lib/aws-sdk-s3/bucket.rb:856:in `extract_name': \e[31m[!] missing required option :name
```

##### Command executed

    fastlane match import --storage-mode=s3

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
[✔] 🚀
[11:18:03]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[11:18:07]: Successfully loaded '/path/to/Matchfile' 📄

+----------------------+------------------------------------------+
|               Detected Values from './Matchfile'                |
+----------------------+------------------------------------------+
match file stuff
+----------------------+------------------------------------------+

~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/highline-1.7.10/lib/highline.rb:624: warning: Using the last argument as keyword parameters is deprecated
[11:18:07]: Certificate (.cer) path:
paths to cert
~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/highline-1.7.10/lib/highline.rb:624: warning: Using the last argument as keyword parameters is deprecated
[11:18:24]: Private key (.p12) path:
paths to cert
~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/highline-1.7.10/lib/highline.rb:624: warning: Using the last argument as keyword parameters is deprecated
[11:18:37]: Provisioning profile (.mobileprovision or .provisionprofile) path or leave empty to skip this file:

[11:19:58]: To not be asked about this value, you can specify it using 'git_url'
~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/highline-1.7.10/lib/highline.rb:624: warning: Using the last argument as keyword parameters is deprecated
[11:19:58]: URL to the git repo containing all the certificates: ^D
Looking for related GitHub issues on fastlane/fastlane...

➡️  Deliver to App Store fails on missing "whatsNew" attribute for app updates
    https://github.com/fastlane/fastlane/issues/17318 [open] 4 💬
    a day ago

➡️  App screenshot missing (APP_IPAD_PRO_3GEN_129)
    https://github.com/fastlane/fastlane/issues/16975 [open] 4 💬
    3 days ago

➡️  download_dsyms: 'Could not find latest bulid for version' error but version exists in App Store Connect
    https://github.com/fastlane/fastlane/issues/17202 [open] 15 💬
    a week ago

and 590 more at: https://github.com/fastlane/fastlane/search?q=missing%20required%20option%20%3Aname&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.

Traceback (most recent call last):
	19: from ~/.rbenv/versions/2.7.1/bin/fastlane:23:in `<main>'
	18: from ~/.rbenv/versions/2.7.1/bin/fastlane:23:in `load'
	17: from ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.161.0/bin/fastlane:23:in `<top (required)>'
	16: from ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	15: from ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.161.0/match/lib/match/commands_generator.rb:25:in `start'
	14: from ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.161.0/match/lib/match/commands_generator.rb:187:in `run'
	13: from ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	12: from ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.161.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	11: from ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	10: from ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 9: from ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 8: from ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.161.0/match/lib/match/commands_generator.rb:146:in `block (2 levels) in run'
	 7: from ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.161.0/match/lib/match/importer.rb:36:in `import_cert'
	 6: from ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.161.0/match/lib/match/storage/s3_storage.rb:96:in `download'
	 5: from ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/helper/s3_client_helper.rb:49:in `find_bucket!'
	 4: from ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/helper/s3_client_helper.rb:49:in `new'
	 3: from ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/aws-sdk-s3-1.81.0/lib/aws-sdk-s3/customizations/bucket.rb:14:in `block in <class:Bucket>'
	 2: from ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/aws-sdk-s3-1.81.0/lib/aws-sdk-s3/customizations/bucket.rb:14:in `call'
	 1: from ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/aws-sdk-s3-1.81.0/lib/aws-sdk-s3/bucket.rb:24:in `initialize'
~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/aws-sdk-s3-1.81.0/lib/aws-sdk-s3/bucket.rb:856:in `extract_name': missing required option :name (ArgumentError)
	19: from ~/.rbenv/versions/2.7.1/bin/fastlane:23:in `<main>'
	18: from ~/.rbenv/versions/2.7.1/bin/fastlane:23:in `load'
	17: from ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.161.0/bin/fastlane:23:in `<top (required)>'
	16: from ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	15: from ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.161.0/match/lib/match/commands_generator.rb:25:in `start'
	14: from ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.161.0/match/lib/match/commands_generator.rb:187:in `run'
	13: from ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	12: from ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.161.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	11: from ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	10: from ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 9: from ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 8: from ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.161.0/match/lib/match/commands_generator.rb:146:in `block (2 levels) in run'
	 7: from ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.161.0/match/lib/match/importer.rb:36:in `import_cert'
	 6: from ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.161.0/match/lib/match/storage/s3_storage.rb:96:in `download'
	 5: from ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/helper/s3_client_helper.rb:49:in `find_bucket!'
	 4: from ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/helper/s3_client_helper.rb:49:in `new'
	 3: from ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/aws-sdk-s3-1.81.0/lib/aws-sdk-s3/customizations/bucket.rb:14:in `block in <class:Bucket>'
	 2: from ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/aws-sdk-s3-1.81.0/lib/aws-sdk-s3/customizations/bucket.rb:14:in `call'
	 1: from ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/aws-sdk-s3-1.81.0/lib/aws-sdk-s3/bucket.rb:24:in `initialize'
~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/aws-sdk-s3-1.81.0/lib/aws-sdk-s3/bucket.rb:856:in `extract_name': \e[31m[!] missing required option :name
  </pre>
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.161.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 1.0.1        |
| faraday_middleware        | 1.0.0        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mini_mime                 | 1.0.2        |
| signet                    | 0.14.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| emoji_regex               | 3.0.0        |
| uri                       | 0.10.0       |
| nanaimo                   | 0.3.0        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.18.0       |
| public_suffix             | 4.0.6        |
| tty-screen                | 0.8.1        |
| excon                     | 0.76.0       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| fastimage                 | 2.2.0        |
| json                      | 2.3.1        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.4        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| retriable                 | 3.1.2        |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| memoist                   | 0.16.2       |
| googleauth                | 0.13.1       |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-env          | 1.3.3        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.0       |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-partitions            | 1.375.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.107.0      |
| aws-sdk-kms               | 1.38.0       |
| aws-sdk-s3                | 1.81.0       |
| forwardable               | 1.3.1        |
| logger                    | 1.4.2        |
| cgi                       | 0.1.0        |
| timeout                   | 0.1.0        |
| stringio                  | 0.1.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.2.0        |
| strscan                   | 1.0.3        |
| date                      | 3.0.0        |
| delegate                  | 0.1.0        |
| fileutils                 | 1.4.1        |
| io-console                | 0.5.6        |
| zlib                      | 1.1.0        |
| singleton                 | 0.1.0        |
| rexml                     | 3.2.3        |
| open3                     | 0.1.0        |
| yaml                      | 0.1.0        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.6.0        |
</details>

**Comment by ryechus** [comment]
It looks like the problem is with this code https://github.com/fastlane/fastlane/blob/master/match/lib/match/importer.rb#L18-L35

The params `s3_bucket` parameter needs to be passed into the underlying storage class. None of the S3 specific params are being passed into the `S3Storage` class instance.

**Comment by joshdholtz** [comment]
@ryechus Thanks for reporting this! I _think_ this is fixed in https://github.com/fastlane/fastlane/pull/17291 but I will verify and fix it if it isn’t 😊 

This new match changes _should_ be going out this week (maybe early Thursday morning)

**Comment by joshdholtz** [comment]
This should be fixed in latest release! ❤️  Feel free to let me know if you run into any other issues!
