### ISSUE TITLE
I am not able to commit the code changes as well as tag using git command from fastlane script. it was working fine with bitbuket but now i am using azure devops repo.

### ISSUE THREAD

**Issue by Priyankakum** [fastlane/fastlane#17341]
desc "Commits and Pushes Build Version Bump & adds GIT Tag"
lane :commit_bump do
	if(lane_context[SharedValues::PLATFORM_NAME].to_s.include? "ios")
		commit_version_bump(message: "Build version bump #{ENV["BUILD_TAG"]}.", force: true, xcodeproj: ENV["XCODE_PROJECT"])
	end
	 add_git_tag(tag: ENV["BUILD_TAG"])
	 sh("git push --all origin")
	 sh("git push --tags")

**Comment by Priyankakum** [comment]
The above command is committing back to the azure repo **tag** folder but not on the current building branch commit.

below i have tried to checkout branch and then push the commit to current building branch but not worked for me:
desc "Commits and Pushes Build Version Bump & adds GIT Tag"
lane :commit_bump do
if(lane_context[SharedValues::PLATFORM_NAME].to_s.include? "ios")
sh("git checkout $GIT_BRANCH")
commit_version_bump(message: "Build version bump #{ENV["BUILD_TAG"]}.", force: true, xcodeproj: ENV["XCODE_PROJECT"])
end
add_git_tag(tag: ENV["BUILD_TAG"])
sh("git push origin $GIT_BRANCH --follow-tags").

output++++++++++++++++++++

🔗  You can ⌘ + double-click on links to open them directly in your browser.
DEBUG [2020-09-28 05:53:43.65]: All plugins are up to date
bundler: failed to load command: fastlane (/usr/local/lib/ruby/gems/2.6.0/bin/fastlane)
FastlaneCore::Interface::FastlaneShellError: [!] Exit status of command 'git push origin $GIT_BRANCH --follow-tags' was 128 instead of 0.
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

**Comment by Priyankakum** [comment]
And if i use suggested command for git push like below it is absouloutly working fine as expected commiting in the current building branch and tag :

sh("git push origin HEAD:<name-of-remote-branch> --follow-tags")


For your info above $GIT_BRANCH is pipeline environment variable for the globally building branch.

**Comment by Priyankakum** [comment]
Classification: HCL Internal
Attached command working but not committing the tag back to the current building branch.(from git local the command is working fine with azure repo as expected)
Now I have tried the below command:

below i have tried to checkout branch and then push the commit to current building branch but not worked for me:
desc "Commits and Pushes Build Version Bump & adds GIT Tag"
lane :commit_bump do
if(lane_context[SharedValues::PLATFORM_NAME].to_s.include? "ios")
sh("git checkout $GIT_BRANCH")
commit_version_bump(message: "Build version bump #{ENV["BUILD_TAG"]}.", force: true, xcodeproj: ENV["XCODE_PROJECT"])
end
add_git_tag(tag: ENV["BUILD_TAG"])
sh("git push origin $GIT_BRANCH --follow-tags").
output++++++++++++++++++++
🔗 You can ⌘ + double-click on links to open them directly in your browser.
DEBUG [2020-09-28 05:53:43.65]: All plugins are up to date
bundler: failed to load command: fastlane (/usr/local/lib/ruby/gems/2.6.0/bin/fastlane)
FastlaneCore::Interface::FastlaneShellError: [!] Exit status of command 'git push origin $GIT_BRANCH --follow-tags' was 128 instead of 0.
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use
git push origin HEAD:<name-of-remote-branch>

NOTE: GIT_BRANCH is the pipeline env variable for branch name.

And if i use suggested command for git push like below it is absouloutly working fine as expected commiting in the current building branch and tag :
sh("git push origin HEAD: :<name-of-remote-branch> --follow-tags")

**Comment by max-ott** [comment]
Could you please open a new issue putting all relevant information together? Also a little bit of formatting would help.

**Comment by Priyankakum** [comment]
Classification: HCL Internal
I am not able to push the git tag in azure repo using Fastlane.

Below is the command:
desc "Commits and Pushes Build Version Bump & adds GIT Tag"
private_lane :commit_bump do
                if(lane_context[SharedValues::PLATFORM_NAME].to_s.include? "ios")
                                commit_version_bump(message: "Build version bump #{ENV["BUILD_TAG"]}.", force: true, xcodeproj: ENV["XCODE_PROJECT"])
                end
                add_git_tag(tag: ENV["BUILD_TAG"])
                sh("git push --all origin")
                sh("git push --tags")


output:++++++++++++++++++++++++++

tag is committing back to the tag option below screenshot for your ref:
[cid:image001.png@01D6980E.EBC6B280]


This tag should also committed back to associated current building branch from the azure pipeline


Thanks,
Priyanka Kumari
