### ISSUE TITLE
Lane 'validate' was defined multiple times!

### ISSUE THREAD

**Issue by SEGVeenstra** [fastlane/fastlane#17353]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I've created a lane (called validate) that we use for Azure DevOps to validate a build.
But when Azure DevOps runs it we get the error telling us the lane is defined multiple times.
Below is the `Fastfile`. It has only one lane called validate and imports no other Fastfiles.

Running the lane locally does work.
```
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :deploy do |options|
    setup_ci
    match(type: "appstore", readonly: is_ci, git_bearer_authorization: options[:git_token])
    build_app(scheme: "RDWVoertuigbeeld",export_method: "app-store")
    
    api_key = app_store_connect_api_key(
      in_house: false
    )
    upload_to_testflight(api_key: api_key)
  end

  desc "Validate the project"
  lane :validate do |options|
    setup_ci
    match(type: "appstore", readonly: is_ci, git_bearer_authorization: options[:git_token])
    build_app(scheme: "APPNAME", export_method: "app-store")
    run_tests(scheme: "APPNAMETests" )
  end
end
```

##### Command executed
`fastlane ios validate git_token:***` / `fastlane validate git_token:***`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
[08:42:23]: fastlane detected a Gemfile in the current directory
[08:42:23]: However, it seems like you didn't use `bundle exec`
[08:42:23]: To launch fastlane faster, please use
[08:42:23]: 
[08:42:23]: $ bundle exec fastlane ios validate git_token:***
[08:42:23]: 
[08:42:23]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[08:42:42]: Sending anonymous analytics information
[08:42:42]: Learn more at https://docs.fastlane.tools/#metrics
[08:42:42]: No personal or sensitive data is sent.
[08:42:42]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
[08:42:42]: ------------------------------
[08:42:42]: --- Step: default_platform ---
[08:42:42]: ------------------------------

[!] Lane 'validate' was defined multiple times!

##[error]Bash exited with code '1'.
Finishing: Bash Script
</pre>
</details>

### Environment
---

**Comment by Alvarado67** [comment]
Thanks for the information keep sharing such information [talktowendys](https://www.talktowendys.us/)

**Comment by Williamssonn** [comment]
This works really well for us, thank you!


[talktowendys](https://www.talktowendys.us/)
