### ISSUE TITLE
Fastlane DELIVER does not have the option to specify api_key_path

### ISSUE THREAD

**Issue by athith-sybo** [fastlane/fastlane#17363]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
The Fastlane Deliver action does not an option to pass the API_KEY which is needed to authenticate with APPSTORE_CONNECT.

##### Command executed
fastlane deliver --force
Values  passed in Deliver File are as below:

# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/
# 1
app_version '2.0.0'
# 2
automatic_release false
# 3
app_icon './metadata/AppIcon.png'
# 4
skip_binary_upload true
# 5
metadata_path './metadata'
# 6
screenshots_path './screenshots'
# 7 
submit_for_review false
# 8
overwrite_screenshots true
# 9
skip_screenshots false
# 10
api_key_path '../../KeyFile.json'

##### Complete output when running fastlane, including the stack trace and command used
fastlane deliver --force

[!] Could not find option 'api_key_path' in the list of available options: username, app_identifier, app, edit_live, ipa, pkg, platform, metadata_path, screenshots_path, skip_binary_upload, skip_screenshots, app_version, skip_metadata, force, submit_for_review, automatic_release, price_tier, build_number, app_rating_config_path, submission_information, team_id, team_name, dev_portal_team_id, dev_portal_team_name, itc_provider, overwrite_screenshots, app_icon, apple_watch_app_icon, copyright, primary_category, secondary_category, primary_first_sub_category, primary_second_sub_category, secondary_first_sub_category, secondary_second_sub_category, app_review_information, description, name, keywords, release_notes, privacy_url, support_url, marketing_url

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>### Captured Output

Command Used: `env`
<details><summary>Output/Log</summary>

```

WARN [2020-10-02 13:30:38.95]: Generating fastlane environment output, this might take a few seconds...
Successfully loaded Appfile at path '/Users/athith/Documents/FastlaneTesting/ios/Appfile'
- app_identifier: 'com.sybo.AthithTest'
- apple_id: 'athith@sybogames.com'
- itc_team_name: 'Sybo Games ApS'
- itc_team_id: '348702'
-------
DEBUG [2020-10-02 13:30:45.09]: Checking if there are any plugins that should be loaded...

Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `length' for nil

URL: https://api.github.com/search/issues?q=undefined%20method%20%60length%27%20for%20nil+repo:fastlane/fastlane
➡️  Completely new app gets: You must provide a value for the attribute 'usesNonExemptEncryption' with this request
   https://github.com/fastlane/fastlane/issues/16645 [closed] 11 💬
   2 weeks ago

➡️  undefined method `login' for Spaceship::Tunes:Module
   https://github.com/fastlane/fastlane/issues/15495 [closed] 7 💬
   13 Feb 2020

➡️  [deliver][produce][spaceship] Update to use new App Store Connect API endpoints
   https://github.com/fastlane/fastlane/pull/16640 [closed] 71 💬
   08 Jul 2020

and 43 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60length%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.7                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.15.7 (19H2)                     |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.0.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

<details><summary>`./Appfile`</summary>

```ruby
# We mention our App Bundle identifier and our Apple ID to be used

app_identifier "com.sybo.AthithTest" # The bundle identifier of your app
apple_id "athith@sybogames.com" # Your Apple email address

# You can uncomment the lines below and add your own
# team selection in case you're in multiple teams
# team_name "Felix Krause"
# team_id "Q2CBPJ58CA"

# To select a team for App Store Connect use

 itc_team_name "Sybo Games ApS"
 itc_team_id "348702"

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://docs.fastlane.tools/advanced/Appfile/#appfile
```
</details>

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.28.3  | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.13.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.17.0       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.1       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.13.1       |
</details>

*generated on:* **2020-10-02**
</details>

**Comment by rogerluan** [comment]
Hey @athith-sybo !
Updating _fastlane_ will fix your issue. Your report above shows you're at v2.28.3, and the API you're looking for is available in the latest version of _fastlane_.

**Comment by athith-sybo** [comment]
Hi @rogerluan ,
I have updated Fastlane still the same error. Can you please post the exact key name which needs to be used in CLI

**Comment by rogerluan** [comment]
It's still `api_key_path` https://docs.fastlane.tools/actions/deliver/#parameters

By the version you were running, you're probably running the wrong CLI command, such as confusing `fastlane deliver` with `bundle exec fastlane deliver` or vice versa. 

What is the exact full command you're entering @athith-sybo ?

**Comment by athith-sybo** [comment]
I maintain my deliver parameters in the deliverfile which has the following values:
app_version '1.5.5'
automatic_release false
skip_binary_upload true
metadata_path './metadata'
screenshots_path './screenshots'
submit_for_review false
overwrite_screenshots true
skip_screenshots false
api_key_path ./AppstoreConnect_API_KEY/fastlane.ios.json

and then i go to the path where my meta-content, screenshots & the deliverfile are , in the terminal i just run **fastlane deliver --force** from that path

**Comment by athith-sybo** [comment]
But anyways i will update my fastlane version and try
