### ISSUE TITLE
Nested import won't work

### ISSUE THREAD

**Issue by jgongo** [fastlane/fastlane#17377]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
If I use `import` with a relative path in an already imported `Fastfile` the second import fails because it resolves the path relative to the root `Fastfile` instead of the imported one.

I was trying to do this because:
* We have a set of mobile projects with almost the same configuration (this is, almost the same `Fastfile`). We were thinking about extracting all the common functionality to a common `Fastfile` which would be included in all the projects using `import_from_git`
* We support bot `iOS` and `Android` and we have quite a few lanes, so we were thinking to split the included `Fastfile` to make it manageable
* Taking this into account we thought we could have a main `Fastfile` for each project, which includes our shared lanes from a second `Fastfile`, which in turn `import`s several files including related lanes for all supported platforms

We wanted to have something like this:
```
(Main project) Fastfile
    +-(import_from_git)(shared configuration) Fastfile
        +-(import)(shared configuration) First set of related lanes
        +-(import)(shared configuration) Second set of related lanes
        ...
```

Maybe this isn't supported? Is there any other way to achieve this?

##### Command executed
```
$ bundle exec fastlane
```

##### Complete output when running fastlane, including the stack trace and command used
```
[✔] 🚀 

[!] Could not find Fastfile at path '/[...]/fastmain/fastlane/./HelloWorld'
```

I have included all the `Fastfile`s used in my test in the Environment section. In this first test I use `import` in the main `Fastfile` instead of `import_from_git` as is intended in the final solution.

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.15.7                                          |
| Ruby                        | 2.6.6                                            |
| Bundler?                    | true                                             |
| Git                         | git version 2.21.0 (Apple Git-122)               |
| Installation Source         | ~/.rbenv/versions/2.6.6/bin/fastlane             |
| Host                        | Mac OS X 10.15.7 (19H2)                          |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.6/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-11.1.app/Contents/Developer/ |
| Xcode Version               | 11.1                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | es_ES.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
#default_platform(:ios)

import("../../fastinclude/fastlane/Fastfile")

platform :ios do
  lane :hello_world_local do
    UI.message "Hello world local iOS"
  end
end

platform :android do
  lane :hello_world_local do
    UI.message "Hello world local Android"
  end
end
```
</details>

<details><summary>`../../fastinclude/fastlane/Fastfile`</summary>

```ruby
import("./HelloWorld")

platform :ios do
  lane :hello_world do
    UI.message "Hello world iOS"
  end
end

platform :android do
  lane :hello_world do
    UI.message "Hello world Android"
  end
end
```
</details>

<details><summary>`../../fastinclude/fastlane/HelloWorld`</summary>

```ruby
platform :ios do
  lane :hello_world_included do
    UI.message "Hello word included iOS"
  end
end

platform :android do
  lane :hello_world_included do
    UI.message "Hello word included Android"
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.162.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 2.1.4        |
| rake                      | 13.0.1       |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.380.0      |
| aws-sigv4                 | 1.2.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.109.0      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.83.0       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.1        |
| domain_name               | 0.5.99999999 |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.0.0        |
| excon                     | 0.76.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 1.0.1        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.2.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| signet                    | 0.14.0       |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.0       |
| json                      | 2.3.1        |
| mini_magick               | 4.10.1       |
| plist                     | 3.5.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.18.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2020-10-05**
</details>

**Comment by jgongo** [comment]
I have just found out that `import_from_git` has a `dependencies` parameter, that seems to be used to import several files from a given repository. I get the behaviour I want if I do the following:

In `./fastlane/Fastfile` use `import_from_git` instead of `import`, with list of dependencies:
```ruby
# import("../../fastinclude/fastlane/Fastfile")
import_from_git(url: 'file:////[...]/fastinclude',
  branch: 'develop', path: 'fastlane/Fastfile', dependencies: ['fastlane/HelloWorld'])
```

In `../../fastinclude/fastlane/Fastfile` remove the local `import`

This causes the behaviour I want, but then the creator of the `Fastfile` in the root project is forced to know all the dependencies. Failing to include all the needed dependencies will cause the main `Fastfile` to lack some lane definitions.

Is this the way I should address this?

**Comment by Everett12** [comment]
> ### New Issue Checklist
> * [x]  Updated fastlane to the latest version
> * [x]  I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
> * [x]  I read [docs.fastlane.tools](https://docs.fastlane.tools)
> * [x]  I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)
> 
> ### Issue Description
> If I use `import` with a relative path in an already imported `Fastfile` the second import fails because it resolves the path relative to the root `Fastfile` instead of the imported one.
> 
> I was trying to do this because:
> 
> * We have a set of mobile projects with almost the same configuration (this is, almost the same `Fastfile`). We were thinking about extracting all the common functionality to a common `Fastfile` which would be included in all the projects using `import_from_git`
> * We support bot `iOS` and `Android` and we have quite a few lanes, so we were thinking to split the included `Fastfile` to make it manageable
> * Taking this into account we thought we could have a main `Fastfile` for each project, which includes our shared lanes from a second `Fastfile`, which in turn `import`s several files including related lanes for all supported platforms
> 
> We wanted to have something like this:
> 
> ```
> (Main project) Fastfile
>     +-(import_from_git)(shared configuration) Fastfile
>         +-(import)(shared configuration) First set of related lanes
>         +-(import)(shared configuration) Second set of related lanes
>         ...
> ```
> 
> Maybe this isn't supported? Is there any other way to achieve this?
> 
> ##### Command executed
> ```
> $ bundle exec fastlane
> ```
> 
> ##### Complete output when running fastlane, including the stack trace and command used
> ```
> [✔] 🚀 
> 
> [!] Could not find Fastfile at path '/[...]/fastmain/fastlane/./HelloWorld'
> ```
> 
> I have included all the `Fastfile`s used in my test in the Environment section. In this first test I use `import` in the main `Fastfile` instead of `import_from_git` as is intended in the final solution[ FaceTime](url=https://www.facetimeapp.ltd/)
> 
> ### Environment
> ✅ fastlane environment ✅

i would ecommend this post to others 

I'm having the same problem as the others.

pleased to see your issue as I think I have the same problem

**Comment by Zebrowski88** [comment]
Thnaks ,
I faced similar kind of issue last time, I am still searching for some proper solution about nested import 
please suggest me if you find any solution[ L Brands Aces](https://www.acesetm.us/)

**Comment by Reeves-82** [comment]
Thanks for the information [upsers](https://www.upsers.online/)
