### ISSUE TITLE
[spaceship] AppStoreVersion properties are different between iTunes credentials VS App Store Connect API token

### ISSUE THREAD

**Issue by rogerluan** [fastlane/fastlane#17370]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I have a standalone ruby script that uses spaceship and while upgrading from Apple ID credentials to API token, my code crashes when trying to access a property from `AppStoreVersion` that isn't available anymore (`store_icon`).
Then I realized that a bunch of properties are not available, so I brought them here:

```ruby
// When logging in using App Store Connect API token:

Printing app.get_latest_app_store_version(platform: Spaceship::ConnectAPI::Platform::IOS) => #<Spaceship::ConnectAPI::AppStoreVersion:0x00007ff8881e4f78 
@id="d046d231-<redacted>-db9d4e7db180", 
@platform="IOS", 
@version_string="2.30.15", 
@app_store_state="READY_FOR_SALE", 
@copyright="2020 Tellus App, Inc.", 
@release_type="redacted", 
@earliest_release_date=redacted, 
@uses_idfa=redacted, 
@downloadable=redacted,
@created_date="redacted">
```

```ruby
// When logging in using Apple ID user/pass credentials:

Printing app.get_latest_app_store_version(platform: Spaceship::ConnectAPI::Platform::IOS) => #<Spaceship::ConnectAPI::AppStoreVersion:0x00007ff95d4ff9f8 
@id="d046d231-redacted-db9d4e7db180", 
@platform="IOS", 
@version_string="2.30.15", 
@app_store_state="READY_FOR_SALE", 
@store_icon={"templateUrl"=>"https://is2-ssl.mzstatic.com/image/thumb/Purple114/v4/24/f7/cc/<redacted>/AppIcon-0-0-1x_U007emarketing-0-0-0-7-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/{w}x{h}bb.{f}", "width"=>1024, "height"=>1024}, 
@watch_store_icon=redacted, 
@copyright="2020 Tellus App, Inc.", 
@release_type="redacted", 
@earliest_release_date=redacted, 
@uses_idfa=redacted, 
@is_watch_only=redacted, 
@downloadable=redacted, 
@created_date="redacted">
```

I dug a little bit into this and realized that the response from Apple itself is different depending on the credentials used. Idk why. Not sure if we can even do anything about it, but just thought about reporting it (maybe we need to send extra parameters to request specific data when using JWT 🤷 ).

##### Command executed

```ruby

require "spaceship"

# When logging in using username/password:
Spaceship::ConnectAPI.login(my_username, itc_password)

# When logging in using JWT:
Spaceship::ConnectAPI.auth(key_id: spaceship_connect_api_key_id, issuer_id: spaceship_connect_api_issuer_id, etc…)

app = Spaceship::ConnectAPI::App.find("my bundle id")
app.get_latest_app_store_version(platform: Spaceship::ConnectAPI::Platform::IOS)
```

##### Complete output when running fastlane, including the stack trace and command used

See above

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                                           |
| --------------------------- | ------------------------------------------------------------------------------- |
| OS                          | 10.15.6                                                                         |
| Ruby                        | 2.6.5                                                                           |
| Bundler?                    | true                                                                            |
| Git                         | git version 2.24.3 (Apple Git-128)                                              |
| Installation Source         | ~/Documents/Projects/app-store-connect-notifier/.vendor/ruby/2.6.0/bin/fastlane |
| Host                        | Mac OS X 10.15.6 (19G2021)                                                      |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.5/lib                                                     |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                                                     |
| Is contained                | false                                                                           |
| Is homebrew                 | false                                                                           |
| Is installed via Fabric.app | false                                                                           |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                                     |
| Xcode Version               | 12.0                                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.162.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| bundler                   | 2.1.4        |
| psych                     | 3.1.0        |
| stringio                  | 0.0.2        |
| strscan                   | 1.0.0        |
| rake                      | 13.0.1       |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| ast                       | 2.4.1        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.380.0      |
| aws-sigv4                 | 1.2.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.109.0      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.83.0       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.0.0        |
| excon                     | 0.76.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 1.0.1        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.2.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| signet                    | 0.14.0       |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.0       |
| json                      | 2.3.1        |
| mini_magick               | 4.10.1       |
| plist                     | 3.5.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.18.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| parallel                  | 1.19.2       |
| parser                    | 2.7.1.5      |
| rainbow                   | 3.0.0        |
| regexp_parser             | 1.8.1        |
| rexml                     | 3.2.4        |
| rubocop-ast               | 0.7.1        |
| ruby-progressbar          | 1.10.1       |
| rubocop                   | 0.92.0       |
</details>

*generated on:* **2020-10-03**
</details></pre>
</details>

**Comment by max-ott** [comment]
What kind of "role" does your App Store Connect API key have? (yes, that's a thing, learned it just a few weeks ago!)

**Comment by rogerluan** [comment]
@max-ott It has an `admin` "access":

<img width="117" alt="image" src="https://user-images.githubusercontent.com/8419048/95517927-5d4df080-0998-11eb-96f2-06016fc9c4b3.png">

**Comment by Arrington88** [comment]
Thanks for clarifying the difference between appstore version prperties and itunes credentials vs appstore connect api token keep suggesting such informative post [www.myaccountaccess.com](https://www.myaccountaccess.us/)

**Comment by Morell9312** [comment]
Facing same Error, please help me on [citefast](https://www.citefast.us/)

**Comment by Dinsen** [comment]
@rogerluan Did you find a solution for this?

We don't have any problems getting the App Store icon, but we are doing it like this:
``` ruby
app = Spaceship::ConnectAPI::App.find("some.bundle.id")
live_app = app.get_live_app_store_version
template_url = live_app.build.icon_asset_token['templateUrl']
icon_url = "#{File.dirname(template_url)}/167x167.png"
```

**Comment by rogerluan** [comment]
I did not @Dinsen ! I'll try that code of yours, though! 
Are you using the new App Store Connect API to authenticate, though?

**Comment by Dinsen** [comment]
> I did not @Dinsen ! I'll try that code of yours, though! 
> 
> Are you using the new App Store Connect API to authenticate, though? 

I'm pretty sure we do both auth key and username/password.
But can confirm when I'm at my desk again.

**Comment by Dinsen** [comment]
> > I did not @Dinsen ! I'll try that code of yours, though!
> > Are you using the new App Store Connect API to authenticate, though?
> 
> I'm pretty sure we do both auth key and username/password.
> But can confirm when I'm at my desk again.

Yup, we do both.

**Comment by rogerluan** [comment]
The issue happens only when authenticating using App Store Connect API key

**Comment by max-ott** [comment]
This is the expected behavior. The App Store Connect API (used when using an ASC API key) has limited featured compared to the „private“ API Apple uses on the App Store Connect Web (used when using Apple ID + password). Please check the official docs to see what is available: https://developer.apple.com/documentation/appstoreconnectapi/appstoreversion/attributes
