### ISSUE TITLE
Ruby extension on base class (`String`, `Hash`) undefined in Fastfile

### ISSUE THREAD

**Issue by felginep** [fastlane/fastlane#17379]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Let's take this contrived example:

```rb
class String
  def foo
    [self, "foo"].join("_")
  end
end

class Fiz
  def to_s
    "fiz"
  end
end

lane :foo_lane do
  puts "bar".foo
end

lane :fiz_lane do
  puts Fiz.new
end
```

It seems the extension on `String` is not found, whereas the `Fiz` class is. I'm not sure to understand why the `foo` method is `undefined`. Is it a bug or correct fastlane behavior ?

##### Command executed

Valid lane `bundle exec fastlane fiz_lane`
```
[✔] 🚀
[14:22:42]: Driving the lane 'fiz_lane' 🚀
[14:22:42]: fiz
[14:22:42]: fastlane.tools finished successfully 🎉
```

Invalid lane `bundle exec fastlane foo_lane`
```
[✔] 🚀
[14:23:59]: Driving the lane 'foo_lane' 🚀
+---------------+----------+
|       Lane Context       |
+---------------+----------+
| PLATFORM_NAME |          |
| LANE_NAME     | foo_lane |
+---------------+----------+
[14:23:59]: Error in your Fastfile at line 15
[14:23:59]:     13:
[14:23:59]:     14:	lane :foo_lane do
[14:23:59]:  => 15:	  puts "bar".foo
[14:23:59]:     16:	end
[14:23:59]:     17:
[14:24:00]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
bundler: failed to load command: fastlane (/Users/user/.rbenv/versions/2.6.5/bin/fastlane)
NoMethodError: [!] undefined method `foo' for "bar":String
Did you mean?  for
Did you mean?  for
  Fastfile:15:in `block in parsing_binding'
  /Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  /Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Users/user/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/bin/fastlane:23:in `<top (required)>'
  /Users/user/.rbenv/versions/2.6.5/bin/fastlane:23:in `load'
  /Users/user/.rbenv/versions/2.6.5/bin/fastlane:23:in `<top (required)>'
```

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.6                                     |
| Ruby                        | 2.6.5                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.17.0                          |
| Installation Source         | ~/.rbenv/versions/2.6.5/bin/fastlane        |
| Host                        | Mac OS X 10.15.6 (19G2021)                  |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.5/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.7                                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby

class String
  def foo
    [self, "foo"].join("_")
  end
end

class Fiz
  def to_s
    "fiz"
  end
end

lane :foo_lane do
  puts "bar".foo
end

lane :fiz_lane do
  puts Fiz.new
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.162.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 2.1.4        |
| rake                      | 13.0.1       |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.380.0      |
| aws-sigv4                 | 1.2.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.109.0      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.83.0       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.0.0        |
| excon                     | 0.76.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 1.0.1        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.2.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| signet                    | 0.14.0       |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.0       |
| json                      | 2.3.1        |
| mini_magick               | 4.10.1       |
| plist                     | 3.5.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.18.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2020-10-05**
</details>

**Comment by minuscorp** [comment]
For extensions, I put them in a separate file and require them whenever they're needed, that might help you.

**Comment by felginep** [comment]
Indeed the following trick works:

```rb
# fastlane/string_ext.rb
class String
  def foo
    [self, "foo"].join("_")
  end
end
```

```rb
#fastlane/Fastfile
require './string_ext'

class Fiz
  def to_s
    "fiz"
  end
end

lane :foo_lane do
  puts "bar".foo
end

lane :fiz_lane do
  puts Fiz.new
end
```

But I still don't get why I need to use the `require` like this.

**Comment by minuscorp** [comment]
Fastfile is not a common Ruby file and don't follow the same rules, so it is a common approach to split fastlane code from Ruby one

**Comment by felginep** [comment]
Ok so I made some digging and found the explanation. 

Behind the hood, fastlane uses a [`Fastlane::FastFile`](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/fast_file.rb) class that reads the Fastfile. During the parsing, a call to `eval` is [made](https://github.com/fastlane/fastlane/blob/55c2ad14205d53bceec783cbc577342ab791a171/fastlane/lib/fastlane/fast_file.rb#L61) with the content of the Fastfile.

That means the content of the Fastfile is evaluated in the context of the `Fastlane::Fastfile` class. Which means the classes `Fiz` and `String` are defined in the context of  `Fastlane::Fastfile`. We can convince ourself with the following example:

```rb
class String
  def foo
    [self, "foo"].join("_")
  end
end

class Fiz
  def to_s
    "fiz"
  end
end

lane :debug_lane do
  puts String
  puts Fiz
end
```

The output of `bundle exec fastlane debug_lane` produces

```
[✔] 🚀
Driving the lane 'debug_lane' 🚀
Fastlane::FastFile::String
Fastlane::FastFile::Fiz
fastlane.tools finished successfully 🎉
```

That explains why the `require` bypasses the `Fastlane::Fastfile` context.

If you do not want to split the `String` extension in another file, there is an alternative. The solution is to tell ruby that `String` is the ruby core class with the following:

```rb
class ::String
  def foo
    [self, "foo"].join("_")
  end
end

lane :foo_lane do
  puts "bar".foo
end
```

The output of `bundle exec fastlane foo_lane` is then correct:

```
[✔] 🚀
Driving the lane 'foo_lane' 🚀
bar_foo
fastlane.tools finished successfully 🎉
```
