### ISSUE TITLE
Shared App Store Connect API value in lane context only work with pilot

### ISSUE THREAD

**Issue by sarunw** [fastlane/fastlane#17385]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

From [App Store Connect API](https://docs.fastlane.tools/app-store-connect-api/#use-the-shared-value-in-lane-context) under "Use the shared value in lane context" section. I am convinced that I could use shared value across multiple actions.

```
The app_store_connect_api_key action sets Actions.lane_context[SharedValues::APP_STORE_CONNECT_API_KEY] and actions (like pilot) will automatically load the API Key from Actions.lane_context
```
But, it looks like it only supports `pilot` action.

##### Command executed

I only test with `match` and the following code asking for username and password, not picking up `api_key`.

```
app_store_connect_api_key(
      key_id: ENV['KEY_ID'],
      issuer_id: ENV['ISSUER_ID'],
      key_content: ENV['KEY_CONTENT'],
      duration: 1200, # optional
      in_house: false, # optional but may be required if using match/sigh
)

match()
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by rogerluan** [comment]
Hey @sarunw ! 👋 

Took me awhile to figure out where to inject this context, but I opened a PR to resolve this issue, could you help me by testing it? 🙏

**Comment by sarunw** [comment]
@rogerluan Sure, I can test it out for `match`.

**Comment by Rosemary8330** [comment]
Thanks for sharing your query I'm having the same problem as the others.

pleased to see your issue as I think I have the same problem [MyGreatLakes ](url=https://www.mygreatlakes.me/)

**Comment by polmum** [comment]
Hey!
I can confirm sigh works correctly.

**Comment by rogerluan** [comment]
Sweet, thanks for testing my PR and confirming @polmum 🚀
