### ISSUE TITLE
Error when creating certificates - ENTITY_ERROR.ATTRIBUTE.TYPE

### ISSUE THREAD

**Issue by barnaclebarnes** [fastlane/fastlane#17384]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Creating a certificate from `sync_code_signing` is producing an error.

```
Spaceship::UnexpectedResponse: [!] {
  "errors" : [ {
    "id" : "cd694b12-48f2-40be-8b15-af7fa17c5d16",
    "status" : "409",
    "code" : "ENTITY_ERROR.ATTRIBUTE.TYPE",
    "title" : "An attribute in the provided entity has the wrong type",
    "detail" : "Unexpected token (START_OBJECT), expected VALUE_STRING: Value is not string"
  } ]
}
```

Expected behaviour is to properly create a certificate.

##### Command executed

```
    sync_code_signing(type: "appstore",
                      storage_mode: "git",
                      git_branch: ENV["APPLE_DEVELOPER_TEAM_ID"],
                      git_url: "git@github.com:hidden/certificates.git",
                      team_id: ENV["APPLE_DEVELOPER_TEAM_ID"],
                      username: ENV["APPLE_DEVELOPER_LOGIN"],
                      app_identifier: ENV["APPLE_BUNDLE_ID"],
                      keychain_name: ENV["KEYCHAIN_NAME"],
                      keychain_password: ENV["KEYCHAIN_PASSWORD"])
```

##### Complete output when running fastlane, including the stack trace and command used

Seems to fail here:

```
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/spaceship/lib/spaceship/connect_api/api_client.rb:183:in `handle_response'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/spaceship/lib/spaceship/connect_api/provisioning/client.rb:73:in `proxy_post'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/spaceship/lib/spaceship/connect_api/provisioning/client.rb:37:in `post'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/spaceship/lib/spaceship/connect_api/provisioning/provisioning.rb:52:in `post_certificate'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/2.6.0/forwardable.rb:230:in `post_certificate'
```

<details>
  <pre>
mytours-rn git:(develop) be fastlane ios provision
[⠹] 🚀 WARNING: Nokogiri was built against LibXML version 2.9.10, but has dynamically loaded 2.9.4
[✔] 🚀
+------------------------------------+---------+----------------------------------------------------------------------------------+
|                                                          Used plugins                                                           |
+------------------------------------+---------+----------------------------------------------------------------------------------+
| Plugin                             | Version | Action                                                                           |
+------------------------------------+---------+----------------------------------------------------------------------------------+
| fastlane-plugin-yarn               | 1.2     | yarn                                                                             |
| fastlane-plugin-android_versioning | 0.5.3   | get_value_from_build increment_version_code set_value_in_build get_version_name  |
|                                    |         | increment_version_name get_version_code                                          |
| fastlane-plugin-cryptex            | 0.1.5   | cryptex cryptex_generate_keystore                                                |
+------------------------------------+---------+----------------------------------------------------------------------------------+

[10:32:39]: ----------------------------------------
[10:32:39]: --- Step: Verifying fastlane version ---
[10:32:39]: ----------------------------------------
[10:32:39]: Your fastlane version 2.162.0 matches the minimum requirement of 2.96.1  ✅
[10:32:41]: ------------------------------
[10:32:41]: --- Step: default_platform ---
[10:32:41]: ------------------------------
[10:32:41]: Driving the lane 'ios provision' 🚀
[10:32:41]: ---------------------
[10:32:41]: --- Step: produce ---
[10:32:41]: ---------------------

+----------------+--------------------------+
|        Summary for produce 2.162.0        |
+----------------+--------------------------+
| app_name       | City Art Walk - Tauranga |
| skip_itc       | true                     |
| team_id        | my_git_branch               |
| username       | someemail@gmail.com |
| app_identifier | com.mytoursapp.myappid   |
| sku            | 1601933561               |
| platform       | ios                      |
| language       | English                  |
| skip_devcenter | false                    |
+----------------+--------------------------+

[10:32:44]: [DevCenter] App 'com.mytoursapp.myappid' already exists, nothing to do on the Dev Center
[10:32:44]: -----------------------------------------------
[10:32:44]: --- Step: Switch to ios code_sign_sync lane ---
[10:32:44]: -----------------------------------------------
[10:32:44]: Cruising over to lane 'ios code_sign_sync' 🚖
[10:32:44]: -----------------------------
[10:32:44]: --- Step: unlock_keychain ---
[10:32:44]: -----------------------------
[10:32:44]: Unlocking keychain at path: /Users/barnaclebarnes/Library/Keychains/appstore.keychain-db
[10:32:44]: -------------------------------
[10:32:44]: --- Step: sync_code_signing ---
[10:32:44]: -------------------------------

+--------------------------------+--------------------------------------------------------------+
|                                   Summary for match 2.162.0                                   |
+--------------------------------+--------------------------------------------------------------+
| type                           | appstore                                                     |
| storage_mode                   | git                                                          |
| git_branch                     | my_git_branch                                                   |
| git_url                        | git@github.com:myorg/certificates.git                      |
| team_id                        | my_git_branch                                                   |
| username                       | someemail@gmail.com                                     |
| app_identifier                 | ["com.mytoursapp.myappid"]                                   |
| keychain_name                  | /Users/barnaclebarnes/Library/Keychains/appstore.keychain-db |
| keychain_password              | ********                                                     |
| readonly                       | false                                                        |
| generate_apple_certs           | true                                                         |
| skip_provisioning_profiles     | false                                                        |
| shallow_clone                  | false                                                        |
| clone_branch_directly          | false                                                        |
| force                          | false                                                        |
| force_for_new_devices          | false                                                        |
| skip_confirmation              | false                                                        |
| skip_docs                      | false                                                        |
| platform                       | ios                                                          |
| derive_catalyst_app_identifier | false                                                        |
| fail_on_name_taken             | false                                                        |
| skip_set_partition_list        | false                                                        |
| verbose                        | false                                                        |
+--------------------------------+--------------------------------------------------------------+

[10:32:44]: Cloning remote git repo...
[10:32:44]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[10:32:47]: Checking out branch my_git_branch...
[10:32:47]: 🔓  Successfully decrypted certificates repo
[10:32:47]: Verifying that the certificate and profile are still valid on the Dev Portal...
[10:32:50]: Couldn't find a valid code signing identity for distribution... creating one for you now

+-------------------------+--------------------------------------------------------------+
|                                Summary for cert 2.162.0                                |
+-------------------------+--------------------------------------------------------------+
| platform                | ios                                                          |
| development             | false                                                        |
| generate_apple_certs    | true                                                         |
| force                   | true                                                         |
| username                | someemail@gmail.com                                     |
| team_id                 | my_git_branch                                                   |
| keychain_path           | /Users/barnaclebarnes/Library/Keychains/appstore.keychain-db |
| keychain_password       | ********                                                     |
| skip_set_partition_list | false                                                        |
+-------------------------+--------------------------------------------------------------+

[10:32:50]: Starting login with user 'someemail@gmail.com'
[10:32:51]: Successfully logged in
[10:32:52]: An error occurred while verifying your certificates and profiles with the Apple Developer Portal.
[10:32:52]: If you already have your certificates stored in git, you can run `fastlane match` in readonly mode
[10:32:52]: to just install the certificates and profiles without accessing the Dev Portal.
[10:32:52]: To do so, just pass `readonly: true` to your match call.
+------------------+---------------+
|           Lane Context           |
+------------------+---------------+
| DEFAULT_PLATFORM | android       |
| PLATFORM_NAME    | ios           |
| LANE_NAME        | ios provision |
| PRODUCE_APPLE_ID |               |
+------------------+---------------+
[10:32:52]: {
  "errors" : [ {
    "id" : "cd694b12-48f2-40be-8b15-af7fa17c5d16",
    "status" : "409",
    "code" : "ENTITY_ERROR.ATTRIBUTE.TYPE",
    "title" : "An attribute in the provided entity has the wrong type",
    "detail" : "Unexpected token (START_OBJECT), expected VALUE_STRING: Value is not string"
  } ]
}

+------+-----------------------------------+-------------+
|                    fastlane summary                    |
+------+-----------------------------------+-------------+
| Step | Action                            | Time (in s) |
+------+-----------------------------------+-------------+
| 1    | Verifying fastlane version        | 0           |
| 2    | default_platform                  | 0           |
| 3    | produce                           | 2           |
| 4    | Switch to ios code_sign_sync lane | 0           |
| 5    | unlock_keychain                   | 0           |
| 💥   | sync_code_signing                 | 7           |
+------+-----------------------------------+-------------+

[10:32:52]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

bundler: failed to load command: fastlane (/Users/barnaclebarnes/.rbenv/versions/2.6.5/bin/fastlane)
Spaceship::UnexpectedResponse: [!] {
  "errors" : [ {
    "id" : "cd694b12-48f2-40be-8b15-af7fa17c5d16",
    "status" : "409",
    "code" : "ENTITY_ERROR.ATTRIBUTE.TYPE",
    "title" : "An attribute in the provided entity has the wrong type",
    "detail" : "Unexpected token (START_OBJECT), expected VALUE_STRING: Value is not string"
  } ]
}
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/spaceship/lib/spaceship/connect_api/api_client.rb:183:in `handle_response'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/spaceship/lib/spaceship/connect_api/provisioning/client.rb:73:in `proxy_post'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/spaceship/lib/spaceship/connect_api/provisioning/client.rb:37:in `post'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/spaceship/lib/spaceship/connect_api/provisioning/provisioning.rb:52:in `post_certificate'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/2.6.0/forwardable.rb:230:in `post_certificate'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/spaceship/lib/spaceship/connect_api/models/certificate.rb:88:in `create'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/cert/lib/cert/runner.rb:191:in `create_certificate'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/cert/lib/cert/runner.rb:54:in `run'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/cert/lib/cert/runner.rb:13:in `launch'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/match/lib/match/generator.rb:42:in `generate_certificate'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/match/lib/match/runner.rb:169:in `fetch_certificate'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/match/lib/match/runner.rb:96:in `run'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/actions/sync_code_signing.rb:13:in `run'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:186:in `block (2 levels) in parsing_binding'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:115:in `block (2 levels) in parsing_binding'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.162.0/bin/fastlane:23:in `<top (required)>'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/bin/fastlane:23:in `load'
  /Users/barnaclebarnes/.rbenv/versions/2.6.5/bin/fastlane:23:in `<top (required)>'
</pre>
</details>

### Environment

<details>
  <pre>
### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.162.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                             | Version | Update-Status |
| ---------------------------------- | ------- | ------------- |
| fastlane-plugin-yarn               | 1.2     | ✅ Up-To-Date  |
| fastlane-plugin-android_versioning | 0.5.3   | ✅ Up-To-Date  |
| fastlane-plugin-cryptex            | 0.1.5   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                | Version      |
| ---------------------------------- | ------------ |
| did_you_mean                       | 1.3.0        |
| slack-notifier                     | 2.3.2        |
| rouge                              | 2.0.7        |
| xcpretty                           | 0.3.0        |
| terminal-notifier                  | 2.0.0        |
| terminal-table                     | 1.8.0        |
| plist                              | 3.5.0        |
| CFPropertyList                     | 3.0.2        |
| multipart-post                     | 2.0.0        |
| word_wrap                          | 1.0.0        |
| tty-cursor                         | 0.7.1        |
| tty-spinner                        | 0.9.3        |
| babosa                             | 1.0.3        |
| colored                            | 1.2          |
| highline                           | 1.7.10       |
| commander-fastlane                 | 4.4.6        |
| faraday_middleware                 | 1.0.0        |
| gh_inspector                       | 1.1.3        |
| rubyzip                            | 2.3.0        |
| security                           | 0.1.3        |
| xcpretty-travis-formatter          | 1.0.0        |
| bundler                            | 2.1.4        |
| simctl                             | 1.6.8        |
| uber                               | 0.1.0        |
| declarative-option                 | 0.1.0        |
| representable                      | 3.0.4        |
| retriable                          | 3.1.2        |
| httpclient                         | 2.8.3        |
| google-api-client                  | 0.38.0       |
| nanaimo                            | 0.3.0        |
| colored2                           | 3.1.2        |
| claide                             | 1.0.3        |
| atomos                             | 0.1.3        |
| xcodeproj                          | 1.18.0       |
| unicode-display_width              | 1.7.0        |
| public_suffix                      | 4.0.6        |
| addressable                        | 2.7.0        |
| tty-screen                         | 0.8.1        |
| excon                              | 0.76.0       |
| unf_ext                            | 0.0.7.7      |
| unf                                | 0.1.4        |
| domain_name                        | 0.5.20190701 |
| http-cookie                        | 1.0.3        |
| faraday                            | 1.0.1        |
| faraday-cookie_jar                 | 0.0.7        |
| fastimage                          | 2.2.0        |
| json                               | 2.3.1        |
| mini_magick                        | 4.10.1       |
| dotenv                             | 2.7.6        |
| naturally                          | 2.2.0        |
| jwt                                | 2.2.2        |
| declarative                        | 0.0.20       |
| mini_mime                          | 1.0.2        |
| multi_json                         | 1.15.0       |
| signet                             | 0.14.0       |
| os                                 | 1.1.1        |
| memoist                            | 0.16.2       |
| googleauth                         | 0.13.1       |
| rake                               | 13.0.1       |
| digest-crc                         | 0.6.1        |
| google-cloud-errors                | 1.0.1        |
| google-cloud-env                   | 1.3.3        |
| google-cloud-core                  | 1.5.0        |
| google-cloud-storage               | 1.29.1       |
| emoji_regex                        | 3.0.0        |
| aws-eventstream                    | 1.1.0        |
| aws-sigv4                          | 1.2.2        |
| aws-partitions                     | 1.380.0      |
| jmespath                           | 1.4.0        |
| aws-sdk-core                       | 3.109.1      |
| aws-sdk-kms                        | 1.39.0       |
| aws-sdk-s3                         | 1.83.0       |
| forwardable                        | 1.2.0        |
| logger                             | 1.3.0        |
| stringio                           | 0.0.2        |
| ipaddr                             | 1.2.2        |
| openssl                            | 2.1.2        |
| ostruct                            | 0.1.0        |
| strscan                            | 1.0.0        |
| date                               | 2.0.0        |
| fileutils                          | 1.1.0        |
| etc                                | 1.0.1        |
| io-console                         | 0.4.7        |
| zlib                               | 1.0.0        |
| mini_portile2                      | 2.4.0        |
| nokogiri                           | 1.10.10      |
| rexml                              | 3.2.4        |
| psych                              | 3.1.0        |
| mutex_m                            | 0.1.0        |
| oj                                 | 3.7.12       |
| bigdecimal                         | 1.4.1        |
| webrick                            | 1.4.2        |
| fastlane-plugin-yarn               | 1.2          |
| fastlane-plugin-android_versioning | 0.5.3        |
| commander                          | 4.4.6        |
| fastlane-plugin-cryptex            | 0.1.5        |
</pre>
</details>

**Comment by barnaclebarnes** [comment]
Running this from the command lane seems to work OK though:

`bundle exec fastlane match appstore --verbose --storage_mode=git --git_branch="ABCDEYKK6" --git_url="git@github.com:certs/certificates.git" --team_id="ABCDEYKK6" --username="someuser@stqry.com" --app_identifier="com.mytoursapp.someapp" --keychain_name="/Users/barnaclebarnes/Library/Keychains/appstore.keychain-db" --keychain_password="secret"`

**Comment by CovertLeopard** [comment]
@barnaclebarnes We just ran into this same error on 2.163.0.  

We use this in a CI environment so we can't necessarily run a manual command each time we need to create certs.  Have you had any luck figuring it out since you logged this?  We are kind of stuck right now.

**Comment by CovertLeopard** [comment]
This is a regression. We reverted Fastlane from 2.163.0 to 2.161.0 and it
resolved the issue. Based on this issue info, the breaking version appears
to be 2.162.0

**Comment by rogerluan** [comment]
Could be a regression introduced in https://github.com/fastlane/fastlane/pull/17291

@joshdholtz could you take a look? 🙈 Thanks in advance!

**Comment by joshdholtz** [comment]
Can do can do!
