### ISSUE TITLE
Fastlane upload to testflight is failing

### ISSUE THREAD

**Issue by userException** [fastlane/fastlane#17394]
**Version:** 2.162.0

Error:  Build is not in an externally assignable state.

**Full trace:**

Traceback (most recent call last):
	34: from /usr/local/bin/fastlane:23:in `<main>'
	33: from /usr/local/bin/fastlane:23:in `load'
	32: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/bin/fastlane:23:in `<top (required)>'
	31: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	30: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	29: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	28: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	27: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	26: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	25: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	24: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	23: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	22: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	21: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	20: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	19: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	16: from Fastfile:174:in `block (2 levels) in parsing_binding'
	15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:27:in `run'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/pilot/lib/pilot/build_manager.rb:61:in `upload'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/pilot/lib/pilot/build_manager.rb:171:in `distribute'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/pilot/lib/pilot/build_manager.rb:398:in `distribute_build'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/spaceship/lib/spaceship/connect_api/models/build.rb:140:in `add_beta_groups'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `add_beta_groups_to_build'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:191:in `add_beta_groups_to_build'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/spaceship/lib/spaceship/connect_api/api_client.rb:124:in `post'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/spaceship/lib/spaceship/connect_api/api_client.rb:188:in `handle_response': [!] Build is not assignable. - Build is not in an externally assignable state. (Spaceship::UnexpectedResponse)

**Comment by jefernandez** [comment]
We have now an old issue: https://github.com/fastlane/fastlane/issues/16596

This is my log:
DEBUG [2020-10-07 17:33:38.36]: /Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/itms/java/bin/java -Djava.ext.dirs=/Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/itms/java/lib/ext -XX:NewSize=2m -Xms32m -Xmx1024m -Xms1024m -Djava.awt.headless=true -Dsun.net.http.retryPost=false -jar /Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/itms/lib/itmstransporter-launcher.jar -m upload -u bitrise@tymit.io -p YourPassword -f /var/folders/rf/2zhzsp6d5yqdgzkgvhdn1cfc0000gp/T/d20201007-13386-m4kdyl/1400849426.itmsp -t DAV,Signiant -k 100000 2>&1
WARN [2020-10-07 17:33:38.44]: [33m[iTMSTransporter] -Djava.ext.dirs=/Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/itms/java/lib/ext is not supported.  Use -classpath instead.
[0m
WARN [2020-10-07 17:33:38.44]: [33m[iTMSTransporter] Error: Could not create the Java Virtual Machine.
[0m
WARN [2020-10-07 17:33:38.44]: [33m[iTMSTransporter] Error: A fatal exception has occurred. Program will exit.
[0m
INFO [2020-10-07 17:33:38.44]: iTunes Transporter output above ^

And my fastlane env:

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.7                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.7 (19H2)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.0.1                                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.162.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 1.0.1        |
| faraday_middleware        | 1.0.0        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| uber                      | 0.1.0        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| signet                    | 0.14.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| nanaimo                   | 0.3.0        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.18.0       |
| public_suffix             | 4.0.6        |
| tty-screen                | 0.8.1        |
| excon                     | 0.76.0       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| fastimage                 | 2.2.0        |
| json                      | 2.3.1        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.4        |
| jwt                       | 2.2.2        |
| declarative               | 0.0.20       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| memoist                   | 0.16.2       |
| googleauth                | 0.13.1       |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-env          | 1.3.3        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.0       |
| emoji_regex               | 3.0.0        |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-partitions            | 1.380.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.109.0      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.83.0       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>


*generated on:* **2020-10-07**
</details>

**Comment by alyssawolejko** [comment]
I'm also having the same issue with Fastlane 2.162.0 and XCode 12

```
WARN [2020-10-07 19:01:09.84]: [iTMSTransporter] Error: Could not find or load main class 2.app.Contents.SharedFrameworks.ContentDeliveryServices.framework.Versions.A.itms.macOS.lib:.Users.Library.Java.Extensions:.Library.Java.Extensions:.Network.Library.Java.Extensions:.System.Library.Java.Extensions:.usr.lib.java:.

WARN [2020-10-07 19:01:09.84]: [iTMSTransporter] Caused by: java.lang.ClassNotFoundException: 2.app.Contents.SharedFrameworks.ContentDeliveryServices.framework.Versions.A.itms.macOS.lib:.Users.Library.Java.Extensions:.Library.Java.Extensions:.Network.Library.Java.Extensions:.System.Library.Java.Extensions:.usr.lib.java:.

INFO [2020-10-07 19:01:09.84]: iTunes Transporter output above ^
ERROR [2020-10-07 19:01:09.84]: The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
```


<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.6                                     |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.rvm/gems/ruby-2.6.3/bin/fastlane         |
| Host                        | Mac OS X 10.15.6 (19G2021)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.3/lib                |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.0.1                                      |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_require 'dotenv'
require './helpers'


# iOS
APP_NAME = ENV["APP_NAME"]
XCODEPROJ = "ios/#{ENV["XCODEPROJ_FILENAME"]}.xcodeproj"
ICON_PATH = 'fastlane/metadata/app_icon.png'
XCODEWORKSPACE = "ios/#{ENV["XCODEPROJ_FILENAME"]}.xcworkspace"

CONTACT_FIRST_NAME=''
CONTACT_LAST_NAME=''
CONTACT_EMAIL=''
CONTACT_PHONE=''

lane :ios_icons do
  appicon(
    appicon_image_file: ICON_PATH,
    appicon_devices: [:iphone, :ios_marketing],
    appicon_path: "ios/#{ENV["XCODEPROJ_FILENAME"]}/Images.xcassets"
  )
end

lane :ios_badge do
  add_badge(
    alpha: false,
    dark: false,
    no_badge: true,
    shield: "#{SERVER.capitalize}-#{VERSION_NUMBER}.#{BUILD_NUMBER}-red",
    glob: "/ios/#{ENV["XCODEPROJ_FILENAME"]}/Images.xcassets/AppIcon.appiconset/*.{png,PNG}"
  )
end

lane :android_icons do
  android_appicon(
    appicon_image_file: ICON_PATH,
    appicon_path: './android/app/src/main/res/mipmap'
  )
end

lane :android_badge do
  add_badge(
    alpha: false,
    dark: false,
    no_badge: true,
    shield: "#{SERVER.capitalize}-#{VERSION_NAME}-red",
    glob: "/android/app/src/main/res/mipmap-*/*.{png, PNG}"
  )
end

platform :ios do
  before_all do |lane, options|
    if (options[:server])
      SERVER = options[:server]
    else 
      if lane == :certs
        SERVER = UI.input("Please choose which App Store account to get certificates/profiles from ('dev' or 'production'):")
      else
        SERVER = UI.input("Please input which server the app is pointing to ('dev', 'staging' or 'production')")
      end
    end
    if SERVER == 'dev'
      VERSION_NUMBER = "100"
    elsif SERVER == 'staging' || SERVER == 'production'
      if (options[:version])
        VERSION_NUMBER = options[:version]
      else
        VERSION_NUMBER = UI.input("Please input the Version number to be displayed in the App Store (e.g. 1.0.1): ")
      end
      if SERVER == 'staging'
        DEV_BUILD_NUMBER = UI.input("Enter the Dev Build Number which has corresponding code for this Staging build:")
      end
    else
      UI.abort_with_message!("########## Invalid server input. Aborting lane. ##########")
    end
    if lane == :push
      changelog = UI.input("Enter the text for the changelog (Min. length 10 characters)\nTo indicate a new line, add a semicolon(;) to the end of the line (e.g. Line1;Line2;Line3):")
      changelog = changelog.split(';').join("\n")
      if SERVER === "staging"
        CHANGELOG = "Built from Dev ##{DEV_BUILD_NUMBER}\n#{changelog}"
      else
        CHANGELOG = changelog
      end
    end
    sh("cp ../.env.#{SERVER} ../.env")
    Dotenv.overload "../.env.#{SERVER}"
  end

  desc "Get Apple Developer Portal certificates and provisioning profiles necessary for deployment"
  lane :certs do
    # match(
    #   git_branch: SERVER,
    #   type: "adhoc",
    #   readonly: true
    # )
    match(
      git_branch: 'dev',
      type: "appstore",
      readonly: true
    )
  end

  desc "Configure Xcode settings"
  lane :configure do
    # https://docs.fastlane.tools/actions/update_code_signing_settings/
    update_code_signing_settings(
      path: XCODEPROJ,
      team_id: ENV["TEAM_ID"],
      use_automatic_signing: false,
      code_sign_identity: "iPhone Developer",
      profile_name: ENV["DEVELOPMENT_PROFILE_NAME"],
      bundle_identifier: ENV["IOS_ID"]
    )

    build_number = latest_testflight_build_number(
      version: VERSION_NUMBER,
      initial_build_number: 0
    ).to_i

    BUILD_NUMBER = build_number + 1

    if SERVER === "production" || SERVER === 'staging'
      if UI.confirm("Is this the correct build number? --- App Store Version #{VERSION_NUMBER} - Build #{BUILD_NUMBER} ---")
        UI.success("Proceeding to create app icons")
      else
        BUILD_NUMBER = UI.input("Please input the correct build number: ")
      end
    end


    increment_version_number_in_plist(
      version_number: VERSION_NUMBER,
      xcodeproj: XCODEPROJ,
      scheme: ENV["XCODEPROJ_FILENAME"]
    )

    increment_build_number(
      build_number: BUILD_NUMBER, # specify specific build number (optional, omitting it increments by one)
      xcodeproj: XCODEPROJ # You must specify the path to your main Xcode project if it is not in the project root directory
    )

    update_info_plist(
      xcodeproj: XCODEPROJ,
      plist_path: "./../ios/#{ENV["XCODEPROJ_FILENAME"]}/Info.plist",
      block: proc do |plist|
        plist["CFBundleDisplayName"] = SERVER === "production" ? APP_NAME : "#{APP_NAME} #{SERVER.upcase}"
      end
    )

    ios_icons

    if SERVER != "production"
      ios_badge
    end

  end

  desc "Configure Xcode settings and run app in iPhone Simulator"
  lane :play do
    configure
    device = UI.input("Select Simulator:\n1. iPhone 8\n2. iPhone 11") == "1" ? "iPhone 8" : "iPhone 11"
    sh("cd .. && ENVFILE=.env.#{SERVER} react-native run-ios --simulator='#{device}'")
  end

  desc "Build and upload to Testflight"
  lane :push do
    configure
    File.open("metadata/#{SERVER == "production" ? 'Client' : 'ADK'}/en-US/release_notes.txt", "w") { |f| f.puts CHANGELOG }
    # https://docs.fastlane.tools/actions/xcversion/
    xcversion(
      version: ENV["XCODE_VERSION"]
      )
    # https://docs.fastlane.tools/actions/automatic_code_signing/#automatic_code_signing
    update_code_signing_settings(
      path: XCODEPROJ,
      team_id: ENV["TEAM_ID"],
      use_automatic_signing: false,
      code_sign_identity: "iPhone Distribution",
      profile_name: ENV["PROVISIONING_PROFILE_NAME"]
    )
    # https://docs.fastlane.tools/actions/build_app/
    build_app(
      workspace: XCODEWORKSPACE,
      scheme: ENV["XCODEPROJ_FILENAME"],
      output_name: ENV["XCODEPROJ_FILENAME"], # specify the name of the .ipa file to generate (including file extension)
      output_directory: "./ipa",
      clean: true,
      silent: true
    )


    CONTACT_FIRST_NAME = File.read("metadata/#{SERVER == "production" ? 'Client' : 'ADK'}/review_information/first_name.txt")
    CONTACT_LAST_NAME = File.read("metadata/#{SERVER == "production" ? 'Client' : 'ADK'}/review_information/last_name.txt")
    CONTACT_EMAIL = File.read("metadata/#{SERVER == "production" ? 'Client' : 'ADK'}/review_information/email_address.txt")
    CONTACT_PHONE = File.read("metadata/#{SERVER == "production" ? 'Client' : 'ADK'}/review_information/phone_number.txt")


    # https://docs.fastlane.tools/actions/pilot/
    upload_to_testflight(
      skip_waiting_for_build_processing: false,
      notify_external_testers: false,
      uses_non_exempt_encryption: false,
      beta_app_review_info: {
        contact_email: CONTACT_EMAIL,
        contact_first_name: CONTACT_FIRST_NAME,
        contact_last_name: CONTACT_LAST_NAME,
        contact_phone: CONTACT_PHONE
      },
      localized_build_info: {
        "default": {
          whats_new: "#{CHANGELOG}",
        }
      }
    )
     # https://docs.fastlane.tools/actions/appstore/
    deliver( # upload metadata only
      metadata_path: "./fastlane/metadata/#{SERVER == "production" ? 'Client' : 'ADK'}",
      force: true,
      skip_binary_upload: true
    )
  end
end

platform :android do
  before_all do |lane, options|
    if (options[:server])
      SERVER = options[:server]
    else
      SERVER = UI.input("Please input which server the app is pointing to ('dev', 'staging' or 'production')")
    end
    if SERVER == 'dev'
      VERSION_NUMBER = "100"
    elsif SERVER == 'staging' || SERVER == 'production'
      if (options[:version])
        VERSION_NAME = options[:version]
      else
        VERSION_NAME = UI.input("Please input the Version number to be displayed in the Google Play Store (e.g. 1.0.1): ")
      end
      if SERVER == 'staging'
        DEV_BUILD_NUMBER = UI.input("Enter the Dev Build Number which has corresponding code for this Staging build:")
      end
    else
      UI.abort_with_message!("########## Invalid server input. Aborting lane. ##########")
    end
    if lane == :push
      changelog = UI.input("Enter the text for the changelog (Min. length 10 characters)\nTo indicate a new line, add a semicolon(;) to the end of the line (e.g. Line1;Line2;Line3):")
      changelog = changelog.split(';').join("\n")
      if SERVER === "staging"
        CHANGELOG = "Built from Dev ##{DEV_BUILD_NUMBER}\n#{changelog}"
      else
        CHANGELOG = changelog
      end
    end
    sh("cp ../.env.#{SERVER} ../.env")
    Dotenv.overload "../.env.#{SERVER}"
  end

  desc "Configure Android Studio settings"
  lane :configure do
    internal = google_play_track_version_codes( track: 'internal' ).first.to_i
    alpha = google_play_track_version_codes( track: 'alpha' ).first.to_i
    beta = google_play_track_version_codes( track: 'beta' ).first.to_i
    production = google_play_track_version_codes( track: 'production' ).first.to_i

    VERSION_CODE = ([internal, alpha, beta, production].max + 1).to_s

    project_version_name = get_version_name
    version_name = project_version_name.split('.')

    if version_name.length === 3
      build_num = version_name[2].to_i
    elsif version_name.length === 2 || version_name.length === 1
      build_num = 0
    end

    if SERVER == "dev"
      if UI.confirm("Is this the correct build number? --- Build #{build_num + 1}")
        BUILD_NUMBER = build_num + 1
      else
        BUILD_NUMBER = UI.input("Please input the build number to upload: ")
      end
      VERSION_NAME = "#{VERSION_NUMBER}.#{BUILD_NUMBER}"
    end

    set_value_in_build(
      key: "versionName",
      value: VERSION_NAME
    )
    set_value_in_build(
      key: "versionCode",
      value: VERSION_CODE
    )

    update_android_strings(
      block: lambda { |strings|
        strings['app_name'] = SERVER == "production" ? APP_NAME : "#{APP_NAME} #{SERVER.upcase}"
      }
    )

    android_icons

    if SERVER != "production"
      android_badge
    end
  end

  desc "Configure Android Studio settings and run app in Simulator (NOTE: must have simulator open when running lane)"
  lane :play do
    configure
    UI.confirm("Is your Android Simulator running? If not, please open the simulator before proceeding.")
    sh("cd .. && cd android && ENVFILE=.env.#{SERVER} && ./gradlew clean install#{SERVER.capitalize}Debug && cd ..")
  end

  desc "Build and upload to Internal Test Track on Google Play Console"
  lane :push do
    configure
    File.open("metadata/#{SERVER == "production" ? 'Client' : 'ADK'}/android/en-US/changelogs/#{VERSION_CODE}.txt", "w") { |f| f.puts CHANGELOG }

    # gradle: https://docs.fastlane.tools/actions/gradle/
    gradle(
      project_dir: './android',
      task: 'clean assemble',
      flavor: SERVER,
      build_type: 'Release'
    )

    # https://docs.fastlane.tools/actions/upload_to_play_store/#upload_to_play_store
    upload_to_play_store(
      metadata_path:"./fastlane/metadata/#{SERVER == "production" ? 'Client' : 'ADK'}/android",
      track: returnAndroidTrackForServer(SERVER),
      apk: "./android/app/build/outputs/apk/#{SERVER}/release/app-#{SERVER}-release.apk",
    )
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
for_platform :ios do
  app_identifier ENV["IOS_ID"] # The bundle identifier of your app
  apple_id ENV["USERNAME"]
  team_id ENV["TEAM_ID"]
  team_name ENV["TEAM_NAME"]
  itc_team_name ENV["TEAM_NAME"]
end

for_platform :android do
  package_name ENV["ANDROID_ID"] # The bundle identifier of your app
  json_key_file ENV["JSON_KEY"]
end
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.162.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                                 | Version | Update-Status      |
| -------------------------------------- | ------- | ------------------ |
| fastlane-plugin-appicon                | 0.15.0  | ✅ Up-To-Date       |
| fastlane-plugin-badge                  | 1.4.0   | ✅ Up-To-Date       |
| fastlane-plugin-android_versioning     | 0.5.3   | ✅ Up-To-Date       |
| fastlane-plugin-versioning             | 0.4.3   | 🚫 Update available |
| fastlane-plugin-update_android_strings | 0.1.0   | ✅ Up-To-Date       |


<details><summary><b>Loaded gems</b></summary>

| Gem                                    | Version      |
| -------------------------------------- | ------------ |
| did_you_mean                           | 1.3.0        |
| executable-hooks                       | 1.6.0        |
| bundler-unload                         | 1.0.2        |
| rubygems-bundler                       | 1.4.5        |
| bundler                                | 1.17.3       |
| etc                                    | 1.0.1        |
| forwardable                            | 1.2.0        |
| rake                                   | 13.0.1       |
| CFPropertyList                         | 3.0.2        |
| public_suffix                          | 4.0.6        |
| addressable                            | 2.7.0        |
| atomos                                 | 0.1.3        |
| aws-eventstream                        | 1.1.0        |
| aws-partitions                         | 1.380.0      |
| aws-sigv4                              | 1.2.2        |
| jmespath                               | 1.4.0        |
| aws-sdk-core                           | 3.109.1      |
| aws-sdk-kms                            | 1.39.0       |
| aws-sdk-s3                             | 1.83.0       |
| babosa                                 | 1.0.4        |
| curb                                   | 0.9.10       |
| fastimage                              | 2.2.0        |
| colored                                | 1.2          |
| highline                               | 1.7.10       |
| commander-fastlane                     | 4.4.6        |
| dotenv                                 | 2.7.6        |
| emoji_regex                            | 3.0.0        |
| excon                                  | 0.76.0       |
| multipart-post                         | 2.0.0        |
| faraday                                | 1.0.1        |
| unf_ext                                | 0.0.7.7      |
| unf                                    | 0.1.4        |
| domain_name                            | 0.5.20190701 |
| http-cookie                            | 1.0.3        |
| faraday-cookie_jar                     | 0.0.7        |
| faraday_middleware                     | 1.0.0        |
| gh_inspector                           | 1.1.3        |
| jwt                                    | 2.2.2        |
| memoist                                | 0.16.2       |
| multi_json                             | 1.15.0       |
| os                                     | 1.1.1        |
| signet                                 | 0.14.0       |
| googleauth                             | 0.13.1       |
| httpclient                             | 2.8.3        |
| mini_mime                              | 1.0.2        |
| declarative                            | 0.0.20       |
| declarative-option                     | 0.1.0        |
| uber                                   | 0.1.0        |
| representable                          | 3.0.4        |
| retriable                              | 3.1.2        |
| google-api-client                      | 0.38.0       |
| digest-crc                             | 0.6.1        |
| google-cloud-env                       | 1.3.3        |
| google-cloud-errors                    | 1.0.1        |
| google-cloud-core                      | 1.5.0        |
| google-cloud-storage                   | 1.29.1       |
| json                                   | 2.3.1        |
| mini_magick                            | 4.10.1       |
| plist                                  | 3.5.0        |
| rubyzip                                | 2.3.0        |
| security                               | 0.1.3        |
| naturally                              | 2.2.0        |
| simctl                                 | 1.6.8        |
| slack-notifier                         | 2.3.2        |
| terminal-notifier                      | 2.0.0        |
| unicode-display_width                  | 1.7.0        |
| terminal-table                         | 1.8.0        |
| tty-screen                             | 0.8.1        |
| tty-cursor                             | 0.7.1        |
| tty-spinner                            | 0.9.3        |
| word_wrap                              | 1.0.0        |
| claide                                 | 1.0.3        |
| colored2                               | 3.1.2        |
| nanaimo                                | 0.3.0        |
| xcodeproj                              | 1.18.0       |
| rouge                                  | 2.0.7        |
| xcpretty                               | 0.3.0        |
| xcpretty-travis-formatter              | 1.0.0        |
| badge                                  | 0.12.0       |
| fastlane-plugin-android_versioning     | 0.5.3        |
| fastlane-plugin-appicon                | 0.15.0       |
| fastlane-plugin-badge                  | 1.4.0        |
| ox                                     | 2.13.2       |
| fastlane-plugin-update_android_strings | 0.1.0        |
| fastlane-plugin-versioning             | 0.4.3        |
| xcode-install                          | 2.6.6        |
</details>


*generated on:* **2020-10-08**
</details>

**Comment by userException** [comment]
I shifted to an older successful commit for my code and it worked. What I can see is from the moment I updated an SDK which requires MixPanel as a dependency to be included via pods, I see this error. If I go back to the commit when this SDK didn't require MixPanel everything worked fine.

**Comment by Wbqqqq** [comment]
same issue, How to fix?
