### ISSUE TITLE
	conflicting dependencies faraday (~> 0.12) and faraday (~> 1.0)   Activated faraday-1.0.0

### ISSUE THREAD

**Issue by colondeethpark** [fastlane/fastlane#17409]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.6                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.6 (19G2021)                                     |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.0.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | ko_KR.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do	
    increment_build_number(
build_number: latest_testflight_build_number + 1,
xcodeproj: "simkoong.xcodeproj")
    build_app(
	workspace: "simkoong.xcworkspace",
	configuration: "Release",
 	scheme: "simkoong"
)
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  end
	

desc "개발 아카이브 후 디폴로이 올리기 "
lane :dev_lane do
    clear_derived_data
    gym(
        scheme: "simkoong",
	configuration: "Debug",
        export_method: "development",
        clean: false,
        output_directory: "/Users/taeho/Desktop/simkoong_dev"       
    )
  deploygate(
  api_token: "470d8b6e9415a900a775f215d4151d1704ef1037",
  user: "colondee",
  ipa: "/Users/taeho/Desktop/simkoong_dev/simkoong.ipa",
  message: "ios 4.19.3(임시) 심쿵 개발 이성검색 맞춤이성 - 태그 중복 선택시 팝업 문구 변경",
  release_note: "ios 4.19.3(임시) 심쿵 개발 이성검색 맞춤이성 - 태그 중복 선택시 팝업 문구 변경",
  distribution_key: "85096c2ff95d8790bda8c71260ccc6fd5db60988",
  distribution_name: "test"
)
end


desc "개발디폴로이 올리기"
lane :dev_gate_lane do
    clear_derived_data  
  deploygate(
  api_token: "470d8b6e9415a900a775f215d4151d1704ef1037",
  user: "colondee",
  ipa: "/Users/taeho/Desktop/simkoong_dev/simkoong.ipa",
  message: "ios 4.19.3(임시) 심쿵 개발 이성검색 맞춤이성 - 태그 중복 선택시 팝업 문구 변경",
  release_note: "ios 4.19.3(임시) 심쿵 개발 이성검색 맞춤이성 - 태그 중복 선택시 팝업 문구 변경",
  distribution_key: "85096c2ff95d8790bda8c71260ccc6fd5db60988",
  distribution_name: "test"
)
end

desc "운영 아카이브 "
lane :dis_lane do
    clear_derived_data
    gym(
        scheme: "simkoong",
	configuration: "Release",
        export_method: "ad-hoc",
        clean: false,
        output_directory: "/Users/taeho/Desktop/simkoong_dis"
    )
deploygate(
  api_token: "470d8b6e9415a900a775f215d4151d1704ef1037",
  user: "colondee",
  ipa: "/Users/taeho/Desktop/simkoong_dis/simkoong.ipa",
  message: "ios 4.19.3(임시) 심쿵 운영 이성검색 맞춤이성 - 태그 중복 선택시 팝업 문구 변경",
  release_note: "ios 4.19.3(임시) 심쿵 운영 이성검색 맞춤이성 - 태그 중복 선택시 팝업 문구 변경",
  distribution_key: "85096c2ff95d8790bda8c71260ccc6fd5db60988",
  distribution_name: "test1"
)

end
desc "디폴로이 운영올리기"
lane :dis_gate_lane do
    clear_derived_data  
  deploygate(
  api_token: "470d8b6e9415a900a775f215d4151d1704ef1037",
  user: "colondee",
  ipa: "/Users/taeho/Desktop/simkoong_dis/simkoong.ipa",
  message: "ios 4.19.3(임시) 심쿵 운영 이성검색 맞춤이성 - 태그 중복 선택시 팝업 문구 변경",
  release_note: "ios 4.19.3(임시) 심쿵 운영 이성검색 맞춤이성 - 태그 중복 선택시 팝업 문구 변경",
  distribution_key: "85096c2ff95d8790bda8c71260ccc6fd5db60988",
  distribution_name: "test"
)
end


end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.colondee.simkoong") # The bundle identifier of your app
apple_id("qkralekf@gmail.com") # Your Apple email address

itc_team_id("117167872") # App Store Connect Team ID
team_id("YKC68J5624") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.152.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.16.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.76.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.9.5        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.0.1        |
| googleauth                | 0.9.0        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.4.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.380.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.109.1      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.83.0       |
| faraday                   | 0.17.3       |
| signet                    | 0.14.0       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>
] </pre>
</details>

fastlane update  error 

 Error installing fastlane:
	conflicting dependencies faraday (~> 0.12) and faraday (~> 1.0)
  Activated faraday-1.0.0
  which does not match conflicting dependency (~> 0.12)

  Conflicting dependency chains:
    fastlane (= 2.162.0), 2.162.0 activated, depends on
    faraday (~> 1.0), 1.0.0 activated

  versus:
    fastlane (= 2.162.0), 2.162.0 activated, depends on
    google-api-client (>= 0.37.0, < 0.39.0), 0.37.0 activated, depends on
    googleauth (~> 0.9), 0.9.0 activated, depends on
    faraday (~> 0.12)

  Gems matching faraday (~> 0.12):
    faraday-0.17.3, faraday-0.17.1
Nothing to update

whiy update error?

**Comment by rogerluan** [comment]
Hey @colondeethpark 👋 

First, I highly encourage you to use bundler instead of installing fastlane directly in the system. It's a lot easier to manage dependencies 👍 
However, to fix your issue, I see that you probably need to update more dependencies other than fastlane so that their requirements don't conflict with each other. Try updating `google-api-client` to the latest version for instance (I am using 0.38.0 instead of 0.37.0, for reference). If that doesn't work, try updating `googleauth`, try uninstalling old versions of `faraday`, etc. This is tricky in non-bundler envs 😬 
Let me know if you need further guidance 🙏 good luck!

**Comment by taylor988** [comment]
I faced similar kind of issue last time, I am still searching for some proper solution
I have exactly the same problem.  Anyone got a suggestion?  [Mypascoconnect](https://www.mypascoconnect.website/)

**Comment by Dele88** [comment]
I faced similar kind of issue last time, I am still searching for some proper solution similar error with conflict dependencies faraday please suggest any answer , keep share[ TellPopeyes Survey ](https://www.tellpopeyes.buzz/)

**Comment by Jones934** [comment]
I am able to install, because of conflict [myPennMedicine Login](https://mypennmedicine.us/)
