### ISSUE TITLE
Error installing fastlane: faraday requires Ruby version >= 2.3.

### ISSUE THREAD

**Issue by YWD** [fastlane/fastlane#17414]
I don't know if fastlane installed correctly on my mac, and I do have a .fastlane folder in my user directory, and ./bin/fastlane command etc. below is the detail:
![1](https://user-images.githubusercontent.com/8605395/95540383-3f799d80-0a23-11eb-85a9-17ecee4c2834.png)
![2](https://user-images.githubusercontent.com/8605395/95540396-46081500-0a23-11eb-812f-467f7c203d20.png)
![3](https://user-images.githubusercontent.com/8605395/95540399-486a6f00-0a23-11eb-8630-d9024faf60c8.png)

**Comment by YWD** [comment]
It seems fastlane is already installed correctly on my mac, but why there is an error print?

**Comment by Rosemary8330** [comment]
Thanks for the info <a href="https://www.mygreatlakes.me/">MyGreatLakes</a>

**Comment by Clark-861** [comment]
Thanks for the solution [targetehr](https://www.targetehr.us/)
