### ISSUE TITLE
Two-factor authentication

### ISSUE THREAD

**Issue by YWD** [fastlane/fastlane#17415]
It seems that I can't use fastlane with my apple id to connect to appstoreconnect, since I've use apple's Two-factor authentication, which can not turn off.

**Comment by victormihaita** [comment]
Same issue here. The CI for deploying doesn't work anymore. I use Bitrise, I've tried the Fastlane step, I've tried to use script to trigger my fastlane step and the Bitrise 'Deploy to iTunes Connect step'. None of them work because it requires to confirm the 2FA

**Comment by rogerluan** [comment]
Hey @YWD & @victormihaita 👋 

Please see https://github.com/fastlane/fastlane/discussions/17059
The comment marked as the answer of that discussion is the state of the art regarding Apple Authentication. I advise you to update your workflow to use JWT. 

If that doesn't suffice your needs, please let me know. 🤗

**Comment by victormihaita** [comment]
@rogerluan thanks for replying.
I have the same issue with the Bitrise step: ‘Deploy to iTunes’. They are also using Fastlane for this, and is failing for that step because is asking for 2FA auth..
if that doesn’t work it means that is an issue on their side or Fastlane?

**Comment by rogerluan** [comment]
@victormihaita there are a few ways to still keep using 2FA with _fastlane_, as you can see in the Discussion I linked above ☝️ e.g. application-specific password, creating a session and passing it as an env var, or if user interaction is enabled (non-CI envs), you can enter the 2FA code manually upon request.

From _fastlane_ point of view, these tools seem to be working correctly as long as you're using them according to your needs. From your description, sounds like Bitrise is using _fastlane_ internally, and that part is not working, so I advise you contact Bitrise to see if they're aware of that issue or have a workaround. 
On the long run, JWT is the way to go, so if you _can_ upgrade to JWT, I'd recommend doing so 😊 

Let me know if this helps! 🙏

**Comment by YWD** [comment]
Hi @rogerluan I can't get xcode-select installed, do you have any ideas about this? or you can close this issue since later I can use 'App Store Connect API' to communicate with applestoreconnect.
![1](https://user-images.githubusercontent.com/8605395/95822962-6acff580-0d5f-11eb-9a5a-7adf507b6d45.png)

**Comment by victormihaita** [comment]
Thanks @rogerluan. I reported the issue on Bitrise side and shored with them the docs that you linked and your answer. Looking forward to see what they can do about it 👍

**Comment by rogerluan** [comment]
@YWD sorry, what do you need xcode-select for? 🤔 Is that still related to this issue?

**Comment by YWD** [comment]
@rogerluan fastlane use xcode command line command to communicate with appstoreconnect. I can't install xcode command line tool, so I can't use fastlane to test the auth way.
