### ISSUE TITLE
[Fastlane.Swift] SnapshotHelper.swift has Swift Compiler Error

### ISSUE THREAD

**Issue by xta** [fastlane/fastlane#17423]
### New Regression Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information
I'm using fastlane (2.162.0) & Xcode Version 12.0.1 (12A7300).

### Regression Description
I'm unable to run `fastlane snapshot` after following the docs.

With the [current helper file](https://github.com/fastlane/fastlane/blob/master/snapshot/lib/assets/SnapshotHelper.swift#L179), it contains `try image.pngData()?.write(to: path, options: .atomic)`. Xcode cannot run since this throws the compiler error, `'pngData()' has been renamed to 'UIImagePNGRepresentation(_:)'`.

I was able to get fastlane snapshot working with this replacement line, `try UIImagePNGRepresentation(image)?.write(to: path, options: .atomic)`. Obviously your team can figure out what replacement line is preferred.

Thanks

**Comment by minuscorp** [comment]
Thank you for reporting this, I'll work on this ASAP.

**Comment by JimHowell20** [comment]
I'm getting the same error as well.

**Comment by JimHowell20** [comment]
Updating the swift version from Swift 4.1 to Swift 5 in the xCode build settings for the build target fixed this error for me:  <img width="635" alt="Screen Shot 2020-10-13 at 2 48 27 PM" src="https://user-images.githubusercontent.com/7559768/95902886-6c9bb800-0d63-11eb-983b-acbfb24bcb43.png">

**Comment by minuscorp** [comment]
Do you have an older code version (I.e. 11.X) where you can select version 4 and check if it fails? Thank you!

**Comment by rogerluan** [comment]
I don't understand, `image.pngData()` should be the Swift version of `UIImagePNGRepresentation(image)`, which is in Objective-C. If you see [pngData docs](https://developer.apple.com/documentation/uikit/uiimage/1624096-pngdata) you will see it's not deprecated. @minuscorp does this still make sense to you? I initially thought it'd just be a matter of replacing one with the other, but `pngData` looks right too AFAICT 🤷‍♂️ 

@xta , your report lacks your env info - just out of curiosity, what Xcode version are you using? 🤔

**Comment by minuscorp** [comment]
This is domain of Swift 4, but the SPM package starts from Swift 4.2 so I'm afraid that a `#if Swift(<5.0)` is needed here. Anyway, this is something that it is going to be deprecated sooner than later.

**Comment by Landgraf-342** [comment]
Thanks for the information [ePayitonline Login](https://www.epayitonline.us/)

**Comment by NicholasIoanJones** [comment]
Any progress with this? I'm still seeing this problem with Fastlane 2.168.0 and Xcode 12.2

**Comment by minuscorp** [comment]
For some reason Apple doesn't want to solve the bug, I'm busy until weekend, but I think I can push a patch this weekend.

**Comment by minuscorp** [comment]
It would be great if someone can try the draft pr and tell me if it works fine 🤗

**Comment by minuscorp** [comment]
Ping @xta

**Comment by xta** [comment]
does it need a `try` in front? The [PR](https://github.com/fastlane/fastlane/pull/17687/files) contains the code that worked for me (`try UIImagePNGRepresentation(image)?.write(to: path, options: .atomic)`) without `try`.

I see the else block also has a `try image.pngData()?.write(to: path, options: .atomic)` method.

**Comment by rogerluan** [comment]
> does it need a `try` in front? The [PR](https://github.com/fastlane/fastlane/pull/17687/files) contains the code that worked for me (`try UIImagePNGRepresentation(image)?.write(to: path, options: .atomic)`) without `try`.
> 
> I see the else block also has a `try image.pngData()?.write(to: path, options: .atomic)` method.

@xta , it shouldn't need `try` AFAICT, as `UIImagePNGRepresentation` doesn't throw: https://developer.apple.com/documentation/uikit/1624096-uiimagepngrepresentation

By adding `try`, it also compiles, but it should throw a warning such as:
>No calls to throwing functions occur within 'try' expression

**Comment by minuscorp** [comment]
Closing it as new release was done, don't hesitate to reopen the issue if the problem persists 😊
