### ISSUE TITLE
Deliver fails with no error message if setting metadata 

### ISSUE THREAD

**Issue by kevint727** [fastlane/fastlane#17421]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

If I do not skip the metadata update with deliver, it fails and does not send up update. If I do skip metadata, works correctly. 

Here is what happens when I DON'T skip metadata:

INFO [2020-10-09 11:49:25.67]: --- Step: deliver ---
INFO [2020-10-09 11:49:25.67]: ---------------------
INFO [2020-10-09 11:49:25.67]: Successfully loaded '/Users/ktodd/BaZingiOS/fastlane/Deliverfile' 📄

+------------------------+------------------------------------------------------------------+
|                       Detected Values from './fastlane/Deliverfile'                       |
+------------------------+------------------------------------------------------------------+
| price_tier             | 0                                                                |
| submission_information | {:export_compliance_encryption_updated=>false,                   |
|                        | :export_compliance_uses_encryption=>false,                       |
|                        | :content_rights_contains_third_party_content=>true,              |
|                        | :content_rights_has_rights=>true, :add_id_info_uses_idfa=>true,  |
|                        | :add_id_info_serves_ads=>false,                                  |
|                        | :add_id_info_tracks_install=>true,                               |
|                        | :add_id_info_tracks_action=>true}                                |
| metadata_path          | ./fastlane/metadata/SCPartnerPerks                               |
| app_rating_config_path | ./fastlane/metadata/SCPartnerPerks/app_store_rating_config.json  |
| ipa                    | ./fastlane/builds/SCPartnerPerks.ipa                             |
| submit_for_review      | true                                                             |
| force                  | true                                                             |
| automatic_release      | false                                                            |
| phased_release         | false                                                            |
| reset_ratings          | false                                                            |
| skip_metadata          | false                                                            |
| skip_screenshots       | true                                                             |
| skip_binary_upload     | false                                                            |
+------------------------+------------------------------------------------------------------+

INFO [2020-10-09 11:49:25.68]: Login to App Store Connect *******)
Reading keychain entry, because either user or password were empty
Loading session from '/Users/ktodd/.fastlane/spaceship/********/cookie'
Looking for App Store Connect Team with name ******
Looking for App Store Connect Team with ID *****
INFO [2020-10-09 11:49:28.41]: Login successful

+-------------------------------------------------------------------+-----------------------------------------------------------------+
|                                                       deliver 2.162.0 Summary                                                       |
+-------------------------------------------------------------------+-----------------------------------------------------------------+
| app_identifier                                                    | *******                                     |
| screenshots_path                                                  | ./fastlane/screenshots                                          |
| app_version                                                       | 1.0.3                                                           |
| username                                                          | ******                                    |
| ipa                                                               | ./fastlane/builds/SCPartnerPerks.ipa                            |
| platform                                                          | ios                                                             |
| edit_live                                                         | false                                                           |
| use_live_version                                                  | false                                                           |
| metadata_path                                                     | ./fastlane/metadata/SCPartnerPerks                              |
| skip_binary_upload                                                | false                                                           |
| skip_screenshots                                                  | true                                                            |
| skip_metadata                                                     | false                                                           |
| skip_app_version_update                                           | false                                                           |
| force                                                             | true                                                            |
| overwrite_screenshots                                             | false                                                           |
| submit_for_review                                                 | true                                                            |
| reject_if_possible                                                | false                                                           |
| automatic_release                                                 | false                                                           |
| phased_release                                                    | false                                                           |
| reset_ratings                                                     | false                                                           |
| price_tier                                                        | 0                                                               |
| app_rating_config_path                                            | ./fastlane/metadata/SCPartnerPerks/app_store_rating_config.json |
| submission_information.export_compliance_encryption_updated       | false                                                           |
| submission_information.export_compliance_uses_encryption          | false                                                           |
| submission_information.content_rights_contains_third_party_conte  | true                                                            |
| nt                                                                |                                                                 |
| submission_information.content_rights_has_rights                  | true                                                            |
| submission_information.add_id_info_uses_idfa                      | true                                                            |
| submission_information.add_id_info_serves_ads                     | false                                                           |
| submission_information.add_id_info_tracks_install                 | true                                                            |
| submission_information.add_id_info_tracks_action                  | true                                                            |
| run_precheck_before_submit                                        | true                                                            |
| precheck_default_rule_level                                       | warn                                                            |
| ignore_language_directory_validation                              | false                                                           |
| precheck_include_in_app_purchases                                 | true                                                            |
+-------------------------------------------------------------------+-----------------------------------------------------------------+

INFO [2020-10-09 11:49:32.08]: Making sure the latest version on App Store Connect matches '1.0.3'...
INFO [2020-10-09 11:49:33.05]: '1.0.3' is the latest version on App Store Connect
INFO [2020-10-09 11:49:33.05]: Loading './fastlane/metadata/SCPartnerPerks/en-US/description.txt'...
INFO [2020-10-09 11:49:33.05]: Loading './fastlane/metadata/SCPartnerPerks/en-US/keywords.txt'...
INFO [2020-10-09 11:49:33.05]: Loading './fastlane/metadata/SCPartnerPerks/en-US/release_notes.txt'...
INFO [2020-10-09 11:49:33.05]: Loading './fastlane/metadata/SCPartnerPerks/en-US/support_url.txt'...
INFO [2020-10-09 11:49:33.05]: Loading './fastlane/metadata/SCPartnerPerks/en-US/marketing_url.txt'...
INFO [2020-10-09 11:49:33.05]: Loading './fastlane/metadata/SCPartnerPerks/en-US/promotional_text.txt'...
INFO [2020-10-09 11:49:33.05]: Loading './fastlane/metadata/SCPartnerPerks/en-US/name.txt'...
INFO [2020-10-09 11:49:33.05]: Loading './fastlane/metadata/SCPartnerPerks/en-US/subtitle.txt'...
INFO [2020-10-09 11:49:33.05]: Loading './fastlane/metadata/SCPartnerPerks/en-US/privacy_url.txt'...
INFO [2020-10-09 11:49:33.05]: Loading './fastlane/metadata/SCPartnerPerks/en-US/apple_tv_privacy_policy.txt'...
INFO [2020-10-09 11:49:33.05]: Loading './fastlane/metadata/SCPartnerPerks/copyright.txt'...
INFO [2020-10-09 11:49:33.06]: Loading './fastlane/metadata/SCPartnerPerks/primary_category.txt'...
INFO [2020-10-09 11:49:33.06]: Loading './fastlane/metadata/SCPartnerPerks/secondary_category.txt'...
INFO [2020-10-09 11:49:33.06]: Loading './fastlane/metadata/SCPartnerPerks/primary_first_sub_category.txt'...
INFO [2020-10-09 11:49:33.06]: Loading './fastlane/metadata/SCPartnerPerks/primary_second_sub_category.txt'...
INFO [2020-10-09 11:49:33.06]: Loading './fastlane/metadata/SCPartnerPerks/secondary_first_sub_category.txt'...
INFO [2020-10-09 11:49:33.06]: Loading './fastlane/metadata/SCPartnerPerks/secondary_second_sub_category.txt'...
INFO [2020-10-09 11:49:33.06]: Loading './fastlane/metadata/SCPartnerPerks/review_information/first_name.txt'...
INFO [2020-10-09 11:49:33.06]: Loading './fastlane/metadata/SCPartnerPerks/review_information/last_name.txt'...
INFO [2020-10-09 11:49:33.06]: Loading './fastlane/metadata/SCPartnerPerks/review_information/phone_number.txt'...
INFO [2020-10-09 11:49:33.06]: Loading './fastlane/metadata/SCPartnerPerks/review_information/email_address.txt'...
INFO [2020-10-09 11:49:33.06]: Loading './fastlane/metadata/SCPartnerPerks/review_information/demo_user.txt'...
INFO [2020-10-09 11:49:33.06]: Loading './fastlane/metadata/SCPartnerPerks/review_information/demo_password.txt'...
INFO [2020-10-09 11:49:33.06]: Loading './fastlane/metadata/SCPartnerPerks/review_information/notes.txt'...
WARN [2020-10-09 11:49:36.91]: Will begin uploading metadata for '1.0.3' on App Store Connect
INFO [2020-10-09 11:49:36.91]: Uploading metadata to App Store Connect for version
INFO [2020-10-09 11:49:37.25]: Uploading metadata to App Store Connect for localized version 'en-US'
INFO [2020-10-09 11:49:37.61]: Uploading metadata to App Store Connect for localized info 'en-US'
INFO [2020-10-09 11:49:39.07]: Successfully generated documentation at path '/Users/ktodd/BaZingiOS/fastlane/README.md'

+------+---------------------------------------+-------------+
|                      fastlane summary                      |
+------+---------------------------------------+-------------+
| Step | Action                                | Time (in s) |
+------+---------------------------------------+-------------+
| 1    | default_platform                      | 0           |
| 2    | get_certificates                      | 12          |
| 3    | increment_version_number_in_xcodeproj | 24          |
| 4    | increment_build_number_in_xcodeproj   | 30          |
| 5    | get_build_number_from_xcodeproj       | 12          |
| 6    | get_version_number_from_xcodeproj     | 8           |
| 💥   | deliver                               | 13          |
+------+---------------------------------------+-------------+

---------------------------------------------------------------------

**Here is the contents of my deliver file:**

price_tier 0
submission_information({
    export_compliance_encryption_updated: false,
    export_compliance_uses_encryption: false,
    content_rights_contains_third_party_content: true,
    content_rights_has_rights:true,
    add_id_info_uses_idfa: true,
  add_id_info_serves_ads: false,
  add_id_info_tracks_install: true,
  add_id_info_tracks_action: true
})
metadata_path("./fastlane/metadata/#{ENV['SCHEME']}")
app_rating_config_path("./fastlane/metadata/#{ENV['SCHEME']}/app_store_rating_config.json")
ipa("./fastlane/builds/#{ENV['SCHEME']}.ipa")
submit_for_review(true)
force(true)
automatic_release(false)
phased_release(false)
reset_ratings(false)
skip_metadata(false)
skip_screenshots(true)
skip_binary_upload(false)

##### Command executed

bundle exec fastlane deliverTest --env SCPartnerPerks --verbose --capture_output
##### Complete output when running fastlane, including the stack trace and command used

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.6                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.6 (19G2021)                                     |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.0.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform(:ios)

platform :ios do

ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "180"
ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "180"
ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "******"

desc "Create new build"
  lane :just_build do |options|
	startEnv = options[:startEnv]
	errorLog = Array.new
	  def execute_for_all_envs(theEnv)
    schemeList = Dir.glob(".env.*")
    schemeList.each do |file|
      Dotenv.overload(file)
      yield
    end
  end
  if ENV['SCHEME'] != nil
    
	begin
		get_certificates(
    			username: "*******",
			keychain_password: "******",
		team_name:ENV["FASTLANE_ITC_TEAM_NAME"]

	)
	rescue => ex
		d = DateTime.now		
		errorLog << (ENV['SCHEME'] + ":")
		errorLog << d.strftime("%m/%d/%Y %H:%M")
		errorLog << ex
		errorLog << "------------------------------------------------------"
		errorLog << "\n"
	end
	begin
    		gym
	rescue => ex
		d = DateTime.now		
		errorLog << (ENV['SCHEME'] + ":")
		errorLog << d.strftime("%m/%d/%Y %H:%M")
		errorLog << ex
		errorLog << "------------------------------------------------------"
		errorLog << "\n"
	end
	

  else 
  	execute_for_all_envs( startEnv ){ just_build }
  end

	d = DateTime.now
	open('ErrorLog.out', 'a') { |f|
		#f.puts (d.strftime("%m/%d/%Y %H:%M"))
  		#f.puts "Error log:"
		f.puts "\n"
		f.puts (errorLog.join("\n"))
	}
  	#puts("Error log:")
	#puts(errorLog.join("\n"))
  
  end



desc "Deliver Test"
  lane :deliverTest do |options|
	startEnv = options[:startEnv]
	errorLog = Array.new
	def execute_for_all_envs(theEnv)
    		schemeList = Dir.glob(".env.*")
		schemeList = schemeList.sort
		if theEnv == nil 
			schemeList.each do |file|
      				Dotenv.overload(file)
      				yield
			end
   		else
			startIndex = schemeList.index(".env." + theEnv)
			schemeList = schemeList.drop(startIndex)
    			schemeList.each do |file|
      				Dotenv.overload(file)
     		 		yield
    			end
  		end
	end
  if ENV['SCHEME'] != nil
	begin
    		get_certificates(
    			username: "*****",
			keychain_password: "****",
			team_name:ENV["FASTLANE_ITC_TEAM_NAME"],
			generate_apple_certs: true

		)
	rescue => ex
		d = DateTime.now		
		errorLog << (ENV['SCHEME'] + ":")
		errorLog << d.strftime("%m/%d/%Y %H:%M")
		errorLog << ex
		errorLog << "------------------------------------------------------"
		errorLog << "\n"
		
	end
  	increment_version_number_in_xcodeproj(
		bump_type: "patch", target: ENV['SCHEME']
	)
	increment_build_number_in_xcodeproj(
  		target: ENV['SCHEME']
	)
	build_number = get_build_number_from_xcodeproj(
		target: ENV["SCHEME"]
    	)
	version_number = get_version_number_from_xcodeproj(
  		target: ENV["SCHEME"]
    	)
	
	begin
    		deliver
	rescue => ex
		d = DateTime.now		
		errorLog << (ENV['SCHEME'] + ":")
		errorLog << d.strftime("%m/%d/%Y %H:%M")
		errorLog << ex
		errorLog << "------------------------------------------------------"
		errorLog << "\n"

	end
    
  else 
  	execute_for_all_envs( startEnv ){deliverTest}
  end
	d = DateTime.now
	open('ErrorLog.out', 'a') { |f|
		#f.puts (d.strftime("%m/%d/%Y %H:%M"))
  		#f.puts "Error log:"
		f.puts "\n"
		f.puts (errorLog.join("\n"))
	}
  	#puts("Error log:")
	#puts(errorLog.join("\n"))
  end  

  
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
#app_identifier(ENV['BUNDLE_IDENTIFIER']) # The bundle identifier of your app

#apple_id(ENV['FASTLANE_USER'])
#team_name(ENV['FASTLANE_ITC_TEAM_NAME'])



#apple_id("****") # Your Apple email address
#team_name ("****")
#user_name ("*****")

#team_name(ENV['FASTLANE_ITC_TEAM_NAME'])
#username(ENV['FASTLANE_USER'])
#apple_id(ENV['FASTLANE_USER'])

#apple_id "****"
#apple_id(ENV['FASTLANE_USER'])
#team_name(ENV['FASTLANE_ITC_TEAM_NAME'])
#team_name "****"

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile


```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.162.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-versioning | 0.4.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version      |
| -------------------------- | ------------ |
| did_you_mean               | 1.3.0        |
| bundler                    | 2.1.4        |
| rake                       | 13.0.1       |
| CFPropertyList             | 3.0.2        |
| public_suffix              | 4.0.6        |
| addressable                | 2.7.0        |
| atomos                     | 0.1.3        |
| aws-eventstream            | 1.1.0        |
| aws-partitions             | 1.380.0      |
| aws-sigv4                  | 1.2.2        |
| jmespath                   | 1.4.0        |
| aws-sdk-core               | 3.109.1      |
| aws-sdk-kms                | 1.39.0       |
| aws-sdk-s3                 | 1.83.0       |
| babosa                     | 1.0.4        |
| claide                     | 1.0.3        |
| colored                    | 1.2          |
| colored2                   | 3.1.2        |
| highline                   | 1.7.10       |
| commander-fastlane         | 4.4.6        |
| declarative                | 0.0.20       |
| declarative-option         | 0.1.0        |
| digest-crc                 | 0.6.1        |
| unf_ext                    | 0.0.7.7      |
| unf                        | 0.1.4        |
| domain_name                | 0.5.20190701 |
| dotenv                     | 2.7.6        |
| emoji_regex                | 3.0.0        |
| excon                      | 0.76.0       |
| multipart-post             | 2.0.0        |
| faraday                    | 1.0.1        |
| http-cookie                | 1.0.3        |
| faraday-cookie_jar         | 0.0.7        |
| faraday_middleware         | 1.0.0        |
| fastimage                  | 2.2.0        |
| gh_inspector               | 1.1.3        |
| jwt                        | 2.2.2        |
| memoist                    | 0.16.2       |
| multi_json                 | 1.15.0       |
| os                         | 1.1.1        |
| signet                     | 0.14.0       |
| googleauth                 | 0.13.1       |
| httpclient                 | 2.8.3        |
| mini_mime                  | 1.0.2        |
| uber                       | 0.1.0        |
| representable              | 3.0.4        |
| retriable                  | 3.1.2        |
| google-api-client          | 0.38.0       |
| google-cloud-env           | 1.3.3        |
| google-cloud-errors        | 1.0.1        |
| google-cloud-core          | 1.5.0        |
| google-cloud-storage       | 1.29.1       |
| json                       | 2.3.1        |
| mini_magick                | 4.10.1       |
| plist                      | 3.5.0        |
| rubyzip                    | 2.3.0        |
| security                   | 0.1.3        |
| naturally                  | 2.2.0        |
| simctl                     | 1.6.8        |
| slack-notifier             | 2.3.2        |
| terminal-notifier          | 2.0.0        |
| unicode-display_width      | 1.7.0        |
| terminal-table             | 1.8.0        |
| tty-screen                 | 0.8.1        |
| tty-cursor                 | 0.7.1        |
| tty-spinner                | 0.9.3        |
| word_wrap                  | 1.0.0        |
| nanaimo                    | 0.3.0        |
| xcodeproj                  | 1.18.0       |
| rouge                      | 2.0.7        |
| xcpretty                   | 0.3.0        |
| xcpretty-travis-formatter  | 1.0.0        |
| fastlane-plugin-versioning | 0.4.4        |
</details>

*generated on:* **2020-10-09**
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by ainame** [comment]
@kevint727 

Hi, I checked your `Fastfile` you shared but it looks like yours wrapped `deliver` with `begin` and `rescue`,  which prevents you from getting backtrace logs when fastlane crashes. Backtrace logs will definitely help to address your issue but without that I think we don't have enough information to get any clue of the cause from this description.

So please try removing `begin` and `rescue` and then share actual backtrace logs with here if you get, or share `ErrorLog.out`  file you seem to save at the end of `Fastfile`...?

```ruby
	begin
    		deliver
	rescue => ex
		d = DateTime.now		
		errorLog << (ENV['SCHEME'] + ":")
		errorLog << d.strftime("%m/%d/%Y %H:%M")
		errorLog << ex
		errorLog << "------------------------------------------------------"
		errorLog << "\n"

	end
```

**Comment by kevint727** [comment]
Thanks ainame and sorry for the delay on the response but I was unavailable for a couple of days. I have removed the begin and rescue and am running again. I will post my results shortly.

**Comment by kevint727** [comment]
@ainame  I am now seeing the following, which is much more helpful I would imagine: 

bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
Spaceship::UnexpectedResponse: [!] The provided entity includes a relationship with an invalid value
The provided entity includes a relationship with an invalid value
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/spaceship/lib/spaceship/connect_api/api_client.rb:188:in `handle_response'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/spaceship/lib/spaceship/connect_api/api_client.rb:135:in `patch'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:560:in `patch_app_info_categories'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `patch_app_info_categories'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/spaceship/lib/spaceship/connect_api/models/app_info.rb:73:in `update_categories'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/deliver/lib/deliver/upload_metadata.rb:286:in `upload'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/deliver/lib/deliver/runner.rb:145:in `upload_metadata'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/deliver/lib/deliver/runner.rb:54:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:17:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:120:in `block (2 levels) in parsing_binding'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/bin/fastlane:23:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>'

**Comment by kevint727** [comment]
I figured out it was a problem with some filler text in the secondary cat metadata files. Left over from previous fastlane version. I removed that and then fixed an additional problem. Will report result shortly.

**Comment by kevint727** [comment]
I was able to successfully run through my lane and submit an app update for review. Thanks so much again to @ainame for suggesting removing the error handling I had in the lane. Was the game-changer. Closing this now.

**Comment by ainame** [comment]
@kevint727 It doesn't matter if you use `rescue` to catch errors and collect error logs in your Fastfile as long as the errors caught are re-raised as the same error again. 

```ruby
begin
  deliver
rescue => error
  # do something with error
  raise error
end
```

In fastlane, there are lots of places using  `UI.user_error!` internally to log error messages and stop the flow to handle exceptions. It is supposed to stop the whole flow in Fastfile as it's not recoverable in most of the cases. So use it with cautions.
