### ISSUE TITLE
[Apple 2FA] Session loaded from environment variable is not valid

### ISSUE THREAD

**Issue by BenjaminSAILcloud** [fastlane/fastlane#17430]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

The 2FA app-specific password does not work. I got `Session loaded from environment variable is not valid. Continuing with normal login.
    Two-factor Authentication (6 digits code) is enabled for account 'email@gmail.com'`
It worked once on oct. 6th with fastlane in version `2.162.0`. I tried creating another app-specific password from my apple account and set the task accordingly but I didn't work either.

I am using fastlane in an Azure DevOps pipeline with the task [Apple App Store Release](url) from Microsoft.

Related issues :
https://github.com/microsoft/app-store-vsts-extension/issues/180
https://github.com/fastlane/fastlane/issues/17425

##### Command executed

```
/usr/local/lib/ruby/gems/2.6.0/bin/fastlane pilot upload -u email@gmail.com -i /Users/runner/work/1/s/output/iphoneos/Release/SAILcloudBox.ipa --changelog # 2.0.0.61 update/npm packages -q 123456789 -r xxxxxxxxxxxx -a xxx.xxxxxxxx.xxx --skip_submission true
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
    ==============================================================================
    Task         : Apple App Store Release
    Description  : Release an app to TestFlight or the Apple App Store
    Version      : 1.176.0
    Author       : Microsoft Corporation
    Help         : [More Information](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.app-store)
    ==============================================================================
    /usr/local/opt/ruby/bin/gem install fastlane
    Successfully installed fastlane-2.162.0
    Parsing documentation for fastlane-2.162.0
    Installing ri documentation for fastlane-2.162.0
    Done installing documentation for fastlane after 22 seconds
    1 gem installed

    /usr/local/opt/ruby/bin/gem update fastlane -i /Users/runner/.gem-cache
    Updating installed gems
    Nothing to update

    /usr/local/lib/ruby/gems/2.6.0/bin/fastlane pilot upload -u email@gmail.com -i /Users/runner/work/1/s/output/iphoneos/Release/SAILcloudBox.ipa --changelog # 2.0.0.61

    update/npm packages
     -q 123456789 -r xxxxxxxxxxxx -a xxx.xxxxxxxx.xxx --skip_submission true
    [09:54:08]: Seems like launching fastlane takes a while - please run
    [09:54:08]: 
    [09:54:08]: $ [sudo] gem cleanup
    [09:54:08]: 
    [09:54:08]: to uninstall outdated gems and make fastlane launch faster
    [09:54:08]: Alternatively it's recommended to start using a Gemfile to lock your dependencies
    [09:54:08]: To get started with a Gemfile, run
    [09:54:08]: 
    [09:54:08]: $ bundle init
    [09:54:08]: $ echo 'gem "fastlane"' >> Gemfile
    [09:54:08]: $ bundle install
    [09:54:08]: 
    [09:54:08]: After creating the Gemfile and Gemfile.lock, commit those files into version control
    [09:54:08]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
    [09:54:16]: Sending anonymous analytics information
    [09:54:16]: Learn more at https://docs.fastlane.tools/#metrics
    [09:54:16]: No personal or sensitive data is sent.
    [09:54:16]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
    [09:54:16]: Login to App Store Connect (email@gmail.com)
    Session loaded from environment variable is not valid. Continuing with normal login.
    Two-factor Authentication (6 digits code) is enabled for account 'email@gmail.com'
    More information about Two-factor Authentication: https://support.apple.com/en-us/HT204915

    If you're running this in a non-interactive session (e.g. server or CI)
    check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification

    Please select a trusted phone number to send code to:
    1. +33 •• •• •• •• 93
    2. +33 •• •• •• •• 95
    ?  
    ##[error]The operation was canceled.
    Finishing: Publish to the App Store TestFlight track
 </pre>
</details>

### Environment

<details><summary>Details</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.15.7                                          |
| Ruby                        | 2.6.6                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.28.0                               |
| Installation Source         | /usr/local/lib/ruby/gems/2.6.0/bin/fastlane      |
| Host                        | Mac OS X 10.15.7 (19H2)                          |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.6/2.6.6_1/lib           |
| OpenSSL Version             | OpenSSL 1.1.1f  31 Mar 2020                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode_11.7.app/Contents/Developer/ |
| Xcode Version               | 11.7                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.162.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.18.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.76.0       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday                   | 1.0.1        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-storage      | 1.29.0       |
| emoji_regex               | 3.0.0        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.380.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.109.0      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.83.0       |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| json                      | 2.3.1        |
| mini_portile2             | 2.1.0        |
| nokogiri                  | 1.6.8.1      |
</details>

*generated on:* **2020-10-13**
</details>

**Comment by rogerluan** [comment]
Hi @BenjaminSAILcloud 👋 

I strongly recommend upgrading to JWT if your account already has 2FA enabled. This will solve all your authentication issues by avoiding auth/pass/session/2fa workarounds 🎉 
You can find more information here: https://github.com/fastlane/fastlane/discussions/17059#discussioncomment-88437

Please let me know if that works out for you! 🙏

**Comment by BenjaminSAILcloud** [comment]
Ok, I am unfortunately dependant of the task that I am using but the authors helped me out. I added, on their suggestion, the `-p` param with the value of the apple id from _Apple ID_ property in the **App Information** section in **App Store Connect**, and it works just fine.

The correct command looks like this : 
```
/usr/local/lib/ruby/gems/2.6.0/bin/fastlane pilot upload -u *** -i /Users/runner/work/1/s/output/iphoneos/Release/app.ipa -q 123456789 -r xxxxxxxxxxx -a xxx.xxxxxxxxx.xxx --skip_submission true --skip_waiting_for_build_processing true -p 1234567890
```

How to find the Apple ID :
![Screenshot 2020-10-22 at 16 42 21](https://user-images.githubusercontent.com/33052668/96888612-1b3ba900-1486-11eb-963c-a289743bdffe.png)
