### ISSUE TITLE
Your shell environment is not correctly configured

### ISSUE THREAD

**Issue by yakimant** [fastlane/fastlane#17431]
I have an issue with locale, which is correctly set on the build agents:
```
LANG=en_US.UTF-8"
LANGUAGE=en_US.UTF-8"
LC_ALL=en_US.UTF-8"
```

Scan is failed with exception
`Error building/testing the application. See the log here: 'path_to_log_file.log'.`

After running again in the same Fastfile, there is no locale issue.

After reading the file
`https://github.com/fastlane/fastlane/blob/master/scan/lib/scan/error_handler.rb`
it's possible, that it's not a locale issue. I don't have it in other jobs using the same Fastfile and environment.

Is it possible to have an output printed for debug?
I only found `export LANG=en_US.US-ASCII` for a CompileC in xcodebuild log. Is it the case?

Related:
https://github.com/fastlane/fastlane/issues/13426
https://github.com/fastlane/fastlane/issues/7440
https://github.com/fastlane/fastlane/issues/7486

**Comment by yakimant** [comment]
This issue is only reproduced with xcpretty disabled (by `disable_xcpretty` or `output_style='raw'`).

**Comment by rogerluan** [comment]
@yakimant is this actually your code?

```
LANG=en_US.UTF-8"
LANGUAGE=en_US.UTF-8"
LC_ALL=en_US.UTF-8"
```

If so, it's missing the opening quotes 🤔

**Comment by yakimant** [comment]
@rogerluan, can't check anymore, as we switched xcpretty back as a temporary workaround.

2 things for sure:
1. Only reproduced with xcpretty off
2. Not reprodices with scan rerun

Next time I will switch the xcpretty off - will debug more.

**Comment by gobetti** [comment]
https://github.com/fastlane/fastlane/issues/16480 has also reported an issue specifically when using `disable_xcpretty`. I'm the author of that flag and I hadn't have issues with it, until today when I had to remove `fail_build: false`. Either omitting or specifying `true` will error with `undefined method `scan' for nil:NilClass`. I'd like to help on this, for now just adding this report in case someone more familiar with the codebase has an idea from this while I look more deeply
