### ISSUE TITLE
Fastlane 2.150.0 breaks enterprise use of iTMSTransport (fastlane-plugin-transporter)

### ISSUE THREAD

**Issue by scibidoo** [fastlane/fastlane#17448]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information
- Breaking version: 2.150.0
- Last working version: 2.149.1

### Regression Description
We require a patched version of iTMSTransporter and use the plugin - https://github.com/mgrebenets/fastlane-plugin-transporter - to ensure CI can deliver via our secure network

This change changes the behaviour:
https://github.com/fastlane/fastlane/pull/16640/files#diff-e4392686971e0801abe75321cc8a4c90eb2f2c971734d8cc88b0ac5fef5ee12d

The use of xcrun in the builder causes the Xcode bundled version of Transporter to be used ignoring FASTLANE_ITUNES_TRANSPORTER_PATH
`ITMS_TRANSPORTER_PASSWORD=YourPassword xcrun iTMSTransporter -m upload`... etc

previously the plugin would utilise the custom installed version
`/Users/homedir/itms/java/bin/java -Djava.ext.dirs=/Users/homedir/itms/java/lib/ext -XX:NewSize=2m -Xms32m -Xmx1024m -Xms1024m -Djava.awt.headless=true -Dsun.net.http.retryPost=false -jar /Users/scibanja/itms/lib/itmstransporter-launcher.jar -m upload`... etc

`The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.`

**Comment by Natalie298** [comment]
Thank you so much for the information keep suggesting us such informative post i will recommend this post to others [mygiftcardsite](https://www.mygiftcardsite.pro)

**Comment by joshdholtz** [comment]
@scibidoo I think this should do it! Do you mind testing this out? https://github.com/fastlane/fastlane/pull/17502 😊

**Comment by scibidoo** [comment]
Tested this and it works 👍🏽 thanks @joshdholtz
