### ISSUE TITLE
Could not resolve package dependencies

### ISSUE THREAD

**Issue by detectedstealth** [fastlane/fastlane#17454]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Building project that uses swift packages fails to resolve dependencies.

##### Command executed

```
gym(
      output_directory: "build_Appstore",
      clean: true,
      export_options: {
        method: "app-store",
        provisioningProfiles: {
          "#{ENV['APP_IDENTIFIER']}" => ENV['sigh_co.App_appstore_profile-path']
        }
      }
)
```
The following is failing to resolve dependencies **when running this command manually it resolves the dependencies**.
```/Applications/Xcode-beta.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -scheme SCHEME_NAME -project ./PROJECT_NAME.xcodeproj```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
   [08:23:14]: Resolving Swift Package Manager dependencies...
[08:23:14]: $ xcodebuild -resolvePackageDependencies -scheme SCHEME_NAME -project ./PROJECT_NAME.xcodeproj
[08:23:15]: ▸ 2020-10-16 08:23:15.233 xcodebuild[24465:768781] [MT] DVTPlugInManager: Required plug-in compatibility UUID 12121 for GraphQL.ideplugin (com.apollographql.xcode.graphql) not present
[08:23:15]: ▸ Command line invocation:
[08:23:15]: ▸     /Applications/Xcode-beta.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -scheme SCHEME_NAME -project ./PROJECT_NAME.xcodeproj
[08:23:16]: ▸ 2020-10-16 08:23:16.881 xcodebuild[24465:768843]  DTDeviceKit: deviceType from ad7f610f316339f2521fe10071c7db43f33e7a95 was NULL
[08:23:19]: ▸ Resolve Package Graph
[08:23:34]: ▸ Resolved source packages:
[08:23:34]: ▸   Firebase: https://github.com/firebase/firebase-ios-sdk @ 6.34-spm-beta
[08:23:34]: ▸   Resolver: git@github.com:hmlongco/Resolver.git @ 1.1.4
[08:23:34]: ▸   PubNub: https://github.com/pubnub/swift.git @ 2.5.4
[08:23:34]: ▸   leveldb: https://github.com/firebase/leveldb.git @ fa1f25f
[08:23:34]: ▸   SQLite.swift: https://github.com/stephencelis/SQLite.swift.git @ 0.12.2
[08:23:34]: ▸   Apollo: https://github.com/apollographql/apollo-ios.git @ 0.34.1
[08:23:34]: ▸   Promises: https://github.com/google/promises.git @ 1.2.10
[08:23:34]: ▸   ReadyDomain: /Users/USER/Development/AppName/Packages/AppDomain
[08:23:34]: ▸   nanopb: https://github.com/nanopb/nanopb.git @ 8119dfe
[08:23:34]: ▸   abseil: https://github.com/firebase/abseil-cpp-SwiftPM.git @ 05d8107
[08:23:34]: ▸   ReadyData: /Users/USER/Development/AppName/Packages/AppData
[08:23:34]: ▸   Starscream: https://github.com/daltoniam/Starscream @ 3.1.1
[08:23:34]: ▸   gRPC: https://github.com/firebase/grpc-SwiftPM.git @ 5bb2669
[08:23:34]: ▸   BoringSSL-GRPC: https://github.com/firebase/boringssl-SwiftPM.git @ 7bcafa2
[08:23:34]: ▸   Codegen: /Users/USER/Development/AppName/Packages/AppCodegen
[08:23:34]: ▸   GTMSessionFetcher: https://github.com/google/gtm-session-fetcher.git @ 1.4.0
[08:23:34]: ▸   PathKit: https://github.com/kylef/PathKit.git @ 1.0.0
[08:23:34]: ▸   Spectre: https://github.com/kylef/Spectre.git @ 0.9.1
[08:23:34]: ▸   swift-nio-zlib-support: https://github.com/apple/swift-nio-zlib-support.git @ 1.0.0
[08:23:34]: ▸   Stencil: https://github.com/stencilproject/Stencil.git @ 0.14.0
[08:23:34]: ▸   Alamofire: https://github.com/Alamofire/Alamofire.git @ 5.2.2
[08:23:34]: ▸ xcodebuild: error: Could not resolve package dependencies:
[08:23:34]: ▸   artifact of binary target 'FIRAnalyticsConnector' failed extraction: The operation couldn’t be completed. (TSCBasic.StringError error 1.)
[08:23:34]: ▸   artifact of binary target 'FirebaseAnalytics' failed extraction: The operation couldn’t be completed. (TSCBasic.StringError error 1.)
[08:23:34]: ▸   artifact of binary target 'GoogleAppMeasurement' failed extraction: The operation couldn’t be completed. (TSCBasic.StringError error 1.)
2020-10-16 08:23:15.233 xcodebuild[24465:768781] [MT] DVTPlugInManager: Required plug-in compatibility UUID 12121 for GraphQL.ideplugin (com.apollographql.xcode.graphql) not present
Command line invocation:
    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -scheme SCHEME_NAME -project ./AppName.xcodeproj

2020-10-16 08:23:16.881 xcodebuild[24465:768843]  DTDeviceKit: deviceType from ad7f610f316339f2521fe10071c7db43f33e7a95 was NULL
Resolve Package Graph

Resolved source packages:
  Firebase: https://github.com/firebase/firebase-ios-sdk @ 6.34-spm-beta
  Resolver: git@github.com:hmlongco/Resolver.git @ 1.1.4
  PubNub: https://github.com/pubnub/swift.git @ 2.5.4
  leveldb: https://github.com/firebase/leveldb.git @ fa1f25f
  SQLite.swift: https://github.com/stephencelis/SQLite.swift.git @ 0.12.2
  Apollo: https://github.com/apollographql/apollo-ios.git @ 0.34.1
  Promises: https://github.com/google/promises.git @ 1.2.10
  ReadyDomain: /Users/USER/Development/AppName/Packages/AppDomain
  nanopb: https://github.com/nanopb/nanopb.git @ 8119dfe
  abseil: https://github.com/firebase/abseil-cpp-SwiftPM.git @ 05d8107
  ReadyData: /Users/USER/Development/AppName/Packages/AppData
  Starscream: https://github.com/daltoniam/Starscream @ 3.1.1
  gRPC: https://github.com/firebase/grpc-SwiftPM.git @ 5bb2669
  BoringSSL-GRPC: https://github.com/firebase/boringssl-SwiftPM.git @ 7bcafa2
  Codegen: /Users/USER/Development/AppName/Packages/AppCodegen
  GTMSessionFetcher: https://github.com/google/gtm-session-fetcher.git @ 1.4.0
  PathKit: https://github.com/kylef/PathKit.git @ 1.0.0
  Spectre: https://github.com/kylef/Spectre.git @ 0.9.1
  swift-nio-zlib-support: https://github.com/apple/swift-nio-zlib-support.git @ 1.0.0
  Stencil: https://github.com/stencilproject/Stencil.git @ 0.14.0
  Alamofire: https://github.com/Alamofire/Alamofire.git @ 5.2.2

xcodebuild: error: Could not resolve package dependencies:
  artifact of binary target 'FIRAnalyticsConnector' failed extraction: The operation couldn’t be completed. (TSCBasic.StringError error 1.)
  artifact of binary target 'FirebaseAnalytics' failed extraction: The operation couldn’t be completed. (TSCBasic.StringError error 1.)
  artifact of binary target 'GoogleAppMeasurement' failed extraction: The operation couldn’t be completed. (TSCBasic.StringError error 1.)
[08:23:34]: Exit status: 74
 </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.7                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.7 (19H2)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode-beta.app/Contents/Developer/               |
| Xcode Version               | 12.2                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  
  desc "Creates the app identifier and registers it with app store connect"
  lane :register_app do
    create_app_online(
      app_name: ENV['APP_NAME'],
      language: "English",
      app_version: "1.0",
      sku: ENV['APP_IDENTIFIER'],
    )
  end

  desc "Setup provisioning profiles, and certificates"
  lane :sync_all_development do
    match(
      type: "development",
      force_for_new_devices: true
    )
  end

  desc "Updates devices used in the development profile"
  lane :sync_device_info do
    register_devices(
      devices_file: "fastlane/Devicefile"
    )
  end

  desc "Sync team Code-Signing assets"
  lane :sync_signing_assets do |options|
    sync_device_info
    selectedType = options[:type]
    match(type: selectedType)
  end

  desc "Re-obtain match code-signing credentials on new machine"
  lane :bootstrap_code_signing do
    sync_device_info
    match(type: "development")
    match(type: "adhoc")
    match(type: "appstore")
  end

  desc "Build for App Store submission"
  lane :build_appstore do

    sync_signing_assets(type: "appstore")
    increment_build_number
    gym(
      output_directory: "build_Appstore",
      clean: true,
      export_options: {
        method: "app-store",
        provisioningProfiles: {
          "#{ENV['APP_IDENTIFIER']}" => ENV['sigh_co.App_appstore_profile-path']
        }
      }
    )
  end

  desc "Build for Ad Hoc submission"
  lane :build_adhoc do

    sync_signing_assets(type: "adhoc")
    increment_build_number
    gym(
      output_directory: "build_AdHoc",
      clean: true,
      export_options: {
        method: "ad-hoc",
        provisioningProfiles: {
          "#{ENV['APP_IDENTIFIER']}" => ENV['sigh_co.App_adhoc_profile-path']
        }
      }
    )
  end

  # --- Testing
  lane :distrubute_to_appstore do
    build_appstore
    pilot(
      changelog: "Version {lane_context[SharedValues::VERSION_NUMBER]}, Build {lane_context[SharedValues::BUILD_NUMBER]}"
    )
  end
  # --- END
end

```
</details>

<details><summary>`./Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

app_identifier ENV['APP_IDENTIFIER']
apple_id ENV['APPLE_ID']
team_id ENV['TEAM_ID']
team_name ENV['TEAM_NAME']
itc_team_name ENV['TEAM_NAME']
itc_team_id ENV['ITC_TEAM_ID']
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.163.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday                   | 1.0.1        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| emoji_regex               | 1.0.1        |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.16.0       |
| unicode-display_width     | 1.7.0        |
| public_suffix             | 4.0.4        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| excon                     | 0.73.0       |
| unf_ext                   | 0.0.7.7      |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| os                        | 1.1.0        |
| memoist                   | 0.16.2       |
| googleauth                | 0.12.0       |
| digest-crc                | 0.5.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-env          | 1.3.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.1       |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.1.3        |
| aws-partitions            | 1.317.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.96.1       |
| aws-sdk-kms               | 1.31.0       |
| aws-sdk-s3                | 1.65.0       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-10-16**
</details>

**Comment by minuscorp** [comment]
It seems to me more than a Xcode bug 😪

**Comment by detectedstealth** [comment]
> It seems to me more than a Xcode bug 😪

Really? Because if I run that command alone outside of anything related to fastlane it has no issues resolving. 

I am using Xcode 12.2 beta 3 though.

**Comment by mvarie** [comment]
Same here, using Xcode Version 12.0 (12A7209), with Stripe's `stripe-ios` SPM library. Maddening.

**Comment by minuscorp** [comment]
Same project in Xcode 11 works?

**Comment by detectedstealth** [comment]
> Same project in Xcode 11 works?

I'm targeting iOS 14 so I can't use Xcode 11 therefor I have never tried. And as stated it doesn't seem like it is an issue with Xcode. Because running the failing command separately in terminal works than after I can run the deploy successfully.

**Comment by minuscorp** [comment]
I have used xcodebuild commands raw that were failing on Xcode, it'd be useful to know it this happens in Xcode 11, but I think it is an Xcode issue because, as you said it happens in Xcode but not in raw command. I'd fill a radar

**Comment by detectedstealth** [comment]
> I have used xcodebuild commands raw that were failing on Xcode, it'd be useful to know it this happens in Xcode 11, but I think it is an Xcode issue because, as you said it happens in Xcode but not in raw command. I'd fill a radar

I think you miss understand what I'm saying. I can build my project in Xcode and I can build my project from the terminal. However when using the fastlane commands to do the same it fails on resolving dependencies.

**Comment by minuscorp** [comment]
I'll check if it Xcode fastlane project supports SPM, on the other hand you can always use the SPM fastlane package instead.

**Comment by detectedstealth** [comment]
> I'll check if it Xcode fastlane project supports SPM, on the other hand you can always use the SPM fastlane package instead.

Ok I'll take a look didn't know there was a SPM fastlane package as it's my other dependancies that are failing with it.

**Comment by minuscorp** [comment]
It is still preliminar, didn't have time to add docs

**Comment by firstzooger** [comment]
any updates on this one? or workarounds?
I'm having the exact same issue with these dependencies (FIRAnalyticsConnector' , FirebaseAnalytics' , 'GoogleAppMeasurement') after switching from cocoapods to SPM.

**Comment by minuscorp** [comment]
In seriously sick ATM, I'll check ASAP when I feel bit better

**Comment by detectedstealth** [comment]
@firstzooger try closing Xcode before running the fastlane command. It seems like it is a timeout issue possibly. I found sometimes I have to run my fastlane command a few times for it to be successful. 

Note: I have updated to Xcode 12.2 release candidate and am still having the exact same issue.

**Comment by minuscorp** [comment]
SPM package runs fastlane in the background after killing any other process that might be using the fastlane Swift socket port.

**Comment by MrBenFTW** [comment]
I have a slightly different issue, Fastlane keeps re downloading all the packages after each batch of simulators, is there a way for it to just use the cache? I have over 5 gb worth of swift packages and my internet is so slow

**Comment by minuscorp** [comment]
I think that's an Xcode issue. I recommend to use static number version over ranges, which might cause your issue.

**Comment by MrBenFTW** [comment]
> I think that's an Xcode issue. I recommend to use static number version over ranges, which might cause your issue.

Just tried setting exact versions, same issue. Maybe It is not related to the packages. But Fastlane does download something every single time and it is roughly 5gb 

```
[19:16:19]: Overriding Status Bar
[19:16:19]: $ xcrun simctl status_bar 833CDAFA-B6E0-46F5-863A-DAC2FC0A8932 override --time 2007-01-09T09:41:00+00:00 --dataNetwork wifi --wifiMode active --wifiBars 3 --cellularMode active --cellularBars 4 --batteryState charged --batteryLevel 100 &> /dev/null
[19:16:22]: Running snapshot on: iPhone 7, iPhone 7 Plus, iPhone 8
[19:16:22]: $ set -o pipefail && xcodebuild -scheme FastlaneScreenshot -project ./Aesther.xcodeproj -derivedDataPath /var/folders/0m/pprkxg7n6z73pswzvysm23br0000gn/T/snapshot_derived20201109-15717-6b5es7 -destination 'platform=iOS Simulator,name=iPhone 7,OS=14.2' -destination 'platform=iOS Simulator,name=iPhone 7 Plus,OS=14.2' -destination 'platform=iOS Simulator,name=iPhone 8,OS=14.2' FASTLANE_SNAPSHOT=YES FASTLANE_LANGUAGE=en-US clean build test | tee /Users/benmitchell/Library/Logs/snapshot/FastlaneScreenshot-FastlaneScreenshot.log | xcpretty 
[19:16:22]: ▸ Loading...
```

As soon as it prints `loading...` network activity shoots up maxing my internet speed and downloads about 5gb. The simulators have already been opened so It isn't them

**Comment by minuscorp** [comment]
Can you retrieve the contents of the project in the Derived Data folder and see what's taking so much memory?
