### ISSUE TITLE
expire_previous_builds = true not expiring previous builds in TestFlight

### ISSUE THREAD

**Issue by jamesdixon** [fastlane/fastlane#17452]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Setting `expire_previous_builds = true` on `upload_to_testflight` is not expiring previous builds.

##### Command executed
```
    upload_to_testflight(
      expire_previous_builds: true,
      notify_external_testers: false,
      skip_waiting_for_build_processing: true,
      skip_submission: true
    )
```

##### Complete output when running fastlane, including the stack trace and command used
Uploading to Testflight works, it just doesn't expire the build.

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.6                                     |
| Ruby                        | 2.6.5                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.rvm/gems/ruby-2.6.5/bin/fastlane         |
| Host                        | Mac OS X 10.15.6 (19G2021)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.5/lib                |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.0.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
desc "Deploy a new version to internal users through TestFlight and Google Play"
lane :internal do |options|
  begin
    bump_build_version

    self.runner.current_platform = :ios
    internal

    self.runner.current_platform = :android
    internal
  rescue => ex
    UI.error(ex)
  ensure
    # only commit the version if it's a pull request
    commit_build_version_bump
  end
end

platform :android do
  desc "Deploy a new version to the Google Play internal track"
  lane :internal do
    sign_and_build

    upload_to_play_store(
      track: 'internal',
      version_code: get_build_version,
      skip_upload_screenshots: true,
      skip_upload_images: true,
      aab: "build/app/outputs/bundle/release/app-release.aab"
    )
  end

  desc "Sign and build the app for Android"
  private_lane :sign_and_build do   
    build_flutter_app(build_type: 'appbundle', version_code: get_build_version)
  end
end

platform :ios do
  KEYCHAIN_NAME = nil

  lane :internal do
    create_keychain_for_ci
    
    sign_and_build

    upload_to_testflight(
      expire_previous_builds: true,
      notify_external_testers: false,
      skip_waiting_for_build_processing: true,
      skip_submission: true
    )

    delete_keychain_from_ci
  end

  private_lane :sign_and_build do
    sync_code_signing(
      type: "appstore", 
      readonly: is_ci,
      keychain_name: KEYCHAIN_NAME,
      keychain_password: KEYCHAIN_NAME
    )

    version_code = get_build_version

    increment_build_number(
      build_number: version_code,
      xcodeproj: "ios/Runner.xcodeproj"
    )

    build_flutter_app(build_type: 'ios', version_code: version_code)
    
    # Build an IPA for upload to TestFlight.
    build_ipa
  end

  desc "Exports an IPA for upload. Currently can't be done by Flutter CLI."
  private_lane :build_ipa do
    build_ios_app(
      workspace: "ios/Runner.xcworkspace", 
      scheme: "Runner",
    )
  end

  private_lane :create_keychain_for_ci do
    if is_ci?
      KEYCHAIN_NAME = "temp.keychain".freeze

      create_keychain(
        name: KEYCHAIN_NAME,
        password: KEYCHAIN_NAME,
        default_keychain: true,
        unlock: true,
        timeout: 3600,
      )
    end
  end

  private_lane :delete_keychain_from_ci do
    delete_keychain(
      name: KEYCHAIN_NAME
    ) unless KEYCHAIN_NAME.nil?
  end
end

# Public Lanes

desc "Increments the build version by 1."
lane :bump_build_version do
  Dir.chdir('..')  do
    sh("cider bump build")
  end
end

desc "Commits version bump to Git."
lane :commit_build_version_bump do |options|
  files = [
    'pubspec.yaml', 
    'ios/Runner/Info.plist', 
    'ios/Runner.xcodeproj/project.pbxproj'
  ].concat(options[:files] || [])

  git_add(path: files)
  git_commit(path: files, message: "build version bump [skip ci]")

  push_to_git_remote
end

# Private Lanes

desc "Add a badge to the app icon for visibility."
private_lane :add_badge_to_icon do |options| 
  version_code = options[:version_code]
  raise "Missing version code" if version_code.nil?

  add_badge(dark: true, alpha: true, shield: "Version-#{version_code}")
end

desc "Build a Flutter app through the CLI."
private_lane :build_flutter_app do |options|
  build_type = options[:build_type]
  raise "Missing build type" if build_type.nil?

  version_code = options[:version_code]
  raise "Missing version code" if version_code.nil?

  flutter_command = is_ci? ? "flutter" : "fvm flutter"

  Dir.chdir ".." do
    begin 
      system("#{flutter_command} packages get")
      system("#{flutter_command} clean")
      system("#{flutter_command} build #{build_type} --build-number=#{version_code}")
    rescue => ex
      UI.error ex
      UI.user_error!("There was an error during the build process.")
    end
  end
end

desc "Gets the build version from pubspec.yaml."
private_lane :get_build_version do
  begin
    pubspec = YAML.load_file('../pubspec.yaml')
  rescue
    raise 'Read pubspec.yaml failed'
  end
  version = pubspec['version']
  
  unless version.include?('+')
    raise 'Build version indicator (+) not found in pubspec.yml'
  end

  version_sections = version.split('+')
  version_name = version_sections[0]
  version_code = version_sections[1]
  
  version_code
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# Android
package_name(ENV["APP_BUNDLE_ID"])
json_key_file("./fastlane/google-play-upload-key.json")

# iOS
app_identifier(ENV["APP_BUNDLE_ID"])
apple_id(ENV["FASTLANE_USER"])

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.163.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.17.3       |
| etc                       | 1.0.1        |
| forwardable               | 1.2.0        |
| rake                      | 13.0.1       |
| CFPropertyList            | 3.0.2        |
| concurrent-ruby           | 1.1.7        |
| i18n                      | 0.9.5        |
| minitest                  | 5.14.2       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.7        |
| activesupport             | 4.2.11.3     |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| httpclient                | 2.8.3        |
| json                      | 2.3.1        |
| algoliasearch             | 1.27.4       |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.381.0      |
| aws-sigv4                 | 1.2.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.109.1      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.83.0       |
| babosa                    | 1.0.4        |
| claide                    | 1.0.3        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| netrc                     | 0.11.0       |
| ffi                       | 1.13.1       |
| ethon                     | 0.12.0       |
| typhoeus                  | 1.4.0        |
| cocoapods-core            | 1.9.3        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.4.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| cocoapods-trunk           | 1.5.0        |
| cocoapods-try             | 1.2.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| cocoapods                 | 1.9.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.0.0        |
| excon                     | 0.76.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 1.0.1        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| jwt                       | 2.2.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| signet                    | 0.14.0       |
| googleauth                | 0.14.0       |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.4.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.1       |
| mini_magick               | 4.10.1       |
| plist                     | 3.5.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2020-10-16**
</details></pre>
</details>

**Comment by max-ott** [comment]
Probably related to all the App Store Connect changes. Not sure if everything "propagated" to TestFlight as well.

**Comment by Fields-hash** [comment]
It will change in app store,i am not about this as it can propagate [NJMCDirect](https://www.njmcdirect.one/)
