### ISSUE TITLE
Is it possible to redirect errors or warning message to a file?

### ISSUE THREAD

**Issue by FFDeveloper** [fastlane/fastlane#17466]
I need to redirect the fastlane output when something goes wrong in different files. One for warning messages and one for errror messages. These messages should include all the exception stack when it is supported. Is it possible to achieve this using the error lane or should I use other toosl? I need to detect build errors, signing errors, upload errors and so on.

**Comment by max-ott** [comment]
You'll find the full logs in `tmp/spaceship....log`. They contain the full stack trace and similar.

**Comment by FFDeveloper** [comment]
Sorry but I have no tmp/spaceship... files or directories. In any cases, I don't want the full output, just the error or warning messages.
