### ISSUE TITLE
The request could not be completed because: Access forbidden

### ISSUE THREAD

**Issue by maykonmichel** [fastlane/fastlane#17479]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When I try to log in on init fastlane, I receive access forbidden and cannot continue.

##### Command executed

fastlane init --verbose

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
[✔] 🚀 
DEBUG [2020-10-21 01:16:00.56]: Checking if there are any plugins that should be loaded...
[✔] Looking for iOS and Android projects in current directory...
INFO [2020-10-21 01:16:01.67]: Detected an iOS/macOS project in the current directory: 'Kovver.xcworkspace'
INFO [2020-10-21 01:16:01.76]: -----------------------------
INFO [2020-10-21 01:16:01.76]: --- Welcome to fastlane 🚀 ---
INFO [2020-10-21 01:16:01.76]: -----------------------------
INFO [2020-10-21 01:16:01.77]: fastlane can help you with all kinds of automation for your mobile app
INFO [2020-10-21 01:16:01.77]: We recommend automating one task first, and then gradually automating more over time
WARN [2020-10-21 01:16:01.77]: What would you like to use fastlane for?
1. 📸  Automate screenshots
2. 👩‍✈️  Automate beta distribution to TestFlight
3. 🚀  Automate App Store distribution
4. 🛠  Manual setup - manually setup your project to automate your tasks
?  2
INFO [2020-10-21 01:16:03.48]: -----------------------------------------------------------
INFO [2020-10-21 01:16:03.48]: --- Setting up fastlane for iOS TestFlight distribution ---
INFO [2020-10-21 01:16:03.48]: -----------------------------------------------------------
INFO [2020-10-21 01:16:03.48]: Parsing your local Xcode project to find the available schemes and the app identifier
Select Scheme: 
1. Kovver
2. Kovver-tvOS
?  1
WARN [2020-10-21 01:16:04.51]: Resolving Swift Package Manager dependencies...
INFO [2020-10-21 01:16:04.51]: $ xcodebuild -resolvePackageDependencies -workspace Kovver.xcworkspace -scheme Kovver
INFO [2020-10-21 01:16:06.00]: ▸ Command line invocation:
INFO [2020-10-21 01:16:06.00]: ▸     /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -workspace Kovver.xcworkspace -scheme Kovver
INFO [2020-10-21 01:16:07.83]: ▸ resolved source packages: 
INFO [2020-10-21 01:16:07.84]: $ xcodebuild -showBuildSettings -workspace Kovver.xcworkspace -scheme Kovver
INFO [2020-10-21 01:16:10.30]: $ cd /Users/maykonmichelpalma/Projects/Bitbucket/kovver-app-hillsong/ios && agvtool what-version -terse
INFO [2020-10-21 01:16:11.10]: ▸ 1
INFO [2020-10-21 01:16:11.10]: --------------------------------
INFO [2020-10-21 01:16:11.10]: --- Login with your Apple ID ---
INFO [2020-10-21 01:16:11.10]: --------------------------------
INFO [2020-10-21 01:16:11.10]: To use App Store Connect and Apple Developer Portal features as part of fastlane,
INFO [2020-10-21 01:16:11.10]: we will ask you for your Apple ID username and password
INFO [2020-10-21 01:16:11.10]: This is necessary for certain fastlane features, for example:
INFO [2020-10-21 01:16:11.10]: 
INFO [2020-10-21 01:16:11.10]: - Create and manage your provisioning profiles on the Developer Portal
INFO [2020-10-21 01:16:11.10]: - Upload and manage TestFlight and App Store builds on App Store Connect
INFO [2020-10-21 01:16:11.10]: - Manage your App Store Connect app metadata and screenshots
INFO [2020-10-21 01:16:11.10]: 
INFO [2020-10-21 01:16:11.10]: Your Apple ID credentials will only be stored in your Keychain, on your local machine
INFO [2020-10-21 01:16:11.10]: For more information, check out
INFO [2020-10-21 01:16:11.10]:  https://github.com/fastlane/fastlane/tree/master/credentials_manager
INFO [2020-10-21 01:16:11.10]: 
WARN [2020-10-21 01:16:11.10]: Please enter your Apple ID developer credentials
 [2020-10-21 01:16:11.10]: Apple ID Username:
some-valid@email.com
INFO [2020-10-21 01:16:17.57]: Logging in...
Reading keychain entry, because either user or password were empty
Two-factor Authentication (6 digits code) is enabled for account 'some-valid@email.com'
More information about Two-factor Authentication: https://support.apple.com/en-us/HT204915

If you're running this in a non-interactive session (e.g. server or CI)
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification

(Input `sms` to escape this prompt and select a trusted phone number to send the code as a text message)

(You can also set the environment variable `SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER` to automate this)
(Read more at: https://github.com/fastlane/fastlane/blob/master/spaceship/docs/Authentication.md#auto-select-sms-via-spaceship_2fa_sms_default_phone_number)

Please enter the 6 digit code:
sms
Please select a trusted phone number to send code to:
1. +55 (••) •••••-••••
2. +55 (••) •••••-••••
?  1
Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 4)...
Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 3)...
Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 2)...
Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 1)...
ERROR [2020-10-21 01:16:37.41]: --------------------
ERROR [2020-10-21 01:16:37.41]: fastlane init failed
ERROR [2020-10-21 01:16:37.41]: --------------------
DEBUG [2020-10-21 01:16:37.41]: /Library/Ruby/Gems/2.6.0/gems/fastlane-2.164.0/spaceship/lib/spaceship/client.rb:875:in `block in send_request'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.164.0/spaceship/lib/spaceship/client.rb:630:in `with_retry'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.164.0/spaceship/lib/spaceship/client.rb:855:in `send_request'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.164.0/spaceship/lib/spaceship/client.rb:699:in `request'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.164.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:294:in `request_two_factor_code_from_phone'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.164.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:287:in `request_two_factor_code_from_phone_choose'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.164.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:166:in `handle_two_factor'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.164.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:20:in `handle_two_step_or_factor'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.164.0/spaceship/lib/spaceship/client.rb:499:in `send_shared_login_request'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.164.0/spaceship/lib/spaceship/tunes/tunes_client.rb:127:in `send_login_request'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.164.0/spaceship/lib/spaceship/client.rb:781:in `do_login'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.164.0/spaceship/lib/spaceship/client.rb:389:in `login'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.164.0/spaceship/lib/spaceship/client.rb:351:in `login'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.164.0/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.164.0/fastlane/lib/fastlane/setup/setup_ios.rb:320:in `ask_for_credentials'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.164.0/fastlane/lib/fastlane/setup/setup_ios.rb:84:in `ios_testflight'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.164.0/fastlane/lib/fastlane/setup/setup_ios.rb:48:in `setup_ios'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.164.0/fastlane/lib/fastlane/setup/setup.rb:108:in `start'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.164.0/fastlane/lib/fastlane/commands_generator.rb:121:in `block (2 levels) in run'
/Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
/Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
/Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.164.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
/Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.164.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.164.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.164.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.164.0/bin/fastlane:23:in `<top (required)>'
/usr/local/bin/fastlane:23:in `load'
/usr/local/bin/fastlane:23:in `<main>'
ERROR [2020-10-21 01:16:37.41]: ["The request could not be completed because:", "Access forbidden"]

  </pre>
</details>

### Environment

<details>
  <pre>
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.7                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.7 (19H2)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.1                                                           |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.164.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.4        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-storage      | 1.29.1       |
| emoji_regex               | 3.0.0        |
| nanaimo                   | 0.3.0        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.19.0       |
| public_suffix             | 4.0.6        |
| excon                     | 0.78.0       |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.1.0        |
| json                      | 2.3.1        |
| bundler                   | 2.1.4        |
| os                        | 1.1.1        |
| memoist                   | 0.16.2       |
| googleauth                | 0.14.0       |
| google-cloud-env          | 1.4.0        |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-partitions            | 1.384.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.109.1      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.83.1       |
| forwardable               | 1.3.1        |
| logger                    | 1.4.2        |
| stringio                  | 0.1.4        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.3        |
| date                      | 3.0.1        |
| fileutils                 | 1.4.1        |
| io-console                | 0.5.6        |
| zlib                      | 1.1.0        |
| libxml-ruby               | 3.2.0        |
| rexml                     | 3.2.4        |
| psych                     | 3.2.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.6.0        |
</details>

*generated on:* **2020-10-21**
</details>
  </pre>
</details>

**Comment by max-ott** [comment]
Are you sure that you have either access to https://appstoreconnect.apple.com or https://developer.apple.com/account ?

**Comment by maykonmichel** [comment]
Yes, I do have access to both of them and the account is the holder of the app.

**Comment by maykonmichel** [comment]
I just kept trying and it worked.
