### ISSUE TITLE
Spaceship Ruby script works from terminal, but not from PHP shell_exec

### ISSUE THREAD

**Issue by StavrosHacker** [fastlane/fastlane#17471]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I've written a script with spaceship that downloads a provison profile from the developer portal. The script works as expected when i run it from the terminal, but when i run it through PHP using shell_exec it errors and gives this:
<details>
  <pre> /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- spaceship (LoadError) from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require' from update_profile.rb:1:in `' </pre>
</details>

##### Command executed
What i run in the PHP file:
<details>
  <pre> echo shell_exec("ruby update_profile.rb 2>&1"); </pre>
</details>

**Comment by max-ott** [comment]
I don't think this is an error related to `spaceship`, but rather your implementation. Unfortunately we cannot provide generic support here on Github.
