### ISSUE TITLE
[Fastlane.Swift] bundle exec fastlane customlane always failed. 

### ISSUE THREAD

**Issue by jaderYang** [fastlane/fastlane#17472]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

fastlane failed to receive a connection from the FastlaneRunner binary after 5 seconds, shutting down

I read related closed issues and tried their solutions, but not work. 

https://github.com/fastlane/fastlane/issues/15121#issuecomment-518897032  and https://github.com/fastlane/fastlane/issues/16493

##### Command executed
bundle exec fastlane customlane

##### Complete output when running fastlane, including the stack trace and command used
[✔] 🚀 
[17:15:45]: loading manifest: /Users/macmini/.rvm/gems/ruby-2.7.0/gems/fastlane-2.163.0/fastlane/swift/upgrade_manifest.json
[17:15:45]: FastlaneSwiftRunner project is up-to-date
[17:15:45]: $ ./fastlane/FastlaneRunner lane cmslane swiftServerPort 2000 > /dev/null
/Users/macmini/.rvm/gems/ruby-2.7.0/gems/fastlane-2.163.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/macmini/.rvm/gems/ruby-2.7.0/gems/fastlane-2.163.0/fastlane_core/lib/fastlane_core/ui/errors/fastlane_error.rb:9: warning: The called method `initialize' is defined here
#<Thread:0x00007fe058310a20 /Users/macmini/.rvm/gems/ruby-2.7.0/gems/fastlane-2.163.0/fastlane/lib/fastlane/swift_lane_manager.rb:220 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	5: from /Users/macmini/.rvm/gems/ruby-2.7.0/gems/fastlane-2.163.0/fastlane/lib/fastlane/swift_lane_manager.rb:223:in `block in start_socket_thread'
	4: from /Users/macmini/.rvm/gems/ruby-2.7.0/gems/fastlane-2.163.0/fastlane/lib/fastlane/server/socket_server.rb:38:in `start'
	3: from /Users/macmini/.rvm/gems/ruby-2.7.0/gems/fastlane-2.163.0/fastlane/lib/fastlane/server/socket_server.rb:147:in `listen'
	2: from /Users/macmini/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/timeout.rb:110:in `timeout'
	1: from /Users/macmini/.rvm/gems/ruby-2.7.0/gems/fastlane-2.163.0/fastlane/lib/fastlane/server/socket_server.rb:148:in `block in listen'
/Users/macmini/.rvm/gems/ruby-2.7.0/gems/fastlane-2.163.0/fastlane/lib/fastlane/server/socket_server.rb:148:in `accept': execution expired (Timeout::Error)
	5: from /Users/macmini/.rvm/gems/ruby-2.7.0/gems/fastlane-2.163.0/fastlane/lib/fastlane/swift_lane_manager.rb:223:in `block in start_socket_thread'
	4: from /Users/macmini/.rvm/gems/ruby-2.7.0/gems/fastlane-2.163.0/fastlane/lib/fastlane/server/socket_server.rb:38:in `start'
	3: from /Users/macmini/.rvm/gems/ruby-2.7.0/gems/fastlane-2.163.0/fastlane/lib/fastlane/server/socket_server.rb:146:in `listen'
	2: from /Users/macmini/.rvm/gems/ruby-2.7.0/gems/fastlane-2.163.0/fastlane/lib/fastlane/server/socket_server.rb:151:in `rescue in listen'
	1: from /Users/macmini/.rvm/gems/ruby-2.7.0/gems/fastlane-2.163.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/macmini/.rvm/gems/ruby-2.7.0/gems/fastlane-2.163.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': fastlane failed to receive a connection from the FastlaneRunner binary after 5 seconds, shutting down (FastlaneCore::Interface::FastlaneError)
+-----------+---------+
|    Lane Context     |
+-----------+---------+
| LANE_NAME | cmslane |
+-----------+---------+
[17:15:50]: fastlane failed to receive a connection from the FastlaneRunner binary after 5 seconds, shutting down
[17:15:50]: fastlane finished with errors

[!] fastlane failed to receive a connection from the FastlaneRunner binary after 5 seconds, shutting down

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.7                                     |
| Ruby                        | 2.7.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.21.0                          |
| Installation Source         | ~/.rvm/gems/ruby-2.7.0/bin/fastlane         |
| Host                        | Mac OS X 10.15.7 (19H2)                     |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.7.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.1h  22 Sep 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.0                                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.163.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 2.1.4        |
| rake                      | 13.0.1       |
| CFPropertyList            | 3.0.2        |
| concurrent-ruby           | 1.1.6        |
| i18n                      | 0.9.5        |
| minitest                  | 5.14.1       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.7        |
| activesupport             | 4.2.11.3     |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| httpclient                | 2.8.3        |
| json                      | 2.3.1        |
| algoliasearch             | 1.27.4       |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.383.0      |
| aws-sigv4                 | 1.2.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.109.1      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.83.0       |
| babosa                    | 1.0.4        |
| claide                    | 1.0.3        |
| clamp                     | 1.3.1        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| netrc                     | 0.11.0       |
| ffi                       | 1.13.1       |
| ethon                     | 0.12.0       |
| typhoeus                  | 1.4.0        |
| cocoapods-core            | 1.9.1        |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.4.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.1.0        |
| cocoapods-trunk           | 1.5.0        |
| cocoapods-try             | 1.2.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| cocoapods                 | 1.9.1        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.0.0        |
| excon                     | 0.78.0       |
| multipart-post            | 2.0.0        |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.1.0        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| jwt                       | 2.2.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| signet                    | 0.14.0       |
| googleauth                | 0.14.0       |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.4.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.1       |
| mini_magick               | 4.10.1       |
| plist                     | 3.5.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.9       |
| slather                   | 2.4.9        |
| xcode-install             | 2.6.0        |
</details>

*generated on:* **2020-10-20**
</details>

**Comment by Griffin322** [comment]
Thanks for sharing your reply here keep share your queries here
so anyone from the community who has faced the same issue can also find 
the solution from comments below, keep sharing 
[ mcdvoice](https://www.mcdvoice.onl/)

**Comment by rogerluan** [comment]
Hey 👋 that's very interesting, and very likely to be something different in your setup. Let's try to figure this out.

Are you behind any weird firewall or restricted computer? 
Could you add these env vars to your zshrc or bash_profiles? 

```bash
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

Could you run `bundle exec fastlane customlane --verbose` and post the full results here? 🙏

**Comment by jaderYang** [comment]
sure. I will update later.

**Comment by minuscorp** [comment]
Is this Xcode or SPM also?

**Comment by jaderYang** [comment]
Job reported this error occasionally before, but now it is all back to normal. I closed the ticket first, and I will report it again if it happens later.
Thanks all.
