### ISSUE TITLE
FastlaneCore::Interface::FastlaneCrash: [!] Could not retrieve response as fastlane runs in non-interactive mode

### ISSUE THREAD

**Issue by pranjali420** [fastlane/fastlane#17488]
### New Issue Checklist

- [ ✅ ] Updated fastlane to the latest version
- [ ✅ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ✅ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ✅ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

 Getting Following fastlane error when running the build on CircleCI
 
##### Complete output when running fastlane, including the stack trace and command used

<img width="1365" alt="Screenshot 2020-10-22 at 6 15 43 PM" src="https://user-images.githubusercontent.com/22310234/96875595-fef33880-1494-11eb-9276-c06e03add077.png">

Fastlane version = 2.164.0
Ruby version = 2.7.0
fastlane-plugin-appcenter version = 1.9.0
Xcode version = 12.0.1

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.7                                     |
| Ruby                        | 2.5.5                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.23.0                          |
| Installation Source         | ~/.rvm/gems/ruby-2.5.5/bin/fastlane         |
| Host                        | Mac OS X 10.15.7 (19H2)                     |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.5.5/lib                |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.0.1                                      |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.164.0 | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| slack-notifier                  | 2.3.2        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.5.0        |
| CFPropertyList                  | 3.0.2        |
| addressable                     | 2.7.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| colored                         | 1.2          |
| highline                        | 1.7.10       |
| commander-fastlane              | 4.4.6        |
| ruby2_keywords                  | 0.0.2        |
| faraday                         | 1.1.0        |
| faraday_middleware              | 1.0.0        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.10.1       |
| rubyzip                         | 2.3.0        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.0        |
| bundler                         | 2.1.4        |
| naturally                       | 2.2.0        |
| simctl                          | 1.6.8        |
| uber                            | 0.1.0        |
| declarative-option              | 0.1.0        |
| representable                   | 3.0.4        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.0.2        |
| httpclient                      | 2.8.3        |
| google-api-client               | 0.38.0       |
| jmespath                        | 1.4.0        |
| aws-partitions                  | 1.384.0      |
| aws-sdk-core                    | 3.109.1      |
| aws-sdk-kms                     | 1.39.0       |
| aws-sdk-s3                      | 1.83.1       |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.0.3        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.19.0       |
| public_suffix                   | 4.0.6        |
| tty-screen                      | 0.8.1        |
| babosa                          | 1.0.4        |
| excon                           | 0.78.0       |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.3        |
| faraday-cookie_jar              | 0.0.7        |
| fastimage                       | 2.2.0        |
| json                            | 2.3.1        |
| dotenv                          | 2.7.6        |
| declarative                     | 0.0.20       |
| multi_json                      | 1.15.0       |
| signet                          | 0.14.0       |
| os                              | 1.1.1        |
| memoist                         | 0.16.2       |
| googleauth                      | 0.14.0       |
| rake                            | 13.0.1       |
| digest-crc                      | 0.6.1        |
| google-cloud-errors             | 1.0.1        |
| google-cloud-env                | 1.4.0        |
| google-cloud-core               | 1.5.0        |
| google-cloud-storage            | 1.29.1       |
| emoji_regex                     | 3.0.0        |
</details>

**Comment by dharapatel-arrk** [comment]
Can someone please help me, I'm also facing the same issue.

**Comment by max-ott** [comment]
Does your Apple ID have 2 factor authentication active? Looks like Fastlane wants you to provide the sms code, which is not working in non-interactive modes. If possible switch to an Apple ID without 2factor/step authentication or use the App Store Connect API key where possible.

**Comment by pranjali420** [comment]
Hey @max-ott thanx for the response we have resolve this issue, it is because of we are not able to upload build to app centre through the CI, Which makes total sense for the error that we are getting from the fastlane "Could not retrieve response as fastlane runs in non-interactive mode". now it has been resolve thanks.

**Comment by oleg-lola** [comment]
> Hey @max-ott thanx for the response we have resolve this issue, it is because of we are not able to upload build to app centre through the CI, Which makes total sense for the error that we are getting from the fastlane "Could not retrieve response as fastlane runs in non-interactive mode". now it has been resolve thanks.

Hi. Could you describe how have you solved it and what was the root cause ?

**Comment by max-ott** [comment]
Running a 2FA enabled Apple ID with CI/CD. As the name says it's a non interactive session. Either use an API key for authentication or an (old) Apple ID without 2FA enabled.

**Comment by oleg-lola** [comment]
> Running a 2FA enabled Apple ID with CI/CD. As the name says it's a non interactive session. Either use an API key for authentication or an (old) Apple ID without 2FA enabled.

but we're building android app and tying to upload it to app center only, without running any ios lanes. Moreover same pipeline locally works fine without any interactive

**Comment by max-ott** [comment]
@oleg-lola Please open a new issue. This seems to be a different issue.

**Comment by FunnyFzl** [comment]
I'm also facing the same issue.

**Comment by max-ott** [comment]
@FunnyFzl Please refrain from "me too" comments. Please post your full stack trace and steps to reproduce the issue as it's otherwise not very helpful.

**Comment by oleg-lola** [comment]
@FunnyFzl 
the reason why fastlane  appcenter upload step may fail  is wrong credentials to appcenter.
install appcenter-cli and  log in with `appcenter login` before the actual fastlane run
