### ISSUE TITLE
Failed to upload to testflight due to 2FA code  

### ISSUE THREAD

**Issue by anusebastian** [fastlane/fastlane#17484]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
 </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by anusebastian** [comment]
Fastlane is failed to upload build to testflight .Everything this was working fine till my last release a month back.
After changing the apple id password associated with fastlane and phone number everything stopped working.resolved all those problems by updating keychain and delted cookie from ~/fastlane/[email]/cookie.
But the build failed and it is asking for the 6 digit code which I received but no idea where to enter as am running the build from non-interacting terminal of gitlab CI.
Any help would be really appreciated.  

updated Fastlane to latest version too.

**Comment by grEvenX** [comment]
@anusebastian 2FA doesn't work very well on CI. You can read more about it here: https://docs.fastlane.tools/best-practices/continuous-integration/#security-code-and-session. 

The latest releases of Fastlane supports most of the actions using an [App Store Connect API](http://docs.fastlane.tools/actions/app_store_connect_api_key/#app_store_connect_api_key) Key, so I'd recommend you to update the process to use that as much as possible. Unfortunately there's some actions not supporting it still (e.g. `download_dsyms`).

**Comment by anusebastian** [comment]
@grEvenX   Thanks for your help .
It started working after I created a new session using the command fastlane spaceauth -u user@email.com and updated the same in FASTLANE_SESSION .Also created new app-session password.
