### ISSUE TITLE
FASTLANE_DISABLE_COLORS doesn't have any effect when executing a plugin action

### ISSUE THREAD

**Issue by Cyberbeni** [fastlane/fastlane#17498]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm using the [test_center](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center) plugin to run tests (UI tests sometimes fail because failed to capture view hierarcy and this plugin retries failed tests) and I would like to disable colors on CI but `export FASTLANE_DISABLE_COLORS=1` doesn't seem to have any effect when running an action from the plugin.

##### Command executed
```
export FASTLANE_DISABLE_COLORS=1
bundle exec fastlane multi_scan # has colors
bundle exec fastlane lane_that_only_calls_multi_scan_with_predefined_parameters # has colors
bundle exec fastlane scan # no colors
```

**Comment by Cyberbeni** [comment]
Colors are also not disabled for `bundle exec fastlane add_plugin ...` and `bundle exec fastlane incorrect_lane_name`

**Comment by Cyberbeni** [comment]
From our logs, this used to work with 2.114.0, which was before this change:
https://github.com/fastlane/fastlane/blob/404ca994f8ecd1a8cfec1f1deca445605327fdc9/fastlane/lib/fastlane/cli_tools_distributor.rb#L130
Might not be related. @liamnichols any idea what would cause this?

**Comment by liamnichols** [comment]
Hmmm, `load_dot_env` should only relate to anything in your Dotfiles... 

Does it work if you create the **.env** file in the root of your repo and add `export FASTLANE_DISABLE_COLORS=1` inside it?

**Comment by Cyberbeni** [comment]
Having the `.env` file produces the same results as exporting it manually before running fastlane. I had no .env or .env.default file before.

**Comment by liamnichols** [comment]
Hmmm this is odd... I created a new directory, added the gem and gave it a go and could not reproduce:

<img width="850" alt="Screenshot 2020-11-02 at 18 11 32" src="https://user-images.githubusercontent.com/482871/97897701-28cf1980-1d37-11eb-9f02-a8d80edbd49b.png">

On the other hand, if I do the same thing in my main project repo it doesn't work:

<img width="1644" alt="Screenshot 2020-11-02 at 18 13 00" src="https://user-images.githubusercontent.com/482871/97897767-3dabad00-1d37-11eb-98e6-b2ab5c9a00c5.png">

Maybe double check to confirm if that its ok in a clean project? Then the next steps are probably working out which configuration breaks it

**Comment by Cyberbeni** [comment]
I remember having a default platform, while your first try doesn't have it. I'll check tomorrow if that changes anything.

**Comment by Cyberbeni** [comment]
Ok, it wasn't the default platform. It happens when `gem 'fastlane-plugin-test_center'` is in the Pluginfile

**Comment by Cyberbeni** [comment]
Aha, test_center is using the colorize plugin as opposed to the colored plugin used by fastlane.

**Comment by Cyberbeni** [comment]
Got the fix, just gotta go through the PR checklist
