### ISSUE TITLE
Github Actions: Screenshots are very slow

### ISSUE THREAD

**Issue by destinybonavita** [fastlane/fastlane#17507]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Attempting to take screenshots via Github Actions is taking 25+ minutes and at some points never returning. 

##### Command executed
`fastlane snapshot`

##### Complete output when running
Below showed for 15 minutes with no progress update 

<details>
  <pre> 03:30:36]: ▸ 2020-10-28 03:30:36.410 xcodebuild[5238:788456]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
889
[03:30:36]: ▸ /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/snapshot_derived20201028-1206-y9im82/Logs/Test/Run-App-2020.10.28_03-30-31-+0000.xcresult/Staging/2_Test/Diagnostics/UITests-E9164DC2-E825-4A98-BF3A-89054C1EA71F/UITests-DDB91F6C-0366-437D-B67D-640515763091/Session-UITests-2020-10-28_033036-AcN4tr.log
890
[03:30:36]: ▸ 2020-10-28 03:30:36.411 xcodebuild[5238:787929] [MT] IDETestOperationsObserverDebug: (36CBB56B-E3C5-417D-B41D-D630C158AAC3) Beginning test session UITests-36CBB56B-E3C5-417D-B41D-D630C158AAC3 at 2020-10-28 03:30:36.411 with Xcode 12A7403 on target <DVTiPhoneSimulator: 0x7fbdf46b3c00> {
891
[03:30:36]: ▸ 		SimDevice: iPhone 12 Pro Max (CC21F310-0354-4E5E-BC72-373B3A899549, iOS 14.1, Shutdown)
892
[03:30:36]: ▸ } (14.1 (18A8394))
893
[03:30:45]: ▸ 2020-10-28 03:30:45.237 xcodebuild[5238:787929] [MT] IDETestOperationsObserverDebug: (36CBB56B-E3C5-417D-B41D-D630C158AAC3) Finished requesting crash reports. Continuing with testing. </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.15.7                                          |
| Ruby                        | 2.7.2                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.29.1                               |
| Installation Source         | /usr/local/lib/ruby/gems/2.7.0/bin/fastlane      |
| Host                        | Mac OS X 10.15.7 (19H2)                          |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.7.2/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode_12.1.app/Contents/Developer/ |
| Xcode Version               | 12.1                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| excon                     | 0.78.0       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.1.0        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.14.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.4.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-storage      | 1.29.1       |
| emoji_regex               | 3.0.0        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.386.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.109.1      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.83.1       |
| uri                       | 0.10.0       |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| json                      | 2.3.0        |
| forwardable               | 1.3.1        |
| logger                    | 1.4.2        |
| cgi                       | 0.1.0        |
| timeout                   | 0.1.0        |
| stringio                  | 0.1.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.2.0        |
| strscan                   | 1.0.3        |
| date                      | 3.0.0        |
| delegate                  | 0.1.0        |
| fileutils                 | 1.4.1        |
| zlib                      | 1.1.0        |
| singleton                 | 0.1.0        |
| mini_portile2             | 2.1.0        |
| nokogiri                  | 1.6.8.1      |
| racc                      | 1.4.16       |
| rexml                     | 3.2.3        |
| open3                     | 0.1.0        |
| yaml                      | 0.1.0        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.6.0        |
</details>

*generated on:* **2020-10-28**
</details>

**Comment by destinybonavita** [comment]
> It seems like you have not included the output of `fastlane env`
> 
> To make it easier for us help you resolve this issue, please update the issue to include the output of `fastlane env` 👍

I just updated to include the output of `fastlane env`

**Comment by max-ott** [comment]
AFAIK this is the expected behaviour. Taking screenshots does take time. Feel free to refactor the `snapshot` code to speed up the process.

**Comment by destinybonavita** [comment]
@max-ott, but this hasn't always been this slow. It was working fine one build then a few builds after it slowed down
