### ISSUE TITLE
xcode_install fails with "Could not find Xcode with version '12.1 GM seed'

### ISSUE THREAD

**Issue by joridor** [fastlane/fastlane#17509]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When using Xcode_install function in the Fastfile, after installation, the script ends with an error "Could not find Xcode with version '12.1 GM seed'. 
```
/Applications/Xcode-12.1.GM.seed.app: unsealed contents present in the bundle root

[31m
[!] Could not find Xcode with version '12.1 GM seed'
```
xcode-select has been fired on this installation, but when you try to use Apple Git or any other tool, that tool fails with error:
`xcrun: error: active developer path ("/Applications/Xcode-12.1.GM.seed.app/Contents/Developer") does not exist`

This also happened with '12.0', we had to manually install it. Never an issue before 12. Some regex failing with 12?

##### Command executed
In fastfile, added:
xcode_install version: '12.1 GM seed'

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>[14:31:01]: [32m----------------------------------------[0m
[14:31:01]: [32m--- Step: Verifying fastlane version ---[0m
[14:31:01]: [32m----------------------------------------[0m
[14:31:01]: Your fastlane version 2.165.0 matches the minimum requirement of 2.140.0  ✅
[14:31:01]: [32m-------------------[0m
[14:31:01]: [32m--- Step: is_ci ---[0m
[14:31:01]: [32m-------------------[0m
[14:31:01]: [32m---------------------------[0m
[14:31:01]: [32m--- Step: xcode_install ---[0m
[14:31:01]: [32m---------------------------[0m
Available session is not valid any more. Continuing with normal login.

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0%
100   325  100   325    0     0    472      0 --:--:-- --:--:-- --:--:--   472
%
100   305  100   305    0     0    227      0  0:00:01  0:00:01 --:--:--  297k
%
100   305  100   305    0     0    227      0  0:00:01  0:00:01 --:--:--  297k
%
100   305  100   305    0     0    227      0  0:00:01  0:00:01 --:--:--  297k
%
  0 10.5G    0 1342k    0     0   474k      0  6:27:46  0:00:02  6:27:44 4847k%
  0 10.5G    0 1342k    0     0   474k      0  6:27:46  0:00:02  6:27:44 4847k%
 ...
 99 10.5G   99 10.5G    0     0  10.2M      0  0:17:36  0:17:35  0:00:01 10.3M%
100 10.5G  100 10.5G    0     0  10.2M      0  0:17:36  0:17:36 --:--:-- 10.3M
%/Applications/Xcode-12.1.GM.seed.app: unsealed contents present in the bundle root

[31m
[!] Could not find Xcode with version '12.1 GM seed'[0m

Build step 'Execute shell' marked build as failure
Post-build clean running...
Post-build clean completed.
Recording test results
ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
[Checks API] No suitable checks publisher found.
Finished: FAILURE</pre>
</details>

### Environment

<details>
  <pre>[16:36:17]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.7                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.7 (19H2)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode-12.1.app/Contents/Developer/               |
| Xcode Version               | 12.1                                                           |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
...

if is_ci?
    # Install the required Xcode version if needed.
    # xcode_install version:  '12.0',
    #               username: 'telenet@icapps.com'
    xcversion(version: "~> 12.0") # Selects Xcode 12.0.x
    # Setup the build server when needed.
    setup_jenkins result_bundle: false
    # Unlock the keychain.
    unlock_keychain path: 'login.keychain', 
                    password: 'jenkins'
end

...
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.163.0 | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-ixguard   | 0.1.4   | ✅ Up-To-Date  |
| fastlane-plugin-badge     | 1.4.0   | ✅ Up-To-Date  |
| fastlane-plugin-sentry    | 1.6.0   | ✅ Up-To-Date  |
| fastlane-plugin-appcenter | 1.10.0  | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 2.1.4        |
| rake                      | 13.0.1       |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.382.0      |
| aws-sigv4                 | 1.2.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.109.1      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.83.0       |
| babosa                    | 1.0.4        |
| curb                      | 0.9.10       |
| fastimage                 | 2.2.0        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.0.0        |
| excon                     | 0.76.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.2.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| signet                    | 0.14.0       |
| googleauth                | 0.14.0       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| digest-crc                | 0.6.1        |
| google-cloud-env          | 1.4.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.1       |
| json                      | 2.3.1        |
| mini_magick               | 4.10.1       |
| plist                     | 3.5.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| badge                     | 0.12.0       |
| fastlane-plugin-appcenter | 1.10.0       |
| fastlane-plugin-badge     | 1.4.0        |
| fastlane-plugin-ixguard   | 0.1.4        |
| fastlane-plugin-sentry    | 1.6.0        |
| xcode-install             | 2.6.6        |
| xcresult                  | 0.2.1        |
| xcov                      | 1.7.5        |
</details>

*generated on:* **2020-10-28**
</details>
</pre>
</details>

**Comment by rogerluan** [comment]
That's an issue with xcode-install, unfortunately. You can follow it here: https://github.com/xcpretty/xcode-install/issues/414

**Comment by rogerluan** [comment]
Actually, my bad. The issue I linked is similar but not the same as what you're seeing. 

Looks like there's no `12.1 GM seed` anymore. Run `xcversion update` and then `xcversion list` to see a list of available Xcode versions. You'll see that the 12.1 is no longer a GM, so it's called simply `12.1` now. 

Hope this helps, let me know!
