### ISSUE TITLE
Spaceship Connect API - select_build not working on app_store_version

### ISSUE THREAD

**Issue by john-mejia** [fastlane/fastlane#17510]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [ x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When working with a build with edit status, select build is not actually selecting the build for the submission.

##### Command executed
```
Spaceship::ConnectAPI.login
Spaceship::ConnectAPI.select_team
app = Spaceship::ConnectAPI::App.find(APP_ID_APPSTORE)
edit_version = app.get_edit_app_store_version
edit_version.select_build // This returns the latest build, but it does not actually select it when I look on App Store connect.
build_number = edit_version.get_build.version //This fails with "no data" from the `get_build` call
```
Fastlane version = fastlane 2.165.0

**Comment by max-ott** [comment]
Please re-open the issue adding all information as per our issue templates.
