### ISSUE TITLE
Spaceship Connect API - select_build not working on app_store_version

### ISSUE THREAD

**Issue by john-mejia** [fastlane/fastlane#17522]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When working with a build with edit status, select build is not actually selecting the build for the submission.

>     Spaceship::ConnectAPI.login
>     Spaceship::ConnectAPI.select_team
>     app = Spaceship::ConnectAPI::App.find(APP_ID_APPSTORE)
>     edit_version = app.get_edit_app_store_version
>     edit_version.select_build

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> ~/workspace/iphone-application   fastlane_test  fl set_the_build                                                             1 ↵  4744  10:46:17
[✔] 🚀
+-------------------------------------------+---------+------------------------------------------------+
|                                             Used plugins                                             |
+-------------------------------------------+---------+------------------------------------------------+
| Plugin                                    | Version | Action                                         |
+-------------------------------------------+---------+------------------------------------------------+
| fastlane-plugin-badge                     | 1.4.0   | add_badge                                      |
| fastlane-plugin-test_center               | 3.14.4  | suppressed_tests suppress_tests                |
|                                           |         | tests_from_xcresult suppress_tests_from_junit  |
|                                           |         | tests_from_xctestrun                           |
|                                           |         | quit_core_simulator_service                    |
|                                           |         | collate_test_result_bundles tests_from_junit   |
|                                           |         | multi_scan test_options_from_testplan          |
|                                           |         | collate_html_reports collate_junit_reports     |
|                                           |         | collate_json_reports testplans_from_scheme     |
|                                           |         | collate_xcresults                              |
| fastlane-plugin-firebase_app_distribution | 0.2.3   | firebase_app_distribution_login                |
|                                           |         | firebase_app_distribution                      |
+-------------------------------------------+---------+------------------------------------------------+

[10:46:52]: ------------------------------
[10:46:52]: --- Step: default_platform ---
[10:46:52]: ------------------------------
[10:46:52]: Driving the lane 'ios set_the_build' 🚀
Multiple teams found on the Developer Portal, please enter the number of the team you want to use:
1) [REDACTED]
2) [REDACTED]
1
Multiple teams found on the Developer Portal, please enter the number of the team you want to use:
1) [REDACTED]
2) [REDACTED]
1

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
+------+------------------+-------------+

+---------------------------+--------------+----------------+
|                 Plugin updates available                  |
+---------------------------+--------------+----------------+
| Plugin                    | Your Version | Latest Version |
+---------------------------+--------------+----------------+
| test_center               | 3.14.4       | 3.14.7         |
| firebase_app_distribution | 0.2.3        | 0.2.4          |
+---------------------------+--------------+----------------+
[10:47:10]: To update all plugins, just run
[10:47:10]: $ bundle exec fastlane update_plugins

[10:47:10]: fastlane.tools finished successfully 🎉
 ~/workspace/iphone-application   fastlane_test  </pre>
</details>

### Environment

<details>
  <pre><details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.7                                     |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.rbenv/versions/2.6.3/bin/fastlane        |
| Host                        | Mac OS X 10.15.7 (19H2)                     |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.3/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2s  28 May 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.5                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
require "spaceship"
default_platform :ios

platform :ios do
  ## Variables
  APP_ID_APPSTORE = [REDACTED]
  VERSION_PLIST_PATH = './version_properties.plist'

  desc 'Set the build'
  lane :set_the_build do |options|
    Spaceship::ConnectAPI.login
    Spaceship::ConnectAPI.select_team
    app = Spaceship::ConnectAPI::App.find(APP_ID_APPSTORE)
    edit_version = app.get_edit_app_store_version
    edit_version.select_build
  end

end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.165.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status      |
| ----------------------------------------- | ------- | ------------------ |
| fastlane-plugin-badge                     | 1.4.0   | ✅ Up-To-Date       |
| fastlane-plugin-test_center               | 3.14.4  | 🚫 Update available |
| fastlane-plugin-firebase_app_distribution | 0.2.3   | 🚫 Update available |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.3.0        |
| bundler                                   | 1.17.2       |
| etc                                       | 1.0.1        |
| forwardable                               | 1.2.0        |
| rake                                      | 13.0.1       |
| CFPropertyList                            | 3.0.2        |
| concurrent-ruby                           | 1.1.7        |
| i18n                                      | 0.9.5        |
| minitest                                  | 5.14.2       |
| thread_safe                               | 0.3.6        |
| tzinfo                                    | 1.2.7        |
| activesupport                             | 4.2.11.3     |
| public_suffix                             | 4.0.6        |
| addressable                               | 2.7.0        |
| httpclient                                | 2.8.3        |
| json                                      | 2.3.1        |
| algoliasearch                             | 1.27.4       |
| atomos                                    | 0.1.3        |
| aws-eventstream                           | 1.1.0        |
| aws-partitions                            | 1.388.0      |
| aws-sigv4                                 | 1.2.2        |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.109.1      |
| aws-sdk-kms                               | 1.39.0       |
| aws-sdk-s3                                | 1.83.1       |
| babosa                                    | 1.0.4        |
| curb                                      | 0.9.10       |
| fastimage                                 | 2.2.0        |
| colored                                   | 1.2          |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| dotenv                                    | 2.7.6        |
| emoji_regex                               | 3.2.0        |
| excon                                     | 0.78.0       |
| multipart-post                            | 2.0.0        |
| ruby2_keywords                            | 0.0.2        |
| faraday                                   | 1.1.0        |
| unf_ext                                   | 0.0.7.7      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.0.0        |
| gh_inspector                              | 1.1.3        |
| jwt                                       | 2.2.2        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.1        |
| signet                                    | 0.14.0       |
| googleauth                                | 0.14.0       |
| mini_mime                                 | 1.0.2        |
| declarative                               | 0.0.20       |
| declarative-option                        | 0.1.0        |
| uber                                      | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| google-api-client                         | 0.38.0       |
| digest-crc                                | 0.6.1        |
| google-cloud-env                          | 1.4.0        |
| google-cloud-errors                       | 1.0.1        |
| google-cloud-core                         | 1.5.0        |
| google-cloud-storage                      | 1.29.1       |
| mini_magick                               | 4.10.1       |
| plist                                     | 3.5.0        |
| rubyzip                                   | 2.3.0        |
| security                                  | 0.1.3        |
| naturally                                 | 2.2.0        |
| simctl                                    | 1.6.8        |
| slack-notifier                            | 2.3.2        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.7.0        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| word_wrap                                 | 1.0.0        |
| claide                                    | 1.0.3        |
| colored2                                  | 3.1.2        |
| nanaimo                                   | 0.3.0        |
| xcodeproj                                 | 1.19.0       |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.0        |
| badge                                     | 0.12.0       |
| fuzzy_match                               | 2.0.4        |
| nap                                       | 1.1.0        |
| netrc                                     | 0.11.0       |
| ffi                                       | 1.13.1       |
| ethon                                     | 0.12.0       |
| typhoeus                                  | 1.4.0        |
| cocoapods-core                            | 1.9.1        |
| cocoapods-deintegrate                     | 1.0.4        |
| cocoapods-downloader                      | 1.4.0        |
| cocoapods-plugins                         | 1.0.0        |
| cocoapods-search                          | 1.0.0        |
| cocoapods-stats                           | 1.1.0        |
| cocoapods-trunk                           | 1.5.0        |
| cocoapods-try                             | 1.2.0        |
| escape                                    | 0.0.4        |
| fourflusher                               | 2.3.1        |
| molinillo                                 | 0.6.6        |
| ruby-macho                                | 1.4.0        |
| cocoapods                                 | 1.9.1        |
| coderay                                   | 1.1.3        |
| colorize                                  | 0.8.1        |
| fastlane-plugin-badge                     | 1.4.0        |
| fastlane-plugin-firebase_app_distribution | 0.2.3        |
| trainer                                   | 0.9.1        |
| xctest_list                               | 1.2.1        |
| fastlane-plugin-test_center               | 3.14.4       |
| method_source                             | 1.0.0        |
| pry                                       | 0.13.1       |
| xcode-install                             | 2.6.6        |
</details>

*generated on:* **2020-10-29**
</details> </pre>
</details>

**Comment by rogerluan** [comment]
Hey @john-mejia 👋 

Are you sure your build has finished processing at the moment you're calling `select_build`? 
Did you try passing the `build_id` as parameter? You can get it via e.g. `build = wait_for_build_processing_to_be_complete(app: app, platform: platform, options: options)` (then access via `build.id`) - this also ensures that your build will have already finished processing.

**Comment by john-mejia** [comment]
Trying this led me some more issues. Mainly, it gets stuck on ` Waiting for the build to show up in the build list - this may take a few minutes` even when a build for the app is done processing. I tried passing different params with no luck. 

Waiting for the build to process is not something I'd want to do in CI, is there a way to just get the latest available build given a version like it was previously possible with build trains?

**Comment by rogerluan** [comment]
I don't know enough to answer that question 😬 I'd assume that if this particular behavior has changed, it may not be possible in the latest API that Apple offers (both official and unofficial ones) 😞 

Sounds like the part where you're getting stuck on the main problem here. That seems to be the root cause for the original problem that you reported. However, the code to throw that warning is pretty clear:

```
def processed?
  return processing_state != ProcessingState::PROCESSING
end
```

So looks like the build it is looking to is actually in the `processing` state 🤔 Are there _any_ builds that haven't finished processing in your workflow? Even if it's not the latest?

**Comment by john-mejia** [comment]
Hey @rogerluan , I just tried this again with a combination of different params and it does not work. I imagine it's working for others since this is pretty key for `deliver`

This is what the lane looks like now, I've tried passing in the version/build numbers with no luck.

```
lane :select_build do |options|
    Spaceship::ConnectAPI.login
    Spaceship::ConnectAPI.select_team
    app = Spaceship::ConnectAPI::App.find(APP_ID_APPSTORE)
    edit_version = app.get_edit_app_store_version
    build = FastlaneCore::BuildWatcher.wait_for_build_processing_to_be_complete(app_id: APP_ID_APPSTORE, platform: "ios")
  end
```

In the activity tab for my app, there is nothing processing.

**Comment by john-mejia** [comment]
I thought Deliver might be able to do the build selection for me, since it does it before submitting for review.. It does not actually select the build in this case:

```
deliver(
      app_identifier: APP_ID_APPSTORE,
      build_number: latest_testflight_build_number,
      app_version: version.version_string,
      phased_release: true,
      submit_for_review: false,
      force: true, # Skip HTMl report verification
      skip_metadata: false,
      skip_screenshots: true,
      skip_binary_upload: true,
      run_precheck_before_submit: false,
      # Comes from https://github.com/fastlane/fastlane/issues/5542#issuecomment-254201994
      submission_information: {
        add_id_info_serves_ads: false,
        add_id_info_tracks_action: true,
        add_id_info_tracks_install: true,
        add_id_info_uses_idfa: true,
        add_id_info_limits_tracking: true
      }
    )
```

I imagine since I'm not submitting for review, it's not actually doing the build selection? If `submit_for_review` is `true` it selects the latest build for this version and submits. 

@joshdholtz any thoughts on this one?

**Comment by rogerluan** [comment]
>I imagine since I'm not submitting for review, it's not actually doing the build selection?

Your assumption is correct here, this is the implemented behavior of `deliver`. However, your code (in the issue description) _should_ work since you're manually calling the correct Spaceship methods to select the build on your own instead of relying on `deliver` implementation.

I don't know why it's not working for you, though 😢 I couldn't figure out, after debugging. We need someone else to take a look at this I'm afraid. @joshdholtz are you available? 🙏
