### ISSUE TITLE
Use of FL_SLATHER_BINARY_BASENAME in Slather action fails with arrays

### ISSUE THREAD

**Issue by jgongo** [fastlane/fastlane#17526]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When I try to use an array in the environment variable `FL_SLATHER_BINARY_BASENAME` the execution of `slather` fails, because an incorrect `--binary-basename` command line option is generated.

This is the command that gets generated:

```sh
$ bundle exec slather coverage --cobertura-xml --build-directory ./derivedData --output-directory ./sonar-reports --ignore Application/Application/Source/Generated/\* --ignore \*\*/UIComponents/\*.swift --ignore \*\*/\*ViewController.swift --ignore \*\*/\*ViewCell.swift --ignore \*\*/\*View.swift --ignore \*\*/\*Tests/\* --ignore Pods/\* --verbose --input-format profdata --scheme Gluci-Chek\ DEV --workspace Gluci-Chek.xcworkspace --binary-basename MyApp\*,Assets Application/Application.xcodeproj
```

Please, notice that at the end of the line you get: `--binary-basename MyApp\*,Assets` instead of the desired `--binary-basename MyApp\* --binary-basename Assets`

This behavior (several binary basenames) is [supported and documented](https://github.com/SlatherOrg/slather#for-multiple-modules) in Slather.

The problem seems to be related with the [declaration of the parameter in the Slather action](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/slather.rb#L272):

```ruby
FastlaneCore::ConfigItem.new(key: :binary_basename,
                             env_name: "FL_SLATHER_BINARY_BASENAME",
                             description: "Basename of the binary file, this should match the name of your bundle excluding its extension (i.e. YourApp [for YourApp.app bundle])",
                             is_string: false,
                             default_value: false),
FastlaneCore::ConfigItem.new(key: :binary_file,
                             env_name: "FL_SLATHER_BINARY_FILE",
                             description: "Binary file name to be used for code coverage",
                             type: Array,
                             skip_type_validation: true, # skipping validation for backwards compatibility with Boolean type
                             optional: true),
```

Notice how the `binary_file` parameter correctly declares its type as an `Array`, while the `binary_basename` parameter declaration misses this.

##### Command executed

```
% bundle exec fastlane sandbox
```

##### Complete output when running fastlane, including the stack trace and command used

Unneeded, the generated Slather command is already included in the description of the issue.

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                                                |
| --------------------------- | ------------------------------------------------------------------------------------ |
| OS                          | 10.15.7                                                                              |
| Ruby                        | 2.6.5                                                                                |
| Bundler?                    | true                                                                                 |
| Git                         | git version 2.21.0 (Apple Git-122)                                                   |
| Installation Source         | ~/Documents/projects/roche/products/gluci-chek-ios.flsh/.gem/ruby/2.6.0/bin/fastlane |
| Host                        | Mac OS X 10.15.7 (19H2)                                                              |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.5/lib                                                          |
| OpenSSL Version             | OpenSSL 1.1.1h  22 Sep 2020                                                          |
| Is contained                | false                                                                                |
| Is homebrew                 | false                                                                                |
| Is installed via Fabric.app | false                                                                                |
| Xcode Path                  | /Applications/Xcode-11.1.app/Contents/Developer/                                     |
| Xcode Version               | 11.1                                                                                 |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | es_ES.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform(:ios)

platform :ios do
  lane :sandbox do
    slather_arguments = {
      workspace: "#{ENV['PROJECT_NAME']}.xcworkspace",
      proj: "Application/Application.xcodeproj",
      scheme: "#{ENV['PROJECT_NAME']} #{ENV['BUILD_SCHEME_SUFFIX']}",
      input_format: "profdata",
      output_directory: "./sonar-reports",
      cobertura_xml: true,
      ignore: [
        "Application/Application/Source/Generated/*",
        "**/UIComponents/*.swift",
        "**/*ViewController.swift",
        "**/*ViewCell.swift",
        "**/*View.swift",
        "**/*Tests/*",
        "Pods/*"
      ],
      verbose: true,
      use_bundle_exec: true
    }
    slather(slather_arguments)
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier ENV['APP_IDENTIFIER']
```
</details>

<details><summary>`.env`</summary>

```sh
# Among other things
FL_SLATHER_BINARY_BASENAME=MyApp*,Assets
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.165.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.2.4   | ✅ Up-To-Date  |
| fastlane-plugin-lizard                    | 1.3.2   | ✅ Up-To-Date  |
| fastlane-plugin-sentry                    | 1.6.0   | ✅ Up-To-Date  |
| fastlane-plugin-google_drive              | 0.5.0   | ✅ Up-To-Date  |
| fastlane-plugin-badge                     | 1.4.0   | ✅ Up-To-Date  |
| fastlane-plugin-xcconfig                  | 2.0.0   | ✅ Up-To-Date  |
| fastlane-plugin-properties                | 1.1.2   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.3.0        |
| bundler                                   | 2.1.4        |
| rake                                      | 13.0.1       |
| CFPropertyList                            | 3.0.2        |
| concurrent-ruby                           | 1.1.7        |
| i18n                                      | 1.8.5        |
| minitest                                  | 5.14.2       |
| thread_safe                               | 0.3.6        |
| tzinfo                                    | 1.2.7        |
| activesupport                             | 5.2.4.4      |
| public_suffix                             | 4.0.6        |
| addressable                               | 2.7.0        |
| httpclient                                | 2.8.3        |
| json                                      | 2.3.1        |
| algoliasearch                             | 1.27.5       |
| atomos                                    | 0.1.3        |
| aws-eventstream                           | 1.1.0        |
| aws-partitions                            | 1.388.0      |
| aws-sigv4                                 | 1.2.2        |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.109.1      |
| aws-sdk-kms                               | 1.39.0       |
| aws-sdk-s3                                | 1.83.1       |
| babosa                                    | 1.0.4        |
| curb                                      | 0.9.10       |
| fastimage                                 | 2.2.0        |
| colored                                   | 1.2          |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| dotenv                                    | 2.7.6        |
| emoji_regex                               | 3.2.0        |
| excon                                     | 0.78.0       |
| multipart-post                            | 2.0.0        |
| ruby2_keywords                            | 0.0.2        |
| faraday                                   | 1.1.0        |
| unf_ext                                   | 0.0.7.7      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.0.0        |
| gh_inspector                              | 1.1.3        |
| jwt                                       | 2.2.2        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.1        |
| signet                                    | 0.14.0       |
| googleauth                                | 0.14.0       |
| mini_mime                                 | 1.0.2        |
| declarative                               | 0.0.20       |
| declarative-option                        | 0.1.0        |
| uber                                      | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| google-api-client                         | 0.38.0       |
| digest-crc                                | 0.6.1        |
| google-cloud-env                          | 1.4.0        |
| google-cloud-errors                       | 1.0.1        |
| google-cloud-core                         | 1.5.0        |
| google-cloud-storage                      | 1.29.1       |
| mini_magick                               | 4.10.1       |
| plist                                     | 3.5.0        |
| rubyzip                                   | 2.3.0        |
| security                                  | 0.1.3        |
| naturally                                 | 2.2.0        |
| simctl                                    | 1.6.8        |
| slack-notifier                            | 2.3.2        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.7.0        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| word_wrap                                 | 1.0.0        |
| claide                                    | 1.0.3        |
| colored2                                  | 3.1.2        |
| nanaimo                                   | 0.3.0        |
| xcodeproj                                 | 1.19.0       |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.0        |
| badge                                     | 0.12.0       |
| cork                                      | 0.3.0        |
| nap                                       | 1.1.0        |
| open4                                     | 1.3.4        |
| claide-plugins                            | 0.9.2        |
| clamp                                     | 1.3.2        |
| fuzzy_match                               | 2.0.4        |
| netrc                                     | 0.11.0       |
| ffi                                       | 1.13.1       |
| ethon                                     | 0.12.0       |
| typhoeus                                  | 1.4.0        |
| cocoapods-core                            | 1.10.0       |
| cocoapods-deintegrate                     | 1.0.4        |
| cocoapods-downloader                      | 1.4.0        |
| cocoapods-plugins                         | 1.0.0        |
| cocoapods-search                          | 1.0.0        |
| cocoapods-trunk                           | 1.5.0        |
| cocoapods-try                             | 1.2.0        |
| escape                                    | 0.0.4        |
| fourflusher                               | 2.3.1        |
| molinillo                                 | 0.6.6        |
| ruby-macho                                | 1.4.0        |
| cocoapods                                 | 1.10.0       |
| coderay                                   | 1.1.3        |
| faraday-http-cache                        | 2.2.0        |
| rchardet                                  | 1.8.0        |
| git                                       | 1.7.0        |
| rexml                                     | 3.2.4        |
| kramdown                                  | 2.3.0        |
| kramdown-parser-gfm                       | 1.1.0        |
| no_proxy_fix                              | 0.1.2        |
| sawyer                                    | 0.8.2        |
| octokit                                   | 4.19.0       |
| danger                                    | 8.2.0        |
| mime-types-data                           | 3.2020.0512  |
| mime-types                                | 3.3.1        |
| multi_xml                                 | 0.6.0        |
| httparty                                  | 0.18.1       |
| gitlab                                    | 4.16.1       |
| danger-gitlab                             | 8.0.0        |
| thor                                      | 0.20.3       |
| danger-swiftlint                          | 0.24.4       |
| fastlane-plugin-badge                     | 1.4.0        |
| fastlane-plugin-firebase_app_distribution | 0.2.4        |
| mini_portile2                             | 2.4.0        |
| nokogiri                                  | 1.10.10      |
| google_drive                              | 3.0.5        |
| fastlane-plugin-google_drive              | 0.5.0        |
| method_source                             | 1.0.0        |
| pry                                       | 0.13.1       |
| fastlane-plugin-lizard                    | 1.3.2        |
| java-properties                           | 0.2.1        |
| fastlane-plugin-properties                | 1.1.2        |
| fastlane-plugin-sentry                    | 1.6.0        |
| fastlane-plugin-xcconfig                  | 2.0.0        |
| prettier                                  | 0.20.1       |
| slather                                   | 2.5.0        |
| xcode-install                             | 2.6.7        |
</details>

*generated on:* **2020-10-30**
</details>

**Comment by jgongo** [comment]
As a workaround, I'm including the following parameter:
```ruby
binary_basename: ENV['FL_SLATHER_BINARY_BASENAME'].split(',')
```
in the `slather` action until this gets solved.

**Comment by SuperBarracuda** [comment]
Im also experiencing this issue we have a project with multiple static frameworks that we'd like to generate coverage for.

https://github.com/SlatherOrg/slather

It's documented slather behaviour.

For multiple modules

If you want to run some modules, but not all (like modules created by CocoaPods) you can do it like this:

`$ slather coverage --binary-basename module1 --binary-basename module2 path/to/project`

**Comment by jgongo** [comment]
Created PR #17606 addressing this.
