### ISSUE TITLE
Seems to be a very old project file format - please open your project file in a more recent version of Xcode

### ISSUE THREAD

**Issue by rafagan** [fastlane/fastlane#17520]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm experiencing the following error:

```
ERROR [2020-10-28 19:12:52.66]: fastlane finished with errors
DEBUG [2020-10-28 19:12:52.66]: All plugins are up to date
bundler: failed to load command: fastlane (/usr/local/var/rbenv/versions/2.7.1/bin/fastlane)
FastlaneCore::Interface::FastlaneError: [!] Seems to be a very old project file format - please open your project file in a more recent version of Xcode
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/actions/update_code_signing_settings.rb:15:in `run'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  ../../pads-ios/Pads/fastlane/Base:20:in `run_match'
  Fastfile:36:in `block (2 levels) in parsing_binding'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.165.0/bin/fastlane:23:in `<top (required)>'
  /usr/local/var/rbenv/versions/2.7.1/bin/fastlane:23:in `load'
  /usr/local/var/rbenv/versions/2.7.1/bin/fastlane:23:in `<top (required)>'
```

Any help?

##### Command executed
The command which causes the error is:

```
update_code_signing_settings(
  use_automatic_signing: false,
  path: ENV['XCPROJ_PATH'],
  team_id: ENV['TEAM_ID']
)
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

[✔] 🚀
[10:10:46]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.15.7                                          |
| Ruby                        | 2.7.1                                            |
| Bundler?                    | true                                             |
| Git                         | git version 2.24.3 (Apple Git-128)               |
| Installation Source         | /usr/local/var/rbenv/versions/2.7.1/bin/fastlane |
| Host                        | Mac OS X 10.15.7 (19H2)                          |
| Ruby Lib Dir                | /usr/local/var/rbenv/versions/2.7.1/lib          |
| OpenSSL Version             | OpenSSL 1.1.1h  22 Sep 2020                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/      |
| Xcode Version               | 12.1                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | pt_BR.UTF-8 | ✅ |
| LC_ALL   | pt_BR.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
import("/Users/Projects/ios/pads-ios/Pads/fastlane/Base")

fastlane_version "2.28.3"
default_platform :ios

platform :ios do
  before_all do
    init()
    ENV['PROJECT_NAME'] = 'RealGuitar'
    ENV['SCHEME'] = 'RealGuitar'
    ENV['APP_IDENTIFIER'] = 'br.com.rodrigokolb.realguitar'
    ENV['XCPROJ_PATH'] = "./#{ENV['PROJECT_NAME']}.xcodeproj"
    ENV['XCWORKSPACE_PATH'] = "./#{ENV['PROJECT_NAME']}.xcworkspace"
    # ENV['APP_DISTRIBUTION'] = '1:91443199327:android:06a0f115ed29361e'
    ENV['CONFIGURATION'] = 'Release'
    ENV['JSON_FILE_NAME'] = 'GoogleService-Info.plist'
  end

  after_all do |lane|
    UI.message('done')
  end

  error do |lane, exception|
    slack(
       message: "Failed: #{exception.to_s}",
       success: false)
  end

  lane :test do
    scan
  end

  lane :do_match do |options|
    # bundle exec fastlane match nuke development
    # bundle exec fastlane match nuke distribution
    run_match(options[:build_method], false)
  end

  desc "Firebase"
  lane :dfb do |options|
    ENV['APPROACH'] = 'Firebase'
    deploy_firebase(options)
  end

  desc "TestFlight"
  lane :dtf do |options|
    ENV['APPROACH'] = 'TestFlight'
    deploy_test_flight(options)
  end

  desc "AppStore"
  lane :das do |options|
    ENV['APPROACH'] = 'AppStore'
    deploy_app_store(options)
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id ENV['APPLE_ID']
team_id 'Z2AQRMWEPF'
itc_team_id '1417705'
itc_team_name 'KOLB SISTEMAS - EIRELI'
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.165.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-semantic_release          | 1.12.0  | ✅ Up-To-Date  |
| fastlane-plugin-firebase_app_distribution | 0.2.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.4.0        |
| bundler                                   | 2.1.4        |
| uri                                       | 0.10.0       |
| rake                                      | 13.0.1       |
| CFPropertyList                            | 3.0.2        |
| concurrent-ruby                           | 1.1.7        |
| i18n                                      | 1.8.5        |
| minitest                                  | 5.14.2       |
| thread_safe                               | 0.3.6        |
| tzinfo                                    | 1.2.7        |
| activesupport                             | 5.2.4.4      |
| public_suffix                             | 4.0.6        |
| addressable                               | 2.7.0        |
| httpclient                                | 2.8.3        |
| json                                      | 2.3.1        |
| algoliasearch                             | 1.27.5       |
| atomos                                    | 0.1.3        |
| aws-eventstream                           | 1.1.0        |
| aws-partitions                            | 1.388.0      |
| aws-sigv4                                 | 1.2.2        |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.109.1      |
| aws-sdk-kms                               | 1.39.0       |
| aws-sdk-s3                                | 1.83.1       |
| babosa                                    | 1.0.4        |
| claide                                    | 1.0.3        |
| fuzzy_match                               | 2.0.4        |
| nap                                       | 1.1.0        |
| netrc                                     | 0.11.0       |
| ffi                                       | 1.13.1       |
| ethon                                     | 0.12.0       |
| typhoeus                                  | 1.4.0        |
| cocoapods-core                            | 1.10.0       |
| cocoapods-deintegrate                     | 1.0.4        |
| cocoapods-downloader                      | 1.4.0        |
| cocoapods-plugins                         | 1.0.0        |
| cocoapods-search                          | 1.0.0        |
| cocoapods-trunk                           | 1.5.0        |
| cocoapods-try                             | 1.2.0        |
| colored2                                  | 3.1.2        |
| escape                                    | 0.0.4        |
| fourflusher                               | 2.3.1        |
| gh_inspector                              | 1.1.3        |
| molinillo                                 | 0.6.6        |
| ruby-macho                                | 1.4.0        |
| nanaimo                                   | 0.3.0        |
| xcodeproj                                 | 1.19.0       |
| cocoapods                                 | 1.10.0       |
| colored                                   | 1.2          |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| declarative                               | 0.0.20       |
| declarative-option                        | 0.1.0        |
| digest-crc                                | 0.6.1        |
| unf_ext                                   | 0.0.7.7      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| dotenv                                    | 2.7.6        |
| emoji_regex                               | 3.0.0        |
| excon                                     | 0.78.0       |
| multipart-post                            | 2.0.0        |
| ruby2_keywords                            | 0.0.2        |
| faraday                                   | 1.1.0        |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.0.0        |
| fastimage                                 | 2.2.0        |
| jwt                                       | 2.2.2        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.1        |
| signet                                    | 0.14.0       |
| googleauth                                | 0.14.0       |
| mini_mime                                 | 1.0.2        |
| uber                                      | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| google-api-client                         | 0.38.0       |
| google-cloud-env                          | 1.4.0        |
| google-cloud-errors                       | 1.0.1        |
| google-cloud-core                         | 1.5.0        |
| google-cloud-storage                      | 1.29.1       |
| mini_magick                               | 4.10.1       |
| plist                                     | 3.5.0        |
| rubyzip                                   | 2.3.0        |
| security                                  | 0.1.3        |
| naturally                                 | 2.2.0        |
| simctl                                    | 1.6.8        |
| slack-notifier                            | 2.3.2        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.7.0        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| word_wrap                                 | 1.0.0        |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.0        |
| fastlane-plugin-firebase_app_distribution | 0.2.4        |
| fastlane-plugin-semantic_release          | 1.12.0       |
</details>

*generated on:* **2020-10-29**
</details>

**Comment by minuscorp** [comment]
Are you using fastlane Swift? Or..? Provide more information if possible. Thanks!

**Comment by rafagan** [comment]
No, I'm using the ruby one.

Ráfagan Sebástian de Abreu
________________________________
De: Jorge <notifications@github.com>
Enviado: quinta-feira, 29 de outubro de 2020 14:15
Para: fastlane/fastlane <fastlane@noreply.github.com>
Cc: Ráfagan Abreu <rafagansa@outlook.com>; Author <author@noreply.github.com>
Assunto: Re: [fastlane/fastlane] Seems to be a very old project file format - please open your project file in a more recent version of Xcode (#17520)


Are you using fastlane Swift? Or..? Provide more information if possible. Thanks!

**Comment by minuscorp** [comment]
Why is trying to open the fastlane Swift's project then?🤔

**Comment by rogerluan** [comment]
That error means your Xcode project file doesn't contain a `TargetAttributes`. This _may_ be related to Xcode 12.1 - would you mind providing your `project.pbxproj` file for analysis?

**Comment by minuscorp** [comment]
Afaik Xcode is format stable (file wise) since Xcode 9. Anyway seeing the backtrace of the op, I only see Ruby execution issue that's what makes me confused in relation with Swift and Xcode 🤔

**Comment by rogerluan** [comment]
> I only see Ruby execution issue that's what makes me confused in relation with Swift and Xcode 🤔

Which part @minuscorp ? I couldn't spot it

**Comment by minuscorp** [comment]
@rogerluan I don't see in the backtrace any reference to this being related to a bad behavior of fastlane. I think that their Xcode pbxproj files are corrupted so fastlane cannot change (it is a simple XML) the signing values. As you called, having the original failing project or the pbxproj file is mandatory to solve the issue, but as I said, there's same compat since Xcode 9, so I _doubt_ Apple changed something in the structure; that and the lack of massive issues makes me think of a corrupted project or a invalid configuration.

**Comment by rafagan** [comment]
After recreate the project and configure everything again, fastlane started working again.

**Comment by minuscorp** [comment]
It seems to me like a corrupted pbxproj can the rest confirm that doing this solves your issues?
