### ISSUE TITLE
[Screengrab] Can't get screenshot when debuggable is false

### ISSUE THREAD

**Issue by GrayaMax** [fastlane/fastlane#17529]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information
- Breaking version: `2.156.0`
- Last working version: `2.155.3`

### Regression Description

In version 2.155.3 screengrab was able to pull screenshot taken on a not debuggable build but in all newest version it can't.
It's seems to be because of use of `run-as` implemented here https://github.com/fastlane/fastlane/pull/17006

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>INFO [2020-10-30 17:08:38.24]: Pulling captured screenshots for locale en-US from the device
DEBUG [2020-10-30 17:08:38.24]: Starting screenshot count is: 0
INFO [2020-10-30 17:08:38.26]: ▸ run-as: package not debuggable: <package.name>
run-as: package not debuggable: <package.name>
ERROR [2020-10-30 17:08:38.26]: Exit status: 1
INFO [2020-10-30 17:08:38.28]: ▸ run-as: package not debuggable: <package.name>
run-as: package not debuggable: <package.name>
ERROR [2020-10-30 17:08:38.28]: Exit status: 1
INFO [2020-10-30 17:08:38.29]: ▸ run-as: package not debuggable: <package.name>
run-as: package not debuggable: <package.name>
ERROR [2020-10-30 17:08:38.29]: Exit status: 1
INFO [2020-10-30 17:08:38.31]: ▸ run-as: package not debuggable: <package.name>
run-as: package not debuggable: <package.name>
ERROR [2020-10-30 17:08:38.31]: Exit status: 1
INFO [2020-10-30 17:08:38.33]: ▸ run-as: package not debuggable: <package.name>
run-as: package not debuggable: <package.name>
ERROR [2020-10-30 17:08:38.33]: Exit status: 1
DEBUG [2020-10-30 17:08:38.33]: Ending screenshot count is: 0</pre>
</details>

**Comment by GrayaMax** [comment]
I don't know if `faslane env` is really needed for this issue, if you need more informations, don't hesitate to ask :)

**Comment by return-main** [comment]
I had the same issue, the temporary fix is:

In app/build.gradle
```groovy
buildTypes {
release {
// Fastlane needs the app to be debuggable when making screenshots
debuggable project.hasProperty('DEBUGGABLE') ? project.getProperty('DEBUGGABLE').toBoolean() : false

///...
}
}
```

and in the Fastfile
```ruby
      gradle(
        task: 'assemble',
        build_type: 'Release',
        flavor: org,
        properties: {
          'versionCode' => versionCode,
          'versionName' => versionName,
          # Used for Fastlane capture_android_screenshots
          'DEBUGGABLE' => true
        }
      )
```
