### ISSUE TITLE
[Deliver] - Not able to reject the app version which is in Pending Developer Release

### ISSUE THREAD

**Issue by Thangaraj-M** [fastlane/fastlane#17534]
@joshdholtz 

When one version is in Pending Developer release and If set the flag **reject_if_possible** with true, the existing version is not rejected. There was error occurred before the reject method is called. It failed in the verify version method. 

**Error:**
INFO [2020-10-31 18:04:16.76]: Making sure the latest version on App Store Connect matches '3.12.0'...
Exception is... The provided entity includes a relationship with an invalid value - You cannot create a new version of the App in the current state.

**spaceship_logs:**
Logfile created on 2020-10-31 18:04:16 +0530 by logger.rb/v1.4.2
INFO  [18:04:16]: >> GET apps/1529770189/appStoreVersions: [undefined body] 
DEBUG [18:04:18]: << GET apps/1529770189/appStoreVersions: 200 {"data"=>[], "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/apps/1529770189/appStoreVersions?include=build%2CappStoreVersionSubmission&filter%5Bplatform%5D=IOS&filter%5BappStoreState%5D=DEVELOPER_REJECTED%2CINVALID_BINARY%2CMETADATA_REJECTED%2CPREPARE_FOR_SUBMISSION%2CREJECTED%2CWAITING_FOR_REVIEW"}, "meta"=>{"paging"=>{"total"=>0, "limit"=>50}}}
INFO  [18:04:18]: >> POST appStoreVersions: {"data":{"type":"appStoreVersions","attributes":{"versionString":"3.12.0","platform":"IOS"},"relationships":{"app":{"data":{"type":"apps","id":"1529770189"}}}}} 
DEBUG [18:04:19]: << POST appStoreVersions: 409 {"errors"=>[{"id"=>"0b344ffd-bd9c-41de-81f7-586f14cdb489", "status"=>"409", "code"=>"ENTITY_ERROR.RELATIONSHIP.INVALID", "title"=>"The provided entity includes a relationship with an invalid value", "detail"=>"You cannot create a new version of the App in the current state.", "source"=>{"pointer"=>"/data/relationships/app"}}]}

**Comment by max-ott** [comment]
Hi there, please include all required data from the issue template and then re-post your issue again.

**Comment by Thangaraj-M** [comment]
@max-ott I have created issue https://github.com/fastlane/fastlane/issues/17539
