### ISSUE TITLE
fastlane sigh ends with error [!] undefined method `expires' for #<Spaceship::ConnectAPI::Certificate:0x00007f9206abd250> (NoMethodError)

### ISSUE THREAD

**Issue by Qwix** [fastlane/fastlane#17549]
**Summary**: I am trying to use fastlane sigh to update and then download an invalid appstore provisioning profile using a newly created distribution certificate. I am getting an error ```[!] undefined method `expires' for #<Spaceship::ConnectAPI::Certificate:0x00007f9206abd250> (NoMethodError)```

**Note**: This may be similar to https://github.com/fastlane/fastlane/issues/17428 where `owner name` was deprecated

**Expected result**: The provisioning profile is updated on the developer portal to use the new distribution certificate and is then downloaded to my local machine.

**Actual result**: The command results in an error ```[!] undefined method `expires' for #<Spaceship::ConnectAPI::Certificate:0x00007f9206abd250> (NoMethodError)```

**Input**: `fastlane sigh --skip-install --username <username> --team_id <team_id> --app_identifier <app_identifier> --provisioning_name <profile_name> --ignore_profiles_with_different_name true --force`

**Output**: 
```
[:heavy_check_mark:] :rocket: 
[10:35:25]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
+-------------------------------------+--------------------------------------------------------+
|                  Summary for sigh 2.166.0                  |
+-------------------------------------+--------------------------------------------------------+
| skip_install				| true			|
| username				| <username>		|
| team_id				| <team id>		|
| app_identifier			| <bundle id>		|
| provisioning_name			| <profile name>	|
| filename				| <profile name>	|
| ignore_profiles_with_different_name	| true			|
| skip_certificate_verification		| true			|
| adhoc					| false			|
| developer_id				| false			|
| development				| false			|
| force					| false			|
| skip_fetch_profiles			| false			|
| platform				| ios			|
| readonly				| false			|
| fail_on_name_taken			| false			|
+-------------------------------------+--------------------------------------------------------+

[10:35:27]: Starting login with user '<username>'
Available session is not valid any more. Continuing with normal login.
[10:35:31]: Successfully logged in
[10:35:31]: Fetching profiles...
[10:35:32]: Provisioning Profile '<profile name>' is not valid, skipping this one...
[10:35:32]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[10:35:32]: Creating new provisioning profile for '<app identifier>' with name '<profile name>' for 'ios' platform
[10:35:32]: Found more than one code signing identity. Choosing the first one. Check out fastlane sigh --help to see all available options.
[10:35:32]: Available Code Signing Identities for current filters:

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run fastlane env to append the fastlane environment to your issue
Traceback (most recent call last):
	17: from /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `<main>'
	16: from /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `load'
	15: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/bin/fastlane:23:in `<top (required)>'
	14: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	13: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/commands_generator.rb:16:in `start'
	12: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/commands_generator.rb:139:in `run'
	11: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	10: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	9: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	8: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	7: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	6: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/commands_generator.rb:61:in `block (2 levels) in run'
	5: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/manager.rb:8:in `start'
	4: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/runner.rb:48:in `run'
	3: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/runner.rb:186:in `create_profile!'
	2: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/runner.rb:329:in `certificates_to_use'
	1: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/runner.rb:329:in `each'
/usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/runner.rb:330:in `block in certificates_to_use': undefined method `expires' for #<Spaceship::ConnectAPI::Certificate:0x00007f9206abd250> (NoMethodError)
	17: from /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `<main>'
	16: from /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `load'
	15: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/bin/fastlane:23:in `<top (required)>'
	14: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	13: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/commands_generator.rb:16:in `start'
	12: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/commands_generator.rb:139:in `run'
	11: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	10: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	9: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	8: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	7: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	6: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/commands_generator.rb:61:in `block (2 levels) in run'
	5: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/manager.rb:8:in `start'
	4: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/runner.rb:48:in `run'
	3: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/runner.rb:186:in `create_profile!'
	2: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/runner.rb:329:in `certificates_to_use'
	1: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/runner.rb:329:in `each'
/usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/runner.rb:330:in `block in certificates_to_use': [!] undefined method `expires' for #<Spaceship::ConnectAPI::Certificate:0x00007f9206abd250> (NoMethodError)
```

**Fastlane env**:
<details><summary>:white_check_mark: fastlane environment :white_check_mark:</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.14.4                                          |
| Ruby                        | 2.6.1                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.20.1 (Apple Git-117)               |
| Installation Source         | /usr/local/lib/ruby/gems/2.6.0/bin/fastlane      |
| Host                        | Mac OS X 10.14.4 (18E226)                        |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.6.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2q  20 Nov 2018                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-10_2.app/Contents/Developer/ |
| Xcode Version               | 10.2                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | :white_check_mark: |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

*No Fastfile found**

No Appfile found*

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.166.0 | :white_check_mark: Up-To-Date  |

### Loaded fastlane plugins:

*No plugins Loaded*

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.4        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.76.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| json                      | 2.3.1        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-storage      | 1.29.1       |
| emoji_regex               | 3.0.0        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.380.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.109.1      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.83.0       |

</details>generated on: *2020-11-03*
</details>

**Comment by ryang1428** [comment]
I am also seeing this on 2.166.0 when attempting to run `sigh` for the same purposes. 

```
/Users/jenkins/.rvm/gems/ruby-2.6.5/gems/fastlane-2.166.0/sigh/lib/sigh/runner.rb:330:in `block in certificates_to_use': [!] undefined method `expires' for #<Spaceship::ConnectAPI::Certificate:0x00007f832b43d9c8> (NoMethodError)
```

**Comment by cannc4** [comment]
Same here.

**Comment by iDuuck** [comment]
I got the same error. Looking at the code, I managed not to find the `expires` attribute/method in the `Spaceship::ConnectAPI::Certificate` model. I only see the expiration_date. However, the last change of the line, which is raising, is 4 years ago, hence I don't think that this is the bad thing about this.

**Comment by Qwix** [comment]
@iDuuck the error is coming from line 330 in this file: https://github.com/fastlane/fastlane/blob/master/sigh/lib/sigh/runner.rb

**Comment by iDuuck** [comment]
I know, that it comes from there. But I am not able to find anything about a `expires` attribute in the model (which is being called there), neither in the current master, nor in any commit in the last months.

What I wanted to say about this is, that there needs to be some contributor having a look at this issue. I wanted to help, but can't unfortunately.

**Comment by iDuuck** [comment]
@Qwix However, I managed to get my provisioning profiles created and managed through `match`. Don't know, if this is an option for you until this issue is fixed.

**Comment by tadija** [comment]
another workaround for this problem is to provide the explicit `cert_id` parameter to `sigh` (**cert_id** can be obtained with [spaceship](https://github.com/fastlane/fastlane/tree/master/spaceship))

**Comment by brianhumphreys** [comment]
I experienced this issue whenever I created a certificate with the development flag set to true and then attempted to invoke sigh without the development flag (which defaults to false when not specified).  So I changed:

`  lane :cert_sandbox do
    cert(
      username: <username>,
      team_name: <team name>,
      development: true
    )
  end

  lane :sigh_sandbox do
    sigh(
      username: <username>,
      team_name: <team name>,
      app_identifier: <app identifier>,
    )
  end`

to the following:

`  lane :cert_sandbox do
    cert(
      username: <username>,
      team_name: <team name>,
      development: true
    )
  end

  lane :sigh_sandbox do
    sigh(
      username: <username>,
      team_name: <team name>,
      app_identifier: <app identifier>,
      development: true
    )
  end`

This resolved my issue.  Hope it helps someone.

**Comment by rogerluan** [comment]
@ All

I opened a PR to fix this issue here: https://github.com/fastlane/fastlane/pull/17741
If anyone could help test it, it'd be superb ✨ ❤️
