### ISSUE TITLE
Internal Server Error when running any fastlane commands

### ISSUE THREAD

**Issue by gelodgreat** [fastlane/fastlane#17548]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>I run any fastlane commands and got to this error, This wasnt appearing yesterday just now. But when im running it through bitrise locally it works well. </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

![Error](https://user-images.githubusercontent.com/20021423/97985813-ba13be00-1e13-11eb-8f9c-76c003bceafd.png)

**Comment by gelodgreat** [comment]
https://user-images.githubusercontent.com/20021423/97985813-ba13be00-1e13-11eb-8f9c-76c003bceafd.png
![image](https://user-images.githubusercontent.com/20021423/97986153-47571280-1e14-11eb-86e6-86e5ae915532.png)

**Comment by rogerluan** [comment]
Please provide the environment info as requested above.

Also, if nothing's changed in your environment between a successful execution and a failed one, it might be a legit issue on Apple's end.

**Comment by gelodgreat** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 10.15.7                                                 |
| Ruby                        | 2.7.2                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.29.2                                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.166.0/libexec/bin/fastlane |
| Host                        | Mac OS X 10.15.7 (19H15)                                |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.7.2/lib                        |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                             |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 12.1                                                    |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
default_platform(:android)

before_all do 
end

platform :android do
  desc "Runs all the tests"
  jsonResponse = JSON.parse(app_upload_response)

  lane :splash_dl do
    Dir.chdir('..') do
      sh("curl -o ./assets/bootsplash #{jsonResponse['launchScreen']['url']} " )
      begin
        sh("find . -name bootsplash -exec mogrify -format png {} +;")
      rescue => exception
        UI.error(ex)
      ensure
        sh('cd assets && rm bootsplash')
        sh('cd assets && cp -v -R  bootsplash.png ../android/app/src/main/res/drawable')
        sh('cd assets && cp -v -R  bootsplash.png ../android/app/src/main/res/drawable-hdpi')
        sh('cd assets && cp -v -R  bootsplash.png ../android/app/src/main/res/drawable-ldpi')
        sh('cd assets && cp -v -R  bootsplash.png ../android/app/src/main/res/drawable-mdpi')
        sh('cd assets && cp -v -R  bootsplash.png ../android/app/src/main/res/drawable-xhdpi')
        sh('cd assets && cp -v -R  bootsplash.png ../android/app/src/main/res/drawable-xxhdpi')
        sh('cd assets && cp -v -R  bootsplash.png ../android/app/src/main/res/drawable-xxxhdpi')
      end
      
    end
  end


  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("./android/app/taply-dev.json") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name(ENV["ANDROID_APPLICATION_ID"]) # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.166.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                                 | Version | Update-Status |
| -------------------------------------- | ------- | ------------- |
| fastlane-plugin-increment_version_code | 0.4.3   | ✅ Up-To-Date  |
| fastlane-plugin-appicon                | 0.15.0  | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                                    | Version      |
| -------------------------------------- | ------------ |
| did_you_mean                           | 1.4.0        |
| slack-notifier                         | 2.3.2        |
| atomos                                 | 0.1.3        |
| CFPropertyList                         | 3.0.2        |
| claide                                 | 1.0.3        |
| colored2                               | 3.1.2        |
| nanaimo                                | 0.3.0        |
| xcodeproj                              | 1.19.0       |
| rouge                                  | 2.0.7        |
| xcpretty                               | 0.3.0        |
| terminal-notifier                      | 2.0.0        |
| unicode-display_width                  | 1.7.0        |
| terminal-table                         | 1.8.0        |
| plist                                  | 3.5.0        |
| public_suffix                          | 4.0.6        |
| addressable                            | 2.7.0        |
| multipart-post                         | 2.0.0        |
| word_wrap                              | 1.0.0        |
| tty-screen                             | 0.8.1        |
| tty-cursor                             | 0.7.1        |
| tty-spinner                            | 0.9.3        |
| babosa                                 | 1.0.4        |
| colored                                | 1.2          |
| highline                               | 1.7.10       |
| commander-fastlane                     | 4.4.6        |
| excon                                  | 0.78.0       |
| ruby2_keywords                         | 0.0.2        |
| faraday                                | 1.1.0        |
| unf_ext                                | 0.0.7.7      |
| unf                                    | 0.1.4        |
| domain_name                            | 0.5.20190701 |
| http-cookie                            | 1.0.3        |
| faraday-cookie_jar                     | 0.0.7        |
| faraday_middleware                     | 1.0.0        |
| fastimage                              | 2.2.0        |
| gh_inspector                           | 1.1.3        |
| json                                   | 2.3.0        |
| mini_magick                            | 4.10.1       |
| rubyzip                                | 2.3.0        |
| security                               | 0.1.3        |
| xcpretty-travis-formatter              | 1.0.0        |
| dotenv                                 | 2.7.6        |
| bundler                                | 2.1.4        |
| naturally                              | 2.2.0        |
| simctl                                 | 1.6.8        |
| jwt                                    | 2.2.2        |
| uber                                   | 0.1.0        |
| declarative                            | 0.0.20       |
| declarative-option                     | 0.1.0        |
| representable                          | 3.0.4        |
| retriable                              | 3.1.2        |
| mini_mime                              | 1.0.2        |
| multi_json                             | 1.15.0       |
| signet                                 | 0.14.0       |
| memoist                                | 0.16.2       |
| os                                     | 1.1.1        |
| googleauth                             | 0.14.0       |
| httpclient                             | 2.8.3        |
| google-api-client                      | 0.38.0       |
| google-cloud-env                       | 1.4.0        |
| google-cloud-errors                    | 1.0.1        |
| google-cloud-core                      | 1.5.0        |
| rake                                   | 13.0.1       |
| digest-crc                             | 0.6.1        |
| google-cloud-storage                   | 1.29.1       |
| emoji_regex                            | 3.2.1        |
| jmespath                               | 1.4.0        |
| aws-partitions                         | 1.388.0      |
| aws-eventstream                        | 1.1.0        |
| aws-sigv4                              | 1.2.2        |
| aws-sdk-core                           | 3.109.1      |
| aws-sdk-kms                            | 1.39.0       |
| aws-sdk-s3                             | 1.83.1       |
| uri                                    | 0.10.0       |
| forwardable                            | 1.3.1        |
| logger                                 | 1.4.2        |
| cgi                                    | 0.1.0        |
| timeout                                | 0.1.0        |
| stringio                               | 0.1.0        |
| ipaddr                                 | 1.2.2        |
| openssl                                | 2.1.2        |
| ostruct                                | 0.2.0        |
| strscan                                | 1.0.3        |
| date                                   | 3.0.0        |
| delegate                               | 0.1.0        |
| fileutils                              | 1.4.1        |
| io-console                             | 0.5.6        |
| zlib                                   | 1.1.0        |
| singleton                              | 0.1.0        |
| rexml                                  | 3.2.3        |
| open3                                  | 0.1.0        |
| yaml                                   | 0.1.0        |
| psych                                  | 3.1.0        |
| mutex_m                                | 0.1.0        |
| webrick                                | 1.6.0        |
| fastlane-plugin-increment_version_code | 0.4.3        |
| fastlane-plugin-appicon                | 0.15.0       |
| benchmark                              | 0.1.0        |
</details>


*generated on:* **2020-11-09**
</details>

**Comment by gelodgreat** [comment]
Uploaded my env, I did just remove some of private use

**Comment by rogerluan** [comment]
If it works locally, did you see if Bitrise change anything on their end? Maybe they upgraded the machine's OS, dependencies or something else 🤔 ? Have you tried resetting any cache that might exist in the CI?

**Comment by gelodgreat** [comment]
@rogerluan , in Bitrise locally it works when using Fastlane, but when I'm using Fastlane directly it doesn't work and the error above shows. I've already reinstall many times my fastlane. 

Note:
my fastlane locally is 2.166 the on above while the bitrise locally uses 2.153

**Comment by rogerluan** [comment]
I'm confused with the terminology 😅 Are there these 3 options?

`bitrise` - unknown ❓ 
`bitrise local (?)` - Fastlane 2.166 - doesn't work ❌ 
`your machine` - Fastlane 2.153 - works ✅ 

Is that right?

**Comment by gelodgreat** [comment]
> I'm confused with the terminology 😅 Are there these 3 options?
> 
> `bitrise server` - unknown ❓
> `bitrise local (?)` - Fastlane 2.166 - doesn't work ❌
> `your machine` - Fastlane 2.153 - works ✅
> 
> Is that right?

bitrise server - works
bitrise local - Fastlane 2.153 works
fastlane local pc - Fastlane 2.166 - doesn't work ❌

**Comment by gelodgreat** [comment]
it's now fixed, I've discovered that the error originates from my environment variables, Fastlane is not the fault

**Comment by rogerluan** [comment]
@gelodgreat Great!! 🎉 
Mind sharing what was the issue? 😃 This might help other users solve the same problem in the future 🤗
