### ISSUE TITLE
Badge documentation problems

### ISSUE THREAD

**Issue by dkk** [fastlane/fastlane#17566]
### Issue Description

[Badge's documentation](https://docs.fastlane.tools/actions/badge/) shows the parameter **path**. However, it doesn't seem to exist. The output I get is:
`Could not find option 'path' in the list of available options: dark, alpha, alpha_channel, custom, no_badge, badge_gravity, shield, shield_parameters, shield_io_timeout, shield_geometry, shield_gravity, shield_scale, shield_no_resize, glob, grayscale`

Also, **glob** does not work as expected due to [this problem](https://github.com/HazAT/badge/issues/83). Maybe a note on the glob parameter should be added, since it is very probable that it will be used wrong otherwise.

**Comment by rogerluan** [comment]
Hello @dkk  👋 

This looks like a bad configuration on your end, as it _does_ seem to support a `path` parameter. Please follow [the template provided when you open a new issue](https://raw.githubusercontent.com/fastlane/fastlane/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md) and provide the output of your `fastlane env` command as asked above ☝️ that will earn you results faster.
