### ISSUE TITLE
resign can't find signing identity

### ISSUE THREAD

**Issue by sel38582** [fastlane/fastlane#17575]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
request regarding the resign of an ipa files using enterprise certificate:
The distribution certificate is hosted on a github repository and so I'm using match in fastfile for retrieving the certificate and installing it in a temp keychain (using circleci mac custom image). The certificate is well retrieve and installed, the provisioning profile also, and when resign is run from fastfile or shell command '''fastlane sigh resign com.factory.myapp.ipa --signing_identity ""iPhone Distribution: MyFactory" --provisioning_profile "/Users/distiller/Library/MobileDevice/Provisioning Profiles/4ffa09d4-1212-1212-1212-12121121295.mobileprovision" --keychain_path "/Users/distiller/Library/Keychains/fastlane_tmp_keychain-db''' I got the error that signing Identity could not be find. I f I ssh to the instance and do security find-certificate it could find it so well installed. attached is console result of instance, signing identity is empty ...

##### Command executed
fastlane sigh resign com.factory.myapp.ipa --signing_identity ""iPhone Distribution: MyFactory" --provisioning_profile "/Users/distiller/Library/MobileDevice/Provisioning Profiles/4ffa09d4-1212-1212-1212-12121121295.mobileprovision" --keychain_path "/Users/distiller/Library/Keychains/fastlane_tmp_keychain-db

##### Complete output when running fastlane, including the stack trace and command used
+-------------------+----------------------------+
|             Installed Certificate              |
+-------------------+----------------------------+
| User ID           | A*******J                 	|
| Common Name       | iPhone Distribution: MyFactory 	|
| Organisation Unit | A*******J                 	|
| Organisation      | MyFactory                    |
| Country           | FR                         |
| Start Datetime    | 2020-10-16 09:47:41 UTC    |
| End Datetime      | 2023-10-16 09:47:41 UTC    |
+-------------------+----------------------------+

INFO [2020-11-02 13:09:23.63]: Installing provisioning profile...
WARN [2020-11-02 13:09:23.83]: Setting environment variable 'sigh_com.factory.myapp_enterprise' to '4ffa09d4-1212-1212-1212-12121121295'
WARN [2020-11-02 13:09:23.83]: Setting environment variable 'sigh_com.factory.myapp_enterprise_team-id' to 'A*******J'
WARN [2020-11-02 13:09:23.83]: Setting environment variable 'sigh_com.factory.myapp_enterprise_profile-name' to 'match InHouse com.factory.myapp'
WARN [2020-11-02 13:09:23.83]: Setting environment variable 'sigh_com.factory.myapp_enterprise_profile-path' to '/Users/distiller/Library/MobileDevice/Provisioning Profiles/4ffa09d4-1212-1212-1212-12121121295.mobileprovision'

+---------------------+----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+
|                                                                                        Installed Provisioning Profile                                                                                         |
+---------------------+----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+
| Parameter           | Environment Variable                                                 | Value                                                                                                            |
+---------------------+----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+
| App Identifier      |                                                                      | com.factory.myapp                                                                          |
| Type                |                                                                      | enterprise                                                                                                       |
| Platform            |                                                                      | ios                                                                                                              |
| Profile UUID        | sigh_com.factory.myapp_enterprise              | 4ffa09d4-1212-1212-1212-12121121295                                                                             |
| Profile Name        | sigh_com.factory.myapp_enterprise_profile-name | match InHouse com.factory.myapp                                                            |
| Profile Path        | sigh_com.factory.myapp_enterprise_profile-path | /Users/distiller/Library/MobileDevice/Provisioning Profiles/4ffa09d4-1212-1212-1212-12121121295.mobileprovision |
| Development Team ID | sigh_com.factory.myapp_enterprise_team-id      | A*******J                                                                                                       |
+---------------------+----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+

INFO [2020-11-02 13:09:23.83]: All required keys, certificates and provisioning profiles are installed 🙌
INFO [2020-11-02 13:09:23.84]: Setting Provisioning Profile type to 'enterprise'
Successfully loaded Appfile at path '/Users/distiller/example/fastlane/Appfile'
- app_identifier: 'com.factory.myapp'
- apple_id: 'com.factory.myapp@myfactory.com'
- team_id: 'A*******J'
-------
INFO [2020-11-02 13:09:23.86]: -----------------------------------------------------
INFO [2020-11-02 13:09:23.86]: Step: fastlane sigh resign ./com.factory.myapp.ipa --signing_identity iPhone\ Distribution:\ MyFactory --provisioning_profile /Users/distiller/Library/MobileDevice/Provisioning\ Profiles/4ffa09d4-1212-1212-1212-12121121295.mobileprovision --keychain_path /Users/distiller/Library/Keychains/fastlane_tmp_keychain-db
INFO [2020-11-02 13:09:23.86]: -----------------------------------------------------
INFO [2020-11-02 13:09:26.66]: ▸ [13:09:26]: Couldn't find signing identity 'iPhone Distribution: MyFactory'.
INFO [2020-11-02 13:09:26.70]: ▸ [13:09:26]: Available identities:
INFO [2020-11-02 13:09:26.70]: ▸ [13:09:26]: Signing Identity: 
INFO [2020-11-02 13:09:26.72]: ▸ Looking for related GitHub issues on fastlane/fastlane...
INFO [2020-11-02 13:09:27.59]: ▸ ➡️  GITLAB CI: Could not retrieve response as fastlane runs in non-interactive mode

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

Distillers-Mac:example distiller$ fastlane env
[✔] 🚀
[09:06:30]: fastlane detected a Gemfile in the current directory
[09:06:30]: However, it seems like you didn't use `bundle exec`
[09:06:30]: To launch fastlane faster, please use
[09:06:30]:
[09:06:30]: $ bundle exec fastlane env
[09:06:30]:
[09:06:30]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[09:06:35]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.15.5                                          |
| Ruby                        | 2.7.1                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.28.0                               |
| Installation Source         | ~/.gem/ruby/2.7.1/bin/fastlane                   |
| Host                        | Mac OS X 10.15.5 (19F101)                        |
| Ruby Lib Dir                | ~/.rubies/ruby-2.7.1/lib                         |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-11.7.app/Contents/Developer/ |
| Xcode Version               | 11.7                                             |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

##### ENV VARIABLES #######
APPSTORE_TYPE = ENV["APPSTORE_TYPE"].freeze
FL_RESIGN_IPA = ENV["IPA_PATH"].freeze
FL_RESIGN_SIGNING_IDENTITY = ENV["SIGNING_IDENTITY"].freeze
GIT_URL = ENV["GIT_REPO"].freeze
FASTLANE_PASSWORD = ENV["FASTLANE_PASSWORD"].freeze
MATCH_PASSWORD = ENV["MATCH_PASSWORD"].freeze

opt_out_usage

before_all do
  #setup_circle_ci
end

# enterprise lane for ios
desc "Submit a new build to Enterprise store"
lane :enterprise do

create_keychain(
      name: "circle",
      password: "circle",
      default_keychain: true,
      add_to_search_list: true,
      unlock: true,
      timeout: false
    )

  match(
    git_branch: "master",
    app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
    team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
    verbose: true,
    readonly: true,
	keychain_name: "circle",
	keychain_password: "circle"
  )

  sh("security", "list-keychains")

  sh("security", "find-identity", "-v", "/Users/distiller/Library/Keychains/circle-db")

  # resign application using shell
  FL_RESIGN_PROVISIONING_PROFILE = ENV["sigh_"+CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)+"_enterprise_profile-path"]
  FL_RESIGN_KEYCHAIN_PATH = "/Users/distiller/Library/Keychains/circle-db"
  sh("fastlane" ,"sigh", "resign", FL_RESIGN_IPA, "--signing_identity", FL_RESIGN_SIGNING_IDENTITY, "--provisioning_profile", FL_RESIGN_PROVISIONING_PROFILE, "--keychain_path", FL_RESIGN_KEYCHAIN_PATH)

# resign(
#     ipa: FL_RESIGN_IPA,
#     signing_identity: FL_RESIGN_SIGNING_IDENTITY,
#     provisioning_profile: FL_RESIGN_PROVISIONING_PROFILE,
#	  keychain_path: "/Users/distiller/Library/Keychains/fastlane_tmp_keychain-db"
# )

end


default_platform(:ios)


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

# app_identifier "" # The bundle identifier of your app
# apple_id ""  # Your Apple email address
# team_id ""

app_identifier "com.factory.myapp"
apple_id "com.factory.myapp@myfactory.com"
team_id "A*******J"

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.166.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| CFPropertyList            | 3.0.2        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| uri                       | 0.10.0       |
| nanaimo                   | 0.3.0        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.19.0       |
| public_suffix             | 4.0.6        |
| babosa                    | 1.0.4        |
| excon                     | 0.78.0       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.1.0        |
| faraday-cookie_jar        | 0.0.7        |
| json                      | 2.3.1        |
| mini_magick               | 4.11.0       |
| os                        | 1.1.1        |
| memoist                   | 0.16.2       |
| googleauth                | 0.14.0       |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-env          | 1.4.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.1       |
| emoji_regex               | 3.2.1        |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-partitions            | 1.390.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.109.2      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.83.2       |
| forwardable               | 1.3.1        |
| logger                    | 1.4.2        |
| cgi                       | 0.1.0        |
| timeout                   | 0.1.0        |
| stringio                  | 0.1.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.2.0        |
| strscan                   | 1.0.3        |
| date                      | 3.0.0        |
| delegate                  | 0.1.0        |
| fileutils                 | 1.4.1        |
| io-console                | 0.5.6        |
| zlib                      | 1.1.0        |
| singleton                 | 0.1.0        |
| rexml                     | 3.2.3        |
| open3                     | 0.1.0        |
| yaml                      | 0.1.0        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.6.0        |
</details>

*generated on:* **2020-11-09**
</details>
[09:06:36]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[09:06:36]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅

**Comment by Katsz** [comment]
I'm not sure what is causing the issue but I can suggest you to use identity UUID instead of it's name. It works fine for me
```ruby
<..>
FL_RESIGN_SIGNING_IDENTITY = extract_signing_identity_from_mobileprovision(provision_path: provision)
<..>
private_lane :extract_signing_identity_from_mobileprovision do |options|
    fastlane_require 'shellwords'
    fastlane_require 'plist'

    output_plist_file = "temp"
    provision_profile_file_path = options[:provision_path]&.shellescape

    fail if provision_profile_file_path.nil?

    sh("security cms -D -i #{provision_profile_file_path} > #{output_plist_file}", log: false)
    profile_plist = Plist.parse_xml(output_plist_file)
    File.delete(output_plist_file)

    encoded_provision =
        Base64.encode64(
            profile_plist['DeveloperCertificates'].first.string
        ).gsub!("\n", "")

    res = sh("echo \"#{encoded_provision}\" | base64 -D | openssl x509 -inform DER -noout -fingerprint -sha1 | cut -d = -f 2 | sed -e 's/://g'", log: false)
    res.gsub!("\n", "")
end
```

> Somehow in different environments of mine `sed`'ing `\n` works differently so I just stuck with gsub.

**Comment by sel38582** [comment]
Hi, thanks for feedback,  but we have a workaround, it looks to be a problem root certificate chain. Our enterprise certificates generated by match is delivered using  this Root https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer and match looks to install an oldest chain certification. So we just add this command in fastfile to get the good CA and resign is working as expected: 
  sh("curl -f -o AppleWWDRCAG3.cer \"https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer\"")
  sh("security", "import", "AppleWWDRCAG3.cer", "-k", KEYCHAIN_PATH)

**Comment by mrosales** [comment]
My solution to this was a little bit similar to the solution @Katsz outlined with extracting the identity from the mobileprovision file.

I just posted my personal github the start of a plugin that extracts the bundle id, signing identity and entitlements from the ipa file before using `match` to renew the provisioning profile and then resigns the binary using the existing `resign` action.

https://github.com/mrosales/fastlane-plugin-resign_ipa/blob/main/lib/fastlane/plugin/resign_ipa/actions/resign_ipa_action.rb

Even though there are some workarounds to the issue, I think the `resign` action is a bit difficult to use on its own. Would anyone on the fastlane team like to comment on whether or not it would be a welcome contribution to try to extend the existing resign action to default to pulling values from the provided IPA file and make it a bit more compatible with the recommended workflow of using `match` to manage certificates + profiles?

**Comment by Katsz** [comment]
@mrosales it doesn't make sense for me to extract signing identity from IPA to resign it with.. same exact identity. Am I missing something?

**Comment by mrosales** [comment]
Yeah I could have clarified there, but the most common use case I've had for `resign` is to sign the same binary with an updated provisioning profile. This use is to support in-house Ad Hoc builds to work around:

1. Adding an additional testing device to the provisioning profile and signing the binary without making a new build
2. Resigning the build to get around the 90day adhoc build expiration.

I haven't ever had a need to change the signing identity between sign operations without making a separate build, but I was thinking that it would be a reasonable behavior to just resign with the same signing identity if no `signing_identity` parameter is passed instead of failing with an error.

**Comment by Katsz** [comment]
> You have a point, I guess, but as far as I am aware - most common use is to resign IPA with different bundle (consequently - different team id/profile identified/mobile provision/etc)
 But we're getting far off topic here
