### ISSUE TITLE
Rework policy and bot on auto closing issues

### ISSUE THREAD

**Issue by joshdholtz** [fastlane/fastlane#17585]
### Issue Description
Referenced from #17523

There is a lot of frustration that can occur from both users and maintainers with auto closing (and not auto closing) issues. I think the way we auto close issues might need to be reworked. Some of the current frustrations are:
- Closing of issues that haven’t been looked at or had any real response/resolution
- Locking of issues (which can lead to duplicate issues)
- Spam by bot when users say issue shouldn’t be closed yet

### How
I have no idea how things should get reworked yet but closing of issues should maybe be a bit more manual/deliberate 🤷‍♂️ 

I like this 👉 https://github.com/microsoft/vscode/wiki/Issue-Grooming

**Comment by Sulivans** [comment]
To ensure the long-term sustainability of your open source project is vital that you’re able to attract new contributors (all kinds of contributors, not only code contributors) and make sure they first encounter with your project ends up in a high note. Otherwise, you’ll be losing them forever.

**Comment by 1Pettigrew** [comment]
I have the very same issue. What is the solution [mykfcexperience](https://www.mykfcexperience.us/).
