### ISSUE TITLE
Spaceship::Tunes::Application latest_version not working anymore

### ISSUE THREAD

**Issue by anh1979** [fastlane/fastlane#17595]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

We try to find out whether a certain app version has passed review, we read the app state by using Spaceship
```
Spaceship::Tunes.login(ENV["FASTLANE_USER"], ENV["FASTLANE_PASSWORD"]) 
Spaceship::Tunes.select_team(team_name: ENV["TEAM_NAME"])
app = Spaceship::Tunes::Application.find(ENV["BUNDLE_ID"])
...
```

and then got version information with 
`app.latest_version`

That used to work fine - but since there are macOs Apps created automatically in AppStoreConnect when you setup a new app, it suddenly crashes with this message:
Spaceship::UnexpectedResponse: {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Not Found"], "info"=>nil}, "statusCode"=>"ERROR"}

There now are versionSets (I can't remember seeing those before)...

##### Command executed
`app.latest_version`

Maybe this is connected to issue https://github.com/fastlane/fastlane/issues/17370, I don't know.

Please let me know if the Spaceship::Tunes code part is still in maintenance or if I will have to switch to using the Spaceship::ConnectAPI instead.

**Comment by anh1979** [comment]
Even tried `app.latest_version(platform:'iOS')` instead of `app.latest_version`, but same outcome.

**Comment by MichaelHuy** [comment]
I am facing this issue. It worked well 2 days ago

**Comment by richard1505** [comment]
Im getting the same error when using the command
```Spaceship::Tunes::Application.create!(name: app_store_name, primary_language: primary_language, sku: sku, bundle_id: bundle_id, company_name: company_name)```

**Comment by tmaly1980** [comment]
Yikes! I'm facing this issue as well. I can't switch over to ConnectAPI as I use multiple development teams. I'm not sure how to get around this. All my builds are failing because I can't find the current version in the store/testflight.

Anyone know of a workaround, that doesn't involve ConnectAPI?

**Comment by tmaly1980** [comment]
If you look at the spaceship logs in /tmp, the overview endpoint returns but when trying to get version specifics, that's where it fails:

```
INFO  [12:39:20]: >> GET ra/apps/1524418469/overview: [undefined body]
DEBUG [12:39:21]: << GET ra/apps/1524418469/overview: 200 {"data"=>{"sectionErrorKeys"=>[], "sectionInfoKeys"=>[], "sectionWarningKeys"=>[], "value"=>nil, "adamId"=>"1524418469", "primaryLocaleCode"=>"en-US", "features"=>["PRERELEASE", "PRICING", "GAMECENTER", "SALES_AND_TRENDS", "ANALYTICS", "ARCHIVE"], "appTransferState"=>nil, "localizedMetadata"=>[{"localeCode"=>"en-US", "name"=>"BEATS Barre + Bike"}], "platforms"=>[{"type"=>"APP", "platformString"=>"ios", "everBeenOnSale"=>true, "inFlightVersion"=>{"type"=>"APP", "id"=>"838930204", "version"=>"1.15.9", "state"=>"prepareForUpload", "stateKey"=>"prepareForUpload", "stateGroup"=>"preRelease", "largeAppIcon"=>{"size"=>nil, "width"=>nil, "height"=>nil, "checksum"=>nil, "assetToken"=>nil, "sortOrder"=>nil, "originalFileName"=>nil, "type"=>nil, "url"=>nil, "thumbNailUrl"=>nil}, "supportedHardware"=>["iphone"], "issuesCount"=>0, "hasGrievous"=>false, "isZulu"=>false, "isWatchCombo"=>false}, "deliverableVersion"=>{"type"=>"APP", "id"=>"836934244", "version"=>"1.15.0", "state"=>"readyForSale", "stateKey"=>"readyForSale", "stateGroup"=>"readyForSale", "largeAppIcon"=>{"size"=>117103, "width"=>1024, "height"=>1024, "checksum"=>"76e76c627e925d6457a53e1683a0a7f5", "assetToken"=>"Purple124/v4/a1/ab/39/a1ab3992-082c-3f4a-5ffd-9fe71a4daad7/contsched.juzdzcsg.png", "sortOrder"=>nil, "originalFileName"=>"AppIcon.BEATS-Barre-Bike-0-0-1x~marketing-0-0-0-10-0-0-sRGB-0-0-0-GLES2,0-512MB-85-220-0-0.png", "type"=>"LargeApplicationIcon", "url"=>"https://is1-ssl.mzstatic.com/image/thumb/Purple124/v4/a1/ab/39/a1ab3992-082c-3f4a-5ffd-9fe71a4daad7/contsched.juzdzcsg.png/1024x1024ss-80.png", "thumbNailUrl"=>"https://is3-ssl.mzstatic.com/image/thumb/Purple124/v4/a1/ab/39/a1ab3992-082c-3f4a-5ffd-9fe71a4daad7/contsched.juzdzcsg.png/340x340bb-80.png"}, "supportedHardware"=>["iphone"], "issuesCount"=>0, "hasGrievous"=>false, "isZulu"=>false, "isWatchCombo"=>false}}], "allowedNewVersionPlatforms"=>["osx", "appletvos"], "submittablePlatforms"=>["osx", "appletvos", "ios"], "deleteablePlatforms"=>[], "appStoreUrl"=>"https://apps.apple.com/us/app/beats-barre-bike/id1524418469?ls=1", "analyticsUrl"=>"https://analytics.itunes.apple.com/", "salesAndTrendsUrl"=>"/WebObjects/iTunesConnect.woa/da/jumpTo?page=salesReports", "salesAndTrendsBaseUrl"=>"https://reportingitc2.apple.com/", "isPreOrderLive"=>false, "requiresPreOrderRelease"=>false, "isAAG"=>false, "isFirstParty"=>false, "canCreateAddOn"=>true, "isIAPLimitExceeded"=>false, "hasAppTransferRequest"=>false, "hasValidContract"=>true, "archiveTimestamp"=>nil, "isOrEverWasAKidsApp"=>false, "recurringAddOnCount"=>0, "contractAnnouncements"=>[], "rcIssues"=>[], "everSubmittedAnAddon"=>false, "everSubmittedFreeSubscriptionAddon"=>true, "freeSubscriptionAddonCount"=>0}, "messages"=>{"warn"=>nil, "error"=>nil, "info"=>nil}, "statusCode"=>"SUCCESS"}
INFO  [12:39:21]: >> GET ra/apps/1524418469/platforms/ios/versions/838930204: [undefined body]
DEBUG [12:39:21]: << GET ra/apps/1524418469/platforms/ios/versions/838930204: 404 {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Not Found"], "info"=>nil}, "statusCode"=>"ERROR"}
```

**Comment by tmaly1980** [comment]
After snooping on network traffic when browsing the Activity tab on AppStoreConnect, it appears the endpoint has changed to:

https://appstoreconnect.apple.com/WebObjects/iTunesConnect.woa/ra/apps/<APPID>/buildHistory?platform=ios

I'm in pretty urgent need of this being fixed so I'll look into creating a patch this weekend.

**Comment by tmaly1980** [comment]
Weird, this seems to be working fine for me now, nothing changed. Anyone else still experiencing the issue?

**Comment by anh1979** [comment]
Sorry, no - problem still existing in my case!

**Comment by vimaljake** [comment]
still facing issue

**Comment by danielgalasko** [comment]
Working for us again ¯\_(ツ)_/¯

**Comment by vimaljake** [comment]
> Working for us again ¯_(ツ)_/¯

can you please share the code you using for getting latest version?

**Comment by danielgalasko** [comment]
Sure, in a nutshell

```
    
    UI.message "Fetching version numbers from App Store Connect"
    app_store_build_number
    live_version_number = lane_context[SharedValues::LATEST_VERSION]
    latest_testflight_build_number
    latest_testflight_version = lane_context[SharedValues::LATEST_TESTFLIGHT_VERSION]
    
    UI.message "Downloading live version dsyms"
    download_dsyms(version: live_version_number, username: username)
    if latest_testflight_version != live_version_number then
        UI.message "Downloading latest TestFlight dsyms"
        download_dsyms(version: latest_testflight_version, username: username)
    end
```

That was not working and then it started working again last night

**Comment by danielgalasko** [comment]
It used to fail on `app_store_build_number` but its all good now for us

**Comment by max-ott** [comment]
You should be able to login with the `Spaceship::Tunes` way and still be able to use the `ConnectAPI` without actually using an API key. There is no longer the concept of edit_version vs. live_version. You want to look into something like:

```
bundle exec irb
require "spaceship"
Spaceship::Tunes.login("*************", "("*************")
Spaceship::Tunes.select_team 
5
app = Spaceship::ConnectAPI.get_app(app_id: "123456789")
versions = app.get_app_store_versions
```

Should be a good starting point to test out locally with `irb`

**Comment by vimaljake** [comment]
> You should be able to login with the `Spaceship::Tunes` way and still be able to use the `ConnectAPI` without actually using an API key. There is no longer the concept of edit_version vs. live_version. You want to look into something like:
> 
> ```
> bundle exec irb
> require "spaceship"
> Spaceship::Tunes.login("*************", "("*************")
> Spaceship::Tunes.select_team 
> 5
> app = Spaceship::ConnectAPI.get_app(app_id: "123456789")
> versions = app.get_app_store_versions
> ```
> 
> Should be a good starting point to test out locally with `irb`
Spaceship::UnexpectedResponse (The specified resource does not exist - There is no resource of type 'AppsV1' with id ""
got the above error for the following line
app = Spaceship::ConnectAPI.get_app(app_id: "123456789")

**Comment by richard1505** [comment]
Solved the issue I had with `Spaceship::Tunes::Application.create!` by switching to `Spaceship::ConnectAPI`

**Comment by anh1979** [comment]
> You should be able to login with the `Spaceship::Tunes` way and still be able to use the `ConnectAPI` without actually using an API key. 

**This was the hint that helped - it was a bit rough to get it working, but finally I can read the appstore version and status again. Many thanks!**

after logging and team selection in via 
`
Spaceship::Tunes.login("*************", "("*************")
Spaceship::Tunes.select_team 
`
I do the following

`app = Spaceship::ConnectAPI::App.find(bId)    #use the new way even if we logged in the old way
      unless app.nil?
        UI.message "App name #{app.name}, bundleId #{app.bundle_id} FOUND"
        
        platform = Spaceship::ConnectAPI::Platform::IOS
        filter   = {
          appStoreState: [
            Spaceship::ConnectAPI::AppStoreVersion::AppStoreState::PREPARE_FOR_SUBMISSION,
            Spaceship::ConnectAPI::AppStoreVersion::AppStoreState::DEVELOPER_REJECTED,
            Spaceship::ConnectAPI::AppStoreVersion::AppStoreState::REJECTED,
            Spaceship::ConnectAPI::AppStoreVersion::AppStoreState::METADATA_REJECTED,
            Spaceship::ConnectAPI::AppStoreVersion::AppStoreState::WAITING_FOR_REVIEW,
            Spaceship::ConnectAPI::AppStoreVersion::AppStoreState::INVALID_BINARY,
            Spaceship::ConnectAPI::AppStoreVersion::AppStoreState::IN_REVIEW,
            Spaceship::ConnectAPI::AppStoreVersion::AppStoreState::READY_FOR_SALE,
            Spaceship::ConnectAPI::AppStoreVersion::AppStoreState::PENDING_APPLE_RELEASE,
            Spaceship::ConnectAPI::AppStoreVersion::AppStoreState::PENDING_DEVELOPER_RELEASE
          ].join(","),
          platform: platform
        }

        v = nil
        app.get_app_store_versions(filter: filter).collect do |version|
          v = version
          UI.message "having version: #{version.version_string} - status: #{version.app_store_state}"
        end
`
... and so on analysing what I got with "v". I do the filtering myself because I want the information about those status', too.

Perhaps this might help somebody later.
