### ISSUE TITLE
Spaceship::Tunes::Application.find return nil

### ISSUE THREAD

**Issue by Chren** [fastlane/fastlane#17607]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I have been using Spaceship::Tunes::Application to get AppStore rating for 2 years, but recently, it doesn't work any more. Spaceship::Tunes::Application returns nil.

##### Command executed

```
Spaceship::Tunes.login(appleId, password)
app = Spaceship::Tunes::Application.find(appId)
ratings = app.ratings
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> get_rating.rb:26:in `<main>': undefined method `ratings' for nil:NilClass (NoMethodError) </pre>
</details>

### Environment

<details>
  <pre> [✔] 🚀
[21:22:01]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[21:22:02]: Generating fastlane environment output, this might take a few seconds...
[21:22:02]: undefined method `strip' for nil:NilClass
[21:22:02]: Error rendering markdown table using the following text:
[21:22:02]: | Key | Value |
| fastlane | 2.166.0 |
| OS | Linux data-bongmi 2.6.32-754.29.2.el6.x86_64 #1 SMP Tue May 12 17:39:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Ruby | 2.4.1 |
| Bundler? | false |
| Git | git version 1.7.1 |
| Installation Source | /usr/local/rvm/gems/ruby-2.4.1/bin/fastlane |
| Host | CentOS release 6.10 (Final)
Kernel \r on an \m Linux data-bongmi 2.6.32-754.29.2.el6.x86_64 #1 SMP Tue May 12 17:39:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux (2.6.32-754.29.2.el6.x86_64) |
| Ruby Lib Dir | /usr/local/rvm/rubies/ruby-2.4.1/lib |
| OpenSSL Version | OpenSSL 1.0.1e 11 Feb 2013 |
| Is contained | false |
| Is homebrew | false |
| Is installed via Fabric.app | false |
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key | Value |
| fastlane | 2.166.0 |
| OS | Linux data-bongmi 2.6.32-754.29.2.el6.x86_64 #1 SMP Tue May 12 17:39:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Ruby | 2.4.1 |
| Bundler? | false |
| Git | git version 1.7.1 |
| Installation Source | /usr/local/rvm/gems/ruby-2.4.1/bin/fastlane |
| Host | CentOS release 6.10 (Final)
Kernel \r on an \m Linux data-bongmi 2.6.32-754.29.2.el6.x86_64 #1 SMP Tue May 12 17:39:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux (2.6.32-754.29.2.el6.x86_64) |
| Ruby Lib Dir | /usr/local/rvm/rubies/ruby-2.4.1/lib |
| OpenSSL Version | OpenSSL 1.0.1e 11 Feb 2013 |
| Is contained | false |
| Is homebrew | false |
| Is installed via Fabric.app | false |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.166.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.17.3       |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.18.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.76.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| json                      | 2.0.2        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-storage      | 1.28.0       |
| emoji_regex               | 3.0.0        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.368.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.105.0      |
| aws-sdk-kms               | 1.37.0       |
| aws-sdk-s3                | 1.80.0       |
| openssl                   | 2.0.3        |
| io-console                | 0.4.6        |
| psych                     | 2.2.2        |
</details>

*generated on:* **2020-11-13**
</details>
[21:22:08]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[21:22:08]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅ </pre>
</details>

I saw that "Spaceship::Tunes::Application is going to be completely deprecated. You will need to use the new Spaceship::ConnectAPI". From [here](https://github.com/fastlane/fastlane/issues/16644)
But I didn't find get rating api in Spaceship::ConnectAPI. 
Are there other solution for us to get ratings now?
Thanks.

**Comment by max-ott** [comment]
Please check out https://github.com/fastlane/fastlane/blob/60ce99a5efa04bf80034beeaf014d5935e908987/spaceship/lib/spaceship/connect_api/tunes/tunes.rb#L20

**Comment by Chren** [comment]
> Please check out
> 
> https://github.com/fastlane/fastlane/blob/60ce99a5efa04bf80034beeaf014d5935e908987/spaceship/lib/spaceship/connect_api/tunes/tunes.rb#L20

Hi, thanks for reply. After checking, it seems that age_rating_declarations is not used for getting rating, but for getting rating setting in AppStore Connect.
Please check the link below:
https://developer.apple.com/documentation/appstoreconnectapi/app_metadata/age_rating_declarations

Could you please reopen it?

**Comment by max-ott** [comment]
Not sure what you mean, please clarify.

**Comment by Chren** [comment]
@max
get_age_rating_declaration is not used for getting app store rating, but for getting age rating. 
> Not sure what you mean, please clarify.
![image](https://user-images.githubusercontent.com/349182/99939497-247da580-2da5-11eb-9c4e-8a0ff6633ce5.png)
 
What I want is to get app store rating: 
![image](https://user-images.githubusercontent.com/349182/99939564-52fb8080-2da5-11eb-986d-203321f5a060.png)

**Comment by max-ott** [comment]
Sorry about that, I thought you were looking for the age ratings. As far as I can see this has not been added to `spaceship` yet. Feel free to open a pull request adding this!

**Comment by Chren** [comment]
> Sorry about that, I thought you were looking for the age ratings. As far as I can see this has not been added to `spaceship` yet. Feel free to open a pull request adding this!

Glad to. But I haven't seen apple connect apis provide such an api. Any suggestion on how to implement it?

**Comment by Dinsen** [comment]
@Chren I just tested this with one of the apps we manage and I get the ratings with your code.
