### ISSUE TITLE
download_dsyms should respect FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD

### ISSUE THREAD

**Issue by ethan021021** [fastlane/fastlane#17600]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Currently when running the `download_dsyms` action on CI the action does not respect the `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` env var.

##### Command executed

`download_dsyms(wait_for_dsym_processing: true)`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[19:13:02]: Missing password for user [REDACTED], and running in non-interactive shell
+------+---------------------------+-------------+
|                fastlane summary                |
+------+---------------------------+-------------+
| Step | Action                    | Time (in s) |
+------+---------------------------+-------------+
| 1    | default_platform          | 0           |
| 2    | app_store_connect_api_key | 0           |
| 3    | get_version_number        | 0           |
| 💥   | download_dsyms            | 0           |
+------+---------------------------+-------------+
[19:13:02]: fastlane finished with errors
Looking for related GitHub issues on fastlane/fastlane...
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
bundler: failed to load command: fastlane (/Users/vagrant/.rbenv/versions/2.6.5/bin/fastlane)
RuntimeError: [!] Missing password for user [REDACTED], and running in non-interactive shell
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/credentials_manager/lib/credentials_manager/account_manager.rb:135:in `ask_for_login'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/credentials_manager/lib/credentials_manager/account_manager.rb:56:in `password'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/spaceship/lib/spaceship/client.rb:379:in `login'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/spaceship/lib/spaceship/client.rb:351:in `login'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/spaceship/lib/spaceship/connect_api/client.rb:56:in `login'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/spaceship/lib/spaceship/connect_api/spaceship.rb:85:in `login'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/actions/download_dsyms.rb:18:in `run'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:46:in `block (2 levels) in parsing_binding'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/bin/fastlane:23:in `<top (required)>'
  /Users/vagrant/.rbenv/versions/2.6.5/bin/fastlane:23:in `load'
  /Users/vagrant/.rbenv/versions/2.6.5/bin/fastlane:23:in `<top (required)>'</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.7                                     |
| Ruby                        | 2.6.5                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.29.0                          |
| Installation Source         | ~/.rbenv/versions/2.6.5/bin/fastlane        |
| Host                        | Mac OS X 10.15.7 (19H2)                     |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.5/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "XXX" # Remove this once download_dsyms supports App Store Connect API key

default_platform(:ios)

platform :ios do
  desc "Push a new DevStage build to TestFlight"
  lane :stage_beta do
    version_number = get_version_number(xcodeproj: "XXX.xcodeproj")
    build_number = latest_testflight_build_number(version: version_number) + 1

    increment_build_number(xcodeproj: "XXX.xcodeproj",
                           build_number: build_number)

    build_app(workspace: "XXX.xcworkspace",
              scheme: "XXX",
              configuration: "DevStage",
              export_method: "app-store",
              export_xcargs: "-allowProvisioningUpdates",
              include_bitcode: true)

    upload_to_testflight(notify_external_testers: false,
                         skip_submission: true
                        )

    download_dsyms(app_identifier: "XXX",
                   username: "XXX", # Remove this once download_dsyms supports App Store Connect API key
                   version: version_number,
                   build_number: build_number,
                   wait_for_dsym_processing: true)

    dsyms_path = lane_context[SharedValues::DSYM_PATHS].first()
    gsp_path = "XXX"

    upload_symbols_to_crashlytics(dsym_path: dsyms_path,
                                  platform: "ios",
                                  gsp_path: gsp_path, debug: true)
    clean_build_artifacts
  end

  lane :prod_beta do

  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("XXX") # The bundle identifier of your app

itc_team_id("XXX") # App Store Connect Team ID
team_id("XXX") # Developer Portal Team ID

for_lane :stage_beta do
    app_identifier 'XXX'
end

for_lane :prod_beta do
    app_identifier 'XXX'
end

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.166.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.4        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.78.0       |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.1.0        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.14.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.4.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-storage      | 1.29.1       |
| public_suffix             | 4.0.6        |
| json                      | 2.3.1        |
| mini_magick               | 4.11.0       |
| jwt                       | 2.2.2        |
| emoji_regex               | 3.2.1        |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-partitions            | 1.390.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.109.2      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.84.1       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.10      |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-11-13**
</details>

**Comment by ethan021021** [comment]
Uploaded `fastlane env`

**Comment by Azbagheri** [comment]
We are also encountering the same issue and consequently are not able to use this action in our CI pipelines. It would be amazing if this action can be updated to use FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD and basically to support 2fa for logging in to App Store Connect.

**Comment by tahirmt** [comment]
I was using the `FASTLANE_SESSION` on my local machine but that doesn't work on CI either.

**Comment by ethan021021** [comment]
@tahirmt agreed. I tried that workaround as well and download_dsyms doesn't seem to use it either

**Comment by rogerluan** [comment]
AFAIK this is not supported by Apple. 

`FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` is extremely limited and it only works for uploading the app to the app store, nothing else. 

For more info see https://docs.fastlane.tools/best-practices/continuous-integration/#application-specific-passwords

**Comment by tahirmt** [comment]
@rogerluan perhaps `FASTLANE_SESSION` should work with `download_dsyms` on CI currently it throws an error that password was not provided.

**Comment by ethan021021** [comment]
@tahirmt if that's a possibility that would be awesome

**Comment by rogerluan** [comment]
AFAICT using `FASTLANE_SESSION` should be possible! 🎉 

So it's just a matter of investigating why it doesn't work 🤔

**Comment by tahirmt** [comment]
@rogerluan It works on my local but not on CI. I’m using GitHub actions.

**Comment by rogerluan** [comment]
Oh, I see the problem you're facing now:

>An Apple ID session is only valid for a certain region, meaning if your CI system is in a different region than your local machine, you might run into issues

https://docs.fastlane.tools/best-practices/continuous-integration/#spaceauth

That's likely the limitation you're facing @tahirmt , it's not particular to `download_dsyms` but rather Apple's session control

**Comment by Azbagheri** [comment]
@tahirmt , @ethan021021 I'm using Gitlab  CI and got `FASTLANE_SESSION` working in my pipelines. You should also pass the apple id password using the env  `FASTLANE_PASSWORD`. Also keep in mind that this session is only valid for one day. I'm passing the session dynamically to the pipeline. Fortunately, this is not a job that needs to run very often. So every time we need to run it, a new session is created and passed to the pipeline. 
@rogerluan thanks for the links. I did check Apple APIs earlier and couldn't find an API to download dSYMs. Is there an endpoint to do that?

**Comment by rogerluan** [comment]
Actually there's no official endpoint for `download_dsyms` @Azbagheri, unfortunately 😥 
See https://github.com/fastlane/fastlane/discussions/17485#discussioncomment-125619

**Comment by Azbagheri** [comment]
@rogerluan oh yeah, that's right. The pipeline server has to be in the same time zone as you. We are lucky that way since we use Enterprise Gitlab and have control over the pipeline setup. 
Thanks for your quick response @rogerluan! I thought it was only a matter of time to have all the actions support 2fa. But seems like it'll never happens for some actions. Right? Just out of curiosity, could you please explain why some actions cannot support the `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`?

**Comment by tahirmt** [comment]
@rogerluan It was that my session was in a different region. I used SSH on the VM to get terminal access and created a new session on the CI machine. Now the session works.

**Comment by rogerluan** [comment]
@Azbagheri 

>could you please explain why some actions that need to access App Store Connect cannot support the FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD?

Apple set that limitation AFAIK. I don't really know anything further this, sorry 😅 

However, what is a matter of time is adding support to the api key (the new App Store Connect API) to all the actions. That _should_ happen for all actions, but Apple hasn't provided us enough endpoints for all the actions that we have (although we already have 200+ official APIs, that's not enough). 😞 

@tahirmt glad to hear it works now 🎉🎉🎉

**Comment by Azbagheri** [comment]
@rogerluan I see, thank you so much for the explanation!! Hopefully Apple expands their APIs soon! :)
