### ISSUE TITLE
Documentation issue:I was using the previous App Store Connect API and suddenly something went wrong

### ISSUE THREAD

**Issue by ZhangYingGang666** [fastlane/fastlane#17612]
itunes_app = Spaceship::Tunes::Application.create!(name: appname,
                                        primary_language: app_language,
                                        # version_string: "1.0", # initial version
                                        sku: bundleid,
                                        bundle_id: bundleid)

I didn't have any problems with it until the 12th

Traceback (most recent call last):
	9: from xxx.rb:374:in `<main>'
	8: from xxx.rb:374:in `collect'
	7: from xxx/.rvm/gems/ruby-2.5.1/gems/rubyXL-3.4.3/lib/rubyXL/worksheet.rb:23:in `each'
	6: from xxx/.rvm/gems/ruby-2.5.1/gems/rubyXL-3.4.3/lib/rubyXL/worksheet.rb:23:in `each'
	5: from xxx/.rvm/gems/ruby-2.5.1/gems/rubyXL-3.4.3/lib/rubyXL/worksheet.rb:23:in `block in each'
	4: from xxx/Desktop/cer/auto_v8.41.rb:406:in `block in <main>'
	3: from xxx/Desktop/cer/auto_v8.41.rb:309:in `itunes_connect_action'
	2: from xxx/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/tunes/application.rb:96:in `create!'
	1: from  xxx/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/tunes/tunes_client.rb:296:in `create_application!'
 xxx/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/client.rb:716:in `parse_response': {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Not Found"], "info"=>nil}, "statusCode"=>"ERROR"} (Spaceship::UnexpectedResponse)

**Comment by rogerluan** [comment]
@ZhangYingGang666 please create a new issue providing all the info that the Issue Template asks for.
