### ISSUE TITLE
Option to skip resolvePackageDependencies step

### ISSUE THREAD

**Issue by lukeredpath** [fastlane/fastlane#17628]
For some reason Fastlane automatically runs `xcodebuild -resolvePackageDependencies` which means we aren't able to cache our dependencies on CircleCI.

In order to cache our dependencies and speed up our builds, we explicitly call `xcodebuild -resolvePackageDependencies -clonedSourcePackagesDirPath SourcePackages` as part of our CircleCI workflow and this directory gets cached based on the `Package.resolved` checksum.

We would then like to skip package resolution when we run `scan` to build our app by passing `disableAutomaticPackageResolution` however as there doesn't seem to be a way to pass this flag OR disable the hardcoded resolve step in Fastlane we are unable to do this.

Please add a configuration option for this.

This is a dupe of #16589 which was closed as stale.

**Comment by lukeredpath** [comment]
```
| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.7                                     |
| Ruby                        | 2.6.5                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.22.0                          |
| Installation Source         | ~/.rbenv/versions/2.6.5/bin/fastlane        |
| Host                        | Mac OS X 10.15.7 (19H2)                     |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.5/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.2                                        |
```

**Comment by joshdholtz** [comment]
@lukeredpath This is totally a thing that should be allowed 👍 It is not an option at the moment but we can totally get that added for you!

**Comment by AvdLee** [comment]
+1 for this one. I'm running into the same with our CI system on Bitrise.

**Comment by wvteijlingen** [comment]
I'd like to +1 this as well. [The documentation](https://developer.apple.com/documentation/swift_packages/building_swift_packages_or_apps_that_use_them_in_continuous_integration_workflows) states:

> If your CI pipeline uses the xcodebuild command directly, also pass the -disableAutomaticPackageResolution flag. This flag ensures that the CI pipeline always uses the package dependencies as defined in the Package.resolved file.

This sounds like `-disableAutomaticPackageResolution` is a necessary argument to force `xcodebuild` to use the resolved dependency versions.
