### ISSUE TITLE
Spaceship::Tunes::AppDetails.save! returning "Not Found"

### ISSUE THREAD

**Issue by knewman-chownow** [fastlane/fastlane#17626]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I have a very simple lane that I use when I need to update my app's name.
```
  lane :update_app_name do |options|
    ENV["FASTLANE_ITC_TEAM_NAME"] = options[:team_name]

    Spaceship::Tunes.login(options[:username], options[:password])
    Spaceship::Tunes.client.select_team
    app = Spaceship::Tunes::Application.find(options[:bundle_id])
    details = app.details
    details.name["en-US"] = options[:app_name]
    details.save!
```
Recently, the lane has been failing with the following error:
```
[!] The request could not be completed because:
	Not Found
```
Even if you remove the update to `details.name`, it will still throw the error:
```
app = Spaceship::Tunes::Application.find(options[:bundle_id])
details = app.details
details.save!
```
Is there a better way to update an app's name? The [github documentation](https://github.com/fastlane/fastlane/blob/master/spaceship/docs/AppStoreConnect.md) still indicates that `details.save!` is the correct method. I also saw [Spaceship::Portal::App.update_name!](https://rdoc.info/gems/fastlane/Spaceship/Portal/App#update_name!-instance_method) in the ruby docs, but as far as I can tell, this method does not appear to change anything on App Store Connect.

##### Command executed
> fastlane update_app_name username:"REDACTED" password:"REDACTED" team_name:"REDACTED" bundle_id:"REDACTED" app_name:"Test Updated Name"

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> fastlane update_app_name username:"REDACTED" password:"REDACTED" team_name:"REDACTED" bundle_id:"REDACTED" app_name:"Test Updated Name"
[✔] 🚀 
[16:35:28]: Seems like launching fastlane takes a while - please run
[16:35:28]: 
[16:35:28]: $ [sudo] gem cleanup
[16:35:28]: 
[16:35:28]: to uninstall outdated gems and make fastlane launch faster
[16:35:28]: Alternatively it's recommended to start using a Gemfile to lock your dependencies
[16:35:28]: To get started with a Gemfile, run
[16:35:28]: 
[16:35:28]: $ bundle init
[16:35:28]: $ echo 'gem "fastlane"' >> Gemfile
[16:35:28]: $ bundle install
[16:35:28]: 
[16:35:28]: After creating the Gemfile and Gemfile.lock, commit those files into version control
[16:35:28]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[16:35:35]: ----------------------------------------
[16:35:35]: --- Step: Verifying fastlane version ---
[16:35:35]: ----------------------------------------
[16:35:35]: Your fastlane version 2.162.0 matches the minimum requirement of 2.161.0  ✅
[16:35:35]: ------------------------------
[16:35:35]: --- Step: default_platform ---
[16:35:35]: ------------------------------
/Users/keith.newman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.162.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/keith.newman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.162.0/fastlane_core/lib/fastlane_core/ui/errors/fastlane_error.rb:9: warning: The called method `initialize' is defined here
[16:35:35]: Driving the lane 'ios update_app_name' 🚀
+------------------+---------------------+
|              Lane Context              |
+------------------+---------------------+
| DEFAULT_PLATFORM | ios                 |
| PLATFORM_NAME    | ios                 |
| LANE_NAME        | ios update_app_name |
+------------------+---------------------+
[16:35:39]: Not Found

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
+------+----------------------------+-------------+

[16:35:39]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  The request could not be completed because: Access forbidden
    https://github.com/fastlane/fastlane/issues/17479 [closed] 3 💬
    4 weeks ago

➡️  The request could not be completed because: 	Access forbidden
    https://github.com/fastlane/fastlane/issues/17141 [closed] 5 💬
    3 weeks ago

➡️  All devices provided to snapshot should run the same operating system
    https://github.com/fastlane/fastlane/issues/17578 [open] 2 💬
    a week ago

and 206 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09Not%20Found&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.

[!] The request could not be completed because:
	Not Found </pre>
</details>

### Environment
I'm currently using Fastlane 2.162. If this issue is fixed by a newer version, I can update to the latest, but I am working on a project where we would first like to see if we can get this fix working with our existing Fastlane version before resorting to an upgrade.
<details>
  <pre> ### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.15.7                                          |
| Ruby                        | 2.7.1                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.24.3 (Apple Git-128)               |
| Installation Source         | ~/.rbenv/versions/2.7.1/bin/fastlane             |
| Host                        | Mac OS X 10.15.7 (19H15)                         |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.1/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-11.6.app/Contents/Developer/ |
| Xcode Version               | 11.6                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.162.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.18.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.76.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-storage      | 1.29.0       |
| emoji_regex               | 3.0.0        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.376.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.108.0      |
| aws-sdk-kms               | 1.38.0       |
| aws-sdk-s3                | 1.81.1       |
| uri                       | 0.10.0       |
| forwardable               | 1.3.1        |
| logger                    | 1.4.2        |
| cgi                       | 0.1.0        |
| timeout                   | 0.1.0        |
| stringio                  | 0.1.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.2.0        |
| strscan                   | 1.0.3        |
| date                      | 3.0.0        |
| delegate                  | 0.1.0        |
| fileutils                 | 1.4.1        |
| io-console                | 0.5.6        |
| zlib                      | 1.1.0        |
| singleton                 | 0.1.0        |
| rexml                     | 3.2.3        |
| open3                     | 0.1.0        |
| yaml                      | 0.1.0        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.6.0        | </pre>
</details>

**Comment by max-ott** [comment]
Please update to the latest `fastlane` version and make sure to use the `ConnectAPI`. Apple killed all old endpoints with their App Store Connect update this summer. Using most `Tunes` endpoints is simply no longer working.

This should get you up to speed:

```
app = Spaceship::ConnectAPI.get_app(app_id: "123456789")
app_info = app.fetch_edit_app_info
app_info_en =  app_info.get_app_info_localizations(filter: {locale: "en-US"}).first
attributes = {}
attributes["name"] = "Test 123456789"
app_info_en.update(attributes: attributes)
```

**Comment by schunlee** [comment]
@max-ott I get the error => undefined method `fetch_edit_app_info' for #<Spaceship::ConnectAPI::Response:0x00007fa83c874a10> (NoMethodError)

**Comment by max-ott** [comment]
Which Fastlane version are you on?

**Comment by schunlee** [comment]
> Which Fastlane version are you on?

fastlane 2.168.0

**Comment by max-ott** [comment]
Are you sure the app has an edit version?

**Comment by rogerluan** [comment]
I personally update the app name using `deliver`'s `metadata_path` option, passing full metadata information.
