### ISSUE TITLE
fastlane deliver error

### ISSUE THREAD

**Issue by Echo-Joker** [fastlane/fastlane#17640]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Command executed
deliver 2.137.0
when i used fastlane deliver
i have get error message how can i fix it

##### Complete output when running fastlane, including the stack trace and command used
`parse_response': {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Not Found"], "info"=>nil}, "statusCode"=>"ERROR"} (Spaceship::UnexpectedResponse)

<details>
  <pre> 

Traceback (most recent call last):
	21: from /Users/joker/.rvm/rubies/ruby-2.6.0/bin/ruby_executable_hooks:24:in `<main>'
	20: from /Users/joker/.rvm/rubies/ruby-2.6.0/bin/ruby_executable_hooks:24:in `eval'
	19: from /Users/joker/.rvm/rubies/ruby-2.6.0/bin/fastlane:23:in `<main>'
	18: from /Users/joker/.rvm/rubies/ruby-2.6.0/bin/fastlane:23:in `load'
	17: from /Users/joker/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/bin/fastlane:23:in `<top (required)>'
	16: from /Users/joker/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	15: from /Users/joker/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
	14: from /Users/joker/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/deliver/lib/deliver/commands_generator.rb:182:in `run'
	13: from /Users/joker/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	12: from /Users/joker/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	11: from /Users/joker/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	10: from /Users/joker/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 9: from /Users/joker/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 8: from /Users/joker/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/deliver/lib/deliver/commands_generator.rb:79:in `block (2 levels) in run'
	 7: from /Users/joker/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/deliver/lib/deliver/runner.rb:37:in `run'
	 6: from /Users/joker/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/deliver/lib/deliver/runner.rb:92:in `verify_version'
	 5: from /Users/joker/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/spaceship/lib/spaceship/tunes/application.rb:245:in `ensure_version!'
	 4: from /Users/joker/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/spaceship/lib/spaceship/tunes/application.rb:130:in `edit_version'
	 3: from /Users/joker/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/spaceship/lib/spaceship/tunes/app_version.rb:291:in `find'
	 2: from /Users/joker/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/spaceship/lib/spaceship/tunes/tunes_client.rb:447:in `app_version'
	 1: from /Users/joker/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/spaceship/lib/spaceship/tunes/tunes_client.rb:456:in `app_version_data'
/Users/joker/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/fastlane-2.137.0/spaceship/lib/spaceship/client.rb:709:in `parse_response': {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Not Found"], "info"=>nil}, "statusCode"=>"ERROR"} (Spaceship::UnexpectedResponse)

 </pre>
</details>

### Environment

<details>
  <pre>

</pre>
</details>

**Comment by joshdholtz** [comment]
@Echo-Joker Hello! Can you try updating to `2.168.0`? There have been major API changes that happened around `2.150.0` that will fix this issue for you 😊

**Comment by julpanucci4** [comment]
@joshdholtz same issue happening here as well. Just updated to 2.1680 and still getting that same error on deliver

**Comment by markreynoso** [comment]
I'm seeing the same thing in relation to the Spaceship::Tunes::AppVersion. So far, all the version methods appear to fail with the error noted above. I am also on 2.168.0 experiencing this issue.

**Comment by James-Rodriquez** [comment]
I'm also facing the same, please help me to resolve this issue [tellpopeyes](https://www.tellpopeyes.me/).

**Comment by daniel-beard** [comment]
I see the same issue here, fails on `Spaceship::Tunes::Application.find()` for me though.

**Comment by Echo-Joker** [comment]
update is work for me
