### ISSUE TITLE
The version number has been previously used - provided entity error.

### ISSUE THREAD

**Issue by LemonSpike** [fastlane/fastlane#17649]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

The provided entity includes an attribute with a value that has already been used - The version number has been previously used.

This error came up when I tried to upload using deliver to the App Store. I have checked the version number and build numbers and they have not been used before. I later uploaded my archive in Xcode Organizer and it worked no hitches. ¯\_(ツ)_/¯

##### Command executed

ran `deliver` step of `send_appstore` lane with appropriate params (see environment). The app doesn't include an App Clip.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> The provided entity includes an attribute with a value that has already been used - The version number has been previously used. </pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.7                                     |
| Ruby                        | 2.7.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.rbenv/versions/2.7.1/bin/fastlane        |
| Host                        | Mac OS X 10.15.7 (19H15)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.1/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.2                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.9.0"
default_platform :ios
platform :ios do

  lane :send_appstore do |options|
    cocoapods

    #retrieve distribution certificate
    certificates(type: "appstore", identifier: options[:identifier], team: options[:team], new_devices: true, force: true)

    xcversion(version: "12.2")
    #increment app store build number
    increment_version_number(version_number: "x.x.x",
                             xcodeproj: "<proj_name>.xcodeproj")
    increment_build_number(build_number: "y",
                           xcodeproj: "<proj_name>.xcodeproj")
    #build app using the certificate
    gym(scheme: options[:scheme], export_method: 'app-store', output_directory: "build", buildlog_path: "./build/build_log")

    deliver(team_id: options[:team_id], skip_screenshots: true, skip_metadata: true)
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "<app_id>" # The bundle identifier of your app
apple_id "<my_email>" # Your Apple email address

team_id "<my_team_id>"
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.168.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.2.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.4.0        |
| slack-notifier                            | 2.3.2        |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.7.0        |
| terminal-table                            | 1.8.0        |
| plist                                     | 3.5.0        |
| CFPropertyList                            | 3.0.2        |
| public_suffix                             | 4.0.6        |
| addressable                               | 2.7.0        |
| multipart-post                            | 2.0.0        |
| word_wrap                                 | 1.0.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| colored                                   | 1.2          |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| unf_ext                                   | 0.0.7.7      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.0.0        |
| fastimage                                 | 2.2.0        |
| gh_inspector                              | 1.1.3        |
| rubyzip                                   | 2.3.0        |
| security                                  | 0.1.3        |
| xcpretty-travis-formatter                 | 1.0.0        |
| dotenv                                    | 2.7.6        |
| naturally                                 | 2.2.0        |
| simctl                                    | 1.6.8        |
| jwt                                       | 2.2.2        |
| uber                                      | 0.1.0        |
| declarative                               | 0.0.20       |
| declarative-option                        | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| mini_mime                                 | 1.0.2        |
| multi_json                                | 1.15.0       |
| signet                                    | 0.14.0       |
| httpclient                                | 2.8.3        |
| google-api-client                         | 0.38.0       |
| uri                                       | 0.10.0       |
| nanaimo                                   | 0.3.0        |
| colored2                                  | 3.1.2        |
| claide                                    | 1.0.3        |
| atomos                                    | 0.1.3        |
| xcodeproj                                 | 1.19.0       |
| babosa                                    | 1.0.4        |
| excon                                     | 0.78.0       |
| ruby2_keywords                            | 0.0.2        |
| faraday                                   | 1.1.0        |
| json                                      | 2.3.1        |
| mini_magick                               | 4.11.0       |
| bundler                                   | 2.1.4        |
| os                                        | 1.1.1        |
| memoist                                   | 0.16.2       |
| googleauth                                | 0.14.0       |
| rake                                      | 13.0.1       |
| digest-crc                                | 0.6.1        |
| google-cloud-errors                       | 1.0.1        |
| google-cloud-env                          | 1.4.0        |
| google-cloud-core                         | 1.5.0        |
| google-cloud-storage                      | 1.29.1       |
| emoji_regex                               | 3.2.1        |
| aws-eventstream                           | 1.1.0        |
| aws-sigv4                                 | 1.2.2        |
| aws-partitions                            | 1.397.0      |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.109.3      |
| aws-sdk-kms                               | 1.39.0       |
| aws-sdk-s3                                | 1.85.0       |
| forwardable                               | 1.3.1        |
| logger                                    | 1.4.2        |
| cgi                                       | 0.1.0        |
| timeout                                   | 0.1.0        |
| stringio                                  | 0.1.0        |
| ipaddr                                    | 1.2.2        |
| openssl                                   | 2.1.2        |
| ostruct                                   | 0.2.0        |
| strscan                                   | 1.0.3        |
| date                                      | 3.0.0        |
| delegate                                  | 0.1.0        |
| fileutils                                 | 1.4.1        |
| io-console                                | 0.5.6        |
| zlib                                      | 1.1.0        |
| singleton                                 | 0.1.0        |
| rexml                                     | 3.2.3        |
| open3                                     | 0.1.0        |
| yaml                                      | 0.1.0        |
| psych                                     | 3.1.0        |
| mutex_m                                   | 0.1.0        |
| webrick                                   | 1.6.0        |
| fastlane-plugin-firebase_app_distribution | 0.2.4        |
| pstore                                    | 0.1.0        |
</details>

*generated on:* **2020-11-20**
</details> </pre>
</details>

**Comment by max-ott** [comment]
Please include some more context in your issue, like all the commands you ran and the full stack trace.
