### ISSUE TITLE
fastlane deleted my default keychains

### ISSUE THREAD

**Issue by aprilmintacpineda** [fastlane/fastlane#17641]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I was trying out fastlane on my local machine, I am a completely new in using fastlane, this is my first time trying to use it, but for whatever reason, it delete my default keychains called "login" which totally messed up my machine. I'm not an expert here, but I'm pretty sure fastlane should not have done that, imagine the shit that newbies will go through when trying it out, right?

This is what my keychain looks like now:

![image](https://user-images.githubusercontent.com/21032419/99775871-f00ead00-2b4a-11eb-862e-07a45a156f47.png)

The code responsible for it is this:

```ruby
create_keychain(
  name: keychain_name,
  password: keychain_password,
  default_keychain: true,
  unlock: true,
  timeout: 3600,
  lock_when_sleeps: false
)
```

I was not able to recover the contents of the replaced keychain.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by joshdholtz** [comment]
@aprilmintacpineda So sorry to hear about your keychain 😔 I think the issue was setting `default_keychain: true`. It seems like this replaced you default `login` keychain with your new one that `create_keychain` replacement. I pretty positive that this _shouldn’t_ have deleted your keychain though. Were you able to go check in the file system that your login keychain was still there?

**Comment by aprilmintacpineda** [comment]
Yeah, I did saw something called "login-renamed", but it was empty, there's nothing in it, I was able to guess the password and reset my keychains, good thing I still have my old mac with me so I was able to recover my keychains from it. In a way, I got lucky.
