### ISSUE TITLE
fastlane ignores 'fail_build: false' in tests

### ISSUE THREAD

**Issue by Jaff** [fastlane/fastlane#17645]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

run_tests set to not fail the build, but build fails anyway.
##### Command executed

`bundle exec fastlane build_app`
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
(See attached file)
[proton_bug.log](https://github.com/fastlane/fastlane/files/5575337/proton_bug.log)

</pre>
</details>

### Environment

(included with log)

**Comment by Jaff** [comment]
I've run it on the Jenkins build-slave in the correct account, but the Jenkinsfile & Fastfile set additional parameters, so it may not be complete. I'll provide additional detail in follow-up.
[Fastlane_env.txt](https://github.com/fastlane/fastlane/files/5599106/Fastlane_env.txt)

**Comment by rogerluan** [comment]
Hey @Jaff 👋 

What kind of failure are you seeing? Compilation-time errors, or testing failures? 
It's documented (in the code only, not in the documentation, unfortunately) that this option will only skip test failures, not build ones:
>Specifically catching FastlaneBuildFailure to prevent build/compile errors from being
>silenced when :fail_build is set to false
>:fail_build should only suppress testing failures
