### ISSUE TITLE
Execution policy exception registration failed and was skipped: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (in target 'Demo' from project 'Demo')

### ISSUE THREAD

**Issue by tejaskdubal** [fastlane/fastlane#17663]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Mac OS - 10.15.7
Xcode - 11.7

Fastfile commands-
```
lane :release do
  get_certificates           # invokes cert
  get_provisioning_profile   # invokes sigh
  build_app(scheme: "Demo")
end
```

When I fire command fastlane release getting errors(please refer Complete output when running fastlane, including the stack trace and command used)

Error in log file-
Execution policy exception registration failed and was skipped: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (in target 'Demo' from project 'Demo')

##### Command executed
fastlane release

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [12:16:56]: ▸ ** ARCHIVE SUCCEEDED **
[12:16:56]: 
[12:16:56]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[12:16:56]: 📋  For the complete and more detailed error log, check the full log at:
[12:16:56]: 📋  /Users/root1/Library/Logs/gym/Demo-Demo.log
[12:16:56]: 
[12:16:56]: Looks like fastlane ran into a build/archive error with your project
[12:16:56]: It's hard to tell what's causing the error, so we wrote some guides on how
[12:16:56]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[12:16:56]: Before submitting an issue on GitHub, please follow the guide above and make
[12:16:56]: sure your project is set up correctly.
[12:16:56]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
[12:16:56]: the full commands printed out in yellow in the above log.
[12:16:56]: Make sure to inspect the output above, as usually you'll find more error information there
[12:16:56]: 
+---------------------+--------------------------------------+
|                        Lane Context                        |
+---------------------+--------------------------------------+
| DEFAULT_PLATFORM    | ios                                  |
| PLATFORM_NAME       | ios                                  |
| LANE_NAME           | ios release                          |
| CERT_FILE_PATH      | /Users/root1/Demo/demo/  |
|                     | demo/ABCDEF8AB7.cer            |
| CERT_CERTIFICATE_ID | HFMGLH8UW7                           |
| SIGH_PROFILE_PATH   | /Users/root1/T/Demo/  |
|                     | Demo/AppStore_com.demo.demo  |
|                     | .mobileprovision                    |
| SIGH_PROFILE_PATHS  | ["/Users/root1/T/Demo  |
|                     | /Demo/AppStore_com.demo.demo  |
|                     | .mobileprovision"]                |
| SIGH_UDID           | b3e446xs-66af-46b9-8b82-aff10b82f1f  |
|                     | 3                                    |
| SIGH_UUID           | b3e446xc-66af-46b9-8b82-aff10b82f1f  |
|                     | 3                                    |
| SIGH_NAME           | Demo Distribution Profile        |
|                     | 12-Aug-2020                          |
| SIGH_PROFILE_TYPE   | app-store                            |
+---------------------+--------------------------------------+
[12:16:56]: Error packaging up the application

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | default_platform       | 0           |
| 2    | get_certificates       | 329         |
| 3    | get_provisioning_prof  | 315         |
|      | ile                    |             |
| 💥   | build_app              | 707         |
+------+------------------------+-------------+

[12:16:56]: fastlane finished with errors

[!] Error packaging up the application </pre>
</details>

### Environment

<details>
  <pre> <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 10.15.7                                                 |
| Ruby                        | 2.7.2                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.24.3 (Apple Git-128)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.168.0/libexec/bin/fastlane |
| Host                        | Mac OS X 10.15.7 (19H2)                                 |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.7.2/lib                        |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                             |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 11.7                                                    |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end


	lane :release do
  get_certificates           # invokes cert
  get_provisioning_profile   # invokes sigh

  		build_app(scheme: "Demo")
	end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.demo.demo") # The bundle identifier of your app
apple_id("demo@gmail.com") # Your Apple email address

itc_team_id("12345678") # App Store Connect Team ID
team_id("XYZABC1234") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.168.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.4        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.78.0       |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.1.0        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| json                      | 2.3.0        |
| mini_magick               | 4.11.0       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.14.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.4.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-storage      | 1.29.1       |
| emoji_regex               | 3.2.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.396.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.109.3      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.84.1       |
| uri                       | 0.10.0       |
| forwardable               | 1.3.1        |
| logger                    | 1.4.2        |
| cgi                       | 0.1.0        |
| timeout                   | 0.1.0        |
| stringio                  | 0.1.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.2.0        |
| strscan                   | 1.0.3        |
| date                      | 3.0.0        |
| delegate                  | 0.1.0        |
| fileutils                 | 1.4.1        |
| io-console                | 0.5.6        |
| zlib                      | 1.1.0        |
| singleton                 | 0.1.0        |
| rexml                     | 3.2.3        |
| open3                     | 0.1.0        |
| yaml                      | 0.1.0        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.6.0        |
</details>

*generated on:* **2020-11-24**
</details> </pre>
</details>

**Comment by tejaskdubal** [comment]
Description Updated. @max-ott

**Comment by max-ott** [comment]
Did you check out https://github.com/fastlane/fastlane/issues/15964 ?
