### ISSUE TITLE
`upload_to_testflight` broken unless run with verbose

### ISSUE THREAD

**Issue by djbe** [fastlane/fastlane#17675]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Was setting up CI (Bitrise) for a new project, using the same structure and configuration used for other projects, but my build uploads kept failing for some weird transporter reason. This only happens on CI, which makes it hard to reproduce for me (had to run it each time on CI, and SSH access / environment is bonkers and broken).

I just happened to stumble on the fact that adding `--verbose` magically fixed my build upload to TestFlight.

#### Downgrading seemed to solve it

Digging a bit further, I first thought I found a regression:
- 2.166.0 and older just works
- 2.167.0 is broken without `--verbose`
- 2.168.0 is broken without `--verbose`

But after temporarily downgrading to 2.166, recent builds seem to be failing with the same issue... So no regression, just something weird going on. Tried going back as far as 2.163, didn't help.

Adding `--verbose` to any of those versions instantly fixes it.

##### Complete output when running fastlane, including the stack trace and command used

I tried using `fastlane ios development --capture_output` but that didn't seem to do much on CI (nothing at all), so here's the CI log of the broken upload:

<details>
<summary>Partial output from CI of a broken upload</summary>
<pre>
[02:03:54]: Successfully exported and compressed dSYM file
[02:03:54]: Successfully exported and signed the ipa file:
[02:03:54]: /Users/vagrant/git/fastlane/build/RemeCare Development.ipa
[02:03:54]: ----------------------------------
[02:03:54]: --- Step: upload_to_testflight ---
[02:03:54]: ----------------------------------
[02:03:54]: Ready to upload new build to TestFlight (App: )...
[02:03:54]: Fetching password for transporter from environment variable named `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`
[02:03:54]: Going to upload updated app to App Store Connect
[02:03:54]: This might take a few minutes. Please don't interrupt the script.
[02:04:11]: [Transporter Error Output]: ERROR ITMS-3000: "Line 3 column 51: value of attribute "apple_id" is invalid; must be an integer at XPath /package/software_assets"
[02:04:11]: [Transporter Error Output]: ERROR ITMS-3000: "Package "null" failed schema validation."
[02:04:11]: [Transporter Error Output]: The package name .itmsp contains an invalid character(s).  The valid characters are: A-Z, a-z, 0-9, dash, period, underscore, but the name cannot start with a dash, period, or underscore
[02:04:11]: Transporter transfer failed.
[02:04:11]: 
[02:04:11]: ERROR ITMS-3000: "Line 3 column 51: value of attribute "apple_id" is invalid; must be an integer at XPath /package/software_assets"
ERROR ITMS-3000: "Package "null" failed schema validation."
The package name .itmsp contains an invalid character(s).  The valid characters are: A-Z, a-z, 0-9, dash, period, underscore, but the name cannot start with a dash, period, or underscore
</pre>
</details>

Notice that the app "name" (or hash?) seems to be empty, and the `itmsp` file/package seems to have no name. Here's what I get for a successful upload with 2.166.0:

<details>
<summary>Partial output from CI of a successful upload</summary>
<pre>
[18:30:55]: Successfully exported and compressed dSYM file
[18:30:55]: Successfully exported and signed the ipa file:
[18:30:55]: /Users/vagrant/git/fastlane/build/RemeCare Development.ipa
[18:30:55]: ----------------------------------
[18:30:55]: --- Step: upload_to_testflight ---
[18:30:55]: ----------------------------------
[18:30:55]: Ready to upload new build to TestFlight (App: 1541566246)...
[18:30:56]: Fetching password for transporter from environment variable named `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`
[18:30:56]: Going to upload updated app to App Store Connect
[18:30:56]: This might take a few minutes. Please don't interrupt the script.
[18:32:12]: iTunes Transporter successfully finished its job
[18:32:12]: --------------------------------------------------------------------
[18:32:12]: Successfully uploaded package to App Store Connect. It might take a few minutes until it's visible online.
[18:32:12]: --------------------------------------------------------------------
</pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.7                                     |
| Ruby                        | 2.6.5                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.29.2                          |
| Installation Source         | ~/git/vendor/bundle/ruby/2.6.0/bin/fastlane |
| Host                        | Mac OS X 10.15.7 (19H2)                     |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.5/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.2                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version '2.137.0'
default_platform :ios

actions_path('./../Pods/AppwiseCore/Fastlane Actions')

platform :ios do
  desc 'Submit a new Development Build to Apple TestFlight'
  lane :development do
    scheme = CredentialsManager::AppfileConfig.try_fetch_value(:scheme)
    archiveAndUpload(scheme: scheme)
  end

  desc 'Submit a new Lab Build to Apple TestFlight'
  lane :lab do
    scheme = CredentialsManager::AppfileConfig.try_fetch_value(:scheme)
    archiveAndUpload(scheme: scheme)
  end

  desc 'Submit a new Local Build to Apple TestFlight'
  lane :local do
    scheme = CredentialsManager::AppfileConfig.try_fetch_value(:scheme)
    archiveAndUpload(scheme: scheme)
  end

  desc 'Submit a new Production Build to Apple TestFlight'
  lane :production do
    scheme = CredentialsManager::AppfileConfig.try_fetch_value(:scheme)
    archiveAndUpload(scheme: scheme)
  end

  desc 'Submit a new Staging Build to Apple TestFlight'
  lane :staging do
    scheme = CredentialsManager::AppfileConfig.try_fetch_value(:scheme)
    archiveAndUpload(scheme: scheme)
  end

  desc 'Submit a new Test Build to Apple TestFlight'
  lane :test do
    scheme = CredentialsManager::AppfileConfig.try_fetch_value(:scheme)
    archiveAndUpload(scheme: scheme)
  end

  desc 'Deploy a new version to the App Store'
  lane :release do
    version_number = get_version_number
    sentry_project = CredentialsManager::AppfileConfig.try_fetch_value(:sentry_project)

    upload_to_app_store(
      submit_for_review: true,
      skip_binary_upload: true,
      force: true
    )
    sentry_finalize_release(
      version: "#{sentry_project}@#{version_number}"
    )
  end

  desc 'Download dSYMs from iTC and upload them to Sentry'
  lane :refresh_dsyms do
    identifiers = CredentialsManager::AppfileConfig.try_fetch_value(:identifiers)

    identifiers.each do |identifier|
      syncDsyms(identifier: identifier)
    end
  end

  desc "Imports, and then extracts localizations from the xcode project"
  lane :sync_translations do
    sync_localizations()
  end

  private_lane :archiveAndUpload do |options|
    scheme = options[:scheme]
    version_number = get_version_number
    sentry_project = CredentialsManager::AppfileConfig.try_fetch_value(:sentry_project)

    get_provisioning_profile(
      output_path: 'fastlane/build'
    ) unless ENV.key?('CI')
    build_ios_app(
      scheme: scheme,
      include_bitcode: true,
      output_directory: 'fastlane/build',
      output_name: "#{scheme}.ipa",
      silent: true
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      itc_provider: '2PPBSYHSNC'
    )
    sentry_create_release(
      version: "#{sentry_project}@#{version_number}"
    )
    sentry_auto_set_commits(
      version: "#{sentry_project}@#{version_number}"
    )
  end

  private_lane :syncDsyms do |options|
    identifier = options[:identifier]

    download_dsyms(
      app_identifier: identifier,
      output_directory: 'fastlane/build'
    )
    sentry_upload_dsym
    clean_build_artifacts
    lane_context[SharedValues::DSYM_PATHS] = []
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id ENV['USER_APPLE_ID'] # Your Apple email address

team_name 'Remedus BVBA'
itc_team_name 'Remedus BVBA'
itc_provider '2PPBSYHSNC'

# Environment settings for Sentry
ENV['SENTRY_URL'] = 'https://sentry.appwi.se'
ENV['SENTRY_ORG_SLUG'] = 'appwise'
ENV['SENTRY_PROJECT_SLUG'] = 'remedus-ios'

# lane specific settings
for_platform :ios do
  app_identifier 'be.remedus.remecoachnew'
  setter(:scheme, 'RemeCare Production')
  setter(:sentry_project, ENV['SENTRY_PROJECT_SLUG'])

  setter(:identifiers, [
    'be.remedus.remecoachnew-Development',
    'be.remedus.remecoachnew-Local',
    'be.remedus.remecoachnew-Lab',
    'be.remedus.remecoachnew-Staging',
    'be.remedus.remecoachnew-Test',
    'be.remedus.remecoachnew'
  ])

  for_lane :development do
    app_identifier 'be.remedus.remecoachnew-Development'
    setter(:scheme, 'RemeCare Development')
  end

  for_lane :lab do
    app_identifier 'be.remedus.remecoachnew-Lab'
    setter(:scheme, 'RemeCare Lab')
  end

  for_lane :local do
    app_identifier 'be.remedus.remecoachnew-Local'
    setter(:scheme, 'RemeCare Local')
  end

  for_lane :staging do
    app_identifier 'be.remedus.remecoachnew-Staging'
    setter(:scheme, 'RemeCare Staging')
  end

  for_lane :test do
    app_identifier 'be.remedus.remecoachnew-Test'
    setter(:scheme, 'RemeCare Test')
  end
end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.167.0 | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                 | Version | Update-Status |
| ---------------------- | ------- | ------------- |
| fastlane-plugin-sentry | 1.7.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 2.1.4        |
| rake                      | 13.0.1       |
| CFPropertyList            | 3.0.2        |
| concurrent-ruby           | 1.1.7        |
| i18n                      | 1.8.5        |
| minitest                  | 5.14.2       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.8        |
| activesupport             | 5.2.4.4      |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| httpclient                | 2.8.3        |
| json                      | 2.3.1        |
| algoliasearch             | 1.27.5       |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.399.0      |
| aws-sigv4                 | 1.2.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.109.3      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.85.0       |
| babosa                    | 1.0.4        |
| claide                    | 1.0.3        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| netrc                     | 0.11.0       |
| ffi                       | 1.13.1       |
| ethon                     | 0.12.0       |
| typhoeus                  | 1.4.0        |
| cocoapods-core            | 1.10.0       |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.4.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-trunk           | 1.5.0        |
| cocoapods-try             | 1.2.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| cocoapods                 | 1.10.0       |
| cocoapods-rome            | 1.0.1        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.2.1        |
| excon                     | 0.78.0       |
| multipart-post            | 2.0.0        |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.1.0        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| jwt                       | 2.2.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| signet                    | 0.14.0       |
| googleauth                | 0.14.0       |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.4.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.1       |
| mini_magick               | 4.11.0       |
| plist                     | 3.5.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-sentry    | 1.7.0        |
</details>

*generated on:* **2020-11-25**
</details>

**Comment by max-ott** [comment]
Could you please try to update fastlane and try it again?

**Comment by djbe** [comment]
Updated to `2.171.0` and I think it's solved. Ran a few different lanes on CI without verbose, and they seem to be working again 🎉

**Comment by rogerluan** [comment]
Great news @djbe ! Thanks for checking and getting back to us. I'm closing this issue for now - if it becomes a problem again, let us know. 🤗
