### ISSUE TITLE
FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD not recognised when running 'upload_to_testflight' on CI (Github Actions)

### ISSUE THREAD

**Issue by MakakWasTaken** [fastlane/fastlane#17679]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I have lately been trying to set up upload_to_testflight with Github Actions. But it doesn't seem to recognise the FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD Environment variable when running, thus causing it to ask for 2FA code.

##### Command executed

`bundle exec fastlane github_test`

```
    upload_to_testflight(
      verbose: true,
      ipa: './build/xxx.ipa', 
      skip_waiting_for_build_processing: is_ci,
      username: ENV["FASTLANE_USER"],
      uses_non_exempt_encryption: true
    )
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
[13:53:11]: ----------------------------------
4045
[13:53:11]: --- Step: upload_to_testflight ---
4046
[13:53:11]: ----------------------------------
4047
[13:53:11]: Login to App Store Connect (***)
4048
Two-factor Authentication (6 digits code) is enabled for account '***'
4049
More information about Two-factor Authentication: https://support.apple.com/en-us/HT204915
4050

4051
If you're running this in a non-interactive session (e.g. server or CI)
4052
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification
4053

4054
/usr/local/lib/ruby/gems/2.7.0/gems/highline-1.7.10/lib/highline.rb:624: warning: Using the last argument as keyword parameters is deprecated
4055
Please enter the 6 digit code you received at +xx •• •• •• xx: 
bundler: failed to load command: fastlane (/usr/local/lib/ruby/gems/2.7.0/bin/fastlane)
4111
NoMethodError: [!] undefined method `strip' for nil:NilClass
4112
Did you mean?  String
4113
Did you mean?  String
4114
  /usr/local/lib/ruby/gems/2.7.0/gems/highline-1.7.10/lib/highline/question.rb:413:in `remove_whitespace'
4115
  /usr/local/lib/ruby/gems/2.7.0/gems/highline-1.7.10/lib/highline.rb:873:in `get_line'
4116
  /usr/local/lib/ruby/gems/2.7.0/gems/highline-1.7.10/lib/highline.rb:891:in `get_response'
4117
  /usr/local/lib/ruby/gems/2.7.0/gems/highline-1.7.10/lib/highline.rb:264:in `ask'
4118
  /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/forwardable.rb:235:in `ask'
4119
  /usr/local/lib/ruby/gems/2.7.0/bundler/gems/fastlane-2624a24407de/spaceship/lib/spaceship/two_step_or_factor_client.rb:225:in `ask_for_2fa_code'
4120
  /usr/local/lib/ruby/gems/2.7.0/bundler/gems/fastlane-2624a24407de/spaceship/lib/spaceship/two_step_or_factor_client.rb:308:in `request_two_factor_code_from_phone'
4121
  /usr/local/lib/ruby/gems/2.7.0/bundler/gems/fastlane-2624a24407de/spaceship/lib/spaceship/two_step_or_factor_client.rb:148:in `handle_two_factor'
4122
  /usr/local/lib/ruby/gems/2.7.0/bundler/gems/fastlane-2624a24407de/spaceship/lib/spaceship/two_step_or_factor_client.rb:20:in `handle_two_step_or_factor'
4123
  /usr/local/lib/ruby/gems/2.7.0/bundler/gems/fastlane-2624a24407de/spaceship/lib/spaceship/client.rb:499:in `send_shared_login_request'
4124
  /usr/local/lib/ruby/gems/2.7.0/bundler/gems/fastlane-2624a24407de/spaceship/lib/spaceship/tunes/tunes_client.rb:127:in `send_login_request'
4125
  /usr/local/lib/ruby/gems/2.7.0/bundler/gems/fastlane-2624a24407de/spaceship/lib/spaceship/client.rb:781:in `do_login'
4126
  /usr/local/lib/ruby/gems/2.7.0/bundler/gems/fastlane-2624a24407de/spaceship/lib/spaceship/client.rb:389:in `login'
4127
  /usr/local/lib/ruby/gems/2.7.0/bundler/gems/fastlane-2624a24407de/spaceship/lib/spaceship/client.rb:351:in `login'
4128
  /usr/local/lib/ruby/gems/2.7.0/bundler/gems/fastlane-2624a24407de/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
4129
  /usr/local/lib/ruby/gems/2.7.0/bundler/gems/fastlane-2624a24407de/spaceship/lib/spaceship/connect_api/client.rb:56:in `login'
4130
  /usr/local/lib/ruby/gems/2.7.0/bundler/gems/fastlane-2624a24407de/spaceship/lib/spaceship/connect_api/spaceship.rb:85:in `login'
4131
  /usr/local/lib/ruby/gems/2.7.0/bundler/gems/fastlane-2624a24407de/pilot/lib/pilot/manager.rb:27:in `login'
4132
  /usr/local/lib/ruby/gems/2.7.0/bundler/gems/fastlane-2624a24407de/pilot/lib/pilot/manager.rb:16:in `start'
4133
  /usr/local/lib/ruby/gems/2.7.0/bundler/gems/fastlane-2624a24407de/pilot/lib/pilot/build_manager.rb:17:in `upload'
4134
  /usr/local/lib/ruby/gems/2.7.0/bundler/gems/fastlane-2624a24407de/fastlane/lib/fastlane/actions/upload_to_testflight.rb:27:in `run'
4135
  /usr/local/lib/ruby/gems/2.7.0/bundler/gems/fastlane-2624a24407de/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
4136
  /usr/local/lib/ruby/gems/2.7.0/bundler/gems/fastlane-2624a24407de/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
4137
  /usr/local/lib/ruby/gems/2.7.0/bundler/gems/fastlane-2624a24407de/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
4138
  /usr/local/lib/ruby/gems/2.7.0/bundler/gems/fastlane-2624a24407de/fastlane/lib/fastlane/runner.rb:229:in `chdir'
4139
  /usr/local/lib/ruby/gems/2.7.0/bundler/gems/fastlane-2624a24407de/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
4140
  /usr/local/lib/ruby/gems/2.7.0/bundler/gems/fastlane-2624a24407de/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
4141
  /usr/local/lib/ruby/gems/2.7.0/bundler/gems/fastlane-2624a24407de/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
4142
  Fastfile:78:in `block (2 levels) in parsing_binding'
4143
  /usr/local/lib/ruby/gems/2.7.0/bundler/gems/fastlane-2624a24407de/fastlane/lib/fastlane/lane.rb:33:in `call'
4144
  /usr/local/lib/ruby/gems/2.7.0/bundler/gems/fastlane-2624a24407de/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
4145
  /usr/local/lib/ruby/gems/2.7.0/bundler/gems/fastlane-2624a24407de/fastlane/lib/fastlane/runner.rb:45:in `chdir'
4146
  /usr/local/lib/ruby/gems/2.7.0/bundler/gems/fastlane-2624a24407de/fastlane/lib/fastlane/runner.rb:45:in `execute'
4147
  /usr/local/lib/ruby/gems/2.7.0/bundler/gems/fastlane-2624a24407de/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
4148
  /usr/local/lib/ruby/gems/2.7.0/bundler/gems/fastlane-2624a24407de/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
4149
  /usr/local/lib/ruby/gems/2.7.0/bundler/gems/fastlane-2624a24407de/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
4150
  /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
4151
  /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
4152
  /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
4153
  /usr/local/lib/ruby/gems/2.7.0/bundler/gems/fastlane-2624a24407de/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
4154
  /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
4155
  /usr/local/lib/ruby/gems/2.7.0/bundler/gems/fastlane-2624a24407de/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
4156
  /usr/local/lib/ruby/gems/2.7.0/bundler/gems/fastlane-2624a24407de/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
4157
  /usr/local/lib/ruby/gems/2.7.0/bundler/gems/fastlane-2624a24407de/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
4158
  /usr/local/lib/ruby/gems/2.7.0/bundler/gems/fastlane-2624a24407de/bin/fastlane:23:in `<top (required)>'
4159
  /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `load'
4160
  /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `<top (required)>'
</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.0.1                                                         |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.29.1                                             |
| Installation Source         | ~/.gems/bin/fastlane                                           |
| Host                        | macOS 11.0.1 (20B29)                                           |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.2                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     |             |   |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

update_fastlane

default_platform(:ios)

platform :ios do

  lane :setup do
    setup_project
  end
  
  private_lane :setup_project do
    create_keychain(
      name: ENV["CI_KEYCHAIN_NAME"],
      password: ENV["CI_KEYCHAIN_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )
  end

  lane :github_test do
    increment_build_number
    match(
      type: "appstore",
      readonly: is_ci,
      git_basic_authorization: ENV["GIT_ACCESS"],
      keychain_name: ENV["CI_KEYCHAIN_NAME"],
      keychain_password: ENV["CI_KEYCHAIN_PASSWORD"]
    )
    
    update_project_provisioning(
      xcodeproj: "xxx.xcodeproj",
      profile: ENV["sigh_xxx_appstore_profile-path"],
      target_filter: "YourKitchen$", 
      build_configuration: "Release",
      code_signing_identity: "Apple Distribution: xxx (teamid)"
    )
    update_project_provisioning(
      xcodeproj: "xxx.xcodeproj",
      profile: ENV["sigh_xxx.YKWidget_appstore_profile-path"],
      target_filter: "YourKitchenWidgetExtension.*", 
      build_configuration: "Release",
      code_signing_identity: "Apple Distribution: xxx (teamid)"
    )
    update_project_provisioning(
      xcodeproj: "xxx.xcodeproj",
      profile: ENV["sigh_xxx.watchkitapp_appstore_profile-path"],
      target_filter: "WatchOS$", 
      build_configuration: "Release",
      code_signing_identity: "Apple Distribution: xxx (teamid)"
    )
    update_project_provisioning(
      xcodeproj: "xxx.xcodeproj",
      profile: ENV["sigh_xxx.watchkitapp.watchkitextension_appstore_profile-path"],
      target_filter: "WatchOS Extension.*", 
      build_configuration: "Release",
      code_signing_identity: "Apple Distribution: xxx (teamid)"
    )
    cocoapods
    build_app(
      scheme: "xxx",
      workspace: "xxx.xcworkspace",
    )
    upload_symbols_to_crashlytics(dsym_path: "./build/xxx.app.dSYM.zip")
    upload_to_testflight(
      verbose: true,
      ipa: './build/YourKitchen.ipa', 
      skip_waiting_for_build_processing: is_ci,
      username: ENV["FASTLANE_USER"],
      uses_non_exempt_encryption: true
    )
  end

  desc "Take screenshots of the app"
  lane :screenshot do
    snapshot
    frameit
  end

  desc "Deploy a test to testflight"
  lane :test do 
    increment_build_number

    sigh
    gym(
      silent: true,
      suppress_xcode_output: true
    )
    upload_symbols_to_crashlytics(dsym_path: "./build/xxxx.app.dSYM.zip")
    pilot(ipa: './build/xxx.ipa', skip_waiting_for_build_processing: true)
  end

  desc "Distribute version to Firebase"
  lane :distributeFirebase do
    increment_build_number
    if is_ci 
      create_keychain(
        name: ENV["CI_KEYCHAIN_NAME"],
        password: ENV["CI_KEYCHAIN_PASSWORD"],
        default_keychain: true,
        unlock: true,
        timeout: 3600,
        lock_when_sleeps: false
      )
    end
    match(
      app_identifier: "xxx",
      git_url: ENV["GIT_REPO_URL"],
      git_basic_authorization: ENV["GIT_ACCESS"],
      type: "appstore",
      username: ENV["FIREBASE_USER"],
      team_id: ENV["DEVELOPER_TEAM_ID"],
      keychain_name: ENV["CI_KEYCHAIN_NAME"],
      keychain_password: ENV["CI_KEYCHAIN_PASSWORD"],
      readonly: true
    )

    cert
    gym(
      export_method: 'ad-hoc',
      silent: true,
      suppress_xcode_output: true
    )
    firebase_app_distribution(
        app: "1:486079812811:ios:46ee85d01ebe6876ffb74e",
        release_notes: "Lots of amazing new features to test out!",
        groups: "Main"
    )
    upload_symbols_to_crashlytics(dsym_path: "./build/YourKitchen.app.dSYM.zip")
  end

  desc "Check for errors"
  lane :error do 
    swiftlint(quiet:true, mode: :autocorrect)
    swiftlint(quiet:true)
    scan(
      derived_data_path: "",
      workspace: "xxx.xcworkspace",
      devices: ["iPhone 8", "iPad (7th generation)"],
      scheme: "YourKitchen",
      test_without_building: true
    )
  end

  desc "Upload dSYM to Crashlytics"
  lane :uploadDSYM do
      upload_symbols_to_crashlytics(dsym_path: "./build/xxx.app.dSYM.zip")
  end

  desc "Create documentation"
  lane :documentation do 
    appledoc
  end

  desc "Deploy app to appstore (With screenshots, only run on mayor releases)"
  lane :deploy do
    increment_build_number
    if is_ci 
      create_keychain(
        name: ENV["CI_KEYCHAIN_NAME"],
        password: ENV["CI_KEYCHAIN_PASSWORD"],
        default_keychain: true,
        unlock: true,
        timeout: 3600,
        lock_when_sleeps: false
      )
    end
    match(
      app_identifier: "xxx",
      git_url: ENV["GIT_REPO_URL"],
      git_basic_authorization: ENV["GIT_ACCESS"],
      type: "appstore",
      username: ENV["FIREBASE_USER"],
      team_id: ENV["DEVELOPER_TEAM_ID"],
      keychain_name: ENV["CI_KEYCHAIN_NAME"],
      keychain_password: ENV["CI_KEYCHAIN_PASSWORD"],
      readonly: true
    )
    cert
    # Build for testing to speed up snapshots
    run_tests(
      build_for_testing: true,
      code_coverage: false,
      derived_data_path: "../../../Library/Developer/Xcode/DerivedData/xxx",
      scheme: "Snapshots",
      suppress_xcode_output: false,
    )
    snapshot(
      clear_previous_screenshots: true,
      skip_open_summary: true,
      test_without_building: true,
      derived_data_path: "../../../Library/Developer/Xcode/DerivedData/xxx",
      scheme: "Snapshots"
    )
    frameit
    gym(
      silent: true,
      suppress_xcode_output: true
    )
    upload_symbols_to_crashlytics(dsym_path: "./build/xxx.app.dSYM.zip")
    deliver(
      force: true,
      skip_metadata: true,
      overwrite_screenshots: true
    )
  end

  desc "Fast deploy (No screenshots)"
  lane :fastDeploy do
    increment_build_number
    sh(command: "rm -vfr ~/Library/Developer/Xcode/Archives/*")

    if is_ci 
      create_keychain(
        name: ENV["CI_KEYCHAIN_NAME"],
        password: ENV["CI_KEYCHAIN_PASSWORD"],
        default_keychain: true,
        unlock: true,
        timeout: 3600,
        lock_when_sleeps: false
      )
    end
    match(
      app_identifier: "xxx",
      git_url: ENV["GIT_REPO_URL"],
      git_basic_authorization: ENV["GIT_ACCESS"],
      type: "appstore",
      username: ENV["FIREBASE_USER"],
      team_id: ENV["DEVELOPER_TEAM_ID"],
      keychain_name: ENV["CI_KEYCHAIN_NAME"],
      keychain_password: ENV["CI_KEYCHAIN_PASSWORD"],
      readonly: true
    )

    cert
    gym(
      silent: true,
      suppress_xcode_output: true
    )

    upload_symbols_to_crashlytics(dsym_path: "./build/xxx.app.dSYM.zip")
    deliver(
      force: true,
      skip_metadata: true,
      skip_screenshots: true
    )
  end


  desc "Fast deploy (No screenshots)"
  lane :fastDeployTV do 
    sigh(platform: "tvos")
    gym(
      scheme: "xxxTV",
      silent: true,
      suppress_xcode_output: true
    )
    deliver(
      force: true,
      skip_metadata: true,
      skip_screenshots: true,
      platform: "appletvos"
    )
  end

  desc "Deploy (With Screenshots)"
  lane :deployTV do 
    sigh(platform: "tvos")
    snapshot(
      scheme: "SnapshotsTV",
      devices: ["Apple TV 4K"],
      clear_previous_screenshots: true,
      skip_open_summary: true
    )
    gym(
      scheme: "xTV",
      silent: true,
      suppress_xcode_output: true
    )
    deliver(
      force: true,
      skip_metadata: true,
      platform: "appletvos"
    )
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("xxx") # The bundle identifier of your app
apple_id("xxx") # Your Apple email address

itc_team_id("xxx") # App Store Connect Team ID
team_id(teamid) # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.168.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-load_json                 | 0.0.1   | ✅ Up-To-Date  |
| fastlane-plugin-firebase_app_distribution | 0.2.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.3.0        |
| bundler                                   | 2.1.4        |
| rake                                      | 13.0.1       |
| CFPropertyList                            | 3.0.2        |
| concurrent-ruby                           | 1.1.7        |
| i18n                                      | 1.8.5        |
| minitest                                  | 5.14.2       |
| thread_safe                               | 0.3.6        |
| tzinfo                                    | 1.2.8        |
| activesupport                             | 5.2.4.4      |
| public_suffix                             | 4.0.6        |
| addressable                               | 2.7.0        |
| httpclient                                | 2.8.3        |
| json                                      | 2.3.1        |
| algoliasearch                             | 1.27.5       |
| atomos                                    | 0.1.3        |
| aws-eventstream                           | 1.1.0        |
| aws-partitions                            | 1.399.0      |
| aws-sigv4                                 | 1.2.2        |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.109.3      |
| aws-sdk-kms                               | 1.39.0       |
| aws-sdk-s3                                | 1.85.0       |
| babosa                                    | 1.0.4        |
| claide                                    | 1.0.3        |
| fuzzy_match                               | 2.0.4        |
| nap                                       | 1.1.0        |
| netrc                                     | 0.11.0       |
| ffi                                       | 1.13.1       |
| ethon                                     | 0.12.0       |
| typhoeus                                  | 1.4.0        |
| cocoapods-core                            | 1.10.0       |
| cocoapods-deintegrate                     | 1.0.4        |
| cocoapods-downloader                      | 1.4.0        |
| cocoapods-plugins                         | 1.0.0        |
| cocoapods-search                          | 1.0.0        |
| cocoapods-trunk                           | 1.5.0        |
| cocoapods-try                             | 1.2.0        |
| colored2                                  | 3.1.2        |
| escape                                    | 0.0.4        |
| fourflusher                               | 2.3.1        |
| gh_inspector                              | 1.1.3        |
| molinillo                                 | 0.6.6        |
| ruby-macho                                | 1.4.0        |
| nanaimo                                   | 0.3.0        |
| xcodeproj                                 | 1.19.0       |
| cocoapods                                 | 1.10.0       |
| colored                                   | 1.2          |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| declarative                               | 0.0.20       |
| declarative-option                        | 0.1.0        |
| digest-crc                                | 0.6.1        |
| unf_ext                                   | 0.0.7.7      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| dotenv                                    | 2.7.6        |
| emoji_regex                               | 3.2.1        |
| excon                                     | 0.78.0       |
| multipart-post                            | 2.0.0        |
| ruby2_keywords                            | 0.0.2        |
| faraday                                   | 1.1.0        |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.0.0        |
| fastimage                                 | 2.2.0        |
| jwt                                       | 2.2.2        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.1        |
| signet                                    | 0.14.0       |
| googleauth                                | 0.14.0       |
| mini_mime                                 | 1.0.2        |
| uber                                      | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| google-api-client                         | 0.38.0       |
| google-cloud-env                          | 1.4.0        |
| google-cloud-errors                       | 1.0.1        |
| google-cloud-core                         | 1.5.0        |
| google-cloud-storage                      | 1.29.1       |
| mini_magick                               | 4.11.0       |
| plist                                     | 3.5.0        |
| rubyzip                                   | 2.3.0        |
| security                                  | 0.1.3        |
| naturally                                 | 2.2.0        |
| simctl                                    | 1.6.8        |
| slack-notifier                            | 2.3.2        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.7.0        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| word_wrap                                 | 1.0.0        |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.0        |
| fastlane-plugin-firebase_app_distribution | 0.2.4        |
| fastlane-plugin-load_json                 | 0.0.1        |
</details>

*generated on:* **2020-11-26**
</details>

**Comment by max-ott** [comment]
You're not having the `apple_id` set. Please check out https://docs.fastlane.tools/actions/upload_to_testflight/#use-an-application-specific-password-to-upload and try again.
