### ISSUE TITLE
Could not find action, lane or variable 'app_store_connect_api_key'

### ISSUE THREAD

**Issue by ginterpto** [fastlane/fastlane#17680]
### New Issue Checklist

- [v] Updated fastlane to the latest version
- [v] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [v] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [v] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Using unity cloud build, I added a post build lane to upload the binary to App Store connect. This works fine with a session and Apple ID, but fails to work with and app_store__connect_ api_key due to the error: Could not find action, lane or variable 'app_store_connect_api_key'.

##### Command executed
lane :beta do |options|
    app_store_connect_api_key(
        key_id: "**********",
        issuer_id: "1ff49d23-5a31-4d65-9cbe-ccf9f01f78ca",
        key_content: ENV['FASTLANE_APPSTORE_API_KEY'],
        duration: 28800,
        in_house: false
    )
    changelog_from_git_commits(commits_count: 3, merge_commit_filtering: "exclude_merges")
    upload_to_testflight(
        groups: ["Some Group"],
        notify_external_testers: true,
        uses_non_exempt_encryption: true
    )
end

##### Complete output when running fastlane, including the stack trace and command used
13433: -------------------------------------
13434: --- Step: Switch to ios beta lane ---
13435: -------------------------------------
13436: Cruising over to lane 'ios beta' 🚖
13437: +--------------------+--------------------------------------------------------------------------------------------------------+
13438: |                                                        Lane Context                                                         |
13439: +--------------------+--------------------------------------------------------------------------------------------------------+
13440: | DEFAULT_PLATFORM   | ios                                                                                                    |
13441: | PLATFORM_NAME      | ios                                                                                                    |
13442: | LANE_NAME          | ios build                                                                                              |
13443: | IPA_OUTPUT_PATH    | /BUILD_PATH/tyaari.movez.testflight-build/.build/last/testflight-build/build.ipa          |
13444: | XCODEBUILD_ARCHIVE | /BUILD_PATH/Library/Developer/Xcode/Archives/2020-11-26/build 2020-11-26 14.51.11.xcarchive        |
13445: | DSYM_OUTPUT_PATH   | /BUILD_PATH/tyaari.movez.testflight-build/.build/last/testflight-build/build.app.dSYM.zip |
13446: +--------------------+--------------------------------------------------------------------------------------------------------+
13447: Could not find action, lane or variable 'app_store_connect_api_key'. Check out the documentation for more details: https://docs.fastlane.tools/actions
13448: +------+---------------------------------------------------------------+-------------+
13449: |                                  fastlane summary                                  |
13450: +------+---------------------------------------------------------------+-------------+
13451: | Step | Action                                                        | Time (in s) |
13452: +------+---------------------------------------------------------------+-------------+
13453: | 1    | Verifying fastlane version                                    | 0           |
13454: | 2    | default_platform                                              | 0           |
13455: | 3    | set_info_plist_value                                          | 0           |
13456: | 4    | update_project_provisioning                                   | 0           |
13457: | 5    | sed -i '' '/PROVISIONING_PROFILE_SPECIFIER/d;/DEVELOPMENT_TEA | 0           |
13458: | 6    | gym                                                           | 1356        |
13459: | 7    | Switch to ios beta lane                                       | 0           |
13460: +------+---------------------------------------------------------------+-------------+
13461: fastlane finished with errors
13462: [!] Could not find action, lane or variable 'app_store_connect_api_key'. Check out the documentation for more details: https://docs.fastlane.tools/actions

fast lane version is 2.142.0

**Comment by max-ott** [comment]
Please upgrade to the latest fastlane version. You are on 2.142.0. Latest is somewhere at 2.168.0. Support for the ASC API Key was added definitely later.

**Comment by ginterpto** [comment]
Thank you very much for the reply. I have actually managed to figure that
out from your well documented change log. Should have remove the post,
sorry about that.

Best regards.

**Comment by c-andrews** [comment]
Hi @ginterpto, could you tell me if you resolved the issue? Is there a way to update Fastlane in CloudBuild as my version is 2.142.0?

**Comment by ginterpto** [comment]
I opened a ticket to the cloud build team and they responded by saying they will upgrade to the latest version. Hopefully it will happen quickly.

**Comment by c-andrews** [comment]
Lovely thanks for letting me know

**Comment by nabbestemmia** [comment]
I have the same error, my fastlane version is:
2.172.0

this is my lane:

`  lane :release do
    api_key = app_store_connect_api_key(
      key_id: "***",
      issuer_id: "***",
      key_filepath: "./AuthKey_***.p8"
    )
      pilot(
        api_key: api_key,
        app_identifier: '***',
        app_platform: 'ios',
        ipa: "~/***",
        skip_waiting_for_build_processing: true
    )
  end`
