### ISSUE TITLE
Sigh won't include M1 devices on the provisioning profile. (temp workaround: edit /sigh/runner.rb)

### ISSUE THREAD

**Issue by raphaelcruzeiro** [fastlane/fastlane#17690]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When running `sigh` to generate the provisioning profiles for an iOS app, `sigh` filters out the Mac devices on the developer portal. This means that M1 (Apple Silicon) machines are not included on the provisioning profiles. I was able to work around this by editing sigh and removing the code that filters the list of devices fetched from the portal.

##### Command executed

```
match(git_url: "<repo_url>",
      type: "development",
      app_identifier: [
          "<id1>",
          "<id2>"
      ]
)
```

##### Complete output when running fastlane, including the stack trace and command used

The command executes successfully.

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.0.1                                                         |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /Library/Ruby/Gems/2.6.0/bin/fastlane                          |
| Host                        | macOS 11.0.1 (20B29)                                           |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.2                                                           |

**Comment by rogerluan** [comment]
Hey @raphaelcruzeiro 👋 

Could you provide the changes you made to `sign/runner.rb` to help future readers? 😊

**Comment by raphaelcruzeiro** [comment]
Sure thing @rogerluan. I'm not much of a Ruby programmer so when changing the filter didn't work, so I just removed it (note the last *else*). This is what `sigh/runner.tb` looks like to me now:

```ruby
    def devices_to_use
      # Only use devices if development or adhoc
      return [] if !Sigh.config[:development] && !Sigh.config[:adhoc]

      device_classes = case Sigh.config[:platform].to_s
                       when 'ios'
                         [
                           Spaceship::ConnectAPI::Device::DeviceClass::APPLE_WATCH,
                           Spaceship::ConnectAPI::Device::DeviceClass::IPAD,
                           Spaceship::ConnectAPI::Device::DeviceClass::IPHONE,
                           Spaceship::ConnectAPI::Device::DeviceClass::IPOD,
                           Spaceship::ConnectAPI::Device::DeviceClass::MAC
                         ]
                       when 'tvos'
                         [Spaceship::ConnectAPI::Device::DeviceClass::APPLE_TV]
                       when 'macos', 'catalyst'
                         [Spaceship::ConnectAPI::Device::DeviceClass::MAC]
                       end
      if api_token
        return Spaceship::ConnectAPI::Device.all.select do |device|
          device_classes.include?(device.device_class)
        end
      else
        return Spaceship::ConnectAPI::Device.all()
      end
    end
```

**Comment by rogerluan** [comment]
Interesting @raphaelcruzeiro , so even after adding `Spaceship::ConnectAPI::Device::DeviceClass::MAC`, to the list of `device_classes` under 'ios' didn't work? 🤔 I'd expect that `deviceClass` would have more cases than fastlane knows, but fastlane is up-to-date with App Store Connect API specification:

```json
"deviceClass" : {
    "type" : "string",
    "enum" : [ "APPLE_WATCH", "IPAD", "IPHONE", "IPOD", "APPLE_TV", "MAC" ]
},
```

Not sure what else could be done to fix this issue

**Comment by halonsoluis** [comment]
This is just a big guess, but maybe Catalyst is missing in the enum depicting the deviceClass

**Comment by raphaelcruzeiro** [comment]
@rogerluan As you can see on my code above, it didn't. I am not really a Ruby developer so it's very much possible that I missed something obvious.

**Comment by Carlit0** [comment]
I think this is still an issue and is not yet ready to be closed!

@rogerluan yes, maybe Fastlane is up to date with the App Store Connect API specifications, however it does not comply with the current apple developer profile management! Let me explain:

When you want to build an iOS app on an Apple Silicon Mac (_Xcode Target:_ "**My Mac (Designed for iPad)**") you have to add the Mac specific _Provisioning-U**D**ID_ to the device list in the related provisioning profile. The selected platform must be **"macos"**, else the U**D**ID would be recognized as an iPod ^^.

Then in your Apple developer account under Profiles>_[chose the right **iOS** profile]_   you have to enable **"include Mac devices"**. 
<img width="750" alt="apple_dev_provisioning_screenshot" src="https://user-images.githubusercontent.com/12805599/113426255-80031400-93d3-11eb-9517-29080fef9df4.png">

...after updating your local profiles the Xcode build succeeds!

**BUT**: Fastlane **match** or **sigh** don't comply with this behavior. If I run fastlane match with `--force_for_new_devices` or `--force`. The iOS provisioning profile gets reset to **exclude Mac devices** and there is no option to avoid it.

@raphaelcruzeiro your provided workaround is simple but awesome if someone is in need that it works. However, I would prefer an additional _fastlane match parameter_ to comply with this option.

To make things clear:
While I was working on this issue, there were a number of misleading error messages and information: 
1) Apple asks for the device UUID. But in case of (_Xcode Target:_ "**My Mac (Designed for iPad)**") you have to provide the _Provisioning-U**D**ID_ of the device.
2) The platform of the device still is **"macos"** even though the provisioning profile is **"iOS"**.
3) Catalyst has nothing to do with it. It is still an iOS App, only. However, Apple Silicon can run iOS apps ^^

**Comment by raphaelcruzeiro** [comment]
Agreed, it would be awesome to have Fastlane support this out-of-the-box specially now since M1 devices are gonna get more and more common.
