### ISSUE TITLE
deliver content rights declaration server error 500 when using API key

### ISSUE THREAD

**Issue by markreynoso** [fastlane/fastlane#17715]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When submitting an app with Deliver using App Store Connect API Key, the content rights declaration consistently returns a 500 error. This does not happen when using username/password auth. Although I do not have an example posted below of the lack of failure on username/password, I have confirmed this through numerous (100's+) runs where the only difference has been API Key vs username/password. While this is particularly noteworthy when required for new apps, it appears to be an issue for all attempts to update the content rights declaration.

##### Command executed
<details>
  <pre>
deliver(
      ipa: "build/distribution/app_build.ipa",
      submit_for_review: true,
      skip_screenshots: true,
      screenshots_path: "fastlane/screenshots/",
      automatic_release: auto,
      force: true,
      precheck_include_in_app_purchases: false,
      submission_information: {
        content_rights_contains_third_party_content: false,
        add_id_info_serves_ads: false,
        add_id_info_uses_idfa: false
      }
      app_store_connect_api_key(
        key_id: ******,
        issuer_id: *********,
        key_content: ************,
        in_house: false
    )
)
</pre>
</details>

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
INFO [2020-12-02 19:31:17.54]: ---------------------
INFO [2020-12-02 19:31:17.54]: --- Step: deliver ---
INFO [2020-12-02 19:31:17.54]: ---------------------
INFO [2020-12-02 19:31:17.55]: Creating authorization token for App Store Connect API

+--------------------------------------------------------------------+--------------------------------+
|                                       deliver 2.169.0 Summary                                       |
+--------------------------------------------------------------------+--------------------------------+
| username                                                           | *************        |
| team_name                                                          | *****************     |
| ipa                                                                | build/distribution/app_build.ipa  |
| submit_for_review                                                  | true                           |
| skip_screenshots                                                   | true                           |
| screenshots_path                                                   | fastlane/screenshots/          |
| overwrite_screenshots                                              | false                          |
| automatic_release                                                  | true                           |
| force                                                              | true                           |
| precheck_include_in_app_purchases                                  | false                          |
| submission_information.content_rights_contains_third_party_content | false                          |
| submission_information.add_id_info_serves_ads                      | false                          |
| submission_information.add_id_info_uses_idfa                       | false                          |
| api_key                                                            | ********                       |
| app_identifier                                                     | ************************** |
| metadata_path                                                      | ./fastlane/metadata            |
| app_version                                                        | *****                          |
| platform                                                           | ios                            |
| edit_live                                                          | false                          |
| use_live_version                                                   | false                          |
| skip_binary_upload                                                 | false                          |
| skip_metadata                                                      | false                          |
| skip_app_version_update                                            | false                          |
| reject_if_possible                                                 | false                          |
| phased_release                                                     | false                          |
| reset_ratings                                                      | false                          |
| run_precheck_before_submit                                         | true                           |
| precheck_default_rule_level                                        | warn                           |
| ignore_language_directory_validation                               | false                          |
+--------------------------------------------------------------------+--------------------------------+
<br>
INFO [2020-12-02 19:40:25.11]: Successfully selected build
Timeout received! Retrying after 3 seconds (remaining: 5)...
Timeout received! Retrying after 3 seconds (remaining: 4)...
Timeout received! Retrying after 3 seconds (remaining: 3)...
Timeout received! Retrying after 3 seconds (remaining: 2)...
Timeout received! Retrying after 3 seconds (remaining: 1)...
DEBUG [2020-12-02 19:40:29.11]: Updating app store version for IDFA status of 'false'
DEBUG [2020-12-02 19:40:29.48]: Updated app store version for IDFA status of 'false'
INFO [2020-12-02 19:40:29.48]: Successfully updated IDFA declarations on App Store Connect
DEBUG [2020-12-02 19:40:29.48]: Updating contents rights declaration on App Store Connect
Timeout received! Retrying after 3 seconds (remaining: 5)...
Timeout received! Retrying after 3 seconds (remaining: 4)...
Timeout received! Retrying after 3 seconds (remaining: 3)...
Timeout received! Retrying after 3 seconds (remaining: 2)...
Timeout received! Retrying after 3 seconds (remaining: 1)...
WARN [2020-12-02 19:40:31.07]: Lane Context:
INFO [2020-12-02 19:40:31.07]: {*************}
ERROR [2020-12-02 19:40:31.08]: Server error got 500
INFO [2020-12-02 19:40:31.12]: Successfully generated documentation at path '/Users/runner/work/1/s/fastlane/README.md'
<br>
/usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.169.0/spaceship/lib/spaceship/connect_api/api_client.rb:185:in `handle_response': \e[31m[!] The request could not be completed because: (Spaceship::InternalServerError)
	Server error got 500\e[0m
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.169.0/spaceship/lib/spaceship/connect_api/api_client.rb:135:in `patch'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.169.0/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:200:in `patch_app'
	from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/forwardable.rb:235:in `patch_app'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.169.0/spaceship/lib/spaceship/connect_api/models/app.rb:106:in `update'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.169.0/deliver/lib/deliver/submit_for_review.rb:178:in `update_submission_information'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.169.0/deliver/lib/deliver/submit_for_review.rb:24:in `submit!'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.169.0/deliver/lib/deliver/runner.rb:194:in `submit_for_review'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.169.0/deliver/lib/deliver/runner.rb:64:in `run'
 </pre>
</details>

### Environment

<details>
  <pre> 

✅ fastlane environment ✅

### Stack
| Key                         | Value                                          |
| --------------------------- | ---------------------------------------------- |
| OS                          | 10.15.7                                        |
| Ruby                        | 2.7.2                                          |
| Bundler?                    | false                                          |
| Git                         | git version 2.29.2                             |
| Installation Source         | /usr/local/lib/ruby/gems/2.7.0/bin/fastlane    |
| Host                        | Mac OS X 10.15.7 (19H15)                       |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.7.2/lib               |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                    |
| Is contained                | false                                          |
| Is homebrew                 | false                                          |
| Is installed via Fabric.app | false                                          |
| Xcode Path                  | /Applications/Xcode_12.app/Contents/Developer/ |
| Xcode Version               | 12.0.1                                         |

### System Locale
| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |
### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.169.0 | ✅ Up-To-Date  |

 </pre>
</details>

**Comment by sonjz** [comment]
hmm strange, about 1-2hrs ago all my builds started to get 500s too on `bundle exec fastlane deliver`
2 hours eariler i had started building multiple white-label without issue (about 7), then all are failing with 500s (about 7 before i stopped it).
i'll keep an eye on this and try upgrade fastlane before commenting further..

**Comment by max-ott** [comment]
It's not possible to switch between ASC API key and Apple ID + password authentication and expect everything to work 100%.  Using the ASC API key, the "scope" of `fastlane` is limited to the official ASC API: https://developer.apple.com/documentation/appstoreconnectapi

Currently the official API does not support setting that parameter, therefore you get the `500` server error. Please use [Feedback Assistant](https://feedbackassistant.apple.com/) to report this issue to Apple.

@sonjz Also not very helpful. Please open a new issue with dedicated details/information. Can be unrelated or related, but hard to tell from generic replies.

**Comment by sonjz** [comment]
fyi: just an update.  my 500 server event disappeared on `bundle exec fastlane deliver` disappeared on its own this morning. chalking up to something on apple end.
