### ISSUE TITLE
gym/deliver crash on export. 'url should be an instance inheriting from NSURL, but it is nil'

### ISSUE THREAD

**Issue by ConfusedVorlon** [fastlane/fastlane#17714]
### Issue Description
My fastlane script to build and upload a macOS app stopped working (a month ago??)
the build seems to succeed, then it crashes on the export archive step

Please help!

```
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/ls/nyk7xgm14vb40_pcngzv11bw0000gn/T/gym_config20201202-90088-1cufop3.plist -archivePath '/Users/rob/Library/Developer/Xcode/Archives/2020-12-02/Multi Monitor Wallpaper 2020-12-02 18.06.58.xcarchive' -exportPath /var/folders/ls/nyk7xgm14vb40_pcngzv11bw0000gn/T/gym_output20201202-90088-vvw2om
2020-12-02 18:10:46.915 xcodebuild[93182:8910574] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/ls/nyk7xgm14vb40_pcngzv11bw0000gn/T/MultiMonitor_2020-12-02_18-10-46.913.xcdistributionlogs'.
2020-12-02 18:10:52.624 xcodebuild[93182:8910574] [MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-17518/DVTFoundation/FilePaths/DVTFilePath.m:912
Details:  url should be an instance inheriting from NSURL, but it is nil
Object:   <DVTFilePath>
Method:   +filePathForFileURL:
Thread:   <NSThread: 0x7fc041507000>{number = 1, name = main}
Hints: 

Backtrace:
  0   -[DVTAssertionHandler handleFailureInMethod:object:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in DVTFoundation)
  1   _DVTAssertionHandler (in DVTFoundation)
  2   _DVTAssertionFailureHandler (in DVTFoundation)
  3   +[DVTFilePath filePathForFileURL:] (in DVTFoundation)
  4   -[IDEDistributionSymbolsStep runWithError:] (in IDEFoundation)
  5   -[IDEDistributionProcessingPipeline process:] (in IDEFoundation)
  6   -[IDEDistributionPackagingStep loadFromExportOptions:error:] (in IDEFoundation)
  7   -[IDEDistributionDriver runWithDestinationPath:error:] (in IDEFoundation)
  8   -[Xcode3CommandLineBuildTool _distributeArchiveAndExit] (in Xcode3Core)
  9   -[Xcode3CommandLineBuildTool run] (in Xcode3Core)
 10   main (in xcodebuild)
 11   start (in libdyld.dylib)
/Users/rob/.rvm/gems/ruby-2.6.6/gems/fastlane-2.169.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh: line 61: 93182 Abort trap: 6           xcodebuild "$@"
[18:10:52]: Exit status: 134

```

##### Command executed

```
	desc "Push a new release build to the App Store"
	lane :release do
		increment
		build_app(scheme: "MultiMonitor")
		upload_to_app_store(
			app_identifier: "com.HobbyistSoftware.mmw",
			skip_metadata: false,
			skip_screenshots: true,
            skip_binary_upload: false,
			submit_for_review: false,
			automatic_release: true,
			run_precheck_before_submit: false,
			force:true,
			submission_information: {
				export_compliance_uses_encryption: false,
				add_id_info_uses_idfa: false
			}
			)
	end
```
with gymfile containing

`output_directory "~/tmp/FastlaneBuild"`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 

[18:10:45]: Successfully exported and compressed dSYM file
[18:10:45]: Successfully exported the .app file:
[18:10:45]: ~/tmp/FastlaneBuild/Multi Monitor Wallpaper.app
[18:10:45]: Generated plist file with the following values:
[18:10:45]: ▸ -----------------------------------------
[18:10:45]: ▸ {
[18:10:45]: ▸   "method": "app-store"
[18:10:45]: ▸ }
[18:10:45]: ▸ -----------------------------------------
[18:10:45]: $ /usr/bin/xcrun /Users/rob/.rvm/gems/ruby-2.6.6/gems/fastlane-2.169.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/ls/nyk7xgm14vb40_pcngzv11bw0000gn/T/gym_config20201202-90088-1cufop3.plist' -archivePath /Users/rob/Library/Developer/Xcode/Archives/2020-12-02/Multi\ Monitor\ Wallpaper\ 2020-12-02\ 18.06.58.xcarchive -exportPath '/var/folders/ls/nyk7xgm14vb40_pcngzv11bw0000gn/T/gym_output20201202-90088-vvw2om' 
RVM detected, forcing to use system ruby
Now using system ruby.
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/ls/nyk7xgm14vb40_pcngzv11bw0000gn/T/gym_config20201202-90088-1cufop3.plist -archivePath '/Users/rob/Library/Developer/Xcode/Archives/2020-12-02/Multi Monitor Wallpaper 2020-12-02 18.06.58.xcarchive' -exportPath /var/folders/ls/nyk7xgm14vb40_pcngzv11bw0000gn/T/gym_output20201202-90088-vvw2om
2020-12-02 18:10:46.915 xcodebuild[93182:8910574] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/ls/nyk7xgm14vb40_pcngzv11bw0000gn/T/MultiMonitor_2020-12-02_18-10-46.913.xcdistributionlogs'.
2020-12-02 18:10:52.624 xcodebuild[93182:8910574] [MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-17518/DVTFoundation/FilePaths/DVTFilePath.m:912
Details:  url should be an instance inheriting from NSURL, but it is nil
Object:   <DVTFilePath>
Method:   +filePathForFileURL:
Thread:   <NSThread: 0x7fc041507000>{number = 1, name = main}
Hints: 

Backtrace:
  0   -[DVTAssertionHandler handleFailureInMethod:object:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in DVTFoundation)
  1   _DVTAssertionHandler (in DVTFoundation)
  2   _DVTAssertionFailureHandler (in DVTFoundation)
  3   +[DVTFilePath filePathForFileURL:] (in DVTFoundation)
  4   -[IDEDistributionSymbolsStep runWithError:] (in IDEFoundation)
  5   -[IDEDistributionProcessingPipeline process:] (in IDEFoundation)
  6   -[IDEDistributionPackagingStep loadFromExportOptions:error:] (in IDEFoundation)
  7   -[IDEDistributionDriver runWithDestinationPath:error:] (in IDEFoundation)
  8   -[Xcode3CommandLineBuildTool _distributeArchiveAndExit] (in Xcode3Core)
  9   -[Xcode3CommandLineBuildTool run] (in Xcode3Core)
 10   main (in xcodebuild)
 11   start (in libdyld.dylib)
/Users/rob/.rvm/gems/ruby-2.6.6/gems/fastlane-2.169.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh: line 61: 93182 Abort trap: 6           xcodebuild "$@"
[18:10:52]: Exit status: 134

+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.169.0                 |
| export_method | app-store               |
| sdk           | MacOSX11.0.sdk          |
+---------------+-------------------------+

[18:10:52]: ▸ warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.6, but the range of supported deployment target versions is 10.9 to 11.0.99. (in target 'objectiveflickr' from project 'Pods')
[18:10:52]: ▸ warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.6, but the range of supported deployment target versions is 10.9 to 11.0.99. (in target 'nanopb' from project 'Pods')
[18:10:52]: ▸ warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.7, but the range of supported deployment target versions is 10.9 to 11.0.99. (in target 'PureLayout' from project 'Pods')
[18:10:52]: ▸ warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.7, but the range of supported deployment target versions is 10.9 to 11.0.99. (in target 'MD5Digest' from project 'Pods')
[18:10:52]: ▸ ** ARCHIVE SUCCEEDED **
[18:10:52]: 
[18:10:52]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[18:10:52]: 📋  For the complete and more detailed error log, check the full log at:
[18:10:52]: 📋  /Users/rob/Library/Logs/gym/Multi Monitor Wallpaper-MultiMonitor.log
[18:10:52]: 
[18:10:52]: Looks like fastlane ran into a build/archive error with your project
[18:10:52]: It's hard to tell what's causing the error, so we wrote some guides on how
[18:10:52]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[18:10:52]: Before submitting an issue on GitHub, please follow the guide above and make
[18:10:52]: sure your project is set up correctly.
[18:10:52]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
[18:10:52]: the full commands printed out in yellow in the above log.
[18:10:52]: Make sure to inspect the output above, as usually you'll find more error information there
[18:10:52]: 
[18:10:52]: Looks like no provisioning profile mapping was provided
[18:10:52]: Please check the complete output, in particular the very top
[18:10:52]: and see if you can find more information. You can also run fastlane
[18:10:52]: with the `--verbose` flag.
[18:10:52]: Alternatively you can provide the provisioning profile mapping manually
[18:10:52]: https://docs.fastlane.tools/codesigning/xcode-project/#xcode-9-and-up
+------------------+-------------+
|          Lane Context          |
+------------------+-------------+
| DEFAULT_PLATFORM | mac         |
| PLATFORM_NAME    | mac         |
| LANE_NAME        | mac release |
| BUILD_NUMBER     | 111         |
+------------------+-------------+
[18:10:52]: Error packaging up the application

+------+------------------------------+-------------+
|                 fastlane summary                  |
+------+------------------------------+-------------+
| Step | Action                       | Time (in s) |
+------+------------------------------+-------------+
| 1    | default_platform             | 0           |
| 2    | Switch to mac increment lane | 0           |
| 3    | increment_build_number       | 6           |
| 💥   | build_app                    | 246         |
+------+------------------------------+-------------+

[18:10:52]: fastlane finished with errors

[!] Error packaging up the application
 </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.0.1                                      |
| Ruby                        | 2.6.6                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.28.0                          |
| Installation Source         | ~/.rvm/gems/ruby-2.6.6/bin/fastlane         |
| Host                        | macOS 11.0.1 (20B50)                        |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.6/lib                |
| OpenSSL Version             | OpenSSL 1.1.1f  31 Mar 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.2                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)

platform :mac do

	desc "Increment build number"
	lane :increment do
		increment_build_number(
  			xcodeproj: "./MultiMonitor/MultiMonitor.xcodeproj" # (optional, you must specify the path to your main Xcode project if it is not in the project root directory)
  			)
	end

	desc "Update all fastlane tools"
	lane :update do
		update_fastlane
	end
 


	desc "Push a new release build to the App Store"
	lane :release do
		increment
		build_app(scheme: "MultiMonitor")
		upload_to_app_store(
			app_identifier: "com.HobbyistSoftware.mmw",
			skip_metadata: false,
			skip_screenshots: true,
            skip_binary_upload: false,
			submit_for_review: false,
			automatic_release: true,
			run_precheck_before_submit: false,
			force:true,
			submission_information: {
				export_compliance_uses_encryption: false,
				add_id_info_uses_idfa: false
			}
			)
	end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.HobbyistSoftware.mmw") # The bundle identifier of your app
apple_id("hobbyist@hobbyistsoftware.com") # Your Apple email address

itc_team_id("18645") # App Store Connect Team ID
team_id("JHV5RC82C3") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.169.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| CFPropertyList            | 3.0.2        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 1.0.1        |
| faraday_middleware        | 1.0.0        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| uber                      | 0.1.0        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| nanaimo                   | 0.3.0        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.19.0       |
| unicode-display_width     | 1.7.0        |
| public_suffix             | 4.0.6        |
| tty-screen                | 0.8.1        |
| excon                     | 0.76.0       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| fastimage                 | 2.2.0        |
| json                      | 2.3.1        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.4        |
| jwt                       | 2.2.2        |
| declarative               | 0.0.20       |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| os                        | 1.1.1        |
| memoist                   | 0.16.2       |
| googleauth                | 0.14.0       |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-env          | 1.3.3        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.0       |
| emoji_regex               | 3.0.0        |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-partitions            | 1.381.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.109.1      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.83.0       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.10      |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-12-02**
</details>

**Comment by ConfusedVorlon** [comment]
update: Xcode is now doing this when I submit manually, so not a fastlane issue.
Any suggestions very welcome nonetheless.

**Comment by ConfusedVorlon** [comment]
If anyone comes to this. The issue for me was that I was including an old-style quicklook plugin in the build.
Switching to a preview extension fixed the packaging step.

**Comment by gregcotten** [comment]
lol, "switching to a preview extension"

**Comment by gregcotten** [comment]
OK, actual workaround is not uploading debug symbols to the App Store, but that's really a terrible no-good solution.
