### ISSUE TITLE
Old iOS build artifacts interfere with macOS build submission

### ISSUE THREAD

**Issue by puls** [fastlane/fastlane#17710]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

A week ago I submitted version 1.28 of my app to the iOS and macOS app stores. Just now I tried to submit version 1.29, starting with the macOS version. The lane is pretty simple:

```ruby
    match(type: 'appstore', app_identifier: ['reverse.bundle.identifier'], team_id: 'TEAM_ID')
    build_mac_app(scheme: 'App Name', build_path: 'build/', configuration: 'App Store')
    upload_to_app_store(skip_screenshots: true, skip_metadata: true, app_identifier: 'reverse.bundle.identifier')
```

The app built correctly, outputting `App.pkg`, but then we got to the upload step. Since I didn't provide a version argument, Deliver goes to [`find_version`](https://github.com/fastlane/fastlane/blob/48151291f2c4949c3b1b9919ba2cc81a7cc33293/deliver/lib/deliver/detect_values.rb#L67) to get it. Problem is, last week's iOS build `App.ipa` is still sitting in the working directory, so Deliver gets last week's version number and tries to set the new App Store version to 1.28, which fails.

After banging my head against the desk for ten minutes or so, I deleted the old `App.ipa`—and everything else that was hanging around—and ran the script again, this time successfully.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
[22:48:34]: Making sure the latest version on App Store Connect matches '1.28.0'...
[22:48:35]: The provided entity includes an attribute with a value that has already been used - The version number has been previously used.
</pre>
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.169.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-sentry    | 1.7.0   | ✅ Up-To-Date  |
| fastlane-plugin-semaphore | 0.2.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 1.17.2       |
| etc                       | 1.0.1        |
| forwardable               | 1.2.0        |
| rake                      | 13.0.1       |
| CFPropertyList            | 3.0.2        |
| concurrent-ruby           | 1.1.6        |
| i18n                      | 1.8.2        |
| minitest                  | 5.14.1       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.7        |
| zeitwerk                  | 2.3.0        |
| activesupport             | 6.0.3.1      |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.402.0      |
| aws-sigv4                 | 1.2.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.109.3      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.86.0       |
| babosa                    | 1.0.4        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.2.1        |
| excon                     | 0.78.0       |
| multipart-post            | 2.0.0        |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.1.0        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.2.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| signet                    | 0.14.0       |
| googleauth                | 0.14.0       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.4.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.1       |
| json                      | 2.3.1        |
| mini_magick               | 4.11.0       |
| plist                     | 3.5.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-semaphore | 0.2.0        |
| fastlane-plugin-sentry    | 1.7.0        |
| graphql                   | 1.10.10      |
| graphql-client            | 0.16.0       |
| rexml                     | 3.2.4        |
| kramdown                  | 2.2.1        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.9       |
| xcode-install             | 2.6.4        |
</details>

**Comment by max-ott** [comment]
I guess this is the expected behaviour as fastlane was primarily made for iOS and Mac support "patched" later on. I think you can avoid this, by specifically setting the `pkg`(Path to your pkg file) parameter: https://docs.fastlane.tools/actions/upload_to_app_store/#parameters
