### ISSUE TITLE
Ability to modify isOptedInToDistributeIosAppOnMacAppStore is no longer working

### ISSUE THREAD

**Issue by ISDr** [fastlane/fastlane#17720]
### New Issue Checklist

- [ x] Updated fastlane to the latest version
- [ x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Ability to modify isOptedInToDistributeIosAppOnMacAppStore is no longer working. It was working 2 weeks ago, but not now with same code.
https://github.com/fastlane/fastlane/issues/16868

##### Command executed

Code: 
            app_from_connect_api = Spaceship::ConnectAPI::App.find("#{app.bundle_id}")
            UI.message "GOT app from connect API, setting is_opted_in_to_distribute_ios_app_on_mac_app_store: false"
            puts app_from_connect_api.is_opted_in_to_distribute_ios_app_on_mac_app_store  #gives null response
            puts app_from_connect_api.name
            puts app_from_connect_api.bundle_id
            app_from_connect_api.update(attributes: {
              is_opted_in_to_distribute_ios_app_on_mac_app_store: false
            })

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> Error: The provided entity includes an unknown attribute - 'isOptedInToDistributeIosAppOnMacAppStore' is not an attribute on the resource 'apps' 

</pre>
</details>

### Environment

<details>
  <pre> [ruby-2.4.5/gems/fastlane-2.169.0/spaceship/lib/spaceship/connect_api/api_client.rb:193:in `handle_response': [!] The provided entity includes an unknown attribute - 'isOptedInToDistributeIosAppOnMacAppStore' is not an attribute on the resource 'apps' (Spaceship::UnexpectedResponse)
	from /Users/isdr/.rvm/gems/ruby-2.4.5/gems/fastlane-2.169.0/spaceship/lib/spaceship/connect_api/api_client.rb:135:in `patch'
	from /Users/isdr/.rvm/gems/ruby-2.4.5/gems/fastlane-2.169.0/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:200:in `patch_app'
	from /Users/isdr/.rvm/gems/ruby-2.4.5/gems/fastlane-2.169.0/spaceship/lib/spaceship/connect_api/models/app.rb:106:in `update'
	from Fastfile:700:in `block (3 levels) in parsing_binding'
	from Fastfile:691:in `collect'
	from Fastfile:691:in `block (2 levels) in parsing_binding'
	from Fastfile:683:in `each'
	from Fastfile:683:in `block in parsing_binding'
	from /Users/isdr/.rvm/gems/ruby-2.4.5/gems/fastlane-2.169.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/isdr/.rvm/gems/ruby-2.4.5/gems/fastlane-2.169.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/isdr/.rvm/gems/ruby-2.4.5/gems/fastlane-2.169.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/isdr/.rvm/gems/ruby-2.4.5/gems/fastlane-2.169.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/isdr/.rvm/gems/ruby-2.4.5/gems/fastlane-2.169.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/isdr/.rvm/gems/ruby-2.4.5/gems/fastlane-2.169.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/isdr/.rvm/gems/ruby-2.4.5/gems/fastlane-2.169.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/isdr/.rvm/gems/ruby-2.4.5/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/isdr/.rvm/gems/ruby-2.4.5/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/isdr/.rvm/gems/ruby-2.4.5/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/isdr/.rvm/gems/ruby-2.4.5/gems/fastlane-2.169.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/isdr/.rvm/gems/ruby-2.4.5/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/isdr/.rvm/gems/ruby-2.4.5/gems/fastlane-2.169.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	from /Users/isdr/.rvm/gems/ruby-2.4.5/gems/fastlane-2.169.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/isdr/.rvm/gems/ruby-2.4.5/gems/fastlane-2.169.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Users/isdr/.rvm/gems/ruby-2.4.5/gems/fastlane-2.169.0/bin/fastlane:23:in `<top (required)>'
	from /Users/isdr/.rvm/gems/ruby-2.4.5/bin/fastlane:23:in `load'
	from /Users/isdr/.rvm/gems/ruby-2.4.5/bin/fastlane:23:in `<main>'
	from /Users/isdr/.rvm/gems/ruby-2.4.5/bin/ruby_executable_hooks:24:in `eval'
	from /Users/isdr/.rvm/gems/ruby-2.4.5/bin/ruby_executable_hooks:24:in `<main>'</pre>
</details>

**Comment by emilieez** [comment]
Having the same problem, it was working for me just a few days ago. The code hasn't changed.

**Comment by JimHowell20** [comment]
Yup, i've been getting the exact same error too

**Comment by mohsinahd** [comment]
Any update on this? can we turn off availability of the app on Mac Store (Apple Silicon) some how from fastlane?

**Comment by nbaryshev** [comment]
The same here:
 #<Spaceship::UnexpectedResponse: The provided entity includes an unknown attribute - 'isOptedInToDistributeIosAppOnMacAppStore' is not an attribute on the resource 'apps'>

**Comment by nbaryshev** [comment]
Hi,
Do we have any updates on this?

**Comment by ISDr** [comment]
An update would be appreciated

**Comment by rogerluan** [comment]
It seems that Apple silently dropped support to this attribute 🧐 I also couldn't find any similar API to perform the same action 😞

**Comment by ISDr** [comment]
:'(

**Comment by christruong90** [comment]
Hi, I am having the same issue and was wondering if there have been any updates. Thanks.
