### ISSUE TITLE
Deliver fails with error 500 on price tire update phase

### ISSUE THREAD

**Issue by pbeast** [fastlane/fastlane#17736]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Deliver failing with the message "Server error got 500".
I've isolated the issue to the price tire and territories update phase. 

##### Command executed
The code below is the test lane I used to reproduce the issue:
<pre>
def authenticateConnectAPI()
	token = Spaceship::ConnectAPI::Token.create(
		key_id: '####',
		issuer_id: '####',
		filepath:  File.absolute_path("./AuthKey/AuthKey_#####.p8")
	)

	Spaceship::ConnectAPI.token = token
end

lane :test do |options|    
	UI.header("In Test...")

	options[:bundle] = productBundleIdentifier(options[:scheme]) unless !options[:bundle].nil?

	authenticateConnectAPI()
	app = Spaceship::ConnectAPI::App.find(options[:bundle])
	if app.nil?
		UI.message("Application not found.")
		return
	else
		UI.message ("Found Application: #{app.name}")
	end

	attributes = {}
	territory_ids = []

	price_tier = "0" 

	app_prices = app.prices
	if app_prices.first
		app_price = Spaceship::ConnectAPI.get_app_price(app_price_id: app_prices.first.id, includes: "priceTier").first
		old_price = app_price.price_tier.id
	else
		UI.message("App has no prices yet... Enabling all countries in App Store Connect")
		territory_ids = Spaceship::ConnectAPI::Territory.all.map(&:id)
		attributes[:availableInNewTerritories] = true
	end

	if price_tier == old_price
		UI.success("Price Tier unchanged (tier #{old_price})")
		return
	end

	app.update(attributes: attributes, app_price_tier_id: price_tier, territory_ids: territory_ids)
	UI.success("Successfully updated the pricing from #{old_price} to #{price_tier}")
end
</pre>

The request `def patch(url_or_path, body)` function inside of `app.update(attributes: attributes, app_price_tier_id: price_tier, territory_ids: territory_ids)` fails with `{"errors"=>[{"status"=>"500", "code"=>"UNEXPECTED_ERROR", "title"=>"An unexpected error occurred.", "detail"=>"An unexpected error occurred on the server side. If this issue continues, contact us at https://developer.apple.com/contact/."}]}` as response. 

### Execution log ###
<pre>
[✔] 🚀
DEBUG [2020-12-04 13:41:45.52]: Checking if there are any plugins that should be loaded...
DEBUG [2020-12-04 13:41:46.74]: Using scheme: ####
INFO [2020-12-04 13:41:47.70]: gem 'spaceship' is already installed
INFO [2020-12-04 13:41:49.14]: gem 'deliver' is already installed
INFO [2020-12-04 13:41:49.71]: gem 'deliver/app_screenshot' is already installed
INFO [2020-12-04 13:41:50.05]: gem 'fileutils' is already installed
INFO [2020-12-04 13:41:50.05]: gem 'json' is already installed
INFO [2020-12-04 13:41:50.40]: gem 'openssl' is already installed
INFO [2020-12-04 13:41:50.41]: gem 'terminal-table' is already installed
INFO [2020-12-04 13:41:50.41]: gem 'xcodeproj' is already installed
INFO [2020-12-04 13:41:50.41]: gem 'chunky_png' is already installed
INFO [2020-12-04 13:41:50.77]: gem 'date' is already installed
INFO [2020-12-04 13:41:50.77]: gem 'tty-spinner' is already installed
INFO [2020-12-04 13:41:50.77]: gem 'tty-progressbar' is already installed
INFO [2020-12-04 13:41:50.79]: gem 'pprof' is already installed
INFO [2020-12-04 13:41:50.80]: gem 'pastel' is already installed
INFO [2020-12-04 13:41:51.14]: gem 'tmpdir' is already installed
INFO [2020-12-04 13:41:51.44]: gem 'date' is already installed
INFO [2020-12-04 13:41:51.82]: gem 'zip' is already installed
INFO [2020-12-04 13:41:51.82]: gem 'mailgun-ruby' is already installed
INFO [2020-12-04 13:41:52.49]: gem 'net/sftp' is already installed
INFO [2020-12-04 13:41:52.89]: gem 'open-uri' is already installed
INFO [2020-12-04 13:41:52.99]: Driving the lane 'test' 🚀
INFO [2020-12-04 13:41:52.99]: {:scheme=>"####"}
INFO [2020-12-04 13:41:52.99]: ---------------------------------------
INFO [2020-12-04 13:41:52.99]: --- Step: app_store_connect_api_key ---
INFO [2020-12-04 13:41:52.99]: ---------------------------------------
WARN [2020-12-04 13:41:52.99]: AppStore Connect API key was successfully loaded
INFO [2020-12-04 13:41:53.16]: ------------------
INFO [2020-12-04 13:41:53.16]: --- In Test... ---
INFO [2020-12-04 13:41:53.16]: ------------------
INFO [2020-12-04 13:41:54.22]: Found bundle identifier: ####
INFO [2020-12-04 13:41:57.25]: Found Application: ####
INFO [2020-12-04 13:41:57.25]: App has no prices yet... Enabling all countries in App Store Connect
{"errors"=>[{"status"=>"500", "code"=>"UNEXPECTED_ERROR", "title"=>"An unexpected error occurred.", "detail"=>"An unexpected error occurred on the server side. If this issue continues, contact us at https://developer.apple.com/contact/."}]}
Timeout received! Retrying after 3 seconds (remaining: 5)...
{"errors"=>[{"status"=>"500", "code"=>"UNEXPECTED_ERROR", "title"=>"An unexpected error occurred.", "detail"=>"An unexpected error occurred on the server side. If this issue continues, contact us at https://developer.apple.com/contact/."}]}
Timeout received! Retrying after 3 seconds (remaining: 4)...
{"errors"=>[{"status"=>"500", "code"=>"UNEXPECTED_ERROR", "title"=>"An unexpected error occurred.", "detail"=>"An unexpected error occurred on the server side. If this issue continues, contact us at https://developer.apple.com/contact/."}]}
Timeout received! Retrying after 3 seconds (remaining: 3)...
{"errors"=>[{"status"=>"500", "code"=>"UNEXPECTED_ERROR", "title"=>"An unexpected error occurred.", "detail"=>"An unexpected error occurred on the server side. If this issue continues, contact us at https://developer.apple.com/contact/."}]}
Timeout received! Retrying after 3 seconds (remaining: 2)...
{"errors"=>[{"status"=>"500", "code"=>"UNEXPECTED_ERROR", "title"=>"An unexpected error occurred.", "detail"=>"An unexpected error occurred on the server side. If this issue continues, contact us at https://developer.apple.com/contact/."}]}
Timeout received! Retrying after 3 seconds (remaining: 1)...
INFO [2020-12-04 13:42:09.14]: -----------------------------------
INFO [2020-12-04 13:42:09.14]: --- Step: clean_build_artifacts ---
INFO [2020-12-04 13:42:09.14]: -----------------------------------
INFO [2020-12-04 13:42:09.14]: Cleaned up build artifacts 🐙
INFO [2020-12-04 13:42:09.14]:

+--------+-----------------------+
|       Calculated Options       |
+--------+-----------------------+
| Option | Value                 |
+--------+-----------------------+
| scheme | ####                  |
| bundle | ####                  |
+--------+-----------------------+

INFO [2020-12-04 13:42:09.14]:

+-------------------------+-----------------------+
|                   Actions Log                   |
+-------------------------+-----------------------+
| Action                  | Result                |
+-------------------------+-----------------------+
| Found bundle identifier | ####                  |
+-------------------------+-----------------------+
WARN [2020-12-04 13:42:09.14]: Lane Context:
INFO [2020-12-04 13:42:09.14]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"test", "noreports"=>true, "####_PRODUCT_BUNDLE_IDENTIFIER"=>"####", :SIGH_PROFILE_PATHS=>nil, :DSYM_PATHS=>nil, :DSYM_LATEST_UPLOADED_DATE=>nil}
ERROR [2020-12-04 13:42:09.14]: Server error got 500
INFO [2020-12-04 13:42:09.14]: Successfully generated documentation at path '####/fastlane/README.md'

+------+---------------------------+-------------+
|                fastlane summary                |
+------+---------------------------+-------------+
| Step | Action                    | Time (in s) |
+------+---------------------------+-------------+
| 1    | app_store_connect_api_key | 0           |
| 2    | is_ci                     | 0           |
| 3    | clean_build_artifacts     | 0           |
+------+---------------------------+-------------+

ERROR [2020-12-04 13:42:09.15]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: The request could not be completed because:
	Server error got 500

URL: https://api.github.com/search/issues?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09Server%20error%20got%20500+repo:fastlane/fastlane
➡️  beta_pa path is relative to the fastlane directory, not the project directory
    https://github.com/fastlane/fastlane/issues/500 [closed] 4 💬
    22 Sep 2016

➡️  deliver content rights declaration server error 500 when using API key
    https://github.com/fastlane/fastlane/issues/17715 [closed] 4 💬
    a day ago

➡️  Getting Server error got 500 while downloading and uploading of screenshots
    https://github.com/fastlane/fastlane/issues/17139 [closed] 10 💬
    17 Oct 2020

and 21 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09Server%20error%20got%20500&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (####/vendor/ruby/2.6.0/bin/fastlane)
Spaceship::InternalServerError: [!] The request could not be completed because:
	Server error got 500
  ####/vendor/ruby/2.6.0/gems/fastlane-2.169.0/spaceship/lib/spaceship/connect_api/api_client.rb:192:in `handle_response'
  ####/vendor/ruby/2.6.0/gems/fastlane-2.169.0/spaceship/lib/spaceship/connect_api/api_client.rb:141:in `patch'
  ####/vendor/ruby/2.6.0/gems/fastlane-2.169.0/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:200:in `patch_app'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `patch_app'
  ####/vendor/ruby/2.6.0/gems/fastlane-2.169.0/spaceship/lib/spaceship/connect_api/models/app.rb:106:in `update'
  PrivateLanes:654:in `block in parsing_binding'
  ####/vendor/ruby/2.6.0/gems/fastlane-2.169.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  ####/vendor/ruby/2.6.0/gems/fastlane-2.169.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  ####/vendor/ruby/2.6.0/gems/fastlane-2.169.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  ####/vendor/ruby/2.6.0/gems/fastlane-2.169.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  ####/vendor/ruby/2.6.0/gems/fastlane-2.169.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  ####/vendor/ruby/2.6.0/gems/fastlane-2.169.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  ####/vendor/ruby/2.6.0/gems/fastlane-2.169.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  ####/vendor/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  ####/vendor/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  ####/vendor/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  ####/vendor/ruby/2.6.0/gems/fastlane-2.169.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  ####/vendor/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  ####/vendor/ruby/2.6.0/gems/fastlane-2.169.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  ####/vendor/ruby/2.6.0/gems/fastlane-2.169.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  ####/vendor/ruby/2.6.0/gems/fastlane-2.169.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  ####/vendor/ruby/2.6.0/gems/fastlane-2.169.0/bin/fastlane:23:in `<top (required)>'
  ####/vendor/ruby/2.6.0/bin/fastlane:23:in `load'
  ####/vendor/ruby/2.6.0/bin/fastlane:23:in `<top (required)>'

</pre>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.7                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | ####/vendor/ruby/2.6.0/bin/fastlane          |
| Host                        | Mac OS X 10.15.7 (19H15)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.2                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.169.0 | ✅ Up-To-Date  |
| match    | 1.0.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 2.1.4        |
| rake                      | 13.0.1       |
| CFPropertyList            | 3.0.2        |
| concurrent-ruby           | 1.1.7        |
| i18n                      | 1.8.5        |
| minitest                  | 5.14.2       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.8        |
| activesupport             | 5.2.4.4      |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| httpclient                | 2.8.3        |
| json                      | 2.3.1        |
| algoliasearch             | 1.27.5       |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.401.0      |
| aws-sigv4                 | 1.2.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.109.3      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.86.0       |
| babosa                    | 1.0.4        |
| bcrypt_pbkdf              | 1.0.1        |
| chunky_png                | 1.3.14       |
| claide                    | 1.0.3        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| netrc                     | 0.11.0       |
| ffi                       | 1.13.1       |
| ethon                     | 0.12.0       |
| typhoeus                  | 1.4.0        |
| cocoapods-core            | 1.10.0       |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.4.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-trunk           | 1.5.0        |
| cocoapods-try             | 1.2.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| cocoapods                 | 1.10.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| cocoapods-binary          | 0.4.4        |
| coderay                   | 1.1.3        |
| colored                   | 1.2          |
| colorize                  | 0.8.1        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| connection_pool           | 2.2.3        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.6        |
| ed25519                   | 1.2.4        |
| emoji_regex               | 3.2.1        |
| excon                     | 0.78.0       |
| multipart-post            | 2.0.0        |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.1.0        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| jwt                       | 2.2.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| signet                    | 0.14.0       |
| googleauth                | 0.14.0       |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.4.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.1       |
| mini_magick               | 4.11.0       |
| plist                     | 3.5.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| xcpretty-travis-formatter | 1.0.0        |
| http-accept               | 1.7.0        |
| ios-deploy                | 1.5.0        |
| launchy                   | 2.5.0        |
| mime-types-data           | 3.2020.1104  |
| mime-types                | 3.3.1        |
| rest-client               | 2.1.0        |
| mailgun-ruby              | 1.1.10       |
| net-http-digest_auth      | 1.4.1        |
| net-http-persistent       | 4.0.0        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.10      |
| ntlm-http                 | 0.1.1        |
| webrobots                 | 0.1.2        |
| mechanize                 | 2.7.6        |
| method_source             | 1.0.0        |
| net-ssh                   | 6.1.0        |
| net-sftp                  | 3.0.0        |
| tty-color                 | 0.6.0        |
| pastel                    | 0.8.0        |
| pprof                     | 0.3.9        |
| pry                       | 0.13.1       |
| strings-ansi              | 0.1.0        |
| tty-progressbar           | 0.17.0       |
| xcode-install             | 2.6.7        |
</details>

*generated on:* **2020-12-04**
</details>

**Comment by hnk-atheer** [comment]
https://developer.apple.com/app-store-connect/api/ was under maintenance,
It works for me now.
https://developer.apple.com/system-status/

**Comment by pbeast** [comment]
> https://developer.apple.com/app-store-connect/api/ was under maintenance,
> It works for me now.
> https://developer.apple.com/system-status/

Still the same :-( 
Also, the issue isn't new - I'm experiencing that for a couple of weeks already.

**Comment by colin-peter** [comment]
Hi, this has been stopping my uploads as well. It indeed has to do with the price tier.  There's some sort of change in the AppStore Connect. Setting the price in App Store Connect allows the uploads to proceed.

**Comment by rogerluan** [comment]
Http 500 means an issue on the server side (in our case, Apple's end). So it's a bug on their end there's probably not much we can do within _fastlane_ 😬 

Have you researched for similar issues in Apple official forums?

**Comment by pbeast** [comment]
It looks like produce still can't work AppStore Connect API key. I switched back to username/password and that solved the problem

**Comment by anh1979** [comment]
maybe same cause as in #17886?

**Comment by calinraducalin** [comment]
I'm experiencing this issue for a new app where there is no price that has been set yet. It started after switching to using app store connect key.

**Comment by EvgeniyGT** [comment]
@calinraducalin we have the same problem. 
Not selected price (new app) + ASC API usage.
