### ISSUE TITLE
Scan: Can't test Swift Package Manager packages using scheme only

### ISSUE THREAD

**Issue by AvdLee** [fastlane/fastlane#17734]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
As described here: https://github.com/apple/swift-package-manager/blob/main/Documentation/Usage.md#depending-on-apple-modules you can test packages easily by just running `xcodebuild` using `-scheme PACKAGE_NAME`. However, running Scan without a project or workspace automatically fails.

##### Command executed
Scan using a `scheme` only.

##### Complete output when running fastlane, including the stack trace and command used
There's not really much to tell, other than this is what you'll get:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/8419048/102044150-fe03c680-3db4-11eb-868e-2fd088352dbd.png">

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment
This is the case with any Fastlane version, I'm pretty sure the environment doesn't impact this.

# Expected behavior
I would love to see Scan accepting a certain `package_testing` property to skip scheme settings. I've tried looking into contributing myself but there are a lot of features dependent on having a project reference.

I feel like this impacts quite some structural changes to make this work. However, it will add support for Package testing within Fastlane, which would be very welcome.

**Comment by AvdLee** [comment]
I guess it would already help if we could pass in a `package_path`:

```ruby
scan(scheme: options[:package_name],
         package_path: options[:package_path])
```  

Instead of the `project_path` which requires things like a `.xcodeproj` extension.

If the `xcodebuild` command executes with the scheme only option inside the `package_path` folder, testing SPM packages would be simplified by a lot. 

We can't use `swift package generate-xcodeproj` first which is deprecated and does not support packages with resources. Therefore, I think this feature is needed to continue support for testing packages with `Scan`.

**Comment by AvdLee** [comment]
@joshdholtz any updates on this?

**Comment by jakob-fiegerl** [comment]
same issue here

**Comment by Panajev** [comment]
Hello @joshdholtz  sorry for the bump, but is this something on the roadmap? Sorry, not trying to rush anyone, just genuinely curious :).

**Comment by joshdholtz** [comment]
Got a PR up for this! I need to add tests yet but this _should_ hopefully work for all of you 😊 There are instructions in the PR description on how to pull down the branch to test.

**Comment by joshdholtz** [comment]
@AvdLee @Panajev Have either of you been able to test this out to make sure its working they way you'd expect? 😇

**Comment by AvdLee** [comment]
@joshdholtz working on it today!

**Comment by AvdLee** [comment]
Just tested it and it works great! 
To see the impact for us, we've opened this PR already showing how we can now reuse logic from testing regular projects 🚀 
https://github.com/WeTransfer/WeTransfer-iOS-CI/pull/72
