### ISSUE TITLE
fastlane gym bulid fail  

### ISSUE THREAD

**Issue by colondeethpark** [fastlane/fastlane#17731]
### New Issue Checklist

- [ v] Updated fastlane to the latest version
- [v ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ v] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ v] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I am using ml kit.
But after doing ml kit update this time
Fastlane bulid fail occurs

ml kit This ML Kit does not support 32-bit architectures (i386 and armv7). ML Kit does support 64-bit architectures (x86_64 and arm64).

Was changed to.

so
❌ Undefined symbols for architecture armv7
> Symbol: _OBJC_CLASS_$_MLKFaceDetector
> Referenced from: objc-class-ref in MyCertificationViewController.o

❌ ld: symbol(s) not found for architecture armv7

❌ clang: error: linker command failed with exit code 1 (use -v to see invocation)

I get this error
How can I fix it?

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by max-ott** [comment]
Please include all the required information (env etc.) and re-open an issue following the template.
