### ISSUE TITLE
upload_app_privacy_details_to_app_store not working

### ISSUE THREAD

**Issue by anh1979** [fastlane/fastlane#17749]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I try to use the CLI command as given in the documentation (I am using 2.170.0), but I cannot get it to work.
I login with a user that is in several development teams.
If I provide a teamName (itc_team_name I suppose), it tells me it cannot find the app with that bundleId in my account.

1. I tried the questions route with an bundleId and without teamName - it generated the JSON File, but crashed during upload - it takes really long to display the error message
2. I tried just the upload with the before generated file for the same app and it also crashes with the same message
3. I tried passing over all parameters to CLI, using a bundleId of an app in a linked, second development team the same user has admin access to, and it says: 
[!] Could not find app with bundle identifier 'com.appdinx.xxxxxxxxxx' on account myaccount@domain.de

##### Command executed
upload_app_privacy_details_to_app_store

##### Complete output when running fastlane, including the stack trace and command used
[19:34:48]: Preparing to upload App Data Usage
[19:34:49]: Setting EMAIL_ADDRESS and APP_FUNCTIONALITY to DATA_LINKED_TO_YOU

Looking for related GitHub issues on fastlane/fastlane...

➡️  undefined method `get_app_info_localizations' for nil
    https://github.com/fastlane/fastlane/issues/17208 [open] 13 💬
    2 days ago

➡️  set_changelog failing to update and ends in error: handle_response': [!] undefined method `status' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/17071 [open] 5 💬
    2 weeks ago

➡️  Fastlane match development -> undefined method `com' for nil:NilClass\e[0m (NoMethodError)
    https://github.com/fastlane/fastlane/issues/17320 [open] 5 💬
    4 weeks ago

and 286 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60status%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	31: from /Users/administrator/.rbenv/versions/2.6.3/bin/fastlane:23:in `<main>'
	30: from /Users/administrator/.rbenv/versions/2.6.3/bin/fastlane:23:in `load'
	29: from /Users/administrator/.gems/gems/fastlane-2.170.0/bin/fastlane:23:in `<top (required)>'
	28: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	27: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	26: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	25: from /Users/administrator/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	24: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	23: from /Users/administrator/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	22: from /Users/administrator/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	21: from /Users/administrator/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	20: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/commands_generator.rb:224:in `block (2 levels) in run'
	19: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/one_off.rb:22:in `execute'
	18: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/one_off.rb:42:in `run'
	17: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	16: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	15: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	14: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	13: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	12: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/upload_app_privacy_details_to_app_store.rb:43:in `run'
	11: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/upload_app_privacy_details_to_app_store.rb:138:in `upload_app_data_usages'
	10: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/upload_app_privacy_details_to_app_store.rb:138:in `each'
	 9: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/upload_app_privacy_details_to_app_store.rb:149:in `block in upload_app_data_usages'
	 8: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/upload_app_privacy_details_to_app_store.rb:149:in `each'
	 7: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/upload_app_privacy_details_to_app_store.rb:150:in `block (2 levels) in upload_app_data_usages'
	 6: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/upload_app_privacy_details_to_app_store.rb:150:in `each'
	 5: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/upload_app_privacy_details_to_app_store.rb:157:in `block (3 levels) in upload_app_data_usages'
	 4: from /Users/administrator/.gems/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/models/app_data_usage.rb:45:in `create'
	 3: from /Users/administrator/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `post_app_data_usage'
	 2: from /Users/administrator/.gems/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:258:in `post_app_data_usage'
	 1: from /Users/administrator/.gems/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/api_client.rb:124:in `post'
/Users/administrator/.gems/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/api_client.rb:181:in `handle_response': undefined method `status' for nil:NilClass (NoMethodError)
	31: from /Users/administrator/.rbenv/versions/2.6.3/bin/fastlane:23:in `<main>'
	30: from /Users/administrator/.rbenv/versions/2.6.3/bin/fastlane:23:in `load'
	29: from /Users/administrator/.gems/gems/fastlane-2.170.0/bin/fastlane:23:in `<top (required)>'
	28: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	27: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	26: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	25: from /Users/administrator/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	24: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	23: from /Users/administrator/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	22: from /Users/administrator/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	21: from /Users/administrator/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	20: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/commands_generator.rb:224:in `block (2 levels) in run'
	19: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/one_off.rb:22:in `execute'
	18: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/one_off.rb:42:in `run'
	17: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	16: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	15: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	14: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	13: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	12: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/upload_app_privacy_details_to_app_store.rb:43:in `run'
	11: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/upload_app_privacy_details_to_app_store.rb:138:in `upload_app_data_usages'
	10: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/upload_app_privacy_details_to_app_store.rb:138:in `each'
	 9: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/upload_app_privacy_details_to_app_store.rb:149:in `block in upload_app_data_usages'
	 8: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/upload_app_privacy_details_to_app_store.rb:149:in `each'
	 7: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/upload_app_privacy_details_to_app_store.rb:150:in `block (2 levels) in upload_app_data_usages'
	 6: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/upload_app_privacy_details_to_app_store.rb:150:in `each'
	 5: from /Users/administrator/.gems/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/upload_app_privacy_details_to_app_store.rb:157:in `block (3 levels) in upload_app_data_usages'
	 4: from /Users/administrator/.gems/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/models/app_data_usage.rb:45:in `create'
	 3: from /Users/administrator/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `post_app_data_usage'
	 2: from /Users/administrator/.gems/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:258:in `post_app_data_usage'
	 1: from /Users/administrator/.gems/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/api_client.rb:124:in `post'
/Users/administrator/.gems/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/api_client.rb:181:in `handle_response': [!] undefined method `status' for nil:NilClass (NoMethodError)

Please help.

**Comment by anh1979** [comment]
Okay, it seems as if there was something wrong with the user role setting - in one account that user was only an app manager, not admin.
Could you perhaps improve the output to display an understandable message in this case - it took me hours to investigate.

I just have to try if it works out with passing a teamName, though - I will report back.

**Comment by anh1979** [comment]
I still have the problem that the CLI says:
[!] Could not find app with bundle identifier 'com.apxxxx.otxxxxxx' on account myaccount@domain.de

when I pass in "team_name" for accessing an app, that is in another account.
I am using the same value (itc_team_name) I am using for example when I check the app status in AppStoreConnect with spaceship means.

If I have to use another value as team_name, please let me know where to find that value.

Thanks for your support.

**Comment by max-ott** [comment]
Can you please try to use the `team_id`?  (http://docs.fastlane.tools/actions/upload_app_privacy_details_to_app_store/#upload_app_privacy_details_to_app_store)

**Comment by anh1979** [comment]
Thank you - this is working great when using the itc_team_id for parameter "team_id"!
Very pleased
