### ISSUE TITLE
FastlaneCore::UI.command does not cooperate with commander-fastlane

### ISSUE THREAD

**Issue by cristi-lupu** [fastlane/fastlane#17751]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I am developing a Ruby gem which uses `fastlane` as a dependency, and the `commander-fastlane` (which is a transitive dependency from `fastlane`) as a command-line argument parsing library.

I noticed that `FastlaneCore::UI.command` method doesn't do his job. It is not printing anything. After a little debugging I noticed that the next line, which Ruby is evaluating after `FastlaneCore::UI.command`, is the `command` method from `commander-fastlane`.

After `require 'commander/import'`, the `command` method will be defined https://github.com/fastlane/commander/blob/master/lib/commander/delegates.rb#L5.

I also developed a gem for reproducing this issue https://github.com/cristi-lupu/commander-fastlane-issue. Please take a look.

1. I try to call `FastlaneCore::UI.command`.
![first](https://user-images.githubusercontent.com/41613812/101407982-5c780300-38e4-11eb-98d4-8135cc999ea6.png)
2. Then it goes to the defined method `command` from `commander-fastlane`.
![second](https://user-images.githubusercontent.com/41613812/101408075-8a5d4780-38e4-11eb-9617-0e8e021b389c.png)

##### Command executed

`FastlaneCore::UI.command`

**Comment by max-ott** [comment]
I'm not sure what the issue actually is and why this is a problem for the `fastlane` community.

**Comment by cristi-lupu** [comment]
@max-ott Yes, I understand that this issue is so not tangent with the `fastlane` itself. Also, I found a workaround for this:
```ruby
module FastlaneCore
  class UI
    def self.command(message)
      self.ui_object.command(message)
    end
  end
end
```
