### ISSUE TITLE
Auto closed issue is locked and #16620

### ISSUE THREAD

**Issue by bsarrazin** [fastlane/fastlane#17754]
See title
https://github.com/fastlane/fastlane/issues/16620

Can we reopen this issue?

**Comment by max-ott** [comment]
Done.

**Comment by bsarrazin** [comment]
@max-ott can we also reopen the issue since it's not fixed?

**Comment by max-ott** [comment]
Without being testing on the current version of fastlane and the exact steps to reproduce, it does not make sense to re-open the issue.
