### ISSUE TITLE
ld: library not found for -lStreamParser

### ISSUE THREAD

**Issue by DreamPWJ** [fastlane/fastlane#17769]
### Issue Description
Fastlane Debug reported no errors when I executed the packing command

##### Command executed
fastlane debug

##### Complete output when running fastlane, including the stack trace and command used

![image](https://user-images.githubusercontent.com/16730031/101708525-5b073000-3ac8-11eb-9d31-b8cdea3073a8.png)

### Environment

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.0.1                                                         |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.0.1 (20B50)                                           |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.2                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
# Author: 潘维吉
# Description: 自定义核心Fastlane配置文件
# cd *.xcworkspace目录 && fastlane debug

default_platform(:ios)

#声明变量
APP_NAME = ENV['APP_NAME']
SCHEME = ENV['SCHEME']
WORKSPACE = ENV['WORKSPACE']
OUTPUT_DIRECTORY = ENV['OUTPUT_DIRECTORY']
APP_INFO_PLIST_PATH = ENV['APP_INFO_PLIST_PATH']
IPA_TIME = Time.now.strftime("%Y%m%d_%H%M")
ENV_PREFIX = ““
IPA_NAME = ““

platform :ios do

  #在执行lane之前只执行一次
  before_all do |lane, options|
    #options参数 fastlane beta key:value key2:value2
    #value = options[:key]
    #sh "fastlane add_plugin versioning"
    #sh "fastlane add_plugin pgyer"
  end

  #在执行任意环境报错都会中止并执行一次
  error do |lane, exception|

  end

  desc "测试环境发布"
  lane :debug do
    ENV_PREFIX = "debug_"
    EXPORT_METHOD = "ad-hoc"
    puts "Debug模式打包"
    package(configuration: "Release") #Debug
    #上传蒲公英 fastlane add_plugin pgyer
    puts "上传蒲公英"
    pgyer(api_key: ENV['PGYER_API_KEY'], user_key: ENV['PGYER_USR_KEY'], install_type: "1", update_description: "release by fastlane")
    #上传到fir fastlane add_plugin firim
    #firim(firim_api_token: ["***"])
    #hockeyapp国外版分发平台 无需身份证
    #发布testflight测试
    #testflight
  end

  desc "生产环境上架"
  lane :release do
    ENV_PREFIX = "appstore_"
    EXPORT_METHOD = "app-store"
    capture_screenshots
    #register_devices(devices_file: "devices.txt")  # Before calling match, we make sure all our devices are registered on the Apple Developer Portal
    sync_code_signing(force_for_new_devices: true, type: "appstore") # see code signing guide for more information
    package(configuration: "Release")
    #发布到AppStore
    #fastlane deliver
    #deliver --ipa "App.ipa" --submit_for_review
    # deliver(
    #   submit_for_review: true,
    #   force: true,
    #   metadata_path: "./metadata"
    # )
    upload_to_app_store # Upload the screenshots and the binary to iTunes
  end

  #打包函数
  lane :package do |option|
    PLIST_INFO_VERSION = get_version_number(target: "#{SCHEME}")
    PLIST_BUILD_VERSION = get_info_plist_value(path: "#{APP_INFO_PLIST_PATH}", key: 'CFBundleVersion')
    IPA_NAME = "#{ENV_PREFIX}" + "#{APP_NAME}_" + "#{IPA_TIME}_" + "#{PLIST_INFO_VERSION}" + "_#{PLIST_BUILD_VERSION}" + ".ipa"

    #执行 pod install --no-repo-update 时 install时不更新本地库
    cocoapods
    #创建产品信息到iTunes Connect(iTC)或者Apple Developer Center(ADC)
    # produce(
    #   app_name: "#{APP_NAME}",
    #   language: 'zh-Hans',
    #   app_version: '1.0.0',
    #   sku: "#{APP_IDENTIFIER}"
    # )
    #自动创建管理iOS代码签名证书 将确保你在本地计算机上安装了有效的证书及其私钥
    #cert
    #sigh是用来创建、更新、下载、修复Provisioning Profile的工具 每次运行时创建新的配置文件 确保你在本地安装了与证书相匹配的有效配置文件
    #sigh(force: true)
    # 证书管理
    # match(git_url: "http://git.antaikeji.top/health/jenkins-shared-library/_jenkins/ios",
    #       git_private_key: "",
    #       type: "adhoc",
    #       app_identifier: ENV['APP_IDENTIFIER'], #若同工程下有多个,则用["bundleId1","bundleId2"]
    #       readonly: true)

    #打包gym
    build_app(
      workspace: "#{WORKSPACE}", #指定.xcworkspace文件的路径(使用cocopods)
      scheme: "#{SCHEME}", #指定打的哪个scheme
      clean: true, #包前是否先执行clean
      configuration: option[:configuration], #指定构建App的配置  Release、Debug、自定义 默认为Release
      export_method: "#{EXPORT_METHOD}", #打包方法 app-store, ad-hoc, package, enterprise, development 默认app-store
      output_directory: "#{OUTPUT_DIRECTORY}", #输出目录 默认为当前文件夹
      output_name: "#{IPA_NAME}", #输出名称 应包含文件扩展名
      include_symbols: true, #是否包含调试符号
      include_bitcode: true, #是否开启bitcode
      silent: false, #是否隐藏打包时不需要的信息
      xcargs: 'DEBUG_INFORMATION_FORMAT="dwarf-with-dsym"', #附加一些参数传递给xcodebuild  DWARF可以提高编译速度
      export_xcargs: "-allowProvisioningUpdates", #allowProvisioningUpdates来控制自动更新管理Provisoning Profile签名证书
    )
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# For more information about the Appfile, see:
# https://docs.fastlane.tools/advanced/#appfile

app_identifier ENV['APP_IDENTIFIER'] # The bundle identifier of your app
apple_id ENV['APPLE_ID'] # Your Apple email address
team_id ENV['TEAM_ID'] # Developer Portal Team ID

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.170.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.4        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.78.1       |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.1.0        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.11.0       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.14.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.4.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 12.3.2       |
| digest-crc                | 0.6.2        |
| google-cloud-storage      | 1.29.1       |
| emoji_regex               | 3.2.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.403.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.110.0      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.86.0       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

**Comment by rogerluan** [comment]
Hey @DreamPWJ 👋 

That seems to be a compile error, thus unrelated to fastlane? 
Does the project compile by running `xcodebuild (alongside your project config parameters)`? Does it compile in Xcode?

**Comment by DreamPWJ** [comment]
pod install again  work
