### ISSUE TITLE
Fastlane commands that use iTMSTransporter (i.e. deliver) do not work on Linux

### ISSUE THREAD

**Issue by jkcdarunday** [fastlane/fastlane#17762]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Fastlane throws no such file or directory even though it exists. Same error happens when using `./release-1.ipa`, `release-1.ipa`, `~/uploads/release-1.ipa`, and `/home/fastlane/uploads/release-1.ipa` in the --ipa argument.

Specifying a non-existant ipa file throws a different and expected error (`Could not find ipa file at path '/home/bitrise/uploads/release-123.ipa'`) early on so I don't think this is fastlane not being able to find the file.

##### Command executed

```
fastlane deliver --username "[REDACTED]" --app "[REDACTED]" --ipa "release-1.ipa" --skip_screenshots --skip_metadata --force --platform "ios"
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
<pre>
[02:21:24]: Login to App Store Connect ([REDACTED])
[02:21:27]: Login successful

+--------------------------------------+-----------------------+
|                   deliver 2.170.0 Summary                    |
+--------------------------------------+-----------------------+
| username                             | [REDACTED] |
| ipa                                  | release-1.ipa         |
| skip_screenshots                     | true                  |
| skip_metadata                        | true                  |
| force                                | true                  |
| platform                             | ios                   |
| app_identifier                       | [REDACTED]           |
| screenshots_path                     | ./screenshots         |
| metadata_path                        | ./metadata            |
| app_version                          | 1.0.66                |
| edit_live                            | false                 |
| use_live_version                     | false                 |
| skip_binary_upload                   | false                 |
| skip_app_version_update              | false                 |
| overwrite_screenshots                | false                 |
| submit_for_review                    | false                 |
| reject_if_possible                   | false                 |
| phased_release                       | false                 |
| reset_ratings                        | false                 |
| run_precheck_before_submit           | true                  |
| precheck_default_rule_level          | warn                  |
| ignore_language_directory_validation | false                 |
| precheck_include_in_app_purchases    | true                  |
+--------------------------------------+-----------------------+

[02:21:30]: Making sure the latest version on App Store Connect matches '1.0.66'...
[02:21:30]: '1.0.66' is the latest version on App Store Connect
[02:21:30]: Uploading binary to App Store Connect
[02:21:31]: Going to upload updated app to App Store Connect
[02:21:31]: This might take a few minutes. Please don't interrupt the script.

[02:21:31]: Error accessing file, this might be due to fastlane's directory handling
[02:21:31]: Check out https://docs.fastlane.tools/advanced/#directory-behavior for more details

Traceback (most recent call last):
        17: from /home/bitrise/.gem/ruby/2.7.0/bin/fastlane:23:in `<main>'
        16: from /home/bitrise/.gem/ruby/2.7.0/bin/fastlane:23:in `load'
        15: from /home/bitrise/.gem/ruby/2.7.0/gems/fastlane-2.170.0/bin/fastlane:23:in `<top (required)>'
        14: from /home/bitrise/.gem/ruby/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
        13: from /home/bitrise/.gem/ruby/2.7.0/gems/fastlane-2.170.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
        12: from /home/bitrise/.gem/ruby/2.7.0/gems/fastlane-2.170.0/deliver/lib/deliver/commands_generator.rb:186:in `run'
        11: from /var/lib/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        10: from /home/bitrise/.gem/ruby/2.7.0/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
         9: from /var/lib/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
         8: from /var/lib/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
         7: from /var/lib/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
         6: from /home/bitrise/.gem/ruby/2.7.0/gems/fastlane-2.170.0/deliver/lib/deliver/commands_generator.rb:81:in `block (2 levels) in run'
         5: from /home/bitrise/.gem/ruby/2.7.0/gems/fastlane-2.170.0/deliver/lib/deliver/runner.rb:58:in `run'
         4: from /home/bitrise/.gem/ruby/2.7.0/gems/fastlane-2.170.0/deliver/lib/deliver/runner.rb:181:in `upload_binary'
         3: from /home/bitrise/.gem/ruby/2.7.0/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:491:in `upload'
         2: from /home/bitrise/.gem/ruby/2.7.0/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:385:in `execute'
         1: from /usr/lib/ruby/2.7.0/fileutils.rb:139:in `cd'
/usr/lib/ruby/2.7.0/fileutils.rb:139:in `chdir': No such file or directory @ dir_chdir -  (Errno::ENOENT)
</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                       |
| --------------------------- | ----------------------------------------------------------- |
| OS                          | debian_based bullseye/sid                                   |
| Ruby                        | 2.7.0                                                       |
| Bundler?                    | false                                                       |
| Git                         | git version 2.25.1                                          |
| Installation Source         | ~/.gem/ruby/2.7.0/bin/fastlane                              |
| Host                        | Ubuntu 20.04 LTS debian_based bullseye/sid (5.4.0-1009-aws) |
| Ruby Lib Dir                | /usr/lib                                                    |
| OpenSSL Version             | OpenSSL 1.1.1f  31 Mar 2020                                 |
| Is contained                | false                                                       |
| Is homebrew                 | false                                                       |
| Is installed via Fabric.app | false                                                       |

### System Locale

| Variable | Value   |   |
| -------- | ------- | - |
| LANG     | C.UTF-8 | ✅ |
| LC_ALL   |         |   |
| LANGUAGE |         |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.170.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.4        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.78.1       |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.1.0        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| json                      | 2.3.0        |
| mini_magick               | 4.11.0       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.14.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.4.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 12.3.3       |
| digest-crc                | 0.6.2        |
| google-cloud-storage      | 1.29.1       |
| emoji_regex               | 3.2.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.404.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.110.0      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.86.0       |
| uri                       | 0.10.0       |
| bundler                   | 2.1.4        |
| forwardable               | 1.3.1        |
| logger                    | 1.4.2        |
| cgi                       | 0.1.0        |
| timeout                   | 0.1.0        |
| stringio                  | 0.1.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.2.0        |
| strscan                   | 1.0.3        |
| date                      | 3.0.0        |
| delegate                  | 0.1.0        |
| fileutils                 | 1.4.1        |
| etc                       | 1.1.0        |
| io-console                | 0.5.3        |
| zlib                      | 1.1.0        |
| singleton                 | 0.1.0        |
| rexml                     | 3.2.3        |
| open3                     | 0.1.0        |
| yaml                      | 0.1.0        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.6.0        |
</details>

*generated on:* **2020-12-09**
</details>

**Comment by jkcdarunday** [comment]
I checked the line that's causing the error (fastlane_core/lib/fastlane_core/itunes_transporter.rb:385) and it seems that it's trying to chdir to the directory of the iTMSTransporter which I didn't have at that time. I installed iTMSTransporter by following Apple's guide for Linux (https://help.apple.com/itc/transporteruserguide/en.lproj/static.html#apdbb0ee90816044) but it still didn't work and had the same error.

I think I need to specify the path where fastlane will look for the iTMSTransporter binaries? How do I do this?

**Comment by jkcdarunday** [comment]
I was able to specify the iTMS path using `FASTLANE_ITUNES_TRANSPORTER_PATH=/usr/local/itms`. 

This now allows fastlane to find the itms binaries but yields the following error:
```
DEBUG [2020-12-09 16:43:52.19]: /usr/local/itms/java/bin/java -Djava.ext.dirs=/usr/local/itms/java/lib/ext -XX:NewSize=2m -Xms32m -Xmx1024m -Xms1024m -Djava.awt.headless=true -Dsun.net.http.retryPost=false -jar /usr/local/itms/lib/itmstransporter-launcher.jar -m upload -u [REDACTED] -p YourPassword -f /tmp/1519258243.itmsp -k 100000 2>&1
WARN [2020-12-09 16:43:52.20]: [iTMSTransporter] Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
WARN [2020-12-09 16:43:52.20]: [iTMSTransporter] -Djava.ext.dirs=/usr/local/itms/java/lib/ext is not supported.  Use -classpath instead.
WARN [2020-12-09 16:43:52.20]: [iTMSTransporter] Error: Could not create the Java Virtual Machine.
WARN [2020-12-09 16:43:52.20]: [iTMSTransporter] Error: A fatal exception has occurred. Program will exit.
INFO [2020-12-09 16:43:52.20]: iTunes Transporter output above ^
ERROR [2020-12-09 16:43:52.20]: The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
```

I found this odd since running the jar file directly works fine. So i looked into the command being run by fastlane and found that it's calling the class directly instead of the jar file. So I changed the java_code_option function in itunes_transporter.rb to use jar file when using linux (added ` || Helper.linux?`):
```
    def java_code_option
      if Helper.mac? && Helper.xcode_at_least?(9) || Helper.linux?
        return "-jar #{Helper.transporter_java_jar_path.shellescape}"
      else
        return "-classpath #{Helper.transporter_java_jar_path.shellescape} com.apple.transporter.Application"
      end
    end
```

This also threw an error so I played around and eventually removed the `"-Djava.ext.dirs=#{Helper.transporter_java_ext_dir.shellescape}",` in the `build_upload_command` in `itunes_transporter.rb` and running the command now runs the transporter correctly.

The logs now show the ff.:
```
INFO [2020-12-09 16:46:55.87]: This might take a few minutes. Please don't interrupt the script.
DEBUG [2020-12-09 16:46:55.87]: /usr/local/itms/java/bin/java -XX:NewSize=2m -Xms32m -Xmx1024m -Xms1024m -Djava.awt.headless=true -Dsun.net.http.retryPost=false -jar /usr/local/itms/lib/itmstransporter-launcher.jar -m upload -u [REDACTED] -p YourPassword -f /tmp/1519258243.itmsp -k 100000 2>&1
DEBUG [2020-12-09 16:46:59.09]: [Transporter]: INFO: Configuring logging...
DEBUG [2020-12-09 16:46:59.10]: [Transporter]: INFO: Logging level set to eXtreme
```


Unfortunately, the transporter eventually throws the ff. and exits:
```
ERROR [2020-12-09 16:47:06.47]: Unable to perform software analysis on Linux. Export an AppStoreInfo.plist from Xcode, and use the -assetDescription option.
Error while processing package 1519258243.itmsp                                                                                                                          
\nError while processing package 1519258243.itmsp to perform software analysis on Linux. Export an AppStoreInfo.plist from Xcode, and use the -assetDescription option.  
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.    
```

**Comment by jkcdarunday** [comment]
The last error looks like the same issue as #14349 but that ticket was prematurely closed that's just for the last error.

There remains the lack of detection of the iTMS path in linux and the lack of a linux codepath in the build_upload_command et. al. functions to remove the -Djava.ext.dirs parameter that causes errors. 

I will rename the title of this ticket to be about linux issues with iTMSTransporter instead.

**Comment by max-ott** [comment]
Feel free to open a pull request and add support for Linux.
