### ISSUE TITLE
build_app parameter use_system_scm is ignored

### ISSUE THREAD

**Issue by jlajlar** [fastlane/fastlane#17767]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm really happy that you've added `use_system_scm` property to the scan and gym commands in previous version!
But it seems like it's not working correctly since the flag is not added to the xcodebuild command. There should be `-scmProvider system` flag added there to force the xcode to use the system git configuration. It's missing in the log, which results in the build error. See the log below:

```
[17:56:31]: -----------------------
[17:56:31]: --- Step: build_app ---
[17:56:31]: -----------------------
[17:56:31]: Resolving Swift Package Manager dependencies...
[17:56:31]: $ xcodebuild -resolvePackageDependencies -workspace Example.xcworkspace -scheme Example -configuration Release
[17:56:32]: ▸ Command line invocation:
[17:56:32]: ▸     /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -workspace "Example.xcworkspace" -scheme "Example" -configuration Release
[17:56:34]: ▸ Resolve Package Graph
[17:56:34]: ▸ Fetching git@github.com:private/repo.git
[17:56:36]: ▸ xcodebuild: error: Could not resolve package dependencies:
[17:56:36]: ▸   Authentication failed because the credentials were rejected
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -workspace "Example.xcworkspace" -scheme "Example" -configuration Release

Resolve Package Graph

Fetching git@github.com:private/repo.git

xcodebuild: error: Could not resolve package dependencies:
  Authentication failed because the credentials were rejected
```

Running `xcodebuild -resolvePackageDependencies -workspace Example.xcworkspace -scheme Example -configuration Release -scmProvider system` forces the xcodebuild to use the system git configuration and resolves the packages correctly.

I've looked around and could not see any possible workarounds to resolve this issue. 

### Environment

<details>
  <pre>
### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.7                                     |
| Ruby                        | 2.7.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.rvm/gems/ruby-2.7.0/bin/fastlane         |
| Host                        | Mac OS X 10.15.7 (19H15)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.7.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.1h  22 Sep 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.2                                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.170.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                 | Version | Update-Status |
| ---------------------- | ------- | ------------- |
| fastlane-plugin-aws_s3 | 1.8.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| rake                      | 12.3.3       |
| CFPropertyList            | 3.0.3        |
| concurrent-ruby           | 1.1.7        |
| i18n                      | 1.8.5        |
| minitest                  | 5.14.2       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.8        |
| activesupport             | 5.2.4.4      |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| httpclient                | 2.8.3        |
| json                      | 2.3.1        |
| algoliasearch             | 1.27.5       |
| rubyzip                   | 2.3.0        |
| apktools                  | 0.7.4        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.404.0      |
| aws-sigv4                 | 1.2.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.110.0      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.86.0       |
| babosa                    | 1.0.4        |
| bundler                   | 2.1.4        |
| claide                    | 1.0.3        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| netrc                     | 0.11.0       |
| ffi                       | 1.13.1       |
| ethon                     | 0.12.0       |
| typhoeus                  | 1.4.0        |
| cocoapods-core            | 1.10.0       |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.4.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-trunk           | 1.5.0        |
| cocoapods-try             | 1.2.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| cocoapods                 | 1.10.0       |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.2        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.2.1        |
| excon                     | 0.78.1       |
| multipart-post            | 2.0.0        |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.1.0        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| jwt                       | 2.2.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| signet                    | 0.14.0       |
| googleauth                | 0.14.0       |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.4.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.1       |
| mini_magick               | 4.11.0       |
| plist                     | 3.5.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| mime-types-data           | 3.2020.1104  |
| mime-types                | 3.3.1        |
| fastlane-plugin-aws_s3    | 1.8.0        |
| xcode-install             | 2.6.8        |

*generated on:* **2020-12-09**
</pre>
</details>

**Comment by rogerluan** [comment]
Hey @jlajlar ! Nice spotting.

Could you post here a full log using `--verbose` option? Also providing details of the command you executed, as well as your configuration files (e.g. Fastfile, Deliverfile, etc) would help 🙏

**Comment by wvteijlingen** [comment]
I think I'm running into this issue as well, but for the "scan" action. The `use_system_scm` parameter seems to be completely ignored.

**Comment by wvteijlingen** [comment]
I'm running into this issue as well. It seems this option needs to be added here as well: https://github.com/fastlane/fastlane/blob/48151291f2c4949c3b1b9919ba2cc81a7cc33293/fastlane_core/lib/fastlane_core/project.rb#L317

**Comment by rogerluan** [comment]
Hey guys! 

@wvteijlingen thanks for providing the info you found out, it definitely sped up the resolution of the problem 🎉 

I just opened a PR fixing this issue: https://github.com/fastlane/fastlane/pull/17832

**Comment by wvteijlingen** [comment]
Great, thank you @rogerluan! Hope we can merge and release this fix soon.

**Comment by jlajlar** [comment]
@rogerluan thank you for the fix!
