### ISSUE TITLE
spaceship update_availability method raise Not Found error

### ISSUE THREAD

**Issue by schunlee** [fastlane/fastlane#17763]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
these days, I find update_availability! not works again, update_availability! function raise Not Found Error.
```
Spaceship::Tunes.login($FASTLANE_USER, $FASTLANE_PASSWORD)
app = Spaceship::Application.find(ENV['APP_IDENTIFIER'])
availability = app.availability
availability.cleared_for_preorder = pre_order_flag
if pre_order_flag.to_s == "false"
availability.app_available_date = nil
else
availability.app_available_date = pre_order_date
end
puts app.update_availability!(availability)
```
[error screen shot on Bitrise, here]
(https://raw.githubusercontent.com/schunlee/coronavirus_questionnaire_autofill/main/Screen%20Shot%202020-12-09%20at%202.47.48%20PM.png)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by max-ott** [comment]
Please update to the latest version of `fastlane` and make sure to use the new `ConnectAPI` methods. 

```
app_prices = app.prices
attributes_prices = {}
territory_ids = []
price_tier = "0".to_s
territory_ids = Spaceship::ConnectAPI::Territory.all.map(&:id)
attributes[:availableInNewTerritories] = true
app.update(attributes: attributes_prices, app_price_tier_id: price_tier, territory_ids: territory_ids)
```

**Comment by schunlee** [comment]
> Please update to the latest version of `fastlane` and make sure to use the new `ConnectAPI` methods.
> 
> ```
> app_prices = app.prices
> attributes_prices = {}
> territory_ids = []
> price_tier = "0".to_s
> territory_ids = Spaceship::ConnectAPI::Territory.all.map(&:id)
> attributes[:availableInNewTerritories] = true
> app.update(attributes: attributes_prices, app_price_tier_id: price_tier, territory_ids: territory_ids)
> ```

execuse me, how to update preorder by new API?
