### ISSUE TITLE
upload_app_privacy_details_to_app_store should return proper error message on AccessForbidden

### ISSUE THREAD

**Issue by billibala** [fastlane/fastlane#17771]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

`upload_app_privacy_details_to_app_store` fails without proper error message when my Apple Developer account does not have "admin" or "account holder" access level.

I receive an error similar to #17749. And I spent quite some time following the suggestion there. 

I obviously don't realize that Apple requires "admin" or "account holder" access level.

<img width="1321" alt="Screen Shot 2020-12-09 at 7 05 25 PM" src="https://user-images.githubusercontent.com/546385/101716128-8dc21180-3a51-11eb-8df1-d6a9e5542ef7.png">

It would save developers time if `upload_app_privacy_details_to_app_store` (or other command, in general) return proper error message for access permission issue.'

I notice the issue when I run `upload_app_privacy_details_to_app_store` with `--verbose` flag.

##### Command executed
fastlane run upload_app_privacy_details_to_app_store --verbose team_id:xxxxxx json_path:"app_privacy_details.json" app_identifier:"xxx.xxx.xxx"

##### Complete output when running fastlane, including the stack trace and command used

When running with `--verbose`:

<details>
  <pre>
INFO [2020-12-09 16:54:03.92]: -----------------------------------------------------
INFO [2020-12-09 16:54:03.92]: --- Step: upload_app_privacy_details_to_app_store ---
INFO [2020-12-09 16:54:03.92]: -----------------------------------------------------
INFO [2020-12-09 16:54:04.00]: Login to App Store Connect (native@sched.com)
Reading keychain entry, because either user or password were empty
Loading session from '/Users/bill/.fastlane/spaceship/native@sched.com/cookie'
Looking for App Store Connect Team with ID 122294023
INFO [2020-12-09 16:54:06.27]: Login successful
INFO [2020-12-09 16:54:07.92]: Preparing to upload App Data Usage
INFO [2020-12-09 16:54:08.10]: Setting EMAIL_ADDRESS and APP_FUNCTIONALITY to DATA_LINKED_TO_YOU
Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 4)...
Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 3)...
Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 2)...
Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 1)...
Access forbidden
Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 4)...
Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 3)...
Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 2)...
Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 1)...
Access forbidden
Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 4)...
Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 3)...
Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 2)...
Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 1)...
^CTraceback (most recent call last):

</pre>
</details>

When running without `--verbose`:

<details>
<pre>
[✔] 🚀 
[15:26:27]: -----------------------------------------------------
[15:26:27]: --- Step: upload_app_privacy_details_to_app_store ---
[15:26:27]: -----------------------------------------------------
[15:26:27]: Login to App Store Connect (native@sched.com)
[15:26:28]: Login successful
[15:26:30]: Preparing to upload App Data Usage
[15:26:30]: Setting USER_ID and APP_FUNCTIONALITY to DATA_LINKED_TO_YOU

Looking for related GitHub issues on fastlane/fastlane...

➡️  Fastlane match development -> undefined method `com' for nil:NilClass\e[0m (NoMethodError)
    https://github.com/fastlane/fastlane/issues/17320 [open] 6 💬
    5 hours ago

➡️  set_changelog failing to update and ends in error: handle_response': [!] undefined method `status' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/17071 [open] 5 💬
    2 weeks ago

➡️  Spaceship::Tunes::Application.find return nil
    https://github.com/fastlane/fastlane/issues/17607 [open] 7 💬
    a week ago

and 287 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60status%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
NoMethodError: [!] undefined method `status' for nil:NilClass
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/api_client.rb:181:in `handle_response'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/api_client.rb:124:in `post'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:258:in `post_app_data_usage'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `post_app_data_usage'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/models/app_data_usage.rb:45:in `create'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/upload_app_privacy_details_to_app_store.rb:157:in `block (3 levels) in upload_app_data_usages'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/upload_app_privacy_details_to_app_store.rb:150:in `each'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/upload_app_privacy_details_to_app_store.rb:150:in `block (2 levels) in upload_app_data_usages'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/upload_app_privacy_details_to_app_store.rb:149:in `each'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/upload_app_privacy_details_to_app_store.rb:149:in `block in upload_app_data_usages'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/upload_app_privacy_details_to_app_store.rb:138:in `each'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/upload_app_privacy_details_to_app_store.rb:138:in `upload_app_data_usages'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/upload_app_privacy_details_to_app_store.rb:43:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/one_off.rb:42:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/one_off.rb:22:in `execute'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/commands_generator.rb:224:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/bin/fastlane:23:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>'
</pre>
</details>

### Environment

<details>
  <pre>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.0.1                                                         |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.0.1 (20B29)                                           |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.2                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.170.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.4        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.1.0        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.14.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| CFPropertyList            | 3.0.3        |
| excon                     | 0.78.1       |
| json                      | 2.3.1        |
| mini_magick               | 4.11.0       |
| rake                      | 12.3.3       |
| digest-crc                | 0.6.2        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-env          | 1.4.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.1       |
| emoji_regex               | 3.2.1        |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-partitions            | 1.404.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.110.0      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.86.0       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-12-09**
</details>
</pre>
</details>

**Comment by rogerluan** [comment]
Hey @billibala 👋 

I feel you, it's frustrating when the error messages are not helpful 😞 however, that information (and other limitations) is clear in the [upload_app_privacy_details_to_app_store action docs](https://docs.fastlane.tools/uploading-app-privacy-details/#requirements). It's expected that users will read the documentation, to avoid issues like this one.

Nonetheless, I think your request to make error messages more user-friendly makes sense, as it's much much better 👍
