### ISSUE TITLE
NoMethodError…in_house? when using enterprise in sync_code_signing

### ISSUE THREAD

**Issue by thunky-monk** [fastlane/fastlane#17782]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Getting the following when running `sync_code_signing` with `type: "enterprise"`

```ruby 
NoMethodError: [!] undefined method `in_house?' for nil:NilClass
```

##### Command executed

```ruby
sync_code_signing(
    git_url: ENTERPRISE_SIGNING_REPO_URL,
    git_branch: SIGNING_REPO_BRANCH,
    type: "enterprise",
    app_identifier: ALPHA_INHOUSE_APP_IDENTIFIER,
    readonly: false,
    team_id: TEAM_ID_ENTERPRISE,
    verbose: false,
    force: false,
    skip_confirmation: false,
    shallow_clone: false,
    clone_branch_directly: false,
    force_for_new_devices: false,
    skip_docs: false,
    platform: "ios",
  )
```

##### Complete output when running fastlane, including the stack trace and command used

```
bundler: failed to load command: fastlane (/Users/thunky-monk/.rbenv/versions/2.7.2/bin/fastlane)
NoMethodError: [!] undefined method `in_house?' for nil:NilClass
  /Users/aaron/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/match/lib/match/runner.rb:73:in `run'
  /Users/aaron/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/sync_code_signing.rb:14:in `run'
  /Users/aaron/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  /Users/aaron/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
  /Users/aaron/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  /Users/aaron/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  /Users/aaron/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  /Users/aaron/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/aaron/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:184:in `block in parsing_binding'
  /Users/aaron/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/aaron/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/aaron/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/aaron/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/aaron/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /Users/aaron/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/aaron/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/aaron/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/aaron/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/aaron/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/aaron/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/aaron/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/aaron/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  /Users/aaron/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/aaron/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Users/aaron/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/bin/fastlane:23:in `<top (required)>'
  /Users/aaron/.rbenv/versions/2.7.2/bin/fastlane:23:in `load'
  /Users/aaron/.rbenv/versions/2.7.2/bin/fastlane:23:in `<top (required)>'
```

### Environment

<details>
### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.7                                     |
| Ruby                        | 2.7.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.22.0                          |
| Installation Source         | ~/.rbenv/versions/2.7.2/bin/fastlane        |
| Host                        | Mac OS X 10.15.7 (19H15)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.2/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.0.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.170.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status      |
| ----------------------------------------- | ------- | ------------------ |
| fastlane-plugin-firebase_app_distribution | 0.1.4   | 🚫 Update available |
| fastlane-plugin-sentry                    | 1.6.0   | 🚫 Update available |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.4.0        |
| bundler                                   | 2.1.4        |
| uri                                       | 0.10.0       |
| rake                                      | 12.3.3       |
| CFPropertyList                            | 3.0.3        |
| concurrent-ruby                           | 1.1.7        |
| i18n                                      | 0.9.5        |
| minitest                                  | 5.14.2       |
| thread_safe                               | 0.3.6        |
| tzinfo                                    | 1.2.7        |
| activesupport                             | 4.2.11.3     |
| public_suffix                             | 4.0.6        |
| addressable                               | 2.7.0        |
| httpclient                                | 2.8.3        |
| json                                      | 2.3.1        |
| algoliasearch                             | 1.27.4       |
| atomos                                    | 0.1.3        |
| aws-eventstream                           | 1.1.0        |
| aws-partitions                            | 1.405.0      |
| aws-sigv4                                 | 1.2.2        |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.110.0      |
| aws-sdk-kms                               | 1.39.0       |
| aws-sdk-s3                                | 1.86.0       |
| babosa                                    | 1.0.4        |
| claide                                    | 1.0.3        |
| fuzzy_match                               | 2.0.4        |
| nap                                       | 1.1.0        |
| netrc                                     | 0.11.0       |
| ffi                                       | 1.13.1       |
| ethon                                     | 0.12.0       |
| typhoeus                                  | 1.4.0        |
| cocoapods-core                            | 1.9.3        |
| cocoapods-deintegrate                     | 1.0.4        |
| cocoapods-downloader                      | 1.4.0        |
| cocoapods-plugins                         | 1.0.0        |
| cocoapods-search                          | 1.0.0        |
| cocoapods-stats                           | 1.1.0        |
| cocoapods-trunk                           | 1.5.0        |
| cocoapods-try                             | 1.2.0        |
| colored2                                  | 3.1.2        |
| escape                                    | 0.0.4        |
| fourflusher                               | 2.3.1        |
| gh_inspector                              | 1.1.3        |
| molinillo                                 | 0.6.6        |
| ruby-macho                                | 1.4.0        |
| nanaimo                                   | 0.3.0        |
| xcodeproj                                 | 1.19.0       |
| cocoapods                                 | 1.9.3        |
| colored                                   | 1.2          |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| declarative                               | 0.0.20       |
| declarative-option                        | 0.1.0        |
| digest-crc                                | 0.6.2        |
| unf_ext                                   | 0.0.7.7      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| dotenv                                    | 2.7.6        |
| emoji_regex                               | 3.2.1        |
| excon                                     | 0.78.1       |
| multipart-post                            | 2.0.0        |
| ruby2_keywords                            | 0.0.2        |
| faraday                                   | 1.1.0        |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.0.0        |
| fastimage                                 | 2.2.0        |
| jwt                                       | 2.2.2        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.1        |
| signet                                    | 0.14.0       |
| googleauth                                | 0.14.0       |
| mini_mime                                 | 1.0.2        |
| uber                                      | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| google-api-client                         | 0.38.0       |
| google-cloud-env                          | 1.4.0        |
| google-cloud-errors                       | 1.0.1        |
| google-cloud-core                         | 1.5.0        |
| google-cloud-storage                      | 1.29.1       |
| mini_magick                               | 4.11.0       |
| plist                                     | 3.5.0        |
| rubyzip                                   | 2.3.0        |
| security                                  | 0.1.3        |
| naturally                                 | 2.2.0        |
| simctl                                    | 1.6.8        |
| slack-notifier                            | 2.3.2        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.7.0        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| word_wrap                                 | 1.0.0        |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.0        |
| fastlane-plugin-firebase_app_distribution | 0.1.4        |
| fastlane-plugin-sentry                    | 1.6.0        |
</details>

**Comment by max-ott** [comment]
How are you authenticating with Apple?

**Comment by thunky-monk** [comment]
Hey thanks for helping @max-ott. Also I want to tag @MattYY so he sees updates here.

I was mistakenly trying to use the App Store Connect API and a key but I realize the enterprise accounts don't support this. However, the same error also occurs with username and password authentication.

**Comment by rogerluan** [comment]
@thunky-monk how did you switch from App Store Connect API to user+pass credentials? Are you sure it is correctly picking up the user+pass instead of the ASC api token? If you could provide a new stack trace and command executed (with `--verbose`), that'd help a lot 🙏
