### ISSUE TITLE
'Access Forbidden', when running: fastlane init

### ISSUE THREAD

**Issue by NathanClassen** [fastlane/fastlane#17789]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I am trying to deploy to Test Flight, following along the [IOS Setup section](https://docs.fastlane.tools/getting-started/ios/setup/).
The problem is that when I try to initialize Fastlane, I get Access Forbidden. I am using my correct email and password (though I have not been asked again for my password since the initial failed attempt). I can log in the my developer account using the same credentials.

##### Command executed
<code>bundle exec fastlane init --verbose</code>

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>
nathanclassen@Nathans-MBP ios % bundle exec fastlane init --verbose
[✔] 🚀 
DEBUG [2020-12-12 21:27:40.75]: Checking if there are any plugins that should be loaded...
[✔] Looking for iOS and Android projects in current directory...
INFO [2020-12-12 21:27:41.20]: Detected an iOS/macOS project in the current directory: 'Cantor.xcworkspace'
INFO [2020-12-12 21:27:41.29]: -----------------------------
INFO [2020-12-12 21:27:41.29]: --- Welcome to fastlane 🚀 ---
INFO [2020-12-12 21:27:41.29]: -----------------------------
INFO [2020-12-12 21:27:41.29]: fastlane can help you with all kinds of automation for your mobile app
INFO [2020-12-12 21:27:41.29]: We recommend automating one task first, and then gradually automating more over time
WARN [2020-12-12 21:27:41.29]: What would you like to use fastlane for?
1. 📸  Automate screenshots
2. 👩‍✈️  Automate beta distribution to TestFlight
3. 🚀  Automate App Store distribution
4. 🛠  Manual setup - manually setup your project to automate your tasks
?  2
INFO [2020-12-12 21:27:46.95]: -----------------------------------------------------------
INFO [2020-12-12 21:27:46.95]: --- Setting up fastlane for iOS TestFlight distribution ---
INFO [2020-12-12 21:27:46.95]: -----------------------------------------------------------
INFO [2020-12-12 21:27:46.95]: Parsing your local Xcode project to find the available schemes and the app identifier
Select Scheme: 
1. Cantor-tvOS
2. Cantor
?  2
WARN [2020-12-12 21:27:50.64]: Resolving Swift Package Manager dependencies...
INFO [2020-12-12 21:27:50.64]: $ xcodebuild -resolvePackageDependencies -workspace Cantor.xcworkspace -scheme Cantor
INFO [2020-12-12 21:27:51.31]: ▸ Command line invocation:
INFO [2020-12-12 21:27:51.31]: ▸     /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -workspace Cantor.xcworkspace -scheme Cantor
INFO [2020-12-12 21:27:52.56]: ▸ resolved source packages: 
INFO [2020-12-12 21:27:52.58]: $ xcodebuild -showBuildSettings -workspace Cantor.xcworkspace -scheme Cantor
INFO [2020-12-12 21:27:54.70]: $ cd /Users/nathanclassen/Projects/CantorMobile/ios && agvtool what-version -terse
INFO [2020-12-12 21:27:54.92]: ▸ 1
INFO [2020-12-12 21:27:54.92]: --------------------------------
INFO [2020-12-12 21:27:54.92]: --- Login with your Apple ID ---
INFO [2020-12-12 21:27:54.92]: --------------------------------
INFO [2020-12-12 21:27:54.92]: To use App Store Connect and Apple Developer Portal features as part of fastlane,
INFO [2020-12-12 21:27:54.92]: we will ask you for your Apple ID username and password
INFO [2020-12-12 21:27:54.92]: This is necessary for certain fastlane features, for example:
INFO [2020-12-12 21:27:54.92]: 
INFO [2020-12-12 21:27:54.92]: - Create and manage your provisioning profiles on the Developer Portal
INFO [2020-12-12 21:27:54.92]: - Upload and manage TestFlight and App Store builds on App Store Connect
INFO [2020-12-12 21:27:54.92]: - Manage your App Store Connect app metadata and screenshots
INFO [2020-12-12 21:27:54.92]: 
INFO [2020-12-12 21:27:54.92]: Your Apple ID credentials will only be stored in your Keychain, on your local machine
INFO [2020-12-12 21:27:54.92]: For more information, check out
INFO [2020-12-12 21:27:54.92]: 	https://github.com/fastlane/fastlane/tree/master/credentials_manager
INFO [2020-12-12 21:27:54.92]: 
WARN [2020-12-12 21:27:54.92]: Please enter your Apple ID developer credentials
 [2020-12-12 21:27:54.92]: Apple ID Username:
hayesclassen@gmail.com
INFO [2020-12-12 21:28:03.56]: Logging in...
Reading keychain entry, because either user or password were empty
Loading session from '/Users/nathanclassen/.fastlane/spaceship/hayesclassen@gmail.com/cookie'
Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 4)...
Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 3)...
Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 2)...
Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 1)...
ERROR [2020-12-12 21:28:17.22]: --------------------
ERROR [2020-12-12 21:28:17.22]: fastlane init failed
ERROR [2020-12-12 21:28:17.22]: --------------------
DEBUG [2020-12-12 21:28:17.22]: /Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/client.rb:887:in `block in send_request'
/Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/client.rb:631:in `with_retry'
/Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/client.rb:867:in `send_request'
/Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/client.rb:711:in `request'
/Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/client.rb:126:in `user_details_data'
/Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/client.rb:72:in `teams'
/Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/tunes/tunes_client.rb:78:in `select_team'
/Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/tunes/spaceship.rb:35:in `select_team'
/Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/setup/setup_ios.rb:321:in `ask_for_credentials'
/Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/setup/setup_ios.rb:84:in `ios_testflight'
/Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/setup/setup_ios.rb:48:in `setup_ios'
/Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/setup/setup.rb:108:in `start'
/Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/commands_generator.rb:121:in `block (2 levels) in run'
/Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
/Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
/Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
/Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
/Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
/Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
/Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
/Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
/Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/bin/fastlane:23:in `<top (required)>'
/Users/nathanclassen/.rbenv/versions/2.6.3/bin/fastlane:23:in `load'
/Users/nathanclassen/.rbenv/versions/2.6.3/bin/fastlane:23:in `<top (required)>'
/Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `load'
/Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `kernel_load'
/Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/cli/exec.rb:28:in `run'
/Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/cli.rb:463:in `exec'
/Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/cli.rb:27:in `dispatch'
/Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/cli.rb:18:in `start'
/Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:30:in `block in <top (required)>'
/Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:22:in `<top (required)>'
/Users/nathanclassen/.rbenv/versions/2.6.3/bin/bundle:23:in `load'
/Users/nathanclassen/.rbenv/versions/2.6.3/bin/bundle:23:in `<main>'
ERROR [2020-12-12 21:28:17.22]: ["The request could not be completed because:", "Access forbidden"]
WARN [2020-12-12 21:28:17.22]: Something failed while running `fastlane init`
WARN [2020-12-12 21:28:17.22]: Tried using Apple ID with email 'hayesclassen@gmail.com'
WARN [2020-12-12 21:28:17.22]: You can either retry, or fallback to manual setup which will create a basic Fastfile
 [2020-12-12 21:28:17.22]: Would you like to fallback to a manual Fastfile? (y/n)
n
INFO [2020-12-12 21:28:22.36]: -----------------------------------------------------------
INFO [2020-12-12 21:28:22.36]: --- Setting up fastlane for iOS TestFlight distribution ---
INFO [2020-12-12 21:28:22.36]: -----------------------------------------------------------
INFO [2020-12-12 21:28:22.36]: Parsing your local Xcode project to find the available schemes and the app identifier
Select Scheme: 
1. Cantor-tvOS
2. Cantor
?  2
WARN [2020-12-12 21:28:29.27]: Resolving Swift Package Manager dependencies...
INFO [2020-12-12 21:28:29.27]: $ xcodebuild -resolvePackageDependencies -workspace Cantor.xcworkspace -scheme Cantor
INFO [2020-12-12 21:28:29.93]: ▸ Command line invocation:
INFO [2020-12-12 21:28:29.93]: ▸     /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -workspace Cantor.xcworkspace -scheme Cantor
INFO [2020-12-12 21:28:31.17]: ▸ resolved source packages: 
INFO [2020-12-12 21:28:31.19]: $ xcodebuild -showBuildSettings -workspace Cantor.xcworkspace -scheme Cantor
INFO [2020-12-12 21:28:33.30]: $ cd /Users/nathanclassen/Projects/CantorMobile/ios && agvtool what-version -terse
INFO [2020-12-12 21:28:33.53]: ▸ 1
INFO [2020-12-12 21:28:33.53]: --------------------------------
INFO [2020-12-12 21:28:33.53]: --- Login with your Apple ID ---
INFO [2020-12-12 21:28:33.53]: --------------------------------
INFO [2020-12-12 21:28:33.53]: To use App Store Connect and Apple Developer Portal features as part of fastlane,
INFO [2020-12-12 21:28:33.53]: we will ask you for your Apple ID username and password
INFO [2020-12-12 21:28:33.53]: This is necessary for certain fastlane features, for example:
INFO [2020-12-12 21:28:33.53]: 
INFO [2020-12-12 21:28:33.54]: - Create and manage your provisioning profiles on the Developer Portal
INFO [2020-12-12 21:28:33.54]: - Upload and manage TestFlight and App Store builds on App Store Connect
INFO [2020-12-12 21:28:33.54]: - Manage your App Store Connect app metadata and screenshots
INFO [2020-12-12 21:28:33.54]: 
INFO [2020-12-12 21:28:33.54]: Your Apple ID credentials will only be stored in your Keychain, on your local machine
INFO [2020-12-12 21:28:33.54]: For more information, check out
INFO [2020-12-12 21:28:33.54]: 	https://github.com/fastlane/fastlane/tree/master/credentials_manager
INFO [2020-12-12 21:28:33.54]: 
INFO [2020-12-12 21:28:33.54]: Logging in...
Reading keychain entry, because either user or password were empty
Loading session from '/Users/nathanclassen/.fastlane/spaceship/hayesclassen@gmail.com/cookie'
Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 4)...
Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 3)...
Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 2)...
Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 1)...

Looking for related GitHub issues on fastlane/fastlane...
Search query: The request could not be completed because:
	Access forbidden

URL: https://api.github.com/search/issues?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09Access%20forbidden+repo:fastlane/fastlane
➡️  'Access Forbidden', when running: fastlane init
    https://github.com/fastlane/fastlane/issues/17789 [open] 0 💬
    12 minutes ago

➡️  The request could not be completed because: Access forbidden
    https://github.com/fastlane/fastlane/issues/17479 [closed] 3 💬
    21 Oct 2020

➡️  The request could not be completed because: 	Access forbidden
    https://github.com/fastlane/fastlane/issues/17141 [closed] 5 💬
    6 weeks ago

and 5 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09Access%20forbidden&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/Users/nathanclassen/.rbenv/versions/2.6.3/bin/fastlane)
Spaceship::AccessForbiddenError: [!] The request could not be completed because:
	Access forbidden
  /Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/client.rb:887:in `block in send_request'
  /Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/client.rb:631:in `with_retry'
  /Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/client.rb:867:in `send_request'
  /Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/client.rb:711:in `request'
  /Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/client.rb:126:in `user_details_data'
  /Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/client.rb:72:in `teams'
  /Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/tunes/tunes_client.rb:78:in `select_team'
  /Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/tunes/spaceship.rb:35:in `select_team'
  /Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/setup/setup_ios.rb:321:in `ask_for_credentials'
  /Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/setup/setup_ios.rb:84:in `ios_testflight'
  /Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/setup/setup_ios.rb:73:in `rescue in setup_ios'
  /Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/setup/setup_ios.rb:47:in `setup_ios'
  /Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/setup/setup.rb:108:in `start'
  /Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/commands_generator.rb:121:in `block (2 levels) in run'
  /Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  /Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Users/nathanclassen/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/bin/fastlane:23:in `<top (required)>'
  /Users/nathanclassen/.rbenv/versions/2.6.3/bin/fastlane:23:in `load'
  /Users/nathanclassen/.rbenv/versions/2.6.3/bin/fastlane:23:in `<top (required)>'
  </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.7                                     |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.rbenv/versions/2.6.3/bin/fastlane        |
| Host                        | Mac OS X 10.15.7 (19H15)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.3/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.2                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.170.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 1.17.2       |
| etc                       | 1.0.1        |
| forwardable               | 1.2.0        |
| rake                      | 12.3.3       |
| CFPropertyList            | 3.0.3        |
| concurrent-ruby           | 1.1.7        |
| i18n                      | 1.8.5        |
| minitest                  | 5.14.2       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.8        |
| activesupport             | 5.2.4.4      |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| httpclient                | 2.8.3        |
| json                      | 2.3.1        |
| algoliasearch             | 1.27.5       |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.405.0      |
| aws-sigv4                 | 1.2.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.110.0      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.86.1       |
| babosa                    | 1.0.4        |
| claide                    | 1.0.3        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| netrc                     | 0.11.0       |
| ffi                       | 1.13.1       |
| ethon                     | 0.12.0       |
| typhoeus                  | 1.4.0        |
| cocoapods-core            | 1.10.0       |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.4.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-trunk           | 1.5.0        |
| cocoapods-try             | 1.2.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| cocoapods                 | 1.10.0       |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.2        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.2.1        |
| excon                     | 0.78.1       |
| multipart-post            | 2.0.0        |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.1.0        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| jwt                       | 2.2.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| signet                    | 0.14.0       |
| googleauth                | 0.14.0       |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.4.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.1       |
| mini_magick               | 4.11.0       |
| plist                     | 3.5.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2020-12-12**
</details></pre>

**Comment by Xi-gofore** [comment]
I am having the same issue, how did you resolve it?

**Comment by zhaomingli007** [comment]
I am having the same issue, how did you resolve it?

**Comment by gongiskhan** [comment]
Why is the issue closed? I am new to fastlane (installed via homebrew after a failed attempt using ruby) and have this issue...

**Comment by NathanClassen** [comment]
I suppose I should have left this open. I did not reach a resolution, but found that I was not quite ready for deploying. I don't know why I closed... my apologies all!

**Comment by max-ott** [comment]
Are you sure that you have the correct rights on App Store Connect and a valid developer account?

**Comment by iwasrobbed** [comment]
Just as an aside, the account should be given at least `App Store Manager` access AND also needs access to the certificates & profiles on their user profile with App Store Connect

<img width="539" alt="Screen Shot 2021-01-07 at 9 24 39 AM" src="https://user-images.githubusercontent.com/317671/103903826-669b4600-50ca-11eb-8736-c0a3fd995ce6.png">
