### ISSUE TITLE
[!] Unsupported screen size [1413, 2844] for path './fastlane/screenshots/en-US/iPhone 11 Pro Max

### ISSUE THREAD

**Issue by saroar** [fastlane/fastlane#17781]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 11.0.1                                                  |
| Ruby                        | 2.7.2                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.24.3 (Apple Git-128)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.170.0/libexec/bin/fastlane |
| Host                        | macOS 11.0.1 (20B50)                                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.7.2/lib                        |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                             |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 12.2                                                    |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.170.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.4        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.78.1       |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.1.0        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| json                      | 2.3.0        |
| mini_magick               | 4.11.0       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.14.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.4.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 12.3.3       |
| digest-crc                | 0.6.2        |
| google-cloud-storage      | 1.29.1       |
| emoji_regex               | 3.2.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.402.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.110.0      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.86.0       |
| uri                       | 0.10.0       |
| forwardable               | 1.3.1        |
| logger                    | 1.4.2        |
| cgi                       | 0.1.0        |
| timeout                   | 0.1.0        |
| stringio                  | 0.1.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.2.0        |
| strscan                   | 1.0.3        |
| date                      | 3.0.0        |
| delegate                  | 0.1.0        |
| fileutils                 | 1.4.1        |
| io-console                | 0.5.6        |
| zlib                      | 1.1.0        |
| singleton                 | 0.1.0        |
| rexml                     | 3.2.3        |
| open3                     | 0.1.0        |
| yaml                      | 0.1.0        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.6.0        |
</details>

*generated on:* **2020-12-11**
</details>

my Snapfiel
```
# A list of devices you want to take the screenshots from
devices([
  "iPhone 11 Pro Max",
  "iPhone 8 Plus",
  "iPad Pro (12.9-inch) (4th generation)"
])

languages([
   "en-US",
#   "de-DE",
#   "it-IT",
#   ["pt", "pt_BR"] # Portuguese with Brazilian locale
])

# The name of the scheme which contains the UI Tests 
scheme("AddaMeIOSUITests")

# set-simulator-location -q Lyft HQ Apple
stop_after_first_error true
erase_simulator true
clear_previous_scree
reinstall_app true
```

i dont want to any text or something else just frame
also one more problem 
'./fastlane/screenshots/en-US/iPad Pro (12.9-inch) (4th generation)-events.png' [20:37:59]: Couldn't find template for screenshot type 'Apple iPad Pro (12.9-inch) (4th generation) Space Gray'
[20:16:22]: Please run `fastlane frameit download_frames` to download the latest frames < also try 

also try this 
lane :sandbox do
    capture_screenshots
    frame_screenshots(white: true)
    frameit(path: "./fastlane/screenshots")
  end
also try separate CMD
 run snapshot with the device iPad Pro (12.9-inch) (4th generation), then run frameit.

**Comment by saroar** [comment]
![iPhone 11 Pro Max-events_framed](https://user-images.githubusercontent.com/8770772/101936596-c7318300-3bf1-11eb-954b-50337c32e9bd.png)

**Comment by ainame** [comment]
Hey! You should provide more details about error message here

> Complete output when running fastlane, including the stack trace and command used

Regarding the error message at the title of this issue, 1413x2844 is actually not the screenshot size that matches any type of iPhone ever released. I don't know how come you get that though.

> also one more problem
'./fastlane/screenshots/en-US/iPad Pro (12.9-inch) (4th generation)-events.png' [20:37:59]: Couldn't find template for screenshot type 'Apple iPad Pro (12.9-inch) (4th generation) Space Gray'

Looking at the latest directory, 4th gen one isn't in there. I suppose the frame design isn't changed from 3rd gen and it's there. You can use 3rd gen one as an equivalent.
https://github.com/fastlane/frameit-frames/tree/gh-pages/latest

**Comment by saroar** [comment]
@ainame why my quis is

Copy from Document
Automatically add device frames around all screenshots in the current directory and its subdirectories, just run
`fastlane frameit`
why frameit has not created in all size as require?
i don't need to customize the title background and font etc 


-> Hey! You should provide more details about the error message here
There are not more details

**Comment by saroar** [comment]
[12:54:39]: Unsupported screen size [2245, 2930] for path './fastlane/screenshots/en-US/iPad Pro (12.9-inch) (3rd generation)-inputVerificationCode_framed.png'

+------+-------------------+-------------+
|            fastlane summary            |
+------+-------------------+-------------+
| Step | Action            | Time (in s) |
+------+-------------------+-------------+
| 1    | default_platform  | 0           |
| 2    | frame_screenshots | 180         |
| 3    | frameit           | 189         |
| 💥   | deliver           | 4           |
+------+-------------------+-------------+

[12:54:39]: fastlane finished with errors

[!] Unsupported screen size [2245, 2930] for path './fastlane/screenshots/en-US/iPad Pro (12.9-inch) (3rd generation)-inputVerificationCode_framed.png'

**Comment by saroar** [comment]
<img width="1001" alt="Screenshot 2020-12-12 at 16 27 25" src="https://user-images.githubusercontent.com/8770772/101985113-09f96680-3c97-11eb-93a3-660a8ff94fac.png">
why? its wrong yes? @ainame

**Comment by saroar** [comment]
@ainame 
Regarding the error message at the title of this issue, 1413x2844 is actually not the screenshot size that matches any type of iPhone ever released. I don't know how come you get that though. https://www.paintcodeapp.com/news/ultimate-guide-to-iphone-resolutions

why fastlane frameit create this kind of size 1413x2844 which code make this size ?

**Comment by ainame** [comment]
I guess you just misunderstood about `frameit`. `frameit` has 2 modes; one is to frame actual screenshots as you did, another one is to additionally decorate framed screenshots with text, background, or customized fonts... The former one doesn't resize images to the sizes that are acceptable on App Store Connect but instead, it embed the original screenshot in the device frame without changing the original screenshot. That's why yours are bigger than screenshots sizes accepted. (It's documented)

> Note: When using frameit without titles on top, the screenshots will have the full resolution, which means they can't be uploaded to the App Store directly. They are supposed to be used for websites, print media and emails. Check out the section below to use the screenshots for the App Store.

https://docs.fastlane.tools/actions/frameit/
