### ISSUE TITLE
how to change https to ssh protocol in push_to_git_remote

### ISSUE THREAD

**Issue by Rickkorsten** [fastlane/fastlane#17796]
Hello,

Is it possible to change the protocol from https to ssh in push_to_git_remote ?

thanks!

**Comment by Rickkorsten** [comment]
FastlaneCore::Interface::FastlaneShellError: [31m[!] Exit status of command 'git push origin HEAD:HEAD --tags' was 128 instead of 0.
remote: You are not allowed to upload code.
fatal: unable to access 'https://gitlab.carsys.online/cbgms/mobile-application.git/': The requested URL returned error: 403

**Comment by max-ott** [comment]
I'm not sure how this is related to fastlane.
