### ISSUE TITLE
undefined method `id' for nil

### ISSUE THREAD

**Issue by zemos** [fastlane/fastlane#17818]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I face ```undefined method `id' for nil``` issue when cert is trying to repair provisioning profiles. I have valid distribution certificate and have proper access rights. Can you please help me with it?

##### Command executed

```bundle exec fastlane sigh repair --username USERNAME --team_id TEAM_ID --verbose```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>bundle exec fastlane sigh repair --username USERNAME --team_id TEAM_ID --verbose                      
[✔] 🚀 
INFO [2020-12-16 17:14:07.25]: Starting login with user 'USERNAME'
Reading keychain entry, because either user or password were empty
INFO [2020-12-16 17:14:09.70]: Successfully logged in
INFO [2020-12-16 17:14:10.65]: Going to repair 11 provisioning profiles
INFO [2020-12-16 17:14:10.65]: Repairing profile 'Provi Name DIST'...

Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `id' for nil

URL: https://api.github.com/search/issues?q=undefined%20method%20%60id%27%20for%20nil+repo:fastlane/fastlane
➡️  Fastlane match development -> undefined method `com' for nil:NilClass\e[0m (NoMethodError)
    https://github.com/fastlane/fastlane/issues/17320 [open] 6 💬
    a week ago

➡️  Download DSYMs action broken
    https://github.com/fastlane/fastlane/issues/17677 [open] 1 💬
    a week ago

➡️  set_changelog failing to update and ends in error: handle_response': [!] undefined method `status' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/17071 [open] 5 💬
    3 weeks ago

and 269 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60id%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/Users/zemos/Projekty/Core Tools/FastlaneMatchTest/vendor/bundle/ruby/2.7.0/bin/fastlane)
NoMethodError: [!] undefined method `id' for nil:NilClass
  /Users/zemos/Projekty/Core Tools/FastlaneMatchTest/vendor/bundle/ruby/2.7.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:456:in `map'
  /Users/zemos/Projekty/Core Tools/FastlaneMatchTest/vendor/bundle/ruby/2.7.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:456:in `block in update!'
  /Users/zemos/Projekty/Core Tools/FastlaneMatchTest/vendor/bundle/ruby/2.7.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/client.rb:631:in `with_retry'
  /Users/zemos/Projekty/Core Tools/FastlaneMatchTest/vendor/bundle/ruby/2.7.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:450:in `update!'
  /Users/zemos/Projekty/Core Tools/FastlaneMatchTest/vendor/bundle/ruby/2.7.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:418:in `repair!'
  /Users/zemos/Projekty/Core Tools/FastlaneMatchTest/vendor/bundle/ruby/2.7.0/gems/fastlane-2.170.0/sigh/lib/sigh/repair.rb:28:in `block in repair_all'
  /Users/zemos/Projekty/Core Tools/FastlaneMatchTest/vendor/bundle/ruby/2.7.0/gems/fastlane-2.170.0/sigh/lib/sigh/repair.rb:26:in `each'
  /Users/zemos/Projekty/Core Tools/FastlaneMatchTest/vendor/bundle/ruby/2.7.0/gems/fastlane-2.170.0/sigh/lib/sigh/repair.rb:26:in `repair_all'
  /Users/zemos/Projekty/Core Tools/FastlaneMatchTest/vendor/bundle/ruby/2.7.0/gems/fastlane-2.170.0/sigh/lib/sigh/commands_generator.rb:96:in `block (2 levels) in run'
  /Users/zemos/Projekty/Core Tools/FastlaneMatchTest/vendor/bundle/ruby/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/zemos/Projekty/Core Tools/FastlaneMatchTest/vendor/bundle/ruby/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/zemos/Projekty/Core Tools/FastlaneMatchTest/vendor/bundle/ruby/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/zemos/Projekty/Core Tools/FastlaneMatchTest/vendor/bundle/ruby/2.7.0/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/zemos/Projekty/Core Tools/FastlaneMatchTest/vendor/bundle/ruby/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/zemos/Projekty/Core Tools/FastlaneMatchTest/vendor/bundle/ruby/2.7.0/gems/fastlane-2.170.0/sigh/lib/sigh/commands_generator.rb:139:in `run'
  /Users/zemos/Projekty/Core Tools/FastlaneMatchTest/vendor/bundle/ruby/2.7.0/gems/fastlane-2.170.0/sigh/lib/sigh/commands_generator.rb:16:in `start'
  /Users/zemos/Projekty/Core Tools/FastlaneMatchTest/vendor/bundle/ruby/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
  /Users/zemos/Projekty/Core Tools/FastlaneMatchTest/vendor/bundle/ruby/2.7.0/gems/fastlane-2.170.0/bin/fastlane:23:in `<top (required)>'
  /Users/zemos/Projekty/Core Tools/FastlaneMatchTest/vendor/bundle/ruby/2.7.0/bin/fastlane:23:in `load'
  /Users/zemos/Projekty/Core Tools/FastlaneMatchTest/vendor/bundle/ruby/2.7.0/bin/fastlane:23:in `<top (required)>' </pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                                         |
| --------------------------- | ----------------------------------------------------------------------------- |
| OS                          | 10.15.6                                                                       |
| Ruby                        | 2.7.2                                                                         |
| Bundler?                    | true                                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                                            |
| Installation Source         | ~/Projekty/Core Tools/FastlaneMatchTest/vendor/bundle/ruby/2.7.0/bin/fastlane |
| Host                        | Mac OS X 10.15.6 (19G2021)                                                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.7.2/lib                                              |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                                                   |
| Is contained                | false                                                                         |
| Is homebrew                 | false                                                                         |
| Is installed via Fabric.app | false                                                                         |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                                   |
| Xcode Version               | 12.2                                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.170.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| bundler                   | 2.1.4        |
| uri                       | 0.10.0       |
| rake                      | 12.3.3       |
| CFPropertyList            | 3.0.3        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.407.0      |
| aws-sigv4                 | 1.2.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.110.0      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.86.2       |
| babosa                    | 1.0.4        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.2        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.2.1        |
| excon                     | 0.78.1       |
| multipart-post            | 2.0.0        |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.1.0        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.2.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| signet                    | 0.14.0       |
| googleauth                | 0.14.0       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.4.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.2       |
| json                      | 2.4.0        |
| mini_magick               | 4.11.0       |
| plist                     | 3.5.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2020-12-16**
</details></pre>
</details>

**Comment by brettdh** [comment]
Encountered this today with 2.172.0; please do not close.

**Comment by savv** [comment]
I am also running into this issue, on 2.170.0 with Ruby 2.6:
```
bundler: failed to load command: fastlane (/opt/hostedtoolcache/Ruby/2.6.6/x64/bin/fastlane)
Fastfile:5:in `parsing_binding': [!] undefined method `[]' for nil:NilClass (NoMethodError)
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/fast_file.rb:61:in `eval'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/fast_file.rb:61:in `block in parse'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/fast_file.rb:50:in `chdir'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/fast_file.rb:50:in `parse'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/fast_file.rb:40:in `initialize'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/lane_manager.rb:15:in `new'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/lane_manager.rb:15:in `cruise_lane'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
```

And also on 2.172.0 with Ruby 2.7:
```
bundler: failed to load command: fastlane (/opt/hostedtoolcache/Ruby/2.7.2/x64/bin/fastlane)
Fastfile:5:in `parsing_binding': \e[31m[!] undefined method `[]' for nil:NilClass\e[0m (NoMethodError)
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/fast_file.rb:61:in `eval'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/fast_file.rb:61:in `block in parse'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/fast_file.rb:50:in `chdir'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/fast_file.rb:50:in `parse'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/fast_file.rb:40:in `initialize'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/lane_manager.rb:15:in `new'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/lane_manager.rb:15:in `cruise_lane'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.172.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.172.0/bin/fastlane:23:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/bin/fastlane:23:in `load'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/bin/fastlane:23:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/cli/exec.rb:63:in `load'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/cli/exec.rb:63:in `kernel_load'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/cli/exec.rb:28:in `run'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/cli.rb:494:in `exec'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/cli.rb:30:in `dispatch'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/cli.rb:24:in `start'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/exe/bundle:49:in `block in <top (required)>'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/exe/bundle:37:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/bin/bundle:23:in `load'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/bin/bundle:23:in `<main>'
Fastfile:5:in `parsing_binding': undefined method `[]' for nil:NilClass (NoMethodError)
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/fast_file.rb:61:in `eval'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/fast_file.rb:61:in `block in parse'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/fast_file.rb:50:in `chdir'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/fast_file.rb:50:in `parse'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/fast_file.rb:40:in `initialize'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/lane_manager.rb:15:in `new'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/lane_manager.rb:15:in `cruise_lane'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.172.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.172.0/bin/fastlane:23:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/bin/fastlane:23:in `load'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/bin/fastlane:23:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/cli/exec.rb:63:in `load'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/cli/exec.rb:63:in `kernel_load'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/cli/exec.rb:28:in `run'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/cli.rb:494:in `exec'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/cli.rb:30:in `dispatch'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/cli.rb:24:in `start'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/exe/bundle:49:in `block in <top (required)>'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/exe/bundle:37:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/bin/bundle:23:in `load'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/bin/bundle:23:in `<main>'
```

**Comment by justinseanmartin** [comment]
This appears to still be an issue. We just saw this on calling `repair!` on an old provisioning profile that is no longer associated with any certificates in the account. The exception seems to happen because no matching certificate is found in `Spaceship::Portal::ProvisioningProfile#update!`. There is a newer `AppleDevelopment` certificate in the account, but the old expired MPP is associated with an iOS `Development` type certificate that is no longer present.
