### ISSUE TITLE
match permission denied

### ISSUE THREAD

**Issue by talezion** [fastlane/fastlane#17810]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I am getting Match issues `unexpected token` and `Access Denied`

##### Command executed

`fastlane match`

##### Complete output when running fastlane, including the stack trace and command used

<details>

I am getting Match issues `unexpected token` and `Access Denied`

```
fastlane match adhoc
fastlane could not check for updates error: 776: unexpected token at '<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>some-request-id>spme-host-id=</HostId></Error>'
[22:55:56]: Successfully loaded '/Users/talsmacbookpro/Matchfile' 📄

+---------+--------------------------------------+
|       Detected Values from './Matchfile'       |
+---------+--------------------------------------+
| git_url | https://github.com/some-team/  |
|         | iOS_Certificates.git                 |
| type    | development                          |
+---------+--------------------------------------+


+-----------------------+--------------------------------------+
|                   Summary for match 2.28.3                   |
+-----------------------+--------------------------------------+
| git_url               | https://github.com/some-team/  |
|                       | iOS_Certificates.git                 |
| type                  | adhoc                                |
| git_branch            | master                               |
| keychain_name         | login.keychain                       |
| readonly              | false                                |
| verbose               | false                                |
| force                 | false                                |
| skip_confirmation     | false                                |
| shallow_clone         | false                                |
| force_for_new_devices | false                                |
| skip_docs             | false                                |
| platform              | ios                                  |
+-----------------------+--------------------------------------+

[22:55:56]: Cloning remote git repo...
[22:55:57]: 🔓  Successfully decrypted certificates repo
[22:55:57]: To not be asked about this value, you can specify it using 'username'
[22:55:57]: Your Apple ID Username: some-email@gmail.com
[22:56:15]: Verifying that the certificate and profile are still valid on the Dev Portal...

Looking for related GitHub issues on fastlane/fastlane...

➡️  Exception type: Spaceship::UnauthorizedAccessError
   https://github.com/fastlane/fastlane/issues/16510 [closed] 35 💬
   17 Sep 2020

➡️  fastlane cert got Unauthorized Access error
   https://github.com/fastlane/fastlane/issues/16108 [closed] 62 💬
   18 Jun 2020

➡️  fastlane spaceauth return Unauthorized Access
   https://github.com/fastlane/fastlane/issues/16197 [closed] 3 💬
   25 May 2020

and 19 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09Unauthorized%20Access&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.

[!] The request could not be completed because:
	Unauthorized Access
```

</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.16.3                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.15.6 (19G73)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.28.3  | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2020-12-15**
</details>

**Comment by rogerluan** [comment]
Hey @talezion 👋 

Are you behind a firewall, or proxy? 
I see two major issues there:

1. _fastlane_ couldn't check for updates, which probably means your network is filtering connections. If your network is filtering connections, it may be the reason why it couldn't authenticate correctly (permission denied).
2. Your version of fastlane is **really** old. Since old fastlane APIs rely on undocumented Apple APIs, you should always be up-to-date with the latest version of _fastlane_ to make sure everything keeps running smoothly.

Once those 2 issues are resolved, let us know if the problem persists.

**Comment by reyesm93** [comment]
Getting same error here: 

`Aws::S3::Errors::AccessDenied: [!] Access Denied`

This is what my match file looks like: 

`s3_bucket("my-bucket")
s3_region(ENV["AWS_DEFAULT_REGION"])
s3_access_key(ENV["AWS_ACCESS_KEY_ID"])
s3_secret_access_key(ENV["AWS_SECRET_ACCESS_KEY"])
storage_mode("s3")

type("appstore")
app_identifier(["my.app.identifier"])
username("myappleid@icloud.com")`

**Comment by rogerluan** [comment]
Hey @reyesm93 👋 

Worth noting that your looks is completely different from OP's (although I don't have any log from your command execution) - as yours clearly states it's a S3 error, whereas OP's permission denied seems to be system-wide. 

I replied your SO question: https://stackoverflow.com/a/65370127/4075379

Basically, I believe you need the `s3:PutBucketPolicy` permission policy.

**Comment by reyesm93** [comment]
Hi @rogerluan 

Thanks a lot for the response here and on SO. Your article helped and I was able to get past this permission's issue!

**Comment by rogerluan** [comment]
Glad to hear your issue has been resolved @reyesm93 ! 😊
Could you mark my answer as accepted on SO? 🤗

**Comment by rogerluan** [comment]
@talezion any update? 🤗

**Comment by talezion** [comment]
Hi @rogerluan , doesn't work my side. My AccessDenied is not related to AWS. I am getting this error on any fastlane command. Even match init.

**Comment by talezion** [comment]
@rogerluan getting the same issue

**Comment by rogerluan** [comment]
> Hey @talezion 👋
> 
> Are you behind a firewall, or proxy?
> I see two major issues there:
> 
> 1. _fastlane_ couldn't check for updates, which probably means your network is filtering connections. If your network is filtering connections, it may be the reason why it couldn't authenticate correctly (permission denied).
> 2. Your version of fastlane is **really** old. Since old fastlane APIs rely on undocumented Apple APIs, you should always be up-to-date with the latest version of _fastlane_ to make sure everything keeps running smoothly.
> 
> Once those 2 issues are resolved, let us know if the problem persists.

@talezion just making sure you didn't miss this reply of mine ☝️ 🙏
