### ISSUE TITLE
pilot builds fails with "The URL path is not valid"

### ISSUE THREAD

**Issue by milkcocoa** [fastlane/fastlane#17821]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When I try to invoke `pilot builds` command with App Store Connect API, I get an error with 'The URL path is not valid'.

It might be the same issue #17283, but since it is the different API, I've posted a new issue.

##### Command executed

```
$ fastlane pilot builds --api_key_path ***
```

##### Complete output when running fastlane, including the stack trace and command used

```
Traceback (most recent call last):
	17: from ~/.anyenv/envs/rbenv/versions/2.7.2/bin/fastlane:23:in `<main>'
	16: from ~/.anyenv/envs/rbenv/versions/2.7.2/bin/fastlane:23:in `load'
	15: from ~/.anyenv/envs/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/bin/fastlane:23:in `<top (required)>'
	14: from ~/.anyenv/envs/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	13: from ~/.anyenv/envs/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/pilot/lib/pilot/commands_generator.rb:18:in `start'
	12: from ~/.anyenv/envs/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/pilot/lib/pilot/commands_generator.rb:166:in `run'
	11: from ~/.anyenv/envs/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	10: from ~/.anyenv/envs/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 9: from ~/.anyenv/envs/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 8: from ~/.anyenv/envs/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 7: from ~/.anyenv/envs/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 6: from ~/.anyenv/envs/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/pilot/lib/pilot/commands_generator.rb:90:in `block (2 levels) in run'
	 5: from ~/.anyenv/envs/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/pilot/lib/pilot/build_manager.rb:183:in `list'
	 4: from ~/.anyenv/envs/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/models/app.rb:360:in `get_build_deliveries'
	 3: from ~/.anyenv/envs/rbenv/versions/2.7.2/lib/ruby/2.7.0/forwardable.rb:235:in `get_build_deliveries'
	 2: from ~/.anyenv/envs/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:374:in `get_build_deliveries'
	 1: from ~/.anyenv/envs/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/api_client.rb:113:in `get'
~/.anyenv/envs/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/api_client.rb:193:in `handle_response': The URL path is not valid - The resource 'buildDeliveries' does not exist (Spaceship::UnexpectedResponse)
	17: from ~/.anyenv/envs/rbenv/versions/2.7.2/bin/fastlane:23:in `<main>'
	16: from ~/.anyenv/envs/rbenv/versions/2.7.2/bin/fastlane:23:in `load'
	15: from ~/.anyenv/envs/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/bin/fastlane:23:in `<top (required)>'
	14: from ~/.anyenv/envs/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	13: from ~/.anyenv/envs/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/pilot/lib/pilot/commands_generator.rb:18:in `start'
	12: from ~/.anyenv/envs/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/pilot/lib/pilot/commands_generator.rb:166:in `run'
	11: from ~/.anyenv/envs/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	10: from ~/.anyenv/envs/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 9: from ~/.anyenv/envs/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 8: from ~/.anyenv/envs/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 7: from ~/.anyenv/envs/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 6: from ~/.anyenv/envs/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/pilot/lib/pilot/commands_generator.rb:90:in `block (2 levels) in run'
	 5: from ~/.anyenv/envs/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/pilot/lib/pilot/build_manager.rb:183:in `list'
	 4: from ~/.anyenv/envs/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/models/app.rb:360:in `get_build_deliveries'
	 3: from ~/.anyenv/envs/rbenv/versions/2.7.2/lib/ruby/2.7.0/forwardable.rb:235:in `get_build_deliveries'
	 2: from ~/.anyenv/envs/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:374:in `get_build_deliveries'
	 1: from ~/.anyenv/envs/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/api_client.rb:113:in `get'
~/.anyenv/envs/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/api_client.rb:193:in `handle_response': \e[31m[!] The URL path is not valid - The resource 'buildDeliveries' does not exist\e[0m (Spaceship::UnexpectedResponse)
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.15.6                                          |
| Ruby                        | 2.7.2                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.24.3 (Apple Git-128)               |
| Installation Source         | ~/.anyenv/envs/rbenv/versions/2.7.2/bin/fastlane |
| Host                        | Mac OS X 10.15.6 (19G2021)                       |
| Ruby Lib Dir                | ~/.anyenv/envs/rbenv/versions/2.7.2/lib          |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                       |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/      |
| Xcode Version               | 12.3                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | ja_JP.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.170.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.4        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.78.1       |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.1.0        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| json                      | 2.3.0        |
| mini_magick               | 4.11.0       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.14.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.4.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 12.3.3       |
| digest-crc                | 0.6.2        |
| google-cloud-storage      | 1.29.2       |
| emoji_regex               | 3.2.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.408.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.110.0      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.86.2       |
| uri                       | 0.10.0       |
| forwardable               | 1.3.1        |
| logger                    | 1.4.2        |
| cgi                       | 0.1.0        |
| timeout                   | 0.1.0        |
| stringio                  | 0.1.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.2.0        |
| strscan                   | 1.0.3        |
| date                      | 3.0.0        |
| delegate                  | 0.1.0        |
| fileutils                 | 1.4.1        |
| io-console                | 0.5.6        |
| zlib                      | 1.1.0        |
| singleton                 | 0.1.0        |
| rexml                     | 3.2.3        |
| open3                     | 0.1.0        |
| yaml                      | 0.1.0        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>

**Comment by davidpaulhunt** [comment]
I am having the same issue but am using `asdf` to manage ruby versions. Upvoting for visibility.

**Comment by roddi** [comment]
Any movement on the issue?

**Comment by tripplilley** [comment]
I had the same issue using the App Store Connect API credentials, but switching back to using plain Apple ID authentication worked.

**Comment by miroslavkovac** [comment]
We are having the same problem and switching back to username+password is no longer an options since Apple enforced 2FA for all accounts.
