### ISSUE TITLE
Fastlane supply --version_codes_to_retain is not working

### ISSUE THREAD

**Issue by henningBunk** [fastlane/fastlane#17822]
### New Issue Checklist

- [x] Updated fastlane to the latest version (1.168.0, no changes regarding supply since than)
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I dropped Android 5 support for newer updates but I want to keep the last version (versioncode=2020212) which supports Android 5 available in the store. Therefore I am executing fastlane supply with the additional `--version_codes_to_retain 2020212`. 

When executed the command finishes with a success message but when I look into the play console no new production release was created.

##### Command executed
```
bundle exec fastlane supply \
    --package_name <package> \
    --metadata_path <path> \
    --track beta \
    --track_promote_to production \
    --rollout 0.2 \
    --release_status inProgress \
    --version_code <version_code_new_update> \
    --version_codes_to_retain <version_code_of_latest_android_5_app>  \
    --json_key ./devcredits.json
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> bundle exec fastlane supply --package_name <package_name> --metadata_path <path> --track beta --track_promote_to production --rollout 0.2 --release_status inProgress --version_code <version_code_new_update> --version_codes_to_retain <version_code_of_latest_android_5_app> --json_key ./devcredits.json

+---------------------------------+--------------------------------------------+
|                          Summary for supply 2.168.0                         |
+---------------------------------+--------------------------------------------+
| package_name                    | <package_name>              |
| metadata_path                   | <path>  |
| track                           | beta                                       |
| track_promote_to                | production                                 |
| rollout                         | 0.2                                        |
| release_status                  | inProgress                                 |
| version_code                    | <version_code_new_update>                                    |
| version_codes_to_retain         | ["<version_code_of_latest_android_5_app>"]                                |
| json_key                        | ./devcredits.json                  |
| skip_upload_apk                 | false                                      |
| skip_upload_aab                 | false                                      |
| skip_upload_metadata            | false                                      |
| skip_upload_changelogs          | false                                      |
| skip_upload_images              | false                                      |
| skip_upload_screenshots         | false                                      |
| validate_only                   | false                                      |
| check_superseded_tracks         | false                                      |
| timeout                         | 300                                        |
| deactivate_on_promote           | true                                       |
| ack_bundle_installation_warning | false                                      |
+---------------------------------+--------------------------------------------+

[15:29:28]: Updating track 'beta'...
[15:29:29]: Preparing to upload for language 'de-DE'...
[15:29:30]: Could not find changelog for '2020212' and language 'de-DE' at path ./fastlane/appName/metadata/android/de-DE/changelogs/2020212.txt...
[15:29:31]: Uploading all changes to Google Play...
[15:29:33]: Successfully finished the upload to Google Play </pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.0.1                                      |
| Ruby                        | 2.7.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.29.2                          |
| Installation Source         | ~/.rvm/gems/ruby-2.7.0/bin/fastlane         |
| Host                        | macOS 11.0.1 (20B29)                        |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.7.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.2                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.168.0 | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.2.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.4.0        |
| executable-hooks                          | 1.6.0        |
| bundler-unload                            | 1.0.2        |
| rubygems-bundler                          | 1.4.5        |
| bundler                                   | 2.2.1        |
| rake                                      | 13.0.1       |
| CFPropertyList                            | 3.0.2        |
| public_suffix                             | 4.0.6        |
| addressable                               | 2.7.0        |
| atomos                                    | 0.1.3        |
| aws-eventstream                           | 1.1.0        |
| aws-partitions                            | 1.399.0      |
| aws-sigv4                                 | 1.2.2        |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.109.3      |
| aws-sdk-kms                               | 1.39.0       |
| aws-sdk-s3                                | 1.85.0       |
| babosa                                    | 1.0.4        |
| claide                                    | 1.0.3        |
| colored                                   | 1.2          |
| colored2                                  | 3.1.2        |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| declarative                               | 0.0.20       |
| declarative-option                        | 0.1.0        |
| digest-crc                                | 0.6.1        |
| unf_ext                                   | 0.0.7.7      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| dotenv                                    | 2.7.6        |
| emoji_regex                               | 3.2.1        |
| excon                                     | 0.78.0       |
| multipart-post                            | 2.0.0        |
| ruby2_keywords                            | 0.0.2        |
| faraday                                   | 1.1.0        |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.0.0        |
| fastimage                                 | 2.2.0        |
| gh_inspector                              | 1.1.3        |
| jwt                                       | 2.2.2        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.1        |
| signet                                    | 0.14.0       |
| googleauth                                | 0.14.0       |
| httpclient                                | 2.8.3        |
| mini_mime                                 | 1.0.2        |
| uber                                      | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| google-api-client                         | 0.38.0       |
| google-cloud-env                          | 1.4.0        |
| google-cloud-errors                       | 1.0.1        |
| google-cloud-core                         | 1.5.0        |
| google-cloud-storage                      | 1.29.1       |
| json                                      | 2.3.1        |
| mini_magick                               | 4.11.0       |
| plist                                     | 3.5.0        |
| rubyzip                                   | 2.3.0        |
| security                                  | 0.1.3        |
| naturally                                 | 2.2.0        |
| simctl                                    | 1.6.8        |
| slack-notifier                            | 2.3.2        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.7.0        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| word_wrap                                 | 1.0.0        |
| nanaimo                                   | 0.3.0        |
| xcodeproj                                 | 1.19.0       |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.0        |
| fastlane-plugin-firebase_app_distribution | 0.2.4        |
</details>

*generated on:* **2020-12-17**
</details>

**Comment by henningBunk** [comment]
Could the missing changelog of the retained version be a reason why the release can not be created?

**Comment by JohnsonKurian1** [comment]
We have been using this for several weeks now and it seems to be going nicely.




[myschoolbucks](https://www.myschoolbucks.us/)
