### ISSUE TITLE
capture_screenshots with testplan does not switch simulator languages

### ISSUE THREAD

**Issue by ilendemli** [fastlane/fastlane#17823]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Scanfile has testplan set with `testplan("testplanname")`
Fastfile calls 
```ruby
derived_data_path = "./DerivedData/"
output_directory = "./screenshots"
devices = [
  "iPhone 12 Pro Max"
]
languages = [
  "de-DE",
  "en-US",
  "fr-FR"
]

run_tests(
  build_for_testing: true,
  code_coverage: false,
  derived_data_path: derived_data_path,
  devices: devices
)

capture_screenshots(
  reinstall_app: true,
  clear_previous_screenshots: true,
  languages: languages,
  devices: devices,
  derived_data_path: derived_data_path,
  test_without_building: true,
  output_directory: output_directory
)
```
Executing this lane triggers the tests but does not change language or region when a testplan is set.
Can't use `scheme` when `testplan` is set either and can't unset `testplan` in this lane to use `scheme`.

##### Command executed

executed custom lane `fastlane create_pr_screenshots`

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                              |
| --------------------------- | -------------------------------------------------- |
| OS                          | 11.1                                               |
| Ruby                        | 2.4.6                                              |
| Bundler?                    | false                                              |
| Git                         | git version 2.24.3 (Apple Git-128)                 |
| Installation Source         | ~/.rvm/gems/ruby-2.4.6/bin/fastlane                |
| Host                        | macOS 11.1 (20C69)                                 |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.6/lib                       |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                        |
| Is contained                | false                                              |
| Is homebrew                 | false                                              |
| Is installed via Fabric.app | false                                              |
| Xcode Path                  | /Applications/Xcode-12.3.0.app/Contents/Developer/ |
| Xcode Version               | 12.3                                               |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.169.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 2.1.4        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| CFPropertyList            | 3.0.2        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday_middleware        | 1.0.0        |
| gh_inspector              | 1.1.3        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| uber                      | 0.1.0        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| signet                    | 0.14.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| nanaimo                   | 0.3.0        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.19.0       |
| public_suffix             | 4.0.6        |
| tty-screen                | 0.8.1        |
| babosa                    | 1.0.4        |
| excon                     | 0.78.0       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.1.0        |
| faraday-cookie_jar        | 0.0.7        |
| fastimage                 | 2.2.0        |
| json                      | 2.3.1        |
| mini_magick               | 4.11.0       |
| dotenv                    | 2.7.6        |
| jwt                       | 2.2.2        |
| declarative               | 0.0.20       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| memoist                   | 0.16.2       |
| googleauth                | 0.14.0       |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-env          | 1.4.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.1       |
| emoji_regex               | 3.2.1        |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-partitions            | 1.402.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.109.3      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.86.0       |
| openssl                   | 2.0.9        |
| io-console                | 0.4.6        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.10      |
| psych                     | 2.2.2        |
</details>

*generated on:* **2020-12-18**
</details>

**Comment by rogerluan** [comment]
Hey @ilendemli 👋 

I didn't know about Test Plans prior to reading your issue, but I'll try to help you 😊 I was reading about Test Plans [here](https://useyourloaf.com/blog/xcode-test-plans/) and [here](https://shashikantjagtap.net/wwdc19-getting-started-with-test-plan-for-xctest/), and turns out Test Plan config file produced by Xcode is a simple json file. In Xcode you can create language configurations, and it would look like the one below:

```js
{
  "configurations" : [
    {
      "id" : "531BA070-1C1F-4027-A28F-31D788835B06",
      "name" : "Configuration 1",
      "options" : {

      }
    }
  ],
  "defaultOptions" : {
    "language" : "pt-BR"
  },
  "testTargets" : [

  ],
  "version" : 1
}
```

Are you expecting your `languages` array to be consumed by fastlane, or are you saying that your `.xctestplan` contains languages preconfigured but they're not being applied? 🤔 

Looking forwarding to hearing from you.

**Comment by ilendemli** [comment]
Hey @rogerluan! 

I didn't know of Test Plas either before working on this project. I created screenshots for other projects using fastlane by providing the devices and languages list before. With this project, there is a testplan set using the Scanfile. So calling ``capture_screenshots` has the testplan set by default. I can't provide the scheme as an argument, as using both scheme and testplan does not work. I can't unset the testplan attribute which is set by the Scanfile in the Fastfile either.

I would like to unset the testplan attribute before running `capture_screenshots`, set the scheme manually and let fastlane consume the languages and devices array.

**Comment by rogerluan** [comment]
Test Plan is a simple json file @ilendemli , so I believe you have two solutions:

a) Delete the `.xctestplan` file you have in your project, then it won't be picked up anymore 😅 
b) Edit your test plan in Xcode to include the desired languages:

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/8419048/102701609-78aa6700-4237-11eb-9eaf-f039a0b697c1.png">

**Comment by ilendemli** [comment]
@rogerluan I can't remove `testplan("testplanname")` from the Scanfile, no permission to do it. I can remove the `.xctestplan` but then I have to use the scheme attribute with `capture_screenshots` which fails because a testplan is defined through Scanfile and I can't use both.

I have edited and added the languages to my testplan, but running `capture_screenshots` here does not capture a screenshot for each language but overrides the last taken screenshot. It is seen as one test by `capture_screenshots` and not a series of tests.

**Comment by rogerluan** [comment]
>no permission to do it.

What do you mean? You don't have permission to modify that file in your organization? 🤔 that seems to be the root cause of the issue here then 😬 can you talk to someone to change that for you?

**Comment by ilendemli** [comment]
It was just my assumption 😅. I might have worded it wrongly here. I will remove the testplan from Scanfile, add it to the needed lanes in Fastfile and create a MR internally.

Anyway there is still this issue with the languages and regions not being applied when using a testplan or is this by design?

**Comment by rogerluan** [comment]
@ilendemli given how Test Plans work, I _believe_ this is intentional. Test Plans declare `languages` and `locale` internally in its `.xctestplan` config file, so this one takes precedence over the ones defined by fastlane (otherwise _fastlane_ would have to edit your `.xctestplan` config file to temporarily disable its language/locale settings, and this doesn't sound any good 🙈 )

**Comment by ilendemli** [comment]
But then the `snapshot` function that is provided by SnapshotHelper should handle the langauges and regions set with Test Plans correctly. Because right now, it overrides the taken snapshot.

**Comment by rogerluan** [comment]
Oh, so your `.xctestplan` config file defines languages and locale, but it's not being picked up?
That doesn't sound right - this should be `xcodebuild`'s responsibility 🤔 The only option related to testplan that xcodebuild receives is `-testplan nameOfTheTestPlan`, and that seems to be being passed correctly.

Can you post the contents of your `.xctestplan` config file here?

**Comment by ilendemli** [comment]
Ok, I think it's easier to showcase the issue using an example project: [exampleProject.zip](https://github.com/fastlane/fastlane/files/5744623/exampleProject.zip)

So executing `fastlane screenshots` passes `["en-US"]` by default. My testplan defines three languages, `en-US`, `de-AT`, and `it-IT`. Test runs for each defined plan and takes a screenshot. Test finishes with the `it-IT` screenshot in the `en-US` folder. no other folders are present.

Do you see and understand the issue i have now? 😅

**Comment by ilendemli** [comment]
@rogerluan have you had time to check my example project?

**Comment by jojost1** [comment]
Any updates? This issue still persists.

**Comment by rogerluan** [comment]
Sorry, haven't had time to dedicate to fastlane anymore lately 😞 I'm gonna reopen this issue so someone knows this is still valid and can be picked up 💪
