### ISSUE TITLE
Fastlane is mostly broken on M1 Big Sur device (after migrating from Mojave)

### ISSUE THREAD

**Issue by alakoring** [fastlane/fastlane#17820]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Fastlane cannot update itself. (I have had other issues, asked https://github.com/fastlane/fastlane/discussions/17788 but got no answer. But this one should cover them all. Basically, fastlane seems to have impossible Ruby dependencies. I was able to install it just fine, and it kind of runs. But almost all of the functionality is broken.

I have a Mac Book Air M1, and copied everything over. When I first ran into problems I tried uninstalling Fastlane and reinstalled.

As you can see below, `fastlane env` doesn’t work. I am running macOS 11.0.1 (20B29), on a new MacBook Air (with 16 GB of RAM).

##### Command executed

fastlane update

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>fastlane update --capture_output
[⠸] 🚀 /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `ensure in take_off': uninitialized constant Fastlane::VERSION (NameError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.170.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
</pre>
</details>

### Environment

<details>
  <pre>% fastlane env
[⠸] 🚀 /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `ensure in take_off': uninitialized constant Fastlane::VERSION (NameError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.170.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
</pre>
</details>

**Comment by alakoring** [comment]
As noted, `fastlane env` doesn’t work. Here is some other info that might help?

% which ruby
/usr/local/opt/ruby@2.4/bin/ruby
% ruby --version
ruby 2.4.9p362 (2019-10-02 revision 67824) [x86_64-darwin18]

**Comment by Dinsen** [comment]
I just tried running `fastlane env` on my brand new MacBook Air M1. (After installing fastlane of course 😄 

Looks good to me?

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.1                                                           |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.1 (20C69)                                             |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Library/Developer/CommandLineTools/                           |
| Xcode Version               |                                                                |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | da_DK.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.171.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.6.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.4        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.78.1       |
| faraday-net_http          | 1.0.0        |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.3.0        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.1        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.11.0       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.1        |
| dotenv                    | 2.7.6        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.14.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.4.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 12.3.2       |
| digest-crc                | 0.6.3        |
| google-cloud-storage      | 1.29.2       |
| emoji_regex               | 3.2.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.414.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.110.0      |
| aws-sdk-kms               | 1.40.0       |
| aws-sdk-s3                | 1.87.0       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| date                      | 2.0.0        |
| stringio                  | 0.0.2        |
| zlib                      | 1.0.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>


*generated on:* **2021-01-12**
</details>

**Comment by alakoring** [comment]
Glad most people aren’t having trouble updating fastlane. Did you migrate from macOS 10.14?

I finally got things working. Not entirely sure how but xcpretty was hardcoded to Ruby 2.3 and version 2.6 was installed. I ended up manually editing xcpretty.

So there is absolutely a dependency problem in Fastlane, I just can’t articulate what it is because I don’t code with Ruby.

**Comment by Dinsen** [comment]
No, it was shipped with macOS 11.1.

**Comment by alakoring** [comment]
And you didn’t copy anything from a previous machine? (I imagine most people will, for a while, and so Fastlane needs to be able to handle this.)

I had a working Fastlane on my 10.14 machine. I use macOS 11 to migrate, at which point Fastlane would no longer work.

**Comment by Dinsen** [comment]
No, a completely clean install.

So it sounds like there can be some issues when coping from another mac.
