### ISSUE TITLE
`error=undefined method `status' for nil:NilClass` while waiting for screenshots to appear

### ISSUE THREAD

**Issue by isaac-weisberg** [fastlane/fastlane#17831]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I have a fully functioning project setup, installed with a 
The `Deliverfile` is configured to only upload screenshots.
The `Snapfile` generates screenshots into proper directory names.
So I `fastlane deliver`, and it mostly succeeds uploading except at some point it gets stuck, occasionally printing:

```
Waiting for screenshots to appear before uploading. This is unlikely to be recovered unless it's 503 error. error="undefined method `status' for nil:NilClass"
```
Is there a way I could possibly disable the behavior or waiting for something and just upload without waiting instead?

##### Command executed

`fastlane deliver`

##### Complete output when running fastlane, including the stack trace and command used

```
[23:39:26]: Uploaded './fastlane/screenshots/en-US/iPhone 8 Plus-03goals.png'... (3.249264 secs)
Waiting for screenshots to appear before uploading. This is unlikely to be recovered unless it's 503 error. error="undefined method `status' for nil:NilClass"
```
The last line is repeated 134 times before I interrupt the execution and put the process out of its misery. 

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.7                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | ~/Projects/BigMoneys/vendor/bundle/ruby/2.6.0/bin/fastlane     |
| Host                        | Mac OS X 10.15.7 (19H2)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.2                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "BigMoneys.xcworkspace", scheme: "BigMoneys")
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("net.caroline.weisberg.Stox") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.170.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 1.17.2       |
| etc                       | 1.0.1        |
| forwardable               | 1.2.0        |
| rake                      | 13.0.2       |
| CFPropertyList            | 3.0.3        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.410.0      |
| aws-sigv4                 | 1.2.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.110.0      |
| aws-sdk-kms               | 1.40.0       |
| aws-sdk-s3                | 1.86.2       |
| babosa                    | 1.0.4        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.3        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.2.1        |
| excon                     | 0.78.1       |
| multipart-post            | 2.0.0        |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.1.0        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.2.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| signet                    | 0.14.0       |
| googleauth                | 0.14.0       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.4.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.2       |
| json                      | 2.4.1        |
| mini_magick               | 4.11.0       |
| plist                     | 3.5.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2020-12-21**
</details> </pre>
</details>

**Comment by isaac-weisberg** [comment]
Well, out of 11 languages times 4 devices times 3 screenshots it left out like 4 images, so I guess it's a no biggie.

**Comment by rogerluan** [comment]
Hey @isaac-weisberg 👋 

Just an idea: https://github.com/fastlane/fastlane/pull/17708 was merged into master but not yet released. It could help fixing your issue (I'm not sure) - ping @ainame 😇 🙈  

Could you try pointing your fastlane gem to master branch, so you can run that PR's code? 😃 

```ruby
gem 'fastlane', :git => 'https://github.com/fastlane/fastlane.git', :branch => 'master'
```

**Comment by isaac-weisberg** [comment]
You know what - I am going to attempt to do exactly this right now.

**Comment by isaac-weisberg** [comment]
So, 20 minutes later, it's safe to say that I don't see the difference. It uploaded 95% of the content and now it's sitting there after 
```
[01:04:31]: Uploaded './fastlane/screenshots/en-US/iPhone 11 Pro Max-01tutorial.png'... (90.478598 secs)
```
and prints
```
Waiting for screenshots to appear before uploading. This is unlikely to be recovered unless it's 503 error. error="undefined method `status' for nil:NilClass"
```
once a minute, repeatedly. I am not going to kill it just yet, will let it run for an hour more.
It did print this message multiple times before for varying amount of repetitions. Sometimes it recovered after 1 print, and sometimes - after 10 of repeated prints.
Maybe I should expect exponential growth of prints required to recover, so I can expect all screenshots to be uploaded by next month :)

**Comment by isaac-weisberg** [comment]
Oooh, something new:
```
[01:18:44]: undefined method `status' for nil:NilClass
[01:18:53]: undefined method `status' for nil:NilClass
```
It was also colored in red! And it was just for 2 lines, after getting back to regular "Waiting for screenshots..." and proceeding as usual.

**Comment by isaac-weisberg** [comment]
Oh, and then:
```
Waiting for screenshots to appear before uploading. This is unlikely to be recovered unless it's 503 error. error="undefined method `status' for nil:NilClass"
[01:23:36]: undefined method `status' for nil:NilClass
[✔] Waiting for all the screenshots processed... 
[01:24:20]: ./fastlane/screenshots/zh-Hans/iPad Pro (12.9-inch) (3rd generation)-01tutorial.png is missing on App Store Connect.
[01:24:20]: ./fastlane/screenshots/zh-Hans/iPad Pro (12.9-inch) (3rd generation)-03goals.png is missing on App Store Connect.
[01:24:20]: ./fastlane/screenshots/zh-Hans/iPhone 11 Pro Max-03goals.png is missing on App Store Connect.
[01:24:20]: ./fastlane/screenshots/de-DE/iPhone 11 Pro Max-02hub.png is missing on App Store Connect.
[01:24:20]: ./fastlane/screenshots/en-US/iPhone 8 Plus-01tutorial.png is missing on App Store Connect.
[01:24:20]: Failed to upload all screenshots... Tries remaining: 4
```
And after that it uploaded the remaining screenshots and it all succeeded. Amazing.

Alright, so maybe, I was just supposed to wait more, even without using the "master"? @rogerluan

**Comment by ainame** [comment]
Hi, I've been working on improving the experience of screenshot uploads in `deliver`👋 Thank you for your reports. 

First of all, I don't think changes in the master branch fixes this issue. I assume it's more like errors in networking (in edge cases) are not well handled. That's why you see "undefined method" error.  

And yes if it's just flakiness/unstableness in networking or App Store Connect API, `deliver` is likely to recover from the issue eventually by retries. It just takes time for a while.

So personally, I would like to improve how `deliver` handles this kind of internal errors to not terrify fastlane users at some point😅

**Comment by ainame** [comment]
>> Waiting for screenshots to appear before uploading. This is unlikely to be recovered unless it's 503 error. error="undefined method `status' for nil:NilClass"
> Is there a way I could possibly disable the behavior or waiting for something and just upload without waiting instead?

In terms of this behaviour, we can't avoid it since the new way to upload assets to App Store Connect requires multiple steps of API calls; to create a placeholder to upload, to actually upload binary data, and to confirm if the upload is done. That log says a "screenshot" object as a placeholder should be created before uploading otherwise nothing can be done.

**Comment by isaac-weisberg** [comment]
Oh dear colleagues, it's been a pleasure to pursue all those discoveries together!
