### ISSUE TITLE
iOS - ARCHIVE SUCCEEDED but  EXPORT FAILED in macOS Big Sur

### ISSUE THREAD

**Issue by Ramprasathselvam** [fastlane/fastlane#17839]
After update macOS Big Sur I'm facing the error.

Action:
 build_app - https://docs.fastlane.tools/actions/build_app/

Error:
 ARCHIVE SUCCEEDED but  EXPORT FAILED in macOS Big Sur

mac OS Version: macos 11.0.1 (Big Sur)
Fastlane Version: 2.170.0

**Comment by williamhqs** [comment]
Just got the same problem.

My error is 

```
 error: exportArchive: test1.framework does not support provisioning profiles.
        
        Error Domain=IDEProvisioningErrorDomain Code=10 "test1.framework does 
not support provisioning profiles." UserInfo={IDEDistributionIssueSeverity=3, 
    NSLocalizedDescription= test1.framework does not support provisioning profiles.,
     NSLocalizedRecoverySuggestion= test1.framework does not 
support provisioning profiles, but provisioning profile PROFILE_TEST1 has been manually specified. 
Remove this item from the "provisioningProfiles" dictionary in your Export Options property list.}
```

I think the solution is set profile to `None` for the framework target.

But I got this:

 **▸ Archive Succeeded
[19:03:09]: Generated plist file with the following values:
[19:03:09]: ▸ -----------------------------------------
[19:03:09]: ▸ {
[19:03:09]: ▸   "provisioningProfiles": {
[19:03:09]: ▸     "com.xxx.test1": "PROFILE_TEST1"
[19:03:09]: ▸   },
[19:03:09]: ▸   "method": "enterprise",
[19:03:09]: ▸   "signingStyle": "manual"
[19:03:09]: ▸ }
[19:03:09]: ▸ -----------------------------------------**


And I found the plist in the location here mentioned:

/usr/bin/xcrun /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.163.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/9l/ww84z3l963378knhd2qdd2180000gp/T/gym_config20201222-84378-2962cg.plist' -archivePath /Users/william/Library/Developer/Xcode/Archives/2020-12-22/ATP\ Chaos\ 2020-12-22\ 19.01.55.xcarchive -exportPath '/var/folders/9l/ww84z3l963378knhd2qdd2180000gp/T/gym_output20201222-84378-twktum'

And this is the plist

```

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>method</key>
	<string>enterprise</string>
	<key>provisioningProfiles</key>
	<dict>
		<key>com.xxx.test1</key>
		<string>PROFILE_TEST1</string>
	</dict>
	<key>signingStyle</key>
	<string>manual</string>
</dict>
</plist>


```

Here is my **FastFile**,
```

lane :beta do |options|

    name = get_provisioning_profile(
      force: false,
      app_identifier: "com.xxx.test1",
      filename: "PROFILE_test1.mobileprovision")
    

    update_app_identifier(
      xcodeproj: "MyProject.xcodeproj",
      plist_path: "./mainInfo.plist", 
      app_identifier: "com.xxx.test1"
    )


    //Is this update_project_provisioning issue? I thought this line 
    //only setup my com.xxx.test1 to profile PROFILE_TEST1, correct?

    update_project_provisioning(xcodeproj: "MyProject.xcodeproj")



    build_app(
      workspace: "MyProject.xcworkspace", 
      output_directory: "./OutputFile",
      xcconfig: xcconfigPath,
        export_method: "enterprise",
        scheme: "MyProject"
      )

  end
```

Thanks for any help!

**Comment by williamhqs** [comment]
**UPDATE**
If I remove `xcconfig` option then the error gone. Seems xcconfig will be applied on all the schemes?

**Comment by rogerluan** [comment]
@Ramprasathselvam please provide all the info asked by [the issue template](https://raw.githubusercontent.com/fastlane/fastlane/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md) otherwise we can't help you.

Can you also try @williamhqs 's fix, and see if it works for you too? 🙏

**Comment by Ramprasathselvam** [comment]
I'm just updated build_app action in fastfile.
 ```
build_app(
  workspace: "Fastlane Setup.xcworkspace",
  configuration: "Debug",
  scheme: "Fastlane Setup",
  silent: true,
  clean: true, 
  output_name: "Fastlane_Setup.ipa",
 )
```
to 

```
build_app(
    export_method: "development"
  )
```
