### ISSUE TITLE
The request could not be completed because: (Spaceship::InternalServerError) 	Server error got 500

### ISSUE THREAD

**Issue by nservidio** [fastlane/fastlane#17838]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Hello!

Love fastlane, thanks so much for making this tool! Everything is working great except deliver is failing at the last second with a 500 error.

We still have an `apple_id` listed in our Appfile even though we switched to using `app_store_connect_api_key` recently. Not sure if that could be affecting things.

Anyways, the build uploads to App Store Connect fine but the submit button doesn't get pressed.

Please let me know if you have any questions!

##### Command executed

deliver(
      app: ENV['MY_APP_ID'],
      submit_for_review: true,
      phased_release: true,
      automatic_release: false,
      skip_screenshots: true,
      force: true,
      app_version: ENV['MY_VERSION'],
      precheck_include_in_app_purchases: false,
      submission_information: {
	     add_id_info_limits_tracking: true,
	     add_id_info_serves_ads: false,
	     add_id_info_tracks_action: false,
	     add_id_info_tracks_install: true,
	     add_id_info_uses_idfa: true,
	     content_rights_contains_third_party_content: false,
	     content_rights_has_rights: false,
	     export_compliance_uses_encryption: false,
	     export_compliance_encryption_updated: false
      }
    )

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
INFO [2020-12-22 00:10:08.96]: Successfully finished processing the build x.x.x - 12345 for IOS
INFO [2020-12-22 00:10:08.96]: Selecting build x.x.x (12345)...
INFO [2020-12-22 00:10:10.21]: Successfully selected build
DEBUG [2020-12-22 00:10:10.21]: Updating build for export compliance status of 'false'
DEBUG [2020-12-22 00:10:10.59]: Successfully updated build for export compliance status of 'false' on App Store Connect
Timeout received! Retrying after 3 seconds (remaining: 5)...
Timeout received! Retrying after 3 seconds (remaining: 4)...
Timeout received! Retrying after 3 seconds (remaining: 3)...
Timeout received! Retrying after 3 seconds (remaining: 2)...
Timeout received! Retrying after 3 seconds (remaining: 1)...
DEBUG [2020-12-22 00:10:14.43]: Updating app store version for IDFA status of 'true'
DEBUG [2020-12-22 00:10:14.94]: Updated app store version for IDFA status of 'true'
DEBUG [2020-12-22 00:10:14.94]: Creating IDFA declaration
DEBUG [2020-12-22 00:10:15.39]: Created IDFA declaration
INFO [2020-12-22 00:10:15.39]: Successfully updated IDFA declarations on App Store Connect
DEBUG [2020-12-22 00:10:15.39]: Updating contents rights declaration on App Store Connect
Timeout received! Retrying after 3 seconds (remaining: 5)...
Timeout received! Retrying after 3 seconds (remaining: 4)...
Timeout received! Retrying after 3 seconds (remaining: 3)...
Timeout received! Retrying after 3 seconds (remaining: 2)...
Timeout received! Retrying after 3 seconds (remaining: 1)...
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
...
ERROR [2020-12-22 00:10:17.70]: Server error got 500
...
Traceback (most recent call last):
	35: from /Users/distiller/.gem/ruby/2.7.2/bin/fastlane:23:in `<main>'
	34: from /Users/distiller/.gem/ruby/2.7.2/bin/fastlane:23:in `load'
	33: from /Users/distiller/.gem/ruby/2.7.2/gems/fastlane-2.170.0/bin/fastlane:23:in `<top (required)>'
	32: from /Users/distiller/.gem/ruby/2.7.2/gems/fastlane-2.170.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	31: from /Users/distiller/.gem/ruby/2.7.2/gems/fastlane-2.170.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	30: from /Users/distiller/.gem/ruby/2.7.2/gems/fastlane-2.170.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	29: from /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	28: from /Users/distiller/.gem/ruby/2.7.2/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	27: from /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	26: from /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	25: from /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	24: from /Users/distiller/.gem/ruby/2.7.2/gems/fastlane-2.170.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	23: from /Users/distiller/.gem/ruby/2.7.2/gems/fastlane-2.170.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	22: from /Users/distiller/.gem/ruby/2.7.2/gems/fastlane-2.170.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	21: from /Users/distiller/.gem/ruby/2.7.2/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	20: from /Users/distiller/.gem/ruby/2.7.2/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	19: from /Users/distiller/.gem/ruby/2.7.2/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	18: from /Users/distiller/.gem/ruby/2.7.2/gems/fastlane-2.170.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	17: from Fastfile:74:in `block (2 levels) in parsing_binding'
	16: from /Users/distiller/.gem/ruby/2.7.2/gems/fastlane-2.170.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	15: from /Users/distiller/.gem/ruby/2.7.2/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	14: from /Users/distiller/.gem/ruby/2.7.2/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	13: from /Users/distiller/.gem/ruby/2.7.2/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	12: from /Users/distiller/.gem/ruby/2.7.2/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	11: from /Users/distiller/.gem/ruby/2.7.2/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	10: from /Users/distiller/.gem/ruby/2.7.2/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 9: from /Users/distiller/.gem/ruby/2.7.2/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:18:in `run'
	 8: from /Users/distiller/.gem/ruby/2.7.2/gems/fastlane-2.170.0/deliver/lib/deliver/runner.rb:64:in `run'
	 7: from /Users/distiller/.gem/ruby/2.7.2/gems/fastlane-2.170.0/deliver/lib/deliver/runner.rb:194:in `submit_for_review'
	 6: from /Users/distiller/.gem/ruby/2.7.2/gems/fastlane-2.170.0/deliver/lib/deliver/submit_for_review.rb:24:in `submit!'
	 5: from /Users/distiller/.gem/ruby/2.7.2/gems/fastlane-2.170.0/deliver/lib/deliver/submit_for_review.rb:178:in `update_submission_information'
	 4: from /Users/distiller/.gem/ruby/2.7.2/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/models/app.rb:106:in `update'
	 3: from /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/2.7.0/forwardable.rb:235:in `patch_app'
	 2: from /Users/distiller/.gem/ruby/2.7.2/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:200:in `patch_app'
	 1: from /Users/distiller/.gem/ruby/2.7.2/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/api_client.rb:135:in `patch'
/Users/distiller/.gem/ruby/2.7.2/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/api_client.rb:185:in `handle_response': \e[31m[!] The request could not be completed because: (Spaceship::InternalServerError)
	Server error got 500\e[0m

Exited with code exit status 1
 </pre>
</details>

### Environment

<details>
  <pre> 
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                    |
| --------------------------- | -------------------------------------------------------- |
| OS                          | 10.15.5                                                  |
| Ruby                        | 2.7.2                                                    |
| Bundler?                    | false                                                    |
| Git                         | git version 2.29.0                                       |
| Installation Source         | ~/.gem/ruby/2.7.2/bin/fastlane                           |
| Host                        | Mac OS X 10.15.5 (19F101)                                |
| Ruby Lib Dir                | ~/.rubies/ruby-2.7.2/lib                                 |
| OpenSSL Version             | OpenSSL 1.1.1h  22 Sep 2020                              |
| Is contained                | false                                                    |
| Is homebrew                 | false                                                    |
| Is installed via Fabric.app | false                                                    |
| Xcode Path                  | /Applications/Xcode-12.1.GM.seed.app/Contents/Developer/ |
| Xcode Version               | 12.1                                                     |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.170.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.4        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.78.0       |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.1.0        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.14.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.4.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-storage      | 1.29.1       |
| emoji_regex               | 3.0.0        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.384.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.109.1      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.83.1       |
| uri                       | 0.10.0       |
| forwardable               | 1.3.1        |
| logger                    | 1.4.2        |
| cgi                       | 0.1.0        |
| timeout                   | 0.1.0        |
| stringio                  | 0.1.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.2.0        |
| strscan                   | 1.0.3        |
| date                      | 3.0.0        |
| delegate                  | 0.1.0        |
| fileutils                 | 1.4.1        |
| io-console                | 0.5.6        |
| zlib                      | 1.1.0        |
| singleton                 | 0.1.0        |
| rexml                     | 3.2.3        |
| open3                     | 0.1.0        |
| yaml                      | 0.1.0        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.6.0        |
</details>

*generated on:* **2020-12-22**
</details>
</pre>
</details>

**Comment by nservidio** [comment]
It seems to work if I remove these two lines:
```
	     content_rights_contains_third_party_content: false,
	     content_rights_has_rights: false,
```

**Comment by rogerluan** [comment]
Did you resolve this issue @nservidio ?

**Comment by nservidio** [comment]
Hi, I seemed to have resolved it for now. However could we update [this](https://docs.fastlane.tools/actions/deliver/#compliance-and-idfa-settings) to point to a new [example](https://github.com/artsy/eigen/blob/faa02e2746194d8d7c11899474de9c517435eca4/fastlane/Fastfile#L131-L149) that doesn't include:

**Comment by max-ott** [comment]
Feel free to open a pull request to change the link in the docs.
