### ISSUE TITLE
Server error  503 despite successful upload to TestFlight

### ISSUE THREAD

**Issue by ashish-naik** [fastlane/fastlane#17858]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I have successfully uploaded build to TestFlight many times but started getting error 503 today.

I have not made any modification to the lane.

What i have tried

 1. Restarted laptop
 2. Quit terminal and restarted in case iTunes session needs relogin
 3. Apple system status all green

below is stripped down relevant output of lane

 ```
   Login to App Store Connect (na@gmail.com)
     Login successful
     Ready to upload new build to TestFlight (App: 1540088973)...
     Going to upload updated app to App Store Connect
     This might take a few minutes. Please don't interrupt the script.
     iTunes Transporter successfully finished its job
     ------------------------------------------------------------------------------------------------------------------
     --- Successfully uploaded package to App Store Connect. It might take a few minutes until it's visible online. ---
     ------------------------------------------------------------------------------------------------------------------
     Successfully uploaded the new binary to App Store Connect
     If you want to skip waiting for the processing to be finished, use the `skip_waiting_for_build_processing` option
     Note that if `skip_waiting_for_build_processing` is used but a `changelog` is supplied, this process will wait for the build to appear on AppStoreConnect, update the changelog and then skip the remaining of the processing steps.
     Waiting for processing on... app_id: 1540088973, app_version: , build_version:, platform: IOS
     Read more information on why this build isn't showing up yet - https://github.com/fastlane/fastlane/issues/14997
     Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
     Waiting for App Store Connect to finish processing the new build () for IOS
     Successfully finished processing the build  for IOS
     Successfully set the changelog for build
     Distributing new build to testers:


```
fastlane environment

  ```
  ### Captured Output
    
    Command Used: `--capture_output`
    <details><summary>Output/Log</summary>
    
    ```
    
    DEBUG [2020-12-25 22:18:12.78]: Checking if there are any plugins that should be loaded...
    DEBUG [2020-12-25 22:18:12.79]: Loading 'fastlane-plugin-versioning' plugin
    INFO [2020-12-25 22:18:12.79]: gem 'fastlane-plugin-versioning' is already installed
    DEBUG [2020-12-25 22:18:12.80]: Loading 'fastlane-plugin-badge' plugin
    INFO [2020-12-25 22:18:12.80]: gem 'fastlane-plugin-badge' is already installed
    DEBUG [2020-12-25 22:18:12.81]: Loading 'fastlane-plugin-firebase_app_distribution' plugin
    INFO [2020-12-25 22:18:12.81]: gem 'fastlane-plugin-firebase_app_distribution' is already installed
    
    
    ```
    
    </details>
    
    <details><summary>🚫 fastlane environment 🚫</summary>
    
    ### Stack
    
    | Key                         | Value                                       |
    | --------------------------- | ------------------------------------------- |
    | OS                          | 11.1                                        |
    | Ruby                        | 2.6.4                                       |
    | Bundler?                    | true                                        |
    | Git                         | git version 2.24.3 (Apple Git-128)          |
    | Installation Source         | ~/.rbenv/versions/2.6.4/bin/fastlane        |
    | Host                        | macOS 11.1 (20C69)                          |
    | Ruby Lib Dir                | ~/.rbenv/versions/2.6.4/lib                 |
    | OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
    | Is contained                | false                                       |
    | Is homebrew                 | false                                       |
    | Is installed via Fabric.app | false                                       |
    | Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
    | Xcode Version               | 12.3                                        |
    
    
    ### System Locale
    
    | Error                       |
    | --------------------------- |
    | No Locale with UTF8 found 🚫 |
    
    
    ### fastlane files:
    
    <details><summary>`./fastlane/Fastfile`</summary>
    
    ```ruby
    
    	lane :bump_version do |options|
    
    		increment_build_number_in_plist(target:  'app')
    		increment_build_number_in_plist(target:  'aptest')
    
    		increment_version_number(
    				bump_type: 'minor' # Automatically increment minor version number
    		)
    
    	end
    
    	# Lane to upload dsysms file to Crashlysitcs. 
    	lane :upload_dsyms do |options|
    		
    		scheme = options[:scheme]
    		if scheme == ""  or scheme == nil
    			UI.important "❌❌❌❌❌ No scheme provided so skipping uploading dsym to Firebase ❌❌❌❌❌"
    		else 		
    			gspPath = "./Source/Configs/Firebase/GoogleService-Info-#{scheme}.plist"
    			puts "Google services plisy file path - #{gspPath}"
    
    			upload_symbols_to_crashlytics(gsp_path: gspPath)
    		end
    	end
    
    
    
      
    
      lane :testflight_beta do |options|
    
    	bump_version
    
    
    	match(type: "appstore", app_identifier: ["bundle id"])
    	
    	notification(title: "Fastlane TestFlight Lane", message: "Match complete",app_icon: ENV['ICON_PATH'])
    
    
    	build_app(
    
    		export_method: "app-store",
    		configuration: "Test",
    		scheme: "Test",
    		export_options: {
    			signingStyle: "automatic",
    			provisioningProfiles: {
    			"bundle id" => "match AppStore "bundle id"
    			}
        	},
    		export_xcargs: "-allowProvisioningUpdates"
      )
    
      	notification(title: "Fastlane TestFlight Lane", message: "Build finished",app_icon: ENV['ICON_PATH'])
    
    	upload_to_testflight(
    		username: "na@gmail.com",
    		beta_app_feedback_email: "na@email.com",
    		beta_app_description: "",
    		demo_account_required: true,
    		notify_external_testers: false,
    		changelog: "Some bug fixes and UI improvements.",
    		beta_app_review_info: {
    			contact_email: "n@gmail.com",
    			contact_first_name: "A",
    			contact_last_name: "N",
    			contact_phone: "",
    			demo_account_name: "a@a.com",
    			demo_account_password: "dummy",
    			notes: 
    "Email based login
    - User Name - a@outlook.com"
    		},
    		testers_file_path: "./all_testers_export.csv",
    		groups: "Internal, Family",
    		expire_previous_builds: true,
    		localized_app_info: {
    			"default": {
    				feedback_email: "a@a.com",
    				marketing_url: "",
    				privacy_policy_url: "https://....",
    				description: ".....",
    			},
    		}	
    	)
    
    	notification(title: "Fastlane TestFlight Lane", message: "Upload to AppStore done",sound: "Crystal", app_icon: ENV['ICON_PATH'])
    
    	# Upload dSYS file to Crashlysitcs
    	upload_dsyms(scheme:"Test")
    
    	notification(title: "Fastlane TestFlight Lane", message: "Upload to Crashlytics done",sound: "Magic Bell",app_icon: ENV['ICON_PATH'])
      end
      
    
    
    
    end
    
    ```
    </details>
    
    **No Appfile found**
    
    
    ### fastlane gems
    
    | Gem      | Version | Update-Status |
    | -------- | ------- | ------------- |
    | fastlane | 2.170.0 | ✅ Up-To-Date  |
    
    
    ### Loaded fastlane plugins:
    
    | Plugin                                    | Version | Update-Status |
    | ----------------------------------------- | ------- | ------------- |
    | fastlane-plugin-versioning                | 0.4.4   | ✅ Up-To-Date  |
    | fastlane-plugin-badge                     | 1.4.0   | ✅ Up-To-Date  |
    | fastlane-plugin-firebase_app_distribution | 0.2.4   | ✅ Up-To-Date  |
    
    
    <details><summary><b>Loaded gems</b></summary>
    
    | Gem                                       | Version      |
    | ----------------------------------------- | ------------ |
    | bundler                                   | 1.17.2       |
    | etc                                       | 1.0.1        |
    | forwardable                               | 1.2.0        |
    | rake                                      | 12.3.3       |
    | CFPropertyList                            | 3.0.3        |
    | public_suffix                             | 4.0.6        |
    | addressable                               | 2.7.0        |
    | atomos                                    | 0.1.3        |
    | aws-eventstream                           | 1.1.0        |
    | aws-partitions                            | 1.402.0      |
    | aws-sigv4                                 | 1.2.2        |
    | jmespath                                  | 1.4.0        |
    | aws-sdk-core                              | 3.110.0      |
    | aws-sdk-kms                               | 1.39.0       |
    | aws-sdk-s3                                | 1.86.0       |
    | babosa                                    | 1.0.4        |
    | curb                                      | 0.9.10       |
    | fastimage                                 | 2.2.0        |
    | colored                                   | 1.2          |
    | highline                                  | 1.7.10       |
    | commander-fastlane                        | 4.4.6        |
    | dotenv                                    | 2.7.6        |
    | emoji_regex                               | 3.2.1        |
    | excon                                     | 0.78.1       |
    | multipart-post                            | 2.0.0        |
    | ruby2_keywords                            | 0.0.2        |
    | faraday                                   | 1.1.0        |
    | unf_ext                                   | 0.0.7.7      |
    | unf                                       | 0.1.4        |
    | domain_name                               | 0.5.20190701 |
    | http-cookie                               | 1.0.3        |
    | faraday-cookie_jar                        | 0.0.7        |
    | faraday_middleware                        | 1.0.0        |
    | gh_inspector                              | 1.1.3        |
    | jwt                                       | 2.2.2        |
    | memoist                                   | 0.16.2       |
    | multi_json                                | 1.15.0       |
    | os                                        | 1.1.1        |
    | signet                                    | 0.14.0       |
    | googleauth                                | 0.14.0       |
    | httpclient                                | 2.8.3        |
    | mini_mime                                 | 1.0.2        |
    | declarative                               | 0.0.20       |
    | declarative-option                        | 0.1.0        |
    | uber                                      | 0.1.0        |
    | representable                             | 3.0.4        |
    | retriable                                 | 3.1.2        |
    | google-api-client                         | 0.38.0       |
    | digest-crc                                | 0.6.2        |
    | google-cloud-env                          | 1.4.0        |
    | google-cloud-errors                       | 1.0.1        |
    | google-cloud-core                         | 1.5.0        |
    | google-cloud-storage                      | 1.29.1       |
    | json                                      | 2.3.1        |
    | mini_magick                               | 4.11.0       |
    | plist                                     | 3.5.0        |
    | rubyzip                                   | 2.3.0        |
    | security                                  | 0.1.3        |
    | naturally                                 | 2.2.0        |
    | simctl                                    | 1.6.8        |
    | slack-notifier                            | 2.3.2        |
    | terminal-notifier                         | 2.0.0        |
    | unicode-display_width                     | 1.7.0        |
    | terminal-table                            | 1.8.0        |
    | tty-screen                                | 0.8.1        |
    | tty-cursor                                | 0.7.1        |
    | tty-spinner                               | 0.9.3        |
    | word_wrap                                 | 1.0.0        |
    | claide                                    | 1.0.3        |
    | colored2                                  | 3.1.2        |
    | nanaimo                                   | 0.3.0        |
    | xcodeproj                                 | 1.19.0       |
    | rouge                                     | 2.0.7        |
    | xcpretty                                  | 0.3.0        |
    | xcpretty-travis-formatter                 | 1.0.0        |
    | badge                                     | 0.12.0       |
    | fastlane-plugin-badge                     | 1.4.0        |
    | fastlane-plugin-firebase_app_distribution | 0.2.4        |
    | fastlane-plugin-versioning                | 0.4.4        |
    </details>
    
    
    *generated on:* **2020-12-25**
    </details>

```

**Comment by minuscorp** [comment]
App uploads are not available during holidays, Apple's policy 🙃

**Comment by ashish-naik** [comment]
Oh! I thought servers would be working over holidays but time for some rest then 😀 thanks.
