### ISSUE TITLE
Cannot use latest SwiftLint with CodeClimate reporter

### ISSUE THREAD

**Issue by bdolewski** [fastlane/fastlane#17855]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
The latest version of `swiftlint` which is version `0.42.0` can support new type of reporter which is CodeClimate. CodeClimate is the engine used by GitLab to generate data for its widgets about code quality.

I can run locally `swiftlint --reporter codeclimate` with proper results. However when I use that inside `Fastfile` then fastlane complains that reporter `codeclimate` is not recognized.

##### Command executed
*Fastfile*

```ruby
  lane :lint do
    swiftlint(
      reporter: "codeclimate",
      output_file: "fastlane/codequality_report.json"
    )
  end
```

*Installed SwiftLint:*

```
➜  ~ swiftlint version
0.42.0
➜  ~ 
```

*Fastlane command*
```
fastlane lint
```
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> -------
INFO [2020-12-25 00:24:36.74]: ------------------------------
INFO [2020-12-25 00:24:36.74]: --- Step: default_platform ---
INFO [2020-12-25 00:24:36.74]: ------------------------------
INFO [2020-12-25 00:24:36.74]: Driving the lane 'ios lint' 🚀
ERROR [2020-12-25 00:24:36.74]: Error setting value 'codeclimate' for option 'reporter'
ERROR [2020-12-25 00:24:36.74]: You passed invalid parameters to 'swiftlint'.
ERROR [2020-12-25 00:24:36.74]: Check out the error below and available options by running `fastlane action swiftlint`
WARN [2020-12-25 00:24:36.74]: Lane Context:
INFO [2020-12-25 00:24:36.74]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios lint"}
ERROR [2020-12-25 00:24:36.74]: Available values are 'xcode', 'json', 'csv', 'checkstyle', 'junit', 'html', 'emoji', 'sonarqube', 'markdown', 'github-actions-logging'
INFO [2020-12-25 00:24:36.74]: Successfully generated documentation at path '/Users/bartoszdolewski/Development/Fieldcode/fma-ios-client/fastlane/README.md'

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
+------+------------------+-------------+

ERROR [2020-12-25 00:24:36.76]: fastlane finished with errors
Traceback (most recent call last):
	35: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/bin/fastlane:23:in `<main>'
	34: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/bin/fastlane:23:in `load'
	33: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/bin/fastlane:23:in `<top (required)>'
	32: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	31: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	30: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	29: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	28: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	27: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	26: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	25: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	24: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	23: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	22: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	21: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	20: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	19: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	18: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	17: from Fastfile:43:in `block (2 levels) in parsing_binding'
	16: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	15: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	14: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	13: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	12: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:239:in `block in execute_action'
	11: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane/lib/fastlane/configuration_helper.rb:8:in `parse'
	10: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:36:in `create'
	 9: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:36:in `new'
	 8: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:66:in `initialize'
	 7: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:82:in `verify_value_exists'
	 6: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:82:in `each'
	 5: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:87:in `block in verify_value_exists'
	 4: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/configuration/config_item.rb:182:in `verify!'
	 3: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/configuration/config_item.rb:221:in `valid?'
	 2: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/swiftlint.rb:148:in `block in available_options'
	 1: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': Available values are 'xcode', 'json', 'csv', 'checkstyle', 'junit', 'html', 'emoji', 'sonarqube', 'markdown', 'github-actions-logging' (FastlaneCore::Interface::FastlaneError)
	33: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/bin/fastlane:23:in `<main>'
	32: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/bin/fastlane:23:in `load'
	31: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/bin/fastlane:23:in `<top (required)>'
	30: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	29: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	28: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	27: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	26: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	25: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	24: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	23: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	22: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	21: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	20: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	19: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	18: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	17: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	16: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	15: from Fastfile:43:in `block (2 levels) in parsing_binding'
	14: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	13: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	12: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	11: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	10: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:239:in `block in execute_action'
	 9: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane/lib/fastlane/configuration_helper.rb:8:in `parse'
	 8: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:36:in `create'
	 7: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:36:in `new'
	 6: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:66:in `initialize'
	 5: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:82:in `verify_value_exists'
	 4: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:82:in `each'
	 3: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:87:in `block in verify_value_exists'
	 2: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/configuration/config_item.rb:182:in `verify!'
	 1: from /opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/configuration/config_item.rb:220:in `valid?'
/opt/homebrew/Cellar/fastlane/2.170.0/libexec/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/configuration/config_item.rb:224:in `rescue in valid?': \e[31m[!] Available values are 'xcode', 'json', 'csv', 'checkstyle', 'junit', 'html', 'emoji', 'sonarqube', 'markdown', 'github-actions-logging'\e[0m (FastlaneCore::Interface::FastlaneError)
 </pre>
</details>

### Environment

<details>
  <pre> 
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 11.1                                                       |
| Ruby                        | 2.7.2                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.29.2                                         |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.170.0/libexec/bin/fastlane |
| Host                        | macOS 11.1 (20C69)                                         |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/2.7.2/lib                        |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                                 |
| Is contained                | false                                                      |
| Is homebrew                 | true                                                       |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
| Xcode Version               | 12.3                                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | pl_PL.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

</details>

</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.170.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.4        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.78.1       |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.1.0        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| json                      | 2.3.0        |
| mini_magick               | 4.11.0       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.14.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.4.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.3       |
| digest-crc                | 0.6.3        |
| google-cloud-storage      | 1.29.2       |
| emoji_regex               | 3.2.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.411.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.110.0      |
| aws-sdk-kms               | 1.40.0       |
| aws-sdk-s3                | 1.87.0       |
| uri                       | 0.10.0       |
| forwardable               | 1.3.1        |
| logger                    | 1.4.2        |
| cgi                       | 0.1.0        |
| timeout                   | 0.1.0        |
| stringio                  | 0.1.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.2.0        |
| strscan                   | 1.0.3        |
| date                      | 3.0.0        |
| delegate                  | 0.1.0        |
| fileutils                 | 1.4.1        |
| io-console                | 0.5.6        |
| zlib                      | 1.1.0        |
| singleton                 | 0.1.0        |
| rexml                     | 3.2.3        |
| open3                     | 0.1.0        |
| yaml                      | 0.1.0        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>

*generated on:* **2020-12-25**
</details>

  </pre>
</details>

**Comment by bdolewski** [comment]
Does fastlane uses SwiftLint installed on system (for example via Homebrew and available in PATH) or it uses it differently? Looks like fastlane fails because it cannot recognize new command line parameter for SwiftLint but I can pass the same parameter simply in command line like `Swiftlint --reporter codeclimate`

**Comment by rogerluan** [comment]
Hey @bdolewski 👋 

It uses your system's swiftlint 👍 I found the root cause of the problem you're facing and I'm opening a PR to fix it 😊

**Comment by rogerluan** [comment]
Here: https://github.com/fastlane/fastlane/pull/17935

It should work for you now!

**Comment by bdolewski** [comment]
I just installed Fastlane 2.172 and I think thing bug is still present unfortunately.

My `Fastfile` hasn't changed since first post.
This is the current output in console:

```
[✔] 🚀 
[08:25:29]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[08:25:31]: ------------------------------
[08:25:31]: --- Step: default_platform ---
[08:25:31]: ------------------------------
[08:25:31]: Driving the lane 'ios lint' 🚀
[08:25:31]: Error setting value 'codequality' for option 'reporter'
[08:25:31]: You passed invalid parameters to 'swiftlint'.
[08:25:31]: Check out the error below and available options by running `fastlane action swiftlint`
+------------------+----------+
|        Lane Context         |
+------------------+----------+
| DEFAULT_PLATFORM | ios      |
| PLATFORM_NAME    | ios      |
| LANE_NAME        | ios lint |
+------------------+----------+
[08:25:31]: Unknown method 'warning', supported [:interactive?, :user_error!, :verbose, :important, :command_output, :command, :error, :success, :content_error, :password, :select, :crash!, :input, :not_implemented, :shell_error!, :build_failure!, :deprecated, :test_failure!, :confirm, :abort_with_message!, :header, :message]

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
+------+------------------+-------------+

[08:25:31]: fastlane finished with errors

[!] Unknown method 'warning', supported [:interactive?, :user_error!, :verbose, :important, :command_output, :command, :error, :success, :content_error, :password, :select, :crash!, :input, :not_implemented, :shell_error!, :build_failure!, :deprecated, :test_failure!, :confirm, :abort_with_message!, :header, :message]

```
