### ISSUE TITLE
Provisioning profile not found

### ISSUE THREAD

**Issue by abouroubi** [fastlane/fastlane#17859]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm using match to sync my certs and provisioning profiles, but after an update of my provisioning profile I have this error:
```
[17:56:14]: No matching provisioning profiles found for 'AdHoc_ai.app.dev.mobileprovision'
[17:56:14]: A new one cannot be created because you enabled `readonly`
[17:56:14]: Provisioning profiles in your repo for type `adhoc`:
[17:56:14]: - 'AdHoc_ai.app.dev.mobileprovision'
[17:56:14]: If you are certain that a profile should exist, double-check the recent changes to your match repository
```

The name it's looking for is clearly present, why I have this error ?

##### Command executed

`fastlane beta`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.1                                        |
| Ruby                        | 2.6.6                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.29.2                          |
| Installation Source         | ~/.rbenv/versions/2.6.6/bin/fastlane        |
| Host                        | macOS 11.1 (20C69)                          |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.6/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.3                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | fr_FR.UTF-8 | ✅ |
| LC_ALL   | fr_FR.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Build the app"
  lane :build_dev do

    setup_ci

    cocoapods

    update_configs

    match(app_identifier: ["ai.app.dev"], readonly: is_ci, force: true)

    build_app(workspace: "App.xcworkspace", scheme: "App", configuration: "Debug-Production")

  end

  desc "Deploy a beta version of the app to Firebase Beta"
  lane :beta do

    setup_ci

    update_build_number

    update_configs

    cocoapods

    match(app_identifier: ["ai.app.dev"], readonly: true)

    build_app(workspace: "App.xcworkspace", scheme: "App", configuration: "Debug-Production")

    firebase_app_distribution(app: ENV["FIREBASE_GOOGLE_APP_ID"], debug: true, firebase_cli_token: ENV["FIREBASE_CI_TOKEN"])

  end

  desc "Deploy a version to the App store"
  lane :release do

    setup_ci

    update_build_number

    update_configs

    cocoapods

    match(type: "appstore", app_identifier: ["ai.app"], readonly: true)

    build_app(workspace: "App.xcworkspace", scheme: "App", configuration: "Release-Production")

    # TODO: Add deployement step
  end

  private_lane :print_env do 
    result = "Env vars:\n"
    
    ENV.each { |name, value| result += "#{name} is #{value}\n" }

    puts(result)
    
  end

  desc "Incrment build number"
  private_lane :update_build_number do 
    
    ensure_git_status_clean
    
    increment_build_number

    commit_version_bump(message: "[skip ci] CI increment build number to: #{lane_context[SharedValues::BUILD_NUMBER]}")

    push_to_git_remote
    
  end

  desc "Update config files with values from env vars"
  private_lane :update_configs do
    update_plist(
      plist_path: "Macaron/GoogleService-Info.plist",
      block: proc do |plist|
        # Set Google Plist variables
        plist["CLIENT_ID"] = ENV["FIREBASE_CLIENTID"]
        plist["REVERSED_CLIENT_ID"] = ENV["FIREBASE_REVERSEDCLIENTID"]
        plist["API_KEY"] = ENV["FIREBASE_APIKEY"]
        plist["GCM_SENDER_ID"] = ENV["FIREBASE_GCMSENDERID"]
        plist["BUNDLE_ID"] = ENV["FIREBASE_BUNDLEID"]
        plist["PROJECT_ID"] = ENV["FIREBASE_PROJECTID"]
        plist["STORAGE_BUCKET"] = ENV["FIREBASE_STORAGEBUCKET"]
        plist["GOOGLE_APP_ID"] = ENV["FIREBASE_GOOGLEAPPID"]
        plist["DATABASE_URL"] = ENV["FIREBASE_DATABASEURL"]
      end
    )

    update_plist(
      plist_path: "Macaron/Configuration.plist",
      block: proc do |plist|
        plist["apiUrl"] = ENV["API_URL"]
      end
    )

    update_info_plist( # Advanced processing: find URL scheme for particular key and replace value
      plist_path: "App/Info.plist",
      block: proc do |plist|
         # Set Mapbox api key
         plist["MGLMapboxAccessToken"] = ENV["MAPBOX_APIKEY"]
      end
    )
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.165.0 | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.2.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.3.0        |
| slack-notifier                            | 2.3.2        |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.7.0        |
| terminal-table                            | 1.8.0        |
| plist                                     | 3.5.0        |
| CFPropertyList                            | 3.0.2        |
| addressable                               | 2.7.0        |
| multipart-post                            | 2.0.0        |
| word_wrap                                 | 1.0.0        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| colored                                   | 1.2          |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| faraday_middleware                        | 1.0.0        |
| gh_inspector                              | 1.1.3        |
| mini_magick                               | 4.10.1       |
| rubyzip                                   | 2.3.0        |
| security                                  | 0.1.3        |
| xcpretty-travis-formatter                 | 1.0.0        |
| bundler                                   | 2.1.4        |
| naturally                                 | 2.2.0        |
| simctl                                    | 1.6.8        |
| uber                                      | 0.1.0        |
| declarative-option                        | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| mini_mime                                 | 1.0.2        |
| signet                                    | 0.14.0       |
| httpclient                                | 2.8.3        |
| google-api-client                         | 0.38.0       |
| nanaimo                                   | 0.3.0        |
| colored2                                  | 3.1.2        |
| claide                                    | 1.0.3        |
| atomos                                    | 0.1.3        |
| xcodeproj                                 | 1.19.0       |
| public_suffix                             | 4.0.6        |
| tty-screen                                | 0.8.1        |
| babosa                                    | 1.0.4        |
| excon                                     | 0.78.0       |
| unf_ext                                   | 0.0.7.7      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| http-cookie                               | 1.0.3        |
| ruby2_keywords                            | 0.0.2        |
| faraday                                   | 1.1.0        |
| faraday-cookie_jar                        | 0.0.7        |
| fastimage                                 | 2.2.0        |
| json                                      | 2.3.1        |
| dotenv                                    | 2.7.6        |
| jwt                                       | 2.2.2        |
| declarative                               | 0.0.20       |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.1        |
| memoist                                   | 0.16.2       |
| googleauth                                | 0.14.0       |
| rake                                      | 13.0.1       |
| digest-crc                                | 0.6.1        |
| google-cloud-errors                       | 1.0.1        |
| google-cloud-env                          | 1.4.0        |
| google-cloud-core                         | 1.5.0        |
| google-cloud-storage                      | 1.29.1       |
| emoji_regex                               | 3.2.0        |
| aws-eventstream                           | 1.1.0        |
| aws-sigv4                                 | 1.2.2        |
| aws-partitions                            | 1.388.0      |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.109.1      |
| aws-sdk-kms                               | 1.39.0       |
| aws-sdk-s3                                | 1.83.1       |
| forwardable                               | 1.2.0        |
| logger                                    | 1.3.0        |
| stringio                                  | 0.0.2        |
| ipaddr                                    | 1.2.2        |
| openssl                                   | 2.1.2        |
| ostruct                                   | 0.1.0        |
| strscan                                   | 1.0.0        |
| date                                      | 2.0.0        |
| fileutils                                 | 1.1.0        |
| etc                                       | 1.0.1        |
| io-console                                | 0.4.7        |
| zlib                                      | 1.0.0        |
| rexml                                     | 3.1.9        |
| psych                                     | 3.1.0        |
| mutex_m                                   | 0.1.0        |
| webrick                                   | 1.4.2        |
| fastlane-plugin-firebase_app_distribution | 0.2.4        |
</details>

*generated on:* **2020-12-26**
</details>

**Comment by rogerluan** [comment]
Hey @abouroubi 👋 

We've been discussing this here: https://github.com/fastlane/fastlane/discussions/17826

Wanna join the discussion? Maybe you can test out the branch I created to help debug this issue: https://github.com/fastlane/fastlane/discussions/17826#discussioncomment-234294 🙏

**Comment by abouroubi** [comment]
Thanks @rogerluan, I'm using GitHub and not S3 do you think it's the same issue ?

**Comment by rogerluan** [comment]
@abouroubi this doesn't seem related actually. Can you update to the latest fastlane version and post the full output of your command, using `--verbose`? 🙏
