### ISSUE TITLE
Can't update fastlane with gem

### ISSUE THREAD

**Issue by HarriMaatta** [fastlane/fastlane#17884]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Our Ansible script tries to update fastlane in our Mac Mini's (macOS Big Sur 11.1) but updating fastlane via gems fails. 

##### Command executed
This works fine:
```
/usr/local/opt/ruby/bin/gem install fastlane 
Fetching fastlane-2.54.1.gem
Successfully installed fastlane-2.54.1
Parsing documentation for fastlane-2.54.1
Installing ri documentation for fastlane-2.54.1
Done installing documentation for fastlane after 7 seconds
1 gem installed
```

Also this works fine:
```
/usr/local/opt/ruby/bin/gem uninstall fastlane
Remove executables:
	bin-proxy, fastlane

in addition to the gem? [Yn]  y
Removing bin-proxy
Removing fastlane
Successfully uninstalled fastlane-2.54.1
```

But for some reason this doesn't:
```
/usr/local/opt/ruby/bin/gem update fastlane
Updating installed gems
Updating fastlane
ERROR:  While executing gem ... (NoMethodError)
    undefined method `request' for nil:NilClass
```

As you can see from below, warning(s) says that I should update the fastlane. Well, that is an issue atm... Also, if I have understood correctly, using sudo with gems are not recommended way to do things. Any other ideas how to proceed?

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre> [/usr/local/lib/ruby/gems/3.0.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/lib/ruby/gems/3.0.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
[19:08:24]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2020-12-30 19:08:27.23]: Checking if there are any plugins that should be loaded...
WARN [2020-12-30 19:08:27.35]: Could not find fastlane in current directory. Make sure to have your fastlane configuration files inside a folder called "fastlane". Would you like to set fastlane up?
WARN [2020-12-30 19:08:29.35]: Generating fastlane environment output, this might take a few seconds...
DEBUG [2020-12-30 19:08:29.69]: Checking if there are any plugins that should be loaded...
### Captured Output

Command Used: ``
<details><summary>Output/Log</summary>

```


Looking for related GitHub issues on fastlane/fastlane...
Search query: Could not retrieve response as fastlane runs in non-interactive mode

URL: https://api.github.com/search/issues?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode+repo:fastlane/fastlane
➡️  GITLAB CI: Could not retrieve response as fastlane runs in non-interactive mode
    https://github.com/fastlane/fastlane/issues/17376 [closed] 18 💬
    a week ago

➡️  FastlaneCore::Interface::FastlaneCrash: [!] Could not retrieve response as fastlane runs in non-interactive mode
    https://github.com/fastlane/fastlane/issues/17488 [closed] 11 💬
    6 weeks ago

➡️  resign can't find signing identity
    https://github.com/fastlane/fastlane/issues/17575 [closed] 8 💬
    a week ago

and 51 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.


```

</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 11.1                                            |
| Ruby                        | 3.0.0                                           |
| Bundler?                    | false                                           |
| Git                         | git version 2.24.3 (Apple Git-128)              |
| Installation Source         | /usr/local/lib/ruby/gems/2.7.0/bin/fastlane     |
| Host                        | macOS 11.1 (20C69)                              |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/3.0.0_1/lib              |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                      |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | false                                           |
| Xcode Path                  | /Applications/Xcode12.3.app/Contents/Developer/ |
| Xcode Version               | 12.3                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.54.1  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.5.0        |
| slack-notifier            | 1.5.1        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| CFPropertyList            | 2.3.6        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.1        |
| babosa                    | 1.0.4        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.78.1       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| fastimage                 | 2.2.1        |
| gh_inspector              | 1.1.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| jwt                       | 2.2.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.14.0       |
| httpclient                | 2.8.3        |
| rexml                     | 3.2.4        |
| google-api-client         | 0.52.0       |
| json                      | 2.5.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.3        |
| dotenv                    | 2.7.6        |
| bundler                   | 1.17.3       |
| faraday_middleware        | 0.14.0       |
| tsort                     | 0.1.0        |
| set                       | 1.0.1        |
| uri                       | 0.10.1       |
| ostruct                   | 0.3.1        |
| logger                    | 1.4.3        |
| cgi                       | 0.2.0        |
| erb                       | 2.2.0        |
| strscan                   | 3.0.0        |
| optparse                  | 0.1.0        |
| stringio                  | 3.0.0        |
| abbrev                    | 0.1.0        |
| date                      | 3.1.0        |
| pathname                  | 0.1.0        |
| forwardable               | 1.3.2        |
| tempfile                  | 0.1.1        |
| delegate                  | 0.2.0        |
| fileutils                 | 1.5.0        |
| tmpdir                    | 0.1.1        |
| shellwords                | 0.1.0        |
| io-console                | 0.5.6        |
| openssl                   | 2.2.0        |
| io-nonblock               | 0.1.0        |
| ipaddr                    | 1.2.2        |
| io-wait                   | 0.1.0        |
| timeout                   | 0.1.1        |
| zlib                      | 1.1.0        |
| digest                    | 3.0.0        |
| time                      | 0.1.0        |
| open-uri                  | 0.1.0        |
| singleton                 | 0.1.1        |
| base64                    | 0.1.0        |
| prettyprint               | 0.1.0        |
| pp                        | 0.1.0        |
| open3                     | 0.1.1        |
| net-protocol              | 0.1.0        |
| net-smtp                  | 0.2.1        |
| securerandom              | 0.1.0        |
| english                   | 0.7.1        |
| find                      | 0.1.0        |
| etc                       | 1.2.0        |
| resolv                    | 0.2.0        |
</details>

*generated on:* **2020-12-30**
</details>

#######################################################################
# fastlane 2.170.0 is available. You are on 2.54.1.
# You should use the latest version.
# Please update using `sudo gem install fastlane`.
#######################################################################

2.170.0 Improvements and Upload App Privacy Details
* [Fastlane.swift] fixed potential undefined method `action_name' in generator (#17660) via phil zhang
* [action] onesignal - update onesignal.rb to include optional organization_id (#17696) via Brandon Carpenter
* [deliver] fix a regression in language detection in Deliver::UploadMetadata (#17730) via Satoshi Namai
* [action] NEW ACTION for App Data Usages: upload_app_privacy_details_to_app_store (#17592) via Josh Holtz
* [match] only include enabled devices for force_for_new_devices (#17695) via Steven Roebert

For more information on uploading App Privacy Details, go to https://docs.fastlane.tools/uploading-app-privacy-details/

2.169.0 Improvements
* [cert] add tvos to platforms option (#17704) via Josh Holtz
* [spaceship] ConnectAPI::App - actually limit get_app_store_versions (#17703) via Josh Holtz
* [spaceship] fix get_live_version (#17701) via Max Ott
* [snapshot] conditional compiler directive (#17687) via Jorge
* [deliver] prepare for adding new validations for screenshots (refactoring) (#17661) via Satoshi Namai
* [gym][scan] add -scmProvider option to xcodebuild command for the gym and scan actions (#17644) via Andrea Sacerdoti
* [spaceship] handle 429 error response (#17692) via Joe DeCapo
* [spaceship] get push mode from trustedPhoneNumbers (#17666) via Nick Rogness
* [spaceship] add support for Privacy Choices URL (#17665) via Max Ott
* [action] xcode-install - add option to customize number of download retry attempts (#17691) via Roger Oba

2.168.0 Improvements
* [spaceship] add client optional parameter in model helpers (#17475) via Bolo Michelin
* [match] support mac_installer_distribution certificate type (#17561) via Paul Taykalo
* [action] add support for arrays in in slather action for binary_basename and FL_SLATHER_BINARY_BASENAME environment variable (#17606) via José González
* [fastlane] also support NO_COLOR for disabling colors (#17611) via Benedek Kozma
* [deliver] read values from SharedValues context only if needed. (#17616) via Roger Oba
* [scan] fix crash on TestResultParser when disable_xcpretty=true (#17623) via Marcelo Gobetti
* [supply] skip sending user fraction if it's 1.0 when promoting track (#17617) via Roger Oba

To see all new releases, open https://github.com/fastlane/fastlane/releases

Please update using `sudo gem install fastlane`
/usr/local/lib/ruby/gems/3.0.0/gems/highline-1.7.10/lib/highline.rb:624:in `encode': no implicit conversion of Hash into String (TypeError)
	from /usr/local/lib/ruby/gems/3.0.0/gems/highline-1.7.10/lib/highline.rb:624:in `say'
	from /usr/local/lib/ruby/gems/3.0.0/gems/highline-1.7.10/lib/highline.rb:261:in `ask'
	from /usr/local/lib/ruby/gems/3.0.0/gems/highline-1.7.10/lib/highline.rb:227:in `agree'
	from /usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/forwardable.rb:238:in `agree'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:109:in `confirm'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/environment_printer.rb:12:in `output'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/commands_generator.rb:51:in `ensure in start'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/commands_generator.rb:51:in `start'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/bin/fastlane:20:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `load'
	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `<main>'
/usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane_core/lib/fastlane_core/ui/interface.rb:119:in `crash!': \e[31m[!] Could not retrieve response as fastlane runs in non-interactive mode\e[0m (FastlaneCore::Interface::FastlaneCrash)
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:130:in `verify_interactive!'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:108:in `confirm'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/commands_generator.rb:313:in `ensure_fastfile'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/commands_generator.rb:103:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/bin/fastlane:20:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `load'
	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `<main>'
/usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane_core/lib/fastlane_core/ui/interface.rb:119:in `crash!': Could not retrieve response as fastlane runs in non-interactive mode (FastlaneCore::Interface::FastlaneCrash)
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:130:in `verify_interactive!'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:108:in `confirm'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/commands_generator.rb:313:in `ensure_fastfile'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/commands_generator.rb:103:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/bin/fastlane:20:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `load'
	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `<main>'
</pre>
</details>

### Environment
<details>
  <pre> /usr/local/lib/ruby/gems/3.0.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/lib/ruby/gems/3.0.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
[19:05:56]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[19:05:59]: Sending crash report...
[19:05:59]: The stack trace is sanitized so no personal information is sent.
[19:05:59]: To see what we are sending, look here: /Users/jenkins/.fastlane/latest_crash.json
[19:05:59]: Learn more at https://github.com/fastlane/fastlane#crash-reporting
[19:05:59]: You can disable crash reporting by adding `opt_out_crash_reporting` at the top of your Fastfile

Looking for related GitHub issues on fastlane/fastlane...

➡️  How to read Shell Curl output into a variable
    https://github.com/fastlane/fastlane/issues/16323 [closed] 3 💬
    20 Jun 2020

➡️  [Question] Skip action-summaries
    https://github.com/fastlane/fastlane/issues/15569 [closed] 13 💬
    13 Feb 2020

➡️  Adding export_options to gym not working
    https://github.com/fastlane/fastlane/issues/10778 [closed] 40 💬
    24 Aug 2018

and 6 more at: https://github.com/fastlane/fastlane/search?q=no%20implicit%20conversion%20of%20Hash%20into%20String&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.

#######################################################################
# fastlane 2.170.0 is available. You are on 2.54.1.
# You should use the latest version.
# Please update using `sudo gem install fastlane`.
#######################################################################

2.170.0 Improvements and Upload App Privacy Details
* [Fastlane.swift] fixed potential undefined method `action_name' in generator (#17660) via phil zhang
* [action] onesignal - update onesignal.rb to include optional organization_id (#17696) via Brandon Carpenter
* [deliver] fix a regression in language detection in Deliver::UploadMetadata (#17730) via Satoshi Namai
* [action] NEW ACTION for App Data Usages: upload_app_privacy_details_to_app_store (#17592) via Josh Holtz
* [match] only include enabled devices for force_for_new_devices (#17695) via Steven Roebert

For more information on uploading App Privacy Details, go to https://docs.fastlane.tools/uploading-app-privacy-details/

2.169.0 Improvements
* [cert] add tvos to platforms option (#17704) via Josh Holtz
* [spaceship] ConnectAPI::App - actually limit get_app_store_versions (#17703) via Josh Holtz
* [spaceship] fix get_live_version (#17701) via Max Ott
* [snapshot] conditional compiler directive (#17687) via Jorge
* [deliver] prepare for adding new validations for screenshots (refactoring) (#17661) via Satoshi Namai
* [gym][scan] add -scmProvider option to xcodebuild command for the gym and scan actions (#17644) via Andrea Sacerdoti
* [spaceship] handle 429 error response (#17692) via Joe DeCapo
* [spaceship] get push mode from trustedPhoneNumbers (#17666) via Nick Rogness
* [spaceship] add support for Privacy Choices URL (#17665) via Max Ott
* [action] xcode-install - add option to customize number of download retry attempts (#17691) via Roger Oba

2.168.0 Improvements
* [spaceship] add client optional parameter in model helpers (#17475) via Bolo Michelin
* [match] support mac_installer_distribution certificate type (#17561) via Paul Taykalo
* [action] add support for arrays in in slather action for binary_basename and FL_SLATHER_BINARY_BASENAME environment variable (#17606) via José González
* [fastlane] also support NO_COLOR for disabling colors (#17611) via Benedek Kozma
* [deliver] read values from SharedValues context only if needed. (#17616) via Roger Oba
* [scan] fix crash on TestResultParser when disable_xcpretty=true (#17623) via Marcelo Gobetti
* [supply] skip sending user fraction if it's 1.0 when promoting track (#17617) via Roger Oba

To see all new releases, open https://github.com/fastlane/fastlane/releases

Please update using `sudo gem install fastlane`
/usr/local/lib/ruby/gems/3.0.0/gems/highline-1.7.10/lib/highline.rb:624:in `encode': \e[31m[!] no implicit conversion of Hash into String\e[0m (TypeError)
	from /usr/local/lib/ruby/gems/3.0.0/gems/highline-1.7.10/lib/highline.rb:624:in `say'
	from /usr/local/lib/ruby/gems/3.0.0/gems/highline-1.7.10/lib/highline.rb:261:in `ask'
	from /usr/local/lib/ruby/gems/3.0.0/gems/highline-1.7.10/lib/highline.rb:227:in `agree'
	from /usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/forwardable.rb:238:in `agree'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:109:in `confirm'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/commands_generator.rb:313:in `ensure_fastfile'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/commands_generator.rb:103:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/bin/fastlane:20:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `load'
	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `<main>'
/usr/local/lib/ruby/gems/3.0.0/gems/highline-1.7.10/lib/highline.rb:624:in `encode': no implicit conversion of Hash into String (TypeError)
	from /usr/local/lib/ruby/gems/3.0.0/gems/highline-1.7.10/lib/highline.rb:624:in `say'
	from /usr/local/lib/ruby/gems/3.0.0/gems/highline-1.7.10/lib/highline.rb:261:in `ask'
	from /usr/local/lib/ruby/gems/3.0.0/gems/highline-1.7.10/lib/highline.rb:227:in `agree'
	from /usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/forwardable.rb:238:in `agree'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:109:in `confirm'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/commands_generator.rb:313:in `ensure_fastfile'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/commands_generator.rb:103:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /usr/local/lib/ruby/gems/3.0.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.54.1/bin/fastlane:20:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `load'
	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `<main>'
</pre>
</details>

**Comment by jbiel** [comment]
Fastlane (and a dependency) appear to be incompatible with Ruby 3. Recommend downgrading to Ruby 2.7 for now.

**Comment by ainame** [comment]
Yes, fastlane with Ruby 3.0 is getting stuck at installation due to an old dependency `google-api-client` blocking us from installing into Ruby 3.0 environment. (And there must be other issues in fastlane itself). I will work on supporting Ruby 3.0 in fastlane over the next few months but I'm not sure how long it will take right now. So stay tuned 🤞

**Comment by T-Jedsada** [comment]
same issue
