### ISSUE TITLE
You must provide a value for the attribute 'companyName'

### ISSUE THREAD

**Issue by dittmarconsulting** [fastlane/fastlane#17883]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
- I have created a sample *React-Native* application, which runs fine in the simulator
- Then I installed *fastlane* with command `sudo gem install fastlane -NV`, which resulted in `/Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/bin/fastlane`

##### Command executed
- The first command I executed was `fastlane init` (output below)
- The second command was `fastlane produce` (output below)

##### Complete output when running fastlane, including the stack trace and command used

```javascript
fastlane init

[✔] 🚀 
[✔] Looking for iOS and Android projects in current directory...
[18:11:02]: Created new folder './fastlane'.
[18:11:02]: Detected an iOS/macOS project in the current directory: 'Wplanner.xcworkspace'
[18:11:02]: -----------------------------
[18:11:02]: --- Welcome to fastlane 🚀 ---
[18:11:02]: -----------------------------
[18:11:02]: fastlane can help you with all kinds of automation for your mobile app
[18:11:02]: We recommend automating one task first, and then gradually automating more over time
[18:11:02]: What would you like to use fastlane for?
1. 📸  Automate screenshots
2. 👩‍✈️  Automate beta distribution to TestFlight
3. 🚀  Automate App Store distribution
4. 🛠  Manual setup - manually setup your project to automate your tasks
?  4
[18:11:11]: ------------------------------------------------------------
[18:11:11]: --- Setting up fastlane so you can manually configure it ---
[18:11:11]: ------------------------------------------------------------
[18:11:11]: --------------------------------------------------------
[18:11:11]: --- ✅  Successfully generated fastlane configuration ---
[18:11:11]: --------------------------------------------------------
[18:11:11]: Generated Fastfile at path `./fastlane/Fastfile`
[18:11:11]: Generated Appfile at path `./fastlane/Appfile`
[18:11:11]: Gemfile and Gemfile.lock at path `Gemfile`
[18:11:11]: Please check the newly generated configuration files into git along with your project
[18:11:11]: This way everyone in your team can benefit from your fastlane setup
[18:11:11]: Continue by pressing Enter ⏎

[18:11:13]: fastlane will collect the number of errors for each action to detect integration issues
[18:11:13]: No sensitive/private information will be uploaded, more information: https://docs.fastlane.tools/#metrics
[18:11:13]: ----------------------
[18:11:13]: --- fastlane lanes ---
[18:11:13]: ----------------------
[18:11:13]: fastlane uses a `Fastfile` to store the automation configuration
[18:11:13]: Within that, you'll see different lanes.
[18:11:13]: Each is there to automate a different task, like screenshots, code signing, or pushing new releases
[18:11:13]: Continue by pressing Enter ⏎

[18:11:14]: --------------------------------------
[18:11:14]: --- How to customize your Fastfile ---
[18:11:14]: --------------------------------------
[18:11:14]: Use a text editor of your choice to open the newly created Fastfile and take a look
[18:11:14]: You can now edit the available lanes and actions to customize the setup to fit your needs
[18:11:14]: To get a list of all the available actions, open https://docs.fastlane.tools/actions
[18:11:14]: Continue by pressing Enter ⏎

[18:11:15]: ------------------------------
[18:11:15]: --- Where to go from here? ---
[18:11:15]: ------------------------------
[18:11:15]: 📸  Learn more about how to automatically generate localized App Store screenshots:
[18:11:15]: 		https://docs.fastlane.tools/getting-started/ios/screenshots/
[18:11:15]: 👩‍✈️  Learn more about distribution to beta testing services:
[18:11:15]: 		https://docs.fastlane.tools/getting-started/ios/beta-deployment/
[18:11:15]: 🚀  Learn more about how to automate the App Store release process:
[18:11:15]: 		https://docs.fastlane.tools/getting-started/ios/appstore-deployment/
[18:11:15]: 👩‍⚕️  Learn more about how to setup code signing with fastlane
[18:11:15]: 		https://docs.fastlane.tools/codesigning/getting-started/
[18:11:15]: 
[18:11:15]: To try your new fastlane setup, just enter and run
[18:11:15]: $ fastlane custom_lane
```

```javascript
fastlane produce
                
[✔] 🚀 
[18:13:31]: fastlane detected a Gemfile in the current directory
[18:13:31]: However, it seems like you didn't use `bundle exec`
[18:13:31]: To launch fastlane faster, please use
[18:13:31]: 
[18:13:31]: $ bundle exec fastlane produce
[18:13:31]: 
[18:13:31]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

+----------------+------------+
| Summary for produce 2.170.0 |
+----------------+------------+
| sku            | 1609312413 |
| platform       | ios        |
| language       | English    |
| skip_itc       | false      |
| skip_devcenter | false      |
+----------------+------------+

[18:13:33]: To not be asked about this value, you can specify it using 'username'
[18:13:33]: Your Apple ID Username: <my apple id email address>
[18:13:47]: To not be asked about this value, you can specify it using 'app_identifier'
[18:13:47]: App Identifier (Bundle ID, e.g. com.krausefx.app): <my bundle id from XCode>
[18:13:57]: To not be asked about this value, you can specify it using 'app_name'
[18:13:57]: App Name: TestApp001
[18:14:09]: Creating new app 'TestApp001' on App Store Connect
[18:14:09]: Sending language name is deprecated. 'English' has been mapped to 'en-US'.
[18:14:09]: Please enter one of available languages: ["ar-SA", "ca", "cs", "da", "de-DE", "el", "en-AU", "en-CA", "en-GB", "en-US", "es-ES", "es-MX", "fi", "fr-CA", "fr-FR", "he", "hi", "hr", "hu", "id", "it", "ja", "ko", "ms", "nl-NL", "no", "pl", "pt-BR", "pt-PT", "ro", "ru", "sk", "sv", "th", "tr", "uk", "vi", "zh-Hans", "zh-Hant"]

Looking for related GitHub issues on fastlane/fastlane...

➡️  Having deliver/upload_to_app_store issues? Install 2.150.0.rc5
    https://github.com/fastlane/fastlane/issues/16639 [closed] 116 💬
    04 Sep 2020

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	19: from /usr/local/bin/fastlane:23:in `<main>'
	18: from /usr/local/bin/fastlane:23:in `load'
	17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/bin/fastlane:23:in `<top (required)>'
	16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/produce/lib/produce/commands_generator.rb:16:in `start'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/produce/lib/produce/commands_generator.rb:233:in `run'
	13: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	11: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	10: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 9: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/produce/lib/produce/commands_generator.rb:40:in `block (2 levels) in run'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/produce/lib/produce/manager.rb:12:in `start_producing'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/produce/lib/produce/itunes_connect.rb:16:in `run'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/produce/lib/produce/itunes_connect.rb:41:in `create_new_app'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/models/app.rb:87:in `create'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `post_app'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:132:in `post_app'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/api_client.rb:124:in `post'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/api_client.rb:193:in `handle_response': The provided entity is missing a required attribute - You must provide a value for the attribute 'companyName' with this request (Spaceship::UnexpectedResponse)
	19: from /usr/local/bin/fastlane:23:in `<main>'
	18: from /usr/local/bin/fastlane:23:in `load'
	17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/bin/fastlane:23:in `<top (required)>'
	16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/produce/lib/produce/commands_generator.rb:16:in `start'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/produce/lib/produce/commands_generator.rb:233:in `run'
	13: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	11: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	10: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 9: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/produce/lib/produce/commands_generator.rb:40:in `block (2 levels) in run'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/produce/lib/produce/manager.rb:12:in `start_producing'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/produce/lib/produce/itunes_connect.rb:16:in `run'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/produce/lib/produce/itunes_connect.rb:41:in `create_new_app'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/models/app.rb:87:in `create'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `post_app'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:132:in `post_app'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/api_client.rb:124:in `post'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.170.0/spaceship/lib/spaceship/connect_api/api_client.rb:193:in `handle_response': [!] The provided entity is missing a required attribute - You must provide a value for the attribute 'companyName' with this request (Spaceship::UnexpectedResponse)
```

### Environment

<details>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.1                                                           |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.17.1                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.1 (20C69)                                             |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.3                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_AU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.170.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.4        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.78.1       |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.2.0        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.1        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.11.0       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.2.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.14.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.4.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.6.3        |
| google-cloud-storage      | 1.29.2       |
| emoji_regex               | 3.2.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.413.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.110.0      |
| aws-sdk-kms               | 1.40.0       |
| aws-sdk-s3                | 1.87.0       |
| nanaimo                   | 0.3.0        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.3        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.19.0       |
| json                      | 2.5.1        |
| rake                      | 13.0.3       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| date                      | 2.0.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>

*generated on:* **2020-12-30**
</details>

**Comment by dittmarconsulting** [comment]
The only thing I found about that error was [here](https://doc.siberiancms.com/knowledge-base/ios-auto-publish-known-issues/)

It suggested:

```
When you publish for the first time, Apple asks you to add a company name when adding your first application in your account at https://appstoreconnect.apple.com. After having this message from the Auto-publish system, go at https://appstoreconnect.apple.com, go in “My Apps”, and click on the “+” to add a new app. Enter the name of your company, then the name of the application that you want to publish, choose the bundle ID of your application in the choice list, enter a SKU (the name of your app with no space and in lowercase) and save. Then use the iOS Auto-publish system again.
```

Does that mean I have to add the app manually before I can use `fastlane produce`?

**Comment by max-ott** [comment]
It can, you just must provide a company name for the first app you setup on the account. We've done this 100+ times in the past, so this works, you just need to provide the value.

**Comment by An0r4k** [comment]
@max-ott how do I provide the company name?

**Comment by max-ott** [comment]
For reference, this works for us:
```
Spaceship::ConnectAPI.post_app(
          name: app_name,
          version_string: "1.0",
          sku: app_identifier,
          primary_locale: "en-US",
          bundle_id: app_identifier,
          platforms: ["IOS"],
          company_name: team_name
        )
```
