### ISSUE TITLE
Couldn't decrypt the repo, please make sure you enter the right password! 

### ISSUE THREAD

**Issue by SeiyaTakahashi** [fastlane/fastlane#17893]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.0.1                                                         |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.0.1 (20B50)                                           |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.2                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | ja_JP.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.63.0"

default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci	
    create_keychain(	
      name: ENV["MATCH_KEYCHAIN_NAME"],	
      password: ENV["MATCH_KEYCHAIN_PASSWORD"],	
      timeout: 1200	
    )	
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do |options|
    api_key = app_store_connect_api_key(
      key_id: "D3T6PQDH74",
      issuer_id: "af230671-0e9c-46da-9553-29eb7b5ceb90",
      key_filepath: 'fastlane/app_store_connect_api_key.p8',
      in_house: false
    )
    pilot(
      ipa: 'ios/Rocket.Chat.ipa',
      app_identifier: options[:official] ? 'io.workchat.ios' : 'io.workchat.reactnative',
      skip_waiting_for_build_processing: true
    )
    upload_symbols_to_crashlytics(dsym_path: "./ios/Rocket.Chat.app.dSYM.zip")
  end

  desc "Build Experimental app"
  lane :build_experimental do
    api_key = app_store_connect_api_key(
      key_id: "D3T6PQDH74",
      issuer_id: "af230671-0e9c-46da-9553-29eb7b5ceb90",
      key_filepath: 'fastlane/app_store_connect_api_key.p8',
      in_house: false
    )
    match(type: "appstore")
    get_provisioning_profile(app_identifier: "io.workchat.reactnative.ShareExtension")
    get_provisioning_profile(app_identifier: "io.workchat.reactnative.NotificationService")
    # pem(api_key: api_key) # still uses Spaceship http://docs.fastlane.tools/actions/pem/#how-does-it-work
    gym(
      scheme: "RocketChatRN",
      workspace: "RocketChatRN.xcworkspace",
      output_name: "Rocket.Chat"
    )
  end

  desc "Build Official app"
  lane :build_official do
    sh "../../scripts/prepare_ios_official.sh"

    match(
      type: "appstore",
      app_identifier: ["io.workchat.ios", "io.workchat.ios.NotificationService", "io.workchat.ios.Rocket-Chat-ShareExtension"],
      readonly: true,
      output_path: './'
    )

    update_project_provisioning(
      xcodeproj: 'RocketChatRN.xcodeproj',
      profile: "AppStore_io.workchat.ios.NotificationService.mobileprovision",
      target_filter: "NotificationService",
      build_configuration: 'Release',
      code_signing_identity: 'iPhone Distribution'
    )

    update_project_provisioning(
      xcodeproj: 'RocketChatRN.xcodeproj',
      profile: "AppStore_io.workchat.ios.Rocket-Chat-ShareExtension.mobileprovision",
      target_filter: "ShareRocketChatRN",
      build_configuration: 'Release',
      code_signing_identity: 'iPhone Distribution'
    )

    gym(
      scheme: "RocketChat",
      workspace: "RocketChatRN.xcworkspace",
      xcargs: "-allowProvisioningUpdates",
      output_name: "Rocket.Chat"
    )
  end

  desc "Build fork app"
  lane :build_fork do
    gym(scheme: "RocketChatRN", workspace: "RocketChatRN.xcworkspace", skip_codesigning: true, skip_archive: true)
  end

  after_all do |lane|
    delete_keychain(name: ENV["MATCH_KEYCHAIN_NAME"])	
  end	

  error do |lane, exception|
    delete_keychain(name: ENV["MATCH_KEYCHAIN_NAME"])	
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "io.workchat" # The bundle identifier of your app
apple_id("seiya4@icloud.com") # Your Apple email address

team_id("2R8AHR37XC") # Developer Portal Team ID
itc_team_id("122508024") # App Store Connect Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.171.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday_middleware        | 1.0.0        |
| gh_inspector              | 1.1.3        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| uber                      | 0.1.0        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| signet                    | 0.14.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| nanaimo                   | 0.3.0        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.3        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.19.0       |
| unicode-display_width     | 1.7.0        |
| plist                     | 3.6.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| tty-screen                | 0.8.1        |
| babosa                    | 1.0.4        |
| excon                     | 0.78.1       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| ruby2_keywords            | 0.0.2        |
| faraday-net_http          | 1.0.0        |
| faraday                   | 1.3.0        |
| faraday-cookie_jar        | 0.0.7        |
| fastimage                 | 2.2.1        |
| json                      | 2.5.1        |
| mini_magick               | 4.11.0       |
| rubyzip                   | 2.3.0        |
| dotenv                    | 2.7.6        |
| jwt                       | 2.2.2        |
| declarative               | 0.0.20       |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| memoist                   | 0.16.2       |
| googleauth                | 0.14.0       |
| rake                      | 13.0.3       |
| digest-crc                | 0.6.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-env          | 1.4.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.2       |
| emoji_regex               | 3.2.1        |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-partitions            | 1.414.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.110.0      |
| aws-sdk-kms               | 1.40.0       |
| aws-sdk-s3                | 1.87.0       |
| forwardable               | 1.3.1        |
| logger                    | 1.4.2        |
| date                      | 3.0.0        |
| stringio                  | 0.1.0        |
| zlib                      | 1.1.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.3        |
| fileutils                 | 1.4.1        |
| io-console                | 0.5.6        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.2.4        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>

*generated on:* **2021-01-02**
</details>

**Comment by xgenem** [comment]
I am experiencing this same issue. Any idea guys?

**Comment by rdewolff** [comment]
Same issue on the last version. Any idea?
