### ISSUE TITLE
Seems pilot uses non-exist param value in Apple Connect API

### ISSUE THREAD

**Issue by myme5261314** [fastlane/fastlane#17899]
```shell
fastlane pilot list --api_key_path XX.json --app_identifier "XX" --verbose
```
<details><summary>Traceback Output</summary>

```shell

Traceback (most recent call last):
	18: from /usr/local/bin/fastlane:23:in '<main>'
	17: from /usr/local/bin/fastlane:23:in 'load'
	16: from /Users/ben/.gems/gems/fastlane-2.171.0/bin/fastlane:23:in '<top (required)>'
	15: from /Users/ben/.gems/gems/fastlane-2.171.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in 'take_off'
	14: from /Users/ben/.gems/gems/fastlane-2.171.0/pilot/lib/pilot/commands_generator.rb:18:in 'start'
	13: from /Users/ben/.gems/gems/fastlane-2.171.0/pilot/lib/pilot/commands_generator.rb:166:in 'run'
	12: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in 'run!'
	11: from /Users/ben/.gems/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in 'run!'
	10: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in 'run_active_command'
	 9: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in 'run'
	 8: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in 'call'
	 7: from /Users/ben/.gems/gems/fastlane-2.171.0/pilot/lib/pilot/commands_generator.rb:114:in 'block (2 levels) in run'
	 6: from /Users/ben/.gems/gems/fastlane-2.171.0/pilot/lib/pilot/tester_manager.rb:76:in 'list_testers'
	 5: from /Users/ben/.gems/gems/fastlane-2.171.0/pilot/lib/pilot/tester_manager.rb:111:in 'list_testers_by_app'
	 4: from /Users/ben/.gems/gems/fastlane-2.171.0/spaceship/lib/spaceship/connect_api/models/app.rb:344:in 'get_beta_testers'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in 'get_beta_testers'
	 2: from /Users/ben/.gems/gems/fastlane-2.171.0/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:235:in 'get_beta_testers'
	 1: from /Users/ben/.gems/gems/fastlane-2.171.0/spaceship/lib/spaceship/connect_api/api_client.rb:113:in 'get'
/Users/ben/.gems/gems/fastlane-2.171.0/spaceship/lib/spaceship/connect_api/api_client.rb:193:in 'handle_response': A parameter has an invalid value - 'betaTesterMetrics' is not a valid relationship name (Spaceship::UnexpectedResponse)
	18: from /usr/local/bin/fastlane:23:in '<main>'
	17: from /usr/local/bin/fastlane:23:in 'load'
	16: from /Users/ben/.gems/gems/fastlane-2.171.0/bin/fastlane:23:in '<top (required)>'
	15: from /Users/ben/.gems/gems/fastlane-2.171.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in 'take_off'
	14: from /Users/ben/.gems/gems/fastlane-2.171.0/pilot/lib/pilot/commands_generator.rb:18:in 'start'
	13: from /Users/ben/.gems/gems/fastlane-2.171.0/pilot/lib/pilot/commands_generator.rb:166:in 'run'
	12: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in 'run!'
	11: from /Users/ben/.gems/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in 'run!'
	10: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in 'run_active_command'
	 9: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in 'run'
	 8: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in 'call'
	 7: from /Users/ben/.gems/gems/fastlane-2.171.0/pilot/lib/pilot/commands_generator.rb:114:in 'block (2 levels) in run'
	 6: from /Users/ben/.gems/gems/fastlane-2.171.0/pilot/lib/pilot/tester_manager.rb:76:in 'list_testers'
	 5: from /Users/ben/.gems/gems/fastlane-2.171.0/pilot/lib/pilot/tester_manager.rb:111:in 'list_testers_by_app'
	 4: from /Users/ben/.gems/gems/fastlane-2.171.0/spaceship/lib/spaceship/connect_api/models/app.rb:344:in 'get_beta_testers'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in 'get_beta_testers'
	 2: from /Users/ben/.gems/gems/fastlane-2.171.0/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:235:in 'get_beta_testers'
	 1: from /Users/ben/.gems/gems/fastlane-2.171.0/spaceship/lib/spaceship/connect_api/api_client.rb:113:in 'get'
/Users/ben/.gems/gems/fastlane-2.171.0/spaceship/lib/spaceship/connect_api/api_client.rb:193:in 'handle_response': [!] A parameter has an invalid value - 'betaTesterMetrics' is not a valid relationship name (Spaceship::UnexpectedResponse)

```

</details>

```shell
fastlane pilot export --api_key_path XX.json --app_identifier "XX" --verbose
```

<details><summary>Traceback Output</summary>

```shell

Traceback (most recent call last):
	17: from /usr/local/bin/fastlane:23:in '<main>'
	16: from /usr/local/bin/fastlane:23:in 'load'
	15: from /Users/ben/.gems/gems/fastlane-2.171.0/bin/fastlane:23:in '<top (required)>'
	14: from /Users/ben/.gems/gems/fastlane-2.171.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in 'take_off'
	13: from /Users/ben/.gems/gems/fastlane-2.171.0/pilot/lib/pilot/commands_generator.rb:18:in 'start'
	12: from /Users/ben/.gems/gems/fastlane-2.171.0/pilot/lib/pilot/commands_generator.rb:166:in 'run'
	11: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in 'run!'
	10: from /Users/ben/.gems/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in 'run!'
	 9: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in 'run_active_command'
	 8: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in 'run'
	 7: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in 'call'
	 6: from /Users/ben/.gems/gems/fastlane-2.171.0/pilot/lib/pilot/commands_generator.rb:148:in 'block (2 levels) in run'
	 5: from /Users/ben/.gems/gems/fastlane-2.171.0/pilot/lib/pilot/tester_exporter.rb:16:in 'export_testers'
	 4: from /Users/ben/.gems/gems/fastlane-2.171.0/spaceship/lib/spaceship/connect_api/models/app.rb:344:in 'get_beta_testers'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in 'get_beta_testers'
	 2: from /Users/ben/.gems/gems/fastlane-2.171.0/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:235:in 'get_beta_testers'
	 1: from /Users/ben/.gems/gems/fastlane-2.171.0/spaceship/lib/spaceship/connect_api/api_client.rb:113:in 'get'
/Users/ben/.gems/gems/fastlane-2.171.0/spaceship/lib/spaceship/connect_api/api_client.rb:193:in 'handle_response': A parameter has an invalid value - 'betaTesterMetrics' is not a valid relationship name (Spaceship::UnexpectedResponse)
	17: from /usr/local/bin/fastlane:23:in '<main>'
	16: from /usr/local/bin/fastlane:23:in 'load'
	15: from /Users/ben/.gems/gems/fastlane-2.171.0/bin/fastlane:23:in '<top (required)>'
	14: from /Users/ben/.gems/gems/fastlane-2.171.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in 'take_off'
	13: from /Users/ben/.gems/gems/fastlane-2.171.0/pilot/lib/pilot/commands_generator.rb:18:in 'start'
	12: from /Users/ben/.gems/gems/fastlane-2.171.0/pilot/lib/pilot/commands_generator.rb:166:in 'run'
	11: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in 'run!'
	10: from /Users/ben/.gems/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in 'run!'
	 9: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in 'run_active_command'
	 8: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in 'run'
	 7: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in 'call'
	 6: from /Users/ben/.gems/gems/fastlane-2.171.0/pilot/lib/pilot/commands_generator.rb:148:in 'block (2 levels) in run'
	 5: from /Users/ben/.gems/gems/fastlane-2.171.0/pilot/lib/pilot/tester_exporter.rb:16:in 'export_testers'
	 4: from /Users/ben/.gems/gems/fastlane-2.171.0/spaceship/lib/spaceship/connect_api/models/app.rb:344:in 'get_beta_testers'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in 'get_beta_testers'
	 2: from /Users/ben/.gems/gems/fastlane-2.171.0/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:235:in 'get_beta_testers'
	 1: from /Users/ben/.gems/gems/fastlane-2.171.0/spaceship/lib/spaceship/connect_api/api_client.rb:113:in 'get'
/Users/ben/.gems/gems/fastlane-2.171.0/spaceship/lib/spaceship/connect_api/api_client.rb:193:in 'handle_response': [!] A parameter has an invalid value - 'betaTesterMetrics' is not a valid relationship name (Spaceship::UnexpectedResponse)

```

</details>

All the error message is
`
A parameter has an invalid value - 'betaTesterMetrics' is not a valid relationship name
`

Refer to the code here
```ruby
testers = app.get_beta_testers(includes: "betaTesterMetrics", limit: 200)
```
 https://github.com/fastlane/fastlane/pull/15126#issuecomment-518738734

code here

https://github.com/fastlane/fastlane/blob/03da1cf3bd3fd21a0d14b4209b3f06307acbcb9f/spaceship/lib/spaceship/connect_api/testflight/testflight.rb#L233-L235
https://github.com/fastlane/fastlane/blob/d2419a710e21d5f9cca9b4568426eb0c9e9ad18a/spaceship/lib/spaceship/connect_api/api_client.rb#L90-L102

And the official document here.
https://developer.apple.com/documentation/appstoreconnectapi/list_users

I doubt the "include" parameter can only be the value of "visibleApps"?

But, the endpoint of "betaTesters" seems to be here, which has no official document.
https://appstoreconnect.apple.com/iris/v1/betaTesters

So, how to fix this basic action?

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.1                                                           |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.29.2                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.1 (20C69)                                             |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.3                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

lane :release do
  app_store_connect_api_key(
    key_id: "XX",
    issuer_id: "XXX",
    key_filepath: "./XXX.p8",
    duration: 1200, # optional
    in_house: false, # optional but may be required if using match/sigh
  )

  # Automatically loads Actions.lane_context[SharedValues::APP_STORE_CONNECT_API_KEY]
  #pilot
  # pilot list
  # pilot(ipa: "./XX.ipa")
  username= "XX@XX.com"
  sh("fastlane pilot export")
  sh("fastlane pilot builds")
  sh("fastlane pilot list")
end

lane :release2 do
  sh("fastlane pilot list --api_key_path XX.json")
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.171.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.4        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.78.1       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.11.0       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| dotenv                    | 2.7.6        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.14.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| emoji_regex               | 3.2.1        |
| CFPropertyList            | 3.0.3        |
| plist                     | 3.6.0        |
| ruby2_keywords            | 0.0.2        |
| faraday-net_http          | 1.0.0        |
| faraday                   | 1.3.0        |
| fastimage                 | 2.2.1        |
| json                      | 2.5.1        |
| xcpretty-travis-formatter | 1.0.1        |
| rake                      | 13.0.3       |
| digest-crc                | 0.6.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-env          | 1.4.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.2       |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-partitions            | 1.414.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.110.0      |
| aws-sdk-kms               | 1.40.0       |
| aws-sdk-s3                | 1.87.0       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| date                      | 2.0.0        |
| stringio                  | 0.0.2        |
| zlib                      | 1.0.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>

*generated on:* **2021-01-04**
</details>

**Comment by tmm1** [comment]
I'm seeing this too when using the API key for authentication. Similar to https://github.com/fastlane/fastlane/issues/17821#issuecomment-770468463

**Comment by booker-dragon** [comment]
I am having the same issue trying to export the tester CSV

**Comment by Sorix** [comment]
The same for `pilot list` using API authentication.

**Comment by francescodifebbo** [comment]
I'm having this issue when trying to export the CSV though the API key authentication

**Comment by whalemare** [comment]
Still relevant in fastlane-2.187.0 with `fastlane pilot list`, `fastlane pilot import` with API Key auth.

`fastlane pilot export` works good

**Comment by kerrmarin-lvmh** [comment]
I'm also still seeing this in 2.187.0

**Comment by paour** [comment]
Still present in 2.189.0

**Comment by whalemare** [comment]
Bump

**Comment by paour** [comment]
Still present in 2.198.1

**Comment by paour** [comment]
This similar ticket indicates that these commands are not available with a keyfile. https://github.com/fastlane/fastlane/issues/18650

If this is the case, Fastlane might provide a more informative error.

**Comment by whalemare** [comment]
Still present

**Comment by markusl** [comment]
Is there any workaround for this issue?

Thanks,
Markus

**Comment by madjemian** [comment]
Confirmed I still encounter this on 2.205.0

**Comment by wuftymerguftyguff** [comment]
I still have this with 2.205.2
