### ISSUE TITLE
upload_app_privacy_details_to_app_store fails when NSUserTrackingUsageDescription is enabled

### ISSUE THREAD

**Issue by sidepelican** [fastlane/fastlane#17895]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

`upload_app_privacy_details_to_app_store` action fails in second time when the uploaded app binary has `NSUserTrackingUsageDescription` in `Info.plist`.

The error happens at this line.
https://github.com/fastlane/fastlane/blob/e2ff4990a44f28fa7b25d745666007dc8e315577/fastlane/lib/fastlane/actions/upload_app_privacy_details_to_app_store.rb#L138

error message:
 
```
Your binary indicates that your app tracks users. - Your app indicates that you track users.
```

It seems that once a category is registered with the NSUserTrackingUsageDescription enabled, it is not possible to delete all categories.
Even when I tried to delete them from the web console, I got the next error.

<img src=https://user-images.githubusercontent.com/19257572/103484810-ead49b80-4e34-11eb-8818-82af9b0ee9ff.png width=50%>
(japanese)

##### Command executed

```
❯ bundle exec fastlane upload_app_privacy_details publish:1
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
<pre>
[✔] 🚀 
[01:51:53]: ------------------------------
[01:51:53]: --- Step: default_platform ---
[01:51:53]: ------------------------------
/Users/iceman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/iceman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/errors/fastlane_error.rb:9: warning: The called method `initialize' is defined here
[01:51:53]: Driving the lane 'ios upload_app_privacy_details' 🚀
[01:51:53]: -----------------------------------------------------
[01:51:53]: --- Step: upload_app_privacy_details_to_app_store ---
[01:51:53]: -----------------------------------------------------
[01:51:53]: Login to App Store Connect (*************)
[01:51:54]: Login successful
[01:51:58]: Preparing to upload App Data Usage
+------------------+--------------------------------+
|                   Lane Context                    |
+------------------+--------------------------------+
| DEFAULT_PLATFORM | ios                            |
| PLATFORM_NAME    | ios                            |
| LANE_NAME        | ios upload_app_privacy_details |
+------------------+--------------------------------+
[01:51:59]: Your binary indicates that your app tracks users. - Your app indicates that you track users.

+------+-------------------------------+-------------+
|                  fastlane summary                  |
+------+-------------------------------+-------------+
| Step | Action                        | Time (in s) |
+------+-------------------------------+-------------+
| 1    | default_platform              | 0           |
| 💥   | upload_app_privacy_details_t  | 6           |
|      | o_app_store                   |             |
+------+-------------------------------+-------------+

[01:51:59]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Having deliver/upload_to_app_store issues? Install 2.150.0.rc5
    https://github.com/fastlane/fastlane/issues/16639 [closed] 116 💬
    04 Sep 2020

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/Users/iceman/.rbenv/versions/2.7.1/bin/fastlane)
Spaceship::UnexpectedResponse: [!] Your binary indicates that your app tracks users. - Your app indicates that you track users.
  /Users/iceman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.171.0/spaceship/lib/spaceship/connect_api/api_client.rb:193:in `handle_response'
  /Users/iceman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.171.0/spaceship/lib/spaceship/connect_api/api_client.rb:148:in `delete'
  /Users/iceman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.171.0/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:262:in `delete_app_data_usage'
  /Users/iceman/.rbenv/versions/2.7.1/lib/ruby/2.7.0/forwardable.rb:235:in `delete_app_data_usage'
  /Users/iceman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.171.0/spaceship/lib/spaceship/connect_api/models/app_data_usage.rb:55:in `delete!'
  /Users/iceman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/actions/upload_app_privacy_details_to_app_store.rb:138:in `each'
  /Users/iceman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/actions/upload_app_privacy_details_to_app_store.rb:138:in `upload_app_data_usages'
  /Users/iceman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/actions/upload_app_privacy_details_to_app_store.rb:43:in `run'
  /Users/iceman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  /Users/iceman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
  /Users/iceman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  /Users/iceman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  /Users/iceman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  /Users/iceman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/iceman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:22:in `block (2 levels) in parsing_binding'
  /Users/iceman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/iceman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/iceman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/iceman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/iceman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /Users/iceman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/iceman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/iceman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/iceman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/iceman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/iceman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/iceman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/iceman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  /Users/iceman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/iceman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Users/iceman/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.171.0/bin/fastlane:23:in `<top (required)>'
  /Users/iceman/.rbenv/versions/2.7.1/bin/fastlane:23:in `load'
  /Users/iceman/.rbenv/versions/2.7.1/bin/fastlane:23:in `<top (required)>'
</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.15.7                                          |
| Ruby                        | 2.7.1                                            |
| Bundler?                    | true                                             |
| Git                         | git version 2.28.0                               |
| Installation Source         | ~/.rbenv/versions/2.7.1/bin/fastlane             |
| Host                        | Mac OS X 10.15.7 (19H114)                        |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.1/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode_12.3.app/Contents/Developer/ |
| Xcode Version               | 12.3                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :upload_app_privacy_details do |options|
    publish = !!options[:publish]
    
    upload_app_privacy_details_to_app_store(
      username: "aaa@aaaaa.com",
      app_identifier: "aaa.aaa.aaa",
      json_path: "./fastlane/app_privacy_details.json",
      skip_publish: !publish
    )
  end
end

```
</details>

<details><summary>`./Appfile`</summary>

```ruby
app_identifier("aaa.aaa.aaa") # The bundle identifier of your app
apple_id("aaa@aaaaa.com") # Your Apple email address

itc_team_id("123") # App Store Connect Team ID
team_id("111") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.171.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| bundler                   | 2.1.4        |
| uri                       | 0.10.0       |
| rake                      | 13.0.3       |
| CFPropertyList            | 3.0.3        |
| concurrent-ruby           | 1.1.7        |
| i18n                      | 1.8.6        |
| minitest                  | 5.14.2       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.9        |
| activesupport             | 5.2.4.4      |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| httpclient                | 2.8.3        |
| json                      | 2.5.1        |
| algoliasearch             | 1.27.5       |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.414.0      |
| aws-sigv4                 | 1.2.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.110.0      |
| aws-sdk-kms               | 1.40.0       |
| aws-sdk-s3                | 1.87.0       |
| babosa                    | 1.0.4        |
| claide                    | 1.0.3        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| netrc                     | 0.11.0       |
| ffi                       | 1.14.2       |
| ethon                     | 0.12.0       |
| typhoeus                  | 1.4.0        |
| cocoapods-core            | 1.10.0       |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.4.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-trunk           | 1.5.0        |
| cocoapods-try             | 1.2.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| cocoapods                 | 1.10.0       |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.3        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.2.1        |
| excon                     | 0.78.1       |
| faraday-net_http          | 1.0.0        |
| multipart-post            | 2.0.0        |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.3.0        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.1        |
| jwt                       | 2.2.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| signet                    | 0.14.0       |
| googleauth                | 0.14.0       |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.4.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.2       |
| mini_magick               | 4.11.0       |
| plist                     | 3.6.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.1        |
</details>

*generated on:* **2021-01-04**
</details>

**Comment by rogerluan** [comment]
cc @ainame tagging you here in case you can help with the Japanese 🙈 

I think I understand this issue correctly though, but not sure what would be an appropriate fix here. Should we just run the same check that the App Store Connect seems to do, and throw a nicer error to the user?

@sidepelican what did you do to fix this issue, in App Store Connect?

**Comment by sidepelican** [comment]
I couldn't remove all the categories in App Store Connect, but I can add/delete individual categories as long as at least one category is added.

So I think this action needs to check current App Store's configuration and apply differences from json configuration. (but I'm not sure it can be done or not😢)

**Comment by rogerluan** [comment]
That's a very useful observation @sidepelican ! If that's really the case, we might need to implement an updating strategy there, like "replace all existing/matching keys, and then delete the ones that are not present in the new json" 🤔
