### ISSUE TITLE
Fastlane won't run

### ISSUE THREAD

**Issue by psrcek** [fastlane/fastlane#17903]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Fastlane does not run, worked fine last week.

I'm running fastlane in a flutter project, inside the docker image `alpine/bundle:latest` (current sha256: [fbface4774a0007dcb3351b36d58ef2447b74a7bf3763b74330d15027967c0b6](https://hub.docker.com/layers/alpine/bundle/latest/images/sha256-fbface4774a0007dcb3351b36d58ef2447b74a7bf3763b74330d15027967c0b6?context=explore))

<details>
  <summary>Fastfile</summary>

```
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)

platform :android do
  # Google play tracks: production, beta, alpha, internal

  lane :internal do
    upload_to_play_store(
      track: 'internal',
      aab: 'build/app/outputs/bundle/release/app-release.aab',
      in_app_update_priority: 5 # Int 1-5
    )
  end

  lane :beta do
    upload_to_play_store(
      track: 'beta',
      aab: 'build/app/outputs/bundle/release/app-release.aab',
      in_app_update_priority: 5 # Int 1-5
    )
  end
end

platform :ios do
  lane :build do
    build_ios_app(
      workspace: "ios/Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store"
    )
  end

  lane :beta do
    sh "security unlock-keychain -p '[redacted]' \"$HOME/Library/Keychains/login.keychain\""

    # sync_code_signing(type: "appstore") 
    # get_certificates
    # get_provisioning_profile

    cert
    sigh(force: true)

    upload_to_testflight(
      localized_app_info: {
        "default": {
          feedback_email: "[redacted]",
          marketing_url: "[redacted]",
          privacy_policy_url: "[redacted]",
          description: "[redacted]",
        }
      },
      beta_app_review_info: {
        contact_email: "[redacted]",
        contact_first_name: "[redacted]",
        contact_last_name: "[redacted]",
        contact_phone: "[redacted]",
        demo_account_name: "[redacted]",
        demo_account_password: "[redacted]",
        notes: "New version"
      }
    )

    # upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
```
</details>

##### Command executed

fastlane internal

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
root@f3de4e50ca1f:/aio# fastlane internal
[10:55:55]: ------------------------------
[10:55:55]: --- Step: default_platform ---
[10:55:55]: ------------------------------
[10:55:55]: Driving the lane 'android internal' 🚀
[10:55:55]: /usr/local/bundle/gems/fastlane-1.92.0/lib/fastlane/runner.rb:101:in `rescue in trigger_action_by_name'
/usr/local/bundle/gems/fastlane-1.92.0/lib/fastlane/runner.rb:96:in `trigger_action_by_name'
/usr/local/bundle/gems/fastlane-1.92.0/lib/fastlane/fast_file.rb:140:in `method_missing'
Fastfile:22:in `block (2 levels) in parsing_binding'
/usr/local/bundle/gems/fastlane-1.92.0/lib/fastlane/lane.rb:33:in `call'
/usr/local/bundle/gems/fastlane-1.92.0/lib/fastlane/runner.rb:50:in `block in execute'
/usr/local/bundle/gems/fastlane-1.92.0/lib/fastlane/runner.rb:46:in `chdir'
/usr/local/bundle/gems/fastlane-1.92.0/lib/fastlane/runner.rb:46:in `execute'
/usr/local/bundle/gems/fastlane-1.92.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
/usr/local/bundle/gems/fastlane-1.92.0/lib/fastlane/command_line_handler.rb:30:in `handle'
/usr/local/bundle/gems/fastlane-1.92.0/lib/fastlane/commands_generator.rb:42:in `block (2 levels) in run'
/usr/local/bundle/gems/commander-4.5.2/lib/commander/command.rb:184:in `call'
/usr/local/bundle/gems/commander-4.5.2/lib/commander/command.rb:155:in `run'
/usr/local/bundle/gems/commander-4.5.2/lib/commander/runner.rb:452:in `run_active_command'
/usr/local/bundle/gems/fastlane_core-0.59.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
/usr/local/bundle/gems/commander-4.5.2/lib/commander/delegates.rb:15:in `run!'
/usr/local/bundle/gems/fastlane-1.92.0/lib/fastlane/commands_generator.rb:175:in `run'
/usr/local/bundle/gems/fastlane-1.92.0/lib/fastlane/commands_generator.rb:13:in `start'
/usr/local/bundle/gems/fastlane-1.92.0/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
/usr/local/bundle/gems/fastlane-1.92.0/bin/fastlane:5:in `<top (required)>'
/usr/local/bundle/bin/fastlane:23:in `load'
/usr/local/bundle/bin/fastlane:23:in `<main>'
[10:55:55]: Variable Dump:
[10:55:55]: {:DEFAULT_PLATFORM=>:android, :PLATFORM_NAME=>:android, :LANE_NAME=>"android internal"}
[10:55:55]: Could not find action or lane 'upload_to_play_store'. Check out the README for more details: https://github.com/fastlane/fastlane/tree/master/fastlane

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
+------+------------------+-------------+

[10:55:55]: fastlane finished with errors

[!] Could not find action or lane 'upload_to_play_store'. Check out the README for more details: https://github.com/fastlane/fastlane/tree/master/fastlane
  </pre>
</details>

### Environment

<details>
  <pre>
root@f3de4e50ca1f:/aio# fastlane env
[10:48:30]: ------------------------------
[10:48:30]: --- Step: default_platform ---
[10:48:30]: ------------------------------
[10:48:30]: Variable Dump:
[10:48:30]: {:DEFAULT_PLATFORM=>:android}
[10:48:30]: Could not find lane 'android env'. Available lanes: android internal, android beta, ios build, ios beta
[10:48:30]: Sending Crash/Success information. More information on: https://github.com/fastlane/enhancer
[10:48:30]: No personal/sensitive data is sent. Only sharing the following:
[10:48:30]: {:default_platform=>1}
[10:48:30]: This information is used to fix failing actions and improve integrations that are often used.
[10:48:30]: You can disable this by adding `opt_out_usage` to your Fastfile

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
+------+------------------+-------------+

[10:48:30]: fastlane finished with errors

[!] Could not find lane 'android env'. Available lanes: android internal, android beta, ios build, ios beta
  </pre>
</details>

**Comment by psrcek** [comment]
> It seems like you have not included the output of `fastlane env`
> To make it easier for us help you resolve this issue, please update the issue to include the output of `fastlane env`

Yes I have...

**Comment by ainame** [comment]
> ENV RUBY_VERSION=3.0.0

Hey, it looks like you are trying to use Ruby 3.0 but fastlane hasn't supported it yet to install. Please try Ruby 2.7 or older.

**Comment by psrcek** [comment]
Fastlane should be the latest one, as I've done `bundle install`
Anyway, the ruby docker image I was using updated to ruby 3.0, that's what broke it, thanks :smiley:
