### ISSUE TITLE
Error Domain=IDEFoundationErrorDomain Code=1 "IPA processing failed" UserInfo={NSLocalizedDescription=IPA processing failed} on Apple Silicon M1 (ARM64) 

### ISSUE THREAD

**Issue by cikichen** [fastlane/fastlane#17914]
```
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/t1/t4n_16gn7pn2p6fyrpj84g340000gn/T/gym_config20210107-28566-1xjaodt.plist -archivePath '/Users/xxx/Library/Developer/Xcode/Archives/2021-01-07/Runner_Release_20210107160543 2021-01-07 16.05.44.xcarchive' -exportPath /var/folders/t1/t4n_16gn7pn2p6fyrpj84g340000gn/T/gym_output20210107-28566-4tlxs8 -allowProvisioningUpdates
objc[30373]: Class AMSupportURLConnectionDelegate is implemented in both ?? (0x2099438f0) and ?? (0x1181942b8). One of the two will be used. Which one is undefined.
objc[30373]: Class AMSupportURLSession is implemented in both ?? (0x209943940) and ?? (0x118194308). One of the two will be used. Which one is undefined.
2021-01-07 16:06:36.778 xcodebuild[30373:980431] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/t1/t4n_16gn7pn2p6fyrpj84g340000gn/T/Runner_2021-01-07_16-06-36.778.xcdistributionlogs'.
error: exportArchive: IPA processing failed

Error Domain=IDEFoundationErrorDomain Code=1 "IPA processing failed" UserInfo={NSLocalizedDescription=IPA processing failed}

** EXPORT FAILED **
[16:06:37]: Exit status: 70

+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.171.0                 |
| export_method | ad-hoc                  |
| sdk           | iPhoneOS14.3.sdk        |
+---------------+-------------------------+
```

**Comment by cikichen** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 11.1                                                       |
| Ruby                        | 2.7.2                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.24.3 (Apple Git-128)                         |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.171.0/libexec/bin/fastlane |
| Host                        | macOS 11.1 (20C69)                                         |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby@2.7/2.7.2/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                                 |
| Is contained                | false                                                      |
| Is homebrew                 | true                                                       |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
| Xcode Version               | 12.3                                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_app_store
  end
 desc "Push a new release build to the Ad Hoc"
  lane :release_adhoc do |option|
    # cocoapods
  # increment_version_number(version_number: option[:version]) 
  #increment_build_number
    update_project_provisioning(
        profile:"fastlane/provision/comauthineh3yun_Adhoc.mobileprovision",
        build_configuration:"Release"
    )
    automatic_code_signing(
        path:"Runner.xcodeproj",
        use_automatic_signing:false,
        team_id:"MD45C2K773",
        targets:"Runner",
        code_sign_identity:"Apple Distribution",
        profile_name:"com.authine.h3yun_Adhoc"
    )
    scheme_name = 'Runner'
    configuration = 'Release'
    version = get_info_plist_value(path: "./#{scheme_name}/Info.plist", key: "CFBundleShortVersionString")
    build = get_info_plist_value(path: "./#{scheme_name}/Info.plist", key: "CFBundleVersion")
    output_directory = File.expand_path("..", Dir.pwd) + File::Separator + 'build'
    output_name = "#{scheme_name}_#{configuration}_#{Time.now.strftime('%Y%m%d%H%M%S')}.ipa"
    gym(
      scheme: scheme_name, 
      clean: true, 
      silent:true,
      export_method:'ad-hoc', 
      export_options: {
          provisioningProfiles: { 
          "com.authine.h3yun" => "com.authine.h3yun_Adhoc"
        }},
        configuration: configuration, 
        output_directory: output_directory, 
        output_name: output_name, 
        codesigning_identity:'Apple Distribution: Ping Jun Xu (MD45C2K773)',
        export_xcargs: '-allowProvisioningUpdates')
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.authine.h3yun") # The bundle identifier of your app
apple_id("Othinker_H3@hotmail.com") # Your Apple email address

itc_team_id("941816") # App Store Connect Team ID
team_id("MD45C2K773") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.171.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.6.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.4        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.78.1       |
| faraday-net_http          | 1.0.0        |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.3.0        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.1        |
| gh_inspector              | 1.1.3        |
| json                      | 2.3.0        |
| mini_magick               | 4.11.0       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.14.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.4.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.3       |
| digest-crc                | 0.6.3        |
| google-cloud-storage      | 1.29.2       |
| emoji_regex               | 3.2.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.414.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.110.0      |
| aws-sdk-kms               | 1.40.0       |
| aws-sdk-s3                | 1.87.0       |
| uri                       | 0.10.0       |
| forwardable               | 1.3.1        |
| logger                    | 1.4.2        |
| cgi                       | 0.1.0        |
| date                      | 3.0.0        |
| timeout                   | 0.1.0        |
| stringio                  | 0.1.0        |
| zlib                      | 1.1.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.2.0        |
| strscan                   | 1.0.3        |
| delegate                  | 0.1.0        |
| fileutils                 | 1.4.1        |
| io-console                | 0.5.6        |
| singleton                 | 0.1.0        |
| rexml                     | 3.2.3        |
| open3                     | 0.1.0        |
| yaml                      | 0.1.0        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>


*generated on:* **2021-01-07**
</details>

**Comment by tfonfara** [comment]
Having the same issue. This seems to be a bug of Xcode, I've already created a bug report on Apple Feedback Assistant.
Maybe fastlane can trigger xcodebuild using Rosetta? (here's an article about this: https://gregmfoster.medium.com/using-m1-mac-minis-to-power-our-github-actions-ios-ci-540c55af13ea)

**Comment by rogerluan** [comment]
@cikichen can you update your issue description using [our issue template](https://raw.githubusercontent.com/fastlane/fastlane/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md)? 🙏

**Comment by josh-burton** [comment]
I've got the same issue. Creating an archive within xcode works fine, but fails when using fastlane.

If I run fastlane under rosetta (`arch -x86_64 fastlane ios ...`) then it works as well.

**Comment by tfonfara** [comment]
Try the latest Xcode beta version. The bug seems to be fixed there!

**Comment by josh-burton** [comment]
@tfonfara thanks you're right! it's working with the latest beta.

**Comment by techinpark** [comment]
@tfonfara @josh-burton  Xcode 12.5 Version work fine?

**Comment by josh-burton** [comment]
Yes 12.5 fixes the issue. Of course I've run into a couple of dependencies that now don't work with the beta version of xcode.

A temporary work around in fastlane would be nice but maybe not possible.

**Comment by TsingYii** [comment]
> I've got the same issue. Creating an archive within xcode works fine, but fails when using fastlane.
> 
> If I run fastlane under rosetta (`arch -x86_64 fastlane ios ...`) then it works as well.

work for me,thanks
