### ISSUE TITLE
Taking screenshots: build working but "undefined method `each' for nil:NilClass "

### ISSUE THREAD

**Issue by Reiszecke** [fastlane/fastlane#17911]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
The console prints ```undefined method `each' for nil:NilClass```

##### Command executed
bundle exec fastlane ios screenshots --verbose

##### Complete output when running fastlane, including the stack trace and command used
<details>
ERROR [2021-01-06 20:29:10.47]: fastlane finished with errors
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
Traceback (most recent call last):
	44: from /usr/local/bin/bundle:23:in `<main>'
	43: from /usr/local/bin/bundle:23:in `load'
	42: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.3/exe/bundle:37:in `<top (required)>'
	41: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.3/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	40: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.3/exe/bundle:49:in `block in <top (required)>'
	39: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.3/lib/bundler/cli.rb:24:in `start'
	38: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	37: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.3/lib/bundler/cli.rb:30:in `dispatch'
	36: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	35: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	34: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	33: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.3/lib/bundler/cli.rb:497:in `exec'
	32: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:28:in `run'
	31: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:63:in `kernel_load'
	30: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:63:in `load'
	29: from /usr/local/bin/fastlane:23:in `<top (required)>'
	28: from /usr/local/bin/fastlane:23:in `load'
	27: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/bin/fastlane:5:in `<top (required)>'
	26: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	25: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/commands_generator.rb:13:in `start'
	24: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/commands_generator.rb:175:in `run'
	23: from /Library/Ruby/Gems/2.6.0/gems/commander-4.5.2/lib/commander/delegates.rb:15:in `run!'
	22: from /Library/Ruby/Gems/2.6.0/gems/fastlane_core-0.59.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	21: from /Library/Ruby/Gems/2.6.0/gems/commander-4.5.2/lib/commander/runner.rb:452:in `run_active_command'
	20: from /Library/Ruby/Gems/2.6.0/gems/commander-4.5.2/lib/commander/command.rb:155:in `run'
	19: from /Library/Ruby/Gems/2.6.0/gems/commander-4.5.2/lib/commander/command.rb:184:in `call'
	18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/commands_generator.rb:42:in `block (2 levels) in run'
	17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/runner.rb:46:in `execute'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/runner.rb:46:in `chdir'
	13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/runner.rb:50:in `block in execute'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/lane.rb:33:in `call'
	11: from Fastfile:22:in `block (2 levels) in parsing_binding'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/runner.rb:109:in `trigger_action_by_name'
	 8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/runner.rb:161:in `execute_action'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/runner.rb:161:in `chdir'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/runner.rb:162:in `block in execute_action'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/runner.rb:177:in `block (2 levels) in execute_action'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/actions/snapshot.rb:17:in `run'
	 2: from /Library/Ruby/Gems/2.6.0/gems/snapshot-1.16.4/lib/snapshot/runner.rb:60:in `work'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane_core-0.59.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
/Library/Ruby/Gems/2.6.0/gems/fastlane_core-0.59.0/lib/fastlane_core/ui/interface.rb:145:in `user_error!': undefined method `each' for nil:NilClass (FastlaneCore::Interface::FastlaneError)
	44: from /usr/local/bin/bundle:23:in `<main>'
	43: from /usr/local/bin/bundle:23:in `load'
	42: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.3/exe/bundle:37:in `<top (required)>'
	41: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.3/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	40: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.3/exe/bundle:49:in `block in <top (required)>'
	39: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.3/lib/bundler/cli.rb:24:in `start'
	38: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	37: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.3/lib/bundler/cli.rb:30:in `dispatch'
	36: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	35: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	34: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	33: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.3/lib/bundler/cli.rb:497:in `exec'
	32: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:28:in `run'
	31: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:63:in `kernel_load'
	30: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:63:in `load'
	29: from /usr/local/bin/fastlane:23:in `<top (required)>'
	28: from /usr/local/bin/fastlane:23:in `load'
	27: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/bin/fastlane:5:in `<top (required)>'
	26: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	25: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/commands_generator.rb:13:in `start'
	24: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/commands_generator.rb:175:in `run'
	23: from /Library/Ruby/Gems/2.6.0/gems/commander-4.5.2/lib/commander/delegates.rb:15:in `run!'
	22: from /Library/Ruby/Gems/2.6.0/gems/fastlane_core-0.59.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	21: from /Library/Ruby/Gems/2.6.0/gems/commander-4.5.2/lib/commander/runner.rb:452:in `run_active_command'
	20: from /Library/Ruby/Gems/2.6.0/gems/commander-4.5.2/lib/commander/command.rb:155:in `run'
	19: from /Library/Ruby/Gems/2.6.0/gems/commander-4.5.2/lib/commander/command.rb:184:in `call'
	18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/commands_generator.rb:42:in `block (2 levels) in run'
	17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/runner.rb:46:in `execute'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/runner.rb:46:in `chdir'
	13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/runner.rb:50:in `block in execute'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/lane.rb:33:in `call'
	11: from Fastfile:22:in `block (2 levels) in parsing_binding'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/runner.rb:109:in `trigger_action_by_name'
	 8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/runner.rb:161:in `execute_action'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/runner.rb:161:in `chdir'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/runner.rb:162:in `block in execute_action'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/runner.rb:177:in `block (2 levels) in execute_action'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-1.92.0/lib/fastlane/actions/snapshot.rb:17:in `run'
	 2: from /Library/Ruby/Gems/2.6.0/gems/snapshot-1.16.4/lib/snapshot/runner.rb:60:in `work'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane_core-0.59.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
/Library/Ruby/Gems/2.6.0/gems/fastlane_core-0.59.0/lib/fastlane_core/ui/interface.rb:145:in `user_error!': [!] undefined method `each' for nil:NilClass (FastlaneCore::Interface::FastlaneError)
</details>

--

I pretty much followed the steps that the fastlane setup walks you through (told the prompt that I only want to capture screenshots, no App Store upload). I think I had to manually add the scheme to the Fastfile but eventually I got the first bit running. Had to fix 2 compiler errors in the SnapshotHelper.swift so building worked as well, Fastlane seems to recognize my project's files (I can see all the .swift files being compiled). However it stops at

--

<details>

[20:21:29]: ▸ All tests
[20:21:29]: ▸ Test Suite UITestScheme.xctest started
[20:21:29]: ▸ UITestScheme
[20:21:36]: ▸ ✓ testExample (7.028 seconds)
[20:21:56]: ▸ ✓ testLaunchPerformance (19.683 seconds)
[20:21:56]: ▸ 	 Executed 2 tests, with 0 failures (0 unexpected) in 26.712 (26.714) seconds
[20:21:56]: ▸ 
[20:21:56]: ▸ 2021-01-06 20:21:56.311 xcodebuild[00000:1234567] [MT] IDETestOperationsObserverDebug: 42.384 elapsed -- Testing started completed.
[20:21:56]: ▸ 2021-01-06 20:21:56.311 xcodebuild[00000:1234567] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
[20:21:56]: ▸ 2021-01-06 20:21:56.311 xcodebuild[00000:1234567] [MT] IDETestOperationsObserverDebug: 42.384 sec, +42.384 sec -- end
[20:21:56]: ▸ Test Succeeded
[20:22:02]: Collecting screenshots...
[20:22:02]: undefined method `each' for nil:NilClass

+-----------+---------+
|  snapshot results   |
+-----------+---------+
| Device    | en-US   |
+-----------+---------+
| iPhone 12 |  ❌      |
+-----------+---------+

[20:22:02]: Variable Dump:
[20:22:02]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios screenshots"}
[20:22:02]: undefined method `each' for nil:NilClass

</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.7                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.30.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.7 (19H2)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.1                                                           |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    #capture_screenshots(scheme: "UITestScheme")
    snapshot
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifie00000000000000000ndle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.171.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.4        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.78.1       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday-net_http          | 1.0.0        |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.3.0        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.1        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.11.0       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.1        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.2.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.14.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.4.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 12.3.2       |
| digest-crc                | 0.6.3        |
| google-cloud-storage      | 1.29.2       |
| emoji_regex               | 3.2.1        |
| jmespath                  | 1.4.0        |
000000000000000000000000
| CFPropertyList            | 3.0.3        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.6.0        |
| json                      | 2.1.0        |
| uber                      | 0.1.0        |
| retriable                 | 3.1.2        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
000000000000000000000000
| date                      | 2.0.0        |
| stringio                  | 0.0.2        |
| zlib                      | 1.0.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>

*generated on:* **2021-01-06**
</details>

**Comment by peterkuiper** [comment]
I have the same problem. I did some digging and the problem occurs [here](https://github.com/fastlane/fastlane/blob/48151291f2c4949c3b1b9919ba2cc81a7cc33293/snapshot/lib/snapshot/collector.rb#L87). 

The plist file does not contain `TestableSummaries`, causing the loop to fail. From the logs:
```
INFO [2021-01-27 16:07:43.76]: ▸ Test Succeeded
INFO [2021-01-27 16:07:49.84]: Collecting screenshots...
DEBUG [2021-01-27 16:07:49.84]: Loading up '/Users/xxxxx/Library/Developer/Xcode/DerivedData/xxxx/Logs/Test/LogStoreManifest.plist'...
```

The plist file:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>logFormatVersion</key>
	<integer>10</integer>
	<key>logs</key>
	<dict>
		<key>xxxx</key>
		<dict>
			<key>auxiliaryLogUniqueIdentifier</key>
			<string>xxxx</string>
			<key>auxiliaryObservable</key>
			<dict>
				<key>highLevelStatus</key>
				<string>W</string>
			</dict>
			<key>className</key>
			<string>IDESchemeActionsInvocationRecord</string>
			<key>documentTypeString</key>
			<string>&lt;nil&gt;</string>
			<key>domainType</key>
			<string>com.apple.dt.unit.cocoaUnitTest</string>
			<key>fileName</key>
			<string>Run-xxx.xcresult</string>
			<key>hasAuxiliaryLog</key>
			<true/>
			<key>hasPrimaryLog</key>
			<true/>
			<key>primaryObservable</key>
			<dict>
				<key>highLevelStatus</key>
				<string>W</string>
			</dict>
			<key>schemeIdentifier-containerName</key>
			<string>xxxx project</string>
			<key>schemeIdentifier-schemeName</key>
			<string>xxxx</string>
			<key>schemeIdentifier-sharedScheme</key>
			<integer>1</integer>
			<key>signature</key>
			<string>Run xxxx</string>
			<key>timeStartedRecording</key>
			<real>xxxx</real>
			<key>timeStoppedRecording</key>
			<real>0.0</real>
			<key>title</key>
			<string>Run xxxxx</string>
			<key>uniqueIdentifier</key>
			<string>xxxxx</string>
		</dict>
	</dict>
</dict>
</plist>
```

`SnapshotHelper.swift` has no real logic in the `snapshot` method, so I assume it is up to Xcode to create the screenshot. I have no idea why it doesn't work. I am using it in a React Native project (0.63.4).

@Reiszecke Can you share your test file?

**Comment by peterkuiper** [comment]
I was able to solve this problem by first removing all instances of Fastlane (`brew uninstall fastlane`) and removing my local gems in `~/.gem`. I use `rbenv` but for some reason it didn't work correctly. I made sure to have the following at the end of my `~/zshrc` : 

```
eval "$(rbenv init -)"
export PATH="$HOME/.rbenv/bin:$PATH"
```

Restart your terminal or run `source ~/.zshrc`. Next, I installed Ruby version `2.7.2`:

```
rbenv install 2.7.2
rbenv global 2.7.2
```

Make sure `gem env home` has the following output:

```
/Users/xxx/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0
```

The last step was just `gem install fastlane` and everything started working. Please note that the [documentation](https://docs.fastlane.tools/getting-started/ios/setup/#a-gemfile-macoslinuxwindows) recommends adding a `Gemfile` to your project.
