### ISSUE TITLE
Mismatch between Fastlane export_method and xcodebuild export_method

### ISSUE THREAD

**Issue by nickplee** [fastlane/fastlane#17918]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

According to `$ xcodebuild -help`, the `method` key of an export options should support the value `mac-application`:

```
Describes how Xcode should export the archive. Available options: app-store, validation, ad-hoc, package, enterprise, development, developer-id, and mac-application. The list of options varies based on the type of archive. Defaults to development.
```

However, when specified in my Fastfile, it fails validation:

```
build_mac_app(export_method: 'mac-application')
```

##### Command executed

```
bundle exec fastlane build
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [✔] 🚀 
[16:53:21]: ------------------------------
[16:53:21]: --- Step: default_platform ---
[16:53:21]: ------------------------------
/Users/nicklee/.rvm/gems/ruby-2.7.0/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/nicklee/.rvm/gems/ruby-2.7.0/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/errors/fastlane_error.rb:9: warning: The called method `initialize' is defined here
[16:53:21]: Driving the lane 'mac build' 🚀
[16:53:21]: Error setting value 'mac-application' for option 'export_method'
[16:53:21]: You passed invalid parameters to 'build_mac_app'.
[16:53:21]: Check out the error below and available options by running `fastlane action build_mac_app`
+------------------+-----------+
|         Lane Context         |
+------------------+-----------+
| DEFAULT_PLATFORM | mac       |
| PLATFORM_NAME    | mac       |
| LANE_NAME        | mac build |
+------------------+-----------+
[16:53:21]: Unsupported export_method 'mac-application', must be: ["app-store", "ad-hoc", "package", "enterprise", "development", "developer-id"]

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
+------+------------------+-------------+

[16:53:21]: fastlane finished with errors

[!] Unsupported export_method 'mac-application', must be: ["app-store", "ad-hoc", "package", "enterprise", "development", "developer-id"]</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.6                                     |
| Ruby                        | 2.7.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.rvm/gems/ruby-2.7.0/bin/fastlane         |
| Host                        | Mac OS X 10.15.6 (19G2021)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.7.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.3                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform(:mac)

platform :mac do
  desc 'Runs the linter and all tests'
  lane :test do
    swiftlint(
      strict: true,
      reporter: 'emoji',
    )

    run_tests(
      project: '< REDACTED >',
      scheme: '< REDACTED >',
    )
  end

  desc 'Builds and archives the app'
  lane :build do
    build_mac_app(scheme: '< REDACTED >', export_method: 'mac-application')
  end
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.171.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| rake                      | 13.0.3       |
| CFPropertyList            | 3.0.3        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.415.0      |
| aws-sigv4                 | 1.2.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.110.0      |
| aws-sdk-kms               | 1.40.0       |
| aws-sdk-s3                | 1.87.0       |
| babosa                    | 1.0.4        |
| bundler                   | 2.1.4        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.3        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.2.1        |
| excon                     | 0.78.1       |
| faraday-net_http          | 1.0.0        |
| multipart-post            | 2.0.0        |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.3.0        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.1        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.2.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| signet                    | 0.14.0       |
| googleauth                | 0.14.0       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.4.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.2       |
| json                      | 2.5.1        |
| mini_magick               | 4.11.0       |
| plist                     | 3.6.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.1        |
</details>

*generated on:* **2021-01-07**
</details>

**Comment by rogerluan** [comment]
Hey @nickplee 👋 

Just opened a PR fixing this issue 😃 https://github.com/fastlane/fastlane/pull/17939
