### ISSUE TITLE
Clarification: How can I upload build if I have different environments (dev, stage, test and prod) and diffferentiate the env in fastfile

### ISSUE THREAD

**Issue by nihp** [fastlane/fastlane#17941]
I have four environments(com.app.dev, com.app.stage, com.app.prod, com.app.test) in my firebase account. 

Here how can I set the build for dev release build for android.

Now I have tried to upload the build to firebase after adding the plugin, but it failed to upload in my dev release because of the stage app id.

Here how can I differentiate the environments in my Fastfile

```

[!] App Distribution halted because it had a problem uploading the APK: There's been an error processing your upload.
The APK package name 'com.app.stage' does not match your Firebase app's package name 'com.app.dev'. Change the APK package name to 'com.app.dev' and retry the upload.
```

**Comment by nihp** [comment]
[✔] 🚀 
undefined method `lane' for #<CredentialsManager::AppfileConfig:0x000>
undefined method `lane' for #<CredentialsManager::AppfileConfig:0x0000>
[09:19:33]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.3                                     |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.27.0                          |
| Installation Source         | ~/.rvm/gems/ruby-2.5.1/bin/fastlane         |
| Host                        | Mac OS X 10.15.3 (19D76)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.5.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0h  27 Mar 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.3.1                                      |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Firebase App Distribution"
  lane :beta do

   gradle(task: "clean assembleRelease")

    firebase_app_distribution(
        release_notes: "Lots of amazing new features to test out!"
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("com.app.dev") # e.g. com.krausefx.app

lane :beta do
  # Adjust the `build_type` and `flavor` params as needed to build the right APK for your setup
  gradle(
    task: 'assemble',
    build_type: 'Release'
  )

desc "Submit a new Beta Build to Firebase App Distribution"
lane :beta do
  build

  firebase_app_distribution(
      release_notes: "Lots of amazing new features to test out!"
  )
end
  # ...
end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.171.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.2.5   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.2.0        |
| executable-hooks                          | 1.4.2        |
| bundler-unload                            | 1.0.2        |
| rubygems-bundler                          | 1.4.4        |
| bundler                                   | 2.0.2        |
| rake                                      | 13.0.3       |
| CFPropertyList                            | 3.0.3        |
| public_suffix                             | 4.0.6        |
| addressable                               | 2.7.0        |
| atomos                                    | 0.1.3        |
| aws-eventstream                           | 1.1.0        |
| aws-partitions                            | 1.415.0      |
| aws-sigv4                                 | 1.2.2        |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.110.0      |
| aws-sdk-kms                               | 1.40.0       |
| aws-sdk-s3                                | 1.87.0       |
| babosa                                    | 1.0.4        |
| claide                                    | 1.0.3        |
| colored                                   | 1.2          |
| colored2                                  | 3.1.2        |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| declarative                               | 0.0.20       |
| declarative-option                        | 0.1.0        |
| digest-crc                                | 0.6.3        |
| unf_ext                                   | 0.0.7.7      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| dotenv                                    | 2.7.6        |
| emoji_regex                               | 3.2.1        |
| excon                                     | 0.78.1       |
| faraday-net_http                          | 1.0.0        |
| multipart-post                            | 2.0.0        |
| ruby2_keywords                            | 0.0.2        |
| faraday                                   | 1.3.0        |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.0.0        |
| fastimage                                 | 2.2.1        |
| gh_inspector                              | 1.1.3        |
| jwt                                       | 2.2.2        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.1        |
| signet                                    | 0.14.0       |
| googleauth                                | 0.14.0       |
| httpclient                                | 2.8.3        |
| mini_mime                                 | 1.0.2        |
| uber                                      | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| google-api-client                         | 0.38.0       |
| google-cloud-env                          | 1.4.0        |
| google-cloud-errors                       | 1.0.1        |
| google-cloud-core                         | 1.5.0        |
| google-cloud-storage                      | 1.29.2       |
| json                                      | 2.5.1        |
| mini_magick                               | 4.11.0       |
| plist                                     | 3.6.0        |
| rubyzip                                   | 2.3.0        |
| security                                  | 0.1.3        |
| naturally                                 | 2.2.0        |
| simctl                                    | 1.6.8        |
| slack-notifier                            | 2.3.2        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.7.0        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| word_wrap                                 | 1.0.0        |
| nanaimo                                   | 0.3.0        |
| xcodeproj                                 | 1.19.0       |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.1        |
| fastlane-plugin-firebase_app_distribution | 0.2.5        |
</details>


*generated on:* **2021-01-11**

**Comment by rogerluan** [comment]
Pass the environment at the moment you call your lane, as an argument. Parse that argument in your lane and based on the environment passed, you use different arguments on your actions/lanes/methods

**Comment by nihp** [comment]
Can you give any sample Fastfile.

Now I have my build.gradle productFlavours have four environments.

**Comment by rogerluan** [comment]
Lane example:

```ruby
desc "Build TellusCore aar, bundle exec fastlane android buildCore buildType:[Debug|Sandbox] (Optional)"
lane :my_lane do |options|
    environment = options[:environment] || "debug"
    gradle(
        task: "my_app:assemble",
        build_type: "#{environment}",
    )
 end
```

Invoke it: `bundle exec fastlane my_lane environment:production`

Check out how to use lane arguments here: https://docs.fastlane.tools/advanced/lanes/

**Comment by nihp** [comment]
How can I set the package name. 

Now I have added only one package and it is available in AppFile. But how can I add the package name in the Fastfile
