### ISSUE TITLE
change_password does not work

### ISSUE THREAD

**Issue by mdentremont** [fastlane/fastlane#17968]
The change_password functionality is still broken as per the details on: https://github.com/fastlane/fastlane/issues/15942

I believe that having a `.env.default` file also breaks things similar to having a `MATCH_PASSWORD` environment variable present.

**Comment by Collier11** [comment]
Yup include the output fastlane env it works.

**Comment by mdentremont** [comment]
I ended up just recreating the entire repository. Now that things are working fine on Github Actions I'll just take your word that it works 👍

**Comment by rogerluan** [comment]
@mdentremont don't take into account what that previous user said, it's a spam account.

**Comment by rogerluan** [comment]
I opened a PR to resolve this issue @mdentremont https://github.com/fastlane/fastlane/pull/18389 if you could test it in your flow, that'd be super! 🤗
