### ISSUE TITLE
fast lane build always fail, but use my Xcode archive works fine

### ISSUE THREAD

**Issue by Santiago0412** [fastlane/fastlane#17969]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

My fastlane build always fail but my Xcode archive work fine,I use automatic sign, and I set all the targets in my project codesign as automatic, not sure why this happened, here is the error message:

##### Command executed

# release notes in firebase
releaseNotesString=""

default_platform(:ios)
platform :ios do
    # distribute develop build to firebase
    desc "Test build for MyApp"
    lane :distributeTest do
        increment_build_number
        build_app(
            scheme: "MyApp",
            export_options: {
                method: "development"
                # method: "ad-hoc"
            }
        )
        update_code_signing_settings(
          use_automatic_signing: true,
          path: "MyApp.xcodeproj"
        )
        firebase_app_distribution(
            firebase_cli_token: "xxxxxxx",
            testers: "",
            release_notes: releaseNotesString
        )
    end
end

##### Complete output when running fastlane, including the stack trace and command used

** ARCHIVE FAILED **

The following build commands failed:
    CodeSign /Users/user/Library/Developer/Xcode/DerivedData/MyApp-gclrgsjclaoajzbsolwnugqqsiji/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/WatchListWidget.appex
(1 failure)
[14:38:30]: Exit status: 65

+-------------+-------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.171.0                 |
| sdk         | iPhoneOS14.3.sdk        |
+-------------+-------------------------+

[14:38:30]: ▸ warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'path_provider' from project 'Pods')
[14:38:30]: ▸ warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'native_shared_preferences' from project 'Pods')
[14:38:30]: ▸ warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'flutter_boost' from project 'Pods')
[14:38:30]: ▸ warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'ReCaptcha' from project 'Pods')
[14:38:30]: ▸ warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'FlutterPluginRegistrant' from project 'Pods')
[14:38:30]: 
[14:38:30]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[14:38:30]: 📋  For the complete and more detailed error log, check the full log at:
[14:38:30]: 📋  /Users/user/Library/Logs/gym/MyApp-MyApp.log
[14:38:30]: 
[14:38:30]: Looks like fastlane ran into a build/archive error with your project
[14:38:30]: It's hard to tell what's causing the error, so we wrote some guides on how
[14:38:30]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[14:38:30]: Before submitting an issue on GitHub, please follow the guide above and make
[14:38:30]: sure your project is set up correctly.
[14:38:30]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
[14:38:30]: the full commands printed out in yellow in the above log.
[14:38:30]: Make sure to inspect the output above, as usually you'll find more error information there
[14:38:30]: 
+------------------+--------------------+
|             Lane Context              |
+------------------+--------------------+
| DEFAULT_PLATFORM | ios                |
| PLATFORM_NAME    | ios                |
| LANE_NAME        | ios distributeTest |
| BUILD_NUMBER     | 5                  |
+------------------+--------------------+
[14:38:30]: Error building the application - see the log above

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | default_platform       | 0           |
| 2    | increment_build_number | 0           |
| 💥   | build_app              | 96          |
+------+------------------------+-------------+

[14:38:30]: fastlane finished with errors

[!] Error building the application - see the log above
<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/10152008/104692011-3004a180-5742-11eb-8adf-d6b6f8abdb45.png">

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by Santiago0412** [comment]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 10.15.6                                                 |
| Ruby                        | 2.7.2                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.24.3 (Apple Git-128)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.171.0/libexec/bin/fastlane |
| Host                        | Mac OS X 10.15.6 (19G73)                                |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.7/2.7.2/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                              |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 12.3                                                    |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.171.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.6.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.4        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.78.1       |
| faraday-net_http          | 1.0.0        |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.3.0        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.1        |
| gh_inspector              | 1.1.3        |
| json                      | 2.3.0        |
| mini_magick               | 4.11.0       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.14.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.4.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.3       |
| digest-crc                | 0.6.3        |
| google-cloud-storage      | 1.29.2       |
| emoji_regex               | 3.2.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.414.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.110.0      |
| aws-sdk-kms               | 1.40.0       |
| aws-sdk-s3                | 1.87.0       |
| uri                       | 0.10.0       |
| forwardable               | 1.3.1        |
| logger                    | 1.4.2        |
| cgi                       | 0.1.0        |
| date                      | 3.0.0        |
| timeout                   | 0.1.0        |
| stringio                  | 0.1.0        |
| zlib                      | 1.1.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.2.0        |
| strscan                   | 1.0.3        |
| delegate                  | 0.1.0        |
| fileutils                 | 1.4.1        |
| io-console                | 0.5.6        |
| singleton                 | 0.1.0        |
| rexml                     | 3.2.3        |
| open3                     | 0.1.0        |
| yaml                      | 0.1.0        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>


*generated on:* **2021-01-15**
</details>

**Comment by ccadieux** [comment]
Ran into something similar do this on CI. Adding unlock_keychain fixed this issue for us I believe.

```
    unlock_keychain
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight(skip_waiting_for_build_processing: true)
```

**Comment by Santiago0412** [comment]
I found fastlane give me this error when there are some issue on my project, which misleading me to check the certificate, but actually it's not because of the certificate issue
