### ISSUE TITLE
Frameit can not frame iPhone 8 Plus

### ISSUE THREAD

**Issue by yunhao** [fastlane/fastlane#17976]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Currently, App Store need at least two kind of screenshots: 5.5'' and 6.5''. Because fastlane doesn't support iPhone 7 Plus any more, I have to use iPhone 8 Plus to make my 5.5'' screenshots. 

```bash
// Make screenshot
fastlane snapshot
```

```ruby
// Snapfile
devices([
  "iPhone 11 Pro Max",
  "iPhone 8 Plus"
])
```

The snapshot process is fine, but there are some errors in Frameit.

```bash
fastlane frameit
```

```bash
[03:37:24]: Unsupported screen size [1242, 2208] for path './en-US/iPhone 8 Plus-XYZ_01.png'
[03:37:24]: Unsupported screen size [1242, 2208] for path './en-US/iPhone 8 Plus-XYZ_02.png'
```

```bash
file fastlane/screenshots/en-US/iPhone\ 8\ Plus-XYZ_01.png
// fastlane/screenshots/en-US/iPhone 8 Plus-XYZ_01.png: PNG image data, 1242 x 2208, 8-bit/color RGB, non-interlaced
```

The image file is generated by `fastlane snapshot`. However, it's resolution is 1242 x 2208. From https://support.apple.com/kb/SP768 , it seems the resolution should be 1080 x 1920.

I find this in the source code of Frameit:

https://github.com/fastlane/fastlane/blob/15093fc8213dcfe8982ab0e07dc8a59388c6ee92/frameit/lib/frameit/device_types.rb#L113

Is this right? The App Store really need a 1080 x 1920 image.
![image](https://user-images.githubusercontent.com/10205466/104774271-57df1e00-57b1-11eb-8dc5-17f8cfa3cdca.png)

Can anyone use the last version of fastlane to release a iOS app to App Store. I find it's imposible to meet the screenshots requirement on app store connectio website.

### Environment

<details>
  <pre> 
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.1                                        |
| Ruby                        | 2.7.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.rbenv/versions/2.7.2/bin/fastlane        |
| Host                        | macOS 11.1 (20C69)                          |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.2/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.3                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "MyApp.xcodeproj"
    )
    build_app(
      workspace: "MyApp.xcworkspace", 
      scheme: "MyApp",
      include_bitcode: true
    )
    upload_to_app_store
  end

  lane :beta do

    UI.message "Fetching the last build number from TestFlight..."

    last_build_number = latest_testflight_build_number
    target_build_number = last_build_number + 1

    increment_build_number(
      build_number: target_build_number,
      xcodeproj: "MyApp.xcodeproj"
    )

    # Build the app and then upload it to TestFlight.
    build_app(scheme: "MyApp")
    upload_to_testflight
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.171.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.4.0        |
| bundler                       | 2.2.3        |
| uri                           | 0.10.0       |
| rake                          | 13.0.3       |
| CFPropertyList                | 3.0.3        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| atomos                        | 0.1.3        |
| aws-eventstream               | 1.1.0        |
| aws-partitions                | 1.416.0      |
| aws-sigv4                     | 1.2.2        |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.111.0      |
| aws-sdk-kms                   | 1.41.0       |
| aws-sdk-s3                    | 1.87.0       |
| babosa                        | 1.0.4        |
| claide                        | 1.0.3        |
| colored                       | 1.2          |
| colored2                      | 3.1.2        |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| digest-crc                    | 0.6.3        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| dotenv                        | 2.7.6        |
| emoji_regex                   | 3.2.1        |
| excon                         | 0.78.1       |
| faraday-net_http              | 1.0.1        |
| multipart-post                | 2.0.0        |
| ruby2_keywords                | 0.0.2        |
| faraday                       | 1.3.0        |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.1        |
| gh_inspector                  | 1.1.3        |
| jwt                           | 2.2.2        |
| memoist                       | 0.16.2       |
| multi_json                    | 1.15.0       |
| os                            | 1.1.1        |
| signet                        | 0.14.0       |
| googleauth                    | 0.14.0       |
| httpclient                    | 2.8.3        |
| mini_mime                     | 1.0.2        |
| uber                          | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| google-api-client             | 0.38.0       |
| rexml                         | 3.2.4        |
| google-apis-core              | 0.2.0        |
| google-apis-iamcredentials_v1 | 0.1.0        |
| google-apis-storage_v1        | 0.1.0        |
| google-cloud-env              | 1.4.0        |
| google-cloud-errors           | 1.0.1        |
| google-cloud-core             | 1.5.0        |
| google-cloud-storage          | 1.30.0       |
| json                          | 2.5.1        |
| mini_magick                   | 4.11.0       |
| plist                         | 3.6.0        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| naturally                     | 2.2.0        |
| simctl                        | 1.6.8        |
| slack-notifier                | 2.3.2        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| word_wrap                     | 1.0.0        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| xcpretty-travis-formatter     | 1.0.1        |
</details>

*generated on:* **2021-01-16**
</details>
 </pre>
</details>

**Comment by ainame** [comment]
Your change LGTM to me as 1920x1080 is not the actual rendered pixel size.  

<img width="1135" alt="Screenshot 2021-01-18 at 11 37 07" src="https://user-images.githubusercontent.com/748949/104910695-99262800-5981-11eb-89e5-4abb52dc3cb2.png">

https://www.paintcodeapp.com/news/ultimate-guide-to-iphone-resolutions

I'm just wondering why other people didn't report this issue since it was introduced in March last year🤔 
https://github.com/fastlane/fastlane/pull/15087/files#diff-82d13aecb96d2d1a16137ec7f637a23aa32b7e335a344f544ff5af4d79b3e321R105

**Comment by ainame** [comment]
I tested this but what I found were that snapshot + frameit for iPhone 8 plus can complete without errors but there was a gotcha that frameit falls back to iPhone "7" Plus frame.

> [03:37:24]: Unsupported screen size [1242, 2208] for path './en-US/iPhone 8 Plus-XYZ_01.png'
> [03:37:24]: Unsupported screen size [1242, 2208] for path './en-US/-XYZ_02.png'

How did you actually get the error? How did you set up frameit and snapshot? As far as I read this method, it doesn't seem to be possible to get the error from the image file prefixed with "iPhone 8 Plus" and having "1242x2208" in its size...

https://github.com/fastlane/fastlane/blob/15093fc8213dcfe8982ab0e07dc8a59388c6ee92/frameit/lib/frameit/device.rb#L46-L72

**Comment by ainame** [comment]
@yunhao 

I tested this but what I found were that snapshot + frameit for iPhone 8 plus can complete without errors but there was a gotcha that frameit falls back to iPhone "7" Plus frame.

> [03:37:24]: Unsupported screen size [1242, 2208] for path './en-US/iPhone 8 Plus-XYZ_01.png'
> [03:37:24]: Unsupported screen size [1242, 2208] for path './en-US/-XYZ_02.png'

How did you actually get the error? How did you set up frameit and snapshot? As far as I read this method, it doesn't seem to be possible to get the error from the image file prefixed with "iPhone 8 Plus" and having "1242x2208" in its size...

https://github.com/fastlane/fastlane/blob/15093fc8213dcfe8982ab0e07dc8a59388c6ee92/frameit/lib/frameit/device.rb#L46-L72

**Comment by yunhao** [comment]
Sorry for the late reply. Yes, you are right. I'm also wondering why other people didn't report this issue. 😂

Perhaps my first post was a bit vague. Let me explain a little more clearly about the issue:
Frameit cannot frame screenshots with 1242 x 2208 resolutions (in pixel), which is generated by an iPhone 8 Plus. It says the screenshots have unsupported screen size.

We can comfirm that screenshots of iPhone 8 Plus and iPhone 7 Plus are both 1242 x 2208 pixel. From specifications: https://help.apple.com/app-store-connect/#/devd274dd925.

> | Device size or platform | Screenshot size |
> |-|-|
> | 5.5 inch (iPhone 8 Plus, iPhone 7 Plus, iPhone 6s Plus) | 1242 x 2208 pixels (portrait)<br>2208 x 1242 pixels (landscape) |

iPhone 8 Plus and iPhone 7 Plus are the same device, if we only look at their screen. Both are:
- 1080 x 1920 Physical Pixels
- 401 PPI
- 1242 x 2208 Rendered Pixels

And the screenshot of an iPhone is generated by rendered pixels. 

https://github.com/fastlane/fastlane/blob/15093fc8213dcfe8982ab0e07dc8a59388c6ee92/frameit/lib/frameit/device_types.rb#L110-L113

However, look at line 111 and line 113, there is a conflict. `IPHONE_7_PLUS` is [1242, 2208], while `IPHONE_8_PLUS` is [1080, 1920]. I think either line 11 is wrong or line 113 is wrong.

**Comment by yunhao** [comment]
I know what happened. 

The command `$ fastlane run frameit` works well. The trouble is caused by my custom action.

I call `frameit` through `Actions::FrameitAction`:

```ruby
class FrameMyScreenshotsAction < Action
  def self.run(params)
    # Not work.
    Actions::FrameitAction.run(
      path: './fastlane/screenshots'
    )
  end
  # ...
end
```

But when I change it to `other_action.frameit`, it works without any warning or errors:

```ruby
class FrameMyScreenshotsAction < Action
  def self.run(params)
    # Work.
    other_action.frameit(
      path: './fastlane/screenshots'
    )
  end
  # ...
end
```

I am very sorry for wasting your time. I'm new to Ruby and fastlane. The issue is caused by my code.

**Comment by yunhao** [comment]
But for my pull request  #17977, I still think it need to be merged if it's right. Because with it, `Actions::FrameitAction` can work.

For frameit, I still have some confusion. 
If i run `$ fastlane frameit` from the root directory of my project. It seems that frameit will search the whole project for screenshots, not only the `./fastlane/screenshot`. A explicit path does not work either: `$ fastlane frameit path:"./fastlane/*"`.

```bash
[20:06:29]: Unsupported screen size [40, 40] for path './MyProject/Assets.xcassets/AppIcon.appiconset/icon_20pt@2x-1.png'
[20:06:29]: Unsupported screen size [40, 40] for path './MyProject/Assets.xcassets/AppIcon.appiconset/icon_20pt@2x.png'
[20:06:29]: Unsupported screen size [120, 120] for path './MyProject/Assets.xcassets/AppIcon.appiconset/icon_40pt@3x.png'
...
```

In the mean time, `$ fastlane run frameit` is OK and it will only search `./fastlane/screenshots` for images.

Is this behavior intentional?

**Comment by ainame** [comment]
No worries at all ☺️   Thank you for your report. The PR got merged!

> If i run $ fastlane frameit from the root directory of my project. It seems that frameit will search the whole project for screenshots, not only the ./fastlane/screenshot. A explicit path does not work either: $ fastlane frameit path:"./fastlane/*".

Regarding this behaviour, from what I read on the document page, I think it's intended.  

> _Just navigate to your folder of screenshots_ and use the following command (iOS and Mac OS are default platforms for backward compatibility):

I assume it was the easiest way to list up images from the fastlane folder. Look at this line in `frameit`. It's done by 1 line while `deliver` has lots of logic just to load all the necessary image file paths. They are basically trying to do the same thing but it's not that easy when we need a very accurate result due to the fact fastlane's screenshot folders have complex rules. Forcing users to navigate to screenshots directory by themselves would make things much easier. But I understand this is not consistent experience though😄  

https://github.com/fastlane/fastlane/blob/0c53efb3e68cf4501264f76ee7f1f5f37261ad72/frameit/lib/frameit/runner.rb#L24

https://github.com/fastlane/fastlane/blob/0c53efb3e68cf4501264f76ee7f1f5f37261ad72/deliver/lib/deliver/loader.rb#L86-L117
