### ISSUE TITLE
set_info_plist_value change other values on info.plist file

### ISSUE THREAD

**Issue by yildirimatcioglu** [fastlane/fastlane#17973]
hello,
when we wet a value with set_info_plist_value other values which contains " ' " apostrophes changing to "&#39;"
my code for doing this:
`set_info_plist_value(path: "./xxx-company/Info.plist", key: "EnvironmentConfigUrl", value: environment)`

ex:
```
<key>NSLocationWhenInUseUsageDescription</key>
<string>AppStore bu uygulamanın sadece Türkiye'de kullanılmasına izin vermektedir. Lütfen konum talebini onaylayınız.</string>
```

it will change to this:
```
<key>NSLocationWhenInUseUsageDescription</key>
<string>AppStore bu uygulamanın sadece Türkiye&#39;de kullanılmasına izin vermektedir. Lütfen konum talebini onaylayınız.</string>```

**Comment by max-ott** [comment]
Sorry, I'm not seeing a difference. Might be an issue with the font / encoding here? Did you try to escape the character?

**Comment by rogerluan** [comment]
<img width="127" alt="image" src="https://user-images.githubusercontent.com/8419048/106983765-38e70280-6745-11eb-8960-fa90914b314d.png">

GitHub re-formats the apostrophe that was encoded differently. I added code markup to the issue description to visualize the difference.
