### ISSUE TITLE
 Google Api Error: forbidden: The caller does not have permission - The caller does not have permission ----- fastlane supply init --verbose

### ISSUE THREAD

**Issue by maelfosso** [fastlane/fastlane#17987]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Hello, 

I hope you are doing well.

I don't understand why `fastlane supply init` always return *Google Api Error: forbidden: The caller does not have permission - The caller does not have permission*
```
maelfosso@maelfosso:~/Documents/Projects/Guitou/mobile/android$ bundle exec fastlane supply init --verbose 
[✔] 🚀 
Successfully loaded Appfile at path '/home/maelfosso/Documents/Projects/Guitou/mobile/android/fastlane/Appfile'
- json_key_file: '/home/maelfosso/Documents/Projects/Guitou/pc-api-xxxxxxxxxxxxxxxx-yyy-zzzzzzzzzz.json'
- package_name: 'cm.guitou.android.xorms'
-------
INFO [2021-01-18 17:23:31.03]: 🕗  Downloading metadata, images, screenshots...
DEBUG [2021-01-18 17:23:31.05]: Fetching a new access token from Google...
bundler: failed to load command: fastlane (/home/maelfosso/.rvm/gems/ruby-2.6.5/bin/fastlane)
FastlaneCore::Interface::FastlaneError: [!] Google Api Error: forbidden: The caller does not have permission - The caller does not have permission
  /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'
  /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/fastlane-2.171.0/supply/lib/supply/client.rb:95:in `rescue in call_google_api'
  /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/fastlane-2.171.0/supply/lib/supply/client.rb:80:in `call_google_api'
  /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/fastlane-2.171.0/supply/lib/supply/client.rb:139:in `begin_edit'
  /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/fastlane-2.171.0/supply/lib/supply/setup.rb:11:in `perform_download'
  /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/fastlane-2.171.0/supply/lib/supply/commands_generator.rb:54:in `block (2 levels) in run'
  /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/fastlane-2.171.0/supply/lib/supply/commands_generator.rb:60:in `run'
  /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/fastlane-2.171.0/supply/lib/supply/commands_generator.rb:12:in `start'
  /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/fastlane-2.171.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
  /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/fastlane-2.171.0/bin/fastlane:23:in `<top (required)>'
  /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/fastlane:23:in `load'
  /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/fastlane:23:in `<top (required)>'


```

```
$ bundle exec fastlane --version
fastlane installation at path:
/home/maelfosso/.rvm/gems/ruby-2.6.5/gems/fastlane-2.171.0/bin/fastlane
-----------------------------
[✔] 🚀 
fastlane 2.171.0

```

I follow this [tutorial](https://flutter.dev/docs/deployment/cd) from flutter with takes me to [this Fastlane tutorial](https://docs.fastlane.tools/getting-started/android/setup/#setting-up-supply)

I followed the differents steps.
1- Created the service accounts
![service-accounts-created](https://user-images.githubusercontent.com/8848104/104859146-7c5b0780-5923-11eb-8d45-122cfda09adc.png)

2- Give them the *Owner* role
![service-account-role](https://user-images.githubusercontent.com/8848104/104859170-867d0600-5923-11eb-978f-11a32503b1d3.png)

3- Add the created service accounts in Google Play Console as indicated
![service-account-console](https://user-images.githubusercontent.com/8848104/104859177-9268c800-5923-11eb-8c3e-9df29e38e3ef.png)

4- Give them the required roles (full administration)
![users-and-permissions](https://user-images.githubusercontent.com/8848104/104859192-b926fe80-5923-11eb-9538-d56e3c12e941.png)

![users-permissions-roles-console](https://user-images.githubusercontent.com/8848104/104859208-c8a64780-5923-11eb-90e8-2386af51479b.png)

Seriously, I don't understand why I got this error.
I tried it twice and nothing.

Can you help me to understand what the problem is?

Thanks

##### Command executed

```
bundle exec fastlane supply init --verbose
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
$ bundle exec fastlane supply init --verbose 
[✔] 🚀 
Successfully loaded Appfile at path '/home/maelfosso/Documents/Projects/Guitou/mobile/android/fastlane/Appfile'
- json_key_file: '/home/maelfosso/Documents/Projects/Guitou/pc-api-xxxxxxxxxxxxxxxx-yyy-zzzzzzzzzz.json'
- package_name: 'cm.guitou.android.xorms'
-------
INFO [2021-01-18 17:23:31.03]: 🕗  Downloading metadata, images, screenshots...
DEBUG [2021-01-18 17:23:31.05]: Fetching a new access token from Google...
bundler: failed to load command: fastlane (/home/maelfosso/.rvm/gems/ruby-2.6.5/bin/fastlane)
FastlaneCore::Interface::FastlaneError: [!] Google Api Error: forbidden: The caller does not have permission - The caller does not have permission
  /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'
  /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/fastlane-2.171.0/supply/lib/supply/client.rb:95:in `rescue in call_google_api'
  /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/fastlane-2.171.0/supply/lib/supply/client.rb:80:in `call_google_api'
  /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/fastlane-2.171.0/supply/lib/supply/client.rb:139:in `begin_edit'
  /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/fastlane-2.171.0/supply/lib/supply/setup.rb:11:in `perform_download'
  /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/fastlane-2.171.0/supply/lib/supply/commands_generator.rb:54:in `block (2 levels) in run'
  /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/fastlane-2.171.0/supply/lib/supply/commands_generator.rb:60:in `run'
  /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/fastlane-2.171.0/supply/lib/supply/commands_generator.rb:12:in `start'
  /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/fastlane-2.171.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
  /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/fastlane-2.171.0/bin/fastlane:23:in `<top (required)>'
  /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/fastlane:23:in `load'
  /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/fastlane:23:in `<top (required)>'

</pre>
</details>

### Environment

<details>
  <pre> 
$ bundle exec fastlane env
[✔] 🚀 
[12:09:34]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | debian_based stretch/sid                                       |
| Ruby                        | 2.6.5                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.7.4                                              |
| Installation Source         | ~/.rvm/gems/ruby-2.6.5/bin/fastlane                            |
| Host                        | Ubuntu 16.04.3 LTS debian_based stretch/sid (4.4.0-87-generic) |
| Ruby Lib Dir                | /usr/share/rvm/rubies/ruby-2.6.5/lib                           |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                                     |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE | en_US       | 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("/home/maelfosso/Documents/Projects/Guitou/pc-api-xxxxxxxxxxx-yyyy-zzzzzzzzz.json") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("cm.guitou.android.xorms") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.171.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 2.1.4        |
| rake                      | 13.0.3       |
| CFPropertyList            | 3.0.3        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.414.0      |
| aws-sigv4                 | 1.2.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.110.0      |
| aws-sdk-kms               | 1.40.0       |
| aws-sdk-s3                | 1.87.0       |
| babosa                    | 1.0.4        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.3        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.2.1        |
| excon                     | 0.78.1       |
| faraday-net_http          | 1.0.0        |
| multipart-post            | 2.0.0        |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.3.0        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.1        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.2.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| signet                    | 0.14.0       |
| googleauth                | 0.14.0       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.4.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.2       |
| json                      | 2.5.1        |
| mini_magick               | 4.11.0       |
| plist                     | 3.6.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.1        |
</details>

*generated on:* **2021-01-18**
</details>
[12:09:38]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[12:09:38]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅

</pre>
</details>

**Comment by max-ott** [comment]
This message comes straight from the underlying Google Publishing API. It looks like the json key does not have the correct permissions. Are you sure you are using the right key?

**Comment by maelfosso** [comment]
@max-ott 

I can notice (from the screenshots above) that I created two JSON files and you also have the possibility (from the same screenshot) to see their permissions.

I tried both of them many times and I am still having the same result.
