### ISSUE TITLE
After updating to 2.171.0, error: Could not find digest-crc-0.6.3 in any of the sources

### ISSUE THREAD

**Issue by alakoring** [fastlane/fastlane#17980]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When I run fastlane (to archive and upload an iOS build), I get the error
Could not find digest-crc-0.6.3 in any of the sources

The archive has been built.

I have tried `bundle install` as recommended but it doesn’t make a difference.

I had been able to run the script a few days earlier, but had decided to update to the latest version of fastlane.

##### Command executed

bundle exec fastlane dark

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
+------------------------+--------------------------------------+
|                    Summary for gym 2.171.0                    |
+------------------------+--------------------------------------+
| workspace              | SixAges.xcworkspace                  |
| scheme                 | DarkAge                              |
| output_directory       | Builds                               |
| destination            | generic/platform=iOS                 |
| output_name            | Lights Going Out                     |
| build_path             | /Users/david/Library/Developer/Xcod  |
|                        | e/Archives/2021-01-15                |
| clean                  | false                                |
| silent                 | false                                |
| skip_package_ipa       | false                                |
| skip_package_pkg       | false                                |
| result_bundle          | false                                |
| buildlog_path          | ~/Library/Logs/gym                   |
| skip_profile_detection | false                                |
| use_system_scm         | false                                |
| xcode_path             | /Applications/Xcode.app              |
+------------------------+--------------------------------------+

[16:37:00]: $ set -o pipefail && xcodebuild -workspace SixAges.xcworkspace -scheme DarkAge -destination 'generic/platform=iOS' -archivePath /Users/david/Library/Developer/Xcode/Archives/2021-01-15/Lights\ Going\ Out\ 2021-01-15\ 16.37.00.xcarchive archive | tee /Users/david/Library/Logs/gym/Lights\ Going\ Out-DarkAge.log | xcpretty
[16:37:01]: ▸ objc[14144]: Class AMSupportURLConnectionDelegate is implemented in both ?? (0x1ed85b8f0) and ?? (0x1314d02b8). One of the two will be used. Which one is undefined.
[16:37:01]: ▸ objc[14144]: Class AMSupportURLSession is implemented in both ?? (0x1ed85b940) and ?? (0x1314d0308). One of the two will be used. Which one is undefined.
[16:37:01]: ▸ Could not find digest-crc-0.6.3 in any of the sources
[16:37:01]: ▸ Run `bundle install` to install missing gems.
objc[14144]: Class AMSupportURLConnectionDelegate is implemented in both ?? (0x1ed85b8f0) and ?? (0x1314d02b8). One of the two will be used. Which one is undefined.
objc[14144]: Class AMSupportURLSession is implemented in both ?? (0x1ed85b940) and ?? (0x1314d0308). One of the two will be used. Which one is undefined.
Could not find digest-crc-0.6.3 in any of the sources
Run `bundle install` to install missing gems.
[16:38:26]: Exit status: 7

+-------------+-------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.171.0                 |
| sdk         | iPhoneOS14.2.sdk        |
+-------------+-------------------------+

[16:38:26]: ▸ Command line invocation:
[16:38:26]: ▸     
[16:38:26]: 
[16:38:26]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[16:38:26]: 📋  For the complete and more detailed error log, check the full log at:
[16:38:26]: 📋  /Users/david/Library/Logs/gym/Lights Going Out-DarkAge.log
[16:38:26]: 
[16:38:26]: Looks like fastlane ran into a build/archive error with your project
[16:38:26]: It's hard to tell what's causing the error, so we wrote some guides on how
[16:38:26]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[16:38:26]: Before submitting an issue on GitHub, please follow the guide above and make
[16:38:26]: sure your project is set up correctly.
[16:38:26]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
[16:38:26]: the full commands printed out in yellow in the above log.
[16:38:26]: Make sure to inspect the output above, as usually you'll find more error information there
[16:38:26]: 
+------------------+----------+
|        Lane Context         |
+------------------+----------+
| DEFAULT_PLATFORM | ios      |
| PLATFORM_NAME    | ios      |
| LANE_NAME        | ios dark |
| BUILD_NUMBER     | 209      |
+------------------+----------+
[16:38:26]: Error building the application - see the log above

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | default_platform       | 0           |
| 2    | prompt                 | 60          |
| 3    | increment_build_numbe  | 1           |
|      | r                      |             |
| 💥   | build_app              | 90          |
+------+------------------------+-------------+

[16:38:26]: fastlane finished with errors

[!] Error building the application - see the log above

</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.1                                                           |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | ~/.gem/bin/fastlane                                            |
| Host                        | macOS 11.1 (20C69)                                             |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.2                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

# Assume Slack is configured by the SLACK_URL environment variable

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :storm do
	log = prompt(
		text: "Changelog: ",
		multi_line_end_keyword: "END"
	)
	bn = increment_build_number(xcodeproj: "SixAges.xcodeproj")
	build_app(
		workspace: "SixAges.xcworkspace",
		scheme: "StormAge",
		output_directory: "Builds"
	)
	upload_to_testflight(
		changelog: log,
		distribute_external: true,
		groups: ["Team"]
	)
	slack(
		message: "StormAge uploaded to TestFlight",
 		default_payloads: [],
 		payload: {
			"Build" => bn,
 			"Changes" => log
		}
	)
	sync
  end

  lane :dark do
	log = prompt(
		text: "Changelog: ",
		multi_line_end_keyword: "END"
	)
	bn = increment_build_number(
		build_number: "208",
		xcodeproj: "SixAges.xcodeproj")
	build_app(
		workspace: "SixAges.xcworkspace",
		scheme: "DarkAge",
		output_directory: "Builds"
	)
	upload_to_testflight(
		changelog: log,
		distribute_external: true,
		groups: ["QA"]
	)
	slack(
		message: "DarkAge uploaded to TestFlight",
 		default_payloads: [],
 		payload: {
			"Build" => bn,
 			"Changes" => log
		}
	)
	sync
  end


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.a-sharp.XXX" # The bundle identifier of your app
apple_id "XXXcom" # Your Apple email address

itc_team_id "XXX" # iTunes Connect Team ID
team_id "XXX" # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

for_lane :dark do
	app_identifier 'com.a-sharp.XXX'
end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.171.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.3.0        |
| bundler                       | 2.2.0        |
| rake                          | 13.0.3       |
| CFPropertyList                | 3.0.3        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| atomos                        | 0.1.3        |
| aws-eventstream               | 1.1.0        |
| aws-partitions                | 1.416.0      |
| aws-sigv4                     | 1.2.2        |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.111.1      |
| aws-sdk-kms                   | 1.41.0       |
| aws-sdk-s3                    | 1.87.0       |
| babosa                        | 1.0.4        |
| claide                        | 1.0.3        |
| colored                       | 1.2          |
| colored2                      | 3.1.2        |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| digest-crc                    | 0.6.3        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| dotenv                        | 2.7.6        |
| emoji_regex                   | 3.2.1        |
| excon                         | 0.78.1       |
| faraday-net_http              | 1.0.1        |
| multipart-post                | 2.0.0        |
| ruby2_keywords                | 0.0.2        |
| faraday                       | 1.3.0        |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.1        |
| gh_inspector                  | 1.1.3        |
| jwt                           | 2.2.2        |
| memoist                       | 0.16.2       |
| multi_json                    | 1.15.0       |
| os                            | 1.1.1        |
| signet                        | 0.14.0       |
| googleauth                    | 0.14.0       |
| httpclient                    | 2.8.3        |
| mini_mime                     | 1.0.2        |
| uber                          | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| google-api-client             | 0.38.0       |
| rexml                         | 3.2.4        |
| google-apis-core              | 0.2.0        |
| google-apis-iamcredentials_v1 | 0.1.0        |
| google-apis-storage_v1        | 0.1.0        |
| google-cloud-env              | 1.4.0        |
| google-cloud-errors           | 1.0.1        |
| google-cloud-core             | 1.5.0        |
| google-cloud-storage          | 1.30.0       |
| json                          | 2.5.1        |
| mini_magick                   | 4.11.0       |
| plist                         | 3.6.0        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| naturally                     | 2.2.0        |
| simctl                        | 1.6.8        |
| slack-notifier                | 2.3.2        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| word_wrap                     | 1.0.0        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| xcpretty-travis-formatter     | 1.0.1        |
</details>

*generated on:* **2021-01-15**
</details>
<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by max-ott** [comment]
Could you please try to uninstall `fastlane` and then install it again? Did you install it previously via `sudo` or similar?

**Comment by alakoring** [comment]
```
% gem uninstall fastlane
Successfully uninstalled fastlane-2.171.0
% gem install fastlane
Fetching artifactory-3.0.15.gem
Fetching fastlane-2.172.0.gem
Successfully installed artifactory-3.0.15
Successfully installed fastlane-2.172.0
Parsing documentation for artifactory-3.0.15
Installing ri documentation for artifactory-3.0.15
Parsing documentation for fastlane-2.172.0
Installing ri documentation for fastlane-2.172.0
Done installing documentation for artifactory, fastlane after 16 seconds
2 gems installed
% bundle exec fastlane dark
Could not find fastlane-2.171.0 in any of the sources
Run `bundle install` to install missing gems.
```

**Comment by alakoring** [comment]
But, `bundle install` did get me 2.171.0 and this time it didn’t give the digest-crc error, and my lane completed successfully. So technically my problem is solved but dependencies still seem like a problem.

(Sorry for the delay, I waited for the next build, since the archive is 800 MB.)
