### ISSUE TITLE
`ensure in take_off': uninitialized constant FastlaneCore::UpdateChecker (NameError) after updating to Fastlane 2.171.0

### ISSUE THREAD

**Issue by Tripwire999** [fastlane/fastlane#17998]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
After updating to Fastlane 2.171.0, Github Actions is reporting this error when running (worked fine on previous versions):
```
/home/runner/work/tessa-android/tessa-android/vendor/bundle/ruby/2.5.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `ensure in take_off': uninitialized constant FastlaneCore::UpdateChecker (NameError)
	from /home/runner/work/tessa-android/tessa-android/vendor/bundle/ruby/2.5.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /home/runner/work/tessa-android/tessa-android/vendor/bundle/ruby/2.5.0/gems/fastlane-2.171.0/bin/fastlane:23:in `<top (required)>'
	from /home/runner/work/tessa-android/tessa-android/vendor/bundle/ruby/2.5.0/bin/fastlane:23:in `load'
	from /home/runner/work/tessa-android/tessa-android/vendor/bundle/ruby/2.5.0/bin/fastlane:23:in `<main>'

```

##### Command executed
bundle exec fastlane deploy_integration

<details>
  Running Github Actions with Fastlane 2.171.0
</details>

**Comment by Kolvin** [comment]
+1

Our builds started failing this morning, been trying to find a solution for the past couple hours

**Comment by austin9350** [comment]
Ours were failing as well this morning, I suspect it was related to this outage. The incident was just marked as resolved and I re-ran our builds and they're running successfully now.

https://www.githubstatus.com/incidents/rk5rhrklkdk3

**Comment by Sebastian-Jedrocha** [comment]
+1

We are facing the same issue. Has anyone solved it?

**Comment by yendrek-rdvk** [comment]
+1 
Same here, we are unable to debug the issue 😕

**Comment by Kolvin** [comment]
My builds are running now - must of been related to the issue @austin9350 mentioned above

**Comment by Tripwire999** [comment]
Seems to be indeed related to Github having issues. Everything seems to work fine again :)
