### ISSUE TITLE
action `download_dsyms` not connect for api token

### ISSUE THREAD

**Issue by tastafur** [fastlane/fastlane#18000]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
the **download_dsyms** action does not work if we use **app_store_connect_api_key** to authorize ourselves

##### Command executed
`app_store_connect_api_key
download_dsyms
`

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.7                                     |
| Ruby                        | 2.7.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.rvm/gems/ruby-2.7.0/bin/fastlane         |
| Host                        | Mac OS X 10.15.7 (19H114)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.7.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.3                                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

def updateVersion()
  set_info_plist_value(
    key: 'CFBundleShortVersionString',
    value: ENV["VERSION"] + ENV["VERSION_CODE"],
    path: "./DoGood/Info.plist"
  )
  set_info_plist_value(
    key: 'CFBundleShortVersionString',
    value: ENV["VERSION"] + ENV["VERSION_CODE"],
    path: "./NotificationServiceExtension/Info.plist"
  )
  set_info_plist_value(
    key: 'CFBundleVersion',
    value: ENV["VERSION_CODE"],
    path: "./DoGood/Info.plist"
  )
  set_info_plist_value(
    key: 'CFBundleVersion',
    value: ENV["VERSION_CODE"],
    path: "./NotificationServiceExtension/Info.plist"
  )
end

def refreshDsyms()
  download_dsyms(version: ENV["VERSION"] + ENV["VERSION_CODE"], build_number: ENV["VERSION_CODE"], wait_for_dsym_processing: true)       # Download dSYM files from iTC
  upload_symbols_to_bugsnag
end

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Run build dev"
  lane :master do
    app_store_connect_api_key(
      key_id: "XXXX",
      issuer_id: "XXXX",
      key_filepath: "./AuthKey-ios.p8",
      duration: 3600, # optional
      in_house: false, # optional but may be required if using match/sigh
    )
    match(type: "appstore")
    build_app(
      workspace: "DoGood.xcworkspace",
      output_name: "dogood.ipa",
      scheme: "DoGood",
      export_options: {
          provisioningProfiles: {
            "com.dogoodpeople.app" => "match AppStore com.dogoodpeople.app",
            "com.dogoodpeople.app.NotificationServiceExtension" => "match AppStore com.dogoodpeople.app.NotificationServiceExtension"
          },
          "signingStyle": "manual"
      },
      xcargs: "DEVELOPMENT_TEAM='XXXX'"
    )
    copy_artifacts(
      target_path: "../output",
      artifacts: ["*.ipa", "*.dSYM.zip"]
    )
  end

  desc "Push a new Beta build to TestFlight"
  lane :beta do
    app_store_connect_api_key(
      key_id: "XXXX",
      issuer_id: "XXXX",
      key_filepath: "./AuthKey-ios.p8",
      duration: 3600, # optional
      in_house: false, # optional but may be required if using match/sigh
    )
    match(type: "appstore")
    updateVersion()
    build_app(
      workspace: "DoGood.xcworkspace",
      output_name: "dogood.ipa",
      scheme: "DoGood",
      export_options: {
          provisioningProfiles: {
            "com.dogoodpeople.app" => "match AppStore com.dogoodpeople.app",
            "com.dogoodpeople.app.NotificationServiceExtension" => "match AppStore com.dogoodpeople.app.NotificationServiceExtension"
          },
          "signingStyle": "manual"
      },
      xcargs: "DEVELOPMENT_TEAM='XXXX'"
    )
    changelog = read_changelog(
      changelog_path: '../CHANGELOG.md'
    )
    upload_to_testflight(
      changelog: changelog,
      distribute_external: false,
      demo_account_required: true,
      beta_app_review_info: {
        contact_email: ENV["IOS_BETA_EMAIL"],
        contact_first_name: ENV["IOS_BETA_FIRST_NAME"],
        contact_last_name: ENV["IOS_BETA_LAST_NAME"],
        contact_phone: ENV["IOS_BETA_PHONE"],
        demo_account_name: ENV["IOS_BETA_ACCOUNT_USERNAME"],
        demo_account_password: ENV["IOS_BETA_ACCOUNT_PASSWORD"]
      }
    )
    copy_artifacts(
      target_path: "../output",
      artifacts: ["*.ipa", "*.dSYM.zip"]
    )
    refreshDsyms()
  end

  desc "Push a new Beta build to TestFlight and group"
  lane :beta_url do
    app_store_connect_api_key(
      key_id: "XXXX",
      issuer_id: "XXXX",
      key_filepath: "./AuthKey-ios.p8",
      duration: 3600, # optional
      in_house: false, # optional but may be required if using match/sigh
    )
    match(type: "appstore")
    updateVersion()
    build_app(
      workspace: "DoGood.xcworkspace",
      output_name: "dogood.ipa",
      scheme: "DoGood",
      export_options: {
          provisioningProfiles: {
            "com.dogoodpeople.app" => "match AppStore com.dogoodpeople.app",
            "com.dogoodpeople.app.NotificationServiceExtension" => "match AppStore com.dogoodpeople.app.NotificationServiceExtension"
          },
          "signingStyle": "manual"
      },
      xcargs: "DEVELOPMENT_TEAM='XXXX'"
    )
    changelog = read_changelog(
      changelog_path: '../CHANGELOG.md'
    )
    upload_to_testflight(
      changelog: changelog,
      distribute_external: true,
      groups: ["Inversores"],
      demo_account_required: true,
      reject_build_waiting_for_review: true,
      beta_app_review_info: {
        contact_email: ENV["IOS_BETA_EMAIL"],
        contact_first_name: ENV["IOS_BETA_FIRST_NAME"],
        contact_last_name: ENV["IOS_BETA_LAST_NAME"],
        contact_phone: ENV["IOS_BETA_PHONE"],
        demo_account_name: ENV["IOS_BETA_ACCOUNT_USERNAME"],
        demo_account_password: ENV["IOS_BETA_ACCOUNT_PASSWORD"]
      }
    )
    copy_artifacts(
      target_path: "../output",
      artifacts: ["*.ipa", "*.dSYM.zip"]
    )
    refreshDsyms()
  end

  desc "Push a new production build to AppStore"
  lane :prod do
    app_store_connect_api_key(
      key_id: "XXXX",
      issuer_id: "XXXX",
      key_filepath: "./AuthKey-ios.p8",
      duration: 3600, # optional
      in_house: false, # optional but may be required if using match/sigh
    )
    match(type: "appstore")
    updateVersion()
    build_app(
      workspace: "DoGood.xcworkspace",
      output_name: "dogood.ipa",
      scheme: "DoGood",
      export_options: {
          provisioningProfiles: {
            "com.dogoodpeople.app" => "match AppStore com.dogoodpeople.app",
            "com.dogoodpeople.app.NotificationServiceExtension" => "match AppStore com.dogoodpeople.app.NotificationServiceExtension"
          },
          "signingStyle": "manual"
      },
      xcargs: "DEVELOPMENT_TEAM='XXXXXX'"
    )
    upload_to_app_store(
        submit_for_review: true,
        reject_if_possible: true,
        automatic_release: false,
        force: true, # Skip HTMl report verification
        submission_information: {
          export_compliance_uses_encryption: false,
          add_id_info_uses_idfa: false,
        }
    )
    copy_artifacts(
      target_path: "../output",
      artifacts: ["*.ipa", "*.dSYM.zip"]
    )
    refreshDsyms()
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.dogoodpeople.app") # The bundle identifier of your app

itc_team_id("121073827") # App Store Connect Team ID
team_id("LS46VK8YTB") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.171.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-changelog | 0.15.0  | ✅ Up-To-Date  |
| fastlane-plugin-bugsnag   | 2.0.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.4.0        |
| executable-hooks              | 1.6.0        |
| bundler-unload                | 1.0.2        |
| rubygems-bundler              | 1.4.5        |
| bundler                       | 2.1.2        |
| uri                           | 0.10.0       |
| rake                          | 13.0.3       |
| CFPropertyList                | 3.0.3        |
| concurrent-ruby               | 1.1.7        |
| i18n                          | 0.9.5        |
| minitest                      | 5.14.2       |
| thread_safe                   | 0.3.6        |
| tzinfo                        | 1.2.7        |
| activesupport                 | 5.2.4.4      |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| httpclient                    | 2.8.3        |
| json                          | 2.5.1        |
| algoliasearch                 | 1.27.4       |
| atomos                        | 0.1.3        |
| aws-eventstream               | 1.1.0        |
| aws-partitions                | 1.416.0      |
| aws-sigv4                     | 1.2.2        |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.111.1      |
| aws-sdk-kms                   | 1.41.0       |
| aws-sdk-s3                    | 1.87.0       |
| babosa                        | 1.0.4        |
| claide                        | 1.0.3        |
| fuzzy_match                   | 2.0.4        |
| nap                           | 1.1.0        |
| netrc                         | 0.11.0       |
| ffi                           | 1.13.1       |
| ethon                         | 0.12.0       |
| typhoeus                      | 1.4.0        |
| cocoapods-core                | 1.10.0       |
| cocoapods-deintegrate         | 1.0.4        |
| cocoapods-downloader          | 1.4.0        |
| cocoapods-plugins             | 1.0.0        |
| cocoapods-search              | 1.0.0        |
| cocoapods-trunk               | 1.5.0        |
| cocoapods-try                 | 1.2.0        |
| colored2                      | 3.1.2        |
| escape                        | 0.0.4        |
| fourflusher                   | 2.3.1        |
| gh_inspector                  | 1.1.3        |
| molinillo                     | 0.6.6        |
| ruby-macho                    | 1.4.0        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| cocoapods                     | 1.10.0       |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| digest-crc                    | 0.6.3        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| dotenv                        | 2.7.6        |
| emoji_regex                   | 3.2.1        |
| excon                         | 0.78.1       |
| faraday-net_http              | 1.0.1        |
| multipart-post                | 2.0.0        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.1        |
| jwt                           | 2.2.2        |
| memoist                       | 0.16.2       |
| multi_json                    | 1.15.0       |
| os                            | 1.1.1        |
| signet                        | 0.14.0       |
| googleauth                    | 0.14.0       |
| mini_mime                     | 1.0.2        |
| uber                          | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| google-api-client             | 0.38.0       |
| rexml                         | 3.2.4        |
| google-apis-core              | 0.2.0        |
| google-apis-iamcredentials_v1 | 0.1.0        |
| google-apis-storage_v1        | 0.1.0        |
| google-cloud-env              | 1.4.0        |
| google-cloud-errors           | 1.0.1        |
| google-cloud-core             | 1.5.0        |
| google-cloud-storage          | 1.30.0       |
| mini_magick                   | 4.11.0       |
| plist                         | 3.6.0        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| naturally                     | 2.2.1        |
| simctl                        | 1.6.8        |
| slack-notifier                | 2.3.2        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| word_wrap                     | 1.0.0        |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| xcpretty-travis-formatter     | 1.0.1        |
| rchardet                      | 1.8.0        |
| git                           | 1.7.0        |
| xml-simple                    | 1.1.5        |
| fastlane-plugin-bugsnag       | 2.0.0        |
| fastlane-plugin-changelog     | 0.15.0       |
</details>

*generated on:* **2021-01-19**
</details>

**Comment by tastafur** [comment]
I have created a PR to solve this #18001

**Comment by bes** [comment]
I just got bit by this as well. Please Apple open up that API :C
