### ISSUE TITLE
"Error loading plugin" message doesn't include backtrace even with --verbose or --troubleshoot

### ISSUE THREAD

**Issue by lilyball** [fastlane/fastlane#18026]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
If a plugin fails to load, fastlane will print an error like

```
Error loading plugin 'fastlane-plugin-foo': Some error message.
```

But it won't include any backtrace, which means I can't figure out the cause of the error. The error message is enough to identify the line of code throwing the error, but I can't determine why this code is being invoked during the plugin load.

Even adding `--verbose` or `--troubleshoot` does nothing. I would have expected one of those flags to include the backtrace of the load error.

### Captured Output

Command Used: `lanes --capture_output`
<details><summary>Output/Log</summary>

```

DEBUG [2021-01-21 16:28:43.12]: Checking if there are any plugins that should be loaded...
DEBUG [2021-01-21 16:28:43.12]: Loading 'fastlane-plugin-firebase_app_distribution' plugin
INFO [2021-01-21 16:28:43.12]: gem 'fastlane-plugin-firebase_app_distribution' is already installed
DEBUG [2021-01-21 16:28:43.16]: Loading 'fastlane-plugin-test_center' plugin
INFO [2021-01-21 16:28:43.16]: gem 'fastlane-plugin-test_center' is already installed
ERROR [2021-01-21 16:28:43.22]: Error loading plugin 'fastlane-plugin-test_center': Could not determine installed iOS SDK version. Try running the _xcodebuild_ command manually to ensure it works.
DEBUG [2021-01-21 16:28:43.22]: Loading 'fastlane-plugin-sentry' plugin
INFO [2021-01-21 16:28:43.22]: gem 'fastlane-plugin-sentry' is already installed


```

</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                                              |
| --------------------------- | ---------------------------------------------------------------------------------- |
| OS                          | 10.15.7                                                                            |
| Ruby                        | 2.6.6                                                                              |
| Bundler?                    | true                                                                               |
| Git                         |                                                                                    |
| Installation Source         | /nix/store/gar5pyjxnwa5z95zqywxxf0f65apjm6n-fastlane-2.161.0/bin/.fastlane-wrapped |
| Host                        | Mac OS X 10.15.7 (19H114)                                                          |
| Ruby Lib Dir                | /nix/store/sr4l5lknv8f35mxpj3sb7qkn57yc0w3s-ruby-2.6.6/lib                         |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                                                        |
| Is contained                | false                                                                              |
| Is homebrew                 | false                                                                              |
| Is installed via Fabric.app | false                                                                              |
| Xcode Path                  | /Library/Developer/CommandLineTools/                                               |
| Xcode Version               |                                                                                    |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.161.0 | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status      |
| ----------------------------------------- | ------- | ------------------ |
| fastlane-plugin-firebase_app_distribution | 0.2.5   | ✅ Up-To-Date       |
| fastlane-plugin-test_center               | 3.15.1  | 🚫 Update available |
| fastlane-plugin-sentry                    | 1.8.0   | ✅ Up-To-Date       |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| rake                                      | 13.0.3       |
| CFPropertyList                            | 3.0.3        |
| concurrent-ruby                           | 1.1.7        |
| i18n                                      | 1.8.7        |
| minitest                                  | 5.14.3       |
| tzinfo                                    | 2.0.4        |
| zeitwerk                                  | 2.4.2        |
| activesupport                             | 6.1.1        |
| public_suffix                             | 4.0.6        |
| addressable                               | 2.7.0        |
| artifactory                               | 3.0.15       |
| jwt                                       | 2.1.0        |
| atlassian-jwt                             | 0.2.0        |
| atomos                                    | 0.1.3        |
| aws-eventstream                           | 1.1.0        |
| aws-partitions                            | 1.416.0      |
| aws-sigv4                                 | 1.2.2        |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.111.0      |
| aws-sdk-kms                               | 1.41.0       |
| aws-sdk-s3                                | 1.87.0       |
| babosa                                    | 1.0.4        |
| bundler                                   | 2.1.4        |
| claide                                    | 1.0.3        |
| colored                                   | 1.2          |
| colored2                                  | 3.1.2        |
| colorize                                  | 0.8.1        |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| declarative                               | 0.0.20       |
| declarative-option                        | 0.1.0        |
| digest-crc                                | 0.6.3        |
| unf_ext                                   | 0.0.7.7      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| dotenv                                    | 2.7.6        |
| emoji_regex                               | 3.2.1        |
| excon                                     | 0.78.1       |
| faraday-net_http                          | 1.0.1        |
| multipart-post                            | 2.0.0        |
| ruby2_keywords                            | 0.0.2        |
| faraday                                   | 1.3.0        |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.0.0        |
| fastimage                                 | 2.2.1        |
| gh_inspector                              | 1.1.3        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.1        |
| signet                                    | 0.14.0       |
| googleauth                                | 0.14.0       |
| httpclient                                | 2.8.3        |
| mini_mime                                 | 1.0.2        |
| uber                                      | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| google-api-client                         | 0.38.0       |
| rexml                                     | 3.2.4        |
| google-apis-core                          | 0.2.0        |
| google-apis-iamcredentials_v1             | 0.1.0        |
| google-apis-storage_v1                    | 0.1.0        |
| google-cloud-env                          | 1.4.0        |
| google-cloud-errors                       | 1.0.1        |
| google-cloud-core                         | 1.5.0        |
| google-cloud-storage                      | 1.30.0       |
| json                                      | 2.5.1        |
| mini_magick                               | 4.11.0       |
| plist                                     | 3.6.0        |
| rubyzip                                   | 2.3.0        |
| security                                  | 0.1.3        |
| naturally                                 | 2.2.0        |
| simctl                                    | 1.6.8        |
| slack-notifier                            | 2.3.2        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.7.0        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| word_wrap                                 | 1.0.0        |
| nanaimo                                   | 0.3.0        |
| xcodeproj                                 | 1.19.0       |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.1        |
| fastlane-plugin-firebase_app_distribution | 0.2.5        |
| fastlane-plugin-sentry                    | 1.8.0        |
| trainer                                   | 0.9.1        |
| xctest_list                               | 1.2.1        |
| fastlane-plugin-test_center               | 3.15.1       |
| oauth                                     | 0.5.4        |
| jira-ruby                                 | 2.1.4        |
| xcode-install                             | 2.6.8        |
</details>

*generated on:* **2021-01-21**
</details>

#### Notes

For this particular error I can file an upstream issue with the plugin author, but without knowing the cause I can't seek any local workarounds.

Also I checked the fastlane code that loads plugins and it hasn't changed in at least 4 years, so I'm pretty sure updating fastlane won't change anything.

**Comment by lilyball** [comment]
This issue is literally only a month old. What the hell.

**Comment by rogerluan** [comment]
@lilyball the "Some error message" part is the exception itself:

https://github.com/fastlane/fastlane/blob/afd4540ea9fdbff20813fc32acd60d6e7febf7bd/fastlane/lib/fastlane/plugins/plugin_manager.rb#L298

I suppose we could also print the stacktrace from that exception (`ex.stacktrace` in this case), not a big deal. Would you like to open a PR with this tiny change? Or, could you provide steps to reproduce this issue so I can test it myself and open the PR? 🙏

**Comment by lilyball** [comment]
@rogerluan I no longer work at the company that had this problem, so I don't have precise reproduction steps, but my recollection is it involved loading `fastlane-plugin-test_center` when there was some issue with the currently-selected default Xcode. The plugin was for some reason trying to fetch information from Xcode at load time, instead of when the plugin was later used. The `Fastfile` specified a working version of Xcode, so everything would have worked just fine if it simply deferred whatever loading it was doing until later.

I located the code that produced the error message by searching for the message itself, that particular error was thrown from the Fastlane core, but I could not for the life of me figure out how `fastlane-plugin-test_center` was getting to that method while loading. This is why I wanted the stack trace, so I could figure out what was actually going wrong.
