### ISSUE TITLE
Fastlane unable to download provisioning profile based on TEAM ID ( enterprise)

### ISSUE THREAD

**Issue by nawaahme** [fastlane/fastlane#18033]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Command executed
fastlane sigh download_all --api_key_path "AppleConnectAPI/XYZ_InHouse.json" --team_id ********--skip_install --skip_certificate_verification --output_path update

##### Complete output when running fastlane, including the stack trace and command used
Just downloads provisioning profile from default apple developer program rather than downloading from Enterprise Apple Developer program
<details>
  <pre> Fastlane unable to download provisioning profile based on TEAM ID ( enterprise) even though i'm using API Keys contains in_house key : "true" </pre>
</details>

### Environment

[06:30:17]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[06:30:19]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.5                                     |
| Ruby                        | 2.6.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0                          |
| Installation Source         | ~/.rvm/gems/ruby-2.6.0/bin/fastlane         |
| Host                        | Mac OS X 10.15.5 (19F101)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.1b  26 Feb 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.4                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     |             |   |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.172.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| artifactory               | 3.0.15       |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday-net_http          | 1.0.1        |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.3.0        |
| faraday_middleware        | 1.0.0        |
| gh_inspector              | 1.1.3        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| uber                      | 0.1.0        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| nanaimo                   | 0.3.0        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.3        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.19.0       |
| unicode-display_width     | 1.7.0        |
| plist                     | 3.6.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.4        |
| excon                     | 0.78.1       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| fastimage                 | 2.2.1        |
| json                      | 2.2.0        |
| mini_magick               | 4.11.0       |
| xcpretty-travis-formatter | 1.0.1        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.0.1        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| declarative               | 0.0.20       |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| os                        | 1.1.1        |
| memoist                   | 0.16.2       |
| googleauth                | 0.14.0       |
| rake                      | 12.3.2       |
| digest-crc                | 0.6.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-env          | 1.4.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.2       |
| emoji_regex               | 3.2.1        |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-partitions            | 1.416.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.111.0      |
| aws-sdk-kms               | 1.41.0       |
| aws-sdk-s3                | 1.87.0       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| date                      | 2.0.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| fileutils                 | 1.2.0        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.2       |
| rexml                     | 3.2.0        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>

*generated on:* **2021-01-22**

<details>
  <pre>   </pre>
</details>

**Comment by krish722** [comment]
The API key or JSON is account specific.  As we know enterprise account it has a different key and appstore account has a different key.  Can you clear the $HOME/.fastlane folder and try it out to find out the old credentials causing the issue?

**Comment by nawaahme** [comment]
Our account is a part of both enterprise and appstore and we have same API key.
I tried clearing $HOME/.fastlane directory and executed command but facing same issue.

**Comment by tmxkevingriesbach** [comment]
> and we have same API key.

That can not be the case. Enterprise and AppStore should be two different enrollments/teams, which results in the need for a different key for each.

**Comment by coltspackers** [comment]
tmx, are you seeing the "API Keys" tab in "Users and Access" in App Store Connect? It is simply not showing up for me in the Enterprise team (it's there in our Store team and we are using it somewhat successfully).

From what I've read online...this may actually be intentional by Apple (not allowing API Keys for Enterprise teams). If so...then I guess we are just stuck, and some of our stuff will break when Apple flips their 2FA switch in Feb...

**Comment by dk9x17** [comment]
Hey I am having the same problem. Called Apple and they said there isn't any API Key for Enterprise program. They also suggest to use auto provisioning profile instead, which doesn't work for me.

**Comment by michaelst7** [comment]
+1 Also having same issue.

**Comment by Vyazovoy** [comment]
I have the same issue with API Key + Enterprise account. It works for AppStore one tho. What confuses me most is that there is `IOS_APP_INHOUSE` filter type in official Apple [docs](https://developer.apple.com/documentation/appstoreconnectapi/list_and_download_profiles), that would implicitly mean that it should support it.
