### ISSUE TITLE
Gem xcode-install fails through Jenkins job

### ISSUE THREAD

**Issue by menvol3** [fastlane/fastlane#18032]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Hi, I’m trying to automate installation of Xcode with Jenkins

I’m using xcode-install with fastlane

When I’m running it locally, it works fine, but with jenkins job i receive a strange error

`/usr/local/Cellar/fastlane/2.171.0/libexec/gems/xcode-install-2.6.8/lib/xcode/install.rb:229:in pwd': No such file or directory - getcwd (Errno::ENOENT)
`
.xip file downloads to the directory `/Users/username/Library/Caches/XcodeInstall/`

Then according to the install.rb it searching Xcode.app file in current directory, in my case it is a directory where job running, and then it fails, but Xcode.app already there, even after error.

Error reproduce on Mac OS Big Sur, Catalina
##### Command executed
`fastlane run xcode_install version:12.2 username:****`

##### Complete output when running fastlane, including the stack trace and command used

<details>
[16:00:19]: [33mError accessing file, this might be due to fastlane's directory handling[0m
[16:00:19]: [33mCheck out https://docs.fastlane.tools/advanced/#directory-behavior for more details[0m]

`
/usr/local/Cellar/fastlane/2.172.0/libexec/gems/xcode-install-2.6.8/lib/xcode/install.rb:229:in  pwd  : No such file or directory - getcwd (Errno::ENOENT)
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/xcode-install-2.6.8/lib/xcode/install.rb:229:in  install_dmg  
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/xcode-install-2.6.8/lib/xcode/install.rb:291:in  install_version  
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/actions/xcode_install.rb:20:in  run  
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/runner.rb:263:in  block (2 levels) in execute_action  
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in execute_action  
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/runner.rb:255:in  block in execute_action  
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/runner.rb:229:in  chdir  
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/runner.rb:229:in  execute_action  
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/one_off.rb:42:in  run  
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/one_off.rb:22:in  execute  
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/commands_generator.rb:224:in  block (2 levels) in run  
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in  call  
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in  run  
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in  run_active_command  
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in  run!  
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in  run!  
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/commands_generator.rb:352:in  run  
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/commands_generator.rb:41:in  start  
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in  take_off  
	from /usr/local/Cellar/fastlane/2.172.0/libexec/gems/fastlane-2.172.0/bin/fastlane:23:in  <top (required)>  
	from /usr/local/Cellar/fastlane/2.172.0/libexec/bin/fastlane:23:in  load  
	from /usr/local/Cellar/fastlane/2.172.0/libexec/bin/fastlane:23:in  <main>  
`
</details>

### Environment

<details>
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 11.1                                                    |
| Ruby                        | 2.7.2                                                   |
| Bundler?                    | false                                                   |
| Git                         |                                                         |
| Installation Source         | /usr/local/Cellar/fastlane/2.172.0/libexec/bin/fastlane |
| Host                        | macOS 11.1 (20C69)                                      |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.7/2.7.2/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                              |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode-12.2.app/Contents/Developer/        |
| Xcode Version               |                                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.172.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.4.0        |
| slack-notifier                | 2.3.2        |
| atomos                        | 0.1.3        |
| CFPropertyList                | 3.0.3        |
| claide                        | 1.0.3        |
| colored2                      | 3.1.2        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| plist                         | 3.6.0        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| multipart-post                | 2.0.0        |
| word_wrap                     | 1.0.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| artifactory                   | 3.0.15       |
| babosa                        | 1.0.4        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| excon                         | 0.78.1       |
| faraday-net_http              | 1.0.1        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.1        |
| gh_inspector                  | 1.1.3        |
| json                          | 2.3.0        |
| mini_magick                   | 4.11.0       |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| xcpretty-travis-formatter     | 1.0.1        |
| dotenv                        | 2.7.6        |
| bundler                       | 2.1.4        |
| naturally                     | 2.2.1        |
| simctl                        | 1.6.8        |
| jwt                           | 2.2.2        |
| uber                          | 0.1.0        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| mini_mime                     | 1.0.2        |
| multi_json                    | 1.15.0       |
| signet                        | 0.14.0       |
| memoist                       | 0.16.2       |
| os                            | 1.1.1        |
| googleauth                    | 0.14.0       |
| httpclient                    | 2.8.3        |
| google-api-client             | 0.38.0       |
| google-cloud-env              | 1.4.0        |
| google-cloud-errors           | 1.0.1        |
| google-cloud-core             | 1.5.0        |
| rexml                         | 3.2.3        |
| google-apis-core              | 0.2.0        |
| google-apis-iamcredentials_v1 | 0.1.0        |
| google-apis-storage_v1        | 0.1.0        |
| rake                          | 13.0.3       |
| digest-crc                    | 0.6.3        |
| google-cloud-storage          | 1.30.0       |
| emoji_regex                   | 3.2.1        |
| jmespath                      | 1.4.0        |
| aws-partitions                | 1.417.0      |
| aws-eventstream               | 1.1.0        |
| aws-sigv4                     | 1.2.2        |
| aws-sdk-core                  | 3.111.2      |
| aws-sdk-kms                   | 1.41.0       |
| aws-sdk-s3                    | 1.87.0       |
| uri                           | 0.10.0       |
| forwardable                   | 1.3.1        |
| logger                        | 1.4.2        |
| cgi                           | 0.1.0        |
| date                          | 3.0.0        |
| timeout                       | 0.1.0        |
| stringio                      | 0.1.0        |
| zlib                          | 1.1.0        |
| ipaddr                        | 1.2.2        |
| openssl                       | 2.1.2        |
| ostruct                       | 0.2.0        |
| strscan                       | 1.0.3        |
| delegate                      | 0.1.0        |
| fileutils                     | 1.4.1        |
| io-console                    | 0.5.6        |
| open3                         | 0.1.0        |
| singleton                     | 0.1.0        |
| yaml                          | 0.1.0        |
| psych                         | 3.1.0        |
| mutex_m                       | 0.1.0        |
</details>

*generated on:* **2021-01-22**
</details>
</details>

**Comment by krish722** [comment]
It looks like Dir.pwd failed. It pretty simple command fails for few reasons only. 
1. the shell in such a directory which was deleted.
2. the current user does not have access to it.

Please check which folder you are in while calling this function and also check the access for the user

**Comment by menvol3** [comment]
Thank you for the reply

I checked it. Added to file install.rb before line where it fails command `puts Dir.pwd`, it printed directory where job was running, also in this folder file Xcode.app appears after error. So in my opinion directory exists.
Also i tried to run it from sudo user, which has full rights. The same thing reproduced.

Maybe there are some others ways to debug it ?

**Comment by krish722** [comment]
user --verbose option on fastlane and can you get the output?
