### ISSUE TITLE
Could not find rake-13.0.3 in any of the sources

### ISSUE THREAD

**Issue by long1eu** [fastlane/fastlane#18064]
When I run the gym command I get this weird error.

```
[16:20:23]: ▸ Could not find rake-13.0.3 in any of the sources
[16:20:23]: ▸ Run `bundle install` to install missing gems.
```

Here is the full log:
```
[16:20:09]: Setting Provisioning Profile type to 'ad-hoc'
[16:20:09]: -----------------
[16:20:09]: --- Step: gym ---
[16:20:09]: -----------------
[16:20:10]: Resolving Swift Package Manager dependencies...
[16:20:10]: $ xcodebuild -resolvePackageDependencies -workspace Runner.xcworkspace -scheme prod
[16:20:11]: ▸ Command line invocation:
[16:20:11]: ▸     /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -workspace Runner.xcworkspace -scheme prod
[16:20:14]: ▸ resolved source packages:
[16:20:14]: $ xcodebuild -showBuildSettings -workspace Runner.xcworkspace -scheme prod
[16:20:17]: Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...
[16:20:22]: Detected provisioning profile mapping: {:"com.example.app"=>"match AdHoc com.example.app", :"com.example.app.dev"=>"match AdHoc com.example.app.dev", :"com.example.app.red"=>"match AdHoc com.example.app.red"}

+-----------------------------------------------------------------+------------------------------------------------------------+
|                                                   Summary for gym 2.172.0                                                    |
+-----------------------------------------------------------------+------------------------------------------------------------+
| workspace                                                       | Runner.xcworkspace                                         |
| scheme                                                          | prod                                                       |
| output_directory                                                | ../build/ios/iphoneos                                      |
| output_name                                                     | Runner_adhoc_prod                                          |
| export_method                                                   | ad-hoc                                                     |
| export_options.provisioningProfiles.com.example.app             | match AdHoc com.example.app                                |
| export_options.provisioningProfiles.com.example.app.dev         | match AdHoc com.example.app.dev                            |
| export_options.provisioningProfiles.com.example.app.red         | match AdHoc com.example.app.red                            |
| destination                                                     | generic/platform=iOS                                       |
| build_path                                                      | /Users/long1eu/Library/Developer/Xcode/Archives/2021-01-28 |
| clean                                                           | false                                                      |
| silent                                                          | false                                                      |
| skip_package_ipa                                                | false                                                      |
| skip_package_pkg                                                | false                                                      |
| result_bundle                                                   | false                                                      |
| buildlog_path                                                   | ~/Library/Logs/gym                                         |
| skip_profile_detection                                          | false                                                      |
| skip_package_dependencies_resolution                            | false                                                      |
| disable_package_automatic_updates                               | false                                                      |
| use_system_scm                                                  | false                                                      |
| xcode_path                                                      | /Applications/Xcode.app                                    |
+-----------------------------------------------------------------+------------------------------------------------------------+

[16:20:22]: $ set -o pipefail && xcodebuild -workspace Runner.xcworkspace -scheme prod -destination 'generic/platform=iOS' -archivePath /Users/long1eu/Library/Developer/Xcode/Archives/2021-01-28/Runner_adhoc_prod\ 2021-01-28\ 16.20.22.xcarchive archive | tee /Users/long1eu/Library/Logs/gym/Runner_prod-prod.log | xcpretty
[16:20:23]: ▸ Could not find rake-13.0.3 in any of the sources
[16:20:23]: ▸ Run `bundle install` to install missing gems.
[16:38:06]: Exit status: 7

+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.172.0                 |
| export_method | ad-hoc                  |
| sdk           | iPhoneOS14.4.sdk        |
+---------------+-------------------------+

[16:38:06]: ▸ Command line invocation:
[16:38:06]: ▸     
[16:38:06]: 
[16:38:06]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[16:38:06]: 📋  For the complete and more detailed error log, check the full log at:
[16:38:06]: 📋  /Users/long1eu/Library/Logs/gym/Runner_prod-prod.log
[16:38:06]: 
[16:38:06]: Looks like fastlane ran into a build/archive error with your project
[16:38:06]: It's hard to tell what's causing the error, so we wrote some guides on how
[16:38:06]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[16:38:06]: Before submitting an issue on GitHub, please follow the guide above and make
[16:38:06]: sure your project is set up correctly.
[16:38:06]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
[16:38:06]: the full commands printed out in yellow in the above log.
[16:38:06]: Make sure to inspect the output above, as usually you'll find more error information there
```

fastlane env

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.6                                     |
| Ruby                        | 2.7.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.gem/ruby/2.7.0/bin/fastlane              |
| Host                        | Mac OS X 10.15.6 (19G2005)                  |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.7/2.7.2/lib        |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.4                                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# frozen_string_literal: true

update_fastlane
default_platform(:ios)

BUILD_OUTPUT_ = '../build/ios/iphoneos'
APPSTORE_CONNECT_API_KEY_PATH_ = '../private/key.json'

def setup_ci(type, env)
  keychain_name = 'CI'
  keychain_password = ENV['MATCH_PASSWORD']

  create_keychain(
      name: keychain_name,
      password: keychain_password,
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
  )
  match(
      type: type,
      force_for_new_devices: true,
      keychain_name: keychain_name,
      keychain_password: keychain_password,
      api_key_path: APPSTORE_CONNECT_API_KEY_PATH_
  )
  sh('security list-keychains -d user')
  sh('security default-keychain -d user')
  sh("security find-identity -v -p codesigning #{keychain_name}")

  app_identifier = "com.example.app#{env == "prod" ? "" : ".#{env}"}"

  team_id = ENV["sigh_#{app_identifier}_#{type}_team-id"]
  identity = "Apple Distribution: ORG (#{team_id})"
  profile = ENV["sigh_#{app_identifier}_#{type}"]
  profile_name = ENV["sigh_#{app_identifier}_#{type}_profile-name"]

  update_code_signing_settings(
      use_automatic_signing: false,
      path: 'Runner.xcodeproj',
      team_id: team_id,
      profile_uuid: profile,
      profile_name: profile_name,
      code_sign_identity: identity
  )
end

def build(type, export_method, env)
  cocoapods
  if is_ci
    setup_ci(type, env)
  else
    match(type: type, force_for_new_devices: true, api_key_path: APPSTORE_CONNECT_API_KEY_PATH_)
  end

  gym(
      workspace: 'Runner.xcworkspace',
      scheme: env,
      output_directory: BUILD_OUTPUT_,
      output_name: "Runner_#{type}_#{env}.ipa",
      export_method: export_method
  )
end

platform :ios do
  desc 'Build ipa for Firebase App Distribution'
  lane :build_firebase do |values|
    build('adhoc', 'ad-hoc', values[:env])
  end

  desc 'Build ipa for App Store and upload'
  lane :build_appstore do |values|
    build('appstore', 'app-store', values[:env])
    upload_to_app_store(
      run_precheck_before_submit: false,
      api_key_path: APPSTORE_CONNECT_API_KEY_PATH_
    )
  end

  desc 'Add new device'
  lane :register do |values|
    register_devices(
      devices: {
        values[:name] => values[:udid],
      },
      api_key_path: APPSTORE_CONNECT_API_KEY_PATH_
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id("username@gmail.com")
team_id("TEAM_ID")
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.172.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.4.0        |
| bundler                       | 2.2.7        |
| uri                           | 0.10.0       |
| rake                          | 13.0.3       |
| CFPropertyList                | 3.0.3        |
| concurrent-ruby               | 1.1.8        |
| i18n                          | 1.8.7        |
| minitest                      | 5.14.3       |
| thread_safe                   | 0.3.6        |
| tzinfo                        | 1.2.9        |
| activesupport                 | 5.2.4.4      |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| httpclient                    | 2.8.3        |
| json                          | 2.5.1        |
| algoliasearch                 | 1.27.5       |
| artifactory                   | 3.0.15       |
| atomos                        | 0.1.3        |
| aws-eventstream               | 1.1.0        |
| aws-partitions                | 1.420.0      |
| aws-sigv4                     | 1.2.2        |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.111.2      |
| aws-sdk-kms                   | 1.41.0       |
| aws-sdk-s3                    | 1.87.0       |
| babosa                        | 1.0.4        |
| claide                        | 1.0.3        |
| fuzzy_match                   | 2.0.4        |
| nap                           | 1.1.0        |
| netrc                         | 0.11.0       |
| ffi                           | 1.14.2       |
| ethon                         | 0.12.0       |
| typhoeus                      | 1.4.0        |
| cocoapods-core                | 1.10.0.rc.1  |
| cocoapods-deintegrate         | 1.0.4        |
| cocoapods-downloader          | 1.4.0        |
| cocoapods-plugins             | 1.0.0        |
| cocoapods-search              | 1.0.0        |
| cocoapods-trunk               | 1.5.0        |
| cocoapods-try                 | 1.2.0        |
| colored2                      | 3.1.2        |
| escape                        | 0.0.4        |
| fourflusher                   | 2.3.1        |
| gh_inspector                  | 1.1.3        |
| molinillo                     | 0.6.6        |
| ruby-macho                    | 1.4.0        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| cocoapods                     | 1.10.0.rc.1  |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| digest-crc                    | 0.6.3        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| dotenv                        | 2.7.6        |
| emoji_regex                   | 3.2.1        |
| excon                         | 0.78.1       |
| faraday-net_http              | 1.0.1        |
| multipart-post                | 2.0.0        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.1        |
| jwt                           | 2.2.2        |
| memoist                       | 0.16.2       |
| multi_json                    | 1.15.0       |
| os                            | 1.1.1        |
| signet                        | 0.14.1       |
| googleauth                    | 0.15.0       |
| mini_mime                     | 1.0.2        |
| uber                          | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| google-api-client             | 0.38.0       |
| rexml                         | 3.2.4        |
| webrick                       | 1.7.0        |
| google-apis-core              | 0.2.1        |
| google-apis-iamcredentials_v1 | 0.1.0        |
| google-apis-storage_v1        | 0.1.0        |
| google-cloud-env              | 1.4.0        |
| google-cloud-errors           | 1.0.1        |
| google-cloud-core             | 1.5.0        |
| google-cloud-storage          | 1.30.0       |
| mini_magick                   | 4.11.0       |
| plist                         | 3.6.0        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| naturally                     | 2.2.1        |
| simctl                        | 1.6.8        |
| slack-notifier                | 2.3.2        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| word_wrap                     | 1.0.0        |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| xcpretty-travis-formatter     | 1.0.1        |
</details>

*generated on:* **2021-01-28**
</details>

**Comment by max-ott** [comment]
Please uninstall fastlane and reinstall it with bundle. Make sure not to use sudo or similar. If you did so previously make sure to uninstall it with sudo.

**Comment by long1eu** [comment]
This solved the issue.
