### ISSUE TITLE
Publish to Test Flight Error

### ISSUE THREAD

**Issue by SudhersonV** [fastlane/fastlane#18062]
I'm using the Azure CI along with self hosted mac agent. I got rid of the 2FA problem by using the userId and password in the authentication method. Earlier I used fastlane token and app specific password, logging into Test Flight was resolved. Still the below error is haunting me. I even updated my self hosted mac agent.

Starting: Publish to the App Store TestFlight track
==============================================================================
Task         : Apple App Store Release
Description  : Release an app to TestFlight or the Apple App Store
Version      : 1.178.4
Author       : Microsoft Corporation
Help         : [More Information](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.app-store)
==============================================================================
/usr/local/bin/fastlane pilot upload -u *** -i /Users/sudhersonv/macagent/_work/1/s/src/ExchangeBooks.iOS/bin/iPhone/Release/ExchangeBooks.iOS.ipa -a com.sudhersonv.exchangebooksapp
[20:01:32]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[20:01:33]: Login to App Store Connect (***)
[20:01:34]: Login successful
[20:01:37]: Ready to upload new build to TestFlight (App: 1546492052)...

Looking for related GitHub issues on fastlane/fastlane...

➡️  Pilot - undefined method `strip' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/15204 [closed] 12 💬
    26 Nov 2019

➡️  some wrong happen when I use fastlane to upload an ipa file
    https://github.com/fastlane/fastlane/issues/14272 [closed] 6 💬
    11 Jun 2019

➡️  Pilot fails to upload ipa: itunes_transporter can't initialise
    https://github.com/fastlane/fastlane/issues/11605 [closed] 5 💬
    22 Mar 2018

and 1 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60start_with%3F%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.172.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:419:in `initialize': [!] undefined method `start_with?' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.172.0/pilot/lib/pilot/build_manager.rb:366:in `new'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.172.0/pilot/lib/pilot/build_manager.rb:366:in `transporter_for_selected_team'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.172.0/pilot/lib/pilot/build_manager.rb:33:in `upload'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.172.0/pilot/lib/pilot/commands_generator.rb:66:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'

**Comment by SudhersonV** [comment]
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.172.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:419:in `initialize': [!] undefined method `start_with?' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.172.0/pilot/lib/pilot/build_manager.rb:366:in `new'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.172.0/pilot/lib/pilot/build_manager.rb:366:in `transporter_for_selected_team'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.172.0/pilot/lib/pilot/build_manager.rb:33:in `upload'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.172.0/pilot/lib/pilot/commands_generator.rb:66:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.172.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.172.0/pilot/lib/pilot/commands_generator.rb:166:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.172.0/pilot/lib/pilot/commands_generator.rb:18:in `start'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.172.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.172.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:419:in `initialize': undefined method `start_with?' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.172.0/pilot/lib/pilot/build_manager.rb:366:in `new'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.172.0/pilot/lib/pilot/build_manager.rb:366:in `transporter_for_selected_team'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.172.0/pilot/lib/pilot/build_manager.rb:33:in `upload'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.172.0/pilot/lib/pilot/commands_generator.rb:66:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.172.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.172.0/pilot/lib/pilot/commands_generator.rb:166:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.172.0/pilot/lib/pilot/commands_generator.rb:18:in `start'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.172.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

##[error]Error: The process '/usr/local/bin/fastlane' failed with exit code 1


<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.1                                                           |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.1 (20C69)                                             |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Library/Developer/CommandLineTools/                           |
| Xcode Version               |                                                                |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.172.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.3.0        |
| slack-notifier                | 2.3.2        |
| atomos                        | 0.1.3        |
| CFPropertyList                | 2.3.6        |
| claide                        | 1.0.3        |
| colored2                      | 3.1.2        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| plist                         | 3.6.0        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| multipart-post                | 2.0.0        |
| word_wrap                     | 1.0.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| artifactory                   | 3.0.15       |
| babosa                        | 1.0.4        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| excon                         | 0.78.1       |
| faraday-net_http              | 1.0.1        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.1        |
| gh_inspector                  | 1.1.3        |
| json                          | 2.1.0        |
| mini_magick                   | 4.11.0       |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| xcpretty-travis-formatter     | 1.0.1        |
| dotenv                        | 2.7.6        |
| bundler                       | 1.17.2       |
| naturally                     | 2.2.1        |
| simctl                        | 1.6.8        |
| jwt                           | 2.2.2        |
| uber                          | 0.1.0        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| mini_mime                     | 1.0.2        |
| multi_json                    | 1.15.0       |
| signet                        | 0.14.0       |
| memoist                       | 0.16.2       |
| os                            | 1.1.1        |
| googleauth                    | 0.15.0       |
| httpclient                    | 2.8.3        |
| google-api-client             | 0.38.0       |
| google-cloud-env              | 1.4.0        |
| google-cloud-errors           | 1.0.1        |
| google-cloud-core             | 1.5.0        |
| rexml                         | 3.1.9        |
| webrick                       | 1.4.2        |
| google-apis-core              | 0.2.1        |
| google-apis-iamcredentials_v1 | 0.1.0        |
| google-apis-storage_v1        | 0.1.0        |
| rake                          | 12.3.2       |
| digest-crc                    | 0.6.3        |
| google-cloud-storage          | 1.30.0       |
| emoji_regex                   | 3.2.1        |
| jmespath                      | 1.4.0        |
| aws-partitions                | 1.420.0      |
| aws-eventstream               | 1.1.0        |
| aws-sigv4                     | 1.2.2        |
| aws-sdk-core                  | 3.111.2      |
| aws-sdk-kms                   | 1.41.0       |
| aws-sdk-s3                    | 1.87.0       |
| forwardable                   | 1.2.0        |
| logger                        | 1.3.0        |
| date                          | 2.0.0        |
| stringio                      | 0.0.2        |
| zlib                          | 1.0.0        |
| ipaddr                        | 1.2.2        |
| openssl                       | 2.1.2        |
| ostruct                       | 0.1.0        |
| strscan                       | 1.0.0        |
| fileutils                     | 1.1.0        |
| etc                           | 1.0.1        |
| io-console                    | 0.4.7        |
| libxml-ruby                   | 3.1.0        |
| psych                         | 3.1.0        |
| mutex_m                       | 0.1.0        |
</details>


*generated on:* **2021-01-27**
</details>

**Comment by SudhersonV** [comment]
Upgraded to fastlane 2.173.0 same error, please see below.

/Library/Ruby/Gems/2.6.0/gems/fastlane-2.173.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:419:in `initialize': [!] undefined method `start_with?' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.173.0/pilot/lib/pilot/build_manager.rb:366:in `new'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.173.0/pilot/lib/pilot/build_manager.rb:366:in `transporter_for_selected_team'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.173.0/pilot/lib/pilot/build_manager.rb:33:in `upload'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.173.0/pilot/lib/pilot/commands_generator.rb:66:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.173.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.173.0/pilot/lib/pilot/commands_generator.rb:166:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.173.0/pilot/lib/pilot/commands_generator.rb:18:in `start'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.173.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.173.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:419:in `initialize': undefined method `start_with?' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.173.0/pilot/lib/pilot/build_manager.rb:366:in `new'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.173.0/pilot/lib/pilot/build_manager.rb:366:in `transporter_for_selected_team'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.173.0/pilot/lib/pilot/build_manager.rb:33:in `upload'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.173.0/pilot/lib/pilot/commands_generator.rb:66:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.173.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'

**Comment by cpk1** [comment]
Not sure if it would help to run with --verbose to get to the bottom of this, but I had a similar error from fastlane - 'undefined method `start_with?' for nil:NilClass' and the actual issue had to do with fastlane not finding xcodebuild.

**Comment by SudhersonV** [comment]
@cpk1 , thank you very much. My XCode was in a different path. Once I corrected it, this issue disappeared.

# Change the path if you installed Xcode somewhere else.
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
