### ISSUE TITLE
Bundle install throwing error "Bundler could not find compatible versions for gem 'faraday'"

### ISSUE THREAD

**Issue by jayzyaj** [fastlane/fastlane#18083]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm trying to run bundle install inside my iOS project that uses fastlane. However I always got this error in the CLI

```
Bundler could not find compatible versions for gem "faraday":
  In Gemfile:
    fastlane (~> 2.172.0) was resolved to 2.172.0, which depends on
      faraday (~> 1.0)

    tinybucket was resolved to 1.2.0, which depends on
      faraday (= 0.9.0)
```
      

##### Command executed
`bundle install`

##### Complete output when running fastlane, including the stack trace and command used
When I run `bundle install` to install fastlane inside my project directory

<details>
  <pre> Bundler could not find compatible versions for gem "faraday":
  In Gemfile:
    fastlane (~> 2.172.0) was resolved to 2.172.0, which depends on
      faraday (~> 1.0)

    tinybucket was resolved to 1.2.0, which depends on
      faraday (= 0.9.0)</pre>
</details>

### Environment

I am using rvm to manage my ruby version.

Here is my **gemfile**

```
source "https://rubygems.org"

gem 'faraday', '~> 1.0'
gem "fastlane", "~> 2.172.0"
gem "xcov"
gem 'slather', github: "moming2k/slather", :branch => 'feature/add_xccov_support'
gem "cocoapods", "~> 1.8.4"
gem "json-schema-generator"
gem 'tinybucket'
# gem 'slather', :path => "fastlane/ruby_gems/slather"   

```

<details>
  <pre>
- fastlane 2.172.0
- ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
- pod (1.8.4)
- Catalina 10.15.6
</pre>
</details>

**Comment by ainame** [comment]
This is more like your end's issue. It looks like your dependency `tinybucket` has the very strict requirement on `faraday`. You can either update `tinybucket` to use newer `faraday` or stop using it completely.
