### ISSUE TITLE
[itms] When iTMSTransporter fails due to connectivity issues it's not clear what's the root cause because logs are truncated

### ISSUE THREAD

**Issue by bdolewski** [fastlane/fastlane#18087]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Due to corporate environment and chores to configure everything on my CI connected to company's network, I have to fight with different connectivity issues.

Apparently port TCP 443 is blocked in my case but somehow fastlane didn't told me that. Got generic SSL handshake error.

I know this is very niche issue 😄But just maybe there is a way to improve grabbing error messages from iTMSTransporter. I thought my certificates are not trusted or something but it looks more like a blocked port.

##### Command executed
```
INFO [2021-02-01 15:48:24.74]: Wrote XML data to '/var/folders/hp/0p_bskpx1bs2x056pmql4br80000gn/T/d20210201-35646-16xkaos/1550953438.itmsp'
INFO [2021-02-01 15:48:24.74]: Going to upload updated app to App Store Connect
INFO [2021-02-01 15:48:24.74]: This might take a few minutes. Please don't interrupt the script.
DEBUG [2021-02-01 15:48:24.74]: xcrun iTMSTransporter -m upload -jwt YourJWT -f /var/folders/hp/0p_bskpx1bs2x056pmql4br80000gn/T/d20210201-35646-16xkaos/1550953438.itmsp -k 100000 2>&1
DEBUG [2021-02-01 15:48:27.66]: [Transporter]: INFO: An error occurred checking the HEAD for: https://contentdelivery.itunes.apple.com/transporter/repositories/j2se8/latest/repository.xml Remote host terminated the handshake Exception's name: javax.net.ssl.SSLHandshakeException, Exception's message: Remote host terminated the handshake
DEBUG [2021-02-01 15:48:28.19]: [Transporter]: INFO: An error occurred checking the HEAD for: https://contentdelivery.itunes.apple.com/transporter/repositories/j2se7/latest/repository.xml Remote host terminated the handshake Exception's name: javax.net.ssl.SSLHandshakeException, Exception's message: Remote host terminated the handshake
DEBUG [2021-02-01 15:48:28.71]: [Transporter]: INFO: An error occurred checking the HEAD for: https://contentdelivery.itunes.apple.com/transporter/repositories/j2se6/latest/repository.xml Remote host terminated the handshake Exception's name: javax.net.ssl.SSLHandshakeException, Exception's message: Remote host terminated the handshake
DEBUG [2021-02-01 15:48:29.25]: [Transporter]: INFO: An error occurred checking the HEAD for: https://contentdelivery.itunes.apple.com/transporter/repositories/j2se5/latest/repository.xml Remote host terminated the handshake Exception's name: javax.net.ssl.SSLHandshakeException, Exception's message: Remote host terminated the handshake
WARN [2021-02-01 15:48:29.26]: [iTMSTransporter] java.lang.reflect.InvocationTargetException

WARN [2021-02-01 15:48:29.26]: [iTMSTransporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

WARN [2021-02-01 15:48:29.26]: [iTMSTransporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

WARN [2021-02-01 15:48:29.26]: [iTMSTransporter] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

WARN [2021-02-01 15:48:29.26]: [iTMSTransporter] 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)

WARN [2021-02-01 15:48:29.26]: [iTMSTransporter] 	at com.apple.transporter.launcher.Application.start(Application.java:450)

WARN [2021-02-01 15:48:29.26]: [iTMSTransporter] 	at com.apple.transporter.launcher.Application.main(Application.java:947)

WARN [2021-02-01 15:48:29.26]: [iTMSTransporter] Caused by: java.io.IOException: Could not connect to any repositories

WARN [2021-02-01 15:48:29.26]: [iTMSTransporter] 	at com.apple.transporter.misc.RemoteBundleRepository.getRepositoryUriAndEtag(RemoteBundleRepository.java:227)

WARN [2021-02-01 15:48:29.26]: [iTMSTransporter] 	at com.apple.transporter.misc.RemoteBundleRepository.loadResourcesFromRepository(RemoteBundleRepository.java:141)

WARN [2021-02-01 15:48:29.26]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.downloadNeededBundles(BootstrapperPhase1.java:247)

WARN [2021-02-01 15:48:29.26]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.bootstrap(BootstrapperPhase1.java:97)

WARN [2021-02-01 15:48:29.26]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.bootstrap(BootstrapperPhase1.java:59)

WARN [2021-02-01 15:48:29.26]: [iTMSTransporter] 	at com.apple.transporter.launcher.Launcher.launchBootstrapper(Launcher.java:37)

WARN [2021-02-01 15:48:29.26]: [iTMSTransporter] 	... 6 more

INFO [2021-02-01 15:48:29.26]: iTunes Transporter output above ^
ERROR [2021-02-01 15:48:29.26]: The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
```

However when I copied the iTMSTransporter command and pasted into terminal:

```
git:(develop) xcrun iTMSTransporter -m upload -jwt YourJWT -f /var/folders/hp/0p_bskpx1bs2x056pmql4br80000gn/T/d20210201-35646-16xkaos/1550953438.itmsp -k 100000 2>&1
[2021-02-01 16:00:10 CET] <main>  INFO: Configuring logging...
[2021-02-01 16:00:10 CET] <main>  INFO: Logging level set to eXtreme
[2021-02-01 16:00:10 CET] <main>  INFO: Transporter is searching for new software components.
[2021-02-01 16:00:10 CET] <main>  INFO: INFO: using cached repository.xml file.
[2021-02-01 16:00:10 CET] <main>  INFO: Update check complete.
[2021-02-01 16:00:12 CET] <main> DEBUG: Attempting refresh of configuration data from https://contentdelivery.itunes.apple.com/transporter/Defaults.properties
[2021-02-01 16:00:12 CET] <main> DEBUG: Configuration refresh successful.
[2021-02-01 16:00:12 CET] <main> DEBUG: Saving configuration to local path: /Users/iosci/Library/Caches/com.apple.amp.itmstransporter/Defaults.properties
[2021-02-01 16:00:13 CET] <main>  INFO: iTMSTransporter : iTunes Store Transporter [2.1.0]
[2021-02-01 16:00:13 CET] <main>  INFO: OS identifier: Mac OS X 11.1 (x86_64); jvm=14.0.2+12-iTunesOpenJDK-5; jre=14.0.2+12-iTunesOpenJDK-5
[2021-02-01 16:00:13 CET] <main>  INFO: Memory: [JVM] 736M free, 1024M total, 2048M max [System] (Physical) 359M free, 16384M total (Swap) 1023M free, 1024M total
[2021-02-01 16:00:13 CET] <main> DBG-X: Memory: [JVM] 736M free, 1024M total, 2048M max [System] (Physical) 360M free, 16384M total (Swap) 1023M free, 1024M total
[2021-02-01 16:00:13 CET] <main> DBG-X: Using operation named: authenticateForSession
[2021-02-01 16:00:13 CET] <main> DBG-X: Apple's web service operation input parameters:
[2021-02-01 16:00:13 CET] <main> DBG-X:   parameter Application = iTMSTransporter
[2021-02-01 16:00:13 CET] <main> DBG-X:   parameter BaseVersion = 2.1.0
[2021-02-01 16:00:13 CET] <main> DBG-X:   parameter OSIdentifier = Mac OS X 11.1 (x86_64); jvm=14.0.2+12-iTunesOpenJDK-5; jre=14.0.2+12-iTunesOpenJDK-5
[2021-02-01 16:00:13 CET] <main> DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2021-02-01T16:00:13+01:00
[2021-02-01 16:00:13 CET] <main> DBG-X:   parameter StatisticsPreviousCallDurationInSecs = 0.336263352
[2021-02-01 16:00:13 CET] <main> DBG-X:   parameter TransporterArguments = -m upload -jwt **hidden value** -f /var/folders/hp/0p_bskpx1bs2x056pmql4br80000gn/T/d20210201-35646-16xkaos/1550953438.itmsp -k 100000
[2021-02-01 16:00:13 CET] <main> DBG-X:   parameter Version = 2.1.0
[2021-02-01 16:00:13 CET] <main> DBG-X:   parameter iTMSTransporterMode = upload
[2021-02-01 16:00:13 CET] <main>  INFO: id = 20210201160013-482
[2021-02-01 16:00:13 CET] <main>  INFO: iTMSTransporter Correlation Key: 47e2429a-70f5-4b6a-8ffa-bf29c1986745-0001
[2021-02-01 16:00:13 CET] <main> ERROR: Communication error. Please use diagnostic mode to check connectivity. You need to have outbound access to TCP port 443.
[2021-02-01 16:00:13 CET] <main> ERROR: An exception has occurred: Remote host terminated the handshake
[2021-02-01 16:00:13 CET] <main> DEBUG: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 11.1                                                    |
| Ruby                        | 2.7.2                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.30.0                                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.172.0/libexec/bin/fastlane |
| Host                        | macOS 11.1 (20C69)                                      |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.7/2.7.2/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                              |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 12.4                                                    |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.172.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.4.0        |
| slack-notifier                | 2.3.2        |
| atomos                        | 0.1.3        |
| CFPropertyList                | 3.0.3        |
| claide                        | 1.0.3        |
| colored2                      | 3.1.2        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| plist                         | 3.6.0        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| multipart-post                | 2.0.0        |
| word_wrap                     | 1.0.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| artifactory                   | 3.0.15       |
| babosa                        | 1.0.4        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| excon                         | 0.78.1       |
| faraday-net_http              | 1.0.1        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.1        |
| gh_inspector                  | 1.1.3        |
| json                          | 2.3.0        |
| mini_magick                   | 4.11.0       |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| xcpretty-travis-formatter     | 1.0.1        |
| dotenv                        | 2.7.6        |
| bundler                       | 2.1.4        |
| naturally                     | 2.2.1        |
| simctl                        | 1.6.8        |
| jwt                           | 2.2.2        |
| uber                          | 0.1.0        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| mini_mime                     | 1.0.2        |
| multi_json                    | 1.15.0       |
| signet                        | 0.14.0       |
| memoist                       | 0.16.2       |
| os                            | 1.1.1        |
| googleauth                    | 0.14.0       |
| httpclient                    | 2.8.3        |
| google-api-client             | 0.38.0       |
| google-cloud-env              | 1.4.0        |
| google-cloud-errors           | 1.0.1        |
| google-cloud-core             | 1.5.0        |
| rexml                         | 3.2.3        |
| google-apis-core              | 0.2.0        |
| google-apis-iamcredentials_v1 | 0.1.0        |
| google-apis-storage_v1        | 0.1.0        |
| rake                          | 13.0.3       |
| digest-crc                    | 0.6.3        |
| google-cloud-storage          | 1.30.0       |
| emoji_regex                   | 3.2.1        |
| jmespath                      | 1.4.0        |
| aws-partitions                | 1.417.0      |
| aws-eventstream               | 1.1.0        |
| aws-sigv4                     | 1.2.2        |
| aws-sdk-core                  | 3.111.2      |
| aws-sdk-kms                   | 1.41.0       |
| aws-sdk-s3                    | 1.87.0       |
| uri                           | 0.10.0       |
| forwardable                   | 1.3.1        |
| logger                        | 1.4.2        |
| cgi                           | 0.1.0        |
| date                          | 3.0.0        |
| timeout                       | 0.1.0        |
| stringio                      | 0.1.0        |
| zlib                          | 1.1.0        |
| ipaddr                        | 1.2.2        |
| openssl                       | 2.1.2        |
| ostruct                       | 0.2.0        |
| strscan                       | 1.0.3        |
| delegate                      | 0.1.0        |
| fileutils                     | 1.4.1        |
| io-console                    | 0.5.6        |
| open3                         | 0.1.0        |
| singleton                     | 0.1.0        |
| racc                          | 1.4.16       |
| nokogiri                      | 1.11.1       |
| yaml                          | 0.1.0        |
| psych                         | 3.1.0        |
| mutex_m                       | 0.1.0        |
</details>

**Comment by rogerluan** [comment]
This PR https://github.com/fastlane/fastlane/pull/12259 that was just released should fix this issue for you @bdolewski @Vannevelj
