### ISSUE TITLE
updateAppGroupIdentifiers Action fails when using Fastlane.swift

### ISSUE THREAD

**Issue by SvenTiigi** [fastlane/fastlane#18085]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When trying to update the app group identifiers in the `Fastfile.swift` via:

```swift
updateAppGroupIdentifiers(
    entitlementsFile: "MyApp/MyApp.entitlements",
    appGroupIdentifiers: ["group.com.company.MyApp"]
)
```
fastlane is finishing with the following error:

```bash
15:37:26]: Error setting value 'group.com.company.MyApp' for option 'app_group_identifiers'
[15:37:26]: You passed invalid parameters to 'update_app_group_identifiers'.
[15:37:26]: Check out the error below and available options by running `fastlane action update_app_group_identifiers`
...
[15:37:26]: The parameter app_group_identifiers need to be an Array.
[15:37:26]: fastlane finished with errors
```

I have tried serval options like passing a simple string or adding single quotes to the string itself but none of them worked.

##### Command executed
I'm getting the same error when trying to update the app group identifiers via the terminal command:
```bash
fastlane run update_app_group_identifiers entitlements_file:MyApp/MyApp.entitlements app_group_identifiers:'group.com.company.MyApp'
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
[✔] 🚀
[15:37:00]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[15:37:02]: Updated ./fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj
[15:37:02]: Resolving Swift Package Manager dependencies...
[15:37:02]: $ xcodebuild -resolvePackageDependencies -scheme FastlaneRunner -project ./fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj
[15:37:03]: ▸ Command line invocation:
[15:37:03]: ▸     /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -scheme FastlaneRunner -project ./fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj
[15:37:03]: ▸ resolved source packages:
[15:37:03]: $ xcodebuild -showBuildSettings -scheme FastlaneRunner -project ./fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj
[15:37:05]: $ set -o pipefail && xcodebuild -scheme FastlaneRunner -project ./fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj -destination 'generic/platform=macOS' build | tee /Users/sventiigi/Library/Logs/gym/App-FastlaneRunner.log | xcpretty
[15:37:26]: $ ./fastlane/FastlaneRunner lane patchAppGroupIdentifiers swiftServerPort 2000 > /dev/null
[15:37:26]: Error setting value 'group.com.company.MyApp' for option 'app_group_identifiers'
[15:37:26]: You passed invalid parameters to 'update_app_group_identifiers'.
[15:37:26]: Check out the error below and available options by running `fastlane action update_app_group_identifiers`
+-----------+--------------------------+
|             Lane Context             |
+-----------+--------------------------+
| LANE_NAME | patchAppGroupIdentifiers |
+-----------+--------------------------+
[15:37:26]: The parameter app_group_identifiers need to be an Array.
[15:37:26]: fastlane finished with errors

[!] The parameter app_group_identifiers need to be an Array.
</pre>
</details>

### Environment

<details>
  <pre>
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.1                                        |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.rbenv/versions/2.6.3/bin/fastlane        |
| Host                        | macOS 11.1 (20C69)                          |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.3/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.4                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             | 🚫 |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

```ruby
// This file contains the fastlane.tools configuration
// You can find the documentation at https://docs.fastlane.tools
//
// For a list of all available actions, check out
//
//     https://docs.fastlane.tools/actions
//

import Foundation

class Fastfile: LaneFile {

    func testLane() {
        updateAppGroupIdentifiers(
            entitlementsFile: "MyApp/MyApp.entitlements",
            appGroupIdentifiers: ["group.com.company.MyApp"]
        )
    }
    
}

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.172.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.5.0        |
| slack-notifier                | 2.3.2        |
| atomos                        | 0.1.3        |
| CFPropertyList                | 3.0.3        |
| claide                        | 1.0.3        |
| colored2                      | 3.1.2        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| plist                         | 3.6.0        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| multipart-post                | 2.0.0        |
| word_wrap                     | 1.0.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| artifactory                   | 3.0.15       |
| babosa                        | 1.0.4        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| excon                         | 0.78.1       |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| gh_inspector                  | 1.1.3        |
| mini_magick                   | 4.11.0       |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| xcpretty-travis-formatter     | 1.0.1        |
| dotenv                        | 2.7.6        |
| bundler                       | 2.2.7        |
| naturally                     | 2.2.1        |
| simctl                        | 1.6.8        |
| jwt                           | 2.2.2        |
| uber                          | 0.1.0        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| mini_mime                     | 1.0.2        |
| multi_json                    | 1.15.0       |
| signet                        | 0.14.1       |
| memoist                       | 0.16.2       |
| os                            | 1.1.1        |
| googleauth                    | 0.15.0       |
| httpclient                    | 2.8.3        |
| google-api-client             | 0.38.0       |
| google-cloud-env              | 1.4.0        |
| google-cloud-errors           | 1.0.1        |
| google-cloud-core             | 1.5.0        |
| google-apis-core              | 0.2.1        |
| google-apis-iamcredentials_v1 | 0.1.0        |
| google-apis-storage_v1        | 0.1.0        |
| digest-crc                    | 0.6.3        |
| google-cloud-storage          | 1.30.0       |
| emoji_regex                   | 3.2.1        |
| jmespath                      | 1.4.0        |
| aws-eventstream               | 1.1.0        |
| aws-sigv4                     | 1.2.2        |
| aws-sdk-core                  | 3.111.2      |
| aws-sdk-kms                   | 1.41.0       |
| aws-sdk-s3                    | 1.87.0       |
| ruby2_keywords                | 0.0.4        |
| faraday-net_http              | 1.0.1        |
| faraday                       | 1.3.0        |
| fastimage                     | 2.2.2        |
| json                          | 2.5.1        |
| rexml                         | 3.2.4        |
| webrick                       | 1.7.0        |
| rake                          | 13.0.3       |
| aws-partitions                | 1.422.0      |
| forwardable                   | 1.3.2        |
| logger                        | 1.4.3        |
| date                          | 3.1.1        |
| stringio                      | 3.0.0        |
| zlib                          | 1.1.0        |
| openssl                       | 2.2.0        |
| ipaddr                        | 1.2.2        |
| ostruct                       | 0.3.3        |
| strscan                       | 3.0.0        |
| fileutils                     | 1.5.0        |
| io-console                    | 0.5.7        |
| psych                         | 3.3.0        |
| mutex_m                       | 0.1.1        |
</details>

*generated on:* **2021-02-01**
</details>
</pre>
</details>

**Comment by jeremierichard** [comment]
Same issue for me.
I think the json returned by [`json` property in `RubyCommand.swift`](https://github.com/fastlane/fastlane/blob/afd4540ea9fdbff20813fc32acd60d6e7febf7bd/fastlane/swift/RubyCommand.swift#L54) is not compatible with the [expected parameter here](https://github.com/fastlane/fastlane/blob/afd4540ea9fdbff20813fc32acd60d6e7febf7bd/fastlane/lib/fastlane/actions/update_app_group_identifiers.rb#L58)

**Comment by jeremierichard** [comment]
I can reproduce with this command
`fastlane run update_app_group_identifiers entitlements_file:"Path/to.entitlements" app_group_identifiers:"com.A,com.B"`
which gives
`The parameter app_group_identifiers need to be an Array.`

From the docs, the above syntax for array should be correct, see CLI paragraph from https://docs.fastlane.tools/actions/update_app_group_identifiers/

**Comment by minuscorp** [comment]
This is fixed in the linked PR, you can check it out and see if it works properly for you all 😄 .
