### ISSUE TITLE
exist bad error when updating session for a dev account

### ISSUE THREAD

**Issue by davidmdt21** [fastlane/fastlane#18089]
hello guys ,
in our system ( linux) i have bad error

when i want update session for each dev account , i get error : and u know after i restart server  , this issue fixs ! but we have this problem after some hours ! again and again ... please help me , its really important for my project . 
notice : i just use Fastlane and spaceship just for add UDID - get provision  ! 

/var/www/html/Api# fastlane spaceauth
[✔] 🚀 
[07:23:19]: fastlane detected a Gemfile in the current directory
[07:23:19]: However, it seems like you didn't use `bundle exec`
[07:23:19]: To launch fastlane faster, please use
[07:23:19]: 
[07:23:19]: $ bundle exec fastlane spaceauth
[07:23:19]: 
[07:23:19]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
Username: p-------@gmail.com
Logging into to App Store Connect (p-------@gmail.com)...
-------------------------------------------------------------------------------------
Please provide your Apple Developer Program account credentials
You can also pass the password using the `FASTLANE_PASSWORD` environment variable
-------------------------------------------------------------------------------------
Password (for p-------@gmail.com): **************
could not find a temporary directory
Continuing with normal login.
No such file or directory @ rb_sysopen - /tmp/spaceship1612250616_11833_47387543891740.log
Could not login to App Store Connect
Please check your credentials and try again.
This could be an issue with App Store Connect,
Please try unsetting the FASTLANE_SESSION environment variable
(if it is set) and re-run `fastlane spaceauth`

Exception type: Spaceship::AppleTimeoutError

Looking for related GitHub issues on fastlane/fastlane...

➡️  `get_certificates` and `get_provisioning_profile` fail with `Could not receive latest API key from App Store Connect, this might be a server issue.`
    https://github.com/fastlane/fastlane/issues/17055 [closed] 4 💬
    21 Oct 2020

➡️  Having deliver/upload_to_app_store issues? Install 2.150.0.rc5
    https://github.com/fastlane/fastlane/issues/16639 [closed] 116 💬
    04 Sep 2020

➡️  [deliver][produce][spaceship] Update to use new App Store Connect API endpoints
    https://github.com/fastlane/fastlane/pull/16626 [closed] 140 💬
    27 Jul 2020

and 8 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09Could%20not%20receive%20latest%20API%20key%20from%20App%20Store%20Connect%2C%20this%20might%20be%20a%20server%20issue.&type=Issues&utf8=✓

[!] The request could not be completed because:
	Could not receive latest API key from App Store Connect, this might be a server issue.

any body have idea ? 

thank you so much guys

**Comment by max-ott** [comment]
Please post the full stack trace and fill out the issue template.
