### ISSUE TITLE
`fastlane spaceauth` is failing with `2FA can only be performed in interactive mode`

### ISSUE THREAD

**Issue by garylai** [fastlane/fastlane#18094]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: 2.172.0
- Last working version: 2.170.0

### Regression Description

We have a `node` program that update Apple session periodically using `fastlane spaceauth`. The 2FA code is written to the `stdin` of the child process. Thus the streams are not tty. This recent change: https://github.com/fastlane/fastlane/pull/17854 forces the command to run only in interactive shell which breaks our pipeline. As there are ways to send input to interactive program running in non-interactive shell and ways to check whether the shell is interactive or not before executing a program, it doesn't seem appropriate to force users to use `spaceauth` only in interactive shell.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>"/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.172.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:7:in `handle_two_step_or_factor': \u001b[31m[!] 2FA can only be performed in interactive mode\u001b[0m (RuntimeError)
\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.172.0/spaceship/lib/spaceship/client.rb:500:in `send_shared_login_request'
\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.172.0/spaceship/lib/spaceship/tunes/tunes_client.rb:127:in `send_login_request'
\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.172.0/spaceship/lib/spaceship/client.rb:793:in `do_login'
\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.172.0/spaceship/lib/spaceship/client.rb:390:in `login'
\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.172.0/spaceship/lib/spaceship/client.rb:352:in `login'
\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.172.0/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.172.0/spaceship/lib/spaceship/spaceauth_runner.rb:18:in `run'
\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.172.0/spaceship/lib/spaceship/commands_generator.rb:44:in `block (2 levels) in run'
\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.172.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.172.0/spaceship/lib/spaceship/commands_generator.rb:50:in `run'
\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.172.0/spaceship/lib/spaceship/commands_generator.rb:14:in `start'
\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.172.0/bin/fastlane:23:in `<top (required)>'
\tfrom /usr/local/bin/fastlane:23:in `load'
\tfrom /usr/local/bin/fastlane:23:in `<main>`</pre>
</details>

### Environment

<details>
  <pre><details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                    |
| --------------------------- | -------------------------------------------------------- |
| OS                          | debian_based 9.13                                        |
| Ruby                        | 2.5.7                                                    |
| Bundler?                    | false                                                    |
| Git                         | git version 2.11.0                                       |
| Installation Source         | /usr/local/bin/fastlane                                  |
| Host                        | Debian GNU/Linux 9 debian_based 9.13 (4.19.121-linuxkit) |
| Ruby Lib Dir                | /usr/local/lib                                           |
| OpenSSL Version             | OpenSSL 1.1.0l  10 Sep 2019                              |
| Is contained                | false                                                    |
| Is homebrew                 | false                                                    |
| Is installed via Fabric.app | false                                                    |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.172.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.2.0        |
| slack-notifier                | 2.3.2        |
| atomos                        | 0.1.3        |
| CFPropertyList                | 3.0.3        |
| claide                        | 1.0.3        |
| colored2                      | 3.1.2        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| plist                         | 3.6.0        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| multipart-post                | 2.0.0        |
| word_wrap                     | 1.0.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| artifactory                   | 3.0.15       |
| babosa                        | 1.0.4        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| excon                         | 0.78.1       |
| faraday-net_http              | 1.0.1        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.1        |
| gh_inspector                  | 1.1.3        |
| json                          | 2.1.0        |
| mini_magick                   | 4.11.0       |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| xcpretty-travis-formatter     | 1.0.1        |
| dotenv                        | 2.7.6        |
| bundler                       | 2.2.6        |
| naturally                     | 2.2.1        |
| simctl                        | 1.6.8        |
| jwt                           | 2.2.2        |
| uber                          | 0.1.0        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| mini_mime                     | 1.0.2        |
| multi_json                    | 1.15.0       |
| signet                        | 0.14.0       |
| memoist                       | 0.16.2       |
| os                            | 1.1.1        |
| googleauth                    | 0.14.0       |
| httpclient                    | 2.8.3        |
| google-api-client             | 0.38.0       |
| google-cloud-env              | 1.4.0        |
| google-cloud-errors           | 1.0.1        |
| google-cloud-core             | 1.5.0        |
| rexml                         | 3.2.4        |
| webrick                       | 1.4.2        |
| google-apis-core              | 0.2.1        |
| google-apis-iamcredentials_v1 | 0.1.0        |
| google-apis-storage_v1        | 0.1.0        |
| rake                          | 12.3.0       |
| digest-crc                    | 0.6.3        |
| google-cloud-storage          | 1.30.0       |
| emoji_regex                   | 3.2.1        |
| jmespath                      | 1.4.0        |
| aws-partitions                | 1.418.0      |
| aws-eventstream               | 1.1.0        |
| aws-sigv4                     | 1.2.2        |
| aws-sdk-core                  | 3.111.2      |
| aws-sdk-kms                   | 1.41.0       |
| aws-sdk-s3                    | 1.87.0       |
| date                          | 1.0.0        |
| stringio                      | 0.0.1        |
| zlib                          | 1.0.0        |
| openssl                       | 2.1.2        |
| strscan                       | 1.0.0        |
| fileutils                     | 1.0.2        |
| etc                           | 1.0.0        |
| io-console                    | 0.4.6        |
| ipaddr                        | 1.2.0        |
| psych                         | 3.0.2        |
</details>

*generated on:* **2021-02-02**
</details></pre>
</details>

**Comment by kohtenko** [comment]
Good catch, I think it's easier to just allow you to override this with an env variable. This PR should fix it https://github.com/fastlane/fastlane/pull/18109

**Comment by WhyLogin** [comment]
I get the same error and need help

**Comment by BenWolstencroft** [comment]
We're seeing the same issue in Azure DevOps Pipeline using the AppStoreRelease@1 task.

WE've configured our AppStore service connection in DevOps with a Fastlane Session following the instructions here: https://github.com/fastlane/fastlane/blob/master/spaceship/README.md#support-for-ci-machines

**Comment by gabsima-nexapp** [comment]
Is there any workaround until the PR is merged?

**Comment by juanmalm** [comment]
Same issue here in Azure DevOps with AppStoreRelease@1 task.

**Comment by talhakaya** [comment]
Same issue here on a local build machine set up with TeamCity.

**Comment by larsriehn** [comment]
Thanks @BenWolstencroft  that made my build work again!
