### ISSUE TITLE
How safe & trustworthy are hosting sites such as sourceforge, github or bitbucket for closed-source projects?

### ISSUE THREAD

**Issue by McDonald147** [fastlane/fastlane#18118]
I am considering using sourceforge, bitbucket or github for managing source control for my business. I have open projects and I participate in open projects such as gcc. But I also have a business where I develop closed-source software for my living.

How trustworthy are sourceforge, github or bitbucket in terms of keeping software secure from prying eyes? How stable is the hosting in terms of data loss prevention? Has anyone out there based their business logic with such an outfit? Has anyone out there surveyed several of the hosting solutions?

**Comment by max-ott** [comment]
Im not seeing any relevance to Fastlane.
