### ISSUE TITLE
2FA + Build Upload + Multiple Apps = Confusion

### ISSUE THREAD

**Issue by igor-makarov** [fastlane/fastlane#18126]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

#### Given that:
* An unattended CI user is enrolled in 2FA and is using `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`.
* The upload doesn't wait for build processing.
* There are multiple apps in the ASC account.

#### When running:
`upload_to_testflight` action without the `apple_id` parameter (name is misleading, it's the iTunes app id).

#### 2FA prompt happens
My guess is it's trying to infer the ITC app id, and that requires 2FA.

**Comment by max-ott** [comment]
I have no idea what actually the issue is. Please be more descriptive and fill out the complete issue template.
