### ISSUE TITLE
[pilot] iTMSTransporter authentication issue with 2FA

### ISSUE THREAD

**Issue by kapfab** [fastlane/fastlane#18127]
### New Issue Checklist

- [✓] Updated fastlane to the latest version
- [✓] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [✓] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [✓] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Now that 2FA is enabled on our CI account, we get an iTMSTransporter authentication error with `pilot`.
We use `fastlane spaceauth` to authenticate (no application-specific password, no App Store Connect API Key).
Authentication is successful for `sigh` (`Successfully logged in` and fetching) and for the App Store Connect part of `pilot` (`Login successful`).
Error happens after the `Ready to upload new build to TestFlight` step.

##### Command executed
`fastlane pilot upload --skip_submission --skip_waiting_for_build_processing`

##### Complete output when running fastlane, including the stack trace and command used
<details>
<pre>
[✔] 🚀 
[15:09:40]: fastlane detected a Gemfile in the current directory
[15:09:40]: However, it seems like you didn't use `bundle exec`
[15:09:40]: To launch fastlane faster, please use
[15:09:40]: 
[15:09:40]: $ bundle exec fastlane pilot upload --skip_submission --skip_waiting_for_build_processing --verbose
[15:09:40]: 
[15:09:40]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
INFO [2021-02-04 15:09:44.67]: Login to App Store Connect (•••@•••)
Reading keychain entry, because either user or password were empty
Loading session from '/Users/•••/.fastlane/spaceship/•••@•••/cookie'
Looking for App Store Connect Team with ID ••••••
INFO [2021-02-04 15:09:45.73]: Login successful
DEBUG [2021-02-04 15:09:45.79]: App identifier (•••)
INFO [2021-02-04 15:09:50.23]: Ready to upload new build to TestFlight (App: •••••••••)...
DEBUG [2021-02-04 15:09:50.23]: App Platform (ios)
INFO [2021-02-04 15:09:50.95]: Wrote XML data to '/var/folders/2w/fbr68bf93p7ffxs850cc4mf40000gq/T/d20210204-33576-1vmf82x/547653186.itmsp'
DEBUG [2021-02-04 15:09:51.03]: ITMS_TRANSPORTER_PASSWORD=YourPassword xcrun iTMSTransporter -m provider -u •••@••• -p @env:ITMS_TRANSPORTER_PASSWORD 2>&1
DEBUG [2021-02-04 15:09:53.84]: [Transporter]: INFO: Configuring logging...
DEBUG [2021-02-04 15:09:53.84]: [Transporter]: INFO: Logging level set to eXtreme
DEBUG [2021-02-04 15:09:53.85]: [Transporter]: INFO: Transporter is searching for new software components.
DEBUG [2021-02-04 15:09:53.85]: [Transporter]: INFO: INFO: using cached repository.xml file.
DEBUG [2021-02-04 15:09:54.11]: [Transporter]: INFO: Update check complete.
DEBUG [2021-02-04 15:09:56.22]: [Transporter]: DEBUG: Attempting refresh of configuration data from https://contentdelivery.itunes.apple.com/transporter/Defaults.properties
DEBUG [2021-02-04 15:09:56.33]: [Transporter]: DEBUG: Configuration refresh successful.
DEBUG [2021-02-04 15:09:56.34]: [Transporter]: DEBUG: Saving configuration to local path: /Users/•••/Library/Caches/com.apple.amp.itmstransporter/Defaults.properties
DEBUG [2021-02-04 15:09:56.50]: [Transporter]: INFO: iTMSTransporter : iTunes Store Transporter [2.1.0]
DEBUG [2021-02-04 15:09:56.50]: [Transporter]: INFO: OS identifier: Mac OS X 10.15.7 (x86_64); jvm=14.0.2+12-iTunesOpenJDK-5; jre=14.0.2+12-iTunesOpenJDK-5
DEBUG [2021-02-04 15:09:56.50]: [Transporter]: INFO: Memory: [JVM] 698M free, 1024M total, 2048M max [System] (Physical) 5671M free, 16384M total (Swap) 1022M free, 1024M total
DEBUG [2021-02-04 15:09:56.50]: [Transporter]: INFO: Provider mode selected.
DEBUG [2021-02-04 15:09:56.50]: [Transporter]: DBG-X: Memory: [JVM] 698M free, 1024M total, 2048M max [System] (Physical) 5671M free, 16384M total (Swap) 1022M free, 1024M total
DEBUG [2021-02-04 15:09:56.50]: [Transporter]: DBG-X: Using operation named: authenticateForSession
DEBUG [2021-02-04 15:09:56.52]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2021-02-04 15:09:56.53]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2021-02-04 15:09:56.53]: [Transporter]: DBG-X:   parameter BaseVersion = 2.1.0
DEBUG [2021-02-04 15:09:56.53]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.15.7 (x86_64); jvm=14.0.2+12-iTunesOpenJDK-5; jre=14.0.2+12-iTunesOpenJDK-5
DEBUG [2021-02-04 15:09:56.53]: [Transporter]: DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2021-02-04T15:09:56+01:00
DEBUG [2021-02-04 15:09:56.53]: [Transporter]: DBG-X:   parameter StatisticsPreviousCallDurationInSecs = 0.305969757
DEBUG [2021-02-04 15:09:56.53]: [Transporter]: DBG-X:   parameter TransporterArguments = -m provider -u •••@••• -p **hidden value**
DEBUG [2021-02-04 15:09:56.53]: [Transporter]: DBG-X:   parameter Version = 2.1.0
DEBUG [2021-02-04 15:09:56.53]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = provider
DEBUG [2021-02-04 15:09:56.53]: [Transporter]: INFO: id = 20210204150956-369
DEBUG [2021-02-04 15:09:56.58]: [Transporter]: INFO: iTMSTransporter Correlation Key: •••
ERROR [2021-02-04 15:09:57.17]: [Transporter Error Output]: Please sign in with an app-specific password. You can create one at appleid.apple.com. (-22910)
ERROR [2021-02-04 15:09:57.21]: Transporter transfer failed.
WARN [2021-02-04 15:09:57.21]: 
ERROR [2021-02-04 15:09:57.21]: Please sign in with an app-specific password. You can create one at appleid.apple.com. (-22910)
ERROR [2021-02-04 15:09:57.37]: 
ERROR [2021-02-04 15:09:57.37]: Your account has 2 step verification enabled
ERROR [2021-02-04 15:09:57.37]: Please go to https://appleid.apple.com/account/manage
ERROR [2021-02-04 15:09:57.37]: and generate an application specific password for
ERROR [2021-02-04 15:09:57.37]: the iTunes Transporter, which is used to upload builds
ERROR [2021-02-04 15:09:57.37]: 
ERROR [2021-02-04 15:09:57.37]: To set the application specific password on a CI machine using
ERROR [2021-02-04 15:09:57.37]: an environment variable, you can set the
ERROR [2021-02-04 15:09:57.37]: FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD variable
-------------------------------------------------------------------------------------
Please provide your Apple Developer Program account credentials
The login information you enter will be stored in your macOS Keychain
-------------------------------------------------------------------------------------
/usr/local/lib/ruby/gems/2.7.0/gems/highline-1.7.10/lib/highline.rb:624: warning: Using the last argument as keyword parameters is deprecated
Password (application-specific for •••@•••):
</pre>
</details>

### Environment
<details>

##### Stack
| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.15.7                                          |
| Ruby                        | 2.7.2                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.24.3 (Apple Git-128)               |
| Installation Source         | /usr/local/bin/fastlane                          |
| Host                        | Mac OS X 10.15.7 (19H2)                          |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.7.2/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-12.2.app/Contents/Developer/ |
| Xcode Version               | 12.2                                             |

##### System Locale
| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

##### fastlane gems
| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.172.0 | ✅ Up-To-Date  |

##### Loaded gems
| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.4.0        |
| slack-notifier                            | 2.3.2        |
| atomos                                    | 0.1.3        |
| CFPropertyList                            | 3.0.2        |
| claide                                    | 1.0.3        |
| colored2                                  | 3.1.2        |
| nanaimo                                   | 0.3.0        |
| xcodeproj                                 | 1.19.0       |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.7.0        |
| terminal-table                            | 1.8.0        |
| plist                                     | 3.5.0        |
| public_suffix                             | 4.0.6        |
| addressable                               | 2.7.0        |
| multipart-post                            | 2.0.0        |
| word_wrap                                 | 1.0.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| artifactory                               | 3.0.15       |
| babosa                                    | 1.0.4        |
| colored                                   | 1.2          |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| excon                                     | 0.78.0       |
| ruby2_keywords                            | 0.0.2        |
| faraday                                   | 1.1.0        |
| unf_ext                                   | 0.0.7.7      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.0.0        |
| fastimage                                 | 2.2.0        |
| gh_inspector                              | 1.1.3        |
| json                                      | 2.3.0        |
| mini_magick                               | 4.11.0       |
| rubyzip                                   | 2.3.0        |
| security                                  | 0.1.3        |
| xcpretty-travis-formatter                 | 1.0.0        |
| dotenv                                    | 2.7.6        |
| bundler                                   | 2.1.4        |
| naturally                                 | 2.2.0        |
| simctl                                    | 1.6.8        |
| jwt                                       | 2.2.2        |
| uber                                      | 0.1.0        |
| declarative                               | 0.0.20       |
| declarative-option                        | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| mini_mime                                 | 1.0.2        |
| multi_json                                | 1.15.0       |
| signet                                    | 0.14.0       |
| memoist                                   | 0.16.2       |
| os                                        | 1.1.1        |
| googleauth                                | 0.14.0       |
| httpclient                                | 2.8.3        |
| google-api-client                         | 0.38.0       |
| google-cloud-env                          | 1.4.0        |
| google-cloud-errors                       | 1.0.1        |
| google-cloud-core                         | 1.5.0        |
| rake                                      | 13.0.1       |
| digest-crc                                | 0.6.1        |
| google-cloud-storage                      | 1.29.1       |
| emoji_regex                               | 3.2.1        |
| jmespath                                  | 1.4.0        |
| aws-partitions                            | 1.393.0      |
| aws-eventstream                           | 1.1.0        |
| aws-sigv4                                 | 1.2.2        |
| aws-sdk-core                              | 3.109.2      |
| aws-sdk-kms                               | 1.39.0       |
| aws-sdk-s3                                | 1.84.1       |
| uri                                       | 0.10.0       |
| forwardable                               | 1.3.1        |
| logger                                    | 1.4.2        |
| cgi                                       | 0.1.0        |
| timeout                                   | 0.1.0        |
| stringio                                  | 0.1.0        |
| ipaddr                                    | 1.2.2        |
| openssl                                   | 2.1.2        |
| ostruct                                   | 0.2.0        |
| strscan                                   | 1.0.3        |
| date                                      | 3.0.0        |
| delegate                                  | 0.1.0        |
| fileutils                                 | 1.4.1        |
| io-console                                | 0.5.6        |
| zlib                                      | 1.1.0        |
| open3                                     | 0.1.0        |
| singleton                                 | 0.1.0        |
| mini_portile2                             | 2.4.0        |
| nokogiri                                  | 1.10.10      |
| racc                                      | 1.4.16       |
| rexml                                     | 3.2.3        |
| yaml                                      | 0.1.0        |
| psych                                     | 3.1.0        |
| mutex_m                                   | 0.1.0        |
| webrick                                   | 1.6.0        |
| fastlane-plugin-firebase_app_distribution | 0.2.4        |
| pstore                                    | 0.1.0        |

</details>

**Comment by max-ott** [comment]
iTMSTransporter does not work with 2FA. For it to work you need an application specific password. This should resolve the issue.

**Comment by kapfab** [comment]
Actually, it works with an App Store Connect API Key, too.
But we try to avoid mixing different authentication methods as we use both Enterprise and AppStore accounts on the same machine.

Anyway, what I understand from the Fastlane documentation and from several discussions on 2FA related issues is that using the `spaceauth` session should be enough for all actions.

**Comment by kapfab** [comment]
You closed this issue a bit prematurely IMHO.

Just looking at http://docs.fastlane.tools/actions/testflight/#use-an-application-specific-password-to-upload, you can read ```pilot/upload_to_testflight **can use** an Application Specific Password via the FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD environment variable to upload a binary if both the skip_waiting_for_build_processing and apple_id options are set. (**If any of those are not set, it will use the normal Apple login process that might require 2FA authentication.**)```.

**Comment by max-ott** [comment]
If it no longer works, Apple probably changed it.

**Comment by kapfab** [comment]
That’s why I spent time to investigate and create this issue.
