### ISSUE TITLE
Authentication credentials are missing or invalid running sigh

### ISSUE THREAD

**Issue by miquelalvarado** [fastlane/fastlane#18128]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Our CI started failing after Apple's enforcement to use 2FA so we've changed our approach to use AppStore Connect API. We've followed the [fastlane documentation](https://docs.fastlane.tools/app-store-connect-api/) to generate an admin-role p8 and use it to properly authenticate before calling `get_provisioning_profile`. Somehow, though, it's failing while getting provisioning profile with the error

```
Authentication credentials are missing or invalid. - Provide a properly configured and signed bearer token, and make sure that it has not expired. Learn more about Generating Tokens for API Requests https://developer.apple.com/go/?id=api-generating-tokens
```
If I've understood it correctly, running the `app_store_connect_api_key` lane before the `get_provisioning_profile` should be enough for it to successfully access and download the provisioning but it keeps failing.

#### How are we using it?
```ruby
api_key = app_store_connect_api_key(
        key_id: app.signing_config.api_key_id,
        issuer_id: app.signing_config.api_key_issuer,
        key_content: 'base64_key_content',
        is_key_content_base64: true,
        in_house: true,
        duration: 1200
    )
get_provisioning_profile(
      api_key: api_key,
      app_identifier: bundle_id,
      adhoc: false,
      provisioning_name: provisioning_name,
      readonly: false,
      fail_on_name_taken: true
    )
```

#### Output

```
...
[10:08:14]: ---------------------------------------------------
[10:08:14]: --- Step: Switch to ios fetch_provisioning lane ---
[10:08:14]: ---------------------------------------------------
[10:08:14]: Cruising over to lane 'ios fetch_provisioning' 🚖
[10:08:14]: ---------------------------------------
[10:08:14]: --- Step: app_store_connect_api_key ---
[10:08:14]: ---------------------------------------
[10:08:14]: --------------------------------------
[10:08:14]: --- Step: get_provisioning_profile ---
[10:08:14]: --------------------------------------
+-------------------------------------+--------------------------+
|                    Summary for sigh 2.172.0                    |
+-------------------------------------+--------------------------+
| api_key                             | ********                 |
| app_identifier                      | com.foo.app.beta    |
| adhoc                               | false                    |
| provisioning_name                   | Foo Beta TestFlight |
| readonly                            | false                    |
| fail_on_name_taken                  | true                     |
| developer_id                        | false                    |
| development                         | false                    |
| skip_install                        | false                    |
| force                               | false                    |
| ignore_profiles_with_different_name | false                    |
| skip_fetch_profiles                 | false                    |
| skip_certificate_verification       | false                    |
| platform                            | ios                      |
+-------------------------------------+--------------------------+
[10:08:14]: Creating authorization token for App Store Connect API
[10:08:14]: Fetching profiles...
+---------------------------+-----------------------------------------------------+
|                                  Lane Context                                   |
+---------------------------+-----------------------------------------------------+
| DEFAULT_PLATFORM          | ios                                                 |
| PLATFORM_NAME             | ios                                                 |
| LANE_NAME                 | ios distribute_beta                                 |
| BUILD_NUMBER              | 3931                                                |
| KEYCHAIN_PATH             | ~/Library/Keychains/travis.keychain                 |
| ORIGINAL_DEFAULT_KEYCHAIN | "/Users/travis/Library/Keychains/login.keychain-db" |
+---------------------------+-----------------------------------------------------+
[10:08:15]: Authentication credentials are missing or invalid. - Provide a properly configured and signed bearer token, and make sure that it has not expired. Learn more about Generating Tokens for API Requests https://developer.apple.com/go/?id=api-generating-tokens
```
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.1                                        |
| Ruby                        | 2.5.7                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.15.1                          |
| Installation Source         | ~/.gem/ruby/2.5.7/bin/fastlane              |
| Host                        | macOS 11.1 (20C69)                          |
| Ruby Lib Dir                | ~/.rubies/ruby-2.5.7/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.4                                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**
**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.172.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.4.0        |
| bundler                       | 2.1.4        |
| rake                          | 13.0.3       |
| CFPropertyList                | 3.0.3        |
| concurrent-ruby               | 1.1.8        |
| i18n                          | 1.8.7        |
| minitest                      | 5.14.3       |
| thread_safe                   | 0.3.6        |
| tzinfo                        | 1.2.9        |
| activesupport                 | 5.2.4.4      |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| httpclient                    | 2.8.3        |
| json                          | 2.5.1        |
| algoliasearch                 | 1.27.5       |
| rubyzip                       | 2.3.0        |
| apktools                      | 0.7.4        |
| artifactory                   | 3.0.15       |
| atomos                        | 0.1.3        |
| aws-eventstream               | 1.1.0        |
| aws-partitions                | 1.422.0      |
| aws-sigv4                     | 1.2.2        |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.112.0      |
| aws-sdk-kms                   | 1.42.0       |
| aws-sdk-s3                    | 1.88.0       |
| babosa                        | 1.0.4        |
| claide                        | 1.0.3        |
| fuzzy_match                   | 2.0.4        |
| nap                           | 1.1.0        |
| netrc                         | 0.11.0       |
| ffi                           | 1.14.2       |
| ethon                         | 0.12.0       |
| typhoeus                      | 1.4.0        |
| cocoapods-core                | 1.10.1       |
| cocoapods-deintegrate         | 1.0.4        |
| cocoapods-downloader          | 1.4.0        |
| cocoapods-plugins             | 1.0.0        |
| cocoapods-search              | 1.0.0        |
| cocoapods-trunk               | 1.5.0        |
| cocoapods-try                 | 1.2.0        |
| colored2                      | 3.1.2        |
| escape                        | 0.0.4        |
| fourflusher                   | 2.3.1        |
| gh_inspector                  | 1.1.3        |
| molinillo                     | 0.6.6        |
| ruby-macho                    | 1.4.0        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| cocoapods                     | 1.10.1       |
| redcarpet                     | 3.5.1        |
| cocoapods-acknowledgements    | 1.3.0        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| digest-crc                    | 0.6.3        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| dotenv                        | 2.7.6        |
| emoji_regex                   | 3.2.1        |
| excon                         | 0.79.0       |
| faraday-net_http              | 1.0.1        |
| multipart-post                | 2.0.0        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.2        |
| jwt                           | 2.2.2        |
| memoist                       | 0.16.2       |
| multi_json                    | 1.15.0       |
| os                            | 1.1.1        |
| signet                        | 0.14.1       |
| googleauth                    | 0.15.0       |
| mini_mime                     | 1.0.2        |
| uber                          | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| google-api-client             | 0.38.0       |
| rexml                         | 3.2.4        |
| webrick                       | 1.7.0        |
| google-apis-core              | 0.2.1        |
| google-apis-iamcredentials_v1 | 0.1.0        |
| google-apis-storage_v1        | 0.1.0        |
| google-cloud-env              | 1.4.0        |
| google-cloud-errors           | 1.0.1        |
| google-cloud-core             | 1.5.0        |
| google-cloud-storage          | 1.30.0       |
| mini_magick                   | 4.11.0       |
| plist                         | 3.6.0        |
| security                      | 0.1.3        |
| naturally                     | 2.2.1        |
| simctl                        | 1.6.8        |
| slack-notifier                | 2.3.2        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| word_wrap                     | 1.0.0        |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| xcpretty-travis-formatter     | 1.0.1        |
| mime-types-data               | 3.2020.1104  |
| mime-types                    | 3.3.1        |
| fastlane-plugin-aws_s3        | 1.8.0        |
| rugged                        | 0.99.0       |
| thor                          | 0.20.3       |
| trainer                       | 0.9.1        |
| xcpretty-json-formatter       | 0.1.1        |
| floki                         | 5.9.2        |
</details>

**Comment by casperriboe** [comment]
Did you fix your issue?

**Comment by miquelalvarado** [comment]
Yes... I'm kind of embarrassed to say but after hours trying to find out the issue I realized i had a typo in the `key_id` or the `issuer_id`, don't remember which one 🤦‍♂️

**Comment by casperriboe** [comment]
Oh, that's a classic. Good to know, thanks for sharing. Gonna check myself 🙂
