### ISSUE TITLE
2FA prompt appears inexplicably when using app-specific password.

### ISSUE THREAD

**Issue by igor-makarov** [fastlane/fastlane#18130]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

#### Given that:
* An unattended CI user is enrolled in 2FA and is using `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`.
* The upload doesn't wait for build processing.
* There are multiple apps in the ASC account.

There is a 2FA prompt when there should be none. Alternatively, the upload action should raise an error if multiple apps are used together with an app-specific password.

##### Command executed

```
FASTLANE_USER=username FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD=password bundle exec fastlane upload_build ipa_path:/Users/Igor/Downloads/xxxx.ipa --env store
```
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
[17:30:11]: Loading from './fastlane/.env.store'
+-----------------------------+---------+------------------------------------------------------------+
|                                            Used plugins                                            |
+-----------------------------+---------+------------------------------------------------------------+
| Plugin                      | Version | Action                                                     |
+-----------------------------+---------+------------------------------------------------------------+
| fastlane-plugin-xcake       | 0.1.0   | xcake                                                      |
| fastlane-plugin-test_center | 3.6.0   | suppressed_tests suppress_tests suppress_tests_from_junit  |
|                             |         | tests_from_xctestrun collate_test_result_bundles           |
|                             |         | tests_from_junit multi_scan collate_html_reports           |
|                             |         | collate_junit_reports collate_json_reports                 |
| fastlane-plugin-appcenter   | 1.11.0  | appcenter_fetch_version_number appcenter_fetch_devices     |
|                             |         | appcenter_upload                                           |
+-----------------------------+---------+------------------------------------------------------------+

[17:30:15]: Driving the lane 'upload_build' 🚀
[17:30:15]: iTunes Connect Team ID: 99999
[17:30:15]: ----------------------------------
[17:30:15]: --- Step: upload_to_testflight ---
[17:30:15]: ----------------------------------
[17:30:15]: Login to App Store Connect (xxx@xxx)
Available session is not valid any more. Continuing with normal login.
Two-factor Authentication (6 digits code) is enabled for account 'xxx@xxx.com'
More information about Two-factor Authentication: https://support.apple.com/en-us/HT204915

If you're running this in a non-interactive session (e.g. server or CI)
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification

(Input `sms` to escape this prompt and select a trusted phone number to send the code as a text message)

(You can also set the environment variable `SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER` to automate this)
(Read more at: https://github.com/fastlane/fastlane/blob/master/spaceship/docs/Authentication.md#auto-select-sms-via-spaceship_2fa_sms_default_phone_number)

/usr/local/lib/ruby/gems/2.7.0/gems/highline-1.7.10/lib/highline.rb:624: warning: Using the last argument as keyword parameters is deprecated
Please enter the 6 digit code:

 </pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 11.1                                             |
| Ruby                        | 2.7.1                                            |
| Bundler?                    | true                                             |
| Git                         | git version 2.24.3 (Apple Git-128)               |
| Installation Source         | /usr/local/lib/ruby/gems/2.7.0/bin/fastlane      |
| Host                        | macOS 11.1 (20C69)                               |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.7.1_2/lib               |
| OpenSSL Version             | OpenSSL 1.1.1f  31 Mar 2020                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-12.3.app/Contents/Developer/ |
| Xcode Version               | 12.3                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

# redacted

desc "Upload the build to the relevant delivery service
Required params:

ipa_path:<path_to_ipa>

Also: use --env to switch flavors, available: #{envs}"
lane :upload_build do |options|
  if ENV['PROVISIONING_TYPE'] == 'appstore'
    UI.message "iTunes Connect Team ID: #{itunes_team_id}"
    ENV['DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS'] = '-t Signiant'
    upload_to_testflight(
      app_identifier: ENV['BUNDLE_PREFIX'],
      ipa: options[:ipa_path],
      team_id: itunes_team_id,
      skip_submission: true,
      skip_waiting_for_build_processing: true
    )
  else
    #redacted
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier 'redacted'

team_name 'redacted'
team_id 'redacted'

itc_team_name 'redacted'
itc_team_id 'redacted'

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.172.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                      | Version | Update-Status      |
| --------------------------- | ------- | ------------------ |
| fastlane-plugin-xcake       | 0.1.0   | ✅ Up-To-Date       |
| fastlane-plugin-test_center | 3.6.0   | 🚫 Update available |
| fastlane-plugin-appcenter   | 1.11.0  | ✅ Up-To-Date       |

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.4.0        |
| bundler                       | 1.17.3       |
| uri                           | 0.10.0       |
| etc                           | 1.1.0        |
| cgi                           | 0.1.0        |
| readline-ext                  | 0.1.0        |
| forwardable                   | 1.3.1        |
| delegate                      | 0.1.0        |
| fileutils                     | 1.4.1        |
| rake                          | 13.0.3       |
| CFPropertyList                | 3.0.2        |
| concurrent-ruby               | 1.1.6        |
| i18n                          | 1.8.3        |
| minitest                      | 5.14.1       |
| thread_safe                   | 0.3.6        |
| tzinfo                        | 1.2.7        |
| activesupport                 | 5.2.4.3      |
| public_suffix                 | 4.0.5        |
| addressable                   | 2.7.0        |
| httpclient                    | 2.8.3        |
| json                          | 2.3.1        |
| algoliasearch                 | 1.27.5       |
| artifactory                   | 3.0.15       |
| ast                           | 2.4.0        |
| atomos                        | 0.1.3        |
| aws-eventstream               | 1.1.0        |
| aws-partitions                | 1.422.0      |
| aws-sigv4                     | 1.2.2        |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.112.0      |
| aws-sdk-kms                   | 1.42.0       |
| aws-sdk-s3                    | 1.88.0       |
| babosa                        | 1.0.4        |
| debug_inspector               | 0.0.3        |
| binding_of_caller             | 0.8.0        |
| byebug                        | 10.0.2       |
| claide                        | 1.0.3        |
| fuzzy_match                   | 2.0.4        |
| nap                           | 1.1.0        |
| netrc                         | 0.11.0       |
| ffi                           | 1.11.3       |
| ethon                         | 0.12.0       |
| typhoeus                      | 1.3.1        |
| cocoapods-core                | 1.10.0       |
| cocoapods-deintegrate         | 1.0.4        |
| cocoapods-downloader          | 1.4.0        |
| cocoapods-plugins             | 1.0.0        |
| cocoapods-search              | 1.0.0        |
| cocoapods-trunk               | 1.5.0        |
| cocoapods-try                 | 1.2.0        |
| colored2                      | 3.1.2        |
| escape                        | 0.0.4        |
| fourflusher                   | 2.3.1        |
| gh_inspector                  | 1.1.3        |
| molinillo                     | 0.6.6        |
| ruby-macho                    | 1.4.0        |
| nanaimo                       | 0.3.0        |
| rexml                         | 3.2.4        |
| xcodeproj                     | 1.19.0       |
| cocoapods                     | 1.10.0       |
| cocoapods-git-tarball         | 0.0.1        |
| coderay                       | 1.1.2        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| cork                          | 0.3.0        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| deep_merge                    | 1.2.1        |
| digest-crc                    | 0.6.3        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| dotenv                        | 2.7.6        |
| emoji_regex                   | 3.2.1        |
| excon                         | 0.79.0       |
| faraday-net_http              | 1.0.1        |
| multipart-post                | 2.0.0        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.2        |
| jwt                           | 2.2.2        |
| memoist                       | 0.16.2       |
| multi_json                    | 1.15.0       |
| os                            | 1.1.1        |
| signet                        | 0.14.1       |
| googleauth                    | 0.15.0       |
| mini_mime                     | 1.0.2        |
| uber                          | 0.0.15       |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| google-api-client             | 0.38.0       |
| webrick                       | 1.7.0        |
| google-apis-core              | 0.2.1        |
| google-apis-iamcredentials_v1 | 0.1.0        |
| google-apis-storage_v1        | 0.1.0        |
| google-cloud-env              | 1.4.0        |
| google-cloud-errors           | 1.0.1        |
| google-cloud-core             | 1.5.0        |
| google-cloud-storage          | 1.30.0       |
| mini_magick                   | 4.11.0       |
| plist                         | 3.5.0        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| naturally                     | 2.2.0        |
| simctl                        | 1.6.8        |
| slack-notifier                | 2.3.2        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.4.1        |
| terminal-table                | 1.8.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| word_wrap                     | 1.0.0        |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| xcpretty-travis-formatter     | 1.0.1        |
| fastlane-plugin-appcenter     | 1.11.0       |
| xctest_list                   | 1.1.6        |
| fastlane-plugin-test_center   | 3.6.0        |
| hooks                         | 0.4.1        |
| xcake                         | 0.10.0       |
| fastlane-plugin-xcake         | 0.1.0        |
| trollop                       | 2.1.2        |
| filewatcher                   | 1.0.1        |
| interception                  | 0.5          |
| jaro_winkler                  | 1.5.1        |
| method_source                 | 0.9.1        |
| parallel                      | 1.12.1       |
| parser                        | 2.5.3.0      |
| powerpack                     | 0.1.2        |
| pry                           | 0.12.0       |
| pry-byebug                    | 3.6.0        |
| pry-rescue                    | 1.5.0        |
| pry-stack_explorer            | 0.4.9.3      |
| rainbow                       | 3.0.0        |
| ruby-progressbar              | 1.10.0       |
| rubocop                       | 0.61.1       |
| xcode-install                 | 2.4.4        |
</details>

*generated on:* **2021-02-04**
</details>

**Comment by igor-makarov** [comment]
Sorry for the confusing description in #18126. Hopefully this clears everything up.

@joshdholtz was the one that I discussed the issue with and I guess I forgot to include a lot of the background by mistake.

**Comment by sergeykochanov** [comment]
Try to set application's apple_id parameter.

**Comment by igor-makarov** [comment]
This issue is mostly about incorrect fault mode, perhaps this can be a newbie PR? @joshdholtz

**Comment by igor-makarov** [comment]
Has this been addressed? It's mostly a messaging issue.
