### ISSUE TITLE
download_dsyms "latest" version does not download latest version

### ISSUE THREAD

**Issue by sisoje** [fastlane/fastlane#18131]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I uploaded v4.8.10 to testflight, fastlane still downloads v4.8.9 on my local machine, and on CI machine it downloads v4.8.8
 
##### Command executed

`fastlane run download_dsyms app_identifier:"com.myid" team_id:"666" version:"latest" --verbose`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre></pre>
</details>

### Environment
Github actions

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by sisoje** [comment]
now it downloaded 4.8.8 !

**Comment by sisoje** [comment]
i use now `after_uploaded_date` aproach because latest does not work

**Comment by aried3r** [comment]
Hey @sisoje, it appears this might have been fixed in a recent version, see https://github.com/fastlane/fastlane/pull/18201.
