### ISSUE TITLE
xcpretty missing after fresh fastlane install

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1813]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/166391?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @hborders - Imported from <a href='https://github.com/fastlane/gym/issues/235'>fastlane/gym#235</a>
        </td>
      </tr>
    </table>

I installed fastlane with `sudo gem install fastlane --verbose` on OSX 10.11.3. I had to reinstall after I upgraded from OSX 10.10.5. When I ran `fastlane`, I saw the following output on my `gym` step:

```
[10:24:25]: -----------------
[10:24:25]: --- Step: gym ---
[10:24:25]: -----------------
[10:24:25]: xcrun xcodebuild -list -project './Foo.xcodeproj'

+----------------------+----------------------+
|            Summary for gym 1.6.1            |
+----------------------+----------------------+
| scheme               | Foo                |
| export_method        | ad-hoc               |
| output_directory     | ./build              |
| project              | ./Foo.xcodeproj   |
| destination          | generic/platform=iOS |
| output_name          | Foo                |
| clean                | false                |
| silent               | false                |
| use_legacy_build_api | false                |
| buildlog_path        | ~/Library/Logs/gym   |
+----------------------+----------------------+

[10:24:29]: $ set -o pipefail && xcodebuild -scheme 'Foo' -project './Foo.xcodeproj' -destination 'generic/platform=iOS' -archivePath '/Users/bordersh/Library/Developer/Xcode/Archives/2016-03-07/Foo 2016-03-07 10.24.29.xcarchive' archive | tee /Users/bordersh/Library/Logs/gym/Foo-Foo.log | xcpretty
[10:24:29]: ▸ sh: xcpretty: command not found
^C
Cancelled... use --verbose to show the stack trace
```

I waited a minute or two and then killed the process because I didn't see any output.

Then, I ran `sudo gem install xcpretty --verbose` and everything seemed to work fine again. I guess there's a dependency missing somewhere?

**Comment by zapjonny** [comment]
Me too. Any progress?

**Comment by TKBurner** [comment]
@zapjonny Were you able to fix this by running `sudo gem install xcpretty`?

**Comment by zapjonny** [comment]
No.

I found out that Jenkins cannot find xcpretty if it is started by the instructions on screen after installing through homebrew. If I start manually using "jenkins" on a command line (as my own user I guess), then xcpretty works. The jenkins instructions at https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Jenkins.md in fact does suggest to start jenkins manually like that. I'm not sure but there may be some other ways to start Jenkins up with a correct user so that gym (xcpretty) works properly.

**Comment by TKBurner** [comment]
@zapjonny Awesome! Really glad to hear you got up and running! Hope you have a great weekend 👍
