### ISSUE TITLE
Getting an error on match

### ISSUE THREAD

**Issue by tomvisions** [fastlane/fastlane#18134]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

With the latest version of match, fastlane crashes. 
##### Command executed

I ran this in a fastlane lane, Using CircleCI and fastlane
     api_key = app_store_connect_api_key(
           key_id: ENV['APPLE_API_KEY_ID'],
           issuer_id: ENV['APPLE_API_ISSUER_ID'],
           key_content: ENV['APPLE_API_PRIVATE_KEY'],
           in_house: true, # optional but may be required if using match/sigh
      )
    match(api_key: api_key, git_branch: "main", git_user_email: "email@email.com", git_full_name: "username", app_identifier: "bundleId", type: "appstore", verbose: true, output_path: "/tmp", keychain_name: ENV["MATCH_KEYCHAIN_NAME"], keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"])

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
Distillers-Mac-2:ios distiller$ fastlane beta
[✔] 🚀
[03:19:24]: fastlane detected a Gemfile in the current directory
[03:19:24]: However, it seems like you didn't use `bundle exec`
[03:19:24]: To launch fastlane faster, please use
[03:19:24]:
[03:19:24]: $ bundle exec fastlane beta
[03:19:24]:
[03:19:24]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
Fastfile:51: warning: key :verbose is duplicated and overwritten on line 51
[03:19:31]: ------------------------------
[03:19:31]: --- Step: default_platform ---
[03:19:31]: ------------------------------
[03:19:31]: Driving the lane 'ios beta' 🚀
[03:19:31]: ------------------------------------
[03:19:31]: --- Step: increment_build_number ---
[03:19:31]: ------------------------------------
Current version of project APP is:
    5

/Users/distiller/project/mobile/ios
[03:19:31]: $ cd /Users/distiller/project/mobile/ios && agvtool next-version -all && cd -
[03:19:31]: ▸ Setting version of project APP to:
[03:19:31]: ▸ 6.
[03:19:31]: ▸ Also setting CFBundleVersion key (assuming it exists)
[03:19:31]: ▸ Updating CFBundleVersion in Info.plist(s)...
[03:19:31]: ▸ Updated CFBundleVersion in "APP.xcodeproj/../APP0/Info.plist" to 6
[03:19:31]: ▸ Updated CFBundleVersion in "APP.xcodeproj/../APP1/Info.plist" to 6
[03:19:31]: ▸ Updated CFBundleVersion in "APP.xcodeproj/../APP2/Info.plist" to 6
[03:19:31]: ▸ /Users/distiller/project/mobile/ios
INFO [2021-02-05 03:19:33.23]: -------------------
INFO [2021-02-05 03:19:33.23]: --- Step: match ---
INFO [2021-02-05 03:19:33.23]: -------------------
WARN [2021-02-05 03:19:33.24]: Lane Context:
INFO [2021-02-05 03:19:33.24]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :BUILD_NUMBER=>"6"}
INFO [2021-02-05 03:19:33.24]: Successfully generated documentation at path '/Users/distiller/project/mobile/ios/fastlane/README.md'

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | default_platform       | 0           |
| 2    | increment_build_number | 0           |
| 💥   | match                  | 0           |
+------+------------------------+-------------+

ERROR [2021-02-05 03:19:33.25]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `[]' for nil

URL: https://api.github.com/search/issues?q=undefined%20method%20%60%5B%5D%27%20for%20nil+repo:fastlane/fastlane
➡️  undefined method `id' for nil
    https://github.com/fastlane/fastlane/issues/17818 [open] 2 💬
    2 days ago

➡️  Undefined method `status' for nil:NilClass (NoMethodError)
    https://github.com/fastlane/fastlane/issues/17910 [open] 8 💬
    an hour ago

➡️  Taking screenshots: build working but "undefined method `each' for nil:NilClass "
    https://github.com/fastlane/fastlane/issues/17911 [open] 2 💬
    a week ago

and 493 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60%5B%5D%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	31: from /Users/distiller/.rubies/ruby-2.7.2/bin/fastlane:23:in `<main>'
	30: from /Users/distiller/.rubies/ruby-2.7.2/bin/fastlane:23:in `load'
	29: from /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/bin/fastlane:23:in `<top (required)>'
	28: from /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	27: from /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	26: from /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	25: from /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	24: from /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	23: from /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	22: from /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	21: from /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	20: from /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	19: from /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	18: from /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	17: from /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	16: from /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	15: from /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	14: from /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	13: from Fastfile:51:in `block (2 levels) in parsing_binding'
	12: from /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	11: from /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	10: from /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	 9: from /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	 8: from /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	 7: from /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	 6: from /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 5: from /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/actions/sync_code_signing.rb:12:in `run'
	 4: from /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:172:in `load_configuration_file'
	 3: from /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:172:in `new'
	 2: from /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane_core/lib/fastlane_core/configuration/configuration_file.rb:46:in `initialize'
	 1: from /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane_core/lib/fastlane_core/configuration/configuration_file.rb:46:in `eval'
(eval):7:in `initialize': \e[31m[!] undefined method `[]' for nil:NilClass\e[0m (NoMethodError)
Distillers-Mac-2:ios distiller$
 </pre>
</details>

### Environment

<details>
  <pre>
Distillers-Mac-2:ios distiller$ fastlane env
[✔] 🚀
[03:21:40]: fastlane detected a Gemfile in the current directory
[03:21:40]: However, it seems like you didn't use `bundle exec`
[03:21:40]: To launch fastlane faster, please use
[03:21:40]:
[03:21:40]: $ bundle exec fastlane env
[03:21:40]:
[03:21:40]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[03:21:47]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.5                                     |
| Ruby                        | 2.7.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.29.2                          |
| Installation Source         | ~/.rubies/ruby-2.7.2/bin/fastlane           |
| Host                        | Mac OS X 10.15.5 (19F101)                   |
| Ruby Lib Dir                | ~/.rubies/ruby-2.7.2/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1h  22 Sep 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.2                                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
#ENV["SPACESHIP_SKIP_2FA_UPGRADE"] = "1"
default_platform(:ios)


platform :ios do
  desc "Push APP new beta build to TestFlight"
  lane :keychain do
    setup_circle_ci
    create_keychain(
      name: ENV["MATCH_KEYCHAIN_NAME"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      add_to_search_list: true
    )
    end

  lane :createDevelopmentProfile do
     api_key = app_store_connect_api_key(
             key_id: ENV['APPLE_API_KEY_ID'],
             issuer_id: ENV['APPLE_API_ISSUER_ID'],
             key_content: ENV['APPLE_API_PRIVATE_KEY'],
             in_house: false, # optional but may be required if using match/sigh
        )
    sigh(development: true, api_key: api_key);
  end

  lane :beta do
    increment_build_number(xcodeproj: "APP.xcodeproj");
     api_key = app_store_connect_api_key(
            key_id: ENV['APPLE_API_KEY_ID'],
           issuer_id: ENV['APPLE_API_ISSUER_ID'],
           key_content: ENV['APPLE_API_PRIVATE_KEY'],
           in_house: true, # optional but may be required if using match/sigh
      )
    match(api_key: api_key, verbose: true, git_branch: "main", git_user_email: "email@email.com", git_full_name: "username", app_identifier: "bundleId, type: "appstore", verbose: true, output_path: "/tmp", keychain_name: ENV["MATCH_KEYCHAIN_NAME"], keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"])
    update_code_signing_settings(
      use_automatic_signing: false,
       team_id: "xxxxxxxxx",
    )

    update_project_provisioning(
      xcodeproj: "APP.xcodeproj",
      profile: "/Users/distiller/project/mobile/ios/Development_bundleId.mobileprovision",
      build_configuration: "Release"
    )
    build_app(verbose: true, workspace: "APP.xcworkspace", scheme: "APP",  export_method: "app-store", sdk: "iphoneos14.2", output_directory: "/tmp", "output_name": "test.ipa", toolchain: "com.apple.dt.toolchain.Swift_5_0", xcargs: "arguments", clean: true);
    upload_to_testflight( username: "email@email.com", app_identifier: $ENV['APPSTORE_APP_ID'])
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("bundleId") # The bundle identifier of your app
apple_id("email@email.com") # Your Apple email address

itc_team_id("xxxxxx") # App Store Connect Team ID
team_id("xxxxxxx") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.173.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| artifactory               | 3.0.15       |
| babosa                    | 1.0.4        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.78.0       |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.1.0        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| json                      | 2.3.0        |
| mini_magick               | 4.11.0       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.14.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.4.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-storage      | 1.29.1       |
| emoji_regex               | 3.2.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.393.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.109.2      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.84.1       |
| uri                       | 0.10.0       |
| forwardable               | 1.3.1        |
| logger                    | 1.4.2        |
| cgi                       | 0.1.0        |
| timeout                   | 0.1.0        |
| stringio                  | 0.1.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.2.0        |
| strscan                   | 1.0.3        |
| date                      | 3.0.0        |
| delegate                  | 0.1.0        |
| fileutils                 | 1.4.1        |
| io-console                | 0.5.6        |
| zlib                      | 1.1.0        |
| open3                     | 0.1.0        |
| singleton                 | 0.1.0        |
| rexml                     | 3.2.3        |
| yaml                      | 0.1.0        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.6.0        |
</details>

*generated on:* **2021-02-05**
</details>
[03:21:48]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[03:21:48]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅
Distillers-Mac-2:ios distiller$
 </pre>
</details>

**Comment by max-ott** [comment]
Are you trying to use the App Store Connect API key to authenticate with Apple for inhouse apps? Currently Apple does NOT support the Apple Enterprise Program (inhouse apps) with the ASC API.

**Comment by tomvisions** [comment]
> Are you trying to use the App Store Connect API key to authenticate with Apple for inhouse apps? Currently Apple does NOT support the Apple Enterprise Program (inhouse apps) with the ASC API.

Thanks for your response. 

I read more about the in-house thing.

Is App Store or Enterprise (in house) team? App Store Connect API cannot not determine this on its own (yet)

I'm not sure what that means. Can you provide more details?

Thank you.

Tom

**Comment by max-ott** [comment]
@tomvisions this project is NOT sponsored or affiliate with Apple. Please contact Apple, when they will provide access to the App Store Connect API for inhouse accounts.

If you log in to https://developer.apple.com/account/ what kind of account type do you see there?

**Comment by tomvisions** [comment]
> @tomvisions this project is NOT sponsored or affiliate with Appled. Please contact Apple, when they will provide access to the App Store Connect API for inhouse accounts. This is not within our realm to decide as we are only using the APIs that are available.
> 
> If you log in to https://developer.apple.com/account/ what kind of account type do you see there?

Understood. Good news, my configuration should use false for in_house.

Here is the output that I get, I believe it's the same error.
<pre>
+------+---------------------------+-------------+
|                fastlane summary                |
+------+---------------------------+-------------+
| Step | Action                    | Time (in s) |
+------+---------------------------+-------------+
| 1    | default_platform          | 0           |
| 2    | increment_build_number    | 2           |
| 3    | app_store_connect_api_key | 0           |
| 💥   | match                     | 0           |
+------+---------------------------+-------------+

ERROR [2021-02-05 14:56:57.98]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `[]' for nil

URL: https://api.github.com/search/issues?q=undefined%20method%20%60%5B%5D%27%20for%20nil+repo:fastlane/fastlane
➡️  undefined method `id' for nil
    https://github.com/fastlane/fastlane/issues/17818 [open] 2 💬
    2 days ago

➡️  Undefined method `status' for nil:NilClass (NoMethodError)
    https://github.com/fastlane/fastlane/issues/17910 [open] 8 💬
    13 hours ago

➡️  Taking screenshots: build working but "undefined method `each' for nil:NilClass "
    https://github.com/fastlane/fastlane/issues/17911 [open] 2 💬
    a week ago

and 494 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60%5B%5D%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/Users/distiller/.rubies/ruby-2.7.2/bin/fastlane)
NoMethodError: [!] undefined method `[]' for nil:NilClass
  (eval):7:in `initialize'
  /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane_core/lib/fastlane_core/configuration/configuration_file.rb:46:in `eval'
  /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane_core/lib/fastlane_core/configuration/configuration_file.rb:46:in `initialize'
  /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:172:in `new'
  /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:172:in `load_configuration_file'
  /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/actions/sync_code_signing.rb:12:in `run'
  /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
  /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:51:in `block (2 levels) in parsing_binding'
  /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
  /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/bin/fastlane:23:in `<top (required)>'
  /Users/distiller/.rubies/ruby-2.7.2/bin/fastlane:23:in `load'
  /Users/distiller/.rubies/ruby-2.7.2/bin/fastlane:23:in `<top (required)>'

Exited with code exit status 1
CircleCI received exit code 1
</pre>

**Comment by Dinsen** [comment]
Hi @tomvisions 
Have you specified the `git_url` somewhere else for `Match`?

According to this line:
`13: from Fastfile:51:in block (2 levels) in parsing_binding' 12: from /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/fast_file.rb:159:in method_missing'`

Something is missing and since I can't see where you have specified the `git_url` I think this could maybe be your problem?

**Comment by tomvisions** [comment]
> Hi @tomvisions
> Have you specified the `git_url` somewhere else for `Match`?
> 
> According to this line:
> `13: from Fastfile:51:in block (2 levels) in parsing_binding' 12: from /Users/distiller/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/fast_file.rb:159:in method_missing'`
> 
> Something is missing and since I can't see where you have specified the `git_url` I think this could maybe be your problem?

I did! Here is my Match config file
<pre>
git_url("https://github.com/location.git")
git_branch("main");
storage_mode("git")

type("development") # The default type, can be: appstore, adhoc, enterprise or development

app_identifier($ENV['APPSTORE_APP_ID'])
username("email@email.com") # Your Apple Developer Portal username
</pre>

**Comment by tomvisions** [comment]
no longer seeing this issue. thank you for your time and whoever fixed it.
