### ISSUE TITLE
[Match] App-specific password doesn't work

### ISSUE THREAD

**Issue by fjcaetano** [fastlane/fastlane#18141]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Due to Apple's security changes we had to enable 2FA on the CI account used for automating Fastlane. After this change, we created a new app-specific password for that account, however Match accuses a wrong credentials error.

The password is being configured as the environment var `FASTLANE_PASSWORD`, however, even when unset and manually provided, when requested, but that also failed with the following message:
> The login credentials for '[redacted]' seem to be wrong.

Just to be safe, I also tried removing the dashes from the app-specific password as suggested on #7199 and I tried setting `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` but neither of those worked either.

##### Command executed
```sh
$ bundle exec fastlane match development --force
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
[✔] 🚀 
[15:51:19]: Successfully loaded '[redacted]/Matchfile' 📄

+--------------+----------------------------------------------------+
|                Detected Values from './Matchfile'                 |
+--------------+----------------------------------------------------+
| storage_mode | git                                                |
| git_url      | [redacted]                                         |
| type         | development                                        |
| username     | [redacted]                                         |
+--------------+----------------------------------------------------+

+--------------------------------+----------------------------------------------------+
|                              Summary for match 2.160.0                              |
+--------------------------------+----------------------------------------------------+
| git_branch                     | shared                                             |
| app_identifier                 | [redacted]                                         |
| force                          | true                                               |
| type                           | development                                        |
| readonly                       | false                                              |
| generate_apple_certs           | true                                               |
| skip_provisioning_profiles     | false                                              |
| username                       | [redacted]                                         |
| storage_mode                   | git                                                |
| git_url                        | [redacted]                                         |
| shallow_clone                  | false                                              |
| clone_branch_directly          | false                                              |
| keychain_name                  | login.keychain                                     |
| force_for_new_devices          | false                                              |
| skip_confirmation              | false                                              |
| skip_docs                      | false                                              |
| platform                       | ios                                                |
| derive_catalyst_app_identifier | false                                              |
| fail_on_name_taken             | false                                              |
| verbose                        | false                                              |
+--------------------------------+----------------------------------------------------+

[15:51:20]: Cloning remote git repo...
[15:51:20]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[15:51:21]: Checking out branch shared...
[15:51:22]: 🔓  Successfully decrypted certificates repo
[15:51:22]: Verifying that the certificate and profile are still valid on the Dev Portal...
The login credentials for '[redacted]' seem to be wrong
The password was taken from the environment variable
Please make sure it is correct
[15:51:23]: An error occurred while verifying your certificates and profiles with the Apple Developer Portal.
[15:51:23]: If you already have your certificates stored in git, you can run `fastlane match` in readonly mode
[15:51:23]: to just install the certificates and profiles without accessing the Dev Portal.
[15:51:23]: To do so, just pass `readonly: true` to your match call.

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue

[!] The request could not be completed because:
        Invalid username and password combination. Used '[redacted]' as the username.
  </pre>
</details>

### Environment

<details>
  <pre><details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                        |
| --------------------------- | ------------------------------------------------------------ |
| OS                          | 11.1                                                         |
| Ruby                        | 2.6.5                                                        |
| Bundler?                    | true                                                         |
| Git                         | git version 2.24.3 (Apple Git-128)                           |
| Installation Source         | ~/github/apple-certificates-match/vendor/bundle/bin/fastlane |
| Host                        | macOS 11.1 (20C69)                                           |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.5/lib                                 |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                                  |
| Is contained                | false                                                        |
| Is homebrew                 | false                                                        |
| Is installed via Fabric.app | false                                                        |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                  |
| Xcode Version               | 12.3                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.160.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.17.3       |
| etc                       | 1.0.1        |
| forwardable               | 1.2.0        |
| rake                      | 13.0.1       |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.375.0      |
| aws-sigv4                 | 1.2.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.107.0      |
| aws-sdk-kms               | 1.38.0       |
| aws-sdk-s3                | 1.81.0       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.0.0        |
| excon                     | 0.76.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 1.0.1        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.2.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| signet                    | 0.14.0       |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.0       |
| json                      | 2.3.1        |
| mini_magick               | 4.10.1       |
| plist                     | 3.5.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.18.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2021-02-05**
</details></pre>
</details>

**Comment by Dinsen** [comment]
Hi @fjcaetano 

The app specific password only works with iTMSTransporter (Upload of .ipa file)
So you can't use it for match.
https://docs.fastlane.tools/best-practices/continuous-integration/#application-specific-passwords

You need to run `fastlane spaceauth -u your@appleid.com` on you CI machine or run it on your machine and add the session you get back, to `FASTLANE_SESSION`.

Another solution is to use the API Key:
https://docs.fastlane.tools/app-store-connect-api/
