### ISSUE TITLE
gym not respecting export_options when use_legacy_build_api is true

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1815]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/474?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @cbowns - Imported from <a href='https://github.com/fastlane/gym/issues/231'>fastlane/gym#231</a>
        </td>
      </tr>
    </table>

I've got a lane for exporting a build for Test Flight upload that goes as follows:

```
  lane :test_flight do
    match(type: "appstore")

    # use the UDID of the newly created provisioning profile
    ENV["PROFILE_UDID"] = lane_context[SharedValues::SIGH_UDID]

    # build the app.
    gym(
      scheme: "Inspire",
      use_legacy_build_api: true
      )
  end
```

`gym` seems like it receives my implicit "appstore" request:

```
[15:41:37]: -----------------
[15:41:37]: --- Step: gym ---
[15:41:37]: -----------------
[15:41:37]: Using legacy build system - waiting for radar to be fixed: https://openradar.appspot.com/radar?id=4952000420642816
[15:41:37]: xcrun xcodebuild -list -workspace 'Inspire.xcworkspace'

+----------------------+----------------------+
|            Summary for gym 1.6.1            |
+----------------------+----------------------+
| scheme               | Inspire              |
| use_legacy_build_api | true                 |
| export_method        | app-store            |
| sdk                  | iphoneos             |
| workspace            | Inspire.xcworkspace  |
| clean                | true                 |
| output_directory     | ./fastlane/builds    |
| output_name          | Inspire_Utility      |
| destination          | generic/platform=iOS |
| silent               | false                |
| buildlog_path        | ~/Library/Logs/gym   |
+----------------------+----------------------+
```

(Note: `export_method` above is `app-store`, as desired.)

However, when I open the `.ipa` it produces:

```
[15:45:55]: Successfully exported and compressed dSYM file
[15:45:55]: Successfully exported and signed the ipa file:
[15:45:55]: /Users/cbowns/Development/crlf/carrot-sense/utility-iOS/fastlane/builds/Inspire_Utility.ipa

# cd ~/Desktop
# cp /Users/cbowns/Development/crlf/carrot-sense/utility-iOS/fastlane/builds/Inspire_Utility.ipa ~/Desktop
# unzip ~/Desktop/Inspire_Utility.ipa

# codesign -d -vv Payload/Inspire.app                                                       
Executable=/Users/cbowns/Desktop/Payload/Inspire.app/Inspire
Identifier=com.carrotsense.Inspire.utility
Format=bundle with Mach-O universal (armv7 arm64)
CodeDirectory v=20200 size=18095 flags=0x0(none) hashes=895+5 location=embedded
Signature size=4364
Authority=iPhone Developer: Carrot-Sense Developer (LAG42SBR79)
Authority=Apple Worldwide Developer Relations Certification Authority
Authority=Apple Root CA
Signed Time=Mar 2, 2016, 3:45:43 PM
Info.plist entries=31
TeamIdentifier=L3WD573F5U
Sealed Resources version=2 rules=12 files=58
Internal requirements count=1 size=204
```

The build is still development-signed: `Authority=iPhone Developer: Carrot-Sense Developer (LAG42SBR79)`

(For ease of viewing, from ProvisioningQL:

![screen shot 2016-03-02 at 3 55 48 pm](https://cloud.githubusercontent.com/assets/474/13479926/4908779e-e08f-11e5-9214-edd1f81dde90.png)

I manually exported another app copy from the archive in Xcode, and Xcode gave me the desired distribution-signed build:

```
# codesign -d -vv Payload/Inspire.app                                                              
Executable=/Users/cbowns/Desktop/Inspire 2016-03-02 15-29-49/Payload/Inspire.app/Inspire
Identifier=com.carrotsense.Inspire.utility
Format=bundle with Mach-O universal (armv7 arm64)
CodeDirectory v=20200 size=18095 flags=0x0(none) hashes=895+5 location=embedded
Signature size=4362
Authority=iPhone Distribution: Carrot Sense, Inc (L3WD573F5U)
Authority=Apple Worldwide Developer Relations Certification Authority
Authority=Apple Root CA
Signed Time=Mar 2, 2016, 3:29:42 PM
Info.plist entries=31
TeamIdentifier=L3WD573F5U
Sealed Resources version=2 rules=12 files=58
Internal requirements count=1 size=200
```

Screenshot:

![screen shot 2016-03-02 at 3 55 56 pm](https://cloud.githubusercontent.com/assets/474/13479932/503196a4-e08f-11e5-9791-86c7c8efceed.png)

The punchline: `gym` clearly knew I wanted an `app-store` build, but failed to actually create one. How can I find out why? And how can I get it to actually do an `app-store` build?

**Comment by cbowns** [comment]
@mpirri I know the repo migration generated a lot of noise. I added more info about our build configs.

**Comment by KrauseFx** [comment]
To come back to the original issue: You can't provide the export_options when you use the legacy build API, since the legacy build API from Xcode doesn't support it

**Comment by cbowns** [comment]
how does `gym` export the build when using `legacy_build_api`?

**Comment by cbowns** [comment]
I'm harping on this issue a bit, because this worked flawlessly in two projects just a few weeks ago, and fell apart sometime recently.

**Comment by cbowns** [comment]
1. Yes, I still need to use `use_legacy_build_api`. (Just tried without it in Xcode 7.3.1 and it failed.)
2. I don't actually know if this is an issue.

**Comment by cbowns** [comment]
Yeah, I think we can close this.

**Comment by KrauseFx** [comment]
Thanks 👍
