### ISSUE TITLE
Trailing newline causing JSON parsing failure

### ISSUE THREAD

**Issue by jsorge** [fastlane/fastlane#18155]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm putting my App Store Connect API key in a JSON file, and my text editor put in a trailing newline to the JSON file. When I use this file in Fastlane I get the following parsing error:

```
JSON::ParserError: [!] 809: unexpected token at '{
    "key_id": "{redacted}",
    "issuer_id": "{redacted}",
    "key": "{redacted}",
    "in_house": false
}
'
```

Removing the trailing newline in the JSON file resolves the issue.

##### Command executed
```ruby
  upload_to_testflight({
    api_key_path: "path/to/file.json"
  })
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.15.7                                          |
| Ruby                        | 2.6.2                                            |
| Bundler?                    | true                                             |
| Git                         | git version 2.28.0                               |
| Installation Source         | ~/.asdf/installs/ruby/2.6.2/bin/fastlane         |
| Host                        | Mac OS X 10.15.7 (19H15)                         |
| Ruby Lib Dir                | ~/.asdf/installs/ruby/2.6.2/lib                  |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode_12.2.app/Contents/Developer/ |
| Xcode Version               | 12.2                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
$asc_key_json_file = 'fastlane/asc-key.json'

desc "Make a build. If `checkWorkingTree` == true then we ensure that there are no git changes"
def build_app_for(checkWorkingTree)
  if checkWorkingTree
    result = `git status --porcelain`
    if !result.nil? && !result.empty?
      UI.user_error!("Your git working tree is not clean.  Please remove all staged and untracked files.")
    end
  end

  reset_derived_data

  match

  build_app
end

desc "Ensure that the tools we need are in proper order"
def check_tool_dependencies
  UI.message("Checking tool installations and outputting versions...")

  xcode_select("/Applications/Xcode_12.2.app")

  gitPath = `which git`
  if !gitPath.nil? && !gitPath.empty?
    UI.message(`git --version`)
  else
    UI.user_error!("Git is not installed on this machine.")
  end

  # Fastlane uses the OpenSSL gem, which uses the openssl executable installed at the /usr/local/opt directory (brew install openssl).
  openSSLPath = `which /usr/local/opt/openssl/bin/openssl`
  if !openSSLPath.nil? && !openSSLPath.empty?
    UI.message(`/usr/local/opt/openssl/bin/openssl version`)
  else
    UI.user_error!("OpenSSL is not installed on this machine in the right directory.  Run brew install openssl")
  end
  UI.message("Finished verifying fastlane external dependencies...")
end

desc "Erase the contents of Derived Data except for that which is needed by Swift Package Manager"
def reset_derived_data
  derived_data_path = ENV["GYM_DERIVED_DATA_PATH"]

  if File.directory?(derived_data_path)
    puts "Clearing all non-SPM content from \"#{derived_data_path}\""

    safe_files = ["SourcePackages"]

    Dir.chdir derived_data_path do
      Dir.glob("*")
      .reject {|f| safe_files.include? f }
      .each { |f| FileUtils.rm_rf(f) }
    end
  else
    puts "Not clearing Derived Data from \"#{derived_data_path}\""
  end
end

desc "Load the environment variables needed by the release environment"
def load_release_env
  UI.message("Loading the Release environment")
  Dotenv.overload(".env.release")
end

desc "Load the environment variables needed by the beta environment"
def load_beta_env
  UI.message("Loading the Beta environment")
  Dotenv.overload(".env.beta")
end

desc "Remove the decoded App Store API Key JSON file"
def remove_asc_key
  # We have to do the `../` to start because our working directory here is `./fastlane`. In our lanes below which
  # use this path, the working directory is the repository root so the actions we pass the path to need the whole relative
  # path.
  `rm "../#{$asc_key_json_file}"`
end

#----------------------------------------------------------
desc "Run unit tests"
lane :tests do
  load_beta_env
  check_tool_dependencies

  scan(
    testplan: "UnitTests",
    reset_simulator: true
  )
end

#----------------------------------------------------------
desc "Run unit tests"
lane :coverage do
  load_beta_env
  check_tool_dependencies

  scan(
    testplan: "UnitTests",
    reset_simulator: true
  )

  slather(
    scheme: "zulily",
    configuration: debug,
    proj: "zulily.xcodeproj",
    html: true,
    show: true)
end

#----------------------------------------------------------
desc "Push a new beta build to TestFlight"
lane :beta do |options|
  load_beta_env
  check_tool_dependencies

  build_app_for(
    options[:checkWorkingTree] == true || options[:checkWorkingTree] == false ? options[:checkWorkingTree] : true
  )

  upload_to_testflight({
    api_key_path: $asc_key_json_file,
    beta_app_review_info: {
      contact_email: "sspring@zulily.com",
      contact_first_name: "Stephen",
      contact_last_name: "Spring",
      contact_phone: "7736773319",
    },
    distribute_external: "true",
    notify_external_testers: true,
    groups: "zuUsers",
    changelog: "Daily build"
  })

  upload_dsyms isBeta:true
  remove_asc_key
end

#----------------------------------------------------------
desc "Makes a release build without uploading to TestFlight."
lane :build_for_release do |options|
  load_release_env

  build_app_for(
    options[:checkWorkingTree] == true || options[:checkWorkingTree] == false ? options[:checkWorkingTree] : true
  )

  upload_dsyms isBeta:true
  remove_asc_key
end

#----------------------------------------------------------
desc "Push a new release build to the App Store"
lane :release do |options|
  load_release_env
  check_tool_dependencies

  build_app_for(
    options[:checkWorkingTree] == true || options[:checkWorkingTree] == false ? options[:checkWorkingTree] : true
  )

  deliver({
    api_key_path: $asc_key_json_file,
    force: true,
    skip_screenshots: true,
    app_identifier: "com.zulily.ios",
    itc_provider: "ZulilyInc",
    submit_for_review: true,
    metadata_path: "./metadata",
    automatic_release: false,
    phased_release: true,
    # Comes from https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/tunes/app_submission.rb
    submission_information: {
      add_id_info_serves_ads: true,
      add_id_info_tracks_action: false,
      add_id_info_tracks_install: false,
      add_id_info_uses_idfa: true,
      content_rights_has_rights: true,
      content_rights_contains_third_party_content: false,
      export_compliance_platform: 'ios',
      export_compliance_compliance_required: false,
      export_compliance_encryption_updated: false,
      export_compliance_app_type: nil,
      export_compliance_uses_encryption: false,
      export_compliance_is_exempt: false,
      export_compliance_contains_third_party_cryptography: false,
      export_compliance_contains_proprietary_cryptography: false
    }
  })

  upload_dsyms isBeta:false

  tag_release
  `git reset --hard`
  remove_asc_key
end

#----------------------------------------------------------
desc "Upload DSYM files to crashlitics"
lane :upload_dsyms do |options|
  if options[:isBeta]
    sh "cd .. && FirebaseCrashlyticsUploadSymbols/upload-symbols -gsp Dependencies/GoogleService-Firebase-Info-Beta.plist -p ios ./build/zulily.app.dSYM.zip"
  else
    sh "cd .. && FirebaseCrashlyticsUploadSymbols/upload-symbols -gsp Dependencies/GoogleService-Info.plist -p ios ./build/zulily.app.dSYM.zip"
  end
end

#----------------------------------------------------------
desc "Tags commit with value provided in Jenkins ios_release job GIT_TAG parameter"
lane :tag_release do
  add_git_tag(tag: ENV["GIT_TAG"])
  push_git_tags
end


# following lanes are for Jenkins (CI)

#----------------------------------------------------------
desc "Do an ios build without submitting to test flight"
lane :ci_build_only do
  load_beta_env

  build_app(
    project: "zulily.xcodeproj",
    scheme: "zulily",
    configuration: "Debug",
    skip_archive: "true",
    skip_package_ipa: "true"
  )
end

#CItests lane differs because of where it writes the code coverage data, specific to Jenkins

#Run with ever MR
#----------------------------------------------------------
desc "Runs the MergeRequest test plan"
lane :ci_test do
  load_beta_env
  check_tool_dependencies

  scan(
    testplan: "MergeRequest",
    code_coverage: true,
    reset_simulator: true
  )

  # Disabled until the executable tools for coverage processing & comparison are not flagged by macOS as malware.
  # sh("../tools/processCoverage.sh")
end

#----------------------------------------------------------

desc "Runs the UnitTests test plan"
lane :ci_test_unit_tests do
  load_beta_env

  scan(
    testplan: "UnitTests",
    code_coverage: true
  )
end

#----------------------------------------------------------
desc "Run Data Logging Tests"
lane :ci_test_datalogging do
  load_beta_env

  scan(
    testplan: "DataLogging"
  )
end

#----------------------------------------------------------
desc "Run UI Tests"
lane :ci_test_ui do
  load_beta_env
  scan(
    testplan: "UITests"
  )
end

#----------------------------------------------------------
desc "Run Snapshot Tests"
lane :ci_test_snapshot do
  load_beta_env
  check_tool_dependencies
  scan(
    testplan: "Snapshot"
  )
end

#----------------------------------------------------------
desc "Runs Fastlane scan and outputs code coverage."
lane :ci_update_base_coverage do |options|
  load_beta_env
  UI.message("This lane runs ZulilyUnitTests and outputs the coverage.")
  check_tool_dependencies
  scan(
    testplan: "MergeRequest",
    reset_simulator: true
  )
end

#----------------------------------------------------------
desc "Run comprehensive test suite"
lane :ci_comprehensive_test do
  load_beta_env
  check_tool_dependencies

  scan(
    testplan: "Comprehensive",
    reset_simulator: true
  )
end

#----------------------------------------------------------
desc "Run Synthetic Tests"
lane :synthetic_jenkins do
  load_beta_env
  check_tool_dependencies

  scan(
    testplan: "SyntheticMonitoring",
    reset_simulator: true
  )
end

#----------------------------------------------------------
desc "Updates the signing certs & provisioning profiles for both beta & release builds"
lane :update_signing do
  # Before doing this it's probably a good idea to call `bundle exec fastlane nuke distribution`
  # so that all of our provisioning profiles & certs are cleared out beforehand.
  cert

  load_beta_env
  match({
    api_key_path: $asc_key_json_file,
    readonly: false
  })

  load_release_env
  match({
    api_key_path: $asc_key_json_file,
    readonly: false
  })

  remove_asc_key
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.173.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                      | Version | Update-Status |
| --------------------------- | ------- | ------------- |
| fastlane-plugin-test_center | 3.15.2  | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.3.0        |
| bundler                       | 1.17.2       |
| etc                           | 1.0.1        |
| forwardable                   | 1.2.0        |
| rake                          | 13.0.3       |
| CFPropertyList                | 3.0.3        |
| concurrent-ruby               | 1.1.8        |
| i18n                          | 1.8.8        |
| minitest                      | 5.14.3       |
| tzinfo                        | 2.0.4        |
| zeitwerk                      | 2.4.2        |
| activesupport                 | 6.1.1        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| artifactory                   | 3.0.15       |
| atomos                        | 0.1.3        |
| aws-eventstream               | 1.1.0        |
| aws-partitions                | 1.425.0      |
| aws-sigv4                     | 1.2.2        |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.112.0      |
| aws-sdk-kms                   | 1.42.0       |
| aws-sdk-s3                    | 1.88.0       |
| babosa                        | 1.0.4        |
| claide                        | 1.0.3        |
| clamp                         | 1.3.2        |
| colored                       | 1.2          |
| colored2                      | 3.1.2        |
| colorize                      | 0.8.1        |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| digest-crc                    | 0.6.3        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| dotenv                        | 2.7.6        |
| emoji_regex                   | 3.2.1        |
| excon                         | 0.79.0       |
| faraday-net_http              | 1.0.1        |
| multipart-post                | 2.0.0        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.2        |
| gh_inspector                  | 1.1.3        |
| jwt                           | 2.2.2        |
| memoist                       | 0.16.2       |
| multi_json                    | 1.15.0       |
| os                            | 1.1.1        |
| signet                        | 0.14.1       |
| googleauth                    | 0.15.0       |
| httpclient                    | 2.8.3        |
| mini_mime                     | 1.0.2        |
| uber                          | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| google-api-client             | 0.38.0       |
| rexml                         | 3.2.4        |
| webrick                       | 1.7.0        |
| google-apis-core              | 0.2.1        |
| google-apis-iamcredentials_v1 | 0.1.0        |
| google-apis-storage_v1        | 0.1.0        |
| google-cloud-env              | 1.4.0        |
| google-cloud-errors           | 1.0.1        |
| google-cloud-core             | 1.5.0        |
| google-cloud-storage          | 1.30.0       |
| json                          | 2.5.1        |
| mini_magick                   | 4.11.0       |
| plist                         | 3.6.0        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| naturally                     | 2.2.1        |
| simctl                        | 1.6.8        |
| slack-notifier                | 2.3.2        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| word_wrap                     | 1.0.0        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| xcpretty-travis-formatter     | 1.0.1        |
| trainer                       | 0.9.1        |
| xctest_list                   | 1.2.1        |
| fastlane-plugin-test_center   | 3.15.2       |
| mini_portile2                 | 2.5.0        |
| racc                          | 1.5.2        |
| nokogiri                      | 1.11.1       |
| slather                       | 2.6.1        |
| xcresult                      | 0.2.1        |
| xcov                          | 1.7.5        |
</details>

*generated on:* **2021-02-08**
</details>

**Comment by rogerluan** [comment]
Hey @jsorge 👋 

Interesting report, but I couldn't reproduce it. In fact, in my production environment I've also been using a json file and it does have a trailing newline (my text editor adds a trailing newline at the end of the file upon saving as well). Do you have more context to your issue? Or maybe a sample project zip where we can reproduce this? 🙏
