### ISSUE TITLE
CI builds fail with SPACESHIP_SKIP_2FA_UPGRADE variable

### ISSUE THREAD

**Issue by dmitry-shibanov** [fastlane/fastlane#18161]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
We have faced with the issue passing 2fa for CI. We created `SPACESHIP_SKIP_2FA_UPGRADE` and other necessary environment variables in our pipelines to pass 2fa. We use flag added in this issue: https://github.com/fastlane/fastlane/issues/18098. This issue is random sometimes it passes successfully but sometimes it fails with the issue below. 
**Failed build:** https://github.visualstudio.com/virtual-environments/_build/results?buildId=98456&view=logs&j=80d86624-2c9a-5cad-9434-144b838e69fb&t=7f6ff0d4-adc5-5557-eba3-0604338bbbf7&l=2586

##### Command executed
In our pipeline we use tool `xcversion`. It uses fastlane 2.173.0 and tries authenticate with bypass 2fa.
**Used commands:**
- [xcversion install](https://github.com/actions/virtual-environments/blob/b45f42aa9ff8948d414f0cf14d9f4860ae0739de/images/macos/helpers/Xcode.Installer.psm1#L33)
- [xcversion list](https://github.com/actions/virtual-environments/blob/b45f42aa9ff8948d414f0cf14d9f4860ae0739de/images/macos/helpers/Xcode.Installer.psm1#L54)
##### Complete output when running fastlane, including the stack trace and command used

<details>
 
```
    vsphere-clone: Installing Xcode versions...
==> vsphere-clone: /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/client.rb:911:in `handle_401'
==> vsphere-clone: /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/client.rb:885:in `block in send_request'
==> vsphere-clone: /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/client.rb:643:in `with_retry'
==> vsphere-clone: /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/client.rb:879:in `send_request'
==> vsphere-clone: /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/client.rb:723:in `request'
==> vsphere-clone: /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/upgrade_2fa_later_client.rb:32:in `try_upgrade_2fa_later'
==> vsphere-clone: /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/client.rb:511:in `send_shared_login_request'
==> vsphere-clone: /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/portal/portal_client.rb:28:in `send_login_request'
==> vsphere-clone: /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/client.rb:805:in `do_login'
==> vsphere-clone: /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/client.rb:390:in `login'
==> vsphere-clone: /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/client.rb:352:in `login'
==> vsphere-clone: /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/portal/spaceship.rb:25:in `login'
==> vsphere-clone: /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/portal/spaceship.rb:103:in `login'
==> vsphere-clone: /usr/local/lib/ruby/gems/2.7.0/gems/xcode-install-2.6.8/lib/xcode/install.rb:350:in `spaceship'
==> vsphere-clone: /usr/local/lib/ruby/gems/2.7.0/gems/xcode-install-2.6.8/lib/xcode/install.rb:391:in `fetch_seedlist'
==> vsphere-clone: /usr/local/lib/ruby/gems/2.7.0/gems/xcode-install-2.6.8/lib/xcode/install.rb:210:in `seedlist'
==> vsphere-clone: /usr/local/lib/ruby/gems/2.7.0/gems/xcode-install-2.6.8/lib/xcode/install.rb:429:in `list_versions'
==> vsphere-clone: /usr/local/lib/ruby/gems/2.7.0/gems/xcode-install-2.6.8/lib/xcode/install.rb:320:in `list'
==> vsphere-clone: /usr/local/lib/ruby/gems/2.7.0/gems/xcode-install-2.6.8/lib/xcode/install/list.rb:13:in `run'
==> vsphere-clone: /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
==> vsphere-clone: /usr/local/lib/ruby/gems/2.7.0/gems/xcode-install-2.6.8/bin/xcversion:12:in `<top (required)>'
==> vsphere-clone: /usr/local/lib/ruby/gems/2.7.0/bin/xcversion:23:in `load'
==> vsphere-clone: /usr/local/lib/ruby/gems/2.7.0/bin/xcversion:23:in `<main>'
==> vsphere-clone: Failed to bypass 2FA upgrade
==> vsphere-clone: To disable this from trying again, set SPACESHIP_SKIP_UPGRADE_2FA_LATER=1

==> vsphere-clone: /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/client.rb:519:in `send_shared_login_request': Need to acknowledge to Apple's Apple ID and Privacy statement. Please manually log into https://appleid.apple.com (or https://appstoreconnect.apple.com) to acknowledge the statement. Your account might also be asked to upgrade to 2FA. Set SPACESHIP_SKIP_2FA_UPGRADE=1 for fastlane to automaticaly bypass 2FA upgrade if possible. (Spaceship::AppleIDAndPrivacyAcknowledgementNeeded)
==> vsphere-clone: 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/portal/portal_client.rb:28:in `send_login_request'
==> vsphere-clone: 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/client.rb:805:in `do_login'
==> vsphere-clone: 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/client.rb:390:in `login'
==> vsphere-clone: 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/client.rb:352:in `login'
==> vsphere-clone: 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/portal/spaceship.rb:25:in `login'
==> vsphere-clone: 	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.173.0/spaceship/lib/spaceship/portal/spaceship.rb:103:in `login'
==> vsphere-clone: 	from /usr/local/lib/ruby/gems/2.7.0/gems/xcode-install-2.6.8/lib/xcode/install.rb:350:in `spaceship'
==> vsphere-clone: 	from /usr/local/lib/ruby/gems/2.7.0/gems/xcode-install-2.6.8/lib/xcode/install.rb:391:in `fetch_seedlist'
==> vsphere-clone: 	from /usr/local/lib/ruby/gems/2.7.0/gems/xcode-install-2.6.8/lib/xcode/install.rb:210:in `seedlist'
==> vsphere-clone: 	from /usr/local/lib/ruby/gems/2.7.0/gems/xcode-install-2.6.8/lib/xcode/install.rb:429:in `list_versions'
==> vsphere-clone: 	from /usr/local/lib/ruby/gems/2.7.0/gems/xcode-install-2.6.8/lib/xcode/install.rb:320:in `list'
==> vsphere-clone: 	from /usr/local/lib/ruby/gems/2.7.0/gems/xcode-install-2.6.8/lib/xcode/install/list.rb:13:in `run'
==> vsphere-clone: 	from /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
==> vsphere-clone: 	from /usr/local/lib/ruby/gems/2.7.0/gems/xcode-install-2.6.8/bin/xcversion:12:in `<top (required)>'
==> vsphere-clone: 	from /usr/local/lib/ruby/gems/2.7.0/bin/xcversion:23:in `load'
==> vsphere-clone: 	from /usr/local/lib/ruby/gems/2.7.0/bin/xcversion:23:in `<main>'
==> vsphere-clone: Exception: /Users/runner/image-generation/helpers/Xcode.Installer.psm1:28
==> vsphere-clone: Line |
==> vsphere-clone:   28 |          throw "Version '$Version' can't be matched to any available v …
==> vsphere-clone:      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> vsphere-clone:      | Version '10.3' can't be matched to any available version
==> vsphere-clone: 
==> vsphere-clone: Script exited with non-zero exit status: 1.Allowed exit codes are: [0]
```
</details>

### Environment

<details>
  
[12:38:54]: Learn more at https://docs.fastlane.tools/#metrics
[12:38:54]: No personal or sensitive data is sent.
[12:38:54]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
[12:38:54]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.15.7                                          |
| Ruby                        | 2.7.2                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.30.0                               |
| Installation Source         | /usr/local/lib/ruby/gems/2.7.0/bin/fastlane      |
| Host                        | Mac OS X 10.15.7 (19H512)                        |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.7/2.7.2/lib             |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                       |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode_12.3.app/Contents/Developer/ |
| Xcode Version               | 12.3                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.173.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.4.0        |
| slack-notifier                | 2.3.2        |
| atomos                        | 0.1.3        |
| CFPropertyList                | 3.0.3        |
| claide                        | 1.0.3        |
| colored2                      | 3.1.2        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| terminal-notifier             | 2.0.0        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| multipart-post                | 2.0.0        |
| word_wrap                     | 1.0.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| artifactory                   | 3.0.15       |
| babosa                        | 1.0.4        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| excon                         | 0.79.0       |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.2        |
| gh_inspector                  | 1.1.3        |
| mini_magick                   | 4.11.0       |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| xcpretty-travis-formatter     | 1.0.1        |
| dotenv                        | 2.7.6        |
| bundler                       | 2.2.8        |
| naturally                     | 2.2.1        |
| simctl                        | 1.6.8        |
| jwt                           | 2.2.2        |
| uber                          | 0.1.0        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| mini_mime                     | 1.0.2        |
| multi_json                    | 1.15.0       |
| signet                        | 0.14.1       |
| memoist                       | 0.16.2       |
| os                            | 1.1.1        |
| googleauth                    | 0.15.0       |
| httpclient                    | 2.8.3        |
| google-api-client             | 0.38.0       |
| google-cloud-env              | 1.4.0        |
| google-cloud-errors           | 1.0.1        |
| google-cloud-core             | 1.5.0        |
| rexml                         | 3.2.3        |
| webrick                       | 1.6.0        |
| google-apis-core              | 0.2.1        |
| google-apis-iamcredentials_v1 | 0.1.0        |
| google-apis-storage_v1        | 0.1.0        |
| rake                          | 13.0.1       |
| digest-crc                    | 0.6.3        |
| google-cloud-storage          | 1.30.0       |
| emoji_regex                   | 3.2.1        |
| jmespath                      | 1.4.0        |
| aws-partitions                | 1.424.0      |
| aws-eventstream               | 1.1.0        |
| aws-sigv4                     | 1.2.2        |
| aws-sdk-core                  | 3.112.0      |
| aws-sdk-kms                   | 1.42.0       |
| aws-sdk-s3                    | 1.88.0       |
| uri                           | 0.10.0       |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| plist                         | 3.6.0        |
| ruby2_keywords                | 0.0.4        |
| faraday-net_http              | 1.0.1        |
| faraday                       | 1.3.0        |
| json                          | 2.3.0        |
| forwardable                   | 1.3.1        |
| logger                        | 1.4.2        |
| cgi                           | 0.1.0        |
| date                          | 3.0.0        |
| timeout                       | 0.1.0        |
| stringio                      | 0.1.0        |
| zlib                          | 1.1.0        |
| ipaddr                        | 1.2.2        |
| openssl                       | 2.1.2        |
| ostruct                       | 0.2.0        |
| strscan                       | 1.0.3        |
| delegate                      | 0.1.0        |
| fileutils                     | 1.4.1        |
| open3                         | 0.1.0        |
| singleton                     | 0.1.0        |
| mini_portile2                 | 2.1.0        |
| nokogiri                      | 1.6.8.1      |
| racc                          | 1.4.16       |
| yaml                          | 0.1.0        |
| psych                         | 3.1.0        |
| mutex_m                       | 0.1.0        |
</details>

*generated on:* **2021-02-09**
</details>
[12:38:54]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[12:38:54]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅

</details>

**Comment by dmitry-shibanov** [comment]
Could you please take a look on it ?
cc: @joshdholtz

**Comment by A-Tokyo** [comment]
Try adding the env var to the Fastfile, maybe the CI is not picking it up for some reason

eg:
```
# iOS only @tempfix for Getting error "Need to acknowledge to Apple's Apple ID and Privacy statement." https://stackoverflow.com/questions/66024297/getting-error-need-to-acknowledge-to-apples-apple-id-and-privacy-statement
ENV['SPACESHIP_SKIP_2FA_UPGRADE']="1"
```

**Comment by joshdholtz** [comment]
So seeing `Failed to bypass 2FA upgrade` does look like it attempted the bypass but failed in one of the 5ish requests that the bypass does to get it to work 😔 

Have you tried to run this locally on your machine at all? I'm curious if there is some firewall thingy or something that azure has that is causing the bypass to fail 🤔

**Comment by dmitry-shibanov** [comment]
Hello @joshdholtz , thank you for your response. As far as we know, we don’t have a firewall on macOS machines (we run build on self-hosted machines, they are outside Azure).
Also we see that this flag can work and doesn’t work on the same machine in the same build (previous Xcode is installed successfully, next one will fail). Sometimes we see that Xcode is installed successfully but this logic looks unreliable.
**For example:** https://github.visualstudio.com/virtual-environments/_build/results?buildId=98564&view=logs&j=80d86624-2c9a-5cad-9434-144b838e69fb&t=7f6ff0d4-adc5-5557-eba3-0604338bbbf7&l=3498
On my local machine it works well. 

May be we could add some retry logic during resolving this modal window or any additional checks could be help?

**Comment by joshdholtz** [comment]
@dmitry-shibanov Would you be able to try a weird thing for me? 😇 

Can you try deleting the existing spaceship session before you run your _fastlane_ stuff?

`rm -rf ~/.fastlane/spaceship/<your@email.com>`

I have no idea why this would help but 🤷‍♂️  Knowing _if_ this solves it for you would help me debug a little more on my end 🙏

**Comment by AlexTheLost** [comment]
@joshdholtz Hi, this problem also was discussing in prev topic about authentication problem, my comment: https://github.com/fastlane/fastlane/issues/18098#issuecomment-774108424. 
In https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/client.rb#L896 script detect 403 HTTP status and after it throw exception in 889 line. 
I found that problem happen on some ip set, example on AWS, on myself PC script work without this problem.

**Comment by dmitry-shibanov** [comment]
Hello @joshdholtz. Thank you for help. I cleaned `~/.fastlane/spaceship/` before each fastlane stuff, but it failed.
Build: https://github.visualstudio.com/virtual-environments/_build/results?buildId=98621&view=logs&j=80d86624-2c9a-5cad-9434-144b838e69fb&t=7f6ff0d4-adc5-5557-eba3-0604338bbbf7&l=4774

**Comment by joshdholtz** [comment]
> @joshdholtz Hi, this problem also was discussing in prev topic about authentication problem, my comment: https://github.com/fastlane/fastlane/issues/18098#issuecomment-774108424. 
> 
> In https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/client.rb#L896 script detect 403 HTTP status and after it throw exception in 889 line. 
> 
> I found that problem happen on some ip set, example on AWS, on myself PC script work without this problem. Perhaps Apple blocking requests from some ip's.

@AlexTheLost Ughhhh... this was kind of my fear 😔 

I'm not exactly sure how to solve or how much time to put into solving since 2FA will _probably_ be fully required here soon 😬

**Comment by maxim-lobanov** [comment]
I am not sure that it is IP related because we run `xcversion` a few times on the same machine in row. Some requests fail, some pass. Obviously, machine has the same IP between requests.
I wonder if small delays between requests could help: https://github.com/fastlane/fastlane/pull/18116/files#diff-5e20dec12daa93019cabbf31b209b09c81265e9057545416201fe8c3e05df453R31
Or may be some retry logic will help?

**Comment by joshdholtz** [comment]
> I am not sure that it is IP related because we run `xcversion` a few times on the same machine in row. Some requests fail, some pass. Obviously, machine has the same IP between requests.
> 
> I wonder if small delays between requests could help: https://github.com/fastlane/fastlane/pull/18116/files#diff-5e20dec12daa93019cabbf31b209b09c81265e9057545416201fe8c3e05df453R31
> 
> Or may be some retry logic will help?

@maxim-lobanov How quick do these run in a row? I'm now wondering if they are maybe rate limiting it? 🤔 

I have no idea. I'm super stumped here so just trying to think of anything I can.

**Comment by maxim-lobanov** [comment]
@joshdholtz , I don't think that it is rate limit. Installation of one Xcode takes about 10 minutes. So we have 1 auth request, then 10 minutes timeout, then 1 more auth request
