### ISSUE TITLE
Just build without archive

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1816]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/675176?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @mr-casual - Imported from <a href='https://github.com/fastlane/gym/issues/230'>fastlane/gym#230</a>
        </td>
      </tr>
    </table>

Can I just build the project without archive and export ?

I want something like this:
`xcodebuild build -workspace 'MyApp.xcworkspace' -scheme 'MyApp' -destination 'generic/platform=iOS' | tee /Users/me/Library/Logs/gym/MyApp-MyApp.log | xcpretty`

**Comment by gavinbunney** [comment]
The `xcodebuild` action does support the `CODE_SIGNING_REQUIRED` and other build settings through the `build_settings` parameter.... this will at least clean up your script a little bit:

```
lane :build do |options|
  xcodebuild(
    workspace: "MyApp.xcworkspace",
    scheme: "MyApp",
    configuration: "Debug",
    clean: options[:clean],
    build: true,
    destination: "generic/platform=iOS",
    build_settings: {
      "CODE_SIGNING_REQUIRED" => "NO",
      "CODE_SIGN_IDENTITY" => ""
    }
  )
end
```

**Comment by jshier** [comment]
We use `gym` to build optimized IPAs for Crashlytics upload, and have an issue with archives consuming all of the disk space on the Jenkins bots. Is there really no setting to prevent archiving altogether? I can see why `gym` offers it as a features, but why not make it configurable, as this option doesn't play well with CI setups.

**Comment by KrauseFx** [comment]
@jshier Yah, feel free to write your own clean up

**Comment by mr-casual** [comment]
@gavinbunney thanks ;)

**Comment by vpolouchkine** [comment]
Looks like this is more or less resolved.

**Comment by jshier** [comment]
Not really, unless you find one of the various workarounds acceptable. I really don't but I need to write one anyway. I still don't understand why making archiving an option is unacceptable here?

**Comment by jshier** [comment]
Just FYI, created this function to cleanup the archive:
```ruby
def cleanup_archive
  sh "rm -r \"#{lane_context[SharedValues::XCODEBUILD_ARCHIVE]}\""
end
```

**Comment by KrauseFx** [comment]
If you read the description of `gym`, it's designed to build and sign ipa files. Thanks for sharing your script

**Comment by revolter** [comment]
There is a `skip_archive` parameter now that does exactly this.
