### ISSUE TITLE
Publish screengrab to maven central

### ISSUE THREAD

**Issue by pocmo** [fastlane/fastlane#18174]
JCenter will go away eventually:
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

It seems like screengrab (`tools.fastlane:screengrab`) is currently only available via JCenter (bintray). Would it be possible to publish it to Maven Central?

Falcon (`com.jraska:falcon`), which screengrab depends on, is affected too. This seems to be tracked here:
https://github.com/jraska/Falcon/issues/52

**Comment by penn5** [comment]
This is a duplicate of #12651

**Comment by pocmo** [comment]
Oh, sorry, I searched for an issue but was somehow unable to find it. I'll close this here then.

**Comment by penn5** [comment]
@joshdholtz could you please double check why #12651 is locked? Is there a plan to fix this? The AGP now warns if you are using jcenter repositories. I could resolve this by adding it to #18003 perhaps?

**Comment by joshdholtz** [comment]
It's the bots fault 😩 I'll be working on getting it published to maven soon!

**Comment by penn5** [comment]
Bad bot

**Comment by joshdholtz** [comment]
Update on this but it's published 😊
