### ISSUE TITLE
[Feature]Add a parameter reporter 

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1817]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/10742352?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @ebaujard - Imported from <a href='https://github.com/fastlane/gym/issues/229'>fastlane/gym#229</a>
        </td>
      </tr>
    </table>

With a parameter  "reporter" we could generate a json-compilation-database, and use this file with action oclint.

Ex in build_command_generator.rb:
 pipe << "| tee #{xcodebuild_log_path.shellescape} | xcpretty --report  #{reporter}"

**Comment by lubbo** [comment]
Is anyone currently working on that?

**Comment by ohwutup** [comment]
I'm going to close this issue for now as it has been quite a while since there was any activity here. Let us know if there is still some discussion we should have around this!
