### ISSUE TITLE
Add the ability to remove xcarchive file on completion of ipa export

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1818]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/3300301?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @RobDay - Imported from <a href='https://github.com/fastlane/gym/issues/228'>fastlane/gym#228</a>
        </td>
      </tr>
    </table>

It would be pretty cool if Gym had the ability to clean up xcarchives after the ipa is generated.  This should definitely not be a default behavior, but it would be a useful feature when considering CI. Our CI server kicks off a large amount of builds and it's currently a manual task to clean up all archives we want deleted (we keep our app store flavors but purge our CI flavors).  

Does removing xcarchives sound valuable? Is it something that should live in Gym or perhaps as a build action?

**Comment by pedro380085** [comment]
Hi @RobDay, did you implement this action? Thanks,

**Comment by RobDay** [comment]
I have not, yet.  I didn't gauge any interest from other people and deferred working on it.  Is it something in which you see value?

**Comment by pedro380085** [comment]
@RobDay I ended up putting the export folder at /temp and then deleting it at the end.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (431/400 (107%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:48543 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKrh-002l3G-Eg
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:21:11 +0200
Date: Sat, 18 Jun 2016 11:20:24 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466274024;
	bh=c2OPET+yzoiKwxidZfTDQoCyAKjt9vF4Sun4gvxN2j4=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=wXkkZCuMtNjeWRWzLzKlNZVYeaEYpZQ3Vw65wRHcjo9S1zQVOxvoHFezCE83eQxpf
	 nmOnzmDDsu8rnaSwwMA87TanfnLk5WSuryzrOuX+e5ee0pWoziE5l5BbZvAh+4I+0G
	 hzsmjaGu5D9q8U0U4V7nI9lpJvlG4oj65il2V+1I=

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (430/400 (107%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:48488 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKrh-002l38-73
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:21:09 +0200
Date: Sat, 18 Jun 2016 11:20:23 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466274024;
	bh=sQ/kJeFjmBcngG0v1N9fbHJoxuFAKB22PCXpTVE12gc=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=JmKjierLgua5mcikoxRtBI7/EiofyFe+Lr+6JI6CViStScoCK8aZwGWopcY0c+5pW
	 d5SFwB3+KoorcCpTLsAu+v98s37kbAjR2njSun5BZvM2WaWIMSRQqaa8jlUb1CnUH0
	 nFtuna4M5YFPZGenG+oOsdOZ6wtLjJPaWEdZ+m6o=
