### ISSUE TITLE
Unable to locate Xcode. Please make sure to have Xcode installed on your machine.

### ISSUE THREAD

**Issue by alexclifford** [fastlane/fastlane#18180]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Running fastlane after updating macOS to Big Sur and it can no longer find xcode.

##### Command executed
```
bundle exec fastlane beta
bundle exec fastlane match
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
⇒  bundle exec fastlane beta
[✔] 🚀
+-------------------------------------------+---------+---------------------------+
|                                  Used plugins                                   |
+-------------------------------------------+---------+---------------------------+
| Plugin                                    | Version | Action                    |
+-------------------------------------------+---------+---------------------------+
| fastlane-plugin-firebase_app_distribution | 0.1.4   | firebase_app_distribution |
+-------------------------------------------+---------+---------------------------+

[07:55:16]: ----------------------------------------
[07:55:16]: --- Step: Verifying fastlane version ---
[07:55:16]: ----------------------------------------
[07:55:16]: Your fastlane version 2.174.0 matches the minimum requirement of 2.141.0  ✅
[07:55:16]: ------------------------------
[07:55:16]: --- Step: default_platform ---
[07:55:16]: ------------------------------
[07:55:16]: Driving the lane 'beta' 🚀
[07:55:16]: -----------------------------
[07:55:16]: --- Step: setup_circle_ci ---
[07:55:16]: -----------------------------
[07:55:16]: Not running on CI, skipping CI setup
[07:55:16]: You passed invalid parameters to 'match'.
[07:55:16]: Check out the error below and available options by running `fastlane action match`
+------------------+------+
|      Lane Context       |
+------------------+------+
| DEFAULT_PLATFORM | ios  |
| PLATFORM_NAME    |      |
| LANE_NAME        | beta |
+------------------+------+
[07:55:16]: Unable to locate Xcode. Please make sure to have Xcode installed on your machine

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 3    | setup_circle_ci            | 0           |
+------+----------------------------+-------------+

[07:55:16]: fastlane finished with errors

[!] Unable to locate Xcode. Please make sure to have Xcode installed on your machine

⇒  bundle exec fastlane match
[✔] 🚀
bundler: failed to load command: fastlane (/Users/alex/git/github/foo/bar/vendor/bundle/ruby/2.7.0/bin/fastlane)
FastlaneCore::Interface::FastlaneError: Unable to locate Xcode. Please make sure to have Xcode installed on your machine
  /Users/alex/git/github/foo/bar/vendor/bundle/ruby/2.7.0/gems/fastlane-2.174.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'
  /Users/alex/git/github/foo/bar/vendor/bundle/ruby/2.7.0/gems/fastlane-2.174.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /Users/alex/git/github/foo/bar/vendor/bundle/ruby/2.7.0/gems/fastlane-2.174.0/fastlane_core/lib/fastlane_core/helper.rb:172:in `xcode_at_least?'
  /Users/alex/git/github/foo/bar/vendor/bundle/ruby/2.7.0/gems/fastlane-2.174.0/match/lib/match/options.rb:57:in `available_options'
  /Users/alex/git/github/foo/bar/vendor/bundle/ruby/2.7.0/gems/fastlane-2.174.0/match/lib/match/commands_generator.rb:44:in `block in run'
  /Users/alex/git/github/foo/bar/vendor/bundle/ruby/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:173:in `command'
  /Users/alex/git/github/foo/bar/vendor/bundle/ruby/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `command'
  /Users/alex/git/github/foo/bar/vendor/bundle/ruby/2.7.0/gems/fastlane-2.174.0/match/lib/match/commands_generator.rb:40:in `run'
  /Users/alex/git/github/foo/bar/vendor/bundle/ruby/2.7.0/gems/fastlane-2.174.0/match/lib/match/commands_generator.rb:25:in `start'
  /Users/alex/git/github/foo/bar/vendor/bundle/ruby/2.7.0/gems/fastlane-2.174.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
  /Users/alex/git/github/foo/bar/vendor/bundle/ruby/2.7.0/gems/fastlane-2.174.0/bin/fastlane:23:in `<top (required)>'
  /Users/alex/git/github/foo/bar/vendor/bundle/ruby/2.7.0/bin/fastlane:23:in `load'
  /Users/alex/git/github/foo/bar/vendor/bundle/ruby/2.7.0/bin/fastlane:23:in `<top (required)>'
</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                |
| --------------------------- | ------------------------------------ |
| OS                          | 11.2                                 |
| Ruby                        | 2.7.2                                |
| Bundler?                    | false                                |
| Git                         | git version 2.29.2                   |
| Installation Source         | /usr/local/bin/fastlane              |
| Host                        | macOS 11.2 (20D64)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.7/2.7.2/lib |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020           |
| Is contained                | false                                |
| Is homebrew                 | false                                |
| Is installed via Fabric.app | false                                |
| Xcode Path                  | /Library/Developer/CommandLineTools/ |
| Xcode Version               |                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.141.0"

default_platform :ios

before_all do
  setup_circle_ci
end

lane :beta do
  match
  build_app
  changelog_from_git_commits(merge_commit_filtering: "exclude_merges")
  firebase_app_distribution
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier "[[APP_IDENTIFIER]]" # The bundle identifier of your app
# apple_id "[[APPLE_ID]]" # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.174.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.2.5   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.4.0        |
| slack-notifier                            | 2.3.2        |
| atomos                                    | 0.1.3        |
| CFPropertyList                            | 3.0.3        |
| claide                                    | 1.0.3        |
| colored2                                  | 3.1.2        |
| nanaimo                                   | 0.3.0        |
| xcodeproj                                 | 1.19.0       |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.7.0        |
| terminal-table                            | 1.8.0        |
| plist                                     | 3.6.0        |
| public_suffix                             | 4.0.6        |
| addressable                               | 2.7.0        |
| multipart-post                            | 2.0.0        |
| word_wrap                                 | 1.0.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| artifactory                               | 3.0.15       |
| babosa                                    | 1.0.4        |
| colored                                   | 1.2          |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| excon                                     | 0.79.0       |
| faraday-net_http                          | 1.0.1        |
| ruby2_keywords                            | 0.0.4        |
| faraday                                   | 1.3.0        |
| unf_ext                                   | 0.0.7.7      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.0.0        |
| fastimage                                 | 2.2.2        |
| gh_inspector                              | 1.1.3        |
| json                                      | 2.3.0        |
| mini_magick                               | 4.11.0       |
| rubyzip                                   | 2.3.0        |
| security                                  | 0.1.3        |
| xcpretty-travis-formatter                 | 1.0.1        |
| dotenv                                    | 2.7.6        |
| bundler                                   | 2.1.4        |
| naturally                                 | 2.2.1        |
| simctl                                    | 1.6.8        |
| jwt                                       | 2.2.2        |
| uber                                      | 0.1.0        |
| declarative                               | 0.0.20       |
| declarative-option                        | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| mini_mime                                 | 1.0.2        |
| multi_json                                | 1.15.0       |
| signet                                    | 0.14.1       |
| memoist                                   | 0.16.2       |
| os                                        | 1.1.1        |
| googleauth                                | 0.15.1       |
| httpclient                                | 2.8.3        |
| google-api-client                         | 0.38.0       |
| google-cloud-env                          | 1.4.0        |
| google-cloud-errors                       | 1.0.1        |
| google-cloud-core                         | 1.5.0        |
| rexml                                     | 3.2.3        |
| webrick                                   | 1.6.0        |
| google-apis-core                          | 0.2.1        |
| google-apis-iamcredentials_v1             | 0.1.0        |
| google-apis-storage_v1                    | 0.2.0        |
| rake                                      | 13.0.1       |
| digest-crc                                | 0.6.3        |
| google-cloud-storage                      | 1.30.0       |
| emoji_regex                               | 3.2.1        |
| jmespath                                  | 1.4.0        |
| aws-partitions                            | 1.426.0      |
| aws-eventstream                           | 1.1.0        |
| aws-sigv4                                 | 1.2.2        |
| aws-sdk-core                              | 3.112.0      |
| aws-sdk-kms                               | 1.42.0       |
| aws-sdk-s3                                | 1.88.0       |
| uri                                       | 0.10.0       |
| forwardable                               | 1.3.1        |
| logger                                    | 1.4.2        |
| cgi                                       | 0.1.0        |
| date                                      | 3.0.0        |
| timeout                                   | 0.1.0        |
| stringio                                  | 0.1.0        |
| zlib                                      | 1.1.0        |
| ipaddr                                    | 1.2.2        |
| openssl                                   | 2.1.2        |
| ostruct                                   | 0.2.0        |
| strscan                                   | 1.0.3        |
| delegate                                  | 0.1.0        |
| fileutils                                 | 1.4.1        |
| io-console                                | 0.5.6        |
| open3                                     | 0.1.0        |
| singleton                                 | 0.1.0        |
| yaml                                      | 0.1.0        |
| psych                                     | 3.1.0        |
| mutex_m                                   | 0.1.0        |
| etc                                       | 1.1.0        |
| fastlane-plugin-firebase_app_distribution | 0.2.5        |
| pstore                                    | 0.1.0        |
</details>

*generated on:* **2021-02-11**
</details>

**Comment by Dinsen** [comment]
Hi @alexclifford 
Could this fix your issue?
https://stackoverflow.com/questions/50404109/unable-to-locate-xcode-please-make-sure-to-have-xcode-installed-on-your-machine

**Comment by alexclifford** [comment]
Unfortunately not, I had come across this particular stackoverflow question earlier. I have never used the full Xcode suite on this particular Mac for building with fastlane, just the CLI tools. As shown in the env output my CLI is configured to the default location for when you installed them with `xcode-select --install`. Usually this is fine but since the macOS upgrade fastlane doesn't think they are installed anymore.

I tried removing them and re-installing, and also changing the path and back to where they are installed.

**Comment by wibbly13** [comment]
@alexclifford Have you tried [this](https://docs.fastlane.tools/actions/xcode_select/)?
