### ISSUE TITLE
"bundle update fastlane" is not updating to latest build

### ISSUE THREAD

**Issue by ibrahimyolbir** [fastlane/fastlane#18191]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

**`fastlane action app_store_connect_api_key`**

> [!] Action 'app_store_connect_api_key' not available, run `fastlane actions` to get a full list

### Issue Description
i want to install **app_store_connect_api_key**. But because of iam using 2.152.0 version of Fastlane . I cant install and then i try to update fastlane to latest version but i cant see any version change when iam trying to use following commands

- **`$ bundle update fastlane`**
- **`$ sudo bundle update fastlane`**
- **`$ sudo bundle update`**
- **`$ sudo fastlane update`**

- Deleted gemfile.lock file and try to use **$ bundle install**
- **`$ gem list`
`$ gem check`
`$ gem cleanup`**

 
<img width="1120" alt="Screenshot 2021-02-12 at 11 08 13" src="https://user-images.githubusercontent.com/25623304/107755234-d5e80380-6d22-11eb-9aed-fc5b0efa46fc.png">

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.2                                        |
| Ruby                        | 2.7.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.rvm/gems/ruby-2.7.1/bin/fastlane         |
| Host                        | macOS 11.2 (20D64)                          |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.7.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.4                                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_require 'dotenv'
fastlane_require 'spaceship'

platform :ios do

  desc 'Push a new build to TestFlight'
  lane :beta do

before_all do
    ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"]
    ENV["SPACESHIP_SKIP_2FA_UPGRADE"]
  end
    cocoapods(
      podfile: 'ios/Podfile'
    )

    # To make sure the build numbers never collide, fetch current
    # build number from testflight for this version
    api_key = app_store_connect_api_key(
      key_id: "********",
      issuer_id: "********,
      key_filepath: '../../../../********.p8',
    )
    update_app_identifier(
      xcodeproj: 'ios/DGFonder.xcodeproj',
      plist_path:'../ios/DGFonder/Info.plist', 
      app_identifier: ENV['APP_IDENTIFIER']
    )
    
    version = get_info_plist_value(
      path:'ios/DGFonder/Info.plist', 
      key: 'CFBundleShortVersionString'
    )

    current_build_number = latest_testflight_build_number(
      app_identifier: ENV['APP_IDENTIFIER'],
      username: ENV['TESTFLIGHT_USERNAME'],
      team_id: ENV['FASTLANE_ITC_TEAM_ID'],
      version: version
    )
    increment_build_number(
      xcodeproj: 'ios/DGFonder.xcodeproj',
      build_number: current_build_number + 1
    )
    if ENV['BADGE_COLOR'] != 'none' then 
      badge_name = ENV['ENVIRONMENT_NAME'][0..3].capitalize
      add_badge(
        shield: '' + version + '-' + badge_name + '-' + ENV['BADGE_COLOR'], 
        no_badge: true
      )
    end


    update_project_team(
      path: 'ios/DGFonder.xcodeproj',
      teamid: ENV['DEVELOPMENT_TEAM']
    )

    sh('cd .. && ./scripts/patchInstall.sh')
    
    build_ios_app(
      workspace: 'ios/DGFonder.xcworkspace',
      scheme: 'DGFonder',
      configuration: ENV['CONFIGURATION'],
      silent: false,
      xcargs: "APP_IDENTIFIER='" + ENV['APP_IDENTIFIER'] + "' CODEPUSH_KEY='" + ENV['CODEPUSH_KEY'] + "' -allowProvisioningUpdates -allowProvisioningDeviceRegistration"
    )
 
    upload_to_testflight(
      username: ENV['TESTFLIGHT_USERNAME'],
      skip_waiting_for_build_processing: true
    )
  end
end


platform :android do
  desc 'Submit a new Beta Build to Crashlytics Beta'
  lane :beta do
    
       
    badge_name = ENV['ENVIRONMENT_NAME'][0..3].capitalize
    add_badge(
      glob: "/android/app/src/main/res/mipmap-*/ic_launcher_foreground.{png,PNG}",
      shield: '3.1' + '-' + badge_name + '-' + ENV['BADGE_COLOR'], 
      shield_scale: "0.55",
      shield_gravity: 'Center',
      no_badge: true
     )



    gradle(
      project_dir: 'android',
      task: 'clean ' + ENV['GRADLE_BUILD_TASK'],
      properties: {
        "sign.didner.android.keystore" => ".keystore",
        "sign.didner.android.storepass" => "********",
        "sign.didner.android.alias" => "********",
        "sign.didner.android.keypass" => "********"

      }
    )
          firebase_app_distribution(
              app: ENV['FIREBASE_APP_ID_ANDROID'],
              testers: "********",
              release_notes: "",
              firebase_cli_path: "/usr/local/bin/firebase"
          )
  end

  lane :tag do
    version_tag = "android/" + android_get_version_name(
      gradle_file: "android/app/build.gradle" 
    )
    if !git_tag_exists(tag: version_tag)
      add_git_tag(
        tag: version_tag
      )
      push_git_tags()
    else 
      raise "Git tag " + version_tag + " already exists"
    end
  end

  lane :playstore do

    gradle(
      project_dir: 'android',
      task: 'clean ' + ENV['GRADLE_BUILD_TASK'],
      properties: {
        "sign.didner.android.keystore" => ".keystore",
        "sign.didner.android.storepass" => "********",
        "sign.didner.android.alias" => "********",
        "sign.didner.android.keypass" => "********"
      }
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# Android parameters
json_key_file("supply_key.json") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("********") # e.g. ********

# iOS parameters
# apple_id("********") # Your Apple email address

itc_team_id("********") # App Store Connect Team ID
team_id("********") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.152.0 | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status      |
| ----------------------------------------- | ------- | ------------------ |
| fastlane-plugin-badge                     | 1.1.0   | 🚫 Update available |
| fastlane-plugin-versioning_android        | 0.1.0   | ✅ Up-To-Date       |
| fastlane-plugin-android_sdk_update        | 1.0.1   | ✅ Up-To-Date       |
| fastlane-plugin-firebase_app_distribution | 0.2.5   | ✅ Up-To-Date       |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.4.0        |
| executable-hooks                          | 1.6.0        |
| bundler-unload                            | 1.0.2        |
| rubygems-bundler                          | 1.4.5        |
| bundler                                   | 2.1.4        |
| rake                                      | 13.0.3       |
| CFPropertyList                            | 3.0.3        |
| concurrent-ruby                           | 1.1.8        |
| i18n                                      | 1.8.8        |
| minitest                                  | 5.14.3       |
| thread_safe                               | 0.3.6        |
| tzinfo                                    | 1.2.9        |
| activesupport                             | 5.2.4.5      |
| public_suffix                             | 4.0.6        |
| addressable                               | 2.7.0        |
| httpclient                                | 2.8.3        |
| json                                      | 2.5.1        |
| algoliasearch                             | 1.27.5       |
| atomos                                    | 0.1.3        |
| aws-eventstream                           | 1.1.0        |
| aws-partitions                            | 1.426.0      |
| aws-sigv4                                 | 1.2.2        |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.112.0      |
| aws-sdk-kms                               | 1.42.0       |
| aws-sdk-s3                                | 1.88.0       |
| babosa                                    | 1.0.4        |
| curb                                      | 0.9.11       |
| fastimage                                 | 2.2.2        |
| colored                                   | 1.2          |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| dotenv                                    | 2.7.6        |
| emoji_regex                               | 3.2.1        |
| excon                                     | 0.79.0       |
| multipart-post                            | 2.0.0        |
| faraday                                   | 0.17.4       |
| unf_ext                                   | 0.0.7.7      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 0.14.0       |
| gh_inspector                              | 1.1.3        |
| jwt                                       | 2.2.2        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.1        |
| signet                                    | 0.14.1       |
| googleauth                                | 0.15.1       |
| mini_mime                                 | 1.0.2        |
| declarative                               | 0.0.20       |
| declarative-option                        | 0.1.0        |
| uber                                      | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| google-api-client                         | 0.38.0       |
| digest-crc                                | 0.6.3        |
| rexml                                     | 3.2.4        |
| webrick                                   | 1.7.0        |
| google-apis-core                          | 0.2.1        |
| google-apis-iamcredentials_v1             | 0.1.0        |
| google-apis-storage_v1                    | 0.2.0        |
| google-cloud-env                          | 1.4.0        |
| google-cloud-errors                       | 1.0.1        |
| google-cloud-core                         | 1.5.0        |
| google-cloud-storage                      | 1.30.0       |
| mini_magick                               | 4.11.0       |
| plist                                     | 3.6.0        |
| rubyzip                                   | 2.3.0        |
| security                                  | 0.1.3        |
| naturally                                 | 2.2.1        |
| simctl                                    | 1.6.8        |
| slack-notifier                            | 2.3.2        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.7.0        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| word_wrap                                 | 1.0.0        |
| claide                                    | 1.0.3        |
| colored2                                  | 3.1.2        |
| nanaimo                                   | 0.3.0        |
| xcodeproj                                 | 1.19.0       |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.1        |
| badge                                     | 0.9.1        |
| fuzzy_match                               | 2.0.4        |
| nap                                       | 1.1.0        |
| netrc                                     | 0.11.0       |
| ffi                                       | 1.14.2       |
| ethon                                     | 0.12.0       |
| typhoeus                                  | 1.4.0        |
| cocoapods-core                            | 1.10.1       |
| cocoapods-deintegrate                     | 1.0.4        |
| cocoapods-downloader                      | 1.4.0        |
| cocoapods-plugins                         | 1.0.0        |
| cocoapods-search                          | 1.0.0        |
| cocoapods-trunk                           | 1.5.0        |
| cocoapods-try                             | 1.2.0        |
| escape                                    | 0.0.4        |
| fourflusher                               | 2.3.1        |
| molinillo                                 | 0.6.6        |
| ruby-macho                                | 1.4.0        |
| cocoapods                                 | 1.10.1       |
| fastlane-plugin-brew                      | 0.1.1        |
| java-properties                           | 0.2.1        |
| fastlane-plugin-android_sdk_update        | 1.0.1        |
| fastlane-plugin-badge                     | 1.1.0        |
| fastlane-plugin-firebase_app_distribution | 0.2.5        |
| fastlane-plugin-versioning_android        | 0.1.0        |
</details>

*generated on:* **2021-02-12**</details>

**Comment by EmDee** [comment]
Do you have a version fix in your `Gemfile`? Can you post the content of your `Gemfile`? Also what is your output when you run `bundle update fastlane`?

**Comment by ibrahimyolbir** [comment]
Thank you for your answer @EmDee i found the problem. I forget to change` gem "fastlane", "~> 2.174.0"` for the version update. so my problem resolved.

 frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "fastlane", "~> 2.174.0"

gem "dotenv", "~> 2.5"

gem "cocoapods", "~> 1.5"

gem 'rake', '~> 13.0', '>= 13.0.1'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)

gem "badge", "~> 0.9.1"
