### ISSUE TITLE
[spaceship] 403 error clash with Portal and ConnectAPI

### ISSUE THREAD

**Issue by Dinsen** [fastlane/fastlane#18193]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When calling `Spaceship::ConnectAPI::App.find("dk.dinsen.secret.app")` using the API Key on an account that have license agreements waiting to be accepted.
I get this error: `undefined method 'status' for nil:NilClass`

I dived into the code and found that with `Spaceship::Portal` the error code 403 is handled here:
https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/client.rb#L896-L899

But because of this line: `raise AccessForbiddenError.new, msg` it goes into a loop where it makes 5x5 retries.
And after that it throw this error: `undefined method 'status' for nil:NilClass`

If I comment out this line `raise AccessForbiddenError.new, msg` then I'm able to add this into the `APIClient.handle_erros` and catch the error I'm looking for:
```ruby
if response.body['errors'].first['code'].eql?("FORBIDDEN.REQUIRED_AGREEMENTS_MISSING_OR_EXPIRED")
  raise ProgramLicenseAgreementUpdated, handle_errors(response) if response && (response.body || {})['errors']
else
  raise AccessForbiddenError, handle_errors(response) if response && (response.body || {})['errors']
end
```

I have not been able to catch the 403 using `Spaceship::Portal` since the Developer Portal is showing the `AppleIDAndPrivacyAcknowledgementNeeded` when trying to login.
So I'm not able to find a solution where we can handle this 403 status for both `Portal` and `ConnectAPI`

**Comment by max-ott** [comment]
I guess you are using an Apple ID without 2FA yet?

**Comment by Dinsen** [comment]
Yes, I currently don't have access to an account with 2FA enabled and licenses needs to be accepted.

**Comment by max-ott** [comment]
Not sure if it makes sense to solve the problem of "hacking away" 2 error messages. Do you also get the same timeout when trying to do the same with a 2FA-enabled Apple ID?

**Comment by Dinsen** [comment]
The 2 error messages is just to catch the error type. Something we could use in the company, so we can avoid using `Spaceship::Portal.fetch_program_license_agreement_messages` and avoid using session login.


The actually problem is if you use the API Key and the license is not accepted, `Spaceship` will throw this error: `undefined method 'status' for nil:NilClass`

It's happening because the `Portal` client is returning `raise AccessForbiddenError.new, msg`.
And since the `ConnectAPI` client is not getting the response from the API, but the `AccessForbiddenError` error. `Spaceship` fails with `undefined method 'status' for nil:NilClass`.

How can we pass the API response to `ConnectAPI` in case of a 403, and still handle the 403 error for `Portal` as it is now?

I don't have an account with 2FA enabled and licenses needs to be accepted. So I'm not able to find a solution myself.

**Comment by rogerluan** [comment]
Closing this, as https://github.com/fastlane/fastlane/pull/18299 was merged 🚀
