### ISSUE TITLE
Force scan to fail if requested simulator does not exist

### ISSUE THREAD

**Issue by tedgonzalez** [fastlane/fastlane#18207]
# Feature Request

Currently if you request scan to run on a particular simulator if that simulator is not found scan will fallback to a default simulator. I would like to be able to fail scan early if the required simulator is not found.

# Motivation Behind Feature

I need the ability for scan to fail early as a mechanism for ensuring that the required simulator is indeed installed on a particular CI machine. This is because we may require a test to run on a particular simulator e.g. a UI test suite run on a particularly sized device.

Example:
fastlane 2.172.0

```
devices: [
        "iPhone 6s (12.4)",
        "iPhone 11 (13.2.2)",
        "iPhone 11 (14.3)",
        "iPhone 11 Pro (14.3)",
        "iPhone 11 Pro Max (14.3)",
        "iPhone 12 (14.3)",
        "iPhone 12 Pro (14.3)",
        "iPhone 12 Pro Max (14.3)",
        "iPhone 12 mini (14.3)",
        "iPhone 8 (14.3)",
        "iPhone 8 Plus (14.3)",
        "iPhone SE (2nd generation) (14.3)"
      ]
```

Error log:  

> [14:33:13]: No simulators found that are equal to the version of specifier (14.3) and greater than or equal to the version of deployment target (0)
> [14:33:13]: Ignoring 'iPhone 11 (14.3)', couldn’t find matching simulator
> [14:33:13]: No simulators found that are equal to the version of specifier (14.3) and greater than or equal to the version of deployment target (0)
> [14:33:13]: Ignoring 'iPhone 11 Pro (14.3)', couldn’t find matching simulator
> [14:33:13]: No simulators found that are equal to the version of specifier (14.3) and greater than or equal to the version of deployment target (0)
> [14:33:13]: Ignoring 'iPhone 11 Pro Max (14.3)', couldn’t find matching simulator
> [14:33:13]: No simulators found that are equal to the version of specifier (14.3) and greater than or equal to the version of deployment target (0)
> [14:33:13]: Ignoring 'iPhone 12 (14.3)', couldn’t find matching simulator
> [14:33:13]: No simulators found that are equal to the version of specifier (14.3) and greater than or equal to the version of deployment target (0)
> [14:33:13]: Ignoring 'iPhone 12 Pro (14.3)', couldn’t find matching simulator
> [14:33:13]: No simulators found that are equal to the version of specifier (14.3) and greater than or equal to the version of deployment target (0)
> [14:33:13]: Ignoring 'iPhone 12 Pro Max (14.3)', couldn’t find matching simulator
> [14:33:13]: No simulators found that are equal to the version of specifier (14.3) and greater than or equal to the version of deployment target (0)
> [14:33:13]: Ignoring 'iPhone 12 mini (14.3)', couldn’t find matching simulator
> [14:33:13]: No simulators found that are equal to the version of specifier (14.3) and greater than or equal to the version of deployment target (0)
> [14:33:13]: Ignoring 'iPhone 8 (14.3)', couldn’t find matching simulator
> [14:33:13]: No simulators found that are equal to the version of specifier (14.3) and greater than or equal to the version of deployment target (0)
> [14:33:13]: Ignoring 'iPhone 8 Plus (14.3)', couldn’t find matching simulator
> [14:33:13]: No simulators found that are equal to the version of specifier (14.3) and greater than or equal to the version of deployment target (0)
> [14:33:13]: Ignoring 'iPhone SE (2nd generation) (14.3)', couldn’t find matching simulator
> 

It proceeded running tests on iPhone 6s and iPhone 11

Running
```
instruments -s devices
```
Results to:
```
iPhone 11 (13.2.2) [AA6CD591-6B39-4711-9E97-A51C13D57569] (Simulator)
iPhone 11 (14.2) [296DBC38-9EF8-4D6C-B585-EC4E3FE1EB42] (Simulator)
iPhone 11 (14.3) [4A3D63C8-6C58-4322-B691-43BD72E1ADB0] (Simulator)
iPhone 11 Pro (13.2.2) [CE72F74E-017E-47B7-A766-614D60DA9110] (Simulator)
iPhone 11 Pro (14.3) [3F01364A-4A7E-4A08-A1BA-D57D31F2741E] (Simulator)
iPhone 11 Pro Max (13.2.2) [F7916D53-6A79-433B-8517-A0C64B70D739] (Simulator)
iPhone 11 Pro Max (14.3) [DEC4ACF1-589A-4AAC-8547-285DACA93F04] (Simulator)
iPhone 12 (14.3) [9C06C94E-90F9-4FD3-A59D-96109B2F2C0C] (Simulator)
iPhone 12 (14.3) + Apple Watch Series 5 - 44mm (7.2) [CB72AEC3-6435-43D6-908E-5780925B6434] (Simulator)
iPhone 12 Pro (14.3) [ADEF2AA4-666C-4CBB-A733-4EE4DF08E153] (Simulator)
iPhone 12 Pro (14.3) + Apple Watch Series 6 - 40mm (7.2) [F753DF6D-ED77-44A8-B8F6-10E4B37A809F] (Simulator)
iPhone 12 Pro Max (14.3) [5ABBA5E5-DE1F-47E7-9C05-B5DCF66AD9E1] (Simulator)
iPhone 12 Pro Max (14.3) + Apple Watch Series 6 - 44mm (7.2) [A069ED0F-DFF3-4F07-A264-431A9CA0733F] (Simulator)
iPhone 12 mini (14.3) [2551D965-5300-4EEA-8051-9C17139A1752] (Simulator)
iPhone 12 mini (14.3) + Apple Watch Series 5 - 40mm (7.2) [E20E9CBE-8BE2-4ECA-ACD8-1CB3CF8C77C1] (Simulator)
iPhone 5s (11.4) [ED806DDC-1D67-45BF-A0F7-04303CDFA706] (Simulator)
iPhone 5s (12.4) [063F88C3-CE30-4560-A1E8-3F6794BB1952] (Simulator)
iPhone 6 (11.4) [70B9C42A-378E-4BB7-B980-C1F2468D296C] (Simulator)
iPhone 6 (12.4) [465FCDBF-F246-4420-8DC8-B7D1947440C5] (Simulator)
iPhone 6 Plus (11.4) [FE3635D3-1D35-41B0-B560-3E21FB8F5328] (Simulator)
iPhone 6 Plus (12.4) [5C4B5506-3A6D-498A-B7A2-F4564DC99B07] (Simulator)
iPhone 6s (11.4) [EB6E8E79-E40C-48B3-832E-23C53339AFBE] (Simulator)
iPhone 6s (12.4) [9DD8C137-7B85-4699-8728-CD20C54AF261] (Simulator)
iPhone 6s Plus (11.4) [FB6ADA1F-B730-4BB9-BE14-D991D94ECB24] (Simulator)
iPhone 6s Plus (12.4) [C03AE80D-26E9-4D57-A7A3-A302150B225C] (Simulator)
iPhone 7 (11.4) [C623BB50-559B-4A7F-8B41-29E1E770D12F] (Simulator)
iPhone 7 (12.4) [1F4CCE89-516E-434C-9A93-4C6E34359219] (Simulator)
iPhone 7 Plus (11.4) [9C874C5D-2C6F-4E41-93E2-8F51F140373F] (Simulator)
iPhone 7 Plus (12.4) [E177D07B-ABB0-4626-8F09-F07BD240CA87] (Simulator)
iPhone 8 (11.4) [14F2968C-0CB7-46F3-97BA-6117DFE3ACF1] (Simulator)
iPhone 8 (12.4) [0669B9B1-301C-4327-B30F-DF82B44B5060] (Simulator)
iPhone 8 (13.2.2) [3C33BE85-0BF3-4390-9132-492A09AD50B8] (Simulator)
iPhone 8 (14.3) [B865CB45-84DA-4B27-91B0-0C7D7AB65C0B] (Simulator)
iPhone 8 Plus (11.4) [DC954443-0CC7-4C6D-B31B-9B5121600BB4] (Simulator)
iPhone 8 Plus (12.4) [4FB523A4-F629-4666-A265-ADCA6FB42549] (Simulator)
iPhone 8 Plus (13.2.2) [BB5DC9C1-0050-4490-B39A-F408B77A4D70] (Simulator)
iPhone 8 Plus (14.3) [133F40BB-A819-45BE-8467-7F8FF57DD3FB] (Simulator)
iPhone SE (11.4) [3136CEBB-71FD-4F67-810F-9CE95A53AE67] (Simulator)
iPhone SE (12.4) [2CC43AE8-FEDD-470A-98C1-8DA8D3660400] (Simulator)
iPhone SE (2nd generation) (14.3) [FE09943B-CEFA-449F-A3AC-7AC1ACA6C9BD] (Simulator)
```

# Feature Description

I imagine this could be done as an optional argument to scan (i.e. ensure_device_found) which would default to false so that it would not be a breaking change.

# Alternatives or Workarounds

I've searched for alternatives but didn't find any would love to hear about workarounds if there are known ones available.
One suggestion was to use `skip_detect_devices` but it didn't work.

source 1: #15706
source 2: #16184

**Comment by Kukurijek** [comment]
Hi @max-ott! Could you please close this issue, since PR is already Merged and released (2.177.0).
