### ISSUE TITLE
upload_to_app_store  The parameter 'filter[bundleId][]' can only be included once

### ISSUE THREAD

**Issue by long1eu** [fastlane/fastlane#18204]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I try can't seems to be able to upload my ipa to store.

##### Command executed
upload_to_app_store

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [09:31:32]: --- Step: upload_to_app_store ---
[09:31:32]: ---------------------------------
[09:31:32]: Creating authorization token for App Store Connect API
+------------------------------------+---------------------------------------------------------------------------------------------------------------+
|                                                                    Lane Context                                                                    |
+------------------------------------+---------------------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM                   | ios                                                                                                           |
| PLATFORM_NAME                      | ios                                                                                                           |
| LANE_NAME                          | ios build_appstore                                                                                            |
| SIGH_PROFILE_TYPE                  | app-store                                                                                                     |
| MATCH_PROVISIONING_PROFILE_MAPPING | {"com.ptchapp.ptchapp"=>"match AppStore com.ptchapp.ptchapp", "com.ptchapp.ptchapp.dev"=>"match AppStore      |
|                                    | com.ptchapp.ptchapp.dev"}                                                                                     |
| IPA_OUTPUT_PATH                    | /Users/long1eu/IdeaProjects/ptch/app/build/ios/iphoneos/Runner_appstore_prod.ipa                              |
| XCODEBUILD_ARCHIVE                 | /Users/long1eu/Library/Developer/Xcode/Archives/2021-02-14/Runner_appstore_prod 2021-02-14 09.23.25.xcarchive |
| DSYM_OUTPUT_PATH                   | /Users/long1eu/IdeaProjects/ptch/app/build/ios/iphoneos/Runner_appstore_prod.app.dSYM.zip                     |
+------------------------------------+---------------------------------------------------------------------------------------------------------------+
[09:31:33]: A parameter is included more than once - The parameter 'filter[bundleId][]' can only be included once

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | update_fastlane     | 4           |
| 2    | default_platform    | 0           |
| 3    | cocoapods           | 18          |
| 4    | is_ci               | 0           |
| 5    | match               | 16          |
| 6    | gym                 | 499         |
| 💥   | upload_to_app_store | 0           |
+------+---------------------+-------------+

[09:31:33]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  [spaceship, pilot] Getting "410 gone"
    https://github.com/fastlane/fastlane/issues/14521 [closed] 177 💬
    22 Jun 2019

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/Users/long1eu/.gem/ruby/2.7.0/bin/fastlane)
Traceback (most recent call last):
        53: from /usr/local/opt/ruby@2.7/bin/bundler:23:in `<main>'
        52: from /usr/local/opt/ruby@2.7/bin/bundler:23:in `load'
        51: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/exe/bundler:4:in `<top (required)>'
        50: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/exe/bundler:4:in `load'
        49: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/exe/bundle:37:in `<top (required)>'
        48: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
        47: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/exe/bundle:49:in `block in <top (required)>'
        46: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/cli.rb:24:in `start'
        45: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        44: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/cli.rb:30:in `dispatch'
        43: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        42: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        41: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        40: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/cli.rb:494:in `exec'
        39: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/cli/exec.rb:28:in `run'
        38: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/cli/exec.rb:63:in `kernel_load'
        37: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/cli/exec.rb:63:in `load'
        36: from /Users/long1eu/.gem/ruby/2.7.0/bin/fastlane:23:in `<top (required)>'
        35: from /Users/long1eu/.gem/ruby/2.7.0/bin/fastlane:23:in `load'
        34: from /Users/long1eu/.gem/ruby/2.7.0/gems/fastlane-2.174.0/bin/fastlane:23:in `<top (required)>'
        33: from /Users/long1eu/.gem/ruby/2.7.0/gems/fastlane-2.174.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
        32: from /Users/long1eu/.gem/ruby/2.7.0/gems/fastlane-2.174.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        31: from /Users/long1eu/.gem/ruby/2.7.0/gems/fastlane-2.174.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
        30: from /Users/long1eu/.gem/ruby/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        29: from /Users/long1eu/.gem/ruby/2.7.0/gems/fastlane-2.174.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        28: from /Users/long1eu/.gem/ruby/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        27: from /Users/long1eu/.gem/ruby/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        26: from /Users/long1eu/.gem/ruby/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        25: from /Users/long1eu/.gem/ruby/2.7.0/gems/fastlane-2.174.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
        24: from /Users/long1eu/.gem/ruby/2.7.0/gems/fastlane-2.174.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        23: from /Users/long1eu/.gem/ruby/2.7.0/gems/fastlane-2.174.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        22: from /Users/long1eu/.gem/ruby/2.7.0/gems/fastlane-2.174.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        21: from /Users/long1eu/.gem/ruby/2.7.0/gems/fastlane-2.174.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        20: from /Users/long1eu/.gem/ruby/2.7.0/gems/fastlane-2.174.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        19: from /Users/long1eu/.gem/ruby/2.7.0/gems/fastlane-2.174.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        18: from Fastfile:75:in `block (2 levels) in parsing_binding'
        17: from /Users/long1eu/.gem/ruby/2.7.0/gems/fastlane-2.174.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        16: from /Users/long1eu/.gem/ruby/2.7.0/gems/fastlane-2.174.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        15: from /Users/long1eu/.gem/ruby/2.7.0/gems/fastlane-2.174.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        14: from /Users/long1eu/.gem/ruby/2.7.0/gems/fastlane-2.174.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        13: from /Users/long1eu/.gem/ruby/2.7.0/gems/fastlane-2.174.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
        12: from /Users/long1eu/.gem/ruby/2.7.0/gems/fastlane-2.174.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        11: from /Users/long1eu/.gem/ruby/2.7.0/gems/fastlane-2.174.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
        10: from /Users/long1eu/.gem/ruby/2.7.0/gems/fastlane-2.174.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:18:in `run'
         9: from /Users/long1eu/.gem/ruby/2.7.0/gems/fastlane-2.174.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:18:in `new'
         8: from /Users/long1eu/.gem/ruby/2.7.0/gems/fastlane-2.174.0/deliver/lib/deliver/runner.rb:24:in `initialize'
         7: from /Users/long1eu/.gem/ruby/2.7.0/gems/fastlane-2.174.0/deliver/lib/deliver/detect_values.rb:15:in `run!'
         6: from /Users/long1eu/.gem/ruby/2.7.0/gems/fastlane-2.174.0/deliver/lib/deliver/detect_values.rb:44:in `find_app'
         5: from /Users/long1eu/.gem/ruby/2.7.0/gems/fastlane-2.174.0/spaceship/lib/spaceship/connect_api/models/app.rb:80:in `find'
         4: from /Users/long1eu/.gem/ruby/2.7.0/gems/fastlane-2.174.0/spaceship/lib/spaceship/connect_api/models/app.rb:74:in `all'
         3: from /usr/local/Cellar/ruby@2.7/2.7.2/lib/ruby/2.7.0/forwardable.rb:235:in `get_apps'
         2: from /Users/long1eu/.gem/ruby/2.7.0/gems/fastlane-2.174.0/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:22:in `get_apps'
         1: from /Users/long1eu/.gem/ruby/2.7.0/gems/fastlane-2.174.0/spaceship/lib/spaceship/connect_api/api_client.rb:113:in `get'
/Users/long1eu/.gem/ruby/2.7.0/gems/fastlane-2.174.0/spaceship/lib/spaceship/connect_api/api_client.rb:193:in `handle_response': \e[31m[!] A parameter is included more than once - The parameter 'filter[bundleId][]' can only be included once\e[0m (Spaceship::UnexpectedResponse)
 </pre>
</details>

### Environment

<details>
  <pre> <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.6                                     |
| Ruby                        | 2.7.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.gem/ruby/2.7.0/bin/fastlane              |
| Host                        | Mac OS X 10.15.6 (19G2005)                  |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.7/2.7.2/lib        |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.4                                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# frozen_string_literal: true

update_fastlane
default_platform(:ios)

BUILD_OUTPUT_ = '../build/ios/iphoneos'
APPSTORE_CONNECT_API_KEY_PATH_ = '../../keys/D7B4TG546P.json'

def setup_ci(type, env)
  keychain_name = 'CI'
  keychain_password = ENV['MATCH_PASSWORD']

  create_keychain(
    name: keychain_name,
    password: keychain_password,
    default_keychain: true,
    unlock: true,
    timeout: 3600,
    lock_when_sleeps: false
  )
  match(
    type: type,
    force_for_new_devices: true,
    keychain_name: keychain_name,
    keychain_password: keychain_password,
    api_key_path: APPSTORE_CONNECT_API_KEY_PATH_
  )
  sh('security list-keychains -d user')
  sh('security default-keychain -d user')
  sh("security find-identity -v -p codesigning #{keychain_name}")

  app_identifier = "com.ptchapp.ptchapp#{env == "prod" ? "" : ".#{env}"}"

  team_id = ENV["sigh_#{app_identifier}_#{type}_team-id"]
  identity = "Apple Distribution: ptch Corporation (#{team_id})"
  profile = ENV["sigh_#{app_identifier}_#{type}"]
  profile_name = ENV["sigh_#{app_identifier}_#{type}_profile-name"]

  update_code_signing_settings(
    use_automatic_signing: false,
    path: 'Runner.xcodeproj',
    team_id: team_id,
    profile_uuid: profile,
    profile_name: profile_name,
    code_sign_identity: identity
  )
end

def build(type, export_method, env)
  cocoapods
  if is_ci
    setup_ci(type, env)
  else
    match(type: type, force_for_new_devices: true, api_key_path: APPSTORE_CONNECT_API_KEY_PATH_)
  end

  gym(
    workspace: 'Runner.xcworkspace',
    scheme: env,
    output_directory: BUILD_OUTPUT_,
    output_name: "Runner_#{type}_#{env}.ipa",
    export_method: export_method
  )
end

platform :ios do
  desc 'Build ipa for Firebase App Distribution'
  lane :build_firebase do |values|
    build('adhoc', 'ad-hoc', values[:env])
  end

  desc 'Build ipa for App Store and upload'
  lane :build_appstore do |values|
    build('appstore', 'app-store', values[:env])
    upload_to_app_store(
      run_precheck_before_submit: false,
      api_key_path: APPSTORE_CONNECT_API_KEY_PATH_,
      ipa: "#{BUILD_OUTPUT_}/Runner_appstore_#{values[:env]}.ipa",
      force: true,
    )
  end

  desc 'Add new device'
  lane :register do |values|
    register_devices(
      devices: {
        values[:name] => values[:udid],
      },
      api_key_path: APPSTORE_CONNECT_API_KEY_PATH_
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
team_id("447Q6692WZ")
app_identifier(["com.ptchapp.ptchapp", "com.ptchapp.ptchapp.dev"])
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.174.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.4.0        |
| bundler                       | 2.2.7        |
| uri                           | 0.10.0       |
| rake                          | 13.0.3       |
| CFPropertyList                | 3.0.3        |
| concurrent-ruby               | 1.1.8        |
| i18n                          | 1.8.8        |
| minitest                      | 5.14.3       |
| thread_safe                   | 0.3.6        |
| tzinfo                        | 1.2.9        |
| activesupport                 | 5.2.4.4      |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| httpclient                    | 2.8.3        |
| json                          | 2.5.1        |
| algoliasearch                 | 1.27.5       |
| artifactory                   | 3.0.15       |
| atomos                        | 0.1.3        |
| aws-eventstream               | 1.1.0        |
| aws-partitions                | 1.427.0      |
| aws-sigv4                     | 1.2.2        |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.112.0      |
| aws-sdk-kms                   | 1.42.0       |
| aws-sdk-s3                    | 1.88.1       |
| babosa                        | 1.0.4        |
| claide                        | 1.0.3        |
| fuzzy_match                   | 2.0.4        |
| nap                           | 1.1.0        |
| netrc                         | 0.11.0       |
| ffi                           | 1.14.2       |
| ethon                         | 0.12.0       |
| typhoeus                      | 1.4.0        |
| cocoapods-core                | 1.10.1       |
| cocoapods-deintegrate         | 1.0.4        |
| cocoapods-downloader          | 1.4.0        |
| cocoapods-plugins             | 1.0.0        |
| cocoapods-search              | 1.0.0        |
| cocoapods-trunk               | 1.5.0        |
| cocoapods-try                 | 1.2.0        |
| colored2                      | 3.1.2        |
| escape                        | 0.0.4        |
| fourflusher                   | 2.3.1        |
| gh_inspector                  | 1.1.3        |
| molinillo                     | 0.6.6        |
| ruby-macho                    | 1.4.0        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| cocoapods                     | 1.10.1       |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| digest-crc                    | 0.6.3        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| dotenv                        | 2.7.6        |
| emoji_regex                   | 3.2.1        |
| excon                         | 0.79.0       |
| faraday-net_http              | 1.0.1        |
| multipart-post                | 2.0.0        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.2        |
| jwt                           | 2.2.2        |
| memoist                       | 0.16.2       |
| multi_json                    | 1.15.0       |
| os                            | 1.1.1        |
| signet                        | 0.14.1       |
| googleauth                    | 0.15.1       |
| mini_mime                     | 1.0.2        |
| uber                          | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| google-api-client             | 0.38.0       |
| rexml                         | 3.2.4        |
| webrick                       | 1.7.0        |
| google-apis-core              | 0.2.1        |
| google-apis-iamcredentials_v1 | 0.1.0        |
| google-apis-storage_v1        | 0.2.0        |
| google-cloud-env              | 1.4.0        |
| google-cloud-errors           | 1.0.1        |
| google-cloud-core             | 1.5.0        |
| google-cloud-storage          | 1.30.0       |
| mini_magick                   | 4.11.0       |
| plist                         | 3.6.0        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| naturally                     | 2.2.1        |
| simctl                        | 1.6.8        |
| slack-notifier                | 2.3.2        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| word_wrap                     | 1.0.0        |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| xcpretty-travis-formatter     | 1.0.1        |
</details>

*generated on:* **2021-02-14**
</details> </pre>
</details>

**Comment by max-ott** [comment]
Can you please post your whole fastfile or the complete command you ran?

**Comment by long1eu** [comment]
Sure:

```
# frozen_string_literal: true

update_fastlane
default_platform(:ios)

BUILD_OUTPUT_ = '../build/ios/iphoneos'
APPSTORE_CONNECT_API_KEY_PATH_ = '../../keys/D7B4TG546P.json'

def setup_ci(type, env)
  keychain_name = 'CI'
  keychain_password = ENV['MATCH_PASSWORD']

  create_keychain(
    name: keychain_name,
    password: keychain_password,
    default_keychain: true,
    unlock: true,
    timeout: 3600,
    lock_when_sleeps: false
  )
  match(
    type: type,
    force_for_new_devices: true,
    keychain_name: keychain_name,
    keychain_password: keychain_password,
    api_key_path: APPSTORE_CONNECT_API_KEY_PATH_
  )
  sh('security list-keychains -d user')
  sh('security default-keychain -d user')
  sh("security find-identity -v -p codesigning #{keychain_name}")

  app_identifier = "com.example.app#{env == "prod" ? "" : ".#{env}"}"

  team_id = ENV["sigh_#{app_identifier}_#{type}_team-id"]
  identity = "Apple Distribution: App Corporation (#{team_id})"
  profile = ENV["sigh_#{app_identifier}_#{type}"]
  profile_name = ENV["sigh_#{app_identifier}_#{type}_profile-name"]

  update_code_signing_settings(
    use_automatic_signing: false,
    path: 'Runner.xcodeproj',
    team_id: team_id,
    profile_uuid: profile,
    profile_name: profile_name,
    code_sign_identity: identity
  )
end

def build(type, export_method, env)
  cocoapods
  if is_ci
    setup_ci(type, env)
  else
    match(type: type, force_for_new_devices: true, api_key_path: APPSTORE_CONNECT_API_KEY_PATH_)
  end

  gym(
    workspace: 'Runner.xcworkspace',
    scheme: env,
    output_directory: BUILD_OUTPUT_,
    output_name: "Runner_#{type}_#{env}.ipa",
    export_method: export_method
  )
end

platform :ios do
  desc 'Build ipa for Firebase App Distribution'
  lane :build_firebase do |values|
    build('adhoc', 'ad-hoc', values[:env])
  end

  desc 'Build ipa for App Store and upload'
  lane :build_appstore do |values|
    build('appstore', 'app-store', values[:env])
  end

  desc 'Deploy to app store'
  lane :deploy do |values|
    upload_to_app_store(
      run_precheck_before_submit: false,
      api_key_path: APPSTORE_CONNECT_API_KEY_PATH_,
      ipa: "#{BUILD_OUTPUT_}/Runner_appstore_#{values[:env]}.ipa",
      force: true,
    )
  end

  desc 'Add new device'
  lane :register do |values|
    register_devices(
      devices: {
        values[:name] => values[:udid],
      },
      api_key_path: APPSTORE_CONNECT_API_KEY_PATH_
    )
  end
end
#
```

```
bundler exec fastlane deploy env:prod
```

**Comment by long1eu** [comment]
@max-ott does this help?
