### ISSUE TITLE
Release app version does not work with app store connect using api keys (The URL path is not valid - The resource 'appStoreVersionReleaseRequests' does not exist)

### ISSUE THREAD

**Issue by thiagoferreiraw** [fastlane/fastlane#18209]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I recently enabled 2FA on my app store connect account and then started to use api_keys as my primary authentication method.

After doing so, I'm no longer able to release apps using this method: 

```ruby
app.get_latest_app_store_version.create_app_store_version_release_request
```
Where I'll have this output: 
```
[09:45:55]: iOS build failed with exception message "The URL path is not valid - The resource 'appStoreVersionReleaseRequests' does not exist"
```

### Related issues (closed)

- https://github.com/fastlane/fastlane/issues/17283 Release app version using new AppStoreConnect API fails for phased release ( The URL path is not valid - The resource 'appStoreVersionReleaseRequests' does not exist )
- https://github.com/fastlane/fastlane/pull/16765  [spaceship] Support manual app release #16765

### Workarounds

- This workaround worked for me: https://github.com/fastlane/fastlane/issues/17283#issuecomment-711865915

##### Command executed

```ruby
version =  app.get_latest_app_store_version
version.create_app_store_version_release_request
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                         |
| --------------------------- | ------------------------------------------------------------- |
| OS                          | 10.15.6                                                       |
| Ruby                        | 2.6.3                                                         |
| Bundler?                    | true                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                            |
| Installation Source         | ~/project/whatsgood-ios/vendor/bundle/ruby/2.6.0/bin/fastlane |
| Host                        | Mac OS X 10.15.6 (19G2021)                                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.3/lib                                   |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                                    |
| Is contained                | false                                                         |
| Is homebrew                 | false                                                         |
| Is installed via Fabric.app | false                                                         |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                   |
| Xcode Version               | 12.3                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# sensitive info
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id "placeholder@example.com" # Your Apple email address

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.174.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-xcodegen                  | 1.0.0   | ✅ Up-To-Date  |
| fastlane-plugin-sentry                    | 1.8.0   | ✅ Up-To-Date  |
| fastlane-plugin-firebase_app_distribution | 0.2.5   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.3.0        |
| bundler                                   | 1.17.2       |
| etc                                       | 1.0.1        |
| forwardable                               | 1.2.0        |
| rake                                      | 13.0.3       |
| CFPropertyList                            | 3.0.3        |
| concurrent-ruby                           | 1.1.8        |
| i18n                                      | 1.8.9        |
| minitest                                  | 5.14.3       |
| thread_safe                               | 0.3.6        |
| tzinfo                                    | 1.2.9        |
| activesupport                             | 5.2.4.5      |
| public_suffix                             | 4.0.6        |
| addressable                               | 2.7.0        |
| httpclient                                | 2.8.3        |
| json                                      | 2.5.1        |
| algoliasearch                             | 1.27.5       |
| artifactory                               | 3.0.15       |
| atomos                                    | 0.1.3        |
| aws-eventstream                           | 1.1.0        |
| aws-partitions                            | 1.427.0      |
| aws-sigv4                                 | 1.2.2        |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.112.0      |
| aws-sdk-kms                               | 1.42.0       |
| aws-sdk-s3                                | 1.88.1       |
| babosa                                    | 1.0.4        |
| claide                                    | 1.0.3        |
| fuzzy_match                               | 2.0.4        |
| nap                                       | 1.1.0        |
| netrc                                     | 0.11.0       |
| ffi                                       | 1.14.2       |
| ethon                                     | 0.12.0       |
| typhoeus                                  | 1.4.0        |
| cocoapods-core                            | 1.10.1       |
| cocoapods-deintegrate                     | 1.0.4        |
| cocoapods-downloader                      | 1.4.0        |
| cocoapods-plugins                         | 1.0.0        |
| cocoapods-search                          | 1.0.0        |
| cocoapods-trunk                           | 1.5.0        |
| cocoapods-try                             | 1.2.0        |
| colored2                                  | 3.1.2        |
| escape                                    | 0.0.4        |
| fourflusher                               | 2.3.1        |
| gh_inspector                              | 1.1.3        |
| molinillo                                 | 0.6.6        |
| ruby-macho                                | 1.4.0        |
| nanaimo                                   | 0.3.0        |
| xcodeproj                                 | 1.19.0       |
| cocoapods                                 | 1.10.1       |
| coderay                                   | 1.1.3        |
| colored                                   | 1.2          |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| declarative                               | 0.0.20       |
| declarative-option                        | 0.1.0        |
| digest-crc                                | 0.6.3        |
| unf_ext                                   | 0.0.7.7      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| dotenv                                    | 2.7.6        |
| emoji_regex                               | 3.2.1        |
| excon                                     | 0.79.0       |
| faraday-net_http                          | 1.0.1        |
| multipart-post                            | 2.0.0        |
| ruby2_keywords                            | 0.0.4        |
| faraday                                   | 1.3.0        |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.0.0        |
| fastimage                                 | 2.2.2        |
| jwt                                       | 2.2.2        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.1        |
| signet                                    | 0.14.1       |
| googleauth                                | 0.15.1       |
| mini_mime                                 | 1.0.2        |
| uber                                      | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| google-api-client                         | 0.38.0       |
| rexml                                     | 3.2.4        |
| webrick                                   | 1.7.0        |
| google-apis-core                          | 0.2.1        |
| google-apis-iamcredentials_v1             | 0.1.0        |
| google-apis-storage_v1                    | 0.2.0        |
| google-cloud-env                          | 1.4.0        |
| google-cloud-errors                       | 1.0.1        |
| google-cloud-core                         | 1.5.0        |
| google-cloud-storage                      | 1.30.0       |
| mini_magick                               | 4.11.0       |
| plist                                     | 3.6.0        |
| rubyzip                                   | 2.3.0        |
| security                                  | 0.1.3        |
| naturally                                 | 2.2.1        |
| simctl                                    | 1.6.8        |
| slack-notifier                            | 2.3.2        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.7.0        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| word_wrap                                 | 1.0.0        |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.1        |
| fastlane-plugin-brew                      | 0.1.1        |
| fastlane-plugin-firebase_app_distribution | 0.2.5        |
| fastlane-plugin-sentry                    | 1.8.0        |
| fastlane-plugin-xcodegen                  | 1.0.0        |
| http-accept                               | 1.7.0        |
| method_source                             | 1.0.0        |
| mime-types-data                           | 3.2021.0212  |
| mime-types                                | 3.3.1        |
| pry                                       | 0.14.0       |
| rest-client                               | 2.1.0        |
</details>

*generated on:* **2021-02-15**
</details>

**Comment by max-ott** [comment]
Can you make sure that this is actually possible using the API, i.e. link to the Apple docs? A lot of endpoints / actions are not (yet) accessible via the ASC API.

**Comment by thiagoferreiraw** [comment]
Ok, will do that and get back to you soon @max-ott, thanks!

**Comment by thiagoferreiraw** [comment]
Hi everyone!
Looks like the workaround started working again: https://github.com/fastlane/fastlane/issues/17283#issuecomment-801037142

I'll close this issue for now.
Thank you all!

**Comment by andrew54068** [comment]
I write a plugin for auto release reviewed version.
https://github.com/andrew54068/fastlane-plugin-taiwan_number_one.
feel free to use it.
