### ISSUE TITLE
spaceship analytics stop working

### ISSUE THREAD

**Issue by DKY1** [fastlane/fastlane#18203]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
hello, i'm running spaceship from a ruby file from the command line on windows. the code was working and running daily for about 2 month, but few days ago it's stop working. i'm able to connect to app store connect and to get my app with this line
>>app = Spaceship::Tunes::Application.find(bundle_id)
i'm also able to get the analytics object with this lines:
>> attrs = {}  
>>attrs[:apple_id] = apple_id  
>>analytics = Spaceship::Tunes::AppAnalytics.factory(attrs)
but when i try to read data i allweys get nil, for exemple all of this lines return Nil:
>>impressions = analytics.app_impressions_interval(date_start,  date_end)
>>views = analytics.app_views_interval(date_start, date_end)
>>units = analytics.app_units_interval(date_start, date_end)
>>sales = analytics.app_sales_interval(date_start, date_end)

##### Command executed
the full code

require "spaceship"

bundle_id = ARGV[0]
apple_id = ARGV[1]
date_start = ARGV[2]
date_end = ARGV[3]

Spaceship::Tunes.login([EMAIL], [PASSWORD])
Spaceship::Tunes.client.select_team(team_id: nil, team_name:[ TEAM_NAME])

app = Spaceship::Tunes::Application.find(bundle_id)
attrs = {}  
attrs[:apple_id] = apple_id  
analytics = Spaceship::Tunes::AppAnalytics.factory(attrs)
impressions = analytics.app_impressions_interval(date_start+"T00:00:00Z", date_end+"T00:00:00Z")
puts impressions["results"][0]["totals"]["value"]

##### Complete output when running fastlane, including the stack trace and command used
command line output
Traceback (most recent call last):
C:/Users/ASUS/PycharmProjects/price_optimization/analytics_with_argv.rb:26:in `<main>': undefined method `[]' for nil:NilClass (NoMethodError)

**Comment by max-ott** [comment]
The old `Spaceship::Tunes` way is deprecated and it's possible that Apple is getting rid of the old endpoints. The error message said it failed on line 26, but there's no easy way to see what line 26 is. Also you missed the whole issue template about your fastlane setup.

**Comment by DKY1** [comment]
yes you right, line 26 is the last line:
>>puts impressions["results"][0]["totals"]["value"]
it's dosen't work becouse impressions is Nil

**Comment by reizist** [comment]
Hi, I'm also in trouble with this.

```rb
require "spaceship"
require 'pry-byebug'

class Client
  def initialize(user, password, team_id, app_id, days)
    Spaceship::Tunes.login(user, password)
    Spaceship::Tunes.select_team(team_id: team_id)
    attrs = {}
    attrs[:apple_id] = app_id
    @analytics = Spaceship::Tunes::AppAnalytics.factory(attrs)
    @end_date = Time.now
    @start_date = @end_date - (days - 1) * 24 * 60 * 60
  end

  def analyze(metrics, dimension = nil)
    responses = metrics.each_slice(2).map do |metrics_slice|
      @analytics.client.time_series_analytics(
        [@analytics.apple_id],
        metrics_slice,
        @start_date.strftime("%Y-%m-%dT00:00:00Z"),
        @end_date.strftime("%Y-%m-%dT00:00:00Z"),
        "DAY",
        dimension
      )
    end
    puts "responses=#{responses}"
  end


user = ENV["APPLE_ID"]
password = ENV["APPLE_PASSWORD"]
team_id = ENV["TEAM_ID"]
app_id = ENV["APP_ID"]
metrics = %w(impressionsTotal units)
days = 7

Client.new(user, password, team_id, app_id, days)
binding.pry
@analytics.client
```

tested like this script, but any API response looks empty.

```
[4] pry(#<Client>)> @analytics.app_units
=> ""

[7] pry(#<Client>)> @analytics.client.time_series_analytics([@analytics.apple_id], metrics.first, @start_date.strftime("%Y-%m-%dT00:00:00Z"), @end_date.strftime("%Y-%m-%dT00:00:00Z"), "DAY", nil)
=> ""

[8] pry(#<Client>)> @analytics.app_installs
=> ""

[11] pry(#<Client>)> @analytics.app_active_devices
=> ""
```

I think Apple just stop old endpoints, unfortunately.

**Comment by valerio-castelli** [comment]
I've just investigated into this. Apple migrated the analytics endpoints from the [analytics.itunes.apple.com](url) domain to the [appstoreconnect.apple.com](url) domain. The response format looks the same though, a simple find and replace on my local copy of fastlane was enough to get it to work again 🙏

**Comment by reizist** [comment]
@valerio-castelli 

It works !! Thank you !!

```
[3] pry(#<Client>)> @analytics.app_active_devices
=> {"size"=>1,
 "results"=>
  [{"adamId"=>"xxx",
    "meetsThreshold"=>true,
    "group"=>nil,
    "data"=>
     [{"date"=>"2021-02-09T00:00:00Z", "activeDevices"=>xxx},
```

**Comment by DKY1** [comment]
works for me to. thank you very much
