### ISSUE TITLE
use_legacy_build_api always true

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1820]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/9294672?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @yzlhccdec - Imported from <a href='https://github.com/fastlane/gym/issues/217'>fastlane/gym#217</a>
        </td>
      </tr>
    </table>

I'm using circleci for daily build, I can't set use_legacy_build_api to false when building, It's just not working.
I've tried
gym -s "$BUILD_SCHEME" -n "XXX.$GIT_COUNT" -j "ad-hoc" -o "build" -c --use_legacy_build_api false
gym -s "$BUILD_SCHEME" -n "XXX.$GIT_COUNT" -j "ad-hoc" -o "build" -c

the version of Xcode for building is 7.2，I always get the message "Using legacy build system - waiting for radar to be fixed: https://openradar.appspot.com/radar?id=4952000420642816"

Please help! Thank you

**Comment by yzlhccdec** [comment]
I think maybe this is the root cause:
sudo xcode-select --switch /Applications/Xcode-7.2.app && xcodebuild -version
Xcode 7.2.1 Build version 7C1002

the path is not compatible with testing logic offered by fastlanecore

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (401/400 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:37895 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKqR-002kWS-L4
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:19:53 +0200
Date: Sat, 18 Jun 2016 11:19:06 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466273946;
	bh=ble+PCistp68q/TjxoT1Mscxf/u0anYc4gSWMd/pGeI=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=nCNIO9PbTFR8PK/MQsuZIWGBJlb39P87QHmUmYxXDkpVQ2O4WxXkpUTLtvWt4G3fp
	 z7K3duhwg9vhuN92c8wq8rgK01XZFvIMCvn4T/poghKFHQSfPc2nMhGwDcbblGNiaD
	 DRQ//uUJ8Z7UGiGos0xg25ZFOnHc3H4mHE7UGMI4=

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (402/400 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:59653)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1bEKqW-002kXP-3h
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:19:56 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=3JFPzwUdsxcg63L3MjAQXuBeJdY=; b=cRUoLE6E9582OFW2
	gL9LCHfFxXenYJKcvX1XpA0EHeGsOWtMUXUJFmHLja6l6dP39jOGyS+tWt93ws4+
	KLZ2uACE/T70lFo3ttIoCq18HV3zvtFPdSxzFmLcRXAZ0qhGjfxQ0DXnF0FfbRwg
	Np3LljzMl5YV6ZK2HAQfqNu2c2E=
Received: by filter0531p1mdw1.sendgrid.net with SMTP id filter0531p1mdw1.24912.5765909A22
        2016-06-18 18:19:06.748960564 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id mM_d2z2zSEO4Be1jKZF_rg
	for <yann.dupuy@zyapps.com>; Sat, 18 Jun 2016 18:19:06.656 +0000 (UTC)
Date: Sat, 18 Jun 2016 11:19:06 -0700
