### ISSUE TITLE
Unable to upload IPA resigned with fastlane using wildcard profile

### ISSUE THREAD

**Issue by ViRb3** [fastlane/fastlane#18214]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When a wildcard provisioning profile (one with an application identifier like `KTORUWN.*`) is used to resign an app:
```bash
fastlane sigh resign file.ipa -i "John Doe" -p "profile.mobileprovision" 
```
fastlane will copy the entitlements from the profile into the app as-is, including the wildcard bundle id. On iOS 14+, this breaks all app entitlements on the signed app, including the file picker. To solve this, fastlane should simply expand the bundle id in the app entitlements from the wildcard to the full app id (i.e. from `KTORUWN.*` to `KTORUWN.my.app`).

This issue is a duplicate of #16515, closed for inactivity, except I have described the root cause of the problem.

**Comment by ViRb3** [comment]
Here is an example of how this problem was fixed in another app, ios-app-signer: https://github.com/DanTheMan827/ios-app-signer/pull/163

**Comment by ViRb3** [comment]
Here's another reference: https://github.com/xndrs/XReSign/pull/30

**Comment by kapfab** [comment]
Using the `bundle_id` and `use_app_entitlements` parameters does not help?

**Comment by ViRb3** [comment]
`bundle_id` is unrelated, since that changes the app's bundle id, not the entitlements' application id. Either way, I tested it and it doesn't work.

`use_app_entitlements` should work, but for some reason it doesn't. The app entitlements' application id is overwritten with the wildcard application id from the provisioning profile, breaking all entitlements.

Just to make sure, I also tested both of these flags combined, and no success.

Either way, the flags above would be a workaround at best. I believe that proper handing of wildcard provisioning profiles should be added by default.

**Comment by kapfab** [comment]
Well, as far as I can see, this issue does not only affects the application identifier, but also other entitlement(s) that can contain a reference to it (`keychain-access-groups` being the only one of this type I know of).

This could probably be fixed quite easily, but it might not be a very safe/future-proof move as using wildcards for App Store distribution is something Apple wants to prevent (the Apple Developer Portal's provisioning profile creation page states that `Uploading apps to the App Store requires an explicit App ID. In the future, wildcard app IDs will no longer appear when creating an App Store provisioning profile.` — There is no such statement for Entreprise In House Distribution profiles, though).

For now, I think the fastest solution for you might be to use the `entitlements` option so you can directly provide your target entitlements file.
