### ISSUE TITLE
New Feature: Ability to reply to customer reviews on the app store

### ISSUE THREAD

**Issue by hhoweson** [fastlane/fastlane#18218]
**Intro**

I've looked through the spaceship documentation and codebase and can't seem to find any evidence of this feature already existing (please correct me if i'm wrong). I've had a look at apple's internal requests and believe this feature shouldn't be too difficult to implement. This is a feature that my company would quite like to use so we would be happy to file a pull request for the necessary changes assuming that this is sounds sensible? @KrauseFx

**This is how I would expect it to work (feel free to suggest any changes!):**

1. First off, there is currently no way to select a specific review, the current method for fetching reviews is:
 `reviews = Spaceship::Application.find(app_id).ratings.reviews()`

2. A method would have to be made that allows the user to select a specific review, eg.
 `review = Spaceship::Application.find(app_id).ratings.review(review_id)`

3. On top of this we would add a method that allows the review to be replied to, eg.
 `Spaceship::Application.find(app_id).ratings.review(review_id).respond(response_text)`

**Fetching a specific review**

This can be done via a simple get request to the following endpoint:

 https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/apps/${app_id}/platforms/ios/reviews?reviewId=${review_id}

**Replying to a review**

Apple uses 2 slightly different requests depending on whether you are updating a response or sending one for the first time. In order to make the method easier to use we would handle this from within the method:

First off we would check whether a developer response has already been sent, this can be done by checking the data sent from apple about the review

 A) If a developer response has not been sent then we would make a **post** request to https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/apps/${app_id}/platforms/ios/reviews/${review_id}/responses

 B) If a developer response has been sent (therefore we are updating the response) we would make a **put** request to https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/apps/${app_id}/platforms/ios/reviews/${review_id}/responses/${response_id}

 The payload for each of the above requests would be as follows (and yes it's weird that they require the review_id in both the url and the payload):
```
{
	"responseText": "Example Developer Response Text",
	"reviewId": "exampleReviewId"
}
```

Not sure what the standard is for error handling and method return values but presumably it would be one of the following:

1. The method return value is a boolean indicating success or failure
2. The method has a null return value and throws an error upon failure detailing what exactly went wrong
3. The method returns an object with a boolean property to indicate whether the request was successful and an additional property containing the error message where applicable

(would love some input on that last point)

Thanks for reading through all that and looking forward to hearing back from you!
_Henry_

_Originally posted by @hhoweson in https://github.com/fastlane/fastlane/discussions/18206_

**Comment by hhoweson** [comment]
Apologies if this is the wrong place to post this - just didn't know whether discussions were monitored or not so figured this might be a better place to get attention (:

**Comment by max-ott** [comment]
Feel free to open a pull request for this or hire a developer to work on this for you, this is still an open source project! 👍
