### ISSUE TITLE
Spaceship Documentation out of date

### ISSUE THREAD

**Issue by alexwasner** [fastlane/fastlane#18220]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
`all_build_train_numbers` is listed in the docs as a valid API on `Spaceship::ConnectAPI::App` but it is _only_ available on `Spaceship::Tunes::Application`. There are also missing docs on `get_builds`, `get_build_deliveries`,  `get_beta_app_localizations`, `get_beta_groups`, `create_beta_group` among others.

**Comment by max-ott** [comment]
Feel free to update it, this is still an open source project! 👍
