### ISSUE TITLE
Uploading to App Store via deliver fails <NoMethodError: undefined method `get_app_store_version_localizations' for nil:NilClass>

### ISSUE THREAD

**Issue by EssamOmar1994** [fastlane/fastlane#18248]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
we are trying to submit to app store production we already submitted to testflight the same version and when submitting to production we get this error "#<NoMethodError: undefined method `get_app_store_version_localizations' for nil:NilClass>
can't update languages - could not find editable version for IOS" . though this is not the first time we upload using fastlane to testflight and production

##### Command executed
fastlane deliver --api_key_path fastlane/temp.json --submit_for_review true --run_precheck_before_submit false --automatic_release true

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [01:37:11]: #<NoMethodError: undefined method `get_app_store_version_localizations' for nil:NilClass>
[01:37:11]: /Library/Ruby/Gems/2.6.0/gems/fastlane-2.174.0/deliver/lib/deliver/html_generator.rb:60:in `render'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.174.0/deliver/lib/deliver/html_generator.rb:16:in `run'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.174.0/deliver/lib/deliver/runner.rb:230:in `validate_html'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.174.0/deliver/lib/deliver/runner.rb:142:in `upload_metadata'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.174.0/deliver/lib/deliver/runner.rb:54:in `run'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.174.0/deliver/lib/deliver/commands_generator.rb:81:in `block (2 levels) in run'
/Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
/Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
/Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.174.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
/Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.174.0/deliver/lib/deliver/commands_generator.rb:186:in `run'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.174.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.174.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.174.0/bin/fastlane:23:in `<top (required)>'
/usr/local/bin/fastlane:23:in `load'
/usr/local/bin/fastlane:23:in `<main>'
[01:37:11]: Could not render HTML preview. Do you still want to continue?
y
[01:37:19]: Cannot find edit app store version... Retrying after 10 seconds (remaining: 4)
[01:37:30]: Cannot find edit app store version... Retrying after 10 seconds (remaining: 3)
[01:37:40]: Cannot find edit app store version... Retrying after 10 seconds (remaining: 2)
[01:37:50]: Cannot find edit app store version... Retrying after 10 seconds (remaining: 1)
[01:38:01]: Cannot find edit app store version... Retrying after 10 seconds (remaining: 0)

[!] Cannot update languages - could not find an editable version for 'IOS'

#######################################################################
# fastlane 2.175.0 is available. You are on 2.174.0.
# You should use the latest version.
# Please update using `sudo gem install fastlane`.
#######################################################################

2.175.0 mprovements
* [action] fix swiftlint validation block. (#18030) via Roger Oba
* [screengrab][actions] - fix android executable checking on windows (#18172) via Kartik Soneji
* [match] add documentation on how to use GitHub tokens (#18066) via Andres Riofrio
* [fastlane] remove "sudo" for gem install (#18189) via Satoshi Namai
* [match] improve copy when asking user for password in interactive mode. (#18199) via Roger Oba
* [deliver] sort screenshots naturally, in a human-friendly way. (#18200) via Roger Oba
* [spaceship] allow extra fields in API Key JSON file (#18235) via Alex
* [action] download_dsyms - fix latest build lookup by ignoring the version. (#18201) via Roger Oba
* [match] nuke use also token when cloning private repo (#18202) via Alisher Ulugbekov
* [spaceship] fix: use new analytics endpoint (#18216) via Valerio Castelli
* [app store connect] unified ENV vars for App Store Connect API Key (#18181) via Josh Holtz
* [fastlane_core] env_names - new config item option (#18173) via Josh Holtz
* [action] fix download dsyms with zero prefixed versions (#18042) via Daisuke Shimamoto

## Notes
- Added new unified environment variables for App Store Connect API Keys
  - `APP_STORE_CONNECT_API_KEY` and `APP_STORE_CONNECT_API_KEY_PATH` can be used in every action/tool that uses App Store Connect API Keys
  - Action specific environment variables will continue to keep working
  -  </pre>
</details>

### Environment

<details>
  <pre>
 #######################################################################
# fastlane 2.175.0 is available. You are on 2.174.0.
# You should use the latest version.
# Please update using `sudo gem install fastlane`.
#######################################################################

2.175.0 mprovements
* [action] fix swiftlint validation block. (#18030) via Roger Oba
* [screengrab][actions] - fix android executable checking on windows (#18172) via Kartik Soneji
* [match] add documentation on how to use GitHub tokens (#18066) via Andres Riofrio
* [fastlane] remove "sudo" for gem install (#18189) via Satoshi Namai
* [match] improve copy when asking user for password in interactive mode. (#18199) via Roger Oba
* [deliver] sort screenshots naturally, in a human-friendly way. (#18200) via Roger Oba
* [spaceship] allow extra fields in API Key JSON file (#18235) via Alex
* [action] download_dsyms - fix latest build lookup by ignoring the version. (#18201) via Roger Oba
* [match] nuke use also token when cloning private repo (#18202) via Alisher Ulugbekov
* [spaceship] fix: use new analytics endpoint (#18216) via Valerio Castelli
* [app store connect] unified ENV vars for App Store Connect API Key (#18181) via Josh Holtz
* [fastlane_core] env_names - new config item option (#18173) via Josh Holtz
* [action] fix download dsyms with zero prefixed versions (#18042) via Daisuke Shimamoto

## Notes
- Added new unified environment variables for App Store Connect API Keys
  - `APP_STORE_CONNECT_API_KEY` and `APP_STORE_CONNECT_API_KEY_PATH` can be used in every action/tool that uses App Store Connect API Keys
  - Action specific environment variables will continue to keep working
 </pre>
</details>

**Comment by EssamOmar1994** [comment]
I have included the output of fastlane env in the Environment section of the issue.

**Comment by max-ott** [comment]
I think the error message is pretty clear: `can't update languages - could not find editable version for IOS`

Can you please make sure that you have an editable version on the store?
