### ISSUE TITLE
Fastlane IOS build is crashing  immediately after the launch if build was distributed to Firebase Distribution

### ISSUE THREAD

**Issue by Luckygirlllll** [fastlane/fastlane#18256]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

IOS build is crashing  immediately after the launch if build was distributed to Firebase Distribution through Fastlane. 
I created adhoc build manually through Xcode without Fastlane and pushed it to Firebase Distribution and it works correctly. If I do build for TestFlight through Fastlane everything works correctly.

##### Command executed

fastlane testandbuild

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[18:17:50]: Successfully exported and compressed dSYM file
[18:17:50]: Successfully exported and signed the ipa file:
[18:17:50]: /Users/iryna/Documents/Projects/MyApp/output/MyApp.ipa
[18:17:50]: ---------------------------------------
[18:17:50]: --- Step: firebase_app_distribution ---
[18:17:50]: ---------------------------------------
[18:17:50]: Authenticating with --firebase_cli_token parameter
[18:17:50]: 🔐 Authenticated successfully.
[18:17:52]: ⌛ Uploading the IPA.
[18:18:01]: ✅ Uploaded the IPA.
[18:18:02]: ✅ Posted release notes.
[18:18:04]: ✅ Added testers/groups.
[18:18:04]: 🎉 App Distribution upload finished successfully.

+------+---------------------------+-------------+
|                fastlane summary                |
+------+---------------------------+-------------+
| Step | Action                    | Time (in s) |
+------+---------------------------+-------------+
| 1    | default_platform          | 0           |
| 2    | setup_circle_ci           | 0           |
| 3    | last_git_commit           | 0           |
| 4    | scan                      | 18          |
| 5    | match                     | 10          |
| 6    | gym                       | 108         |
| 7    | firebase_app_distribution | 13          |
+------+---------------------------+-------------+
</pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.7                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.7 (19H114)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.4                                                           |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Runs tests and build the app "
  lane :testandbuild do |options|
     commit = last_git_commit
     # Uncomment the line if you want to increment build number  
     # increment_build_number(xcodeproj: "MyApp.xcodeproj")
     scan(
	    scheme: "MyApp"
    )
    if(options[:branch] == "main")
      increment_build_number
      keyFilePath = File.join(Dir.pwd, "appStoreKey.p8")
      app_store_connect_api_key(
        key_id: options[:key_id],
        issuer_id: options[:issuer_id],
        key_filepath: keyFilePath,
        # duration: 1200,
        in_house: false,
      )
      match(type: "appstore", readonly: "false")
      build_app(
	      scheme: "MyApp",
        configuration: "Release"
      )
      upload_to_testflight(
        skip_waiting_for_build_processing: true
      )
    else
       match(type: "adhoc")
       gym(export_method: "ad-hoc", scheme: "MyApp", output_directory: "../output", configuration: "Debug")
       firebase_app_distribution(
               groups: 'dev-team',
               release_notes: "Branch: #{options[:branch]}. Message: #{commit[:message]}",
               firebase_cli_token: options[:firebase_cli_token]
       )
    end       
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("myapp.com") # The bundle identifier of your app
apple_id("i@myapp.com") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.175.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.2.5   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.3.0        |
| slack-notifier                            | 2.3.2        |
| atomos                                    | 0.1.3        |
| claide                                    | 1.0.3        |
| colored2                                  | 3.1.2        |
| nanaimo                                   | 0.3.0        |
| xcodeproj                                 | 1.19.0       |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.7.0        |
| terminal-table                            | 1.8.0        |
| plist                                     | 3.6.0        |
| public_suffix                             | 4.0.6        |
| addressable                               | 2.7.0        |
| multipart-post                            | 2.0.0        |
| word_wrap                                 | 1.0.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| artifactory                               | 3.0.15       |
| babosa                                    | 1.0.4        |
| colored                                   | 1.2          |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| excon                                     | 0.79.0       |
| faraday-net_http                          | 1.0.1        |
| ruby2_keywords                            | 0.0.4        |
| faraday                                   | 1.3.0        |
| unf_ext                                   | 0.0.7.7      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.0.0        |
| fastimage                                 | 2.2.2        |
| gh_inspector                              | 1.1.3        |
| mini_magick                               | 4.11.0       |
| naturally                                 | 2.2.1        |
| rubyzip                                   | 2.3.0        |
| security                                  | 0.1.3        |
| xcpretty-travis-formatter                 | 1.0.1        |
| dotenv                                    | 2.7.6        |
| bundler                                   | 1.17.2       |
| simctl                                    | 1.6.8        |
| jwt                                       | 2.2.2        |
| uber                                      | 0.1.0        |
| declarative                               | 0.0.20       |
| declarative-option                        | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| mini_mime                                 | 1.0.2        |
| multi_json                                | 1.15.0       |
| signet                                    | 0.14.1       |
| httpclient                                | 2.8.3        |
| google-api-client                         | 0.38.0       |
| google-cloud-env                          | 1.4.0        |
| google-cloud-errors                       | 1.0.1        |
| google-cloud-core                         | 1.5.0        |
| google-apis-core                          | 0.2.1        |
| google-apis-iamcredentials_v1             | 0.1.0        |
| digest-crc                                | 0.6.3        |
| google-cloud-storage                      | 1.30.0       |
| CFPropertyList                            | 3.0.3        |
| json                                      | 2.5.1        |
| os                                        | 1.1.1        |
| memoist                                   | 0.16.2       |
| googleauth                                | 0.15.1       |
| rexml                                     | 3.2.4        |
| webrick                                   | 1.7.0        |
| google-apis-storage_v1                    | 0.2.0        |
| rake                                      | 13.0.3       |
| emoji_regex                               | 3.2.2        |
| aws-eventstream                           | 1.1.0        |
| aws-sigv4                                 | 1.2.2        |
| aws-partitions                            | 1.428.0      |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.112.0      |
| aws-sdk-kms                               | 1.42.0       |
| aws-sdk-s3                                | 1.88.1       |
| forwardable                               | 1.2.0        |
| logger                                    | 1.3.0        |
| date                                      | 2.0.0        |
| stringio                                  | 0.0.2        |
| zlib                                      | 1.0.0        |
| ipaddr                                    | 1.2.2        |
| openssl                                   | 2.1.2        |
| ostruct                                   | 0.1.0        |
| strscan                                   | 1.0.0        |
| fileutils                                 | 1.1.0        |
| etc                                       | 1.0.1        |
| io-console                                | 0.4.7        |
| libxml-ruby                               | 3.1.0        |
| psych                                     | 3.1.0        |
| mutex_m                                   | 0.1.0        |
| fastlane-plugin-firebase_app_distribution | 0.2.5        |
</details>

**Comment by Luckygirlllll** [comment]
It looks like a problem relates to the fact that I use configuration 'Debug' for Firebase builds, if remove it,  Firebase build is working correctly. However, I need this configuration, because I'm using different type of certificates for Debug and Release build in CI. What can be a solution for this problem? why configuration "Debug" is not working?

**Comment by bguidolim** [comment]
In theory, Debug configuration means the compiler doesn't run optimizations and build the app exclusively for the current platform unless you have made a custom configuration for this.

An ad-hoc deployment doesn't mean you should avoid the Release configuration. So my suggestion to you is use Release config with ad-hoc certificates, and find another way to configure the certificates.

Fastlane was made to work out-of-the-box for simple cases (this is a personal opinion), if you need more advanced implementation, you have to do it by yourself, probably with the combination `match + update_code_signing_settings`.
