### ISSUE TITLE
Promoting a TestFlight build to App Store Review hangs on "Selecting build"

### ISSUE THREAD

**Issue by andi357** [fastlane/fastlane#18257]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

In our process, we always use an existing TestFlight build to be submitted to App Store review after final testings. Part of this process is to submit a specific existing TestFlight build to App Store review using Deliver. 

This worked perfectly until some months ago, but stopped working with a recent release (unfortunately I don't know which Fastlane version worked last).

When the deliver command is executed, everything works fine until the build becomes selected. This is where the script stops. The script **does not** confirm the selection of the build with the expected _"Successfully selected build"_ message.

I already tried changing the parameters that are given to the deliver command and reduced them to the minimum, but it always stops when it is about to select the build.

After executing the command all information is right in App Store Connect, even the build is correctly selected, but somehow Deliver does not recognize it, so it cannot "push the submit button" for us.

##### Command executed

```  
deliver(
    app_version: <version>,
    build_number: <build_number>,
    phased_release: <phased_release_option>
)
```

other options are taken from Deliverfile:

```
app_identifier <bundle_id>
submit_for_review true
automatic_release false
skip_screenshots true
skip_binary_upload true
platform "ios"
metadata_path "fastlane/metadata/appstore"
team_id <our_team_id>
dev_portal_team_id <our_dev_portal_id>
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
[20:15:23]: ---------------------
[20:15:23]: --- Step: deliver ---
[20:15:23]: ---------------------
[20:15:23]: Successfully loaded '/Users/#REDACTED#/fastlane/Deliverfile' 📄

+--------------------+----------------------------+
|  Detected Values from './fastlane/Deliverfile'  |
+--------------------+----------------------------+
| app_identifier     | #REDACTED#                 |
| submit_for_review  | true                       |
| automatic_release  | false                      |
| skip_screenshots   | true                       |
| skip_binary_upload | true                       |
| platform           | ios                        |
| metadata_path      | fastlane/metadata/appstore |
| team_id            | #REDACTED#                 |
| dev_portal_team_id | #REDACTED#                 |
+--------------------+----------------------------+

[20:15:23]: Login to App Store Connect (#REDACTED#)
[20:15:25]: Login successful

+--------------------------------------+----------------------------+
|                      deliver 2.175.0 Summary                      |
+--------------------------------------+----------------------------+
| app_version                          | 7.10.1                     |
| build_number                         | 50214                      |
| phased_release                       | true                       |
| screenshots_path                     | ./fastlane/screenshots     |
| username                             | #REDACTED#                 |
| app_identifier                       | #REDACTED#                 |
| platform                             | ios                        |
| edit_live                            | false                      |
| use_live_version                     | false                      |
| metadata_path                        | fastlane/metadata/appstore |
| skip_binary_upload                   | true                       |
| skip_screenshots                     | true                       |
| skip_metadata                        | false                      |
| skip_app_version_update              | false                      |
| force                                | false                      |
| overwrite_screenshots                | false                      |
| submit_for_review                    | true                       |
| reject_if_possible                   | false                      |
| automatic_release                    | false                      |
| reset_ratings                        | false                      |
| team_id                              | #REDACTED#                 |
| dev_portal_team_id                   | #REDACTED#                 |
| run_precheck_before_submit           | true                       |
| precheck_default_rule_level          | warn                       |
| ignore_language_directory_validation | false                      |
| precheck_include_in_app_purchases    | true                       |
+--------------------------------------+----------------------------+

[20:15:29]: Making sure the latest version on App Store Connect matches '7.10.1'...
[20:15:30]: '7.10.1' is the latest version on App Store Connect
[20:15:30]: Loading 'fastlane/metadata/appstore/de-DE/release_notes.txt'...
[20:15:31]: Verifying the upload via the HTML file can be disabled by either adding
[20:15:31]: `force true` to your Deliverfile or using `fastlane deliver --force`
/usr/local/lib/ruby/gems/2.7.0/gems/highline-1.7.10/lib/highline.rb:624: warning: Using the last argument as keyword parameters is deprecated
[20:15:31]: Does the Preview on path './fastlane/Preview.html' look okay for you? (y/n)
/usr/local/lib/ruby/gems/2.7.0/gems/highline-1.7.10/lib/highline.rb:624: warning: Using the last argument as keyword parameters is deprecated
                                                                                                                                             y
[20:15:34]: HTML file confirmed...
[20:15:37]: Will begin uploading metadata for '7.10.1' on App Store Connect
[20:15:37]: Uploading metadata to App Store Connect for version
[20:15:41]: Uploading metadata to App Store Connect for localized version 'de-DE'
[20:15:44]: Uploading app review information to App Store Connect
[20:15:45]: Running precheck before submitting to review, if you'd like to disable this check you can set run_precheck_before_submit to false
[20:15:45]: Making sure we pass precheck 👮‍♀️ 👮 before we submit  🛫

+--------------------------+-----------------------+
|           Summary for precheck 2.175.0           |
+--------------------------+-----------------------+
| default_rule_level       | warn                  |
| include_in_app_purchases | true                  |
| app_identifier           | #REDACTED#            |
| username                 | #REDACTED#            |
| platform                 | ios                   |
| team_id                  | #REDACTED#            |
| use_live                 | false                 |
+--------------------------+-----------------------+

[20:15:45]: Checking app for precheck rule violations
[20:15:59]: Reading in-app purchases. If you have a lot, this might take a while
[20:15:59]: You can disable IAP checking by setting the `include_in_app_purchases` flag to `false`
[20:16:00]: Done reading in-app purchases
[20:16:01]: ✅  Passed: No negative  sentiment
[20:16:01]: ✅  Passed: No placeholder text
[20:16:01]: ✅  Passed: No mentioning  competitors
[20:16:01]: ✅  Passed: No future functionality promises
[20:16:01]: ✅  Passed: No words indicating test content
[20:16:01]: ✅  Passed: No curse words
[20:16:01]: ✅  Passed: No words indicating your IAP is free
[20:16:01]: ✅  Passed: Incorrect, or missing copyright date
[20:16:01]: ✅  Passed: No broken urls
[20:16:01]: precheck 👮‍♀️ 👮  finished without detecting any potential problems 🛫
[20:16:01]: Selecting existing build-number: 50214
[20:16:02]: Selecting build 7.10.1 (50214)...

^C <--- here we cancel with CTRL+C as the script stucks. 

+----------------+---------------------+
|             Lane Context             |
+----------------+---------------------+
| PLATFORM_NAME  |                     |
| LANE_NAME      | submit_to_app_store |
| VERSION_NUMBER | 7.10.1              |
| BUILD_NUMBER   | 50214               |
+----------------+---------------------+

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | ensure_bundle_exec         | 0           |
| 3    | git_branch                 | 0           |
| 4    | get_version_number         | 0           |
| 5    | get_build_number           | 0           |
| 6    | git_branch                 | 0           |
| 7    | deliver                    | 50          |
+------+----------------------------+-------------+

[20:16:14]: fastlane finished with errors

Cancelled... use --verbose to show the stack trace
</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.2.1                                      |
| Ruby                        | 2.7.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | /usr/local/lib/ruby/gems/2.7.0/bin/fastlane |
| Host                        | macOS 11.2.1 (20D75)                        |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.7.2/lib            |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.4                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.175.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.4.0        |
| bundler                       | 2.2.7        |
| uri                           | 0.10.0       |
| rake                          | 13.0.3       |
| CFPropertyList                | 3.0.3        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| artifactory                   | 3.0.15       |
| atomos                        | 0.1.3        |
| aws-eventstream               | 1.1.0        |
| aws-partitions                | 1.428.0      |
| aws-sigv4                     | 1.2.2        |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.112.0      |
| aws-sdk-kms                   | 1.42.0       |
| aws-sdk-s3                    | 1.88.1       |
| babosa                        | 1.0.4        |
| claide                        | 1.0.3        |
| colored                       | 1.2          |
| colored2                      | 3.1.2        |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| digest-crc                    | 0.6.3        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| dotenv                        | 2.7.6        |
| emoji_regex                   | 3.2.2        |
| excon                         | 0.79.0       |
| faraday-net_http              | 1.0.1        |
| multipart-post                | 2.0.0        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.2        |
| gh_inspector                  | 1.1.3        |
| jwt                           | 2.2.2        |
| memoist                       | 0.16.2       |
| multi_json                    | 1.15.0       |
| os                            | 1.1.1        |
| signet                        | 0.14.1       |
| googleauth                    | 0.15.1       |
| httpclient                    | 2.8.3        |
| mini_mime                     | 1.0.2        |
| uber                          | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| google-api-client             | 0.38.0       |
| rexml                         | 3.2.4        |
| webrick                       | 1.7.0        |
| google-apis-core              | 0.2.1        |
| google-apis-iamcredentials_v1 | 0.1.0        |
| google-apis-storage_v1        | 0.2.0        |
| google-cloud-env              | 1.4.0        |
| google-cloud-errors           | 1.0.1        |
| google-cloud-core             | 1.5.0        |
| google-cloud-storage          | 1.30.0       |
| json                          | 2.5.1        |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| plist                         | 3.6.0        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| simctl                        | 1.6.8        |
| slack-notifier                | 2.3.2        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| word_wrap                     | 1.0.0        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| xcpretty-travis-formatter     | 1.0.1        |
</details>

*generated on:* **2021-02-22**
</details>

**Comment by minuscorp** [comment]
If it gets suck at some point of the process you can Ctrl+c from the terminal to end the process and you'll get the traceback of the interruption signal so we have more information about the issue.

Thanks!

**Comment by max-ott** [comment]
Apple changed a few bits and piece when it comes to the build section and TestFlight (i.e. there is no more "builds section"). My guess it that this change broke a few fastlane things as well.

**Comment by andi357** [comment]
@minuscorp Sorry for the delay, here is the full stacktrace:

```
INFO [2021-03-26 18:01:51.82]: precheck 👮‍♀️ 👮  finished without detecting any potential problems 🛫
INFO [2021-03-26 18:01:52.22]: Selecting existing build-number: 50220
INFO [2021-03-26 18:01:53.65]: Selecting build 7.11.0 (50220)...
^C
WARN [2021-03-26 18:02:05.18]: Lane Context:
INFO [2021-03-26 18:02:05.18]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"submit_to_app_store", :GIT_REPO_WAS_CLEAN_ON_START=>true, :VERSION_NUMBER=>"7.11.0", :BUILD_NUMBER=>"50220"}
INFO [2021-03-26 18:02:05.18]: Successfully generated documentation at path '/#REDACTED#/fastlane/README.md'

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | ensure_bundle_exec         | 0           |
| 3    | ensure_git_status_clean    | 0           |
| 4    | git_branch                 | 0           |
| 5    | get_version_number         | 0           |
| 6    | get_build_number           | 0           |
| 7    | git_branch                 | 0           |
| 8    | deliver                    | 58          |
+------+----------------------------+-------------+

ERROR [2021-03-26 18:02:05.19]: fastlane finished with errors
Traceback (most recent call last):
	81: from /usr/local/opt/ruby/bin/bundle:23:in `<main>'
	80: from /usr/local/opt/ruby/bin/bundle:23:in `load'
	79: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/exe/bundle:37:in `<top (required)>'
	78: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	77: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/exe/bundle:49:in `block in <top (required)>'
	76: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/cli.rb:24:in `start'
	75: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	74: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/cli.rb:30:in `dispatch'
	73: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	72: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	71: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	70: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/cli.rb:494:in `exec'
	69: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/cli/exec.rb:28:in `run'
	68: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/cli/exec.rb:63:in `kernel_load'
	67: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.7/lib/bundler/cli/exec.rb:63:in `load'
	66: from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `<top (required)>'
	65: from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `load'
	64: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/bin/fastlane:23:in `<top (required)>'
	63: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	62: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	61: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	60: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	59: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	58: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	57: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	56: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	55: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	54: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	53: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	52: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	51: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	50: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	49: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	48: from Fastfile:221:in `block in parsing_binding'
	47: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	46: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	45: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	44: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	43: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	42: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	41: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	40: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:18:in `run'
	39: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/deliver/lib/deliver/runner.rb:68:in `run'
	38: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/deliver/lib/deliver/runner.rb:202:in `submit_for_review'
	37: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/deliver/lib/deliver/submit_for_review.rb:20:in `submit!'
	36: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/deliver/lib/deliver/submit_for_review.rb:51:in `select_build'
	35: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/spaceship/lib/spaceship/connect_api/models/app_store_version.rb:205:in `select_build'
	34: from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/forwardable.rb:235:in `patch_app_store_version_with_build'
	33: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:922:in `patch_app_store_version_with_build'
	32: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/spaceship/lib/spaceship/connect_api/api_client.rb:128:in `patch'
	31: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/spaceship/lib/spaceship/connect_api/api_client.rb:162:in `with_asc_retry'
	30: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/spaceship/lib/spaceship/connect_api/api_client.rb:129:in `block in patch'
	29: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/spaceship/lib/spaceship/client.rb:726:in `request'
	28: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/spaceship/lib/spaceship/client.rb:882:in `send_request'
	27: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/spaceship/lib/spaceship/client.rb:646:in `with_retry'
	26: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/spaceship/lib/spaceship/client.rb:883:in `block in send_request'
	25: from /usr/local/lib/ruby/gems/2.7.0/gems/faraday-1.3.0/lib/faraday/connection.rb:279:in `patch'
	24: from /usr/local/lib/ruby/gems/2.7.0/gems/faraday-1.3.0/lib/faraday/connection.rb:492:in `run_request'
	23: from /usr/local/lib/ruby/gems/2.7.0/gems/faraday-1.3.0/lib/faraday/rack_builder.rb:154:in `build_response'
	22: from /usr/local/lib/ruby/gems/2.7.0/gems/faraday_middleware-1.0.0/lib/faraday_middleware/response_middleware.rb:36:in `call'
	21: from /usr/local/lib/ruby/gems/2.7.0/gems/faraday_middleware-1.0.0/lib/faraday_middleware/response_middleware.rb:36:in `call'
	20: from /usr/local/lib/ruby/gems/2.7.0/gems/faraday-cookie_jar-0.0.7/lib/faraday/cookie_jar.rb:24:in `call'
	19: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/spaceship/lib/spaceship/helper/rels_middleware.rb:17:in `call'
	18: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/spaceship/lib/spaceship/stats_middleware.rb:45:in `call'
	17: from /usr/local/lib/ruby/gems/2.7.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:64:in `call'
	16: from /usr/local/lib/ruby/gems/2.7.0/gems/faraday-1.3.0/lib/faraday/adapter.rb:60:in `connection'
	15: from /usr/local/lib/ruby/gems/2.7.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:66:in `block in call'
	14: from /usr/local/lib/ruby/gems/2.7.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:122:in `perform_request'
	13: from /usr/local/lib/ruby/gems/2.7.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:131:in `request_with_wrapped_block'
	12: from /usr/local/lib/ruby/gems/2.7.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:146:in `request_via_request_method'
	11: from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/net/http.rb:933:in `start'
	10: from /usr/local/lib/ruby/gems/2.7.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:152:in `block in request_via_request_method'
	 9: from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/net/http.rb:1492:in `request'
	 8: from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/net/http.rb:1519:in `transport_request'
	 7: from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/net/http.rb:1519:in `catch'
	 6: from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/net/http.rb:1528:in `block in transport_request'
	 5: from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/net/http/response.rb:31:in `read_new'
	 4: from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/net/http/response.rb:42:in `read_status_line'
	 3: from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/net/protocol.rb:201:in `readline'
	 2: from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/net/protocol.rb:191:in `readuntil'
	 1: from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/net/protocol.rb:217:in `rbuf_fill'
/usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/net/protocol.rb:217:in `wait_readable': Interrupt
```

**Comment by minuscorp** [comment]
Have you tried to run your lane with `DEBUG=1` environment variable set? It seems that the connection hangs, so maybe trying with another network might work as well.
