### ISSUE TITLE
Documentation for using Fastlane with Unity in a CI Context

### ISSUE THREAD

**Issue by BenWoodford** [fastlane/fastlane#18265]
<snip>

I've just removed the entire issue as I once again resolved it on my own after finding certain bits and pieces that worked for me.

Instead, I'm switching this issue to a new proposal: documentation for using Fastlane's workflow with Unity in a CI context. I've spent quite a while scouring for bits of information on how to use Fastlane appropriately in a scenario where the Xcode project is ephemeral (as your CI would generate a clean Xcode project every build) so it'd be great to have some documentation for it.

Of note:

- A dummy folder for Fastlane may be needed for generating all the files
- Fastlane files (Fastfile, Appfile, Matchfile, Pluginfile) should all be stored in a folder inside the root of the Unity project and copied over post-build (snippet below for the script for that, which should be in an `Editor` folder inside Unity)
- Copy over your Gemfile and Gemfile.lock
- Run `fastlane install_plugins` to install the plugins from the Pluginfile/Gemfile
- There's quite a few odd little things you have to do to pre-process the Xcode project and prep it for a build, bear with while I write that up in due course

Unity build post-process script to copy Fastlane data:

```
    public class FastlanePostBuild : IPostprocessBuildWithReport // Will execute after XCode project is built
    {
#if UNITY_IOS
            ProcessFastlane(report.summary.platform, report.summary.outputPath);
#endif
        }

        static void ProcessFastlane(BuildTarget target, string outputPath)
        {
            if(target == BuildTarget.iOS)
            {
                if (!Directory.Exists(outputPath + "/fastlane"))
                    Directory.CreateDirectory(outputPath + "/fastlane");

                File.Copy("output-assets/ios/fastlane/Appfile", outputPath + "/fastlane/Appfile", true);
                File.Copy("output-assets/ios/fastlane/Fastfile", outputPath + "/fastlane/Fastfile", true);
                File.Copy("output-assets/ios/fastlane/Matchfile", outputPath + "/fastlane/Matchfile", true);

                if(File.Exists("output-assets/ios/fastlane/Pluginfile"))
                    File.Copy("output-assets/ios/fastlane/Pluginfile", outputPath + "/fastlane/Pluginfile", true);

                if (File.Exists("output-assets/ios/Gemfile"))
                    File.Copy("output-assets/ios/Gemfile", outputPath + "/Gemfile", true);

                if (File.Exists("output-assets/ios/Gemfile.lock"))
                    File.Copy("output-assets/ios/Gemfile.lock", outputPath + "/Gemfile.lock", true);

                Debug.Log("Copied Appfile, MatchFile, Gemfile(.lock), Pluginfile and Fastfile to " + outputPath);
            }
        }
    }
```

A lane for building on a CI from a Unity-generated, untouched Xcode project, this is quite a basic one and while it includes `match` usage it doesn't deal with TestFlight, API Keys, etc. Of note is disabling of automatic code signing, manually assigning the signing identity and profile, and also specifying it exactly in `gym`

```
  lane :ci do
    setup_ci

    match(
      type: "appstore",
      readonly: true
    )

    disable_automatic_code_signing(
      path: "Unity-iPhone.xcodeproj"
    )

    update_project_provisioning(
      xcodeproj: "Unity-iPhone.xcodeproj",
      target_filter: "Unity-iPhone",
      profile: ENV["sigh_#{ENV['BUNDLE_IDENTIFIER']}_appstore_profile-path"],
      code_signing_identity: "Apple Distribution: #{ENV['APPLE_TEAM_NAME']} (#{ENV['APPLE_TEAM_ID']})"
    )

    gym(
      project: "Unity-iPhone.xcodeproj",
      skip_profile_detection: true,
      codesigning_identity: "Apple Distribution: #{ENV['APPLE_TEAM_NAME']} (#{ENV['APPLE_TEAM_ID']})",
      scheme: "Unity-iPhone",
      export_method: "app-store",
      export_options: {
        method: "app-store",
        provisioningProfiles: {
          ENV["BUNDLE_IDENTIFIER"] => "match AppStore #{ENV['BUNDLE_IDENTIFIER']}",
        }
      }
    )
  end
```

**Comment by max-ott** [comment]
Please open a pull request instead of the issue. Here it will simply get closed after a specific amount of time.
