### ISSUE TITLE
Deliver Pulls Build Number From IPA If It Exists 

### ISSUE THREAD

**Issue by mccarron** [fastlane/fastlane#18269]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When calling Deliver with a simple command of:
`deliver(app_version: VERSION_NUMBER)` 

I was expecting it to pull the latest build number from Appstore Connect but it was pulling `1000` for some reason. Thusly it was waiting forever for the build to process.

```
Waiting for processing on... app_id: XXXXX, app_version: VERSION_NUMBER, build_version: 1000, platform: IOS
WARN [2021-02-23 18:36:23.36]: Read more information on why this build isn't showing up yet - https://github.com/fastlane/fastlane/issues/14997
INFO [2021-02-23 18:36:23.36]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
INFO [2021-02-23 18:36:38.76]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
INFO [2021-02-23 18:36:54.35]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
INFO [2021-02-23 18:37:09.68]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
INFO [2021-02-23 18:37:25.02]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
```

Appears I had a locally built `APPNAME.ipa` in my folder and it was pulling 1000 from that and sending it to Apple as a filter instead of using the value from Apple. 

##### Command executed
`bundle exec fastlane release`

which runs

`deliver(app_version: VERSION_NUMBER)` 

@joshdholtz thinks he knows where the bug is, so asked me to file this. 

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>N/A </pre>
</details>

### Environment

<details>
  <pre>N/A </pre>
</details>

**Comment by max-ott** [comment]
As far as I know Apple broke the whole build pipeline stuff with their App Store Connect changes. There is no easy way to find out the latest build info anymore (even with the API).

**Comment by mccarron** [comment]
> As far as I know Apple broke the whole build pipeline stuff with their App Store Connect changes. There is no easy way to find out the latest build info anymore (even with the API).

Hmm that's strange as it does pull the right build info now, just in this case Fastlane is pulling a version off a local file as input to query Apple when that wasn't defined as the input so it would never return the right build. It works fine with that IPA file not existing.

@joshdholtz said he knows where the bug was, and asked me to create the ticket.
