### ISSUE TITLE
undefined method `key?' for nil

### ISSUE THREAD

**Issue by lyf571321556** [fastlane/fastlane#18271]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Issue Description
I am using a fastlane API Key JSON to upload our builds to TestFlight as a way around 2FA that is being required by Apple by Feb 2021.
The build successfully uploads, then the build step will fail afterwards with this error: [!] undefined method `key?' for nil

Command executed
pilot(
            skip_submission: true,
            skip_waiting_for_build_processing: true,
            api_key_path: fastlane/xxx.json
        )

API JSON looks like:
{ "key_id": "key id", "issuer_id": "issuer ID", "key": "-----BEGIN PRIVATE KEY-----\nOur key\n-----END PRIVATE KEY-----" }

##### Complete output when running fastlane, including the stack trace and command used
INFO [2021-02-24 09:14:49.52]: --- Step: pilot ---
INFO [2021-02-24 09:14:49.52]: -------------------
WARN [2021-02-24 09:14:49.53]: Lane Context:
INFO [2021-02-24 09:14:49.53]: {:DEFAULT_PLATFORM=>:ios, :KEYCHAIN_PATH=>"~/Library/Keychains/fastlane_tmp_keychain", :ORIGINAL_DEFAULT_KEYCHAIN=>"\"/Users/runner/Library/Keychains/login.keychain-db\"", :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios release", :SIGH_PROFILE_TYPE=>"app-store", :MATCH_PROVISIONING_PROFILE_MAPPING=>{"ai.ones.project.ios"=>"ONES.AI Project iOS Distribution"}, :BUILD_NUMBER=>"298", :IPA_OUTPUT_PATH=>"/Users/runner/work/ai_one_flutter/ai_one_flutter/ios/fastlane/ipas/ones_mobile.ipa", :XCODEBUILD_ARCHIVE=>"/Users/runner/Library/Developer/Xcode/Archives/2021-02-24/ones_mobile 2021-02-24 09.08.31.xcarchive", :DSYM_OUTPUT_PATH=>"/Users/runner/work/ai_one_flutter/ai_one_flutter/ios/fastlane/ipas/ones_mobile.app.dSYM.zip"}
INFO [2021-02-24 09:14:49.53]: Successfully generated documentation at path '/Users/runner/work/ai_one_flutter/ai_one_flutter/ios/fastlane/README.md'

+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | default_platform                                              | 0           |
| 2    | setup_travis                                                  | 0           |
| 3    | xcversion                                                     | 34          |
| 4    | number_of_commits                                             | 0           |
| 5    | flutter build ios --no-tree-shake-icons --no-codesign --relea | 456         |
| 6    | match                                                         | 3           |
| 7    | set_info_plist_value                                          | 0           |
| 8    | number_of_commits                                             | 0           |
| 9    | increment_build_number                                        | 6           |
| 10   | gym                                                           | 382         |
| 11   | cp /Users/runner/work/ai_one_flutter/ai_one_flutter/ios/fastl | 3           |
| 12   | ls -lh                                                        | 0           |
| 💥   | pilot                                                         | 0           |
+------+---------------------------------------------------------------+-------------+

DEBUG [2021-02-24 09:14:49.80]: All plugins are up to date
ERROR [2021-02-24 09:14:49.80]: fastlane finished with errors
bundler: failed to load command: fastlane (/usr/local/lib/ruby/gems/2.7.0/bin/fastlane)

/usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/spaceship/lib/spaceship/connect_api/token.rb:32:in `from_json_file': \e[31m[!] undefined method `key?' for nil:NilClass\e[0m (NoMethodError)
Looking for related GitHub issues on fastlane/fastlane...
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/pilot/lib/pilot/manager.rb:34:in `api_token'
Search query: undefined method `key?' for nil
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/pilot/lib/pilot/manager.rb:20:in `login'

	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/pilot/lib/pilot/manager.rb:16:in `start'
URL: https://api.github.com/search/issues?q=undefined%20method%20%60key%3F%27%20for%20nil+repo:fastlane/fastlane
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/pilot/lib/pilot/build_manager.rb:17:in `upload'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:158:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `load'
	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/cli/exec.rb:63:in `load'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/cli/exec.rb:63:in `kernel_load'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/cli/exec.rb:28:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/cli.rb:494:in `exec'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/cli.rb:30:in `dispatch'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/cli.rb:24:in `start'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/exe/bundle:49:in `block in <top (required)>'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/exe/bundle:37:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.7.0/bin/bundle:23:in `load'
	from /usr/local/lib/ruby/gems/2.7.0/bin/bundle:23:in `<main>'
/usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/spaceship/lib/spaceship/connect_api/token.rb:32:in `from_json_file': undefined method `key?' for nil:NilClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/pilot/lib/pilot/manager.rb:34:in `api_token'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/pilot/lib/pilot/manager.rb:20:in `login'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/pilot/lib/pilot/manager.rb:16:in `start'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/pilot/lib/pilot/build_manager.rb:17:in `upload'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:158:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.175.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `load'
	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/cli/exec.rb:63:in `load'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/cli/exec.rb:63:in `kernel_load'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/cli/exec.rb:28:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/cli.rb:494:in `exec'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/cli.rb:30:in `dispatch'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/cli.rb:24:in `start'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/exe/bundle:49:in `block in <top (required)>'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/exe/bundle:37:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.7.0/bin/bundle:23:in `load'
	from /usr/local/lib/ruby/gems/2.7.0/bin/bundle:23:in `<main>'
➡️  undefined method `key?' for nil
    https://github.com/fastlane/fastlane/issues/18271 [open] 1 💬
    28 minutes ago

➡️  Undefined method `status' for nil:NilClass (NoMethodError)
    https://github.com/fastlane/fastlane/issues/17910 [open] 26 💬
    16 hours ago

➡️  undefined method `id' for nil
    https://github.com/fastlane/fastlane/issues/17818 [open] 2 💬
    3 weeks ago

and 291 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60key%3F%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
DEBUG [2021-02-24 09:14:50.70]: All plugins are up to date
Error: Process completed with exit code 1.
### Environment
fastlane env:
✅ fastlane environment ✅

===Fastlane env output===
[08:26:27]: Sending anonymous analytics information
[08:26:27]: Learn more at https://docs.fastlane.tools/#metrics
[08:26:27]: No personal or sensitive data is sent.
[08:26:27]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
[08:26:27]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.15.7                                          |
| Ruby                        | 2.7.2                                            |
| Bundler?                    | true                                             |
| Git                         | git version 2.30.1                               |
| Installation Source         | /usr/local/lib/ruby/gems/2.7.0/bin/fastlane      |
| Host                        | Mac OS X 10.15.7 (19H512)                        |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.7/2.7.2/lib             |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                       |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode_12.3.app/Contents/Developer/ |
| Xcode Version               | 12.3                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.175.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-appcenter | 1.11.0  | ✅ Up-To-Date  |
| fastlane-plugin-pgyer     | 0.2.2   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.4.0        |
| bundler                       | 2.2.9        |
| uri                           | 0.10.0       |
| rake                          | 13.0.3       |
| CFPropertyList                | 3.0.3        |
| concurrent-ruby               | 1.1.6        |
| i18n                          | 0.9.5        |
| minitest                      | 5.14.1       |
| thread_safe                   | 0.3.6        |
| tzinfo                        | 1.2.7        |
| activesupport                 | 4.2.11.3     |
| public_suffix                 | 2.0.5        |
| addressable                   | 2.7.0        |
| httpclient                    | 2.8.3        |
| json                          | 2.5.1        |
| algoliasearch                 | 1.27.3       |
| artifactory                   | 3.0.15       |
| atomos                        | 0.1.3        |
| aws-eventstream               | 1.1.0        |
| aws-partitions                | 1.429.0      |
| aws-sigv4                     | 1.2.2        |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.112.0      |
| aws-sdk-kms                   | 1.42.0       |
| aws-sdk-s3                    | 1.88.1       |
| babosa                        | 1.0.4        |
| claide                        | 1.0.3        |
| fuzzy_match                   | 2.0.4        |
| nap                           | 1.1.0        |
| netrc                         | 0.11.0       |
| ffi                           | 1.13.1       |
| ethon                         | 0.12.0       |
| typhoeus                      | 1.4.0        |
| cocoapods-core                | 1.9.3        |
| cocoapods-deintegrate         | 1.0.4        |
| cocoapods-downloader          | 1.4.0        |
| cocoapods-plugins             | 1.0.0        |
| cocoapods-search              | 1.0.0        |
| cocoapods-stats               | 1.1.0        |
| cocoapods-trunk               | 1.5.0        |
| cocoapods-try                 | 1.2.0        |
| colored2                      | 3.1.2        |
| escape                        | 0.0.4        |
| fourflusher                   | 2.3.1        |
| gh_inspector                  | 1.1.3        |
| molinillo                     | 0.6.6        |
| ruby-macho                    | 1.4.0        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| cocoapods                     | 1.9.3        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| digest-crc                    | 0.6.3        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| dotenv                        | 2.7.6        |
| emoji_regex                   | 3.2.2        |
| excon                         | 0.79.0       |
| faraday-net_http              | 1.0.1        |
| multipart-post                | 2.0.0        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.2        |
| jwt                           | 2.2.2        |
| memoist                       | 0.16.2       |
| multi_json                    | 1.15.0       |
| os                            | 1.1.1        |
| signet                        | 0.14.1       |
| googleauth                    | 0.15.1       |
| mini_mime                     | 1.0.2        |
| uber                          | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| google-api-client             | 0.38.0       |
| rexml                         | 3.2.4        |
| webrick                       | 1.7.0        |
| google-apis-core              | 0.2.1        |
| google-apis-iamcredentials_v1 | 0.1.0        |
| google-apis-storage_v1        | 0.2.0        |
| google-cloud-env              | 1.4.0        |
| google-cloud-errors           | 1.0.1        |
| google-cloud-core             | 1.5.0        |
| google-cloud-storage          | 1.30.0       |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| plist                         | 3.6.0        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| simctl                        | 1.6.8        |
| slack-notifier                | 2.3.2        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| word_wrap                     | 1.0.0        |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| xcpretty-travis-formatter     | 1.0.1        |
| fastlane-plugin-appcenter     | 1.11.0       |
| fastlane-plugin-pgyer         | 0.2.2        |
| xcode-install                 | 2.6.6        |
</details>

*generated on:* **2021-02-24**
</details>

**Comment by lyf571321556** [comment]
same issue on  lastest fastlane version ;

**Comment by DTRobertson9194** [comment]
Seeing this same issue on our build jobs leveraging **distribute_external** argument.  
A remedial fix for this though is noted by removing the **distribute_external** and adding **skip_waiting_for_build_processing** in place.  I'm leveraging the skip arg for a beta app but our tester groups wanted the external method which is where failure is noted.   

Hope this helps!

**Comment by lyf571321556** [comment]
I solved it by doing:
```
app_store_connect_api_key(
  key_id: "#{ENV["KEY_ID"]}",
  issuer_id: "#{ENV["ISSUER_ID"]}",
  key_content: "plain key content or base64(key content) from p8 file",
  is_key_content_base64: false/true,
  in_house: false,
)
```
