### ISSUE TITLE
Expose new Swift toolchain flag for Xcode 7.3

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1828]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/1484989?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @jcampbell05 - Imported from <a href='https://github.com/fastlane/gym/issues/187'>fastlane/gym#187</a>
        </td>
      </tr>
    </table>

Re-duplication of https://github.com/fastlane/fastlane/issues/1079

In the new `xcodebuild` we will be able to specify which version of swift we wish to use. This is just a note to add support for it, once Xcode 7.3 is released.

We should add an extra flag for `gym` which will pass the toolchain of swift to use, (Unless Gym just accepts the same flags that xcodebuild does).

We should expose this new flag to the `gym` action inside of fastlane.

**Comment by KrauseFx** [comment]
Sorry for not coming back to this earlier, is this issue still happening with the latest _fastlane_ release?
