### ISSUE TITLE
[Gym] ARCHIVE FAILED when the provisioning profile is expired in the Enterprise account

### ISSUE THREAD

**Issue by Thangaraj-M** [fastlane/fastlane#18304]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

If the provisioning profile is expired for the bundle id in enterprise account, then the new profile is not created when calling the Sigh. Then when calling the gym,  the build is happening with the expired profile itself and it is failed.

##### Command executed

fastlane build

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
INFO [2021-02-28 23:19:13.70]: ▸ [35m** ARCHIVE FAILED **[0m
** ARCHIVE FAILED **
ERROR [2021-02-28 23:19:14.11]: [31mExit status: 65[0m
INFO [2021-02-28 23:19:14.21]: 
WARN [2021-02-28 23:19:14.21]: [33mMaybe the error shown is caused by using the wrong version of Xcode[0m
WARN [2021-02-28 23:19:14.21]: [33mFound multiple versions of Xcode in '/Applications/'[0m
WARN [2021-02-28 23:19:14.21]: [33mMake sure you selected the right version for your project[0m
WARN [2021-02-28 23:19:14.22]: [33mThis build process was executed using '/Applications/Xcode12.app'[0m
WARN [2021-02-28 23:19:14.22]: [33mIf you want to update your Xcode path, either[0m
INFO [2021-02-28 23:19:14.22]: 
INFO [2021-02-28 23:19:14.22]: - Specify the Xcode version in your Fastfile
INFO [2021-02-28 23:19:14.22]: ▸ [35mxcversion(version: "8.1") # Selects Xcode 8.1.0[0m
INFO [2021-02-28 23:19:14.22]: 
INFO [2021-02-28 23:19:14.22]: - Specify an absolute path to your Xcode installation in your Fastfile
INFO [2021-02-28 23:19:14.22]: ▸ [35mxcode_select "/Applications/Xcode8.app"[0m
INFO [2021-02-28 23:19:14.22]: 
INFO [2021-02-28 23:19:14.22]: - Manually update the path using
INFO [2021-02-28 23:19:14.22]: ▸ [35msudo xcode-select -s /Applications/Xcode.app[0m
INFO [2021-02-28 23:19:14.22]: 

+---------------+---------------------------+
|             [32m[33mBuild environment[0m             |
+---------------+---------------------------+
| xcode_path    | /Applications/Xcode12.app |
| gym_version   | 2.176.0                   |
| export_method | enterprise                |
| sdk           | iPhoneOS14.0.sdk          |
+---------------+---------------------------+

INFO [2021-02-28 23:19:14.38]: ▸ [35mnote: Planning build[0m
INFO [2021-02-28 23:19:14.38]: ▸ [35mnote: Constructing build description[0m
INFO [2021-02-28 23:19:14.38]: ▸ [35merror: Provisioning profile "*************_provisiong_profile" expired on Feb 18, 2021. (in target 'Mobile' from project 'Mobile')[0m
INFO [2021-02-28 23:19:14.38]: 
ERROR [2021-02-28 23:19:14.38]: [31m⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error[0m
WARN [2021-02-28 23:19:14.38]: [33m📋  For the complete and more detailed error log, check the full log at:[0m
WARN [2021-02-28 23:19:14.38]: [33m📋  fastlane/logs/Mobile-Mobile.log[0m
INFO [2021-02-28 23:19:14.38]: 
ERROR [2021-02-28 23:19:14.38]: [31mLooks like fastlane ran into a build/archive error with your project[0m
ERROR [2021-02-28 23:19:14.38]: [31mIt's hard to tell what's causing the error, so we wrote some guides on how[0m
ERROR [2021-02-28 23:19:14.38]: [31mto troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/[0m
ERROR [2021-02-28 23:19:14.38]: [31mBefore submitting an issue on GitHub, please follow the guide above and make[0m
ERROR [2021-02-28 23:19:14.38]: [31msure your project is set up correctly.[0m
ERROR [2021-02-28 23:19:14.38]: [31mfastlane uses `xcodebuild` commands to generate your binary, you can see the[0m
ERROR [2021-02-28 23:19:14.38]: [31mthe full commands printed out in yellow in the above log.[0m
ERROR [2021-02-28 23:19:14.38]: [31mMake sure to inspect the output above, as usually you'll find more error information there[0m
INFO [2021-02-28 23:19:14.38]: 
Init: {:error_info=>"** ARCHIVE FAILED **\n"}
</pre>
</details>

### Environment

<details>
  <pre>
[22:16:57]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[22:16:58]: Generating fastlane environment output, this might take a few seconds...

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                         |
| --------------------------- | --------------------------------------------- |
| OS                          | 10.15.5                                       |
| Ruby                        | 2.6.3                                         |
| Bundler?                    | false                                         |
| Git                         | git version 2.24.3 (Apple Git-128)            |
| Installation Source         | ~/.rvm/rubies/ruby-2.6.3/bin/fastlane         |
| Host                        | Mac OS X 10.15.5 (19F101)                     |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.3/lib                  |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                   |
| Is contained                | false                                         |
| Is homebrew                 | false                                         |
| Is installed via Fabric.app | false                                         |
| Xcode Path                  | /Applications/Xcode12.app/Contents/Developer/ |
| Xcode Version               | 12.0                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.176.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.17.3       |
| etc                       | 1.0.1        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.18.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| artifactory               | 3.0.15       |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.76.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| naturally                 | 2.2.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.1        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-storage      | 1.27.0       |
| emoji_regex               | 3.0.0        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.355.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.104.3      |
| aws-sdk-kms               | 1.36.0       |
| aws-sdk-s3                | 1.78.0       |
| json                      | 2.3.1        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

 </pre>
</details>

**Comment by Thangaraj-M** [comment]
After provisioning profile expired, the status is showing as Active in the developer account. If we open that profile manually once in the developer account, after that the status is changed to Expired. 
In the Fastlane, provisioning profile validity is verified based on status only. In the developer account, the status is showing Active for the expired profile also until we manually open the profile once. 
So the expired date also need to be validate when checking the profile validity in the Sigh.

**Comment by Dinsen** [comment]
@max-ott this is a Match/Cert/Sigh issue. (dunno where the logic is yet 😆)
I see the same issue sometimes, but also see other issues since we use the API Key.
Will create a new issue then I have investigated more..

**Comment by markst** [comment]
Seems as if Gym is not updating the XCode project `PROVISIONING_PROFILE_SPECIFIER` prior to Archive?
Possibly similar to #15338 #16295 ?
