### ISSUE TITLE
latest_testflight_build_number returns an older build

### ISSUE THREAD

**Issue by shadone** [fastlane/fastlane#18309]
I use `latest_testflight_build_number` lane as documented to get the build number and increment it by one. However I noticed that it doesn't always return the greatest build number but rather a build number for the most recently uploaded build. In most cases it is the same but I've accidentally uploaded an older build to TestFlight - which correctly rejected the build, however now the `latest_testflight_build_number` lane returns that old build number.

```
    api_key = app_store_connect_api_key(
      key_id: "XXX",
      issuer_id: "XXX",
      key_filepath: "XXX",
      duration: 1200,
      in_house: false,
    )

    build_number = latest_testflight_build_number(
      api_key: api_key,
      app_identifier: 'com.example.myapp',
    )
```

I'd tried to debug this by adding addition puts statement in `app_store_build_number.rb:75` like this:
```
          UI.message("Fetching the latest build number for #{version_number_message}")

          # <<<
          foobar = Spaceship::ConnectAPI.get_builds(filter: filter, sort: "-uploadedDate", includes: "preReleaseVersion")
          puts foobar.inspect
          # <<<

          # Get latest build for optional version number and return build number if found
          build = Spaceship::ConnectAPI.get_builds(filter: filter, sort: "-uploadedDate", includes: "preReleaseVersion", limit: 1).first
```

Here is the snippet from ConnectAPI response. Latest build number in our TestFlight is 35; but most recently uploaded build is 29:

```
[
  {
    "attributes": {
      "expirationDate": "2021-05-27T03:35:47-07:00",
      "expired": false,
      "iconAssetToken": {
        "height": 167,
        "templateUrl": "https://is2-ssl.mzstatic.com/image/thumb/Purple114/v4/ed/b1/d9/edb1d976-.../Icon-83.5@2x.png.png/{w}x{h}bb.{f}",
        "width": 167
      },
      "minOsVersion": "11.0",
      "processingState": "VALID",
      "uploadedDate": "2021-02-26T03:35:47-08:00",
      "usesNonExemptEncryption": false,
      "version": "29"
    },
    "id": "04afa88f-80ba..",
    "links": {
      "self": "https://api.appstoreconnect.apple.com/v1/builds/04afa88f-..."
    },
    ...
    "type": "builds"
  },
  ...
  {
    "attributes": {
      "expirationDate": "2021-05-11T07:23:25-07:00",
      "expired": false,
      "iconAssetToken": {
        "height": 167,
        "templateUrl": "https://is1-ssl.mzstatic.com/image/thumb/Purple114/v4/14/05/b6/1405b641-.../Icon-83.5@2x.png.png/{w}x{h}bb.{f}",
        "width": 167
      },
      "minOsVersion": "11.0",
      "processingState": "VALID",
      "uploadedDate": "2021-02-10T07:23:25-08:00",
      "usesNonExemptEncryption": false,
      "version": "35"
    },
    "id": "86867e52-...",
    "links": {
      "self": "https://api.appstoreconnect.apple.com/v1/builds/86867e52-..."
    },
    ...
    "type": "builds"
  },
  ...
]
```

I think a better implementation would be to sort builds by "version" field instead of "uploadedDate". Does this sound sensible?

I believe this is the same issue as described here: https://github.com/fastlane/fastlane/issues/18185#issuecomment-780119339

**Comment by max-ott** [comment]
Unfortunately with the App Store Connect API there is no one size fits it all to get the actual latest build / version number. In theory you would need to iterate over ALL versions / builds and sort them in a meaningful way. Then we have *some* users, who use an extremely high version number to never have their TestFlight builds require beta review again.

Check out the official docs for the available information: https://developer.apple.com/documentation/appstoreconnectapi/list_builds Maybe we have someone smart come up with a lightweight and always working solution.

**Comment by evanjmg** [comment]
Anyone have any workarounds?
