### ISSUE TITLE
Ability to add manifest to exportOptionsPlist for enterprise deployment

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1830]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/10878329?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @iONsky - Imported from <a href='https://github.com/fastlane/gym/issues/180'>fastlane/gym#180</a>
        </td>
      </tr>
    </table>

At the moment I have to create an extra manifest plist file for my enterprise app deployment by hand. Since Xcode 7 it will be generated automatically when you add a 'manifest' dictionary into the exportOptionsPlist.

Sadly I haven't found a way to tell gym to add this to the exportOptionsPlist when exporting an ipa.

Do you think it would be possibly to have a parameter to pass the content of the manifest dictionary?

Here is the output from `xcodebuild -help` about the manifest I'm talking about:

> manifest : Dictionary
> For non-App Store exports, users can download your app over the web by opening your distribution manifest file in a web browser. To generate a distribution manifest, the value of this key should be a dictionary with three sub-keys: appURL, displayImageURL, fullSizeImageURL. The additional sub-key assetPackManifestURL is required when using on demand resources.

**Comment by ShadyElyaski** [comment]
Hasn't that been added already in export_options?

**Comment by iONsky** [comment]
Yes, it works like a charm 👍 

Here a example of how I use it:
> gym(
   export_options: {
     manifest: {
       appURL: "https://server.local/apps/TestApp.ipa",
            displayImageURL: "https://server.local/apps/TestApp.png",
            fullSizeImageURL: "https://server.local/apps/TestApp.png"
         }
        }
      )
