### ISSUE TITLE
fastlane_match with app_store_connect_api_key doesn't work cross organization. Bundle id is not found.

### ISSUE THREAD

**Issue by thinklinux** [fastlane/fastlane#18316]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Our developer account in invited in multiple organizations. Until enabling 2fa we haven't have any issues with that. Fastlane would search for the bundle id in every account that we have access to.

What we receive right now is: `An app with that bundle ID needs to exist in order to create a provisioning profile for it` followed with list of apps, all from our own account. This is while we are using the app_store_connect_api_key action. If we fallback to the session based authorisation + application specific password there are no issues there. So adding app_store_connect_api_key is limiting the access to apps to our account only. I don't know if that's Apple's API limitation or a bug in Fastlane.

##### Command executed
fastlane match

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
+--------------------------------+-------------------------------------------------------+
|                               Summary for match 2.176.0                                |
+--------------------------------+-------------------------------------------------------+
| app_identifier                 | ["bundle_id"]                                     |
| type                           | appstore                                              |
| git_branch                     | branch                                                 |
| team_id                        | team_id                                            |
| api_key                        | ********                                              |
| readonly                       | false                                                 |
| generate_apple_certs           | true                                                  |
| skip_provisioning_profiles     | false                                                 |
| username                       | account_email                                     |
| storage_mode                   | git                                                   |
| git_url                        | git@gitlab.com:url  |
|                                | es.git                                                |
| shallow_clone                  | false                                                 |
| clone_branch_directly          | false                                                 |
| keychain_name                  | login.keychain                                        |
| force                          | false                                                 |
| force_for_new_devices          | false                                                 |
| skip_confirmation              | false                                                 |
| skip_docs                      | false                                                 |
| platform                       | ios                                                   |
| derive_catalyst_app_identifier | false                                                 |
| fail_on_name_taken             | false                                                 |
| skip_certificate_matching      | false                                                 |
| skip_set_partition_list        | false                                                 |
| verbose                        | false                                                 |
+--------------------------------+-------------------------------------------------------+

[18:10:29]: Cloning remote git repo...
[18:10:29]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[18:10:32]: Checking out branch branch...
[18:10:32]: 🔓  Successfully decrypted certificates repo
[18:10:32]: Verifying that the certificate and profile are still valid on the Dev Portal...
[18:10:32]: Creating authorization token for App Store Connect API
[18:10:33]: 
[18:10:33]: ==========================================
[18:10:33]: Could not find App ID with bundle identifier 'bundle_id'
[18:10:33]: You can easily generate a new App ID on the Developer Portal using 'produce':
[18:10:33]: 
[18:10:33]: fastlane produce -u account_email -a bundle_id --skip_itc
[18:10:33]: 
[18:10:33]: You will be asked for any missing information, like the full name of your app
[18:10:33]: If the app should also be created on App Store Connect, remove the --skip_itc from the command above
[18:10:33]: ==========================================
[18:10:33]: 
[18:10:33]: An app with that bundle ID needs to exist in order to create a provisioning profile for it
[18:10:33]: ================================================================
[18:10:36]: Available apps:
[**LIST OF APPS**]
[18:10:36]: Make sure to run `fastlane match` with the same user and team every time.
+------------------+-----------+
|         Lane Context         |
+------------------+-----------+
| DEFAULT_PLATFORM | ios       |
| PLATFORM_NAME    | ios       |
| LANE_NAME        | ios build |
+------------------+-----------+
[18:10:36]: Couldn't find bundle identifier '[**SOME_BUNDLE_ID**]' for the user '[**SOME_ACCOUNT**]'

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 3    | app_store_connect_api_key  | 0           |
| 💥   | match                      | 6           |
+------+----------------------------+-------------+

[18:10:36]: fastlane finished with errors

[!] Couldn't find bundle identifier '[**SOME_BUNDLE_ID**]' for the user '[**SOME_ACCOUNT**]'
</pre>
</details>

### Environment

<details>
  <pre>
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.2                                        |
| Ruby                        | 2.6.5                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.rbenv/versions/2.6.5/bin/fastlane        |
| Host                        | macOS 11.2 (20D64)                          |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.5/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.5                                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.176.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.3.0        |
| slack-notifier                | 2.3.2        |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| addressable                   | 2.7.0        |
| multipart-post                | 2.0.0        |
| word_wrap                     | 1.0.0        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| artifactory                   | 3.0.15       |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| faraday_middleware            | 1.0.0        |
| gh_inspector                  | 1.1.3        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| bundler                       | 1.17.2       |
| simctl                        | 1.6.8        |
| uber                          | 0.1.0        |
| declarative-option            | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| mini_mime                     | 1.0.2        |
| httpclient                    | 2.8.3        |
| google-api-client             | 0.38.0       |
| nanaimo                       | 0.3.0        |
| colored2                      | 3.1.2        |
| claide                        | 1.0.3        |
| CFPropertyList                | 3.0.3        |
| atomos                        | 0.1.3        |
| xcodeproj                     | 1.19.0       |
| plist                         | 3.6.0        |
| public_suffix                 | 4.0.6        |
| tty-screen                    | 0.8.1        |
| babosa                        | 1.0.4        |
| excon                         | 0.79.0       |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| http-cookie                   | 1.0.3        |
| ruby2_keywords                | 0.0.4        |
| faraday-net_http              | 1.0.1        |
| faraday                       | 1.3.0        |
| faraday-cookie_jar            | 0.0.7        |
| fastimage                     | 2.2.2        |
| json                          | 2.5.1        |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| xcpretty-travis-formatter     | 1.0.1        |
| dotenv                        | 2.7.6        |
| jwt                           | 2.2.2        |
| declarative                   | 0.0.20       |
| multi_json                    | 1.15.0       |
| signet                        | 0.14.1       |
| os                            | 1.1.1        |
| memoist                       | 0.16.2       |
| googleauth                    | 0.15.1       |
| rake                          | 13.0.3       |
| digest-crc                    | 0.6.3        |
| webrick                       | 1.7.0        |
| rexml                         | 3.2.4        |
| google-apis-core              | 0.2.1        |
| google-apis-storage_v1        | 0.2.0        |
| google-apis-iamcredentials_v1 | 0.1.0        |
| google-cloud-errors           | 1.0.1        |
| google-cloud-env              | 1.4.0        |
| google-cloud-core             | 1.5.0        |
| google-cloud-storage          | 1.30.0       |
| emoji_regex                   | 3.2.2        |
| aws-eventstream               | 1.1.0        |
| aws-sigv4                     | 1.2.2        |
| aws-partitions                | 1.429.0      |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.112.0      |
| aws-sdk-kms                   | 1.42.0       |
| aws-sdk-s3                    | 1.88.1       |
| forwardable                   | 1.2.0        |
| logger                        | 1.3.0        |
| date                          | 2.0.0        |
| stringio                      | 0.0.2        |
| zlib                          | 1.0.0        |
| ipaddr                        | 1.2.2        |
| openssl                       | 2.1.2        |
| ostruct                       | 0.1.0        |
| strscan                       | 1.0.0        |
| fileutils                     | 1.1.0        |
| etc                           | 1.0.1        |
| io-console                    | 0.4.7        |
| mini_portile2                 | 2.4.0        |
| nokogiri                      | 1.10.4       |
| psych                         | 3.1.0        |
| mutex_m                       | 0.1.0        |
</details>

*generated on:* **2021-03-02**
</details>
</pre>
</details>

**Comment by Dinsen** [comment]
Hi @thinklinux 
You will need an API Key for every account you have access to.
