### ISSUE TITLE
itc_team_id/itc_team_name in Appfile ignored when using FASTLANE_SESSION -> "Multiple Teams found; unable to choose"

### ISSUE THREAD

**Issue by cynicer** [fastlane/fastlane#18322]
### New Issue Checklist

- [x] Updated fastlane to the latest version (fastlane 2.176.0)
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I have the problem that the defined itc_team_id/itc_team_name in the Appfile is seemingly ignored by fastlane when logging into the AppStore Connect API (for dSYM download) via a cached FASTLANE_SESSION. This is very similar to #17371 which is already closed. None of the workarounds there worked for me. Setting the the corresponding environment variables (e.g. FASTLANE_ITC_TEAM_ID) works for me, but is not ideal.

It also works while setting it in the fastfile (e.g. `ENV['FASTLANE_ITC_TEAM_ID'] = CredentialsManager::AppfileConfig.try_fetch_value(:itc_team_id)`). So the correct info is there, but it's ignored by fastlane for some reason.

##### Command executed
Our fastlane pipeline which essentially fails at "Actions::DownloadDsymsAction.run" while logging in, because it doesn't automatically choose the correct team.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [10:36:21]: ---------------------------------------
[10:36:21]: --- Step: custom_step ---
[10:36:21]: ---------------------------------------
[10:36:22]: Login to App Store Connect (redacted)
Multiple App Store Connect teams found, please enter the number of the team you want to use:
Note: to automatically choose the team, provide either the App Store Connect Team ID, or the Team Name in your fastlane/Appfile:
Alternatively you can pass the team name or team ID using the `FASTLANE_ITC_TEAM_ID` or `FASTLANE_ITC_TEAM_NAME` environment variable

  itc_team_id "redacted1"

or

  itc_team_name "redacted2"

1) redacted
2) redacted
Multiple teams found on App Store Connect, Your Terminal is running in non-interactive mode! Cannot continue from here.
Please check that you set FASTLANE_ITC_TEAM_ID or FASTLANE_ITC_TEAM_NAME to the right value.
+------------------+-------------+
|          Lane Context          |
+------------------+-------------+
| DEFAULT_PLATFORM | ios         |
| PLATFORM_NAME    | ios         |
| LANE_NAME        | ios release |
| BUILD_NUMBER     | 134         |
| VERSION_NUMBER   | 8.203       |
+------------------+-------------+
[10:36:23]: Multiple App Store Connect Teams found; unable to choose, terminal not interactive!

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | default_platform       | 0           |
| 2    | app_store_connect_api  | 0           |
|      | _key                   |             |
| 3    | get_build_number       | 0           |
| 4    | get_version_number     | 0           |
| 💥   | custom_step            | 1           |
+------+------------------------+-------------+

[10:36:23]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  ITC Team ID specified in AppFile isn't being passed to connect_api; now I get "Multiple Teams found; unable to choose"
    https://github.com/fastlane/fastlane/issues/17371 [closed] 22 💬
    2 weeks ago

➡️  Selecting ITC team from environment in `deliver` doesn't work
    https://github.com/fastlane/fastlane/issues/16433 [closed] 3 💬
    06 Jul 2020

➡️  Fastlane ignores non-interactive mode and asks for 2FA code
    https://github.com/fastlane/fastlane/issues/14345 [closed] 17 💬
bundler: failed to load command: fastlane (/Users/user/.rbenv/versions/2.7.2/bin/fastlane)
    29 Nov 2019
RuntimeError: [!] Multiple App Store Connect Teams found; unable to choose, terminal not interactive!

  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/spaceship/lib/spaceship/tunes/tunes_client.rb:112:in `block in select_team'
and 1 more at: https://github.com/fastlane/fastlane/search?q=Multiple%20App%20Store%20Connect%20Teams%20found%3B%20unable%20to%20choose%2C%20terminal%20not%20interactive%21&type=Issues&utf8=✓
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/spaceship/lib/spaceship/tunes/tunes_client.rb:89:in `loop'

  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/spaceship/lib/spaceship/tunes/tunes_client.rb:89:in `select_team'
🔗  You can ⌘ + double-click on links to open them directly in your browser.
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/spaceship/lib/spaceship/connect_api/client.rb:69:in `login'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/spaceship/lib/spaceship/connect_api/spaceship.rb:85:in `login'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane/lib/fastlane/actions/download_dsyms.rb:18:in `run'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-plugin-custom-1.0.0/lib/fastlane/plugin/custom/actions/custom_action.rb:54:in `run'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:51:in `block (2 levels) in parsing_binding'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.176.0/bin/fastlane:23:in `<top (required)>'
  /Users/user/.rbenv/versions/2.7.2/bin/fastlane:23:in `load'
  /Users/user/.rbenv/versions/2.7.2/bin/fastlane:23:in `<top (required)>'

> Task :executeFastlaneWorkflowTest FAILED
:executeFastlaneWorkflowTest (Thread[Execution worker for ':',5,main]) completed. Took 4.814 secs.

FAILURE: Build failed with an exception.</pre>
</details>

### Environment

<details>
  <pre> <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.2.1                                      |
| Ruby                        | 2.7.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.rbenv/versions/2.7.2/bin/fastlane        |
| Host                        | macOS 11.2.1 (20D74)                        |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.2/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.4                                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>
REDACTED
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile
app_identifier("REDACTED") # The bundle identifier of your app
itc_team_id("REDACTED")
team_id("REDACTED")

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.176.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-versioning | 0.4.4   | ✅ Up-To-Date  |
| fastlane-plugin-custom     | 1.0.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.5.0        |
| slack-notifier                | 2.3.2        |
| atomos                        | 0.1.3        |
| CFPropertyList                | 3.0.3        |
| claide                        | 1.0.3        |
| colored2                      | 3.1.2        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| multipart-post                | 2.0.0        |
| word_wrap                     | 1.0.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| artifactory                   | 3.0.15       |
| babosa                        | 1.0.4        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| gh_inspector                  | 1.1.3        |
| mini_magick                   | 4.11.0       |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| dotenv                        | 2.7.6        |
| simctl                        | 1.6.8        |
| jwt                           | 2.2.2        |
| uber                          | 0.1.0        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| mini_mime                     | 1.0.2        |
| httpclient                    | 2.8.3        |
| google-api-client             | 0.38.0       |
| uri                           | 0.10.1       |
| plist                         | 3.6.0        |
| excon                         | 0.79.0       |
| ruby2_keywords                | 0.0.4        |
| faraday-net_http              | 1.0.1        |
| faraday                       | 1.3.0        |
| fastimage                     | 2.2.3        |
| json                          | 2.5.1        |
| naturally                     | 2.2.1        |
| xcpretty-travis-formatter     | 1.0.1        |
| bundler                       | 2.2.12       |
| multi_json                    | 1.15.0       |
| signet                        | 0.14.1       |
| os                            | 1.1.1        |
| memoist                       | 0.16.2       |
| googleauth                    | 0.15.1       |
| rake                          | 13.0.3       |
| digest-crc                    | 0.6.3        |
| webrick                       | 1.7.0        |
| rexml                         | 3.2.4        |
| google-apis-core              | 0.2.1        |
| google-apis-storage_v1        | 0.2.0        |
| google-apis-iamcredentials_v1 | 0.1.0        |
| google-cloud-errors           | 1.0.1        |
| google-cloud-env              | 1.4.0        |
| google-cloud-core             | 1.5.0        |
| google-cloud-storage          | 1.30.0       |
| emoji_regex                   | 3.2.2        |
| aws-eventstream               | 1.1.0        |
| aws-sigv4                     | 1.2.2        |
| aws-partitions                | 1.430.0      |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.112.0      |
| aws-sdk-kms                   | 1.42.0       |
| aws-sdk-s3                    | 1.89.0       |
| forwardable                   | 1.3.2        |
| logger                        | 1.4.3        |
| cgi                           | 0.2.0        |
| date                          | 3.1.1        |
| timeout                       | 0.1.1        |
| stringio                      | 3.0.0        |
| zlib                          | 1.1.0        |
| openssl                       | 2.2.0        |
| ipaddr                        | 1.2.2        |
| ostruct                       | 0.3.3        |
| strscan                       | 3.0.0        |
| delegate                      | 0.2.0        |
| fileutils                     | 1.5.0        |
| io-console                    | 0.5.8        |
| open3                         | 0.1.1        |
| singleton                     | 0.1.1        |
| yaml                          | 0.1.1        |
| psych                         | 3.3.1        |
| mutex_m                       | 0.1.1        |
| fastlane-plugin-versioning    | 0.4.4        |
| fastlane-plugin-custom        | 1.0.0        |
</details>

*generated on:* **2021-03-03**
</details> </pre>
</details>

**Comment by cynicer** [comment]
Same problem with 2.179.0.

**Comment by marcinmatczuk** [comment]
Same issue with 2.181.0.

**Comment by Decorsair** [comment]
> There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.
> 
> Please make sure to update to the latest `fastlane` version and check if that solves the issue. Let us know if that works for you by adding a comment 👍
> 
> Friendly reminder: contributions are always welcome! Check out [CONTRIBUTING.md](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md) for more information on how to help with `fastlane` and feel free to tackle this issue yourself 💪
> 
> This issue will be auto-closed if there is no reply within 1 month.

Good one, I had no idea about this trick. Make sense if it works pretty well. Thanks!

**Comment by cynicer** [comment]
Still happening.

**Comment by cynicer** [comment]
Same procedure as every time.
