### ISSUE TITLE
Gym command gets stuck and never ends

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1832]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/1828968?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @calclavia - Imported from <a href='https://github.com/fastlane/gym/issues/171'>fastlane/gym#171</a>
        </td>
      </tr>
    </table>

I typed the following command into terminal:

```
gym -p 'platforms/ios/app.xcodeproj' --scheme app --export_method ad-hoc -o build/ios -e scripts/ekko_ad_hoc.mobileprovision -c
```

The command gets stuck after it prints this line. It stalls and never finishes:
```
xcrun xcodebuild -list -project 'platforms/ios/app.xcodeproj'
```

I tried typing the following into the terminal:
```
xcrun xcodebuild -list -project 'platforms/ios/app.xcodeproj'
```

It correctly lists out the target of the xcode project. I'm using Cordova to generate the xcodeproject file.

Using gym v1.2.0
System: Mac OS X El Capitan 10.11.2

**Comment by calclavia** [comment]
Using gym 1.6.2.

Now the command ends and times out. However, this does not really resolve the problem of the command `xcrun xcodebuild -list -project 'platforms/ios/app.xcodeproj'` stalling the terminal. I'm not sure what would be a good solution for this.

**Comment by i2amsam** [comment]
@calclavia :+1: going to close this, hopefully those steps are useful to others too.

**Comment by TKBurner** [comment]
Thanks @calclavia 

> Had the same trouble few days ago.
My problem was that xcrun xcodebuild -list -project looking for user scheme in project directory. xcuserdata is where it should be located.

The solution for me was to install xcodeproj gem – gem install xcodeproj.
Create small script to recreate user schemes

#!/usr/bin/env ruby
require 'xcodeproj'
xcproj = Xcodeproj::Project.open("MyProject.xcodeproj")
xcproj.recreate_user_schemes
xcproj.save
And execute it. After this xcrun xcodebuild -list -project runs smooth.
Hope it helps you!

**Comment by dmakovec** [comment]
@TKBurner Excellent tip - this saved me. Many thanks!
