### ISSUE TITLE
Upgrading from 2.174.0 to 2.176.0 results in `'api_key' value must be a Hash! Found String instead.`

### ISSUE THREAD

**Issue by mikaelbartlett** [fastlane/fastlane#18324]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: `2.176.0`
- Last working version: `2.174.0`

### Regression Description
After updating our CI fails to upload to app store connect with error `'api_key' value must be a Hash! Found String instead.`

**Comment by max-ott** [comment]
How are you currently setting the api key?

**Comment by mikaelbartlett** [comment]
```
app_store_connect_api_key(
      key_id: "XXX",
      issuer_id: "xxx-xx-xx-xx-xx",
      key_filepath: "fastlane/app_store_connect_api_key.p8",
      in_house: false
    )
```

**Comment by mikaelbartlett** [comment]
Here's the whole lane

`desc "Upload beta to Testflight"
  lane :beta do
    app_store_connect_api_key(
      key_id: "XXXXXXX",
      issuer_id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
      key_filepath: "fastlane/app_store_connect_api_key.p8",
      in_house: false
    )

    sync_code_signing(type: "appstore", readonly: true)

    build_app(scheme: "XXXXXX")

    build_number = sh("git rev-list HEAD | wc -l | tr -d ' '").strip.to_i
    add_git_tag(
      build_number: build_number
    )

    push_to_git_remote

    upload_to_testflight(
      notify_external_testers: false
    )
  end`

**Comment by NicolasLourenco** [comment]
👋🏼 Same here
I think this commit introduced the bug: https://github.com/fastlane/fastlane/commit/711ed66d201e6fe4ad7146406d956880402c9346

Ping @joshdholtz

**Comment by joshdholtz** [comment]
Will look at! Thanks for ping 💪

**Comment by csc-EricWu** [comment]
I have the same problem, it makes me unable to work, please fix it as soon as possible.

**Comment by joshdholtz** [comment]
@mikaelbartlett @nicolasbraun @csc-EricWu Can you either of your provide me with your console output that also contains the stacktrace in it? I can’t seem to reproduce this 😔  

If you don’t feel comfortable posting here, you can email it to me at me@joshholtz.com 🙏

**Comment by joshdholtz** [comment]
@mikaelbartlett @NicolasLourenco @csc-EricWu 

Follow up question... do any of you happen to have the `APP_STORE_CONNECT_API_KEY` environment variable set to something? This variable was first introduced in https://github.com/fastlane/fastlane/commit/711ed66d201e6fe4ad7146406d956880402c9346 but your examples of using `app_store_connect_api_key` don’t seem to be using them. I’m curious if you set that exact environment variable for something else?

**Comment by mikaelbartlett** [comment]
I have set `APP_STORE_CONNECT_API_KEY` in circle ci. That is used to generate a p8 file named `app_store_connect_api_key.p8`.

[output_fastlane.txt](https://github.com/fastlane/fastlane/files/6100629/output_fastlane.txt)

**Comment by joshdholtz** [comment]
@mikaelbartlett Ahhhhh, so... I think that is clashing with the newly introduced environment variable that is now used by all the actions 😱 Are you able to rename that to something else to see if that fixes things?

**Comment by mikaelbartlett** [comment]
I'll give it a try and see.

**Comment by NicolasLourenco** [comment]
> I have set `APP_STORE_CONNECT_API_KEY` in circle ci. That is used to generate a p8 file named `app_store_connect_api_key.p8`.
> 
> Here's the output: [output_fastlane.txt](https://github.com/fastlane/fastlane/files/6100629/output_fastlane.txt)
> 
> I hope this helps @joshdholtz

Exactly the same, I use this env var to create a p8 file.
So @joshdholtz  what you mean, is that we just can create this env var without passing them to `app_store_connect_api_key`
like 
```
app_store_connect_api_key(
      key_id: key_id,
      issuer_id: issuer_id,
      in_house: false
    )

**Comment by joshdholtz** [comment]
Correct! If you run `fastlane action app_store_connect_api_key`, you will see the environment variables that this action will implicitly lookup 👇 

So... if you set `APP_STORE_CONNECT_API_KEY_KEY_ID`, `APP_STORE_CONNECT_API_KEY_ISSUER_ID`, and `APP_STORE_CONNECT_API_KEY_KEY_FILEPATH` in your Ci environment variables or `.env` file, your `Fastfile` will only need to look like...

```rb
app_store_connect_api_key

sync_code_signing
build_ios_app

# etc etc etc
```

### Doc from running `fastlane action app_store_connect_api_key`

```sh
+-----------------------+-----------------------------------+-----------------------------------+---------+
|                                    app_store_connect_api_key Options                                    |
+-----------------------+-----------------------------------+-----------------------------------+---------+
| Key                   | Description                       | Env Var(s)                        | Default |
+-----------------------+-----------------------------------+-----------------------------------+---------+
| key_id                | The key ID                        | APP_STORE_CONNECT_API_KEY_KEY_ID  |         |
| issuer_id             | The issuer ID                     | APP_STORE_CONNECT_API_KEY_ISSUER  |         |
|                       |                                   | _ID                               |         |
| key_filepath          | The path to the key p8 file       | APP_STORE_CONNECT_API_KEY_KEY_FI  |         |
|                       |                                   | LEPATH                            |         |
| key_content           | The content of the key p8 file    | APP_STORE_CONNECT_API_KEY_KEY     |         |
| is_key_content_base64 | Whether :key_content is Base64    | APP_STORE_CONNECT_API_KEY_IS_KEY  | false   |
|                       | encoded or not                    | _CONTENT_BASE64                   |         |
| duration              | The token session duration        | APP_STORE_CONNECT_API_KEY_DURATI  | 1200    |
|                       |                                   | ON                                |         |
| in_house              | Is App Store or Enterprise (in    | APP_STORE_CONNECT_API_KEY_IN_HOU  |         |
|                       | house) team? App Store Connect    | SE                                |         |
|                       | API cannot determine this on its  |                                   |         |
|                       | own (yet)                         |                                   |         |
+-----------------------+-----------------------------------+-----------------------------------+---------+
* = default value is dependent on the user's system

+---------------------------+-----------------------------------------------------------------------+
|                            app_store_connect_api_key Output Variables                             |
+---------------------------+-----------------------------------------------------------------------+
| Key                       | Description                                                           |
+---------------------------+-----------------------------------------------------------------------+
| APP_STORE_CONNECT_API_KEY | The App Store Connect API key information used for authorization      |
|                           | requests. This hash can be passed directly into the :api_key options  |
|                           | on other tools or into Spaceship::ConnectAPI::Token.create method     |
+---------------------------+-----------------------------------------------------------------------+
Access the output values using `lane_context[SharedValues::VARIABLE_NAME]`

```

**Comment by mikaelbartlett** [comment]
> @mikaelbartlett Ahhhhh, so... I think that is clashing with the newly introduced environment variable that is now used by all the actions 😱 Are you able to rename that to something else to see if that fixes things?

Change the name of the environment variable solved the issue. Thanks @joshdholtz

**Comment by joshdholtz** [comment]
@mikaelbartlett Cool cool! Glad that solved it 😊  Sorry about that clash! Didn’t think there would be any issues when I picked that environment variable name 😅 We okay to close this issue?

**Comment by mikaelbartlett** [comment]
Yes, let's close it.
