### ISSUE TITLE
fastlane match AccessForbiddenError for enterprise with Admin role account

### ISSUE THREAD

**Issue by sp-ricard-valverde** [fastlane/fastlane#18336]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Running `fastlane match` for an enterprise account with a user with **Admin** role is failing with an `AccessForbiddenError`
It was working properly not so long ago, It might have been the consequence of a recent apple change:

`Starting March 3, 2021, additional authentication will be required to sign in to the Users and Access section of your Apple Developer account in an effort to ensure security. When you sign in, you’ll be prompted to update your account.`

Although the affected account had been already upgraded to use 2FA(the `fastlane` command is reading the authentication from a cookie generated by `spaceauth` using the 2FA code.

With the `developer` accounts we did not hit the same problem and we can invoke `fastlane match` just fine.

##### Command executed
````
FASTLANE_SESSION=***
MATCH_PASSWORD=***
FASTLANE_PASSWORD=***
FASTLANE_DISABLE_OUTPUT_FORMAT=true
FASTLANE_SKIP_UPDATE_CHECK=true
FASTLANE_HIDE_TIMESTAMP=true
FL_SKIP_TABLE_TRANSFORM=true
MATCH_GIT_URL=***

fastlane match enterprise --app_identifier="*" --clone_branch_directly=true --git_branch=*** --keychain_password=*** --team_id=*** --verbose
````

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 

fastlane match enterprise --app_identifier="*" --clone_branch_directly=true --git_branch=*** --keychain_password=*** --team_id=*** --verbose

[✔] ð
Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

+--------------------------------+----------------------------------------------------------------+
|                                    Summary for match 2.176.0                                    |
+--------------------------------+----------------------------------------------------------------+
| verbose                        | true                                                           |
| app_identifier                 | ["*"]                                                          |
| clone_branch_directly          | true                                                           |
| git_branch                     | ***************                                                |
| keychain_password              | ********                                                       |
| team_id                        | **********                                                     |
| type                           | enterprise                                                     |
| readonly                       | false                                                          |
| generate_apple_certs           | true                                                           |
| skip_provisioning_profiles     | false                                                          |
| username                       | **************************                                     |
| storage_mode                   | git                                                            |
| git_url                        | ************************************************************** |
| shallow_clone                  | false                                                          |
| keychain_name                  | login.keychain                                                 |
| force                          | false                                                          |
| force_for_new_devices          | false                                                          |
| skip_confirmation              | false                                                          |
| skip_docs                      | false                                                          |
| platform                       | ios                                                            |
| derive_catalyst_app_identifier | false                                                          |
| fail_on_name_taken             | false                                                          |
| skip_certificate_matching      | false                                                          |
| skip_set_partition_list        | false                                                          |
+--------------------------------+----------------------------------------------------------------+

INFO [2021-03-04 16:06:14.34]: Cloning remote git repo...
INFO [2021-03-04 16:06:14.34]: $ git clone ************************************************************** /var/folders/zp/xf4k42dn09q_jwvm1zy7q6k40000gn/T/d20210304-89794-m8gf32 -b *************** --single-branch
INFO [2021-03-04 16:06:14.36]: Cloning into '/var/folders/zp/xf4k42dn09q_jwvm1zy7q6k40000gn/T/d20210304-89794-m8gf32'...
INFO [2021-03-04 16:06:15.72]: remote: Enumerating objects: 26, done.
INFO [2021-03-04 16:06:15.72]: remote: Counting objects: 100% (26/26), done.
INFO [2021-03-04 16:06:15.73]: remote: Compressing objects: 100% (23/23), done.
INFO [2021-03-04 16:06:15.92]: remote: Total 65 (delta 4), reused 20 (delta 2), pack-reused 39
INFO [2021-03-04 16:06:15.92]: Receiving objects: 100% (65/65), 67.88 KiB | 681.00 KiB/s, done.
INFO [2021-03-04 16:06:15.92]: Resolving deltas: 100% (6/6), done.
INFO [2021-03-04 16:06:16.84]: $ git --no-pager branch --list ********************** --no-color -r
INFO [2021-03-04 16:06:16.86]:   **********************
INFO [2021-03-04 16:06:16.86]: Checking out branch ***************...
INFO [2021-03-04 16:06:16.86]: $ git checkout ***************
INFO [2021-03-04 16:06:16.87]: Already on '***************'
INFO [2021-03-04 16:06:16.87]: Your branch is up to date with '**********************'.
INFO [2021-03-04 16:06:17.76]: ð  Decrypted ***********.cer'
INFO [2021-03-04 16:06:17.76]: ð  Decrypted '**********.p12'
INFO [2021-03-04 16:06:17.76]: ð  Decrypted '**********.cer'
INFO [2021-03-04 16:06:17.76]: ð  Decrypted '**********.p12'
INFO [2021-03-04 16:06:17.76]: ð  Decrypted 'InHouse_*.mobileprovision'
INFO [2021-03-04 16:06:17.76]: ð  Decrypted 'Development_*.mobileprovision'
INFO [2021-03-04 16:06:17.76]: ð  Successfully decrypted certificates repo
INFO [2021-03-04 16:06:17.76]: Verifying that the certificate and profile are still valid on the Dev Portal...
Reading keychain entry, because either user or password were empty
Loading session from environment variable
Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 4)...
Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 3)...
Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 2)...
Timeout received: 'Spaceship::AccessForbiddenError', 'Access forbidden'. Retrying after 3 seconds (remaining: 1)...

Looking for related GitHub issues on fastlane/fastlane...
Search query: The request could not be completed because:
	Access forbidden

URL: https://api.github.com/search/issues?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09Access%20forbidden+repo:fastlane/fastlane
➡️  The request could not be completed because: Access forbidden
    https://github.com/fastlane/fastlane/issues/17479 [closed] 3 ð¬
    21 Dec 2020

➡️  The request could not be completed because: 	Access forbidden
    https://github.com/fastlane/fastlane/issues/17141 [closed] 5 ð¬
    26 Dec 2020

➡️  'Access Forbidden', when running: fastlane init
    https://github.com/fastlane/fastlane/issues/17789 [closed] 8 ð¬
    2 weeks ago

and 5 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09Access%20forbidden&type=Issues&utf8=✓

ð  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	25: from /usr/local/opt/gems/bin/fastlane:23:in `<main>'
	24: from /usr/local/opt/gems/bin/fastlane:23:in `load'
	23: from /usr/local/opt/gems/gems/fastlane-2.176.0/bin/fastlane:23:in `<top (required)>'
	22: from /usr/local/opt/gems/gems/fastlane-2.176.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	21: from /usr/local/opt/gems/gems/fastlane-2.176.0/match/lib/match/commands_generator.rb:25:in `start'
	20: from /usr/local/opt/gems/gems/fastlane-2.176.0/match/lib/match/commands_generator.rb:187:in `run'
	19: from /usr/local/opt/gems/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	18: from /usr/local/opt/gems/gems/fastlane-2.176.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	17: from /usr/local/opt/gems/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	16: from /usr/local/opt/gems/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	15: from /usr/local/opt/gems/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	14: from /usr/local/opt/gems/gems/fastlane-2.176.0/match/lib/match/commands_generator.rb:68:in `block (3 levels) in run'
	13: from /usr/local/opt/gems/gems/fastlane-2.176.0/match/lib/match/runner.rb:90:in `run'
	12: from /usr/local/opt/gems/gems/fastlane-2.176.0/match/lib/match/runner.rb:90:in `each'
	11: from /usr/local/opt/gems/gems/fastlane-2.176.0/match/lib/match/runner.rb:91:in `block in run'
	10: from /usr/local/opt/gems/gems/fastlane-2.176.0/match/lib/match/spaceship_ensure.rb:42:in `bundle_identifier_exists'
	 9: from /usr/local/opt/gems/gems/fastlane-2.176.0/spaceship/lib/spaceship/connect_api/models/bundle_id.rb:50:in `find'
	 8: from /usr/local/opt/gems/gems/fastlane-2.176.0/spaceship/lib/spaceship/connect_api/models/bundle_id.rb:44:in `all'
	 7: from /usr/local/Cellar/ruby/2.6.4/lib/ruby/2.6.0/forwardable.rb:230:in `get_bundle_ids'
	 6: from /usr/local/opt/gems/gems/fastlane-2.176.0/spaceship/lib/spaceship/connect_api/provisioning/provisioning.rb:22:in `get_bundle_ids'
	 5: from /usr/local/opt/gems/gems/fastlane-2.176.0/spaceship/lib/spaceship/connect_api/provisioning/client.rb:29:in `get'
	 4: from /usr/local/opt/gems/gems/fastlane-2.176.0/spaceship/lib/spaceship/connect_api/provisioning/client.rb:54:in `proxy_get'
	 3: from /usr/local/opt/gems/gems/fastlane-2.176.0/spaceship/lib/spaceship/client.rb:723:in `request'
	 2: from /usr/local/opt/gems/gems/fastlane-2.176.0/spaceship/lib/spaceship/client.rb:879:in `send_request'
	 1: from /usr/local/opt/gems/gems/fastlane-2.176.0/spaceship/lib/spaceship/client.rb:643:in `with_retry'
/usr/local/opt/gems/gems/fastlane-2.176.0/spaceship/lib/spaceship/client.rb:899:in `block in send_request': Access forbidden (Spaceship::AccessForbiddenError)
	25: from /usr/local/opt/gems/bin/fastlane:23:in `<main>'
	24: from /usr/local/opt/gems/bin/fastlane:23:in `load'
	23: from /usr/local/opt/gems/gems/fastlane-2.176.0/bin/fastlane:23:in `<top (required)>'
	22: from /usr/local/opt/gems/gems/fastlane-2.176.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	21: from /usr/local/opt/gems/gems/fastlane-2.176.0/match/lib/match/commands_generator.rb:25:in `start'
	20: from /usr/local/opt/gems/gems/fastlane-2.176.0/match/lib/match/commands_generator.rb:187:in `run'
	19: from /usr/local/opt/gems/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	18: from /usr/local/opt/gems/gems/fastlane-2.176.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	17: from /usr/local/opt/gems/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	16: from /usr/local/opt/gems/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	15: from /usr/local/opt/gems/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	14: from /usr/local/opt/gems/gems/fastlane-2.176.0/match/lib/match/commands_generator.rb:68:in `block (3 levels) in run'
	13: from /usr/local/opt/gems/gems/fastlane-2.176.0/match/lib/match/runner.rb:90:in `run'
	12: from /usr/local/opt/gems/gems/fastlane-2.176.0/match/lib/match/runner.rb:90:in `each'
	11: from /usr/local/opt/gems/gems/fastlane-2.176.0/match/lib/match/runner.rb:91:in `block in run'
	10: from /usr/local/opt/gems/gems/fastlane-2.176.0/match/lib/match/spaceship_ensure.rb:42:in `bundle_identifier_exists'
	 9: from /usr/local/opt/gems/gems/fastlane-2.176.0/spaceship/lib/spaceship/connect_api/models/bundle_id.rb:50:in `find'
	 8: from /usr/local/opt/gems/gems/fastlane-2.176.0/spaceship/lib/spaceship/connect_api/models/bundle_id.rb:44:in `all'
	 7: from /usr/local/Cellar/ruby/2.6.4/lib/ruby/2.6.0/forwardable.rb:230:in `get_bundle_ids'
	 6: from /usr/local/opt/gems/gems/fastlane-2.176.0/spaceship/lib/spaceship/connect_api/provisioning/provisioning.rb:22:in `get_bundle_ids'
	 5: from /usr/local/opt/gems/gems/fastlane-2.176.0/spaceship/lib/spaceship/connect_api/provisioning/client.rb:29:in `get'
	 4: from /usr/local/opt/gems/gems/fastlane-2.176.0/spaceship/lib/spaceship/connect_api/provisioning/client.rb:54:in `proxy_get'
	 3: from /usr/local/opt/gems/gems/fastlane-2.176.0/spaceship/lib/spaceship/client.rb:723:in `request'
	 2: from /usr/local/opt/gems/gems/fastlane-2.176.0/spaceship/lib/spaceship/client.rb:879:in `send_request'
	 1: from /usr/local/opt/gems/gems/fastlane-2.176.0/spaceship/lib/spaceship/client.rb:643:in `with_retry'
/usr/local/opt/gems/gems/fastlane-2.176.0/spaceship/lib/spaceship/client.rb:899:in `block in send_request': [!] The request could not be completed because: (Spaceship::AccessForbiddenError)
	Access forbidden
</pre>
</details>

### Environment

<details>
  <pre> [✔] ð
[16:16:55]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[16:16:56]: Generating fastlane environment output, this might take a few seconds...
<details><summary>ð« fastlane environment ð«</summary>

### Stack

| Key                         | Value                                          |
| --------------------------- | ---------------------------------------------- |
| OS                          | 10.15.6                                        |
| Ruby                        | 2.6.4                                          |
| Bundler?                    | false                                          |
| Git                         | git version 2.24.3 (Apple Git-128)             |
| Installation Source         | /usr/local/opt/gems/bin/fastlane               |
| Host                        | Mac OS X 10.15.6 (19G2021)                     |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.6.4/lib               |
| OpenSSL Version             | OpenSSL 1.0.2s  28 May 2019                    |
| Is contained                | false                                          |
| Is homebrew                 | false                                          |
| Is installed via Fabric.app | false                                          |
| Xcode Path                  | /Applications/Xcode-12.app/Contents/Developer/ |
| Xcode Version               | 12.0                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | C           | ð« |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.176.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| artifactory               | 3.0.15       |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.76.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| json                      | 2.3.1        |
| mini_magick               | 4.10.1       |
| naturally                 | 2.2.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.4        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-storage      | 1.28.0       |
| emoji_regex               | 3.0.0        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.364.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.105.0      |
| aws-sdk-kms               | 1.37.0       |
| aws-sdk-s3                | 1.79.1       |
| nanaimo                   | 0.3.0        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.19.0       |
</details>

*generated on:* **2021-03-04**
</details> </pre>
</details>

**Comment by swaroop05** [comment]
I'm facing same issue..

**Comment by sp-ricard-valverde** [comment]
I've posted the issue in the apple forums too just in case:

https://developer.apple.com/forums/thread/675418

**Comment by max-ott** [comment]
The App Store Connect API does not support Enterprise accounts.

**Comment by sp-ricard-valverde** [comment]
Well it does not support API Keys for sure but it did work with a 2FA authenticated account before March 3 for sure, we've been using it extensively 😕

**Comment by sp-ricard-valverde** [comment]
So, turns out that our Enterprise account expired the very same day apple warned us about the misleading additional authentication requirement, aaaand the account _owner_ was on holidays that week(the one to receive the apple email about account expiration) ... 

Sorry for the trouble, I'm closing this as I've already verified that the API is working fine after account renewal.
