### ISSUE TITLE
Gym sdk version list

### ISSUE THREAD

**Issue by armandobelara** [fastlane/fastlane#18334]
Hi! I'm having trouble integrating fastlane with github action for my CI/CD.

When building the iOS build, it seems that it can't proceed due to the version of sdk not found. Error is something like this below:

`2021-03-04T12:54:46.1800150Z [12:54:46]: ▸ [35mxcodebuild: error: SDK "iphoneos11.0" cannot be located.[0m`
`2021-03-04T12:54:46.2671960Z xcodebuild: error: SDK "iphoneos11.0" cannot be located.`
`2021-03-04T12:54:46.2674690Z [12:54:46]: [31mExit status: 64[0m`

Can someone enlighten me on what to put in the sdk parameter in the gym action?

Here's what I have set in the fastfile.

gym(
  workspace: XCODE_WORKSPACE,
  scheme: PROJECT_NAME,
  xcargs: "-UseNewBuildSystem=YES",
  include_bitcode: true,
  include_symbols: true,
  silent: true,
  clean: true,
  export_method: "app-store",
  configuration: "Release",
  sdk: "iphoneos11.0"
)

**Comment by max-ott** [comment]
Please read the docs: http://docs.fastlane.tools/actions/gym/#5-examples
