### ISSUE TITLE
Spaceship::TestFlight::Tester.all return unexpected token

### ISSUE THREAD

**Issue by zerxon** [fastlane/fastlane#18350]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I want to get the internal teseters from my account, but it did't work

##### Command executed
```Spaceship::Tunes.login("xxx", "xxx")```
```Spaceship::TestFlight::Tester.all(app_id: "com.xx.app")```

##### Complete output when running fastlane, including the stack trace and command used
```
Traceback (most recent call last):
	17: from apple.rb:103:in `<main>'
	16: from /Users/wallace/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/spaceship/lib/spaceship/test_flight/tester.rb:82:in `all'
	15: from /Users/wallace/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/spaceship/lib/spaceship/test_flight/client.rb:182:in `testers_for_app'
	14: from /Users/wallace/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/spaceship/lib/spaceship/client.rb:723:in `request'
	13: from /Users/wallace/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/spaceship/lib/spaceship/client.rb:879:in `send_request'
	12: from /Users/wallace/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/spaceship/lib/spaceship/client.rb:643:in `with_retry'
	11: from /Users/wallace/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/spaceship/lib/spaceship/client.rb:880:in `block in send_request'
	10: from /Users/wallace/.rvm/gems/ruby-2.6.3/gems/faraday-1.3.0/lib/faraday/connection.rb:198:in `get'
	 9: from /Users/wallace/.rvm/gems/ruby-2.6.3/gems/faraday-1.3.0/lib/faraday/connection.rb:492:in `run_request'
	 8: from /Users/wallace/.rvm/gems/ruby-2.6.3/gems/faraday-1.3.0/lib/faraday/rack_builder.rb:154:in `build_response'
	 7: from /Users/wallace/.rvm/gems/ruby-2.6.3/gems/faraday_middleware-1.0.0/lib/faraday_middleware/response_middleware.rb:36:in `call'
	 6: from /Users/wallace/.rvm/gems/ruby-2.6.3/gems/faraday-1.3.0/lib/faraday/response.rb:59:in `on_complete'
	 5: from /Users/wallace/.rvm/gems/ruby-2.6.3/gems/faraday_middleware-1.0.0/lib/faraday_middleware/response_middleware.rb:38:in `block in call'
	 4: from /Users/wallace/.rvm/gems/ruby-2.6.3/gems/faraday_middleware-1.0.0/lib/faraday_middleware/response_middleware.rb:45:in `process_response'
	 3: from /Users/wallace/.rvm/gems/ruby-2.6.3/gems/faraday_middleware-1.0.0/lib/faraday_middleware/response_middleware.rb:56:in `parse'
	 2: from /Users/wallace/.rvm/gems/ruby-2.6.3/gems/faraday_middleware-1.0.0/lib/faraday_middleware/response/parse_json.rb:13:in `block in <class:ParseJson>'
	 1: from /Users/wallace/.rvm/gems/ruby-2.6.3/gems/json-2.5.1/lib/json/common.rb:216:in `parse'
/Users/wallace/.rvm/gems/ruby-2.6.3/gems/json-2.5.1/lib/json/common.rb:216:in `parse': 809: unexpected token at '<!DOCTYPE html><html lang="en"> (JSON::ParserError)
<head>
<title></title>
<link rel="stylesheet" href="/styles/main.css">
<style type='text/css'>
    /*include ../../dist/styles/main.css*/
</style>
</head>

<body><div id="wrapper" class="j42">
<h2>Not Found</h2></div>

<div class="footer">
    <p>Copyright &copy; <span id='year'>2015</span> Apple Inc. All rights reserved.</p>
    <ul><li><a href="https://www.apple.com/legal/internet-services/itunes/">Terms of Service</a></li><li><a href="https://www.apple.com/legal/privacy">Privacy Policy</a></li></ul>
</div>


<script type='text/javascript'>(function() {
    var isIos = navigator.userAgent.match(/(iPod|iPhone|iPad)/);
    document.body.setAttribute( 'class', (!isIos) ? 'otherBrowser' : 'isMobileSafari' )
    var yearEl = document.getElementById('year');
    if (yearEl) { yearEl.textContent = new Date().getFullYear(); }
})();
</script>

</body>
</html>'
```

### Environment

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.2                                        |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.29.2                          |
| Installation Source         | ~/.rvm/gems/ruby-2.6.3/bin/fastlane         |
| Host                        | macOS 11.2 (20D64)                          |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.3/lib                |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/XCode.app/Contents/Developer/ |
| Xcode Version               | 12.4                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

**Comment by max-ott** [comment]
Which version of fastlane are you using?
