### ISSUE TITLE
[match]Caught Encoding::CompatibilityError at ',       "deviceClass': incompatible character encodings: UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by phil-zZ** [fastlane/fastlane#18359]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
```
  }, {
    "type" : "devices",
    "id" : "2RD3XBZ2Z4",
    "attributes" : {
      "addedDate" : "2021-02-01T05:34:02.000+0000",
      "name" : "Jingyuuuuu",
      "deviceClass" : "IPHONE",
      "model" : "iPhone XR",
      "udid" : "00008xxxxxx",
      "platform" : "IOS",
      "status" : "ENABLED"
    },
    "links" : {
      "self" : "https://api.appstoreconnect.apple.com/v1/devices/2RD3XBZ2Z4"
    }
  } ],
  "links" : {
    "self" : "https://api.appstoreconnect.apple.com/v1/profiles?include=devices"
  },
  "meta" : {
    "paging" : {
      "total" : 3,
      "limit" : 20
    }
  }
}
UTF-8
<<<<<<<<<<<<<<<<<<<<<<<<<<<<
+----------------+-------+
|      Lane Context      |
+----------------+-------+
| ENVIRONMENT    | adhoc |
| LANE_NAME      | ipa   |
| VERSION_NUMBER | 2.2.0 |
| BUILD_NUMBER   | 783   |
+----------------+-------+
[11:00:32]: Caught Encoding::CompatibilityError at ',
      "deviceClass': incompatible character encodings: UTF-8 and ASCII-8BIT

+------+---------------------------+-------------+
|                fastlane summary                |
+------+---------------------------+-------------+
| Step | Action                    | Time (in s) |
+------+---------------------------+-------------+
| 1    | app_store_connect_api_key | 0           |
| 2    | get_version_number        | 0           |
| 3    | get_build_number          | 0           |
| 💥   | match                     | 24          |
+------+---------------------------+-------------+
```

##### Command executed
```swift
match(
	type: env.sign,
	readonly: false,
	appIdentifier: [env.identifier],
	cloneBranchDirectly: true,
	forceForNewDevices: true
)
```

##### Complete output when running fastlane, including the stack trace and command used

<details>

  ![WX20210309-110654](https://user-images.githubusercontent.com/626401/110418415-7affbd00-80d2-11eb-989e-ae5a023d5878.png)

</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.177.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-lizard    | 1.3.3   | ✅ Up-To-Date  |
| fastlane-plugin-sentry    | 1.8.1   | ✅ Up-To-Date  |
| fastlane-plugin-fir_cli   | 2.0.12  | ✅ Up-To-Date  |
| fastlane-plugin-ding_talk | 0.1.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.5.0        |
| executable-hooks              | 1.6.0        |
| bundler-unload                | 1.0.2        |
| rubygems-bundler              | 1.4.5        |
| bundler                       | 2.1.4        |
| psych                         | 3.3.0        |
| stringio                      | 3.0.0        |
| strscan                       | 3.0.0        |
| rake                          | 13.0.3       |
| CFPropertyList                | 3.0.3        |
| concurrent-ruby               | 1.1.7        |
| i18n                          | 1.8.5        |
| minitest                      | 5.14.2       |
| thread_safe                   | 0.3.6        |
| tzinfo                        | 1.2.8        |
| activesupport                 | 5.2.4.4      |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| multi_json                    | 1.15.0       |
| http-accept                   | 1.7.0        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| http-cookie                   | 1.0.3        |
| mime-types-data               | 3.2021.0225  |
| mime-types                    | 3.3.1        |
| netrc                         | 0.11.0       |
| rest-client                   | 2.1.0        |
| api_tools                     | 0.1.1        |
| thor                          | 0.20.3       |
| admqr_knife                   | 0.1.5        |
| httpclient                    | 2.8.3        |
| json                          | 2.5.1        |
| algoliasearch                 | 1.27.5       |
| artifactory                   | 3.0.15       |
| atomos                        | 0.1.3        |
| aws-eventstream               | 1.1.1        |
| aws-partitions                | 1.431.1      |
| aws-sigv4                     | 1.2.3        |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.112.1      |
| aws-sdk-kms                   | 1.42.0       |
| aws-sdk-s3                    | 1.90.0       |
| babosa                        | 1.0.4        |
| chunky_png                    | 1.4.0        |
| claide                        | 1.0.3        |
| clamp                         | 1.3.2        |
| fuzzy_match                   | 2.0.4        |
| nap                           | 1.1.0        |
| ffi                           | 1.13.1       |
| ethon                         | 0.12.0       |
| typhoeus                      | 1.4.0        |
| cocoapods-core                | 1.10.0       |
| cocoapods-deintegrate         | 1.0.4        |
| cocoapods-downloader          | 1.4.0        |
| cocoapods-plugins             | 1.0.0        |
| cocoapods-search              | 1.0.0        |
| cocoapods-trunk               | 1.5.0        |
| cocoapods-try                 | 1.2.0        |
| colored2                      | 3.1.2        |
| escape                        | 0.0.4        |
| fourflusher                   | 2.3.1        |
| gh_inspector                  | 1.1.3        |
| molinillo                     | 0.6.6        |
| ruby-macho                    | 1.4.0        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| cocoapods                     | 1.10.0       |
| coderay                       | 1.1.3        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| digest-crc                    | 0.6.3        |
| dotenv                        | 2.7.6        |
| emoji_regex                   | 3.2.2        |
| excon                         | 0.79.0       |
| faraday-net_http              | 1.0.1        |
| multipart-post                | 2.0.0        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.3        |
| jwt                           | 2.2.2        |
| memoist                       | 0.16.2       |
| os                            | 1.1.1        |
| signet                        | 0.15.0       |
| googleauth                    | 0.16.0       |
| mini_mime                     | 1.0.2        |
| uber                          | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| google-api-client             | 0.38.0       |
| rexml                         | 3.2.4        |
| webrick                       | 1.7.0        |
| google-apis-core              | 0.3.0        |
| google-apis-iamcredentials_v1 | 0.2.0        |
| google-apis-storage_v1        | 0.3.0        |
| google-cloud-env              | 1.5.0        |
| google-cloud-errors           | 1.0.1        |
| google-cloud-core             | 1.5.0        |
| google-cloud-storage          | 1.30.0       |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| plist                         | 3.6.0        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| simctl                        | 1.6.8        |
| slack-notifier                | 2.3.2        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| word_wrap                     | 1.0.0        |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| xcpretty-travis-formatter     | 1.0.1        |
| fastlane-plugin-ding_talk     | 0.1.1        |
| rqrcode                       | 0.10.1       |
| ruby_android_apk              | 0.7.7.1      |
| fir-cli                       | 2.0.12       |
| fastlane-plugin-fir_cli       | 2.0.12       |
| method_source                 | 1.0.0        |
| pry                           | 0.14.0       |
| fastlane-plugin-lizard        | 1.3.3        |
| fastlane-plugin-sentry        | 1.8.1        |
| mini_portile2                 | 2.5.0        |
| racc                          | 1.5.2        |
| nokogiri                      | 1.11.1       |
| slather                       | 2.6.1        |
</details>

*generated on:* **2021-03-09**
</details>

**Comment by revolter** [comment]
@cdoky, How did you fix this issue?

**Comment by revolter** [comment]
It was caused by the fact that I had a device named `👾 Iulian's iPhone 11 Pro Max`, but it used to work a couple of months ago :(

**Comment by cdoky** [comment]
> @cdoky, How did you fix this issue?

```ruby
JSON.iconv('utf-8', 'utf-16be', bytes)
puts "path: ~/.rvm/gems/ruby-2.7.2/gems/json-2.5.1/lib/json/pure/parser.rb:183 -- any thing"
```

**Comment by cdoky** [comment]
I don't know why, but as long as you type any string after this line`JSON.iconv('utf-8', 'utf-16be', bytes)`, it won't get an error.

**Comment by cdoky** [comment]
I don't know why, but as long as I print any string after this line `JSON.iconv('utf-8', 'utf-16be', bytes)`, I won't get an error.

file: `gems/json-2.5.1/lib/json/pure/parser.rb`
