### ISSUE TITLE
Lane download_dsyms Error: Unauthorised Access

### ISSUE THREAD

**Issue by kwstasna** [fastlane/fastlane#18357]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm having an issue here with `download_dsyms` command. The error is because of the `api_key` missing.
Although in documentation [here](https://docs.fastlane.tools/actions/download_dsyms/) you don't mention anywhere that you accept API_KEY, like you do in `upload_to_testflight`.
Is there any work around? 

##### Command executed
```
      download_dsyms(
        username: "email@example.com",
        team_name: ENV["MATCH_TEAM_NAME"],
        app_identifier: ENV["BUNDLE_IDENTIFIER"],
        min_version: options[:min_version],
        output_directory: "fastlane/dsyms"
      )
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [18:59:00]: ----------------------------
[18:59:00]: --- Step: download_dsyms ---
[18:59:00]: ----------------------------
[18:59:00]: Login to App Store Connect (email@example.com)
Available session is not valid any more. Continuing with normal login.
This account is being prompted to upgrade to 2FA
Attempting to automatically bypass the upgrade until a later date
To disable this, remove SPACESHIP_SKIP_2FA_UPGRADE=1 environment variable
+------------------+------------------+
|            Lane Context             |
+------------------+------------------+
| ENVIRONMENT      | xm               |
| DEFAULT_PLATFORM | ios              |
| PLATFORM_NAME    | ios              |
| LANE_NAME        | ios upload_dsyms |
+------------------+------------------+
[18:59:25]: Unauthorized Access

+------+---------------------------------------------+-------------+
|                         fastlane summary                         |
+------+---------------------------------------------+-------------+
| Step | Action                                      | Time (in s) |
+------+---------------------------------------------+-------------+
| 1    | Verifying fastlane version                  | 0           |
| 2    | default_platform                            | 0           |
| 3    | mkdir -p ../reports/static_analysis || true | 0           |
| 4    | mkdir ../dist || true                       | 0           |
| 5    | bundle _2.1.4_ install                      | 0           |
| 💥   | download_dsyms                              | 25          |
+------+---------------------------------------------+-------------+

[18:59:25]: fastlane finished with errors </pre>
</details>

### Environment
<details>
  <pre> <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.6                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane         |
| Host                        | Mac OS X 10.15.6 (19G2021)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.5                                        |

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.174.0 | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                      | Version | Update-Status      |
| --------------------------- | ------- | ------------------ |
| fastlane-plugin-badge       | 1.3.0   | 🚫 Update available |
| fastlane-plugin-test_center | 3.8.3   | 🚫 Update available |

<details>

<summary>
<b>Loaded gems</b>

</summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.1.0        |
| bundler                       | 2.1.4        |
| rake                          | 13.0.3       |
| CFPropertyList                | 3.0.3        |
| concurrent-ruby               | 1.1.5        |
| i18n                          | 0.9.5        |
| minitest                      | 5.11.3       |
| thread_safe                   | 0.3.6        |
| tzinfo                        | 1.2.5        |
| activesupport                 | 4.2.11.1     |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| artifactory                   | 3.0.15       |
| atomos                        | 0.1.3        |
| aws-eventstream               | 1.1.0        |
| aws-partitions                | 1.427.0      |
| aws-sigv4                     | 1.2.2        |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.112.0      |
| aws-sdk-kms                   | 1.42.0       |
| aws-sdk-s3                    | 1.88.1       |
| babosa                        | 1.0.4        |
| curb                          | 0.9.10       |
| fastimage                     | 2.2.2        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| dotenv                        | 2.7.6        |
| emoji_regex                   | 3.2.1        |
| excon                         | 0.79.0       |
| faraday-net_http              | 1.0.1        |
| multipart-post                | 2.0.0        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| gh_inspector                  | 1.1.3        |
| jwt                           | 2.2.2        |
| memoist                       | 0.16.2       |
| multi_json                    | 1.15.0       |
| os                            | 1.1.1        |
| signet                        | 0.14.1       |
| googleauth                    | 0.15.1       |
| httpclient                    | 2.8.3        |
| mini_mime                     | 1.0.2        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| uber                          | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| google-api-client             | 0.38.0       |
| digest-crc                    | 0.6.3        |
| rexml                         | 3.2.4        |
| webrick                       | 1.7.0        |
| google-apis-core              | 0.2.1        |
| google-apis-iamcredentials_v1 | 0.1.0        |
| google-apis-storage_v1        | 0.2.0        |
| google-cloud-env              | 1.4.0        |
| google-cloud-errors           | 1.0.1        |
| google-cloud-core             | 1.5.0        |
| google-cloud-storage          | 1.30.0       |
| json                          | 2.5.1        |
| mini_magick                   | 4.9.5        |
| plist                         | 3.6.0        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| naturally                     | 2.2.1        |
| simctl                        | 1.6.8        |
| slack-notifier                | 2.3.2        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| word_wrap                     | 1.0.0        |
| claide                        | 1.0.3        |
| colored2                      | 3.1.2        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| xcpretty-travis-formatter     | 1.0.1        |
| badge                         | 0.11.0       |
| chunky_png                    | 1.3.11       |
| clamp                         | 1.3.0        |
| fuzzy_match                   | 2.0.4        |
| nap                           | 1.1.0        |
| cocoapods-core                | 1.6.1        |
| cocoapods-deintegrate         | 1.0.4        |
| cocoapods-downloader          | 1.2.2        |
| cocoapods-plugins             | 1.0.0        |
| cocoapods-search              | 1.0.0        |
| cocoapods-stats               | 1.1.0        |
| netrc                         | 0.11.0       |
| cocoapods-trunk               | 1.3.1        |
| cocoapods-try                 | 1.1.0        |
| escape                        | 0.0.4        |
| fourflusher                   | 2.2.0        |
| molinillo                     | 0.6.6        |
| ruby-macho                    | 1.4.0        |
| cocoapods                     | 1.6.1        |
| colorize                      | 0.8.1        |
| fastlane-plugin-badge         | 1.3.0        |
| xctest_list                   | 1.1.8        |
| fastlane-plugin-test_center   | 3.8.3        |
| imatcher                      | 0.1.9        |
| mini_portile2                 | 2.4.0        |
| nokogiri                      | 1.10.2       |
| slather                       | 2.4.7        |
</details>

*generated on:* **2021-03-08** </pre>
</details>
</details>

**Comment by topLayoutGuide** [comment]
Seeing the same issue here.

**Comment by phynet** [comment]
I think this problem is related with the 2FA, Apple moved the account to use Api Key's instead. I don't know if fastlane will update this lane to use api key. I'm waiting to know :D

**Comment by tmxkevingriesbach** [comment]
As sad as it is, this was discussed a bunch of times already. It is not currently fixable, because Apple does not offer a dsym download API using their ASC API-key: https://github.com/fastlane/fastlane/discussions/17485

**Comment by max-ott** [comment]
ASC Connect API does not provide this endpoint. This is an "issue" on Apple's side.
