### ISSUE TITLE
upload_symbols_to_crashlytics succeeds even if upload fails

### ISSUE THREAD

**Issue by liamnichols** [fastlane/fastlane#18353]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When running the `upload_symbols_to_crashlytics` action, it'll complete successfully even some or all of the calls to the upload-symbols binary actually fail as illustrated in the following console output:

```
[11:53:34]: -------------------------------------------
[11:53:34]: --- Step: upload_symbols_to_crashlytics ---
[11:53:34]: -------------------------------------------
[11:53:35]: Uploading '1.dSYM.zip'...
[11:53:56]: Shell command exited with exit status  instead of 0.
[11:53:56]: Uploading '2.dSYM.zip'...
[11:54:00]: Shell command exited with exit status  instead of 0.
[11:54:00]: Uploading '3.dSYM.zip'...
[11:54:01]: Shell command exited with exit status  instead of 0.
[11:54:01]: Uploading '4.dSYM.zip'...
[11:54:02]: Shell command exited with exit status  instead of 0.
[11:54:02]: Successfully uploaded dSYM files to Crashlytics 💯
``` 

Looking through the action code, this actually appears to be intentional:

https://github.com/fastlane/fastlane/blob/83ebc377791c30e428a214737bd0c9583b5758f5/fastlane/lib/fastlane/actions/upload_symbols_to_crashlytics.rb#L74-L76

However I'm not 100% convinced that this is the right path. In some use cases, it's not uncommon to run the `upload_symbols_to_crashlytics` lane after waiting for App Store Connect to process a build, which can take hours. If this fails silently, it's likely that the issue won't be discovered until Firebase starts seeing unsymbolicated crashes (which isn't completely clear) or if you dig into the console output from a CI job. 

While I'm raising this as a bug report, I'm also using it as a chance to gain some insight from the community to discover how we should handle it.. I guess there are a few obvious solutions:

1. Leave it working 'as expected'
2. Fail with a [`shell_error`](https://github.com/fastlane/fastlane/blob/48151291f2c4949c3b1b9919ba2cc81a7cc33293/fastlane_core/lib/fastlane_core/ui/interface.rb#L144-L154) 
3. Add a `FastlaneCore::ConfigItem` called `fail_on_error` or something similar to allow us to customise the behaviour
    - But which default value should we use? 

Personally speaking, I'm leaning towards option 3 with a default behaviour of failing the action, but I think I lack overall context of how actions should be expected to behave. Is there a consistent pattern to follow here? 

I'm happy to submit a patch but would just like to agree on an approach first 👍

**Comment by liamnichols** [comment]
please don't close @fastlane-bot 😄

**Comment by ainame** [comment]
> Add a FastlaneCore::ConfigItem called fail_on_error or something similar to allow us to customise the behaviour

This makes sense to me! I suppose this action has been used within a release operation, which people don't want fastlane to crash at the end of the process after spending on very expensive operations like `build_app` on CI😅 Having that option won't bother existing fastlane users but still can make it right for the use-case using that action for a small handy script just to download and upload dSYM. The need arose since downloading dSYM can't be done with App Store Connect API's key and some people want to run such script locally.

Slack action has exactly the same option to behave so. It should be applicable for other actions 🚀  
https://github.com/fastlane/fastlane/blob/620cf59b4d9a4513de24971cd17ea97f84906939/fastlane/lib/fastlane/actions/slack.rb#L239-L244
