### ISSUE TITLE
Sandbox Tester creation with Fastlane errors out with an unexpected Response  error.

### ISSUE THREAD

**Issue by cris-mwaura** [fastlane/fastlane#18369]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

We currently have a process within which we have sandbox testers created. Recently ever since the rollout of the new 2FA from Apple it seems like the process of creating sandbox testers has been flaky and now completely erroring out. I am still using the code snippet on the Shapeship readme

```
Spaceship::Tunes::SandboxTester.create!(
      first_name: "abc",
      last_name: "abc",
      email: "email",
      password: "password",
    )
```
As well as using the 8hr token thats generated with Spaceship (tried using api key but i think that the API keys do not have access to /Iris/* endpoints.

The Error that i see  is

`Spaceship::UnexpectedResponse: {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Not Found"], "info"=>nil}, "statusCode"=>"ERROR"}`

I tried this in different environments and still ended up with the same issue.

##### Command executed

```
Spaceship::Tunes::SandboxTester.create!(
      first_name: "abc",
      last_name: "abc",
      email: "email",
      password: "password",
    )
```
##### Complete output when running fastlane, including the stack trace and command used

```Uncaught exception: {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Not Found"], "info"=>nil}, "statusCode"=>"ERROR"}
	/Users/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.132.0/spaceship/lib/spaceship/client.rb:709:in `parse_response'
	/Users/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.132.0/spaceship/lib/spaceship/tunes/tunes_client.rb:1458:in `create_sandbox_tester!'
	/Users/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.132.0/spaceship/lib/spaceship/tunes/sandbox_tester.rb:46:in `create!'
	/Users/ruby/sandbox_tester.rb:35:in `create_sandbox_tester'
	/Users/ruby/sandbox_tester.rb:15:in `initialize'
	/Users/ruby/ios_users.rb:66:in `new'
	/Users/ruby/ios_users.rb:66:in `block in create_sandbox_accounts'
	/Users/ruby/ios_users.rb:60:in `times'
	/Users/ruby/ios_users.rb:60:in `create_sandbox_accounts'
	/Users/ruby/ios_users.rb:141:in `lambda_handler'
	/Users/ruby/ios_users.rb:146:in `<top (required)>'
```

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by max-ott** [comment]
The ASC API keys only have access to the "official" endpoints. Is it working with an Apple ID and 2FA enabled?

**Comment by cris-mwaura** [comment]
Hi @max-ott. Thank you for your response. It doesn't seem to work with the 2FA enabled. It's kind of strange in that it was working for a while and somewhere around February it just stopped. At that point, i tried regenerating the session_token, which works in getting all of the sandbox users but fails during creation of sandbox users. 

https://github.com/fastlane/fastlane/blob/6702e2eeef1f383b3627b940f6e6c76d4ebc1551/spaceship/lib/spaceship/tunes/tunes_client.rb#L1450

I did a rough debug session and realized that it  was the `request` being sent over to the unofficial `iris` api. So I tried a few things:

1. use `spaceship playground` to try and generate the creation of users.
2. change the data and allow for the defaults to be passed in here:

https://github.com/fastlane/fastlane/blob/6702e2eeef1f383b3627b940f6e6c76d4ebc1551/spaceship/lib/spaceship/tunes/sandbox_tester.rb#L45

Still ended up with the same traceback shown above.

**Comment by max-ott** [comment]
I don't think this has anything to do with the 2FA change. Maybe they changed something on their end. It also seems that you are still using the old `Spaceship::Tunes` instead of `Spaceship::ConnectAPI`. Can you check if we already have actions over there?

**Comment by cris-mwaura** [comment]
yeah i did. I think because connectAPI focuses on the API's provided by apple, it is not there. Will post stack trace below:

```Uncaught exception: The URL path is not valid - The resource 'sandboxTesters' does not exist
	/Users/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.177.0/spaceship/lib/spaceship/connect_api/api_client.rb:199:in `handle_response'
	/Users/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.177.0/spaceship/lib/spaceship/connect_api/api_client.rb:113:in `get'
	/Users/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.177.0/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:1133:in `get_sandbox_testers'
	/Users/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/forwardable-1.3.2/lib/forwardable.rb:238:in `get_sandbox_testers'
	/Users/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.177.0/spaceship/lib/spaceship/connect_api/models/sandbox_tester.rb:41:in `all'
	/Users/tools/test-account-creation/ruby/ios_users.rb:140:in `lambda_handler'
	/Users/tools/test-account-creation/ruby/ios_users.rb:146:in `<top (required)>'
```

Seems like it's unable to find the resource.

**Comment by max-ott** [comment]
@cris-mwaura I think you are mixing up things. `ConnectAPI` does not mean it uses the official API. Josh introduced `ConnectAPI` when Apple changed most parts of App Store Connect. It tries to use as much of the "official" API as possible, but as you have noticed Apple actually has 2 different APIs. Their "internal" one using `/iris` and the public one. Fastlane uses both to provide the broadest possible feature set. 

I just tried out `response = Spaceship::ConnectAPI.get_sandbox_testers` and get all Sandbox testers, so the "new" code definitely works, e.g. here: https://github.com/fastlane/fastlane/blob/2c34e6573dcf0014670af3a554fa92a9ad2566b7/spaceship/lib/spaceship/connect_api/tunes/tunes.rb#L1131

The `post_sandbox_testers` should be the method to create new testers. I just tested it and it worked:
```
attributes = {}
# Then go through all attributes like this
attributes["email"] = "test@sample.com"
...
Spaceship::ConnectAPI.post_sandbox_tester(attributes: attributes)
```

You can find all attributes here: https://github.com/fastlane/fastlane/blob/2bdb19d08db3964ddf6b20c830c63eb069b5a1ed/spaceship/lib/spaceship/connect_api/models/sandbox_tester.rb#L47

**Comment by cris-mwaura** [comment]
Hi Max, 

I tried this with `post_sandbox_tester` and it seems like it's still not working on my end. The code i added was `Spaceship::ConnectAPI.post_sandbox_tester(attributes: attributes)` and within the attributes i added all the params. 

```
Uncaught exception: The URL path is not valid - The resource 'sandboxTesters' does not exist
	/Users/cris/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.177.0/spaceship/lib/spaceship/connect_api/api_client.rb:199:in `handle_response'
	/Users/cris/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.177.0/spaceship/lib/spaceship/connect_api/api_client.rb:124:in `post'
	/Users/cris/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.177.0/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:1144:in `post_sandbox_tester'
	/Users/cris/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/forwardable-1.3.2/lib/forwardable.rb:238:in `post_sandbox_tester'
	/Users/cris/HeadspaceProjects/tools/test-account-creation/ruby/sandbox_tester.rb:46:in `create_sandbox_tester'
	/Users/cris/HeadspaceProjects/tools/test-account-creation/ruby/sandbox_tester.rb:15:in `initialize'
	/Users/cris/HeadspaceProjects/tools/test-account-creation/ruby/ios_users.rb:66:in `new'
	/Users/cris/HeadspaceProjects/tools/test-account-creation/ruby/ios_users.rb:66:in `block in create_sandbox_accounts'
	/Users/cris/HeadspaceProjects/tools/test-account-creation/ruby/ios_users.rb:60:in `times'
	/Users/cris/HeadspaceProjects/tools/test-account-creation/ruby/ios_users.rb:60:in `create_sandbox_accounts'
	/Users/cris/HeadspaceProjects/tools/test-account-creation/ruby/ios_users.rb:144:in `lambda_handler'
	/Users/cris/HeadspaceProjects/tools/test-account-creation/ruby/ios_users.rb:147:in `<top (required)>'

Process finished with exit code 1```

This is done after both generating the token with connectAPI and a P8 key as well as after i also did a spaceship login.

**Comment by cris-mwaura** [comment]
Can we perhaps reopen this issue pls

**Comment by max-ott** [comment]
I'm not able to repro the steps. What are your attributes? How are you creating them? What is the role of your Apple ID? I don't think the official App Store Connect API supports this feature, therefore you get the problem. How do you login?
