### ISSUE TITLE
Metadata: Add ability to use erb or other templates

### ISSUE THREAD

**Issue by bkazez** [fastlane/fastlane#18365]
For multi-target apps, often the metadata differences are small (e.g., adding "Pro" to a name). It would be very useful to be able to use templates (erb, etc.) to customize metadata. For example, instead of `name.txt`, use `name.erb`:

```
MyApp <% ENV['IS_PRO'] ? 'Pro' : 'Free' %>
```

**Comment by max-ott** [comment]
Discussions are for feature requests. If you'll like to directly add this to Fastlane, we're completely open source, feel free to open a pull request!
