### ISSUE TITLE
[scan] derived data path defaults to /Users

### ISSUE THREAD

**Issue by kroussevrb** [fastlane/fastlane#18360]
The issue is the same as 
https://github.com/fastlane/fastlane/issues/15910

which is the same as
https://github.com/fastlane/fastlane/issues/15236

and both times there has been no action taken

**Comment by RenatGafarov** [comment]
We have same problem too.
Fastlane use default derived data path for xcarchive validation

**Comment by max-ott** [comment]
@kroussevrb This is still an open source project. Feel free to open a pull request or pay a freelancer to do so.

**Comment by rogerluan** [comment]
@kroussevrb if you can provide a .zip with a project where you can reproduce this issue, that'd be helpful. It's not clear to me when or why the `BUILT_PRODUCTS_DIR` would be empty yet
