### ISSUE TITLE
increment_build_number should allow bumping all compatible version numbers

### ISSUE THREAD

**Issue by lhunath** [fastlane/fastlane#18368]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
`increment_build_number` only supports version numbers of the format `A`, `A.B`, or `A.B.C`. This is idealistic and there is no reason to place a hard-cap on this.  There are valid reasons why developers may want different version schemes that are still 100% compatible with TestFlight and the App Store, such as `A.B.C.D`.

`increment_build_number`'s default strategy should be to just bump the latest identifier, akin to:

```
    build = get_build_number().split(".").map(&:to_i)
    build[-1] += 1
    increment_build_number(build_number: build.join("."))
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.2.2                                                         |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.30.1                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.2.2 (20D80)                                           |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.4                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   | en_CA.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
opt_out_usage
update_fastlane

platform :ios do
  desc "Build an application archive"
  lane :archive do
    ensure_no_debug_code(text: "<<<<<<|WIP:", exclude_dirs: [".git", "fastlane"])
    #verify_xcode
    cocoapods
    #swiftlint

    build_app(scheme: "Spectre-iOS", export_options: { method: "ad-hoc" })
    verify_build
  end

  desc "Build an application archive and send it to TestFlight"
  lane :beta do
    ensure_git_status_clean
    ensure_git_branch(branch: "^stream/(alpha|beta|probe)$")

    archive
    install_on_device(skip_wifi: true)
    prompt(boolean: true, text: "Please test the app on your device. Is everything alright?") # TODO: check
    upload_to_testflight
    download_dsyms
    sentry_upload_dsym #(include_sources: true)

    build = get_build_number().split(".").map(&:to_i)
    build[-1] += 1
    increment_build_number(build_number: build.join("."))
  end

  lane :release do
    #precheck
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("app.spectre")

apple_id("lhunath@lyndir.com")
itc_team_id("153897")
team_id("HL3Q45LX9N")

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.177.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                 | Version | Update-Status |
| ---------------------- | ------- | ------------- |
| fastlane-plugin-sentry | 1.8.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.5.0        |
| slack-notifier                | 2.3.2        |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| terminal-notifier             | 2.0.0        |
| terminal-table                | 1.8.0        |
| plist                         | 3.6.0        |
| addressable                   | 2.7.0        |
| multipart-post                | 2.0.0        |
| word_wrap                     | 1.0.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| artifactory                   | 3.0.15       |
| babosa                        | 1.0.4        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| excon                         | 0.79.0       |
| faraday-net_http              | 1.0.1        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.3        |
| gh_inspector                  | 1.1.3        |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| xcpretty-travis-formatter     | 1.0.1        |
| dotenv                        | 2.7.6        |
| simctl                        | 1.6.8        |
| jwt                           | 2.2.2        |
| uber                          | 0.1.0        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| mini_mime                     | 1.0.2        |
| httpclient                    | 2.8.3        |
| google-api-client             | 0.38.0       |
| google-cloud-errors           | 1.0.1        |
| google-cloud-core             | 1.5.0        |
| digest-crc                    | 0.6.3        |
| google-cloud-storage          | 1.30.0       |
| emoji_regex                   | 3.2.2        |
| nanaimo                       | 0.3.0        |
| colored2                      | 3.1.2        |
| claide                        | 1.0.3        |
| CFPropertyList                | 3.0.3        |
| atomos                        | 0.1.3        |
| xcodeproj                     | 1.19.0       |
| unicode-display_width         | 1.7.0        |
| public_suffix                 | 4.0.6        |
| json                          | 2.5.1        |
| bundler                       | 2.2.7        |
| multi_json                    | 1.15.0       |
| signet                        | 0.15.0       |
| os                            | 1.1.1        |
| memoist                       | 0.16.2       |
| googleauth                    | 0.16.0       |
| google-cloud-env              | 1.5.0        |
| webrick                       | 1.7.0        |
| rexml                         | 3.2.4        |
| google-apis-core              | 0.3.0        |
| google-apis-iamcredentials_v1 | 0.2.0        |
| google-apis-storage_v1        | 0.3.0        |
| rake                          | 13.0.3       |
| aws-eventstream               | 1.1.1        |
| aws-sigv4                     | 1.2.3        |
| aws-partitions                | 1.431.1      |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.112.1      |
| aws-sdk-kms                   | 1.42.0       |
| aws-sdk-s3                    | 1.90.0       |
| forwardable                   | 1.3.2        |
| logger                        | 1.4.3        |
| date                          | 3.1.1        |
| stringio                      | 3.0.0        |
| zlib                          | 1.1.0        |
| ipaddr                        | 1.2.2        |
| openssl                       | 2.1.2        |
| ostruct                       | 0.3.3        |
| strscan                       | 3.0.0        |
| fileutils                     | 1.5.0        |
| io-console                    | 0.5.7        |
| libxml-ruby                   | 3.2.1        |
| psych                         | 3.3.0        |
| mutex_m                       | 0.1.1        |
| ox                            | 2.13.2       |
| fastlane-plugin-sentry        | 1.8.1        |
</details>

*generated on:* **2021-03-09**
</details>

**Comment by max-ott** [comment]
Discussions are for feature requests. If you'll like to directly add this to Fastlane, we're completely open source, feel free to open a pull request!
