### ISSUE TITLE
FASTLANE_SESSION seems to expire after one run

### ISSUE THREAD

**Issue by gtranchedone** [fastlane/fastlane#18363]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

After one successful run on Circle CI, the 2FA session stored in `FASTLANE_SESSION` seems to expire. Oddly enough, it doesn't seem to happen on my local machine. I suspect it has something to do with the fact that the account my team uses is associated with multiple Apple Developer Teams and that we have the same workflow running for multiple apps, each associated with one team. Might that be?

##### Command executed

`upload_to_testflight` resulting in the error `2FA can only be performed in interactive mode`. Updating the `FASTLANE_SESSION` solves the issue temporarily, but within the hour the session expires again.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[11:58:08]: ----------------------------------
[11:58:08]: --- Step: upload_to_testflight ---
[11:58:08]: ----------------------------------
[11:58:08]: Login to App Store Connect (*****************************)
Session loaded from environment variable is not valid. Continuing with normal login.
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
[11:58:10]: -------------------
[11:58:10]: --- Step: is_ci ---
[11:58:10]: -------------------
[11:58:10]: Notifying result to Slack
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
[11:58:10]: -------------------
[11:58:10]: --- Step: slack ---
[11:58:10]: -------------------
/Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/slack-notifier-2.3.2/lib/slack-notifier/util/link_formatter.rb:32: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/slack-notifier-2.3.2/lib/slack-notifier/util/link_formatter.rb:38: warning: The called method `initialize' is defined here
[11:58:10]: Successfully sent Slack notification
+------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                   Lane Context                                                                                                    |
+------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM                   | ios                                                                                                                                                                          |
| PLATFORM_NAME                      | ios                                                                                                                                                                          |
| LANE_NAME                          | ios release                                                                                                                                                                  |
| KEYCHAIN_PATH                      | ~/Library/Keychains/fastlane_tmp_keychain                                                                                                                                    |
| ORIGINAL_DEFAULT_KEYCHAIN          | "/Users/distiller/Library/Keychains/login.keychain-db"                                                                                                                       |
| SIGH_PROFILE_TYPE                  | app-store                                                                                                                                                                    |
| MATCH_PROVISIONING_PROFILE_MAPPING | {REDACTED} |
| GET_INFO_PLIST_VALUE_CUSTOM_VALUE  | REDACTED                                                                                                                                                                       |
| BUILD_NUMBER                       | 202103031146                                                                                                                                                                 |
| IPA_OUTPUT_PATH                    | /Users/distiller/project/fastlane/output/REDACTED.ipa                                                                                                                    |
| XCODEBUILD_ARCHIVE                 | /Users/distiller/Library/Developer/Xcode/Archives/2021-03-03/REDACTED 2021-03-03 11.46.21.xcarchive                                                                      |
| DSYM_OUTPUT_PATH                   | /Users/distiller/project/fastlane/output/REDACTED.app.dSYM.zip                                                                                                           |
| VERSION_NUMBER                     | 20.0.0                                                                                                                                                                       |
+------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
[11:58:10]: 2FA can only be performed in interactive mode
</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.2                                        |
| Ruby                        | 2.7.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.30.1                          |
| Installation Source         | ~/.rvm/gems/ruby-2.7.2/bin/fastlane         |
| Host                        | macOS 11.2 (20D64)                          |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.7.2/lib                |
| OpenSSL Version             | OpenSSL 1.1.1h  22 Sep 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.4                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

$projects = [REDACTED]
$brands = { REDACTED }

platform :ios do
  before_all do | lane, options |
    if is_ci?
      setup_circle_ci
    else
      puts "Skipping CI configuration"
    end
  end

  error do | lane, exception, options |
    send_slack_message(
      brand: options[:brand],
      success: false,
      message: exception.to_s
    )
  end

  desc "Runs Tests for the specified brand and environment. The environment defaults to 'development'."
  lane :test do | options |
    default_build_arguments = {
      environment: :development,
      device_type: :simulator
    }
    build_arguments = default_build_arguments.merge(options)
    targets_configuration = get_targets_configuration(build_arguments)
    cocoapods(try_repo_update_on_error: true, verbose: true)
    run_unit_tests(scheme: targets_configuration[:scheme])
    prepare_build_for_automation(build_arguments)
  end

  desc "Tests and Builds a Release build of the specified brand and uploads it to Test Flight"
  lane :release do | options |
    build_arguments = options.merge({
      distribution_type: "appstore",
      environment: :production,
      device_type: :device,
      should_tag: true
    })
    deploy(build_arguments)
    prepare_build_for_automation(build_arguments)
  end

  desc "Tests and Builds an Ad-Hoc Development build of the specified brand and distributes it to testers"
  lane :build_development do | options |
    build_arguments = options.merge({
      distribution_type: "adhoc",
      environment: :development,
      device_type: :device
    })
    deploy(build_arguments)
    prepare_build_for_automation(build_arguments)
  end

  desc "Tests and Builds an Ad-Hoc Mock build of the specified brand and distributes it to testers"
  lane :build_prototype do | options |
    build_arguments = options.merge({
      distribution_type: "adhoc",
      environment: :prototype,
      device_type: :device
    })
    deploy(build_arguments)
    prepare_build_for_automation(build_arguments)
  end

  desc "Tests and Builds an Ad-Hoc Staging build of the specified brand and distributes it to testers"
  lane :build_staging do | options |
    build_arguments = options.merge({
      distribution_type: "adhoc",
      environment: :staging,
      device_type: :device
    })
    deploy(build_arguments)
    prepare_build_for_automation(build_arguments)
  end

  desc "Tests and Builds an Ad-Hoc Production build of the specified brand and distributes it to testers"
  lane :build_production do | options |
    build_arguments = options.merge({
      distribution_type: "adhoc",
      environment: :production,
      device_type: :device
    })
    deploy(build_arguments)
    prepare_build_for_automation(build_arguments)
  end

  desc "Runs the qa_prepare_build_for_automation.sh script to prepare a build for Automation Tests."
  desc "Required parameters are: brand ([brand_name])."
  desc "Optional parameters are: device_type ('DEVICE' | 'SIMULATOR'), environment ('development|staging|production'), build_number."
  lane :prepare_build_for_automation do | options |
    environment = (options[:environment] || :development).to_s.capitalize
    device_type = (options[:device_type] || :simulator).to_s.upcase
    brand_name = get_normalized_brand_name(options)
    puts "Preparing build for '#{brand_name}', device_type: '#{device_type}', environment: '#{environment}'"
    # Adjust the environment name for Development as the build folder is actually called "Debug"
    if environment == "Development"
      environment = "Debug"
    end
    sh "BRAND=#{brand_name} TYPE=#{device_type} ENVIRONMENT=#{environment} bash ../qa_prepare_build_for_automation.sh"
  end

  desc "Triggers a QA's CI Job for running UI Smoke Tests. NOTE: the build must exist already on S3."
  desc "Required parameters are: brand ([brand_name])."
  desc "Optional parameters are: device_type ('DEVICE' | 'SIMULATOR'), environment ('development|staging|production')."
  lane :trigger_automation_tests do | options |
    environment = (options[:environment] || :development).to_s.capitalize
    device_type = (options[:device_type] || :simulator).to_s.upcase
    job_number = (options[:job_number] || "0").to_s
    brand_name = get_normalized_brand_name(options)
    puts "Trigger automation tests for '#{brand_name}', device_type: '#{device_type}', environment: '#{environment}', job_number: '#{job_number}'"
    sh "BRAND=#{brand_name} TYPE=#{device_type} ENVIRONMENT=#{environment} JOB_NUMBER=#{job_number} bash ../qa_trigger_automation_tests.sh"
  end

  desc "Uploads to S3 a build prepared using the prepare_build_for_automation lane."
  desc "This lane should be used to update the reference builds used by the QA team to run their tests agains when they make changes to their CI environment."
  lane :upload_build_to_archive do | options |
    environment = (options[:environment] || :development).to_s.capitalize
    device_type = (options[:device_type] || :simulator).to_s.upcase
    brand_name = get_normalized_brand_name(options)
    puts "Upload build for '#{brand_name}', device_type: '#{device_type}', environment: '#{environment}'"
    sh "BRAND=#{brand_name} TYPE=#{device_type} ENVIRONMENT=#{environment} bash ../qa_update_reference_builds_on_s3.sh"
  end

  desc "Registers new devices and updates the Ad-Hoc provisioning profiles for all targets"
  lane :register_new_devices do | options |
    didFinishEnteringDevices = false
    new_devices = {}
    while !didFinishEnteringDevices do
      uuid = prompt(
        text: "Insert UUID"
      )
      device_name = prompt(
        text: "Insert device name"
      )
      new_devices[device_name] = uuid
      didFinishEnteringDevices = !prompt(
        text: "Do you want to add more devices?",
        boolean: true
      )
    end
    $brands.keys.each { | brand_name |
      brand_object = get_brand({ brand: brand_name })
      register_devices(
        devices: new_devices,
        team_id: brand_object[:developer_portal_team_id],
      )
      update_code_signing(options.merge({ brand: brand_name, force: true }))
    }
  end

  desc "Syncs code signing certificates and profiles for the specified brand on your machine"
  desc "Required parameters: brand:[brand_name]"
  desc "Optional parameters: distribution_type:(development|adhoc|appstore), force:(true|false)"
  lane :update_code_signing do | options |
    distribution_type = options[:distribution_type] || :adhoc
    force = options[:force] || false
    brand = get_brand(options)
    all_bundle_ids = []
    brand[:targets_configuration].values.each { | config |
      all_bundle_ids.concat config[:targets].map { | t | t[:id] } unless config[:skip_code_signing]
    }
    run_code_signing_sync(brand, all_bundle_ids, distribution_type, force)
  end

  desc "Increments the marketing version for a single brand"
  desc "Required arguments are: 'brand'."
  desc "Optional arguments are: 'bump_type'."
  lane :increment_version do | options |
    target_names = get_target_names({environment: :production}.merge(options))
    target_names.each { | target |
      increment_version_number_in_plist(
        bump_type: options[:bump_type] || "patch",
        target: target
      )
    }
    target = get_main_target_name({environment: :production}.merge(options))
    get_version_number_from_plist(target: target)
  end

  desc "Creates and pushes a release branch cut from the latest develop branch."
  desc "It also bumps the marketing version on the development branch."
  desc "By default the version increment is a minor. You can specify the bump type using passing a bump_type paramenter. Accepted values are major|minor|patch"
  lane :cut_release_candidate do | options |
    # Ensure we're on develop and pull the latest changes
    base_branch_name = "develop" # This should match the default branch name for the repository
    ensure_git_branch(branch: base_branch_name)
    git_pull
    # Define a new release branch name
    release_branch_name = "release"
    # Create the release branch and push it
    sh("git", "checkout", "-b", release_branch_name)
    sh("git", "push", "-u", "origin", release_branch_name)
    # Check out deveolp again to bump the minor version
    sh("git", "checkout", base_branch_name)
    # Bump and commit the new version number on develop and push
    new_development_version = increment_version(options)
    sh("git", "add", "--all")
    sh("git", "commit", "-m", "Bump version to #{new_development_version}")
    sh("git", "push", "-u", "origin", base_branch_name)
    # Checkout the release branch again to the developer's benefit
    sh("git", "checkout", release_branch_name)
  end

  desc "Tags the current branch with our new tagging strategy."
  desc "You need to specify brand, an environment, and a distribution type for this to work."
  lane :tag do | options |
    target = get_main_target_name(options)
    version_number = get_version_number_from_plist(target: target)
    build_number = lane_context[SharedValues::BUILD_NUMBER] || get_build_number
    environment = options[:distribution_type] == :appstore ? :appstore : options[:environment]
    normalized_brand_name = get_normalized_brand_name(options)
    add_git_tag(
      tag: "builds/#{normalized_brand_name}/#{environment}/v#{version_number}-#{build_number}"
    )
    push_git_tags
  end

  desc "Syncs certificates and provisioning profiles and updates the Xcode project for building the correct environment and target."
  desc "Required parameters: brand:[brand_name]."
  desc "Optional parameters: environment:(production|adhoc|development), distribution_type:(development|adhoc|appstore)."
  lane :update_signing_configuration do | options |
    passthrough_options = {
      distribution_type: :development,
      environment: :development
    }.merge(options).merge({ use_automatic_signing: false })
    sync_certificates(passthrough_options)
    run_code_signing_settings_update(passthrough_options)
    configure_code_signing(passthrough_options)
    update_projects_team(passthrough_options)
  end

  # === Private Lanes ===

  desc "Runs tests against a target, creates a build for that target, and deploys it"
  private_lane :deploy do | options |
    prebuild(options)
    build(options)
    postbuild(options)
    unless options[:skip_upload]
      upload_build(options)
      send_slack_message(
        brand: options[:brand]
      )
    end
  end

  private_lane :prebuild do | options |
    cocoapods(try_repo_update_on_error: true, verbose: true)
    if options[:skip_tests]
      puts "Skipping Unit Tests"
    else
      testing_options = { environment: :development }.merge(options)
      targets_configuration = get_targets_configuration(testing_options)
      run_unit_tests(targets_configuration)
    end
  end

  private_lane :postbuild do | options |
    if options[:should_tag]
      git_commit(path: ".", message: "Version Bump")
      tag(options)
    end
  end

  desc "Builds and archives the app signed with the correct profiles and certificates"
  private_lane :build do | options |
    update_signing_configuration(options)
    update_build_number(options)
    targets_configuration = get_targets_configuration(options)
    brand = get_brand(options)
    build_app(
      output_directory: "fastlane/output",
      scheme: targets_configuration[:scheme],
      codesigning_identity: brand[:code_signing_identity],
    )
  end

  private_lane :run_code_signing_settings_update do | options |
    targets_configuration = get_targets_configuration(options)
    targets_info = targets_configuration[:targets]
    targets = targets_info.map { | t | t[:name] }
    update_code_signing_settings(
      targets: targets,
      use_automatic_signing: options[:use_automatic_signing] || false
    )
  end

  desc "Runs all Unit Tests for the passed in Scheme"
  private_lane :run_unit_tests do | options |
    run_tests(
      output_directory: "fastlane/output",
      deployment_target_version: "13",
      reset_simulator: true,
      should_zip_build_products: true,
      workspace: "WirelessDigital.xcworkspace",
      scheme: options[:scheme],
      clean: true,
      skip_slack: true
    )
  end

  desc "Updates the build number for the project using the current date and time"
  private_lane :update_build_number do | options |
    target_names = get_target_names({environment: :production}.merge(options))
    target_names.each { | target |
      increment_build_number_in_plist(
        target: target,
        build_number: Time.new.strftime("%Y%m%d%H%M")
      )
    }
  end

  private_lane :upload_build do | options |
    if options[:distribution_type].to_s == "appstore"
      brand = get_brand(options)
      target = get_main_target_name(options)
      version_number = get_version_number_from_plist(target: target)
      upload_to_testflight(
        app_version: version_number,
        team_id: brand[:app_store_connect_team_id]
      )
    else
      targets_configuration = get_targets_configuration(options)
      firebase_app_distribution(
        app: targets_configuration[:firebase_app_id],
        groups: "qa, ios-engineers, team-managers",
        release_notes: "Branch: #{git_branch}"
      )
    end
  end

  desc "Downloads code signing certificates and provisioning profiles"
  private_lane :sync_certificates do | options |
    brand = get_brand(options)
    targets_configuration = get_targets_configuration(options)
    app_identifiers = targets_configuration[:targets].map { |target| target[:id] }
    run_code_signing_sync(brand, app_identifiers, options[:distribution_type] || :development)
  end

  desc "Makes sure all provisioning profiles are set for the target before building"
  private_lane :configure_code_signing do | options |
    brand = get_brand(options)
    targets_configuration = get_targets_configuration(options)
    targets = targets_configuration[:targets]
    targets.each do | target |
      update_project_provisioning(
        profile: ENV["sigh_#{target[:id]}_#{options[:distribution_type].to_s}_profile-path"],
        target_filter: target[:name],
        code_signing_identity: brand[:code_signing_identity]
      )
    end
  end

  # === Helpers ===

  def get_brand(options)
    normalized_brand_name = get_normalized_brand_name(options)
    brand = $brands[normalized_brand_name.to_sym]
    available_brands = $brands.keys.map { | b | b.to_s }
    UI.user_error!("Invalid brand name '#{normalized_brand_name}'. Available brands: #{available_brands}") unless brand
    brand
  end

  def get_normalized_brand_name(options)
    brand_name = options[:brand].to_s
    UI.user_error!("You must specify a brand name") unless brand_name
    brand_name.downcase.delete(" ")
  end

  def get_targets_configuration(options)
    brand = get_brand(options)
    environment = options[:environment]
    UI.user_error!("You must specify an environment") unless environment
    available_environments = brand[:targets_configuration].keys.map { | e | e.to_s }
    configuration = brand[:targets_configuration][environment.to_sym]
    UI.user_error!("Invalid environment '#{environment.to_s}'. Available environments: #{available_environments}") unless configuration
    configuration
  end

  def get_target_names(options)
    targets_configuration = get_targets_configuration(options)
    target_names = targets_configuration[:targets].map { |target| target[:name] }
    target_names
  end

  def get_main_target_name(options)
    target_names = get_target_names(options)
    target_names.first
  end

  def update_projects_team(options)
    brand = get_brand(options)
    # Main Project
    targets_configuration = get_targets_configuration(options)
    targets_info = targets_configuration[:targets]
    targets = targets_info.map { | t | t[:name] }
    update_project_team(
      teamid: brand[:developer_portal_team_id],
      targets: targets,
    )
    # Dependencies
    $projects.each { | project |
      update_project_team(
        path: project[:path],
        teamid: brand[:developer_portal_team_id],
      )
    }
  end

  def run_code_signing_sync(brand, bundle_ids, distribution_type, force = false)
    sync_code_signing(
      app_identifier: bundle_ids,
      git_url: brand[:match_url],
      team_id: brand[:developer_portal_team_id],
      type: distribution_type.to_s,
      force: force
    )
  end

  def send_slack_message(options)
    unless is_ci?
      puts "Skipping Slack step as not running on CI."
      return
    else
      puts "Notifying result to Slack"
    end

    brand = get_brand(options)
    success = options[:success]
    success = true if success.nil?
    slack(
      success: success,
      channel: brand[:slack_channel],
      payload: options[:payload] || {},
      message: options[:message] || "Build succeeded. A build will be available shortly.",
      use_webhook_configured_username_and_icon: false
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.177.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.2.5   | ✅ Up-To-Date  |
| fastlane-plugin-versioning                | 0.4.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.4.0        |
| executable-hooks                          | 1.6.0        |
| bundler-unload                            | 1.0.2        |
| rubygems-bundler                          | 1.4.5        |
| bundler                                   | 2.1.4        |
| rake                                      | 13.0.3       |
| CFPropertyList                            | 3.0.3        |
| ZenTest                                   | 4.12.0       |
| RubyInline                                | 3.12.5       |
| concurrent-ruby                           | 1.1.8        |
| i18n                                      | 1.8.9        |
| minitest                                  | 5.14.4       |
| thread_safe                               | 0.3.6        |
| tzinfo                                    | 1.2.9        |
| activesupport                             | 5.2.4.5      |
| public_suffix                             | 4.0.6        |
| addressable                               | 2.7.0        |
| httpclient                                | 2.8.3        |
| json                                      | 2.5.1        |
| algoliasearch                             | 1.27.5       |
| artifactory                               | 3.0.15       |
| atomos                                    | 0.1.3        |
| aws-eventstream                           | 1.1.1        |
| aws-partitions                            | 1.431.1      |
| aws-sigv4                                 | 1.2.3        |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.112.1      |
| aws-sdk-kms                               | 1.42.0       |
| aws-sdk-s3                                | 1.90.0       |
| babosa                                    | 1.0.4        |
| claide                                    | 1.0.3        |
| fuzzy_match                               | 2.0.4        |
| nap                                       | 1.1.0        |
| netrc                                     | 0.11.0       |
| ffi                                       | 1.15.0       |
| ethon                                     | 0.12.0       |
| typhoeus                                  | 1.4.0        |
| cocoapods-core                            | 1.10.1       |
| cocoapods-deintegrate                     | 1.0.4        |
| cocoapods-downloader                      | 1.4.0        |
| cocoapods-plugins                         | 1.0.0        |
| cocoapods-search                          | 1.0.0        |
| cocoapods-trunk                           | 1.5.0        |
| cocoapods-try                             | 1.2.0        |
| colored2                                  | 3.1.2        |
| escape                                    | 0.0.4        |
| fourflusher                               | 2.3.1        |
| gh_inspector                              | 1.1.3        |
| molinillo                                 | 0.6.6        |
| ruby-macho                                | 1.4.0        |
| nanaimo                                   | 0.3.0        |
| xcodeproj                                 | 1.19.0       |
| cocoapods                                 | 1.10.1       |
| dotenv                                    | 2.7.6        |
| osx_keychain                              | 1.0.2        |
| cocoapods-keys                            | 2.2.1        |
| colored                                   | 1.2          |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| declarative                               | 0.0.20       |
| declarative-option                        | 0.1.0        |
| digest-crc                                | 0.6.3        |
| unf_ext                                   | 0.0.7.7      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| emoji_regex                               | 3.2.2        |
| excon                                     | 0.79.0       |
| faraday-net_http                          | 1.0.1        |
| multipart-post                            | 2.0.0        |
| ruby2_keywords                            | 0.0.4        |
| faraday                                   | 1.3.0        |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.0.0        |
| fastimage                                 | 2.2.3        |
| jwt                                       | 2.2.2        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.1        |
| signet                                    | 0.15.0       |
| googleauth                                | 0.16.0       |
| mini_mime                                 | 1.0.2        |
| uber                                      | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| google-api-client                         | 0.38.0       |
| rexml                                     | 3.2.4        |
| webrick                                   | 1.7.0        |
| google-apis-core                          | 0.3.0        |
| google-apis-iamcredentials_v1             | 0.2.0        |
| google-apis-storage_v1                    | 0.3.0        |
| google-cloud-env                          | 1.5.0        |
| google-cloud-errors                       | 1.0.1        |
| google-cloud-core                         | 1.5.0        |
| google-cloud-storage                      | 1.30.0       |
| mini_magick                               | 4.11.0       |
| naturally                                 | 2.2.1        |
| plist                                     | 3.6.0        |
| rubyzip                                   | 2.3.0        |
| security                                  | 0.1.3        |
| simctl                                    | 1.6.8        |
| slack-notifier                            | 2.3.2        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.7.0        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| word_wrap                                 | 1.0.0        |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.1        |
| fastlane-plugin-firebase_app_distribution | 0.2.5        |
| fastlane-plugin-versioning                | 0.4.4        |
</details>

*generated on:* **2021-03-09**
</details>

**Comment by max-ott** [comment]
We have no influence on how long sessions are working. It seems sessions are depending on geographical areas, meaning if CI machines "change" and are in different locations, it's possible the old session is not valid for the new one. Try to use the App Store Connect API key where possible to solve this issue.
