### ISSUE TITLE
The completions don't know about platforms/arguments and don't offer option names

### ISSUE THREAD

**Issue by Cyberbeni** [fastlane/fastlane#18376]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I've just installed the zsh autocompletion (I think the readme should mention how to install them) and noticed that it will just offer any lane name found in the Fastfile regardless of default_platform/previous arguments.

Once the lane is selected in a previous argument then it would be nice to get the options from that lane. (Pattern matching for options[:option_name] inside the lane block is fairly simple and would be perfect for almost everyone)

**Comment by max-ott** [comment]
Feel free to open a pull request to add support for this.
