### ISSUE TITLE
Fastlane not running

### ISSUE THREAD

**Issue by OscarGorog** [fastlane/fastlane#18375]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Running anything to do with Fastlane throws this message:
```
/usr/local/bin/fastlane: /usr/local/Cellar/fastlane/2.177.0/libexec/bin/fastlane: /usr/local/opt/ruby@2.7/bin/ruby: bad interpreter: No such file or directory
/usr/local/bin/fastlane: line 4: /usr/local/Cellar/fastlane/2.177.0/libexec/bin/fastlane: Undefined error: 0
```

##### Command executed
Anything but for example: `fastlane env`

##### Complete output when running fastlane, including the stack trace and command used
```
/usr/local/bin/fastlane: /usr/local/Cellar/fastlane/2.177.0/libexec/bin/fastlane: /usr/local/opt/ruby@2.7/bin/ruby: bad interpreter: No such file or directory
/usr/local/bin/fastlane: line 4: /usr/local/Cellar/fastlane/2.177.0/libexec/bin/fastlane: Undefined error: 0
```

### Environment
Can't run the command

**Comment by minuscorp** [comment]
It seems that you don't have a Ruby interpreter correctly installed/linked, check for `brew link` command for your Ruby installation.

**Comment by OscarGorog** [comment]
Got it to works, thanks!
