### ISSUE TITLE
Broken link to Google Play Console in docs

### ISSUE THREAD

**Issue by lkesteloot** [fastlane/fastlane#18384]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

The link to the Google Play Console is broken in the docs.

Visit [this page](https://docs.fastlane.tools/actions/supply/), click the link to "Google Play Console" under "Setup". It refreshes the page because the `title` attribute was set instead of the `href` attribute.

![image](https://user-images.githubusercontent.com/419771/110878580-50f3f980-8290-11eb-925d-c224173da2ee.png)

**Comment by max-ott** [comment]
Please open a pull request by clicking on "edit on Github" at the top right corner.
