### ISSUE TITLE
[supply] How to promote a release from internal testing to closed testing

### ISSUE THREAD

**Issue by nicolasguenther** [fastlane/fastlane#18386]
We use supply with parameters `track: "internal` and `track_promote_to: "alpha"` to make a release available to internal testing and closed testing at the same time. However, the parameter `track_promote_to` seems to be ignored by fastlane supply and a manual step is necessary in the play console to make the release available for closed testing.

**Comment by andreialecu** [comment]
Having the same problem. 

`track_promote_to: 'beta'` seems to be ignored.

I wonder if it's because of missing changelogs?

**Comment by nicolasguenther** [comment]
I found out that you have to call supply twice. First to upload your app to a track and then again to promote it to another track.

**Comment by andreialecu** [comment]
That seems like a bug, or documentation problem. Is it mentioned anywhere?

Could you provide a small example of how you call it? (particularly, when you call it again, do you skip the upload?)

Perhaps this should be kept open so that it can be addressed by the maintainers.

**Comment by nicolasguenther** [comment]
Example:

```
upload_to_play_store(
  track: "internal",
  json_key_data: "key-data",
  package_name: "package-name",
  aab: "path"
)

upload_to_play_store(
  track: "internal",
  track_promote_to: "alpha",
  json_key_data: "key-data",
  package_name: "package-name,
  skip_upload_apk: true,
  skip_upload_aab: true,
  skip_upload_metadata: true,
  skip_upload_changelogs: true,
  skip_upload_images: true,
  skip_upload_screenshots: true
)
```

**Comment by andreialecu** [comment]
Thanks @nicolasguenther, that seems to work.

/cc perhaps @joshdholtz could shed some light on this.
