### ISSUE TITLE
Access type needed for API key is undocumented

### ISSUE THREAD

**Issue by christhegrand** [fastlane/fastlane#18383]
### New Issue Checklist

- [ x ] Updated fastlane to the latest version
- [ x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Hi there,
We're updating our Fastlane code to use an Apple API key for authentication when submitting a build to App Store Connect, and were wondering what type of access the API key needs to have. I don't see anything about this in the [documentation for the App Store API](https://docs.fastlane.tools/app-store-connect-api/). In the documentation for [Pilot](https://docs.fastlane.tools/actions/pilot/), I see this: 

"pilot/upload_to_testflight updates build information and testers after the build has finished processing. App Store Connect requires the "App Manager" or "Admin" role for your Apple account to update this information. The "Developer" role will allow builds to be uploaded but will not allow updating of build information and testers."

Are the access levels needed for the API key the same? Developer for uploads, and App Manager or Admin for the build updates?

##### Command executed

N/A

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> N/A</pre>
</details>

### Environment

<details>
  <pre> N/A </pre>
</details>

**Comment by max-ott** [comment]
Please check out https://help.apple.com/app-store-connect/#/deve5f9a89d7 for an overview of the roles and their permissions. This is a limitation by Apple.

**Comment by rogerluan** [comment]
I was gonna add this link ☝️ to our docs, but our docs [here](https://docs.fastlane.tools/app-store-connect-api/) has this:

<img width="629" alt="image" src="https://user-images.githubusercontent.com/8419048/111005912-82d98e80-836a-11eb-8503-f5ee360fc697.png">

Which links to this: https://developer.apple.com/documentation/appstoreconnectapi/creating_api_keys_for_app_store_connect_api

Which inform users about the roles:

<img width="785" alt="image" src="https://user-images.githubusercontent.com/8419048/111005929-92f16e00-836a-11eb-811c-406ec4980657.png">

(the link being https://help.apple.com/app-store-connect/#/deve5f9a89d7)

I think our docs are as good on this one, but thanks for bringing this up @christhegrand
