### ISSUE TITLE
Frameit frames still seem to have the wrong size

### ISSUE THREAD

**Issue by dhermanns** [fastlane/fastlane#18394]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Looks like the snapshot are still not respecting the new Apple Image Sizes here:
https://help.apple.com/app-store-connect/#/devd274dd925

E.g. the iPhone 8 Plus here still has the wrong size. Looks like this is an issue in the Frames
https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%208%20Plus%20Silver.png

So if I don't use frameit, it looks like #18276 fixed it. But as soon as the frames are added, there seem
to be still the image size problem.

The error message is:

[15:58:14]: 🚫 Error: ./fastlane/screenshots/en-US/iPhone 8 Plus-06-stats_framed.png - Invalid screen size (Actual size is 2876x1436. See the specifications to fix https://help.apple.com/app-store-connect/#/devd274dd925)

##### Command executed
```
bundle exec fastlane iOS screenshots
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.2.3                                                         |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.2.3 (20D91)                                           |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.4                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(
        workspace: "nightguard.xcworkspace",
        scheme: "nightguard")
    frame_screenshots
  end

  desc "Release the nightguard app"
  lane :release do
    increment_build_number
    build_app(scheme: "nightguard")
    upload_to_app_store(
        force: true,
        overwrite_screenshots: false,
        skip_screenshots: false)
  end
end

```
</details>

<details><summary>`./Appfile`</summary>

```ruby
app_identifier("de.my-wan.dhe.nightguard") # The bundle identifier of your app
apple_id("h3rmanns@gmail.com") # Your Apple email address

# You can uncomment the lines below and add your own
# team selection in case you're in multiple teams
team_name "etrada GmbH"
team_id "118795774"

itc_team_name "etrada GmbH"
itc_team_id "118795774"

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.178.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.3.0        |
| slack-notifier                | 2.3.2        |
| atomos                        | 0.1.3        |
| claide                        | 1.0.3        |
| colored2                      | 3.1.2        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| plist                         | 3.6.0        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| multipart-post                | 2.0.0        |
| word_wrap                     | 1.0.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| artifactory                   | 3.0.15       |
| babosa                        | 1.0.4        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| faraday-net_http              | 1.0.1        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| gh_inspector                  | 1.1.3        |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| xcpretty-travis-formatter     | 1.0.1        |
| dotenv                        | 2.7.6        |
| bundler                       | 1.17.2       |
| simctl                        | 1.6.8        |
| jwt                           | 2.2.2        |
| uber                          | 0.1.0        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| mini_mime                     | 1.0.2        |
| httpclient                    | 2.8.3        |
| google-api-client             | 0.38.0       |
| CFPropertyList                | 3.0.3        |
| excon                         | 0.79.0       |
| fastimage                     | 2.2.3        |
| json                          | 2.5.1        |
| multi_json                    | 1.15.0       |
| signet                        | 0.15.0       |
| os                            | 1.1.1        |
| memoist                       | 0.16.2       |
| googleauth                    | 0.16.0       |
| rake                          | 13.0.3       |
| digest-crc                    | 0.6.3        |
| webrick                       | 1.7.0        |
| rexml                         | 3.2.4        |
| google-apis-core              | 0.3.0        |
| google-apis-storage_v1        | 0.3.0        |
| google-apis-iamcredentials_v1 | 0.2.0        |
| google-cloud-errors           | 1.1.0        |
| google-cloud-env              | 1.5.0        |
| google-cloud-core             | 1.6.0        |
| google-cloud-storage          | 1.31.0       |
| emoji_regex                   | 3.2.2        |
| aws-eventstream               | 1.1.1        |
| aws-sigv4                     | 1.2.3        |
| aws-partitions                | 1.432.0      |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.113.0      |
| aws-sdk-kms                   | 1.43.0       |
| aws-sdk-s3                    | 1.91.0       |
| forwardable                   | 1.2.0        |
| logger                        | 1.3.0        |
| date                          | 2.0.0        |
| stringio                      | 0.0.2        |
| zlib                          | 1.0.0        |
| ipaddr                        | 1.2.2        |
| openssl                       | 2.1.2        |
| ostruct                       | 0.1.0        |
| strscan                       | 1.0.0        |
| fileutils                     | 1.1.0        |
| etc                           | 1.0.1        |
| io-console                    | 0.4.7        |
| libxml-ruby                   | 3.1.0        |
| psych                         | 3.1.0        |
| mutex_m                       | 0.1.0        |
</details>

*generated on:* **2021-03-14**
</details>

**Comment by michaellenaghan** [comment]
#18276 was a fix for newer 5.8" devices. It did nothing for 5.5" devices, which is what an iPhone 8 Plus is.

When I manually take a screenshot in the iPhone 8 Plus simulator, I get the same dimensions Fastlane does: 1242x2208. I think we need to figure out why you're generating 1436x2876 screenshots for the same device? (In fact, those dimensions don't appear anywhere in Fastlane. It looks like something about your configuration is unusual. What dimensions do you get from a manually generated screenshot?)

**Comment by michaellenaghan** [comment]
[Here](https://github.com/fastlane/fastlane/issues/18394) is a handy list of resolutions. No device is 1436x2876.

**Comment by dhermanns** [comment]
If I got it right, fastlane tries to download frame images from this location. E.g.:
https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%208%20Plus%20Silver.png

If I download this manually - it has the wrong size 1436x2876.

**Comment by michaellenaghan** [comment]
That's the frame that goes *around* the screenshot. The `frameit` action preserves the dimensions of the original screenshot itself, and resizes things to fit — including the frame. If you want to get a sense of what `frameit` is doing, take a look [here](https://github.com/fastlane/fastlane/blob/master/frameit/lib/frameit/editor.rb).

The config you've given above isn't enough for me to see what you're doing differently; there's no `Snapfile` or `Framefile.json`. In case it helps, here's my own `Framefile.json`, with unimportant details elided:

```json
{
  "default": {
    "background": "./background-white.png",
    "frame": "SPACE_GRAY",
    "keyword": {
      "color": "#000",
      "font": "..."
    },
    "padding": 50,
    "show_complete_frame": true,
    "stack_title": true,
    "title": {
      "color": "#000",
      "font": "..."
    },
    "title_min_height": "34%"
  },
  "data": [
    {
      "filter": "iPad",
      "background": "./background-black.png",
      "keyword": {
        "color": "#fff"
      },
      "title": {
        "color": "#fff"
      },
      "title_min_height": "27.5%"
    },
    {
      "filter": "Overview",
      "keyword": {
        "text": "..."
      },
      "title": {
        "text": "..."
      }
    },
   ...
  ]
}
```

Also, to be clear: I'm just another Fastfile user. I went through the process of getting this to work a few months ago. I distinctly remember that there was a key point I misunderstood about `frameit`, but I don't remember exactly what it was. I also remember running into some bugs that I had to work around. For example, I reported in #18243 that the iPad 8th generation didn't work. I never found a fix for that; my workaround was to use a different 10.5" device.

In this case, you're using the same device I am for 5.5" screenshots. I know it *can* work, but I don't know why it isn't for you. 

You may want to consider supplying those additional config files, together with the output of your run.

**Comment by michaellenaghan** [comment]
I see [here](https://github.com/fastlane/fastlane/blob/57aae14b26aae9bf92aafeb55115e74a380a0f0c/frameit/lib/frameit/editor.rb#L41) that if `is_complex_framing_mode?` is `false` you go down a [completely different path](https://github.com/fastlane/fastlane/blob/57aae14b26aae9bf92aafeb55115e74a380a0f0c/frameit/lib/frameit/editor.rb#L84). `is_complex_framing_mode?` returns `true` if [a) you have a background and b) you have a title or a keyword](https://github.com/fastlane/fastlane/blob/57aae14b26aae9bf92aafeb55115e74a380a0f0c/frameit/lib/frameit/editor.rb#L152).

I think that might be it: you're going down [that different path](https://github.com/fastlane/fastlane/blob/57aae14b26aae9bf92aafeb55115e74a380a0f0c/frameit/lib/frameit/editor.rb#L84), and the different path just places the screenshot in the frame, without resizing. That might in fact be the exact same lesson I learned many months ago.

**Comment by dhermanns** [comment]
My Framefile was missing what seemed to cause the invalid screen size. Seems that I missed that the framing exited or hasn't been executed correctly. Your hint helped - thx.
