### ISSUE TITLE
dsym is not getting zipped

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1839]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/415987?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @arunks - Imported from <a href='https://github.com/fastlane/gym/issues/154'>fastlane/gym#154</a>
        </td>
      </tr>
    </table>

I am building my app right now with - 
include_symbols: "true",

At the end of the process I expect the dsym to be zipped for easy upload to distribution mechanisms. But I dont see the ZIP file. Has this feature been removed? Or do I have to write a postscript?

**Comment by FBente** [comment]
I ran into the same problem and found a reason after some try and error. In the 'Build Settings' for your target under 'Build Options' the 'Debug Information Format'  has to be 'DWARF with dSYM File' for your desired configuration. Otherwise no dSYM.zip file can be created by gym.

**Comment by TKBurner** [comment]
@FBente Awesome! Glad you found a solution 👍
