### ISSUE TITLE
[Fastlane.Swift] Runner.executeCommand(_:) returns empty String for commands with other result types

### ISSUE THREAD

**Issue by andrei-kuzma** [fastlane/fastlane#18393]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

There are a lot of actions, plugins that are not usable in Fastlane Swift as generated functions are Void. For example `gitTagExists(tag:remote:remoteName:)`. Even if we will try to write our own implementations using `RubyCommand` we will not be able to do that for actions that have not `String` return type as `Runner.executeCommand(_:)` uses `String` as return type.
The issue is that `return_object` from `payload` can have any type and during casting we get `nil` for such cases.

Let see how it looks in code:
We have next code that's cast execution result to `String` in `SocketResponse.ResponseType.init(statusDictionary:)`:
```swift
let returnedObject = statusDictionary["return_object"] as? String
```
It means that for types like `Bool` we will get `nil` and `Runner.executeCommand(_:)` will return empty `String` for this case.

The easiest way to have `String`  result type is to replace
```swift
let returnedObject = statusDictionary["return_object"] as? String
```
with
```swift
let returnedObject = statusDictionary["return_object"].map { "\($0)" }
``` 

But I don't think that it is expected behaviour.
I think we should have something like `Runner.executeCommand<V>(_:) -> V` instead, to be able to handle different types.

To achieve this  we can do next:
 - in `SocketResponse. ResponseType` change `returnedObject ` type to `Any`  and do not cast value from payload
```swift
struct SocketResponse {
    enum ResponseType {
        ...
        case readyForNext(returnedObject: Any?, closureArgumentValue: String?) //updated
        ...
        init(statusDictionary: [String: Any]) {
            ...
            if status == "ready_for_next" {
                ...
                let returnedObject = statusDictionary["return_object"] //updated
               ...
                return

            }
            ...
        }
    }
    ...
}
```
 - change `returnedObject ` type to `Any` in`SocketClientResponse` 
 ```swift
 public enum SocketClientResponse: Error {
    ...
    case success(returnedObject: Any?, closureArgumentValue: String?) // updated
}
 ```
  -  and finally update `Runner` to make `Runner.executeCommand(_:)` generic `
  ```swift
 protocol OptionalProtocol {}

extension Optional: OptionalProtocol {}

class Runner {
    ...
    private var returnValue: Any? //updated
    ...

    @discardableResult
    func executeCommand(_ command: RubyCommandable) -> String {
        execute(command).map { "\($0)"} ?? ""
    }

    func executeCommand<Value>(_ command: RubyCommandable) -> Value {
        guard let commandResult = execute(command) else {
            fatalError("Command id:\(command.id) returned 'nil'")
        }
        guard let value: Value = commandResult as? Value else {
            fatalError("Unable to cast \(commandResult) to \(Value.self)")
        }
        return value
    }

    func executeCommand<Value: OptionalProtocol>(_ command: RubyCommandable) -> Value? {
        execute(command).flatMap({ $0 as? Value })
    }

    private func execute(_ command: RubyCommandable) -> Any? {
        dispatchGroup.enter()
        currentlyExecutingCommand = command
        socketClient.send(rubyCommand: command)

        let secondsToWait = DispatchTimeInterval.seconds(SocketClient.defaultCommandTimeoutSeconds)
        // swiftformat:disable:next redundantSelf
        let timeoutResult = Self.waitWithPolling(self.executeNext[command.id], toEventually: { $0 == true }, timeout: SocketClient.defaultCommandTimeoutSeconds)
        executeNext.removeValue(forKey: command.id)
        let failureMessage = "command didn't execute in: \(SocketClient.defaultCommandTimeoutSeconds) seconds"
        let success = testDispatchTimeoutResult(timeoutResult, failureMessage: failureMessage, timeToWait: secondsToWait)
        guard success else {
            log(message: "command timeout")
            preconditionFailure()
        }
        return returnValue
    }
 ...
}
 ```

Then functions like existing `gitTagExists(tag:remote:remoteName:)` can be rewritten next way:
```swift
    func gitTagExists(
        tag: String,
        remote: Bool = false,
        remoteName: String = "origin"
    ) -> Bool {
        let command = RubyCommand(
            commandID: "",
            methodName: "git_tag_exists",
            className: nil,
            args: [
                RubyCommand.Argument(name: "tag", value: tag),
                RubyCommand.Argument(name: "remote", value: remote),
                RubyCommand.Argument(name: "remote_name", value: remoteName)
            ]
        )
        return runner.executeCommand(command)
    }
```

Not sure how code for plugins is generated and how return type is determined, but I believe the next step will be to update those scripts and generate proper return types there to make Fastlane Swift fans happy :).

**Comment by minuscorp** [comment]
This is very interesting indeed, many commands have a closure when a result is intended to be returned, like `sh` for example. This is how we communicate asynchronously results to the caller which allows to cascade calls or chain them. I think we can always return the value received from the socket before the `ready_for_next` message, but probably it will be generated as a `Any` object for generic interface of actions into Swift code.

**Comment by minuscorp** [comment]
I digged into the issue a little bit more and there's actually a way to parse the return value of several actions, just let you know that not all of them define the `return_type`.
```ruby
def self.return_type
        :bool
end
```
Is what we want for the example you raised.

**Comment by andrei-kuzma** [comment]
@minuscorp, thank you for fixes!

Could you help me to understand what should I do to see new generated swift files?
I've changed my `GemFile` to use version from master
`gem 'fastlane', git: 'https://github.com/fastlane/fastlane.git', branch: 'master'`
And see all your changes in ruby files on file system, but there is no changes in swift files. Should they also be regenerated and committed to master?
Also it not clear for me how your fix will change the fact that:
 -  `Runner` returns `String` value
 - all values are casted to `String` in `SocketResponse.ResponseType.init(statusDictionary:)`
`let returnedObject = statusDictionary["return_object"] as? String`

Thank you in advance!

**Comment by minuscorp** [comment]
They are generated on release, not on master so if you want to see the results you have to run the following lane from the fastlane installation directory:
`fastlane generate_swift_api`

**Comment by andrei-kuzma** [comment]
@minuscorp, thank you for your response!
I was able to generate files and it works ok for for actions that defined return types.
But I faced with issue for `fastlane-plugin-appcenter` which not define return type for `appcenter_fetch_version_number`
and socket sends object instead of `String`, so I can't create `RubyCommand` and return expected result.

If socket sends object instead of `String` because return type is not defined then it's not flexible as you have to wait for fix in each plugin. But probably the root cause is in other place and we will not get 'String' even if return type will be defined.

**Comment by minuscorp** [comment]
For actions which are outside of the fastlane's main repo like that one you have to open a PR or an issue in the corresponding repository and get it fixed. Sorry for the inconvenience.

**Comment by andrei-kuzma** [comment]
@minuscorp, np, you help me a lot.
**Just a note:** I checked behaviour for case when result type for `appcenter_fetch_version_number` is defined like `:hash`and everything works as expected. So nothing to do here.

Thank you again!
