### ISSUE TITLE
[Deliver] reject_if_possible doesn't work when using submit_build. The app store version is in Waiting For Review.

### ISSUE THREAD

**Issue by TragedyStar** [fastlane/fastlane#18416]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

The app store version was in Waiting For Review state, it could be rejected manually.

I debuged the code and found the problem might be related too this issue: **can_reject property of app_store_version_submission was nil, so `app_store_version_submission.delete!` did been called.**

I found no canReject field in the response of [List All App Store Version App Store Connect API](https://developer.apple.com/documentation/appstoreconnectapi/list_all_app_store_versions_for_an_app). I'm not sure whether this is  related to this issue.

##### Command executed

`fastlane deliver submit_build --api_key_path "$API_KEY_INFO_FILEPATH" --app_identifier 'com.xxxx.xxxx' --platform 'ios' --app_version $version --build_number $app_version --skip_binary_upload true --skip_screenshots true --automatic_release false --phased_release true --reset_ratings false --submission_information "$DELIVER_SUBMISSION_INFO" --app_review_information "$DELIVER_APP_REVIEW_INFO" --reject_if_possible true --force true --run_precheck_before_submit false`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [00:32:04]: Making sure the latest version on App Store Connect matches '10.80.0'...
[00:32:05]: [32m'10.80.0' is the latest version on App Store Connect[0m
[00:32:26]: [33mWill begin uploading metadata for '10.80.0' on App Store Connect[0m
[00:32:26]: Uploading metadata to App Store Connect for version
[00:32:41]: Uploading app review information to App Store Connect
[00:32:47]: Selecting existing build-number: 10.80.0.2812
[00:32:52]: Selecting build 10.80.0 (10.80.0.2812)...

Looking for related GitHub issues on fastlane/fastlane...

➡️  [33m[deliver][produce][spaceship] Update to use new App Store Connect API endpoints[0m
    https://github.com/fastlane/fastlane/pull/16626 [[32mclosed[0m] 140 💬
    27 Jul 2020

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.178.0/spaceship/lib/spaceship/connect_api/api_client.rb:199:in `handle_response': [31m[!] A relationship value is not acceptable for the current resource state. - The specified pre-release build could not be added. - /data/relationships/build[0m (Spaceship::UnexpectedResponse)
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.178.0/spaceship/lib/spaceship/connect_api/api_client.rb:135:in `patch'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.178.0/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:922:in `patch_app_store_version_with_build'
from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `patch_app_store_version_with_build'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.178.0/spaceship/lib/spaceship/connect_api/models/app_store_version.rb:205:in `select_build'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.178.0/deliver/lib/deliver/submit_for_review.rb:51:in `select_build'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.178.0/deliver/lib/deliver/submit_for_review.rb:20:in `submit!'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.178.0/deliver/lib/deliver/runner.rb:198:in `submit_for_review'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.178.0/deliver/lib/deliver/runner.rb:64:in `run'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.178.0/deliver/lib/deliver/commands_generator.rb:96:in `block (2 levels) in run'
from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.178.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.178.0/deliver/lib/deliver/commands_generator.rb:186:in `run'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.178.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.178.0/bin/fastlane:23:in `<top (required)>'
from /usr/local/bin/fastlane:23:in `load'
from /usr/local/bin/fastlane:23:in `<main>'
 </pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.2.3                                                         |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.2.3 (20D91)                                           |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.4                                                           |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.178.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| artifactory               | 3.0.15       |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 1.0.1        |
| faraday_middleware        | 1.0.0        |
| gh_inspector              | 1.1.3        |
| naturally                 | 2.2.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| uber                      | 0.1.0        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| nanaimo                   | 0.3.0        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.19.0       |
| unicode-display_width     | 1.7.0        |
| public_suffix             | 4.0.6        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| excon                     | 0.76.0       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| fastimage                 | 2.2.0        |
| json                      | 2.3.1        |
| mini_magick               | 4.10.1       |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.4        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| declarative               | 0.0.20       |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| os                        | 1.1.1        |
| memoist                   | 0.16.2       |
| googleauth                | 0.13.1       |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-env          | 1.3.3        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.0       |
| emoji_regex               | 3.0.0        |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-partitions            | 1.374.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.107.0      |
| aws-sdk-kms               | 1.38.0       |
| aws-sdk-s3                | 1.81.0       |
| forwardable               | 1.3.1        |
| logger                    | 1.4.2        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 3.0.1        |
| fileutils                 | 1.4.1        |
| io-console                | 0.5.6        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.2.0        |
| rexml                     | 3.2.4        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| ox                        | 2.13.4       |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2021-03-18**
</details>

**Comment by max-ott** [comment]
I'm not seeing any documentation from Apple that this is a supported action with the ASC API. If you use regular Apple ID auth, do you get the same behaviour?
