### ISSUE TITLE
FastlaneCore::Interface::FastlaneError: [!] Google Api Error: Server error - Internal error encountered.

### ISSUE THREAD

**Issue by alexolivier** [fastlane/fastlane#18415]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Since this morning uploading to Google Play as resulted in a Google API error:

```
Google Api Error: Server error - Internal error encountered.
```

##### Command executed
```
    upload_to_play_store(
      aab: "build/app/outputs/bundle/release/app-release.aab",
      track: "production"
    )
```

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>
INFO [2021-03-17 16:06:11.12]: ----------------------------------
INFO [2021-03-17 16:06:11.12]: --- Step: upload_to_play_store ---
INFO [2021-03-17 16:06:11.12]: ----------------------------------

+---------------------------------+--------------------------------------------------+
|                             Summary for supply 2.178.0                             |
+---------------------------------+--------------------------------------------------+
| aab                             | build/app/outputs/bundle/release/app-release.aab |
| track                           | internal                                         |
| package_name                    | co.anothertrip.app.boarding_pass                 |
| release_status                  | completed                                        |
| metadata_path                   | ./fastlane/metadata/android                      |
| json_key                        | android/google-play-key.json                     |
| skip_upload_apk                 | false                                            |
| skip_upload_aab                 | false                                            |
| skip_upload_metadata            | false                                            |
| skip_upload_changelogs          | false                                            |
| skip_upload_images              | false                                            |
| skip_upload_screenshots         | false                                            |
| validate_only                   | false                                            |
| check_superseded_tracks         | false                                            |
| timeout                         | 300                                              |
| deactivate_on_promote           | true                                             |
| ack_bundle_installation_warning | false                                            |
+---------------------------------+--------------------------------------------------+

DEBUG [2021-03-17 16:06:11.17]: Fetching a new access token from Google...
INFO [2021-03-17 16:06:12.39]: Preparing aab at path 'build/app/outputs/bundle/release/app-release.aab' for upload...
INFO [2021-03-17 16:06:52.42]: Updating track 'internal'...
INFO [2021-03-17 16:06:53.60]: Preparing to upload for language 'en-GB'...
INFO [2021-03-17 16:06:54.34]: Uploading image file ./fastlane/metadata/android/en-GB/images/featureGraphic.png...
INFO [2021-03-17 16:06:56.70]: Uploading image file ./fastlane/metadata/android/en-GB/images/icon.png...
INFO [2021-03-17 16:06:59.20]: Uploading screenshot ./fastlane/metadata/android/en-GB/images/phoneScreenshots/1_en-GB.png...
INFO [2021-03-17 16:07:02.69]: Uploading screenshot ./fastlane/metadata/android/en-GB/images/phoneScreenshots/2_en-GB.png...
INFO [2021-03-17 16:07:05.84]: Could not find changelog for '397' and language 'en-GB' at path ./fastlane/metadata/android/en-GB/changelogs/397.txt...
INFO [2021-03-17 16:07:06.25]: Uploading all changes to Google Play...
WARN [2021-03-17 16:07:49.32]: Lane Context:
INFO [2021-03-17 16:07:49.32]: {:DEFAULT_PLATFORM=>:android, :PLATFORM_NAME=>:android, :LANE_NAME=>"android alpha"}
ERROR [2021-03-17 16:07:49.32]: Google Api Error: Server error - Internal error encountered.
INFO [2021-03-17 16:07:49.33]: Successfully generated documentation at path '/Users/alexolivier/projects/anothertrip/repos/boarding_pass/fastlane/README.md'

+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | default_platform                                              | 0           |
| 2    | number_of_commits                                             | 0           |
| 3    | flutter packages get                                          | 5           |
| 4    | flutter clean                                                 | 12          |
| 5    | flutter build appbundle --dart-define\=AT_ENV\=production --b | 140         |
| 💥   | upload_to_play_store                                          | 98          |
+------+---------------------------------------------------------------+-------------+

ERROR [2021-03-17 16:07:49.36]: fastlane finished with errors
bundler: failed to load command: fastlane (/Users/alexolivier/.rbenv/versions/2.6.3/bin/fastlane)
FastlaneCore::Interface::FastlaneError: [!] Google Api Error: Server error - Internal error encountered.
  /Users/alexolivier/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.178.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'
  /Users/alexolivier/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.178.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /Users/alexolivier/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.178.0/supply/lib/supply/client.rb:95:in `rescue in call_google_api'
  /Users/alexolivier/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.178.0/supply/lib/supply/client.rb:80:in `call_google_api'
  /Users/alexolivier/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.178.0/supply/lib/supply/client.rb:165:in `commit_current_edit!'
  /Users/alexolivier/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.178.0/supply/lib/supply/uploader.rb:40:in `perform_upload'
  /Users/alexolivier/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/actions/upload_to_play_store.rb:33:in `run'
  /Users/alexolivier/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  /Users/alexolivier/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
  /Users/alexolivier/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  /Users/alexolivier/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  /Users/alexolivier/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  /Users/alexolivier/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/alexolivier/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:35:in `block (2 levels) in parsing_binding'
  /Users/alexolivier/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/alexolivier/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/alexolivier/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/alexolivier/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/alexolivier/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /Users/alexolivier/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/alexolivier/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/alexolivier/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/alexolivier/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/alexolivier/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/alexolivier/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.178.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/alexolivier/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/alexolivier/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  /Users/alexolivier/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/alexolivier/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.178.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
  /Users/alexolivier/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.178.0/bin/fastlane:23:in `<top (required)>'
  /Users/alexolivier/.rbenv/versions/2.6.3/bin/fastlane:23:in `load'
  /Users/alexolivier/.rbenv/versions/2.6.3/bin/fastlane:23:in `<top (required)>'
</pre>
</details>

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.7                                     |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.30.2                          |
| Installation Source         | ~/.rbenv/versions/2.6.3/bin/fastlane        |
| Host                        | Mac OS X 10.15.7 (19H524)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.3/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.4                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :internal do
    build_number = number_of_commits()
    sh("flutter", "packages", "get")
    sh("flutter", "clean")
    sh("flutter", "build", "appbundle", "--dart-define=AT_ENV=production", "--build-number=#{build_number}")
    upload_to_play_store(
      aab: "build/app/outputs/bundle/release/app-release.aab",
      track: "internal"
    )
  end
  
  lane :alpha do
    build_number = number_of_commits()
    sh("flutter", "packages", "get")
    sh("flutter", "clean")
    sh("flutter", "build", "appbundle", "--dart-define=AT_ENV=production", "--build-number=#{build_number}")
    upload_to_play_store(
      aab: "build/app/outputs/bundle/release/app-release.aab",
      track: "internal"
    )
  end

  lane :beta do
    build_number = number_of_commits()
    sh("flutter", "packages", "get")
    sh("flutter", "clean")
    sh("flutter", "build", "appbundle", "--dart-define=AT_ENV=production", "--build-number=#{build_number}")
    upload_to_play_store(
      aab: "build/app/outputs/bundle/release/app-release.aab",
      track: "beta"
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    build_number = number_of_commits()
    sh("flutter", "packages", "get")
    sh("flutter", "clean")
    sh("flutter", "build", "appbundle", "--dart-define=AT_ENV=production", "--build-number=#{build_number}")
    upload_to_play_store(
      aab: "build/app/outputs/bundle/release/app-release.aab",
      track: "production"
    )
  end
end


platform :ios do
  lane :alpha do
    build_number = number_of_commits()
    sync_code_signing
    sh("flutter", "packages", "get")
    sh("flutter", "clean")
    sh("flutter", "build", "ios", "--release", "--no-codesign", "--dart-define=AT_ENV=production", "--build-number=#{build_number}")
    build_ios_app(
      workspace: "ios/Runner.xcworkspace",
      export_method: "app-store",
      output_directory: "build/",
    )
    upload_to_testflight(ipa:"build/Runner.ipa", username:"ios-dev@anothertrip.co", skip_waiting_for_build_processing: true)
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("android/google-play-key.json") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("co.anothertrip.app.boarding_pass") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.178.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.3.0        |
| bundler                       | 1.17.2       |
| etc                           | 1.0.1        |
| forwardable                   | 1.2.0        |
| rake                          | 13.0.3       |
| CFPropertyList                | 3.0.3        |
| concurrent-ruby               | 1.1.6        |
| i18n                          | 0.9.5        |
| minitest                      | 5.14.1       |
| thread_safe                   | 0.3.6        |
| tzinfo                        | 1.2.7        |
| activesupport                 | 5.2.4.4      |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| httpclient                    | 2.8.3        |
| json                          | 2.5.1        |
| algoliasearch                 | 1.27.3       |
| artifactory                   | 3.0.15       |
| atomos                        | 0.1.3        |
| aws-eventstream               | 1.1.1        |
| aws-partitions                | 1.433.0      |
| aws-sigv4                     | 1.2.3        |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.113.0      |
| aws-sdk-kms                   | 1.43.0       |
| aws-sdk-s3                    | 1.91.0       |
| babosa                        | 1.0.4        |
| claide                        | 1.0.3        |
| fuzzy_match                   | 2.0.4        |
| nap                           | 1.1.0        |
| netrc                         | 0.11.0       |
| ffi                           | 1.13.0       |
| ethon                         | 0.12.0       |
| typhoeus                      | 1.4.0        |
| cocoapods-core                | 1.10.0.rc.1  |
| cocoapods-deintegrate         | 1.0.4        |
| cocoapods-downloader          | 1.4.0        |
| cocoapods-plugins             | 1.0.0        |
| cocoapods-search              | 1.0.0        |
| cocoapods-trunk               | 1.5.0        |
| cocoapods-try                 | 1.2.0        |
| colored2                      | 3.1.2        |
| escape                        | 0.0.4        |
| fourflusher                   | 2.3.1        |
| gh_inspector                  | 1.1.3        |
| molinillo                     | 0.6.6        |
| ruby-macho                    | 1.4.0        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| cocoapods                     | 1.10.0.rc.1  |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| digest-crc                    | 0.6.3        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| dotenv                        | 2.7.6        |
| emoji_regex                   | 3.2.2        |
| excon                         | 0.79.0       |
| faraday-net_http              | 1.0.1        |
| multipart-post                | 2.0.0        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.3        |
| jwt                           | 2.2.2        |
| memoist                       | 0.16.2       |
| multi_json                    | 1.15.0       |
| os                            | 1.1.1        |
| signet                        | 0.15.0       |
| googleauth                    | 0.16.0       |
| mini_mime                     | 1.0.2        |
| uber                          | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| google-api-client             | 0.38.0       |
| rexml                         | 3.2.4        |
| webrick                       | 1.7.0        |
| google-apis-core              | 0.3.0        |
| google-apis-iamcredentials_v1 | 0.2.0        |
| google-apis-storage_v1        | 0.3.0        |
| google-cloud-env              | 1.5.0        |
| google-cloud-errors           | 1.1.0        |
| google-cloud-core             | 1.6.0        |
| google-cloud-storage          | 1.31.0       |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| plist                         | 3.6.0        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| simctl                        | 1.6.8        |
| slack-notifier                | 2.3.2        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| word_wrap                     | 1.0.0        |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| xcpretty-travis-formatter     | 1.0.1        |
</details>

*generated on:* **2021-03-17**
</details>

**Comment by itcherry** [comment]
Experiencing the same issue

**Comment by KalevychOleksandr** [comment]
Same for my project

**Comment by alexolivier** [comment]
This has just started working for me again. Looks to be at Google's end.
