### ISSUE TITLE
Failed to register new device (undefined method `first' for "errors":String)

### ISSUE THREAD

**Issue by MoOx** [fastlane/fastlane#18424]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Failed to register new devices (before updating some pp)

`devices.txt`

```
Device ID	Device Name
00008020-001B04E12606XXXX	Long label with dot
00008101-000A41E2040XXXX	Long label with spaces and dots
3a6ed4ae8465d1c71638a5934e7e8af2579cxxxx	Long label with space and dot
```

##### Command executed

```
    register_devices(
      username: apple_id,
      team_id: ENV["ios_developerPortalTeamId"],
      devices_file: "./fastlane/devices.txt",
    )
```

##### Complete output when running fastlane, including the stack trace and command used

```
[15:55:20]: Fetching list of currently registered devices...
[15:55:21]: undefined method `first' for "errors":String
+---------------+-----------------------------+
|                Lane Context                 |
+---------------+-----------------------------+
| PLATFORM_NAME | ios                         |
| LANE_NAME     | ios sync_code_signing_write |
+---------------+-----------------------------+
[15:55:21]: Failed to register new device (name: *redacted*, UDID: 3a6ed4ae8465d1c71638a5934e7e8af2579cxxxx)

+------+-----------------------+-------------+
|              fastlane summary              |
+------+-----------------------+-------------+
| Step | Action                | Time (in s) |
+------+-----------------------+-------------+
| 1    | unlock_keychain       | 4           |
| 2    | setup_jenkins         | 0           |
| 3    | update_app_identifier | 0           |
| 4    | update_info_plist     | 0           |
| 5    | update_project_team   | 0           |
| 6    | get_push_certificate  | 2           |
| 💥   | register_devices      | 3           |
+------+-----------------------+-------------+

[15:55:21]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
bundler: failed to load command: fastlane (/Users/moox/.gem/bin/fastlane)
FastlaneCore::Interface::FastlaneCrash: [!] Failed to register new device (name: *redacted*, UDID: 3a6ed4ae8465d1c71638a5934e7e8af2579cxxxx)
  /Users/moox/.gem/gems/fastlane-2.178.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!'
  /Users/moox/.gem/gems/fastlane-2.178.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /Users/moox/.gem/gems/fastlane-2.178.0/fastlane/lib/fastlane/actions/register_devices.rb:83:in `rescue in try_create_device'
  /Users/moox/.gem/gems/fastlane-2.178.0/fastlane/lib/fastlane/actions/register_devices.rb:79:in `try_create_device'
  /Users/moox/.gem/gems/fastlane-2.178.0/fastlane/lib/fastlane/actions/register_devices.rb:72:in `block in run'
  /Users/moox/.gem/gems/fastlane-2.178.0/fastlane/lib/fastlane/actions/register_devices.rb:55:in `map'
  /Users/moox/.gem/gems/fastlane-2.178.0/fastlane/lib/fastlane/actions/register_devices.rb:55:in `run'
  /Users/moox/.gem/gems/fastlane-2.178.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  /Users/moox/.gem/gems/fastlane-2.178.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
  /Users/moox/.gem/gems/fastlane-2.178.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  /Users/moox/.gem/gems/fastlane-2.178.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  /Users/moox/.gem/gems/fastlane-2.178.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  /Users/moox/.gem/gems/fastlane-2.178.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/moox/.gem/gems/fastlane-2.178.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:118:in `block (2 levels) in parsing_binding'
  /Users/moox/.gem/gems/fastlane-2.178.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/moox/.gem/gems/fastlane-2.178.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/moox/.gem/gems/fastlane-2.178.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/moox/.gem/gems/fastlane-2.178.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/moox/.gem/gems/fastlane-2.178.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /Users/moox/.gem/gems/fastlane-2.178.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/moox/.gem/gems/fastlane-2.178.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/moox/.gem/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/moox/.gem/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/moox/.gem/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/moox/.gem/gems/fastlane-2.178.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/moox/.gem/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/moox/.gem/gems/fastlane-2.178.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  /Users/moox/.gem/gems/fastlane-2.178.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/moox/.gem/gems/fastlane-2.178.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
  /Users/moox/.gem/gems/fastlane-2.178.0/bin/fastlane:23:in `<top (required)>'
  /Users/moox/.gem/bin/fastlane:23:in `load'
  /Users/moox/.gem/bin/fastlane:23:in `<top (required)>'
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.2.3                                      |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.gem/bin/fastlane                         |
| Host                        | macOS 11.2.3 (20D91)                        |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.3/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.4                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
apple_id = "adm@kisio.com"

android_project_dir = "android"
android_task = "assemble"
android_build_type = "Release"

ios_scheme = "ADM"
ios_workspace = "ios/ADM.xcworkspace"
ios_xcodeproj = "ios/ADM.xcodeproj"
ios_output_directory = "./ios/release"
ios_plist_path = "ADM/Info.plist"
ios_clean = true
ios_codesigning_git_branch = ENV["ADM_VARIANT"] != nil ?
  "adm-variant-"+ENV["ADM_VARIANT"] :
  "adm-variant-adm"

platform :android do
  before_all do
    skip_docs
  end

  desc "build an adhoc release for internal store"
  lane :adhoc do
    gradle(
      project_dir: android_project_dir,
      task: android_task,
      build_type: android_build_type,
    )
  end

  desc "Submit a new Internal Build to Google Play "
  lane :beta do |options|
    track = 'internal'
    gradle_file_path = "android/app/build.gradle"
    json_key = 'android/app/google-service-account-key.json'
    
    versionName = ENV["android_baseVersionName"]+"."+ENV["ADM3_VERSION"]
    begin
      version_codes = google_play_track_version_codes(
        package_name: ENV["android_applicationId"],
        track: track,
        json_key: json_key,
      )
    rescue
      version_codes = nil
    end
    versionCode = (version_codes.nil? ? 0 : version_codes.max) + 1;
    UI.message "google_play_track_version_codes"
    UI.message version_codes
    UI.message "versionCode"
    UI.message versionCode
    increment_version_code(
      version_code: versionCode,
      gradle_file_path: gradle_file_path
    )
    gradle(
      project_dir: android_project_dir,
      task: android_task,
      build_type: android_build_type,
    )
    upload_to_play_store(
      package_name: ENV["android_applicationId"],
      track: track,
      json_key: json_key,
      version_name: versionName,
      version_code: versionCode
    )
  end
end

platform :ios do
  before_all do
    CURRENT_USER = `whoami`.chomp
    KEYCHAINE_PATH = "/Users/"+CURRENT_USER+"/Library/Keychains/fastlane.keychain-db"
    if !File.exists?(KEYCHAINE_PATH)
      create_keychain(
        path: KEYCHAINE_PATH,
        password: ENV["KEYCHAIN_PASSWORD"],
      )
    end
    unlock_keychain(
      path: KEYCHAINE_PATH,
      password: ENV["KEYCHAIN_PASSWORD"],
    )

    setup_jenkins(
      ## we don't use https://wiki.jenkins-ci.org/display/JENKINS/Keychains+and+Provisioning+Profiles+Plugin
      unlock_keychain: false,
      set_default_keychain: false,
    )
    skip_docs

    # update xcodeproj with variant information
    update_app_identifier(
      xcodeproj: ios_xcodeproj,
      plist_path: ios_plist_path,
      app_identifier: ENV["ios_applicationId"],
    )
    update_info_plist(
      xcodeproj: ios_xcodeproj,
      plist_path: ios_plist_path,
      app_identifier: ENV["ios_applicationId"],
      display_name: ENV["ios_displayName"],
    )
    update_project_team(
      path: ios_xcodeproj,
      teamid: ENV["ios_developerPortalTeamId"],
    )
    get_push_certificate(
      username: apple_id,
      team_id: ENV["ios_developerPortalTeamId"],
      app_identifier: ENV["ios_applicationId"],
    )
  end

  desc "prepare certs && pp, to use by hand, not on ci"
  lane :sync_code_signing_write do
    register_devices(
      username: apple_id,
      team_id: ENV["ios_developerPortalTeamId"],
      devices_file: "./fastlane/devices.txt",
    )
    
    # match
    sync_code_signing(
      type: "development",
      username: apple_id,
      team_id: ENV["ios_developerPortalTeamId"],
      keychain_password: ENV["KEYCHAIN_PASSWORD"],
      git_branch: ios_codesigning_git_branch,
      app_identifier: ENV["ios_applicationId"],
    )
    # match
    sync_code_signing(
      type: "adhoc",
      username: apple_id,
      team_id: ENV["ios_developerPortalTeamId"],
      keychain_password: ENV["KEYCHAIN_PASSWORD"],
      git_branch: ios_codesigning_git_branch,
      app_identifier: ENV["ios_applicationId"],
    )
    # match
    sync_code_signing(
      type: "appstore",
      username: apple_id,
      team_id: ENV["ios_developerPortalTeamId"],
      keychain_password: ENV["KEYCHAIN_PASSWORD"],
      git_branch: ios_codesigning_git_branch,
      app_identifier: ENV["ios_applicationId"],
    )
  end

  desc "build an adhoc release for internal store"
  lane :adhoc do
    update_provisioning_profile_specifier(
      xcodeproj: ios_xcodeproj,
      target: "ADM",
      new_specifier: "match AdHoc "+ENV["ios_applicationId"],
    )
    
    # match
    sync_code_signing(
      type: "adhoc",
      username: apple_id,
      team_id: ENV["ios_developerPortalTeamId"],
      keychain_password: ENV["KEYCHAIN_PASSWORD"],
      git_branch: ios_codesigning_git_branch,
      app_identifier: ENV["ios_applicationId"],
      readonly: true,
    )
    
    # gym
    signing_type = "adhoc"
    build_app(
      scheme: ios_scheme,
      workspace: ios_workspace,
      clean: ios_clean,
      output_directory: ios_output_directory,
      xcargs: {
        # defined by match/sync_code_signing
        PROVISIONING_PROFILE_SPECIFIER: ENV["sigh_#{ENV["ios_applicationId"]}_#{signing_type}"],
        # override default that is used for local development
        CODE_SIGN_IDENTITY: "iPhone Distribution",
      },
      export_team_id: ENV["ios_developerPortalTeamId"],
      export_method: 'ad-hoc',
      export_options: {
        manifest: {
          appURL: ENV["URL_IOS_IPA"],
          displayImageURL: ENV["URL_APP_LOGO"],
          fullSizeImageURL: ENV["URL_APP_LOGO"],
        },  
        # because of masabi / justridesdk
        # see also ios/Podfile 'ENABLE_BITCODE' option
        compileBitcode: false,
      }
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # prepare release version
    versionName = ENV["ios_baseVersionName"]+"."+ENV["ADM3_VERSION"]
    increment_version_number(
      version_number: versionName,
      xcodeproj: ios_xcodeproj,
    )
    build_number = latest_testflight_build_number(
      username: apple_id,
      initial_build_number: 0,
      version: versionName,
      app_identifier: ENV["ios_applicationId"],
      team_id: ENV["ios_appStoreConnectTeamId"],
    )
    increment_build_number(
      build_number: build_number + 1,
      xcodeproj: ios_xcodeproj,
    )
    
    update_provisioning_profile_specifier(
      xcodeproj: ios_xcodeproj,
      target: "ADM",
      new_specifier: "match AppStore "+ENV["ios_applicationId"],
    )
    
    # match
    sync_code_signing(
      type: "appstore",
      username: apple_id,
      team_id: ENV["ios_developerPortalTeamId"],
      keychain_password: ENV["KEYCHAIN_PASSWORD"],
      app_identifier: ENV["ios_applicationId"],
      git_branch: ios_codesigning_git_branch,
      readonly: true,
    )

    # gym
    signing_type = "appstore"
    build_app(
      scheme: ios_scheme,
      workspace: ios_workspace,
      clean: ios_clean,
      output_directory: ios_output_directory,
      xcargs: {
        # defined by match/sync_code_signing
        PROVISIONING_PROFILE_SPECIFIER: ENV["sigh_#{ENV["ios_applicationId"]}_#{signing_type}"],
        # override default that is used for local development
        CODE_SIGN_IDENTITY: "iPhone Distribution",
      },
      # because of masabi / justridesdk
      # see also ios/Podfile 'ENABLE_BITCODE' option
      export_options: {
        uploadBitcode: false,
      },
    )
    upload_to_testflight(
      username: apple_id,
      dev_portal_team_id: ENV["ios_developerPortalTeamId"],
      team_id: ENV["ios_appStoreConnectTeamId"],
      itc_provider: ENV["ios_appStoreConnectProviderShortName"],
      app_identifier: ENV["ios_applicationId"],
      # skip_waiting_for_build_processing: true,
    )
  end
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.178.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                                | Version | Update-Status |
| ----------------------------------------------------- | ------- | ------------- |
| fastlane-plugin-increment_version_code                | 0.4.3   | ✅ Up-To-Date  |
| fastlane-plugin-update_provisioning_profile_specifier | 1.3.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                                   | Version      |
| ----------------------------------------------------- | ------------ |
| bundler                                               | 1.17.2       |
| etc                                                   | 1.0.1        |
| forwardable                                           | 1.2.0        |
| rake                                                  | 13.0.3       |
| CFPropertyList                                        | 3.0.3        |
| concurrent-ruby                                       | 1.1.8        |
| i18n                                                  | 1.8.9        |
| minitest                                              | 5.14.4       |
| thread_safe                                           | 0.3.6        |
| tzinfo                                                | 1.2.9        |
| activesupport                                         | 5.2.4.5      |
| public_suffix                                         | 4.0.6        |
| addressable                                           | 2.7.0        |
| httpclient                                            | 2.8.3        |
| json                                                  | 2.5.1        |
| algoliasearch                                         | 1.27.5       |
| artifactory                                           | 3.0.15       |
| atomos                                                | 0.1.3        |
| aws-eventstream                                       | 1.1.1        |
| aws-partitions                                        | 1.434.0      |
| aws-sigv4                                             | 1.2.3        |
| jmespath                                              | 1.4.0        |
| aws-sdk-core                                          | 3.113.0      |
| aws-sdk-kms                                           | 1.43.0       |
| aws-sdk-s3                                            | 1.91.0       |
| babosa                                                | 1.0.4        |
| claide                                                | 1.0.3        |
| fuzzy_match                                           | 2.0.4        |
| nap                                                   | 1.1.0        |
| netrc                                                 | 0.11.0       |
| ffi                                                   | 1.15.0       |
| ethon                                                 | 0.12.0       |
| typhoeus                                              | 1.4.0        |
| cocoapods-core                                        | 1.10.1       |
| cocoapods-deintegrate                                 | 1.0.4        |
| cocoapods-downloader                                  | 1.4.0        |
| cocoapods-plugins                                     | 1.0.0        |
| cocoapods-search                                      | 1.0.0        |
| cocoapods-trunk                                       | 1.5.0        |
| cocoapods-try                                         | 1.2.0        |
| colored2                                              | 3.1.2        |
| escape                                                | 0.0.4        |
| fourflusher                                           | 2.3.1        |
| gh_inspector                                          | 1.1.3        |
| molinillo                                             | 0.6.6        |
| ruby-macho                                            | 1.4.0        |
| nanaimo                                               | 0.3.0        |
| xcodeproj                                             | 1.19.0       |
| cocoapods                                             | 1.10.1       |
| colored                                               | 1.2          |
| highline                                              | 1.7.10       |
| commander-fastlane                                    | 4.4.6        |
| declarative                                           | 0.0.20       |
| declarative-option                                    | 0.1.0        |
| digest-crc                                            | 0.6.3        |
| unf_ext                                               | 0.0.7.7      |
| unf                                                   | 0.1.4        |
| domain_name                                           | 0.5.20190701 |
| dotenv                                                | 2.7.6        |
| emoji_regex                                           | 3.2.2        |
| excon                                                 | 0.79.0       |
| faraday-net_http                                      | 1.0.1        |
| multipart-post                                        | 2.0.0        |
| ruby2_keywords                                        | 0.0.4        |
| faraday                                               | 1.3.0        |
| http-cookie                                           | 1.0.3        |
| faraday-cookie_jar                                    | 0.0.7        |
| faraday_middleware                                    | 1.0.0        |
| fastimage                                             | 2.2.3        |
| jwt                                                   | 2.2.2        |
| memoist                                               | 0.16.2       |
| multi_json                                            | 1.15.0       |
| os                                                    | 1.1.1        |
| signet                                                | 0.15.0       |
| googleauth                                            | 0.16.0       |
| mini_mime                                             | 1.0.2        |
| uber                                                  | 0.1.0        |
| representable                                         | 3.0.4        |
| retriable                                             | 3.1.2        |
| google-api-client                                     | 0.38.0       |
| rexml                                                 | 3.2.4        |
| webrick                                               | 1.7.0        |
| google-apis-core                                      | 0.3.0        |
| google-apis-iamcredentials_v1                         | 0.2.0        |
| google-apis-storage_v1                                | 0.3.0        |
| google-cloud-env                                      | 1.5.0        |
| google-cloud-errors                                   | 1.1.0        |
| google-cloud-core                                     | 1.6.0        |
| google-cloud-storage                                  | 1.31.0       |
| mini_magick                                           | 4.11.0       |
| naturally                                             | 2.2.1        |
| plist                                                 | 3.6.0        |
| rubyzip                                               | 2.3.0        |
| security                                              | 0.1.3        |
| simctl                                                | 1.6.8        |
| slack-notifier                                        | 2.3.2        |
| terminal-notifier                                     | 2.0.0        |
| unicode-display_width                                 | 1.7.0        |
| terminal-table                                        | 1.8.0        |
| tty-screen                                            | 0.8.1        |
| tty-cursor                                            | 0.7.1        |
| tty-spinner                                           | 0.9.3        |
| word_wrap                                             | 1.0.0        |
| rouge                                                 | 2.0.7        |
| xcpretty                                              | 0.3.0        |
| xcpretty-travis-formatter                             | 1.0.1        |
| fastlane-plugin-increment_version_code                | 0.4.3        |
| fastlane-plugin-update_provisioning_profile_specifier | 1.3.1        |
</details>

*generated on:* **2021-03-18**
</details>

**Comment by michalsurynt** [comment]
git the same while calling `fastlane match adhoc`:
`/usr/local/Cellar/fastlane/2.177.0/libexec/gems/fastlane-2.177.0/spaceship/lib/spaceship/connect_api/api_client.rb:214:in `handle_error': undefined method `first' for "errors":String (NoMethodError)`

**Comment by max-ott** [comment]
What's the format / content of the file you are trying to use. These kind of error messages usually pop up if the input is not in the correct format.

**Comment by MoOx** [comment]
it's in the top of the description. The exact same file has worked for many months. No edit. Just a fast lane update (or an App Store connect one) did this :(

**Comment by mykone** [comment]
Same thing happens with the latest version of fastlane. I believe this issue is also related to #18431

**Comment by nickderobertis-ch** [comment]
I am also facing this issue on fastlane `2.183.2`. I tried downgrading to `2.176.0`, and instead I get `Access forbidden`.

**Comment by abraaolevi** [comment]
@MoOx @nickderobertis-ch I was also experiencing this issue, but this was only because the Account Holder needed to agree to the latest Program License Agreement. Once they agree, everything works fine.

**Comment by code-src** [comment]
I reported the error with the developer account, but it was successfully executed with another admin and account holder account. Maybe this is the direction to solve the problem.
