### ISSUE TITLE
[Frameit] - fastlane frameit download_frames fails

### ISSUE THREAD

**Issue by guidev** [fastlane/fastlane#18422]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When running `fastlane frameit download_frames` i get the following error: `Error accessing URL ''`
 

##### Command executed

`fastlane frameit download_frames`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>fastlane frameit download_frames
[✔] 🚀
[13:49:09]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[13:49:12]: --------------------------------
[13:49:12]: --- Device frames disclaimer ---
[13:49:12]: --------------------------------
[13:49:12]: All used device frames are available via Facebook Design: http://facebook.design/devices
[13:49:12]: ----------------------------------------
[13:49:12]: While Facebook has redrawn and shares these assets for the benefit
[13:49:12]: of the design community, Facebook does not own any of the underlying
[13:49:12]: product or user interface designs.
[13:49:12]: By accessing these assets, you agree to obtain all necessary permissions
[13:49:12]: from the underlying rights holders and/or adhere to any applicable brand
[13:49:12]: use guidelines before using them.
[13:49:12]: Facebook disclaims all express or implied warranties with respect to these assets, including
[13:49:12]: non-infringement of intellectual property rights.
[13:49:12]: ----------------------------------------
[13:49:12]: Using device frames version 'latest'
[13:49:12]: Downloading device frames to '/Users/username/.fastlane/frameit/latest'
[13:49:12]: undefined method `escape' for URI:Module

[!] Error accessing URL ''</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.2.3                                      |
| Ruby                        | 2.7.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.31.0                          |
| Installation Source         | ~/.rvm/gems/ruby-2.7.0/bin/fastlane         |
| Host                        | macOS 11.2.3 (20D91)                        |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.7.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.4                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number
    build_app(workspace: "App.xcworkspace", scheme: "App")
    upload_to_app_store
  end


end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("redacted") # The bundle identifier of your app
apple_id("redacted") # Your Apple email address

itc_team_id("redacted") # App Store Connect Team ID
team_id("redacted") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.178.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.5.0        |
| executable-hooks              | 1.6.1        |
| bundler-unload                | 1.0.2        |
| rubygems-bundler              | 1.4.5        |
| bundler                       | 2.2.14       |
| slack-notifier                | 2.3.2        |
| atomos                        | 0.1.3        |
| CFPropertyList                | 3.0.3        |
| claide                        | 1.0.3        |
| colored2                      | 3.1.2        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| plist                         | 3.6.0        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| multipart-post                | 2.0.0        |
| word_wrap                     | 1.0.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| artifactory                   | 3.0.15       |
| babosa                        | 1.0.4        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| excon                         | 0.79.0       |
| faraday-net_http              | 1.0.1        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.3        |
| gh_inspector                  | 1.1.3        |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| xcpretty-travis-formatter     | 1.0.1        |
| dotenv                        | 2.7.6        |
| simctl                        | 1.6.8        |
| jwt                           | 2.2.2        |
| uber                          | 0.1.0        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.1        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| mini_mime                     | 1.0.2        |
| multi_json                    | 1.15.0       |
| signet                        | 0.15.0       |
| memoist                       | 0.16.2       |
| os                            | 1.1.1        |
| googleauth                    | 0.16.0       |
| httpclient                    | 2.8.3        |
| google-api-client             | 0.38.0       |
| google-cloud-env              | 1.5.0        |
| google-cloud-errors           | 1.1.0        |
| google-cloud-core             | 1.6.0        |
| google-apis-core              | 0.3.0        |
| google-apis-iamcredentials_v1 | 0.2.0        |
| google-apis-storage_v1        | 0.3.0        |
| digest-crc                    | 0.6.3        |
| google-cloud-storage          | 1.31.0       |
| emoji_regex                   | 3.2.2        |
| jmespath                      | 1.4.0        |
| aws-partitions                | 1.433.0      |
| aws-eventstream               | 1.1.1        |
| aws-sigv4                     | 1.2.3        |
| aws-sdk-core                  | 3.113.0      |
| aws-sdk-kms                   | 1.43.0       |
| aws-sdk-s3                    | 1.91.0       |
| uri                           | 0.10.1       |
| json                          | 2.5.1        |
| rexml                         | 3.2.4        |
| webrick                       | 1.7.0        |
| rake                          | 13.0.3       |
| forwardable                   | 1.3.2        |
| logger                        | 1.4.3        |
| cgi                           | 0.2.0        |
| date                          | 3.1.1        |
| timeout                       | 0.1.1        |
| stringio                      | 3.0.0        |
| zlib                          | 1.1.0        |
| openssl                       | 2.2.0        |
| ipaddr                        | 1.2.2        |
| ostruct                       | 0.3.3        |
| strscan                       | 3.0.0        |
| delegate                      | 0.2.0        |
| fileutils                     | 1.5.0        |
| io-console                    | 0.5.9        |
| open3                         | 0.1.1        |
| singleton                     | 0.1.1        |
| yaml                          | 0.1.1        |
| psych                         | 3.3.1        |
| mutex_m                       | 0.1.1        |
</details>

*generated on:* **2021-03-18**
</details> </pre>
</details>

**Comment by gelodgreat** [comment]
up for this
