### ISSUE TITLE
How can we specify a device and OS for which to use for testing.

### ISSUE THREAD

**Issue by dallas-lbg** [fastlane/fastlane#18421]
For example:
There are examples specifying a device eg `iPhone 8` but how can I reliably define I would like `iPhone 8` with iOS 13.5
When applied as an argument to the `run_tests` action in my Fastfile:

    run_tests(
        fail_build: true,
        output_files: "",
        output_types: "",
        scheme: "VBP-iOS-Demo",
        device: "OS:13.5, name:iPhone 8",  # ************* Here is the problem line *****************
        ensure_devices_found: true,
        xcargs: "-parallel-testing-enabled NO",
        derived_data_path: derivedDataPath,
        reset_simulator: true
  )

I have tried `iPhone 8@13.5`, `iPhone 8 (13.5)` and `"OS:13.5, name:iPhone 8"` and none of them worked.

I am using Fastlane v 2.178.0

**Comment by Kukurijek** [comment]
The right way would be:
`devices: ["iPhone 8 (13.5)"] `

If device is not found tests will fail, because you set `ensure_devices_found: true`

Docs: https://docs.fastlane.tools/actions/run_tests/#parameters

**Comment by dallas-lbg** [comment]
> The right way would be:
> `devices: ["iPhone 8 (13.5)"] `
> 
> If device is not found tests will fail, because you set `ensure_devices_found: true`
> 
> Docs: https://docs.fastlane.tools/actions/run_tests/#parameters

That's the behaviour I would have expected too. However, when I remove the `ensure_devices_found: true` param and run the tests Fastlane runs with `iPhone 8 (13.5)` as an autoselected simulator which is what it was also doing without either the `devices: ...` or the `ensure_devices_found: true`. 

Therefore that would suggest including both parameters is not having the desired effect of ensuring the tests run only with the intended device and fails otherwise.

**Comment by Kukurijek** [comment]
> > The right way would be:
> > `devices: ["iPhone 8 (13.5)"] `
> > If device is not found tests will fail, because you set `ensure_devices_found: true`
> > Docs: https://docs.fastlane.tools/actions/run_tests/#parameters
> 
> That's the behaviour I would have expected too. However, when I remove the `ensure_devices_found: true` param and run the tests Fastlane runs with `iPhone 8 (13.5)` as an autoselected simulator which is what it was also doing without either the `devices: ...` or the `ensure_devices_found: true`.
> 
> Therefore that would suggest including both parameters is not having the desired effect of ensuring the tests run only with the intended device and fails otherwise.

Most probably your default simulator is `iPhone 8 (13.5)`.
I do not understand what actually your problem is? Please provide the output.
