### ISSUE TITLE
[snapshot] Generated html does not contain all screenshots (some devices missing)

### ISSUE THREAD

**Issue by OliverDobner** [fastlane/fastlane#18423]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
My snapfile defines this devices:
devices([
    "iPhone SE (1st generation)",
    "iPhone SE (2nd generation)",
    "iPhone 8",
    "iPhone 12",
    "iPhone 12 Pro Max"
  ])

The screenshots are all generated. (see shortened output for iPhone 12 Pro Max". On the generated html page the iPhone 12 and iPhone 12 Pro Max are missing. (and iPhone SE is 1st./2nd. gen all in one row)

##### Command executed
desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(scheme: "xxxx")
  end

##### Complete output when running fastlane, including the stack trace and command used

<details>
... shortened...
[14:40:12]: ▸ Test Succeeded
[14:40:12]: Clearing Status Bar Override
[14:40:12]: $ xcrun simctl status_bar 64AC555A-F140-426E-AF2A-D71A88D7B67A clear &> /dev/null
[14:40:12]: Copying '/Users/oliverdobner/Projekte/bcm/fastlane/screenshots/de-DE/iPhone 12 Pro Max-1Menu.png'...
[14:40:12]: Copying '/Users/oliverdobner/Projekte/bcm/fastlane/screenshots/de-DE/iPhone 12 Pro Max-4Worktime.png'...
[14:40:12]: Copying '/Users/oliverdobner/Projekte/bcm/fastlane/screenshots/de-DE/iPhone 12 Pro Max-2ProductionOverview.png'...
[14:40:12]: Copying '/Users/oliverdobner/Projekte/bcm/fastlane/screenshots/de-DE/iPhone 12 Pro Max-0Launch.png'...
[14:40:12]: Copying '/Users/oliverdobner/Projekte/bcm/fastlane/screenshots/de-DE/iPhone 12 Pro Max-3EquipmentOverview.png'...

+----------------------------+-------+-------+
|              snapshot results              |
+----------------------------+-------+-------+
| Device                     | en-US | de-DE |
+----------------------------+-------+-------+
| iPhone SE (1st generation) |  💚   |  💚   |
| iPhone SE (2nd generation) |  💚   |  💚   |
| iPhone 8                   |  💚   |  💚   |
| iPhone 12                  |  💚   |  💚   |
| iPhone 12 Pro Max          |  💚   |  💚   |
+----------------------------+-------+-------+

[14:40:12]: Generating HTML Report
[14:40:12]: Successfully created HTML file with an overview of all the screenshots: '/Users/oliverdobner/Projekte/bcm/fastlane/screenshots/screenshots.html'

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | default_platform    | 0           |
| 2    | capture_screenshots | 667         |
+------+---------------------+-------------+

[14:40:13]: fastlane.tools just saved you 11 minutes! 🎉

  <div id="byLanguage" class="tabContent"><h1 class="tabTitle">By Language:</h1>
      <h2 id="de-DE">de-DE</h2>
      <hr>
      <table>
        <tr>
          <th colspan="5">
            <a id="de-DE-iPhone 8" class="deviceName" href="#de-DE-iPhone 8">iPhone 8</a>
          </th>
        </tr>
        <tr>
          <td>
            <a href="./de-DE/iPhone 8-0Launch.png" target="_blank" class="screenshotLink">
              <img class="screenshot" src="./de-DE/iPhone 8-0Launch.png" style="width: 100%;" alt="de-DE iPhone 8" data-tab="1" data-counter="1">
            </a>
          </td>
          <td>
            <a href="./de-DE/iPhone 8-1Menu.png" target="_blank" class="screenshotLink">
              <img class="screenshot" src="./de-DE/iPhone 8-1Menu.png" style="width: 100%;" alt="de-DE iPhone 8" data-tab="1" data-counter="2">
            </a>
          </td>
          <td>
            <a href="./de-DE/iPhone 8-2ProductionOverview.png" target="_blank" class="screenshotLink">
              <img class="screenshot" src="./de-DE/iPhone 8-2ProductionOverview.png" style="width: 100%;" alt="de-DE iPhone 8" data-tab="1" data-counter="3">
            </a>
          </td>
          <td>
            <a href="./de-DE/iPhone 8-3EquipmentOverview.png" target="_blank" class="screenshotLink">
              <img class="screenshot" src="./de-DE/iPhone 8-3EquipmentOverview.png" style="width: 100%;" alt="de-DE iPhone 8" data-tab="1" data-counter="4">
            </a>
          </td>
          <td>
            <a href="./de-DE/iPhone 8-4Worktime.png" target="_blank" class="screenshotLink">
              <img class="screenshot" src="./de-DE/iPhone 8-4Worktime.png" style="width: 100%;" alt="de-DE iPhone 8" data-tab="1" data-counter="5">
            </a>
          </td>
        </tr>
        <tr>
          <th colspan="10">
            <a id="de-DE-iPhone SE" class="deviceName" href="#de-DE-iPhone SE">iPhone SE</a>
          </th>
        </tr>
        <tr>
          <td>
            <a href="./de-DE/iPhone SE (1st generation)-0Launch.png" target="_blank" class="screenshotLink">
              <img class="screenshot" src="./de-DE/iPhone SE (1st generation)-0Launch.png" style="width: 100%;" alt="de-DE iPhone SE" data-tab="1" data-counter="6">
            </a>
          </td>
          <td>
            <a href="./de-DE/iPhone SE (1st generation)-1Menu.png" target="_blank" class="screenshotLink">
              <img class="screenshot" src="./de-DE/iPhone SE (1st generation)-1Menu.png" style="width: 100%;" alt="de-DE iPhone SE" data-tab="1" data-counter="7">
            </a>
          </td>
          <td>
            <a href="./de-DE/iPhone SE (1st generation)-2ProductionOverview.png" target="_blank" class="screenshotLink">
              <img class="screenshot" src="./de-DE/iPhone SE (1st generation)-2ProductionOverview.png" style="width: 100%;" alt="de-DE iPhone SE" data-tab="1" data-counter="8">
            </a>
          </td>
          <td>
            <a href="./de-DE/iPhone SE (1st generation)-3EquipmentOverview.png" target="_blank" class="screenshotLink">
              <img class="screenshot" src="./de-DE/iPhone SE (1st generation)-3EquipmentOverview.png" style="width: 100%;" alt="de-DE iPhone SE" data-tab="1" data-counter="9">
            </a>
          </td>
          <td>
            <a href="./de-DE/iPhone SE (1st generation)-4Worktime.png" target="_blank" class="screenshotLink">
              <img class="screenshot" src="./de-DE/iPhone SE (1st generation)-4Worktime.png" style="width: 100%;" alt="de-DE iPhone SE" data-tab="1" data-counter="10">
            </a>
          </td>
          <td>
            <a href="./de-DE/iPhone SE (2nd generation)-0Launch.png" target="_blank" class="screenshotLink">
              <img class="screenshot" src="./de-DE/iPhone SE (2nd generation)-0Launch.png" style="width: 100%;" alt="de-DE iPhone SE" data-tab="1" data-counter="11">
            </a>
          </td>
          <td>
            <a href="./de-DE/iPhone SE (2nd generation)-1Menu.png" target="_blank" class="screenshotLink">
              <img class="screenshot" src="./de-DE/iPhone SE (2nd generation)-1Menu.png" style="width: 100%;" alt="de-DE iPhone SE" data-tab="1" data-counter="12">
            </a>
          </td>
          <td>
            <a href="./de-DE/iPhone SE (2nd generation)-2ProductionOverview.png" target="_blank" class="screenshotLink">
              <img class="screenshot" src="./de-DE/iPhone SE (2nd generation)-2ProductionOverview.png" style="width: 100%;" alt="de-DE iPhone SE" data-tab="1" data-counter="13">
            </a>
          </td>
          <td>
            <a href="./de-DE/iPhone SE (2nd generation)-3EquipmentOverview.png" target="_blank" class="screenshotLink">
              <img class="screenshot" src="./de-DE/iPhone SE (2nd generation)-3EquipmentOverview.png" style="width: 100%;" alt="de-DE iPhone SE" data-tab="1" data-counter="14">
            </a>
          </td>
          <td>
            <a href="./de-DE/iPhone SE (2nd generation)-4Worktime.png" target="_blank" class="screenshotLink">
              <img class="screenshot" src="./de-DE/iPhone SE (2nd generation)-4Worktime.png" style="width: 100%;" alt="de-DE iPhone SE" data-tab="1" data-counter="15">
            </a>
          </td>
        </tr>
      </table>
      <h2 id="en-US">en-US</h2>
      <hr>
      <table>
        <tr>
          <th colspan="5">
            <a id="en-US-iPhone 8" class="deviceName" href="#en-US-iPhone 8">iPhone 8</a>
          </th>
        </tr>
        <tr>
          <td>
            <a href="./en-US/iPhone 8-0Launch.png" target="_blank" class="screenshotLink">
              <img class="screenshot" src="./en-US/iPhone 8-0Launch.png" style="width: 100%;" alt="en-US iPhone 8" data-tab="1" data-counter="16">
            </a>
          </td>
          <td>
            <a href="./en-US/iPhone 8-1Menu.png" target="_blank" class="screenshotLink">
              <img class="screenshot" src="./en-US/iPhone 8-1Menu.png" style="width: 100%;" alt="en-US iPhone 8" data-tab="1" data-counter="17">
            </a>
          </td>
          <td>
            <a href="./en-US/iPhone 8-2ProductionOverview.png" target="_blank" class="screenshotLink">
              <img class="screenshot" src="./en-US/iPhone 8-2ProductionOverview.png" style="width: 100%;" alt="en-US iPhone 8" data-tab="1" data-counter="18">
            </a>
          </td>
          <td>
            <a href="./en-US/iPhone 8-3EquipmentOverview.png" target="_blank" class="screenshotLink">
              <img class="screenshot" src="./en-US/iPhone 8-3EquipmentOverview.png" style="width: 100%;" alt="en-US iPhone 8" data-tab="1" data-counter="19">
            </a>
          </td>
          <td>
            <a href="./en-US/iPhone 8-4Worktime.png" target="_blank" class="screenshotLink">
              <img class="screenshot" src="./en-US/iPhone 8-4Worktime.png" style="width: 100%;" alt="en-US iPhone 8" data-tab="1" data-counter="20">
            </a>
          </td>
        </tr>
        <tr>
          <th colspan="10">
            <a id="en-US-iPhone SE" class="deviceName" href="#en-US-iPhone SE">iPhone SE</a>
          </th>
        </tr>
        <tr>
          <td>
            <a href="./en-US/iPhone SE (1st generation)-0Launch.png" target="_blank" class="screenshotLink">
              <img class="screenshot" src="./en-US/iPhone SE (1st generation)-0Launch.png" style="width: 100%;" alt="en-US iPhone SE" data-tab="1" data-counter="21">
            </a>
          </td>
          <td>
            <a href="./en-US/iPhone SE (1st generation)-1Menu.png" target="_blank" class="screenshotLink">
              <img class="screenshot" src="./en-US/iPhone SE (1st generation)-1Menu.png" style="width: 100%;" alt="en-US iPhone SE" data-tab="1" data-counter="22">
            </a>
          </td>
          <td>
            <a href="./en-US/iPhone SE (1st generation)-2ProductionOverview.png" target="_blank" class="screenshotLink">
              <img class="screenshot" src="./en-US/iPhone SE (1st generation)-2ProductionOverview.png" style="width: 100%;" alt="en-US iPhone SE" data-tab="1" data-counter="23">
            </a>
          </td>
          <td>
            <a href="./en-US/iPhone SE (1st generation)-3EquipmentOverview.png" target="_blank" class="screenshotLink">
              <img class="screenshot" src="./en-US/iPhone SE (1st generation)-3EquipmentOverview.png" style="width: 100%;" alt="en-US iPhone SE" data-tab="1" data-counter="24">
            </a>
          </td>
          <td>
            <a href="./en-US/iPhone SE (1st generation)-4Worktime.png" target="_blank" class="screenshotLink">
              <img class="screenshot" src="./en-US/iPhone SE (1st generation)-4Worktime.png" style="width: 100%;" alt="en-US iPhone SE" data-tab="1" data-counter="25">
            </a>
          </td>
          <td>
            <a href="./en-US/iPhone SE (2nd generation)-0Launch.png" target="_blank" class="screenshotLink">
              <img class="screenshot" src="./en-US/iPhone SE (2nd generation)-0Launch.png" style="width: 100%;" alt="en-US iPhone SE" data-tab="1" data-counter="26">
            </a>
          </td>
          <td>
            <a href="./en-US/iPhone SE (2nd generation)-1Menu.png" target="_blank" class="screenshotLink">
              <img class="screenshot" src="./en-US/iPhone SE (2nd generation)-1Menu.png" style="width: 100%;" alt="en-US iPhone SE" data-tab="1" data-counter="27">
            </a>
          </td>
          <td>
            <a href="./en-US/iPhone SE (2nd generation)-2ProductionOverview.png" target="_blank" class="screenshotLink">
              <img class="screenshot" src="./en-US/iPhone SE (2nd generation)-2ProductionOverview.png" style="width: 100%;" alt="en-US iPhone SE" data-tab="1" data-counter="28">
            </a>
          </td>
          <td>
            <a href="./en-US/iPhone SE (2nd generation)-3EquipmentOverview.png" target="_blank" class="screenshotLink">
              <img class="screenshot" src="./en-US/iPhone SE (2nd generation)-3EquipmentOverview.png" style="width: 100%;" alt="en-US iPhone SE" data-tab="1" data-counter="29">
            </a>
          </td>
          <td>
            <a href="./en-US/iPhone SE (2nd generation)-4Worktime.png" target="_blank" class="screenshotLink">
              <img class="screenshot" src="./en-US/iPhone SE (2nd generation)-4Worktime.png" style="width: 100%;" alt="en-US iPhone SE" data-tab="1" data-counter="30">
            </a>
          </td>
        </tr>
      </table>
    </div>

</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                |
| --------------------------- | ---------------------------------------------------- |
| OS                          | 11.2.3                                               |
| Ruby                        | 2.6.6                                                |
| Bundler?                    | true                                                 |
| Git                         | git version 2.24.3 (Apple Git-128)                   |
| Installation Source         | ~/Projekte/bcm/vendor/bundle/ruby/2.6.0/bin/fastlane |
| Host                        | macOS 11.2.3 (20D91)                                 |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.6/2.6.6_1/lib               |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                           |
| Is contained                | false                                                |
| Is homebrew                 | false                                                |
| Is installed via Fabric.app | false                                                |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/          |
| Xcode Version               | 12.4                                                 |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(scheme: "Mobile Tool")
  end

  desc "Upload metadata to appstore"
  lane :metadata do
    upload_to_app_store(skip_binary_upload: true)
  end

  desc "Run test"
  lane :test do
    clear_derived_data
    xcclean(scheme: "Mobile Tool")
    scan(scheme: "Mobile Tool",
         output_types: "html,junit")
  end

  desc "Build release version"
  lane :build do
    get_certificates
    get_provisioning_profile
    clear_derived_data
    xcclean(scheme: "Mobile Tool")
    gym(configuration: "Release",
        scheme: "Mobile Tool",
        export_xcargs: "-allowProvisioningUpdates")
  end

  desc "Upload binary to appstore"
  lane :upload do
    get_certificates
    get_provisioning_profile
    clear_derived_data
    xcclean(scheme: "Mobile Tool")
    increment_build_number(xcodeproj: "./Mobile Tool/Mobile Tool.xcodeproj")
    gym(configuration: "Release",
        scheme: "Mobile Tool",
        export_xcargs: "-allowProvisioningUpdates")
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("de.broadcast-concept.mobiletool") # The bundle identifier of your app
apple_id("freelance@oliverdobner.de") # Your Apple email address

itc_team_id("626409") # App Store Connect Team ID
team_id("Q92EVX3VB6") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.178.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.3.0        |
| bundler                       | 2.2.14       |
| rake                          | 13.0.3       |
| CFPropertyList                | 3.0.3        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| artifactory                   | 3.0.15       |
| atomos                        | 0.1.3        |
| aws-eventstream               | 1.1.1        |
| aws-partitions                | 1.434.0      |
| aws-sigv4                     | 1.2.3        |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.113.0      |
| aws-sdk-kms                   | 1.43.0       |
| aws-sdk-s3                    | 1.91.0       |
| babosa                        | 1.0.4        |
| claide                        | 1.0.3        |
| colored                       | 1.2          |
| colored2                      | 3.1.2        |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| digest-crc                    | 0.6.3        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| dotenv                        | 2.7.6        |
| emoji_regex                   | 3.2.2        |
| excon                         | 0.79.0       |
| faraday-net_http              | 1.0.1        |
| multipart-post                | 2.0.0        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.3        |
| gh_inspector                  | 1.1.3        |
| jwt                           | 2.2.2        |
| memoist                       | 0.16.2       |
| multi_json                    | 1.15.0       |
| os                            | 1.1.1        |
| signet                        | 0.15.0       |
| googleauth                    | 0.16.0       |
| httpclient                    | 2.8.3        |
| mini_mime                     | 1.0.2        |
| uber                          | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| google-api-client             | 0.38.0       |
| rexml                         | 3.2.4        |
| webrick                       | 1.7.0        |
| google-apis-core              | 0.3.0        |
| google-apis-iamcredentials_v1 | 0.2.0        |
| google-apis-storage_v1        | 0.3.0        |
| google-cloud-env              | 1.5.0        |
| google-cloud-errors           | 1.1.0        |
| google-cloud-core             | 1.6.0        |
| google-cloud-storage          | 1.31.0       |
| json                          | 2.5.1        |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| plist                         | 3.6.0        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| simctl                        | 1.6.8        |
| slack-notifier                | 2.3.2        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| word_wrap                     | 1.0.0        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| xcpretty-travis-formatter     | 1.0.1        |
</details>

*generated on:* **2021-03-18**
</details>

**Comment by zardazare** [comment]
Confirmed! Similar setup and package versions, snapshot with newer version 2.179.0 does not contain all screenshots. (In particular, iPhone 12 Pro Max - screenshots are available inside screenshots folder, not when .html is loaded).

**Comment by zardazare** [comment]
👍

**Comment by OliverDobner** [comment]
Tried with current fastlane version .. solved.
