### ISSUE TITLE
gym hangs on xcrun

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1844]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/425716?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @contra - Imported from <a href='https://github.com/fastlane/gym/issues/143'>fastlane/gym#143</a>
        </td>
      </tr>
    </table>

![screen shot 2015-11-13 at 12 30 19 pm](https://cloud.githubusercontent.com/assets/425716/11156715/660f0544-8a02-11e5-9052-de2cf9933f69.png)

When gym runs xcrun, it never continues because the xcrun command never closes itself.

Running `xcrun xcodebuild -list -project './platforms/ios/Charmed.xcodeproj'` by hand shows this:

![screen shot 2015-11-13 at 12 31 55 pm](https://cloud.githubusercontent.com/assets/425716/11156741/90f5decc-8a02-11e5-957d-cafcf8af3c58.png)

It seems as if gym is expecting that xcrun will print the info then close, but in reality it is printing the info and staying open so gym never continues.

**Comment by amosrivera** [comment]
If it helps anything I just had the same issue and it turns out it had to do with my Fish terminal. I noticed you're using Fish as well and started suspecting. I rebooted my zsh setup and everything started working again. @contra

**Comment by TKBurner** [comment]
Hey @Ricowere, can you let me know if you are still seeing this. I'm going to close it out for the time being. Thanks!

**Comment by Ricowere** [comment]
@TKBurner No issues in any of our machines. 

Jenkins machine: Ruby 2.2.1, terminal app, bash.
My machine: Ruby 2.2.3, iTerm, oh my zsh.

Timeout set: 600ms

**Comment by TKBurner** [comment]
@Ricowere Awesome! Thanks so much for letting us know 👍
