### ISSUE TITLE
[Windows] Bundle fastlane cannot load such pty

### ISSUE THREAD

**Issue by EArminjon** [fastlane/fastlane#18447]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Would install fastlane on windows.

##### Command executed

In an admin Powershell :
```bash
choco install ruby -y
choco install msys2
gem install bundler
Create a ./Gemfile (doc)
bundle update
bundle install
```

##### Complete output when running fastlane, including the stack trace and command used

```bash
$> bundle exec fastlane

C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/fastlane_core-0.59.0/lib/fastlane_core/itunes_transporter.rb:1:in `require': cannot load such file -- pty (LoadError)
        from C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/fastlane_core-0.59.0/lib/fastlane_core/itunes_transporter.rb:1:in `<top (required)>'
        from C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/fastlane_core-0.59.0/lib/fastlane_core.rb:17:in `require'
        from C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/fastlane_core-0.59.0/lib/fastlane_core.rb:17:in `<top (required)>'
        from C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/fastlane-1.92.0/lib/fastlane.rb:1:in `require'
        from C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/fastlane-1.92.0/lib/fastlane.rb:1:in `<top (required)>'
        from C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/fastlane-1.92.0/lib/fastlane/cli_tools_distributor.rb:8:in `require'
        from C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/fastlane-1.92.0/lib/fastlane/cli_tools_distributor.rb:8:in `take_off'
        from C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/fastlane-1.92.0/bin/fastlane:5:in `<top (required)>'
        from C:/tools/ruby30/bin/fastlane:23:in `load'
        from C:/tools/ruby30/bin/fastlane:23:in `<main>'


```

### Environment

Cannot execute bundle exec fastlane env because of the error.
Windows 10 pro, last update 20H2

**Comment by EArminjon** [comment]
![image](https://user-images.githubusercontent.com/37028599/112333697-1c823380-8cbb-11eb-83f2-dedf116dab70.png)

Need help xD

**Comment by ainame** [comment]
<img width="1536" alt="Screenshot 2021-03-24 at 21 24 27" src="https://user-images.githubusercontent.com/748949/112385337-67b23b80-8ce7-11eb-99eb-4f759d2547a9.png">

https://docs.fastlane.tools/getting-started/ios/setup/

Unfortunately, this is a known issue. Your Ruby 3.0 picked up a very old version that wasn't restricted to Ruby version.
We've been working on Ruby 3.0 support but it won't be coming that soon.  #17931

**Comment by ainame** [comment]
Feel free to open another issue if you face any other "Windows" specific issue🙂
