### ISSUE TITLE
[gym] failing with "exportArchive: Reached end of file while looking for: Mach-O slice."

### ISSUE THREAD

**Issue by mickyzinho** [fastlane/fastlane#18441]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When running 'fastlane gym', archive succeeds but 'xcodebuild -exportArchive' fails with 'exportArchive: Reached end of file while looking for: Mach-O slice.'
Happens both locally and on CircleCI.

I read https://github.com/fastlane/fastlane/issues/17712 but this is related to react native, which we do not use here.
Also I cannot compare the Podfile.lock to a previous working version, as we're setting up fastlane for the first time for this project.

##### Command executed
`fastlane appstoreconnect` (leading to 'fastlane gym')

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
/usr/bin/xcrun /Users/<redacted>/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.178.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/tl/f3hy7tsj0571f5bvs20vfhb40000gn/T/gym_config20210323-99944-fgta6c.plist' -archivePath /Users/<redacted>/Library/Developer/Xcode/Archives/2021-03-23/IDAGIO-ios\ 2021-03-23\ 11.32.05.xcarchive -exportPath '/var/folders/tl/f3hy7tsj0571f5bvs20vfhb40000gn/T/gym_output20210323-99944-colk9o'
rbenv detected, removing env variables
rbenv: shell integration not enabled. Run `rbenv init' for instructions.
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/tl/f3hy7tsj0571f5bvs20vfhb40000gn/T/gym_config20210323-99944-fgta6c.plist -archivePath '/Users/<redacted>/Library/Developer/Xcode/Archives/2021-03-23/<redacted> 2021-03-23 11.32.05.xcarchive' -exportPath /var/folders/tl/f3hy7tsj0571f5bvs20vfhb40000gn/T/gym_output20210323-99944-colk9o
2021-03-23 11:40:45.265 xcodebuild[4082:2357635] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/tl/f3hy7tsj0571f5bvs20vfhb40000gn/T/App Production_2021-03-23_11-40-45.263.xcdistributionlogs'.
error: exportArchive: Reached end of file while looking for: Mach-O slice.

Error Domain=DVTMachOErrorDomain Code=1 "Reached end of file while looking for: Mach-O slice." UserInfo={NSLocalizedDescription=Reached end of file while looking for: Mach-O slice., NSLocalizedRecoverySuggestion=}

** EXPORT FAILED **
[11:40:48]: Exit status: 70
 </pre>
</details>

### Environment

<details>
  <pre><details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.0.1                                      |
| Ruby                        | 2.7.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0                          |
| Installation Source         | ~/.rbenv/versions/2.7.2/bin/fastlane        |
| Host                        | macOS 11.0.1 (20B50)                        |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.2/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1j  16 Feb 2021                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.4                                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do
    setup_circle_ci
  end

  desc "Fetch provisioning profiles"
  lane :certs do
    match(app_identifier: "com.<redacted>", type: "development", readonly: is_ci)
    match(app_identifier: "com.<redacted>.staging", type: "development", readonly: is_ci)
    match(app_identifier: "com.<redacted>.storeapp", type: "appstore", readonly: is_ci)
    match(app_identifier: "com.<redacted>.staging", type: "appstore", readonly: is_ci)
  end

  desc "Run Swiftlint"
  lane :lint do
    swiftlint(raise_if_swiftlint_error: is_ci, config_file: ".swiftlint-ci.yml", executable: './Pods/SwiftLint/swiftlint')
  end  

  desc "Run unit tests"
  lane :test do
    scan
  end

  desc "Run UI tests"
  lane :ui_test do
    scan(scheme: "AppUITests")
  end

  desc "Push a new production beta build to TestFlight"
  lane :appstoreconnect do
    gym(
       workspace: '<redacted>.xcworkspace',
       scheme: 'App Production',
       configuration: 'Release Production',
       clean: true,
       output_directory: 'archives',
       output_name: '<redacted>-ios.ipa',
       export_method: 'app-store'
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.178.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.4.0        |
| slack-notifier                | 2.3.2        |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| plist                         | 3.6.0        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| multipart-post                | 2.0.0        |
| word_wrap                     | 1.0.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| artifactory                   | 3.0.15       |
| babosa                        | 1.0.4        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| excon                         | 0.79.0       |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.3        |
| gh_inspector                  | 1.1.3        |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| xcpretty-travis-formatter     | 1.0.1        |
| dotenv                        | 2.7.6        |
| simctl                        | 1.6.8        |
| jwt                           | 2.2.2        |
| uber                          | 0.1.0        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| mini_mime                     | 1.0.2        |
| multi_json                    | 1.15.0       |
| signet                        | 0.15.0       |
| memoist                       | 0.16.2       |
| os                            | 1.1.1        |
| googleauth                    | 0.16.0       |
| httpclient                    | 2.8.3        |
| google-api-client             | 0.38.0       |
| google-cloud-env              | 1.5.0        |
| google-cloud-errors           | 1.1.0        |
| google-cloud-core             | 1.6.0        |
| google-apis-core              | 0.3.0        |
| google-apis-iamcredentials_v1 | 0.2.0        |
| google-apis-storage_v1        | 0.3.0        |
| digest-crc                    | 0.6.3        |
| google-cloud-storage          | 1.31.0       |
| emoji_regex                   | 3.2.2        |
| jmespath                      | 1.4.0        |
| aws-partitions                | 1.433.0      |
| aws-eventstream               | 1.1.1        |
| aws-sigv4                     | 1.2.3        |
| aws-sdk-core                  | 3.113.0      |
| aws-sdk-kms                   | 1.43.0       |
| aws-sdk-s3                    | 1.91.0       |
| uri                           | 0.10.0       |
| nanaimo                       | 0.3.0        |
| colored2                      | 3.1.2        |
| claide                        | 1.0.3        |
| CFPropertyList                | 3.0.3        |
| atomos                        | 0.1.3        |
| xcodeproj                     | 1.19.0       |
| ruby2_keywords                | 0.0.4        |
| faraday-net_http              | 1.0.1        |
| faraday                       | 1.3.0        |
| json                          | 2.5.1        |
| bundler                       | 2.2.14       |
| rexml                         | 3.2.4        |
| webrick                       | 1.7.0        |
| rake                          | 13.0.1       |
| forwardable                   | 1.3.1        |
| logger                        | 1.4.2        |
| cgi                           | 0.1.0        |
| date                          | 3.0.0        |
| timeout                       | 0.1.0        |
| stringio                      | 0.1.0        |
| zlib                          | 1.1.0        |
| ipaddr                        | 1.2.2        |
| openssl                       | 2.1.2        |
| ostruct                       | 0.2.0        |
| strscan                       | 1.0.3        |
| delegate                      | 0.1.0        |
| fileutils                     | 1.4.1        |
| io-console                    | 0.5.6        |
| open3                         | 0.1.0        |
| singleton                     | 0.1.0        |
| yaml                          | 0.1.0        |
| psych                         | 3.1.0        |
| mutex_m                       | 0.1.0        |
</details>

*generated on:* **2021-03-23**
</details></pre>
</details>

**Comment by IDAGIODeploy** [comment]
It turned out to be a internal issue with the project files. This can be closed.

**Comment by mickyzinho** [comment]
Turned out to be an internal issue with malformed library files. Closing.
