### ISSUE TITLE
Upload_to_play_store is succesful but AAB does not appear in Google Play library

### ISSUE THREAD

**Issue by zilppuri** [fastlane/fastlane#18451]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
upload_to_play_store is succesful but AAB does not appear in Google Play library.
Manually uploading the same AAB works. There are no pending releases in any tracks in Google Play.

##### Command executed
  <pre> 
  lane :release do
    gradle(
        flavor: "pilotRelease",
        task: "bundle"
    )
    upload_to_play_store(
            skip_upload_apk: true,
           skip_upload_metadata: true,
          skip_upload_images: true,
          skip_upload_screenshots: true,
          validate_only: true,
          skip_upload_changelogs: true,
          track_promote_to: "beta",
          track: "beta"
    )
  end
</pre>

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
bundle exec fastlane release
[✔] 🚀
+-------------------------------------------+---------+-----------------------------------------------------------+
|                                                  Used plugins                                                   |
+-------------------------------------------+---------+-----------------------------------------------------------+
| Plugin                                    | Version | Action                                                    |
+-------------------------------------------+---------+-----------------------------------------------------------+
| fastlane-plugin-firebase_app_distribution | 0.2.3   | firebase_app_distribution_login firebase_app_distribution |
+-------------------------------------------+---------+-----------------------------------------------------------+

[12:13:53]: ------------------------------
[12:13:53]: --- Step: default_platform ---
[12:13:53]: ------------------------------
[12:13:53]: Driving the lane 'android release' 🚀
[12:13:53]: --------------------------------
[12:13:53]: --- Step: bundlepilotRelease ---
[12:13:53]: --------------------------------

~~~~~~~~

[12:13:55]: ▸ BUILD SUCCESSFUL in 1s
[12:13:55]: ▸ 36 actionable tasks: 2 executed, 34 up-to-date
[12:13:56]: ----------------------------------
[12:13:56]: --- Step: upload_to_play_store ---
[12:13:56]: ----------------------------------

+---------------------------------+---------------------------------------------------------------------------------------------------------+
|                                                        Summary for supply 2.178.0                                                         |
+---------------------------------+---------------------------------------------------------------------------------------------------------+
| skip_upload_apk                 | true                                                                                                    |
| skip_upload_metadata            | true                                                                                                    |
| skip_upload_images              | true                                                                                                    |
| skip_upload_screenshots         | true                                                                                                    |
| validate_only                   | true                                                                                                    |
| skip_upload_changelogs          | true                                                                                                    |
| track_promote_to                | beta                                                                                                    |
| track                           | beta                                                                                                    |
| apk_paths                       | [~~~/release/app-beta-release.apk  |
|                                 | ", "~~~debug/app-beta-debug.apk",  |
|                                 | "~~~/app/build/outputs/apk/pilot/release/app-pilot-release.ap  |
|                                 | k",                                                                                                     |
|                                 | "~~~/app-pilot-debug.apk"]   |
| aab                             |~~~/app/build/outputs/bundle/pilotRelease/app-pilot-release.a  |
|                                 | ab                                                                                                      |
| package_name                    | com.fira.onsite                                                                                         |
| release_status                  | completed                                                                                               |
| metadata_path                   | ./fastlane/metadata/android                                                                             |
| json_key                        | ~~~.json                                                                      |
| skip_upload_aab                 | false                                                                                                   |
| check_superseded_tracks         | false                                                                                                   |
| timeout                         | 300                                                                                                     |
| deactivate_on_promote           | true                                                                                                    |
| ack_bundle_installation_warning | false                                                                                                   |
+---------------------------------+---------------------------------------------------------------------------------------------------------+

[12:13:57]: Preparing aab at path '~~~/app/build/outputs/bundle/pilotRelease/app-pilot-release.aab' for upload...
[12:14:36]: Updating track 'beta'...
[12:14:37]: Validating all changes with Google Play...
[12:14:40]: Successfully validated the upload to Google Play

+------+----------------------+-------------+
|             fastlane summary              |
+------+----------------------+-------------+
| Step | Action               | Time (in s) |
+------+----------------------+-------------+
| 1    | default_platform     | 0           |
| 2    | bundlepilotRelease   | 3           |
| 3    | upload_to_play_store | 43          |
+------+----------------------+-------------+

</pre>
</details>

### Environment

<!-- 
Please run `fastlane env` and copy the output below. This will help us help you.
If you used the `--capture_output` option, please remove this block as it is already included there. 
-->

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by wormoworm** [comment]
I'm seeing the same issue, `upload_to_play_store()` reports success, but no AAB is visible in the Play Store dashboard. Running on Azure DevOps Pipelines, MacOS 10.14.

Here is the output of `fastlane env`:

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                              |
| --------------------------- | -------------------------------------------------- |
| OS                          | 10.14.6                                            |
| Ruby                        | 2.7.2                                              |
| Bundler?                    | true                                               |
| Git                         | git version 2.31.1                                 |
| Installation Source         | /usr/local/lib/ruby/gems/2.7.0/bin/fastlane        |
| Host                        | Mac OS X 10.14.6 (18G8022)                         |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.7/2.7.2/lib               |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                         |
| Is contained                | false                                              |
| Is homebrew                 | false                                              |
| Is installed via Fabric.app | false                                              |
| Xcode Path                  | /Applications/Xcode_11.3.1.app/Contents/Developer/ |
| Xcode Version               | 11.3.1                                             |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools

opt_out_usage

default_platform(:android)

platform :android do

  desc "Run UI tests"
  lane :app_ui_test do
    gradle(
      task: "app:connectedAndroidTest"
    )
  end

  desc "Publish app"
  lane :app_build_test_publish do
    puts "Patch version for this build will be " + ENV["BUILD_NUMBER"]
    gradle(
      task: "app:assembleRelease",
      properties: {
        "versionPatch" => ENV["BUILD_NUMBER"],
        "android.injected.signing.store.file" => ***,
        "android.injected.signing.store.password" => ***,
        "android.injected.signing.key.alias" => ***,
        "android.injected.signing.key.password" => ***
      }
    )
    puts "Mapping file exists: "+(mapping_file_exists() ?  "true" : "false")
    if is_ci?
      upload_to_play_store(
        track: "internal",
        aab: Actions.lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH],
        skip_upload_apk: true,
        json_key_data: ENV["PLAY_STORE_SERVICE_ACCOUNT_JSON"],
        mapping: mapping_file_exists() ? Actions.lane_context[SharedValues::GRADLE_MAPPING_TXT_OUTPUT_PATH] : nil
      )
    end
  end

  def get_app_version_name()
    return android_get_version_name
  end

  def mapping_file_exists()
      return Actions.lane_context[SharedValues::GRADLE_MAPPING_TXT_OUTPUT_PATH] != nil && File.file?(Actions.lane_context[SharedValues::GRADLE_MAPPING_TXT_OUTPUT_PATH])
    end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file(ENV["PLAY_STORE_CREDENTIALS_PATH"])
package_name(ENV["APP_PACKAGE_NAME"])
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.180.1 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                             | Version | Update-Status |
| ---------------------------------- | ------- | ------------- |
| fastlane-plugin-appcenter          | 1.11.0  | ✅ Up-To-Date  |
| fastlane-plugin-versioning_android | 0.1.0   | ✅ Up-To-Date  |
| fastlane-plugin-android_emulator   | 1.1.1   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                                | Version      |
| ---------------------------------- | ------------ |
| did_you_mean                       | 1.4.0        |
| bundler                            | 2.2.15       |
| uri                                | 0.10.0       |
| rake                               | 13.0.3       |
| CFPropertyList                     | 3.0.3        |
| public_suffix                      | 4.0.6        |
| addressable                        | 2.7.0        |
| artifactory                        | 3.0.15       |
| atomos                             | 0.1.3        |
| aws-eventstream                    | 1.1.1        |
| aws-partitions                     | 1.443.0      |
| aws-sigv4                          | 1.2.3        |
| jmespath                           | 1.4.0        |
| aws-sdk-core                       | 3.113.1      |
| aws-sdk-kms                        | 1.43.0       |
| aws-sdk-s3                         | 1.93.0       |
| babosa                             | 1.0.4        |
| claide                             | 1.0.3        |
| colored                            | 1.2          |
| colored2                           | 3.1.2        |
| highline                           | 1.7.10       |
| commander-fastlane                 | 4.4.6        |
| declarative                        | 0.0.20       |
| declarative-option                 | 0.1.0        |
| digest-crc                         | 0.6.3        |
| unf_ext                            | 0.0.7.7      |
| unf                                | 0.1.4        |
| domain_name                        | 0.5.20190701 |
| dotenv                             | 2.7.6        |
| emoji_regex                        | 3.2.2        |
| excon                              | 0.79.0       |
| faraday-net_http                   | 1.0.1        |
| multipart-post                     | 2.0.0        |
| ruby2_keywords                     | 0.0.4        |
| faraday                            | 1.3.0        |
| http-cookie                        | 1.0.3        |
| faraday-cookie_jar                 | 0.0.7        |
| faraday_middleware                 | 1.0.0        |
| fastimage                          | 2.2.3        |
| gh_inspector                       | 1.1.3        |
| jwt                                | 2.2.2        |
| memoist                            | 0.16.2       |
| multi_json                         | 1.15.0       |
| os                                 | 1.1.1        |
| signet                             | 0.15.0       |
| googleauth                         | 0.16.1       |
| httpclient                         | 2.8.3        |
| mini_mime                          | 1.1.0        |
| uber                               | 0.1.0        |
| representable                      | 3.0.4        |
| retriable                          | 3.1.2        |
| google-api-client                  | 0.38.0       |
| rexml                              | 3.2.5        |
| webrick                            | 1.7.0        |
| google-apis-core                   | 0.3.0        |
| google-apis-iamcredentials_v1      | 0.3.0        |
| google-apis-storage_v1             | 0.3.0        |
| google-cloud-env                   | 1.5.0        |
| google-cloud-errors                | 1.1.0        |
| google-cloud-core                  | 1.6.0        |
| google-cloud-storage               | 1.31.0       |
| json                               | 2.5.1        |
| mini_magick                        | 4.11.0       |
| naturally                          | 2.2.1        |
| plist                              | 3.6.0        |
| rubyzip                            | 2.3.0        |
| security                           | 0.1.3        |
| simctl                             | 1.6.8        |
| slack-notifier                     | 2.3.2        |
| terminal-notifier                  | 2.0.0        |
| unicode-display_width              | 1.7.0        |
| terminal-table                     | 1.8.0        |
| tty-screen                         | 0.8.1        |
| tty-cursor                         | 0.7.1        |
| tty-spinner                        | 0.9.3        |
| word_wrap                          | 1.0.0        |
| nanaimo                            | 0.3.0        |
| xcodeproj                          | 1.19.0       |
| rouge                              | 2.0.7        |
| xcpretty                           | 0.3.0        |
| xcpretty-travis-formatter          | 1.0.1        |
| fastlane-plugin-android_emulator   | 1.1.1        |
| fastlane-plugin-appcenter          | 1.11.0       |
| fastlane-plugin-versioning_android | 0.1.0        |
</details>

**Comment by wormoworm** [comment]
As usual, just after I posted, I solved my issue :)

I was running `app:assembleRelease`, which generates an **APK**, not an **AAB**. Changing to `app:bundleRelease` has fixed the issue and now I see my AAB in the Play Store dashboard.

For reference, my publish lane now looks like this:
```ruby
desc "Publish app"
  lane :app_build_test_publish do
    puts "Patch version for this build will be " + ENV["BUILD_NUMBER"]
    gradle(
      task: "app:bundleRelease",
      properties: {
        "versionPatch" => ENV["BUILD_NUMBER"],
        "android.injected.signing.store.file" => ENV["ANDROID_KEYSTORE_PATH"],
        "android.injected.signing.store.password" => ENV["ANDROID_KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["ANDROID_KEYSTORE_HELSINKI_ALIAS"],
        "android.injected.signing.key.password" => ENV["ANDROID_KEYSTORE_HELSINKI_PASSWORD"]
      }
    )
    puts "Mapping file exists: "+(mapping_file_exists() ?  "true" : "false")
    if is_ci?
      upload_to_play_store(
        track: "internal",
        aab: Actions.lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH],
        skip_upload_apk: true,
        json_key_data: ENV["PLAY_STORE_SERVICE_ACCOUNT_JSON"],
        mapping: mapping_file_exists() ? Actions.lane_context[SharedValues::GRADLE_MAPPING_TXT_OUTPUT_PATH] : nil
      )
    end
  end
```

In summary, it was a PICNIC error, but I'm not sure how / why `supply` reported the upload a success, since there was no AAB generated.

Hope this helps @zilppuri
