### ISSUE TITLE
FastLane only runs the default TestPlan

### ISSUE THREAD

**Issue by sbogart19** [fastlane/fastlane#18453]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When attempting to run a non-default TestPlan, it always chooses the default TestPlan instead of the one specified in the lane.

In XCode, I have a scheme (tvOS-UITests) that has 2 test plans associated with it (tvOS-Functional, tvOS-Backend).  In my fastfile, I have something similar to this:

```
lane :tvos_ui_tests do |options|
  output_directory = "./artifacts/tvos_ui_tests"

  scan(
    scheme: "tvOS-UITests",
    output_directory: output_directory,
    output_style: "standard",
    output_types: "html,junit",
    buildlog_path: output_directory,
    disable_concurrent_testing: true,
    testplan: options["tvOS-Functional"],
    result_bundle: true
  )
end

lane :tvos_ui_new_backend do |options|
  output_directory = "./artifacts/tvos_ui_tests"

  scan(
    scheme: "tvOS-UITests",
    output_directory: output_directory,
    output_style: "standard",
    output_types: "html,junit",
    buildlog_path: output_directory,
    disable_concurrent_testing: true,
    testplan: options["tvOS-Backend"],
    result_bundle: true
  )
end
```

- When the `tvOS-Functional` testplan is set as default in the scheme, it is run regardless which of the below two commands are executed.
- Likewise, when the `tvOS-Backend` testplan is set as default in the scheme, its run regardless of command.

It may be important to note that when initially setting up the testplans, I wasn't able to get it to work without using options[].

##### Command executed
```bundle exec fastlane tvos_ui_new_backend``` 
```bundle exec fastlane tvos_ui_tests```

### Captured Output

Command Used: `tvos_ui_new_backend --capture_output`
<details><summary>Output/Log</summary>

```

DEBUG [2021-03-25 16:51:00.55]: Checking if there are any plugins that should be loaded...
DEBUG [2021-03-25 16:51:00.55]: Loading 'fastlane-plugin-appcenter' plugin
INFO [2021-03-25 16:51:00.55]: gem 'fastlane-plugin-appcenter' is already installed
DEBUG [2021-03-25 16:51:00.58]: Loading 'fastlane-plugin-appcenter' plugin
INFO [2021-03-25 16:51:00.58]: gem 'fastlane-plugin-appcenter' is already installed
WARN [2021-03-25 16:51:00.58]: Plugin 'Appcenter' overwrites already loaded action 'appcenter_fetch_version_number'
WARN [2021-03-25 16:51:00.58]: Plugin 'Appcenter' overwrites already loaded action 'appcenter_fetch_devices'
WARN [2021-03-25 16:51:00.58]: Plugin 'Appcenter' overwrites already loaded action 'appcenter_upload'
DEBUG [2021-03-25 16:51:00.58]: Loading 'fastlane-plugin-test_center' plugin
INFO [2021-03-25 16:51:00.58]: gem 'fastlane-plugin-test_center' is already installed


```

</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.7                                     |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.30.0                          |
| Installation Source         | ~/.rvm/gems/ruby-2.6.3/bin/fastlane         |
| Host                        | Mac OS X 10.15.7 (19H524)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.3/lib                |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.4                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.165.0"
default_platform :ios

# Setup build environment
before_all do
  $root_dir = File.expand_path(File.join(File.dirname(__FILE__), ".."))
end

# Shared build lane
desc "Build a given configuration."
# scheme: Xcode scheme name
# configuration: Xcode configuration name
# output_directory: Path to the build product destination
# buildlog_path: Path to the build log destination
# export_method: The export method required - ad-hoc, app-store, enterprise
private_lane :build do |options|
  # Set build number
  increment_build_number(
    build_number: ENV['BUILD_NUMBER'],
    xcodeproj: "Project.xcodeproj"
  )

  gym(
    scheme: options[:scheme],
    configuration: options[:configuration],
    clean: true,
    output_directory: options[:output_directory],
    buildlog_path: options[:buildlog_path],
    archive_path: options[:archive_path],
    export_options: {
      method: options[:export_method],
      compileBitcode: options[:bitcode],
      teamID: options[:teamID],
      provisioningProfiles: options[:provisioningProfiles]
    }
  )
end

# Setup the Signing Keychain
desc "Install build certificates and provisioning profiles."
lane :install_signing do |options|
  # Clean up old keychain if it exists
  begin
    uninstall_signing
  rescue
    puts "ios-build keychain doesn't exist!"
  end

  # Setup build keychain & add certificates
  puts "Creating ios-build keychain..."
  create_keychain(
    name: "ios-build",
    password: "ios-build",
    default_keychain: false,
    unlock: true,
    timeout: 3600,
    lock_when_sleeps: false
  )

  puts "Importing certificate..."
  import_certificate(
    keychain_name: "ios-build",
    keychain_password: "ios-build",
    certificate_path: ".cert.p12",
    certificate_password: ENV['PASSWORD']
  )

  puts "Importing adhoc1 certificate..."
  import_certificate(
    keychain_name: "ios-build",
    keychain_password: "ios-build",
    certificate_path: "cert.p12",
    certificate_password: ENV['PASSWORD']
  )

  puts "Importing adhoc2 certificate..."
  import_certificate(
    keychain_name: "ios-build",
    keychain_password: "ios-build",
    certificate_path: "cert.p12",
    certificate_password: ''
  )

  # Sync Provisioning Profiles
  $system_provisioning_path = File.expand_path("~/Library/MobileDevice/Provisioning Profiles")
  sh(%|mkdir -p "#{$system_provisioning_path}"|)
  sh(%|rsync -av "#{$root_dir}/profiles/" "#{$system_provisioning_path}"|)
end

desc "Remove build certificates. Always do this, even if the build fails."
lane :uninstall_signing do |options|
  # Set the login.keychain back to default
  sh(%{
    security default-keychain -s login.keychain || :
    security list-keychains -d user -s ~/Library/Keychains/login.keychain
  })

  delete_keychain(name: "ios-build")
end


# Run Tests
lane :unit_tests do
  ios_tests
  tvos_tests
end

lane :ios_tests do
  output_directory = "./artifacts/ios_tests"

  scan(
    scheme: "iOS",
    output_directory: output_directory,
    output_style: "standard",
    output_types: "html,junit",
    buildlog_path: output_directory,
    disable_concurrent_testing: true
  )
end

lane :tvos_tests do
  output_directory = "./artifacts/tvos_tests"

  scan(
    scheme: "tvOS",
    output_directory: output_directory,
    output_style: "standard",
    output_types: "html,junit",
    buildlog_path: output_directory,
    disable_concurrent_testing: true
  )
end

# Run UI Tests
lane :ui_tests do
  ios_ui_tests
  tvos_ui_tests
end

lane :ios_ui_tests do |options|
  output_directory = "./artifacts/ios_ui_tests"

  scan(
    scheme: "iOS-UITests",
    device: "iPhone 8 Plus",
    output_directory: output_directory,
    output_style: "standard",
    output_types: "html,junit",
    buildlog_path: output_directory,
    derived_data_path: "./build/TestDD-iPhone",
    testplan: options["iOS-Functional"],
    disable_concurrent_testing: true,
    result_bundle: true,
  )
end

lane :tvos_ui_tests do |options|
  output_directory = "./artifacts/tvos_ui_tests"

  scan(
    scheme: "tvOS-UITests",
    output_directory: output_directory,
    output_style: "standard",
    output_types: "html,junit",
    buildlog_path: output_directory,
    derived_data_path: "./build/TestDD-iPhone",
    disable_concurrent_testing: true,
    testplan: options["tvOS-Functional"],
    result_bundle: true
  )
end

lane :tvos_ui_new_backend do |options|
  output_directory = "./artifacts/tvos_ui_tests"

  scan(
    scheme: "tvOS-UITests",
    output_directory: output_directory,
    output_style: "standard",
    output_types: "html,junit",
    buildlog_path: output_directory,
    derived_data_path: "./build/TestDD-iPhone",
    disable_concurrent_testing: true,
    testplan: options["tvOS-Backend"],
    result_bundle: true
  )
end

# Simulator Builds

def self.parse_default_environment(options)
  if options[:default_environment] == "INTEG"
    return "QA_AUTOMATION_BUILD_INTEG"
  elsif options[:default_environment] == "PREPROD"
    return "QA_AUTOMATION_BUILD_PREPROD"
  else
    return "QA_AUTOMATION_BUILD"
  end
end

desc "Build the Debug configuration (iOS Simulator). Use option 'default_environment:(INTEG|PREPROD)' to specify default Environment"
lane :simulator_debug_ios do |options|
  output_directory = "#{$root_dir}/artifacts/project-ios-simulator"
  derived_data_path = "#{$root_dir}/tmp/DerivedData"

  automation_environment = parse_default_environment(options)

  generate_simulator_build(
      workspace: "#{$root_dir}/iOS.xcworkspace",
      scheme: 'iOS',
      configuration: 'Debug',
      destination: 'platform=iOS Simulator,name=iPhone 8,OS=14.4',
      derived_data_path: derived_data_path,
      output_directory: output_directory,
      automation_environment: automation_environment
    )
end

desc "Build the Debug configuration (tvOS Simulator). Use option 'default_environment:(INTEG|PREPROD)' to specify Environment"
lane :simulator_debug_tvos do |options|
  output_directory = "#{$root_dir}/artifacts/tvos-simulator"
  derived_data_path = "#{$root_dir}/tmp/DerivedData"

  automation_environment = parse_default_environment(options)

  generate_simulator_build(
      workspace: "#{$root_dir}/project.xcworkspace",
      scheme: 'tvOS',
      configuration: 'Debug',
      destination: 'platform=tvOS Simulator,name=Apple TV,OS=latest',
      derived_data_path: derived_data_path,
      output_directory: output_directory,
      automation_environment: automation_environment
    )
end

desc "Generates simulator build"
private_lane :generate_simulator_build do |options|
 workspace_dir = options[:workspace]
 scheme = options[:scheme]
 configuration = options[:configuration]
 destination = options[:destination]
 output_directory = options[:output_directory]
 derived_data_path = options[:derived_data_path]
 automation_environment = options[:automation_environment]

 xcbuild(
  workspace: workspace_dir,
  scheme: scheme,
  destination: destination,
  derivedDataPath: derived_data_path,
  xcargs: "-configuration #{configuration} GCC_PREPROCESSOR_DEFINITIONS='$GCC_PREPROCESSOR_DEFINITIONS #{automation_environment}'"
  )

 app_location = find_app_file(derived_data_path)

 begin
   FileUtils.remove_dir(output_directory, force = true)
   FileUtils.mkdir_p output_directory
   FileUtils.mv(app_location, output_directory)
 rescue
   # in case it already exists
 end
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.178.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                      | Version | Update-Status      |
| --------------------------- | ------- | ------------------ |
| fastlane-plugin-appcenter   | 1.8.0   | 🚫 Update available |
| fastlane-plugin-appcenter   | 1.8.0   | 🚫 Update available |
| fastlane-plugin-test_center | 3.9.0   | 🚫 Update available |

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.3.0        |
| bundler                       | 1.17.3       |
| etc                           | 1.0.1        |
| forwardable                   | 1.2.0        |
| rake                          | 13.0.3       |
| CFPropertyList                | 3.0.3        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| artifactory                   | 3.0.15       |
| atomos                        | 0.1.3        |
| aws-eventstream               | 1.1.1        |
| aws-partitions                | 1.435.0      |
| aws-sigv4                     | 1.2.3        |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.113.0      |
| aws-sdk-kms                   | 1.43.0       |
| aws-sdk-s3                    | 1.93.0       |
| babosa                        | 1.0.4        |
| claide                        | 1.0.3        |
| colored                       | 1.2          |
| colored2                      | 3.1.2        |
| colorize                      | 0.8.1        |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| digest-crc                    | 0.6.3        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| dotenv                        | 2.7.6        |
| emoji_regex                   | 3.2.2        |
| excon                         | 0.79.0       |
| faraday-net_http              | 1.0.1        |
| multipart-post                | 2.0.0        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.3        |
| gh_inspector                  | 1.1.3        |
| jwt                           | 2.2.2        |
| memoist                       | 0.16.2       |
| multi_json                    | 1.15.0       |
| os                            | 1.1.1        |
| signet                        | 0.15.0       |
| googleauth                    | 0.16.0       |
| httpclient                    | 2.8.3        |
| mini_mime                     | 1.0.2        |
| uber                          | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| google-api-client             | 0.38.0       |
| rexml                         | 3.2.4        |
| webrick                       | 1.7.0        |
| google-apis-core              | 0.3.0        |
| google-apis-iamcredentials_v1 | 0.2.0        |
| google-apis-storage_v1        | 0.3.0        |
| google-cloud-env              | 1.5.0        |
| google-cloud-errors           | 1.1.0        |
| google-cloud-core             | 1.6.0        |
| google-cloud-storage          | 1.31.0       |
| json                          | 2.5.1        |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| plist                         | 3.6.0        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| simctl                        | 1.6.8        |
| slack-notifier                | 2.3.2        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| word_wrap                     | 1.0.0        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| xcpretty-travis-formatter     | 1.0.1        |
| fastlane-plugin-appcenter     | 1.8.0        |
| xctest_list                   | 1.1.8        |
| fastlane-plugin-test_center   | 3.9.0        |
</details>

*generated on:* **2021-03-25**
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.7                                     |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.30.0                          |
| Installation Source         | ~/.rvm/gems/ruby-2.6.3/bin/fastlane         |
| Host                        | Mac OS X 10.15.7 (19H524)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.3/lib                |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.4                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.165.0"
default_platform :ios


# Setup build environment
before_all do
  $root_dir = File.expand_path(File.join(File.dirname(__FILE__), ".."))
end

# Shared build lane
desc "Build a given configuration."
# scheme: Xcode scheme name
# configuration: Xcode configuration name
# output_directory: Path to the build product destination
# buildlog_path: Path to the build log destination
# export_method: The export method required - ad-hoc, app-store, enterprise
private_lane :build do |options|
  # Set build number
  increment_build_number(
    build_number: ENV['BUILD_NUMBER'],
    xcodeproj: "Project.xcodeproj"
  )

  gym(
    scheme: options[:scheme],
    configuration: options[:configuration],
    clean: true,
    output_directory: options[:output_directory],
    buildlog_path: options[:buildlog_path],
    archive_path: options[:archive_path],
    export_options: {
      method: options[:export_method],
      compileBitcode: options[:bitcode],
      teamID: options[:teamID],
      provisioningProfiles: options[:provisioningProfiles]
    }
  )
end


# Run Tests
lane :tests do
  ios_tests
  tvos_tests
end

lane :ios_tests do
  output_directory = "./artifacts/ios_tests"

  scan(
    scheme: "iOS",
    output_directory: output_directory,
    output_style: "standard",
    output_types: "html,junit",
    buildlog_path: output_directory,
    disable_concurrent_testing: true
  )
end

lane :tvos_tests do
  output_directory = "./artifacts/tvos_tests"

  scan(
    scheme: "tvOS",
    output_directory: output_directory,
    output_style: "standard",
    output_types: "html,junit",
    buildlog_path: output_directory,
    disable_concurrent_testing: true
  )
end

# Run UI Tests
lane :ui_tests do
  ios_ui_tests
  tvos_ui_tests
end

lane :ios_ui_tests do |options|
  output_directory = "./artifacts/ios_ui_tests"

  scan(
    scheme: "iOS-UITests",
    device: "iPhone 8 Plus",
    output_directory: output_directory,
    output_style: "standard",
    output_types: "html,junit",
    buildlog_path: output_directory,
    derived_data_path: "./build/TestDD-iPhone",
    testplan: options["iOS-Functional"],
    disable_concurrent_testing: true,
    result_bundle: true,
  )
end

lane :tvos_ui_tests do |options|
  output_directory = "./artifacts/tvos_ui_tests"

  scan(
    scheme: "tvOS-UITests",
    output_directory: output_directory,
    output_style: "standard",
    output_types: "html,junit",
    buildlog_path: output_directory,
    derived_data_path: "./build/TestDD-iPhone",
    disable_concurrent_testing: true,
    testplan: options["tvOS-Functional"],
    result_bundle: true
  )
end

lane :tvos_ui_new_backend do |options|
  output_directory = "./artifacts/tvos_ui_tests"

  scan(
    scheme: "tvOS-UITests",
    output_directory: output_directory,
    output_style: "standard",
    output_types: "html,junit",
    buildlog_path: output_directory,
    derived_data_path: "./build/TestDD-iPhone",
    disable_concurrent_testing: true,
    testplan: options["tvOS-Backend"],
    result_bundle: true
  )
end


# Debug configurations - Used to create the debug build for automation

lane :debug do
  output_directory = "./artifacts/debug"

  build(
    scheme: "Debug",
    configuration: "Debug",
    output_directory: output_directory,
    buildlog_path: output_directory,
    export_method: "development",
    bitcode: false,
    teamID: "xx",
    provisioningProfiles: {xx}
  )
end

# Simulator Builds

def self.parse_default_environment(options)
  if options[:default_environment] == "INTEG"
    return "QA_AUTOMATION_BUILD_INTEG"
  elsif options[:default_environment] == "PREPROD"
    return "QA_AUTOMATION_BUILD_PREPROD"
  else
    return "QA_AUTOMATION_BUILD"
  end
end

desc "Build the Debug configuration (iOS Simulator). Use option 'default_environment:(INTEG|PREPROD)' to specify default Environment"
lane :simulator_debug_ios do |options|
  output_directory = "#{$root_dir}/artifacts/ios-simulator"
  derived_data_path = "#{$root_dir}/tmp/DerivedData"

  automation_environment = parse_default_environment(options)

  generate_simulator_build(
      workspace: "#{$root_dir}/project.xcworkspace",
      scheme: 'ios',
      configuration: 'Debug',
      destination: 'platform=iOS Simulator,name=iPhone 8,OS=14.4',
      derived_data_path: derived_data_path,
      output_directory: output_directory,
      automation_environment: automation_environment
    )
end

desc "Build the Debug configuration (tvOS Simulator). Use option 'default_environment:(INTEG|PREPROD)' to specify Environment"
lane :simulator_debug_tvos do |options|
  output_directory = "#{$root_dir}/artifacts/tvos-simulator"
  derived_data_path = "#{$root_dir}/tmp/DerivedData"

  automation_environment = parse_default_environment(options)

  generate_simulator_build(
      workspace: "#{$root_dir}/project.xcworkspace",
      scheme: 'tvOS',
      configuration: 'Debug',
      destination: 'platform=tvOS Simulator,name=Apple TV,OS=latest',
      derived_data_path: derived_data_path,
      output_directory: output_directory,
      automation_environment: automation_environment
    )
end

desc "Generates simulator build"
private_lane :generate_simulator_build do |options|
 workspace_dir = options[:workspace]
 scheme = options[:scheme]
 configuration = options[:configuration]
 destination = options[:destination]
 output_directory = options[:output_directory]
 derived_data_path = options[:derived_data_path]
 automation_environment = options[:automation_environment]

 xcbuild(
  workspace: workspace_dir,
  scheme: scheme,
  destination: destination,
  derivedDataPath: derived_data_path,
  xcargs: "-configuration #{configuration} GCC_PREPROCESSOR_DEFINITIONS='$GCC_PREPROCESSOR_DEFINITIONS #{automation_environment}'"
  )

 app_location = find_app_file(derived_data_path)

 begin
   FileUtils.remove_dir(output_directory, force = true)
   FileUtils.mkdir_p output_directory
   FileUtils.mv(app_location, output_directory)
 rescue
   # in case it already exists
 end
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.178.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                      | Version | Update-Status      |
| --------------------------- | ------- | ------------------ |
| fastlane-plugin-appcenter   | 1.8.0   | 🚫 Update available |
| fastlane-plugin-appcenter   | 1.8.0   | 🚫 Update available |
| fastlane-plugin-test_center | 3.9.0   | 🚫 Update available |

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.3.0        |
| executable-hooks              | 1.6.0        |
| bundler-unload                | 1.0.2        |
| rubygems-bundler              | 1.4.5        |
| bundler                       | 1.17.3       |
| etc                           | 1.0.1        |
| forwardable                   | 1.2.0        |
| rake                          | 13.0.3       |
| CFPropertyList                | 3.0.3        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| artifactory                   | 3.0.15       |
| atomos                        | 0.1.3        |
| aws-eventstream               | 1.1.1        |
| aws-partitions                | 1.435.0      |
| aws-sigv4                     | 1.2.3        |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.113.0      |
| aws-sdk-kms                   | 1.43.0       |
| aws-sdk-s3                    | 1.93.0       |
| babosa                        | 1.0.4        |
| claide                        | 1.0.3        |
| colored                       | 1.2          |
| colored2                      | 3.1.2        |
| colorize                      | 0.8.1        |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| digest-crc                    | 0.6.3        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| dotenv                        | 2.7.6        |
| emoji_regex                   | 3.2.2        |
| excon                         | 0.79.0       |
| faraday-net_http              | 1.0.1        |
| multipart-post                | 2.0.0        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.3        |
| gh_inspector                  | 1.1.3        |
| jwt                           | 2.2.2        |
| memoist                       | 0.16.2       |
| multi_json                    | 1.15.0       |
| os                            | 1.1.1        |
| signet                        | 0.15.0       |
| googleauth                    | 0.16.0       |
| httpclient                    | 2.8.3        |
| mini_mime                     | 1.0.2        |
| uber                          | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| google-api-client             | 0.38.0       |
| rexml                         | 3.2.4        |
| webrick                       | 1.7.0        |
| google-apis-core              | 0.3.0        |
| google-apis-iamcredentials_v1 | 0.2.0        |
| google-apis-storage_v1        | 0.3.0        |
| google-cloud-env              | 1.5.0        |
| google-cloud-errors           | 1.1.0        |
| google-cloud-core             | 1.6.0        |
| google-cloud-storage          | 1.31.0       |
| json                          | 2.5.1        |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| plist                         | 3.6.0        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| simctl                        | 1.6.8        |
| slack-notifier                | 2.3.2        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| word_wrap                     | 1.0.0        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| xcpretty-travis-formatter     | 1.0.1        |
| fastlane-plugin-appcenter     | 1.8.0        |
| xctest_list                   | 1.1.8        |
| fastlane-plugin-test_center   | 3.9.0        |
</details>

**Comment by tedgonzalez** [comment]
What's the value of options["tvOS-Functional"] and options["tvOS-Backend"] ?

**Comment by sbogart19** [comment]
Closing this issue - turns out that this works fine without the `options`.
