### ISSUE TITLE
The uploadBitcode, uploadSymbols options are always true.

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1846]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/11883253?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @taehoon-jung - Imported from <a href='https://github.com/fastlane/gym/issues/136'>fastlane/gym#136</a>
        </td>
      </tr>
    </table>

Hello,

Recently I applied gym to my project. I modified all scripts.
I am very satisfied with gym. Thank you.

But I found a something when I ran gym with options.

### Issue 

I ran `gym` with `include_bitcode` and `include_symbols` options.
`$ gym --include_bitcode false --include_symbols false`

Building and exporting binary are succeed but I found a log about `exportOptionsPlist` on console.
```
[18:07:09]: Successfully stored the archive. You can find it in the Xcode Organizer.
[18:07:09]: /usr/bin/xcrun xcodebuild -exportArchive -exportOptionsPlist '/tmp/gym_config_1446196029.plist' -archivePath '/Users/user/Library/Developer/Xcode/Archives/2015-10-30/ProductName 2015-10-30 18.03.14.xcarchive' -exportPath '/tmp/1446196029'
```

So I checked the file. 
`$cat /tmp/gym_config_1446196029.plist`
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>method</key>
	<string>app-store</string>
	<key>uploadBitcode</key>
	<true/>
	<key>uploadSymbols</key>
	<true/>
</dict>
</plist>
```

All values of option are `true`. 
Is it right?

**Comment by cybertk** [comment]
Same issue here.

Both `gym(include_bitcode: "false")` and `gym(include_bitcode: false)` does not work in _Fastfile_

**Comment by vpolouchkine** [comment]
@cybertk Does https://github.com/fastlane/fastlane/issues/1846#issuecomment-193420186 a feasible workaround for you?

**Comment by cybertk** [comment]
I'm not using `Gymfile`, I will give it a shot next week.

**Comment by TKBurner** [comment]
Thanks for updating @cybertk. Let us know how it goes! 👍

**Comment by atainter** [comment]
Has anyone had any luck with this? `gym(include_bitcode: false)` does not work for me.
