### ISSUE TITLE
 Permission denied @ rb_sysopen - /Users/xxx/.fastlane/spaceship/admin@xxx.id/cookie 

### ISSUE THREAD

**Issue by ShivaSunny9** [fastlane/fastlane#18478]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

 Permission denied @ rb_sysopen - /Users/xxx/.fastlane/spaceship/admin@xxx.id/cookie 
##### Command executed

This is my fastlane
desc "Push a new beta build to TestFlight" 
    lane :increment do
      build_app(
        xcargs: "-allowProvisioningUpdates",
        workspace: "xxx.xcworkspace", 
        scheme: "xxx"
        )
        sync_code_signing(type: "appstore")    # see code signing guide for more information
      upload_to_testflight
end
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
Traceback (most recent call last):
	55: from /usr/local/bin/bundle:23:in `<main>'
	54: from /usr/local/bin/bundle:23:in `load'
	53: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.15/exe/bundle:37:in `<top (required)>'
	52: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.15/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	51: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.15/exe/bundle:49:in `block in <top (required)>'
	50: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.15/lib/bundler/cli.rb:24:in `start'
	49: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	48: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.15/lib/bundler/cli.rb:30:in `dispatch'
	47: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	46: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	45: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	44: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.15/lib/bundler/cli.rb:494:in `exec'
	43: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.15/lib/bundler/cli/exec.rb:28:in `run'
	42: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.15/lib/bundler/cli/exec.rb:63:in `kernel_load'
	41: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.15/lib/bundler/cli/exec.rb:63:in `load'
	40: from /usr/local/bin/fastlane:23:in `<top (required)>'
	39: from /usr/local/bin/fastlane:23:in `load'
	38: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/bin/fastlane:23:in `<top (required)>'
	37: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	36: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	35: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	34: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	33: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	32: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	31: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	30: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	29: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	28: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	27: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	26: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	25: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	24: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	23: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	22: from Fastfile:57:in `block (2 levels) in parsing_binding'
	21: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	20: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	19: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:31:in `run'
	13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/pilot/lib/pilot/build_manager.rb:17:in `upload'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/pilot/lib/pilot/manager.rb:16:in `start'
	11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/pilot/lib/pilot/manager.rb:31:in `login'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/spaceship/lib/spaceship/connect_api/spaceship.rb:85:in `login'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/spaceship/lib/spaceship/connect_api/client.rb:56:in `login'
	 8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/spaceship/lib/spaceship/client.rb:355:in `login'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/spaceship/lib/spaceship/client.rb:393:in `login'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/spaceship/lib/spaceship/client.rb:808:in `do_login'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/spaceship/lib/spaceship/tunes/tunes_client.rb:129:in `send_login_request'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/spaceship/lib/spaceship/client.rb:281:in `store_cookie'
	 2: from /Library/Ruby/Gems/2.6.0/gems/http-cookie-1.0.3/lib/http/cookie_jar.rb:261:in `save'
	 1: from /Library/Ruby/Gems/2.6.0/gems/http-cookie-1.0.3/lib/http/cookie_jar.rb:261:in `open'
/Library/Ruby/Gems/2.6.0/gems/http-cookie-1.0.3/lib/http/cookie_jar.rb:261:in `initialize': [!] Permission denied @ rb_sysopen - /Users/xxx/.fastlane/spaceship/admin@xxx.id/cookie (Errno::EACCES)
 
] </pre>
</details>

### Environment

mac os
fastlane ver 2.179

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by max-ott** [comment]
Did you install fastlane with sudo or similar? The error is pretty obvious. The process does not have access to where cookies are usually stored.
