### ISSUE TITLE
Fastlane Frameit wont download frames running on bitrise

### ISSUE THREAD

**Issue by gelodgreat** [fastlane/fastlane#18474]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Fastlane frameit wont download the frames
This work previously, and now it doesn't. Seems getting write error?

![image](https://user-images.githubusercontent.com/20021423/112930280-93507e00-914c-11eb-9284-9244987b4105.png)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> Fastlane frameit wont download the frames. It worked before since last week and successfully framing our screenshots</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>
### Stack
| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.15.7                                          |
| Ruby                        | 2.6.5                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.30.1                               |
| Installation Source         | ~/.rbenv/versions/2.6.5/bin/fastlane             |
| Host                        | Mac OS X 10.15.7 (19H2)                          |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.5/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                       |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-12.4.app/Contents/Developer/ |
| Xcode Version               | 12.4                                             |
### System Locale
| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |
### fastlane files:
**No Fastfile found**
**No Appfile found**
### fastlane gems
| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.179.0 | ✅ Up-To-Date  |
### Loaded fastlane plugins:
**No plugins Loaded**
<details><summary><b>Loaded gems</b></summary>
| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.3.0        |
| slack-notifier                | 2.3.2        |
| atomos                        | 0.1.3        |
| CFPropertyList                | 3.0.3        |
| claide                        | 1.0.3        |
| colored2                      | 3.1.2        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| plist                         | 3.6.0        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| multipart-post                | 2.0.0        |
| word_wrap                     | 1.0.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| artifactory                   | 3.0.15       |
| babosa                        | 1.0.4        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| excon                         | 0.79.0       |
| faraday-net_http              | 1.0.1        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.3        |
| gh_inspector                  | 1.1.3        |
| json                          | 2.1.0        |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| xcpretty-travis-formatter     | 1.0.1        |
| dotenv                        | 2.7.6        |
| simctl                        | 1.6.8        |
| jwt                           | 2.2.2        |
| uber                          | 0.1.0        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| mini_mime                     | 1.0.2        |
| multi_json                    | 1.15.0       |
| signet                        | 0.14.1       |
| memoist                       | 0.16.2       |
| os                            | 1.1.1        |
| googleauth                    | 0.15.1       |
| httpclient                    | 2.8.3        |
| google-api-client             | 0.38.0       |
| google-cloud-env              | 1.4.0        |
| google-cloud-errors           | 1.0.1        |
| google-cloud-core             | 1.5.0        |
| rexml                         | 3.1.9        |
| webrick                       | 1.4.2        |
| google-apis-core              | 0.2.1        |
| google-apis-iamcredentials_v1 | 0.1.0        |
| google-apis-storage_v1        | 0.2.0        |
| rake                          | 12.3.2       |
| digest-crc                    | 0.6.3        |
| google-cloud-storage          | 1.30.0       |
| emoji_regex                   | 3.2.2        |
| jmespath                      | 1.4.0        |
| aws-partitions                | 1.430.0      |
| aws-eventstream               | 1.1.0        |
| aws-sigv4                     | 1.2.2        |
| aws-sdk-core                  | 3.112.0      |
| aws-sdk-kms                   | 1.42.0       |
| aws-sdk-s3                    | 1.89.0       |
| bundler                       | 2.1.4        |
| forwardable                   | 1.2.0        |
| logger                        | 1.3.0        |
| date                          | 2.0.0        |
| stringio                      | 0.0.2        |
| zlib                          | 1.0.0        |
| ipaddr                        | 1.2.2        |
| openssl                       | 2.1.2        |
| ostruct                       | 0.1.0        |
| strscan                       | 1.0.0        |
| fileutils                     | 1.1.0        |
| etc                           | 1.0.1        |
| io-console                    | 0.4.7        |
| racc                          | 1.5.2        |
| nokogiri                      | 1.11.1       |
| psych                         | 3.1.0        |
| mutex_m                       | 0.1.0        |
</details>
*generated on:* **2021-03-30**

**Comment by gelodgreat** [comment]
Even lowering the versions seems made it broken, hopefully this can be fixed

![image](https://user-images.githubusercontent.com/20021423/112965956-5603e480-917c-11eb-976d-1e3519542652.png)

**Comment by gelodgreat** [comment]
Even lowering versions seems its broken with bitrise, hopefully this would be fixed.

![image](https://user-images.githubusercontent.com/20021423/112966044-6ddb6880-917c-11eb-97c0-b895f8a4f395.png)

**Comment by max-ott** [comment]
This looks more like an issue of Bitrise. Are you sure that you have the correct read/write access?

**Comment by gelodgreat** [comment]
@max-ott, its already resolved, it seemed that bitrise has issues on github pages last march 31
