### ISSUE TITLE
Unable to authentificate into iTMSTransporter with pilot

### ISSUE THREAD

**Issue by GautierLouis** [fastlane/fastlane#18489]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm unable to upload my ipa on Apple. 
I don't have any proxy, I tried multiples params for `DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS`
It doesn't work if I use XCode > Window > Organizer > Distribute App.
What am I missing ?

##### Command executed
fastlane upload

##### Complete output when running fastlane, including the stack trace and command used
(base) macbook-pro-de-louis:*** louis$ fastlane test --verbose
[✔] 🚀 
[11:42:56]: fastlane detected a Gemfile in the current directory
[11:42:56]: However, it seems like you didn't use `bundle exec`
[11:42:56]: To launch fastlane faster, please use
[11:42:56]: 
[11:42:56]: $ bundle exec fastlane test --verbose
[11:42:56]: 
[11:42:56]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2021-03-31 11:42:57.40]: Checking if there are any plugins that should be loaded...
DEBUG [2021-03-31 11:42:57.44]: Loading 'fastlane-plugin-sentry' plugin
INFO [2021-03-31 11:42:57.46]: gem 'fastlane-plugin-sentry' is already installed
+------------------------+---------+----------------------------------------------------------------+
|                                           Used plugins                                            |
+------------------------+---------+----------------------------------------------------------------+
| Plugin                 | Version | Action                                                         |
+------------------------+---------+----------------------------------------------------------------+
| fastlane-plugin-sentry | 1.8.1   | sentry_upload_dsym sentry_set_commits sentry_upload_sourcemap  |
|                        |         | sentry_finalize_release sentry_upload_file                     |
|                        |         | sentry_upload_proguard sentry_create_release                   |
+------------------------+---------+----------------------------------------------------------------+

Successfully loaded Appfile at path '/Users/louis/Documents/***/fastlane/Appfile'
- app_identifier: '***'
- team_name: '***'
- team_id: '***'
- apple_id: '***'
- itc_team_name: '***'
- itc_team_id: '***'
-------
INFO [2021-03-31 11:42:57.61]: ----------------------------------------
INFO [2021-03-31 11:42:57.61]: --- Step: Verifying fastlane version ---
INFO [2021-03-31 11:42:57.61]: ----------------------------------------
INFO [2021-03-31 11:42:57.61]: Your fastlane version 2.179.0 matches the minimum requirement of 1.40.0  ✅
INFO [2021-03-31 11:42:57.61]: ------------------------------
INFO [2021-03-31 11:42:57.61]: --- Step: default_platform ---
INFO [2021-03-31 11:42:57.61]: ------------------------------
INFO [2021-03-31 11:42:57.61]: Driving the lane 'ios test' 🚀
INFO [2021-03-31 11:42:57.61]: ---------------------------------------
INFO [2021-03-31 11:42:57.61]: --- Step: app_store_connect_api_key ---
INFO [2021-03-31 11:42:57.61]: ---------------------------------------
INFO [2021-03-31 11:42:57.72]: -------------------
INFO [2021-03-31 11:42:57.72]: --- Step: pilot ---
INFO [2021-03-31 11:42:57.72]: -------------------
INFO [2021-03-31 11:42:57.72]: Ready to upload new build to TestFlight (App: 1102463980)...
DEBUG [2021-03-31 11:42:57.72]: App Platform (ios)
INFO [2021-03-31 11:42:58.58]: Wrote XML data to '/var/folders/3b/sbjy_rxn4gg_htfcbpcq7n2c0000gn/T/d20210331-1036-15enb3/1102463980-8fc6c39b-91bf-4b6c-b4c8-cb4e9e43587e.itmsp'
INFO [2021-03-31 11:42:58.58]: Going to upload updated app to App Store Connect
INFO [2021-03-31 11:42:58.58]: This might take a few minutes. Please don't interrupt the script.
WARN [2021-03-31 11:42:58.58]: Apple recommends you don’t specify the -t transport and instead allow Transporter to use automatic transport discovery to determine the best transport mode for your packages. For more information, please read Apple's Transporter User Guide 2.1: https://help.apple.com/itc/transporteruserguide/#/apdATD1E1288-D1E1A1303-D1E1288A1126
WARN [2021-03-31 11:42:58.58]: Apple recommends you don’t specify the -t transport and instead allow Transporter to use automatic transport discovery to determine the best transport mode for your packages. For more information, please read Apple's Transporter User Guide 2.1: https://help.apple.com/itc/transporteruserguide/#/apdATD1E1288-D1E1A1303-D1E1288A1126
DEBUG [2021-03-31 11:42:58.58]: xcrun iTMSTransporter -m upload -jwt YourJWT -f /var/folders/3b/sbjy_rxn4gg_htfcbpcq7n2c0000gn/T/d20210331-1036-15enb3/1102463980-8fc6c39b-91bf-4b6c-b4c8-cb4e9e43587e.itmsp -t DAV -k 100000 2>&1
DEBUG [2021-03-31 11:43:00.90]: [Transporter]: INFO: Configuring logging...
DEBUG [2021-03-31 11:43:00.90]: [Transporter]: INFO: Logging level set to eXtreme
DEBUG [2021-03-31 11:43:00.91]: [Transporter]: INFO: Transporter is searching for new software components.
DEBUG [2021-03-31 11:43:00.91]: [Transporter]: INFO: INFO: using cached repository.xml file.
DEBUG [2021-03-31 11:43:01.09]: [Transporter]: INFO: Update check complete.
DEBUG [2021-03-31 11:43:02.68]: [Transporter]: DEBUG: Attempting refresh of configuration data from https://contentdelivery.itunes.apple.com/transporter/Defaults.properties
DEBUG [2021-03-31 11:43:02.85]: [Transporter]: DEBUG: Configuration refresh successful.
DEBUG [2021-03-31 11:43:02.85]: [Transporter]: DEBUG: Saving configuration to local path: /Users/louis/Library/Caches/com.apple.amp.itmstransporter/Defaults.properties
DEBUG [2021-03-31 11:43:02.96]: [Transporter]: INFO: iTMSTransporter : iTunes Store Transporter [2.1.0]
DEBUG [2021-03-31 11:43:02.96]: [Transporter]: INFO: OS identifier: Mac OS X 10.15.7 (x86_64); jvm=14.0.2+12-iTunesOpenJDK-5; jre=14.0.2+12-iTunesOpenJDK-5
DEBUG [2021-03-31 11:43:02.96]: [Transporter]: INFO: Memory: [JVM] 729M free, 1024M total, 2048M max [System] (Physical) 689M free, 16384M total (Swap) 0 free, 0 total
DEBUG [2021-03-31 11:43:02.96]: [Transporter]: DBG-X: Memory: [JVM] 729M free, 1024M total, 2048M max [System] (Physical) 689M free, 16384M total (Swap) 0 free, 0 total
DEBUG [2021-03-31 11:43:02.97]: [Transporter]: DBG-X: Using operation named: authenticateForSession
DEBUG [2021-03-31 11:43:03.00]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2021-03-31 11:43:03.00]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2021-03-31 11:43:03.00]: [Transporter]: DBG-X:   parameter BaseVersion = 2.1.0
DEBUG [2021-03-31 11:43:03.00]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.15.7 (x86_64); jvm=14.0.2+12-iTunesOpenJDK-5; jre=14.0.2+12-iTunesOpenJDK-5
DEBUG [2021-03-31 11:43:03.00]: [Transporter]: DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2021-03-31T11:43:02+02:00
DEBUG [2021-03-31 11:43:03.00]: [Transporter]: DBG-X:   parameter StatisticsPreviousCallDurationInSecs = 0.298892484
DEBUG [2021-03-31 11:43:03.00]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -jwt **hidden value** -f /var/folders/3b/sbjy_rxn4gg_htfcbpcq7n2c0000gn/T/d20210331-1036-15enb3/1102463980-8fc6c39b-91bf-4b6c-b4c8-cb4e9e43587e.itmsp -t DAV -k 100000
DEBUG [2021-03-31 11:43:03.00]: [Transporter]: DBG-X:   parameter Version = 2.1.0
DEBUG [2021-03-31 11:43:03.00]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
DEBUG [2021-03-31 11:43:03.00]: [Transporter]: INFO: id = 20210331114303-508
DEBUG [2021-03-31 11:43:03.01]: [Transporter]: INFO: iTMSTransporter Correlation Key: cee49c86-d8fa-4ffc-aa0a-b7bcd8ac997f-0001
DEBUG [2021-03-31 11:43:03.69]: [Transporter]: INFO: Apple Correlation Key: IIPCKBGYA22M2PKSHJNGSTEDNI
DEBUG [2021-03-31 11:43:03.69]: [Transporter]: INFO: Web service received a server status of: HTTP/1.1 401 Unauthorized
DEBUG [2021-03-31 11:43:03.69]: [Transporter]: INFO: Web service response received: Unauthenticated
ERROR [2021-03-31 11:43:03.71]: Transporter transfer failed.
WARN [2021-03-31 11:43:03.71]: 
ERROR [2021-03-31 11:43:03.71]: Communication error. Please use diagnostic mode to check connectivity.
WARN [2021-03-31 11:43:03.84]: [iTMSTransporter] [2021-03-31 11:43:03 CEST] <main> DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2021-03-31T11:43:02+02:00

WARN [2021-03-31 11:43:03.84]: [iTMSTransporter] [2021-03-31 11:43:03 CEST] <main> DBG-X:   parameter StatisticsPreviousCallDurationInSecs = 0.298892484

WARN [2021-03-31 11:43:03.84]: [iTMSTransporter] [2021-03-31 11:43:03 CEST] <main> DBG-X:   parameter TransporterArguments = -m upload -jwt **hidden value** -f /var/folders/3b/sbjy_rxn4gg_htfcbpcq7n2c0000gn/T/d20210331-1036-15enb3/1102463980-8fc6c39b-91bf-4b6c-b4c8-cb4e9e43587e.itmsp -t DAV -k 100000

WARN [2021-03-31 11:43:03.84]: [iTMSTransporter] [2021-03-31 11:43:03 CEST] <main> DBG-X:   parameter Version = 2.1.0

WARN [2021-03-31 11:43:03.84]: [iTMSTransporter] [2021-03-31 11:43:03 CEST] <main> DBG-X:   parameter iTMSTransporterMode = upload

WARN [2021-03-31 11:43:03.84]: [iTMSTransporter] [2021-03-31 11:43:03 CEST] <main>  INFO: id = 20210331114303-508

WARN [2021-03-31 11:43:03.84]: [iTMSTransporter] [2021-03-31 11:43:03 CEST] <main>  INFO: iTMSTransporter Correlation Key: cee49c86-d8fa-4ffc-aa0a-b7bcd8ac997f-0001

WARN [2021-03-31 11:43:03.84]: [iTMSTransporter] [2021-03-31 11:43:03 CEST] <main>  INFO: Apple Correlation Key: IIPCKBGYA22M2PKSHJNGSTEDNI

WARN [2021-03-31 11:43:03.84]: [iTMSTransporter] [2021-03-31 11:43:03 CEST] <main>  INFO: Web service received a server status of: HTTP/1.1 401 Unauthorized

WARN [2021-03-31 11:43:03.84]: [iTMSTransporter] [2021-03-31 11:43:03 CEST] <main>  INFO: Web service response received: Unauthenticated

WARN [2021-03-31 11:43:03.84]: [iTMSTransporter] 

WARN [2021-03-31 11:43:03.84]: [iTMSTransporter] Request ID: IIPCKBGYA22M2PKSHJNGSTEDNI.0.0

WARN [2021-03-31 11:43:03.84]: [iTMSTransporter] 

WARN [2021-03-31 11:43:03.84]: [iTMSTransporter] [2021-03-31 11:43:03 CEST] <main> ERROR: Communication error. Please use diagnostic mode to check connectivity.

WARN [2021-03-31 11:43:03.84]: [iTMSTransporter] [2021-03-31 11:43:03 CEST] <main> DBG-X: Returning 1

INFO [2021-03-31 11:43:03.84]: iTunes Transporter output above ^
ERROR [2021-03-31 11:43:03.84]: Communication error. Please use diagnostic mode to check connectivity.
Return status of iTunes Transporter was 1: Communication error. Please use diagnostic mode to check connectivity.
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
WARN [2021-03-31 11:43:03.84]: Lane Context:
INFO [2021-03-31 11:43:03.84]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios test"}
ERROR [2021-03-31 11:43:03.84]: Error uploading ipa file: 
 
INFO [2021-03-31 11:43:03.84]: Successfully generated documentation at path '/Users/louis/Documents/***/fastlane/README.md'

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 3    | app_store_connect_api_key  | 0           |
| 💥   | pilot                      | 6           |
+------+----------------------------+-------------+

DEBUG [2021-03-31 11:43:03.85]: All plugins are up to date
ERROR [2021-03-31 11:43:03.85]: fastlane finished with errors
DEBUG [2021-03-31 11:43:03.85]: All plugins are up to date
Traceback (most recent call last):
	29: from /usr/local/bin/fastlane:23:in `<main>'
	28: from /usr/local/bin/fastlane:23:in `load'
	27: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/bin/fastlane:23:in `<top (required)>'
	26: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	25: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	24: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	23: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	22: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	21: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	20: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	19: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	11: from Fastfile:21:in `block (2 levels) in parsing_binding'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	 8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:31:in `run'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/pilot/lib/pilot/build_manager.rb:38:in `upload'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': Error uploading ipa file:  (FastlaneCore::Interface::FastlaneError)
 
	29: from /usr/local/bin/fastlane:23:in `<main>'
	28: from /usr/local/bin/fastlane:23:in `load'
	27: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/bin/fastlane:23:in `<top (required)>'
	26: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	25: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	24: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	23: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	22: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	21: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	20: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	19: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	11: from Fastfile:21:in `block (2 levels) in parsing_binding'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	 8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:31:in `run'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/pilot/lib/pilot/build_manager.rb:38:in `upload'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Error uploading ipa file:  (FastlaneCore::Interface::FastlaneError)
 

### Environment
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.7                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.7 (19H524)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.4                                                           |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "1.40.0"

default_platform :ios

xcodeproj = "***.xcodeproj"


platform :ios do

  desc "Upload App" 
  lane :upload do |options|

  app_store_connect_api_key(
    key_id: "***",
    issuer_id: "***",
    key_filepath: "./AuthKey_***.p8",
    in_house: true
  )

  ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV" 
#Also tried ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = " " 
  pilot(
    apple_id: "***",
    app_identifier: "***",
    skip_waiting_for_build_processing: true,
    team_id: "***"
  )

  end

#Increment build version; add git tag; build and sign ipa
  desc "Build App" 
  lane :build do |options|

    ensure_git_status_clean
    clean_build_artifacts

    build_number = number_of_commits + 300 # Added offset since git repostitory reset
    increment_build_number(build_number: build_number)
    commit_version_bump(xcodeproj: xcodeproj)     
    add_git_tag(tag: "appstore/v#{get_version_number}", force: true)
    get_certificates
    get_provisioning_profile
    build_app
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "***"
team_name "****"
team_id "****"
apple_id "***@***.com"
itc_team_name "****"
itc_team_id "****"

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.179.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                 | Version | Update-Status |
| ---------------------- | ------- | ------------- |
| fastlane-plugin-sentry | 1.8.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| artifactory               | 3.0.15       |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.76.0       |
| faraday                   | 1.0.1        |
| faraday_middleware        | 1.0.0        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| naturally                 | 2.2.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.17.2       |
| uber                      | 0.1.0        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| signet                    | 0.14.0       |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-storage      | 1.28.0       |
| jmespath                  | 1.4.0        |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.107.0      |
| aws-sdk-kms               | 1.38.0       |
| aws-sdk-s3                | 1.81.0       |
| nanaimo                   | 0.3.0        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.18.0       |
| unicode-display_width     | 1.7.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| fastimage                 | 2.2.0        |
| json                      | 2.3.1        |
| dotenv                    | 2.7.6        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| declarative               | 0.0.20       |
| multi_json                | 1.15.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| emoji_regex               | 3.0.0        |
| aws-partitions            | 1.374.0      |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
| fastlane-plugin-sentry    | 1.8.1        |
</details>

*generated on:* **2021-03-31**
</details>

**Comment by max-ott** [comment]
How are you authenticating? 

```
DEBUG [2021-03-31 11:43:03.69]: [Transporter]: INFO: Web service received a server status of: HTTP/1.1 401 Unauthorized
DEBUG [2021-03-31 11:43:03.69]: [Transporter]: INFO: Web service response received: Unauthenticated
```

Show that you are not authorized to do this.

**Comment by GautierLouis** [comment]
Hello. 
Thanks for the reply
I figured out. I replace the .p8 file but forget to update the key_id.
