### ISSUE TITLE
 [Regression] Failed archive after executed gym(release)

### ISSUE THREAD

**Issue by funzin** [fastlane/fastlane#18495]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: [e.g. `2.179.0`]
- Last working version: [e.g. `2.178.0`]

### Regression Description
From `2.179.0`, when executed `gym`, if export_method is `ad-hoc` or `app-store`, we got `ARCHIVE FAILED` error.
We haven't seen the error before `2.178.0`.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>** ARCHIVE FAILED **
The following build commands failed:
	PhaseScriptExecution Carthage /Users/vagrant/git/tmp/fastlane/derived_data/Build/Intermediates.noindex/ArchiveIntermediates/App-Adhoc/IntermediateBuildFilesPath/App.build/Adhoc-iphoneos/App.build/Script-F5222583018FA2A2995FFC5F.sh
(1 failure)
[12:24:16]: Exit status: 65
[12:24:16]: 
[12:24:16]: Maybe the error shown is caused by using the wrong version of Xcode
[12:24:16]: Found multiple versions of Xcode in '/Applications/'
[12:24:16]: Make sure you selected the right version for your project
[12:24:16]: This build process was executed using '/Applications/Xcode-12.4.app'
[12:24:16]: If you want to update your Xcode path, either
[12:24:16]: 
[12:24:16]: - Specify the Xcode version in your Fastfile
[12:24:16]: ▸ xcversion(version: "8.1") # Selects Xcode 8.1.0
[12:24:16]: 
[12:24:16]: - Specify an absolute path to your Xcode installation in your Fastfile
[12:24:16]: ▸ xcode_select "/Applications/Xcode8.app"
[12:24:16]: 
[12:24:16]: - Manually update the path using
[12:24:16]: ▸ sudo xcode-select -s /Applications/Xcode.app</pre>

</details>

### Environment

<details

  <summary>🚫 fastlane environment 🚫</summary>
  
### Stack

| Key                         | Value                                                            |
| --------------------------- | ---------------------------------------------------------------- |
| OS                          | 11.2.2                                                           |
| Ruby                        | 2.6.5                                                            |
| Bundler?                    | true                                                             |
| Git                         | git version 2.29.2                                               |
| Installation Source         | ~/App/vendor/bundle/ruby/2.6.0/bin/fastlane |
| Host                        | macOS 11.2.2 (20D80)                                             |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.5/lib                                      |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                                      |
| Is contained                | false                                                            |
| Is homebrew                 | false                                                            |
| Is installed via Fabric.app | false                                                            |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                      |
| Xcode Version               | 12.4                                                             |

</details>

**Comment by joshdholtz** [comment]
@funzin Sorry about this! So... if you switch back to `2.178.0`, does it successfully build for you again?

**Comment by funzin** [comment]
>if you switch back to 2.178.0, does it successfully build for you again?
 
Yes,  it successfully builds in `2.178.0`!

**Comment by joshdholtz** [comment]
@funzin Are you able to send me what parameters you are passing into `gym`? 😇 I’d like to try to replicate this issue on my side so I can fix.

**Comment by funzin** [comment]
Yes, I'm.
Please check the following code:pray:.

```Fastfile.rb
    gym(
      scheme: "App-Release",
      export_method: "app-store",
      derived_data_path: "./derived_data",
      result_bundle: true,
      result_bundle_path: "./result_bundle"
    )
```

**Comment by joshdholtz** [comment]
@funzin This is _really_ weird 🤔 I guess its failing inside of some carthage command (based upon your description) and I’m not able to replicate that 😔 

But also, I looked at the changelog for `2.179.0` and there were two changes to `gym` put both were _after_ the build command and for macOS apps. And it looks like this is happening before that and for iOS 🤔 

Would you possibly be able to get me complete console output running this in both `2.178.0` and `2.179.0` 😇  I want to compare the logs to see if there are any differences in things be executed.

Thank you and sorry about this issue!

**Comment by funzin** [comment]
Ummm, I just checked and executed `gym` command again but **succeeded**🙄
I don't know why failed 6 days ago... but there seems to be no problem!

Thank you for investigating:bow:
