### ISSUE TITLE
upload_to_testflight choose wrong file

### ISSUE THREAD

**Issue by maphongba008** [fastlane/fastlane#18499]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.4                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.4 (19E2269)                                     |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.5                                                           |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.179.0 | ✅ Up-To-Date  |

### Issue Description

upload_to_testflight choose wrong file to upload. I want to upload a build to ***.qa with build number 1.12.8.9, but somehow fastlane chooses wrong build with wrong app id (as you can see fastlane upload build version 1.9.2.1).
```
INFO [2021-04-02 13:14:35.92]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, 
:LANE_NAME=>"ios qa_store", 
:SIGH_PROFILE_TYPE=>"app-store", 
:MATCH_PROVISIONING_PROFILE_MAPPING=>{"****"}, 
:IPA_OUTPUT_PATH=>"/Users/quynh/Documents/Projects/LeapXpert/new-mobile-app/LeapXpertApp/ios/QA/AppStore/output.ipa", 
:XCODEBUILD_ARCHIVE=>"/Users/quynh/Library/Developer/Xcode/Archives/2021-04-02/output 2021-04-02 11.52.15.xcarchive", 
:DSYM_OUTPUT_PATH=>"/Users/quynh/Documents/Projects/LeapXpert/new-mobile-app/LeapXpertApp/ios/QA/AppStore/output.app.dSYM.zip",
 :VERSION_NUMBER=>"1.12.8", 
:BUILD_NUMBER=>"9"}
ERROR [2021-04-02 13:14:35.92]: Error uploading ipa file: 
 [Transporter Error Output]: ERROR ITMS-90053: This bundle is invalid. The bundle identifier is already in use by a different software package.
[Transporter Error Output]: ERROR ITMS-90055: This bundle is invalid. The bundle identifier cannot be changed from the current value, '***.qa'. If you want to change your bundle identifier, you will need to create a new application in App Store Connect.
[Transporter Error Output]: ERROR ITMS-90189: Redundant Binary Upload. You've already uploaded a build with build number '1' for version number '1.9.2'. Make sure you increment the build string before you upload your app to App Store Connect. Learn more in Xcode Help (http://help.apple.com/xcode/mac/current/#/devba7f53ad4).
\nERROR ITMS-90055: This bundle is invalid. The bundle identifier cannot be changed from the current value, '*****.qa'. If you want to change your bundle identifier, you will need
ERROR ITMS-90189: Redundant Binary Upload. You've already uploaded a build with build number '1' for version number '1.9.2'. Make sure you increment the build string before you upload your app to App Store Connect. Learn more in Xcode Help (http://help.apple.com/xcode/mac/current/#/devba7f53ad4).
[Transporter Error Output]: The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
```

Here's my config:
```

desc "Release a new QA build"
  lane :qa_store do
    # sync cert/profiles for appstore release
    match(type: "appstore", readonly: true)
    # qa app
    app_identifier = "***.qa"
    matchProvisioningUUID = ENV["sigh_#{app_identifier}_appstore"]
    # update cert/profile in Xcode
    update_code_signing_settings(
      path: "#{projectName}.xcodeproj",
      use_automatic_signing: false,
      team_id: team_id,
      targets: [target],
      code_sign_identity: 'Apple Distribution',
      profile_uuid: matchProvisioningUUID,
      build_configurations: 'Release',
    )
    # build app
    build_app(
      clean: true,
      scheme: "***",
      configuration: "Release",
      workspace: "#{projectName}.xcworkspace",
      export_team_id: team_id,
      output_directory: "./QA/AppStore/",
      export_options: {
        method: "app-store",
        provisioningProfiles: {
          "#{app_identifier}" => "match AppStore #{app_identifier}",
        }
      },
    )
    version = get_version_number(
      xcodeproj: "#{projectName}.xcodeproj",
      target: "***",
    )
    build_number = get_build_number(
      xcodeproj: "#{projectName}.xcodeproj",
    )
    # upload
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      apple_id: "***",
    )
    slack(
      message: "Successfully upload a new build *QA* *#{version}(#{build_number})* to TestFlight",
      slack_url: '***',
      payload: {  # Optional, lets you specify any number of your own Slack attachments.
        "Version" => "#{version}(#{build_number})",
      },
      default_payloads: [],
    )
  end
```

**Comment by max-ott** [comment]
What happens if you explicitly use the bundle ID? https://docs.fastlane.tools/actions/upload_to_testflight/#parameters

**Comment by maphongba008** [comment]
@max-ott  still the same :(

**Comment by maphongba008** [comment]
@max-ott still the same :(

**Comment by maphongba008** [comment]
Resolved, due to specified wrong apple_id
