### ISSUE TITLE
java.lang.IllegalArgumentException: Unknown package:

### ISSUE THREAD

**Issue by BharathSaraswathi** [fastlane/fastlane#18527]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

After providing the debug test apk , an error is thrown as shown below.

**_Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown package: com.aligntech.myinvisalign
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:1391)
        at com.android.server.pm.permission.PermissionManagerService.access$900(PermissionManagerService.java:89)
        at com.android.server.pm.permission.PermissionManagerService$PermissionManagerInternalImpl.grantRuntimePermission(PermissionManagerService.java:2093)
        at com.android.server.pm.PackageManagerService.grantRuntimePermission(PackageManagerService.java:5411)
        at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:1730)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:217)
        at android.os.ShellCommand.exec(ShellCommand.java:103)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21328)
        at android.os.Binder.shellCommand(Binder.java:634)
        at android.os.Binder.onTransact(Binder.java:532)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2821)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3856)
        at android.os.Binder.execTransact(Binder.java:731)
 Exit status: 255_**

##### Command executed

fastlane screengrab
Select your debug app APK. - 6
Select your debug tests APK - 3

##### Complete output when running fastlane, including the stack trace and command used

 **Exception occurred while executing:**
[11:40:02]: ▸ java.lang.IllegalArgumentException: Unknown package: com.aligntech.myinvisalign
[11:40:02]: ▸   at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:1391)
[11:40:02]: ▸   at com.android.server.pm.permission.PermissionManagerService.access$900(PermissionManagerService.java:89)
[11:40:02]: ▸   at com.android.server.pm.permission.PermissionManagerService$PermissionManagerInternalImpl.grantRuntimePermission(PermissionManagerService.java:2093)
[11:40:02]: ▸   at com.android.server.pm.PackageManagerService.grantRuntimePermission(PackageManagerService.java:5411)
[11:40:02]: ▸   at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:1730)
[11:40:02]: ▸   at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:217)
[11:40:02]: ▸   at android.os.ShellCommand.exec(ShellCommand.java:103)
[11:40:02]: ▸   at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21328)
[11:40:02]: ▸   at android.os.Binder.shellCommand(Binder.java:634)
[11:40:02]: ▸   at android.os.Binder.onTransact(Binder.java:532)
[11:40:02]: ▸   at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2821)
[11:40:02]: ▸   at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3856)
[11:40:02]: ▸   at android.os.Binder.execTransact(Binder.java:731)

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[11:48:19]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
[11:48:20]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.0.1                                                         |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.0.1 (20B50)                                           |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Library/Developer/CommandLineTools/                           |
| Xcode Version               |                                                                |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.179.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.3.0        |
| slack-notifier                | 2.3.2        |
| atomos                        | 0.1.3        |
| claide                        | 1.0.3        |
| colored2                      | 3.1.2        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| plist                         | 3.6.0        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| multipart-post                | 2.0.0        |
| word_wrap                     | 1.0.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| artifactory                   | 3.0.15       |
| babosa                        | 1.0.4        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| excon                         | 0.79.0       |
| faraday-net_http              | 1.0.1        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.3        |
| gh_inspector                  | 1.1.3        |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| xcpretty-travis-formatter     | 1.0.1        |
| dotenv                        | 2.7.6        |
| simctl                        | 1.6.8        |
| jwt                           | 2.2.2        |
| uber                          | 0.1.0        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| mini_mime                     | 1.1.0        |
| multi_json                    | 1.15.0       |
| signet                        | 0.15.0       |
| memoist                       | 0.16.2       |
| os                            | 1.1.1        |
| googleauth                    | 0.16.1       |
| httpclient                    | 2.8.3        |
| google-api-client             | 0.38.0       |
| google-cloud-env              | 1.5.0        |
| google-cloud-errors           | 1.1.0        |
| google-cloud-core             | 1.6.0        |
| google-apis-core              | 0.3.0        |
| google-apis-storage_v1        | 0.3.0        |
| digest-crc                    | 0.6.3        |
| google-cloud-storage          | 1.31.0       |
| emoji_regex                   | 3.2.2        |
| jmespath                      | 1.4.0        |
| aws-partitions                | 1.441.0      |
| aws-eventstream               | 1.1.1        |
| aws-sigv4                     | 1.2.3        |
| aws-sdk-core                  | 3.113.1      |
| aws-sdk-kms                   | 1.43.0       |
| aws-sdk-s3                    | 1.93.0       |
| CFPropertyList                | 3.0.3        |
| json                          | 2.5.1        |
| bundler                       | 2.2.15       |
| webrick                       | 1.7.0        |
| rexml                         | 3.2.5        |
| google-apis-iamcredentials_v1 | 0.3.0        |
| rake                          | 13.0.3       |
| forwardable                   | 1.2.0        |
| logger                        | 1.3.0        |
| date                          | 2.0.0        |
| stringio                      | 0.0.2        |
| zlib                          | 1.0.0        |
| ipaddr                        | 1.2.2        |
| openssl                       | 2.1.2        |
| ostruct                       | 0.1.0        |
| strscan                       | 1.0.0        |
| fileutils                     | 1.1.0        |
| etc                           | 1.0.1        |
| io-console                    | 0.4.7        |
| libxml-ruby                   | 3.1.0        |
| psych                         | 3.1.0        |
| mutex_m                       | 0.1.0        |
</details>

*generated on:* **2021-04-09**
</details>
[11:48:22]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.

Looking for related GitHub issues on fastlane/fastlane...

➡️  Screenshot are failing. 
    https://github.com/fastlane/fastlane/issues/15447 [closed] 5 💬
    14 Jan 2020

➡️  Malformed version number string undefined
    https://github.com/fastlane/fastlane/issues/14663 [closed] 1 💬
    23 Jun 2019

➡️  invalid byte sequence in UTF-8 when importing XLIFF files containing non UTF8 characters
    https://github.com/fastlane/fastlane/issues/12442 [closed] 3 💬
    05 Oct 2018

and 31 more at: https://github.com/fastlane/fastlane/search?q=invalid%20byte%20sequence%20in%20US-ASCII&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.

#######################################################################
# fastlane 2.180.1 is available. You are on 2.179.0.
# You should use the latest version.
# Please update using `gem install fastlane`.
#######################################################################

2.180.1 Improvements
* [fastlane] fix fastlane_require to work with RubyGems 3.2.0 and up (#18520) via Josh Holtz

2.180.0 Improvements
* [action][jira] API response improvement (#18504) via Manish Rathi
* [action] fix "sh" broken when output is in encoding other than UTF-8 (#18075) via Stuart McHattie
* [scan] retry after failure (#17765) via Xavier Lowmiller
* [Fastlane.Swift] fix onError not being called (#18452) via Jorge
* [match] fix match change password argument error (#18510) via Bob Smits
* [action] notarize: add support for AppStore Connect API Key (#18364) via Paul Niezborala
* [Fastlane.Swift] Restore 'swift' directory if it is deleted before running a lane (#18496) via Tim Oliver
* [action][app_store_connect_api_key] Updated `is_supported` platform  (#18462) via Manish Rathi
* [snapshot] bump SnapshotHelper.swift's version. (#18503) via Yilei "Dolee" Yang
* [Fastlane.Swift] fix array-typed RubyCommand arguments (#18458) via Jorge
* [action] new sourcedocs action (#18464) via Nemanja Filipovic

Please update using `gem install fastlane`
[11:48:25]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
Traceback (most recent call last):
        20: from /usr/local/bin/fastlane:23:in `<main>'
        19: from /usr/local/bin/fastlane:23:in `load'
        18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/bin/fastlane:23:in `<top (required)>'
        17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
        16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
        14: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        12: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        11: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        10: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
         9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/commands_generator.rb:266:in `block (2 levels) in run'
         8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/environment_printer.rb:13:in `output'
         7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
         6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:135:in `confirm'
         5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `agree'
         4: from /Library/Ruby/Gems/2.6.0/gems/highline-1.7.10/lib/highline.rb:227:in `agree'
         3: from /Library/Ruby/Gems/2.6.0/gems/highline-1.7.10/lib/highline.rb:261:in `ask'
         2: from /Library/Ruby/Gems/2.6.0/gems/highline-1.7.10/lib/highline.rb:621:in `say'
         1: from /Library/Ruby/Gems/2.6.0/gems/highline-1.7.10/lib/highline.rb:730:in `format_statement'
/Library/Ruby/Gems/2.6.0/gems/highline-1.7.10/lib/highline.rb:730:in `gsub': invalid byte sequence in US-ASCII (ArgumentError)
        20: from /usr/local/bin/fastlane:23:in `<main>'
        19: from /usr/local/bin/fastlane:23:in `load'
        18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/bin/fastlane:23:in `<top (required)>'
        17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
        16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
        14: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        12: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        11: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        10: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
         9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/commands_generator.rb:266:in `block (2 levels) in run'
         8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/environment_printer.rb:13:in `output'
         7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
         6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.179.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:135:in `confirm'
         5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `agree'
         4: from /Library/Ruby/Gems/2.6.0/gems/highline-1.7.10/lib/highline.rb:227:in `agree'
         3: from /Library/Ruby/Gems/2.6.0/gems/highline-1.7.10/lib/highline.rb:261:in `ask'
         2: from /Library/Ruby/Gems/2.6.0/gems/highline-1.7.10/lib/highline.rb:621:in `say'
         1: from /Library/Ruby/Gems/2.6.0/gems/highline-1.7.10/lib/highline.rb:730:in `format_statement'
/Library/Ruby/Gems/2.6.0/gems/highline-1.7.10/lib/highline.rb:730:in `gsub': [!] invalid byte sequence in US-ASCII (ArgumentError)
</pre>
</details>

**Comment by BharathSaraswathi** [comment]
Hello,
Does anyone have a solution for this issue. Appreciate if someone can help.

**Comment by MakakWasTaken** [comment]
I started having this error a couple of days ago. In my case, I was working on a react native project and I had accidentally put in the wrong package name. 

You can find the list of package names by running the command: `adb -s :EMULATOR: shell pm list packages -f  `
You should replace 'EMULATOR' with the id that you get from running `adb devices`. You will then get a long list of different packages. Look through it and find something that is related to your project. In addition to this you can set the test package name in the settings aswell. This is done by appending `.tests` to your package name.
