### ISSUE TITLE
create_keychain unlock: true doesn't actually unlock the keychain.

### ISSUE THREAD

**Issue by airtonix** [fastlane/fastlane#18541]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Few things I've noticed:

- `create_keychain` is required for fully hands off automated build.
- `create_keychain(unlock: true, name: 'cicd')` doesn't actually unlock the keychain created.
- even when unlocked manually by myself clicking around OSX, xcode still can't see the certs described in the profiles.

This is our "codesigning prep" step before our `build` step to ensure we have all the bits in place (we're also using ruby-config)...

```
desc "Fetch the codesigning assets for IOS

Match will handle the creation of the filenames, which we control
via the application_id.
"
lane :keystore_get do |options|
  application_id = options[:application_id] || Settings.application.id
  team_id = options[:team_id] || Settings.apple.team_id
  git_branch = options[:git_branch] || Settings.codesigning.branch
  git_url = options[:git_url] || Settings.codesigning.git_url
  output_path = Settings.codesigning.store_path
  keychain_name = Settings.codesigning.keychain_name

  create_keychain(
    name: keychain_name,
    password: '',
    default_keychain: true,
    lock_when_sleeps: false,
    add_to_search_list: true,
    unlock: true,
    timeout: 3600
  )

  match(
    keychain_name: keychain_name,
    keychain_password: '',
    git_url: git_url,
    git_branch: git_branch,
    storage_mode: 'git',
    type: 'appstore',
    team_name: team_id,
    readonly: true,
    output_path: output_path,
    app_identifier: application_id
  )
end

```

##### Command executed

I ran the lane. `bundle exec fastlane ios keystore_get` 

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
-----------------------------
--- Step: create_keychain ---
-----------------------------
Found keychain '~/Library/Keychains/cicd', creation skipped
If creating a new Keychain DB is required please set the `require_create` option true to cause the action to fail
$ security list-keychains -d user
"~/Library/Keychains/login.keychain-db"
"~/Library/Keychains/cicd-db"
Found keychain '~/Library/Keychains/cicd-db' in list-keychains, adding to search list skipped
  </pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.1                                                           |
| Ruby                        | 2.5.8                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | ~/Projects/foovendor/bundle/ruby/2.5.0/bin/fastlane |
| Host                        | macOS 11.1 (20C69)                                             |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.8/lib                                    |
| OpenSSL Version             | OpenSSL 1.1.1j  16 Feb 2021                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.4                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_AU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
$VERBOSE = nil

import '../../../tools/fastlane/Fastfile'

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.180.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status      |
| ----------------------- | ------- | ------------------ |
| fastlane-plugin-cryptex | 0.1.6   | 🚫 Update available |

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.2.0        |
| bundler                       | 2.2.14       |
| rake                          | 13.0.3       |
| CFPropertyList                | 3.0.3        |
| concurrent-ruby               | 1.1.8        |
| i18n                          | 1.8.9        |
| minitest                      | 5.14.4       |
| thread_safe                   | 0.3.6        |
| tzinfo                        | 1.2.9        |
| activesupport                 | 5.2.4.5      |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| httpclient                    | 2.8.3        |
| json                          | 2.5.1        |
| algoliasearch                 | 1.27.5       |
| artifactory                   | 3.0.15       |
| ast                           | 2.4.2        |
| atomos                        | 0.1.3        |
| awesome_print                 | 1.9.2        |
| aws-eventstream               | 1.1.1        |
| aws-partitions                | 1.444.0      |
| aws-sigv4                     | 1.2.3        |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.113.1      |
| aws-sdk-kms                   | 1.43.0       |
| aws-sdk-s3                    | 1.93.1       |
| babosa                        | 1.0.4        |
| claide                        | 1.0.3        |
| fuzzy_match                   | 2.0.4        |
| nap                           | 1.1.0        |
| netrc                         | 0.11.0       |
| ffi                           | 1.15.0       |
| ethon                         | 0.12.0       |
| typhoeus                      | 1.4.0        |
| cocoapods-core                | 1.10.1       |
| cocoapods-deintegrate         | 1.0.4        |
| cocoapods-downloader          | 1.4.0        |
| cocoapods-plugins             | 1.0.0        |
| cocoapods-search              | 1.0.0        |
| cocoapods-trunk               | 1.5.0        |
| cocoapods-try                 | 1.2.0        |
| colored2                      | 3.1.2        |
| escape                        | 0.0.4        |
| fourflusher                   | 2.3.1        |
| gh_inspector                  | 1.1.3        |
| molinillo                     | 0.6.6        |
| ruby-macho                    | 1.4.0        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| cocoapods                     | 1.10.1       |
| coderay                       | 1.1.3        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander                     | 4.4.6        |
| commander-fastlane            | 4.4.6        |
| deep_merge                    | 1.2.1        |
| dry-core                      | 0.5.0        |
| dry-configurable              | 0.12.1       |
| dry-container                 | 0.7.2        |
| dry-equalizer                 | 0.3.0        |
| dry-initializer               | 3.0.4        |
| dry-logic                     | 1.1.0        |
| dry-inflector                 | 0.2.0        |
| dry-types                     | 1.5.1        |
| dry-schema                    | 1.6.1        |
| dry-validation                | 1.6.0        |
| config                        | 3.0.0        |
| declarative                   | 0.0.20       |
| digest-crc                    | 0.6.3        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| dotenv                        | 2.7.6        |
| emoji_regex                   | 3.2.2        |
| excon                         | 0.79.0       |
| faraday-net_http              | 1.0.1        |
| multipart-post                | 2.0.0        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.3        |
| jwt                           | 2.2.2        |
| memoist                       | 0.16.2       |
| multi_json                    | 1.15.0       |
| os                            | 1.1.1        |
| signet                        | 0.15.0       |
| googleauth                    | 0.16.1       |
| mini_mime                     | 1.1.0        |
| trailblazer-option            | 0.1.0        |
| uber                          | 0.1.0        |
| representable                 | 3.1.0        |
| retriable                     | 3.1.2        |
| google-api-client             | 0.38.0       |
| rexml                         | 3.2.4        |
| webrick                       | 1.7.0        |
| google-apis-core              | 0.3.0        |
| google-apis-iamcredentials_v1 | 0.3.0        |
| google-apis-storage_v1        | 0.3.0        |
| google-cloud-env              | 1.5.0        |
| google-cloud-errors           | 1.1.0        |
| google-cloud-core             | 1.6.0        |
| google-cloud-storage          | 1.31.0       |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| plist                         | 3.6.0        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| simctl                        | 1.6.8        |
| slack-notifier                | 2.3.2        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| word_wrap                     | 1.0.0        |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| xcpretty-travis-formatter     | 1.0.1        |
| fastlane-plugin-cryptex       | 0.1.6        |
| multi_xml                     | 0.6.0        |
| httparty                      | 0.14.0       |
| lastpass                      | 1.7.0        |
| method_source                 | 1.0.0        |
| parallel                      | 1.20.1       |
| parser                        | 3.0.0.0      |
| tty-color                     | 0.6.0        |
| pastel                        | 0.8.0        |
| pry                           | 0.14.0       |
| rainbow                       | 3.0.0        |
| regexp_parser                 | 2.1.1        |
| rodash                        | 3.0.0        |
| rubocop-ast                   | 1.4.1        |
| ruby-progressbar              | 1.11.0       |
| rubocop                       | 1.11.0       |
| semantic                      | 1.6.1        |
| wisper                        | 2.0.1        |
| tty-reader                    | 0.9.0        |
| tty-prompt                    | 0.23.0       |
</details>

*generated on:* **2021-04-13**
</details>

**Comment by Kukurijek** [comment]
Have you tried to delete the keychain manually and create it again with the command ? 
Have you tried to set `require_create` to `true`?

**Comment by airtonix** [comment]
@Kukurijek yes to all of that, but when you open the keychain app.... I still have to right click it and click unlock.

I strongly suspect this is causing some of my frustrating `error 65` situations.

**Comment by airtonix** [comment]
ahhh!!! you know i think perhaps i discovered something incredibly obscure here.

I have a development environment where I mainly use Linux, but and required to build IOS apps with react-native. I refuse to get used to how macosx keyaboard shortcuts work... my muscle memory.. it's just not worth it.

So I use synergy and vscode remote-ssh. Which means i've been running these fastlane cmds in a terminal session over ssh to the macbook pro.

When it gets to the stage of signing it, fail.

Repeat the same fastlane command on the macbookpro in an iterm2 window... success.

what.even.

Is there some kind of option we can pipe in that makes this not annoying ?

**Comment by max-ott** [comment]
This is a known issue on Apple's end. If SSH/VNC is running, some keychain stuff does not work as you expect it. I assume it's something very deep on the OS-level.
