### ISSUE TITLE
Pilot distribute_only: FastlaneCore::BuildWatcher found more than 1 matching build

### ISSUE THREAD

**Issue by andrewclaus** [fastlane/fastlane#18545]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I have previously uploaded a new version to testflight and it has been approved by apple for testing. I now want to distribute that to my external testers group.

Before updating to using the new Apple API key, I used to run this command in my lane to distribute an existing testflight build to my external testers:
`sh "fastlane pilot distribute -g \"External Pilot Testers\""
`

When I updated to the API Key, I was unable to figure out how to pass the API key properly, but I found a parameter in testflight that says it does the same thing, "distribute_only", and used it like so:
```
testflight(
      distribute_only: true,
      groups: ["External Pilot Testers"]
)
```

However this was unable to select the latest build like the documentation states. My workaround is to attempt to get the newest build number myself and pass it to testflight like so:

```
build_number = app_store_build_number(live: false)
testflight(
  distribute_only: true,
  groups: ["External Pilot Testers"],
  build_number: build_number.to_s
)
```

I am worried this will be fragile and would prefer it if testflight handled this for me.

##### Command executed
fastlane external_pilot

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> AClaus@C02D820WMD6N Amrock.AmrockConnect.iOS % fastlane external_pilot
[✔] 🚀 
[15:06:38]: ------------------------------
[15:06:38]: --- Step: default_platform ---
[15:06:38]: ------------------------------
[15:06:38]: Driving the lane 'ios external_pilot' 🚀
[15:06:38]: -----------------------------------------------------
[15:06:38]: --- Step: Switch to ios set_appstore_api_key lane ---
[15:06:38]: -----------------------------------------------------
[15:06:38]: Cruising over to lane 'ios set_appstore_api_key' 🚖
[15:06:38]: ---------------------------------------
[15:06:38]: --- Step: app_store_connect_api_key ---
[15:06:38]: ---------------------------------------
[15:06:38]: Cruising back to lane 'ios external_pilot' 🚘
[15:06:38]: ------------------------
[15:06:38]: --- Step: testflight ---
[15:06:38]: ------------------------
[15:06:38]: Creating authorization token for App Store Connect API
[15:06:41]: Waiting for processing on... app_id: 123456789, app_version: , build_version: , platform: IOS
+------------------+--------------------+
|             Lane Context              |
+------------------+--------------------+
| DEFAULT_PLATFORM | ios                |
| PLATFORM_NAME    | ios                |
| LANE_NAME        | ios external_pilot |
+------------------+--------------------+
[15:06:43]: FastlaneCore::BuildWatcher found more than 1 matching build: 
1.6.9(1281) for IOS - VALID
1.6.9(1279) for IOS - VALID
1.6.9(1276) for IOS - VALID
1.6.9(1275) for IOS - VALID
1.6.9(1274) for IOS - VALID
1.6.9(1273) for IOS - VALID
1.6.9(1272) for IOS - VALID
1.6.9(1271) for IOS - VALID
1.6.9(1270) for IOS - VALID
1.6.9(1269) for IOS - VALID
1.6.8(1240) for IOS - VALID
1.6.8(1233) for IOS - VALID
1.6.8(1227) for IOS - VALID
1.6.8(1219) for IOS - VALID
1.6.7(1203) for IOS - VALID
1.6.6(1193) for IOS - VALID
1.6.5(1183) for IOS - VALID
1.6.5(1173) for IOS - VALID
1.6.4(1158) for IOS - VALID
1.6.3(1134) for IOS - VALID
1.6.2(1118) for IOS - VALID
1.6.1(1078) for IOS - VALID
1.6.0(994) for IOS - VALID
1.5.0(953) for IOS - VALID
1.4.0(873) for IOS - VALID
1.3.0(840) for IOS - VALID
1.1.0(802) for IOS - VALID
1.1.0(797) for IOS - VALID
1.0.0(774) for IOS - VALID
1.0.0(764) for IOS - VALID
1.0.0(761) for IOS - VALID
1.0.0(657) for IOS - VALID

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | default_platform       | 0           |
| 2    | Switch to ios          | 0           |
|      | set_appstore_api_key   |             |
|      | lane                   |             |
| 3    | app_store_connect_api  | 0           |
|      | _key                   |             |
| 💥   | testflight             | 5           |
+------+------------------------+-------------+

[15:06:43]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Traceback (most recent call last):
	35: from /Users/AClaus/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
	34: from /Users/AClaus/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
	33: from /Users/AClaus/.rvm/rubies/ruby-2.6.3/bin/fastlane:23:in `<main>'
	32: from /Users/AClaus/.rvm/rubies/ruby-2.6.3/bin/fastlane:23:in `load'
	31: from /Users/AClaus/.rvm/gems/ruby-2.6.3/gems/fastlane-2.180.1/bin/fastlane:23:in `<top (required)>'
	30: from /Users/AClaus/.rvm/gems/ruby-2.6.3/gems/fastlane-2.180.1/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	29: from /Users/AClaus/.rvm/gems/ruby-2.6.3/gems/fastlane-2.180.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	28: from /Users/AClaus/.rvm/gems/ruby-2.6.3/gems/fastlane-2.180.1/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	27: from /Users/AClaus/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	26: from /Users/AClaus/.rvm/gems/ruby-2.6.3/gems/fastlane-2.180.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	25: from /Users/AClaus/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	24: from /Users/AClaus/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	23: from /Users/AClaus/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	22: from /Users/AClaus/.rvm/gems/ruby-2.6.3/gems/fastlane-2.180.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	21: from /Users/AClaus/.rvm/gems/ruby-2.6.3/gems/fastlane-2.180.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	20: from /Users/AClaus/.rvm/gems/ruby-2.6.3/gems/fastlane-2.180.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	19: from /Users/AClaus/.rvm/gems/ruby-2.6.3/gems/fastlane-2.180.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	18: from /Users/AClaus/.rvm/gems/ruby-2.6.3/gems/fastlane-2.180.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	17: from /Users/AClaus/.rvm/gems/ruby-2.6.3/gems/fastlane-2.180.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	16: from /Users/AClaus/.rvm/gems/ruby-2.6.3/gems/fastlane-2.180.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	15: from Fastfile:169:in `block (2 levels) in parsing_binding'
	14: from /Users/AClaus/.rvm/gems/ruby-2.6.3/gems/fastlane-2.180.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	13: from /Users/AClaus/.rvm/gems/ruby-2.6.3/gems/fastlane-2.180.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	12: from /Users/AClaus/.rvm/gems/ruby-2.6.3/gems/fastlane-2.180.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	11: from /Users/AClaus/.rvm/gems/ruby-2.6.3/gems/fastlane-2.180.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	10: from /Users/AClaus/.rvm/gems/ruby-2.6.3/gems/fastlane-2.180.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	 9: from /Users/AClaus/.rvm/gems/ruby-2.6.3/gems/fastlane-2.180.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	 8: from /Users/AClaus/.rvm/gems/ruby-2.6.3/gems/fastlane-2.180.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 7: from /Users/AClaus/.rvm/gems/ruby-2.6.3/gems/fastlane-2.180.1/fastlane/lib/fastlane/actions/upload_to_testflight.rb:28:in `run'
	 6: from /Users/AClaus/.rvm/gems/ruby-2.6.3/gems/fastlane-2.180.1/pilot/lib/pilot/build_manager.rb:102:in `wait_for_build_processing_to_be_complete'
	 5: from /Users/AClaus/.rvm/gems/ruby-2.6.3/gems/fastlane-2.180.1/fastlane_core/lib/fastlane_core/build_watcher.rb:25:in `wait_for_build_processing_to_be_complete'
	 4: from /Users/AClaus/.rvm/gems/ruby-2.6.3/gems/fastlane-2.180.1/fastlane_core/lib/fastlane_core/build_watcher.rb:25:in `loop'
	 3: from /Users/AClaus/.rvm/gems/ruby-2.6.3/gems/fastlane-2.180.1/fastlane_core/lib/fastlane_core/build_watcher.rb:26:in `block in wait_for_build_processing_to_be_complete'
	 2: from /Users/AClaus/.rvm/gems/ruby-2.6.3/gems/fastlane-2.180.1/fastlane_core/lib/fastlane_core/build_watcher.rb:77:in `matching_build'
	 1: from /Users/AClaus/.rvm/gems/ruby-2.6.3/gems/fastlane-2.180.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/AClaus/.rvm/gems/ruby-2.6.3/gems/fastlane-2.180.1/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': [!] FastlaneCore::BuildWatcher found more than 1 matching build:  (FastlaneCore::Interface::FastlaneCrash)
1.6.9(1281) for IOS - VALID
1.6.9(1279) for IOS - VALID
1.6.9(1276) for IOS - VALID
1.6.9(1275) for IOS - VALID
1.6.9(1274) for IOS - VALID
1.6.9(1273) for IOS - VALID
1.6.9(1272) for IOS - VALID
1.6.9(1271) for IOS - VALID
1.6.9(1270) for IOS - VALID
1.6.9(1269) for IOS - VALID
1.6.8(1240) for IOS - VALID
1.6.8(1233) for IOS - VALID
1.6.8(1227) for IOS - VALID
1.6.8(1219) for IOS - VALID
1.6.7(1203) for IOS - VALID
1.6.6(1193) for IOS - VALID
1.6.5(1183) for IOS - VALID
1.6.5(1173) for IOS - VALID
1.6.4(1158) for IOS - VALID
1.6.3(1134) for IOS - VALID
1.6.2(1118) for IOS - VALID
1.6.1(1078) for IOS - VALID
1.6.0(994) for IOS - VALID
1.5.0(953) for IOS - VALID
1.4.0(873) for IOS - VALID
1.3.0(840) for IOS - VALID
1.1.0(802) for IOS - VALID
1.1.0(797) for IOS - VALID
1.0.0(774) for IOS - VALID
1.0.0(764) for IOS - VALID
1.0.0(761) for IOS - VALID
1.0.0(657) for IOS - VALID </pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.6                                     |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.rvm/rubies/ruby-2.6.3/bin/fastlane       |
| Host                        | Mac OS X 10.15.6 (19G2021)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.3/lib                |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.4                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
require 'spaceship'
default_platform(:ios)

platform :ios do

  lane :external_pilot do |options|
    set_appstore_api_key

    testflight(
      distribute_only: true,
      groups: ["External Pilot Testers"]
    )
  end

  lane :set_appstore_api_key do
    app_store_connect_api_key(
      key_id: "1234567",
      issuer_id: "123456-123456-12356-12356",
      key_filepath: "./AppStoreConnectAPIKey.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false, # optional but may be required if using match/sigh
    )
  end
end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.180.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.3.0        |
| executable-hooks              | 1.6.0        |
| bundler-unload                | 1.0.2        |
| rubygems-bundler              | 1.4.5        |
| bundler                       | 1.17.3       |
| etc                           | 1.0.1        |
| forwardable                   | 1.2.0        |
| rake                          | 13.0.3       |
| CFPropertyList                | 3.0.3        |
| concurrent-ruby               | 1.1.8        |
| i18n                          | 1.8.9        |
| minitest                      | 5.14.4       |
| thread_safe                   | 0.3.6        |
| tzinfo                        | 1.2.9        |
| activesupport                 | 5.2.4.5      |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| httpclient                    | 2.8.3        |
| json                          | 2.5.1        |
| algoliasearch                 | 1.27.5       |
| artifactory                   | 3.0.15       |
| atomos                        | 0.1.3        |
| aws-eventstream               | 1.1.1        |
| aws-partitions                | 1.444.0      |
| aws-sigv4                     | 1.2.3        |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.113.1      |
| aws-sdk-kms                   | 1.43.0       |
| aws-sdk-s3                    | 1.93.1       |
| babosa                        | 1.0.4        |
| claide                        | 1.0.3        |
| clamp                         | 1.3.2        |
| fuzzy_match                   | 2.0.4        |
| nap                           | 1.1.0        |
| netrc                         | 0.11.0       |
| ffi                           | 1.15.0       |
| ethon                         | 0.12.0       |
| typhoeus                      | 1.4.0        |
| cocoapods-core                | 1.10.1       |
| cocoapods-deintegrate         | 1.0.4        |
| cocoapods-downloader          | 1.4.0        |
| cocoapods-plugins             | 1.0.0        |
| cocoapods-search              | 1.0.0        |
| cocoapods-trunk               | 1.5.0        |
| cocoapods-try                 | 1.2.0        |
| colored2                      | 3.1.2        |
| escape                        | 0.0.4        |
| fourflusher                   | 2.3.1        |
| gh_inspector                  | 1.1.3        |
| molinillo                     | 0.6.6        |
| ruby-macho                    | 1.4.0        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| cocoapods                     | 1.10.1       |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| declarative                   | 0.0.20       |
| digest-crc                    | 0.6.3        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| dotenv                        | 2.7.6        |
| emoji_regex                   | 3.2.2        |
| excon                         | 0.79.0       |
| faraday-net_http              | 1.0.1        |
| multipart-post                | 2.0.0        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.3        |
| jwt                           | 2.2.2        |
| memoist                       | 0.16.2       |
| multi_json                    | 1.15.0       |
| os                            | 1.1.1        |
| signet                        | 0.15.0       |
| googleauth                    | 0.16.1       |
| mini_mime                     | 1.1.0        |
| trailblazer-option            | 0.1.1        |
| uber                          | 0.1.0        |
| representable                 | 3.1.1        |
| retriable                     | 3.1.2        |
| google-api-client             | 0.38.0       |
| rexml                         | 3.2.5        |
| webrick                       | 1.7.0        |
| google-apis-core              | 0.3.0        |
| google-apis-iamcredentials_v1 | 0.3.0        |
| google-apis-storage_v1        | 0.3.0        |
| google-cloud-env              | 1.5.0        |
| google-cloud-errors           | 1.1.0        |
| google-cloud-core             | 1.6.0        |
| google-cloud-storage          | 1.31.0       |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| plist                         | 3.6.0        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| simctl                        | 1.6.8        |
| slack-notifier                | 2.3.2        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| word_wrap                     | 1.0.0        |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| xcpretty-travis-formatter     | 1.0.1        |
| mini_portile2                 | 2.5.0        |
| racc                          | 1.5.2        |
| nokogiri                      | 1.11.2       |
| slather                       | 2.7.0        |
</details>

*generated on:* **2021-04-13**
</details> </pre>
</details>

**Comment by AdrianPrice** [comment]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.0.1                                                         |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.0.1 (20B29)                                           |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.3                                                           |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_AU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.180.0 | 🚫 Update available |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.3.0        |
| slack-notifier                | 2.3.2        |
| atomos                        | 0.1.3        |
| CFPropertyList                | 2.3.6        |
| claide                        | 1.0.3        |
| colored2                      | 3.1.2        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| plist                         | 3.6.0        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| multipart-post                | 2.0.0        |
| word_wrap                     | 1.0.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| artifactory                   | 3.0.15       |
| babosa                        | 1.0.4        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| excon                         | 0.79.0       |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday-net_http              | 1.0.1        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.3        |
| gh_inspector                  | 1.1.3        |
| json                          | 2.1.0        |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| xcpretty-travis-formatter     | 1.0.1        |
| dotenv                        | 2.7.6        |
| bundler                       | 1.17.2       |
| simctl                        | 1.6.8        |
| uber                          | 0.1.0        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| mini_mime                     | 1.1.0        |
| multi_json                    | 1.15.0       |
| signet                        | 0.15.0       |
| memoist                       | 0.16.2       |
| os                            | 1.1.1        |
| googleauth                    | 0.16.1       |
| httpclient                    | 2.8.3        |
| google-api-client             | 0.38.0       |
| google-cloud-env              | 1.5.0        |
| google-cloud-errors           | 1.1.0        |
| google-cloud-core             | 1.6.0        |
| rexml                         | 3.1.9        |
| webrick                       | 1.4.2        |
| google-apis-core              | 0.3.0        |
| google-apis-iamcredentials_v1 | 0.3.0        |
| google-apis-storage_v1        | 0.3.0        |
| rake                          | 12.3.2       |
| digest-crc                    | 0.6.3        |
| google-cloud-storage          | 1.31.0       |
| emoji_regex                   | 3.2.2        |
| jmespath                      | 1.4.0        |
| aws-partitions                | 1.442.0      |
| aws-eventstream               | 1.1.1        |
| aws-sigv4                     | 1.2.3        |
| aws-sdk-core                  | 3.113.1      |
| aws-sdk-kms                   | 1.43.0       |
| aws-sdk-s3                    | 1.93.0       |
| jwt                           | 2.2.2        |
| forwardable                   | 1.2.0        |
| logger                        | 1.3.0        |
| date                          | 2.0.0        |
| stringio                      | 0.0.2        |
| zlib                          | 1.0.0        |
| ipaddr                        | 1.2.2        |
| openssl                       | 2.1.2        |
| ostruct                       | 0.1.0        |
| strscan                       | 1.0.0        |
| fileutils                     | 1.1.0        |
| etc                           | 1.0.1        |
| io-console                    | 0.4.7        |
| libxml-ruby                   | 3.1.0        |
| psych                         | 3.1.0        |
| mutex_m                       | 0.1.0        |
</details>


*generated on:* **2021-04-14**
</details>

**Comment by AdrianPrice** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.0.1                                                         |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.0.1 (20B29)                                           |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.3                                                           |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_AU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.180.1 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.3.0        |
| slack-notifier                | 2.3.2        |
| atomos                        | 0.1.3        |
| CFPropertyList                | 2.3.6        |
| claide                        | 1.0.3        |
| colored2                      | 3.1.2        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| plist                         | 3.6.0        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| multipart-post                | 2.0.0        |
| word_wrap                     | 1.0.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| artifactory                   | 3.0.15       |
| babosa                        | 1.0.4        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| excon                         | 0.79.0       |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday-net_http              | 1.0.1        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.3        |
| gh_inspector                  | 1.1.3        |
| json                          | 2.1.0        |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| xcpretty-travis-formatter     | 1.0.1        |
| dotenv                        | 2.7.6        |
| bundler                       | 1.17.2       |
| simctl                        | 1.6.8        |
| uber                          | 0.1.0        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| mini_mime                     | 1.1.0        |
| multi_json                    | 1.15.0       |
| signet                        | 0.15.0       |
| memoist                       | 0.16.2       |
| os                            | 1.1.1        |
| googleauth                    | 0.16.1       |
| httpclient                    | 2.8.3        |
| google-api-client             | 0.38.0       |
| google-cloud-env              | 1.5.0        |
| google-cloud-errors           | 1.1.0        |
| google-cloud-core             | 1.6.0        |
| rexml                         | 3.1.9        |
| webrick                       | 1.4.2        |
| google-apis-core              | 0.3.0        |
| google-apis-iamcredentials_v1 | 0.3.0        |
| google-apis-storage_v1        | 0.3.0        |
| rake                          | 12.3.2       |
| digest-crc                    | 0.6.3        |
| google-cloud-storage          | 1.31.0       |
| emoji_regex                   | 3.2.2        |
| jmespath                      | 1.4.0        |
| aws-partitions                | 1.442.0      |
| aws-eventstream               | 1.1.1        |
| aws-sigv4                     | 1.2.3        |
| aws-sdk-core                  | 3.113.1      |
| aws-sdk-kms                   | 1.43.0       |
| aws-sdk-s3                    | 1.93.0       |
| jwt                           | 2.2.2        |
| forwardable                   | 1.2.0        |
| logger                        | 1.3.0        |
| date                          | 2.0.0        |
| stringio                      | 0.0.2        |
| zlib                          | 1.0.0        |
| ipaddr                        | 1.2.2        |
| openssl                       | 2.1.2        |
| ostruct                       | 0.1.0        |
| strscan                       | 1.0.0        |
| fileutils                     | 1.1.0        |
| etc                           | 1.0.1        |
| io-console                    | 0.4.7        |
| libxml-ruby                   | 3.1.0        |
| psych                         | 3.1.0        |
| mutex_m                       | 0.1.0        |
</details>


*generated on:* **2021-04-14**
</details>

**Comment by max-zaytsev** [comment]
>I was unable to figure out how to pass the API key properly


I just tried running the following command and it worked for me:

`fastlane pilot distribute --app_identifier com.test.app --groups "Beta" --api_key_path ./api_key.json`

api_key.json:

```json
{
	"key_id": "SOMEKEYID",
	"issuer_id": "69aJ45f-kjd0-89e3-e893-5n8i7l15a8d1",
	"key":"LS0tSOMEKEYCONTENTCONVCERTEDTOBASE640tCk1JR1RBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJIa3dkd0lCQVFRZ1pmcDVnZDR3N1ZhkjdhlhLDFJkhlDKJfhldkjfhlKDhflkVFBpS2xPUTZhZ0NnWUlLb1pJemowRELKdhfjlkjHLDKHflkHLDKFFRVHltZVo5TnFYOHJPVgpLeERmFDlkhjlKDHFlkdjhfLKJDHfkjhdfkj1Y4QldZWlRLTHJzSW5nQXDLFJhkjdhfkJHDfkjhd3d1pKakxPS2lYcDh2CnZ4dXUwdWlvCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=",
	"is_key_content_base64":"true"
}
```

Where _key_ is a content of API Key file (.p8) converted to base64

**Comment by andrewclaus** [comment]
Thanks, that would probably work for me. I was trying to pass the hash generated from app_store_connect_api_key to the --api_key parameter

However that is not the main issue, I am calling this action from inside of a fastfile so I would prefer to call the pilot action directly instead of executing a script which calls the action.

It seems like the behavior is different between

`sh "fastlane pilot distribute"`
and
`pilot(distribute_only: true)`

when the documentation says:

> distribute_only | Distribute a previously uploaded build (equivalent to the fastlane pilot distribute command)

**Comment by max-ott** [comment]
@andrewclaus The code is exactly the same, so there should be no difference, maybe just in the way the attributes are formatted or similar. Please note that App Store Connect API and Apple ID use 2 different APIs and you cannot expect that if you change the auth method everything is working 100% exactly the same. 

From the error and your code `build_number.to_s` can be the same for builds on different versions. Please make sure that you always use build + version to look for builds.

**Comment by andrewclaus** [comment]
I think this PR will fix my issue with my core issue: https://github.com/fastlane/fastlane/pull/18710

`distribute_only: true does not automatically select the latest version. `

**Comment by lucgrabowski** [comment]
Hi, @andrewclaus. Was this issue fixed by the PR? Can it be closed?

**Comment by andrewclaus** [comment]
I will update my fast file and report back here on the next upload to the App Store!
