### ISSUE TITLE
Direct local .aar file dependencies are not supported when building an AAR

### ISSUE THREAD

**Issue by archcorsair** [fastlane/fastlane#18549]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

- react-native CLI is able to produce a release build without issues
- android studio is able to produce a release build without issues
- fastlane's `gradle` action failing with errors: (it wasn't before)

Relevant change: Upgraded from RN 0.63 > RN 0.64
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':adobe_react-native-aepassurance:bundleReleaseAar'.
> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :adobe_react-native-aepassurance project caused this error: /Users/<app path>/node_modules/@adobe/react-native-aepassurance/android/libs/aepcorebridge.aar
```

##### Command executed

Gradle command from Fastfile:
<pre>
    gradle(
      task: 'assemble',
      build_type: 'Release',
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => releaseFilePath,
        "android.injected.signing.store.password" => store_password,
        "android.injected.signing.key.alias" => "my-key-alias",
        "android.injected.signing.key.password" => key_password,
      }
    )
</pre>

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>...
> Task :adobe_react-native-acpuserprofile:compileReleaseJavaWithJavac
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 warnings

> Task :adobe_react-native-acpuserprofile:extractReleaseAnnotations
> Task :adobe_react-native-acpuserprofile:mergeReleaseGeneratedProguardFiles UP-TO-DATE
> Task :adobe_react-native-acpuserprofile:mergeReleaseConsumerProguardFiles UP-TO-DATE
> Task :adobe_react-native-acpuserprofile:compileReleaseSources
> Task :expo-permissions:generateReleaseResValues
> Task :expo-permissions:generateReleaseResources
> Task :expo-permissions:packageReleaseResources
> Task :expo-splash-screen:compileReleaseRenderscript NO-SOURCE
> Task :expo-splash-screen:generateReleaseResValues
> Task :expo-splash-screen:generateReleaseResources
> Task :expo-splash-screen:packageReleaseResources
> Task :expo-sqlite:compileReleaseRenderscript NO-SOURCE
> Task :expo-sqlite:generateReleaseResValues
> Task :expo-sqlite:generateReleaseResources
> Task :expo-sqlite:packageReleaseResources
> Task :expo-web-browser:compileReleaseRenderscript NO-SOURCE
> Task :expo-web-browser:generateReleaseResValues
> Task :expo-web-browser:generateReleaseResources
> Task :expo-web-browser:packageReleaseResources
> Task :adobe_react-native-aepassurance:generateReleaseRFile

> Task :adobe_react-native-aepassurance:compileReleaseJavaWithJavac
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings

> Task :adobe_react-native-aepassurance:extractReleaseAnnotations
> Task :adobe_react-native-aepassurance:mergeReleaseGeneratedProguardFiles UP-TO-DATE
> Task :adobe_react-native-aepassurance:mergeReleaseConsumerProguardFiles UP-TO-DATE
> Task :adobe_react-native-aepassurance:compileReleaseSources
> Task :react-native-async-storage_async-storage:compileReleaseRenderscript NO-SOURCE
> Task :react-native-async-storage_async-storage:generateReleaseResValues
> Task :react-native-async-storage_async-storage:generateReleaseResources
> Task :react-native-async-storage_async-storage:packageReleaseResources
> Task :react-native-community_masked-view:compileReleaseRenderscript NO-SOURCE
> Task :react-native-community_masked-view:generateReleaseResValues
> Task :react-native-community_masked-view:generateReleaseResources
> Task :react-native-community_masked-view:packageReleaseResources
> Task :react-native-device-info:compileReleaseRenderscript NO-SOURCE
> Task :react-native-device-info:generateReleaseResValues
> Task :react-native-device-info:generateReleaseResources
> Task :react-native-device-info:packageReleaseResources
> Task :react-native-gesture-handler:compileReleaseRenderscript NO-SOURCE
> Task :react-native-gesture-handler:generateReleaseResValues
> Task :react-native-gesture-handler:generateReleaseResources
> Task :react-native-gesture-handler:packageReleaseResources
> Task :react-native-jw-media-player:compileReleaseRenderscript NO-SOURCE
> Task :react-native-jw-media-player:generateReleaseResValues
> Task :react-native-jw-media-player:generateReleaseResources
> Task :react-native-jw-media-player:packageReleaseResources
> Task :react-native-maps:compileReleaseRenderscript NO-SOURCE
> Task :react-native-maps:generateReleaseResValues
> Task :react-native-maps:generateReleaseResources
> Task :react-native-maps:packageReleaseResources
> Task :react-native-reanimated:compileReleaseRenderscript NO-SOURCE
> Task :react-native-reanimated:generateReleaseResValues
> Task :react-native-reanimated:generateReleaseResources
> Task :react-native-reanimated:packageReleaseResources
> Task :react-native-restart:compileReleaseRenderscript NO-SOURCE
> Task :react-native-restart:generateReleaseResValues
> Task :react-native-restart:generateReleaseResources
> Task :react-native-restart:packageReleaseResources
> Task :react-native-safe-area-context:compileReleaseRenderscript NO-SOURCE
> Task :react-native-safe-area-context:generateReleaseResValues
> Task :react-native-safe-area-context:generateReleaseResources
> Task :react-native-safe-area-context:packageReleaseResources
> Task :react-native-screens:compileReleaseRenderscript NO-SOURCE
> Task :react-native-screens:generateReleaseResValues
> Task :react-native-screens:generateReleaseResources
> Task :react-native-screens:packageReleaseResources
> Task :react-native-svg:compileReleaseRenderscript NO-SOURCE
> Task :react-native-svg:generateReleaseResValues
> Task :react-native-svg:generateReleaseResources
> Task :react-native-svg:packageReleaseResources
> Task :react-native-webview:compileReleaseRenderscript NO-SOURCE
> Task :react-native-webview:generateReleaseResValues
> Task :react-native-webview:generateReleaseResources
> Task :react-native-webview:packageReleaseResources
> Task :unimodules-app-loader:compileReleaseRenderscript NO-SOURCE
> Task :unimodules-app-loader:generateReleaseResValues
> Task :unimodules-app-loader:generateReleaseResources
> Task :unimodules-app-loader:packageReleaseResources
> Task :unimodules-barcode-scanner-interface:compileReleaseRenderscript NO-SOURCE
> Task :unimodules-barcode-scanner-interface:generateReleaseResValues
> Task :unimodules-barcode-scanner-interface:generateReleaseResources
> Task :unimodules-barcode-scanner-interface:packageReleaseResources
> Task :unimodules-camera-interface:compileReleaseRenderscript NO-SOURCE
> Task :unimodules-camera-interface:generateReleaseResValues
> Task :unimodules-camera-interface:generateReleaseResources
> Task :unimodules-camera-interface:packageReleaseResources
> Task :unimodules-constants-interface:compileReleaseRenderscript NO-SOURCE
> Task :unimodules-constants-interface:generateReleaseResValues
> Task :unimodules-constants-interface:generateReleaseResources
> Task :unimodules-constants-interface:packageReleaseResources
> Task :unimodules-core:compileReleaseRenderscript NO-SOURCE
> Task :unimodules-core:generateReleaseResValues
> Task :unimodules-core:generateReleaseResources
> Task :unimodules-core:packageReleaseResources
> Task :unimodules-face-detector-interface:compileReleaseRenderscript NO-SOURCE
> Task :unimodules-face-detector-interface:generateReleaseResValues
> Task :unimodules-face-detector-interface:generateReleaseResources
> Task :unimodules-face-detector-interface:packageReleaseResources
> Task :unimodules-file-system-interface:compileReleaseRenderscript NO-SOURCE
> Task :unimodules-file-system-interface:generateReleaseResValues
> Task :unimodules-file-system-interface:generateReleaseResources
> Task :unimodules-file-system-interface:packageReleaseResources
> Task :unimodules-font-interface:compileReleaseRenderscript NO-SOURCE
> Task :unimodules-font-interface:generateReleaseResValues
> Task :unimodules-font-interface:generateReleaseResources
> Task :unimodules-font-interface:packageReleaseResources
> Task :unimodules-image-loader-interface:compileReleaseRenderscript NO-SOURCE
> Task :unimodules-image-loader-interface:generateReleaseResValues
> Task :unimodules-image-loader-interface:generateReleaseResources
> Task :unimodules-image-loader-interface:packageReleaseResources
> Task :unimodules-permissions-interface:compileReleaseRenderscript NO-SOURCE
> Task :unimodules-permissions-interface:generateReleaseResValues
> Task :unimodules-permissions-interface:generateReleaseResources
> Task :unimodules-permissions-interface:packageReleaseResources
> Task :unimodules-react-native-adapter:compileReleaseRenderscript NO-SOURCE
> Task :unimodules-react-native-adapter:generateReleaseResValues
> Task :unimodules-react-native-adapter:generateReleaseResources
> Task :unimodules-react-native-adapter:packageReleaseResources
> Task :unimodules-sensors-interface:compileReleaseRenderscript NO-SOURCE
> Task :unimodules-sensors-interface:generateReleaseResValues
> Task :unimodules-sensors-interface:generateReleaseResources
> Task :unimodules-sensors-interface:packageReleaseResources
> Task :unimodules-task-manager-interface:compileReleaseRenderscript NO-SOURCE
> Task :unimodules-task-manager-interface:generateReleaseResValues
> Task :unimodules-task-manager-interface:generateReleaseResources
> Task :unimodules-task-manager-interface:packageReleaseResources
> Task :adobe_react-native-acpanalytics:extractDeepLinksRelease
> Task :adobe_react-native-acpcore:extractDeepLinksRelease
> Task :adobe_react-native-acpuserprofile:extractDeepLinksRelease
> Task :adobe_react-native-aepassurance:extractDeepLinksRelease
> Task :app:createReleaseCompatibleScreenManifests
> Task :app:extractDeepLinksRelease
> Task :expo-av:extractDeepLinksRelease
> Task :expo-constants:extractDeepLinksRelease
> Task :adobe_react-native-aepassurance:bundleLibCompileToJarRelease
> Task :expo-error-recovery:extractDeepLinksRelease
> Task :adobe_react-native-acpuserprofile:bundleLibCompileToJarRelease
> Task :expo-file-system:extractDeepLinksRelease
> Task :expo-error-recovery:processReleaseManifest
> Task :expo-font:extractDeepLinksRelease

> Task :expo-file-system:processReleaseManifest
/Users/<app path>/node_modules/react-native-unimodules/node_modules/expo-file-system/android/src/main/AndroidManifest.xml:9:9-20:20 Warning:
	provider#expo.modules.filesystem.FileSystemFileProvider@android:authorities was tagged at AndroidManifest.xml:9 to replace other declarations but no other declaration present

> Task :expo-image-loader:extractDeepLinksRelease
> Task :expo-keep-awake:extractDeepLinksRelease
> Task :expo-image-loader:processReleaseManifest
> Task :expo-linear-gradient:extractDeepLinksRelease
> Task :expo-av:processReleaseManifest
> Task :expo-location:extractDeepLinksRelease
> Task :expo-permissions:extractDeepLinksRelease
> Task :expo-keep-awake:processReleaseManifest
> Task :expo-splash-screen:extractDeepLinksRelease
> Task :expo-permissions:processReleaseManifest
> Task :expo-sqlite:extractDeepLinksRelease
> Task :expo-font:processReleaseManifest
> Task :expo-web-browser:extractDeepLinksRelease
> Task :expo-sqlite:processReleaseManifest
> Task :react-native-async-storage_async-storage:extractDeepLinksRelease
> Task :react-native-community_masked-view:extractDeepLinksRelease
> Task :react-native-async-storage_async-storage:processReleaseManifest
> Task :react-native-device-info:extractDeepLinksRelease
> Task :expo-constants:processReleaseManifest
> Task :react-native-gesture-handler:extractDeepLinksRelease
> Task :react-native-jw-media-player:extractDeepLinksRelease
> Task :react-native-gesture-handler:processReleaseManifest
> Task :react-native-maps:extractDeepLinksRelease
> Task :react-native-jw-media-player:processReleaseManifest
> Task :react-native-reanimated:extractDeepLinksRelease
> Task :react-native-maps:processReleaseManifest
> Task :react-native-restart:extractDeepLinksRelease
> Task :react-native-reanimated:processReleaseManifest
> Task :react-native-safe-area-context:extractDeepLinksRelease
> Task :expo-linear-gradient:processReleaseManifest
> Task :react-native-screens:extractDeepLinksRelease
> Task :react-native-safe-area-context:processReleaseManifest
> Task :react-native-svg:extractDeepLinksRelease
> Task :expo-location:processReleaseManifest
> Task :react-native-webview:extractDeepLinksRelease
> Task :react-native-restart:processReleaseManifest
> Task :unimodules-app-loader:extractDeepLinksRelease
> Task :react-native-webview:processReleaseManifest
> Task :unimodules-barcode-scanner-interface:extractDeepLinksRelease
> Task :unimodules-app-loader:processReleaseManifest
> Task :unimodules-camera-interface:extractDeepLinksRelease
> Task :unimodules-barcode-scanner-interface:processReleaseManifest
> Task :unimodules-constants-interface:extractDeepLinksRelease
> Task :adobe_react-native-acpuserprofile:syncReleaseLibJars
> Task :adobe_react-native-acpuserprofile:bundleReleaseAar
> Task :adobe_react-native-acpuserprofile:assembleRelease
> Task :unimodules-core:extractDeepLinksRelease
> Task :react-native-community_masked-view:processReleaseManifest
> Task :unimodules-face-detector-interface:extractDeepLinksRelease
> Task :unimodules-core:processReleaseManifest
> Task :unimodules-file-system-interface:extractDeepLinksRelease
> Task :unimodules-camera-interface:processReleaseManifest
> Task :unimodules-font-interface:extractDeepLinksRelease
> Task :unimodules-file-system-interface:processReleaseManifest
> Task :unimodules-image-loader-interface:extractDeepLinksRelease
> Task :unimodules-font-interface:processReleaseManifest
> Task :unimodules-permissions-interface:extractDeepLinksRelease
> Task :unimodules-image-loader-interface:processReleaseManifest
> Task :unimodules-react-native-adapter:extractDeepLinksRelease
> Task :unimodules-permissions-interface:processReleaseManifest
> Task :unimodules-face-detector-interface:processReleaseManifest
> Task :unimodules-sensors-interface:extractDeepLinksRelease
> Task :unimodules-task-manager-interface:extractDeepLinksRelease
> Task :unimodules-sensors-interface:processReleaseManifest
> Task :unimodules-task-manager-interface:processReleaseManifest
> Task :adobe_react-native-aepassurance:syncReleaseLibJars
> Task :adobe_react-native-aepassurance:bundleReleaseAar FAILED
> Task :expo-av:parseReleaseLocalResources
> Task :unimodules-react-native-adapter:processReleaseManifest
> Task :expo-av:compileReleaseLibraryResources
> Task :unimodules-constants-interface:processReleaseManifest
> Task :expo-web-browser:processReleaseManifest
> Task :app:mergeReleaseResources
> Task :react-native-device-info:processReleaseManifest
> Task :expo-splash-screen:processReleaseManifest
> Task :react-native-screens:processReleaseManifest
> Task :react-native-svg:processReleaseManifest

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':adobe_react-native-aepassurance:bundleReleaseAar'.
> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :adobe_react-native-aepassurance project caused this error: /Users/<app path>/node_modules/@adobe/react-native-aepassurance/android/libs/aepcorebridge.aar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2m 14s
385 actionable tasks: 339 executed, 46 up-to-date] </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 11.1                                                    |
| Ruby                        | 2.6.6                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.24.3 (Apple Git-128)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.180.1/libexec/bin/fastlane |
| Host                        | macOS 11.1 (20C69)                                      |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.6/2.6.6_1/lib                  |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                              |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 12.4                                                    |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
skip_docs # Do not create fastlane/README on run
slack_url = "******"

default_platform(:android)

platform :android do
  desc "Submit a new Beta Build to Play Store"
  lane :beta do
    confirm = UI.confirm "Have you added a changelog to this release?"
    if !confirm
      UI.user_error!("Please add a changelog for this release and try again")
    end
    ensure_git_status_clean
    store_password = prompt(text: "Signing Store Password: ", secure_text: true)
    key_password = prompt(text: "Alias Key Password: ", secure_text: true)
    releaseFilePath = File.join(Dir.pwd, "..", "my-release-key.keystore")
    increment_version_code # Bumps build number
    gradle(task: 'clean')
    add_badge # Add beta badge to app icon
    gradle(
      task: 'assemble',
      build_type: 'Release',
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => releaseFilePath,
        "android.injected.signing.store.password" => store_password,
        "android.injected.signing.key.alias" => "my-key-alias",
        "android.injected.signing.key.password" => key_password,
      }
    )
    upload_to_play_store(
      track: 'internal',
      apk: 'app/build/outputs/apk/release/app-release.apk'
      )
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    slack(
      slack_url: slack_url,
      message: "Android build successfully published to Google Play Store! :rocket:",
      success: true,
      default_payloads: ["git_branch", "last_git_commit_hash"]
    )
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("key.json") # Path to the json secret file
package_name("com.****")

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.180.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                 | Version | Update-Status |
| -------------------------------------- | ------- | ------------- |
| fastlane-plugin-increment_version_code | 0.4.3   | ✅ Up-To-Date  |
| fastlane-plugin-badge                  | 1.5.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                    | Version      |
| -------------------------------------- | ------------ |
| slack-notifier                         | 2.3.2        |
| atomos                                 | 0.1.3        |
| CFPropertyList                         | 3.0.3        |
| claide                                 | 1.0.3        |
| colored2                               | 3.1.2        |
| nanaimo                                | 0.3.0        |
| xcodeproj                              | 1.19.0       |
| rouge                                  | 2.0.7        |
| xcpretty                               | 0.3.0        |
| terminal-notifier                      | 2.0.0        |
| unicode-display_width                  | 1.7.0        |
| terminal-table                         | 1.8.0        |
| plist                                  | 3.6.0        |
| public_suffix                          | 4.0.6        |
| addressable                            | 2.7.0        |
| multipart-post                         | 2.0.0        |
| word_wrap                              | 1.0.0        |
| tty-screen                             | 0.8.1        |
| tty-cursor                             | 0.7.1        |
| tty-spinner                            | 0.9.3        |
| artifactory                            | 3.0.15       |
| babosa                                 | 1.0.4        |
| colored                                | 1.2          |
| highline                               | 1.7.10       |
| commander-fastlane                     | 4.4.6        |
| excon                                  | 0.79.0       |
| faraday-net_http                       | 1.0.1        |
| ruby2_keywords                         | 0.0.4        |
| faraday                                | 1.3.0        |
| unf_ext                                | 0.0.7.7      |
| unf                                    | 0.1.4        |
| domain_name                            | 0.5.20190701 |
| http-cookie                            | 1.0.3        |
| faraday-cookie_jar                     | 0.0.7        |
| faraday_middleware                     | 1.0.0        |
| fastimage                              | 2.2.3        |
| gh_inspector                           | 1.1.3        |
| json                                   | 2.1.0        |
| mini_magick                            | 4.11.0       |
| naturally                              | 2.2.1        |
| rubyzip                                | 2.3.0        |
| security                               | 0.1.3        |
| xcpretty-travis-formatter              | 1.0.1        |
| dotenv                                 | 2.7.6        |
| bundler                                | 2.2.15       |
| simctl                                 | 1.6.8        |
| jwt                                    | 2.2.2        |
| uber                                   | 0.1.0        |
| declarative                            | 0.0.20       |
| declarative-option                     | 0.1.0        |
| representable                          | 3.0.4        |
| retriable                              | 3.1.2        |
| mini_mime                              | 1.1.0        |
| multi_json                             | 1.15.0       |
| signet                                 | 0.15.0       |
| memoist                                | 0.16.2       |
| os                                     | 1.1.1        |
| googleauth                             | 0.16.1       |
| httpclient                             | 2.8.3        |
| google-api-client                      | 0.38.0       |
| google-cloud-env                       | 1.5.0        |
| google-cloud-errors                    | 1.1.0        |
| google-cloud-core                      | 1.6.0        |
| rexml                                  | 3.1.9        |
| webrick                                | 1.4.2        |
| google-apis-core                       | 0.3.0        |
| google-apis-iamcredentials_v1          | 0.3.0        |
| google-apis-storage_v1                 | 0.3.0        |
| rake                                   | 13.0.3       |
| digest-crc                             | 0.6.3        |
| google-cloud-storage                   | 1.31.0       |
| emoji_regex                            | 3.2.2        |
| jmespath                               | 1.4.0        |
| aws-partitions                         | 1.443.0      |
| aws-eventstream                        | 1.1.1        |
| aws-sigv4                              | 1.2.3        |
| aws-sdk-core                           | 3.113.1      |
| aws-sdk-kms                            | 1.43.0       |
| aws-sdk-s3                             | 1.93.0       |
| forwardable                            | 1.2.0        |
| logger                                 | 1.3.0        |
| date                                   | 2.0.0        |
| stringio                               | 0.0.2        |
| zlib                                   | 1.0.0        |
| ipaddr                                 | 1.2.2        |
| openssl                                | 2.1.2        |
| ostruct                                | 0.1.0        |
| strscan                                | 1.0.0        |
| fileutils                              | 1.1.0        |
| etc                                    | 1.0.1        |
| io-console                             | 0.4.7        |
| psych                                  | 3.1.0        |
| mutex_m                                | 0.1.0        |
| fastlane-plugin-increment_version_code | 0.4.3        |
| badge                                  | 0.13.0       |
| fastlane-plugin-badge                  | 1.5.0        |
</details>

*generated on:* **2021-04-13**
</details>
<details>
<pre>
MacOS Big Sur: 11.1
Android Studio: 4.1.3
React Native: 0.64
Fastlane: 2.180.1
</pre>
build.gradle snippet:
<pre>
buildscript {
    ext {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
        ndkVersion = "20.1.5948944"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath('com.android.tools.build:gradle:4.0.1')
    }
}
</pre>
</details>

**Comment by archcorsair** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 11.1                                                    |
| Ruby                        | 2.6.6                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.24.3 (Apple Git-128)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.180.1/libexec/bin/fastlane |
| Host                        | macOS 11.1 (20C69)                                      |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.6/2.6.6_1/lib                  |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                              |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 12.4                                                    |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
skip_docs # Do not create fastlane/README on run
slack_url = "******"

default_platform(:android)

platform :android do
  desc "Submit a new Beta Build to Play Store"
  lane :beta do
    confirm = UI.confirm "Have you added a changelog to this release?"
    if !confirm
      UI.user_error!("Please add a changelog for this release and try again")
    end
    ensure_git_status_clean
    store_password = prompt(text: "Signing Store Password: ", secure_text: true)
    key_password = prompt(text: "Alias Key Password: ", secure_text: true)
    releaseFilePath = File.join(Dir.pwd, "..", "my-release-key.keystore")
    increment_version_code # Bumps build number
    gradle(task: 'clean')
    add_badge # Add beta badge to app icon
    gradle(
      task: 'assemble',
      build_type: 'Release',
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => releaseFilePath,
        "android.injected.signing.store.password" => store_password,
        "android.injected.signing.key.alias" => "my-key-alias",
        "android.injected.signing.key.password" => key_password,
      }
    )
    upload_to_play_store(
      track: 'internal',
      apk: 'app/build/outputs/apk/release/app-release.apk'
      )
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    slack(
      slack_url: slack_url,
      message: "Android build successfully published to Google Play Store! :rocket:",
      success: true,
      default_payloads: ["git_branch", "last_git_commit_hash"]
    )
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("key.json") # Path to the json secret file
package_name("com.****")

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.180.1 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                                 | Version | Update-Status |
| -------------------------------------- | ------- | ------------- |
| fastlane-plugin-increment_version_code | 0.4.3   | ✅ Up-To-Date  |
| fastlane-plugin-badge                  | 1.5.0   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                                    | Version      |
| -------------------------------------- | ------------ |
| slack-notifier                         | 2.3.2        |
| atomos                                 | 0.1.3        |
| CFPropertyList                         | 3.0.3        |
| claide                                 | 1.0.3        |
| colored2                               | 3.1.2        |
| nanaimo                                | 0.3.0        |
| xcodeproj                              | 1.19.0       |
| rouge                                  | 2.0.7        |
| xcpretty                               | 0.3.0        |
| terminal-notifier                      | 2.0.0        |
| unicode-display_width                  | 1.7.0        |
| terminal-table                         | 1.8.0        |
| plist                                  | 3.6.0        |
| public_suffix                          | 4.0.6        |
| addressable                            | 2.7.0        |
| multipart-post                         | 2.0.0        |
| word_wrap                              | 1.0.0        |
| tty-screen                             | 0.8.1        |
| tty-cursor                             | 0.7.1        |
| tty-spinner                            | 0.9.3        |
| artifactory                            | 3.0.15       |
| babosa                                 | 1.0.4        |
| colored                                | 1.2          |
| highline                               | 1.7.10       |
| commander-fastlane                     | 4.4.6        |
| excon                                  | 0.79.0       |
| faraday-net_http                       | 1.0.1        |
| ruby2_keywords                         | 0.0.4        |
| faraday                                | 1.3.0        |
| unf_ext                                | 0.0.7.7      |
| unf                                    | 0.1.4        |
| domain_name                            | 0.5.20190701 |
| http-cookie                            | 1.0.3        |
| faraday-cookie_jar                     | 0.0.7        |
| faraday_middleware                     | 1.0.0        |
| fastimage                              | 2.2.3        |
| gh_inspector                           | 1.1.3        |
| json                                   | 2.1.0        |
| mini_magick                            | 4.11.0       |
| naturally                              | 2.2.1        |
| rubyzip                                | 2.3.0        |
| security                               | 0.1.3        |
| xcpretty-travis-formatter              | 1.0.1        |
| dotenv                                 | 2.7.6        |
| bundler                                | 2.2.15       |
| simctl                                 | 1.6.8        |
| jwt                                    | 2.2.2        |
| uber                                   | 0.1.0        |
| declarative                            | 0.0.20       |
| declarative-option                     | 0.1.0        |
| representable                          | 3.0.4        |
| retriable                              | 3.1.2        |
| mini_mime                              | 1.1.0        |
| multi_json                             | 1.15.0       |
| signet                                 | 0.15.0       |
| memoist                                | 0.16.2       |
| os                                     | 1.1.1        |
| googleauth                             | 0.16.1       |
| httpclient                             | 2.8.3        |
| google-api-client                      | 0.38.0       |
| google-cloud-env                       | 1.5.0        |
| google-cloud-errors                    | 1.1.0        |
| google-cloud-core                      | 1.6.0        |
| rexml                                  | 3.1.9        |
| webrick                                | 1.4.2        |
| google-apis-core                       | 0.3.0        |
| google-apis-iamcredentials_v1          | 0.3.0        |
| google-apis-storage_v1                 | 0.3.0        |
| rake                                   | 13.0.3       |
| digest-crc                             | 0.6.3        |
| google-cloud-storage                   | 1.31.0       |
| emoji_regex                            | 3.2.2        |
| jmespath                               | 1.4.0        |
| aws-partitions                         | 1.443.0      |
| aws-eventstream                        | 1.1.1        |
| aws-sigv4                              | 1.2.3        |
| aws-sdk-core                           | 3.113.1      |
| aws-sdk-kms                            | 1.43.0       |
| aws-sdk-s3                             | 1.93.0       |
| forwardable                            | 1.2.0        |
| logger                                 | 1.3.0        |
| date                                   | 2.0.0        |
| stringio                               | 0.0.2        |
| zlib                                   | 1.0.0        |
| ipaddr                                 | 1.2.2        |
| openssl                                | 2.1.2        |
| ostruct                                | 0.1.0        |
| strscan                                | 1.0.0        |
| fileutils                              | 1.1.0        |
| etc                                    | 1.0.1        |
| io-console                             | 0.4.7        |
| psych                                  | 3.1.0        |
| mutex_m                                | 0.1.0        |
| fastlane-plugin-increment_version_code | 0.4.3        |
| badge                                  | 0.13.0       |
| fastlane-plugin-badge                  | 1.5.0        |
</details>


*generated on:* **2021-04-13**
</details>

**Comment by max-ott** [comment]
Are you able to build it with `gradle` in general? It's not "our" or "fastlane's" gradle. It's just gradle AFAIK, which is probably failing here.

**Comment by archcorsair** [comment]
Appears that this problem was related to the package itself, has been resolved in: https://github.com/adobe/react-native-aepassurance/issues/13

Thank you!
