### ISSUE TITLE
upload_to_play_store_internal_app_sharing auto upload redundant apks 

### ISSUE THREAD

**Issue by maphongba008** [fastlane/fastlane#18557]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
As you can see in the fastfile, I just build an aab file and want to upload it to GG Internal app sharing, but action `upload_to_play_store_internal_app_sharing` auto fill all apk path and cause the error that the package name mismatch. After I take a look on the source code of `upload_to_play_store_internal_app_sharing` https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/upload_to_play_store_internal_app_sharing.rb, it put all apks from fastlane context (attached below)

```
 # If no APK params were provided, try to fill in the values from lane context, preferring
        # the multiple APKs over the single APK if set.
        if params[:apk_paths].nil? && params[:apk].nil?
          all_apk_paths = Actions.lane_context[SharedValues::GRADLE_ALL_APK_OUTPUT_PATHS] || []
          if all_apk_paths.size > 1
            params[:apk_paths] = all_apk_paths
          else
            params[:apk] = Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
          end
        end
```

The workaround for me is just delete the `android/app/builds` folder before release a new build, but it's not a long term solution since I want to store the history of releases. 

##### Command executed
fastlane qa_store

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.4                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.4 (19E2269)                                     |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.5                                                           |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform(:android)

platform :android do

  desc "Submit a new Internal Build to Google PlayStore"
  lane :qa_store do
    gradle(task: "bundleQaRelease")
    version = get_version_name(
        gradle_file_path:"app/build.gradle",
        ext_constant_name:"versionName"
    )
    build_number = get_version_name(
        gradle_file_path:"app/build.gradle",
        ext_constant_name:"versionCode"
    )
    fileName = "qa-v#{build_number}.aab"
    sh("pwd")
    destination = "../app/build/outputs/bundle/qaRelease/#{fileName}"
    sh("mv", "../app/build/outputs/bundle/qaRelease/app-qa-release.aab", destination)
    path = upload_to_play_store_internal_app_sharing(
        package_name: '*******',
        json_key: 'secret.json',
        aab: "./app/build/outputs/bundle/qaRelease/#{fileName}",
    )
    slack(
      message: "Successfully upload a new build to Google Play Store",
      slack_url: '***,
      payload: {  
        "Version" => "#{version}(#{build_number})",
        "Commit" => "#{last_git_commit()[:abbreviated_commit_hash]}",
        "Url" => path,
      },
      default_payloads: [],
    )
  end

end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.179.0 | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                           | Version | Update-Status |
| -------------------------------- | ------- | ------------- |
| fastlane-plugin-get_version_name | 0.2.2   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                              | Version      |
| -------------------------------- | ------------ |
| did_you_mean                     | 1.3.0        |
| slack-notifier                   | 2.3.2        |
| rouge                            | 2.0.7        |
| xcpretty                         | 0.3.0        |
| terminal-notifier                | 2.0.0        |
| unicode-display_width            | 1.7.0        |
| terminal-table                   | 1.8.0        |
| addressable                      | 2.7.0        |
| multipart-post                   | 2.0.0        |
| word_wrap                        | 1.0.0        |
| tty-screen                       | 0.8.1        |
| tty-cursor                       | 0.7.1        |
| tty-spinner                      | 0.9.3        |
| artifactory                      | 3.0.15       |
| colored                          | 1.2          |
| highline                         | 1.7.10       |
| commander-fastlane               | 4.4.6        |
| faraday_middleware               | 1.0.0        |
| gh_inspector                     | 1.1.3        |
| rubyzip                          | 2.3.0        |
| security                         | 0.1.3        |
| dotenv                           | 2.7.6        |
| bundler                          | 1.17.2       |
| simctl                           | 1.6.8        |
| uber                             | 0.1.0        |
| declarative                      | 0.0.20       |
| declarative-option               | 0.1.0        |
| representable                    | 3.0.4        |
| retriable                        | 3.1.2        |
| mini_mime                        | 1.0.2        |
| httpclient                       | 2.8.3        |
| google-api-client                | 0.38.0       |
| nanaimo                          | 0.3.0        |
| colored2                         | 3.1.2        |
| claide                           | 1.0.3        |
| CFPropertyList                   | 3.0.3        |
| atomos                           | 0.1.3        |
| xcodeproj                        | 1.19.0       |
| plist                            | 3.6.0        |
| public_suffix                    | 4.0.6        |
| babosa                           | 1.0.4        |
| excon                            | 0.79.0       |
| unf_ext                          | 0.0.7.7      |
| unf                              | 0.1.4        |
| domain_name                      | 0.5.20190701 |
| http-cookie                      | 1.0.3        |
| ruby2_keywords                   | 0.0.4        |
| faraday-net_http                 | 1.0.1        |
| faraday                          | 1.3.0        |
| faraday-cookie_jar               | 0.0.7        |
| fastimage                        | 2.2.2        |
| json                             | 2.5.1        |
| mini_magick                      | 4.11.0       |
| naturally                        | 2.2.1        |
| xcpretty-travis-formatter        | 1.0.1        |
| jwt                              | 2.2.2        |
| multi_json                       | 1.15.0       |
| signet                           | 0.14.1       |
| os                               | 1.1.1        |
| memoist                          | 0.16.2       |
| googleauth                       | 0.15.1       |
| rake                             | 13.0.3       |
| digest-crc                       | 0.6.3        |
| webrick                          | 1.7.0        |
| rexml                            | 3.2.4        |
| google-apis-core                 | 0.2.1        |
| google-apis-storage_v1           | 0.2.0        |
| google-apis-iamcredentials_v1    | 0.1.0        |
| google-cloud-errors              | 1.0.1        |
| google-cloud-env                 | 1.4.0        |
| google-cloud-core                | 1.5.0        |
| google-cloud-storage             | 1.30.0       |
| emoji_regex                      | 3.2.2        |
| aws-eventstream                  | 1.1.0        |
| aws-sigv4                        | 1.2.2        |
| aws-partitions                   | 1.428.0      |
| jmespath                         | 1.4.0        |
| aws-sdk-core                     | 3.112.0      |
| aws-sdk-kms                      | 1.42.0       |
| aws-sdk-s3                       | 1.88.1       |
| forwardable                      | 1.2.0        |
| logger                           | 1.3.0        |
| date                             | 2.0.0        |
| stringio                         | 0.0.2        |
| zlib                             | 1.0.0        |
| ipaddr                           | 1.2.2        |
| openssl                          | 2.1.2        |
| ostruct                          | 0.1.0        |
| strscan                          | 1.0.0        |
| fileutils                        | 1.1.0        |
| etc                              | 1.0.1        |
| io-console                       | 0.4.7        |
| libxml-ruby                      | 3.1.0        |
| psych                            | 3.1.0        |
| mutex_m                          | 0.1.0        |
| fastlane-plugin-get_version_name | 0.2.2        |
</details>

*generated on:* **2021-04-15**
</details>

**Comment by Martha-20330** [comment]
Upload metadata, screenshots and binaries to Google Play (via supply) Features • Setup • Quick Start • Commands • Uploading an APK • Uploading an Google Play will automatically deactivate a release from its previous track on promote.
