### ISSUE TITLE
deliver upload ipa success, but double screenshots in appstore connect。 

### ISSUE THREAD

**Issue by LittleXu** [fastlane/fastlane#18556]
如题所示，我使用fastlane deliver上传到苹果商店
第一次因为version没有改上传失败
第二次修改之后上传成功
但是appstoreconnect里面的图片却从5张变成了10张
而且少了一部分关键词和隐私政策。

**Comment by rogerluan** [comment]
Please follow our issue template provided at the moment you open an issue. Also, please provide details in English so more people can understand and collaborate.
