### ISSUE TITLE
fastlane deliver init fails with undefined method `get_app_info_localizations' for nil:NilClass

### ISSUE THREAD

**Issue by muralikrish91** [fastlane/fastlane#18565]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I was trying to initialize deliver for the iOS project but ended up with the error undefined method `get_app_info_localizations' for nil:NilClass

##### Command executed
`fastlane deliver init`

##### Complete output when running fastlane, including the stack trace and command used
Traceback (most recent call last):
	16: from /Users/murali/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
	15: from /Users/murali/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
	14: from /Users/murali/.rvm/gems/ruby-2.6.3/bin/fastlane:23:in `<main>'
	13: from /Users/murali/.rvm/gems/ruby-2.6.3/bin/fastlane:23:in `load'
	12: from /Users/murali/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.180.1/bin/fastlane:23:in `<top (required)>'
	11: from /Users/murali/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	10: from /Users/murali/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.180.1/deliver/lib/deliver/commands_generator.rb:17:in `start'
	 9: from /Users/murali/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.180.1/deliver/lib/deliver/commands_generator.rb:186:in `run'
	 8: from /Users/murali/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	 7: from /Users/murali/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.180.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 6: from /Users/murali/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 5: from /Users/murali/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 4: from /Users/murali/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 3: from /Users/murali/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.180.1/deliver/lib/deliver/commands_generator.rb:118:in `block (2 levels) in run'
	 2: from /Users/murali/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.180.1/deliver/lib/deliver/setup.rb:20:in `run'
	 1: from /Users/murali/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.180.1/deliver/lib/deliver/setup.rb:48:in `generate_deliver_file'
/Users/murali/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.180.1/deliver/lib/deliver/setup.rb:70:in `generate_metadata_files': undefined method `get_app_info_localizations' for nil:NilClass (NoMethodError)
	16: from /Users/murali/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
	15: from /Users/murali/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
	14: from /Users/murali/.rvm/gems/ruby-2.6.3/bin/fastlane:23:in `<main>'
	13: from /Users/murali/.rvm/gems/ruby-2.6.3/bin/fastlane:23:in `load'
	12: from /Users/murali/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.180.1/bin/fastlane:23:in `<top (required)>'
	11: from /Users/murali/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.180.1/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	10: from /Users/murali/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.180.1/deliver/lib/deliver/commands_generator.rb:17:in `start'
	 9: from /Users/murali/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.180.1/deliver/lib/deliver/commands_generator.rb:186:in `run'
	 8: from /Users/murali/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	 7: from /Users/murali/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.180.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 6: from /Users/murali/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 5: from /Users/murali/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 4: from /Users/murali/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 3: from /Users/murali/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.180.1/deliver/lib/deliver/commands_generator.rb:118:in `block (2 levels) in run'
	 2: from /Users/murali/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.180.1/deliver/lib/deliver/setup.rb:20:in `run'
	 1: from /Users/murali/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.180.1/deliver/lib/deliver/setup.rb:48:in `generate_deliver_file'
/Users/murali/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.180.1/deliver/lib/deliver/setup.rb:70:in `generate_metadata_files': [!] undefined method `get_app_info_localizations' for nil:NilClass (NoMethodError)

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.6                                     |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.29.2                          |
| Installation Source         | ~/.rvm/gems/ruby-2.6.3/bin/fastlane         |
| Host                        | Mac OS X 10.15.6 (19G2021)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.3/lib                |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.4                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.180.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-appcenter | 1.11.0  | ✅ Up-To-Date  |

**Comment by max-ott** [comment]
You get this usually if Fastlane / Spaceship cannot find the app. Are you 100% sure you have access to it?

**Comment by Robert-3014** [comment]
I definitely enjoyed reading it, you’re a great author.

[]([MyCardStatement](https://www.mycardstatement.me/))
