### ISSUE TITLE
Deliver doesn't upload ios metadata to the Apple Store

### ISSUE THREAD

**Issue by f4aci** [fastlane/fastlane#18576]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Hi,
We have a flutter app which builds 4 different envs: prod, integration, staging and dev.
At the moment I am trying to test the dev env to upload via fastlane the ios metadata to the Apple Store.

Unfortunately after many attempts, it says that the job has been executed successful but no images, icons or content on the Apple Store marketing page.

This is my folder structure:
![Screenshot 2021-04-19 at 20 14 17](https://user-images.githubusercontent.com/74613381/115298689-afe14400-a155-11eb-973d-3e6b13bb499c.png)

##### Command executed

No Errors

### Environment

<details>
  <pre><details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.2.3                                                         |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.2.3 (20D91)                                           |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.4                                                           |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.177.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| artifactory               | 3.0.15       |
| babosa                    | 1.0.4        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.78.1       |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.1.0        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.11.0       |
| naturally                 | 2.2.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.14.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.4.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 12.3.2       |
| digest-crc                | 0.6.2        |
| google-cloud-storage      | 1.29.1       |
| emoji_regex               | 3.2.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.402.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.110.0      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.86.0       |
| bundler                   | 2.1.4        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2021-04-19**
</details></pre>
</details>

This is my ios fastlane file:
````
lane :dev_applestore do
             MY_APP_ID = "xxx.app.dev"
             MY_PROFILE = "match AppStore xxx.app.dev"
             WORKSPACE_PATH = "Runner.xcworkspace"

             match(
                 app_identifier: MY_APP_ID,
                 type: "appstore",
                 readonly: true
             )

             settings_to_override = {
               :BUNDLE_IDENTIFIER => MY_APP_ID,
               :PROVISIONING_PROFILE_SPECIFIER => MY_PROFILE,
             }

             gym(
                 workspace: WORKSPACE_PATH,
                 scheme: "dev",
                 xcargs: settings_to_override,
                 export_method: "app-store",
                 export_options: {
                     provisioningProfiles: {
                         MY_APP_ID => MY_PROFILE
                     }
                 }
             )

             deliver(
                   app_identifier: MY_APP_ID,
                   force: true, # Skip HTMl report verification
                   skip_metadata: false,
                   skip_screenshots: false,
                   skip_binary_upload: true,
                   metadata_path: "./metadata/dev",
                   screenshots_path: "./screenshots",
                   app_icon: "./iTunesArtwork@2x.png",
                   copyright: "#{Time.now.year} XXX SARL"
              )

             upload_to_testflight(app_identifier: MY_APP_ID)
             upload_symbols_to_crashlytics
         end
````

This is the pipeline logs:
````
[19:05:14]: Successfully exported and signed the ipa file:
[19:05:14]: /Users/[hidden]/src/flutter-mob-app/ios/Runner.ipa
[19:05:14]: Using deprecated option: '--app_icon' (Removed after the migration to the new App Store Connect API in June 2020)
[19:05:14]: ---------------------
[19:05:14]: --- Step: deliver ---
[19:05:14]: ---------------------
[19:05:14]: Successfully loaded '/Users/[hidden]/src/flutter-mob-app/ios/fastlane/Deliverfile' 📄
+-----------------------+-----------------------+
| Detected Values from './fastlane/Deliverfile' |
+-----------------------+-----------------------+
| languages             | ["en-US"]             |
+-----------------------+-----------------------+
[19:05:14]: Login to App Store Connect ([hidden])
[19:05:16]: Login successful
+--------------------------------------+------------------------+
|                    deliver 2.180.1 Summary                    |
+--------------------------------------+------------------------+
| app_identifier                       | XXX.app.dev         |
| force                                | true                   |
| skip_metadata                        | false                  |
| skip_screenshots                     | false                  |
| skip_binary_upload                   | true                   |
| metadata_path                        | ./metadata/dev         |
| screenshots_path                     | ./screenshots          |
| app_icon                             | ./iTunesArtwork@2x.png |
| copyright                            | 2021 XXX SARL          |
| app_version                          | 2.4.0                  |
| username                             | [hidden]                  |
| ipa                                  | Runner.ipa             |
| platform                             | ios                    |
| edit_live                            | false                  |
| use_live_version                     | false                  |
| skip_app_version_update              | false                  |
| overwrite_screenshots                | false                  |
| submit_for_review                    | false                  |
| reject_if_possible                   | false                  |
| phased_release                       | false                  |
| reset_ratings                        | false                  |
| team_id                              | [hidden]              |
| dev_portal_team_id                   | [hidden]                  |
| run_precheck_before_submit           | true                   |
| precheck_default_rule_level          | warn                   |
| languages                            | ["en-US"]              |
| ignore_language_directory_validation | false                  |
| precheck_include_in_app_purchases    | true                   |
+--------------------------------------+------------------------+
[19:05:19]: Making sure the latest version on App Store Connect matches '2.4.0'...
[19:05:20]: '2.4.0' is the latest version on App Store Connect
[19:05:22]: Will begin uploading metadata for '2.4.0' on App Store Connect
[19:05:22]: Release type will not be set because neither `automatic_release` nor `auto_release_date` were provided. Please explicitly set one of these options if you need a release type set
[19:05:22]: Uploading metadata to App Store Connect for version
[19:05:30]: Will begin uploading snapshots for '2.4.0' on App Store Connect
[19:05:30]: Starting with the upload of screenshots...
[19:05:31]: Waiting for all the screenshots processed...
[19:05:31]: Successfully uploaded all screenshots
[19:05:31]: Sorting screenshots uploaded...
[19:05:31]: Successfully uploaded screenshots to App Store Connect
````

This is the Deliverfile:
````
# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

languages(['en-US'])
````

By the way, the Android version of fastlane works like a charm and I am able to upload everything on each environment.
Any idea?
Thanks
Matt

````
============= UPDATE 20/Apr/2021
````
I've discovered that if I move the files from inside the custom metadata_path: "./metadata/dev",  into /metadata/, fastlane is able to trigger the upload (but now I have another issue, see down below).
The question now is: "is it possible to use envs on the custom metadata path?". 
If this is possible, why it doesn't work in my case? I need to be able to change text and screenshot dynamically on commits for all envs separately.
Is it a bug or it's me using the ```` metadata_path: "./metadata/dev" ```` incorrectly?

Now that I have been able to push some text, I get this error:
````
[17:12:11]: The provided entity includes an attribute with a value that has already been used on this account. - The app name you entered is already being used for another app in your account. If you would like to use the name for this app you will need to submit an update to your other app to change the name, or remove it from App Store Connect. - /data/attributes/name
````
I've found this: https://stackoverflow.com/questions/57899931/app-name-is-unavailable-after-removing-it-from-one-account-while-in-beta-in-apps
But I don't understand why I get this error since I should be able to dynamically change titles, images etc.. the same way I do it for the Google Store.

Am I missing something?
Thanks
Matt

**Comment by f4aci** [comment]
Anyone with this kind of issue or suggest if something is wrong in the code I'm using? I've run out of options to try. Help is much appreciated. Thank you

**Comment by f4aci** [comment]
Update:
I've discovered that by using the custom URL for the metadata: metadata_path: "./metadata/dev", doesn't work. 
What I did was to move all the files outside the /dev/ and put them directly into /metadata/

**Comment by devolab** [comment]
I've found another issue logged but an engineer which is exactly the same as the one I have: https://github.com/fastlane/fastlane/issues/16555
Can anyone look into it?

**Comment by max-ott** [comment]
@devolab I have no idea what you want from me.
