### ISSUE TITLE
Your session has expired.  Please log in.

### ISSUE THREAD

**Issue by kelokchan** [fastlane/fastlane#18574]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I was trying to generate a app specific password when running `pilot`. When I accessed `https://appleid.apple.com/`, Apple prompted me to change my password. And then I removed the deliver keychain password. But I'm constantly getting `Your session has expired.  Please log in.` error. I have already run `fastlane fastlane-credentials remove --username` too. None of them worked. 

I was able login to my account in XCode and Mac System Preference with the new password just fine. I'm not sure what went wrong. I even reinstalled `fastlane` using `brew` 

##### Command executed

`fastlane sigh`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>```❯ fastlane sigh
[✔] 🚀
[18:23:29]: fastlane detected a Gemfile in the current directory
[18:23:29]: However, it seems like you didn't use `bundle exec`
[18:23:29]: To launch fastlane faster, please use
[18:23:29]:
[18:23:29]: $ bundle exec fastlane sigh
[18:23:29]:
[18:23:29]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

+-------------------------------------+-------+
|          Summary for sigh 2.180.1           |
+-------------------------------------+-------+
| adhoc                               | false |
| developer_id                        | false |
| development                         | false |
| skip_install                        | false |
| force                               | false |
| ignore_profiles_with_different_name | false |
| skip_fetch_profiles                 | false |
| skip_certificate_verification       | false |
| platform                            | ios   |
| readonly                            | false |
| fail_on_name_taken                  | false |
+-------------------------------------+-------+

[18:23:30]: To not be asked about this value, you can specify it using 'username'
/opt/homebrew/Cellar/fastlane/2.180.1_1/libexec/gems/highline-1.7.10/lib/highline.rb:624: warning: Using the last argument as keyword parameters is deprecated
[18:23:30]: Your Apple ID Username: xxx
[18:23:35]: Starting login with user 'xxx'
-------------------------------------------------------------------------------------
Please provide your Apple Developer Program account credentials
The login information you enter will be stored in your macOS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` environment variable
See more information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
-------------------------------------------------------------------------------------
/opt/homebrew/Cellar/fastlane/2.180.1_1/libexec/gems/highline-1.7.10/lib/highline.rb:624: warning: Using the last argument as keyword parameters is deprecated
/opt/homebrew/Cellar/fastlane/2.180.1_1/libexec/gems/highline-1.7.10/lib/highline.rb:624: warning: Using the last argument as keyword parameters is deprecated

Looking for related GitHub issues on fastlane/fastlane...

➡️  Pilot and deliver fails with "string contains null byte"
    https://github.com/fastlane/fastlane/issues/18312 [closed] 6 💬
    6 weeks ago

➡️  Having deliver/upload_to_app_store issues? Install 2.150.0.rc5
    https://github.com/fastlane/fastlane/issues/16639 [closed] 116 💬
    04 Sep 2020

➡️  code sign errors while building the app
    https://github.com/fastlane/fastlane/issues/13779 [closed] 17 💬
    01 Aug 2019

and 22 more at: https://github.com/fastlane/fastlane/search?q=Apple%20provided%20the%20following%20error%20info%3A%0A%09Your%20session%20has%20expired.%20%20Please%20log%20in.&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.

[!] Apple provided the following error info:
	Your session has expired.  Please log in.</pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                        |
| --------------------------- | ------------------------------------------------------------ |
| OS                          | 11.1                                                         |
| Ruby                        | 2.7.3                                                        |
| Bundler?                    | false                                                        |
| Git                         | git version 2.24.3 (Apple Git-128)                           |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.180.1_1/libexec/bin/fastlane |
| Host                        | macOS 11.1 (20C69)                                           |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby@2.7/2.7.3/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                                  |
| Is contained                | false                                                        |
| Is homebrew                 | true                                                         |
| Is installed via Fabric.app | false                                                        |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                  |
| Xcode Version               | 12.4                                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.180.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.4.0        |
| slack-notifier                | 2.3.2        |
| atomos                        | 0.1.3        |
| CFPropertyList                | 3.0.3        |
| claide                        | 1.0.3        |
| colored2                      | 3.1.2        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| plist                         | 3.6.0        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| multipart-post                | 2.0.0        |
| word_wrap                     | 1.0.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| artifactory                   | 3.0.15       |
| babosa                        | 1.0.4        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.3        |
| gh_inspector                  | 1.1.3        |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| xcpretty-travis-formatter     | 1.0.1        |
| dotenv                        | 2.7.6        |
| bundler                       | 2.2.15       |
| simctl                        | 1.6.8        |
| jwt                           | 2.2.2        |
| uber                          | 0.1.0        |
| declarative                   | 0.0.20       |
| trailblazer-option            | 0.1.1        |
| representable                 | 3.1.1        |
| retriable                     | 3.1.2        |
| mini_mime                     | 1.1.0        |
| multi_json                    | 1.15.0       |
| signet                        | 0.15.0       |
| memoist                       | 0.16.2       |
| os                            | 1.1.1        |
| googleauth                    | 0.16.1       |
| httpclient                    | 2.8.3        |
| google-api-client             | 0.38.0       |
| google-cloud-env              | 1.5.0        |
| google-cloud-errors           | 1.1.0        |
| google-cloud-core             | 1.6.0        |
| google-apis-core              | 0.3.0        |
| google-apis-iamcredentials_v1 | 0.3.0        |
| google-apis-storage_v1        | 0.3.0        |
| rake                          | 13.0.3       |
| digest-crc                    | 0.6.3        |
| google-cloud-storage          | 1.31.0       |
| emoji_regex                   | 3.2.2        |
| jmespath                      | 1.4.0        |
| aws-eventstream               | 1.1.1        |
| aws-sigv4                     | 1.2.3        |
| aws-sdk-core                  | 3.114.0      |
| aws-sdk-kms                   | 1.43.0       |
| aws-sdk-s3                    | 1.93.1       |
| uri                           | 0.10.0       |
| excon                         | 0.80.1       |
| ruby2_keywords                | 0.0.4        |
| faraday-net_http_persistent   | 1.1.0        |
| faraday-net_http              | 1.0.1        |
| faraday-excon                 | 1.1.0        |
| faraday                       | 1.4.1        |
| json                          | 2.5.1        |
| rexml                         | 3.2.5        |
| webrick                       | 1.7.0        |
| aws-partitions                | 1.445.0      |
| forwardable                   | 1.3.1        |
| logger                        | 1.4.2        |
| cgi                           | 0.1.0        |
| date                          | 3.0.0        |
| timeout                       | 0.1.0        |
| stringio                      | 0.1.0        |
| zlib                          | 1.1.0        |
| ipaddr                        | 1.2.2        |
| openssl                       | 2.1.2        |
| ostruct                       | 0.2.0        |
| strscan                       | 1.0.3        |
| delegate                      | 0.1.0        |
| fileutils                     | 1.4.1        |
| io-console                    | 0.5.6        |
| open3                         | 0.1.0        |
| singleton                     | 0.1.0        |
| yaml                          | 0.1.0        |
| psych                         | 3.1.0        |
| mutex_m                       | 0.1.0        |
</details>

*generated on:* **2021-04-19**
</details>

**Comment by kelokchan** [comment]
Everything works as usual after trying again in 1 hour. Closing this issue

**Comment by ravik2015** [comment]
Any solution for this  issue? I got stuck around here from last couple of hours

**Comment by berkhulagu** [comment]
All of a sudden, this started happening. Let's wait a couple of hours and see what happens

**Comment by berkhulagu** [comment]
It automatically started working after 15 minutes
