### ISSUE TITLE
MATCH does not comply with Apple (developer) profiles for iOS Apps running on Apple Silicon (M1)

### ISSUE THREAD

**Issue by Carlit0** [fastlane/fastlane#18581]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
To be able to run iOS Apps on Apple Silicon / M1 (Target: _My Mac (Designed for iPad)_)  you have to enable "_include Mac devices_" and include the desired device in the Apple Developer Profile.
Of course, the **UDID** of the M1-device had to be registered beforehand :)

However, if If I run `fastlane match` with `--force_for_new_devices` or `--force` the previously included device gets **deselected/excluded** from the profile and there is no option to avoid it.
btw: The enabled "_include Mac devices_" switch stays enabled in the profile.

So in short: `fastlane match` with `--force_for_new_devices` or `--force` filters out all macos devices on an iOS profile even though we want them to be included to be able to run iOS Apps on Target: _My Mac (Designed for iPad)_

related to #17690

##### Command executed
`fastlane match` with `--force_for_new_devices` or `--force`

##### Complete output when running fastlane, including the stack trace and command used

The command executes successfully.

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.2.3                                      |
| Ruby                        | 2.7.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.rbenv/versions/2.7.2/bin/fastlane        |
| Host                        | macOS 11.2.3 (20D91)                        |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.2/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1j  16 Feb 2021                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.4                                        |

</details>

*generated on:* **2021-04-20**

Screenshot of an Apple developer profile highlighting the _"include Mac devices"_ functionality, that `fastlane match` does not comply with:
<img width="750" alt="apple_dev_provisioning_screenshot" src="https://user-images.githubusercontent.com/12805599/115417039-9513db80-a1f8-11eb-9b26-cd87f5d99feb.png">

One additional note:
The registered (M1) macos device is not a "normal" macos device. We have to register the **UDID** of the macos device NOT the UUID. The provisioning UDID looks similar to an iOS UUID but looks completely different from a macos UUID.
</details>

**Comment by patreu22** [comment]
Can confirm that issue, would be great if somebody could look into that :)

**Comment by max-ott** [comment]
As far as I know this is the expected behaviour. `Fastlane` was initially / historically built for mobile / iOS apps. Some Mac app functionalities were available, but most of the time more by accident than by design. (So I consider this more "working as expected" than an actual bug)

Feel free to open a pull-request to add this functionality!

**Comment by Carlit0** [comment]
Hello @max-ott , maybe you got me wrong. I meant running **iOS** Apps. However, with the new Apple Silicon you are able to run iOS Apps on macos natively.
Expected bahaviour would be that I can build for that case.
With `fastlane match` with `--force_for_new_devices` or `--force` this can not be achieved.

**Comment by max-ott** [comment]
It's still a different way than the standard iOS way as you described it yourself. It would definitely be great if that's supported, but it's a feature addition and not a bug.

**Comment by Kylmakalle** [comment]
I Also face this and think it would be a great opportunity to support m1 macs provisioning for iOS apps

**Comment by radko93** [comment]
Is there any workaround for this?

**Comment by Carlit0** [comment]
> Is there any workaround for this?

1) include the device manually and don't run `match` again with `--force_for_new_devices` or `--force`.
2) change fastlane filter locally: https://github.com/fastlane/fastlane/issues/17690#issuecomment-739528204

**Comment by Kylmakalle** [comment]
bump

**Comment by rockylive** [comment]
Bump, M1 still have this issue

**Comment by Kylmakalle** [comment]
M1 Macs are more common now in development.
I will definitely bump this issue once more.

**Comment by CraigSiemens** [comment]
@max-ott This is a feature we'd like as well. Do you have any recommendations for what an acceptable solution would look like?

I did a quick look and it could be setup to always add Mac devices to iOS provisioning profiles, or there could be another flag passed sigh and/or match to `--include-mac-devices`.

**Comment by PoissonBallon** [comment]
Any news about it ? 🙏

**Comment by Kylmakalle** [comment]
👀

**Comment by Kylmakalle** [comment]
We still require this functionality :)

**Comment by taschik** [comment]
Hi, I spend over an hour to figure out why my M1 certificate was not added until I found this thread. Is there any update to this?

**Comment by juliengdt** [comment]
Bump here too. 
Would be awesome to integrate easily our mac's uuid ! +100

**Comment by fonograph** [comment]
Bumpity bump. This just lost me an hour or so.

**Comment by zakkhoyt** [comment]
Bump. Another consumer in need of this functionality.

**Comment by colejd** [comment]
Me too thanks. This is going to be pretty important to support now that Xcode 14 supports single targets that can deploy to multiple platforms.

**Comment by Kylmakalle** [comment]
This definitely should not be closed.
M2 macs are already here and we still not able to automatically provision them 😁

**Comment by maxlapides** [comment]
I think we should keep this issue open. More work is needed to make it easy to manage Apple Silicon Macs in the Apple Developer system.

**Comment by maxlapides** [comment]
I still think we should keep this issue open. More work is needed to make it easy to manage Apple Silicon Macs in the Apple Developer system.

**Comment by cnordvik** [comment]
I think we got away with adding the Mac as ipod in the devices list when registering them 😅 
`00006001-111119920CEB801E	M1MAC	ipod`
