### ISSUE TITLE
[scan] retry feature did not work as expected

### ISSUE THREAD

**Issue by shuguenot** [fastlane/fastlane#18587]
@xavierLowmiller On my side, the retried build fails (see logs below) : "and logs" string seems to cause the issue. Maybe because my app has multiple test targets or has coverage enabled ?
```
Failing tests:
Test session results, code coverage, and logs:
	/Users/admin/.gitlab-runner/builds/ios/xxxx/0/app/fastlane/test_output/App.xcresult
	FunctionalTests:
		TabbarTests.testTabbar()
		MenuTests.testMenu()
** TEST FAILED **
[18:18:36]: Exit status: 65
[18:18:36]: Retrying tests: and logs//Users/admin//gitlab-runner/builds/ios/xxxx/fastlane/test_output/App/xcresult
[18:18:36]: Number of retries remaining: 1
...
[18:19:02]: ▸ xcodebuild: error: Failed to build project Project with scheme App.
[18:19:02]: ▸ 	Reason: Tests in the target “and logs” can’t be run because “and logs” isn’t a member of the specified scheme.
```

_Originally posted by @shuguenot in https://github.com/fastlane/fastlane/issues/17765#issuecomment-823423124_

**Comment by shuguenot** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                              |
| --------------------------- | -------------------------------------------------- |
| OS                          | 11.2.3                                             |
| Ruby                        | 2.7.2                                              |
| Bundler?                    | true                                               |
| Git                         | git version 2.31.1                                 |
| Installation Source         | ~/.rbenv/versions/2.7.2/bin/fastlane               |
| Host                        | macOS 11.2.3 (20D91)                               |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.2/lib                        |
| OpenSSL Version             | OpenSSL 1.1.1j  16 Feb 2021                        |
| Is contained                | false                                              |
| Is homebrew                 | false                                              |
| Is installed via Fabric.app | false                                              |
| Xcode Path                  | /Applications/Xcode_12.5.0.app/Contents/Developer/ |
| Xcode Version               | 12.5                                               |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | fr_FR.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
#-------------------------------------------------------------------------------
# Fastfile
#-------------------------------------------------------------------------------

opt_out_usage
skip_docs
fastlane_version '2.181.0'
default_platform :ios

#-------------------------------------------------------------------------------
# Common
#-------------------------------------------------------------------------------

before_all do |lane|
  ensure_git_status_clean if should_cleanup(lane)
  ENV['GYM_OUTPUT_DIRECTORY'] = 'fastlane/build'
  ENV['SCAN_DERIVED_DATA_PATH'] = 'fastlane/build'
  ENV['DOWNLOAD_DSYMS_OUTPUT_DIRECTORY'] = 'fastlane/dsym'
end

after_all do |lane|
  if should_cleanup(lane)
    reset_git_repo(exclude: ['Packages',
                             'fastlane/test_output',
                             'fastlane/swiftlint.xml',
                             'fastlane/iblinter.xml',
                             ENV['GYM_OUTPUT_DIRECTORY'],
                             ENV['SCAN_DERIVED_DATA_PATH'],
                             ENV['DOWNLOAD_DSYMS_OUTPUT_DIRECTORY']])
  end
end

def should_cleanup(lane)
  !(%i[certificates
       build_app_icon
       optimize_app_icon
       symbols_stable_fetch
       symbols_stable_upload
       symbols_local_upload].include? lane)
end

def before_build(increment_build = true)
  ensure_xcode_version(strict: false)
  make('workspace')
  if increment_build
    build_id = ENV['CI_PIPELINE_ID']
    UI.user_error!('CI_PIPELINE_ID must be provided') unless build_id
    increment_build_number(
      build_number: build_id.to_s
    )
  end
end

#-------------------------------------------------------------------------------
# Tests
#-------------------------------------------------------------------------------

def auth_with_retry(retries: 20)
  session = auth
  if !session.nil?
    session
  elsif retries.positive?
    delay = 15
    UI.message("API auth request failed! Retry in #{delay} seconds... (#{retries} retries left)")
    sleep(delay)
    auth_with_retry(retries: retries - 1)
  else
    UI.user_error!('API auth request failed! Aborting!')
  end
end

def auth
  require 'curb'
  curl = Curl::Easy.new(ENV['TEST_AUTH_URL'])
  curl.ssl_verify_peer = false
  curl.headers['user-agent'] = ENV['TEST_AUTH_USER_AGENT']
  curl.headers['x-disable-debug'] = 'true'
  curl.http_auth_types = :basic
  curl.username = ENV['TEST_USER_IDENTIFIER']
  curl.password = ENV['TEST_USER_PASSWORD']
  begin
    curl.perform
    json = curl.body_str
    if curl.response_code == 200
      puts json
      return json
    elsif curl.response_code == 399
      raise SecurityError.new("2-step authentication is enabled on this test user account (#{curl.username}). Aborting!")
      return nil
    elsif curl.response_code >= 400
      puts json
      return nil
    end
  rescue SecurityError => e
    UI.user_error!(e)
    return nil
  rescue StandardError
    return nil
  end
end

lane :tests do |env|
  UI.user_error!('`device` must be provided') unless env[:device]
  UI.user_error!('`version` must be provided') unless env[:version]
  ENV['TEST_USER_SESSION'] = auth_with_retry unless ENV['TESTS_PREAUTH_DISABLED']
  before_build(
    increment_build: false
  )
  begin
    # https://github.com/fastlane/fastlane/blob/master/scan/lib/scan/options.rb
    run_tests(
      scheme: 'App',
      fail_build: true,
      output_types: '',
      output_style: 'raw',
      result_bundle: true,
      code_coverage: true,
      xcargs: '-quiet -includeScreenshots',
      concurrent_workers: 5,
      max_concurrent_simulators: 5,
      prelaunch_simulator: false,
      destination: "platform=iOS Simulator,name=#{env[:device]},OS=#{env[:version]}",
      cloned_source_packages_path: 'Packages',
      number_of_retries: 2
    )
    Dir.chdir('test_output') do
      # If build succeeds, merge retry result with first result
      if Dir.glob('*.xcresult').size > 1
        sh('mv App.xcresult App-0.xcresult')
        sh('xcrun xcresulttool merge *.xcresult --output-path App.xcresult')
      end
      # Build coverage for GitLab CI
      # https://github.com/ChargePoint/xcparse/blob/master/README.md
      sh('../../.bin/xcparse codecov App.xcresult App')
      sh('xcrun xccov view --report App/action.xccovreport > Coverage.txt')
      sh('head -n 3 Coverage.txt')
      sh('rm -rf App Coverage.txt')
    end
    # Build XML Report for GitLab CI
    # https://github.com/KrauseFx/trainer/blob/master/lib/trainer/options.rb
    trainer(
      path: 'fastlane/test_output',
      output_directory: 'fastlane/test_output',
      fail_build: false # Because the failed tests was retried and succeeds
    )
  rescue
    # Build XML Report for GitLab CI
    # https://github.com/KrauseFx/trainer/blob/master/lib/trainer/options.rb
    trainer(
      path: 'fastlane/test_output',
      output_directory: 'fastlane/test_output',
      fail_build: true
    )
  end
end

#-------------------------------------------------------------------------------
# Build
#-------------------------------------------------------------------------------

lane :staging do |env|
  before_build
  run_match(env, 'adhoc', 'staging')
  add_badge(
    glob: '/fastlane/metadata/app_icon.png',
    no_badge: true,
    shield: "Staging-#{ENV['CI_PIPELINE_ID']}-orange"
  )
  build_app_icon
  gym(
    scheme: 'App',
    configuration: 'Staging',
    export_options: { uploadSymbols: false },
    cloned_source_packages_path: 'Packages'
  )
end

lane :preprod do |env|
  before_build
  run_match(env, 'adhoc', 'preprod')
  add_badge(
    glob: '/fastlane/metadata/app_icon.png',
    no_badge: true,
    shield: "Preprod-#{ENV['CI_PIPELINE_ID']}-blue"
  )
  build_app_icon
  gym(
    scheme: 'App',
    configuration: 'Preprod',
    export_options: { uploadSymbols: false },
    cloned_source_packages_path: 'Packages'
  )
end

lane :stable do |env|
  before_build
  run_match(env, 'appstore', nil)
  gym(
    scheme: 'App',
    configuration: 'Release',
    cloned_source_packages_path: 'Packages'
  )
end

#-------------------------------------------------------------------------------
# Deploy
#-------------------------------------------------------------------------------

def internal_deploy(app)
  firebase_app_distribution(
    app: app,
    groups: 'ios',
    ipa_path: 'fastlane/' + Dir['build/*.ipa'].first,
    release_notes_file: 'fastlane/build_notes.txt'
  )
end

lane :staging_deploy do
  internal_deploy(ENV['FIREBASE_APP_STAGING'])
end

lane :preprod_deploy do
  internal_deploy(ENV['FIREBASE_APP_PREPROD'])
end

lane :stable_deploy do
  apple_key_path = ENV['APPLE_API_KEY'] || File.expand_path('apple-api-key.json')
  UI.user_error!('Missing Apple Store Connect API Key') unless File.exist?(apple_key_path)
  build_notes = sh('cat build_notes.txt')
  upload_to_testflight(
    app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
    api_key_path: apple_key_path,
    changelog: build_notes,
    skip_waiting_for_build_processing: false,
    ipa: 'fastlane/' + Dir['build/*.ipa'].first
  )
end

lane :store_deploy do
  apple_key_path = ENV['APPLE_API_KEY'] || File.expand_path('apple-api-key.json')
  UI.user_error!('Missing Apple Store Connect API Key') unless File.exist?(apple_key_path)
  latest_testflight_build_number(
    api_key_path: apple_key_path
  )
  upload_app_privacy_details_to_app_store(
    json_path: 'fastlane/app_privacy_details.json'
  )
  upload_to_app_store(
    app_version: lane_context[SharedValues::LATEST_TESTFLIGHT_VERSION],
    app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
    api_key_path: apple_key_path,
    submit_for_review: true,
    reject_if_possible: true,
    automatic_release: true,
    phased_release: true,
    skip_binary_upload: true,
    precheck_include_in_app_purchases: false,
    force: true, # Skip HTML report verification
    overwrite_screenshots: true,
    submission_information: {
      add_id_info_uses_idfa: true,
      add_id_info_serves_ads: false,
      add_id_info_tracks_install: true,
      add_id_info_tracks_action: true,
      add_id_info_limits_tracking: true
    }
  )
end

#-------------------------------------------------------------------------------
# Code signing
#-------------------------------------------------------------------------------

lane :certificates do |env|
  run_match(env, 'development', 'dev')
  run_match(env, 'adhoc', 'staging')
  run_match(env, 'adhoc', 'preprod')
  run_match(env, 'appstore', nil)
end

def run_match(env, type, suffix)
  google_key_path = ENV['GOOGLE_CLOUD_API_KEY'] || File.expand_path('code-signing-keys.json')
  UI.user_error!('Missing Google Cloud Key') unless File.exist?(google_key_path)
  apple_key_path = ENV['APPLE_API_KEY'] || File.expand_path('apple-api-key.json')
  UI.user_error!('Missing Apple Store Connect API Key') unless File.exist?(apple_key_path)
  force = env[:force] == true
  app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
  app_identifier += '.' + suffix if suffix
  template_name = ENV['APPLE_PAY_ENTITLEMENTS'] == 'true' && type == 'appstore' ? 'ApplePay In-App Provisioning Distribution' : nil
  sync_code_signing(
    type: type,
    app_identifier: app_identifier,
    api_key_path: apple_key_path,
    storage_mode: 'google_cloud',
    google_cloud_bucket_name: 'ios-' + CredentialsManager::AppfileConfig.try_fetch_value(:team_id).downcase,
    google_cloud_keys_file: google_key_path,
    template_name: template_name,
    force: force,
    readonly: !force
  )
end

#-------------------------------------------------------------------------------
# Debug symbols
#-------------------------------------------------------------------------------

lane :staging_symbols_upload do
  symbols_upload('build', 'staging')
end

lane :preprod_symbols_upload do
  symbols_upload('build', 'preprod')
end

lane :stable_symbols_fetch do |env|
  make('workspace')
  sh('mkdir -p dsym')
  download_dsyms(
    app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
    version: env[:tag] || get_version_number(target: 'App'),
    username: CredentialsManager::AppfileConfig.try_fetch_value(:apple_id),
    team_id: CredentialsManager::AppfileConfig.try_fetch_value(:itc_team_id),
    wait_for_dsym_processing: true,
    wait_timeout: 3000
  )
end

lane :stable_symbols_upload do
  symbols_upload('dsym', 'prod')
end

def symbols_upload(path, env)
  sh('curl -o upload-symbols https://raw.githubusercontent.com/firebase/firebase-ios-sdk/master/Crashlytics/upload-symbols')
  sh('chmod u+x upload-symbols')
  sh("unzip -o '#{path}/*.zip' -d #{path}")
  sh("rm #{path}/*.zip")
  upload_symbols_to_crashlytics(
    binary_path: 'fastlane/upload-symbols',
    gsp_path: 'Project/App/Supporting files/GoogleService-Info~' + env + '.plist',
    dsym_paths: Dir[path + '/*.dSYM'].map { |s| 'fastlane/' + s },
    dsym_worker_threads: 8
  )
end

#-------------------------------------------------------------------------------
# Git Tag
#-------------------------------------------------------------------------------

lane :stable_publish_tag do
  make('workspace')
  version = get_version_number(target: 'App')
  url = "https://git.manager.one/api/v4/projects/#{ENV['CI_PROJECT_ID']}/repository/tags?tag_name=#{version}-#{ENV['CI_PIPELINE_ID']}&ref=#{ENV['CI_COMMIT_SHA']}"
  sh("curl --request POST --silent --show-error --fail --header 'PRIVATE-TOKEN: #{ENV['GITLAB_TOKEN']}' '#{url}'")
end

#-------------------------------------------------------------------------------
# App Icon
#-------------------------------------------------------------------------------

lane :build_app_icon do
  path = 'Project/App/Assets/Assets.xcassets'
  appicon(
    appicon_devices: %i[ipad iphone ios_marketing],
    appicon_path: path
  )
end

lane :optimize_app_icon do
  path = 'Project/App/Assets/Assets.xcassets'
  Dir.chdir('../') do
    sh("imageoptim '#{path}/AppIcon.appiconset/*.png'")
  end
end

#-------------------------------------------------------------------------------
# Utils
#-------------------------------------------------------------------------------

def make(command)
  Dir.chdir('../') do
    sh("make #{command}")
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "one.manager.app"
apple_id "fastlane@saga-corp.net"
team_id "R655RG7RU3"
itc_team_id "118547816"

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.181.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-badge                     | 1.5.0   | ✅ Up-To-Date  |
| fastlane-plugin-trainer                   | 0.4.1   | ✅ Up-To-Date  |
| fastlane-plugin-firebase_app_distribution | 0.2.7   | ✅ Up-To-Date  |
| fastlane-plugin-xchtmlreport              | 0.1.1   | ✅ Up-To-Date  |
| fastlane-plugin-appicon                   | 0.16.0  | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.4.0        |
| bundler                                   | 2.1.4        |
| uri                                       | 0.10.0       |
| rake                                      | 13.0.3       |
| CFPropertyList                            | 3.0.3        |
| public_suffix                             | 4.0.6        |
| addressable                               | 2.7.0        |
| artifactory                               | 3.0.15       |
| atomos                                    | 0.1.3        |
| aws-eventstream                           | 1.1.1        |
| aws-partitions                            | 1.446.0      |
| aws-sigv4                                 | 1.2.3        |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.114.0      |
| aws-sdk-kms                               | 1.43.0       |
| aws-sdk-s3                                | 1.93.1       |
| babosa                                    | 1.0.4        |
| fastimage                                 | 2.2.3        |
| colored                                   | 1.2          |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| dotenv                                    | 2.7.6        |
| emoji_regex                               | 3.2.2        |
| excon                                     | 0.80.1       |
| faraday-excon                             | 1.1.0        |
| faraday-net_http                          | 1.0.1        |
| faraday-net_http_persistent               | 1.1.0        |
| multipart-post                            | 2.0.0        |
| ruby2_keywords                            | 0.0.4        |
| faraday                                   | 1.4.1        |
| unf_ext                                   | 0.0.7.7      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.0.0        |
| gh_inspector                              | 1.1.3        |
| jwt                                       | 2.2.3        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.1        |
| signet                                    | 0.15.0       |
| googleauth                                | 0.16.1       |
| httpclient                                | 2.8.3        |
| mini_mime                                 | 1.1.0        |
| declarative                               | 0.0.20       |
| trailblazer-option                        | 0.1.1        |
| uber                                      | 0.1.0        |
| representable                             | 3.1.1        |
| retriable                                 | 3.1.2        |
| google-api-client                         | 0.38.0       |
| digest-crc                                | 0.6.3        |
| rexml                                     | 3.2.5        |
| webrick                                   | 1.7.0        |
| google-apis-core                          | 0.3.0        |
| google-apis-iamcredentials_v1             | 0.3.0        |
| google-apis-storage_v1                    | 0.3.0        |
| google-cloud-env                          | 1.5.0        |
| google-cloud-errors                       | 1.1.0        |
| google-cloud-core                         | 1.6.0        |
| google-cloud-storage                      | 1.31.0       |
| json                                      | 2.5.1        |
| mini_magick                               | 4.11.0       |
| naturally                                 | 2.2.1        |
| plist                                     | 3.6.0        |
| rubyzip                                   | 2.3.0        |
| security                                  | 0.1.3        |
| simctl                                    | 1.6.8        |
| slack-notifier                            | 2.3.2        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.7.0        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| word_wrap                                 | 1.0.0        |
| claide                                    | 1.0.3        |
| colored2                                  | 3.1.2        |
| nanaimo                                   | 0.3.0        |
| xcodeproj                                 | 1.19.0       |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.1        |
| badge                                     | 0.13.0       |
| curb                                      | 0.9.11       |
| fastlane-plugin-appicon                   | 0.16.0       |
| fastlane-plugin-badge                     | 1.5.0        |
| fastlane-plugin-firebase_app_distribution | 0.2.7        |
| trainer                                   | 0.9.1        |
| fastlane-plugin-trainer                   | 0.4.1        |
| fastlane-plugin-xchtmlreport              | 0.1.1        |
| xcode-install                             | 2.6.8        |
</details>


*generated on:* **2021-04-22**
</details>

**Comment by Cyberbeni** [comment]
Yeah, the `Test session results, code coverage, and logs:` part is sometimes before, sometimes after, sometimes in the middle of the actual part we want to parse. And when it's in the middle, the parsing fails.

**Comment by Cyberbeni** [comment]
A better way would probably be to parse the xcresult file and retry the tests that didn't succeed. That way if a test crashes before it starts, won't be left out from the retries.

**Comment by Raymond-59** [comment]
This is such a great resource that you are providing and you give it away for free.

**Comment by gobetti** [comment]
I suspect we're having this because you use `output_style: 'raw'` and similarly, I use `disable_xcpretty` - possibly the current approach that parses from the console output strongly depends on xcpretty's output.

I can repro this error 100% when using either configuration

**Comment by shuguenot** [comment]
The latest version of fastlane does not fix the problem.

**Comment by daianaiziatovTradeRev** [comment]
I started having the same issue once I've added retry to scan. Here is the output that causing that:
```

[16:00:16]: Exit status: 65
[16:00:16]: Retrying tests: Test session results, code coverage, and logs//Users/theuser/Documents/ado-agent/_work/412/s/fastlane/logs/TheAppQAUITestScheme/xcresult
[16:00:16]: Number of retries remaining: 2
[16:00:16]: $ set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace ./TheApp.xcworkspace -scheme TheAppQAUITestScheme -derivedDataPath /Users/theuser/Library/Developer/Xcode/DerivedData/UITests -destination 'platform=iOS Simulator,id=54014595-FA60-4420-95B0-FBCBE7814C64' -resultBundlePath 'fastlane/logs/TheAppQAUITestScheme-1.xcresult' -enableCodeCoverage YES -only-testing:Test\ session\ results,\ code\ coverage,\ and\ logs//Users/theuser/Documents/ado-agent/_work/412/s/fastlane/logs/TheAppQAUITestScheme/xcresult clean build test | tee '/Users/theuser/Documents/ado-agent/_work/412/s/fastlane/logs/build/TheApp-TheAppQAUITestScheme.log'
[16:00:16]: ▸ Loading...
[16:00:18]: ▸ Command line invocation:
[16:00:18]: ▸     /Applications/Xcode-12.5.1.app/Contents/Developer/usr/bin/xcodebuild -workspace ./TheApp.xcworkspace -scheme TheAppQAUITestScheme -derivedDataPath /Users/theuser/Library/Developer/Xcode/DerivedData/UITests -destination "platform=iOS Simulator,id=54014595-FA60-4420-95B0-FBCBE7814C64" -resultBundlePath fastlane/logs/TheAppQAUITestScheme-1.xcresult -enableCodeCoverage YES "-only-testing:Test session results, code coverage, and logs//Users/theuser/Documents/ado-agent/_work/412/s/fastlane/logs/TheAppQAUITestScheme/xcresult" clean build test
[16:00:18]: ▸ User defaults from command line:
[16:00:18]: ▸     IDEBuildOperationResultBundlePath = /Users/theuser/Documents/ado-agent/_work/412/s/fastlane/logs/TheAppQAUITestScheme-1.xcresult
[16:00:18]: ▸     IDEDerivedDataPathOverride = /Users/theuser/Library/Developer/Xcode/DerivedData/UITests
[16:00:18]: ▸     IDEPackageSupportUseBuiltinSCM = YES
[16:00:18]: ▸     IDETestRunOnlyIdentifiers = (
[16:00:18]: ▸     "Test session results, code coverage, and logs//Users/theuser/Documents/ado-agent/_work/412/s/fastlane/logs/TheAppQAUITestScheme/xcresult"
[16:00:18]: ▸ )

```

as you can see, the reason is that `IDETestRunOnlyIdentifiers` arguments are incorrect, it includes other strings which are most likely haven't been stripped correctly with regex:
>16:00:18]: ▸     IDETestRunOnlyIdentifiers = (
[16:00:18]: ▸     "Test session results, code coverage, and logs//Users/theuser/Documents/ado-agent/_work/412/s/fastlane/logs/TheAppQAUITestScheme/xcresult"
[16:00:18]: ▸ )

So I am just wondering if https://github.com/fastlane/fastlane/issues/18659 and solution https://github.com/fastlane/fastlane/pull/18661 might be the cause for that

This is my lane:
```ruby
lane :uitest do
    reset_simulator_contents
    clear_derived_data(derived_data_path: ENV["DERIVED_DATA_UITEST"])
    sh "rm -rf logs"
    dsym_path = ENV["DERIVED_DATA_UITEST"] + "/Build/Products/Debug-iphonesimulator/TheApp.app.dSYM"
    set_info_plist_value(path: "./TheApp/Info.plist", key: "CFBundleVersion", value: jobId)

    begin
      scan(
        scheme: "TheAppQAUITestScheme",
        output_types: '',
        output_style: 'raw',
        clean: true,
        code_coverage: true,
        device: "iPhone 8",
        include_simulator_logs: false,
        buildlog_path: 'fastlane/logs/build',
        result_bundle: true,
        derived_data_path: ENV["DERIVED_DATA_UITEST"],
        skip_slack: true,
        output_directory: "fastlane/logs",
        number_of_retries: 3
      )
    rescue Exception => exceptionrescue
      begin
        upload_symbols_to_crashlytics(gsp_path: gsp_path_stage, dsym_path: dsym_path)
      rescue
        puts "Can't upload dSym"
      end
      raise exceptionrescue
    end

    slather(build_directory: ENV["DERIVED_DATA_UITEST"])
    upload_symbols_to_crashlytics(gsp_path: gsp_path_stage, dsym_path: dsym_path)
  end
```

**Comment by daianaiziatovTradeRev** [comment]
Also found one more interesting thing, On another CI job the logs are slightly different:
```
Failing tests:
	TheAppQAUITestTarget:
		TheTests.testOne()
		TheTests.testTwo()
		
** TEST FAILED **


Test session results, code coverage, and logs:
	/Users/alexmaslov/Documents/ado-agent/_work/412/s/fastlane/logs/TraderevQAUITestScheme.xcresult

```

so it seems like this part:
```
Failing tests:
	TheAppQAUITestTarget:
		TheTests.testOne()
		TheTests.testTwo()
```
can have some other lines of report in between from another workers 🤔

and it happens more frequently with retry implementation

**Comment by eytanbiala** [comment]
Seeing a possibly similar issue, where on the retry attempt it doesn't actually execute any tests so the result is that all 0 tests pass.
This is the command it's running for the retry:

`set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace ./myapp.xcworkspace -scheme MyAppRelease -derivedDataPath /Users/me/Library/Developer/Xcode/DerivedData/myapp-duyudwfisklykgafeeappfiqzwld -destination 'platform=iOS Simulator,id=B44907A3-0581-44A2-9726-EBFAC6938AA8' -only-testing:MyAppTests/-\[PhoneNumberServiceTests\ testFailure\] build test | tee '/Users/me/Library/Logs/scan/myapp-MyAppRelease.log' | xcpretty  --report html --output '/Users/me/myapp/ios/fastlane/test_output/report.html' --report junit --output '/Users/me/myapp/ios/fastlane/test_output/report.junit' --report junit --output '/var/folders/9r/b23jhd_1345cx1b6bc13gh4m00_98l/T/junit_report20210819-11419-1mf1jqt'`

The test being retried is `-[PhoneNumberServiceTests testFailure]` which should always fail:
```
-(void)testFailure {
  XCTAssertEqual(YES, NO);
}
```

Is the -only-testing param possibly missing some escaping?

**Comment by gobetti** [comment]
still seeing this

```
[17:25:43]: Retrying tests: Test session results, code coverage, and logs//Users/gobetti/Developer/redacted/fastlane/builds/Logs/Test/Run-redacted-2021/09/10_17-23-33--0300/xcresult

...

[17:25:50]: ▸ xcodebuild: error: Failed to build workspace redacted with scheme redacted.
[17:25:50]: ▸ 	Reason: Tests in the target “Test session results, code coverage, and logs” can’t be run because “Test session results, code coverage, and logs” isn’t a member of the specified scheme.
```
