### ISSUE TITLE
MATCH Certificate 'xxxxxxxxxx' (stored in your storage) is not available on the Developer Portal for the user user@email.com

### ISSUE THREAD

**Issue by gelodgreat** [fastlane/fastlane#18591]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When executing this line it always made this match error. 
**MATCH Certificate 'xxxxxxxxxx' (stored in your storage) is not available on the Developer Portal for the user user@email.com**

recently, we've revoked some certificates due to non setting of the certs on the app then, even running on bitrise this occur on our app that the expected behaviour is that it will create new cert and provisioning profile but it didnt happen

 match(
          app_identifier: [app,app],
          type: "appstore",
          verbose: true,
        )

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 11.2.3                                                  |
| Ruby                        | 2.7.3                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.29.2                                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.181.0/libexec/bin/fastlane |
| Host                        | macOS 11.2.3 (20D91)                                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.7/2.7.3/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                             |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 12.4                                                    |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane



# fastlane_require "dotenv"


default_platform(:ios)

platform :ios do
    lane :signing do 
      desc "signing"


        match(
          app_identifier: [ app1, app1.notif],
          type: "appstore",
          verbose: true,
        )

        mapping = Actions.lane_context[
          SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING
        ]

        mapping.each do |prof|
          puts prof
        end 
        
    end

    lane :build do
      begin
        build_ios_app(export_xcargs: "-allowProvisioningUpdates", derived_data_path:"~/Library/Developer/Xcode/DerivedData")
      rescue => exception
        UI.user_error!(exception)
      end
    end

  
    lane :release do
      build
      clear_derived_data
      upload_to_app_store(
        force: true,
        submit_for_review: false,
        skip_binary_upload: false,
        skip_metadata: false,
        skip_screenshots: false,
        description:{"en-US" =>  ENV["APP_STORE_DESCRIPTION"]},
        promotional_text: {"en-US" => ENV["APP_STORE_PROMOTIONAL_TEXT"]},
        privacy_url: {"en-US" => ENV["APP_STORE_PRIVACY_URL"]}, 
        submission_information: {
          add_id_info_limits_tracking: true,
          add_id_info_serves_ads: false,
          add_id_info_tracks_action: true,
          add_id_info_tracks_install: true,
          add_id_info_uses_idfa: true,
          content_rights_has_rights: true,
          content_rights_contains_third_party_content: true,
          export_compliance_platform: 'ios',
          export_compliance_compliance_required: false,
          export_compliance_encryption_updated: false,
          export_compliance_app_type: nil,
          export_compliance_uses_encryption: true,
          export_compliance_is_exempt: true,
          export_compliance_contains_third_party_cryptography: false,
          export_compliance_contains_proprietary_cryptography: false,
          export_compliance_available_on_french_store: false
        }
      )
    
    end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.181.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-appicon    | 0.16.0  | ✅ Up-To-Date  |
| fastlane-plugin-versioning | 0.4.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.4.0        |
| slack-notifier                | 2.3.2        |
| atomos                        | 0.1.3        |
| CFPropertyList                | 3.0.3        |
| claide                        | 1.0.3        |
| colored2                      | 3.1.2        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| plist                         | 3.6.0        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| multipart-post                | 2.0.0        |
| word_wrap                     | 1.0.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| artifactory                   | 3.0.15       |
| babosa                        | 1.0.4        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| excon                         | 0.80.1       |
| faraday-excon                 | 1.1.0        |
| faraday-net_http              | 1.0.1        |
| faraday-net_http_persistent   | 1.1.0        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.4.1        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.3        |
| gh_inspector                  | 1.1.3        |
| json                          | 2.3.0        |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| xcpretty-travis-formatter     | 1.0.1        |
| dotenv                        | 2.7.6        |
| bundler                       | 2.2.15       |
| simctl                        | 1.6.8        |
| jwt                           | 2.2.3        |
| uber                          | 0.1.0        |
| declarative                   | 0.0.20       |
| trailblazer-option            | 0.1.1        |
| representable                 | 3.1.1        |
| retriable                     | 3.1.2        |
| mini_mime                     | 1.1.0        |
| multi_json                    | 1.15.0       |
| signet                        | 0.15.0       |
| memoist                       | 0.16.2       |
| os                            | 1.1.1        |
| googleauth                    | 0.16.1       |
| httpclient                    | 2.8.3        |
| google-api-client             | 0.38.0       |
| google-cloud-env              | 1.5.0        |
| google-cloud-errors           | 1.1.0        |
| google-cloud-core             | 1.6.0        |
| rexml                         | 3.2.3.1      |
| webrick                       | 1.6.1        |
| google-apis-core              | 0.3.0        |
| google-apis-iamcredentials_v1 | 0.3.0        |
| google-apis-storage_v1        | 0.3.0        |
| rake                          | 13.0.3       |
| digest-crc                    | 0.6.3        |
| google-cloud-storage          | 1.31.0       |
| emoji_regex                   | 3.2.2        |
| jmespath                      | 1.4.0        |
| aws-partitions                | 1.446.0      |
| aws-eventstream               | 1.1.1        |
| aws-sigv4                     | 1.2.3        |
| aws-sdk-core                  | 3.114.0      |
| aws-sdk-kms                   | 1.43.0       |
| aws-sdk-s3                    | 1.93.1       |
| uri                           | 0.10.0       |
| forwardable                   | 1.3.1        |
| logger                        | 1.4.2        |
| cgi                           | 0.1.0        |
| date                          | 3.0.0        |
| timeout                       | 0.1.0        |
| stringio                      | 0.1.0        |
| zlib                          | 1.1.0        |
| ipaddr                        | 1.2.2        |
| openssl                       | 2.1.2        |
| ostruct                       | 0.2.0        |
| strscan                       | 1.0.3        |
| delegate                      | 0.1.0        |
| fileutils                     | 1.4.1        |
| io-console                    | 0.5.6        |
| singleton                     | 0.1.0        |
| open3                         | 0.1.0        |
| yaml                          | 0.1.0        |
| psych                         | 3.1.0        |
| mutex_m                       | 0.1.0        |
| fastlane-plugin-appicon       | 0.16.0       |
| benchmark                     | 0.1.0        |
| fastlane-plugin-versioning    | 0.4.4        |
</details>

*generated on:* **2021-04-23**
</details>

</pre>
</details>

**Comment by gelodgreat** [comment]
<img width="1319" alt="Screen Shot 2021-04-23 at 3 49 11 PM" src="https://user-images.githubusercontent.com/20021423/115838050-d9e38080-a44b-11eb-8633-537fde8cf412.png">
here's the error that occur

**Comment by crazymanish** [comment]
Hi @gelodgreat 

To create a new certificate and provisional profiles. Please run **match nuke** first which will clean the Apple developer portal and match-storage(i.e git repo) and then run match to regenerate new certificate and provisional profiles.
Something like this:

```ruby
match_nuke(
    type: "appstore", 
    app_identifier: ["tools.fastlane.app", "tools.fastlane.sleepy"],
    verbose: true,
)

match(
    type: "appstore", 
    app_identifier: ["tools.fastlane.app", "tools.fastlane.sleepy"],
    verbose: true,
    force: true, #Important: to re-generates the new provisioning profiles
)
```

Please let me know if that will work for you or not! Enjoy match Nuking 🚀!

**Comment by gelodgreat** [comment]
i was successful on generating cert and it removed the issue, i get this error that it wasnt able to generate Apple Distribution Certificate

![image](https://user-images.githubusercontent.com/20021423/115980261-e556b900-a5bd-11eb-9bd6-c3a0ccbc9700.png)

**Comment by gelodgreat** [comment]
got it resolved by using it like this, thank you very much @crazymanish 

` match_nuke(
        type: "appstore", 
        app_identifier: ["tools.fastlane.app", "tools.fastlane.sleepy"],
        verbose: true,
        skip_confirmation: true,
       )

       match(
        app_identifier:["tools.fastlane.app", "tools.fastlane.sleepy"],
        type: "appstore",
        verbose: true,
        force: true,
        generate_apple_certs: true,
      )
`
