### ISSUE TITLE
Could not find a matching code signing identity for type, is guessing the wrong type. Should be "Direct", its "AppStore"

### ISSUE THREAD

**Issue by pvinis** [fastlane/fastlane#18603]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I created a lane in a completely new project for a mac project.
```
lane :wow do
  sync_code_signing(
        storage_mode: "git",
        git_url: "git@github.com:pvinis/test-certs.git",
        type: "developer_id",
        username: "pvinis@gmail.com",
        team_id: "CAG2W9M777",
        app_identifier: "is.pvin.wow.test"
    )
end
```

Notice that I use `type: "developer_id"`.

I then executed the lane, `bundle e fastlane wow`, and I got an error `Could not find a matching code signing identity for type 'AppStore'`, when it should be "Direct", based on https://github.com/fastlane/fastlane/blob/master/match/lib/match/generator.rb#L114.

It ended up creating a developer id application certificate, but it did not find it or add it on the test-certs repo.

##### Command executed
`sync_code_signing` with `developer_id` as `type`.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
bundle e fastlane wow
[✔] 🚀
[17:43:48]: Driving the lane 'wow' 🚀
[17:43:48]: -------------------------------
[17:43:48]: --- Step: sync_code_signing ---
[17:43:48]: -------------------------------

+--------------------------------+--------------------------------------+
|                       Summary for match 2.181.0                       |
+--------------------------------+--------------------------------------+
| storage_mode                   | git                                  |
| git_url                        | git@github.com:pvinis/test-certs.git |
| type                           | developer_id                         |
| username                       | pvinis@gmail.com                     |
| team_id                        | CAG2W9M777                           |
| app_identifier                 | ["is.pvin.wow.test"]                 |
| readonly                       | false                                |
| generate_apple_certs           | true                                 |
| skip_provisioning_profiles     | false                                |
| git_branch                     | master                               |
| shallow_clone                  | false                                |
| clone_branch_directly          | false                                |
| keychain_name                  | login.keychain                       |
| force                          | false                                |
| force_for_new_devices          | false                                |
| skip_confirmation              | false                                |
| skip_docs                      | false                                |
| platform                       | ios                                  |
| derive_catalyst_app_identifier | false                                |
| fail_on_name_taken             | false                                |
| skip_certificate_matching      | false                                |
| skip_set_partition_list        | false                                |
| verbose                        | false                                |
+--------------------------------+--------------------------------------+

[17:43:48]: Cloning remote git repo...
[17:43:48]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[17:43:55]: Checking out branch master...
[17:43:55]: 🔓  Successfully decrypted certificates repo
[17:43:55]: Verifying that the certificate and profile are still valid on the Dev Portal...
Available session is not valid any more. Continuing with normal login.
[17:44:02]: Couldn't find a valid code signing identity for developer_id_application... creating one for you now

+-------------------------+---------------------------------------------------+
|                          Summary for cert 2.181.0                           |
+-------------------------+---------------------------------------------------+
| platform                | ios                                               |
| development             | false                                             |
| type                    | developer_id_application                          |
| generate_apple_certs    | true                                              |
| force                   | true                                              |
| username                | pvinis@gmail.com                                  |
| team_id                 | CAG2W9M777                                        |
| keychain_path           | /Users/pavlos/Library/Keychains/login.keychain-db |
| skip_set_partition_list | false                                             |
+-------------------------+---------------------------------------------------+

[17:44:02]: Starting login with user 'pvinis@gmail.com'
Available session is not valid any more. Continuing with normal login.
[17:44:08]: Successfully logged in
[17:44:09]: Enter the password for /Users/pavlos/Library/Keychains/login.keychain-db
[17:44:09]: This passphrase will be stored in your local keychain with the name fastlane_keychain_login and used in future runs
[17:44:09]: This prompt can be avoided by specifying the 'keychain_password' option or 'MATCH_KEYCHAIN_PASSWORD' environment variable
[17:44:09]: Password for login keychain: ****
[17:44:25]: Type password for login keychain again: ****
[✔] Setting key partition list... (this can take a minute if there are a lot of keys installed)
[17:44:28]: Using keychain password from keychain item fastlane_keychain_login in /Users/pavlos/Library/Keychains/login.keychain-db
[✔] Setting key partition list... (this can take a minute if there are a lot of keys installed)
[17:44:28]: Successfully generated CW9BPB9K3N which was imported to the local machine.
[17:44:30]: Verifying the certificate is properly installed locally...
[17:44:30]: Successfully installed certificate CW9BPB9K3N

+-------------------------------------+-------------------------------+
|                      Summary for sigh 2.181.0                       |
+-------------------------------------+-------------------------------+
| app_identifier                      | is.pvin.wow.test              |
| username                            | pvinis@gmail.com              |
| force                               | false                         |
| cert_id                             | CW9BPB9K3N                    |
| provisioning_name                   | match Direct is.pvin.wow.test |
| ignore_profiles_with_different_name | true                          |
| team_id                             | CAG2W9M777                    |
| fail_on_name_taken                  | false                         |
| platform                            | ios                           |
| developer_id                        | true                          |
| adhoc                               | false                         |
| development                         | false                         |
| skip_install                        | false                         |
| skip_fetch_profiles                 | false                         |
| skip_certificate_verification       | false                         |
| readonly                            | false                         |
+-------------------------------------+-------------------------------+

[17:44:30]: Starting login with user 'pvinis@gmail.com'
Available session is not valid any more. Continuing with normal login.
[17:44:33]: Successfully logged in
[17:44:33]: Fetching profiles...
[17:44:34]: Verifying certificates...
[17:44:34]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[17:44:35]: Creating new provisioning profile for 'is.pvin.wow.test' with name 'match Direct is.pvin.wow.test' for 'ios' platform
[17:44:35]: No certificates for filter: Certificate ID: 'CW9BPB9K3N'
+---------------+-----+
|    Lane Context     |
+---------------+-----+
| PLATFORM_NAME |     |
| LANE_NAME     | wow |
+---------------+-----+
[17:44:35]: Could not find a matching code signing identity for type 'AppStore'. It is recommended to use match to manage code signing for you, more information on https://codesigning.guide. If you don't want to do so, you can also use cert to generate a new one: https://fastlane.tools/cert

+------+-------------------+-------------+
|            fastlane summary            |
+------+-------------------+-------------+
| Step | Action            | Time (in s) |
+------+-------------------+-------------+
| 💥   | sync_code_signing | 47          |
+------+-------------------+-------------+

[17:44:35]: fastlane finished with errors

[!] Could not find a matching code signing identity for type 'AppStore'. It is recommended to use match to manage code signing for you, more information on https://codesigning.guide. If you don't want to do so, you can also use cert to generate a new one: https://fastlane.tools/cert
  </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.1                                        |
| Ruby                        | 2.7.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.31.1                          |
| Installation Source         | ~/.asdf/installs/ruby/2.7.2/bin/fastlane    |
| Host                        | macOS 11.1 (20C69)                          |
| Ruby Lib Dir                | ~/.asdf/installs/ruby/2.7.2/lib             |
| OpenSSL Version             | OpenSSL 1.1.1j  16 Feb 2021                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.4                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
lane :wow do
  sync_code_signing(
        storage_mode: "git",
        git_url: "git@github.com:pvinis/test-certs.git",
        type: "developer_id",
        username: "pvinis@gmail.com",
        team_id: "CAG2W9M777",
        app_identifier: "is.pvin.wow.test"
    )
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.181.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.4.0        |
| bundler                       | 2.2.11       |
| uri                           | 0.10.0       |
| rake                          | 13.0.3       |
| CFPropertyList                | 3.0.3        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| artifactory                   | 3.0.15       |
| atomos                        | 0.1.3        |
| aws-eventstream               | 1.1.1        |
| aws-partitions                | 1.447.0      |
| aws-sigv4                     | 1.2.3        |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.114.0      |
| aws-sdk-kms                   | 1.43.0       |
| aws-sdk-s3                    | 1.93.1       |
| babosa                        | 1.0.4        |
| claide                        | 1.0.3        |
| colored                       | 1.2          |
| colored2                      | 3.1.2        |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| declarative                   | 0.0.20       |
| digest-crc                    | 0.6.3        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| dotenv                        | 2.7.6        |
| emoji_regex                   | 3.2.2        |
| excon                         | 0.80.1       |
| faraday-excon                 | 1.1.0        |
| faraday-net_http              | 1.0.1        |
| faraday-net_http_persistent   | 1.1.0        |
| multipart-post                | 2.0.0        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.4.1        |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.3        |
| gh_inspector                  | 1.1.3        |
| jwt                           | 2.2.3        |
| memoist                       | 0.16.2       |
| multi_json                    | 1.15.0       |
| os                            | 1.1.1        |
| signet                        | 0.15.0       |
| googleauth                    | 0.16.1       |
| httpclient                    | 2.8.3        |
| mini_mime                     | 1.1.0        |
| trailblazer-option            | 0.1.1        |
| uber                          | 0.1.0        |
| representable                 | 3.1.1        |
| retriable                     | 3.1.2        |
| google-api-client             | 0.38.0       |
| rexml                         | 3.2.5        |
| webrick                       | 1.7.0        |
| google-apis-core              | 0.3.0        |
| google-apis-iamcredentials_v1 | 0.3.0        |
| google-apis-storage_v1        | 0.3.0        |
| google-cloud-env              | 1.5.0        |
| google-cloud-errors           | 1.1.0        |
| google-cloud-core             | 1.6.0        |
| google-cloud-storage          | 1.31.0       |
| json                          | 2.5.1        |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| plist                         | 3.6.0        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| simctl                        | 1.6.8        |
| slack-notifier                | 2.3.2        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| word_wrap                     | 1.0.0        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| xcpretty-travis-formatter     | 1.0.1        |
</details>

*generated on:* **2021-04-26**
</details>

**Comment by pvinis** [comment]
You silly bot. It's a bug report. Keep it open.

**Comment by lucgrabowski** [comment]
Hi @pvinis, could you try setting a platform to `macos` or `catalyst`? 

I think that for `ios` platform `sigh` gets wrong values in:
https://github.com/fastlane/fastlane/blob/430fcb19fc4fca33901c91f619b2324cdb0c875d/sigh/lib/sigh/runner.rb#L211
and 
https://github.com/fastlane/fastlane/blob/430fcb19fc4fca33901c91f619b2324cdb0c875d/sigh/lib/sigh/runner.rb#L69
