### ISSUE TITLE
Match attempts to create new certificate/doesn't find imported certificate after existing certificate is imported into repository

### ISSUE THREAD

**Issue by parsable-njeremic** [fastlane/fastlane#18605]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I want to set up **match** to use with my existing enterprise certificate. To do this, I have used `match import`, and everything was successfully imported into certificate repo.

After import, I tried running `fastlane match` to check if sync is working, but fastlane tries to create the certificate again, and it fails - because limit is reached.

##### Command executed

`fastlane match enterprise`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>

~/projects/<project name> on <branch> ❯ bundle exec fastlane match enterprise                                                                                 took 22s at 12:18:25
[✔] 🚀 
[12:18:31]: Successfully loaded '/Users/<user>/projects/<project name>/fastlane/Matchfile' 📄

+----------------+-----------------------------------------------------------+
|                Detected Values from './fastlane/Matchfile'                 |
+----------------+-----------------------------------------------------------+
| git_url        | git@github.com:<company>/react-native-ios-certificates.git |
| storage_mode   | git                                                       |
| type           | enterprise                                                |
| app_identifier | ["com.<company>.<appid>"]                        |
| username       | <user>@<company>.com                              |
+----------------+-----------------------------------------------------------+

+--------------------------------+-----------------------------------------------------------+
|                                 Summary for match 2.181.0                                  |
+--------------------------------+-----------------------------------------------------------+
| type                           | enterprise                                                |
| readonly                       | false                                                     |
| generate_apple_certs           | true                                                      |
| skip_provisioning_profiles     | false                                                     |
| app_identifier                 | ["com.<company>.<appid>"]                        |
| username                       | <user>@<company>.com                              |
| team_id                        | <teamId>                                                |
| storage_mode                   | git                                                       |
| git_url                        | git@github.com:<company>/react-native-ios-certificates.git |
| git_branch                     | master                                                    |
| shallow_clone                  | false                                                     |
| clone_branch_directly          | false                                                     |
| keychain_name                  | login.keychain                                            |
| force                          | false                                                     |
| force_for_new_devices          | false                                                     |
| skip_confirmation              | false                                                     |
| skip_docs                      | false                                                     |
| platform                       | ios                                                       |
| derive_catalyst_app_identifier | false                                                     |
| fail_on_name_taken             | false                                                     |
| skip_certificate_matching      | false                                                     |
| skip_set_partition_list        | false                                                     |
| verbose                        | false                                                     |
+--------------------------------+-----------------------------------------------------------+

[12:18:31]: Cloning remote git repo...
[12:18:31]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[12:18:33]: Checking out branch master...
[12:18:33]: 🔓  Successfully decrypted certificates repo
[12:18:33]: Verifying that the certificate and profile are still valid on the Dev Portal...
Available session is not valid any more. Continuing with normal login.
[12:18:35]: Couldn't find a valid code signing identity for enterprise... creating one for you now

+-------------------------+----------------------------------------------------+
|                           Summary for cert 2.181.0                           |
+-------------------------+----------------------------------------------------+
| platform                | ios                                                |
| development             | false                                              |
| generate_apple_certs    | true                                               |
| force                   | true                                               |
| username                | <user>@<company>.com                       |
| team_id                 | <teamId>                                         |
| keychain_path           | /Users/<user>/Library/Keychains/login.keychain-db |
| skip_set_partition_list | false                                              |
+-------------------------+----------------------------------------------------+

[12:18:35]: Starting login with user '<user>@<company>.com'
Available session is not valid any more. Continuing with normal login.
[12:18:38]: Successfully logged in

Looking for related GitHub issues on fastlane/fastlane...

➡️  Could not create another Development certificate, reached the maximum number.
    https://github.com/fastlane/fastlane/issues/17272 [closed] 1 💬
    18 Nov 2020

➡️  Match : Google Cloud Storage - Stops after fetching 1000 objects. So it keeps trying to re-create new certificates.
    https://github.com/fastlane/fastlane/issues/17088 [closed] 3 💬
    03 Dec 2020

➡️  Fastlane match + multiple apps + git branches
    https://github.com/fastlane/fastlane/issues/16311 [closed] 5 💬
    03 Aug 2020

and 23 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20create%20another%20Distribution%20certificate%2C%20reached%20the%20maximum%20number%20of%20available%20Distribution%20certificates.&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.

[!] Could not create another Distribution certificate, reached the maximum number of available Distribution certificates.</pre>
</details>

### Environment

<details>
  <pre> <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.2.3                                                         |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.2.3 (20D91)                                           |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.4                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
################################
# Android
################################

platform :android do
  desc "Build android locally"
  lane :build do
    sh ("rm -rf ../builds/android")
    gradle(task: "--refresh-dependencies clean cleanBuildCache assemble", project_dir: "android/")
    copy_artifacts(target_path: "./builds/android", artifacts: ["android/app/build/outputs/apk/*"])
    gradle(
      task: "clean", project_dir: "android/",
    )
  end

  desc "Increment version, build .apk, and distribute via FirebaseAppDistribution"
  lane :beta do
    if ENV["ENVIRONMENT"] == "enterprise"
      package_name = "<packageName>"
      firebase_app_id = "<firebaseId>"
    elsif ENV["ENVIRONMENT"] == "testing"
      package_name = "<packageName>"
      firebase_app_id = "<firebaseId>"
    end
    # version name is version visible to public
    # android_set_version_name(
    # version_name: "1.0.1",
    # )
    #version code is internal versioning
    android_set_version_code(
      gradle_file: "android/app/build.gradle", # optional
    )

    android_change_package_name(
      path: "./android",
      package_name: package_name,
      manifest: "./android/app/src/main/AndroidManifest.xml",
    )
    gradle(task: "--refresh-dependencies clean cleanBuildCache assemble", project_dir: "android/")
    ##TODO decide when commit bump should be triggered
    commit_android_version_bump(
      gradle_file_folder: "android/app",
    )
    firebase_app_distribution(
      app: firebase_app_id,
      apk_path: "android/app/build/outputs/apk/release/app-release.apk",
      testers: "xx",
      release_notes_file: "CHANGELOG.md",
    )
    gradle(
      task: "clean", project_dir: "android/",
    )
  end
end

################################
# iOS
################################

platform :ios do
  desc "Add description of lane"
  lane :matchit do
    match(git_url: "<gitrepo>",
          type: "enterprise",
          app_identifier: "<packageName>",
          # readonly: true,
          generate_apple_certs: "false")
  end
  desc "Build iOS locally with Debug configuration"
  lane :build_debug do
    sh ("rm -rf ../builds/ios")
    user = `printf $USER`
    derived_path = "/Users/#{user}/Documents/tmp_build"
    sh ("cd .. && cd ios && pod install")
    build_app(
      workspace: "ios/Company.xcworkspace",
      scheme: "Company",
      silent: "true",
      configuration: "Debug",
      derived_data_path: derived_path,
      output_directory: "./builds/ios",
      skip_package_ipa: true,
      skip_archive: true,
      destination: "platform=iOS Simulator,name=iPhone 11",
    )
    copy_artifacts(target_path: "./builds/ios", artifacts: ["/Users/#{user}/Documents/tmp_build/Build/Products/Debug-iphonesimulator/*.app"])
    sh ("rm -rf #{derived_path}")
  end

  desc "Build iOS locally with Test configuration"
  lane :build_test do
    sh ("rm -rf ../builds/ios")
    user = `printf $USER`
    derived_path = "/Users/#{user}/Documents/tmp_build"
    sh ("cd .. && cd ios && pod install")
    build_app(
      workspace: "ios/Company.xcworkspace",
      scheme: "Company",
      silent: "true",
      configuration: "Test",
      derived_data_path: derived_path,
      output_directory: "./builds/ios",
      skip_package_ipa: true,
      skip_archive: true,
      destination: "platform=iOS Simulator,name=iPhone 11",
    )
    copy_artifacts(target_path: "./builds/ios", artifacts: ["/Users/#{user}/Documents/tmp_build/Build/Products/Test-iphonesimulator/*.app"])
    sh ("rm -rf #{derived_path}")
  end

  desc "Increment version, build .ipa, and distribute via FirebaseAppDistribution"
  lane :beta do
    if ENV["ENVIRONMENT"] == "enterprise"
      bundle_id = "<packageName>"
      firebase_app_id = "xxxx"
      profile = "Company Staging In-house distribution"
      #all data in the next 4 lines will be replaced with data for production app (instead of testing, which is an example here)
    elsif ENV["ENVIRONMENT"] == "testing"
      bundle_id = "<packageName>"
      firebase_app_id = "xxxx"
      profile = "Company Testing"
    end
    update_app_identifier(
      xcodeproj: "ios/Company.xcodeproj", # Optional path to xcodeproj, will use the first .xcodeproj if not set
      plist_path: "Company/Info.plist", # Path to info plist file, relative to xcodeproj
      app_identifier: bundle_id, # The App Identifier
    )
    #get current build number, convert to integer and increase by 1, so this can be used in commit message
    new_build_number = get_build_number(xcodeproj: "ios/Company.xcodeproj").to_i + 1
    increment_build_number(xcodeproj: "ios/Company.xcodeproj")

    update_code_signing_settings(
      use_automatic_signing: false,
      path: "ios/Company.xcodeproj",
    )
    #match
    # cert
    # sigh(
    #   app_identifier: bundle_id,
    # )
    update_project_provisioning(
      xcodeproj: "ios/Company.xcodeproj",
      target_filter: ".*",
      profile: "./InHouse_#{bundle_id}.mobileprovision",
    )
    sh ("cd .. && cd ios && pod install")
    build_app(
      workspace: "ios/Company.xcworkspace",
      scheme: "Company",
      silent: "true",
      output_directory: "./builds/ios",
      export_options: {
        method: "enterprise",
        provisioningProfiles: {
          "<packageName>" => "CompanyCompany Testing",
          "<packageName>" => "CompanyCompany Staging In-house distribution",
        },
      },
    )
    ##TODO decide when commit bump should be triggered
    commit_version_bump(
      xcodeproj: "ios/Company.xcodeproj",
      message: "Bump build number  to #{new_build_number}",
    )
    firebase_app_distribution(
      app: firebase_app_id,
      ipa_path: "./builds/ios/Company.ipa",
      testers: "user@Company.com",
      release_notes_file: "CHANGELOG.md",
    )
    #increment_build_number(xcodeproj: "Company.xcodeproj")
    #build_app(workspace: "Company.xcworkspace", scheme: "Company")
    #upload_to_testflight
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id(ENV["APPLE_ID"]) # Your Apple email address

itc_team_id("xxx") # App Store Connect Team ID
team_id("xxx") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.181.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                      | Version | Update-Status      |
| ------------------------------------------- | ------- | ------------------ |
| fastlane-plugin-versioning_android          | 0.1.0   | ✅ Up-To-Date       |
| fastlane-plugin-increment_version_code      | 0.4.3   | ✅ Up-To-Date       |
| fastlane-plugin-firebase_app_distribution   | 0.2.5   | 🚫 Update available |
| fastlane-plugin-android_change_package_name | 0.1.9   | ✅ Up-To-Date       |
| fastlane-plugin-commit_android_version_bump | 0.2.0   | ✅ Up-To-Date       |

<details><summary><b>Loaded gems</b></summary>

| Gem                                         | Version      |
| ------------------------------------------- | ------------ |
| did_you_mean                                | 1.3.0        |
| slack-notifier                              | 2.3.2        |
| atomos                                      | 0.1.3        |
| claide                                      | 1.0.3        |
| colored2                                    | 3.1.2        |
| nanaimo                                     | 0.3.0        |
| xcodeproj                                   | 1.19.0       |
| rouge                                       | 2.0.7        |
| xcpretty                                    | 0.3.0        |
| terminal-notifier                           | 2.0.0        |
| unicode-display_width                       | 1.7.0        |
| terminal-table                              | 1.8.0        |
| plist                                       | 3.6.0        |
| public_suffix                               | 4.0.6        |
| addressable                                 | 2.7.0        |
| multipart-post                              | 2.0.0        |
| word_wrap                                   | 1.0.0        |
| tty-screen                                  | 0.8.1        |
| tty-cursor                                  | 0.7.1        |
| tty-spinner                                 | 0.9.3        |
| artifactory                                 | 3.0.15       |
| babosa                                      | 1.0.4        |
| colored                                     | 1.2          |
| highline                                    | 1.7.10       |
| commander-fastlane                          | 4.4.6        |
| unf_ext                                     | 0.0.7.7      |
| unf                                         | 0.1.4        |
| domain_name                                 | 0.5.20190701 |
| http-cookie                                 | 1.0.3        |
| faraday-cookie_jar                          | 0.0.7        |
| faraday_middleware                          | 1.0.0        |
| fastimage                                   | 2.2.3        |
| gh_inspector                                | 1.1.3        |
| mini_magick                                 | 4.11.0       |
| naturally                                   | 2.2.1        |
| rubyzip                                     | 2.3.0        |
| security                                    | 0.1.3        |
| xcpretty-travis-formatter                   | 1.0.1        |
| dotenv                                      | 2.7.6        |
| simctl                                      | 1.6.8        |
| retriable                                   | 3.1.2        |
| multi_json                                  | 1.15.0       |
| signet                                      | 0.15.0       |
| httpclient                                  | 2.8.3        |
| google-api-client                           | 0.38.0       |
| google-cloud-env                            | 1.5.0        |
| google-cloud-errors                         | 1.1.0        |
| google-cloud-core                           | 1.6.0        |
| google-apis-core                            | 0.3.0        |
| google-apis-storage_v1                      | 0.3.0        |
| digest-crc                                  | 0.6.3        |
| google-cloud-storage                        | 1.31.0       |
| emoji_regex                                 | 3.2.2        |
| CFPropertyList                              | 3.0.3        |
| excon                                       | 0.80.1       |
| ruby2_keywords                              | 0.0.4        |
| faraday-net_http_persistent                 | 1.1.0        |
| faraday-net_http                            | 1.0.1        |
| faraday-excon                               | 1.1.0        |
| faraday                                     | 1.4.1        |
| json                                        | 2.5.1        |
| bundler                                     | 2.2.16       |
| jwt                                         | 2.2.3        |
| trailblazer-option                          | 0.1.1        |
| declarative                                 | 0.0.20       |
| uber                                        | 0.1.0        |
| representable                               | 3.1.1        |
| mini_mime                                   | 1.1.0        |
| os                                          | 1.1.1        |
| memoist                                     | 0.16.2       |
| googleauth                                  | 0.16.1       |
| webrick                                     | 1.7.0        |
| rexml                                       | 3.2.5        |
| google-apis-iamcredentials_v1               | 0.3.0        |
| rake                                        | 13.0.3       |
| aws-eventstream                             | 1.1.1        |
| aws-sigv4                                   | 1.2.3        |
| aws-partitions                              | 1.447.0      |
| jmespath                                    | 1.4.0        |
| aws-sdk-core                                | 3.114.0      |
| aws-sdk-kms                                 | 1.43.0       |
| aws-sdk-s3                                  | 1.93.1       |
| forwardable                                 | 1.2.0        |
| logger                                      | 1.3.0        |
| date                                        | 2.0.0        |
| stringio                                    | 0.0.2        |
| zlib                                        | 1.0.0        |
| ipaddr                                      | 1.2.2        |
| openssl                                     | 2.1.2        |
| ostruct                                     | 0.1.0        |
| strscan                                     | 1.0.0        |
| fileutils                                   | 1.1.0        |
| etc                                         | 1.0.1        |
| io-console                                  | 0.4.7        |
| libxml-ruby                                 | 3.1.0        |
| psych                                       | 3.1.0        |
| mutex_m                                     | 0.1.0        |
| fastlane-plugin-versioning_android          | 0.1.0        |
| fastlane-plugin-increment_version_code      | 0.4.3        |
| fastlane-plugin-firebase_app_distribution   | 0.2.5        |
| fastlane-plugin-android_change_package_name | 0.1.9        |
| fastlane-plugin-commit_android_version_bump | 0.2.0        |
</details>

*generated on:* **2021-04-26**
</details></pre>
</details>

**Comment by YanaSyritskaya** [comment]
I also have the same issue. Are there any updates?

**Comment by Molly584** [comment]
I'm having the same issue attempting to figure out where to store the record. Do you know where the way is assumed to be relevant to?
[IndigoCard Login](https://www.indigocard.run/)

**Comment by YanaSyritskaya** [comment]
Made it work. Turned out that could read certs git repo, but couldn't write. Created new repo for certs. Revoked manually certificates, added git user in circle ci settings.
