### ISSUE TITLE
iOS 9 Invalid Swift Support

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1860]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/337986?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @djtarazona - Imported from <a href='https://github.com/fastlane/gym/issues/81'>fastlane/gym#81</a>
        </td>
      </tr>
    </table>

Has anyone been able to successfully submit a build to iTC / TestFlight for iOS 9 with `gym`?  I'm using Xcode 7 GM (along with El Capitan GM) and every time I submit my binary, I get an email with the following:

> Invalid Swift Support - The files libswiftsimd.dylib, libswiftCoreMedia.dylib, libswiftAVFoundation.dylib, libswiftGLKit.dylib don’t match /Payload/App.app/Frameworks/libswiftsimd.dylib, /Payload/App.app/Frameworks/libswiftCoreMedia.dylib, /Payload/App.app/Frameworks/libswiftAVFoundation.dylib, /Payload/App.app/Frameworks/libswiftGLKit.dylib. Make sure the files are correct, rebuild your app, and resubmit it. Don’t apply post-processing to /Payload/App.app/Frameworks/libswiftsimd.dylib, /Payload/App.app/Frameworks/libswiftCoreMedia.dylib, /Payload/App.app/Frameworks/libswiftAVFoundation.dylib, /Payload/App.app/Frameworks/libswiftGLKit.dylib.
>
> Once these issues have been corrected, you can then redeliver the corrected binary.

It seems like a lot of other people are having the same issue, so this probably isn't an issue with `gym`.  But I'm hoping some workaround can be added to `gym` in the meantime.

These links may help:

http://stackoverflow.com/questions/32526526/invalid-swift-support-files-don-t-match
http://stackoverflow.com/questions/26163856/invalid-swift-support-invalid-implementation-of-swift
https://forums.developer.apple.com/thread/17063

I'm going to try archiving with just Xcode and see if that works.

**Comment by zhonghuiwen** [comment]
I managed to solve this issue by setting the toolchain to use swift 2.3
[http://stackoverflow.com/a/39523759/2490135](url)

**Comment by TKBurner** [comment]
@zhonghuiwen Awesome! Thanks so much for sharing. Hope you have a wonderful day!

**Comment by KrauseFx** [comment]
We just pushed a new release for gym that fixes this: https://github.com/fastlane/fastlane/releases/tag/gym%2F1.10.0

**Comment by wongzigii** [comment]
@KrauseFx  I am getting same error in `gym 1.10.0`

**Comment by KrauseFx** [comment]
@wongzigii Could you please submit a new issue for this?

**Comment by TKBurner** [comment]
@wolfe719 Can you open a new ticket and share the full input and output? I'd love to take a look. Hope you have a great day!
