### ISSUE TITLE
SwiftLint action - Replace autocorrect with --fix

### ISSUE THREAD

**Issue by lordcodes** [fastlane/fastlane#18604]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When running the swiftlint action in 'autocorrect' mode, SwiftLint outputs a warning about that mode being deprecated and that you should use 'swiftlint --fix' instead.

The fix should just require updating the 'swiftlint' action to use --fix instead of autocorrect mode as is done currently.

It doesn't prevent the command running, however, it could stop working in the future if SwiftLint remove it from a new version.

##### Command executed

A fastlane lane that uses the 'swiftlint' action with 'mode' set to 'autocorrect'.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
[11:35:09]: -----------------------
[11:35:09]: --- Step: swiftlint ---
[11:35:09]: -----------------------
[11:35:10]: $ Pods/SwiftLint/swiftlint autocorrect
[11:35:10]: ▸ The `swiftlint autocorrect` command is no longer available.
[11:35:10]: ▸ Please use `swiftlint --fix` instead. 
</pre>
</details>

**Comment by lordcodes** [comment]
Does the complexity you can do this label, mean I should just stop using swiftlint action and run the command myself?
Happy to do that, just wanted to report that the built in action was using a deprecated argument.

**Comment by minuscorp** [comment]
No no, it means it is a straightforward fix that can be done easily for people who want to contribute 😊

**Comment by Kukurijek** [comment]
What is actually the right approach for deprecations (I have not found anything about this in docs)?
Removing the old mode and adding new or just adding the new without breaking changes ?

**Comment by minuscorp** [comment]
Maybe checking the version installed so you know which parameter may be used

**Comment by crazymanish** [comment]
Hello @lordcodes

Open PR here https://github.com/fastlane/fastlane/pull/18695
Please feel free to review, test, and provide your feedback! 

Thank you.

**Comment by lordcodes** [comment]
@crazymanish Fantastic, thank you very much! Looks great!
