### ISSUE TITLE
I can not get_provisioning_profile when the profile is exists,even I use force:true when it is InHouse

### ISSUE THREAD

**Issue by WhyLogin** [fastlane/fastlane#18613]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Command executed
fastlane run get_provisioning_profile app_identifier:"com.XXX.test11" team_id:XXXXXX

### Environment
linux
ruby 2.7.3
fastlane 2.181.0

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

[16:35:55]: Starting login with user 'certrdm@tencent.com'
[16:35:56]: Successfully logged in
[16:35:56]: Fetching profiles...
[16:36:12]: Verifying certificates...

[16:36:12]: Error accessing file, this might be due to fastlane's directory handling
[16:36:12]: Check out https://docs.fastlane.tools/advanced/#directory-behavior for more details

Traceback (most recent call last):
        37: from /usr/local/rvm/gems/ruby-2.7.3/bin/ruby_executable_hooks:22:in `<main>'
        36: from /usr/local/rvm/gems/ruby-2.7.3/bin/ruby_executable_hooks:22:in `eval'
        35: from /usr/local/rvm/gems/ruby-2.7.3/bin/fastlane:23:in `<main>'
        34: from /usr/local/rvm/gems/ruby-2.7.3/bin/fastlane:23:in `load'
        33: from /usr/local/rvm/gems/ruby-2.7.3/gems/fastlane-2.181.0/bin/fastlane:23:in `<top (required)>'
        32: from /usr/local/rvm/gems/ruby-2.7.3/gems/fastlane-2.181.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
        31: from /usr/local/rvm/gems/ruby-2.7.3/gems/fastlane-2.181.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        30: from /usr/local/rvm/gems/ruby-2.7.3/gems/fastlane-2.181.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
        29: from /usr/local/rvm/gems/ruby-2.7.3/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        28: from /usr/local/rvm/gems/ruby-2.7.3/gems/fastlane-2.181.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        27: from /usr/local/rvm/gems/ruby-2.7.3/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        26: from /usr/local/rvm/gems/ruby-2.7.3/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        25: from /usr/local/rvm/gems/ruby-2.7.3/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        24: from /usr/local/rvm/gems/ruby-2.7.3/gems/fastlane-2.181.0/fastlane/lib/fastlane/commands_generator.rb:224:in `block (2 levels) in run'
        23: from /usr/local/rvm/gems/ruby-2.7.3/gems/fastlane-2.181.0/fastlane/lib/fastlane/one_off.rb:22:in `execute'
        22: from /usr/local/rvm/gems/ruby-2.7.3/gems/fastlane-2.181.0/fastlane/lib/fastlane/one_off.rb:42:in `run'
        21: from /usr/local/rvm/gems/ruby-2.7.3/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        20: from /usr/local/rvm/gems/ruby-2.7.3/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        19: from /usr/local/rvm/gems/ruby-2.7.3/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
        18: from /usr/local/rvm/gems/ruby-2.7.3/gems/fastlane-2.181.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        17: from /usr/local/rvm/gems/ruby-2.7.3/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
        16: from /usr/local/rvm/gems/ruby-2.7.3/gems/fastlane-2.181.0/fastlane/lib/fastlane/actions/get_provisioning_profile.rb:20:in `run'
        15: from /usr/local/rvm/gems/ruby-2.7.3/gems/fastlane-2.181.0/sigh/lib/sigh/manager.rb:8:in `start'
        14: from /usr/local/rvm/gems/ruby-2.7.3/gems/fastlane-2.181.0/sigh/lib/sigh/runner.rb:36:in `run'
        13: from /usr/local/rvm/gems/ruby-2.7.3/gems/fastlane-2.181.0/sigh/lib/sigh/runner.rb:124:in `fetch_profiles'
        12: from /usr/local/rvm/gems/ruby-2.7.3/gems/fastlane-2.181.0/sigh/lib/sigh/runner.rb:124:in `find_all'
        11: from /usr/local/rvm/gems/ruby-2.7.3/gems/fastlane-2.181.0/sigh/lib/sigh/runner.rb:124:in `each'
        10: from /usr/local/rvm/gems/ruby-2.7.3/gems/fastlane-2.181.0/sigh/lib/sigh/runner.rb:142:in `block in fetch_profiles'
         9: from /usr/local/rvm/gems/ruby-2.7.3/gems/fastlane-2.181.0/sigh/lib/sigh/runner.rb:142:in `each'
         8: from /usr/local/rvm/gems/ruby-2.7.3/gems/fastlane-2.181.0/sigh/lib/sigh/runner.rb:148:in `block (2 levels) in fetch_profiles'
         7: from /usr/local/rvm/gems/ruby-2.7.3/gems/fastlane-2.181.0/fastlane_core/lib/fastlane_core/cert_checker.rb:12:in `installed?'
         6: from /usr/local/rvm/gems/ruby-2.7.3/gems/fastlane-2.181.0/fastlane_core/lib/fastlane_core/cert_checker.rb:25:in `installed_identies'
         5: from /usr/local/rvm/gems/ruby-2.7.3/gems/fastlane-2.181.0/fastlane_core/lib/fastlane_core/cert_checker.rb:86:in `wwdr_certificates_installed?'
         4: from /usr/local/rvm/gems/ruby-2.7.3/gems/fastlane-2.181.0/fastlane_core/lib/fastlane_core/cert_checker.rb:130:in `wwdr_keychain'
         3: from /usr/local/rvm/gems/ruby-2.7.3/gems/fastlane-2.181.0/fastlane_core/lib/fastlane_core/cert_checker.rb:130:in `each'
         2: from /usr/local/rvm/gems/ruby-2.7.3/gems/fastlane-2.181.0/fastlane_core/lib/fastlane_core/cert_checker.rb:131:in `block in wwdr_keychain'
         1: from /usr/local/rvm/gems/ruby-2.7.3/gems/fastlane-2.181.0/fastlane_core/lib/fastlane_core/helper.rb:291:in `backticks'
/usr/local/rvm/gems/ruby-2.7.3/gems/fastlane-2.181.0/fastlane_core/lib/fastlane_core/helper.rb:291:in ``': No such file or directory - security (Errno::ENOENT)

**Comment by WhyLogin** [comment]
this is my fastlane env result :

[✔] 🚀 
[16:45:07]: Generating fastlane environment output, this might take a few seconds...
[16:45:07]: undefined method `strip' for nil:NilClass
[16:45:07]: Error rendering markdown table using the following text:
[16:45:07]: | Key | Value |
| fastlane | 2.181.0 |
| OS | Linux VM-127-179-centos 3.10.107-1-tlinux2_kvm_guest-0052 #1 SMP Wed Jan 15 18:42:19 CST 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Ruby | 2.7.3 |
| Bundler? | true |
| Git | git version 1.8.3.1 |
| Installation Source | /usr/local/rvm/gems/ruby-2.7.3/bin/fastlane |
| Host | Tencent tlinux release 2.2 (Final)
Kernel \r on an \m Linux VM-127-179-centos 3.10.107-1-tlinux2_kvm_guest-0052 #1 SMP Wed Jan 15 18:42:19 CST 2020 x86_64 x86_64 x86_64 GNU/Linux (3.10.107-1-tlinux2_kvm_guest-0052) |
| Ruby Lib Dir | /usr/local/rvm/rubies/ruby-2.7.3/lib |
| OpenSSL Version | OpenSSL 1.0.2k  26 Jan 2017 |
| Is contained | false |
| Is homebrew | false |
| Is installed via Fabric.app | false |
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key | Value |
| fastlane | 2.181.0 |
| OS | Linux VM-127-179-centos 3.10.107-1-tlinux2_kvm_guest-0052 #1 SMP Wed Jan 15 18:42:19 CST 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Ruby | 2.7.3 |
| Bundler? | true |
| Git | git version 1.8.3.1 |
| Installation Source | /usr/local/rvm/gems/ruby-2.7.3/bin/fastlane |
| Host | Tencent tlinux release 2.2 (Final)
Kernel \r on an \m Linux VM-127-179-centos 3.10.107-1-tlinux2_kvm_guest-0052 #1 SMP Wed Jan 15 18:42:19 CST 2020 x86_64 x86_64 x86_64 GNU/Linux (3.10.107-1-tlinux2_kvm_guest-0052) |
| Ruby Lib Dir | /usr/local/rvm/rubies/ruby-2.7.3/lib |
| OpenSSL Version | OpenSSL 1.0.2k  26 Jan 2017 |
| Is contained | false |
| Is homebrew | false |
| Is installed via Fabric.app | false |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.181.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.4.0        |
| executable-hooks              | 1.6.1        |
| bundler-unload                | 1.0.2        |
| rubygems-bundler              | 1.4.5        |
| bundler                       | 2.1.4        |
| rake                          | 13.0.3       |
| CFPropertyList                | 3.0.3        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| artifactory                   | 3.0.15       |
| atomos                        | 0.1.3        |
| aws-eventstream               | 1.1.1        |
| aws-partitions                | 1.447.0      |
| aws-sigv4                     | 1.2.3        |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.114.0      |
| aws-sdk-kms                   | 1.43.0       |
| aws-sdk-s3                    | 1.93.1       |
| babosa                        | 1.0.4        |
| claide                        | 1.0.3        |
| colored                       | 1.2          |
| colored2                      | 3.1.2        |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| declarative                   | 0.0.20       |
| digest-crc                    | 0.6.3        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| dotenv                        | 2.7.6        |
| emoji_regex                   | 3.2.2        |
| excon                         | 0.80.1       |
| faraday-excon                 | 1.1.0        |
| faraday-net_http              | 1.0.1        |
| faraday-net_http_persistent   | 1.1.0        |
| multipart-post                | 2.0.0        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.4.1        |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.3        |
| gh_inspector                  | 1.1.3        |
| jwt                           | 2.2.3        |
| memoist                       | 0.16.2       |
| multi_json                    | 1.15.0       |
| os                            | 1.1.1        |
| signet                        | 0.15.0       |
| googleauth                    | 0.16.1       |
| httpclient                    | 2.8.3        |
| mini_mime                     | 1.1.0        |
| trailblazer-option            | 0.1.1        |
| uber                          | 0.1.0        |
| representable                 | 3.1.1        |
| retriable                     | 3.1.2        |
| google-api-client             | 0.38.0       |
| rexml                         | 3.2.5        |
| webrick                       | 1.7.0        |
| google-apis-core              | 0.3.0        |
| google-apis-iamcredentials_v1 | 0.3.0        |
| google-apis-storage_v1        | 0.3.0        |
| google-cloud-env              | 1.5.0        |
| google-cloud-errors           | 1.1.0        |
| google-cloud-core             | 1.6.0        |
| google-cloud-storage          | 1.31.0       |
| json                          | 2.5.1        |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| plist                         | 3.6.0        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| simctl                        | 1.6.8        |
| slack-notifier                | 2.3.2        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| word_wrap                     | 1.0.0        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| xcpretty-travis-formatter     | 1.0.1        |
</details>


*generated on:* **2021-04-28**
</details>
[16:45:07]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[16:45:07]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅

**Comment by max-ott** [comment]
How do you authenticate with Apple? Apple ID or ASX API key?

**Comment by WhyLogin** [comment]
I use Apple ID 
I have fix it by delete a line in 
/usr/local/rvm/gems/ruby-2.7.3/gems/fastlane-2.176.0/sigh/lib/sigh/runner.rb
![image](https://user-images.githubusercontent.com/7535834/117235368-29b54500-ae59-11eb-880b-01f75276d8ca.png)

**Comment by WhyLogin** [comment]
maybe in linux fastlane should not check local certifacate

**Comment by WhyLogin** [comment]
> How do you authenticate with Apple? Apple ID or ASC API key?

Maybe you can fix this on linux ?
