### ISSUE TITLE
 iTMSTransporter fails when uploading to store.

### ISSUE THREAD

**Issue by ir2pid** [fastlane/fastlane#18619]
### New Issue Checklist

- [ x ] Updated fastlane to the latest version
- [ x  ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x  ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
iTMSTransporter fails when uploading to store.

##### Complete output when running fastlane, including the stack trace and command used

INFO [2021-04-29 09:22:58.29]: ----------------------------------
INFO [2021-04-29 09:22:58.29]: --- Step: upload_to_testflight ---
INFO [2021-04-29 09:22:58.29]: ----------------------------------
INFO [2021-04-29 09:22:58.29]: Ready to upload new build to TestFlight (App: 1065921908)...
DEBUG [2021-04-29 09:22:58.29]: App Platform (ios)
INFO [2021-04-29 09:22:59.04]: Wrote XML data to '/var/folders/7g/88jlglrx7jxds9qk353rl93w0000gp/T/d20210429-13178-13orl16/1065921908-19d45f0c-d695-4332-914d-43bec2bc5531.itmsp'
INFO [2021-04-29 09:22:59.04]: Fetching password for transporter from environment variable named `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`
INFO [2021-04-29 09:22:59.04]: Going to upload updated app to App Store Connect
INFO [2021-04-29 09:22:59.04]: This might take a few minutes. Please don't interrupt the script.
DEBUG [2021-04-29 09:22:59.04]: ITMS_TRANSPORTER_PASSWORD=YourPassword xcrun iTMSTransporter -m upload -u [MASKED] -p @env:ITMS_TRANSPORTER_PASSWORD -f /var/folders/7g/88jlglrx7jxds9qk353rl93w0000gp/T/d20210429-13178-13orl16/1065921908-19d45f0c-d695-4332-914d-43bec2bc5531.itmsp -k 100000 2>&1
DEBUG [2021-04-29 09:26:51.69]: [Transporter]: INFO: An error occurred checking the HEAD for: https://contentdelivery.itunes.apple.com/transporter/repositories/j2se8/latest/repository.xml Operation timed out Exception's name: java.net.ConnectException, Exception's message: Operation timed out
DEBUG [2021-04-29 09:28:07.37]: [Transporter]: INFO: An error occurred checking the HEAD for: https://contentdelivery.itunes.apple.com/transporter/repositories/j2se7/latest/repository.xml Operation timed out Exception's name: java.net.ConnectException, Exception's message: Operation timed out
DEBUG [2021-04-29 09:29:23.35]: [Transporter]: INFO: An error occurred checking the HEAD for: https://contentdelivery.itunes.apple.com/transporter/repositories/j2se6/latest/repository.xml Operation timed out Exception's name: java.net.ConnectException, Exception's message: Operation timed out
DEBUG [2021-04-29 09:30:39.03]: [Transporter]: INFO: An error occurred checking the HEAD for: https://contentdelivery.itunes.apple.com/transporter/repositories/j2se5/latest/repository.xml Operation timed out Exception's name: java.net.ConnectException, Exception's message: Operation timed out
WARN [2021-04-29 09:30:39.07]: [iTMSTransporter] java.lang.reflect.InvocationTargetException
WARN [2021-04-29 09:30:39.07]: [iTMSTransporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
WARN [2021-04-29 09:30:39.07]: [iTMSTransporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
WARN [2021-04-29 09:30:39.08]: [iTMSTransporter] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
WARN [2021-04-29 09:30:39.08]: [iTMSTransporter] 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
WARN [2021-04-29 09:30:39.08]: [iTMSTransporter] 	at com.apple.transporter.launcher.Application.start(Application.java:450)
WARN [2021-04-29 09:30:39.08]: [iTMSTransporter] 	at com.apple.transporter.launcher.Application.main(Application.java:947)
WARN [2021-04-29 09:30:39.08]: [iTMSTransporter] Caused by: java.io.IOException: Could not connect to any repositories
WARN [2021-04-29 09:30:39.08]: [iTMSTransporter] 	at com.apple.transporter.misc.RemoteBundleRepository.getRepositoryUriAndEtag(RemoteBundleRepository.java:227)
WARN [2021-04-29 09:30:39.08]: [iTMSTransporter] 	at com.apple.transporter.misc.RemoteBundleRepository.loadResourcesFromRepository(RemoteBundleRepository.java:141)
WARN [2021-04-29 09:30:39.08]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.downloadNeededBundles(BootstrapperPhase1.java:247)
WARN [2021-04-29 09:30:39.08]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.bootstrap(BootstrapperPhase1.java:97)
WARN [2021-04-29 09:30:39.08]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.bootstrap(BootstrapperPhase1.java:59)
WARN [2021-04-29 09:30:39.08]: [iTMSTransporter] 	at com.apple.transporter.launcher.Launcher.launchBootstrapper(Launcher.java:37)
WARN [2021-04-29 09:30:39.08]: [iTMSTransporter] 	... 6 more
INFO [2021-04-29 09:30:39.08]: iTunes Transporter output above ^
ERROR [2021-04-29 09:30:39.08]: The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
WARN [2021-04-29 09:30:39.12]: upload failed! Error uploading ipa file: 
 

fastlane version 2.177.0.

**Comment by sorianog** [comment]
Might be related to the [App Store Connect outage](https://developer.apple.com/system-status/) (which is now resolved):
<img width="493" alt="Screen Shot 2021-04-28 at 12 34 11 PM" src="https://user-images.githubusercontent.com/13261711/116462335-55bc3f00-a837-11eb-9dad-e026e28cef01.png">

**Comment by max-ott** [comment]
This is a standard timeout, which has nothing to do with fastlane, but Apple's servers.
