### ISSUE TITLE
fastlane update_fastlane not used, Updating fastlane from 2.180.1 to 2.181.0... 

### ISSUE THREAD

**Issue by WangLongONE** [fastlane/fastlane#18616]
inao@xinaodeMacBook-Pro ~ % fastlane update_fastlane 
[✔] 🚀 
[18:10:54]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[18:10:55]: -----------------------------
[18:10:55]: --- Step: update_fastlane ---
[18:10:55]: -----------------------------
[18:10:55]: Looking for updates for fastlane...
[18:10:59]: Updating fastlane from 2.180.1 to 2.181.0... 🚀
[18:10:59]: $ brew upgrade fastlane
Warning: fastlane 2.180.1_1 already installed
[18:11:00]: Finished updating fastlane
[18:11:00]: fastlane.tools successfully updated! I will now restart myself... 😴
[✔] 🚀 
[18:11:01]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[18:11:02]: -----------------------------
[18:11:02]: --- Step: update_fastlane ---
[18:11:02]: -----------------------------

#######################################################################
# fastlane 2.181.0 is available. You are on 2.180.1.
# You should use the latest version.
# Please update using `fastlane update_fastlane`.
#######################################################################

2.181.0 Improvements
* [scan] keep initial xcresult (#18555) via Corey Werner
* [spaceauth] add `--copy_to_clipboard` option to `spaceauth` (#18538) via Roger Oba
* [Ruby 3.0] improve specs for Slack action  (#18512) via Satoshi Namai
* [spaceship] fix case sensitive email issue for Spaceship::Members.find (#18573) via Max Ott
* [supply] upload native symbols for crash symbolication (#18526) via Marcelo Oliveira
* [fastlane][lanemanager] fastlane command suggestion improvement when running using bundler (#18515) via Manish Rathi
* [gym] fix in the gym/runner. When moving mac 'app' silently fails if file already exist in that location. (#18529) via Krzysztof
* [snapshot] added iPhone 12 models to snapshot reports generator (#18535) via Davide
* [fastlane_core][pilot][deliver] fix when polling for build processing to poll for X.Y and

**Comment by WangLongONE** [comment]
xinao@xinaodeMacBook-Pro ~ % fastlane evn
[✔] 🚀 
[18:47:31]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
/usr/local/Cellar/fastlane/2.180.1_1/libexec/gems/highline-1.7.10/lib/highline.rb:624: warning: Using the last argument as keyword parameters is deprecated
[18:47:32]: Could not find fastlane in current directory. Make sure to have your fastlane
configuration files inside a folder called "fastlane". Would you like to set fastlane up?
(y/n)
/usr/local/Cellar/fastlane/2.180.1_1/libexec/gems/highline-1.7.10/lib/highline.rb:624: warning: Using the last argument as keyword parameters is deprecated
                                                              y
[⠹] Looking for iOS and Android projects in current directory...
Looking for related GitHub issues on fastlane/fastlane...

[⠸] Looking for iOS and Android projects in current directory...➡️  Operation not permitted - Library/Application Support/MobileSync (Errno::EPERM)
    https://github.com/fastlane/fastlane/issues/16611 [closed] 6 💬
    19 Aug 2020

➡️  fastlane tests crash - access denied on mobile sync dir
    https://github.com/fastlane/fastlane/issues/16336 [closed] 1 💬
    20 Jun 2020

➡️   [!] Operation not permitted - Library/Application Support/MobileSync (Errno::EPERM) 
    https://github.com/fastlane/fastlane/issues/15677 [closed] 0 💬
    18 Jan 2020

🔗  You can ⌘ + double-click on links to open them directly in your browser.

#######################################################################
# fastlane 2.181.0 is available. You are on 2.180.1.
# You should use the latest version.
# Please update using `fastlane update_fastlane`.
#######################################################################
# Run `gem cleanup` from time to time to speed up fastlane
#######################################################################
[⠇] Looking for iOS and Android projects in current directory...
2.181.0 Improvements
* [scan] keep initial xcresult (#18555) via Corey Werner
* [spaceauth] add `--copy_to_clipboard` option to `spaceauth` (#18538) via Roger Oba
* [Ruby 3.0] improve specs for Slack action  (#18512) via Satoshi Namai
* [spaceship] fix case sensitive email issue for Spaceship::Members.find (#18573) via Max Ott
* [supply] upload native symbols for crash symbolication (#18526) via Marcelo Oliveira
* [fastlane][lanemanager] fastlane command suggestion improvement when running using bundler (#18515) via Manish Rathi
* [gym] fix in the gym/runner. When moving mac 'app' silently fails if file already exist in that location. (#18529) via Krzysztof
* [snapshot] added iPhone 12 models to snapshot reports generator (#18535) via Davide
* [fastlane_core][pilot][deliver] fix when polling for build processing to poll for X.Y and X.Y.0 (#18547) via Josh Holtz
* [action][ensure_env_vars] efficiency improvement (#18522) via Manish Rathi
* [fastlane][action] fix git_branch when not in a git repo (#18525) via Josh Holtz

Please update using `fastlane update_fastlane`

**Comment by max-ott** [comment]
This is probably related to how you installed fastlane in the first place. (e.g. brew vs. bundler, using sudo etc.)
