### ISSUE TITLE
`fastlane match --readonly` doesn't work with `mac_installer_distribution`

### ISSUE THREAD

**Issue by mandrigin** [fastlane/fastlane#18611]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

`fastlane match mac_installer_distribution --readonly` doesn't work with `mac_installer_distribution`

Steps to reproduce:
1) Do `fastlane match mac_installer_distribution`, wait for it to succeed
2) Do `fastlane match mac_installer_distribution --readonly` on the same machine

Expected:
- success

Actual:

```
[21:46:33]: No matching provisioning profiles found for 'Unknown_com.*********.provisionprofile'
[21:46:33]: A new one cannot be created because you enabled `readonly`
[21:46:33]: Provisioning profiles in your repo for type `mac_installer_distribution`:
[21:46:33]: - 'AppStore_com.*********.provisionprofile'
[21:46:33]: If you are certain that a profile should exist, double-check the recent changes to your match repository

[!] No matching provisioning profiles found and can not create a new one because you enabled `readonly`. Check the output above for more information.
```

##### Command executed

fastlane match mac_installer_distribution --readonly

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> fastlane match mac_installer_distribution --readonly
[✔] 🚀
[21:53:28]: fastlane detected a Gemfile in the current directory
[21:53:28]: However, it seems like you didn't use `bundle exec`
[21:53:28]: To launch fastlane faster, please use
[21:53:28]:
[21:53:28]: $ bundle exec fastlane match mac_installer_distribution --readonly
[21:53:28]:
[21:53:28]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[21:53:30]: Successfully loaded '/Users/anonymous/src/github.com/sample/app/desktop/macos/Matchfile' 📄

+----------------+-----------------------------+
|      Detected Values from './Matchfile'      |
+----------------+-----------------------------+
| git_url        | git@github.com:****/ca.git |
| storage_mode   | git                         |
| platform       | macos                       |
| type           | appstore                    |
| app_identifier | ["*********"]    |
| username       | ****@****m                  |
| profile_name   | AppStore                    |
+----------------+-----------------------------+

+--------------------------------+-----------------------------+
|                  Summary for match 2.181.0                   |
+--------------------------------+-----------------------------+
| readonly                       | true                        |
| type                           | mac_installer_distribution  |
| generate_apple_certs           | true                        |
| skip_provisioning_profiles     | false                       |
| app_identifier                 | ["*********"]               |
| username                       | ****@****m                  |
| storage_mode                   | git                         |
| git_url                        | git@github.com:****/ca.git |
| git_branch                     | master                      |
| shallow_clone                  | false                       |
| clone_branch_directly          | false                       |
| keychain_name                  | login.keychain              |
| force                          | false                       |
| force_for_new_devices          | false                       |
| skip_confirmation              | false                       |
| skip_docs                      | false                       |
| platform                       | macos                       |
| derive_catalyst_app_identifier | false                       |
| profile_name                   | AppStore                    |
| fail_on_name_taken             | false                       |
| skip_certificate_matching      | false                       |
| skip_set_partition_list        | false                       |
| verbose                        | false                       |
+--------------------------------+-----------------------------+

[21:53:30]: Cloning remote git repo...
[21:53:30]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[21:53:32]: Checking out branch master...
[21:53:32]: 🔓  Successfully decrypted certificates repo
[21:53:32]: Installing certificate...

+-------------------+---------------------------------------------+
|                      Installed Certificate                      |
+-------------------+---------------------------------------------+
| User ID           | ****                                        |
| Common Name       | Apple Distribution: ***** Inc. (Q63J5YSLG3) |
| Organisation Unit | Q63J5YSLG3                                  |
| Organisation      | ***** Inc.                                  |
| Country           | US                                          |
| Start Datetime    | 2021-04-27 18:40:14 UTC                     |
| End Datetime      | 2022-04-27 18:40:13 UTC                     |
+-------------------+---------------------------------------------+

[21:53:33]: No matching provisioning profiles found for 'Unknown_com.*****.*****.provisionprofile'
[21:53:33]: A new one cannot be created because you enabled `readonly`
[21:53:33]: Provisioning profiles in your repo for type `mac_installer_distribution`:
[21:53:33]: - 'AppStore_com.*****.*****.provisionprofile'
[21:53:33]: If you are certain that a profile should exist, double-check the recent changes to your match repository

[!] No matching provisioning profiles found and can not create a new one because you enabled `readonly`. Check the output above for more information. </pre>
</details>

### Environment

<details>
  <pre><details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 11.2.3                                                  |
| Ruby                        | 2.7.3                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.30.1 (Apple Git-130)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.181.0/libexec/bin/fastlane |
| Host                        | macOS 11.2.3 (20D91)                                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.7/2.7.3/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                             |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 12.5                                                    |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.181.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.4.0        |
| slack-notifier                | 2.3.2        |
| atomos                        | 0.1.3        |
| CFPropertyList                | 3.0.3        |
| claide                        | 1.0.3        |
| colored2                      | 3.1.2        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| plist                         | 3.6.0        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| multipart-post                | 2.0.0        |
| word_wrap                     | 1.0.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| artifactory                   | 3.0.15       |
| babosa                        | 1.0.4        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| excon                         | 0.80.1       |
| faraday-excon                 | 1.1.0        |
| faraday-net_http              | 1.0.1        |
| faraday-net_http_persistent   | 1.1.0        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.4.1        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.3        |
| gh_inspector                  | 1.1.3        |
| json                          | 2.3.0        |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| xcpretty-travis-formatter     | 1.0.1        |
| dotenv                        | 2.7.6        |
| bundler                       | 2.2.15       |
| simctl                        | 1.6.8        |
| jwt                           | 2.2.3        |
| uber                          | 0.1.0        |
| declarative                   | 0.0.20       |
| trailblazer-option            | 0.1.1        |
| representable                 | 3.1.1        |
| retriable                     | 3.1.2        |
| mini_mime                     | 1.1.0        |
| multi_json                    | 1.15.0       |
| signet                        | 0.15.0       |
| memoist                       | 0.16.2       |
| os                            | 1.1.1        |
| googleauth                    | 0.16.1       |
| httpclient                    | 2.8.3        |
| google-api-client             | 0.38.0       |
| google-cloud-env              | 1.5.0        |
| google-cloud-errors           | 1.1.0        |
| google-cloud-core             | 1.6.0        |
| rexml                         | 3.2.3.1      |
| webrick                       | 1.6.1        |
| google-apis-core              | 0.3.0        |
| google-apis-iamcredentials_v1 | 0.3.0        |
| google-apis-storage_v1        | 0.3.0        |
| rake                          | 13.0.3       |
| digest-crc                    | 0.6.3        |
| google-cloud-storage          | 1.31.0       |
| emoji_regex                   | 3.2.2        |
| jmespath                      | 1.4.0        |
| aws-partitions                | 1.446.0      |
| aws-eventstream               | 1.1.1        |
| aws-sigv4                     | 1.2.3        |
| aws-sdk-core                  | 3.114.0      |
| aws-sdk-kms                   | 1.43.0       |
| aws-sdk-s3                    | 1.93.1       |
| uri                           | 0.10.0       |
| forwardable                   | 1.3.1        |
| logger                        | 1.4.2        |
| cgi                           | 0.1.0        |
| date                          | 3.0.0        |
| timeout                       | 0.1.0        |
| stringio                      | 0.1.0        |
| zlib                          | 1.1.0        |
| ipaddr                        | 1.2.2        |
| openssl                       | 2.1.2        |
| ostruct                       | 0.2.0        |
| strscan                       | 1.0.3        |
| delegate                      | 0.1.0        |
| fileutils                     | 1.4.1        |
| io-console                    | 0.5.6        |
| singleton                     | 0.1.0        |
| open3                         | 0.1.0        |
| yaml                          | 0.1.0        |
| psych                         | 3.1.0        |
| mutex_m                       | 0.1.0        |
</details>

*generated on:* **2021-04-27**
</details> </pre>
</details>

**Comment by lucgrabowski** [comment]
Hi, @mandrigin what is the name of generated profile? "AppStore" based on `profile_name`? Could you check it in match repository? I think that match generates a profile with custom name and later when you use `--readonly` it uses automatically generated name instead, which starts with `Unknown`. Prefix is taken from https://github.com/fastlane/fastlane/blob/f06d785b60575227744c6436a298a15578af3fb5/match/lib/match/generator.rb#L113-L119

**Comment by mandrigin** [comment]
its definitely `AppStore_` in one place and `Unknown_` in another, I don't remember which is which.

**Comment by lucgrabowski** [comment]
Could you remove `profile_name` from configuration and run both commands (with and without `readonly`)?

**Comment by mandrigin** [comment]
hmm, my `Matchfile` looks like that

```
git_url("git@github.com:***/**.git")

storage_mode("git")

platform("macos")

type("mac_installer_distribution") # The default type, can be: appstore, adhoc, enterprise or development

app_identifier(["com.***.**-app" ])

username("igor.mandrigin*****") # Your Apple Developer Portal username
```

(redacted personal info)

I don't see any `profile_name` here...

**Comment by lucgrabowski** [comment]
Strangely, in the output you showed in the issue description there was `profile_name`:
` fastlane match mac_installer_distribution --readonly
[✔] 🚀
[21:53:28]: fastlane detected a Gemfile in the current directory
[21:53:28]: However, it seems like you didn't use `bundle exec`
[21:53:28]: To launch fastlane faster, please use
[21:53:28]:
[21:53:28]: $ bundle exec fastlane match mac_installer_distribution --readonly
[21:53:28]:
[21:53:28]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[21:53:30]: Successfully loaded '/Users/anonymous/src/github.com/sample/app/desktop/macos/Matchfile' 📄

+----------------+-----------------------------+

|      Detected Values from './Matchfile'      |

+----------------+-----------------------------+

| git_url        | git@github.com:/ca.git |

| storage_mode   | git                         |

| platform       | macos                       |

| type           | appstore                    |

| app_identifier | ["*****"]    |

| username       | ****@****m                  |

| profile_name   | AppStore                    |

+----------------+-----------------------------+`
