### ISSUE TITLE
Flutter: Getting error while finding apk using to release on internal app sharing using fastlane

### ISSUE THREAD

**Issue by DhavalRKansara** [fastlane/fastlane#18624]
**FastFile:**
```
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
 desc 'Build a signed release APK & deploy to Internal App Sharing'
 lane :sign_apk_build do
   gradle(
     task: 'bundle',
     build_type: 'Release',
     print_command: false,
     properties: {
       'android.injected.signing.store.file' => ENV['StoreFile'],
       'android.injected.signing.store.password' => ENV['StorePassword'],
       'android.injected.signing.key.alias' => ENV['KeyAlias'],
       'android.injected.signing.key.password' => ENV['KeyPassword']
     }
   )

   upload_internal_sharing
 end
 desc "Deploy a new version to the Google Play"
 private_lane :upload_internal_sharing do
 upload_to_play_store_internal_app_sharing
 lane_context[SharedValues::PLATFORM_NAME]
 end
end
``` 

- After running command `fastlane  android sign_apk_build` inside Android folder getting below error: 

```
[20:28:06]: Couldn't find any new signed apk files...
[20:28:06]: ------------------------------------------------------------
[20:28:06]: --- Step: Switch to android upload_internal_sharing lane ---
[20:28:06]: ------------------------------------------------------------
[20:28:06]: Cruising over to lane 'android upload_internal_sharing' 🚖
[20:28:06]: -------------------------------------------------------
[20:28:06]: --- Step: upload_to_play_store_internal_app_sharing ---
[20:28:06]: -------------------------------------------------------
[20:28:06]: Cruising back to lane 'android sign_apk_build' 🚘

+------+------------------------------------------------+-------------+
|                          fastlane summary                           |
+------+------------------------------------------------+-------------+
| Step | Action                                         | Time (in s) |
+------+------------------------------------------------+-------------+
| 1    | default_platform                               | 0           |
| 2    | bundleRelease                                  | 22          |
| 3    | Switch to android upload_internal_sharing lane | 0           |
| 4    | upload_to_play_store_internal_app_sharing      | 0           |
+------+------------------------------------------------+-------------+

[20:28:06]: fastlane.tools finished successfully 🎉
```

**Comment by DhavalRKansara** [comment]
`fastlane env`

```
[20:33:55]: fastlane detected a Gemfile in the current directory
[20:33:55]: However, it seems like you didn't use `bundle exec`
[20:33:55]: To launch fastlane faster, please use
[20:33:55]: 
[20:33:55]: $ bundle exec fastlane env
[20:33:55]: 
[20:33:55]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[20:34:01]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 11.2.3                                                  |
| Ruby                        | 2.7.2                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.23.0                                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.171.0/libexec/bin/fastlane |
| Host                        | macOS 11.2.3 (20D91)                                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.7/2.7.2/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                              |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 12.4                                                    |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
 desc 'Build a signed release APK & deploy to Internal App Sharing'
 lane :sign_apk_build do
   gradle(
     task: 'bundle',
     build_type: 'Release',
     print_command: false,
     properties: {
       'android.injected.signing.store.file' => ENV['storeFile'],
       'android.injected.signing.store.password' => ENV['storePassword'],
       'android.injected.signing.key.alias' => ENV['keyAlias'],
       'android.injected.signing.key.password' => ENV['keyPassword']
     }
   )

   upload_internal_sharing
 end
 desc "Deploy a new version to the Google Play"
 private_lane :upload_internal_sharing do
 upload_to_play_store_internal_app_sharing
 lane_context[SharedValues::PLATFORM_NAME]
 end
end


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("/Users/dhavalkansara/Flutter Development/project/my-app/android/api-key.json") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("com.me****R.myapp") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.181.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.4.0        |
| slack-notifier                | 2.3.2        |
| atomos                        | 0.1.3        |
| CFPropertyList                | 3.0.3        |
| claide                        | 1.0.3        |
| colored2                      | 3.1.2        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| plist                         | 3.6.0        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| multipart-post                | 2.0.0        |
| word_wrap                     | 1.0.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| artifactory                   | 3.0.15       |
| babosa                        | 1.0.4        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| gh_inspector                  | 1.1.3        |
| mini_magick                   | 4.11.0       |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| dotenv                        | 2.7.6        |
| bundler                       | 2.1.4        |
| simctl                        | 1.6.8        |
| retriable                     | 3.1.2        |
| httpclient                    | 2.8.3        |
| google-api-client             | 0.38.0       |
| uri                           | 0.10.0       |
| excon                         | 0.81.0       |
| ruby2_keywords                | 0.0.4        |
| faraday-net_http_persistent   | 1.1.0        |
| faraday-net_http              | 1.0.1        |
| faraday-excon                 | 1.1.0        |
| faraday                       | 1.4.1        |
| fastimage                     | 2.2.3        |
| json                          | 2.5.1        |
| naturally                     | 2.2.1        |
| xcpretty-travis-formatter     | 1.0.1        |
| jwt                           | 2.2.3        |
| trailblazer-option            | 0.1.1        |
| declarative                   | 0.0.20       |
| uber                          | 0.1.0        |
| representable                 | 3.1.1        |
| mini_mime                     | 1.1.0        |
| multi_json                    | 1.15.0       |
| signet                        | 0.15.0       |
| os                            | 1.1.1        |
| memoist                       | 0.16.2       |
| googleauth                    | 0.16.2       |
| rake                          | 13.0.3       |
| digest-crc                    | 0.6.3        |
| webrick                       | 1.7.0        |
| rexml                         | 3.2.5        |
| google-apis-core              | 0.3.0        |
| google-apis-storage_v1        | 0.3.0        |
| google-apis-iamcredentials_v1 | 0.3.0        |
| google-cloud-errors           | 1.1.0        |
| google-cloud-env              | 1.5.0        |
| google-cloud-core             | 1.6.0        |
| google-cloud-storage          | 1.31.0       |
| emoji_regex                   | 3.2.2        |
| aws-eventstream               | 1.1.1        |
| aws-sigv4                     | 1.2.3        |
| aws-partitions                | 1.449.0      |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.114.0      |
| aws-sdk-kms                   | 1.43.0       |
| aws-sdk-s3                    | 1.94.0       |
| forwardable                   | 1.3.1        |
| logger                        | 1.4.2        |
| cgi                           | 0.1.0        |
| date                          | 3.0.0        |
| timeout                       | 0.1.0        |
| stringio                      | 0.1.0        |
| zlib                          | 1.1.0        |
| ipaddr                        | 1.2.2        |
| openssl                       | 2.1.2        |
| ostruct                       | 0.2.0        |
| strscan                       | 1.0.3        |
| delegate                      | 0.1.0        |
| fileutils                     | 1.4.1        |
| io-console                    | 0.5.6        |
| singleton                     | 0.1.0        |
| open3                         | 0.1.0        |
| yaml                          | 0.1.0        |
| psych                         | 3.1.0        |
| mutex_m                       | 0.1.0        |
</details>


*generated on:* **2021-04-29**
```
[20:34:02]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
/usr/local/Cellar/fastlane/2.171.0/libexec/gems/highline-1.7.10/lib/highline.rb:624: warning: Using the last argument as keyword parameters is deprecated
[20:34:02]: 🙄  Wow, that's a lot of markdown text... should fastlane put it into your clipboard, so you can easily paste it on GitHub? (y/n)
/usr/local/Cellar/fastlane/2.171.0/libexec/gems/highline-1.7.10/lib/highline.rb:624: warning: Using the last argument as keyword parameters is deprecated
                                                                                                                                                         y
[20:34:15]: Successfully copied markdown into your clipboard 🎨
[20:34:15]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅
```

```

**Comment by vmeditab** [comment]
I am also facing the same issue...
