### ISSUE TITLE
supply issue when both native symbols and ProGuard mappings are supplied

### ISSUE THREAD

**Issue by ff-ahumberston** [fastlane/fastlane#18623]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
upload_to_play_store fails when both native symbols and ProGuard mappings are supplied

While the merge of https://github.com/fastlane/fastlane/pull/18526 into fastlane 2.181.0 is most welcome it appears to be incomplete.

After the adopting --mapping_paths as suggested in the pull request the error below was encountered.

The absence of a version code number in the 2nd message is significant.

With reference to fastlane/supply/lib/supply/uploader.rb, the apk_version_codes array receives one entry per APK or AAB to upload. In this situation 1 entry is added for the single AAB file.

Later, upload_mapping() uses zip() to pair each mapping path with a code from apk_version_codes. Unsuccessfully - as mapping_paths contains 2 entries while apk_version_codes still contains just 1.

A possible solution is to split the paths by type - "proguard" or "nativeCode" - before applying zip() to each type in turn.

##### Command executed
bundle exec fastlane supply --package_name "com.xxx.yyy" \
 --aab "build/outputs/bundle/release/yyy-release.aab" -d \
 --mapping_paths build/outputs/mapping/release/mapping.txt,build/outputs/native-debug-symbols/release/native-debug-symbols.zip   \
 --track internal --skip_upload_metadata   --skip_upload_images \
 --skip_upload_screenshots --json_key ~ffadmin/supply_google_key.json

##### Complete output when running fastlane, including the stack trace and command used

[11:46:45]: Preparing aab at path 'build/outputs/bundle/release/yyy-release.aab' for upload...
[11:48:16]: Preparing mapping at path 'build/outputs/mapping/release/mapping.txt', version code 47 for upload...
[11:48:22]: Preparing mapping at path 'build/outputs/native-debug-symbols/release/native-debug-symbols.zip', version code  for upload...
[!] Google Api Error: invalid: Invalid value at 'apk_version_code' (TYPE_INT32), "" - Invalid value at 'apk_version_code' (TYPE_INT32), ""

### Environment

[✔] 🚀
[14:59:10]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.2.3                                      |
| Ruby                        | 2.6.5                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.rbenv/versions/2.6.5/bin/fastlane        |
| Host                        | macOS 11.2.3 (20D91)                        |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.5/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.4                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.181.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-appcenter | 1.11.0  | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.5.0        |
| bundler                       | 2.2.14       |
| rake                          | 13.0.3       |
| CFPropertyList                | 3.0.3        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| artifactory                   | 3.0.15       |
| atomos                        | 0.1.3        |
| aws-eventstream               | 1.1.1        |
| aws-partitions                | 1.449.0      |
| aws-sigv4                     | 1.2.3        |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.114.0      |
| aws-sdk-kms                   | 1.43.0       |
| aws-sdk-s3                    | 1.94.0       |
| babosa                        | 1.0.4        |
| claide                        | 1.0.3        |
| colored                       | 1.2          |
| colored2                      | 3.1.2        |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| digest-crc                    | 0.6.3        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| dotenv                        | 2.7.6        |
| emoji_regex                   | 3.2.2        |
| excon                         | 0.81.0       |
| faraday-excon                 | 1.1.0        |
| faraday-net_http              | 1.0.1        |
| faraday-net_http_persistent   | 1.1.0        |
| multipart-post                | 2.0.0        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.4.1        |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.3        |
| gh_inspector                  | 1.1.3        |
| jwt                           | 2.2.3        |
| memoist                       | 0.16.2       |
| multi_json                    | 1.15.0       |
| os                            | 1.1.1        |
| signet                        | 0.15.0       |
| googleauth                    | 0.16.2       |
| httpclient                    | 2.8.3        |
| mini_mime                     | 1.1.0        |
| trailblazer-option            | 0.1.1        |
| uber                          | 0.1.0        |
| representable                 | 3.1.1        |
| retriable                     | 3.1.2        |
| google-api-client             | 0.38.0       |
| rexml                         | 3.2.5        |
| webrick                       | 1.7.0        |
| google-apis-core              | 0.3.0        |
| google-apis-iamcredentials_v1 | 0.3.0        |
| google-apis-storage_v1        | 0.3.0        |
| google-cloud-env              | 1.5.0        |
| google-cloud-errors           | 1.1.0        |
| google-cloud-core             | 1.6.0        |
| google-cloud-storage          | 1.31.0       |
| json                          | 2.5.1        |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| plist                         | 3.6.0        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| simctl                        | 1.6.8        |
| slack-notifier                | 2.3.2        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| word_wrap                     | 1.0.0        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| xcpretty-travis-formatter     | 1.0.1        |
| fastlane-plugin-appcenter     | 1.11.0       |
</details>

*generated on:* **2021-04-29**
</details>

**Comment by aberaud** [comment]
@capyvara Any idea?

**Comment by capyvara** [comment]
That's strange because if so, the multiple mapping_paths maybe wasn't working before?

**Comment by luka-piljek-nb** [comment]
Wouldn't it be preferable to have a separate parameter for symbols (e.g. something like "--symbols_paths") anyway?
It would make it both more descriptive and it would not mess with the previously well understood and working parameter.
Was there some technical problem that would make adding a new parameter much more complicated than this?

**Comment by capyvara** [comment]
Google play call all these "mappings" despite being a text or a symbols zip and are upload on the same edit, that's why I reused the same parameter.

**Comment by luka-piljek-nb** [comment]
As far as I can tell, google calls them collectively "deobfuscation files" and you have to specify the type when you upload them.
https://developers.google.com/android-publisher/api-ref/rest/v3/edits.deobfuscationfiles
Anyway, this was just a suggestion that made sense to me. I do appreciate your work on this as this is something we would like to automate as well.

**Comment by remcoanker** [comment]
Is there a solution for this issue? I'm trying to upload a mapping file and debug symbols, but supply can only handle one per apk/aab.

https://github.com/fastlane/fastlane/blob/430fcb19fc4fca33901c91f619b2324cdb0c875d/supply/lib/supply/uploader.rb#L11-L14
Only one version code is sent to `upload_mapping` per apk/aab.

https://github.com/fastlane/fastlane/blob/430fcb19fc4fca33901c91f619b2324cdb0c875d/supply/lib/supply/uploader.rb#L303-L311
`zip` only adds the version code the first `mapping_path`.

Which leads to an error.

> [11:50:30]: Preparing aab at path '../build/app/outputs/bundle/release/app-release.aab' for upload...
[11:51:23]: Preparing mapping at path '../build/app/outputs/mapping/release/mapping.txt', version code 37 for upload...
[11:51:28]: Preparing mapping at path '../symbols/playstore.zip', version code  for upload...
+------------------+-------------------------+
|                Lane Context               |
+------------------+-------------------------+
| DEFAULT_PLATFORM | android                 |
| PLATFORM_NAME    | android                 |
| LANE_NAME        | android deploy_internal |
+------------------+-------------------------+
[11:51:38]: Google Api Error: INVALID_ARGUMENT: Invalid value at 'apk_version_code' (TYPE_INT32), "" - Invalid value at 'apk_version_code' (TYPE_INT32), ""

**Comment by JollyMonk2** [comment]
> Wouldn't it be preferable to have a separate parameter for symbols (e.g. something like "--symbols_paths") anyway?
> It would make it both more descriptive and it would not mess with the previously well understood and working parameter.
> Was there some technical problem that would make adding a new parameter much more complicated than this?

Good one. Thanks for sharing a nice piece of info.

**Comment by rafagan** [comment]
Any progress on it? Same problem here

**Comment by jonameson** [comment]
I'm having similar issues. Thanks for any updates or workarounds.

**Comment by rusitschka** [comment]
> `zip` only adds the version code the first `mapping_path`.

Using `product` instead of `zip` solves the issue for me.

**Comment by jonameson** [comment]
> > `zip` only adds the version code the first `mapping_path`.
> 
> Using `product` instead of `zip` solves the issue for me.

Could you expand on the workaround? You mean you rename the file to .product instead of .zip?

**Comment by rusitschka** [comment]
Although the exception is gone I think this is still not working as expected:

```
upload_to_play_store(
      aab: "Build/Game.aab",
      skip_upload_apk: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      package_name: "com.package.name",
      track: "internal",
      mapping_paths: ["Build/Game.symbols.zip", "Build/Game_mapping.txt"],
      json_key: "two_players_android_play_store.json"
)
```

Seems to upload mappings and symbols but in Play Console only mappings show up. Uploading symbols via Play Console works fine. Anyone else experiencing this?

**Comment by jonameson** [comment]
Alright, as @rusitschka mentioned, the patch did not work. Interestingly whatever was last placed on the mapping_paths array is what will be uploaded. So in my case the symbols where last and they got uploaded.
`mapping_paths: ["releases/googleQa/mapping.txt", "releases/googleQa/native_debug_sym.zip"])`

I think we're almost there with a working patch!

**Comment by rusitschka** [comment]
I just did another release and now both mapping.txt and symbols.zip were attached to the build. So it seems to work at least sometimes...
