### ISSUE TITLE
fastlane multi_scan: undefined method `length' for nil:NilClass

### ISSUE THREAD

**Issue by tasvir-rohila-carsales** [fastlane/fastlane#18639]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm trying to use `multi_scan` fastlane plugin to be able to retry failing UI tests. But when I run the `ui_tests` lane which internally executes the `multi_scan` command via Fastfile, it fails with below mentioned error.

Expected: This plugin should be able to run `multi_scan` successfully and retry any failing UI tests as per `try_count:` property.

##### Command executed

IOS_APP=my_awesome_app XCODE_VERSION=12.4 FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT=10 FASTLANE_XCODEBUILD_SETTINGS_RETRIES=3 bundle exec fastlane ui_tests

##### Complete output when running fastlane, including the stack trace and command used

<details>
<pre>
+------+--------------------------------------------------+-------------+
|                           fastlane summary                            |
+------+--------------------------------------------------+-------------+
| Step | Action                                           | Time (in s) |
+------+--------------------------------------------------+-------------+
| 1    | Verifying fastlane version                       | 0           |
| 2    | default_platform                                 | 0           |
| 3    | Switch to ios close_simulators lane              | 0           |
| 4    | killall -9 Simulator || echo "Simulator already  | 0           |
|      | shutdown"                                        |             |
| 5    | cocoapods                                        | 71          |
| 6    | Switch to ios run_test_plan lane                 | 0           |
| 7    | Switch to ios set_xcode_version lane             | 0           |
| 8    | xcversion                                        | 1           |
| 💥   | multi_scan                                       | 625         |
+------+--------------------------------------------------+-------------+

[13:50:35]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Fastlane DELIVER does not have the option to specify api_key_path
    https://github.com/fastlane/fastlane/issues/17363 [closed] 5 💬
    01 Dec 2020

➡️  upload_to_testflight hangs during upload
    https://github.com/fastlane/fastlane/issues/18286 [closed] 5 💬
    a week ago

➡️  Completely new app gets: You must provide a value for the attribute 'usesNonExemptEncryption' with this request
    https://github.com/fastlane/fastlane/issues/16645 [closed] 11 💬
    15 Sep 2020

and 46 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60length%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane Users/machine.user/.rbenv/versions/2.6.6/bin/fastlane)
NoMethodError: [!] undefined method `length' for nil:NilClass
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-plugin-test_center-3.15.3/lib/fastlane/plugin/test_center/actions/testplans_from_scheme.rb:33:in `schemes'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-plugin-test_center-3.15.3/lib/fastlane/plugin/test_center/actions/testplans_from_scheme.rb:5:in `run'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-plugin-test_center-3.15.3/lib/fastlane/plugin/test_center/helper/test_collector.rb:164:in `only_testing_from_testplan'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-plugin-test_center-3.15.3/lib/fastlane/plugin/test_center/helper/test_collector.rb:53:in `derive_only_testing'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-plugin-test_center-3.15.3/lib/fastlane/plugin/test_center/helper/test_collector.rb:62:in `testable_tests_hash_from_options'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-plugin-test_center-3.15.3/lib/fastlane/plugin/test_center/helper/test_collector.rb:84:in `derive_batches_from_tests'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-plugin-test_center-3.15.3/lib/fastlane/plugin/test_center/helper/test_collector.rb:27:in `initialize_batches'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-plugin-test_center-3.15.3/lib/fastlane/plugin/test_center/helper/test_collector.rb:18:in `initialize'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-plugin-test_center-3.15.3/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:69:in `new'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-plugin-test_center-3.15.3/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:69:in `setup_testcollector'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-plugin-test_center-3.15.3/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:26:in `initialize'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-plugin-test_center-3.15.3/lib/fastlane/plugin/test_center/actions/multi_scan.rb:37:in `new'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-plugin-test_center-3.15.3/lib/fastlane/plugin/test_center/actions/multi_scan.rb:37:in `run'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:172:in `block (2 levels) in parsing_binding'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/lane.rb:33:in `call'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:190:in `block (2 levels) in parsing_binding'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/lane.rb:33:in `call'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.181.0/bin/fastlane:23:in `<top (required)>'
Users/machine.user/.rbenv/versions/2.6.6/bin/fastlane:23:in `load'
Users/machine.user/.rbenv/versions/2.6.6/bin/fastlane:23:in `<top (required)>'
[13:50:36]: Shutting down B5F09472-CADE-4605-8345-356F98AC9314
[13:50:43]: Shutting down 2D83E9B5-716C-49DF-A84A-9FF776F3918C

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.15.5                                          |
| Ruby                        | 2.6.6                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.24.3 (Apple Git-128)               |
| Installation Source         | ~/.rbenv/versions/2.6.6/bin/fastlane             |
| Host                        | Mac OS X 10.15.5 (19F101)                        |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.6/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode_12.4.app/Contents/Developer/ |
| Xcode Version               | 12.4                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_AU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
require 'fileutils'

fastlane_version "2.144.0"

default_platform :ios

build_dir = "build"

# default version range of xcode to build with if one is not passed in
xcode_version = "~> 12.0"

private_lane :set_xcode_version do
  xcode_version = ENV["XCODE_VERSION"]
  UI.user_error!("No XCODE_VERSION environment variable specified") if xcode_version == nil

  xcversion version: xcode_version 
end

platform :ios do |options|

  private_lane :run_test_plan do |options|
    app = ENV["IOS_APP"]
    UI.user_error!("No IOS_APP environment variable specified") if app == nil

    scheme = schemes[app]
    testplan = options[:testplan]

    set_xcode_version
    
    # build the source code and run the tests
    multi_scan(
      clean: true,
      scheme: scheme,
      devices: ["iPhone SE (2nd generation)", "iPad (8th generation)"],
      derived_data_path: build_dir,
      output_directory: build_dir,
      reset_simulator: true,
      prelaunch_simulator: true,
      include_simulator_logs: false,
      try_count: 3, # retry _failing_ tests up to three times^1.
      testplan: testplan
    )
  end

  desc "Run UI tests"
  lane :ui_tests do
    app = ENV["IOS_APP"]
    UI.user_error!("No IOS_APP environment variable specified") if app == nil
    run_test_plan(testplan: myAwesomeAppUITests)  
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
team_id "XXXXXXXXX"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.181.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.2.7   | ✅ Up-To-Date  |
| fastlane-plugin-xcconfig                  | 2.0.0   | ✅ Up-To-Date  |
| fastlane-plugin-test_center               | 3.15.3  | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.3.0        |
| slack-notifier                            | 2.3.2        |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.7.0        |
| terminal-table                            | 1.8.0        |
| addressable                               | 2.7.0        |
| multipart-post                            | 2.0.0        |
| word_wrap                                 | 1.0.0        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| artifactory                               | 3.0.15       |
| colored                                   | 1.2          |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| faraday_middleware                        | 1.0.0        |
| gh_inspector                              | 1.1.3        |
| rubyzip                                   | 2.3.0        |
| security                                  | 0.1.3        |
| bundler                                   | 2.1.4        |
| simctl                                    | 1.6.8        |
| retriable                                 | 3.1.2        |
| httpclient                                | 2.8.3        |
| google-api-client                         | 0.38.0       |
| nanaimo                                   | 0.3.0        |
| colored2                                  | 3.1.2        |
| claide                                    | 1.0.3        |
| CFPropertyList                            | 3.0.3        |
| atomos                                    | 0.1.3        |
| xcodeproj                                 | 1.19.0       |
| plist                                     | 3.6.0        |
| public_suffix                             | 4.0.6        |
| tty-screen                                | 0.8.1        |
| babosa                                    | 1.0.4        |
| excon                                     | 0.81.0       |
| unf_ext                                   | 0.0.7.7      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| http-cookie                               | 1.0.3        |
| ruby2_keywords                            | 0.0.4        |
| faraday-net_http_persistent               | 1.1.0        |
| faraday-net_http                          | 1.0.1        |
| faraday-excon                             | 1.1.0        |
| faraday                                   | 1.4.1        |
| faraday-cookie_jar                        | 0.0.7        |
| fastimage                                 | 2.2.3        |
| json                                      | 2.5.1        |
| mini_magick                               | 4.11.0       |
| naturally                                 | 2.2.1        |
| xcpretty-travis-formatter                 | 1.0.1        |
| dotenv                                    | 2.7.6        |
| jwt                                       | 2.2.3        |
| trailblazer-option                        | 0.1.1        |
| declarative                               | 0.0.20       |
| uber                                      | 0.1.0        |
| representable                             | 3.1.1        |
| mini_mime                                 | 1.1.0        |
| multi_json                                | 1.15.0       |
| signet                                    | 0.15.0       |
| os                                        | 1.1.1        |
| memoist                                   | 0.16.2       |
| googleauth                                | 0.16.2       |
| rake                                      | 13.0.3       |
| digest-crc                                | 0.6.3        |
| webrick                                   | 1.7.0        |
| rexml                                     | 3.2.5        |
| google-apis-core                          | 0.3.0        |
| google-apis-storage_v1                    | 0.3.0        |
| google-apis-iamcredentials_v1             | 0.3.0        |
| google-cloud-errors                       | 1.1.0        |
| google-cloud-env                          | 1.5.0        |
| google-cloud-core                         | 1.6.0        |
| google-cloud-storage                      | 1.31.0       |
| emoji_regex                               | 3.2.2        |
| aws-eventstream                           | 1.1.1        |
| aws-sigv4                                 | 1.2.3        |
| aws-partitions                            | 1.451.0      |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.114.0      |
| aws-sdk-kms                               | 1.43.0       |
| aws-sdk-s3                                | 1.94.0       |
| forwardable                               | 1.2.0        |
| logger                                    | 1.3.0        |
| date                                      | 2.0.0        |
| stringio                                  | 0.0.2        |
| zlib                                      | 1.0.0        |
| ipaddr                                    | 1.2.2        |
| openssl                                   | 2.1.2        |
| ostruct                                   | 0.1.0        |
| strscan                                   | 1.0.0        |
| fileutils                                 | 1.1.0        |
| etc                                       | 1.0.1        |
| io-console                                | 0.4.7        |
| psych                                     | 3.1.0        |
| mutex_m                                   | 0.1.0        |
| fastlane-plugin-firebase_app_distribution | 0.2.7        |
| fastlane-plugin-xcconfig                  | 2.0.0        |
| trainer                                   | 0.9.1        |
| xctest_list                               | 1.2.1        |
| colorize                                  | 0.8.1        |
| fastlane-plugin-test_center               | 3.15.3       |
</details>

*generated on:* **2021-05-04**
</details>

**Comment by crazymanish** [comment]
Hi @tasvir-rohila-carsales 

This issue nothing to do with this Fastlane repo code and the Fastlane team can't really solve or do anything about it! 

I will recommend you to report this issue in[ fastlane-plugin-test_center](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center) repository.
When I saw your logs, Fastlane is crashing in the below line which is **own and maintain by the fastlane-plugin-test_center team**
https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/f1e8dc62f174dfc6e4ffa15112836a15dddc47b9/lib/fastlane/plugin/test_center/actions/testplans_from_scheme.rb#L33

**Exception:**
NoMethodError: [!] undefined method length' for nil:NilClass Users/machine.user/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/**fastlane-plugin-test_center-3.15.3**/lib/fastlane/plugin/test_center/actions/**testplans_from_scheme.rb:33**:in schemes'

<img width="787" alt="Screenshot 2021-05-15 at 19 12 21" src="https://user-images.githubusercontent.com/5364500/118372360-8b8c5200-b5b1-11eb-8e60-c1dc5d6958a9.png">

**Comment by minuscorp** [comment]
Maybe this issue should be opened on the plug-in repository instead of here. What do you think?
