### ISSUE TITLE
Pilot: Fails because url is incorrect format.

### ISSUE THREAD

**Issue by CraigSiemens** [fastlane/fastlane#18648]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
`upload_to_testflight` fails after waiting for the build to finish processing with the error
```
An attribute value has invalid url. - The format of the url is invalid. - marketingUrl
An attribute value has invalid url. - The format of the url is invalid. - privacyPolicyUrl
```

Those two fields are using the exact same files that `deliver` uses, and `deliver` is able to complete without an issue.

The URLs have the format `https://www.example.com/path`. The files do have a trialing newline. Is it possible the `deliver` is handling that but `pilot` isn't?

##### Command executed
This is run inside a custom lane, but it also has the same issue when run individually.
```
    upload_to_testflight(
      beta_app_review_info: {
        contact_email: File.read("metadata/review_information/email_address.txt"),
        contact_first_name: File.read("metadata/review_information/first_name.txt"),
        contact_last_name: File.read("metadata/review_information/last_name.txt"),
        contact_phone: File.read("metadata/review_information/phone_number.txt"),
        demo_account_required: true,
        demo_account_name: File.read("metadata/review_information/demo_user.txt"),
        demo_account_password: File.read("metadata/review_information/demo_password.txt"),
        notes: File.read("metadata/review_information/notes.txt")
      },
      localized_app_info: {
        "default": {
          feedback_email: "[REDACTED]",
          marketing_url: File.read("metadata/en-CA/marketing_url.txt"),
          privacy_policy_url: File.read("metadata/en-CA/privacy_url.txt"),
          description: File.read("metadata/en-CA/description.txt"),
        }
      },
      skip_submission: true,
    )
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
[16:01:27]: ----------------------------------
[16:01:27]: --- Step: upload_to_testflight ---
[16:01:27]: ----------------------------------
[16:01:27]: Creating authorization token for App Store Connect API
[16:01:33]: Ready to upload new build to TestFlight (App: 1495268044)...
[16:01:34]: Going to upload updated app to App Store Connect
[16:01:34]: This might take a few minutes. Please don't interrupt the script.
[16:03:04]: iTunes Transporter successfully finished its job
[16:03:04]: --------------------------------------------------------------------
[16:03:04]: Successfully uploaded package to App Store Connect. It might take a few minutes until it's visible online.
[16:03:04]: --------------------------------------------------------------------
[16:03:04]: Successfully uploaded the new binary to App Store Connect
[16:03:04]: If you want to skip waiting for the processing to be finished, use the `skip_waiting_for_build_processing` option
[16:03:04]: Note that if `skip_waiting_for_build_processing` is used but a `changelog` is supplied, this process will wait for the build to appear on AppStoreConnect, update the changelog and then skip the remaining of the processing steps.
[16:03:04]: Waiting for processing on... app_id: 1495268044, app_version: 2021.7, build_version: 7864, platform: IOS
[16:03:05]: Read more information on why this build isn't showing up yet - https://github.com/fastlane/fastlane/issues/14997
[16:03:05]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[16:03:36]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[16:04:06]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[16:04:37]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[16:05:07]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[16:05:37]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[16:06:08]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[16:06:38]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[16:07:08]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[16:07:39]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[16:08:09]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[16:08:47]: Waiting for App Store Connect to finish processing the new build (2021.7 - 7864) for IOS
[16:09:18]: Waiting for App Store Connect to finish processing the new build (2021.7 - 7864) for IOS
[16:09:49]: Waiting for App Store Connect to finish processing the new build (2021.7 - 7864) for IOS
[16:10:20]: Waiting for App Store Connect to finish processing the new build (2021.7 - 7864) for IOS
[16:10:51]: Waiting for App Store Connect to finish processing the new build (2021.7 - 7864) for IOS
[16:11:22]: Waiting for App Store Connect to finish processing the new build (2021.7 - 7864) for IOS
[16:11:57]: Waiting for App Store Connect to finish processing the new build (2021.7 - 7864) for IOS
[16:12:27]: Waiting for App Store Connect to finish processing the new build (2021.7 - 7864) for IOS
[16:12:58]: Waiting for App Store Connect to finish processing the new build (2021.7 - 7864) for IOS
[16:13:29]: Waiting for App Store Connect to finish processing the new build (2021.7 - 7864) for IOS
[16:14:00]: Waiting for App Store Connect to finish processing the new build (2021.7 - 7864) for IOS
[16:14:31]: Waiting for App Store Connect to finish processing the new build (2021.7 - 7864) for IOS
[16:15:02]: Waiting for App Store Connect to finish processing the new build (2021.7 - 7864) for IOS
[16:15:33]: Waiting for App Store Connect to finish processing the new build (2021.7 - 7864) for IOS
[16:16:04]: Waiting for App Store Connect to finish processing the new build (2021.7 - 7864) for IOS
[16:16:35]: Waiting for App Store Connect to finish processing the new build (2021.7 - 7864) for IOS
[16:17:06]: Waiting for App Store Connect to finish processing the new build (2021.7 - 7864) for IOS
[16:17:37]: Waiting for App Store Connect to finish processing the new build (2021.7 - 7864) for IOS
[16:18:08]: Successfully finished processing the build 2021.7 - 7864 for IOS
+--------------------+----------------------------------------------------------------------------------------------+
|                                                   Lane Context                                                    |
+--------------------+----------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM   | ios                                                                                          |
| PLATFORM_NAME      | ios                                                                                          |
| LANE_NAME          | ios production_testflight                                                                    |
| SIGH_PROFILE_PATH  | /Users/vagrant/git/AppStore_com.neofinancial.neo.mobileprovision                             |
| SIGH_PROFILE_PATHS | ["/Users/vagrant/git/AppStore_com.neofinancial.neo.mobileprovision"]                         |
| SIGH_UDID          | 2698b2d4-8b3b-4c80-8dba-8c5725111081                                                         |
| SIGH_UUID          | 2698b2d4-8b3b-4c80-8dba-8c5725111081                                                         |
| SIGH_NAME          | com.neofinancial.neo AppStore                                                                |
| SIGH_PROFILE_TYPE  | app-store                                                                                    |
| IPA_OUTPUT_PATH    | /Users/vagrant/git/Neo.ipa                                                                   |
| XCODEBUILD_ARCHIVE | /Users/vagrant/Library/Developer/Xcode/Archives/2021-05-05/Neo 2021-05-05 15.55.47.xcarchive |
| DSYM_OUTPUT_PATH   | /Users/vagrant/git/Neo.app.dSYM.zip                                                          |
+--------------------+----------------------------------------------------------------------------------------------+
[16:18:09]: An attribute value has invalid url. - The format of the url is invalid. - marketingUrl
An attribute value has invalid url. - The format of the url is invalid. - privacyPolicyUrl
+------+---------------------------+-------------+
|                fastlane summary                |
+------+---------------------------+-------------+
| Step | Action                    | Time (in s) |
+------+---------------------------+-------------+
| 1    | default_platform          | 0           |
| 2    | app_store_connect_api_key | 0           |
| 3    | get_provisioning_profile  | 3           |
| 4    | build_ios_app             | 353         |
| 💥   | upload_to_testflight      | 1001        |
+------+---------------------------+-------------+
[16:18:09]: fastlane finished with errors
Looking for related GitHub issues on fastlane/fastlane...
➡️  Having deliver/upload_to_app_store issues? Install 2.150.0.rc5
    https://github.com/fastlane/fastlane/issues/16639 [closed] 116 💬
    04 Sep 2020
🔗  You can ⌘ + double-click on links to open them directly in your browser.
#######################################################################
# fastlane 2.182.0 is available. You are on 2.181.0.
# You should use the latest version.
# Please update using `bundle update fastlane`.
#######################################################################
bundler: failed to load command: fastlane (/Users/vagrant/git/bundle-gems/ruby/2.6.0/bin/fastlane)
Spaceship::UnexpectedResponse: [!] An attribute value has invalid url. - The format of the url is invalid. - marketingUrl
An attribute value has invalid url. - The format of the url is invalid. - privacyPolicyUrl
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/gems/fastlane-2.181.0/spaceship/lib/spaceship/connect_api/api_client.rb:199:in `handle_response'
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/gems/fastlane-2.181.0/spaceship/lib/spaceship/connect_api/api_client.rb:135:in `patch'
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/gems/fastlane-2.181.0/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:67:in `patch_beta_app_localizations'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/2.6.0/forwardable.rb:230:in `patch_beta_app_localizations'
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/gems/fastlane-2.181.0/pilot/lib/pilot/build_manager.rb:504:in `update_localized_app_review_for_lang'
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/gems/fastlane-2.181.0/pilot/lib/pilot/build_manager.rb:491:in `block in update_localized_app_review'
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/gems/fastlane-2.181.0/pilot/lib/pilot/build_manager.rb:487:in `each'
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/gems/fastlane-2.181.0/pilot/lib/pilot/build_manager.rb:487:in `update_localized_app_review'
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/gems/fastlane-2.181.0/pilot/lib/pilot/build_manager.rb:233:in `update_beta_app_meta'
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/gems/fastlane-2.181.0/pilot/lib/pilot/build_manager.rb:159:in `distribute'
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/gems/fastlane-2.181.0/pilot/lib/pilot/build_manager.rb:62:in `upload'
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:31:in `run'
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:68:in `block (2 levels) in parsing_binding'
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/gems/fastlane-2.181.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/gems/fastlane-2.181.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/gems/fastlane-2.181.0/bin/fastlane:23:in `<top (required)>'
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/bin/fastlane:23:in `load'
  /Users/vagrant/git/bundle-gems/ruby/2.6.0/bin/fastlane:23:in `<top (required)>'
 </pre>
</details>

### Environment

<details>
  <pre> [10:29:57]: [33mGenerating fastlane environment output, this might take a few seconds...[0m
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 11.2.3                                           |
| Ruby                        | 2.6.5                                            |
| Bundler?                    | true                                             |
| Git                         | git version 2.30.2                               |
| Installation Source         | ~/.rvm/gems/ruby-2.6.5/bin/fastlane              |
| Host                        | macOS 11.2.3 (20D91)                             |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.5/lib                     |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-12-4.app/Contents/Developer/ |
| Xcode Version               | 12.4                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require_relative 'Configurations'

default_platform(:ios)

platform :ios do
  before_all do |lane|
    ENV["FASTLANE"] = "1"
  end

  after_all do |lane|
    if !ENV["CI"]
      clean_build_artifacts
    end
  end

  desc "Runs the tests for the app."
  lane :test do
    run_tests
  end

  lane :staging do
    app_store_connect_api_key(
      in_house: false
    )

    get_provisioning_profile(
      adhoc: true,
      skip_certificate_verification: true,
      force: true,
      template_name: "ApplePay In-App Provisioning Distribution"
    )

    build_ios_app(
      export_options: {
        compileBitcode: false
      }
    )

    sentry_upload_dsym
  end

  lane :production_testflight do
    app_store_connect_api_key(
      in_house: false
    )

    get_provisioning_profile(
      skip_certificate_verification: true
    )

    build_ios_app

    upload_to_testflight(
      beta_app_review_info: {
        contact_email: File.read("metadata/review_information/email_address.txt"),
        contact_first_name: File.read("metadata/review_information/first_name.txt"),
        contact_last_name: File.read("metadata/review_information/last_name.txt"),
        contact_phone: File.read("metadata/review_information/phone_number.txt"),
        demo_account_required: true,
        demo_account_name: File.read("metadata/review_information/demo_user.txt"),
        demo_account_password: File.read("metadata/review_information/demo_password.txt"),
        notes: File.read("metadata/review_information/notes.txt")
      },
      localized_app_info: {
        "default": {
          feedback_email: "support@neofinancial.com",
          marketing_url: File.read("metadata/en-CA/marketing_url.txt"),
          privacy_policy_url: File.read("metadata/en-CA/privacy_url.txt"),
          description: File.read("metadata/en-CA/description.txt"),
        }
      },
      skip_submission: true,
      skip_waiting_for_build_processing: true,
    )
  end

  lane :upload_metadata do
    app_store_connect_api_key(
      in_house: false
    )

    deliver(
      skip_binary_upload: true,
      overwrite_screenshots: true,
      precheck_include_in_app_purchases: false
    )
  end

  desc "Uploads the app privacy details to the app store"
  desc "Requirements:"
  desc " - must be run manually (for now)"
  desc " - an admin or higher member of the development team"
  desc " - the ability to use two factor authentication for that user"
  desc "   - this is because application specific passwords and the App Store Connect API key dont have access to the app privacy details"
  lane :upload_app_privacy_details do
    # Info about uploading privacy details and the expected json format.
    # https://github.com/fastlane/fastlane/pull/17592
    upload_app_privacy_details_to_app_store(
      json_path: "fastlane/metadata/app_privacy_details.json"
    )
  end

  desc "Adds a device to the developer account and triggers a new bitrise build"
  desc "Requires the BITRISE_APP_SLUG and BITRISE_ACCESS_TOKEN environment variables to be set (optionally in a .env file)"
  desc "Options:"
  desc "- `name`\n  - The name of the persion the device belongs to"
  desc "- `device_type`\n  - The type of the device. ex. iPhone 12 Pro, iPad Air (4th Generation)"
  desc "- `udid`\n  - The UDID for the device"
  desc "- `skip_build:true`\n  - Skips triggering a bitrise build"
  lane :add_device_to_staging do |options|
    skip_build = options[:skip_build] || false

    bitrise_username = ENV["BITRISE_USERNAME"] unless ENV["BITRISE_USERNAME"].nil? || ENV["BITRISE_USERNAME"].empty?
    UI.user_error! "Missing environment variable: BITRISE_USERNAME" unless bitrise_username || skip_build

    user_name = options[:name] || UI.input("Who does the device belong to?")
    device_type = options[:device_type] || UI.input("What kind of device is it? ex. iPhone 12 Pro, iPad Air (4th Generation)")
    udid = options[:udid] || UI.input("What is the devices UDID?")

    name = "#{user_name} - #{device_type}"

    UI.confirm("Device Information\nName: #{name}\nUDID: #{udid}\n\nIs this infomrmation correct?") || next

    register_device(
      name: name,
      udid: udid
    )

    !skip_build && UI.confirm("Do you want to trigger a bitrise build?") || next

    trigger_bitrise_workflow(
      workflow: "staging",
      branch: "develop",
      build_message: "Fastlane - Add Device to Staging - #{name}",
      triggered_by: "@#{bitrise_username}"
    )
  end

  desc "Renew provisioning profiles"
  desc "Options:"
  desc "- `all:true`\n  - Try to renew all provisioning profiles"
  desc "- `local:true`\n  - Renew the local provisioning profiles"
  desc "- `staging_debug:true`\n  - Renew the staging debug provisioning profiles"
  desc "- `staging_release:true`\n  - Renew the staging release provisioning profiles"
  desc "- `production_debug:true`\n  - Renew the production debug provisioning profiles"
  desc "- `production_release:true`\n  - Renew the production release provisioning profiles"
  desc "- `force:true`\n  - Forces the provisioning profiles to be renewed even if it hasnt expired"
  desc ""
  lane :renew_provisioning_profiles do |options|
    renew = ->(config) { 
      get_provisioning_profile(
        app_identifier: config.identifier,
        adhoc: config.is_adhoc,
        development: config.is_development,
        force: options[:force] || false
      )
    }
    
    if options[:all] || options[:local]
      renew.call(Configurations.local)
    end

    if options[:all] || options[:staging_debug]
      renew.call(Configurations.staging_debug)
    end

    if options[:all] || options[:staging_release]
      renew.call(Configurations.staging_release)
    end

    if options[:all] || options[:production_debug]
      renew.call(Configurations.production_debug)
    end

    if options[:all] || options[:production_release]
      renew.call(Configurations.production_release)
    end
  end

  desc "Renew push notification certificates"
  desc "Options:"
  desc "- `all:true`\n  - Try to renew all push notification certificates"
  desc "- `local:true`\n  - Renew the local push notification certificate"
  desc "- `staging:true`\n  - Renew the staging push notification certificate"
  desc "- `production:true`\n  - Renew the production push notification certificate"
  desc "- `force:true`\n  - Forces the certificate to be renewed even if it doesnt expire in the next 30 days"
  desc ""
  lane :renew_push_certs do |options|
    if options[:all] || options[:local]
      get_push_certificate(
        development: Configurations.local.is_development,
        app_identifier: Configurations.local.identifier,
        force: options[:force] || false,
        output_path: './certificates'
      )
    end

    if options[:all] || options[:staging]
      get_push_certificate(
        development: Configurations.staging_release.is_development,
        app_identifier: Configurations.staging_release.identifier,
        force: options[:force] || false,
        output_path: './certificates'
      )
    end

    if options[:all] || options[:production]
      get_push_certificate(
        development: Configurations.production_release.is_development,
        app_identifier: Configurations.production_release.identifier,
        force: options[:force] || false,
        output_path: './certificates'
      )
    end
  end

  desc "Download the dsyms from iTunes Connect and upload to Sentry"
  desc "Options:"
  desc "- `version`\n  - The version to download the dsyms from. Uses the version from the xcodeproj is not set."
  desc "- `build`\n  - The build to download the dsyms from. If manunlly set, version won't be used."
  lane :dsym do |options|
    version = options[:version] || get_version_number(
      xcodeproj: "Neo.xcodeproj",
      target: "Neo"
    ) unless options[:build]

    build = options[:build] || latest_testflight_build_number(
      version: version
    )

    UI.confirm("Do you want to download the dsyms for #{version}(#{build})?") || next

    download_dsyms(
      version: version,
      build_number: build.to_s
    )

    sentry_upload_dsym
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

require './Configurations'

itc_team_id "120120312"
team_id "8AKPS28AYR"

app_identifier Configurations.current.identifier

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.178.0 | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                             | Version | Update-Status |
| ---------------------------------- | ------- | ------------- |
| fastlane-plugin-sentry             | 1.8.1   | ✅ Up-To-Date  |
| fastlane-plugin-bitrise_automation | 0.4.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                | Version      |
| ---------------------------------- | ------------ |
| did_you_mean                       | 1.3.0        |
| executable-hooks                   | 1.6.0        |
| bundler-unload                     | 1.0.2        |
| rubygems-bundler                   | 1.4.5        |
| bundler                            | 2.1.4        |
| rake                               | 13.0.3       |
| CFPropertyList                     | 3.0.3        |
| public_suffix                      | 4.0.6        |
| addressable                        | 2.7.0        |
| artifactory                        | 3.0.15       |
| atomos                             | 0.1.3        |
| aws-eventstream                    | 1.1.1        |
| aws-partitions                     | 1.432.0      |
| aws-sigv4                          | 1.2.3        |
| jmespath                           | 1.4.0        |
| aws-sdk-core                       | 3.113.0      |
| aws-sdk-kms                        | 1.43.0       |
| aws-sdk-s3                         | 1.91.0       |
| babosa                             | 1.0.4        |
| claide                             | 1.0.3        |
| colored                            | 1.2          |
| colored2                           | 3.1.2        |
| highline                           | 1.7.10       |
| commander-fastlane                 | 4.4.6        |
| declarative                        | 0.0.20       |
| declarative-option                 | 0.1.0        |
| digest-crc                         | 0.6.3        |
| unf_ext                            | 0.0.7.7      |
| unf                                | 0.1.4        |
| domain_name                        | 0.5.20190701 |
| dotenv                             | 2.7.6        |
| emoji_regex                        | 3.2.2        |
| excon                              | 0.79.0       |
| faraday-net_http                   | 1.0.1        |
| multipart-post                     | 2.0.0        |
| ruby2_keywords                     | 0.0.4        |
| faraday                            | 1.3.0        |
| http-cookie                        | 1.0.3        |
| faraday-cookie_jar                 | 0.0.7        |
| faraday_middleware                 | 1.0.0        |
| fastimage                          | 2.2.3        |
| gh_inspector                       | 1.1.3        |
| jwt                                | 2.2.2        |
| memoist                            | 0.16.2       |
| multi_json                         | 1.15.0       |
| os                                 | 1.1.1        |
| signet                             | 0.15.0       |
| googleauth                         | 0.16.0       |
| httpclient                         | 2.8.3        |
| mini_mime                          | 1.0.2        |
| uber                               | 0.1.0        |
| representable                      | 3.0.4        |
| retriable                          | 3.1.2        |
| google-api-client                  | 0.38.0       |
| rexml                              | 3.2.4        |
| webrick                            | 1.7.0        |
| google-apis-core                   | 0.3.0        |
| google-apis-iamcredentials_v1      | 0.2.0        |
| google-apis-storage_v1             | 0.3.0        |
| google-cloud-env                   | 1.5.0        |
| google-cloud-errors                | 1.1.0        |
| google-cloud-core                  | 1.6.0        |
| google-cloud-storage               | 1.31.0       |
| json                               | 2.5.1        |
| mini_magick                        | 4.11.0       |
| naturally                          | 2.2.1        |
| plist                              | 3.6.0        |
| rubyzip                            | 2.3.0        |
| security                           | 0.1.3        |
| simctl                             | 1.6.8        |
| slack-notifier                     | 2.3.2        |
| terminal-notifier                  | 2.0.0        |
| unicode-display_width              | 1.7.0        |
| terminal-table                     | 1.8.0        |
| tty-screen                         | 0.8.1        |
| tty-cursor                         | 0.7.1        |
| tty-spinner                        | 0.9.3        |
| word_wrap                          | 1.0.0        |
| nanaimo                            | 0.3.0        |
| xcodeproj                          | 1.19.0       |
| rouge                              | 2.0.7        |
| xcpretty                           | 0.3.0        |
| xcpretty-travis-formatter          | 1.0.1        |
| fastlane-plugin-bitrise_automation | 0.4.1        |
| fastlane-plugin-sentry             | 1.8.1        |
</details>

*generated on:* **2021-05-05**
</details>
[10:29:58]: [33mTake notice that this output may contain sensitive information, or simply information that you don't want to make public.[0m
[10:29:58]: [32mOpen https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅[0m

#######################################################################
# fastlane 2.182.0 is available. You are on 2.178.0.
# You should use the latest version.
# Please update using `bundle update fastlane`.
#######################################################################

[32m2.182.0 Improvements[0m
* [snapshot] enable greater customization of the iOS status bar in snapshot screenshots (#18560) via Dave Wood
* [Fastlane.Swift] Swift's `ConfigItem` for conflicting values into Ruby's end. (#18544) via Jorge Revuelta
* [Fastlane.Swift] sanitize Swift document comments (#18635) via Jorge Revuelta
* [Ruby 3.0] wwitch back to the original commander gem and update dependencies (#18599) via Satoshi Namai
* [action] ensure backup_xcarchive preserves symbolic links (#18627) via Matej Bukovinski
* [action][git_submodule_update] documentation improvements (#18598) via Manish Rathi
* [Ruby 3.0] replace slack-notifier gem with internal library (#18537) via Satoshi Namai
* [fastlane_core] `xcode_at_least` method improvements (#18600) via Manish Rathi
* [pilot] clean-up - removed empty `tester_util` file (#18601) via Manish Rathi
* [action][upload_symbols_to_crashlytics]  add check for app_id before searching for gsp and api_token (#18607) via Cristian Lupu
* [spaceship] add `fetch_all_certificates` method (#18620) via Damian Rzeszot
* [Ruby 3.0] bump rubocop version (#18564) via Satoshi Namai
* [action] import_from_git - Add caching support for branch (#18568) via Hiroki Nagasawa

[32m2.181.0 Improvements[0m
* [scan] keep initial xcresult (#18555) via Corey Werner
* [spaceauth] add `--copy_to_clipboard` option to `spaceauth` (#18538) via Roger Oba
* [Ruby 3.0] improve specs for Slack action  (#18512) via Satoshi Namai
* [spaceship] fix case sensitive email issue for Spaceship::Members.find (#18573) via Max Ott
* [supply] upload native symbols for crash symbolication (#18526) via Marcelo Oliveira
* [fastlane][lanemanager] fastlane command suggestion improvement when running using bundler (#18515) via Manish Rathi
* [gym] fix in the gym/runner. When moving mac 'app' silently fails if file already exist in that location. (#18529) via Krzysztof
* [snapshot] added iPhone 12 models to snapshot reports generator (#18535) via Davide
* [fastlane_core][pilot][deliver] fix when polling for build processing to poll for X.Y and X.Y.0 (#18547) via Josh Holtz
* [action][ensure_env_vars] efficiency improvement (#18522) via Manish Rathi
* [fastlane][action] fix git_branch when not in a git repo (#18525) via Josh Holtz

[32m2.180.1 Improvements[0m
* [fastlane] fix fastlane_require to work with RubyGems 3.2.0 and up (#18520) via Josh Holtz

[32mTo see all new releases, open https://github.com/fastlane/fastlane/releases[0m

[32mPlease update using `bundle update fastlane`[0m
] </pre>
</details>

**Comment by max-ott** [comment]
Can you confirm that if you use a string and not a file that it's working?

**Comment by CraigSiemens** [comment]
Yeah, a string without a newline works. I ended up fixing it by calling `.strip` on the file contents. It appears like that's what deliver does by default.

https://github.com/fastlane/fastlane/blob/e874a47c6e2e0e61590a03d3b71e75e5a505d1ce/deliver/lib/deliver/upload_metadata.rb#L144-L146

**Comment by CraigSiemens** [comment]
It'd be nice if this could strip newlines automatically.
