### ISSUE TITLE
Running saml2aws login shell command using fastlane hangs 

### ISSUE THREAD

**Issue by Mohamed3amer** [fastlane/fastlane#18645]
### New Issue Checklist

- [ x] Updated fastlane to the latest version
- [ x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When we run `saml2aws login --skip-prompt -a xxxx` command from terminal it works as following:
```
Using xxx Account xxx to access xxx https://xxxx
Authenticating as xyz@xxx.com ...
? Enter verification code 
xxxx
Selected role: xxxx
Requesting AWS credentials using SAML assertion
Logged in as: xxxx
```

But when we are trying to run it using fastlane private lane but it hangs (maybe in reading the saved password or in showing `Enter verification code` step).
As following:
```
▸ Using xxx Account xxx to access xxx https://xxxx
▸ Authenticating as xyz@xxx.com ...
```

##### Command executed
```
private_lane :aws_login do |options|
    sh("saml2aws login --skip-prompt --force -a xxx")
  end
```

##### Fastlane --version
fastlane 2.181.0

**Comment by max-ott** [comment]
Not sure if this is related to fastlne or the `smal2aws` script. I don't think shell commands are supposed to be interactive when called that way, so I think this is the expected behaviour.

**Comment by Mohamed3amer** [comment]
@max-ott thank you Max for answering. So you mean through Fastlane we shouldn't invoke any interactive shell commands, right?

**Comment by AngelHoglet** [comment]
> There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.
> 
> Please make sure to update to the latest `fastlane` version and check if that solves the issue. Let us know if that works for you by adding a comment 👍
> 
> Friendly reminder: contributions are always welcome! Check out [CONTRIBUTING.md](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md) for more information on how to help with `fastlane` and feel free to tackle this issue yourself 💪
> 
> This issue will be auto-closed if there is no reply within 1 month.

I don't think shell commands are supposed to be interactive when called that way, so I think this is the expected behavior.
