### ISSUE TITLE
pilot, spaceship: The URL path is not valid - The resource 'buildDeliveries' does not exist

### ISSUE THREAD

**Issue by ivanbartsov** [fastlane/fastlane#18650]
Fastlane version 2.182.0

When running the following command:
```bundle exec fastlane pilot builds --api_key_path ../appstoreconnect.json -a com.my.app.id```

I get an exception:
```
bundler: failed to load command: fastlane (/Users/user/.rbenv/versions/2.7.2/bin/fastlane)
Spaceship::UnexpectedResponse: [!] The URL path is not valid - The resource 'buildDeliveries' does not exist
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.182.0/spaceship/lib/spaceship/connect_api/api_client.rb:199:in `handle_response'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.182.0/spaceship/lib/spaceship/connect_api/api_client.rb:113:in `get'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.182.0/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:399:in `get_build_deliveries'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/2.7.0/forwardable.rb:235:in `get_build_deliveries'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.182.0/spaceship/lib/spaceship/connect_api/models/app.rb:366:in `get_build_deliveries'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.182.0/pilot/lib/pilot/build_manager.rb:189:in `list'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.182.0/pilot/lib/pilot/commands_generator.rb:91:in `block (2 levels) in run'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.182.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.182.0/pilot/lib/pilot/commands_generator.rb:167:in `run'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.182.0/pilot/lib/pilot/commands_generator.rb:19:in `start'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.182.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.182.0/bin/fastlane:23:in `<top (required)>'
```

Seems related to #17821

`fastlane env`:

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.3.1                                      |
| Ruby                        | 2.7.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.30.1 (Apple Git-130)          |
| Installation Source         | ~/.rbenv/versions/2.7.2/bin/fastlane        |
| Host                        | macOS 11.3.1 (20E241)                       |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.2/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.5                                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```
CENSORED OUT, IRRELEVANT
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.182.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.4.0        |
| bundler                       | 2.1.4        |
| uri                           | 0.10.0       |
| rake                          | 13.0.3       |
| CFPropertyList                | 3.0.3        |
| concurrent-ruby               | 1.1.8        |
| i18n                          | 1.8.10       |
| minitest                      | 5.14.4       |
| thread_safe                   | 0.3.6        |
| tzinfo                        | 1.2.9        |
| activesupport                 | 5.2.5        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| httpclient                    | 2.8.3        |
| json                          | 2.5.1        |
| algoliasearch                 | 1.27.5       |
| artifactory                   | 3.0.15       |
| atomos                        | 0.1.3        |
| aws-eventstream               | 1.1.1        |
| aws-partitions                | 1.451.0      |
| aws-sigv4                     | 1.2.3        |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.114.0      |
| aws-sdk-kms                   | 1.43.0       |
| aws-sdk-s3                    | 1.94.1       |
| babosa                        | 1.0.4        |
| claide                        | 1.0.3        |
| fuzzy_match                   | 2.0.4        |
| nap                           | 1.1.0        |
| netrc                         | 0.11.0       |
| ffi                           | 1.15.0       |
| ethon                         | 0.12.0       |
| typhoeus                      | 1.4.0        |
| cocoapods-core                | 1.10.1       |
| cocoapods-deintegrate         | 1.0.4        |
| cocoapods-downloader          | 1.4.0        |
| cocoapods-plugins             | 1.0.0        |
| cocoapods-search              | 1.0.0        |
| cocoapods-trunk               | 1.5.0        |
| cocoapods-try                 | 1.2.0        |
| colored2                      | 3.1.2        |
| escape                        | 0.0.4        |
| fourflusher                   | 2.3.1        |
| gh_inspector                  | 1.1.3        |
| molinillo                     | 0.6.6        |
| ruby-macho                    | 1.4.0        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| cocoapods                     | 1.10.1       |
| colored                       | 1.2          |
| highline                      | 2.0.3        |
| commander                     | 4.6.0        |
| declarative                   | 0.0.20       |
| digest-crc                    | 0.6.3        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| dotenv                        | 2.7.6        |
| emoji_regex                   | 3.2.2        |
| excon                         | 0.81.0       |
| faraday-excon                 | 1.1.0        |
| faraday-net_http              | 1.0.1        |
| faraday-net_http_persistent   | 1.1.0        |
| multipart-post                | 2.0.0        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.4.1        |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.3        |
| jwt                           | 2.2.3        |
| memoist                       | 0.16.2       |
| multi_json                    | 1.15.0       |
| os                            | 1.1.1        |
| signet                        | 0.15.0       |
| googleauth                    | 0.16.2       |
| mini_mime                     | 1.1.0        |
| trailblazer-option            | 0.1.1        |
| uber                          | 0.1.0        |
| representable                 | 3.1.1        |
| retriable                     | 3.1.2        |
| google-api-client             | 0.38.0       |
| rexml                         | 3.2.5        |
| webrick                       | 1.7.0        |
| google-apis-core              | 0.3.0        |
| google-apis-iamcredentials_v1 | 0.3.0        |
| google-apis-storage_v1        | 0.3.0        |
| google-cloud-env              | 1.5.0        |
| google-cloud-errors           | 1.1.0        |
| google-cloud-core             | 1.6.0        |
| google-cloud-storage          | 1.31.0       |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| plist                         | 3.6.0        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| simctl                        | 1.6.8        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| word_wrap                     | 1.0.0        |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| xcpretty-travis-formatter     | 1.0.1        |
</details>

*generated on:* **2021-05-06**
</details>

**Comment by max-ott** [comment]
@ivanbartsov Please use Apple ID + password for this. This resource is not available via the official App Store Connect API.
