### ISSUE TITLE
Explicit provisioning_profile_path not used?

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1866]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/2075915?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @vittoriom - Imported from <a href='https://github.com/fastlane/gym/issues/69'>fastlane/gym#69</a>
        </td>
      </tr>
    </table>

I'm using `gym` to build an enterprise version of our app. Just for this task it should use an explicitly provided provisioning profile and code signing identity, that override the ones defined in the project.

I'm building with the `--verbose` flag since after the first try I saw that it was using the wrong (as defined in the Xcode project) provisioning profile instead, but it looks like the generated build command doesn't include any parameter for passing the specified provisioning profile.

Is there any step I'm missing?

Generated build command:
```
set -o pipefail && xcodebuild 
-scheme '[REDACTED]' 
-project './[REDACTED].xcodeproj' 
-configuration 'Release' 
-destination 'generic/platform=iOS' 
-xcconfig 'config/Debug.xcconfig' 
-archivePath '/Users/vmonaco/Library/Developer/Xcode/Archives/2015-08-27/[REDACTED] 2015-08-27 12.48.13.xcarchive' 
archive | xcpretty
```

The command I used is:

```
gym 
--xcconfig "config/Debug.xcconfig" 
--codesigning_identity "iPhone Distribution: [REDACTED]" 
--provisioning_profile_path: "../CodeSigning/Enterprise.mobileprovision" 
--scheme "[REDACTED]" 
--configuration "Release"
--verbose
```

After `xcodebuild` finishes, I got the following command:

```
/usr/bin/xcrun 
/tmp/PackageApplication4Gym 
-v /Users/vmonaco/Library/Developer/Xcode/Archives/2015-08-27/[REDACTED]\ 2015-08-27\ 12.48.13.xcarchive/Products/Applications/[REDACTED].app 
-o '/Users/vmonaco/Library/Developer/Xcode/Archives/2015-08-27/[REDACTED].ipa' exportFormat ipa --sign 'iPhone Distribution: [REDACTED]'
```

But nowhere I can see the embedded provisioning being set.

**Comment by eholzwarth** [comment]
Running into this same issue - aren't we supposed to be able to use gym independently from match? We had a command line argument that was working and now every solution in the readme is listed as deprecated with a recommendation to use match. Match looks like a nice tool, but it's a big investment to convert our team over to using it. gym still accepts the provisioning_profile_path argument and happily reports "Installing provisioning profile..." only later to fail with "Code Sign error: No matching provisioning profile found: Your build settings specify a provisioning profile with the UUID ..." :\

**Comment by KrauseFx** [comment]
I just pushed https://github.com/fastlane/fastlane/pull/4890 to make it more clear that the option is not used. That's not something we decided, but that's how `xcodebuild` works. 
@eholzwarth Please submit a separate issue for your problem with more information about your setup, in particular a screenshot of your codesigning settings in Xcode
