### ISSUE TITLE
Specify Gymfile

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1867]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/3853006?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @Reedyuk - Imported from <a href='https://github.com/fastlane/gym/issues/68'>fastlane/gym#68</a>
        </td>
      </tr>
    </table>

At the moment, i want to have multiple gym files so that i have a different configuration for dev, ad-hoc and release.
Could you make it so that when i do gym i can specify a gymfile name e.g. 
"gym devGymFile"
"gym adHocGymFile"

Thanks

**Comment by rexeisen** [comment]
Still not implemented, fastlane-bot

**Comment by TKBurner** [comment]
@rexeisen Thanks! We'll keep this open 👍

**Comment by puttin** [comment]
It's not implemented.

**Comment by KrauseFx** [comment]
Currently this is not something we want to build. You can use a `Fastfile` with multiple lanes to support different build environments 👍
