### ISSUE TITLE
[!] Permission denied @ dir_s_mkdir - fastlane/metadata

### ISSUE THREAD

**Issue by pavelsust** [fastlane/fastlane#18707]
Here I am using mac big sur when I want to work with fastlane. I need to to work with sudo command. How I can give all access permission in my fastlane so that always it don't ask for permission.

**Comment by pavelsust** [comment]
| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.3.1                                                         |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.23.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.3.1 (20E241)                                          |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.4                                                           |

**Comment by jacobparish** [comment]
@pavelsust I am having the same issue - how did you resolve it?

**Comment by pavelsust** [comment]
Are you using mac?

**Comment by jacobparish** [comment]
@pavelsust I am using mac, but I was able to resolve my issue. I don't think it was actually the same issue as this one

**Comment by pavelsust** [comment]
> @pavelsust I am using mac, but I was able to resolve my issue. I don't think it was actually the same issue as this one

Please uninstall everything and install it globally.
