### ISSUE TITLE
Documentation Issue: developer_id requires Account Holder

### ISSUE THREAD

**Issue by mstobin** [fastlane/fastlane#18711]
This is related to the ongoing instruction on this thread, where error messages from Apple are not being displayed correctly:
https://github.com/fastlane/fastlane/issues/18431

In my case, the issue related to developer_id certificates, and the fact that Apple only allows the original Account Holder Apple ID of a development team being used to generate developer_id certificates.

Currently, the fastlane documentation is quite misleading on this, as it recommends the use of a shared devteam@ account for all certificates.

it would be helpful to update the documentation to reflect the fact this doesn’t work, and that in those cases the original Account Holder account must be used.

I would recommend adding a short note to each location that developer_id is listed as an option, as well as one longer paragraph explanation somewhere, as this requirement is pretty easy to miss (especially with the current bug where the error is not shown).

I wonder also if there is an established best practice for developer_id certificates yet, as it seems like a pretty big risk for the primary Account Holder Apple ID to be shared amongst the team the way fastlane match usually advocates.

In my case, I am currently taking the approach of using a different git branch and account details just for the developer_id certificates, while continuing with the shared dev team account for all others.

But I wonder if there is a better way to go about it.

**Comment by vanpham1986** [comment]
Thanks

**Comment by max-ott** [comment]
Could you please open a pull request for the documentation and directly change it? I don't think opening an issue for best practices is the right place to discuss it.

**Comment by Saravia83c** [comment]
- - [x] - en
