### ISSUE TITLE
Any fastlane command: `gsub': invalid byte sequence in UTF-8 (ArgumentError)

### ISSUE THREAD

**Issue by kkor** [fastlane/fastlane#18723]
### Issue Description

I have a project with a fastfile that works for another team member. Any fastlane command (e.g. `fastlane help`) throws an invalid byte sequence error:
```

✔] 🚀
Traceback (most recent call last):
	20: from /usr/local/Cellar/fastlane/2.183.2/libexec/bin/fastlane:23:in `<main>'
	19: from /usr/local/Cellar/fastlane/2.183.2/libexec/bin/fastlane:23:in `load'
	18: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/fastlane-2.183.2/bin/fastlane:23:in `<top (required)>'
	17: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/fastlane-2.183.2/fastlane/lib/fastlane/cli_tools_distributor.rb:51:in `take_off'
	16: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/fastlane-2.183.2/fastlane/lib/fastlane/cli_tools_distributor.rb:147:in `load_dot_env'
	15: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/fastlane-2.183.2/fastlane/lib/fastlane/helper/dotenv_helper.rb:10:in `load_dot_env'
	14: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/fastlane-2.183.2/fastlane/lib/fastlane/helper/dotenv_helper.rb:32:in `load_dot_envs_from'
	13: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv.rb:14:in `load'
	12: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv.rb:63:in `with'
	11: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv.rb:63:in `reduce'
	10: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv.rb:63:in `each'
	 9: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv.rb:64:in `block in with'
	 8: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv.rb:15:in `block in load'
	 7: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv.rb:83:in `ignoring_nonexistent_files'
	 6: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv.rb:16:in `block (2 levels) in load'
	 5: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv.rb:16:in `new'
	 4: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv/environment.rb:9:in `initialize'
	 3: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv/environment.rb:13:in `load'
	 2: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv/parser.rb:36:in `call'
	 1: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv/parser.rb:48:in `call'
/usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv/parser.rb:48:in `gsub': invalid byte sequence in UTF-8 (ArgumentError)
```

If I init a new fastfile in a new directory, `fastlane help` works, so it's something in my local project configuration that only fails for me but not my team member?

##### Command executed

`fastlane help` 

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>fastlane help --capture_output
[✔] 🚀
Traceback (most recent call last):
	20: from /usr/local/Cellar/fastlane/2.183.2/libexec/bin/fastlane:23:in `<main>'
	19: from /usr/local/Cellar/fastlane/2.183.2/libexec/bin/fastlane:23:in `load'
	18: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/fastlane-2.183.2/bin/fastlane:23:in `<top (required)>'
	17: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/fastlane-2.183.2/fastlane/lib/fastlane/cli_tools_distributor.rb:51:in `take_off'
	16: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/fastlane-2.183.2/fastlane/lib/fastlane/cli_tools_distributor.rb:147:in `load_dot_env'
	15: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/fastlane-2.183.2/fastlane/lib/fastlane/helper/dotenv_helper.rb:10:in `load_dot_env'
	14: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/fastlane-2.183.2/fastlane/lib/fastlane/helper/dotenv_helper.rb:32:in `load_dot_envs_from'
	13: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv.rb:14:in `load'
	12: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv.rb:63:in `with'
	11: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv.rb:63:in `reduce'
	10: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv.rb:63:in `each'
	 9: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv.rb:64:in `block in with'
	 8: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv.rb:15:in `block in load'
	 7: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv.rb:83:in `ignoring_nonexistent_files'
	 6: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv.rb:16:in `block (2 levels) in load'
	 5: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv.rb:16:in `new'
	 4: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv/environment.rb:9:in `initialize'
	 3: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv/environment.rb:13:in `load'
	 2: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv/parser.rb:36:in `call'
	 1: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv/parser.rb:48:in `call'
/usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv/parser.rb:48:in `gsub': invalid byte sequence in UTF-8 (ArgumentError) </pre>
</details>

### Environment

In my project:
 
<details>
  <pre> fastlane env
[✔] 🚀
Traceback (most recent call last):
	20: from /usr/local/Cellar/fastlane/2.183.2/libexec/bin/fastlane:23:in `<main>'
	19: from /usr/local/Cellar/fastlane/2.183.2/libexec/bin/fastlane:23:in `load'
	18: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/fastlane-2.183.2/bin/fastlane:23:in `<top (required)>'
	17: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/fastlane-2.183.2/fastlane/lib/fastlane/cli_tools_distributor.rb:51:in `take_off'
	16: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/fastlane-2.183.2/fastlane/lib/fastlane/cli_tools_distributor.rb:147:in `load_dot_env'
	15: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/fastlane-2.183.2/fastlane/lib/fastlane/helper/dotenv_helper.rb:10:in `load_dot_env'
	14: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/fastlane-2.183.2/fastlane/lib/fastlane/helper/dotenv_helper.rb:32:in `load_dot_envs_from'
	13: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv.rb:14:in `load'
	12: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv.rb:63:in `with'
	11: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv.rb:63:in `reduce'
	10: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv.rb:63:in `each'
	 9: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv.rb:64:in `block in with'
	 8: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv.rb:15:in `block in load'
	 7: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv.rb:83:in `ignoring_nonexistent_files'
	 6: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv.rb:16:in `block (2 levels) in load'
	 5: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv.rb:16:in `new'
	 4: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv/environment.rb:9:in `initialize'
	 3: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv/environment.rb:13:in `load'
	 2: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv/parser.rb:36:in `call'
	 1: from /usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv/parser.rb:48:in `call'
/usr/local/Cellar/fastlane/2.183.2/libexec/gems/dotenv-2.7.6/lib/dotenv/parser.rb:48:in `gsub': invalid byte sequence in UTF-8 (ArgumentError)</pre>
</details>

In the newly initialized project:
 
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 11.2.1                                                  |
| Ruby                        | 2.7.3                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.30.1 (Apple Git-130)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.183.2/libexec/bin/fastlane |
| Host                        | macOS 11.2.1 (20D74)                                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.7/2.7.3/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                             |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 12.5                                                    |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.183.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.4.0        |
| atomos                          | 0.1.3        |
| CFPropertyList                  | 3.0.3        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.19.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.7.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.81.0       |
| faraday-excon                   | 1.1.0        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.1.0        |
| ruby2_keywords                  | 0.0.4        |
| faraday                         | 1.4.1        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.3        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.0.0        |
| fastimage                       | 2.2.3        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.0        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.15       |
| simctl                          | 1.6.8        |
| jwt                             | 2.2.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.1        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.0        |
| multi_json                      | 1.15.0       |
| signet                          | 0.15.0       |
| memoist                         | 0.16.2       |
| os                              | 1.1.1        |
| googleauth                      | 0.16.2       |
| httpclient                      | 2.8.3        |
| google-apis-core                | 0.3.0        |
| google-apis-playcustomapp_v1    | 0.2.0        |
| emoji_regex                     | 3.2.2        |
| jmespath                        | 1.4.0        |
| aws-eventstream                 | 1.1.1        |
| aws-sigv4                       | 1.2.3        |
| aws-sdk-core                    | 3.114.0      |
| aws-sdk-kms                     | 1.43.0       |
| aws-sdk-s3                      | 1.94.1       |
| uri                             | 0.10.0       |
| json                            | 2.5.1        |
| rexml                           | 3.2.5        |
| webrick                         | 1.7.0        |
| google-apis-androidpublisher_v3 | 0.3.0        |
| rake                            | 13.0.3       |
| digest-crc                      | 0.6.3        |
| google-apis-storage_v1          | 0.3.0        |
| google-apis-iamcredentials_v1   | 0.3.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.31.1       |
| aws-partitions                  | 1.459.0      |
| forwardable                     | 1.3.1        |
| logger                          | 1.4.2        |
| cgi                             | 0.1.0        |
| date                            | 3.0.0        |
| timeout                         | 0.1.0        |
| stringio                        | 0.1.0        |
| zlib                            | 1.1.0        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| ostruct                         | 0.2.0        |
| strscan                         | 1.0.3        |
| io-console                      | 0.5.6        |
| delegate                        | 0.1.0        |
| fileutils                       | 1.4.1        |
| singleton                       | 0.1.0        |
| open3                           | 0.1.0        |
| yaml                            | 0.1.0        |
| psych                           | 3.1.0        |
| mutex_m                         | 0.1.0        |
</details>

*generated on:* **2021-05-20**
</details>

**Comment by minuscorp** [comment]
It seems that your dotenv file has some invalid UTF8 sequence, make sure the file has the correct format and try again.

**Comment by mistenkt** [comment]
I was getting this error when running `fastlane match appstore` as i kept misstyping my email and having to backspace to fix it every time. when i finally managed to type it correctly without backspacing the issue went away

**Comment by Brumor** [comment]
I'm also getting this error in a github action, works locally
