### ISSUE TITLE
Snapshot is not saving screenshots

### ISSUE THREAD

**Issue by alexnot95** [fastlane/fastlane#18722]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Snapshot is not saving screenshots. I've updated snapshot to 1.25 version and fastlane version is 2.183.1
I'm running my localization test suite, tests passed successfuly but folders with screenshots are empty :( 
Running on xcode 12.5 + ios 14.5 simulator
![Screenshot 2021-05-20 at 14 39 23](https://user-images.githubusercontent.com/37154209/118972395-2f427d00-b979-11eb-9e2d-9c9c95fdbc20.png)

My lane:
```
desc 'Run localization UI tests'
lane :native_localization_ui_test do |options|
    
  fastlane_require 'fastlane-plugin-test_center'

  clean_up_and_install_dependencies
  scheme = ENV["UI_TESTS_SCHEME"] || "Acceptance"
  testplan = ENV["UI_TEST_PLAN"]
  workspace = "#{ENV["MAIN_TARGET"]}.xcworkspace"
  derived_data_path = "~/Library/Developer/Xcode/DerivedData"
  cloned_source_packages_path = "~/Library/Caches/SPMCloneCaches"
  devices = ENV["UI_TESTS_DEVICE_TYPE"]
  output_dir = "./fastlane/test_output"
  languages = ENV["UI_TESTS_LANGUAGE"]

  scan(
    workspace: workspace,
    devices: devices,
    scheme: scheme,
    testplan: testplan,
    skip_slack: true,
    derived_data_path: derived_data_path,
    cloned_source_packages_path: cloned_source_packages_path,
    build_for_testing: true
  )

  snapshot(
    workspace: workspace,
    devices: devices,
    scheme: scheme,
    testplan: testplan,
    languages: languages,
    localize_simulator: true,
    output_directory: output_dir,
    clear_previous_screenshots: true,
    output_simulator_logs: true,
    erase_simulator: true,
    result_bundle: true,
    number_of_retries: 0,
    skip_open_summary: true,
    test_without_building: true,
    derived_data_path: derived_data_path,
    cloned_source_packages_path: cloned_source_packages_path
 )
```
**Running not on M1 processor**
Everything worked fine like a month ago
screenshots.html is also empty 
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                              |
| --------------------------- | -------------------------------------------------- |
| OS                          | 11.2.3                                             |
| Ruby                        | 2.5.0                                              |
| Bundler?                    | false                                              |
| Git                         | git version 2.31.1                                 |
| Installation Source         | ~/.rbenv/versions/2.5.0/bin/fastlane               |
| Host                        | macOS 11.2.3 (20D91)                               |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.0/lib                        |
| OpenSSL Version             | OpenSSL 1.1.1j  16 Feb 2021                        |
| Is contained                | false                                              |
| Is homebrew                 | false                                              |
| Is installed via Fabric.app | false                                              |
| Xcode Path                  | /Applications/Xcode-12.5.0.app/Contents/Developer/ |
| Xcode Version               | 12.5                                               |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.183.1 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.2.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.7.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.3        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.0.0        |
| gh_inspector                    | 1.1.3        |
| rubyzip                         | 2.3.0        |
| security                        | 0.1.3        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.15       |
| simctl                          | 1.6.8        |
| google-apis-playcustomapp_v1    | 0.2.0        |
| google-apis-androidpublisher_v3 | 0.2.0        |
| google-cloud-storage            | 1.31.0       |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.0.3        |
| CFPropertyList                  | 3.0.3        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.19.0       |
| plist                           | 3.6.0        |
| babosa                          | 1.0.4        |
| excon                           | 0.81.0       |
| ruby2_keywords                  | 0.0.4        |
| faraday-net_http_persistent     | 1.1.0        |
| faraday-net_http                | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday                         | 1.4.1        |
| fastimage                       | 2.2.3        |
| json                            | 2.5.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| xcpretty-travis-formatter       | 1.0.1        |
| jwt                             | 2.2.2        |
| webrick                         | 1.7.0        |
| rexml                           | 3.2.5        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| signet                          | 0.15.0       |
| os                              | 1.1.1        |
| memoist                         | 0.16.2       |
| googleauth                      | 0.16.2       |
| mini_mime                       | 1.1.0        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.1        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| google-apis-core                | 0.3.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.3.0        |
| google-apis-storage_v1          | 0.3.0        |
| rake                            | 13.0.3       |
| digest-crc                      | 0.6.3        |
| emoji_regex                     | 3.2.2        |
| aws-eventstream                 | 1.1.1        |
| aws-sigv4                       | 1.2.3        |
| aws-partitions                  | 1.457.0      |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.114.0      |
| aws-sdk-kms                     | 1.43.0       |
| aws-sdk-s3                      | 1.94.1       |
| date                            | 1.0.0        |
| openssl                         | 2.1.0        |
| ipaddr                          | 1.2.0        |
| fileutils                       | 1.0.2        |
| racc                            | 1.5.2        |
| nokogiri                        | 1.11.3       |
| psych                           | 3.0.2        |
</details>

*generated on:* **2021-05-20**
</details> </pre>
</details>

**Comment by bdolewski** [comment]
Well, I deal with the same issue right now. My UI tests are passing and yet I see empty `screenshots` folder and "x" mark at the `fastlane snapshot` results.

**Comment by alexnot95** [comment]
Ok, after debug session looks like I figured out the problem, I changed the place where we use setupSnapshot function and it works fine for now, don't know why It worked before and start failing after the update but for now, the issue is resolved, I think we can close the issue

**Comment by bdolewski** [comment]
> Ok, after debug session looks like I figured out the problem, I changed the place where we use setupSnapshot function and it works fine for now, don't know why It worked before and start failing after the update but for now, the issue is resolved, I think we can close the issue

Just curious - were you trying to call `setupSnapshot()` inside some test-base class?

**Comment by alexnot95** [comment]
> > Ok, after debug session looks like I figured out the problem, I changed the place where we use setupSnapshot function and it works fine for now, don't know why It worked before and start failing after the update but for now, the issue is resolved, I think we can close the issue
> 
> Just curious - were you trying to call `setupSnapshot()` inside some test-base class?

I have the main base test class with launchApp func where I set a lot of arguments and environment variables, so my base localization class inherit base test class and I override launchApp func, so somewhere in this chain something goes wrong, but a month ago everything worked fine  🤷‍♂️

**Comment by bdolewski** [comment]
I have almost the same setup. At the end of the day I figured out to create another scheme, for example "Screenshots". Add new UI test target and attach it to this scheme only. Simple "tests", no assertion - just automation that walk through entire app and grab screenshots.

I don't want my screenshots be taking forever because of actual testing. It became way efficient to me to go this way with separate scheme. I can also create some "manual" jobs on CI of choice to just take screenshots using this new scheme only. Saving some billable build time 😊

**Comment by alexnot95** [comment]
> I have almost the same setup. At the end of the day I figured out to create another scheme, for example "Screenshots". Add new UI test target and attach it to this scheme only. Simple "tests", no assertion - just automation that walk through entire app and grab screenshots.
> 
> 
> 
> I don't want my screenshots be taking forever because of actual testing. It became way efficient to me to go this way with separate scheme. I can also create some "manual" jobs on CI of choice to just take screenshots using this new scheme only. Saving some billable build time 😊

Separate localization test plan in one scheme doesn't work?
We have separate localization jobs to take and save screenshots, and all asserts for different localizations are in regression suite

**Comment by bdolewski** [comment]
> Separate localization test plan in one scheme doesn't work?
We have separate localization jobs to take and save screenshots, and all asserts for different localizations are in regression suite

Oh, didn't understand that by reading for the first time 🙂 Actually I never used test plans. Your setup sounds like a better way then to handle screenshots. Any tips where to start if I may ask?

**Comment by alexnot95** [comment]
> > Separate localization test plan in one scheme doesn't work?
> > We have separate localization jobs to take and save screenshots, and all assert for different localizations are in the regression suite
> 
> Oh, didn't understand that by reading for the first time 🙂 Actually I never used test plans. Your setup sounds like a better way than to handle screenshots. Any tips on where to start if I may ask?

Emm If you have specific questions you can ask)) In a short way we have 1 scheme, in this scheme we have ~10 test plans with different tests set for ex. for Push test plan we run only pushUITests, for the Analytics test plan we run only analyticsUITests and so on.. Also, each test plan can contain different environment variables like a localization test plan to run snapshot. 

If concentrate on localization, we just pass the scheme + needed test plan through FastLane this test plan located in CI job environment variables, localization tests run through the app and take screenshots on each screen, sometimes we can trigger needed screen with fast buttons (when tap on fastbutton it's just an Action to show needed screen) after that when we have all screenshots on all locales we use CI plugin to take generated html and add it to CI build, so everyone can open a link and see full Html with all screenshots, pretty easy approach
