### ISSUE TITLE
This train could not be activated because there is no testable build in the train. 

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1872]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/1019479?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @jonandersen - Imported from <a href='https://github.com/fastlane/pilot/issues/158'>fastlane/pilot#158</a>
        </td>
      </tr>
    </table>

I'm getting an error when trying to submit an app to test flight. The build successfully uploads and appears inside the `app` section of iTunes connect (I can submit it to the App Store). The app can't be released for internal testing (there is no build showing up), but it can be released for external testers. I'm not sure what the error means `there is no testable build in the train. ` but I assume it's related to the build not being available for internal testers? 

crash number: `c9f1898c98cbc1e483e630e5c7fbc0fe`

```
/Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/spaceship-0.21.1/lib/spaceship/tunes/tunes_client.rb:219:in `handle_itc_response': [!] This train could not be activated because there is no testable build in the train. (Spaceship::TunesClient::ITunesConnectError)
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/spaceship-0.21.1/lib/spaceship/tunes/tunes_client.rb:538:in `update_build_trains!'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/spaceship-0.21.1/lib/spaceship/tunes/build_train.rb:118:in `update_testing_status!'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/pilot-1.4.1/lib/pilot/build_manager.rb:124:in `distribute_build'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/pilot-1.4.1/lib/pilot/build_manager.rb:26:in `upload'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane-1.64.0/lib/fastlane/actions/pilot.rb:18:in `run'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane-1.64.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane-1.64.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane-1.64.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane-1.64.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane-1.64.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane-1.64.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:64:in `block (2 levels) in parsing_binding'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane-1.64.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane-1.64.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane-1.64.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane-1.64.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane-1.64.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane-1.64.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane-1.64.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane-1.64.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane_core-0.37.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane-1.64.0/bin/fastlane:156:in `run'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3@global/gems/fastlane-1.64.0/bin/fastlane:162:in `<top (required)>'
	from /Users/jonandersen/.rvm/rubies/ruby-2.1.3/bin/fastlane:23:in `load'
	from /Users/jonandersen/.rvm/rubies/ruby-2.1.3/bin/fastlane:23:in `<main>'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jonandersen/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (437/400 (109%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:42018)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1bEKs4-002lAT-1Q
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:21:33 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=Ekw2ZNdh+BpvQk7+zVP+wJU6Lsg=; b=OpjDXflCaQzxBEtt
	UrqJXEEGWcm8L4ZR6JD5FRG/4wn7aa0RMjUyUd0qHtnoYcwORh81YSrqTPiO7s8s
	2JSgo8pzouUPVQscchXNNU0KrPvtIZieJDAI6618TtMbe0ZjrgveYqolK2zrCqJe
	dYkttv4WgXEHBRN3goDPE0NbNcg=
Received: by filter0432p1mdw1.sendgrid.net with SMTP id filter0432p1mdw1.490.576590F82D
        2016-06-18 18:20:40.814165763 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id Ul2tFBBZRkKcuiQyANOsUA
	for <yann.dupuy@zyapps.com>; Sat, 18 Jun 2016 18:20:40.880 +0000 (UTC)
Date: Sat, 18 Jun 2016 11:20:40 -0700

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (436/400 (109%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:56250 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKrx-002l8r-Mz
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:21:29 +0200
Date: Sat, 18 Jun 2016 11:20:40 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466274040;
	bh=LLxhNq7gm7fsPard4CELOdZ03NJtKuUynk+7rK5snc0=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=vykEWe1BOXclB0iG90uwaybIptXfg9p4F9Tx/y7h+mBLhqyboKrGrTHjcpuJZmo+A
	 IAr40jErLbXxu+yuBe9J1tVC6zHPJlVQdBSsHEzjgGDjimBEehPwhqtGVDX3BmcDAl
	 TApR+AIa9iin20kISymF4sSpiXxXBQBRHBvcqgcg=
