### ISSUE TITLE
Fastlane Match hanging on cloning

### ISSUE THREAD

**Issue by thomaskellough** [fastlane/fastlane#18731]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm on a new computer for a new job and trying to use match to download certificates/profiles and possibly update them. The old developer is no longer working with the company so I don't have access to his old machine and information. 

When I try to use match, it gets stuck on cloning the repo due to authenticity not being able to be established. However, there is no prompt to continue anyway...

##### Command executed
fastlane match --development --verbose

##### Complete output when running fastlane, including the stack trace and command used

git:(master) fastlane match development --verbose
[✔] 🚀
[08:18:58]: fastlane detected a Gemfile in the current directory
[08:18:58]: However, it seems like you didn't use `bundle exec`
[08:18:58]: To launch fastlane faster, please use
[08:18:58]:
[08:18:58]: $ bundle exec fastlane match development --verbose
[08:18:58]:
[08:18:58]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
Successfully loaded Appfile at path '/Users/xxx/xxx/xxx/xxx/xxx/fastlane/Appfile'
- app_identifier: ‘xxx'
- apple_id: 'xxx'
- itc_team_id: 'xxx'
- team_id: 'xxx'
-------
INFO [2021-05-21 08:18:59.86]: Successfully loaded '/Users/xxx/xxx/xxx/xxx/xxx/fastlane/Matchfile' 📄

+--------------+---------------------------------------+
|     Detected Values from './fastlane/Matchfile'      |
+--------------+---------------------------------------+
| git_url           | git@github.com:xxx/apple-certs.git|
| storage_mode | git                                                |
| type              | development                                   |
+--------------+---------------------------------------+

+--------------------------------+---------------------------------------+
|                       Summary for match 2.183.2                                    |
+--------------------------------+---------------------------------------+
| verbose                                 | true                                                |
| type                          	            | development                                  |
| readonly                                | false                                               |
| generate_apple_certs           | true                                                 |
| skip_provisioning_profiles    | false                                                |
| app_identifier                       | ["xxx"]                                             |
| username                             | xxx                                                  |
| team_id                                | xxx                                                  |
| storage_mode                      | git                                                    |
| git_url                                    | git@github.com:xxx/apple-certs.git |
| git_branch                            | master                                             |
| shallow_clone                      | false                                                 |
| clone_branch_directly          | false                                                 |
| keychain_name                   | login.keychain                                   |
| force                                     | false                                                 |
| force_for_new_devices        | false                                                 |
| skip_confirmation                | false                                                 |
| skip_docs                            | false                                                 |
| platform                               | ios                                                    |
| derive_catalyst_app_identifier | false                                             |
| fail_on_name_taken             | false                                                 |
| skip_certificate_matching      | false                                              |
| skip_set_partition_list            | false                                              |
+--------------------------------+---------------------------------------+

INFO [2021-05-21 08:18:59.87]: Cloning remote git repo...
INFO [2021-05-21 08:18:59.87]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
INFO [2021-05-21 08:18:59.87]: $ git clone git@github.com:xxx/apple-certs.git /var/folders/n5/s4t72jlx1jn14lzmzgxn8kw00000gn/T/d20210521-37232-1mwscar
INFO [2021-05-21 08:18:59.88]: ▸ Cloning into '/var/folders/n5/s4t72jlx1jn14lzmzgxn8kw00000gn/T/d20210521-37232-1mwscar'...
INFO [2021-05-21 08:19:00.31]: ▸ The authenticity of host 'github.com (xxx.xx.xxx.x)' can't be established.
INFO [2021-05-21 08:19:00.31]: ▸ RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 11.2.3                                                     |
| Ruby                        | 2.7.3                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.30.1 (Apple Git-130)                         |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.183.2/libexec/bin/fastlane |
| Host                        | macOS 11.2.3 (20D91)                                       |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby@2.7/2.7.3/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                                |
| Is contained                | false                                                      |
| Is homebrew                 | true                                                       |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
| Xcode Version               | 12.5                                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
### KIOSK

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require 'spaceship'

default_platform(:ios) 
xcversion(version: "12.2.0")

platform :ios do

	before_all do
		setup_ci
	end

	def set_build_number
		build_number = latest_testflight_build_number + 1

		increment_build_number(build_number: build_number)

		set_info_plist_value(path: "./xxx/Info.plist", key: "CFBundleVersion", 
		value: build_number.to_s)

		set_info_plist_value(path: "./xxx/Info.plist", key: "CFBundleVersion", 
		value: build_number.to_s)

	end

	# set version number to either the git tag
	# or the latest approved version + patch. 
	def set_version_number
		if (!last_git_tag.nil?)
			increment_version_number(version_number: last_git_tag[1..-1])
		else 
			# a call to app_store_build_number generates LATEST_VERSION in lane_context
			app_store_build_number
			version_number = lane_context[SharedValues:: LATEST_VERSION]
			increment_version_number(version_number: version_number)
			increment_version_number(bump_type: "patch")
		end
	end

	def set_deployment_info
		path = String("./VisitU/Info.plist")
		set_info_plist_value(path: path, key: "branch", value: ENV["BRANCH"])
		set_info_plist_value(path: path, key: "number", value: ENV["NUMBER"])
		set_info_plist_value(path: path, key: "hash", value: ENV["HASH"])
		set_info_plist_value(path: path, key: "tag", value: ENV["TAG"])
	end

	lane :build do
		set_build_number
		set_version_number
		build_app(workspace: "xxx.xcworkspace", scheme: 'VisitU')
	end

	lane :beta do

		api_key = app_store_connect_api_key(
			key_id: "xxx",
			issuer_id: "xxx",
			key_filepath: "./AuthKey_xxx.p8",
			duration: 1200, # optional (maximum 1200)
		)

		match(
			readonly: false,
			app_identifier: ["com.xxx.xxx","com.xxx.xxx.xxx"],
			type: "appstore",
			verbose: true,
			api_key: api_key,
			git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"]
		)

		build

		upload_to_testflight(skip_waiting_for_build_processing: true)

	end

	lane :release do

		# api_key = app_store_connect_api_key(
		# 	key_id: "xxx",
		# 	issuer_id: "xxx1",
		# 	key_filepath: "./AuthKey_xxx.p8",
		# 	duration: 1200, # optional (maximum 1200)
		# )

		match(
			readonly: false,
			app_identifier: ["com.xxx.xxx","com.xxx.xxx.xxx"],
			type: "appstore",
		)

		build

		set_deployment_info

		upload_to_app_store(
			force: true, 
			automatic_release: false,
			skip_screenshots: true, 
			precheck_include_in_app_purchases: false,
			submit_for_review: true,
			reject_if_possible: true,
			submission_information: {
				add_id_info_uses_idfa: false
			})
	end

	desc "Upload dSYM to Sentry"
	lane :dsym do
		download_dsyms(version: "latest")
		sentry_upload_dsym(
			auth_token: ENV['SENTRY_AUTH_TOKEN'],
			org_slug: "visitu",
			project_slug: "xxx",
			dsym_path: "./xxx.app.dSYM.zip"
		)
		
	end
	
	lane :tests do
  		run_tests(workspace: "xxx.xcworkspace",
            		devices: ["iPad (8th generation)"],
            		scheme: "Configurations Debug (Production)",
			configuration: "Debug(Production)")
	end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("xxx") # The bundle identifier of your app
apple_id("xxx") # Your Apple email address

itc_team_id("xxx") # App Store Connect Team ID
team_id("xxx") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.183.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                 | Version | Update-Status |
| ---------------------- | ------- | ------------- |
| fastlane-plugin-sentry | 1.8.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.4.0        |
| atomos                          | 0.1.3        |
| CFPropertyList                  | 3.0.3        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.19.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.7.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.81.0       |
| faraday-excon                   | 1.1.0        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.1.0        |
| ruby2_keywords                  | 0.0.4        |
| faraday                         | 1.4.1        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.3        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.0.0        |
| fastimage                       | 2.2.3        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.3.0        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.0        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.15       |
| simctl                          | 1.6.8        |
| jwt                             | 2.2.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.1        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.0        |
| multi_json                      | 1.15.0       |
| signet                          | 0.15.0       |
| memoist                         | 0.16.2       |
| os                              | 1.1.1        |
| googleauth                      | 0.16.2       |
| httpclient                      | 2.8.3        |
| rexml                           | 3.2.3.1      |
| webrick                         | 1.6.1        |
| google-apis-core                | 0.3.0        |
| google-apis-playcustomapp_v1    | 0.2.0        |
| google-apis-androidpublisher_v3 | 0.2.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.3.0        |
| google-apis-storage_v1          | 0.3.0        |
| rake                            | 13.0.3       |
| digest-crc                      | 0.6.3        |
| google-cloud-storage            | 1.31.0       |
| emoji_regex                     | 3.2.2        |
| jmespath                        | 1.4.0        |
| aws-partitions                  | 1.457.0      |
| aws-eventstream                 | 1.1.1        |
| aws-sigv4                       | 1.2.3        |
| aws-sdk-core                    | 3.114.0      |
| aws-sdk-kms                     | 1.43.0       |
| aws-sdk-s3                      | 1.94.1       |
| uri                             | 0.10.0       |
| forwardable                     | 1.3.1        |
| logger                          | 1.4.2        |
| cgi                             | 0.1.0        |
| date                            | 3.0.0        |
| timeout                         | 0.1.0        |
| stringio                        | 0.1.0        |
| zlib                            | 1.1.0        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| ostruct                         | 0.2.0        |
| strscan                         | 1.0.3        |
| io-console                      | 0.5.6        |
| delegate                        | 0.1.0        |
| fileutils                       | 1.4.1        |
| singleton                       | 0.1.0        |
| open3                           | 0.1.0        |
| yaml                            | 0.1.0        |
| psych                           | 3.1.0        |
| mutex_m                         | 0.1.0        |
| fastlane-plugin-sentry          | 1.8.1        |
</details>

*generated on:* **2021-05-21**
</details>

 I also tried using `clone_branch_directly` but the same things happens

**Comment by crazymanish** [comment]
Hi @thomaskellough 
Question: Do you have access to clone the `apple-certs` git repo? 
I request you to perform a git clone directly once to ensure that you have the access to clone this repo, you can use the above command directly, i.e

```ruby
git clone git@github.com:xxx/apple-certs.git
```

**Comment by thomaskellough** [comment]
@crazymanish Thanks for reaching out. 

I can't clone if I use ssh, but I can if I use HTTP. 

With ssh I get this output.

```
git clone git@github.com:xxx/apple-certs.git
Cloning into 'apple-certs'...
Warning: Permanently added the RSA host key for IP address 'xxx.xx.xxx.x' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

This is a private repository not owned by me, but where I have access.

**Comment by crazymanish** [comment]
this is it! 
This is the confirmation that it's not a Fastlane issue, it's your git-clone issue using ssh...
**You can setup your ssh key** in your GitHub account with your new MacBook and everything will work after that.
Follow instructions here: https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh

Please feel free to close this issue! @thomaskellough and Enjoy your weekend! 🚀

**Comment by thomaskellough** [comment]
@crazymanish Thanks so much! Following those steps then adding the SSH to my GitHub did the trick :)
