### ISSUE TITLE
Cannot update fast lane due to missing -lgmp

### ISSUE THREAD

**Issue by pronebird** [fastlane/fastlane#18749]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>bundle update fastlane
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Fetching rake 13.0.3 (was 13.0.1)
Installing rake 13.0.3 (was 13.0.1)
Fetching CFPropertyList 3.0.3 (was 3.0.2)
Installing CFPropertyList 3.0.3 (was 3.0.2)
Using public_suffix 4.0.6
Using addressable 2.7.0
Using atomos 0.1.3
Fetching aws-eventstream 1.1.1 (was 1.1.0)
Installing aws-eventstream 1.1.1 (was 1.1.0)
Fetching aws-partitions 1.462.0 (was 1.365.0)
Installing aws-partitions 1.462.0 (was 1.365.0)
Fetching aws-sigv4 1.2.3 (was 1.2.2)
Installing aws-sigv4 1.2.3 (was 1.2.2)
Using jmespath 1.4.0
Fetching aws-sdk-core 3.114.0 (was 3.105.0)
Installing aws-sdk-core 3.114.0 (was 3.105.0)
Fetching aws-sdk-kms 1.43.0 (was 1.37.0)
Installing aws-sdk-kms 1.43.0 (was 1.37.0)
Fetching aws-sdk-s3 1.95.1 (was 1.79.1)
Installing aws-sdk-s3 1.95.1 (was 1.79.1)
Fetching babosa 1.0.4 (was 1.0.3)
Installing babosa 1.0.4 (was 1.0.3)
Using bundler 1.16.6
Using claide 1.0.3
Using colored 1.2
Using colored2 3.1.2
Using highline 1.7.10
Using commander-fastlane 4.4.6
Using declarative 0.0.20
Fetching digest-crc 0.6.3 (was 0.6.1)
Installing digest-crc 0.6.3 (was 0.6.1) with native extensions
Using unf_ext 0.0.7.7
Using unf 0.1.4
Using domain_name 0.5.20190701
Using dotenv 2.7.6
Fetching emoji_regex 3.2.2 (was 3.0.0)
Installing emoji_regex 3.2.2 (was 3.0.0)
Fetching excon 0.81.0 (was 0.76.0)
Installing excon 0.81.0 (was 0.76.0)
Fetching faraday-em_http 1.0.0
Installing faraday-em_http 1.0.0
Fetching faraday-em_synchrony 1.0.0
Installing faraday-em_synchrony 1.0.0
Fetching faraday-excon 1.1.0
Installing faraday-excon 1.1.0
Fetching faraday-net_http 1.0.1
Installing faraday-net_http 1.0.1
Fetching faraday-net_http_persistent 1.1.0
Installing faraday-net_http_persistent 1.1.0
Using multipart-post 2.0.0
Fetching ruby2_keywords 0.0.4
Installing ruby2_keywords 0.0.4
Fetching faraday 1.4.2 (was 1.0.1)
Installing faraday 1.4.2 (was 1.0.1)
Using http-cookie 1.0.3
Using faraday-cookie_jar 0.0.7
Using faraday_middleware 1.0.0
Fetching fastimage 2.2.3 (was 2.2.0)
Installing fastimage 2.2.3 (was 2.2.0)
Using gh_inspector 1.1.3
Fetching jwt 2.2.3 (was 2.2.2)
Installing jwt 2.2.3 (was 2.2.2)
Using memoist 0.16.2
Using multi_json 1.15.0
Using os 1.1.1
Fetching signet 0.15.0 (was 0.14.0)
Installing signet 0.15.0 (was 0.14.0)
Fetching googleauth 0.16.2 (was 0.13.1)
Installing googleauth 0.16.2 (was 0.13.1)
Using httpclient 2.8.3
Fetching mini_mime 1.1.0 (was 1.0.2)
Installing mini_mime 1.1.0 (was 1.0.2)
Fetching trailblazer-option 0.1.1
Installing trailblazer-option 0.1.1
Using uber 0.1.0
Fetching representable 3.1.1 (was 3.0.4)
Installing representable 3.1.1 (was 3.0.4)
Using retriable 3.1.2
Using google-api-client 0.38.0
Fetching rexml 3.2.5
Installing rexml 3.2.5
Fetching webrick 1.7.0
Installing webrick 1.7.0
Fetching google-apis-core 0.3.0
Installing google-apis-core 0.3.0
Fetching google-apis-iamcredentials_v1 0.4.0
Installing google-apis-iamcredentials_v1 0.4.0
Fetching google-apis-storage_v1 0.4.0
Installing google-apis-storage_v1 0.4.0
Fetching google-cloud-env 1.5.0 (was 1.3.3)
Installing google-cloud-env 1.5.0 (was 1.3.3)
Fetching google-cloud-errors 1.1.0 (was 1.0.1)
Installing google-cloud-errors 1.1.0 (was 1.0.1)
Fetching google-cloud-core 1.6.0 (was 1.5.0)
Installing google-cloud-core 1.6.0 (was 1.5.0)
Fetching google-cloud-storage 1.31.1 (was 1.28.0)
Installing google-cloud-storage 1.31.1 (was 1.28.0)
Fetching json 2.5.1 (was 2.3.1)
Installing json 2.5.1 (was 2.3.1) with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/pronebird/.rvm/gems/ruby-2.5.1/gems/json-2.5.1/ext/json/ext/generator
/Users/pronebird/.rvm/rubies/ruby-2.5.1/bin/ruby -r ./siteconf20210525-41829-1ln6z2u.rb extconf.rb
creating Makefile

current directory: /Users/pronebird/.rvm/gems/ruby-2.5.1/gems/json-2.5.1/ext/json/ext/generator
make "DESTDIR=" clean

current directory: /Users/pronebird/.rvm/gems/ruby-2.5.1/gems/json-2.5.1/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
linking shared-object json/ext/generator.bundle
ld: library not found for -lgmp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [generator.bundle] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/pronebird/.rvm/gems/ruby-2.5.1/gems/json-2.5.1 for inspection.
Results logged to /Users/pronebird/.rvm/gems/ruby-2.5.1/extensions/x86_64-darwin-18/2.5.0/json-2.5.1/gem_make.out

An error occurred while installing json (2.5.1), and Bundler cannot continue.
Make sure that `gem install json -v '2.5.1' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  fastlane was resolved to 2.158.0, which depends on
    json

</pre>
</details>

### Environment

<details>
  <pre> <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 11.2.3                                           |
| Ruby                        | 2.5.1                                            |
| Bundler?                    | true                                             |
| Git                         | git version 2.30.1 (Apple Git-130)               |
| Installation Source         | ~/.rvm/gems/ruby-2.5.1/bin/fastlane              |
| Host                        | macOS 11.2.3 (20D91)                             |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.5.1/lib                     |
| OpenSSL Version             | OpenSSL 1.1.1  11 Sep 2018                       |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-12.5.app/Contents/Developer/ |
| Xcode Version               | 12.5                                             |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.158.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.16.6       |
| rake                      | 13.0.1       |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.365.0      |
| aws-sigv4                 | 1.2.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.105.0      |
| aws-sdk-kms               | 1.37.0       |
| aws-sdk-s3                | 1.79.1       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.0.0        |
| excon                     | 0.76.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 1.0.1        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.2.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| signet                    | 0.14.0       |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.28.0       |
| json                      | 2.3.1        |
| mini_magick               | 4.10.1       |
| plist                     | 3.5.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.18.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2021-05-25**
</details> </pre>
</details>

**Comment by Treeane** [comment]
Run bundle update and add both the ./Gemfile and the ./Gemfile.lock to version control.
Every time you run fastlane, use bundle exec fastlane [lane]
On your CI, add bundle install as your first build step [Official Website](https://www.dgcustomerfirst.run/)
To update fastlane, just run bundle update fastlane.

**Comment by Armstrong-256** [comment]
Next, install fastlane and execute the following command in Terminal: Choosing Product Lead grants access to update all tracks except the production fastlane cannot create a new listing on the Play Store. File google-services.json is missing.
