### ISSUE TITLE
Match - Failed new development provisioning profile (ENTITY_ERROR)

### ISSUE THREAD

**Issue by escakot** [fastlane/fastlane#18742]
Hello there, 

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Successfully creates certificate but fails to create a new development provisioning profile after running `fastlane match nuke development`. I've changed recently from using an account Login to the AppStoreConnectAPI key.

##### Command executed
`fastlane match development`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
[✔] 🚀 
[13:58:20]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

+--------------------------------+---------------------------------------------------------+
|                                Summary for match 2.184.0                                 |
+--------------------------------+---------------------------------------------------------+
| type                           | development                                             |
| readonly                       | false                                                   |
| generate_apple_certs           | true                                                    |
| skip_provisioning_profiles     | false                                                   |
| app_identifier                 | ["com.touchbistro.TouchBistro"]                         |
| api_key_path                   | ./appstore_connect_api_key.json                         |
| team_id                        | R8HVB85AU9                                              |
| team_name                      | TouchBistro Inc.                                        |
| storage_mode                   | git                                                     |
| git_url                        | git@github.com:TouchBistro/*redacted*.git |
| git_branch                     | renew-certificates                                      |
| shallow_clone                  | false                                                   |
| clone_branch_directly          | false                                                   |
| keychain_name                  | login.keychain                                          |
| force                          | false                                                   |
| force_for_new_devices          | false                                                   |
| skip_confirmation              | false                                                   |
| skip_docs                      | false                                                   |
| platform                       | ios                                                     |
| derive_catalyst_app_identifier | false                                                   |
| template_name                  | Contact Note Field Access iOS                           |
| fail_on_name_taken             | false                                                   |
| skip_certificate_matching      | false                                                   |
| skip_set_partition_list        | false                                                   |
| verbose                        | false                                                   |
+--------------------------------+---------------------------------------------------------+

[13:58:25]: Cloning remote git repo...
[13:58:25]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[13:58:25]: Checking out branch renew-certificates...
[13:58:26]: 🔓  Successfully decrypted certificates repo
[13:58:26]: Verifying that the certificate and profile are still valid on the Dev Portal...
[13:58:26]: Creating authorization token for App Store Connect API
[13:58:26]: Couldn't find a valid code signing identity for development... creating one for you now

+-------------------------+----------------------------------------------------+
|                           Summary for cert 2.184.0                           |
+-------------------------+----------------------------------------------------+
| platform                | ios                                                |
| development             | true                                               |
| generate_apple_certs    | true                                               |
| force                   | true                                               |
| api_key_path            | ./appstore_connect_api_key.json                    |
| team_id                 | R8HVB85AU9                                         |
| team_name               | TouchBistro Inc.                                   |
| keychain_path           | /Users/echeong/Library/Keychains/login.keychain-db |
| skip_set_partition_list | false                                              |
+-------------------------+----------------------------------------------------+

[13:58:26]: Creating authorization token for App Store Connect API
[13:58:27]: Using keychain password from keychain item fastlane_keychain_login in /Users/echeong/Library/Keychains/login.keychain-db
[✔] Setting key partition list... (this can take a minute if there are a lot of keys installed) 
[13:58:27]: Using keychain password from keychain item fastlane_keychain_login in /Users/echeong/Library/Keychains/login.keychain-db
[✔] Setting key partition list... (this can take a minute if there are a lot of keys installed) 
[13:58:28]: Successfully generated 448V38V6YK which was imported to the local machine.
[13:58:28]: Verifying the certificate is properly installed locally...
[13:58:28]: Successfully installed certificate 448V38V6YK

+-------------------------------------+-----------------------------------------------+
|                              Summary for sigh 2.184.0                               |
+-------------------------------------+-----------------------------------------------+
| app_identifier                      | com.touchbistro.TouchBistro                   |
| force                               | false                                         |
| cert_id                             | 448V38V6YK                                    |
| provisioning_name                   | match Development com.touchbistro.TouchBistro |
| ignore_profiles_with_different_name | true                                          |
| api_key_path                        | ./appstore_connect_api_key.json               |
| team_id                             | R8HVB85AU9                                    |
| team_name                           | TouchBistro Inc.                              |
| template_name                       | Contact Note Field Access iOS                 |
| fail_on_name_taken                  | false                                         |
| platform                            | ios                                           |
| development                         | true                                          |
| adhoc                               | false                                         |
| developer_id                        | false                                         |
| skip_install                        | false                                         |
| skip_fetch_profiles                 | false                                         |
| skip_certificate_verification       | false                                         |
| readonly                            | false                                         |
+-------------------------------------+-----------------------------------------------+

[13:58:31]: Creating authorization token for App Store Connect API
[13:58:31]: Fetching profiles...
[13:58:32]: Verifying certificates...
[13:58:32]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[13:58:34]: Creating new provisioning profile for 'com.touchbistro.TouchBistro' with name 'match Development com.touchbistro.TouchBistro' for 'ios' platform
[13:58:38]: An error occurred while verifying your certificates and profiles with the Apple Developer Portal.
[13:58:38]: If you already have your certificates stored in git, you can run `fastlane match` in readonly mode
[13:58:38]: to just install the certificates and profiles without accessing the Dev Portal.
[13:58:38]: To do so, just pass `readonly: true` to your match call.

Looking for related GitHub issues on fastlane/fastlane...

Traceback (most recent call last):
	27: from /Users/echeong/.rbenv/versions/2.7.2/bin/fastlane:23:in `<main>'
	26: from /Users/echeong/.rbenv/versions/2.7.2/bin/fastlane:23:in `load'
	25: from /Users/echeong/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/bin/fastlane:23:in `<top (required)>'
	24: from /Users/echeong/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	23: from /Users/echeong/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/match/lib/match/commands_generator.rb:26:in `start'
	22: from /Users/echeong/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/match/lib/match/commands_generator.rb:188:in `run'
	21: from /Users/echeong/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	20: from /Users/echeong/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	19: from /Users/echeong/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	18: from /Users/echeong/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	17: from /Users/echeong/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	16: from /Users/echeong/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/match/lib/match/commands_generator.rb:69:in `block (3 levels) in run'
	15: from /Users/echeong/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/match/lib/match/runner.rb:109:in `run'
	14: from /Users/echeong/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/match/lib/match/runner.rb:109:in `each'
	13: from /Users/echeong/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/match/lib/match/runner.rb:110:in `block in run'
	12: from /Users/echeong/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/match/lib/match/runner.rb:110:in `loop'
	11: from /Users/echeong/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/match/lib/match/runner.rb:111:in `block (2 levels) in run'
	10: from /Users/echeong/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/match/lib/match/runner.rb:269:in `fetch_provisioning_profile'
	 9: from /Users/echeong/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/match/lib/match/generator.rb:108:in `generate_provisioning_profile'
	 8: from /Users/echeong/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/sigh/lib/sigh/manager.rb:8:in `start'
	 7: from /Users/echeong/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/sigh/lib/sigh/runner.rb:54:in `run'
	 6: from /Users/echeong/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/sigh/lib/sigh/runner.rb:182:in `create_profile!'
	 5: from /Users/echeong/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/spaceship/lib/spaceship/connect_api/models/profile.rb:76:in `create'
	 4: from /Users/echeong/.rbenv/versions/2.7.2/lib/ruby/2.7.0/forwardable.rb:235:in `post_profiles'
	 3: from /Users/echeong/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/spaceship/lib/spaceship/connect_api/provisioning/provisioning.rb:189:in `post_profiles'
	 2: from /Users/echeong/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/spaceship/lib/spaceship/connect_api/provisioning/client.rb:39:in `post'
	 1: from /Users/echeong/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/spaceship/lib/spaceship/connect_api/api_client.rb:124:in `post'
/Users/echeong/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/spaceship/lib/spaceship/connect_api/api_client.rb:194:in `handle_response': \e[31m[!] { (Spaceship::UnexpectedResponse)
  "errors" : [ {
    "id" : "f99d0e0d-6230-4a47-93c3-10a449b2f3eb",
    "status" : "409",
    "code" : "ENTITY_ERROR",
    "title" : "There is a problem with the request entity",
    "detail" : "There was an error generating the provisioning profile 'match Development com.touchbistro.TouchBistro'.  Please try again.  If the problem persists, please contact Apple Developer Program Support. https://developer.apple.com/support"
  } ]
}\e[0m

 </pre>
</details>

### Environment

[✔] 🚀 
[14:04:21]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[14:04:26]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.15.7                                          |
| Ruby                        | 2.7.2                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.24.3 (Apple Git-128)               |
| Installation Source         | ~/.rbenv/versions/2.7.2/bin/fastlane             |
| Host                        | Mac OS X 10.15.7 (19H2)                          |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.2/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                       |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-12.2.app/Contents/Developer/ |
| Xcode Version               | 12.2                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**Fastfile redacted, not applicable**
**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.184.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.4.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| terminal-table                  | 1.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| artifactory                     | 3.0.15       |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| faraday_middleware              | 1.0.0        |
| gh_inspector                    | 1.1.3        |
| rubyzip                         | 2.3.0        |
| security                        | 0.1.3        |
| google-apis-playcustomapp_v1    | 0.2.0        |
| google-apis-androidpublisher_v3 | 0.3.0        |
| uri                             | 0.10.0       |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.0.3        |
| CFPropertyList                  | 3.0.3        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.19.0       |
| unicode-display_width           | 1.7.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.7.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| babosa                          | 1.0.4        |
| excon                           | 0.81.0       |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.3        |
| ruby2_keywords                  | 0.0.4        |
| faraday-net_http_persistent     | 1.1.0        |
| faraday-net_http                | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.4.2        |
| faraday-cookie_jar              | 0.0.7        |
| fastimage                       | 2.2.3        |
| json                            | 2.5.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.17       |
| simctl                          | 1.6.8        |
| jwt                             | 2.2.3        |
| webrick                         | 1.7.0        |
| rexml                           | 3.2.5        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| signet                          | 0.15.0       |
| os                              | 1.1.1        |
| memoist                         | 0.16.2       |
| googleauth                      | 0.16.2       |
| mini_mime                       | 1.1.0        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.1        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| google-apis-core                | 0.3.0        |
| rake                            | 13.0.3       |
| digest-crc                      | 0.6.3        |
| google-apis-storage_v1          | 0.3.0        |
| google-apis-iamcredentials_v1   | 0.3.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.31.1       |
| emoji_regex                     | 3.2.2        |
| aws-eventstream                 | 1.1.1        |
| aws-sigv4                       | 1.2.3        |
| aws-partitions                  | 1.461.0      |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.114.0      |
| aws-sdk-kms                     | 1.43.0       |
| aws-sdk-s3                      | 1.95.0       |
| forwardable                     | 1.3.1        |
| logger                          | 1.4.2        |
| cgi                             | 0.1.0        |
| date                            | 3.0.0        |
| timeout                         | 0.1.0        |
| stringio                        | 0.1.0        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.1.0        |
| ostruct                         | 0.2.0        |
| strscan                         | 1.0.3        |
| io-console                      | 0.5.6        |
| delegate                        | 0.1.0        |
| fileutils                       | 1.4.1        |
| singleton                       | 0.1.0        |
| open3                           | 0.1.0        |
| yaml                            | 0.1.0        |
| psych                           | 3.1.0        |
| mutex_m                         | 0.1.0        |
</details>

*generated on:* **2021-05-22**
</details>

**Comment by krystianpaszek** [comment]
I'm experiencing the same problem right now.

**Comment by msuzoagu** [comment]
@krystianpaszek @escakot I am experiencing the same issue; any resolutions you can share?

**Comment by escakot** [comment]
@msuzoagu Nope, it still wasn't working for me in the end. 

Fastlane still couldn't create the Provisioning Profile. So, I manually created a the Certificate & Provisioning profile and used `fastlane match import` instead.

**Comment by krystianpaszek** [comment]
@msuzoagu for me it was a problem with the development team. For some reason profiles with com.apple.developer.playable-content can't be created in this particular team and that was the reason for getting 409 ENTITY_ERROR response from the dev portal.

**Comment by Elkins587** [comment]
This is such a great resource that you are providing and you give it away for free. I like seeing blog that understand the value of providing a quality resource for free.

[paycheckrecords](https://www.paycheckrecords.me/)
