### ISSUE TITLE
fastlane sigh manage -e error

### ISSUE THREAD

**Issue by wvteijlingen** [fastlane/fastlane#18757]
### Issue Description

Reopening issue https://github.com/fastlane/fastlane/issues/16642, which was closed even though the problem still exists. 

##### Command executed
```
fastlane sigh manage -e
```

##### Complete output when running fastlane, including the stack trace and command used
```
Traceback (most recent call last):
    8: from /Users/x/.rbenv/versions/2.7.1/bin/fastlane:23:in `<main>'
    7: from /Users/x/.rbenv/versions/2.7.1/bin/fastlane:23:in `load'
    6: from /Users/x/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/bin/fastlane:23:in `<top (required)>'
    5: from /Users/x/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
    4: from /Users/x/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/sigh/lib/sigh/commands_generator.rb:17:in `start'
    3: from /Users/x/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/sigh/lib/sigh/commands_generator.rb:140:in `run'
    2: from /Users/x/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
    1: from /Users/x/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:50:in `run!'
/Users/baumeister/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:379:in `parse_global_options': missing argument: -e (OptionParser::MissingArgument)
```

**Comment by crazymanish** [comment]
Dear @wvteijlingen 

Fixed this command, **I am requesting you** to test this PR https://github.com/fastlane/fastlane/pull/18760, which will fix this issue.
- Update Gemfile and run `bundle install` with
```
gem "fastlane", :git => "git@github.com:crazymanish/fastlane.git", :branch => "sigh-manage-clean_expired-fix"
```
- Run `bundle exec fastlane sigh manage -e`

Thank you!

-----
Its working for me now! see screenshot! 😇
<img width="1217" alt="Screenshot 2021-05-26 at 19 40 56 2" src="https://user-images.githubusercontent.com/5364500/119708020-1eec3f80-be5c-11eb-91fd-c82c2b089549.png">

**Comment by wvteijlingen** [comment]
@crazymanish

Thanks for the quick response! I looked in the PR and it seemed that it wasn't entirely ready yet. I'll hold of testing until then :).

**Comment by crazymanish** [comment]
> @crazymanish
> 
> 
> 
> Thanks for the quick response! I looked in the PR and it seemed that it wasn't entirely ready yet. I'll hold of testing until then :).

Yes it's seem this is ruby library(optparse) issue for parsing '-e' option (introduced this bug above Ruby2.5)

I will update you again when PR will be ready for review and testing.
Thank you for your patience 🙏
