### ISSUE TITLE
2.184.0 Breaks APP_STORE_CONNECT_API_KEY_KEY content

### ISSUE THREAD

**Issue by colin-campbell** [fastlane/fastlane#18754]
- [ x] Updated fastlane to the latest version
- [ x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information
- Breaking version: [2.184.0]
- Last working version: [2.183.2]

### Regression Description

Key content (double-escaped '\\\\n' - checked also '\n') passed as key_content or env variable APP_STORE_CONNECT_API_KEY_KEY fails with  "wrong number of arguments (given 1, expected 0)" in spaceship connect api. (token.rb). Working fine up to and including 2.183.2  

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>bundle exec fastlane ios client_test
[✔] 🚀
+--------------------------------------+---------+-----------------------------+
|                                 Used plugins                                 |
+--------------------------------------+---------+-----------------------------+
| Plugin                               | Version | Action                      |
+--------------------------------------+---------+-----------------------------+
| fastlane-plugin-commit_android_vers  | 0.2.0   | commit_android_version_bump |
| ion_bump                             |         |                             |
| fastlane-plugin-versioning_android   | 0.1.0   | android_get_version_code    |
|                                      |         | android_get_version_name    |
|                                      |         | android_set_version_code    |
|                                      |         | android_set_version_name    |
| fastlane-plugin-versioning_ios       | 0.1.0   | ios_get_build_number        |
|                                      |         | ios_get_version             |
|                                      |         | ios_set_build_number        |
|                                      |         | ios_set_version             |
| fastlane-plugin-slack_upload         | 0.1.0   | slack_upload                |
+--------------------------------------+---------+-----------------------------+

[06:40:10]: ---------------------------
[06:40:10]: --- Step: opt_out_usage ---
[06:40:10]: ---------------------------
[06:40:10]: Disabled upload of used actions
[06:40:10]: -------------------------
[06:40:10]: --- Step: setup_drone ---
[06:40:10]: -------------------------
[06:40:10]: This plugin is deprecated. configure the Mac DRone runner instead.
[06:40:10]: Not running on Drone CI, skipping CI setup
[06:40:10]: Driving the lane 'ios client_test' 🚀
[06:40:10]: -----------------------
[06:40:10]: --- Step: xcversion ---
[06:40:10]: -----------------------
[06:40:11]: Setting Xcode version to /Applications/Xcode.app for all build steps
[06:40:11]: ---------------------------------
[06:40:11]: --- Step: update_project_team ---
[06:40:11]: ---------------------------------
[06:40:11]: Updating development team (REDACTED) for target `REDACTED` in the project 'ios/REDACTED.xcodeproj'
[06:40:11]: Successfully updated project settings to use Developer Team ID 'TM4FYV9W36' for target `REDACTED`
[06:40:11]: Updating development team (REDACTED) for target `REDACTEDTests` in the project 'ios/REDACTED.xcodeproj'
[06:40:11]: Successfully updated project settings to use Developer Team ID 'REDACTED' for target `REDACTEDTests`
[06:40:11]: ---------------------------------------
[06:40:11]: --- Step: app_store_connect_api_key ---
[06:40:11]: ---------------------------------------
[06:40:11]: -------------------
[06:40:11]: --- Step: slack ---
[06:40:11]: -------------------
[06:40:11]: Successfully sent Slack notification
+---------------+-----------------+
|          Lane Context           |
+---------------+-----------------+
| PLATFORM_NAME | ios             |
| LANE_NAME     | ios client_test |
+---------------+-----------------+
[06:40:11]: wrong number of arguments (given 1, expected 0)

+------+---------------------------+-------------+
|                fastlane summary                |
+------+---------------------------+-------------+
| Step | Action                    | Time (in s) |
+------+---------------------------+-------------+
| 1    | opt_out_usage             | 0           |
| 2    | setup_drone               | 0           |
| 3    | xcversion                 | 0           |
| 4    | update_project_team       | 0           |
| 💥   | app_store_connect_api_key | 0           |
| 6    | slack                     | 0           |
+------+---------------------------+-------------+

[06:40:11]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  upload_to_play_store fails with error wrong number of arguments (given 1, expected 0)
    https://github.com/fastlane/fastlane/issues/18698 [closed] 9 💬
    a week ago

➡️  Passing api-key to sigh via CLI doesn't work
    https://github.com/fastlane/fastlane/issues/18222 [open] 5 💬
    2 days ago

➡️  [supply][Ruby 3] fix Ruby 3 keyword args issues
    https://github.com/fastlane/fastlane/pull/18703 [closed] 0 💬
    a week ago

and 27 more at: https://github.com/fastlane/fastlane/search?q=wrong%20number%20of%20arguments%20%28given%201%2C%20expected%200%29&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/Users/colin/dev/apps/REDACTED_mobile_app/vendor/bundle/ruby/3.0.0/bin/fastlane)
/Users/colin/dev/apps/REDACTED_mobile_app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.184.0/spaceship/lib/spaceship/connect_api/token.rb:49:in `create': \e[31m[!] wrong number of arguments (given 1, expected 0)\e[0m (ArgumentError)
	from /Users/colin/dev/apps/REDACTED_mobile_app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/actions/app_store_connect_api_key.rb:43:in `run'
	from /Users/colin/dev/apps/REDACTED_mobile_app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/colin/dev/apps/REDACTED_mobile_app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/colin/dev/apps/REDACTED_mobile_app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/colin/dev/apps/REDACTED_mobile_app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/colin/dev/apps/REDACTED_mobile_app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/colin/dev/apps/REDACTED_mobile_app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/colin/dev/apps/REDACTED_mobile_app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:72:in `block (2 levels) in parsing_binding'
	from /Users/colin/dev/apps/REDACTED_mobile_app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:291:in `execute_flow_block'
	from /Users/colin/dev/apps/REDACTED_mobile_app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:46:in `block in execute'
	from /Users/colin/dev/apps/REDACTED_mobile_app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/colin/dev/apps/REDACTED_mobile_app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/colin/dev/apps/REDACTED_mobile_app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/colin/dev/apps/REDACTED_mobile_app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/colin/dev/apps/REDACTEDl_mobile_app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	from /Users/colin/dev/apps/REDACTED_mobile_app/vendor/bundle/ruby/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/colin/dev/apps/REDACTED_mobile_app/vendor/bundle/ruby/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/colin/dev/apps/REDACTED_mobile_app/vendor/bundle/ruby/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/colin/dev/apps/REDACTED_mobile_app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.184.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/colin/dev/apps/REDACTED_mobile_app/vendor/bundle/ruby/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/colin/dev/apps/REDACTED_mobile_app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	from /Users/colin/dev/apps/REDACTED_mobile_app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/colin/dev/apps/REDACTED_mobile_app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /Users/colin/dev/apps/REDACTED_mobile_app/vendor/bundle/ruby/3.0.0/gems/fastlane-2.184.0/bin/fastlane:23:in `<top (required)>'
	from /Users/colin/dev/apps/REDACTED_mobile_app/vendor/bundle/ruby/3.0.0/bin/fastlane:23:in `load'
	from /Users/colin/dev/apps/REDACTED_mobile_app/vendor/bundle/ruby/3.0.0/bin/fastlane:23:in `<top (required)>'
	from /Users/colin/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/cli/exec.rb:63:in `load'
	from /Users/colin/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/cli/exec.rb:63:in `kernel_load'
	from /Users/colin/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/cli/exec.rb:28:in `run'
	from /Users/colin/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/cli.rb:494:in `exec'
	from /Users/colin/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/colin/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/colin/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/colin/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/cli.rb:30:in `dispatch'
	from /Users/colin/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/colin/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/cli.rb:24:in `start'
	from /Users/colin/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/libexec/bundle:49:in `block in <top (required)>'
	from /Users/colin/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	from /Users/colin/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/libexec/bundle:37:in `<top (required)>'
	from /Users/colin/.rbenv/versions/3.0.1/bin/bundle:23:in `load'
	from /Users/colin/.rbenv/versions/3.0.1/bin/bundle:23:in `<main>'

</pre>
</details>

### Environment
<details><pre>     
Environment:
APP_STORE_CONNECT_API_KEY_ISSUER_ID="REDACTED"
APP_STORE_CONNECT_API_KEY_KEY_ID="REDACTED"
APP_STORE_CONNECT_API_KEY_KEY="-----BEGIN PRIVATE KEY-----\\nMIGREDACTED==\\n-----END PRIVATE KEY-----"

app_store_connect_api_key(duration: 1200, in_house: false)
</pre></details>

**Comment by joshkopecek** [comment]
@colin-campbell I can confirm I get the same thing when using Ruby v3.0.1. Ruby 2.7.2 works fine.

**Comment by crazymanish** [comment]
Dear @colin-campbell 

Thank you very much for letting us know, in v2.184 PR #18186 introduced this regression **only applicable for Ruby3.0+**

**I am requesting you** to test this PR https://github.com/fastlane/fastlane/pull/18758, which will fix this issue.
- Update Gemfile and run `bundle install` with
```
gem "fastlane", :git => "git@github.com:crazymanish/fastlane.git", :branch => "app_store_connect_api_key-regression-fix"
```

Thank you!

**Comment by colin-campbell** [comment]
@crazymanish Also managed to confirm today, working with ruby 3. Thank you!
