### ISSUE TITLE
Fastlane shows "Couldn't decrypt the repo, please make sure you enter the right password" but I remember the password.

### ISSUE THREAD

**Issue by aa08666** [fastlane/fastlane#18756]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When i run the "fastlane match development", it show these messages:

Enter the passphrase that should be used to encrypt/decrypt your certificates
This passphrase is specific per repository and will be stored in your local keychain
Make sure to remember the password, as you'll need it when you run match on a different machine

I  type password and then it shows the error "Couldn't decrypt the repo, please make sure you enter the right password!"
Yes, I remember the password, but  it not accepting that password.

I saw issue #12613, now I want to know if it is resolved? thx

**Comment by Ronald8565** [comment]
You could try setting ENV['FASTLANE_PASSWORD'] (Apple Developer Portal password - mymail in your example) in your Fastfile which should make it available to your build.

As a side note: I have the Keychains and Provisioning Profiles Management plugin as well, but didn't need it to get match working. Hope this helps.

**Comment by FrizzyGhost** [comment]
Very helpful and informative. Thank for sharing this post.
