### ISSUE TITLE
[bug] ExportOptionsPlist error for key 'method': expected one of {}, but found app-store

### ISSUE THREAD

**Issue by paulo-coutinho** [fastlane/fastlane#18761]
Hi,

I have this problem when try deploy my app now:

```
[15:46:02]: $ /usr/bin/xcrun /opt/homebrew/Cellar/fastlane/2.184.0/libexec/gems/fastlane-2.184.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/4y/0lvdrkv10fq_4dk8n4nxtmmr0000gn/T/gym_config20210526-75711-lh1eui.plist' -archivePath /Users/ubookmobile/Library/Developer/Xcode/Archives/2021-05-26/App\ 2021-05-26\ 15.45.58.xcarchive -exportPath '/var/folders/4y/0lvdrkv10fq_4dk8n4nxtmmr0000gn/T/gym_output20210526-75711-ee1w8o' 
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/4y/0lvdrkv10fq_4dk8n4nxtmmr0000gn/T/gym_config20210526-75711-lh1eui.plist -archivePath '/Users/ubookmobile/Library/Developer/Xcode/Archives/2021-05-26/App 2021-05-26 15.45.58.xcarchive' -exportPath /var/folders/4y/0lvdrkv10fq_4dk8n4nxtmmr0000gn/T/gym_output20210526-75711-ee1w8o
objc[75743]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1f673d160) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1187002b8). One of the two will be used. Which one is undefined.
objc[75743]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x1f673d1b0) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x118700308). One of the two will be used. Which one is undefined.
2021-05-26 15:46:03.178 xcodebuild[75743:5514047] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/4y/0lvdrkv10fq_4dk8n4nxtmmr0000gn/T/ubook_2021-05-26_15-46-03.178.xcdistributionlogs'.
2021-05-26 15:46:03.192 xcodebuild[75743:5514047] [MT] IDEDistributionMethodManager: -[IDEDistributionMethodManager orderedDistributionMethodsForTask:archive:]: Error = Error Domain=IDEDistributionMethodManagerErrorDomain Code=2 "Unknown Distribution Error" UserInfo={NSLocalizedDescription=Unknown Distribution Error}
error: exportArchive: exportOptionsPlist error for key 'method': expected one of {}, but found app-store

Error Domain=IDEFoundationErrorDomain Code=1 "exportOptionsPlist error for key 'method': expected one of {}, but found app-store" UserInfo={NSLocalizedDescription=exportOptionsPlist error for key 'method': expected one of {}, but found app-store}

** EXPORT FAILED **
[15:46:03]: Exit status: 70

+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.184.0                 |
| export_method | app-store               |
| sdk           | iPhoneOS14.5.sdk        |
+---------------+-------------------------+

[15:46:03]: ▸ sent 134416834 bytes  received 6272 bytes  89615404.00 bytes/sec
[15:46:03]: ▸ total size is 134378069  speedup is 1.00
[15:46:03]: ▸ Copied /Users/ubookmobile/Developer/workspaces/ios/ubook-ios/Pods/ubook/Release/ubook.xcframework/ios-arm64_arm64e_armv7_armv7s to /Users/ubookmobile/Library/Developer/Xcode/DerivedData/Ubook-eydstraulkwyohdjzkkywtxgowfk/Build/Intermediates.noindex/ArchiveIntermediates/ubook/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/ubook
[15:46:03]: ▸ ** ARCHIVE SUCCEEDED **
[15:46:03]: 
[15:46:03]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[15:46:03]: 📋  For the complete and more detailed error log, check the full log at:
[15:46:03]: 📋  /Users/ubookmobile/Library/Logs/gym/App-ubook.log
[15:46:03]: 
[15:46:03]: Looks like fastlane ran into a build/archive error with your project
[15:46:03]: It's hard to tell what's causing the error, so we wrote some guides on how
[15:46:03]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[15:46:03]: Before submitting an issue on GitHub, please follow the guide above and make
[15:46:03]: sure your project is set up correctly.
[15:46:03]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
[15:46:03]: the full commands printed out in yellow in the above log.
[15:46:03]: Make sure to inspect the output above, as usually you'll find more error information there
[15:46:03]: 
+---------------+------------------+
|           Lane Context           |
+---------------+------------------+
| PLATFORM_NAME |                  |
| LANE_NAME     | testflight_ubook |
+---------------+------------------+
[15:46:03]: Error packaging up the application

+------+-----------------------------------+-------------+
|                    fastlane summary                    |
+------+-----------------------------------+-------------+
| Step | Action                            | Time (in s) |
+------+-----------------------------------+-------------+
| 1    | Verifying fastlane version        | 0           |
| 2    | Switch to send_to_testflight lane | 0           |
| 💥   | gym                               | 7           |
+------+-----------------------------------+-------------+

[15:46:03]: fastlane finished with errors

[!] Error packaging up the application
make: *** [deploy-ubook] Error 1
```

- MacOS Big Sur
- Fastlane 2.184.0

Can anyone help me?

Thanks guys.

**Comment by paulo-coutinho** [comment]
Hi, sorry.

Here is:
```
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 11.3.1                                                     |
| Ruby                        | 2.7.3                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.30.1 (Apple Git-130)                         |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.184.0/libexec/bin/fastlane |
| Host                        | macOS 11.3.1 (20E241)                                      |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby@2.7/2.7.3/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                                |
| Is contained                | false                                                      |
| Is homebrew                 | true                                                       |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
| Xcode Version               | 12.5                                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.170.0"

Excon.defaults[:ssl_verify_peer] = false

before_all do
	# before all
end

##############################################################################################
# TESTFLIGHT
##############################################################################################

desc "Prepare evertything to publish to Testflight"
lane :testflight_prepare do
	clean_build_artifacts
	increment_build_number(xcodeproj: "./Ubook.xcodeproj")
end


desc "Download debug symbols from testflight and upload to Firebase Crashlytics"
lane :update_debug_symbols do |options|
	download_dsyms(app_identifier: options[:app_identifier], version: "latest", wait_for_dsym_processing: true)
	upload_symbols_to_crashlytics(gsp_path: "./Ubook/Targets/" + options[:target] + "/GoogleService-Info.plist")
	clean_build_artifacts
end

desc "Execute evertything to an app be published to Testflight"
lane :send_to_testflight do |options|
	gym(
		scheme: options[:scheme],
		clean: true,
		export_options: {
			method: "app-store"
		}
	)	
	
	#ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"
	ENV["FASTLANE_ITC_TEAM_ID"] = "24214800"
	ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = ENV["UBOOK_APPLE_SPECIFIC_PASSWORD"]

	pilot(skip_submission: options[:skip_submission], skip_waiting_for_build_processing: false)				
	update_debug_symbols(
		app_identifier: options[:app_identifier],
		target: options[:target]	
	)
end

desc "Ubook"
lane :testflight_ubook do
	send_to_testflight(
		app_identifier: "br.com.ubook.ubook-app",
		scheme: "ubook",
		skip_submission: true,
		target: "Ubook"
	)	
end

desc "Ureader"
lane :testflight_ureader do
	send_to_testflight(
		app_identifier: "br.com.ubook.ureader",
		scheme: "ureader",
		skip_submission: true,
		target: "Ureader"	
	)
end

desc "Saraiva"
lane :testflight_saraiva do
	send_to_testflight(
		app_identifier: "br.com.ubook.ubook-saraiva",
		scheme: "saraiva",
		skip_submission: true,
		target: "Saraiva"
	)
end

desc "Nextel"
lane :testflight_nextel do
	send_to_testflight(
		app_identifier: "br.com.ubook.ubook-nextel",
		scheme: "nextel",
		skip_submission: true,
		target: "PlayLivros"
	)
end

desc "Livros Narrados"
lane :testflight_livros_narrados do
	send_to_testflight(
		app_identifier: "br.com.ubook.ubook-livros-narrados",
		scheme: "livros-narrados",
		skip_submission: true,
		target: "LivrosNarrados"
	)
end

desc "Augusto Cury Audiolivros"
lane :testflight_augusto_cury_audiolivros do
	send_to_testflight(
		app_identifier: "br.com.ubook.ubook-augusto-cury-audiolivros",
		scheme: "augusto-cury",
		skip_submission: true,
		target: "AugustoCury"
	)
end

desc "Planeta de Libros"
lane :testflight_planeta_de_libros do
	send_to_testflight(
		app_identifier: "com.ubook.reader.planetadelibros",
		scheme: "planeta-de-libros",
		skip_submission: true,
		target: "PlanetaDeLibros"
	)
end

desc "Send all apps to Testflight"
lane :testflight_all do
	testflight_ubook
	testflight_ureader
	testflight_saraiva
	testflight_nextel
	testflight_livros_narrados
	testflight_augusto_cury_audiolivros
	testflight_planeta_de_libros
end

##############################################################################################
# GENERAL
##############################################################################################

lane :refresh_dsyms do
	download_dsyms
	upload_symbols_to_crashlytics
	clean_build_artifacts
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_dev_portal_id ENV["UBOOK_APPLE_DEV_PORTAL_ID"]  # Apple Developer Account
itunes_connect_id ENV["UBOOK_ITUNES_CONNECT_ID"]     # iTunes Connect Account
team_name "Ubook Editora Ltda"
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.184.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.4.0        |
| atomos                          | 0.1.3        |
| CFPropertyList                  | 3.0.3        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.19.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.7.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.81.0       |
| faraday-excon                   | 1.1.0        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.1.0        |
| ruby2_keywords                  | 0.0.4        |
| faraday                         | 1.4.1        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.3        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.0.0        |
| fastimage                       | 2.2.3        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.3.0        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.0        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.15       |
| simctl                          | 1.6.8        |
| jwt                             | 2.2.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.1        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.0        |
| multi_json                      | 1.15.0       |
| signet                          | 0.15.0       |
| memoist                         | 0.16.2       |
| os                              | 1.1.1        |
| googleauth                      | 0.16.2       |
| httpclient                      | 2.8.3        |
| rexml                           | 3.2.3.1      |
| webrick                         | 1.6.1        |
| google-apis-core                | 0.3.0        |
| google-apis-playcustomapp_v1    | 0.2.0        |
| google-apis-androidpublisher_v3 | 0.3.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.3.0        |
| google-apis-storage_v1          | 0.3.0        |
| rake                            | 13.0.3       |
| digest-crc                      | 0.6.3        |
| google-cloud-storage            | 1.31.1       |
| emoji_regex                     | 3.2.2        |
| jmespath                        | 1.4.0        |
| aws-partitions                  | 1.461.0      |
| aws-eventstream                 | 1.1.1        |
| aws-sigv4                       | 1.2.3        |
| aws-sdk-core                    | 3.114.0      |
| aws-sdk-kms                     | 1.43.0       |
| aws-sdk-s3                      | 1.95.0       |
| uri                             | 0.10.0       |
| forwardable                     | 1.3.1        |
| logger                          | 1.4.2        |
| cgi                             | 0.1.0        |
| date                            | 3.0.0        |
| timeout                         | 0.1.0        |
| stringio                        | 0.1.0        |
| zlib                            | 1.1.0        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| ostruct                         | 0.2.0        |
| strscan                         | 1.0.3        |
| io-console                      | 0.5.6        |
| delegate                        | 0.1.0        |
| fileutils                       | 1.4.1        |
| singleton                       | 0.1.0        |
| open3                           | 0.1.0        |
| yaml                            | 0.1.0        |
| psych                           | 3.1.0        |
| mutex_m                         | 0.1.0        |
</details>


*generated on:* **2021-05-27**
</details>
```

**Comment by Garand0** [comment]
Hi, @paulo-coutinho did you figured out what's the problem and maybe you know how to solve it?

**Comment by paulo-coutinho** [comment]
In my case i need add/remove some problematic frameworks and solved
