### ISSUE TITLE
`download_dsyms` fails to use session from spaceauth

### ISSUE THREAD

**Issue by grEvenX** [fastlane/fastlane#18763]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
We are using the `download_dsyms` actions to retrieve dsyms from App Store Connect in our release pipeline, however it fails when it tries to Login to App Store Connect.
We are using a username/password login for an App Store Connect user that has NOT enabled 2FA.
Our pipeline runs with the ENV variable `SPACESHIP_SKIP_2FA_UPGRADE=1` in order to prevent the login to ask about upgrading to 2FA.
If we run the command `fastlane spaceauth`, it logins successfully. Even if we run it right before the `download_dsyms` action, we see that spaceauth succeeds, but `download_dsyms` fail.

##### Command executed
The following command are being run from a lane in our fastlane Fastfile:
`download_dsyms(version: version_number, build_number: build_number, wait_for_dsym_processing: true)`.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
[17:31:36]: ----------------------------
[17:31:36]: --- Step: download_dsyms ---
[17:31:36]: ----------------------------
[17:31:36]: Login to App Store Connect (**redacted***@**redacted**)
+---------------------------+-----------------------------------------------------------+
|                                     Lane Context                                      |
+---------------------------+-----------------------------------------------------------+
 | DEFAULT_PLATFORM          | ios                                                       |
 | PLATFORM_NAME             | ios                                                       |
 | LANE_NAME                 | ios dsyms                                                 |
 | ORIGINAL_DEFAULT_KEYCHAIN | "/Users/devops/Library/Keychains/jenkins_dev.keychain-db" |
 | BUILD_NUMBER              | 2451                                                      |
 | VERSION_NUMBER            | 2.42.0                                                    |
+---------------------------+-----------------------------------------------------------+
 [17:31:55]: Unauthorized Access

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
 | Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
 | 1    | Verifying fastlane version | 0           |
 | 2    | default_platform           | 0           |
 | 3    | setup_jenkins              | 0           |
 | 4    | get_build_number           | 0           |
 | 5    | get_version_number         | 0           |
 | 💥   | download_dsyms             | 19          |
 +------+----------------------------+-------------+

[17:31:55]: fastlane finished with errors
Looking for related GitHub issues on fastlane/fastlane...

 ➡️  match permission denied
    https://github.com/fastlane/fastlane/issues/17810 [closed] 11 💬
   4 weeks ago

 ➡️  Exception type: Spaceship::UnauthorizedAccessError
     https://github.com/fastlane/fastlane/issues/16510 [closed] 35 💬
     17 Sep 2020

 ➡️  fastlane cert got Unauthorized Access error
     https://github.com/fastlane/fastlane/issues/16108 [closed] 62 💬
     18 Jun 2020

 and 20 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09Unauthorized%20Access&type=Issues&utf8=✓

 🔗  You can ⌘ + double-click on links to open them directly in your browser.

[!] The request could not be completed because:
 	Unauthorized Access
</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.3.1                                                         |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.30.1 (Apple Git-130)                             |
| Installation Source         | ~/.gem/bin/fastlane                                            |
| Host                        | macOS 11.3.1 (20E241)                                          |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode12_5.app/Contents/Developer/                |
| Xcode Version               | 12.5                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     |             |   |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.18.1"

default_platform :ios

# Create changelog for TestFligh's "What's New" section
def mw_changelog()
  changelog = read_changelog()
  return changelog
end

# If the path to an App Store Connect API KEY is set, use it for authentication
# This is typically used on the CI
if (ENV["APP_STORE_CONNECT_APIKEY_PATH"])
  app_store_connect_api_key(
    key_id: "**redacted**",
    issuer_id: "**redacted**",
    key_filepath: ENV["APP_STORE_CONNECT_APIKEY_PATH"],
    duration: 1200, # optional
    in_house: false, # optional but may be required if using match/sigh
  )
end

platform :ios do

  lane :dsyms do
    setup_jenkins(force: true, result_bundle: false)

    build_number = get_build_number
    version_number = get_version_number(target: "MyBioAge")

    download_dsyms(version: version_number, build_number: build_number, wait_for_dsym_processing: true)
    upload_symbols_to_crashlytics(
      gsp_path: "MyBioAge/Application/Firebase/Dev/GoogleService-Info.plist",
      platform: "ios"
    )
  end

  # This lane can be used to get latest build number sent to testflight for a given
  # release version, and bumps it with +1.
  private_lane :mw_increment_build_number do
    if (ENV["TESTFLIGHT_BUILD_NUMBER"])
      new_build_number = ENV["TESTFLIGHT_BUILD_NUMBER"]
    else
      UI.user_error!("TESTFLIGHT_BUILD_NUMBER env variable needs to be specified")
    end
    increment_build_number(build_number: new_build_number)
  end

  ########################## POST LANES ###########################
  after_all do |lane|
    
  end
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "**redacted**" # The bundle identifier of your app
apple_id "**redacted**@**redacted**" # Your Apple email address

team_id "**redacted**"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.184.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-badge     | 1.5.0   | ✅ Up-To-Date  |
| fastlane-plugin-changelog | 0.16.0  | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| bundler                         | 1.17.2       |
| etc                             | 1.0.1        |
| forwardable                     | 1.2.0        |
| rake                            | 13.0.3       |
| CFPropertyList                  | 3.0.3        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.7.0        |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.1.1        |
| aws-partitions                  | 1.463.0      |
| aws-sigv4                       | 1.2.3        |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.114.0      |
| aws-sdk-kms                     | 1.43.0       |
| aws-sdk-s3                      | 1.95.1       |
| babosa                          | 1.0.4        |
| fastimage                       | 2.2.3        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.2        |
| excon                           | 0.81.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.1.0        |
| multipart-post                  | 2.0.0        |
| ruby2_keywords                  | 0.0.4        |
| faraday                         | 1.4.2        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.3        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.0.0        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.2.3        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| signet                          | 0.15.0       |
| googleauth                      | 0.16.2       |
| httpclient                      | 2.8.3        |
| mini_mime                       | 1.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.1        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| rexml                           | 3.2.5        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.3.0        |
| google-apis-androidpublisher_v3 | 0.4.0        |
| google-apis-playcustomapp_v1    | 0.3.0        |
| digest-crc                      | 0.6.3        |
| google-apis-iamcredentials_v1   | 0.4.0        |
| google-apis-storage_v1          | 0.4.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.31.1       |
| json                            | 2.5.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.0        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.19.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| badge                           | 0.13.0       |
| fastlane-plugin-badge           | 1.5.0        |
| fastlane-plugin-changelog       | 0.16.0       |
</details>

*generated on:* **2021-05-27**
</details>

**Comment by max-ott** [comment]
It's no longer possible to NOT have 2FA enabled for your account. `SPACESHIP_SKIP_2FA_UPGRADE=1` is no longer needed/working. Please upgrade your Apple ID to use 2FA and then copy over the session.

`Unauthorized Access` --> Shows that you are not actually logged in.

**Comment by Elgranchorla** [comment]
I'm using 2FA and have the same issue just after introducing the 6 digit code.
