### ISSUE TITLE
Pilot does not show installed versions at all for specific app

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1876]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/4519870?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @appcoders - Imported from <a href='https://github.com/fastlane/pilot/issues/150'>fastlane/pilot#150</a>
        </td>
      </tr>
    </table>

This is the iTunes Connect state:

https://www.dropbox.com/s/4i7saiv85qhztse/itunesconnect.png?dl=0

This is what pilot gives me for this app (all users are there):

https://www.dropbox.com/s/d2nun5q7totc11l/pilot_console.png?dl=0

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (404/400 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o3.sgmail.github.com ([192.254.112.98]:9084)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1bEKqa-002kYb-Vu
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:20:02 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=jWYPI6AVkPH7jVDFT8KKFeqsEl0=; b=V5AeNogWv4cQ+Er+
	pQ16/y+OpabCYaIWF1M910ovxNZN/CHStiGezqOGSBfOVk3vQdv6A4IkVFxBtCGR
	Oa90xa+Q7/h9VySfaPUM2WPg6jUrCAoUDGGNbnR4gj6BIE5VvrFeJQ8ZH1+ZB4e/
	42F8lZpEU+BRxeSSaYUtNVSHzA4=
Received: by filter0824p1mdw1.sendgrid.net with SMTP id filter0824p1mdw1.17835.576590A0F
        2016-06-18 18:19:12.122480474 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id xC-m7oeoQyKWRd6YbJc-gQ
	for <yann.dupuy@zyapps.com>; Sat, 18 Jun 2016 18:19:12.203 +0000 (UTC)
Date: Sat, 18 Jun 2016 11:19:12 -0700

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (403/400 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:46065)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1bEKqa-002kYh-I3
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:20:01 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=X34jZjKmEFKfA06oBuTy7u+IS6Y=; b=XIBiS6TgcZ4DzU7W
	W6Gb1CfD9XdeaKp9jUcoLql5z5G77hALgrTehea57cBGqZ/VpcvcMQ9tlnQTG9xf
	Z5Hq44PZw78z6WDha2V/cbGb4ESPOavV5aNvN+k0+6LA4odNmdomp9hIu7v/b/4I
	uqPxqQ6Z5pBJFJUj6zOlXQ9g694=
Received: by filter0526p1mdw1.sendgrid.net with SMTP id filter0526p1mdw1.29752.576590A05
        2016-06-18 18:19:12.040618509 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0006p1iad1.sendgrid.net (SG) with ESMTP id Jll1-zzTRS2xIcCoqypKnQ
	for <yann.dupuy@zyapps.com>; Sat, 18 Jun 2016 18:19:12.023 +0000 (UTC)
Date: Sat, 18 Jun 2016 11:19:11 -0700
