### ISSUE TITLE
Update docs about new "contests and gambling" age rating config

### ISSUE THREAD

**Issue by TheWirv** [fastlane/fastlane#18779]
Hi, I just ran into an error because my age rating JSON was not configured correctly. To find out the correct format (I ran into another crash because I just split up `contestsAndGambling` `boolean` into to other `boolean`s, although it requires a `string` key), I had to dig into the code base to find this recent commit: https://github.com/fastlane/fastlane/commit/90062c97e93e2a79c78bea7904ff1af6d78faa4e
I'm fine now, but please update https://docs.fastlane.tools/actions/deliver/ with info about the new proper age rating config. It would also make sense to update [the example config](https://github.com/fastlane/fastlane/blob/master/deliver/assets/example_rating_config.json) while being at it.

**Comment by Treeane** [comment]
> Hi, I just ran into an error because my age rating JSON was not configured correctly. To find out the correct format (I ran into another crash because I just split up `contestsAndGambling` `boolean` into to other `boolean`s, although it requires a `string` key), I had to dig into the code base to find this recent commit: [www.myloweslife.com](https://www.myloweslife.life/)
> I'm fine now, but please update https://docs.fastlane.tools/actions/deliver/ with info about the new proper age rating config. It would also make sense to update 
Hi, I just ran into an error because my age rating JSON was not configured correctly  Update docs about new "contests and gambling" age rating config .
