### ISSUE TITLE
TEAM_ID selection on environment variable not working

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1877]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/3224197?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @pabloromeu - Imported from <a href='https://github.com/fastlane/pilot/issues/143'>fastlane/pilot#143</a>
        </td>
      </tr>
    </table>

I am working using an iTunes User with several teams. I setup the environment variable for the team id and it does not select it automatically

     ITUNESCONNECT_TEAM_ID           = "333" 
     ENV["PILOT_TEAM_ID"]              = ITUNESCONNECT_TEAM_ID

But it does not work:

     [13:30:03]: Login to iTunes Connect (whatever@ever.es)
     Multiple iTunes Connect teams found, please enter the number of the team you want to use: 
     1) "First" (111)
     2) "Second" (222)
     3) "Third" (333)

Pilot version is 1.3.0

**Comment by andreif** [comment]
According to https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/tunes/tunes_client.rb#L78-93 the env var names should be `FASTLANE_ITC_TEAM_ID` and `FASTLANE_ITC_TEAM_NAME`

**Comment by pabloromeu** [comment]
`pilot -h´ say:

`    -q, --team_id [VALUE] The ID of your team if you're in multiple teams (PILOT_TEAM_ID) `

**Comment by TKBurner** [comment]
@pabloromeu Hope you are doing well! Can you let me know if setting them as ENV using 

FASTLANE_ITC_TEAM_ID and FASTLANE_ITC_TEAM_NAME

works in your setup? Thanks!

**Comment by pabloromeu** [comment]
Yes! It does the trick @TKBurner ! 

IMHO If FASTLANE_ITC_TEAM_ID/FASTLANE_ITC_TEAM_NAME should be set instead of PILOT_TEAM_ID/PILOT_TEAM_NAME I think it should be stated at help.

**Comment by TKBurner** [comment]
Thanks @pabloromeu! Really glad to hear you got up and running. I'm going to mark this as a doc todo so we can address it in our documentation. Hope that you have a wonderful day!

**Comment by Lutzifer** [comment]
this should be stated in the output of "fastlane action pilot" also.
