### ISSUE TITLE
Create App Online Bundle id is not available

### ISSUE THREAD

**Issue by gelodgreat** [fastlane/fastlane#18789]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Create App Online Bundle id is not available on specific teams, it works on other teams also i did try changing the app_identifier still its not creating, Is it possible that this is an account issue?

<details>
  <pre> Create App Online Bundle id is not available </pre>
</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 11.4                                                    |
| Ruby                        | 2.7.3                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.29.2                                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.181.0/libexec/bin/fastlane |
| Host                        | macOS 11.4 (20F71)                                      |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.7/2.7.3/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                             |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 12.5                                                    |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane



# fastlane_require "dotenv"

before_all do 

default_platform(:ios)

platform :ios do
    lane :prepare do
      create_app_online(
	    app_identifier: ENV['APP_IDENTIFIER'] ,
        app_name: ENV['APP_NAME'],
        enable_services: {
          push_notification: "on",
          app_group: "on"
        }    
      )
      produce(
          app_identifier: ENV['NotificationServiceBundleID'] ,
          app_name: ENV['NotificationServiceAppName'],
          sku: ENV['SKU'],
          skip_itc: true,
          enable_services: {
            push_notification: "on",
            app_group: "on"
          }
      )

    end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.181.0 | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status      |
| -------------------------- | ------- | ------------------ |
| fastlane-plugin-appicon    | 0.16.0  | ✅ Up-To-Date       |
| fastlane-plugin-versioning | 0.4.4   | 🚫 Update available |
| fastlane-plugin-sentry     | 1.8.1   | ✅ Up-To-Date       |

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.4.0        |
| slack-notifier                | 2.3.2        |
| atomos                        | 0.1.3        |
| CFPropertyList                | 3.0.3        |
| claide                        | 1.0.3        |
| colored2                      | 3.1.2        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| plist                         | 3.6.0        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| multipart-post                | 2.0.0        |
| word_wrap                     | 1.0.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| artifactory                   | 3.0.15       |
| babosa                        | 1.0.4        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| excon                         | 0.80.1       |
| faraday-excon                 | 1.1.0        |
| faraday-net_http              | 1.0.1        |
| faraday-net_http_persistent   | 1.1.0        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.4.1        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.3        |
| gh_inspector                  | 1.1.3        |
| json                          | 2.3.0        |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| xcpretty-travis-formatter     | 1.0.1        |
| dotenv                        | 2.7.6        |
| bundler                       | 2.2.15       |
| simctl                        | 1.6.8        |
| jwt                           | 2.2.3        |
| uber                          | 0.1.0        |
| declarative                   | 0.0.20       |
| trailblazer-option            | 0.1.1        |
| representable                 | 3.1.1        |
| retriable                     | 3.1.2        |
| mini_mime                     | 1.1.0        |
| multi_json                    | 1.15.0       |
| signet                        | 0.15.0       |
| memoist                       | 0.16.2       |
| os                            | 1.1.1        |
| googleauth                    | 0.16.1       |
| httpclient                    | 2.8.3        |
| google-api-client             | 0.38.0       |
| google-cloud-env              | 1.5.0        |
| google-cloud-errors           | 1.1.0        |
| google-cloud-core             | 1.6.0        |
| rexml                         | 3.2.3.1      |
| webrick                       | 1.6.1        |
| google-apis-core              | 0.3.0        |
| google-apis-iamcredentials_v1 | 0.3.0        |
| google-apis-storage_v1        | 0.3.0        |
| rake                          | 13.0.3       |
| digest-crc                    | 0.6.3        |
| google-cloud-storage          | 1.31.0       |
| emoji_regex                   | 3.2.2        |
| jmespath                      | 1.4.0        |
| aws-partitions                | 1.446.0      |
| aws-eventstream               | 1.1.1        |
| aws-sigv4                     | 1.2.3        |
| aws-sdk-core                  | 3.114.0      |
| aws-sdk-kms                   | 1.43.0       |
| aws-sdk-s3                    | 1.93.1       |
| uri                           | 0.10.0       |
| forwardable                   | 1.3.1        |
| logger                        | 1.4.2        |
| cgi                           | 0.1.0        |
| date                          | 3.0.0        |
| timeout                       | 0.1.0        |
| stringio                      | 0.1.0        |
| zlib                          | 1.1.0        |
| ipaddr                        | 1.2.2        |
| openssl                       | 2.1.2        |
| ostruct                       | 0.2.0        |
| strscan                       | 1.0.3        |
| delegate                      | 0.1.0        |
| fileutils                     | 1.4.1        |
| io-console                    | 0.5.6        |
| singleton                     | 0.1.0        |
| open3                         | 0.1.0        |
| yaml                          | 0.1.0        |
| psych                         | 3.1.0        |
| mutex_m                       | 0.1.0        |
| fastlane-plugin-appicon       | 0.16.0       |
| benchmark                     | 0.1.0        |
| fastlane-plugin-versioning    | 0.4.4        |
| fastlane-plugin-sentry        | 1.8.1        |
</details>

*generated on:* **2021-06-02**
</details>

**Comment by lucgrabowski** [comment]
Hi, 
If it's a problem with creating Bundle ids, you should go to Appstore Connect - Users and Access - select your account and scroll down to "developer resources" and check if you have "Access to Certificates, Identifiers & Profiles" selected.
If you have it selected in those teams, it will be hard to help without `fastlane env` output and a more detailed description of the issue.

**Comment by gelodgreat** [comment]
> Hi,
> If it's a problem with creating Bundle ids, you should go to Appstore Connect - Users and Access - select your account and scroll down to "developer resources" and check if you have "Access to Certificates, Identifiers & Profiles" selected.
> If you have it selected in those teams, it will be hard to help without `fastlane env` output and a more detailed description of the issue.

Hi @lucgrabowski , Thank you will provide fastlane env. This is weird because its working on other teams just specific account.

**Comment by gelodgreat** [comment]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 11.4                                                    |
| Ruby                        | 2.7.3                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.29.2                                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.181.0/libexec/bin/fastlane |
| Host                        | macOS 11.4 (20F71)                                      |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.7/2.7.3/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                             |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 12.5                                                    |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane



# fastlane_require "dotenv"

before_all do 

default_platform(:ios)

platform :ios do
    lane :prepare do
      create_app_online(
        enable_services: {
          push_notification: "on",
          app_group: "on"
        }    
      )

    end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.181.0 | 🚫 Update available |


### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status      |
| -------------------------- | ------- | ------------------ |
| fastlane-plugin-appicon    | 0.16.0  | ✅ Up-To-Date       |
| fastlane-plugin-versioning | 0.4.4   | 🚫 Update available |
| fastlane-plugin-sentry     | 1.8.1   | ✅ Up-To-Date       |


<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.4.0        |
| slack-notifier                | 2.3.2        |
| atomos                        | 0.1.3        |
| CFPropertyList                | 3.0.3        |
| claide                        | 1.0.3        |
| colored2                      | 3.1.2        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| plist                         | 3.6.0        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| multipart-post                | 2.0.0        |
| word_wrap                     | 1.0.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| artifactory                   | 3.0.15       |
| babosa                        | 1.0.4        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| excon                         | 0.80.1       |
| faraday-excon                 | 1.1.0        |
| faraday-net_http              | 1.0.1        |
| faraday-net_http_persistent   | 1.1.0        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.4.1        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.3        |
| gh_inspector                  | 1.1.3        |
| json                          | 2.3.0        |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| xcpretty-travis-formatter     | 1.0.1        |
| dotenv                        | 2.7.6        |
| bundler                       | 2.2.15       |
| simctl                        | 1.6.8        |
| jwt                           | 2.2.3        |
| uber                          | 0.1.0        |
| declarative                   | 0.0.20       |
| trailblazer-option            | 0.1.1        |
| representable                 | 3.1.1        |
| retriable                     | 3.1.2        |
| mini_mime                     | 1.1.0        |
| multi_json                    | 1.15.0       |
| signet                        | 0.15.0       |
| memoist                       | 0.16.2       |
| os                            | 1.1.1        |
| googleauth                    | 0.16.1       |
| httpclient                    | 2.8.3        |
| google-api-client             | 0.38.0       |
| google-cloud-env              | 1.5.0        |
| google-cloud-errors           | 1.1.0        |
| google-cloud-core             | 1.6.0        |
| rexml                         | 3.2.3.1      |
| webrick                       | 1.6.1        |
| google-apis-core              | 0.3.0        |
| google-apis-iamcredentials_v1 | 0.3.0        |
| google-apis-storage_v1        | 0.3.0        |
| rake                          | 13.0.3       |
| digest-crc                    | 0.6.3        |
| google-cloud-storage          | 1.31.0       |
| emoji_regex                   | 3.2.2        |
| jmespath                      | 1.4.0        |
| aws-partitions                | 1.446.0      |
| aws-eventstream               | 1.1.1        |
| aws-sigv4                     | 1.2.3        |
| aws-sdk-core                  | 3.114.0      |
| aws-sdk-kms                   | 1.43.0       |
| aws-sdk-s3                    | 1.93.1       |
| uri                           | 0.10.0       |
| forwardable                   | 1.3.1        |
| logger                        | 1.4.2        |
| cgi                           | 0.1.0        |
| date                          | 3.0.0        |
| timeout                       | 0.1.0        |
| stringio                      | 0.1.0        |
| zlib                          | 1.1.0        |
| ipaddr                        | 1.2.2        |
| openssl                       | 2.1.2        |
| ostruct                       | 0.2.0        |
| strscan                       | 1.0.3        |
| delegate                      | 0.1.0        |
| fileutils                     | 1.4.1        |
| io-console                    | 0.5.6        |
| singleton                     | 0.1.0        |
| open3                         | 0.1.0        |
| yaml                          | 0.1.0        |
| psych                         | 3.1.0        |
| mutex_m                       | 0.1.0        |
| fastlane-plugin-appicon       | 0.16.0       |
| benchmark                     | 0.1.0        |
| fastlane-plugin-versioning    | 0.4.4        |
| fastlane-plugin-sentry        | 1.8.1        |
</details>


*generated on:* **2021-06-02**
</details>

**Comment by lucgrabowski** [comment]
Could you login to Appstore Connect to the team that it's failing and go to A Users and Access - select your tester account and scroll down to "developer resources" and check if you have "Access to Certificates, Identifiers & Profiles" selected? 
If access to developer resources is there and it's not working, it would be good if you describe what fastlane's commands do you try to execute and show some logs.

**Comment by gelodgreat** [comment]
@lucgrabowski , this is the output on bitrise and bitrise locally, it works on other teams that i've deployed, but this one is specific this account is nearing its expiration and it might be the cause

![image](https://user-images.githubusercontent.com/20021423/120485429-a7cc2380-c3e6-11eb-8bae-b27da27a85ab.png)

**Comment by gelodgreat** [comment]
@lucgrabowski , yes i have access on everything, my role was admin

![image](https://user-images.githubusercontent.com/20021423/120485616-dc3fdf80-c3e6-11eb-8373-c474d4e1e917.png)

**Comment by shamikagasc** [comment]
We are also facing the same issue

**Comment by lucgrabowski** [comment]
I don't use Bitrise and I don't have any ideas without taking a look at configuration and logs. It would be best if you could paste verbose logs.

**Comment by lucgrabowski** [comment]
Do you try to create an app with bundle identifier that is used on another developer account? If you created an identifier in Team1, you won't be able to create it in Team2.

**Comment by Anthonyby526** [comment]
Hello,
thanks for sharing your concern.
Please update your bundle ID in XCode to match the bundle ID of the push certificate you uploaded, or upload a new .p12 push certificate file that matches your XCode bundle ID.

**Comment by gelodgreat** [comment]
@lucgrabowski , i've tested multiple bundle ids and even random ones just to simulate that, and its really happening on just one dev account, i've managed multiple teams and this is just isolated case on 1 account, i'm assuming that its account related and its near expiring, can that be a possible root cause?

**Comment by gelodgreat** [comment]
> Do you try to create an app with bundle identifier that is used on another developer account? If you created an identifier in Team1, you won't be able to create it in Team2.

@lucgrabowski , i've tested multiple bundle ids and even random ones just to simulate that, and its really happening on just one dev account, i've managed multiple teams and this is just isolated case on 1 account, i'm assuming that its account related and its near expiring, can that be a possible root cause?

**Comment by gelodgreat** [comment]
> Hello,
> thanks for sharing your concern.
> Please update your bundle ID in XCode to match the bundle ID of the push certificate you uploaded, or upload a new .p12 push certificate file that matches your XCode bundle ID.

@Anthonyby526 , i've already setup automation for that, it's not the issue. Thank you :)

**Comment by Anthonyby526** [comment]
> > Hello,
> > thanks for sharing your concern.
> > Please update your bundle ID in XCode to match the bundle ID of the push certificate you uploaded, or upload a new .p12 push certificate file that matches your XCode bundle ID.
> 
> @Anthonyby526 , i've already setup automation for that, it's not the issue. Because its working on other teams that i manage. Thank you :)

ok thank you for update.

**Comment by max-ott** [comment]
How do you login/authenticate? Via Apple ID or App Store Connect API key?

**Comment by gelodgreat** [comment]
@max-ott , I'm using bitrise for that, also the build is successful on multiple other teams that I've deployed. this is isolated on just 1 team that I managed.

**Comment by gelodgreat** [comment]
This issue has been resolved, So once the apple membership is expiring it would always fail to upload then once you renew your membership the team id also changes. Thank you everyone!
