### ISSUE TITLE
increment_build_number xcodeproj not found

### ISSUE THREAD

**Issue by OlivierEdoki** [fastlane/fastlane#18783]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
In my root project directory, I have
fastlane/Fastfile
Build/Apple/Unity-iPhone.xcodeproject

My fastfile looks like this
platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :upload_testflight do
      increment_build_number(
        build_number: ENV['BUILD_NUMBER'],
        xcodeproj: "./Build/APPLE/Unity-iPhone.xcodeproj"
        )
      build_app(scheme: "Unity-iPhone")
      upload_to_testflight(
        changelog: "Automated build for Release 3.9 using fastlane",
        api_key_path: "./fastlane/api_key.json",
        skip_waiting_for_build_processing: true
      )
  end
end

##### Command executed
From the root project directory: fastlane upload_testflight

##### Complete output when running fastlane, including the stack trace and command used
[✔] 🚀 
[17:10:50]: fastlane detected a Gemfile in the current directory
[17:10:50]: However, it seems like you didn't use `bundle exec`
[17:10:50]: To launch fastlane faster, please use
[17:10:50]: 
[17:10:50]: $ bundle exec fastlane upload_testflight --verbose
[17:10:50]: 
[17:10:50]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2021-05-31 17:10:51.04]: Checking if there are any plugins that should be loaded...
Successfully loaded Appfile at path '/Users/user/Documents/GitHub/Project/fastlane/Appfile'
- app_identifier: 'com.test.test'
- apple_id: 'user@edokiacademy.com'
- itc_team_id: 'XXXXXX'
- team_id: 'XXXXXXXXXX'
-------
INFO [2021-05-31 17:10:51.22]: ------------------------------
INFO [2021-05-31 17:10:51.22]: --- Step: default_platform ---
INFO [2021-05-31 17:10:51.22]: ------------------------------
INFO [2021-05-31 17:10:51.22]: Driving the lane 'ios upload_testflight' 🚀
INFO [2021-05-31 17:10:51.23]: ---------------------------------
INFO [2021-05-31 17:10:51.23]: --- Step: update_project_team ---
INFO [2021-05-31 17:10:51.23]: ---------------------------------
INFO [2021-05-31 17:10:51.38]: Updating development team (XXXXXXXXXX) for target `Unity-iPhone` in the project 'Build/APPLE/Unity-iPhone.xcodeproj'
INFO [2021-05-31 17:10:51.48]: Successfully updated project settings to use Developer Team ID 'XXXXXXXXXX' for target `Unity-iPhone`
INFO [2021-05-31 17:10:51.48]: Updating development team (XXXXXXXXXX) for target `Unity-iPhone Tests` in the project 'Build/APPLE/Unity-iPhone.xcodeproj'
INFO [2021-05-31 17:10:51.61]: Successfully updated project settings to use Developer Team ID 'XXXXXXXXXX' for target `Unity-iPhone Tests`
INFO [2021-05-31 17:10:51.61]: Updating development team (XXXXXXXXXX) for target `UnityFramework` in the project 'Build/APPLE/Unity-iPhone.xcodeproj'
INFO [2021-05-31 17:10:51.70]: Successfully updated project settings to use Developer Team ID 'XXXXXXXXXX' for target `UnityFramework`
INFO [2021-05-31 17:10:51.70]: Updating development team (XXXXXXXXXX) for target `Unity-iPhone-Stickers` in the project 'Build/APPLE/Unity-iPhone.xcodeproj'
INFO [2021-05-31 17:10:51.79]: Successfully updated project settings to use Developer Team ID 'XXXXXXXXXX' for target `Unity-iPhone-Stickers`
INFO [2021-05-31 17:10:51.79]: ------------------------------------
INFO [2021-05-31 17:10:51.79]: --- Step: increment_build_number ---
INFO [2021-05-31 17:10:51.79]: ------------------------------------
Current version of project Unity-iPhone is: 
    2133

/Users/user/Documents/GitHub/Project
INFO [2021-05-31 17:10:52.28]: $ cd /Users/user/Documents/GitHub/Project/Build/APPLE && agvtool new-version -all 2133 && cd -
INFO [2021-05-31 17:10:52.66]: ▸ Setting version of project Unity-iPhone to:
INFO [2021-05-31 17:10:52.66]: ▸ 2133.
INFO [2021-05-31 17:10:52.70]: ▸ Also setting CFBundleVersion key (assuming it exists)
INFO [2021-05-31 17:10:52.74]: ▸ Updating CFBundleVersion in Info.plist(s)...
INFO [2021-05-31 17:10:52.76]: ▸ Updated CFBundleVersion in "Unity-iPhone.xcodeproj/../Info.plist" to 2133
INFO [2021-05-31 17:10:52.77]: ▸ Updated CFBundleVersion in "Unity-iPhone.xcodeproj/../Unity-iPhone Tests/Unity-iPhone Tests-Info.plist" to 2133
INFO [2021-05-31 17:10:52.79]: ▸ Updated CFBundleVersion in "Unity-iPhone.xcodeproj/../Unity-iPhone-Stickers/Info.plist" to 2133
INFO [2021-05-31 17:10:52.80]: ▸ Updated CFBundleVersion in "Unity-iPhone.xcodeproj/../UnityFramework/Info.plist" to 2133
INFO [2021-05-31 17:10:52.80]: ▸ /Users/user/Documents/GitHub/Project
INFO [2021-05-31 17:10:52.82]: -----------------------
INFO [2021-05-31 17:10:52.82]: --- Step: build_app ---
INFO [2021-05-31 17:10:52.82]: -----------------------
 [2021-05-31 17:10:52.82]: Couldn't automatically detect the project file, please provide a path: ^CWARN [2021-05-31 17:11:02.97]: Lane Context:
INFO [2021-05-31 17:11:02.97]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios upload_testflight", :BUILD_NUMBER=>"2133"}
INFO [2021-05-31 17:11:02.97]: Successfully generated documentation at path '/Users/user/Documents/GitHub/Project/fastlane/README.md'

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | default_platform       | 0           |
| 2    | update_project_team    | 0           |
| 3    | increment_build_number | 1           |
| 4    | build_app              | 10          |
+------+------------------------+-------------+

ERROR [2021-05-31 17:11:02.98]: fastlane finished with errors
Traceback (most recent call last):
	46: from /usr/local/Cellar/fastlane/2.184.1/libexec/bin/fastlane:23:in `<main>'
	45: from /usr/local/Cellar/fastlane/2.184.1/libexec/bin/fastlane:23:in `load'
	44: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/fastlane-2.184.1/bin/fastlane:23:in `<top (required)>'
	43: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/fastlane-2.184.1/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	42: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/fastlane-2.184.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	41: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/fastlane-2.184.1/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	40: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	39: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/fastlane-2.184.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	38: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	37: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	36: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	35: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/fastlane-2.184.1/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	34: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/fastlane-2.184.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	33: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/fastlane-2.184.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	32: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/fastlane-2.184.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	31: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/fastlane-2.184.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	30: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/fastlane-2.184.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	29: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/fastlane-2.184.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	28: from Fastfile:55:in `block (2 levels) in parsing_binding'
	27: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/fastlane-2.184.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	26: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/fastlane-2.184.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	25: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/fastlane-2.184.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	24: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/fastlane-2.184.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	23: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/fastlane-2.184.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	22: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/fastlane-2.184.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	21: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/fastlane-2.184.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	20: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/fastlane-2.184.1/fastlane/lib/fastlane/actions/build_app.rb:68:in `run'
	19: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/fastlane-2.184.1/gym/lib/gym/manager.rb:8:in `work'
	18: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/fastlane-2.184.1/gym/lib/gym/module.rb:15:in `config='
	17: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/fastlane-2.184.1/gym/lib/gym/detect_values.rb:18:in `set_additional_default_values'
	16: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/fastlane-2.184.1/fastlane_core/lib/fastlane_core/project.rb:41:in `detect_projects'
	15: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/fastlane-2.184.1/fastlane_core/lib/fastlane_core/project.rb:46:in `select_project'
	14: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/fastlane-2.184.1/fastlane_core/lib/fastlane_core/project.rb:46:in `loop'
	13: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/fastlane-2.184.1/fastlane_core/lib/fastlane_core/project.rb:47:in `block in select_project'
	12: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/fastlane-2.184.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	11: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/fastlane-2.184.1/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:130:in `input'
	10: from /usr/local/Cellar/ruby@2.7/2.7.3/lib/ruby/2.7.0/forwardable.rb:235:in `ask'
	 9: from /usr/local/Cellar/ruby@2.7/2.7.3/lib/ruby/2.7.0/forwardable.rb:235:in `ask'
	 8: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/highline-2.0.3/lib/highline.rb:223:in `ask'
	 7: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/highline-2.0.3/lib/highline/question_asker.rb:30:in `ask_once'
	 6: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/highline-2.0.3/lib/highline/question.rb:536:in `get_response_or_default'
	 5: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/highline-2.0.3/lib/highline/question.rb:524:in `get_response'
	 4: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/highline-2.0.3/lib/highline.rb:516:in `get_response_line_mode'
	 3: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/highline-2.0.3/lib/highline.rb:532:in `get_line'
	 2: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/highline-2.0.3/lib/highline/terminal.rb:89:in `get_line'
	 1: from /usr/local/Cellar/fastlane/2.184.1/libexec/gems/highline-2.0.3/lib/highline/terminal.rb:138:in `get_line_default'
/usr/local/Cellar/fastlane/2.184.1/libexec/gems/highline-2.0.3/lib/highline/terminal.rb:138:in `gets': Interrupt

**Comment by OlivierEdoki** [comment]
fastlane.env content

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 11.4                                                    |
| Ruby                        | 2.7.3                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.31.1                                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.184.1/libexec/bin/fastlane |
| Host                        | macOS 11.4 (20F71)                                      |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.7/2.7.3/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                             |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode_12.4.app/Contents/Developer/        |
| Xcode Version               | 12.4                                                    |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
require 'uri'
require 'net/http'

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

XCODE_PROJECT = "./Build/APPLE/Unity-iPhone.xcodeproj"

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :upload_testflight do
    # puts "FOLDER1 " + Dir.pwd
    # Dir.chdir("..") do
      # puts "FOLDER2 " + Dir.pwd

      # uri = URI('https://api.edokiacademy.com/api/editor/BuildCode')
      # res = Net::HTTP.get_response(uri)
      # ENV['BUILD_NUMBER'] =  res.body if res.is_a?(Net::HTTPSuccess)

      # print "New build version number: " + ENV['BUILD_NUMBER']

      update_project_team(
        path: "Build/APPLE/Unity-iPhone.xcodeproj",
        teamid: "XXXXXXXXX"
      )

      increment_build_number(
        build_number: 2133, #ENV['BUILD_NUMBER'],
        xcodeproj: "Build/APPLE/Unity-iPhone.xcodeproj"
        )
      build_app(scheme: "Unity-iPhone")
      upload_to_testflight(
        changelog: "Automated build for Release 3.9 using fastlane\nCommit fb3d815 (add keyboard sound effect)",
        api_key_path: "./fastlane/api_key.json",
        skip_waiting_for_build_processing: true
      )
    # end
  end
end


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

XXXXXXXXXXXXXXXXXXXXX

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.184.1 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.4.0        |
| atomos                          | 0.1.3        |
| CFPropertyList                  | 3.0.3        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.19.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.7.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.82.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.1.0        |
| ruby2_keywords                  | 0.0.4        |
| faraday                         | 1.4.2        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.3        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.0.0        |
| fastimage                       | 2.2.3        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.3.0        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.0        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.15       |
| simctl                          | 1.6.8        |
| jwt                             | 2.2.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.1        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.0        |
| multi_json                      | 1.15.0       |
| signet                          | 0.15.0       |
| memoist                         | 0.16.2       |
| os                              | 1.1.1        |
| googleauth                      | 0.16.2       |
| httpclient                      | 2.8.3        |
| rexml                           | 3.2.3.1      |
| webrick                         | 1.6.1        |
| google-apis-core                | 0.3.0        |
| google-apis-playcustomapp_v1    | 0.3.0        |
| google-apis-androidpublisher_v3 | 0.4.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.4.0        |
| google-apis-storage_v1          | 0.4.0        |
| rake                            | 13.0.3       |
| digest-crc                      | 0.6.3        |
| google-cloud-storage            | 1.31.1       |
| emoji_regex                     | 3.2.2        |
| jmespath                        | 1.4.0        |
| aws-partitions                  | 1.465.0      |
| aws-eventstream                 | 1.1.1        |
| aws-sigv4                       | 1.2.3        |
| aws-sdk-core                    | 3.114.0      |
| aws-sdk-kms                     | 1.43.0       |
| aws-sdk-s3                      | 1.95.1       |
| uri                             | 0.10.0       |
| forwardable                     | 1.3.1        |
| logger                          | 1.4.2        |
| cgi                             | 0.1.0        |
| date                            | 3.0.0        |
| timeout                         | 0.1.0        |
| stringio                        | 0.1.0        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.1.0        |
| ostruct                         | 0.2.0        |
| strscan                         | 1.0.3        |
| io-console                      | 0.5.6        |
| delegate                        | 0.1.0        |
| fileutils                       | 1.4.1        |
| singleton                       | 0.1.0        |
| open3                           | 0.1.0        |
| yaml                            | 0.1.0        |
| psych                           | 3.1.0        |
| mutex_m                         | 0.1.0        |
</details>


*generated on:* **2021-05-31**
</details>

**Comment by OlivierEdoki** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 11.4                                                    |
| Ruby                        | 2.7.3                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.31.1                                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.184.1/libexec/bin/fastlane |
| Host                        | macOS 11.4 (20F71)                                      |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.7/2.7.3/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                             |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode_12.4.app/Contents/Developer/        |
| Xcode Version               | 12.4                                                    |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
require 'uri'
require 'net/http'

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

XCODE_PROJECT = "./Build/APPLE/Unity-iPhone.xcodeproj"

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :upload_testflight do
      increment_build_number(
        build_number: ENV['BUILD_NUMBER'],
        xcodeproj: "Build/APPLE/Unity-iPhone.xcodeproj"
        )
      build_app(scheme: "Unity-iPhone")
      upload_to_testflight(
        changelog: "Automated build for Release 3.9 using fastlane\nCommit fb3d815 (add keyboard sound effect)",
        api_key_path: "./fastlane/api_key.json",
        skip_waiting_for_build_processing: true
      )
    # end
  end
end


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

XXXXXXXXXXXXXXXXXXXXX

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.184.1 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.4.0        |
| atomos                          | 0.1.3        |
| CFPropertyList                  | 3.0.3        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.19.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.7.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.82.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.1.0        |
| ruby2_keywords                  | 0.0.4        |
| faraday                         | 1.4.2        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.3        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.0.0        |
| fastimage                       | 2.2.3        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.3.0        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.0        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.15       |
| simctl                          | 1.6.8        |
| jwt                             | 2.2.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.1        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.0        |
| multi_json                      | 1.15.0       |
| signet                          | 0.15.0       |
| memoist                         | 0.16.2       |
| os                              | 1.1.1        |
| googleauth                      | 0.16.2       |
| httpclient                      | 2.8.3        |
| rexml                           | 3.2.3.1      |
| webrick                         | 1.6.1        |
| google-apis-core                | 0.3.0        |
| google-apis-playcustomapp_v1    | 0.3.0        |
| google-apis-androidpublisher_v3 | 0.4.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.4.0        |
| google-apis-storage_v1          | 0.4.0        |
| rake                            | 13.0.3       |
| digest-crc                      | 0.6.3        |
| google-cloud-storage            | 1.31.1       |
| emoji_regex                     | 3.2.2        |
| jmespath                        | 1.4.0        |
| aws-partitions                  | 1.465.0      |
| aws-eventstream                 | 1.1.1        |
| aws-sigv4                       | 1.2.3        |
| aws-sdk-core                    | 3.114.0      |
| aws-sdk-kms                     | 1.43.0       |
| aws-sdk-s3                      | 1.95.1       |
| uri                             | 0.10.0       |
| forwardable                     | 1.3.1        |
| logger                          | 1.4.2        |
| cgi                             | 0.1.0        |
| date                            | 3.0.0        |
| timeout                         | 0.1.0        |
| stringio                        | 0.1.0        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.1.0        |
| ostruct                         | 0.2.0        |
| strscan                         | 1.0.3        |
| io-console                      | 0.5.6        |
| delegate                        | 0.1.0        |
| fileutils                       | 1.4.1        |
| singleton                       | 0.1.0        |
| open3                           | 0.1.0        |
| yaml                            | 0.1.0        |
| psych                           | 3.1.0        |
| mutex_m                         | 0.1.0        |
</details>


*generated on:* **2021-05-31**
</details>

**Comment by lucgrabowski** [comment]
Hi @OlivierEdoki. It looks like `gym` is unable to `automatically detect the project file`. Could you try to call `gym` with `project` parameter with path to Xcode project or with `workspace` (https://docs.fastlane.tools/actions/gym/ )?

**Comment by OlivierEdoki** [comment]
Hi,
this command worked fine (from Project directory):
 fastlane gym --project /Users/user/Documents/GitHub/Project/Build/APPLE/Unity-iPhone.xcodeproj

and this one worked fine too (from Project directory):
 fastlane gym --project ./Build/APPLE/Unity-iPhone.xcodeproj

for both:
[10:06:28]: Successfully exported and compressed dSYM file
[10:06:28]: Successfully exported and signed the ipa file:

**Comment by lucgrabowski** [comment]
Hi, so if you could build the app with `gym` (`gym` is an alias to `build_app`) you can add a `project` parameter in `build_app` call in Fastfile like this:
```ruby
build_app(scheme: "Unity-iPhone", project: "Build/APPLE/Unity-iPhone.xcodeproj")
```
and fastlane should be able to detect the project and build the app.

**Comment by OlivierEdoki** [comment]
indeed, it works when I specify the project path (relative or absolute) in the build_app step

thanks for the quick answer!

**Comment by lucgrabowski** [comment]
@OlivierEdoki Could this issue be closed?

**Comment by OlivierEdoki** [comment]
yes, thanks for the quick reply! :)

**Comment by crazymanish** [comment]
Looks like, the issue has been resolved! Closing it now!
