### ISSUE TITLE
Fastlane produce fails with error, but appears to still create the app on App Store Connect

### ISSUE THREAD

**Issue by llamaluvr** [fastlane/fastlane#18794]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Fastlane produce fails with the following error:
```
Spaceship::UnexpectedResponse: [!] The provided entity includes a relationship with an invalid value - You cannot create a new version of the App in the current state. - /data/relationships/app
```
However, if you login to App Store Connect, the app appear to be created and everything seems to be OK. Besides the error showing up, we also no longer see the app ID (numeric ID) posted to the console.

##### Command executed
`bundle exec fastlane ios provision`
Our "provision" lane includes the following:

```
lane :provision do
    produce(
      app_name: ENV['APP_NAME'],
      app_identifier: ENV['APP_IDENTIFIER'],
      sku: ENV['SKU'],
      language: 'English',
      app_version: '1.0.0',
      team_id: ENV['TEAM_ID'],
      team_name: ENV['TEAM_NAME'],
      itc_team_id: ENV['ITC_TEAM_ID'],
      itc_team_name: ENV['ITC_TEAM_NAME'],
      company_name: ENV['ITC_TEAM_NAME'],
      enable_services: {
        associated_domains: "on",
        health_kit: "on",
        push_notification: "on",
      }
    )
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [✔] 🚀 
[11:29:50]: Loading from './fastlane/.env.brand'
[11:29:51]: ------------------------------
[11:29:51]: --- Step: default_platform ---
[11:29:51]: ------------------------------
[11:29:51]: Driving the lane 'ios provision' 🚀
[11:29:51]: ---------------------
[11:29:51]: --- Step: produce ---
[11:29:51]: ---------------------

+------------------------------------+--------------------------------+
|                     Summary for produce 2.184.1                     |
+------------------------------------+--------------------------------+
| app_name                           |  REDACTED            |
| app_identifier                     | com. REDACTED |
| sku                                | STORYSHERPAS01                 |
| language                           | English                        |
| app_version                        | 1.0.0                          |
| team_id                            |  REDACTED                     |
| team_name                          |  REDACTED                   |
| itc_team_id                        | REDACTED                      |
| itc_team_name                      | REDACTED                  |
| company_name                       |  REDACTED                   |
| enable_services.associated_domains | on                             |
| enable_services.health_kit         | on                             |
| enable_services.push_notification  | on                             |
| username                           |  REDACTED      |
| platform                           | ios                            |
| skip_itc                           | false                          |
| skip_devcenter                     | false                          |
+------------------------------------+--------------------------------+

[11:29:53]: Creating new app ' REDACTED' on the Apple Dev Center
[11:29:53]: Created app  REDACTED
[11:29:53]: Finished creating new app ' REDACTED' on the Dev Center
[11:29:58]: Creating new app ' REDACTED' on App Store Connect
[11:29:58]: Sending language name is deprecated. 'English' has been mapped to 'en-US'.
[11:29:58]: Please enter one of available languages: ["ar-SA", "ca", "cs", "da", "de-DE", "el", "en-AU", "en-CA", "en-GB", "en-US", "es-ES", "es-MX", "fi", "fr-CA", "fr-FR", "he", "hi", "hr", "hu", "id", "it", "ja", "ko", "ms", "nl-NL", "no", "pl", "pt-BR", "pt-PT", "ro", "ru", "sk", "sv", "th", "tr", "uk", "vi", "zh-Hans", "zh-Hant"]
[11:30:06]: Ensuring version number
+------------------+---------------+
|           Lane Context           |
+------------------+---------------+
| ENVIRONMENT      | brand         |
| DEFAULT_PLATFORM | ios           |
| PLATFORM_NAME    | ios           |
| LANE_NAME        | ios provision |
+------------------+---------------+
[11:30:07]: The provided entity includes a relationship with an invalid value - You cannot create a new version of the App in the current state. - /data/relationships/app

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 💥   | produce          | 16          |
+------+------------------+-------------+

[11:30:07]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  [Deliver] - Not able to reject the app version which is in Pending Developer Release
    https://github.com/fastlane/fastlane/issues/17539 [open] 25 💬
    4 weeks ago

➡️  [Deliver] - Not able to reject the app version which is in Pending Developer Release
    https://github.com/fastlane/fastlane/issues/17534 [closed] 3 💬
    01 Jan 2021

➡️  Having deliver/upload_to_app_store issues? Install 2.150.0.rc5
    https://github.com/fastlane/fastlane/issues/16639 [closed] 116 💬
    04 Sep 2020

and 2 more at: https://github.com/fastlane/fastlane/search?q=The%20provided%20entity%20includes%20a%20relationship%20with%20an%20invalid%20value%20-%20You%20cannot%20create%20a%20new%20version%20of%20the%20App%20in%20the%20current%20state.%20-%20%2Fdata%2Frelationships%2Fapp&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bin/fastlane)
Spaceship::UnexpectedResponse: [!] The provided entity includes a relationship with an invalid value - You cannot create a new version of the App in the current state. - /data/relationships/app
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/fastlane-a553f89de55b/spaceship/lib/spaceship/connect_api/api_client.rb:199:in `handle_response'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/fastlane-a553f89de55b/spaceship/lib/spaceship/connect_api/api_client.rb:124:in `post'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/fastlane-a553f89de55b/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:888:in `post_app_store_version'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/2.7.0/forwardable.rb:235:in `post_app_store_version'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/fastlane-a553f89de55b/spaceship/lib/spaceship/connect_api/models/app.rb:217:in `ensure_version!'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/fastlane-a553f89de55b/produce/lib/produce/itunes_connect.rb:68:in `block in create_new_app'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/fastlane-a553f89de55b/produce/lib/produce/itunes_connect.rb:67:in `each'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/fastlane-a553f89de55b/produce/lib/produce/itunes_connect.rb:67:in `create_new_app'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/fastlane-a553f89de55b/produce/lib/produce/itunes_connect.rb:16:in `run'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/fastlane-a553f89de55b/produce/lib/produce/manager.rb:12:in `start_producing'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/fastlane-a553f89de55b/fastlane/lib/fastlane/actions/create_app_online.rb:17:in `block in run'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/fastlane-a553f89de55b/fastlane/lib/fastlane/actions/create_app_online.rb:15:in `chdir'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/fastlane-a553f89de55b/fastlane/lib/fastlane/actions/create_app_online.rb:15:in `run'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/fastlane-a553f89de55b/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/fastlane-a553f89de55b/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/fastlane-a553f89de55b/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/fastlane-a553f89de55b/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/fastlane-a553f89de55b/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/fastlane-a553f89de55b/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/fastlane-a553f89de55b/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:278:in `block (2 levels) in parsing_binding'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/fastlane-a553f89de55b/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/fastlane-a553f89de55b/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/fastlane-a553f89de55b/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/fastlane-a553f89de55b/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/fastlane-a553f89de55b/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/fastlane-a553f89de55b/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/fastlane-a553f89de55b/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/fastlane-a553f89de55b/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/fastlane-a553f89de55b/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/fastlane-a553f89de55b/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/fastlane-a553f89de55b/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/fastlane-a553f89de55b/bin/fastlane:23:in `<top (required)>'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bin/fastlane:23:in `load'
  /Users/keith/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bin/fastlane:23:in `<top (required)>'</pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                    |
| --------------------------- | -------------------------------------------------------- |
| OS                          | 11.3.1                                                   |
| Ruby                        | 2.7.1                                                    |
| Bundler?                    | true                                                     |
| Git                         | git version 2.28.0                                       |
| Installation Source         | ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bin/fastlane |
| Host                        | macOS 11.3.1 (20E241)                                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.1/lib                              |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                              |
| Is contained                | false                                                    |
| Is homebrew                 | false                                                    |
| Is installed via Fabric.app | false                                                    |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/              |
| Xcode Version               | 12.4                                                     |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
require "spaceship"
require 'json'
default_platform :ios

platform :android do
  lane :update_store_listing do
    supply(
      skip_upload_screenshots: false,
      skip_upload_images: false,
      skip_upload_apk: true,
      skip_upload_metadata: false,
      skip_upload_changelogs: true,
      metadata_path: 'tmp/preview/fastlane/metadata/android',
    )
  end

  # updates store listing and submits new APK already uploaded to beta track
  # only works for updates where all metadata is already set
  # D'oh! This doesn't work for existing apps until we download all the existing app store descriptions and stuff
  # No wait! If we delete the metadata files entirely, it works!
  lane :submit_new_version do |options|
    supply(
      skip_upload_screenshots: options[:skip_upload_screenshots],
      skip_upload_images: false,
      skip_upload_apk: true,
      skip_upload_metadata: false,
      track_promote_to: 'production',
      track: 'beta',
      version_code: options[:version_code],
      metadata_path: 'tmp/preview/fastlane/metadata/android',
    )
  end

  # just testing this out to see if we could use it to confirm version number before promoting to production
  # output looks like this: "Found '4044' version codes in track 'beta'"
  lane :check_versions do |options|
    google_play_track_version_codes(
      track: 'beta'
    )
  end

  lane :submit_new_version_no_promote do |options|
    supply(
      skip_upload_screenshots: options[:skip_upload_screenshots],
      skip_upload_images: false,
      skip_upload_apk: true,
      skip_upload_metadata: false,
      skip_upload_changelogs: true,
      metadata_path: 'tmp/preview/fastlane/metadata/android',
    )
  end

  # we will eventually switch to this when we remove the upload step from the app build process
  lane :submit_new_version_with_upload do |options|
    supply(
      skip_upload_screenshots: options[:skip_upload_screenshots],
      skip_upload_images: false,
      skip_upload_apk: true,
      skip_upload_metadata: false,
      track: 'beta',
      metadata_path: 'tmp/preview/fastlane/metadata/android',
    )
  end
end

platform :ios do
  lane :queryteams do
    Spaceship::Tunes.login
    Spaceship::Tunes.select_team
    Spaceship::Portal.login
    Spaceship::Portal.select_team
  end
  # just some command that allows us to enter the second factor auth
  lane :entersecondfactor do
    Spaceship::Tunes.login
    Spaceship::Tunes.select_team
  end
  lane :querypem do
    pem(
      team_id: ENV['TEAM_ID'],
      team_name: ENV['TEAM_NAME'],
      development: false,
      generate_p12: false,
      force: false,
      active_days_limit: 1,
      save_private_key: false
    )
  end
  lane :testspaceship do
    Spaceship::Tunes.login
    Spaceship::Tunes.select_team
    app = Spaceship::Tunes::Application.all[0]
    puts app
    puts app.apple_id
    #puts Spaceship::Tunes.client.get_groups(app_id: app.apple_id)
  end
  lane :query_team_license_messages do
    open('../library/reports/app-store-issues.txt', 'w') do |f|
      client = Spaceship::Portal.login
      i = 0
      loop do
          begin
              Spaceship.select_team(team_id: client.teams[i]["teamId"])
              Spaceship::Portal.client.apps
          rescue StandardError => error
              f.puts "Org Name: " + client.teams[i]["name"]
              f.puts error
              f.puts client.teams[i]["teamAgent"]["email"]
              f.puts '--------------'
          end

          if client.teams[i + 1] == nil
              break
          end

          i += 1
      end
    end
  end
  lane :query_team_account_holders do
    open('../library/reports/app-store-account-holders.txt', 'w') do |f|
      client = Spaceship::Portal.login
      i = 0
      loop do
          begin
              f.puts "Org Name: " + client.teams[i]["name"] + " / Account holder: " + client.teams[i]["teamAgent"]["firstName"] + " " + client.teams[i]["teamAgent"]["lastName"] + " (" + client.teams[i]["teamAgent"]["email"] + ")"
          rescue StandardError => error
              f.puts "Org Name: " + client.teams[i]["name"]
              f.puts error
              f.puts client.teams[i]["teamAgent"]["email"]
              f.puts '--------------'
          end

          if client.teams[i + 1] == nil
              break
          end

          i += 1
      end
    end
  end
  lane :query_app_releases do
    # idea for querying releases to see what's up to date and what's not
    # next step is to get the latest build number from the tunes app somehow
    open('../library/reports/app-releases.txt', 'w') do |f|
      client = Spaceship::Portal.login
      Spaceship::Tunes.login
      i = 0
      loop do
          begin
              Spaceship.select_team(team_id: client.teams[i]["teamId"])
              apps = Spaceship::Portal.client.apps
              j = 0
              loop do
                  begin
                    app = apps[j]
                    f.puts app["name"]
                    tunesApp = Spaceship::Tunes::Application.find(app["identifier"])
                    f.puts tunesApp
                  end
                  if apps[j + 1] == nil
                      break
                  end
                  j += 1
              end
          rescue StandardError => error
              f.puts "Org Name: " + client.teams[i]["name"] + ": can't retrieve apps"
              f.puts error
          end

          if client.teams[i + 1] == nil
              break
          end
          i += 1

      end
    end
  end
  lane :check_app_status do
    Spaceship::ConnectAPI.login(
      portal_team_id: ENV['TEAM_ID'],
      tunes_team_id: ENV['ITC_TEAM_ID']
    )
    app = Spaceship::ConnectAPI::App.find(ENV["APP_IDENTIFIER"])
    #print(JSON.unparse(app))
    publish_state = Spaceship::ConnectAPI::AppDataUsagesPublishState.get(app_id: app.id)
    print("~~~")
    print(JSON.unparse(publish_state))
    print("~~~")
  end
  lane :createusers do
    Spaceship::ConnectAPI.login(
      portal_team_id: ENV['TEAM_ID'],
      tunes_team_id: ENV['ITC_TEAM_ID']
    )
    begin
      users = [
        redacted
      ]
      i = 0
      loop do
          begin
              Spaceship::ConnectAPI.post_user_invitation(
                first_name: users[i]["first_name"],
                last_name: users[i]["last_name"],
                email: users[i]["email"],
                roles: ["DEVELOPER"],
                all_apps_visible: true
              )
               puts "User: " + users[i]["first_name"] + " added!"
          rescue StandardError => error
              puts "Error: User: " + users[i]["first_name"] + " not added!"
              puts error
              puts '--------------'
          end

          if users[i + 1] == nil
              break
          end

          i += 1
      end
    end
  end
  lane :provision do
    produce(
      app_name: ENV['APP_NAME'],
      app_identifier: ENV['APP_IDENTIFIER'],
      sku: ENV['SKU'],
      language: 'English',
      app_version: '1.0.0',
      team_id: ENV['TEAM_ID'],
      team_name: ENV['TEAM_NAME'],
      itc_team_id: ENV['ITC_TEAM_ID'],
      itc_team_name: ENV['ITC_TEAM_NAME'],
      company_name: ENV['ITC_TEAM_NAME'],
      enable_services: {
        associated_domains: "on",
        health_kit: "on",
        push_notification: "on",
      }
    )
  end

  lane :push do
    pem(
      team_id: ENV['TEAM_ID'],
      team_name: ENV['TEAM_NAME'],
      development: true,
      generate_p12: true,
      force: true,
      save_private_key: true,
      p12_password: 'wR!R5n9&',
      output_path: File.expand_path('~/dev/nudge-api/storage/certificates/')
    )

    pem(
      team_id: ENV['TEAM_ID'],
      team_name: ENV['TEAM_NAME'],
      development: false,
      generate_p12: true,
      force: true,
      save_private_key: true,
      p12_password: 'W2@MkxP6',
      output_path: File.expand_path('~/dev/nudge-api/storage/certificates/')
    )
  end

  lane :preview_new_version do
    deliver(
      submit_for_review: false,
      metadata_path: 'tmp/preview/fastlane/metadata',
      screenshots_path: 'tmp/preview/fastlane/screenshots',
      app_rating_config_path: 'tmp/preview/fastlane/rating_config.json',
      overwrite_screenshots: true,
      automatic_release: false,
      price_tier: 0,
      force: false,
    )
  end

  # essentially the same as create_new_version, but now allows for optional automatic release and screenshot overwriting
  # automatic release is great for bulk updates.
  # turning off screenshot overwriting is a nice time-saver when you know new screenshots aren't necessary
  # heads-up that metadata that is missing entirely (like for existing brands ported over from nudge-mobile-v4) is not blanked output_path
  # The missing stuff just isn't overwritten - cool!
  lane :submit_new_version do |options|
    deliver(
      submit_for_review: true,
      metadata_path: 'tmp/preview/fastlane/metadata',
      screenshots_path: 'tmp/preview/fastlane/screenshots',
      app_rating_config_path: 'tmp/preview/fastlane/rating_config.json',
      overwrite_screenshots: true,
      skip_screenshots: options[:skip_upload_screenshots],
      automatic_release: true,
      price_tier: 0,
      force: true,
      submission_information: {
          content_rights_contains_third_party_content: false,
          add_id_info_limits_tracking: true,
          add_id_info_serves_ads: false,
          add_id_info_tracks_action: true,
          add_id_info_tracks_install: true,
          add_id_info_uses_idfa: true,
      },
      build_number: options[:build_number],
      app_version: options[:app_version]
    )
  end

  # probably not needed in the long run, but still used when submitting the first white label version
  lane :create_new_version do |options|
    deliver(
      submit_for_review: true,
      metadata_path: 'tmp/preview/fastlane/metadata',
      screenshots_path: 'tmp/preview/fastlane/screenshots',
      app_rating_config_path: 'tmp/preview/fastlane/rating_config.json',
      overwrite_screenshots: true,
      automatic_release: true,
      price_tier: 0,
      force: true,
      submission_information: {
          content_rights_contains_third_party_content: false,
          add_id_info_limits_tracking: true,
          add_id_info_serves_ads: false,
          add_id_info_tracks_action: true,
          add_id_info_tracks_install: true,
          add_id_info_uses_idfa: true,
      },
      # will feed this in from a consolidated version file in the future
      # we probably can't bring version file over until all white labels are here
      #build_number: '4030',
      # Also manual for now
      #app_version: '2.0.1'
      build_number: options[:build_number],
      app_version: options[:app_version]
    )
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier ENV['APP_IDENTIFIER'] # The bundle identifier of your app
itc_team_id ENV['ITC_TEAM_ID']
itc_team_name ENV['ITC_TEAM_NAME']

team_id ENV['TEAM_ID']  # Developer Portal Team ID
json_key_file ENV["JSON_KEY_FILE"]
package_name ENV["APP_IDENTIFIER"]

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

#if ENV["USE_BUILDAGENT"] == '1'
 # ENV["FASTLANE_USER"] = ENV["BUILDAGENT_FASTLANE_USER"];
 # ENV["FASTLANE_PASSWORD"] = ENV["BUILDAGENT_FASTLANE_PASSWORD"];
#end
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.184.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.4.0        |
| bundler                         | 2.1.4        |
| uri                             | 0.10.0       |
| rake                            | 13.0.3       |
| CFPropertyList                  | 3.0.3        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.7.0        |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.1.1        |
| aws-partitions                  | 1.465.0      |
| aws-sigv4                       | 1.2.3        |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.114.0      |
| aws-sdk-kms                     | 1.43.0       |
| aws-sdk-s3                      | 1.95.1       |
| babosa                          | 1.0.4        |
| claide                          | 1.0.3        |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.3        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.2        |
| excon                           | 0.82.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.1.0        |
| multipart-post                  | 2.0.0        |
| ruby2_keywords                  | 0.0.4        |
| faraday                         | 1.4.2        |
| http-cookie                     | 1.0.3        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.0.0        |
| fastimage                       | 2.2.4        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.2.3        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| signet                          | 0.15.0       |
| googleauth                      | 0.16.2       |
| httpclient                      | 2.8.3        |
| mini_mime                       | 1.1.0        |
| trailblazer-option              | 0.1.1        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| rexml                           | 3.2.5        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.3.0        |
| google-apis-androidpublisher_v3 | 0.5.0        |
| google-apis-playcustomapp_v1    | 0.3.0        |
| google-apis-iamcredentials_v1   | 0.4.0        |
| google-apis-storage_v1          | 0.4.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.31.1       |
| json                            | 2.5.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.0        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.19.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
</details>

*generated on:* **2021-06-02**
</details> </pre>
</details>

**Comment by lucgrabowski** [comment]
Hi, what is the current state of the app on AppstoreConnect? Isn't it Pending Developer Release state? If you go to the app on AppstoreConnect, do you see + button above the iOS app version? 

From the stacktrace, we can see that there is no edit_version of the app and crash happens when you try to create a new version.
https://github.com/fastlane/fastlane/blob/adc0af347f5820d1b73d670f247561cef4caf227/spaceship/lib/spaceship/connect_api/models/app.rb#L204-L221

**Comment by Treeane** [comment]
New Issue Checklist Updated fastlane to the latest version I read the  When I go to AppStoreConnect and create the App with same bundleID  [deliver][produce][spaceship] Update to use new App Store Connect API endpoints #16640  This should still work for creating the app on the Developer Center

**Comment by Hall20** [comment]
It must feel great to receive such a comment.

[aces etm](https://www.acesetm.me/)

**Comment by lucgrabowski** [comment]
Hi, @llamaluvr, as I got a notification from the issue now for the last comment ... Did you have a possibility to check state of the app, as I wrote in the comment above?

**Comment by llamaluvr** [comment]
@lucgrabowski I am SO SORRY for missing this. Thank you so much for looking into this. I only realized I have forgotten to follow-up when I saw the issue in the console output when I got the error again for another app under Produce 2.187. Here's what it looks like in ASC, no plus above the iOS version. 
![image](https://user-images.githubusercontent.com/8053974/124188055-bb71b500-da8c-11eb-9d7d-503ff548d5ca.png)

**Comment by lucgrabowski** [comment]
Hi, it seems like AppStore Connect isn't satisfied with `app_version` parameter when you're creating an app and I think that it may return error because `app_version="1.0.0`. Could you try creating an app with `app_version="1.0"`? This is a default initial value, as you can see and maybe it will help. And if that fails, could you try creating an app without using `app_version` parameter?

**Comment by Matilda1185** [comment]
Did you have a possibility to check state of the app, as I wrote in the comment above?

**Comment by llamaluvr** [comment]
@lucgrabowski I only get one chance to create the app (since it still creates even if it errors out), so I just removed the `app_version` parameter to accept the default, and that worked. Thanks so much for your help!
