### ISSUE TITLE
expire_previous_builds = true not expiring previous builds in TestFlight

### ISSUE THREAD

**Issue by madjuju** [fastlane/fastlane#18791]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

expire_previous_builds = true not expiring previous builds in TestFlight
##### Command executed
upload_to_testflight(
expire_previous_builds: "true"
) 

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.4                                                           |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.30.1 (Apple Git-130)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.4 (20F71)                                             |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.5                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | fr_FR.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.171.0"




####--------------------------- TESTFLIGHT PROD API2-------------------------
  desc "Déploiement sur TestFlight PROD"
  lane :beta do
  build_app(
                                        scheme: ENV['APP_SCHEME_NAME'], 
                                        export_xcargs: "-allowProvisioningUpdates",
                                        output_name: ENV['PILOT_USERNAME'] = "xxxxxxxx,
                                        include_bitcode: "true",
                                        include_symbols: "true",
                                        derived_data_path: "/Users/julien/Library/Developer/Xcode/DerivedData/#{ENV['APP_SCHEME_NAME']}/",
                                        build_path:"/Users/julien/Library/Developer/Xcode/DerivedData/ipa/#{ENV['APP_SCHEME_NAME']}/",
                                        output_directory:"/Users/julien/Library/Developer/Xcode/DerivedData/ipa/#{ENV['APP_SCHEME_NAME']}/",
                                        )

  #ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t Aspera"
  upload_to_testflight(


                                        expire_previous_builds: "true"


                                        ) 

  version = get_version_number_from_plist(

                                        #xcodeproj: "coolncamp.xcworkspace", # optional
                                        scheme: ENV['APP_SCHEME_NAME'], # optional, or `scheme`
                                        # optional, must be specified if you have different Info.plist build settings
                                        # for different build configurations
                                        plist_build_setting_support: true, # optional, and defaulting to false. setting this will 
                                        # resolve the version number using the relevant build settings from your xcodeproj.
                                        build_configuration_name: 'Release')

  build = get_build_number_from_plist(

                                        #xcodeproj: "coolncamp.xcworkspace", # optional
                                        scheme: ENV['APP_SCHEME_NAME'], # optional, or `scheme`
                                        # optional, must be specified if you have different Info.plist build settings
                                        # for different build configurations
                                        plist_build_setting_support: false, # optional, and defaulting to false. setting this will 
                                        # resolve the version number using the relevant build settings from your xcodeproj.
                                        build_configuration_name: 'Release')
puts "#{version} build #{build}"
                                   
  git_add_tag(
                                        workspace: './',
                                        branch: 'master',
                                        tag_message: '',
                                        prefix: ENV['APP_SCHEME_NAME'],
                                        tag_name:"_#{version}_#{build}")

    download_dsyms(

                      #after_uploaded_date: "2020-01-11T19:00:00+01:00",
                      version: "#{version}",
                      build_number: "#{build}",
                      output_directory: "/Users/julien/Library/Developer/Xcode/DerivedData/#{ENV['APP_SCHEME_NAME']}/"

                    )
    upload_symbols_to_crashlytics(
                      
                      dsym_worker_threads: "1",
                      gsp_path: ENV['GOOGLE_SERVICES_INFO_PLIST_PATH']

                      )

    clean_build_artifacts
 

  end




end


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier(ENV['BUNDLE_ID']) # The bundle identifier of your app
apple_id(ENV['APPLE_EMAIL'])     # Your Apple email address
itc_team_id(ENV['FASTLANE_ITC_TEAM_ID'])
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.184.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                | Version | Update-Status |
| ------------------------------------- | ------- | ------------- |
| fastlane-plugin-appicon               | 0.16.0  | ✅ Up-To-Date  |
| fastlane-plugin-translation           | 1.1.4   | ✅ Up-To-Date  |
| fastlane-plugin-google_sheet_localize | 0.4.0   | ✅ Up-To-Date  |
| fastlane-plugin-localization          | 0.2.0   | ✅ Up-To-Date  |
| fastlane-plugin-badge                 | 1.5.0   | ✅ Up-To-Date  |
| fastlane-plugin-git_add_tag           | 0.1.2   | ✅ Up-To-Date  |
| fastlane-plugin-versioning            | 0.4.5   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                   | Version      |
| ------------------------------------- | ------------ |
| did_you_mean                          | 1.3.0        |
| bundler                               | 2.2.16       |
| rake                                  | 13.0.3       |
| CFPropertyList                        | 3.0.3        |
| concurrent-ruby                       | 1.1.8        |
| i18n                                  | 1.8.10       |
| minitest                              | 5.14.4       |
| thread_safe                           | 0.3.6        |
| tzinfo                                | 1.2.9        |
| activesupport                         | 5.2.5        |
| public_suffix                         | 4.0.6        |
| addressable                           | 2.7.0        |
| httpclient                            | 2.8.3        |
| json                                  | 2.5.1        |
| algoliasearch                         | 1.27.5       |
| artifactory                           | 3.0.15       |
| atomos                                | 0.1.3        |
| aws-eventstream                       | 1.1.1        |
| aws-partitions                        | 1.465.0      |
| aws-sigv4                             | 1.2.3        |
| jmespath                              | 1.4.0        |
| aws-sdk-core                          | 3.114.0      |
| aws-sdk-kms                           | 1.43.0       |
| aws-sdk-s3                            | 1.95.1       |
| babosa                                | 1.0.4        |
| fastimage                             | 2.2.4        |
| colored                               | 1.2          |
| highline                              | 2.0.3        |
| commander                             | 4.6.0        |
| dotenv                                | 2.7.6        |
| emoji_regex                           | 3.2.2        |
| excon                                 | 0.82.0       |
| faraday-em_http                       | 1.0.0        |
| faraday-em_synchrony                  | 1.0.0        |
| faraday-excon                         | 1.1.0        |
| faraday-net_http                      | 1.0.1        |
| faraday-net_http_persistent           | 1.1.0        |
| multipart-post                        | 2.0.0        |
| ruby2_keywords                        | 0.0.4        |
| faraday                               | 1.4.2        |
| unf_ext                               | 0.0.7.7      |
| unf                                   | 0.1.4        |
| domain_name                           | 0.5.20190701 |
| http-cookie                           | 1.0.3        |
| faraday-cookie_jar                    | 0.0.7        |
| faraday_middleware                    | 1.0.0        |
| gh_inspector                          | 1.1.3        |
| jwt                                   | 2.2.3        |
| memoist                               | 0.16.2       |
| multi_json                            | 1.15.0       |
| os                                    | 1.1.1        |
| signet                                | 0.15.0       |
| googleauth                            | 0.16.2       |
| mini_mime                             | 1.1.0        |
| declarative                           | 0.0.20       |
| trailblazer-option                    | 0.1.1        |
| uber                                  | 0.1.0        |
| representable                         | 3.1.1        |
| retriable                             | 3.1.2        |
| rexml                                 | 3.2.5        |
| webrick                               | 1.7.0        |
| google-apis-core                      | 0.3.0        |
| google-apis-androidpublisher_v3       | 0.5.0        |
| google-apis-playcustomapp_v1          | 0.3.0        |
| digest-crc                            | 0.6.3        |
| google-apis-iamcredentials_v1         | 0.4.0        |
| google-apis-storage_v1                | 0.4.0        |
| google-cloud-env                      | 1.5.0        |
| google-cloud-errors                   | 1.1.0        |
| google-cloud-core                     | 1.6.0        |
| google-cloud-storage                  | 1.31.1       |
| mini_magick                           | 4.11.0       |
| naturally                             | 2.2.1        |
| plist                                 | 3.6.0        |
| rubyzip                               | 2.3.0        |
| security                              | 0.1.3        |
| simctl                                | 1.6.8        |
| terminal-notifier                     | 2.0.0        |
| unicode-display_width                 | 1.7.0        |
| terminal-table                        | 1.8.0        |
| tty-screen                            | 0.8.1        |
| tty-cursor                            | 0.7.1        |
| tty-spinner                           | 0.9.3        |
| word_wrap                             | 1.0.0        |
| claide                                | 1.0.3        |
| colored2                              | 3.1.2        |
| nanaimo                               | 0.3.0        |
| xcodeproj                             | 1.19.0       |
| rouge                                 | 2.0.7        |
| xcpretty                              | 0.3.0        |
| xcpretty-travis-formatter             | 1.0.1        |
| badge                                 | 0.13.0       |
| fuzzy_match                           | 2.0.4        |
| nap                                   | 1.1.0        |
| netrc                                 | 0.11.0       |
| ffi                                   | 1.15.0       |
| ethon                                 | 0.13.0       |
| typhoeus                              | 1.4.0        |
| cocoapods-core                        | 1.10.1       |
| cocoapods-deintegrate                 | 1.0.4        |
| cocoapods-downloader                  | 1.4.0        |
| cocoapods-plugins                     | 1.0.0        |
| cocoapods-search                      | 1.0.0        |
| cocoapods-trunk                       | 1.5.0        |
| cocoapods-try                         | 1.2.0        |
| escape                                | 0.0.4        |
| fourflusher                           | 2.3.1        |
| molinillo                             | 0.6.6        |
| ruby-macho                            | 1.4.0        |
| cocoapods                             | 1.10.1       |
| fastlane-plugin-appicon               | 0.16.0       |
| fastlane-plugin-badge                 | 1.5.0        |
| fastlane-plugin-git_add_tag           | 0.1.2        |
| google-apis-drive_v3                  | 0.5.0        |
| google-apis-sheets_v4                 | 0.4.0        |
| mini_portile2                         | 2.5.1        |
| racc                                  | 1.5.2        |
| nokogiri                              | 1.11.3       |
| google_drive                          | 3.0.7        |
| fastlane-plugin-google_sheet_localize | 0.4.0        |
| fastlane-plugin-localization          | 0.2.0        |
| fastlane-plugin-translation           | 1.1.4        |
| fastlane-plugin-versioning            | 0.4.5        |
</details>

*generated on:* **2021-06-02**
</details>

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by Kenneth587** [comment]
You just can't. Expired builds can't be used again in TestFlight. They do show up in the Activity section because it's the "history" of your builds, App Store versions and reviews.
