### ISSUE TITLE
Missing or invalid signature. The bundle X at bundle path X is not signed using an Apple submission certificate.

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1879]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/4329185?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @AvdLee - Imported from <a href='https://github.com/fastlane/pilot/issues/132'>fastlane/pilot#132</a>
        </td>
      </tr>
    </table>

I'm having troubles setting up our Mac mini together with Fastlane. 
I want my app to be build by an integration on our Xcode server and uploaded to TestFlight.

My first try was to:

- Create a bot which generates an IPA using the "Create user installable product" checkmark
- Select this IPA and submit to TestFlight using Pilot

However, this failed with the following error:
```
Assertion: exportArchive: No 'teamID' specified and no team ID found in the archive
```

I checked my project, team ID is set, bundle identifier matches production provisioning profile.

**Using Fastlane only: Gym and Pilot**

My best approach so far is using Fastlane only using this prescript:
```
export LC_ALL="en_US.UTF-8"

# Export path to make sure XCPretty works
export PATH="/usr/local/bin:$PATH" 

#Change to the directory where .xcodeproj is located
cd MainProject

#Copy provisioning profiles, which are in the Git repo
cp -a "Certificates/." "/Library/Developer/XcodeServer/ProvisioningProfiles/"

#From example, all steps:
/usr/local/bin/fastlane ios beta_testflight
```

My lane looks as followed:

```
  desc "Responsible for building and signing the app"
  private_lane :build_app do |options|
    cocoapods

    gym(
      workspace: "MyProject.xcworkspace",
      scheme: "MyProject",
      clean: true,
      export_team_id: "XXXXXXX",
      provisioning_profile_path: "/Library/Developer/XcodeServer/ProvisioningProfiles/AppStore.mobileprovision",
      codesigning_identity: "iPhone Distribution: XXX"
    )
  end


  desc "Build and upload a new build to Apple TestFlight"
  desc "This action will also do a build version bump and push it to git."
  desc "This will **not** send an email to all testers, it will only be uploaded to the new TestFlight."
  lane :beta_testflight do
    build_app

    pilot(username:"myuser@x.com", skip_submission:true)
  end
```

_I've cleared some personal data from it_

This creates an ipa correctly:
```
[20:24:12]: [32mSuccessfully exported and compressed dSYM file[0m
[20:24:12]: [32mSuccessfully exported and signed the ipa file:[0m
[20:24:12]: /Library/Developer/XcodeServer/Integrations/Caches/cf28edc3cf17c74d94ed4fec4202b29e/Source/X/X.ipa
```

However Pilot still marks the following error:
```
[31m[20:25:13]: [0mERROR ITMS-90034: "Missing or invalid signature. The bundle 'X' at bundle path 'Payload/X.app' is not signed using an Apple submission certificate."
[31mReturn status of iTunes Transporter was 1: ERROR ITMS-90034: "Missing or invalid signature. The bundle 'X' at bundle path 'Payload/X.app' is not signed using an Apple submission certificate."
```

I've also tried to resign with sigh, by using terminal on our Mac mini and navigate to the integration folder:

```
Repackaging as X.ipa
Process complete

[20:14:03]: Successfully signed X.ipa!
```

However, this still gives me the above error.

I'm really lost and out of my ideas how to fix this.

Hoping to find the correct answer here!

**Comment by AvdLee** [comment]
this one can be closed!

**Comment by KrauseFx** [comment]
Perfect, thanks 👍
