### ISSUE TITLE
Upload immediately succeeds, but no build uploaded

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1880]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/41975?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @dusek - Imported from <a href='https://github.com/fastlane/pilot/issues/128'>fastlane/pilot#128</a>
        </td>
      </tr>
    </table>

running `pilot(distribute_external: false, skip_submission: true)` as part of fastlane or standalone `pilot upload --skip_submission`:

```
INFO [2016-01-27 10:53:26.03]: Login successful
INFO [2016-01-27 10:53:26.47]: Ready to upload new build to TestFlight (App: XXXXXXXXXX)...
INFO [2016-01-27 10:53:27.11]: Wrote XML data to '/tmp/XXXXXXXXXX.itmsp'
INFO [2016-01-27 10:53:27.13]: Going to upload updated app to iTunesConnect
INFO [2016-01-27 10:53:27.13]: This might take a few minutes, please don't interrupt the script
DEBUG [2016-01-27 10:53:27.19]: "/Applications/Xcode.app/Contents/Developer/../Applications/Application Loader.app/Contents/itms/bin/iTMSTransporter" -m upload -u "my@apple.id" -p 'YourPassword' -f '/tmp/XXXXXXXXXX.itmsp'  -t 'Signiant' -k 100000
INFO [2016-01-27 10:53:27.19]: ------------------------------------------------------------------------------------------------------
INFO [2016-01-27 10:53:27.19]: Successfully uploaded package to iTunesConnect. It might take a few minutes until it's visible online.
INFO [2016-01-27 10:53:27.19]: ------------------------------------------------------------------------------------------------------
INFO [2016-01-27 10:53:27.19]: Successfully uploaded the new binary to iTunes Connect
```

You can see that the upload command itself succeeds in under a second. The IPA has ~41MB and I definitely do not have such a fast internet connection to upload it in under a second :-) This problem was reproduced at two places (home and office), so it should not be a network issue. The problem was also reproduced on two different machines.

I checked that XXXXXXXXXX is the correct App ID, my@apple.id is my Apple ID.

I tried with `DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV"`, same result.

Also archiving with Xcode and submitting using Xcode organizer works fine.

This is my first time using fastlane. Other tools I am using (cert, sigh, gym) work fine.

```
$ pilot --version
pilot 1.2.1
$ ruby -v
ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
$ sw_vers 
ProductName:    Mac OS X
ProductVersion: 10.11.3
BuildVersion:   15D21
$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

Any help would be appreciated. Without `pilot` working, fastlane is not really useful for us.

**Comment by KrauseFx** [comment]
Sorry for not coming back to this earlier, is this issue still happening with the latest _fastlane_ release?
