### ISSUE TITLE
Xcode Can Build Release but not Debug - App requires a provisioning profile with Push Notifications etc

### ISSUE THREAD

**Issue by ohthepain** [fastlane/fastlane#18805]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I am Xcode trying to build and run on my device. When I hit "play" it tries to build but I get this error message. 
`Code Signing Error: "Unity-iPhone" requires a provisioning profile with the In-App Purchase, Game Center, and Push Notifications features. Select a provisioning profile in the Signing & Capabilities editor.
`

I am using Fastlane match to manage code signing. I can build Release using Fastlane from the command line on my local machine. I have checked my settings in Xcode and in the dev portal many many times and have regenerated my certs.

##### Command executed
Build from Xcode, Debug mode
Manual signing

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 11.4                                                    |
| Ruby                        | 2.7.3                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.30.1 (Apple Git-130)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.184.1/libexec/bin/fastlane |
| Host                        | macOS 11.4 (20F71)                                      |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.7/2.7.3/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                             |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 12.5                                                    |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

#before_all do
#  update_fastlane
#end

platform :android do
	desc "Runs all the tests"
	lane :test do
		gradle(task: "test")
	end

	desc "Submit a new Beta Build to Crashlytics Beta"
	lane :beta do
		gradle(task: "clean assembleRelease")
		crashlytics

	# sh "your_script.sh"
	# You can also use other beta testing services here
	end

	desc "Deploy a new version to the Google Play"
	lane :deploy do
		gradle(task: "clean assembleRelease")
		upload_to_play_store
	end
end

lane :beta do
#	infoPlistPath = "/Users/paulwilkinson/projects/Unity/BadNRG/Build/iPhone/Info.plist"
#	version = get_version_number()
#	buildNumber = get_info_plist_value(path: infoPlistPath, key: "CFBundleVersion")
	#increment_version_number(version_number: version)
	#increment_version_number()
	build_app(scheme: "Unity-iPhone",
		project: "../../../Build/iPhone/Unity-iPhone.xcodeproj",
		include_bitcode: true)
	upload_to_testflight
	slack(message: "Successfully distributed a new beta build")
end

platform :ios do

	desc "Get certificates - this is done by build machine"
	lane :certificates do
		sync_code_signing(
		  type: "development",
		  app_identifier: 'com.thisco.badenergy',
		  force_for_new_devices: true,
		  readonly: true
		)

		sync_code_signing(
		  type: "appstore",
		  app_identifier: 'com.thisco.badenergy',
		  readonly: true
		)
	end

	desc "Generate new certificates"
	lane :generate_new_certificates do
		sync_code_signing(
			type: "development",
			app_identifier: 'com.thisco.badenergy',
			force_for_new_devices: true,
			readonly: false
		)

		sync_code_signing(
			type: "appstore",
			app_identifier: 'com.thisco.badenergy',
			force_for_new_devices: true,
			readonly: false
		)
	end

	desc "deploy"
	lane :deploy do
		setup_ci
		sync_code_signing(
			type: "appstore",
			app_identifier: 'com.thisco.badenergy',
			readonly: true
		)

		build_app(scheme: "Unity-iPhone",
							project: "../../../Build/iPhone/Unity-iPhone.xcodeproj",
							include_bitcode: true)
		app_store_connect_api_key(
			is_key_content_base64: true,
			in_house: false, # if it is enterprise or not
		)
		upload_to_app_store(
			force: true,
			run_precheck_before_submit: false,
			submit_for_review: false
		)
	end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file(xxx-api-upload.json") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("xxx")
team_name "xxx"
team_id "xxx"
itc_team_id "xxx"
itc_team_name "xxx"
username("xxxxxx@gmail.com")
slack_url("https://hooks.slack.com/services/xxx/xxx/xxx")

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.184.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.4.0        |
| atomos                          | 0.1.3        |
| CFPropertyList                  | 3.0.3        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.19.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.7.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.82.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.1.0        |
| ruby2_keywords                  | 0.0.4        |
| faraday                         | 1.4.2        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.3        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.0.0        |
| fastimage                       | 2.2.3        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.0        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.15       |
| simctl                          | 1.6.8        |
| jwt                             | 2.2.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.1        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.0        |
| multi_json                      | 1.15.0       |
| signet                          | 0.15.0       |
| memoist                         | 0.16.2       |
| os                              | 1.1.1        |
| googleauth                      | 0.16.2       |
| httpclient                      | 2.8.3        |
| google-apis-core                | 0.3.0        |
| google-apis-playcustomapp_v1    | 0.3.0        |
| google-apis-androidpublisher_v3 | 0.4.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.4.0        |
| google-apis-storage_v1          | 0.4.0        |
| rake                            | 13.0.3       |
| digest-crc                      | 0.6.3        |
| google-cloud-storage            | 1.31.1       |
| emoji_regex                     | 3.2.2        |
| jmespath                        | 1.4.0        |
| aws-partitions                  | 1.465.0      |
| aws-eventstream                 | 1.1.1        |
| aws-sigv4                       | 1.2.3        |
| aws-sdk-core                    | 3.114.0      |
| aws-sdk-kms                     | 1.43.0       |
| aws-sdk-s3                      | 1.95.1       |
| uri                             | 0.10.0       |
| json                            | 2.5.1        |
| rexml                           | 3.2.5        |
| webrick                         | 1.7.0        |
| forwardable                     | 1.3.1        |
| logger                          | 1.4.2        |
| cgi                             | 0.1.0        |
| date                            | 3.0.0        |
| timeout                         | 0.1.0        |
| stringio                        | 0.1.0        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.1.0        |
| ostruct                         | 0.2.0        |
| strscan                         | 1.0.3        |
| io-console                      | 0.5.6        |
| delegate                        | 0.1.0        |
| fileutils                       | 1.4.1        |
| singleton                       | 0.1.0        |
| open3                           | 0.1.0        |
| yaml                            | 0.1.0        |
| psych                           | 3.1.0        |
| mutex_m                         | 0.1.0        |
</details>

*generated on:* **2021-06-05**
</details>

<details>
Can’t use development profile
match Development includes my development certificate on the site

Code Signing Error: "Unity-iPhone" requires a provisioning profile with the In-App Purchase, Game Center, and Push Notifications features. Select a provisioning profile in the Signing & Capabilities editor.

I can build release, but not Debug

I am using match provisioning profiles and have assigned a "match" Provisioning Profile in Xcode Build Settings 

Profile:
Enabled Capabilities
Game Center, In-App Purchase, Personal VPN, Push Notifications

I tried switching to automatic

I have no expired certs on the apple site or in my keychain
In Xcode Signing & Capabilities, my settings are all correct for
- Team
- Bundle ID
- Provisioning profile (match Development com.myco….)
- Signing Certificate

I regenerated my keys, certificates and provisioning profiles with
fastlane match nuke development
fastlane match development

Restarted Xcode and my machine

Output from these commands looks correct:
security find-identity -v -p codesigning
security default-keychain
</details>

**Comment by crazymanish** [comment]
Hi @ohthepain 
> Code Signing Error: "Unity-iPhone" requires a provisioning profile with the In-App Purchase, Game Center, and Push Notifications features. Select a provisioning profile in the Signing & Capabilities editor.

From your logs it seems, your debug provisioning profile is not `In-App Purchase, Game Center, and Push Notifications features` enabled.

I request you to compare your release v/s debug ***.mobileprovision** file. I am pretty sure, there is some error in your project settings or maybe you are using the wrong  ***.mobileprovision** file...

I hope this will help! I am sorry, can't do much about your project setting!

**Comment by crazymanish** [comment]
If the issue still occurs, i am requesting you to open a discussion here https://github.com/fastlane/fastlane/discussions/categories/q-a 

Thank you!

**Comment by ohthepain** [comment]
Thanks crazymanish. It seems to be because I selected iOS Development instead of Apple Development somewhere.
