### ISSUE TITLE
Why do we expect the dSYM to end in dSYM ?

### ISSUE THREAD

**Issue by tewner** [fastlane/fastlane#18884]
Hi FastLane Team!
Why does fastLane automatically add "/dSYMs" to the path?

https://github.com/fastlane/fastlane/blob/b817148d4967ab6e38b8f1a8b81d1b3e60d6e645/fastlane/lib/fastlane/actions/dsym_zip.rb#L14

That seems to be pretty arbitrary, especially considering that I'm given the option to specify _where_ my dSYMs are.

**Comment by crazymanish** [comment]
Hi @tewner 

Apple always generate `dSYMs` inside `.archive` by default, that's maybe the only reason

![Screen_Recording_2021-06-13_at_18 35 12](https://user-images.githubusercontent.com/5364500/121815393-8d136d80-cc76-11eb-853d-bce029a41912.gif)

.
.
> I'm given the option to specify where my dSYMs are.

Question:  is it possible to have dSYMs files outside of the `.archive` file path? do we have such an option in `gym`? 🤔 
I don't know that how to do that? can you help, please?

**Comment by tewner** [comment]
Thank you for the super-informative response!
Ah, I see what's going on - 
It seems that I'm not taking the dSYMs from the archive. I use build_app and specify:
`            build_path: "./build/APP",
`
I then pull the dSYMs from:
build/APP/myApp.app.dSYM/Contents/Resources/DWARF/

It would be nice to be able to say "this is where I want you to look for dSYMs (without dsym_zip() opaquely adding "dSYMs"), but It looks like I'm making my own life difficult.

Thank you, @crazymanish !
