### ISSUE TITLE
http_command.rb:228:in `check_status': \e[31m[!] Invalid request\e[0m (Google::Apis::ClientError)

### ISSUE THREAD

**Issue by TheLastProject** [fastlane/fastlane#18895]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Fastlane supply crashes when trying to upload my metadata to the Google Play Store.

If it helps, the metadata is publicly available on https://github.com/TheLastProject/Catima/tree/master/fastlane.

##### Command executed
```
fastlane supply --version-code 69
```

##### Complete output when running fastlane, including the stack trace and command used

Adding `--capture_output` returned `invalid option: --capture_output` so I did without.

<details>
  <pre>[19:49:35]: [33mfastlane detected a Gemfile in the current directory[0m
[19:49:35]: [33mHowever, it seems like you didn't use `bundle exec`[0m
[19:49:35]: [33mTo launch fastlane faster, please use[0m
[19:49:35]: 
[19:49:35]: [36m$ bundle exec fastlane supply --version-code 69[0m
[19:49:35]: 
[19:49:35]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m

+---------------------------------+--------------------------------------+
|                       [32mSummary for supply 2.185.1[0m                       |
+---------------------------------+--------------------------------------+
| version_code                    | 69                                   |
| package_name                    | me.hackerchick.catima                |
| release_status                  | completed                            |
| track                           | production                           |
| metadata_path                   | ./fastlane/metadata/android          |
| json_key                        | ~/.config/google_play_service_accou  |
|                                 | nt.json                              |
| skip_upload_apk                 | false                                |
| skip_upload_aab                 | false                                |
| skip_upload_metadata            | false                                |
| skip_upload_changelogs          | false                                |
| skip_upload_images              | false                                |
| skip_upload_screenshots         | false                                |
| validate_only                   | false                                |
| check_superseded_tracks         | false                                |
| timeout                         | 300                                  |
| deactivate_on_promote           | true                                 |
| ack_bundle_installation_warning | false                                |
+---------------------------------+--------------------------------------+

[19:49:37]: Preparing to upload for language 'de-DE'...
[19:49:38]: Could not find changelog for '69' and language 'de-DE' at path ./fastlane/metadata/android/de-DE/changelogs/69.txt...
[19:49:38]: Preparing to upload for language 'en-US'...
[19:49:38]: Uploading image file ./fastlane/metadata/android/en-US/images/featureGraphic.png...
[19:49:40]: Uploading image file ./fastlane/metadata/android/en-US/images/icon.png...
[19:49:43]: Uploading screenshot ./fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot-01.png...
[19:49:45]: Uploading screenshot ./fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot-02.png...
[19:49:48]: Uploading screenshot ./fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot-03.png...
[19:49:51]: Uploading screenshot ./fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot-04.png...
[19:49:53]: Uploading screenshot ./fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot-05.png...
[19:49:56]: Uploading screenshot ./fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot-06.png...
[19:49:58]: Uploading screenshot ./fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot-07.png...
[19:50:01]: Uploading screenshot ./fastlane/metadata/android/en-US/images/phoneScreenshots/screenshot-08.png...
[19:50:03]: Could not find changelog for '69' and language 'en-US' at path ./fastlane/metadata/android/en-US/changelogs/69.txt...
[19:50:03]: Preparing to upload for language 'fi'...

Looking for related GitHub issues on fastlane/fastlane...

➡️  [33msupply issue when both native symbols and ProGuard mappings are supplied[0m
    https://github.com/fastlane/fastlane/issues/18623 [[31mopen[0m] 6 💬
    2 weeks ago

➡️  [33m"Invalid screen size" error for iPhone 12 Pro due to invalid screen size in app_screenshot.rb[0m
    https://github.com/fastlane/fastlane/issues/18244 [[32mclosed[0m] 4 💬
    6 weeks ago

➡️  [33mDELIVER (2.150.0.rc3/4) always ask attribute whatsNew[0m
    https://github.com/fastlane/fastlane/issues/16700 [[31mopen[0m] 82 💬
    2 weeks ago

and 411 more at: https://github.com/fastlane/fastlane/search?q=Invalid%20request&type=Issues&utf8=✓

/usr/share/gems/gems/google-apis-core-0.3.0/lib/google/apis/core/http_command.rb:228:in `check_status': \e[31m[!] Invalid request\e[0m (Google::Apis::ClientError)
	from /usr/share/gems/gems/google-apis-core-0.3.0/lib/google/apis/core/api_command.rb:134:in `check_status'
	from /usr/share/gems/gems/google-apis-core-0.3.0/lib/google/apis/core/http_command.rb:194:in `process_response'
	from /usr/share/gems/gems/google-apis-core-0.3.0/lib/google/apis/core/http_command.rb:310:in `execute_once'
	from /usr/share/gems/gems/google-apis-core-0.3.0/lib/google/apis/core/http_command.rb:113:in `block (2 levels) in execute'
	from /usr/local/share/gems/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
	from /usr/local/share/gems/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	from /usr/local/share/gems/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	from /usr/share/gems/gems/google-apis-core-0.3.0/lib/google/apis/core/http_command.rb:110:in `block in execute'
	from /usr/local/share/gems/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
	from /usr/local/share/gems/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	from /usr/local/share/gems/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	from /usr/share/gems/gems/google-apis-core-0.3.0/lib/google/apis/core/http_command.rb:102:in `execute'
	from /usr/share/gems/gems/google-apis-core-0.3.0/lib/google/apis/core/base_service.rb:377:in `execute_or_queue_command'
	from /usr/share/gems/gems/google-apis-androidpublisher_v3-0.6.0/lib/google/apis/androidpublisher_v3/service.rb:1028:in `get_edit_listing'
	from /home/sylvia/.gem/ruby/gems/fastlane-2.185.1/supply/lib/supply/client.rb:192:in `listing_for_language'
	from /home/sylvia/.gem/ruby/gems/fastlane-2.185.1/supply/lib/supply/uploader.rb:93:in `block (2 levels) in perform_upload_meta'
	from /home/sylvia/.gem/ruby/gems/fastlane-2.185.1/supply/lib/supply/uploader.rb:89:in `each'
	from /home/sylvia/.gem/ruby/gems/fastlane-2.185.1/supply/lib/supply/uploader.rb:89:in `block in perform_upload_meta'
	from /home/sylvia/.gem/ruby/gems/fastlane-2.185.1/supply/lib/supply/uploader.rb:81:in `each'
	from /home/sylvia/.gem/ruby/gems/fastlane-2.185.1/supply/lib/supply/uploader.rb:81:in `perform_upload_meta'
	from /home/sylvia/.gem/ruby/gems/fastlane-2.185.1/supply/lib/supply/uploader.rb:32:in `perform_upload'
	from /home/sylvia/.gem/ruby/gems/fastlane-2.185.1/supply/lib/supply/commands_generator.rb:40:in `block (2 levels) in run'
	from /home/sylvia/.gem/ruby/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /home/sylvia/.gem/ruby/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /home/sylvia/.gem/ruby/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /home/sylvia/.gem/ruby/gems/fastlane-2.185.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /home/sylvia/.gem/ruby/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /home/sylvia/.gem/ruby/gems/fastlane-2.185.1/supply/lib/supply/commands_generator.rb:61:in `run'
	from /home/sylvia/.gem/ruby/gems/fastlane-2.185.1/supply/lib/supply/commands_generator.rb:13:in `start'
	from /home/sylvia/.gem/ruby/gems/fastlane-2.185.1/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	from /home/sylvia/.gem/ruby/gems/fastlane-2.185.1/bin/fastlane:23:in `<top (required)>'
	from /home/sylvia/bin/fastlane:23:in `load'
	from /home/sylvia/bin/fastlane:23:in `<main>'
/usr/share/gems/gems/google-apis-core-0.3.0/lib/google/apis/core/http_command.rb:228:in `check_status': Invalid request (Google::Apis::ClientError)
	from /usr/share/gems/gems/google-apis-core-0.3.0/lib/google/apis/core/api_command.rb:134:in `check_status'
	from /usr/share/gems/gems/google-apis-core-0.3.0/lib/google/apis/core/http_command.rb:194:in `process_response'
	from /usr/share/gems/gems/google-apis-core-0.3.0/lib/google/apis/core/http_command.rb:310:in `execute_once'
	from /usr/share/gems/gems/google-apis-core-0.3.0/lib/google/apis/core/http_command.rb:113:in `block (2 levels) in execute'
	from /usr/local/share/gems/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
	from /usr/local/share/gems/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	from /usr/local/share/gems/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	from /usr/share/gems/gems/google-apis-core-0.3.0/lib/google/apis/core/http_command.rb:110:in `block in execute'
	from /usr/local/share/gems/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
	from /usr/local/share/gems/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	from /usr/local/share/gems/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	from /usr/share/gems/gems/google-apis-core-0.3.0/lib/google/apis/core/http_command.rb:102:in `execute'
	from /usr/share/gems/gems/google-apis-core-0.3.0/lib/google/apis/core/base_service.rb:377:in `execute_or_queue_command'
	from /usr/share/gems/gems/google-apis-androidpublisher_v3-0.6.0/lib/google/apis/androidpublisher_v3/service.rb:1028:in `get_edit_listing'
	from /home/sylvia/.gem/ruby/gems/fastlane-2.185.1/supply/lib/supply/client.rb:192:in `listing_for_language'
	from /home/sylvia/.gem/ruby/gems/fastlane-2.185.1/supply/lib/supply/uploader.rb:93:in `block (2 levels) in perform_upload_meta'
	from /home/sylvia/.gem/ruby/gems/fastlane-2.185.1/supply/lib/supply/uploader.rb:89:in `each'
	from /home/sylvia/.gem/ruby/gems/fastlane-2.185.1/supply/lib/supply/uploader.rb:89:in `block in perform_upload_meta'
	from /home/sylvia/.gem/ruby/gems/fastlane-2.185.1/supply/lib/supply/uploader.rb:81:in `each'
	from /home/sylvia/.gem/ruby/gems/fastlane-2.185.1/supply/lib/supply/uploader.rb:81:in `perform_upload_meta'
	from /home/sylvia/.gem/ruby/gems/fastlane-2.185.1/supply/lib/supply/uploader.rb:32:in `perform_upload'
	from /home/sylvia/.gem/ruby/gems/fastlane-2.185.1/supply/lib/supply/commands_generator.rb:40:in `block (2 levels) in run'
	from /home/sylvia/.gem/ruby/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /home/sylvia/.gem/ruby/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /home/sylvia/.gem/ruby/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /home/sylvia/.gem/ruby/gems/fastlane-2.185.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /home/sylvia/.gem/ruby/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /home/sylvia/.gem/ruby/gems/fastlane-2.185.1/supply/lib/supply/commands_generator.rb:61:in `run'
	from /home/sylvia/.gem/ruby/gems/fastlane-2.185.1/supply/lib/supply/commands_generator.rb:13:in `start'
	from /home/sylvia/.gem/ruby/gems/fastlane-2.185.1/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	from /home/sylvia/.gem/ruby/gems/fastlane-2.185.1/bin/fastlane:23:in `<top (required)>'
	from /home/sylvia/bin/fastlane:23:in `load'
	from /home/sylvia/bin/fastlane:23:in `<main>'
</pre>
</details>

### Environment

<details>
  <pre>[19:51:13]: [33mfastlane detected a Gemfile in the current directory[0m
[19:51:13]: [33mHowever, it seems like you didn't use `bundle exec`[0m
[19:51:13]: [33mTo launch fastlane faster, please use[0m
[19:51:13]: 
[19:51:13]: [36m$ bundle exec fastlane env[0m
[19:51:13]: 
[19:51:13]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
[19:51:13]: [33mGenerating fastlane environment output, this might take a few seconds...[0m
[19:51:13]: [31mundefined method `strip' for nil:NilClass[0m
[19:51:13]: [31mError rendering markdown table using the following text:[0m
[19:51:13]: | Key | Value |
| fastlane | 2.185.1 |
| OS | fedora Fedora release 34 (Thirty Four) |
| Ruby | 3.0.1 |
| Bundler? | false |
| Git | git version 2.31.1 |
| Installation Source | ~/bin/fastlane |
| Host | \S
Kernel \r on an \m (\l) fedora Fedora release 34 (Thirty Four) (5.12.9-300.fc34.x86_64) |
| Ruby Lib Dir | /usr/lib64 |
| OpenSSL Version | OpenSSL 1.1.1k  FIPS 25 Mar 2021 |
| Is contained | false |
| Is homebrew | false |
| Is installed via Fabric.app | false |
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key | Value |
| fastlane | 2.185.1 |
| OS | fedora Fedora release 34 (Thirty Four) |
| Ruby | 3.0.1 |
| Bundler? | false |
| Git | git version 2.31.1 |
| Installation Source | ~/bin/fastlane |
| Host | \S
Kernel \r on an \m (\l) fedora Fedora release 34 (Thirty Four) (5.12.9-300.fc34.x86_64) |
| Ruby Lib Dir | /usr/lib64 |
| OpenSSL Version | OpenSSL 1.1.1k  FIPS 25 Mar 2021 |
| Is contained | false |
| Is homebrew | false |
| Is installed via Fabric.app | false |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             | 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("~/.config/google_play_service_account.json") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("me.hackerchick.catima") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.185.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| faraday_middleware              | 1.0.0        |
| gh_inspector                    | 1.1.3        |
| rubyzip                         | 2.3.0        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| google-apis-playcustomapp_v1    | 0.3.0        |
| google-cloud-storage            | 1.31.1       |
| tsort                           | 0.1.0        |
| uri                             | 0.10.1       |
| set                             | 1.0.1        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.0.3        |
| CFPropertyList                  | 3.0.3        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.19.0       |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.7.0        |
| tty-screen                      | 0.8.1        |
| babosa                          | 1.0.4        |
| excon                           | 0.82.0       |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| ruby2_keywords                  | 0.0.4        |
| faraday-net_http_persistent     | 1.1.0        |
| faraday-net_http                | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.4.2        |
| faraday-cookie_jar              | 0.0.7        |
| fastimage                       | 2.2.4        |
| json                            | 2.5.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.15       |
| jwt                             | 2.2.3        |
| webrick                         | 1.7.0        |
| rexml                           | 3.2.5        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| signet                          | 0.15.0       |
| os                              | 1.1.1        |
| memoist                         | 0.16.2       |
| googleauth                      | 0.16.2       |
| mini_mime                       | 1.1.0        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.1        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| google-apis-core                | 0.3.0        |
| google-apis-androidpublisher_v3 | 0.6.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.4.0        |
| google-apis-storage_v1          | 0.4.0        |
| rake                            | 13.0.3       |
| digest-crc                      | 0.6.3        |
| emoji_regex                     | 3.2.2        |
| aws-eventstream                 | 1.1.1        |
| aws-sigv4                       | 1.2.3        |
| aws-partitions                  | 1.467.0      |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.114.2      |
| aws-sdk-kms                     | 1.43.0       |
| aws-sdk-s3                      | 1.96.1       |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.0        |
| date                            | 3.1.0        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.0        |
| openssl                         | 2.2.0        |
| digest                          | 3.0.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.2        |
| io-wait                         | 0.1.0        |
| zlib                            | 1.1.0        |
| resolv                          | 0.2.0        |
| securerandom                    | 0.1.0        |
| net-protocol                    | 0.1.0        |
| net-smtp                        | 0.2.1        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.0        |
| optparse                        | 0.1.0        |
| abbrev                          | 0.1.0        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.2        |
| etc                             | 1.2.0        |
| base64                          | 0.1.0        |
| time                            | 0.1.0        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| nokogiri                        | 1.11.4       |
| racc                            | 1.5.2        |
| prettyprint                     | 0.1.0        |
| pp                              | 0.1.0        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
</details>

*generated on:* **2021-06-15**
</details>
[19:51:14]: [33mTake notice that this output may contain sensitive information, or simply information that you don't want to make public.[0m
[19:51:14]: [32mOpen https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅[0m

</pre>
</details>

**Comment by bmarty** [comment]
It seems to happen if your fastlane language folder is not correct. For instance you have

> ./fastlane/metadata/android/de

and fastlane (or the PlayStore) expect the folder to be

> ./fastlane/metadata/android/de-DE

Renaming the folder worked for me.

For language you have in your folders that are not supported by the PlayStore (example `eo`), I see no other option so far than to delete the folder before running fastlane.

**Comment by TheLastProject** [comment]
I don't understand how you name that example, as I don't have a folder named `de`, it is named `de-DE`: https://github.com/TheLastProject/Catima/tree/master/fastlane/metadata/android

So, these are the folders, which I compared to https://support.google.com/googleplay/android-developer/answer/9844778?hl=en#zippy=%2Cview-list-of-available-languages:

de-DE -> Correct
en-US -> Correct
fi -> Should apparently be fi-FI
fr-FR -> Correct
it-IT -> Correct
ja -> Should apparently be ja-JP
nb-NO -> Not even listed, but still accepted
nl-NL -> Correct
ru-RU -> Correct

So, that works now, but it still seems a bug to me it just crashes likes this without more information?

**Comment by bmarty** [comment]
Sure, I did not check your project, I was just trying to give an example since I have the same issue. I'm not in the Fastlane core team FTR.

On my side, I fixed the issue here: https://github.com/vector-im/element-android/pull/3525

Also Fastlane is not happy if file short_description.txt or long_description.txt is missing. My PR fixes that too.

I agree with you @TheLastProject , Fastlane tool should be more robust, or fail more gracefully. Also it should use the default file if a translation is missing to avoid us to do some ugly workaround.

I'm happy that your problem is fixed on your project too!

**Comment by DerBasler** [comment]
I'm currently having the same issue but I don't understand is where those fastlane language folder should be located?
I am using the latest official fastlane (fastlane 2.186.0) and using it with Win10. 
I could not find any metadata folder inside the gems folder or my project. 
Do I have to make a clone of the official repo change the folders in there and build fastlane myself?

Thanks

**Comment by formatCvt** [comment]
same issue. Looks like google return an error for empty tracks

```
 % fastlane run google_play_track_version_codes track:"internal" 
[✔] 🚀 
[09:45:00]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[09:45:02]: ---------------------------------------------
[09:45:02]: --- Step: google_play_track_version_codes ---
[09:45:02]: ---------------------------------------------
[09:45:04]: Found '23' version codes in track 'internal'
[09:45:04]: Result: [23]
 % fastlane run google_play_track_version_codes track:"beta"
[✔] 🚀 
[09:45:14]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[09:45:16]: ---------------------------------------------
[09:45:16]: --- Step: google_play_track_version_codes ---
[09:45:16]: ---------------------------------------------

Looking for related GitHub issues on fastlane/fastlane...

➡️  http_command.rb:228:in `check_status': \e[31m[!] Invalid request\e[0m (Google::Apis::ClientError)
    https://github.com/fastlane/fastlane/issues/18895 [open] 4 💬
    2 weeks ago

➡️  Authentication credentials are missing or invalid. - Provide a properly configured and signed bearer token, and make sure that it has not expired
    https://github.com/fastlane/fastlane/issues/19072 [open] 7 💬
    28 minutes ago

➡️  Supply: Error 404 (Not Found) Google Api Error: Invalid request
    https://github.com/fastlane/fastlane/issues/18896 [closed] 4 💬
    3 weeks ago

```

**Comment by thanhtoan1196** [comment]
any updates?

**Comment by pke** [comment]
`google_play_track_version_codes` with invalid tracks should not throw an error but return an array with `[0]` as version code result.

**Comment by marcosrocha85** [comment]
I'm with that error when using `google_play_track_version_codes(track: "beta")`. I created an empty Fastlane project and just calling the function gives that error.
