### ISSUE TITLE
Supply: Error 404 (Not Found) Google Api Error: Invalid request

### ISSUE THREAD

**Issue by zekapp** [fastlane/fastlane#18896]
I am having the below error while uploading the APK to PlayStore by using the supply command. 

```
Google Api Error: Invalid request - <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  **<a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/androidpublisher/v2/applications/{packageName}/edits?</code> was not found on this** server.  <ins>That’s all we know.</ins>
```

Here is my setup for the supply command
```
+-------------------------+----------------------------------------------------------------------------------------+
|                                            Summary for supply 2.123.0                                            |
+-------------------------+----------------------------------------------------------------------------------------+
| track                   | alpha                                                                                  |
| skip_upload_metadata    | true                                                                                   |
| skip_upload_images      | true                                                                                   |
| skip_upload_screenshots | true                                                                                   |
| validate_only           | false                                                                                  |
| apk                     | {pathToApk}                                                                            |
| package_name            | {packageName}                                                                          |
| metadata_path           | ./fastlane/metadata/android                                                            |
| json_key                | ./google-key.json                                                                      |
| skip_upload_apk         | false                                                                                  |
| skip_upload_aab         | false                                                                                  |
| check_superseded_tracks | false                                                                                  |
| timeout                 | 300                                                                                    |
| deactivate_on_promote   | true                                                                                   |
+-------------------------+----------------------------------------------------------------------------------------+
```

**Comment by zekapp** [comment]
### Stack
| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.7                                     |
| Ruby                        | 2.6.5                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.29.2                          |
| Installation Source         | ~/.rbenv/versions/2.6.5/bin/fastlane        |
| Host                        | Mac OS X 10.15.7 (19H2)                     |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.5/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1h  22 Sep 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.3                                        |
### System Locale
| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |
### fastlane files:
<details><summary>`./fastlane/Fastfile`</summary>
```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command
# If you want to automatically update fastlane if a new version is available:
#update_fastlane
fastlane_version "2.38.1"
default_platform :android
platform :android do
    desc "Deploy a new version to the Google Play"
    lane :release do
    gradle(task: "")
    gradle(task: "") // build APK
    supply(
        track: "alpha",
        #rollout: 0.5,
        skip_upload_metadata: true,
        skip_upload_images: true,
        skip_upload_screenshots: true,
        validate_only: false
    )
    post_to_slack_no_payload(
        message: getPvtSlackMessage("App Center"),
        channel: "mobilesquad_bots"
    )
    end
end
```
</details>
<details><summary>`./fastlane/Appfile`</summary>
```ruby
# Path to the jason secret file, by using a relative path it means fastlane can only be run from the project root directory
json_key_file ""
package_name ""
```
</details>
### fastlane gems
| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.166.0 | 🚫 Update available |
### Loaded fastlane plugins:
| Plugin                           | Version | Update-Status |
| -------------------------------- | ------- | ------------- |
| fastlane-plugin-get_version_code | 0.2.0   | ✅ Up-To-Date  |
| fastlane-plugin-appcenter        | 1.11.1  | ✅ Up-To-Date  |
| fastlane-plugin-badge            | 1.5.0   | ✅ Up-To-Date  |
<details><summary><b>Loaded gems</b></summary>
| Gem                              | Version      |
| -------------------------------- | ------------ |
| did_you_mean                     | 1.3.0        |
| slack-notifier                   | 2.3.2        |
| atomos                           | 0.1.3        |
| CFPropertyList                   | 3.0.3        |
| claide                           | 1.0.3        |
| colored2                         | 3.1.2        |
| nanaimo                          | 0.3.0        |
| xcodeproj                        | 1.19.0       |
| rouge                            | 2.0.7        |
| xcpretty                         | 0.3.0        |
| terminal-notifier                | 2.0.0        |
| unicode-display_width            | 1.7.0        |
| terminal-table                   | 1.8.0        |
| plist                            | 3.5.0        |
| public_suffix                    | 4.0.6        |
| addressable                      | 2.7.0        |
| multipart-post                   | 2.0.0        |
| word_wrap                        | 1.0.0        |
| tty-screen                       | 0.8.1        |
| tty-cursor                       | 0.7.1        |
| tty-spinner                      | 0.9.3        |
| babosa                           | 1.0.4        |
| colored                          | 1.2          |
| highline                         | 1.7.10       |
| commander-fastlane               | 4.4.6        |
| excon                            | 0.78.1       |
| ruby2_keywords                   | 0.0.2        |
| faraday                          | 1.1.0        |
| unf_ext                          | 0.0.7.7      |
| unf                              | 0.1.4        |
| domain_name                      | 0.5.20190701 |
| http-cookie                      | 1.0.3        |
| faraday-cookie_jar               | 0.0.7        |
| faraday_middleware               | 1.0.0        |
| fastimage                        | 2.2.0        |
| gh_inspector                     | 1.1.3        |
| json                             | 2.1.0        |
| mini_magick                      | 4.11.0       |
| rubyzip                          | 2.3.0        |
| security                         | 0.1.3        |
| xcpretty-travis-formatter        | 1.0.0        |
| dotenv                           | 2.7.6        |
| bundler                          | 1.17.2       |
| naturally                        | 2.2.0        |
| simctl                           | 1.6.8        |
| jwt                              | 2.2.2        |
| uber                             | 0.1.0        |
| declarative                      | 0.0.20       |
| declarative-option               | 0.1.0        |
| representable                    | 3.0.4        |
| retriable                        | 3.1.2        |
| mini_mime                        | 1.0.2        |
| multi_json                       | 1.15.0       |
| signet                           | 0.14.0       |
| memoist                          | 0.16.2       |
| os                               | 1.1.1        |
| googleauth                       | 0.14.0       |
| httpclient                       | 2.8.3        |
| google-api-client                | 0.38.0       |
| google-cloud-env                 | 1.4.0        |
| google-cloud-errors              | 1.0.1        |
| google-cloud-core                | 1.5.0        |
| rake                             | 12.3.2       |
| digest-crc                       | 0.6.2        |
| google-cloud-storage             | 1.29.1       |
| emoji_regex                      | 3.2.1        |
| jmespath                         | 1.4.0        |
| aws-partitions                   | 1.404.0      |
| aws-eventstream                  | 1.1.0        |
| aws-sigv4                        | 1.2.2        |
| aws-sdk-core                     | 3.110.0      |
| aws-sdk-kms                      | 1.39.0       |
| aws-sdk-s3                       | 1.86.0       |
| forwardable                      | 1.2.0        |
| logger                           | 1.3.0        |
| stringio                         | 0.0.2        |
| ipaddr                           | 1.2.2        |
| openssl                          | 2.1.2        |
| ostruct                          | 0.1.0        |
| strscan                          | 1.0.0        |
| date                             | 2.0.0        |
| fileutils                        | 1.1.0        |
| etc                              | 1.0.1        |
| zlib                             | 1.0.0        |
| racc                             | 1.5.2        |
| nokogiri                         | 1.11.1       |
| rexml                            | 3.1.9        |
| psych                            | 3.1.0        |
| mutex_m                          | 0.1.0        |
| webrick                          | 1.4.2        |
| fastlane-plugin-get_version_code | 0.2.0        |
| fastlane-plugin-appcenter        | 1.11.1       |
| csv                              | 3.0.9        |
| badge                            | 0.13.0       |
| fastlane-plugin-badge            | 1.5.0        |
</details>

**Comment by lucgrabowski** [comment]
Hi @zekapp, it seems that you try to use very old version of supply tool (Android Publisher v2 API is not supported anymore). 
Please update to the newest fastlane version.
You can read more in https://github.com/fastlane/fastlane/issues/14573

**Comment by ainame** [comment]
Yes. Please try the latest one. 
We've migrated the SDK of Google's APIs in #18656 lately, which should work for you.
