### ISSUE TITLE
[app_store_build_number/maybe others?] Redundant App Store Token request

### ISSUE THREAD

**Issue by dtorres** [fastlane/fastlane#18899]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

In one of our lanes, we use app_store_build_number several times (in essence, to synchronize build numbers across several targets) and I noticed that an App Store Connect Token was requested each time.

The offending code seems to be here, where it will create a token if the credentials are provided, regardless if there was a token already. https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/app_store_build_number.rb#L30  

I'm using the following helper, called before the Lane starts to work around this:
```ruby
def create_token_once_if_possible
  key = Fastlane::Actions.lane_context[Fastlane::Actions::SharedValues::APP_STORE_CONNECT_API_KEY]
  return if key.nil? 
  if (api_token = Spaceship::ConnectAPI::Token.from(hash: key))
    UI.message("Creating authorization token for App Store Connect API")
    Spaceship::ConnectAPI.token = api_token
    Fastlane::Actions.lane_context.set_sensitive(SharedValues::APP_STORE_CONNECT_API_KEY, nil)
  end
end
```

Maybe this is by design but I can't find anything saying so

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by Everett121** [comment]
I like seeing blog that understand the value of providing a quality resource for free.

<a href="https://www.omegle.kim/">omegle</a>
