### ISSUE TITLE
create_keychain broken

### ISSUE THREAD

**Issue by bukira** [fastlane/fastlane#18892]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information
- Breaking version: [2.185.1 ]
- Last working version: [2.185.10]

### Regression Description
The change in the version changed the options from:

- is_string is slowly being replaced by type to make the docs clearer, options safer, and Swift generation more correct.

How ever in create_keychain this affected the timeout value, as per the DOCS:

timeout | timeout interval in seconds. Set&nbsp;false&nbsp;if you want to specify "no time-out" | 300
-- | -- | --

How ever timeout is now an Int NOT a Bool so you CANNOT set it to "false" anymore

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.4                                                           |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.31.1                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.4 (20F71)                                             |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.5                                                           |
| Swift Version               | 5.4                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

**Comment by bukira** [comment]
setting the timeout to an Int (3600) etc fixed the issue how ever that's not what the documentation says you can do

**Comment by crazymanish** [comment]
Hello @bukira 
I think, I broke it in the last release...working on it right away 👍

**Comment by bukira** [comment]
Yes you did, no problem, for now im sending an Int that's big enough for my use (Bitrise)  :-)

**Comment by crazymanish** [comment]
> Yes you did, no problem, for now im sending an Int that's big enough for my use (Bitrise) :-)

Nice, so we already have `workaround` <--> passing a big enough integer number for the timeout param.
btw, just now, open the PR to fix this regression issue: https://github.com/fastlane/fastlane/pull/18894

Thank you very much for reporting this issue! 🙏
