### ISSUE TITLE
fastlane init fails, missing company name, creating first app in app store connect

### ISSUE THREAD

**Issue by ryanhanks** [fastlane/fastlane#18915]
https://github.com/fastlane/fastlane/issues/16759 and https://github.com/fastlane/fastlane/issues/15252 fully document the issue as I'm experiencing it. Both these were closed by the bot, but are still a reproducible issue.

TL;DR, `fastlane init` fails on creating the app in AppStore Connect. I'm not sure the scenario under which it actually works.

Is `fastlane init` no longer supported for iOS?

Looks like the error might be somewhere near https://github.com/fastlane/fastlane/blob/e9b79e422b5161fdae9309ed60872288ae5cb583/spaceship/lib/spaceship/portal/portal_client.rb#L202. It doesn't look like anyone has touched much in that file in few years.

@joshdholtz since you're listed as the lead maintainer of this project, and the previous issue went unnoticed by anyone on the team, I'd like to bring this to your attention. I understand you might not be the most knowledgable dev on the team in this area, but maybe you know of someone who can help. Thanks.

**Comment by lucgrabowski** [comment]
Hi @ryanhanks, do you try to create your first app on Appstore Connect account?  If that's the case, you need to pass `company_name` which will be used as developer name on AppStore (the one below the name of the app on app's page) - it is required only when creating first app. You can set it with`PRODUCE_COMPANY_NAME` env variable:
`PRODUCE_COMPANY_NAME="YOUR COMPANY NAME" fastlane init`

**Comment by ryanhanks** [comment]
Thanks @lucgrabowski, I'll give that a try today and report back.

**Comment by lucgrabowski** [comment]
I've opened PRs to add this information in getting-started docs: https://github.com/fastlane/docs/pull/1066 and `create_app_online` action docs: https://github.com/fastlane/fastlane/pull/18934

**Comment by crazymanish** [comment]
PR #18934 is merged so closing this issue! Thank you @lucgrabowski
