### ISSUE TITLE
Upload tvOS builds

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1891]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/1849419?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @notbenoit - Imported from <a href='https://github.com/fastlane/pilot/issues/92'>fastlane/pilot#92</a>
        </td>
      </tr>
    </table>

Sorry this is a duplicate...https://github.com/fastlane/pilot/issues/55  :( My bad! Feel free to close this useless duplicate.

-----
First, thanks for the amazing toolchain! 

My issue here, is that I cannot upload an IPA to ITC using pilot (or any similar tool, even altool fails). Only *Application Loader* worked. But I need command line upload. The error here is : 
```
ERROR ITMS-90545: "Invalid Provisioning Profile. This provisioning profile is not compatible with iOS apps."
```

But, I investigated, and found that the default package sent from altool looks like that :
```
<package version="software5.3" xmlns="http://apple.com/itunes/importer">
    <software_assets apple_id="#APPLE_APP_ID#"
        bundle_short_version_string="0.1"
        bundle_version="151201105028"
        bundle_identifier="#BUNDLE_IDENTIFIER#"
        app_platform="ios">
        <asset type="bundle">
            <data_file>
                <file_name>#IPA_NAME#</file_name>
                <checksum type="md5">a97130dc797045444e1d422255611afb</checksum>
                <size>21210100</size>
            </data_file>
        </asset>
    </software_assets>
</package>
```
(I removed app specific data).

Here note **app_platform="ios"**. This is where is the magic. I made my own itmsp package with `appletvos` instead of `ios` parameter, and managed to upload the IPA !

Since I have nearly zero knowledge about how `pilot` works, do you have any idea how we could add a parameter, or detect the target, to have this `appletvos` set in the sent XML ?

EDIT : The only things needed to successfully upload a tvOS build are **packageVersion** at `5.3` and **app_platform** with `appletvos`. No need for the bundle(s) stuff.

**Comment by aresundnes** [comment]
Any update on this? Im still getting ```This provisioning profile is not compatible with iOS apps.```when building with gym and submitting with deliver to tvOS

**Comment by TKBurner** [comment]
@aresundnes Thanks for following up on this. Can you create a new issue if you are running into this still? Thanks!
