### ISSUE TITLE
Undisclosed breaking change in create_keychain in minor version 2.185.1

### ISSUE THREAD

**Issue by vrouet** [fastlane/fastlane#18936]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: 2.185.1
- Last working version: 2.185.0

### Regression Description
Up until now, we used the following code to create a temporary keychain for our iOS build process:
```
create_keychain(
      name: name,
      password: 'temppassword',
      unlock: true,
      timeout: false
)
```
This `false` boolean value for the `timeout` argument is actually still listed as a valid value in the doc (https://docs.fastlane.tools/actions/create_keychain/)

The thing is, with the changes in type validation from the last minor release, this is not working anymore, as only Integer values are allowed.

I'd argue that such a change should not have made it to a minor release in the first place, but even more problematic is having it not listed anywhere else than in the actual commit where it was changed (https://github.com/fastlane/fastlane/commit/e5f3371d59f1dacf55bec11078e9ad6c8924d764).

Anyways, just letting you know so you can make sure people running into this issue can easily find the info, as this took me a while to figure out, it doesn't seem to have been reported elsewhere yet.

**Comment by singhravi1** [comment]
Can confirm this.
Fastlane 2.185.1 broke builds for **many** of our projects due to required integer value of `timeout`.
Moreover, It took a while to debug this due to confusion from the wrong description in the documentation.

**Comment by lucgrabowski** [comment]
It happens. There are 2 ways of dealing with it for now:
- you could temporarily use an older version of Fastlane before a fix is released
- use a workaround described in comments of https://github.com/fastlane/fastlane/issues/18892 (It has a linked PR that is pending review with a fix for `create_keychain`)

And please remember it's an open source project, people are improving the tool in their free time.

**Comment by vrouet** [comment]
Oh so there actually was an open issue already, I somehow missed it, sorry about that.

Of course I am fully aware of the open source nature of the project and my opening of the issue was not aimed at blaming anyone. And, truth be told, we should always use fixed versions in our gemfile so surprises can't happen ;)

That said, my point was more that it would probably be a good idea to have this breaking change part of the release notes somewhere - with a "will be fixed in next release" comment, or something. But that's up to you guys and depending on the timeline for next release it might actually not affect many more people.

**Comment by crazymanish** [comment]
Thank you @lucgrabowski ❤️ 

Dear @vrouet 
FYI, Fastlane team decided that `timeout` should allow the **only integer** which makes sense and will be consistent with others platforms, and of course, it will be much better for Fastlane's Swift generated code too.
You have now two choices, 
- either use `timeout: 0` for no timeout or 
- use big integer number `timeout: 360000`

Please free to review PR if you think there is anything missing. Thank you.

cc:  @joshdholtz @minuscorp

**Comment by singhravi1** [comment]
Thank you @crazymanish !
I can see the PR is still open. So `timeout` as 0 would work in later upcoming fastlane release, right?
For now, we can still use a sufficiently large number for timeout?

Thanks to everyone for this feature rich tool btw :)

**Comment by crazymanish** [comment]
> Thank you @crazymanish !
> I can see the PR is still open. So `timeout` as 0 would work in upcoming fastlane release, right?

YES 
> For now, we can still use a sufficiently large number for timeout?

YES
> Thanks to everyone for this feature rich tool btw :)

Hi, @singhravi1 You are 💯  right! Thank you guys for your patience!

**Comment by crazymanish** [comment]
PR https://github.com/fastlane/fastlane/pull/18894 is merged! 🎉 
Docs will update once this PR will be released, You will have now two choices:
- either use `timeout: 0` for no timeout or
- use big integer number `timeout: 360000`
