### ISSUE TITLE
Fastlane install failing when using Xcode 13.0 beta 1

### ISSUE THREAD

**Issue by chrisvasselli** [fastlane/fastlane#18931]
If I use xcode-select to switch to the Xcode 13.0 beta, and then attempt to install fastlane using `bundle install`, I get an error:

`An error occurred while installing unf_ext (0.0.7.7), and Bundler cannot continue.`

Switching back to Xcode 12.5 (and deleting the vendor folder), fastlane installs correctly. Targeting fastlane 2.185.1. 

I tried installing the command line tools (via `xcode-select --install`), and I tried moving Xcode-beta.app to Xcode.app, and neither seemed to fix the issue.

**Gemfile**
```
source "https://rubygems.org"

gem "fastlane", ">= 2.150.rc4"
```

**Fastlane Env (from fastlane built with Xcode 12.5, so some of this might not be relevant/correct for this problem)**
[fastlane-env.txt](https://github.com/fastlane/fastlane/files/6683374/fastlane-env.txt)

**Generated Files**
[gem_make.out.txt](https://github.com/fastlane/fastlane/files/6683350/gem_make.out.txt)
[mkmf.log](https://github.com/fastlane/fastlane/files/6683351/mkmf.log)

**Output**
```
chris@Ultros StudyJapanese % sudo xcode-select -s /Applications/Xcode-beta.app 
chris@Ultros StudyJapanese % bundle install                                   
Fetching gem metadata from https://rubygems.org/.........
Fetching rake 13.0.3
Installing rake 13.0.3
Fetching CFPropertyList 3.0.3
Installing CFPropertyList 3.0.3
Fetching public_suffix 4.0.6
Installing public_suffix 4.0.6
Fetching addressable 2.7.0
Installing addressable 2.7.0
Fetching artifactory 3.0.15
Installing artifactory 3.0.15
Fetching atomos 0.1.3
Installing atomos 0.1.3
Fetching aws-eventstream 1.1.1
Installing aws-eventstream 1.1.1
Fetching aws-partitions 1.469.0
Installing aws-partitions 1.469.0
Fetching aws-sigv4 1.2.3
Installing aws-sigv4 1.2.3
Fetching jmespath 1.4.0
Installing jmespath 1.4.0
Fetching aws-sdk-core 3.114.3
Installing aws-sdk-core 3.114.3
Fetching aws-sdk-kms 1.44.0
Installing aws-sdk-kms 1.44.0
Fetching aws-sdk-s3 1.96.1
Installing aws-sdk-s3 1.96.1
Fetching babosa 1.0.4
Installing babosa 1.0.4
Using bundler 2.1.4
Fetching claide 1.0.3
Installing claide 1.0.3
Fetching colored 1.2
Installing colored 1.2
Fetching colored2 3.1.2
Installing colored2 3.1.2
Fetching highline 2.0.3
Installing highline 2.0.3
Fetching commander 4.6.0
Installing commander 4.6.0
Fetching declarative 0.0.20
Installing declarative 0.0.20
Fetching digest-crc 0.6.3
Installing digest-crc 0.6.3 with native extensions
Fetching unf_ext 0.0.7.7
Installing unf_ext 0.0.7.7 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/chris/Code/SerpentiSei/StudyJapanese/vendor/bundle/ruby/2.6.0/gems/unf_ext-0.0.7.7/ext/unf_ext
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20210620-7173-zo4c4p.rb extconf.rb
checking for -lstdc++... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/$(RUBY_BASE_NAME)
	--with-static-libstdc++
	--without-static-libstdc++
	--with-stdc++lib
	--without-stdc++lib
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to
generate an executable file. (RuntimeError)
You have to install development tools first.
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:546:in `block in try_link0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:543:in `try_link0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:570:in `try_link'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:789:in `try_func'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:1016:in `block in have_library'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:959:in `block in checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:361:in `block (2 levels) in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:331:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:361:in `block in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:331:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:357:in `postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:958:in `checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:1011:in `have_library'
	from extconf.rb:6:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

/Users/chris/Code/SerpentiSei/StudyJapanese/vendor/bundle/ruby/2.6.0/extensions/universal-darwin-20/2.6.0/unf_ext-0.0.7.7/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/chris/Code/SerpentiSei/StudyJapanese/vendor/bundle/ruby/2.6.0/gems/unf_ext-0.0.7.7
for inspection.
Results logged to
/Users/chris/Code/SerpentiSei/StudyJapanese/vendor/bundle/ruby/2.6.0/extensions/universal-darwin-20/2.6.0/unf_ext-0.0.7.7/gem_make.out

An error occurred while installing unf_ext (0.0.7.7), and Bundler cannot continue.
Make sure that `gem install unf_ext -v '0.0.7.7' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  fastlane was resolved to 2.185.1, which depends on
    faraday-cookie_jar was resolved to 0.0.7, which depends on
      http-cookie was resolved to 1.0.4, which depends on
        domain_name was resolved to 0.5.20190701, which depends on
          unf was resolved to 0.1.4, which depends on
            unf_ext
```

**Comment by crazymanish** [comment]
Hi @chrisvasselli 


> An error occurred while installing unf_ext (0.0.7.7), and Bundler cannot continue.
Make sure that `gem install unf_ext -v '0.0.7.7' --source 'https://rubygems.org/'` succeeds before bundling.

Can you try once suggested command the `gem install unf_ext -v '0.0.7.7'` and then I request you to make your Gemfile very simple

source "https://rubygems.org"
gem "fastlane"

**Comment by lucgrabowski** [comment]
Hi, errors like this happen when there is a mismatch between Xcode version and Command line tools selected in Xcode - Preferences - Locations tab. Also, in `mkmf.log` Xcode.app appears in logs instead of Xcode-beta.app, so I would recommend taking a look at Xcode preferences and also verifying which Xcode is used (` xcode-select -p`).

**Comment by chrisvasselli** [comment]
@crazymanish  @lucgrabowski Thanks for the quick responses!

Apologies for the confusion with mkmf.log. I probably grabbed it after my attempt to fix the problem by renaming Xcode-beta.app to Xcode.app. When I run it again, mkmf.log looks the same but referring to Xcode-beta.app.

I tried changing the command line tools location selected in Xcode - Preferences - Locations to make sure it is pointing at Xcode-beta.app, and am seeing the same output. I have also simplified my Gemfile to exactly as suggested. Same problem.

I tried running `sudo gem install unf_ext -v '0.0.7.7 --source 'https://rubygems.org/'` and get very similar output. I have attached it below.

[mkmf.log](https://github.com/fastlane/fastlane/files/6687020/mkmf.log)
[gem_make.out.txt](https://github.com/fastlane/fastlane/files/6687021/gem_make.out.txt)
[command-out.txt](https://github.com/fastlane/fastlane/files/6687022/command-out.txt)

**Comment by crazymanish** [comment]
Hi @chrisvasselli 
Indeed, `command-out.txt` is showing that something is wrong with your ruby Gem dependency, nothing related to Fastlane gem. btw, why are you running `sudo` ? I highly recommend you to setup your ruby with rbenv https://github.com/rbenv/rbenv

after that, you dont need sudo command anymore and all ruby gem dependency should be resolved automatically :)
i.e running `gem install unf_ext -v '0.0.7.7` will be enough

<img width="1004" alt="Screenshot 2021-06-21 at 16 00 24" src="https://user-images.githubusercontent.com/5364500/122774989-f95f2400-d2a9-11eb-82d3-a656b452fc41.png">

**Comment by chrisvasselli** [comment]
@crazymanish thanks! Setting up rbenv seemed to fix the issue. 

I usually don't use sudo to install gems, I use bundler to install locally. Up until Xcode 13, this seemed to work fine without rubyenv, so I wonder if others who don't have rubyenv setup will run into this issue. I don't use ruby a whole lot, so I think when I was setting things up, and bundler worked to install fastlane without sudo, I just stopped there and didn't bother setting up rbenv.

My gut sense is there still might be something different about installing with Xcode 13 here that others might run into? But I'm happy to close this if you feel like "use rbenv" is a sufficient answer.

**Comment by crazymanish** [comment]
Good to know, Issue has been fixed!

I can ensure you that it was a ruby setup issue, `system Ruby` always causes such issues. nothing related to Xcode13 
(You are just lucky that you got this issue after Xcode13 but with `system Ruby` such issue can happen any day, any Xcode 😉 )

Fastlane docs already recommend that **always setup Ruby using rbenv** 
https://docs.fastlane.tools/

<img width="1260" alt="Screenshot 2021-06-22 at 07 27 47" src="https://user-images.githubusercontent.com/5364500/122869013-edb44180-d32b-11eb-9d13-48082029c2b0.png">

**Comment by chrisvasselli** [comment]
@crazymanish thanks for taking the time to walk me through that!
