### ISSUE TITLE
Submitting Changelog with Pilot didn't work

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1894]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/343450?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @squarefrog - Imported from <a href='https://github.com/fastlane/pilot/issues/86'>fastlane/pilot#86</a>
        </td>
      </tr>
    </table>

I've just submitted a new beta update using `pilot`, and I've noticed my change log string did not get submitted. I've not changed our `fastfile` since the last successful upload about a month ago, which did upload the change log.

I'm not sure if this is a one-time issue, or a regression due to iTunes Connect changes, but I'm leaving this issue open until I have another beta update to push out.

**Comment by urimagisto** [comment]
I am facing the same pilot issue for not being able to upload the changelog into "What to test" field, however when manually adding in ITC site i am able to see it reflected in testFlight app via my mobile(after the build is already uploaded). Is there anyone who managed to solve it?

I am using:
pilot 1.5.0
Xcode 7.3
EL capitan 10.11.4

**Comment by vpolouchkine** [comment]
@urimagisto Can you please format your comment per https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md? Thanks! That will help to debug this.

**Comment by urimagisto** [comment]
Thanks @vpolouchkine

https://github.com/fastlane/fastlane/issues/4444

**Comment by vpolouchkine** [comment]
Closing in favor of https://github.com/fastlane/fastlane/issues/4444
