### ISSUE TITLE
'app' value must be a Integer! Found String instead.

### ISSUE THREAD

**Issue by nele-llama** [fastlane/fastlane#18966]
After update from 2.185.1 to 2.186.0 i am getting `'app' value must be a Integer! Found String instead.` when running deliver:

DEBUG [2021-06-24 16:44:16.50]: All plugins are up to date
ERROR [2021-06-24 16:44:16.50]: fastlane finished with errors
DEBUG [2021-06-24 16:44:16.50]: All plugins are up to date
bundler: failed to load command: fastlane (/Users/me/.rbenv/versions/2.6.6/bin/fastlane)
FastlaneCore::Interface::FastlaneError: [!] 'app' value must be a Integer! Found String instead.
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane_core/lib/fastlane_core/configuration/config_item.rb:204:in `ensure_generic_type_passes_validation'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane_core/lib/fastlane_core/configuration/config_item.rb:242:in `valid?'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane_core/lib/fastlane_core/configuration/config_item.rb:195:in `verify!'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane_core/lib/fastlane_core/configuration/config_item.rb:261:in `block in fetch_env_value'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane_core/lib/fastlane_core/configuration/config_item.rb:258:in `each'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane_core/lib/fastlane_core/configuration/config_item.rb:258:in `fetch_env_value'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:222:in `fetch'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:290:in `block in values'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:289:in `each'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane_core/lib/fastlane_core/configuration/configuration.rb:289:in `values'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane_core/lib/fastlane_core/print_table.rb:22:in `print_values'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/deliver/lib/deliver/runner.rb:25:in `initialize'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:22:in `new'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:22:in `run'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:65:in `block (2 levels) in parsing_binding'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:15:in `block (2 levels) in parsing_binding'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
  /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.186.0/bin/fastlane:23:in `<top (required)>'
  /Users/me/.rbenv/versions/2.6.6/bin/fastlane:23:in `load'
  /Users/me/.rbenv/versions/2.6.6/bin/fastlane:23:in `<top (required)>'

**Comment by nele-llama** [comment]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.4                                        |
| Ruby                        | 2.6.6                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.30.1 (Apple Git-130)          |
| Installation Source         | ~/.rbenv/versions/2.6.6/bin/fastlane        |
| Host                        | macOS 11.4 (20F71)                          |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.6/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.5.1                                      |
| Swift Version               | 5.4.2                                       |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform(:ios)

platform :ios do

  before_all do
    sh('bundle update')
  end

  # # # # # # # # # 
  # PUBLIC LANES  #
  # # # # # # # # #

  desc 'Upload new release candidate build to App Store Connect.'
  lane :release do
    upload_to_asc
  end

  desc 'Upload new beta build to App Distribution.'
  lane :release_beta do
    upload_to_firebase
  end

  desc 'Setup all certificates and provisioning profiles.'
  lane :setup_profiles do |options|
    development_profiles
    adhoc_profiles
    appstore_profiles
  end

  lane :development_profiles do
    match(type:             'development',  
          app_identifier:   ENV['BUNDLE_ID'] + 'Beta')
  end

  lane :appstore_profiles do
    match(type:             'appstore',  
          app_identifier:   ENV['BUNDLE_ID'])
  end 

  lane :adhoc_profiles do
    match(type:           'adhoc',
          app_identifier: ENV['BUNDLE_ID'] + 'Beta')
  end

  desc 'Fetch and upload dSYM files to Firebase Crashlytics'
  lane :refresh_admiral_dsyms do
    FileUtils.mkdir_p '../build'
    download_dsyms(app_identifier: ENV['BUNDLE_ID'],
                                  output_directory: './build',
                                  version: 'latest')   
    upload_symbols_to_crashlytics(gsp_path: './XXXXX/GoogleService-Info.plist') 
    delete_build_dir
  end

  # # # # # # # # # 
  # PRIVATE LANES #
  # # # # # # # # #

  private_lane :upload_to_asc do
    appstore_profiles
    increment_build_number
    gym(export_method: 'app-store',
        scheme:         'XXXXXX',
        configuration:  'Release')
    deliver(force:            true,
            skip_metadata:    true,
            skip_screenshots: true )
    upload_symbols_to_crashlytics(gsp_path: './XXXXX/GoogleService-Info.plist',
                                  dsym_path: './build/XXXXX.app.dSYM.zip')
    send_slack_notification(beta: false)
    delete_build_dir
  end

  private_lane :upload_to_firebase do
    sh('bundle exec fastlane update_plugins')
    sh('curl -sL firebase.tools | upgrade=true bash')
    adhoc_profiles
    increment_build_number
    gym(export_method:  'ad-hoc',
        scheme:         'XXXXX',
        configuration:  'ReleaseBeta')
    firebase_app_distribution(googleservice_info_plist_path: 'BetaGoogleService-Info.plist',
                              ipa_path: './build/XXXXX.ipa',
                              groups: 'XXXXX',
                              release_notes: get_changelog)
    upload_symbols_to_crashlytics(gsp_path: './XXXXX/BetaGoogleService-Info.plist',
                                  dsym_path: './build/XXXXX.app.dSYM.zip')
    send_slack_notification(beta: true)
    delete_build_dir
  end

  private_lane :get_changelog do 
      changelog = last_git_commit[:message]
  end

  private_lane :send_slack_notification do |options|
    version = get_info_plist_value(key: 'CFBundleShortVersionString', path: './XXXXX/Info.plist')
    build = get_info_plist_value(key: 'CFBundleVersion', path: './XXXXX/Info.plist')
    if options[:beta]==true
      message = 'New iOS build v' + version + ' #' + build + ' for XXXXX uploaded to App Distribution.'
      slack(message: message)
    else
      message = 'New iOS build v' + version + ' #' + build + ' for XXXXX uploaded to TestFlight.'
      slack(message: message)
    end
  end

  private_lane :delete_build_dir do
    UI.message 'Delete build directory and downloaded profile'
    Dir.chdir('..') do
      FileUtils.remove_dir('./build', force = true)
      FileUtils.rm_r Dir.glob('./*.mobileprovision')
    end
  end
end

```
</details>

**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.186.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.2.9   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.3.0        |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.7.0        |
| terminal-table                            | 1.8.0        |
| public_suffix                             | 4.0.6        |
| addressable                               | 2.7.0        |
| multipart-post                            | 2.0.0        |
| word_wrap                                 | 1.0.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| artifactory                               | 3.0.15       |
| colored                                   | 1.2          |
| highline                                  | 2.0.3        |
| commander                                 | 4.6.0        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.0.0        |
| gh_inspector                              | 1.1.3        |
| rubyzip                                   | 2.3.0        |
| security                                  | 0.1.3        |
| dotenv                                    | 2.7.6        |
| bundler                                   | 2.1.4        |
| simctl                                    | 1.6.8        |
| google-apis-playcustomapp_v1              | 0.3.0        |
| google-apis-androidpublisher_v3           | 0.6.0        |
| nanaimo                                   | 0.3.0        |
| colored2                                  | 3.1.2        |
| claide                                    | 1.0.3        |
| CFPropertyList                            | 3.0.3        |
| atomos                                    | 0.1.3        |
| xcodeproj                                 | 1.19.0       |
| plist                                     | 3.6.0        |
| babosa                                    | 1.0.4        |
| excon                                     | 0.82.0       |
| ruby2_keywords                            | 0.0.4        |
| faraday-net_http_persistent               | 1.1.0        |
| faraday-net_http                          | 1.0.1        |
| faraday-excon                             | 1.1.0        |
| faraday-em_synchrony                      | 1.0.0        |
| faraday-em_http                           | 1.0.0        |
| faraday                                   | 1.4.2        |
| unf_ext                                   | 0.0.7.7      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| http-cookie                               | 1.0.4        |
| fastimage                                 | 2.2.4        |
| json                                      | 2.5.1        |
| mini_magick                               | 4.11.0       |
| naturally                                 | 2.2.1        |
| xcpretty-travis-formatter                 | 1.0.1        |
| jwt                                       | 2.2.3        |
| webrick                                   | 1.7.0        |
| rexml                                     | 3.2.5        |
| httpclient                                | 2.8.3        |
| multi_json                                | 1.15.0       |
| signet                                    | 0.15.0       |
| os                                        | 1.1.1        |
| memoist                                   | 0.16.2       |
| googleauth                                | 0.16.2       |
| mini_mime                                 | 1.1.0        |
| retriable                                 | 3.1.2        |
| trailblazer-option                        | 0.1.1        |
| declarative                               | 0.0.20       |
| uber                                      | 0.1.0        |
| representable                             | 3.1.1        |
| google-apis-core                          | 0.3.0        |
| rake                                      | 13.0.3       |
| digest-crc                                | 0.6.3        |
| google-apis-storage_v1                    | 0.4.0        |
| google-apis-iamcredentials_v1             | 0.4.0        |
| google-cloud-errors                       | 1.1.0        |
| google-cloud-env                          | 1.5.0        |
| google-cloud-core                         | 1.6.0        |
| google-cloud-storage                      | 1.32.0       |
| emoji_regex                               | 3.2.2        |
| aws-eventstream                           | 1.1.1        |
| aws-sigv4                                 | 1.2.3        |
| aws-partitions                            | 1.470.0      |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.115.0      |
| aws-sdk-kms                               | 1.44.0       |
| aws-sdk-s3                                | 1.96.1       |
| forwardable                               | 1.2.0        |
| logger                                    | 1.3.0        |
| date                                      | 2.0.0        |
| stringio                                  | 0.0.2        |
| ipaddr                                    | 1.2.2        |
| openssl                                   | 2.1.2        |
| zlib                                      | 1.0.0        |
| ostruct                                   | 0.1.0        |
| strscan                                   | 1.0.0        |
| io-console                                | 0.4.7        |
| fileutils                                 | 1.5.0        |
| psych                                     | 3.1.0        |
| mutex_m                                   | 0.1.0        |
| fastlane-plugin-firebase_app_distribution | 0.2.9        |
</details>


*generated on:* **2021-06-24**
</details>

**Comment by crazymanish** [comment]
Hi @nele-llama 

Are you very sure, Deliver was working okay in the last version for you i.e `v2.185.1` ?

I am asking because I am very sure we did not release anything about Deliver `app param`, in fact since this PR https://github.com/fastlane/fastlane/pull/18617 : **app param always allow the only integer**  and that change was released as part of v2.184.0 release. 
see below:
https://github.com/fastlane/fastlane/pull/18617/files#diff-27143d195515a7995a267355f184482c6012dd94bfe65d7622dcb19aae30b448R446

**Comment by crazymanish** [comment]
Also, I notice that in your `upload_to_asc` lane, you are not passing `app param` I m very curious to know how are you using this param because it's an optional param, are you passing something in CLI command, ENV, or in DeliverFile ?

```ruby
deliver(force: true,
  skip_metadata: true,
  skip_screenshots: true 
)
```

**Comment by nele-llama** [comment]
Well i can see in my git commit that on 24.06. at 00:26 Belgrade time zone build with fastlane version 2.185.1 was successful and i can see that build on TestFlight.

Yes i am using .env file for params.

```
USERNAME='foo@foo.com'
BUNDLE_ID='foo.foo.foo'
TEAM_ID='XXXXXXXXX'

# MATCH

MATCH_USERNAME=$USERNAME
FASTLANE_TEAM_ID=$TEAM_ID
MATCH_STORAGE_MODE='git'
MATCH_GIT_URL='...'
MATCH_GIT_USER_EMAIL=$USERNAME
MATCH_FORCE_FOR_NEW_DEVICES=true
MATCH_GENERATE_APPLE_CERTS=false
MATCH_READONLY=false
MATCH_VERBOSE=true

# GYM

GYM_CLEAN=true
GYM_OUTPUT_DIRECTORY='./build'
GYM_DERIVED_DATA_PATH='./build/derivedData'
GYM_BUILD_PATH='./build'
GYM_ARCHIVE_PATH='./build/archive'
GYM_OUTPUT_NAME='XXXXX'
GYM_EXPORT_METHOD='app-store'
GYM_INCLUDE_SYMBOLS=true
GYM_INCLUDE_BITCODE=true

# DELIVER

DELIVER_USERNAME=$USERNAME
DELIVER_IPA_PATH='./build/XXXXX.ipa'
DELIVER_SUBMIT_FOR_REVIEW=false
DELIVER_TEAM_ID=$TEAM_ID
DELIVER_APP_ID=$BUNDLE_ID
PRECHECK_INCLUDE_IN_APP_PURCHASES=false

# SLACK

FL_SLACK_CHANNEL='#ios-builds'
SLACK_URL='https://hooks.slack.com/services/XXXXX'

FIREBASE_TOKEN='...'

FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD='...'
```

**Comment by crazymanish** [comment]
Hi @nele-llama 
Thank you for the reply! I want to inform you that you don't need to pass to `DELIVER_APP_ID ` that is spaceship app_id and Fastlane uses/take-care of it internally.

Please remove `DELIVER_TEAM_ID=$TEAM_ID` from your .env file.

More details:
https://github.com/fastlane/fastlane/blob/master/deliver/lib/deliver/detect_values.rb#L41

<img width="673" alt="Screenshot 2021-06-25 at 06 14 43" src="https://user-images.githubusercontent.com/5364500/123368999-20a14400-d57d-11eb-8b9a-d1fc19291bbe.png">


closing this is the issue, please let us know if have an issue, after removing `DELIVER_TEAM_ID=$TEAM_ID`

**Comment by nele-llama** [comment]
It works!! Thanks for the great support!

Regards!
