### ISSUE TITLE
Running Cert and Sigh in github runner

### ISSUE THREAD

**Issue by jdr81394** [fastlane/fastlane#18967]
I am attempting to automate IPA resigning and I do not want to use match because I do not want to revoke my current certificates. I have successfully ran cert and now I am attempting to run fastlane sigh to pull down the provisioning profiles. 

I get these warnings ( which I do not believe to be the actual problem) : 
[18:08:13]: Fetching profiles...
[18:08:14]: Verifying certificates...
[18:08:14]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[18:08:15]: Creating new provisioning profile for 'com--12-12' with name 'com--12-12 InHouse' for 'ios' platform

Which is then followed by the actual error:
/usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/spaceship/lib/spaceship/connect_api/api_client.rb:214:in `handle_error': \e[31m[!] undefined method `first' for "errors":String\e[0m (NoMethodError)
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/spaceship/lib/spaceship/client.rb:886:in `block in send_request'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/spaceship/lib/spaceship/client.rb:646:in `with_retry'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/spaceship/lib/spaceship/client.rb:882:in `send_request'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/spaceship/lib/spaceship/client.rb:726:in `request'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/spaceship/lib/spaceship/connect_api/provisioning/client.rb:67:in `proxy_post'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/spaceship/lib/spaceship/connect_api/provisioning/client.rb:37:in `post'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/spaceship/lib/spaceship/connect_api/provisioning/provisioning.rb:189:in `post_profiles'
	from /usr/local/Cellar/ruby@2.7/2.7.3/lib/ruby/2.7.0/forwardable.rb:235:in `post_profiles'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/spaceship/lib/spaceship/connect_api/models/profile.rb:76:in `create'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/sigh/lib/sigh/runner.rb:182:in `create_profile!'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/sigh/lib/sigh/runner.rb:54:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/sigh/lib/sigh/manager.rb:8:in `start'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/sigh/lib/sigh/commands_generator.rb:62:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/sigh/lib/sigh/commands_generator.rb:140:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/sigh/lib/sigh/commands_generator.rb:17:in `start'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `load'
	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `<main>'
/usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/spaceship/lib/spaceship/connect_api/api_client.rb:214:in `handle_error': undefined method `first' for "errors":String (NoMethodError)
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/spaceship/lib/spaceship/client.rb:886:in `block in send_request'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/spaceship/lib/spaceship/client.rb:646:in `with_retry'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/spaceship/lib/spaceship/client.rb:882:in `send_request'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/spaceship/lib/spaceship/client.rb:726:in `request'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/spaceship/lib/spaceship/connect_api/provisioning/client.rb:67:in `proxy_post'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/spaceship/lib/spaceship/connect_api/provisioning/client.rb:37:in `post'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/spaceship/lib/spaceship/connect_api/provisioning/provisioning.rb:189:in `post_profiles'
	from /usr/local/Cellar/ruby@2.7/2.7.3/lib/ruby/2.7.0/forwardable.rb:235:in `post_profiles'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/spaceship/lib/spaceship/connect_api/models/profile.rb:76:in `create'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/sigh/lib/sigh/runner.rb:182:in `create_profile!'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/sigh/lib/sigh/runner.rb:54:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/sigh/lib/sigh/manager.rb:8:in `start'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/sigh/lib/sigh/commands_generator.rb:62:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/sigh/lib/sigh/commands_generator.rb:140:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/sigh/lib/sigh/commands_generator.rb:17:in `start'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `load'
	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `<main>'
Error: Process completed with exit code 1.

Here is the ENV:

GITHUB_JOB=job_1
GITHUB_EVENT_PATH=/Users/runner/work/_temp/_github_workflow/event.json
RUNNER_OS=macOS
XCODE_12_DEVELOPER_DIR=/Applications/Xcode_12.4.app/Contents/Developer
GITHUB_BASE_REF=
NVM_CD_FLAGS=
ANDROID_HOME=/Users/runner/Library/Android/sdk
SHELL=/bin/bash
CHROMEWEBDRIVER=/usr/local/Caskroom/chromedriver/91.0.4472.19
PIPX_BIN_DIR=/usr/local/opt/pipx_bin
@TMPDIR=/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/
GITHUB_RUN_NUMBER=178
GITHUB_ACTIONS=true
ANDROID_SDK_ROOT=/Users/runner/Library/Android/sdk
RUNNER_WORKSPACE=/Users/runner/work/ipaTest
RCT_NO_LAUNCH_PACKAGER=1
JAVA_HOME_8_X64=/Users/runner/hostedtoolcache/Java_Adopt_jdk/8.0.292-10/x64/Contents/Home
NUNIT_BASE_PATH=/Library/Developer/nunit
RUNNER_PERFLOG=/usr/local/opt/runner/perflog
GITHUB_WORKFLOW=Single-Runner Automation
GITHUB_REF=refs/heads/master
NUNIT3_PATH=/Library/Developer/nunit/3.6.0
LC_ALL=en_US.UTF-8
JAVA_HOME_11_X64=/Users/runner/hostedtoolcache/Java_Adopt_jdk/11.0.11-9/x64/Contents/Home
RUNNER_TOOL_CACHE=/Users/runner/hostedtoolcache
GITHUB_ACTION_REPOSITORY=
USER=runner
JAVA_HOME_14_X64=/Users/runner/hostedtoolcache/Java_Adopt_jdk/14.0.2-12/x64/Contents/Home
NVM_DIR=/Users/runner/.nvm
GITHUB_API_URL=https://api.github.com
GITHUB_EVENT_NAME=workflow_dispatch
GITHUB_SHA=abdec6809ba59345bb2c7ffbae9003405326d223
XCODE_10_DEVELOPER_DIR=/Applications/Xcode_10.3.app/Contents/Developer
RUNNER_TEMP=/Users/runner/work/_temp
ANDROID_NDK_ROOT=/Users/runner/Library/Android/sdk/ndk-bundle
ImageVersion=20210612.1
ANDROID_NDK_LATEST_HOME=/Users/runner/Library/Android/sdk/ndk/22.1.7171670
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.Bf0w5clxOj/Listeners
GITHUB_SERVER_URL=https://github.com
__CF_USER_TEXT_ENCODING=0x1F5:0:0
HOMEBREW_NO_AUTO_UPDATE=1
GITHUB_HEAD_REF=
AGENT_TOOLSDIRECTORY=/Users/runner/hostedtoolcache
GITHUB_GRAPHQL_URL=https://api.github.com/graphql
FASTLANE_SESSION=*REDACTED*
PATH=/usr/local/opt/pipx_bin:/Users/runner/.cargo/bin:/usr/local/lib/ruby/gems/2.7.0/bin:/usr/local/opt/ruby@2.7/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/Users/runner/Library/Android/sdk/tools:/Users/runner/Library/Android/sdk/platform-tools:/Users/runner/Library/Android/sdk/ndk-bundle:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/runner/.dotnet/tools:/Users/runner/.ghcup/bin:/Users/runner/hostedtoolcache/stack/2.7.1/x64
_=/usr/bin/env
GITHUB_RETENTION_DAYS=90
PERFLOG_LOCATION_SETTING=RUNNER_PERFLOG
EDGEWEBDRIVER=/usr/local/share/edge_driver
DOTNET_ROOT=/Users/runner/.dotnet
CONDA=/usr/local/miniconda
VM_ASSETS=/usr/local/opt/runner/scripts
***
JAVA_HOME=/Users/runner/hostedtoolcache/Java_Adopt_jdk/8.0.292-10/x64/Contents/Home
VCPKG_INSTALLATION_ROOT=/usr/local/share/vcpkg
JAVA_HOME_12_X64=/Users/runner/hostedtoolcache/Java_Adopt_jdk/12.0.2-10.3/x64/Contents/Home
LANG=en_US.UTF-8
ImageOS=macos1015
XPC_FLAGS=0x0
PIPX_HOME=/usr/local/opt/pipx
GITHUB_ACTOR=jdr81394
GECKOWEBDRIVER=/usr/local/opt/geckodriver/bin
XPC_SERVICE_NAME=0
HOME=/Users/runner
SHLVL=2
RUNNER_TRACKING_ID=github_2e4627e1-73c0-4659-8790-320e7166ef6a
GITHUB_WORKSPACE=/Users/runner/work/ipaTest/ipaTest
ANDROID_NDK_18R_PATH=/Users/runner/Library/Android/sdk/ndk/18.1.5063045
GITHUB_ACTION_REF=
CI=true
GITHUB_RUN_ID=968918582
VAULT_TOKEN=b.AAAAAgIPHzoPnFbVlqraifM8EJgku71P9wQ_O8I6r10DlU7nlttcfAaBgpzk_fTbM4P_LggNjhrNxrXU3bMYcOXFEHfYNZAVxzud60-coyJn1L60M3l5S8_YJlkKsxBPMt3ym4rpt7q6gPeT0SOLmt99KYiF29BdV8-S8ZNY5xQksG9tPrl6RMX33EAvexWbFV9XWoCuwO--6l0_KCyHOxp-MzcvPb5KXFmZcXMPnC_gNneRMpfoNWRt1QL3i1kPcswBefOSwNQGBFm2oDsTWGF_Ko4DkDFQywlOpA_Y5UEbMmfQ5lyDU4XHYyOWNl3w7Xb53AFb77tWjcgzVYV_rg
LOGNAME=runner
GITHUB_ENV=/Users/runner/work/_temp/_runner_file_commands/set_env_e168f38a-2d46-4dbb-80c4-c2d555059ef5
LC_CTYPE=en_US.UTF-8
HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS=3650
JAVA_HOME_13_X64=/Users/runner/hostedtoolcache/Java_Adopt_jdk/13.0.2-8.1/x64/Contents/Home
HOMEBREW_CASK_OPTS=--no-quarantine
POWERSHELL_DISTRIBUTION_CHANNEL=GitHub-Actions-macos1015
BOOTSTRAP_HASKELL_NONINTERACTIVE=1
ANDROID_NDK_HOME=/Users/runner/Library/Android/sdk/ndk-bundle
XCODE_11_DEVELOPER_DIR=/Applications/Xcode_11.7.app/Contents/Developer
GITHUB_PATH=/Users/runner/work/_temp/_runner_file_commands/add_path_e168f38a-2d46-4dbb-80c4-c2d555059ef5
GITHUB_ACTION=run4
DOTNET_MULTILEVEL_LOOKUP=0

I am not currently using a Fastfile/Gemfile as I am unsure of how to implement this with my github runner. 

Can anyone please advise? This is my first fastlane issue, so please let me know if I left out any important information that would assist in solving this issue. Thank you.

**Comment by crazymanish** [comment]
Hi @jdr81394 
Requesting you to open discussion here 🙏 
https://github.com/fastlane/fastlane/discussions/categories/q-a

You may already found the answer there!

**Comment by jdr81394** [comment]
@crazymanish thank you. I will open a discussion but no I do not see the answer there.

**Comment by crazymanish** [comment]
Cool. then I will close this issue! Pretty sure, we will get help for this question under Q&A
https://github.com/fastlane/fastlane/discussions/categories/q-a

Also, such important information will be helpful for other Fastlane users too...in the future so Opening a discussion is a very good choice! 🙏
