### ISSUE TITLE
Password that starts with a '-' recognized as an option

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1897]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/2110500?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @RuCray - Imported from <a href='https://github.com/fastlane/pilot/issues/83'>fastlane/pilot#83</a>
        </td>
      </tr>
    </table>

Password that starts with a `-` is recognized as an option and the upload process is stalled with the warning message: 
`[Transporter Warning Output]: The following option was specified but is not recognized:`

**Comment by KrauseFx** [comment]
Sorry for not coming back to this earlier, is this issue still happening with the latest _fastlane_ release?
