### ISSUE TITLE
create_keychain timeout parameter no longer accepts "false" after version 2.185.1

### ISSUE THREAD

**Issue by davejlin** [fastlane/fastlane#18970]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
We had used the following for ```create_keychain```, which worked fine with version 2.185.0 and prior:

    create_keychain(
      name: "keychain",
      password: "password",
      default_keychain: true,
      unlock: true,
      timeout: false,
      lock_when_sleeps: false
    )

Based on the [docs for create_keychain](https://docs.fastlane.tools/actions/create_keychain/) as of this posting,  ```timeout``` is the: 

> timeout interval in seconds. Set false if you want to specify "no time-out"

However, after version 2.185.1, ```timeout``` appears to no longer accept ```false``` as a valid argument.

For example, using ```false```, we were getting the following errors:

```
INFO [2021-06-24 20:54:24.58]: Cruising over to lane 'ios create_match_keychain' 🚖
ERROR [2021-06-24 20:54:24.58]: You passed invalid parameters to 'create_keychain'.
ERROR [2021-06-24 20:54:24.58]: Check out the error below and available options by running `fastlane action create_keychain`
WARN [2021-06-24 20:54:24.58]: Lane Context:
INFO [2021-06-24 20:54:24.58]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios test_and_build"}

+------+------------------------------------------+-------------+
|                       fastlane summary                        |
+------+------------------------------------------+-------------+
| Step | Action                                   | Time (in s) |
+------+------------------------------------------+-------------+
| 1    | default_platform                         | 0           |
| 2    | Switch to ios create_match_keychain lane | 0           |
+------+------------------------------------------+-------------+

DEBUG [2021-06-24 20:54:24.65]: All plugins are up to date
ERROR [2021-06-24 20:54:24.65]: fastlane finished with errors

.
.
.
/usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.185.1/fastlane_core/lib/fastlane_core/configuration/config_item.rb:262:in `auto_convert_value': undefined method `to_i' for false:FalseClass (NoMethodError)
.
.
.
```

The change in [PR #18857 ](https://github.com/fastlane/fastlane/pull/18857) appears to be where the type for the ```timeout``` parameter changed from ```is_string: false``` to ```type: Integer```, so that a ```Boolean``` is no longer valid.

Opening this issue to document our experience and findings, and to request that you please update your [docs for create_keychain](https://docs.fastlane.tools/actions/create_keychain/).

**Comment by crazymanish** [comment]
Hi @davejlin 

This issue has been fixed, please see: https://github.com/fastlane/fastlane/pull/18894
Please use `timeout: 0` instead of `timeout: false` after next release

```ruby
# or use timeout: 0 for no-timeout -- after next release
create_keychain(
  name: "keychain",
  password: "password",
  default_keychain: true,
  unlock: true,
  timeout: 0,
  lock_when_sleeps: false
)

# or for now, you can use timeout: 360000
create_keychain(
  name: "keychain",
  password: "password",
  default_keychain: true,
  unlock: true,
  timeout: 360000,
  lock_when_sleeps: false
)
```

Fastlane master branch is up-to-date: https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/create_keychain.rb#L132

Fastlane **docs** is a separate git repo, it will get updated soon after next release, please see this:
https://github.com/fastlane/docs/pull/1067/files#diff-b9c72bc875fb5747ed4f3394fc4c6b988f1c0d5ca4b50f381e121fc733f54e95L49

Old related issue:
https://github.com/fastlane/fastlane/issues/18892 https://github.com/fastlane/fastlane/issues/18936
