### ISSUE TITLE
Fastlane build_app is ignoring custom provisioningProfiles configuration

### ISSUE THREAD

**Issue by emilioheinz** [fastlane/fastlane#18974]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm trying to build my application with the `Release` configuration but for `ad-hoc` distribution. As mentioned in the documentation you can do it by providing a custom `provisioningProfiles` mapping to the `build_app` action.

It seems that fastlane `build_app` is ignoring this custom mapping and using the default configuration setted on `project.pbxproj` file. As the default config is for a `appstore` provisioning profile - that we don't have in our machine - it throws an error saying that  _Xcode couldn't find any provisioning profiles matching 'team/profile-appstore'_ but we are actually trying to use the `team/profile-adhoc` profile.

##### Command executed

```ruby
build_app(
      workspace: "App.xcworkspace",
      scheme: "App",
      configuration: options[:configuration],
      clean: true,
      silent: true,
      skip_profile_detection: true,
      output_directory: "./build",
      export_method: options[:export_method],
      export_options: "ReleaseAdHoc.plist",
)
```
ReleaseAdHoc.plist
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>provisioningProfiles</key>
    <dict>
      <key>br.com.company.app</key>
      <string>profile-adhoc</string>
      <key>br.com.company.app.OneSignalNotificationServiceExtension</key>
      <string>profile-onesignalextension-adhoc</string>
    </dict>
  </dict>
</plist>
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
[✔] 🚀 
[11:08:41]: fastlane detected a Gemfile in the current directory
[11:08:41]: However, it seems like you didn't use `bundle exec`
[11:08:41]: To launch fastlane faster, please use
[11:08:41]: 
[11:08:41]: $ bundle exec fastlane ios build configuration:Release export_method:ad-hoc --verbose
[11:08:41]: 
[11:08:41]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2021-06-25 11:08:42.08]: Checking if there are any plugins that should be loaded...
DEBUG [2021-06-25 11:08:42.13]: Loading 'fastlane-plugin-appcenter' plugin
INFO [2021-06-25 11:08:42.15]: gem 'fastlane-plugin-appcenter' is already installed
+---------------------------+---------+-----------------------------------------------------------+
|                                          Used plugins                                           |
+---------------------------+---------+-----------------------------------------------------------+
| Plugin                    | Version | Action                                                    |
+---------------------------+---------+-----------------------------------------------------------+
| fastlane-plugin-appcenter | 1.11.0  | appcenter_fetch_version_number, appcenter_fetch_devices,  |
|                           |         | appcenter_upload                                          |
+---------------------------+---------+-----------------------------------------------------------+

Successfully loaded Appfile at path '***/ios/fastlane/Appfile'
- app_identifier: '***'
- apple_id: '***'
- itc_team_id: '***'
- team_id: '***'
-------
DEBUG [2021-06-25 11:08:42.32]: Using configuration: Release
DEBUG [2021-06-25 11:08:42.33]: Using export_method: ad-hoc
INFO [2021-06-25 11:08:42.33]: ------------------------------
INFO [2021-06-25 11:08:42.33]: --- Step: default_platform ---
INFO [2021-06-25 11:08:42.33]: ------------------------------
INFO [2021-06-25 11:08:42.33]: Driving the lane 'ios build' 🚀
INFO [2021-06-25 11:08:42.34]: -----------------------
INFO [2021-06-25 11:08:42.34]: --- Step: build_app ---
INFO [2021-06-25 11:08:42.34]: -----------------------
WARN [2021-06-25 11:08:42.39]: Resolving Swift Package Manager dependencies...
INFO [2021-06-25 11:08:42.39]: $ xcodebuild -resolvePackageDependencies -workspace ***.xcworkspace -scheme *** -configuration Release
INFO [2021-06-25 11:08:43.15]: ▸ Command line invocation:
INFO [2021-06-25 11:08:43.15]: ▸     /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -workspace ***.xcworkspace -scheme *** -configuration Release
INFO [2021-06-25 11:08:45.01]: ▸ resolved source packages: 
INFO [2021-06-25 11:08:45.03]: $ xcodebuild -showBuildSettings -workspace ***.xcworkspace -scheme *** -configuration Release
INFO [2021-06-25 11:08:47.63]: Detected provisioning profile mapping: {"br.com.company.app"=>"app-adhoc", "br.com.company.app.OneSignalNotificationServiceExtension"=>"onesignalextension-adhoc"}

+---------------------------------------------------------------------------------------------------+--------------------------------------------------------------------+
|                                                                        Summary for gym 2.186.0                                                                         |
+---------------------------------------------------------------------------------------------------+--------------------------------------------------------------------+
| workspace                                                                                         | ***.xcworkspace                                          |
| scheme                                                                                            | ***                                                      |
| configuration                                                                                     | Release                                                            |
| clean                                                                                             | true                                                               |
| silent                                                                                            | true                                                               |
| skip_profile_detection                                                                            | true                                                               |
| output_directory                                                                                  | ./build                                                            |
| export_method                                                                                     | ad-hoc                                                             |
| export_options.provisioningProfiles.br.com.company.app                                            | app-adhoc                                                   |
| export_options.provisioningProfiles.br.com.company.app.OneSignalNotificationServiceEx             | onesignalextension-adhoc                                    |
| tension                                                                                           |                                                                    |
| output_name                                                                                       | ***                                                           |
| skip_package_ipa                                                                                  | false                                                              |
| skip_package_pkg                                                                                  | false                                                              |
| build_path                                                                                        | /Users/***/Library/Developer/Xcode/Archives/2021-06-25 |
| result_bundle                                                                                     | false                                                              |
| buildlog_path                                                                                     | ~/Library/Logs/gym                                                 |
| destination                                                                                       | generic/platform=iOS                                               |
| skip_package_dependencies_resolution                                                              | false                                                              |
| disable_package_automatic_updates                                                                 | false                                                              |
| use_system_scm                                                                                    | false                                                              |
| xcode_path                                                                                        | /Applications/Xcode.app                                            |
+---------------------------------------------------------------------------------------------------+--------------------------------------------------------------------+

+--------------------------------------------------------------------------------------------+----------------------+
|                                              Generated Build Command                                              |
+--------------------------------------------------------------------------------------------+----------------------+
| Option                                                                                     | Value                |
+--------------------------------------------------------------------------------------------+----------------------+
| set -o pipefail &&                                                                         |                      |
| xcodebuild                                                                                 |                      |
| -workspace ***.xcworkspace                                                                 |                      |
| -scheme ***                                                                                |                      |
| -configuration Release                                                                     |                      |
| -destination                                                                               | generic/platform=iOS |
| -archivePath /Users/***/Library/Developer/Xcode/Archives/2021-06-25/***                    |                      |
| 2021-06-25\ 11.08.47.xcarchive                                                             |                      |
| clean                                                                                      |                      |
| archive                                                                                    |                      |
| | tee /Users/***/Library/Logs/gym/***.log                                                  |                      |
| | xcpretty                                                                                 |                      |
+--------------------------------------------------------------------------------------------+----------------------+
INFO [2021-06-25 11:08:51.45]: ▸ Clean Succeeded
INFO [2021-06-25 11:08:58.68]: ▸ ** ARCHIVE FAILED **
INFO [2021-06-25 11:08:58.68]: ▸ ❌  error: No profile for team '***' matching 'app-appstore' found: Xcode couldn't find any provisioning profiles matching '***/app-appstore'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the Signing & Capabilities tab of the target editor. (in target '***' from project '***')

+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.186.0                 |
| export_method | ad-hoc                  |
| sdk           | iPhoneOS14.4.sdk        |
+---------------+-------------------------+

ERROR [2021-06-25 11:08:58.72]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
WARN [2021-06-25 11:08:58.72]: 📋  For the complete and more detailed error log, check the full log at:
WARN [2021-06-25 11:08:58.72]: 📋  /Users/***/Library/Logs/gym/***.log
INFO [2021-06-25 11:08:58.72]: 
ERROR [2021-06-25 11:08:58.72]: Looks like fastlane ran into a build/archive error with your project
ERROR [2021-06-25 11:08:58.72]: It's hard to tell what's causing the error, so we wrote some guides on how
ERROR [2021-06-25 11:08:58.72]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
ERROR [2021-06-25 11:08:58.72]: Before submitting an issue on GitHub, please follow the guide above and make
ERROR [2021-06-25 11:08:58.72]: sure your project is set up correctly.
ERROR [2021-06-25 11:08:58.72]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
ERROR [2021-06-25 11:08:58.72]: the full commands printed out in yellow in the above log.
ERROR [2021-06-25 11:08:58.72]: Make sure to inspect the output above, as usually you'll find more error information there
INFO [2021-06-25 11:08:58.72]: 
WARN [2021-06-25 11:08:58.72]: Lane Context:
INFO [2021-06-25 11:08:58.72]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios build"}
ERROR [2021-06-25 11:08:58.72]: Error building the application - see the log above
INFO [2021-06-25 11:08:58.72]: Successfully generated documentation at path '/Users/***/ios/fastlane/README.md'

ERROR [2021-06-25 11:08:58.73]: fastlane finished with errors
</pre>
</details>

### Environment

<details>
  <pre> <summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.2                                                           |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.2 (20D64)                                             |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.4                                                           |
| Swift Version               | 5.3.2                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :build do |options|
    app_release_plist_file = (
      options[:export_method] == "app-store" ?
        "./fastlane/export-options/ReleaseAppStore.plist" :
        "./fastlane/export-options/ReleaseAdHoc.plist"
    )
    app_debug_staging_plist_file = "./fastlane/export-options/DebugStagingAdHoc.plist"

    app_export_options_plist_file = (
      options[:configuration] == "Release" ?
        app_release_plist_file :
        app_debug_staging_plist_file
    )


    build_app(
      workspace: "**.xcworkspace",
      scheme: "**",
      configuration: options[:configuration],
      clean: true,
      silent: true,
      skip_profile_detection: true,
      output_directory: "./build",
      export_method: options[:export_method],
      export_options: app_export_options_plist_file,
    )
  end

  lane :stage do
    appcenter_upload(
      api_token: "***",
      owner_name: "***",
      owner_type: "organization",
      app_name: "***-iOS",
      file: "./build/***.ipa",
      notify_testers: false,
      destinations: "***",
    )
  end

  lane :release do
    deliver(
      ipa: "./build/***.ipa",
      submit_for_review: false,
      automatic_release: false,
      skip_app_version_update: true,
      skip_screenshots: true,
      skip_metadata: true,
      force: true,
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("br.com.company.app") # The bundle identifier of your app
apple_id("***@email.com.br") # Your Apple email address

itc_team_id("***") # App Store Connect Team ID
team_id("***") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.186.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status      |
| ------------------------- | ------- | ------------------ |
| fastlane-plugin-appcenter | 1.11.0  | 🚫 Update available |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.5.0        |
| addressable                     | 2.7.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.3        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.76.0       |
| faraday                         | 1.0.1        |
| faraday_middleware              | 1.0.0        |
| fastimage                       | 2.2.0        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.10.1       |
| naturally                       | 2.2.0        |
| rubyzip                         | 2.3.0        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.0        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.1.4        |
| simctl                          | 1.6.8        |
| jwt                             | 2.2.2        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| declarative-option              | 0.1.0        |
| representable                   | 3.0.4        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.0.2        |
| multi_json                      | 1.15.0       |
| signet                          | 0.14.0       |
| memoist                         | 0.16.2       |
| os                              | 1.1.1        |
| googleauth                      | 0.16.2       |
| httpclient                      | 2.8.3        |
| rexml                           | 3.1.9        |
| webrick                         | 1.4.2        |
| google-apis-core                | 0.3.0        |
| google-apis-playcustomapp_v1    | 0.3.0        |
| google-apis-androidpublisher_v3 | 0.6.0        |
| google-cloud-env                | 1.3.3        |
| google-cloud-errors             | 1.0.1        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.4.0        |
| google-apis-storage_v1          | 0.4.0        |
| rake                            | 13.0.1       |
| digest-crc                      | 0.6.1        |
| google-cloud-storage            | 1.32.0       |
| emoji_regex                     | 3.0.0        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.0.3        |
| CFPropertyList                  | 3.0.2        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.19.0       |
| public_suffix                   | 4.0.6        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.3        |
| faraday-cookie_jar              | 0.0.7        |
| json                            | 2.3.1        |
| aws-eventstream                 | 1.1.0        |
| aws-sigv4                       | 1.2.2        |
| aws-partitions                  | 1.380.0      |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.109.0      |
| aws-sdk-kms                     | 1.39.0       |
| aws-sdk-s3                      | 1.83.0       |
| forwardable                     | 1.2.0        |
| logger                          | 1.3.0        |
| stringio                        | 0.0.2        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| date                            | 2.0.0        |
| io-console                      | 0.4.7        |
| fileutils                       | 1.1.0        |
| etc                             | 1.0.1        |
| zlib                            | 1.0.0        |
| libxml-ruby                     | 3.1.0        |
| psych                           | 3.1.0        |
| mutex_m                         | 0.1.0        |
| fastlane-plugin-appcenter       | 1.11.0       |
| csv                             | 3.0.9        |
</details>

*generated on:* **2021-06-25**
 </pre>
</details>

**Comment by lucgrabowski** [comment]
Hi, you should update profile in Xcode project using `update_project_provisioning` http://docs.fastlane.tools/actions/update_project_provisioning/#update_project_provisioning before running `build_app`. Custom mapping isn't enough.

**Comment by emilioheinz** [comment]
@lucgrabowski Nice I'll try it ASAP. Wouldn't it be nice to mention it on `build_app / gym` docs?

**Comment by emilioheinz** [comment]
@lucgrabowski We are facing some issues trying to use this action. `update_project_provisioning` needs a `profile` to be run, but `profile` is, in this case, a path. Is there a way to use only the name of the specific profile?

**Comment by lucgrabowski** [comment]
@emilioheinz `update_project_provisioning` needs a profile's path, like you said. 
It could be set automatically if you used `sigh` before running `build_app`.
You could also use `match` but I think that you would have to see in match summary table (when command is run in terminal) what environment variable is created with profile path and use it in `update_project_provisioning`
https://docs.fastlane.tools/codesigning/getting-started/

**Comment by emilioheinz** [comment]
@lucgrabowski Thank you for the quick response. I'll take a look on this docs :)
