### ISSUE TITLE
xcarchive support?

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1900]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/117700?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @Pipen - Imported from <a href='https://github.com/fastlane/pilot/issues/73'>fastlane/pilot#73</a>
        </td>
      </tr>
    </table>

Hi, Correct me if I'm wrong, but the only way to upload dSYM to iTunes Connect/Testflight is by instead of uploading an IPA would be to upload a xcarchive like xcode does for you, instead of using the application loader which seems to have very limited support now days.

**Comment by rex-remind101** [comment]
👍

**Comment by KrauseFx** [comment]
@rex-remind101 You can do that, run `gym --help` to see the option to include dSYM files 👍

**Comment by rex-remind101** [comment]
Awesome! I'll give that a shot, thanks!
