### ISSUE TITLE
Find (or preferably remove) users with no devices.

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1904]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/1222408?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @runloop - Imported from <a href='https://github.com/fastlane/pilot/issues/61'>fastlane/pilot#61</a>
        </td>
      </tr>
    </table>

Seeing as Apple seem to be actively worsening the experience and functionality of the iTC version of TestFlight it would be amazing if Pilot allowed us to find users with no devices, or better yet, simply remove them. I've got 500 or so users they have been invited to test and probably 80% haven't even registered their device. Currently there is no sane way to remove these users from TestFlight. I'm hoping one day Pilot could be the answer.

**Comment by KrauseFx** [comment]
Sorry for not coming back to this earlier, is this issue still happening with the latest _fastlane_ release?
