### ISSUE TITLE
[docs] "Platform" parameter values on deliver is not up to date

### ISSUE THREAD

**Issue by zackdotcomputer** [fastlane/fastlane#19050]
The docs for deliver still list the valid platform values as "mac" and "ios" and whether these should be symbols or strings is not defined. However, in usage the tool requires a string and says the valid values are "ios, appletvos, or osx". The docs should be updated to reflect this.

**Comment by Kelly7894** [comment]
A parameter might have several conditional values associated with it. The following rules determine which value is fetched from the Remote Config Server, and which value is used in a given app instance at a particular point in time..

**Comment by lucgrabowski** [comment]
@joshdholtz What is your take on the supported os values that are shown in documentation of actions http://docs.fastlane.tools/actions/? 

Should those values be similar as in `platform` options?

Currently only `ios, android, mac` are supported in the documentation:
https://github.com/fastlane/fastlane/blob/66a4bb17bf6f3c0f3222b5c296926e5b58dd2b4e/fastlane/lib/assets/Actions.md.erb#L40
https://github.com/fastlane/fastlane/blob/66a4bb17bf6f3c0f3222b5c296926e5b58dd2b4e/fastlane/lib/assets/ActionDetails.md.erb#L22
There are actions which according to the docs support `ios, mac`, but from the `is_supported` method we can see that other values  should also be supported:
https://github.com/fastlane/fastlane/blob/66a4bb17bf6f3c0f3222b5c296926e5b58dd2b4e/fastlane/lib/fastlane/actions/app_store_connect_api_key.rb#L111-L113

https://github.com/fastlane/fastlane/blob/66a4bb17bf6f3c0f3222b5c296926e5b58dd2b4e/fastlane/lib/fastlane/actions/install_xcode_plugin.rb#L76
(This is the only place in code with `:caros`)

https://github.com/fastlane/fastlane/blob/66a4bb17bf6f3c0f3222b5c296926e5b58dd2b4e/fastlane/lib/fastlane/actions/download_dsyms.rb#L338


Mapping from platform names to ConnectAPI platforms for comparison:
https://github.com/fastlane/fastlane/blob/66a4bb17bf6f3c0f3222b5c296926e5b58dd2b4e/spaceship/lib/spaceship/connect_api.rb#L79-L96
