### ISSUE TITLE
Submit for Beta Review

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1905]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/800103?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @kohtenko - Imported from <a href='https://github.com/fastlane/pilot/issues/60'>fastlane/pilot#60</a>
        </td>
      </tr>
    </table>

What about submitting to external beta review in `pilot`? 
This available in `spaceship` with `build.submit_for_beta_review!(parameters)`, but never used in `pilot`.

**Comment by truth3** [comment]
It seems Apple is now asking for the beta information for all languages (what to test, description, feedback email, marketing URL). Having the same abilities as Deliver to deal with localization would be amazing.

**Comment by TKBurner** [comment]
@truth3 Thanks for following up on this. I'll make sure we talk about this as a team and update the thread as relevant. Thanks!
