### ISSUE TITLE
Using Github Deploy Keys

### ISSUE THREAD

**Issue by vin-fandemand** [fastlane/fastlane#19062]
### Discussed in https://github.com/fastlane/fastlane/discussions/19035

<div type='discussions-op-text'>

<sup>Originally posted by **vin-fandemand** June 30, 2021</sup>
I was running ios build to publish to firebase distribution using fastlane. So I created the profiles and certificates and added to my private repository. Then I testing the fastlane script in the local machine and it works all well. I then added the script to Github CI/CD. Then I generated the private/public key withouth a passphrase and added the public key as Deploy Key in the github repository where my certificates and and private key in the Github secrets. I then referenced this private key in the Github Actions script and passed it to fastlane as an environment variable. However I am unable to clone the repo in the script. Does anyone know why and what did I miss ?

<img width="511" alt="Screen Shot 2021-06-30 at 10 32 48 AM" src="https://user-images.githubusercontent.com/64597233/123980151-508e8400-d98f-11eb-9311-f032f8d1d946.png">
<img width="615" alt="Screen Shot 2021-06-30 at 10 33 28 AM" src="https://user-images.githubusercontent.com/64597233/123980156-51271a80-d98f-11eb-97ba-09bc32e0ecb2.png">
<img width="884" alt="Screen Shot 2021-06-30 at 10 34 14 AM" src="https://user-images.githubusercontent.com/64597233/123980161-51bfb100-d98f-11eb-9bdc-5c451eda5310.png">
</div>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.4                                                           |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.30.1 (Apple Git-130)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.4 (20F71)                                             |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.5.1                                                         |
| Swift Version               | 5.4.2                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.187.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| atomos                          | 0.1.3        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.19.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.7.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.0.0        |
| fastimage                       | 2.2.4        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.0        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| simctl                          | 1.6.8        |
| jwt                             | 2.2.3        |
| emoji_regex                     | 3.2.2        |
| aws-eventstream                 | 1.1.1        |
| aws-sigv4                       | 1.2.3        |
| aws-sdk-kms                     | 1.44.0       |
| aws-sdk-s3                      | 1.96.1       |
| CFPropertyList                  | 3.0.3        |
| excon                           | 0.83.0       |
| ruby2_keywords                  | 0.0.4        |
| faraday-net_http_persistent     | 1.1.0        |
| faraday-net_http                | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.4.3        |
| json                            | 2.5.1        |
| bundler                         | 2.2.21       |
| webrick                         | 1.7.0        |
| rexml                           | 3.2.5        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| signet                          | 0.15.0       |
| os                              | 1.1.1        |
| memoist                         | 0.16.2       |
| googleauth                      | 0.16.2       |
| mini_mime                       | 1.1.0        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.1        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| google-apis-core                | 0.4.0        |
| google-apis-playcustomapp_v1    | 0.4.0        |
| google-apis-androidpublisher_v3 | 0.7.0        |
| rake                            | 13.0.3       |
| digest-crc                      | 0.6.3        |
| google-apis-storage_v1          | 0.5.0        |
| google-apis-iamcredentials_v1   | 0.5.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.32.0       |
| aws-partitions                  | 1.472.0      |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.115.0      |
| forwardable                     | 1.2.0        |
| logger                          | 1.3.0        |
| date                            | 2.0.0        |
| stringio                        | 0.0.2        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.0.0        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| io-console                      | 0.4.7        |
| fileutils                       | 1.1.0        |
| etc                             | 1.0.1        |
| libxml-ruby                     | 3.1.0        |
| psych                           | 3.1.0        |
| mutex_m                         | 0.1.0        |
</details>

*generated on:* **2021-07-07**
</details>

**Comment by vin-fandemand** [comment]
I have exhausted all possibilities. It works in my local machine as it has all the credentials. Running and failing build on Mac machines in the cloud is time-consuming as well as costly. Any help would be greatly appreciated.

**Comment by crazymanish** [comment]
Hello @vin-fandemand 
please use this github-action
https://github.com/joshdholtz/fastlane-plugin-github_action

in case of any issue, let continue discuss it here https://github.com/fastlane/fastlane/discussions/19035
