### ISSUE TITLE
firebase_app_distribution throw error

### ISSUE THREAD

**Issue by olindv** [fastlane/fastlane#19067]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
In connection with the latest news from Android, it became known that applications will soon switch to the AAB format. We decided to change the fastlane setting for creating `AAB` releases, namely, we changed the parameter `task` in the `build_android_app` from `assemble` to a `bundle`. After these changes, an error began to appear when calling the `distribute_firebase_staging` command. At first, the error looked like this `Could not find the APK. Make sure you set the APK path parameter to point to your APK` after which I updated the fastlane and other gems and the error changed to `Couldn't find binary` the error appears only when `build_android_app` has task parameters: `bundle`. We use fastlane in conjunction with firebase.

##### Command executed
<details><pre>
platform :android do
    # fastlane android distribute_firebase_staging build_number:190
    desc "Distribute Firebase Staging Android"
    lane :distribute_firebase_staging do |options|
        ENV['ENVFILE'] = '.env.staging'
        increment_version_code(version_code: ENV["CIRCLE_BUILD_NUM"])
        version_name = get_version_name(gradle_file_path: "android/app/build.gradle", ext_constant_name: "versionName")
        sh("yarn jetifier")
        gradle(task: "clean", project_dir: "./android")
        build_android_app(task: "bundle", build_type: "StagingRelease", project_dir: "./android")
        release_notes = generate_release_notes(
            type: "staging",
            platform: "android",
            version: version_name
        )
        firebase_app_distribution(app: "X:XXXXXX:android:XXXXX", release_notes: release_notes[:firebase], groups: "default-android")
        slack_message(channel: "#test", message: release_notes[:slack])
    end
end
</pre></details>

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> +-------------------------------------+----------------------------------------------------------------------------------------+
|                                                         Lane Context                                                         |
+-------------------------------------+----------------------------------------------------------------------------------------+
| PLATFORM_NAME                       | android                                                                                |
| LANE_NAME                           | android distribute_firebase_staging                                                    |
| VERSION_NAME                        | 1.231.1                                                                                |
| GRADLE_BUILD_TYPE                   | StagingRelease                                                                         |
| GRADLE_ALL_APK_OUTPUT_PATHS         | []                                                                                     |
| GRADLE_ALL_AAB_OUTPUT_PATHS         | ["/Users/myuser/projects/test/android/app/build/outputs/bundle/stagingRelease/   |
|                                     | app-stagingRelease.aab"]                                                               |
| GRADLE_ALL_OUTPUT_JSON_OUTPUT_PATHS | []                                                                                     |
| GRADLE_ALL_MAPPING_TXT_OUTPUT_PATHS | []                                                                                     |
| GRADLE_AAB_OUTPUT_PATH              | /Users/myuser/projects/test/android/app/build/outputs/bundle/stagingRelease/ap   |
|                                     | p-stagingRelease.aab                                                                   |
| FL_CHANGELOG                        |  • (User) - feat(NEX-3439): aab distributuion  • (User) -                |
|                                     | feat(xxx): aab distribution  • (User) - feat(xxx): aab distribution   |
|                                     | • (User) - feat(xxx): aab distrubution  • (User) -                  |
|                                     | feat(xxx): aab distribution                                                       |
+-------------------------------------+----------------------------------------------------------------------------------------+
[18:58:44]: Couldn't find binary

+------+------------------------------------------------+-------------+
|                          fastlane summary                           |
+------+------------------------------------------------+-------------+
| Step | Action                                         | Time (in s) |
+------+------------------------------------------------+-------------+
| 1    | update_fastlane                                | 2           |
| 2    | setup_circle_ci                                | 0           |
| 3    | Switch to android increment_version_code lane  | 0           |
| 4    | get_version_name                               | 0           |
| 5    | yarn jetifier                                  | 8           |
| 6    | clean                                          | 31          |
| 7    | bundleStagingRelease                           | 330         |
| 8    | Switch to android generate_release_notes lane  | 0           |
| 9    | Switch to android commits_based_changelog lane | 0           |
| 10   | changelog_from_git_commits                     | 0           |
| 11   | Switch to android commits_based_changelog lane | 0           |
| 12   | changelog_from_git_commits                     | 0           |
| 💥   | firebase_app_distribution                      | 0           |
+------+------------------------------------------------+-------------+

[18:58:44]: fastlane finished with errors

[!] Couldn't find binary </pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.4                                                           |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.31.1                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.4 (20F71)                                             |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.5.1                                                         |
| Swift Version               | 5.4.2                                                          |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Service lanes
import "./lanes/IncrementVersionCodeFastfile"
import "./lanes/SlackMessageFastfile"
import "./lanes/Changelog.Fastfile"

# Platform lanes
import "./lanes/platform/Ios.Fastfile"
import "./lanes/platform/Android.Fastfile"

before_all do
    update_fastlane
    setup_circle_ci
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.myproject.test") # The bundle identifier of your app

# Specify below your email attached to your apple id
apple_id("user@gmail.com")

itc_team_id("XXXXXX") # App Store Connect Team ID
team_id("XXXXXX") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

json_key_file("") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("com.project.test") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.187.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-get_version_name          | 0.2.2   | ✅ Up-To-Date  |
| fastlane-plugin-firebase_app_distribution | 0.2.9   | ✅ Up-To-Date  |
| fastlane-plugin-semantic_release          | 1.13.1  | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.3.0        |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.7.0        |
| terminal-table                            | 1.8.0        |
| plist                                     | 3.6.0        |
| multipart-post                            | 2.0.0        |
| word_wrap                                 | 1.0.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| artifactory                               | 3.0.15       |
| babosa                                    | 1.0.4        |
| colored                                   | 1.2          |
| highline                                  | 2.0.3        |
| commander                                 | 4.6.0        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.0.0        |
| gh_inspector                              | 1.1.3        |
| mini_magick                               | 4.11.0       |
| naturally                                 | 2.2.1        |
| security                                  | 0.1.3        |
| xcpretty-travis-formatter                 | 1.0.1        |
| dotenv                                    | 2.7.6        |
| bundler                                   | 1.17.2       |
| simctl                                    | 1.6.8        |
| retriable                                 | 3.1.2        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.1        |
| signet                                    | 0.15.0       |
| googleauth                                | 0.16.2       |
| httpclient                                | 2.8.3        |
| google-apis-core                          | 0.4.0        |
| google-apis-playcustomapp_v1              | 0.5.0        |
| google-apis-androidpublisher_v3           | 0.8.0        |
| google-cloud-env                          | 1.5.0        |
| google-cloud-core                         | 1.6.0        |
| digest-crc                                | 0.6.3        |
| google-cloud-storage                      | 1.34.0       |
| emoji_regex                               | 3.2.2        |
| rexml                                     | 3.2.5        |
| nanaimo                                   | 0.3.0        |
| colored2                                  | 3.1.2        |
| claide                                    | 1.0.3        |
| CFPropertyList                            | 3.0.3        |
| atomos                                    | 0.1.3        |
| xcodeproj                                 | 1.20.0       |
| public_suffix                             | 4.0.6        |
| addressable                               | 2.8.0        |
| excon                                     | 0.84.0       |
| ruby2_keywords                            | 0.0.4        |
| faraday-patron                            | 1.0.0        |
| faraday-net_http_persistent               | 1.1.0        |
| faraday-net_http                          | 1.0.1        |
| faraday-httpclient                        | 1.0.1        |
| faraday-excon                             | 1.1.0        |
| faraday-em_synchrony                      | 1.0.0        |
| faraday-em_http                           | 1.0.0        |
| faraday                                   | 1.5.0        |
| unf_ext                                   | 0.0.7.7      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| http-cookie                               | 1.0.4        |
| fastimage                                 | 2.2.4        |
| json                                      | 2.5.1        |
| rubyzip                                   | 2.3.2        |
| jwt                                       | 2.2.3        |
| trailblazer-option                        | 0.1.1        |
| declarative                               | 0.0.20       |
| uber                                      | 0.1.0        |
| representable                             | 3.1.1        |
| mini_mime                                 | 1.1.0        |
| webrick                                   | 1.7.0        |
| google-cloud-errors                       | 1.1.0        |
| google-apis-iamcredentials_v1             | 0.6.0        |
| google-apis-storage_v1                    | 0.6.0        |
| rake                                      | 13.0.5       |
| aws-eventstream                           | 1.1.1        |
| aws-sigv4                                 | 1.2.3        |
| aws-partitions                            | 1.474.0      |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.116.0      |
| aws-sdk-kms                               | 1.44.0       |
| aws-sdk-s3                                | 1.96.1       |
| forwardable                               | 1.2.0        |
| logger                                    | 1.3.0        |
| date                                      | 2.0.0        |
| stringio                                  | 0.0.2        |
| ipaddr                                    | 1.2.2        |
| openssl                                   | 2.1.2        |
| zlib                                      | 1.0.0        |
| mutex_m                                   | 0.1.0        |
| ostruct                                   | 0.1.0        |
| strscan                                   | 1.0.0        |
| io-console                                | 0.4.7        |
| fileutils                                 | 1.1.0        |
| etc                                       | 1.0.1        |
| libxml-ruby                               | 3.1.0        |
| psych                                     | 3.1.0        |
| fastlane-plugin-get_version_name          | 0.2.2        |
| fastlane-plugin-firebase_app_distribution | 0.2.9        |
| fastlane-plugin-semantic_release          | 1.13.1       |
</details>

*generated on:* **2021-07-08**
</details>

**Comment by lucgrabowski** [comment]
Hi @olindv Could you set `android_artifact_type` parameter to `AAB`? Will it help?
It looks like the plugin supports both `AAB` and `APK` and `APK` is default option:
https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/blob/4bb1f05d3af8f9339d0e65e3c0e10c3df468e442/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb#L178-L186

**Comment by olindv** [comment]
Hello @lucgrabowski ! Thank you very much for ur prompt reply. Issue solved!
