### ISSUE TITLE
Timeout after login successful

### ISSUE THREAD

**Issue by cherpake** [fastlane/fastlane#19085]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Trying to upload a new build to AppStore - fastlane fails with 'Server error got 500'

##### Command executed
fastlane deliver --ignore_language_directory_validation --precheck_include_in_app_purchases false -x false --force --skip_binary_upload --skip_screenshots --verbose

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>cherpake@control (master) $ fastlane deliver --ignore_language_directory_validation --precheck_include_in_app_purchases false -x false --force --skip_binary_upload --skip_screenshots --verbose
[✔] 🚀 
[13:17:53]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
Successfully loaded Appfile at path '/Users/cherpake/Code/source/apps/control/fastlane/Appfile'
- app_identifier: 'com.xxxxx'
- apple_id: 'xxxxx@gmail.com'
- itc_team_id: 'xxxxxx'
- team_id: 'xxxxx'
-------
INFO [2021-07-12 13:17:54.38]: Successfully loaded '/Users/cherpake/Code/source/apps/control/fastlane/Deliverfile' 📄
WARN [2021-07-12 13:17:54.38]: No values defined in './fastlane/Deliverfile'
INFO [2021-07-12 13:17:54.38]: Login to App Store Connect (xxxxx@gmail.com)
Reading keychain entry, because either user or password were empty
Loading session from '/Users/cherpake/.fastlane/spaceship/xxxxx@gmail.com/cookie'
Looking for App Store Connect Team with ID xxxxxx
INFO [2021-07-12 13:17:59.81]: Login successful
Timeout received! Retrying after 3 seconds (remaining: 5)...
Timeout received! Retrying after 3 seconds (remaining: 4)...
Timeout received! Retrying after 3 seconds (remaining: 3)...
Timeout received! Retrying after 3 seconds (remaining: 2)...
Timeout received! Retrying after 3 seconds (remaining: 1)...

Looking for related GitHub issues on fastlane/fastlane...
Search query: The request could not be completed because:
	Server error got 500

URL: https://api.github.com/search/issues?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09Server%20error%20got%20500+repo:fastlane/fastlane
➡️  beta_pa path is relative to the fastlane directory, not the project directory
    https://github.com/fastlane/fastlane/issues/500 [closed] 4 💬
    22 Sep 2016

➡️  [deliver][spaceship] 500 server error - creating new App Store version
    https://github.com/fastlane/fastlane/issues/17886 [closed] 87 💬
    2 weeks ago

➡️  Deliver fails with error 500 on price tire update phase
    https://github.com/fastlane/fastlane/issues/17736 [closed] 11 💬
    2 weeks ago

and 25 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09Server%20error%20got%20500&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	21: from /usr/local/Cellar/fastlane/2.187.0/libexec/bin/fastlane:23:in `<main>'
	20: from /usr/local/Cellar/fastlane/2.187.0/libexec/bin/fastlane:23:in `load'
	19: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/fastlane-2.187.0/bin/fastlane:23:in `<top (required)>'
	18: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/fastlane-2.187.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	17: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/fastlane-2.187.0/deliver/lib/deliver/commands_generator.rb:18:in `start'
	16: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/fastlane-2.187.0/deliver/lib/deliver/commands_generator.rb:187:in `run'
	15: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	14: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	13: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	12: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	11: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	10: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/fastlane-2.187.0/deliver/lib/deliver/commands_generator.rb:82:in `block (2 levels) in run'
	 9: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/fastlane-2.187.0/deliver/lib/deliver/commands_generator.rb:82:in `new'
	 8: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/fastlane-2.187.0/deliver/lib/deliver/runner.rb:24:in `initialize'
	 7: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/fastlane-2.187.0/deliver/lib/deliver/detect_values.rb:17:in `run!'
	 6: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/fastlane-2.187.0/deliver/lib/deliver/detect_values.rb:46:in `find_app'
	 5: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/fastlane-2.187.0/spaceship/lib/spaceship/connect_api/models/app.rb:80:in `find'
	 4: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/fastlane-2.187.0/spaceship/lib/spaceship/connect_api/models/app.rb:74:in `all'
	 3: from /usr/local/Cellar/ruby@2.7/2.7.3/lib/ruby/2.7.0/forwardable.rb:235:in `get_apps'
	 2: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/fastlane-2.187.0/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:22:in `get_apps'
	 1: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/fastlane-2.187.0/spaceship/lib/spaceship/connect_api/api_client.rb:113:in `get'
/usr/local/Cellar/fastlane/2.187.0/libexec/gems/fastlane-2.187.0/spaceship/lib/spaceship/connect_api/api_client.rb:191:in `handle_response': Server error got 500 (Spaceship::InternalServerError)
	21: from /usr/local/Cellar/fastlane/2.187.0/libexec/bin/fastlane:23:in `<main>'
	20: from /usr/local/Cellar/fastlane/2.187.0/libexec/bin/fastlane:23:in `load'
	19: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/fastlane-2.187.0/bin/fastlane:23:in `<top (required)>'
	18: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/fastlane-2.187.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	17: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/fastlane-2.187.0/deliver/lib/deliver/commands_generator.rb:18:in `start'
	16: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/fastlane-2.187.0/deliver/lib/deliver/commands_generator.rb:187:in `run'
	15: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	14: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	13: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	12: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	11: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	10: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/fastlane-2.187.0/deliver/lib/deliver/commands_generator.rb:82:in `block (2 levels) in run'
	 9: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/fastlane-2.187.0/deliver/lib/deliver/commands_generator.rb:82:in `new'
	 8: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/fastlane-2.187.0/deliver/lib/deliver/runner.rb:24:in `initialize'
	 7: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/fastlane-2.187.0/deliver/lib/deliver/detect_values.rb:17:in `run!'
	 6: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/fastlane-2.187.0/deliver/lib/deliver/detect_values.rb:46:in `find_app'
	 5: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/fastlane-2.187.0/spaceship/lib/spaceship/connect_api/models/app.rb:80:in `find'
	 4: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/fastlane-2.187.0/spaceship/lib/spaceship/connect_api/models/app.rb:74:in `all'
	 3: from /usr/local/Cellar/ruby@2.7/2.7.3/lib/ruby/2.7.0/forwardable.rb:235:in `get_apps'
	 2: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/fastlane-2.187.0/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:22:in `get_apps'
	 1: from /usr/local/Cellar/fastlane/2.187.0/libexec/gems/fastlane-2.187.0/spaceship/lib/spaceship/connect_api/api_client.rb:113:in `get'
/usr/local/Cellar/fastlane/2.187.0/libexec/gems/fastlane-2.187.0/spaceship/lib/spaceship/connect_api/api_client.rb:191:in `handle_response': \e[31m[!] The request could not be completed because: (Spaceship::InternalServerError)
	Server error got 500\e[0m </pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 12.0                                                    |
| Ruby                        | 2.7.3                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.32.0                                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.187.0/libexec/bin/fastlane |
| Host                        | macOS 12.0 (21A5268h)                                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.7/2.7.3/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                             |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 12.5.1                                                  |
| Swift Version               | 5.4.2                                                   |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :deploy do
	cocoapods
    increment_build_number(xcodeproj: "Control.xcodeproj")
    add_git_tag(prefix: "rc-master-")
    commit_version_bump(message: "AppStore: Version Bump", xcodeproj: "./Control.xcodeproj")
    build_app(workspace: "Control.xcworkspace", scheme: "Control", export_xcargs: "-allowProvisioningUpdates")
# 	upload_to_app_store(ignore_language_directory_validation: true, force: true, skip_screenshots: false, overwrite_screenshots: true)
	upload_to_app_store(ignore_language_directory_validation: true, force: true, skip_screenshots: true)
  end
  
  lane :upload do
	upload_to_app_store(ignore_language_directory_validation: true, force: true, skip_screenshots: true)
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.cherpake.macrc.adsfree") # The bundle identifier of your app
apple_id("d314127481@gmail.com") # Your Apple email address

itc_team_id("2028706") # App Store Connect Team ID
team_id("MCKT7VHXP5") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.187.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.4.0        |
| atomos                          | 0.1.3        |
| CFPropertyList                  | 3.0.3        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.19.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.7.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.83.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.1.0        |
| ruby2_keywords                  | 0.0.4        |
| faraday                         | 1.4.3        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.0.0        |
| fastimage                       | 2.2.4        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.3.0        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.0        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.15       |
| simctl                          | 1.6.8        |
| jwt                             | 2.2.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.1        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| signet                          | 0.15.0       |
| googleauth                      | 0.16.2       |
| httpclient                      | 2.8.3        |
| rexml                           | 3.2.3.1      |
| webrick                         | 1.6.1        |
| google-apis-core                | 0.4.0        |
| google-apis-playcustomapp_v1    | 0.4.0        |
| google-apis-androidpublisher_v3 | 0.7.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.5.0        |
| google-apis-storage_v1          | 0.5.0        |
| rake                            | 13.0.3       |
| digest-crc                      | 0.6.3        |
| google-cloud-storage            | 1.32.0       |
| emoji_regex                     | 3.2.2        |
| jmespath                        | 1.4.0        |
| aws-partitions                  | 1.472.0      |
| aws-eventstream                 | 1.1.1        |
| aws-sigv4                       | 1.2.3        |
| aws-sdk-core                    | 3.115.0      |
| aws-sdk-kms                     | 1.44.0       |
| aws-sdk-s3                      | 1.96.1       |
| uri                             | 0.10.0       |
| forwardable                     | 1.3.1        |
| logger                          | 1.4.2        |
| cgi                             | 0.1.0        |
| date                            | 3.0.0        |
| timeout                         | 0.1.0        |
| stringio                        | 0.1.0        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.1.0        |
| ostruct                         | 0.2.0        |
| strscan                         | 1.0.3        |
| io-console                      | 0.5.6        |
| delegate                        | 0.1.0        |
| fileutils                       | 1.4.1        |
| singleton                       | 0.1.0        |
| open3                           | 0.1.0        |
| yaml                            | 0.1.0        |
| psych                           | 3.1.0        |
| mutex_m                         | 0.1.0        |
</details>

*generated on:* **2021-07-12**
</details></pre>
</details>

**Comment by cherpake** [comment]
I know I'm running macOS 12 Beta - but this used to work couple of days ago just fine.

**Comment by cmartinezv** [comment]
Seems App Store Connect is down, I can't acces to my apps from the web either.

**Comment by cherpake** [comment]
Hmm... it looked that way for a moment here. But then it returned - and now I'm able to sign in and it seems like its working.

**Comment by cherpake** [comment]
Oh spoke too soon :/ seems its not.

**Comment by cmartinezv** [comment]
you broke it, you fix it :P

**Comment by cherpake** [comment]
AppStore was down.
