### ISSUE TITLE
Unable to access URL using `push_to_git_remote`

### ISSUE THREAD

**Issue by jbatra-umeey** [fastlane/fastlane#19088]
### Issue Description
<details>
Initially, I was getting the below :

```
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.186.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': [!] Exit status of command 'git push origin Development:Development --tags' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
error: src refspec Development does not match any
error: failed to push some refs to '/Users/user/Development/Personal/Project/APP'
```
But, I was able to fix this after following the instructions mentioned https://github.com/fastlane/fastlane/issues/7588#issuecomment-274462956

This worked locally but It's not working when I run the CI via Gitlab. I get the below error :

```
[23:29:26]: Exit status of command 'git push origin HEAD:Development --tags --force' was 128 instead of 0.
2583 remote: You are not allowed to upload code.
2584 fatal: unable to access 'URL': The requested URL returned an error: 403
```

I presume there is some issue with authentication, but I'm not sure how I can inject details in https://docs.fastlane.tools/actions/push_to_git_remote/#push_to_git_remote to fix it.

</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.7                                     |
| Ruby                        | 2.7.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.rvm/gems/ruby-2.7.2/bin/fastlane         |
| Host                        | Mac OS X 10.15.7 (19H1030)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.7.2/lib                |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.4                                        |
| Swift Version               | 5.3.2                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


fastlane_require 'dotenv'
before_all do
  Dotenv.overload '.env.secret'
    puts Dotenv.overload
end

default_platform(:ios)
platform :ios do
  desc "Build Application"
  lane :build do
    clear_derived_data
    clean_build_artifacts
     cocoapods(use_bundle_exec: false)
     gym(scheme: ENV['SCHEME'], skip_archive: true)

   end

 lane: deploy do

    clear_derived_data
    clean_build_artifacts
    cocoapods(use_bundle_exec: false)
    gym(scheme: ENV['SCHEME'])

    api_key = app_store_connect_api_key(
        key_id: ENV['KEY'],
        issuer_id: ENV['ISSUE'],
        key_filepath: "AuthKey_XXX.p8",
       duration: 1200, # optional (maximum 1200)
       in_house: false # optional but may be required if using match/sigh
    )

    pilot(api_key: api_key,
       distribute_external: true,
       skip_submission: true,
       notify_external_testers: false,
       skip_waiting_for_build_processing: false,
       groups: ["HelloWorld Beta Testers"], # Maybe we should create groups
       changelog: File.read("changelog.txt")
    )

    
    # push_to_git_remote(remote: "origin", remote_branch: ENV['BRANCH'])
 
    upload_symbols_to_crashlytics

push_to_git_remote(
      remote: "origin",         # optional, default: "origin"
      local_branch: "HEAD",  # optional, aliased by "branch", default: "master"
      remote_branch: ENV['BRANCH'], # optional, default is set to local_branch
      force: true,    # optional, default: false
    )
   end

   lane :versioning do
     increment_build_number
     commit_version_bump(
           message: 'Build Version Bump by fastlane',
           force: true,
           xcodeproj: "./XXX.xcodeproj"  # optional, if you have multiple Xcode project files, you must specify your main project here
         )

      build_number = Actions.lane_context[Actions::SharedValues::BUILD_NUMBER]
      add_git_tag(tag: "testflight-#{build_number}-#{ENV['TAG']}")
   end

  end

```
</details>

<details><summary>`./Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.185.1 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.4.0        |
| executable-hooks                | 1.6.1        |
| bundler-unload                  | 1.0.2        |
| rubygems-bundler                | 1.4.5        |
| bundler                         | 2.2.20       |
| rake                            | 13.0.3       |
| CFPropertyList                  | 3.0.3        |
| concurrent-ruby                 | 1.1.9        |
| i18n                            | 1.8.10       |
| minitest                        | 5.14.4       |
| thread_safe                     | 0.3.6        |
| tzinfo                          | 1.2.9        |
| activesupport                   | 5.2.6        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.7.0        |
| httpclient                      | 2.8.3        |
| json                            | 2.5.1        |
| algoliasearch                   | 1.27.5       |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.1.1        |
| aws-partitions                  | 1.469.0      |
| aws-sigv4                       | 1.2.3        |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.114.3      |
| aws-sdk-kms                     | 1.44.0       |
| aws-sdk-s3                      | 1.96.1       |
| babosa                          | 1.0.4        |
| claide                          | 1.0.3        |
| fuzzy_match                     | 2.0.4        |
| nap                             | 1.1.0        |
| netrc                           | 0.11.0       |
| ffi                             | 1.15.3       |
| ethon                           | 0.14.0       |
| typhoeus                        | 1.4.0        |
| cocoapods-core                  | 1.10.1       |
| cocoapods-deintegrate           | 1.0.4        |
| cocoapods-downloader            | 1.4.0        |
| cocoapods-plugins               | 1.0.0        |
| cocoapods-search                | 1.0.0        |
| cocoapods-trunk                 | 1.5.0        |
| cocoapods-try                   | 1.2.0        |
| colored2                        | 3.1.2        |
| escape                          | 0.0.4        |
| fourflusher                     | 2.3.1        |
| gh_inspector                    | 1.1.3        |
| molinillo                       | 0.6.6        |
| ruby-macho                      | 1.4.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.19.0       |
| cocoapods                       | 1.10.1       |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.3        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.2        |
| excon                           | 0.82.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.1.0        |
| multipart-post                  | 2.0.0        |
| ruby2_keywords                  | 0.0.4        |
| faraday                         | 1.4.2        |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.0.0        |
| fastimage                       | 2.2.4        |
| jwt                             | 2.2.3        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| signet                          | 0.15.0       |
| googleauth                      | 0.16.2       |
| mini_mime                       | 1.1.0        |
| trailblazer-option              | 0.1.1        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| rexml                           | 3.2.5        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.3.0        |
| google-apis-androidpublisher_v3 | 0.6.0        |
| google-apis-playcustomapp_v1    | 0.3.0        |
| google-apis-iamcredentials_v1   | 0.4.0        |
| google-apis-storage_v1          | 0.4.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.31.1       |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.0        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
</details>

*generated on:* **2021-07-13**
</details>

**Comment by lucgrabowski** [comment]
@jbatra-umeey Hi, have you tried to `git push` from terminal? What was the result?

**Comment by jbatra-umeey** [comment]
Yes, the following commands work fine when tried locally

-  sh('git', 'pull')
-  sh('git', 'push')

 
Also, the below command works as mentioned in https://github.com/fastlane/fastlane/issues/7588#issuecomment-274462956

```
push_to_git_remote(
      remote: "origin",         # optional, default: "origin"
      local_branch: "HEAD",  # optional, aliased by "branch", default: "master"
      remote_branch: "development", # optional, default is set to local_branch
      force: true,    # optional, default: false
      tags: true     # optional, default: true
    )
```

Do I need to add some `git config` for this to work?

**Comment by lucgrabowski** [comment]
I meant running git push command in terminal, not from fastlane or a ruby script to see that it's possible to push and that the repository rights are fine.
Is ENV['BRANCH'] defined properly? Your first call resulted in `git push origin HEAD:Development` and you say that if you hardcode `remote_branch` to `development` it works.

**Comment by jbatra-umeey** [comment]
@lucgrabowski 
Yes, when I try `git push origin HEAD: Development`, it works fine. For this run, via Fastlane I had to add additional params in 
`push_to_git_remote` as mentioned https://github.com/fastlane/fastlane/issues/19088#issuecomment-878910111

Below the stack trace from Gitlab

```
 [23:07:56]: $ git push origin HEAD:Development --tags --force
 [23:07:58]: ▸ remote: You are not allowed to upload code.
 [23:07:58]: ▸ fatal: unable to access 'URL': The requested URL returned error: 403
 +---------------------------+------------------------------------------------------------------------------------------------------+
 |                                                           Lane Context                                                           |
 +---------------------------+------------------------------------------------------------------------------------------------------+
 | ENVIRONMENT               | STAG                                                                                                 |
 | DEFAULT_PLATFORM          | ios                                                                                                  |
 | PLATFORM_NAME             | ios                                                                                                  |
 | LANE_NAME                 | ios deploy                                                                                           |
 | SIGH_PROFILE_PATHS        |                                                                                                      |
 | DSYM_PATHS                |                                                                                                      |
 | DSYM_LATEST_UPLOADED_DATE |                                                                                                      |
 | IPA_OUTPUT_PATH           | /Users/user/builds/K4rAvYXo/0/xx/ttap_app/XX.ipa                                    |
 | XCODEBUILD_ARCHIVE        | /Users/user/Library/Developer/Xcode/Archives/2021-07-12/XX 2021-07-12 22.47.32.xcarchive |
 | DSYM_OUTPUT_PATH          | /Users/user/builds/K4rAvYXo/0/xx/ttap_app/XX.app.dSYM.zip                           |
 +---------------------------+------------------------------------------------------------------------------------------------------+
 [23:07:58]: Exit status of command 'git push origin HEAD:Development --tags --force' was 128 instead of 0.
 remote: You are not allowed to upload code.
 fatal: unable to access URL': The requested URL returned error: 403
 +------+---------------------------+-------------+
 |                fastlane summary                |
 +------+---------------------------+-------------+
 | Step | Action                    | Time (in s) |
 +------+---------------------------+-------------+
 | 1    | default_platform          | 0           |
 | 2    | clear_derived_data        | 22          |
 | 3    | clean_build_artifacts     | 0           |
 | 4    | cocoapods                 | 15          |
 | 5    | gym                       | 426         |
 | 6    | app_store_connect_api_key | 0           |
 | 7    | pilot                     | 810         |
 | 💥   | push_to_git_remote        | 2           |
 +------+---------------------------+-------------+
 [23:07:58]: fastlane finished with errors
 Looking for related GitHub issues on fastlane/fastlane...
 ➡️  silent option is not available in ipa block
     https://github.com/fastlane/fastlane/issues/403 [closed] 4 💬
     22 Sep 2016
 ➡️  Adds more options to the `slack` command
     https://github.com/fastlane/fastlane/pull/128 [closed] 3 💬
     04 Feb 2017
 🔗  You can ⌘ + double-click on links to open them directly in your browser.
 #######################################################################
```

From the logs, it seems the branch name is passed correctly.

**Comment by Gillon6** [comment]
If the website is down, there's not much you can do until it comes back up. Check back after a while to see if anything changes. If you know the site is back up but you still can't access it, clear your browser cache and then try again.

**Comment by jbatra-umeey** [comment]
@Gillon6 @lucarge 

I tried to add the script in gitlab.yml and I get the below error

```
Executing "step_script" stage of the job script
00:01
 $ unset cd
 $ git remote set-url origin https://$GIT_USER:$GIT_TOKEN@ttap.XXX.com/XXX/ttap_app.git
 $ cd fastlane
 $ git push
 fatal: You are not currently on a branch.
 To push the history leading to the current (detached HEAD)
 state now, use
     git push origin HEAD:<name-of-remote-branch>
Cleaning up file based variables
00:02
 ERROR: Job failed: exit status 1
 ```
