### ISSUE TITLE
Filter testers by the app

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1909]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/1086260?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @kostiakoval - Imported from <a href='https://github.com/fastlane/pilot/issues/52'>fastlane/pilot#52</a>
        </td>
      </tr>
    </table>

## New feature request: 

I Want to be able to filter the testers by the app ID.
`pilot list -a no.myCompanyID.MyappID`

**Comment by jaleksynas** [comment]
issue 85 above (refers to pilot/85) -- migrated to #1895
