### ISSUE TITLE
firebase_app_distribution fails to execute, with no details

### ISSUE THREAD

**Issue by RodrigoSosa95** [fastlane/fastlane#19102]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Cannot run firebase_app_distribution, the script just ends with a `Couldn't find binary` error

##### Command executed

firebase_app_distribution

##### Complete output when running fastlane, including the stack trace and command used

```

ERROR [2021-07-14 16:20:25.08]: fastlane finished with errors
bundler: failed to load command: fastlane (/Users/grainchain/.rbenv/versions/2.6.6/bin/fastlane)
Traceback (most recent call last):
        43: from /Users/grainchain/.rbenv/versions/2.6.6/bin/bundle:23:in `<main>'
        42: from /Users/grainchain/.rbenv/versions/2.6.6/bin/bundle:23:in `load'
        41: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.23/exe/bundle:37:in `<top (required)>'
        40: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.23/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
        39: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.23/exe/bundle:49:in `block in <top (required)>'
        38: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.23/lib/bundler/cli.rb:24:in `start'
        37: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.23/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        36: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.23/lib/bundler/cli.rb:30:in `dispatch'
        35: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.23/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        34: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.23/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        33: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.23/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        32: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.23/lib/bundler/cli.rb:474:in `exec'
        31: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.23/lib/bundler/cli/exec.rb:28:in `run'
        30: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.23/lib/bundler/cli/exec.rb:63:in `kernel_load'
        29: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.23/lib/bundler/cli/exec.rb:63:in `load'
        28: from /Users/grainchain/.rbenv/versions/2.6.6/bin/fastlane:23:in `<top (required)>'
        27: from /Users/grainchain/.rbenv/versions/2.6.6/bin/fastlane:23:in `load'
        26: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/bin/fastlane:23:in `<top (required)>'
        25: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
        24: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
        23: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
        22: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        21: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        20: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        19: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        18: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        17: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
        16: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        15: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        14: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        13: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        12: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        11: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        10: from Fastfile:23:in `block (2 levels) in parsing_binding'
         9: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
         8: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
         7: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
         6: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
         5: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
         4: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
         3: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
         2: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-plugin-firebase_app_distribution-0.2.9/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb:25:in `run'
         1: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': Couldn't find binary (FastlaneCore::Interface::FastlaneError)
        43: from /Users/grainchain/.rbenv/versions/2.6.6/bin/bundle:23:in `<main>'
        42: from /Users/grainchain/.rbenv/versions/2.6.6/bin/bundle:23:in `load'
        41: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.23/exe/bundle:37:in `<top (required)>'
        40: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.23/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
        39: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.23/exe/bundle:49:in `block in <top (required)>'
        38: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.23/lib/bundler/cli.rb:24:in `start'
        37: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.23/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        36: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.23/lib/bundler/cli.rb:30:in `dispatch'
        35: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.23/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        34: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.23/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        33: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.23/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        32: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.23/lib/bundler/cli.rb:474:in `exec'
        31: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.23/lib/bundler/cli/exec.rb:28:in `run'
        30: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.23/lib/bundler/cli/exec.rb:63:in `kernel_load'
        29: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.23/lib/bundler/cli/exec.rb:63:in `load'
        28: from /Users/grainchain/.rbenv/versions/2.6.6/bin/fastlane:23:in `<top (required)>'
        27: from /Users/grainchain/.rbenv/versions/2.6.6/bin/fastlane:23:in `load'
        26: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/bin/fastlane:23:in `<top (required)>'
        25: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
        24: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
        23: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
        22: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        21: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        20: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        19: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        18: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        17: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
        16: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        15: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        14: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        13: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        12: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        11: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        10: from Fastfile:23:in `block (2 levels) in parsing_binding'
         9: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
         8: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
         7: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
         6: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
         5: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
         4: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
         3: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
         2: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-plugin-firebase_app_distribution-0.2.9/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb:25:in `run'
         1: from /Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/grainchain/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Couldn't find binary (FastlaneCore::Interface::FastlaneError)

```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.4                                        |
| Ruby                        | 2.6.6                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.30.1 (Apple Git-130)          |
| Installation Source         | ~/.rbenv/versions/2.6.6/bin/fastlane        |
| Host                        | macOS 11.4 (20F71)                          |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.6/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.5                                        |
| Swift Version               | 5.4                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Deploy to firebase app distribution"
  lane :distribute do
      # increment_build_number(xcodeproj: "silosys_mobile.xcodeproj")
      # build_app(scheme: "silosys_mobile", workspace: "silosys_mobile.xcworkspace")
      firebase_app_distribution(
          app: ENV["FIREBASE_IOS_APP_ID"],
          testers_file: "../../testers.txt",
          release_notes_file: "../../release-notes.txt",
          firebase_cli_token: ENV["FIREBASE_TOKEN"],
          debug: true
      )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby

# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile
app_identifier("io.grainchain.silosys-mobile")
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.187.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.2.9   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.3.0        |
| bundler                                   | 2.2.23       |
| rake                                      | 13.0.6       |
| CFPropertyList                            | 3.0.3        |
| public_suffix                             | 4.0.6        |
| addressable                               | 2.8.0        |
| artifactory                               | 3.0.15       |
| atomos                                    | 0.1.3        |
| aws-eventstream                           | 1.1.1        |
| aws-partitions                            | 1.478.0      |
| aws-sigv4                                 | 1.2.4        |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.117.0      |
| aws-sdk-kms                               | 1.44.0       |
| aws-sdk-s3                                | 1.96.1       |
| babosa                                    | 1.0.4        |
| claide                                    | 1.0.3        |
| colored                                   | 1.2          |
| colored2                                  | 3.1.2        |
| highline                                  | 2.0.3        |
| commander                                 | 4.6.0        |
| declarative                               | 0.0.20       |
| digest-crc                                | 0.6.3        |
| unf_ext                                   | 0.0.7.7      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| dotenv                                    | 2.7.6        |
| emoji_regex                               | 3.2.2        |
| excon                                     | 0.84.0       |
| faraday-em_http                           | 1.0.0        |
| faraday-em_synchrony                      | 1.0.0        |
| faraday-excon                             | 1.1.0        |
| faraday-httpclient                        | 1.0.1        |
| faraday-net_http                          | 1.0.1        |
| faraday-net_http_persistent               | 1.2.0        |
| faraday-patron                            | 1.0.0        |
| multipart-post                            | 2.0.0        |
| ruby2_keywords                            | 0.0.4        |
| faraday                                   | 1.5.1        |
| http-cookie                               | 1.0.4        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.0.0        |
| fastimage                                 | 2.2.4        |
| gh_inspector                              | 1.1.3        |
| jwt                                       | 2.2.3        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.1        |
| signet                                    | 0.15.0       |
| googleauth                                | 0.16.2       |
| httpclient                                | 2.8.3        |
| mini_mime                                 | 1.1.0        |
| trailblazer-option                        | 0.1.1        |
| uber                                      | 0.1.0        |
| representable                             | 3.1.1        |
| retriable                                 | 3.1.2        |
| rexml                                     | 3.2.5        |
| webrick                                   | 1.7.0        |
| google-apis-core                          | 0.4.0        |
| google-apis-androidpublisher_v3           | 0.8.0        |
| google-apis-playcustomapp_v1              | 0.5.0        |
| google-apis-iamcredentials_v1             | 0.6.0        |
| google-apis-storage_v1                    | 0.6.0        |
| google-cloud-env                          | 1.5.0        |
| google-cloud-errors                       | 1.1.0        |
| google-cloud-core                         | 1.6.0        |
| google-cloud-storage                      | 1.34.1       |
| json                                      | 2.5.1        |
| mini_magick                               | 4.11.0       |
| naturally                                 | 2.2.1        |
| plist                                     | 3.6.0        |
| rubyzip                                   | 2.3.2        |
| security                                  | 0.1.3        |
| simctl                                    | 1.6.8        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.7.0        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| word_wrap                                 | 1.0.0        |
| nanaimo                                   | 0.3.0        |
| xcodeproj                                 | 1.20.0       |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.1        |
| fastlane-plugin-firebase_app_distribution | 0.2.9        |
</details>

*generated on:* **2021-07-14**
</details>

**Comment by lucgrabowski** [comment]
Hi @RodrigoSosa95. 
I've taken a look at the plugin's code and it seems that based on your fastfile, the plugin will know that you try to upload iOS app, but it will not know which ipa file should be uploaded.
If you uncomment `build_app(scheme: "silosys_mobile", workspace: "silosys_mobile.xcworkspace")` it should figure this out.
https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/blob/2fb39170929323590b0877dcb5ac9cbf775a49a8/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb#L159-L162
Otherwise you need to use `ipa_path` parameter to point to binary if it's not in current directory:
https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/blob/2fb39170929323590b0877dcb5ac9cbf775a49a8/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb#L107-L112

**Comment by crazymanish** [comment]
Hi @RodrigoSosa95 

If the above suggestion also will not work, then I will recommend you to open the issue in `fastlane-plugin-firebase_app_distribution` git repo, They can help us much faster and release a new plugin version if required.
https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/issues

<img width="941" alt="Screenshot 2021-07-16 at 17 33 03" src="https://user-images.githubusercontent.com/5364500/125972870-bb4026b3-214f-4d7d-8d1e-6741b7350232.png">
