### ISSUE TITLE
get_provisioning_profile with platform "tvos" leads to **SystemStackError**

### ISSUE THREAD

**Issue by cynicer** [fastlane/fastlane#19108]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
get_provisioning_profile with platform "tvos" leads to **SystemStackError**

##### Command executed
`get_provisioning_profile(platform: tvos)`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [✔] 🚀
+----------------------------+---------+----------------------------------------------------------------------------------------+
|                                                         Used plugins                                                          |
+----------------------------+---------+----------------------------------------------------------------------------------------+
| Plugin                     | Version | Action                                                                                 |
+----------------------------+---------+----------------------------------------------------------------------------------------+
| fastlane-plugin-versioning | 0.4.6   | get_version_number_from_git_branch, increment_build_number_in_xcodeproj,               |
|                            |         | get_version_number_from_plist, get_build_number_from_plist, ci_build_number,           |
|                            |         | get_version_number_from_xcodeproj, increment_version_number_in_xcodeproj,              |
|                            |         | increment_version_number_in_plist, get_app_store_version_number, get_info_plist_path,  |
|                            |         | get_build_number_from_xcodeproj, increment_build_number_in_plist                       |
+----------------------------+---------+----------------------------------------------------------------------------------------+

[10:03:31]: ------------------------------
[10:03:31]: --- Step: default_platform ---
[10:03:31]: ------------------------------
[10:03:31]: Driving the lane 'ios tvos' 🚀
[10:03:31]: -------------------------------------
[10:03:31]: --- Step: Switch to ios tvos lane ---
[10:03:31]: -------------------------------------
[10:03:31]: Cruising over to lane 'ios tvos' 🚖
[10:03:31]: -------------------------------------
[10:03:31]: --- Step: Switch to ios tvos lane ---
[10:03:31]: -------------------------------------
[10:03:31]: Cruising over to lane 'ios tvos' 🚖
[10:03:31]: -------------------------------------
[10:03:31]: --- Step: Switch to ios tvos lane ---
[10:03:31]: -------------------------------------
[10:03:31]: Cruising over to lane 'ios tvos' 🚖
[10:03:31]: -------------------------------------
[10:03:31]: --- Step: Switch to ios tvos lane ---
[10:03:31]: -------------------------------------
[10:03:31]: Cruising over to lane 'ios tvos' 🚖
[10:03:31]: -------------------------------------
**[REMOVED REPEATING LINES FOR LENGTH]**
[10:03:31]: -------------------------------------
[10:03:32]: Cruising over to lane 'ios tvos' 🚖
[10:03:32]: -------------------------------------
[10:03:32]: --- Step: Switch to ios tvos lane ---
[10:03:32]: -------------------------------------
[10:03:32]: Cruising over to lane 'ios tvos' 🚖
[10:03:32]: -------------------------------------
[10:03:32]: --- Step: Switch to ios tvos lane ---
[10:03:32]: -------------------------------------
[10:03:32]: Cruising over to lane 'ios tvos' 🚖
[10:03:32]: -------------------------------------
[10:03:32]: --- Step: Switch to ios tvos lane ---
[10:03:32]: -------------------------------------
[10:03:32]: Cruising over to lane 'ios tvos' 🚖
+------------------+----------+
|        Lane Context         |
+------------------+----------+
| DEFAULT_PLATFORM | ios      |
| PLATFORM_NAME    | ios      |
| LANE_NAME        | ios tvos |
+------------------+----------+

+------+-------------------------+-------------+
|               fastlane summary               |
+------+-------------------------+-------------+
| Step | Action                  | Time (in s) |
+------+-------------------------+-------------+
| 1    | default_platform        | 0           |
| 2    | Switch to ios tvos lane | 0           |
| 3    | Switch to ios tvos lane | 0           |
**[REMOVED REPEATING LINES FOR LENGTH]**
| 1788 | Switch to ios tvos lane | 0           |
| 1789 | Switch to ios tvos lane | 0           |
+------+-------------------------+-------------+

[10:03:33]: fastlane finished with errors
bundler: failed to load command: fastlane (/Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bin/fastlane)
Traceback (most recent call last):
	8978: from /Users/user/.rbenv/versions/2.7.2/bin/bundle:23:in `<main>'
	8977: from /Users/user/.rbenv/versions/2.7.2/bin/bundle:23:in `load'
	8976: from /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.14/exe/bundle:37:in `<top (required)>'
	8975: from /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.14/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	8974: from /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.14/exe/bundle:49:in `block in <top (required)>'
	8973: from /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.14/lib/bundler/cli.rb:24:in `start'
	8972: from /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.14/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	8971: from /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.14/lib/bundler/cli.rb:30:in `dispatch'
	 ... 8966 levels...
	   4: from /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:89:in `header'
	   3: from /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/tty-screen-0.8.1/lib/tty/screen.rb:76:in `width'
	   2: from /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/tty-screen-0.8.1/lib/tty/screen.rb:64:in `size'
	   1: from /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/tty-screen-0.8.1/lib/tty/screen.rb:199:in `size_from_ioctl'
/Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/tty-screen-0.8.1/lib/tty/screen.rb:215:in `ioctl?': stack level too deep (SystemStackError) </pre>
</details>

### Environment

<details>
  <pre> <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.4                                        |
| Ruby                        | 2.7.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.30.1 (Apple Git-130)          |
| Installation Source         | ~/.rbenv/versions/2.7.2/bin/fastlane        |
| Host                        | macOS 11.4 (20F71)                          |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.2/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.5.1                                      |
| Swift Version               | 5.4.2                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

	lane :tvos do |options|

		get_provisioning_profile(platform: tvos)


	end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile
app_identifier("xxx")
itc_team_id("xxx")
team_id("xxx")

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.187.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-versioning | 0.4.6   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.0.0        |
| gh_inspector                    | 1.1.3        |
| security                        | 0.1.3        |
| dotenv                          | 2.7.6        |
| simctl                          | 1.6.8        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| googleauth                      | 0.16.2       |
| httpclient                      | 2.8.3        |
| google-apis-core                | 0.4.0        |
| google-apis-playcustomapp_v1    | 0.5.0        |
| google-apis-androidpublisher_v3 | 0.8.0        |
| uri                             | 0.10.0       |
| rexml                           | 3.2.5        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.0.3        |
| CFPropertyList                  | 3.0.3        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.20.0       |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| excon                           | 0.84.0       |
| ruby2_keywords                  | 0.0.5        |
| faraday-patron                  | 1.0.0        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-net_http                | 1.0.1        |
| faraday-httpclient              | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.5.1        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| fastimage                       | 2.2.4        |
| json                            | 2.5.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| xcpretty-travis-formatter       | 1.0.1        |
| bundler                         | 2.2.14       |
| jwt                             | 2.2.3        |
| trailblazer-option              | 0.1.1        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.0        |
| signet                          | 0.15.0       |
| webrick                         | 1.7.0        |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.3        |
| google-apis-storage_v1          | 0.6.0        |
| google-apis-iamcredentials_v1   | 0.6.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.34.1       |
| emoji_regex                     | 3.2.2        |
| aws-eventstream                 | 1.1.1        |
| aws-sigv4                       | 1.2.4        |
| aws-partitions                  | 1.478.0      |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.117.0      |
| aws-sdk-kms                     | 1.44.0       |
| aws-sdk-s3                      | 1.96.1       |
| forwardable                     | 1.3.1        |
| logger                          | 1.4.3        |
| cgi                             | 0.1.0        |
| date                            | 3.1.1        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.0        |
| openssl                         | 2.2.0        |
| ipaddr                          | 1.2.2        |
| zlib                            | 1.1.0        |
| mutex_m                         | 0.1.1        |
| ostruct                         | 0.3.3        |
| strscan                         | 3.0.0        |
| io-console                      | 0.5.9        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.1        |
| ox                              | 2.13.2       |
| fastlane-plugin-versioning      | 0.4.6        |
</details>

*generated on:* **2021-07-16**
</details> </pre>
</details>

**Comment by cynicer** [comment]
`platform :ios do`

That in combination with the platform parameter is the culprit. Since "tvos" platform wasn't supported according to the docs, I didn't even try to set it.

**Comment by lucgrabowski** [comment]
It happens because you have a lane called `tvos` that you call as a platform and you have a cycle (you can see how many times fastlane switches lane in summary). I think that you can easily fix it by using string or symbol as a platform name:
`get_provisioning_profile(platform: :tvos)`
`get_provisioning_profile(platform: "tvos")`

**Comment by cynicer** [comment]
Ah damn, that was obvious. Thanks!
