### ISSUE TITLE
User groups

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1911]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/101272?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @ahknight - Imported from <a href='https://github.com/fastlane/pilot/issues/46'>fastlane/pilot#46</a>
        </td>
      </tr>
    </table>

We use the user groups functionality in iTunes Connect for our beta tests a lot.  I don't see support for that in pilot at the moment.  Am I missing it?

What we do is recruit a set of testers, add them to the iTunes account in a user group ("MyApp Beta 1") and then add the group to the app.  This way we know which tests a user is on, and also why they're on the account in the first place (we have many, many apps in the account).

Is there a way to specify a group when importing a CSV so that the user is also added to that group (and have it created if it doesn't exist)?

**Comment by cybertk** [comment]
+1, this feature is still missing in latest **pilot v1.5.0**. Is there any update on this topic?

**Comment by vpolouchkine** [comment]
Thanks for bumping, we'll evaluate this.

**Comment by etolstoy** [comment]
+1

**Comment by cybertk** [comment]
Is there any updates?

**Comment by TKBurner** [comment]
Hi @cybertk We'd love to see an external PR on this, but haven't made any work internally. Thanks!

**Comment by cybertk** [comment]
This feature is still missing in latest **pilot v1.11.0**

**Comment by TKBurner** [comment]
@cybertk Thanks for following up on this. We'll leave it open 👍
