### ISSUE TITLE
Action "sonar" authentication failure with token in "sonar_login" vs sonar-scanner 4.6.2

### ISSUE THREAD

**Issue by soleilpqd** [fastlane/fastlane#19123]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Hello,

I'm using fastlane `sonar(sonar_url: "my_url", sonar_login: "my_token")` with latest `sonar-scanner` (4.6.2; downloaded from SonarQube) but it fails to authenticate with the Sonar server.
I tried to run `sonar-scanner -Dsonar.login="my_token"` directly in Terminal and got same issue.
I found that `sonar-scanner -Dsonar.login="my_token" -Dsonar.password=""` works as expected.

Please pass argument `-Dsonar.password=""` to `sonnar-scanner` when `sonar_login` is available.
Or it's better that action `sonar` supports `sonar.password` argument.

Thank you.

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                                             |
| --------------------------- | --------------------------------------------------------------------------------- |
| OS                          | 11.4                                                                              |
| Ruby                        | 2.6.3                                                                             |
| Bundler?                    | true                                                                              |
| Git                         | git version 2.30.1 (Apple Git-130)                                                |
| Installation Source         | ~/Documents/&lt;my project&gt;/vendor/bundle/ruby/2.6.0/bin/fastlane |
| Host                        | macOS 11.4 (20F71)                                                                |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib                    |
| OpenSSL Version             | LibreSSL 2.8.3                                                                    |
| Is contained                | false                                                                             |
| Is homebrew                 | false                                                                             |
| Is installed via Fabric.app | false                                                                             |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                                       |
| Xcode Version               | 12.5.1                                                                            |
| Swift Version               | 5.4.2                                                                             |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform(:ios)

platform :ios do
  
  lane :metrics do |args|

    scan(
      ...
    )
  
    slather(
      ...
    )

    swiftlint(
      ...
    )
  
    sonar(
      sonar_url: args[:url],
      sonar_login: args[:auth_token],
    )
  end
end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.187.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-appcenter | 1.11.1  | ✅ Up-To-Date  |

**Comment by chedabob** [comment]
Are you able to roll-back to 4.6.1 or earlier to verify? I don't see anything in the release notes of sonar-scanner that suggest they made any changes around that.

I can't test as this doesn't seem like it affects SonarCloud.
