### ISSUE TITLE
fastlane pilot distribute fails with vague error message

### ISSUE THREAD

**Issue by kurtmc** [fastlane/fastlane#19125]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Running `fastlane pilot distribute` fails with `The request could not be completed because: Not Found`

This is a pretty vague error. Maybe there is a more verbose mode I can use to get more context for the failure?

I have been using fastlane with my CI/CD setup for a few years and have had issues in the past but usually there has been enough context for me to figure out what is going wrong and I have been able to resolve it. Any help would be greatly appreciated.

##### Command executed

```
fastlane pilot distribute --distribute_external true --groups Beta
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
[✔] 🚀 
[18:59:21]: Login to App Store Connect (webops+apple-id@halter.co.nz)

Looking for related GitHub issues on fastlane/fastlane...

➡️  download_dsyms failing with 'Not Found' error
    https://github.com/fastlane/fastlane/issues/19124 [open] 1 💬
    2 minutes ago

➡️  Fastlane supply aab to internal track fail with google api error bad request
    https://github.com/fastlane/fastlane/issues/18670 [open] 13 💬
    a week ago

➡️  2FA attempts to request a verification code too many times
    https://github.com/fastlane/fastlane/issues/19015 [closed] 1 💬
    3 weeks ago

and 225 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09Not%20Found&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.

[!] The request could not be completed because:
	Not Found
  </pre>
</details>

### Environment

<details>
  <pre>
[✔] 🚀 
[18:59:18]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.7                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.7 (19H2)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.0.1                                                         |
| Swift Version               | 5.3                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform(:ios)

platform :ios do

  desc "Deploy to TestFlight internal"
  lane :alpha do
    match(
      git_url: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      type: "appstore",
      readonly: is_ci,
      keychain_password: ENV["SUDO_PASSWORD"],
    )
    settings_to_override = {
      :PROVISIONING_PROFILE_SPECIFIER => "match AppStore xxxxxxxxxxxxxxxx",
      :DEVELOPMENT_TEAM => "UL84L2547Q"
    }
    disable_automatic_code_signing
    update_app_identifier(
      plist_path: "xxxxxx/Info.plist",
      app_identifier: "xxxxxxxxxxxxxxxx"
    )
    update_project_team(
      path: "xxxxxx.xcodeproj",
      teamid: "UL84L2547Q"
    )
    set_info_plist_value(path: "xxxxxx/Info.plist", key: "CFBundleVersion", value: ENV["BUILD_NUMBER"])
    increment_version_number(version_number: ENV["VERSION_NUMBER"])
    cocoapods()
    gym(
      codesigning_identity: "iPhone Distribution",
      scheme: "xxxxxx",
      xcargs: settings_to_override,
      export_method: "app-store",
      export_options: {
        distributionBundleIdentifier: "xxxxxxxxxxxxxxxx",
        provisioningProfiles: {
          "xxxxxxxxxxxxxxxx" => "match AppStore xxxxxxxxxxxxxxxx",
        }
      },
      output_directory: ENV["OUTPUT_DIRECTORY"],
      output_name: ENV["OUTPUT_NAME"],
    )
    pilot(wait_processing_interval: 100)
  end

  desc "Deploy to TestFlight external"
  lane :beta do
    pilot(
      wait_processing_interval: 100,
      distribute_external: true,
    )
  end

  desc "Deploy to App Store"
  lane :production do
    deliver(
      build_number: ENV["BUILD_NUMBER"],
      submit_for_review: true,
      automatic_release: true,
      force: true, # Skip HTMl report verification
      skip_binary_upload: true,
      price_tier: 0,
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "xxxxxxxxxxxxxxxx" # The bundle identifier of your app
apple_id "xxxxxxxxxxxxxxxxxxxxxxxxxxxx"  # Your Apple email address
team_id "UL84L2547Q"

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.187.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| bundler                         | 1.17.2       |
| etc                             | 1.0.1        |
| forwardable                     | 1.2.0        |
| rake                            | 13.0.6       |
| CFPropertyList                  | 3.0.3        |
| concurrent-ruby                 | 1.1.9        |
| i18n                            | 1.8.10       |
| minitest                        | 5.14.4       |
| thread_safe                     | 0.3.6        |
| tzinfo                          | 1.2.9        |
| activesupport                   | 5.2.6        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| httpclient                      | 2.8.3        |
| json                            | 2.5.1        |
| algoliasearch                   | 1.27.5       |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.1.1        |
| aws-partitions                  | 1.479.0      |
| aws-sigv4                       | 1.2.4        |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.117.0      |
| aws-sdk-kms                     | 1.44.0       |
| aws-sdk-s3                      | 1.96.2       |
| babosa                          | 1.0.4        |
| claide                          | 1.0.3        |
| fuzzy_match                     | 2.0.4        |
| nap                             | 1.1.0        |
| netrc                           | 0.11.0       |
| ffi                             | 1.15.3       |
| ethon                           | 0.14.0       |
| typhoeus                        | 1.4.0        |
| cocoapods-core                  | 1.10.1       |
| cocoapods-deintegrate           | 1.0.4        |
| cocoapods-downloader            | 1.4.0        |
| cocoapods-plugins               | 1.0.0        |
| cocoapods-search                | 1.0.0        |
| cocoapods-trunk                 | 1.5.0        |
| cocoapods-try                   | 1.2.0        |
| colored2                        | 3.1.2        |
| escape                          | 0.0.4        |
| fourflusher                     | 2.3.1        |
| gh_inspector                    | 1.1.3        |
| molinillo                       | 0.6.6        |
| ruby-macho                      | 1.4.0        |
| nanaimo                         | 0.3.0        |
| rexml                           | 3.2.5        |
| xcodeproj                       | 1.20.0       |
| cocoapods                       | 1.10.1       |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.3        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.2        |
| excon                           | 0.85.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| multipart-post                  | 2.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.5.1        |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.0.0        |
| fastimage                       | 2.2.4        |
| jwt                             | 2.2.3        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| signet                          | 0.15.0       |
| googleauth                      | 0.16.2       |
| mini_mime                       | 1.1.0        |
| trailblazer-option              | 0.1.1        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-androidpublisher_v3 | 0.8.0        |
| google-apis-playcustomapp_v1    | 0.5.0        |
| google-apis-iamcredentials_v1   | 0.6.0        |
| google-apis-storage_v1          | 0.6.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.34.1       |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
</details>

*generated on:* **2021-07-21**
</details>
[18:59:18]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[18:59:18]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅

  </pre>
</details>

**Comment by ericwang24** [comment]
Same issue. Using fastlane 2.187.0.

**Comment by stuartrr** [comment]
Same issue. Can isolate it to `fastlane upload` with below stack trace. Using Fastlane 2.187.0. 

```
Traceback (most recent call last):
	21: from /Users/stuart/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:22:in `<main>'
	20: from /Users/stuart/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:22:in `eval'
	19: from /Users/stuart/.rvm/gems/ruby-2.5.1/bin/fastlane:23:in `<main>'
	18: from /Users/stuart/.rvm/gems/ruby-2.5.1/bin/fastlane:23:in `load'
	17: from /Users/stuart/.rvm/gems/ruby-2.5.1/gems/fastlane-2.187.0/bin/fastlane:23:in `<top (required)>'
	16: from /Users/stuart/.rvm/gems/ruby-2.5.1/gems/fastlane-2.187.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	15: from /Users/stuart/.rvm/gems/ruby-2.5.1/gems/fastlane-2.187.0/pilot/lib/pilot/commands_generator.rb:19:in `start'
	14: from /Users/stuart/.rvm/gems/ruby-2.5.1/gems/fastlane-2.187.0/pilot/lib/pilot/commands_generator.rb:167:in `run'
	13: from /Users/stuart/.rvm/gems/ruby-2.5.1/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	12: from /Users/stuart/.rvm/gems/ruby-2.5.1/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	11: from /Users/stuart/.rvm/gems/ruby-2.5.1/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	10: from /Users/stuart/.rvm/gems/ruby-2.5.1/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	 9: from /Users/stuart/.rvm/gems/ruby-2.5.1/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	 8: from /Users/stuart/.rvm/gems/ruby-2.5.1/gems/fastlane-2.187.0/pilot/lib/pilot/commands_generator.rb:67:in `block (2 levels) in run'
	 7: from /Users/stuart/.rvm/gems/ruby-2.5.1/gems/fastlane-2.187.0/pilot/lib/pilot/build_manager.rb:17:in `upload'
	 6: from /Users/stuart/.rvm/gems/ruby-2.5.1/gems/fastlane-2.187.0/pilot/lib/pilot/manager.rb:19:in `start'
	 5: from /Users/stuart/.rvm/gems/ruby-2.5.1/gems/fastlane-2.187.0/pilot/lib/pilot/manager.rb:36:in `login'
	 4: from /Users/stuart/.rvm/gems/ruby-2.5.1/gems/fastlane-2.187.0/spaceship/lib/spaceship/connect_api/spaceship.rb:85:in `login'
	 3: from /Users/stuart/.rvm/gems/ruby-2.5.1/gems/fastlane-2.187.0/spaceship/lib/spaceship/connect_api/client.rb:69:in `login'
	 2: from /Users/stuart/.rvm/gems/ruby-2.5.1/gems/fastlane-2.187.0/spaceship/lib/spaceship/tunes/tunes_client.rb:84:in `select_team'
	 1: from /Users/stuart/.rvm/gems/ruby-2.5.1/gems/fastlane-2.187.0/spaceship/lib/spaceship/client.rb:172:in `team_id='
/Users/stuart/.rvm/gems/ruby-2.5.1/gems/fastlane-2.187.0/spaceship/lib/spaceship/tunes/tunes_client.rb:230:in `handle_itc_response': [!] The request could not be completed because: (Spaceship::Tunes::Error)
	Not Found
```

**Comment by coreyd303** [comment]
Seeing this issue with  2.185.1, literally just deployed successfully 2 days ago, today no dice

**Comment by stuartrr** [comment]
https://github.com/fastlane/fastlane/issues/19124 bigger thread.

**Comment by crazymanish** [comment]
Closing this w.r.t #19124
