### ISSUE TITLE
[actions][modify_services] Error `You need to instantiate this module with provisioning_request_client` when calling `modify_services` after `produce` in 2.187.0

### ISSUE THREAD

**Issue by peterfox1** [fastlane/fastlane#19144]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: `2.187.0`
- Last working version: `2.186.0`

### Regression Description

Hi, I'm getting the following error from modify_services after updating to `2.188.0` from `2.170.0`:
`You need to instantiate this module with provisioning_request_client` (full output attached below)

It seemed unrelated but I have tried adding `DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS=-t Aspera,Signiant,DAV` to the env too but it didn't have an affect. (https://github.com/fastlane/fastlane/issues/17122#issuecomment-685755479)

Command used in the Fastfile:
```ruby
	# -- Create the app on Itunes
	produce(
		username: options[:username],
		team_id: options[:team_id],
		itc_team_id: options[:itc_team_id],
		
		app_identifier: options[:app_identifier],
		app_name: options[:app_name],
		language: 'en-GB',
		app_version: options[:app_version],
		sku: options[:sku],
	)
	
	# Set / Update serivces
	modify_services(
		username: options[:username],
		app_identifier: options[:app_identifier],
		team_id: options[:team_id],
		services: {
			push_notification: "on",
		}
	)
```
Edit: ** If `produce` is commented out, `modify_services` will work correctly.. **

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[13:52:55]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2021-07-23 13:52:57.26]: Checking if there are any plugins that should be loaded...
DEBUG [2021-07-23 13:52:58.72]: Using username: xxxxxxxxxxxx
DEBUG [2021-07-23 13:52:58.72]: Using team_id: xxxxxxxxxxxx
DEBUG [2021-07-23 13:52:58.72]: Using itc_team_id: xxxxxxxxxxxx
DEBUG [2021-07-23 13:52:58.72]: Using app_identifier: xxxxxxxxxxxx
DEBUG [2021-07-23 13:52:58.72]: Using app_name: xxxxxxxxxxxx
DEBUG [2021-07-23 13:52:58.72]: Using app_version: xxxxxxxxxxxx
DEBUG [2021-07-23 13:52:58.72]: Using sku: xxxxxxxxxxxx
INFO [2021-07-23 13:52:58.72]: Driving the lane 'step_produce' �
INFO [2021-07-23 13:52:58.76]: ---------------------
INFO [2021-07-23 13:52:58.76]: --- Step: produce ---
INFO [2021-07-23 13:52:58.76]: ---------------------
INFO [2021-07-23 13:53:00.35]: [DevCenter] App 'xxxxxxxxxxxx' already exists, nothing to do on the Dev Center
INFO [2021-07-23 13:53:05.81]: App 'xxxxxxxxxxxx' already exists (xxxxxxxxxxxx), nothing to do on App Store Connect
INFO [2021-07-23 13:53:05.81]: -----------------------------
INFO [2021-07-23 13:53:05.81]: --- Step: modify_services ---
INFO [2021-07-23 13:53:05.81]: -----------------------------
INFO [2021-07-23 13:53:05.82]: Starting login with user 'xxxxxxxxxxxx'
INFO [2021-07-23 13:53:06.84]: Successfully logged in
WARN [2021-07-23 13:53:06.84]: Lane Context:
INFO [2021-07-23 13:53:06.84]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"step_produce", :PRODUCE_APPLE_ID=>"xxxxxxxxxxxx"}
ERROR [2021-07-23 13:53:06.84]: You need to instantiate this module with provisioning_request_client
INFO [2021-07-23 13:53:06.84]: Successfully generated documentation at path 'xxxxxxxxxxxx'
ERROR [2021-07-23 13:53:06.85]: fastlane finished with errors</pre>
</details>

### Environment

<details><summary>� fastlane environment �</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.7                                     |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.rvm/rubies/ruby-2.6.3/bin/fastlane       |
| Host                        | Mac OS X 10.15.7 (19H1217)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.3/lib                |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.4                                        |
| Swift Version               | 5.3.2                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found � |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


lane :step_produce do |options|
	
	# -- Create the app on Itunes
	produce(
		username: options[:username],
		team_id: options[:team_id],
		itc_team_id: options[:itc_team_id],
		
		app_identifier: options[:app_identifier],
		app_name: options[:app_name],
		language: 'en-GB',
		app_version: options[:app_version],
		sku: options[:sku],
	)
	
	# Set / Update serivces
	modify_services(
		username: options[:username],
		app_identifier: options[:app_identifier],
		team_id: options[:team_id],
		services: {
			push_notification: "on",
		}
	)
	
	# -- Set / update privacy details
	
	upload_app_privacy_details_to_app_store(
		username: options[:username],
		team_id: options[:team_id],
		app_identifier: options[:app_identifier],
		json_path: "fastlane/metadata/app_privacy_details.json",
	)
	
end

...

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.188.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| executable-hooks                | 1.6.0        |
| bundler-unload                  | 1.0.2        |
| rubygems-bundler                | 1.4.5        |
| bundler                         | 1.17.3       |
| etc                             | 1.0.1        |
| atomos                          | 0.1.3        |
| CFPropertyList                  | 3.0.2        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.2.6        |
| xcodeproj                       | 1.15.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.5.0        |
| public_suffix                   | 2.0.5        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| tty-screen                      | 0.7.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.3        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.73.0       |
| unf_ext                         | 0.0.7.6      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.3        |
| faraday-cookie_jar              | 0.0.6        |
| faraday                         | 1.0.1        |
| faraday_middleware              | 1.0.0        |
| fastimage                       | 2.1.7        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.1.0        |
| mini_magick                     | 4.10.1       |
| naturally                       | 2.2.0        |
| rubyzip                         | 2.3.0        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.0        |
| dotenv                          | 2.7.5        |
| simctl                          | 1.6.8        |
| jwt                             | 2.1.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.10       |
| declarative-option              | 0.1.0        |
| representable                   | 3.0.4        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.0.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.14.1       |
| os                              | 1.0.1        |
| signet                          | 0.15.0       |
| googleauth                      | 0.16.2       |
| httpclient                      | 2.8.3        |
| rexml                           | 3.1.9        |
| webrick                         | 1.4.2        |
| google-apis-core                | 0.4.1        |
| google-apis-playcustomapp_v1    | 0.5.0        |
| google-apis-androidpublisher_v3 | 0.8.0        |
| google-cloud-env                | 1.3.1        |
| google-cloud-errors             | 1.0.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.6.0        |
| google-apis-storage_v1          | 0.6.0        |
| digest-crc                      | 0.5.1        |
| google-cloud-storage            | 1.34.1       |
| emoji_regex                     | 1.0.1        |
| jmespath                        | 1.4.0        |
| aws-partitions                  | 1.364.0      |
| aws-eventstream                 | 1.0.3        |
| aws-sigv4                       | 1.1.1        |
| aws-sdk-core                    | 3.105.0      |
| aws-sdk-kms                     | 1.37.0       |
| aws-sdk-s3                      | 1.79.1       |
| forwardable                     | 1.2.0        |
| logger                          | 1.3.0        |
| stringio                        | 0.0.2        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| date                            | 2.0.0        |
| io-console                      | 0.4.7        |
| fileutils                       | 1.1.0        |
| zlib                            | 1.0.0        |
| psych                           | 3.1.0        |
| mutex_m                         | 0.1.0        |
</details>

*generated on:* **2021-07-23**
</details>

**Comment by peterfox1** [comment]
I've been trying to narrow this down as much as I can. So far I've found it was introduced in the `2.187.0` release instead of 2.188.0. (Suspected this one due to the change to this action, however the change didn't look like it could cause an issue like this).

Also, oddly, I've found that the issue only happens when it's proceeded by `produce`. If I comment out that and just run `modify_services` on it's own, it will work. I have tried hard-coded values in case it was modifying the values, but no success so far.

**Comment by peterfox1** [comment]
`modify_services` is working when it's executed in it's own lane and separate fastlane call. Using this as a workaround for now.

**Comment by jl-gogovapps** [comment]
@peterfox1 did you try removing modify_services and using the `enable_services` key in produce?  I'm hoping this is idempotent for new and existing builds (i'm fairly certain it wasn't previously, but now it seems to be working for modifying existing builds)...

**Comment by peterfox1** [comment]
Thanks for the suggestion @jl-gogovapps I hadn't seen that option. That might explain why this hasn't been reported otherwise.

I've have just tried the `enable_services` key in produce but I only have an existing app to test with atm. It doesn't seem to modify the existing services for the existing app. - produce returns 'app already exists, nothing to do'. (double checked with modify services & produce commented out which did apply the changes)

It would be fine to only set it on creation of new apps in most cases - there will be some very rare edge cases where we would need the existing services to update in our specific setup. The work around of just calling it separately is working well though.

**Comment by jl-gogovapps** [comment]
I was diving into this a bit, and it looks like adding to https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/modify_services.rb#L7 

the following line:

```
Spaceship::ConnectAPI.login(Produce.config[:username], nil, use_portal: true, use_tunes: true)
```

resolves the issue.  Of course, there might be a better way, or this might be a hack that doesn't get to the underlying root cause, but 🤷

**Comment by gholias** [comment]
I'm also having this issue

**Comment by richexp** [comment]
I'm also having this issue

**Comment by mjovkovic** [comment]
This is still an issue when `produce` and `modify_services` are in the same lane.
