### ISSUE TITLE
[spaceship] analytics not working - request url is not correct

### ISSUE THREAD

**Issue by DKY1** [fastlane/fastlane#19153]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
i runs daily a script that uses spaceship analytics, a few days ago this script stop working and i noted that apple change the url. i tried to change the url in tunes_client.rb but it didnt help, i gues thay change more than just the url. 
Also my ruby skills are poor i would want to help and fix this issue, if someone can give me direction on were to see how the massege looks like today and what needs to be change to fit to the new appstore connect analytics it would be great 

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by kevin-lxh** [comment]
Same issue. My codes like this
```
Spaceship::Tunes.login('xxx', 'xxx')
app = Spaceship::Tunes::Application.find('com.xxx.xxx')
analytics = app.analytics
```

Then I got the error
```
Traceback (most recent call last):
	6: from index.rb:17:in `<main>'
	5: from /Users/Kevin/.rvm/gems/ruby-2.7.2/gems/fastlane-2.190.0/spaceship/lib/spaceship/tunes/application.rb:146:in `analytics'
	4: from /Users/Kevin/.rvm/gems/ruby-2.7.2/gems/fastlane-2.190.0/spaceship/lib/spaceship/tunes/application.rb:126:in `live_version'
	3: from /Users/Kevin/.rvm/gems/ruby-2.7.2/gems/fastlane-2.190.0/spaceship/lib/spaceship/tunes/app_version.rb:291:in `find'
	2: from /Users/Kevin/.rvm/gems/ruby-2.7.2/gems/fastlane-2.190.0/spaceship/lib/spaceship/tunes/tunes_client.rb:452:in `app_version'
	1: from /Users/Kevin/.rvm/gems/ruby-2.7.2/gems/fastlane-2.190.0/spaceship/lib/spaceship/tunes/tunes_client.rb:461:in `app_version_data'
/Users/Kevin/.rvm/gems/ruby-2.7.2/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:763:in `parse_response': <?xml version="1.0" encoding="UTF-8"?> (Spaceship::UnexpectedResponse)
<String>There is no route for the path 'apps/123456xxx/platforms/ios/versions/123456xxx'.</String>
```
