### ISSUE TITLE
[action][import_from_git] Caching is not working

### ISSUE THREAD

**Issue by gdetari** [fastlane/fastlane#19158]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I have the following Fastfile:

```
import_from_git(
  url: "[redacted]/ci-ios.git",
  branch: "HEAD",
  cache_path: "~/.cache/fastlane"
)
```

This defines several lanes. The workflow is successful, lanes work as expected. However the cache is not being created at the specified directory at all.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
[15:46:04]: -----------------------------
[15:46:04]: --- Step: import_from_git ---
[15:46:04]: -----------------------------
[15:46:04]: Cloning remote git repo...
[15:46:04]: $ git clone [redacted]/ci-ios.git /var/folders/_c/4106dfkx25l_brjc3066xz980000gn/T/fl_clone20210728-20758-dh43f/ci-ios.git --depth 1 --no-checkout
[15:46:04]: ▸ Cloning into '/var/folders/_c/4106dfkx25l_brjc3066xz980000gn/T/fl_clone20210728-20758-dh43f/ci-ios.git'...
[15:46:08]: $ cd /var/folders/_c/4106dfkx25l_brjc3066xz980000gn/T/fl_clone20210728-20758-dh43f/ci-ios.git && git checkout HEAD fastlane/Fastfile
[15:46:08]: ▸ Updated 1 path from 1a72669
[15:46:08]: $ cd /var/folders/_c/4106dfkx25l_brjc3066xz980000gn/T/fl_clone20210728-20758-dh43f/ci-ios.git && git checkout HEAD fastlane/actions
[15:46:08]: ▸ Updated 1 path from 1a72669
 </pre>
</details>

### Environment

<details>
  <pre>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.7                                     |
| Ruby                        | 2.7.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.gem/bin/fastlane                         |
| Host                        | Mac OS X 10.15.7 (19H1217)                  |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.7.2/lib            |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.4                                        |
| Swift Version               | 5.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
import_from_git(
  url: "[redacted]/ci-ios.git",
  branch: "HEAD",
  cache_path: "~/.cache/fastlane"
)

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.188.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                             | Version | Update-Status |
| ---------------------------------- | ------- | ------------- |
| fastlane-plugin-create_xcframework | 1.1.2   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                | Version      |
| ---------------------------------- | ------------ |
| did_you_mean                       | 1.4.0        |
| rouge                              | 2.0.7        |
| xcpretty                           | 0.3.0        |
| terminal-notifier                  | 2.0.0        |
| unicode-display_width              | 1.7.0        |
| terminal-table                     | 1.8.0        |
| public_suffix                      | 4.0.6        |
| addressable                        | 2.8.0        |
| multipart-post                     | 2.0.0        |
| word_wrap                          | 1.0.0        |
| tty-screen                         | 0.8.1        |
| tty-cursor                         | 0.7.1        |
| tty-spinner                        | 0.9.3        |
| artifactory                        | 3.0.15       |
| colored                            | 1.2          |
| highline                           | 2.0.3        |
| commander                          | 4.6.0        |
| unf_ext                            | 0.0.7.7      |
| unf                                | 0.1.4        |
| domain_name                        | 0.5.20190701 |
| http-cookie                        | 1.0.3        |
| faraday-cookie_jar                 | 0.0.7        |
| faraday_middleware                 | 1.0.0        |
| gh_inspector                       | 1.1.3        |
| rubyzip                            | 2.3.0        |
| security                           | 0.1.3        |
| dotenv                             | 2.7.6        |
| simctl                             | 1.6.8        |
| jwt                                | 2.2.2        |
| retriable                          | 3.1.2        |
| memoist                            | 0.16.2       |
| multi_json                         | 1.15.0       |
| os                                 | 1.1.1        |
| googleauth                         | 0.16.2       |
| httpclient                         | 2.8.3        |
| google-apis-core                   | 0.4.1        |
| google-apis-playcustomapp_v1       | 0.5.0        |
| google-apis-androidpublisher_v3    | 0.9.0        |
| google-cloud-storage               | 1.31.0       |
| uri                                | 0.10.0       |
| nanaimo                            | 0.3.0        |
| colored2                           | 3.1.2        |
| claide                             | 1.0.3        |
| CFPropertyList                     | 3.0.3        |
| atomos                             | 0.1.3        |
| xcodeproj                          | 1.19.0       |
| plist                              | 3.6.0        |
| babosa                             | 1.0.4        |
| excon                              | 0.79.0       |
| ruby2_keywords                     | 0.0.4        |
| faraday-net_http                   | 1.0.1        |
| faraday                            | 1.3.0        |
| fastimage                          | 2.2.3        |
| json                               | 2.5.1        |
| mini_magick                        | 4.11.0       |
| naturally                          | 2.2.1        |
| xcpretty-travis-formatter          | 1.0.1        |
| bundler                            | 2.2.0        |
| trailblazer-option                 | 0.1.0        |
| declarative                        | 0.0.20       |
| uber                               | 0.1.0        |
| representable                      | 3.1.0        |
| mini_mime                          | 1.1.0        |
| signet                             | 0.15.0       |
| rexml                              | 3.2.5        |
| webrick                            | 1.7.0        |
| google-cloud-errors                | 1.1.0        |
| google-cloud-env                   | 1.5.0        |
| google-cloud-core                  | 1.6.0        |
| google-apis-iamcredentials_v1      | 0.3.0        |
| google-apis-storage_v1             | 0.3.0        |
| rake                               | 13.0.3       |
| digest-crc                         | 0.6.3        |
| emoji_regex                        | 3.2.2        |
| aws-eventstream                    | 1.1.1        |
| aws-sigv4                          | 1.2.3        |
| aws-partitions                     | 1.443.0      |
| jmespath                           | 1.4.0        |
| aws-sdk-core                       | 3.113.1      |
| aws-sdk-kms                        | 1.43.0       |
| aws-sdk-s3                         | 1.93.0       |
| forwardable                        | 1.3.1        |
| logger                             | 1.4.2        |
| cgi                                | 0.1.0        |
| date                               | 3.0.0        |
| timeout                            | 0.1.0        |
| stringio                           | 0.1.0        |
| zlib                               | 1.1.0        |
| ipaddr                             | 1.2.2        |
| openssl                            | 2.1.2        |
| ostruct                            | 0.2.0        |
| strscan                            | 1.0.3        |
| io-console                         | 0.5.6        |
| delegate                           | 0.1.0        |
| fileutils                          | 1.4.1        |
| singleton                          | 0.1.0        |
| open3                              | 0.1.0        |
| nokogiri                           | 1.11.3       |
| racc                               | 1.5.2        |
| yaml                               | 0.1.0        |
| psych                              | 3.1.0        |
| mutex_m                            | 0.1.0        |
| fastlane-plugin-create_xcframework | 1.1.2        |
</details>

*generated on:* **2021-07-28**
</details>
 </pre>
</details>

**Comment by lucgrabowski** [comment]
Hi, I've tried to reproduce the issue and I wasn't able.
It looks as if `cache_path` wasn't present in `import_from_git` call. Are you sure you're using correct Fastfile?
The logs should have `Eligible for caching` message before cloning starts:
```
[08:14:44]: --- Step: import_from_git ---
[08:14:44]: -----------------------------
[08:14:44]: Eligible for caching
[08:14:44]: Cloning remote git repo...
```

**Comment by gdetari** [comment]
Yes, 100% using the correct Fastfile - there is only one. This is a stable repro for me.

**Comment by Beaudry62** [comment]
Here are some ways you can try to fix your caching problem, in order of escalation: Try holding down the Shift key while pressing the Refresh button. Close your browser and re-open it (make sure you are NOT on the cached page) and delete your temporary Internet files (clear your cache).
