### ISSUE TITLE
match_nuke cannot determine team_id

### ISSUE THREAD

**Issue by mrkelvinli** [fastlane/fastlane#19192]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When using the `match_nuke` action, I get this error.
`Cannot determine portal team id via the App Store Connect API (yet). Look to see if you can get the portal team id from somewhere else. View more info in the docs at https://docs.fastlane.tools/app-store-connect-api/`

This error is coming from [`client.rb`](https://github.com/fastlane/fastlane/blob/0072e332e8fac0a1b37d8bc630bb802710ce5df5/spaceship/lib/spaceship/connect_api/client.rb#L104). The `match_nuke` action used to works like other action (eg. `check_app_store_metadata`) where it is able to determine my team ID. Recently, it has failed to do so and required setting the team id in the parameters.

##### Command executed

```ruby
match_nuke(
  api_key_path: "./fastlane/AuthKey.json",
  type: "development",
  git_branch: "development",
  skip_confirmation: true,
)
```

My Matchfile
```
git_url("ssh://*****.git")

storage_mode("git")

shallow_clone(true)

clone_branch_directly(true)

type("appstore")
```

##### Complete output when running fastlane, including the stack trace and command used

```
Renewing main ios certificates
+ [[ ios == \i\o\s ]]
+ cd projects/main/native/ios/App
+ bundle exec fastlane renew_certificates
[✔] 🚀
+------------------------------+---------+------------------------------------------+
|                                   Used plugins                                    |
+------------------------------+---------+------------------------------------------+
| Plugin                       | Version | Action                                   |
+------------------------------+---------+------------------------------------------+
| fastlane-plugin-sentry       | 1.8.1   | sentry_upload_dsym, sentry_set_commits,  |
|                              |         | sentry_upload_sourcemap,                 |
|                              |         | sentry_finalize_release,                 |
|                              |         | sentry_upload_file,                      |
|                              |         | sentry_upload_proguard,                  |
|                              |         | sentry_create_release                    |
| fastlane-plugin-trainer      | 0.4.1   | trainer                                  |
| fastlane-plugin-xchtmlreport | 0.1.1   | xchtmlreport                             |
+------------------------------+---------+------------------------------------------+

[15:44:19]: ------------------------------
[15:44:19]: --- Step: default_platform ---
[15:44:19]: ------------------------------
[15:44:19]: Driving the lane 'ios renew_certificates' 🚀
[15:44:19]: ------------------------
[15:44:19]: --- Step: match_nuke ---
[15:44:19]: ------------------------
[15:44:19]: Successfully loaded '*************/fastlane/Matchfile' 📄

+-----------------------+---------------------------------------------------------------------+
|                         Detected Values from './fastlane/Matchfile'                         |
+-----------------------+---------------------------------------------------------------------+
| git_url               | ssh://**************  |
|                       |                                                               |
| storage_mode          | git                                                                 |
| shallow_clone         | true                                                                |
| clone_branch_directly | true                                                                |
| type                  | appstore                                                            |
+-----------------------+---------------------------------------------------------------------+

[15:44:19]: Going to revoke your 'development' certificate type and provisioning profiles
[15:44:19]: Creating authorization token for App Store Connect API
+------------------+------------------------+
|               Lane Context                |
+------------------+------------------------+
| DEFAULT_PLATFORM | ios                    |
| PLATFORM_NAME    | ios                    |
| LANE_NAME        | ios renew_certificates |
+------------------+------------------------+
[15:44:19]: Cannot determine portal team id via the App Store Connect API (yet). Look to see if you can get the portal team id from somewhere else. View more info in the docs at https://docs.fastlane.tools/app-store-connect-api/

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 💥   | match_nuke       | 0           |
+------+------------------+-------------+

[15:44:19]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  [deliver][spaceship] 500 server error - creating new App Store version
    https://github.com/fastlane/fastlane/issues/17886 [closed] 87 💬
    5 weeks ago

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
RuntimeError: [!] Cannot determine portal team id via the App Store Connect API (yet). Look to see if you can get the portal team id from somewhere else. View more info in the docs at https://docs.fastlane.tools/app-store-connect-api/
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.189.0/spaceship/lib/spaceship/connect_api/client.rb:109:in `portal_team_id'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.189.0/match/lib/match/nuke.rb:52:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.189.0/fastlane/lib/fastlane/actions/match_nuke.rb:13:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.189.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.189.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.189.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.189.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.189.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.189.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.189.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:431:in `block (2 levels) in parsing_binding'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.189.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.189.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.189.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.189.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.189.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.189.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.189.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.189.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.189.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.189.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.189.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.189.0/bin/fastlane:23:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>'
```

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.4                                                           |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.31.1                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.4 (20F71)                                             |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.5.1                                                         |
| Swift Version               | 5.4.2                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_AU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Appfile`</summary>

</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.189.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                       | Version | Update-Status      |
| ---------------------------- | ------- | ------------------ |
| fastlane-plugin-sentry       | 1.8.1   | 🚫 Update available |
| fastlane-plugin-trainer      | 0.4.1   | ✅ Up-To-Date       |
| fastlane-plugin-xchtmlreport | 0.1.1   | ✅ Up-To-Date       |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| bundler                         | 2.1.4        |
| rake                            | 13.0.6       |
| CFPropertyList                  | 3.0.3        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.1.1        |
| aws-partitions                  | 1.482.0      |
| aws-sigv4                       | 1.2.4        |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.119.0      |
| aws-sdk-kms                     | 1.46.0       |
| aws-sdk-s3                      | 1.98.0       |
| babosa                          | 1.0.4        |
| claide                          | 1.0.3        |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.2        |
| excon                           | 0.85.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| multipart-post                  | 2.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.6.0        |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.1.0        |
| fastimage                       | 2.2.4        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.2.3        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| signet                          | 0.15.0       |
| googleauth                      | 0.17.0       |
| httpclient                      | 2.8.3        |
| mini_mime                       | 1.1.0        |
| trailblazer-option              | 0.1.1        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| rexml                           | 3.2.5        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-androidpublisher_v3 | 0.9.0        |
| google-apis-playcustomapp_v1    | 0.5.0        |
| google-apis-iamcredentials_v1   | 0.6.0        |
| google-apis-storage_v1          | 0.6.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.34.1       |
| json                            | 2.5.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.20.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| fastlane-plugin-sentry          | 1.8.1        |
| trainer                         | 0.9.1        |
| fastlane-plugin-trainer         | 0.4.1        |
| fastlane-plugin-xchtmlreport    | 0.1.1        |
</details>

*generated on:* **2021-08-02**
</details>

**Comment by crazymanish** [comment]
Hi @mrkelvinli

The spaceship tool is the common tool that's used all over the place/actions/tools etc to login using AppStoreConnect API key or using old fashion way (username, password)
& this is indeed true, `App Store Connect API cannot determine this on its own (yet)`

I suspect if other tools/actions are getting team ID then you may have defined them somewhere i.e inside DeliverFile/Snapfile/AppFile or ENV files 🤷‍♂️
if yes, You need to define the same way team ID in your MatchFile or ENV file

------
The best way to define team-id is using the `FASTLANE_TEAM_ID` ENV variable because the same ENV variable is used across all tools i.e match, pilot, deliver, spaceship
i.e 
FASTLANE_TEAM_ID='M1TJ4C1234'  # this is just a random test team-ID 😉 

I hope, that will help...in case of any issue, please feel free to start a discussion here
https://github.com/fastlane/fastlane/discussions/categories/q-a

**Comment by mrkelvinli** [comment]
Hi @crazymanish,

Thanks for your advice. That is very helpful 😄 

Kelvin
