### ISSUE TITLE
undefined method `sign_in_with_apple' for Spaceship::Portal::AppService:Class

### ISSUE THREAD

**Issue by jwaldrip** [fastlane/fastlane#19201]
Getting the following error when trying to run produce from the DSL.

```
produce(
  app_identifier: app_identifier,
  app_name: env == "prod" ? APP_MARKETING_NAME : "#{APP_MARKETING_NAME} (#{env.upcase})",
  skip_itc: true,
  enable_services: {
    associated_domains: "on",
    push_notification: "on",
    sign_in_with_apple: "on"
  }
)
```

```
bundler: failed to load command: fastlane (/Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/bin/fastlane)
NoMethodError: [!] undefined method `sign_in_with_apple' for Spaceship::Portal::AppService:Class
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/fastlane-2.190.0/produce/lib/produce/developer_center.rb:148:in `block in enable_services'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/fastlane-2.190.0/produce/lib/produce/developer_center.rb:127:in `each'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/fastlane-2.190.0/produce/lib/produce/developer_center.rb:127:in `enable_services'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/fastlane-2.190.0/produce/lib/produce/developer_center.rb:99:in `create_new_app'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/fastlane-2.190.0/produce/lib/produce/developer_center.rb:84:in `run'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/fastlane-2.190.0/produce/lib/produce/manager.rb:11:in `start_producing'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/actions/create_app_online.rb:17:in `block in run'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/actions/create_app_online.rb:15:in `chdir'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/actions/create_app_online.rb:15:in `run'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  ../../../fastlane/Fastfile:397:in `block (2 levels) in parsing_binding'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  ../../../fastlane/Fastfile:451:in `block (2 levels) in parsing_binding'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/fastlane-2.190.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/gems/fastlane-2.190.0/bin/fastlane:23:in `<top (required)>'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/bin/fastlane:23:in `load'
  /Users/jwaldrip/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/bin/fastlane:23:in `<top (required)>'
```

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                                             |
| --------------------------- | --------------------------------------------------------------------------------- |
| OS                          | 12.0                                                                              |
| Ruby                        | 2.6.3                                                                             |
| Bundler?                    | true                                                                              |
| Git                         | git version 2.32.0                                                                |
| Installation Source         | ~/dev/src/gitlab.com/gigsmart/projects/monorepo-1/bundler/ruby/2.6.0/bin/fastlane |
| Host                        | macOS 12.0 (21A5294g)                                                             |
| Ruby Lib Dir                | ~/.asdf/installs/ruby/2.6.3/lib                                                   |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                                                       |
| Is contained                | false                                                                             |
| Is homebrew                 | false                                                                             |
| Is installed via Fabric.app | false                                                                             |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                                       |
| Xcode Version               | 12.5.1                                                                            |
| Swift Version               | 5.4.2                                                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
import "../../../fastlane/Fastfile"

ANDROID_PROJECT_DIR  = File.expand_path("../android")
PACKAGE_NAME = "com.gigsmart.requester"
ANDROID_KEY_ALIAS = "requester"
APP_NAME = "requester"
APP_MARKETING_NAME = "GIGSMART Get Workers"
WEBAPP_DOMAIN_PREFIX = "getworkers"
ANDROID_KEY_PASSWORD = ENV["REQUESTER_ANDROID_KEY_PASSWORD"]
APP_ICON_PATH = "./ios/Requester/Images.xcassets/AppIcon.appiconset/ios-marketing-1024x1024-1x.png"
XCODE_GSP_PATH = File.expand_path("../ios/Requester/GoogleService-Info.plist")
XCODE_PROJECT = File.expand_path("../ios/Requester.xcodeproj")
XCODE_WORKSPACE = File.expand_path("../ios/Requester.xcworkspace")
ENTITLEMENTS_PATH = File.expand_path("../ios/Requester/Requester.entitlements")
URL_SCHEME = "gs-get-workers"

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.190.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                            | Version | Update-Status |
| ------------------------------------------------- | ------- | ------------- |
| fastlane-plugin-yarn                              | 1.2     | ✅ Up-To-Date  |
| fastlane-plugin-increment_version_code            | 0.4.3   | ✅ Up-To-Date  |
| fastlane-plugin-increment_version_name            | 0.0.10  | ✅ Up-To-Date  |
| fastlane-plugin-update_android_strings            | 0.1.0   | ✅ Up-To-Date  |
| fastlane-plugin-android_change_package_identifier | 0.1.0   | ✅ Up-To-Date  |
| fastlane-plugin-browserstack                      | 0.3.2   | ✅ Up-To-Date  |
| fastlane-plugin-slack_upload                      | 0.1.0   | ✅ Up-To-Date  |
| fastlane-plugin-sentry                            | 1.8.3   | ✅ Up-To-Date  |
| fastlane-plugin-google_cloud_storage              | 0.1.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                               | Version      |
| ------------------------------------------------- | ------------ |
| did_you_mean                                      | 1.3.0        |
| bundler                                           | 2.1.4        |
| rake                                              | 13.0.6       |
| CFPropertyList                                    | 3.0.3        |
| concurrent-ruby                                   | 1.1.9        |
| i18n                                              | 1.8.10       |
| minitest                                          | 5.14.4       |
| thread_safe                                       | 0.3.6        |
| tzinfo                                            | 1.2.9        |
| activesupport                                     | 5.2.6        |
| public_suffix                                     | 4.0.6        |
| addressable                                       | 2.8.0        |
| httpclient                                        | 2.8.3        |
| json                                              | 2.5.1        |
| algoliasearch                                     | 1.27.5       |
| artifactory                                       | 3.0.15       |
| atomos                                            | 0.1.3        |
| aws-eventstream                                   | 1.1.1        |
| aws-partitions                                    | 1.482.0      |
| aws-sigv4                                         | 1.2.4        |
| jmespath                                          | 1.4.0        |
| aws-sdk-core                                      | 3.119.0      |
| aws-sdk-kms                                       | 1.46.0       |
| aws-sdk-s3                                        | 1.98.0       |
| babosa                                            | 1.0.4        |
| claide                                            | 1.0.3        |
| fuzzy_match                                       | 2.0.4        |
| nap                                               | 1.1.0        |
| netrc                                             | 0.11.0       |
| ffi                                               | 1.15.3       |
| ethon                                             | 0.14.0       |
| typhoeus                                          | 1.4.0        |
| cocoapods-core                                    | 1.10.2       |
| cocoapods-deintegrate                             | 1.0.4        |
| cocoapods-downloader                              | 1.4.0        |
| cocoapods-plugins                                 | 1.0.0        |
| cocoapods-search                                  | 1.0.0        |
| cocoapods-trunk                                   | 1.5.0        |
| cocoapods-try                                     | 1.2.0        |
| colored2                                          | 3.1.2        |
| escape                                            | 0.0.4        |
| fourflusher                                       | 2.3.1        |
| gh_inspector                                      | 1.1.3        |
| molinillo                                         | 0.6.6        |
| ruby-macho                                        | 1.4.0        |
| nanaimo                                           | 0.3.0        |
| rexml                                             | 3.2.5        |
| xcodeproj                                         | 1.20.0       |
| cocoapods                                         | 1.10.2       |
| coderay                                           | 1.1.3        |
| colored                                           | 1.2          |
| highline                                          | 2.0.3        |
| commander                                         | 4.6.0        |
| declarative                                       | 0.0.20       |
| digest-crc                                        | 0.6.4        |
| unf_ext                                           | 0.0.7.7      |
| unf                                               | 0.1.4        |
| domain_name                                       | 0.5.20190701 |
| dotenv                                            | 2.7.6        |
| emoji_regex                                       | 3.2.2        |
| excon                                             | 0.85.0       |
| faraday-em_http                                   | 1.0.0        |
| faraday-em_synchrony                              | 1.0.0        |
| faraday-excon                                     | 1.1.0        |
| faraday-httpclient                                | 1.0.1        |
| faraday-net_http                                  | 1.0.1        |
| faraday-net_http_persistent                       | 1.2.0        |
| faraday-patron                                    | 1.0.0        |
| faraday-rack                                      | 1.0.0        |
| multipart-post                                    | 2.0.0        |
| ruby2_keywords                                    | 0.0.5        |
| faraday                                           | 1.6.0        |
| http-cookie                                       | 1.0.4        |
| faraday-cookie_jar                                | 0.0.7        |
| faraday_middleware                                | 1.1.0        |
| fastimage                                         | 2.2.4        |
| jwt                                               | 2.2.3        |
| memoist                                           | 0.16.2       |
| multi_json                                        | 1.15.0       |
| os                                                | 1.1.1        |
| signet                                            | 0.15.0       |
| googleauth                                        | 0.17.0       |
| mini_mime                                         | 1.1.0        |
| trailblazer-option                                | 0.1.1        |
| uber                                              | 0.1.0        |
| representable                                     | 3.1.1        |
| retriable                                         | 3.1.2        |
| webrick                                           | 1.7.0        |
| google-apis-core                                  | 0.4.1        |
| google-apis-androidpublisher_v3                   | 0.10.0       |
| google-apis-playcustomapp_v1                      | 0.5.0        |
| google-apis-iamcredentials_v1                     | 0.6.0        |
| google-apis-storage_v1                            | 0.6.0        |
| google-cloud-env                                  | 1.5.0        |
| google-cloud-errors                               | 1.1.0        |
| google-cloud-core                                 | 1.6.0        |
| google-cloud-storage                              | 1.34.1       |
| mini_magick                                       | 4.11.0       |
| naturally                                         | 2.2.1        |
| plist                                             | 3.6.0        |
| rubyzip                                           | 2.3.2        |
| security                                          | 0.1.3        |
| simctl                                            | 1.6.8        |
| terminal-notifier                                 | 2.0.0        |
| unicode-display_width                             | 1.7.0        |
| terminal-table                                    | 1.8.0        |
| tty-screen                                        | 0.8.1        |
| tty-cursor                                        | 0.7.1        |
| tty-spinner                                       | 0.9.3        |
| word_wrap                                         | 1.0.0        |
| rouge                                             | 2.0.7        |
| xcpretty                                          | 0.3.0        |
| xcpretty-travis-formatter                         | 1.0.1        |
| fastlane-plugin-android_change_package_identifier | 0.1.0        |
| http-accept                                       | 1.7.0        |
| mime-types-data                                   | 3.2021.0704  |
| mime-types                                        | 3.3.1        |
| rest-client                                       | 2.1.0        |
| fastlane-plugin-browserstack                      | 0.3.2        |
| fastlane-plugin-google_cloud_storage              | 0.1.1        |
| fastlane-plugin-increment_version_code            | 0.4.3        |
| fastlane-plugin-increment_version_name            | 0.0.10       |
| fastlane-plugin-sentry                            | 1.8.3        |
| gli                                               | 2.20.1       |
| hashie                                            | 4.1.0        |
| websocket-extensions                              | 0.1.5        |
| websocket-driver                                  | 0.7.5        |
| slack-ruby-client                                 | 0.17.0       |
| fastlane-plugin-slack_upload                      | 0.1.0        |
| ox                                                | 2.14.5       |
| fastlane-plugin-update_android_strings            | 0.1.0        |
| fastlane-plugin-yarn                              | 1.2          |
| foreman                                           | 0.87.2       |
| multi_xml                                         | 0.6.0        |
| httparty                                          | 0.18.1       |
| gitlab                                            | 4.17.0       |
| method_source                                     | 1.0.0        |
| mini_portile2                                     | 2.6.1        |
| racc                                              | 1.5.2        |
| nokogiri                                          | 1.12.1       |
| pry                                               | 0.14.1       |
| ruby-progressbar                                  | 1.11.0       |
</details>

*generated on:* **2021-08-03**
</details>

**Comment by mtuktarov** [comment]
same  issue here
```
15:01:42  🔗  You can ⌘ + double-click on links to open them directly in your browser.
15:01:42  /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/produce/lib/produce/developer_center.rb:148:in `block in enable_services': \e[31m[!] undefined method `sign_in_with_apple' for Spaceship::Portal::AppService:Class\e[0m (NoMethodError)
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/produce/lib/produce/developer_center.rb:127:in `each'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/produce/lib/produce/developer_center.rb:127:in `enable_services'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/produce/lib/produce/developer_center.rb:99:in `create_new_app'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/produce/lib/produce/developer_center.rb:84:in `run'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/produce/lib/produce/manager.rb:11:in `start_producing'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/actions/create_app_online.rb:17:in `block in run'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/actions/create_app_online.rb:15:in `chdir'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/actions/create_app_online.rb:15:in `run'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
15:01:42  	from Fastfile:2:in `block in parsing_binding'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/lane.rb:33:in `call'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/bin/fastlane:23:in `<top (required)>'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/bin/fastlane:23:in `load'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/bin/fastlane:23:in `<main>'
15:01:42  /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/produce/lib/produce/developer_center.rb:148:in `block in enable_services': undefined method `sign_in_with_apple' for Spaceship::Portal::AppService:Class (NoMethodError)
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/produce/lib/produce/developer_center.rb:127:in `each'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/produce/lib/produce/developer_center.rb:127:in `enable_services'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/produce/lib/produce/developer_center.rb:99:in `create_new_app'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/produce/lib/produce/developer_center.rb:84:in `run'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/produce/lib/produce/manager.rb:11:in `start_producing'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/actions/create_app_online.rb:17:in `block in run'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/actions/create_app_online.rb:15:in `chdir'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/actions/create_app_online.rb:15:in `run'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
15:01:42  	from Fastfile:2:in `block in parsing_binding'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/lane.rb:33:in `call'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.190.0/bin/fastlane:23:in `<top (required)>'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/bin/fastlane:23:in `load'
15:01:42  	from /Users/****/.rbenv/versions/2.7.1/bin/fastlane:23:in `<main>'
```

**Comment by lucgrabowski** [comment]
Hi, 
I think that to enable `sign_in_with_apple`, you could use `modify_services` just after `produce`
http://docs.fastlane.tools/actions/modify_services/#modify_services
```ruby
modify_services(
  app_identifier: app_identifier,
  services: {
   associated_domains: "on",
    push_notification: "on",
    sign_in_with_apple: "on"
  })
  ```

`sign_in_with_apple` doesn't seem to be supported in `Spaceship::Portal::AppService`:
https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/portal/app_service.rb

**Comment by Cheshire7740** [comment]
I am also having the same Issue. Did you get any solution?

**Comment by max-ott** [comment]
This has probably been never added to fastlane, so you cannot simply add it in the services hash.
