### ISSUE TITLE
app.analytics fails with UnexpectedResponse Error - There is no route for the path

### ISSUE THREAD

**Issue by kevin-lxh** [fastlane/fastlane#19202]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
My codes like this
```
Spaceship::Tunes.login('xxx', 'xxx')
app = Spaceship::Tunes::Application.find('com.xxx.xxx')
analytics = app.analytics
```

Then I got the error
```
Traceback (most recent call last):
	6: from index.rb:17:in `<main>'
	5: from /Users/Kevin/.rvm/gems/ruby-2.7.2/gems/fastlane-2.190.0/spaceship/lib/spaceship/tunes/application.rb:146:in `analytics'
	4: from /Users/Kevin/.rvm/gems/ruby-2.7.2/gems/fastlane-2.190.0/spaceship/lib/spaceship/tunes/application.rb:126:in `live_version'
	3: from /Users/Kevin/.rvm/gems/ruby-2.7.2/gems/fastlane-2.190.0/spaceship/lib/spaceship/tunes/app_version.rb:291:in `find'
	2: from /Users/Kevin/.rvm/gems/ruby-2.7.2/gems/fastlane-2.190.0/spaceship/lib/spaceship/tunes/tunes_client.rb:452:in `app_version'
	1: from /Users/Kevin/.rvm/gems/ruby-2.7.2/gems/fastlane-2.190.0/spaceship/lib/spaceship/tunes/tunes_client.rb:461:in `app_version_data'
/Users/Kevin/.rvm/gems/ruby-2.7.2/gems/fastlane-2.190.0/spaceship/lib/spaceship/client.rb:763:in `parse_response': <?xml version="1.0" encoding="UTF-8"?> (Spaceship::UnexpectedResponse)
<String>There is no route for the path 'apps/12345xxx/platforms/ios/versions/23456xxx'.</String>
```

<details><summary> fastlane environment </summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.1                                        |
| Ruby                        | 2.7.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.30.1 (Apple Git-130)          |
| Installation Source         | ~/.rvm/gems/ruby-2.7.2/bin/fastlane         |
| Host                        | macOS 11.1 (20C69)                          |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.7.2/lib                |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.5                                        |
| Swift Version               | 5.4                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.190.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.4.0        |
| executable-hooks                | 1.6.1        |
| bundler-unload                  | 1.0.2        |
| rubygems-bundler                | 1.4.5        |
| bundler                         | 2.1.4        |
| atomos                          | 0.1.3        |
| CFPropertyList                  | 3.0.3        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.19.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.83.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.1.0        |
| ruby2_keywords                  | 0.0.4        |
| faraday                         | 1.4.3        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.0.0        |
| fastimage                       | 2.2.4        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.3.0        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.0        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| simctl                          | 1.6.8        |
| jwt                             | 2.2.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.1        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| signet                          | 0.15.0       |
| googleauth                      | 0.16.2       |
| httpclient                      | 2.8.3        |
| rexml                           | 3.2.3        |
| webrick                         | 1.6.0        |
| google-apis-core                | 0.4.0        |
| google-apis-playcustomapp_v1    | 0.4.0        |
| google-apis-androidpublisher_v3 | 0.7.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.5.0        |
| google-apis-storage_v1          | 0.5.0        |
| rake                            | 13.0.1       |
| digest-crc                      | 0.6.3        |
| google-cloud-storage            | 1.34.0       |
| emoji_regex                     | 3.2.2        |
| jmespath                        | 1.4.0        |
| aws-partitions                  | 1.472.0      |
| aws-eventstream                 | 1.1.1        |
| aws-sigv4                       | 1.2.3        |
| aws-sdk-core                    | 3.115.0      |
| aws-sdk-kms                     | 1.44.0       |
| aws-sdk-s3                      | 1.96.1       |
| uri                             | 0.10.0       |
| forwardable                     | 1.3.1        |
| logger                          | 1.4.2        |
| cgi                             | 0.1.0        |
| date                            | 3.0.0        |
| timeout                         | 0.1.0        |
| stringio                        | 0.1.0        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.1.0        |
| ostruct                         | 0.2.0        |
| strscan                         | 1.0.3        |
| io-console                      | 0.5.6        |
| delegate                        | 0.1.0        |
| fileutils                       | 1.4.1        |
| singleton                       | 0.1.0        |
| open3                           | 0.1.0        |
| yaml                            | 0.1.0        |
| psych                           | 3.1.0        |
| mutex_m                         | 0.1.0        |
</details>

*generated on:* **2021-08-04**
</details>

**Comment by xwal** [comment]
Hi @kevin-lxh , I met the same problem 'There is no route for the path', how did you solve it?

**Comment by Reiszecke** [comment]
@kevin-lxh why do you close an issue without comment? Have you solved it?
