### ISSUE TITLE
Android Screenshots not working API 25

### ISSUE THREAD

**Issue by sp71** [fastlane/fastlane#19218]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
* Fastlane `generate_screenshots` fails always
* The instrument tests navigates the app fine (screen change, button click, etc)
* I checked the emulator using adb shell and I cannot find any screenshots being written. This would explain why it cannot read the contents when it tries
* Same error on devices: Pixel 2 API 25 and Nexus 7 API 25

##### Command executed
* bundle exec fastlane generate_screenshots

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> ➜  SikhLifeAndroid git:(master) ✗ bundle exec fastlane generate_screenshots

[✔] 🚀
+----------------------------------+---------+----------------------------+
|                              Used plugins                               |
+----------------------------------+---------+----------------------------+
| Plugin                           | Version | Action                     |
+----------------------------------+---------+----------------------------+
| fastlane-plugin-versioning_andr  | 0.1.0   | android_get_version_name,  |
| oid                              |         | android_set_version_code,  |
|                                  |         | android_set_version_name,  |
|                                  |         | android_get_version_code   |
+----------------------------------+---------+----------------------------+

[19:47:02]: ------------------------------
[19:47:02]: --- Step: default_platform ---
[19:47:02]: ------------------------------
[19:47:02]: Driving the lane 'android generate_screenshots' 🚀
[19:47:02]: -----------------------------------------
[19:47:02]: --- Step: capture_android_screenshots ---
[19:47:02]: -----------------------------------------

+-----------------------------+-----------------------------------------------------+
|                          Summary for screengrab 2.191.0                           |
+-----------------------------+-----------------------------------------------------+
| locales                     | ["en-US", "pa-IN"]                                  |
| device_type                 | phone                                               |
| clear_previous_screenshots  | true                                                |
| app_apk_path                | app/build/outputs/apk/debug/app-debug.apk           |
| tests_apk_path              | app/build/outputs/apk/androidTest/debug/app-debug-  |
|                             | androidTest.apk                                     |
| tests_package_name          | com.surreal.interactive.sikhLife.test               |
| android_home                | /Users/satindersingh/Library/Android/sdk            |
| output_directory            | fastlane/metadata/android                           |
| skip_open_summary           | false                                               |
| app_package_name            | com.surreal.interactive.sikhLife                    |
| test_instrumentation_runner | androidx.test.runner.AndroidJUnitRunner             |
| ending_locale               | en-US                                               |
| use_adb_root                | false                                               |
| exit_on_test_failure        | true                                                |
| reinstall_app               | false                                               |
| use_timestamp_suffix        | true                                                |
+-----------------------------+-----------------------------------------------------+

[19:47:02]: Limiting the test classes run by `screengrab` to just those that generate screenshots can make runs faster.
[19:47:02]: Consider using the :use_tests_in_classes or :use_tests_in_packages option, and organize your tests accordingly.
[19:47:02]: Clearing phoneScreenshots within fastlane/metadata/android
[19:47:02]: $ /Users/satindersingh/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell echo \$EXTERNAL_STORAGE
[19:47:02]: ▸ /sdcard
[19:47:02]: $ /Users/satindersingh/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell echo \$ANDROID_DATA
[19:47:02]: ▸ /data
[19:47:02]: Cleaning screenshots on device
ls: /sdcard/com.surreal.interactive.sikhLife/screengrab/en-US/images/screenshots: No such file or directory
[19:47:03]: Exit status: 1
ls: /sdcard/Android/data/com.surreal.interactive.sikhLife/files/screengrab/en-US/images/screenshots: No such file or directory
[19:47:03]: Exit status: 1
ls: /sdcard/com.surreal.interactive.sikhLife/screengrab/pa-IN/images/screenshots: No such file or directory
[19:47:03]: Exit status: 1
ls: /sdcard/Android/data/com.surreal.interactive.sikhLife/files/screengrab/pa-IN/images/screenshots: No such file or directory
[19:47:03]: Exit status: 1
ls: /data/user/0/com.surreal.interactive.sikhLife/files/com.surreal.interactive.sikhLife/screengrab/en-US/images/screenshots: No such file or directory
[19:47:03]: Exit status: 1
ls: /data/data/com.surreal.interactive.sikhLife/files/com.surreal.interactive.sikhLife/screengrab/en-US/images/screenshots: No such file or directory
[19:47:03]: Exit status: 1
ls: /data/data/com.surreal.interactive.sikhLife/app_screengrab/en-US/images/screenshots: No such file or directory
[19:47:03]: Exit status: 1
ls: /data/data/com.surreal.interactive.sikhLife/screengrab/en-US/images/screenshots: No such file or directory
[19:47:03]: Exit status: 1
ls: /data/user/0/com.surreal.interactive.sikhLife/files/com.surreal.interactive.sikhLife/screengrab/pa-IN/images/screenshots: No such file or directory
[19:47:03]: Exit status: 1
ls: /data/data/com.surreal.interactive.sikhLife/files/com.surreal.interactive.sikhLife/screengrab/pa-IN/images/screenshots: No such file or directory
[19:47:03]: Exit status: 1
ls: /data/data/com.surreal.interactive.sikhLife/app_screengrab/pa-IN/images/screenshots: No such file or directory
[19:47:03]: Exit status: 1
ls: /data/data/com.surreal.interactive.sikhLife/screengrab/pa-IN/images/screenshots: No such file or directory
[19:47:03]: Exit status: 1
[19:47:03]: $ /Users/satindersingh/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop ro.build.version.sdk
[19:47:03]: ▸ 25
[19:47:03]: Installing app APK
[19:47:03]: $ /Users/satindersingh/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -t -r app/build/outputs/apk/debug/app-debug.apk
[19:47:03]: ▸ Performing Streamed Install
[19:47:07]: ▸ Success
[19:47:07]: Installing tests APK
[19:47:07]: $ /Users/satindersingh/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -t -r app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
[19:47:07]: ▸ Performing Streamed Install
[19:47:08]: ▸ Success
[19:47:08]: Granting the permission necessary to change locales on the device
[19:47:08]: $ /Users/satindersingh/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm grant com.surreal.interactive.sikhLife android.permission.CHANGE_CONFIGURATION
[19:47:09]: Granting the permissions necessary to access device external storage
[19:47:09]: $ /Users/satindersingh/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm grant com.surreal.interactive.sikhLife android.permission.WRITE_EXTERNAL_STORAGE
[19:47:09]: $ /Users/satindersingh/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm grant com.surreal.interactive.sikhLife android.permission.READ_EXTERNAL_STORAGE
[19:47:09]: Enabling clean status bar
[19:47:09]: $ /Users/satindersingh/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm grant com.surreal.interactive.sikhLife android.permission.DUMP
[19:47:09]: $ /Users/satindersingh/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell settings put global sysui_demo_allowed 1
[19:47:09]: $ /Users/satindersingh/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am force-stop com.surreal.interactive.sikhLife.test
[19:47:10]: $ /Users/satindersingh/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am force-stop com.surreal.interactive.sikhLife
[19:47:10]: Running tests for locale: en-US
[19:47:10]: $ /Users/satindersingh/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am instrument --no-window-animation -w \
-e testLocale en-US \
-e appendTimestamp true \
com.surreal.interactive.sikhLife.test/androidx.test.runner.AndroidJUnitRunner
[19:47:56]: ▸ com.surreal.interactive.sikhLife.MainActivityTest:.
[19:47:56]: ▸ Time: 45.245
[19:47:56]: ▸ OK (1 test)
[19:47:56]: Pulling captured screenshots for locale en-US from the device
[19:47:56]: $ /Users/satindersingh/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell echo \$EXTERNAL_STORAGE
[19:47:56]: ▸ /sdcard
[19:47:56]: $ /Users/satindersingh/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell echo \$ANDROID_DATA
[19:47:56]: ▸ /data
ls: /sdcard/com.surreal.interactive.sikhLife/screengrab/en-US/images/screenshots: No such file or directory
[19:47:56]: Exit status: 1
ls: /sdcard/Android/data/com.surreal.interactive.sikhLife/files/screengrab/en-US/images/screenshots: No such file or directory
[19:47:56]: Exit status: 1
ls: /data/user/0/com.surreal.interactive.sikhLife/files/com.surreal.interactive.sikhLife/screengrab/en-US/images/screenshots: No such file or directory
[19:47:56]: Exit status: 1
ls: /data/data/com.surreal.interactive.sikhLife/files/com.surreal.interactive.sikhLife/screengrab/en-US/images/screenshots: No such file or directory
[19:47:56]: Exit status: 1
ls: /data/data/com.surreal.interactive.sikhLife/app_screengrab/en-US/images/screenshots: No such file or directory
[19:47:56]: Exit status: 1
ls: /data/data/com.surreal.interactive.sikhLife/screengrab/en-US/images/screenshots: No such file or directory
[19:47:57]: Exit status: 1
[19:47:57]: Make sure you've used Screengrab.screenshot() in your tests and that your expected tests are being run.
+------------------+------------------------------+
|                  Lane Context                   |
+------------------+------------------------------+
| DEFAULT_PLATFORM | android                      |
| PLATFORM_NAME    | android                      |
| LANE_NAME        | android generate_screenshots |
+------------------+------------------------------+
[19:47:57]: No screenshots were detected 📷❌

+------+-----------------------------+-------------+
|                 fastlane summary                 |
+------+-----------------------------+-------------+
| Step | Action                      | Time (in s) |
+------+-----------------------------+-------------+
| 1    | default_platform            | 0           |
| 💥   | capture_android_screenshots | 54          |
+------+-----------------------------+-------------+

[19:47:57]: fastlane finished with errors

[!] No screenshots were detected 📷❌ </pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.5.1                                      |
| Ruby                        | 2.7.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.29.2                          |
| Installation Source         | ~/.rvm/gems/ruby-2.7.0/bin/fastlane         |
| Host                        | macOS 11.5.1 (20G80)                        |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.7.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.5.1                                      |
| Swift Version               | 5.4.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Screenshot with Debug Build Debug"
  lane :build_for_screengrab do
    if prompt(text: "Clean Build?", boolean: true)
      gradle(task: 'clean')
      build_android_app(task: 'assemble', build_type: 'Debug')
      build_android_app(task: 'assemble', build_type: 'AndroidTest')
    end
    generate_screenshots
  end

  desc "Generates AppStore Screenshots"
  lane :generate_screenshots do |options|
    capture_android_screenshots(
      locales: ["en-US", "pa-IN"],
      device_type: "phone",
      clear_previous_screenshots: true,
      app_apk_path: "app/build/outputs/apk/debug/app-debug.apk",
      tests_apk_path: "app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk"
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("fastlane-key.json") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("com.surreal.interactive.sikhLife") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.191.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                             | Version | Update-Status |
| ---------------------------------- | ------- | ------------- |
| fastlane-plugin-versioning_android | 0.1.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                | Version      |
| ---------------------------------- | ------------ |
| did_you_mean                       | 1.4.0        |
| executable-hooks                   | 1.6.0        |
| bundler-unload                     | 1.0.2        |
| rubygems-bundler                   | 1.4.5        |
| bundler                            | 2.1.4        |
| rake                               | 13.0.6       |
| CFPropertyList                     | 3.0.3        |
| public_suffix                      | 4.0.6        |
| addressable                        | 2.8.0        |
| artifactory                        | 3.0.15       |
| atomos                             | 0.1.3        |
| aws-eventstream                    | 1.1.1        |
| aws-partitions                     | 1.484.0      |
| aws-sigv4                          | 1.2.4        |
| jmespath                           | 1.4.0        |
| aws-sdk-core                       | 3.119.0      |
| aws-sdk-kms                        | 1.46.0       |
| aws-sdk-s3                         | 1.98.0       |
| babosa                             | 1.0.4        |
| claide                             | 1.0.3        |
| colored                            | 1.2          |
| colored2                           | 3.1.2        |
| highline                           | 2.0.3        |
| commander                          | 4.6.0        |
| declarative                        | 0.0.20       |
| digest-crc                         | 0.6.4        |
| unf_ext                            | 0.0.7.7      |
| unf                                | 0.1.4        |
| domain_name                        | 0.5.20190701 |
| dotenv                             | 2.7.6        |
| emoji_regex                        | 3.2.2        |
| excon                              | 0.85.0       |
| faraday-em_http                    | 1.0.0        |
| faraday-em_synchrony               | 1.0.0        |
| faraday-excon                      | 1.1.0        |
| faraday-httpclient                 | 1.0.1        |
| faraday-net_http                   | 1.0.1        |
| faraday-net_http_persistent        | 1.2.0        |
| faraday-patron                     | 1.0.0        |
| faraday-rack                       | 1.0.0        |
| multipart-post                     | 2.0.0        |
| ruby2_keywords                     | 0.0.5        |
| faraday                            | 1.6.0        |
| http-cookie                        | 1.0.4        |
| faraday-cookie_jar                 | 0.0.7        |
| faraday_middleware                 | 1.1.0        |
| fastimage                          | 2.2.4        |
| gh_inspector                       | 1.1.3        |
| jwt                                | 2.2.3        |
| memoist                            | 0.16.2       |
| multi_json                         | 1.15.0       |
| os                                 | 1.1.1        |
| signet                             | 0.15.0       |
| googleauth                         | 0.17.0       |
| httpclient                         | 2.8.3        |
| mini_mime                          | 1.1.0        |
| trailblazer-option                 | 0.1.1        |
| uber                               | 0.1.0        |
| representable                      | 3.1.1        |
| retriable                          | 3.1.2        |
| rexml                              | 3.2.5        |
| webrick                            | 1.7.0        |
| google-apis-core                   | 0.4.1        |
| google-apis-androidpublisher_v3    | 0.10.0       |
| google-apis-playcustomapp_v1       | 0.5.0        |
| google-apis-iamcredentials_v1      | 0.6.0        |
| google-apis-storage_v1             | 0.6.0        |
| google-cloud-env                   | 1.5.0        |
| google-cloud-errors                | 1.1.0        |
| google-cloud-core                  | 1.6.0        |
| google-cloud-storage               | 1.34.1       |
| json                               | 2.5.1        |
| mini_magick                        | 4.11.0       |
| naturally                          | 2.2.1        |
| plist                              | 3.6.0        |
| rubyzip                            | 2.3.2        |
| security                           | 0.1.3        |
| simctl                             | 1.6.8        |
| terminal-notifier                  | 2.0.0        |
| unicode-display_width              | 1.7.0        |
| terminal-table                     | 1.8.0        |
| tty-screen                         | 0.8.1        |
| tty-cursor                         | 0.7.1        |
| tty-spinner                        | 0.9.3        |
| word_wrap                          | 1.0.0        |
| nanaimo                            | 0.3.0        |
| xcodeproj                          | 1.20.0       |
| rouge                              | 2.0.7        |
| xcpretty                           | 0.3.0        |
| xcpretty-travis-formatter          | 1.0.1        |
| fastlane-plugin-versioning_android | 0.1.0        |
</details>

*generated on:* **2021-08-08**
</details> </pre>
</details>

**Comment by Frank9898** [comment]
Thanks for sharing this information.
