### ISSUE TITLE
firebase_app_distribution Stopped deploying

### ISSUE THREAD

**Issue by JustinasKristopaitis** [fastlane/fastlane#19227]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
After updating macOS, Xcode to newest versions, and when using fastlane, CI stopped deploying to firebase, 

##### Command executed
 bundle exec fastlane firebase_app_distribution 

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> +---------------------+-----------------------------------------------------------------------------------------------------------------+
|                                                             Lane Context                                                              |
+---------------------+-----------------------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM    | ios                                                                                                             |
| PLATFORM_NAME       | ios                                                                                                             |
| LANE_NAME           | ios deploy_firebase_debug                                                                                       |
| BUILD_NUMBER        | 202108.12.153846                                                                                                |
| CERT_FILE_PATH      | /Users/ci/builds/syqQyRNi/0/organization/apps/iOS/xxxxxx.cer                                 |
| CERT_CERTIFICATE_ID | QDZKXTUSPM                                                                                                      |
| SIGH_PROFILE_PATH   | /Users/ci/builds/syqQyRNi/0/organization/apps/iOS/AdHoc_com.xxx.App.mobileprovision             |
| SIGH_PROFILE_PATHS  | ["/Users/ci/builds/syqQyRNi/0/organization/apps/iOS/AdHoc_com.xxx.App.mobileprovision"]         |
| SIGH_UDID           | 031cc0ad-6c3a-42ed-8280-886f8c984ae0                                                                            |
| SIGH_UUID           | 031cc0ad-6c3a-42ed-8280-886f8c984ae0                                                                            |
| SIGH_NAME           | com.xxxx.App AdHoc 1623158172                                                                                   |
| SIGH_PROFILE_TYPE   | ad-hoc                                                                                                          |
| IPA_OUTPUT_PATH     | /Users/ci/builds/syqQyRNi/0/organization/apps/iOS/xxx.ipa                                       |
| XCODEBUILD_ARCHIVE  | /Users/ci/builds/syqQyRNi/0/organization/apps/iOS/build/Build/xxx 2021-08-12 15.39.19.xcarchive |
| DSYM_OUTPUT_PATH    | /Users/ci/builds/syqQyRNi/0/organization/apps/iOS/xxx.app.dSYM.zip                              |
+---------------------+-----------------------------------------------------------------------------------------------------------------+
[15:50:51]: Could not find action, lane or variable 'firebase_app_distribution'. Check out the documentation for more details: https://docs.fastlane.tools/actions
+------+--------------------------------------+-------------+
|                     fastlane summary                      |
+------+--------------------------------------+-------------+
| Step | Action                               | Time (in s) |
+------+--------------------------------------+-------------+
| 1    | default_platform                     | 0           |
| 2    | app_store_connect_api_key            | 0           |
| 3    | cocoapods                            | 19          |
| 4    | increment_build_number               | 1           |
| 5    | automatic_code_signing               | 0           |
| 6    | update_code_signing_settings         | 0           |
| 7    | get_certificates                     | 1           |
| 8    | get_provisioning_profile             | 3           |
| 9    | Switch to ios download_lokalise lane | 0           |
| 10   | lokalise                             | 3           |
| 11   | cocoapods                            | 13          |
| 12   | gym                                  | 700         |
+------+--------------------------------------+-------------+
[15:50:51]: fastlane finished with errors
[!] Could not find action, lane or variable 'firebase_app_distribution'. Check out the documentation for more details: https://docs.fastlane.tools/actions
Cleaning up file based variables
00:00
ERROR: Job failed: exit status 1 </pre>
</details>

### Environment

<details>
  <pre> 

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.5.1                                      |
| Ruby                        | 2.7.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.30.1 (Apple Git-130)          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | macOS 11.5.1 (20G80)                        |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.2/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.5.1                                      |
| Swift Version               | 5.4.2                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform :ios

platform :ios do
  before_all do
  app_store_connect_api_key(
    key_id: “xxxxx”,
    issuer_id: “xxxxx”,
    key_filepath: "fastlane/AuthKey_xxxx.p8",
    duration: 1200,
    in_house: false,
  )
    ENV['SLACK_URL'] = 'https://hooks.slack.com/services/xxxx/xxx/xxx’
    ENV['FASTLANE_XCODEBUILD_SETTINGS_RETRIES'] = '10'
    ENV['FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT'] = '20'
    ENV['CI_TMP_DIR'] = ENV['CI_PROJECT_DIR'].nil? ? nil : "#{ENV['CI_PROJECT_DIR']}/build"
  end

  # Defs

  def prepare_certificates
    enable_automatic_code_signing
    update_code_signing_settings(use_automatic_signing: true)
    get_certificates
    get_provisioning_profile
  end

  def prepare_adhoc_certificates
    enable_automatic_code_signing
    update_code_signing_settings(use_automatic_signing: true)
    get_certificates
    get_provisioning_profile(adhoc: true)
  end

  def update_build_number
    increment_build_number(
      build_number: Time.new.strftime("%Y%m.%d.%H%M%S")
    )
  end

  # Lanes
  desc 'Bump build number to current time'
  lane :bumpBuildNumber do
    update_build_number()
  end

  desc 'Bump patch in MAJOR.MINOR.PATCH format'
  lane :bumpPatch do
    increment_version_number(
      bump_type: 'patch'
    )
  end

  desc 'Bump minor in MAJOR.MINOR.PATCH format'
  lane :bumpMinor do
    increment_version_number(
      bump_type: 'minor'
    )
  end

  lane :upload_symbols do |options|
    download_dsyms(
      version: options[:version] || 'live'
    )

    upload_symbols_to_crashlytics(
      gsp_path: "./xxx/Resources/Google\ Services/GoogleService-Info.plist",
      app_id: “1xxxxx
    )

    clean_build_artifacts()
  end

  desc 'Bump major in MAJOR.MINOR.PATCH format'
  lane :bumpMajor do
    increment_version_number(
      bump_type: 'major'
    )
  end

  desc 'Run tests'
  lane :tests do
    scan(
      scheme: 'xxx - Production',
      derived_data_path: ENV['CI_TMP_DIR'].nil? ? nil : "#{ENV['CI_TMP_DIR']}/DerivedData",
      output_directory: ENV['CI_TMP_DIR'].nil? ? nil : "#{ENV['CI_TMP_DIR']}/Scan",
      buildlog_path: ENV['CI_TMP_DIR'].nil? ? nil : "#{ENV['CI_TMP_DIR']}/Logs/scan",
      xcargs: "-quiet"
    )
  end

  desc 'Update localizations from localise.co'
  lane :download_lokalise do
    lokalise(
        api_token: ‘xxxxx’,
        project_identifier: ‘xxxxxx’,
        use_original: true,
        languages: ['lt', 'en', 'ru', 'es', 'de', 'fr', 'pt', 'nl', 'pl', 'sv', 'ja', 'it'],
        destination: 'xxx/Resources'
    )
  end

  lane :add_sandbox_user do |options|
    number_of_accounts = 1
    country = options[:country] || ‘DE’
    password = options[:password] || 'xxx’
    email = options[:email]
    if !email && options[:count]
      number_of_accounts = options[:count].to_i
    end

    Spaceship::Tunes.login
    nextUserId = Spaceship::Tunes::SandboxTester.all.count + 1

    for userId in nextUserId..nextUserId+number_of_accounts-1
        generatedEmail = email || userId.to_s + '@xxx.app'
        user = Spaceship::Tunes::SandboxTester.create!(
          email: generatedEmail,
          password: password,
          country: country
        )
        puts 'Created ' + generatedEmail
    end
  end

  desc 'Build'
  lane :build do

    cocoapods(
      podfile: 'Podfile',
      try_repo_update_on_error: true
    )

    prepare_certificates()

    # Build
    gym(
      scheme: 'xxx - Production',
      derived_data_path: ENV['CI_TMP_DIR'].nil? ? nil : "#{ENV['CI_TMP_DIR']}/DerivedData",
      build_path: ENV['CI_TMP_DIR'].nil? ? nil : "#{ENV['CI_TMP_DIR']}/Build",
      buildlog_path: ENV['CI_TMP_DIR'].nil? ? nil : "#{ENV['CI_TMP_DIR']}/Logs/gym",
      xcargs: "-quiet",
      export_options: {
        'provisioningProfiles': {
          'com.xxx.App': 'com.xxx.App AppStore',
          'com.xxx.App.Today': 'com.xxx.App.Today AppStore',
          'com.xxx.App.watchkitapp': 'com.xxx.App.watchkitapp AppStore',
          'com.xxx.App.watchkitapp.watchkitextension': 'com.xxx.App.watchkitapp.watchkitextension AppStore',
          'com.xxx.App.Notification': 'com.xxx.App.Notification AppStore',
          'com.xxx.App.ClickerWidget': 'com.xxx.App.Notification AppStore',
          'com.xxx.App.LessonWidget': 'com.xxx.App.LessonWidget',
          'com.xxx.App.NotificationService': 'com.xxx.App.Notification AppStore'
        }
      },
      skip_archive: true
    )
    #
    scan(
      scheme: 'xxx - Production',
      derived_data_path: ENV['CI_TMP_DIR'].nil? ? nil : "#{ENV['CI_TMP_DIR']}/DerivedData",
      output_directory: ENV['CI_TMP_DIR'].nil? ? nil : "#{ENV['CI_TMP_DIR']}/Scan",
      buildlog_path: ENV['CI_TMP_DIR'].nil? ? nil : "#{ENV['CI_TMP_DIR']}/Logs/scan",
      xcargs: "-quiet"
    )
  end

  desc 'Upload to Testflight'
  lane :deploy do

    cocoapods(
      podfile: 'Podfile',
      try_repo_update_on_error: true
    )

    update_build_number()
    prepare_certificates()
    download_lokalise()

    # Build
    gym(
      scheme: 'xxx - Production',
      derived_data_path: ENV['CI_TMP_DIR'].nil? ? nil : "#{ENV['CI_TMP_DIR']}/DerivedData",
      build_path: ENV['CI_TMP_DIR'].nil? ? nil : "#{ENV['CI_TMP_DIR']}/Build",
      buildlog_path: ENV['CI_TMP_DIR'].nil? ? nil : "#{ENV['CI_TMP_DIR']}/Logs/gym",
      xcargs: "-quiet",
      export_options: {
        'provisioningProfiles': {
          'com.xxx.App': 'com.xxx.App AppStore',
          'com.xxx.App.Today': 'com.xxx.App.Today AppStore',
          'com.xxx.App.watchkitapp': 'com.xxx.App.watchkitapp AppStore',
          'com.xxx.App.watchkitapp.watchkitextension': 'com.xxx.App.watchkitapp.watchkitextension AppStore',
          'com.xxx.App.Notification': 'com.xxx.App.Notification AppStore',
          'com.xxx.App.ClickerWidget': 'com.xxx.App.Notification AppStore',
          'com.xxx.App.LessonWidget': 'com.xxx.App.LessonWidget',
          'com.xxx.App.NotificationService': 'com.xxx.App.Notification AppStore'
        },
      }
    )
    pilot(
      skip_waiting_for_build_processing: true
    )
  end

  desc 'Upload Debug App to Testflight'
  lane :deploy_debug do

    cocoapods(
      podfile: 'Podfile',
      try_repo_update_on_error: true
    )

    update_build_number()
    prepare_certificates()
    download_lokalise()

    #Build
    gym(
      scheme: 'xxx - Debug',
      derived_data_path: ENV['CI_TMP_DIR'].nil? ? nil : "#{ENV['CI_TMP_DIR']}/DerivedData",
      build_path: ENV['CI_TMP_DIR'].nil? ? nil : "#{ENV['CI_TMP_DIR']}/Build",
      buildlog_path: ENV['CI_TMP_DIR'].nil? ? nil : "#{ENV['CI_TMP_DIR']}/Logs/gym",
      xcargs: "-quiet",
      export_options: {
        'provisioningProfiles': {
          'com.xxx.xxx-DebugV2': 'com.xxx.xxx-DebugV2 AppStore',
          'com.xxx.xxx-DebugV2.Today': 'com.xxx.xxx-DebugV2 Today',
          'com.xxx.xxx-DebugV2.watchkitapp': 'com.xxx.xxx-DebugV2.watchkitapp AppStore',
          'com.xxx.xxx-DebugV2.watchkitapp.watchkitextension': 'com.xxx.xxx-DebugV2.watchkitapp.watchkitextensio',
          'com.xxx.xxx-DebugV2.Notification': 'com.xxx.xxx-DebugV2 Wildcard',
          'com.xxx.xxx-DebugV2.LessonWidget': 'com.xxx.xxx-DebugV2 LessonWidget',
          'com.xxx.xxx-DebugV2.ClickerWidget': 'com.xxx.xxx-DebugV2 Wildcard',
          'com.xxx.xxx-DebugV2.NotificationService': 'com.xxx.xxx-DebugV2 Wildcard'
        },
      }
    )
    # Upload
    pilot(
      skip_waiting_for_build_processing: true,
      changelog: ENV['RELEASE_NOTES'],
    )
  end

  desc '[Debug] Upload to Firebase Distribution'
  lane :deploy_firebase_debug do
    cocoapods(
      podfile: 'Podfile',
      try_repo_update_on_error: true
    )

    update_build_number()
    prepare_adhoc_certificates()
    download_lokalise()

    cocoapods(
      podfile: 'Podfile',
      try_repo_update_on_error: true
    )

    #Build
    gym(
      scheme: 'xxx - Debug',
      derived_data_path: ENV['CI_TMP_DIR'].nil? ? nil : "#{ENV['CI_TMP_DIR']}/DerivedData",
      build_path: ENV['CI_TMP_DIR'].nil? ? nil : "#{ENV['CI_TMP_DIR']}/Build",
      buildlog_path: ENV['CI_TMP_DIR'].nil? ? nil : "#{ENV['CI_TMP_DIR']}/Logs/gym",
      xcargs: "-quiet",
      export_options: {
        'method': 'ad-hoc',
        'provisioningProfiles': {
          'com.xxx.xxx-DebugV2': 'Debug Adhoc',
          'com.xxx.xxx-DebugV2.Today': 'Debug Adhoc Today',
          'com.xxx.xxx-DebugV2.watchkitapp': 'Adhoc Wildcard',
          'com.xxx.xxx-DebugV2.watchkitapp.watchkitextension': 'Adhoc Wildcard',
          'com.xxx.xxx-DebugV2.Notification': 'Adhoc Wildcard',
          'com.xxx.xxx-DebugV2.LessonWidget': 'Debug Adhoc LessonWidget',
          'com.xxx.xxx-DebugV2.ClickerWidget': 'Adhoc Wildcard',
          'com.xxx.xxx-DebugV2.NotificationService': 'Adhoc Wildcard'
        },
      }
    )

    firebase_app_distribution(
      app: "xxxxx",
      service_credentials_file: ENV['FIREBASE_APP_DIST_KEY_DEVELOP'],
      release_notes: ENV['RELEASE_NOTES'],
      groups: 'xxx-ios'
    )
  end

  desc 'Upload to Firebase Distribution'
  lane :deploy_firebase do
    cocoapods(
      podfile: 'Podfile',
      try_repo_update_on_error: true
    )

    update_build_number()
    prepare_adhoc_certificates()
    download_lokalise()

    cocoapods(
      podfile: 'Podfile',
      try_repo_update_on_error: true
    )

    #Build
    gym(
      scheme: 'xxx - Production',
      derived_data_path: ENV['CI_TMP_DIR'].nil? ? nil : "#{ENV['CI_TMP_DIR']}/DerivedData",
      build_path: ENV['CI_TMP_DIR'].nil? ? nil : "#{ENV['CI_TMP_DIR']}/Build",
      buildlog_path: ENV['CI_TMP_DIR'].nil? ? nil : "#{ENV['CI_TMP_DIR']}/Logs/gym",
      xcargs: "-quiet",
      export_options: {
        'method': 'ad-hoc',
        'provisioningProfiles': {
          'com.xxx.App': 'com.xxx.App AdHoc',
          'com.xxx.App.Today': 'Adhoc Today',
          'com.xxx.App.watchkitapp': 'Adhoc Wildcard',
          'com.xxx.App.watchkitapp.watchkitextension': 'Adhoc Wildcard',
          'com.xxx.App.Notification': 'Adhoc Wildcard',
          'com.xxx.App.ClickerWidget': 'Adhoc Wildcard',
          'com.xxx.App.LessonWidget': 'Adhoc LessonWidget',
          'com.xxx.App.NotificationService': 'Adhoc Wildcard'
        },
      }
    )

    firebase_app_distribution(
      app: "1xxxa",
      service_credentials_file: ENV['FIREBASE_APP_DIST_KEY_PROD'],
      release_notes: ENV['RELEASE_NOTES'],
      groups: 'xxx-ios'
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.xxx.App" # The bundle identifier of your app
team_id “xxxx” # Developer Portal Team ID
itc_team_id “xxxxxx”

for_platform :ios do  
  for_lane :deploy_debug do
    app_identifier 'com.xxx.xxx-DebugV2'
  end
end
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.191.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.4.0        |
| atomos                          | 0.1.3        |
| CFPropertyList                  | 3.0.3        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| rexml                           | 3.2.5        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.85.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.7.0        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.1.0        |
| fastimage                       | 2.2.5        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.3.0        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| simctl                          | 1.6.8        |
| jwt                             | 2.2.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.1        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| signet                          | 0.15.0       |
| googleauth                      | 0.17.0       |
| httpclient                      | 2.8.3        |
| webrick                         | 1.6.0        |
| google-apis-core                | 0.4.1        |
| google-apis-playcustomapp_v1    | 0.5.0        |
| google-apis-androidpublisher_v3 | 0.10.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.6.0        |
| google-apis-storage_v1          | 0.6.0        |
| rake                            | 13.0.1       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.34.1       |
| emoji_regex                     | 3.2.2        |
| jmespath                        | 1.4.0        |
| aws-eventstream                 | 1.1.1        |
| aws-sigv4                       | 1.2.4        |
| aws-sdk-core                    | 3.119.0      |
| aws-sdk-kms                     | 1.46.0       |
| aws-sdk-s3                      | 1.98.0       |
| uri                             | 0.10.0       |
| bundler                         | 2.2.25       |
| aws-partitions                  | 1.485.0      |
| forwardable                     | 1.3.1        |
| logger                          | 1.4.2        |
| cgi                             | 0.1.0        |
| date                            | 3.0.0        |
| timeout                         | 0.1.0        |
| stringio                        | 0.1.0        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.1.0        |
| mutex_m                         | 0.1.0        |
| ostruct                         | 0.2.0        |
| strscan                         | 1.0.3        |
| io-console                      | 0.5.6        |
| delegate                        | 0.1.0        |
| fileutils                       | 1.4.1        |
| singleton                       | 0.1.0        |
| open3                           | 0.1.0        |
| yaml                            | 0.1.0        |
| psych                           | 3.1.0        |
</details>

*generated on:* **2021-08-12**
</details>

 </pre>
</details>

**Comment by crazymanish** [comment]
Hi @JustinasKristopaitis 

Quickly looked into your attached ^ Fastfile, 
i think you should run `bundle exec fastlane deploy_firebase `

btw, **firebase_app_distribution** plugin has a `completely different Git repo` and if issue still exist, please feel free to open ticket here https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/issues

.
.
<img width="633" alt="Screenshot 2021-08-12 at 8 46 07 PM" src="https://user-images.githubusercontent.com/5364500/129252160-beee75c2-b33e-461c-a12b-d254185c3aa3.png">
