### ISSUE TITLE
Can Fastlane servers be clustered?

### ISSUE THREAD

**Issue by geeklingo** [fastlane/fastlane#19222]
I have an issue where my fastlane mac mini goes offline every now and then. Was thinking of have another mini running as well. Is it possible to run Fastlane clustered or with failover? I just didn't want both running the same job from Gitlab at the same time

**Comment by snatchev** [comment]
This is not within the scope of fastlane. There is no serving mechanism. The solution seems like it should be within the realm of gitlab. It should have the ability to preform a health check on your mini and failover to another one if possible.

**Comment by Braddock56** [comment]
Fast Lane is an authorized Cisco Learning Specialized Partner and authorized Cisco Business Learning Partner. With certified, experienced instructors, our broad Cisco curriculum covers routing and switching, networking, wireless, security, service provider, collaboration, and data center technologies. We offer a range of courses and certifications, from entry-level to advanced specialist, all featuring content that is approved by Cisco.
