### ISSUE TITLE
The resource 'betaFeedbacks' does not exist

### ISSUE THREAD

**Issue by wilg** [fastlane/fastlane#19239]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

It appears the undocumented API introduced in https://github.com/fastlane/fastlane/pull/15793 no longer works. (cc @max-ott )

Is there any way around this or did Apple just disable the API. Other endpoints seem to work. I am using `Spaceship::ConnectAPI::Token` to authenticate.

```
>> app.get_beta_feedback
Traceback (most recent call last):
        2: from (irb):8
        1: from (irb):9:in `rescue in irb_binding'
Spaceship::UnexpectedResponse (The URL path is not valid - The resource 'betaFeedbacks' does not exist)
```

**Comment by max-ott** [comment]
If it's not supported by the official App Store Connect API you cannot simply switch to that authentication method and expect old code to work. `Spaceship::ConnectAPI::Token` only works as an authentication method for what is available at https://developer.apple.com/documentation/appstoreconnectapi

From what I can see there is no "official" way to export that data via the API.
