### ISSUE TITLE
Documentation leaks an example of how to use regex for action `ensure_git_branch`

### ISSUE THREAD

**Issue by aymkin** [fastlane/fastlane#19246]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Documentation leaks an example of how to use regex for action `ensure_git_branch`

##### Command executed
In my Fastfile executes the following command
```ruby
ensure_git_branch(branch: "^*release-*$")
```

##### Complete output when running fastlane, including the stack trace and command used
[13:55:21]: An error occurred while executing the `error` block:
[13:55:21]: This is a destructive and potentially dangerous action. To protect from data loss, please add the `ensure_git_status_clean` action to the beginning of your lane, or if you're absolutely sure of what you're doing then call this action with the :force option.
+---------------+------------------+
|           Lane Context           |
+---------------+------------------+
| PLATFORM_NAME | ios              |
| LANE_NAME     | ios tripkey_beta |
+---------------+------------------+
[13:55:21]: Git is not on a branch matching `^*release-*$`. Current branch is `releases/release-4.1.0`! Please ensure the repo is checked out to the correct branch.
+------+-------------------+-------------+
|            fastlane summary            |
+------+-------------------+-------------+
| Step | Action            | Time (in s) |
+------+-------------------+-------------+
| 1    | update_fastlane   | 3           |
| 💥   | ensure_git_branch | 0           |
| 💥   | reset_git_repo    | 0           |
+------+-------------------+-------------+
[13:55:21]: fastlane finished with errors
[!] Git is not on a branch matching `^*release-*$`. Current branch is `releases/release-4.1.0`! Please ensure the repo is checked out to the correct branch.
Fastlane command: (fastlane "ios" "tripkey_beta") failed
If you want to send an issue report to fastlane (https://github.com/fastlane/fastlane/issues/new), you can find the output of fastlane env in the following log file:
/Users/vagrant/deploy/fastlane_env.log
Command failed, error: exit status 1

<details>
  <pre>  
   * I know there is PR to support  regex https://github.com/fastlane/fastlane/commit/f1c65bb0d7ffbe4cf64102b8b0f419289a18bd27
   * Also I did try to pass the actual regex, but got an error as well  https://prnt.sc/1qabwgk
   ```ruby
ensure_git_branch(branch: ^*release-*$/)
```
  </pre>
</details>

### Environment

Bitrise

**Comment by lucgrabowski** [comment]
Depending on what you want to achieve, you could try the following regexes: 
`^release.*$` , 
`^releases\/.*$` or 
`^.*release-.*$`
