### ISSUE TITLE
The URL path is not valid - The resource 'resetRatingsRequests' does not exist

### ISSUE THREAD

**Issue by Leonwu21** [fastlane/fastlane#19250]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When running "fastlane deliver" with the "reset_ratings" field in the Deliverfile set to true, we're getting the error below (see complete output). We've traced the error to this [API call](https://github.com/fastlane/fastlane/blob/16db9e0f2526772b9365e052a37b555e376cf7ea/spaceship/lib/spaceship/connect_api/tunes/tunes.rb#L936) but are unsure of how to fix this issue.

@joshdholtz Could you please take a look? Thanks!

##### Command executed

fastlane deliver -f --verbose --api_key_path ****

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> /Users/****/.rvm/gems/ruby-2.7.0/gems/fastlane-2.191.0/spaceship/lib/spaceship/connect_api/api_client.rb:199:in `handle_response': \e[31m[!] The URL path is not valid - The resource 'resetRatingsRequests' does not exist\e[0m (Spaceship::UnexpectedResponse)
	from /Users/****/.rvm/gems/ruby-2.7.0/gems/fastlane-2.191.0/spaceship/lib/spaceship/connect_api/api_client.rb:124:in `post'
	from /Users/****/.rvm/gems/ruby-2.7.0/gems/fastlane-2.191.0/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:951:in `post_reset_ratings_request'
	from /Users/****/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/forwardable.rb:235:in `post_reset_ratings_request'
	from /Users/****/.rvm/gems/ruby-2.7.0/gems/fastlane-2.191.0/spaceship/lib/spaceship/connect_api/models/app_store_version.rb:236:in `create_reset_ratings_request'
	from /Users/****/.rvm/gems/ruby-2.7.0/gems/fastlane-2.191.0/deliver/lib/deliver/upload_metadata.rb:335:in `upload'
	from /Users/****/.rvm/gems/ruby-2.7.0/gems/fastlane-2.191.0/deliver/lib/deliver/runner.rb:146:in `upload_metadata'
	from /Users/****/.rvm/gems/ruby-2.7.0/gems/fastlane-2.191.0/deliver/lib/deliver/runner.rb:55:in `run'
	from /Users/****/.rvm/gems/ruby-2.7.0/gems/fastlane-2.191.0/deliver/lib/deliver/commands_generator.rb:82:in `block (2 levels) in run'
	from /Users/****/.rvm/gems/ruby-2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/****/.rvm/gems/ruby-2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/****/.rvm/gems/ruby-2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/****/.rvm/gems/ruby-2.7.0/gems/fastlane-2.191.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/****/.rvm/gems/ruby-2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/****/.rvm/gems/ruby-2.7.0/gems/fastlane-2.191.0/deliver/lib/deliver/commands_generator.rb:187:in `run'
	from /Users/****/.rvm/gems/ruby-2.7.0/gems/fastlane-2.191.0/deliver/lib/deliver/commands_generator.rb:18:in `start'
	from /Users/****/.rvm/gems/ruby-2.7.0/gems/fastlane-2.191.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	from /Users/****/.rvm/gems/ruby-2.7.0/gems/fastlane-2.191.0/bin/fastlane:23:in `<top (required)>'
	from /Users/****/.rvm/gems/ruby-2.7.0/bin/fastlane:23:in `load'
	from /Users/****/.rvm/gems/ruby-2.7.0/bin/fastlane:23:in `<main>'
	from /Users/****/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:22:in `eval'
	from /Users/****/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:22:in `<main>' </pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.1                                     |
| Ruby                        | 2.7.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.21.1 (Apple Git-122.3)        |
| Installation Source         | ~/.rvm/gems/ruby-2.7.0/bin/fastlane         |
| Host                        | Mac OS X 10.15.1 (19B88)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.7.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.3.1                                      |
| Swift Version               | 5.1.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
lane :privacy do
  upload_app_privacy_details_to_app_store(
    username: "xxxx",
    team_name: "xxxx",
    app_identifier: "xxxx",
    json_path: "fastlane/app_privacy_details.json"
  )
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.191.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| executable-hooks                | 1.6.1        |
| bundler-unload                  | 1.0.2        |
| rubygems-bundler                | 1.4.5        |
| bundler                         | 2.2.19       |
| rake                            | 13.0.6       |
| CFPropertyList                  | 3.0.3        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.1.1        |
| aws-partitions                  | 1.484.0      |
| aws-sigv4                       | 1.2.4        |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.119.0      |
| aws-sdk-kms                     | 1.46.0       |
| aws-sdk-s3                      | 1.98.0       |
| babosa                          | 1.0.4        |
| claide                          | 1.0.3        |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.2        |
| excon                           | 0.85.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| multipart-post                  | 2.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.6.0        |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.1.0        |
| fastimage                       | 2.2.4        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.2.3        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| signet                          | 0.15.0       |
| googleauth                      | 0.17.0       |
| httpclient                      | 2.8.3        |
| mini_mime                       | 1.1.0        |
| trailblazer-option              | 0.1.1        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| rexml                           | 3.2.5        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-androidpublisher_v3 | 0.10.0       |
| google-apis-playcustomapp_v1    | 0.5.0        |
| google-apis-iamcredentials_v1   | 0.6.0        |
| google-apis-storage_v1          | 0.6.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.34.1       |
| json                            | 2.5.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.20.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
</details>

*generated on:* **2021-08-18**
</details> </pre>
</details>

**Comment by christruong90** [comment]
Seen this error as well.

**Comment by Krishsidu** [comment]
Facing this error too.

**Comment by Irina369** [comment]
Seeing the same issue as well.

**Comment by Leonwu21** [comment]
Hi @joshdholtz,

Have you had a chance to look into this issue?

Thanks!

**Comment by joshdholtz** [comment]
@Leonwu21 Hello! I have not yet 😣 I've been traveling to speak at a conference but it's on my list!

**Comment by Krishsidu** [comment]
Hi @joshdholtz,

I am part of Leon's team as well. Did you get a chance to look into this item?

Thanks!

**Comment by joshdholtz** [comment]
@Krishsidu Thanks for the ping! Will bump up in my queue 💪
