### ISSUE TITLE
Could not store password in keychain

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1925]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/804308?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @xareelee - Imported from <a href='https://github.com/fastlane/credentials_manager/issues/5'>fastlane/credentials_manager#5</a>
        </td>
      </tr>
    </table>

I use `cert` and `sigh` in **fastlane**, and it works fine on my computer. But now I want to build the fastlane environment on my server (Mac Mini), it ask the password for the account every time when using `cert` and `sigh`.

I try to manually execute the `cert` and `sigh` action under **Terminal**, and it shows the message: **security: SecKeychainAddInternetPassword \<NULL\>: The specified item already exists in the keychain.
Could not store password in keychain**.

```
$ sigh
INFO [2015-04-21 15:06:07.62]: Login into iOS Developer Center
No username or password given. You can set environment variables:
DELIVER_USER, DELIVER_PASSWORD
-------------------------------------------------------------------------------------
The login information you enter will be stored in your Mac OS Keychain
More information about that on GitHub: https://github.com/KrauseFx/CredentialsManager
-------------------------------------------------------------------------------------
Password (for XXXX@XXXXXXX.com): ************
security: SecKeychainAddInternetPassword <NULL>: The specified item already exists in the keychain.
Could not store password in keychain
INFO [2015-04-21 15:06:26.49]: Login successful
INFO [2015-04-21 15:06:27.15]: Fetching all available provisioning profiles...
INFO [2015-04-21 15:06:27.90]: Checking if profile is available. (11 profiles found)
INFO [2015-04-21 15:06:31.62]: Downloading profile...
INFO [2015-04-21 15:06:32.41]: Successfully downloaded provisioning profile
....
```

BTW, the project was pulled from GitHub by Jenkins. The path of the project is `/Users/{XXXX}/.jenkins/jobs/iOS develop branch/workspace`.

I've tried log in *Apple Developer Program* and *iTunes Connect* in a browser and store the keyword in the Keychain. The `cert` and `sigh` still ask the password every time.

I can't figure out why this happened.

**Comment by FrankNine** [comment]
I was connecting my Mac slave to Jenkins server by manually executing the jnlp file downloaded from the server. Yesterday I decided to setup Jenkins slave as a launchd entry then this "stty: stdin isn't a terminal" fastlane error happens to me. Not sure why there is a difference between running Jenkins slave from GUI and from launchd.

In the end, I run "security unlock-keychain" before every fastlane call and it works. You also need to run "security set-keychain-settings" to extend keychain timeout. Or it will lock itself up 5 min after unlock and when the Mac goes to sleep mode.

**Comment by TKBurner** [comment]
Thanks for updating the thread @FrankNine! This seems like a viable workaround for your system setup. However, I'll be sure we note this in the future. Is there anywhere in our docs that you think it'd be useful for us to surface this information?

Thanks!

**Comment by FrankNine** [comment]
I am not really familiar with fastlane development and documentation. I guess since it is credentials related, I should be documented at CredentialsManager. I am still trying to get to the bottom of it. Placing keychain password on Jenkins server is not ideal. Hope we can address it in the right way.

**Comment by TKBurner** [comment]
@FrankNine Thanks for following up. Right now we use the keychain to store credentials. I'm going to convert this to a feature request and close it. The team will have a look soon :+1:
