### ISSUE TITLE
deliver always set latest build_number from testflight

### ISSUE THREAD

**Issue by IlyaNakhaichuk** [fastlane/fastlane#19271]
Hey
fastlane ios deliver always installs the latest version in the testflight. I try to set build_number: priveusly version, but after successfully passing fastlane, looking in the App Store, I see that the latest available version is installed. Is this a bug? Or is there a solution to this?
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

**Comment by Robert3518** [comment]
Provides a way to have increment_build_number be based on the latest build you uploaded to iTC.
Fetches the most recent build number from TestFlight based on the version number. Provides a way to have increment_build_number be based on the latest build you uploaded to iTC.

**Comment by IlyaNakhaichuk** [comment]
@Robert3518 And how can I install not the latest version with testflight, but let’s say the previous one? When I run with the previous version, in the output of fastlane, I see that the version that I set is taken, but the latest is installed in the App Store.
