### ISSUE TITLE
Gym stage fails - "Could not find dotenv-2.7.6 in any of the sources"

### ISSUE THREAD

**Issue by ohthepain** [fastlane/fastlane#19270]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I can't build on my intel MacBook. gym stage reports "Could not find dotenv-2.7.6 in any of the sources" and the build fails.

dotenv is in my Gemfile and the correct version is installed when I do 'bundle install'

Gemfile:
`bash-3.2$ cat Gemfile
source "https://rubygems.org"

gem "dotenv"
gem "fastlane"
gem "pry"
`

##### Command executed
bundle exec fastlane ios deploy

##### Complete output when running fastlane, including the stack trace and command used

<details>

bash-3.2$ bundle exec fastlane ios deploy
[✔] 🚀 
undefined method `username' for #<CredentialsManager::AppfileConfig:0x00007fc0f9d0f1f8 @data={:json_key_file=>"bek-api-upload.json", :package_name=>"com.(redacted)", :team_name=>"Paul Wilkinson", :team_id=>"xxxx", :itc_team_id=>"13820", :itc_team_name=>"Paul Wilkinson"}>
undefined method `username' for #<CredentialsManager::AppfileConfig:0x00007fc0f6423b50 @data={:json_key_file=>"bek-api-upload.json", :package_name=>"com.(redacted)", :team_name=>"Paul Wilkinson", :team_id=>"xxxx", :itc_team_id=>"13820", :itc_team_name=>"Paul Wilkinson"}>
[10:33:09]: ------------------------------
[10:33:09]: --- Step: default_platform ---
[10:33:09]: ------------------------------
[10:33:09]: Driving the lane 'ios deploy' 🚀
undefined method `username' for #<CredentialsManager::AppfileConfig:0x00007fc0f76c15c8 @data={:json_key_file=>"bek-api-upload.json", :package_name=>"com.(redacted)", :team_name=>"Paul Wilkinson", :team_id=>"xxxx", :itc_team_id=>"13820", :itc_team_name=>"Paul Wilkinson"}>
undefined method `username' for #<CredentialsManager::AppfileConfig:0x00007fc0fad17280 @data={:json_key_file=>"bek-api-upload.json", :package_name=>"com.(redacted)", :team_name=>"Paul Wilkinson", :team_id=>"xxxx", :itc_team_id=>"13820", :itc_team_name=>"Paul Wilkinson"}>
[10:33:09]: Clambake100
undefined method `username' for #<CredentialsManager::AppfileConfig:0x00007fc0fad2e3b8 @data={:json_key_file=>"bek-api-upload.json", :package_name=>"com.(redacted)", :team_name=>"Paul Wilkinson", :team_id=>"xxxx", :itc_team_id=>"13820", :itc_team_name=>"Paul Wilkinson"}>
undefined method `username' for #<CredentialsManager::AppfileConfig:0x00007fc0fad3c738 @data={:json_key_file=>"bek-api-upload.json", :package_name=>"com.(redacted)", :team_name=>"Paul Wilkinson", :team_id=>"xxxx", :itc_team_id=>"13820", :itc_team_name=>"Paul Wilkinson"}>
[10:33:09]: ----------------------
[10:33:09]: --- Step: setup_ci ---
[10:33:09]: ----------------------
[10:33:09]: Not running on CI, skipping CI setup
undefined method `username' for #<CredentialsManager::AppfileConfig:0x00007fc0faab7170 @data={:json_key_file=>"bek-api-upload.json", :package_name=>"com.(redacted)", :team_name=>"Paul Wilkinson", :team_id=>"xxxx", :itc_team_id=>"13820", :itc_team_name=>"Paul Wilkinson"}>
undefined method `username' for #<CredentialsManager::AppfileConfig:0x00007fc0f7414550 @data={:json_key_file=>"bek-api-upload.json", :package_name=>"com.(redacted)", :team_name=>"Paul Wilkinson", :team_id=>"xxxx", :itc_team_id=>"13820", :itc_team_name=>"Paul Wilkinson"}>
undefined method `username' for #<CredentialsManager::AppfileConfig:0x00007fc0f74a6180 @data={:json_key_file=>"bek-api-upload.json", :package_name=>"com.(redacted)", :team_name=>"Paul Wilkinson", :team_id=>"xxxx", :itc_team_id=>"13820", :itc_team_name=>"Paul Wilkinson"}>
undefined method `username' for #<CredentialsManager::AppfileConfig:0x00007fc0f9a5ca78 @data={:json_key_file=>"bek-api-upload.json", :package_name=>"com.(redacted)", :team_name=>"Paul Wilkinson", :team_id=>"xxxx", :itc_team_id=>"13820", :itc_team_name=>"Paul Wilkinson"}>
undefined method `username' for #<CredentialsManager::AppfileConfig:0x00007fc0f624aef0 @data={:json_key_file=>"bek-api-upload.json", :package_name=>"com.(redacted)", :team_name=>"Paul Wilkinson", :team_id=>"xxxx", :itc_team_id=>"13820", :itc_team_name=>"Paul Wilkinson"}>
undefined method `username' for #<CredentialsManager::AppfileConfig:0x00007fc0f6203708 @data={:json_key_file=>"bek-api-upload.json", :package_name=>"com.(redacted)", :team_name=>"Paul Wilkinson", :team_id=>"xxxx", :itc_team_id=>"13820", :itc_team_name=>"Paul Wilkinson"}>
undefined method `username' for #<CredentialsManager::AppfileConfig:0x00007fc0f75856f0 @data={:json_key_file=>"bek-api-upload.json", :package_name=>"com.(redacted)", :team_name=>"Paul Wilkinson", :team_id=>"xxxx", :itc_team_id=>"13820", :itc_team_name=>"Paul Wilkinson"}>
undefined method `username' for #<CredentialsManager::AppfileConfig:0x00007fc0fab37208 @data={:json_key_file=>"bek-api-upload.json", :package_name=>"com.(redacted)", :team_name=>"Paul Wilkinson", :team_id=>"xxxx", :itc_team_id=>"13820", :itc_team_name=>"Paul Wilkinson"}>
undefined method `username' for #<CredentialsManager::AppfileConfig:0x00007fc0fab80340 @data={:json_key_file=>"bek-api-upload.json", :package_name=>"com.(redacted)", :team_name=>"Paul Wilkinson", :team_id=>"xxxx", :itc_team_id=>"13820", :itc_team_name=>"Paul Wilkinson"}>
undefined method `username' for #<CredentialsManager::AppfileConfig:0x00007fc0fab781b8 @data={:json_key_file=>"bek-api-upload.json", :package_name=>"com.(redacted)", :team_name=>"Paul Wilkinson", :team_id=>"xxxx", :itc_team_id=>"13820", :itc_team_name=>"Paul Wilkinson"}>
[10:33:10]: -------------------
[10:33:10]: --- Step: match ---
[10:33:10]: -------------------
[10:33:10]: Successfully loaded '/Users/xxxx/projects/Unity/BadNRG/fastlane/Matchfile' 📄

+----------------+----------------------------------------+
|       Detected Values from './fastlane/Matchfile'       |
+----------------+----------------------------------------+
| git_url        | git@gitlab.com:thisco/provisioning.git |
| storage_mode   | git                                    |
| type           | appstore                               |
| app_identifier | ["com.(redacted)"]               |
| username       | (redacted)                      |
+----------------+----------------------------------------+

+--------------------------------+----------------------------------------+
|                        Summary for match 2.191.0                        |
+--------------------------------+----------------------------------------+
| type                           | appstore                               |
| readonly                       | false                                  |
| generate_apple_certs           | true                                   |
| skip_provisioning_profiles     | false                                  |
| app_identifier                 | ["com.(redacted)"]               |
| username                       | (redacted)                      |
| storage_mode                   | git                                    |
| git_url                        | git@gitlab.com:thisco/provisioning.git |
| git_branch                     | master                                 |
| shallow_clone                  | false                                  |
| clone_branch_directly          | false                                  |
| keychain_name                  | login.keychain                         |
| force                          | false                                  |
| force_for_new_devices          | false                                  |
| skip_confirmation              | false                                  |
| skip_docs                      | false                                  |
| platform                       | ios                                    |
| derive_catalyst_app_identifier | false                                  |
| fail_on_name_taken             | false                                  |
| skip_certificate_matching      | false                                  |
| skip_set_partition_list        | false                                  |
| verbose                        | false                                  |
+--------------------------------+----------------------------------------+

[10:33:10]: Cloning remote git repo...
[10:33:10]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[10:33:12]: Checking out branch master...
[10:33:12]: 🔓  Successfully decrypted certificates repo
[10:33:12]: Verifying that the certificate and profile are still valid on the Dev Portal...
Available session is not valid any more. Continuing with normal login.
[10:33:19]: Installing certificate...

+-------------------+-------------------------------------------------+
|                        Installed Certificate                        |
+-------------------+-------------------------------------------------+
| User ID           | xxxx                                      |
| Common Name       | Apple Distribution: xxxx(xxxx) |
| Organisation Unit | xxxx                                      |
| Organisation      | xxxx                                 |
| Country           | US                                              |
| Start Datetime    | 2021-06-04 06:16:32 UTC                         |
| End Datetime      | 2022-06-04 06:16:31 UTC                         |
+-------------------+-------------------------------------------------+

[10:33:20]: Installing provisioning profile...

+---------------------+-------------------------------------+-------------------------------------+
|                                 Installed Provisioning Profile                                  |
+---------------------+-------------------------------------+-------------------------------------+
| Parameter           | Environment Variable                | Value                               |
+---------------------+-------------------------------------+-------------------------------------+
| App Identifier      |                                     | com.(redacted)                |
| Type                |                                     | appstore                            |
| Platform            |                                     | ios                                 |
| Profile UUID        | sigh_com.(redacted)_appstore  | e4650135-2746-4e04-91fe-5596f5de95  |
|                     |                                     | 95                                  |
| Profile Name        | sigh_com.(redacted)_appstore  | match AppStore                      |
|                     | _profile-name                       | com.(redacted)                |
| Profile Path        | sigh_com.(redacted)_appstore  | /Users/xxxx/Library/Mobil  |
|                     | _profile-path                       | eDevice/Provisioning                |
|                     |                                     | Profiles/e4650135-2746-4e04-91fe-5  |
|                     |                                     | 596f5de9595.mobileprovision         |
| Development Team ID | sigh_com.(redacted)_appstore  | xxxx                          |
|                     | _team-id                            |                                     |
+---------------------+-------------------------------------+-------------------------------------+

[10:33:20]: All required keys, certificates and provisioning profiles are installed 🙌
[10:33:20]: Setting Provisioning Profile type to 'app-store'
undefined method `username' for #<CredentialsManager::AppfileConfig:0x00007fc0f76c40c0 @data={:json_key_file=>"bek-api-upload.json", :package_name=>"com.(redacted)", :team_name=>"Paul Wilkinson", :team_id=>"xxxx", :itc_team_id=>"13820", :itc_team_name=>"Paul Wilkinson"}>
undefined method `username' for #<CredentialsManager::AppfileConfig:0x00007fc0f6479668 @data={:json_key_file=>"bek-api-upload.json", :package_name=>"com.(redacted)", :team_name=>"Paul Wilkinson", :team_id=>"xxxx", :itc_team_id=>"13820", :itc_team_name=>"Paul Wilkinson"}>
undefined method `username' for #<CredentialsManager::AppfileConfig:0x00007fc0fb02dfc8 @data={:json_key_file=>"bek-api-upload.json", :package_name=>"com.(redacted)", :team_name=>"Paul Wilkinson", :team_id=>"xxxx", :itc_team_id=>"13820", :itc_team_name=>"Paul Wilkinson"}>
undefined method `username' for #<CredentialsManager::AppfileConfig:0x00007fc0f9d3af60 @data={:json_key_file=>"bek-api-upload.json", :package_name=>"com.(redacted)", :team_name=>"Paul Wilkinson", :team_id=>"xxxx", :itc_team_id=>"13820", :itc_team_name=>"Paul Wilkinson"}>
undefined method `username' for #<CredentialsManager::AppfileConfig:0x00007fc0f9d31cd0 @data={:json_key_file=>"bek-api-upload.json", :package_name=>"com.(redacted)", :team_name=>"Paul Wilkinson", :team_id=>"xxxx", :itc_team_id=>"13820", :itc_team_name=>"Paul Wilkinson"}>
undefined method `username' for #<CredentialsManager::AppfileConfig:0x00007fc0f64aa308 @data={:json_key_file=>"bek-api-upload.json", :package_name=>"com.(redacted)", :team_name=>"Paul Wilkinson", :team_id=>"xxxx", :itc_team_id=>"13820", :itc_team_name=>"Paul Wilkinson"}>
undefined method `username' for #<CredentialsManager::AppfileConfig:0x00007fc0f9d439a8 @data={:json_key_file=>"bek-api-upload.json", :package_name=>"com.(redacted)", :team_name=>"Paul Wilkinson", :team_id=>"xxxx", :itc_team_id=>"13820", :itc_team_name=>"Paul Wilkinson"}>
undefined method `username' for #<CredentialsManager::AppfileConfig:0x00007fc0f6489798 @data={:json_key_file=>"bek-api-upload.json", :package_name=>"com.(redacted)", :team_name=>"Paul Wilkinson", :team_id=>"xxxx", :itc_team_id=>"13820", :itc_team_name=>"Paul Wilkinson"}>
undefined method `username' for #<CredentialsManager::AppfileConfig:0x00007fc0f64c3100 @data={:json_key_file=>"bek-api-upload.json", :package_name=>"com.(redacted)", :team_name=>"Paul Wilkinson", :team_id=>"xxxx", :itc_team_id=>"13820", :itc_team_name=>"Paul Wilkinson"}>
undefined method `username' for #<CredentialsManager::AppfileConfig:0x00007fc0f9d489d0 @data={:json_key_file=>"bek-api-upload.json", :package_name=>"com.(redacted)", :team_name=>"Paul Wilkinson", :team_id=>"xxxx", :itc_team_id=>"13820", :itc_team_name=>"Paul Wilkinson"}>
[10:33:20]: -------------------------------
[10:33:20]: --- Step: sync_code_signing ---
[10:33:20]: -------------------------------
[10:33:20]: Successfully loaded '/Users/xxxx/projects/Unity/BadNRG/fastlane/Matchfile' 📄

+----------------+----------------------------------------+
|       Detected Values from './fastlane/Matchfile'       |
+----------------+----------------------------------------+
| git_url        | git@gitlab.com:thisco/provisioning.git |
| storage_mode   | git                                    |
| type           | appstore                               |
| app_identifier | ["com.(redacted)"]               |
| username       | (redacted)                      |
+----------------+----------------------------------------+

+--------------------------------+----------------------------------------+
|                        Summary for match 2.191.0                        |
+--------------------------------+----------------------------------------+
| type                           | appstore                               |
| app_identifier                 | ["com.(redacted)"]               |
| readonly                       | true                                   |
| generate_apple_certs           | true                                   |
| skip_provisioning_profiles     | false                                  |
| username                       | (redacted)                      |
| storage_mode                   | git                                    |
| git_url                        | git@gitlab.com:thisco/provisioning.git |
| git_branch                     | master                                 |
| shallow_clone                  | false                                  |
| clone_branch_directly          | false                                  |
| keychain_name                  | login.keychain                         |
| force                          | false                                  |
| force_for_new_devices          | false                                  |
| skip_confirmation              | false                                  |
| skip_docs                      | false                                  |
| platform                       | ios                                    |
| derive_catalyst_app_identifier | false                                  |
| fail_on_name_taken             | false                                  |
| skip_certificate_matching      | false                                  |
| skip_set_partition_list        | false                                  |
| verbose                        | false                                  |
+--------------------------------+----------------------------------------+

[10:33:20]: Cloning remote git repo...
[10:33:20]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[10:33:22]: Checking out branch master...
[10:33:22]: 🔓  Successfully decrypted certificates repo
[10:33:22]: Installing certificate...

+-------------------+-------------------------------------------------+
|                        Installed Certificate                        |
+-------------------+-------------------------------------------------+
| User ID           | xxxx                                      |
| Common Name       | Apple Distribution: xxxx(xxxx) |
| Organisation Unit | xxxx                                      |
| Organisation      | xxxx                                 |
| Country           | US                                              |
| Start Datetime    | 2021-06-04 06:16:32 UTC                         |
| End Datetime      | 2022-06-04 06:16:31 UTC                         |
+-------------------+-------------------------------------------------+

[10:33:23]: Installing provisioning profile...

+---------------------+-------------------------------------+-------------------------------------+
|                                 Installed Provisioning Profile                                  |
+---------------------+-------------------------------------+-------------------------------------+
| Parameter           | Environment Variable                | Value                               |
+---------------------+-------------------------------------+-------------------------------------+
| App Identifier      |                                     | com.(redacted)                |
| Type                |                                     | appstore                            |
| Platform            |                                     | ios                                 |
| Profile UUID        | sigh_com.(redacted)_appstore  | e4650135-2746-4e04-91fe-5596f5de95  |
|                     |                                     | 95                                  |
| Profile Name        | sigh_com.(redacted)_appstore  | match AppStore                      |
|                     | _profile-name                       | com.(redacted)                |
| Profile Path        | sigh_com.(redacted)_appstore  | /Users/xxxx/Library/Mobil  |
|                     | _profile-path                       | eDevice/Provisioning                |
|                     |                                     | Profiles/e4650135-2746-4e04-91fe-5  |
|                     |                                     | 596f5de9595.mobileprovision         |
| Development Team ID | sigh_com.(redacted)_appstore  | xxxx                          |
|                     | _team-id                            |                                     |
+---------------------+-------------------------------------+-------------------------------------+

[10:33:23]: All required keys, certificates and provisioning profiles are installed 🙌
[10:33:23]: Setting Provisioning Profile type to 'app-store'
[10:33:23]: -----------------
[10:33:23]: --- Step: gym ---
[10:33:23]: -----------------
[10:33:23]: Resolving Swift Package Manager dependencies...
[10:33:23]: $ xcodebuild -resolvePackageDependencies -scheme Unity-iPhone -project ./Build/iPhone/Unity-iPhone.xcodeproj
[10:33:24]: ▸ Command line invocation:
[10:33:24]: ▸     /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -scheme Unity-iPhone -project ./Build/iPhone/Unity-iPhone.xcodeproj
[10:33:24]: ▸ User defaults from command line:
[10:33:24]: ▸     IDEPackageSupportUseBuiltinSCM = YES
[10:33:25]: ▸ resolved source packages: 
[10:33:25]: $ xcodebuild -showBuildSettings -scheme Unity-iPhone -project ./Build/iPhone/Unity-iPhone.xcodeproj
[10:33:28]: Detected provisioning profile mapping: {:"com.(redacted)"=>"match AppStore com.(redacted)"}

+---------------------------------------------------------+---------------------------------------------------------+
|                                              Summary for gym 2.191.0                                              |
+---------------------------------------------------------+---------------------------------------------------------+
| scheme                                                  | Unity-iPhone                                            |
| project                                                 | ./Build/iPhone/Unity-iPhone.xcodeproj                   |
| include_bitcode                                         | true                                                    |
| export_method                                           | app-store                                               |
| export_options.provisioningProfiles.com.thisco.badener  | match AppStore com.(redacted)                     |
| gy                                                      |                                                         |
| clean                                                   | false                                                   |
| output_directory                                        | .                                                       |
| output_name                                             | (redacted)                                           |
| silent                                                  | false                                                   |
| skip_package_ipa                                        | false                                                   |
| skip_package_pkg                                        | false                                                   |
| build_path                                              | /Users/xxxx/Library/Developer/Xcode/Archives/  |
|                                                         | 2021-08-23                                              |
| result_bundle                                           | false                                                   |
| buildlog_path                                           | ~/Library/Logs/gym                                      |
| destination                                             | generic/platform=iOS                                    |
| skip_profile_detection                                  | false                                                   |
| skip_package_dependencies_resolution                    | false                                                   |
| disable_package_automatic_updates                       | false                                                   |
| use_system_scm                                          | false                                                   |
| xcode_path                                              | /Applications/Xcode.app                                 |
+---------------------------------------------------------+---------------------------------------------------------+

[10:33:28]: $ set -o pipefail && xcodebuild -scheme Unity-iPhone -project ./Build/iPhone/Unity-iPhone.xcodeproj -destination 'generic/platform=iOS' -archivePath /Users/xxxx/Library/Developer/Xcode/Archives/2021-08-23/(redacted)\ 2021-08-23\ 10.33.28.xcarchive archive | tee /Users/xxxx/Library/Logs/gym/(redacted)-Unity-iPhone.log | xcpretty
[10:33:28]: ▸ Could not find dotenv-2.7.6 in any of the sources
[10:33:28]: ▸ Run `bundle install` to install missing gems.
[10:34:35]: ▸ ** ARCHIVE FAILED **
[10:34:35]: ▸ The following build commands failed:
[10:34:35]: ▸ 	CompileC /Users/xxxx/Library/Developer/Xcode/DerivedData/Unity-iPhone-hkcqwwhwhwzutkfescuxnozrdlgk/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/UnityFramework.build/Objects-normal/arm64/System1.o /Users/xxxx/projects/Unity/BadNRG/Build/iPhone/Classes/Native/System1.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler
[10:34:35]: ▸ (1 failure)
Could not find dotenv-2.7.6 in any of the sources
Run `bundle install` to install missing gems.
** ARCHIVE FAILED **

The following build commands failed:
	CompileC /Users/xxxx/Library/Developer/Xcode/DerivedData/Unity-iPhone-hkcqwwhwhwzutkfescuxnozrdlgk/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/UnityFramework.build/Objects-normal/arm64/System1.o /Users/xxxx/projects/Unity/BadNRG/Build/iPhone/Classes/Native/System1.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
[10:34:35]: Exit status: 7

+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.191.0                 |
| export_method | app-store               |
| sdk           | iPhoneOS14.5.sdk        |
+---------------+-------------------------+

[10:34:35]: ▸ Command line invocation:
[10:34:35]: ▸     
[10:34:35]: 
[10:34:35]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[10:34:35]: 📋  For the complete and more detailed error log, check the full log at:
[10:34:35]: 📋  /Users/xxxx/Library/Logs/gym/(redacted)-Unity-iPhone.log
[10:34:35]: 
[10:34:35]: Looks like fastlane ran into a build/archive error with your project
[10:34:35]: It's hard to tell what's causing the error, so we wrote some guides on how
[10:34:35]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[10:34:35]: Before submitting an issue on GitHub, please follow the guide above and make
[10:34:35]: sure your project is set up correctly.
[10:34:35]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
[10:34:35]: the full commands printed out in yellow in the above log.
[10:34:35]: Make sure to inspect the output above, as usually you'll find more error information there
[10:34:35]: 
+------------------------------------+-------------------------------------------+
|                                  Lane Context                                  |
+------------------------------------+-------------------------------------------+
| DEFAULT_PLATFORM                   | ios                                       |
| PLATFORM_NAME                      | ios                                       |
| LANE_NAME                          | ios deploy                                |
| SIGH_PROFILE_TYPE                  | app-store                                 |
| MATCH_PROVISIONING_PROFILE_MAPPING | {"com.(redacted)"=>"match AppStore  |
|                                    | com.(redacted)"}                    |
+------------------------------------+-------------------------------------------+
[10:34:35]: Error building the application - see the log above

+------+-------------------+-------------+
|            fastlane summary            |
+------+-------------------+-------------+
| Step | Action            | Time (in s) |
+------+-------------------+-------------+
| 1    | default_platform  | 0           |
| 2    | setup_ci          | 0           |
| 3    | match             | 10          |
| 4    | sync_code_signing | 2           |
| 💥   | gym               | 72          |
+------+-------------------+-------------+

[10:34:35]: fastlane finished with errors

[!] Error building the application - see the log above
bash-3.2$ 

</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.5.2                                      |
| Ruby                        | 3.0.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.30.1 (Apple Git-130)          |
| Installation Source         | ~/.gem/ruby/2.6.0/bin/fastlane              |
| Host                        | macOS 11.5.2 (20G95)                        |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/3.0.2/lib            |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.5.1                                      |
| Swift Version               | 5.4.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :android do
	desc "Runs all the tests"
	lane :test do
		gradle(task: "test")
	end

	desc "Submit a new Beta Build to Crashlytics Beta"
	lane :beta do
		gradle(task: "clean assembleRelease")
		crashlytics

	# sh "your_script.sh"
	# You can also use other beta testing services here
	end

	desc "Deploy a new version to the Google Play"
	lane :deploy do
		gradle(task: "clean assembleRelease")
		upload_to_play_store
	end
end

lane :beta do
#	infoPlistPath = "/Users/xxxme/projects/Unity/xxxx/Build/iPhone/Info.plist"
#	version = get_version_number()
#	buildNumber = get_info_plist_value(path: infoPlistPath, key: "CFBundleVersion")
	#increment_version_number(version_number: version)
	#increment_version_number()
	build_app(scheme: "Unity-iPhone",
		project: "./Build/iPhone/Unity-iPhone.xcodeproj",
		include_bitcode: true)
	upload_to_testflight
	slack(message: "Successfully distributed a new beta build")
end

platform :ios do

	before_all do
		desc "for keychain unlock"
		keychain_entry_builder = CredentialsManager::AccountManager.new(user: "email")
		password_builder = keychain_entry_builder.password
		ENV["USER_PASS"] = "#{password_builder}"

		desc "for pilot(TestFlight)"
		keychain_entry_devid = CredentialsManager::AccountManager.new(user: "email")
		password_devid = keychain_entry_devid.password
		puts "#{password_devid}"
	end

	desc "Get certificates - this is done by build machine"
	lane :certificates do
		#update_fastlane
		sync_code_signing(
		  type: "development",
		  app_identifier: 'cxxxx',
		  force_for_new_devices: true,
		  readonly: true
		)

		sync_code_signing(
		  type: "appstore",
		  app_identifier: 'cxxxx',
		  readonly: true
		)
	end

	desc "Generate new certificates"
	lane :generate_new_certificates do
		#update_fastlane
		sync_code_signing(
			type: "development",
			app_identifier: 'cxxxx',
			force_for_new_devices: true,
			readonly: false
		)

		sync_code_signing(
			type: "appstore",
			app_identifier: 'cxxxx',
			force_for_new_devices: true,
			readonly: false
		)
	end

	lane :deploy do
		#update_fastlane

		# Setup the keychain and match to work with CI
		setup_ci

		# Download certs (optional)
		match
		#match(type: "appstore")
		#match(type: "development")

		sync_code_signing(
			type: "appstore",
			app_identifier: 'cxxxx',
			readonly: true
		)

		gym(scheme: "Unity-iPhone",
			project: "./Build/iPhone/Unity-iPhone.xcodeproj",
			include_bitcode: true)

		app_store_connect_api_key(
			key_id: "LJH8X793FT",
			issuer_id: "69a6de6e-4bd6-47e3-e053-5b8c7c11a4d1",
			key_filepath: "AuthKey_LJH8X793FT.p8"
		)

		upload_to_app_store(
			force: true,
			run_precheck_before_submit: false,
			submit_for_review: false
		)
	end

	lane :bump_version do
		sh "../get_build_number.sh"
		#infoPlistPath = "/Users/xxxme/projects/Unity/xxxx/Build/iPhone/Info.plist"
        #version = get_version_number(xcodeproj: "./Build/iPhone/Unity-iPhone.xcodeproj")
		#buildNumber = get_info_plist_value(path: infoPlistPath, key: "CFBundleVersion")
    	#increment_version_number(version_number: version)
    	#increment_version_number()
		increment_build_number(build_number: ENV["BUILD_NUMBER"])
	end

	TEMP_KEYCHAIN = "fastlane_tmp_keychain"

	lane :remove_temp_keychain do |options|
		begin
			name = options[:name].nil? ? TEMP_KEYCHAIN : options[:name]
			delete_keychain(
				name: name
			) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
		rescue => ex
			puts(ex)
		end
	end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("bek-api-upload.json") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("cxxxx")
team_name "me"
team_id "teamid"
itc_team_id "13820"
itc_team_name "me"
username("email")
slack_url("https://hooks.slack.com/services/TF9FBiDv")

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.191.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| bundler                         | 2.2.24       |
| tsort                           | 0.1.0        |
| uri                             | 0.10.1       |
| pathname                        | 0.1.0        |
| rake                            | 13.0.6       |
| CFPropertyList                  | 3.0.3        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.1.1        |
| aws-partitions                  | 1.489.0      |
| aws-sigv4                       | 1.2.4        |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.119.1      |
| aws-sdk-kms                     | 1.46.0       |
| aws-sdk-s3                      | 1.99.0       |
| babosa                          | 1.0.4        |
| claide                          | 1.0.3        |
| coderay                         | 1.1.3        |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.2        |
| excon                           | 0.85.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| multipart-post                  | 2.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.7.0        |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.1.0        |
| fastimage                       | 2.2.5        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.2.3        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| signet                          | 0.15.0       |
| googleauth                      | 0.17.0       |
| httpclient                      | 2.8.3        |
| mini_mime                       | 1.1.0        |
| trailblazer-option              | 0.1.1        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| rexml                           | 3.2.5        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-androidpublisher_v3 | 0.10.0       |
| google-apis-playcustomapp_v1    | 0.5.0        |
| google-apis-iamcredentials_v1   | 0.6.0        |
| google-apis-storage_v1          | 0.6.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.34.1       |
| json                            | 2.5.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| method_source                   | 1.0.0        |
| pry                             | 0.14.1       |
</details>

*generated on:* **2021-08-23**
</details>

**Comment by ohthepain** [comment]
I can repro with just 

```
	lane :test do
			gym(scheme: "Unity-iPhone",
    			project: "./Build/iPhone/Unity-iPhone.xcodeproj",
    			include_bitcode: true)
	end

```

and 

`bundle exec fastlane ios test`

**Comment by lucgrabowski** [comment]
If you take a look at Stack in Fastlane Environment, you'll notice 2 different versions of ruby (2.6.0 and 3.0.2) in `Installation Source` and `Installation Source`.
I suggest installing ruby version manager, e.g. rbenv 
https://github.com/rbenv/rbenv#installation
installing ruby version you'd like to use, setting global version
https://github.com/rbenv/rbenv#rbenv-global
and installing bundler. I think that it should fix your issues.
