### ISSUE TITLE
Can't initialise

### ISSUE THREAD

**Issue by ibigbug** [fastlane/fastlane#19275]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Fastlane match is failing with unknown error

##### Command executed
```
fastlane match adhoc
```

##### Complete output when running fastlane, including the stack trace and command used

```
[08:23:47]: Cloning remote git repo...
[08:23:47]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[08:23:50]: Checking out branch master...
[08:23:50]: 🔓  Successfully decrypted certificates repo
[08:23:50]: Verifying that the certificate and profile are still valid on the Dev Portal...
[08:23:52]: Couldn't find a valid code signing identity for distribution... creating one for you now

+-------------------------+----------------------------------------------------+
|                           Summary for cert 2.191.0                           |
+-------------------------+----------------------------------------------------+
| platform                | ios                                                |
| development             | false                                              |
| generate_apple_certs    | true                                               |
| force                   | true                                               |
| username                | ***                                     |
| team_id                 | ***                                         |
| keychain_path           | /Users/yuweiba/Library/Keychains/login.keychain-db |
| skip_set_partition_list | false                                              |
+-------------------------+----------------------------------------------------+

[08:23:52]: Starting login with user '***'
[08:23:53]: Successfully logged in

Looking for related GitHub issues on fastlane/fastlane...

➡️  Specify IPA path as a parameter to deliver beta
    https://github.com/fastlane/fastlane/issues/244 [closed] 2 💬
    22 Sep 2016

➡️  commit_version_bump error in-spite of expected and actual changes being same
    https://github.com/fastlane/fastlane/issues/248 [closed] 2 💬
    22 Sep 2016

➡️  Sigh: Lane specific `team_id` and `app_identifier` not used
    https://github.com/fastlane/fastlane/issues/256 [closed] 23 💬
    22 Sep 2016

and 18353 more at: https://github.com/fastlane/fastlane/search?q=809%3A%20unexpected%20token%20at%20%27%3CHTML%3E%0A%3CHEAD%3E%0A%3CTITLE%3EError%3C%2FTITLE%3E%0A%3C%2FHEAD%3E%0A%0A%3CBODY%20BGCOLOR%3D%22white%22%20FGCOLOR%3D%22black%22%3E%0A%3CH1%3EError%3C%2FH1%3E%0A%3CHR%3E%0A%0A%3CFONT%20FACE%3D%22Helvetica%2CArial%22%3E%3CB%3E%0ADescription%3A%20Could%20not%20process%20this%20request.%0A%3C%2FB%3E%3C%2FFONT%3E%0A%3CHR%3E%0A%3C%2FBODY%3E%0A%27&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/opt/homebrew/Cellar/ruby/3.0.2/lib/ruby/3.0.0/json/common.rb:216:in `parse': \e[31m[!] 809: unexpected token at '<HTML> (JSON::ParserError)
<HEAD>
<TITLE>Error</TITLE>
</HEAD>

<BODY BGCOLOR="white" FGCOLOR="black">
<H1>Error</H1>
<HR>

<FONT FACE="Helvetica,Arial"><B>
Description: Could not process this request.
</B></FONT>
<HR>
</BODY>
'\e[0m
        from /opt/homebrew/Cellar/ruby/3.0.2/lib/ruby/3.0.0/json/common.rb:216:in `parse'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/spaceship/lib/spaceship/connect_api/api_client.rb:211:in `handle_error'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/spaceship/lib/spaceship/client.rb:902:in `block in send_request'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/spaceship/lib/spaceship/client.rb:657:in `with_retry'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/spaceship/lib/spaceship/client.rb:898:in `send_request'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/spaceship/lib/spaceship/client.rb:742:in `request'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/spaceship/lib/spaceship/connect_api/provisioning/client.rb:67:in `proxy_post'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/spaceship/lib/spaceship/connect_api/provisioning/client.rb:37:in `post'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/spaceship/lib/spaceship/connect_api/provisioning/provisioning.rb:154:in `post_certificate'
        from /opt/homebrew/Cellar/ruby/3.0.2/lib/ruby/3.0.0/forwardable.rb:238:in `post_certificate'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/spaceship/lib/spaceship/connect_api/models/certificate.rb:90:in `create'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/cert/lib/cert/runner.rb:191:in `create_certificate'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/cert/lib/cert/runner.rb:54:in `run'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/cert/lib/cert/runner.rb:13:in `launch'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/match/lib/match/generator.rb:42:in `generate_certificate'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/match/lib/match/runner.rb:168:in `fetch_certificate'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/match/lib/match/runner.rb:96:in `run'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/match/lib/match/commands_generator.rb:69:in `block (3 levels) in run'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/match/lib/match/commands_generator.rb:188:in `run'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/match/lib/match/commands_generator.rb:26:in `start'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/bin/fastlane:23:in `<top (required)>'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/bin/fastlane:23:in `load'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/bin/fastlane:23:in `<main>'
/opt/homebrew/Cellar/ruby/3.0.2/lib/ruby/3.0.0/json/common.rb:216:in `parse': 809: unexpected token at '<HTML> (JSON::ParserError)
<HEAD>
<TITLE>Error</TITLE>
</HEAD>

<BODY BGCOLOR="white" FGCOLOR="black">
<H1>Error</H1>
<HR>

<FONT FACE="Helvetica,Arial"><B>
Description: Could not process this request.
</B></FONT>
<HR>
</BODY>
'
        from /opt/homebrew/Cellar/ruby/3.0.2/lib/ruby/3.0.0/json/common.rb:216:in `parse'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/spaceship/lib/spaceship/connect_api/api_client.rb:211:in `handle_error'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/spaceship/lib/spaceship/client.rb:902:in `block in send_request'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/spaceship/lib/spaceship/client.rb:657:in `with_retry'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/spaceship/lib/spaceship/client.rb:898:in `send_request'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/spaceship/lib/spaceship/client.rb:742:in `request'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/spaceship/lib/spaceship/connect_api/provisioning/client.rb:67:in `proxy_post'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/spaceship/lib/spaceship/connect_api/provisioning/client.rb:37:in `post'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/spaceship/lib/spaceship/connect_api/provisioning/provisioning.rb:154:in `post_certificate'
        from /opt/homebrew/Cellar/ruby/3.0.2/lib/ruby/3.0.0/forwardable.rb:238:in `post_certificate'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/spaceship/lib/spaceship/connect_api/models/certificate.rb:90:in `create'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/cert/lib/cert/runner.rb:191:in `create_certificate'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/cert/lib/cert/runner.rb:54:in `run'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/cert/lib/cert/runner.rb:13:in `launch'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/match/lib/match/generator.rb:42:in `generate_certificate'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/match/lib/match/runner.rb:168:in `fetch_certificate'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/match/lib/match/runner.rb:96:in `run'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/match/lib/match/commands_generator.rb:69:in `block (3 levels) in run'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/match/lib/match/commands_generator.rb:188:in `run'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/match/lib/match/commands_generator.rb:26:in `start'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/bin/fastlane:23:in `<top (required)>'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/bin/fastlane:23:in `load'
        from /opt/homebrew/Cellar/fastlane/2.191.0/libexec/bin/fastlane:23:in `<main>'
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 11.5.2                                                     |
| Ruby                        | 3.0.2                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.30.1 (Apple Git-130)                         |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.191.0/libexec/bin/fastlane |
| Host                        | macOS 11.5.2 (20G95)                                       |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.0.2/lib                        |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                                |
| Is contained                | false                                                      |
| Is homebrew                 | true                                                       |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
| Xcode Version               | 12.5.1                                                     |
| Swift Version               | 5.4.2                                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "adhoc")
    build_app(workspace: "Clash.xcworkspace", scheme: "Clash")
    upload_to_testflight
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("***") # The bundle identifier of your app
apple_id("***") # Your Apple email address

itc_team_id("***") # App Store Connect Team ID
team_id("***") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.191.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| CFPropertyList                  | 3.0.3        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.85.0       |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.1.0        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.5.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.22       |
| simctl                          | 1.6.8        |
| jwt                             | 2.2.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.1        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| signet                          | 0.15.0       |
| googleauth                      | 0.17.0       |
| httpclient                      | 2.8.3        |
| rexml                           | 3.2.5        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-playcustomapp_v1    | 0.5.0        |
| google-apis-androidpublisher_v3 | 0.10.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-storage_v1          | 0.6.0        |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.34.1       |
| emoji_regex                     | 3.2.2        |
| tsort                           | 0.1.0        |
| uri                             | 0.10.1       |
| set                             | 1.0.1        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.0.3        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.21.0       |
| ruby2_keywords                  | 0.0.5        |
| faraday-rack                    | 1.0.0        |
| faraday-patron                  | 1.0.0        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-net_http                | 1.0.1        |
| faraday-httpclient              | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.7.0        |
| fastimage                       | 2.2.5        |
| mini_mime                       | 1.1.1        |
| google-apis-iamcredentials_v1   | 0.7.0        |
| aws-eventstream                 | 1.1.1        |
| aws-sigv4                       | 1.2.4        |
| aws-partitions                  | 1.490.0      |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.119.1      |
| aws-sdk-kms                     | 1.46.0       |
| aws-sdk-s3                      | 1.99.0       |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.0        |
| date                            | 3.1.0        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.0        |
| openssl                         | 2.2.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.2        |
| io-wait                         | 0.1.0        |
| zlib                            | 1.1.0        |
| resolv                          | 0.2.0        |
| securerandom                    | 0.1.0        |
| digest                          | 3.0.0        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.0        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.0        |
| optparse                        | 0.1.0        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.7        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| net-http                        | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| prettyprint                     | 0.1.0        |
| pp                              | 0.1.0        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.0        |
</details>

*generated on:* **2021-08-24**
</details>

**Comment by lucgrabowski** [comment]
Hi @ibigbug Please update to the newest version of fastlane - `2.192` that has just been released. This looks like https://github.com/fastlane/fastlane/issues/19264 that's just been fixed in `2.192`

**Comment by ibigbug** [comment]
thanks @lucgrabowski the latest version has fixed the issues.

but now I'm getting 

```
[18:44:35]: Could not process this request

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 💥   | match            | 21          |
+------+------------------+-------------+

[18:44:35]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Getting `Server error got 500` despite successful testflight publish
    https://github.com/fastlane/fastlane/issues/19217 [open] 8 💬
    5 days ago

➡️  The request could not be completed
    https://github.com/fastlane/fastlane/issues/17700 [closed] 16 💬
    26 Apr 2021

➡️  809: unexpected token at '<HTML>
    https://github.com/fastlane/fastlane/issues/19264 [closed] 36 💬
    4 hours ago

and 157 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09Could%20not%20process%20this%20request&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.

[!] The request could not be completed because:
        Could not process this request
y
``` 

instead.

TBH, I've tried to use fast lane many times, but none of them I was able to successfully setup and use it, not even a simple "Hello World" that I could come up.

**Comment by lucgrabowski** [comment]
Could you send more logs from output? Also, if you changed `beta` lane in your Fastfile, please share how it looks now.
The error that you got looks like the one from the issue that I mentioned before, but it would be good to confirm it. 
cc: @joshdholtz

**Comment by ibigbug** [comment]
thanks for the prompt reply - I didn't change anything, just updated the version.

however after several retries, it finally succeeded.

**Comment by crazymanish** [comment]
> however after several retries, it finally succeeded.
Glad it works now! Apple might fix this issue soon so that we don't even need to retry anymore. Closing this ticket for now!
