### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1927]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/603144?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @tspecht - Imported from <a href='https://github.com/fastlane/scan/issues/98'>fastlane/scan#98</a>
        </td>
      </tr>
    </table>

Hi guys,

I tried to use scan() today to run my tests but unfortunately they are failing with "Segmentation Fault: 11". I had xctool in use previously which is running the same test suite just fine :(

```
Testing failed:
Command failed due to signal: Segmentation fault: 11
** TEST FAILED **


The following build commands failed:
CompileSwift normal x86_64 /Users/myUser/Documents/Code/SomeClass.swift
CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
```

Any ideas on how to fix this?

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (415/400 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:42607 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKr6-002kit-4z
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:20:32 +0200
Date: Sat, 18 Jun 2016 11:19:46 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466273986;
	bh=gEmhqKRmn9eMnE+5jSR5dcXhI0oKBIAHsRdcwsEurVg=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=IqHVoENTRXkwNsuf2WAPeUA6hpe4pnzy09p7NwehcIeihnIYjDXeiwwr2/T7h6uIE
	 Sv0UxpAKwrGQb+nm4VfEX/lKAV+lj3L5ezTYdDf9EfiG9pyLlkatTeIf+LmE+mBojY
	 hC1zFpyed4npbOoIh+2+UFhNbM8zTyETCEEN/8Oc=

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (416/400 (104%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:32558)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1bEKrA-002kjj-BG
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:20:36 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=mVUdw45AKuUMWK7mlrUuEIWC34w=; b=JkvkrNIQoc0TIXwy
	TFbE7q8nUlk3Y1ZOxQPhFB9Og4glPekVd+KHLVHyLPfCWRdBGvup9Sh2GfTQ/6S9
	GHkZMHnnSeraXhGGx+5HLjS4oiJ00uJ/Vdbav7lOty8jBIDgH0AZFLW0zjzyfrfc
	yCzV2uyecdrZHAS0/YhH6cO4Qig=
Received: by filter0915p1mdw1.sendgrid.net with SMTP id filter0915p1mdw1.21973.576590C218
        2016-06-18 18:19:46.645592415 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id URi-Wom5SruESDCkmYGIFg
	for <yann.dupuy@zyapps.com>; Sat, 18 Jun 2016 18:19:46.621 +0000 (UTC)
Date: Sat, 18 Jun 2016 11:19:46 -0700
