### ISSUE TITLE
Unable to find a destination matching the provided destination specifier

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1928]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/1484989?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @jcampbell05 - Imported from <a href='https://github.com/fastlane/scan/issues/97'>fastlane/scan#97</a>
        </td>
      </tr>
    </table>

When running scan, I get.
```bash
[18:11:20]: ▸ xcodebuild: error: Unable to find a destination matching the provided destination specifier:
[18:11:20]: ▸ { platform:iOS Simulator, id:CE6062D2-735F-4350-9804-A5CB0DE9234C }
```

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (414/400 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:21513)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1bEKr1-002khU-IM
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:20:28 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=XklH7WOUP69h+NjXFft+8+UEQZo=; b=Ei+n9fzg/rHzkaXT
	/sxGGU27l1p4CQMO+ZVzsdoRG575JYqMydNWloe7k+SJSECvRTjsIrIZqhmBgiaP
	WUz2OKueHloR55Zi8xYaUxdyupcISoUBVZggqB7lJXTVpQY06udLDXejXNPknSVI
	5uc+gEqUVkpM/lalfGEZxQ7FcAE=
Received: by filter0406p1mdw1.sendgrid.net with SMTP id filter0406p1mdw1.23139.576590BC10
        2016-06-18 18:19:40.095992119 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0001p1iad1.sendgrid.net (SG) with ESMTP id Q6cijdMeS6aa6WPSy2aYYw
	for <yann.dupuy@zyapps.com>; Sat, 18 Jun 2016 18:19:40.143 +0000 (UTC)
Date: Sat, 18 Jun 2016 11:19:40 -0700

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (413/400 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:41980 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKqy-002khE-Ul
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:20:25 +0200
Date: Sat, 18 Jun 2016 11:19:39 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466273979;
	bh=oRfZMbcUg1K1ea8RexG/AWXHmEmNOBq/Pzd0Aem5g1k=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Cx8jvmm91v6D0p8Rgr550sjxMuCQHbDDcWAV2rF9as78MCLGKzFzG2y+us85xEE+s
	 tLRzWWVNsg2Po7gTs4FS/re/7lZQdTowBUOT9MObpCTGt6feT4k2plRSXkaFV+C/Oi
	 DwLf3kCYb1f7FeEXYYiiOtnxReCeZIec3w9owEhs=
