### ISSUE TITLE
Error while uploading .ipa & .apk file to Firebase App Distribution

### ISSUE THREAD

**Issue by iamisathya** [fastlane/fastlane#19284]
<h3>Error while uploading .ipa & .apk file to Firebase App Distribution<h3>

<details>
  <pre> 
[13:14:44]: Successfully exported and compressed dSYM file
[13:14:44]: Successfully exported and signed the ipa file:
[13:14:44]: /Users/insanetechie/FlutterProjects/code_magic_ex/ios/build/Runner/Runner.ipa
[13:14:44]: ---------------------------------------
[13:14:44]: --- Step: firebase_app_distribution ---
[13:14:44]: ---------------------------------------
[13:14:44]: Authenticating with --firebase_cli_token parameter
[13:14:45]: 🔐 Authenticated successfully.
[13:14:48]: ⌛ Uploading the IPA.
+--------------------+--------------------------------------------------+
|                             Lane Context                              |
+--------------------+--------------------------------------------------+
| DEFAULT_PLATFORM   | ios                                              |
| PLATFORM_NAME      | ios                                              |
| LANE_NAME          | ios ios_beta_app                                 |
| IPA_OUTPUT_PATH    | /Users/insanetechie/FlutterProjects/code_magic_  |
|                    | ex/ios/build/Runner/Runner.ipa                   |
| XCODEBUILD_ARCHIVE | ./build/Runner.xcarchive                         |
| DSYM_OUTPUT_PATH   | /Users/insanetechie/FlutterProjects/code_magic_  |
|                    | ex/ios/build/Runner/Runner.app.dSYM.zip          |
+--------------------+--------------------------------------------------+
[13:15:48]: Net::ReadTimeout with #<TCPSocket:(closed)>

+------+---------------------------+-------------+
|                fastlane summary                |
+------+---------------------------+-------------+
| Step | Action                    | Time (in s) |
+------+---------------------------+-------------+
| 1    | default_platform          | 0           |
| 2    | build_app                 | 177         |
| 💥   | firebase_app_distribution | 64          |
+------+---------------------------+-------------+

[13:15:48]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️   Net::ReadTimeout with #<TCPSocket:(closed)
    https://github.com/fastlane/fastlane/issues/15191 [closed] 0 💬
    15 Oct 2019

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
Faraday::TimeoutError: [!] Net::ReadTimeout with #<TCPSocket:(closed)>
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/protocol.rb:217:in `rbuf_fill'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/protocol.rb:191:in `readuntil'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/protocol.rb:201:in `readline'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http/response.rb:40:in `read_status_line'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http/response.rb:29:in `read_new'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:1509:in `block in transport_request'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:1506:in `catch'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:1506:in `transport_request'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:1479:in `request'
  /Library/Ruby/Gems/2.6.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:152:in `block in request_via_request_method'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:920:in `start'
  /Library/Ruby/Gems/2.6.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:146:in `request_via_request_method'
  /Library/Ruby/Gems/2.6.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:131:in `request_with_wrapped_block'
  /Library/Ruby/Gems/2.6.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:122:in `perform_request'
  /Library/Ruby/Gems/2.6.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:66:in `block in call'
  /Library/Ruby/Gems/2.6.0/gems/faraday-1.7.0/lib/faraday/adapter.rb:50:in `connection'
  /Library/Ruby/Gems/2.6.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:64:in `call'
  /Library/Ruby/Gems/2.6.0/gems/faraday-1.7.0/lib/faraday/middleware.rb:18:in `call'
  /Library/Ruby/Gems/2.6.0/gems/faraday_middleware-1.1.0/lib/faraday_middleware/response_middleware.rb:36:in `call'
  /Library/Ruby/Gems/2.6.0/gems/faraday-1.7.0/lib/faraday/rack_builder.rb:154:in `build_response'
  /Library/Ruby/Gems/2.6.0/gems/faraday-1.7.0/lib/faraday/connection.rb:496:in `run_request'
  /Library/Ruby/Gems/2.6.0/gems/faraday-1.7.0/lib/faraday/connection.rb:281:in `post'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-firebase_app_distribution-0.2.9/lib/fastlane/plugin/firebase_app_distribution/client/firebase_app_distribution_api_client.rb:108:in `upload_binary'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-firebase_app_distribution-0.2.9/lib/fastlane/plugin/firebase_app_distribution/client/firebase_app_distribution_api_client.rb:144:in `upload'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-firebase_app_distribution-0.2.9/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb:36:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:27:in `block (2 levels) in parsing_binding'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.192.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.192.0/bin/fastlane:23:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>'
</pre>
</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.1                                                           |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.1 (20C69)                                             |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.3                                                           |
| Swift Version               | 5.3.2                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Submit a new iOS beta build to Firebase App Distribution"
    lane :ios_beta_app do
        build_app(
            scheme: "Runner",
            archive_path: "./build/Runner.xcarchive",
            export_method: "development",
            output_directory: "./build/Runner"
        )
        firebase_app_distribution(
            app: ENV["FIREBASE_APP_ID"],
            firebase_cli_token: ENV["FIREBASE_TOKEN"],
            testers: "****@gmail.com",
            groups: "testers",
            release_notes: "Test release note",            
            ipa_path: "./build/Runner/Runner.ipa"
        )
    end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.192.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.2.9   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.3.0        |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.7.0        |
| terminal-table                            | 1.8.0        |
| plist                                     | 3.6.0        |
| public_suffix                             | 4.0.6        |
| addressable                               | 2.8.0        |
| multipart-post                            | 2.0.0        |
| word_wrap                                 | 1.0.0        |
| optparse                                  | 0.1.1        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| artifactory                               | 3.0.15       |
| babosa                                    | 1.0.4        |
| colored                                   | 1.2          |
| highline                                  | 2.0.3        |
| commander                                 | 4.6.0        |
| excon                                     | 0.85.0       |
| faraday-em_http                           | 1.0.0        |
| faraday-em_synchrony                      | 1.0.0        |
| faraday-excon                             | 1.1.0        |
| faraday-httpclient                        | 1.0.1        |
| faraday-net_http                          | 1.0.1        |
| faraday-net_http_persistent               | 1.2.0        |
| faraday-patron                            | 1.0.0        |
| faraday-rack                              | 1.0.0        |
| ruby2_keywords                            | 0.0.5        |
| faraday                                   | 1.7.0        |
| unf_ext                                   | 0.0.7.7      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| http-cookie                               | 1.0.4        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.1.0        |
| fastimage                                 | 2.2.5        |
| gh_inspector                              | 1.1.3        |
| mini_magick                               | 4.11.0       |
| naturally                                 | 2.2.1        |
| rubyzip                                   | 2.3.2        |
| security                                  | 0.1.3        |
| xcpretty-travis-formatter                 | 1.0.1        |
| dotenv                                    | 2.7.6        |
| bundler                                   | 1.17.2       |
| simctl                                    | 1.6.8        |
| jwt                                       | 2.2.3        |
| uber                                      | 0.1.0        |
| declarative                               | 0.0.20       |
| trailblazer-option                        | 0.1.1        |
| representable                             | 3.1.1        |
| retriable                                 | 3.1.2        |
| mini_mime                                 | 1.1.1        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.1        |
| signet                                    | 0.15.0       |
| googleauth                                | 0.17.0       |
| httpclient                                | 2.8.3        |
| google-apis-core                          | 0.4.1        |
| google-apis-playcustomapp_v1              | 0.5.0        |
| google-apis-androidpublisher_v3           | 0.10.0       |
| google-cloud-env                          | 1.5.0        |
| google-cloud-errors                       | 1.1.0        |
| google-cloud-core                         | 1.6.0        |
| google-apis-iamcredentials_v1             | 0.7.0        |
| google-apis-storage_v1                    | 0.6.0        |
| digest-crc                                | 0.6.4        |
| google-cloud-storage                      | 1.34.1       |
| emoji_regex                               | 3.2.2        |
| jmespath                                  | 1.4.0        |
| aws-partitions                            | 1.490.0      |
| aws-eventstream                           | 1.1.1        |
| aws-sigv4                                 | 1.2.4        |
| aws-sdk-core                              | 3.119.1      |
| aws-sdk-kms                               | 1.46.0       |
| aws-sdk-s3                                | 1.99.0       |
| rexml                                     | 3.2.5        |
| nanaimo                                   | 0.3.0        |
| colored2                                  | 3.1.2        |
| claide                                    | 1.0.3        |
| CFPropertyList                            | 3.0.3        |
| atomos                                    | 0.1.3        |
| xcodeproj                                 | 1.21.0       |
| json                                      | 2.5.1        |
| webrick                                   | 1.7.0        |
| rake                                      | 13.0.6       |
| forwardable                               | 1.2.0        |
| logger                                    | 1.3.0        |
| date                                      | 2.0.0        |
| stringio                                  | 0.0.2        |
| ipaddr                                    | 1.2.2        |
| openssl                                   | 2.1.2        |
| zlib                                      | 1.0.0        |
| mutex_m                                   | 0.1.0        |
| ostruct                                   | 0.1.0        |
| strscan                                   | 1.0.0        |
| io-console                                | 0.4.7        |
| fileutils                                 | 1.1.0        |
| etc                                       | 1.0.1        |
| libxml-ruby                               | 3.1.0        |
| psych                                     | 3.1.0        |
| fastlane-plugin-firebase_app_distribution | 0.2.9        |
</details>

*generated on:* **2021-08-25**
</details>

**Comment by lucgrabowski** [comment]
Are you connected to the Internet or are you behind a firewall that may block the connection?
It seems like a timeout when uploading files with firebase_app_distribution plugin. 
Shouldn't it be moved to https://github.com/fastlane/fastlane-plugin-firebase_app_distribution ?

**Comment by max-ott** [comment]
Yes, please move issues with plugins to the respective repo. We have no "influence" on them as they extend `fastlane`.
