### ISSUE TITLE
Scan hangs running test against target with missing linked files

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1929]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/919166?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @micnguyen - Imported from <a href='https://github.com/fastlane/scan/issues/96'>fastlane/scan#96</a>
        </td>
      </tr>
    </table>

Hi,

I've been using scan for a bit and it's been working great. 

I have recently added a new Target and a new test for that target (that is a duplicate of the 1st test but with the target app changed). When I do CMD+U in Xcode to run, it fails on the test because the new Target didn't have some files linked when you add a file (that checkbox that appears when adding new files to a project). That's all fine - but when I try and run a scan on the project with the missing linked files, it just stalls and doesn't error out on any compilation.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (411/400 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:41382 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKqt-002kfd-AJ
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:20:22 +0200
Date: Sat, 18 Jun 2016 11:19:34 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466273974;
	bh=7iRixYsWJiT/vzpqNeeNYgwWdSCdb801IPcC83nJZr0=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=R7wlkBysh1eOuFTNXlvZahh+KtOZ1oNnCxkQAJh0g7tmm4YMQh12TVASjzPBNhgSC
	 CXjwIuUdRk0fOAV/0XSj1mWbMjLdebxoDTB9IS7TbinK8aO+IuiMDmGsgJCMKq2JgH
	 ezjnBbXo+EKgRgJLXf/4SkuCiQ6hCTZSJ+Q28Ugo=

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (412/400 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:45879 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKqt-002kfz-MV
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:20:24 +0200
Date: Sat, 18 Jun 2016 11:19:34 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466273974;
	bh=/xuP+KhAZzsh4nOzhv90HjROJMxiLeLLLVrGgTIKG/I=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=fv2JAQIsaSfyk7Q9S0dapYUoOPM5yXRxU44jEFFvYZor/kaVIH4XvKX7jtmLHDRJf
	 D0qVqEFyibTQ7pDmyPcbdQmpBOfenTMwvoF1OAxJ3B9ifhFGgVn0fM2RPwt12N0F/e
	 55IW/9AH26wyOaxNpB5VsQUo6IUldkQ9T1Lfz7os=
