### ISSUE TITLE
Fastlane/Spaceship Authentication issue

### ISSUE THREAD

**Issue by christruong90** [fastlane/fastlane#19318]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Job fails when attempting to login to app store connect after making the "fastlane pilot export -a $bundle_id" call. Error that is given is:

`/Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/net/http/response.rb:124:in `error!': \e[31m[!] 403 "Forbidden"\e[0m (Faraday::ConnectionFailed)`

and

`/Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/net/http/response.rb:124:in `error!': 403 "Forbidden" (Net::HTTPServerException)`

It appears to be a problem with spaceship authentication. 

Please look into this when you have a chance @joshdholtz 🙏 

##### Command executed
fastlane pilot export -a $bundle_id

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [14:44:19]: Login to App Store Connect (****)
Available session is not valid any more. Continuing with normal login.

Looking for related GitHub issues on fastlane/fastlane...

Could not access the GitHub API, you may have better luck via the website.
https://github.com/fastlane/fastlane/search?q=403 "Forbidden"&type=Issues&utf8=✓
/Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/net/http/response.rb:124:in `error!': \e[31m[!] 403 "Forbidden"\e[0m (Faraday::ConnectionFailed)
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/net/http/response.rb:133:in `value'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/net/http.rb:982:in `connect'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/net/http.rb:932:in `start'
	from /Users/atomato/.rvm/gems/ruby-2.7.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:146:in `request_via_request_method'
	from /Users/atomato/.rvm/gems/ruby-2.7.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:131:in `request_with_wrapped_block'
	from /Users/atomato/.rvm/gems/ruby-2.7.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:122:in `perform_request'
	from /Users/atomato/.rvm/gems/ruby-2.7.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:66:in `block in call'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/faraday-1.7.1/lib/faraday/adapter.rb:50:in `connection'
	from /Users/atomato/.rvm/gems/ruby-2.7.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:64:in `call'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/stats_middleware.rb:45:in `call'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/helper/rels_middleware.rb:17:in `call'
	from /Users/atomato/.rvm/gems/ruby-2.7.0/gems/faraday-cookie_jar-0.0.7/lib/faraday/cookie_jar.rb:24:in `call'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/faraday_middleware-1.1.0/lib/faraday_middleware/response_middleware.rb:36:in `call'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/faraday_middleware-1.1.0/lib/faraday_middleware/response_middleware.rb:36:in `call'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/faraday-1.7.1/lib/faraday/rack_builder.rb:154:in `build_response'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/faraday-1.7.1/lib/faraday/connection.rb:511:in `run_request'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/faraday-1.7.1/lib/faraday/connection.rb:281:in `post'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/client.rb:899:in `block in send_request'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/client.rb:657:in `with_retry'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/client.rb:898:in `send_request'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/client.rb:742:in `request'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/client.rb:492:in `send_shared_login_request'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/tunes/tunes_client.rb:130:in `send_login_request'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/client.rb:824:in `do_login'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/client.rb:404:in `login'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/client.rb:366:in `login'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/connect_api/client.rb:56:in `login'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/connect_api/spaceship.rb:85:in `login'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/pilot/lib/pilot/manager.rb:36:in `login'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/pilot/lib/pilot/manager.rb:19:in `start'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/pilot/lib/pilot/tester_exporter.rb:10:in `export_testers'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/pilot/lib/pilot/commands_generator.rb:149:in `block (2 levels) in run'
	from /Users/atomato/.rvm/gems/ruby-2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/atomato/.rvm/gems/ruby-2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/atomato/.rvm/gems/ruby-2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	from /Users/atomato/.rvm/gems/ruby-2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/pilot/lib/pilot/commands_generator.rb:167:in `run'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/pilot/lib/pilot/commands_generator.rb:19:in `start'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/bin/fastlane:23:in `<top (required)>'
	from /Users/atomato/.rvm/gems/ruby-2.7.0/bin/fastlane:23:in `load'
	from /Users/atomato/.rvm/gems/ruby-2.7.0/bin/fastlane:23:in `<main>'
	from /Users/atomato/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:22:in `eval'
	from /Users/atomato/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:22:in `<main>'
/Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/net/http/response.rb:124:in `error!': 403 "Forbidden" (Net::HTTPServerException)
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/net/http/response.rb:133:in `value'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/net/http.rb:982:in `connect'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/net/http.rb:932:in `start'
	from /Users/atomato/.rvm/gems/ruby-2.7.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:146:in `request_via_request_method'
	from /Users/atomato/.rvm/gems/ruby-2.7.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:131:in `request_with_wrapped_block'
	from /Users/atomato/.rvm/gems/ruby-2.7.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:122:in `perform_request'
	from /Users/atomato/.rvm/gems/ruby-2.7.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:66:in `block in call'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/faraday-1.7.1/lib/faraday/adapter.rb:50:in `connection'
	from /Users/atomato/.rvm/gems/ruby-2.7.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:64:in `call'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/stats_middleware.rb:45:in `call'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/helper/rels_middleware.rb:17:in `call'
	from /Users/atomato/.rvm/gems/ruby-2.7.0/gems/faraday-cookie_jar-0.0.7/lib/faraday/cookie_jar.rb:24:in `call'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/faraday_middleware-1.1.0/lib/faraday_middleware/response_middleware.rb:36:in `call'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/faraday_middleware-1.1.0/lib/faraday_middleware/response_middleware.rb:36:in `call'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/faraday-1.7.1/lib/faraday/rack_builder.rb:154:in `build_response'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/faraday-1.7.1/lib/faraday/connection.rb:511:in `run_request'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/faraday-1.7.1/lib/faraday/connection.rb:281:in `post'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/client.rb:899:in `block in send_request'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/client.rb:657:in `with_retry'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/client.rb:898:in `send_request'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/client.rb:742:in `request'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/client.rb:492:in `send_shared_login_request'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/tunes/tunes_client.rb:130:in `send_login_request'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/client.rb:824:in `do_login'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/client.rb:404:in `login'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/client.rb:366:in `login'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/connect_api/client.rb:56:in `login'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/connect_api/spaceship.rb:85:in `login'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/pilot/lib/pilot/manager.rb:36:in `login'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/pilot/lib/pilot/manager.rb:19:in `start'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/pilot/lib/pilot/tester_exporter.rb:10:in `export_testers'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/pilot/lib/pilot/commands_generator.rb:149:in `block (2 levels) in run'
	from /Users/atomato/.rvm/gems/ruby-2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/atomato/.rvm/gems/ruby-2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/atomato/.rvm/gems/ruby-2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	from /Users/atomato/.rvm/gems/ruby-2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/pilot/lib/pilot/commands_generator.rb:167:in `run'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/pilot/lib/pilot/commands_generator.rb:19:in `start'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	from /Users/atomato/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.192.0/bin/fastlane:23:in `<top (required)>'
	from /Users/atomato/.rvm/gems/ruby-2.7.0/bin/fastlane:23:in `load'
	from /Users/atomato/.rvm/gems/ruby-2.7.0/bin/fastlane:23:in `<main>'
	from /Users/atomato/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:22:in `eval'
	from /Users/atomato/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:22:in `<main>' </pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.1                                     |
| Ruby                        | 2.7.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.21.1 (Apple Git-122.3)        |
| Installation Source         | ~/.rvm/gems/ruby-2.7.0/bin/fastlane         |
| Host                        | Mac OS X 10.15.1 (19B88)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.7.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.3.1                                      |
| Swift Version               | 5.1.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.193.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| executable-hooks                | 1.6.1        |
| bundler-unload                  | 1.0.2        |
| rubygems-bundler                | 1.4.5        |
| bundler                         | 2.2.26       |
| rake                            | 13.0.6       |
| CFPropertyList                  | 3.0.3        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.1.1        |
| aws-partitions                  | 1.493.0      |
| aws-sigv4                       | 1.2.4        |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.119.1      |
| aws-sdk-kms                     | 1.47.0       |
| aws-sdk-s3                      | 1.100.0      |
| babosa                          | 1.0.4        |
| claide                          | 1.0.3        |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.2        |
| excon                           | 0.85.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| multipart-post                  | 2.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.7.1        |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.1.0        |
| fastimage                       | 2.2.5        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.2.3        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| signet                          | 0.15.0       |
| googleauth                      | 0.17.0       |
| httpclient                      | 2.8.3        |
| mini_mime                       | 1.1.1        |
| trailblazer-option              | 0.1.1        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| rexml                           | 3.2.5        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-androidpublisher_v3 | 0.10.0       |
| google-apis-playcustomapp_v1    | 0.5.0        |
| google-apis-iamcredentials_v1   | 0.7.0        |
| google-apis-storage_v1          | 0.6.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.34.1       |
| json                            | 2.5.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
</pre>
</details>

**Comment by Leonwu21** [comment]
Seeing the same issue here!

**Comment by lucgrabowski** [comment]
Hi, does the user you use have rights to this app and does it have rights manage testers? You should check Role/Apps in Users and Access tab on Appstore Connect.

**Comment by christruong90** [comment]
Hi @lucgrabowski, Thanks for the reply.

Yes, the user we are using has the "App Manager" role and looks to have permissions to manage Testflight testers on appstore connect:

![image](https://user-images.githubusercontent.com/19395006/131713447-b4c92def-b6c1-4e8d-b334-cb0a7d393031.png)

**Comment by lucgrabowski** [comment]
Hi, and have you checked in Users and Access if the user has rights to the app (the one with the bundle identifier that you use in ` fastlane pilot export`?

**Comment by christruong90** [comment]
Hi @joshdholtz, are you able to look into this? Thanks.

**Comment by christruong90** [comment]
Was able to resolve this issue. Thanks for the help @lucgrabowski
