### ISSUE TITLE
Is it possible to run individual test case/test class?

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1931]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/1986672?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @kinwahlai - Imported from <a href='https://github.com/fastlane/scan/issues/90'>fastlane/scan#90</a>
        </td>
      </tr>
    </table>

Is it possible to run individual test case/test class? like -only in xctool

Darren

**Comment by lucianomarisi** [comment]
now that xcodebuild supports the flag `-only-testing:TestBundle/TestSuite/TestCase` for `test`, is it more likely that this feature will be supported by scan in the near future?

**Comment by TKBurner** [comment]
@lucianomarisi Are you interested in implementing this in a PR? I think we'd be really happy to see a PR? I'm marking this open to contribution. Thanks!

**Comment by lucianomarisi** [comment]
@TKBurner unfortunately my ruby skills are not existent (barely know the syntax and have no idea on how unit testing works on ruby), so it's unlikely that I'll be able to contribute

**Comment by TKBurner** [comment]
@lucianomarisi No problem! I'll leave this open in case someone from the community wants to take it on. 👍
