### ISSUE TITLE
There is no route for the path 'apps/xxx/platforms/ios/versions/xxx'

### ISSUE THREAD

**Issue by xwal** [fastlane/fastlane#19313]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I use fastlane spaceship to run some code, there is an error with
```
5: from /Users/user/.gem/ruby/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/tunes/application.rb:146:in `analytics'
4: from /Users/user/.gem/ruby/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/tunes/application.rb:126:in `live_version'
3: from /Users/user/.gem/ruby/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/tunes/app_version.rb:291:in `find'
2: from /Users/user/.gem/ruby/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/tunes/tunes_client.rb:450:in `app_version'
1: from /Users/user/.gem/ruby/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/tunes/tunes_client.rb:459:in `app_version_data'
/Users/user/.gem/ruby/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/client.rb:763:in `parse_response': \e[31m[!] <?xml version="1.0" encoding="UTF-8"?> (Spaceship::UnexpectedResponse)
<String>There is no route for the path 'apps/1436799971/platforms/ios/versions/843780651'.</String>
```

##### Command executed

```ruby
Spaceship::Tunes.login
apps = Spaceship::Tunes::Application.all
apps.each do |app|
          UI.success "Tracking App: #{app.name}"
          puts app.live_version
end
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
<pre>
Traceback (most recent call last):
	50: from /Users/user/.rbenv/versions/2.7.2/bin/bundle:23:in `<main>'
	49: from /Users/user/.rbenv/versions/2.7.2/bin/bundle:23:in `load'
	48: from /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.25/exe/bundle:37:in `<top (required)>'
	47: from /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.25/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
	46: from /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.25/exe/bundle:49:in `block in <top (required)>'
	45: from /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.25/lib/bundler/cli.rb:25:in `start'
	44: from /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.25/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	43: from /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.25/lib/bundler/cli.rb:31:in `dispatch'
	42: from /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.25/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	41: from /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.25/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	40: from /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.25/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	39: from /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.25/lib/bundler/cli.rb:481:in `exec'
	38: from /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.25/lib/bundler/cli/exec.rb:28:in `run'
	37: from /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.25/lib/bundler/cli/exec.rb:63:in `kernel_load'
	36: from /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.25/lib/bundler/cli/exec.rb:63:in `load'
	35: from /Users/user/.gem/ruby/2.7.0/bin/fastlane:23:in `<top (required)>'
	34: from /Users/user/.gem/ruby/2.7.0/bin/fastlane:23:in `load'
	33: from /Users/user/.gem/ruby/2.7.0/gems/fastlane-2.192.0/bin/fastlane:23:in `<top (required)>'
	32: from /Users/user/.gem/ruby/2.7.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	31: from /Users/user/.gem/ruby/2.7.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	30: from /Users/user/.gem/ruby/2.7.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	29: from /Users/user/.gem/ruby/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	28: from /Users/user/.gem/ruby/2.7.0/gems/fastlane-2.192.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	27: from /Users/user/.gem/ruby/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	26: from /Users/user/.gem/ruby/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	25: from /Users/user/.gem/ruby/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	24: from /Users/user/.gem/ruby/2.7.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	23: from /Users/user/.gem/ruby/2.7.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	22: from /Users/user/.gem/ruby/2.7.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	21: from /Users/user/.gem/ruby/2.7.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	20: from /Users/user/.gem/ruby/2.7.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	19: from /Users/user/.gem/ruby/2.7.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	18: from /Users/user/.gem/ruby/2.7.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	17: from Fastfile:479:in `block (2 levels) in parsing_binding'
	16: from /Users/user/.gem/ruby/2.7.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	15: from /Users/user/.gem/ruby/2.7.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	14: from /Users/user/.gem/ruby/2.7.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	13: from /Users/user/.gem/ruby/2.7.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	12: from /Users/user/.gem/ruby/2.7.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	11: from /Users/user/.gem/ruby/2.7.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	10: from /Users/user/.gem/ruby/2.7.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 9: from /Users/user/Workspace/xxx/fastlane/actions/track_app_status.rb:9:in `run'
	 8: from /Users/user/Workspace/xxx/fastlane/actions/track_app_status.rb:28:in `track_team_apps'
	 7: from /Users/user/Workspace/xxx/fastlane/actions/track_app_status.rb:28:in `each'
	 6: from /Users/user/Workspace/xxx/fastlane/actions/track_app_status.rb:30:in `block in track_team_apps'
	 5: from /Users/user/.gem/ruby/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/tunes/application.rb:146:in `analytics'
	 4: from /Users/user/.gem/ruby/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/tunes/application.rb:126:in `live_version'
	 3: from /Users/user/.gem/ruby/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/tunes/app_version.rb:291:in `find'
	 2: from /Users/user/.gem/ruby/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/tunes/tunes_client.rb:450:in `app_version'
	 1: from /Users/user/.gem/ruby/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/tunes/tunes_client.rb:459:in `app_version_data'
/Users/user/.gem/ruby/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/client.rb:763:in `parse_response': \e[31m[!] <?xml version="1.0" encoding="UTF-8"?> (Spaceship::UnexpectedResponse)
<String>There is no route for the path 'apps/1436799971/platforms/ios/versions/843780651'.</String>
\e[0m
</pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.5.2                                      |
| Ruby                        | 2.7.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.30.1 (Apple Git-130)          |
| Installation Source         | ~/.rbenv/versions/2.7.2/bin/fastlane        |
| Host                        | macOS 11.5.2 (20G95)                        |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.2/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1j  16 Feb 2021                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.5.1                                      |
| Swift Version               | 5.4.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.192.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                      | Version | Update-Status      |
| ------------------------------------------- | ------- | ------------------ |
| fastlane-plugin-telegram                    | 0.1.3   | ✅ Up-To-Date       |
| fastlane-plugin-update_xcodeproj            | 1.0.1   | ✅ Up-To-Date       |
| fastlane-plugin-update_provisioning_profile | 0.1.1   | ✅ Up-To-Date       |
| fastlane-plugin-xcconfig                    | 2.0.0   | ✅ Up-To-Date       |
| fastlane-plugin-clean_testflight_testers    | 0.3.0   | ✅ Up-To-Date       |
| fastlane-plugin-json                        | 1.0.0   | ✅ Up-To-Date       |
| fastlane-plugin-xml_editor                  | 0.1.0   | 🚫 Update available |
| fastlane-plugin-analyze_ios_ipa             | 0.1.2   | ✅ Up-To-Date       |

<details><summary><b>Loaded gems</b></summary>

| Gem                                         | Version      |
| ------------------------------------------- | ------------ |
| did_you_mean                                | 1.4.0        |
| rouge                                       | 2.0.7        |
| xcpretty                                    | 0.3.0        |
| terminal-notifier                           | 2.0.0        |
| plist                                       | 3.6.0        |
| CFPropertyList                              | 3.0.3        |
| public_suffix                               | 4.0.6        |
| addressable                                 | 2.8.0        |
| multipart-post                              | 2.0.0        |
| word_wrap                                   | 1.0.0        |
| optparse                                    | 0.1.1        |
| tty-screen                                  | 0.8.1        |
| tty-cursor                                  | 0.7.1        |
| tty-spinner                                 | 0.9.3        |
| artifactory                                 | 3.0.15       |
| babosa                                      | 1.0.4        |
| colored                                     | 1.2          |
| highline                                    | 2.0.3        |
| commander                                   | 4.6.0        |
| faraday-cookie_jar                          | 0.0.7        |
| gh_inspector                                | 1.1.3        |
| mini_magick                                 | 4.11.0       |
| naturally                                   | 2.2.1        |
| security                                    | 0.1.3        |
| xcpretty-travis-formatter                   | 1.0.1        |
| dotenv                                      | 2.7.6        |
| simctl                                      | 1.6.8        |
| emoji_regex                                 | 3.2.2        |
| uri                                         | 0.10.0       |
| rexml                                       | 3.2.5        |
| nanaimo                                     | 0.3.0        |
| colored2                                    | 3.1.2        |
| claide                                      | 1.0.3        |
| atomos                                      | 0.1.3        |
| xcodeproj                                   | 1.21.0       |
| unicode-display_width                       | 1.7.0        |
| terminal-table                              | 1.8.0        |
| excon                                       | 0.85.0       |
| ruby2_keywords                              | 0.0.5        |
| faraday-rack                                | 1.0.0        |
| faraday-patron                              | 1.0.0        |
| faraday-net_http_persistent                 | 1.2.0        |
| faraday-net_http                            | 1.0.1        |
| faraday-httpclient                          | 1.0.1        |
| faraday-excon                               | 1.1.0        |
| faraday-em_synchrony                        | 1.0.0        |
| faraday-em_http                             | 1.0.0        |
| faraday                                     | 1.7.1        |
| unf_ext                                     | 0.0.7.7      |
| unf                                         | 0.1.4        |
| domain_name                                 | 0.5.20190701 |
| http-cookie                                 | 1.0.4        |
| faraday_middleware                          | 1.1.0        |
| fastimage                                   | 2.2.5        |
| json                                        | 2.5.1        |
| rubyzip                                     | 2.3.2        |
| bundler                                     | 2.2.25       |
| jwt                                         | 2.2.3        |
| webrick                                     | 1.7.0        |
| httpclient                                  | 2.8.3        |
| multi_json                                  | 1.15.0       |
| signet                                      | 0.15.0       |
| os                                          | 1.1.1        |
| memoist                                     | 0.16.2       |
| googleauth                                  | 0.17.0       |
| mini_mime                                   | 1.1.1        |
| retriable                                   | 3.1.2        |
| trailblazer-option                          | 0.1.1        |
| declarative                                 | 0.0.20       |
| uber                                        | 0.1.0        |
| representable                               | 3.1.1        |
| google-apis-core                            | 0.4.1        |
| google-apis-playcustomapp_v1                | 0.5.0        |
| google-apis-androidpublisher_v3             | 0.10.0       |
| rake                                        | 13.0.6       |
| digest-crc                                  | 0.6.4        |
| google-apis-storage_v1                      | 0.6.0        |
| google-apis-iamcredentials_v1               | 0.7.0        |
| google-cloud-errors                         | 1.1.0        |
| google-cloud-env                            | 1.5.0        |
| google-cloud-core                           | 1.6.0        |
| google-cloud-storage                        | 1.34.1       |
| aws-eventstream                             | 1.1.1        |
| aws-sigv4                                   | 1.2.4        |
| aws-partitions                              | 1.492.0      |
| jmespath                                    | 1.4.0        |
| aws-sdk-core                                | 3.119.1      |
| aws-sdk-kms                                 | 1.47.0       |
| aws-sdk-s3                                  | 1.100.0      |
| forwardable                                 | 1.3.1        |
| logger                                      | 1.4.2        |
| cgi                                         | 0.1.0        |
| date                                        | 3.0.0        |
| timeout                                     | 0.1.0        |
| stringio                                    | 0.1.0        |
| ipaddr                                      | 1.2.2        |
| openssl                                     | 2.1.2        |
| zlib                                        | 1.1.0        |
| mutex_m                                     | 0.1.0        |
| ostruct                                     | 0.2.0        |
| strscan                                     | 1.0.3        |
| io-console                                  | 0.5.6        |
| delegate                                    | 0.1.0        |
| fileutils                                   | 1.4.1        |
| singleton                                   | 0.1.0        |
| open3                                       | 0.1.0        |
| nokogiri                                    | 1.12.4       |
| racc                                        | 1.5.2        |
| yaml                                        | 0.1.0        |
| psych                                       | 3.1.0        |
| fastlane-plugin-telegram                    | 0.1.3        |
| fastlane-plugin-update_xcodeproj            | 1.0.1        |
| fastlane-plugin-update_provisioning_profile | 0.1.1        |
| fastlane-plugin-xcconfig                    | 2.0.0        |
| fastlane-plugin-clean_testflight_testers    | 0.3.0        |
| fastlane-plugin-json                        | 1.0.0        |
| fastlane-plugin-xml_editor                  | 0.1.0        |
| fastlane-plugin-analyze_ios_ipa             | 0.1.2        |
</details>

*generated on:* **2021-08-31**
</details>

**Comment by Reiszecke** [comment]
Same issue here.

**Comment by lucgrabowski** [comment]
Hi, Could you try using newer API? 
```ruby
Spaceship::ConnectAPI.login
apps = Spaceship::ConnectAPI::App.all
app.get_live_app_store_version
```
https://github.com/fastlane/fastlane/blob/master/spaceship/docs/AppStoreConnect.md#applications
https://github.com/fastlane/fastlane/blob/master/spaceship/docs/AppStoreConnect.md#appversions

**Comment by xwal** [comment]
> Hi, Could you try using newer API?
> 
> ```ruby
> Spaceship::ConnectAPI.login
> apps = Spaceship::ConnectAPI::App.all
> app.get_live_app_store_version
> ```
> 
> https://github.com/fastlane/fastlane/blob/master/spaceship/docs/AppStoreConnect.md#applications
> https://github.com/fastlane/fastlane/blob/master/spaceship/docs/AppStoreConnect.md#appversions

Yes, I have changed to ConnectAPI, it's ok.

**Comment by lucgrabowski** [comment]
Could you close the issue if it's ok now?

**Comment by xwal** [comment]
OK, but `Spaceship::Tunes`'s `app.live_version` also has problem.
