### ISSUE TITLE
undefined method `first' for "errors":String

### ISSUE THREAD

**Issue by gornidar** [fastlane/fastlane#19326]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
not descriptive error in running sync_code_signing when latest program license is not accepted

##### Command executed
sync_code_signing

##### Complete output when running fastlane, including the stack trace and command used
response from API
       {
  "errors" : [ {
    "id" : "xxx",
    "status" : "403",
    "code" : "FORBIDDEN_ERROR.PLA_NOT_ACCEPTED",
    "title" : "Unable to process request - PLA Update available",
    "detail" : "You currently don't have access to this membership resource. To resolve this issue, your team's Account Holder, xxxxx, must agree to the latest Program License Agreement."
  } ]
}

<details>
  <pre>NoMethodError: [!] undefined method `first' for "errors":String
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/spaceship/lib/spaceship/connect_api/api_client.rb:214:in `handle_error'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/spaceship/lib/spaceship/client.rb:886:in `block in send_request'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/spaceship/lib/spaceship/client.rb:646:in `with_retry'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/spaceship/lib/spaceship/client.rb:882:in `send_request'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/spaceship/lib/spaceship/client.rb:726:in `request'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/spaceship/lib/spaceship/connect_api/provisioning/client.rb:54:in `proxy_get'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/spaceship/lib/spaceship/connect_api/provisioning/client.rb:29:in `get'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/spaceship/lib/spaceship/connect_api/provisioning/provisioning.rb:22:in `get_bundle_ids'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `get_bundle_ids'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/spaceship/lib/spaceship/connect_api/models/bundle_id.rb:44:in `all'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/spaceship/lib/spaceship/connect_api/models/bundle_id.rb:50:in `find'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/match/lib/match/spaceship_ensure.rb:45:in `bundle_identifier_exists'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/match/lib/match/runner.rb:91:in `block in run'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/match/lib/match/runner.rb:90:in `each'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/match/lib/match/runner.rb:90:in `run'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/actions/sync_code_signing.rb:19:in `run'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:157:in `block (2 levels) in parsing_binding'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:76:in `block (2 levels) in parsing_binding'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
  /xxx/vendor/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
  /xxx/vendor/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
  /xxx/vendor/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /xxx/vendor/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
  /xxx/vendor/bundle/ruby/2.6.0/gems/fastlane-2.184.1/bin/fastlane:23:in `<top (required)>'
  /xxx/vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `load'
  /xxx/vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `<top (required)>'
Error: Process completed with exit code 1.</pre>
</details>

### Environment

<details>
<pre>
### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 11.4                                                    |
| Ruby                        | 2.7.1                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.30.1 (Apple Git-130)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.156.1/libexec/bin/fastlane |
| Host                        | macOS 11.4 (20F71)                                      |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.7.1_2/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1f  31 Mar 2020                             |
| Is contained                | false                                                   |
| Is homebrew                 | false                                                   |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 12.5.1                                                  |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.156.1 | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status      |
| ------------------------- | ------- | ------------------ |
| fastlane-plugin-appcenter | 1.9.0   | 🚫 Update available |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.18.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.76.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.2        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.1        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-storage      | 1.27.0       |
| emoji_regex               | 3.0.0        |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.1        |
| aws-sdk-kms               | 1.36.0       |
| aws-sdk-s3                | 1.78.0       |
| uri                       | 0.10.0       |
| aws-partitions            | 1.354.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.114.0      |
| forwardable               | 1.3.1        |
| logger                    | 1.4.2        |
| cgi                       | 0.1.0        |
| timeout                   | 0.1.0        |
| stringio                  | 0.1.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.2.0        |
| strscan                   | 1.0.3        |
| date                      | 3.0.0        |
| delegate                  | 0.1.0        |
| fileutils                 | 1.4.1        |
| io-console                | 0.5.6        |
| zlib                      | 1.1.0        |
| singleton                 | 0.1.0        |
| rexml                     | 3.2.3        |
| open3                     | 0.1.0        |
| yaml                      | 0.1.0        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.6.0        |
| fastlane-plugin-appcenter | 1.9.0        |
| csv                       | 3.1.2        |
</details>

</pre>
</details>

**Comment by lucgrabowski** [comment]
Hi @gornidar, I think that this was fixed some time ago. Could you try using the newest version of fastlane?
