### ISSUE TITLE
[!] 'bucket_url' value must be a String! Found File instead.

### ISSUE THREAD

**Issue by YassinELhadedy** [fastlane/fastlane#19320]
when I run command to integrate Fastlane with firebase test lab: Fastlane instrumentation_tests_testlab

this error shows:
fastlane finished with errors

[!] 'bucket_url' value must be a String! Found File instead.

**Comment by YassinELhadedy** [comment]
> fastlane env

fastlane env
[✔] 🚀 
[01:59:26]: fastlane detected a Gemfile in the current directory
[01:59:26]: However, it seems like you didn't use `bundle exec`
[01:59:26]: To launch fastlane faster, please use
[01:59:26]: 
[01:59:26]: $ bundle exec fastlane env
[01:59:26]: 
[01:59:26]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[01:59:29]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                           |
| --------------------------- | --------------------------------------------------------------- |
| OS                          | debian_based bullseye/sid                                       |
| Ruby                        | 2.7.2                                                           |
| Bundler?                    | false                                                           |
| Git                         | git version 2.13.0.rc2                                          |
| Installation Source         | /usr/local/bin/fastlane                                         |
| Host                        | Ubuntu 20.04.3 LTS debian_based bullseye/sid (5.4.0-81-generic) |
| Ruby Lib Dir                | /usr/lib                                                        |
| OpenSSL Version             | OpenSSL 1.1.1f  31 Mar 2020                                     |
| Is contained                | false                                                           |
| Is homebrew                 | false                                                           |
| Is installed via Fabric.app | false                                                           |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE | en_US:en    | 🚫 |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Assemble Build"
  lane :assemble_build do
    gradle(task: "assembleDebug")
  end

  desc "Assemble Test Application"
  lane :assemble_test_application do
    gradle(task: "assembleDebugAndroidTest")
  end

  desc "Assemble Build and Test Application"
  lane :assemble do
    assemble_build
    assemble_test_application
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Run instrumentation tests"
  lane :instrumentation_tests do
    automated_test_emulator_run(
      AVD_setup_path: "fastlane/AVD_setup.json",
      AVD_recreate_new: false,
      AVD_clean_after: false,
      gradle_task: "connectedDebugAndroidTest")
  end

desc "Run instrumentation tests in Firebase Test Lab"
lane :instrumentation_tests_testlab do
  run_tests_firebase_testlab(
    project_id: "project-id",
    devices: [
      {
        model: "Samsung",
        version: "26"
      }
    ],
    delete_firebase_files: true)
end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("com.jumia.myapplication") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.193.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                                      | Version | Update-Status |
| ------------------------------------------- | ------- | ------------- |
| fastlane-plugin-automated_test_emulator_run | 1.6.0   | ✅ Up-To-Date  |
| fastlane-plugin-run_tests_firebase_testlab  | 0.3.1   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                                         | Version      |
| ------------------------------------------- | ------------ |
| did_you_mean                                | 1.4.0        |
| atomos                                      | 0.1.3        |
| CFPropertyList                              | 3.0.3        |
| claide                                      | 1.0.3        |
| colored2                                    | 3.1.2        |
| nanaimo                                     | 0.3.0        |
| rexml                                       | 3.2.5        |
| xcodeproj                                   | 1.21.0       |
| rouge                                       | 2.0.7        |
| xcpretty                                    | 0.3.0        |
| terminal-notifier                           | 2.0.0        |
| unicode-display_width                       | 1.7.0        |
| terminal-table                              | 1.8.0        |
| plist                                       | 3.6.0        |
| public_suffix                               | 4.0.6        |
| addressable                                 | 2.8.0        |
| multipart-post                              | 2.0.0        |
| word_wrap                                   | 1.0.0        |
| optparse                                    | 0.1.1        |
| tty-screen                                  | 0.8.1        |
| tty-cursor                                  | 0.7.1        |
| tty-spinner                                 | 0.9.3        |
| artifactory                                 | 3.0.15       |
| babosa                                      | 1.0.4        |
| colored                                     | 1.2          |
| highline                                    | 2.0.3        |
| commander                                   | 4.6.0        |
| excon                                       | 0.85.0       |
| faraday-em_http                             | 1.0.0        |
| faraday-em_synchrony                        | 1.0.0        |
| faraday-excon                               | 1.1.0        |
| faraday-httpclient                          | 1.0.1        |
| faraday-net_http                            | 1.0.1        |
| faraday-net_http_persistent                 | 1.2.0        |
| faraday-patron                              | 1.0.0        |
| faraday-rack                                | 1.0.0        |
| ruby2_keywords                              | 0.0.5        |
| faraday                                     | 1.7.1        |
| unf_ext                                     | 0.0.7.7      |
| unf                                         | 0.1.4        |
| domain_name                                 | 0.5.20190701 |
| http-cookie                                 | 1.0.4        |
| faraday-cookie_jar                          | 0.0.7        |
| faraday_middleware                          | 1.1.0        |
| fastimage                                   | 2.2.5        |
| gh_inspector                                | 1.1.3        |
| mini_magick                                 | 4.11.0       |
| naturally                                   | 2.2.1        |
| rubyzip                                     | 2.3.2        |
| security                                    | 0.1.3        |
| xcpretty-travis-formatter                   | 1.0.1        |
| dotenv                                      | 2.7.6        |
| simctl                                      | 1.6.8        |
| jwt                                         | 2.2.3        |
| uber                                        | 0.1.0        |
| declarative                                 | 0.0.20       |
| trailblazer-option                          | 0.1.1        |
| representable                               | 3.1.1        |
| retriable                                   | 3.1.2        |
| mini_mime                                   | 1.1.1        |
| memoist                                     | 0.16.2       |
| multi_json                                  | 1.15.0       |
| os                                          | 1.1.1        |
| signet                                      | 0.15.0       |
| googleauth                                  | 0.17.0       |
| httpclient                                  | 2.8.3        |
| google-apis-core                            | 0.4.1        |
| google-apis-playcustomapp_v1                | 0.5.0        |
| google-apis-androidpublisher_v3             | 0.10.0       |
| google-cloud-env                            | 1.5.0        |
| google-cloud-errors                         | 1.1.0        |
| google-cloud-core                           | 1.6.0        |
| google-apis-iamcredentials_v1               | 0.7.0        |
| google-apis-storage_v1                      | 0.6.0        |
| digest-crc                                  | 0.6.4        |
| google-cloud-storage                        | 1.34.1       |
| emoji_regex                                 | 3.2.2        |
| jmespath                                    | 1.4.0        |
| aws-partitions                              | 1.493.0      |
| aws-eventstream                             | 1.1.1        |
| aws-sigv4                                   | 1.2.4        |
| aws-sdk-core                                | 3.119.1      |
| aws-sdk-kms                                 | 1.47.0       |
| aws-sdk-s3                                  | 1.100.0      |
| uri                                         | 0.10.0       |
| json                                        | 2.5.1        |
| bundler                                     | 2.2.26       |
| webrick                                     | 1.7.0        |
| rake                                        | 13.0.6       |
| forwardable                                 | 1.3.1        |
| logger                                      | 1.4.2        |
| cgi                                         | 0.1.0        |
| date                                        | 3.0.0        |
| timeout                                     | 0.1.0        |
| stringio                                    | 0.1.0        |
| ipaddr                                      | 1.2.2        |
| openssl                                     | 2.1.2        |
| zlib                                        | 1.1.0        |
| mutex_m                                     | 0.1.0        |
| ostruct                                     | 0.2.0        |
| strscan                                     | 1.0.3        |
| io-console                                  | 0.5.6        |
| delegate                                    | 0.1.0        |
| fileutils                                   | 1.4.1        |
| etc                                         | 1.1.0        |
| singleton                                   | 0.1.0        |
| open3                                       | 0.1.0        |
| yaml                                        | 0.1.0        |
| psych                                       | 3.1.0        |
| fastlane-plugin-automated_test_emulator_run | 1.6.0        |
| fastlane-plugin-run_tests_firebase_testlab  | 0.3.1        |
</details>


*generated on:* **2021-09-01**
</details>
[01:59:32]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[01:59:32]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅

**Comment by lucgrabowski** [comment]
Hi, it looks like this issue is related to the plugin, not to fastlane itself. Could you close this issue and open it in the plugin's repository?

**Comment by crazymanish** [comment]
Hello @YassinELhadedy 
please open an issue in below GitHub repo
https://github.com/pink-room/fastlane-plugin-run_tests_firebase_testlab
