### ISSUE TITLE
Google Api Error: Invalid request - UploadException

### ISSUE THREAD

**Issue by yu-carter** [fastlane/fastlane#19321]
JSON key is OK. I want to know why I am getting this error.
 -> [!] Google Api Error: Invalid request - UploadException: PARSE_ERROR [[ArtifactParseError{key=APK_NOTIFICATION_MESSAGE_KEY_INVALID_FILE, params=[]}]] (<empty>)

+------+-------------------------------------------+-------------+
|                        fastlane summary                        |
+------+-------------------------------------------+-------------+
| Step | Action                                    | Time (in s) |
+------+-------------------------------------------+-------------+
| 1    | default_platform                          | 0           |
| 2    | clean bundleGoogle                        | 68          |
| 💥   | upload_to_play_store_internal_app_sharin  | 2           |
|      | g                                         |             |
+------+-------------------------------------------+-------------+

[16:17:13]: fastlane finished with errors

[!] Google Api Error: Invalid request - UploadException: PARSE_ERROR [[ArtifactParseError{key=APK_NOTIFICATION_MESSAGE_KEY_INVALID_FILE, params=[]}]] (<empty>)

-------------------------------------------------------------

[16:20:40]: ------------------------------------------
[16:20:40]: --- Step: validate_play_store_json_key ---
[16:20:40]: ------------------------------------------

+----------+------------------------------------------------------------------+
|                  Summary for validate_play_store_json_key                   |
+----------+------------------------------------------------------------------+
| json_key | ./../.github/secrets/pc-api-********-***-*********8.json                                                           |
| timeout  | 300                                                              |
+----------+------------------------------------------------------------------+

[16:20:41]: Successfully established connection to Google Play Store.

**Comment by lucgrabowski** [comment]
Hi, it seems that you got Google API build parsing error. Does `APK_NOTIFICATION_MESSAGE_KEY_INVALID_FILE` give you a clue what should be adjusted in the APK?

**Comment by yu-carter** [comment]
I couldn't find any information about the syntax APK_NOTIFICATION_MESSAGE_KEY_INVALID_FILE so I asked. That syntax is nowhere in my project.

**Comment by lucgrabowski** [comment]
Thanks for explaining the root cause of the issue 🚀
