### ISSUE TITLE
fastlane: [!] Google Api Error: Invalid request - Package not found: com.example.todo

### ISSUE THREAD

**Issue by alakdam07** [fastlane/fastlane#19337]
I am using React-native for my app. I have named my name `reactamplify`. I want to deploy my app to Google play-store. For automation deployment I am using first time `fastlane`. I found this [documentation](https://docs.fastlane.tools/actions/upload_to_play_store/), follow the steps and give API [grant access][1]. In my React native app, I navigate to `android` folder then run this  command `fastlane init`. Give `json_key_file` path my downloaded auth json file. But I got confused about package name. I search my app name in vscode `com.reactamplify` replace them into `com.example.todo`. Then run android folder `fastlane supply init`, I am getting this error: `[!] Google Api Error: Invalid request - Package not found: com.example.todo.` I really don't know how to fix it :(. Really lost TBH.

When I run `fastlane supply`. I got this:

[![enter image description here][2]][2]

**PS: It would be awesome if someone gives me example with images**

  [1]: https://i.stack.imgur.com/fdKmr.png
  [2]: https://i.stack.imgur.com/iq6wG.png

**Comment by lucgrabowski** [comment]
Hi, as written in `Quick start` in the documentation you linked, have you created app manually on Google Play and uplaoded at least one build?
>Quick Start
    Before using supply to connect to Google Play Store, you'll need to set up your app manually first by uploading at least one build to Google Play Store. See fastlane/fastlane#14686 for more info.

**Comment by alakdam07** [comment]
No I did not uploaded any build in play store. Everything is so confusing right now 🙈🙈
