### ISSUE TITLE
Shell command exited with exit status 2 instead of 0.

### ISSUE THREAD

**Issue by YassinELhadedy** [fastlane/fastlane#19339]
integrating fastlane with sonarqube using https://docs.fastlane.tools/actions/sonar/ 

this log:

42s
Run fastlane deploy_to_sonarqube
  fastlane deploy_to_sonarqube
  shell: /bin/bash -e {0}
  env:
    JAVA_HOME_11.0.12_x64: /Users/runner/hostedtoolcache/jdk/11.0.12/x64
    JAVA_HOME: /Users/runner/hostedtoolcache/jdk/11.0.12/x64
    JAVA_HOME_11_0_12_X64: /Users/runner/hostedtoolcache/jdk/11.0.12/x64
[08:58:27]: fastlane detected a Gemfile in the current directory
[08:58:27]: However, it seems like you didn't use `bundle exec`
[08:58:27]: To launch fastlane faster, please use
[08:58:27]: 
[08:58:27]: $ bundle exec fastlane deploy_to_sonarqube
[08:58:27]: 
[08:58:27]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[08:58:29]: ------------------------------
[08:58:29]: --- Step: default_platform ---
[08:58:29]: ------------------------------
[08:58:29]: Driving the lane 'android deploy_to_sonarqube' 🚀
[08:58:29]: -------------------
[08:58:29]: --- Step: sonar ---
[08:58:29]: -------------------
[08:58:32]: ▸ INFO: Scanner configuration file: /usr/local/Cellar/sonar-scanner/4.6.2.2472_1/libexec/conf/sonar-scanner.properties
[08:58:32]: ▸ INFO: Project root configuration file: NONE
[08:58:32]: ▸ INFO: SonarScanner 4.6.2.2472
[08:58:32]: ▸ INFO: Java 11.0.12 Homebrew (64-bit)
[08:58:32]: ▸ INFO: Mac OS X 10.15.7 x86_64
[08:58:33]: ▸ INFO: User cache: /Users/runner/.sonar/cache
[08:58:36]: ▸ INFO: Scanner configuration file: /usr/local/Cellar/sonar-scanner/4.6.2.2472_1/libexec/conf/sonar-scanner.properties
[08:58:36]: ▸ INFO: Project root configuration file: NONE
[08:58:36]: ▸ INFO: Analyzing on SonarCloud
[08:58:36]: ▸ INFO: Default locale: "en_US", source code encoding: "UTF-8" (analysis is platform dependent)
[08:58:36]: ▸ INFO: Load global settings
[08:58:37]: ▸ INFO: Load global settings (done) | time=556ms
[08:58:37]: ▸ INFO: Server id: 1BD809FA-AWHW8ct9-T_TB3XqouNu
[08:58:37]: ▸ INFO: User cache: /Users/runner/.sonar/cache
[08:58:37]: ▸ INFO: Load/download plugins
[08:58:37]: ▸ INFO: Load plugins index
[08:58:37]: ▸ INFO: Load plugins index (done) | time=135ms
[08:59:04]: ▸ INFO: Load/download plugins (done) | time=27804ms
[08:59:05]: ▸ INFO: Loaded core extensions: developer-scanner
[08:59:05]: ▸ INFO: Found an active CI vendor: 'Github Actions'
[08:59:05]: ▸ INFO: Load project settings for component key: 'com.exa.nanashopper'
[08:59:05]: ▸ INFO: Process project properties
[08:59:05]: ▸ ERROR: Invalid value of sonar.sources for com.exa.nanashopper
[08:59:05]: ▸ INFO: ------------------------------------------------------------------------
[08:59:05]: ▸ INFO: EXECUTION FAILURE
[08:59:05]: ▸ INFO: ------------------------------------------------------------------------
[08:59:05]: ▸ INFO: Total time: 33.249s
[08:59:05]: ▸ INFO: Final Memory: 6M/24M
[08:59:05]: ▸ INFO: ------------------------------------------------------------------------
[08:59:05]: ▸ ERROR: Error during SonarScanner execution
[08:59:05]: ▸ ERROR: The folder '/Users/runner/work/android-shopperapp/android-shopperapp/NanaApp' does not exist for 'com.exa.nanashopper' (base directory = /Users/runner/work/android-shopperapp/android-shopperapp)
[08:59:05]: ▸ ERROR:
[08:59:05]: ▸ ERROR: Re-run SonarScanner using the -X switch to enable full debug logging.
+------------------+-----------------------------+
|                  Lane Context                  |
+------------------+-----------------------------+
| DEFAULT_PLATFORM | android                     |
| PLATFORM_NAME    | android                     |
| LANE_NAME        | android deploy_to_sonarqube |
+------------------+-----------------------------+
[08:59:05]: Shell command exited with exit status 2 instead of 0.
INFO: Scanner configuration file: /usr/local/Cellar/sonar-scanner/4.6.2.2472_1/libexec/conf/sonar-scanner.properties
INFO: Project root configuration file: NONE
INFO: SonarScanner 4.6.2.2472
INFO: Java 11.0.12 Homebrew (64-bit)
INFO: Mac OS X 10.15.7 x86_64
INFO: User cache: /Users/runner/.sonar/cache
INFO: Scanner configuration file: /usr/local/Cellar/sonar-scanner/4.6.2.2472_1/libexec/conf/sonar-scanner.properties
INFO: Project root configuration file: NONE
INFO: Analyzing on SonarCloud
INFO: Default locale: "en_US", source code encoding: "UTF-8" (analysis is platform dependent)
INFO: Load global settings
INFO: Load global settings (done) | time=556ms
INFO: Server id: 1BD809FA-AWHW8ct9-T_TB3XqouNu
INFO: User cache: /Users/runner/.sonar/cache
INFO: Load/download plugins
INFO: Load plugins index
INFO: Load plugins index (done) | time=135ms
INFO: Load/download plugins (done) | time=27804ms
INFO: Loaded core extensions: developer-scanner
INFO: Found an active CI vendor: 'Github Actions'
INFO: Load project settings for component key: 'com.exa.nanashopper'
INFO: Process project properties
ERROR: Invalid value of sonar.sources for com.exa.nanashopper
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 33.249s
INFO: Final Memory: 6M/24M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarScanner execution
ERROR: The folder '/Users/runner/work/android-shopperapp/android-shopperapp/NanaApp' does not exist for 'com.exa.nanashopper' (base directory = /Users/runner/work/android-shopperapp/android-shopperapp)
ERROR: 
ERROR: Re-run SonarScanner using the -X switch to enable full debug logging.

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 💥   | sonar            | 36          |
+------+------------------+-------------+

[08:59:05]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

#######################################################################
# fastlane 2.193.1 is available. You are on 2.193.0.
# You should use the latest version.
# Please update using `gem install fastlane`.
#######################################################################

2.193.1 Improvements
* [gradle] add output context with "tasks" options (#19312) via David Kuo
* [match] ignore force_for_new_devices for developer_id provisioning type (#19314) via Vitalii Budnik
* [match] don't force update macos development certs if macos device count unchanged (#19315) via Vitalii Budnik
* [pilot][upload_to_testflight] add missing method (#19319) via David Brunow

Please update using `gem install fastlane`
/usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.193.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': \e[31m[!] Shell command exited with exit status 2 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
INFO: Scanner configuration file: /usr/local/Cellar/sonar-scanner/4.6.2.2472_1/libexec/conf/sonar-scanner.properties
INFO: Project root configuration file: NONE
INFO: SonarScanner 4.6.2.2472
INFO: Java 11.0.12 Homebrew (64-bit)
INFO: Mac OS X 10.15.7 x86_64
INFO: User cache: /Users/runner/.sonar/cache
INFO: Scanner configuration file: /usr/local/Cellar/sonar-scanner/4.6.2.2472_1/libexec/conf/sonar-scanner.properties
INFO: Project root configuration file: NONE
INFO: Analyzing on SonarCloud
INFO: Default locale: "en_US", source code encoding: "UTF-8" (analysis is platform dependent)
INFO: Load global settings
INFO: Load global settings (done) | time=556ms
INFO: Server id: 1BD809FA-AWHW8ct9-T_TB3XqouNu
INFO: User cache: /Users/runner/.sonar/cache
INFO: Load/download plugins
INFO: Load plugins index
INFO: Load plugins index (done) | time=135ms
INFO: Load/download plugins (done) | time=27804ms
INFO: Loaded core extensions: developer-scanner
INFO: Found an active CI vendor: 'Github Actions'
INFO: Load project settings for component key: 'com.exa.nanashopper'
INFO: Process project properties
ERROR: Invalid value of sonar.sources for com.exa.nanashopper
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 33.249s
INFO: Final Memory: 6M/24M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarScanner execution
ERROR: The folder '/Users/runner/work/android-shopperapp/android-shopperapp/NanaApp' does not exist for 'com.exa.nanashopper' (base directory = /Users/runner/work/android-shopperapp/android-shopperapp)
ERROR: 
ERROR: Re-run SonarScanner using the -X switch to enable full debug logging.
\e[0m
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.193.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/actions/sonar.rb:38:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:68:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.193.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.193.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:25:in `load'
	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:25:in `<main>'
Error: Process completed with exit code 1.

**Comment by StevenFY** [comment]
```
Traceback (most recent call last):
        36: from /usr/local/bin/fastlane:23:in `<main>'
        35: from /usr/local/bin/fastlane:23:in `load'
        34: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/bin/fastlane:23:in `<top (required)>'
        33: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
        32: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
        31: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
        30: from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        29: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
        28: from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        27: from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        26: from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        25: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
        24: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        23: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        22: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        21: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        20: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        19: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        18: from Fastfile:38:in `block (2 levels) in parsing_binding'
        17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
        15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
        14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        13: from Fastfile_Generic:22:in `block (2 levels) in parsing_binding'
        12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
         9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
         8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
         7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
         6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
         5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/fastlane/lib/fastlane/actions/gradle.rb:60:in `run'
         4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/fastlane/lib/fastlane/helper/gradle_helper.rb:32:in `trigger'
         3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `sh'
         2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
         1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.194.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': [!] Shell command exited with exit status 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)

```

```
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.5.2                                                         |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.23.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.5.2 (20G95)                                           |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Library/Developer/CommandLineTools/                           |
| Xcode Version               |                                                                |
| Swift Version               | 5.3.2                                                          |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
import("./Fastfile_Before")
import("./Fastfile_Generic")

default_platform(:android)

platform :android do

  desc "Run Unit Tests"
    lane :unit_tests do
      assemble(
        build_task: "test",
        build_flavor: "dev",
        build_type: "Debug"
      )
  end

  desc "Run Instrumented tests"
    lane :instrumented_tests do
      gradle(task: "connectedProdDebugAndroidTest")
  end

  desc "Distribute a new version on Firebase"
  lane :distribute_firebase do |options|
    build_type = options[:type] || "APK"
    build_task = (build_type == "AAB" ? "bundle" : "assemble")

    assemble(
      build_task: build_task, 
      build_flavor: "Dev",
      build_type: "Release"
    )

    upload_to_firebase(
        release_notes: options[:release_notes],
        build_type: build_type
    )

    message = getBuildVersion() + " is ready to test on AppTester (Firebase) !"
    post_success_on_slack(message: message)
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy_play_store do |options|
    unit_tests

    assemble(
      build_task: "clean assemble", 
      build_flavor: "prod",        
      build_type: "Release",
      build_properties: true
    )

   build_track = options[:build_track] || "internal"
   build_rollout = options[:build_track] || 1
   deploy_to_play_store(
    build_track: build_track,
    build_rollout: build_rollout
   )
  end

  desc "Update Strings from POEditor for all projects and subprojects"
  lane :update_strings do

    # Strings for app-pro
    update_loop_strings(
      project_id: ENV["POE_EDITOR_APP_PRO_PROJECT_ID"],
      output_path: ENV["POE_EDITOR_APP_PRO_OUTPUT_PATH"]
    )

    # Strings for adjust_actuators
    update_loop_strings(
      project_id: ENV["POE_EDITOR_ADJUST_ACTUATORS_PROJECT_ID"],
      output_path: ENV["POE_EDITOR_ADJUST_ACTUATORS_OUTPUT_PATH"]
    )

    # Langs not in commun between two projects. Need to be removed in future.
    update_loop_strings(
      langs: ["sk"],
      project_id: ENV["POE_EDITOR_APP_PRO_PROJECT_ID"],
      output_path: ENV["POE_EDITOR_APP_PRO_OUTPUT_PATH"]
    )
  end

  desc "Update XML for adjust_actuators module from Github"
  lane :update_xml do
    sh "./script/class/adjust_actuators/update_xml.sh"
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("./app/google-services.json") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("com.somfy.pro") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.194.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.3.1   | ✅ Up-To-Date  |
| fastlane-plugin-versioning_android        | 0.1.0   | ✅ Up-To-Date  |
| fastlane-plugin-poeditor_export           | 0.3.0   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.3.0        |
| atomos                                    | 0.1.3        |
| claide                                    | 1.0.3        |
| colored2                                  | 3.1.2        |
| nanaimo                                   | 0.3.0        |
| rexml                                     | 3.2.5        |
| xcodeproj                                 | 1.21.0       |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.7.0        |
| terminal-table                            | 1.8.0        |
| plist                                     | 3.6.0        |
| public_suffix                             | 4.0.6        |
| addressable                               | 2.8.0        |
| multipart-post                            | 2.0.0        |
| word_wrap                                 | 1.0.0        |
| optparse                                  | 0.1.1        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| artifactory                               | 3.0.15       |
| babosa                                    | 1.0.4        |
| colored                                   | 1.2          |
| highline                                  | 2.0.3        |
| commander                                 | 4.6.0        |
| excon                                     | 0.85.0       |
| faraday-em_http                           | 1.0.0        |
| faraday-em_synchrony                      | 1.0.0        |
| faraday-excon                             | 1.1.0        |
| faraday-httpclient                        | 1.0.1        |
| faraday-net_http                          | 1.0.1        |
| faraday-net_http_persistent               | 1.2.0        |
| faraday-patron                            | 1.0.0        |
| faraday-rack                              | 1.0.0        |
| ruby2_keywords                            | 0.0.5        |
| faraday                                   | 1.7.0        |
| unf_ext                                   | 0.0.7.7      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| http-cookie                               | 1.0.4        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.1.0        |
| fastimage                                 | 2.2.5        |
| gh_inspector                              | 1.1.3        |
| mini_magick                               | 4.11.0       |
| naturally                                 | 2.2.1        |
| rubyzip                                   | 2.3.2        |
| security                                  | 0.1.3        |
| xcpretty-travis-formatter                 | 1.0.1        |
| dotenv                                    | 2.7.6        |
| bundler                                   | 2.2.22       |
| simctl                                    | 1.6.8        |
| jwt                                       | 2.2.3        |
| uber                                      | 0.1.0        |
| declarative                               | 0.0.20       |
| trailblazer-option                        | 0.1.1        |
| representable                             | 3.1.1        |
| retriable                                 | 3.1.2        |
| mini_mime                                 | 1.1.1        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.1        |
| signet                                    | 0.15.0       |
| googleauth                                | 0.17.0       |
| httpclient                                | 2.8.3        |
| google-apis-core                          | 0.4.1        |
| google-apis-playcustomapp_v1              | 0.5.0        |
| google-apis-androidpublisher_v3           | 0.10.0       |
| google-cloud-env                          | 1.5.0        |
| google-cloud-errors                       | 1.1.0        |
| google-cloud-core                         | 1.6.0        |
| google-apis-iamcredentials_v1             | 0.7.0        |
| google-apis-storage_v1                    | 0.6.0        |
| digest-crc                                | 0.6.4        |
| google-cloud-storage                      | 1.34.1       |
| emoji_regex                               | 3.2.2        |
| jmespath                                  | 1.4.0        |
| aws-partitions                            | 1.491.0      |
| aws-eventstream                           | 1.1.1        |
| aws-sigv4                                 | 1.2.4        |
| aws-sdk-core                              | 3.119.1      |
| aws-sdk-kms                               | 1.46.0       |
| aws-sdk-s3                                | 1.99.0       |
| CFPropertyList                            | 3.0.3        |
| json                                      | 2.5.1        |
| webrick                                   | 1.7.0        |
| rake                                      | 13.0.6       |
| forwardable                               | 1.2.0        |
| logger                                    | 1.3.0        |
| date                                      | 2.0.0        |
| stringio                                  | 0.0.2        |
| ipaddr                                    | 1.2.2        |
| openssl                                   | 2.1.2        |
| zlib                                      | 1.0.0        |
| mutex_m                                   | 0.1.0        |
| ostruct                                   | 0.1.0        |
| strscan                                   | 1.0.0        |
| io-console                                | 0.4.7        |
| fileutils                                 | 1.1.0        |
| etc                                       | 1.0.1        |
| libxml-ruby                               | 3.1.0        |
| psych                                     | 3.1.0        |
| fastlane-plugin-firebase_app_distribution | 0.3.1        |
| fastlane-plugin-versioning_android        | 0.1.0        |
| fastlane-plugin-poeditor_export           | 0.3.0        |
</details>


*generated on:* **2021-09-17**
</details>
```

**Comment by lucgrabowski** [comment]
Hi, I think that you should take a look at `deploy_to_sonarqube` in your Fastfile. Maybe adjusting `sources_path` would help?
>Comma-separated paths to directories containing source files. Must either be specified here or inside the sonar project configuration file

as written in docs https://docs.fastlane.tools/actions/sonar/ 

It looks like sonar tries to access directory that doesn't exist:

> ERROR: Invalid value of sonar.sources for com.exa.nanashopper
...
ERROR: Error during SonarScanner execution
ERROR: The folder '/Users/runner/work/android-shopperapp/android-shopperapp/NanaApp' does not exist for 'com.exa.nanashopper' (base directory = /Users/runner/work/android-shopperapp/android-shopperapp)

**Comment by Braddock569** [comment]
Very informative post. I really do hope and pray this stuff works.
