### ISSUE TITLE
Deliverfile api_key: connect_api/token.rb:62:in `binread': [!] no implicit conversion of nil into String

### ISSUE THREAD

**Issue by Kondamon** [fastlane/fastlane#19348]
### New Issue Checklist

- [ x ] Updated fastlane to the latest version
- [ x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Want to store api_key for AppstoreConnect in Deliverfile. But I receive errors when running any command like `fastlane deliver download_screenshots`
##### Command executed

`fastlane deliver download_screenshots`

Deliverfile
```
# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

app_identifier "app.bundle.iOS-App"

api_key(
  key_id: "ABCDEFGHI",
  issuer_id: "45348905834-ds345345435-3534534534",
  key_filepath: "./fastlane/AuthKey_ABCDEFGHI.p8",
  duration: 1200, # optional (maximum 1200)
  in_house: false # optional but may be required if using match/sigh
)
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>  $> fastlane deliver download_screenshots
[⠙] 🚀 Ignoring ffi-1.13.1 because its extensions are not built. Try: gem pristine ffi --version 1.13.1
Ignoring redcarpet-3.5.0 because its extensions are not built. Try: gem pristine redcarpet --version 3.5.0
Ignoring sassc-2.4.0 because its extensions are not built. Try: gem pristine sassc --version 2.4.0
[✔] 🚀 
[20:04:49]: fastlane detected a Gemfile in the current directory
[20:04:49]: However, it seems like you didn't use `bundle exec`
[20:04:49]: To launch fastlane faster, please use
[20:04:49]: 
[20:04:49]: $ bundle exec fastlane deliver download_screenshots
[20:04:49]: 
[20:04:49]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[20:04:51]: Successfully loaded '/Users/christian/pgm/fastlane-appstore/fastlane/Deliverfile' 📄

+----------------+--------------------------------------------------------------------------------------+
|                             Detected Values from './fastlane/Deliverfile'                             |
+----------------+--------------------------------------------------------------------------------------+
| app_identifier | app.bundle.iOS-App                                                                   |
| api_key        | {:key_id=>"ABCDEFGHI", :issuer_id=>"45348905834-ds345345435-3534534534",             |
|                | :key_filepath=>"./fastlane/AuthKey_ABCDEFGHI.p8", :duration=>1200, :in_house=>false} |
+----------------+--------------------------------------------------------------------------------------+

Looking for related GitHub issues on fastlane/fastlane...

➡️  google_cloud_storage TypeError: [!] no implicit conversion of nil into String
    https://github.com/fastlane/fastlane/issues/16836 [closed] 10 💬
    20 Oct 2020

➡️  latest_testflight_build_number receiving error: [!] no implicit conversion of Integer into String
    https://github.com/fastlane/fastlane/issues/17161 [closed] 10 💬
    04 Nov 2020

➡️  latest_testflight_build_number receiving error: [!] no implicit conversion of Integer into String
    https://github.com/fastlane/fastlane/issues/17162 [closed] 1 💬
    03 Nov 2020

and 88 more at: https://github.com/fastlane/fastlane/search?q=no%20implicit%20conversion%20of%20nil%20into%20String&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	17: from /usr/local/bin/fastlane:23:in `<main>'
	16: from /usr/local/bin/fastlane:23:in `load'
	15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/bin/fastlane:23:in `<top (required)>'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/deliver/lib/deliver/commands_generator.rb:18:in `start'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/deliver/lib/deliver/commands_generator.rb:187:in `run'
	11: from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	 9: from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	 8: from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	 7: from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/deliver/lib/deliver/commands_generator.rb:148:in `block (2 levels) in run'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/deliver/lib/deliver/commands_generator.rb:148:in `new'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/deliver/lib/deliver/runner.rb:23:in `initialize'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/deliver/lib/deliver/runner.rb:30:in `login'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/spaceship/lib/spaceship/connect_api/token.rb:32:in `from'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/spaceship/lib/spaceship/connect_api/token.rb:62:in `create'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/spaceship/lib/spaceship/connect_api/token.rb:62:in `binread': no implicit conversion of nil into String (TypeError)
	17: from /usr/local/bin/fastlane:23:in `<main>'
	16: from /usr/local/bin/fastlane:23:in `load'
	15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/bin/fastlane:23:in `<top (required)>'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/deliver/lib/deliver/commands_generator.rb:18:in `start'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/deliver/lib/deliver/commands_generator.rb:187:in `run'
	11: from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	 9: from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	 8: from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	 7: from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/deliver/lib/deliver/commands_generator.rb:148:in `block (2 levels) in run'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/deliver/lib/deliver/commands_generator.rb:148:in `new'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/deliver/lib/deliver/runner.rb:23:in `initialize'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/deliver/lib/deliver/runner.rb:30:in `login'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/spaceship/lib/spaceship/connect_api/token.rb:32:in `from'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/spaceship/lib/spaceship/connect_api/token.rb:62:in `create'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/spaceship/lib/spaceship/connect_api/token.rb:62:in `binread': [!] no implicit conversion of nil into String (TypeError)
</pre>
</details>

### Environment

<details>
  <pre> <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.5.2                                                         |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.30.1 (Apple Git-130)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.5.2 (20G95)                                           |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.5.1                                                         |
| Swift Version               | 5.4.2                                                          |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end



# key_id "J3PHHY66L5"

#issuer_id "3dbc55a2-b2a0-424f-9a02-cecc35a421ca"
#key_filepath "./AuthKey_J3PHHY66L5.p8"


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "app.hero21.iOS-App" # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.193.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| atomos                          | 0.1.3        |
| CFPropertyList                  | 2.3.6        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.18.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.85.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.7.1        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.1.0        |
| fastimage                       | 2.2.5        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.1.0        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.22       |
| simctl                          | 1.6.8        |
| jwt                             | 2.2.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.1        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.1        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| signet                          | 0.16.0       |
| googleauth                      | 0.17.1       |
| httpclient                      | 2.8.3        |
| rexml                           | 3.1.9        |
| webrick                         | 1.4.2        |
| google-apis-core                | 0.4.1        |
| google-apis-playcustomapp_v1    | 0.5.0        |
| google-apis-androidpublisher_v3 | 0.11.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.7.0        |
| google-apis-storage_v1          | 0.6.0        |
| rake                            | 12.3.2       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.34.1       |
| emoji_regex                     | 3.2.2        |
| jmespath                        | 1.4.0        |
| aws-partitions                  | 1.500.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-sdk-core                    | 3.121.0      |
| aws-sdk-kms                     | 1.48.0       |
| aws-sdk-s3                      | 1.102.0      |
| forwardable                     | 1.2.0        |
| logger                          | 1.3.0        |
| date                            | 2.0.0        |
| stringio                        | 0.0.2        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.0.0        |
| mutex_m                         | 0.1.0        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| io-console                      | 0.4.7        |
| fileutils                       | 1.1.0        |
| etc                             | 1.0.1        |
| libxml-ruby                     | 3.1.0        |
| psych                           | 3.1.0        |
</details>

*generated on:* **2021-09-12**
</details> </pre>
</details>

**Comment by lucgrabowski** [comment]
@Kondamon, could you try renaming `key_filepath` to `filepath`?
It looks like `filepath` is expected:
https://github.com/fastlane/fastlane/blob/be624617eb2cefb5a96457f27768ad26d74eebed/spaceship/lib/spaceship/connect_api/token.rb#L52-L62

**Comment by cristibaluta** [comment]
I get the same thing, i'm using the swift version and the key expected is definitely key_filepath
