### ISSUE TITLE
Error fetching app store review detail - The specified resource does not exist 

### ISSUE THREAD

**Issue by gelodgreat** [fastlane/fastlane#19342]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Error fetching app store review detail - The specified resource does not exist - There is no resource of type 'appStoreReviewDetail' with id

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> Uploading metadata causes this, I dont have app store review detail</pre>
</details>

### Environment

<details>
  <pre> 
[09:44:36]: [33mfastlane detected a Gemfile in the current directory[0m
[09:44:36]: [33mHowever, it seems like you didn't use `bundle exec`[0m
[09:44:36]: [33mTo launch fastlane faster, please use[0m
[09:44:36]: 
[09:44:36]: [36m$ bundle exec fastlane env[0m
[09:44:36]: 
[09:44:36]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
[09:44:38]: [33mGenerating fastlane environment output, this might take a few seconds...[0m
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.15.7                                          |
| Ruby                        | 2.6.5                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.32.0                               |
| Installation Source         | ~/.rbenv/versions/2.6.5/bin/fastlane             |
| Host                        | Mac OS X 10.15.7 (19H15)                         |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.5/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-12.4.app/Contents/Developer/ |
| Xcode Version               | 12.4                                             |
| Swift Version               | 5.3.2                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane



# fastlane_require "dotenv"


default_platform(:ios)

platform :ios do
    
    lane :release do
     begin
      upload_to_app_store(
        force: true,
        submit_for_review: false,
        skip_binary_upload: false,
        skip_metadata: false,
        skip_screenshots: false,
        app_version: ENV['APP_VERSION'],
        description:{"en-US" =>  ENV["APP_STORE_DESCRIPTION"]},
        promotional_text: {"en-US" => ENV["APP_STORE_PROMOTIONAL_TEXT"]},
        privacy_url: {"en-US" => ENV["APP_STORE_PRIVACY_URL"]}, 
        submission_information: {
          add_id_info_limits_tracking: true,
          add_id_info_serves_ads: false,
          add_id_info_tracks_action: true,
          add_id_info_tracks_install: true,
          add_id_info_uses_idfa: true,
          content_rights_has_rights: true,
          content_rights_contains_third_party_content: true,
          export_compliance_platform: 'ios',
          export_compliance_compliance_required: false,
          export_compliance_encryption_updated: false,
          export_compliance_app_type: nil,
          export_compliance_uses_encryption: true,
          export_compliance_is_exempt: true,
          export_compliance_contains_third_party_cryptography: false,
          export_compliance_contains_proprietary_cryptography: false,
          export_compliance_available_on_french_store: false
        }
      )
     rescue => exception
      UI.user_error!("Upload failed")
     end

      
    end
end
```
</details>

<details><summary>`./Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.193.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-appicon    | 0.16.0  | ✅ Up-To-Date  |
| fastlane-plugin-versioning | 0.5.0   | ✅ Up-To-Date  |
| fastlane-plugin-sentry     | 1.9.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| atomos                          | 0.1.3        |
| CFPropertyList                  | 3.0.3        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| rexml                           | 3.2.5        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.85.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.7.0        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.1.0        |
| fastimage                       | 2.2.5        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.1.0        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.1.4        |
| simctl                          | 1.6.8        |
| jwt                             | 2.2.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.1        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| signet                          | 0.15.0       |
| googleauth                      | 0.17.0       |
| httpclient                      | 2.8.3        |
| webrick                         | 1.4.2        |
| google-apis-core                | 0.4.1        |
| google-apis-playcustomapp_v1    | 0.5.0        |
| google-apis-androidpublisher_v3 | 0.10.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.6.0        |
| google-apis-storage_v1          | 0.6.0        |
| rake                            | 12.3.2       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.34.1       |
| emoji_regex                     | 3.2.2        |
| jmespath                        | 1.4.0        |
| aws-partitions                  | 1.484.0      |
| aws-eventstream                 | 1.1.1        |
| aws-sigv4                       | 1.2.4        |
| aws-sdk-core                    | 3.119.0      |
| aws-sdk-kms                     | 1.46.0       |
| aws-sdk-s3                      | 1.98.0       |
| forwardable                     | 1.2.0        |
| logger                          | 1.3.0        |
| date                            | 2.0.0        |
| stringio                        | 0.0.2        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.0.0        |
| mutex_m                         | 0.1.0        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| io-console                      | 0.4.7        |
| fileutils                       | 1.1.0        |
| etc                             | 1.0.1        |
| racc                            | 1.5.2        |
| nokogiri                        | 1.12.3       |
| psych                           | 3.1.0        |
| fastlane-plugin-appicon         | 0.16.0       |
| fastlane-plugin-versioning      | 0.5.0        |
| fastlane-plugin-sentry          | 1.9.0        |
</details>

*generated on:* **2021-09-08**
</details>
[09:44:40]: [33mTake notice that this output may contain sensitive information, or simply information that you don't want to make public.[0m
[09:44:40]: [32mOpen https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅[0m

 </pre>
</details>

**Comment by gelodgreat** [comment]
updated the environment

**Comment by Nightstep** [comment]
The same here, fastlane version 2.193.1
`Spaceship::UnexpectedResponse: [!] The specified resource does not exist - There is no resource of type 'appStoreReviewDetail' with id '008881d7-185a-464e-93aa-7bc919b22e5e'`

**Comment by aroyzen1983** [comment]
Running into the same issue. Is there time line when it could be fixed?

**Comment by dave-filion** [comment]
Same here, get this fairly frequently and randomly on several different calls.
