### ISSUE TITLE
Integration with OCLint?

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1934]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/450923?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @TiagoVeloso - Imported from <a href='https://github.com/fastlane/scan/issues/74'>fastlane/scan#74</a>
        </td>
      </tr>
    </table>

`xctool` has a reporter option to generate `compile_commands.json`that can be used by `OCLint`

Does `scan` offer the same option? How do I achieve that?

**Comment by mfurtak** [comment]
We've addressed this with https://github.com/fastlane/fastlane/pull/4992, which will go out with the next release 🚀

**Comment by mfurtak** [comment]
This is released as part of [`scan` 0.8.0](https://github.com/fastlane/fastlane/releases/tag/scan%2F0.8.0) 🎉
