### ISSUE TITLE
[regression] pilot distribute_external asks for app_platform in non-interactive mode

### ISSUE THREAD

**Issue by kurtmc** [fastlane/fastlane#19351]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I have a lane setup that looks like this:
```ruby
  desc "Deploy to TestFlight external"
  lane :beta do
    pilot(
      wait_processing_interval: 100,
      distribute_external: true,
    )
  end
```

on version 2.192.0 this was working and since 2.193.1 it's no longer working I am getting the following in the logs, asking me for app platform (I am running this in a CI system):
```
[17:28:16]: Login successful
[17:28:16]: No build specified - fetching latest build
[17:28:16]: Please enter the app's platform (appletvos, ios, osx): 

Looking for related GitHub issues on fastlane/fastlane...

➡️  Metadata Path is not considered
    https://github.com/fastlane/fastlane/issues/18321 [closed] 7 💬
    5 weeks ago

➡️  GITLAB CI: Could not retrieve response as fastlane runs in non-interactive mode
    https://github.com/fastlane/fastlane/issues/17376 [closed] 18 💬
    17 Feb 2021

➡️  FastlaneCore::Interface::FastlaneCrash: [!] Could not retrieve response as fastlane runs in non-interactive mode
    https://github.com/fastlane/fastlane/issues/17488 [closed] 11 💬
    16 Jan 2021

and 53 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
FastlaneCore::Interface::FastlaneCrash: [!] Could not retrieve response as fastlane runs in non-interactive mode
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:170:in `verify_interactive!'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:129:in `input'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/pilot/lib/pilot/manager.rb:88:in `fetch_app_platform'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/pilot/lib/pilot/build_manager.rb:149:in `distribute'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/pilot/lib/pilot/commands_generator.rb:79:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/pilot/lib/pilot/commands_generator.rb:167:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/pilot/lib/pilot/commands_generator.rb:19:in `start'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/bin/fastlane:23:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>'

```

##### Command executed

```
bundle exec fastlane pilot distribute --distribute_external true --groups Beta
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
[✔] 🚀 
[17:28:14]: Login to App Store Connect (xxxxxxxxxxxxxxxxxxxxxxxxxxxx)
Available session is not valid any more. Continuing with normal login.
Session loaded from environment variable is not valid. Continuing with normal login.
[17:28:16]: Login successful
[17:28:16]: No build specified - fetching latest build
[17:28:16]: Please enter the app's platform (appletvos, ios, osx): 

Looking for related GitHub issues on fastlane/fastlane...

➡️  Metadata Path is not considered
    https://github.com/fastlane/fastlane/issues/18321 [closed] 7 💬
    5 weeks ago

➡️  GITLAB CI: Could not retrieve response as fastlane runs in non-interactive mode
    https://github.com/fastlane/fastlane/issues/17376 [closed] 18 💬
    17 Feb 2021

➡️  FastlaneCore::Interface::FastlaneCrash: [!] Could not retrieve response as fastlane runs in non-interactive mode
    https://github.com/fastlane/fastlane/issues/17488 [closed] 11 💬
    16 Jan 2021

and 53 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
FastlaneCore::Interface::FastlaneCrash: [!] Could not retrieve response as fastlane runs in non-interactive mode
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:170:in `verify_interactive!'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:129:in `input'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/pilot/lib/pilot/manager.rb:88:in `fetch_app_platform'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/pilot/lib/pilot/build_manager.rb:149:in `distribute'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/pilot/lib/pilot/commands_generator.rb:79:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/pilot/lib/pilot/commands_generator.rb:167:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/pilot/lib/pilot/commands_generator.rb:19:in `start'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.193.1/bin/fastlane:23:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>'

  </pre>
</details>

### Environment

<details>
  <pre>
[✔] 🚀 
[17:28:08]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.7                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.7 (19H2)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.0.1                                                         |
| Swift Version               | 5.3                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform(:ios)

platform :ios do

  desc "Deploy to TestFlight internal"
  lane :alpha do
    match(
      git_url: "XXXXXXXXXXXXXXXXXXXXXXXXXXX",
      type: "appstore",
      readonly: is_ci,
      keychain_password: ENV["SUDO_PASSWORD"],
    )
    settings_to_override = {
      :PROVISIONING_PROFILE_SPECIFIER => "match AppStore example.com",
      :DEVELOPMENT_TEAM => "xxxxxxxxxx"
    }
    disable_automatic_code_signing
    update_app_identifier(
      plist_path: "MyCompany/Info.plist",
      app_identifier: "example.com"
    )
    update_project_team(
      path: "MyCompany.xcodeproj",
      teamid: "xxxxxxxxxx"
    )
    set_info_plist_value(path: "MyCompany/Info.plist", key: "CFBundleVersion", value: ENV["BUILD_NUMBER"])
    increment_version_number(version_number: ENV["VERSION_NUMBER"])
    cocoapods()
    gym(
      codesigning_identity: "iPhone Distribution",
      scheme: "MyCompany",
      xcargs: settings_to_override,
      export_method: "app-store",
      export_options: {
        distributionBundleIdentifier: "example.com",
        provisioningProfiles: {
          "example.com" => "match AppStore example.com",
        }
      },
      output_directory: ENV["OUTPUT_DIRECTORY"],
      output_name: ENV["OUTPUT_NAME"],
    )
    pilot(wait_processing_interval: 100)
  end

  desc "Deploy to TestFlight external"
  lane :beta do
    pilot(
      wait_processing_interval: 100,
      distribute_external: true,
    )
  end

  desc "Deploy to App Store"
  lane :production do
    deliver(
      build_number: ENV["BUILD_NUMBER"],
      submit_for_review: true,
      automatic_release: true,
      force: true, # Skip HTMl report verification
      skip_binary_upload: true,
      price_tier: 0,
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "example.com" # The bundle identifier of your app
apple_id "xxxxxxxxxxxxxxxxxxxxxxxxxxxx"  # Your Apple email address
team_id "xxxxxxxxxx"

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.193.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| bundler                         | 1.17.2       |
| etc                             | 1.0.1        |
| forwardable                     | 1.2.0        |
| rake                            | 13.0.6       |
| CFPropertyList                  | 3.0.3        |
| concurrent-ruby                 | 1.1.9        |
| i18n                            | 1.8.10       |
| minitest                        | 5.14.4       |
| tzinfo                          | 2.0.4        |
| zeitwerk                        | 2.4.2        |
| activesupport                   | 6.1.4.1      |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| httpclient                      | 2.8.3        |
| json                            | 2.5.1        |
| algoliasearch                   | 1.27.5       |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.496.0      |
| aws-sigv4                       | 1.4.0        |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.121.0      |
| aws-sdk-kms                     | 1.48.0       |
| aws-sdk-s3                      | 1.102.0      |
| babosa                          | 1.0.4        |
| claide                          | 1.0.3        |
| fuzzy_match                     | 2.0.4        |
| nap                             | 1.1.0        |
| netrc                           | 0.11.0       |
| ffi                             | 1.15.4       |
| ethon                           | 0.14.0       |
| typhoeus                        | 1.4.0        |
| cocoapods-core                  | 1.11.0       |
| cocoapods-deintegrate           | 1.0.5        |
| cocoapods-downloader            | 1.5.0        |
| cocoapods-plugins               | 1.0.0        |
| cocoapods-search                | 1.0.1        |
| cocoapods-trunk                 | 1.6.0        |
| cocoapods-try                   | 1.2.0        |
| colored2                        | 3.1.2        |
| escape                          | 0.0.4        |
| fourflusher                     | 2.3.1        |
| gh_inspector                    | 1.1.3        |
| molinillo                       | 0.8.0        |
| ruby-macho                      | 2.5.1        |
| nanaimo                         | 0.3.0        |
| rexml                           | 3.2.5        |
| xcodeproj                       | 1.21.0       |
| cocoapods                       | 1.11.0       |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.2        |
| excon                           | 0.85.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| multipart-post                  | 2.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.7.1        |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.1.0        |
| fastimage                       | 2.2.5        |
| jwt                             | 2.2.3        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| signet                          | 0.16.0       |
| googleauth                      | 0.17.1       |
| mini_mime                       | 1.1.1        |
| trailblazer-option              | 0.1.1        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-androidpublisher_v3 | 0.10.0       |
| google-apis-playcustomapp_v1    | 0.5.0        |
| google-apis-iamcredentials_v1   | 0.7.0        |
| google-apis-storage_v1          | 0.6.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.34.1       |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
</details>

*generated on:* **2021-09-03**

  </pre>
</details>

**Comment by lucgrabowski** [comment]
Hi, is build that you want to distribute available on the server? If it is, fastlane should figure out the platform parameter based on that build. If it's not available, you could add an `app_platform` parameter (`appletvos`, `ios`, or `osx`)

**Comment by kurtmc** [comment]
That command is not run in the same directory as build. I have added `app_platform: "ios"` to the `pilot` call and I get the same error.

**Comment by acoutts** [comment]
Getting the same error now too.

**Comment by acoutts** [comment]
Even if I pass the platform in the command too, it still has this issue. Is there a workaround?

**Comment by kurtmc** [comment]
This is still an issue for me.

**Comment by dcacenabes** [comment]
For us, adding `app_platform: "ios"` to the parameters made the trick

**Comment by antonysouthworth-halter** [comment]
I am experiencing this on 2.199.0 also (same config as @kurtmc)

**Comment by niharaminwahoo** [comment]
commenting to keep it going, also having the same issue. It's an optional parameter in the documents. https://docs.fastlane.tools/actions/pilot/

**Comment by bartekpacia** [comment]
This occurred to me today.
