### ISSUE TITLE
Returning the test result

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1935]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/9826047?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @dalu93 - Imported from <a href='https://github.com/fastlane/scan/issues/72'>fastlane/scan#72</a>
        </td>
      </tr>
    </table>

Hi,
Is there a way to manage the test result directly on `Fasfile`? For example, I was expecting there was a variable into `lane_context`, but I can't find it.
This is what I want to do

    scan(
        ...
    )

    if test_result
        testflght(
            ...
        )
    end

**Comment by dreyhomedev** [comment]
I just ended up to parse the junit file created by scan. As far as I saw in the scan source code it's also using this approach to report success or failure when using the slack posting option of scan.

I used `Crack` gem to parse the junit xml file to json and build a simple class that monitors the required information about the tests.
