### ISSUE TITLE
Pilot action sets the wrong build number for Xcode 13 beta Testflight builds

### ISSUE THREAD

**Issue by MohgaNabil** [fastlane/fastlane#19352]
##### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the Contribution Guidelines
- [x] I read docs.fastlane.tools
- [x] I searched for existing GitHub issues

##### Issue Description
Hi!
Well, the team is currently prepping our apps for iOS 15. We noticed that build number is not set properly on all the builds created using Xcode 13 beta 5, particularly when uploaded to test flight (see screenshots below).

For versioning in general, we're using the fastlane step`increment_build_number` (see screenshots below) which is working as expected with builds created using Xcode 12.5.1 . 
It's also worth menthotioning that we've tried setting the `build_number` on the `pilot` step explicitly, but didn't work as well.

We're not sure what has changed with Xcode 13 around app/build versioning that we need to adapt accordingly, so would appreciate some help. Thanks!

##### Command executed
<details>
This's the pilot command used in our fastlane pod:

> pilot(
>       api_key_path: ENV['ASC_KEY_PATH'],
>       app_identifier: app_identifier,
>       changelog: ENV['NOTES'],
>       ipa: absolut_ipa_path,
>       wait_processing_interval: 180, 
>       groups: groups,
>      build_number: build_nr  # value is: 6.5.0.3887
>     )

![Screenshot 2021-09-15 at 10 56 08 AM](https://user-images.githubusercontent.com/12371520/133404685-18842089-01ff-42db-9708-33c17061138a.png)
![Screenshot 2021-09-15 at 10 42 05 AM](https://user-images.githubusercontent.com/12371520/133404705-b055f96f-b860-4bb2-9bca-c43676980d76.png)

</details>

### Environment
<details>
  <pre>
  <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.4                                        |
| Ruby                        | 3.0.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.31.1                          |
| Installation Source         | ~/.rvm/gems/ruby-3.0.2/bin/fastlane         |
| Host                        | macOS 11.4 (20F71)                          |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-3.0.2/lib                |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.4                                        |
| Swift Version               | 5.3.2                                       |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.193.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                      | Version | Update-Status |
| ------------------------------------------- | ------- | ------------- |
| fastlane-plugin-upload_symbols_to_new_relic | 0.1.1   | ✅ Up-To-Date  |

*generated on:* **2021-09-15**
</details> 
   </pre>
</details>

**Comment by MohgaNabil** [comment]
Also worth mentionting that our apps versioning setup follows the guidelines mentioned [here](https://developer.apple.com/library/archive/qa/qa1827/_index.html).
And, I'm not entirely sure if this is relevant to this [issue](https://github.com/fastlane/fastlane/issues/15383)

**Comment by pd95** [comment]
I see similar problems with a new project I've created using Xcode 13. 
When uploading it with pilot, I don't have a VERSION_NUMBER set because it cannot be detected.
I'm now debugging the `get_version_number` action...

Important note: New in Xcode 13 there is not necessarily a Info.plist file containing all the information which fastlane might rely on. Xcode 13 has a target configuration `Generate Info.plist File` which is enabled for new projects (therefore you won't find such a file in a new project)

The issue you've found is dated from Xcode 11 where the `MARKETING_VERSION` configuration has been introduced to Xcode and the `CFBundleShortVersionString` was referring to it.
In my Xcode 13 project there is no CFBundleShortVersionString in Info.plist... Looking for this setting in "Build Settings" highlights the **Marketing Version** setting.
IMO fastlane should fall back to get the `MARKETING_VERSION` build setting whenever it was unable to find a `CFBundleShortVersionString`.

**Comment by pd95** [comment]
Just something else: Apples `agvtool` seems to be unable to find the marketing version if it is only in the Xcode project

```
% agvtool what-marketing-version

No marketing version number (CFBundleShortVersionString) found for Jambase targets.

Looking for marketing version in native targets...
Looking for marketing version (CFBundleShortVersionString) in native targets...

Cannot find "Learn It.xcodeproj/../YES"
Found CFBundleShortVersionString of "" in "Learn It.xcodeproj/../iOS/Info.plist" 
Found CFBundleShortVersionString of "" in "Learn It.xcodeproj/../macOS/Info.plist" 
```

So perhaps Apples `agvtool` & Xcode 13.0 have some issues and are not yet ready for fastlane?

**Comment by pd95** [comment]
The fix I made in https://github.com/pd95/fastlane/commit/d1153132706e49f52d7817f1789de124d33379e8 here, did solve the issue for me. I don't know if you have a possibility to test it yourself.

**Comment by MohgaNabil** [comment]
Thanks a lot for taking the time to help! I gave your branch a try, but the problem still persists. I can still see that build_number is wrongly set on Testflight with the pilot step.  Not sure why the pattern changes with Xcode 13 builds, would be happy to provide additional insights/logs upon request. Thanks again!
<img width="211" alt="Screenshot 2021-09-16 at 6 31 52 PM" src="https://user-images.githubusercontent.com/12371520/133651246-c8a72767-48af-432b-8fd1-cbe18fdc0395.png">

**Comment by pd95** [comment]
Hmm... I've looked into `pilot.rb` and `build_manager.rb` and it seems as if the `build_number` argument is only used if you have no `ipa` or `pkg` parameter set: https://github.com/fastlane/fastlane/blob/a5616116d0e686a6975321bc38a51b5ce1e3c056/pilot/lib/pilot/build_manager.rb#L99-L110

As you have an IPA specified: could you check what version (`CFBundleVersionString` and `CFBundleShortVersionString`) are set in the `Info.plist`? If it is wrong in the IPA we would have to fix it there and not in the upload/pilot part.

**Comment by alexsteinerde** [comment]
I have the same issue. In Xcode 13 I have the option to not manage build versions automatically (Default is on). If I disable this I can upload the build manually. 
Is there such an option for fastlane and Xcode 13?

**Comment by SofteqDG** [comment]
We should add new option into export_options to disable automatic version set. This options is called:
```
manageAppVersionAndBuildNumber
```

This is the output from xcodebuild --help:
```
	manageAppVersionAndBuildNumber

		Should Xcode manage the app's build number when uploading to App Store Connect? Defaults to YES.
```

**Comment by alexsteinerde** [comment]
That would be optimal. 
Do you have any recommendation what I could do in the mean time to fix my build scripts? 
Can I set this option from the outside via an environment variable or something else?

**Comment by SofteqDG** [comment]
> That would be optimal.
> Do you have any recommendation what I could do in the mean time to fix my build scripts?
> Can I set this option from the outside via an environment variable or something else?

Well, i'm using build_ios_app action to build my apps. This action is an alias for the build_app action. Actually gym is also an alias for build_app action. As far as i know this action is responsible for building xcarchive and ipa. You can set export_options parameter to this action to disable new behavior introduced in Xcode 13. Here is an example from my project:
```
    build_ios_app(
      workspace: "test.xcworkspace",
      export_options: {
        compileBitcode: false,
        uploadBitcode: false,
        uploadSymbols: true,
        manageAppVersionAndBuildNumber: false
      }
    )
```

**Comment by MohgaNabil** [comment]
Thanks a lot for taking the time to look into it! I've tried the `export_option` approach and that does the trick 👍
