### ISSUE TITLE
Adding a timeout option

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1936]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/12499583?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @n4me1ess - Imported from <a href='https://github.com/fastlane/scan/issues/67'>fastlane/scan#67</a>
        </td>
      </tr>
    </table>

I am running XC UI tests. Often they are stucking because of simulator is not responding. The scan process  wait a long time. **Is there some way to terminate testing by timeout and generate report as is?**
Also, My console output says me nothing about some problem with sim:
`[...]testRemoveUnsentItem (60.486 seconds)
2015-12-23 20:20:07.946 xcodebuild[61490:7264664] [MT] IDETestOperationsObserverDebug: (2CDF552D-23BF-4484-87CF-355405801581) Beginning test session 2CDF552D-23BF-4484-87CF-355405801581 with Xcode 7C62b on target <DVTiPhoneSimulator: 0x7fdae6796a40> {
SimDevice: SimDevice : iPad 2 (A09BF579-8C13-418D-B035-BAD8A29C0BEE) : state={ Booted } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPad-2 } runtime={ SimRuntime : 9.2 (13C70) - com.apple.CoreSimulator.SimRuntime.iOS-9-2 }
} (9.2 (13C70))`

**Comment by KrauseFx** [comment]
Sorry for not coming back to this earlier, is this issue still happening with the latest _fastlane_ release?
