### ISSUE TITLE
Fastlane not use profiles that i set in `provisioningProfiles:` of `export_options:`. It always use the profiles that i set in `TARGETS` of my `Project`

### ISSUE THREAD

**Issue by GuoZhiQiang** [fastlane/fastlane#19378]
I define a `lane` like this:
   
```
lane :appstore_lane do
    gym(
        clean: true,
        scheme:"XY",
        export_method:"app-store",
        configuration:"Release",
        output_directory:"./fastlane/build",
        output_name:"XY.ipa",
        export_xcargs: "-allowProvisioningUpdates",
        export_options: {
          iCloudContainerEnvironment: "Production",
          provisioningProfiles: {
            "com.cc.XY": "profile_DIS",
            "com.cc.XY.NotificationService": "dis_pushProfile" 
          }
        }
     )
  end
```

In my project，the `Provisoning Profile` for App Store of `XY` targets and `NotificationService` targets are  respectively `dev_Profile` and `dev_notificationService_profile`.

![image](https://user-images.githubusercontent.com/9813791/134640159-fb157945-3694-4424-8fdf-c4ffc18104e7.png)

When i run `fastlane appstore_lane`, I got the error as: 
```
"Provisioning profile "dev_Profile" is not an "iOS App Store" profile."
```

Fastlane do not use `profile_DIS` and `dis_pushProfile` for App Store I declare in parameter `provisioningProfiles` but use the set in `project.pbxproj`. 

I know  set `dev_Profile` and `dev_notificationService_profile` for App Store is wrong, but why do fastlane  not use  the profiles i declared in `provisioningProfiles` ?

**Comment by StNebel** [comment]
same ...

**Comment by StNebel** [comment]
In my case, "Secondary provisioning profile mapping" even uses a profile from another target. Although I limited it to 5 profiles of the main target in the export options.

My guess is that fastlane cannot find a configuration that is assigned to a target in a build configuration.
In my case:
Configuration name: "Store Release"
in it the project: "PROJECT1"
in it the AppTarget: "MyApp1" 

<img width="539" alt="grafik" src="https://user-images.githubusercontent.com/54270778/135916814-82be1702-dd8d-4f13-b229-9aa0d1a4f420.png">


<img width="119" alt="grafik" src="https://user-images.githubusercontent.com/54270778/135916702-3d9886b4-ff25-4264-a8cf-64c77be08743.png">

Its a Projekt with 3 App-Targets .. and one target each for unit and UI tests

**Comment by StNebel** [comment]
https://github.com/fastlane/fastlane/issues/17231

**Comment by StNebel** [comment]
**WORKAROUND** for multiple Targets:

1. Create ExportOptions -  provisioning profiles from your specific target (use `GYM_EXPORT_OPTIONS` inside a env)
2. Stop wrong automapping from fastline by `build_app` set `GYM_CONFIGURATION = "WORKAROUND MOCK NAME"`

**done**
only the primary profiles from ExportOptions are used for the mapping. 
Secondary provisioning profile mapping is now empy

**Comment by mxs** [comment]
I am seeing the same thing except i am using a plist
`export_options: "./ProductionExportOptions.plist",`
