### ISSUE TITLE
Add support to share test results for use in other actions

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1937]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/7799267?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @kdawgwilk - Imported from <a href='https://github.com/fastlane/scan/issues/57'>fastlane/scan#57</a>
        </td>
      </tr>
    </table>

It would be great if the tests results were shared so they could be used in other actions to allow for keeping analytics or forming custom messages to team chat.

**Comment by dreyhomedev** [comment]
#1935
