### ISSUE TITLE
Scan should use scheme setting for code coverage

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1938]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/661647?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @mackoj - Imported from <a href='https://github.com/fastlane/scan/issues/52'>fastlane/scan#52</a>
        </td>
      </tr>
    </table>

Hi,

I think `scan` should use scheme setting for code coverage by default and maybe be overladed by `code_coverage` setting.

Cheers,

**Comment by mackoj** [comment]
https://github.com/nakiostudio/xcov works great for analysing test data
