### ISSUE TITLE
Codesign Error on build ios application managed by match 

### ISSUE THREAD

**Issue by YonaLugassi** [fastlane/fastlane#19389]
### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.194.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| bundler                         | 2.2.23       |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.4        |
| concurrent-ruby                 | 1.1.9        |
| i18n                            | 1.8.10       |
| minitest                        | 5.14.4       |
| tzinfo                          | 2.0.4        |
| zeitwerk                        | 2.4.2        |
| activesupport                   | 6.1.4.1      |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| httpclient                      | 2.8.3        |
| json                            | 2.5.1        |
| algoliasearch                   | 1.27.5       |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.506.0      |
| aws-sigv4                       | 1.4.0        |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.121.1      |
| aws-sdk-kms                     | 1.48.0       |
| aws-sdk-s3                      | 1.103.0      |
| babosa                          | 1.0.4        |
| claide                          | 1.0.3        |
| fuzzy_match                     | 2.0.4        |
| nap                             | 1.1.0        |
| netrc                           | 0.11.0       |
| ffi                             | 1.15.4       |
| ethon                           | 0.14.0       |
| typhoeus                        | 1.4.0        |
| cocoapods-core                  | 1.11.2       |
| cocoapods-deintegrate           | 1.0.5        |
| cocoapods-downloader            | 1.5.1        |
| cocoapods-plugins               | 1.0.0        |
| cocoapods-search                | 1.0.1        |
| cocoapods-trunk                 | 1.6.0        |
| cocoapods-try                   | 1.2.0        |
| colored2                        | 3.1.2        |
| escape                          | 0.0.4        |
| fourflusher                     | 2.3.1        |
| gh_inspector                    | 1.1.3        |
| molinillo                       | 0.8.0        |
| ruby-macho                      | 2.5.1        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| cocoapods                       | 1.11.2       |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.2        |
| excon                           | 0.85.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| multipart-post                  | 2.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.8.0        |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.1.0        |
| fastimage                       | 2.2.5        |
| jwt                             | 2.2.3        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| signet                          | 0.16.0       |
| googleauth                      | 0.17.1       |
| mini_mime                       | 1.1.1        |
| trailblazer-option              | 0.1.1        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-androidpublisher_v3 | 0.11.0       |
| google-apis-playcustomapp_v1    | 0.5.0        |
| google-apis-iamcredentials_v1   | 0.7.0        |
| google-apis-storage_v1          | 0.7.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.34.1       |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
</details>

*generated on:* **2021-09-26**
</details>

### Issue Description
I'm using with match command to manage my certificates and I store them on s3 bucket, everything looks ok when I run the match command.
I'm trying to build and upload my application to TestFligth and I got the error 
```
The following build commands failed:
	PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/ec2-user/Library/Developer/Xcode/DerivedData/..../Script-xxxxxx.sh
(1 failure)
[14:58:50]: Exit status: 65
```

#log file output 
```
sent 42111409 bytes  received 70 bytes  28074319.33 bytes/sec
total size is 42106044  speedup is 1.00
Stripped /Users/ec2-user/Library/Developer/Xcode/DerivedData/<App>/<App>.app/Frameworks/OpenSSL.framework/OpenSSL of architectures: armv7 armv7s arm64e
Code Signing /Users/ec2-user/Library/Developer/Xcode/DerivedData/...../Applications/Next.app/Frameworks/OpenSSL.framework with Identity Apple Distribution: xxxxx. (XXXXXXXX)
/usr/bin/codesign --force --sign xxxxxx  --preserve-metadata=identifier,entitlements '/Users/ec2-user/Library/Developer/Xcode/DerivedData/......../Applications/Next.app/Frameworks/OpenSSL.framework'
Warning: unable to build chain to self-signed root for signer "Apple Distribution: xxxxx. (xxxxxxx)"
/Users/ec2-user/Library/Developer/Xcode/DerivedData/........../Applications/Next.app/Frameworks/OpenSSL.framework: errSecInternalComponent
Command PhaseScriptExecution failed with a nonzero exit code.
```

I give permissions on my ci machine (MacOs)  to access the new certificate and no errors appear on the Xcode when I checked the Code singing configuration for debug and release.

Here is my Fastfile lane that I'm using to build and upload to TestFligth: 

```ruby
desc "Push a new release build to the TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "MyApp.xcodeproj")
    match(type: "development", app_identifier: "com.<my company>" )
    match(type: "appstore",  app_identifier: "com.<my company>" )
    cocoapods(clean_install: true)
    build_ios_app(workspace: "MyApp.xcworkspace", scheme: "MyApp", clean: true)
    upload_to_testflight(
       skip_waiting_for_build_processing: true
    )
    clean_build_artifacts
  end
```
I'm trying to fix it for 2 days, What could be wrong?

**Comment by YonaLugassi** [comment]
I found that the same certificates that were created on the ci machine were fine.
I run the same configuration on my mac and it was built the application successfully .
I forgot to say that my ci machine runs on AWS EC2 MacOs instance, Are there any known issues related to AWS  MacOs instances?

**Comment by normanzb** [comment]
We are having exact same issue after updated distribution certificate, did you figure out what's going on?

**Comment by burtsevyg** [comment]
Same problem, after create key chain for match and add 
```
gym(
   export_method: "app-store"
)
```

**Comment by burtsevyg** [comment]
Reboot my mac fix the problem.
