### ISSUE TITLE
scan hangs after running tests (process doesn't exit; I'm not returned to the shell)

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1939]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/7117366?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @alex-hunsley-zonal - Imported from <a href='https://github.com/fastlane/scan/issues/49'>fastlane/scan#49</a>
        </td>
      </tr>
    </table>

I'm using scan to run my iOS app tests. I'm invoking it merely as 'scan' in the root of my iOS project. It runs all the tests but then just hangs. By 'hang' I mean that control isn't returned to the shell, I have to do CTRL-C.

When I do CTRL-C I see the following text:

```

        Executed 181 tests, with 0 failures (0 unexpected) in 41.231 (45.663) seconds


^C/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.27.0/lib/fastlane_core/command_executor.rb:27:in `each': Interrupt
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.27.0/lib/fastlane_core/command_executor.rb:27:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.27.0/lib/fastlane_core/command_executor.rb:26:in `spawn'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.27.0/lib/fastlane_core/command_executor.rb:26:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.3.2/lib/scan/runner.rb:23:in `test_app'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.3.2/lib/scan/runner.rb:9:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.3.2/lib/scan/manager.rb:10:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.3.2/lib/scan/commands_generator.rb:41:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.3.2/lib/scan/commands_generator.rb:60:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.3.2/lib/scan/commands_generator.rb:14:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.3.2/bin/scan:6:in `<top (required)>'
	from /usr/bin/scan:23:in `load'
	from /usr/bin/scan:23:in `<main>'
```

I've tried invoking scan by using fastlane and a Fastfile and the same thing happens.

**Comment by mkujalowicz** [comment]
I had the same problem until I figured out that it wasn't a problem with fastlane but with xcodebuild. After upgrading to cocoapods 1.0 my unit tests stopped working due to problems with rpaths and dynamic module dependencies. After fixing it, scan automatically was able to finish the process.

**Comment by TKBurner** [comment]
Thanks for letting us know @mkujalowicz! Can you let me know what versions of cocoapods you are on now? Thanks!

**Comment by mkujalowicz** [comment]
@TKBurner I'm using version 1.0 of cocoapods. More info on problems with running unit tests against pod frameworks you can find here: https://github.com/CocoaPods/CocoaPods/issues/5340

**Comment by TKBurner** [comment]
@mkujalowicz Thanks!
