### ISSUE TITLE
XCode 13: R.generated.swift was modified during the build

### ISSUE THREAD

**Issue by hibernat** [fastlane/fastlane#19394]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by tonysms** [comment]
same here

**Comment by EmDee** [comment]
This has nothing to do with `fastlane`, but is a problem of Xcode 13. `R.swift` even has a ticket about that: https://github.com/mac-cain13/R.swift/issues/719

The solution (mentioned in https://github.com/mac-cain13/R.swift/issues/719#issuecomment-937733804) is to wrap the R.swift command:

```
if [ $ACTION != "indexbuild" ]; then
  "$SRCROOT/scripts/rswift" generate "$SRCROOT/R.generated.swift" 
fi
```

Or just update to R.swift 6.0.0, where this problem has been solved internall.
