### ISSUE TITLE
'No profiles found' on XCode 13

### ISSUE THREAD

**Issue by jacobokoenig** [fastlane/fastlane#19406]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
After upgrading Xcode to v. 13, fastlane shows an error when exporting the archive:

`Error Domain=IDEProfileLocatorErrorDomain Code=1 "No profiles for 'com.--.--' were found" UserInfo={IDEDistributionIssueSeverity=3, NSLocalizedDescription=No profiles for ''com.--.--' were found, NSLocalizedRecoverySuggestion=Xcode couldn't find any iOS App Store provisioning profiles matching 'com.--.--'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.}`

Automatic signing is indeed enabled (which I've turned off and back on to test as well).

##### Command executed
`lane :beta do
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight
  end`

##### Complete output when running fastlane, including the stack trace and command used
[13:16:46]: ▸ Archive Succeeded
[13:16:46]: Generated plist file with the following values:
[13:16:46]: ▸ -----------------------------------------
[13:16:46]: ▸ {
[13:16:46]: ▸   "method": "app-store"
[13:16:46]: ▸ }
[13:16:46]: ▸ -----------------------------------------
[13:16:46]: $ /usr/bin/xcrun /Library/Ruby/Gems/2.6.0/gems/fastlane-2.195.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/cb/4g9bljkn1wg4ctpxygjbj4p80000gn/T/gym_config20210929-35730-at89dr.plist' -archivePath /Users/jacobokoenig/Library/Developer/Xcode/Archives/2021-09-29/Runner\ 2021-09-29\ 13.12.56.xcarchive -exportPath '/var/folders/cb/4g9bljkn1wg4ctpxygjbj4p80000gn/T/gym_output20210929-35730-mbb7ha' 
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/cb/4g9bljkn1wg4ctpxygjbj4p80000gn/T/gym_config20210929-35730-at89dr.plist -archivePath '/Users/jacobokoenig/Library/Developer/Xcode/Archives/2021-09-29/Runner 2021-09-29 13.12.56.xcarchive' -exportPath /var/folders/cb/4g9bljkn1wg4ctpxygjbj4p80000gn/T/gym_output20210929-35730-mbb7ha
2021-09-29 13:16:47.826 xcodebuild[43090:4141397] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path "/var/folders/cb/4g9bljkn1wg4ctpxygjbj4p80000gn/T/Runner_2021-09-29_13-16-47.826.xcdistributionlogs".
2021-09-29 13:16:48.460 xcodebuild[43090:4141498] CFURLRequestSetHTTPCookieStorageAcceptPolicy_block_invoke: no longer implemented and should not be called
error: exportArchive: No profiles for 'com.whering.app.OneSignalNotificationServiceExtension' were found

Error Domain=IDEProfileLocatorErrorDomain Code=1 "No profiles for 'com.whering.app.OneSignalNotificationServiceExtension' were found" UserInfo={IDEDistributionIssueSeverity=3, NSLocalizedDescription=No profiles for 'com.whering.app.OneSignalNotificationServiceExtension' were found, NSLocalizedRecoverySuggestion=Xcode couldn't find any iOS App Store provisioning profiles matching 'com.whering.app.OneSignalNotificationServiceExtension'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.}

error: exportArchive: No profiles for 'com.whering.app.Share-Extension' were found

Error Domain=IDEProfileLocatorErrorDomain Code=1 "No profiles for 'com.whering.app.Share-Extension' were found" UserInfo={IDEDistributionIssueSeverity=3, NSLocalizedDescription=No profiles for 'com.whering.app.Share-Extension' were found, NSLocalizedRecoverySuggestion=Xcode couldn't find any iOS App Store provisioning profiles matching 'com.whering.app.Share-Extension'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.}

error: exportArchive: No profiles for 'com.whering.app' were found

Error Domain=IDEProfileLocatorErrorDomain Code=1 "No profiles for 'com.whering.app' were found" UserInfo={IDEDistributionIssueSeverity=3, NSLocalizedDescription=No profiles for 'com.whering.app' were found, NSLocalizedRecoverySuggestion=Xcode couldn't find any iOS App Store provisioning profiles matching 'com.whering.app'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.}

** EXPORT FAILED **
[13:16:55]: Exit status: 70

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.5                                                           |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.30.1 (Apple Git-130)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.5 (20G71)                                             |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 13.0                                                           |
| Swift Version               | 5.5                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.195.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| atomos                          | 0.1.3        |
| CFPropertyList                  | 2.3.6        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.19.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.5.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.78.0       |
| ruby2_keywords                  | 0.0.2        |
| faraday                         | 1.1.0        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.3        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.0.0        |
| fastimage                       | 2.2.0        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.1.0        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.0        |
| rubyzip                         | 2.3.0        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.0        |
| dotenv                          | 2.7.6        |
| simctl                          | 1.6.8        |
| jwt                             | 2.2.2        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| declarative-option              | 0.1.0        |
| representable                   | 3.0.4        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.0.2        |
| multi_json                      | 1.15.0       |
| signet                          | 0.14.0       |
| memoist                         | 0.16.2       |
| os                              | 1.1.1        |
| googleauth                      | 0.14.0       |
| httpclient                      | 2.8.3        |
| rexml                           | 3.1.9        |
| webrick                         | 1.4.2        |
| google-apis-core                | 0.3.0        |
| google-apis-playcustomapp_v1    | 0.2.0        |
| google-apis-androidpublisher_v3 | 0.3.0        |
| google-cloud-env                | 1.4.0        |
| google-cloud-errors             | 1.0.1        |
| google-cloud-core               | 1.5.0        |
| google-apis-iamcredentials_v1   | 0.3.0        |
| google-apis-storage_v1          | 0.3.0        |
| rake                            | 13.0.1       |
| digest-crc                      | 0.6.1        |
| google-cloud-storage            | 1.31.1       |
| emoji_regex                     | 3.2.1        |
| jmespath                        | 1.4.0        |
| aws-partitions                  | 1.395.0      |
| aws-eventstream                 | 1.1.0        |
| aws-sigv4                       | 1.2.2        |
| aws-sdk-core                    | 3.109.3      |
| aws-sdk-kms                     | 1.39.0       |
| aws-sdk-s3                      | 1.84.1       |
| bundler                         | 2.1.2        |
| forwardable                     | 1.2.0        |
| logger                          | 1.3.0        |
| stringio                        | 0.0.2        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| date                            | 2.0.0        |
| io-console                      | 0.4.7        |
| fileutils                       | 1.1.0        |
| etc                             | 1.0.1        |
| zlib                            | 1.0.0        |
| libxml-ruby                     | 3.1.0        |
| psych                           | 3.1.0        |
| mutex_m                         | 0.1.0        |
</details>

*generated on:* **2021-09-29**
</details>

**Comment by imWildCat** [comment]
I saw this too. Since my CI machine is local, I can use remote screen to that machine and used Xcode GUI to build and deliver the app once to fix this problem.
