### ISSUE TITLE
Add support for output_name parameter

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1942]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/2593278?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @sguillope - Imported from <a href='https://github.com/fastlane/scan/issues/27'>fastlane/scan#27</a>
        </td>
      </tr>
    </table>

It would be nice if it was possible to specify the name of the output file (similar to `gym`'s `output_name` parameter).
We are running our tests on Bamboo but the [Junit Parser plugin](https://confluence.atlassian.com/bamboo/junit-parser-289277056.html) only seems to parse files with an `.xml` extension. We currently have to manually rename the output file `report.junit` to have the `.xml` extension.

**Comment by nfalco79** [comment]
Mee too.
Jenkins SonarQube and other tools that parse junit report wants xml.
Using xml file for junit avoid a lot of setup.

**Comment by fabioknoedt** [comment]
+1 for this feature

**Comment by mikecole20** [comment]
I would also like to see this. CircleCI also expects an xml file. I was able to work around it using `mv $CIRCLE_TEST_REPORTS/xcode/report.junit $CIRCLE_TEST_REPORTS/xcode/results.xml`

**Comment by TKBurner** [comment]
@fabioknoedt Thanks for the plus 1. We are going to consider this over here. Have a great day!

**Comment by PycKamil** [comment]
I have added new flag for specifying full custom report name (custom_report_file_name). scan version 0.10.0 includes this change and this should solve this issue 👍

**Comment by jacobvanorder** [comment]
Thank you @PycKamil!

**Comment by KrauseFx** [comment]
Thanks for updating the issue and contributing to fastlane @PycKamil 🚀

**Comment by kirillzh** [comment]
`--custom_report_file_name STRING Sets custom full report file name`
Is this report filename for HTML or XML report? Also, why is it still `report.junit` and not `report.xml`? 😕

**Comment by TKBurner** [comment]
@kirillzh I believe it impacts both.
