### ISSUE TITLE
I'm having trouble running fastlane on my mac

### ISSUE THREAD

**Issue by eavilac12** [fastlane/fastlane#19433]
Good day,
When running fastlane on my mac, I get the following error:

Run `fastlane env` to append the fastlane environment to your issue
<internal:dir>:43:in `[]': \e[31m[!] Operation not permitted - Library/Accounts\e[0m (Errno::EPERM)
	from /opt/homebrew/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane/lib/fastlane/setup/setup.rb:60:in `start'
	from /opt/homebrew/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane/lib/fastlane/commands_generator.rb:365:in `ensure_fastfile'
	from /opt/homebrew/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /opt/homebrew/Cellar/fastlane/2.195.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/Cellar/fastlane/2.195.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/Cellar/fastlane/2.195.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.195.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	from /opt/homebrew/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /opt/homebrew/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /opt/homebrew/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/Cellar/fastlane/2.195.0/libexec/bin/fastlane:23:in `load'
	from /opt/homebrew/Cellar/fastlane/2.195.0/libexec/bin/fastlane:23:in `<main>'
<internal:dir>:43:in `[]': Operation not permitted - Library/Accounts (Errno::EPERM)
	from /opt/homebrew/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane/lib/fastlane/setup/setup.rb:60:in `start'
	from /opt/homebrew/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane/lib/fastlane/commands_generator.rb:365:in `ensure_fastfile'
	from /opt/homebrew/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /opt/homebrew/Cellar/fastlane/2.195.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/Cellar/fastlane/2.195.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/Cellar/fastlane/2.195.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.195.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	from /opt/homebrew/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /opt/homebrew/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /opt/homebrew/Cellar/fastlane/2.195.0/libexec/gems/fastlane-2.195.0/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/Cellar/fastlane/2.195.0/libexec/bin/fastlane:23:in `load'
	from /opt/homebrew/Cellar/fastlane/2.195.0/libexec/bin/fastlane:23:in `<main>'

**Comment by jessicatarra** [comment]
Try this https://gitlab.com/gnachman/iterm2/-/wikis/fulldiskaccess

**Comment by pengjinfeng** [comment]
I have this problem too，on Mac M1


[⠙] Looking for iOS and Android projects in current directory...➡️  I'm having trouble running fastlane on my mac
    https://github.com/fastlane/fastlane/issues/19433 [open] 3 💬
    4 weeks ago

🔗  You can ⌘ + double-click on links to open them directly in your browser.
[⠋] Looking for iOS and Android projects in current directory...<internal:dir>:43:in `[]': \e[31m[!] Operation not permitted - Library/Accounts\e[0m (Errno::EPERM)
	from /Users/ks/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.199.0/fastlane/lib/fastlane/setup/setup.rb:60:in `start'
	from /Users/ks/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.199.0/fastlane/lib/fastlane/commands_generator.rb:122:in `block (2 levels) in run'
	from /Users/ks/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/ks/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/ks/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/ks/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.199.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	from /Users/ks/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/ks/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.199.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	from /Users/ks/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.199.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/ks/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.199.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /Users/ks/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.199.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
	from /Users/ks/.rvm/rubies/ruby-3.0.0/bin/ruby_executable_hooks:22:in `eval'
	from /Users/ks/.rvm/rubies/ruby-3.0.0/bin/ruby_executable_hooks:22:in `<main>'
<internal:dir>:43:in `[]': Operation not permitted - Library/Accounts (Errno::EPERM)
	from /Users/ks/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.199.0/fastlane/lib/fastlane/setup/setup.rb:60:in `start'
	from /Users/ks/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.199.0/fastlane/lib/fastlane/commands_generator.rb:122:in `block (2 levels) in run'
	from /Users/ks/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/ks/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/ks/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/ks/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.199.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	from /Users/ks/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/ks/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.199.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	from /Users/ks/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.199.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/ks/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.199.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /Users/ks/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.199.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
	from /Users/ks/.rvm/rubies/ruby-3.0.0/bin/ruby_executable_hooks:22:in `eval'
	from /Users/ks/.rvm/rubies/ruby-3.0.0/bin/ruby_executable_hooks:22:in `<main>'

**Comment by Patsy69** [comment]
I'm having the same problem with the device provisioning as you i.e. nothing happens when plugging in a new device.

**Comment by icedice** [comment]
> Try this https://gitlab.com/gnachman/iterm2/-/wikis/fulldiskaccess

This solved it for me.
