### ISSUE TITLE
automatic_release

### ISSUE THREAD

**Issue by constantRAIN** [fastlane/fastlane#19452]
### New Issue Checklist

- [ ✅] Updated fastlane to the latest version
- [ ✅] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ✅] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ✅] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

lane :submit_app_store do
    deliver(
      api_key_path: 'fastlane/2VKZJ4933J.json',
      username: 'zxliuyu@didiglobal.com',
      app_identifier: 'com.xiaojukeji.sunkai.test666',
      build_number: '3.5.11.92300501',
      app_version: '3.5.11',
      platform: 'ios',
      skip_binary_upload: true,
      skip_screenshots: true,
      skip_metadata: true,
      submit_for_review: true,
      automatic_release: false,
      phased_release: false,
      run_precheck_before_submit: false,
      force: true,
      submission_information: { add_id_info_uses_idfa: false }
    )
end

App store connect still automatically publishes this version

fastlane submit_app_store

**Comment by constantRAIN** [comment]
> It seems like you have not included the output of `fastlane env`
> To make it easier for us help you resolve this issue, please update the issue to include the output of `fastlane env` 👍

FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD = "xgxf-mgnd-lunt-rbnq"
DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV"

**Comment by alex-taffe** [comment]
> > It seems like you have not included the output of `fastlane env`
> > To make it easier for us help you resolve this issue, please update the issue to include the output of `fastlane env` 👍
> 
> FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD = "REDACTED" DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV"

@constantRAIN might want to delete this comment considering this is exposing your Apple ID password (well the application specific version)
