### ISSUE TITLE
When I upgrade Xcode 13 form 12, Then build_ios_app Fail (exportOptionsPlist error for key "uploadBitcode": cannot upload bitcode because bitcode is imbalanced)

### ISSUE THREAD

**Issue by AlexanderPan** [fastlane/fastlane#19461]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When I upgrade Xcode 13 form 12, Then got error message below:

##### Command executed

```
build_ios_app(
      workspace: "xxx.xcworkspace", 
      scheme: "xxx",
      cloned_source_packages_path: "SourcePackages",
      export_method:"app-store",
      configuration: "Release",
      include_bitcode: true,
      include_symbols: true
      )
```
      
      

##### Complete output when running fastlane, including the stack trace and command used

```

RVM detected, forcing to use system ruby

Warning: PATH set to RVM ruby but GEM_HOME and/or GEM_PATH not set, see:
    https://github.com/rvm/rvm/issues/3212

Now using system ruby.
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/yy/kl6ykdxn4yjdslm_sx_s2z3r0000gn/T/gym_config20211012-75777-uwcr.plist -archivePath '/Users/panhaoqun/Library/Developer/Xcode/Archives/2021-10-12/invoice 2021-10-12 20.07.31.xcarchive' -exportPath /var/folders/yy/kl6ykdxn4yjdslm_sx_s2z3r0000gn/T/gym_output20211012-75777-qgxxlo
2021-10-12 20:23:59.260 xcodebuild[88254:11560269] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path "/var/folders/yy/kl6ykdxn4yjdslm_sx_s2z3r0000gn/T/invoice_2021-10-12_20-23-59.259.xcdistributionlogs".
2021-10-12 20:24:00.748 xcodebuild[88254:11560353] CFURLRequestSetHTTPCookieStorageAcceptPolicy_block_invoke: no longer implemented and should not be called
error: exportArchive: exportOptionsPlist error for key "uploadBitcode": cannot upload bitcode because bitcode is imbalanced

Error Domain=IDEFoundationErrorDomain Code=1 "exportOptionsPlist error for key "uploadBitcode": cannot upload bitcode because bitcode is imbalanced" UserInfo={NSLocalizedDescription=exportOptionsPlist error for key "uploadBitcode": cannot upload bitcode because bitcode is imbalanced}

** EXPORT FAILED **
ERROR [2021-10-12 20:24:06.85]: Exit status: 70

```

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.195.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.3.1   | ✅ Up-To-Date  |
| fastlane-plugin-google_cloud_storage      | 0.1.1   | ✅ Up-To-Date  |
| fastlane-plugin-unzip                     | 1.0.1   | ✅ Up-To-Date  |
| fastlane-plugin-google_drive              | 0.7.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.5.0        |
| pathname                                  | 0.1.0        |
| set                                       | 1.0.1        |
| tsort                                     | 0.1.0        |
| shellwords                                | 0.1.0        |
| digest                                    | 3.0.0        |
| rake                                      | 13.0.6       |
| rexml                                     | 3.2.5        |
| CFPropertyList                            | 3.0.4        |
| concurrent-ruby                           | 1.1.9        |
| i18n                                      | 1.8.10       |
| minitest                                  | 5.14.4       |
| thread_safe                               | 0.3.6        |
| tzinfo                                    | 1.2.9        |
| activesupport                             | 5.2.6        |
| public_suffix                             | 4.0.6        |
| addressable                               | 2.8.0        |
| httpclient                                | 2.8.3        |
| json                                      | 2.5.1        |
| algoliasearch                             | 1.27.5       |
| artifactory                               | 3.0.15       |
| atomos                                    | 0.1.3        |
| aws-eventstream                           | 1.2.0        |
| aws-partitions                            | 1.507.0      |
| aws-sigv4                                 | 1.4.0        |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.121.1      |
| aws-sdk-kms                               | 1.48.0       |
| aws-sdk-s3                                | 1.103.0      |
| babosa                                    | 1.0.4        |
| bundler                                   | 2.2.3        |
| claide                                    | 1.0.3        |
| clamp                                     | 1.3.2        |
| fuzzy_match                               | 2.0.4        |
| nap                                       | 1.1.0        |
| netrc                                     | 0.11.0       |
| ffi                                       | 1.15.4       |
| ethon                                     | 0.14.0       |
| typhoeus                                  | 1.4.0        |
| cocoapods-core                            | 1.10.2       |
| cocoapods-deintegrate                     | 1.0.5        |
| cocoapods-downloader                      | 1.5.1        |
| cocoapods-plugins                         | 1.0.0        |
| cocoapods-search                          | 1.0.1        |
| cocoapods-trunk                           | 1.6.0        |
| cocoapods-try                             | 1.2.0        |
| colored2                                  | 3.1.2        |
| escape                                    | 0.0.4        |
| fourflusher                               | 2.3.1        |
| gh_inspector                              | 1.1.3        |
| molinillo                                 | 0.6.6        |
| ruby-macho                                | 1.4.0        |
| nanaimo                                   | 0.3.0        |
| xcodeproj                                 | 1.21.0       |
| cocoapods                                 | 1.10.2       |
| colored                                   | 1.2          |
| highline                                  | 2.0.3        |
| commander                                 | 4.6.0        |
| declarative                               | 0.0.20       |
| digest-crc                                | 0.6.4        |
| unf_ext                                   | 0.0.8        |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| dotenv                                    | 2.7.6        |
| emoji_regex                               | 3.2.2        |
| excon                                     | 0.85.0       |
| faraday-em_http                           | 1.0.0        |
| faraday-em_synchrony                      | 1.0.0        |
| faraday-excon                             | 1.1.0        |
| faraday-httpclient                        | 1.0.1        |
| faraday-net_http                          | 1.0.1        |
| faraday-net_http_persistent               | 1.2.0        |
| faraday-patron                            | 1.0.0        |
| faraday-rack                              | 1.0.0        |
| multipart-post                            | 2.0.0        |
| ruby2_keywords                            | 0.0.5        |
| faraday                                   | 1.8.0        |
| http-cookie                               | 1.0.4        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.1.0        |
| fastimage                                 | 2.2.5        |
| jwt                                       | 2.2.3        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.1        |
| signet                                    | 0.16.0       |
| googleauth                                | 0.17.1       |
| mini_mime                                 | 1.1.1        |
| trailblazer-option                        | 0.1.1        |
| uber                                      | 0.1.0        |
| representable                             | 3.1.1        |
| retriable                                 | 3.1.2        |
| webrick                                   | 1.7.0        |
| google-apis-core                          | 0.4.1        |
| google-apis-androidpublisher_v3           | 0.11.0       |
| google-apis-playcustomapp_v1              | 0.5.0        |
| google-apis-iamcredentials_v1             | 0.7.0        |
| google-apis-storage_v1                    | 0.8.0        |
| google-cloud-env                          | 1.5.0        |
| google-cloud-errors                       | 1.2.0        |
| google-cloud-core                         | 1.6.0        |
| google-cloud-storage                      | 1.34.1       |
| mini_magick                               | 4.11.0       |
| naturally                                 | 2.2.1        |
| optparse                                  | 0.1.1        |
| plist                                     | 3.6.0        |
| rubyzip                                   | 2.3.2        |
| security                                  | 0.1.3        |
| simctl                                    | 1.6.8        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.8.0        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| word_wrap                                 | 1.0.0        |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.1        |
| fastlane-plugin-firebase_app_distribution | 0.3.1        |
| fastlane-plugin-google_cloud_storage      | 0.1.1        |
| google-apis-drive_v3                      | 0.13.0       |
| google-apis-sheets_v4                     | 0.9.0        |
| mini_portile2                             | 2.6.1        |
| racc                                      | 1.5.2        |
| nokogiri                                  | 1.12.4       |
| google_drive                              | 3.0.7        |
| fastlane-plugin-google_drive              | 0.7.0        |
| fastlane-plugin-unzip                     | 1.0.1        |
| slather                                   | 2.6.0        |
| xcode-install                             | 2.6.8        |

**Comment by genry86** [comment]
Have similar issue using `gym`
```
Error Domain=IDEFoundationErrorDomain Code=1 "exportOptionsPlist error for key "uploadBitcode": cannot upload bitcode because bitcode is imbalanced" UserInfo={NSLocalizedDescription=exportOptionsPlist error for key "uploadBitcode": cannot upload bitcode because bitcode is imbalanced}
```

```
+---------------+-----------------------------------+
|                 Build environment                 |
+---------------+-----------------------------------+
| xcode_path    | /Applications/Xcode-13.1.beta.app |
| gym_version   | 2.197.0                           |
| export_method | app-store                         |
| sdk           | iPhoneOS15.2.sdk                  |
+---------------+-----------------------------------+
```

Any progress with fixing that issue?

**Comment by bonro001** [comment]
Why closed, not seeing a solution.

**Comment by AlexanderPan** [comment]
@bonro001 Here is my solution: https://developer.apple.com/forums/thread/690934

**Comment by bonro001** [comment]
Thank you, that worked!On Nov 18, 2021, at 8:35 AM, Alex ***@***.***> ***@***.*** Here is my solution: https://developer.apple.com/forums/thread/690934—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
