### ISSUE TITLE
FastLane can’t update itself

### ISSUE THREAD

**Issue by alakoring** [fastlane/fastlane#19486]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Fastlane suggests updating, but actually doing so fails.

##### Command executed
bundle exec fastlane update

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [6AS/SixAges] % bundle exec fastlane update
[✔] 🚀 
[17:30:17]: ------------------------------
[17:30:17]: --- Step: default_platform ---
[17:30:17]: ------------------------------
[17:30:17]: -----------------------------
[17:30:17]: --- Step: update_fastlane ---
[17:30:17]: -----------------------------
[17:30:17]: Looking for updates for fastlane...
[17:30:18]: Updating fastlane from 2.195.0 to 2.196.0... 🚀
[17:30:27]: Finished updating fastlane
[17:30:27]: Cleaning up old versions...
[17:30:27]: fastlane.tools successfully updated! I will now restart myself... 😴
[✔] 🚀 
[17:30:28]: ------------------------------
[17:30:28]: --- Step: default_platform ---
[17:30:28]: ------------------------------
[17:30:28]: -----------------------------
[17:30:28]: --- Step: update_fastlane ---
[17:30:28]: -----------------------------
+------------------+-----+
|      Lane Context      |
+------------------+-----+
| DEFAULT_PLATFORM | ios |
+------------------+-----+
[17:30:28]: Could not find lane 'ios update'. Available lanes: ios storm, ios dark, ios tests, ios sync

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 2    | update_fastlane  | 0           |
+------+------------------+-------------+

[17:30:28]: fastlane finished with errors

[!] Could not find lane 'ios update'. Available lanes: ios storm, ios dark, ios tests, ios sync

#######################################################################
# fastlane 2.196.0 is available. You are on 2.195.0.
# You should use the latest version.
# Please update using `bundle update fastlane`.
#######################################################################

2.196.0 Improvements
* [fastlane_core] symbolize keys in options of type Hash (#19424) via Davide De Rosa
* [snapshot] add snapshot iPad Mini support (#19460) via Paul
* [pem] fix issue OpenSSL empty password (#19459) via Fernando
* [supply] Treat no release note as warning instead of error (#19425) via yanagiragi
* [sigh] add --generate-entitlement-der to resign codesign calls (#19423) via Taylor Fort
* [action][latest_testflight_build] make `LatestTestflightBuildNumberAction` not overwrite existing Actions.lane_context (#19421) via Jan Klausa
* [snapshot] add the iPhone 13 devices so that they can be included in the HTML report page. (#19420) via Yilei "Dolee" Yang
* [screengrab] fix typos in Screengrab options (#19426) via Christoph Dreis
* [supply] fix rollout update (#19411) via Oleksii Malovanyi

Please update using `bundle update fastlane`
/Users/david/.gem/gems/bundler-2.2.0/lib/bundler/spec_set.rb:86:in `block in materialize': Could not find unf_ext-0.0.8 in any of the sources (Bundler::GemNotFound)
	from /Users/david/.gem/gems/bundler-2.2.0/lib/bundler/spec_set.rb:80:in `map!'
	from /Users/david/.gem/gems/bundler-2.2.0/lib/bundler/spec_set.rb:80:in `materialize'
	from /Users/david/.gem/gems/bundler-2.2.0/lib/bundler/definition.rb:175:in `specs'
	from /Users/david/.gem/gems/bundler-2.2.0/lib/bundler/definition.rb:245:in `specs_for'
	from /Users/david/.gem/gems/bundler-2.2.0/lib/bundler/definition.rb:227:in `requested_specs'
	from /Users/david/.gem/gems/bundler-2.2.0/lib/bundler/runtime.rb:91:in `block in definition_method'
	from /Users/david/.gem/gems/bundler-2.2.0/lib/bundler/runtime.rb:20:in `setup'
	from /Users/david/.gem/gems/bundler-2.2.0/lib/bundler.rb:149:in `setup'
	from /Users/david/.gem/gems/bundler-2.2.0/lib/bundler/setup.rb:20:in `block in <top (required)>'
	from /Users/david/.gem/gems/bundler-2.2.0/lib/bundler/ui/shell.rb:136:in `with_level'
	from /Users/david/.gem/gems/bundler-2.2.0/lib/bundler/ui/shell.rb:88:in `silence'
	from /Users/david/.gem/gems/bundler-2.2.0/lib/bundler/setup.rb:20:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:85:in `require'

[17:30:29]: RubyGems is not listed as your Gem source
[17:30:29]: You can run `gem sources` to see all your sources
[17:30:29]: Please run the following command to fix this:
[17:30:29]: $ gem sources --add https://rubygems.org

[6AS/SixAges] % gem sources
*** CURRENT SOURCES ***

https://rubygems.org/
[6AS/SixAges] % 
</pre>
</details>

### Environment

<details>
  <pre> <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.6                                                           |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.30.1 (Apple Git-130)                             |
| Installation Source         | ~/.gem/bin/fastlane                                            |
| Host                        | macOS 11.6 (20G165)                                            |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 13.0                                                           |
| Swift Version               | 5.5                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

# Assume Slack is configured by the SLACK_URL environment variable

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :storm do
	log = prompt(
		text: "Changelog: ",
		multi_line_end_keyword: "END"
	)
	bn = increment_build_number(xcodeproj: "SixAges.xcodeproj")
	build_app(
		workspace: "SixAges.xcworkspace",
		scheme: "StormAge",
		output_directory: "Builds"
	)
	upload_to_testflight(
		changelog: log,
		distribute_external: true,
		groups: ["Team"]
	)
	slack(
		message: "StormAge uploaded to TestFlight",
 		default_payloads: [],
 		payload: {
			"Build" => bn,
 			"Changes" => log
		}
	)
	sync
  end

  lane :dark do
	log = prompt(
		text: "Changelog: ",
		multi_line_end_keyword: "END"
	)
	bn = increment_build_number(
		build_number: "352",
		xcodeproj: "SixAges.xcodeproj")
	build_app(
		workspace: "SixAges.xcworkspace",
		scheme: "DarkAge",
		output_directory: "Builds"
	)
	upload_to_testflight(
		changelog: log,
		distribute_external: true,
		groups: ["QA"]
	)
	slack(
		message: "DarkAge uploaded to TestFlight",
 		default_payloads: [],
 		payload: {
			"Build" => bn,
 			"Changes" => log
		}
	)
	sync
  end

  desc "Run the unit tests"
  lane :tests do
	run_tests(
		scheme: "StormAge",
		slack_only_on_failure: true,
		slack_channel: "XXX"
	)
  end

  desc "Be sure the QA dropbox has the latest from Scripts"
  lane :sync do
	rsync(
		extra: '-avz --stats',
		source: "Resources/Scripts/StormAge/*.osl",
		destination: '"/Users/david/Dropbox/Six Ages of Saird/SixAges-QA/Scripts/StormAge"'
	)
	rsync(
		extra: '-avz --stats',
		source: "Resources/Scripts/StormAge/*.txt",
		destination: '"/Users/david/Dropbox/Six Ages of Saird/SixAges-QA/Scripts/StormAge"'
	)
 	rsync(
		extra: '-avz --stats',
		source: "Resources/Scripts/DarkAge/*.osl",
		destination: '"/Users/david/Dropbox/Six Ages of Saird/SixAges-QA/Scripts/DarkAge"'
	)
	rsync(
		extra: '-avz --stats',
		source: "Resources/Scripts/DarkAge/*.txt",
		destination: '"/Users/david/Dropbox/Six Ages of Saird/SixAges-QA/Scripts/DarkAge"'
	)
 end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.a-sharp.Six-Ages" # The bundle identifier of your app
apple_id "XXX" # Your Apple email address

itc_team_id "XXX" # iTunes Connect Team ID
team_id "XXX" # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

for_lane :dark do
	app_identifier 'com.a-sharp.DarkAge'
end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.195.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| bundler                         | 2.2.0        |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.4        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.513.0      |
| aws-sigv4                       | 1.4.0        |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.121.1      |
| aws-sdk-kms                     | 1.49.0       |
| aws-sdk-s3                      | 1.103.0      |
| babosa                          | 1.0.4        |
| claide                          | 1.0.3        |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.87.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| multipart-post                  | 2.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.8.0        |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.1.0        |
| fastimage                       | 2.2.5        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.3.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| signet                          | 0.16.0       |
| googleauth                      | 1.0.0        |
| httpclient                      | 2.8.3        |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.1        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-androidpublisher_v3 | 0.12.0       |
| google-apis-playcustomapp_v1    | 0.5.0        |
| google-apis-iamcredentials_v1   | 0.7.0        |
| google-apis-storage_v1          | 0.8.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.34.1       |
| json                            | 2.5.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
</details>

*generated on:* **2021-10-15**
</details> </pre>
</details>

**Comment by alakoring** [comment]
Thanks, that does get me an update. And fastlane did actually tell me that — I wonder if the command I typed used to work?

I do think there is a bug, in that

```
Updating fastlane from 2.195.0 to 2.196.0... 🚀
…
fastlane.tools successfully updated! I will now restart myself
```
is completely untrue (it did not successfully update, but it led me to believe that the command was valid). That’s not as big a problem as my operator error led me to think there was, however.

**Comment by lucgrabowski** [comment]
Are you sure you're running the command in the expected directory and do you commit `Gemfile.lock` changes? You should see 2.196.0 in Gemfile.lock.

**Comment by alakoring** [comment]
I’ve always run fastlane from the same directory; other commands work fine (#19442 is still an issue for me but fastlane does build an iOS archive).

I have no idea what Gemfile.lock is — I realize that’s an important implementation detail but I don’t recall seeing that in documentation as something I’m supposed to know about. (I’m not running a CI server or anything so I haven’t been committing any fastlane artifacts.) Since I have now updated the proper way, it includes `fastlane (2.196.0)`.

**Comment by alakoring** [comment]
The situation has magically cleared itself up. I mean that literally — I kept trying different things, none of which worked. And then somehow it did, and I could run fastlane again. I was able to update fastlane today, so that is still working too.
