### ISSUE TITLE
Please keep .certsigningrequest

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1949]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/1295242?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @programmin1 - Imported from <a href='https://github.com/fastlane/pem/issues/92'>fastlane/pem#92</a>
        </td>
      </tr>
    </table>

It appears the pem command doesn't keep the .certsigningrequest when run for an app.

When time comes to renew the push certificate, the easiest way to fix it is to reupload the certsigningrequest, download the new cert and replace wherever you were using the expired one.

**Comment by programmin1** [comment]
because reusing the certsigningrequest keeps the private key and everything the same, no need to re-compile the app to make push work again.

**Comment by KrauseFx** [comment]
You don't need to re-compile your app, you can create a new push certificate any time, even after your app got approved by Apple.
