### ISSUE TITLE
upload_to_app_store returns error: No data

### ISSUE THREAD

**Issue by pawelkoszcodema** [fastlane/fastlane#19501]
Hello, i cant send app to appstore. 
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.4                                                           |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.23.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.4 (20F71)                                             |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 13.0                                                           |
| Swift Version               | 5.5                                                            |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
 # This file contains the fastlane.tools configuration
 # You can find the documentation at https://docs.fastlane.tools
 #
 # For a list of all available actions, check out
 #
 #     https://docs.fastlane.tools/actions
 #
 # For a list of all available plugins, check out
 #
 #     https://docs.fastlane.tools/plugins/available-plugins
 #

 # Uncomment the line if you want fastlane to automatically update itself
 # update_fastlane

 default_platform(:ios)

 platform :ios do
   desc "Push a new release build to the App Store"
   lane :release do
     increment_version_number
     increment_build_number(xcodeproj: "xxx")
     build_app(workspace: "xxx", scheme: "xx")
     upload_to_app_store
   end
 end

```
</details>

<details><summary>`./Appfile`</summary>

```ruby
app_identifier("xxx") # The bundle identifier of your app

apple_dev_portal_id "xxx"  # Apple Developer Account
itunes_connect_id "xxx"     # App Store Connect Account
#apple_id "xxx"

itc_team_id("xxx") # App Store Connect Team ID
team_id("xxx") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.192.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.85.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.7.0        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.1.0        |
| fastimage                       | 2.2.5        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| simctl                          | 1.6.8        |
| jwt                             | 2.2.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.1        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.1        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| signet                          | 0.15.0       |
| googleauth                      | 0.17.0       |
| httpclient                      | 2.8.3        |
| google-apis-core                | 0.4.1        |
| google-apis-playcustomapp_v1    | 0.5.0        |
| google-apis-androidpublisher_v3 | 0.10.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.7.0        |
| google-apis-storage_v1          | 0.6.0        |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.34.1       |
| emoji_regex                     | 3.2.2        |
| jmespath                        | 1.4.0        |
| aws-partitions                  | 1.490.0      |
| aws-eventstream                 | 1.1.1        |
| aws-sigv4                       | 1.2.4        |
| aws-sdk-core                    | 3.119.1      |
| aws-sdk-kms                     | 1.46.0       |
| aws-sdk-s3                      | 1.99.0       |
| rexml                           | 3.2.5        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.0.3        |
| CFPropertyList                  | 3.0.3        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.21.0       |
| json                            | 2.5.1        |
| bundler                         | 2.2.26       |
| webrick                         | 1.7.0        |
| rake                            | 13.0.6       |
| forwardable                     | 1.2.0        |
| logger                          | 1.3.0        |
| date                            | 2.0.0        |
| stringio                        | 0.0.2        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.0.0        |
| mutex_m                         | 0.1.0        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| io-console                      | 0.4.7        |
| fileutils                       | 1.1.0        |
| etc                             | 1.0.1        |
| libxml-ruby                     | 3.1.0        |
| psych                           | 3.1.0        |
</details>

*generated on:* **2021-10-20**
</details>
upload_to_app_store returns error 
<pre>[15:47:58]: No data</pre>

  <pre> [15:47:47]: Making sure the latest version on App Store Connect matches '1.0'...
[15:47:48]: '1.0' is the latest version on App Store Connect
[15:47:48]: Verifying the upload via the HTML file can be disabled by either adding
[15:47:48]: `force true` to your Deliverfile or using `fastlane deliver --force`
[15:47:49]: Does the Preview on path './fastlane/Preview.html' look okay for you? (y/n)
y
[15:47:51]: HTML file confirmed...
[15:47:53]: Will begin uploading metadata for '1.0' on App Store Connect
[15:47:53]: Release type will not be set because neither `automatic_release` nor `auto_release_date` were provided. Please explicitly set one of these options if you need a release type set
[15:47:53]: Uploading metadata to App Store Connect for version
+------------------+-------------+
|          Lane Context          |
+------------------+-------------+
| DEFAULT_PLATFORM | ios         |
| PLATFORM_NAME    | ios         |
| LANE_NAME        | ios release |
| BUILD_NUMBER     | 8           |
+------------------+-------------+
[15:47:58]: No data

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | default_platform       | 0           |
| 2    | increment_build_number | 1           |
| 💥   | upload_to_app_store    | 12          |
+------+------------------------+-------------+

[15:47:58]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  action lcov: allow for custom derived data path
    https://github.com/fastlane/fastlane/issues/19396 [open] 1 💬
    3 weeks ago

➡️  [Gym] Signing with Xcode 13 fails because no provisioning profiles were found
    https://github.com/fastlane/fastlane/issues/19377 [open] 1 💬
    4 weeks ago

➡️  Android Screenshots not working API 25
    https://github.com/fastlane/fastlane/issues/19218 [open] 1 💬
    5 weeks ago

and 3883 more at: https://github.com/fastlane/fastlane/search?q=No%20data&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
        33: from /usr/local/bin/fastlane:23:in `<main>'
        32: from /usr/local/bin/fastlane:23:in `load'
        31: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.196.0/bin/fastlane:23:in `<top (required)>'
        30: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.196.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
        29: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.196.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
        28: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.196.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
        27: from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        26: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.196.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
        25: from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        24: from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        23: from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        22: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.196.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
        21: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.196.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        20: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.196.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        19: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.196.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.196.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.196.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.196.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        15: from Fastfile:26:in `block (2 levels) in parsing_binding'
        14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.196.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.196.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.196.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.196.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.196.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
         9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.196.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
         8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.196.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
         7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.196.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:22:in `run'
         6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.196.0/deliver/lib/deliver/runner.rb:55:in `run'
         5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.196.0/deliver/lib/deliver/runner.rb:146:in `upload_metadata'
         4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.196.0/deliver/lib/deliver/upload_metadata.rb:344:in `upload'
         3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.196.0/deliver/lib/deliver/upload_metadata.rb:628:in `set_review_attachment_file'
         2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.196.0/spaceship/lib/spaceship/connect_api/models/app_store_version.rb:147:in `fetch_app_store_review_detail'
         1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.196.0/spaceship/lib/spaceship/connect_api/response.rb:58:in `to_models'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.196.0/spaceship/lib/spaceship/connect_api/model.rb:82:in `parse': [!] No data (RuntimeError)
</pre>

**Comment by m3rkus** [comment]
Got the same issue, ruby version 2.6.5, M1 Macbook Pro. Tried Fastlane version 2.197.0, 2.195.0, 2.190.0

**Comment by SDooman** [comment]
I have the same issue, did a little digging in the fastlane source code and it seems to be thrown by Spaceship's connect API to one of Apple's services.  For me it happens right after finishing this step:

`Uploading metadata to App Store Connect for localized info`

Would be super useful if we could have `deliver` print which endpoint it was hitting to get no data

For everyone who has experienced this issue so far: Is that about the same spot in your `deliver` process that it fails?

**Comment by nathanbroyles** [comment]
I'm also encountering the same error at the `Uploading metadata to App Store Connect for localized info` step.

**Comment by nathanbroyles** [comment]
Something is happening here in model.rb.
```
def self.parse(json)
        data = json["data"]
        raise "No data" unless data
```

**Comment by kocyigityunus** [comment]
it happens on to upload metadata phase, so if you are not uploading any metadata, consider skipping it in parameters like: 
```ruby
# send to store
deliver(
    submit_for_review: false,
    force: true,
    skip_metadata: true,
    skip_screenshots: true
)
```

**Comment by nathanbroyles** [comment]
@kocyigityunus I think the problem is that we are wanting to upload metadata though.

**Comment by nathanbroyles** [comment]
Good news. I was able to get passed this error by running `bundle install`. I guess I didn't have a required Gem named rake, which I was alerted to when trying to run `bundle exec fastlane deliver`. After running bundle install things started working. Hope that helps!

**Comment by SDooman** [comment]
Quick follow up:

the solution above did not work for me, but did some more digging and the error is being thrown at the `get_app_store_review_detail` function found [here](https://github.com/fastlane/fastlane/blob/5dc9f74769c0b9e3688e8befe24f3ef6de4c6187/spaceship/lib/spaceship/connect_api/tunes/tunes.rb#L727).  I'm only experiencing this error for targets where this is the first release of the app, so it's possible that this just doesn't work for first releases of targets.

**Comment by pawelkoszcodema** [comment]
I managed to resolve this by adding 
`skip_metadata: true` to `upload_to_app_store()` so it looks like this
`upload_to_app_store(skip_metadata: true)`

**Comment by Stephan-FDG** [comment]
I am having the same issue, we want to automate uploading our metadata so `skip_metadata: true` is not an option.
We are before our first release of the app, is there a Workaround?

**Comment by Stephan-FDG** [comment]
I found a Workaround: 
I downloaded the metadata to check if I missed a file running `fastlane deliver download_meatadata`
then there I saw the folder "review_information" but all files were empty. 
So I added the folder "review_information" with empty files: [demo_password, demo_user, email_address, first_name, last_name, notes, phone_number] and the error no longer appeard.

**Comment by nysander** [comment]
unfortunately I got similar error for new app
