### ISSUE TITLE
About buildNumber

### ISSUE THREAD

**Issue by zi6xuan** [fastlane/fastlane#19509]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When I uploaded the 1.1.0 and 1.2.0 versions to testflight at the same time, the final buildNumber I got was the last uploaded version, not the final buildNumber of the corresponding version.
For example, the latest build for 1.1.0 is 10, and the latest build for 1.2.0 is 5.
When the last time I uploaded the version was 1.1.0, when I archived and uploaded the 1.2.0 version again, I found that the archived version of 1.2.0 became 11.
Is it possible to get the correct build corresponding to the version number instead of the last uploaded buildNumber

**Comment by salabaha** [comment]
I had the same issue and after a few hours of research I have found that we can pass "**manageAppVersionAndBuildNumbe: false**" parameter to export_options of build_app action to disable xcode version change. 

`build_app(
  scheme: "your_app_scheme",
  export_options:{
    manageAppVersionAndBuildNumber: false
  })`

**Comment by zi6xuan** [comment]
Yes, you can also turn off automatic management by modifying the xcode project settings
