### ISSUE TITLE
Edit promotional_text for live app in "Ready for Sale" state

### ISSUE THREAD

**Issue by tiagomartinho** [fastlane/fastlane#19522]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I tried to use deliver to update the promotional text of a live app without success.
I used both edit_live and use_live_version, but neither allow me to change the metadata for the current live app, only for future releases.

##### Command executed
  upload_to_app_store(edit_live: true,
                      use_live_version: true,
                      submit_for_review: false,
                      force: true,
                      app_identifier: ENV['APP_IDENTIFIER'],
                      app_version: ENV['APP_VERSION'],
                      metadata_path: ENV['METADATA_PATH'],
                      run_precheck_before_submit: false,
                      automatic_release: true,
                      skip_screenshots: true,
                      skip_binary_upload: true,
                      reject_if_possible: false,
                      ignore_language_directory_validation: true)

##### Complete output when running fastlane, including the stack trace and command used
[13:56:32]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
ArgumentError: [!] Enqueue Array instead of NilClass
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.197.0/fastlane_core/lib/fastlane_core/queue_worker.rb:26:in `batch_enqueue'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.197.0/deliver/lib/deliver/upload_metadata.rb:210:in `upload'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.197.0/deliver/lib/deliver/runner.rb:146:in `upload_metadata'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.197.0/deliver/lib/deliver/runner.rb:55:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:22:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:7:in `block in parsing_binding'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.197.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.197.0/bin/fastlane:23:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>'

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.6                                                           |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.30.1 (Apple Git-130)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.6 (20G165)                                            |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 13.0                                                           |
| Swift Version               | 5.5                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.197.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| terminal-table                  | 1.8.0        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| artifactory                     | 3.0.15       |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| gh_inspector                    | 1.1.3        |
| security                        | 0.1.3        |
| rexml                           | 3.2.5        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.0.3        |
| CFPropertyList                  | 3.0.4        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.21.0       |
| unicode-display_width           | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| babosa                          | 1.0.4        |
| excon                           | 0.87.0       |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| ruby2_keywords                  | 0.0.5        |
| faraday-rack                    | 1.0.0        |
| faraday-patron                  | 1.0.0        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-net_http                | 1.0.1        |
| faraday-httpclient              | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.8.0        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.5        |
| json                            | 2.6.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.1.4        |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| webrick                         | 1.7.0        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| signet                          | 0.16.0       |
| os                              | 1.1.1        |
| memoist                         | 0.16.2       |
| googleauth                      | 1.1.0        |
| mini_mime                       | 1.1.2        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.1        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| google-apis-core                | 0.4.1        |
| google-apis-playcustomapp_v1    | 0.5.0        |
| google-apis-androidpublisher_v3 | 0.12.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-apis-storage_v1          | 0.8.0        |
| google-apis-iamcredentials_v1   | 0.7.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.34.1       |
| emoji_regex                     | 3.2.3        |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-partitions                  | 1.518.0      |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.121.3      |
| aws-sdk-kms                     | 1.50.0       |
| aws-sdk-s3                      | 1.104.0      |
| forwardable                     | 1.2.0        |
| logger                          | 1.3.0        |
| date                            | 2.0.0        |
| stringio                        | 0.0.2        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.0.0        |
| mutex_m                         | 0.1.0        |
| connection_pool                 | 2.2.2        |
| net-http-persistent             | 3.1.0        |
| net-http-pipeline               | 1.0.1        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| io-console                      | 0.4.7        |
| fileutils                       | 1.1.0        |
| etc                             | 1.0.1        |
| libxml-ruby                     | 3.2.1        |
| psych                           | 3.1.0        |
</details>

*generated on:* **2021-10-25**
</details>

**Comment by tiagomartinho** [comment]
Hi!

Does anyone has an update on this issue?

Thank you

**Comment by bunuelcubosoto** [comment]
Hi!

We have the same issue. We use deliver to update the promotional text of our live App Store version and we got the same error.

**Comment by FelixLisczyk** [comment]
I'm encountering the same error when using deliver with the `edit_live` flag enabled.

**Comment by FelixLisczyk** [comment]
This issue is still reproducible with the latest fastlane version 2.204.2.

<details>
<summary>Fastlane</summary>

```
deliver(
    edit_live: true,
    force: true,
    run_precheck_before_submit: false,
    skip_screenshots: true,
    promotional_text: {
        "en-US" => "My Promo Text",
        "de-DE" => "Mein Promo-Text",
    }
)
```

</details>

<details>
<summary>Stacktrace</summary>

```
/Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.2/fastlane_core/lib/fastlane_core/queue_worker.rb:26:in `batch_enqueue': \e[31m[!] Enqueue Array instead of NilClass\e[0m (ArgumentError)
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.2/deliver/lib/deliver/upload_metadata.rb:210:in `upload'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.2/deliver/lib/deliver/runner.rb:146:in `upload_metadata'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.2/deliver/lib/deliver/runner.rb:55:in `run'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.2/fastlane/lib/fastlane/actions/upload_to_app_store.rb:22:in `run'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.2/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.2/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.2/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.2/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.2/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.2/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.2/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        from configuration/Fastfile_Discounts:52:in `block (2 levels) in parsing_binding'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.2/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.2/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.2/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.2/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.2/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.2/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.2/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.2/bin/fastlane:23:in `<top (required)>'
        from /Users/felix/.rvm/gems/ruby-3.0.0/bin/fastlane:23:in `load'
        from /Users/felix/.rvm/gems/ruby-3.0.0/bin/fastlane:23:in `<top (required)>'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/lib/bundler/cli/exec.rb:58:in `load'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/lib/bundler/cli/exec.rb:23:in `run'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/lib/bundler/cli.rb:478:in `exec'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/lib/bundler/cli.rb:31:in `dispatch'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/lib/bundler/cli.rb:25:in `start'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/exe/bundle:49:in `block in <top (required)>'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
        from /Users/felix/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.31/exe/bundle:37:in `<top (required)>'
        from /Users/felix/.rvm/gems/ruby-3.0.0/bin/bundle:23:in `load'
        from /Users/felix/.rvm/gems/ruby-3.0.0/bin/bundle:23:in `<main>'
```

</details>

**Comment by FelixLisczyk** [comment]
The issue still occurs in the latest fastlane version 2.204.3. See my previous comment for the configuration and stack trace.

**Comment by FelixLisczyk** [comment]
The error message remains unchanged in the latest fastlane version 2.205.2.

**Comment by FelixLisczyk** [comment]
The error message remains unchanged in the latest fastlane version 2.208.0
