### ISSUE TITLE
copy_artifacts is messing with aab's signing on ubuntu

### ISSUE THREAD

**Issue by gabides** [fastlane/fastlane#19548]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

On ubuntu, when using the [copy_artifacts](http://docs.fastlane.tools/actions/copy_artifacts/) action on an aab and trying to upload  the copied aab (output of copy_artifacts) to the playstore, we're getting an error  `Google Api Error: Invalid request - The Android App Bundle was not signed. Please sign the bundle using jarsigner.`

On macos it works correctly with the exact same code, and on ubuntu uploading to the store the aab generated by `gradle` action works as well with no error.
Only uploading the `aab` copied by `copy_artifacts` from a ubuntu machine has this issue.

##### Command executed

1. build an aab with in the lane:
```ruby
  desc "Build all flavors for release"
  lane :build_release do |options|
    gradle(
      task: "assemble",
      project_dir: "android/",
      build_type: "Release",
    )
    copy_artifacts(
      target_path: "mobile-artifacts/android",
      artifacts: ["**/*.aab"],
      fail_on_missing: true,
    )
  end
```
2. upload the release to playstore with action `upload_to_play_store`. This results in the error `Google Api Error: Invalid request - The Android App Bundle was not signed. Please sign the bundle using jarsigner.`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
[09:11:25]: Preparing aab at path '/home/ubuntu/my-app/mobile-artifacts/android/my-app.aab' for upload...
+---------------+------------------------+
|              Lane Context              |
+---------------+------------------------+
| PLATFORM_NAME | android                |
| LANE_NAME     | android upload_release |
+---------------+------------------------+
[09:11:31]: Google Api Error: Invalid request - The Android App Bundle was not signed. Please sign the bundle using jarsigner.
</pre>
</details>

### Environment

This happens on all ubuntu environments I tested:
1. github actions ubuntu runner 
```
Current runner version: '2.283.3'
Operating System
  Ubuntu
  20.04.3
  LTS
```
2. ubuntu VM on google compute

<details>
<pre>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                         |
| --------------------------- | ------------------------------------------------------------- |
| OS                          | debian_based stretch/sid                                      |
| Ruby                        | 2.5.1                                                         |
| Bundler?                    | false                                                         |
| Git                         | git version 2.7.4                                             |
| Installation Source         | ~/.rbenv/versions/2.5.1/bin/fastlane                          |
| Host                        | Ubuntu 16.04.7 LTS debian_based stretch/sid (4.15.0-1098-gcp) |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.1/lib                                   |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                                    |
| Is contained                | false                                                         |
| Is homebrew                 | false                                                         |
| Is installed via Fabric.app | false                                                         |

</pre>
</details>

**Comment by Barrows2** [comment]
So, I was dragging some files around in Nautilus and I wanted to cancel a drag. So, I just hit escape.
Then I got this weird file icon floating always on top on my screen that I couldn't figure out how to get rid of. Logging out and back in fixed it, but I'd rather not have to do that as I have this problem come up quite a bit.
I tried killing and restarting Nautilus but that didn't fix it.
Here is a screenshot of the little visual artifact.
