### ISSUE TITLE
get_version_number doesn't see version number

### ISSUE THREAD

**Issue by AdrianBinDC** [fastlane/fastlane#19557]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I have a marketing version set in the Xcode project file, but `get_version_number` doesn't see it in my build settings.
```
  desc "Print app version number"
  lane :print_app_version do
    #add actions here
    UI.command("App version number executing")
    version = get_version_number(
      xcodeproj: "./FastlaneExperiment.xcodeproj"
    )
    UI.success "The app version number is #{version}"
  end
```

I call this with `fastlane print_app_version` from the root directory of the project I've got Fastlane installed in. I get the following error:

> Unable to find Xcode build setting:

##### Command executed

`fastlane print_app_version`

##### Complete output when running fastlane, including the stack trace and command used

```
 ~/Desktop/FastlaneExperiment/ > fastlane print_app_version

[✔] 🚀
[11:35:22]: fastlane detected a Gemfile in the current directory
[11:35:22]: However, it seems like you didn't use `bundle exec`
[11:35:22]: To launch fastlane faster, please use
[11:35:22]:
[11:35:22]: $ bundle exec fastlane print_app_version
[11:35:22]:
[11:35:22]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[11:35:24]: ------------------------------
[11:35:24]: --- Step: default_platform ---
[11:35:24]: ------------------------------
[11:35:24]: Driving the lane 'ios print_app_version' 🚀
[11:35:24]: $ App version number executing
[11:35:24]: --------------------------------
[11:35:24]: --- Step: get_version_number ---
[11:35:24]: --------------------------------
+------------------+-----------------------+
|               Lane Context               |
+------------------+-----------------------+
| DEFAULT_PLATFORM | ios                   |
| PLATFORM_NAME    | ios                   |
| LANE_NAME        | ios print_app_version |
+------------------+-----------------------+
[11:35:24]: Unable to find Xcode build setting:

+------+--------------------+-------------+
|            fastlane summary             |
+------+--------------------+-------------+
| Step | Action             | Time (in s) |
+------+--------------------+-------------+
| 1    | default_platform   | 0           |
| 💥   | get_version_number | 0           |
+------+--------------------+-------------+

[11:35:24]: fastlane finished with errors

[!] Unable to find Xcode build setting:
```
### Environment

<details>
  <pre> 
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 11.3.1                                                  |
| Ruby                        | 3.0.2                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.33.1                                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.197.0/libexec/bin/fastlane |
| Host                        | macOS 11.3.1 (20E241)                                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/3.0.2_1/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021                             |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 13.1                                                    |
| Swift Version               | 5.5.1                                                   |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

# CONSTANTS
# This is the regular expression to identify valid git commit hashes
COMMIT_HASH_REGEX = /[0-9a-f]{5,40}/

platform :ios do
  desc "Generate release notes"
  lane :generate_release_notes do
    # prompt for commit hashes
    starting_hash = UI.input("What is the starting commit hash?")
    ending_hash = UI.input("What is the ending commit hash? [Press Enter for HEAD]")

    if ending_hash == ""
      ending_hash = "HEAD"
    end

    UI.important "ℹ️  The starting hash is #{starting_hash}"
    UI.important "ℹ️  The ending hash is #{ending_hash}"

    changelog = changelog_from_git_commits(
      between: [starting_hash, ending_hash]
    )
    UI.success "\n🏁 RELEASE NOTES: 🏁\n#{changelog}"
  end

  desc "Increment build number and commit"
  lane :build_bump do
    # get the current build number
    current_build_number = get_build_number
    UI.message "The current build number is #{current_build_number}"
    # bump the build number
    increment_build_number
    UI.message "The new build number is #{get_build_number}"
    # commit the increment in project.pbxproj
    git_commit(path: "./FastlaneExperiment.xcodeproj/project.pbxproj", message: "Build bump from #{current_build_number} to #{get_build_number}")
  end

  desc "Print app version number"
  lane :print_app_version do
    #add actions here
    UI.command("App version number executing")
    version = get_version_number(
      xcodeproj: "./FastlaneExperiment.xcodeproj"
    )
    UI.success "The app version number is #{version}"
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.197.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.4        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.8.0        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.5        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.22       |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| mini_mime                       | 1.1.2        |
| google-cloud-storage            | 1.34.1       |
| emoji_regex                     | 3.2.3        |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-sdk-kms                     | 1.50.0       |
| aws-sdk-s3                      | 1.104.0      |
| tsort                           | 0.1.0        |
| uri                             | 0.10.1       |
| set                             | 1.0.1        |
| excon                           | 0.88.0       |
| json                            | 2.6.1        |
| webrick                         | 1.7.0        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| signet                          | 0.16.0       |
| os                              | 1.1.1        |
| memoist                         | 0.16.2       |
| googleauth                      | 1.1.0        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.1        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| google-apis-core                | 0.4.1        |
| google-apis-playcustomapp_v1    | 0.6.0        |
| google-apis-androidpublisher_v3 | 0.13.0       |
| google-apis-iamcredentials_v1   | 0.8.0        |
| google-apis-storage_v1          | 0.9.0        |
| aws-partitions                  | 1.521.0      |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.121.5      |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.0        |
| date                            | 3.1.0        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.0        |
| openssl                         | 2.2.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.2        |
| io-wait                         | 0.1.0        |
| zlib                            | 1.1.0        |
| resolv                          | 0.2.0        |
| securerandom                    | 0.1.0        |
| digest                          | 3.0.0        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.0        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.0        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.7        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| net-http                        | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| prettyprint                     | 0.1.0        |
| pp                              | 0.1.0        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.0        |
</details>

*generated on:* **2021-10-31**
</details>
 </pre>
</details>

**Comment by CidJHT** [comment]
I got some error when I use get_version_number too. And my new project is create from Xcode 13.
Is your project create form Xcode 13 ?
if yes, you should add info.plist file manually, and go to your project target build settings, set up the info.plist path.

**Comment by vdshko** [comment]
Try to add `Bundle version string (short)` key with value: `$(MARKETING_VERSION)` into your Info.plist file. Hope it will help u.

**Comment by bsarrazin** [comment]
Does the `get_version_number` action not support SwiftUI apps yet? Must we absolutely add the `Info.plist` file back into our project manually?
