### ISSUE TITLE
[screengrab] Android app screenshots inside module

### ISSUE THREAD

**Issue by doudasek** [fastlane/fastlane#19554]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I have a modularized app with package name `a.b.c` that has `app`, `presentation`, `domain`, `data`, `infrastructure` modules. All UI logic is inside `presentation` module. I have created UI tests inside `presentation` module (`presentation/src/androidTest/kotlin/a/b/c/presentation/screenshots`) like this: 

```kotlin
@RunWith(JUnit4::class)
class FirstScreenshot {
    companion object {
        @BeforeClass
        @JvmStatic
        fun setup() {
            Screengrab.setDefaultScreenshotStrategy(UiAutomatorScreenshotStrategy())
            CleanStatusBar.enableWithDefaults()
        }

        @AfterClass
        @JvmStatic
        fun teardown() {
            CleanStatusBar.disable()
        }
    }

    @get:Rule
    val composeTestRule = createAndroidComposeRule(ScreenshotFirstActivity::class.java)

    @Rule
    @JvmField
    val localeTestRule = LocaleTestRule()

    @Test
    fun screenshot1() {
        composeTestRule.activityRule.scenario.moveToState(Lifecycle.State.RESUMED)
        composeTestRule.waitForIdle()
        Screengrab.screenshot("screen01")
    }
}
```

The problem is that screengrab fails to find captured screenshots. I can see all screenshots made in Device File Explorer after launching the script located here:
`/data/data/a.b.c.presentation.test/app_screengrab/en/images/screenshots/screen01.png`. But as I can see in the screengrab log, it is trying to find the screenshots only in `/data/data/a.b.c` folder. There is nothing to find so screengrab fails.

Should screengrab try to search even this folder: `/data/data/a.b.c.presentation.test` folder? Or how to make it work? 

##### Command executed
Both APKs are up-to-date prebuilt.

```
desc "Make screenshots"
lane :makeScreenshots do
  screengrab(
    locales: ["en", "cs", "sk"],
    clear_previous_screenshots: true,
    app_apk_path: "app/build/outputs/apk/debug/app-debug.apk",
    tests_apk_path: "presentation/build/outputs/apk/androidTest/debug/presentation-debug-androidTest.apk",
    use_tests_in_packages: ["a.b.c.presentation.screenshots"],
    app_package_name: "a.b.c",
    tests_package_name: "a.b.c.presentation.test",
    use_timestamp_suffix: false,
  )
end
```

`fastlane android makeScreenshots`

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>

[✔] 🚀
[14:08:13]: fastlane detected a Gemfile in the current directory
[14:08:13]: However, it seems like you didn't use `bundle exec`
[14:08:13]: To launch fastlane faster, please use
[14:08:13]:
[14:08:13]: $ bundle exec fastlane android makeScreenshots
[14:08:13]:
[14:08:13]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[14:08:15]: ------------------------------
[14:08:15]: --- Step: default_platform ---
[14:08:15]: ------------------------------
[14:08:15]: Driving the lane 'android makeScreenshots' 🚀
[14:08:15]: ------------------------
[14:08:15]: --- Step: screengrab ---
[14:08:15]: ------------------------

+-----------------------------+-------------------------------------------------------------------------------------+
|                                          Summary for screengrab 2.197.0                                           |
+-----------------------------+-------------------------------------------------------------------------------------+
| locales                     | ["en", "cs", "sk"]                                                                  |
| clear_previous_screenshots  | true                                                                                |
| app_apk_path                | app/build/outputs/apk/debug/app-debug.apk                                           |
| tests_apk_path              | presentation/build/outputs/apk/androidTest/debug/presentation-debug-androidTest.apk |
| use_tests_in_packages       | ["a.b.c.presentation.screenshots"]                                |
| app_package_name            | a.b.c                                                             |
| tests_package_name          | a.b.c.presentation.test                                           |
| use_timestamp_suffix        | false                                                                               |
| output_directory            | fastlane/metadata/android                                                           |
| skip_open_summary           | false                                                                               |
| test_instrumentation_runner | androidx.test.runner.AndroidJUnitRunner                                             |
| ending_locale               | en-US                                                                               |
| use_adb_root                | false                                                                               |
| device_type                 | phone                                                                               |
| exit_on_test_failure        | true                                                                                |
| reinstall_app               | false                                                                               |
+-----------------------------+-------------------------------------------------------------------------------------+

[14:08:15]: Clearing phoneScreenshots within fastlane/metadata/android
[14:08:15]: $ /Users/martin/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell echo \$EXTERNAL_STORAGE
[14:08:16]: ▸ /sdcard
[14:08:16]: $ /Users/martin/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell echo \$ANDROID_DATA
[14:08:16]: ▸ /data
[14:08:16]: Cleaning screenshots on device
ls: /sdcard/a.b.c/screengrab/en/images/screenshots: No such file or directory
[14:08:16]: Exit status: 1
ls: /sdcard/Android/data/a.b.c/files/screengrab/en/images/screenshots: No such file or directory
[14:08:16]: Exit status: 1
ls: /sdcard/a.b.c/screengrab/cs/images/screenshots: No such file or directory
[14:08:16]: Exit status: 1
ls: /sdcard/Android/data/a.b.c/files/screengrab/cs/images/screenshots: No such file or directory
[14:08:16]: Exit status: 1
ls: /sdcard/a.b.c/screengrab/sk/images/screenshots: No such file or directory
[14:08:16]: Exit status: 1
ls: /sdcard/Android/data/a.b.c/files/screengrab/sk/images/screenshots: No such file or directory
[14:08:16]: Exit status: 1
ls: /data/user/0/a.b.c/files/a.b.c/screengrab/en/images/screenshots: No such file or directory
[14:08:16]: Exit status: 1
ls: /data/data/a.b.c/files/a.b.c/screengrab/en/images/screenshots: No such file or directory
[14:08:16]: Exit status: 1
ls: /data/data/a.b.c/app_screengrab/en/images/screenshots: No such file or directory
[14:08:16]: Exit status: 1
ls: /data/data/a.b.c/screengrab/en/images/screenshots: No such file or directory
[14:08:16]: Exit status: 1
ls: /data/user/0/a.b.c/files/a.b.c/screengrab/cs/images/screenshots: No such file or directory
[14:08:16]: Exit status: 1
ls: /data/data/a.b.c/files/a.b.c/screengrab/cs/images/screenshots: No such file or directory
[14:08:16]: Exit status: 1
ls: /data/data/a.b.c/app_screengrab/cs/images/screenshots: No such file or directory
[14:08:16]: Exit status: 1
ls: /data/data/a.b.c/screengrab/cs/images/screenshots: No such file or directory
[14:08:16]: Exit status: 1
ls: /data/user/0/a.b.c/files/a.b.c/screengrab/sk/images/screenshots: No such file or directory
[14:08:16]: Exit status: 1
ls: /data/data/a.b.c/files/a.b.c/screengrab/sk/images/screenshots: No such file or directory
[14:08:16]: Exit status: 1
ls: /data/data/a.b.c/app_screengrab/sk/images/screenshots: No such file or directory
[14:08:16]: Exit status: 1
ls: /data/data/a.b.c/screengrab/sk/images/screenshots: No such file or directory
[14:08:16]: Exit status: 1
[14:08:16]: $ /Users/martin/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop ro.build.version.sdk
[14:08:16]: ▸ 30
[14:08:16]: Installing app APK
[14:08:16]: $ /Users/martin/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -t -r app/build/outputs/apk/debug/app-debug.apk
[14:08:16]: ▸ Performing Streamed Install
[14:08:17]: ▸ Success
[14:08:17]: Installing tests APK
[14:08:17]: $ /Users/martin/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -t -r presentation/build/outputs/apk/androidTest/debug/presentation-debug-androidTest.apk
[14:08:17]: ▸ Performing Streamed Install
[14:08:17]: ▸ Success
[14:08:17]: Granting the permission necessary to change locales on the device
[14:08:17]: $ /Users/martin/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm grant a.b.c android.permission.CHANGE_CONFIGURATION
[14:08:17]: Granting the permissions necessary to access device external storage
[14:08:17]: $ /Users/martin/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm grant a.b.c android.permission.WRITE_EXTERNAL_STORAGE
[14:08:17]: $ /Users/martin/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm grant a.b.c android.permission.READ_EXTERNAL_STORAGE
[14:08:17]: Enabling clean status bar
[14:08:17]: $ /Users/martin/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm grant a.b.c android.permission.DUMP
[14:08:18]: $ /Users/martin/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell settings put global sysui_demo_allowed 1
[14:08:18]: $ /Users/martin/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am force-stop a.b.c.test
[14:08:18]: $ /Users/martin/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am force-stop a.b.c
[14:08:18]: Running tests for locale: en
[14:08:18]: $ /Users/martin/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am instrument --no-window-animation -w \
-e testLocale en \
--no-hidden-api-checks \
-e appendTimestamp false \
-e package a.b.c.presentation.screenshots \
a.b.c.presentation.test/androidx.test.runner.AndroidJUnitRunner
[14:08:23]: ▸ a.b.c.presentation.screenshots.FirstScreenshot:.
[14:08:24]: ▸ a.b.c.presentation.screenshots.SecondScreenshot:.
[14:08:26]: ▸ a.b.c.presentation.screenshots.ThirdScreenshot:.
[14:08:28]: ▸ a.b.c.presentation.screenshots.FourthScreenshot:.
[14:08:30]: ▸ a.b.c.presentation.screenshots.FifthScreenshot:.
[14:08:30]: ▸ Time: 11.218
[14:08:30]: ▸ OK (5 tests)
[14:08:31]: Pulling captured screenshots for locale en from the device
[14:08:31]: $ /Users/martin/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell echo \$EXTERNAL_STORAGE
[14:08:31]: ▸ /sdcard
[14:08:31]: $ /Users/martin/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell echo \$ANDROID_DATA
[14:08:31]: ▸ /data
ls: /sdcard/a.b.c/screengrab/en/images/screenshots: No such file or directory
[14:08:31]: Exit status: 1
ls: /sdcard/Android/data/a.b.c/files/screengrab/en/images/screenshots: No such file or directory
[14:08:31]: Exit status: 1
ls: /data/user/0/a.b.c/files/a.b.c/screengrab/en/images/screenshots: No such file or directory
[14:08:31]: Exit status: 1
ls: /data/data/a.b.c/files/a.b.c/screengrab/en/images/screenshots: No such file or directory
[14:08:31]: Exit status: 1
ls: /data/data/a.b.c/app_screengrab/en/images/screenshots: No such file or directory
[14:08:31]: Exit status: 1
ls: /data/data/a.b.c/screengrab/en/images/screenshots: No such file or directory
[14:08:31]: Exit status: 1
[14:08:31]: Make sure you've used Screengrab.screenshot() in your tests and that your expected tests are being run.
+------------------+-------------------------+
|                Lane Context                |
+------------------+-------------------------+
| DEFAULT_PLATFORM | android                 |
| PLATFORM_NAME    | android                 |
| LANE_NAME        | android makeScreenshots |
+------------------+-------------------------+
[14:08:31]: No screenshots were detected 📷❌

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 💥   | screengrab       | 16          |
+------+------------------+-------------+

[14:08:31]: fastlane finished with errors

[!] No screenshots were detected 📷❌

 </pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.5.2                                                         |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.15.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.5.2 (20G95)                                           |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Library/Developer/CommandLineTools/                           |
| Xcode Version               |                                                                |
| Swift Version               | 5.3.2                                                          |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
    desc "Run unit tests"
    lane :tests do
      gradle(
        task: ':domain:testDebugUnitTest'
      )
      gradle(
        task: ':data:testDebugUnitTest'
      )
    end

    desc "Verifies code coverage metrics"
    lane :verification do
      gradle(
        task: 'clean'
      )
      gradle(
        task: ':domain:testDebugUnitTestVerification'
      )
      gradle(
        task: ':data:testDebugUnitTestVerification'
      )
      gradle(
        task: ':infrastructure:testDebugUnitTestVerification'
      )
    end

    desc "Creates test coverage reports"
    lane :report do
      gradle(
        task: 'clean'
      )
      gradle(
        task: ':domain:testDebugUnitTestReport'
      )
      gradle(
        task: ':data:testDebugUnitTestReport'
      )
      gradle(
        task: ':infrastructure:testDebugUnitTestReport'
      )
    end

    desc "Build release code (APK format)"
    lane :buildRelease do
        gradle(
            task: 'assemble',
            build_type: 'release'
        )
    end

    desc "Build debug code"
    lane :buildDebug do
        gradle(
          task: 'assemble',
          build_type: 'debug'
        )
    end

    desc "Promote release app to Google Play Console - internal testing"
    lane :releaseGooglePlayInternal do
        gradle(
            task: 'clean'
        )

        gradle(
            task: 'bundle',
            build_type: 'ReleaseGooglePlay'
        )

        upload_to_play_store(
            track: 'internal',
            skip_upload_apk: true,
            skip_upload_images: true,
            skip_upload_screenshots: true,
            skip_upload_metadata: true
        )
    end

    desc "Build debug and test APK for screenshots"
    lane :buildForScreengrab do
        gradle(
          task: 'clean'
        )
        build_android_app(
              task: 'assemble',
              build_type: 'Debug'
        )
        gradle(
            task: ':presentation:assembleDebugAndroidTest'
        )
    end

    desc "Make screenshots"
    lane :makeScreenshots do
        buildForScreengrab
        screengrab(
          locales: ["en", "cs", "sk"],
          clear_previous_screenshots: true,
          app_apk_path: "app/build/outputs/apk/debug/app-debug.apk",
          tests_apk_path: "presentation/build/outputs/apk/androidTest/debug/presentation-debug-androidTest.apk",
          use_tests_in_packages: ["a.b.c.presentation.screenshots"],
          app_package_name: "a.b.c",
          tests_package_name: "a.b.c.presentation.test",
          use_timestamp_suffix: false,
        )
    end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("./fastlane/google_play_credential.json")
package_name("a.b.c")

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.197.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| atomos                          | 0.1.3        |
| CFPropertyList                  | 2.3.6        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.19.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.80.1       |
| faraday-excon                   | 1.1.0        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.1.0        |
| ruby2_keywords                  | 0.0.4        |
| faraday                         | 1.4.1        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.5        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.1.0        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.15       |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.1        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.0        |
| httpclient                      | 2.8.3        |
| rexml                           | 3.1.9        |
| webrick                         | 1.4.2        |
| google-apis-core                | 0.4.1        |
| google-apis-playcustomapp_v1    | 0.5.0        |
| google-apis-androidpublisher_v3 | 0.12.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.7.0        |
| google-apis-storage_v1          | 0.8.0        |
| rake                            | 12.3.2       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.34.1       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.4.0        |
| aws-partitions                  | 1.519.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-sdk-core                    | 3.121.3      |
| aws-sdk-kms                     | 1.50.0       |
| aws-sdk-s3                      | 1.104.0      |
| forwardable                     | 1.2.0        |
| logger                          | 1.3.0        |
| date                            | 2.0.0        |
| stringio                        | 0.0.2        |
| zlib                            | 1.0.0        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| io-console                      | 0.4.7        |
| fileutils                       | 1.1.0        |
| etc                             | 1.0.1        |
| libxml-ruby                     | 3.1.0        |
| psych                           | 3.1.0        |
| mutex_m                         | 0.1.0        |
</details>

*generated on:* **2021-10-29**
</details>

**Comment by EmDee** [comment]
I'm seeing the same problem after updating to the latest `2.198.0`. Before we've been using `2.168.0` without a problem.

So something seems to have changed in between those two...

```
[12:20:34]: Cleaning screenshots on device
ls: /sdcard/com.package.name/screengrab/en-US/images/screenshots: No such file or directory
[12:20:34]: Exit status: 1
ls: /sdcard/Android/data/com.package.name/files/screengrab/en-US/images/screenshots: No such file or directory
[12:20:34]: Exit status: 1
ls: /data/user/0/com.package.name/files/com.package.name/screengrab/en-US/images/screenshots: No such file or directory
[12:20:34]: Exit status: 1
ls: /data/data/com.package.name/files/com.package.name/screengrab/en-US/images/screenshots: No such file or directory
[12:20:34]: Exit status: 1
ls: /data/data/com.package.name/app_screengrab/en-US/images/screenshots: No such file or directory
[12:20:34]: Exit status: 1
ls: /data/data/com.package.name/screengrab/en-US/images/screenshots: No such file or directory
```

**Comment by doudasek** [comment]
@EmDee I have tried to downgrade but it didn't help. In my case, it is because it is a modularized app and Fastlane doesn't count on it to find the screenshots in subpackages (ex: `.presentation`).
