### ISSUE TITLE
[actions] `upload_to_testflight` won't import testers from `testers_file_path`

### ISSUE THREAD

**Issue by ericklborges** [fastlane/fastlane#19556]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

My team is constantly adding and removing people from a TestFlight external group, and this process is manual nowadays.

I am attempting to make it automatic on the CI, turning a `testers.csv` file into the single source of truth for the TestFlight testers.

I found `Pilot` the perfect tool to do that, but it looks like the action `upload_to_testflight` simply ignores the `testers_file_path` parameter on my use case. 

I do not want to upload a new `.ipa` every time the testers list needs update, so I'm using this `distribute_only` option.

```ruby
upload_to_testflight(
  app_identifier: @app_id,
  dev_portal_team_id: @team_id,
  itc_provider: @team_id,
  distribute_only: true, 
  notify_external_testers: true,
  distribute_external: true,
  groups: "Test Group",
  testers_file_path: "testers.csv"
)
```

The lane succeeds, and adds a build to the "Test Group", but the testers list remain the same. I assume that new testers in the `.csv` should be added to the group, as it happens when I use the CLI command bellow:
```bash
$ bundle exec fastlane pilot import -c testers.csv -a my.bundle.id -u my@apple.id
```

As you can see [here](https://github.com/fastlane/fastlane/blob/e8d30e3494024b6d4ee81bf21448991779ca278d/fastlane/lib/fastlane/actions/upload_to_testflight.rb#L27-L35) it seems that whenever `distribute_only` is `true`, this method [`distribute`](https://github.com/fastlane/fastlane/blob/e8d30e3494024b6d4ee81bf21448991779ca278d/pilot/lib/pilot/build_manager.rb#L132) is called, and I could not find any reference to the `testers_file_path` parameter there.

##### Command executed

```bash
$ bundle exec fastlane update_testers --env sandbox
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[18:26:58]: ----------------------------------
[18:26:58]: --- Step: upload_to_testflight ---
[18:26:58]: ----------------------------------
[18:26:58]: Creating authorization token for App Store Connect API
[18:27:02]: Waiting for processing on... app_id: 1470507774, app_version: , build_version: , platform: IOS
[18:27:02]: Searching for the latest build
[18:27:18]: Successfully finished processing the build 2.23.0 - 5610 for IOS
[18:27:18]: Uploaded app  - , but received build 2.23.0 - 5610.
[18:27:18]: No build specified - fetching latest build
[18:30:33]: Distributing new build to testers: 2.23.0 - 5610
[18:30:33]: Build 2.23.0 - 5610 already submitted for review
[18:30:34]: Successfully distributed build to External testers 🚀 </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.6                                                           |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.30.1 (Apple Git-130)                             |
| Installation Source         | ~/Git/mobile-banking-ios/vendor/bundle/ruby/2.6.0/bin/fastlane |
| Host                        | macOS 11.6 (20G165)                                            |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode-13.0.0.app/Contents/Developer/             |
| Xcode Version               | 13.0                                                           |
| Swift Version               | 5.5                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | pt_BR.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform :ios

require 'json'

platform :ios do
  TESTFLIGHT_DEST = ''
  FIREBASE_DEST = ''

  APPSTORE_CERT_TYPE = ''
  ADHOC_CERT_TYPE = ''

  before_all do
    @apple_id = ''
    @dev_portal_team_id = ''
  end

  lane :update_testers do
    check_environment
    app_id = ENV['APP_ID']

    upload_to_testflight(
      app_identifier: @app_id,
      dev_portal_team_id: @dev_portal_team_id,
      itc_provider: @dev_portal_team_id,
      distribute_only: true, 
      notify_external_testers: true,
      distribute_external: true,
      groups: "Test Group",
      testers_file_path: "./testers.csv"
    )
  end

  def check_environment
    unless ENV.key?('APP_ID')
      UI.user_error!('🚨 Environment not set. Use "--env [name]". Exiting 👋')
    end
  end

end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.197.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.3.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.3.0        |
| bundler                                   | 2.2.17       |
| rake                                      | 13.0.6       |
| rexml                                     | 3.2.5        |
| CFPropertyList                            | 3.0.4        |
| public_suffix                             | 4.0.6        |
| addressable                               | 2.8.0        |
| artifactory                               | 3.0.15       |
| atomos                                    | 0.1.3        |
| aws-eventstream                           | 1.2.0        |
| aws-partitions                            | 1.521.0      |
| aws-sigv4                                 | 1.4.0        |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.121.5      |
| aws-sdk-kms                               | 1.50.0       |
| aws-sdk-s3                                | 1.104.0      |
| babosa                                    | 1.0.4        |
| claide                                    | 1.0.3        |
| colored2                                  | 3.1.2        |
| cork                                      | 0.3.0        |
| nap                                       | 1.1.0        |
| open4                                     | 1.3.4        |
| claide-plugins                            | 0.9.2        |
| colored                                   | 1.2          |
| highline                                  | 2.0.3        |
| commander                                 | 4.6.0        |
| faraday-em_http                           | 1.0.0        |
| faraday-em_synchrony                      | 1.0.0        |
| faraday-excon                             | 1.1.0        |
| faraday-httpclient                        | 1.0.1        |
| faraday-net_http                          | 1.0.1        |
| faraday-net_http_persistent               | 1.2.0        |
| faraday-patron                            | 1.0.0        |
| faraday-rack                              | 1.0.0        |
| multipart-post                            | 2.0.0        |
| ruby2_keywords                            | 0.0.5        |
| faraday                                   | 1.8.0        |
| faraday-http-cache                        | 2.2.0        |
| rchardet                                  | 1.8.0        |
| git                                       | 1.9.1        |
| kramdown                                  | 2.3.1        |
| kramdown-parser-gfm                       | 1.1.0        |
| no_proxy_fix                              | 0.1.2        |
| sawyer                                    | 0.8.2        |
| octokit                                   | 4.21.0       |
| unicode-display_width                     | 1.8.0        |
| terminal-table                            | 1.8.0        |
| danger                                    | 8.3.1        |
| ox                                        | 2.14.5       |
| danger-junit                              | 1.0.2        |
| danger-plugin-api                         | 1.0.0        |
| danger-swiftformat                        | 0.8.1        |
| thor                                      | 0.20.3       |
| danger-swiftlint                          | 0.26.0       |
| declarative                               | 0.0.20       |
| digest-crc                                | 0.6.4        |
| unf_ext                                   | 0.0.8        |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| dotenv                                    | 2.7.6        |
| emoji_regex                               | 3.2.3        |
| excon                                     | 0.88.0       |
| http-cookie                               | 1.0.4        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.2.0        |
| fastimage                                 | 2.2.5        |
| gh_inspector                              | 1.1.3        |
| jwt                                       | 2.3.0        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.1        |
| signet                                    | 0.16.0       |
| googleauth                                | 1.1.0        |
| httpclient                                | 2.8.3        |
| mini_mime                                 | 1.1.2        |
| trailblazer-option                        | 0.1.1        |
| uber                                      | 0.1.0        |
| representable                             | 3.1.1        |
| retriable                                 | 3.1.2        |
| webrick                                   | 1.7.0        |
| google-apis-core                          | 0.4.1        |
| google-apis-androidpublisher_v3           | 0.13.0       |
| google-apis-playcustomapp_v1              | 0.6.0        |
| google-apis-iamcredentials_v1             | 0.8.0        |
| google-apis-storage_v1                    | 0.9.0        |
| google-cloud-env                          | 1.5.0        |
| google-cloud-errors                       | 1.2.0        |
| google-cloud-core                         | 1.6.0        |
| google-cloud-storage                      | 1.34.1       |
| json                                      | 2.6.1        |
| mini_magick                               | 4.11.0       |
| naturally                                 | 2.2.1        |
| optparse                                  | 0.1.1        |
| plist                                     | 3.6.0        |
| rubyzip                                   | 2.3.2        |
| security                                  | 0.1.3        |
| simctl                                    | 1.6.8        |
| terminal-notifier                         | 2.0.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| word_wrap                                 | 1.0.0        |
| nanaimo                                   | 0.3.0        |
| xcodeproj                                 | 1.21.0       |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.1        |
| fastlane-plugin-firebase_app_distribution | 0.3.1        |
</details>

*generated on:* **2021-10-29**
</details>

**Comment by hernangonzalez** [comment]
Hi, I am seeing a similar issue with `fastlane pilot import`. It picks up the file and returns a success message, yet testers are not showing up.

**Comment by ericklborges** [comment]
@hernangonzalez are you adding the tester to an existing group on App Store Connect?

I noticed that `fastlane pilot import` won't create new groups, just update existing ones with more testers.

**Comment by hernangonzalez** [comment]
@ericklborges yes, I created the groups before hand. All logs seem to print success messages too (tried with verbose on).

**Comment by ericklborges** [comment]
Just to be sure, have you checked if the group name, and the app identifier (bundle id) are spelled correctly?

Or even, are you checking the correct app and group on App Store Connect?

I know it's a dumb question, but I work on a project which has multiple bundle ids on App Store Connect, and different test groups. It has made me confused many times. 😊

**Comment by hernangonzalez** [comment]
@ericklborges group is spelled correctly (I am on multiple teams/apps too). 

I have not specified the bundle id as it is being picked from the Appfile, and it is printing the right App name afterwards. So looks ok to me.

**Comment by hernangonzalez** [comment]
Ok, this might be the thing. 

I have repeated the procedure with a user that is already member of the App Store user groups and process worked. This user shows up in the distribution group.

My previous case was with members that were not even invite yet to the Apple account.

So, is this the expected behaviour? I was looking forward not to manually invite each one of them :'(

**Comment by ericklborges** [comment]
Well, I don't understand that much about fastlane pilot, but when I use the command as told on the issue description, it can add new testers which have not been invited yet.

**Comment by iOSNinja** [comment]
Hi @hernangonzalez,
i used the below Pilot action in my lane and doesn't seem to add the already existing user to the internal/external testing groups. 
```
pilot(
  app_identifier: @app_id,
  dev_portal_team_id: @team_id,
  itc_provider: @team_id,
  distribute_only: true, 
  notify_external_testers: true,
  distribute_external: true,
  groups: "Test Group",
  testers_file_path: "testers.csv"
)
```
- [x] And by what i understood, adding testers is not available as a fastlane action but only via the command line tool, meaning we can’t use pilot in fastlane script to add testers. It is only to upload ipa & distribute to external users/groups. Check this [link](https://github.com/fastlane/fastlane/issues/13406) for reference).

- [x] Testers can be added from a lane using sh("fastlane pilot import --api_key_path <PATH> --testers_file_path <CSV file path>"). Check this [link](https://github.com/fastlane/fastlane/issues/19823) for reference.

So my question is, were you able to add existing internal testers or an external tester to using the action upload_to_testflight by passing testers_file_path and groups parameters? I tried using passing the same params in pilot action as above, and it didn't work.

Thanks.

**Comment by hernangonzalez** [comment]
Hi @iOSNinja,

Mine is working from the command line. Users that are already part of the developer team, are added accordingly to my defined groups.

I use it rarely now, so have not tried to automate it yet fyi. I use it in a similar way as your `sh` command, expect I keep the API key on an .env file.

**Comment by iOSNinja** [comment]
@hernangonzalez  cool, this is what i expected. Thanks for the reply.

Also, 

1. adding to the default internal group -> “App Store Connect Users” group, is not working(tried using both _**pilot add**_ and _**pilot import**_ as shown below). 
2. Adding to other internal groups is working fine. 

Is this the expected behavior? 

Commands tried:
`fastlane pilot add <emailid> -a <app_id>  -g "App Store Connect Users"`
` fastlane pilot import -c ../fastlane/testers.csv --app_identifier 'com.xyz'`

As shown in the below console logs, it says **_"Successfully added tester <emailid> to app <appname> in group(s) App Store Connect Users"_**, _**but when i check in the app store connect, it is not actually added.**_


```
[11:20:36]: $ fastlane pilot import -c ../fastlane/testers.csv --app_identifier 'com.excentus.smittys'
[11:20:38]: ▸ [11:20:38]: fastlane detected a Gemfile in the current directory
[11:20:38]: ▸ [11:20:38]: However, it seems like you didn't use `bundle exec`
[11:20:38]: ▸ [11:20:38]: To launch fastlane faster, please use
[11:20:38]: ▸ [11:20:38]:
[11:20:38]: ▸ [11:20:38]: $ bundle exec fastlane pilot import -c ../fastlane/testers.csv --app_identifier com.xyz
[11:20:38]: ▸ [11:20:38]:
[11:20:38]: ▸ [11:20:38]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[11:20:39]: ▸ [11:20:39]: Login to App Store Connect (xyz@abc.com)
[11:20:40]: ▸ [11:20:40]: Login successful
[11:20:40]: ▸ [11:20:40]: Login to App Store Connect (xyz@abc.com)
[11:20:59]: ▸ [11:20:59]: Login successful
[11:21:00]: ▸ [11:21:00]: **_Successfully added tester <emailid> to app <appname> in group(s) App Store Connect Users_**
[11:21:00]: ▸ [11:21:00]**_: Successfully imported 1 testers from ../fastlane/testers.csv_**
```

**Comment by hernangonzalez** [comment]
hey @iOSNinja,

1. I have not used the default one, all of mine are custom created by me.

Regards,
H.
