### ISSUE TITLE
upload_to_testflight  Authentication credentials are missing or invalid.

### ISSUE THREAD

**Issue by CyrilHu** [fastlane/fastlane#19578]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Uploading testflight reports an error when publishing. This happens only occasionally, but it is fatal for the CI process. It is often encountered that the testflight package is not automatically released. If this problem cannot be completely resolved, it is recommended to automatically retry.

##### Command executed

upload_to_testflight

##### Complete output when running fastlane, including the stack trace and command used

<details>
<summary>upload_to_testflight output </summary>
  <pre> 
1174 [10:23:20]: --- Step: upload_to_testflight ---
1175 [10:23:20]: ----------------------------------
1176 [10:23:20]: Creating authorization token for App Store Connect API
1177 [10:23:25]: Ready to upload new build to TestFlight (App: 999999999)...
1178 [10:23:26]: Going to upload updated app to App Store Connect
1179 [10:23:26]: This might take a few minutes. Please don't interrupt the script.
1180 [10:25:54]: iTunes Transporter successfully finished its job
1181 [10:25:54]: --------------------------------------------------------------------
1182 [10:25:54]: Successfully uploaded package to App Store Connect. It might take a few minutes until it's visible online.
1183 [10:25:54]: --------------------------------------------------------------------
1184 [10:25:54]: Successfully uploaded the new binary to App Store Connect
1185 [10:25:54]: If you want to skip waiting for the processing to be finished, use the `skip_waiting_for_build_processing` option
1186 [10:25:54]: Note that if `skip_waiting_for_build_processing` is used but a `changelog` is supplied, this process will wait for the build to appear on AppStoreConnect, update the changelog and then skip the remaining of the processing steps.
1187 [10:25:54]: Waiting for processing on... app_id: 999999999, app_version: 3.3.0, build_version: 4125, platform: IOS
1188 [10:25:56]: Read more information on why this build isn't showing up yet - https://github.com/fastlane/fastlane/issues/14997
1189 [10:25:56]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
1190 [10:26:29]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
1191 [10:27:01]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
1192 [10:27:34]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
1193 [10:28:06]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
1194 [10:28:39]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
1195 [10:29:11]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
1196 [10:29:44]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
1197 [10:30:16]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
1198 [10:30:49]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
1199 [10:31:24]: Waiting for App Store Connect to finish processing the new build (3.3.0 - 4125) for IOS
1200 [10:31:57]: Waiting for App Store Connect to finish processing the new build (3.3.0 - 4125) for IOS
1201 [10:32:30]: Waiting for App Store Connect to finish processing the new build (3.3.0 - 4125) for IOS
1202 [10:33:04]: Waiting for App Store Connect to finish processing the new build (3.3.0 - 4125) for IOS
1203 [10:33:38]: Waiting for App Store Connect to finish processing the new build (3.3.0 - 4125) for IOS
1204 [10:34:11]: Waiting for App Store Connect to finish processing the new build (3.3.0 - 4125) for IOS
1205 [10:34:45]: Waiting for App Store Connect to finish processing the new build (3.3.0 - 4125) for IOS
1206 [10:35:18]: Waiting for App Store Connect to finish processing the new build (3.3.0 - 4125) for IOS
1207 [10:35:51]: Waiting for App Store Connect to finish processing the new build (3.3.0 - 4125) for IOS
1208 [10:36:25]: Waiting for App Store Connect to finish processing the new build (3.3.0 - 4125) for IOS
1209 [10:36:58]: Waiting for App Store Connect to finish processing the new build (3.3.0 - 4125) for IOS
1210 [10:37:30]: Waiting for App Store Connect to finish processing the new build (3.3.0 - 4125) for IOS
1211 [10:38:03]: Waiting for App Store Connect to finish processing the new build (3.3.0 - 4125) for IOS
1212 [10:38:35]: Waiting for App Store Connect to finish processing the new build (3.3.0 - 4125) for IOS
1213 [10:39:08]: Waiting for App Store Connect to finish processing the new build (3.3.0 - 4125) for IOS
1214 [10:39:41]: Waiting for App Store Connect to finish processing the new build (3.3.0 - 4125) for IOS
1215 [10:40:15]: Waiting for App Store Connect to finish processing the new build (3.3.0 - 4125) for IOS
1216 [10:40:48]: Waiting for App Store Connect to finish processing the new build (3.3.0 - 4125) for IOS
1217 [10:41:21]: Waiting for App Store Connect to finish processing the new build (3.3.0 - 4125) for IOS
1218 [10:41:54]: Waiting for App Store Connect to finish processing the new build (3.3.0 - 4125) for IOS
1219 +------------------+---------------------------------------------+
1220 |                          Lane Context                          |
1221 +------------------+---------------------------------------------+
1222 | DEFAULT_PLATFORM | ios                                         |
1223 | TARGET_NAME      | {"com.example.bundleid"=>"Runner"} |
1224 | VERSION_NUMBER   | 3.3.0                                       |
1225 | PLATFORM_NAME    | ios                                         |
1226 | LANE_NAME        | ios testFlight                              |
1227 | OUTPUT_NAME      | Runner_3.3.0_4125_11.05                     |
1228 +------------------+---------------------------------------------+
1229 [10:42:25]: Authentication credentials are missing or invalid. - Provide a properly configured and signed bearer token, and make sure that it has not expired. Learn more about Generating Tokens for API Requests https://developer.apple.com/go/?id=api-generating-tokens
1230 +------+---------------------------+-------------+
1231 |                fastlane summary                |
1232 +------+---------------------------+-------------+
1233 | Step | Action                    | Time (in s) |
1234 +------+---------------------------+-------------+
1235 | 1    | default_platform          | 0           |
1236 | 2    | get_target_name           | 0           |
1237 | 3    | get_version_number        | 0           |
1238 | 4    | import_from_git           | 0           |
1239 | 5    | default_platform          | 0           |
1240 | 6    | app_store_connect_api_key | 0           |
1241 | 💥   | upload_to_testflight      | 1144        |
1242 +------+---------------------------+-------------+
1243 [10:42:25]: fastlane finished with errors
1244 Looking for related GitHub issues on fastlane/fastlane...
1245 [!] The request could not be completed because:
1246 	Authentication credentials are missing or invalid. - Provide a properly configured and signed bearer token, and make sure that it has not expired. Learn more about Generating Tokens for API Requests https://developer.apple.com/go/?id=api-generating-tokens
</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 10.15.7                                                 |
| Ruby                        | 3.0.2                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.24.3 (Apple Git-128)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.197.0/libexec/bin/fastlane |
| Host                        | Mac OS X 10.15.7 (19H1030)                              |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/3.0.2_1/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021                             |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 12.2                                                    |
| Swift Version               | 5.3.1                                                   |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.197.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.4        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.87.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.8.0        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.5        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.5.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.22       |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.1        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| signet                          | 0.16.0       |
| googleauth                      | 1.0.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-playcustomapp_v1    | 0.5.0        |
| google-apis-androidpublisher_v3 | 0.12.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.7.0        |
| google-apis-storage_v1          | 0.8.0        |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.34.1       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.4.0        |
| aws-partitions                  | 1.518.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-sdk-core                    | 3.121.3      |
| aws-sdk-kms                     | 1.50.0       |
| aws-sdk-s3                      | 1.104.0      |
| tsort                           | 0.1.0        |
| uri                             | 0.10.1       |
| set                             | 1.0.1        |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.0        |
| date                            | 3.1.0        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.0        |
| openssl                         | 2.2.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.2        |
| io-wait                         | 0.1.0        |
| zlib                            | 1.1.0        |
| resolv                          | 0.2.0        |
| securerandom                    | 0.1.0        |
| digest                          | 3.0.0        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.0        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.0        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.7        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| net-http                        | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| prettyprint                     | 0.1.0        |
| pp                              | 0.1.0        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.0        |
</details>

*generated on:* **2021-11-05**
</details>

**Comment by CyrilHu** [comment]
I set the duration time 1200 for API Key. please close this issue if  the duration is the reason.
```
    "DGD3G45D" => {
      :key_id => "3KDL49L2LD",
      :issuer_id => "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",
      :key => "-----BEGIN PRIVATE KEY-----\nXXXXX\n-----END PRIVATE KEY-----",
      :duration => 1200, 
    },
```

**Comment by pradyhk** [comment]
Seeing similar issue `get_provisioning_profile` . We were using `APP_STORE_CONNECT_API_KEY_DURATION =1200` as per suggestion here https://github.com/fastlane/fastlane/discussions/18100#discussioncomment-1030488 and was working fine from July 21, 2021 till now.. But getting this error `Authentication credentials are missing or invalid. - Provide a properly configured and signed bearer token, and make sure that it has not expired. Learn more about Generating Tokens for API Requests https://developer.apple.com/go/?id=api-generating-tokens` today

**Comment by destryteeter** [comment]
I too am seeing a similar issue.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.4                                                           |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.30.1 (Apple Git-130)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.4 (20F71)                                             |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.5.1                                                         |
| Swift Version               | 5.4.2                                                          |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
...
    desc <<~EOF
    Generate beta release for TestFlight (Available only to internal testers)

    - param ignore_git_cleanliness true to allow staged and unstaged changes
    - param ignore_build true to skip dependency build/breakdown, key generation, app building/uploading, and git commit/tag
    - param ignore_distribution true to skip distributing to internal testers and external test groups
    - param ignore_external_distribution true to skip distributing to external test groups
    EOF
    lane :beta do |options|
        if options[:ignore_git_cleanliness] != true
            # Make sure we're ready to commit and tag
            ensure_git_status_clean()
        end

        if options[:environments]
            pp_multiple_environments(
                options: options,
                lane: "beta",
            )
            next
        end

        # # Generate App Store Connect Key
        # pp_generate_key()

        if options[:ignore_build] != true
            # Build dependencies
            rebuild()

            # Increment Build
            pp_patch_product_version()

            # Build App
            pp_build_for_release()
        end

        # Prepare release
        pp_prepare_release()

        # Retreive beta notes
        localized_build_info = pp_generate_release_notes(log: true)

        if options[:ignore_build] != true
            # Upload and deliver
            upload_to_testflight(
                api_key_path: ENV['APP_STORE_CONNECT_API_KEY_JSON_PATH'],
                app_identifier: ENV['BUNDLE_IDENTIFIER'],
                team_id: ENV['TEAM_ID'],
                ipa: "./fastlane/builds/#{ENV['BUNDLE_IDENTIFIER']}/#{ENV['SCHEME']}.ipa",
                uses_non_exempt_encryption: false,
                localized_build_info: {
                    "default": {
                        whats_new: localized_build_info,
                    }
                },
                app_version: pp_app_version(version_only: true),
                build_number: pp_app_version(build_only: true),
            )
        end
        ...
    end
    ...
end
...
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.197.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status      |
| -------------------------- | ------- | ------------------ |
| fastlane-plugin-changelog  | 0.16.0  | ✅ Up-To-Date       |
| fastlane-plugin-versioning | 0.4.6   | 🚫 Update available |


<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| terminal-table                  | 1.8.0        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.0.0        |
| gh_inspector                    | 1.1.3        |
| security                        | 0.1.3        |
| bundler                         | 2.0.2        |
| simctl                          | 1.6.8        |
| retriable                       | 3.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| googleauth                      | 0.16.2       |
| httpclient                      | 2.8.3        |
| google-apis-core                | 0.4.0        |
| google-apis-playcustomapp_v1    | 0.5.0        |
| google-apis-androidpublisher_v3 | 0.8.0        |
| rexml                           | 3.2.5        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.0.3        |
| CFPropertyList                  | 3.0.3        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.20.0       |
| unicode-display_width           | 1.7.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| babosa                          | 1.0.4        |
| excon                           | 0.84.0       |
| ruby2_keywords                  | 0.0.4        |
| faraday-patron                  | 1.0.0        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-net_http                | 1.0.1        |
| faraday-httpclient              | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.5.1        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| fastimage                       | 2.2.4        |
| json                            | 2.5.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| jwt                             | 2.2.3        |
| trailblazer-option              | 0.1.1        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| mini_mime                       | 1.1.0        |
| signet                          | 0.15.0       |
| webrick                         | 1.7.0        |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.3        |
| google-apis-storage_v1          | 0.6.0        |
| google-apis-iamcredentials_v1   | 0.6.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.34.1       |
| emoji_regex                     | 3.2.2        |
| aws-eventstream                 | 1.1.1        |
| aws-sigv4                       | 1.2.4        |
| aws-partitions                  | 1.478.0      |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.117.0      |
| aws-sdk-kms                     | 1.44.0       |
| aws-sdk-s3                      | 1.96.1       |
| forwardable                     | 1.2.0        |
| logger                          | 1.3.0        |
| date                            | 2.0.0        |
| stringio                        | 0.0.2        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.0.0        |
| mutex_m                         | 0.1.0        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| io-console                      | 0.4.7        |
| fileutils                       | 1.1.0        |
| etc                             | 1.0.1        |
| libxml-ruby                     | 3.1.0        |
| psych                           | 3.1.0        |
| fastlane-plugin-changelog       | 0.16.0       |
| fastlane-plugin-versioning      | 0.4.6        |
</details>


*generated on:* **2021-11-08**
</details>

**Comment by ShreCap1** [comment]
Seeing similar on multiple instances:

16:50:08 | 💥   | sigh                       | 0           |
16:50:08 +------+----------------------------+-------------+
16:50:08 
16:50:08 fastlane finished with errors
16:50:08 
16:50:08 [!] The request could not be completed because:
16:50:08 	Authentication credentials are missing or invalid. - Provide a properly configured and signed bearer token, and make sure that it has not expired. Learn more about Generating Tokens for API Requests https://developer.apple.com/go/?id=api-generating-tokens
16:50:08 Build step 'Execute shell' marked build as failure

**Comment by Zboncak2** [comment]
First of all, am I correct in thinking that uploading to testflight is only possible nowadays with a 2-factor enabled account?
I'm trying to upload to testflight with the upload_to_testflight tool, but I'm struggling to get i working. Currently I'm using an Store Connect account without 2-factor for most of the lanes, with the credentials specified in FASTLANE_USER and FASTLANE_PASSWORD.
However, I have a different user for the upload_to_testflight lane, with credentials set in FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD in order to use the application specific password

**Comment by Buju77** [comment]
We are also receiving this issue. Sometimes it works and sometimes it fails. We even had this case of successful upload and we were already waiting for processing and then it suddenly failed 💥 

Log output:

```
[19:29:58]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[19:30:29]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[19:31:00]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[19:31:31]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[19:32:02]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[19:32:32]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[19:33:03]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[19:33:38]: Waiting for App Store Connect to finish processing the new build (12.10 - 12.10.0.32) for IOS
[19:34:09]: Waiting for App Store Connect to finish processing the new build (12.10 - 12.10.0.32) for IOS
[19:34:42]: Waiting for App Store Connect to finish processing the new build (12.10 - 12.10.0.32) for IOS
Looking for related GitHub issues on fastlane/fastlane...
[!] The request could not be completed because:
	Authentication credentials are missing or invalid. - Provide a properly configured and signed bearer token, and make sure that it has not expired. Learn more about Generating Tokens for API Requests https://developer.apple.com/go/?id=api-generating-tokens
```

**Comment by dgilbert-foreflight** [comment]
Curious if anyone here still experiencing this error can possibly relate to this issue I created
https://github.com/fastlane/fastlane/issues/19684

**Comment by Buju77** [comment]
yes, we are still experiencing this issue. error happens randomly. some builds uploads fine and some builds throws the Authentication credentials error :(

**Comment by cdoky** [comment]
This is Apple's problem. If this happens, you can go to AppStoreConnect and see if you can refresh the API key. If you can refresh the API key, you can execute the FastLane task and you are good.

**Comment by jvk75** [comment]
> This is Apple's problem. If this happens, you can go to AppStoreConnect and see if you can refresh the API key. If you can refresh the API key, you can execute the FastLane task and you are good.

@cdoky In case I explained in #19721 it is not expiring the API key but the session. Similarily, like in any Oauth2 session one has access token and refresh token. Access token being valid for only minutes and refresh token for longer periods (months even). Once access token expires the client (or who ever uses it) need to refresh the token with refresh token. Here we have similar issue. During wait the session expires and fastlane (or upload in this case) does not know how to refresh it but fails.

**Comment by rogerluan** [comment]
Did anyone find any solution to this? I'm facing the same problem: intermittent successes and failures, except that the difference between the moment I create my session (via `app_store_connect_api_key`) and the moment I need to use it (via `match`), only 8 seconds have lapsed. I've tried using duration of 500 and also 1200, both result in intermittent issues.

**Comment by rogerluan** [comment]
We've implemented and automatic retry in this scenario. Let us know if there're still issues around this topic.

**Comment by Dmytro-Mishchenko** [comment]
Started getting this again. Using the latest `2.205.2` after https://github.com/fastlane/fastlane/pull/19502 fix.

**Comment by rogerluan** [comment]
Hopefully https://github.com/fastlane/fastlane/pull/20206 will fix it 🙇

**Comment by Dmytro-Mishchenko** [comment]
Seems like issue is fully on a Apple side. 
More discussions here https://github.com/fastlane/fastlane/issues/20270
@rogerluan, I think you can close it again; sorry for the confusion 😀
