### ISSUE TITLE
[!] Invalid character "\xEF" in unquoted string on update_info_plist

### ISSUE THREAD

**Issue by mattvv** [fastlane/fastlane#19570]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm getting a new issue when trying to use update_info_plist.

I'm doing the following command:
```ruby
 update_info_plist(
      xcodeproj: "#{ENV['IOS_BUILD_PATH']}/iOS/Unity-iPhone.xcodeproj",
      plist_path: "Info.plist",
      block: proc do |plist|
        plist['ITSAppUsesNonExemptEncryption'] = false
      end
    )
```

which was working fine until about 6 days ago, Now i'm seeing the following error:
![image](https://user-images.githubusercontent.com/117194/140165901-89fbf2fe-12b8-468b-9681-649be59cacc6.png)

I've tried setting the following env vars:
```yml
      LANG: en_US.UTF-8
      LC_COLLATE: en_US.UTF-8
      LC_CTYPE: en_US.UTF-8
      LC_MESSAGES: en_US.UTF-8
      LC_MONETARY: en_US.UTF-8
      LC_NUMERIC: en_US.UTF-8
      LC_TIME: en_US.UTF-8
      LC_ALL: en_US.UTF-8
```

##### Command executed
update_info_plist 

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> bundler: failed to load command: fastlane (/usr/local/lib/ruby/gems/2.7.0/bin/fastlane)
/usr/local/lib/ruby/gems/2.7.0/gems/nanaimo-0.3.0/lib/nanaimo/reader.rb:284:in `raise_parser_error': [!] \e[31m[!] [!] Invalid character "\\xEF" in unquoted string (Nanaimo::Reader::ParseError)
 #  -------------------------------------------
1>  ﻿<?xml version="1.0" encoding="utf-8"?>
    ^
 #  <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
 #  <plist version="1.0">
 #  -------------------------------------------
\e[0m
 #  -------------------------------------------
1>  ﻿<?xml version="1.0" encoding="utf-8"?>
    ^
 #  <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
 #  <plist version="1.0">
 #  -------------------------------------------
	from /usr/local/lib/ruby/gems/2.7.0/gems/nanaimo-0.3.0/lib/nanaimo/reader.rb:150:in `parse_string'
	from /usr/local/lib/ruby/gems/2.7.0/gems/nanaimo-0.3.0/lib/nanaimo/reader.rb:140:in `parse_object'
	from /usr/local/lib/ruby/gems/2.7.0/gems/nanaimo-0.3.0/lib/nanaimo/reader.rb:107:in `parse!'
	from /usr/local/lib/ruby/gems/2.7.0/gems/xcodeproj-1.21.0/lib/xcodeproj/plist.rb:27:in `read_from_path'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/actions/update_plist.rb:18:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/actions/update_info_plist.rb:37:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:23:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.197.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.197.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:25:in `load'
	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:25:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.30/lib/bundler/cli/exec.rb:58:in `load'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.30/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.30/lib/bundler/cli/exec.rb:23:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.30/lib/bundler/cli.rb:478:in `exec'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.30/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.30/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.30/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.30/lib/bundler/cli.rb:31:in `dispatch'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.30/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.30/lib/bundler/cli.rb:25:in `start'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.30/exe/bundle:49:in `block in <top (required)>'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.30/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.30/exe/bundle:37:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.7.0/bin/bundle:23:in `load'
	from /usr/local/lib/ruby/gems/2.7.0/bin/bundle:23:in `<main>'
Error: Error: Executing lane ios beta failed.
Error: Executing lane ios beta failed.</pre>
</details>

### Environment
Github Actions CI OSX

**Comment by QuiZr** [comment]
I have the same issue, including env results

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 12.0.1                                                         |
| Ruby                        | 2.6.8                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.30.1 (Apple Git-130)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 12.0.1 (21A559)                                          |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 13.1                                                           |
| Swift Version               | 5.5.1                                                          |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | pl_PL.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
keychain_name = "temporary_keychain"
keychain_password = SecureRandom.base64

platform :android do
  desc "Upload a new Android version to the Google Play Store"
  lane :internal do
    upload_to_play_store(track: 'internal',release_status: 'completed',aab: "#{ENV['ANDROID_BUILD_FILE_PATH']}")
  end
  lane :alpha do
    upload_to_play_store(track: 'alpha',release_status: 'completed',aab: "#{ENV['ANDROID_BUILD_FILE_PATH']}")
  end
end

platform :ios do

  desc "Push a new release build to the App Store"
  lane :release do
    build
    api_key = app_store_connect_api_key(
      key_id: "#{ENV['APPSTORE_KEY_ID']}",
      issuer_id: "#{ENV['APPSTORE_ISSUER_ID']}",
      key_filepath: "#{ENV['APPSTORE_P8_PATH']}",
      duration: 1200, # optional
      in_house: false, # true for enterprise and false for individual accounts
    )
    upload_to_app_store(api_key: api_key)
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    # Automate Missing export compliance error
    # Comment out when resolved: https://github.com/fastlane/fastlane/issues/19570
    #update_info_plist(
    #  xcodeproj: "#{ENV['IOS_BUILD_PATH']}/iOS/Unity-iPhone.xcodeproj",
    #  plist_path: "Info.plist",
    #  block: proc do |plist|
    #    plist['ITSAppUsesNonExemptEncryption'] = false
    #  end
    #)
    build
    api_key = app_store_connect_api_key(
      key_id: "#{ENV['APPSTORE_KEY_ID']}",
      issuer_id: "#{ENV['APPSTORE_ISSUER_ID']}",
      key_filepath: "#{ENV['APPSTORE_P8_PATH']}",
      duration: 1200, # optional
      in_house: false, # true for enterprise and false for individual accounts
    )
    upload_to_testflight(skip_waiting_for_build_processing: true, api_key: api_key)
  end

  desc "Create .ipa"
  lane :build do
    update_code_signing_settings(use_automatic_signing: false, path: "#{ENV['IOS_BUILD_PATH']}/iOS/Unity-iPhone.xcodeproj")
    certificates
    update_project_provisioning(
      xcodeproj: "#{ENV['IOS_BUILD_PATH']}/iOS/Unity-iPhone.xcodeproj",
      target_filter: "Unity-iPhone",
      profile: ENV["sigh_#{ENV["IOS_APP_ID"]}_appstore_profile-path"],
      code_signing_identity: "Apple Distribution: #{ENV['APPLE_TEAM_NAME']} (#{ENV['APPLE_TEAM_ID']})"
    )
    increment_build_number(
       xcodeproj: "#{ENV['IOS_BUILD_PATH']}/iOS/Unity-iPhone.xcodeproj"
    )
    gym(
      project: "#{ENV['IOS_BUILD_PATH']}/iOS/Unity-iPhone.xcodeproj",
      scheme: "Unity-iPhone",
      clean: true,
      skip_profile_detection: true,
      codesigning_identity: "Apple Distribution: #{ENV['APPLE_TEAM_NAME']} (#{ENV['APPLE_TEAM_ID']})",
      export_method: "app-store",
      export_options: {
        method: "app-store",
        provisioningProfiles: {
          ENV["IOS_APP_ID"] => "match AppStore #{ENV['IOS_APP_ID']}"
        }
      }
    )
  end

  desc "Synchronize certificates"
  lane :certificates do
    cleanup_keychain
    create_keychain(
      name: keychain_name,
      password: keychain_password,
      default_keychain: true,
      lock_when_sleeps: true,
      timeout: 3600,
      unlock: true
    )
    match(
      type: "appstore",
      readonly: true,
      keychain_name: keychain_name,
      keychain_password: keychain_password
    )
  end

  lane :cleanup_keychain do
    if File.exist?(File.expand_path("~/Library/Keychains/#{keychain_name}-db"))
      delete_keychain(name: keychain_name)
    end
  end

  after_all do
    if File.exist?(File.expand_path("~/Library/Keychains/#{keychain_name}-db"))
      delete_keychain(name: keychain_name)
    end
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
for_platform :ios do
  app_identifier(ENV["IOS_APP_ID"])

  apple_dev_portal_id(ENV["APPLE_DEVELOPER_EMAIL"])
  itunes_connect_id(ENV["APPLE_CONNECT_EMAIL"])

  team_id(ENV["APPLE_TEAM_ID"])
  itc_team_id(ENV["APPLE_TEAM_ID"])
end

for_platform :android do
  package_name(ENV["ANDROID_PACKAGE_NAME"])
  json_key_file(ENV["GOOGLE_PLAY_KEY_FILE_PATH"])
end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.197.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| fastimage                       | 2.2.5        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 1.17.2       |
| simctl                          | 1.6.8        |
| google-cloud-env                | 1.5.0        |
| google-cloud-core               | 1.6.0        |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.34.1       |
| rexml                           | 3.2.5        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.0.3        |
| CFPropertyList                  | 3.0.4        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.21.0       |
| unicode-display_width           | 1.8.0        |
| excon                           | 0.88.0       |
| ruby2_keywords                  | 0.0.5        |
| faraday-rack                    | 1.0.0        |
| faraday-patron                  | 1.0.0        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-net_http                | 1.0.1        |
| faraday-httpclient              | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.8.0        |
| unf_ext                         | 0.0.8        |
| faraday_middleware              | 1.2.0        |
| json                            | 2.6.1        |
| jwt                             | 2.3.0        |
| webrick                         | 1.7.0        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| signet                          | 0.16.0       |
| os                              | 1.1.1        |
| memoist                         | 0.16.2       |
| googleauth                      | 1.1.0        |
| mini_mime                       | 1.1.2        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.1        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| google-apis-core                | 0.4.1        |
| google-apis-playcustomapp_v1    | 0.6.0        |
| google-apis-androidpublisher_v3 | 0.13.0       |
| google-cloud-errors             | 1.2.0        |
| google-apis-iamcredentials_v1   | 0.8.0        |
| google-apis-storage_v1          | 0.9.0        |
| rake                            | 13.0.6       |
| emoji_regex                     | 3.2.3        |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-partitions                  | 1.525.0      |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.122.0      |
| aws-sdk-kms                     | 1.51.0       |
| aws-sdk-s3                      | 1.105.1      |
| forwardable                     | 1.2.0        |
| logger                          | 1.3.0        |
| date                            | 2.0.0        |
| stringio                        | 0.0.2        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.0.0        |
| mutex_m                         | 0.1.0        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| io-console                      | 0.4.7        |
| fileutils                       | 1.1.0        |
| etc                             | 1.0.1        |
| libxml-ruby                     | 3.2.1        |
| psych                           | 3.1.0        |
</details>


*generated on:* **2021-11-06**
</details>

**Comment by kocyigityunus** [comment]
I had the same problem. 

in my case, Unity was generating a false Info.plist with utf-8 bom encoding file.
so, i had to read and rewrite it as default utf-8

```
# fix Info.plist encoding issue
info_plist_content = File.open("../Info.plist", "r:bom|utf-8", &:read)
File.write('../Info.plist', info_plist_content)
```

**Comment by QuiZr** [comment]
If you're using Unity you can also use [this](https://gist.github.com/TiborUdvari/4679d636b17ddff0d83065eefa399c04) instead.
