### ISSUE TITLE
Error uploading AppStore 

### ISSUE THREAD

**Issue by 643824979** [fastlane/fastlane#19595]
gym  success

deliver(
        submit_for_review: true,
        automatic_release: false,
        force: true,
        team_id:"*****",
        team_name:"****",
        app_identifier:"*****",
        skip_metadata: true,
        skip_screenshots: true,
        skip_app_version_update: true,
        run_precheck_before_submit: false
    )
Run `fastlane env` to append the fastlane environment to your issue
/Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/credentials_manager/lib/credentials_manager/account_manager.rb:135:in `ask_for_login': \e[31m[!] Missing password for user zhoulinglong01@vcredit.com, and running in non-interactive shell\e[0m (RuntimeError)
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/credentials_manager/lib/credentials_manager/account_manager.rb:56:in `password'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:585:in `handle_two_step_failure'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:494:in `rescue in upload'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:491:in `upload'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/deliver/lib/deliver/runner.rb:189:in `upload_binary'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/deliver/lib/deliver/runner.rb:59:in `run'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:22:in `run'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:131:in `block (2 levels) in parsing_binding'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/bin/fastlane:23:in `<top (required)>'
	from /Users/luoshuibo/.rvm/gems/ruby-3.0.0/bin/fastlane:25:in `load'
	from /Users/luoshuibo/.rvm/gems/ruby-3.0.0/bin/fastlane:25:in `<main>'
	from /Users/luoshuibo/.rvm/gems/ruby-3.0.0/bin/ruby_executable_hooks:22:in `eval'
	from /Users/luoshuibo/.rvm/gems/ruby-3.0.0/bin/ruby_executable_hooks:22:in `<main>'
/Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:73:in `execute': FastlaneCore::TransporterRequiresApplicationSpecificPasswordError (FastlaneCore::TransporterRequiresApplicationSpecificPasswordError)
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:385:in `block in execute'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/fileutils.rb:139:in `chdir'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/fileutils.rb:139:in `cd'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:384:in `execute'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:492:in `upload'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/deliver/lib/deliver/runner.rb:189:in `upload_binary'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/deliver/lib/deliver/runner.rb:59:in `run'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:22:in `run'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:131:in `block (2 levels) in parsing_binding'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /Users/luoshuibo/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/fastlane-2.197.0/bin/fastlane:23:in `<top (required)>'
	from /Users/luoshuibo/.rvm/gems/ruby-3.0.0/bin/fastlane:25:in `load'
	from /Users/luoshuibo/.rvm/gems/ruby-3.0.0/bin/fastlane:25:in `<main>'
	from /Users/luoshuibo/.rvm/gems/ruby-3.0.0/bin/ruby_executable_hooks:22:in `eval'
	from /Users/luoshuibo/.rvm/gems/ruby-3.0.0/bin/ruby_executable_hooks:22:in `<main>'

**Comment by 643824979** [comment]
[09:59:05]: /Users/luoshuibo/Documents/打包目录/IOS/kaka_jinchan/appstore/4.7.5.693/kaka.ipa
[09:59:05]: [32m---------------------[0m
[09:59:05]: [32m--- Step: deliver ---[0m
[09:59:05]: [32m---------------------[0m
[09:59:05]: [32mSuccessfully loaded '/Users/luoshuibo/.jenkins/workspace/kakadai_jinchan_iOS/fastlane/Deliverfile' 📄[0m
[09:59:05]: [33mNo values defined in './fastlane/Deliverfile'[0m
[09:59:05]: Login to App Store Connect (zhoulinglong01@vcredit.com)
[09:59:09]: Login successful
+--------------------------------------+----------------------------------------------------------------------------------+
|                                                 [32mdeliver 2.197.0 Summary[0m                                                 |
+--------------------------------------+----------------------------------------------------------------------------------+
| submit_for_review                    | true                                                                             |
| automatic_release                    | false                                                                            |
| force                                | true                                                                             |
| team_id                              | ***                                                                        |
| team_name                            | ***                                                 |
| app_identifier                       | ****                                                                 |
| skip_metadata                        | true                                                                             |
| skip_screenshots                     | true                                                                             |
| skip_app_version_update              | true                                                                             |
| run_precheck_before_submit           | false                                                                            |
| ipa                                  | /Users/luoshuibo/Documents/打包目录/IOS/kaka_jinchan/appstore/4.7.5.693/kaka.ipa |
| screenshots_path                     | ./fastlane/screenshots                                                           |
| metadata_path                        | ./fastlane/metadata                                                              |
| app_version                          | 4.7.5                                                                            |
| username                             | zhoulinglong01@vcredit.com                                                       |
| platform                             | ios                                                                              |
| edit_live                            | false                                                                            |
| use_live_version                     | false                                                                            |
| skip_binary_upload                   | false                                                                            |
| overwrite_screenshots                | false                                                                            |
| sync_screenshots                     | false                                                                            |
| reject_if_possible                   | false                                                                            |
| phased_release                       | false                                                                            |
| reset_ratings                        | false                                                                            |
| dev_portal_team_id                   | 118993496                                                                        |
| precheck_default_rule_level          | warn                                                                             |
| ignore_language_directory_validation | false                                                                            |
| precheck_include_in_app_purchases    | true                                                                             |
+--------------------------------------+----------------------------------------------------------------------------------+

[09:59:13]: Uploading binary to App Store Connect
[09:59:22]: [31mTransporter transfer failed.[0m
[09:59:22]: 
[09:59:22]: [31mPlease sign in with an app-specific password. You can create one at appleid.apple.com. (-22910)
[0m
[09:59:23]: 
[09:59:23]: [31mYour account has 2 step verification enabled[0m
[09:59:23]: [31mPlease go to https://appleid.apple.com/account/manage[0m
[09:59:23]: [31mand generate an application specific password for[0m
[09:59:23]: [31mthe iTunes Transporter, which is used to upload builds[0m
[09:59:23]: 
[09:59:23]: [31mTo set the application specific password on a CI machine using[0m
[09:59:23]: [31man environment variable, you can set the[0m
[09:59:23]: [31mFASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD variable[0m
[32m-------------------------------------------------------------------------------------[0m
[32mPlease provide your Apple Developer Program account credentials[0m
[32mThe login information you enter will be stored in your macOS Keychain[0m
[32m-------------------------------------------------------------------------------------[0m
[09:59:23]: Going to upload updated app to App Store Connect
[09:59:23]: [32mThis might take a few minutes. Please don't interrupt the script.[0m
[09:59:29]: [31mTransporter transfer failed.[0m
[09:59:29]: 
[09:59:29]: [31mPlease sign in with an app-specific password. You can create one at appleid.apple.com. (-22910)
[0m
[09:59:29]: 
[09:59:29]: [31mYour account has 2 step verification enabled[0m
[09:59:29]: [31mPlease go to https://appleid.apple.com/account/manage[0m
[09:59:29]: [31mand generate an application specific password for[0m
[09:59:29]: [31mthe iTunes Transporter, which is used to upload builds[0m
[09:59:29]: 
[09:59:29]: [31mTo set the application specific password on a CI machine using[0m
[09:59:29]: [31man environment variable, you can set the[0m
[09:59:29]: [31mFASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD variable[0m
[32m-------------------------------------------------------------------------------------[0m
[32mPlease provide your Apple Developer Program account credentials[0m
[32mThe login information you enter will be stored in your macOS Keychain[0m
[32m-------------------------------------------------------------------------------------[0m
+--------------------+-------------------------------------------------------------------------------------------------+
|                                                     [33mLane Context[0m                                                     |
+--------------------+-------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM   | ios                                                                                             |
| PLATFORM_NAME      | ios                                                                                             |
| LANE_NAME          | ios prod                                                                                        |
| VERSION_NUMBER     | 4.7.5                                                                                           |
| BUILD_NUMBER       | 693                                                                                             |
| IPA_OUTPUT_PATH    | /Users/luoshuibo/Documents/打包目录/IOS/kaka_jinchan/appstore/4.7.5.693/kaka.ipa                |
| XCODEBUILD_ARCHIVE | /Users/luoshuibo/Library/Developer/Xcode/Archives/2021-11-11/kaka 2021-11-11 09.56.02.xcarchive |
| DSYM_OUTPUT_PATH   | /Users/luoshuibo/Documents/打包目录/IOS/kaka_jinchan/appstore/4.7.5.693/kaka.app.dSYM.zip       |
+--------------------+-------------------------------------------------------------------------------------------------+
[09:59:29]: [31mMissing password for user zhoulinglong01@vcredit.com, and running in non-interactive shell[0m

+------+------------------------------+-------------+
|                 [32mfastlane summary[0m                  |
+------+------------------------------+-------------+
| Step | Action                       | Time (in s) |
+------+------------------------------+-------------+
| 1    | default_platform             | 0           |
| 2    | update_code_signing_settings | 0           |
| 3    | update_code_signing_settings | 0           |
| 4    | get_version_number           | 0           |
| 5    | get_build_number             | 0           |
| 6    | gym                          | 190         |
| 💥   | [31mdeliver[0m                      | 23          |
+------+------------------------------+-------------+

[09:59:29]: [31mfastlane finished with errors[0m

**Comment by lucgrabowski** [comment]
Hi @643824979, you got the error, because you didn't provide username and password and you're running deliver in non-interactive shell. I understand that you run deliver on CI.

You can read more in docs:
1. http://docs.fastlane.tools/advanced/other/#adding-credentials
2. http://docs.fastlane.tools/best-practices/continuous-integration/#environment-variables-to-set
3. https://github.com/fastlane/fastlane/tree/master/credentials_manager
