### ISSUE TITLE
notarize fails with `method_missing` when using Xcode 12 (altool)

### ISSUE THREAD

**Issue by unityfeth** [fastlane/fastlane#19640]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
1) ~The `fastlane notarize` command fails with non-zero status when I specify `use_notarytool:false` or when I actually switch to Xcode 12 (`xcode-select -s /Applications/Xcode_12.app`) so that it uses Fastlane's `altool` code path.~

   ~Our CI servers use Xcode 12, and they may continue to do so for some time, so I would like to ask if you can address this failure when trying to use the older `altool` command.~

   _**UPDATE:** This (cryptic) failure seems to have been the result of user-error (wrong app-specific password)._

2) Also, I noticed the `skip_stapling` parameter is not mentioned in the [notarize docs](https://docs.fastlane.tools/actions/notarize/#parameters-legend-dynamic). Please consider adding it to the documented list of parameters.

   ps. The `notarize skip_stapling:true` action works great with Xcode 13 (`notarytool`). Thanks again to Kyle for addressing #17667 with PR #19577!

##### Command executed
```
env FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD=redacted bundle exec fastlane run notarize skip_stapling:true package:path/to/package.zip asc_provider:TeamID username:user@email.com bundle_id:com.foo.bar123
```

##### Complete output when running fastlane, including the stack trace and command used
<details><summary>fastlane notarize failure output</summary>
  <pre>$ env FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD=redacted bundle exec fastlane run notarize skip_stapling:true package:path/to/package.zip asc_provider:TeamID username:user@email.com bundle_id:com.foo.bar123
[✔] 🚀 
[17:29:43]: ----------------------
[17:29:43]: --- Step: notarize ---
[17:29:43]: ----------------------
[17:29:43]: Uploading package to notarization service, might take a while

Looking for related GitHub issues on fastlane/fastlane...

➡️  Shell command exited with exit status 2 instead of 0.
    https://github.com/fastlane/fastlane/issues/19339 [open] 4 💬
    2 weeks ago

➡️  create_keychain throwing Shell command exited with exit status 162 instead of 0
    https://github.com/fastlane/fastlane/issues/19374 [open] 3 💬
    2 weeks ago

➡️  Improve Beta Setup
    https://github.com/fastlane/fastlane/pull/1 [closed] 1 💬
    04 Feb 2017

and 92 more at: https://github.com/fastlane/fastlane/search?q=Shell%20command%20exited%20with%20exit%20status%201%20instead%20of%200.&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	28: from /Users/bill.feth/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
	27: from /Users/bill.feth/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
	26: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/bin/fastlane:23:in `<main>'
	25: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/bin/fastlane:23:in `load'
	24: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/bin/fastlane:23:in `<top (required)>'
	23: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	22: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	21: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	20: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	19: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	18: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	17: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	16: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	15: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/commands_generator.rb:225:in `block (2 levels) in run'
	14: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/one_off.rb:22:in `execute'
	13: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/one_off.rb:42:in `run'
	12: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	11: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	10: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	 9: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	 8: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 7: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/actions/notarize.rb:44:in `run'
	 6: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/actions/notarize.rb:117:in `altool'
	 5: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/actions/notarize.rb:240:in `with_notarize_authenticator'
	 4: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/actions/notarize.rb:120:in `block in altool'
	 3: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
	 2: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	 1: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': Shell command exited with exit status 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
	28: from /Users/bill.feth/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
	27: from /Users/bill.feth/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
	26: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/bin/fastlane:23:in `<main>'
	25: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/bin/fastlane:23:in `load'
	24: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/bin/fastlane:23:in `<top (required)>'
	23: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	22: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	21: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	20: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	19: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	18: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	17: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	16: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	15: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/commands_generator.rb:225:in `block (2 levels) in run'
	14: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/one_off.rb:22:in `execute'
	13: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/one_off.rb:42:in `run'
	12: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	11: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	10: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	 9: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	 8: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 7: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/actions/notarize.rb:44:in `run'
	 6: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/actions/notarize.rb:117:in `altool'
	 5: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/actions/notarize.rb:240:in `with_notarize_authenticator'
	 4: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/actions/notarize.rb:120:in `block in altool'
	 3: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
	 2: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	 1: from /Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/bill.feth/Projects/sdk/.gems/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': [!] Shell command exited with exit status 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
</pre>
</details>

<details><summary>fastlane notarize --capture_output output</summary>
  <pre>$ env FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD=redacted bundle exec fastlane run notarize skip_stapling:true package:path/to/package.zip asc_provider:<team_id> username:<email> bundle_id:com.foo.bar123 asc_provider:TeamShortname username:user@email.com bundle_id:com.foo.bar123 use_notarytool:false --capture_output
[✔] 🚀 
DEBUG [2021-11-23 17:59:52.69]: Checking if there are any plugins that should be loaded...
DEBUG [2021-11-23 17:59:52.84]: Using skip_stapling: true
DEBUG [2021-11-23 17:59:52.84]: Using package: path/to/package.zip
DEBUG [2021-11-23 17:59:52.84]: Using asc_provider: TeamShortname
DEBUG [2021-11-23 17:59:52.84]: Using username: user@email.com
DEBUG [2021-11-23 17:59:52.84]: Using bundle_id: com.foo.bar123
DEBUG [2021-11-23 17:59:52.84]: Using use_notarytool: false
</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                               |
| --------------------------- | --------------------------------------------------- |
| OS                          | 11.6.1                                              |
| Ruby                        | 2.6.3                                               |
| Bundler?                    | true                                                |
| Git                         | git version 2.30.1 (Apple Git-130)                  |
| Installation Source         | ~/Projects/sdk/.gems/bundle/ruby/2.6.0/bin/fastlane |
| Host                        | macOS 11.6.1 (20G224)                               |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.3/lib                        |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                         |
| Is contained                | false                                               |
| Is homebrew                 | false                                               |
| Is installed via Fabric.app | false                                               |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/         |
| Xcode Version               | 13.1                                                |
| Swift Version               | 5.5.1                                               |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

Omitted - the failure occurs without invoking any lanes from our Fastfile.

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.198.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.534.0      |
| aws-sigv4                       | 1.4.0        |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.123.0      |
| aws-sdk-kms                     | 1.51.0       |
| aws-sdk-s3                      | 1.107.0      |
| babosa                          | 1.0.4        |
| bundler                         | 2.1.4        |
| claide                          | 1.0.3        |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.88.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| multipart-post                  | 2.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.8.0        |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.5        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.3.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.0        |
| httpclient                      | 2.8.3        |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-androidpublisher_v3 | 0.13.0       |
| google-apis-playcustomapp_v1    | 0.6.0        |
| google-apis-iamcredentials_v1   | 0.8.0        |
| google-apis-storage_v1          | 0.9.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.34.1       |
| json                            | 2.6.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
</details>

*generated on:* **2021-11-23**
</details>

**Comment by unityfeth** [comment]
Well, good news--this was due to user error. I think I happened to pass the wrong app-specific password via `env FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` when I was testing the Xcode 12 / altool case. You can repro the (obtuse) error message if you supply mismatched credentials.

When I ran the use_notarytool:false case again (with the right app-specific password), I was able to successfully notarize our app!

I will leave this open in case you feel item #2 above needs to be addressed (documentation of `skip_stapling`).

**Comment by macblazer** [comment]
The website docs for specific actions are automatically generated from the code on some frequency that I don't know.  The link you have to the [notarize docs](https://docs.fastlane.tools/actions/notarize/) _does_ show the `skip_stapling` parameter now.

Still, the `notarize` code could definitely use some better error handling and unit tests of the error handling.

**Comment by unityfeth** [comment]
Thanks @macblazer! Sounds like this ticket can be closed as "cannot repro" or similar.

Closing.

**Comment by unityfeth** [comment]
Just wanted to circle back and say thanks. We're using fastlane notarize in production for the first time now!
