### ISSUE TITLE
error: “FirebaseAnalytics.framework” couldn’t be copied to “debug-iphoneos” because an item with the same name already exists.

### ISSUE THREAD

**Issue by geeklingo** [fastlane/fastlane#19645]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I keep getting the following error when building via FastLane:

```
▸ Compiling GULNSData+zlib.m
❌  error: “FirebaseAnalytics.framework” couldn’t be copied to “debug-iphoneos” because an item with the same name already exists.
[16:36:52]: Exit status: 65
[16:36:52]: 
[16:36:52]: Maybe the error shown is caused by using the wrong version of Xcode
[16:36:52]: Found multiple versions of Xcode in '/Applications/'
[16:36:52]: Make sure you selected the right version for your project
[16:36:52]: This build process was executed using '/Applications/Xcode-13.1.app'
[16:36:52]: If you want to update your Xcode path, either
```
and sometimes i see this
```
** ARCHIVE FAILED **
The following build commands failed:
	ProcessXCFramework /Users/myuser/Library/Developer/Xcode/DerivedData/myApp-fvbagbmzujvhscasknrtxnjwwvzq/SourcePackages/artifacts/Firebase/FirebaseAnalytics.xcframework /Users/myuser/Library/Developer/Xcode/DerivedData/myApp-fvbagbmzujvhscasknrtxnjwwvzq/Build/Intermediates.noindex/ArchiveIntermediates/myApp/BuildProductsPath/release-iphoneos/FirebaseAnalytics.framework ios
(1 failure)
▸ Compiling GULNSData+zlib.m
▸ Compiling GULNSData+zlib.m
❌  error: “FirebaseAnalytics.framework” couldn’t be removed because you don’t have permission to access it.
ERROR [2021-11-26 10:45:03.27]: Exit status: 65
INFO [2021-11-26 10:45:03.28]: 
WARN [2021-11-26 10:45:03.28]: Maybe the error shown is caused by using the wrong version of Xcode
WARN [2021-11-26 10:45:03.28]: Found multiple versions of Xcode in '/Applications/'
WARN [2021-11-26 10:45:03.28]: Make sure you selected the right version for your project
WARN [2021-11-26 10:45:03.28]: This build process was executed using '/Applications/Xcode-13.1.app'
WARN [2021-11-26 10:45:03.28]: If you want to update your Xcode path, either

```

Building via XCode works fine without error, only via pipeline it keeps failing with this error.

##### Command executed

bundle exec fastlane

### Captured Output

Command Used: `--capture_output`
<details><summary>Output/Log</summary>

```

DEBUG [2021-11-25 20:59:43.29]: Checking if there are any plugins that should be loaded...
DEBUG [2021-11-25 20:59:43.29]: Loading 'fastlane-plugin-wait_xcrun' plugin
INFO [2021-11-25 20:59:43.29]: gem 'fastlane-plugin-wait_xcrun' is already installed


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 12.0.1                                      |
| Ruby                        | 3.0.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.23.0                          |
| Installation Source         | ~/.rbenv/versions/3.0.2/bin/fastlane        |
| Host                        | macOS 12.0.1 (21A559)                       |
| Ruby Lib Dir                | ~/.rbenv/versions/3.0.2/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 13.1                                        |
| Swift Version               | 5.5.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

#Parse the config file
config_file = File.read("config.json")
config = JSON.parse(config_file)

#Info from parsed config object
xcode_version = config["xcode_version"]
schemes = config["schemes"]

testable_schemes = config["testable_schemes"] || []
ENV["SLACK_URL"] = config["slack_webhook_url"] || ""


platform :ios do
  before_all do
    # Clean up DerivedData folder (otherwise build slave eventually runs out of disk space)
    clear_derived_data

    # Specify Xcode version
    xcversion(version: xcode_version)
    wait_xcrun
  end

  ##### PUBLIC #####
  desc "Build only"
  lane :build_only do
    # Clean up DerivedData folder (otherwise build slave eventually runs out of disk space)
    clear_derived_data

    run_build_app(upload: false)
  end

  desc "Unit tests only"
  lane :test_only do
    # Clean up DerivedData folder (otherwise build slave eventually runs out of disk space)
    clear_derived_data

    run_unit_tests
  end

  desc "Build and Test"
  lane :test_and_build do
    # Clean up DerivedData folder (otherwise build slave eventually runs out of disk space)
    clear_derived_data

    test_only
    build_only
  end

  desc "Build, Test and Deploy to TestFlight"
  lane :build_and_upload do
    # Clean up DerivedData folder (otherwise build slave eventually runs out of disk space)
    clear_derived_data

    test_only
    increment_build_number build_number: ENV["CI_BUILD_ID"]
    run_build_app(upload: true)
  end

  desc "Deploy to DEV"
  lane :build_and_upload_dev do
    # Clean up DerivedData folder (otherwise build slave eventually runs out of disk space)
    clear_derived_data

    puts "Deploying #{schemes[0]}".red
    increment_build_number build_number: ENV["CI_BUILD_ID"]
    run_targetted_build_app(
      upload: true,
      app_id: "au.com.myco.myapp.dev",
      scheme: "myapp_dev",
      gsp_path: "myapp/Config/GoogleService-Info-debug.plist"
    )
  end

  desc "Deploy to PRD"
  lane :build_and_upload_prd do
    # Clean up DerivedData folder (otherwise build slave eventually runs out of disk space)
    clear_derived_data

    puts "Deploying #{schemes[1]}".green
    increment_build_number build_number: ENV["CI_BUILD_ID"]
    run_targetted_build_app(
      upload: true,
      app_id: "au.com.myco.myapp",
      scheme: "myapp",
      gsp_path: "myapp/Config/GoogleService-Info-release.plist"
    )
  end


  desc "Download dSYM files from App Store Connect after the ipa gets re-compiled by Apple"
  # lane :refresh_dsyms do
  #   download_dsyms(build_number: ENV["CI_BUILD_ID"])                  # Download dSYM files from iTC
  #   upload_symbols_to_crashlytics                                     # Upload them to Crashlytics
  #   clean_build_artifacts                                             # Delete the local dSYM files
  # end
  lane :refresh_dsyms do |options|
    buildVersion = options[:buildVersion]
    buildNumber = options[:buildNumber]
    gspPath = options[:gspPath]
    appIdentifier = options[:appIdentifier]
    scheme = options[:scheme]
    binary_path = options[:binary_path]

    puts "--------------------------------"
    puts "Starting dSYM updates".white

    if appIdentifier.nil? || appIdentifier.empty?
      # Command run from command prompt so will cycle through all the environments and update
      for scheme in schemes do
        puts "Running via CLI"
        puts "Using app_id: #{scheme["app_id"]}".blue
        puts "Using Google PLIST: #{scheme["gsp_path"]}".blue
        puts "--------------------------------"

        # As Firebase added to project through SPM the location of upload-symbols
        # script is not handled by upload_symbols_to_crashlytics automatically,
        # so we need to find it and provide to action
        UPLOAD_SYMBOLS_PATH=`xcodebuild -project ../myapp.xcodeproj -showBuildSettings -scheme #{scheme["scheme_name"]} | grep -m 1 "BUILD_DIR" | grep -oEi "\/.*" | sed 's:Build/Products:SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/upload-symbols:' | tr -d '\n'`
        UI.success "UPLOAD_SYMBOLS_PATH = #{UPLOAD_SYMBOLS_PATH}"

        # Download dSYM files from iTC
        start_date = DateTime.now - 30
        download_dsyms(
            app_identifier: scheme["app_id"],
            after_uploaded_date: start_date.iso8601
        )

        # Upload them to Crashlytics
        upload_symbols_to_crashlytics(
          dsym_paths: Actions.lane_context[SharedValues::DSYM_PATHS],
          gsp_path: scheme["gsp_path"],
          binary_path: UPLOAD_SYMBOLS_PATH,
          dsym_worker_threads: 3
        )

        # Delete the local dSYM files
        clean_build_artifacts
      end

    else
      puts "Running via Fastlane Pipeline"
      puts "Using app_id: #{appIdentifier}".yellow
      puts "Using gsp_path: #{gspPath}".yellow
      puts "--------------------------------"

      # Download dSYM files from iTC
      download_dsyms(
          app_identifier: options[:appIdentifier],
          build_number:   ENV["CI_BUILD_ID"]
      )

      # Upload them to Crashlytics
      upload_symbols_to_crashlytics(
          gsp_path: gspPath,
          binary_path:  UPLOAD_SYMBOLS_PATH
      )
    end

    # Delete the local dSYM files
    clean_build_artifacts
  end


  ##### PRIVATE #####

  desc "Run unit tests for testable_schemes"
  private_lane :run_unit_tests do
    if testable_schemes.length > 0
      for scheme_object in testable_schemes do

        # scan related (`fastlane action scan` for more info)
        ENV["SCAN_CLEAN"] = "true"
        ENV["SCAN_SCHEME"] = scheme_object["scheme_name"]
        ENV["SCAN_XCARGS"] = "ONLY_ACTIVE_ARCH='YES'"

        scan(
          code_coverage: true,
          devices: scheme_object["devices"],
          skip_slack: true,
          derived_data_path: "./DerivedData",
          output_directory: "./fastlane/reports"
        )
      end
    else
      puts "No unit tests run".blue
    end
  end

  desc "Run build"
  private_lane :run_build_app do |options|
    is_upload_lane = options[:upload]

    commitslog = changelog_from_git_commits(pretty: '- %s', merge_commit_filtering: "exclude_merges")
    puts commitslog.blue

    for scheme in schemes do
      build_app(
        scheme: scheme["scheme_name"],
        include_bitcode: true,
        export_xcargs: "-allowProvisioningUpdates",
        export_method: "app-store",
        export_options: {
          provisioningProfiles: {
            "au.com.myco.myapp" => "match AppStore au.com.myco.myapp" ,
            "au.com.myco.myapp.dev" => "match AppStore au.com.myco.myapp.dev"
          }
        }
      )

      if is_upload_lane
        app_store_connect_api_key(
          key_id: ENV['APPSTORE_KEY_ID'],
          issuer_id: ENV['APPSTORE_ISSUER_ID'],
          key_filepath: ENV['APPSTORE_KEY_FILEPATH'],
          duration: 1200, # optional
          in_house: false, # optional but may be required if using match/sigh
        )
        upload_to_testflight(
          app_identifier: scheme["app_id"],
          skip_waiting_for_build_processing: false,
          changelog: commitslog
        )
      end

      # As Firebase added to project through SPM the location of upload-symbols
      # script is not handled by upload_symbols_to_crashlytics automatically,
      # so we need to find it and provide to action
      UPLOAD_SYMBOLS_PATH=`xcodebuild -project ../myapp.xcodeproj -showBuildSettings -scheme #{scheme["scheme_name"]} | grep -m 1 "BUILD_DIR" | grep -oEi "\/.*" | sed 's:Build/Products:SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/upload-symbols:' | tr -d '\n'`
      UI.success "UPLOAD_SYMBOLS_PATH = #{UPLOAD_SYMBOLS_PATH}"


      # dSYM updates to Firebase for each schema
      upload_symbols_to_crashlytics(
        binary_path: UPLOAD_SYMBOLS_PATH,
        dsym_path: "./myapp.app.dSYM.zip"
      )

      if is_upload_lane
        # Refresh the dSYM and upload to Firebase
        refresh_dsyms(
          appIdentifier: scheme["app_id"],
          gspPath: scheme["gsp_path"],
          binary_path: UPLOAD_SYMBOLS_PATH
        )

        slack(
          message: "#{config["project_name"]} (#{scheme["scheme_name"]}) TestFlight\n\nBuild ID ##{ENV["CI_BUILD_ID"]}\n\n\nChangelog from previous TestFlight version:\n\n#{commitslog}",
          slack_url: config["slack_webhook_url"]
        )
      else
        slack(
          message: "#{config["project_name"]} (#{scheme["scheme_name"]}) Build Success\n\nBuild ID ##{ENV["CI_BUILD_ID"]}\n\n\nChangelog from previous TestFlight version::\n\n#{commitslog}",
          slack_url: config["slack_webhook_url"]
        )
      end
    end

    error do |lane, exception|
      slack(
        success: false,
        message: "#{config["project_name"]} (#{environment["scheme_name"]}) Build Fail\n\nBuild ID ##{ENV["CI_BUILD_ID"]}\n\n#{exception}",
        slack_url: config["slack_webhook_url"]
      )
    end
  end

  desc "Run targeted build"
  private_lane :run_targetted_build_app do |options|
    is_upload_lane = options[:upload]
    app_id = options[:app_id]
    scheme = options[:scheme]
    gsp_path = options[:gsp_path]

    commitslog = changelog_from_git_commits(pretty: '- %s', merge_commit_filtering: "exclude_merges")
    puts commitslog.blue

    puts "++++++++++++++++++++++++++".blue
    puts "Pre TestFlight environment #{scheme} with app_id #{app_id}".blue
    puts "++++++++++++++++++++++++++".blue
    build_app(
      scheme: scheme,
      include_bitcode: true,
      export_xcargs: "-allowProvisioningUpdates",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "#{app_id}" => "match AppStore #{app_id}"
        }
      }
    )

    if is_upload_lane
      app_store_connect_api_key(
        key_id: ENV['APPSTORE_KEY_ID'],
        issuer_id: ENV['APPSTORE_ISSUER_ID'],
        key_filepath: ENV['APPSTORE_KEY_FILEPATH'],
        duration: 1200, # optional
        in_house: false, # optional but may be required if using match/sigh
      )

      upload_to_testflight(
        app_identifier: app_id,
        skip_waiting_for_build_processing: false,
        changelog: commitslog
      )
    end

    # As Firebase added to project through SPM the location of upload-symbols
    # script is not handled by upload_symbols_to_crashlytics automatically,
    # so we need to find it and provide to action
    UPLOAD_SYMBOLS_PATH=`xcodebuild -project ../myapp.xcodeproj -showBuildSettings -scheme #{scheme} | grep -m 1 "BUILD_DIR" | grep -oEi "\/.*" | sed 's:Build/Products:SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/upload-symbols:' | tr -d '\n'`
    UI.success "UPLOAD_SYMBOLS_PATH = #{UPLOAD_SYMBOLS_PATH}"


    # dSYM updates to Firebase for each schema
    upload_symbols_to_crashlytics(
      gsp_path: gsp_path,
      binary_path: UPLOAD_SYMBOLS_PATH,
      dsym_path: "./myapp.app.dSYM.zip"
    )

    if is_upload_lane
      puts "++++++++++++++++++++++++++".blue
      puts "Post TestFlight environment #{scheme} with app_id #{app_id}".blue
      puts "++++++++++++++++++++++++++".blue

      # Refresh the dSYM and upload to Firebase
      refresh_dsyms(
        appIdentifier: app_id,
        gsp_path: gsp_path,
        binary_path: UPLOAD_SYMBOLS_PATH
      )

      slack(
        message: "#{config["project_name"]} (#{scheme}) TestFlight\n\nBuild ID ##{ENV["CI_BUILD_ID"]}\n\n\nChangelog from previous TestFlight version:\n\n#{commitslog}",
        slack_url: config["slack_webhook_url"]
      )
    else
      slack(
        message: "#{config["project_name"]} (#{scheme}) Build Success\n\nBuild ID ##{ENV["CI_BUILD_ID"]}\n\n\nChangelog from previous TestFlight version::\n\n#{commitslog}",
        slack_url: config["slack_webhook_url"]
      )
    end



    error do |lane, exception|
      slack(
        success: false,
        message: "#{config["project_name"]} (#{scheme}) Build Fail\n\nBuild ID ##{ENV["CI_BUILD_ID"]}\n\n#{exception}",
        slack_url: config["slack_webhook_url"]
      )
    end
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("au.com.myco.myapp") # The bundle identifier of your app
apple_id(ENV['APPLE_ID']) # Your Apple email address
itc_team_id(ENV['APPLE_ITC_TEAM_ID']) # App Store Connect Team ID
team_id(ENV['APPLE_TEAM_ID']) # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.198.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-wait_xcrun | 1.0.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| bundler                         | 2.2.31       |
| tsort                           | 0.1.0        |
| uri                             | 0.10.1       |
| pathname                        | 0.1.0        |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.532.0      |
| aws-sigv4                       | 1.4.0        |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.122.1      |
| aws-sdk-kms                     | 1.51.0       |
| aws-sdk-s3                      | 1.106.0      |
| babosa                          | 1.0.4        |
| claide                          | 1.0.3        |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.88.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| multipart-post                  | 2.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.8.0        |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.5        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.3.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.0        |
| httpclient                      | 2.8.3        |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-androidpublisher_v3 | 0.13.0       |
| google-apis-playcustomapp_v1    | 0.6.0        |
| google-apis-iamcredentials_v1   | 0.8.0        |
| google-apis-storage_v1          | 0.9.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.34.1       |
| json                            | 2.6.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| fastlane-plugin-wait_xcrun      | 1.0.0        |
| xcode-install                   | 2.7.0        |
</details>

*generated on:* **2021-11-25**
</details>

**Comment by geeklingo** [comment]
Slightly different error in pipeline today

```
▸ Compiling GULNSData+zlib.m
❌  error: “GoogleAppMeasurement.framework” couldn’t be copied to “release-iphoneos” because an item with the same name already exists.
ERROR [2021-11-30 21:58:33.49]: Exit status: 65
```

**Comment by newforma-bclemans** [comment]
I potentially am suffering from the same issue. 

```
17:47:07  [17:47:06]: Exit status: 65
17:47:07  [17:47:06]: 
17:47:07  [17:47:06]: Maybe the error shown is caused by using the wrong version of Xcode
17:47:07  [17:47:06]: Found multiple versions of Xcode in '/Applications/'
17:47:07  [17:47:06]: Make sure you selected the right version for your project
17:47:07  [17:47:06]: This build process was executed using '/Applications/Xcode.app'
17:47:07  [17:47:06]: If you want to update your Xcode path, either
17:47:07 | Build environment |
17:47:07 +-------------+-------------------------+
17:47:07 | xcode_path | /Applications/Xcode.app |
17:47:07 | gym_version | 2.198.1 |
17:47:07 | sdk | iPhoneOS15.0.sdk |

17:47:07 ▸ Running script 'Crashlytics Setup'
17:47:07 ** ARCHIVE FAILED **`

Any insight on this is appreciated.

**Comment by geeklingo** [comment]
Anyone else having the same issue? I've been trying to get help from [Firebase](https://github.com/firebase/firebase-ios-sdk/issues/9031) as well with no luck. But this issue seems to only be affecting me using Fastlane CI pipelines via GitLab.

**Comment by a-25** [comment]
Hello, @geeklingo. 
Do not know for sure but could this thing be connected with the error?
`Found multiple versions of Xcode in '/Applications/'`
As for my experience, it could be a problem, because Xcode sometimes messes up xcode tools when using different versions.
Is it possible to remove other versions and try once more?

**Comment by geeklingo** [comment]
> 

Shouldn't be that, i use multiple versions of xcode via xcversions for 10 or so other projects on the same fastlane machine. This is the only one that is playing up.

**Comment by a-25** [comment]
@geeklingo: if you could or could not reproduce the bug on a machine with a single version, that could be a great help for guess which one fails: Fastlane or Firebase.
Otherwise it would be hard to understand what's wrong without the sources.
Do you have Firebase in your other projects that are built fine?

**Comment by geeklingo** [comment]
Yeah same SPMs in the other projects, I use Firebase in everything I am working on atm. The only difference is this one has a min iOS version set to 15 but otherwise all the projects are the same.

**Comment by Erin69** [comment]
I am facing this issue after upgrading to xcode 12.

**Comment by geeklingo** [comment]
I fixed this by creating a fresh project, still don't know what caused the issue as the previous one was also a fresh project.
