### ISSUE TITLE
AppStore Error upload file

### ISSUE THREAD

**Issue by omerb09** [fastlane/fastlane#19654]
**iTunes Transporter output above ^**
**An error occurred while processing the json request. (1268)
Return status of iTunes Transporter was 1: An error occurred while processing the json request. (1268)
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.**

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.6                                                           |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.23.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.6 (20G165)                                            |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 13.0                                                           |
| Swift Version               | 5.5                                                            |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
BOT_TOKEN = "**************************"
CHAT_ID = "**********"
$version_number =  ""

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do |options|
    match(type: "appstore")
    buildNumber = latest_testflight_build_number
    incrementBuildNumber(buildNumber)
    incrementVersionNumber(options[:version])
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight
    telegramSendMessage("HYD-Mobil #{$version_number} - #{(buildNumber+1).to_s}  versionu başarılı şekilde Appstore'a gönderildi. Tebrikler!!!")
  end

  lane :test do |options|
    match(type: "appstore")
    buildNumber = latest_testflight_build_number
    incrementVersionNumber(options[:version])
    telegramSendMessage("HYD-Mobil #{$version_number} - #{(buildNumber+1).to_s}  versionu başarılı şekilde Appstore'a gönderildi. Tebrikler!!!")
  end

  def incrementBuildNumber(val)
    if val != nil
      increment_build_number({build_number: val + 1})
    end
  end


  def incrementVersionNumber(val)
    if val != nil
      $version_number = increment_version_number(bump_type: val)
    end
  end

  def telegramSendMessage(text)
    telegram(
              token: BOT_TOKEN,
              chat_id: CHAT_ID,
              text: text,
            )
end

end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("org.********.ios") # The bundle identifier of your app
apple_id("apple@*********.com") # Your Apple email address

itc_team_id("********") # App Store Connect Team ID
team_id("*******") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.198.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                   | Version | Update-Status |
| ------------------------ | ------- | ------------- |
| fastlane-plugin-telegram | 0.1.3   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.85.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.8.0        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.1.0        |
| fastimage                       | 2.2.5        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 1.17.2       |
| simctl                          | 1.6.8        |
| jwt                             | 2.2.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.1        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.1        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| signet                          | 0.16.0       |
| googleauth                      | 0.17.1       |
| httpclient                      | 2.8.3        |
| google-apis-core                | 0.4.1        |
| google-apis-playcustomapp_v1    | 0.5.0        |
| google-apis-androidpublisher_v3 | 0.11.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.7.0        |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.34.1       |
| emoji_regex                     | 3.2.2        |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-sdk-kms                     | 1.48.0       |
| aws-sdk-s3                      | 1.103.0      |
| rexml                           | 3.2.5        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.0.3        |
| CFPropertyList                  | 3.0.4        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.21.0       |
| json                            | 2.5.1        |
| webrick                         | 1.7.0        |
| google-cloud-errors             | 1.2.0        |
| google-apis-storage_v1          | 0.8.0        |
| rake                            | 13.0.6       |
| aws-partitions                  | 1.506.0      |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.121.1      |
| forwardable                     | 1.2.0        |
| logger                          | 1.3.0        |
| date                            | 2.0.0        |
| stringio                        | 0.0.2        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.0.0        |
| mutex_m                         | 0.1.0        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| io-console                      | 0.4.7        |
| fileutils                       | 1.1.0        |
| etc                             | 1.0.1        |
| libxml-ruby                     | 3.2.1        |
| psych                           | 3.1.0        |
| fastlane-plugin-telegram        | 0.1.3        |
</details>

**Comment by barnewsapp** [comment]
Same issue here. 
It only happens to apps with names with non-standard characters like: æ, ø, å, á 
Fastlane version: 2.198.1

**Comment by omerb09** [comment]
> Same issue here. It only happens to apps with names with non-standard characters like: æ, ø, å, á Fastlane version: 2.198.1

It doesn't contain any of the characters you say in the name of my app. fastlane dataend 2.197.0 works fine.

**Comment by Phillip8322** [comment]
Thanks for the update. I'll be sure to keep an eye on this thread.

**Comment by omerb09** [comment]
I finally solved it.
The output of my application was "Hayrat Yardım.ipa" .
It was working with v2.197.0. I saved the application output from Turkish characters and uploaded it to the app store as "Hayrat Yardim.ipa" with version v2.199.0. And it worked.
