### ISSUE TITLE
"your account is in no teams" - Runtime error on fast lane match command

### ISSUE THREAD

**Issue by tclaus** [fastlane/fastlane#19656]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I want to update Certs and profiles. But $: fastlane match produces the "You Account Is In No Teams "runtime error. Even with giving team_id on the command line 

##### Command executed
$: fastlane match 

##### Complete output when running fastlane, including the stack trace and command used
thorstenclaus@Thorstens-MBP ios % fastlane match                            

[✔] 🚀 
[17:26:55]: Successfully loaded '/Users/thorstenclaus/Documents/develop/insporation/ios/Matchfile' 📄

+----------------+--------------------------------------------------------------------+
|                         Detected Values from './Matchfile'                          |
+----------------+--------------------------------------------------------------------+
| git_url        | git@github.com:jhass/insporation-certificates.git                  |
| storage_mode   | git                                                                |
| type           | development                                                        |
| app_identifier | ["eu.jhass.insporation", "eu.jhass.insporation.Insporation-Share"] |
+----------------+--------------------------------------------------------------------+

+--------------------------------+--------------------------------------------------------------------+
|                                      Summary for match 2.198.1                                      |
+--------------------------------+--------------------------------------------------------------------+
| type                           | development                                                        |
| readonly                       | false                                                              |
| generate_apple_certs           | true                                                               |
| skip_provisioning_profiles     | false                                                              |
| app_identifier                 | ["eu.jhass.insporation", "eu.jhass.insporation.Insporation-Share"] |
| username                       | XXXXXXXXX@XXXXX.XX                               |
| team_id                        | MYEC2JCSBB                                                         |
| storage_mode                   | git                                                                |
| git_url                        | git@github.com:jhass/insporation-certificates.git                  |
| git_branch                     | master                                                             |
| shallow_clone                  | false                                                              |
| clone_branch_directly          | false                                                              |
| keychain_name                  | login.keychain                                                     |
| force                          | false                                                              |
| force_for_new_devices          | false                                                              |
| include_all_certificates       | false                                                              |
| force_for_new_certificates     | false                                                              |
| skip_confirmation              | false                                                              |
| skip_docs                      | false                                                              |
| platform                       | ios                                                                |
| derive_catalyst_app_identifier | false                                                              |
| fail_on_name_taken             | false                                                              |
| skip_certificate_matching      | false                                                              |
| skip_set_partition_list        | false                                                              |
| verbose                        | false                                                              |
+--------------------------------+--------------------------------------------------------------------+

[17:26:55]: Cloning remote git repo...
[17:26:55]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[17:26:57]: Checking out branch master...
[17:26:57]: 🔓  Successfully decrypted certificates repo
[17:26:57]: Verifying that the certificate and profile are still valid on the Dev Portal...
No teams available on the Developer Portal
You must accept an invitation to a team for it to be available
To learn more about teams and how to use them visit https://developer.apple.com/library/ios/documentation/IDEs/Conceptual/AppDistributionGuide/ManagingYourTeam/ManagingYourTeam.html

Looking for related GitHub issues on fastlane/fastlane...

➡️  [spaceship] new team switching endpoint
    https://github.com/fastlane/fastlane/pull/19132 [closed] 1 💬
    22 Sep 2021

➡️  Fastlane produce fails with error, but appears to still create the app on App Store Connect
    https://github.com/fastlane/fastlane/issues/18794 [closed] 8 💬
    05 Sep 2021

➡️  `sigh repair` doesn't respect options like `--force`
    https://github.com/fastlane/fastlane/issues/18621 [closed] 2 💬
    28 Aug 2021

and 153 more at: https://github.com/fastlane/fastlane/search?q=Your%20account%20is%20in%20no%20teams&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	20: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/bin/ruby_executable_hooks:24:in `<main>'
	19: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/bin/ruby_executable_hooks:24:in `eval'
	18: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/bin/fastlane:23:in `<main>'
	17: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/bin/fastlane:23:in `load'
	16: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/gems/fastlane-2.198.1/bin/fastlane:23:in `<top (required)>'
	15: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/gems/fastlane-2.198.1/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	14: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/gems/fastlane-2.198.1/match/lib/match/commands_generator.rb:26:in `start'
	13: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/gems/fastlane-2.198.1/match/lib/match/commands_generator.rb:188:in `run'
	12: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	11: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/gems/fastlane-2.198.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	10: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	 9: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	 8: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	 7: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/gems/fastlane-2.198.1/match/lib/match/commands_generator.rb:54:in `block (2 levels) in run'
	 6: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/gems/fastlane-2.198.1/match/lib/match/runner.rb:73:in `run'
	 5: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/gems/fastlane-2.198.1/match/lib/match/runner.rb:73:in `new'
	 4: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/gems/fastlane-2.198.1/match/lib/match/spaceship_ensure.rb:34:in `initialize'
	 3: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/gems/fastlane-2.198.1/spaceship/lib/spaceship/connect_api/spaceship.rb:85:in `login'
	 2: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/gems/fastlane-2.198.1/spaceship/lib/spaceship/connect_api/client.rb:68:in `login'
	 1: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/gems/fastlane-2.198.1/spaceship/lib/spaceship/portal/portal_client.rb:73:in `select_team'
/Users/thorstenclaus/.rvm/gems/ruby-2.6.6/gems/fastlane-2.198.1/spaceship/lib/spaceship/portal/ui/select_team.rb:57:in `select_team': Your account is in no teams (RuntimeError)
	20: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/bin/ruby_executable_hooks:24:in `<main>'
	19: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/bin/ruby_executable_hooks:24:in `eval'
	18: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/bin/fastlane:23:in `<main>'
	17: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/bin/fastlane:23:in `load'
	16: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/gems/fastlane-2.198.1/bin/fastlane:23:in `<top (required)>'
	15: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/gems/fastlane-2.198.1/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	14: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/gems/fastlane-2.198.1/match/lib/match/commands_generator.rb:26:in `start'
	13: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/gems/fastlane-2.198.1/match/lib/match/commands_generator.rb:188:in `run'
	12: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	11: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/gems/fastlane-2.198.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	10: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	 9: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	 8: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	 7: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/gems/fastlane-2.198.1/match/lib/match/commands_generator.rb:54:in `block (2 levels) in run'
	 6: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/gems/fastlane-2.198.1/match/lib/match/runner.rb:73:in `run'
	 5: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/gems/fastlane-2.198.1/match/lib/match/runner.rb:73:in `new'
	 4: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/gems/fastlane-2.198.1/match/lib/match/spaceship_ensure.rb:34:in `initialize'
	 3: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/gems/fastlane-2.198.1/spaceship/lib/spaceship/connect_api/spaceship.rb:85:in `login'
	 2: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/gems/fastlane-2.198.1/spaceship/lib/spaceship/connect_api/client.rb:68:in `login'
	 1: from /Users/thorstenclaus/.rvm/gems/ruby-2.6.6/gems/fastlane-2.198.1/spaceship/lib/spaceship/portal/portal_client.rb:73:in `select_team'
/Users/thorstenclaus/.rvm/gems/ruby-2.6.6/gems/fastlane-2.198.1/spaceship/lib/spaceship/portal/ui/select_team.rb:57:in `select_team': [!] Your account is in no teams (RuntimeError)

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 12.0.1                                      |
| Ruby                        | 2.6.6                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.30.1 (Apple Git-130)          |
| Installation Source         | ~/.rvm/gems/ruby-2.6.6/bin/fastlane         |
| Host                        | macOS 12.0.1 (21A559)                       |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.6/lib                |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 13.1                                        |
| Swift Version               | 5.5.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    if is_ci
      increment_build_number(build_number: ENV["GITHUB_RUN_NUMBER"] || "1")
      create_keychain(
        name: "fastlane_ci",
        password: "ci_keychain",
        default_keychain: true,
        unlock: true,
        timeout: 3600,
        lock_when_sleeps: false
      )
      match(
        type: "appstore",
        keychain_name: 'fastlane_ci',
        keychain_password: 'ci_keychain',
        readonly: true
      )
      api_key = app_store_connect_api_key(
        key_id: "3AABBDDEEFF",
        issuer_id: "69AAAA-BBBB-CCCCC-DDDD",
        key_content: ENV["APPLE_API_KEY"],
        duration: 1200,
        in_house: false
      )
    else
      # please run bundle exec fastlane match appstore manually
      api_key = app_store_connect_api_key(
        key_id: "4BABBDDEEFF",
        issuer_id: "69AAAA-BBBB-CCCCC-DDDD",
        key_filepath: "AuthKey_3FMRTAH64H.p8",
        duration: 1200,
        in_house: false
      )
    end

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store"
    )

    upload_to_testflight(
      api_key: api_key,
      distribute_external: true,
      groups: "Extern",
      # TODO: CI: move automatic release step into job running prior this
      # and fetch changelog from the release notes
      changelog: "Latest nightly build changes",
      reject_build_waiting_for_review: true
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("eu.jhass.insporation") # The bundle identifier of your app
apple_id("insporation-appreview@mail.de") # Your Apple email address

itc_team_id("11223344") # App Store Connect Team ID
team_id("AABBCCDDF") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.198.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.4.0        |
| executable-hooks                | 1.6.0        |
| bundler-unload                  | 1.0.2        |
| rubygems-bundler                | 1.4.5        |
| bundler                         | 2.1.4        |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.534.0      |
| aws-sigv4                       | 1.4.0        |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.123.0      |
| aws-sdk-kms                     | 1.51.0       |
| aws-sdk-s3                      | 1.107.0      |
| babosa                          | 1.0.4        |
| claide                          | 1.0.3        |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.88.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| multipart-post                  | 2.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.8.0        |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.5        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.3.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.0        |
| httpclient                      | 2.8.3        |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-androidpublisher_v3 | 0.13.0       |
| google-apis-playcustomapp_v1    | 0.6.0        |
| google-apis-iamcredentials_v1   | 0.8.0        |
| google-apis-storage_v1          | 0.9.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.34.1       |
| json                            | 2.6.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
</details>

*generated on:* **2021-11-28**
</details>

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by lucgrabowski** [comment]
It looks like the username that you use wasn't invited to any team on Appstore Connect. Could you login to Appstore Connect with this user and check it? Remember that the user should have `Access to Certificates, Identifiers & Profiles.`
Please take a look at the hint from logs:
>No teams available on the Developer Portal
You must accept an invitation to a team for it to be available
To learn more about teams and how to use them visit https://developer.apple.com/library/ios/documentation/IDEs/Conceptual/AppDistributionGuide/ManagingYourTeam/ManagingYourTeam.html

**Comment by tclaus** [comment]
@lucgrabowski Thats the case - this mail is set as Role "Developer" / "App Manager" and I have accepted the invitation. Right after I got this message first, I removed the user and re-invited again. 

What I am missing is a clear statement what's going wrong (and why).

**Comment by tclaus** [comment]
Solved.
I watched this video https://www.youtube.com/watch?v=6Jz-Ywxki0U , and used the .env file.

In my case the used account was connected and invited to the AppStore, but something did go wrong. I changed the account to my main account and now this works. 

Better error handling would be appreciated. 
Issue can be closed.

**Comment by mfcollins3** [comment]
I'm running into the same issue. This is a problem with the Apple Developer Portal. I talked to Apple Developer Support and are aware of the error, but no ETA to getting it fixed.
