### ISSUE TITLE
Couldn't upload testers from CSV because of ArgumentError

### ISSUE THREAD

**Issue by takeshi-akutsu** [fastlane/fastlane#19671]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm trying to upload testers from CSV with fastlane pilot, but it couldn't be done because of wrong number of arguments error.

This might be related to the following issue;
https://github.com/fastlane/fastlane/issues/12403

##### Command executed

`bundle exec fastlane pilot import -c testers.csv`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [I'm working on *** $ bundle exec fastlane pilot import -c testers.csv

[✔] 🚀 
[20:12:44]: Login to App Store Connect (hogehoge@example.com)
[20:12:45]: Login successful

Looking for related GitHub issues on fastlane/fastlane...

➡️  DELIVER (2.150.0.rc3/4) always ask attribute whatsNew
    https://github.com/fastlane/fastlane/issues/16700 [open] 97 💬
    3 weeks ago

➡️  upload_to_play_store fails with error wrong number of arguments (given 1, expected 0)
    https://github.com/fastlane/fastlane/issues/18698 [closed] 9 💬
    18 Jul 2021

➡️  Passing api-key to sigh via CLI doesn't work
    https://github.com/fastlane/fastlane/issues/18222 [closed] 7 💬
    23 Sep 2021

and 28 more at: https://github.com/fastlane/fastlane/search?q=wrong%20number%20of%20arguments%20%28given%202%2C%20expected%201%29&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/Users/my_user_name/***/vendor/bundle/ruby/2.6.0/bin/fastlane)
Traceback (most recent call last):
	28: from /Users/my_user_name/.rbenv/versions/2.6.0/bin/bundle:23:in `<main>'
	27: from /Users/my_user_name/.rbenv/versions/2.6.0/bin/bundle:23:in `load'
	26: from /Users/my_user_name/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bundler-2.2.0/exe/bundle:37:in `<top (required)>'
	25: from /Users/my_user_name/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bundler-2.2.0/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	24: from /Users/my_user_name/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bundler-2.2.0/exe/bundle:49:in `block in <top (required)>'
	23: from /Users/my_user_name/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bundler-2.2.0/lib/bundler/cli.rb:24:in `start'
	22: from /Users/my_user_name/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bundler-2.2.0/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	21: from /Users/my_user_name/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bundler-2.2.0/lib/bundler/cli.rb:30:in `dispatch'
	20: from /Users/my_user_name/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bundler-2.2.0/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	19: from /Users/my_user_name/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bundler-2.2.0/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	18: from /Users/my_user_name/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bundler-2.2.0/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	17: from /Users/my_user_name/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bundler-2.2.0/lib/bundler/cli.rb:497:in `exec'
	16: from /Users/my_user_name/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bundler-2.2.0/lib/bundler/cli/exec.rb:28:in `run'
	15: from /Users/my_user_name/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bundler-2.2.0/lib/bundler/cli/exec.rb:63:in `kernel_load'
	14: from /Users/my_user_name/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bundler-2.2.0/lib/bundler/cli/exec.rb:63:in `load'
	13: from /Users/my_user_name/***/vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `<top (required)>'
	12: from /Users/my_user_name/***/vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `load'
	11: from /Users/my_user_name/***/vendor/bundle/ruby/2.6.0/gems/fastlane-2.198.1/bin/fastlane:23:in `<top (required)>'
	10: from /Users/my_user_name/***/vendor/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	 9: from /Users/my_user_name/***/vendor/bundle/ruby/2.6.0/gems/fastlane-2.198.1/pilot/lib/pilot/commands_generator.rb:19:in `start'
	 8: from /Users/my_user_name/***/vendor/bundle/ruby/2.6.0/gems/fastlane-2.198.1/pilot/lib/pilot/commands_generator.rb:167:in `run'
	 7: from /Users/my_user_name/***/vendor/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	 6: from /Users/my_user_name/***/vendor/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	 5: from /Users/my_user_name/***/vendor/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	 4: from /Users/my_user_name/***/vendor/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	 3: from /Users/my_user_name/***/vendor/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	 2: from /Users/my_user_name/***/vendor/bundle/ruby/2.6.0/gems/fastlane-2.198.1/pilot/lib/pilot/commands_generator.rb:161:in `block (2 levels) in run'
	 1: from /Users/my_user_name/***/vendor/bundle/ruby/2.6.0/gems/fastlane-2.198.1/pilot/lib/pilot/tester_importer.rb:20:in `import_testers'
/Users/my_user_name/.rbenv/versions/2.6.0/lib/ruby/2.6.0/csv.rb:505:in `foreach': wrong number of arguments (given 2, expected 1) (ArgumentError)
	28: from /Users/my_user_name/.rbenv/versions/2.6.0/bin/bundle:23:in `<main>'
	27: from /Users/my_user_name/.rbenv/versions/2.6.0/bin/bundle:23:in `load'
	26: from /Users/my_user_name/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bundler-2.2.0/exe/bundle:37:in `<top (required)>'
	25: from /Users/my_user_name/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bundler-2.2.0/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	24: from /Users/my_user_name/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bundler-2.2.0/exe/bundle:49:in `block in <top (required)>'
	23: from /Users/my_user_name/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bundler-2.2.0/lib/bundler/cli.rb:24:in `start'
	22: from /Users/my_user_name/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bundler-2.2.0/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	21: from /Users/my_user_name/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bundler-2.2.0/lib/bundler/cli.rb:30:in `dispatch'
	20: from /Users/my_user_name/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bundler-2.2.0/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	19: from /Users/my_user_name/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bundler-2.2.0/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	18: from /Users/my_user_name/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bundler-2.2.0/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	17: from /Users/my_user_name/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bundler-2.2.0/lib/bundler/cli.rb:497:in `exec'
	16: from /Users/my_user_name/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bundler-2.2.0/lib/bundler/cli/exec.rb:28:in `run'
	15: from /Users/my_user_name/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bundler-2.2.0/lib/bundler/cli/exec.rb:63:in `kernel_load'
	14: from /Users/my_user_name/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bundler-2.2.0/lib/bundler/cli/exec.rb:63:in `load'
	13: from /Users/my_user_name/***/vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `<top (required)>'
	12: from /Users/my_user_name/***/vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `load'
	11: from /Users/my_user_name/***/vendor/bundle/ruby/2.6.0/gems/fastlane-2.198.1/bin/fastlane:23:in `<top (required)>'
	10: from /Users/my_user_name/***/vendor/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	 9: from /Users/my_user_name/***/vendor/bundle/ruby/2.6.0/gems/fastlane-2.198.1/pilot/lib/pilot/commands_generator.rb:19:in `start'
	 8: from /Users/my_user_name/***/vendor/bundle/ruby/2.6.0/gems/fastlane-2.198.1/pilot/lib/pilot/commands_generator.rb:167:in `run'
	 7: from /Users/my_user_name/***/vendor/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	 6: from /Users/my_user_name/***/vendor/bundle/ruby/2.6.0/gems/fastlane-2.198.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	 5: from /Users/my_user_name/***/vendor/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	 4: from /Users/my_user_name/***/vendor/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	 3: from /Users/my_user_name/***/vendor/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	 2: from /Users/my_user_name/***/vendor/bundle/ruby/2.6.0/gems/fastlane-2.198.1/pilot/lib/pilot/commands_generator.rb:161:in `block (2 levels) in run'
	 1: from /Users/my_user_name/***/vendor/bundle/ruby/2.6.0/gems/fastlane-2.198.1/pilot/lib/pilot/tester_importer.rb:20:in `import_testers'
/Users/my_user_name/.rbenv/versions/2.6.0/lib/ruby/2.6.0/csv.rb:505:in `foreach': [!] wrong number of arguments (given 2, expected 1) (ArgumentError)
] </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                    |
| --------------------------- | -------------------------------------------------------- |
| OS                          | 11.3                                                     |
| Ruby                        | 2.6.0                                                    |
| Bundler?                    | true                                                     |
| Git                         | git version 2.26.1                                       |
| Installation Source         | ~/***/vendor/bundle/ruby/2.6.0/bin/fastlane |
| Host                        | macOS 11.3 (20E232)                                      |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.0/lib                              |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                              |
| Is contained                | false                                                    |
| Is homebrew                 | false                                                    |
| Is installed via Fabric.app | false                                                    |
| Xcode Path                  | ~/Downloads/Xcode.app/Contents/Developer/                |
| Xcode Version               | 13.0                                                     |
| Swift Version               | 5.5                                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | ja_JP.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.198.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                       | Version | Update-Status |
| ---------------------------- | ------- | ------------- |
| fastlane-plugin-google_drive | 0.7.0   | ✅ Up-To-Date  |
| fastlane-plugin-bitrise      | 0.2.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| bundler                         | 2.2.0        |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| concurrent-ruby                 | 1.1.9        |
| i18n                            | 1.8.11       |
| minitest                        | 5.14.4       |
| tzinfo                          | 2.0.4        |
| zeitwerk                        | 2.5.1        |
| activesupport                   | 6.1.4.1      |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| httpclient                      | 2.8.3        |
| json                            | 2.6.1        |
| algoliasearch                   | 1.27.5       |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.539.0      |
| aws-sigv4                       | 1.4.0        |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.124.0      |
| aws-sdk-kms                     | 1.52.0       |
| aws-sdk-s3                      | 1.109.0      |
| babosa                          | 1.0.4        |
| claide                          | 1.0.3        |
| fuzzy_match                     | 2.0.4        |
| nap                             | 1.1.0        |
| netrc                           | 0.11.0       |
| ffi                             | 1.15.4       |
| ethon                           | 0.15.0       |
| typhoeus                        | 1.4.0        |
| cocoapods-core                  | 1.11.2       |
| cocoapods-deintegrate           | 1.0.5        |
| cocoapods-downloader            | 1.5.1        |
| cocoapods-plugins               | 1.0.0        |
| cocoapods-search                | 1.0.1        |
| cocoapods-trunk                 | 1.6.0        |
| cocoapods-try                   | 1.2.0        |
| colored2                        | 3.1.2        |
| escape                          | 0.0.4        |
| fourflusher                     | 2.3.1        |
| gh_inspector                    | 1.1.3        |
| molinillo                       | 0.8.0        |
| ruby-macho                      | 2.5.1        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| cocoapods                       | 1.11.2       |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.88.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| multipart-post                  | 2.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.8.0        |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.5        |
| jwt                             | 2.3.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.0       |
| googleauth                      | 0.17.1       |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-androidpublisher_v3 | 0.13.0       |
| google-apis-playcustomapp_v1    | 0.6.0        |
| google-apis-iamcredentials_v1   | 0.8.0        |
| google-apis-storage_v1          | 0.9.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.34.1       |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| fastlane-plugin-bitrise         | 0.2.0        |
| google-apis-drive_v3            | 0.16.0       |
| google-apis-sheets_v4           | 0.10.0       |
| racc                            | 1.6.0        |
| nokogiri                        | 1.12.5       |
| google_drive                    | 3.0.7        |
| fastlane-plugin-google_drive    | 0.7.0        |
</details>

*generated on:* **2021-12-03**
</details>

**Comment by lucgrabowski** [comment]
I recommend using `pilot export` in the first place to check the syntax used in csv file. It should be comma separated file with:
`first_name,last_name,email,testing_groups`
When you export to csv, you'll see a header row, I'm not sure if import will work with this header row.

**Comment by takeshi-akutsu** [comment]
I tried that step first and checked the exported csv format, but the result was same. I got the argument error again.

```
/vendor/bundle/ruby/2.6.0/gems/fastlane-2.198.1/pilot/lib/pilot/tester_importer.rb:20:in `import_testers'
/.rbenv/versions/2.6.0/lib/ruby/2.6.0/csv.rb:505:in `foreach': [!] wrong number of arguments (given 2, expected 1) (ArgumentError)
```

**Comment by takeshi-akutsu** [comment]
As described in this comment https://github.com/fastlane/fastlane/issues/12403#issuecomment-385062860, 
this error is caused by the change in Ruby 2.5, and fastlane pilot might not have supported that Ruby version yet.

**Ruby 2.4** 
`foreach(path, options = Hash.new, &block)`
https://ruby-doc.org/stdlib-2.4.0/libdoc/csv/rdoc/CSV.html#method-c-foreach

**Ruby 2.5** 
`foreach(path, **options, &block)`
https://ruby-doc.org/stdlib-2.5.0/libdoc/csv/rdoc/CSV.html#method-c-foreach
