### ISSUE TITLE
Match doesn't pull info from input team_name and team_id

### ISSUE THREAD

**Issue by crewshin** [fastlane/fastlane#19689]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
We white label a *lot* of apps and most are under their own team_name and team_id

##### Problem areas in fastfile
```ruby
def update_signing(options)

	register_devices(
		devices_file: "devices.txt",
		api_key: api_key(options)
	)

	match(
		type: options[:match_type] || ENV["MATCH_TYPE"] || "development",
		# username: options[:match_username] || ENV["MATCH_USERNAME"] || "...",
		# team_id: options[:team_id] || ENV["TEAM_ID"] || "...",
		# team_name: options[:team_name] || ENV["TEAM_NAME"] || "...",
		api_key: api_key(options),
		git_branch: "main",
	)

	# Sets profile names correctly in xcode.
	mapping = Actions.lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING]

	xcodeproj_path = File.expand_path("../OurApp.xcodeproj", Dir.pwd)
	update_code_signing_settings(
		path: xcodeproj_path,
		profile_name: mapping[options[:match_app_identifier] || ENV['MATCH_APP_IDENTIFIER']],
		bundle_identifier: options[:match_app_identifier] || ENV['MATCH_APP_IDENTIFIER'] || $bundle_identifier,
	)
end

def api_key(options)

	if !ENV["API_KEY_PATH"].to_s.strip.empty?
		key_filepath = ENV["API_KEY_PATH"]
	else
		if ENV["IS_FACTS_APP"] == "true"
			key_filepath = options[:api_key_path] || ENV["API_KEY_FACTS_PATH"]
		else 
			key_filepath = options[:api_key_path] || ENV["API_KEY_A3_PATH"]
		end
	end

	app_store_connect_api_key(
		key_id: options[:api_key_id] || ENV["API_KEY_ID"] || "...",
		issuer_id: options[:api_issuer_id] || ENV["API_ISSUER_ID"] || "...",
		key_filepath: key_filepath,
		is_key_content_base64: false,
		duration: 1200,
		in_house: false,
	)
end
```

```
+--------------------------------+--------------------------------------+
|                       Summary for match 2.193.1                       |
+--------------------------------+--------------------------------------+
| type                           | appstore                             |
| username                       | Correct email                        |
| team_id                        | Correct id                           |
| team_name                      | Correct team name                    |
| api_key                        | ********                             |
| git_branch                     | main                                 |
| readonly                       | false                                |
| generate_apple_certs           | true                                 |
| skip_provisioning_profiles     | false                                |
| app_identifier                 | ["Correct bundle id"]                |
| storage_mode                   | git                                  |
| git_url                        | Correct repo url                     |
| shallow_clone                  | false                                |
| clone_branch_directly          | false                                |
| keychain_name                  | login.keychain                       |
| force                          | false                                |
| force_for_new_devices          | false                                |
| skip_confirmation              | false                                |
| skip_docs                      | false                                |
| platform                       | ios                                  |
| derive_catalyst_app_identifier | false                                |
| fail_on_name_taken             | false                                |
| skip_certificate_matching      | false                                |
| skip_set_partition_list        | false                                |
| verbose                        | false                                |
+--------------------------------+--------------------------------------+
```

What I get is:
<output>
<pre>
- com.somebundleId1
- com.somebundleId2
- com.somebundleId3
- com.somebundleId4
- com.somebundleId5
- com.somebundleId6 // These are all correct bundle id's from our main account. But shouldln't exist in the one I'm trying to fetch from in this pipeline.
- com.somebundleId7
- com.somebundleId8
- com.somebundleId9
[11:39:44]: Make sure to run `fastlane match` with the same user and team every time.
+------------------+-------------------------+
|                Lane Context                |
+------------------+-------------------------+
| DEFAULT_PLATFORM | ios                     |
| PLATFORM_NAME    | ios                     |
| LANE_NAME        | ios publish_to_appstore |
+------------------+-------------------------+
[11:39:44]: Couldn't find bundle identifier 'com.correct.bundle.id' for the user 'foo@us.com'
+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | opt_out_usage                                                 | 0           |
| 2    | default_platform                                              | 0           |
| 3    | git rev-parse --abbrev-ref HEAD | tr -d '                     | 0           |
|      | '                                                             |             |
| 4    | printenv | sort                                               | 0           |
| 5    | Switch to ios pod_install lane                                | 0           |
| 6    | bundle exec pod install                                       | 9           |
| 7    | set_info_plist_value                                          | 0           |
| 8    | Switch to ios build_archive lane                              | 0           |
| 9    | Switch to ios pod_install lane                                | 0           |
| 10   | bundle exec pod install                                       | 7           |
| 11   | Switch to ios get_config lane                                 | 0           |
| 12   | curl --http1.1 -o 33644-config.zip 'https://ourcompany.net/api/sy | 5           |
| 13   | unzip -o 33644-config.zip 'amp-ios/*' -d '../'                | 0           |
| 14   | get_xcconfig_value                                            | 0           |
| 15   | get_xcconfig_value                                            | 0           |
| 16   | Switch to ios update_signing lane                             | 0           |
| 17   | app_store_connect_api_key                                     | 0           |
| 18   | register_devices                                              | 0           |
| 19   | app_store_connect_api_key                                     | 0           |
| 💥   | match                                                         | 6           |
+------+---------------------------------------------------------------+-------------+
[11:39:44]: fastlane finished with errors
[!] Couldn't find bundle identifier 'com.correct.bundle.id' for the user 'foo@us.com'
Cleaning up file based variables
00:01
ERROR: Job failed: exit status 1
</pre>
</output>

What I expect is match to see and use the existing identifier under the passed in team_name and team_id.

**Comment by Marcella3** [comment]
If no team_id is provided, then the queue SID is used as the unique ID. The team_id attribute is required to display team_name

**Comment by crewshin** [comment]
I'm not exactly sure what that means. I provide the `team_id` and `team_name` every time.

**Comment by crewshin** [comment]
This is a blocker for us atm. If anyone has any input that would be great.

**Comment by crewshin** [comment]
Small update on this. it appears that if you use an api key, then the team_id and team_name are no longer needed? So now with swapping out the api key for each client, however I still get this error which is displaying the wrong email:

```
[13:28:57]: Certificate '...' (stored in your storage) is not available on the Developer Portal
[13:28:57]: for the user ... # this is the wrong email which is our default for internal apps.
[13:28:57]: Make sure to use the same user and team every time you run 'match' for this
[13:28:57]: Git repository. This might be caused by revoking the certificate on the Dev Portal
[13:28:57]: If missing certificate is a Developer ID Installer, you may need to auth with Apple ID instead of App Store API Key
```
