### ISSUE TITLE
App Store Connect API - Authentication credentials are missing or invalid.

### ISSUE THREAD

**Issue by dgilbert-foreflight** [fastlane/fastlane#19684]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Noticing odd behavior when working with `app_store_connect_api_key` action.

`app_store_connect_api` only appears to be work for other actions when explicitly specifying parameters as such:
```ruby
app_store_connect_api_key(
      key_id: "<key_id>",
      issuer_id: "<issuer_id>",
      key_content: "<key_content>",
      is_key_content_base_64: <true|false>
)
```

If say, you try to utilize dotenv with `app_store_connect_api` by setting up the following variables in your `.env` file:
```
APP_STORE_CONNECT_API_KEY_KEY_ID=<key_id>
APP_STORE_CONNECT_API_KEY_ISSUER_ID=<issuer_id>
APP_STORE_CONNECT_API_KEY_KEY=<key_content>
APP_STORE_CONNECT_API_KEY_IS_KEY_CONTENT_BASE64=<true|false>
```
Just calling `app_store_connect_api` oddly enough appears to properly set `SharedValues::APP_STORE_CONNECT_API_KEY` with the correct information; however, you are met by the following error when attempting to use any actions which either look for `SharedValues::APP_STORE_CONNECT_API_KEY` or `Spaceship::ConnectAPI.token`
> Authentication credentials are missing or invalid. - Provide a properly configured and signed bearer token, and make sure that it has not expired.

What's even more odd, even if you were to try and explicitly specify parameters for `app_store_connect_api` through passing environment variables to the parameters, it will also behave as mentioned above.
```ruby
app_store_connect_api_key(
      key_id: ENV['KEY_ID'],
      issuer_id: ENV['ISSUER_ID'],
      key_content: ENV['KEY_CONTENT'],
      is_key_content_base_64: <true|false>
)
```

FWIW, it doesn't appear to matter if the key content is base64 encoded or not.
Also, didn't see any change in behavior when utilizing `key_filepath` vs `key_content` for `app_store_connect_api_key`

##### Command executed

```ruby
fastlane playground
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [✔] 🚀 
[14:11:13]: fastlane detected a Gemfile in the current directory
[14:11:13]: However, it seems like you didn't use `bundle exec`
[14:11:13]: To launch fastlane faster, please use
[14:11:13]: 
[14:11:13]: $ bundle exec fastlane playground
[14:11:13]: 
[14:11:13]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[14:11:14]: ------------------------------
[14:11:14]: --- Step: default_platform ---
[14:11:14]: ------------------------------
[14:11:14]: Driving the lane 'ios playground' 🚀
[14:11:14]: ---------------------------------------
[14:11:14]: --- Step: app_store_connect_api_key ---
[14:11:14]: ---------------------------------------
[14:11:14]: -------------------
[14:11:14]: --- Step: match ---
[14:11:14]: -------------------
[14:11:14]: Successfully loaded '/Users/dgilbert/Developer/ios/fastlane/Matchfile' 📄

+----------------+-------------------------------------------------------------------------------------------------------------------------------+
|                                                  Detected Values from './fastlane/Matchfile'                                                   |
+----------------+-------------------------------------------------------------------------------------------------------------------------------+
| git_url        | https://github.com/dgilbert/ios-certificates.git                                                                            |
| storage_mode   | git                                                                                                                           |
| type           | development                                                                                                                   |
| app_identifier | ["com.example.fakeapp"] |
+----------------+-------------------------------------------------------------------------------------------------------------------------------+

+--------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
|                                                                   Summary for match 2.198.1                                                                    |
+--------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| api_key                        | ********                                                                                                                      |
| type                           | development                                                                                                                   |
| readonly                       | false                                                                                                                         |
| generate_apple_certs           | true                                                                                                                          |
| skip_provisioning_profiles     | false                                                                                                                         |
| app_identifier                 | ["com.example.fakeapp"] |
| team_id                        | WE376FT8S9                                                                                                                    |
| team_name                      | FakeTeam                                                                                                                |
| storage_mode                   | git                                                                                                                           |
| git_url                        | https://github.com/dgilbert/ios-certificates.git                                                                            |
| git_branch                     | master                                                                                                                        |
| shallow_clone                  | false                                                                                                                         |
| clone_branch_directly          | false                                                                                                                         |
| keychain_name                  | login.keychain                                                                                                                |
| force                          | false                                                                                                                         |
| force_for_new_devices          | false                                                                                                                         |
| include_all_certificates       | false                                                                                                                         |
| force_for_new_certificates     | false                                                                                                                         |
| skip_confirmation              | false                                                                                                                         |
| skip_docs                      | false                                                                                                                         |
| platform                       | ios                                                                                                                           |
| derive_catalyst_app_identifier | false                                                                                                                         |
| fail_on_name_taken             | false                                                                                                                         |
| skip_certificate_matching      | false                                                                                                                         |
| skip_set_partition_list        | false                                                                                                                         |
| verbose                        | false                                                                                                                         |
+--------------------------------+-------------------------------------------------------------------------------------------------------------------------------+

[14:11:14]: Cloning remote git repo...
[14:11:14]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[14:11:16]: Checking out branch master...
[14:11:16]: 🔓  Successfully decrypted certificates repo
[14:11:16]: Verifying that the certificate and profile are still valid on the Dev Portal...
[14:11:16]: Creating authorization token for App Store Connect API
+------------------+----------------+
|           Lane Context            |
+------------------+----------------+
| DEFAULT_PLATFORM | ios            |
| PLATFORM_NAME    | ios            |
| LANE_NAME        | ios playground |
+------------------+----------------+
[14:11:16]: Authentication credentials are missing or invalid. - Provide a properly configured and signed bearer token, and make sure that it has not expired. Learn more about Generating Tokens for API Requests https://developer.apple.com/go/?id=api-generating-tokens

+------+---------------------------+-------------+
|                fastlane summary                |
+------+---------------------------+-------------+
| Step | Action                    | Time (in s) |
+------+---------------------------+-------------+
| 1    | default_platform          | 0           |
| 2    | app_store_connect_api_key | 0           |
| 💥   | match                     | 2           |
+------+---------------------------+-------------+

[14:11:16]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

[!] The request could not be completed because:
        Authentication credentials are missing or invalid. - Provide a properly configured and signed bearer token, and make sure that it has not expired. Learn more about Generating Tokens for API Requests https://developer.apple.com/go/?id=api-generating-tokens </pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 12.0.1                                                     |
| Ruby                        | 3.0.2                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.30.1 (Apple Git-130)                         |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.198.1/libexec/bin/fastlane |
| Host                        | macOS 12.0.1 (21A559)                                      |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.0.2_1/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021                                |
| Is contained                | false                                                      |
| Is homebrew                 | true                                                       |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
| Xcode Version               | 13.1                                                       |
| Swift Version               | 5.5.1                                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform(:ios)
# Specify your APP_STORE_CONNECT_API environment variables in `.env.secret`
# APP_STORE_CONNECT_API_KEY_KEY_ID=
# APP_STORE_CONNECT_API_KEY_ISSUER_ID=
# APP_STORE_CONNECT_API_KEY_KEY=
# APP_STORE_CONNECT_API_KEY_IS_KEY_CONTENT_BASE64=true
## OR
# KEY_ID=
# ISSUER_ID=
# KEY=
Dotenv.overload ".env.secret"

platform :ios do

  before_all do |lane, options|
    ## Works for other actions / lanes
    # app_store_connect_api_key(
    #   key_id: "<explicit_key_id>",
    #   issuer_id: "<explicit_issuer_id>",
    #   key_content: "<explicit_key_content>",
    #   is_key_content_base64: <true|false>
    # )
    
    ## Doesn't Work for other actions / lanes
    # app_store_connect_api_key(
    #  key_id: ENV['KEY_ID'],
    #  issuer_id: ENV['ISSUER_ID'],
    #  key_content: ENV['KEY'],
    #  is_key_content_base64: true
    #)
    
    ## Doesn't Work for other actions / lanes
    app_store_connect_api_key
  end

  desc "Playground Lane"
  lane :playground do |options|
    puts lane_context[SharedValues::APP_STORE_CONNECT_API_KEY] ## Prints correct info from `app_store_connect_api_key`
    match(
      # api_key: lane_context[SharedValues::APP_STORE_CONNECT_API_KEY] ## Doesn't work
    )
    # Another command which fails with authentication error.
   # register_devices(devices: <devices hash>)
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.example.fakeapp"
team_name "FakeTeam"
team_id "WE376FT8S9"

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.198.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.88.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.8.0        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.5        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.22       |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-playcustomapp_v1    | 0.6.0        |
| google-apis-androidpublisher_v3 | 0.13.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.8.0        |
| google-apis-storage_v1          | 0.9.0        |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.34.1       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.4.0        |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-sdk-core                    | 3.122.1      |
| aws-sdk-kms                     | 1.51.0       |
| aws-sdk-s3                      | 1.106.0      |
| tsort                           | 0.1.0        |
| uri                             | 0.10.1       |
| set                             | 1.0.1        |
| json                            | 2.6.1        |
| aws-partitions                  | 1.533.0      |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.0        |
| date                            | 3.1.0        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.0        |
| openssl                         | 2.2.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.2        |
| io-wait                         | 0.1.0        |
| zlib                            | 1.1.0        |
| resolv                          | 0.2.0        |
| securerandom                    | 0.1.0        |
| digest                          | 3.0.0        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.0        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.0        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.7        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| net-http                        | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| prettyprint                     | 0.1.0        |
| pp                              | 0.1.0        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.0        |
</details>

*generated on:* **2021-12-08**
</details> </pre>
</details>

**Comment by noahsbwilliams** [comment]
Had the same issue, can't figure why this doesn't work...

**Comment by dgilbert-foreflight** [comment]
This issue is still happening in `2.204.3`.

As stated, I can fix the issue by explicitly specifying parameter information in the lane action as opposed to obfuscating the key details via environment variables like so.
```ruby
app_store_connect_api_key(
      key_id: "<key_id>",
      issuer_id: "<issuer_id>",
      key_content: "<key_content>",
      is_key_content_base64: <true|false>
)
```

I'm not sure why this does the trick but it works in my testing.
