### ISSUE TITLE
[gym] skip_archive option leads to `No output path received from gym`

### ISSUE THREAD

**Issue by pierpo** [fastlane/fastlane#19694]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I am using Fastlane Gym to build my app for my Detox tests and for my ad-hoc distribution builds. I use fastlane for both so that I re-use the data in `derived_data` directory (allowing me to easily cache it in my CI).

The problem is that once I have the flag `skip_archive: true`, I _systematically_ get the error `No output path received from gym`.

##### Command executed

```ruby
platform :ios do
  lane :build do |options|
    gym(
      configuration: "ReleaseStaging",
      output_directory: "ios/build",
      output_name: "MyApp.ipa",
      workspace: "ios/MyApp.xcworkspace",
      export_method: "ad-hoc",
      derived_data_path: "ios/derived_data",
      skip_archive: ENV['DETOX'] ? true : false,
    )
  end
end
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
<pre>
bundle exec fastlane ios build 

[...]

[17:54:45]: ▸ Running script '[CP] Copy Pods Resources'
[17:54:45]: ▸ Running script '[CP] Embed Pods Frameworks'
[17:54:46]: ▸ Touching MyApp.xctest
[17:54:46]: ▸ Signing derived_data/Build/Products/ReleaseStaging-iphoneos/MyApp.app/PlugIns/MyApp.xctest
[17:54:46]: ▸ Signing derived_data/Build/Products/ReleaseStaging-iphoneos/MyApp.app
[17:54:47]: ▸ Build Succeeded
[17:54:47]: No output path received from gym

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Switch to ios load_env_file lane    | 0           |
| 2    | Switch to ios check_env_exists lane | 0           |
| 3    | gym                                 | 64          |
+------+-------------------------------------+-------------+

[17:54:47]: fastlane.tools finished successfully 🎉

</pre>
</details>

### Environment

<details>
  <pre>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 12.0                                        |
| Ruby                        | 3.0.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.30.1 (Apple Git-130)          |
| Installation Source         | ~/.rbenv/versions/3.0.3/bin/fastlane        |
| Host                        | macOS 12.0 (21A344)                         |
| Ruby Lib Dir                | ~/.rbenv/versions/3.0.3/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 13.1                                        |
| Swift Version               | 5.5.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | fr_FR.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_require 'dotenv'

import('../../common/fastlane/FastfileConfig')
import('../../common/fastlane/FastfileCheck')
import('../../common/fastlane/FastfileEnvironment')
import('../../common/fastlane/FastfileIOSSigning')
import('../../common/fastlane/FastfileCommon')

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.199.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| bundler                         | 2.2.32       |
| pathname                        | 0.1.0        |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| concurrent-ruby                 | 1.1.9        |
| i18n                            | 1.8.10       |
| minitest                        | 5.14.4       |
| tzinfo                          | 2.0.4        |
| zeitwerk                        | 2.5.1        |
| activesupport                   | 6.1.4.1      |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| httpclient                      | 2.8.3        |
| json                            | 2.6.1        |
| algoliasearch                   | 1.27.5       |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.540.0      |
| aws-sigv4                       | 1.4.0        |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.124.0      |
| aws-sdk-kms                     | 1.52.0       |
| aws-sdk-s3                      | 1.109.0      |
| babosa                          | 1.0.4        |
| claide                          | 1.0.3        |
| fuzzy_match                     | 2.0.4        |
| nap                             | 1.1.0        |
| netrc                           | 0.11.0       |
| ffi                             | 1.15.4       |
| ethon                           | 0.15.0       |
| typhoeus                        | 1.4.0        |
| cocoapods-core                  | 1.11.2       |
| cocoapods-deintegrate           | 1.0.5        |
| cocoapods-downloader            | 1.5.1        |
| cocoapods-plugins               | 1.0.0        |
| cocoapods-search                | 1.0.1        |
| cocoapods-trunk                 | 1.6.0        |
| cocoapods-try                   | 1.2.0        |
| colored2                        | 3.1.2        |
| escape                          | 0.0.4        |
| fourflusher                     | 2.3.1        |
| gh_inspector                    | 1.1.3        |
| molinillo                       | 0.8.0        |
| ruby-macho                      | 2.5.1        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| cocoapods                       | 1.11.2       |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.89.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| multipart-post                  | 2.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.8.0        |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.5        |
| jwt                             | 2.3.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.0        |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-androidpublisher_v3 | 0.14.0       |
| google-apis-playcustomapp_v1    | 0.6.0        |
| google-apis-iamcredentials_v1   | 0.9.0        |
| google-apis-storage_v1          | 0.10.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.35.0       |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
</details>

*generated on:* **2021-12-13**
</details>
</pre>
</details>

**Comment by pierpo** [comment]
I had a look at the code, and it seems to be because of this:

- Here, we check if a path is not null https://github.com/fastlane/fastlane/blob/605d2618da27cd63a088a0bdcbec78d7e0e5def1/fastlane/lib/fastlane/actions/build_app.rb#L69
- But in the runner that returns this path, we explicitely say "if skip_archive is enabled, then return nil" https://github.com/fastlane/fastlane/blob/605d2618da27cd63a088a0bdcbec78d7e0e5def1/gym/lib/gym/runner.rb#L22

But after second thought... I just realised that this **was actually expected ✅**!

My problem was that Detox was not finding my `.app`. But Gym was actually generating it... I was simply not giving the proper path to Detox. Oops.

Should we document this as expected?

If not, we may close the issue!
In any case, I hope someone else will find this helpful.

**Comment by GLinnik21** [comment]
I have kind a same issue with `SharedValues::IPA_OUTPUT_PATH`. It seems `gym` stopped exporting these envars in one of the latest fastlane versions

**Comment by Ramos169** [comment]
It seems that I have similar query, did you get the solution for this?

**Comment by pierpo** [comment]
> It seems that I have similar query, did you get the solution for this?

As I said, in my case it was not really a problem. Gym is just warning you that nothing useful was generated, which is true if you skipped the archiving of your `.app` to a `.ipa`.

In my case, I needed the `.app` to install it on a simulator, but this is not common at all. Fastlane's usage is meant for distribution, and a `.app` on its own is of no use for distribution.

**Comment by GLinnik21** [comment]
> It seems that I have similar query, did you get the solution for this?

I just rolled back to the old fastlane version (`2.121.1`)
