### ISSUE TITLE
Error does NOT have any valid iTMS, Can not upload .ipa to TestFlight

### ISSUE THREAD

**Issue by leewonghao** [fastlane/fastlane#19734]
### Discussed in https://github.com/fastlane/fastlane/discussions/19733

<div type='discussions-op-text'>

<sup>Originally posted by **leewonghao** December 21, 2021</sup>
### Issue Description
I have a issue, I can't upload .ipa to TestFlight with version 2.199.0, but it announced upload to App store connect successfully.

##### Command executed
15:38:59 [15:38:59]: Creating authorization token for App Store Connect API
15:39:05 [15:39:05]: Ready to upload new build to TestFlight (App: 1594783317)...
15:39:07 [15:39:07]: Going to upload updated app to App Store Connect
15:39:07 [15:39:07]: This might take a few minutes. Please don't interrupt the script.
15:39:21 [15:39:21]: iTunes Transporter successfully finished its job
15:39:22 [15:39:22]: [iTMSTransporter] [2021-12-21 15:39:21 ICT] <main>  INFO: Upload mode selected.
15:39:22 
15:39:22 [15:39:22]: [iTMSTransporter] [2021-12-21 15:39:21 ICT] <main> DEBUG: Ignoring file: /var/folders/sw/kqr0spsj2g75yr737kl1v9t80000gp/T/Prufin.ipa/Prufin.ipa because it is NOT an iTMS package.
15:39:22 
15:39:22 [15:39:22]: [iTMSTransporter] [2021-12-21 15:39:21 ICT] <main> DEBUG: Ignoring file: /var/folders/sw/kqr0spsj2g75yr737kl1v9t80000gp/T/Prufin.ipa/Payload because it is NOT an iTMS package.
15:39:22 
15:39:22 [15:39:22]: [iTMSTransporter] [2021-12-21 15:39:21 ICT] <main> DEBUG: Ignoring file: /var/folders/sw/kqr0spsj2g75yr737kl1v9t80000gp/T/Prufin.ipa/SwiftSupport because it is NOT an iTMS package.
15:39:22 
15:39:22 [15:39:22]: [iTMSTransporter] [2021-12-21 15:39:21 ICT] <main> DEBUG: Ignoring file: /var/folders/sw/kqr0spsj2g75yr737kl1v9t80000gp/T/Prufin.ipa/AppThinning.plist because it is NOT an iTMS package.
15:39:22 
15:39:22 [15:39:22]: [iTMSTransporter] [2021-12-21 15:39:21 ICT] <main> ERROR: The directory: /var/folders/sw/kqr0spsj2g75yr737kl1v9t80000gp/T/Prufin.ipa does NOT have any valid iTMS packages.
15:39:22 
15:39:22 [15:39:22]: [iTMSTransporter] [2021-12-21 15:39:21 ICT] <main> DEBUG: Ignoring file: /var/folders/sw/kqr0spsj2g75yr737kl1v9t80000gp/T/Prufin.ipa/Prufin.ipa because it is NOT an iTMS package.
15:39:22 
15:39:22 [15:39:22]: [iTMSTransporter] [2021-12-21 15:39:21 ICT] <main> DEBUG: Ignoring file: /var/folders/sw/kqr0spsj2g75yr737kl1v9t80000gp/T/Prufin.ipa/Payload because it is NOT an iTMS package.
15:39:22 
15:39:22 [15:39:22]: [iTMSTransporter] [2021-12-21 15:39:21 ICT] <main> DEBUG: Ignoring file: /var/folders/sw/kqr0spsj2g75yr737kl1v9t80000gp/T/Prufin.ipa/SwiftSupport because it is NOT an iTMS package.
15:39:22 
15:39:22 [15:39:22]: [iTMSTransporter] [2021-12-21 15:39:21 ICT] <main> DEBUG: Ignoring file: /var/folders/sw/kqr0spsj2g75yr737kl1v9t80000gp/T/Prufin.ipa/AppThinning.plist because it is NOT an iTMS package.
15:39:22 
15:39:22 [15:39:22]: [iTMSTransporter] 
15:39:22 
15:39:22 [15:39:22]: [iTMSTransporter] 
15:39:22 
15:39:22 [15:39:22]: [iTMSTransporter] 
15:39:22 
15:39:22 [15:39:22]: [iTMSTransporter] Package Summary:
15:39:22 
15:39:22 [15:39:22]: [iTMSTransporter] [2021-12-21 15:39:21 ICT] <main> DBG-X: Returning 0
15:39:22 
15:39:22 [15:39:22]: iTunes Transporter output above ^
15:39:22 [15:39:22]: The directory: /var/folders/sw/kqr0spsj2g75yr737kl1v9t80000gp/T/Prufin.ipa does NOT have any valid iTMS packages.

15:39:22 [15:39:22]: Although errors occurred during execution of iTMSTransporter, it returned success status.
15:39:22 [15:39:22]: --------------------------------------------------------------------
15:39:22 [15:39:22]: Successfully uploaded package to App Store Connect. It might take a few minutes until it's visible online.
15:39:22 [15:39:22]: --------------------------------------------------------------------
15:39:22 [15:39:22]: Successfully uploaded the new binary to App Store Connect

### Environment
<details>
  <pre>
[✔] 🚀 
[16:32:09]: fastlane detected a Gemfile in the current directory
[16:32:09]: However, it seems like you didn't use `bundle exec`
[16:32:09]: To launch fastlane faster, please use
[16:32:09]: 
[16:32:09]: $ bundle exec fastlane env
[16:32:09]: 
[16:32:09]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[16:32:14]: Generating fastlane environment output, this might take a few seconds...
swift-driver version: 1.26.9 <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 11.5                                                    |
| Ruby                        | 3.0.3                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.30.1 (Apple Git-130)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.199.0/libexec/bin/fastlane |
| Host                        | macOS 11.5 (20G71)                                      |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/3.0.3/lib                        |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021                             |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 13.1                                                    |
| Swift Version               | 5.5.1                                                   |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.199.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-appcenter | 1.11.1  | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.89.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.8.0        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.5        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.5.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-playcustomapp_v1    | 0.6.0        |
| google-apis-androidpublisher_v3 | 0.14.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.8.0        |
| google-apis-storage_v1          | 0.10.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.35.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.4.0        |
| aws-partitions                  | 1.540.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-sdk-core                    | 3.124.0      |
| aws-sdk-kms                     | 1.52.0       |
| aws-sdk-s3                      | 1.109.0      |
| set                             | 1.0.1        |
| bundler                         | 2.3.0        |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.1        |
| date                            | 3.1.3        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.1        |
| uri                             | 0.10.1       |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.2.1        |
| digest                          | 3.0.0        |
| io-nonblock                     | 0.1.0        |
| io-wait                         | 0.2.0        |
| zlib                            | 2.0.0        |
| resolv                          | 0.2.1        |
| securerandom                    | 0.1.0        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.1        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.7        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| net-http                        | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.2.1        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.2        |
| fastlane-plugin-appcenter       | 1.11.1       |
| csv                             | 3.1.9        |
</details>

*generated on:* **2021-12-21**
</details>
 </pre>
</details>

</div>

**Comment by Wojcik** [comment]
Having the same issue

**Comment by abbotsd** [comment]
Note however, that Apple recommends you don’t specify the -t transport and instead allow Transporter to use automatic transport discovery to determine the best transport mode for your packages. For this reason, if the t option is passed, we will raise a warning.

**Comment by leewonghao** [comment]
> Note however, that Apple recommends you don’t specify the -t transport and instead allow Transporter to use automatic transport discovery to determine the best transport mode for your packages. For this reason, if the t option is passed, we will raise a warning.

Can you give specific instructions for example ?

**Comment by dokimyj** [comment]
It seems like `.ipa` file path has been passed to `-f` option for Transporter. Basically `-f` should take the path of `.itmsp` package path, while `-assetFile` should be with `.ipa/pkg/dmg` path. 

`/var/folders/sw/kqr0spsj2g75yr737kl1v9t80000gp/T/Prufin.ipa/Prufin.ipa`
(This line appears to be like `-f` option is executed because the Transporter app trys to find `.ipa` inside the `.ipa` file.)

Would you please show us how you executed `upload_to_testflight` (or `pilot`) with envs related to iTMSTransporter?
