### ISSUE TITLE
Deliver failed because of Apple iTunesTransporter remove DAV support 

### ISSUE THREAD

**Issue by LeeJunhui** [fastlane/fastlane#19744]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
After Apple has removed the DAV support of iTMSTransporter, Deliver action will failed like this below:

```
DEBUG [2021-12-23 17:43:10.20]: xcrun iTMSTransporter -m upload -jwt YourJWT -assetFile /var/folders/vj/ytr_xh754112jc_wkpz18w3w0000gp/T/xxx.ipa -t DAV -k 100000 2>&1
DEBUG [2021-12-23 17:43:15.49]: [Transporter]: INFO: Configuring logging...
DEBUG [2021-12-23 17:43:15.50]: [Transporter]: INFO: Logging level set to eXtreme
ERROR [2021-12-23 17:43:18.29]: [31mTransporter transfer failed.[0m
WARN [2021-12-23 17:43:18.29]: 
ERROR [2021-12-23 17:43:18.29]: [31mThe DAV transport is obsolete, and is no longer supported. Please use the HTTP transport instead.
[0m
WARN [2021-12-23 17:43:18.46]: [33m[iTMSTransporter] [2021-12-23 17:43:15 CST] <main>  INFO: Configuring logging...
[0m
WARN [2021-12-23 17:43:18.46]: [33m[iTMSTransporter] [2021-12-23 17:43:15 CST] <main>  INFO: Logging level set to eXtreme
[0m
WARN [2021-12-23 17:43:18.46]: [33m[iTMSTransporter] [2021-12-23 17:43:18 CST] <main> ERROR: The DAV transport is obsolete, and is no longer supported. Please use the HTTP transport instead.
[0m
WARN [2021-12-23 17:43:18.46]: [33m[iTMSTransporter] [2021-12-23 17:43:18 CST] <main> DBG-X: Returning 1
[0m
iTunes Transporter output above ^ERROR [2021-12-23 17:43:18.46]: [31mThe DAV transport is obsolete, and is no longer supported. Please use the HTTP transport instead.
Return status of iTunes Transporter was 1: The DAV transport is obsolete, and is no longer supported. Please use the HTTP transport instead.
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.[0m
```

I've browsed dozens of issues related to Deliver,but I can't find any solution.Can you guys figure it out? Thanks a lot~

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                                                                                            |
| --------------------------- | -------------------------------------------------------------------------------------------------------------------------------- |
| OS                          | 11.5.1                                                                                                                           |
| Ruby                        | 2.7.0                                                                                                                            |
| Bundler?                    | true                                                                                                                             |
| Git                         | git version 2.30.1 (Apple Git-130)                                                                                               |
| Installation Source         | ~/.jenkins/workspace/bookln-cdc-ios-upload-appstore-ipa-to-testflight/packages/sl-core/ios/vendor/bundle/ruby/2.7.0/bin/fastlane |
| Host                        | macOS 11.5.1 (20G80)                                                                                                             |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.7.0/lib                                                                                                     |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                                                                                                       |
| Is contained                | false                                                                                                                            |
| Is homebrew                 | false                                                                                                                            |
| Is installed via Fabric.app | false                                                                                                                            |
| Xcode Path                  | /Applications/Xcode-13.app/Contents/Developer/                                                                                   |
| Xcode Version               | 13.0                                                                                                                             |
| Swift Version               | 5.5                                                                                                                              |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

</details>

<details><summary>`./fastlane/Appfile`</summary>

</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.199.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                          | Version | Update-Status |
| ------------------------------- | ------- | ------------- |
| fastlane-plugin-appicon         | 0.16.0  | ✅ Up-To-Date  |
| fastlane-plugin-settings_bundle | 1.3.2   | ✅ Up-To-Date  |
| fastlane-plugin-badge           | 1.5.0   | ✅ Up-To-Date  |
| fastlane-plugin-pgyer           | 0.2.2   | ✅ Up-To-Date  |
| fastlane-plugin-versioning      | 0.5.0   | ✅ Up-To-Date  |
| fastlane-plugin-xcconfig        | 2.0.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.4.0        |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| concurrent-ruby                 | 1.1.9        |
| i18n                            | 1.8.10       |
| minitest                        | 5.14.4       |
| thread_safe                     | 0.3.6        |
| tzinfo                          | 1.2.9        |
| activesupport                   | 5.2.6        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| httpclient                      | 2.8.3        |
| json                            | 2.6.1        |
| algoliasearch                   | 1.27.5       |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.541.0      |
| aws-sigv4                       | 1.4.0        |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.124.0      |
| aws-sdk-kms                     | 1.52.0       |
| aws-sdk-s3                      | 1.109.0      |
| babosa                          | 1.0.4        |
| fastimage                       | 2.2.5        |
| bundler                         | 2.2.25       |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.89.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| multipart-post                  | 2.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.8.0        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.3.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.0        |
| mini_mime                       | 1.1.2        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-androidpublisher_v3 | 0.14.0       |
| google-apis-playcustomapp_v1    | 0.6.0        |
| digest-crc                      | 0.6.4        |
| google-apis-iamcredentials_v1   | 0.9.0        |
| google-apis-storage_v1          | 0.10.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.35.0       |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| badge                           | 0.13.0       |
| fuzzy_match                     | 2.0.4        |
| nap                             | 1.1.0        |
| netrc                           | 0.11.0       |
| ffi                             | 1.15.4       |
| ethon                           | 0.15.0       |
| typhoeus                        | 1.4.0        |
| cocoapods-core                  | 1.10.2       |
| cocoapods-deintegrate           | 1.0.5        |
| cocoapods-downloader            | 1.5.1        |
| cocoapods-plugins               | 1.0.0        |
| cocoapods-search                | 1.0.1        |
| cocoapods-trunk                 | 1.6.0        |
| cocoapods-try                   | 1.2.0        |
| escape                          | 0.0.4        |
| fourflusher                     | 2.3.1        |
| molinillo                       | 0.6.6        |
| ruby-macho                      | 1.4.0        |
| cocoapods                       | 1.10.2       |
| cocoapods-project-hmap          | 0.0.5        |
| coderay                         | 1.1.3        |
| fastlane-plugin-appicon         | 0.16.0       |
| fastlane-plugin-badge           | 1.5.0        |
| fastlane-plugin-pgyer           | 0.2.2        |
| fastlane-plugin-settings_bundle | 1.3.2        |
| fastlane-plugin-versioning      | 0.5.0        |
| fastlane-plugin-xcconfig        | 2.0.0        |
| subexec                         | 0.2.3        |
| graphicsmagick                  | 1.0.6        |
| method_source                   | 1.0.0        |
| pry                             | 0.14.1       |
| xcode-install                   | 2.6.6        |
</details>

*generated on:* **2021-12-23**
</details>

**Comment by LeeJunhui** [comment]
> 

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                                                                                            |
| --------------------------- | -------------------------------------------------------------------------------------------------------------------------------- |
| OS                          | 11.5.1                                                                                                                           |
| Ruby                        | 2.7.0                                                                                                                            |
| Bundler?                    | true                                                                                                                             |
| Git                         | git version 2.30.1 (Apple Git-130)                                                                                               |
| Installation Source         | ~/.jenkins/workspace/bookln-cdc-ios-upload-appstore-ipa-to-testflight/packages/sl-core/ios/vendor/bundle/ruby/2.7.0/bin/fastlane |
| Host                        | macOS 11.5.1 (20G80)                                                                                                             |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.7.0/lib                                                                                                     |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                                                                                                       |
| Is contained                | false                                                                                                                            |
| Is homebrew                 | false                                                                                                                            |
| Is installed via Fabric.app | false                                                                                                                            |
| Xcode Path                  | /Applications/Xcode-13.app/Contents/Developer/                                                                                   |
| Xcode Version               | 13.0                                                                                                                             |
| Swift Version               | 5.5                                                                                                                              |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.41.0"


require '../fastlane/app_type'
require '../fastlane/server_type'
require '../fastlane/build'
require '../fastlane/ding_talk'
require '../fastlane/dynamic_config'
require 'json'


default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # cocoapods
  end

  desc 'Runs all the tests'
  lane :test do
    scan
  end

  desc '书链demo'
  lane :app_demo do
    app(app_id: 10)
  end

  desc '新东方书加加'
  lane :app_sjj do
    app(app_id: 8)
  end

  desc '打包'
  desc '使用方法：bundle exec fastlane app app_id:10 is_inhouse:false is_dev:false'


  desc '参数：is_inhouse，optional，是否是测试包，如果是测试包，则使用企业账号打包，默认false。'
  desc '参数：is_dev，optional，是否开发签名的包，用于monkey测试等，默认false。'
  desc '参数：should_send_message，optional，是否打包成功后发送钉钉消息，默认true。'
  desc '参数：submit_for_review，optional，是否提交审核，默认false。'
  desc '参数：upload_to_test_flight，optional，是否上传到TestFlight，默认false。'
  desc '参数：match_force_update，Renew the provisioning profiles every time，默认true，手动执行的时候建议传false。'
  desc '参数：is_debug，optional，是否是调试模式，默认false。'
  desc '参数：base_host，optional，传入的值会替换为打包配置中的baseHost值。'
  desc '参数: dev_build, optional, 是否开启 expo-dev-client，默认false'
  lane :app do |options|
    app_id = options[:app_id]
    if app_id.nil?
      abort("\n\napp_id不能为空\n\n")
    end

    is_inhouse = options[:is_inhouse].nil? ? false : options[:is_inhouse]
    is_dev = options[:is_dev].nil? ? false : options[:is_dev]
    should_send_message = options[:should_send_message].nil? ? true : options[:should_send_message]
    submit_for_review = options[:submit_for_review].nil? ? false : options[:submit_for_review]
    upload_to_test_flight = options[:upload_to_test_flight].nil? ? false : options[:upload_to_test_flight]
    match_force_update = options[:match_force_update].nil? ? true : options[:match_force_update]
    is_debug = options[:is_debug].nil? ? false : options[:is_debug]
    base_host = options[:base_host].nil? ? nil : options[:base_host]
    dev_build = options[:dev_build].nil? ? nil : options[:dev_build]
    build(app_id, is_inhouse, is_dev, should_send_message, submit_for_review, upload_to_test_flight, match_force_update, is_debug, base_host, dev_build)
  end

  desc "切换应用"
  desc "会切换所有配置，包括bundleId、应用名、图标等各种配置"
  desc "使用方法：bundle exec fastlane switch_app app_id:10 is_inhouse:false is_dev:false"
  desc "参数：is_inhouse，optional，是否是测试包，如果是测试包，则使用企业账号打包。"
  desc "参数：is_dev，optional，是否开发签名的包，用于monkey测试等。"
  desc '参数：base_host，optional，传入的值会替换为打包配置中的baseHost值。'
  desc '参数：previous_vid，optional，获取之前版本的配置并替换，发布热更新的时候使用。'
  lane :switch_app do |options|
    app_id = options[:app_id]
    if app_id.nil?
      abort("\n\napp_id不能为空\n\n")
      abort("使用方法：bundle exec fastlane switch_app app_id:10\n\n")
    end

    is_inhouse = options[:is_inhouse].nil? ? false : options[:is_inhouse]
    is_dev = options[:is_dev].nil? ? false : options[:is_dev]
    base_host = options[:base_host].nil? ? nil : options[:base_host]
    previous_vid = options[:previous_vid].nil? ? 0 : options[:previous_vid]
    switch_app(app_id, is_inhouse, '?', base_host, previous_vid, '1')
  end

  desc "更新证书"
  desc "更新证书目前是一个单独的任务，每一次都会强制更新，并且把新添加的设备也更新进去"
  desc "会同时更新Company账号和Enterprise账号"
  desc "Company账号下development、adhoc、appstore这三种类型都会更新"
  desc "日常打包就不再每次更新证书，以提高打包速度"
  desc "参数：app_id"
  lane :update_certificates do |options|
    app_id = options[:app_id]
    if app_id.nil?
      abort("\n\napp_id不能为空\n\n")
      abort("使用方法：bundle exec fastlane update_certificates app_id:10\n\n")
    end

    update_certificates(app_id)
  end

  desc "更新证书"
  desc "使用方法：bundle exec fastlane update_certificate_demo_wugensongai"
  lane :update_certificate_demo_wugensongai do |options|
    update_certificate_demo_wugensongai
  end

  lane :register_all_devices do |options|
    # WZC352K2HA "Beijing New Oriental Dogwood Cultural Communications Co., Ltd." (Company/Organization)
    # 9SV7S73XXB "Beijing Rongdeji Education Technology Co., Ltd." (Company/Organization)
    # VFDJ7UN26F "Beijing Yinglang Times Cultural Development Co., Ltd." (Company/Organization)
    # Z7DFPRAC33 "Beijing Zhenyu Rich International Cultural Co.,Ltd" (Company/Organization)
    # 2KT364D29M "Hangzhou Yunti Technology Co. Ltd." (Company/Organization)
    # E99ZYE7U8L "Hangzhou Yunti Technology Co. Ltd." (In-House)
    # 3QPKV2WK9T "Zhejiang University Press Co.,Ltd." (Company/Organization)

    team_xdf = 'WZC352K2HA'
    team_rdj = '9SV7S73XXB'
    team_angxiu = 'VFDJ7UN26F'
    team_waiyu = 'Z7DFPRAC33'
    team_lfs = '3QPKV2WK9T'
    team_hhtk = '358ADJARFQ'
    team_luqi = 'D5M79568QS'

    team_bookln = '2KT364D29M'
    team_bookln_inhouse = 'E99ZYE7U8L'

    [team_xdf, team_angxiu, team_rdj, team_waiyu, team_lfs, team_bookln].each do |team_id|
      register_devices(
        username: "iosdev@yeteam.com",
        team_id: team_id,
        
        # 下面列表是所有的测试机
        devices: {
          "b-6-cl" => "44e103c3a0139f4de736f808aea47e64d19f238c",
          "b-6-cx" => "4da18ca17698f4928594cc5662ac5c9044762352",
          "b-5" => "22fb9184cbcc5dcd2058a4afa27cb713dae715bd",
          "b-6-wl" => "83f9aa1c516b7400fea8fcb6987a21528386063f",
          "b-6p" => "83c10000b1c714eb0f05c5a299c2d4543a07ff16",
          "b-iPadAir" => "649f6cc63d4009a1d5b3e37dc1da56bb475f01cf",
          "b-6-wjb" => "6459b36564bfc60849a4410c971d851efc0ed3d7",
          "b-7-zq" => "1c0dc0d97e8f6c79a4280d99d3c01e2884543306",
          "b-x-cx" => "3d317da15ddaf0e497a7e070781988d45a65d228",
          "b-x-zz" => "23d063e8b8797a300be83891a8ac2969027ad919",
          "b-7p-wws" => "f0aa41d998c631b9469102e80cc9da4c7fe4bebd",
          "b-7p-wjb" => "ba974ff1636a3b620f0e0b2afcf94160271af482",
          "b-w2-wjb" => "03fa43f1f40a72fcab30c03f293c06401cdce57b",
          "b-7-zwd" => "84a23feed8ca6f927d7981cc49f963fac6d9e846",
          "b-7-kq" => "fe30f8e03037cd2033d26509c803389085d9dc26",
          "b-iPadPro97-wjb" => "f828f748dc2c24b45c1847a3a7aa2043d662a468",
          "b-7p-mayi" => "9f79d40cff2ed7171373f7b3f4c192e6713f1a82",
          "b-6-yezi" => "bccdf007b63f1ef835108e975505d844caad554e",
          "b-x-mingyang" => "ef993a86f8769cb0535686099260e4308b72f282",
          "b-xsmax-zw" => "00008020-001A38E41E9A002E",
          "b-8p-yy" => "26f02d3ff2668d568c4daa0116308a23ff1fa3df",
          "b-xs-wm" => "00008020-000209200281002E",
          "b-xr-yellow" => "00008020-001A1D303692002E",
          "b-x-qingniu" => "05c640cf771aefa42fbb22e78bbf039401218519",
          "b-x-qingyun" => "3717f3b0d5001d20af80812176620545f65aa974",
          "b-ipad-7" => "b4022a045b80c21067b1317cb051c4cd2198052b",
          "b-11-mayi" => "00008030-00010CA23A01802E",
          "b-8p-yueyue" => "9bd00a74fa29791a7a44295a22c604400b936095",
          "b-6s-fucheng" => "fe7eec2eb667df7fd495f336e861c8cc8ec9d15a",
          "b-ipadmini2-wangling" => "14d93edbf5f9387d74fa59a0b51a147d5fb7f3b1",
          "b-11max-zhouwei" => "00008030-00026C2611E2802E",
          "b-xs-wjb" => "00008020-000231D60E68002E",
          "b-yuanshun-ipad-mini2" => "a9bab14bc694ab2d088e52eedcc7495e85531a38",
          "guzi-xs" => "00008020-000E1C993EF8002E",
          "unknown-ipad" => "00008027-000C30D01AE3002E",
          "jia-6s" => "a6aaf471ca04f7ec1f650fa75abb7ec6fc8f4587",
          "yuanshun-11" => "00008020-000D59420CE9002E",
          "zhouqinyu-iphone11" => "00008030-001029241442802E",
          "ZhouShisong-iPad" => "00008020-001C189C0A51002E",
          "b-yezi-7p-1" => "bd1fda9dd9bc7fd655e6f0b88aefb862778eef5e",
          "b-yezi-7p-2" => "42bc4e8d33be857c6d22b52c3c84a383f8695084",
          "b-ipad12.9-aini" => "00008103-001C706E1E53001E",
          "李俊辉iPhone" => "f9f586cb6f0cd305e76c8536d4c52f09673526b1",
          "李俊辉的iPhone" => "ad689f37a98274088627c089d676c7d21ef4fa1f"
        }
      )
    end
  end

  desc '自动检测最新生成的 archive 包是否有 appstore 的 ipa 包，如果有则上传至 testflight'
  desc '使用方法: bundle exec fastlane auto_detect_latest_archive_then_upload_to_testflight'
  desc '参数：app_id，required'
  lane :auto_detect_latest_archive_then_upload_to_testflight do |options|
    app_id = options[:app_id]
      if app_id.nil?
        abort("\n\napp_id不能为空\n\n")
      end
    find_latest_archive_and_ipa(app_id)
  end

  desc '测试用 修改 Xcode build phase 和 build settings，确保 dev build 可以打出 jsbundle'
  lane :modify_xcode_project_settings do
    modify_xcode_project_settings()
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    if is_ci
      ding_talk_send_text_message("😱 #{exception.to_s}", false)
    end
  end
end


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby

ENV['GYM_WORKSPACE'] = 'BooklnSaaS.xcworkspace'
ENV['GYM_SCHEME'] = 'BooklnSaaS'


# yunti's mac mini
ENV['MATCH_KEYCHAIN_PASSWORD'] = 'yunti'


# 解决TestFlight上传失败问题
ENV['DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS'] = '-t DAV'


ENV['CRASHLYTICS_API_TOKEN'] = '9217b3261c78fd6c99502ecfb2cf0c556ddee82c'


ENV['GYM_INCLUDE_SYMBOLS'] = true
ENV['GYM_INCLUDE_BITCODE'] = false


# 默认是10秒钟，导出ipa的时候经常会出问题，特别是机器比较卡的时候
ENV['FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT'] = 60
ENV['FASTLANE_XCODEBUILD_SETTINGS_RETRIES'] = 10


# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.199.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                          | Version | Update-Status |
| ------------------------------- | ------- | ------------- |
| fastlane-plugin-appicon         | 0.16.0  | ✅ Up-To-Date  |
| fastlane-plugin-settings_bundle | 1.3.2   | ✅ Up-To-Date  |
| fastlane-plugin-badge           | 1.5.0   | ✅ Up-To-Date  |
| fastlane-plugin-pgyer           | 0.2.2   | ✅ Up-To-Date  |
| fastlane-plugin-versioning      | 0.5.0   | ✅ Up-To-Date  |
| fastlane-plugin-xcconfig        | 2.0.0   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.4.0        |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| concurrent-ruby                 | 1.1.9        |
| i18n                            | 1.8.10       |
| minitest                        | 5.14.4       |
| thread_safe                     | 0.3.6        |
| tzinfo                          | 1.2.9        |
| activesupport                   | 5.2.6        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| httpclient                      | 2.8.3        |
| json                            | 2.6.1        |
| algoliasearch                   | 1.27.5       |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.541.0      |
| aws-sigv4                       | 1.4.0        |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.124.0      |
| aws-sdk-kms                     | 1.52.0       |
| aws-sdk-s3                      | 1.109.0      |
| babosa                          | 1.0.4        |
| fastimage                       | 2.2.5        |
| bundler                         | 2.2.25       |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.89.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| multipart-post                  | 2.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.8.0        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.3.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.0        |
| mini_mime                       | 1.1.2        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-androidpublisher_v3 | 0.14.0       |
| google-apis-playcustomapp_v1    | 0.6.0        |
| digest-crc                      | 0.6.4        |
| google-apis-iamcredentials_v1   | 0.9.0        |
| google-apis-storage_v1          | 0.10.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.35.0       |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| badge                           | 0.13.0       |
| fuzzy_match                     | 2.0.4        |
| nap                             | 1.1.0        |
| netrc                           | 0.11.0       |
| ffi                             | 1.15.4       |
| ethon                           | 0.15.0       |
| typhoeus                        | 1.4.0        |
| cocoapods-core                  | 1.10.2       |
| cocoapods-deintegrate           | 1.0.5        |
| cocoapods-downloader            | 1.5.1        |
| cocoapods-plugins               | 1.0.0        |
| cocoapods-search                | 1.0.1        |
| cocoapods-trunk                 | 1.6.0        |
| cocoapods-try                   | 1.2.0        |
| escape                          | 0.0.4        |
| fourflusher                     | 2.3.1        |
| molinillo                       | 0.6.6        |
| ruby-macho                      | 1.4.0        |
| cocoapods                       | 1.10.2       |
| cocoapods-project-hmap          | 0.0.5        |
| coderay                         | 1.1.3        |
| fastlane-plugin-appicon         | 0.16.0       |
| fastlane-plugin-badge           | 1.5.0        |
| fastlane-plugin-pgyer           | 0.2.2        |
| fastlane-plugin-settings_bundle | 1.3.2        |
| fastlane-plugin-versioning      | 0.5.0        |
| fastlane-plugin-xcconfig        | 2.0.0        |
| subexec                         | 0.2.3        |
| graphicsmagick                  | 1.0.6        |
| method_source                   | 1.0.0        |
| pry                             | 0.14.1       |
| xcode-install                   | 2.6.6        |
</details>


*generated on:* **2021-12-23**
</details>

**Comment by LeeJunhui** [comment]
> It seems like you have not included the output of `fastlane env`
> To make it easier for us help you resolve this issue, please update the issue to include the output of `fastlane env` 👍

I've updated the output of `fastlane env`

**Comment by Schnecik** [comment]
Had the same issue thank you for sharing this amazing post..

**Comment by NigelGan** [comment]
Same issue and appreciate if @LeeJunhui you have any update/fix, thanks.

**Comment by LeeJunhui** [comment]
> Same issue and appreciate if @LeeJunhui you have any update/fix, thanks.

I've changed the transport type of iTMSTransporter from DAV to Aspera, but after executed the Fastlane Deliver Action, the console still outputs DAV issue.And I also searched in the Fastlane source code,but cannot find anything related to DAV besides the picture below
![image](https://user-images.githubusercontent.com/9007793/147547118-3163186c-1b99-4010-8360-f2ded027c628.png)

**Comment by LeeJunhui** [comment]
> Same issue and appreciate if @LeeJunhui you have any update/fix, thanks.

After couple of times of execution of Deliver Action, it finally succeed.

**Comment by Thangaraj-M** [comment]
We not require to set the upload param with -t option. The Transporter will choose that automatically as per the Transporter guide - https://help.apple.com/itc/transporteruserguide/#/apdATD1E1288-D1E1A1303-D1E1288A1126.
If remove the Environment variable **DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS** and try that, then it will work.
