### ISSUE TITLE
Spaceship submit for review "request is forbidden for security reasons"

### ISSUE THREAD

**Issue by simondelphia** [fastlane/fastlane#19747]
Opened [a discussion a while ago](https://github.com/fastlane/fastlane/discussions/19427) but it hasn't gotten any attention so I'm escalating this to an issue.

I'm trying to automate submitting new builds for external beta review on TestFlight using Spaceship.

Here's the relevant lane:

```
  lane :spaceshipping do |options|
    Spaceship::Tunes.login('user', 'pass')
    app = Spaceship::Tunes::Application.find("my.bundle.id")
    
    train = app.build_trains["1.0.0"]
    build = train.last
    build.submit_for_testflight_review!
  end
```

When I do this I get the error:

> This request is forbidden for security reasons - The API key in use does not allow this request

1) I'm not sure why this is referencing an API key if I've logged in with a username and password, and
2) How do I get around this?

The user I'm using has "App Manager" access but I also tried bumping it to an "Admin" and that didn't work either. Doesn't seem like that should be necessary anyway. 

Unless something has changed recently the fact that `submit_for_testflight_review` exists implies that it's possible to do this.

It looks like there are other methods using `ConnectAPI` to do this (e.g. https://github.com/fastlane/fastlane/issues/16294) but I'm not sure where to find documentation for these other methods (`post_beta_app_review_submission`, `patch_beta_app_review_detail` etc)

**Comment by lucgrabowski** [comment]
Hi, you could submit a build for external beta review with `upload_to_testflight`.
If build was previously uploaded to Testflight you could use `distribute_only = true`.
Please note that if you want to distribute build externally you need to use `distribute_external` and `groups` parameters.
You can read more about `upload_to_testflight` in docs: https://docs.fastlane.tools/actions/upload_to_testflight/

If you want to do it manually in spaceship playground, you could probably do something similar to:
- fetch app https://github.com/fastlane/fastlane/blob/master/spaceship/docs/AppStoreConnect.md#applications
`app = Spaceship::ConnectAPI::App.find("com.krausefx.app")`
- select a build, e.g.:
`build = Spaceship::ConnectAPI::Build.all(app_id: app.id, sort: "-uploadedDate", limit: 1).first`
- check if it's ready for submission
`build.ready_for_beta_submission?`
- and submit
`build.post_beta_app_review_submission`

If you want to know how `post_beta_app_review_submission` and `patch_beta_app_review_detail` are used in `upload_to_testflight`, you could take a look at `BuildManager`'s code:
https://github.com/fastlane/fastlane/blob/master/pilot/lib/pilot/build_manager.rb

**Comment by simondelphia** [comment]
Thank you very much I was able to make some progress on this using `upload_to_testflight`!
