### ISSUE TITLE
Download metadata via deliver seems to ignore api key (file)

### ISSUE THREAD

**Issue by phjs** [fastlane/fastlane#19752]
### New Issue Checklist
- [x] Updated Fastlane to the latest version
- [x] I read the Contribution Guidelines
- [x] I read docs.fastlane.tools
- [x] I searched for existing GitHub issues

### Issue Description
I want to use the new AppStoreConnect API to download metadata via deliver. Therefor, I have created a JSON key file as described within the [fastlane documentation](https://docs.fastlane.tools/app-store-connect-api/#using-fastlane-api-key-json-file).

To trigger the metadata download I run the following shell string

```
sh(command: "fastlane deliver download_metadata -api_key_path 'JSON_FILE_PATH' -m 'METADATA_PATH' -w 'SCREENHSOT_PATH' -u $USERNAME -a $APP_ID"
```
**Note:**
1. The variables `$USERNAME` and `$APP_ID` are defined in `.env` files.
2. Without `-u $USERNAME` I get `[!] No value found for 'username'`

When I execute the above command the console shows `Login to App Store Connect (USERNAME)`, but after an eternity of nothing happening, it triggers the old AppleID authentication, instead of using the JSON key file.

### What I also tried and didn't worked
1. Put all necessary variable into an `.env` file and called `app_store_connect_api_key` before executing `deliver download_metadata` (as described [here](https://pgu.dev/2021/06/26/app-store-connect-access-key.html)) 
1. Remember the return value of `app_store_connect_api_key` in a variable and passed it as `api_key` into the deliver call

### Maybe it is the JSON key file?
I run `check_app_store_metadata` with the same JSON key file and this worked without any problems

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 12.1                                                       |
| Ruby                        | 3.0.3                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.32.0 (Apple Git-132)                         |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.199.0/libexec/bin/fastlane |
| Host                        | macOS 12.1 (21C52)                                         |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.0.3/lib                        |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021                                |
| Is contained                | false                                                      |
| Is homebrew                 | true                                                       |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
| Xcode Version               | 13.2                                                       |
| Swift Version               | 5.5.2                                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.199.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.89.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.8.0        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.5        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.5.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.32       |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-playcustomapp_v1    | 0.6.0        |
| google-apis-androidpublisher_v3 | 0.14.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.8.0        |
| google-apis-storage_v1          | 0.10.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.35.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.4.0        |
| aws-partitions                  | 1.540.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-sdk-core                    | 3.124.0      |
| aws-sdk-kms                     | 1.52.0       |
| aws-sdk-s3                      | 1.109.0      |
| set                             | 1.0.1        |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.1        |
| date                            | 3.1.3        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.1        |
| uri                             | 0.10.1       |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.2.1        |
| digest                          | 3.0.0        |
| io-nonblock                     | 0.1.0        |
| io-wait                         | 0.2.0        |
| zlib                            | 2.0.0        |
| resolv                          | 0.2.1        |
| securerandom                    | 0.1.0        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.1        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.7        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| net-http                        | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.2.1        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.2        |
</details>

*generated on:* **2021-12-28**
</details>

**Comment by lucgrabowski** [comment]
Hi, you should use two hyphens for api_key_path  option: `--api_key_path`.
To use variables in a double-quoted string you should interpolate them with `#{}`.
So the command would be:

`sh(command: "fastlane deliver download_metadata --api_key_path 'JSON_FILE_PATH' -m 'METADATA_PATH' -w 'SCREENHSOT_PATH' -u #{ENV["USERNAME"]} -a #{ENV["APP_ID"]}"`
or shorter:
`sh "fastlane deliver download_metadata --api_key_path 'JSON_FILE_PATH' -m 'METADATA_PATH' -w 'SCREENHSOT_PATH' -u #{ENV["USERNAME"]} -a #{ENV["APP_ID"]}"`

**Comment by phjs** [comment]
Hello Lukasz, since the paths for screenshots and metadata are declared with a single hyphen I assumed this is also the case for the API key. Adding the second hyphen solved my problem. Thank you very much. 

I hope this isn't too much away from my initial question, but how would the same call work with the actual API key? Is it even possible to pass a hash as a parameter with the `sh` command?

I tried the following calls without success:

1.
```
apiKey = app_store_connect_api_key
shellString = "fastlane deliver download_metadata -m '#{PATH}' -w '#{PATH}' -a '#{ENV["APP_ID"]}' --api_key #{apiKey}"
```

2.
```
apiKey = app_store_connect_api_key
shellString = "fastlane deliver download_metadata -m '#{PATH}' -w '#{PATH}' -a '#{ENV["APP_ID"]}' --api_key '#{apiKey}'"
```
3.
```
app_store_connect_api_key
shellString = "fastlane deliver download_metadata -m '#{PATH}' -w '#{PATH}' -a '#{ENV["APP_ID"]}' --api_key #{lane_context[SharedValues::APP_STORE_CONNECT_API_KEY]}" 
```
4.
```
app_store_connect_api_key
shellString = "fastlane deliver download_metadata -m '#{PATH}' -w '#{PATH}' -a '#{ENV["APP_ID"]}'" 
```


The following call worked:
```
lane :validate do |options|
        apiKey = app_store_connect_api_key
        
        check_app_store_metadata(
            api_key: apiKey,
            app_identifier: ENV["APP_ID"],
            include_in_app_purchases: false
        )
end
```
