### ISSUE TITLE
App

### ISSUE THREAD

**Issue by engynzss** [fastlane/fastlane#19759]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: [e.g. `2.x.x`]
- Last working version: [e.g. `2.x.x`]

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by lucgrabowski** [comment]
@engynzss Hi, I'm closing this issue as description is empty. Please open a new one with description of an issue if needed.
