### ISSUE TITLE
Fastlane Init detecting iOS code in Android directory but no iOS project, so Command does not run

### ISSUE THREAD

**Issue by phamsarah** [fastlane/fastlane#19769]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Trying to run "fastlane init" in my Android project (which has a Gitlab submodule containing iOS code) and it thinks theres an iOS project in the directory. I am only doing Android though. 

My directory is like:
Artemis (Folder) -> 

##### Command executed
fastlane init
fastlane init --verbose

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> fastlane init
[✔] 🚀 
[✔] Looking for iOS and Android projects in current directory...
[11:58:27]: It looks like there is no iOS project in the current directory, though we did find one in a sub-directory
[11:58:27]: Please `cd` into the directory of the intended Xcode project you wish to use.

[!] Please `cd` into the directory of the intended Xcode project you wish to use and run `fastlane init` again</pre>
</details>

<details>
  <pre> spham$ fastlane init --verbose
[✔] 🚀 
DEBUG [2022-01-06 12:00:02.80]: Checking if there are any plugins that should be loaded...
[✔] Looking for iOS and Android projects in current directory...
ERROR [2022-01-06 12:00:04.63]: It looks like there is no iOS project in the current directory, though we did find one in a sub-directory
ERROR [2022-01-06 12:00:04.63]: Please `cd` into the directory of the intended Xcode project you wish to use.
/usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': \e[31m[!] Please `cd` into the directory of the intended Xcode project you wish to use and run `fastlane init` again\e[0m (FastlaneCore::Interface::FastlaneError)
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane/lib/fastlane/setup/setup.rb:97:in `start'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane/lib/fastlane/commands_generator.rb:122:in `block (2 levels) in run'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/bin/fastlane:25:in `load'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/bin/fastlane:25:in `<main>'
/usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': Please `cd` into the directory of the intended Xcode project you wish to use and run `fastlane init` again (FastlaneCore::Interface::FastlaneError)
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane/lib/fastlane/setup/setup.rb:97:in `start'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane/lib/fastlane/commands_generator.rb:122:in `block (2 levels) in run'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/gems/fastlane-2.199.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/bin/fastlane:25:in `load'
	from /usr/local/Cellar/fastlane/2.199.0/libexec/bin/fastlane:25:in `<main></pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 11.5.2                                                  |
| Ruby                        | 3.0.3                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.33.0                                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.199.0/libexec/bin/fastlane |
| Host                        | macOS 11.5.2 (20G95)                                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/3.0.3/lib                        |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021                             |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 13.2.1                                                  |
| Swift Version               | 5.5.2                                                   |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.199.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.89.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.8.0        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.5        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.5.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.32       |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-playcustomapp_v1    | 0.6.0        |
| google-apis-androidpublisher_v3 | 0.14.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.8.0        |
| google-apis-storage_v1          | 0.10.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.35.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.4.0        |
| aws-partitions                  | 1.540.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-sdk-core                    | 3.124.0      |
| aws-sdk-kms                     | 1.52.0       |
| aws-sdk-s3                      | 1.109.0      |
| set                             | 1.0.1        |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.1        |
| date                            | 3.1.3        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.1        |
| uri                             | 0.10.1       |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.2.1        |
| digest                          | 3.0.0        |
| io-nonblock                     | 0.1.0        |
| io-wait                         | 0.2.0        |
| zlib                            | 2.0.0        |
| resolv                          | 0.2.1        |
| securerandom                    | 0.1.0        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.1        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.7        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| net-http                        | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.2.1        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.2        |
</details>

*generated on:* **2022-01-06**
</details> </pre>
</details>

**Comment by lucgrabowski** [comment]
hi @phamsarah It looks like the init process prefers iOS app projects, so when you have an iOS project in a subdirectory of an Android project, init won't set fastlane up for Android project.

The easiest way to set it up for Android would be to open `Terminal.app`, go to directory with Android project, open `irb`, and run two commands: 1. to require fastlane gem, 2. to setup project for Android:
```ruby
require 'fastlane'
Fastlane::SetupAndroid.new.setup_android
```

**Comment by phamsarah** [comment]
<img width="1612" alt="Screen Shot 2022-01-10 at 10 45 03 AM" src="https://user-images.githubusercontent.com/46578346/148794779-6c2e8a9b-f3a7-4ed1-be32-141d9b3bd39c.png">
@lucgrabowski Thank you for the suggestion! I have tried this and I have attached my results:

**Comment by lucgrabowski** [comment]
`irb` is a ruby console, you can execute ruby code there. It should be the easiest way to run setup for Android with those 2 steps above as a workaround.

I see that requiring fastlane gem in irb fails. It's because you have 2 ruby versions - ruby installed with homebrew and another ruby version that was shipped with MacOS and somehow irb uses system-wide installation instead of ruby installed with homebrew which was used when you ran `fastlane init`.
I've never installed ruby with homebrew, but I see 2 options to fix this, you could install ruby version manager, e.g. rbenv as advised in https://docs.fastlane.tools/getting-started/ios/setup/, 
or  simply make sure that fastlane gem is also installed in system-wide ruby with `gem install fastlane` before running `irb`.

**Comment by phamsarah** [comment]
@lucgrabowski Tried 'gem install fastlane' and got an error response, this may be due to me doing this on a work laptop and not having all read/write permissions?

<details>
  <pre> gem install fastlane
  
  Building native extensions. This could take a while...
ERROR:  Error installing fastlane:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.6.0/gems/unf_ext-0.0.8/ext/unf_ext
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20220110-86770-xl70m4.rb extconf.rb
checking for -lstdc++... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/$(RUBY_BASE_NAME)
	--with-static-libstdc++
	--without-static-libstdc++
	--with-stdc++lib
	--without-stdc++lib
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:546:in `block in try_link0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:543:in `try_link0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:570:in `try_link'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:789:in `try_func'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:1016:in `block in have_library'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:959:in `block in checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:361:in `block (2 levels) in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:331:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:361:in `block in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:331:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:357:in `postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:958:in `checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:1011:in `have_library'
	from extconf.rb:6:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-20/2.6.0/unf_ext-0.0.8/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.6.0/gems/unf_ext-0.0.8 for inspection.
Results logged to /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-20/2.6.0/unf_ext-0.0.8/gem_make.out
  </pre>
  </details>
<img width="779" alt="Screen Shot 2022-01-10 at 2 10 26 PM" src="https://user-images.githubusercontent.com/46578346/148824749-1d846dbf-639c-4d23-9f55-552311d60512.png">

  
  Also ran 'ruby --version':

**Comment by shuLeesin** [comment]
> @lucgrabowski Tried 'gem install fastlane' and got an error response, this may be due to me doing this on a work laptop and not having all read/write permissions?
> 
> <img alt="Screen Shot 2022-01-10 at 2 10 26 PM" width="779" src="https://user-images.githubusercontent.com/46578346/148824749-1d846dbf-639c-4d23-9f55-552311d60512.png">
> 
> Also ran 'ruby --version':

`/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
ERROR:  Error installing fastlane:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.6.0/gems/unf_ext-0.0.8/ext/unf_ext
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20220120-58177-1s49o21.rb extconf.rb
Building has failed. See above output for more information on the failure.
To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-20/2.6.0/unf_ext-0.0.8/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.6.0/gems/unf_ext-0.0.8 for inspection.
Results logged to /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-20/2.6.0/unf_ext-0.0.8/gem_make.out
ahe@Ashe-2 ~ % ruby --version               
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]`

I also have this problem, have you solved it?

**Comment by phamsarah** [comment]
@shuLeesin I haven't solved it, what @lucgrabowski last suggested didn't work either

**Comment by shuLeesin** [comment]
您的邮件我已经收到，我会尽快回复，谢谢!!!

**Comment by lucgrabowski** [comment]
The error from the log says that you need to install command line tools.
>You have to install development tools first

This is a common issue. To install developer tools, you need to run `xcode-select --install` in terminal and it should help. If it fails, you can post error here, maybe someone will be able to help.

**Comment by phamsarah** [comment]
@lucgrabowski
<img width="1153" alt="Screen Shot 2022-01-20 at 3 44 08 PM" src="https://user-images.githubusercontent.com/46578346/150419202-bb741e12-dc37-4fcf-a392-c3146fb7eff1.png">
I already went down the "Software Update" rabbit hole 

then tried 'gem install fastlane' again:

`Building native extensions. This could take a while...
ERROR:  Error installing fastlane:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.6.0/gems/unf_ext-0.0.8/ext/unf_ext
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20220120-51113-dc0pz5.rb extconf.rb
checking for -lstdc++... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/$(RUBY_BASE_NAME)
	--with-static-libstdc++
	--without-static-libstdc++
	--with-stdc++lib
	--without-stdc++lib
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:546:in `block in try_link0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:543:in `try_link0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:570:in `try_link'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:789:in `try_func'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:1016:in `block in have_library'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:959:in `block in checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:361:in `block (2 levels) in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:331:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:361:in `block in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:331:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:357:in `postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:958:in `checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:1011:in `have_library'
	from extconf.rb:6:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-20/2.6.0/unf_ext-0.0.8/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.6.0/gems/unf_ext-0.0.8 for inspection.
Results logged to /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-20/2.6.0/unf_ext-0.0.8/gem_make.out`

**Comment by shuLeesin** [comment]
您的邮件我已经收到，我会尽快回复，谢谢!!!
