### ISSUE TITLE
Fastlane build hangs at copy xcframework step with Github Actions

### ISSUE THREAD

**Issue by thula-belive** [fastlane/fastlane#19776]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I can run successfully same build command in my local machine and simple test project with Github Actions. 

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [09:33:46]: ▸ Compiling JoinTextView.xib
[09:33:46]: ▸ Compiling RedPacketAnnouncementView.xib
[09:33:46]: ▸ Compiling GiftAnnouncementView.xib
[09:33:46]: ▸ Compiling MissionClaimView.xib
[09:33:46]: ▸ Compiling DailyMissionAlertView.xib
[09:33:47]: ▸ Compiling RedPacketCountDownView.xib
[09:33:47]: ▸ Compiling ContentChatView.xib
[09:33:47]: ▸ Compiling BottomTabbar.xib
[09:33:47]: ▸ Compiling AlertPopupView.xib
[09:33:47]: ▸ Compiling Wallet.storyboard
[09:33:48]: ▸ Compiling Video.storyboard
[09:33:48]: ▸ Compiling Profile.storyboard
[09:33:54]: ▸ Compiling Prelive.storyboard
[09:33:54]: ▸ Compiling Post.storyboard
[09:33:54]: ▸ Compiling Login.storyboard
[09:33:54]: ▸ Compiling Live.storyboard
[09:33:58]: ▸ Compiling Club.storyboard
[09:33:58]: ▸ Compiling Chat.storyboard
[09:33:58]: ▸ Compiling Main.storyboard
[09:33:59]: ▸ Compiling KDealViewer.storyboard
[09:33:59]: ▸ Compiling KDeal.storyboard
[09:33:59]: ▸ Compiling LaunchScreen.storyboard
[09:35:39]: ▸ Processing Info-STG.plist
[09:35:39]: ▸ Generating 'wakelearningSTG.app.dSYM'
[09:35:42]: ▸ Running script 'Run Script'
[09:35:42]: ▸ Copying /Users/runner/work/knockknock-ios/knockknock-ios/AdjustSigSdk.xcframework/ios-armv7_arm64/AdjustSigSdk.framework
Error: The operation was canceled.</pre>
</details>

### Environment

<details>
  <pre> ### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.199.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.3.2   | ✅ Up-To-Date  |
| fastlane-plugin-json                      | 1.0.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.4.0        |
| bundler                                   | 2.2.33       |
| rake                                      | 13.0.6       |
| rexml                                     | 3.2.5        |
| CFPropertyList                            | 3.0.5        |
| concurrent-ruby                           | 1.1.9        |
| i18n                                      | 1.8.11       |
| minitest                                  | 5.15.0       |
| thread_safe                               | 0.3.6        |
| tzinfo                                    | 1.2.9        |
| activesupport                             | 5.2.6        |
| public_suffix                             | 4.0.6        |
| addressable                               | 2.8.0        |
| httpclient                                | 2.8.3        |
| json                                      | 2.6.1        |
| algoliasearch                             | 1.27.5       |
| artifactory                               | 3.0.15       |
| atomos                                    | 0.1.3        |
| aws-eventstream                           | 1.2.0        |
| aws-partitions                            | 1.546.0      |
| aws-sigv4                                 | 1.4.0        |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.125.1      |
| aws-sdk-kms                               | 1.53.0       |
| aws-sdk-s3                                | 1.111.1      |
| babosa                                    | 1.0.4        |
| claide                                    | 1.0.3        |
| fuzzy_match                               | 2.0.4        |
| nap                                       | 1.1.0        |
| netrc                                     | 0.11.0       |
| ffi                                       | 1.15.4       |
| ethon                                     | 0.15.0       |
| googleauth                                | 1.1.0        |
| mini_mime                                 | 1.1.2        |
| trailblazer-option                        | 0.1.2        |
| uber                                      | 0.1.0        |
| representable                             | 3.1.1        |
| retriable                                 | 3.1.2        |
| webrick                                   | 1.7.0        |
| google-apis-core                          | 0.4.1        |
| google-apis-androidpublisher_v3           | 0.14.0       |
| google-apis-playcustomapp_v1              | 0.6.0        |
| google-apis-iamcredentials_v1             | 0.9.0        |
| google-apis-storage_v1                    | 0.10.0       |
| google-cloud-env                          | 1.5.0        |
| google-cloud-errors                       | 1.2.0        |
| google-cloud-core                         | 1.6.0        |
| google-cloud-storage                      | 1.35.0       |
| mini_magick                               | 4.11.0       |
| naturally                                 | 2.2.1        |
| optparse                                  | 0.1.1        |
| plist                                     | 3.6.0        |
| rubyzip                                   | 2.3.2        |
| security                                  | 0.1.3        |
| simctl                                    | 1.6.8        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.8.0        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| word_wrap                                 | 1.0.0        |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.1        |
| fastlane-plugin-firebase_app_distribution | 0.3.2        |
| fastlane-plugin-json                      | 1.0.0        |
</details> </pre>
</details>

**Comment by Kukurijek** [comment]
Can you provide your github action configuration and the error you are geting?
