### ISSUE TITLE
google_play_track_release_names return Invalid request when track don't exist

### ISSUE THREAD

**Issue by NicolasLourenco** [fastlane/fastlane#19787]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When I call `google_play_track_release_names`, if the track don't exist, it return an error `Invalid request`.

##### Command executed
```
google_play_track_release_names(
        package_name: "com.package.name",
        track: "beta"
      )
```

##### Complete output when running fastlane, including the stack trace and command used
```
INFO [2022-01-13 11:18:51.54]: ---------------------------------------------
INFO [2022-01-13 11:18:51.54]: --- Step: google_play_track_release_names ---
INFO [2022-01-13 11:18:51.54]: ---------------------------------------------
DEBUG [2022-01-13 11:18:51.54]: Fetching a new access token from Google...
WARN [2022-01-13 11:18:52.78]: Invalid request
```

It seems that the code only catch 404 errors code with a message `trackEmpty`.
https://github.com/fastlane/fastlane/blob/f616ea64caa2fc58dcb548449d8140634b26f0ed/supply/lib/supply/client.rb#L468

Wouldn't it be better to remove that filter on the message and catch all 404s?

**Comment by Emmitt121** [comment]
Hey did you manage it? please share the suggestion if you have that will be really helpful.

**Comment by NicolasLourenco** [comment]
It appears when the track don't exist.
You can manage it manually in order to ignore the response, something like

```
begin
  release_name = google_play_track_release_names(
    package_name: package_name,
    track: track
  )
rescue StandardError => e
  UI.important("#{e}: Current track is none")
end
```

Just be aware that this code is not clear about other errors. it catch anything

**Comment by max-ott** [comment]
I think this is currently simply not implemented. Thanks @NicolasLourenco for the work around! Feel free to open a pull request to add this!
