### ISSUE TITLE
Fastlane fails to build app through Azure Devops

### ISSUE THREAD

**Issue by chrdias** [fastlane/fastlane#19795]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I have set up a fastlane pipeline to build an iOS app. It works fine when remoting to the build agent via SSH and executing with `bundle exec fastlane ci`

When I run it through the Azure DevOps build agent (same user), however, it fails with 
```
▸ Running script '[CP] Check Pods Manifest.lock'
▸ Running script 'Run Script'
** ARCHIVE FAILED **

The following build commands failed:
	PhaseScriptExecution Run\ Script /Users/tfsservice/Library/Developer/Xcode/DerivedData/Runner-gxldmbqzkabqmlbxazaxctiiltel/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Script-9740EEB61CF901F6004384FC.sh (in target 'Runner' from project 'Runner')
(1 failure)
ERROR [2022-01-14 10:22:57.27]: Exit status: 65
```

The script is a wrapper for `flutter_tools/bin/xcode_backend.sh` which executes `dart xcode_backend.dart build`

## Azure DevOps
I run the following script:
```
echo Unlocking keychain
security unlock-keychain -p $(BuildagentPassword) /Users/tfsservice/Library/Keychains/login.keychain-db
echo Moving to project directory
cd './Source/attendance_app/App'
echo Building iOS app
../../../../../_tool/Flutter/2.8.1-stable/macos/flutter/bin/flutter build ios --release --no-codesign
echo Fastlane
cd ios
bundle exec fastlane env
bundle exec fastlane ci --verbose
```

After this fails, I can run the last line by hand in the build agent work directory via SSH and get a successful result.

##### Command executed

`bundle exec fastlane ci`

##### Complete output when running fastlane, including the stack trace and command used

<details>
This is just the last part of the output. The full log is too large to post here.
  <pre> ▸ Compiling Pods-Runner-dummy.m
▸ Compiling Pods-Runner-dummy.m
▸ Compiling Pods_Runner_vers.c
▸ Compiling Pods_Runner_vers.c
▸ Touching Pods_Runner.framework (in target 'Pods-Runner' from project 'Pods')
▸ Running script '[CP] Check Pods Manifest.lock'
▸ Running script 'Run Script'
** ARCHIVE FAILED **

The following build commands failed:
	PhaseScriptExecution Run\ Script /Users/tfsservice/Library/Developer/Xcode/DerivedData/Runner-gxldmbqzkabqmlbxazaxctiiltel/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Script-9740EEB61CF901F6004384FC.sh (in target 'Runner' from project 'Runner')
(1 failure)
ERROR [2022-01-14 10:22:57.27]: Exit status: 65

+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.200.0                 |
| export_method | app-store               |
| sdk           | iPhoneOS15.2.sdk        |
+---------------+-------------------------+

INFO [2022-01-14 10:22:57.50]: ▸     export variant\=normal
INFO [2022-01-14 10:22:57.50]: ▸     /bin/sh -c /Users/tfsservice/Library/Developer/Xcode/DerivedData/Runner-gxldmbqzkabqmlbxazaxctiiltel/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Script-9740EEB61CF901F6004384FC.sh
INFO [2022-01-14 10:22:57.50]: ▸ Failed to package /Users/tfsservice/buildagent/_work/3/s/Source/attendance_app/App.
INFO [2022-01-14 10:22:57.50]: ▸ Command PhaseScriptExecution failed with a nonzero exit code
INFO [2022-01-14 10:22:57.50]: 
ERROR [2022-01-14 10:22:57.50]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
WARN [2022-01-14 10:22:57.50]: 📋  For the complete and more detailed error log, check the full log at:
WARN [2022-01-14 10:22:57.50]: 📋  /Users/tfsservice/Library/Logs/gym/Runner-Runner.log
INFO [2022-01-14 10:22:57.50]: 
ERROR [2022-01-14 10:22:57.50]: Looks like fastlane ran into a build/archive error with your project
ERROR [2022-01-14 10:22:57.50]: It's hard to tell what's causing the error, so we wrote some guides on how
ERROR [2022-01-14 10:22:57.50]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
ERROR [2022-01-14 10:22:57.50]: Before submitting an issue on GitHub, please follow the guide above and make
ERROR [2022-01-14 10:22:57.50]: sure your project is set up correctly.
ERROR [2022-01-14 10:22:57.50]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
ERROR [2022-01-14 10:22:57.50]: the full commands printed out in yellow in the above log.
ERROR [2022-01-14 10:22:57.50]: Make sure to inspect the output above, as usually you'll find more error information there
INFO [2022-01-14 10:22:57.50]: 
WARN [2022-01-14 10:22:57.52]: Lane Context:
INFO [2022-01-14 10:22:57.52]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios ci", :CERT_FILE_PATH=>"/Users/tfsservice/buildagent/_work/3/s/Source/attendance_app/App/ios/JWGST88AH6.cer", :CERT_CERTIFICATE_ID=>"JWGST88AH6", :SIGH_PROFILE_PATH=>"/Users/tfsservice/buildagent/_work/3/s/Source/attendance_app/App/ios/AppStore_dk.schultz.attendance.mobileprovision", :SIGH_PROFILE_PATHS=>["/Users/tfsservice/buildagent/_work/3/s/Source/attendance_app/App/ios/AppStore_dk.schultz.attendance.mobileprovision"], :SIGH_UDID=>"9e1e4056-6891-4ea0-a48d-653a091e3e79", :SIGH_UUID=>"9e1e4056-6891-4ea0-a48d-653a091e3e79", :SIGH_NAME=>"dk.schultz.attendance AppStore", :SIGH_PROFILE_TYPE=>"app-store"}
ERROR [2022-01-14 10:22:57.52]: Error building the application - see the log above
INFO [2022-01-14 10:22:57.55]: Successfully generated documentation at path '/Users/tfsservice/buildagent/_work/3/s/Source/attendance_app/App/ios/fastlane/README.md' </pre>
</details>

### Environment
<details>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.6                                                           |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.32.0 (Apple Git-132)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.6 (20G165)                                            |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 13.2                                                           |
| Swift Version               | 5.5.2                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "CI build"
  lane :ci do
    get_certificates
    get_provisioning_profile
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
  end
  desc "Push a new beta build to TestFlight"
  lane :beta do
    get_certificates
    get_provisioning_profile
    increment_version_number(bump_type: "patch")
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    build_ios_app(export_method: "app-store")
    upload_to_testflight
  end
  desc "Push a new release build to App Store"
  lane :release do
    get_certificates
    get_provisioning_profile
    increment_version_number(bump_type: "minor")
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    build_ios_app(export_method: "app-store")
    upload_to_app_store
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("[redacted]") # The bundle identifier of your app
apple_id("[redacted]") # Your Apple email address

itc_team_id("[redacted]") # App Store Connect Team ID
team_id("[redacted]") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.200.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| bundler                         | 2.3.4        |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.547.0      |
| aws-sigv4                       | 1.4.0        |
| jmespath                        | 1.5.0        |
| aws-sdk-core                    | 3.125.2      |
| aws-sdk-kms                     | 1.53.0       |
| aws-sdk-s3                      | 1.111.1      |
| babosa                          | 1.0.4        |
| claide                          | 1.0.3        |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.89.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.0.0        |
| faraday-multipart               | 1.0.3        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.9.3        |
| http-cookie                     | 1.0.3        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.3.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.0        |
| httpclient                      | 2.8.3        |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-androidpublisher_v3 | 0.15.0       |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.11.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.35.0       |
| json                            | 2.1.0        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
</details>

*generated on:* **2022-01-14**
</details>
</details>

**Comment by chrdias** [comment]
This appears to be caused by a custom keychain being created (by Xcode?). Removing it allowed the build to complete.

**Comment by 4brunu** [comment]
Hi,
I'm having this same issue.
Could you please elaborate how did you fix it please?
Thanks

**Comment by chrdias** [comment]
There were two issues:
- The password wasn't passed properly in from variables. I'm unsure what exactly went wrong, but simply hardcoding the password instead of `$(BuildagentPassword)` worked. It might be a solution to set the password as an environment variable and reference it from there in the script.
- In Keychain on the Mac, I found a custom keychain with the same name as my Apple Development certificate.
  Find the exact path of this keychain with `security list-keychains` and delete it with `security delete-keychain path/to/keychain`
