### ISSUE TITLE
automatic_release flag does not work

### ISSUE THREAD

**Issue by alex-taffe** [fastlane/fastlane#19797]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When setting `automatic_release` to `false`, App Store Connect still keeps release as automatic. In the deliver summary, automatic release does appear to be properly set to false, it just doesn't actually update on Apple's side. This appears to have been reported before (https://github.com/fastlane/fastlane/issues/16135, https://github.com/fastlane/fastlane/issues/15181, https://github.com/fastlane/fastlane/issues/13777) going back at least a few years, but the bug reports are dead and didn't seem to gain any traction. Just trying to get this bumped back up into visibility.
##### Command executed

`fastlane deliver --automatic_release false --skip_metadata --skip_screenshots --force --ipa "${WORKSPACE}/product/${TRICODE}/${TRICODE}-${SCHEME}.ipa"`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 09:44:01]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
[09:44:03]: [32mSuccessfully loaded '/Volumes/External/jenkins/workspace/Release Test/apps/iOS/REDACTED/REDACTED/Configuration/fastlane/Deliverfile' 📄[0m

+-----------------+-----------------------------+
| Detected Values from './fastlane/Deliverfile' |
+-----------------+-----------------------------+
| app_identifier  | REDACTED                    |
| username        | REDACTED                    |
+-----------------+-----------------------------+

[09:44:03]: Login to App Store Connect (REDACTED)
Available session is not valid any more. Continuing with normal login.
[09:44:06]: Login successful

+--------------------------------------+----------------------------------------------------------------------------------------+
|                                                    [32mdeliver 2.190.0 Summary[0m                                                    |
+--------------------------------------+----------------------------------------------------------------------------------------+
| automatic_release                    | false                                                                                  |
| skip_metadata                        | true                                                                                   |
| skip_screenshots                     | true                                                                                   |
| force                                | true                                                                                   |
| ipa                                  | /Volumes/External/jenkins/workspace/Release Test/product/REDACTED/REDACTED-Release.ipa |
| screenshots_path                     | ./fastlane/screenshots                                                                 |
| metadata_path                        | ./fastlane/metadata                                                                    |
| app_version                          | 5.0.0                                                                                  |
| username                             | REDACTED 					                                                            |
| app_identifier                       | REDACTED 		                                                                        |
| platform                             | ios                                                                                    |
| edit_live                            | false                                                                                  |
| use_live_version                     | false                                                                                  |
| skip_binary_upload                   | false                                                                                  |
| skip_app_version_update              | false                                                                                  |
| overwrite_screenshots                | false                                                                                  |
| submit_for_review                    | false                                                                                  |
| reject_if_possible                   | false                                                                                  |
| phased_release                       | false                                                                                  |
| reset_ratings                        | false                                                                                  |
| team_id                              | REDACTED                                                                               |
| dev_portal_team_id                   | REDACTED              	                                                                |
| run_precheck_before_submit           | true                                                                                   |
| precheck_default_rule_level          | warn                                                                                   |
| ignore_language_directory_validation | false                                                                                  |
| precheck_include_in_app_purchases    | true                                                                                   |
+--------------------------------------+----------------------------------------------------------------------------------------+

[09:44:09]: Making sure the latest version on App Store Connect matches '5.0.0'...
[09:44:11]: [32mSuccessfully set the version to '5.0.0'[0m
[09:44:11]: Uploading binary to App Store Connect
[09:44:12]: Fetching password for transporter from environment variable named `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`
[09:44:23]: [32miTunes Transporter successfully finished its job[0m
[09:44:23]: Going to upload updated app to App Store Connect
[09:44:23]: [32mThis might take a few minutes. Please don't interrupt the script.[0m
[09:46:03]: [32miTunes Transporter successfully finished its job[0m
[09:46:03]: [32m--------------------------------------------------------------------[0m
[09:46:03]: [32mSuccessfully uploaded package to App Store Connect. It might take a few minutes until it's visible online.[0m
[09:46:03]: [32m--------------------------------------------------------------------[0m
[09:46:03]: [32mFinished the upload to App Store Connect[0m
[09:46:03]: Running precheck before submitting to review, if you'd like to disable this check you can set run_precheck_before_submit to false
[09:46:03]: Running precheck 👮‍♀️ 👮

+--------------------------+-----------------------------+
|              [32mSummary for precheck 2.190.0[0m              |
+--------------------------+-----------------------------+
| default_rule_level       | warn                        |
| include_in_app_purchases | true                        |
| app_identifier           | REDACTED                    |
| username                 | REDACTED 					 |
| platform                 | ios                         |
| team_id                  | REDACTED                    |
| use_live                 | false                       |
+--------------------------+-----------------------------+

[09:46:03]: Checking app for precheck rule violations
[09:46:20]: Reading in-app purchases. If you have a lot, this might take a while
[09:46:20]: You can disable IAP checking by setting the `include_in_app_purchases` flag to `false`
[09:46:20]: Done reading in-app purchases
[09:46:21]: ✅  Passed: No negative  sentiment
[09:46:21]: ✅  Passed: No placeholder text
[09:46:21]: ✅  Passed: No mentioning  competitors
[09:46:21]: ✅  Passed: No future functionality promises
[09:46:21]: ✅  Passed: No words indicating test content
[09:46:21]: ✅  Passed: No curse words
[09:46:21]: ✅  Passed: No words indicating your IAP is free
[09:46:21]: [33m😵  Failed: Incorrect, or missing copyright date-> using a copyright date that is any different from this current year, or missing a date[0m
[09:46:24]: ✅  Passed: No broken urls
+-----------+----------------+
|     [33mPotential problems[0m     |
+-----------+----------------+
| Field     | Failure reason |
+-----------+----------------+
| copyright | [33mmissing: 2022[0m  |
+-----------+----------------+
[09:46:24]: [33m[33mprecheck 👮‍♀️ 👮  found one or more potential metadata problems, but this won't prevent fastlane from completing 👍[0m </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                  |
| --------------------------- | ------------------------------------------------------ |
| OS                          | 11.4                                                   |
| Ruby                        | 2.6.6                                                  |
| Bundler?                    | false                                                  |
| Git                         | git version 2.29.2                                     |
| Installation Source         | ~/.rbenv/versions/2.6.6/bin/fastlane                   |
| Host                        | macOS 11.4 (20F71)                                     |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.6/lib                            |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                            |
| Is contained                | false                                                  |
| Is homebrew                 | false                                                  |
| Is installed via Fabric.app | false                                                  |
| Xcode Path                  | /Applications/Xcode-12.5/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.5                                                   |
| Swift Version               | 5.4                                                    |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.206.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.5.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.3        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.76.0       |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.3        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.0.0        |
| fastimage                       | 2.2.0        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.10.1       |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.0        |
| dotenv                          | 2.7.6        |
| simctl                          | 1.6.8        |
| jwt                             | 2.2.2        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| declarative-option              | 0.1.0        |
| representable                   | 3.0.4        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.0.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| signet                          | 0.14.0       |
| googleauth                      | 0.16.2       |
| httpclient                      | 2.8.3        |
| webrick                         | 1.4.2        |
| google-apis-core                | 0.4.1        |
| google-apis-playcustomapp_v1    | 0.5.0        |
| google-apis-androidpublisher_v3 | 0.8.0        |
| google-cloud-env                | 1.3.3        |
| google-cloud-errors             | 1.0.1        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.6.0        |
| google-apis-storage_v1          | 0.6.0        |
| rake                            | 13.0.1       |
| digest-crc                      | 0.6.1        |
| google-cloud-storage            | 1.34.1       |
| emoji_regex                     | 3.0.0        |
| rexml                           | 3.2.5        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.0.3        |
| CFPropertyList                  | 3.0.3        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.21.0       |
| ruby2_keywords                  | 0.0.2        |
| faraday                         | 1.1.0        |
| json                            | 2.3.1        |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.0        |
| bundler                         | 2.2.24       |
| aws-eventstream                 | 1.1.0        |
| aws-sigv4                       | 1.2.2        |
| aws-partitions                  | 1.388.0      |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.109.1      |
| aws-sdk-kms                     | 1.39.0       |
| aws-sdk-s3                      | 1.83.1       |
| forwardable                     | 1.2.0        |
| logger                          | 1.3.0        |
| stringio                        | 0.0.2        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| date                            | 2.0.0        |
| io-console                      | 0.4.7        |
| fileutils                       | 1.1.0        |
| etc                             | 1.0.1        |
| zlib                            | 1.0.0        |
| psych                           | 3.1.0        |
| mutex_m                         | 0.1.0        |
</details>

*generated on:* **2022-01-14**
</details>

**Comment by PeterStaev** [comment]
I'm having the same problem. The option worked in the past but something changed either in fastlane or in App Store Connect API and now the option has no effect. Using fastlane with Azure DevOps release task.

**Comment by Patsy69** [comment]
Because we need to have full control over the release time. Sometimes, in a company environment, after all the testing is done, we want to release the app, and start monitoring usage on that day. On Google Play, this is not a problem. We can expect an app we submit for release to go live shortly after the submission.

**Comment by alex-taffe** [comment]
Bumping to prevent auto close

**Comment by alex-taffe** [comment]
Bumping to prevent auto close

**Comment by alex-taffe** [comment]
Comment to prevent close

**Comment by timothycosta** [comment]
I regularly have the opposite problem. I choose to automatically release, but it has no effect about 90% of the time. Sometimes I get lucky though.

![Screen Shot 2022-06-24 at 9 39 42 AM](https://user-images.githubusercontent.com/948806/175437885-3af3ec1b-310c-40ee-a374-d9d11af0e18b.png)


```
[⠙] 🚀 Ignoring ffi-1.14.2 because its extensions are not built. Try: gem pristine ffi --version 1.14.2
[✔] 🚀
[09:36:30]: Loading from './fastlane/.env.main'
[09:36:30]: fastlane detected a Gemfile in the current directory
[09:36:30]: However, it seems like you didn't use `bundle exec`
[09:36:30]: To launch fastlane faster, please use
[09:36:30]:
[09:36:30]: $ bundle exec fastlane upload submit:1 release:1
[09:36:30]:
[09:36:30]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
Fastfile:156: warning: key :app_version is duplicated and overwritten on line 157
[09:36:31]: ----------------------------------------
[09:36:31]: --- Step: Verifying fastlane version ---
[09:36:31]: ----------------------------------------
[09:36:31]: Your fastlane version 2.206.2 matches the minimum requirement of 2.20.0  ✅
[09:36:31]: ------------------------------
[09:36:31]: --- Step: default_platform ---
[09:36:31]: ------------------------------
[09:36:31]: Driving the lane 'ios upload' 🚀
[09:36:31]: ---------------------
[09:36:31]: --- Step: deliver ---
[09:36:31]: ---------------------
[09:36:31]: Successfully loaded '/Users/timothycosta/Desktop/lingq/fastlane/Deliverfile' 📄

+--------------------------------------+----------------------------------------------------------------------+
|                                Detected Values from './fastlane/Deliverfile'                                |
+--------------------------------------+----------------------------------------------------------------------+
| metadata_path                        | ./fastlane/LingQ/metadata/                                           |
| screenshots_path                     | ./fastlane/LingQ/screenshots/                                        |
| app_icon                             | ./fastlane/LingQ/app_icon.png                                        |
| primary_category                     | EDUCATION                                                            |
| secondary_category                   | TRAVEL                                                               |
| run_precheck_before_submit           | false                                                                |
| precheck_include_in_app_purchases    | false                                                                |
| force                                | true                                                                 |
| overwrite_screenshots                | true                                                                 |
| app_rating_config_path               | fastlane/app_rating_config.json                                      |
| ignore_language_directory_validation | true                                                                 |
| submission_information               | {:add_id_info_tracks_install=>true,                                  |
|                                      | :add_id_info_tracks_action=>true, :add_id_info_uses_idfa=>true,      |
|                                      | :add_id_info_limits_tracking=>true,                                  |
|                                      | :export_compliance_uses_encryption=>false,                           |
|                                      | :export_compliance_encryption_updated=>false,                        |
|                                      | :content_rights_contains_third_party_content=>false,                 |
|                                      | :content_rights_has_rights=>true}                                    |
| app_review_information               | {:first_name=>",                        |
|                                      | :phone_number=>"", :email_address=>"",      |
|                                      | :demo_user=>"", :demo_password=>"", :notes=>"\nTo      |
|                                      | test in-app purchases create a new account. You will be prompted     |
|                                      | after signup to purchase.  \nOr, tap the crown in the top left       |
|                                      | corner of the screen after logging in.\n\nSubscriptions can be       |
|                                      | viewed via More -> Settings -> App -> Subscription Info.\n\n\nThe    |
|                                      | referral id on the signup screen allows users to join study groups.  |
|                                      | Study groups\nallow group leaders to share lessons and track users'  |
|                                      | progress.\n\nTo test a referral id, select English as your learning  |
|                                      | language during signup.\nThen, on the registration screen, tap       |
|                                      | 'Referral ID' and enter APPTEST2020 in the added field.\nAfter       |
|                                      | login has completed you will have a new section 'iOS Test' at the    |
|                                      | top of the Library tab.\n\n"}                                        |
| release_notes                        | {"default"=>"5.0.23\n- Fix an audio related crash\n- Fix a crash     |
|                                      | when TTS is activated\n- LingQs of the day settings fix\n\n",        |
|                                      | "it"=>"5.0.23\n- Fix an audio related crash\n- Fix a crash when TTS  |
|                                      | is activated\n- LingQs of the day settings fix\n\n"}                 |
+--------------------------------------+----------------------------------------------------------------------+

[09:36:31]: Login to App Store Connect (timothycosta@lingq.com)
[09:36:32]: Login successful
^[
+--------------------------------------------------------------------+----------------------------------------------------------------------+
|                                                          deliver 2.206.2 Summary                                                          |
+--------------------------------------------------------------------+----------------------------------------------------------------------+
| submit_for_review                                                  | true                                                                 |
| automatic_release                                                  | true                                                                 |
| phased_release                                                     | false                                                                |
| skip_metadata                                                      | true                                                                 |
| skip_screenshots                                                   | true                                                                 |
| edit_live                                                          | false                                                                |
| username                                                           | @lingq.com                                               |
| app_identifier                                                     | com.lingq.iLingQ                                                     |
| platform                                                           | ios                                                                  |
| use_live_version                                                   | false                                                                |
| metadata_path                                                      | ./fastlane/LingQ/metadata/                                           |
| screenshots_path                                                   | ./fastlane/LingQ/screenshots/                                        |
| skip_binary_upload                                                 | false                                                                |
| skip_app_version_update                                            | false                                                                |
| force                                                              | true                                                                 |
| overwrite_screenshots                                              | true                                                                 |
| sync_screenshots                                                   | false                                                                |
| verify_only                                                        | false                                                                |
| reject_if_possible                                                 | false                                                                |
| reset_ratings                                                      | false                                                                |
| app_rating_config_path                                             | fastlane/app_rating_config.json                                      |
| submission_information.add_id_info_tracks_install                  | true                                                                 |
| submission_information.add_id_info_tracks_action                   | true                                                                 |
| submission_information.add_id_info_uses_idfa                       | true                                                                 |
| submission_information.add_id_info_limits_tracking                 | true                                                                 |
| submission_information.export_compliance_uses_encryption           | false                                                                |
| submission_information.export_compliance_encryption_updated        | false                                                                |
| submission_information.content_rights_contains_third_party_content | false                                                                |
| submission_information.content_rights_has_rights                   | true                                                                 |
| dev_portal_team_id                                                 |                                                           |
| run_precheck_before_submit                                         | false                                                                |
| precheck_default_rule_level                                        | warn                                                                 |
| app_icon                                                           | ./fastlane/LingQ/app_icon.png                                        |
| primary_category                                                   | EDUCATION                                                            |
| secondary_category                                                 | TRAVEL                                                               |
| app_review_information.first_name                                  |                                                                  |
| app_review_information.last_name                                   |                                                              |
| app_review_information.phone_number                                |                                                          |
| app_review_information.email_address                               |                                                        |
| app_review_information.demo_user                                   |                                                              |
| app_review_information.demo_password                               | ********                                                             |
| app_review_information.notes                                       |  To test in-app purchases create a new account. You will be          |
|                                                                    | prompted after signup to purchase.   Or, tap the crown in the top    |
|                                                                    | left corner of the screen after logging in.  Subscriptions can be    |
|                                                                    | viewed via More -> Settings -> App -> Subscription Info.   The       |
|                                                                    | referral id on the signup screen allows users to join study groups.  |
|                                                                    | Study groups allow group leaders to share lessons and track users'   |
|                                                                    | progress.  To test a referral id, select English as your learning    |
|                                                                    | language during signup. Then, on the registration screen, tap        |
|                                                                    | 'Referral ID' and enter APPTEST2020 in the added field. After login  |
|                                                                    | has completed you will have a new section 'iOS Test' at the top of   |
|                                                                    | the Library tab.                                                     |
| release_notes.default                                              | 5.0.23 - Fix an audio related crash - Fix a crash when TTS is        |
|                                                                    | activated - LingQs of the day settings fix                           |
| release_notes.it                                                   | 5.0.23 - Fix an audio related crash - Fix a crash when TTS is        |
|                                                                    | activated - LingQs of the day settings fix                           |
| ignore_language_directory_validation                               | true                                                                 |
| precheck_include_in_app_purchases                                  | false                                                                |
+--------------------------------------------------------------------+----------------------------------------------------------------------+

[09:36:47]: Detected languages: ["default", "it", "zh-Hans", "zh-Hant", "fr-FR", "de-DE", "es-ES", "ja", "el", "es-MX", "en-AU", "ru", "en-GB", "nl-NL", "fr-CA", "en-CA", "pt-PT", "pt-BR", "ko", "en-US", "tr"]
[09:36:47]: Finished the upload to App Store Connect
[09:36:50]: Selecting the latest build...
[09:36:50]: Waiting for processing on... app_id:, app_version: , build_version: , platform: IOS
[09:36:50]: Searching for the latest build
[09:37:34]: Successfully finished processing the build 5.0.23 - 0 for IOS
[09:37:34]: Selecting build 5.0.23 (0)...
[09:37:35]: Successfully selected build
[09:37:36]: Successfully updated IDFA declarations on App Store Connect
[09:37:38]: Successfully updated contents rights declaration on App Store Connect
[09:38:11]: Successfully submitted the app for review!
[09:38:11]: ---------------------------------------------
[09:38:11]: --- Step: Switch to ios upload_dsyms lane ---
[09:38:11]: ---------------------------------------------
[09:38:11]: Cruising over to lane 'ios upload_dsyms' 🚖
[09:38:11]: --------------------------------
[09:38:11]: --- Step: get_version_number ---
[09:38:11]: --------------------------------
[09:38:12]: ------------------------------
[09:38:12]: --- Step: get_build_number ---
[09:38:12]: ------------------------------
[09:38:12]: $ cd /Users/timothycosta/Desktop/lingq && agvtool what-version -terse
[09:38:12]: ▸ "$(CURRENT_PROJECT_VERSION)"
[09:38:12]: ▸ 1
[09:38:12]: Downloading DSYMS for 5.0.23 (1)
[09:38:12]: ----------------------------
[09:38:12]: --- Step: download_dsyms ---
[09:38:12]: ----------------------------
[09:38:12]: Login to App Store Connect (timothycosta@lingq.com)
[09:38:15]: Login successful
[09:38:31]: Looking for dSYM files for 'com.lingq.iLingQ' on platform IOS v5.0.23 (1)
[09:38:32]: Uploading DSYMS
[09:38:32]: -------------------------------------------
[09:38:32]: --- Step: upload_symbols_to_crashlytics ---
[09:38:32]: -------------------------------------------
[09:38:32]: Uploading '/Users/timothycosta/Desktop/lingq/Carthage/Build/AFNetworking.xcframework/watchos-arm64_i386_x86_64-simulator/dSYMs/AFNetworking.framework.dSYM'...
[09:38:36]: Successfully uploaded dSYM files to Crashlytics 💯
[09:38:36]: -----------------------------------
[09:38:36]: --- Step: clean_build_artifacts ---
[09:38:36]: -----------------------------------
[09:38:36]: Cleaned up build artifacts 🐙
[09:38:36]: Cruising back to lane 'ios upload' 🚘
[09:38:36]: upload finished

+------+---------------------------------+-------------+
|                   fastlane summary                   |
+------+---------------------------------+-------------+
| Step | Action                          | Time (in s) |
+------+---------------------------------+-------------+
| 1    | Verifying fastlane version      | 0           |
| 2    | default_platform                | 0           |
| 3    | deliver                         | 100         |
| 4    | Switch to ios upload_dsyms lane | 0           |
| 5    | get_version_number              | 0           |
| 6    | get_build_number                | 0           |
| 7    | download_dsyms                  | 19          |
| 8    | upload_symbols_to_crashlytics   | 3           |
| 9    | clean_build_artifacts           | 0           |
+------+---------------------------------+-------------+

[09:38:36]: fastlane.tools finished successfully 🎉
```

**Comment by alex-taffe** [comment]
Do not auto close, still a problem

**Comment by alex-taffe** [comment]
Keep alive

**Comment by alex-taffe** [comment]
Still an issue, do not close

**Comment by alex-taffe** [comment]
@joshdholtz any chance you can take a look at this?

**Comment by Riddick1987** [comment]
Same thing happens to me.

Calling this (check the last parameter for the `automatic_release` value):
```
deliver(submit_for_review: true,app_version: version_number, build_number: testflight_build_nr,
          skip_binary_upload: true,skip_metadata: true,skip_screenshots:true,
          submission_information: { add_id_info_uses_idfa: false },username: ENV['DLV_ITUNESCONNECT_USERNAME'],
        app_identifier: ENV['DLV_BUNDLE_ID'], force: true, run_precheck_before_submit: false, automatic_release: true)
```
Seeing this in the logs:
<img width="786" alt="Screenshot 2023-04-28 at 17 26 37" src="https://user-images.githubusercontent.com/3007635/235190078-2e1855b2-9bb8-41e6-b450-db696c99b554.png">

But having this in the App Store Connect page:
<img width="1402" alt="Screenshot 2023-04-28 at 17 30 40" src="https://user-images.githubusercontent.com/3007635/235190544-feb6c87f-dd9a-4bef-a23f-01ca1a70b891.png">

**Comment by alex-taffe** [comment]
So actually, we figured out it was the `--skip-metadata` argument causing this to fail. It is a piece of metadata, so it makes sense, but a warning may also make sense
