### ISSUE TITLE
Mismatch between `get_app_store_version_localizations` and `appStoreVersionLocalizations`

### ISSUE THREAD

**Issue by phjs** [fastlane/fastlane#19790]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

We noticed a mismatch in the amount of returned languages between `get_app_store_version_localizations` and `appStoreVersionLocalizations`. 
Our apps are available in more than 10 languages, but when requesting the languages with the latter approach (as stated in the [documentation](https://github.com/fastlane/fastlane/blob/master/spaceship/docs/AppStoreConnect.md#appversions)) we receive only a (random) subset of 10 of the available languages. No matter which app we test, `appStoreVersionLocalizations` always returns precisely 10.

We would have expected that both methods return the same amount of languages.

##### Command executed

```
lane :testLocalizations do
        fastlane_require 'spaceship'

        # Login with json api key
        token = Spaceship::ConnectAPI::Token.from_json_file(APIKeyPath)
        Spaceship::ConnectAPI.token = token

        # get current app
        app = Spaceship::ConnectAPI::App.find(ENV["APP_ID"])
        app_version = app.get_edit_app_store_version(platform:Spaceship::ConnectAPI::Platform::IOS, includes: "appStoreVersionLocalizations")
        if app_version == nil
            app_version = app.get_live_app_store_version(platform:Spaceship::ConnectAPI::Platform::IOS, includes: "appStoreVersionLocalizations")
        end

        localizations = app_version.get_app_store_version_localizations
        locs = app_version.appStoreVersionLocalizations # same result with 'app_store_version_localizations'

        if localizations.count() == locs.count()
            UI.success("Both returned #{localizations.count()} languages")
        else
            UI.error("Unequal lang count: #{localizations.count()} vs #{locs.count()}")
        end
    end
```

##### Complete output when running Fastlane, including the stack trace and command used

<details>
  <pre> 
➜  fastlane/ ✗ fastlane testLocalizations --env MyApp

[✔] 🚀 
[14:36:39]: Loading from './.env.MyApp'
[14:36:40]: ---------------------------
[14:36:40]: --- Step: shell command ---
[14:36:40]: ---------------------------
[14:36:40]: ------------------------------
[14:36:40]: --- Step: default_platform ---
[14:36:40]: ------------------------------
[14:36:40]: Driving the lane 'ios testLocalizations' 🚀
[14:36:47]: Unequal lang count: 17 vs 10

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | shell command    | 0           |
| 2    | default_platform | 0           |
+------+------------------+-------------+

[14:36:47]: fastlane.tools finished successfully 🎉
</pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 12.1                                                       |
| Ruby                        | 3.0.3                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.32.0 (Apple Git-132)                         |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.200.0/libexec/bin/fastlane |
| Host                        | macOS 12.1 (21C52)                                         |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.0.3/lib                        |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021                                |
| Is contained                | false                                                      |
| Is homebrew                 | true                                                       |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
| Xcode Version               | 13.2.1                                                     |
| Swift Version               | 5.5.2                                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
require "json"

# Fastlane

default_platform(:ios)

platform :ios do
    lane :testLocalizations do
        fastlane_require 'spaceship'

        # Login with json api key
        token = Spaceship::ConnectAPI::Token.from_json_file(APIKeyPath)
        Spaceship::ConnectAPI.token = token

        # get current app
        app = Spaceship::ConnectAPI::App.find(ENV["APP_ID"])
        app_version = app.get_edit_app_store_version(platform:Spaceship::ConnectAPI::Platform::IOS, includes: "appStoreVersionLocalizations")
        if app_version == nil
            app_version = app.get_live_app_store_version(platform:Spaceship::ConnectAPI::Platform::IOS, includes: "appStoreVersionLocalizations")
        end

        localizations = app_version.get_app_store_version_localizations
        locs = app_version.app_store_version_localizations

        if localizations.count() == locs.count()
            UI.success("Both returned #{localizations.count()} languages")
        else
            UI.error("Unequal lang count: #{localizations.count()} vs #{locs.count()}")
        end
    end
end




```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.200.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.90.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.3        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.9.3        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.5.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.32       |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-androidpublisher_v3 | 0.15.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.11.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.36.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.5.0        |
| aws-partitions                  | 1.547.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-sdk-core                    | 3.125.3      |
| aws-sdk-kms                     | 1.53.0       |
| aws-sdk-s3                      | 1.111.1      |
| set                             | 1.0.1        |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.1        |
| date                            | 3.1.3        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.0        |
| uri                             | 0.10.1       |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.2.1        |
| digest                          | 3.0.0        |
| io-nonblock                     | 0.1.0        |
| io-wait                         | 0.2.0        |
| zlib                            | 2.0.0        |
| resolv                          | 0.2.1        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.1        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.7        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| net-http                        | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.2.1        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.2        |
</details>

*generated on:* **2022-01-13**
</details> </pre>
</details>

**Comment by max-ott** [comment]
Do you have 2 versions of the app currently? (live and edit?) Might be related! I've not seen any inconsistencies here.

**Comment by phjs** [comment]
At that time, we had two versions, but both had the same amount of languages (we hadn't added a language for one year). So today, I tested it again with only a live version and with Fastlane 2.205.1. It is still the same: `appStoreVersionLocalizations` returns only "random" ten of our seventeen supported languages, whereas `get_app_store_version_localizations` returns all seventeen languages.
@max-ott did you test it with an app with more than ten languages?
