### ISSUE TITLE
Fastlane cannot load certificates from keychain (Big Sur and Monterey)

### ISSUE THREAD

**Issue by Kukurijek** [fastlane/fastlane#19815]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

We have been using fastlane with mac minis  for a long time in the cloud (CI) and they worked all the time until we updated to Big Sur / Monterey.

Match works and saves certificates in the keychain, but gym, scan and create_xcframework Action cannot load them from the keychain.

Error: `error: No certificate for team" xxx "matching" Apple Development xxx "found: Select a different signing certificate for CODE_SIGNING_IDENTITY, a team that matches your selected certificate, or switch to automatic provisioning,

We use a generic keychain, but I tried using the default keychain and it did not work.

So using the `unlock_keychain` and  action before the gym and scan does not help.

Since nothing has changed in the script, the problem may be in fastlane or in macOS. Before creating the generic keychain (`create_keychain`), the script deletes the old one with the same name (`delete_keychain`).

I also tried to use the `setup_ci` action and it did not help either.

I just cannot figure out what the problem is. As I said, man minis with older OS (Catalina) work without a problem with the same setup.

This issue may be related to: https://github.com/fastlane/fastlane/issues/15185

Also, manually importing Apple WWDR certificates into System Keychain does not help. The same is the case with the login keychain.

Many other things that I tried did not help:
- test with different values for keychain timeout
- test with different versions of Xcode
- test with different versions of Ruby
- test with different parameters for keychain (like add keychain to search list)
- test with deleting all items from keychain
- test with new certificates, profiles and keys
...

The only thing we have not tried is to switch to `automatic signing`, but I do not believe it would help.

Is it possible that unlocking keychain from non GUI session (i.e. ssh) does not work anymore (on Big Sur and Monterey)?

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by Emmitt121** [comment]
When you request a certificate, your Mac creates a public/private pair that will be used to download the certificate from Apple. This is why you can't download the resulting certificate from another Mac that doesn't have the original pair.

**Comment by AdalbertoMadden** [comment]
Thank you so much to sharing this post.

**Comment by Kukurijek** [comment]
Since the problem is solved and has nothing to do with fastlane, I will close the issue.

Hint: always double check the full name and account name of your generic user.
