### ISSUE TITLE
`ensure_git_status_clean` documentation confusing wording for `ignored` parameter

### ISSUE THREAD

**Issue by simondelphia** [fastlane/fastlane#19818]
https://docs.fastlane.tools/actions/ensure_git_status_clean/

For the parameter `ignored` the description says "The flag whether to ignore file the git status if the repo is dirty"

I'm not clear on what that means. Looks like a typo.

Thank you

**Comment by lucgrabowski** [comment]
It looks like you're right, it's not a bool flag, it's a string parameter. `git status` docs should be helpful to understand how to use it
https://github.com/fastlane/fastlane/blob/e215bdc787aa9e14fcf24b1fabc168a3182f4f89/fastlane/lib/fastlane/actions/ensure_git_status_clean.rb#L8-L15

**Comment by Kivettt** [comment]
willful ignorance uncountable idiomatic, law A decision in bad faith to avoid becoming informed about something so as to avoid having to make undesirable decisions that such information might prompt. Synonyms: vincible ignorance, willful blindness.

**Comment by tcf909** [comment]
Actually, even worse is the actual command being run is wrong.

It needs to be:

```
git status --porcelain --ignored=#{ignored_file}
```

if you run it without the equals sign it basically always comes back as empty because it is using "no" as the <pathspec>... for the git-status command.

**Comment by simondelphia** [comment]
Still an issue

**Comment by simondelphia** [comment]
Still an issue

**Comment by simondelphia** [comment]
still an issue

**Comment by Ryabchikus** [comment]
I'm here too
I can't exclude some files from git check

**Comment by ObjectiveCesar** [comment]
And still an issue.

```
[13:29:49]: -------------------------------------
[13:29:49]: --- Step: ensure_git_status_clean ---
[13:29:49]: -------------------------------------
[13:29:49]: $ git status --porcelain --ignored Gemfile.lock
[13:29:49]: ▸ M Gemfile.lock [!] Git repository is dirty! Please ensure the repo is in a clean state by committing/stashing/discarding all changes first.
```

**Comment by revolter** [comment]
I can rename that PR and also fix the issue. Would you be willing to test it? As I'm not currently using that action.

**Comment by ObjectiveCesar** [comment]
> I can rename that PR and also fix the issue. Would you be willing to test it? As I'm not currently using that action.

I could try at least. Never built fastlane from source so far. :)
