### ISSUE TITLE
Multiple entitlement option for Fastlane resign

### ISSUE THREAD

**Issue by bobrenji** [fastlane/fastlane#19821]
### Discussed in https://github.com/fastlane/fastlane/discussions/19817

<div type='discussions-op-text'>

<sup>Originally posted by **bobrenji** January 19, 2022</sup>
I am building an app with extensions. I have enabled capabilities like keychain sharing, associated-domains etc.

So I have to use resign action with custom entitlements. Problem for me, When I resign my app and try to upload App Store. It fails with error. I can see both my app and extension target used same app-id entitlement. Is there any way I can provide multiple entitlements. So I can handle it properly.

So any idea?</div>

**Comment by choli** [comment]
Hi, did you solve this? Currently checking for a resign with extensions, don't know exactly how to do that. Thanks

**Comment by choli** [comment]
still open :(

**Comment by Ocello1** [comment]
Entitlement versioning lets you create multiple versions of an entitlement process, even if it's assigned to active entitlements and support records. You can use multiple versions of an entitlement process at the same time in your Salesforce org.

**Comment by choli** [comment]
Anyone?
