### ISSUE TITLE
[pilot] Unable to add users from csv when 'distribute_only' is set to true

### ISSUE THREAD

**Issue by RobertoPelonara** [fastlane/fastlane#19823]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm trying to distribute an app using pilot in a lane, and I have the need to separate the build and the distribution phase into two lane. So when I build I only upload the ipa to AppStoreConnect and after with a second lane i distribute the build to certain groups and I need to add or delete members of the groups based on the csv I provide, but it is completely ignored. 

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [19:12:09]: ------------------------------
[19:12:09]: --- Step: default_platform ---
[19:12:09]: ------------------------------
[19:12:09]: Driving the lane 'ios distributeAppTestFlight' 🚀
[19:12:09]: ---------------------------------------
[19:12:09]: --- Step: app_store_connect_api_key ---
[19:12:09]: ---------------------------------------
[19:12:09]: -------------------
[19:12:09]: --- Step: pilot ---
[19:12:09]: -------------------
[19:12:09]: Creating authorization token for App Store Connect API
[19:12:11]: Waiting for processing on... app_id: 1600xxxxxx, app_version: , build_version: , platform: IOS
[19:12:11]: Searching for the latest build
[19:12:13]: Successfully finished processing the build 1.0.2 - 2 for IOS
[19:12:13]: Uploaded app  - , but received build 1.0.2 - 2.
[19:12:13]: No build specified - fetching latest build
[19:12:20]: Successfully set the beta_app_feedback_email and/or beta_app_description
[19:12:22]: Successfully set the changelog for build
[19:12:23]: Distributing new build to testers: 1.0.2 - 2
[19:12:27]: Successfully distributed build to External testers 🚀

+------+---------------------------+-------------+
|                fastlane summary                |
+------+---------------------------+-------------+
| Step | Action                    | Time (in s) |
+------+---------------------------+-------------+
| 1    | default_platform          | 0           |
| 2    | app_store_connect_api_key | 0           |
| 3    | pilot                     | 18          |
+------+---------------------------+-------------+

[19:12:27]: fastlane.tools finished successfully 🎉
</pre>
</details>

### Environment

<details>
  <pre> <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 11.4                                                    |
| Ruby                        | 3.0.3                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.30.1 (Apple Git-130)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.201.0/libexec/bin/fastlane |
| Host                        | macOS 11.4 (20F71)                                      |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/3.0.3/lib                        |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021                             |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 13.1                                                    |
| Swift Version               | 5.5.1                                                   |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

ENV["MATCH_PASSWORD"] = "test"


platform :ios do

  lane :distributeAppTestFlight do
    app_store_connect_api_key(
      key_id: "<KEY_ID>",
      issuer_id: "<ISSUER_ID>",
      key_filepath: ENV["P8_path"],
      )
    pilot(
      app_identifier: ENV["app_id"],
      beta_app_feedback_email: "<MAIL>",
      beta_app_description: "This is a beta version of our Custom Apps",
      demo_account_required: false,
      notify_external_testers: true,
      distribute_only: true ,
      changelog: "First release on beta channel",
      distribute_external: true,
      testers_file_path: "<TRIED ABSOLUTE AND RELATIVE PATH>",
      groups: ["Gruppo A"],
      app_platform: "ios",
      verbose: true,
    )
  end

end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.201.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.90.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.3        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.9.3        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.5.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.32       |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.2        |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-androidpublisher_v3 | 0.15.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.11.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.36.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.5.0        |
| aws-partitions                  | 1.549.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-sdk-core                    | 3.125.5      |
| aws-sdk-kms                     | 1.53.0       |
| aws-sdk-s3                      | 1.111.2      |
| set                             | 1.0.1        |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.1        |
| date                            | 3.1.3        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.0        |
| uri                             | 0.10.1       |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.2.1        |
| digest                          | 3.0.0        |
| io-nonblock                     | 0.1.0        |
| io-wait                         | 0.2.0        |
| zlib                            | 2.0.0        |
| resolv                          | 0.2.1        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.1        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.7        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| net-http                        | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.2.1        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.2        |
</details>

*generated on:* **2022-01-21**
</details></pre>
</details>

**Comment by lucgrabowski** [comment]
`testers_file_path` is used only when you run `fastlane pilot import` command in terminal to import testers from CSV file and calling `pilot` the way you do in `distributeAppTestFlight` lane won't trigger importing testers. 

You could import testers before running `pilot` to distribute build with:
`sh("fastlane pilot import --api_key_path <PATH> --testers_file_path <CSV file path>")`

To remove a tester, you could read about `fastlane pilot remove`.

**Comment by RobertoPelonara** [comment]
So it's not possible to handle the testers and the groups in a lane?

**Comment by lucgrabowski** [comment]
It is, you can execute many commands in lanes:
```ruby
  lane :example do
    app_store_connect_api_key(...)
    sh("fastlane pilot import --api_key_path <PATH> --testers_file_path <CSV file path>")
    ...
    pilot(...)
  end
```
Take a look at managing beta testers in docs: https://docs.fastlane.tools/actions/pilot/ to see how to import/export, add/remove testers.

**Comment by RobertoPelonara** [comment]
Yes I know this, but for example I cannot take advantage of the fact that pilot share the key defined in app_store_connect_api_key action. So if it's this the case I can close the issue
