### ISSUE TITLE
Trainer issue on 2.201.0 : Could not find option 'output_filename' in the list of available options: path, extension, output_directory, fail_build, xcpretty_naming, silent

### ISSUE THREAD

**Issue by pradyhk** [fastlane/fastlane#19832]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Could not find option 'output_filename' in the list of available options: path, extension, output_directory, fail_build, xcpretty_naming, silent

##### Command executed

lane :lane1 do
  trainer(
    path: #{path to xcresult},
    fail_build: false,
    output_directory: #{path to outputdirectory},
    xcpretty_naming: true
  )  
end

##### Complete output when running fastlane, including the stack trace and command used

[18:40:35]: --- Step: trainer ---
[18:40:35]: ---------------------

+------------------+------------------------------------------------------------+
|                          Summary for trainer 2.201.0                          |
+------------------+------------------------------------------------------------+
| path             | /Users/ios/target/unit-tests  |
| fail_build       | false                                                      |
| output_directory | /Users/ios/derivedData/target/unit-tests/ |
| xcpretty_naming  | true                                                       |
| extension        | .xml                                                       |
| silent           | false                                                      |
+------------------+------------------------------------------------------------+

+------------------+-------+
|       Lane Context       |
+------------------+-------+
| DEFAULT_PLATFORM | ios   |
| PLATFORM_NAME    |       |
| LANE_NAME        | lane1 |
+------------------+-------+
[18:40:35]: Could not find option 'output_filename' in the list of available options: path, extension, output_directory, fail_build, xcpretty_naming, silent

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by joshdholtz** [comment]
@pradyhk This is fixed in #19828 and will be released in about an hour or two! Going to close this but really appreciate the filing of the issue 🙌
