### ISSUE TITLE
trainer return value change

### ISSUE THREAD

**Issue by vincentisambart** [fastlane/fastlane#19839]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

The release notes for fastlane 2.201 say to remove `fastlane-plugin-trainer` and use fastlane's new internal version of `trainer` instead. Reading that it looked like to me the behavior of the internal version should be the same as the plugin version. However, it seems the return value format changed.

- Return value of the plugin version:
```
{"path/to/file1.xml" => true, ...}
```
- Return value of the new fastlane internal version:
```
{"path/to/file1.xcresult" => {:to_path => "path/to/file1.xml", :successful => true, number_of_tests: ..}, ...}
```

I'm totally fine with updating our code to the new return value format, especially as it gives more information, but it seems a few things need fixing:

- The release notes should mention that `trainer`'s return value format changed.
- Realizing the format changed I thought about looking at the official docs, but I could find the new `trainer` action at https://docs.fastlane.tools/actions/
- And even looking directly at the code, the documentation for the return value still describes the old format: https://github.com/fastlane/fastlane/blob/bdf2336949388cfcd9b13a718bca9c12bc6ab7df/fastlane/lib/fastlane/actions/trainer.rb#L32

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by joshdholtz** [comment]
@vincentisambart Thanks for making this issue! I'll make sure that I get the trainer docs add later this week 💪 I had to take a little detour and prepare for some upcoming App Store Connect changes for tomorrow first 🤷‍♂️  But I'll make sure this gets added to the docs as soon as I can!

**Comment by Chesterqa** [comment]
When passing data to the built-in training loops of a model, you should either use NumPy arrays (if your data is small and fits in memory) or tf.data Dataset objects. In the next few paragraphs, we'll use the MNIST dataset as NumPy arrays, in order to demonstrate how to use optimizers, losses, and metrics

**Comment by dcacenabes** [comment]
Hi @joshdholtz !
Unfortunately this is affecting more than just the documentation. The change in the return type is affecting the trainer action. The fail_build parameter is not working, so Fastlane is finishing with exit code 0 when running trainer, which is not correct.
I have opened a PR addressing this issue (also included some tests)
https://github.com/fastlane/fastlane/pull/19882
Have a great day!
