### ISSUE TITLE
Collision between `trainer` inside Fastlane and `trainer` gem

### ISSUE THREAD

**Issue by igor-makarov** [fastlane/fastlane#19834]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: [e.g. `2.201.1`]
- Last working version: [e.g. `2.191.0`]

### Regression Description

When `trainer` gem is installed, e.g. when using `fastlane-plugin-test_center` plugin, Fastlane will `require` the gem and not the internally packaged library. This causes the run to fail with:
```
bundler: failed to load command: fastlane (/Users/Igor/.rbenv/versions/2.7.2/bin/fastlane)
TypeError: [!] no implicit conversion of nil into String
  /Users/Igor/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/trainer-0.9.1/lib/trainer/test_parser.rb:41:in `gsub'
  /Users/Igor/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/trainer-0.9.1/lib/trainer/test_parser.rb:41:in `block in auto_convert'
  /Users/Igor/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/trainer-0.9.1/lib/trainer/test_parser.rb:36:in `each'
  /Users/Igor/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/trainer-0.9.1/lib/trainer/test_parser.rb:36:in `auto_convert'
  /Users/Igor/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.201.1/scan/lib/scan/runner.rb:223:in `trainer_test_results'
  /Users/Igor/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.201.1/scan/lib/scan/runner.rb:236:in `handle_results'
  /Users/Igor/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.201.1/scan/lib/scan/runner.rb:23:in `run'
  /Users/Igor/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.201.1/scan/lib/scan/manager.rb:23:in `work'
```

**Comment by 1010011010** [comment]
I have the same problem.


<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 12.1                                        |
| Ruby                        | 2.7.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.32.0 (Apple Git-132)          |
| Installation Source         | ~/.rbenv/versions/2.7.0/bin/fastlane        |
| Host                        | macOS 12.1 (21C52)                          |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.0/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 13.2.1                                      |
| Swift Version               | 5.5.2                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

# some content is removed

def run_tests(scheme, binary_basename)
    scan(
      scheme: scheme,
      code_coverage: true,
      clean: true,
      reset_simulator: true,
      output_directory: "fastlane/test_output",
    )
    slather(
      binary_basename: binary_basename,
      input_format: "profdata",
      llvm_cov: true,
      output_directory: "./fastlane/test_output",
      scheme: scheme,
      workspace: "AppWorkspace.xcworkspace",
      source_directory: ".",
      proj: "AppWorkspace.xcodeproj",
    )
    File.rename "../fastlane/test_output/report.junit", "../fastlane/test_output/TEST-#{scheme}.xml"
  end



  desc "Test"
  lane :Test do |options|
    puts "BranchName: #{git_branch}"
    scheme = (options[:scheme] ? options[:scheme] : "AppName")
    binary_basename = (options[:binary_basename] ? options[:binary_basename] : scheme)
    run_tests(scheme, binary_basename)
  end

# some content is removed

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.202.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                      | Version | Update-Status |
| --------------------------- | ------- | ------------- |
| fastlane-plugin-test_center | 3.15.3  | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.4.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| terminal-table                  | 1.8.0        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| artifactory                     | 3.0.15       |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| gh_inspector                    | 1.1.3        |
| security                        | 0.1.3        |
| uri                             | 0.10.0       |
| rexml                           | 3.2.5        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.1.0        |
| CFPropertyList                  | 3.0.5        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.21.0       |
| unicode-display_width           | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| babosa                          | 1.0.4        |
| excon                           | 0.90.0       |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| ruby2_keywords                  | 0.0.5        |
| faraday-retry                   | 1.0.3        |
| faraday-rack                    | 1.0.0        |
| faraday-patron                  | 1.0.0        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-net_http                | 1.0.1        |
| faraday-multipart               | 1.0.3        |
| faraday-httpclient              | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.9.3        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| json                            | 2.6.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.23       |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| webrick                         | 1.7.0        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| signet                          | 0.16.0       |
| os                              | 1.1.4        |
| memoist                         | 0.16.2       |
| googleauth                      | 1.1.0        |
| mini_mime                       | 1.1.2        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.2        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| google-apis-core                | 0.4.2        |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-androidpublisher_v3 | 0.15.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-apis-storage_v1          | 0.11.0       |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-cloud-errors             | 1.2.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.36.0       |
| emoji_regex                     | 3.2.3        |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-partitions                  | 1.550.0      |
| jmespath                        | 1.5.0        |
| aws-sdk-core                    | 3.125.5      |
| aws-sdk-kms                     | 1.53.0       |
| aws-sdk-s3                      | 1.111.3      |
| forwardable                     | 1.3.1        |
| logger                          | 1.4.2        |
| cgi                             | 0.1.0        |
| date                            | 3.0.0        |
| timeout                         | 0.1.0        |
| stringio                        | 0.1.0        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.1.0        |
| mutex_m                         | 0.1.0        |
| ostruct                         | 0.2.0        |
| strscan                         | 1.0.3        |
| io-console                      | 0.5.3        |
| delegate                        | 0.1.0        |
| fileutils                       | 1.4.1        |
| singleton                       | 0.1.0        |
| open3                           | 0.1.0        |
| nokogiri                        | 1.13.1       |
| racc                            | 1.6.0        |
| yaml                            | 0.1.0        |
| psych                           | 3.1.0        |
| xctest_list                     | 1.2.1        |
| colorize                        | 0.8.1        |
| fastlane-plugin-test_center     | 3.15.3       |
</details>


*generated on:* **2022-01-26**
</details>

**Comment by mokagio** [comment]
For what is worth, we "solved" this issue by removing the test center plugin. Since [Xcode 13 added support for test repetition](https://developer.apple.com/videos/play/wwdc2021/10296/), a lot of what `multi_scan` (the action provided by the plugin) does can be replicated with vanilla `scan` combine with the desired test repetition mode.

**Comment by djiangnz** [comment]
Im experiencing the same problem. your PR can defo solve it. Thanks @igor-makarov
