### ISSUE TITLE
Google Api Error: Invalid request - APKs are not allowed for this application.

### ISSUE THREAD

**Issue by dessalines** [fastlane/fastlane#19831]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Whenever I run a deploy, I get the error:

`[15:51:40]: Google Api Error: Invalid request - APKs are not allowed for this application.`

##### Command executed

The default deploy task

##### Complete output when running fastlane, including the stack trace and command used
```
+------+-----------------------+-------------+
|              fastlane summary              |
+------+-----------------------+-------------+
| Step | Action                | Time (in s) |
+------+-----------------------+-------------+
| 1    | update_fastlane       | 0           |
| 2    | default_platform      | 0           |
| 3    | clean assembleRelease | 14          |
| 💥   | upload_to_play_store  | 9           |
+------+-----------------------+-------------+

[15:51:40]: fastlane finished with errors

[!] Google Api Error: Invalid request - APKs are not allowed for this application.
```
### Environment

```
### Stack

| Key                         | Value                                                                                            |
| --------------------------- | ------------------------------------------------------------------------------------------------ |
| OS                          | Linux asus 5.15.15-1-lts #1 SMP Sun, 16 Jan 2022 09:28:22 +0000 x86_64 GNU/Linux                 |
| Ruby                        | 3.0.3                                                                                            |
| Bundler?                    | false                                                                                            |
| Git                         | git version 2.34.1                                                                               |
| Installation Source         | ~/.gem/ruby/3.0.0/bin/fastlane                                                                   |
| Host                        | Linux asus 5.15.15-1-lts #1 SMP Sun, 16 Jan 2022 09:28:22 +0000 x86_64 GNU/Linux (5.15.15-1-lts) |
| Ruby Lib Dir                | /usr/lib                                                                                         |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021                                                                      |
| Is contained                | false                                                                                            |
| Is homebrew                 | false                                                                                            |
| Is installed via Fabric.app | false                                                                                            |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("~/Sync/pc-api-5872058229700584798-705-87a33fa586cc.json")
package_name("com.torrents_csv_android")

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.201.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.89.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.3        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.9.3        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.3.4        |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-playcustomapp_v1    | 0.6.0        |
| google-apis-androidpublisher_v3 | 0.14.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.9.0        |
| google-apis-storage_v1          | 0.10.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.35.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.4.0        |
| aws-partitions                  | 1.547.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-sdk-core                    | 3.125.1      |
| aws-sdk-kms                     | 1.53.0       |
| aws-sdk-s3                      | 1.111.1      |
| tsort                           | 0.1.0        |
| set                             | 1.0.1        |
| json                            | 2.6.1        |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.1        |
| date                            | 3.1.3        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.0        |
| uri                             | 0.10.1       |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.2.1        |
| digest                          | 3.0.0        |
| io-nonblock                     | 0.1.0        |
| io-wait                         | 0.2.0        |
| zlib                            | 2.0.0        |
| resolv                          | 0.2.1        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.1        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.7        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.2        |
| etc                             | 1.3.0        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| net-http                        | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.2.1        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.2        |
</details>

*generated on:* **2022-01-22**
</details>
[15:56:34]: [33mTake notice that this output may contain sensitive information, or simply information that you don't want to make public.[0m
[15:56:34]: [32mOpen https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅[0m
```

**Comment by lucgrabowski** [comment]
Shouldn't you use app bundles instead of .apks?

**Comment by dessalines** [comment]
How do you set that up with fastlane? There's nothing in the config to make it not do apks, that seems to be the default.

**Comment by lucgrabowski** [comment]
Use `aab` parameter as described in http://docs.fastlane.tools/actions/upload_to_play_store/#uploading-an-aab

**Comment by dessalines** [comment]
I'm confused, I thought fastlane deploy was supposed to build apks and aabs for you? And if this is happening for me (google is refusing to allow apk uploads), why isn't this happening for everyone else?

**Comment by dessalines** [comment]
According to this, it seems like fastlane defaults are entirely broken then:

https://stackoverflow.com/questions/70136933/apks-are-not-allowed-for-this-application-when-submitting-an-expo-build-to-pla

**Comment by Kivettt** [comment]
Drive apps should catch and handle all errors that might be encountered when using the REST API. This guide provides instructions on how to resolve specific API errors.

**Comment by Patsy69** [comment]
I found the reason. I need to upload at least one build to google Play store app manually. That’s why I got package name error.

**Comment by max-ott** [comment]
The error is coming directly from the Play Publishing API. Please upload an `AAB` as `APKs` are no longer allowed for new apps.
