### ISSUE TITLE
[run_tests] XCResult no longer generated in derived data path

### ISSUE THREAD

**Issue by DamienRivetOgury** [fastlane/fastlane#19841]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: [e.g. `2.201.0`]
- Last working version: [e.g. `2.200.0`]

### Regression Description
When using the `derived_data_path` parameter of `run_tests`, the resulting `.xcresult` folders were outputted at the specified path.

Starting from version `2.201.0`, this no longer works, the `${derived_data_path}/Logs/Test/` folder now contains only the `LogStoreManifest.plist` file.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[✔] 🚀
[13:10:20]: ------------------------------
[13:10:20]: --- Step: default_platform ---
[13:10:20]: ------------------------------
[13:10:20]: Driving the lane 'ios test' 🚀
[13:10:20]: -----------------------------------------------
[13:10:20]: --- Step: Switch to ios test_framework lane ---
[13:10:20]: -----------------------------------------------
[13:10:20]: Cruising over to lane 'ios test_framework' 🚖
[13:10:20]: -----------------------
[13:10:20]: --- Step: run_tests ---
[13:10:20]: -----------------------
[13:10:20]: Resolving Swift Package Manager dependencies...
[13:10:20]: $ xcodebuild -resolvePackageDependencies -scheme OguryCore -project OguryCore.xcodeproj -configuration Debug -derivedDataPath ./jenkins/test_derived_data
[13:10:21]: ▸ Command line invocation:
[13:10:21]: ▸     /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -scheme OguryCore -project OguryCore.xcodeproj -configuration Debug -derivedDataPath ./jenkins/test_derived_data
[13:10:21]: ▸ User defaults from command line:
[13:10:21]: ▸     IDEDerivedDataPathOverride = /Users/drivet/Documents/Workspace/git/sdk-core-ios/jenkins/test_derived_data
[13:10:21]: ▸     IDEPackageSupportUseBuiltinSCM = YES
[13:10:22]: ▸ resolved source packages:
[13:10:22]: $ xcodebuild -showBuildSettings -scheme OguryCore -project OguryCore.xcodeproj -configuration Debug -derivedDataPath ./jenkins/test_derived_data

+------------------------------------------------+-----------------------------------------------------+
|                                       Summary for scan 2.201.0                                       |
+------------------------------------------------+-----------------------------------------------------+
| project                                        | OguryCore.xcodeproj                                 |
| configuration                                  | Debug                                               |
| scheme                                         | OguryCore                                           |
| devices                                        | ["iPhone 12"]                                       |
| sdk                                            | iphonesimulator                                     |
| clean                                          | true                                                |
| derived_data_path                              | ./jenkins/test_derived_data                         |
| skip_detect_devices                            | false                                               |
| ensure_devices_found                           | false                                               |
| force_quit_simulator                           | false                                               |
| reset_simulator                                | false                                               |
| disable_slide_to_type                          | true                                                |
| reinstall_app                                  | false                                               |
| open_report                                    | false                                               |
| output_directory                               | ./fastlane/test_output                              |
| output_types                                   | html,junit                                          |
| buildlog_path                                  | ~/Library/Logs/scan                                 |
| include_simulator_logs                         | false                                               |
| xcodebuild_formatter                           | xcpretty                                            |
| output_remove_retry_attempts                   | false                                               |
| should_zip_build_products                      | false                                               |
| output_xctestrun                               | false                                               |
| result_bundle                                  | false                                               |
| use_clang_report_name                          | false                                               |
| disable_concurrent_testing                     | false                                               |
| skip_build                                     | false                                               |
| slack_use_webhook_configured_username_and_icon | false                                               |
| slack_username                                 | fastlane                                            |
| slack_icon_url                                 | https://fastlane.tools/assets/img/fastlane_icon.png |
| skip_slack                                     | false                                               |
| slack_only_on_failure                          | false                                               |
| xcodebuild_command                             | env NSUnbufferedIO=YES xcodebuild                   |
| skip_package_dependencies_resolution           | false                                               |
| disable_package_automatic_updates              | false                                               |
| use_system_scm                                 | false                                               |
| number_of_retries                              | 0                                                   |
| fail_build                                     | true                                                |
| xcode_path                                     | /Applications/Xcode.app                             |
+------------------------------------------------+-----------------------------------------------------+

[13:10:25]: Disabling 'Slide to Type' iPhone 12
[13:10:25]: $ /usr/libexec/PlistBuddy -c "Add :KeyboardContinuousPathEnabled bool false" /Users/drivet/Library/Developer/CoreSimulator/Devices/45FA39FF-D251-46CB-897B-50978C39C93C/data/Library/Preferences/com.apple.keyboard.ContinuousPath.plist >/dev/null 2>&1
[13:10:25]: $ set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme OguryCore -project OguryCore.xcodeproj -configuration Debug -derivedDataPath ./jenkins/test_derived_data -sdk 'iphonesimulator' -destination 'platform=iOS Simulator,id=45FA39FF-D251-46CB-897B-50978C39C93C' -resultBundlePath '/var/folders/30/p598kt3j6538d7s26nbx05dw0000gn/T/d20220124-80489-b4gffg/OguryCore.xcresult' clean build test | tee '/Users/drivet/Library/Logs/scan/OguryCore-OguryCore.log' | xcpretty  --report html --output '/Users/drivet/Documents/Workspace/git/sdk-core-ios/fastlane/test_output/report.html' --report junit --output '/Users/drivet/Documents/Workspace/git/sdk-core-ios/fastlane/test_output/report.junit' --report junit --output '/var/folders/30/p598kt3j6538d7s26nbx05dw0000gn/T/junit_report20220124-80489-g1q7i6'
[13:10:25]: ▸ Loading...
[13:10:27]: ▸ Clean Succeeded
...
[13:10:29]: ▸ Linking OguryCoreTests
[13:10:29]: Running Tests: ▸ Touching OguryCoreTests.xctest (in target 'OguryCoreTests' from project 'OguryCore')
[13:10:29]: ▸ All tests
[13:10:29]: ▸ Test Suite OguryCoreTests.xctest started
...
[13:10:30]: ▸ 	 Executed 109 tests, with 0 failures (0 unexpected) in 0.108 (0.161) seconds
[13:10:30]: ▸
[13:10:30]: ▸ 2022-01-24 13:10:30.340 xcodebuild[80561:3490913] [MT] IDETestOperationsObserverDebug: 0.593 elapsed -- Testing started completed.
[13:10:30]: ▸ 2022-01-24 13:10:30.340 xcodebuild[80561:3490913] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
[13:10:30]: ▸ 2022-01-24 13:10:30.340 xcodebuild[80561:3490913] [MT] IDETestOperationsObserverDebug: 0.593 sec, +0.593 sec -- end
[13:10:30]: ▸ Test Succeeded
+--------------------+-----+
|       Test Results       |
+--------------------+-----+
| Number of tests    | 109 |
| Number of failures | 0   |
+--------------------+-----+</pre>
</details>

### Environment

<details>
  <pre>| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.6.2                                      |
| Ruby                        | 2.7.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.34.1                          |
| Installation Source         | ~/.rbenv/versions/2.7.3/bin/fastlane        |
| Host                        | macOS 11.6.2 (20G314)                       |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.3/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.5.1                                      |
| Swift Version               | 5.4.2                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.201.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.4.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| terminal-table                  | 1.8.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| faraday-cookie_jar              | 0.0.7        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| security                        | 0.1.3        |
| dotenv                          | 2.7.6        |
| simctl                          | 1.6.8        |
| uri                             | 0.10.0       |
| rexml                           | 3.2.5        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.1.0        |
| CFPropertyList                  | 3.0.5        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.21.0       |
| unicode-display_width           | 1.8.0        |
| plist                           | 3.6.0        |
| excon                           | 0.90.0       |
| ruby2_keywords                  | 0.0.5        |
| faraday-retry                   | 1.0.3        |
| faraday-rack                    | 1.0.0        |
| faraday-patron                  | 1.0.0        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-net_http                | 1.0.1        |
| faraday-multipart               | 1.0.3        |
| faraday-httpclient              | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.9.3        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| json                            | 2.6.1        |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| xcpretty-travis-formatter       | 1.0.1        |
| bundler                         | 2.2.33       |
| jwt                             | 2.3.0        |
| webrick                         | 1.7.0        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| signet                          | 0.16.0       |
| os                              | 1.1.4        |
| memoist                         | 0.16.2       |
| googleauth                      | 1.1.0        |
| mini_mime                       | 1.1.2        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.2        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| google-apis-core                | 0.4.2        |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-androidpublisher_v3 | 0.15.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-apis-storage_v1          | 0.11.0       |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-cloud-errors             | 1.2.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.36.0       |
| emoji_regex                     | 3.2.3        |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-partitions                  | 1.549.0      |
| jmespath                        | 1.5.0        |
| aws-sdk-core                    | 3.125.5      |
| aws-sdk-kms                     | 1.53.0       |
| aws-sdk-s3                      | 1.111.2      |
| forwardable                     | 1.3.1        |
| logger                          | 1.4.2        |
| cgi                             | 0.1.0        |
| date                            | 3.0.0        |
| timeout                         | 0.1.0        |
| stringio                        | 0.1.0        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.1.0        |
| mutex_m                         | 0.1.0        |
| ostruct                         | 0.2.0        |
| strscan                         | 1.0.3        |
| io-console                      | 0.5.6        |
| delegate                        | 0.1.0        |
| fileutils                       | 1.4.1        |
| singleton                       | 0.1.0        |
| open3                           | 0.1.0        |
| nokogiri                        | 1.12.4       |
| racc                            | 1.5.2        |
| yaml                            | 0.1.0        |
| psych                           | 3.1.0        |
</details>
</pre>
</details>

**Comment by DamienRivetOgury** [comment]
Seems to be linked to https://github.com/fastlane/fastlane/issues/19824.

**Comment by spitz** [comment]
@DamienRivetOgury - looks like `scan` has `result_bundle` set to `false`. In my issue #19824 after updating to 2.201.**1**, adding this value in my Fastfile and setting it to true resolved the issue.

**Comment by andrewclaus** [comment]
> @DamienRivetOgury - looks like `scan` has `result_bundle` set to `false`. In my issue #19824 after updating to 2.201.**1**, adding this value in my Fastfile and setting it to true resolved the issue.

Unfortunately this did not work for my project. prior to 2.201.0, the xcresult file was being generated for our project, but now it is not.

**Comment by joshdholtz** [comment]
Oh no, my bad! I will look into and get a fix out for this

**Comment by joshdholtz** [comment]
Side note... The xcresult path can also be found with...

```rb
Actions.lane_context[SharedValues::SCAN_GENERATED_XCRESULT_PATH]
```

... after `scan` is called 😊

**Comment by DamienRivetOgury** [comment]
Wow that was fast as hell 😲 Thanks for the fix @joshdholtz.

**Comment by evenoe** [comment]
I'm still having this issue with fastlane 2.201.2. Also tried v2.204.2 with no success.
