### ISSUE TITLE
[scan] number_of_retries on 2.201.1 + Xcode 13 behaves differently from documentation

### ISSUE THREAD

**Issue by gobetti** [fastlane/fastlane#19842]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Per [docs](https://docs.fastlane.tools/actions/scan/) `number_of_retries` is
> The number of times a test can fail before scan should stop retrying

i.e. 0 (the default value) means no retries, only 1 iteration is allowed.
With Xcode 13, [`number_of_retries` is being input to the new `-test-iterations` setting in xcodebuild](https://github.com/fastlane/fastlane/blob/bdf2336949388cfcd9b13a718bca9c12bc6ab7df/scan/lib/scan/test_command_generator.rb#L75-L78) so it's retrying 1 time less than before.
Another example: now `number_of_retries: 1` actually means "don't retry".

##### Example
This should be reproducible using the `number-of-iterations-equals-retries` branch from https://github.com/gobetti/fastlane-201-issues , or this commit https://github.com/gobetti/fastlane-201-issues/commit/14b4c6ff2515769975edbf11a2c988ad74b1a01f

**Comment by joshdholtz** [comment]
Ah! Can't believe I forgot to change this. I'll get this fixed!

**Comment by joshdholtz** [comment]
@gobetti This should be fixed with #19844 💪
