### ISSUE TITLE
Uploading binaries and metadata with `deliver`, but some metadata text files are not reflected on the App Store Connect.

### ISSUE THREAD

**Issue by daidongon** [fastlane/fastlane#19848]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
  - I'm having this issue with at least `2.182.0` and `2.198.1`.
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

- I uploaded the metadata contained in `./fastlane/metadata/default/` by `deliver`, but the metadata described in the `promotional_text.txt`, `release_notes.txt` and `support_url.txt` files is not reflected on App Store Connect.
- There may be other metadata files that aren't reflected, but I haven't confirmed them.
- By the way, no error was output in the command execution result.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by max-ott** [comment]
Can you please update to the latest version of Fastlane and try again?

**Comment by daidongon** [comment]
@max-ott Thanks. It seems that this problem still occurs in the latest version. If you don't mind, I would be grateful if you could reopen the Issue.
