### ISSUE TITLE
Build number: xx.yy does not exist

### ISSUE THREAD

**Issue by medabida** [fastlane/fastlane#19840]
### Discussed in https://github.com/fastlane/fastlane/discussions/19691

<div type='discussions-op-text'>

<sup>Originally posted by **medabida** December 10, 2021</sup>
Hi, 👋  
I am using `Deliver` to publish an app to the Appstore and i am running into the error `Build number: xx.yy does not exist`.
i saw that this was kinda a bug in fastlane in previous versions  [(issue here)](https://github.com/fastlane/fastlane/issues/18069) and was fixed, so this is not related.

the cause of my issue is the following:
let say i am uploading a new version `5.6.1`, i will first upload the build to testflight under another version `1000005.6.1`  (the prefix 100000 is for sake of compliance/ other technical reasons).. and then when publishing the app on the appstore i will have to pick that exact build and publish it under `5.6.1`

to achieve this i am doing the following:
```
current_version = "5.6.1"

// get the build number
latest_build_number = latest_testflight_build_number(version: "100000000" + current_version, api_key: api_key, app_identifier: "com.yolo.com")

// use the build number with deliver to publish that specific build
deliver(
    precheck_include_in_app_purchases: false,
    api_key: api_key,
    build_number: latest_build_number,
    app_version: current_version,
    submit_for_review: true,
    automatic_release: false,
    phased_release: true,
    force: true, # Skip HTMl report verification
    run_precheck_before_submit: true,
    skip_metadata: true,
    skip_screenshots: true,
    skip_binary_upload: true,
    submission_information: {
        ...
    }
)
```

`Deliver` will then throw the error `Build number: xx.yy does not exist` because it couldnt find that build number under `5.6.1`.
Under the hood, fastlane will use this GET request 
```
https://api.appstoreconnect.apple.com/v1/builds?include=app%2CpreReleaseVersion%2CbuildBundles%2CbuildBetaDetail&filter%5Bversion%5D=5465454.91918&filter%5BpreReleaseVersion.version%5D=5.6.1&limit=30&sort=-uploadedDate&filter%5BprocessingState%5D=FAILED%2CINVALID%2CPROCESSING%2CVALID
```
which when i execute it with Postman, it will return an empty list. but when changing the version in the GET param to `1000005.6.1` instead of `5.6.1` it gives the correct response.

Going through the fastlane/deliver documentation i could not find a way to specify the version number except `app_version` which doesn't fit my use-case. (the version needs to be created is `5.6.1` but the build needs to be picked up from `1000005.6.1`).

is there a workaround for this, will this be supported in future versions of fastlane ?

Thanks

---
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 12.0.1                                                  |
| Ruby                        | 3.0.3                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.30.1 (Apple Git-130)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.198.1/libexec/bin/fastlane |
| Host                        | macOS 12.0.1 (21A559)                                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/3.0.3/lib                        |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021                             |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode13.1-beta.app/Contents/Developer/    |
| Xcode Version               | 13.1                                                    |
| Swift Version               | 5.5.1                                                   |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.198.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.88.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.8.0        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.5        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.32       |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-playcustomapp_v1    | 0.6.0        |
| google-apis-androidpublisher_v3 | 0.13.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.8.0        |
| google-apis-storage_v1          | 0.9.0        |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.34.1       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.4.0        |
| aws-partitions                  | 1.532.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-sdk-core                    | 3.122.1      |
| aws-sdk-kms                     | 1.51.0       |
| aws-sdk-s3                      | 1.106.0      |
| set                             | 1.0.1        |
| json                            | 2.6.1        |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.1        |
| date                            | 3.1.3        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.1        |
| uri                             | 0.10.1       |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.2.1        |
| digest                          | 3.0.0        |
| io-nonblock                     | 0.1.0        |
| io-wait                         | 0.2.0        |
| zlib                            | 2.0.0        |
| resolv                          | 0.2.1        |
| securerandom                    | 0.1.0        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.1        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.7        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| net-http                        | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.2.1        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.2        |
</details>

*generated on:* **2021-12-10**
</details></div>

**Comment by Erin69** [comment]
For every new build you submit, you will need to invent a new Build Number whose value is greater than the last Build Number you used (for that same version).

**Comment by medabida** [comment]
@Erin69 That is already the case. 
The issue here is something else, basically `deliver` does not allow creating a new store version lets say `1.1.2` while using a build uploaded for `1.1.1`..

@webwarrior06 i solved this in kinda a hacky way..
basically every-time we build the app for TestFlight we also upload it to an S3 bucket as an archive.
then when it is time to release the app, i download it from S3 and feed its local path to `deliver` using the ipa key

**Comment by GJBlog** [comment]
same Problem ,2.176.0 version
