### ISSUE TITLE
[scan] [docs] Missing new options in docs: output_remove_retry_attempts and xcodebuild_formatter

### ISSUE THREAD

**Issue by gobetti** [fastlane/fastlane#19843]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I wasn't able to find these new fastlane 2.201 options in the [scan docs](https://docs.fastlane.tools/actions/scan/):
- output_remove_retry_attempts
- xcodebuild_formatter

**Comment by joshdholtz** [comment]
Whoops! Forgot to merge the docs 😱 This should be updated in a bit 😊
