### ISSUE TITLE
No option for xcodebuild option "-parallel-testing-enabled"

### ISSUE THREAD

**Issue by tejassharma96** [fastlane/fastlane#19856]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

It's pretty strange that fastlane lets me set `-parallel-testing-worker-count` using `concurrent_workers`, but I have to use `xcargs: "-parallel-testing-enabled YES"` to actually enable parallel testing. I would expect that option to be configurable via fastlane as well.

**Comment by Chesterqa** [comment]
This is quiet a common issue
