### ISSUE TITLE
Match: fails to create provisioning profile for certain appID: "There is a problem with the request entity"

### ISSUE THREAD

**Issue by zahs** [fastlane/fastlane#19855]
### Discussed in https://github.com/fastlane/fastlane/discussions/19854

<div type='discussions-op-text'>

<sup>Originally posted by **zahs** January 26, 2022</sup>
hi,

I am trying to renew my adhoc/appstore cert and profiles.\ 
We have eg _bunlde.id_, _bundle.id.watch_, _bundle.id.widget_
And I have to update all provisioning profiles, provisioning profile for _bunlde.id_ fails to be created, others are creating successully.

I am using nuke to revoke them firstly.
afterwards running a match command to create cert and profiles.
`match_nuke(
            type: type,
            app_identifier: appIdentifier,
            username: username,
            git_user_email: git_user_email
        )`

`match(
        type: type,
        app_identifier: appIdentifier,
        profile_name: profile_name,
        generate_apple_certs: true,
        template_name: template_name,
        username: username,
        git_user_email: git_user_email
    )`
    
 

for one of my profiles it gives the following error

    
` {
  "errors" : [ {
    "id" : "id...,
    "status" : "409",
    "code" : "ENTITY_ERROR",
    "title" : "There is a problem with the request entity",
    "resultCode" : 8530,
    "detail" : "There was an error generating the provisioning profile   Please try again.  If the problem persists, please contact Apple Developer Program Support. https://developer.apple.com/support"
  } ]
}`

I am able to create this profile manually using already generated certificate.
What can be the issue?</div>

**Comment by lucgrabowski** [comment]
It's hard to say why you get this error without seeing logs. One of the possible problems could be using wrong template_name. If you try creating a profile with wrong template_name, Apple's server will respond with 409, as above. When you create a profile manually, you should take a look at the values in the Entitlements dropdown to look for possible values in template_name parameter.

**Comment by Chesterqa** [comment]
Facing same issue here. Help is appreciated.

**Comment by Chesterqa** [comment]
But I'm curious since I'm pretty sure my App.entitlements does not contains Game Center lines. Could you please show me a clear path how to solve this glitch?

**Comment by zahs** [comment]
I have fixed the template_name and it worked correctly. 
Thanks @lucgrabowski 
@Chesterqa  probably you should check if all your parameters have correct values

**Comment by zahs** [comment]
> It's hard to say why you get this error without seeing logs. One of the possible problems could be using wrong template_name. If you try creating a profile with wrong template_name, Apple's server will respond with 409, as above. When you create a profile manually, you should take a look at the values in the Entitlements dropdown to look for possible values in template_name parameter.

**Comment by zahs** [comment]
one more help pls
now I am setting my template 
`match(
        type: type,
        app_identifier: appIdentifier,
        profile_name: profile_name,
        generate_apple_certs: true,
        template_name: "Apple Pay Pass Suppression Distribution",
        username: username,
        git_user_email: git_user_email
    )`
    
it creates appstore type provisioning profile correctly with correct entitlement but doesn't add entitlement for adhoc provisioning profile.
Do you know what can be the issue?
FYI @lucgrabowski

**Comment by lucgrabowski** [comment]
Hi, it's hard to guess without logs. Are you able to create adhoc profile with entitlements in Developer Center? What `type` value do you use? You could call lane with `--verbose` option in terminal, maybe you'll notice something helpful there.

**Comment by zahs** [comment]
yes, I am able to add it manually , also after fastlane creates it, I can add the entitlement the same one I am trying to add via fastlane.
Verbose doesn't give me anything helpful.
The only thing it checks WWDR certificate if it relates.
here the summary from fastlane
<img width="896" alt="Screenshot 2022-02-01 at 20 36 03" src="https://user-images.githubusercontent.com/6029281/152031065-46894ba8-bd8b-48de-a9d8-9bed8c67ab64.png">

**Comment by Kivettt** [comment]
Thank you so much to sharing amazing post.

**Comment by max-ott** [comment]
As far as I know you cannot mix `match` and `sigh`/`cert`.

**Comment by Hinderlit** [comment]
A provisioning profile is downloaded from your developer account and embedded in the app bundle, and the entire bundle is code-signed. A Development Provisioning Profile must be installed on each device on which you wish to run your application code. If the information in the provisioning profile doesn’t match certain criteria, your app won’t launch.
