### ISSUE TITLE
I am unable to init the fastlane in React-Native Android in windows 11

### ISSUE THREAD

**Issue by HammadUllahKhan12** [fastlane/fastlane#19877]
Issue.
I am working on react-native project. And need to integrate the fastlane with android. 
React-native is running successfully. 
But as per the documentation. I move to the android folder run the command to fastlane init. It gives me this error.

Here are the screenshot of my terminal.
![image](https://user-images.githubusercontent.com/48718737/151659605-77a518da-7d66-4773-bc59-bfb8cdfbafd0.png)

and here is the screenshot with envs.

![image](https://user-images.githubusercontent.com/48718737/151659651-ba4be985-e88f-4a93-9c42-ba5a0d4284f4.png)

**Comment by HammadUllahKhan12** [comment]
fastlane env output: 

$ fastlane env
[11:41:12]: fastlane detected a Gemfile in the current directory
[11:41:12]: However, it seems like you didn't use `bundle exec`
[11:41:12]: To launch fastlane faster, please use
[11:41:12]:
[11:41:12]: $ bundle exec fastlane env
[11:41:12]:
[11:41:12]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[11:41:15]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                        |
| --------------------------- | ---------------------------- |
| OS                          | UNKNOWN                      |
| Ruby                        | 3.0.3                        |
| Bundler?                    | false                        |
| Git                         | git version 2.34.1.windows.1 |
| Installation Source         | C:/Ruby30-x64/bin/fastlane   |
| Host                        | Unknown  ()                  |
| Ruby Lib Dir                | C:/Ruby30-x64/lib            |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021  |
| Is contained                | false                        |
| Is homebrew                 | false                        |
| Is installed via Fabric.app | false                        |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.203.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| fiddle                          | 1.0.8        |
| did_you_mean                    | 1.5.0        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.90.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.3        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.9.3        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.5.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.32       |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.2        |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-androidpublisher_v3 | 0.15.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.11.0       |
| rake                            | 13.0.3       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.36.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.5.0        |
| aws-partitions                  | 1.551.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-sdk-core                    | 3.125.5      |
| aws-sdk-kms                     | 1.53.0       |
| aws-sdk-s3                      | 1.111.3      |
| set                             | 1.0.1        |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.1        |
| date                            | 3.1.3        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.0        |
| uri                             | 0.10.1       |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.2.1        |
| digest                          | 3.0.0        |
| io-nonblock                     | 0.1.0        |
| io-wait                         | 0.2.0        |
| zlib                            | 2.0.0        |
| resolv                          | 0.2.1        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.1        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.7        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.2        |
| etc                             | 1.3.0        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| net-http                        | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.2.1        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.2        |
</details>


*generated on:* **2022-01-29**
</details>
[11:41:17]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[11:41:17]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅

**Comment by Davidsons1** [comment]
This article is really amazing. Thanks for the sharing.
