### ISSUE TITLE
fastlane archive failed with `method_missing`

### ISSUE THREAD

**Issue by xwartz** [fastlane/fastlane#19874]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I am trying to build my iOS App with Fastlane, but fails with `method_missing`.

##### Command executed
```
build_app(
    workspace: "token.xcworkspace", 
    scheme: "token", 
    export_method: "ad-hoc"
)
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
/opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane_core/lib/fastlane_core/ui/interface.rb:163:in `build_failure!': \e[31m[!] Error building the application - see the log above\e[0m (FastlaneCore::Interface::FastlaneBuildFailure)
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/gym/lib/gym/error_handler.rb:73:in `handle_build_error'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/gym/lib/gym/runner.rb:114:in `block in build_app'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane_core/lib/fastlane_core/command_executor.rb:84:in `execute'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/gym/lib/gym/runner.rb:110:in `build_app'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/gym/lib/gym/runner.rb:18:in `run'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/gym/lib/gym/manager.rb:19:in `work'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/actions/build_app.rb:68:in `run'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:42:in `block (2 levels) in parsing_binding'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/opt/rbenv/versions/3.0.3/bin/fastlane:25:in `load'
	from /opt/homebrew/opt/rbenv/versions/3.0.3/bin/fastlane:25:in `<main>'
/opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane_core/lib/fastlane_core/ui/interface.rb:163:in `build_failure!': Error building the application - see the log above (FastlaneCore::Interface::FastlaneBuildFailure)
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/gym/lib/gym/error_handler.rb:73:in `handle_build_error'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/gym/lib/gym/runner.rb:114:in `block in build_app'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane_core/lib/fastlane_core/command_executor.rb:84:in `execute'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/gym/lib/gym/runner.rb:110:in `build_app'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/gym/lib/gym/runner.rb:18:in `run'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/gym/lib/gym/manager.rb:19:in `work'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/actions/build_app.rb:68:in `run'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:42:in `block (2 levels) in parsing_binding'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.203.0/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/opt/rbenv/versions/3.0.3/bin/fastlane:25:in `load'
	from /opt/homebrew/opt/rbenv/versions/3.0.3/bin/fastlane:25:in `<main>'
  </pre>
</details>

### Environment

<details>
  <pre>
swift-driver version: 1.26.21 <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                               |
| --------------------------- | --------------------------------------------------- |
| OS                          | 12.0.1                                              |
| Ruby                        | 3.0.3                                               |
| Bundler?                    | false                                               |
| Git                         | git version 2.31.1                                  |
| Installation Source         | /opt/homebrew/opt/rbenv/versions/3.0.3/bin/fastlane |
| Host                        | macOS 12.0.1 (21A559)                               |
| Ruby Lib Dir                | /opt/homebrew/Cellar/rbenv/1.2.0/versions/3.0.3/lib |
| OpenSSL Version             | OpenSSL 1.1.1m  14 Dec 2021                         |
| Is contained                | false                                               |
| Is homebrew                 | false                                               |
| Is installed via Fabric.app | false                                               |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/         |
| Xcode Version               | 13.2.1                                              |
| Swift Version               | 5.5.2                                               |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "upload to fir.im"
  lane :fir do
    build_app(
      workspace: "token.xcworkspace",
      scheme: "token",
      export_method: "ad-hoc"
    )
    firim(
      firim_api_token: "",
      app_changelog: changelog,
      firim_api_url: "https://api.bq04.com"
    )
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "im.xxxx.app" # The bundle identifier of your app
apple_id "xxxx@gmail.com" # Your Apple email address

itc_team_id "xxxx" # iTunes Connect Team ID
team_id "xxxx" # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.203.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-versioning | 0.5.0   | ✅ Up-To-Date  |
| fastlane-plugin-firim      | 0.2.2   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.89.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.3        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.9.3        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.5.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-androidpublisher_v3 | 0.15.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.11.0       |
| rake                            | 13.0.3       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.35.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.5.0        |
| aws-partitions                  | 1.547.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-sdk-core                    | 3.125.2      |
| aws-sdk-kms                     | 1.53.0       |
| aws-sdk-s3                      | 1.111.1      |
| set                             | 1.0.1        |
| bundler                         | 2.3.4        |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.1        |
| date                            | 3.1.3        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.0        |
| uri                             | 0.10.1       |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.2.1        |
| digest                          | 3.0.0        |
| io-nonblock                     | 0.1.0        |
| io-wait                         | 0.2.0        |
| zlib                            | 2.0.0        |
| resolv                          | 0.2.1        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.1        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.7        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| net-http                        | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.2.1        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.2        |
| fastlane-plugin-versioning      | 0.5.0        |
| firim                           | 0.2.7        |
| fastlane-plugin-firim           | 0.2.2        |
</details>

*generated on:* **2022-01-28**
  </pre>
</details>

**Comment by lucgrabowski** [comment]
The problem that you have is probably because of wrong code signing settings. Without more logs the community won't be able to help you. It is explicitly written in logs that you pasted  "Error building the application - see the log above", so the problem is described higher in logs. I can advise you that you check if you can build and export app properly from Xcode. You could also take a look at http://docs.fastlane.tools/actions/update_project_provisioning and use it before `build_app`

**Comment by xwartz** [comment]
I can build and export app properly from Xcode but can't from Fastlane, I will check the http://docs.fastlane.tools/actions/update_project_provisioning

**Comment by Kivettt** [comment]
Thank you so much to sharing this post.

**Comment by Jesus131** [comment]
I was building it and haven't faced this issue but good to know this thanks for sharing.

**Comment by Davidsons1** [comment]
Thank you for sharing your valuable solution, it's work properly.
