### ISSUE TITLE
Match doesn't add Apple Development Certificate to Xcode

### ISSUE THREAD

**Issue by emrdgrmnci** [fastlane/fastlane#19885]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I tried all of this on both Xcode 13.0, 13.1 and, 13.2.1 and iOS 15.0, 15.1, 15.2.1.

I have a lot of different Targets on Xcode. And also, their Apple Development and Distribution certificates. Fastlane setup on different Git branch.

I used `bundle exec fastlane onboarding_certificates` command from my terminal to install the corresponding app certificates. Everything works properly with this fastlane command but when it comes to selecting these certificates on Xcode Provisioning Profiles, match AppStore certificate is okay, but when I select the match Apple Development certificate giver this error `Provisioning profile "match Development com.*****.*****" doesn't include signing certificate "Apple Development: ******* (1234ABC)".` 

##### Command executed

`bundle exec fastlane onboarding_certificates` 
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 12.2                                                    |
| Ruby                        | 3.0.3                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.32.0 (Apple Git-132)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.200.0/libexec/bin/fastlane |
| Host                        | macOS 12.2 (21D49)                                      |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/3.0.3/lib                        |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021                             |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode_13.2.1.app/Contents/Developer/      |
| Xcode Version               | 13.2.1                                                  |
| Swift Version               | 5.5.2                                                   |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
require_relative "teams.rb"
require_relative "app"

apps = Array.new
f = File.open("apps")
f.each_line { |line|
  apps.push App.new(line)
}

def prompt_with_default(default, args)
  print(*args)
  result = STDIN.gets.strip
  return result.empty? ? default : result
end

def filter_apps(apps)
  puts "Available apps:"
  i = 0
  for app in apps
    puts "#{i}: #{app.app_name} (#{app.identifier})"
    i = i + 1
  end
  app_id = prompt_with_default(-1, "Select which app you want to perform the action for (see list above), by entering its index. \nTo perform the action for all apps, leave the index empty: ").to_i
  if app_id != -1
    single_app_array = Array.new
    app = apps[app_id]
    single_app_array.push app
    return single_app_array
  else
    return apps
  end
end

desc "Runs all the tests"
lane :tests do
  scan(
    workspace: "***********",
    scheme: "***********",
    device: "***********",
    use_system_scm: true,
    clean: true
  )
end

desc "Run Danger pre-checks"
lane :danger_pre_checks do
  danger(
    danger_id: "pre_checks",
    dangerfile: "Dangerfile.prechecks",
    fail_on_errors: true,
    verbose: true
  )
end

desc "Run match for one or all of our profiles"
lane :certificates do
  prompt_result = prompt(text: "Should we force the creation of new profiles? [yN]: ")
  should_force = prompt_result == "y" || prompt_result == "Y"
  for app in filter_apps(apps)
    for type in ["development", "appstore"]
      begin
        match(
          type: type,
          username: app.team.username,
          app_identifier: app.identifier,
          team_id: app.team.team_id,
          git_branch: app.team.git_branch,
          force: should_force
        )
      rescue => ex
        UI.error(ex)
      end
    end
  end
end

desc "Export translations ***********"
lane :translations_export do
  sh "bash ./../Scripts/upload_translations.sh"
end

desc "Import translations ***********"
lane :translations_import do
  ***********r_export(
    api_token: "***********",
    project_id: "***********",
    export_format: "***********",
    language: "***********",
    output_path: "***********"
  )
 ***********r_export(
    api_token: "***********",
    project_id: "***********",
    export_format: "***********",
    language: "sv***********,
    output_path: "***********"
  )
  ***********r_export(
    api_token: "***********",
    project_id: "***********",
    export_format: "***********",
    language: "***********",
    output_path: "***********"
  )
  ***********r_export(
    api_token: "***********",
    project_id: "***********",
    export_format: "***********",
    language: "***********",
    output_path: "***********"
  )
  ***********r_export(
    api_token: "***********",
    project_id: "***********",
    export_format: "***********",
    language: "***********",
    output_path: "***********"
  )
  ***********r_export(
    api_token: "***********",
    project_id: "***********",
    export_format: "***********",
    language: "***********",
    output_path: "***********"
  )
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.200.0 | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                          | Version | Update-Status |
| ------------------------------- | ------- | ------------- |
| fastlane-plugin-***********rt | 0.3.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.90.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.3        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.9.3        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.5.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.32       |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-androidpublisher_v3 | 0.15.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.11.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.36.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.5.0        |
| aws-partitions                  | 1.547.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-sdk-core                    | 3.125.3      |
| aws-sdk-kms                     | 1.53.0       |
| aws-sdk-s3                      | 1.111.1      |
| set                             | 1.0.1        |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.1        |
| date                            | 3.1.3        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.0        |
| uri                             | 0.10.1       |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.2.1        |
| digest                          | 3.0.0        |
| io-nonblock                     | 0.1.0        |
| io-wait                         | 0.2.0        |
| zlib                            | 2.0.0        |
| resolv                          | 0.2.1        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.1        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.7        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| net-http                        | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.2.1        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.2        |
| fastlane-plugin-***********r_export | 0.3.0        |
</details>

*generated on:* **2022-02-01**
</details> </pre>
</details
<img width="808" alt="dev" src="https://user-images.githubusercontent.com/10485498/152038118-4f9a2f5a-d18d-4309-b2f8-c958e2e172eb.png">
<img width="821" alt="dist" src="https://user-images.githubusercontent.com/10485498/152038140-5861b497-b2c7-464c-93be-109d49fbf694.png">
<img width="820" alt="xcode" src="https://user-images.githubusercontent.com/10485498/152038142-65ef4c6b-f9f7-4cf7-8edc-ab8736ae8f88.png">
>

**Comment by emrdgrmnci** [comment]
Add more detail.

**Comment by AdamGerthel** [comment]
I have the exact same problem. I'm on xcode 13.3.
