### ISSUE TITLE
Fastlane erroring out with error "Migration Needed: As of 2.201.0, trainer is included in fastlane"

### ISSUE THREAD

**Issue by ykhandelwal913** [fastlane/fastlane#19887]
### New Issue Checklist

- [x] Updated fastlane to the latest version - Yes 
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md) 
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
We were using fastlane 2.148.0 and started notificing the error `Migration Needed: As of 2.201.0, trainer is included in fastlane. Please remove the trainer plugin from your Gemfile or Pluginfile (or with 'gem uninstall fastlane-plugin-trainer') - More information: https://docs.fastlane.tools/best-practices/xcodebuild-formatters/` , 
We updated fastlane to latest version but still that error coming intermittenly. We dont have fastlane-plugin-trainer gem installed locally. 

##### Command executed
all fastlane command giving the same error.
fastlane 
fastlane env
fastlane run create_keychain name:${keychainName} default_keychain:false timeout:${keychainTimeout} password:${keychainPassword} unlock:true require_create:false

##### Complete output when running fastlane, including the stack trace and command used
Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
[!] Migration Needed: As of 2.201.0, trainer is included in fastlane. Please remove the trainer plugin from your Gemfile or Pluginfile (or with 'gem uninstall fastlane-plugin-trainer') - More information: https://docs.fastlane.tools/best-practices/xcodebuild-formatters/[0m

fastlane --verbose
[✔] 🚀
[23:39:13]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2022-02-01 23:39:14.75]: Checking if there are any plugins that should be loaded...
Traceback (most recent call last):
	11: from /Users/xxxxx/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `<main>'
	10: from /Users/xxxxx/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `eval'
	 9: from /Users/xxxxx/.rvm/gems/ruby-2.7.2/bin/fastlane:25:in `<main>'
	 8: from /Users/xxxxx/.rvm/gems/ruby-2.7.2/bin/fastlane:25:in `load'
	 7: from /Users/xxxxx/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/bin/fastlane:23:in `<top (required)>'
	 6: from /Users/xxxxx/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	 5: from /Users/xxxxx/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	 4: from /Users/xxxxx/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	 3: from /Users/xxxxx/.rvm/gems/ruby-2.7.2/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	 2: from /Users/xxxxx/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:121:in `run!'
	 1: from /Users/xxxxx/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/xxxxx/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': Migration Needed: As of 2.201.0, trainer is included in fastlane. Please remove the trainer plugin from your Gemfile or Pluginfile (or with 'gem uninstall fastlane-plugin-trainer') - More information: https://docs.fastlane.tools/best-practices/xcodebuild-formatters/ (FastlaneCore::Interface::FastlaneError)
	11: from /Users/xxxxx/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `<main>'
	10: from /Users/xxxxx/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `eval'
	 9: from /Users/xxxxx/.rvm/gems/ruby-2.7.2/bin/fastlane:25:in `<main>'
	 8: from /Users/xxxxx/.rvm/gems/ruby-2.7.2/bin/fastlane:25:in `load'
	 7: from /Users/xxxxx/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/bin/fastlane:23:in `<top (required)>'
	 6: from /Users/xxxxx/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	 5: from /Users/xxxxx/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	 4: from /Users/xxxxx/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	 3: from /Users/xxxxx/.rvm/gems/ruby-2.7.2/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	 2: from /Users/xxxxx/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:121:in `run!'
	 1: from /Users/xxxxx/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/xxxxx/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.204.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': \e[31m[!] Migration Needed: As of 2.201.0, trainer is included in fastlane. Please remove the trainer plugin from your Gemfile or Pluginfile (or with 'gem uninstall fastlane-plugin-trainer') - More information: https://docs.fastlane.tools/best-practices/xcodebuild-formatters/\e[0m (FastlaneCore::Interface::FastlaneError)

### Environment

fastlane -version
[✔] 🚀
[23:27:57]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
fastlane 2.204.0

fastlane env
[✔] 🚀
[23:28:11]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

[!] Migration Needed: As of 2.201.0, trainer is included in fastlane. Please remove the trainer plugin from your Gemfile or Pluginfile (or with 'gem uninstall fastlane-plugin-trainer') - More information: https://docs.fastlane.tools/best-practices/xcodebuild-formatters/

**Comment by ykhandelwal913** [comment]
fastlane env is giving error mentioned above.

**Comment by ykhandelwal913** [comment]
All looking good with fastlane version <= 2.200.0

**Comment by ykhandelwal913** [comment]
@joshdholtz can you please check this?

**Comment by joshdholtz** [comment]
@ykhandelwal913 Are you using a `Gemfile`? Can you try running `bundle exec fastlane <cmd>`? Seems like trainer gem might be still in your system somewhere? 🤔 

Could you also try doing `gem uninstall trainer` or `gem install fastlane-plugin-trainer`?

This error might have been too aggressive and I need to fix but I'm curious on why you are seeing this.

**Comment by ykhandelwal913** [comment]
@joshdholtz Yes i am using Gemfile , mentioned only 3 gems in that (fastlane, xcov,slather) 

I have tried gem uninstall trainer or gem install or uninstall fastlane-plugin-trainer but still it didnot work.

**Comment by joshdholtz** [comment]
@ykhandelwal913 Did you try running with `bundle exec`?

Can you send over your `Gemfile.lock` contents?

**Comment by ykhandelwal913** [comment]
Gemfile.lock contents `GEM
  remote: https://rubygems.org/
  specs:
    CFPropertyList (3.0.5)
      rexml
    activesupport (7.0.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    artifactory (3.0.15)
    atomos (0.1.3)
    aws-eventstream (1.2.0)
    aws-partitions (1.551.0)
    aws-sdk-core (3.125.5)
      aws-eventstream (~> 1, >= 1.0.2)
      aws-partitions (~> 1, >= 1.525.0)
      aws-sigv4 (~> 1.1)
      jmespath (~> 1.0)
    aws-sdk-kms (1.53.0)
      aws-sdk-core (~> 3, >= 3.125.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-s3 (1.111.3)
      aws-sdk-core (~> 3, >= 3.125.0)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.4)
    aws-sigv4 (1.4.0)
      aws-eventstream (~> 1, >= 1.0.2)
    babosa (1.0.4)
    claide (1.1.0)
    clamp (1.3.2)
    colored (1.2)
    colored2 (3.1.2)
    commander (4.6.0)
      highline (~> 2.0.0)
    concurrent-ruby (1.1.9)
    declarative (0.0.20)
    digest-crc (0.6.4)
      rake (>= 12.0.0, < 14.0.0)
    domain_name (0.5.20190701)
      unf (>= 0.0.5, < 1.0.0)
    dotenv (2.7.6)
    emoji_regex (3.2.3)
    excon (0.90.0)
    faraday (1.9.3)
      faraday-em_http (~> 1.0)
      faraday-em_synchrony (~> 1.0)
      faraday-excon (~> 1.1)
      faraday-httpclient (~> 1.0)
      faraday-multipart (~> 1.0)
      faraday-net_http (~> 1.0)
      faraday-net_http_persistent (~> 1.0)
      faraday-patron (~> 1.0)
      faraday-rack (~> 1.0)
      faraday-retry (~> 1.0)
      ruby2_keywords (>= 0.0.4)
    faraday-cookie_jar (0.0.7)
      faraday (>= 0.8.0)
      http-cookie (~> 1.0.0)
    faraday-em_http (1.0.0)
    faraday-em_synchrony (1.0.0)
    faraday-excon (1.1.0)
    faraday-httpclient (1.0.1)
    faraday-multipart (1.0.3)
      multipart-post (>= 1.2, < 3)
    faraday-net_http (1.0.1)
    faraday-net_http_persistent (1.2.0)
    faraday-patron (1.0.0)
    faraday-rack (1.0.0)
    faraday-retry (1.0.3)
    faraday_middleware (1.2.0)
      faraday (~> 1.0)
    fastimage (2.2.6)
    fastlane (2.204.0)
      CFPropertyList (>= 2.3, < 4.0.0)
      addressable (>= 2.8, < 3.0.0)
      artifactory (~> 3.0)
      aws-sdk-s3 (~> 1.0)
      babosa (>= 1.0.3, < 2.0.0)
      bundler (>= 1.12.0, < 3.0.0)
      colored
      commander (~> 4.6)
      dotenv (>= 2.1.1, < 3.0.0)
      emoji_regex (>= 0.1, < 4.0)
      excon (>= 0.71.0, < 1.0.0)
      faraday (~> 1.0)
      faraday-cookie_jar (~> 0.0.6)
      faraday_middleware (~> 1.0)
      fastimage (>= 2.1.0, < 3.0.0)
      gh_inspector (>= 1.1.2, < 2.0.0)
      google-apis-androidpublisher_v3 (~> 0.3)
      google-apis-playcustomapp_v1 (~> 0.1)
      google-cloud-storage (~> 1.31)
      highline (~> 2.0)
      json (< 3.0.0)
      jwt (>= 2.1.0, < 3)
      mini_magick (>= 4.9.4, < 5.0.0)
      multipart-post (~> 2.0.0)
      naturally (~> 2.2)
      optparse (~> 0.1.1)
      plist (>= 3.1.0, < 4.0.0)
      rubyzip (>= 2.0.0, < 3.0.0)
      security (= 0.1.3)
      simctl (~> 1.6.3)
      terminal-notifier (>= 2.0.0, < 3.0.0)
      terminal-table (>= 1.4.5, < 2.0.0)
      tty-screen (>= 0.6.3, < 1.0.0)
      tty-spinner (>= 0.8.0, < 1.0.0)
      word_wrap (~> 1.0.0)
      xcodeproj (>= 1.13.0, < 2.0.0)
      xcpretty (~> 0.3.0)
      xcpretty-travis-formatter (>= 0.0.3)
    gh_inspector (1.1.3)
    google-apis-androidpublisher_v3 (0.16.0)
      google-apis-core (>= 0.4, < 2.a)
    google-apis-core (0.4.2)
      addressable (~> 2.5, >= 2.5.1)
      googleauth (>= 0.16.2, < 2.a)
      httpclient (>= 2.8.1, < 3.a)
      mini_mime (~> 1.0)
      representable (~> 3.0)
      retriable (>= 2.0, < 4.a)
      rexml
      webrick
    google-apis-iamcredentials_v1 (0.10.0)
      google-apis-core (>= 0.4, < 2.a)
    google-apis-playcustomapp_v1 (0.7.0)
      google-apis-core (>= 0.4, < 2.a)
    google-apis-storage_v1 (0.11.0)
      google-apis-core (>= 0.4, < 2.a)
    google-cloud-core (1.6.0)
      google-cloud-env (~> 1.0)
      google-cloud-errors (~> 1.0)
    google-cloud-env (1.5.0)
      faraday (>= 0.17.3, < 2.0)
    google-cloud-errors (1.2.0)
    google-cloud-storage (1.36.0)
      addressable (~> 2.8)
      digest-crc (~> 0.4)
      google-apis-iamcredentials_v1 (~> 0.1)
      google-apis-storage_v1 (~> 0.1)
      google-cloud-core (~> 1.6)
      googleauth (>= 0.16.2, < 2.a)
      mini_mime (~> 1.0)
    googleauth (1.1.0)
      faraday (>= 0.17.3, < 2.0)
      jwt (>= 1.4, < 3.0)
      memoist (~> 0.16)
      multi_json (~> 1.11)
      os (>= 0.9, < 2.0)
      signet (>= 0.16, < 2.a)
    highline (2.0.3)
    http-cookie (1.0.4)
      domain_name (~> 0.5)
    httpclient (2.8.3)
    i18n (1.9.1)
      concurrent-ruby (~> 1.0)
    jmespath (1.5.0)
    json (2.6.1)
    jwt (2.3.0)
    memoist (0.16.2)
    mini_magick (4.11.0)
    mini_mime (1.1.2)
    minitest (5.15.0)
    multi_json (1.15.0)
    multipart-post (2.0.0)
    nanaimo (0.3.0)
    naturally (2.2.1)
    nokogiri (1.13.1-x86_64-darwin)
      racc (~> 1.4)
    optparse (0.1.1)
    os (1.1.4)
    plist (3.6.0)
    public_suffix (4.0.6)
    racc (1.6.0)
    rake (13.0.6)
    representable (3.1.1)
      declarative (< 0.1.0)
      trailblazer-option (>= 0.1.1, < 0.2.0)
      uber (< 0.2.0)
    retriable (3.1.2)
    rexml (3.2.5)
    rouge (2.0.7)
    ruby2_keywords (0.0.5)
    rubyzip (2.3.2)
    security (0.1.3)
    signet (0.16.0)
      addressable (~> 2.8)
      faraday (>= 0.17.3, < 2.0)
      jwt (>= 1.5, < 3.0)
      multi_json (~> 1.10)
    simctl (1.6.8)
      CFPropertyList
      naturally
    slack-notifier (2.4.0)
    slather (2.7.2)
      CFPropertyList (>= 2.2, < 4)
      activesupport
      clamp (~> 1.3)
      nokogiri (~> 1.12)
      xcodeproj (~> 1.21)
    terminal-notifier (2.0.0)
    terminal-table (1.8.0)
      unicode-display_width (~> 1.1, >= 1.1.1)
    trailblazer-option (0.1.2)
    tty-cursor (0.7.1)
    tty-screen (0.8.1)
    tty-spinner (0.9.3)
      tty-cursor (~> 0.7)
    tzinfo (2.0.4)
      concurrent-ruby (~> 1.0)
    uber (0.1.0)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.8)
    unicode-display_width (1.8.0)
    webrick (1.7.0)
    word_wrap (1.0.0)
    xcodeproj (1.21.0)
      CFPropertyList (>= 2.3.3, < 4.0)
      atomos (~> 0.1.3)
      claide (>= 1.0.2, < 2.0)
      colored2 (~> 3.1)
      nanaimo (~> 0.3.0)
      rexml (~> 3.2.4)
    xcov (1.7.5)
      fastlane (>= 2.141.0, < 3.0.0)
      multipart-post
      slack-notifier
      terminal-table
      xcodeproj
      xcresult (~> 0.2.0)
    xcpretty (0.3.0)
      rouge (~> 2.0.7)
    xcpretty-travis-formatter (1.0.1)
      xcpretty (~> 0.2, >= 0.0.7)
    xcresult (0.2.1)

PLATFORMS
  x86_64-darwin-20

DEPENDENCIES
  fastlane
  slather
  xcov

BUNDLED WITH
   2.2.33
`

**Comment by ykhandelwal913** [comment]
@joshdholtz I think in some edge case this issue is happening , though i didnot have fastlane-plugin-trainer gem installed. I was getting this error intermittently earlier.
I just updated the fastlane again to latest, i am not able to reproduce this issue again. 
but as you mentioned, this error is too aggressive , is there any fix we can have for that? 
I am also trying to find out in which case it is failing.

**Comment by joshdholtz** [comment]
@ykhandelwal913 I'll take a look again later tonight and see how I can do things differently! Maybe I'll find a way to print out some warning text.

But if you are able to figure out what conditions this happens in that would be great! Is this happening locally or on a CI?

**Comment by ykhandelwal913** [comment]
@joshdholtz This is happening locally as well as on CI.

**Comment by ykhandelwal913** [comment]
@joshdholtz i am still trying to figure out in which case this is coming but this error block the build with error. Did you get chancee to take a look at that?

**Comment by takasurazeem** [comment]
Facing the same issue: ```[!] Migration Needed: As of 2.201.0, trainer is included in fastlane. Please remove the trainer plugin from your Gemfile or Pluginfile (or with 'gem uninstall fastlane-plugin-trainer') - More information: https://docs.fastlane.tools/best-practices/xcodebuild-formatters/```

Upon ```gem uninstall fastlane-plugin-trainer``` it says ```Gem 'fastlane-plugin-trainer' is not installed```
