### ISSUE TITLE
Could not find gem 'pry', needed by spaceship but only listed as dev-dependency

### ISSUE THREAD

**Issue by LinusU** [fastlane/fastlane#19881]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I've installed Fastlane via Homebrew which does:

```sh
gem build fastlane.gemspec
gem install fastlane-#{version}.gem --no-document
```

When later trying to run `fastlane spaceship login` I'm greeted with the following error:

```text
Could not find gem 'pry'

If you installed spaceship using `gem install spaceship` run
  gem install pry
to install the missing gem

If you use a Gemfile add this to your Gemfile:
  gem 'pry'
and run `bundle install`
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'pry' (>= 0) among 164 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/opt/homebrew/Cellar/fastlane/2.203.0/libexec' , execute `gem env` for more information
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:323:in `to_spec'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:987:in `find_by_name'
	from /opt/homebrew/Cellar/fastlane/2.203.0/libexec/gems/fastlane-2.203.0/spaceship/lib/spaceship/playground.rb:12:in `initialize'
	from /opt/homebrew/Cellar/fastlane/2.203.0/libexec/gems/fastlane-2.203.0/spaceship/lib/spaceship/commands_generator.rb:36:in `new'
	from /opt/homebrew/Cellar/fastlane/2.203.0/libexec/gems/fastlane-2.203.0/spaceship/lib/spaceship/commands_generator.rb:36:in `block (2 levels) in run'
	from /opt/homebrew/Cellar/fastlane/2.203.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/Cellar/fastlane/2.203.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/Cellar/fastlane/2.203.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/Cellar/fastlane/2.203.0/libexec/gems/fastlane-2.203.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.203.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.203.0/libexec/gems/fastlane-2.203.0/spaceship/lib/spaceship/commands_generator.rb:52:in `run'
	from /opt/homebrew/Cellar/fastlane/2.203.0/libexec/gems/fastlane-2.203.0/spaceship/lib/spaceship/commands_generator.rb:15:in `start'
	from /opt/homebrew/Cellar/fastlane/2.203.0/libexec/gems/fastlane-2.203.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	from /opt/homebrew/Cellar/fastlane/2.203.0/libexec/gems/fastlane-2.203.0/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/Cellar/fastlane/2.203.0/libexec/bin/fastlane:25:in `load'
	from /opt/homebrew/Cellar/fastlane/2.203.0/libexec/bin/fastlane:25:in `<main>'
```

I believe that is because `pry` is only listed as a _development_ dependency in the gem spec file here:

https://github.com/fastlane/fastlane/blob/bbdd8bbd2280aab2ddcd3ebe113159a9c9422f13/fastlane.gemspec#L121

##### Command executed

```
fastlane spaceship login
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> $ fastlane spaceship login                                                        
[✔] 🚀 
[22:45:13]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
Could not find gem 'pry'

If you installed spaceship using `gem install spaceship` run
  gem install pry
to install the missing gem

If you use a Gemfile add this to your Gemfile:
  gem 'pry'
and run `bundle install`
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'pry' (>= 0) among 164 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/opt/homebrew/Cellar/fastlane/2.203.0/libexec' , execute `gem env` for more information
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:323:in `to_spec'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:987:in `find_by_name'
	from /opt/homebrew/Cellar/fastlane/2.203.0/libexec/gems/fastlane-2.203.0/spaceship/lib/spaceship/playground.rb:12:in `initialize'
	from /opt/homebrew/Cellar/fastlane/2.203.0/libexec/gems/fastlane-2.203.0/spaceship/lib/spaceship/commands_generator.rb:36:in `new'
	from /opt/homebrew/Cellar/fastlane/2.203.0/libexec/gems/fastlane-2.203.0/spaceship/lib/spaceship/commands_generator.rb:36:in `block (2 levels) in run'
	from /opt/homebrew/Cellar/fastlane/2.203.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/Cellar/fastlane/2.203.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/Cellar/fastlane/2.203.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/Cellar/fastlane/2.203.0/libexec/gems/fastlane-2.203.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.203.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.203.0/libexec/gems/fastlane-2.203.0/spaceship/lib/spaceship/commands_generator.rb:52:in `run'
	from /opt/homebrew/Cellar/fastlane/2.203.0/libexec/gems/fastlane-2.203.0/spaceship/lib/spaceship/commands_generator.rb:15:in `start'
	from /opt/homebrew/Cellar/fastlane/2.203.0/libexec/gems/fastlane-2.203.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
	from /opt/homebrew/Cellar/fastlane/2.203.0/libexec/gems/fastlane-2.203.0/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/Cellar/fastlane/2.203.0/libexec/bin/fastlane:25:in `load'
	from /opt/homebrew/Cellar/fastlane/2.203.0/libexec/bin/fastlane:25:in `<main>'

 </pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 12.0.1                                                     |
| Ruby                        | 3.0.3                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.30.1 (Apple Git-130)                         |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.203.0/libexec/bin/fastlane |
| Host                        | macOS 12.0.1 (21A559)                                      |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.0.3/lib                        |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021                                |
| Is contained                | false                                                      |
| Is homebrew                 | true                                                       |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
| Xcode Version               | 13.1                                                       |
| Swift Version               | 5.5.1                                                      |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.203.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.90.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.3        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.9.3        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.5.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.32       |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.2        |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-androidpublisher_v3 | 0.15.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.11.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.36.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.5.0        |
| aws-partitions                  | 1.550.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-sdk-core                    | 3.125.5      |
| aws-sdk-kms                     | 1.53.0       |
| aws-sdk-s3                      | 1.111.3      |
| set                             | 1.0.1        |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.1        |
| date                            | 3.1.3        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.0        |
| uri                             | 0.10.1       |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.2.1        |
| digest                          | 3.0.0        |
| io-nonblock                     | 0.1.0        |
| io-wait                         | 0.2.0        |
| zlib                            | 2.0.0        |
| resolv                          | 0.2.1        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.1        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.7        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| net-http                        | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.2.1        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.2        |
</details>

*generated on:* **2022-01-31**
</details>

**Comment by Nebel69** [comment]
According to rubygems.org, jquery-rails 2.0.0 has been yanked. That explains the error you had with jquery-rails.
Running $ bundle update jquery-rails will rebuild your gem snapshot. That way you don't have to delete Gemfile.lock

**Comment by LinusU** [comment]
The issue is still present in 2.205.1:

```text
Could not find gem 'pry'

If you installed spaceship using `gem install spaceship` run
  gem install pry
to install the missing gem

If you use a Gemfile add this to your Gemfile:
  gem 'pry'
and run `bundle install`
```

> I would recommend using bundler for best compatibility!

Is this because dev-dependencies is also installed when running `bundle install`?

Installing via Brew is very very convenient for me, and I would prefer to keep doing that 😅 

It seems like the correct thing would be to make it a regular dependency instead of dev-dependency, since it's used by code paths in the final product, no?

**Comment by LinusU** [comment]
This issue is still present in 2.206.2:

```text
Could not find gem 'pry'

If you installed spaceship using `gem install spaceship` run
  gem install pry
to install the missing gem

If you use a Gemfile add this to your Gemfile:
  gem 'pry'
and run `bundle install`
```

This is with fastlane installed via `brew install fastlane`

**Comment by akring** [comment]
> 

Same problem here. Removed homebrew fastlane and reinstall it with `gem install fastlane` solved this problem. Still wired.
