### ISSUE TITLE
Undefined symbols for architecture arm64 fastlane Error 

### ISSUE THREAD

**Issue by dhimansham** [fastlane/fastlane#19894]
Hello team, I'm trying to upload build through GitHub action and fastlane. I'm stuck in the MapBox framework. I'm using Github LFS to upload the Mapbox framework. But in the last I'm getting error given below please check.

Warning:- ld: ignoring file /Users/runner/Library/Developer/Xcode/DerivedData/test-dplpvtipvtqvtobqpvumxtffttst/Build/Intermediates.noindex/ArchiveIntermediates/test/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/MapboxCoreMaps/MapboxCoreMaps.framework/MapboxCoreMaps, building for iOS-arm64 but attempting to link with file built for unknown-unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F )

Error:-

❌ Undefined symbols for architecture arm64
Symbol: OBJC_CLASS$_MBMLayerPosition
Referenced from: objc-class-ref in Style.o
❌ ld: symbol(s) not found for architecture arm64
❌ clang: error: linker command failed with exit code 1 (use -v to see invocation)

▸ Linking FirebaseCoreDiagnostics
** ARCHIVE FAILED **

The following build commands failed:
Ld /Users/runner/Library/Developer/Xcode/DerivedData/test-dplpvtipvtqvtobqpvumxtffttst/Build/Intermediates.noindex/ArchiveIntermediates/test/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/MapboxMaps.framework/MapboxMaps normal (in target 'MapboxMaps' from project 'Pods')
(1 failure)
[10:59:06]: Exit status: 65

[Stack-overflow question
](https://stackoverflow.com/questions/70942325/undefined-symbols-for-architecture-arm64-ios)
Question:- Can someone please explain to me how to solve this issue.

Can someone please explain to me How to get Progress?

Any help would be greatly appreciated.

Thanks in advance.

Please check fastlane env output

> <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                              |
| --------------------------- | -------------------------------------------------- |
| OS                          | 11.6                                               |
| Ruby                        | 3.0.0                                              |
| Bundler?                    | true                                               |
| Git                         | git version 2.32.0 (Apple Git-132)                 |
| Installation Source         | ~/.rvm/gems/ruby-3.0.0/bin/fastlane                |
| Host                        | macOS 11.6 (20G165)                                |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-3.0.0/lib                       |
| OpenSSL Version             | OpenSSL 1.1.1m  14 Dec 2021                        |
| Is contained                | false                                              |
| Is homebrew                 | false                                              |
| Is installed via Fabric.app | false                                              |
| Xcode Path                  | /Applications/Xcode 13.2.1.app/Contents/Developer/ |
| Xcode Version               | 13.2.1                                             |
| Swift Version               | 5.5.2                                              |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

DEVELOPER_APP_ID = ENV["DEVELOPER_APP_ID"]
DEVELOPER_APP_IDENTIFIER = ENV["DEVELOPER_APP_IDENTIFIER"]
DEVELOPER_APP_IDENTIFIER_EXTENSION = ENV["DEVELOPER_APP_IDENTIFIER_EXTENSION"]
PROVISIONING_PROFILE_SPECIFIER = ENV["PROVISIONING_PROFILE_SPECIFIER"]
PROVISIONING_PROFILE_SPECIFIER_EXTENSION = ENV["PROVISIONING_PROFILE_SPECIFIER_EXTENSION"]
TEMP_KEYCHAIN_USER = ENV["TEMP_KEYCHAIN_USER"]
TEMP_KEYCHAIN_PASSWORD = ENV["TEMP_KEYCHAIN_PASSWORD"]
APPLE_ISSUER_ID = ENV["APPLE_ISSUER_ID"]
APPLE_KEY_ID = ENV["APPLE_KEY_ID"]
APPLE_KEY_CONTENT = ENV["APPLE_KEY_CONTENT"]
GIT_AUTHORIZATION = ENV["GIT_AUTHORIZATION"]

def delete_temp_keychain(name)

  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

def create_temp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    unlock: false,
    timeout: 0
  )
end

def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end

platform :ios do
  lane :closed_beta do
    keychain_name = TEMP_KEYCHAIN_USER
    keychain_password = TEMP_KEYCHAIN_PASSWORD
    ensure_temp_keychain(keychain_name, keychain_password)

    api_key = app_store_connect_api_key(
      key_id: APPLE_KEY_ID,
      issuer_id: APPLE_ISSUER_ID,
      key_content: "#{ENV["APPLE_KEY_CONTENT"]}".gsub('\n', '\\n'),
is_key_content_base64:true,            
      duration: 1200,            
      in_house: false
    ) 

    increment_build_number(xcodeproj: "test.xcodeproj")

    match(
      type: 'appstore',
      app_identifier:["#{DEVELOPER_APP_IDENTIFIER}","#{DEVELOPER_APP_IDENTIFIER_EXTENSION}"],
      git_basic_authorization: Base64.strict_encode64(GIT_AUTHORIZATION),
      readonly: false,
      keychain_name: keychain_name,
      keychain_password: keychain_password,
      api_key: api_key
    )

    gym(
      configuration: "Release",
      scheme: "test",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: { 
            DEVELOPER_APP_ID => PROVISIONING_PROFILE_SPECIFIER,
            "#{DEVELOPER_APP_IDENTIFIER}" => PROVISIONING_PROFILE_SPECIFIER_EXTENSION
        }
      }
    )

    pilot(
      apple_id: "#{DEVELOPER_APP_ID}",
      app_identifier:["#{DEVELOPER_APP_IDENTIFIER}","#{DEVELOPER_APP_IDENTIFIER_EXTENSION}"],
      skip_waiting_for_build_processing: true,
      skip_submission: true,
      distribute_external: false,
      notify_external_testers: false,
      ipa: "./test.ipa"
    )

    delete_temp_keychain(keychain_name)
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier(ENV["DEVELOPER_APP_IDENTIFIER","DEVELOPER_APP_IDENTIFIER_EXTENSION"])
apple_id(ENV["FASTLANE_APPLE_ID"])
itc_team_id(ENV["APP_STORE_CONNECT_TEAM_ID"])
team_id(ENV["DEVELOPER_PORTAL_TEAM_ID"])

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.202.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| executable-hooks                | 1.6.1        |
| bundler-unload                  | 1.0.2        |
| rubygems-bundler                | 1.4.5        |
| bundler                         | 2.2.3        |
| pathname                        | 0.1.0        |
| set                             | 1.0.1        |
| tsort                           | 0.1.0        |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.550.0      |
| aws-sigv4                       | 1.4.0        |
| jmespath                        | 1.5.0        |
| aws-sdk-core                    | 3.125.5      |
| aws-sdk-kms                     | 1.53.0       |
| aws-sdk-s3                      | 1.111.3      |
| babosa                          | 1.0.4        |
| claide                          | 1.1.0        |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.90.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.0.0        |
| faraday-multipart               | 1.0.3        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.9.3        |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.3.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.0        |
| httpclient                      | 2.8.3        |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.2        |
| google-apis-androidpublisher_v3 | 0.15.0       |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.11.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.36.0       |
| json                            | 2.6.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
</details>

*generated on:* **2022-02-02**
</details>

**Sourcetree Github LFS Tracking files:-**

![Screenshot 2022-02-02 at 7 53 43 PM](https://user-images.githubusercontent.com/9291694/152172350-e801363c-80af-4c63-a7f1-9806fefb22b5.png)

**Comment by dhimansham** [comment]
@fastlane-bot Updated, Please check

@kommen @cbowns @lsegal Could you please check the attached question, i'm not able to build the app.

**Comment by yellowTiger** [comment]
I have the same problem

**Comment by mobileexpert1** [comment]
@yellowTiger Did you find any Solution?

**Comment by dhimansham** [comment]
@yellowTiger Did you find any solution?

**Comment by yellowTiger** [comment]
for me ,the error is reported by FMDB in pods,So I change  the
setting Build Active Architecture Only to NO

**Comment by mobileexpert1** [comment]
@yellowTiger ok i will try with your solution and update you. Thanks.

**Comment by myfordbenefits** [comment]
The issue is that the cocoapods have not been built for arm64 architecture yet thus they cannot be linked when you build them. Likely you cannot use those packages until they are updated and use that architecture. You can fix the linker error by going to project -> target (your project name) -> build settings and change architectures to standard architectures (armv7, armv7s), and valid architectures to armv7, armv7s.

**Comment by dhimansham** [comment]
@yellowTiger I have tried your code but still same issue.
 
@myfordbenefits I have tried to set architecture in build setting, but you can check the there is only Excluded architectures option the valid architectures is already depreciated. Could you please check the attached screenshot.  

![Screenshot 2022-02-04 at 12 46 36 PM](https://user-images.githubusercontent.com/33354025/152487706-cbf44819-b9a9-4f9c-a8f9-e910d0477acf.png)

**Comment by yellowTiger** [comment]
you should change it to No

**Comment by dhimansham** [comment]
@yellowTiger 

Please check, Correct or not ? 

![Screenshot 2022-02-04 at 1 22 39 PM](https://user-images.githubusercontent.com/9291694/152492042-f0359ffa-da76-48d8-96dd-244a8165ac94.png)

**Comment by yellowTiger** [comment]
I think you need add arm64 for the architecture ,just take a try

**Comment by dhimansham** [comment]
@yellowTiger Correct, if you not could you please correct me or if it's possible can you please add a screenshot. 
![Screenshot 2022-02-04 at 1 44 45 PM](https://user-images.githubusercontent.com/33354025/152494899-ab067a5a-b71a-4661-921f-ca2211b9ed11.png)

**Comment by dhimansham** [comment]
@yellowTiger,  I got the solution. it's my biggest mistake I was not used Github LFS fetch in the YML file. When I'm fetch LFS data first then uploading the build succeeded without any error.

Here is the Latest YML file:-

![Screenshot 2022-02-10 at 11 50 17 AM](https://user-images.githubusercontent.com/99244215/153349556-6f7ba086-3c00-44ad-a6df-55cb0ded6339.png)

@yellowTiger thanks for your help.
