### ISSUE TITLE
Xcov reports: 'minimum_coverage_percentage' value must be a Float! Found Integer instead.

### ISSUE THREAD

**Issue by sebspi** [fastlane/fastlane#19909]
### Issue Description
When not setting or setting an int value for "minimum_coverage_percentage" in xcov, I just got an error with "'minimum_coverage_percentage' value must be a Float! Found Integer instead.". 
If I am setting, e.g. 75.5, it works.

##### Command executed
`xcov(
          scheme: .userDefined(schemeRelease),
          outputDirectory: TestConfiguration.Xcov.outputDirectory,
          htmlReport: .userDefined(true),
          minimumCoveragePercentage: 75,
          ignoreFilePath: TestConfiguration.Xcov.ignoreFilePath,
          ideFoundationPath: TestConfiguration.Xcov.ideFoundationPath
        )`

### Environment
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 12.1                                        |
| Ruby                        | 3.0.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.32.0 (Apple Git-132)          |
| Installation Source         | ~/.rbenv/versions/3.0.3/bin/fastlane        |
| Host                        | macOS 12.1 (21C52)                          |
| Ruby Lib Dir                | ~/.rbenv/versions/3.0.3/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 13.2.1                                      |
| Swift Version               | 5.5.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

```ruby
import Foundation

class Fastfile: LaneFile {
    
    private let proj = "AppDemo.xcodeproj"
    private let workspace = "AppDemo.xcworkspace"
    private let schemeRelease = "AppDemo"
    private let schemeStaging = "AppDemoStaging"
    private let appIdentifierRelease = "de.App.AppDemo"
    private let appIdentifierStaging = "de.App.AppDemoStaging"
    
    private enum TestConfiguration {
        static let outputTypes = "junit"
        static let outputDirectory = "fastlane"
        static let outputFiles: OptionalConfigValue<String?> = .userDefined("junit-report.xml")
        static let devices: OptionalConfigValue<[String]?> = .userDefined([
            "iPhone 11"
        ])
        enum Slather {
            static let outputDirectory: OptionalConfigValue<String?> = .userDefined("fastlane")
            static let ignore: OptionalConfigValue<[String]?> = .userDefined(["../../*"])
        }
        enum Xcov {
            static let outputDirectory = "fastlane/xcov_output"
            static let ignoreFilePath = ".xcovignore"
            static let ideFoundationPath = "/Applications/Xcode.app/Contents/Developer/../Frameworks/IDEFoundation.framework/Versions/A/IDEFoundation"
        }
    }

    func testLane() {
        desc("Running test lane and creating test report...")
        runTests(
            scheme: .userDefined(schemeRelease),
            devices: TestConfiguration.devices,
            forceQuitSimulator: true,
            resetSimulator: true,
            reinstallApp: true,
            appIdentifier: .userDefined(appIdentifier),
            outputDirectory: TestConfiguration.outputDirectory,
            outputTypes: TestConfiguration.outputTypes,
            outputFiles: TestConfiguration.outputFiles
        )
        slather(
            proj: .userDefined(proj),
            workspace: .userDefined(workspace),
            scheme: .userDefined(schemeRelease),
            coberturaXml: .userDefined(true),
            outputDirectory: TestConfiguration.Slather.outputDirectory,
            ignore: TestConfiguration.Slather.ignore
        )
        xcov(
          scheme: .userDefined(schemeRelease),
          outputDirectory: TestConfiguration.Xcov.outputDirectory,
          htmlReport: .userDefined(true),
          minimumCoveragePercentage: 75.5,
          ignoreFilePath: TestConfiguration.Xcov.ignoreFilePath,
          ideFoundationPath: TestConfiguration.Xcov.ideFoundationPath
        )
    }
    
    func betaLane() {
    desc("Push a new beta build to TestFlight")
        incrementBuildNumber(xcodeproj: "AppDemo.xcodeproj")
        buildApp(workspace: "AppDemo.xcworkspace", scheme: "AppDemo")
        uploadToTestflight(username: "development@App.de")
    }
}

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.204.1 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.90.0       |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.32       |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.2        |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-androidpublisher_v3 | 0.16.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.11.0       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.36.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.5.0        |
| aws-partitions                  | 1.551.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-sdk-core                    | 3.125.6      |
| aws-sdk-kms                     | 1.53.0       |
| aws-sdk-s3                      | 1.111.3      |
| set                             | 1.0.1        |
| ruby2_keywords                  | 0.0.5        |
| faraday-retry                   | 1.0.3        |
| faraday-rack                    | 1.0.0        |
| faraday-patron                  | 1.0.0        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-net_http                | 1.0.1        |
| faraday-multipart               | 1.0.3        |
| faraday-httpclient              | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.9.3        |
| json                            | 2.6.1        |
| rake                            | 13.0.6       |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.1        |
| date                            | 3.1.3        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.0        |
| uri                             | 0.10.1       |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.2.1        |
| digest                          | 3.0.0        |
| io-nonblock                     | 0.1.0        |
| io-wait                         | 0.2.0        |
| zlib                            | 2.0.0        |
| resolv                          | 0.2.1        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.1        |
| rack                            | 2.2.3        |
| rack-test                       | 1.1.0        |
| fileutils                       | 1.5.0        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| tmpdir                          | 0.1.2        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.7        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| net-http                        | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| nokogiri                        | 1.12.5       |
| racc                            | 1.6.0        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.2.1        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.2        |
</details>

*generated on:* **2022-02-04**
</details>

**Comment by max-ott** [comment]
I think you solved your own issue! The value needs to be a `Float` and not an `Integer`, so using `75.0` should work as well!

**Comment by sebspi** [comment]
Hello,

no I am not solving it by myself. If you set it to 75.0 it throws the same error.

So there is a conversion error somewhere, which is cutting of the trailing 0.

So, please reopen the issue and have a look at this issue more carefully.
