### ISSUE TITLE
Could not find app with app identifier '###' in your App Store Connect account (### - Team: 100000)

### ISSUE THREAD

**Issue by dipak-s** [fastlane/fastlane#19902]
I am facing issue in the azure devops pipeline while building and deploying the code at app store. below are the error i am getting.

Could not find app with app identifier '###' in your App Store Connect account (### - Team: 100000)

Please do the needful for me.

**Comment by lenartowski** [comment]
I had the same problem. Try updating fastlane, version `2.204.1` has a (temporary?) fix for that.

**Comment by ljoraanstad** [comment]
+1, experiencing the same

**Comment by simonbourdon-illogika** [comment]
+1, experiencing the same

**Comment by jrounsav** [comment]
> I had the same problem. Try updating fastlane, version `2.204.1` has a (temporary?) fix for that.

@lenartowski  Ouch. Will give this a shot. Thank you

**Comment by dipak-s** [comment]
Thanks All. This solution is working for me for now,
