### ISSUE TITLE
Fastlane sign resign issue

### ISSUE THREAD

**Issue by git4ravi** [fastlane/fastlane#19919]
When I am trying to resign the unsigned IPA file, I am facing below issue while running below fastlane command.
 I am also using "CFBundleDisplayName" key and string in info.plist file
Command: fastlane sigh resign <ipa-filename.ipa> --signing_identity <name-of-certificate> --provisioning_profile <name-of-pp-file>

Error: 
15:43:12  Print: Entry, ":CFBundleDisplayName", Does Not Exist
15:43:12  cp: _floatsignTemp/Payload/<app_name>.app/embedded.mobileprovision: No such file or directory
15:43:12  _floatsignTemp/Payload/<app_name>.app: replacing existing signature
15:43:12  _floatsignTemp/Payload/<app_name>.app: errSecInternalComponent
15:43:12  Encountered an error, aborting!
15:43:12  
15:43:12  [15:43:12]: Something went wrong while code signing <ipa_file_name>.ipa
15:43:12  
[2022-02-06T21:43:12.218Z] [!] Failed to re-sign .ipa

Fastlane ENV
****************************
+ fastlane env
   [15:43:07]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
   [15:43:07]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
   [ ]: Generating fastlane environment output, this might take a few seconds...
   swift-driver version: 1.26.9 <details><summary>🚫 fastlane environment 🚫</summary>
   
   ### Stack
   
   | Key                         | Value                                                          |
   | --------------------------- | -------------------------------------------------------------- |
   | OS                          | 12.0.1                                                         |
   | Ruby                        | 2.6.8                                                          |
   | Bundler?                    | false                                                          |
   | Git                         | git version 2.30.1 (Apple Git-130)                             |
   | Installation Source         | /usr/local/bin/fastlane                                        |
   | Host                        | macOS 12.0.1 (21A559)                                          |
   | Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
   | OpenSSL Version             | LibreSSL 2.8.3                                                 |
   | Is contained                | false                                                          |
   | Is homebrew                 | false                                                          |
   | Is installed via Fabric.app | false                                                          |
   | Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
   | Xcode Version               | 13.1                                                           |
   | Swift Version               | 5.5.1                                                          |
   
   
   ### System Locale
   
   | Error                       |
   | --------------------------- |
   | No Locale with UTF8 found 🚫 |
   
   
   ### fastlane files:
   
   **No Fastfile found**
   
   
   **No Appfile found**
   
   
   ### fastlane gems
   
   | Gem      | Version | Update-Status  |
   | -------- | ------- | -------------- |
   | fastlane | 2.199.0 | 💥 Check failed |
   
   
   ### Loaded fastlane plugins:
   
   **No plugins Loaded**
   
   
   <details><summary><b>Loaded gems</b></summary>
   
   | Gem                             | Version |
   | ------------------------------- | ------- |

**Comment by git4ravi** [comment]
Can anyone please help what exactly I am missing ?

**Comment by max-ott** [comment]
Hey, please edit the issue following our issue template or re-open another issue for our community to be able to help you!
