### ISSUE TITLE
sh command with cocoapods

### ISSUE THREAD

**Issue by Disconnecter** [fastlane/fastlane#19921]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
error when trying run sh with pods

##### Command executed
sh "pod repo add test_frmwrk https://github.com/Disconnecter/framework_src.git"

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre> fastlane CI_pod_repo_init                                                                     zsh   100  11:53:25 
[✔] 🚀
[11:53:28]: fastlane detected a Gemfile in the current directory
[11:53:28]: However, it seems like you didn't use `bundle exec`
[11:53:28]: To launch fastlane faster, please use
[11:53:28]:
[11:53:28]: $ bundle exec fastlane CI_pod_repo_init
[11:53:28]:
[11:53:28]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
objc[15800]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x2114a6b90) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x103da02c8). One of the two will be used. Which one is undefined.
objc[15800]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x2114a6be0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x103da0318). One of the two will be used. Which one is undefined.
[11:53:29]: ------------------------------
[11:53:29]: --- Step: default_platform ---
[11:53:29]: ------------------------------
[11:53:29]: Driving the lane 'ios CI_pod_repo_init' 🚀
[11:53:29]: ----------------------------------------------------------------------------------------
[11:53:29]: --- Step: pod repo add test_frmwrk https://github.com/Disconnecter/framework_src.git ---
[11:53:29]: ----------------------------------------------------------------------------------------
[11:53:29]: $ pod repo add test_frmwrk https://github.com/Disconnecter/framework_src.git
[11:53:29]: ▸ /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1402:in `rescue in block in activate_dependencies': Could not find 'minitest' (>= 5.1) among 190 total gem(s) (Gem::MissingSpecError)
[11:53:29]: ▸ Checked in 'GEM_PATH=/opt/homebrew/Cellar/fastlane/2.204.2/libexec:/opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec' at: /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/specifications/activesupport-6.1.4.1.gemspec, execute `gem env` for more information
[11:53:29]: ▸ from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1399:in `block in activate_dependencies'
[11:53:29]: ▸ from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `each'
[11:53:29]: ▸ from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `activate_dependencies'
[11:53:29]: ▸ from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1370:in `activate'
[11:53:29]: ▸ from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1406:in `block in activate_dependencies'
[11:53:29]: ▸ from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `each'
[11:53:29]: ▸ from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `activate_dependencies'
[11:53:29]: ▸ from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1370:in `activate'
[11:53:29]: ▸ from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1406:in `block in activate_dependencies'
[11:53:29]: ▸ from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `each'
[11:53:29]: ▸ from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `activate_dependencies'
[11:53:29]: ▸ from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1370:in `activate'
[11:53:29]: ▸ from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems.rb:299:in `block in activate_bin_path'
[11:53:29]: ▸ from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems.rb:298:in `synchronize'
[11:53:29]: ▸ from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems.rb:298:in `activate_bin_path'
[11:53:29]: ▸ from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/bin/pod:23:in `<main>'
[11:53:29]: ▸ /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'minitest' (>= 5.1) among 190 total gem(s) (Gem::MissingSpecError)
[11:53:29]: ▸ Checked in 'GEM_PATH=/opt/homebrew/Cellar/fastlane/2.204.2/libexec:/opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec' , execute `gem env` for more information
[11:53:29]: ▸ from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1400:in `block in activate_dependencies'
[11:53:29]: ▸ from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `each'
[11:53:29]: ▸ from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `activate_dependencies'
[11:53:29]: ▸ from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1370:in `activate'
[11:53:29]: ▸ from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1406:in `block in activate_dependencies'
[11:53:29]: ▸ from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `each'
[11:53:29]: ▸ from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `activate_dependencies'
[11:53:29]: ▸ from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1370:in `activate'
[11:53:29]: ▸ from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1406:in `block in activate_dependencies'
[11:53:29]: ▸ from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `each'
[11:53:29]: ▸ from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `activate_dependencies'
[11:53:29]: ▸ from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1370:in `activate'
[11:53:29]: ▸ from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems.rb:299:in `block in activate_bin_path'
[11:53:29]: ▸ from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems.rb:298:in `synchronize'
[11:53:29]: ▸ from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems.rb:298:in `activate_bin_path'
[11:53:29]: ▸ from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/bin/pod:23:in `<main>'
+------------------+----------------------+
|              Lane Context               |
+------------------+----------------------+
| DEFAULT_PLATFORM | ios                  |
| PLATFORM_NAME    | ios                  |
| LANE_NAME        | ios CI_pod_repo_init |
+------------------+----------------------+
[11:53:29]: Exit status of command 'pod repo add test_frmwrk https://github.com/Disconnecter/framework_src.git' was 1 instead of 0.
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1402:in `rescue in block in activate_dependencies': Could not find 'minitest' (>= 5.1) among 190 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/opt/homebrew/Cellar/fastlane/2.204.2/libexec:/opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec' at: /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/specifications/activesupport-6.1.4.1.gemspec, execute `gem env` for more information
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1399:in `block in activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `each'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1370:in `activate'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1406:in `block in activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `each'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1370:in `activate'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1406:in `block in activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `each'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1370:in `activate'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems.rb:299:in `block in activate_bin_path'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems.rb:298:in `synchronize'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems.rb:298:in `activate_bin_path'
	from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/bin/pod:23:in `<main>'
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'minitest' (>= 5.1) among 190 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/opt/homebrew/Cellar/fastlane/2.204.2/libexec:/opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec' , execute `gem env` for more information
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1400:in `block in activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `each'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1370:in `activate'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1406:in `block in activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `each'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1370:in `activate'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1406:in `block in activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `each'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1370:in `activate'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems.rb:299:in `block in activate_bin_path'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems.rb:298:in `synchronize'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems.rb:298:in `activate_bin_path'
	from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/bin/pod:23:in `<main>'

+------+--------------------------------------+-------------+
|                     fastlane summary                      |
+------+--------------------------------------+-------------+
| Step | Action                               | Time (in s) |
+------+--------------------------------------+-------------+
| 1    | default_platform                     | 0           |
| 💥   | pod repo add test_frmwrk             | 0           |
|      | https://github.com/Disconnecter/fram |             |
+------+--------------------------------------+-------------+

[11:53:29]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

/opt/homebrew/Cellar/fastlane/2.204.2/libexec/gems/fastlane-2.204.2/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': \e[31m[!] Exit status of command 'pod repo add test_frmwrk https://github.com/Disconnecter/framework_src.git' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1402:in `rescue in block in activate_dependencies': Could not find 'minitest' (>= 5.1) among 190 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/opt/homebrew/Cellar/fastlane/2.204.2/libexec:/opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec' at: /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/specifications/activesupport-6.1.4.1.gemspec, execute `gem env` for more information
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1399:in `block in activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `each'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1370:in `activate'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1406:in `block in activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `each'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1370:in `activate'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1406:in `block in activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `each'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1370:in `activate'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems.rb:299:in `block in activate_bin_path'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems.rb:298:in `synchronize'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems.rb:298:in `activate_bin_path'
	from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/bin/pod:23:in `<main>'
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'minitest' (>= 5.1) among 190 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/opt/homebrew/Cellar/fastlane/2.204.2/libexec:/opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec' , execute `gem env` for more information
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1400:in `block in activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `each'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1370:in `activate'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1406:in `block in activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `each'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1370:in `activate'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1406:in `block in activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `each'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1388:in `activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems/specification.rb:1370:in `activate'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems.rb:299:in `block in activate_bin_path'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems.rb:298:in `synchronize'
	from /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/rubygems.rb:298:in `activate_bin_path'
	from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/bin/pod:23:in `<main>'
\e[0m
	from /opt/homebrew/Cellar/fastlane/2.204.2/libexec/gems/fastlane-2.204.2/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /opt/homebrew/Cellar/fastlane/2.204.2/libexec/gems/fastlane-2.204.2/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	from /opt/homebrew/Cellar/fastlane/2.204.2/libexec/gems/fastlane-2.204.2/fastlane/lib/fastlane/helper/sh_helper.rb:16:in `sh_no_action'
	from /opt/homebrew/Cellar/fastlane/2.204.2/libexec/gems/fastlane-2.204.2/fastlane/lib/fastlane/fast_file.rb:223:in `block in sh'
	from /opt/homebrew/Cellar/fastlane/2.204.2/libexec/gems/fastlane-2.204.2/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /opt/homebrew/Cellar/fastlane/2.204.2/libexec/gems/fastlane-2.204.2/fastlane/lib/fastlane/fast_file.rb:222:in `sh'
	from /opt/homebrew/Cellar/fastlane/2.204.2/libexec/gems/fastlane-2.204.2/fastlane/lib/fastlane/fast_file.rb:216:in `sh'
	from Fastfile:43:in `block (2 levels) in parsing_binding'
	from /opt/homebrew/Cellar/fastlane/2.204.2/libexec/gems/fastlane-2.204.2/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /opt/homebrew/Cellar/fastlane/2.204.2/libexec/gems/fastlane-2.204.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /opt/homebrew/Cellar/fastlane/2.204.2/libexec/gems/fastlane-2.204.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /opt/homebrew/Cellar/fastlane/2.204.2/libexec/gems/fastlane-2.204.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /opt/homebrew/Cellar/fastlane/2.204.2/libexec/gems/fastlane-2.204.2/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /opt/homebrew/Cellar/fastlane/2.204.2/libexec/gems/fastlane-2.204.2/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /opt/homebrew/Cellar/fastlane/2.204.2/libexec/gems/fastlane-2.204.2/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	from /opt/homebrew/Cellar/fastlane/2.204.2/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/Cellar/fastlane/2.204.2/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/Cellar/fastlane/2.204.2/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/Cellar/fastlane/2.204.2/libexec/gems/fastlane-2.204.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.204.2/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.204.2/libexec/gems/fastlane-2.204.2/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	from /opt/homebrew/Cellar/fastlane/2.204.2/libexec/gems/fastlane-2.204.2/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /opt/homebrew/Cellar/fastlane/2.204.2/libexec/gems/fastlane-2.204.2/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /opt/homebrew/Cellar/fastlane/2.204.2/libexec/gems/fastlane-2.204.2/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/Cellar/fastlane/2.204.2/libexec/bin/fastlane:25:in `load'
	from /opt/homebrew/Cellar/fastlane/2.204.2/libexec/bin/fastlane:25:in `<main>'</pre>
</details>

### Environment

<details>
  <pre> <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 12.1                                                       |
| Ruby                        | 3.0.3                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.32.0 (Apple Git-132)                         |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.204.2/libexec/bin/fastlane |
| Host                        | macOS 12.1 (21C52)                                         |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.0.3/lib                        |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021                                |
| Is contained                | false                                                      |
| Is homebrew                 | true                                                       |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
| Xcode Version               | 13.2.1                                                     |
| Swift Version               | 5.5.2                                                      |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
POD_FRMW_NAME = "test_frmwrk"

platform :ios do

  desc "Bump podspec version options bump_type patch, minor, major. patch by default. then run add_tag automaticaly"
  lane :pod_spec_bump do |options|
	version_bump_podspec(bump_type: options[:bump_type])
	add_tag
  end

  desc "Adding tag related podspec version and push to repo. then run push_spec automaticaly"
  lane :add_tag do 
	add_git_tag(tag: lane_context[SharedValues::PODSPEC_VERSION_NUMBER])
	push_git_tags
	push_spec
  end

  desc "Commit and push podspec to repo + pod repo push"
  lane :push_spec do 
	git_commit(path: "./POD_FRMW_NAME.podspec", message: "Podspec Version Bump")
	push_to_git_remote
	sh "pod repo push POD_FRMW_NAME --allow-warnings"
  end

	desc "Init pod repo"
  lane :CI_pod_repo_init do
  sh "pod repo add test_frmwrk https://github.com/Disconnecter/framework_src.git"
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.204.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.91.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.3        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.9.3        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.5.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.32       |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.2        |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-androidpublisher_v3 | 0.16.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.11.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.36.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.5.0        |
| aws-partitions                  | 1.552.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-sdk-core                    | 3.126.0      |
| aws-sdk-kms                     | 1.54.0       |
| aws-sdk-s3                      | 1.112.0      |
| set                             | 1.0.1        |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.1        |
| date                            | 3.1.3        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.0        |
| uri                             | 0.10.1       |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.2.1        |
| digest                          | 3.0.0        |
| io-nonblock                     | 0.1.0        |
| io-wait                         | 0.2.0        |
| zlib                            | 2.0.0        |
| resolv                          | 0.2.1        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.1        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.7        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| net-http                        | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.2.1        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.2        |
</details>

*generated on:* **2022-02-07**
 </pre>
</details>

**Comment by iAgentur** [comment]
it's not related to fastlane at all: auth is required to access this repo as it's private.

either add credentials to keychain beforehand like cocoapods do (check on local machine) or use SSH with proper key.
