### ISSUE TITLE
Build made by fastlane in Testflight has no DSYM download link

### ISSUE THREAD

**Issue by lowfreq2010** [fastlane/fastlane#19925]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I am experiencing strange problem with builds made with fastlane. Since last Moday all builds uploaded successfully toi Testflight have no DSYMs, although, Testflight metadata says Symbols included - yes and there is no link to download them from appstoreconnect. Also, lane to download DSYM files from appstoreconnect infinitely waits for DSYMs to show up. But, if i build and uopload archive within xcode - then DSYMs download link is shown up correctly. We're using bitcode and downloading bitcode-processed DSYM files is cruicial step for us because otherwise we cannot symbolicate crashes in crashlytic.

I haven't changed anything in our fastlane fastfile usied for build and deliver, only updated fastlane. Our CI process is completely disrupted because as of now we have to upload everything manually. Please, advise what's wrong and how to correct it.

##### Command executed

we build archive with the following command which does not produce any error per se, just the final result is wrong

  build_app(export_method: "app-store",
            scheme: "KubanKredit",
            include_bitcode: true,
            include_symbols: true,
            xcargs: "-allowProvisioningUpdates")

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 12.1                                        |
| Ruby                        | 3.0.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.34.1                          |
| Installation Source         | ~/.rvm/gems/ruby-3.0.0/bin/fastlane         |
| Host                        | macOS 12.1 (21C52)                          |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-3.0.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 13.2.1                                      |
| Swift Version               | 5.5.2                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

#### RELEASE TARGET ###

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate code for assets, storyboards and mocks"
  lane :code_generation do
    sh "../Pods/SwiftGen/bin/swiftgen config run --config ../swiftgen.yml"
    sh "../Pods/Sourcery/bin/sourcery --config ../sourcery.yml"
  end
end

build_number = nil
version_number = nil

desc "Инкремент номера билда для тестфлайта"
lane :incrementBNTF do

  version_number = get_version_number(xcodeproj: "KubanKredit.xcodeproj",
                                      target: "KubanKredit")
  build_number = latest_testflight_build_number(version: version_number,
                                                app_identifier: "ru.kubankredit.mobilebanking").to_i
  increment_build_number({ build_number: build_number + 1 })

end

desc "Отправляем свежий билд в тестфлайт"
lane :send2TF do

  api_key = app_store_connect_api_key(
    key_id: "636CRDDJ2R",
    issuer_id: "69a6de83-5d9c-47e3-e053-5b8c7c11a4d1",
    key_filepath: "./fastlane/AuthKey_636CRDDJ2R.p8",
    duration: 1200, # optional (maximum 1200)
    in_house: false # optional but may be required if using match/sigh
  )

  pilot(api_key: api_key)

end


lane :refresh_dsyms do
  api_key = app_store_connect_api_key(
    key_id: "636CRDDJ2R",
    issuer_id: "69a6de83-5d9c-47e3-e053-5b8c7c11a4d1",
    key_filepath: "./fastlane/AuthKey_636CRDDJ2R.p8",
    duration: 1200, # optional (maximum 1200)
    in_house: false # optional but may be required if using match/sigh
  )

  download_dsyms(api_key: api_key,
    app_identifier: "ru.kubankredit.mobilebanking",
    version: "latest",
    build_number: build_number,
    wait_for_dsym_processing: true,
    wait_timeout: 10800)   # Download dSYM files from iTC
end

desc "отправка DSYM в крашлитик "
lane :upload2crashlytic do
    dsyms = lane_context[SharedValues::DSYM_PATHS][0]
    upload_symbols_to_crashlytics(dsym_path: dsyms,
                              gsp_path:"./Firebase/GoogleService-Info-prod.plist")
end

desc "clean up "
lane :cleanup do
  clean_build_artifacts
end

desc "dsyms to crashlytic "
lane :dsyms_upload do
  refresh_dsyms
  upload2crashlytic
  cleanup
end

desc "Отправляем свежий билд в аппстор"
lane :appstorego do

  api_key = app_store_connect_api_key(
    key_id: "636CRDDJ2R",
    issuer_id: "69a6de83-5d9c-47e3-e053-5b8c7c11a4d1",
    key_filepath: "./fastlane/AuthKey_636CRDDJ2R.p8",
    duration: 1200, # optional (maximum 1200)
    in_house: false # optional but may be required if using match/sigh
  )

  deliver(submit_for_review: true,
          app_identifier: "ru.kubankredit.mobilebanking",
          force: true,
          api_key: api_key,
          automatic_release: false,
          skip_metadata: true,
          skip_screenshots: true,
          app: 895734191)

end

desc "собираем свежий релизный билд для ТЕстФлайт"
lane :build4TF do

  unlock_keychain(
      path: "~/Library/Keychains/login.keychain-db",
      password: "Qwerty12345"
    )

  clear_derived_data
  build_app(export_method: "app-store",
            scheme: "KubanKredit",
            include_bitcode: true,
            include_symbols: true,
            xcargs: "-allowProvisioningUpdates")

end


desc "Команда для отправки на тестирование в тестфлайт"
lane :beta do

  incrementBNTF
  build4TF
  send2TF
  refresh_dsyms
  upload2crashlytic
  cleanup 

end

desc "Команда для загрузки релиза в Аппстор"
lane :release do

  incrementBNTF
  clear_derived_data
  build4TF
  appstorego
  refresh_dsyms
  upload2crashlytic
  cleanup 

end


desc "changelog"
lane :changelog do

changelog_from_git_commits(
  pretty: "- %s %b",# Optional, lets you provide a custom format to apply to each commit when generating the changelog text
  date_format: "short",# Optional, lets you provide an additional date format to dates within the pretty-formatted string
  match_lightweight_tag: false,  # Optional, lets you ignore lightweight (non-annotated) tags when searching for the last tag
  merge_commit_filtering: "exclude_merges" # Optional, lets you filter out merge commits
)

end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby

apple_id("www.kubankredit.ru@gmail.com") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.204.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| bundler                         | 2.2.29       |
| tsort                           | 0.1.0        |
| set                             | 1.0.1        |
| uri                             | 0.10.1       |
| pathname                        | 0.1.0        |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| concurrent-ruby                 | 1.1.9        |
| i18n                            | 1.8.11       |
| minitest                        | 5.15.0       |
| tzinfo                          | 2.0.4        |
| zeitwerk                        | 2.5.3        |
| activesupport                   | 6.1.4.4      |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| httpclient                      | 2.8.3        |
| json                            | 2.6.1        |
| algoliasearch                   | 1.27.5       |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.553.0      |
| aws-sigv4                       | 1.4.0        |
| jmespath                        | 1.5.0        |
| aws-sdk-core                    | 3.126.0      |
| aws-sdk-kms                     | 1.54.0       |
| aws-sdk-s3                      | 1.112.0      |
| babosa                          | 1.0.4        |
| claide                          | 1.0.3        |
| fuzzy_match                     | 2.0.4        |
| nap                             | 1.1.0        |
| netrc                           | 0.11.0       |
| ffi                             | 1.15.5       |
| ethon                           | 0.15.0       |
| typhoeus                        | 1.4.0        |
| cocoapods-core                  | 1.11.2       |
| cocoapods-deintegrate           | 1.0.5        |
| cocoapods-downloader            | 1.5.1        |
| cocoapods-plugins               | 1.0.0        |
| cocoapods-search                | 1.0.1        |
| cocoapods-trunk                 | 1.6.0        |
| cocoapods-try                   | 1.2.0        |
| colored2                        | 3.1.2        |
| escape                          | 0.0.4        |
| fourflusher                     | 2.3.1        |
| gh_inspector                    | 1.1.3        |
| molinillo                       | 0.8.0        |
| ruby-macho                      | 2.5.1        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| cocoapods                       | 1.11.2       |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.91.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.0.0        |
| faraday-multipart               | 1.0.3        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.9.3        |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| jwt                             | 2.3.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.0        |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.2        |
| google-apis-androidpublisher_v3 | 0.16.0       |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.11.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.36.0       |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| terminal-table                  | 1.4.5        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| git                             | 1.2.9.1      |
| liquid                          | 4.0.0        |
| thor                            | 0.19.1       |
| generamba                       | 1.5.0        |
| slack-notifier                  | 2.4.0        |
| wannabe_bool                    | 0.7.1        |
| xcode-install                   | 2.8.0        |
| xcresult                        | 0.2.1        |
| xcov                            | 1.7.5        |
</details>

*generated on:* **2022-02-08**
</details></pre>
</details>

**Comment by lowfreq2010** [comment]
the problem has been resolved since i added include_symbols: true parameter to Build_app call. Althith, it worked without this parameter fine in the past, now it seesm to be mandatory parameter to make it work properly.

**Comment by mmdock** [comment]
@lowfreq2010 this might not be that either.  All my builds the last few days haven't been generating dsyms even when manually uploading.  Since thursday last week

**Comment by lowfreq2010** [comment]
@mmdock seems like the issues is back again even with all parameters supplied and all updates installed. So, the question is who or what is the culprit ? and how we can workaround this problem?

**Comment by lowfreq2010** [comment]
i filed a complain to Apple Tech Support about this problem and suggest that everybody with this problem do the same

**Comment by lowfreq2010** [comment]
just tried to upload build with xcode and DSYM download link has been created and shown in appstoreconnect. So, definitely problem lies within fastlane. Anyone out there, experiencing the same problem?

**Comment by MaatheusGois** [comment]
Here we have same issue 🤕

**Comment by lowfreq2010** [comment]
> Here we have same issue 🤕

@MaatheusGois , the same issue even with xcode-delivered builds? I am unable to get DSYMs even in xcode... Seems like something, somewhere is completely broken.

**Comment by distomin** [comment]
@lowfreq2010 I wrote to Apple support yesterday. Now I see symbols in all last builds.

**Comment by lowfreq2010** [comment]
> @lowfreq2010 I wrote to Apple support yesterday. Now I see symbols in all last builds.

@distomin, and new builds made with fastlane have download link too?

**Comment by lowfreq2010** [comment]
seems like after writing to apple's support fastlane is working properly again. at least, i was able to run fastlane script properly from start to finish, including downloading DSYMs step

**Comment by MaatheusGois** [comment]
Here, after 6 hours, DSYMs appear in Apple Connect 👍🏻

**Comment by kolesnikovakate** [comment]
Same issue, no DSYMs links for fastlane builds. I tried to upload build manually by xcode and DSYM download link has been appeared. For me it's fastlane related problem 😕

**Comment by distomin** [comment]
Works like a charm in today's build. As we are using fastlane I think it's definetely not a Fastlane issue.

**Comment by max-ott** [comment]
Please check out https://twitter.com/joshdholtz/status/1491236404667781120?s=21

This is not a `fastlane` issue, but a bigger issue on Apple's side. Closing for now as it seems to be resolved.
