### ISSUE TITLE
Fastlane is freezing when trying to upload to Testflight

### ISSUE THREAD

**Issue by lucswart** [fastlane/fastlane#19920]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm trying to upload my iOS file to Testflight with Fastlane. It all works fine for the android part. However, when it finished building for iOS and tries to upload it it gets stuck on my M1 Macbook.

The weird thing that happens then is that internet doesn't work anymore on my macbook. It's basically stuck somehow and I have to restart it to get it to work again.

I've tried multiple times, 5 or so, and 1 of them succeed. The other tries got stuck.
![Screenshot 2022-02-06 at 12 14 30](https://user-images.githubusercontent.com/66739939/152763806-09283c96-874b-4d62-b6c6-f3047cfce9a0.png)
![Screenshot 2022-02-06 at 12 13 46](https://user-images.githubusercontent.com/66739939/152763808-4d56c458-d76d-4989-b929-19f98e281f5b.png)

##### Command executed

`cd ./ios && bundle exec fastlane beta`

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 12.1                                                       |
| Ruby                        | 3.0.3                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.30.1 (Apple Git-130)                         |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.204.2/libexec/bin/fastlane |
| Host                        | macOS 12.1 (21C52)                                         |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.0.3/lib                        |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021                                |
| Is contained                | false                                                      |
| Is homebrew                 | true                                                       |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
| Xcode Version               | 13.1                                                       |
| Swift Version               | 5.5.1                                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.204.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.91.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.3        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.9.3        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.5.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.32       |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.2        |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-androidpublisher_v3 | 0.16.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.11.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.36.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.5.0        |
| aws-partitions                  | 1.552.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-sdk-core                    | 3.126.0      |
| aws-sdk-kms                     | 1.54.0       |
| aws-sdk-s3                      | 1.112.0      |
| set                             | 1.0.1        |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.1        |
| date                            | 3.1.3        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.0        |
| uri                             | 0.10.1       |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.2.1        |
| digest                          | 3.0.0        |
| io-nonblock                     | 0.1.0        |
| io-wait                         | 0.2.0        |
| zlib                            | 2.0.0        |
| resolv                          | 0.2.1        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.1        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.7        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| net-http                        | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.2.1        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.2        |
</details>

*generated on:* **2022-02-07**
</details>

**Comment by lucswart** [comment]
I think related to https://github.com/fastlane/fastlane/issues/19852, gonna try if suggested fixes work.

**Comment by lucswart** [comment]
Update: after updating xcode command line tools error stil persists.

**Comment by max-ott** [comment]
Can you post the full error of the time out?

**Comment by Stephan-FDG** [comment]
I encountered the same problem. 
Are you by any chance still on macOS Big Sur?

**Comment by lucswart** [comment]
I'm running Monterey 12.2!

**Comment by lucswart** [comment]
@Stephan-FDG Maybe this temp fix can work: https://github.com/fastlane/fastlane/issues/19775#issuecomment-1010182598, haven't tried is myself yet.

**Comment by jkiter** [comment]
I am having the same issue. Listed below is the output when I run fastlane beta --verbose. The interesting thing is it runs just fine when I run the same command on the server itself using terminal. 

When I run it on terminal, I noticed it added arch and rosetta settings. 
DEBUG [2022-02-14 16:56:00.00]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 12.0.1 (x86_64); jvm=14.0.2+12-iTunesOpenJDK-8; jre=14.0.2+12-iTunesOpenJDK-8; arch=arm64; rosetta=true

OUTPUT for fastlane beta --verbose
INFO [2022-02-14 16:06:09.19]: [32m[32mAll required keys, certificates and provisioning profiles are installed 🙌[0m
INFO [2022-02-14 16:06:09.19]: Setting Provisioning Profile type to 'app-store'
INFO [2022-02-14 16:06:09.20]: [32m----------------------------------[0m
INFO [2022-02-14 16:06:09.20]: [32m--- Step: upload_to_testflight ---[0m
INFO [2022-02-14 16:06:09.20]: [32m----------------------------------[0m
INFO [2022-02-14 16:06:09.20]: Creating authorization token for App Store Connect API
DEBUG [2022-02-14 16:06:09.20]: App identifier (com.#####.app)
INFO [2022-02-14 16:06:11.10]: [32mReady to upload new build to TestFlight (App: ######)...[0m
DEBUG [2022-02-14 16:06:11.10]: App Platform (ios)
INFO [2022-02-14 16:06:11.99]: [32mWrote XML data to '/var/folders/q7/#####'[0m
INFO [2022-02-14 16:06:12.02]: Going to upload updated app to App Store Connect
INFO [2022-02-14 16:06:12.02]: [32mThis might take a few minutes. Please don't interrupt the script.[0m
DEBUG [2022-02-14 16:06:12.02]: xcrun iTMSTransporter -m upload -jwt YourJWT -assetFile /var/folders/q7/####.ipa -k 100000 2>&1
DEBUG [2022-02-14 16:06:15.74]: [Transporter]: INFO: Configuring logging...
DEBUG [2022-02-14 16:06:15.75]: [Transporter]: INFO: Logging level set to eXtreme
DEBUG [2022-02-14 16:06:18.58]: [Transporter]: DEBUG: SMART-CLIENT: initializing data center locking ops: [authenticateForSession, validateAssets]
DEBUG [2022-02-14 16:06:18.62]: [Transporter]: DEBUG: SMART-CLIENT: initializing data centers with: [contentdelivery02.itunes.apple.com, contentdelivery01.itunes.apple.com]
DEBUG [2022-02-14 16:06:18.62]: [Transporter]: INFO: iTMSTransporter : iTunes Store Transporter [2.3.0]
DEBUG [2022-02-14 16:06:18.62]: [Transporter]: INFO: OS identifier: Mac OS X 12.0.1 (x86_64); jvm=14.0.2+12-iTunesOpenJDK-8; jre=14.0.2+12-iTunesOpenJDK-8
DEBUG [2022-02-14 16:06:18.63]: [Transporter]: INFO: Memory: [JVM] 999M free, 1024M total, 2048M max [System] (Physical) 189M free, 16384M total (Swap) 0 free, 0 total
DEBUG [2022-02-14 16:06:18.63]: [Transporter]: DBG-X: Memory: [JVM] 998M free, 1024M total, 2048M max [System] (Physical) 188M free, 16384M total (Swap) 0 free, 0 total
DEBUG [2022-02-14 16:06:18.64]: [Transporter]: DBG-X: Using operation named: authenticateForSession
DEBUG [2022-02-14 16:06:18.67]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2022-02-14 16:06:18.67]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2022-02-14 16:06:18.67]: [Transporter]: DBG-X:   parameter BaseVersion = 2.1.0
DEBUG [2022-02-14 16:06:18.67]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 12.0.1 (x86_64); jvm=14.0.2+12-iTunesOpenJDK-8; jre=14.0.2+12-iTunesOpenJDK-8
DEBUG [2022-02-14 16:06:18.67]: [Transporter]: DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2022-02-14T16:06:18-06:00
DEBUG [2022-02-14 16:06:18.67]: [Transporter]: DBG-X:   parameter StatisticsPreviousCallDurationInSecs = 0.224969167
DEBUG [2022-02-14 16:06:18.67]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -jwt **hidden value** -assetFile /var/folders/q7/####.ipa -k 100000
DEBUG [2022-02-14 16:06:18.67]: [Transporter]: DBG-X:   parameter Version = 2.3.0
DEBUG [2022-02-14 16:06:18.67]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
DEBUG [2022-02-14 16:06:18.67]: [Transporter]: INFO: id = ####
DEBUG [2022-02-14 16:06:18.68]: [Transporter]: DEBUG: SMART-CLIENT: getCurrent(); current data center is null
DEBUG [2022-02-14 16:06:18.68]: [Transporter]: DEBUG: SMART-CLIENT: getCurrent(); iterator was null, setting it
DEBUG [2022-02-14 16:06:18.68]: [Transporter]: DEBUG: SMART-CLIENT: getCurrent(); setting current data center to: contentdelivery02.itunes.apple.com
DEBUG [2022-02-14 16:06:18.68]: [Transporter]: INFO: iTMSTransporter Correlation Key: ####
DEBUG [2022-02-14 16:06:18.69]: [Transporter]: DEBUG: SMART-CLIENT: Host HTTP header: contentdelivery02.itunes.apple.com
DEBUG [2022-02-14 16:06:19.40]: [Transporter]: DEBUG: SMART-CLIENT: pinning data center to: contentdelivery02.itunes.apple.com
DEBUG [2022-02-14 16:06:19.40]: [Transporter]: DBG-X: Apple's web service operation return value:
DEBUG [2022-02-14 16:06:19.40]: [Transporter]: DBG-X:   parameter SharedSecret = **hidden value**
DEBUG [2022-02-14 16:06:19.40]: [Transporter]: DBG-X:   parameter MultipartUploadsEnabled = true
DEBUG [2022-02-14 16:06:19.40]: [Transporter]: DBG-X:   parameter EnableJWTForAllCalls = false
DEBUG [2022-02-14 16:06:19.41]: [Transporter]: DBG-X:   parameter TxHeaders = {jenga=true}
DEBUG [2022-02-14 16:06:19.41]: [Transporter]: DBG-X:   parameter ShouldUseFeatures = (null)
DEBUG [2022-02-14 16:06:19.41]: [Transporter]: DBG-X:   parameter SessionExpiration = 2022-02-18T22:06:18.853Z
DEBUG [2022-02-14 16:06:19.41]: [Transporter]: DBG-X:   parameter SessionId = ####==
DEBUG [2022-02-14 16:06:19.41]: [Transporter]: DBG-X:   parameter ShouldUseRESTAPIs = false
DEBUG [2022-02-14 16:06:19.41]: [Transporter]: DBG-X:   parameter StreamingSettings = {LogStreamingEnabled=true, MultipartUploadsEnabled=true, AssetDescriptionStreamingEnabled=false}
DEBUG [2022-02-14 16:06:28.96]: [Transporter]: DBG-X: Using operation named: lookupSoftwareForBundleId
DEBUG [2022-02-14 16:06:28.96]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2022-02-14 16:06:28.96]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2022-02-14 16:06:28.96]: [Transporter]: DBG-X:   parameter BaseVersion = 2.1.0
DEBUG [2022-02-14 16:06:28.96]: [Transporter]: DBG-X:   parameter BundleId = com.####.app
DEBUG [2022-02-14 16:06:28.96]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 12.0.1 (x86_64); jvm=14.0.2+12-iTunesOpenJDK-8; jre=14.0.2+12-iTunesOpenJDK-8
DEBUG [2022-02-14 16:06:28.96]: [Transporter]: DBG-X:   parameter SoftwareTypeEnum = ios
DEBUG [2022-02-14 16:06:28.96]: [Transporter]: DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2022-02-14T16:06:28-06:00
DEBUG [2022-02-14 16:06:28.96]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -jwt **hidden value** -assetFile /var/folders/q7/####.ipa -k 100000
DEBUG [2022-02-14 16:06:28.96]: [Transporter]: DBG-X:   parameter Version = 2.3.0
DEBUG [2022-02-14 16:06:28.96]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
DEBUG [2022-02-14 16:06:28.96]: [Transporter]: INFO: id = ####
DEBUG [2022-02-14 16:06:28.96]: [Transporter]: DEBUG: SMART-CLIENT: getCurrent(); using pinned data center = contentdelivery02.itunes.apple.com
DEBUG [2022-02-14 16:06:28.96]: [Transporter]: INFO: iTMSTransporter Correlation Key: ####
DEBUG [2022-02-14 16:06:28.96]: [Transporter]: DEBUG: SMART-CLIENT: Host HTTP header: contentdelivery02.itunes.apple.com
DEBUG [2022-02-14 16:06:29.71]: [Transporter]: DBG-X: Apple's web service operation return value:
DEBUG [2022-02-14 16:06:29.71]: [Transporter]: DBG-X:   parameter ProviderPublicId = ####
DEBUG [2022-02-14 16:06:29.71]: [Transporter]: DBG-X:   parameter DisplayKeys = [Application, Version Number, SKU Number, Primary Language, Copyright, Type, Apple ID]
DEBUG [2022-02-14 16:06:29.71]: [Transporter]: DBG-X:   parameter EnableJWTForAllCalls = false

**Comment by jkiter** [comment]
I believe that it is an issue with xcrun iTMSTransporter. I used xcrun altool  and it worked just fine. 

Anybody know what is the difference between iTMSTransporter and altool and why one vs the other one would work?

**Comment by jkiter** [comment]
@lucswart  did you ever get this resolved?

**Comment by lucswart** [comment]
@jkiter No unfortunately not...

**Comment by Stephan-FDG** [comment]
I was finally able to Updating to Monetary and also updating Xcode additional components and now I am able to run fastlane successfully via terminal 

But issue still persists with when running the same fastlane file via Jenkins

I think there are some configuration issues on my end but I don't know what's causing it yet

**Comment by Stephan-FDG** [comment]
I saw that the ticket is closed but I am still having this issue.
When I run the fast file in Terminal everything seems fine but inside my CI-Tool it sill stuck on upload_to_testflight

I compared the debug logs and the only difference is that the Terminal seems to have more Physical Memory than when I run it with Jenkins.

Can this be the issue?

### **On Jenkins:**

`DEBUG [2022-03-21 20:55:33.59]: [Transporter]: INFO: Memory: [JVM] 997M free, 1024M total, 2048M max [System] (Physical) 96M free, 8192M total (Swap) 1150M free, 3072M total
DEBUG [2022-03-21 20:55:33.60]: [Transporter]: DBG-X: Memory: [JVM] 997M free, 1024M total, 2048M max [System] (Physical) 95M free, 8192M total (Swap) 1150M free, 3072M total`

### In Terminal
`DEBUG [2022-03-22 11:31:21.41]: [Transporter]: INFO: Memory: [JVM] 998M free, 1024M total, 2048M max [System] (Physical) 150M free, 8192M total (Swap) 1356M free, 4096M total
DEBUG [2022-03-22 11:31:21.42]: [Transporter]: DBG-X: Memory: [JVM] 998M free, 1024M total, 2048M max [System] (Physical) 150M free, 8192M total (Swap) 1356M free, 4096M total`



<details>
  <summary>Here is the Complete Jenkins log, where it stuck on the last line</summary>
INFO [2022-03-21 20:55:17.31]: [32m----------------------------------[0m
INFO [2022-03-21 20:55:17.31]: [32m--- Step: upload_to_testflight ---[0m
INFO [2022-03-21 20:55:17.31]: [32m----------------------------------[0m
INFO [2022-03-21 20:55:17.31]: Creating authorization token for App Store Connect API
DEBUG [2022-03-21 20:55:17.33]: App identifier (###)
INFO [2022-03-21 20:55:21.03]: [32mReady to upload new build to TestFlight (App: 1543687361)...[0m
DEBUG [2022-03-21 20:55:21.07]: App Platform (ios)
INFO [2022-03-21 20:55:23.75]: [32mWrote XML data to '/var/folders/3j/prd8ybks5kqgcz3qs5b3ggxr0000gp/T/d20220321-34590-bvh7vo/1543687361-2c9d4e34-3d4d-4c55-a3d2-529b37880493.itmsp'[0m
INFO [2022-03-21 20:55:24.37]: Going to upload updated app to App Store Connect
INFO [2022-03-21 20:55:24.37]: [32mThis might take a few minutes. Please don't interrupt the script.[0m
DEBUG [2022-03-21 20:55:24.37]: xcrun iTMSTransporter -m upload -jwt YourJWT -assetFile /var/folders/3j/prd8ybks5kqgcz3qs5b3ggxr0000gp/T/e75d96a3-ffb8-4109-af0e-6ee13a481232.ipa -k 100000 2>&1
DEBUG [2022-03-21 20:55:30.39]: [Transporter]: INFO: Configuring logging...
DEBUG [2022-03-21 20:55:30.40]: [Transporter]: INFO: Logging level set to eXtreme
DEBUG [2022-03-21 20:55:33.54]: [Transporter]: DEBUG: SMART-CLIENT: initializing data center locking ops: [authenticateForSession, validateAssets]
DEBUG [2022-03-21 20:55:33.59]: [Transporter]: DEBUG: SMART-CLIENT: initializing data centers with: [contentdelivery01.itunes.apple.com, contentdelivery02.itunes.apple.com]
DEBUG [2022-03-21 20:55:33.59]: [Transporter]: INFO: iTMSTransporter : iTunes Store Transporter [2.3.0]
DEBUG [2022-03-21 20:55:33.59]: [Transporter]: INFO: OS identifier: Mac OS X 12.3 (x86_64); jvm=14.0.2+12-iTunesOpenJDK-8; jre=14.0.2+12-iTunesOpenJDK-8; arch=arm64; rosetta=true
DEBUG [2022-03-21 20:55:33.59]: [Transporter]: INFO: Memory: [JVM] 997M free, 1024M total, 2048M max [System] (Physical) 96M free, 8192M total (Swap) 1150M free, 3072M total
DEBUG [2022-03-21 20:55:33.60]: [Transporter]: DBG-X: Memory: [JVM] 997M free, 1024M total, 2048M max [System] (Physical) 95M free, 8192M total (Swap) 1150M free, 3072M total
DEBUG [2022-03-21 20:55:33.61]: [Transporter]: DBG-X: Using operation named: authenticateForSession
DEBUG [2022-03-21 20:55:33.63]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2022-03-21 20:55:33.63]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2022-03-21 20:55:33.63]: [Transporter]: DBG-X:   parameter BaseVersion = 2.1.0
DEBUG [2022-03-21 20:55:33.63]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 12.3 (x86_64); jvm=14.0.2+12-iTunesOpenJDK-8; jre=14.0.2+12-iTunesOpenJDK-8; arch=arm64; rosetta=true
DEBUG [2022-03-21 20:55:33.63]: [Transporter]: DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2022-03-21T20:55:33+01:00
DEBUG [2022-03-21 20:55:33.63]: [Transporter]: DBG-X:   parameter StatisticsPreviousCallDurationInSecs = 0.223485
DEBUG [2022-03-21 20:55:33.64]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -jwt **hidden value** -assetFile /var/folders/3j/prd8ybks5kqgcz3qs5b3ggxr0000gp/T/e75d96a3-ffb8-4109-af0e-6ee13a481232.ipa -k 100000
DEBUG [2022-03-21 20:55:33.64]: [Transporter]: DBG-X:   parameter Version = 2.3.0
DEBUG [2022-03-21 20:55:33.64]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
DEBUG [2022-03-21 20:55:33.64]: [Transporter]: INFO: id = ###
DEBUG [2022-03-21 20:55:33.65]: [Transporter]: DEBUG: SMART-CLIENT: getCurrent(); current data center is null
DEBUG [2022-03-21 20:55:33.65]: [Transporter]: DEBUG: SMART-CLIENT: getCurrent(); iterator was null, setting it
DEBUG [2022-03-21 20:55:33.65]: [Transporter]: DEBUG: SMART-CLIENT: getCurrent(); setting current data center to: contentdelivery01.itunes.apple.com
DEBUG [2022-03-21 20:55:33.65]: [Transporter]: INFO: iTMSTransporter Correlation Key: ###
DEBUG [2022-03-21 20:55:33.65]: [Transporter]: DEBUG: SMART-CLIENT: Host HTTP header: contentdelivery01.itunes.apple.com
DEBUG [2022-03-21 20:55:34.96]: [Transporter]: DEBUG: SMART-CLIENT: pinning data center to: contentdelivery01.itunes.apple.com
DEBUG [2022-03-21 20:55:34.96]: [Transporter]: DBG-X: Apple's web service operation return value:
DEBUG [2022-03-21 20:55:34.96]: [Transporter]: DBG-X:   parameter SharedSecret = **hidden value**
DEBUG [2022-03-21 20:55:34.96]: [Transporter]: DBG-X:   parameter MultipartUploadsEnabled = true
DEBUG [2022-03-21 20:55:34.96]: [Transporter]: DBG-X:   parameter EnableJWTForAllCalls = false
DEBUG [2022-03-21 20:55:34.97]: [Transporter]: DBG-X:   parameter TxHeaders = {jenga=true}
DEBUG [2022-03-21 20:55:34.97]: [Transporter]: DBG-X:   parameter ShouldUseFeatures = (null)
DEBUG [2022-03-21 20:55:34.97]: [Transporter]: DBG-X:   parameter SessionExpiration = 2022-03-25T19:55:33.873Z
DEBUG [2022-03-21 20:55:34.97]: [Transporter]: DBG-X:   parameter SessionId = ###
DEBUG [2022-03-21 20:55:34.97]: [Transporter]: DBG-X:   parameter ShouldUseRESTAPIs = false
DEBUG [2022-03-21 20:55:34.97]: [Transporter]: DBG-X:   parameter StreamingSettings = {LogStreamingEnabled=true, MultipartUploadsEnabled=true, AssetDescriptionStreamingEnabled=false}
DEBUG [2022-03-21 20:56:35.41]: [Transporter]: DBG-X: Using operation named: lookupSoftwareForBundleId
DEBUG [2022-03-21 20:56:35.41]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2022-03-21 20:56:35.41]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2022-03-21 20:56:35.41]: [Transporter]: DBG-X:   parameter BaseVersion = 2.1.0
DEBUG [2022-03-21 20:56:35.41]: [Transporter]: DBG-X:   parameter BundleId = ###
DEBUG [2022-03-21 20:56:35.41]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 12.3 (x86_64); jvm=14.0.2+12-iTunesOpenJDK-8; jre=14.0.2+12-iTunesOpenJDK-8; arch=arm64; rosetta=true
DEBUG [2022-03-21 20:56:35.42]: [Transporter]: DBG-X:   parameter SoftwareTypeEnum = ios
DEBUG [2022-03-21 20:56:35.42]: [Transporter]: DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2022-03-21T20:56:35+01:00
DEBUG [2022-03-21 20:56:35.42]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -jwt **hidden value** -assetFile /var/folders/3j/prd8ybks5kqgcz3qs5b3ggxr0000gp/T/e75d96a3-ffb8-4109-af0e-6ee13a481232.ipa -k 100000
DEBUG [2022-03-21 20:56:35.42]: [Transporter]: DBG-X:   parameter Version = 2.3.0
DEBUG [2022-03-21 20:56:35.42]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
DEBUG [2022-03-21 20:56:35.42]: [Transporter]: INFO: id = 20220321205635-852
DEBUG [2022-03-21 20:56:35.42]: [Transporter]: DEBUG: SMART-CLIENT: getCurrent(); using pinned data center = contentdelivery01.itunes.apple.com
DEBUG [2022-03-21 20:56:35.42]: [Transporter]: INFO: iTMSTransporter Correlation Key: ###
DEBUG [2022-03-21 20:56:35.42]: [Transporter]: DEBUG: SMART-CLIENT: Host HTTP header: contentdelivery01.itunes.apple.com
DEBUG [2022-03-21 20:56:36.30]: [Transporter]: DBG-X: Apple's web service operation return value:
DEBUG [2022-03-21 20:56:36.30]: [Transporter]: DBG-X:   parameter ProviderPublicId = ###
DEBUG [2022-03-21 20:56:36.30]: [Transporter]: DBG-X:   parameter DisplayKeys = [Application, Version Number, SKU Number, Primary Language, Copyright, Type, Apple ID]
DEBUG [2022-03-21 20:56:36.30]: [Transporter]: DBG-X:   parameter EnableJWTForAllCalls = false
DEBUG [2022-03-21 20:56:36.30]: [Transporter]: DBG-X:   parameter Applications = ###
DEBUG [2022-03-21 20:56:36.31]: [Transporter]: DBG-X:   parameter ShouldUseFeatures = (null)
DEBUG [2022-03-21 20:56:36.31]: [Transporter]: DBG-X:   parameter ValidIconSizes = [57x57]
DEBUG [2022-03-21 20:56:36.31]: [Transporter]: DBG-X:   parameter SessionExpiration = 2022-03-25T19:56:35.969Z
</details>

**Comment by deremakif** [comment]
Hi @Stephan-FDG, is there any progress here?

**Comment by lucswart** [comment]
I got this issue again now, it basically just freezes my whole macbook again...

**Comment by tomo10** [comment]
We're having the same issue

**Comment by lucswart** [comment]
Can I reopen this issue? 😅

**Comment by deremakif** [comment]
I think it is time to reopen the issue. :)

**Comment by Stephan-FDG** [comment]
Hey @deremakif,
my solution was stop using upload_to_testflight or pilot and instead I used a Xcode command line which was suggested here:
https://gist.github.com/keith/5b5f61f4cc690aec403afd92aab020c3
