### ISSUE TITLE
sh: xcbeautify: command not found

### ISSUE THREAD

**Issue by rserentill** [fastlane/fastlane#19924]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm executing Fastlane through `FastlaneSwiftRunner`, and when executing `scan` or `gym` with default parameters it fails saying:
`sh: xcbeautify: command not found`.

##### Command executed
`scan()` or `gym()`

##### Complete output when running fastlane, including the stack trace and command used
```
[18:05:33]: Disabling 'Slide to Type' iPhone 8
[18:05:33]: $ /usr/libexec/PlistBuddy -c "Add :KeyboardContinuousPathEnabled bool false" /Users/roger/Library/Developer/CoreSimulator/Devices/47A365B9-A985-4037-B2C6-CEFB3FF881E4/data/Library/Preferences/com.apple.keyboard.ContinuousPath.plist >/dev/null 2>&1
[18:05:33]: Booting iPhone 8
[18:05:33]: $ set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace ./App.xcworkspace -scheme App -configuration Debug -derivedDataPath /Users/roger/Library/Developer/Xcode/DerivedData/App-dgfnmeuedupmgjekivmpvvhazyop -destination 'platform=iOS Simulator,id=47A365B9-A985-4037-B2C6-CEFB3FF881E4' -resultBundlePath '/var/folders/kv/ccbtkwmn43l_zfmpqf7n0dgw0000gn/T/d20220207-61461-fy99fm/App.xcresult' -enableCodeCoverage YES clean test | tee '/Users/roger/Library/Logs/scan/App-App.log' | xcbeautify
[18:05:33]: ▸ Loading...
[18:05:33]: ▸ sh: xcbeautify: command not found
+--------------+-----------+
|       Lane Context       |
+--------------+-----------+
| LANE_NAME    | passTests |
| BUILD_NUMBER | 0         |
+--------------+-----------+
#<Thread:0x0000000108c0fd10 /Users/roger/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/fastlane-2.201.1/fastlane/lib/fastlane/swift_lane_manager.rb:96 run> terminated with exception (report_on_exception is true):
/Users/roger/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/fastlane-2.201.1/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': Exit status of command './fastlane/FastlaneRunner lane passTests swiftServerPort 2000 > /dev/null' was  instead of 0. (FastlaneCore::Interface::FastlaneShellError)
	from /Users/roger/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/fastlane-2.201.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/roger/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/fastlane-2.201.1/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	from /Users/roger/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/fastlane-2.201.1/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
	from /Users/roger/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/fastlane-2.201.1/fastlane/lib/fastlane/swift_lane_manager.rb:97:in `block in cruise_swift_lane_in_thread'

+------+---------------------------------------------------+-------------+
|                            fastlane summary                            |
+------+---------------------------------------------------+-------------+
| Step | Action                                            | Time (in s) |
+------+---------------------------------------------------+-------------+
| 1    | is_ci                                             | 0           |
| 2    | ruby ./fastlane/reset_product_name_script.rb      | 0           |
| 3    | git_branch                                        | 0           |
| 4    | ruby                                              | 0           |
|      | ./fastlane/scripts/remove_resource_file_from_mai  |             |
|      | n_target                                          |             |
| 5    | git_branch                                        | 0           |
| 6    | update_project_team                               | 0           |
| 7    | erase_module_frameworks                           | 0           |
| 8    | embed_module_frameworks                           | 0           |
| 9    | ruby ./fastlane/flags_script.rb                   | 0           |
| 10   | increment_build_number                            | 0           |
| 11   | cocoapods                                         | 2           |
| 12   | cocoapods                                         | 4           |
| 13   | increment_build_number                            | 0           |
| 14   | rm -rf ./mobile-project-config                    | 0           |
+------+---------------------------------------------------+-------------+

[18:07:01]: fastlane finished with errors
```

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 12.1                                        |
| Ruby                        | 3.1.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.32.0 (Apple Git-132)          |
| Installation Source         | ~/.rbenv/versions/3.1.0/bin/fastlane        |
| Host                        | macOS 12.1 (21C52)                          |
| Ruby Lib Dir                | ~/.rbenv/versions/3.1.0/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 13.2.1                                      |
| Swift Version               | 5.5.2                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.201.1 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| bundler                         | 2.0.2        |
| pathname                        | 0.2.0        |
| cgi                             | 0.3.1        |
| set                             | 1.0.2        |
| readline-ext                    | 0.1.4        |
| uri                             | 0.11.0       |
| tsort                           | 0.1.0        |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| concurrent-ruby                 | 1.1.9        |
| i18n                            | 1.8.11       |
| minitest                        | 5.14.4       |
| tzinfo                          | 2.0.4        |
| zeitwerk                        | 2.5.1        |
| activesupport                   | 6.1.4.1      |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| httpclient                      | 2.8.3        |
| json                            | 2.6.1        |
| algoliasearch                   | 1.27.5       |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.549.0      |
| aws-sigv4                       | 1.4.0        |
| jmespath                        | 1.5.0        |
| aws-sdk-core                    | 3.125.5      |
| aws-sdk-kms                     | 1.53.0       |
| aws-sdk-s3                      | 1.111.2      |
| babosa                          | 1.0.4        |
| claide                          | 1.1.0        |
| fuzzy_match                     | 2.0.4        |
| nap                             | 1.1.0        |
| netrc                           | 0.11.0       |
| ffi                             | 1.15.4       |
| ethon                           | 0.15.0       |
| typhoeus                        | 1.4.0        |
| cocoapods-core                  | 1.11.2       |
| cocoapods-deintegrate           | 1.0.5        |
| cocoapods-downloader            | 1.5.1        |
| cocoapods-plugins               | 1.0.0        |
| cocoapods-search                | 1.0.1        |
| cocoapods-trunk                 | 1.6.0        |
| cocoapods-try                   | 1.2.0        |
| colored2                        | 3.1.2        |
| escape                          | 0.0.4        |
| fourflusher                     | 2.3.1        |
| gh_inspector                    | 1.1.3        |
| molinillo                       | 0.8.0        |
| ruby-macho                      | 2.5.1        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| cocoapods                       | 1.11.2       |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.90.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.0.0        |
| faraday-multipart               | 1.0.3        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.9.3        |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| jwt                             | 2.3.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.0        |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.2        |
| google-apis-androidpublisher_v3 | 0.15.0       |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.11.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.36.0       |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| mustache                        | 1.1.1        |
| open4                           | 1.3.4        |
| redcarpet                       | 3.5.1        |
| sassc                           | 2.4.0        |
| sqlite3                         | 1.4.2        |
| liferaft                        | 0.0.6        |
| xcinvoke                        | 0.3.0        |
| jazzy                           | 0.13.6       |
| slack-notifier                  | 2.4.0        |
| xcresult                        | 0.2.1        |
| xcov                            | 1.7.5        |
</details>

*generated on:* **2022-02-07**
</details>

**Comment by eseay** [comment]
I am seeing the same issue via `FastlaneSwiftRunner`. My workaround was similar to @rserentill except I just explicitly specified to use "xcpretty". Our CI uses GitHub Actions, which does not have xcbeautify installed by default.
