### ISSUE TITLE
allowProvisioningUpdates not working in automatic signing fastlane

### ISSUE THREAD

**Issue by shamsunderCS** [fastlane/fastlane#19936]
I'm trying to upload build through Github action but i'm stuck in the last point. I'm trying to upload build through automatic signing. But every time got the error. 

FastFile:-

    platform :ios do
    lane :closed_beta do
    keychain_name = TEMP_KEYCHAIN_USER
    keychain_password = TEMP_KEYCHAIN_PASSWORD
    ensure_temp_keychain(keychain_name, keychain_password)
  
      api_key = app_store_connect_api_key(
      key_id: APPLE_KEY_ID,
      issuer_id: APPLE_ISSUER_ID,
      key_content: "#{ENV["APPLE_KEY_CONTENT"]}".gsub('\n', '\\n'),
      is_key_content_base64:true,            
      duration: 1200,            
      in_house: false
      ) 

      increment_build_number(xcodeproj: "**********")

      enable_automatic_code_signing(
        team_id: "********",
      )

      gym(
      configuration: "Release",
      scheme: "*******",
      export_xcargs: "-allowProvisioningUpdates",
      workspace: '********',
      include_bitcode: false,
      export_method: "app-store",
      export_options: {
      uploadBitcode: false,
        uploadSymbols: false,
        compileBitcode: false,
        provisioningProfiles: { 
            DEVELOPER_APP_ID => PROVISIONING_PROFILE_SPECIFIER
         },
            "signingStyle": "manual"
        }
      )

      pilot(
      apple_id: "*******",
      app_identifier: "*******",
      skip_waiting_for_build_processing: true,
      skip_submission: true,
      distribute_external: false,
      notify_external_testers: false,
      ipa: "./*******.ipa"
     )

      delete_temp_keychain(keychain_name)
     end

Xcode:-

![Image][1]

I have tried with and without “-allowProvisioningUpdates”.

**With I get the following:**

> Code Signing Error: There are no accounts registered with Xcode. Add your developer account to Xcode
Code Signing Error: No profiles for '[my app name]' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching '[my app name]'.

**Without I get:**

> No profiles for '[my app name]' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching '[my app name]'. 
Automatic signing is disabled and unable to generate a profile. 
To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.

Question: Can someone please explain to me how to solve this, I've tried with above code but no results yet.

Can someone please explain to me How to upload app test Flight with automatic signing?

Any help would be greatly appreciated.

Thanks in advance.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                              |
| --------------------------- | -------------------------------------------------- |
| OS                          | 11.6                                               |
| Ruby                        | 3.0.0                                              |
| Bundler?                    | false                                              |
| Git                         | git version 2.32.0 (Apple Git-132)                 |
| Installation Source         | ~/.rvm/gems/ruby-3.0.0/bin/fastlane                |
| Host                        | macOS 11.6 (20G165)                                |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-3.0.0/lib                       |
| OpenSSL Version             | OpenSSL 1.1.1m  14 Dec 2021                        |
| Is contained                | false                                              |
| Is homebrew                 | false                                              |
| Is installed via Fabric.app | false                                              |
| Xcode Path                  | /Applications/Xcode 13.2.1.app/Contents/Developer/ |
| Xcode Version               | 13.2.1                                             |
| Swift Version               | 5.5.2                                              |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

DEVELOPER_APP_ID = ENV["DEVELOPER_APP_ID"]
DEVELOPER_APP_IDENTIFIER = ENV["DEVELOPER_APP_IDENTIFIER"]
PROVISIONING_PROFILE_SPECIFIER = ENV["PROVISIONING_PROFILE_SPECIFIER"]
TEMP_KEYCHAIN_USER = ENV["TEMP_KEYCHAIN_USER"]
TEMP_KEYCHAIN_PASSWORD = ENV["TEMP_KEYCHAIN_PASSWORD"]
APPLE_ISSUER_ID = ENV["APPLE_ISSUER_ID"]
APPLE_KEY_ID = ENV["APPLE_KEY_ID"]
APPLE_KEY_CONTENT = ENV["APPLE_KEY_CONTENT"]
GIT_AUTHORIZATION = ENV["GIT_AUTHORIZATION"]

def delete_temp_keychain(name)

  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

def create_temp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    unlock: false,
    timeout: 0
  )
end

def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end

platform :ios do
  lane :closed_beta do
    build_app(scheme: "GitHubAction_CS",
            workspace: "GitHubAction_CS.xcworkspace",
            include_bitcode: true)
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier(ENV["DEVELOPER_APP_IDENTIFIER"])
apple_id(ENV["FASTLANE_APPLE_ID"])
itc_team_id(ENV["APP_STORE_CONNECT_TEAM_ID"])
team_id(ENV["DEVELOPER_PORTAL_TEAM_ID"])

# For more information about the Appfile, see:
# https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.204.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| atomos                          | 0.1.3        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.3        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.9.3        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.3        |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.2        |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.11.0       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.36.0       |
| emoji_regex                     | 3.2.3        |
| tsort                           | 0.1.0        |
| set                             | 1.0.1        |
| uri                             | 0.10.1       |
| rexml                           | 3.2.5        |
| excon                           | 0.91.0       |
| json                            | 2.6.1        |
| google-apis-androidpublisher_v3 | 0.16.0       |
| rake                            | 13.0.6       |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-partitions                  | 1.553.0      |
| jmespath                        | 1.5.0        |
| aws-sdk-core                    | 3.126.0      |
| aws-sdk-kms                     | 1.54.0       |
| aws-sdk-s3                      | 1.112.0      |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.0        |
| date                            | 3.1.0        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.0        |
| securerandom                    | 0.1.0        |
| openssl                         | 2.2.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.2        |
| io-wait                         | 0.1.0        |
| zlib                            | 1.1.0        |
| resolv                          | 0.2.0        |
| digest                          | 3.0.0        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.0        |
| net-smtp                        | 0.2.1        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.0        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.6        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.1        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| prettyprint                     | 0.1.0        |
| pp                              | 0.1.0        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.0        |
</details>

*generated on:* **2022-02-09**
</details>

  [1]: https://i.stack.imgur.com/BPQJ4.png

**Comment by shamsunderCS** [comment]
@kommen @fastlane-bot @cbowns @lsegal Could you please check

**Comment by max-ott** [comment]
@shamsunderCS please don't ping any individuals, it's just rude. It seems the error message is pretty specific:

> Code Signing Error: There are no accounts registered with Xcode. Add your developer account to Xcode
Code Signing Error: No profiles for '[my app name]' were found: Xcode couldn't find any iOS App Development provisioning profiles matching '[my app name]'. 

You'll need to add your Apple ID to Xcode to use automatic code signing.
