### ISSUE TITLE
Uploading videos on the App Store

### ISSUE THREAD

**Issue by IlyaNakhaichuk** [fastlane/fastlane#19948]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I want to upload videos to the App Store, is it possible to do this? I saw a similar question #1632, but after that a lot of time has passed, perhaps something has changed.

**Comment by valerio-castelli** [comment]
It is [possible](https://developer.apple.com/documentation/appstoreconnectapi/app_metadata/app_previews) in general, but fastlane currently doesn't implement a flow to do it.

**Comment by max-ott** [comment]
It's possible to upload app previews via `spaceship`: https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/connect_api/models/app_preview.rb

If you are looking for an "easy" command in `deliver`, it's currently not implemented. Any pull requests would be more than welcomed!
