### ISSUE TITLE
Fastlane gym doesnot support export_path when archiving

### ISSUE THREAD

**Issue by ykhandelwal913** [fastlane/fastlane#19954]
### Discussed in https://github.com/fastlane/fastlane/discussions/19951

<div type='discussions-op-text'>

<sup>Originally posted by **ykhandelwal913** February 11, 2022</sup>
Currently xcodebuild support export_path and we can define our own path which is not supported by fastlane gym.

Before gym
xcodebuild clean archive -archivePath build/MyApp \
                         -scheme MyApp
xcodebuild -exportArchive \
           -exportFormat ipa \
           -archivePath "build/MyApp.xcarchive" \
           -exportPath "build/MyApp.ipa" \
           -exportProvisioningProfile "ProvisioningProfileName"

After gym
| include_bitcode                      | Should the ipa file include bitcode?            | GYM_INCLUDE_BITCODE                      |                      |
| export_method                        | Method used to export the archive. Valid        | GYM_EXPORT_METHOD                        |                      |
|                                      | values are: app-store, validation, ad-hoc,      |                                          |                      |
|                                      | package, enterprise, development, developer-id  |                                          |                      |
|                                      | and mac-application                             |                                          |                      |
| export_options                       | Path to an export options plist or a hash with  | GYM_EXPORT_OPTIONS                       |                      |
|                                      | export options. Use 'xcodebuild -help' to       |                                          |                      |
|                                      | print the full set of available options         |                                          |                      |
| export_xcargs                        | Pass additional arguments to xcodebuild for     | GYM_EXPORT_XCARGS                        |                      |
|                                      | the package phase. Be sure to quote the         |                                          |                      |
|                                      | setting names and values e.g.                   |                                          |                      |</div>

**Comment by max-ott** [comment]
Hey, please edit the issue following our issue template or re-open another issue for our community to be able to help you!
