### ISSUE TITLE
Args only allowed in library command line alias

### ISSUE THREAD

**Issue by bradyt** [fastlane/fastlane#19964]
The following are successful:

```
bundle exec fastlane gym --scheme stable
bundle exec fastlane pilot upload --skip_submission
```

The documentation suggests `gym` is an alias for `build_app`, and `testflight` is an alternative alias as `pilot`.

But the following args are not allowed:

```
bundle exec fastlane build_app --scheme stable
bundle exec fastlane testflight upload --skip_submission
```

For example, `invalid option: --scheme`.

**Comment by roman4864** [comment]
Just to reiterate what has been posted for other shells, in Bash the following works:

`alias blah='function _blah(){ echo "First: $1"; echo "Second: $2"; };_blah'`
Running the following:

blah one two
Gives the output below:

```
First: one
Second: two
```

**Comment by bradyt** [comment]
@roman4864 I assume you posted to the wrong issue, but if I'm mistaken, can you clarify the connection?
