### ISSUE TITLE
'destination' argument to build_app not passed to all xcodebuild calls

### ISSUE THREAD

**Issue by jamescrowley** [fastlane/fastlane#19976]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When building via fastlane, I receive the following warning:

```
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:00006000-001C08A03E62801E }
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
{ platform:iOS Simulator, id:AF58B44B-5C5C-4F69-8B33-CDD276611AB2, OS:15.2, name:iPad (9th generation) }
{ platform:iOS Simulator, id:2D209399-698A-4822-98E0-90E9D0BEF6E8, OS:15.2, name:iPad Air (4th generation) }
{ platform:iOS Simulator, id:8715C6B5-FFA6-4B93-8925-C63C155BE0AF, OS:15.2, name:iPad Pro (9.7-inch) }
{ platform:iOS Simulator, id:B0D37ED2-3D53-44C8-AED4-6B4BE07EAF10, OS:15.2, name:iPad Pro (11-inch) (3rd generation) }
{ platform:iOS Simulator, id:A3FE9935-9C1A-4943-88B0-5ABD66EB9B2B, OS:15.2, name:iPad Pro (12.9-inch) (5th generation) }
{ platform:iOS Simulator, id:DF81A41B-16DE-47AA-8E54-ECD87D10F802, OS:15.2, name:iPad mini (6th generation) }
{ platform:iOS Simulator, id:E5D641EF-B692-47B1-B7EF-FE6929819AC3, OS:15.2, name:iPhone 8 }
{ platform:iOS Simulator, id:6EA7D179-12F9-4230-8500-19E89F81F213, OS:15.2, name:iPhone 8 Plus }
{ platform:iOS Simulator, id:B365725F-A8A9-441F-BC9A-4C6B3D5CCA8A, OS:15.2, name:iPhone 11 }
{ platform:iOS Simulator, id:519B6F6E-405E-49DE-AC47-59457D8D1042, OS:15.2, name:iPhone 11 Pro }
{ platform:iOS Simulator, id:FA93A0E1-27B3-451A-A207-365B1A2AA35B, OS:15.2, name:iPhone 11 Pro Max }
{ platform:iOS Simulator, id:AC428A5F-665A-4A87-BFC2-2C63F798FE69, OS:15.2, name:iPhone 12 }
{ platform:iOS Simulator, id:F3C55681-4FC9-40BD-BDD0-EEE4CF2A2ECF, OS:15.2, name:iPhone 12 Pro }
{ platform:iOS Simulator, id:48F6B10A-6D5F-463D-A9C9-FA173106B161, OS:15.2, name:iPhone 12 Pro Max }
{ platform:iOS Simulator, id:4D6050E0-1E01-4196-91C9-EE0BADE7EFA4, OS:15.2, name:iPhone 12 mini }
{ platform:iOS Simulator, id:C108068D-5E27-416B-A180-8EA9A102D55E, OS:15.2, name:iPhone 13 }
{ platform:iOS Simulator, id:2E265F14-4F11-4C3B-ADD5-3CC946B7363A, OS:15.2, name:iPhone 13 Pro }
{ platform:iOS Simulator, id:D838050C-F966-4D37-8F51-70EC001C251A, OS:15.2, name:iPhone 13 Pro Max }
{ platform:iOS Simulator, id:C4DCBF3F-76AA-472C-95BF-867DC5EDAA99, OS:15.2, name:iPhone 13 mini }
{ platform:iOS Simulator, id:8E23E9B5-FCE7-4724-B448-1CC3B3CE86C2, OS:15.2, name:iPhone SE (2nd generation) }
{ platform:iOS Simulator, id:9C26BFF4-13D2-4628-822B-FCE995AE4E14, OS:15.2, name:iPod touch (7th generation) }
```

This occurs 2x times through the build. While the appropriate 'destination' argument is provided for this step: 

`set -o pipefail && xcodebuild -scheme XXXX -project ./XXXX.xcodeproj -destination 'generic/platform=iOS' #snip archive`

It is not provided for these calls:

```
xcodebuild -resolvePackageDependencies -scheme XXXX -project ./XXXX.xcodeproj
xcodebuild -showBuildSettings -scheme XXXX -project ./XXXX.xcodeproj
```

I attempted to fix this by passing destination as an argument to build_app

build_app(scheme: "XXXX", destination: "generic/platform=X")

but it too is only passed to the `archive` xcodebuild command step.

##### Command executed

`fastlane beta`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [15:09:17]: -----------------------
[15:09:17]: --- Step: build_app ---
[15:09:17]: -----------------------
[15:09:17]: Resolving Swift Package Manager dependencies...
[15:09:17]: $ xcodebuild -resolvePackageDependencies -scheme XXXX -project ./XXXX.xcodeproj
[15:09:17]: ▸ objc[291]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x1fee4f678) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x107d7c2c8). One of the two will be used. Which one is undefined.
[15:09:17]: ▸ objc[291]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x1fee4f6c8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x107d7c318). One of the two will be used. Which one is undefined.
[15:09:17]: ▸ Command line invocation:
[15:09:17]: ▸     /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -scheme XXXX -project ./XXXX.xcodeproj
[15:09:17]: ▸ User defaults from command line:
[15:09:17]: ▸     IDEPackageSupportUseBuiltinSCM = YES
[15:09:18]: ▸ Resolve Package Graph
[15:09:20]: ▸ Resolved source packages:
[15:09:20]: ▸   GTMSessionFetcher: https://github.com/google/gtm-session-fetcher.git @ 1.7.0
[15:09:20]: ▸   GoogleDataTransport: https://github.com/google/GoogleDataTransport.git @ 9.1.2
[15:09:20]: ▸   Firebase: https://github.com/firebase/firebase-ios-sdk @ 8.10.0
[15:09:20]: ▸   swift-collections: https://github.com/apple/swift-collections @ 1.0.2
[15:09:20]: ▸   leveldb: https://github.com/firebase/leveldb.git @ 1.22.2
[15:09:20]: ▸   nanopb: https://github.com/firebase/nanopb.git @ 2.30908.0
[15:09:20]: ▸   gRPC: https://github.com/firebase/grpc-SwiftPM.git @ 1.28.4
[15:09:20]: ▸   Promises: https://github.com/google/promises.git @ 2.0.0
[15:09:20]: ▸   GoogleUtilities: https://github.com/google/GoogleUtilities.git @ 7.6.0
[15:09:20]: ▸   SwiftProtobuf: https://github.com/apple/swift-protobuf.git @ 1.18.0
[15:09:20]: ▸   BoringSSL-GRPC: https://github.com/firebase/boringssl-SwiftPM.git @ 0.7.2
[15:09:20]: ▸   abseil: https://github.com/firebase/abseil-cpp-SwiftPM.git @ 0.20200225.4
[15:09:20]: ▸   AWSiOSSDKV2: https://github.com/aws-amplify/aws-sdk-ios-spm @ 2.27.1
[15:09:20]: ▸   GoogleAppMeasurement: https://github.com/google/GoogleAppMeasurement.git @ 8.9.1
[15:09:20]: ▸ --- xcodebuild: WARNING: Using the first of multiple matching destinations:
[15:09:20]: ▸ { platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:00006000-001C08A03E62801E }
[15:09:20]: ▸ { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
[15:09:20]: ▸ { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
[15:09:20]: ▸ { platform:iOS Simulator, id:AF58B44B-5C5C-4F69-8B33-CDD276611AB2, OS:15.2, name:iPad (9th generation) }
[15:09:20]: ▸ { platform:iOS Simulator, id:2D209399-698A-4822-98E0-90E9D0BEF6E8, OS:15.2, name:iPad Air (4th generation) }
[15:09:20]: ▸ { platform:iOS Simulator, id:8715C6B5-FFA6-4B93-8925-C63C155BE0AF, OS:15.2, name:iPad Pro (9.7-inch) }
[15:09:20]: ▸ { platform:iOS Simulator, id:B0D37ED2-3D53-44C8-AED4-6B4BE07EAF10, OS:15.2, name:iPad Pro (11-inch) (3rd generation) }
[15:09:20]: ▸ { platform:iOS Simulator, id:A3FE9935-9C1A-4943-88B0-5ABD66EB9B2B, OS:15.2, name:iPad Pro (12.9-inch) (5th generation) }
[15:09:20]: ▸ { platform:iOS Simulator, id:DF81A41B-16DE-47AA-8E54-ECD87D10F802, OS:15.2, name:iPad mini (6th generation) }
[15:09:20]: ▸ { platform:iOS Simulator, id:E5D641EF-B692-47B1-B7EF-FE6929819AC3, OS:15.2, name:iPhone 8 }
[15:09:20]: ▸ { platform:iOS Simulator, id:6EA7D179-12F9-4230-8500-19E89F81F213, OS:15.2, name:iPhone 8 Plus }
[15:09:20]: ▸ { platform:iOS Simulator, id:B365725F-A8A9-441F-BC9A-4C6B3D5CCA8A, OS:15.2, name:iPhone 11 }
[15:09:20]: ▸ { platform:iOS Simulator, id:519B6F6E-405E-49DE-AC47-59457D8D1042, OS:15.2, name:iPhone 11 Pro }
[15:09:20]: ▸ { platform:iOS Simulator, id:FA93A0E1-27B3-451A-A207-365B1A2AA35B, OS:15.2, name:iPhone 11 Pro Max }
[15:09:20]: ▸ { platform:iOS Simulator, id:AC428A5F-665A-4A87-BFC2-2C63F798FE69, OS:15.2, name:iPhone 12 }
[15:09:20]: ▸ { platform:iOS Simulator, id:F3C55681-4FC9-40BD-BDD0-EEE4CF2A2ECF, OS:15.2, name:iPhone 12 Pro }
[15:09:20]: ▸ { platform:iOS Simulator, id:48F6B10A-6D5F-463D-A9C9-FA173106B161, OS:15.2, name:iPhone 12 Pro Max }
[15:09:20]: ▸ { platform:iOS Simulator, id:4D6050E0-1E01-4196-91C9-EE0BADE7EFA4, OS:15.2, name:iPhone 12 mini }
[15:09:20]: ▸ { platform:iOS Simulator, id:C108068D-5E27-416B-A180-8EA9A102D55E, OS:15.2, name:iPhone 13 }
[15:09:20]: ▸ { platform:iOS Simulator, id:2E265F14-4F11-4C3B-ADD5-3CC946B7363A, OS:15.2, name:iPhone 13 Pro }
[15:09:20]: ▸ { platform:iOS Simulator, id:D838050C-F966-4D37-8F51-70EC001C251A, OS:15.2, name:iPhone 13 Pro Max }
[15:09:20]: ▸ { platform:iOS Simulator, id:C4DCBF3F-76AA-472C-95BF-867DC5EDAA99, OS:15.2, name:iPhone 13 mini }
[15:09:20]: ▸ { platform:iOS Simulator, id:8E23E9B5-FCE7-4724-B448-1CC3B3CE86C2, OS:15.2, name:iPhone SE (2nd generation) }
[15:09:20]: ▸ { platform:iOS Simulator, id:9C26BFF4-13D2-4628-822B-FCE995AE4E14, OS:15.2, name:iPod touch (7th generation) }
[15:09:20]: ▸ resolved source packages: GTMSessionFetcher, GoogleDataTransport, Firebase, swift-collections, leveldb, nanopb, gRPC, Promises, GoogleUtilities, SwiftProtobuf, BoringSSL-GRPC, abseil, AWSiOSSDKV2, GoogleAppMeasurement
[15:09:20]: $ xcodebuild -showBuildSettings -scheme XXXX -project ./XXXX.xcodeproj
objc[296]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x1fee4f678) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x107a502c8). One of the two will be used. Which one is undefined.
objc[296]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x1fee4f6c8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x107a50318). One of the two will be used. Which one is undefined.
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:00006000-001C08A03E62801E }
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
{ platform:iOS Simulator, id:AF58B44B-5C5C-4F69-8B33-CDD276611AB2, OS:15.2, name:iPad (9th generation) }
{ platform:iOS Simulator, id:2D209399-698A-4822-98E0-90E9D0BEF6E8, OS:15.2, name:iPad Air (4th generation) }
{ platform:iOS Simulator, id:8715C6B5-FFA6-4B93-8925-C63C155BE0AF, OS:15.2, name:iPad Pro (9.7-inch) }
{ platform:iOS Simulator, id:B0D37ED2-3D53-44C8-AED4-6B4BE07EAF10, OS:15.2, name:iPad Pro (11-inch) (3rd generation) }
{ platform:iOS Simulator, id:A3FE9935-9C1A-4943-88B0-5ABD66EB9B2B, OS:15.2, name:iPad Pro (12.9-inch) (5th generation) }
{ platform:iOS Simulator, id:DF81A41B-16DE-47AA-8E54-ECD87D10F802, OS:15.2, name:iPad mini (6th generation) }
{ platform:iOS Simulator, id:E5D641EF-B692-47B1-B7EF-FE6929819AC3, OS:15.2, name:iPhone 8 }
{ platform:iOS Simulator, id:6EA7D179-12F9-4230-8500-19E89F81F213, OS:15.2, name:iPhone 8 Plus }
{ platform:iOS Simulator, id:B365725F-A8A9-441F-BC9A-4C6B3D5CCA8A, OS:15.2, name:iPhone 11 }
{ platform:iOS Simulator, id:519B6F6E-405E-49DE-AC47-59457D8D1042, OS:15.2, name:iPhone 11 Pro }
{ platform:iOS Simulator, id:FA93A0E1-27B3-451A-A207-365B1A2AA35B, OS:15.2, name:iPhone 11 Pro Max }
{ platform:iOS Simulator, id:AC428A5F-665A-4A87-BFC2-2C63F798FE69, OS:15.2, name:iPhone 12 }
{ platform:iOS Simulator, id:F3C55681-4FC9-40BD-BDD0-EEE4CF2A2ECF, OS:15.2, name:iPhone 12 Pro }
{ platform:iOS Simulator, id:48F6B10A-6D5F-463D-A9C9-FA173106B161, OS:15.2, name:iPhone 12 Pro Max }
{ platform:iOS Simulator, id:4D6050E0-1E01-4196-91C9-EE0BADE7EFA4, OS:15.2, name:iPhone 12 mini }
{ platform:iOS Simulator, id:C108068D-5E27-416B-A180-8EA9A102D55E, OS:15.2, name:iPhone 13 }
{ platform:iOS Simulator, id:2E265F14-4F11-4C3B-ADD5-3CC946B7363A, OS:15.2, name:iPhone 13 Pro }
{ platform:iOS Simulator, id:D838050C-F966-4D37-8F51-70EC001C251A, OS:15.2, name:iPhone 13 Pro Max }
{ platform:iOS Simulator, id:C4DCBF3F-76AA-472C-95BF-867DC5EDAA99, OS:15.2, name:iPhone 13 mini }
{ platform:iOS Simulator, id:8E23E9B5-FCE7-4724-B448-1CC3B3CE86C2, OS:15.2, name:iPhone SE (2nd generation) }
{ platform:iOS Simulator, id:9C26BFF4-13D2-4628-822B-FCE995AE4E14, OS:15.2, name:iPod touch (7th generation) }
[15:09:23]: Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...
objc[300]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x1fee4f678) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1081cc2c8). One of the two will be used. Which one is undefined.
objc[300]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x1fee4f6c8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1081cc318). One of the two will be used. Which one is undefined.
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:00006000-001C08A03E62801E }
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
{ platform:iOS Simulator, id:AF58B44B-5C5C-4F69-8B33-CDD276611AB2, OS:15.2, name:iPad (9th generation) }
{ platform:iOS Simulator, id:2D209399-698A-4822-98E0-90E9D0BEF6E8, OS:15.2, name:iPad Air (4th generation) }
{ platform:iOS Simulator, id:8715C6B5-FFA6-4B93-8925-C63C155BE0AF, OS:15.2, name:iPad Pro (9.7-inch) }
{ platform:iOS Simulator, id:B0D37ED2-3D53-44C8-AED4-6B4BE07EAF10, OS:15.2, name:iPad Pro (11-inch) (3rd generation) }
{ platform:iOS Simulator, id:A3FE9935-9C1A-4943-88B0-5ABD66EB9B2B, OS:15.2, name:iPad Pro (12.9-inch) (5th generation) }
{ platform:iOS Simulator, id:DF81A41B-16DE-47AA-8E54-ECD87D10F802, OS:15.2, name:iPad mini (6th generation) }
{ platform:iOS Simulator, id:E5D641EF-B692-47B1-B7EF-FE6929819AC3, OS:15.2, name:iPhone 8 }
{ platform:iOS Simulator, id:6EA7D179-12F9-4230-8500-19E89F81F213, OS:15.2, name:iPhone 8 Plus }
{ platform:iOS Simulator, id:B365725F-A8A9-441F-BC9A-4C6B3D5CCA8A, OS:15.2, name:iPhone 11 }
{ platform:iOS Simulator, id:519B6F6E-405E-49DE-AC47-59457D8D1042, OS:15.2, name:iPhone 11 Pro }
{ platform:iOS Simulator, id:FA93A0E1-27B3-451A-A207-365B1A2AA35B, OS:15.2, name:iPhone 11 Pro Max }
{ platform:iOS Simulator, id:AC428A5F-665A-4A87-BFC2-2C63F798FE69, OS:15.2, name:iPhone 12 }
{ platform:iOS Simulator, id:F3C55681-4FC9-40BD-BDD0-EEE4CF2A2ECF, OS:15.2, name:iPhone 12 Pro }
{ platform:iOS Simulator, id:48F6B10A-6D5F-463D-A9C9-FA173106B161, OS:15.2, name:iPhone 12 Pro Max }
{ platform:iOS Simulator, id:4D6050E0-1E01-4196-91C9-EE0BADE7EFA4, OS:15.2, name:iPhone 12 mini }
{ platform:iOS Simulator, id:C108068D-5E27-416B-A180-8EA9A102D55E, OS:15.2, name:iPhone 13 }
{ platform:iOS Simulator, id:2E265F14-4F11-4C3B-ADD5-3CC946B7363A, OS:15.2, name:iPhone 13 Pro }
{ platform:iOS Simulator, id:D838050C-F966-4D37-8F51-70EC001C251A, OS:15.2, name:iPhone 13 Pro Max }
{ platform:iOS Simulator, id:C4DCBF3F-76AA-472C-95BF-867DC5EDAA99, OS:15.2, name:iPhone 13 mini }
{ platform:iOS Simulator, id:8E23E9B5-FCE7-4724-B448-1CC3B3CE86C2, OS:15.2, name:iPhone SE (2nd generation) }
{ platform:iOS Simulator, id:9C26BFF4-13D2-4628-822B-FCE995AE4E14, OS:15.2, name:iPod touch (7th generation) }
[15:09:27]: Detected provisioning profile mapping: {:"com.XXXX.XXXXapp"=>"match AppStore com.XXXX.XXXXapp"}

+--------------------------------------------------------------------------------+-------------------------------------------------------------+
|                                                           Summary for gym 2.204.3                                                            |
+--------------------------------------------------------------------------------+-------------------------------------------------------------+
| scheme                                                                         | XXXX                                                |
| destination                                                                    | generic/platform=iOS                                        |
| export_method                                                                  | app-store                                                   |
| export_options.provisioningProfiles.com.XXXX.XXXXapp | match AppStore com.XXXX.XXXXapp   |
| project                                                                        | ./XXXX.xcodeproj                                    |
| clean                                                                          | false                                                       |
| output_directory                                                               | .                                                           |
| output_name                                                                    | XXXX                                                |
| silent                                                                         | false                                                       |
| skip_package_ipa                                                               | false                                                       |
| skip_package_pkg                                                               | false                                                       |
| build_path                                                                     | /Users/userY/Library/Developer/Xcode/Archives/2022-02-16 |
| result_bundle                                                                  | false                                                       |
| buildlog_path                                                                  | ~/Library/Logs/gym                                          |
| xcodebuild_formatter                                                           | xcpretty                                                    |
| skip_profile_detection                                                         | false                                                       |
| xcodebuild_command                                                             | xcodebuild                                                  |
| skip_package_dependencies_resolution                                           | false                                                       |
| disable_package_automatic_updates                                              | false                                                       |
| use_system_scm                                                                 | false                                                       |
| xcode_path                                                                     | /Applications/Xcode.app                                     |
+--------------------------------------------------------------------------------+-------------------------------------------------------------+

[15:09:27]: $ set -o pipefail && xcodebuild -scheme XXXX -project ./XXXX.xcodeproj -destination 'generic/platform=iOS' -archivePath /Users/userY/Library/Developer/Xcode/Archives/2022-02-16/XXXX\ 2022-02-16\ 15.09.27.xcarchive archive | tee /Users/userY/Library/Logs/gym/XXXX-XXXX.log | xcpretty
[15:09:27]: ▸ objc[320]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x1fee4f678) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x107e482c8). One of the two will be used. Which one is undefined.
[15:09:27]: ▸ objc[320]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x1fee4f6c8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x107e48318). One of the two will be used. Which one is undefined.
[15:09:32]: ▸ Compiling FBLPromise+Validate.m
[15:09:33]: ▸ Compiling FBLPromise+Wrap.m
[15:09:33]: ▸ Compiling FBLPromise.m
[15:09:33]: ▸ Compiling FBLPromiseError.m
[15:09:33]: ▸ Compiling FBLPromise+Then.m
[15:09:33]: ▸ Compiling dummy.m
[15:09:33]: ▸ Compiling FBLPromise+Timeout.m
[15:09:33]: ▸ Compiling FBLPromise+Retry.m
[15:09:33]: ▸ Compiling FBLPromise+Testing.m
[15:09:33]: ▸ Compiling FBLPromise+Reduce.m
[15:09:33]: ▸ Compiling FBLPromise+Recover.m
[15:09:33]: ▸ Linking Firebase.o
[15:09:33]: ▸ Compiling FBLPromise+Race.m
[15:09:33]: ▸ Compiling FBLPromise+Do.m
... snip

 </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 12.2.1                                      |
| Ruby                        | 3.1.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.32.0 (Apple Git-132)          |
| Installation Source         | ~/.rbenv/versions/3.1.0/bin/fastlane        |
| Host                        | macOS 12.2.1 (21D62)                        |
| Ruby Lib Dir                | ~/.rbenv/versions/3.1.0/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 13.2                                        |
| Swift Version               | 5.5.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "XXXX.xcodeproj")
    build_app(scheme: "XXXX", destination: "generic/platform=macOS")

    upload_to_testflight(api_key: api_key)
  end
end


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("XXXX") # The bundle identifier of your app

itc_team_id("XXXX") # App Store Connect Team ID
team_id("XXXX") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.204.3 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| bundler                         | 2.3.7        |
| pathname                        | 0.2.0        |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.554.0      |
| aws-sigv4                       | 1.4.0        |
| jmespath                        | 1.6.0        |
| aws-sdk-core                    | 3.126.1      |
| aws-sdk-kms                     | 1.54.0       |
| aws-sdk-s3                      | 1.112.0      |
| babosa                          | 1.0.4        |
| claide                          | 1.1.0        |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.91.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.0.0        |
| faraday-multipart               | 1.0.3        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.9.3        |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.3.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.1        |
| httpclient                      | 2.8.3        |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.2        |
| google-apis-androidpublisher_v3 | 0.16.0       |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.11.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.36.1       |
| json                            | 2.6.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
</details>

*generated on:* **2022-02-16**
</details>

**Comment by jamescrowley** [comment]
Just commenting to keep this open.

**Comment by jakub-vallo** [comment]
Bump for this issue.

**Comment by vinamelody** [comment]
Hi project maintainer @joshdholtz , I notice that in `fastlane_core/lib/fastlane_core/project.rb`, there is no `destination` added in `xcodebuild_parameters` (or rather, ignored)

Is it safe to add it? 
looking at how -derivedData was added but causing duplicates here https://github.com/fastlane/fastlane/pull/16534
