### ISSUE TITLE
Snapshot reinstall_app doesn't work

### ISSUE THREAD

**Issue by ahti** [fastlane/fastlane#19971]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.4                                                           |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.35.1                                             |
| Installation Source         | ...../vendor/bundle/ruby/2.6.0/bin/fastlane       |
| Host                        | macOS 11.4 (20F71)                                             |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode-13.2.1.app/Contents/Developer/             |
| Xcode Version               | 13.2.1                                                         |
| Swift Version               | 5.5.2                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.204.3 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                 | Version | Update-Status |
| ---------------------- | ------- | ------------- |
| fastlane-plugin-sentry | 1.11.1  | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| bundler                         | 1.17.3       |
| etc                             | 1.0.1        |
| forwardable                     | 1.2.0        |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| concurrent-ruby                 | 1.1.9        |
| i18n                            | 1.10.0       |
| minitest                        | 5.15.0       |
| tzinfo                          | 2.0.4        |
| zeitwerk                        | 2.5.4        |
| activesupport                   | 6.1.4.6      |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| httpclient                      | 2.8.3        |
| json                            | 2.6.1        |
| algoliasearch                   | 1.27.5       |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.554.0      |
| aws-sigv4                       | 1.4.0        |
| jmespath                        | 1.6.0        |
| aws-sdk-core                    | 3.126.1      |
| aws-sdk-kms                     | 1.54.0       |
| aws-sdk-s3                      | 1.112.0      |
| babosa                          | 1.0.4        |
| claide                          | 1.0.3        |
| fuzzy_match                     | 2.0.4        |
| nap                             | 1.1.0        |
| netrc                           | 0.11.0       |
| ffi                             | 1.15.5       |
| ethon                           | 0.15.0       |
| typhoeus                        | 1.4.0        |
| cocoapods-core                  | 1.11.2       |
| cocoapods-deintegrate           | 1.0.5        |
| cocoapods-downloader            | 1.5.1        |
| cocoapods-plugins               | 1.0.0        |
| cocoapods-search                | 1.0.1        |
| cocoapods-trunk                 | 1.6.0        |
| cocoapods-try                   | 1.2.0        |
| colored2                        | 3.1.2        |
| escape                          | 0.0.4        |
| fourflusher                     | 2.3.1        |
| gh_inspector                    | 1.1.3        |
| molinillo                       | 0.8.0        |
| ruby-macho                      | 2.5.1        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| cocoapods                       | 1.11.2       |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.91.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.0.0        |
| faraday-multipart               | 1.0.3        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.9.3        |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| jwt                             | 2.3.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.1        |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.2        |
| google-apis-androidpublisher_v3 | 0.16.0       |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.11.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.36.1       |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| fastlane-plugin-sentry          | 1.11.1       |
| http-accept                     | 1.7.0        |
| mime-types-data                 | 3.2022.0105  |
| mime-types                      | 3.4.1        |
| mustermann                      | 1.1.1        |
| rack                            | 2.2.3        |
| rack-protection                 | 2.1.0        |
| rest-client                     | 2.1.0        |
| tilt                            | 2.0.10       |
| sinatra                         | 2.1.0        |
| slack-notifier                  | 2.4.0        |
| xcode-install                   | 2.8.0        |
| xcresult                        | 0.2.1        |
| xcov                            | 1.7.5        |
</details>

*generated on:* **2022-02-15**
</details>

### Issue Description
My Snapfile sets reinstall_app to true (and provides the bundle ID). The options are passed fine and show up in the summary, but the app doesn't get uninstalled.

Relevant section from the log (repeats for other devices):

```
[09:31:18]: $ open -a Simulator.app --args -CurrentDeviceUDID C21E7240-D4BA-48DA-B3D7-A4E3D0EE44ED &> /dev/null
[09:31:19]: Uninstall application com.example.bundleid
[09:31:19]: $ xcrun simctl uninstall C21E7240-D4BA-48DA-B3D7-A4E3D0EE44ED com.example.bundleid &> /dev/null
```

This happens [here](https://github.com/fastlane/fastlane/blob/a5919aecbd4b5ff1631d2d5c916f7dd62f3c70dd/fastlane_core/lib/fastlane_core/device_manager.rb#L324) and was recently changed by #19531.

From what I could find, the cause of the issue seems to be that `simctl uninstall` only works when the device is booted, but the `open` command exits before the simulator is up fully.

I was able to fix this on my machine by replacing the line I linked above (the open command) with the following:

    Helper.backticks("xcrun simctl boot #{device_udid}")
    Helper.backticks("xcrun simctl bootstatus #{device_udid}")

With this change, each `boostatus` invocation waits about 5 seconds before continuing, and the uninstall proceeds successfully.

I'm not very familiar with `simctl` though, so this might not be the appropriate way to address the issue? 🤔

**Comment by ahti** [comment]
Ping @lucgrabowski @joshdholtz (since you two reviewed #19531)

**Comment by Hinderlit** [comment]
Attempts:

1.  Ensured info.plist "Bundle Identifier" is correct. it is "$(PRODUCT_BUNDLE_IDENTIFIER)"
2. Checked to see if typing the bundle identifier manually would work, but it did not.
3. Recreated Provisioning Profiles - Expires in 11 months
4. Automatically Manage Signing is unchecked then checked again
5. Project Cleaned
6. Deleted Derived Data
7. Xcode relaunched
8. Computer Restarted
9. Xcode betas uninstalled
10. Xcode Uninstalled and Reinstalled
