### ISSUE TITLE
Resign issue when certificate "signing_identity" is not unique in the Keychain

### ISSUE THREAD

**Issue by oebbstefan** [fastlane/fastlane#19982]
Hi, 

I have two certificates in my macOS Keychain, that have the same "identity" but different "team ids".
Don't ask me why ... I have to deal with it ;)

**Keychain**
Cert1: "iPhone Distribution: XYZ GmbH"
Cert2: "iPhone Distribution: XYZ GmbH"

How am I supposed to use resign my app with the correct certificate?
Resigning works fine but takes the "wrong" in this case undefined certificate.
The "team_id" parameter is not present on "resign" .. at least it seems so as adding team_id: "ASDFGHJK" to my lane did not work

My lane looks like this:

lane :demo do
  resign(
    ipa: "./resigned_enterprise_demo_app.ipa",
    **signing_identity: "iPhone Distribution: XYZ GmbH",**
    bundle_id: "com.xyz.demo",
    use_app_entitlements: false
  )
end

In my current workaround I have to export, delete the wrong certificate before resigning and import it again afterwards.
Is there a solution for my issue?

EDIT:
added output of fastlane env

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 12.2                                                           |
| Ruby                        | 2.6.8                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.32.0 (Apple Git-132)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 12.2 (21D49)                                             |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 13.2.1                                                         |
| Swift Version               | 5.5.2                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_AT.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Resigns the App Store build with the enterprise account details"
  
lane :demo do
  resign(
    ipa: "./resigned_enterprise_demo_app.ipa",
    signing_identity: "iPhone Distribution: XYZ GmbH",
    bundle_id: "com.xyz.demo",
    provisioning_profile: {
      "de.xyz“ => „./XYZ_Demo_App.mobileprovision",
      "de.xyz.watchkitapp“ => „./XYZ_Demo_Watch_App.mobileprovision",
      "de.xyz.watchkitapp.watchkitextension" => „./XYZ_Demo_Watch_App_Extension.mobileprovision",
    },
    use_app_entitlements: false
  )
end


end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.204.3 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.5.0        |
| CFPropertyList                  | 2.3.6        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.78.0       |
| ruby2_keywords                  | 0.0.2        |
| faraday                         | 1.1.0        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.3        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.0.0        |
| fastimage                       | 2.2.0        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.1.0        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.0        |
| rubyzip                         | 2.3.0        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.0        |
| dotenv                          | 2.7.6        |
| simctl                          | 1.6.8        |
| jwt                             | 2.2.2        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| declarative-option              | 0.1.0        |
| representable                   | 3.0.4        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.0.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| signet                          | 0.16.0       |
| googleauth                      | 0.17.1       |
| httpclient                      | 2.8.3        |
| webrick                         | 1.4.4        |
| google-apis-core                | 0.4.1        |
| google-apis-playcustomapp_v1    | 0.5.0        |
| google-apis-androidpublisher_v3 | 0.11.0       |
| google-cloud-env                | 1.4.0        |
| google-cloud-errors             | 1.0.1        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.7.0        |
| google-apis-storage_v1          | 0.6.0        |
| rake                            | 13.0.1       |
| digest-crc                      | 0.6.1        |
| google-cloud-storage            | 1.34.1       |
| emoji_regex                     | 3.2.1        |
| jmespath                        | 1.4.0        |
| aws-partitions                  | 1.402.0      |
| aws-eventstream                 | 1.1.0        |
| aws-sigv4                       | 1.2.2        |
| aws-sdk-core                    | 3.109.3      |
| aws-sdk-kms                     | 1.39.0       |
| aws-sdk-s3                      | 1.86.0       |
| rexml                           | 3.2.5        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.0.3        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.21.0       |
| bundler                         | 2.1.4        |
| forwardable                     | 1.2.0        |
| logger                          | 1.3.0        |
| stringio                        | 0.0.2        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| date                            | 2.0.0        |
| io-console                      | 0.4.7        |
| fileutils                       | 1.1.0        |
| etc                             | 1.0.1        |
| zlib                            | 1.0.0        |
| libxml-ruby                     | 3.2.1        |
| psych                           | 3.1.0        |
| mutex_m                         | 0.1.0        |
</details>

*generated on:* **2022-02-18**
</details>

**Comment by AdalbertoMadden** [comment]
Thank you for sharing your valuable solution, it's work properly.

**Comment by Patsy69** [comment]
I now need to make a change to an app but what used to compile without error is now failing at the codesign step with:
Signing Identity: "-"
