### ISSUE TITLE
app.get_edit_app_store_version || app.get_latest_app_store_version || app.get_live_app_store_version ，What exactly did you use App Store Connect API

### ISSUE THREAD

**Issue by DreamPWJ** [fastlane/fastlane#19986]
Other than ruby, are you going to provide a node version, because node is used by more people
![image](https://user-images.githubusercontent.com/16730031/154593958-7d6bfd72-db5f-4bd7-8f27-2aacc02aeaa5.png)
appInfos The interface could not get the version being submitted for review。

**Comment by DreamPWJ** [comment]
I have been asking questions in the question area for several months and no one has returned. Thank you for your answer

**Comment by lucgrabowski** [comment]
I don't think that node version is planned, but you're more than welcome to add pull requests with it. 
Please remember that this is an open source project and people work on it in their free time.
