### ISSUE TITLE
latest_testflight_build_number should return 0 if no prior build exists

### ISSUE THREAD

**Issue by igoriuz** [fastlane/fastlane#19988]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I want using the same code snippet for new projects. It looks something like this:

```
increment_build_number({
        build_number: latest_testflight_build_number(app_identifier: 'com.foo.bar') + 1
})
```

Unfortunately it updates my build number to 2 instead of 1 when uploading the very first IPA to TestFlight.

**Comment by EvanMasterson** [comment]
It supports the `initial_build_number` param https://docs.fastlane.tools/actions/latest_testflight_build_number/
```
increment_build_number({
  build_number: latest_testflight_build_number(app_identifier: 'com.foo.bar', initial_build_number: 0) + 1
})
```

**Comment by igoriuz** [comment]
> It supports the `initial_build_number` param https://docs.fastlane.tools/actions/latest_testflight_build_number/
> 
> ```
> increment_build_number({
>   build_number: latest_testflight_build_number(app_identifier: 'com.foo.bar', initial_build_number: 0) + 1
> })
> ```

Great. Thanks.
