### ISSUE TITLE
Scan prefixes every "touching" output with "Running tests: "

### ISSUE THREAD

**Issue by gsbernstein** [fastlane/fastlane#20014]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Steps:
Run scan on a project

Expected:
"Touch" outputs match the rest of the output

Actual:
Every time scan outputs a "touch" command to the log, it prefixes the string "Running Tests:"

<img width="450" alt="Screen Shot 2022-02-24 at 6 08 55 PM" src="https://user-images.githubusercontent.com/6655924/155640288-e87828f3-6d43-4677-8dc9-1d9d7f88af9e.png">

# Note:
xcpretty does not include the string "Running Tests:" anywhere in its source. Fastlane does in three places, and in all places it's explicitly checking for the string "Touching". This is the one that seems related to scan:
https://github.com/fastlane/fastlane/blob/74ffd23a7ea1221b2a98df619d6ef0c9645a0abd/scan/lib/scan/runner.rb#L70-L77
I don't totally understand this code but it looks intentional as far as I can tell, so maybe you know what's going on.

##### Command executed
```
    scan(
      workspace: "Vida.xcworkspace",
      scheme: "AllTests",
      devices: ["iPhone 12"],
      xcpretty_formatter: "./fastlane/xcpretty_formatter.rb",
      skip_package_dependencies_resolution: true
    )
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 12.3                                                           |
| Ruby                        | 2.6.8                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.30.1 (Apple Git-130)                             |
| Installation Source         | ~/source/via_ios/vendor/bundle/ruby/2.6.0/bin/fastlane         |
| Host                        | macOS 12.3 (21E5196i)                                          |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode13.1.app/Contents/Developer/                |
| Xcode Version               | 13.1                                                           |
| Swift Version               | 5.5.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile` (relevant parts)</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.104.0"

default_platform :ios

platform :ios do

  desc "Runs all the unit tests"
  lane :test do
    scan(
      workspace: "Vida.xcworkspace",
      scheme: "AllTests",
      devices: ["iPhone 12"],
      xcpretty_formatter: "./fastlane/xcpretty_formatter.rb",
      skip_package_dependencies_resolution: true
    )
  end

end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.vida.vida" # The bundle identifier of your app
apple_id "ios-devs@vida.com" # Your Apple email address

team_id "59VUAD6Y56"  # Developer Portal Team ID

for_lane :deploy_design_system_app do
  app_identifier "com.vida.designsystem"
end

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.204.3 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.3.2   | ✅ Up-To-Date  |
| fastlane-plugin-browserstack              | 0.3.2   | ✅ Up-To-Date  |
| fastlane-plugin-google_cloud_storage      | 0.1.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.3.0        |
| bundler                                   | 2.2.4        |
| rake                                      | 13.0.6       |
| rexml                                     | 3.2.5        |
| CFPropertyList                            | 3.0.5        |
| concurrent-ruby                           | 1.1.9        |
| i18n                                      | 1.10.0       |
| minitest                                  | 5.15.0       |
| tzinfo                                    | 2.0.4        |
| zeitwerk                                  | 2.5.4        |
| activesupport                             | 6.1.4.6      |
| public_suffix                             | 4.0.6        |
| addressable                               | 2.8.0        |
| httpclient                                | 2.8.3        |
| json                                      | 2.6.1        |
| algoliasearch                             | 1.27.5       |
| artifactory                               | 3.0.15       |
| atomos                                    | 0.1.3        |
| aws-eventstream                           | 1.2.0        |
| aws-partitions                            | 1.558.0      |
| aws-sigv4                                 | 1.4.0        |
| jmespath                                  | 1.6.0        |
| aws-sdk-core                              | 3.127.0      |
| aws-sdk-kms                               | 1.55.0       |
| aws-sdk-s3                                | 1.113.0      |
| babosa                                    | 1.0.4        |
| claide                                    | 1.1.0        |
| fuzzy_match                               | 2.0.4        |
| nap                                       | 1.1.0        |
| netrc                                     | 0.11.0       |
| ffi                                       | 1.15.5       |
| ethon                                     | 0.15.0       |
| typhoeus                                  | 1.4.0        |
| cocoapods-core                            | 1.11.2       |
| cocoapods-deintegrate                     | 1.0.5        |
| cocoapods-downloader                      | 1.5.1        |
| cocoapods-plugins                         | 1.0.0        |
| cocoapods-search                          | 1.0.1        |
| cocoapods-trunk                           | 1.6.0        |
| cocoapods-try                             | 1.2.0        |
| colored2                                  | 3.1.2        |
| escape                                    | 0.0.4        |
| fourflusher                               | 2.3.1        |
| gh_inspector                              | 1.1.3        |
| molinillo                                 | 0.8.0        |
| ruby-macho                                | 2.5.1        |
| nanaimo                                   | 0.3.0        |
| xcodeproj                                 | 1.21.0       |
| cocoapods                                 | 1.11.2       |
| colored                                   | 1.2          |
| highline                                  | 2.0.3        |
| commander                                 | 4.6.0        |
| declarative                               | 0.0.20       |
| digest-crc                                | 0.6.4        |
| unf_ext                                   | 0.0.8        |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| dotenv                                    | 2.7.6        |
| emoji_regex                               | 3.2.3        |
| excon                                     | 0.91.0       |
| faraday-em_http                           | 1.0.0        |
| faraday-em_synchrony                      | 1.0.0        |
| faraday-excon                             | 1.1.0        |
| faraday-httpclient                        | 1.0.1        |
| multipart-post                            | 2.0.0        |
| faraday-multipart                         | 1.0.3        |
| faraday-net_http                          | 1.0.1        |
| faraday-net_http_persistent               | 1.2.0        |
| faraday-patron                            | 1.0.0        |
| faraday-rack                              | 1.0.0        |
| faraday-retry                             | 1.0.3        |
| ruby2_keywords                            | 0.0.5        |
| faraday                                   | 1.10.0       |
| http-cookie                               | 1.0.4        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.2.0        |
| fastimage                                 | 2.2.6        |
| jwt                                       | 2.3.0        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.4        |
| signet                                    | 0.16.1       |
| googleauth                                | 1.1.2        |
| mini_mime                                 | 1.1.2        |
| trailblazer-option                        | 0.1.2        |
| uber                                      | 0.1.0        |
| representable                             | 3.1.1        |
| retriable                                 | 3.1.2        |
| webrick                                   | 1.7.0        |
| google-apis-core                          | 0.4.2        |
| google-apis-androidpublisher_v3           | 0.16.0       |
| google-apis-playcustomapp_v1              | 0.7.0        |
| google-apis-iamcredentials_v1             | 0.10.0       |
| google-apis-storage_v1                    | 0.11.0       |
| google-cloud-env                          | 1.5.0        |
| google-cloud-errors                       | 1.2.0        |
| google-cloud-core                         | 1.6.0        |
| google-cloud-storage                      | 1.36.1       |
| mini_magick                               | 4.11.0       |
| naturally                                 | 2.2.1        |
| optparse                                  | 0.1.1        |
| plist                                     | 3.6.0        |
| rubyzip                                   | 2.3.2        |
| security                                  | 0.1.3        |
| simctl                                    | 1.6.8        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.8.0        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| word_wrap                                 | 1.0.0        |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.1        |
| http-accept                               | 1.7.0        |
| mime-types-data                           | 3.2022.0105  |
| mime-types                                | 3.4.1        |
| rest-client                               | 2.1.0        |
| fastlane-plugin-browserstack              | 0.3.2        |
| fastlane-plugin-firebase_app_distribution | 0.3.2        |
| fastlane-plugin-google_cloud_storage      | 0.1.1        |
</details>

*generated on:* **2022-02-24**
</details> </pre>
</details>

**Comment by gsbernstein** [comment]
Not sure I understand. Are you saying that these lines coincidentally represent the beginning of a block?

**Comment by Russel476** [comment]
Everything works fine on the first pass as com.myapp.dev is processed. When the 2nd scheme is run, it errors after Gym completes. Export fails and the pipeline stops.
