### ISSUE TITLE
[precheck] check locally metadata first

### ISSUE THREAD

**Issue by rehannali** [fastlane/fastlane#20029]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I run `precheck` before everything and it is expected to check precheck before initiating process. I updated local metadata and `precheck` utility ignores it instead it check live like copyright or URLs. 
It should check first local instead of live.

##### Command executed

`precheck` in `Fastfile`

**Comment by Hinderlit** [comment]
Will give a try to modify_services action then.

But it's really strange that enable_services is in the documentation of produce action if it's not working ..

By the way, executing the action directly by command line is working perfectly :
