### ISSUE TITLE
SPM: Confusing error message `The workspace named "<workspace>" does not contain a scheme named "xcode".`

### ISSUE THREAD

**Issue by jkmathew** [fastlane/fastlane#20039]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When running a lane that uses scan confusing error messge is printed `The workspace named "<woorkspace>" does not contain a scheme named "xcode".`

Steps to reproduce,
1. Create an SPM package for iOS.
2. Setup a lane that calls `scan` with default workspace.
3. Invoke the lane 4. 
<details><summary>Example Package.swift file</summary>

```swift
// swift-tools-version:5.3
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
  name: "spm_fastlane",
  platforms: [.iOS(.v11)],
  products: [
    .library(
      name: "spm_fastlane",
      targets: ["spm_fastlane"]),
  ],
  dependencies: [
    .package(name: "Lottie", url: "git@github.com:airbnb/lottie-ios.git", .exact("3.2.3"))
  ],
  targets: [
    .target(
      name: "spm_fastlane",
      dependencies: ["Lottie"]),
    .testTarget(
      name: "spm_fastlaneTests",
      dependencies: ["spm_fastlane"]),
  ]
)
```
</details>

### Lane
```ruby
  lane :spm_test do
    scan(
      workspace: './.swiftpm/xcode/package.xcworkspace',
      device: "iOS Simulator",
      scheme: "spm_fastlane",
      derived_data_path: ".build",
      clean: false,
      code_coverage: true
    )
  end
```
When running `bundle exec fastlane spm_test`, somehow fastlane converts this to xcodebuild like `xcodebuild -resolvePackageDependencies -workspace ./.swiftpm/xcode/package.xcworkspace -scheme xcode -derivedDataPath .build` . _Note the **scheme** argument here._
And this gives the error` xcodebuild: error: The workspace named "spm_fastlane" does not contain a scheme named "xcode". The "-list" option can be used to find the names of the schemes in the workspace.`

When I run `xcodebuild -list -workspace ./.swiftpm/xcode/package.xcworkspace`, I can see the scheme `spm_fastlane` listed in the output.

<details><summary>`xcodebuild -list -workspace ./.swiftpm/xcode/package.xcworkspace`    </summary>

```
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list -workspace ./.swiftpm/xcode/package.xcworkspace

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

Resolve Package Graph

Resolved source packages:
  spm_fastlane: /Users/j.mathew/Documents/DH/Project/spm_fastlane
  Lottie: git@github.com:airbnb/lottie-ios.git @ 3.2.3

Information about workspace "spm_fastlane":
    Schemes:
        spm_fastlane
```
</details>

From the error log, I could see that the error is because the scheme is not shared. Still `... does not contain a scheme named "xcode"` is confusing.
##### Command executed
`bundle exec fastlane <lane name>`

##### Complete output when running fastlane, including the stack trace and command used

<details>
[✔] 🚀
[10:21:23]: ------------------------------
[10:21:23]: --- Step: default_platform ---
[10:21:23]: ------------------------------
[10:21:23]: Driving the lane 'ios spm_test' 🚀
[10:21:24]: ------------------
[10:21:24]: --- Step: scan ---
[10:21:24]: ------------------
[10:21:24]: Couldn't find specified scheme 'spm_fastlane'. Please make sure that the scheme is shared, see https://developer.apple.com/library/content/documentation/IDEs/Conceptual/xcode_guide-continuous_integration/ConfigureBots.html#//apple_ref/doc/uid/TP40013292-CH9-SW3
[10:21:24]: Resolving Swift Package Manager dependencies...
[10:21:24]: $ xcodebuild -resolvePackageDependencies -workspace ./.swiftpm/xcode/package.xcworkspace -scheme xcode -derivedDataPath .build
[10:21:25]: ▸ Command line invocation:
[10:21:25]: ▸     /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -workspace ./.swiftpm/xcode/package.xcworkspace -scheme xcode -derivedDataPath .build
[10:21:25]: ▸ User defaults from command line:
[10:21:25]: ▸     IDEDerivedDataPathOverride = /Users/j.mathew/Documents/spm_fastlane/.build
[10:21:25]: ▸     IDEPackageSupportUseBuiltinSCM = YES
[10:21:25]: ▸ Resolve Package Graph
[10:21:26]: ▸ Resolved source packages:
[10:21:26]: ▸   Lottie: git@github.com:airbnb/lottie-ios.git @ 3.2.3
[10:21:26]: ▸   spm_fastlane: /Users/j.mathew/Documents/spm_fastlane
[10:21:26]: ▸ xcodebuild: error: The workspace named "spm_fastlane" does not contain a scheme named "xcode". The "-list" option can be used to find the names of the schemes in the workspace.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -workspace ./.swiftpm/xcode/package.xcworkspace -scheme xcode -derivedDataPath .build

User defaults from command line:
    IDEDerivedDataPathOverride = /Users/j.mathew/Documents/spm_fastlane/.build
    IDEPackageSupportUseBuiltinSCM = YES

Resolve Package Graph

Resolved source packages:
  Lottie: git@github.com:airbnb/lottie-ios.git @ 3.2.3
  spm_fastlane: /Users/j.mathew/Documents/spm_fastlane

xcodebuild: error: The workspace named "spm_fastlane" does not contain a scheme named "xcode". The "-list" option can be used to find the names of the schemes in the workspace.
[10:21:26]: Exit status: 65
+------------------------------+--------------+
|                Lane Context                 |
+------------------------------+--------------+
| DEFAULT_PLATFORM             | ios          |
| PLATFORM_NAME                | ios          |
| LANE_NAME                    | ios spm_test |
| SCAN_GENERATED_XCRESULT_PATH |              |
| SCAN_DERIVED_DATA_PATH       | .build       |
| SCAN_GENERATED_PLIST_FILES   | []           |
| SCAN_GENERATED_PLIST_FILE    |              |
+------------------------------+--------------+
[10:21:26]: Exit status: 65

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 💥   | scan             | 2           |
+------+------------------+-------------+

[10:21:26]: fastlane finished with errors

[!] Exit status: 65
</details>

### Environment

<details>
  <pre><details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.5.1                                      |
| Ruby                        | 2.6.5                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.30.1 (Apple Git-130)          |
| Installation Source         | ~/.gem/bin/fastlane                         |
| Host                        | macOS 11.5.1 (20G80)                        |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.5/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.5.1                                      |
| Swift Version               | 5.4.2                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

default_platform(:ios)

platform :ios do
  desc "Test with spm"
  lane :spm_test do
    scan(
      workspace: './.swiftpm/xcode/package.xcworkspace',
      device: "iOS Simulator",
      scheme: "spm_fastlane",
      derived_data_path: ".build",
      clean: false,
      code_coverage: true
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.204.3 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| bundler                         | 2.2.32       |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.563.0      |
| aws-sigv4                       | 1.4.0        |
| jmespath                        | 1.6.1        |
| aws-sdk-core                    | 3.128.1      |
| aws-sdk-kms                     | 1.55.0       |
| aws-sdk-s3                      | 1.113.0      |
| babosa                          | 1.0.4        |
| claide                          | 1.1.0        |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.91.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.0.0        |
| faraday-multipart               | 1.0.3        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.0       |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.3.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.1       |
| googleauth                      | 1.1.2        |
| httpclient                      | 2.8.3        |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.2        |
| google-apis-androidpublisher_v3 | 0.16.0       |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.11.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.36.1       |
| json                            | 2.6.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
</details>

*generated on:* **2022-03-08**
</details> </pre>
</details>

**Comment by Kukurijek** [comment]
`Setup a lane that calls scan with default workspace.` - so you have a default workspace called `package` located in `./.swiftpm/xcode/package.xcworkspace` ?

**Comment by Farr69** [comment]
If you don't use cocoapods in your project you should remove .xcworkspace file from ./ios directory.
