### ISSUE TITLE
Enable_services : criticals_alerts is undefined

### ISSUE THREAD

**Issue by velco-greg** [fastlane/fastlane#20046]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Executing produce action with enable_services options raised an error saying that "criticals_alerts" is an undefined method

##### Command executed

```
produce(
      username: FASTLANE_APPLE_ID,
      app_identifier: configuration[:bundle_id],
      app_name: "#{configuration[:brand]} #{configuration[:target].upcase}",
      language: 'en-US',
      app_version: '1.0',
      sku: configuration[:sku],
      platform: configuration[:platform],
      team_id: APP_STORE_CONNECT_TEAM_ID,
      enable_services: {
        critical_alerts: "on",
        push_notification: "on"
      }
    )

## STACKTRACE ##
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/produce/lib/produce/developer_center.rb:148:in `block in enable_services': \e[31m[!] undefined method `critical_alerts' for Spaceship::Portal::AppService:Class\e[0m (NoMethodError)
	from /Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/produce/lib/produce/developer_center.rb:127:in `each'
	from /Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/produce/lib/produce/developer_center.rb:127:in `enable_services'
	from /Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/produce/lib/produce/developer_center.rb:99:in `create_new_app'
	from /Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/produce/lib/produce/developer_center.rb:84:in `run'
	from /Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/produce/lib/produce/manager.rb:11:in `start_producing'
	from /Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/actions/create_app_online.rb:17:in `block in run'
	from /Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/actions/create_app_online.rb:15:in `chdir'
	from /Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/actions/create_app_online.rb:15:in `run'
	from /Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:151:in `block (2 levels) in parsing_binding'
	from /Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	from /Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	from /Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/gems/fastlane-2.204.3/bin/fastlane:23:in `<top (required)>'
	from /Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/bin/fastlane:25:in `load'
	from /Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/bin/fastlane:25:in `<main>'
	from /Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/bin/ruby_executable_hooks:22:in `eval'
	from /Users/gregoirefreuchet/.rvm/gems/ruby-3.0.0/bin/ruby_executable_hooks:22:in `<main>'
```

### Captured Output

Command Used: `create_brand --capture_output`
<details><summary>Output/Log</summary>

```

DEBUG [2022-03-10 09:56:54.48]: Checking if there are any plugins that should be loaded...
DEBUG [2022-03-10 09:56:54.48]: Loading 'fastlane-plugin-appicon' plugin
INFO [2022-03-10 09:56:54.48]: gem 'fastlane-plugin-appicon' is already installed
DEBUG [2022-03-10 09:56:54.49]: Loading 'fastlane-plugin-json' plugin
INFO [2022-03-10 09:56:54.49]: gem 'fastlane-plugin-json' is already installed
DEBUG [2022-03-10 09:56:54.50]: Loading 'fastlane-plugin-file_manager' plugin
INFO [2022-03-10 09:56:54.50]: gem 'fastlane-plugin-file_manager' is already installed

```

</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 12.1                                             |
| Ruby                        | 3.0.0                                            |
| Bundler?                    | true                                             |
| Git                         | git version 2.30.1 (Apple Git-130)               |
| Installation Source         | ~/.rvm/gems/ruby-3.0.0/bin/fastlane              |
| Host                        | macOS 12.1 (21C52)                               |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-3.0.0/lib                     |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode_13.1.app/Contents/Developer/ |
| Xcode Version               | 13.1                                             |
| Swift Version               | 5.5.1                                            |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

default_platform(:ios)

before_all do
  update_fastlane
end

platform :ios do

  lane :brand_configuration do
    configuration = {}
    brand = prompt(text: "Brand name: ")
    configuration[:brand] = brand
    target = prompt(text: "Target environnement: ")
    configuration[:target] = target
    configuration[:bundle_id] = "bike.velco.#{brand.downcase.gsub(/\s+/, ".")}.#{target.downcase}"
    configuration[:sku] = "bike-velco-#{brand.downcase.gsub(/\s+/, "-")}-#{target.downcase}"
    configuration[:platform] = "ios"
    puts configuration
    configuration
  end

  lane :create_brand do
    # Configure App
    configuration = brand_configuration

    # Create Application on AppStoreConnect
    produce(
      username: FASTLANE_APPLE_ID,
      app_identifier: configuration[:bundle_id],
      app_name: "#{configuration[:brand]} #{configuration[:target].upcase}",
      language: 'en-US',
      app_version: '1.0',
      sku: configuration[:sku],
      platform: configuration[:platform],
      team_id: APP_STORE_CONNECT_TEAM_ID,
      itc_team_id: ***,
      enable_services: {
        critical_alerts: "on",
        push_notification: "on"
      }
    )

    # Create Certificates
    match(app_identifier: [configuration[:bundle_id]])

    # Create Directory to stock APNS Locally
    apns_path = "***"
    sh "mkdir -p #{apns_path}"

    # Create Push Notification Certificates
    pem(
      username: FASTLANE_APPLE_ID,
      app_identifier: configuration[:bundle_id],
      platform: configuration[:platform],
      team_id: APP_STORE_CONNECT_TEAM_ID,
      output_path: "#{apns_path}"
    )
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier(ENV["DEVELOPER_APP_IDENTIFIER"])
apple_id(ENV["FASTLANE_APPLE_ID"])
itc_team_id(ENV["APP_STORE_CONNECT_TEAM_ID"])
team_id(ENV["DEVELOPER_PORTAL_TEAM_ID"])
# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.204.3 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                       | Version | Update-Status |
| ---------------------------- | ------- | ------------- |
| fastlane-plugin-appicon      | 0.16.0  | ✅ Up-To-Date  |
| fastlane-plugin-json         | 1.1.0   | ✅ Up-To-Date  |
| fastlane-plugin-file_manager | 0.2.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| executable-hooks                | 1.6.1        |
| bundler-unload                  | 1.0.2        |
| rubygems-bundler                | 1.4.5        |
| bundler                         | 2.2.27       |
| pathname                        | 0.1.0        |
| tsort                           | 0.1.0        |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| concurrent-ruby                 | 1.1.9        |
| i18n                            | 1.10.0       |
| minitest                        | 5.15.0       |
| tzinfo                          | 2.0.4        |
| zeitwerk                        | 2.5.4        |
| activesupport                   | 6.1.4.6      |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| httpclient                      | 2.8.3        |
| json                            | 2.6.1        |
| algoliasearch                   | 1.27.5       |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.554.0      |
| aws-sigv4                       | 1.4.0        |
| jmespath                        | 1.6.0        |
| aws-sdk-core                    | 3.126.1      |
| aws-sdk-kms                     | 1.54.0       |
| aws-sdk-s3                      | 1.112.0      |
| babosa                          | 1.0.4        |
| builder                         | 3.2.4        |
| claide                          | 1.0.3        |
| fuzzy_match                     | 2.0.4        |
| nap                             | 1.1.0        |
| netrc                           | 0.11.0       |
| ffi                             | 1.15.5       |
| ethon                           | 0.15.0       |
| typhoeus                        | 1.4.0        |
| cocoapods-core                  | 1.11.2       |
| cocoapods-deintegrate           | 1.0.5        |
| cocoapods-downloader            | 1.5.1        |
| cocoapods-plugins               | 1.0.0        |
| cocoapods-search                | 1.0.1        |
| cocoapods-trunk                 | 1.6.0        |
| cocoapods-try                   | 1.2.0        |
| colored2                        | 3.1.2        |
| escape                          | 0.0.4        |
| fourflusher                     | 2.3.1        |
| gh_inspector                    | 1.1.3        |
| molinillo                       | 0.8.0        |
| ruby-macho                      | 2.5.1        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| cocoapods                       | 1.11.2       |
| cocoapods-generate              | 1.4.1        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.91.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.0.0        |
| faraday-multipart               | 1.0.3        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.9.3        |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| jwt                             | 2.3.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.1        |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.2        |
| google-apis-androidpublisher_v3 | 0.16.0       |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.11.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.36.1       |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| fastlane-plugin-appicon         | 0.16.0       |
| fastlane-plugin-file_manager    | 0.2.0        |
| fastlane-plugin-json            | 1.1.0        |
| net                             | 0.3.3        |
| poesie                          | 1.5.2        |
| xcode-install                   | 2.8.0        |
</details>

*generated on:* **2022-03-10**
</details>

**Comment by lucgrabowski** [comment]
Hi @velco-greg, you could find a workaround in https://github.com/fastlane/fastlane/issues/19201

**Comment by velco-greg** [comment]
Thanks @lucgrabowski 
Will give a try to modify_services action then.

But it's really strange that enable_services is in the documentation of produce action if it's not working ..

By the way, executing the action directly by command line is working perfectly :
`bundle exec fastlane produce enable_services -a <BUNDLE_ID> --push-notification --critical-alerts`

So I guess there is a bug in produce action when executed by a lane
