### ISSUE TITLE
Wear Screenshots don't match Play guidance on Round Devices

### ISSUE THREAD

**Issue by yschimke** [fastlane/fastlane#20053]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Screenshots on Round wear devices include the frame, possibly also included in Square.
However these are not acceptable for the Play Store.

https://support.google.com/googleplay/android-developer/answer/9866151#zippy=%2Cscreenshots

    Upload screenshots with a minimum size of 384 x 384 pixels, and with a 1:1 aspect ratio.
    Provide screenshots showing only your app interface. Screenshots must demonstrate the actual in-app or in-game experience, focusing on the core features and content so that users can anticipate what the app or game experience will be like.
    Don’t frame your screenshots in a Wear OS hardware device.
    Don’t include additional text, graphics or backgrounds in your Wear OS screenshots that are not a part of your app's interface.
    Don’t include transparent backgrounds or masking.

##### Command executed

`fastlane screenshots`

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/231923/157934444-0ce1cdee-9587-4ad0-a4b4-67ebd3700e7a.png">

The left two are my playstore images, the 3rd is the default fastlane image, and the 4th is my customised WearScreenshotStrategy.

This is a draft, and I still need to remove the transparency.

```
import android.graphics.Bitmap
import android.graphics.Color
import android.graphics.Paint
import android.graphics.PorterDuff
import android.graphics.PorterDuffXfermode
import androidx.core.graphics.applyCanvas
import androidx.test.platform.app.InstrumentationRegistry
import tools.fastlane.screengrab.ScreenshotCallback
import tools.fastlane.screengrab.ScreenshotStrategy
import kotlin.math.min

class WearScreenshotStrategy(val isRoundDevice: Boolean) : ScreenshotStrategy {
    override fun takeScreenshot(screenshotName: String, screenshotCallback: ScreenshotCallback) {
        val uiAutomation = InstrumentationRegistry.getInstrumentation().uiAutomation
        var screenshot = uiAutomation.takeScreenshot()

        if (isRoundDevice) {
            screenshot = circularClip(screenshot)
        }

        screenshotCallback.screenshotCaptured(screenshotName, screenshot)
    }

    fun circularClip(image: Bitmap): Bitmap {
        // From https://github.com/coil-kt/coil/blob/2.0.0-rc01/coil-base/src/main/java/coil/transform/CircleCropTransformation.kt
        val paint = Paint(Paint.ANTI_ALIAS_FLAG or Paint.FILTER_BITMAP_FLAG)

        val minSize = min(image.width, image.height)
        val radius = minSize / 2f
        val output = Bitmap.createBitmap(image.width, image.height, Bitmap.Config.ARGB_8888)
        output.applyCanvas {
            drawCircle(radius, radius, radius, paint)
            paint.xfermode = PorterDuffXfermode(PorterDuff.Mode.SRC_IN)
            drawBitmap(image, radius - image.width / 2f, radius - image.height / 2f, paint)
            drawColor(Color.WHITE, PorterDuff.Mode.DST_OVER)
        }

        return output
    }
}
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
```
 fastlane screenshots --capture_output
[✔] 🚀 
[18:59:44]: fastlane detected a Gemfile in the current directory
[18:59:44]: However, it seems like you didn't use `bundle exec`
[18:59:44]: To launch fastlane faster, please use
[18:59:44]: 
[18:59:44]: $ bundle exec fastlane screenshots --capture_output
[18:59:44]: 
[18:59:44]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2022-03-11 18:59:44.62]: Checking if there are any plugins that should be loaded...
DEBUG [2022-03-11 18:59:44.65]: Couldn't find xcodebuild at /Library/Developer/CommandLineTools//usr/bin/xcodebuild, check that it exists
```
 </pre>
</details>

### Environment

<details>
  <pre> 
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 12.2.1                                                     |
| Ruby                        | 3.1.1                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.32.0 (Apple Git-132)                         |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.204.3/libexec/bin/fastlane |
| Host                        | macOS 12.2.1 (21D62)                                       |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.1.1/lib                        |
| OpenSSL Version             | OpenSSL 1.1.1m  14 Dec 2021                                |
| Is contained                | false                                                      |
| Is homebrew                 | true                                                       |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Library/Developer/CommandLineTools/                       |
| Xcode Version               |                                                            |
| Swift Version               | 5.5.2                                                      |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Google Play"
  lane :beta do
    gradle(task: "clean assembleRelease")
    upload_to_play_store(track: 'beta')
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  lane :screenshots do
    build_android_app(
      task: 'assemble',
      build_type: 'Debug'
    )
    build_android_app(
      task: 'assemble',
      build_type: 'AndroidTest'
    )
    capture_android_screenshots(
        locales: ["en-US"],
        app_apk_path: "./wear/build/intermediates/apk/debug/rememberwear-debug.apk",
        tests_apk_path: "./wear/build/intermediates/apk/androidTest/debug/rememberwear-debug-androidTest.apk",
        device_type: "wear",
        test_instrumentation_runner: "com.google.wear.soyted.junit.CustomTestRunner",
        use_tests_in_packages: "com.google.wear.soyted.fastlane",
        skip_open_summary: false
    )
#     upload_to_play_store
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("fastlane/pc-api.json") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("ee.schimke.wear.soyted")

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.204.3 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.91.0       |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.6.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.3.7        |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.2        |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-androidpublisher_v3 | 0.16.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.11.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.36.1       |
| emoji_regex                     | 3.2.3        |
| set                             | 1.0.2        |
| ruby2_keywords                  | 0.0.5        |
| faraday-retry                   | 1.0.3        |
| faraday-rack                    | 1.0.0        |
| faraday-patron                  | 1.0.0        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-net_http                | 1.0.1        |
| faraday-multipart               | 1.0.3        |
| faraday-httpclient              | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.10.0       |
| multi_json                      | 1.15.0       |
| signet                          | 0.16.1       |
| os                              | 1.1.4        |
| memoist                         | 0.16.2       |
| googleauth                      | 1.1.2        |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-partitions                  | 1.566.0      |
| jmespath                        | 1.6.1        |
| aws-sdk-core                    | 3.129.1      |
| aws-sdk-kms                     | 1.55.0       |
| aws-sdk-s3                      | 1.113.0      |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.1        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.1        |
| uri                             | 0.11.0       |
| openssl                         | 3.0.0        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.0        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.2        |
| net-http                        | 0.2.0        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.11       |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.3        |
</details>

*generated on:* **2022-03-11**
</details>
 </pre>
</details>

**Comment by yschimke** [comment]
Should be black background

```
drawColor(Color.BLACK, PorterDuff.Mode.DST_OVER)
```

**Comment by Nebel69** [comment]
I am also encountering this issue.

**Comment by Ryan42000** [comment]
SCV records in ClinVar may be updated by the submitter at any time, but only by the submitter. For example, interpretations of clinical significance or condition may be refined or more observations of the variant may be registered. Each SCV accession is versioned so that updates to content are tracked.

**Comment by yschimke** [comment]
I'd love someone to look at the PR https://github.com/fastlane/fastlane/pull/20054

**Comment by yschimke** [comment]
This was a poor experience with an open source project. Oooooffff.
