### ISSUE TITLE
[Feature] two factor authentication for automation use

### ISSUE THREAD

**Issue by martinimartinimartini** [fastlane/fastlane#20056]
Hey guys!
I'm currently using fast lane in a large environment and i'm having some time issues with the workflow, more specific with the token utilization.
I have a pipeline implemented that is stopping on a manual human intervention because of the SMS interaction.
Is there any possible way to change that? By that I mean something that I can listen on and trigger the next step on the pipeline.

Thanks a lot.

**Comment by rogerluan** [comment]
Hey @martinimartinimartini 👋 

I've transferred this issue to the correct repository (from `fastlane/docs` to `fastlane/fastlane`).

Regarding your query, you should try to use App Store Connect API as much as possible, so you're not prompted with 2FA code. Here's its documentation: https://docs.fastlane.tools/app-store-connect-api/

Good luck!

**Comment by martinimartinimartini** [comment]
After a few days I got my key_id, issuer_id and key.
But how do I use it for update xcode on CLI?
There is no information about the app_store_coinnect_api_key for the CLI update (https://docs.fastlane.tools/actions/xcode_install/)

**Comment by rogerluan** [comment]
There's no way to use App Store Connect API Key to download xcode as of today. For more info see https://github.com/xcpretty/xcode-install/issues/436 and https://github.com/xcpretty/xcode-install/issues/395 - I see you already found your way to https://github.com/xcpretty/xcode-install/issues/436#issuecomment-1087790335 so I'm closing this issue as it's not related to fastlane 🙏
