### ISSUE TITLE
StandAlone WatchOS App Not Building

### ISSUE THREAD

**Issue by bradmartin** [fastlane/fastlane#20066]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

App builds and archives fine in Xcode 13.2.1 locally for WatchOS application.

App build fails when trying to build with fastlane.

The output indicates the destination is not found. I've tried putting the destination into the build process using a `GymFile` using `xcodebuild` directly and same result every time. Have tried on 2 different macbooks running Big Sur `11.4` and XCode `13.2.1`.

This is out first WatchOS stand alone application and I can't find anything relevant in previous issues regarding this error specific to WatchOS stand alone apps. I noticed a PR in 2020 added support for `gym` to target platform `watchOS` but nothing else. 

A sample stand alone WatchOS I couldn't find in the examples repo either, not sure what needs to be configured to get fastlane to build the project correctly.

At the end of the day I just want to get the archiving process working and then I'll tackle other avenues of fastlane (tests, upload, etc). Just cannot seem to get a proper build for the watchOS app.

Also, I can hop over in XCode and archive with no issues just to clarify that the system seems configured just fine to build/archive the project as we've been doing for months. So it seems that something in the project might need a change for fastlane to properly build, just not sure what option to try. I've tried many configuration approaches, different flags, various schemes all end in the same result.

##### Command executed

`bundle exec fastlane beta`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
MacBook-Pro:SmartDrive-WatchOS bradmartin$ bundle exec fastlane beta
[14:08:38]: ------------------------------
[14:08:38]: --- Step: default_platform ---
[14:08:38]: ------------------------------
[14:08:38]: Driving the lane 'ios beta' 🚀
[14:08:38]: -----------------------
[14:08:38]: --- Step: build_app ---
[14:08:38]: -----------------------
[14:08:38]: Resolving Swift Package Manager dependencies...
[14:08:38]: $ xcodebuild -resolvePackageDependencies -workspace SmartDrive.xcworkspace -scheme Release\ SmartDrive\ WatchKit\ App
[14:08:38]: ▸ Command line invocation:
[14:08:38]: ▸     /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -workspace SmartDrive.xcworkspace -scheme "Release SmartDrive WatchKit App"
[14:08:38]: ▸ User defaults from command line:
[14:08:38]: ▸     IDEPackageSupportUseBuiltinSCM = YES
[14:08:39]: ▸ --- xcodebuild: WARNING: Using the first of multiple matching destinations:
[14:08:39]: ▸ { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
[14:08:39]: ▸ { platform:watchOS, id:dvtdevice-DVTiOSDevicePlaceholder-watchos:placeholder, name:Any watchOS Device }
[14:08:39]: ▸ { platform:iOS Simulator, id:5226263E-41A1-4559-83EB-D643337930EE, OS:15.2, name:iPhone 12 Pro }
[14:08:39]: ▸ { platform:iOS Simulator, id:5214DE78-40B3-4480-B88D-542FF8F01B8E, OS:15.2, name:iPhone 12 Pro Max }
[14:08:39]: ▸ { platform:iOS Simulator, id:BC02416F-C2F7-4513-A054-EBECA7AABC43, OS:15.2, name:iPhone 13 }
[14:08:39]: ▸ { platform:iOS Simulator, id:4E4DB372-0F47-4A19-9A55-3615EE005783, OS:15.2, name:iPhone 13 Pro }
[14:08:39]: ▸ { platform:iOS Simulator, id:0B19B3DD-EB28-4041-9A55-660BD7DC4CE6, OS:15.2, name:iPhone 13 Pro Max }
[14:08:39]: ▸ { platform:iOS Simulator, id:43C92747-79AD-48D1-BE5E-9E07FDA77EA3, OS:15.2, name:iPhone 13 mini }
[14:08:39]: ▸ resolved source packages: 
[14:08:39]: $ xcodebuild -showBuildSettings -workspace SmartDrive.xcworkspace -scheme Release\ SmartDrive\ WatchKit\ App
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
{ platform:watchOS, id:dvtdevice-DVTiOSDevicePlaceholder-watchos:placeholder, name:Any watchOS Device }
{ platform:iOS Simulator, id:5226263E-41A1-4559-83EB-D643337930EE, OS:15.2, name:iPhone 12 Pro }
{ platform:iOS Simulator, id:5214DE78-40B3-4480-B88D-542FF8F01B8E, OS:15.2, name:iPhone 12 Pro Max }
{ platform:iOS Simulator, id:BC02416F-C2F7-4513-A054-EBECA7AABC43, OS:15.2, name:iPhone 13 }
{ platform:iOS Simulator, id:4E4DB372-0F47-4A19-9A55-3615EE005783, OS:15.2, name:iPhone 13 Pro }
{ platform:iOS Simulator, id:0B19B3DD-EB28-4041-9A55-660BD7DC4CE6, OS:15.2, name:iPhone 13 Pro Max }
{ platform:iOS Simulator, id:43C92747-79AD-48D1-BE5E-9E07FDA77EA3, OS:15.2, name:iPhone 13 mini }
[!] Xcodeproj doesn't know about the following attributes {"buildSettings"=>{}, "buildStyles"=>["35BFAF6877A44092876F375F", "31EECEEC1A1C47B38C31A904", "0E9068A65A164A3AAB77A12A", "0D462F8BD47641978B85E162"]} for the 'PBXProject' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
[!] Xcodeproj doesn't know about the following attributes {"buildSettings"=>{}, "buildStyles"=>["35BFAF6877A44092876F375F", "31EECEEC1A1C47B38C31A904", "0E9068A65A164A3AAB77A12A", "0D462F8BD47641978B85E162"]} for the 'PBXProject' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new

+--------------------------------------+---------------------------------------------------------------+
|                                       Summary for gym 2.204.3                                        |
+--------------------------------------+---------------------------------------------------------------+
| workspace                            | SmartDrive.xcworkspace                                        |
| scheme                               | Release SmartDrive WatchKit App                               |
| clean                                | false                                                         |
| output_directory                     | .                                                             |
| output_name                          | SmartDrive WatchKit App                                       |
| silent                               | false                                                         |
| skip_package_ipa                     | false                                                         |
| skip_package_pkg                     | false                                                         |
| build_path                           | /Users/bradmartin/Library/Developer/Xcode/Archives/2022-03-15 |
| result_bundle                        | false                                                         |
| buildlog_path                        | ~/Library/Logs/gym                                            |
| destination                          | generic/platform=iOS                                          |
| xcodebuild_formatter                 | xcbeautify                                                    |
| skip_profile_detection               | false                                                         |
| xcodebuild_command                   | xcodebuild                                                    |
| skip_package_dependencies_resolution | false                                                         |
| disable_package_automatic_updates    | false                                                         |
| use_system_scm                       | false                                                         |
| xcode_path                           | /Applications/Xcode.app                                       |
+--------------------------------------+---------------------------------------------------------------+

[14:08:41]: $ set -o pipefail && xcodebuild -workspace SmartDrive.xcworkspace -scheme Release\ SmartDrive\ WatchKit\ App -destination 'generic/platform=iOS' -archivePath /Users/bradmartin/Library/Developer/Xcode/Archives/2022-03-15/SmartDrive\ WatchKit\ App\ 2022-03-15\ 14.08.41.xcarchive archive | tee /Users/bradmartin/Library/Logs/gym/SmartDrive\ WatchKit\ App-Release\ SmartDrive\ WatchKit\ App.log | xcbeautify
[14:09:13]: ▸ xcodebuild: error: Unable to find a destination matching the provided destination specifier:
[14:09:13]: ▸           { generic:1, platform:iOS }
[14:09:13]: ▸   The requested device could not be found because no available devices matched the request.
[14:09:13]: ▸   Available destinations for the "Release SmartDrive WatchKit App" scheme:
[14:09:13]: ▸           { platform:iOS Simulator, id:5226263E-41A1-4559-83EB-D643337930EE, OS:15.2, name:iPhone 12 Pro }
[14:09:13]: ▸           { platform:iOS Simulator, id:5214DE78-40B3-4480-B88D-542FF8F01B8E, OS:15.2, name:iPhone 12 Pro Max }
[14:09:13]: ▸           { platform:iOS Simulator, id:BC02416F-C2F7-4513-A054-EBECA7AABC43, OS:15.2, name:iPhone 13 }
[14:09:13]: ▸           { platform:iOS Simulator, id:4E4DB372-0F47-4A19-9A55-3615EE005783, OS:15.2, name:iPhone 13 Pro }
[14:09:13]: ▸           { platform:iOS Simulator, id:0B19B3DD-EB28-4041-9A55-660BD7DC4CE6, OS:15.2, name:iPhone 13 Pro Max }
[14:09:13]: ▸           { platform:iOS Simulator, id:43C92747-79AD-48D1-BE5E-9E07FDA77EA3, OS:15.2, name:iPhone 13 mini }
[14:09:13]: ▸   Ineligible destinations for the "Release SmartDrive WatchKit App" scheme:
[14:09:13]: ▸           { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
[14:09:13]: ▸           { platform:watchOS, id:dvtdevice-DVTiOSDevicePlaceholder-watchos:placeholder, name:Any watchOS Device }
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
                { generic:1, platform:iOS }

        The requested device could not be found because no available devices matched the request.

        Available destinations for the "Release SmartDrive WatchKit App" scheme:
                { platform:iOS Simulator, id:5226263E-41A1-4559-83EB-D643337930EE, OS:15.2, name:iPhone 12 Pro }
                { platform:iOS Simulator, id:5214DE78-40B3-4480-B88D-542FF8F01B8E, OS:15.2, name:iPhone 12 Pro Max }
                { platform:iOS Simulator, id:BC02416F-C2F7-4513-A054-EBECA7AABC43, OS:15.2, name:iPhone 13 }
                { platform:iOS Simulator, id:4E4DB372-0F47-4A19-9A55-3615EE005783, OS:15.2, name:iPhone 13 Pro }
                { platform:iOS Simulator, id:0B19B3DD-EB28-4041-9A55-660BD7DC4CE6, OS:15.2, name:iPhone 13 Pro Max }
                { platform:iOS Simulator, id:43C92747-79AD-48D1-BE5E-9E07FDA77EA3, OS:15.2, name:iPhone 13 mini }

        Ineligible destinations for the "Release SmartDrive WatchKit App" scheme:
                { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
                { platform:watchOS, id:dvtdevice-DVTiOSDevicePlaceholder-watchos:placeholder, name:Any watchOS Device }
[14:09:13]: Exit status: 70

+-------------+-------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.204.3                 |
| sdk         | WatchOS8.3.sdk          |
+-------------+-------------------------+

[14:09:13]: ▸     /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace SmartDrive.xcworkspace -scheme "Release SmartDrive WatchKit App" -destination generic/platform=iOS -archivePath "/Users/bradmartin/Library/Developer/Xcode/Archives/2022-03-15/SmartDrive WatchKit App 2022-03-15 14.08.41.xcarchive" archive
[14:09:13]: ▸ User defaults from command line:
[14:09:13]: ▸     IDEArchivePathOverride = /Users/bradmartin/Library/Developer/Xcode/Archives/2022-03-15/SmartDrive WatchKit App 2022-03-15 14.08.41.xcarchive
[14:09:13]: ▸     IDEPackageSupportUseBuiltinSCM = YES
[14:09:13]: 
[14:09:13]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[14:09:13]: 📋  For the complete and more detailed error log, check the full log at:
[14:09:13]: 📋  /Users/bradmartin/Library/Logs/gym/SmartDrive WatchKit App-Release SmartDrive WatchKit App.log
[14:09:13]: 
[14:09:13]: Looks like fastlane ran into a build/archive error with your project
[14:09:13]: It's hard to tell what's causing the error, so we wrote some guides on how
[14:09:13]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[14:09:13]: Before submitting an issue on GitHub, please follow the guide above and make
[14:09:13]: sure your project is set up correctly.
[14:09:13]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
[14:09:13]: the full commands printed out in yellow in the above log.
[14:09:13]: Make sure to inspect the output above, as usually you'll find more error information there
[14:09:13]: 
+------------------+----------+
|        Lane Context         |
+------------------+----------+
| DEFAULT_PLATFORM | ios      |
| PLATFORM_NAME    | ios      |
| LANE_NAME        | ios beta |
+------------------+----------+
[14:09:13]: Error building the application - see the log above

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 💥   | build_app        | 35          |
+------+------------------+-------------+

[14:09:13]: fastlane finished with errors

[!] Error building the application - see the log above
 </pre>
</details>

### Environment

<details>
  <pre> 
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.4                                                           |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.32.0 (Apple Git-132)                             |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane                            |
| Host                        | macOS 11.4 (20F71)                                             |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | true                                                           |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 13.2.1                                                         |
| Swift Version               | 5.5.2                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform(:ios)

platform :ios do
  desc "Build and push to TestFlight"
  lane :beta do
    build_app(workspace: "SmartDrive.xcworkspace", scheme: "Release SmartDrive WatchKit App")
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.permobil.smartdrive.watchkitapp") # The bundle identifier of your app
apple_id("engineering.smartdrive@PRIVATE.com") # Your Apple email address

itc_team_id("118XXXXX") # App Store Connect Team ID
team_id("W6XXXXXXX") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.204.3 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| atomos                          | 0.1.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| rexml                           | 3.2.5        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.3.9        |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| emoji_regex                     | 3.2.3        |
| forwardable                     | 1.2.0        |
| logger                          | 1.3.0        |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.3        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.0       |
| date                            | 2.0.0        |
| stringio                        | 0.0.2        |
| excon                           | 0.92.0       |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.0.0        |
| httpclient                      | 2.8.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| google-apis-core                | 0.4.2        |
| google-apis-playcustomapp_v1    | 0.7.0        |
| mutex_m                         | 0.1.0        |
| net-http-persistent             | 2.9.4        |
| net-http-pipeline               | 1.0.1        |
| json                            | 2.5.1        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| io-console                      | 0.4.7        |
| fileutils                       | 1.1.0        |
| etc                             | 1.0.1        |
| faraday_middleware              | 1.2.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| googleauth                      | 1.1.2        |
| google-apis-androidpublisher_v3 | 0.16.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.36.1       |
| signet                          | 0.16.1       |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.11.0       |
| fastimage                       | 2.2.6        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| os                              | 1.1.4        |
| psych                           | 3.1.0        |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.2        |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-sdk-s3                      | 1.113.0      |
| aws-sdk-kms                     | 1.55.0       |
| aws-sdk-core                    | 3.130.0      |
| aws-partitions                  | 1.567.0      |
| jmespath                        | 1.6.1        |
</details>

*generated on:* **2022-03-15**
</details>
 </pre>
</details>

**Comment by bradmartin** [comment]
Just poking to see if any maintainer has any possible insight for configuring stand alone apple watch extensions to be built via fastlane. Had no luck with various attempts and possible work arounds for old issues with any relation.

**Comment by Hendershott** [comment]
Connect your iPhone to your computer with the USB cable it came with. Xcode communicates with Apple Watch wirelessly via the iPhone. Xcode will download the watchOS device symbols from server and then after a few minutes your watch should be an available device in the Run Destination pop-up. (If you are using a Personal Team for signing you will need to trust it before the app will run on the device.)

**Comment by Nebel69** [comment]
If your watch app might need to communicate with the iPhone also (even though you also want it to run independently), then you should create the watch app by starting with 'iOS App With Watch App' template. If your watch app will not need to communicate with the iPhone at all, then use the 'App' template for a truly independent watch app.

**Comment by bradmartin** [comment]
The watch app is an independent watch app, started with the provided XCode template in June of 2021. Published on the app store and installed several thousand times in the last two months. I can build it fine locally on multiple machines using XCode. However, fastlane builds fail with the same message on the different machines. So it's likely something in fastlane needs to be configured differently for this scenario. Sadly, I'm not too familiar with the various inner pieces or the xcode CLI to provide much insight right now. 

That's just the clear issue at this point.
