### ISSUE TITLE
I back to 2.176.0 version,help!! 

### ISSUE THREAD

**Issue by GJBlog** [fastlane/fastlane#20080]
I perform action submit_review, but meet Build number: xx.yy does not exist, I cry

**Comment by GJBlog** [comment]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.4                                                           |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.30.1 (Apple Git-130)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.4 (20F71)                                             |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | ~/Downloads/Xcode.app/Contents/Developer/                      |
| Xcode Version               | 13.0                                                           |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.176.0 | 🚫 Update available |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.3.0        |
| slack-notifier                | 2.3.2        |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| plist                         | 3.5.0        |
| multipart-post                | 2.0.0        |
| word_wrap                     | 1.0.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| artifactory                   | 3.0.15       |
| babosa                        | 1.0.3        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| faraday                       | 1.0.1        |
| faraday_middleware            | 1.0.0        |
| gh_inspector                  | 1.1.3        |
| mini_magick                   | 4.10.1       |
| naturally                     | 2.2.0        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| xcpretty-travis-formatter     | 1.0.0        |
| dotenv                        | 2.7.6        |
| simctl                        | 1.6.8        |
| uber                          | 0.1.0        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| mini_mime                     | 1.0.2        |
| httpclient                    | 2.8.3        |
| google-api-client             | 0.38.0       |
| emoji_regex                   | 3.0.0        |
| rexml                         | 3.2.5        |
| nanaimo                       | 0.3.0        |
| colored2                      | 3.1.2        |
| claide                        | 1.0.3        |
| CFPropertyList                | 3.0.3        |
| atomos                        | 0.1.3        |
| xcodeproj                     | 1.21.0       |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.8.0        |
| excon                         | 0.76.0       |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| fastimage                     | 2.2.0        |
| json                          | 2.3.1        |
| bundler                       | 2.1.4        |
| jwt                           | 2.2.2        |
| multi_json                    | 1.15.0       |
| signet                        | 0.16.1       |
| os                            | 1.1.1        |
| memoist                       | 0.16.2       |
| googleauth                    | 0.17.1       |
| rake                          | 13.0.3       |
| digest-crc                    | 0.6.1        |
| webrick                       | 1.4.2        |
| google-apis-core              | 0.4.2        |
| google-apis-storage_v1        | 0.11.0       |
| google-apis-iamcredentials_v1 | 0.10.0       |
| google-cloud-errors           | 1.0.1        |
| google-cloud-env              | 1.3.3        |
| google-cloud-core             | 1.6.0        |
| google-cloud-storage          | 1.36.1       |
| aws-eventstream               | 1.1.0        |
| aws-sigv4                     | 1.2.2        |
| aws-partitions                | 1.368.0      |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.105.0      |
| aws-sdk-kms                   | 1.37.0       |
| aws-sdk-s3                    | 1.80.0       |
| forwardable                   | 1.2.0        |
| logger                        | 1.3.0        |
| stringio                      | 0.0.2        |
| ipaddr                        | 1.2.2        |
| openssl                       | 2.1.2        |
| ostruct                       | 0.1.0        |
| strscan                       | 1.0.0        |
| date                          | 2.0.0        |
| fileutils                     | 1.1.0        |
| etc                           | 1.0.1        |
| io-console                    | 0.4.7        |
| zlib                          | 1.0.0        |
| libxml-ruby                   | 3.1.0        |
| psych                         | 3.1.0        |
| mutex_m                       | 0.1.0        |
</details>


*generated on:* **2022-03-17**
</details>

**Comment by Kukurijek** [comment]
Could you just be a little clearer and more detailed.
Explain what you tried, what command you run and what does not work properly. And post the error you got.

**Comment by GJBlog** [comment]
this is my code

**Comment by valerio-castelli** [comment]
Perhaps you could try using the latest version of fastlane, 2.205.0. It contains a fix for the team selection mechanism that supersedes the recommendation to revert to version 2.176.0 and could potentially address your problem as well (via the additional fixes that have been implemented since 2.176.0). 🙂

**Comment by GJBlog** [comment]
> Perhaps you could try using the latest version of fastlane, 2.205.0. It contains a fix for the team selection mechanism that supersedes the recommendation to revert to version 2.176.0 and could potentially address your problem as well (via the additional fixes that have been implemented since 2.176.0). 🙂

It has been updated to 2.205.0, but the problem still exists. I have read all the documents, but have not found how to solve it

**Comment by Kukurijek** [comment]
Have you tried to omit the `build_number`, because it cannot be `4.xx.xx.xxx` ?
This is not a version and build number of app, but only the build number, that you want to override from the project,  e.g. `111`.

**Comment by GJBlog** [comment]
> Have you tried to omit the `build_number`, because it cannot be `4.xx.xx.xxx` ? This is not a version and build number of app, but only the build number, that you want to override from the project, e.g. `111`.

Ok, first of all, thank you very much for your reply. I will try to remove the version number first, because I used Fastlane to configure the version number is OK, I check the document, and the document is written as: build_number: '830 ', for example my version number 4.1.2.1 does that mean my build_number should be set to 1?

**Comment by GJBlog** [comment]
> Have you tried to omit the `build_number`, because it cannot be `4.xx.xx.xxx` ? This is not a version and build number of app, but only the build number, that you want to override from the project, e.g. `111`.

Thank you very much for your reply. I have tried, and it is OK to write my build_number separately. The old one is 4.1.2.6100, and the new one is app_version 4.1.2,build_number 6100

**Comment by GJBlog** [comment]
But，i use submit_review, Keep failing, I'm going to cry, display the following message, what should I do， help me！

[11:27:53]: appStoreVersions with id 'xxxx-xxxx-xxxx-xxxx-xxxxx' is not in valid state. - This resource cannot be reviewed, please check associated errors to see why.
The provided entity is missing a required attribute - You must provide a value for the attribute 'whatsNew' with this request
The provided entity is missing a required attribute - You must provide a value for the attribute 'whatsNew' with this request
The provided entity is missing a required attribute - You must provide a value for the attribute 'whatsNew' with this request
The provided entity is missing a required attribute - You must provide a value for the attribute 'whatsNew' with this request
The provided entity is missing a required attribute - You must provide a value for the attribute 'whatsNew' with this request
The provided entity is missing a required attribute - You must provide a value for the attribute 'whatsNew' with this request
The provided entity is missing a required attribute - You must provide a value for the attribute 'whatsNew' with this request
