### ISSUE TITLE
Fastlane Swift: cannot find 'desc' in scope

### ISSUE THREAD

**Issue by jakob-fiegerl** [fastlane/fastlane#20096]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
**Fastlane version**: 2.205.0

When creating a standalone swift package where I include the fastlane swift package and also define a new lane, the compiler complains about the `desc` function, as this is not public in the package:
<img width="681" alt="Screenshot 2022-03-21 at 17 21 54" src="https://user-images.githubusercontent.com/8776368/159305633-d5200116-3033-4c9d-8b04-329cfd49ed47.png">

The current `desc` function in the Fastlane Swift Package is located in `Runner.swift` and looks like this:
```swift
func desc(_: String) {
    // no-op, this is handled in fastlane/lane_list.rb
}
```

Making this function public would solve the issue.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by Kukurijek** [comment]
As far as I know fastlane is not intended to be included as a swift package 😄 
But if you do not want to use ruby, but just swift, fastlane can be set up with swift
(`fastlane init swift`).
Then this functionality will work for you.
What would be the advantage if fastlane could be included like any other swift package?

**Comment by jakob-fiegerl** [comment]
According to the documentation here http://docs.fastlane.tools/getting-started/ios/fastlane-swift/#getting-started-with-fastlaneswift-beta in the section `Get Started (SPM) (Beta)` you actually are able to declare fastlane as a swift package dependency.
Other lanes like `gym` just work fine, however the `desc` command is not available

**Comment by Kukurijek** [comment]
Sorry, I missed this somehow. You are right! 🚀 
Would you mind creating a PR?
We will see what the maintainer has to say 😄
