### ISSUE TITLE
fastlane upload to testflight failure

### ISSUE THREAD

**Issue by thehellmaker** [fastlane/fastlane#20097]
[23:01:10]: ----------------------------------
[23:01:10]: --- Step: upload_to_testflight ---
[23:01:10]: ----------------------------------
[23:01:10]: Login to App Store Connect (<email_masked>)
[23:01:13]: Login successful
[23:01:15]: Ready to upload new build to TestFlight (App:)...
[23:01:18]: Going to upload updated app to App Store Connect
[23:01:18]: This might take a few minutes. Please don't interrupt the script.
[23:01:35]: [iTMSTransporter] 	at com.apple.transporter.launcher.Application.main(Application.java:947)

[23:01:35]: [iTMSTransporter] Caused by: org.osgi.framework.BundleException: Could not resolve module: com.apple.transporter.starter [20]

[23:01:35]: [iTMSTransporter]   Unresolved requirement: Import-Package: javax.annotation; version="[3.0.0,4.0.0)"; resolution:="optional"

[23:01:35]: [iTMSTransporter]   Unresolved requirement: Import-Package: com.apple.transporter.launcher.asu; version="[1.0.0,2.0.0)"

[23:01:35]: [iTMSTransporter] 

[23:01:35]: [iTMSTransporter] 	at org.eclipse.osgi.container.Module.start(Module.java:463)

[23:01:35]: [iTMSTransporter] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:440)

[23:01:35]: [iTMSTransporter] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:459)

[23:01:35]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase2.bootstrapBundles(BootstrapperPhase2.java:321)

[23:01:35]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase2.start(BootstrapperPhase2.java:153)

[23:01:35]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.startOSGiFramework(BootstrapperPhase1.java:319)

[23:01:35]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.bootstrap(BootstrapperPhase1.java:99)

[23:01:35]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.bootstrap(BootstrapperPhase1.java:59)

[23:01:35]: [iTMSTransporter] 	at com.apple.transporter.launcher.Launcher.launchBootstrapper(Launcher.java:37)

[23:01:35]: [iTMSTransporter] 	... 6 more

[23:01:35]: iTunes Transporter output above ^
[23:01:35]: The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
+------------------+----------+
|        Lane Context         |
+------------------+----------+
| DEFAULT_PLATFORM | ios      |
| PLATFORM_NAME    | ios      |
| LANE_NAME        | ios beta |
+------------------+----------+
[23:01:35]: Error uploading ipa file: 
 

+------+----------------------+-------------+
|             fastlane summary              |
+------+----------------------+-------------+
| Step | Action               | Time (in s) |
+------+----------------------+-------------+
| 1    | default_platform     | 0           |
| 💥   | upload_to_testflight | 25          |
+------+----------------------+-------------+

[23:01:35]: fastlane finished with errors

[!] Error uploading ipa file:

**Comment by thehellmaker** [comment]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 12.2.1                                                         |
| Ruby                        | 2.6.8                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.32.0 (Apple Git-132)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 12.2.1 (21D62)                                           |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 13.2.1                                                         |
| Swift Version               | 5.5.2                                                          |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    clean_build_artifacts
    get_certificates           # invokes cert
    get_provisioning_profile  
    increment_build_number(xcodeproj: "atom8app.xcodeproj")
    build_app(
      workspace: "atom8app.xcworkspace", 
      scheme: "atom8app",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: { 
          "com.atom8.app" => "com.atom8.app AppStore 1634588226",
          "com.atom8.app.NotifeeNotificationService" => "NotificationServiceExtension"
        }
      }
    )
    upload_to_testflight
  end
  lane :release do
    get_certificates           # invokes cert
    get_provisioning_profile
    increment_build_number(xcodeproj: "atom8app.xcodeproj")
    build_app(workspace: "atom8app.xcworkspace", scheme: "atom8app")
    upload_to_app_store
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.atom8.app") # The bundle identifier of your app
apple_id("thehellmaker@gmail.com") # Your Apple email address

itc_team_id("120038901") # App Store Connect Team ID
team_id("XY3S52T7UP") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.205.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| terminal-table                  | 1.8.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| faraday-cookie_jar              | 0.0.7        |
| gh_inspector                    | 1.1.3        |
| security                        | 0.1.3        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.1.4        |
| simctl                          | 1.6.8        |
| rexml                           | 3.2.5        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.1.0        |
| CFPropertyList                  | 3.0.5        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.21.0       |
| unicode-display_width           | 1.8.0        |
| plist                           | 3.6.0        |
| babosa                          | 1.0.4        |
| excon                           | 0.90.0       |
| ruby2_keywords                  | 0.0.5        |
| faraday-retry                   | 1.0.3        |
| faraday-rack                    | 1.0.0        |
| faraday-patron                  | 1.0.0        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-net_http                | 1.0.1        |
| faraday-multipart               | 1.0.3        |
| faraday-httpclient              | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.9.3        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| json                            | 2.6.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| xcpretty-travis-formatter       | 1.0.1        |
| jwt                             | 2.3.0        |
| webrick                         | 1.7.0        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| signet                          | 0.16.0       |
| os                              | 1.1.4        |
| memoist                         | 0.16.2       |
| googleauth                      | 1.1.0        |
| mini_mime                       | 1.1.2        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.2        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| google-apis-core                | 0.4.2        |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-androidpublisher_v3 | 0.15.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-apis-storage_v1          | 0.11.0       |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-cloud-errors             | 1.2.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.36.0       |
| emoji_regex                     | 3.2.3        |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-partitions                  | 1.549.0      |
| jmespath                        | 1.5.0        |
| aws-sdk-core                    | 3.125.5      |
| aws-sdk-kms                     | 1.53.0       |
| aws-sdk-s3                      | 1.111.2      |
| forwardable                     | 1.2.0        |
| logger                          | 1.3.0        |
| date                            | 2.0.0        |
| stringio                        | 0.0.2        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.0.0        |
| mutex_m                         | 0.1.0        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| io-console                      | 0.4.7        |
| fileutils                       | 1.1.0        |
| etc                             | 1.0.1        |
| libxml-ruby                     | 3.2.1        |
| psych                           | 3.1.0        |
</details>


*generated on:* **2022-03-21**
</details>

**Comment by jrtibbetts** [comment]
Looks like a problem on Apple's end (`developer.apple.com:443`); the same thing just started happening to me 10 minutes ago. The `https://developer.apple.com` homepage is down, too.

**Comment by thehellmaker** [comment]
Upload to android play store is happening fine. So its not a network issue

**Comment by jrtibbetts** [comment]
https://www.apple.com/support/systemstatus/

**Comment by thehellmaker** [comment]
i guess it was indeed problem at apple's end. Now developer.apple.com is also back up and build proceeding. I will be validating this and closing this issue if its resolved

**Comment by thehellmaker** [comment]
apps are still taking for ever  to get uploaded but this seems to be an issue on apple end. Resolving
