### ISSUE TITLE
Bamboo Support

### ISSUE THREAD

**Issue by kcharwood** [fastlane/fastlane#201]
I know there is Jenkins support. Any plans to support [Bamboo](https://www.atlassian.com/software/bamboo) from Atlassian?

**Comment by KrauseFx** [comment]
I'm sure it already is supported. I just put Jenkins on the project page, as many teams are using it. Just give it a go on Bamboo :+1:

**Comment by KrauseFx** [comment]
Let me know if it works as expected.

**Comment by kcharwood** [comment]
Cool. What is the best practice for passing in the bamboo job number to fast lane? Appending it to the env file?

**Comment by KrauseFx** [comment]
I don't know, sorry, haven't worked with bamboo myself. Why would you need the job number?

**Comment by kcharwood** [comment]
We currently use the job number as the incrementing build number in our feature branches. When we have parallel branches being developed, its difficult to have a source of truth, so we have bamboo plans spun up for that work and push them to unique hockey app buckets.

Just trying to figure out the slickest way to get into fastlane.

Here is some code showing how we pack a bunch of different information into the build number string in this scenario, just need to get the build job number in there now.

How do you get the Jenkins job number into fastlane? Is there a best practice for that?

```ruby
def full_development_build_number_string_for_build_number(build_number)
  #creates a build number that looks like 1.1.3-b101-branch_name-207EA8D
  plistfilepath = ENV['PLISTPATH']
  version = `/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "../#{plistfilepath}"`.strip
  commit_sha = `git rev-parse --short HEAD`
  branch_name = `git rev-parse --abbrev-ref HEAD`
  full_version = "#{version}-b#{build_number}-#{branch_name.strip}-#{commit_sha.strip.upcase}"
  return full_version
end
```

**Comment by KrauseFx** [comment]
@kcharwood Have you found a solution for this issue?

**Comment by kcharwood** [comment]
Hey @KrauseFx 

I've got a lot of things working in Bamboo, and loving fastlane!

I'm still a ruby newbie, and I was trying to see if `is_ci` supports Bamboo. Looking through [source](https://github.com/fastlane/fastlane/blob/5fcdcac3b66083f3fdbf17ddfa4d8b6ae0673595/lib/fastlane/actions/is_ci.rb#L5), I'm not super clear how fastlane determines that. I'm assuming it checks for various environment variables to determine if that is running, but I can't find where the magic actually happens. If it doesn't support Bamboo already, I'd be happy to push up a PR with support, I'm just not quite sure where to look. Could you point me in the right direction?

Thanks! :beers:

**Comment by xfreebird** [comment]
@kcharwood the ```is_ci``` method is implemented here https://github.com/fastlane/fastlane_core/blob/master/lib/fastlane_core/helper.rb
Bamboo detection is already there.

**Comment by kcharwood** [comment]
fastlane_core! Havent poked around in there yet. Thanks!
