### ISSUE TITLE
Keychain Prompts on CI/CD Runner

### ISSUE THREAD

**Issue by allidoisace** [fastlane/fastlane#20103]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

CI: GitLab
**Issue 1:** Every time our build is executed on the Mac Mini a prompt is displayed asking for keychain access to `fastlane_tmp_keychain_db`. I believed this is caused by `setup_ci`, so I am not sure why we need this.
**Issue 2:** This issue has already been talked about, but the solution seems ridiculous and I don't understand why we need to create a keychain in the first place https://github.com/fastlane/fastlane/issues/10589.

##### Command executed

```
bundle exec fastlane build
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                                      |
| --------------------------- | -------------------------------------------------------------------------- |
| OS                          | 12.3                                                                       |
| Ruby                        | 3.0.2                                                                      |
| Bundler?                    | true                                                                       |
| Git                         | git version 2.33.1                                                         |
| Installation Source         | ~/.../app/ios/App/vendor/ruby/3.0.0/bin/fastlane |
| Host                        | macOS 12.3 (21E230)                                                        |
| Ruby Lib Dir                | ~/.rbenv/versions/3.0.2/lib                                                |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021                                                |
| Is contained                | false                                                                      |
| Is homebrew                 | false                                                                      |
| Is installed via Fabric.app | false                                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                                |
| Xcode Version               | 13.0                                                                       |
| Swift Version               | 5.5                                                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
before_all do
  update_fastlane
  setup_ci
end

default_platform(:ios)

platform :ios do
  desc "Get certificates"
  lane :certificates do
    sync_code_signing(
      type: "development",
      app_identifier: ['...'],
      force_for_new_devices: true,
      readonly: true
    )

    sync_code_signing(
      type: "appstore",
      app_identifier: ['...'],
      readonly: true
    )
  end

  desc "Generate new certificates"
  lane :generate_new_certificates do
    sync_code_signing(
      type: "development",
      app_identifier: ['...'],
      force_for_new_devices: true,
      readonly: false
    )
    sync_code_signing(
      type: "appstore",
      app_identifier: ['...'],
      force_for_new_devices: true,
      readonly: false
    )
  end

  desc "Build binary"
  lane :build do
    increment_build_number(build_number: ENV['...'])
    certificates
    build_app(workspace: "App.xcworkspace", configuration: "Release", scheme: "...")
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: "...",
      issuer_id: "...",
      key_filepath: ENV['...'],
      duration: 1200, # optional (maximum 1200)
    )
    certificates
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end

  desc "Release binary"
  lane :release do
    api_key = app_store_connect_api_key(
      key_id: "...",
      issuer_id: "...",
      key_filepath: ENV['...'],
      duration: 1200, # optional (maximum 1200)
      in_house: false, # optional but may be required if using match/sigh
    )
    certificates
    upload_to_app_store(
      api_key: api_key
    ) # deliver
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("...") # The bundle identifier of your app
apple_id("...") # Your Apple email address

team_name("...")
itc_team_name("...")
team_id("...") # Developer Portal Team ID
itc_team_id("...") # App Store Connect Team ID

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.205.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| bundler                         | 2.3.9        |
| tsort                           | 0.1.0        |
| uri                             | 0.10.1       |
| pathname                        | 0.1.0        |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| concurrent-ruby                 | 1.1.9        |
| i18n                            | 1.8.10       |
| minitest                        | 5.14.4       |
| tzinfo                          | 2.0.4        |
| zeitwerk                        | 2.4.2        |
| activesupport                   | 6.1.4.1      |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| httpclient                      | 2.8.3        |
| json                            | 2.6.1        |
| algoliasearch                   | 1.27.5       |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.568.0      |
| aws-sigv4                       | 1.4.0        |
| jmespath                        | 1.6.1        |
| aws-sdk-core                    | 3.130.0      |
| aws-sdk-kms                     | 1.55.0       |
| aws-sdk-s3                      | 1.113.0      |
| babosa                          | 1.0.4        |
| claide                          | 1.1.0        |
| fuzzy_match                     | 2.0.4        |
| nap                             | 1.1.0        |
| netrc                           | 0.11.0       |
| ffi                             | 1.15.4       |
| ethon                           | 0.14.0       |
| typhoeus                        | 1.4.0        |
| cocoapods-core                  | 1.11.0       |
| cocoapods-deintegrate           | 1.0.5        |
| cocoapods-downloader            | 1.5.0        |
| cocoapods-plugins               | 1.0.0        |
| cocoapods-search                | 1.0.1        |
| cocoapods-trunk                 | 1.6.0        |
| cocoapods-try                   | 1.2.0        |
| colored2                        | 3.1.2        |
| escape                          | 0.0.4        |
| fourflusher                     | 2.3.1        |
| gh_inspector                    | 1.1.3        |
| molinillo                       | 0.8.0        |
| ruby-macho                      | 2.5.1        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| cocoapods                       | 1.11.0       |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.8.1      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.92.1       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.0.0        |
| faraday-multipart               | 1.0.3        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.0       |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| jwt                             | 2.3.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.1       |
| googleauth                      | 1.1.2        |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.2        |
| google-apis-androidpublisher_v3 | 0.16.0       |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.11.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.36.1       |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
</details>

*generated on:* **2022-03-22**
</details>

**Comment by Kukurijek** [comment]
When the mac mini goes into sleep mode, the keychain locks, maybe that is the reason. In any case, it is best to use your own script so that you can adjust the keychain parameters as you wish.

#10589 is not ridiculous 😄 

Fastlane keeps private key and certificates in the keychain. If you do not define your keychain entry or use seup_ci (which does this in the background), then everything will be saved in the default keychain.

In case someone gets access to your mac mini or knows the login password, they can enter the default keychain and export private keys and certificates.

**Comment by allidoisace** [comment]
> When the mac mini goes into sleep mode, the keychain locks, maybe that is the reason. In any case, it is best to use your own script so that you can adjust the keychain parameters as you wish.
> 
> #10589 is not ridiculous 😄
> 
> Fastlane keeps private key and certificates in the keychain. If you do not define your keychain entry or use setup_ci (which does this in the background), then everything will be saved in the default keychain.
> 
> In case someone gets access to your mac mini or knows the login password, they can enter the default keychain and export private keys and certificates.

So, are you recommending to use `setup_ci` and then store the keychain password (I think there is a keychain env variable for Fastlane) in Gitlab variables?

**Comment by Kukurijek** [comment]
I would rather use the `ensure_temp_keychain` from jgavris. But `timeout` parameter is not Bool anymore, so you can set it to `0`.
You can define the password as a gitlab secret, but you do not have to. You can use a random password as well (e.g. [SecureRandom](https://ruby-doc.org/stdlib-2.5.1/libdoc/securerandom/rdoc/SecureRandom.html)).

Both approaches have pros and cons 😄

**Comment by allidoisace** [comment]
With the solution from jgavris, how does the keychain get unlocked with the password (or random password) without having to access the machine?

**Comment by Kukurijek** [comment]
Since you mentioned gitlab, I guess you use gitlab ci. So you have installed a gitlab runner directly on the machine (that is why the runner has access to the machine). With this script you create a new keychain that is locked with a key defined in the function. Did this help you?

**Comment by allidoisace** [comment]
I have not tried it quite yet, just trying to understand how the keychain will get unlocked.
