### ISSUE TITLE
spaceship provisioning_profile error 

### ISSUE THREAD

**Issue by liqianjie** [fastlane/fastlane#20106]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

the code as below:

`require "spaceship"
username = ARGV[0];
password = ARGV[1];
Spaceship.login(username, password)
certificates = Spaceship::Portal.certificate.production.all
puts certificates
ad_hocProfile = Spaceship::Portal.provisioning_profile.all.first
puts ad_hocProfile`

I can get certificate list.
but the  provisioning_profile report error:

/usr/local/ruby-2.6.4/lib/ruby/gems/2.6.0/gems/fastlane-2.205.0/spaceship/lib/spaceship/client.rb:771:in `parse_response': {"responseId"=>"773ed0c2-1908-45f5-a287-cabf4e31264d", "resultCode"=>3018, "resultString"=>"Please update to Xcode 7.3 or later to continue developing with your Apple ID.", "userString"=>"Please update to Xcode 7.3 or later to continue developing with your Apple ID.", "creationTimestamp"=>"2022-03-23T07:34:33Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developerservices2.apple.com/services/QH65B2/ios/listProvisioningProfiles.action", "httpCode"=>200} (Spaceship::UnexpectedResponse)

##### Command executed

ruby getCertificateId.rb mydeveloperemail mydeveloperpass

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [Traceback (most recent call last):
        3: from getCertificateId.rb:16:in `<main>'
        2: from /usr/local/ruby-2.6.4/lib/ruby/gems/2.6.0/gems/fastlane-2.205.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:319:in `all'
        1: from /usr/local/ruby-2.6.4/lib/ruby/gems/2.6.0/gems/fastlane-2.205.0/spaceship/lib/spaceship/portal/portal_client.rb:669:in `provisioning_profiles_via_xcode_api'
/usr/local/ruby-2.6.4/lib/ruby/gems/2.6.0/gems/fastlane-2.205.0/spaceship/lib/spaceship/client.rb:771:in `parse_response': {"responseId"=>"0cad27d8-9ef4-46d3-9ee6-9485a6b81db1", "resultCode"=>3018, "resultString"=>"Please update to Xcode 7.3 or later to continue developing with your Apple ID.", "userString"=>"Please update to Xcode 7.3 or later to continue developing with your Apple ID.", "creationTimestamp"=>"2022-03-23T07:59:58Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developerservices2.apple.com/services/QH65B2/ios/listProvisioningProfiles.action", "httpCode"=>200} (Spaceship::UnexpectedResponse)
] </pre>
</details>

### Environment

<details>
  <pre> [/usr/local/ruby-2.6.4/lib/ruby/gems/2.6.0/gems/fastlane-2.205.0/bin/fastlane env
[✔] 🚀 
[15:56:01]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[15:56:02]: Sending anonymous analytics information
[15:56:02]: Learn more at https://docs.fastlane.tools/#metrics
[15:56:02]: No personal or sensitive data is sent.
[15:56:02]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
[15:56:02]: Generating fastlane environment output, this might take a few seconds...
[15:56:02]: undefined method `strip' for nil:NilClass
[15:56:02]: Error rendering markdown table using the following text:
[15:56:02]: | Key | Value |
| fastlane | 2.205.0 |
| OS | Linux VM-12-13-centos 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Ruby | 2.6.4 |
| Bundler? | false |
| Git | git version 1.8.3.1 |
| Installation Source | /usr/local/ruby-2.6.4/lib/ruby/gems/2.6.0/gems/fastlane-2.205.0/bin/fastlane |
| Host | \S
Kernel \r on an \m Linux VM-12-13-centos 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux (3.10.0-1160.45.1.el7.x86_64) |
| Ruby Lib Dir | /usr/local/ruby-2.6.4/lib |
| OpenSSL Version | OpenSSL 1.0.2k  26 Jan 2017 |
| Is contained | false |
| Is homebrew | false |
| Is installed via Fabric.app | false |
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key | Value |
| fastlane | 2.205.0 |
| OS | Linux VM-12-13-centos 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Ruby | 2.6.4 |
| Bundler? | false |
| Git | git version 1.8.3.1 |
| Installation Source | /usr/local/ruby-2.6.4/lib/ruby/gems/2.6.0/gems/fastlane-2.205.0/bin/fastlane |
| Host | \S
Kernel \r on an \m Linux VM-12-13-centos 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux (3.10.0-1160.45.1.el7.x86_64) |
| Ruby Lib Dir | /usr/local/ruby-2.6.4/lib |
| OpenSSL Version | OpenSSL 1.0.2k  26 Jan 2017 |
| Is contained | false |
| Is homebrew | false |
| Is installed via Fabric.app | false |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.205.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| atomos                          | 0.1.3        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| rexml                           | 3.2.5        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.92.1       |
| unf_ext                         | 0.0.8.1      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.3        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.0       |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.1.0        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 1.17.2       |
| simctl                          | 1.6.8        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.4.2        |
| google-apis-core                | 0.4.2        |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-androidpublisher_v3 | 0.16.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.11.0       |
| rake                            | 12.3.2       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.36.1       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.6.1        |
| aws-partitions                  | 1.568.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-sdk-core                    | 3.130.0      |
| aws-sdk-kms                     | 1.55.0       |
| aws-sdk-s3                      | 1.113.0      |
| forwardable                     | 1.2.0        |
| logger                          | 1.3.0        |
| date                            | 2.0.0        |
| stringio                        | 0.0.2        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.0.0        |
| mutex_m                         | 0.1.0        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| io-console                      | 0.4.7        |
| fileutils                       | 1.1.0        |
| etc                             | 1.0.1        |
| jwt                             | 2.3.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.1       |
| googleauth                      | 1.1.2        |
| psych                           | 3.1.0        |
</details>

*generated on:* **2022-03-23**
</details>
[15:56:03]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[15:56:03]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅] </pre>
</details>

**Comment by lucgrabowski** [comment]
Please take a look at the discussion in https://github.com/fastlane/fastlane/issues/20060. I'm closing it as a duplicate.
