### ISSUE TITLE
Build stucking on cancel submission step.

### ISSUE THREAD

**Issue by Glaubenio** [fastlane/fastlane#20128]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
The build get stuck on submit cancel step. one information is that, submitting a version and cancelling it right after makes this process to fail with the following output:

<pre>/Users/jenkins/.rvm/gems/ruby-2.6.6/gems/fastlane-2.205.0/deliver/lib/deliver/runner.rb:210:in `block in reject_version_if_possible': [!] undefined method `app_store_state' for nil:NilClass (NoMethodError)
	from /Users/jenkins/.rvm/gems/ruby-2.6.6/gems/fastlane-2.205.0/deliver/lib/deliver/runner.rb:208:in `loop'
	from /Users/jenkins/.rvm/gems/ruby-2.6.6/gems/fastlane-2.205.0/deliver/lib/deliver/runner.rb:208:in `reject_version_if_possible'
	from /Users/jenkins/.rvm/gems/ruby-2.6.6/gems/fastlane-2.205.0/deliver/lib/deliver/runner.rb:53:in `run'
	from /Users/jenkins/.rvm/gems/ruby-2.6.6/gems/fastlane-2.205.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:22:in `run'
	from /Users/jenkins/.rvm/gems/ruby-2.6.6/gems/fastlane-2.205.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/jenkins/.rvm/gems/ruby-2.6.6/gems/fastlane-2.205.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/jenkins/.rvm/gems/ruby-2.6.6/gems/fastlane-2.205.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/jenkins/.rvm/gems/ruby-2.6.6/gems/fastlane-2.205.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/jenkins/.rvm/gems/ruby-2.6.6/gems/fastlane-2.205.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/jenkins/.rvm/gems/ruby-2.6.6/gems/fastlane-2.205.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/jenkins/.rvm/gems/ruby-2.6.6/gems/fastlane-2.205.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:536:in `block in parsing_binding'
	from /Users/jenkins/.rvm/gems/ruby-2.6.6/gems/fastlane-2.205.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/jenkins/.rvm/gems/ruby-2.6.6/gems/fastlane-2.205.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/jenkins/.rvm/gems/ruby-2.6.6/gems/fastlane-2.205.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/jenkins/.rvm/gems/ruby-2.6.6/gems/fastlane-2.205.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/jenkins/.rvm/gems/ruby-2.6.6/gems/fastlane-2.205.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/jenkins/.rvm/gems/ruby-2.6.6/gems/fastlane-2.205.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/jenkins/.rvm/gems/ruby-2.6.6/gems/fastlane-2.205.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /Users/jenkins/.rvm/gems/ruby-2.6.6/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/jenkins/.rvm/gems/ruby-2.6.6/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/jenkins/.rvm/gems/ruby-2.6.6/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/jenkins/.rvm/gems/ruby-2.6.6/gems/fastlane-2.205.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/jenkins/.rvm/gems/ruby-2.6.6/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/jenkins/.rvm/gems/ruby-2.6.6/gems/fastlane-2.205.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /Users/jenkins/.rvm/gems/ruby-2.6.6/gems/fastlane-2.205.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Users/jenkins/.rvm/gems/ruby-2.6.6/gems/fastlane-2.205.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /Users/jenkins/.rvm/gems/ruby-2.6.6/gems/fastlane-2.205.0/bin/fastlane:23:in `<top (required)>'
	from /Users/jenkins/.rvm/gems/ruby-2.6.6/bin/fastlane:23:in `load'
	from /Users/jenkins/.rvm/gems/ruby-2.6.6/bin/fastlane:23:in `<main>'
	from /Users/jenkins/.rvm/gems/ruby-2.6.6/bin/ruby_executable_hooks:22:in `eval'
	from /Users/jenkins/.rvm/gems/ruby-2.6.6/bin/ruby_executable_hooks:22:in `<main>'</pre>

##### Complete output when running fastlane, including the stack trace and command used

<details>
 <pre>  upload_to_app_store(
    app_identifier: ENV['DELIVER_APP_IDENTIFIER'],
    api_key: api_key,
    submit_for_review: true,
    skip_screenshots: true,
    run_precheck_before_submit: false,
    reject_if_possible: true,
    precheck_include_in_app_purchases: false, # Not supported for API KEY
    force: true # Skip HTMl report verification
  ) </pre>
  <pre> [11:24:02]: Making sure the latest version on App Store Connect matches '4.11.15'...
[11:24:02]: '4.11.15' is the latest version on App Store Connect
[11:24:07]: Review submission cancellation has been requested
[11:24:07]: Waiting for cancellation to take effect...
[11:24:26]: Waiting for cancellation to take effect...
[11:24:44]: Waiting for cancellation to take effect...
[11:24:59]: Waiting for cancellation to take effect...
[11:25:15]: Waiting for cancellation to take effect...
[11:25:31]: Waiting for cancellation to take effect...
[11:25:46]: Waiting for cancellation to take effect...
[11:26:02]: Waiting for cancellation to take effect...
[11:26:18]: Waiting for cancellation to take effect...
[11:26:34]: Waiting for cancellation to take effect...
[11:26:49]: Waiting for cancellation to take effect...
[11:27:05]: Waiting for cancellation to take effect...
[11:27:21]: Waiting for cancellation to take effect...
[11:27:36]: Waiting for cancellation to take effect...
[11:27:52]: Waiting for cancellation to take effect...
[11:28:08]: Waiting for cancellation to take effect...
[11:28:24]: Waiting for cancellation to take effect...
[11:28:39]: Waiting for cancellation to take effect...
[11:28:55]: Waiting for cancellation to take effect...
[11:29:11]: Waiting for cancellation to take effect...
[11:29:27]: Waiting for cancellation to take effect...
[11:29:42]: Waiting for cancellation to take effect...
[11:29:58]: Waiting for cancellation to take effect...
[11:30:14]: Waiting for cancellation to take effect...
[11:30:29]: Waiting for cancellation to take effect...
[11:30:45]: Waiting for cancellation to take effect...
[11:31:01]: Waiting for cancellation to take effect...
[11:31:17]: Waiting for cancellation to take effect...
[11:31:33]: Waiting for cancellation to take effect...
[11:31:48]: Waiting for cancellation to take effect...
[11:32:04]: Waiting for cancellation to take effect...
[11:32:20]: Waiting for cancellation to take effect...
[11:32:36]: Waiting for cancellation to take effect...
[11:32:51]: Waiting for cancellation to take effect...
[11:33:07]: Waiting for cancellation to take effect...
[11:33:23]: Waiting for cancellation to take effect...
[11:33:38]: Waiting for cancellation to take effect...
[11:33:54]: Waiting for cancellation to take effect...
[11:34:10]: Waiting for cancellation to take effect...
[11:34:26]: Waiting for cancellation to take effect...
[11:34:41]: Waiting for cancellation to take effect...
[11:34:57]: Waiting for cancellation to take effect...
[11:35:13]: Waiting for cancellation to take effect...
[11:35:28]: Waiting for cancellation to take effect...
[11:35:44]: Waiting for cancellation to take effect...
[11:36:00]: Waiting for cancellation to take effect...
[11:36:16]: Waiting for cancellation to take effect...
[11:36:31]: Waiting for cancellation to take effect...
[11:36:47]: Waiting for cancellation to take effect...
[11:37:03]: Waiting for cancellation to take effect...
[11:37:18]: Waiting for cancellation to take effect...
[11:37:34]: Waiting for cancellation to take effect...
[11:37:50]: Waiting for cancellation to take effect...
[11:38:06]: Waiting for cancellation to take effect... </pre>
</details>

### Environment

<details>
swift-driver version: 1.26.21 <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.5.2                                      |
| Ruby                        | 2.6.6                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.32.0 (Apple Git-132)          |
| Installation Source         | ~/.rvm/gems/ruby-2.6.6/bin/fastlane         |
| Host                        | macOS 11.5.2 (20G95)                        |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.6/lib                |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 13.2.1                                      |
| Swift Version               | 5.5.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.205.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                                 | Version      |
| ----------------------------------- | ------------ |
| did_you_mean                        | 1.3.0        |
| rake                                | 13.0.6       |
| rexml                               | 3.2.5        |
| CFPropertyList                      | 3.0.5        |
| concurrent-ruby                     | 1.1.9        |
| i18n                                | 1.10.0       |
| minitest                            | 5.15.0       |
| tzinfo                              | 2.0.4        |
| zeitwerk                            | 2.5.4        |
| activesupport                       | 6.1.5        |
| public_suffix                       | 4.0.6        |
| addressable                         | 2.8.0        |
| httpclient                          | 2.8.3        |
| json                                | 2.6.1        |
| algoliasearch                       | 1.27.5       |
| artifactory                         | 3.0.15       |
| ast                                 | 2.4.2        |
| atomos                              | 0.1.3        |
| aws-eventstream                     | 1.2.0        |
| aws-partitions                      | 1.568.0      |
| aws-sigv4                           | 1.4.0        |
| jmespath                            | 1.6.1        |
| aws-sdk-core                        | 3.130.0      |
| aws-sdk-kms                         | 1.55.0       |
| aws-sdk-s3                          | 1.113.0      |
| babosa                              | 1.0.4        |
| bundler                             | 2.2.25       |
| claide                              | 1.0.3        |
| fuzzy_match                         | 2.0.4        |
| nap                                 | 1.1.0        |
| netrc                               | 0.11.0       |
| ffi                                 | 1.15.5       |
| ethon                               | 0.15.0       |
| typhoeus                            | 1.4.0        |
| cocoapods-core                      | 1.11.3       |
| cocoapods-deintegrate               | 1.0.5        |
| cocoapods-downloader                | 1.5.1        |
| cocoapods-plugins                   | 1.0.0        |
| cocoapods-search                    | 1.0.1        |
| cocoapods-trunk                     | 1.6.0        |
| cocoapods-try                       | 1.2.0        |
| colored2                            | 3.1.2        |
| escape                              | 0.0.4        |
| fourflusher                         | 2.3.1        |
| gh_inspector                        | 1.1.3        |
| molinillo                           | 0.8.0        |
| ruby-macho                          | 2.5.1        |
| nanaimo                             | 0.3.0        |
| xcodeproj                           | 1.21.0       |
| cocoapods                           | 1.11.3       |
| coderay                             | 1.1.3        |
| colored                             | 1.2          |
| highline                            | 2.0.3        |
| commander                           | 4.6.0        |
| configure_extensions                | 1.1.0        |
| declarative                         | 0.0.20       |
| digest-crc                          | 0.6.4        |
| unf_ext                             | 0.0.8.1      |
| unf                                 | 0.1.4        |
| domain_name                         | 0.5.20190701 |
| dotenv                              | 2.7.6        |
| emoji_regex                         | 3.2.3        |
| excon                               | 0.92.1       |
| faraday-em_http                     | 1.0.0        |
| faraday-em_synchrony                | 1.0.0        |
| faraday-excon                       | 1.1.0        |
| faraday-httpclient                  | 1.0.1        |
| multipart-post                      | 2.0.0        |
| faraday-multipart                   | 1.0.3        |
| faraday-net_http                    | 1.0.1        |
| faraday-net_http_persistent         | 1.2.0        |
| faraday-patron                      | 1.0.0        |
| faraday-rack                        | 1.0.0        |
| faraday-retry                       | 1.0.3        |
| ruby2_keywords                      | 0.0.5        |
| faraday                             | 1.10.0       |
| http-cookie                         | 1.0.4        |
| faraday-cookie_jar                  | 0.0.7        |
| faraday_middleware                  | 1.2.0        |
| fastimage                           | 2.2.6        |
| jwt                                 | 2.3.0        |
| memoist                             | 0.16.2       |
| multi_json                          | 1.15.0       |
| os                                  | 1.1.4        |
| signet                              | 0.16.1       |
| googleauth                          | 1.1.2        |
| mini_mime                           | 1.1.2        |
| trailblazer-option                  | 0.1.2        |
| uber                                | 0.1.0        |
| representable                       | 3.1.1        |
| retriable                           | 3.1.2        |
| webrick                             | 1.7.0        |
| google-apis-core                    | 0.4.2        |
| google-apis-androidpublisher_v3     | 0.16.0       |
| google-apis-playcustomapp_v1        | 0.7.0        |
| google-apis-iamcredentials_v1       | 0.10.0       |
| google-apis-storage_v1              | 0.11.0       |
| google-cloud-env                    | 1.5.0        |
| google-cloud-errors                 | 1.2.0        |
| google-cloud-core                   | 1.6.0        |
| google-cloud-storage                | 1.36.1       |
| mini_magick                         | 4.11.0       |
| naturally                           | 2.2.1        |
| optparse                            | 0.1.1        |
| plist                               | 3.6.0        |
| rubyzip                             | 2.3.2        |
| security                            | 0.1.3        |
| simctl                              | 1.6.8        |
| terminal-notifier                   | 2.0.0        |
| terminal-table                      | 1.6.0        |
| tty-screen                          | 0.8.1        |
| tty-cursor                          | 0.7.1        |
| tty-spinner                         | 0.9.3        |
| word_wrap                           | 1.0.0        |
| rouge                               | 2.0.7        |
| xcpretty                            | 0.3.0        |
| xcpretty-travis-formatter           | 1.0.1        |
| google-apis-cloudresourcemanager_v3 | 0.22.0       |
| google-apis-firebase_v1beta1        | 0.13.0       |
| method_source                       | 1.0.0        |
| parallel                            | 1.22.0       |
| parser                              | 3.1.1.0      |
| pry                                 | 0.14.1       |
| rainbow                             | 3.1.1        |
| regexp_parser                       | 2.2.1        |
| rubocop-ast                         | 1.16.0       |
| ruby-progressbar                    | 1.11.0       |
| unicode-display_width               | 2.1.0        |
| rubocop                             | 1.26.0       |
| xcode-install                       | 2.8.0        |
</details>

*generated on:* **2022-03-26**
</details>

</details>
</pre>
</details>

**Comment by TheWirv** [comment]
I have the same problem, although I can clearly see in App Store Connect that the old build/version has already been successfully canceled.

**Comment by Emmitt121** [comment]
My submissions to iTunes Connect are stuck in the processing stage under "Activity". I resubmitted a new build and it too is stuck in processing. Any one else?

**Comment by Hendershott** [comment]
Click your profile picture .
Click Switch account.
You should see a check mark next to the account that you're currently signed in with. If you see another account listed that also belongs to you, tap on it to switch to that account.
Check if your other account is signed up for a paid membership by visiting [youtube.com/purchases](http://youtube.com/purchases). If there are no other accounts listed, you can always try signing in using other Google Accounts that belong to you and check for active memberships

**Comment by stherold** [comment]
We have the sae problem that adding `reject_if_possible` to the deliver command cancels teh active submission but that doesn't seem to be detected by fastlane since the build is stuck with the message:
```
INFO [2022-04-14 09:02:20.12]: Making sure the latest version on App Store Connect matches '3.20.0'...
INFO [2022-04-14 09:02:23.18]: '3.20.0' is the latest version on App Store Connect
INFO [2022-04-14 09:02:27.06]: Review submission cancellation has been requested
INFO [2022-04-14 09:02:30.55]: Waiting for cancellation to take effect...
INFO [2022-04-14 09:02:49.67]: Waiting for cancellation to take effect...
INFO [2022-04-14 09:03:05.43]: Waiting for cancellation to take effect...
INFO [2022-04-14 09:03:21.20]: Waiting for cancellation to take effect...
INFO [2022-04-14 09:03:36.97]: Waiting for cancellation to take effect...
INFO [2022-04-14 09:03:52.72]: Waiting for cancellation to take effect...
INFO [2022-04-14 09:04:08.49]: Waiting for cancellation to take effect...
INFO [2022-04-14 09:04:24.31]: Waiting for cancellation to take effect...
INFO [2022-04-14 09:04:43.32]: Waiting for cancellation to take effect...
INFO [2022-04-14 09:04:59.12]: Waiting for cancellation to take effect...
INFO [2022-04-14 09:05:14.87]: Waiting for cancellation to take effect...
INFO [2022-04-14 09:05:30.97]: Waiting for cancellation to take effect...
INFO [2022-04-14 09:05:46.78]: Waiting for cancellation to take effect...
INFO [2022-04-14 09:06:02.55]: Waiting for cancellation to take effect...
INFO [2022-04-14 09:06:18.32]: Waiting for cancellation to take effect...
INFO [2022-04-14 09:06:34.11]: Waiting for cancellation to take effect...
INFO [2022-04-14 09:06:49.85]: Waiting for cancellation to take effect...
INFO [2022-04-14 09:07:05.61]: Waiting for cancellation to take effect...
INFO [2022-04-14 09:07:21.43]: Waiting for cancellation to take effect...
INFO [2022-04-14 09:07:37.31]: Waiting for cancellation to take effect...
INFO [2022-04-14 09:07:53.13]: Waiting for cancellation to take effect...
INFO [2022-04-14 09:08:11.73]: Waiting for cancellation to take effect...
INFO [2022-04-14 09:08:27.59]: Waiting for cancellation to take effect...
INFO [2022-04-14 09:08:43.41]: Waiting for cancellation to take effect...
INFO [2022-04-14 09:08:59.26]: Waiting for cancellation to take effect...
```

Any idea whats wrong there?

**Comment by Ryan42000** [comment]
You should see a check mark next to the account that you're currently signed in with. If you see another account listed that also belongs to you, tap on it to switch to that account.

**Comment by McNeely12** [comment]
In window-based GUI applications, it is standard to have a Cancel button that closes any dialog box and discards any changes the user may have made within that dialog box. A great way to support exploratory learning. Compare with older systems where you were trapped if you ever activated the wrong command.

In editing systems it is usual to have an Undo command that makes the document revert to the state before the user's most recent changes. Sometimes, multi-level undo and redo is supported: this can be very useful but confusing.

**Comment by Banck** [comment]
Any news here? The same issue...

**Comment by Wei-Pinkoi** [comment]
I think the related issue.
[08:55:45]: Review submission cancellation has been requested
[08:55:48]: ▸ undefined method `app_store_state' for nil:NilClass

**Comment by ryan-caarter** [comment]
Same issue here, the submission is successfully removed but fastlane does not recognise the state has changed and hangs with "Waiting for cancellation to take effect..."

**Comment by sneko** [comment]
Same issue on my side... any news?

Thank you,

**Comment by blueberry6401** [comment]
Same issue here.

**Comment by Wei18** [comment]
Same issue here.

**Comment by assembleMHN** [comment]
Same issue here, cancellation works, but Fastlane never see that it takes effect...

**Comment by cbjerg** [comment]
Same issue, been having this for months

**Comment by appinteractive** [comment]
Waiting for cancellation [GitHub issue] to take effect... 👋
