### ISSUE TITLE
Regression / Signing Issue with Xcode 13.3 on macOS 12: "Development team" required for Cocoapods targets

### ISSUE THREAD

**Issue by gereons** [fastlane/fastlane#20122]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm running build jobs on the (private beta) macos-12 VMs from Github actions, using Xcode 13.3. 
Fastlane: 2.205.1
Cocoapods: 1.11.3

During build, I'm getting "Development team required" error messages for some of the cocoapods-generated targets in my app, specifically the only ones that include `resource_bundles` commands in their podspecs.

The exact error messages are
```
[09:45:48]: ▸ ❌  error: Signing for "SDCAlertView-SDCAlertView" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'SDCAlertView-SDCAlertView' from project 'SDCAlertView')
[09:45:48]: ▸ ❌  error: Signing for "Snabble-Snabble" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'Snabble-Snabble' from project 'Snabble')
[09:45:48]: ▸ ❌  error: Signing for "Snabble-SnabbleDT" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'Snabble-SnabbleDT' from project 'Snabble')
[09:45:48]: ▸ ** ARCHIVE FAILED **
```

This is the lane I'm running:
```
lane :githubbuild do
    setup_travis
    update_code_signing_settings(
      use_automatic_signing: false
    )
    import_certificate(
      certificate_path: "fastlane/Certificates/distribution.p12",
      certificate_password: ENV["KEY_PASSWORD"],
      keychain_name: "fastlane_tmp_keychain",
      log_output: false
    )
    install_provisioning_profile(
      path: "fastlane/Certificates/MyApp_Release.mobileprovision"
    )
    update_project_provisioning(
      xcodeproj: "MyApp.xcodeproj",
      profile: "fastlane/Certificates/MyApp_Release.mobileprovision",
      build_configuration: "Release",
      code_signing_identity: "Apple Distribution: s****e GmbH (5********L)"
    )
    sigh(
      adhoc: false,
      provisioning_name: "MyApp Release",
    )
    build_number = ENV["GITHUB_RUN_NUMBER"]
    increment_build_number(build_number: build_number)
    build_ios_app(
      configuration: "Release",
      export_method: "app-store",
      include_bitcode: true,
      include_symbols: true,
    )
end
```

Running this lane locally does not cause any errors, nor does running it on a `macos-11` runner instance with Xcode 13.2.1

What could be causing this? Is this a regression in Xcode itself, something broken in the macos-12 VMs, or is this something that fastlane is responsible for?

**Comment by gereons** [comment]
`fastlane env` output:


### Stack

| Key                         | Value                                                             |
| --------------------------- | ----------------------------------------------------------------- |
| OS                          | 12.2.1                                                            |
| Ruby                        | 3.0.3                                                             |
| Bundler?                    | true                                                              |
| Git                         | git version 2.35.1                                                |
| Installation Source         | ~/work/iOS-App/iOS-App/main/vendor/bundle/ruby/3.0.0/bin/fastlane |
| Host                        | macOS 12.2.1 (21D62)                                              |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@3.0/3.0.3/lib                              |
| OpenSSL Version             | OpenSSL 1.1.1m  14 Dec 2021                                       |
| Is contained                | false                                                             |
| Is homebrew                 | false                                                             |
| Is installed via Fabric.app | false                                                             |
| Xcode Path                  | /Applications/Xcode_13.3.app/Contents/Developer/                  |
| Xcode Version               | 13.3                                                              |
| Swift Version               | 5.6                                                               |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.205.1 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                 | Version | Update-Status |
| ---------------------- | ------- | ------------- |
| fastlane-plugin-sentry | 1.11.1  | ✅ Up-To-Date  |


### Loaded gems

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| bundler                         | 2.3.7        |
| pathname                        | 0.1.0        |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| concurrent-ruby                 | 1.1.10       |
| i18n                            | 1.10.0       |
| minitest                        | 5.15.0       |
| tzinfo                          | 2.0.4        |
| zeitwerk                        | 2.5.4        |
| activesupport                   | 6.1.5        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| httpclient                      | 2.8.3        |
| json                            | 2.6.1        |
| algoliasearch                   | 1.27.5       |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.570.0      |
| aws-sigv4                       | 1.4.0        |
| jmespath                        | 1.6.1        |
| aws-sdk-core                    | 3.130.0      |
| aws-sdk-kms                     | 1.55.0       |
| aws-sdk-s3                      | 1.113.0      |
| babosa                          | 1.0.4        |
| claide                          | 1.1.0        |
| fuzzy_match                     | 2.0.4        |
| nap                             | 1.1.0        |
| netrc                           | 0.11.0       |
| ffi                             | 1.15.5       |
| ethon                           | 0.15.0       |
| typhoeus                        | 1.4.0        |
| cocoapods-core                  | 1.11.3       |
| cocoapods-deintegrate           | 1.0.5        |
| cocoapods-downloader            | 1.6.1        |
| cocoapods-plugins               | 1.0.0        |
| cocoapods-search                | 1.0.1        |
| cocoapods-trunk                 | 1.6.0        |
| cocoapods-try                   | 1.2.0        |
| colored2                        | 3.1.2        |
| escape                          | 0.0.4        |
| fourflusher                     | 2.3.1        |
| gh_inspector                    | 1.1.3        |
| molinillo                       | 0.8.0        |
| ruby-macho                      | 2.5.1        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| cocoapods                       | 1.11.3       |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.8.1      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.92.1       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.0.0        |
| faraday-multipart               | 1.0.3        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.0       |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| jwt                             | 2.3.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.1       |
| googleauth                      | 1.1.2        |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.2        |
| google-apis-androidpublisher_v3 | 0.16.0       |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.11.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.36.1       |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| fastlane-plugin-sentry          | 1.11.1       |
| http-accept                     | 1.7.0        |
| mime-types-data                 | 3.2022.0105  |
| mime-types                      | 3.4.1        |
| rest-client                     | 2.1.0        |


*generated on:* **2022-03-25**

**Comment by monchote** [comment]
Are you using the final version of Xcode 13.3? This was affecting the betas but got fixed with the RC
- https://github.com/CocoaPods/CocoaPods/issues/11196
- https://github.com/CocoaPods/CocoaPods/issues/8891#issuecomment-1063056608
