### ISSUE TITLE
SonarQuebe link is not redirecting to a valid website

### ISSUE THREAD

**Issue by asif13** [fastlane/fastlane#20146]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
we have sonarquebe website url in source code of sonar.rb to help with understanding the sonar action functionalities, but the link is broken
link which is broken - http://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner

##### Command executed
NA

##### Complete output when running fastlane, including the stack trace and command used
NA

### Environment
NA

**Comment by Emmitt121** [comment]
I've exactly the same problem. I've put my sonarqube domain name but my redirect_uri is localhost:9000... It's maybe a problem with the sonarqube configuration because its default listen port is 9000 (for me, sonarqube run in a container and i've bind 0.0.0.0:57563 with 9000/tcp)

**Comment by CaseyCw1** [comment]
Thanks for the information, I will try to figure it out for more. Keep sharing such informative post keep suggesting such post.
