### ISSUE TITLE
get_certificates errors with 'Authentication credentials are missing or invalid. - Provide a properly configured and signed bearer token, and make sure that it has not expired.'

### ISSUE THREAD

**Issue by indiejames** [fastlane/fastlane#20143]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue 

`get_certificates` returns an  authentication error despite previously calling `app_store_connect_api_key`. This worked for months previously. I have tried generating a new API key, but I still get the error.

##### Command executed

```
bundle exec fastlane beta
```

##### Complete output when running fastlane, including the stack trace and command used
<details>
<pre>
[✔] 🚀 
[14:08:39]: -----------------------------
[14:08:39]: --- Step: update_fastlane ---
[14:08:39]: -----------------------------
[14:08:39]: Looking for updates for fastlane...
[14:08:42]: Nothing to update ✅
[14:08:42]: ------------------------------
[14:08:42]: --- Step: default_platform ---
[14:08:42]: ------------------------------
[14:08:42]: Driving the lane 'ios beta' 🚀
[14:08:42]: ---------------------------------------
[14:08:42]: --- Step: app_store_connect_api_key ---
[14:08:42]: ---------------------------------------
[14:08:42]: ---------------------
[14:08:42]: --- Step: xcclean ---
[14:08:42]: ---------------------
[14:08:42]: For a more detailed xcodebuild log open /Users/jnorton/Library/Logs/fastlane/xcbuild/2022-04-03/46711/xcodebuild.log
[14:08:42]: $ set -o pipefail && xcodebuild clean | tee '/Users/jnorton/Library/Logs/fastlane/xcbuild/2022-04-03/46711/xcodebuild.log' | xcpretty --color --simple
[14:08:45]: ▸ Clean Succeeded
[14:08:45]: ------------------------------
[14:08:45]: --- Step: get_certificates ---
[14:08:45]: ------------------------------

+-------------------------+---------------------------------------+
|                    Summary for cert 2.205.1                     |
+-------------------------+---------------------------------------+
| api_key                 | ********                              |
| development             | false                                 |
| force                   | false                                 |
| generate_apple_certs    | true                                  |
| username                | ...                                   |
| team_id                 | ...                                   |
| keychain_path           | ...                                   |
| skip_set_partition_list | false                                 |
| platform                | ios                                   |
+-------------------------+---------------------------------------+

[14:08:45]: Creating authorization token for App Store Connect API

+------------------------------+----------+
|              Lane Context               |
+------------------------------+----------+
| DEFAULT_PLATFORM             | ios      |
| PLATFORM_NAME                | ios      |
| LANE_NAME                    | ios beta |
| XCODEBUILD_DERIVED_DATA_PATH |          |
+------------------------------+----------+
[14:08:45]: Authentication credentials are missing or invalid. - Provide a properly configured and signed bearer token, and make sure that it has not expired. Learn more about Generating Tokens for API Requests https://developer.apple.com/go/?id=api-generating-tokens

+------+-------------------------+-------------+
|               fastlane summary               |
+------+-------------------------+-------------+
| Step | Action                  | Time (in s) |
+------+-------------------------+-------------+
| 1    | update_fastlane         | 3           |
| 2    | default_platform        | 0           |
| 3    | app_store_connect_api_  | 0           |
|      | key                     |             |
| 4    | xcclean                 | 2           |
| 💥   | get_certificates        | 0           |
+------+-------------------------+-------------+

[14:08:45]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

[!] The request could not be completed because:
	Authentication credentials are missing or invalid. - Provide a properly configured and signed bearer token, and make sure that it has not expired. Learn more about Generating Tokens for API Requests https://developer.apple.com/go/?id=api-generating-tokens

 </pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.7                                     |
| Ruby                        | 3.0.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.28.0                          |
| Installation Source         | ~/.rbenv/versions/3.0.2/bin/fastlane        |
| Host                        | Mac OS X 10.15.7 (19H1615)                  |
| Ruby Lib Dir                | ~/.rbenv/versions/3.0.2/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.4                                        |
| Swift Version               | 5.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    app_store_connect_api_key(
      key_id: "...",
      issuer_id: "...",
      key_filepath: "...",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )
    xcclean
    get_certificates           # invokes cert
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("...") # The bundle identifier of your app
apple_id("...") # Your Apple email address

itc_team_id("...") # App Store Connect Team ID
team_id("...") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.205.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| bundler                         | 2.2.28       |
| tsort                           | 0.1.0        |
| uri                             | 0.10.1       |
| pathname                        | 0.1.0        |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.573.0      |
| aws-sigv4                       | 1.4.0        |
| jmespath                        | 1.6.1        |
| aws-sdk-core                    | 3.130.0      |
| aws-sdk-kms                     | 1.55.0       |
| aws-sdk-s3                      | 1.113.0      |
| babosa                          | 1.0.4        |
| claide                          | 1.1.0        |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.8.1      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.92.2       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.0.0        |
| faraday-multipart               | 1.0.3        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.0       |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.3.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.1       |
| googleauth                      | 1.1.2        |
| httpclient                      | 2.8.3        |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.2        |
| google-apis-androidpublisher_v3 | 0.17.0       |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.11.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.36.1       |
| json                            | 2.6.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
</details>

*generated on:* **2022-04-03**
</details> </pre>
</details>

**Comment by panderman** [comment]
It's seem like your Apple account is ban by apple, can you login apple account developer? If not,try another apple account and then generate p8 key，good luck

**Comment by indiejames** [comment]
I have no problem logging into the Apple developer site (or App Store Connect for that matter).

**Comment by indiejames** [comment]
I tracked this down to setting the timeout to 1200. I didn't see any error message, but when I lowered it to 500 things started working.

**Comment by panderman** [comment]
> I tracked this down to setting the timeout to 1200. I didn't see any error message, but when I lowered it to 500 things started working.

Ok,may be you can use custom retry function when exception raise,I always use retry 3 times when exceptions raise.
