### ISSUE TITLE
Could not change CODE_SIGN_IDENTITY using an update_project_provisioning actions

### ISSUE THREAD

**Issue by davydspotnana** [fastlane/fastlane#20153]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I have 3 shemes, each of them used *.Debug + *.Relese variants:

<img width="1177" alt="Screenshot 2022-04-07 at 19 49 38" src="https://user-images.githubusercontent.com/95620376/162267398-51cc9f58-8d89-4172-9892-38f146308c92.png">

so when invoke `update_project_provisioning` actions to apply profile `CODE_SIGN_IDENTITY` isn't changing

And ad-hoc build failed with errors
- `error: Provisioning profile "match AdHoc com.spotnana.ios.staging" doesn't include signing certificate "Apple Development: D N (ZWPU7N53HR)". (in target 'Spotnana' from project 'Spotnana')`

as by default `CODE_SIGN_IDENTITY = "iOS Development"`

<table>
<tr>
<th>
DO NOT WORK ❌
</th>
<th>
WORK ✅
</th>
</tr>

<tr>
<td>

```rb
update_project_provisioning(
  xcodeproj: "./ios/MyApp.xcodeproj",
  profile: ENV["...adhoc_profile-path"],
  build_configuration: "Staging.Release",
  target_filter: "MyApp",
  code_signing_identity: "iPhone Distribution"
)
```

</td>
<td>

```diff
+update_code_signing_settings(
+  use_automatic_signing: false,
+  path: xcodeproj_path,
+  code_sign_identity: "iPhone Distribution"
+)

update_project_provisioning(
  xcodeproj: "./ios/MyApp.xcodeproj",
  profile: ENV["...adhoc_profile-path"],
  build_configuration: "Staging.Release",
  target_filter: "MyApp",
  code_signing_identity: "iPhone Distribution"
)
```

</td>
</tr>
</table>

So, **I have to use another an action** `update_code_signing_settings` just to update `CODE_SIGN_IDENTITY`

##### Command executed

...

##### Complete output when running fastlane, including the stack trace and command used

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 12.1                                                           |
| Ruby                        | 2.6.8                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.32.0 (Apple Git-132)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 12.1 (21C52)                                             |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 13.2.1                                                         |
| Swift Version               | 5.5.2                                                          |

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.205.1 | ✅ Up-To-Date  |

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.3.3   | ✅ Up-To-Date  |
| fastlane-plugin-browserstack              | 0.3.2   | ✅ Up-To-Date  |

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.3.0        |
| atomos                                    | 0.1.3        |
| claide                                    | 1.1.0        |
| colored2                                  | 3.1.2        |
| nanaimo                                   | 0.3.0        |
| rexml                                     | 3.2.5        |
| xcodeproj                                 | 1.21.0       |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.8.0        |
| terminal-table                            | 1.8.0        |
| plist                                     | 3.6.0        |
| public_suffix                             | 4.0.6        |
| addressable                               | 2.8.0        |
| multipart-post                            | 2.0.0        |
| word_wrap                                 | 1.0.0        |
| optparse                                  | 0.1.1        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| artifactory                               | 3.0.15       |
| babosa                                    | 1.0.4        |
| colored                                   | 1.2          |
| highline                                  | 2.0.3        |
| commander                                 | 4.6.0        |
| excon                                     | 0.92.2       |
| faraday-em_http                           | 1.0.0        |
| faraday-em_synchrony                      | 1.0.0        |
| faraday-excon                             | 1.1.0        |
| faraday-httpclient                        | 1.0.1        |
| faraday-multipart                         | 1.0.3        |
| faraday-net_http                          | 1.0.1        |
| faraday-net_http_persistent               | 1.2.0        |
| faraday-patron                            | 1.0.0        |
| faraday-rack                              | 1.0.0        |
| faraday-retry                             | 1.0.3        |
| ruby2_keywords                            | 0.0.5        |
| faraday                                   | 1.10.0       |
| unf_ext                                   | 0.0.8.1      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| http-cookie                               | 1.0.4        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.2.0        |
| fastimage                                 | 2.2.6        |
| gh_inspector                              | 1.1.3        |
| mini_magick                               | 4.11.0       |
| naturally                                 | 2.2.1        |
| rubyzip                                   | 2.3.2        |
| security                                  | 0.1.3        |
| xcpretty-travis-formatter                 | 1.0.1        |
| dotenv                                    | 2.7.6        |
| bundler                                   | 2.3.6        |
| simctl                                    | 1.6.8        |
| jwt                                       | 2.3.0        |
| uber                                      | 0.1.0        |
| declarative                               | 0.0.20       |
| trailblazer-option                        | 0.1.2        |
| representable                             | 3.1.1        |
| retriable                                 | 3.1.2        |
| mini_mime                                 | 1.1.2        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.4        |
| signet                                    | 0.16.1       |
| googleauth                                | 1.1.2        |
| httpclient                                | 2.8.3        |
| google-apis-core                          | 0.4.2        |
| google-apis-playcustomapp_v1              | 0.7.0        |
| google-cloud-env                          | 1.6.0        |
| google-cloud-errors                       | 1.2.0        |
| google-cloud-core                         | 1.6.0        |
| google-apis-iamcredentials_v1             | 0.10.0       |
| digest-crc                                | 0.6.4        |
| google-cloud-storage                      | 1.36.1       |
| emoji_regex                               | 3.2.3        |
| jmespath                                  | 1.6.1        |
| aws-eventstream                           | 1.2.0        |
| aws-sigv4                                 | 1.4.0        |
| aws-sdk-core                              | 3.130.0      |
| aws-sdk-kms                               | 1.55.0       |
| aws-sdk-s3                                | 1.113.0      |
| CFPropertyList                            | 3.0.5        |
| json                                      | 2.6.1        |
| webrick                                   | 1.7.0        |
| google-apis-androidpublisher_v3           | 0.18.0       |
| google-apis-storage_v1                    | 0.12.0       |
| rake                                      | 13.0.6       |
| aws-partitions                            | 1.574.0      |
| forwardable                               | 1.2.0        |
| logger                                    | 1.3.0        |
| date                                      | 2.0.0        |
| stringio                                  | 0.0.2        |
| ipaddr                                    | 1.2.2        |
| openssl                                   | 2.1.2        |
| zlib                                      | 1.0.0        |
| mutex_m                                   | 0.1.0        |
| ostruct                                   | 0.1.0        |
| strscan                                   | 1.0.0        |
| io-console                                | 0.4.7        |
| fileutils                                 | 1.1.0        |
| etc                                       | 1.0.1        |
| libxml-ruby                               | 3.2.1        |
| psych                                     | 3.1.0        |
| fastlane-plugin-firebase_app_distribution | 0.3.3        |
| http-accept                               | 1.7.0        |
| mime-types-data                           | 3.2022.0105  |
| mime-types                                | 3.4.1        |
| netrc                                     | 0.11.0       |
| rest-client                               | 2.1.0        |
| fastlane-plugin-browserstack              | 0.3.2        |
</details>

**Comment by Farr69** [comment]
Take note that before code signing the application itself, we first have to retrieve the entitlements that were embedded into the application binary, update them to contain the bundle ID and application ID that were in the customer’s mobileprovision file, and re-embed those entitlements back into the application binary. This happens in the prepare_entitlements method and its various helper methods.

**Comment by lucgrabowski** [comment]
If you want to update code signing settings, could you turn off "Automatically manage signing" with http://docs.fastlane.tools/actions/update_code_signing_settings/#update_code_signing_settings as in the first example in docs?

**Comment by davydspotnana** [comment]
@lucgrabowski It won't help 

My code: 
![image](https://user-images.githubusercontent.com/95620376/173192882-06c6d9c5-6b71-4697-bfb6-39cb7a744dc4.png)

**Comment by davydspotnana** [comment]
<table>
<tr>
<th>
DO NOT WORK ❌
</th>
<th>
WORK ✅
</th>
</tr>


<tr>
<td>

```diff
update_project_provisioning(
      xcodeproj: "./ios/MyApp.xcodeproj",
      profile: ENV["...adhoc_profile-path"],
      build_configuration: "Staging.Release",
      target_filter: "MyApp",
      code_signing_identity: "iPhone Distribution"
    )
```

</td>
<td>

```diff
+    update_code_signing_settings(
+      use_automatic_signing: false,
+      path: xcodeproj_path,
+      code_sign_identity: "iPhone Distribution"
+    )
    
update_project_provisioning(
      xcodeproj: "./ios/MyApp.xcodeproj",
      profile: ENV["...adhoc_profile-path"],
      build_configuration: "Staging.Release",
      target_filter: "MyApp",
      code_signing_identity: "iPhone Distribution"
    )
```

</td>
</tr>
</table>
