### ISSUE TITLE
Fastlane beta provision profile and gym errors

### ISSUE THREAD

**Issue by elirangoshen** [fastlane/fastlane#20157]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
when running fastlane beta gives 2 errors: 
1. error: No profile for team 'BW66K849Z5' matching 'match AppStore app.yonder.mobile' found: Xcode couldn't find any provisioning profiles matching 'BW66K849Z5/match AppStore app.yonder.mobile'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the Signing & Capabilities tab of the target editor. (in target 'Yonder' from project 'Yonder')
2. There seems to be a mismatch between your provided `export_method` in gym
[13:36:19]: and the selected provisioning profiles. You passed the following options:
[13:36:19]:   export_method:      
[13:36:19]:   Bundle identifier:  app.yonder.mobile
[13:36:19]:   Profile name:       match AppStore app.yonder.mobile
[13:36:19]:   Profile type:       app-store
[13:36:19]: Make sure to either change the `export_method` passed from your Fastfile or CLI
[13:36:19]: or select the correct provisioning profiles by updating your Xcode project
[13:36:19]: or passing the profiles to use by using match or manually via the `export_options` hash

##### Command executed
fastlane beta

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [13:36:18]: Exit status: 1

+-------------+-------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.205.1                 |
| sdk         | iPhoneOS15.4.sdk        |
+-------------+-------------------------+

[13:36:19]: ▸ Build description path: /var/root/Library/Developer/Xcode/DerivedData/Yonder-fvjndkvubsrjoxfopzezeljmbles/Build/Intermediates.noindex/ArchiveIntermediates/Yonder/IntermediateBuildFilesPath/XCBuildData/de8c6cd07dc88afc256ad825ee2e2f9c-desc.xcbuild
[13:36:19]: ▸ note: Build preparation complete
[13:36:19]: ▸ note: Building targets in dependency order
[13:36:19]: ▸ error: No profile for team 'BW66K849Z5' matching 'match AppStore app.yonder.mobile' found: Xcode couldn't find any provisioning profiles matching 'BW66K849Z5/match AppStore app.yonder.mobile'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the Signing & Capabilities tab of the target editor. (in target 'Yonder' from project 'Yonder')
[13:36:19]: 
[13:36:19]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[13:36:19]: 📋  For the complete and more detailed error log, check the full log at:
[13:36:19]: 📋  /Users/elirangoshen/Library/Logs/gym/Yonder-Yonder.log
[13:36:19]: 
[13:36:19]: There seems to be a mismatch between your provided `export_method` in gym
[13:36:19]: and the selected provisioning profiles. You passed the following options:
[13:36:19]:   export_method:      
[13:36:19]:   Bundle identifier:  app.yonder.mobile
[13:36:19]:   Profile name:       match AppStore app.yonder.mobile
[13:36:19]:   Profile type:       app-store
[13:36:19]: Make sure to either change the `export_method` passed from your Fastfile or CLI
[13:36:19]: or select the correct provisioning profiles by updating your Xcode project
[13:36:19]: or passing the profiles to use by using match or manually via the `export_options` hash
[13:36:19]: 
[13:36:19]: 
[13:36:19]: Looks like fastlane ran into a build/archive error with your project
[13:36:19]: It's hard to tell what's causing the error, so we wrote some guides on how
[13:36:19]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[13:36:19]: Before submitting an issue on GitHub, please follow the guide above and make
[13:36:19]: sure your project is set up correctly.
[13:36:19]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
[13:36:19]: the full commands printed out in yellow in the above log.
[13:36:19]: Make sure to inspect the output above, as usually you'll find more error information there
[13:36:19]: 
+------------------+----------+
|        Lane Context         |
+------------------+----------+
| DEFAULT_PLATFORM | ios      |
| PLATFORM_NAME    | ios      |
| LANE_NAME        | ios beta |
| BUILD_NUMBER     | 3        |
+------------------+----------+
[13:36:19]: Error building the application - see the log above
[13:36:19]: Permission denied @ rb_sysopen - ./fastlane/README.md
[13:36:19]: Couldn't save fastlane documentation at path '/Users/elirangoshen/Projects/Yonder New/Yonder/ios/fastlane/README.md', make sure you have write access to the containing directory.
[13:36:19]: Permission denied @ rb_sysopen - ./fastlane/report.xml
[13:36:19]: Couldn't save report.xml at path '/Users/elirangoshen/Projects/Yonder New/Yonder/ios/fastlane/report.xml', make sure you have write access to the containing directory.

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | default_platform       | 0           |
| 2    | increment_build_number | 1           |
| 💥   | build_app              | 407         |
+------+------------------------+-------------+

[13:36:19]: fastlane finished with errors

[!] Error building the application - see the log above </pre>
</details>

### Environment

<details>
  <pre> elirangoshen@MacBook-Pro-3 fastlane % fastlane env
[⠹] 🚀 Ignoring ffi-1.13.1 because its extensions are not built. Try: gem pristine ffi --version 1.13.1
[✔] 🚀 
[13:48:45]: fastlane detected a Gemfile in the current directory
[13:48:45]: However, it seems like you didn't use `bundle exec`
[13:48:45]: To launch fastlane faster, please use
[13:48:45]: 
[13:48:45]: $ bundle exec fastlane env
[13:48:45]: 
[13:48:45]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[13:48:47]: Generating fastlane environment output, this might take a few seconds...
swift-driver version: 1.45.2 <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 12.0.1                                                         |
| Ruby                        | 2.6.8                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.32.0 (Apple Git-132)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 12.0.1 (21A559)                                          |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 13.3                                                           |
| Swift Version               | 5.6                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "Yonder.xcodeproj")
    build_app(workspace: "Yonder.xcworkspace", scheme: "Yonder")
    upload_to_testflight
  end
end

```
</details>

<details><summary>`./Appfile`</summary>

```ruby
app_identifier("app.yonder.mobile") # The bundle identifier of your app
apple_id("elirangoshen@gmail.com") # Your Apple email address

itc_team_id("124164726") # App Store Connect Team ID
team_id("BW66K849Z5") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.205.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| CFPropertyList                  | 2.3.6        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.92.2       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.3        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.0       |
| unf_ext                         | 0.0.8.1      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.1.0        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 1.17.2       |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.1       |
| googleauth                      | 1.1.2        |
| httpclient                      | 2.8.3        |
| rexml                           | 3.1.9.1      |
| webrick                         | 1.4.4        |
| google-apis-core                | 0.4.2        |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-androidpublisher_v3 | 0.18.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.12.0       |
| rake                            | 12.3.3       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.36.1       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.6.1        |
| aws-partitions                  | 1.574.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-sdk-core                    | 3.130.0      |
| aws-sdk-kms                     | 1.55.0       |
| aws-sdk-s3                      | 1.113.0      |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.0.3        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.19.0       |
| forwardable                     | 1.2.0        |
| logger                          | 1.3.0        |
| date                            | 2.0.0        |
| stringio                        | 0.0.2        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.0.0        |
| mutex_m                         | 0.1.0        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| io-console                      | 0.4.7        |
| fileutils                       | 1.1.0        |
| etc                             | 1.0.1        |
| libxml-ruby                     | 3.2.1        |
| psych                           | 3.1.0        |
</details></pre>
</details>

**Comment by lucgrabowski** [comment]
It seems that in the project in Xcode's code signing tab you have a profile managed by `match` tool set for release configuration. 
You should run `match` before `build_app` to install the profile if it's not on the computer you use.
https://docs.fastlane.tools/actions/match/ In your case, you should set `appstore` in `type` option.

**Comment by elirangoshen** [comment]
> It seems that in the project in Xcode's code signing tab you have a profile managed by `match` tool set for release configuration. You should run `match` before `build_app` to install the profile if it's not on the computer you use. https://docs.fastlane.tools/actions/match/ In your case, you should set `appstore` in `type` option.

So I shouldn't use match in xcode configuration ? i mean thats what i'm getting eventually from match automatically..

**Comment by lucgrabowski** [comment]
You can select it in xcode or use http://docs.fastlane.tools/actions/update_project_provisioning/#update_project_provisioning to update it before `build_app`'s call.
Are you sure that you have this profile installed on the computer you use to build the app?
I advise you to run `match` before `build_app`, like this:
```ruby
lane :beta do
    increment_build_number(xcodeproj: "Yonder.xcodeproj")
    match(type: "appstore")
    build_app(workspace: "Yonder.xcworkspace", scheme: "Yonder")
    upload_to_testflight
  end
```
You may need to adjust the options, this just an example.
