### ISSUE TITLE
[Fastlane.Swift] can't omit precision for a Float in plugin icon_versioning

### ISSUE THREAD

**Issue by sebspi** [fastlane/fastlane#20156]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I tried to install the plugin [icon_versioning](https://github.com/revolter/fastlane-plugin-icon_versioning) in Fastlane Swift. But somehow I got this error message and do not know how to fix this.

##### Command executed
`fastlane add_plugin icon_versioning`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
bundler: failed to load command: fastlane (/Users/sebastian/.rbenv/versions/3.0.3/bin/fastlane)
/Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/swift_fastlane_function.rb:177:in `BigDecimal': \e[31m[!] can't omit precision for a Float.\e[0m (ArgumentError)
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/swift_fastlane_function.rb:177:in `block in parameters'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/swift_fastlane_function.rb:165:in `map'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/swift_fastlane_function.rb:165:in `parameters'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/swift_fastlane_function.rb:226:in `swift_code'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/swift_fastlane_api_generator.rb:171:in `block in generate_swift'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/documentation/actions_list.rb:180:in `block in all_actions'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/documentation/actions_list.rb:172:in `each'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/documentation/actions_list.rb:172:in `all_actions'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/swift_fastlane_api_generator.rb:155:in `generate_swift'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/commands_generator.rb:348:in `block (2 levels) in run'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.205.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.205.1/bin/fastlane:23:in `<top (required)>'
	from /Users/sebastian/.rbenv/versions/3.0.3/bin/fastlane:25:in `load'
	from /Users/sebastian/.rbenv/versions/3.0.3/bin/fastlane:25:in `<top (required)>'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/cli/exec.rb:58:in `load'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/cli/exec.rb:23:in `run'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/cli.rb:478:in `exec'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/cli.rb:31:in `dispatch'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/cli.rb:25:in `start'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/libexec/bundle:49:in `block in <top (required)>'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/libexec/bundle:37:in `<top (required)>'
	from /Users/sebastian/.rbenv/versions/3.0.3/bin/bundle:23:in `load'
	from /Users/sebastian/.rbenv/versions/3.0.3/bin/bundle:23:in `<main>'
/Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/swift_fastlane_function.rb:177:in `BigDecimal': can't omit precision for a Float. (ArgumentError)
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/swift_fastlane_function.rb:177:in `block in parameters'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/swift_fastlane_function.rb:165:in `map'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/swift_fastlane_function.rb:165:in `parameters'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/swift_fastlane_function.rb:226:in `swift_code'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/swift_fastlane_api_generator.rb:171:in `block in generate_swift'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/documentation/actions_list.rb:180:in `block in all_actions'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/documentation/actions_list.rb:172:in `each'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/documentation/actions_list.rb:172:in `all_actions'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/swift_fastlane_api_generator.rb:155:in `generate_swift'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/commands_generator.rb:348:in `block (2 levels) in run'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.205.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.205.1/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/fastlane-2.205.1/bin/fastlane:23:in `<top (required)>'
	from /Users/sebastian/.rbenv/versions/3.0.3/bin/fastlane:25:in `load'
	from /Users/sebastian/.rbenv/versions/3.0.3/bin/fastlane:25:in `<top (required)>'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/cli/exec.rb:58:in `load'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/cli/exec.rb:23:in `run'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/cli.rb:478:in `exec'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/cli.rb:31:in `dispatch'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/cli.rb:25:in `start'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/libexec/bundle:49:in `block in <top (required)>'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /Users/sebastian/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/libexec/bundle:37:in `<top (required)>'
	from /Users/sebastian/.rbenv/versions/3.0.3/bin/bundle:23:in `load'
	from /Users/sebastian/.rbenv/versions/3.0.3/bin/bundle:23:in `<main>'
 </pre>
</details>

### Environment

<details>
  <pre> 
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 12.2.1                                      |
| Ruby                        | 3.0.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.32.0 (Apple Git-132)          |
| Installation Source         | ~/.rbenv/versions/3.0.3/bin/fastlane        |
| Host                        | macOS 12.2.1 (21D62)                        |
| Ruby Lib Dir                | ~/.rbenv/versions/3.0.3/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 13.3                                        |
| Swift Version               | 5.6                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

```ruby
// This file contains the fastlane.tools configuration
// You can find the documentation at https://docs.fastlane.tools
//
// For a list of all available actions, check out
//
//     https://docs.fastlane.tools/actions
//

import Foundation

class Fastfile: LaneFile {
	func customLane() {
	desc("Description of what the lane does")
		// add actions here: https://docs.fastlane.tools/actions
	}
}

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.205.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                          | Version | Update-Status |
| ------------------------------- | ------- | ------------- |
| fastlane-plugin-icon_versioning | 1.4.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.2.32       |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.2        |
| google-apis-playcustomapp_v1    | 0.7.0        |
| emoji_regex                     | 3.2.3        |
| set                             | 1.0.1        |
| excon                           | 0.92.2       |
| ruby2_keywords                  | 0.0.5        |
| faraday-retry                   | 1.0.3        |
| faraday-rack                    | 1.0.0        |
| faraday-patron                  | 1.0.0        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-net_http                | 1.0.1        |
| faraday-multipart               | 1.0.3        |
| faraday-httpclient              | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.10.0       |
| unf_ext                         | 0.0.8.1      |
| json                            | 2.6.1        |
| multi_json                      | 1.15.0       |
| signet                          | 0.16.1       |
| os                              | 1.1.4        |
| memoist                         | 0.16.2       |
| googleauth                      | 1.1.2        |
| google-apis-androidpublisher_v3 | 0.18.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-apis-storage_v1          | 0.12.0       |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-cloud-errors             | 1.2.0        |
| google-cloud-env                | 1.6.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.36.1       |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-partitions                  | 1.574.0      |
| jmespath                        | 1.6.1        |
| aws-sdk-core                    | 3.130.0      |
| aws-sdk-kms                     | 1.55.0       |
| aws-sdk-s3                      | 1.113.0      |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.1        |
| date                            | 3.1.3        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.0        |
| uri                             | 0.10.1       |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.2.1        |
| digest                          | 3.0.0        |
| io-nonblock                     | 0.1.0        |
| io-wait                         | 0.2.0        |
| zlib                            | 2.0.0        |
| resolv                          | 0.2.1        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.1        |
| rack                            | 2.2.3        |
| rack-test                       | 1.1.0        |
| fileutils                       | 1.5.0        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| tmpdir                          | 0.1.2        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.7        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| net-http                        | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| nokogiri                        | 1.12.5       |
| racc                            | 1.6.0        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.2.1        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.2        |
| fastlane-plugin-icon_versioning | 1.4.0        |
| benchmark                       | 0.1.1        |
</details>

*generated on:* **2022-04-08**
</details>
</pre>
</details>

**Comment by Russel476** [comment]
I faced similar kind of issue last time, I am still searching for some proper solution.

**Comment by Nebel69** [comment]
I am experiencing the same issue. I will guess it depends on the architecture, my system is 32 bit so I think there is where I get the rounding error.

**Comment by Erin69** [comment]
I am experiencing the same issue. I will guess it depends on the architecture, my system is 32 bit so I think there is where I get the rounding error.
