### ISSUE TITLE
Google Play Data Safety section

### ISSUE THREAD

**Issue by pkwiatkowski0** [fastlane/fastlane#20161]
### Discussed in https://github.com/fastlane/fastlane/discussions/19851

<div type='discussions-op-text'>

<sup>Originally posted by **codyrotwein** January 25, 2022</sup>
As you are probably aware, Google Play will start displaying a data safety section on the store starting next month, and enforcing developers to populate the section in April: https://android-developers.googleblog.com/2021/10/launching-data-safety-in-play-console.html 

They have given a way to export/import a CSV to make it easier. Are there any plans for fastlane to support this, or is it not part of the google play api? Can anyone lead me in the right direction as how I could possibly automate doing this? We have over 300 apps that would need get updated. Thanks!</div>

**Comment by Renner11** [comment]
Developers agree that people should have transparency and control over their data.

**Comment by Hendershott** [comment]
Overview. The Data safety section on Google Play is a simple way for you to help people understand what user data your app collects or shares, as well as showcase your app's key privacy and security practices. This information helps users make more informed choices when deciding which apps to install.
[MyCFAVisit](https://www.mycfavisit.biz/)

**Comment by Ocello1** [comment]
Hii  pkwiatkowski0,
I have Question 
Which developers need to complete the Data safety form in Play Console?
What developers need to disclose in the Data safety form?

Thanks
Ocello1

**Comment by markmuniz** [comment]
Does Fastlane intend on supporting this? Since the initial deadline yesterday, we're seeing warnings in Google Play. It seems that we have until August 22, 2022 to address this.

**Comment by patreu22** [comment]
+1 for this issue
