### ISSUE TITLE
Add authentication request for match repo clonning

### ISSUE THREAD

**Issue by kamenovpk** [fastlane/fastlane#20199]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Match hanging on clonning repo step and doesn't show request to input password from ssh key.

Workaround is to add your key to ssh-agent.

I found some forgotten [issue](https://github.com/fastlane/fastlane/issues/1982) , but the problem is still here.

### Environment

macOS Monterey 12.3.1

**Comment by jenne045** [comment]
If you want to clone it to a specific folder, just insert the folder address at the end like so: git clone https://<token>@github.com/<username>/<repository.git> <folder> , where <folder> is, you guessed it, the folder to clone it to! You can of course use . , .. , ~ , etc.

**Comment by Farr69** [comment]
This was the exact problem I was looking for and the answer worked great. Thanks a lot.
