### ISSUE TITLE
Clarification: Can I use the fastlane snapshots without the Test target

### ISSUE THREAD

**Issue by nihp** [fastlane/fastlane#20191]
Can I use the fastlane snapshots without the Test target?

I need to know the fastane snapshot setup needs to be added the test target. If the Test target is not available and If I add the fastlane snapshot, does it works for me or not?

**Comment by rogerluan** [comment]
Transferred issue to the right repository.

**Comment by rogerluan** [comment]
@nihp I think that having UI tests is a precondition to using fastlane snapshot. Not entirely sure, though.

**Comment by Russel476** [comment]
I totally like your gave limits as the post you passed on has some uncommon information which is totally essential for me.

**Comment by lucgrabowski** [comment]
Setting up UI tests target is a precondition as @rogerluan said. You can read more on how to set it up in docs: https://docs.fastlane.tools/getting-started/ios/screenshots/#setting-up-snapshot
