### ISSUE TITLE
screengrab: data / sdcard paths: No such file or directory

### ISSUE THREAD

**Issue by benomatis** [fastlane/fastlane#20201]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
screengrab lane completes with success, but then it is unable to extract the images taken from the device looking at the incorrect path. It may have something to do with the fact I'm using 'en-CA' as locale.

When I checked any of the paths on the emulator via Android Studio file explorer they did not exist, I tried creating them manually but that made no difference, error was still the same.

##### Command executed
```bundle exec fastlane screengrab```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>% bundle exec fastlane screengrab
[✔] 🚀 
objc[29577]: Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib (0x205001eb0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1087384f8). One of the two will be used. Which one is undefined.
objc[29577]: Class AppleTypeCRetimerFirmwareAggregateRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x205001f00) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x108738548). One of the two will be used. Which one is undefined.
objc[29577]: Class AppleTypeCRetimerFirmwareRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x205001f50) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x108738598). One of the two will be used. Which one is undefined.
objc[29577]: Class ATCRTRestoreInfoFTABFile is implemented in both /usr/lib/libauthinstall.dylib (0x205001fa0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1087385e8). One of the two will be used. Which one is undefined.
objc[29577]: Class AppleTypeCRetimerFirmwareCopier is implemented in both /usr/lib/libauthinstall.dylib (0x205001ff0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x108738638). One of the two will be used. Which one is undefined.
objc[29577]: Class ATCRTRestoreInfoFTABSubfile is implemented in both /usr/lib/libauthinstall.dylib (0x205002040) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x108738688). One of the two will be used. Which one is undefined.
[22:10:06]: Successfully loaded '/path/to/fastlane/Screengrabfile' 📄

+----------------------------+--------------------------------------------------------------------------+
|                           Detected Values from './fastlane/Screengrabfile'                            |
+----------------------------+--------------------------------------------------------------------------+
| locales                    | ["en-CA"]                                                                |
| clear_previous_screenshots | true                                                                     |
| app_apk_path               | android/app/build/outputs/apk/debug/app-debug.apk                        |
| tests_apk_path             | android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.a  |
|                            | pk                                                                       |
| app_package_name           | com.myapp                                                   |
+----------------------------+--------------------------------------------------------------------------+

+-----------------------------+--------------------------------------------------------------------------+
|                                     Summary for screengrab 2.205.1                                     |
+-----------------------------+--------------------------------------------------------------------------+
| tests_package_name          | com.myapp.test                                              |
| android_home                | /Users/user/Library/Android/sdk                                     |
| locales                     | ["en-CA"]                                                                |
| clear_previous_screenshots  | true                                                                     |
| output_directory            | fastlane/metadata/android                                                |
| skip_open_summary           | false                                                                    |
| app_package_name            | com.myapp                                                   |
| test_instrumentation_runner | androidx.test.runner.AndroidJUnitRunner                                  |
| ending_locale               | en-US                                                                    |
| use_adb_root                | false                                                                    |
| app_apk_path                | android/app/build/outputs/apk/debug/app-debug.apk                        |
| tests_apk_path              | android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.a  |
|                             | pk                                                                       |
| device_type                 | phone                                                                    |
| exit_on_test_failure        | true                                                                     |
| reinstall_app               | false                                                                    |
| use_timestamp_suffix        | true                                                                     |
+-----------------------------+--------------------------------------------------------------------------+

[22:10:06]: Limiting the test classes run by `screengrab` to just those that generate screenshots can make runs faster.
[22:10:06]: Consider using the :use_tests_in_classes or :use_tests_in_packages option, and organize your tests accordingly.
[22:10:06]: Clearing phoneScreenshots within fastlane/metadata/android
[22:10:06]: $ /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell echo \$EXTERNAL_STORAGE
[22:10:06]: ▸ /sdcard
[22:10:06]: $ /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell echo \$ANDROID_DATA
[22:10:06]: ▸ /data
[22:10:06]: Cleaning screenshots on device
ls: /sdcard/com.myapp/screengrab/en-CA/images/screenshots: No such file or directory
[22:10:06]: Exit status: 1
ls: /sdcard/Android/data/com.myapp/files/screengrab/en-CA/images/screenshots: No such file or directory
[22:10:06]: Exit status: 1
ls: /data/user/0/com.myapp/files/com.myapp/screengrab/en-CA/images/screenshots: No such file or directory
[22:10:06]: Exit status: 1
ls: /data/data/com.myapp/files/com.myapp/screengrab/en-CA/images/screenshots: No such file or directory
[22:10:06]: Exit status: 1
ls: /data/data/com.myapp/app_screengrab/en-CA/images/screenshots: No such file or directory
[22:10:06]: Exit status: 1
ls: /data/data/com.myapp/screengrab/en-CA/images/screenshots: No such file or directory
[22:10:06]: Exit status: 1
[22:10:06]: $ /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop ro.build.version.sdk
[22:10:06]: ▸ 30
[22:10:06]: Installing app APK
[22:10:06]: $ /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -t -r android/app/build/outputs/apk/debug/app-debug.apk
[22:10:06]: ▸ Performing Streamed Install
[22:10:07]: ▸ Success
[22:10:07]: Installing tests APK
[22:10:07]: $ /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -t -r android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
[22:10:07]: ▸ Performing Streamed Install
[22:10:07]: ▸ Success
[22:10:07]: Granting the permission necessary to change locales on the device
[22:10:07]: $ /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm grant com.myapp android.permission.CHANGE_CONFIGURATION
[22:10:07]: Granting the permissions necessary to access device external storage
[22:10:07]: $ /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm grant com.myapp android.permission.WRITE_EXTERNAL_STORAGE
[22:10:08]: $ /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm grant com.myapp android.permission.READ_EXTERNAL_STORAGE
[22:10:08]: Enabling clean status bar
[22:10:08]: $ /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm grant com.myapp android.permission.DUMP
[22:10:08]: $ /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell settings put global sysui_demo_allowed 1
[22:10:08]: $ /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am force-stop com.myapp.test
[22:10:08]: $ /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am force-stop com.myapp
[22:10:08]: Running tests for locale: en-CA
[22:10:08]: $ /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am instrument --no-window-animation -w \
-e testLocale en-CA \
--no-hidden-api-checks \
-e appendTimestamp true \
com.myapp.test/androidx.test.runner.AndroidJUnitRunner
[22:10:48]: ▸ com.myapp.ScreenGrabInstrumentedTest:.
[22:10:48]: ▸ Time: 38.965
[22:10:48]: ▸ OK (1 test)
[22:10:49]: Pulling captured screenshots for locale en-CA from the device
[22:10:49]: $ /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell echo \$EXTERNAL_STORAGE
[22:10:49]: ▸ /sdcard
[22:10:49]: $ /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell echo \$ANDROID_DATA
[22:10:49]: ▸ /data
ls: /sdcard/com.myapp/screengrab/en-CA/images/screenshots: No such file or directory
[22:10:49]: Exit status: 1
ls: /sdcard/Android/data/com.myapp/files/screengrab/en-CA/images/screenshots: No such file or directory
[22:10:49]: Exit status: 1
ls: /data/user/0/com.myapp/files/com.myapp/screengrab/en-CA/images/screenshots: No such file or directory
[22:10:49]: Exit status: 1
ls: /data/data/com.myapp/files/com.myapp/screengrab/en-CA/images/screenshots: No such file or directory
[22:10:49]: Exit status: 1
ls: /data/data/com.myapp/app_screengrab/en-CA/images/screenshots: No such file or directory
[22:10:49]: Exit status: 1
ls: /data/data/com.myapp/screengrab/en-CA/images/screenshots: No such file or directory
[22:10:49]: Exit status: 1
[22:10:49]: Make sure you've used Screengrab.screenshot() in your tests and that your expected tests are being run.

[!] No screenshots were detected 📷❌</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 12.3.1                                                         |
| Ruby                        | 2.6.8                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.23.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 12.3.1 (21E258)                                          |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 13.0                                                           |
| Swift Version               | 5.5                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   | en_GB.UTF-8 | ✅ |
| LANGUAGE | en_GB.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

platform :android do
  project_dir = "android"

  desc "Create screenshots"
  lane :grab do
     gradle(
       task: 'clean',
       project_dir: project_dir
     )
     build_android_app(
       project_dir: project_dir,
       task: 'assemble',
       build_type: 'Debug'
     )
     build_android_app(
       project_dir: project_dir,
       task: 'assemble',
       build_type: 'AndroidTest'
     )
    screengrab()
  end
end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.205.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                             | Version | Update-Status |
| ---------------------------------- | ------- | ------------- |
| fastlane-plugin-versioning_android | 0.1.0   | ✅ Up-To-Date  |
| fastlane-plugin-load_json          | 0.0.1   | ✅ Up-To-Date  |
| fastlane-plugin-versioning         | 0.5.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                | Version      |
| ---------------------------------- | ------------ |
| did_you_mean                       | 1.3.0        |
| rouge                              | 2.0.7        |
| xcpretty                           | 0.3.0        |
| terminal-notifier                  | 2.0.0        |
| terminal-table                     | 1.8.0        |
| plist                              | 3.6.0        |
| public_suffix                      | 4.0.6        |
| addressable                        | 2.8.0        |
| multipart-post                     | 2.0.0        |
| word_wrap                          | 1.0.0        |
| optparse                           | 0.1.1        |
| tty-screen                         | 0.8.1        |
| tty-cursor                         | 0.7.1        |
| tty-spinner                        | 0.9.3        |
| artifactory                        | 3.0.15       |
| babosa                             | 1.0.4        |
| colored                            | 1.2          |
| highline                           | 2.0.3        |
| commander                          | 4.6.0        |
| faraday-cookie_jar                 | 0.0.7        |
| gh_inspector                       | 1.1.3        |
| mini_magick                        | 4.11.0       |
| naturally                          | 2.2.1        |
| security                           | 0.1.3        |
| xcpretty-travis-formatter          | 1.0.1        |
| dotenv                             | 2.7.6        |
| bundler                            | 2.2.11       |
| simctl                             | 1.6.8        |
| rexml                              | 3.2.5        |
| nanaimo                            | 0.3.0        |
| colored2                           | 3.1.2        |
| claide                             | 1.0.3        |
| CFPropertyList                     | 3.0.4        |
| atomos                             | 0.1.3        |
| xcodeproj                          | 1.21.0       |
| unicode-display_width              | 1.8.0        |
| excon                              | 0.88.0       |
| ruby2_keywords                     | 0.0.5        |
| faraday-rack                       | 1.0.0        |
| faraday-patron                     | 1.0.0        |
| faraday-net_http_persistent        | 1.2.0        |
| faraday-net_http                   | 1.0.1        |
| faraday-httpclient                 | 1.0.1        |
| faraday-excon                      | 1.1.0        |
| faraday-em_synchrony               | 1.0.0        |
| faraday-em_http                    | 1.0.0        |
| faraday                            | 1.8.0        |
| unf_ext                            | 0.0.8        |
| unf                                | 0.1.4        |
| domain_name                        | 0.5.20190701 |
| http-cookie                        | 1.0.4        |
| faraday_middleware                 | 1.2.0        |
| fastimage                          | 2.2.5        |
| json                               | 2.6.1        |
| rubyzip                            | 2.3.2        |
| jwt                                | 2.3.0        |
| webrick                            | 1.7.0        |
| httpclient                         | 2.8.3        |
| multi_json                         | 1.15.0       |
| signet                             | 0.16.0       |
| os                                 | 1.1.1        |
| memoist                            | 0.16.2       |
| googleauth                         | 1.1.0        |
| mini_mime                          | 1.1.2        |
| retriable                          | 3.1.2        |
| trailblazer-option                 | 0.1.1        |
| declarative                        | 0.0.20       |
| uber                               | 0.1.0        |
| representable                      | 3.1.1        |
| google-apis-core                   | 0.4.1        |
| google-apis-playcustomapp_v1       | 0.6.0        |
| google-apis-androidpublisher_v3    | 0.13.0       |
| rake                               | 13.0.6       |
| digest-crc                         | 0.6.4        |
| google-apis-storage_v1             | 0.9.0        |
| google-apis-iamcredentials_v1      | 0.8.0        |
| google-cloud-errors                | 1.2.0        |
| google-cloud-env                   | 1.5.0        |
| google-cloud-core                  | 1.6.0        |
| google-cloud-storage               | 1.34.1       |
| emoji_regex                        | 3.2.3        |
| aws-eventstream                    | 1.2.0        |
| aws-sigv4                          | 1.4.0        |
| aws-partitions                     | 1.525.0      |
| jmespath                           | 1.4.0        |
| aws-sdk-core                       | 3.122.0      |
| aws-sdk-kms                        | 1.51.0       |
| aws-sdk-s3                         | 1.105.0      |
| forwardable                        | 1.2.0        |
| logger                             | 1.3.0        |
| date                               | 2.0.0        |
| stringio                           | 0.0.2        |
| ipaddr                             | 1.2.2        |
| openssl                            | 2.1.2        |
| zlib                               | 1.0.0        |
| mutex_m                            | 0.1.0        |
| ostruct                            | 0.1.0        |
| strscan                            | 1.0.0        |
| io-console                         | 0.4.7        |
| fileutils                          | 1.1.0        |
| etc                                | 1.0.1        |
| libxml-ruby                        | 3.2.1        |
| psych                              | 3.1.0        |
| fastlane-plugin-versioning_android | 0.1.0        |
| fastlane-plugin-load_json          | 0.0.1        |
| fastlane-plugin-versioning         | 0.5.0        |
</details>

*generated on:* **2022-04-20**
</details></pre>
</details>

**Comment by benomatis** [comment]
note that downgrading to 2.186.0 did resolve the issue (taken from comment https://github.com/fastlane/fastlane/issues/19096#issuecomment-938411166 - that issue has been closed without a resolution), however, I prefer working off of the latest and greatest, if possible.

**Comment by Holthaus789** [comment]
you can check this : https://github.com/fastlane/fastlane/issues/13787

**Comment by benomatis** [comment]
> you can check this : https://github.com/fastlane/fastlane/issues/13787

I've already seen that one, but it has no solution, it's been closed unresolved, or am I missing something?
