### ISSUE TITLE
`zip` include not working

### ISSUE THREAD

**Issue by denandreychuk** [fastlane/fastlane#20219]
I want to create simple zip archive with just one file:

    zip(
      path: "./",
      output_path: "Framework.zip",
      include: ["LICENSE"]
    )

This action generate the following output:

> [02:56:24]: $ zip -r /Users/denandreychuk/Desktop/TestFramework/Framework.zip . -i ./LICENSE
> [02:56:25]: ▸ zip warning: zip file empty

However, if I just copy paste this command in terminal, I got the right non-empty zip:

> zip -r /Users/denandreychuk/Desktop/TestFramework/Framework.zip . -i ./LICENSE
>   adding: LICENSE (deflated 41%)

Am I doing something wrong or its a action bug?

**Comment by Hendershott** [comment]
You need to try the path of functions. php within the system and not its url. Do you have console access? If so just find out what directory is the file in and include it using the full path.

**Comment by Kukurijek** [comment]
Hi @denandreychuk !
Is it still not working for you?

Could you please post the output of `fastlane env`? 🙂 
I have tested it locally and it is working fine for me.

**Comment by denandreychuk** [comment]
@Kukurijek yeah, still not working. One possible workaround for this is to use absolute path, but for relative path i got the same output `zip warning: zip file empty`.

[fastlanenv.txt](https://github.com/fastlane/fastlane/files/8778533/fastlanenv.txt)
