### ISSUE TITLE
expire_previous_builds option doesn't seem to work

### ISSUE THREAD

**Issue by ab666** [fastlane/fastlane#20210]

**Comment by Gibbs465** [comment]
Facing same issue but no response from anyone and couldn't find this topic troubleshooting in google.

**Comment by CaseyCw1** [comment]
Thanks for sharing, I found a lot of interesting information here. A really good post, very thankful and helpful that you will write many more posts like this one.

**Comment by litebluetips** [comment]
Thanks for the update and quick reply. I'll be sure to keep an eye on this thread. Looking for the same issue. Bumped into your thread. Thanks for creating it. Looking forward for solution.
