### ISSUE TITLE
Could not find aab file at path '../app/build/outputs/bundle/release/app-release.aab'

### ISSUE THREAD

**Issue by lyqht** [fastlane/fastlane#20217]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

For the lanes, please refer to Details at the end of the issue. 

I have built an `.aab` by running

```
fastlane bundle
```

However, when I try to deploy to google play store **internal track** via

```
fastlane internal
```

I get the following error

```
+------+---------------------------------+-------------+
|                   fastlane summary                   |
+------+---------------------------------+-------------+
| Step | Action                          | Time (in s) |
+------+---------------------------------+-------------+
| 1    | default_platform                | 0           |
| 2    | google_play_track_version_codes | 1           |
+------+---------------------------------+-------------+

[16:11:36]: fastlane finished with errors

[!] Could not find aab file at path '../app/build/outputs/bundle/release/app-release.aab'
```

But I can find the file here

<img width="402" alt="image" src="https://user-images.githubusercontent.com/35736525/165254222-2aa82255-d795-47c4-b90d-a97b918b83f4.png">

### Environment

<details>
  <pre> 
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.6.4                                      |
| Ruby                        | 3.0.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.35.0                          |
| Installation Source         | ~/.rbenv/versions/3.0.0/bin/fastlane        |
| Host                        | macOS 11.6.4 (20G417)                       |
| Ruby Lib Dir                | ~/.rbenv/versions/3.0.0/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 13.2.1                                      |
| Swift Version               | 5.5.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Increment version code and add git tag"
  lane :vc_and_tag do |options|
    increment_version_code(
      gradle_file_path: "./app/build.gradle",
      version_code: options[:current_build_number]
    )

    add_git_tag(
      grouping: "builds",
      includes_lane: false,
      prefix: "android",
      build_number: options[:current_build_number],
      force: true,
    )
  end

  desc "Create a new app bundle for release"
  lane :bundle do
    gradle(task: 'clean')
    gradle(
      task: 'bundle',
      build_type: 'Release'
    )
  end

  desc "Submit a new bundle to Play Store: Internal Track"
  lane :internal do
    previous_build_number = google_play_track_version_codes(
      track: "internal",
    ).first

    current_build_number = previous_build_number + 1
    # vc_and_tag(current_build_number: current_build_number)
    # bundle()
    upload_to_play_store(track: 'internal', version_name: "#{current_build_number}", version_code: current_build_number, aab: "../app/build/outputs/bundle/release/app-release.aab")
  end


end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("key.json")
package_name("com.lyqht.billy")

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.205.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                 | Version | Update-Status |
| -------------------------------------- | ------- | ------------- |
| fastlane-plugin-increment_version_code | 0.4.3   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                    | Version      |
| -------------------------------------- | ------------ |
| did_you_mean                           | 1.5.0        |
| rouge                                  | 2.0.7        |
| xcpretty                               | 0.3.0        |
| terminal-notifier                      | 2.0.0        |
| unicode-display_width                  | 1.8.0        |
| terminal-table                         | 1.8.0        |
| plist                                  | 3.6.0        |
| addressable                            | 2.8.0        |
| multipart-post                         | 2.0.0        |
| word_wrap                              | 1.0.0        |
| optparse                               | 0.1.1        |
| tty-screen                             | 0.8.1        |
| tty-cursor                             | 0.7.1        |
| tty-spinner                            | 0.9.3        |
| artifactory                            | 3.0.15       |
| babosa                                 | 1.0.4        |
| colored                                | 1.2          |
| highline                               | 2.0.3        |
| commander                              | 4.6.0        |
| excon                                  | 0.92.2       |
| faraday-em_http                        | 1.0.0        |
| faraday-em_synchrony                   | 1.0.0        |
| faraday-excon                          | 1.1.0        |
| faraday-httpclient                     | 1.0.1        |
| faraday-multipart                      | 1.0.3        |
| faraday-net_http                       | 1.0.1        |
| faraday-net_http_persistent            | 1.2.0        |
| faraday-patron                         | 1.0.0        |
| faraday-rack                           | 1.0.0        |
| faraday-retry                          | 1.0.3        |
| faraday                                | 1.10.0       |
| unf                                    | 0.1.4        |
| domain_name                            | 0.5.20190701 |
| http-cookie                            | 1.0.4        |
| faraday-cookie_jar                     | 0.0.7        |
| faraday_middleware                     | 1.2.0        |
| fastimage                              | 2.2.6        |
| gh_inspector                           | 1.1.3        |
| mini_magick                            | 4.11.0       |
| naturally                              | 2.2.1        |
| rubyzip                                | 2.3.2        |
| security                               | 0.1.3        |
| xcpretty-travis-formatter              | 1.0.1        |
| dotenv                                 | 2.7.6        |
| bundler                                | 2.2.3        |
| simctl                                 | 1.6.8        |
| jwt                                    | 2.3.0        |
| uber                                   | 0.1.0        |
| declarative                            | 0.0.20       |
| trailblazer-option                     | 0.1.2        |
| representable                          | 3.1.1        |
| retriable                              | 3.1.2        |
| mini_mime                              | 1.1.2        |
| httpclient                             | 2.8.3        |
| webrick                                | 1.7.0        |
| google-apis-core                       | 0.4.2        |
| google-apis-playcustomapp_v1           | 0.7.0        |
| google-apis-androidpublisher_v3        | 0.19.0       |
| emoji_regex                            | 3.2.3        |
| aws-sdk-s3                             | 1.113.0      |
| tsort                                  | 0.1.0        |
| set                                    | 1.0.1        |
| uri                                    | 0.10.1       |
| rexml                                  | 3.2.5        |
| nanaimo                                | 0.3.0        |
| colored2                               | 3.1.2        |
| claide                                 | 1.1.0        |
| CFPropertyList                         | 3.0.5        |
| atomos                                 | 0.1.3        |
| xcodeproj                              | 1.21.0       |
| public_suffix                          | 4.0.7        |
| ruby2_keywords                         | 0.0.5        |
| unf_ext                                | 0.0.8.1      |
| json                                   | 2.6.1        |
| multi_json                             | 1.15.0       |
| signet                                 | 0.16.1       |
| os                                     | 1.1.4        |
| memoist                                | 0.16.2       |
| googleauth                             | 1.1.3        |
| rake                                   | 13.0.6       |
| digest-crc                             | 0.6.4        |
| google-apis-storage_v1                 | 0.13.0       |
| google-apis-iamcredentials_v1          | 0.10.0       |
| google-cloud-errors                    | 1.2.0        |
| google-cloud-env                       | 1.6.0        |
| google-cloud-core                      | 1.6.0        |
| google-cloud-storage                   | 1.36.2       |
| aws-eventstream                        | 1.2.0        |
| aws-sigv4                              | 1.5.0        |
| aws-partitions                         | 1.579.0      |
| jmespath                               | 1.6.1        |
| aws-sdk-core                           | 3.130.2      |
| aws-sdk-kms                            | 1.56.0       |
| forwardable                            | 1.3.2        |
| logger                                 | 1.4.3        |
| pathname                               | 0.1.0        |
| shellwords                             | 0.1.0        |
| cgi                                    | 0.2.0        |
| date                                   | 3.1.0        |
| timeout                                | 0.1.1        |
| stringio                               | 3.0.0        |
| securerandom                           | 0.1.0        |
| openssl                                | 2.2.0        |
| io-nonblock                            | 0.1.0        |
| ipaddr                                 | 1.2.2        |
| io-wait                                | 0.1.0        |
| zlib                                   | 1.1.0        |
| resolv                                 | 0.2.0        |
| digest                                 | 3.0.0        |
| time                                   | 0.1.0        |
| open-uri                               | 0.1.0        |
| mutex_m                                | 0.1.1        |
| net-protocol                           | 0.1.0        |
| net-smtp                               | 0.2.1        |
| ostruct                                | 0.3.1        |
| english                                | 0.7.1        |
| erb                                    | 2.2.0        |
| strscan                                | 3.0.0        |
| abbrev                                 | 0.1.0        |
| io-console                             | 0.5.6        |
| tempfile                               | 0.1.1        |
| delegate                               | 0.2.0        |
| fileutils                              | 1.5.0        |
| tmpdir                                 | 0.1.1        |
| base64                                 | 0.1.0        |
| singleton                              | 0.1.1        |
| open3                                  | 0.1.1        |
| nkf                                    | 0.1.0        |
| racc                                   | 1.5.1        |
| nokogiri                               | 1.11.7       |
| prettyprint                            | 0.1.0        |
| pp                                     | 0.1.0        |
| find                                   | 0.1.0        |
| yaml                                   | 0.1.1        |
| psych                                  | 3.3.0        |
| fastlane-plugin-increment_version_code | 0.4.3        |
</details>

*generated on:* **2022-04-26**
</details>
  </pre>
</details>

**Comment by geisterfurz007** [comment]
Try removing the first `.` from your path to get `./app/build/outputs/bundle/release/app-release.aab` for your aab. The path is not relative to the fastlane directory but to the directory you are in when running fastlane if I am not mistaken.

You will also notice in your Fastfile that in the lane `:vc_and_tag`, the gradle file is also only referenced with `./app` and not `../app`.

**Comment by lyqht** [comment]
Thank you @geisterfurz007 ! you're right.
