### ISSUE TITLE
fetch_access_token doesn't work in googleauth

### ISSUE THREAD

**Issue by asdf1stlwj** [fastlane/fastlane#20220]
I follow the steps on https://docs.fastlane.tools/actions/supply/#setup and then run the script fastlane run validate_play_store_json_key json_key:/path/to/your/downloaded/file.json, it gives an error

liwenjin@asdf1sts-Mac-mini zenggewifi % fastlane run validate_play_store_json_key json_key:GooglePlayJsonKey.json --verbose
[✔] 🚀 
[15:45:46]: fastlane detected a Gemfile in the current directory
[15:45:46]: However, it seems like you didn't use `bundle exec`
[15:45:46]: To launch fastlane faster, please use
[15:45:46]: 
[15:45:46]: $ bundle exec fastlane run validate_play_store_json_key json_key:GooglePlayJsonKey.json --verbose
[15:45:46]: 
[15:45:46]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2022-04-27 15:45:48.07]: Checking if there are any plugins that should be loaded...
DEBUG [2022-04-27 15:45:48.14]: Loading 'fastlane-plugin-android_versioning' plugin
INFO [2022-04-27 15:45:48.17]: gem 'fastlane-plugin-android_versioning' is already installed
DEBUG [2022-04-27 15:45:48.19]: Loading 'fastlane-plugin-fir_cli' plugin
INFO [2022-04-27 15:45:48.19]: gem 'fastlane-plugin-fir_cli' is already installed
/Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-fir_cli-2.0.12/lib/fastlane/plugin/fir_cli/helper/fir_cli_helper.rb:19: warning: already initialized constant FIR::VERSION
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.14/lib/fir/version.rb:4: warning: previous definition of VERSION was here
+------------------------+---------+------------------------+
|                       Used plugins                        |
+------------------------+---------+------------------------+
| Plugin                 | Version | Action                 |
+------------------------+---------+------------------------+
| fastlane-plugin-andro  | 0.5.5   | get_value_from_build,  |
| id_versioning          |         | increment_version_cod  |
|                        |         | e,                     |
|                        |         | set_value_in_build,    |
|                        |         | get_version_name,      |
|                        |         | increment_version_nam  |
|                        |         | e, get_version_code    |
| fastlane-plugin-fir_c  | 2.0.12  | fir_cli                |
| li                     |         |                        |
+------------------------+---------+------------------------+

Successfully loaded Appfile at path '/Users/liwenjin/Documents/Project/Android/zenggewifi/fastlane/Appfile'
- json_key_file: 'GooglePlayJsonKey.json'
- package_name: 'com.zengge.wifi'
-------
DEBUG [2022-04-27 15:45:49.48]: Using json_key: GooglePlayJsonKey.json
Successfully loaded Appfile at path '/Users/liwenjin/Documents/Project/Android/zenggewifi/fastlane/Appfile'
- json_key_file: 'GooglePlayJsonKey.json'
- package_name: 'com.zengge.wifi'
-------
Successfully loaded Appfile at path '/Users/liwenjin/Documents/Project/Android/zenggewifi/fastlane/Appfile'
- json_key_file: 'GooglePlayJsonKey.json'
- package_name: 'com.zengge.wifi'
-------
Successfully loaded Appfile at path '/Users/liwenjin/Documents/Project/Android/zenggewifi/fastlane/Appfile'
- json_key_file: 'GooglePlayJsonKey.json'
- package_name: 'com.zengge.wifi'
-------
Successfully loaded Appfile at path '/Users/liwenjin/Documents/Project/Android/zenggewifi/fastlane/Appfile'
- json_key_file: 'GooglePlayJsonKey.json'
- package_name: 'com.zengge.wifi'
-------
INFO [2022-04-27 15:45:49.49]: ------------------------------------------
INFO [2022-04-27 15:45:49.49]: --- Step: validate_play_store_json_key ---
INFO [2022-04-27 15:45:49.49]: ------------------------------------------

+-----------------+------------------------+
| Summary for validate_play_store_json_key |
+-----------------+------------------------+
| json_key        | GooglePlayJsonKey.json |
| timeout         | 300                    |
+-----------------+------------------------+

DEBUG [2022-04-27 15:45:49.49]: Fetching a new access token from Google...
ERROR [2022-04-27 15:51:54.02]: Could not establish a connection to Google Play Store with this json key file.
ERROR [2022-04-27 15:51:54.02]: Unexpected error: #<Faraday::ConnectionFailed wrapped=#<Net::OpenTimeout: execution expired>>
/Library/Ruby/Gems/2.6.0/gems/googleauth-1.1.1/lib/googleauth/signet.rb:112:in `rescue in retry_with_error'
/Library/Ruby/Gems/2.6.0/gems/googleauth-1.1.1/lib/googleauth/signet.rb:101:in `retry_with_error'
/Library/Ruby/Gems/2.6.0/gems/googleauth-1.1.1/lib/googleauth/signet.rb:74:in `fetch_access_token!'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/supply/lib/supply/client.rb:53:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/supply/lib/supply/client.rb:19:in `new'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/supply/lib/supply/client.rb:19:in `make_from_config'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/actions/validate_play_store_json_key.rb:14:in `run'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/runner.rb:229:in `chdir'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/one_off.rb:42:in `run'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/one_off.rb:22:in `execute'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/commands_generator.rb:226:in `block (2 levels) in run'
/Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
/Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
/Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
/Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.205.2/bin/fastlane:23:in `<top (required)>'
/usr/local/bin/fastlane:23:in `load'
/usr/local/bin/fastlane:23:in `<main>'
INFO [2022-04-27 15:51:54.02]: Result: true
DEBUG [2022-04-27 15:51:54.02]: All plugins are up to date

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 12.0.1                                                         |
| Ruby                        | 2.6.8                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.32.0 (Apple Git-132)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 12.0.1 (21A559)                                          |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 13.2.1                                                         |
| Swift Version               | 5.5.2                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>No Fastfile found</summary>
</details>

<details><summary>No Appfile found</summary>
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.205.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                             | Version | Update-Status |
| ---------------------------------- | ------- | ------------- |
| fastlane-plugin-android_versioning | 0.5.5   | ✅ Up-To-Date  |
| fastlane-plugin-fir_cli            | 2.0.12  | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                | Version      |
| ---------------------------------- | ------------ |
| did_you_mean                       | 1.5.0        |
| atomos                             | 0.1.3        |
| colored2                           | 3.1.2        |
| nanaimo                            | 0.3.0        |
| rexml                              | 3.2.5        |
| xcodeproj                          | 1.21.0       |
| rouge                              | 2.0.7        |
| xcpretty                           | 0.3.0        |
| terminal-notifier                  | 2.0.0        |
| unicode-display_width              | 1.8.0        |
| terminal-table                     | 1.8.0        |
| plist                              | 3.6.0        |
| addressable                        | 2.8.0        |
| multipart-post                     | 2.0.0        |
| word_wrap                          | 1.0.0        |
| optparse                           | 0.1.1        |
| tty-screen                         | 0.8.1        |
| tty-cursor                         | 0.7.1        |
| tty-spinner                        | 0.9.3        |
| artifactory                        | 3.0.15       |
| babosa                             | 1.0.4        |
| colored                            | 1.2          |
| highline                           | 2.0.3        |
| commander                          | 4.6.0        |
| unf                                | 0.1.4        |
| domain_name                        | 0.5.20190701 |
| http-cookie                        | 1.0.4        |
| faraday-cookie_jar                 | 0.0.7        |
| faraday-em_http                    | 1.0.0        |
| faraday-em_synchrony               | 1.0.0        |
| faraday-excon                      | 1.1.0        |
| faraday-httpclient                 | 1.0.1        |
| faraday-multipart                  | 1.0.3        |
| faraday-net_http                   | 1.0.1        |
| faraday-net_http_persistent        | 1.2.0        |
| faraday-patron                     | 1.0.0        |
| faraday-rack                       | 1.0.0        |
| faraday-retry                      | 1.0.3        |
| ruby2_keywords                     | 0.0.5        |
| faraday                            | 1.10.0       |
| faraday_middleware                 | 1.2.0        |
| fastimage                          | 2.2.6        |
| gh_inspector                       | 1.1.3        |
| mini_magick                        | 4.11.0       |
| naturally                          | 2.2.1        |
| rubyzip                            | 2.3.2        |
| security                           | 0.1.3        |
| xcpretty-travis-formatter          | 1.0.1        |
| dotenv                             | 2.7.6        |
| bundler                            | 2.2.18       |
| simctl                             | 1.6.8        |
| jwt                                | 2.3.0        |
| uber                               | 0.1.0        |
| declarative                        | 0.0.20       |
| trailblazer-option                 | 0.1.2        |
| representable                      | 3.1.1        |
| retriable                          | 3.1.2        |
| mini_mime                          | 1.1.2        |
| memoist                            | 0.16.2       |
| multi_json                         | 1.15.0       |
| os                                 | 1.1.4        |
| signet                             | 0.16.1       |
| googleauth                         | 1.1.1        |
| httpclient                         | 2.8.3        |
| google-apis-core                   | 0.4.2        |
| google-apis-playcustomapp_v1       | 0.7.0        |
| emoji_regex                        | 3.2.3        |
| aws-sdk-s3                         | 1.113.0      |
| CFPropertyList                     | 3.0.5        |
| claide                             | 1.1.0        |
| public_suffix                      | 4.0.7        |
| excon                              | 0.92.2       |
| unf_ext                            | 0.0.8.1      |
| json                               | 2.6.1        |
| webrick                            | 1.7.0        |
| google-apis-androidpublisher_v3    | 0.19.0       |
| rake                               | 13.0.6       |
| digest-crc                         | 0.6.4        |
| google-apis-storage_v1             | 0.13.0       |
| google-apis-iamcredentials_v1      | 0.10.0       |
| google-cloud-errors                | 1.2.0        |
| google-cloud-env                   | 1.6.0        |
| google-cloud-core                  | 1.6.0        |
| google-cloud-storage               | 1.36.2       |
| aws-eventstream                    | 1.2.0        |
| aws-sigv4                          | 1.5.0        |
| aws-partitions                     | 1.579.0      |
| jmespath                           | 1.6.1        |
| aws-sdk-core                       | 3.130.1      |
| aws-sdk-kms                        | 1.56.0       |
| forwardable                        | 1.3.2        |
| logger                             | 1.4.3        |
| date                               | 2.0.0        |
| stringio                           | 0.0.2        |
| ipaddr                             | 1.2.2        |
| openssl                            | 2.1.2        |
| zlib                               | 1.0.0        |
| mutex_m                            | 0.1.1        |
| ostruct                            | 0.3.3        |
| strscan                            | 1.0.0        |
| io-console                         | 0.4.7        |
| fileutils                          | 1.5.0        |
| libxml-ruby                        | 3.2.1        |
| psych                              | 3.1.0        |
| fastlane-plugin-android_versioning | 0.5.5        |
| http-accept                        | 1.7.0        |
| mime-types-data                    | 3.2022.0105  |
| mime-types                         | 3.4.1        |
| netrc                              | 0.11.0       |
| rest-client                        | 2.1.0        |
| api_tools                          | 0.1.1        |
| thor                               | 0.20.3       |
| admqr_knife                        | 0.1.5        |
| ruby_android_apk                   | 0.7.7.1      |
| chunky_png                         | 1.4.0        |
| rqrcode                            | 0.10.1       |
| fir-cli                            | 2.0.14       |
| fastlane-plugin-fir_cli            | 2.0.12       |
</details>

*generated on:* **2022-04-27**
</details>

And I found that I didn't configure OAuth Clients under Api aceess page, will this make any difference?
![截屏2022-04-27 下午4 22 46](https://user-images.githubusercontent.com/29203192/165475409-eb86c6c5-d77c-463a-a2c1-ca5c9a877226.png)

**Comment by Erin69** [comment]
When attempting to get an access or refresh token, you will get an "Invalid client" error if you provide an incorrect OAuth 2.0 Client Secret.

**Comment by asdf1stlwj** [comment]
> When attempting to get an access or refresh token, you will get an "Invalid client" error if you provide an incorrect OAuth 2.0 Client Secret.

but i am sure that i have provide an correct OAuth 2.0 Client Secret and my case is not "Invalid client",it seems i can't visit google api with time out error
