### ISSUE TITLE
match nuke doesn't remove additional_cert_types: mac_installer_distribution 

### ISSUE THREAD

**Issue by mrcperello** [fastlane/fastlane#20225]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When recreating certificates, we followed these steps:
1. nuke develop & nuke distribution
2. run match with force: true to recreate all profiles and create new certificates
3. we discovered that nuke didn't remove the additional_cert_types: mac_installer_distribution, as a work around we removed it from the repository manually, and when re-running match it was successfully created.

##### Command executed

```
fastlane match nuke develop
fastlane match nuke distribution
fastlane match --force
```

**Comment by Gibbs465** [comment]
I was trying this out and got some issues and still finding it can you give some more suggestions if any thanks in advance.
