### ISSUE TITLE
Fastlane command:

### ISSUE THREAD

**Issue by anastasiaShpakava** [fastlane/fastlane#20244]
Fastlane command: (bundle "_1.16.2_" "exec" "fastlane" "android" "<brunch>" "app:<name>") failed
If you want to send an issue report to fastlane (https://github.com/fastlane/fastlane/issues/new), you can find the output of fastlane env in the following log file:
/Users/vagrant/deploy/fastlane_env.log
Command failed, error: exit status 1
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | fastlane@3 (exit code: 1)                                     | 2.7 min  |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-fastlane/issues           |
| Source: https://github.com/bitrise-io/steps-fastlane                         |
+---+---------------------------------------------------------------+----------+
                                          ▼

**Comment by Ryan42000** [comment]
> It seems like you have not included the output of `fastlane env` To make it easier for us help you resolve this issue, please update the issue to include the output of `fastlane env` 👍

I was facing the same kind of question, Thank you for sharing the suggestion, I will try to figure it out for more.

**Comment by lacostej** [comment]
@anastasiaShpakava there doesn't seem to be anything in the bug report that points to a fastlane bug. Closing for now.
