### ISSUE TITLE
Increment build number is not being updated in the xcode project

### ISSUE THREAD

**Issue by MuhammadAliYousaf** [fastlane/fastlane#20242]
I included following line in Fastfile. 
increment_build_number(xcodeproj: "JustLearn.xcodeproj")

Build number is successfully updated before the creation of ipa file. But updated build number is not being saved in the project.
For example, if build number in the project is 10, build is created with build number 11 but xcode project's build number remains 10. Due to this issue, every time I have to update build number in the code after a successful release.

Any solution for that?

**Comment by MuhammadAliYousaf** [comment]
Please see following,

[20:22:25]: ▸ Setting version of project JustLearn to:
[20:22:25]: ▸ 3.
[20:22:25]: ▸ Also setting CFBundleVersion key (assuming it exists)
[20:22:25]: ▸ Updating CFBundleVersion in Info.plist(s)...
[20:22:25]: ▸ Updated CFBundleVersion in "JustLearn.xcodeproj/../JustLearn/Info.plist" to 3
[20:22:25]: ▸ Cannot find "JustLearn.xcodeproj/../YES"

Looks like info.plist file path is incorrect, can you please help me how to fix this by setting path of info.plist?

**Comment by SamuelS1c** [comment]
Great article! I realized these are my favorite kinds of GI articles. Enough news and reviews, more stuff like this! Let the writers get creative!

**Comment by marcpalmer** [comment]
> Please see following,
> 
> [20:22:25]: ▸ Setting version of project JustLearn to: [20:22:25]: ▸ 3. [20:22:25]: ▸ Also setting CFBundleVersion key (assuming it exists) [20:22:25]: ▸ Updating CFBundleVersion in Info.plist(s)... [20:22:25]: ▸ Updated CFBundleVersion in "JustLearn.xcodeproj/../JustLearn/Info.plist" to 3 [20:22:25]: ▸ Cannot find "JustLearn.xcodeproj/../YES"
> 
> Looks like info.plist file path is incorrect, can you please help me how to fix this by setting path of info.plist?

I'm also seeing this issue, with the strange output `▸ Cannot find "<ProjectName>/../YES"` <--- what is the YES thing about? This seems like a bug?

**Comment by aserdobintsev** [comment]
Note: This issue is caused by **agvtool** and the **GENERATE_INFOPLIST_FILE** setting. 
Remove **GENERATE_INFOPLIST_FILE** in your project’s Build Settings.
See the discussion for details: https://github.com/fastlane/fastlane/discussions/20062
