### ISSUE TITLE
Deliver:submit without review, just select build

### ISSUE THREAD

**Issue by pke** [fastlane/fastlane#20243]
Could a new option `review=true` be added to options that prepares the build for submission but not actually submits its yet?

https://github.com/fastlane/fastlane/blob/eb4584e0394c1fecccd70d4313260f4707f2af80/deliver/lib/deliver/submit_for_review.rb#L26

would have to be changed to
`create_review_submission(options, app, version, platform) unless false == options[:review]`

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 12.2.1                                      |
| Ruby                        | 3.1.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.32.0 (Apple Git-132)          |
| Installation Source         | ~/.gem/bin/fastlane                         |
| Host                        | macOS 12.2.1 (21D62)                        |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.1.1/lib         |
| OpenSSL Version             | OpenSSL 1.1.1m  14 Dec 2021                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 13.3.1                                      |
| Swift Version               | 5.6                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.205.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                      | Version | Update-Status |
| --------------------------- | ------- | ------------- |
| fastlane-plugin-badge       | 1.5.0   | ✅ Up-To-Date  |
| fastlane-plugin-rocket_chat | 0.1.1   | ✅ Up-To-Date  |
| fastlane-plugin-load_json   | 0.0.1   | ✅ Up-To-Date  |
| fastlane-plugin-changelog   | 0.16.0  | ✅ Up-To-Date  |
| fastlane-plugin-versioning  | 0.5.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| bundler                         | 2.3.9        |
| pathname                        | 0.2.0        |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| concurrent-ruby                 | 1.1.9        |
| i18n                            | 1.10.0       |
| minitest                        | 5.15.0       |
| tzinfo                          | 2.0.4        |
| zeitwerk                        | 2.5.4        |
| activesupport                   | 6.1.5        |
| public_suffix                   | 4.0.7        |
| addressable                     | 2.8.0        |
| httpclient                      | 2.8.3        |
| json                            | 2.6.1        |
| algoliasearch                   | 1.27.5       |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.583.0      |
| aws-sigv4                       | 1.5.0        |
| jmespath                        | 1.6.1        |
| aws-sdk-core                    | 3.130.2      |
| aws-sdk-kms                     | 1.56.0       |
| aws-sdk-s3                      | 1.114.0      |
| babosa                          | 1.0.4        |
| fastimage                       | 2.2.6        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.92.3       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.0.0        |
| faraday-multipart               | 1.0.3        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.0       |
| unf_ext                         | 0.0.8.1      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.3.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.1       |
| googleauth                      | 1.1.3        |
| mini_mime                       | 1.1.2        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.2        |
| google-apis-androidpublisher_v3 | 0.19.0       |
| google-apis-playcustomapp_v1    | 0.7.0        |
| digest-crc                      | 0.6.4        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.13.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.36.2       |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| badge                           | 0.13.0       |
| fuzzy_match                     | 2.0.4        |
| nap                             | 1.1.0        |
| netrc                           | 0.11.0       |
| ffi                             | 1.15.5       |
| ethon                           | 0.15.0       |
| typhoeus                        | 1.4.0        |
| cocoapods-core                  | 1.11.3       |
| cocoapods-deintegrate           | 1.0.5        |
| cocoapods-downloader            | 1.5.1        |
| cocoapods-plugins               | 1.0.0        |
| cocoapods-search                | 1.0.1        |
| cocoapods-trunk                 | 1.6.0        |
| cocoapods-try                   | 1.2.0        |
| escape                          | 0.0.4        |
| fourflusher                     | 2.3.1        |
| molinillo                       | 0.8.0        |
| ruby-macho                      | 2.5.1        |
| cocoapods                       | 1.11.3       |
| fastlane-plugin-badge           | 1.5.0        |
| fastlane-plugin-changelog       | 0.16.0       |
| fastlane-plugin-load_json       | 0.0.1        |
| rocket-chat-notifier            | 0.1.0        |
| fastlane-plugin-rocket_chat     | 0.1.1        |
| fastlane-plugin-versioning      | 0.5.0        |
</details>

*generated on:* **2022-05-05**
</details>

**Comment by Holthaus789** [comment]
check this out : https://developer.apple.com/forums/thread/70031

**Comment by pke** [comment]
> check this out : https://developer.apple.com/forums/thread/70031

How is this related to my feature request?
