### ISSUE TITLE
Produce - 2.205.2 - Sending language name deprecated

### ISSUE THREAD

**Issue by dev-danries** [fastlane/fastlane#20252]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When trying to create a new app in App Store Connect it errors out and shows a deprecation message for name.

##### Command executed
fastlane init

##### Complete output when running fastlane, including the stack trace and command used
[08:53:01]: Would you like fastlane to create the App on App Store Connect for you? (y/n)
y

+----------------+----------------------+
|      Summary for produce 2.205.2      |
+----------------+----------------------+
| platform       | ios                  |
| skip_devcenter | true                 |
| language       | English              |
| skip_itc       | false                |
+----------------+----------------------+

[08:53:12]: App Name: XxXxxxx
[08:53:18]: Creating new app 'XxXxxxx' on App Store Connect
[08:53:18]: Sending language name is deprecated. 'English' has been mapped to 'en-US'.
[08:53:18]: Please enter one of available languages: ["ar-SA", "ca", "cs", "da", "de-DE", "el", "en-AU", "en-CA", "en-GB", "en-US", "es-ES", "es-MX", "fi", "fr-CA", "fr-FR", "he", "hi", "hr", "hu", "id", "it", "ja", "ko", "ms", "nl-NL", "no", "pl", "pt-BR", "pt-PT", "ro", "ru", "sk", "sv", "th", "tr", "uk", "vi", "zh-Hans", "zh-Hant"]
[08:53:20]:
[08:53:20]: It looks like something went wrong when we tried to create your app on the Apple Developer Portal
[08:53:20]: Would you like to try again (y)? If you enter (n), fastlane will fall back to the manual setup (y/n)

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 12.3.1                                      |
| Ruby                        | 3.1.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.32.0 (Apple Git-132)          |
| Installation Source         | ~/.rbenv/versions/3.1.1/bin/fastlane        |
| Host                        | macOS 12.3.1 (21E258)                       |
| Ruby Lib Dir                | ~/.rbenv/versions/3.1.1/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 13.3.1                                      |
| Swift Version               | 5.6                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

```

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.205.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| bundler                         | 2.3.9        |
| pathname                        | 0.2.0        |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| public_suffix                   | 4.0.7        |
| addressable                     | 2.8.0        |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.586.0      |
| aws-sigv4                       | 1.5.0        |
| jmespath                        | 1.6.1        |
| aws-sdk-core                    | 3.130.2      |
| aws-sdk-kms                     | 1.56.0       |
| aws-sdk-s3                      | 1.114.0      |
| babosa                          | 1.0.4        |
| claide                          | 1.1.0        |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.8.1      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.92.3       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.0.0        |
| faraday-multipart               | 1.0.3        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.0       |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.3.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.1       |
| googleauth                      | 1.1.3        |
| httpclient                      | 2.8.3        |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.2        |
| google-apis-androidpublisher_v3 | 0.20.0       |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.13.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.36.2       |
| json                            | 2.6.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
</details>

*generated on:* **2022-05-09**
</details>

**Comment by Erin69** [comment]
You have created and configured a Rule to send an email to Developer Organization members that are associated with an application that is subscribed to a Plan in a Product, that the Product is deprecated.

**Comment by Nebel69** [comment]
> You have created and configured a Rule to send an email to Developer Organization members that are associated with an application that is subscribed to a Plan in a Product, that the Product is deprecated.

Thanks for the information, I will try to figure it out for more.
[My Merrill Lynch](https://www.mymerrill.me/)

**Comment by humblehacker** [comment]
I've received the same error. Re-running with `--verbose` didn't reveal anything I could use, so I modified the code to dump the response and saw this:

```
INFO [2022-05-31 10:49:56.38]: ✅  Your app '████████' is available in your Apple Developer Portal
INFO [2022-05-31 10:49:56.38]: Checking if the app '████████' exists on App Store Connect...
ERROR [2022-05-31 10:49:57.58]: Looks like the app '████████' isn't available on App Store Connect
ERROR [2022-05-31 10:49:57.58]: for the team ID '████████' on Apple ID '████████'
 [2022-05-31 10:49:57.58]: Would you like fastlane to create the App on App Store Connect for you?
(y/n)
y

+----------------+-----------------------+
|      Summary for produce 2.206.2       |
+----------------+-----------------------+
| username       | ████████              |
| team_id        | ████████              |
| itc_team_id    | ████████              |
| platform       | ios                   |
| app_identifier | ████████              |
| skip_devcenter | true                  |
| sku            | ████████              |
| language       | English               |
| skip_itc       | false                 |
+----------------+-----------------------+

Reading keychain entry, because either user or password were empty
Loading session from '/Users/david/.fastlane/spaceship/████████/cookie'
Looking for App Store Connect Team with ID ████████
status = 200
body = {"data"=>[], "links"=>{"self"=>"https://appstoreconnect.apple.com/iris/v1/apps?include=appStoreVersions%2Cprices&filter%5BbundleId%5D=████████"}, "meta"=>{"paging"=>{"total"=>0, "limit"=>50}}}
response = #<Faraday::Response:0x0000000106a63680>
 [2022-05-31 10:50:03.27]: App Name: ████████
INFO [2022-05-31 10:50:09.68]: Creating new app '████████' on App Store Connect
ERROR [2022-05-31 10:50:09.68]: Sending language name is deprecated. 'English' has been mapped to 'en-US'.
ERROR [2022-05-31 10:50:09.68]: Please enter one of available languages: ["ar-SA", "ca", "cs", "da", "de-DE", "el", "en-AU", "en-CA", "en-GB", "en-US", "es-ES", "es-MX", "fi", "fr-CA", "fr-FR", "he", "hi", "hr", "hu", "id", "it", "ja", "ko", "ms", "nl-NL", "no", "pl", "pt-BR", "pt-PT", "ro", "ru", "sk", "sv", "th", "tr", "uk", "vi", "zh-Hans", "zh-Hant"]
status = 409
body = {"errors"=>[{"id"=>"b315cbe5-49c0-4008-b482-304763717ca9", "status"=>"409", "code"=>"ENTITY_ERROR.ATTRIBUTE.INVALID.DUPLICATE.DIFFERENT_ACCOUNT", "title"=>"The provided entity includes an attribute with a value that has already been used on a different account.", "detail"=>"The App Name you entered is already being used. If you have trademark rights to this name and would like it released for your use, submit a claim.", "source"=>{"pointer"=>"/included/1/name"}}]}
```

Seems like error response body parsing may be broken. In my quick scan of `handle_response` and `format_errors` I didn't notice anything obviously wrong. Hopefully someone with more experience in this area can find the problem. 🙏

**Comment by piscespieces** [comment]
Same problem

**Comment by AppleDev879** [comment]
Also having this issue

**Comment by danieldt232** [comment]
Im my case I tried to use a name that already exists..
Trying with a different `App Name` worked

**Comment by AppleDev879** [comment]
After trying to have Fastlane create the app in App Store Connect and it failed, I just made the app manually on the App Store Connect website and then Fastlane was able to see it.

**Comment by tkausch** [comment]
Same error for me but the process of creating app is finished as default "en-US" is taken.
