### ISSUE TITLE
http_command.rb:229:in `check_status': [!] Invalid request (Google::Apis::ClientError)

### ISSUE THREAD

**Issue by DoronK** [fastlane/fastlane#20298]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Fastlane supply crashes when trying to upload metadata.

##### Command executed
Fastlane supply(track: 'internal',
                               skip_upload_aab: false,
                               skip_upload_metadata: true,
                               metadata_path: "fastlane/#{options[:app_name]}/metadata",
                               skip_upload_changelogs: false,
                               skip_upload_images: true,
                               skip_upload_screenshots: true,
                               aab: path) 

##### Complete output when running fastlane, including the stack trace and command used
[09:29:05]: --- Step: supply ---
[09:29:05]: --------------------

+------------------------------------+-----------------------------------------------------------------------------+
|                                            Summary for supply 2.206.0                                            |
+------------------------------------+-----------------------------------------------------------------------------+
| track                              | internal                                                                    |
| skip_upload_aab                    | false                                                                       |
| skip_upload_metadata               | true                                                                        |
| metadata_path                      | fastlane/prep/metadata                                                      |
| skip_upload_changelogs             | false                                                                       |
| skip_upload_images                 | true                                                                        |
| skip_upload_screenshots            | true                                                                        |
| aab                                | app/prep/build/outputs/bundle/productionRelease/prep-production-release.aab |
| package_name                       | com.chegg.prep                                                              |
| release_status                     | completed                                                                   |
| json_key                           | serviceAccount.json                                                         |
| skip_upload_apk                    | false                                                                       |
| track_promote_release_status       | completed                                                                   |
| validate_only                      | false                                                                       |
| check_superseded_tracks            | false                                                                       |
| timeout                            | 300                                                                         |
| deactivate_on_promote              | true                                                                        |
| changes_not_sent_for_review        | false                                                                       |
| rescue_changes_not_sent_for_review | true                                                                        |
| ack_bundle_installation_warning    | false                                                                       |
+------------------------------------+-----------------------------------------------------------------------------+

[09:29:06]: Preparing aab at path 'app/prep/build/outputs/bundle/productionRelease/prep-production-release.aab' for upload...
[09:29:34]: Updating track 'internal'...
[09:29:35]: Preparing to upload for language 'android'...
+------------------+------------------+
|            Lane Context             |
+------------------+------------------+
| ENVIRONMENT      | prep             |
| DEFAULT_PLATFORM | android          |
| PLATFORM_NAME    | android          |
| LANE_NAME        | android internal |
+------------------+------------------+
[09:29:36]: Invalid request

+------+------------------------------------------+-------------+
|                       fastlane summary                        |
+------+------------------------------------------+-------------+
| Step | Action                                   | Time (in s) |
+------+------------------------------------------+-------------+
| 1    | default_platform                         | 0           |
| 2    | Switch to android checkIfFileExists lane | 0           |
| 💥   | supply                                   | 30          |
+------+------------------------------------------+-------------+

[09:29:36]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Authentication credentials are missing or invalid.
    https://github.com/fastlane/fastlane/issues/20270 [open] 30 💬
    5 days ago

➡️  Cookie generated via spaceauth is different when old one hasn't expired
    https://github.com/fastlane/fastlane/issues/20208 [open] 3 💬
    3 weeks ago

➡️  Only show 'invalid request' with no more error output
    https://github.com/fastlane/fastlane/issues/20057 [closed] 4 💬
    2 weeks ago

and 464 more at: https://github.com/fastlane/fastlane/search?q=Invalid%20request&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Library/Ruby/Gems/2.6.0/gems/google-apis-core-0.4.2/lib/google/apis/core/http_command.rb:229:in `check_status': [!] Invalid request (Google::Apis::ClientError)
        from /Library/Ruby/Gems/2.6.0/gems/google-apis-core-0.4.2/lib/google/apis/core/api_command.rb:134:in `check_status'
        from /Library/Ruby/Gems/2.6.0/gems/google-apis-core-0.4.2/lib/google/apis/core/http_command.rb:195:in `process_response'
        from /Library/Ruby/Gems/2.6.0/gems/google-apis-core-0.4.2/lib/google/apis/core/http_command.rb:311:in `execute_once'
        from /Library/Ruby/Gems/2.6.0/gems/google-apis-core-0.4.2/lib/google/apis/core/http_command.rb:114:in `block (2 levels) in execute'
        from /Library/Ruby/Gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
        from /Library/Ruby/Gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
        from /Library/Ruby/Gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
        from /Library/Ruby/Gems/2.6.0/gems/google-apis-core-0.4.2/lib/google/apis/core/http_command.rb:111:in `block in execute'
        from /Library/Ruby/Gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
        from /Library/Ruby/Gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
        from /Library/Ruby/Gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
        from /Library/Ruby/Gems/2.6.0/gems/google-apis-core-0.4.2/lib/google/apis/core/http_command.rb:102:in `execute'
        from /Library/Ruby/Gems/2.6.0/gems/google-apis-core-0.4.2/lib/google/apis/core/base_service.rb:377:in `execute_or_queue_command'
        from /Library/Ruby/Gems/2.6.0/gems/google-apis-androidpublisher_v3-0.20.0/lib/google/apis/androidpublisher_v3/service.rb:1175:in `get_edit_listing'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.0/supply/lib/supply/client.rb:231:in `listing_for_language'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.0/supply/lib/supply/uploader.rb:96:in `block (2 levels) in perform_upload_meta'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.0/supply/lib/supply/uploader.rb:92:in `each'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.0/supply/lib/supply/uploader.rb:92:in `block in perform_upload_meta'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.0/supply/lib/supply/uploader.rb:84:in `each'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.0/supply/lib/supply/uploader.rb:84:in `perform_upload_meta'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.0/supply/lib/supply/uploader.rb:35:in `perform_upload'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.0/fastlane/lib/fastlane/actions/upload_to_play_store.rb:33:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        from Fastfile:87:in `block (2 levels) in parsing_binding'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
        from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.0/bin/fastlane:23:in `<top (required)>'
        from /usr/local/bin/fastlane:23:in `load'
        from /usr/local/bin/fastlane:23:in `<main>'

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.206.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| atomos                          | 0.1.3        |
| CFPropertyList                  | 2.3.6        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| rexml                           | 3.2.5        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.7        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.92.3       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.3        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.0       |
| unf_ext                         | 0.0.8.1      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.1.0        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.1       |
| googleauth                      | 1.1.3        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.4.4        |
| google-apis-core                | 0.4.2        |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-androidpublisher_v3 | 0.20.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.13.0       |
| rake                            | 12.3.3       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.36.2       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.6.1        |
| aws-partitions                  | 1.587.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.0        |
| aws-sdk-core                    | 3.130.2      |
| aws-sdk-kms                     | 1.56.0       |
| aws-sdk-s3                      | 1.114.0      |
| bundler                         | 2.3.13       |
| forwardable                     | 1.2.0        |
| logger                          | 1.3.0        |
| date                            | 2.0.0        |
| stringio                        | 0.0.2        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.0.0        |
| mutex_m                         | 0.1.0        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| io-console                      | 0.4.7        |
| fileutils                       | 1.1.0        |
| etc                             | 1.0.1        |
| libxml-ruby                     | 3.2.1        |
| psych                           | 3.1.0        |
</details>

<details>
  There was an issue before that has been closed automatically.
  https://github.com/fastlane/fastlane/issues/18895
</details>

**Comment by lacostej** [comment]
In issue #18895 it seems like the issue is caused by supply is failing when used with non existing tracks. Has your project an  active `internal` track? No error on the Google Play console related to that track?

**Comment by bartekpacia** [comment]
I second @lacostej – this happens most probably because the track for which you're trying to get version code doesn't exist.

I think it's a bug and `google_play_track_version_codes` should return `0` for the non-existent track, not throw an error. Such poor DX.

See [this comment](https://github.com/fastlane/fastlane/issues/18895#issuecomment-944243782).
