### ISSUE TITLE
Wrong upload_to_testflight teams available for account specified

### ISSUE THREAD

**Issue by liudasbar** [fastlane/fastlane#20322]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
``upload_to_testflight`` via CI/CD TestFlight distribution pipeline detects wrong Apple ID account available teams (not the Apple ID account itself) even though all CI/CD environment variables are set accordingly to correct account / team details.

**But there is one twist** - before everything, I ran ``fastlane spaceauth -u wrong-account@account.com`` with wrong account set (_by the way, it has its own teams that I don't need for now_), updated ``FASTLANE_SESSION`` CI/CD variable and ran the TestFlight distribution pipeline. It failed, I noticed that it is wrong account. After that, I ran ``fastlane spaceauth -u correct-account@account.com`` with a correct account, updated the variable, and re-ran the pipeline.

❗️The issue is that it still searches for team within the previous account, not the new correct one, even though it displays correct account in line ``Login to App Store Connect (correct-account@account.com)`` and correct team ID in line ``Could not set team ID to 'Good team ID', only found the following available teams``. How I know it shows the previous wrong account - by checking "available teams". Those available teams are related to previous account, not the updated correct new one.

---
Pipeline says:

```
--- Step: upload_to_testflight ---

Login to App Store Connect (correct-account@account.com)

Could not set team ID to 'Good team ID', only found the following available teams:
 - XXXXXX (Team from wrong account)
 - XXXXXX (Another team from wrong account)
 - XXXXXX (And another team from wrong account)
```

For visual, please see this [screenshot](https://imgur.com/a/mJ45QAK)

- [x] I once again checked Apple Developer Account Membership page for team ID and email I want to use.
- [x] I once again checked all my CI/CD variables.
- [x] I once again checked what teams wrong and correct account have and I still confirm this issue is present.
- [x] I once again did CMD+F search throughout the project folder (with fastlane folder included) and CI/CD variables to make sure nothing from wrong account is left. Yes, nothing is left, only new needed account and team details.

---
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 12.0.1                                      |
| Ruby                        | 2.6.5                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.32.0 (Apple Git-132)          |
| Installation Source         | ~/.rbenv/versions/2.6.5/bin/fastlane        |
| Host                        | macOS 12.0.1 (21A559)                       |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.5/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 13.2.1                                      |
| Swift Version               | 5.5.2                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#     https://docs.fastlane.tools/actions
# For a list of all available plugins, check out
#     https://docs.fastlane.tools/plugins/available-plugins

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta_testflight do
    login_keychain_password = ENV["LOGIN_KEYCHAIN_PASSWORD"]
    new_keychain_name = ENV["NEW_KEYCHAIN_NAME"]
    new_keychain_password = ENV["NEW_KEYCHAIN_PASSWORD"]
    username = ENV["FASTLANE_USER"]
    team_id = ENV["APPLE_DEVELOPER_TEAM_ID"]
    unlock_keychain(
      path: "login.keychain",
      password: login_keychain_password
    )
    sh "security set-keychain-settings -t 3600 -l ~/Library/Keychains/login.keychain"
    create_keychain(
      name: new_keychain_name,
      unlock: true,
      timeout: 0,
      lock_when_sleeps: false,
      password: new_keychain_password
    )
    match(
      type: "adhoc",
      keychain_name: new_keychain_name,
      keychain_password: new_keychain_password,
      readonly: true
    )
    sh "security set-key-partition-list -S apple-tool:,apple: -s -k \"#{new_keychain_password}\" \"#{new_keychain_name}\""
    build_app(
      workspace: "xxx.xcworkspace",
      scheme: "App-tst",
      configuration: "Release",
      export_method: "ad-hoc",
      export_options: {
        signingStyle: "manual",
        provisioningProfiles: { 
          xxxxx
        }
      },
      clean: true,
      export_team_id: team_id
    )
    release_notes = sh("../release-notes.sh")
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      changelog: release_notes,
      username: username,
      team_id: team_id
    )
    upload_symbols_to_crashlytics(
      dsym_path: "#{Actions.lane_context[SharedValues::DSYM_OUTPUT_PATH]}", 
      api_token: ENV["FIREBASE_CRASHLYTICS_API_KEY"],
      gsp_path: ENV["GSP_PATH"],
      app_id: ENV["FIREBASE_APP_ID"],
      debug: false,
      binary_path: './scripts/upload-symbols'
    )
    delete_keychain(name: new_keychain_name)
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier(ENV["APPLE_APP_IDENTIFIER"] || "correct_app_identifier")
team_id(ENV["APPLE_DEVELOPER_TEAM_ID"] || "correct_team_id")
apple_id("correct-account@account.com")
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.206.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.3.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.3.0        |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| terminal-notifier                         | 2.0.0        |
| terminal-table                            | 1.8.0        |
| plist                                     | 3.6.0        |
| addressable                               | 2.8.0        |
| multipart-post                            | 2.0.0        |
| word_wrap                                 | 1.0.0        |
| optparse                                  | 0.1.1        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| artifactory                               | 3.0.15       |
| babosa                                    | 1.0.4        |
| colored                                   | 1.2          |
| highline                                  | 2.0.3        |
| commander                                 | 4.6.0        |
| faraday-cookie_jar                        | 0.0.7        |
| gh_inspector                              | 1.1.3        |
| mini_magick                               | 4.11.0       |
| naturally                                 | 2.2.1        |
| security                                  | 0.1.3        |
| xcpretty-travis-formatter                 | 1.0.1        |
| dotenv                                    | 2.7.6        |
| simctl                                    | 1.6.8        |
| rexml                                     | 3.2.5        |
| nanaimo                                   | 0.3.0        |
| colored2                                  | 3.1.2        |
| claide                                    | 1.1.0        |
| CFPropertyList                            | 3.0.5        |
| atomos                                    | 0.1.3        |
| xcodeproj                                 | 1.21.0       |
| unicode-display_width                     | 1.8.0        |
| public_suffix                             | 4.0.7        |
| excon                                     | 0.92.2       |
| ruby2_keywords                            | 0.0.5        |
| faraday-retry                             | 1.0.3        |
| faraday-rack                              | 1.0.0        |
| faraday-patron                            | 1.0.0        |
| faraday-net_http_persistent               | 1.2.0        |
| faraday-net_http                          | 1.0.1        |
| faraday-multipart                         | 1.0.3        |
| faraday-httpclient                        | 1.0.1        |
| faraday-excon                             | 1.1.0        |
| faraday-em_synchrony                      | 1.0.0        |
| faraday-em_http                           | 1.0.0        |
| faraday                                   | 1.10.0       |
| unf_ext                                   | 0.0.8.1      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| http-cookie                               | 1.0.4        |
| faraday_middleware                        | 1.2.0        |
| fastimage                                 | 2.2.6        |
| json                                      | 2.6.1        |
| rubyzip                                   | 2.3.2        |
| bundler                                   | 2.2.14       |
| jwt                                       | 2.3.0        |
| webrick                                   | 1.7.0        |
| httpclient                                | 2.8.3        |
| multi_json                                | 1.15.0       |
| signet                                    | 0.16.1       |
| os                                        | 1.1.4        |
| memoist                                   | 0.16.2       |
| googleauth                                | 1.1.3        |
| mini_mime                                 | 1.1.2        |
| retriable                                 | 3.1.2        |
| trailblazer-option                        | 0.1.2        |
| declarative                               | 0.0.20       |
| uber                                      | 0.1.0        |
| representable                             | 3.1.1        |
| google-apis-core                          | 0.4.2        |
| google-apis-playcustomapp_v1              | 0.7.0        |
| google-apis-androidpublisher_v3           | 0.19.0       |
| rake                                      | 13.0.6       |
| digest-crc                                | 0.6.4        |
| google-apis-storage_v1                    | 0.13.0       |
| google-apis-iamcredentials_v1             | 0.10.0       |
| google-cloud-errors                       | 1.2.0        |
| google-cloud-env                          | 1.6.0        |
| google-cloud-core                         | 1.6.0        |
| google-cloud-storage                      | 1.36.2       |
| emoji_regex                               | 3.2.3        |
| aws-eventstream                           | 1.2.0        |
| aws-sigv4                                 | 1.5.0        |
| aws-partitions                            | 1.579.0      |
| jmespath                                  | 1.6.1        |
| aws-sdk-core                              | 3.130.1      |
| aws-sdk-kms                               | 1.56.0       |
| aws-sdk-s3                                | 1.113.0      |
| forwardable                               | 1.2.0        |
| logger                                    | 1.3.0        |
| date                                      | 2.0.0        |
| stringio                                  | 0.0.2        |
| ipaddr                                    | 1.2.2        |
| openssl                                   | 2.1.2        |
| zlib                                      | 1.0.0        |
| mutex_m                                   | 0.1.0        |
| ostruct                                   | 0.1.0        |
| strscan                                   | 1.0.0        |
| io-console                                | 0.4.7        |
| fileutils                                 | 1.1.0        |
| etc                                       | 1.0.1        |
| racc                                      | 1.5.2        |
| nokogiri                                  | 1.11.7       |
| psych                                     | 3.1.0        |
| fastlane-plugin-firebase_app_distribution | 0.3.4        |
</details>

*generated on:* **2022-05-25**
</details>

---
<details>

CI/CD variables:

``APPLE_DEVELOPER_TEAM_ID`` - correct team ID
``FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`` - correct
``FASTLANE_ITC_TEAM_ID`` - checked, correct
``FASTLANE_SESSION`` - regenerated for correct account, must be ok
``FASTLANE_USER`` - correct account
``SPACESHIP_ONLY_ALLOW_INTERACTIVE_2FA`` - true
  
</details>

**Comment by liudasbar** [comment]
**SOLVED**

By removing cookie files for both:``/Users/admin/.fastlane/spaceship/correct-account@account.com`` and ``/Users/admin/.fastlane/spaceship/wrong-account@account.com`` and re-generating new correct account session.

**Comment by Holthaus789** [comment]
check this out : https://stackoverflow.com/questions/55568566/fastlane-uploading-to-testflight-return-an-error-but-still-showing-the-build-a

**Comment by Holthaus789** [comment]
check this out :https://docs.fastlane.tools/actions/upload_to_testflight/
