### ISSUE TITLE
Can't find s3 object with nuke command

### ISSUE THREAD

**Issue by iaia** [fastlane/fastlane#20345]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

s3_object_prefix is not reflected even if specified, and certificate download fails.

https://github.com/fastlane/fastlane/blob/c02fa82a35b84a4e6ba01d3942a6c2ff77339819/match/lib/match/nuke.rb#L37-L58

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by litebluetips** [comment]
Your article content is being very much interested, I am very impressed with your post. I hope to receive more great posts.

**Comment by iaia** [comment]
I have fixed it. https://github.com/fastlane/fastlane/pull/20344
Waiting for it to be merged and released.
