### ISSUE TITLE
Release to 2 different Apps in Testflight? (ERROR ITMS-90053, ERROR ITMS-90055)

### ISSUE THREAD

**Issue by allidoisace** [fastlane/fastlane#20355]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I am receiving an error for trying to call `upload_to_testflight` with a bundle id that's a subset of the production's bundle id. I want the following:

App #1 in Testflight: `com.myuniquename.app`
App #2 in Testflight: `com.myuniquename.app.debug`

But, I receive the errors below on `upload_to_testflight` step.

```
ERROR ITMS-90053: "This bundle is invalid. The bundle identifier is already in use by a different software package."
ERROR ITMS-90055: This bundle is invalid. The bundle identifier cannot be changed from the current value, 'com.myuniquename.app.debug'. If you want to change your bundle identifier, you will need to create a new application in App Store Connect.
```

##### Command executed

`upload_to_testflight`

**Comment by Anita854** [comment]
did you solve the question ?

**Comment by allidoisace** [comment]
This has been resolved. I needed to actually create schemes in Xcode.
