### ISSUE TITLE
Is there a fastlane action for getting build details from testflight?

### ISSUE THREAD

**Issue by SumanDas94** [fastlane/fastlane#20350]
### Discussed in https://github.com/fastlane/fastlane/discussions/20349

<div type='discussions-op-text'>

<sup>Originally posted by **SumanDas94** June  3, 2022</sup>
Currently we can use `latest_testflight_build_number` to get the latest TestFlight build number
We have a use case where we would need the version numbers present in TestFlight or even better the latest actual version present in TestFlight
The closest thing i got is `fastlane pilot builds` but this can't be used directly in the fastfile I believe and it needs the apple account password to be given as input. 
Is there an action present or any in the roadmap which can get me the existing TestFlight versions or latest TestFlight version via the fastfile </div>

**Comment by crazymanish** [comment]
Existing [latest_testflight_build_number](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/latest_testflight_build_number.rb) action provide both values [build version](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/latest_testflight_build_number.rb#L15) and [build number](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/latest_testflight_build_number.rb#L14). 

You should be able to fetch both values using the something like below code and we don't need another action or something to fetch the version.

```ruby
  lane :fetch_latest_testflight_build_version_and_number do
    # https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/latest_testflight_build_number.rb
    latest_testflight_build_number # you can provides more input params, if required.

    latest_build_version = lane_context[SharedValues::LATEST_TESTFLIGHT_VERSION]
    latest_build_number = lane_context[SharedValues::LATEST_TESTFLIGHT_BUILD_NUMBER]

    UI.important("The latest build number #{latest_build_number} of the latest version: #{latest_build_version}")
  end
