### ISSUE TITLE
Create_app_online services not working

### ISSUE THREAD

**Issue by atanas-ampeco** [fastlane/fastlane#20361]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm trying to create a new apple app identifier using the create_app_online action. At the same time I would like to include sign_in_with_apple and time_sensitive_notifications as enabled services in the identifier. However when I add these fastline is failing with an error stating that these are not available options(undefined method sign_in_with_apple' for Spaceship::Portal::AppService:Class) while both the documentation and the help page clearly state that they are. 

Another interesting point here is that I tested modife_services action, with the same arguments and it worked like a charm, however I can't use modify_services in my setup

##### Command executed
Here is my code
<details>
<pre>
create_app_online(
    username: tenant.config.ios.user,
    team_name: tenant.config.ios.team_name,
    app_name: tenant.config.ios.app_name,
    skip_itc: true,
    app_identifier: tenant.config.ios.bundle_id,
    enable_services: {
        apple_pay: "on",                       
        associated_domains: "on",
        push_notification: "on",
        sign_in_with_apple: "on",
        time_sensitive_notifications: "on"
    }
)
</pre>
</details>

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre> [12:35:47]: -------------------------------
[12:35:47]: --- Step: create_app_online ---
[12:35:47]: -------------------------------

+----------------------------------------------+--------------------+
|                    Summary for produce 2.206.2                    |
+----------------------------------------------+--------------------+
| username                                     | ******             |
| team_name                                    | ******             |
| app_name                                     | junkapp4           |
| skip_itc                                     | true               |
| app_identifier                               | tech.junk4         |
| enable_services.apple_pay                    | on                 |
| enable_services.associated_domains           | on                 |
| enable_services.push_notification            | on                 |
| enable_services.sign_in_with_apple           | on                 |
| enable_services.time_sensitive_notifications | on                 |
| sku                                          | 1654594547         |
| platform                                     | ios                |
| language                                     | English            |
| skip_devcenter                               | false              |
+----------------------------------------------+--------------------+

[12:35:49]: Creating new app 'junkapp4' on the Apple Dev Center
+---------------+----------------+
|          Lane Context          |
+---------------+----------------+
| PLATFORM_NAME |                |
| LANE_NAME     | n_setup_app_id |
+---------------+----------------+

+------+-------------------+-------------+
|            fastlane summary            |
+------+-------------------+-------------+
| Step | Action            | Time (in s) |
+------+-------------------+-------------+
| 💥   | create_app_online | 1           |
+------+-------------------+-------------+

[12:35:49]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Specify IPA path as a parameter to deliver beta
    https://github.com/fastlane/fastlane/issues/244 [closed] 2 💬
    22 Sep 2016

➡️  commit_version_bump error in-spite of expected and actual changes being same
    https://github.com/fastlane/fastlane/issues/248 [closed] 2 💬
    22 Sep 2016

➡️  Sigh: Lane specific `team_id` and `app_identifier` not used
    https://github.com/fastlane/fastlane/issues/256 [closed] 23 💬
    22 Sep 2016

and 19070 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60sign_in_with_apple%27%20for%20Spaceship%3A%3APortal%3A%3AAppService%3AClass%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20enabled_clean_options%5Bapp_service.send%28k.to_s%29.on.service_id%5D%20%3D%20app_service.send%28k.to_s%29.on%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/atanasna/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.206.2/produce/lib/produce/developer_center.rb:148:in `block in enable_services': \e[31m[!] undefined method `sign_in_with_apple' for Spaceship::Portal::AppService:Class (NoMethodError)

            enabled_clean_options[app_service.send(k.to_s).on.service_id] = app_service.send(k.to_s).on
                                             ^^^^^\e[0m
        from /Users/atanasna/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.206.2/produce/lib/produce/developer_center.rb:127:in `each'
        from /Users/atanasna/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.206.2/produce/lib/produce/developer_center.rb:127:in `enable_services'
        from /Users/atanasna/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.206.2/produce/lib/produce/developer_center.rb:99:in `create_new_app'
        from /Users/atanasna/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.206.2/produce/lib/produce/developer_center.rb:84:in `run'
        from /Users/atanasna/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.206.2/produce/lib/produce/manager.rb:11:in `start_producing'
        from /Users/atanasna/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/actions/create_app_online.rb:17:in `block in run'
        from /Users/atanasna/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/actions/create_app_online.rb:15:in `chdir'
        from /Users/atanasna/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/actions/create_app_online.rb:15:in `run'
        from /Users/atanasna/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
        from /Users/atanasna/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        from /Users/atanasna/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
        from /Users/atanasna/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        from /Users/atanasna/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        from /Users/atanasna/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        from /Users/atanasna/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        from lanes/sole.lanes:46:in `block in parsing_binding'
        from /Users/atanasna/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /Users/atanasna/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /Users/atanasna/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /Users/atanasna/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /Users/atanasna/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        from /Users/atanasna/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from /Users/atanasna/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
        from /Users/atanasna/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /Users/atanasna/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /Users/atanasna/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /Users/atanasna/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.206.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /Users/atanasna/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /Users/atanasna/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
        from /Users/atanasna/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        from /Users/atanasna/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        from /Users/atanasna/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-2.206.2/bin/fastlane:23:in `<top (required)>'
        from /Users/atanasna/.asdf/installs/ruby/3.1.2/bin/fastlane:25:in `load'
        from /Users/atanasna/.asdf/installs/ruby/3.1.2/bin/fastlane:25:in `<main>'</pre>
</details>

##### Environment
<details>
<pre>
### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 12.4                                        |
| Ruby                        | 3.1.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.32.1 (Apple Git-133)          |
| Installation Source         | ~/.asdf/installs/ruby/3.1.2/bin/fastlane    |
| Host                        | macOS 12.4 (21F79)                          |
| Ruby Lib Dir                | ~/.asdf/installs/ruby/3.1.2/lib             |
| OpenSSL Version             | OpenSSL 1.1.1n  15 Mar 2022                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 13.4.1                                      |
| Swift Version               | 5.6.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.206.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

### Loaded gems

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.7        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.92.3       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.3        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.0       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.3.7        |
| simctl                          | 1.6.8        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.1       |
| googleauth                      | 1.1.3        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.5.0        |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-androidpublisher_v3 | 0.21.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.14.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.36.2       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.6.1        |
| aws-partitions                  | 1.592.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.0        |
| aws-sdk-core                    | 3.131.1      |
| aws-sdk-kms                     | 1.57.0       |
| aws-sdk-s3                      | 1.114.0      |
| set                             | 1.0.2        |
| json                            | 2.6.2        |
| jwt                             | 2.4.0        |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.1        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.1        |
| uri                             | 0.11.0       |
| openssl                         | 3.0.0        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.0        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.2        |
| net-http                        | 0.2.0        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.11       |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.3        |
</pre>
</details>

**Comment by Holthaus789** [comment]
do you get any proper solution

**Comment by Ido-Levi** [comment]
Just reproduced to me using `produce`

**Comment by ShallowHound** [comment]
Thanks for sharing this wonderful post. And it is informative too. I want to get more information like this article. Please keep sharing.

**Comment by spacesuitdiver** [comment]
Any workaround @atanas-ampeco or @Ido-Levi ?
