### ISSUE TITLE
Fastlane authentication error on Unity Cloud Build

### ISSUE THREAD

**Issue by pietroF42** [fastlane/fastlane#20387]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Fastlane won't authenticate to the app store. I have tried in many ways and with many different env variables, but no matter what I put _deliver_ fails to authenticate.
the last runs I have been gatting the 2fa request on my mac while the build was running on the cloud.. which it shouldn't since I have specified the `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`. 

I had previously tried to use this custom lane but the api_key fails with some "curve" error (which is apparently related to the _new line catachter_s]
https://docs.fastlane.tools/app-store-connect-api/
```
  lane :test_flight do
    api_key = app_store_connect_api_key(
      key_id: "******",
      issuer_id: "*******",
      key_content: ENV["IOS_API_KEY"], # you can specify this on the Unity Evnironment Variables setup
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )
    pilot(api_key: api_key)
  end
```

Unity Cloud Build already uses fastlane to build the xcode project into the binary form, so I wonder if me tring to set up a different "fastlane environment" within the same machine is screwing things up.. 

##### Command executed
This is the bash script I run as post-build event
```#!/bin/bash

echo "###############################################"
echo "Uploading app to TestFlight..."
echo "-----------------------------------------------"
pwd
echo "-----------------------------------------------"
env
echo "-----------------------------------------------"
ls -a .
echo "-----------------------------------------------"

echo "-----------------------------------------------"
bundle install
echo "-----------------------------------------------"

exit_code=1
if bundle exec fastlane release --verbose ; then
    echo "======== Upload IPA to Appstore Connect finished with success"
    # end without error
    exit_code=0
else
    echo "======== ERROR! Upload IPA to Appstore Connect failed"
    echo "-------- Current Folder Content"
    ls -a .
    echo "-----------------------------------------------"
    bundle exec fastlane env
    echo "-----------------------------------------------"
    # end with error
    exit_code=1
fi

echo "###############################################"
exit $exit_code

```

##### Complete output when running fastlane, including the stack trace and command used

Generating fastlane environment output, this might take a few seconds...
swift-driver version: 1.26.21 <details><summary>✅ fastlane environment ✅</summary>
### Stack
| Key                         | Value                                             |
| --------------------------- | ------------------------------------------------- |
| OS                          | 11.6.2                                            |
| Ruby                        | 2.7.4                                             |
| Bundler?                    | true                                              |
| Git                         | git version 2.34.1                                |
| Installation Source         | ~/.rvm/gems/ruby-2.7.4/bin/fastlane               |
| Host                        | macOS 11.6.2 (20G314)                             |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.7.4/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1m  14 Dec 2021                       |
| Is contained                | false                                             |
| Is homebrew                 | false                                             |
| Is installed via Fabric.app | false                                             |
| Xcode Path                  | /Applications/Xcode13_2_1.app/Contents/Developer/ |
| Xcode Version               | 13.2.1                                            |
| Swift Version               | 5.5.2                                             |

### System Locale
| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:
<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_require "dotenv"
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
before_all do
  Dotenv.load ".env.secret"
end
# Uncomment the line if you want fastlane to automatically update itself
update_fastlane
default_platform(:ios)
platform :ios do
  before_all do
    Dotenv.load ".env.ios"
  end
  desc "Sync singing"
  lane :signing do
    sync_code_signing # match
    mapping = Actions.lane_context[
      SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING
    ]
    update_code_signing_settings(
      profile_name: mapping[ENV['MATCH_APP_IDENTIFIER']]
    )
  end
  private_lane :reset_pass do
    ENV['FASTLANE_USER'] = nil
    ENV['FASTLANE_PASSWORD'] = nil
  end
  desc "Sign and upload to upstore"
  lane :release do
    deliver
  end
  
end
```
</details>
<details><summary>`./fastlane/Appfile`</summary>

```ruby
# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile
apple_id("appleid@mail.com")
team_id("**********")
```
</details>

### fastlane gems 

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.206.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:
**No plugins Loaded**
<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.4.0        |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| public_suffix                   | 4.0.7        |
| addressable                     | 2.8.0        |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.598.0      |
| aws-sigv4                       | 1.5.0        |
| jmespath                        | 1.6.1        |
| aws-sdk-core                    | 3.131.1      |
| aws-sdk-kms                     | 1.57.0       |
| aws-sdk-s3                      | 1.114.0      |
| babosa                          | 1.0.4        |
| bundler                         | 2.2.2        |
| claide                          | 1.1.0        |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.92.3       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.0.0        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.0       |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.4.1        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.1       |
| googleauth                      | 1.1.3        |
| httpclient                      | 2.8.3        |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.5.0        |
| google-apis-androidpublisher_v3 | 0.21.0       |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.14.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.36.2       |
| json                            | 2.6.2        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |

</details>

*generated on:*  **2022-06-15**

</details>
Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅

**Comment by pietroF42** [comment]
some other resources:

- https://github.com/fastlane/fastlane/tree/master/credentials_manager
- https://forum.unity.com/threads/fastlane-for-ios-and-android.1019485/
- https://forum.unity.com/threads/unity-cloud-build-fastlane-for-android.1186918

**Comment by Hendershott** [comment]
Your article content is being very much interested, I am very impressed with your post. I hope to receive more great posts.

**Comment by Holthaus789** [comment]
This works really well for us, thank you!

**Comment by L4ZZA** [comment]
> This works really well for us, thank you!

How is it working for you? 😭

**Comment by pietroF42** [comment]
> This works really well for us, thank you!

You're welcome! There really is not enough talk about this.. 
@Holthaus789 How did you `app_store_connect_api_key`? following the official documentation doesn't seem to work for me..

**Comment by pietroF42** [comment]
Here the same issue posted on Unity Forum
https://forum.unity.com/threads/fastlane-for-ios-and-android.1019485/#post-8224878

**Comment by pietroF42** [comment]
Well, I am still waiting for a response both from Fastlane and from Unity..
