### ISSUE TITLE
verify_xcode action fails for Xcode 14 Beta

### ISSUE THREAD

**Issue by TheMetalCode** [fastlane/fastlane#20380]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

See also: https://github.com/xcpretty/xcode-install/issues/460

This was originally made known to me when attempting to use `xcode-install` to install the Xcode 14 Beta on a CI runner, but after realizing that `xcode-install` uses the `verify_xcode` action and that it was that action that was causing the failure, I was able to reproduce the issue on my local machine by manually downloading & installing the Xcode beta from the Apple Developer site, and then running `fastlane verify_xcode` on that installation.

What isn't clear to me is if the Xcode internals have changed in a way that isn't accounted for in this action or if there's an issue with the `spctl --assess` command itself when executed against an Xcode 14 Beta installation.

##### Command executed

`bundle exec fastlane run verify_xcode xcode_path:"/Applications/Xcode-14-beta.app"`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[✔] 🚀
+-------------------------------------------+---------+--------------------------------------------------+
|                                              Used plugins                                              |
+-------------------------------------------+---------+--------------------------------------------------+
| Plugin                                    | Version | Action                                           |
+-------------------------------------------+---------+--------------------------------------------------+
| fastlane-plugin-firebase_app_distribution | 0.3.4   | firebase_app_distribution_login,                 |
|                                           |         | firebase_app_distribution_add_testers,           |
|                                           |         | firebase_app_distribution_get_udids,             |
|                                           |         | firebase_app_distribution,                       |
|                                           |         | firebase_app_distribution_get_latest_release,    |
|                                           |         | firebase_app_distribution_remove_testers         |
| fastlane-plugin-bugsnag                   | 2.2.1   | upload_symbols_to_bugsnag, send_build_to_bugsnag |
+-------------------------------------------+---------+--------------------------------------------------+

[09:44:08]: --------------------------
[09:44:08]: --- Step: verify_xcode ---
[09:44:08]: --------------------------
[09:44:08]: Verifying your Xcode installation at path '/Applications/Xcode-14-beta.app'...
[09:44:08]: Verifying Xcode was signed by Apple Inc.
[09:44:08]: $ codesign --display --verbose=4 /Applications/Xcode-14-beta.app
[09:44:11]: ▸ Executable=/Applications/Xcode-14-beta.app/Contents/MacOS/Xcode
[09:44:11]: ▸ Identifier=com.apple.dt.Xcode
[09:44:11]: ▸ Format=app bundle with Mach-O universal (x86_64 arm64)
[09:44:11]: ▸ CodeDirectory v=20400 size=790 flags=0x2000(library-validation) hashes=14+7 location=embedded
[09:44:11]: ▸ VersionPlatform=1
[09:44:11]: ▸ VersionMin=720896
[09:44:11]: ▸ VersionSDK=851968
[09:44:11]: ▸ Hash type=sha256 size=32
[09:44:11]: ▸ CandidateCDHash sha256=3fa0a23059108e19b0b63db7b91fd68fe086bd0f
[09:44:11]: ▸ CandidateCDHashFull sha256=3fa0a23059108e19b0b63db7b91fd68fe086bd0f55583f22cc39123a27f55f5a
[09:44:11]: ▸ Hash choices=sha256
[09:44:11]: ▸ CMSDigest=3fa0a23059108e19b0b63db7b91fd68fe086bd0f55583f22cc39123a27f55f5a
[09:44:11]: ▸ CMSDigestType=2
[09:44:11]: ▸ Executable Segment base=0
[09:44:11]: ▸ Executable Segment limit=16384
[09:44:11]: ▸ Executable Segment flags=0x1
[09:44:11]: ▸ Page size=4096
[09:44:11]: ▸ CDHash=3fa0a23059108e19b0b63db7b91fd68fe086bd0f
[09:44:11]: ▸ Signature size=4442
[09:44:11]: ▸ Authority=Software Signing
[09:44:11]: ▸ Authority=Apple Code Signing Certification Authority
[09:44:11]: ▸ Authority=Apple Root CA
[09:44:11]: ▸ Signed Time=Jun 4, 2022 at 1:55:48 PM
[09:44:11]: ▸ Info.plist entries=44
[09:44:11]: ▸ TeamIdentifier=59GAB85EFG
[09:44:11]: ▸ Sealed Resources version=2 rules=13 files=367263
[09:44:11]: ▸ Internal requirements count=1 size=68
[09:44:11]: Successfully verified the code signature ✅
[09:44:11]: Verifying Xcode using GateKeeper...
[09:44:11]: This will take up to a few minutes, now is a great time to go for a coffee ☕...
[09:44:11]: $ /usr/sbin/spctl --assess --verbose /Applications/Xcode-14-beta.app
[09:49:58]: ▸ /Applications/Xcode-14-beta.app: rejected (invalid destination for symbolic link in bundle)

Looking for related GitHub issues on fastlane/fastlane...

➡️  testmunk intro text
    https://github.com/fastlane/fastlane/pull/3 [closed] 0 💬
    04 Feb 2017

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/Users/jhagglund/.rbenv/versions/2.7.6/bin/fastlane)
Traceback (most recent call last):
	40: from /Users/jhagglund/.rbenv/versions/2.7.6/bin/bundle:25:in `<main>'
	39: from /Users/jhagglund/.rbenv/versions/2.7.6/bin/bundle:25:in `load'
	38: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/exe/bundle:36:in `<top (required)>'
	37: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	36: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/exe/bundle:48:in `block in <top (required)>'
	35: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/cli.rb:25:in `start'
	34: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	33: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/cli.rb:31:in `dispatch'
	32: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	31: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	30: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	29: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/cli.rb:483:in `exec'
	28: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/cli/exec.rb:23:in `run'
	27: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/cli/exec.rb:58:in `kernel_load'
	26: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/cli/exec.rb:58:in `load'
	25: from /Users/jhagglund/.rbenv/versions/2.7.6/bin/fastlane:25:in `<top (required)>'
	24: from /Users/jhagglund/.rbenv/versions/2.7.6/bin/fastlane:25:in `load'
	23: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/bin/fastlane:23:in `<top (required)>'
	22: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	21: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	20: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	19: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	18: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	17: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	16: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	15: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	14: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/commands_generator.rb:226:in `block (2 levels) in run'
	13: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/one_off.rb:22:in `execute'
	12: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/one_off.rb:42:in `run'
	11: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	10: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	 9: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	 8: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	 7: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 6: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/actions/verify_xcode.rb:17:in `run'
	 5: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/actions/verify_xcode.rb:78:in `verify_gatekeeper'
	 4: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/actions/verify_xcode.rb:88:in `verify'
	 3: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
	 2: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	 1: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': Exit status of command '/usr/sbin/spctl --assess --verbose /Applications/Xcode-14-beta.app' was 3 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
/Applications/Xcode-14-beta.app: rejected (invalid destination for symbolic link in bundle)
	40: from /Users/jhagglund/.rbenv/versions/2.7.6/bin/bundle:25:in `<main>'
	39: from /Users/jhagglund/.rbenv/versions/2.7.6/bin/bundle:25:in `load'
	38: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/exe/bundle:36:in `<top (required)>'
	37: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	36: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/exe/bundle:48:in `block in <top (required)>'
	35: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/cli.rb:25:in `start'
	34: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	33: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/cli.rb:31:in `dispatch'
	32: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	31: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	30: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	29: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/cli.rb:483:in `exec'
	28: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/cli/exec.rb:23:in `run'
	27: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/cli/exec.rb:58:in `kernel_load'
	26: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bundler-2.3.15/lib/bundler/cli/exec.rb:58:in `load'
	25: from /Users/jhagglund/.rbenv/versions/2.7.6/bin/fastlane:25:in `<top (required)>'
	24: from /Users/jhagglund/.rbenv/versions/2.7.6/bin/fastlane:25:in `load'
	23: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/bin/fastlane:23:in `<top (required)>'
	22: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	21: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	20: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	19: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	18: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	17: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	16: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	15: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	14: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/commands_generator.rb:226:in `block (2 levels) in run'
	13: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/one_off.rb:22:in `execute'
	12: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/one_off.rb:42:in `run'
	11: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	10: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	 9: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	 8: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	 7: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 6: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/actions/verify_xcode.rb:17:in `run'
	 5: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/actions/verify_xcode.rb:78:in `verify_gatekeeper'
	 4: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/actions/verify_xcode.rb:88:in `verify'
	 3: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
	 2: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	 1: from /Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/jhagglund/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': \e[31m[!] Exit status of command '/usr/sbin/spctl --assess --verbose /Applications/Xcode-14-beta.app' was 3 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
/Applications/Xcode-14-beta.app: rejected (invalid destination for symbolic link in bundle)</pre>
</details>

### Environment

<details>
  <pre>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                               |
| --------------------------- | --------------------------------------------------- |
| OS                          | 12.4                                                |
| Ruby                        | 2.7.6                                               |
| Bundler?                    | true                                                |
| Git                         | git version 2.36.1                                  |
| Installation Source         | ~/.rbenv/versions/2.7.6/bin/fastlane                |
| Host                        | macOS 12.4 (21F79)                                  |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.6/lib                         |
| OpenSSL Version             | OpenSSL 1.1.1n  15 Mar 2022                         |
| Is contained                | false                                               |
| Is homebrew                 | false                                               |
| Is installed via Fabric.app | false                                               |
| Xcode Path                  | /Applications/Xcode-14-beta.app/Contents/Developer/ |
| Xcode Version               | 14.0                                                |
| Swift Version               | 5.7                                                 |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
[REDACTED]

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "REDACTED" # The bundle identifier of your app

team_id "REDACTED"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.206.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.3.4   | ✅ Up-To-Date  |
| fastlane-plugin-bugsnag                   | 2.2.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.4.0        |
| bundler                                   | 2.3.15       |
| rake                                      | 13.0.6       |
| rexml                                     | 3.2.5        |
| CFPropertyList                            | 3.0.5        |
| concurrent-ruby                           | 1.1.10       |
| i18n                                      | 1.10.0       |
| minitest                                  | 5.15.0       |
| tzinfo                                    | 2.0.4        |
| zeitwerk                                  | 2.5.4        |
| activesupport                             | 6.1.6        |
| public_suffix                             | 4.0.7        |
| addressable                               | 2.8.0        |
| httpclient                                | 2.8.3        |
| json                                      | 2.6.2        |
| algoliasearch                             | 1.27.5       |
| artifactory                               | 3.0.15       |
| atomos                                    | 0.1.3        |
| aws-eventstream                           | 1.2.0        |
| aws-partitions                            | 1.596.0      |
| aws-sigv4                                 | 1.5.0        |
| jmespath                                  | 1.6.1        |
| aws-sdk-core                              | 3.131.1      |
| aws-sdk-dynamodb                          | 1.74.0       |
| aws-sdk-kms                               | 1.57.0       |
| aws-sdk-s3                                | 1.114.0      |
| babosa                                    | 1.0.4        |
| circleci                                  | 2.0.3        |
| highline                                  | 2.0.3        |
| commander                                 | 4.6.0        |
| down                                      | 5.3.1        |
| faraday-em_http                           | 1.0.0        |
| faraday-em_synchrony                      | 1.0.0        |
| faraday-excon                             | 1.1.0        |
| faraday-httpclient                        | 1.0.1        |
| multipart-post                            | 2.0.0        |
| faraday-multipart                         | 1.0.4        |
| faraday-net_http                          | 1.0.1        |
| faraday-net_http_persistent               | 1.2.0        |
| faraday-patron                            | 1.0.0        |
| faraday-rack                              | 1.0.0        |
| faraday-retry                             | 1.0.3        |
| ruby2_keywords                            | 0.0.5        |
| faraday                                   | 1.9.3        |
| racc                                      | 1.6.0        |
| nokogiri                                  | 1.13.6       |
| openssl                                   | 3.0.0        |
| [REDACTED]                           | [REDACTED]       |
| claide                                    | 1.1.0        |
| fuzzy_match                               | 2.0.4        |
| nap                                       | 1.1.0        |
| netrc                                     | 0.11.0       |
| ffi                                       | 1.15.5       |
| ethon                                     | 0.15.0       |
| typhoeus                                  | 1.4.0        |
| cocoapods-core                            | 1.11.3       |
| cocoapods-deintegrate                     | 1.0.5        |
| cocoapods-downloader                      | 1.6.3        |
| cocoapods-plugins                         | 1.0.0        |
| cocoapods-search                          | 1.0.1        |
| cocoapods-trunk                           | 1.6.0        |
| cocoapods-try                             | 1.2.0        |
| colored2                                  | 3.1.2        |
| escape                                    | 0.0.4        |
| fourflusher                               | 2.3.1        |
| gh_inspector                              | 1.1.3        |
| molinillo                                 | 0.8.0        |
| ruby-macho                                | 2.5.1        |
| nanaimo                                   | 0.3.0        |
| xcodeproj                                 | 1.21.0       |
| cocoapods                                 | 1.11.3       |
| colored                                   | 1.2          |
| ruby-terminfo                             | 0.1.1        |
| console_table                             | 0.3.0        |
| declarative                               | 0.0.20       |
| digest-crc                                | 0.6.4        |
| unf_ext                                   | 0.0.8.2      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| dotenv                                    | 2.7.6        |
| emoji_regex                               | 3.2.3        |
| excon                                     | 0.92.3       |
| http-cookie                               | 1.0.5        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.2.0        |
| fastimage                                 | 2.2.6        |
| jwt                                       | 2.4.0        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.4        |
| signet                                    | 0.16.1       |
| googleauth                                | 1.1.3        |
| mini_mime                                 | 1.1.2        |
| trailblazer-option                        | 0.1.2        |
| uber                                      | 0.1.0        |
| representable                             | 3.2.0        |
| retriable                                 | 3.1.2        |
| webrick                                   | 1.7.0        |
| google-apis-core                          | 0.5.0        |
| google-apis-androidpublisher_v3           | 0.21.0       |
| google-apis-playcustomapp_v1              | 0.7.0        |
| google-apis-iamcredentials_v1             | 0.10.0       |
| google-apis-storage_v1                    | 0.14.0       |
| google-cloud-env                          | 1.6.0        |
| google-cloud-errors                       | 1.2.0        |
| google-cloud-core                         | 1.6.0        |
| google-cloud-storage                      | 1.36.2       |
| mini_magick                               | 4.11.0       |
| naturally                                 | 2.2.1        |
| optparse                                  | 0.1.1        |
| plist                                     | 3.6.0        |
| rubyzip                                   | 2.3.2        |
| security                                  | 0.1.3        |
| simctl                                    | 1.6.8        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.8.0        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| word_wrap                                 | 1.0.0        |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.1        |
| rchardet                                  | 1.8.0        |
| git                                       | 1.11.0       |
| xml-simple                                | 1.1.9        |
| fastlane-plugin-bugsnag                   | 2.2.1        |
| fastlane-plugin-firebase_app_distribution | 0.3.4        |
| frontkick                                 | 0.5.7    |
| mustache                                  | 1.1.1        |
| open4                                     | 1.3.4        |
| redcarpet                                 | 3.5.1        |
| sassc                                     | 2.4.0        |
| sqlite3                                   | 1.4.2        |
| liferaft                                  | 0.0.6        |
| xcinvoke                                  | 0.3.0        |
| jazzy                                     | 0.14.2       |
</details>

*generated on:* **2022-06-13**
</details>
  </pre>
</details>

**Comment by TheMetalCode** [comment]
I suspect it may have been something quirky with the first Xcode 14 Beta. I am able to run `verify_xcode` on the recently release Xcode 14 Beta 2 successfully.

**Comment by richardsimkins** [comment]
I can confirm that Xcode "14 beta 2" passes verification.
