### ISSUE TITLE
Clarification on Deliver lane- Pricing and availability updates - App store connect 

### ISSUE THREAD

**Issue by kamalmobiledev** [fastlane/fastlane#20382]
Hi Team,

While going through documents we understand that the metadata for availability section of IOS can be provided with the country code. 
However wanted to know if there is any way or parameter which we can use to update the availability/visiblity to be only within the business organization or school and not public ?

**Comment by litebluetips** [comment]
Facing same issue here. Help is appreciated.

**Comment by Lydia748** [comment]
I have the exact same problem. Have tried a variety of things. Me too facing the similar issues.

**Comment by kamalmobiledev** [comment]
Hi Team,


Apologies,This is not an issue.

We would need clarity on the possibility of making changes to the
availablity flag.

Thanks
Kamal
