### ISSUE TITLE
Cannot specify automatic signing if provisioning profiles are present

### ISSUE THREAD

**Issue by Helam24** [fastlane/fastlane#20388]
[This PR](https://github.com/fastlane/fastlane/pull/10508) looks to have introduced code that forces manual signing if there are any provisioning profiles present, even if we manually specify that it should use automatic signing in the export_options. 

For context, I am working in an xcode workspace that contains multiple projects:
- App A: uses manual signing and specifies provisioning profiles in the xcode project file.
- App B: uses automatic signing and does not specify provisioning profiles in the xcode project file.

Even though we specify automatic signing in the export_options (and do not specify provisioning profiles), App B is being forced to use manual signing because there are provisioning profiles in the project file for App A that are making it into the resolved export_options and triggering the logic in [this PR](https://github.com/fastlane/fastlane/pull/10508).

I am not using match or sigh or anything like that for App B to specify provisioning profiles, but it still seems to include the provisioning profiles from App A's project file (in the same workspace) into the resolved export_options. If I rename App A's project file to a garbage value so that it can't be found by gym and then build App B, it works properly and does not force manual signing when building App B.

[This issue](https://github.com/fastlane/fastlane/issues/10778) talks about the same problematic behavior but in a different scenario. [This comment](https://github.com/fastlane/fastlane/issues/10778#issuecomment-341637844) states:

> maybe has the meaning to don't ignore signingStyle in export_options if it specified by user. it will add flexibility.

It seems like it would be good to respect the signingStyle specified by the user if they did specify one, and not overwrite it with 'manual' in that case.

I can't easily share the output of fastlane env without some heavy work to redact it, but I hope it should be obvious by looking at the code in [the referenced PR](https://github.com/fastlane/fastlane/pull/10508) that it will overwrite the user-specified signing style if there is one. I am hoping this can change to respect the user-specified value.

**Comment by Helam24** [comment]
Regarding the bot message, I put some reasoning at the end of the issue description explaining why I did not include it and I hope that the issue is obvious without it. If absolutely necessary I can do the work to redact it and share what I can, but I am hoping it will not be necessary.

**Comment by Hendershott** [comment]
How To Fix Xcode Failed To Create Provisioning Profile Error. To fix this error is very easy, just connect your real iOS device such as iPhone to the Mac computer with a USB line, follow the popup screen on the iPhone, then you can select your iOS device in the Set the active scheme drop down list.

**Comment by Helam24** [comment]
@Hendershott that is not the error, this is a problem with fastlane building the project using the wrong signingStyle due to a bug introduced in the past PR that I linked.
