### ISSUE TITLE
 App store connect doc does not have example for FastFile

### ISSUE THREAD

**Issue by GMerakis** [fastlane/fastlane#20393]
### New Issue Checklist

- [y] Updated fastlane to the latest version
- [y] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [y] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [y] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

As described in the title, the documentation at https://github.com/fastlane/fastlane/blob/master/spaceship/docs/AppStoreConnect.md
does not explain how to update FastFile when using fastlane.

eg.

`app_store_connect_api_key(
  key_id: "ABCDEFG",
  issuer_id: "Your_issuer_id",
  key_content: File.read("./key.p8").chomp,
  duration: 1200,
  in_house: false
)`

It's unclear what the code in the doc meant and where it should be applied

**Comment by crazymanish** [comment]
Hi @GMerakis 
i think you are looking for the below documentation 
https://docs.fastlane.tools/app-store-connect-api/

**Comment by GMerakis** [comment]
thanks @crazymanish !!
