### ISSUE TITLE
Fastlane is not working in M1

### ISSUE THREAD

**Issue by Chetan-Goyal** [fastlane/fastlane#20404]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
fastlane test is giving some ruby related issues.

##### Command executed

Tried installing via `brew install fastlane` , `arch -x86_64 brew install fastlane`, `sudo gem install fastlane` and `sudo arch -x86_64 gem install fastlane`

##### Complete output when running fastlane, including the stack trace and command used

`fastlane test`
<details>
  <pre> [✔] 🚀 
[10:34:09]: ------------------------------
[10:34:09]: --- Step: default_platform ---
[10:34:09]: ------------------------------
[10:34:09]: Driving the lane 'android test' 🚀
[10:34:09]: ------------------
[10:34:09]: --- Step: test ---
[10:34:09]: ------------------
[10:34:09]: $ /Users/satan/Library/github/ToDo-App/android/gradlew test -p .
[10:34:14]: ▸ > Task :app:compileFlutterBuildDebug
[10:34:14]: ▸ > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[10:34:14]: ▸ > Task :app:preBuild UP-TO-DATE
[10:34:14]: ▸ > Task :app:preDebugBuild UP-TO-DATE
[10:34:14]: ▸ > Task :flutter_secure_storage:preBuild UP-TO-DATE
[10:34:14]: ▸ > Task :flutter_secure_storage:preDebugBuild UP-TO-DATE
[10:34:14]: ▸ > Task :flutter_secure_storage:compileDebugAidl NO-SOURCE
[10:34:14]: ▸ > Task :fluttertoast:preBuild UP-TO-DATE
[10:34:14]: ▸ > Task :fluttertoast:preDebugBuild UP-TO-DATE
[10:34:14]: ▸ > Task :fluttertoast:compileDebugAidl NO-SOURCE
[10:34:14]: ▸ > Task :share_plus:preBuild UP-TO-DATE
[10:34:14]: ▸ > Task :share_plus:preDebugBuild UP-TO-DATE
[10:34:14]: ▸ > Task :share_plus:compileDebugAidl NO-SOURCE
[10:34:14]: ▸ > Task :shared_preferences_android:preBuild UP-TO-DATE
[10:34:14]: ▸ > Task :shared_preferences_android:preDebugBuild UP-TO-DATE
[10:34:14]: ▸ > Task :shared_preferences_android:compileDebugAidl NO-SOURCE
[10:34:14]: ▸ > Task :url_launcher_android:preBuild UP-TO-DATE
[10:34:14]: ▸ > Task :url_launcher_android:preDebugBuild UP-TO-DATE
[10:34:14]: ▸ > Task :url_launcher_android:compileDebugAidl NO-SOURCE
[10:34:14]: ▸ > Task :app:compileDebugAidl NO-SOURCE
[10:34:14]: ▸ > Task :flutter_secure_storage:packageDebugRenderscript NO-SOURCE
[10:34:14]: ▸ > Task :fluttertoast:packageDebugRenderscript NO-SOURCE
[10:34:14]: ▸ > Task :share_plus:packageDebugRenderscript NO-SOURCE
[10:34:14]: ▸ > Task :shared_preferences_android:packageDebugRenderscript NO-SOURCE
[10:34:14]: ▸ > Task :url_launcher_android:packageDebugRenderscript NO-SOURCE
[10:34:14]: ▸ > Task :app:compileDebugRenderscript NO-SOURCE
[10:34:14]: ▸ > Task :app:generateDebugBuildConfig UP-TO-DATE
[10:34:14]: ▸ > Task :flutter_secure_storage:writeDebugAarMetadata UP-TO-DATE
[10:34:14]: ▸ > Task :fluttertoast:writeDebugAarMetadata UP-TO-DATE
[10:34:14]: ▸ > Task :share_plus:writeDebugAarMetadata UP-TO-DATE
[10:34:14]: ▸ > Task :shared_preferences_android:writeDebugAarMetadata UP-TO-DATE
[10:34:14]: ▸ > Task :url_launcher_android:writeDebugAarMetadata UP-TO-DATE
[10:34:14]: ▸ > Task :app:checkDebugAarMetadata UP-TO-DATE
[10:34:14]: ▸ > Task :app:cleanMergeDebugAssets FAILED
[10:34:14]: ▸ FAILURE: Build failed with an exception.
[10:34:14]: ▸ * What went wrong:
[10:34:14]: ▸ Execution failed for task ':app:cleanMergeDebugAssets'.
[10:34:14]: ▸ > java.io.IOException: Unable to delete directory '/Users/satan/Library/github/ToDo-App/build/app/intermediates/incremental/mergeDebugAssets'
[10:34:14]: ▸ Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
[10:34:14]: ▸ - /Users/satan/Library/github/ToDo-App/build/app/intermediates/incremental/mergeDebugAssets/merger.xml
[10:34:14]: ▸ * Try:
[10:34:14]: ▸ > Run with --stacktrace option to get the stack trace.
[10:34:14]: ▸ > Run with --info or --debug option to get more log output.
[10:34:14]: ▸ > Run with --scan to get full insights.
[10:34:14]: ▸ * Get more help at https://help.gradle.org
[10:34:14]: ▸ Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
[10:34:14]: ▸ You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
[10:34:14]: ▸ See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings
[10:34:14]: ▸ BUILD FAILED in 5s
[10:34:14]: ▸ 10 actionable tasks: 2 executed, 8 up-to-date
+------------------+--------------+
|          Lane Context           |
+------------------+--------------+
| DEFAULT_PLATFORM | android      |
| PLATFORM_NAME    | android      |
| LANE_NAME        | android test |
+------------------+--------------+
[10:34:15]: Exit status of command '/Users/satan/Library/github/ToDo-App/android/gradlew test -p .' was 1 instead of 0.
> Task :app:compileFlutterBuildDebug
> Task :app:packLibsflutterBuildDebug UP-TO-DATE
> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :flutter_secure_storage:preBuild UP-TO-DATE
> Task :flutter_secure_storage:preDebugBuild UP-TO-DATE
> Task :flutter_secure_storage:compileDebugAidl NO-SOURCE
> Task :fluttertoast:preBuild UP-TO-DATE
> Task :fluttertoast:preDebugBuild UP-TO-DATE
> Task :fluttertoast:compileDebugAidl NO-SOURCE
> Task :share_plus:preBuild UP-TO-DATE
> Task :share_plus:preDebugBuild UP-TO-DATE
> Task :share_plus:compileDebugAidl NO-SOURCE
> Task :shared_preferences_android:preBuild UP-TO-DATE
> Task :shared_preferences_android:preDebugBuild UP-TO-DATE
> Task :shared_preferences_android:compileDebugAidl NO-SOURCE
> Task :url_launcher_android:preBuild UP-TO-DATE
> Task :url_launcher_android:preDebugBuild UP-TO-DATE
> Task :url_launcher_android:compileDebugAidl NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :flutter_secure_storage:packageDebugRenderscript NO-SOURCE
> Task :fluttertoast:packageDebugRenderscript NO-SOURCE
> Task :share_plus:packageDebugRenderscript NO-SOURCE
> Task :shared_preferences_android:packageDebugRenderscript NO-SOURCE
> Task :url_launcher_android:packageDebugRenderscript NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :flutter_secure_storage:writeDebugAarMetadata UP-TO-DATE
> Task :fluttertoast:writeDebugAarMetadata UP-TO-DATE
> Task :share_plus:writeDebugAarMetadata UP-TO-DATE
> Task :shared_preferences_android:writeDebugAarMetadata UP-TO-DATE
> Task :url_launcher_android:writeDebugAarMetadata UP-TO-DATE
> Task :app:checkDebugAarMetadata UP-TO-DATE
> Task :app:cleanMergeDebugAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:cleanMergeDebugAssets'.
> java.io.IOException: Unable to delete directory '/Users/satan/Library/github/ToDo-App/build/app/intermediates/incremental/mergeDebugAssets'
    Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
    - /Users/satan/Library/github/ToDo-App/build/app/intermediates/incremental/mergeDebugAssets/merger.xml

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 5s
10 actionable tasks: 2 executed, 8 up-to-date

[10:34:15]: Permission denied @ rb_sysopen - ./fastlane/README.md
[10:34:15]: Couldn't save fastlane documentation at path '/Users/satan/Library/github/ToDo-App/android/fastlane/README.md', make sure you have write access to the containing directory.
[10:34:15]: Permission denied @ rb_sysopen - ./fastlane/report.xml
[10:34:15]: Couldn't save report.xml at path '/Users/satan/Library/github/ToDo-App/android/fastlane/report.xml', make sure you have write access to the containing directory.

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 💥   | test             | 5           |
+------+------------------+-------------+

[10:34:15]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': [!] Exit status of command '/Users/satan/Library/github/ToDo-App/android/gradlew test -p .' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
> Task :app:compileFlutterBuildDebug
> Task :app:packLibsflutterBuildDebug UP-TO-DATE
> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :flutter_secure_storage:preBuild UP-TO-DATE
> Task :flutter_secure_storage:preDebugBuild UP-TO-DATE
> Task :flutter_secure_storage:compileDebugAidl NO-SOURCE
> Task :fluttertoast:preBuild UP-TO-DATE
> Task :fluttertoast:preDebugBuild UP-TO-DATE
> Task :fluttertoast:compileDebugAidl NO-SOURCE
> Task :share_plus:preBuild UP-TO-DATE
> Task :share_plus:preDebugBuild UP-TO-DATE
> Task :share_plus:compileDebugAidl NO-SOURCE
> Task :shared_preferences_android:preBuild UP-TO-DATE
> Task :shared_preferences_android:preDebugBuild UP-TO-DATE
> Task :shared_preferences_android:compileDebugAidl NO-SOURCE
> Task :url_launcher_android:preBuild UP-TO-DATE
> Task :url_launcher_android:preDebugBuild UP-TO-DATE
> Task :url_launcher_android:compileDebugAidl NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :flutter_secure_storage:packageDebugRenderscript NO-SOURCE
> Task :fluttertoast:packageDebugRenderscript NO-SOURCE
> Task :share_plus:packageDebugRenderscript NO-SOURCE
> Task :shared_preferences_android:packageDebugRenderscript NO-SOURCE
> Task :url_launcher_android:packageDebugRenderscript NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :flutter_secure_storage:writeDebugAarMetadata UP-TO-DATE
> Task :fluttertoast:writeDebugAarMetadata UP-TO-DATE
> Task :share_plus:writeDebugAarMetadata UP-TO-DATE
> Task :shared_preferences_android:writeDebugAarMetadata UP-TO-DATE
> Task :url_launcher_android:writeDebugAarMetadata UP-TO-DATE
> Task :app:checkDebugAarMetadata UP-TO-DATE
> Task :app:cleanMergeDebugAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:cleanMergeDebugAssets'.
> java.io.IOException: Unable to delete directory '/Users/satan/Library/github/ToDo-App/build/app/intermediates/incremental/mergeDebugAssets'
    Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
    - /Users/satan/Library/github/ToDo-App/build/app/intermediates/incremental/mergeDebugAssets/merger.xml

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 5s
10 actionable tasks: 2 executed, 8 up-to-date

        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `sh'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/helper/gradle_helper.rb:32:in `trigger'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/actions/gradle.rb:60:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        from Fastfile:21:in `block (2 levels) in parsing_binding'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
        from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.2/bin/fastlane:23:in `<top (required)>'
        from /usr/local/bin/fastlane:23:in `load'
        from /usr/local/bin/fastlane:23:in `<top (required)>'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.11/lib/bundler/cli/exec.rb:58:in `load'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.11/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.11/lib/bundler/cli/exec.rb:23:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.11/lib/bundler/cli.rb:483:in `exec'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.11/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.11/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.11/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.11/lib/bundler/cli.rb:31:in `dispatch'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.11/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.11/lib/bundler/cli.rb:25:in `start'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.11/exe/bundle:48:in `block in <top (required)>'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.11/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.11/exe/bundle:36:in `<top (required)>'
        from /usr/local/bin/bundle:23:in `load'
        from /usr/local/bin/bundle:23:in `<main>' </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 12.4                                                           |
| Ruby                        | 2.6.8                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.32.1 (Apple Git-133)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 12.4 (21F79)                                             |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 13.4.1                                                         |
| Swift Version               | 5.6.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("com.listomania.listapp") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.206.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| atomos                          | 0.1.3        |
| CFPropertyList                  | 2.3.6        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| rexml                           | 3.2.5        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.92.3       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.0       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.1.0        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.3.11       |
| simctl                          | 1.6.8        |
| jwt                             | 2.4.1        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.1       |
| googleauth                      | 1.1.3        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.4.4        |
| google-apis-core                | 0.6.0        |
| google-apis-playcustomapp_v1    | 0.9.0        |
| google-apis-androidpublisher_v3 | 0.22.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.12.0       |
| google-apis-storage_v1          | 0.15.0       |
| rake                            | 12.3.3       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.36.2       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.6.1        |
| aws-partitions                  | 1.600.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.0        |
| aws-sdk-core                    | 3.131.2      |
| aws-sdk-kms                     | 1.57.0       |
| aws-sdk-s3                      | 1.114.0      |
| forwardable                     | 1.2.0        |
| logger                          | 1.3.0        |
| date                            | 2.0.0        |
| stringio                        | 0.0.2        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.0.0        |
| mutex_m                         | 0.1.0        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| io-console                      | 0.4.7        |
| fileutils                       | 1.1.0        |
| etc                             | 1.0.1        |
| libxml-ruby                     | 3.2.1        |
| psych                           | 3.1.0        |
</details>

*generated on:* **2022-06-23**
</details>

**Comment by Michael8569** [comment]
A really good post, very thankful and hopeful that you will write many more posts like this one.

**Comment by litebluetips** [comment]
I have exactly the same problem. Did anyone get a suggestion?
