### ISSUE TITLE
git add tag is not adding a tag to github repo

### ISSUE THREAD

**Issue by HassanChamseddine** [fastlane/fastlane#20415]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I have added the fastlane file to my flutter project including the add_git_tag method:
`add_git_tag(
      grouping: 'fastlane-builds',
      includes_lane: true,
      prefix: 'v',
      postfix: '-RC1',
      build_number: 25
    )`
assuming that this will create a new tag in my repo, but it didn't even though the action was successfully passed.

![Screenshot 2022-06-27 at 14 01 36](https://user-images.githubusercontent.com/97539986/175936506-8cf2df1f-f45b-4e77-9d62-2114e0fefe19.png)

![Screenshot 2022-06-27 at 14 03 14](https://user-images.githubusercontent.com/97539986/175936776-077392ca-62c3-4614-bdaf-ba2637b379a7.png)

![Screenshot 2022-06-27 at 14 02 26](https://user-images.githubusercontent.com/97539986/175936643-b36ee3e4-e845-4529-abd0-9e4e1c9cf69a.png)

##### Command executed

github action triggered on commit push 
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 12.4                                                       |
| Ruby                        | 3.1.2                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.32.1 (Apple Git-133)                         |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.206.1/libexec/bin/fastlane |
| Host                        | macOS 12.4 (21F79)                                         |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.1.2/lib                        |
| OpenSSL Version             | OpenSSL 1.1.1n  15 Mar 2022                                |
| Is contained                | false                                                      |
| Is homebrew                 | true                                                       |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
| Xcode Version               | 13.4.1                                                     |
| Swift Version               | 5.6.1                                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform(:ios)

DEVELOPER_APP_ID = ENV['DEVELOPER_APP_ID']
DEVELOPER_APP_IDENTIFIER = ENV['DEVELOPER_APP_IDENTIFIER']
PROVISIONING_PROFILE_SPECIFIER = ENV['PROVISIONING_PROFILE_SPECIFIER']
TEMP_KEYCHAIN_USER = ENV['TEMP_KEYCHAIN_USER']
TEMP_KEYCHAIN_PASSWORD = ENV['TEMP_KEYCHAIN_PASSWORD']

def delete_temp_keychain(name)
  if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
    delete_keychain(
      name: name
    )
  end
end

def create_temp_keychain(name, password)
  print('name', name, 'password', password)
  create_keychain(
    name: name,
    password: password,
    unlock: false,
    timeout: 0
  )
end

def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end

platform :ios do
  lane :closed_beta do
    keychain_name = TEMP_KEYCHAIN_USER
    keychain_password = TEMP_KEYCHAIN_PASSWORD
    # ensure_temp_keychain('fastlane_keychain_login', '!QA#ED4rf')
    ensure_temp_keychain(keychain_name, keychain_password)
    add_git_tag(
      grouping: 'fastlane-builds',
      includes_lane: true,
      prefix: 'v',
      postfix: '-RC1',
      build_number: 25
    )
    # match(
    #   type: 'appstore',
    #   app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
    #   git_basic_authorization: Base64.strict_encode64(ENV['GIT_AUTHORIZATION']),
    #   readonly: true,
    #   keychain_name: keychain_name,
    #   keychain_password: keychain_password
    # )

    # gym(
    #   configuration: 'Release',
    #   workspace: 'Runner.xcworkspace',
    #   scheme: 'Runner',
    #   export_method: 'app-store',
    #   export_options: {
    #     provisioningProfiles: {
    #       DEVELOPER_APP_ID => PROVISIONING_PROFILE_SPECIFIER
    #     }
    #   }
    # )

    # pilot(
    #   apple_id: "#{DEVELOPER_APP_ID}",
    #   app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
    #   skip_waiting_for_build_processing: false,
    #   skip_submission: true,
    #   distribute_external: false,
    #   notify_external_testers: false,
    #   ipa: './Runner.ipa'
    # )

    delete_temp_keychain(keychain_name)
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier(ENV['DEVELOPER_APP_IDENTIFIER'])
apple_id(ENV['FASTLANE_APPLE_ID'])

itc_team_id(ENV['APP_STORE_CONNECT_TEAM_ID'])
team_id(ENV['DEVELOPER_PORTAL_TEAM_ID'])
# app_identifier('***.***.*****') # The bundle identifier of your app
# apple_id('**********') # Your Apple email address

# itc_team_id('********') # App Store Connect Team ID
# team_id('**********') # Developer Portal Team ID

# For more information about the appFile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.206.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                          | Version | Update-Status      |
| ------------------------------- | ------- | ------------------ |
| fastlane-plugin-versioning      | 0.5.0   | 🚫 Update available |
| fastlane-plugin-flutter_version | 1.1.15  | ✅ Up-To-Date       |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.7        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.92.3       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.0       |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.3.11       |
| simctl                          | 1.6.8        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.1       |
| googleauth                      | 1.1.3        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.5.0        |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-androidpublisher_v3 | 0.21.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.14.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.36.2       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.6.1        |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.0        |
| aws-sdk-core                    | 3.131.1      |
| aws-sdk-kms                     | 1.57.0       |
| aws-sdk-s3                      | 1.114.0      |
| set                             | 1.0.2        |
| faraday-multipart               | 1.0.4        |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| json                            | 2.6.2        |
| jwt                             | 2.4.1        |
| aws-partitions                  | 1.598.0      |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.1        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.1        |
| uri                             | 0.11.0       |
| openssl                         | 3.0.0        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.0        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.2        |
| net-http                        | 0.2.0        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.11       |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.3        |
| fastlane-plugin-versioning      | 0.5.0        |
| fastlane-plugin-flutter_version | 1.1.15       |
</details>

*generated on:* **2022-06-27**
</details> </pre>
</details>

**Comment by crazymanish** [comment]
Hi @HassanChamseddine 

When you create a git-tag, then it tag will be created in the local git-checkout code, and you need to do **git-push tag** to see that tag in remote branch/git-repo 

so your code should be something like this:

```ruby
add_git_tag(
      grouping: 'fastlane-builds',
      includes_lane: true,
      prefix: 'v',
      postfix: '-RC1',
      build_number: 25
    )
    
push_to_git_remote # this will git-push the above newly created local git-tag
