### ISSUE TITLE
Error with multiple jvmargs parameters with gradle

### ISSUE THREAD

**Issue by joseFromis** [fastlane/fastlane#20427]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I am trying to use gradle plugin in that way:

gradle(
    task: "jacocoFullReport",
    flags: "--stacktrace",
    system_properties: {
      "org.gradle.jvmargs" => "-Xmx4g -XX:MaxPermSize=2048m -XX:+UseParallelGC -XX:+HeapDumpOnOutOfMemoryError",
      "org.gradle.parallel" => true,
      "org.gradle.configureondemand" => true,
      "org.gradle.caching" => true,
      "file.encoding" => "UTF-8"
    }

Then I get this error:
invalid option: -XX:MaxPermSize=2048m

It seems fastlane only use the first parameter.

### Environment

| Key                         | Value                                                            |
| --------------------------- | ---------------------------------------------------------------- |
| OS                          | debian_based bullseye/sid                                        |
| Ruby                        | 2.7.2                                                            |
| Bundler?                    | false                                                            |
| Git                         | git version 2.36.1                                               |
| Installation Source         | /opt/hostedtoolcache/Ruby/2.7.2/x64/bin/fastlane                 |
| Host                        | Ubuntu 20.04.4 LTS debian_based bullseye/sid (5.13.0-[103](https://github.com/santander-group-europe/alm-fastlane-framework/runs/7149770381?check_suite_focus=true#step:14:104)1-azure) |
| Ruby Lib Dir                | /opt/hostedtoolcache/Ruby/2.7.2/x64/lib                          |
| OpenSSL Version             | OpenSSL 1.1.1f  31 Mar 2020                                      |
| Is contained                | false                                                            |
| Is homebrew                 | false                                                            |
| Is installed via Fabric.app | false                                                            |
### System Locale
| Variable | Value   |   |
| -------- | ------- | - |
| LANG     | C.UTF-8 | ✅ |
| LC_ALL   |         |   |
| LANGUAGE |         |   |

**Comment by Farr69** [comment]
Unfortunately parameter does not getting applied. I added jvmArguments logging to ToolingApiInvoker.java runTasks method. Gradle plugin 5.4.1, MacOS.
