### ISSUE TITLE
Deliver: waiting for screenshots to appear before uploading. This is unlikely to be recovered unless it's 503 error

### ISSUE THREAD

**Issue by Banck** [fastlane/fastlane#20423]
The deliver lane stuck on upload screenshots with the log I attached bellow.
<details>
  <summary> Lane </summary>

```
lane :send_to_review do
    generate_api_key
    deliver(
      app_identifier: "{bundle_id}",
      skip_binary_upload: true,
      run_precheck_before_submit: false,
      submit_for_review: true,
      automatic_release: true,
      reject_if_possible: true,
      force: true,
      price_tier: 0,
      overwrite_screenshots: true,
      metadata_path: "./config/appstore/metadata",
      screenshots_path: "./config/appstore/screenshots",
      submission_information: {
         add_id_info_uses_idfa: false,
         content_rights_has_rights: true,
         content_rights_contains_third_party_content: true   
         },
      app_rating_config_path: "./config/appstore/metadata/age_rating_config.json"
    )
```
  </details>

<details>
  <summary> Log </summary>

[14:14:17]: Creating authorization token for App Store Connect API
...
[14:15:01]: Uploaded './config/appstore/screenshots/en-US/1_IPAD_PRO_3GEN_129_1.PNG'... (3.190861 secs)
```

Waiting for screenshots to appear before uploading. This is unlikely to be recovered unless it's 503 error. error="Authentication credentials are missing or invalid. - Provide a properly configured and signed bearer token, and make sure that it has not expired. Learn more about Generating Tokens for API Requests https://developer.apple.com/go/?id=api-generating-tokens"

Waiting for screenshots to appear before uploading. This is unlikely to be recovered unless it's 503 error. error="Authentication credentials are missing or invalid. - Provide a properly configured and signed bearer token, and make sure that it has not expired. Learn more about Generating Tokens for API Requests https://developer.apple.com/go/?id=api-generating-tokens"

Waiting for screenshots to appear before uploading. This is unlikely to be recovered unless it's 503 error. error="Authentication credentials are missing or invalid. - Provide a properly configured and signed bearer token, and make sure that it has not expired. Learn more about Generating Tokens for API Requests https://developer.apple.com/go/?id=api-generating-tokens"

....
```
</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 12.4                                                       |
| Ruby                        | 3.1.2                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.32.1 (Apple Git-133)                         |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.206.2/libexec/bin/fastlane |
| Host                        | macOS 12.4 (21F79)                                         |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.1.2/lib                        |
| OpenSSL Version             | OpenSSL 1.1.1n  15 Mar 2022                                |
| Is contained                | false                                                      |
| Is homebrew                 | true                                                       |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode-13.4.1.app/Contents/Developer/         |
| Xcode Version               | 13.4.1                                                     |
| Swift Version               | 5.6.1                                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | ru_RU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
lane :test do
  analyze_commits(match: 'v*')
  notes = conventional_changelog
  puts(notes)
end

lane :publish do
  is_releasable = analyze_commits(match: 'v*')

  unless is_releasable
    UI.message('Nothing to release')
    next
  end

  next_version = lane_context[SharedValues::RELEASE_NEXT_VERSION]
  # generates release notes for this version
  notes = conventional_changelog(
    order: ["feat", "fix", "docs"]
  )

  # Put down the next version - it will be taken in gemspec then
  # see .gemspec and version.rb
  code = "module Fastlane module SemanticRelease VERSION = \"#{next_version}\" end end"
  filepath = "../lib/fastlane/plugin/semantic_release/version.rb"
  sh("echo '#{code}' > #{filepath}")

  filename = "fastlane-plugin-semantic_release-#{next_version}.gem"
  tag = "v#{next_version}"

  sh("rake build")
  sh("gem push ../pkg/#{filename}")

  add_git_tag(tag: tag)
  push_git_tags

  set_github_release(
    repository_name: "xotahal/fastlane-plugin-semantic_release",
    api_token: ENV["GH_TOKEN"],
    name: next_version,
    tag_name: tag,
    description: notes,
    commitish: "master",
    upload_assets: ["./pkg/#{filename}"]
  )
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.206.2 | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                           | Version | Update-Status      |
| -------------------------------- | ------- | ------------------ |
| fastlane-plugin-semantic_release | 1.0.0   | 🚫 Update available |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| public_suffix                   | 4.0.7        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.92.3       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.0       |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.3.11       |
| simctl                          | 1.6.8        |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| mini_mime                       | 1.1.2        |
| google-cloud-storage            | 1.36.2       |
| emoji_regex                     | 3.2.3        |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.0        |
| aws-sdk-kms                     | 1.57.0       |
| aws-sdk-s3                      | 1.114.0      |
| set                             | 1.0.2        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.1.0        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.22.0       |
| faraday-multipart               | 1.0.4        |
| unf_ext                         | 0.0.8.2      |
| json                            | 2.6.2        |
| jwt                             | 2.4.1        |
| webrick                         | 1.7.0        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| signet                          | 0.17.0       |
| os                              | 1.1.4        |
| memoist                         | 0.16.2       |
| googleauth                      | 1.2.0        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.2        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| google-apis-core                | 0.6.0        |
| google-apis-playcustomapp_v1    | 0.9.0        |
| google-apis-androidpublisher_v3 | 0.23.0       |
| google-apis-iamcredentials_v1   | 0.12.0       |
| google-apis-storage_v1          | 0.16.0       |
| aws-partitions                  | 1.602.0      |
| jmespath                        | 1.6.1        |
| aws-sdk-core                    | 3.131.2      |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.1        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.1        |
| uri                             | 0.11.0       |
| openssl                         | 3.0.0        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.0        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.2        |
| net-http                        | 0.2.0        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.11       |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.3        |
</details>

*generated on:* **2022-06-30**
</details>

**Comment by crazymanish** [comment]
this looks like a temp issue from Apple's side. The status page is showing everything green 🤷‍♂️
https://developer.apple.com/system-status/


I will recommend that Please try again without any change! Should work 🤞
