### ISSUE TITLE
Is there a way to disable an xcode build phase from Fastlane?

### ISSUE THREAD

**Issue by Yourney** [fastlane/fastlane#20438]
I have an xcode project that contains a SwiftLint build phase.
I want the Fastlane CI to also run the SwiftLint, cos then we have the logging and errors more clearly 'from SwiftLint' so we can clearly see in the Dashboard that it was SwiftLint that failed.

However, SwiftLint is now executed twice on the FastLane CI ... once when the project is built, and once when the SwiftLint is executed. Is there a way to 'disable' the SwiftLint BuildPhase in xcode on Fastlane, so that SwiftLint is only executed once?? Or would the 'only' way be to do the SwiftLint in the Porject on a separate Target (which is not handled by FastLane).

Thanks very much!
Kind regards,
Wouter Wessels

**Comment by Carissa34** [comment]
Create a separate Target in xcode that only contains the SwiftLint thing. 'Problem' with that is that solution is that the SwiftLint is not automatically don on the Developers machine when he/she builds.
