### ISSUE TITLE
latest_testflight_build_number doesn't work for app extension

### ISSUE THREAD

**Issue by borut-t** [fastlane/fastlane#20439]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I have an app with two targets, one for the app and the second for push notifications.
When trying to get the latest TF build number for app extension, it fails.

##### Command executed
```ruby
build_number = latest_testflight_build_number(app_identifier: app_bundle_id) + 1  => this works
build_number = latest_testflight_build_number(app_identifier: ext_bundle_id) + 1  => this doesn't!
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> Could not find an app on App Store Connect with app_identifier: myapp-qa.notificationServiceExtension </pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 12.4                                        |
| Ruby                        | 3.0.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.32.1 (Apple Git-133)          |
| Installation Source         | ~/.rvm/gems/ruby-3.0.0/bin/fastlane         |
| Host                        | macOS 12.4 (21F79)                          |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-3.0.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.1n  15 Mar 2022                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 13.4.1                                      |
| Swift Version               | 5.6.1                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.207.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| atomos                          | 0.1.3        |
| CFPropertyList                  | 3.0.5        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| simctl                          | 1.6.8        |
| emoji_regex                     | 3.2.3        |
| tsort                           | 0.1.0        |
| set                             | 1.0.1        |
| uri                             | 0.10.1       |
| rexml                           | 3.2.5        |
| claide                          | 1.1.0        |
| public_suffix                   | 4.0.7        |
| excon                           | 0.92.3       |
| ruby2_keywords                  | 0.0.5        |
| faraday-retry                   | 1.0.3        |
| faraday-rack                    | 1.0.0        |
| faraday-patron                  | 1.0.0        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-net_http                | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-httpclient              | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.10.0       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| fastimage                       | 2.2.6        |
| json                            | 2.6.2        |
| bundler                         | 2.3.11       |
| jwt                             | 2.4.1        |
| webrick                         | 1.7.0        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| signet                          | 0.16.1       |
| os                              | 1.1.4        |
| memoist                         | 0.16.2       |
| googleauth                      | 0.17.1       |
| mini_mime                       | 1.1.2        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.2        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| google-apis-core                | 0.5.0        |
| google-apis-playcustomapp_v1    | 0.8.0        |
| google-apis-androidpublisher_v3 | 0.22.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-apis-storage_v1          | 0.15.0       |
| google-apis-iamcredentials_v1   | 0.11.0       |
| google-cloud-errors             | 1.2.0        |
| google-cloud-env                | 1.6.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.37.0       |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.0        |
| aws-partitions                  | 1.602.0      |
| jmespath                        | 1.6.1        |
| aws-sdk-core                    | 3.131.2      |
| aws-sdk-kms                     | 1.57.0       |
| aws-sdk-s3                      | 1.114.0      |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.0        |
| date                            | 3.1.0        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.0        |
| securerandom                    | 0.1.0        |
| openssl                         | 2.2.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.2        |
| io-wait                         | 0.1.0        |
| zlib                            | 1.1.0        |
| resolv                          | 0.2.0        |
| digest                          | 3.0.0        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.0        |
| net-smtp                        | 0.2.1        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.0        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.6        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.1        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| nokogiri                        | 1.13.6       |
| racc                            | 1.6.0        |
| prettyprint                     | 0.1.0        |
| pp                              | 0.1.0        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.0        |
</details>

*generated on:* **2022-07-06**
</details>

**Comment by Palmieri78759** [comment]
latest_testflight_build_number
Fetches most recent build number from TestFlight

Provides a way to have increment_build_number be based on the latest build you uploaded to iTC.
Fetches the most recent build number from TestFlight based on the version number. Provides a way to have increment_build_number be based on the latest build you uploaded to iTC.

latest_testflight_build_number	
Supported platforms	ios, mac
Author	@daveanderson
Returns	Integer representation of the latest build number uploaded to TestFlight

**Comment by borut-t** [comment]
> latest_testflight_build_number Fetches most recent build number from TestFlight
> 
> Provides a way to have increment_build_number be based on the latest build you uploaded to iTC. Fetches the most recent build number from TestFlight based on the version number. Provides a way to have increment_build_number be based on the latest build you uploaded to iTC.
> 
> latest_testflight_build_number Supported platforms ios, mac Author @daveanderson Returns Integer representation of the latest build number uploaded to TestFlight

I can read that from the documentation. And that still doesn't solve my issue.

**Comment by daveanderson** [comment]
I believe it is common for the extension and the app to use the same version number. In the past it was required.
