### ISSUE TITLE
Can't build Flutter ipa ad-hoc version

### ISSUE THREAD

**Issue by the4thfloor** [fastlane/fastlane#20441]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

With `flutter build ipa --export-method=ad-hoc` you can create an ad-hoc version of a Flutter app. 

This works fine except when I do this with Fastlane. Then I get an `exportArchive: The data couldn’t be read because it isn’t in the correct format.` error.

Steps to reproduce:
1. run `flutter create`
2. make sure iOS signing is working
3. in the `ios` folder create a `Gemfile` with this content:  
```ruby
source "https://rubygems.org"

gem 'fastlane'
gem 'cocoapods'
```
4. run `bundle install`
5. run `bundle exec fastlane init` and select option 4 `Manual setup - manually setup your project to automate your tasks`
6. in the newly created `fastlane/Fastfile` add this lane:  
```ruby
default_platform(:ios)

platform :ios do
  desc "Submit a new Build to App Center"
  lane :appcenter do

    Dir.chdir ".." do
      sh("pod", "repo", "update")
      sh("flutter", "clean")
      sh("flutter", "build", "ipa", "--export-method=ad-hoc")
    end

  end
end
```
7. run Fastlane `bundle exec fastlane ios appcenter`

The `flutter build ipa` command will fail with `error: exportArchive: The data couldn’t be read because it isn’t in the correct format.`. But as I wrote it only fails when I run it from Fastlane.

And it gets weirder. Fastlane is able to create a `app-store` version (replace `"--export-method=ad-hoc"` with `"--export-method=app-store"`).

Why can't Fastlane create an `ad-hoc` version?

##### Complete output when running fastlane, including the stack trace and command used

`--capture_output` (`bundle exec fastlane ios appcenter --capture_output`) does nothing so I copied the output manually.

<details>
  <pre>
[14:23:41]: [32m------------------------------[0m
[14:23:41]: [32m--- Step: default_platform ---[0m
[14:23:41]: [32m------------------------------[0m
[14:23:41]: [32mDriving the lane 'ios appcenter' 🚀[0m
[14:23:41]: [32m-----------------------------[0m
[14:23:41]: [32m--- Step: pod repo update ---[0m
[14:23:41]: [32m-----------------------------[0m
[14:23:41]: [36m$ pod repo update[0m
[14:23:42]: ▸ [35mUpdating spec repo `trunk`[0m
[14:23:42]: [32m---------------------------[0m
[14:23:42]: [32m--- Step: flutter clean ---[0m
[14:23:42]: [32m---------------------------[0m
[14:23:42]: [36m$ flutter clean[0m
[14:23:43]: ▸ [35mChanging current working directory to: /Users/ralphbergmann/development/projects/flutter/setrex[0m
[14:23:45]: ▸ [35mCleaning Xcode workspace...                                      2.064ms[0m
[14:23:48]: ▸ [35mCleaning Xcode workspace...                                         3,1s[0m
[14:23:48]: [32m-------------------------------------------------------[0m
[14:23:48]: [32m--- Step: flutter build ipa --export-method\=ad-hoc ---[0m
[14:23:48]: [32m-------------------------------------------------------[0m
[14:23:48]: [36m$ flutter build ipa --export-method\=ad-hoc[0m
[14:23:49]: ▸ [35mChanging current working directory to: /Users/ralphbergmann/development/projects/flutter/setrex[0m
[14:23:49]: ▸ [35mRunning "flutter pub get" in setrex...                             411ms[0m
[14:23:52]: ▸ [35mArchiving kmb.systems.adag.app.setrex...[0m
[14:23:52]: ▸ [35mAutomatically signing iOS for device deployment using specified development team in Xcode project: G23X3LUX5Y[0m
[14:24:21]: ▸ [35mRunning Xcode build...[0m
[14:24:21]: ▸ [35mXcode archive done.                                         29,2s[0m
[14:24:22]: ▸ [35mBuilt /Users/ralphbergmann/development/projects/flutter/setrex/build/ios/archive/Runner.xcarchive.[0m
[14:24:22]: ▸ [35m💪 Building with sound null safety 💪[0m
[14:24:26]: ▸ [35mBuilding ad-hoc IPA...                                              4,0s[0m
[14:24:26]: ▸ [35mEncountered error while creating the IPA:[0m
[14:24:26]: ▸ [35merror: exportArchive: The data couldn’t be read because it isn’t in the correct format.[0m
[14:24:26]: ▸ [35mTry distributing the app in Xcode: "open /Users/ralphbergmann/development/projects/flutter/setrex/build/ios/archive/Runner.xcarchive"[0m

+------+-------------------------------------------+-------------+
|                        [32mfastlane summary[0m                        |
+------+-------------------------------------------+-------------+
| Step | Action                                    | Time (in s) |
+------+-------------------------------------------+-------------+
| 1    | default_platform                          | 0           |
| 2    | pod repo update                           | 1           |
| 3    | flutter clean                             | 6           |
| 4    | flutter build ipa --export-method\=ad-hoc | 37          |
+------+-------------------------------------------+-------------+

[14:24:26]: [32mfastlane.tools finished successfully 🎉[0m

</pre>
</details>

### Environment

<details>
  <pre>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                                            |
| --------------------------- | -------------------------------------------------------------------------------- |
| OS                          | 12.4                                                                             |
| Ruby                        | 2.6.8                                                                            |
| Bundler?                    | true                                                                             |
| Git                         | git version 2.32.1 (Apple Git-133)                                               |
| Installation Source         | ~/development/projects/flutter/setrex/ios/.bundle/vendor/ruby/2.6.0/bin/fastlane |
| Host                        | macOS 12.4 (21F79)                                                               |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib                   |
| OpenSSL Version             | LibreSSL 2.8.3                                                                   |
| Is contained                | false                                                                            |
| Is homebrew                 | false                                                                            |
| Is installed via Fabric.app | false                                                                            |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                                      |
| Xcode Version               | 13.4.1                                                                           |
| Swift Version               | 5.6.1                                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Submit a new Build to App Center"
  lane :appcenter do

    Dir.chdir ".." do
      sh("pod", "repo", "update")
      sh("flutter", "clean")
      sh("flutter", "build", "ipa", "--export-method=ad-hoc")
    end

  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.207.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| bundler                         | 2.3.5        |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| concurrent-ruby                 | 1.1.10       |
| i18n                            | 1.10.0       |
| minitest                        | 5.16.2       |
| tzinfo                          | 2.0.4        |
| zeitwerk                        | 2.6.0        |
| activesupport                   | 6.1.6        |
| public_suffix                   | 4.0.7        |
| addressable                     | 2.8.0        |
| httpclient                      | 2.8.3        |
| json                            | 2.6.2        |
| algoliasearch                   | 1.27.5       |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.603.0      |
| aws-sigv4                       | 1.5.0        |
| jmespath                        | 1.6.1        |
| aws-sdk-core                    | 3.131.2      |
| aws-sdk-kms                     | 1.57.0       |
| aws-sdk-s3                      | 1.114.0      |
| babosa                          | 1.0.4        |
| claide                          | 1.1.0        |
| fuzzy_match                     | 2.0.4        |
| nap                             | 1.1.0        |
| netrc                           | 0.11.0       |
| ffi                             | 1.15.5       |
| ethon                           | 0.15.0       |
| typhoeus                        | 1.4.0        |
| cocoapods-core                  | 1.11.3       |
| cocoapods-deintegrate           | 1.0.5        |
| cocoapods-downloader            | 1.6.3        |
| cocoapods-plugins               | 1.0.0        |
| cocoapods-search                | 1.0.1        |
| cocoapods-trunk                 | 1.6.0        |
| cocoapods-try                   | 1.2.0        |
| colored2                        | 3.1.2        |
| escape                          | 0.0.4        |
| fourflusher                     | 2.3.1        |
| gh_inspector                    | 1.1.3        |
| molinillo                       | 0.8.0        |
| ruby-macho                      | 2.5.1        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| cocoapods                       | 1.11.3       |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.92.3       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.0.0        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.0       |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| jwt                             | 2.4.1        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.2.0        |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.7.0        |
| google-apis-androidpublisher_v3 | 0.24.0       |
| google-apis-playcustomapp_v1    | 0.10.0       |
| google-apis-iamcredentials_v1   | 0.13.0       |
| google-apis-storage_v1          | 0.17.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.37.0       |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
</details>

*generated on:* **2022-07-06**
</details>
</pre>
</details>

**Comment by Fuller05767** [comment]
Update the app’s build and version numbers
The default version number of the app is 1.0.0. To update it, navigate to the pubspec.yaml file and update the following line:

content_copy
version: 1.0.0+1
The version number is three numbers separated by dots, such as 1.0.0 in the example above, followed by an optional build number such as 1 in the example above, separated by a +.

Both the version and the build number can be overridden in flutter build ipa by specifying --build-name and --build-number, respectively.

In iOS, build-name uses CFBundleShortVersionString while build-number uses CFBundleVersion. Read more about iOS versioning at Core Foundation Keys on the Apple Developer’s site.

You may also override the pubspec.yaml build name and number in Xcode:

Open Runner.xcworkspace in your app’s ios folder.
Select Runner in the Xcode project navigator, then select the Runner target in the settings view sidebar.
In the Identity section, update the Version to the user-facing version number you wish to publish.
In the Identity section, update the Build identifier to a unique build number used to track this build on App Store Connect. Each upload requires a unique build number.

**Comment by RalphBergmannKMB** [comment]
Ticket can be closed, see https://github.com/flutter/flutter/issues/107641

**Comment by jmagman** [comment]
Or maybe the docs need to be updated to include `gem 'sqlite3'`?  Or the `fastlane` gem should set up a dependency on it?
