### ISSUE TITLE
fastlane init failed - undefined method `include?' for nil:NilClass

### ISSUE THREAD

**Issue by emoonadev** [fastlane/fastlane#20457]
Hi,

I'm trying to init fastlane in my iOS project, when I run `fastlane init` the start work:
```
[15:40:42]: Created new folder './fastlane'.
[15:40:42]: Detected an iOS/macOS project in the current directory: 'MyProject.xcworkspace'
[15:40:42]: -----------------------------
[15:40:42]: --- Welcome to fastlane 🚀 ---
[15:40:42]: -----------------------------
[15:40:42]: fastlane can help you with all kinds of automation for your mobile app
[15:40:42]: We recommend automating one task first, and then gradually automating more over time
[15:40:42]: What would you like to use fastlane for?
1. 📸  Automate screenshots
2. 👩‍✈️  Automate beta distribution to TestFlight
3. 🚀  Automate App Store distribution
4. 🛠  Manual setup - manually setup your project to automate your tasks
?  3
[15:40:48]: ----------------------------------------------------------
[15:40:48]: --- Setting up fastlane for iOS App Store distribution ---
[15:40:48]: ----------------------------------------------------------
[15:40:48]: Parsing your local Xcode project to find the available schemes and the app identifier
Select Scheme: 
1. My First App
2. My Second App
3. My Third App
```

Then after choosing app I need to login:

```
[15:41:04]: --------------------------------
[15:41:04]: --- Login with your Apple ID ---
[15:41:04]: --------------------------------
[15:41:04]: To use App Store Connect and Apple Developer Portal features as part of fastlane,
[15:41:04]: we will ask you for your Apple ID username and password
[15:41:04]: This is necessary for certain fastlane features, for example:
[15:41:04]: 
[15:41:04]: - Create and manage your provisioning profiles on the Developer Portal
[15:41:04]: - Upload and manage TestFlight and App Store builds on App Store Connect
[15:41:04]: - Manage your App Store Connect app metadata and screenshots
[15:41:04]: 
[15:41:04]: Your Apple ID credentials will only be stored in your Keychain, on your local machine
[15:41:04]: For more information, check out
[15:41:04]: 	https://github.com/fastlane/fastlane/tree/master/credentials_manager
[15:41:04]: 
[15:41:04]: Please enter your Apple ID developer credentials
[15:41:04]: Apple ID Username:
myAppleEmail@gmail.com
[15:41:10]: Logging in...
[15:41:15]: ✅  Logging in with your Apple ID was successful
[15:41:15]: Checking if the app 'mypackage.name' exists in your Apple Developer Portal...
[15:41:16]: ✅  Your app 'mypackage.name' is available in your Apple Developer Portal
[15:41:16]: Checking if the app 'mypackage.name' exists on App Store Connect...
[15:41:16]: --------------------
[15:41:16]: fastlane init failed
[15:41:16]: --------------------
[15:41:16]: undefined method `include?' for nil:NilClass

      if body["messages"] && body["messages"]["error"].include?("Forbidden")
                                                      ^^^^^^^^^
[15:41:16]: Something failed while running `fastlane init`
```

What's mean:

```
[15:41:16]: fastlane init failed
[15:41:16]: --------------------
[15:41:16]: undefined method `include?' for nil:NilClass

      if body["messages"] && body["messages"]["error"].include?("Forbidden")
                                                      ^^^^^^^^^

```

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 12.4                                                       |
| Ruby                        | 3.1.2                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.32.1 (Apple Git-133)                         |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.207.0/libexec/bin/fastlane |
| Host                        | macOS 12.4 (21F79)                                         |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.1.2/lib                        |
| OpenSSL Version             | OpenSSL 1.1.1n  15 Mar 2022                                |
| Is contained                | false                                                      |
| Is homebrew                 | true                                                       |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
| Xcode Version               | 13.4.1                                                     |
| Swift Version               | 5.6.1                                                      |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.207.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.7        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.92.3       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.0       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.3.11       |
| simctl                          | 1.6.8        |
| jwt                             | 2.4.1        |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.2.0        |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| mini_mime                       | 1.1.2        |
| google-cloud-storage            | 1.37.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.6.1        |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.0        |
| aws-sdk-core                    | 3.131.2      |
| aws-sdk-kms                     | 1.57.0       |
| aws-sdk-s3                      | 1.114.0      |
| set                             | 1.0.2        |
| json                            | 2.6.2        |
| webrick                         | 1.7.0        |
| httpclient                      | 2.8.3        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.2        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| google-apis-core                | 0.7.0        |
| google-apis-playcustomapp_v1    | 0.10.0       |
| google-apis-androidpublisher_v3 | 0.25.0       |
| google-apis-iamcredentials_v1   | 0.13.0       |
| google-apis-storage_v1          | 0.18.0       |
| aws-partitions                  | 1.604.0      |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.1        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.1        |
| uri                             | 0.11.0       |
| openssl                         | 3.0.0        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.0        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.2        |
| net-http                        | 0.2.0        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.11       |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.3        |
</details>

*generated on:* **2022-07-12**
</details>

**Comment by zbarbuto** [comment]
#20444

**Comment by emoonadev** [comment]
@zbarbuto I already saw that feed, but there is no solution?
