### ISSUE TITLE
Warning: Category 'MZGenre.Lifestyle' from iTunesConnect has been deprecated. Please replace with 'LIFESTYLE'

### ISSUE THREAD

**Issue by timbms** [fastlane/fastlane#20456]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
#16797 resurfaces. 
The following warnings are generated

```
[08:07:01]: Category 'MZGenre.Lifestyle' from iTunesConnect has been deprecated. Please replace with 'LIFESTYLE'
[08:07:01]: Category 'MZGenre.Utilities' from iTunesConnect has been deprecated. Please replace with 'UTILITIES'

```
##### Command executed
fastlane deliver

##### Complete output when running fastlane, including the stack trace and command used

<details>
fastlane --capture_output deliver crashes with an error:
  <pre> 
/Users/tms/.gem/gems/tty-screen-0.8.1/lib/tty/screen.rb:216:in `ioctl?': undefined method `ioctl' for #<StringIO:0x000000010a24dd20> (NoMethodError)

        ($stdout.ioctl(control, buf) >= 0) ||
                ^^^^^^
	from /Users/tms/.gem/gems/tty-screen-0.8.1/lib/tty/screen.rb:199:in `size_from_ioctl'
	from /Users/tms/.gem/gems/tty-screen-0.8.1/lib/tty/screen.rb:64:in `size'
	from /Users/tms/.gem/gems/tty-screen-0.8.1/lib/tty/screen.rb:76:in `width'
	from /Users/tms/.gem/gems/fastlane-2.207.0/fastlane_core/lib/fastlane_core/print_table.rb:95:in `transform_output'
	from /Users/tms/.gem/gems/fastlane-2.207.0/fastlane/lib/fastlane/plugins/plugin_manager.rb:335:in `print_plugin_information'
	from /Users/tms/.gem/gems/fastlane-2.207.0/fastlane/lib/fastlane/plugins/plugin_manager.rb:316:in `load_plugins'
	from /Users/tms/.gem/gems/fastlane-2.207.0/fastlane/lib/fastlane/commands_generator.rb:40:in `start'
	from /Users/tms/.gem/gems/fastlane-2.207.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /Users/tms/.gem/gems/fastlane-2.207.0/bin/fastlane:23:in `<top (required)>'
	from /Users/tms/.gem/bin/fastlane:25:in `load'
	from /Users/tms/.gem/bin/fastlane:25:in `<main>'
 </pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 12.4                                        |
| Ruby                        | 3.1.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.32.1 (Apple Git-133)          |
| Installation Source         | ~/.gem/bin/fastlane                         |
| Host                        | macOS 12.4 (21F79)                          |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/3.1.2/lib            |
| OpenSSL Version             | OpenSSL 1.1.1n  15 Mar 2022                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 13.4.1                                      |
| Swift Version               | 5.6.1                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.207.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-changelog  | 0.16.0  | ✅ Up-To-Date  |
| fastlane-plugin-versioning | 0.5.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| faraday-cookie_jar              | 0.0.7        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| simctl                          | 1.6.8        |
| set                             | 1.0.2        |
| rexml                           | 3.2.5        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.1.0        |
| CFPropertyList                  | 3.0.5        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.21.0       |
| public_suffix                   | 4.0.7        |
| excon                           | 0.92.3       |
| ruby2_keywords                  | 0.0.5        |
| faraday-retry                   | 1.0.3        |
| faraday-rack                    | 1.0.0        |
| faraday-patron                  | 1.0.0        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-net_http                | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-httpclient              | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.10.0       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| json                            | 2.6.2        |
| bundler                         | 2.3.11       |
| jwt                             | 2.4.1        |
| webrick                         | 1.7.0        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| signet                          | 0.16.1       |
| os                              | 1.1.4        |
| memoist                         | 0.16.2       |
| googleauth                      | 1.1.3        |
| mini_mime                       | 1.1.2        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.2        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| google-apis-core                | 0.6.0        |
| google-apis-playcustomapp_v1    | 0.9.0        |
| google-apis-androidpublisher_v3 | 0.22.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-apis-storage_v1          | 0.15.0       |
| google-apis-iamcredentials_v1   | 0.12.0       |
| google-cloud-errors             | 1.2.0        |
| google-cloud-env                | 1.6.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.36.2       |
| emoji_regex                     | 3.2.3        |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.0        |
| aws-partitions                  | 1.600.0      |
| jmespath                        | 1.6.1        |
| aws-sdk-core                    | 3.131.2      |
| aws-sdk-kms                     | 1.57.0       |
| aws-sdk-s3                      | 1.114.0      |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.1        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.1        |
| uri                             | 0.11.0       |
| openssl                         | 3.0.0        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.0        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.2        |
| net-http                        | 0.2.0        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.11       |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.3        |
| fastlane-plugin-changelog       | 0.16.0       |
| fastlane-plugin-versioning      | 0.5.1        |
</details>

*generated on:* **2022-07-12**
</details>

**Comment by Marcoside** [comment]
```
<html>
<body>
<!--StartFragment-->

UI.verbose("Updating build for export compliance status of '#{uses_encryption}'")
--
66 | +
67 | +         if uses_encryption.to_s.empty?
68 | +           message = [
69 | +             "Export compliance is required to submit",
70 | +             "Add information to the :submission_information option...",
71 | +             "  Docs: http://docs.fastlane.tools/actions/deliver/#compliance-and-idfa-settings",
72 | +             "  Example: submission_information: { export_compliance_uses_encryption: false }",
73 | +             "This can also be set in your Info.plist with key 'ITSAppUsesNonExemptEncryption'"
74 | +           ].join("\n")
75 | +           UI.user_error!(message)
76 | +         end

<!--EndFragment-->
</body>
</html>
```
