### ISSUE TITLE
`upload_to_testflight` ignores `build_number` and uses the latest Mac build instead of the latest iOS

### ISSUE THREAD

**Issue by tremblay** [fastlane/fastlane#20479]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I am running the `upload_to_testflight` command with an application that has iOS and macOS products. The latest iOS build number is 252, the latest macOS build number is 246. Running this command always results in `Waiting for processing on... app_id: xxxxxxx, app_version: 1.0, build_version: 246`, even when I specify the platform and build number.

##### Command executed

`fastlane run testflight groups:"Group Name" distribute_only:true app_platform:"ios" build_number:"252"`
note: tried build_number with and without quotes, no change to the output.
`fastlane run testflight groups:"Group Name" distribute_only:true app_platform:"ios"`
note: output is the same for this one too, except the line `Using build_number: 252` doesn't appear (which does make sense).

##### Complete output when running fastlane, including the stack trace and command used

<details>
% bundle exec fastlane run testflight groups:"Group Name" distribute_only:true app_platform:"ios" build_number:252 --verbose 
[✔] 🚀 
DEBUG [2022-07-18 17:39:08.25]: Checking if there are any plugins that should be loaded...
DEBUG [2022-07-18 17:39:08.25]: Loading 'fastlane-plugin-bugsnag' plugin
INFO [2022-07-18 17:39:08.25]: gem 'fastlane-plugin-bugsnag' is already installed
DEBUG [2022-07-18 17:39:08.26]: Loading 'fastlane-plugin-xcconfig' plugin
INFO [2022-07-18 17:39:08.26]: gem 'fastlane-plugin-xcconfig' is already installed
DEBUG [2022-07-18 17:39:08.26]: Loading 'fastlane-plugin-bugsee' plugin
INFO [2022-07-18 17:39:08.26]: gem 'fastlane-plugin-bugsee' is already installed
+--------------------------+---------+---------------------------------------------------------------+
|                                            Used plugins                                            |
+--------------------------+---------+---------------------------------------------------------------+
| Plugin                   | Version | Action                                                        |
+--------------------------+---------+---------------------------------------------------------------+
| fastlane-plugin-bugsnag  | 2.2.1   | upload_symbols_to_bugsnag, send_build_to_bugsnag              |
| fastlane-plugin-xcconfig | 2.0.0   | update_xcconfig_value, set_xcconfig_value, get_xcconfig_value |
| fastlane-plugin-bugsee   | 1.0.2   | upload_symbols_to_bugsee                                      |
+--------------------------+---------+---------------------------------------------------------------+

Successfully loaded Appfile at path '~/repo/fastlane/Appfile'
- app_identifier: 'xxxxxxx'
- itc_team_id: 'xxxxxxx'
- team_id: 'xxxxxxx'
-------
Successfully loaded Appfile at path '~/repo/fastlane/Appfile'
- app_identifier: 'xxxxxxx'
- itc_team_id: 'xxxxxxx'
- team_id: 'xxxxxxx'
-------
DEBUG [2022-07-18 17:39:08.58]: Using groups: Group Name
DEBUG [2022-07-18 17:39:08.59]: Using distribute_only: true
DEBUG [2022-07-18 17:39:08.59]: Using app_platform: ios
DEBUG [2022-07-18 17:39:08.59]: Using build_number: 252
Successfully loaded Appfile at path '~/repos/fastlane/Appfile'
- app_identifier: 'xxxxxxx'
- itc_team_id: 'xxxxxxx'
- team_id: 'xxxxxxx'
-------
Successfully loaded Appfile at path '~/repo/fastlane/Appfile'
- app_identifier: 'xxxxxxx'
- itc_team_id: 'xxxxxxx'
- team_id: 'xxxxxxx'
-------
Successfully loaded Appfile at path '~/repo/fastlane/Appfile'
- app_identifier: 'xxxxxxx'
- itc_team_id: 'xxxxxxx'
- team_id: 'xxxxxxx'
-------
Successfully loaded Appfile at path '~/repo/fastlane/Appfile'
- app_identifier: 'xxxxxxx'
- itc_team_id: 'xxxxxxx'
- team_id: 'xxxxxxx'
-------
Successfully loaded Appfile at path '~/repo/fastlane/Appfile'
- app_identifier: 'xxxxxxx'
- itc_team_id: 'xxxxxxx'
- team_id: 'xxxxxxx'
-------
Successfully loaded Appfile at path '~/repo/fastlane/Appfile'
- app_identifier: 'xxxxxxx'
- itc_team_id: 'xxxxxxx'
- team_id: 'xxxxxxx'
-------
Successfully loaded Appfile at path '~/repo/fastlane/Appfile'
- app_identifier: 'xxxxxxx'
- itc_team_id: 'xxxxxxx'
- team_id: 'xxxxxxx'
-------
Successfully loaded Appfile at path '~/repo/fastlane/Appfile'
- app_identifier: 'xxxxxxx'
- itc_team_id: 'xxxxxxx'
- team_id: 'xxxxxxx'
-------
Successfully loaded Appfile at path '~/repo/fastlane/Appfile'
- app_identifier: 'xxxxxxx'
- itc_team_id: 'xxxxxxx'
- team_id: 'xxxxxxx'
-------
Successfully loaded Appfile at path '~/repo/fastlane/Appfile'
- app_identifier: 'xxxxxxx'
- itc_team_id: 'xxxxxxx'
- team_id: 'xxxxxxx'
-------
Successfully loaded Appfile at path '~/repo/fastlane/Appfile'
- app_identifier: 'xxxxxxx'
- itc_team_id: 'xxxxxxx'
- team_id: 'xxxxxxx'
-------
Successfully loaded Appfile at path '~/repo/fastlane/Appfile'
- app_identifier: 'xxxxxxx'
- itc_team_id: 'xxxxxxx'
- team_id: 'xxxxxxx'
-------
INFO [2022-07-18 17:39:08.60]: ------------------------
INFO [2022-07-18 17:39:08.60]: --- Step: testflight ---
INFO [2022-07-18 17:39:08.60]: ------------------------
INFO [2022-07-18 17:39:08.60]: Login to App Store Connect (xxxxxxx)
Reading keychain entry, because either user or password were empty
Loading session from 'xxxxxxxxxxxxxxx'
Looking for App Store Connect Team with ID xxxxxxx
INFO [2022-07-18 17:39:10.30]: Login successful
DEBUG [2022-07-18 17:39:10.30]: App Platform (ios)
INFO [2022-07-18 17:39:10.30]: $ xar -C /var/folders/f9/bn94wk756dj9trk3v8rd2lww0000gn/T/d20220718-33664-ljrpxv -xf xxxxxxx.pkg
INFO [2022-07-18 17:39:10.75]: $ xar -C /var/folders/f9/bn94wk756dj9trk3v8rd2lww0000gn/T/d20220718-33664-zp5v24 -xf xxxxxxx.pkg
DEBUG [2022-07-18 17:39:11.18]: App identifier (xxxxxxx)
INFO [2022-07-18 17:39:13.07]: Waiting for processing on... app_id: xxxxxxx, app_version: 1.0, build_version: 246, platform: IOS
WARN [2022-07-18 17:39:14.44]: Read more information on why this build isn't showing up yet - https://github.com/fastlane/fastlane/issues/14997
INFO [2022-07-18 17:39:14.44]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 12.3.1                                                         |
| Ruby                        | 2.6.8                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.32.1 (Apple Git-133)                             |
| Installation Source         | ~/.gem/bin/fastlane                                            |
| Host                        | macOS 12.3.1 (21E258)                                          |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 13.4.1                                                         |
| Swift Version               | 5.6.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

after_all do |lane|
  if lane == :number || lane == :refresh_dsyms || lane == :promote_latest
    puts "lane is `#{lane}`, do not perform `after_all`"
  else
    increment_build_number(build_number: 1) # temporary, until we have real versions in place
    clean_build_artifacts
    push_git_tags
  end
end

lane :number do
  mac_latest = latest_testflight_build_number(platform: "osx")
  ios_latest = latest_testflight_build_number
  build_number = ((max = mac_latest > ios_latest ? mac_latest : ios_latest) + 1).to_s
  increment_build_number(build_number: build_number)
end

private_lane :send_dsyms_to_bugsnag do |options|
  download_dsyms(build_number: options[:build_number])       # Download dSYM files from App Store Connect

  bugsnag_key = "xxxxxxx"
  upload_symbols_to_bugsnag(api_key: bugsnag_key)            # Upload them to Bugsnag
end

private_lane :bugsnag do
  key = "xxxxxxx"
  upload_symbols_to_bugsnag(api_key: key)
  send_build_to_bugsnag(api_key: key)
end

platform :ios do
  before_all do |lane|
    if lane == :refresh_dsyms || lane == :promote_latest
      puts "lane is `#{lane}`, do not perform `before_all`"
    else
      number
      cert
      sigh
    end
  end

  desc "Promote the latest build to External Testers"
  lane :promote_latest do
    # TODO: validate that `latest` is in `Another Group`
    testflight(
      groups: ['Group Name'],
      distribute_only: true,
      app_platform: "ios",
      build_number: "#{latest_testflight_build_number}"
    )
  end

  desc "Push a new Lite build to the AppStore"
  lane :lite do |options|
    update_xcconfig_value(
      path: 'Shared/BuildConfig.xcconfig',
      name: 'IS_LITE_BUILD',
      value: 'YES'
    )

    # TODO: fail if `version_number` wasn't passed
    increment_version_number(version_number: options[:version_number])
    app_store

    update_xcconfig_value(
      path: 'Shared/BuildConfig.xcconfig',
      name: 'IS_LITE_BUILD',
      value: 'NO'
    )
    increment_version_number(version_number: '1.0')
  end

  desc "Push a new build the AppStore"
  private_lane :app_store do
    app_store_build

    deliver(
      submit_for_review: true,
      force: true, # skip the check for screenshots, since we usually aren't changing them
      automatic_release: false,
      submission_information: { add_id_info_uses_idfa: false }
    )

    add_git_tag(includes_lane: false)

    bugsnag
  end

  desc "Push a new build to External TestFlight"
  lane :external do |options|
    app_store_build

    testflight(
      distribute_external: true,
      groups: ['Another Group'],
      changelog: options[:changelog]
    )

    add_git_tag(includes_lane: false)

    bugsnag
  end

  desc "Push a new internal build to TestFlight"
  lane :internal do
    commit = last_git_commit
    hash = commit[:commit_hash] # long sha of commit

    build("Release")

    testflight(skip_waiting_for_build_processing: true, changelog: hash)

    add_git_tag(includes_lane: false)
  
    # bugsnag
  end

  private_lane :app_store_build do
    build("App Store")
  end

  def build(configuration)
    build_app(
      configuration: configuration,
      scheme: "xxxxxxx (iOS)",
      include_symbols: true,
      include_bitcode: true,
      export_options: {
        provisioningProfiles: {
          "xxxxxxx" => "xxxxxxx",
          "xxxxxxx" => "xxxxxxx",
          "xxxxxxx" => "xxxxxxx"
        }
      }
    )
  end

  lane :refresh_dsyms do |options|
    send_dsyms_to_bugsnag(build_number: options[:build_number])

    bugsee_token = "xxxxxxx"
    upload_symbols_to_bugsee(app_token: bugsee_token, agent_path: "./BuildTools/BugseeAgent")

    # Delete the local dSYM files
    clean_build_artifacts
  end
end

platform :mac do
  before_all do |lane|
    if lane == :refresh_dsyms || lane == :promote_latest
      puts "lane is `#{lane}`, do not perform `before_all`"
    else
      number
      cert(platform: "macos")
      sigh(platform: "macos")
    end
  end

  desc "Promote the latest build to External Testers"
  lane :promote_latest do
    testflight(
      groups: ['Group Name'],
      distribute_only: true,
      app_platform: "osx",
      build_number: "#{latest_testflight_build_number(platform: "osx")}"
    )
  end

  desc "Push a new build the AppStore"
  private_lane :app_store do |options|
    build_mac("App Store", options[:scheme])
    testflight(
      app_platform: "osx",
      distribute_external: true,
      groups: ['Another Group'],
      changelog: options[:changelog]
    )

    add_git_tag(includes_lane: false)

    bugsnag
  end

  desc "Push a new build to External TestFlight"
  lane :external do |options|
    build_mac("App Store", "xxxxxxx (macOS)")

    testflight(
      app_platform: "osx",
      distribute_external: true,
      groups: ['Another Group'],
      changelog: options[:changelog]
    )

    add_git_tag(includes_lane: false)

    bugsnag
  end

  desc "Push a new internal build to TestFlight"
  lane :internal do
    commit = last_git_commit
    hash = commit[:commit_hash] # long sha of commit

    build_mac("Release", "xxxxxxx (macOS)")

    testflight(
      app_platform: "osx",
      skip_waiting_for_build_processing: true,
      changelog: hash
    )

    add_git_tag(includes_lane: false)

    bugsnag
  end

  def build_mac(configuration, scheme)
    build_mac_app(
      configuration: configuration,
      export_method: "app-store",
      scheme: scheme,
      include_symbols: true,
      include_bitcode: true,
      export_options: {
        provisioningProfiles: {
          "xxxxxxx" => "xxxxxxx",
          "xxxxxxx" => "xxxxxxx",
          "xxxxxxx" => "xxxxxxx"
        }
      }
    )
  end

  lane :refresh_dsyms do |options|
    send_dsyms_to_bugsnag(build_number: options[:build_number])
    # no bugsee, because they don't have a mac library
    clean_build_artifacts                                      # Delete the local dSYM files
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("xxxxxxx") # The bundle identifier of your app

itc_team_id("xxxxxxx") # App Store Connect Team ID
team_id("xxxxxxx") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.207.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                   | Version | Update-Status |
| ------------------------ | ------- | ------------- |
| fastlane-plugin-bugsnag  | 2.2.1   | ✅ Up-To-Date  |
| fastlane-plugin-xcconfig | 2.0.0   | ✅ Up-To-Date  |
| fastlane-plugin-bugsee   | 1.0.2   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| bundler                         | 1.17.2       |
| etc                             | 1.0.1        |
| forwardable                     | 1.2.0        |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| public_suffix                   | 4.0.7        |
| addressable                     | 2.8.0        |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.608.0      |
| aws-sigv4                       | 1.5.0        |
| jmespath                        | 1.6.1        |
| aws-sdk-core                    | 3.131.3      |
| aws-sdk-kms                     | 1.58.0       |
| aws-sdk-s3                      | 1.114.0      |
| babosa                          | 1.0.4        |
| claide                          | 1.1.0        |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.92.3       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.0.0        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.0       |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.4.1        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.2.0        |
| httpclient                      | 2.8.3        |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.7.0        |
| google-apis-androidpublisher_v3 | 0.25.0       |
| google-apis-playcustomapp_v1    | 0.10.0       |
| google-apis-iamcredentials_v1   | 0.13.0       |
| google-apis-storage_v1          | 0.18.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.37.0       |
| json                            | 2.6.2        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| fastlane-plugin-bugsee          | 1.0.2        |
| rchardet                        | 1.8.0        |
| git                             | 1.11.0       |
| xml-simple                      | 1.1.9        |
| fastlane-plugin-bugsnag         | 2.2.1        |
| fastlane-plugin-xcconfig        | 2.0.0        |
</details>

*generated on:* **2022-07-18**
</details>

**Comment by tremblay** [comment]
I was able to fix this issue by deleting a stray `.pkg` file that was sitting in my repo (from a recent macOS build). However, it still seems like a bug to have `app_platform:"ios" build_number:252` get overridden just because there's a build artifact in the repo.

**Comment by getaaron** [comment]
It's hard to understand how it'd happen (if there's an IPA)

looking at [`upload_to_testflight.rb`](https://github.com/fastlane/fastlane/blob/e8d30e3494024b6d4ee81bf21448991779ca278d/fastlane/lib/fastlane/actions/upload_to_testflight.rb) and [`pilot/build_manager.rb`](https://github.com/fastlane/fastlane/blob/e8d30e3494024b6d4ee81bf21448991779ca278d/pilot/lib/pilot/build_manager.rb) it seems like the IPA file would always win if it could be found

does anything jump out to you if you read through the code?

**Comment by tremblay** [comment]
So my particular use case is for just adding a group to a build that has already been uploaded, meaning that there's actually no IPA or PKG to upload in this scenario.

**Comment by getaaron** [comment]
Oh I see

So I believe the problem is here:

https://github.com/fastlane/fastlane/blob/e8d30e3494024b6d4ee81bf21448991779ca278d/pilot/lib/pilot/build_manager.rb#L101-L110

for the `:ipa` and `:pkg` branches of the conditional, it _should_ only run if `distribute_only` is false but the current code doesn't check that, it just seems to implicitly assume if an ipa/pkg is present it should use that

I probably won't have bandwidth to fix it soon but I'd be happy to review & merge a PR if you'd like to take a stab at it?

**Comment by tremblay** [comment]
Will do, thanks!!
