### ISSUE TITLE
get_cert_info: path name contains null byte 

### ISSUE THREAD

**Issue by ff-ahumberston** [fastlane/fastlane#20489]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Receiving 'ERROR [2022-07-20 09:52:59.80]: get_cert_info: path name contains null byte' 

##### Command executed
bundle exec fastlane match development --team_id xxx --username yyy@zzz.com --verbose 

##### Complete output when running fastlane, including the stack trace and command used
Output trimmed, as very long - 
INFO [2022-07-20 09:57:24.36]: 🔓  Decrypted 'AdHoc_com.xxx.yyy.mobileprovision'
INFO [2022-07-20 09:57:24.36]: 🔓  Successfully decrypted certificates repo
INFO [2022-07-20 09:57:24.36]: Verifying that the certificate and profile are still valid on the Dev Portal...
Reading keychain entry, because either user or password were empty
Loading session from '/Users/aaaa/.fastlane/spaceship/xxx@yyy.com/cookie'
Available session is not valid any more. Continuing with normal login.
<snip>
+-------------------+-------------------------------------------------+
|                        Installed Certificate                        |
+-------------------+-------------------------------------------------+
| User ID           | 12345                                      |
| Common Name       | Apple Development: Acme User |
| Organisation Unit | 54321                                      |
| Organisation      | Acme                        |
| Country           | US                                              |
| Start Datetime    | 2022-07-19 22:22:39 UTC                         |
| End Datetime      | 2023-07-19 22:22:38 UTC                         |
+-------------------+-------------------------------------------------+

INFO [2022-07-20 09:58:29.75]: Installing provisioning profile...
WARN [2022-07-20 09:58:34.18]: Setting environment variable 'sigh_com.xxx.*_development' to '1cb624e7-f42b-45ab-98b1-57246599e76c'
WARN [2022-07-20 09:58:34.18]: Setting environment variable 'sigh_com.xxx.*_development_team-id' to '9H95BT9Q8V'
ERROR [2022-07-20 09:58:34.18]: get_cert_info: path name contains null byte
WARN [2022-07-20 09:58:34.18]: Setting environment variable 'sigh_com.xxx.*_development_certificate-name' to ''
WARN [2022-07-20 09:58:34.18]: Setting environment variable 'sigh_com.xxx.*_development_profile-name' to 'match Development com.fullfat.*'
WARN [2022-07-20 09:58:34.18]: Setting environment variable 'sigh_com.xxx.*_development_profile-path' to '/Users/aaaa/Library/MobileDevice/Provisioning Profiles/1cb624e7-f42b-45ab-98b1-57246599e76c.mobileprovision'

<details>
  <pre>Receiving the error path name contains null byte, looks to be connected to 
   Setting environment variable 'sigh_com.xxx.*_development_certificate-name' to ''
 </pre>
</details>

**Comment by getaaron** [comment]
I believe it's emitted by the `File.exists?` check, e.g.

```ruby
irb(main):007:0> File.exist?("/etc/hosts\x00")
Traceback (most recent call last):
	20: from /Users/aaron/.rbenv/versions/2.7.4/bin/irb:23:in `<main>'
	19: from /Users/aaron/.rbenv/versions/2.7.4/bin/irb:23:in `load'
	18: from /Users/aaron/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
	 1: from (irb):7:in `<main>'
```

**Comment by Dids** [comment]
Also getting this when running `bundle exec fastlane run match init`, however the `fastlane/Matchfile` never gets created, which I'm assuming is from this error.

**Comment by carlosen14** [comment]
i dont know on which version this fix will be released, but still happening on 2.208.0 when running `bundle exec fastlane match appstoreplacing`

**Comment by getaaron** [comment]
@carlosen14 thanks for the ping, we'll try to get a release out later tonight if we can swing it

**Comment by carlosen14** [comment]
Great, just was a comment.
________________________________

**Comment by pedromassango** [comment]
This happens when you use a EMPTY STRING as your keychain password when prompted by Fastlane. You can fix by providing a non-empty string, by that I mean DON'T just press enter when prompted to type a password for the keychain.
