### ISSUE TITLE
Fastlane with iOS Extension

### ISSUE THREAD

**Issue by benjitusk** [fastlane/fastlane#20482]
I'm having a similar issue as #12826, where OP was having trouble configuring profiles for a project that has extensions, but even after following the steps prescribed in this answer, I am still coming up with errors (see after the quoted comment for errors):

[@]yusuftor good for you. I'm managing certs with match and just found a solution that seems to work so far, based on https://github.com/fastlane/fastlane/issues/8563

```
  desc "Prepare the iOS app for dev or build"
  lane :prepare do
    produce(
        app_identifier: "com.x.mobile.OneSignalNotificationServiceExtension",
        app_name: "x OneSignalNotificationServiceExtension",
        skip_itc: true
    )
    match(
        app_identifier: ["com.x.mobile","com.x.mobile.OneSignalNotificationServiceExtension"],
        type: "development",
    )
    match(
        app_identifier: ["com.x.mobile","com.x.mobile.OneSignalNotificationServiceExtension"],
        type: "appstore",
    )
    cocoapods
  end
```

Hope this will be helpful

_Originally posted by @slorber in https://github.com/fastlane/fastlane/issues/12826#issuecomment-402993080_

Errors:
`❌  error: "Yeshivat Torat Shraga" requires a provisioning profile with the Associated Domains, App Groups, App Attest, and Push Notifications features. Select a provisioning profile in the Signing & Capabilities editor. (in target 'Yeshivat Torat Shraga' from project 'Yeshivat Torat Shraga')`

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 13.0                                                           |
| Ruby                        | 2.6.10                                                         |
| Bundler?                    | true                                                           |
| Git                         | git version 2.32.1 (Apple Git-133)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 13.0 (22A5295i)                                          |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode-beta.app/Contents/Developer/               |
| Xcode Version               | 14.0                                                           |
| Swift Version               | 5.7                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  # desc "upload beta"
  # lane :beta do
  #   build_app(scheme: "Yeshivat Torat Shraga")
  #   upload
  # end

  # desc "upload release"
  # lane :upload do
  #   upload_to_testflight(username: "benjitusk1@gmail.com", skip_waiting_for_build_processing: true)
  # end

  desc "Set the Xcode version to be used"
  lane :set_xcode_version do
    xcversion(version: "13.3.1")
  end

  desc "Load ASC API Key information to use in subsequent lanes"
  lane :load_asc_api_key do
    app_store_connect_api_key(
      # The api key can be found in the App Store Connect API UI
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      # key_content: ENV["ASC_KEY"],
      key_filepath: "~/Downloads/asc-key.p8",
      in_house: false # detecting this via ASC private key not currently supported
    )
  end

  desc "Bump build number based on most recent TestFlight build number"
  lane :fetch_and_increment_build_number do
    #fetch read your app identifier defined in your Appfile
    app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
    api_key = lane_context[SharedValues::APP_STORE_CONNECT_API_KEY]

    current_version = get_version_number(
      target: "Yeshivat Torat Shraga" # replace with your main target, required if you have more than one non-test target
    )
    latest_build_number = latest_testflight_build_number(
      api_key: api_key,
      version: current_version,
      app_identifier: app_identifier
    )
    increment_build_number(
      build_number: (latest_build_number.to_f + 1),
    )
  end
 
  desc "Check certs and profiles"
  lane :prepare_signing do |options|
    app_id = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
    api_key = lane_context[SharedValues::APP_STORE_CONNECT_API_KEY]
 
    # profile_name = "App Provisioning Profile" # replace with the name of your existing profile, or define a name for the profile that fastlane will create if it's not found

    create_keychain(
        name: "actiontest_keychain",
        password: "meow",
        default_keychain: false,
        unlock: true,
        timeout: 3600,
        lock_when_sleeps: false
    )

    produce(
      app_identifier: app_id,
      app_name: "Yeshivat Torat Shraga",
      skip_itc: true,
      enable_services: {
        "associated_domains": "on",
        "app_group": "on",
        "app_attest": "on",
        "push_notification": "on",
      }
    )
    produce(
      app_identifier: app_id + ".NotificationService",
      app_name: "Yeshivat Torat Shraga Notification Service",
      skip_itc: true,
      enable_services: {
        "app_group": "on",
      }
    )

    match(
      type: "appstore",
      app_identifier: [app_id, app_id + ".NotificationService"],
      # MATCH_GIT_BASIC_AUTHORIZATION should be formatted as follows:
      # plaintext_username:plaintext_auth_token
      git_basic_authorization: Base64.strict_encode64(ENV["MATCH_GIT_BASIC_AUTHORIZATION"]),
      keychain_name: "actiontest_keychain",
      keychain_password: "meow",
    )
  end
 
  desc "Build the iOS app for release"
  lane :build_release do |options|
    app_id = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
    # app_profile_name = "match AppStore " + app_identifier
    # profile_name = "App Provisioning Profile" # the name of the profile to use for the build
    output_name = "YTS" # specify the name of the .ipa file to generate
    export_method = "app-store" # specify the export method
    compile_bitcode = true # specify whether to enable bitcode
 
    # turn off automatic signing during build so correct code signing identity is guaranteed to be used
    update_code_signing_settings(
      use_automatic_signing: false,
      targets: ["Yeshivat Torat Shraga", "NotificationModifier"], # specify which targets to update code signing settings for
      code_sign_identity: "Apple Distribution", # replace with name of code signing identity if different
      # bundle_identifier: app_identifier,
      build_configurations: ["Release"] # only toggle code signing settings for Release configurations
    )

    settings_to_override = {
      # :BUNDLE_IDENTIFIER => "com.reesedevelopment.YTS", # Might need to be removed
      # :PROVISIONING_PROFILE_SPECIFIER => app_profile_name,
      # Use BUILDCACHE override compiler paths to ensure that the correct compiler paths are used.
      :CC => "clang",
      :CPLUSPLUS => "clang++",
      :LD => "clang",
      :LDPLUSPLUS => "clang++",
    }

 
    # build the app
    gym(
      scheme: "Yeshivat Torat Shraga", # replace with name of your project's scheme
      output_name: output_name,
      configuration: "Release",
      xcargs: settings_to_override,
      export_options: {
        method: export_method,
        provisioningProfiles: {
          app_id => ENV["sigh_com.reesedevelopment.YTS_appstore_profile-name"],
          app_id + ".NotificationService" => ENV["sigh_com.reesedevelopment.YTS.NotificationService_appstore_profile-name"]
        },
        compileBitcode: compile_bitcode
      }
    )
  end
 
  desc "Upload to TestFlight / ASC"
  lane :upload_release do
    api_key = lane_context[SharedValues::APP_STORE_CONNECT_API_KEY]
    
    deliver(
        api_key: api_key,
        skip_screenshots: true,
        skip_metadata: true,
        skip_app_version_update: true,
        force: true, # skips verification of HTML preview file (since this will be run from a CI machine)
        run_precheck_before_submit: false # not supported through ASC API yet
    )
  end

  desc "Build and upload to TestFlight"
  lane :build_upload_testflight do
    # set_xcode_version
    load_asc_api_key
    prepare_signing
    # fetch_and_increment_build_number
    build_release
    upload_release
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.reesedevelopment.YTS") # The bundle identifier of your app
apple_id("---") # Your Apple email address

team_id("---") # App Store Connect Team ID
itc_team_id("---") # App Store Connect Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.207.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| bundler                         | 2.3.7        |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| public_suffix                   | 4.0.7        |
| addressable                     | 2.8.0        |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.608.0      |
| aws-sigv4                       | 1.5.0        |
| jmespath                        | 1.6.1        |
| aws-sdk-core                    | 3.131.3      |
| aws-sdk-kms                     | 1.58.0       |
| aws-sdk-s3                      | 1.114.0      |
| babosa                          | 1.0.4        |
| claide                          | 1.0.3        |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.92.3       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.0.0        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.0       |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.4.1        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.2.0        |
| httpclient                      | 2.8.3        |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.7.0        |
| google-apis-androidpublisher_v3 | 0.25.0       |
| google-apis-playcustomapp_v1    | 0.10.0       |
| google-apis-iamcredentials_v1   | 0.13.0       |
| google-apis-storage_v1          | 0.18.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.37.0       |
| json                            | 2.6.2        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| xcode-install                   | 2.8.0        |
</details>

*generated on:* **2022-07-18**
</details>

**Comment by lucgrabowski** [comment]
The problem that you have is not related to Fastlane but to code signing settings that you have for your project. 
If you go to Xcode project - Signing and capabilities tab you should see those errors. You need to select a profile that supports `Associated Domains, App Groups, App Attest, and Push Notifications features`. To add capabilities to profile, app identifier (you can check it Apple developer center) needs to be edited and profile needs to be regenerated.

**Comment by benjitusk** [comment]
I was able to fix it that way but I'm trying to run this as a GitHub CI action, so I don't have access to Xcode's GUI. Is there a way to do this with fastlane?

**Comment by benjitusk** [comment]
Resolved by nuking my certs and inserting this in my Fastfile:
```ruby
    produce(
      app_identifier: app_id,
      app_name: "Yeshivat Torat Shraga",
      skip_itc: true,
      enable_services: {
        "associated_domains": "on",
        "app_group": "on",
        "app_attest": "on",
        "push_notification": "on",
      }
    )
```
