### ISSUE TITLE
fastlane ios beta have error

### ISSUE THREAD

**Issue by GospelHW** [fastlane/fastlane#20492]
error message
```
The following build commands failed:
        PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/togetu/Library/Developer/Xcode/DerivedData/Instpower-affwtpakkrcizwemlrmqacddvoam/Build/Intermediates.noindex/ArchiveIntermediates/Beta/IntermediateBuildFilesPath/Instpower.build/Release-iphoneos/Instpower.build/Script-00DD1BFF1BD5951E006B06BC.sh (in target 'Instpower' from project 'Instpower')
(1 failure)
[15:28:43]: Exit status: 65

+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.206.0                 |
| export_method | ad-hoc                  |
| sdk           | iPhoneOS15.4.sdk        |
+---------------+-------------------------+

[15:28:43]: ▸ /Users/togetu/Documents/proj/instpintail/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.4.99. (in target 'NYTPhotoViewer-NYTPhotoViewer' from project 'Pods')
[15:28:43]: ▸ /Users/togetu/Documents/proj/instpintail/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.4.99. (in target 'NYTPhotoViewer' from project 'Pods')
[15:28:43]: ▸ /Users/togetu/Documents/proj/instpintail/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.4.99. (in target 'react-native-maps' from project 'Pods')
[15:28:43]: ▸ /Users/togetu/Documents/proj/instpintail/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.4.99. (in target 'RNFastImage' from project 'Pods')
[15:28:43]: ▸ /Users/togetu/Documents/proj/instpintail/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.4.99. (in target 'MerryPhotoViewer' from project 'Pods')
[15:28:43]: 
[15:28:43]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[15:28:43]: 📋  For the complete and more detailed error log, check the full log at:
[15:28:43]: 📋  /Users/togetu/Library/Logs/gym/Instpower-Beta.log
[15:28:43]: 
[15:28:43]: Looks like fastlane ran into a build/archive error with your project
[15:28:43]: It's hard to tell what's causing the error, so we wrote some guides on how
[15:28:43]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[15:28:43]: Before submitting an issue on GitHub, please follow the guide above and make
[15:28:43]: sure your project is set up correctly.
[15:28:43]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
[15:28:43]: the full commands printed out in yellow in the above log.
[15:28:43]: Make sure to inspect the output above, as usually you'll find more error information there
[15:28:43]: 
+------------------------------------+----------------------------------------+
|                                Lane Context                                 |
+------------------------------------+----------------------------------------+
| PLATFORM_NAME                      | ios                                    |
| LANE_NAME                          | ios beta                               |
| SIGH_PROFILE_TYPE                  | ad-hoc                                 |
| MATCH_PROVISIONING_PROFILE_MAPPING | {"com.instpower.global"=>"match AdHoc  |
|                                    | com.instpower.global"}                 |
| BUILD_NUMBER                       | 108                                    |
+------------------------------------+----------------------------------------+
[15:28:43]: Error building the application - see the log above

+------+---------------------------------+-------------+
|                   fastlane summary                   |
+------+---------------------------------+-------------+
| Step | Action                          | Time (in s) |
+------+---------------------------------+-------------+
| 1    | Switch to ios certificates lane | 0           |
| 2    | match                           | 18          |
| 3    | match                           | 4           |
| 4    | Switch to ios build lane        | 0           |
| 5    | increment_build_number          | 2           |
| 💥   | build_app                       | 807         |
+------+---------------------------------+-------------+

[15:28:43]: fastlane finished with errors

[!] Error building the application - see the log above

#######################################################################
# fastlane 2.208.0 is available. You are on 2.206.0.
# You should use the latest version.
# Please update using `fastlane update_fastlane`.
#######################################################################
```
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 12.4                                                    |
| Ruby                        | 3.1.2                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.32.0 (Apple Git-132)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.206.0/libexec/bin/fastlane |
| Host                        | macOS 12.4 (21F79)                                      |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/3.1.2/lib                        |
| OpenSSL Version             | OpenSSL 1.1.1n  15 Mar 2022                             |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 13.3.1                                                  |
| Swift Version               | 5.6                                                     |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
platform :ios do
  # iOS Lanes
  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    match(app_identifier: 'com.instpower.global', type: 'development', readonly: true)
    match(app_identifier: 'com.instpower.global', type: 'adhoc', readonly: true, force_for_new_devices: true)
    # match(app_identifier: 'com.instpower.global', type: 'appstore', readonly: true)
  end
  lane :beta do
    certificates
    build
  end
  desc 'Build the iOS application.'
  private_lane :build do
    increment_build_number(xcodeproj: './ios/instpower.xcodeproj')
    build_app(workspace: "./ios/instpower.xcworkspace", scheme: "Beta")

    gofir
  end
  desc 'Ship to fir.im'
  private_lane :gofir do
    buildNumber = lane_context[SharedValues::BUILD_NUMBER]
    fir_cli api_token: "52d98f113c85425cc73d520680d968f5",  changelog: buildNumber
  end
end

platform :android do
  # Android Lanes
  desc 'Ship to fir.im'
  lane :beta do
    # 新增 versionCode
    increment_version_code(app_project_dir: './android/app')
    build
    git
  end
  desc 'Build the Android application.'
  private_lane :build do
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'assemble', build_type: 'BetaRelease', project_dir: 'android/')
    # 获取Apk默认输出路径
    apk_file_path = lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]

    gofir(filePath: apk_file_path)
  end
  private_lane :gofir do |options|
    # 获取版本名称
    versionName = get_version_name(app_project_dir: 'android/app')
  
    fir_cli api_token: "52d98f113c85425cc73d520680d968f5",  changelog: options[:versionName], specify_file_path: options[:filePath]
  end
  private_lane :git do
    git_commit(path: [
      './android/app/build.gradle',
      './ios/Instpower/Info.plist',
      './ios/Instpower.xcodeproj/project.pbxproj',
      './ios/InstpowerTests/Info.plist'
    ], message: 'chore: update version')
    push_to_git_remote
  end
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.206.0 | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                             | Version | Update-Status |
| ---------------------------------- | ------- | ------------- |
| fastlane-plugin-fir_cli            | 2.0.12  | ✅ Up-To-Date  |
| fastlane-plugin-android_versioning | 0.5.5   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                | Version      |
| ---------------------------------- | ------------ |
| error_highlight                    | 0.3.0        |
| did_you_mean                       | 1.6.1        |
| atomos                             | 0.1.3        |
| rexml                              | 3.2.5        |
| CFPropertyList                     | 3.0.5        |
| claide                             | 1.1.0        |
| colored2                           | 3.1.2        |
| nanaimo                            | 0.3.0        |
| xcodeproj                          | 1.21.0       |
| rouge                              | 2.0.7        |
| xcpretty                           | 0.3.0        |
| terminal-notifier                  | 2.0.0        |
| unicode-display_width              | 1.8.0        |
| terminal-table                     | 1.8.0        |
| plist                              | 3.6.0        |
| public_suffix                      | 4.0.7        |
| addressable                        | 2.8.0        |
| multipart-post                     | 2.0.0        |
| word_wrap                          | 1.0.0        |
| optparse                           | 0.1.1        |
| tty-screen                         | 0.8.1        |
| tty-cursor                         | 0.7.1        |
| tty-spinner                        | 0.9.3        |
| artifactory                        | 3.0.15       |
| babosa                             | 1.0.4        |
| colored                            | 1.2          |
| highline                           | 2.0.3        |
| commander                          | 4.6.0        |
| excon                              | 0.92.3       |
| faraday-em_http                    | 1.0.0        |
| faraday-em_synchrony               | 1.0.0        |
| faraday-excon                      | 1.1.0        |
| faraday-httpclient                 | 1.0.1        |
| faraday-multipart                  | 1.0.3        |
| faraday-net_http                   | 1.0.1        |
| faraday-net_http_persistent        | 1.2.0        |
| faraday-patron                     | 1.0.0        |
| faraday-rack                       | 1.0.0        |
| faraday-retry                      | 1.0.3        |
| ruby2_keywords                     | 0.0.5        |
| faraday                            | 1.10.0       |
| unf_ext                            | 0.0.8.1      |
| unf                                | 0.1.4        |
| domain_name                        | 0.5.20190701 |
| http-cookie                        | 1.0.4        |
| faraday-cookie_jar                 | 0.0.7        |
| faraday_middleware                 | 1.2.0        |
| fastimage                          | 2.2.6        |
| gh_inspector                       | 1.1.3        |
| json                               | 2.6.1        |
| mini_magick                        | 4.11.0       |
| naturally                          | 2.2.1        |
| rubyzip                            | 2.3.2        |
| security                           | 0.1.3        |
| xcpretty-travis-formatter          | 1.0.1        |
| dotenv                             | 2.7.6        |
| bundler                            | 2.3.11       |
| simctl                             | 1.6.8        |
| jwt                                | 2.3.0        |
| uber                               | 0.1.0        |
| declarative                        | 0.0.20       |
| trailblazer-option                 | 0.1.2        |
| representable                      | 3.2.0        |
| retriable                          | 3.1.2        |
| mini_mime                          | 1.1.2        |
| memoist                            | 0.16.2       |
| multi_json                         | 1.15.0       |
| os                                 | 1.1.4        |
| signet                             | 0.16.1       |
| googleauth                         | 1.1.3        |
| httpclient                         | 2.8.3        |
| webrick                            | 1.7.0        |
| google-apis-core                   | 0.5.0        |
| google-apis-playcustomapp_v1       | 0.7.0        |
| google-apis-androidpublisher_v3    | 0.21.0       |
| google-cloud-env                   | 1.6.0        |
| google-cloud-errors                | 1.2.0        |
| google-cloud-core                  | 1.6.0        |
| google-apis-iamcredentials_v1      | 0.10.0       |
| google-apis-storage_v1             | 0.14.0       |
| rake                               | 13.0.6       |
| digest-crc                         | 0.6.4        |
| google-cloud-storage               | 1.36.2       |
| emoji_regex                        | 3.2.3        |
| jmespath                           | 1.6.1        |
| aws-partitions                     | 1.587.0      |
| aws-eventstream                    | 1.2.0        |
| aws-sigv4                          | 1.5.0        |
| aws-sdk-core                       | 3.131.0      |
| aws-sdk-kms                        | 1.57.0       |
| aws-sdk-s3                         | 1.114.0      |
| set                                | 1.0.2        |
| forwardable                        | 1.3.2        |
| logger                             | 1.5.0        |
| pathname                           | 0.2.0        |
| shellwords                         | 0.1.0        |
| cgi                                | 0.3.1        |
| date                               | 3.2.2        |
| timeout                            | 0.2.0        |
| stringio                           | 3.0.1        |
| securerandom                       | 0.1.1        |
| uri                                | 0.11.0       |
| openssl                            | 3.0.0        |
| digest                             | 3.1.0        |
| io-nonblock                        | 0.1.0        |
| ipaddr                             | 1.2.4        |
| io-wait                            | 0.2.1        |
| zlib                               | 2.1.1        |
| resolv                             | 0.2.1        |
| time                               | 0.2.0        |
| open-uri                           | 0.2.0        |
| mutex_m                            | 0.1.1        |
| net-protocol                       | 0.1.2        |
| net-http                           | 0.2.0        |
| ostruct                            | 0.5.2        |
| english                            | 0.7.1        |
| erb                                | 2.2.3        |
| strscan                            | 3.0.1        |
| abbrev                             | 0.1.0        |
| io-console                         | 0.5.11       |
| tempfile                           | 0.1.2        |
| delegate                           | 0.2.0        |
| fileutils                          | 1.6.0        |
| tmpdir                             | 0.1.2        |
| base64                             | 0.1.1        |
| singleton                          | 0.1.1        |
| open3                              | 0.1.1        |
| nkf                                | 0.1.1        |
| prettyprint                        | 0.1.1        |
| pp                                 | 0.3.0        |
| find                               | 0.1.1        |
| yaml                               | 0.2.0        |
| psych                              | 4.0.3        |
| http-accept                        | 1.7.0        |
| mime-types-data                    | 3.2022.0105  |
| mime-types                         | 3.4.1        |
| netrc                              | 0.11.0       |
| rest-client                        | 2.1.0        |
| api_tools                          | 0.1.1        |
| thor                               | 0.20.3       |
| admqr_knife                        | 0.1.5        |
| ruby_android_apk                   | 0.7.7.1      |
| chunky_png                         | 1.4.0        |
| rqrcode                            | 0.10.1       |
| fir-cli                            | 2.0.14       |
| fastlane-plugin-fir_cli            | 2.0.12       |
| readline-ext                       | 0.1.4        |
| fastlane-plugin-android_versioning | 0.5.5        |
</details>

*generated on:* **2022-07-21**
</details>

**Comment by GospelHW** [comment]
use Xcode build is no problem

**Comment by max-ott** [comment]
Please add your `fastlane` env so the community will be able to help.

**Comment by whwngur** [comment]
@GospelHW 

How did you solve this problem?
I'm having the same problem.

**Comment by Samad313** [comment]
@GospelHW same question that @whwngur asked, how did you solve it? Getting the exact same error.
