### ISSUE TITLE
[Regression] Code signing failed with error errSecInternalComponent

### ISSUE THREAD

**Issue by crazytonyli** [fastlane/fastlane#20509]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: `2.208.0`
- Last working version: `2.206.0`

### Regression Description

On the same CI environment, we see following error when using 2.208.0, but not when using 2.206.0

```
Warning: unable to build chain to self-signed root for signer "iPhone Distribution: Automattic, Inc."
/usr/local/var/buildkite-agent/builds/builder/automattic/wordpress-ios/DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/WordPress Alpha/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/WordPressTodayWidget.appex: errSecInternalComponent
Command CodeSign failed with a nonzero exit code
```

_I think_, the issue might be caused by [this PR](https://github.com/fastlane/fastlane/pull/20448), which changed where to install the WWDR certificate—it might be the Login keychain or a random keychain that's set as the default keychain.

We uses `setup_ci` action in our Fastfile, which creates a `fastlane_tmp_keychain` and sets it as the default keychain. Maybe this is the reason why code-sign was "unable to build chain to self-signed root", since the WWDR certifcate is not in Login or System keychain?

### Environment

https://github.com/wordpress-mobile/WordPress-iOS/tree/trunk/fastlane

**Comment by dcacenabes** [comment]
We are having the same problem. For us it works too in 2.207.0, the breaking change is definitely in 2.208.0.

**Comment by dcacenabes** [comment]
I have a workaround for this.

1. Download the certificate you use from: https://www.apple.com/certificateauthority/
2. Import the certificate into the keychain:
```
import_certificate(
  certificate_path: "path_to_your_intermediate_wwdr_cert",
  keychain_name: "your keychain name",
  keychain_password: "your keychain password"
)
```

**Comment by sk-chanch** [comment]
try this.
1. Open https://developer.apple.com/account/resources/certificates/add scroll to bottom section Intermediate Certificates
2. Download all certificate
3. Install all certificate to system keychain

**Comment by grigorye** [comment]
> We are having the same problem. For us it works too in 2.207.0, the breaking change is definitely in 2.208.0.

Yeah, I can confirm it's a regression in 2.208.0. In our case, Fastlane installs the Apple WWDR certificate with organization unit "G6", but our distribution certificate has the one with "G3" organization unit in the trust chain:

<img width="625" alt="Distribution-Certificate" src="https://user-images.githubusercontent.com/803905/183973340-414bd306-27e4-4952-8064-97d3cb84d6e4.png">

Pinning Fastlane to 2.207.0 results in installation of the latter.

The certificate installed with 2.207.0:

<img width="625" alt="Screenshot 2022-08-10 at 18 30 35" src="https://user-images.githubusercontent.com/803905/183973540-d3434189-d3ac-4bae-bca5-073ec21c17b4.png">

The certificate installed with 2.208.0:

<img width="625" alt="Screenshot 2022-08-10 at 18 28 09" src="https://user-images.githubusercontent.com/803905/183973603-8a87cfb2-1459-41e8-b9ce-5e55ab8e2750.png">
