### ISSUE TITLE
Match nuke does not parse type argument correctly

### ISSUE THREAD

**Issue by lordzsolt** [fastlane/fastlane#20524]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Despite running `match_nuke(type: "appstore", api_key: api_key)` nuke is attempting to delete AdHoc profiles
![Screen Shot 2022-08-03 at 16 23 42](https://user-images.githubusercontent.com/8976891/182635172-9e12157e-2b88-45d7-8400-ed64e56b7bae.png)

##### Command executed
match_nuke(type: "appstore", api_key: api_key)

##### Complete output when running fastlane, including the stack trace and command used
See screenshot

### Environment

Not env related.

**Comment by Fuller05767** [comment]
Optional: Create a new, shared Apple Developer Portal account, something like office@company.com, that will be shared across your team from now on (for more information visit codesigning.guide)
Run the following in your project folder to start using match.

**Comment by lordzsolt** [comment]
Ah lovely. Closed without any comment.
