### ISSUE TITLE
iOS build does not see provision profile from match

### ISSUE THREAD

**Issue by zdnk** [fastlane/fastlane#20548]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I am trying to build flutter app on GitHub Actions. Using match and build_ios_app. The build does not register the downloaded profiles by match.

```
default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_KEY_ISSUER_ID"],
      key_filepath: "./AuthKey.p8",
      duration: 1200,
      in_house: false
    )

    match(type: 'development')

    build_ios_app(
      clean: true,
      scheme: "Runner",
      workspace: 'Runner.xcworkspace',
      output_directory: '../output/',
      output_name: 'tlappka',
      include_symbols: false,
    )

    upload_to_testflight(
      api_key: api_key,
      ipa: '../output/tlappka.ipa',
      submit_beta_review: false,
      distribute_external: false,
    )
  end
end
```

##### Command executed
`bundle exec fastlane beta`

##### Complete output when running fastlane, including the stack trace and command used
[9_Build & upload.txt](https://github.com/fastlane/fastlane/files/9300302/9_Build.upload.txt)

### Environment

<details><summary>✅ fastlane environment ✅</summary>
### Stack
| Key                         | Value                                              |
| --------------------------- | -------------------------------------------------- |
| OS                          | 11.6.8                                             |
| Ruby                        | 2.7.6                                              |
| Bundler?                    | true                                               |
| Git                         | git version 2.37.1                                 |
| Installation Source         | /usr/local/lib/ruby/gems/2.7.0/bin/fastlane        |
| Host                        | macOS 11.6.8 (20G730)                              |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.7/2.7.6/lib               |
| OpenSSL Version             | OpenSSL 1.1.1n  15 Mar 2022                        |
| Is contained                | false                                              |
| Is homebrew                 | false                                              |
| Is installed via Fabric.app | false                                              |
| Xcode Path                  | /Applications/Xcode_[13](https://github.com/Buddyvet/app/runs/7767726382?check_suite_focus=true#step:6:14).2.1.app/Contents/Developer/ |
| Xcode Version               | 13.2.1                                             |
| Swift Version               | 5.5.2                                              |
### System Locale
| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |
### fastlane files:
<details><summary>`./fastlane/Fastfile`</summary>
```ruby
default_platform(:ios)
platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_KEY_ISSUER_ID"],
      key_filepath: "./AuthKey.p8",
      duration: 1200,
      in_house: false
    )
    match(type: 'development')
    build_ios_app(
      clean: true,
      scheme: "Runner",
      workspace: 'Runner.xcworkspace',
      output_directory: '../output/',
      output_name: 'tlappka',
      include_symbols: false,
    )
    upload_to_testflight(
      api_key: api_key,
      ipa: '../output/tlappka.ipa',
      submit_beta_review: false,
      distribute_external: false,
    )
  end
end
```
</details>
<details><summary>`./fastlane/Appfile`</summary>
```ruby
app_identifier("com.buddyvet.buddy")
apple_id("zdenek@zdnkt.com")
itc_team_id("123930078")
team_id("X2UMSQC6LQ")
```
</details>
### fastlane gems
| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.208.0 | ✅ Up-To-Date  |
### Loaded fastlane plugins:
**No plugins Loaded**
<details><summary><b>Loaded gems</b></summary>
| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.4.0        |
| bundler                         | 2.2.27       |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| concurrent-ruby                 | 1.1.10       |
| i18n                            | 1.12.0       |
| minitest                        | 5.16.2       |
| tzinfo                          | 2.0.5        |
| zeitwerk                        | 2.6.0        |
| activesupport                   | 6.1.6.1      |
| public_suffix                   | 4.0.7        |
| addressable                     | 2.8.0        |
| httpclient                      | 2.8.3        |
| json                            | 2.6.2        |
| algoliasearch                   | 1.27.5       |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.616.0      |
| aws-sigv4                       | 1.5.1        |
| jmespath                        | 1.6.1        |
| aws-sdk-core                    | 3.132.0      |
| aws-sdk-kms                     | 1.58.0       |
| aws-sdk-s3                      | 1.1[14](https://github.com/Buddyvet/app/runs/7767726382?check_suite_focus=true#step:6:15).0      |
| babosa                          | 1.0.4        |
| claide                          | 1.1.0        |
| fuzzy_match                     | 2.0.4        |
| nap                             | 1.1.0        |
| netrc                           | 0.11.0       |
| ffi                             | 1.[15](https://github.com/Buddyvet/app/runs/7767726382?check_suite_focus=true#step:6:16).5       |
| ethon                           | 0.15.0       |
| typhoeus                        | 1.4.0        |
| cocoapods-core                  | 1.11.3       |
| cocoapods-deintegrate           | 1.0.5        |
| cocoapods-downloader            | 1.6.3        |
| cocoapods-plugins               | 1.0.0        |
| cocoapods-search                | 1.0.1        |
| cocoapods-trunk                 | 1.6.0        |
| cocoapods-try                   | 1.2.0        |
| colored2                        | 3.1.2        |
| escape                          | 0.0.4        |
| fourflusher                     | 2.3.1        |
| gh_inspector                    | 1.1.3        |
| molinillo                       | 0.8.0        |
| ruby-macho                      | 2.5.1        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| cocoapods                       | 1.11.3       |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.92.4       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.0.0        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.1       |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| jwt                             | 2.4.1        |
| memoist                         | 0.[16](https://github.com/Buddyvet/app/runs/7767726382?check_suite_focus=true#step:6:17).2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.[17](https://github.com/Buddyvet/app/runs/7767726382?check_suite_focus=true#step:6:18).0       |
| googleauth                      | 1.2.0        |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.7.0        |
| google-apis-androidpublisher_v3 | 0.25.0       |
| google-apis-playcustomapp_v1    | 0.10.0       |
| google-apis-iamcredentials_v1   | 0.13.0       |
| google-apis-storage_v1          | 0.17.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.38.0       |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
</details>
*generated on:* **[20](https://github.com/Buddyvet/app/runs/7767726382?check_suite_focus=true#step:6:21)[22](https://github.com/Buddyvet/app/runs/7767726382?check_suite_focus=true#step:6:23)-08-10**
</details>

**Comment by zdnk** [comment]
Can anyone please help?

**Comment by iBotPeaches** [comment]
Does your `Matchfile` exist with the valid values? What does `match` say during output? It is pretty explicit in the things its setting.

After that, I don't see anything between `match` and `build_is_app`, which means you either expect the configurations in your project to match what `match` would have downloaded. Or it isn't and thus a problem.

Like normally after I run `match`, I tend to use:
 * `update_code_signing_settings`  - fix up profile name
 * `update_project_team` - ensure team is the right one

**Comment by aasri13** [comment]
Oh , so sorry but i m not sure about that.
