### ISSUE TITLE
Stuck at "Waiting for the build to show up in the build list - this may take a few minutes"

### ISSUE THREAD

**Issue by canpoyrazoglu** [fastlane/fastlane#20557]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

fastlane has been stuck at "Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)" step. Tried 3 times, I'm on latest version, and I haven't received an email regarding processing issues.

##### Command executed

The lane that has the following code:
```
  log = changelog_from_git_commits(
    commits_count: 5,
    merge_commit_filtering: "exclude_merges" 
  )
  log += "\n (last 5 commits)"
  upload_to_testflight(
    beta_app_review_info: {
      # redacted
    },
    team_id: "redacted,
    distribute_external: true,
    notify_external_testers: true,
    groups:["redacted"],
    beta_app_feedback_email: "redacted",
    changelog: log,
    beta_app_description: "redacted."
  )
```

##### Complete output when running fastlane, including the stack trace and command used
[...]
```
[12:04:13]: Successfully uploaded package to App Store Connect. It might take a few minutes until it's visible online.
[12:04:13]: --------------------------------------------------------------------------------------------------
[12:04:13]: Successfully uploaded the new binary to App Store Connect
[12:04:13]: If you want to skip waiting for the processing to be finished, use the `skip_waiting_for_build_processing` option
[12:04:13]: Note that if `skip_waiting_for_build_processing` is used but a `changelog` is supplied, this process will wait for the build to appear on AppStoreConnect, update the changelog and then skip the remaining of the processing steps.
[12:04:13]: Waiting for processing on... app_id: redacted, app_version: 1.0.3, build_version: 97, platform: IOS
[12:04:14]: Read more information on why this build isn't showing up yet - https://github.com/fastlane/fastlane/issues/14997
[12:04:14]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
```
Last line repeats forever every 30 secs.

### Environment

<details>
  <pre> 

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 12.5                                                       |
| Ruby                        | 3.1.2                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.32.1 (Apple Git-133)                         |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.209.0/libexec/bin/fastlane |
| Host                        | macOS 12.5 (21G72)                                         |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.1.2/lib                        |
| OpenSSL Version             | OpenSSL 1.1.1n  15 Mar 2022                                |
| Is contained                | false                                                      |
| Is homebrew                 | true                                                       |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
| Xcode Version               | 13.4.1                                                     |
| Swift Version               | 5.6.1                                                      |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
(redacted)
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.209.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.7        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.92.4       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.1       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.6.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.8.1        |
| bundler                         | 2.3.11       |
| simctl                          | 1.6.8        |
| jwt                             | 2.4.1        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.2.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.7.0        |
| google-apis-playcustomapp_v1    | 0.10.0       |
| google-apis-androidpublisher_v3 | 0.25.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.13.0       |
| google-apis-storage_v1          | 0.17.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.38.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.6.1        |
| aws-partitions                  | 1.617.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.1        |
| aws-sdk-core                    | 3.132.0      |
| aws-sdk-kms                     | 1.58.0       |
| aws-sdk-s3                      | 1.114.0      |
| set                             | 1.0.2        |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.1        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.1        |
| uri                             | 0.11.0       |
| openssl                         | 3.0.0        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.0        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.2        |
| net-http                        | 0.2.0        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.11       |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.3        |
</details>

*generated on:* **2022-08-13**
</details>

</pre>
</details>

---

Update: It's still the case but Xcode Archive + Upload via GUI works perfectly (build shows up).

Using fastlane, the waiting takes literally forever and no build ever shows up in Xcode connect too.

**Comment by canpoyrazoglu** [comment]
Update: It's still the case but Xcode Archive + Upload via GUI works perfectly (build shows up).

Using fastlane, the waiting takes literally forever and no build ever shows up in Xcode connect too.

**Comment by KieranKI** [comment]
We’re constantly working to improve our features based on feedback like this, so I’ll be sure to share your request to the API product team.

**Comment by ErollIncodeks** [comment]
@canpoyrazoglu i'm running into the same issue after Xcode upgrade to 14.2 any solution for this?

**Comment by SolitaryWolf** [comment]
Same issue . Xcode 14.2, fastlane version 2.213.0

**Comment by roman-stetsenko-reed** [comment]
yep, same for me.
looks like something with Apple's api.
I got email that build available, can install new build via TestFlight, but fastlane still prints "Waiting for the build to show up in the build list".
And when I run `bundle exec fastlane pilot builds` - new build is not listed here.

**Comment by julestburt** [comment]
Thx [roman-stetsenko-reed](https://github.com/roman-stetsenko-reed) - passing the app_identifier in pilot solved it for me!

**Comment by WojuadeAA** [comment]
Hi, i am facing this issue, please how am i supposed to the app_identifier through fastlane?

**Comment by julestburt** [comment]
You would add the following line to your Appfile:
app_identifier("com.your.bundleID")

**Comment by WojuadeAA** [comment]
Thank you

**Comment by carlos-santos-anchor** [comment]
🔜 If someone in the future lands here, this could also be the issue: https://github.com/fastlane/fastlane/issues/14748#issuecomment-518714610
