### ISSUE TITLE
Notarize action using notarytool can fail without a proper error message

### ISSUE THREAD

**Issue by WKD** [fastlane/fastlane#20578]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When using the `notarize` action, sometimes the `notarytool` tool fails but doesn’t return any useful message in `statusMessage` so this is reported by fastlane as a very unhelpful error message `Could not notarize package with message ‘’` which makes debugging tricky.

It seems to especially happen when it encounters errors signing a framework included in the built app.

Using the `notarytool log` command yields useful information in such cases, so it could be a good idea to integrate its output whenever the `statusMessage` is empty.

NB: `notarytool log` returns a JSON similar to the snippet below which clearly states that in our case the error was signing a framework included into our own framework which is part of the app:

`{"logFormatVersion"=>1, "jobId"=>"[redacted]", "status"=>"Invalid", "statusSummary"=>"Archive contains critical validation errors", "statusCode"=>4000, "archiveFilename"=>"MySampleApp.zip", "uploadDate"=>"2022-08-19T17:31:32.205Z", "sha256"=>"[redacted]", "ticketContents"=>nil, "issues"=>[{"severity"=>"error", "code"=>nil, "path"=>"MySampleApp.app.zip/MySampleApp.app/Contents/Frameworks/MyFramework.framework/Versions/A/Frameworks/Atomics_301F3DE065572157_PackageProduct.framework/Versions/A/Atomics_301F3DE065572157_PackageProduct", "message"=>"The binary is not signed with a valid Developer ID certificate.", "docUrl"=>nil, "architecture"=>"x86_64"}, {"severity"=>"error", "code"=>nil, "path"=>"MySampleApp.app.zip/MySampleApp.app/Contents/Frameworks/MyFramework.framework/Versions/A/Frameworks/Atomics_301F3DE065572157_PackageProduct.framework/Versions/A/Atomics_301F3DE065572157_PackageProduct", "message"=>"The binary is not signed with a valid Developer ID certificate.", "docUrl"=>nil, "architecture"=>"arm64"}]}`

##### Command executed
- `fastlane mac notarize_build`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[✔] 🚀 
[19:19:46]: fastlane detected a Gemfile in the current directory
[19:19:46]: However, it seems like you didn't use `bundle exec`
[19:19:46]: To launch fastlane faster, please use
[19:19:46]: 
[19:19:46]: $ bundle exec fastlane mac notarize_build
[19:19:46]: 
[19:19:46]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
+-----------------------------+---------+-----------------------------------------------------------------------------+
|                                                    Used plugins                                                     |
+-----------------------------+---------+-----------------------------------------------------------------------------+
| Plugin                      | Version | Action                                                                      |
+-----------------------------+---------+-----------------------------------------------------------------------------+
| fastlane-plugin-aws_s3      | 2.1.0   | aws_s3                                                                      |
| fastlane-plugin-dmg         | 0.1.1   | dmg                                                                         |
| fastlane-plugin-slack_train | 0.2.0   | slack_train_crash, slack_train_start, slack_train                           |
| fastlane-plugin-badge       | 1.5.0   | add_badge                                                                   |
| fastlane-plugin-sentry      | 1.12.0  | sentry_upload_dsym, sentry_set_commits, sentry_upload_sourcemap,            |
|                             |         | sentry_finalize_release, sentry_upload_file, sentry_create_deploy,          |
|                             |         | sentry_upload_proguard, sentry_create_release, sentry_check_cli_installed,  |
|                             |         | sentry_upload_dif                                                           |
+-----------------------------+---------+-----------------------------------------------------------------------------+

objc[83419]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x20f82b640) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1085002c8). One of the two will be used. Which one is undefined.
objc[83419]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x20f82b690) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x108500318). One of the two will be used. Which one is undefined.
objc[83419]: Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib (0x20f82b458) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1085004f8). One of the two will be used. Which one is undefined.
objc[83419]: Class AppleTypeCRetimerFirmwareAggregateRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x20f82b4a8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x108500548). One of the two will be used. Which one is undefined.
objc[83419]: Class AppleTypeCRetimerFirmwareRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x20f82b4f8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x108500598). One of the two will be used. Which one is undefined.
objc[83419]: Class ATCRTRestoreInfoFTABFile is implemented in both /usr/lib/libauthinstall.dylib (0x20f82b548) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1085005e8). One of the two will be used. Which one is undefined.
objc[83419]: Class AppleTypeCRetimerFirmwareCopier is implemented in both /usr/lib/libauthinstall.dylib (0x20f82b598) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x108500638). One of the two will be used. Which one is undefined.
objc[83419]: Class ATCRTRestoreInfoFTABSubfile is implemented in both /usr/lib/libauthinstall.dylib (0x20f82b5e8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x108500688). One of the two will be used. Which one is undefined.
[19:19:47]: ------------------------------
[19:19:47]: --- Step: default_platform ---
[19:19:47]: ------------------------------
[19:19:47]: Driving the lane 'mac notarize_build' 🚀
[19:19:47]: ---------------------------------------
[19:19:47]: --- Step: app_store_connect_api_key ---
[19:19:47]: ---------------------------------------
[19:19:47]: ----------------------
[19:19:47]: --- Step: notarize ---
[19:19:47]: ----------------------
[19:19:47]: $ ditto -c -k --rsrc --keepParent "builds/MySampleApp.app" "builds/MySampleApp.app.zip"
[19:19:50]: $ xcrun notarytool submit builds/MySampleApp.app.zip --output-format json --wait --key /var/folders/dg/wcbw5rv53nl4k8frrm93wsd40000gn/T/20220819-83404-c8f1r8 --key-id [redacted] --issuer [redacted]
[19:20:18]: ▸ {"id":[redacted],"status":"Invalid","message":"Processing complete"}
+------------------+--------------------+
|             Lane Context              |
+------------------+--------------------+
| DEFAULT_PLATFORM | mac                |
| PLATFORM_NAME    | mac                |
| LANE_NAME        | mac notarize_build |
+------------------+--------------------+
[19:20:18]: Could not notarize package with message ''

+------+---------------------------+-------------+
|                fastlane summary                |
+------+---------------------------+-------------+
| Step | Action                    | Time (in s) |
+------+---------------------------+-------------+
| 1    | default_platform          | 0           |
| 2    | app_store_connect_api_key | 0           |
| 💥   | notarize                  | 30          |
+------+---------------------------+-------------+

+--------+--------------+----------------+
|        Plugin updates available        |
+--------+--------------+----------------+
| Plugin | Your Version | Latest Version |
+--------+--------------+----------------+
| sentry | 1.12.0       | 1.12.2         |
+--------+--------------+----------------+
[19:20:18]: To update all plugins, just run
[19:20:18]: $ bundle exec fastlane update_plugins

[19:20:18]: fastlane finished with errors

[!] Could not notarize package with message '' </pre>
</details>

### Environment

<details>
  <pre><details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                              |
| --------------------------- | -------------------------------------------------- |
| OS                          | 12.4                                               |
| Ruby                        | 2.7.2                                              |
| Bundler?                    | false                                              |
| Git                         | git version 2.32.0 (Apple Git-132)                 |
| Installation Source         | ~/.rbenv/versions/2.7.2/bin/fastlane               |
| Host                        | macOS 12.4 (21F79)                                 |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.2/lib                        |
| OpenSSL Version             | OpenSSL 1.1.1o  3 May 2022                         |
| Is contained                | false                                              |
| Is homebrew                 | false                                              |
| Is installed via Fabric.app | false                                              |
| Xcode Path                  | /Applications/Xcode-13.2.1.app/Contents/Developer/ |
| Xcode Version               | 13.2.1                                             |
| Swift Version               | 5.5.2                                              |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


default_platform(:mac)
xcode_file = "../.xcode_version"
xcversion(version: File.read(xcode_file)) if File.exists?(xcode_file)

platform :mac do
  lane :notarize_build do

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_API_KEY_ISSUER_ID"],
      key_content: ENV["APP_STORE_API_KEY"]
    )
    
    notarize(
      package: "builds/MySampleApp.app",
      verbose: true,
      print_log: true,
      bundle_id: ENV["APP_IDENTIFIER"],
      asc_provider: ENV["TEAM_ID"],
      api_key: api_key
    )
  end

  [redacted]

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier(ENV["APP_IDENTIFIER"])
apple_id(ENV["CERT_USERNAME"])

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.209.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                      | Version | Update-Status      |
| --------------------------- | ------- | ------------------ |
| fastlane-plugin-aws_s3      | 2.1.0   | ✅ Up-To-Date       |
| fastlane-plugin-dmg         | 0.1.1   | ✅ Up-To-Date       |
| fastlane-plugin-slack_train | 0.2.0   | ✅ Up-To-Date       |
| fastlane-plugin-badge       | 1.5.0   | ✅ Up-To-Date       |
| fastlane-plugin-sentry      | 1.12.0  | 🚫 Update available |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.4.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| CFPropertyList                  | 3.0.5        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| simctl                          | 1.6.8        |
| emoji_regex                     | 3.2.3        |
| uri                             | 0.10.0       |
| rexml                           | 3.2.5        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.1.0        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.22.0       |
| public_suffix                   | 4.0.7        |
| excon                           | 0.92.4       |
| ruby2_keywords                  | 0.0.5        |
| faraday-retry                   | 1.0.3        |
| faraday-rack                    | 1.0.0        |
| faraday-patron                  | 1.0.0        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-net_http                | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-httpclient              | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.10.1       |
| domain_name                     | 0.5.99999999 |
| http-cookie                     | 1.0.5        |
| json                            | 2.6.2        |
| dotenv                          | 2.8.1        |
| bundler                         | 2.3.7        |
| jwt                             | 2.4.1        |
| webrick                         | 1.7.0        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| signet                          | 0.17.0       |
| os                              | 1.1.4        |
| memoist                         | 0.16.2       |
| googleauth                      | 1.2.0        |
| mini_mime                       | 1.1.2        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.2        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| google-apis-core                | 0.7.0        |
| google-apis-playcustomapp_v1    | 0.10.0       |
| google-apis-androidpublisher_v3 | 0.25.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-apis-storage_v1          | 0.17.0       |
| google-apis-iamcredentials_v1   | 0.13.0       |
| google-cloud-errors             | 1.2.0        |
| google-cloud-env                | 1.6.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.38.0       |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.1        |
| aws-partitions                  | 1.616.0      |
| jmespath                        | 1.6.1        |
| aws-sdk-core                    | 3.132.0      |
| aws-sdk-kms                     | 1.58.0       |
| aws-sdk-s3                      | 1.114.0      |
| forwardable                     | 1.3.1        |
| logger                          | 1.4.2        |
| cgi                             | 0.1.0        |
| date                            | 3.0.0        |
| timeout                         | 0.1.0        |
| stringio                        | 0.1.0        |
| openssl                         | 3.0.0        |
| ipaddr                          | 1.2.2        |
| zlib                            | 1.1.0        |
| mutex_m                         | 0.1.0        |
| ostruct                         | 0.2.0        |
| strscan                         | 1.0.3        |
| io-console                      | 0.5.6        |
| delegate                        | 0.1.0        |
| fileutils                       | 1.4.1        |
| singleton                       | 0.1.0        |
| open3                           | 0.1.0        |
| nokogiri                        | 1.13.8       |
| racc                            | 1.6.0        |
| yaml                            | 0.1.0        |
| psych                           | 3.1.0        |
| apktools                        | 0.7.4        |
| mime-types-data                 | 3.2022.0105  |
| mime-types                      | 3.4.1        |
| fastlane-plugin-aws_s3          | 2.1.0        |
| fastlane-plugin-dmg             | 0.1.1        |
| fastlane-plugin-slack_train     | 0.2.0        |
| badge                           | 0.13.0       |
| fastlane-plugin-badge           | 1.5.0        |
| fastlane-plugin-sentry          | 1.12.0       |
</details>

*generated on:* **2022-08-19**
</details></pre>
</details>

**Comment by KieranKI** [comment]
I appreciate the information and advice you have shared.

**Comment by Johnstonmouth** [comment]
Apple has documented this tool in a WWDC21 session and some developer articles, in addition we got some great information through the twitter account of one of the engineers, and Howard Oakley has already written a post as well:
