### ISSUE TITLE
Support generating APNS Auth key (.p8)

### ISSUE THREAD

**Issue by Yahllil** [fastlane/fastlane#20588]
Following the discussion from this [thread](https://github.com/fastlane/fastlane/issues/11221) a few years ago, I have seen this feature has not yet been implemented into Fastlane.

Generating APNS Auth keys is very useful for white-label app builders, which uses multiple Apple Developer accounts in order to upload different versions of the app.

Many push notification services, and especially FCM, required the APNS Auth key in order to enable push notifications for iOS.
Therefore, I believe it is appropriate to consider adding this feature into Fastlane.

**Comment by Carissa34** [comment]
This works really well for us, thank you!

**Comment by Yahllil** [comment]
Hi @Carissa34 , I didn't understand you answer. Is this already implemented in Fastlane? Because I couldn't find any info about it

**Comment by mortenholmgaard** [comment]
Any news on this @joshdholtz, 5 years ago you said it would be added to your list. And it would be cool to the p8 auth keys to push so we do not have to handle expirations of those tokens.

**Comment by Romulomga** [comment]
Any news on this?

**Comment by ciekawy** [comment]
this is definitely a missing feature
CC @joshdholtz in regard to https://github.com/fastlane/fastlane/issues/11221#issuecomment-386856901

**Comment by muhammad67uzair** [comment]
any update to support the p.8 APNs yet?
