### ISSUE TITLE
Mandatory destination on scan + package_path

### ISSUE THREAD

**Issue by apascual** [fastlane/fastlane#20608]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I am configuring a new lane to test a Swift Package and it looks like providing a destination is mandatory, but I would like scan to pick one for me instead.

Picking the first matching destination seems to work when testing apps, but for some reason it does not work when testing Swift Packages.

##### Command executed

```
lane :custom_lane do
    scan(
      scheme: "AxisLogger",
      package_path: ".",
      result_bundle: true
      )
end
```

Results in the following error:

`xcodebuild: error: Building a Swift package requires that a destination is provided using the "-destination" option. The "-showdestinations" option can be used to list the available destinations.`

**Comment by Bryansa23** [comment]
I appreciate the information and advice you have shared. I will try to figure it out for more.

**Comment by kylebshr** [comment]
@joshdholtz any chance you could take a look at this? Any reason scan can't pick a destination for packages?
