### ISSUE TITLE
Deliver action keep in Waiting for all the screenshots to finish being processed forever

### ISSUE THREAD

**Issue by OmniaMahmoud** [fastlane/fastlane#20619]
I run deliver action with the following options: 
deliver(
        submit_for_review: false,
        skip_app_version_update: true,
        force: true,
        team_id: "TEAM_ID",
	precheck_include_in_app_purchases: false,
	overwrite_screenshots: true,
    )
all store data updated but the screenshots keep waiting for processing forever.
Note: I use app_store_connect_api_key for authentication

fastlane env output:
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 12.3                                                    |
| Ruby                        | 3.1.2                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.35.1                                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.209.1/libexec/bin/fastlane |
| Host                        | macOS 12.3 (21E230)                                     |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/3.1.2_1/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1q  5 Jul 2022                              |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 13.3                                                    |
| Swift Version               | 5.6                                                     |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"

  lane :upload do

    app_store_connect_api_key(
        key_id: "xx",
        issuer_id: "xx",
        key_filepath: "xx",
        duration: 1200, # optional (maximum 1200)
        in_house: false # optional but may be required if using match/sigh
    )

    deliver(
        submit_for_review: false,
        skip_app_version_update: true,
        force: true,
        team_id: "xx",
	    precheck_include_in_app_purchases: false,
	    overwrite_screenshots: true,
    )

    end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("") # The bundle identifier of your app
apple_id("") # Your Apple email address

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.209.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 5.0.0        |
| addressable                     | 2.8.1        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.92.4       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.1       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.6.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.8.1        |
| bundler                         | 2.3.11       |
| simctl                          | 1.6.8        |
| jwt                             | 2.4.1        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.2.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.7.0        |
| google-apis-playcustomapp_v1    | 0.10.0       |
| google-apis-androidpublisher_v3 | 0.25.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.13.0       |
| google-apis-storage_v1          | 0.17.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.38.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.6.1        |
| aws-partitions                  | 1.620.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.1        |
| aws-sdk-core                    | 3.132.0      |
| aws-sdk-kms                     | 1.58.0       |
| aws-sdk-s3                      | 1.114.0      |
| set                             | 1.0.2        |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.1        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.1        |
| uri                             | 0.11.0       |
| openssl                         | 3.0.0        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.0        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.2        |
| net-http                        | 0.2.0        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.11       |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.3        |
</details>

*generated on:* **2022-09-03**
</details>

**Comment by OmniaMahmoud** [comment]
> It seems like you have not included the output of `fastlane env` To make it easier for us help you resolve this issue, please update the issue to include the output of `fastlane env` 👍

done

**Comment by mjovkovic** [comment]
Same here

**Comment by OmniaMahmoud** [comment]
there is a part of my images uploaded  and appear on app store and other not appear with this message 
"this file has been uploaded and is processing"

**Comment by dungnt109** [comment]
I have the same issue. My solution is to go to the portal, delete the greyed screenshots, keep the successfully uploaded screenshots and run fastlane with overwrite_screenshots set to false. Keep the process until all screenshots are uploaded.

**Comment by markmuniz** [comment]
We are having the same issue.

**Comment by henry-wbs** [comment]
Fastlane continued for me after cancelling the images with "this file has been uploaded and is processing" and uploading them manually.

**Comment by jmif** [comment]
Having the same issue, started occurring ~4 days ago.  Manual upload of same images also works.

**Comment by development-incapptic** [comment]
We are also facing the same issue
There are still incomplete screenshots - {"UPLOAD_COMPLETE"=>5, "COMPLETE"=>3}

**Comment by hakburi** [comment]
Same issue. 

[⠋] Waiting for all the screenshots to finish being processed... DEBUG [2022-09-06 01:34:51.31]: There are still incomplete screenshots - {"COMPLETE"=>2, "UPLOAD_COMPLETE"=>4}

- Fastfile 
```
    upload_to_app_store(
      force: true,
      overwrite_screenshots: true,
      skip_binary_upload: true,
    )
```

**Comment by fhperuchi** [comment]
I am having the same issue.

**Comment by Thangaraj-M** [comment]
facing the same issue

**Comment by Ido-Levi** [comment]
Same issue here, any workaround for the meantime?

**Comment by Gywem** [comment]
Recently we are facing the exact same issue.

**Comment by muehlemann** [comment]
Facing the same issue

**Comment by sonjz** [comment]
is is a reoccurring issue with apple i've noticed over at least the past 4 years.
my guess has always been apple is rolling in server changes to the fleet, and some get caught with the old code and can't resolve.  i recall it normally taking a couple days to a week for the issue to disappear on its own.

**Comment by samueldusek** [comment]
I am facing the same issue. Is there any workaround? 🙂

**Comment by galacticdisassembler** [comment]
We're facing the same issue for quite some time already. 
Is there some kind of a workaround?

**Comment by TalRandi1** [comment]
Same issue here

**Comment by development-incapptic** [comment]
Hi Team, Do you have any workaround or can you please let us know about any ETA?

**Comment by jakub-przy** [comment]
Experiencing the same issue (as per my comment in: https://github.com/fastlane/fastlane/issues/20625)

**Comment by michaelforrest** [comment]
Happening to me too. Would love a workaround or ETA for a fix...

**Comment by BDDev** [comment]
We noticed our builds getting stuck on "Waiting for screenshots to finish uploading" September 1st. I suspect the same or similar as https://github.com/fastlane/fastlane/issues/20619#issuecomment-1238492501 and hope it is an issue on Apple's side that will resolve any day now.

**Comment by daidongon** [comment]
Facing the same issue too

```
deliver(
    submit_for_review: false,
    automatic_release: false,
    force: true,
    skip_binary_upload: true,
    skip_metadata: false,
    skip_screenshots: false,
    overwrite_screenshots: true,
    precheck_include_in_app_purchases: false,
)
```

**Comment by Westacular** [comment]
This does seem to be an Apple issue, when I logged into App Store Connect _10 hours later_, some of the screenshoots were still showing a blank placeholder with the message "This file has been uploaded and is processing."

I can remove the placeholders and manually upload the missing screenshots directly in App Store Connect, and that doesn't seem to incur this processing delay. But after doing so, when I try to submit to app review, it fails with an error message saying "There are still screenshot uploads in progress."

Ugh.

**Comment by Ido-Levi** [comment]
for now we have just skipped uploading screenshots using fastlane and doing it manually which sucks, but couldn't find a different way

**Comment by daidongon** [comment]
I tried again just now and it seems to have worked with [same script](https://github.com/fastlane/fastlane/issues/20619#issuecomment-1239474192) !

<img width="1127" alt="スクリーンショット 2022-09-08 11 41 57" src="https://user-images.githubusercontent.com/25152049/189021820-4c2e1d4d-9b79-48da-84bd-d7f604834260.png">

**Comment by jakub-przy** [comment]
It seems to be working for us as well! Oh Apple 🍏

**Comment by OmniaMahmoud** [comment]
Yes working
Thank you all

**Comment by murataksuu** [comment]
not working for me

**Comment by sonjz** [comment]
hit and miss, must be still rolling out slowly.

**Comment by sonjz** [comment]
noticed that i hadn't updated to fastlane 2.209.1 yet, retesting.

**Comment by fhperuchi** [comment]
We were already using the `2.209.1` fastlane version, and we did not changed anything on our fastlane scripts. It started to work again today for us.

```
$ fastlane --version
fastlane installation at path:
/Users/fhperuchi/.rvm/gems/ruby-3.1.2/gems/fastlane-2.209.1/bin/fastlane
-----------------------------
[✔] 🚀 
fastlane 2.209.1
```

**Comment by saggio89** [comment]
@sonjz I think this is a problem with Apple -- I manually uploaded the build via xcode & when I try to update the pricing on AppStore Connect, it throws an error 

<img width="1172" alt="Screen Shot 2022-09-08 at 3 38 45 PM" src="https://user-images.githubusercontent.com/17790636/189211064-ec5c7e13-6066-4a16-add7-08173710efb3.png">

**Comment by sonjz** [comment]
@saggio89 i received the same but think it cleared up last night.
i was able to save it as Free and rerelease without issue.

**Comment by saggio89** [comment]
@sonjz  same! I submitted an issue to Apple yesterday, looks like they fixed it since then. Happy coding!

**Comment by samueldusek** [comment]
I tried it again today and everything seems to be fine. I was finally able to realease the app using the same fastlane script as always. Looks like apple has solved the issue. 🙂

**Comment by markmuniz** [comment]
Is this happening again for anyone else?

**Comment by samueldusek** [comment]
@markmuniz 
> Is this happening again for anyone else?

No. Everything seems to be working fine. 👍

**Comment by jjochen** [comment]
This is still happening for me...

**Comment by jjochen** [comment]
> This is still happening for me...

Worked after deleting all existing screenshots from App Store Connect.

**Comment by skarol** [comment]
> Is this happening again for anyone else?

After some time when working fine, started appearing again today.

**Comment by Westacular** [comment]
I've seen a couple random recurrences of this. It definitely seems like there's something flaky in whatever queue Apple's using to process these uploads? Not sure there's much Fastlane can do to work around that.

Our CI process for submitting builds is granular enough that we have a specific job just for uploading screenshots. The times we've experienced this issue in the last couple of weeks, retrying just that job has always succeeded, so ... at least the problem isn't as big or consistent as it was when this all started.

**Comment by EmDee** [comment]
Just happened on our end again.

**Comment by ralfebert** [comment]
Same here, it seems to be stuck in a loop with the screenshots never finishing:

```
[⠹] Waiting for all the screenshots to finish being processed... DEBUG [2022-10-07 14:29:45.85]: There are still incomplete screenshots - {"COMPLETE"=>439, "FAILED"=>17, "UPLOAD_COMPLETE"=>36}
[⠸] Waiting for all the screenshots to finish being processed... DEBUG [2022-10-07 14:29:52.12]: There are still incomplete screenshots - {"COMPLETE"=>439, "FAILED"=>17, "UPLOAD_COMPLETE"=>36}
[⠹] Waiting for all the screenshots to finish being processed... DEBUG [2022-10-07 14:29:58.31]: There are still incomplete screenshots - {"COMPLETE"=>439, "FAILED"=>17, "UPLOAD_COMPLETE"=>36}
```

**Comment by ppamorim** [comment]
Still happening for me.  I beleive fastlane should offer a timeout option to not keep the process stuck.

**Comment by EmDee** [comment]
Today has been such a day again. Our runners have been stuck the last 5h waiting for the processing to finish.

**Comment by sonjz** [comment]
> Still happening for me. I believe fastlane should offer a timeout option to not keep the process stuck.

just use a timeout from bash or your scripting language and wrap it.
bash has `timeout` and ruby has `Timeout`

check the error it throws and respond appropriately...

**Comment by sonjz** [comment]
> In regards to the timeout ⬆️ I recommend doing this: https://support.circleci.com/hc/en-us/articles/4411204604059-Automatically-cancel-build-after-set-amount-of-time
> 
> This is a CircleCI specific doc, but this should be doable elsewhere.

to each their own, but if i  already knew my timeout time, i would rather wrap the process in a timeout vs creating another job to poll it and send the kill signal.

**Comment by mrazam110** [comment]
Its still happening :(

**Comment by EmDee** [comment]
Apple seems to have trouble in regard to the screenshot processing lately.

What we did is separate the `deliver` job for screenshots from the submission one. This helped tremendously as we can just retry the screenshot upload as often as we need to.

**Comment by RaymondGuirguis** [comment]
1 Question for those who faced this error. 
If I am stuck for 2 hours in this step, Is it better to keep the process running, or restart the process? 
I mean was the issue fixed for anyone just by restarting the fastlane process for the same app? Or we should just keep waiting?

**Comment by EmDee** [comment]
> 1 Question for those who faced this error. 
> 
> If I am stuck for 2 hours in this step, Is it better to keep the process running, or restart the process? 
> 
> I mean was the issue fixed for anyone just by restarting the fastlane process for the same app? Or we should just keep waiting?

Waiting never worked for us. When you go to ASC you can see that the resources are just stuck in the processing loop forever.

The only solution for us was either manually uploading the screenshots with ASC's media manager or restarting the job.

**Comment by mregnauld** [comment]
I experienced the same problem today.
Relaunching the same lane without changing anything worked out for me.

**Comment by jjochen** [comment]
No, also happened to us recently.

**Comment by ralfebert** [comment]
Has anyone a workaround for this issue?

Here is my routine for uploading screenshots which works but is still painful:

I always upload all screenshots (`overwrite_screenshots: true`). 

Most of the time this will result in an endless loop like this:

```
[⠇] Waiting for all the screenshots to finish being processed... DEBUG [2023-05-02 16:35:00.45]: There are still incomplete screenshots - {"COMPLETE"=>538, "UPLOAD_COMPLETE"=>6, "FAILED"=>15}
[⠇] Waiting for all the screenshots to finish being processed... DEBUG [2023-05-02 16:35:00.45]: There are still incomplete screenshots - {"COMPLETE"=>538, "UPLOAD_COMPLETE"=>6, "FAILED"=>15}
[⠇] Waiting for all the screenshots to finish being processed... DEBUG [2023-05-02 16:35:00.45]: There are still incomplete screenshots - {"COMPLETE"=>538, "UPLOAD_COMPLETE"=>6, "FAILED"=>15}
```

The FAILED ones are not a problem, fastlane will re-upload them (in App Store connect those will have a red exclamation mark).

But the UPLOAD_COMPLETE ones are just stuck. So what I do is I go to App Store Connect, click through all the locales and find those (6 in this case) that are stuck (they will have a gray cloud symbol). I delete those. Then fastlane will continue and upload the missing and failed ones. It might get stuck a second time, same procedure.

I tried using the new `sync_screenshots`, this worked the first time but this failed to do the update the second time...

It seems the screenshot upload needs a timeout for the images in state `UPLOAD_COMPLETE`...

**Comment by ralfebert** [comment]
All the logic to re-upload the screenshots seems to be there and a change as simple as this might do the trick of not waiting endlessly for the uploads to complete: https://github.com/fastlane/fastlane/commit/6168384629dd5e4a3935b0829c6ab9831b0d8c8a

**Comment by thisisthekap** [comment]
@ralfebert Are you considering creating a PR for your fix?

**Comment by AlkanV** [comment]
hello, any news on this? i am facing same issue.

**Comment by vanniktech** [comment]
The best 'solution', I have is to go to the Media Manager, here's an url for my app: https://appstoreconnect.apple.com/apps/6453164382/appstore/ios/version/inflight/media-manager (simply swap the app id and it should work for you). Force refresh the site without a cache and go through each language and then you can find the unprocessed screenshots, remove them yourself and reupload the screenshots yourself. Fastlane is able to pick it up again:

```
[19:31:27]: Uploaded './fastlane/screenshots/cs/iPhone 8 Plus-06.png'... (3.93246 secs)
[✔] Waiting for all the screenshots to finish being processed...
[19:47:41]: ./fastlane/screenshots/sv/iPhone 14 Pro Max-02.png is missing on App Store Connect.
```

As you can see this took me more than 15 minutes, since I have 3 different sizes with 25 languages.

In the meantime - fastlane must know this - would it be possible to print out which exact screenshots (file path is suffice) are missing?

**Comment by jjochen** [comment]
Lately this is happening so much again.

**Comment by efraespada** [comment]
Stills happening, with this error at the end:

```
[13:40:22]: Uploaded './fastlane/screenshots/tr/2_APP_IPHONE_65_2.png'... (3.193515 secs)
[⠏] Waiting for all the screenshots to finish being processed... #<Thread:0x00007fb8702b19e0@/Library/Ruby/Gems/2.6.0/gems/fastlane-2.216.0/deliver/lib/deliver/app_screenshot_iterator.rb:24 run> terminated with exception (report_on_exception is true):
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/models/app_store_version_localization.rb:103:in `rescue in get_app_screenshot_sets': it (Spaceship::AppStoreScreenshotError)
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/models/app_store_version_localization.rb:99:in `get_app_screenshot_sets'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.216.0/deliver/lib/deliver/app_screenshot_iterator.rb:25:in `block (3 levels) in each_app_screenshot_set'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/api_client.rb:188:in `rescue in with_asc_retry': undefined method `refresh!' for nil:NilClass (NoMethodError)
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/api_client.rb:165:in `with_asc_retry'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/api_client.rb:105:in `get'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:493:in `get_app_screenshot_sets'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `get_app_screenshot_sets'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/models/app_screenshot_set.rb:129:in `all'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/models/app_store_version_localization.rb:101:in `get_app_screenshot_sets'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.216.0/deliver/lib/deliver/app_screenshot_iterator.rb:25:in `block (3 levels) in each_app_screenshot_set'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/api_client.rb:244:in `handle_error': Authentication credentials are missing or invalid. - No valid credentials found in the request. (Spaceship::UnauthorizedAccessError)
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/client.rb:932:in `block in send_request'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/client.rb:687:in `with_retry'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/client.rb:928:in `send_request'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/client.rb:772:in `request'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/api_client.rb:106:in `block in get'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/api_client.rb:166:in `with_asc_retry'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/api_client.rb:105:in `get'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:493:in `get_app_screenshot_sets'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `get_app_screenshot_sets'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/models/app_screenshot_set.rb:129:in `all'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.216.0/spaceship/lib/spaceship/connect_api/models/app_store_version_localization.rb:101:in `get_app_screenshot_sets'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.216.0/deliver/lib/deliver/app_screenshot_iterator.rb:25:in `block (3 levels) in each_app_screenshot_set'
+------------------------------------+
|            Lane Context            |
+------------------+-----------------+
| DEFAULT_PLATFORM | ios             |
| PLATFORM_NAME    | ios             |
| LANE_NAME        | ios deliver_ios |
+------------------+-----------------+
[15:07:54]: it

+---------------------------------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 💥   | deliver          | 5438        |
+------+------------------+-------------+

[15:07:54]: fastlane finished with errors

[!] An exception occurred for locale: it. Check the screenshot requirements here: https://help.apple.com/app-store-connect/en.lproj/static.html#devd274dd925
```

**Comment by mikhailmaslo** [comment]
@vhartikainen @efraespada @assembleMHN @jjochen @vanniktech  @rocketnik @AlkanV 

I've made a PR that addresses the issue with screenshots uploading https://github.com/fastlane/fastlane/pull/21693.

Could you check it with your setup and give the feedback? I would be grateful.

You can adjust your `Gemfile` in this way:
```ruby
gem "fastlane", git: "https://github.com/mikhailmaslo/fastlane",  branch: "feature/introduce-timeout-for-screenshots-upload"
```

Then, you can use _deliver_ to upload screenshots
```ruby
deliver(
	api_key: api_key,
	skip_binary_upload: true,
	skip_screenshots: false,
	skip_metadata: true,
	skip_app_version_update: true,
	force: true,
	overwrite_screenshots: true,
	run_precheck_before_submit: false,
	screenshot_processing_timeout: 120
)
```

Note the `screenshot_processing_timeout` parameter, which defines the timeout for screenshots processing awaiting. In this example, it's set to 2 minutes. All unprocessed screenshots are deleted from App Store Connect and then re-uploaded again with the same timeout of `screenshot_processing_timeout`

In my experience, one re-uploading loop is sufficient to upload all screenshots. I've tested with ~200 screenshots.

**Comment by jjochen** [comment]
I tested it, but in my first couple of tries, the upload didn't get stuck, but worked on the first try 🙄
Will try some more.

**Comment by rogerluan** [comment]
Thanks for your PR @mikhailmaslo ! 🙏 

I'd also like to ask as many people as possible to test @mikhailmaslo 's PR, here: https://github.com/fastlane/fastlane/pull/21693

There are testing instructions at the bottom of the PR description to help you test this 😊  thank you everyone! ❤️
