### ISSUE TITLE
[XCode 14 issue]: No signing certificate iOS Development found. needs selected Development Team for Pod Bundles 

### ISSUE THREAD

**Issue by salvatoreboemia** [fastlane/fastlane#20626]
Hi 

since I set up on Azure XCode 14 the fastlane fails in the build_app phase

Local XCode 14 works (assigning the teamID to the two PODs

ERRORS:

```
- /Users/runner/work/1/s/Pods/Pods.xcodeproj: error: No signing certificate "iOS Development" found: 
No "iOS Development" signing certificate matching team ID "XXXXX" 
with a private key was found. (in target 'POD NAME XXXX' from project 'Pods')

- /Users/runner/work/1/s/Pods/Pods.xcodeproj: error: No signing certificate "iOS Development" found:
No "iOS Development" signing certificate matching team ID "XXXXX" 
with a private key was found. (in target 'POD NAME XXXX' from project 'Pods')
```
<img width="270" alt="Screenshot 2022-09-06 at 12 24 41" src="https://user-images.githubusercontent.com/20614870/188650439-f8ffc1d6-e17e-4712-ae7b-6b95a44d0e69.png">

Do you have any suggestions on how to fix this error?

Thanks

**Comment by josher8** [comment]
Add this to your podfile then run pod install again. 

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
    end
  end
end
```

**Comment by crazymanish** [comment]
This is the CocoaPods issue: 
- please follow https://github.com/CocoaPods/CocoaPods/issues/11402#issuecomment-1201464693


closing it

**Comment by JorgeAGomez** [comment]
> Add this to your podfile then run pod install again.
> 
> ```
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     target.build_configurations.each do |config|
>       config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
>     end
>   end
> end
> ```

This did the trick for me. Thank you!

**Comment by bshirley** [comment]
This may solve the problem differently:

```
post_install do |installer|


  # This may only be needed temporarily for XCode 14. Two pods needed signing identities.
  # An update to Xcode 14.0 or cocoapods 1.11.3 might remove the need for this.
  # Get main project development team id
  dev_team = ""
  project = installer.aggregate_targets[0].user_project
  project.targets.each do |target|
      target.build_configurations.each do |config|
          if dev_team.empty? and !config.build_settings['DEVELOPMENT_TEAM'].nil?
              dev_team = config.build_settings['DEVELOPMENT_TEAM']
          end
      end
  end
  
  # Fix bundle targets' 'Signing Certificate' to 'Sign to Run Locally'
  installer.pods_project.targets.each do |target|
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
          target.build_configurations.each do |config|
              config.build_settings['DEVELOPMENT_TEAM'] = dev_team
          end
      end
  end  

end

```

**Comment by Yusufkhan11223344556677** [comment]
> Hi
> 
> since I set up on Azure XCode 14 the fastlane fails in the build_app phase
> 
> Local XCode 14 works (assigning the teamID to the two PODs
> 
> ERRORS:
> 
> ```
> - /Users/runner/work/1/s/Pods/Pods.xcodeproj: error: No signing certificate "iOS Development" found: 
> No "iOS Development" signing certificate matching team ID "XXXXX" 
> with a private key was found. (in target 'POD NAME XXXX' from project 'Pods')
> 
> - /Users/runner/work/1/s/Pods/Pods.xcodeproj: error: No signing certificate "iOS Development" found:
> No "iOS Development" signing certificate matching team ID "XXXXX" 
> with a private key was found. (in target 'POD NAME XXXX' from project 'Pods')
> ```
> 
> <img alt="Screenshot 2022-09-06 at 12 24 41" width="270" src="https://user-images.githubusercontent.com/20614870/188650439-f8ffc1d6-e17e-4712-ae7b-6b95a44d0e69.png">
> 
> Do you have any suggestions on how to fix this error?
> 
> Thanks
