### ISSUE TITLE
`upload_to_testflight` action hangs with "Waiting for App Store Connect to finish processing the new build ..."

### ISSUE THREAD

**Issue by mathaeus** [fastlane/fastlane#20645]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
`upload_to_testflight` action hangs with the following message although the build has been processed
```
Waiting for App Store Connect to finish processing the new build (1.0.0 - 1234) for IOS
```

Since up until recently this worked just fine it could also just be an App Store Connect issue 🤷‍♂️. 
Tried several times with different apps.

##### Command executed
I basically have such a lane.

```
  lane :submit_build_for_beta_review_and_distribute do 
      app_store_connect_api_key(
        key_id: "keyid",
        issuer_id: "issuerid",
        key_content: "keycontent",
        is_key_content_base64: true,
        duration: 1200,
        in_house: false
      )

    upload_to_testflight(
      beta_app_review_info: {
        contact_email: "foo@bar.com",
        contact_first_name: "foo",
        contact_last_name: "bar",
        contact_phone: "+1234",
        demo_account_name: "foo",
        demo_account_password: "bar",
        notes: "foo bar"
      },
      app_version: version_name,
      build_number: build_number,
      submit_beta_review: true, 
      distribute_only: true,
      notify_external_testers: true,
      groups: ["foo", "bar"]
    )
end
```

##### Complete output when running fastlane, including the stack trace and command used
Here's our output from CI with some data anonymised 

<details>
  <pre>
#!/bin/bash --login -eo pipefail
bundle exec fastlane submit_build_for_beta_review_and_distribute
[⠋] 🚀 [⠙] 🚀 [⠹] 🚀 [⠸] 🚀 [⠼] 🚀 [⠴] 🚀 [⠦] 🚀 [⠧] 🚀 [⠇] 🚀 [✔] 🚀 
+----------------------------------+---------+------------------+
|                         Used plugins                          |
+----------------------------------+---------+------------------+
| Plugin                           | Version | Action           |
+----------------------------------+---------+------------------+
| fastlane-plugin-aws_s3           | 2.1.0   | aws_s3           |
| fastlane-plugin-update_xcodeproj | 1.0.1   | update_xcodeproj |
+----------------------------------+---------+------------------+

[07:57:38]: Sending anonymous analytics information
[07:57:38]: Learn more at https://docs.fastlane.tools/#metrics
[07:57:38]: No personal or sensitive data is sent.
[07:57:38]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
[07:57:39]: ----------------------------------------
[07:57:39]: --- Step: Verifying fastlane version ---
[07:57:39]: ----------------------------------------
[07:57:39]: Your fastlane version 2.209.1 matches the minimum requirement of 2.170.0  ✅
[07:57:39]: ------------------------------
[07:57:39]: --- Step: default_platform ---
[07:57:39]: ------------------------------
[07:57:39]: Driving the lane 'ios submit_build_for_beta_review_and_distribute' 🚀
[07:57:39]: -----------------------------
[07:57:39]: --- Step: setup_circle_ci ---
[07:57:39]: -----------------------------
[07:57:39]: Creating temporary keychain: "fastlane_tmp_keychain".
[07:57:39]: $ security list-keychains -d user
[07:57:39]: ▸ "/Users/distiller/Library/Keychains/fastlane_tmp_keychain-db"
[07:57:39]: Found keychain '/Users/distiller/Library/Keychains/fastlane_tmp_keychain-db' in list-keychains, adding to search list skipped
[07:57:39]: Enabling match readonly mode.
[07:57:39]: Trying to create AppStoreConnectAPIKey via CI ENV variables...
[07:57:39]: ---------------------------------------
[07:57:39]: --- Step: app_store_connect_api_key ---
[07:57:39]: ---------------------------------------
[07:57:39]: --------------------------------------
[07:57:39]: --- Step: get_ipa_info_plist_value ---
[07:57:39]: --------------------------------------
[07:57:39]: --------------------------------------
[07:57:39]: --- Step: get_ipa_info_plist_value ---
[07:57:39]: --------------------------------------
[07:57:39]: Submitting foobar 1.0.0/1234 for review and distributing to external testers.
[07:57:39]: ----------------------------------
[07:57:39]: --- Step: upload_to_testflight ---
[07:57:39]: ----------------------------------
[07:57:39]: Creating authorization token for App Store Connect API
[07:57:41]: Waiting for processing on... app_id: 12345678, app_version: 1.0.0, build_version: 1234, platform: IOS
[07:57:43]: Waiting for App Store Connect to finish processing the new build (1.0.0 - 1234) for IOS
[07:58:14]: Waiting for App Store Connect to finish processing the new build (1.0.0 - 1234) for IOS
[07:58:45]: Waiting for App Store Connect to finish processing the new build (1.0.0 - 1234) for IOS
[07:59:17]: Waiting for App Store Connect to finish processing the new build (1.0.0 - 1234) for IOS
[07:59:48]: Waiting for App Store Connect to finish processing the new build (1.0.0 - 1234) for IOS
[08:00:19]: Waiting for App Store Connect to finish processing the new build (1.0.0 - 1234) for IOS
[08:00:50]: Waiting for App Store Connect to finish processing the new build (1.0.0 - 1234) for IOS
...
</pre>
</details>

**Comment by hendych** [comment]
Same here,
My build always `Waiting for App Store Connect to finish processing the new build (xxx - xxx009) for IOS` even the build is already done processing.

![Screen Shot 2022-09-12 at 16 15 08](https://user-images.githubusercontent.com/8999432/189617272-4dc10cd7-88af-4ece-bee3-82780fe3553b.png)

**Comment by Baza207** [comment]
Having the same issue. Seems to have started last Friday 9th Sept as builds from the Thursday 8th were fine.

Builds this morning having the same issues, I can see them in App Store Connect but DevOps ends up timing out due to stuck at this step where Fastlane isn't able to see the build has finished processing. 😞

**Comment by baderbenzribia** [comment]
Same here too.
We can see the build on TestFlight but Fastlane keep saying `Waiting for App Store Connect to finish processing the new build...`

**Comment by mathaeus** [comment]
Thanks @hendych @Baza207 @baderbenzribia for confirming that you have the same issue 👍

**Comment by mathaeus** [comment]
ℹ️ Submitting the same build for App Store review with `deliver` works without any problem.

**Comment by unixvb** [comment]
The same, using latest `fastlane (2.209.1)`

**Comment by readyruncode** [comment]
We see the same issue.
Build stays at "Waiting for App Store Connect to finish processing the new build" and times out after 5 hours.
Builds show up in TestFlight as `Ready to Submit`, but they seem to be missing tester groups and change log.
When we try to submit for review the build gets labeled `Invalid Binary`.

**Comment by Baza207** [comment]
> ℹ️ Submitting the same build for App Store review with `deliver` works without any problem.

Using `2.209.1` here as well, but via the Azure DevOps Apple App Store task, so can't switch to `deliver` without re-writing our pipelines. 😞

Pretty sure it's not Fastlane though as using the same version before Friday last week worked fine. Feels very much like something on Apple's end that got pushed last thing Thursday in the US that might have broken the API. Though I don't have the ability (at the moment) to test it myself, the API endpoints don't look like they've changed in Apple's docs. https://developer.apple.com/documentation/appstoreconnectapi/internalbetastate

**Comment by mathaeus** [comment]
> When we try to submit for review the build gets labeled Invalid Binary.

@readyruncode you mean if you try to submit manually?

----

I was able to submit the build for BETA review manually without any problem (it disrupts our CI pipeline, but well ... 😅)

**Comment by mathaeus** [comment]
> Pretty sure it's not Fastlane though as using the same version before Friday last week worked fine

Yes, it worked without any problem last week for us as well. My first thought also was that (parts of the) ASC APIs are either temporarily broken or Apple changed some things under the hood and now the `fastlane` code needs to be adapted or something.

I have too little knowledge about the internals of `fastlane` to debug the communication with ASC API. Guess that would show the underlying problem.

**Comment by Baza207** [comment]
> > Pretty sure it's not Fastlane though as using the same version before Friday last week worked fine
> 
> Yes, it worked without any problem last week for us as well. My first thought also was that (parts of the) ASC APIs are either temporarily broken or Apple changed some things under the hood and now the `fastlane` code needs to be adapted or something.
> 
> I have too little knowledge about the internals of `fastlane` to debug the communication with ASC API. Guess that would show the underlying problem.

I don't have much either, but from what I can see the Fastlane model here:
https://github.com/fastlane/fastlane/blob/e8d30e3494024b6d4ee81bf21448991779ca278d/spaceship/lib/spaceship/connect_api/models/build_beta_detail.rb

Maps directly to the App Store Connect API docs about build state here:
https://developer.apple.com/documentation/appstoreconnectapi/internalbetastate
https://developer.apple.com/documentation/appstoreconnectapi/externalbetastate

Sadly I don't have the time right now to look any further into this and see what the endpoints from Apple actually return (https://developer.apple.com/documentation/appstoreconnectapi/read_build_beta_detail_information).

Posting the links here for anyone else who might have the time/ability to test and see what does/doesn't get returned. 😅

**Comment by christianYoopies** [comment]
Same issue , started around` Friday 9th Sept` too.

**Comment by readyruncode** [comment]
> > When we try to submit for review the build gets labeled Invalid Binary.
> 
> @readyruncode you mean if you try to submit manually?
> 
> I was able to submit the build for BETA review manually without any problem (it disrupts our CI pipeline, but well ... 😅)

@mathaeus Yes, I mean when trying to manually submit the build to beta review using the TestFlight interface on App Store Connect, the status changed to `Invalid Binary`.

**Comment by veerlorden** [comment]
Same here. Started last Friday approximately. I'm able to deliver new app version to App Store, however, the CI always fails because the processing lasts too long

**Comment by ivan-gaydamakin** [comment]
fastlane 2.209.0.
Still "waiting" on during 6 hours... Today I saw that problem.

**Comment by DimaElka** [comment]
same issue

**Comment by SSheldon** [comment]
This looks like the same issue that @bassrock opened #20644 to fix. It sounds like [that change solved the issue for him](https://github.com/fastlane/fastlane/discussions/20640#discussioncomment-3621840).

**Comment by saudeon** [comment]
Confirming we are also seeing this issue with the latest version of Fastlane.
My assumption is that perhaps Apple changed a response?

**Comment by benjamin-es-hall** [comment]
Confirming also seeing same issue with fastlane 2.209.1. Not sure when started but I've just about gone crazy trying to distribute to internal groups with no luck today (same as reported by @bassrock in #20644 )

**Comment by LizCira** [comment]
Also seeing the same using Bamboo and yes, for us it started sometime over the weekend. I have been able to locally reproduce the behavior running Fastlane from my terminal

**Comment by mathaeus** [comment]
Thanks @SSheldon for linking that other issue. The issues do indeed sound like they could have the same cause.

@joshdholtz since quite a few people are affected, may I drag you into this to get your expert opinion on this?

**Comment by minhthong095** [comment]
Same here :(
<img width="664" alt="image" src="https://user-images.githubusercontent.com/15071968/189810726-e1fa53a0-f4c6-488b-b7d9-f108e3784d75.png">
<img width="1195" alt="Screen Shot 2022-09-13 at 11 44 12" src="https://user-images.githubusercontent.com/15071968/189810918-e7301812-7b23-4f8f-813b-202e2153eaa4.png">

**Comment by 3a4oT** [comment]
The same issue is on our side, is there any workaround?

**Comment by crazymanish** [comment]
Dear all,

@bassrock PR https://github.com/fastlane/fastlane/pull/20644 looks like fix this issue.
Adding steps to switch your Fastlane version to this PR

### Switch your Fastlane version to PR
- Update `Gemfile` to 👇 and run `bundle install`, `bundle update fastlane`, or `bundle update`

```rb
gem "fastlane", :git => "https://github.com/bassrock/fastlane.git", :branch => "beta-build"
```

Please let us know if this PR fixed the issue for you or not and provide us your valuable feedback!

**Comment by Ibni-Amin** [comment]
On 9th September 2022 I faced the same issue on testFlight through pipeline, before it was fine and work smoothly, when
I run pipeline, maximum within an hour build would available on testFlight.

**Comment by Baza207** [comment]
> Dear all,
> 
> @bassrock PR #20644 looks like fix this issue. Adding steps to switch your Fastlane version to this PR
> 
> ### Switch your Fastlane version to PR
> * Update `Gemfile` to 👇 and run `bundle install`, `bundle update fastlane`, or `bundle update`
> 
> ```ruby
> gem "fastlane", :git => "https://github.com/bassrock/fastlane.git", :branch => "beta-build"
> ```
> 
> Please let us know if this PR fixed the issue for you or not and provide us your valuable feedback!

If this works that's great, but I have 2 questions:
1. Does anyone know how we'd use this version when using Azure DevOps tasks when use Fastlane where we don't use Fastlane directly?
2. Would there be any timeline for a new version being released (assuming this fix works)?

**Comment by DimaElka** [comment]
> Dear all,
> 
> @bassrock PR #20644 looks like fix this issue. Adding steps to switch your Fastlane version to this PR
> 
> ### Switch your Fastlane version to PR
> * Update `Gemfile` to 👇 and run `bundle install`, `bundle update fastlane`, or `bundle update`
> 
> ```ruby
> gem "fastlane", :git => "https://github.com/bassrock/fastlane.git", :branch => "beta-build"
> ```
> 
> Please let us know if this PR fixed the issue for you or not and provide us your valuable feedback!

after raising version to beta I have "No build_beta_detail included" error with the same upload step that worked previously

**Comment by kamvoick** [comment]
> Dear all,
> 
> @bassrock PR #20644 looks like fix this issue. Adding steps to switch your Fastlane version to this PR
> 
> ### Switch your Fastlane version to PR
> * Update `Gemfile` to 👇 and run `bundle install`, `bundle update fastlane`, or `bundle update`
> 
> ```ruby
> gem "fastlane", :git => "https://github.com/bassrock/fastlane.git", :branch => "beta-build"
> ```
> 
> Please let us know if this PR fixed the issue for you or not and provide us your valuable feedback!

Fixed that issue for me, thanks :)

**Comment by benjamin-es-hall** [comment]
> Dear all,
> 
> @bassrock PR #20644 looks like fix this issue. Adding steps to switch your Fastlane version to this PR
> 
> ### Switch your Fastlane version to PR
> * Update `Gemfile` to 👇 and run `bundle install`, `bundle update fastlane`, or `bundle update`
> 
> ```ruby
> gem "fastlane", :git => "https://github.com/bassrock/fastlane.git", :branch => "beta-build"
> ```
> 
> Please let us know if this PR fixed the issue for you or not and provide us your valuable feedback!

Can confirm worked for me as well!

**Comment by muffe** [comment]
> after raising version to beta I have "No build_beta_detail included" error with the same upload step that worked previously

Same for me.

It now detects the new version again, but errors out soon after

```
[13:16:40]: Successfully finished processing the build 1.1.6 - 638669436 for IOS
[13:16:40]: Build did include information for app, build beta detail and pre release version
[13:16:40]: Fetching a new build with all the information needed
[13:16:43]: Successfully set the changelog for build
[13:16:43]: Using App Store Connect's default for notifying external testers (which is true) - set `notify_external_testers` for full control
[13:16:43]: Distributing new build to testers: 1.1.6 - 638669436
+------------------+-----------------------------+
|                  Lane Context                  |
+------------------+-----------------------------+
| DEFAULT_PLATFORM | ios                         |
| PLATFORM_NAME    | ios                         |
| LANE_NAME        | ios upload_external_staging |
+------------------+-----------------------------+
[13:16:43]: No build_beta_detail included
+------+------------------------------+-------------+
|                 fastlane summary                  |
+------+------------------------------+-------------+
| Step | Action                       | Time (in s) |
+------+------------------------------+-------------+
| 1    | opt_out_usage                | 0           |
| 2    | default_platform             | 0           |
| 3    | Switch to ios getApiKey lane | 0           |
| 4    | app_store_connect_api_key    | 0           |
| 💥   | upload_to_testflight         | 1063        |
+------+------------------------------+-------------+
[13:16:43]: fastlane finished with errors
```

**Comment by baderbenzribia** [comment]
Same error here too
> Error in 'upload_app_to_testflight': No build_beta_detail included

**Comment by markusmattfolkstenberg** [comment]
We're facing the same issue and can't sadly try the workaround as we're using fastlane via azure devops.

**Comment by Julien-Roger** [comment]
The beta build does not help as we get now error "no_build_beta_details"
The forever loop on "waiting for app store connect to finish processing ..." happens since last friday (9th september 2022).
I've noticed that during processing I get following warning message. 
"App Store Connect API token expired at 2022-09-13 11:03:44 +0200... refreshing"
It seems the token now expires after 8 minutes (i think it used to be 20 minutes)...

Today I tried again and now during processing in logs I see following:
INFO [2022-09-13 12:12:24.53]: Waiting for App Store Connect to finish processing the new build (1.0 - 3961) for IOS
Authentication credentials are missing or invalid. - Provide a properly configured and signed bearer token, and make sure that it has not expired. Learn more about Generating Tokens for API Requests https://developer.apple.com/go/?id=api-generating-tokens
Token has expired or has been revoked! Trying to refresh...
INFO [2022-09-13 12:13:02.35]: Waiting for App Store Connect to finish processing the new build (1.0 - 3961) for IOS

I am wondering if this issue where fastlane is unable to detect processing termination could be due to some token expiration/renewal issue...

**Comment by daniel-moonactive** [comment]
we have managed to resolve the "No build_beta_detail" included
we are using bundler to execute fastlane
in gem file we updated fastlane to 2.209.1 version
used bundle update and committed the gem.lock changes
in the build pipeline we first call `bundle install` and then `bundle exec fastlane <method>`

**Comment by mathaeus** [comment]
We do have `bundle install` and `bundle exec fastlane <lane>` but we still run into the following 
```
/spaceship/lib/spaceship/connect_api/models/build.rb:96:in `ready_for_beta_submission?': \e[31m[!] No build_beta_detail included\e[0m (RuntimeError)
```

@crazymanish any idea why the workaround does work in some cases but not in others?

Could it be that it depends on how the `upload_to_testflight` action is used?
i.e. 

- upload + submit for review + distribute OR
- submit for review + distribute (doing the upload in a previous step)

**Comment by Baza207** [comment]
It feels like the build object still isn't being returned or returned in full by the App Store Connect API. Might be why it sometimes works but sometimes doesn't. 🤔 

Has anyone been able to call that API endpoint directly and see what's returned?

**Comment by M1ZoN** [comment]
I am also facing the `No build_beta_detail included`

Also I have a question regarding this workaround, does anyone distributing to external testers? If so does it works for you, are you able to see if the build was distributed to external testers.

**Comment by MrChrisBarker** [comment]
> I am also facing the `No build_beta_detail included` error, but it did uploaded to TestFlight without being stuck.
> 
> Also I have a question regarding this workaround, does anyone distributing to external testers? If so does it works for you, are you able to see if the build was distributed to external testers.

I've not tried the workaround yet... but I did notice with the initial issue, once the build had processed it doesn't  distribute to Groups I specified in the job (previously worked fine)

**Comment by elliottkember** [comment]
I've tried the workaround, and while it uploads to TF it doesn't seem to add the build to external test groups. I believe the beta build detail includes the ID it needs to submit those requests after the build is uploaded.

**Comment by M1ZoN** [comment]
I think it is not getting distributed to external test groups because of the build_beta_details:

```
if options[:submit_beta_review] && (options[:groups] || options[:distribute_external])
    if uploaded_build.ready_for_beta_submission?
        uploaded_build.post_beta_app_review_submission
    else
        UI.message("Build #{uploaded_build.app_version} - #{uploaded_build.version} already submitted for review")
    end
end
```

It is failing in second if condition -> raises error `No build_beta_detail included` -> no external distribution, can anyone help looking into it

**Comment by daniel-moonactive** [comment]
> we have managed to resolve the "No build_beta_detail" included we are using bundler to execute fastlane in gem file we updated fastlane to 2.209.1 version used bundle update and committed the gem.lock changes in the build pipeline we first call `bundle install` and then `bundle exec fastlane <method>`

after another check I see that even if the message `No build_beta_detail included` doesn't show up for me, and the external text group is assigned to the build correctly, it doesn't submit the build for testing
the app is still in "ready to submit" state (yellow icon), after manually deleting and re adding the external group it also changed the state of the app to "testing" which is necessary to show up for testers in testflight

**Comment by crazymanish** [comment]
Looks like, Apple has changed something recently and no longer provides the `buildBetaDetail ` when we list the builds using the [GET https://api.appstoreconnect.apple.com/v1/builds](https://developer.apple.com/documentation/appstoreconnectapi/list_builds)

Adding the flow, if anyone is interested to contribute:
- **Step1:** BuildWatcher is fetching the build details and expecting to   return `buildBetaDetail ` also https://github.com/fastlane/fastlane/blob/ff41f3556f1baf8e700477e50f65be728780aa94/fastlane_core/lib/fastlane_core/build_watcher.rb#L106

- **Step2:** Fetching build details with **[ESSENTIAL_INCLUDES](https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/connect_api/models/build.rb#L46)** (betaBuildDetail) https://github.com/fastlane/fastlane/blob/ff41f3556f1baf8e700477e50f65be728780aa94/spaceship/lib/spaceship/connect_api/models/build.rb#L124

- **Step3:** Apple suppose to returns the `buildBetaDetail` because we are requesting it here but stop returning 🤷‍♂️ https://github.com/fastlane/fastlane/blob/ff41f3556f1baf8e700477e50f65be728780aa94/spaceship/lib/spaceship/connect_api/models/build.rb#L46


**I don't know if this is temporary Apple issue** or they removed it completely. 
According to Apple document, we can expect `buildBetaDetail ` in response 
<img width="1208" alt="Screenshot 2022-09-13 at 20 52 13" src="https://user-images.githubusercontent.com/5364500/189986096-e8b240e1-39b8-4389-ac9a-a2e9916705ee.png">



cc: A friendly ping to @joshdholtz to deal with it! 😅

**Comment by daniel-moonactive** [comment]
this PR seems relevant, it indicates that build beta details sometimes will not return from apple https://github.com/fastlane/fastlane/pull/16006

**Comment by ls-philippe-casgrain** [comment]
The workaround for `https://github.com/bassrock/fastlane.git` worked for us (just adding a data point).

**Comment by joshdholtz** [comment]
I'm here now! Sorry, life is really crazy right now 😔 Familiarizing myself and seeing what I can do tonight 💪

**Comment by joshdholtz** [comment]
✨ OFFICIAL UPDATE

`GET` to ` https://api.appstoreconnect.apple.com/v1/builds` isn't returning any build beta details (which is what is the cause of this issue) but also...

`GET to `https://api.appstoreconnect.apple.com/v1/builds/<build_id>/buildBetaDetail` (which would be the work around) is 500ing... 😬 

So it seems like there is a bigger issue on App Store Connect with serializing any build beta detail information.

---

🔨**Solution**
I'm going to send an email to the App Store Connect API team with my HAR files of the failed requests tonight. I'm hoping I can get a response from them in the morning followed by a fix sometime tomorrow.

---

🩹 **Workarounds**
1. To prevent this crash you _could_ set `skip_waiting_for_build_processing: true` to prevent the crash from happening while waiting for the build to process
2. Sleep the process for like an hour or just wait an hour 😛 
3. After some amount of time you could run `upload_to_testflight` again with `distribute_only: true`

**Comment by mathaeus** [comment]
Thanks @joshdholtz for looking into it, much appreciated.

----

Regarding the workaround, unfortunately that doesn't work, since even with `distribute_only: true` for a previously uploaded (and processed) build we run into this problem. See my OP. Just wanted to point that out :)

**Comment by Julien-Roger** [comment]
> 🩹 **Workarounds**
> 
> 1. To prevent this crash you _could_ set `skip_waiting_for_build_processing: true` to prevent the crash from happening while waiting for the build to process
> 2. Sleep the process for like an hour or just wait an hour 😛
> 3. After some amount of time you could run `upload_to_testflight` again with `distribute_only: true`

Problem is that method upload_to_testflight will never exit or timeout. Need to add some watchdog to kill the process after 1 hour.

**Comment by joshdholtz** [comment]
✨Official Update

Got confirmation that the App Store Connect API team is looking into the issue ✅

Will report back when I hear more and/or when it's fixed!

**Comment by joshdholtz** [comment]
✨Official Update

App Store Connect API is back to working for `https://api.appstoreconnect.apple.com/v1/builds` 💯 🥳 

*If you are able to test and report back that its working for you too that would be greatly appreciate* 🙏

**Comment by M1ZoN** [comment]
I think now it is stuck on 
```
Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
```
Because previously it was doing this stage for 4-6 min, and now it is doing it for 12 min, and I am hypothesising that it will be stuck now :(

Will update shortly, because script has timeout in one hour.

**Comment by nick-kt** [comment]
The API is working for us again - no workarounds or changes since prior to the issue 🙌

**Comment by joshdholtz** [comment]
@M1ZoN Huh... it really should have worked for you! Are you using App Store Connect API key, right? Did you check your email for any processing issues? 

I don't know if that PR will get merged because the waiting for processing is needed for all the proper external distribution stuff to take place 🤔

**Comment by bassrock** [comment]
I can confirm my upload action is working again without https://github.com/fastlane/fastlane/pull/20644 ! 🥳

**Comment by Baza207** [comment]
Working again for us as well via Azure DevOps Apple App Store task. 🥳 Thanks @joshdholtz and everyone for the help. 😄

**Comment by elitalon** [comment]
It's working for us as well. Thanks a lot!

**Comment by DimaElka** [comment]
It's working again! Thanks!

**Comment by bonnyfone** [comment]
Working for me again without any change.

**Comment by Jonas-Storytel** [comment]
@joshdholtz saves us once again. You're a goddamn legend, man! ❤️

**Comment by MrChrisBarker** [comment]
Working for me too, including distribution to Groups!!
Thanks everyone & @joshdholtz !!!!

**Comment by MatthewTHFisher** [comment]
Amazing work!!! Thanks @joshdholtz and everyone 🎉

**Comment by mathaeus** [comment]
I haven't had the chance yet to test it, but since it's working for everyone now I'll close the issue.

Great work everyone ❤️

**Comment by readyruncode** [comment]
Confirming it's working again for our team as well! No changes needed.

Thanks @joshdholtz and everyone else who helped resolve this! ❤️

**Comment by trongnhan68** [comment]
Hello, I still got an issue like this. Can any have an idea? 
ENV: 
- Xcode 13.4.1
- Fastlane 2.210.0
