### ISSUE TITLE
Pilot: `ready_for_beta_submission?': No build_beta_detail included (RuntimeError)

### ISSUE THREAD

**Issue by rokgregoric** [fastlane/fastlane#20654]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Submitting for external testing using pilot fails with the following error:
```
ready_for_beta_submission?': No build_beta_detail included (RuntimeError)
```

##### Command executed
```
$ fastlane "pilot" "distribute" "--api_key_path" "api_key.json" "--app_identifier" "xxx" "--ipa" "tmp.ipa" "--distribute_external" "true" "--changelog" "commit msg" "--groups" "external" "--build_number" "123"
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
/Users/vagrant/.rbenv/versions/2.6.9/lib/ruby/gems/2.6.0/gems/fastlane-2.209.1/spaceship/lib/spaceship/connect_api/models/build.rb:96:in `ready_for_beta_submission?': No build_beta_detail included (RuntimeError)
	from /Users/vagrant/.rbenv/versions/2.6.9/lib/ruby/gems/2.6.0/gems/fastlane-2.209.1/pilot/lib/pilot/build_manager.rb:424:in `distribute_build'
	from /Users/vagrant/.rbenv/versions/2.6.9/lib/ruby/gems/2.6.0/gems/fastlane-2.209.1/pilot/lib/pilot/build_manager.rb:200:in `distribute'
	from /Users/vagrant/.rbenv/versions/2.6.9/lib/ruby/gems/2.6.0/gems/fastlane-2.209.1/pilot/lib/pilot/commands_generator.rb:79:in `block (2 levels) in run'
	from /Users/vagrant/.rbenv/versions/2.6.9/lib/ruby/gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/vagrant/.rbenv/versions/2.6.9/lib/ruby/gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/vagrant/.rbenv/versions/2.6.9/lib/ruby/gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/vagrant/.rbenv/versions/2.6.9/lib/ruby/gems/2.6.0/gems/fastlane-2.209.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/vagrant/.rbenv/versions/2.6.9/lib/ruby/gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/vagrant/.rbenv/versions/2.6.9/lib/ruby/gems/2.6.0/gems/fastlane-2.209.1/pilot/lib/pilot/commands_generator.rb:167:in `run'
	from /Users/vagrant/.rbenv/versions/2.6.9/lib/ruby/gems/2.6.0/gems/fastlane-2.209.1/pilot/lib/pilot/commands_generator.rb:19:in `start'
	from /Users/vagrant/.rbenv/versions/2.6.9/lib/ruby/gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
	from /Users/vagrant/.rbenv/versions/2.6.9/lib/ruby/gems/2.6.0/gems/fastlane-2.209.1/bin/fastlane:23:in `<top (required)>'
	from /Users/vagrant/.rbenv/versions/2.6.9/bin/fastlane:23:in `load'
	from /Users/vagrant/.rbenv/versions/2.6.9/bin/fastlane:23:in `<main>'
</pre>
</details>

**Comment by dinsen** [comment]
See here: https://github.com/fastlane/fastlane/issues/20645

**Comment by rokgregoric** [comment]
Related to: https://github.com/fastlane/fastlane/issues/20645
