### ISSUE TITLE
Could not retrieve response as fastlane runs in non-interactive mode\e[0m (FastlaneCore::Interface::FastlaneCrash)

### ISSUE THREAD

**Issue by hafsa-code** [fastlane/fastlane#20661]
![Screenshot from 2022-09-15 17-32-04](https://user-images.githubusercontent.com/71277499/190405182-d0ce2f00-b0fa-48e9-a3fb-f7e15769d2da.png)

Attaching  Fastlane env output here, I am continuously getting non-interactive fastlane mode error on fastlane build and bundle exec. Please guide how to resolve this error and deploy flutter app to playstore through githubactions

**Comment by hasanmakane** [comment]
The only possible reason would be that Fastlane is asking for input and it needs interactive mode. when running the lane from other than terminal directly. Fastlane run in non-interactive mode. so when its that and needs input that happens.

input could be asking for apple authentication maybe. you need to show your lane. and some logging.
