### ISSUE TITLE
An exception has occurred: issuerId is required - upload_to_testflight 

### ISSUE THREAD

**Issue by knightbenax** [fastlane/fastlane#20736]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Whenever I run the upload_to_testflight command, I get a failure from Transporter with the following error: An exception has occurred: issuerId is required. While the issuerId has been well supplied. Worked well a few days ago and with no code changes, started failing with this error

### Output
<details><pre>
[11:41:18]: Successfully exported and compressed dSYM file
[11:41:18]: Successfully exported and signed the ipa file:
[11:41:18]: /Users/administrator/actions-runner/_work/pp-members/pp-members/ios/Members.ipa
[11:41:18]: ----------------------------------
[11:41:18]: --- Step: upload_to_testflight ---
[11:41:18]: ----------------------------------
[11:41:18]: Creating authorization token for App Store Connect API
[11:41:18]: Ready to upload new build to TestFlight (App: 6443610541)...
[11:41:19]: Going to upload updated app to App Store Connect
[11:41:19]: This might take a few minutes. Please don't interrupt the script.
[11:41:28]: Transporter transfer failed.
[11:41:28]: 
[11:41:28]: There was a general exception while executing
An exception has occurred: issuerId is required

[11:41:29]: [iTMSTransporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[11:41:29]: [iTMSTransporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

[11:41:29]: [iTMSTransporter] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

[11:41:29]: [iTMSTransporter] 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)

[11:41:29]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.bootstrap(BootstrapperPhase1.java:107)

[11:41:29]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.bootstrap(BootstrapperPhase1.java:78)

[11:41:29]: [iTMSTransporter] 	at com.apple.transporter.launcher.Launcher.launchBootstrapper(Launcher.java:37)

[11:41:29]: [iTMSTransporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[11:41:29]: [iTMSTransporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

[11:41:29]: [iTMSTransporter] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

[11:41:29]: [iTMSTransporter] 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)

[11:41:29]: [iTMSTransporter] 	at com.apple.transporter.launcher.Application.start(Application.java:450)

[11:41:29]: [iTMSTransporter] 	at com.apple.transporter.launcher.Application.main(Application.java:947)

[11:41:29]: [iTMSTransporter] 

[11:41:29]: [iTMSTransporter] [2022-10-10 11:41:28 PDT] <main> DBG-X: Returning 1

[11:41:29]: iTunes Transporter output above ^
[11:41:29]: There was a general exception while executing
An exception has occurred: issuerId is required
Return status of iTunes Transporter was 1: There was a general exception while executing
\nAn exception has occurred: issuerId is required
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
+------------------------------------+--------------------------------------------------------------------------------------------------------+
|                                                                Lane Context                                                                 |
+------------------------------------+--------------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM                   | ios                                                                                                    |
| PLATFORM_NAME                      | ios                                                                                                    |
| LANE_NAME                          | ios beta                                                                                               |
| BUILD_NUMBER                       | 1665426593                                                                                             |
| SIGH_PROFILE_TYPE                  | app-store                                                                                              |
| MATCH_PROVISIONING_PROFILE_MAPPING | {"com.pushpress.empowerfitness"=>"match AppStore com.pushpress.empowerfitness"}                        |
| VERSION_NUMBER                     | 2.39.0                                                                                                 |
| IPA_OUTPUT_PATH                    | /Users/administrator/actions-runner/_work/pp-members/pp-members/ios/Members.ipa                        |
| XCODEBUILD_ARCHIVE                 | /Users/administrator/Library/Developer/Xcode/Archives/2022-10-10/Members 2022-10-10 11.34.32.xcarchive |
| DSYM_OUTPUT_PATH                   | /Users/administrator/actions-runner/_work/pp-members/pp-members/ios/Members.app.dSYM.zip               |
+------------------------------------+--------------------------------------------------------------------------------------------------------+
[11:41:29]: Error uploading ipa file: 
 

+------+------------------------------+-------------+
|                 fastlane summary                  |
+------+------------------------------+-------------+

[!] Error uploading ipa file: 
| Step | Action                       | Time (in s) |
+------+------------------------------+-------------+
| 1    | default_platform             | 0           |
| 2    | app_store_connect_api_key    | 0           |
| 3    | increment_build_number       | 0           |
| 4    | update_app_identifier        | 0           |
| 5    | match_nuke                   | 16          |
| 6    | match                        | 255         |
| 7    | update_code_signing_settings | 0           |
| 8    | load_json                    | 0           |
| 9    | increment_version_number     | 0           |
| 10   | build_app                    | 410         |
| 💥   | upload_to_testflight         | 10          |
+------+------------------------------+-------------+

[11:41:29]: fastlane finished with errors
 
Error: Process completed with exit code 1.
</pre></details>

### Environment

<details>
  <pre><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                          |
| --------------------------- | ---------------------------------------------- |
| OS                          | 12.6                                           |
| Ruby                        | 3.0.2                                          |
| Bundler?                    | false                                          |
| Git                         | git version 2.32.0 (Apple Git-132)             |
| Installation Source         | /opt/homebrew/lib/ruby/gems/3.0.0/bin/fastlane |
| Host                        | macOS 12.6 (21G115)                            |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.0.2/lib            |
| OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                    |
| Is contained                | false                                          |
| Is homebrew                 | false                                          |
| Is installed via Fabric.app | false                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/    |
| Xcode Version               | 13.2.1                                         |
| Swift Version               | 5.5.2                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>
default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    key_id = ENV["ASC_KEY_ID"]
    issuer_id = ENV["ASC_ISSUER_ID"]
    # File.exist is going to use the current working directory which is ios/fastlane
    # so we must check parent directory if we want to make sure the file exists
    # HOWEVER when passing file path to fastlane functions, it expects paths relative to ios/
    # so when we set the resulting keypath if the file exists, it looks kinda weird. Here's why.
    key_path = ENV["KEY_PATH"]

    key = app_store_connect_api_key(
      key_id: key_id,
      issuer_id: issuer_id,
      key_filepath: key_path,
      duration: 500,
      in_house: false
    )

    increment_build_number(xcodeproj: "pushpressMembers.xcodeproj", build_number: Time.now.to_i)
    update_app_identifier(
      xcodeproj: "pushpressMembers.xcodeproj", # Optional path to xcodeproj, will use the first .xcodeproj if not set
      plist_path: "pushpressMembers/Info.plist", # Path to info plist file, relative to xcodeproj
      app_identifier: ENV["IOS_APP_ID"]  # The App Identifier
      )

    # PM-775 do not nuke certs for pushpress team
    # unless ENV["IOS_DEV_TEAM_ID"] == "LZ4HJM5FB2" Removing this just to test deployment since it's breaking
      match_nuke(
        skip_confirmation: true, 
        type: "appstore", 
        app_identifier: ENV["IOS_APP_ID"], 
        git_branch: ENV["IOS_DEV_TEAM_ID"], 
        team_id: ENV["IOS_DEV_TEAM_ID"], 
        api_key: key
      )
    # end

    match(
      type: "appstore", 
      app_identifier: ENV["IOS_APP_ID"], 
      git_branch: ENV["IOS_DEV_TEAM_ID"], 
      team_id: ENV["IOS_DEV_TEAM_ID"], 
      api_key: key
    )
    puts("sigh_" + ENV["IOS_APP_ID"] + "_appstore_profile-path")
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "pushpressMembers.xcodeproj",
      profile_uuid: ENV["sigh_" + ENV["IOS_APP_ID"] + "_appstore"],
      team_id: ENV["IOS_DEV_TEAM_ID"],
      code_sign_identity: "iPhone Distribution"
    )
    package = load_json(json_path: "../package.json")
    increment_version_number(version_number: package["version"])
    build_app(export_team_id: ENV["IOS_DEV_TEAM_ID"], workspace: "pushpressMembers.xcworkspace", scheme: "pushpressMembers", export_method: "app-store")
    upload_to_testflight(skip_waiting_for_build_processing: true, apple_id: ENV["ASC_APPLE_ID"], api_key: key)
    update_code_signing_settings(
      use_automatic_signing: true,
      path: "pushpressMembers.xcodeproj"
    )
  end
  lane :bump do
    package = load_json(json_path: "../package.json")
    increment_version_number(version_number: package["version"])
  end
 

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier(ENV["IOS_APP_ID"]) # The bundle identifier of your app
apple_id("memberapp@pushpress.com") # Your Apple email address

# itc_team_id("2197525") # App Store Connect Team ID
# team_id("LZ4HJM5FB2") # Developer Portal Team ID
team_id(ENV["IOS_DEV_TEAM_ID"]) # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.210.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-load_json | 0.0.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| faraday-cookie_jar              | 0.0.7        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| bundler                         | 2.2.22       |
| simctl                          | 1.6.8        |
| emoji_regex                     | 3.2.3        |
| tsort                           | 0.1.0        |
| uri                             | 0.10.1       |
| set                             | 1.0.1        |
| rexml                           | 3.2.5        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.1.0        |
| CFPropertyList                  | 3.0.5        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.22.0       |
| public_suffix                   | 5.0.0        |
| addressable                     | 2.8.1        |
| excon                           | 0.93.0       |
| ruby2_keywords                  | 0.0.5        |
| faraday-retry                   | 1.0.3        |
| faraday-rack                    | 1.0.0        |
| faraday-patron                  | 1.0.0        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-net_http                | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-httpclient              | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.10.2       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| json                            | 2.6.2        |
| dotenv                          | 2.8.1        |
| jwt                             | 2.5.0        |
| webrick                         | 1.7.0        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| signet                          | 0.17.0       |
| os                              | 1.1.4        |
| memoist                         | 0.16.2       |
| googleauth                      | 1.2.0        |
| mini_mime                       | 1.1.2        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.2        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| google-apis-core                | 0.9.0        |
| google-apis-playcustomapp_v1    | 0.11.0       |
| google-apis-androidpublisher_v3 | 0.29.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-apis-storage_v1          | 0.19.0       |
| google-apis-iamcredentials_v1   | 0.15.0       |
| google-cloud-errors             | 1.3.0        |
| google-cloud-env                | 1.6.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.43.0       |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.2        |
| aws-partitions                  | 1.644.0      |
| jmespath                        | 1.6.1        |
| aws-sdk-core                    | 3.159.0      |
| aws-sdk-kms                     | 1.58.0       |
| aws-sdk-s3                      | 1.114.0      |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.0        |
| date                            | 3.1.0        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.0        |
| securerandom                    | 0.1.0        |
| openssl                         | 2.2.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.2        |
| io-wait                         | 0.1.0        |
| zlib                            | 1.1.0        |
| resolv                          | 0.2.0        |
| digest                          | 3.0.0        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.0        |
| ostruct                         | 0.3.1        |
| strscan                         | 3.0.0        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.7        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| net-http                        | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| prettyprint                     | 0.1.0        |
| pp                              | 0.1.0        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.0        |
| fastlane-plugin-load_json       | 0.0.1        |
</details>

*generated on:* **2022-10-10**
</pre>
</details>

**Comment by dsokal** [comment]
You're seeing this error because your locally installed Transporter decided to upgrade itself from 2.3 to 3.0 :D 
The new version seems to be incompatible with the "old" ASC API key format. 

I think what could help is upgrading Xcode to 14. If I understand things correctly, for Xcode 14, fastlane uses `altool` - https://github.com/fastlane/fastlane/pull/20631

**Comment by knightbenax** [comment]
@dsokal wow, that seems on the right path because I did get a light warning from Transporter that it would be upgraded in a few days. Going to try the upgrade now

**Comment by knightbenax** [comment]
Updating to Xcode 14 worked. Closing now

**Comment by p16r** [comment]
Is there a way to reverse the Transporter upgrade for now? I can't update to Xcode 14 until after Ventura is out.

**Comment by p16r** [comment]
Update: This fix worked for me: https://github.com/fastlane/fastlane/issues/20741#issuecomment-1280687500
