### ISSUE TITLE
fastlane gym - code sign error with the exit code 65

### ISSUE THREAD

**Issue by Brad19** [fastlane/fastlane#20740]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

i'm in my initial days to understand  the fastlane builds and configs. And we have an existing implementation of fastlane build which I've mentioned below. 

At the moment, we have an issue similar to this one (https://github.com/fastlane/fastlane/issues/14859) where when i tried to build ios, it throws the message as follows.

```

** ARCHIVE FAILED **
--
13-Oct-2022 22:44:31 | INFO [2022-10-13 22:44:31.96]: ? The following build commands failed:
13-Oct-2022 22:44:31 | INFO [2022-10-13 22:44:31.96]: ?         CodeSign /Users/xxxx/Library/Developer/Xcode/DerivedData/XXXMobileApp-cfdtykzxfkwsrmcamwyyztrmcbal/Build/Intermediates.noindex/ArchiveIntermediates/ClubState/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/ClubStateNSE.appex (in target 'ClubStateNSE' from project 'XXXMobileApp')
13-Oct-2022 22:44:31 | INFO [2022-10-13 22:44:31.96]: ? (1 failure)
13-Oct-2022 22:44:31 | ** ARCHIVE FAILED **
```

### Environment

<details>
  <pre> 
Fastlane version :2.193.1
Bamboo CI/CD pipeline
Xcode version: 13.2.1
node: 14.8.1
ruby: 2.7.1</pre>
</details>

#### Action taken so far as below

1. The original issue was we found that the build showed the error as `Cert is invalid `(which in our case is expired). So in order to fix it, I went through docs and then used the easy approach i.e., first I nuked the distribution certificate and then used Matchfile to generate the  adhoc and appstore profile for all bundle identifiers which i saw the profiles that are getting created in apple developer portal. 
2. I logged in to Bamboo server and made sure that the Apple distribution cert,  Apple IPhone cert, private keys  and  Apple WorldWide developer cert are available in keychain. After that the cert invalid issue is `gone` and then the `code sign` issue emerged as mentioned above.
3. I saw the fastlane was throwing error to auto code signing being deprecated. So i updated to update_code_signing_settings.
4. Restarted Bamboo server couple of times.
5. I've logged in to bamboo server and when i ran to build archive ios, it throws `No code signing identity found and can not create a new one because you enabled `.  And I was trying to check this one (https://github.com/fastlane/fastlane/discussions/18272) which is similar the one, but when i verified the logs it has provisional profile set for debug and release.

Lastly before raising this issue, I opened the Xcode from the build server and checked Preferences -> accounts -> it says the Login session is expired. `Is this the main issue` or Am I missing anything else? 

Please advise as i need to resolve at the earliest since the time is short before we release to prod. 

Please let me know if you need any more details.

Thanks,
Brad

####  Our existing code below: 👇 

```
private_lane :get_release_notes do
  build_date = Time.now.strftime "%F"
  build_time = Time.now.strftime "%T"
  git_version = lane_context[GIT_VERSION]

  "#{git_version['BranchName']} branch (#{git_version['Sha']}) on #{build_date} at #{build_time} #{ENV['bamboo_resultsUrl']}"
end

lane :deploy_appcenter do
  json_paths = Dir[ARTIFACTS_PATH + "*.json"]

  json_paths.map do |json_path|
    json = JSON.parse(File.read(json_path), symbolize_names: true)
    release_notes = get_release_notes

    # The value of :platform need to be an instance of symbol for Variant
    json[:platform] = json[:platform].to_sym
    variant = Util::Variant.new json
    app = Util.camelcase variant.appcentre_app
    build = Util.camelcase variant.build
    basename = File.basename json_path, ".*"

    if variant.platform.to_s.eql? "ios"
      appcenter_upload \
        app_os: 'iOS',
        upload_build_only: true,
        app_name: "iOS-#{app}-#{build}",
        strict: 'true',
        file: (ARTIFACTS_PATH + "#{basename}.ipa").to_s,
        release_notes: release_notes
    else
      appcenter_upload \
        app_os: 'Android',
        upload_build_only: true,
        app_name: "Android-#{app}-#{build}",
        strict: 'true',
        file: (ARTIFACTS_PATH + "#{basename}.apk").to_s,
        release_notes: release_notes
    end
  end
end

platform :ios do
  lane :archive_apps do |options|
    # Resolve variants
    if options[:variants]
      variants = options[:variants]
    elsif options[:json_variants]
      json_variants = JSON.parse options[:json_variants], symbolize_names: true
      variants = json_variants.map do |json_variant|
        Util::Variant.new(
          **json_variant,
          platform: lane_context[SharedValues::PLATFORM_NAME],
          is_release: true
        )
      end
    else
      variants = get_variants(**options, is_release: true)
    end

    # Unlock SSH deploy
    unlock_keychain

    # Match profiles
    match_profiles variants: variants

    variants.each do |variant|
      # Update project profile
      main_bundle_id = variant.build_configs["bundle_identifier"]
      nse_bundle_id = variant.build_configs["bundle_identifier_nse"]
      target = Util.camelcase variant.target
      type = Util.camelcase variant.ios_profile_type

      unless main_bundle_id.nil?
        update_code_signing_settings \
          code_sign_identity: "iPhone Distribution",
          path: XCODE_PROJECT_PATH.to_s,
          profile_name: "match #{type} #{main_bundle_id}",
          targets: target
      end

      unless nse_bundle_id.nil?
        update_code_signing_settings \
          code_sign_identity: "iPhone Distribution",
          path: XCODE_PROJECT_PATH.to_s,
          profile_name: "match #{type} #{nse_bundle_id}",
          targets: "#{target}NSE"
      end

      # Archive
      output_name = "#{variant.appcentre_app}-#{SecureRandom.hex}"
      app_dsym_zip_path = ARTIFACTS_PATH + "#{output_name}.app.dSYM.zip"
      combined_dsym_zip_path = ARTIFACTS_PATH + "#{output_name}.dSYM.zip"
      meta_json_path = ARTIFACTS_PATH + "#{output_name}.json"
      src_map_path = ARTIFACTS_PATH + output_name + "index.ios.map"
      xcargs = variant.pre_build_envs.to_s(" ") + \
               " -UseModernBuildSystem=YES" \
               " IDEBuildOperationMaxNumberOfConcurrentCompileTasks=\"sysctl -n hw.ncpu\"" \
               " EXTRA_PACKAGER_ARGS=\"--sourcemap-output #{src_map_path}\""

      # Ensure sourcemap folder exists
      FileUtils.mkdir_p src_map_path.dirname, verbose: true

      # Build with Gym
      # Output files:
      #   - #{output_name}.ipa
      #   - #{output_name}.app.dSYM.zip
      #   - #{output_name}/index.ios.map
      gym \
        clean: true,
        export_method: variant.ios_profile_type,
        include_symbols: true,
        output_directory: ARTIFACTS_PATH.to_s,
        output_name: output_name,
        scheme: target,
        silent: true,
        suppress_xcode_output: true,
        workspace: XCODE_WORKSPACE_PATH.to_s,
        xcargs: xcargs

      # Generate variant json for the later deployment tasks
      # Output file:
      #   - #{output_name}.json
      File.write meta_json_path, variant.input_hash.to_h.to_json

      # Combine app dSYM and sourcemap
      # Output file:
      #   - #{output_name}.dSYM.zip
      # Removed files:
      #   - #{output_name}.app.dSYM.zip
      #   - #{output_name}/index.ios.map
      `zip -uvjm9 #{app_dsym_zip_path} #{src_map_path}`
      FileUtils.mv app_dsym_zip_path, combined_dsym_zip_path, verbose: true
      FileUtils.rm_rf src_map_path.dirname, verbose: true
    end
  end
end
```
##### Logs

<details>
  <pre> 

3-Oct-2022 17:56:50 | INFO [2022-10-13 17:56:50.83]: ? ** ARCHIVE FAILED **
-- | --
13-Oct-2022 17:56:50 | INFO [2022-10-13 17:56:50.83]: ? The following build commands failed:
13-Oct-2022 17:56:50 | INFO [2022-10-13 17:56:50.83]: ?         CodeSign /Users/xxxx/Library/Developer/Xcode/DerivedData/XXXMobileApp-cfdtykzxfkwsrmcamwyyztrmcbal/Build/Intermediates.noindex/ArchiveIntermediates/ClubState/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/ClubStateNSE.appex (in target 'ClubStateNSE' from project 'xxxMobileApp')
13-Oct-2022 17:56:50 | INFO [2022-10-13 17:56:50.83]: ? (1 failure)
13-Oct-2022 17:56:50 | ** ARCHIVE FAILED **
13-Oct-2022 17:56:50 |  
13-Oct-2022 17:56:50 |  
13-Oct-2022 17:56:50 | The following build commands failed:
13-Oct-2022 17:56:50 | CodeSign /Users/xxxxx/Library/Developer/Xcode/DerivedData/XXXMobileApp-cfdtykzxfkwsrmcamwyyztrmcbal/Build/Intermediates.noindex/ArchiveIntermediates/ClubState/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/ClubStateNSE.appex (in target 'ClubStateNSE' from project 'XXXMobileApp')
13-Oct-2022 17:56:50 | (1 failure)
13-Oct-2022 17:56:50 | ERROR [2022-10-13 17:56:50.86]: Exit status: 65
13-Oct-2022 17:56:50 |  
13-Oct-2022 17:56:50 | +---------------+-------------------------------------------------+
13-Oct-2022 17:56:50 | \|                        Build environment                        \|
13-Oct-2022 17:56:50 | +---------------+-------------------------------------------------+
13-Oct-2022 17:56:50 | \| xcode_path    \| /Users/xxxx/Downloads/Xcode.app \|
13-Oct-2022 17:56:50 | \| gym_version   \| 2.193.1                                         \|
13-Oct-2022 17:56:50 | \| export_method \| ad-hoc                                          \|
13-Oct-2022 17:56:50 | \| sdk           \| iPhoneOS15.2.sdk                                \|
13-Oct-2022 17:56:50 | +---------------+-------------------------------------------------+
13-Oct-2022 17:56:50 |  
13-Oct-2022 17:56:50 | INFO [2022-10-13 17:56:50.88]: ? /Users/xxxx/bamboo-agent-home/xml-data/build-dir/CA-BPR761-JOB1/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'SDWebImageWebPCoder' from project 'Pods')
13-Oct-2022 17:56:50 | INFO [2022-10-13 17:56:50.88]: ? /Users/xxxxx/bamboo-agent-home/xml-data/build-dir/CA-BPR761-JOB1/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'RNSentry' from project 'Pods')
13-Oct-2022 17:56:50 | INFO [2022-10-13 17:56:50.88]: ? /Users/xxxxx/bamboo-agent-home/xml-data/build-dir/CA-BPR761-JOB1/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'SVGKit' from project 'Pods')
13-Oct-2022 17:56:50 | INFO [2022-10-13 17:56:50.88]: ? /Users/xxxxx/bamboo-agent-home/xml-data/build-dir/CA-BPR761-JOB1/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'OneSignal' from project 'Pods')
13-Oct-2022 17:56:50 | INFO [2022-10-13 17:56:50.88]: ? /Users/xxxxx/bamboo-agent-home/xml-data/build-dir/CA-BPR761-JOB1/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'AppAuth' from project 'Pods')
13-Oct-2022 17:56:50 | INFO [2022-10-13 17:56:50.88]:
13-Oct-2022 17:56:50 | ERROR [2022-10-13 17:56:50.88]: ??  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
13-Oct-2022 17:56:50 | WARN [2022-10-13 17:56:50.88]: ?  For the complete and more detailed error log, check the full log at:
13-Oct-2022 17:56:50 | WARN [2022-10-13 17:56:50.88]: ?  /Users/xxxxx/Library/Logs/gym/ClubState-ClubState.log
13-Oct-2022 17:56:50 | INFO [2022-10-13 17:56:50.88]:
13-Oct-2022 17:56:50 | ERROR [2022-10-13 17:56:50.88]: Looks like fastlane ran into a build/archive error with your project
13-Oct-2022 17:56:50 | ERROR [2022-10-13 17:56:50.88]: It's hard to tell what's causing the error, so we wrote some guides on how
13-Oct-2022 17:56:50 | ERROR [2022-10-13 17:56:50.88]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
13-Oct-2022 17:56:50 | ERROR [2022-10-13 17:56:50.88]: Before submitting an issue on GitHub, please follow the guide above and make
13-Oct-2022 17:56:50 | ERROR [2022-10-13 17:56:50.88]: sure your project is set up correctly.
13-Oct-2022 17:56:50 | ERROR [2022-10-13 17:56:50.88]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
13-Oct-2022 17:56:50 | ERROR [2022-10-13 17:56:50.88]: the full commands printed out in yellow in the above log.
13-Oct-2022 17:56:50 | ERROR [2022-10-13 17:56:50.88]: Make sure to inspect the output above, as usually you'll find more error information there

3-Oct-2022 22:44:32 | WARN [2022-10-13 22:44:32.01]: Lane Context:
-- | --
13-Oct-2022 22:44:32 | INFO [2022-10-13 22:44:32.01]: {:PLATFORM_NAME=>:ios, :LANE_NAME=>"ios archive_apps", "GIT_VERSION"=>{"Major"=>2, "Minor"=>2, "Patch"=>0, "PreReleaseTag"=>"test-build-fail-1.1", "PreReleaseTagWithDash"=>"-test-build-fail-1.1", "PreReleaseLabel"=>"test-build-fail-1", "PreReleaseNumber"=>1, "BuildMetaData"=>7, "BuildMetaDataPadded"=>"0007", "FullBuildMetaData"=>"7.Branch.test-build-fail-1.Sha.27d38aa991cd776125681103bfe387cbf7d9db69", "MajorMinorPatch"=>"2.2.0", "SemVer"=>"2.2.0-test-build-fail-1.1", "LegacySemVer"=>"2.2.0-test-build-fail-1-1", "LegacySemVerPadded"=>"2.2.0-test-build-fail-0001", "AssemblySemVer"=>"2.2.0.0", "AssemblySemFileVer"=>"2.2.0.0", "FullSemVer"=>"2.2.0-test-build-fail-1.1+7", "InformationalVersion"=>"2.2.0-test-build-fail-1.1+7.Branch.test-build-fail-1.Sha.27d38aa991cd776125681103bfe387cbf7d9db69", "BranchName"=>"test-build-fail-1", "Sha"=>"27d38aa991cd776125681103bfe387cbf7d9db69", "ShortSha"=>"27d38aa", "NuGetVersionV2"=>"2.2.0-test-build-fail-0001", "NuGetVersion"=>"2.2.0-test-build-fail-0001", "NuGetPreReleaseTagV2"=>"test-build-fail-0001", "NuGetPreReleaseTag"=>"test-build-fail-0001", "CommitsSinceVersionSource"=>7, "CommitsSinceVersionSourcePadded"=>"0007", "CommitDate"=>"2022-10-13"}, "NATIVE_VERSION"=>"7.1.0", :SIGH_PROFILE_TYPE=>"ad-hoc", :MATCH_PROVISIONING_PROFILE_MAPPING=>{"au.com.xxx.xxxxx.qa"=>"match AdHoc au.com.xxx.xxxx.qa", "au.com.xxx.xxxx.qa.nse"=>"match AdHoc au.com.xxx.xxxxx.qa.nse", "au.com.xxx.xxx.qa"=>"match AdHoc au.com.xx.xxxx.qa", "au.com.xxx.xxxx.qa.nse"=>"match AdHoc au.com.xxx.xxxx.qa.nse", "au.com.xxx.xxx.qa"=>"match AdHoc au.com.xxxx.xxxx.qa", "au.com.xxx.xxx.qa.nse"=>"match AdHoc au.com.xxx.xxx.qa.nse", "com.xxxx.xxxx.qa"=>"match AdHoc com.xxxx.xxx.qa", "com.xxx.xxx.qa.nse"=>"match AdHoc com.xxx.xxx.qa.nse"}}
13-Oct-2022 22:44:32 | ERROR [2022-10-13 22:44:32.01]: Error building the application - see the log above

 </pre>
</details>

**Comment by Brad19** [comment]
I've finally managed to fix this issue as i found that the `code signing identity` for the `Build settings -> release` in the Xcode has to be Apple distribution from the Team for `any ios sdk` and not the ios distribution in our case and there were 2 versions of Apple worldwide Developer Relations Certificate which i removed the latest one.

**Comment by acoutts** [comment]
Great find!! In my case I also use `get_provisioning_profile` and `update_project_provisioning` in CI to fetch the right profiles. I previously used `iPhone Distribution` and had to update it to `Apple Distribution` now.
I do this so the xcode project checked in has the developer profile set for release builds (so we can easily test release builds), and in CI it flips that to distribution to build the right binary. That way we don't have to worry about the right code signing setting being checked in and potentially breaking CI if someone forgets to set it back.

**Comment by Brad19** [comment]
Nice @acoutts 
The documentation of fastlane shows only about ios distribution. Looks like something is changed. I was kind of sweating and worth investigating.

**Comment by acoutts** [comment]
Somehow my xcode project had a bunch of sub-settings for `Any iOS sdk` added, so when my script called `update_project_provisioning`, it was updating the root level setting (ie: the build variant name) but not the new sub-setting for `any ios sdk`, which meant my builds actually failed.

**Comment by Brad19** [comment]
In my case the root level has `ios distribution`, but for `any ios sdk`, it is `Apple distribution` from Team. It was not like that earlier i suppose.
