### ISSUE TITLE
Pilot failure - altool missing CFBundlePackageType - macOS Ventura - Xcode 14.0.1

### ISSUE THREAD

**Issue by fbaumgart** [fastlane/fastlane#20813]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Hello,
after upgrading Xcode to 14.0.1 and macOS to Ventura on Mac mini M1 the pilot command now fails to send package to TestFlight.
altool finishes with the error: `Error: Could not determine the package’s bundle ID. The package is missing an Info.plist or the CFBundlePackageType is not ‘APPL’ or ‘FMWK’. Unable to validate your application. (-21017)`
I have already checked my project and all application targets' Info.plist files contain proper information. 
Fastlane is invoked in jenkins environment, but locally it fails in the same way.

I wonder if altool should try to upload .itmsp package? 

Expected behaviour: fastlane is able to upload the package correctly to TestFlight as in the previous version

##### Complete output when running fastlane, including the stack trace and command used

<details>
INFO [2022-10-28 15:04:35.53]: [32m----------------------------------[0m

INFO [2022-10-28 15:04:35.53]: [32m--- Step: upload_to_testflight ---[0m

INFO [2022-10-28 15:04:35.53]: [32m----------------------------------[0m

INFO [2022-10-28 15:04:35.53]: Creating authorization token for App Store Connect API

INFO [2022-10-28 15:04:35.53]: [32mReady to upload new build to TestFlight (App: 1220925463)...[0m

DEBUG [2022-10-28 15:04:35.58]: App Platform (iOS)

INFO [2022-10-28 15:04:35.78]: [32mWrote XML data to '/var/folders/pv/3jycc90x1qz7h4g1s_vzwf94vcf7sj/T/d20221028-61555-oorr4w/1220925463-498f22cd-889e-40e6-ae2c-697400081359.itmsp'[0m
DEBUG [2022-10-28 15:04:35.78]: Using altool as transporter.
INFO [2022-10-28 15:04:35.78]: Going to upload updated app to App Store Connect
INFO [2022-10-28 15:04:35.78]: [32mThis might take a few minutes. Please don't interrupt the script.[0m
DEBUG [2022-10-28 15:04:35.78]: API_PRIVATE_KEYS_DIR=YourTmpP8KeyDir xcrun altool --upload-app --apiKey YourKeyID --apiIssuer YourIssuerID -t ios -f /var/folders/pv/3jycc90x1qz7h4g1s_vzwf94vcf7sj/T/d20221028-61555-oorr4w/1220925463-498f22cd-889e-40e6-ae2c-697400081359.itmsp -k 100000
DEBUG [2022-10-28 15:04:37.34]: [altool]:  {

DEBUG [2022-10-28 15:04:37.34]: [altool]:     NSLocalizedDescription = "Could not determine the package\U2019s bundle ID. The package is missing an Info.plist or the CFBundlePackageType is not \U2018APPL\U2019 or \U2018FMWK\U2019.";

DEBUG [2022-10-28 15:04:37.34]: [altool]:     NSLocalizedFailureReason = "Unable to validate your application.";

DEBUG [2022-10-28 15:04:37.34]: [altool]: }

WARN [2022-10-28 15:04:37.34]: [33m[altool] 2022-10-28 15:04:37.340 *** Error: Could not determine the package’s bundle ID. The package is missing an Info.plist or the CFBundlePackageType is not ‘APPL’ or ‘FMWK’. Unable to validate your application. (-21017)
[0m
WARN [2022-10-28 15:04:37.34]: [33m[altool]  {
[0m
WARN [2022-10-28 15:04:37.34]: [33m[altool]     NSLocalizedDescription = "Could not determine the package\U2019s bundle ID. The package is missing an Info.plist or the CFBundlePackageType is not \U2018APPL\U2019 or \U2018FMWK\U2019.";
[0m
WARN [2022-10-28 15:04:37.34]: [33m[altool]     NSLocalizedFailureReason = "Unable to validate your application.";
[0m
WARN [2022-10-28 15:04:37.34]: [33m[altool] }
[0m
INFO [2022-10-28 15:04:37.34]: Application Loader output above ^
ERROR [2022-10-28 15:04:37.34]: [31mError uploading '/var/folders/pv/3jycc90x1qz7h4g1s_vzwf94vcf7sj/T/d20221028-61555-oorr4w/1220925463-498f22cd-889e-40e6-ae2c-697400081359.itmsp'.
[0m
ERROR [2022-10-28 15:04:37.34]: [31mCould not determine the package’s bundle ID. The package is missing an Info.plist or the CFBundlePackageType is not ‘APPL’ or ‘FMWK’. Unable to validate your application. (-21017)
[0m
ERROR [2022-10-28 15:04:37.34]: [31mThe call to the altool completed with a non-zero exit status: 1. This indicates a failure.[0m
ERROR [2022-10-28 15:04:37.34]: [31mCould not download/upload from App Store Connect![0m
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 13.0                                                       |
| Ruby                        | 3.1.2                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.37.0 (Apple Git-136)                         |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.210.1/libexec/bin/fastlane |
| Host                        | macOS 13.0 (22A380)                                        |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.1.2_1/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1q  5 Jul 2022                                 |
| Is contained                | false                                                      |
| Is homebrew                 | true                                                       |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
| Xcode Version               | 14.0.1                                                     |
| Swift Version               | 5.7                                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.210.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| addressable                     | 2.8.1        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.92.4       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.2       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.6.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.8.1        |
| bundler                         | 2.3.11       |
| simctl                          | 1.6.8        |
| jwt                             | 2.5.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.2.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.9.0        |
| google-apis-playcustomapp_v1    | 0.10.0       |
| google-apis-androidpublisher_v3 | 0.27.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.14.0       |
| google-apis-storage_v1          | 0.17.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.42.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.6.1        |
| aws-partitions                  | 1.633.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.1        |
| aws-sdk-core                    | 3.151.0      |
| aws-sdk-kms                     | 1.58.0       |
| aws-sdk-s3                      | 1.114.0      |
| set                             | 1.0.2        |
| public_suffix                   | 5.0.0        |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.1        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.1        |
| uri                             | 0.11.0       |
| openssl                         | 3.0.0        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.0        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.2        |
| net-http                        | 0.2.0        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.11       |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.3        |
</details>

*generated on:* **2022-11-02**
</details>

**Comment by nachkarjc** [comment]
Have the same issue any idea how to fix it ? Already tried : ENV['ITMSTRANSPORTER_FORCE_ITMS_PACKAGE_UPLOAD'] = 'true'

**Comment by mittenimraum** [comment]
Same for Xcode 14.1 (14B47b)

**Comment by fbaumgart** [comment]
Found reference to this problem in this issue and comment: https://github.com/fastlane/fastlane/issues/20741#issuecomment-1286699506
but not sure if this is really a solution

**Comment by fbaumgart** [comment]
I have succeeded to upload the package - the resolution was to remove the workaround for iTMS Transporter mentioned in #20741 

So basically I removed ENV['ITMSTRANSPORTER_FORCE_ITMS_PACKAGE_UPLOAD'] = 'true' from my code and now it works.

**Comment by HeadmasterHong** [comment]
I had the same problem this week. The resolution was to set ENV['ITMSTRANSPORTER_FORCE_ITMS_PACKAGE_UPLOAD'] = 'false', also you can basically removed it from your code.
I dont know the reson why we set it TRUE before. After reading the source code of Fastlane, i konw that this parameter is used to force to  upload in .itmsp.

**Comment by 2sem** [comment]
> I had the same problem this week. The resolution was to set ENV['ITMSTRANSPORTER_FORCE_ITMS_PACKAGE_UPLOAD'] = 'false', also you can basically removed it from your code. I dont know the reson why we set it TRUE before. After reading the source code of Fastlane, i konw that this parameter is used to force to upload in .itmsp.

https://github.com/fastlane/fastlane/issues/20741
