### ISSUE TITLE
Building iOS/Catalyst app assumes `.ipa` instead of `.pgk` file

### ISSUE THREAD

**Issue by NachoSoto** [fastlane/fastlane#20826]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Command executed
```ruby
build_app(
  workspace: "workspace.xcworkspace",
  scheme: "scheme",
  destination: 'platform=macOS,variant=Mac Catalyst',
  xcodebuild_formatter: '',
  catalyst_platform: 'ios',
  installer_cert_name: installer_cert_name,
  codesigning_identity: codesign_identity,
  # skip_package_ipa: true,
  export_options: {
    provisioningProfiles: {
      "bundle_id" => "match AppStore bundle_id catalyst"
    },
    installerSigningCertificate: installer_cert_name,
    signingCertificate: codesign_identity
  }
)
upload_to_app_store(
  skip_metadata: true,
  skip_screenshots: true,
  automatic_release: true,
  submit_for_review: false,
  run_precheck_before_submit: false,
  platform: 'osx'
)
```

This fails with the following error:
> IPA invalid

Looking [at the code](https://github.com/fastlane/fastlane/blob/fastlane/2.210.1/gym/lib/gym/runner.rb#L35), it looks like it's assuming that an iOS app has an IPA. However, in this case, the iOS Catalyst app generates a `.pkg` file.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
[16:40:30]: ▸ ** ARCHIVE SUCCEEDED ** [19.401 sec]
[16:40:30]: Generated plist file with the following values:
[16:40:30]: ▸ -----------------------------------------
[16:40:30]: ▸ {
[16:40:30]: ▸   "provisioningProfiles": {
[16:40:30]: ▸     "bundle_id": "match AppStore bundle_id catalyst"
[16:40:30]: ▸   },
[16:40:30]: ▸   "installerSigningCertificate": "3rd Party Mac Developer Installer: XXX, Inc. (xxx)",
[16:40:30]: ▸   "signingCertificate": "Apple Distribution: XXX, Inc. (xxx)",
[16:40:30]: ▸   "method": "app-store",
[16:40:30]: ▸   "signingStyle": "manual"
[16:40:30]: ▸ }
[16:40:30]: ▸ -----------------------------------------
[16:40:30]: $ /usr/bin/xcrun /Users/nachosoto/.gems/gems/fastlane-2.210.1/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/wc/zf_ws3kn4w31s3g6jzhjsvlm0000gn/T/gym_config20221104-76905-1ep208n.plist' -archivePath /Users/nachosoto/Library/Developer/Xcode/Archives/2022-11-04/Project\ 2022-11-04\ 16.40.10.xcarchive -exportPath '/var/folders/wc/zf_ws3kn4w31s3g6jzhjsvlm0000gn/T/gym_output20221104-76905-1hnbk62'
[16:40:37]: Compressing 1 dSYM(s)
[16:40:37]: $ cd '/Users/nachosoto/Library/Developer/Xcode/Archives/2022-11-04/Project 2022-11-04 16.40.10.xcarchive/dSYMs' && zip -r '/Users/nachosoto/dev/Project/Project.app.dSYM.zip' *.dSYM
[16:40:37]: ▸ updating: Project.app.dSYM/ (stored 0%)
[16:40:37]: ▸ updating: Project.app.dSYM/Contents/ (stored 0%)
[16:40:37]: ▸ updating: Project.app.dSYM/Contents/Resources/ (stored 0%)
[16:40:37]: ▸ updating: Project.app.dSYM/Contents/Resources/DWARF/ (stored 0%)
[16:40:37]: ▸ updating: Project.app.dSYM/Contents/Resources/DWARF/Project (deflated 68%)
[16:40:37]: ▸ updating: Project.app.dSYM/Contents/Info.plist (deflated 52%)

[16:40:37]: Successfully exported and compressed dSYM file
+------------------------------------+-----------------------------------------------+
|                                    Lane Context                                    |
+------------------------------------+-----------------------------------------------+
| DEFAULT_PLATFORM                   | ios                                           |
| PLATFORM_NAME                      | ios                                           |
| LANE_NAME                          | ios deploy_project                    |
| LATEST_TESTFLIGHT_BUILD_NUMBER     | 8                                             |
| LATEST_TESTFLIGHT_VERSION          | 1.0                                           |
| BUILD_NUMBER                       | 9                                             |
| SIGH_PROFILE_TYPE                  | app-store                                     |
| MATCH_PROVISIONING_PROFILE_MAPPING | {"bundle_id"=>"match AppStore  |
|                                    | bundle_id macos"}              |
+------------------------------------+-----------------------------------------------+
[16:40:37]: IPA invalid
</pre>
</details>

### Environment
<details>
  <pre>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 13.1                                                           |
| Ruby                        | 2.6.10                                                         |
| Bundler?                    | true                                                           |
| Git                         | git version 2.36.1                                             |
| Installation Source         | ~/.gems/bin/fastlane                                           |
| Host                        | macOS 13.1 (22C5033e)                                          |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 14.1                                                           |
| Swift Version               | 5.7.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
import("../../../../fastlane/Fastfile")

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.revenuecat.sampleapp"
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.210.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                              | Version | Update-Status  |
| ----------------------------------- | ------- | -------------- |
| fastlane-plugin-create_xcframework  | 1.1.2   | ✅ Up-To-Date   |
| fastlane-plugin-revenuecat_internal | 0.1.0   | 💥 Check failed |

<details><summary><b>Loaded gems</b></summary>

| Gem                                 | Version      |
| ----------------------------------- | ------------ |
| did_you_mean                        | 1.3.0        |
| bundler                             | 2.3.6        |
| rake                                | 13.0.6       |
| rexml                               | 3.2.5        |
| CFPropertyList                      | 3.0.5        |
| concurrent-ruby                     | 1.1.10       |
| i18n                                | 1.12.0       |
| minitest                            | 5.16.2       |
| tzinfo                              | 2.0.5        |
| zeitwerk                            | 2.6.0        |
| activesupport                       | 6.1.6.1      |
| public_suffix                       | 4.0.7        |
| addressable                         | 2.8.1        |
| httpclient                          | 2.8.3        |
| json                                | 2.6.2        |
| algoliasearch                       | 1.27.5       |
| artifactory                         | 3.0.15       |
| atomos                              | 0.1.3        |
| aws-eventstream                     | 1.2.0        |
| aws-partitions                      | 1.650.0      |
| aws-sigv4                           | 1.5.2        |
| jmespath                            | 1.6.1        |
| aws-sdk-core                        | 3.164.0      |
| aws-sdk-kms                         | 1.58.0       |
| aws-sdk-s3                          | 1.116.0      |
| babosa                              | 1.0.4        |
| claide                              | 1.1.0        |
| colored2                            | 3.1.2        |
| cork                                | 0.3.0        |
| nap                                 | 1.1.0        |
| open4                               | 1.3.4        |
| claide-plugins                      | 0.9.2        |
| fuzzy_match                         | 2.0.4        |
| netrc                               | 0.11.0       |
| ffi                                 | 1.15.5       |
| ethon                               | 0.15.0       |
| typhoeus                            | 1.4.0        |
| cocoapods-core                      | 1.11.3       |
| cocoapods-deintegrate               | 1.0.5        |
| cocoapods-downloader                | 1.6.3        |
| cocoapods-plugins                   | 1.0.0        |
| cocoapods-search                    | 1.0.1        |
| cocoapods-trunk                     | 1.6.0        |
| cocoapods-try                       | 1.2.0        |
| escape                              | 0.0.4        |
| fourflusher                         | 2.3.1        |
| gh_inspector                        | 1.1.3        |
| molinillo                           | 0.8.0        |
| ruby-macho                          | 2.5.1        |
| nanaimo                             | 0.3.0        |
| xcodeproj                           | 1.22.0       |
| cocoapods                           | 1.11.3       |
| colored                             | 1.2          |
| highline                            | 2.0.3        |
| commander                           | 4.6.0        |
| faraday-em_http                     | 1.0.0        |
| faraday-em_synchrony                | 1.0.0        |
| faraday-excon                       | 1.1.0        |
| faraday-httpclient                  | 1.0.1        |
| multipart-post                      | 2.0.0        |
| faraday-multipart                   | 1.0.4        |
| faraday-net_http                    | 1.0.1        |
| faraday-net_http_persistent         | 1.2.0        |
| faraday-patron                      | 1.0.0        |
| faraday-rack                        | 1.0.0        |
| faraday-retry                       | 1.0.3        |
| ruby2_keywords                      | 0.0.5        |
| faraday                             | 1.10.2       |
| faraday-http-cache                  | 2.4.1        |
| rchardet                            | 1.8.0        |
| git                                 | 1.11.0       |
| kramdown                            | 2.4.0        |
| kramdown-parser-gfm                 | 1.1.0        |
| no_proxy_fix                        | 0.1.2        |
| sawyer                              | 0.9.2        |
| octokit                             | 4.25.1       |
| unicode-display_width               | 1.8.0        |
| terminal-table                      | 1.8.0        |
| danger                              | 8.6.1        |
| declarative                         | 0.0.20       |
| digest-crc                          | 0.6.4        |
| unf_ext                             | 0.0.8.2      |
| unf                                 | 0.1.4        |
| domain_name                         | 0.5.20190701 |
| dotenv                              | 2.8.1        |
| emoji_regex                         | 3.2.3        |
| excon                               | 0.93.1       |
| http-cookie                         | 1.0.5        |
| faraday-cookie_jar                  | 0.0.7        |
| faraday_middleware                  | 1.2.0        |
| fastimage                           | 2.2.6        |
| jwt                                 | 2.5.0        |
| memoist                             | 0.16.2       |
| multi_json                          | 1.15.0       |
| os                                  | 1.1.4        |
| signet                              | 0.17.0       |
| googleauth                          | 1.3.0        |
| mini_mime                           | 1.1.2        |
| trailblazer-option                  | 0.1.2        |
| uber                                | 0.1.0        |
| representable                       | 3.2.0        |
| retriable                           | 3.1.2        |
| webrick                             | 1.7.0        |
| google-apis-core                    | 0.9.1        |
| google-apis-androidpublisher_v3     | 0.29.0       |
| google-apis-playcustomapp_v1        | 0.12.0       |
| google-apis-iamcredentials_v1       | 0.15.0       |
| google-apis-storage_v1              | 0.19.0       |
| google-cloud-env                    | 1.6.0        |
| google-cloud-errors                 | 1.3.0        |
| google-cloud-core                   | 1.6.0        |
| google-cloud-storage                | 1.43.0       |
| mini_magick                         | 4.11.0       |
| naturally                           | 2.2.1        |
| optparse                            | 0.1.1        |
| plist                               | 3.6.0        |
| rubyzip                             | 2.3.2        |
| security                            | 0.1.3        |
| simctl                              | 1.6.8        |
| terminal-notifier                   | 2.0.0        |
| tty-screen                          | 0.8.1        |
| tty-cursor                          | 0.7.1        |
| tty-spinner                         | 0.9.3        |
| word_wrap                           | 1.0.0        |
| rouge                               | 2.0.7        |
| xcpretty                            | 0.3.0        |
| xcpretty-travis-formatter           | 1.0.1        |
| fastlane-plugin-create_xcframework  | 1.1.2        |
| fastlane-plugin-revenuecat_internal | 0.1.0        |
| mustache                            | 1.1.1        |
| redcarpet                           | 3.5.1        |
| sassc                               | 2.4.0        |
| sqlite3                             | 1.4.4        |
| liferaft                            | 0.0.6        |
| xcinvoke                            | 0.3.0        |
| jazzy                               | 0.14.2       |
</details>

*generated on:* **2022-11-04**
</details>
</pre>
</details>

**Comment by macblazer** [comment]
@NachoSoto If the "Command Executed" details you listed are correct, you've got a mis-match in parameters for the `build_app` command.  The `destination` parameter is calling for macOS Catalyst, but you're also telling it the `catalyst_platform` of `iOS`.  You should probably change the `catalyst_platform` to `macos`, and try again.

```
build_app(
...
  destination: 'platform=macOS,variant=Mac Catalyst',
...
  catalyst_platform: 'ios',
...
  }
)
upload_to_app_store(
...
  platform: 'osx'
)
```
