### ISSUE TITLE
[iTunes Transporter]: SocketException: No buffer space available - unable to upload app to TestFlight

### ISSUE THREAD

**Issue by shliama** [fastlane/fastlane#20832]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Uploading the iOS build to TestFlight fails with `java.net.SocketException: No buffer space available`

This started to happen a week ago and since then I couldn't upload a single build (the archive is built correctly since I can find it inside the Xcode Organizer and upload the archive manually)

Looks like a similar issue https://github.com/fastlane/fastlane/issues/16892

##### Command executed
`pilot(api_key: api_key, skip_waiting_for_build_processing: true)`

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>
[06:46:56]: -------------------
[06:46:56]: --- Step: pilot ---
[06:46:56]: -------------------
[06:46:56]: Creating authorization token for App Store Connect API
[06:46:58]: Ready to upload new build to TestFlight (App: ***********)...
[06:47:00]: Going to upload updated app to App Store Connect
[06:47:00]: This might take a few minutes. Please don't interrupt the script.
[06:49:06]: Transporter transfer failed.
[06:49:06]: 
[06:49:06]: An un-handled exception occurred: java.net.SocketException: No buffer space available for (id: b6a89ad9-e8b7-41aa-8616-a4633f59f46f file: a92c2864-3fdd-4705-9d14-cd31691738d2.ipa part: 24)
An un-handled exception occurred: java.net.SocketException: No buffer space available for (id: b6a89ad9-e8b7-41aa-8616-a4633f59f46f file: a92c2864-3fdd-4705-9d14-cd31691738d2.ipa part: 6)
java.util.concurrent.ExecutionException: java.net.SocketException: No buffer space available
An un-handled exception occurred: java.net.SocketException: No buffer space available for (id: b6a89ad9-e8b7-41aa-8616-a4633f59f46f file: a92c2864-3fdd-4705-9d14-cd31691738d2.ipa part: 8)
An un-handled exception occurred: java.net.SocketException: No buffer space available for (id: b6a89ad9-e8b7-41aa-8616-a4633f59f46f file: a92c2864-3fdd-4705-9d14-cd31691738d2.ipa part: 16)
An un-handled exception occurred: java.net.SocketException: No buffer space available for (id: b6a89ad9-e8b7-41aa-8616-a4633f59f46f file: a92c2864-3fdd-4705-9d14-cd31691738d2.ipa part: 19)
An un-handled exception occurred: java.net.SocketException: No buffer space available for (id: b6a89ad9-e8b7-41aa-8616-a4633f59f46f file: a92c2864-3fdd-4705-9d14-cd31691738d2.ipa part: 12)
An un-handled exception occurred: java.net.SocketException: No buffer space available for (id: b6a89ad9-e8b7-41aa-8616-a4633f59f46f file: a92c2864-3fdd-4705-9d14-cd31691738d2.ipa part: 17)
java.util.concurrent.ExecutionException: java.net.SocketException: No buffer space available
java.util.concurrent.ExecutionException: java.net.SocketException: No buffer space available
An un-handled exception occurred: java.net.SocketException: No buffer space available for (id: b6a89ad9-e8b7-41aa-8616-a4633f59f46f file: a92c2864-3fdd-4705-9d14-cd31691738d2.ipa part: 31)
java.util.concurrent.ExecutionException: java.net.SocketException: No buffer space available
java.util.concurrent.ExecutionException: java.net.SocketException: No buffer space available
An un-handled exception occurred: java.net.SocketException: No buffer space available for (id: b6a89ad9-e8b7-41aa-8616-a4633f59f46f file: a92c2864-3fdd-4705-9d14-cd31691738d2.ipa part: 2)
An un-handled exception occurred: javax.net.ssl.SSLException: Couldn't kickstart handshaking for (id: b6a89ad9-e8b7-41aa-8616-a4633f59f46f file: a92c2864-3fdd-4705-9d14-cd31691738d2.ipa part: 22)
An un-handled exception occurred: javax.net.ssl.SSLException: Couldn't kickstart handshaking for (id: b6a89ad9-e8b7-41aa-8616-a4633f59f46f file: a92c2864-3fdd-4705-9d14-cd31691738d2.ipa part: 14)
An un-handled exception occurred: javax.net.ssl.SSLException: Couldn't kickstart handshaking for (id: b6a89ad9-e8b7-41aa-8616-a4633f59f46f file: a92c2864-3fdd-4705-9d14-cd31691738d2.ipa part: 25)
An un-handled exception occurred: javax.net.ssl.SSLException: Couldn't kickstart handshaking for (id: b6a89ad9-e8b7-41aa-8616-a4633f59f46f file: a92c2864-3fdd-4705-9d14-cd31691738d2.ipa part: 9)
An un-handled exception occurred: javax.net.ssl.SSLException: Couldn't kickstart handshaking for (id: b6a89ad9-e8b7-41aa-8616-a4633f59f46f file: a92c2864-3fdd-4705-9d14-cd31691738d2.ipa part: 10)
An un-handled exception occurred: javax.net.ssl.SSLException: Couldn't kickstart handshaking for (id: b6a89ad9-e8b7-41aa-8616-a4633f59f46f file: a92c2864-3fdd-4705-9d14-cd31691738d2.ipa part: 29)
An un-handled exception occurred: javax.net.ssl.SSLException: Couldn't kickstart handshaking for (id: b6a89ad9-e8b7-41aa-8616-a4633f59f46f file: a92c2864-3fdd-4705-9d14-cd31691738d2.ipa part: 23)
An un-handled exception occurred: javax.net.ssl.SSLException: Couldn't kickstart handshaking for (id: b6a89ad9-e8b7-41aa-8616-a4633f59f46f file: a92c2864-3fdd-4705-9d14-cd31691738d2.ipa part: 15)
An un-handled exception occurred: javax.net.ssl.SSLException: Couldn't kickstart handshaking for (id: b6a89ad9-e8b7-41aa-8616-a4633f59f46f file: a92c2864-3fdd-4705-9d14-cd31691738d2.ipa part: 33)
An un-handled exception occurred: java.net.SocketException: No buffer space available for (id: b6a89ad9-e8b7-41aa-8616-a4633f59f46f file: a92c2864-3fdd-4705-9d14-cd31691738d2.ipa part: 20)
java.util.concurrent.ExecutionException: java.net.SocketException: No buffer space available
java.util.concurrent.ExecutionException: java.net.SocketException: No buffer space available
java.util.concurrent.ExecutionException: java.net.SocketException: No buffer space available
java.util.concurrent.ExecutionException: java.net.SocketException: No buffer space available
java.util.concurrent.ExecutionException: java.net.SocketException: No buffer space available
An un-handled exception occurred: javax.net.ssl.SSLException: Couldn't kickstart handshaking for (id: b6a89ad9-e8b7-41aa-8616-a4633f59f46f file: a92c2864-3fdd-4705-9d14-cd31691738d2.ipa part: 27)
An un-handled exception occurred: javax.net.ssl.SSLException: Couldn't kickstart handshaking for (id: b6a89ad9-e8b7-41aa-8616-a4633f59f46f file: a92c2864-3fdd-4705-9d14-cd31691738d2.ipa part: 4)
An un-handled exception occurred: javax.net.ssl.SSLException: Couldn't kickstart handshaking for (id: b6a89ad9-e8b7-41aa-8616-a4633f59f46f file: a92c2864-3fdd-4705-9d14-cd31691738d2.ipa part: 30)
java.util.concurrent.ExecutionException: javax.net.ssl.SSLException: Couldn't kickstart handshaking
java.util.concurrent.ExecutionException: javax.net.ssl.SSLException: Couldn't kickstart handshaking
java.util.concurrent.ExecutionException: javax.net.ssl.SSLException: Couldn't kickstart handshaking
java.util.concurrent.ExecutionException: javax.net.ssl.SSLException: Couldn't kickstart handshaking
java.util.concurrent.ExecutionException: javax.net.ssl.SSLException: Couldn't kickstart handshaking
java.util.concurrent.ExecutionException: javax.net.ssl.SSLException: Couldn't kickstart handshaking
An un-handled exception occurred: java.net.SocketException: No buffer space available for (id: b6a89ad9-e8b7-41aa-8616-a4633f59f46f file: a92c2864-3fdd-4705-9d14-cd31691738d2.ipa part: 28)
An un-handled exception occurred: java.net.SocketException: No buffer space available for (id: b6a89ad9-e8b7-41aa-8616-a4633f59f46f file: a92c2864-3fdd-4705-9d14-cd31691738d2.ipa part: 13)
An un-handled exception occurred: java.net.SocketException: No buffer space available for (id: b6a89ad9-e8b7-41aa-8616-a4633f59f46f file: a92c2864-3fdd-4705-9d14-cd31691738d2.ipa part: 5)
java.util.concurrent.ExecutionException: java.net.SocketException: No buffer space available
An un-handled exception occurred: java.net.SocketException: No buffer space available for (id: b6a89ad9-e8b7-41aa-8616-a4633f59f46f file: a92c2864-3fdd-4705-9d14-cd31691738d2.ipa part: 21)
An un-handled exception occurred: java.net.SocketException: No buffer space available for (id: b6a89ad9-e8b7-41aa-8616-a4633f59f46f file: a92c2864-3fdd-4705-9d14-cd31691738d2.ipa part: 3)
An un-handled exception occurred: java.net.SocketException: No buffer space available for (id: b6a89ad9-e8b7-41aa-8616-a4633f59f46f file: a92c2864-3fdd-4705-9d14-cd31691738d2.ipa part: 26)
java.util.concurrent.ExecutionException: javax.net.ssl.SSLException: Couldn't kickstart handshaking
java.util.concurrent.ExecutionException: java.net.SocketException: No buffer space available
java.util.concurrent.ExecutionException: javax.net.ssl.SSLException: Couldn't kickstart handshaking
java.util.concurrent.ExecutionException: javax.net.ssl.SSLException: Couldn't kickstart handshaking
java.util.concurrent.ExecutionException: java.net.SocketException: No buffer space available
java.util.concurrent.ExecutionException: java.net.SocketException: No buffer space available
java.util.concurrent.ExecutionException: javax.net.ssl.SSLException: Couldn't kickstart handshaking
java.util.concurrent.ExecutionException: javax.net.ssl.SSLException: Couldn't kickstart handshaking
java.util.concurrent.ExecutionException: java.net.SocketException: No buffer space available
java.util.concurrent.ExecutionException: javax.net.ssl.SSLException: Couldn't kickstart handshaking
java.util.concurrent.ExecutionException: java.net.SocketException: No buffer space available
Could not upload 1 file(s):
Could not upload file: a92c2864-3fdd-4705-9d14-cd31691738d2.ipa 34 parts failed: [20, 19, 34, 21, 3, 6, 8, 7, 23, 25, 11, 5, 26, 28, 27, 2, 29, 16, 13, 14, 4, 10, 32, 24, 30, 15, 22, 1, 12, 31, 17, 33, 9, 18]
Please retry your upload later.
Upload is not in processing state, please try again. state: class Build {
[06:49:06]: [iTMSTransporter]             data: null
[06:49:06]: [iTMSTransporter]         }
[06:49:06]: [iTMSTransporter]         buildAssetSpi: class BuildRelationshipsBuildAssetDescription {
[06:49:06]: [iTMSTransporter]             links: class AppAvailabilityRelationshipsAppLinks {
[06:49:06]: [iTMSTransporter]                 self: https://contentdelivery.itunes.apple.com/MZContentDeliveryService/iris/v1/builds/0200f22a-8d0f-4662-9994-b1d79288380c/relationships/buildAssetSpi
[06:49:06]: [iTMSTransporter]                 related: https://contentdelivery.itunes.apple.com/MZContentDeliveryService/iris/v1/builds/0200f22a-8d0f-4662-9994-b1d79288380c/buildAssetSpi
[06:49:06]: [iTMSTransporter]             }
[06:49:06]: [iTMSTransporter]             data: null
[06:49:06]: [iTMSTransporter]         }
[06:49:06]: [iTMSTransporter]     }
[06:49:06]: [iTMSTransporter]     links: class ResourceLinks {
[06:49:06]: [iTMSTransporter]         self: https://contentdelivery.itunes.apple.com/MZContentDeliveryService/iris/v1/builds/0200f22a-8d0f-4662-9994-b1d79288380c
[06:49:06]: [iTMSTransporter]     }
[06:49:06]: [iTMSTransporter] }
[06:49:06]: [iTMSTransporter] [2022-11-08 06:49:06 GMT] <main> DBG-X: Returning 1
[06:49:06]: iTunes Transporter output above ^
</pre>
</details>

### Environment

<details>
<pre>

+ bundle exec fastlane env
[13:57:15]: [33mGenerating fastlane environment output, this might take a few seconds...[0m
swift-driver version: 1.45.2 <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                          |
| --------------------------- | ---------------------------------------------- |
| OS                          | 12.0.1                                         |
| Ruby                        | 3.0.2                                          |
| Bundler?                    | true                                           |
| Git                         | git version 2.32.1 (Apple Git-133)             |
| Installation Source         | /opt/homebrew/lib/ruby/gems/3.0.0/bin/fastlane |
| Host                        | macOS 12.0.1 (21A559)                          |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.0.2_1/lib          |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021                    |
| Is contained                | false                                          |
| Is homebrew                 | false                                          |
| Is installed via Fabric.app | false                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/    |
| Xcode Version               | 13.4                                           |
| Swift Version               | 5.6.1                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_IE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Build and upload the app bundle to TestFlight Internal testing track"
  lane :testflightInternal do |options|
    # Retrieve app version
    version = flutter_version()

    # Build core module
    Dir.chdir "../../../core" do
      sh("flutter", "pub", "get")
      sh("flutter", "pub", "run", "intl_utils:generate")
      sh("flutter", "pub", "run", "build_runner", "build", "--delete-conflicting-outputs")
    end

    # Build app bundle
    Dir.chdir "../.." do
      sh("flutter", "pub", "get")
      sh("flutter", "pub", "run", "build_runner", "build", "--delete-conflicting-outputs")
      sh("pod", "repo", "update")
      sh("flutter", "build", "ios", "--release", "--no-codesign")
    end

    # Acquire App Store Connect API key
    api_key = app_store_connect_api_key(
        key_id: options[:APPLE_KEY_ID],
        issuer_id: options[:APPLE_ISSUER_ID],
        key_filepath: Dir.pwd + "/AuthKey_$APPLE_KEY_ID.p8",
        # duration: 1200, # optional (maximum 1200)
        # in_house: false # optional but may be required if using match/sigh
    )

    # build_app(workspace: "Runner.xcworkspace", export_method: "app-store")
    build_app(
        workspace: "Runner.xcworkspace",
        export_method: "app-store",
        skip_profile_detection: true,
        export_options: {
          provisioningProfiles: {
            "**************" => "**************",
            "**************" => "**************",
          }
        }
    )

    # Upload bundle to TestFlight Internal testing track
    pilot(api_key: api_key, skip_waiting_for_build_processing: true)

    # Clean after build
    clean_build_artifacts
    clear_derived_data
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("**************") # The bundle identifier of your app
apple_id("**************") # Your Apple email address
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.211.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                          | Version | Update-Status |
| ------------------------------- | ------- | ------------- |
| fastlane-plugin-flutter_version | 1.1.15  | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| bundler                         | 2.2.32       |
| tsort                           | 0.1.0        |
| uri                             | 0.10.1       |
| pathname                        | 0.1.0        |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| concurrent-ruby                 | 1.1.10       |
| i18n                            | 1.12.0       |
| minitest                        | 5.16.3       |
| tzinfo                          | 2.0.5        |
| zeitwerk                        | 2.6.6        |
| activesupport                   | 6.1.7        |
| public_suffix                   | 4.0.7        |
| addressable                     | 2.8.1        |
| httpclient                      | 2.8.3        |
| json                            | 2.6.2        |
| algoliasearch                   | 1.27.5       |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.660.0      |
| aws-sigv4                       | 1.5.2        |
| jmespath                        | 1.6.1        |
| aws-sdk-core                    | 3.167.0      |
| aws-sdk-kms                     | 1.59.0       |
| aws-sdk-s3                      | 1.117.1      |
| babosa                          | 1.0.4        |
| claide                          | 1.1.0        |
| fuzzy_match                     | 2.0.4        |
| nap                             | 1.1.0        |
| netrc                           | 0.11.0       |
| ffi                             | 1.15.5       |
| ethon                           | 0.16.0       |
| typhoeus                        | 1.4.0        |
| cocoapods-core                  | 1.11.3       |
| cocoapods-deintegrate           | 1.0.5        |
| cocoapods-downloader            | 1.6.3        |
| cocoapods-plugins               | 1.0.0        |
| cocoapods-search                | 1.0.1        |
| cocoapods-trunk                 | 1.6.0        |
| cocoapods-try                   | 1.2.0        |
| colored2                        | 3.1.2        |
| escape                          | 0.0.4        |
| fourflusher                     | 2.3.1        |
| gh_inspector                    | 1.1.3        |
| molinillo                       | 0.8.0        |
| ruby-macho                      | 2.5.1        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| cocoapods                       | 1.11.3       |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.94.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.0.0        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.2       |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| jwt                             | 2.5.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.3.0        |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.9.1        |
| google-apis-androidpublisher_v3 | 0.31.0       |
| google-apis-playcustomapp_v1    | 0.12.0       |
| google-apis-iamcredentials_v1   | 0.16.0       |
| google-apis-storage_v1          | 0.19.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.44.0       |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| fastlane-plugin-flutter_version | 1.1.15       |
</details>

*generated on:* **2022-11-14**
</details>

</pre>
</details>

**Comment by rainbowcardiod** [comment]
It seems that upgrading from MacOS 12 to MacOS 13 solves the problem for me, at least tried 3 times and it worked, while before it always failed like in this issue description.

**Comment by shliama** [comment]
@rainbowcardiod wow, it worked! Thanks a lot, I haven't even thought about MacOS version... just another software shenanigans I want to forget.
