### ISSUE TITLE
appStoreVersions is not in valid state. You must provide a value for attribute 'privacyPolicyText' with this request.

### ISSUE THREAD

**Issue by jayshah123** [fastlane/fastlane#20869]
### New Issue Checklist

- [ ] Updated fastlane to the latest version (I am using Fastlane 2.210.1)
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

```
/Users/runner/hostedtoolcache/Ruby/2.7.5/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.210.1/spaceship/lib/spaceship/connect_api/api_client.rb:204:in `handle_response': \e[31m[!] appStoreVersions with id 'xxxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' is not in valid state. - This resource cannot be reviewed, please check associated errors to see why. (Spaceship::UnexpectedResponse)
The provided entity is missing a required attribute - You must provide a value for the attribute 'privacyPolicyText' with this request\e[0m
```

##### Command executed

bundle exec fastlane upload_to_appstore

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> /Users/runner/hostedtoolcache/Ruby/2.7.5/x64/lib/ruby/gems/2.7.0/gems/fastlane-2.210.1/spaceship/lib/spaceship/connect_api/api_client.rb:204:in `handle_response': \e[31m[!] appStoreVersions with id 'xxxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' is not in valid state. - This resource cannot be reviewed, please check associated errors to see why. (Spaceship::UnexpectedResponse)
The provided entity is missing a required attribute - You must provide a value for the attribute 'privacyPolicyText' with this request\e[0m
 </pre>
</details>

### Environment

https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md
<details>
  <pre> https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md </pre>
</details>

**Comment by rogerluan** [comment]
This attribute is required when you're submitting an Apple TV app (aka tvOS app). Check if there's no pending tvOS app in your App Store Connect. Maybe one was created by mistake. You should delete it from App Store Connect if you have no intention of submitting a tvOS app, and then your `deliver` command should work 👍
