### ISSUE TITLE
xcodebuild -showBuildSettings timed out after 4 retries with a base timeout of 3. You can override the base timeout value with the environment variable FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT, and the number of retries with the environment variable FASTLANE_XCODEBUILD_SETTINGS_RETRIES 

### ISSUE THREAD

**Issue by ChristineWasike** [fastlane/fastlane#20919]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I've been running fastlane to deploy my testflight builds but up until yesterday I've been hitting this error:
`xcodebuild -showBuildSettings timed out after 4 retries with a base timeout of 3. You can override the base timeout value with the environment variable FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT, and the number of retries with the environment variable FASTLANE_XCODEBUILD_SETTINGS_RETRIES`

##### Command executed
`fastlane beta`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[✔] 🚀 
[19:45:56]: fastlane detected a Gemfile in the current directory
[19:45:56]: However, it seems like you didn't use `bundle exec`
[19:45:56]: To launch fastlane faster, please use
[19:45:56]: 
[19:45:56]: $ bundle exec fastlane beta
[19:45:56]: 
[19:45:56]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[19:45:57]: ------------------------------
[19:45:57]: --- Step: default_platform ---
[19:45:57]: ------------------------------
[19:45:57]: Driving the lane 'ios beta' 🚀
[19:45:57]: ------------------------------------
[19:45:57]: --- Step: increment_build_number ---
[19:45:57]: ------------------------------------
Current version of project Runner is: 
    84

[19:45:57]: ▸ Setting version of project Runner to:
[19:45:57]: ▸ 85.
[19:45:57]: ▸ Also setting CFBundleVersion key (assuming it exists)
[19:45:57]: ▸ Updating CFBundleVersion in Info.plist(s)...
[19:45:57]: ▸ Updated CFBundleVersion in "Runner.xcodeproj/../Runner/Info.plist" to 85
[19:45:58]: -----------------------
[19:45:58]: --- Step: build_app ---
[19:45:58]: -----------------------
[19:45:58]: Resolving Swift Package Manager dependencies...
[19:45:58]: $ xcodebuild -resolvePackageDependencies -workspace Runner.xcworkspace -scheme Runner
[19:45:58]: ▸ Command line invocation:
[19:45:58]: ▸     /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -workspace Runner.xcworkspace -scheme Runner
[19:45:58]: ▸ User defaults from command line:
[19:45:58]: ▸     IDEPackageSupportUseBuiltinSCM = YES
[19:45:59]: ▸ --- xcodebuild: WARNING: Using the first of multiple matching destinations:
[19:45:59]: ▸ { platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:00006000-000604A61121801E }
[19:45:59]: ▸ { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
[19:45:59]: ▸ { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
[19:45:59]: ▸ { platform:iOS Simulator, id:9C406038-71F2-4467-B4CB-28206901998C, OS:16.1, name:iPhone 13 }
[19:45:59]: ▸ resolved source packages: 
[19:45:59]: $ xcodebuild -showBuildSettings -workspace Runner.xcworkspace -scheme Runner
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:00006000-000604A61121801E }
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
{ platform:iOS Simulator, id:9C406038-71F2-4467-B4CB-28206901998C, OS:16.1, name:iPhone 13 }
[19:46:02]: Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:00006000-000604A61121801E }
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
{ platform:iOS Simulator, id:9C406038-71F2-4467-B4CB-28206901998C, OS:16.1, name:iPhone 13 }
[19:46:08]: Command timed out after 6 seconds on try 2 of 4, trying again with a 12 second timeout...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:00006000-000604A61121801E }
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
{ platform:iOS Simulator, id:9C406038-71F2-4467-B4CB-28206901998C, OS:16.1, name:iPhone 13 }
[19:46:20]: Command timed out after 12 seconds on try 3 of 4, trying again with a 24 second timeout...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:00006000-000604A61121801E }
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
{ platform:iOS Simulator, id:9C406038-71F2-4467-B4CB-28206901998C, OS:16.1, name:iPhone 13 }
2022-12-08 19:46:38.345 xcodebuild[94925:438440] Requested but did not find extension point with identifier Xcode.InterfaceBuilderBuildSupport.PlatformDefinition
2022-12-08 19:46:38.345 xcodebuild[94941:438514] Requested but did not find extension point with identifier Xcode.InterfaceBuilderBuildSupport.PlatformDefinition
2022-12-08 19:46:38.346 xcodebuild[94955:438649] Requested but did not find extension point with identifier Xcode.InterfaceBuilderBuildSupport.PlatformDefinition
[19:46:44]: Command timed out after 24 seconds on try 4 of 4
+------------------+----------+
|        Lane Context         |
+------------------+----------+
| DEFAULT_PLATFORM | ios      |
| PLATFORM_NAME    | ios      |
| LANE_NAME        | ios beta |
| BUILD_NUMBER     | 85       |
+------------------+----------+
[19:46:44]: xcodebuild -showBuildSettings timed out after 4 retries with a base timeout of 3. You can override the base timeout value with the environment variable FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT, and the number of retries with the environment variable FASTLANE_XCODEBUILD_SETTINGS_RETRIES 

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | default_platform       | 0           |
| 2    | increment_build_numbe  | 0           |
|      | r                      |             |
| 💥   | build_app              | 46          |
+------+------------------------+-------------+

[19:46:44]: fastlane finished with errors

[!] xcodebuild -showBuildSettings timed out after 4 retries with a base timeout of 3. You can override the base timeout value with the environment variable FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT, and the number of retries with the environment variable FASTLANE_XCODEBUILD_SETTINGS_RETRIES </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 12.6                                                       |
| Ruby                        | 3.1.2                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.37.1 (Apple Git-137.1)                       |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.211.0/libexec/bin/fastlane |
| Host                        | macOS 12.6 (21G115)                                        |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.1.2_1/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1q  5 Jul 2022                                 |
| Is contained                | false                                                      |
| Is homebrew                 | true                                                       |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
| Xcode Version               | 14.1                                                       |
| Swift Version               | 5.7.1                                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = " "
default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight(app_identifier: "com.socialai.limited",
    itc_provider:"ZR3QGWZA6A" )
    # slack(message: "Successfully distributed a new beta build")
  end
end

</details>

<details><summary>`./fastlane/Appfile`</summary>

ruby
app_identifier("com.socialai.limited") # The bundle identifier of your app
apple_id("christinewasike22@gmail.com") # Your Apple Developer Portal username

itc_team_id("125087325") # App Store Connect Team ID
team_id("ZR3QGWZA6A") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.211.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 5.0.0        |
| addressable                     | 2.8.1        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.94.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.2       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.6.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.8.1        |
| bundler                         | 2.3.11       |
| simctl                          | 1.6.8        |
| jwt                             | 2.5.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.3.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.9.1        |
| google-apis-playcustomapp_v1    | 0.12.0       |
| google-apis-androidpublisher_v3 | 0.31.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.16.0       |
| google-apis-storage_v1          | 0.19.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.44.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.6.1        |
| aws-partitions                  | 1.660.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.2        |
| aws-sdk-core                    | 3.167.0      |
| aws-sdk-kms                     | 1.59.0       |
| aws-sdk-s3                      | 1.117.1      |
| set                             | 1.0.2        |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.1        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.1        |
| uri                             | 0.11.0       |
| openssl                         | 3.0.0        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.0        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.2        |
| net-http                        | 0.2.0        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.11       |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.3        |
</details>

*generated on:* **2022-12-08**
</details>

**Comment by blwinters** [comment]
I'm seeing this as well, starting today.

**Comment by fabricetiennette** [comment]
Setting `ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"` in your fastfile should resolved this issue.

**Comment by ChristineWasike** [comment]
Thank you for the suggestion! 

This solution seems to work alongside some tinkering with the podfile (Removed `config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64 i386`).

**Comment by rajbopched11** [comment]
> Setting `ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"` in your fastfile should resolved this issue.

This was very helpful thank you. Can you please take a moment and explain in detail what is going on here?
1. Why the original issue occured?
2. Why the solution works?

This will help and improve all future readers understanding 🙏

**Comment by hariria** [comment]
Yeah adding on to @rajbopched11, would love to better understand why this is happening. We just saw this issue again recently. Is there a reason why the timeout needs to be adjusted to 120 seconds? It usually takes < 1 second to complete the command on my local...

**Comment by Ccalary** [comment]
> Setting `ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"` in your fastfile should resolved this issue.

Thank you for the suggestion! It works

**Comment by hborders** [comment]
I'm also curious about why this command seems so different when run locally vs when running on CI

**Comment by rajbopched11** [comment]
> Setting `ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"` in your fastfile should resolved this issue.

@fabricetiennette any clues, as to why the original error occurs and why this workaround works?

**Comment by Laxman18** [comment]
Were we able to find the real cause for this issue. Solution provided by @fabricetiennette worked!

**Comment by mokagio** [comment]
We run into this issue too when upgrading CI to Xcode 15.4. I bumping the timeout as suggested above, but it didn't work. 

The issue for us turned out to be our script was using a Simulator no longer available out of the box with Xcode 15.4. [Updating the target Simulator solved it](https://github.com/wordpress-mobile/WordPress-iOS/commit/1688918e755fb849e35e7dccac6b9e9c35e217b0).
