### ISSUE TITLE
Can't get a build version when I define main version.

### ISSUE THREAD

**Issue by linuxoid69** [fastlane/fastlane#20982]
**When I run without parameter "version" then I get build version.**

```
foo@localhost % fastlane run latest_testflight_build_number app_identifier:com.example api_key_path:api.json

[14:34:25]: fastlane detected a Gemfile in the current directory
[14:34:25]: However, it seems like you didn't use `bundle exec`
[14:34:25]: To launch fastlane faster, please use
[14:34:25]: 
[14:34:25]: $ bundle exec fastlane run latest_testflight_build_number app_identifier:com.example api_key_path:api.json
[14:34:25]: 
[14:34:25]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[14:34:26]: --------------------------------------------
[14:34:26]: --- Step: latest_testflight_build_number ---
[14:34:26]: --------------------------------------------
[14:34:26]: Creating authorization token for App Store Connect API
[14:34:27]: Fetching the latest build number for any version
[14:34:27]: Latest upload for version 2022.23.014 on ios platform is build: 41
[14:34:27]: Result: 41

```

**When I run with parameter "version" I don't see correct result**
```

foo@localhost % fastlane run latest_testflight_build_number app_identifier:com.example api_key_path:api.json version:2022.23.014

[✔] 🚀 
[14:34:42]: fastlane detected a Gemfile in the current directory
[14:34:42]: However, it seems like you didn't use `bundle exec`
[14:34:42]: To launch fastlane faster, please use
[14:34:42]: 
[14:34:42]: $ bundle exec fastlane run latest_testflight_build_number app_identifier:com.example api_key_path:api.json version:2022.23.014
[14:34:42]: 
[14:34:42]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[14:34:42]: --------------------------------------------
[14:34:42]: --- Step: latest_testflight_build_number ---
[14:34:42]: --------------------------------------------
[14:34:42]: Creating authorization token for App Store Connect API
[14:34:43]: Fetching the latest build number for version 2022.23.014
[14:34:44]: Could not find a build for version 2022.23.014 on ios platform on App Store Connect
[14:34:44]: Using initial build number of 1
[14:34:44]: Result: 1

```

ENV:

fastlane env                          

[✔] 🚀 
[14:39:01]: fastlane detected a Gemfile in the current directory
[14:39:01]: However, it seems like you didn't use `bundle exec`
[14:39:01]: To launch fastlane faster, please use
[14:39:01]: 
[14:39:01]: $ bundle exec fastlane env
[14:39:01]: 
[14:39:01]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[14:39:02]: Generating fastlane environment output, this might take a few seconds...
swift-driver version: 1.45.2 <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 12.3.1                                                  |
| Ruby                        | 3.1.2                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.37.1                                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.211.0/libexec/bin/fastlane |
| Host                        | macOS 12.3.1 (21E258)                                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/3.1.2_1/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1q  5 Jul 2022                              |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 13.3                                                    |
| Swift Version               | 5.6                                                     |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple Developer Portal username

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.211.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| addressable                     | 2.8.1        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.2       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.8.1        |
| bundler                         | 2.3.11       |
| simctl                          | 1.6.8        |
| google-apis-playcustomapp_v1    | 0.12.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.16.0       |
| google-apis-storage_v1          | 0.19.0       |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.3.0        |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| mini_mime                       | 1.1.2        |
| google-cloud-storage            | 1.44.0       |
| emoji_regex                     | 3.2.3        |
| set                             | 1.0.2        |
| public_suffix                   | 5.0.1        |
| excon                           | 0.97.0       |
| json                            | 2.6.3        |
| mini_magick                     | 4.12.0       |
| jwt                             | 2.6.0        |
| webrick                         | 1.7.0        |
| httpclient                      | 2.8.3        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.2        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| google-apis-core                | 0.9.4        |
| google-apis-androidpublisher_v3 | 0.32.0       |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.2        |
| aws-partitions                  | 1.690.0      |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.168.4      |
| aws-sdk-kms                     | 1.61.0       |
| aws-sdk-s3                      | 1.117.2      |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.1        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.1        |
| uri                             | 0.11.0       |
| openssl                         | 3.0.0        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.0        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.2        |
| net-http                        | 0.2.0        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.11       |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.3        |
</details>

*generated on:* **2023-01-10**
</details>
[14:39:03]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[14:39:03]: 🙄  Wow, that's a lot of markdown text... should fastlane put it into your clipboard, so you can easily paste it on GitHub? (y/n)
n
[14:39:04]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅

**Comment by melmus** [comment]
I have the same problem too

**Comment by den-patrakeev** [comment]
I join

**Comment by elbars** [comment]
Please pay attention this issue.

**Comment by EmDee** [comment]
I believe this is a limitation of the App Store Connect API. The "problem" is with the `0` in your version `2022.23.014`. 

I think internally the query param `filter[preReleaseVersion.version]` is used and somehow the ASC API is not doing a string comparison but some sort of integer one.

Can you try to pass `2022.23.14` instead?

**Comment by linuxoid69** [comment]
> I believe this is a limitation of the App Store Connect API. The "problem" is with the `0` in your version `2022.23.014`.
> 
> I think internally the query param `filter[preReleaseVersion.version]` is used and somehow the ASC API is not doing a string comparison but some sort of integer one.
> 
> Can you try to pass `2022.23.14` instead?

Thank you so much. Your way resolved my problem.
