### ISSUE TITLE
Invalid application specific password provided

### ISSUE THREAD

**Issue by mabreu14** [fastlane/fastlane#21009]
### New Issue Checklist

- [x] Updated Fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I have triple-checked the password and even created a new one just to be sure, but I always get "Invalid application specific password provided"

##### Command executed

fastlane deliver run --force --price_tier 0 --app_version "[VERSION]" --app_icon "./ios-store-icon.png" --primary_category "[CATEGORY]" --username [APPLE_USERNAME] --ipa "./app.ipa" --metadata_path ./metadata --team_id [TEAM_ID] --team_name "[TEAM_NAME]" --skip_screenshots

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
[11:40:55]: Uploading metadata to App Store Connect for version
[11:40:58]: Uploading metadata to App Store Connect for localized version 'en-US'
[11:40:58]: Uploading metadata to App Store Connect for localized info 'en-US'
[11:41:08]: Uploading app review information to App Store Connect
[11:41:10]: [32mPrice Tier unchanged (tier 0)[0m
[11:41:10]: Uploading binary to App Store Connect
[11:41:10]: Fetching password for transporter from environment variable named `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`
[11:41:20]: [31mTransporter transfer failed.[0m
[11:41:20]: 
[11:41:20]: [31mSign in with the app-specific password you generated. If you forgot the app-specific password or need to create a new one, go to appleid.apple.com (-22938)
[0m
[11:41:20]: 
[11:41:20]: [31mApplication specific password you provided using[0m
[11:41:20]: [31menvironment variable FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD[0m
[11:41:20]: [31mis invalid, please make sure it's correct[0m
[11:41:20]: 
[11:41:20]: Going to upload updated app to App Store Connect
[11:41:20]: [32mThis might take a few minutes. Please don't interrupt the script.[0m
[11:41:30]: [31mTransporter transfer failed.[0m
[11:41:30]: 
[11:41:30]: [31mSign in with the app-specific password you generated. If you forgot the app-specific password or need to create a new one, go to appleid.apple.com (-22938)
[0m
[11:41:30]: 
[11:41:30]: [31mApplication specific password you provided using[0m
[11:41:30]: [31menvironment variable FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD[0m
[11:41:30]: [31mis invalid, please make sure it's correct[0m
[11:41:30]: 
[31m
[!] Invalid application specific password provided[0m 
</pre>
</details>

### Environment

<details>
  <pre> 
### Stack

| Key                         | Value                                                     |
| --------------------------- | --------------------------------------------------------- |
| OS                          | 12.5                                                      |
| Ruby                        | 3.1.3                                                     |
| Bundler?                    | false                                                     |
| Git                         | git version 2.32.1 (Apple Git-133)                        |
| Installation Source         | /usr/local/Cellar/fastlane/2.211.0_2/libexec/bin/fastlane |
| Host                        | macOS 12.5 (21G72)                                        |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@3.1/3.1.3_1/lib                    |
| OpenSSL Version             | OpenSSL 3.0.7 1 Nov 2022                                  |
| Is contained                | false                                                     |
| Is homebrew                 | true                                                      |
| Is installed via Fabric.app | false                                                     |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/               |
| Xcode Version               | 13.4.1                                                    |
| Swift Version               | 5.6.1                                                     |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.211.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 5.0.1        |
| addressable                     | 2.8.1        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.96.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.2       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.6.1        |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.8.1        |
| bundler                         | 2.3.26       |
| simctl                          | 1.6.8        |
| jwt                             | 2.6.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.3.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.9.4        |
| google-apis-playcustomapp_v1    | 0.12.0       |
| google-apis-androidpublisher_v3 | 0.32.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.16.0       |
| google-apis-storage_v1          | 0.19.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.44.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.6.2        |
| aws-partitions                  | 1.689.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.2        |
| aws-sdk-core                    | 3.168.4      |
| aws-sdk-kms                     | 1.61.0       |
| aws-sdk-s3                      | 1.117.2      |
| set                             | 1.0.2        |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.5        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.2.0        |
| uri                             | 0.11.0       |
| openssl                         | 3.0.1        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.0        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-http                        | 0.3.0        |
| net-protocol                    | 0.1.2        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.11       |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.4        |
</details>

*generated on:* **2023-01-25**
</pre>
</details>

**Comment by DavidWiesner** [comment]
@mabreu14 I got the same issue. What was your fix?
