### ISSUE TITLE
Building for ios platform failing with error [webpack-cli] Error: Unknown option '--env.production'

### ISSUE THREAD

**Issue by pratik-fascet** [fastlane/fastlane#21059]
Getting below error while running fastlane command to build the project. Build was working fine before upgrading macOS & Xcode versions. 
Kindly suggest possible solution for this error.
**Error trace**
```
[13:02:40]: ----------------------------------------------------------------
[13:02:40]: --- Step: tns prepare ios --release --clean --env.production ---
[13:02:40]: ----------------------------------------------------------------
[13:02:40]: $ tns prepare ios --release --clean --env.production
[13:02:42]: ▸ Copying template files...
[13:02:44]: ▸ Platform ios successfully added. v7.2.0
[13:02:44]: ▸ Preparing project...
[13:02:44]: ▸ [webpack-cli] Error: Unknown option '--env.production'
[13:02:44]: ▸ [webpack-cli] Run 'webpack --help' to see available commands and options
[13:02:44]: ▸ Executing webpack failed with exit code 2.
[13:02:44]: ▸ 
+--------------------------------+-------------+
|                 Lane Context                 |
+--------------------------------+-------------+
| PLATFORM_NAME                  | ios         |
| LANE_NAME                      | ios prepare |
| LATEST_TESTFLIGHT_BUILD_NUMBER | 0.1.26.3    |
| LATEST_TESTFLIGHT_VERSION      | 0.1         |
+--------------------------------+-------------+
[13:02:44]: Exit status of command 'tns prepare ios --release --clean --env.production' was 127 instead of 0.
Copying template files...
Platform ios successfully added. v7.2.0
Preparing project...
[webpack-cli] Error: Unknown option '--env.production'
[webpack-cli] Run 'webpack --help' to see available commands and options
Executing webpack failed with exit code 2.


+------+----------------------------------------------------+-------------+
|                            fastlane summary                             |
+------+----------------------------------------------------+-------------+
| Step | Action                                             | Time (in s) |
+------+----------------------------------------------------+-------------+
| 1    | Verifying fastlane version                         | 0           |
| 2    | read_json                                          | 0           |
| 3    | read_json                                          | 0           |
| 4    | last_git_tag                                       | 0           |
| 5    | latest_testflight_build_number                     | 4           |
| 6    | update_plist                                       | 0           |
| 💥   | tns prepare ios --release --clean --env.production | 3           |
+------+----------------------------------------------------+-------------+

[13:02:44]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

/usr/local/Cellar/fastlane/2.211.0_2/libexec/gems/fastlane-2.211.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': \e[31m[!] Exit status of command 'tns prepare ios --release --clean --env.production' was 127 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
Copying template files...
Platform ios successfully added. v7.2.0
Preparing project...
[webpack-cli] Error: Unknown option '--env.production'
[webpack-cli] Run 'webpack --help' to see available commands and options
\e[1m\e[31mExecuting webpack failed with exit code 2.
\e[39m\e[22m\e[0m
        from /usr/local/Cellar/fastlane/2.211.0_2/libexec/gems/fastlane-2.211.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
        from /usr/local/Cellar/fastlane/2.211.0_2/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
        from /usr/local/Cellar/fastlane/2.211.0_2/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/helper/sh_helper.rb:16:in `sh_no_action'
        from /usr/local/Cellar/fastlane/2.211.0_2/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/fast_file.rb:223:in `block in sh'
        from /usr/local/Cellar/fastlane/2.211.0_2/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        from /usr/local/Cellar/fastlane/2.211.0_2/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/fast_file.rb:222:in `sh'
        from /usr/local/Cellar/fastlane/2.211.0_2/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/fast_file.rb:216:in `sh'
        from Fastfile:47:in `block (2 levels) in parsing_binding'
        from /usr/local/Cellar/fastlane/2.211.0_2/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /usr/local/Cellar/fastlane/2.211.0_2/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /usr/local/Cellar/fastlane/2.211.0_2/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /usr/local/Cellar/fastlane/2.211.0_2/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /usr/local/Cellar/fastlane/2.211.0_2/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        from /usr/local/Cellar/fastlane/2.211.0_2/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from /usr/local/Cellar/fastlane/2.211.0_2/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
        from /usr/local/Cellar/fastlane/2.211.0_2/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /usr/local/Cellar/fastlane/2.211.0_2/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /usr/local/Cellar/fastlane/2.211.0_2/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /usr/local/Cellar/fastlane/2.211.0_2/libexec/gems/fastlane-2.211.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /usr/local/Cellar/fastlane/2.211.0_2/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /usr/local/Cellar/fastlane/2.211.0_2/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
        from /usr/local/Cellar/fastlane/2.211.0_2/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        from /usr/local/Cellar/fastlane/2.211.0_2/libexec/gems/fastlane-2.211.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        from /usr/local/Cellar/fastlane/2.211.0_2/libexec/gems/fastlane-2.211.0/bin/fastlane:23:in `<top (required)>'
        from /usr/local/Cellar/fastlane/2.211.0_2/libexec/bin/fastlane:25:in `load'
        from /usr/local/Cellar/fastlane/2.211.0_2/libexec/bin/fastlane:25:in `<main>'
```

Result for 'fastlane env'
`<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                     |
| --------------------------- | --------------------------------------------------------- |
| OS                          | 13.2                                                      |
| Ruby                        | 3.1.3                                                     |
| Bundler?                    | false                                                     |
| Git                         | git version 2.37.1 (Apple Git-137.1)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.211.0_2/libexec/bin/fastlane |
| Host                        | macOS 13.2 (22D49)                                        |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@3.1/3.1.3_1/lib                    |
| OpenSSL Version             | OpenSSL 3.0.7 1 Nov 2022                                  |
| Is contained                | false                                                     |
| Is homebrew                 | true                                                      |
| Is installed via Fabric.app | false                                                     |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/               |
| Xcode Version               | 14.2                                                      |
| Swift Version               | 5.7.2                                                     |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version '2.170.0'
fastlane_require 'dotenv'
fastlane_require 'fileutils'
fastlane_require 'dir'

before_all do
  # Dotenv.overload '.env.secret'
  # Dotenv.overload '.env.ios'
end

desc 'test lane'
lane :test do
  print 'TEST SUCCESSFUL!'
end

platform :ios do
  before_all do
    UI.important 'Loading iOS environment variables'
    Dotenv.load '.env.ios'
  end

  lane :prepare do |options|
    client = options[:client]

    if Dir.exist?('../platforms')
      FileUtils.remove_dir('../platforms')
     end

     client_data = read_json(
      json_path: "./AppVariants/#{client}/data.json"
     )
     client_secrets = read_json(
       json_path: "./AppVariants/#{client}/data.secret.json"
     )

     print "Building: " + client_data[:appId] + "\n"

     ENV["MATCH_PASSWORD"] = client_secrets[:certsKey]
     ENV["FASTLANE_USER"] = client_secrets[:appleId]
     ENV["FASTLANE_PASSWORD"] = client_secrets[:applePassword]

     version = github_version
     print "version: " + version + "\n"
     up_to_date = store_is_up_to_date(client_data, client_secrets, version)

     set_variant(client_data, version, 1)
     sh('tns', 'prepare', 'ios', '--release', '--clean', '--env.production')
     update_code_signing_settings(
      use_automatic_signing: false,
      targets: 'all',
      team_id: client_data[:teamId],
      code_sign_identity: 'Apple Distribution',
      bundle_identifier: client_data[:appId],
      profile_name: 'match AppStore com.XXX.XXX'
     )

     match(
      type: 'appstore',
      readonly: false,
      generate_apple_certs: true,
      skip_provisioning_profiles: false,
      app_identifier: client_data[:appId],
      username: client_data[:appleId],
      team_id: client_data[:teamId],
      team_name: client_data[:teamName],
      storage_mode: 'git',
      git_url: client_data[:gitUrl],
      git_branch: 'master',
      git_full_name: 'XXXX',
      git_user_email: client_data[:appleId],
      keychain_password: client_secrets[:localPassword],
      force: true,
      force_for_new_devices: true,
      platform: client_data[:applePlatform],
      verbose: true
    )

  end

  lane :build do |options|
    client = options[:client]
    client_data = read_json(
      json_path: "./AppVariants/#{client}/data.json"
     )
     client_secrets = read_json(
       json_path: "./AppVariants/#{client}/data.secret.json"
     )
    print "Building: " + client_data[:appId] + "\n"

    build_app(
      scheme: 'fascetapp',
      configuration: 'Release',
      workspace: './platforms/ios/fascetapp.xcworkspace',
      export_method: 'app-store',
      xcargs: "-allowProvisioningUpdates"
    )

    if options[:upload]
      upload_to_testflight(
        username: client_secrets[:appleId],
        app_identifier: client_data[:appId],
        app_platform: client_data[:applePlatform],
        apple_id: client_secrets[:appleId],
        ipa: 'platforms/ios/build/fascetapp.ipa',
        team_id: client_data[:teamId],
        team_name: client_data[:teamName],
        dev_portal_team_id: client_data[:teamName]
      )
    end
  end

  desc 'Only run this to register your devices with the various Dev Portals for the apps. Make sure you have created a Devicefile'
  lane :sync_all_development do
    app_variants.each do |client|

      client_data = read_json(
        json_path: "./AppVariants/#{client}/data.json"
      )
      client_secrets = read_json(
        json_path: "./AppVariants/#{client}/data.secret.json"
      )

      register_devices(
        devices_file: 'fastlane/Devicefile',
        username: client_secrets[:appleId],
        platform: client_data[:applePlatform],
        team_id: client_data[:teamId],
        team_name: client_data[:teamName]
      )

      match(
        type: 'development',
        readonly: false,
        app_identifier: client_data[:appId],
        username: client_data[:appleId],
        team_id: client_data[:teamId],
        team_name: client_data[:teamName],
        storage_mode: 'git',
        git_url: client_data[:gitUrl],
        git_branch: 'master',
        git_user_email: client_data[:appleId],
        keychain_password: client_secrets[:localPassword],
        force: true,
        force_for_new_devices: true,
        platform: client_data[:applePlatform],
        verbose: true
      )
    end
  end

end

def app_variants
  Dir.entries('../AppVariants').select do |entry|
    File.directory? File.join('../AppVariants', entry) and !['.', '..'].include?(entry)
  end
end

def set_variant(client_data, version, target)
  app_id = client_data[:appId]
  display_name = client_data[:displayName]

  version_arr = version.split('.').map(&:to_i)
  short_version = "#{version_arr[0]}.#{version_arr[1]}"
  version = "#{version}.#{target}"

  update_plist(
    plist_path: './App_Resources/iOS/Info.plist',
    block: proc do |plist|
      plist['CFBundleVersion'] = version
      plist['CFBundleShortVersionString'] = short_version
      plist['CFBundleDisplayName'] = display_name
      plist['CFBundleName'] = display_name
    end
  )

  app_target_url = ''
  case target
  when 1
    app_target_url = client_data[:devUrl]
  when 2
    app_target_url = client_data[:stagingUrl]
  when 3
    app_target_url = client_data[:productionUrl]
  end

  File.open('../src/app/shared/globals.ts', 'w') do |f|
    f.write "export const SiteUrl: string = \"#{app_target_url}\";\n"
  end
end

def copy_assets(client)
  FileUtils.copy_entry "../AppVariants/#{client}/App_Resources", '../App_Resources', false, false, true
end

def store_is_up_to_date(client_data, client_secrets, version)
  tf = latest_testflight_build_number(
    app_identifier: client_data[:appId],
    username: client_secrets[:appleId],
    platform: client_data[:applePlatform],
    team_id: client_data[:teamId],
    team_name: client_data[:teamName],
    live: false
  )
  version_arr = tf.split('.').map(&:to_i)
  tfs = "#{version_arr[0]}.#{version_arr[1]}.#{version_arr[2]}"
  print tfs
  tfs == version
end

def github_version
  version = last_git_tag pattern: 'v*'
  version[0] = '' # cut the leading "v" off
  version
end

def upload_to_playstore(name, track)
  changelog_from_git_commits

  upload_to_play_store(
    package_name: name,
    skip_upload_metadata: true,
    skip_upload_images: true,
    skip_upload_screenshots: true,
    skip_upload_changelogs: true,
    track: track,
    json_key: "fastlane/play-store-credentials.json",
    apk: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
  )
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("fastlane/play-store-credentials.json")

package_name("com.XXX.XXX")
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.211.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin               | Version | Update-Status |
| -------------------- | ------- | ------------- |
| fastlane-plugin-json | 1.1.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 5.0.1        |
| addressable                     | 2.8.1        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.96.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.2       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.6.1        |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.8.1        |
| bundler                         | 2.3.26       |
| simctl                          | 1.6.8        |
| jwt                             | 2.6.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.3.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.9.4        |
| google-apis-playcustomapp_v1    | 0.12.0       |
| google-apis-androidpublisher_v3 | 0.32.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.16.0       |
| google-apis-storage_v1          | 0.19.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.44.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.6.2        |
| aws-partitions                  | 1.689.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.2        |
| aws-sdk-core                    | 3.168.4      |
| aws-sdk-kms                     | 1.61.0       |
| aws-sdk-s3                      | 1.117.2      |
| set                             | 1.0.2        |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.5        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.2.0        |
| uri                             | 0.11.0       |
| openssl                         | 3.0.1        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.0        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-http                        | 0.3.0        |
| net-protocol                    | 0.1.2        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.11       |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.4        |
| fastlane-plugin-json            | 1.1.0        |
</details>

*generated on:* **2023-02-16**
</details>`

**Comment by rawatnaresh** [comment]
I think you are missing a blank space after `--env` flag

```
tns prepare ios --release --clean --env env-file-name
```

**Comment by pratik-fascet** [comment]
@rawatnaresh In my Fastlane file I have specified command as `sh('tns', 'prepare', 'ios', '--release', '--clean', '--env.production')`, spacing is not an issue. Also this same code worked perfectly before MacOS & Xcode upgrades.

**Comment by rawatnaresh** [comment]
This looks like a NativeScript issue. take a look at https://github.com/NativeScript/NativeScript/issues/10217
