### ISSUE TITLE
Fastlane : [altool] Error: Unable to upload archive. Failed to get authorization for username and password

### ISSUE THREAD

**Issue by komritza** [fastlane/fastlane#21060]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Building ios app works fine, but when try to do deployment gives me an error. Last time we deployed the app was 2 weeks ago.

##### Command executed
Fastfile:
```
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Automatically update fastlane
update_fastlane

default_platform(:ios)

# Default temporary keychain password and name, if not included from environment
TEMP_KEYCHAIN_NAME_DEFAULT = "fastlane_flutter"
TEMP_KEYCHAN_PASSWORD_DEFAULT = "temppassword"

# Remove the temporary keychain, if it exists
def delete_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

# Create the temporary keychain with name and password
def create_temp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    unlock: false,
    timeout: 0
  )
end

# Ensure we have a fresh, empty temporary keychain
def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end

platform :ios do
  desc "Build & sign appname iOS app"
  lane :build_ios_appname do |options|
    increment_build_number(build_number: ENV['CI_JOB_ID'])
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "./Runner.xcodeproj",
      team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
      profile_name: "match AppStore #{CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)}",
      code_sign_identity: "iPhone Distribution",
    )
    keychain_name = ENV['TEMP_KEYCHAIN_NAME'] || TEMP_KEYCHAIN_NAME_DEFAULT
    keychain_password = ENV['TEMP_KEYCHAIN_PASSWORD'] || TEMP_KEYCHAN_PASSWORD_DEFAULT
    ensure_temp_keychain(keychain_name, keychain_password)
    match(
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
      type: "appstore",
      readonly: is_ci,
      keychain_name: keychain_name,
      keychain_password: keychain_password,
      git_branch: "master"
    )
    sh "./flutter_build_appname.sh --clean"
    build_ios_app(
      scheme: "appname",
      export_options: {
          method: "app-store"
      },
      output_directory: "./appname"
    )
    delete_temp_keychain(keychain_name)
  end

  desc "Upload iOS app to app store"
  lane :deploy_ios do |options|
    # Upload to test flight or AppStore depending on caller parameters
    if options[:testflight]
      upload_to_testflight(
        skip_submission: true,
        ipa: "./#{options[:flavor]}/Runner.ipa"
      )
    else
      deliver(
        skip_metadata: false,
        skip_screenshots: true,
        submit_for_review: true,
        force: true,
        ipa: "./#{options[:flavor]}/Runner.ipa"
      )
    end
  end
end
```

##### Complete output when running fastlane, including the stack trace and command used
```
[16:29:50]: Login to App Store Connect (appleid).
[16:29:53]: Login successful
[16:29:54]: Ready to upload new build to TestFlight (App: 1502436715)...
[16:29:55]: Fetching password for transporter from environment variable named `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`
[16:29:57]: [altool] }
[16:29:57]: [altool] 2023-02-17 16:29:57.738 Non-localized server string received: 'Error Description not available (-24169)'.
[16:29:57]: [altool] 2023-02-17 16:29:57.739 Non-localized server string received: 'Error Description not available (-24169)'.
[16:29:57]: [altool] 2023-02-17 16:29:57.739 {
[16:29:57]: [altool]     EnableJWTForAllCalls = 0;
[16:29:57]: [altool]     ErrorCode = "-24169";
[16:29:57]: [altool]     ErrorMessage = "Error Description not available (-24169)";
[16:29:57]: [altool]     Errors =     (
[16:29:57]: [altool]         "Error Description not available (-24169)"
[16:29:57]: [altool]     );
[16:29:57]: [altool]     RestartClient = 0;
[16:29:57]: [altool]     ShouldUseRESTAPIs = 0;
[16:29:57]: [altool]     Success = 0;
[16:29:57]: [altool] }
[16:29:57]: [altool] 2023-02-17 16:29:57.739 Non-localized server string received: 'Error Description not available'.
[16:29:57]: [altool] 2023-02-17 16:29:57.739 Non-localized server string received: 'Error Description not available (-24169)'.
[16:29:57]: [altool] 2023-02-17 16:29:57.739 Non-localized server string received: 'Error Description not available'.
[16:29:57]: [altool] 2023-02-17 16:29:57.806 Bad status code: <MZWebServiceDAWTokenForUsernameAndPassword: 0x111e05fe0>
[16:29:57]: [altool] {"tool-version":"6.043.1[40](https://git.repo.appname/-/jobs/254260#L40)[43](https://git.repo.appname/name/appname-app/-/jobs/254260#L43)","tool-path":"\/Applications\/Xcode.app\/Contents\/SharedFrameworks\/ContentDeliveryServices.framework\/Versions\/A\/Frameworks\/AppStoreService.framework","os-version":"13.2.1","product-errors":[{"message":"Failed to list providers.","userInfo":{"NSLocalizedDescription":"Failed to list providers.","NSLocalizedFailureReason":"Failed to get authorization for username 'appleid' and password. (\n    \"Error Domain=NSCocoaErrorDomain Code=0 \\\"Status code: 0\\\" UserInfo={NSLocalizedDescription=Status code: 0, NSLocalizedFailureReason=The auth server returned a bad status code.}\"\n)"},"code":-1011}]}
[16:29:57]: [altool] 
[16:29:57]: Application Loader output above ^
[16:29:57]: The call to the altool completed with a non-zero exit status: 1. This indicates a failure.
[16:29:57]: Fetching password for transporter from environment variable named `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`
[16:29:57]: Going to upload updated app to App Store Connect
[16:29:57]: This might take a few minutes. Please don't interrupt the script.
[16:29:59]: [altool] 2023-02-17 16:29:59.151 *** Error: Unable to upload archive. Failed to get authorization for username 'appleid' and password. (
[16:29:59]: [altool]     "Error Domain=NSCocoaErrorDomain Code=0 \"Status code: 0\" UserInfo={NSLocalizedDescription=Status code: 0, NSLocalizedFailureReason=The auth server returned a bad status code.}"
[16:29:59]: [altool] ) (-1011)
[16:29:59]: [altool]  {
[16:29:59]: [altool]     NSLocalizedDescription = "Unable to upload archive.";
[16:29:59]: [altool]     NSLocalizedFailureReason = "Failed to get authorization for username 'appleid' and password. (\n    \"Error Domain=NSCocoaErrorDomain Code=0 \\\"Status code: 0\\\" UserInfo={NSLocalizedDescription=Status code: 0, NSLocalizedFailureReason=The auth server returned a bad status code.}\"\n)";
[16:29:59]: [altool] }
[16:29:[59](https://git.repo.appname/name/appname-app/-/jobs/254260#L59)]: Application Loader output above ^
[16:29:59]: The call to the altool completed with a non-zero exit status: 1. This indicates a failure.
[16:29:59]: Could not download/upload from App Store Connect!
+------------------+----------------+
|           Lane Context            |
+------------------+----------------+
| DEFAULT_PLATFORM | ios            |
| PLATFORM_NAME    | ios            |
| LANE_NAME        | ios deploy_ios |
+------------------+----------------+
[16:29:59]: Error uploading ipa file: 
 [Application Loader Error Output]: Error uploading '/var/folders/n_/_j0jjx_n35dbr_89n126_xjh0000gn/T/6e87780a-16e8-4bf7-82e5-08eae6c6da74.ipa'.
[Application Loader Error Output]: Unable to upload archive. Failed to get authorization for username 'appleid' and password. (
[Application Loader Error Output]: The call to the altool completed with a non-zero exit status: 1. This indicates a failure.
+------+----------------------+-------------+
|             fastlane summary              |
+------+----------------------+-------------+
| Step | Action               | Time (in s) |
+------+----------------------+-------------+
| 1    | update_fastlane      | 1           |
| 2    | default_platform     | 0           |
| 💥   | upload_to_testflight | 8           |
+------+----------------------+-------------+
[16:29:59]: fastlane finished with errors
[!] Error uploading ipa file: 
 [Application Loader Error Output]: Error uploading '/var/folders/n_/_j0jjx_n35dbr_89n126_xjh0000gn/T/6e87780a-16e8-4bf7-82e5-08eae6c6da[74](https://git.repo.appname/name/appname-app/-/jobs/254260#L74).ipa'.
[Application Loader Error Output]: Unable to upload archive. Failed to get authorization for username 'appleid' and password. (
[Application Loader Error Output]: The call to the altool completed with a non-zero exit status: 1. This indicates a failure.
Cleaning up project directory and file based variables
00:00
ERROR: Job failed: exit status 1
```

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 13.2.1                                      |
| Ruby                        | 3.1.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.37.1 (Apple Git-137.1)        |
| Installation Source         | ~/.rvm/gems/ruby-3.1.0/bin/fastlane         |
| Host                        | macOS 13.2.1 (22D68)                        |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-3.1.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.1o  3 May 2022                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 14.2                                        |
| Swift Version               | 5.7.2                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.211.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| faraday-cookie_jar              | 0.0.7        |
| gh_inspector                    | 1.1.3        |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| set                             | 1.0.2        |
| rexml                           | 3.2.5        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.1.0        |
| CFPropertyList                  | 3.0.6        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.22.0       |
| unicode-display_width           | 1.8.0        |
| public_suffix                   | 5.0.1        |
| addressable                     | 2.8.1        |
| excon                           | 0.99.0       |
| ruby2_keywords                  | 0.0.5        |
| faraday-retry                   | 1.0.3        |
| faraday-rack                    | 1.0.0        |
| faraday-patron                  | 1.0.0        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-net_http                | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-httpclient              | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.10.3       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| json                            | 2.6.3        |
| mini_magick                     | 4.12.0       |
| dotenv                          | 2.8.1        |
| bundler                         | 2.3.22       |
| simctl                          | 1.6.10       |
| jwt                             | 2.7.0        |
| webrick                         | 1.8.1        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| signet                          | 0.17.0       |
| os                              | 1.1.4        |
| memoist                         | 0.16.2       |
| googleauth                      | 1.3.0        |
| mini_mime                       | 1.1.2        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.2        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| google-apis-core                | 0.11.0       |
| google-apis-playcustomapp_v1    | 0.12.0       |
| google-apis-androidpublisher_v3 | 0.34.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-apis-storage_v1          | 0.19.0       |
| google-apis-iamcredentials_v1   | 0.16.0       |
| google-cloud-errors             | 1.3.0        |
| google-cloud-env                | 1.6.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.44.0       |
| emoji_regex                     | 3.2.3        |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.2        |
| aws-partitions                  | 1.713.0      |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.170.0      |
| aws-sdk-kms                     | 1.62.0       |
| aws-sdk-s3                      | 1.119.1      |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.1        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.1        |
| uri                             | 0.11.0       |
| openssl                         | 3.0.0        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.3        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.0        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.2        |
| net-http                        | 0.2.0        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.10       |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.3        |
</details>

*generated on:* **2023-02-17**
</details>

Macos: Ventura 13.2.1
Xcode: Version 14.2 (14C18)
</details>

**Comment by ilendemli** [comment]
I have the same issue when running altool directly.

**Comment by js-adalo** [comment]
We're seeing this, too. Apple system status is green at the moment, but y'all know how that goes 🤷‍♀️

**Comment by revolter** [comment]
I switched from the old `FASTLANE_USER` env var and password in the Keychain to the [`app_store_connect_api_key`](http://docs.fastlane.tools/actions/app_store_connect_api_key/) action, and it worked.

**Comment by mylogon341** [comment]
We're also seeing this. It was happening intermittently this morning (9-12 GMT) but and retrying it fixed it once or twice but now it's 100% of the time. The fact that it was on and off this morning said to me that something was failing rather than something expiring (or whatever) on my end...
Hopefully it's all resolved itself when I get back into the office on Monday :)

**Comment by dimitri320** [comment]
We're seeing this same exact issue. Last release on a week ago, all was working fine. Today all day, we've being seeing this issue.

**Comment by david-var** [comment]
I think this is because of 	
Developer ID Notary Service - Issue
https://developer.apple.com/system-status/
![Screenshot 2023-02-17 at 11 57 01](https://user-images.githubusercontent.com/3316824/219715913-d8d1542a-bc10-445e-bf53-5946371261d8.png)

**Comment by bsalves** [comment]
I had tried to upload an archive through Xcode and it worked properly, but, when I try to upload the same archive through fastlane it crash!

**Comment by madjuju** [comment]
same issue since 4 month. 
First fastlane make a session cookies login and stop in the keychain deliver.xxx.com with the apple password. But when it try tu upload the bundle it should use apple application password but expose the Apple ID password.

So they ask 2 different password for the same keychain element. It makes me crazy

**Comment by Jarutais** [comment]
Same issue here, let's hope Apple fixes it on their side

**Comment by ptfly** [comment]
> I switched from the old `FASTLANE_USER` env var and password in the Keychain to the [`app_store_connect_api_key`](http://docs.fastlane.tools/actions/app_store_connect_api_key/) action, and it worked.

Confirmed, it's working flawlessly, thanks!

**Comment by bsalves** [comment]
> I switched from the old `FASTLANE_USER` env var and password in the Keychain to the [`app_store_connect_api_key`](http://docs.fastlane.tools/actions/app_store_connect_api_key/) action, and it worked.

In this case are you changed manually this key on the Keychain?

**Comment by komritza** [comment]
> I think this is because of Developer ID Notary Service - Issue https://developer.apple.com/system-status/ ![Screenshot 2023-02-17 at 11 57 01](https://user-images.githubusercontent.com/3316824/219715913-d8d1542a-bc10-445e-bf53-5946371261d8.png)

It looks like that you were right. They changed the status to fixed, I did new build and I have successfully deployed the app to test flight. Thanks everyone!

**Comment by david-var** [comment]
thanks @komritza. I can confirm the same. In our CI/CD it was not working today in the morning. And it's working now again. 🚀

**Comment by dimitri320** [comment]
And it's not working again. I think we should re-open this issue :face_palm:

**Comment by komritza** [comment]
> And it's not working again. I think we should re-open this issue :face_palm:

I am not sure that this problem has anything to do with `fastlane`, because as mentioned previously, I have successfully deployed the app to `TestFlight` without changing anything from my side.

**Comment by ConfusedVorlon** [comment]
I'm seeing this issue today
No _reported_ outages on Apple Status

```
[17:28:33]: Going to upload updated app to App Store Connect
[17:28:33]: This might take a few minutes. Please don't interrupt the script.
[17:28:35]: [altool] 2023-02-24 17:28:35.208 *** Error: Unable to upload archive. Failed to get authorization for username 'hobbyist@hobbyistsoftware.com' and password. (

[17:28:35]: [altool]     "Error Domain=NSCocoaErrorDomain Code=0 \"Status code: 0\" UserInfo={NSLocalizedDescription=Status code: 0, NSLocalizedFailureReason=The auth server returned a bad status code.}"

[17:28:35]: [altool] ) (-1011)

[17:28:35]: [altool]  {

[17:28:35]: [altool]     NSLocalizedDescription = "Unable to upload archive.";

[17:28:35]: [altool]     NSLocalizedFailureReason = "Failed to get authorization for username 'hobbyist@hobbyistsoftware.com' and password. (\n    \"Error Domain=NSCocoaErrorDomain Code=0 \\\"Status code: 0\\\" UserInfo={NSLocalizedDescription=Status code: 0, NSLocalizedFailureReason=The auth server returned a bad status code.}\"\n)";

[17:28:35]: [altool] }
```

**Comment by vaccarov** [comment]
[Solved with this](https://stackoverflow.com/a/74229749/8222564)

It turns out that it's not related to related to transporter but you have to create an apple application password and store it in the .env with FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD

**Comment by iosdevben** [comment]
What @vaccarov suggested worked for me.

**Comment by Alexzenderus** [comment]
> I switched from the old `FASTLANE_USER` env var and password in the Keychain to the [`app_store_connect_api_key`](http://docs.fastlane.tools/actions/app_store_connect_api_key/) action, and it worked.

@revolter thanks, it worked with your solution !

**Comment by NightSkyWatchers** [comment]
> [Solved with this](https://stackoverflow.com/a/74229749/8222564)
> 
> It turns out that it's not related to related to transporter but you have to create an apple application password and store it in the .env with FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD

it works for me

**Comment by mohamedanwer123** [comment]
i have this issues and i can't solve it ... please any help

**Comment by jakansha2001** [comment]
Fastlane needs an Apple user id and app-specific password for iOS configuration which is present in the .env file with the environment variable 'FASTLANE_USER' and 'FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD'. 

To generate an app-specific password:
- Go to https://appleid.apple.com/account/manage, log in, and then go to App-Specific Passwords, from here, generate a new App-Specific Password and copy it.
- Now, inside your .env file, add these two properties:
FASTLANE_USER=<Apple USER ID>
FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD=<App-Specific Password>

This way you can use an app-specific password to sign in to an app or a service not provided by Apple such as Fastlane.

**Comment by jakansha2001** [comment]
> @jakansha2001 Where do I find the .env File? Thanks!

Hi @louis-sicko, you can create a `.env` file on your own in `ios/fastlane/.env` and add the two properties I mentioned above.

**Comment by thejeff77** [comment]
I've setup the .env file as mentioned by @jakansha2001 [here](https://github.com/fastlane/fastlane/issues/21060#issuecomment-1772362069). I've also run `fastlane precheck` and it says it can login fine. 

Despite the above steps being completed, I still get the following:

```
 [Application Loader Error Output]: Error uploading '/var/folders/rm/gb3cy4bj14n_dr8c6m8c4n2m0000gn/T/ac7a32f8-3bee-43c3-a377-6d6f2cc68144.ipa'.
[Application Loader Error Output]: Unable to upload archive. Failed to get authorization for username 'someschmuck@gmail.com' and password. (
[Application Loader Error Output]: The call to the altool completed with a non-zero exit status: 1. This indicates a failure.
 ```
 
 Plus as previously mentioned, all of the [apple systems](https://developer.apple.com/system-status/) are showing as green and up.
 
 Any help with this nonsense would be very appreciated! The fastlane process should run this on precheck and also give a helpful link for setup if its setup related, which it doesn't appear to be so far.

**Comment by thejeff77** [comment]
@louis-sicko ... the info above is incorrect about the environment. Nowhere does it say or work to create a .env file in the fastlane folder with the format mentioned above. 

Simply creating this file doesn't put it in environment variables or in fastlane. 

Follow the official fastlane docs [here for keys](https://docs.fastlane.tools/best-practices/keys/) to setup your environment.

In order for this to work, you must export these to your environment.. and put this in a .bash_profile or something that will consistently keep it in your terminal environment eg:

```
export FASTLANE_USER=<Apple USER ID>
export FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD=<App-Specific Password>
```

Fastlane Precheck should really check this and report if it isn't there.

**Comment by Saipavangithub1920** [comment]
Error:
I am facing the below Screenshot error.

Error uploading ipa file:
[Application Loader Error Output]: Error uploading 'va/folders/sdfhdsg/sdjnaskd/sdsgsd.ipa
Unable to upload archive. Failed to get authorisation for username 'xxxxxxxx.com' and password. 
The call to the altol completed with a non-zero exit status: 1. This indicates a failure.

**I am using below fastlane code to build and upload to testflight.**

![image](https://github.com/fastlane/fastlane/assets/166187758/2b81415b-bad5-459d-bfe3-8ee83f0d5fa4)

platform :ios do
  desc "push a new beta to testFlight"
  lane :beta do
    increment_build_number(xxxxproj: "Runner.xxxxproj")
    build_app(workspace: "Runner.xxxxxspace", schema: "Myapp")
    upload_to_testflight
  end
end

**.env file i used like below**

app_identifier = "com.xxxxxx.xxxxxin

**APPFILE like below**

app_identifier("com.xxxxx.xxxxxin")
apple_id("axxxx@xxxxx.com")


Please provide me the correct solution, This is urgent issue for me.

**Comment by GusttavoCastilho** [comment]
@Saipavangithub1920 did you manage to fix?

**Comment by daholino** [comment]
I had the same issue and after using app specific password generated on the Apple account profile page everything worked as expected. Thank you.

**Comment by revolter** [comment]
> @louis-sicko ... the info above is incorrect about the environment. Nowhere does it say or work to create a .env file in the fastlane folder with the format mentioned above.
> 
> Simply creating this file doesn't put it in environment variables or in fastlane.

Actually, fastlane does automatically load environment variables when put in an `.env` file next to the `Fastfile`: https://docs.fastlane.tools/advanced/other/#environment-variables

**Comment by srinathsilla** [comment]
> @louis-sicko ... the info above is incorrect about the environment. Nowhere does it say or work to create a .env file in the fastlane folder with the format mentioned above.
> 
> Simply creating this file doesn't put it in environment variables or in fastlane.
> 
> Follow the official fastlane docs [here for keys](https://docs.fastlane.tools/best-practices/keys/) to setup your environment.
> 
> In order for this to work, you must export these to your environment.. and put this in a .bash_profile or something that will consistently keep it in your terminal environment eg:
> 
> ```
> export FASTLANE_USER=<Apple USER ID>
> export FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD=<App-Specific Password>
> ```
> 
> Fastlane Precheck should really check this and report if it isn't there.

Worked for me after I exported those commands in my terminal. Thanks

**Comment by alexander0205** [comment]
https://stackoverflow.com/a/74229749/5963210
The solution

**Comment by sparkts-shaun** [comment]
I had recently changed my Appstore Connect password. I had to update the `fastlane_keychain_login` in my Keychain manually.

**Comment by han4wluc** [comment]
Need to create an app-specific  password:

	1.	Go to [Apple ID](https://appleid.apple.com/)
	2.	Sign in and navigate to Security
	3.	Generate an App-Specific Password
	4.	Use this password in your Fastlane commands

and then set env variable like is suggested agove

**Comment by voghDev** [comment]
We had the exact same issue and it seems due to Apple systems outage. Thanks everyone for the clear information in this thread.

<img width="1066" height="945" alt="Image" src="https://github.com/user-attachments/assets/331e9135-8abb-4da1-8130-f89cb2551cf1" />
