### ISSUE TITLE
"Invalid screen size" error for Apple Watch Ultra

### ISSUE THREAD

**Issue by xiii111** [fastlane/fastlane#21086]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Simular to https://github.com/fastlane/fastlane/issues/18244

According to https://help.apple.com/app-store-connect/#/devd274dd925 , screenshot size of Apple Watch Ultra is 410x502. However, the following error occurs.

```
🚫 Error: ./fastlane/screenshots/ja/0_APP_WATCH_ULTRA_0.png - Invalid screen size (Actual size is 410x502. See the specifications to fix https://help.apple.com/app-store-connect/#/devd274dd925)
```

I think the reason is lack of Apple Watch Ultra size in the following codes.

https://github.com/fastlane/fastlane/blob/13f4db247af1ffab04201ac37248fe4c28075812/deliver/lib/deliver/app_screenshot.rb#L331-L339

##### Command executed

The error is created by `upload_to_app_store`.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
+----------------------------------------------+-------------------------------------------------------------------------------+
|                                                   deliver 2.212.1 Summary                                                    |
+----------------------------------------------+-------------------------------------------------------------------------------+
| app_identifier                               | ...                                        |
| app_version                                  | ...                                                                        |
| build_number                                 | ...                                                                         |
| skip_screenshots                             | false                                                                         |
| automatic_release                            | false                                                                         |
| phased_release                               | false                                                                         |
| reset_ratings                                | false                                                                         |
| submit_for_review                            | false                                                                         |
| force                                        | true                                                                          |
| reject_if_possible                           | true                                                                          |
| skip_binary_upload                           | true                                                                          |
| precheck_include_in_app_purchases            | false                                                                         |
| submission_information.add_id_info_uses_idfa | false                                                                         |
| screenshots_path                             | ./fastlane/screenshots                                                        |
| metadata_path                                | ./fastlane/metadata                                                           |
| api_key_path                                 | ... |
| platform                                     | ios                                                                           |
| edit_live                                    | false                                                                         |
| use_live_version                             | false                                                                         |
| skip_metadata                                | false                                                                         |
| skip_app_version_update                      | false                                                                         |
| overwrite_screenshots                        | false                                                                         |
| sync_screenshots                             | false                                                                         |
| verify_only                                  | false                                                                         |
| run_precheck_before_submit                   | true                                                                          |
| precheck_default_rule_level                  | warn                                                                          |
| ignore_language_directory_validation         | false                                                                         |
+----------------------------------------------+-------------------------------------------------------------------------------+

...

[07:25:35]: 🚫 Invalid screenshots were detected! Here are the reasons:
[07:25:35]: 🚫 Error: ./fastlane/screenshots/ja/0_APP_WATCH_ULTRA_0.png - Invalid screen size (Actual size is 410x502. See the specifications to fix https://help.apple.com/app-store-connect/#/devd274dd925)
[07:25:35]: 🚫 Error: ./fastlane/screenshots/ja/1_APP_WATCH_ULTRA_1.png - Invalid screen size (Actual size is 410x502. See the specifications to fix https://help.apple.com/app-store-connect/#/devd274dd925)
[07:25:35]: 🚫 Error: ./fastlane/screenshots/ja/2_APP_WATCH_ULTRA_2.png - Invalid screen size (Actual size is 410x502. See the specifications to fix https://help.apple.com/app-store-connect/#/devd274dd925)

...

</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                               |
| --------------------------- | --------------------------------------------------- |
| OS                          | 13.1                                                |
| Ruby                        | 3.1.3                                               |
| Bundler?                    | true                                                |
| Git                         | git version 2.37.0                  |
| Installation Source         | ~/XXX/Vendor/Bundler/ruby/3.1.0/bin/fastlane |
| Host                        | macOS 13.1 (22C65)                                  |
| Ruby Lib Dir                | ~/.rbenv/versions/3.1.3/lib                         |
| OpenSSL Version             | OpenSSL 3.0.8 7 Feb 2023                            |
| Is contained                | false                                               |
| Is homebrew                 | false                                               |
| Is installed via Fabric.app | false                                               |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/         |
| Xcode Version               | 14.0                                                |
| Swift Version               | 5.7                                                 |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | ja_JP.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
...
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.212.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| bundler                         | 2.1.4        |
| pathname                        | 0.2.0        |
| set                             | 1.0.2        |
| tsort                           | 0.1.0        |
| shellwords                      | 0.1.0        |
| digest                          | 3.1.0        |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.6        |
| concurrent-ruby                 | 1.1.10       |
| i18n                            | 1.12.0       |
| minitest                        | 5.17.0       |
| tzinfo                          | 2.0.5        |
| zeitwerk                        | 2.6.6        |
| activesupport                   | 6.1.7.1      |
| public_suffix                   | 4.0.7        |
| addressable                     | 2.8.1        |
| httpclient                      | 2.8.3        |
| json                            | 2.6.3        |
| algoliasearch                   | 1.27.5       |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.714.0      |
| aws-sigv4                       | 1.5.2        |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.170.0      |
| aws-sdk-kms                     | 1.62.0       |
| aws-sdk-s3                      | 1.119.1      |
| babosa                          | 1.0.4        |
| claide                          | 1.1.0        |
| fuzzy_match                     | 2.0.4        |
| nap                             | 1.1.0        |
| netrc                           | 0.11.0       |
| ffi                             | 1.15.5       |
| ethon                           | 0.15.0       |
| typhoeus                        | 1.4.0        |
| cocoapods-core                  | 1.11.3       |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.99.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.0.0        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.3       |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.7.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.3.0        |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| webrick                         | 1.8.1        |
| google-apis-core                | 0.11.0       |
| google-apis-androidpublisher_v3 | 0.34.0       |
| google-apis-playcustomapp_v1    | 0.12.0       |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.19.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.44.0       |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.10       |
| terminal-notifier               | 2.0.0        |
| terminal-table                  | 1.4.5        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| rchardet                        | 1.8.0        |
| git                             | 1.13.0       |
| liquid                          | 4.0.0        |
| thor                            | 0.19.1       |
| generamba                       | 1.6.0        |
| slack-notifier                  | 2.4.0        |
| xcresult                        | 0.2.1        |
| xcov                            | 1.8.1        |
</details>

*generated on:* **2023-02-27**
</details>

**Comment by acevif** [comment]
Same problem.
