### ISSUE TITLE
Reading keychain entry, because either user or password were empty

### ISSUE THREAD

**Issue by biyuhuaping** [fastlane/fastlane#21119]
INFO [2023-03-09 18:02:50.52]: Installing provisioning profile...
WARN [2023-03-09 18:02:51.32]: Setting environment variable 'sigh_com.ybm.GDD_development' to 'a36f149b-cea0-494a-8d24-cf9179b57a30'
WARN [2023-03-09 18:02:51.32]: Setting environment variable 'sigh_com.ybm.GDD_development_team-id' to '5Z2477437E'
WARN [2023-03-09 18:02:51.32]: Setting environment variable 'sigh_com.ybm.GDD_development_certificate-name' to 'Apple Development: xiaoyang li (2UV86B857L)'
WARN [2023-03-09 18:02:51.32]: Setting environment variable 'sigh_com.ybm.GDD_development_profile-name' to 'match Development com.ybm.GDD'
WARN [2023-03-09 18:02:51.32]: Setting environment variable 'sigh_com.ybm.GDD_development_profile-path' to '/Users/yaobangmang/Library/MobileDevice/Provisioning Profiles/a36f149b-cea0-494a-8d24-cf9179b57a30.mobileprovision'
undefined method `git_url' for #<CredentialsManager::AppfileConfig:0x00007f8cb39ada70>
undefined method `git_url' for #<CredentialsManager::AppfileConfig:0x00007f8cb39d01d8>
undefined method `git_url' for #<CredentialsManager::AppfileConfig:0x00007f8cb39e33f0>
undefined method `git_url' for #<CredentialsManager::AppfileConfig:0x00007f8cb3a016c0>
undefined method `git_url' for #<CredentialsManager::AppfileConfig:0x00007f8cb1de3600>

+-------------------------------------+------------------------------+
|                      Summary for sigh 2.212.1                      |
+-------------------------------------+------------------------------+
| app_identifier                      | com.xyycrm                   |
| force                               | false                        |
| cert_id                             | B75DRM3Z7H                   |
| provisioning_name                   | match Development com.xyycrm |
| ignore_profiles_with_different_name | true                         |
| fail_on_name_taken                  | false                        |
| include_all_certificates            | false                        |
| include_mac_in_profiles             | false                        |
| platform                            | ios                          |
| development                         | true                         |
| adhoc                               | false                        |
| developer_id                        | false                        |
| skip_install                        | false                        |
| skip_fetch_profiles                 | false                        |
| skip_certificate_verification       | false                        |
| readonly                            | false                        |
+-------------------------------------+------------------------------+
Unable to find 'X-Apple-HC-Bits' and 'X-Apple-HC-Challenge' to make hashcash

Looking for related GitHub issues on fastlane/fastlane...
Search query: The request could not be completed because:
	<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>Apple</center>
</body>
</html>

**Comment by celtaheaven** [comment]
Happens with me as well.

**Comment by taschik** [comment]
I am encountering exactly the same issue right now. Did you find a solution @biyuhuaping ?

**Comment by biyuhuaping** [comment]
> 我现在遇到完全相同的问题。你找到解决办法了吗@biyuhuaping？

我换了一台电脑，就奇迹般的好啦，应该是电脑环境问题。

**Comment by tysonios** [comment]
@biyuhuaping Can you provide any solution?
