### ISSUE TITLE
`Setup_circle_ci` is failing on Ventura 13.2.1 while running on CircleCi

### ISSUE THREAD

**Issue by AleksPetrovski** [fastlane/fastlane#21122]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

We have self-hosted runner on CircleCI, in Fastfile `before_all` we are running `setup_circle_ci` and it's failing immediately. 
machine config:
Ventura 13.2.1
Mac mini m1

##### Command executed

Fastfile:
<pre>
  before_all do
     ...
     setup_circle_ci
     ...
  end
</pre>

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> #!/bin/bash --login -eo pipefail
bundle exec fastlane resolve_dependencies --verbose
[⠋] 🚀 [⠙] 🚀 [⠹] 🚀 [⠸] 🚀 [⠼] 🚀 [✔] 🚀 
DEBUG [2023-03-08 19:49:46.02]: Checking if there are any plugins that should be loaded...
DEBUG [2023-03-08 19:49:46.02]: Loading 'fastlane-plugin-xcconfig' plugin
INFO [2023-03-08 19:49:46.02]: gem 'fastlane-plugin-xcconfig' is already installed
+--------------------------+---------+---------------------------------------------------------------+
|                                            Used plugins                                            |
+--------------------------+---------+---------------------------------------------------------------+
| Plugin                   | Version | Action                                                        |
+--------------------------+---------+---------------------------------------------------------------+
| fastlane-plugin-xcconfig | 2.0.0   | update_xcconfig_value, set_xcconfig_value, get_xcconfig_value |
+--------------------------+---------+---------------------------------------------------------------+

tput: unknown terminal "unknown"
tput: unknown terminal "unknown"
INFO [2023-03-08 19:49:46.59]: ----------------------------------------
INFO [2023-03-08 19:49:46.59]: --- Step: Verifying fastlane version ---
INFO [2023-03-08 19:49:46.59]: ----------------------------------------
INFO [2023-03-08 19:49:46.59]: Your fastlane version 2.212.1 matches the minimum requirement of 2.89.0  ✅
tput: unknown terminal "unknown"
tput: unknown terminal "unknown"
INFO [2023-03-08 19:49:46.60]: ------------------------------
INFO [2023-03-08 19:49:46.60]: --- Step: default_platform ---
INFO [2023-03-08 19:49:46.60]: ------------------------------
INFO [2023-03-08 19:49:46.60]: Driving the lane 'ios resolve_dependencies' 🚀
tput: unknown terminal "unknown"
tput: unknown terminal "unknown"
INFO [2023-03-08 19:49:46.61]: ---------------------------------------
INFO [2023-03-08 19:49:46.61]: --- Step: app_store_connect_api_key ---
INFO [2023-03-08 19:49:46.61]: ---------------------------------------
tput: unknown terminal "unknown"
tput: unknown terminal "unknown"
INFO [2023-03-08 19:49:46.62]: -------------------
INFO [2023-03-08 19:49:46.62]: --- Step: is_ci ---
INFO [2023-03-08 19:49:46.62]: -------------------
tput: unknown terminal "unknown"
tput: unknown terminal "unknown"
INFO [2023-03-08 19:49:46.62]: -----------------------------
INFO [2023-03-08 19:49:46.62]: --- Step: setup_circle_ci ---
INFO [2023-03-08 19:49:46.62]: -----------------------------
INFO [2023-03-08 19:49:46.62]: Creating temporary keychain: "fastlane_tmp_keychain".
WARN [2023-03-08 19:49:46.62]: Found keychain '~/Library/Keychains/fastlane_tmp_keychain', creation skipped
WARN [2023-03-08 19:49:46.62]: If creating a new Keychain DB is required please set the `require_create` option true to cause the action to fail
WARN [2023-03-08 19:49:46.65]: Lane Context:
INFO [2023-03-08 19:49:46.65]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios resolve_dependencies", :KEYCHAIN_PATH=>"~/Library/Keychains/fastlane_tmp_keychain", :ORIGINAL_DEFAULT_KEYCHAIN=>"\"/Library/Keychains/System.keychain\""}
ERROR [2023-03-08 19:49:46.65]: Shell command exited with exit status 1 instead of 0.

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 3    | app_store_connect_api_key  | 0           |
| 4    | is_ci                      | 0           |
| 💥   | setup_circle_ci            | 0           |
+------+----------------------------+-------------+

DEBUG [2023-03-08 19:49:46.65]: All plugins are up to date
ERROR [2023-03-08 19:49:46.65]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: Shell command exited with exit status 1 instead of 0.

URL: https://api.github.com/search/issues?q=Shell%20command%20exited%20with%20exit%20status%201%20instead%20of%200.+repo:fastlane/fastlane
➡️  Shell command exited with exit status 1 instead of 0. git_add action
    https://github.com/fastlane/fastlane/issues/20624 [open] 6 💬
    02 Nov 2022

➡️  "method_missing" Shell command exited with exit status 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError) when bundling on Android
    https://github.com/fastlane/fastlane/issues/20493 [open] 10 💬
    18 Nov 2022

➡️  Improve Beta Setup
    https://github.com/fastlane/fastlane/pull/1 [closed] 1 💬
    04 Feb 2017

and 98 more at: https://github.com/fastlane/fastlane/search?q=Shell%20command%20exited%20with%20exit%20status%201%20instead%20of%200.&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
DEBUG [2023-03-08 19:49:48.18]: All plugins are up to date
bundler: failed to load command: fastlane (/Users/eng.user/.rvm/gems/ruby-2.7.7/bin/fastlane)
Traceback (most recent call last):
	55: from /Users/eng.user/.rvm/gems/ruby-2.7.7/bin/bundle:23:in `<main>'
	54: from /Users/eng.user/.rvm/gems/ruby-2.7.7/bin/bundle:23:in `load'
	53: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/bundler-2.4.8/exe/bundle:33:in `<top (required)>'
	52: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/bundler-2.4.8/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	51: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/bundler-2.4.8/exe/bundle:45:in `block in <top (required)>'
	50: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/bundler-2.4.8/lib/bundler/cli.rb:28:in `start'
	49: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/bundler-2.4.8/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	48: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/bundler-2.4.8/lib/bundler/cli.rb:34:in `dispatch'
	47: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/bundler-2.4.8/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	46: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/bundler-2.4.8/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	45: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/bundler-2.4.8/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	44: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/bundler-2.4.8/lib/bundler/cli.rb:492:in `exec'
	43: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/bundler-2.4.8/lib/bundler/cli/exec.rb:23:in `run'
	42: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/bundler-2.4.8/lib/bundler/cli/exec.rb:58:in `kernel_load'
	41: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/bundler-2.4.8/lib/bundler/cli/exec.rb:58:in `load'
	40: from /Users/eng.user/.rvm/gems/ruby-2.7.7/bin/fastlane:23:in `<top (required)>'
	39: from /Users/eng.user/.rvm/gems/ruby-2.7.7/bin/fastlane:23:in `load'
	38: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/bin/fastlane:23:in `<top (required)>'
	37: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	36: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	35: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	34: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	33: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	32: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	31: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	30: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	29: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	28: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	27: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	26: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	25: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	24: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:46:in `block in execute'
	23: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:291:in `execute_flow_block'
	22: from Fastfile:200:in `block (2 levels) in parsing_binding'
	21: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	20: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	19: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	18: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	17: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	16: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	15: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	14: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/actions/setup_circle_ci.rb:5:in `run'
	13: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/other_action.rb:23:in `method_missing'
	12: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	11: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	10: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	 9: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	 8: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	 7: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 6: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/actions/setup_ci.rb:15:in `run'
	 5: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/actions/setup_ci.rb:42:in `setup_keychain'
	 4: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/actions/create_keychain.rb:44:in `run'
	 3: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
	 2: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	 1: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': Shell command exited with exit status 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
	55: from /Users/eng.user/.rvm/gems/ruby-2.7.7/bin/bundle:23:in `<main>'
	54: from /Users/eng.user/.rvm/gems/ruby-2.7.7/bin/bundle:23:in `load'
	53: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/bundler-2.4.8/exe/bundle:33:in `<top (required)>'
	52: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/bundler-2.4.8/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	51: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/bundler-2.4.8/exe/bundle:45:in `block in <top (required)>'
	50: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/bundler-2.4.8/lib/bundler/cli.rb:28:in `start'
	49: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/bundler-2.4.8/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	48: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/bundler-2.4.8/lib/bundler/cli.rb:34:in `dispatch'
	47: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/bundler-2.4.8/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	46: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/bundler-2.4.8/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	45: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/bundler-2.4.8/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	44: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/bundler-2.4.8/lib/bundler/cli.rb:492:in `exec'
	43: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/bundler-2.4.8/lib/bundler/cli/exec.rb:23:in `run'
	42: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/bundler-2.4.8/lib/bundler/cli/exec.rb:58:in `kernel_load'
	41: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/bundler-2.4.8/lib/bundler/cli/exec.rb:58:in `load'
	40: from /Users/eng.user/.rvm/gems/ruby-2.7.7/bin/fastlane:23:in `<top (required)>'
	39: from /Users/eng.user/.rvm/gems/ruby-2.7.7/bin/fastlane:23:in `load'
	38: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/bin/fastlane:23:in `<top (required)>'
	37: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	36: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	35: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	34: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	33: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	32: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	31: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	30: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	29: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	28: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	27: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	26: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	25: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	24: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:46:in `block in execute'
	23: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:291:in `execute_flow_block'
	22: from Fastfile:200:in `block (2 levels) in parsing_binding'
	21: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	20: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	19: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	18: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	17: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	16: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	15: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	14: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/actions/setup_circle_ci.rb:5:in `run'
	13: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/other_action.rb:23:in `method_missing'
	12: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	11: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	10: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	 9: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	 8: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	 7: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 6: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/actions/setup_ci.rb:15:in `run'
	 5: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/actions/setup_ci.rb:42:in `setup_keychain'
	 4: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/actions/create_keychain.rb:44:in `run'
	 3: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
	 2: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	 1: from /Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/eng.user/.rvm/gems/ruby-2.7.7/gems/fastlane-2.212.1/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': \e[31m[!] Shell command exited with exit status 1 instead of 0.\e[0m (FastlaneCore::Interface::FastlaneShellError)

Exited with code exit status 1
CircleCI received exit code 1 </pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 13.2.1                                      |
| Ruby                        | 2.7.7                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.37.1 (Apple Git-137.1)        |
| Installation Source         | ~/.rvm/gems/ruby-2.7.7/bin/fastlane         |
| Host                        | macOS 13.2.1 (22D68)                        |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.7.7/lib                |
| OpenSSL Version             | OpenSSL 1.1.1t  7 Feb 2023                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 14.1                                        |
| Swift Version               | 5.7.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

```
</details>

**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.212.1 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                   | Version | Update-Status |
| ------------------------ | ------- | ------------- |
| fastlane-plugin-xcconfig | 2.0.0   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.4.0        |
| atomos                          | 0.1.3        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| rexml                           | 3.2.5        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| public_suffix                   | 5.0.1        |
| addressable                     | 2.8.1        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.8.1        |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-storage_v1          | 0.19.0       |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.3.0        |
| digest-crc                      | 0.6.4        |
| mini_mime                       | 1.1.2        |
| google-cloud-storage            | 1.44.0       |
| emoji_regex                     | 3.2.3        |
| uri                             | 0.10.0       |
| CFPropertyList                  | 3.0.6        |
| plist                           | 3.7.0        |
| excon                           | 0.99.0       |
| ruby2_keywords                  | 0.0.5        |
| faraday-retry                   | 1.0.3        |
| faraday-rack                    | 1.0.0        |
| faraday-patron                  | 1.0.0        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-net_http                | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-httpclient              | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.10.3       |
| json                            | 2.6.3        |
| bundler                         | 2.4.8        |
| simctl                          | 1.6.10       |
| jwt                             | 2.7.0        |
| webrick                         | 1.8.1        |
| httpclient                      | 2.8.3        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.2        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| google-apis-core                | 0.11.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-apis-androidpublisher_v3 | 0.34.0       |
| google-apis-iamcredentials_v1   | 0.17.0       |
| rake                            | 13.0.6       |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.2        |
| aws-partitions                  | 1.717.0      |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.170.0      |
| aws-sdk-kms                     | 1.62.0       |
| aws-sdk-s3                      | 1.119.1      |
| forwardable                     | 1.3.1        |
| logger                          | 1.4.2        |
| cgi                             | 0.1.0.2      |
| date                            | 3.0.3        |
| timeout                         | 0.1.0        |
| stringio                        | 0.1.0        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.4        |
| zlib                            | 1.1.0        |
| mutex_m                         | 0.1.0        |
| ostruct                         | 0.2.0        |
| strscan                         | 1.0.3        |
| io-console                      | 0.5.6        |
| delegate                        | 0.1.0        |
| fileutils                       | 1.4.1        |
| singleton                       | 0.1.0        |
| open3                           | 0.1.0        |
| nokogiri                        | 1.13.10      |
| racc                            | 1.6.1        |
| yaml                            | 0.1.0        |
| psych                           | 3.1.0        |
| fastlane-plugin-xcconfig        | 2.0.0        |
</details>


*generated on:* **2023-03-09**
</details> </pre>
</details>

**Comment by AleksPetrovski** [comment]
Here are some additional logs
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/63307542/225515756-e98e2a50-3a42-4b91-8886-931f0015bc02.png">

**Comment by AleksPetrovski** [comment]
issues was resolved by adding <key>SessionCreate</key> <true/> to `/Library/LaunchDaemons/com.circleci.runner.plist` file

**Comment by michalsrutek** [comment]
To be more precise, you need to add the following entry to the `/Library/LaunchDaemons/com.circleci.runner.plist` file and restart the daemon.

```xml
<key>SessionCreate</key>
<true/>
```
