### ISSUE TITLE
Exit status: 65, no more message

### ISSUE THREAD

**Issue by plkgq** [fastlane/fastlane#21145]
▸ Running script '[CP] Embed Pods Frameworks'
▸ Running script '[CP] Copy Pods Resources'
▸ Running script 'swiftlint'
▸ Touching xxth.app (in target 'xxth' from project 'xxth')
** ARCHIVE FAILED **
[08:33:31]: Exit status: 65

+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.212.1                 |
| export_method | ad-hoc                  |
| sdk           | iPhoneOS16.2.sdk        |
+---------------+-------------------------+

[08:33:31]: ▸ /Users/pileqiageqiu/Desktop/Project/xxthios/xxth/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'NSObject+Rx' from project 'Pods')
[08:33:31]: ▸ /Users/pileqiageqiu/Desktop/Project/xxthios/xxth/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'RxCocoa' from project 'Pods')
[08:33:31]: ▸ /Users/pileqiageqiu/Desktop/Project/xxthios/xxth/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'JXBanner' from project 'Pods')
[08:33:31]: ▸ /Users/pileqiageqiu/Desktop/Project/xxthios/xxth/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'BSText' from project 'Pods')
[08:33:31]: ▸ /Users/pileqiageqiu/Desktop/Project/xxthios/xxth/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'Moya' from project 'Pods')
[08:33:31]:
[08:33:31]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[08:33:31]: 📋  For the complete and more detailed error log, check the full log at:
[08:33:31]: 📋  /Users/pileqiageqiu/Library/Logs/gym/xxth-xxth.log
[08:33:31]:
[08:33:31]: Looks like fastlane ran into a build/archive error with your project
[08:33:31]: It's hard to tell what's causing the error, so we wrote some guides on how
[08:33:31]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[08:33:31]: Before submitting an issue on GitHub, please follow the guide above and make
[08:33:31]: sure your project is set up correctly.
[08:33:31]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
[08:33:31]: the full commands printed out in yellow in the above log.
[08:33:31]: Make sure to inspect the output above, as usually you'll find more error information there
[08:33:31]:
+------------------------------+--------------+
|                Lane Context                 |
+------------------------------+--------------+
| DEFAULT_PLATFORM             | ios          |
| PLATFORM_NAME                | ios          |
| LANE_NAME                    | ios pub_test |
| XCODEBUILD_DERIVED_DATA_PATH |              |
| VERSION_NUMBER               | 2.1          |
| BUILD_NUMBER                 | 202303132101 |
+------------------------------+--------------+
[08:33:31]: Error building the application - see the log above

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | default_platform           | 0           |
| 2    | xcclean                    | 1           |
| 3    | Switch to ios package lane | 0           |
| 4    | get_version_number         | 0           |
| 5    | get_build_number           | 0           |
| 💥   | build_app                  | 96          |
+------+----------------------------+-------------+

[08:33:31]: fastlane finished with errors

[!] Error building the application - see the log above

### Captured Output

Command Used: `build_ios --capture_output`
<details><summary>Output/Log</summary>

```

DEBUG [2023-03-18 08:35:04.43]: Checking if there are any plugins that should be loaded...
DEBUG [2023-03-18 08:35:04.43]: Loading 'fastlane-plugin-pgyer' plugin
INFO [2023-03-18 08:35:04.43]: gem 'fastlane-plugin-pgyer' is already installed


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 13.2.1                                                         |
| Ruby                        | 2.6.10                                                         |
| Bundler?                    | true                                                           |
| Git                         | git version 2.37.1 (Apple Git-137.1)                           |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 13.2.1 (22D68)                                           |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 14.2                                                           |
| Swift Version               | 5.7.2                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
require 'net/http'
require 'uri'
require 'json'
require 'net/http/post/multipart'

default_platform(:ios)

platform :ios do

  # 更新pod及版本号
  before_all do
    # source_control
    # cocoapods(use_bundle_exec: false)
    # build_number_lane
    xcclean(scheme: ENV['SCHEME_NAME'])
  end

  after_all do |lane|
    say("Successfully finished deployment (#{lane})!")
  end

  error do |lane, exception|
    # send_dingding_error_msg("error":exception, "lane": lane)
  end

  # 测试包
  lane :pub_test do |option|

    package(configuration:"Debug",method:"ad-hoc")

  end

  # 正式包
  lane :pub_release do |option|

    package(configuration:"Release",method:"app-store")

  end

  # 打包函数
  private_lane :package do |option|

    method = option[:method]

    scheme = ENV['SCHEME_NAME']

    appName = ENV['APP_NAME']

    productName = ENV['PRODUCT_NAME']

    config = option[:configuration]

    targetName = ENV['TARGET_NAME']

    #currentTime = Time.new.strftime("%Y-%m-%d-%H-%M")

    # ipaName = "#{appName}-#{currentTime}.ipa"
    ipaName = "#{appName}.ipa"

    versionStr = get_version_number(target:targetName) 

    versionCode = get_build_number()

    # 更新版本号
    # increment_version_number_in_plist(target: appName, version_number: ENV['APP_VERSION_RELEASE'])

    #puts ">>>>>#{currentTime}<<<<<>>>>>开始打包 #{appName}<<<<<"

    # update_porfile(type: "adhoc")


      #打包
      build_app(
      clean: true,
      scheme: scheme,
      include_symbols: true,
      include_bitcode: false,
      workspace:"#{productName}.xcworkspace",
      export_method: method,
      configuration: config,
      export_xcargs: "-allowProvisioningUpdates",
      # codesigning_identity: "Apple Development: 守帅 康 (BZVB957LBZ)",
      # xcargs: "CODE_SIGN_STYLE=Manual DEVELOPMENT_TEAM=P6X2PX82QZ",

      output_name:ipaName,
      output_directory:"./build/#{appName}-#{config}",
      archive_path:"./build/#{appName}-#{config}/#{appName}.xcarchive"
      )
      

      workspace_path = File.expand_path("..")

      #upload_symbols_to_crashlytics(
      #  dsym_path: "#{workspace_path}/build/#{appName}-#{config}/#{appName}.app.dSYM.zip",
      #  gsp_path: "#{workspace_path}/#{appName}/Resource/Supporting Files/GoogleService-Info.plist"
      #)

      # method_app_store = "app-store"

      # if method != method_app_store then
      #   filePath="#{workspace_path}/build/#{appName}-#{config}/#{ipaName}"
      #   upload_ipa_to_pgyer(path: filePath)
      #   send_dingding_msg("version":"#{versionStr}(#{versionCode})", "method":method)
      # else
      #   deliver(force: false, skip_screenshots: true, skip_metadata: true)
      #   send_dingding_msg("version":"#{versionStr}(#{versionCode})", "method":method)
      # end

  end

  # 发送机器人🤖消息到钉钉群"
  private_lane :send_dingding_msg do |options|
    appName = ENV['APP_NAME']
    version = option[:version]
    method = option[:method]
    text = ""
    if method == "app-store" then
      text = "#{appName}(#{version})正式包已上传至苹果商店"
    else
      text = "#{appName}(#{version})测试包更新啦，下载地址：https://www.pgyer.com/xxx ,请查收~ "
    ding_talk_msg_push(token:dingding_token, text:text, at_all: false)
    end

  end

  # 发送机器人🤖消息到钉钉群"
  private_lane :send_dingding_error_msg do |options|
    appName = ENV['APP_NAME']
    dingding_token = ENV['DING_WEBHOOK_API']
    targetName = ENV['TARGET_NAME']
    versionStr = get_version_number(target:targetName) 
    versionCode = get_build_number()
    text = "#{appName}(#{versionStr}(#{versionCode}))打包失败, 错误原因[#{lane}]#{error}"
    ding_talk_msg_push(token:dingding_token, text:text, at_all: false)
  end

  private_lane :upload_ipa_to_pgyer do |options|
    filePath = option[:path]
    pgyer(
      api_key: "xxxx",
      user_key: "xxxx",
      ipa: filePath
    )
  end

  # 修改build
  private_lane :build_number_lane do |lane, options|
    today = Time.new; #获取当前时间
    todayString = today.strftime("%Y%m%d%H%M") 
    build_number = todayString
    increment_build_number(
      build_number: build_number # set a specific number
    )

  end

  # desc "重新生成证书及描述文件"
  private_lane :update_porfile do |option|
    type = option[:type]
    if type.nil?
      type = "development"
    end
    match(type: type, force_for_new_devices: true)
  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple Developer Portal username


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

app_identifier ENV['APP_IDENTIFIER']
apple_id ENV['APPLE_ID']
team_id ENV['TEAM_ID']
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.212.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                | Version | Update-Status |
| --------------------- | ------- | ------------- |
| fastlane-plugin-pgyer | 0.2.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.6.3        |
| bundler                         | 2.4.8        |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.6        |
| public_suffix                   | 5.0.1        |
| addressable                     | 2.8.1        |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.730.0      |
| aws-sigv4                       | 1.5.2        |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.170.1      |
| aws-sdk-kms                     | 1.63.0       |
| aws-sdk-s3                      | 1.119.1      |
| babosa                          | 1.0.4        |
| claide                          | 1.1.0        |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.99.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.0.0        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.3       |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.7.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.3.0        |
| httpclient                      | 2.8.3        |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| webrick                         | 1.8.1        |
| google-apis-core                | 0.11.0       |
| google-apis-androidpublisher_v3 | 0.36.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.19.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.1        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.44.0       |
| json                            | 2.6.3        |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.7.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.10       |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| fastlane-plugin-pgyer           | 0.2.4        |
</details>

*generated on:* **2023-03-18**
</details>

**Comment by plkgq** [comment]
These are the last few lines of the build log:

SetOwnerAndGroup pileqiageqiu:staff /Users/pileqiageqiu/Library/Developer/Xcode/DerivedData/xxth-gtcppysvgvzcfkdqgyuvmrytyqfp/Build/Intermediates.noindex/ArchiveIntermediates/xxth/InstallationBuildProductsLocation/Applications/xxth.app (in target 'xxth' from project 'xxth')
    cd /Users/pileqiageqiu/Desktop/Project/xxthios/xxth
    /usr/sbin/chown -RH pileqiageqiu:staff /Users/pileqiageqiu/Library/Developer/Xcode/DerivedData/xxth-gtcppysvgvzcfkdqgyuvmrytyqfp/Build/Intermediates.noindex/ArchiveIntermediates/xxth/InstallationBuildProductsLocation/Applications/xxth.app

SetMode u+w,go-w,a+rX /Users/pileqiageqiu/Library/Developer/Xcode/DerivedData/xxth-gtcppysvgvzcfkdqgyuvmrytyqfp/Build/Intermediates.noindex/ArchiveIntermediates/xxth/InstallationBuildProductsLocation/Applications/xxth.app (in target 'xxth' from project 'xxth')
    cd /Users/pileqiageqiu/Desktop/Project/xxthios/xxth
    /bin/chmod -RH u+w,go-w,a+rX /Users/pileqiageqiu/Library/Developer/Xcode/DerivedData/xxth-gtcppysvgvzcfkdqgyuvmrytyqfp/Build/Intermediates.noindex/ArchiveIntermediates/xxth/InstallationBuildProductsLocation/Applications/xxth.app

CodeSign /Users/pileqiageqiu/Library/Developer/Xcode/DerivedData/xxth-gtcppysvgvzcfkdqgyuvmrytyqfp/Build/Intermediates.noindex/ArchiveIntermediates/xxth/InstallationBuildProductsLocation/Applications/xxth.app (in target 'xxth' from project 'xxth')
    cd /Users/pileqiageqiu/Desktop/Project/xxthios/xxth
    
    Signing Identity:     "Apple Development: ** * (BZVB957LBZ)"
    Provisioning Profile: "iOS Team Provisioning Profile: com.xxth.www"
                          (114f0ce5-fc7f-475e-91d9-a5e532c22071)
    
    /usr/bin/codesign --force --sign 4F9D238DF29557272B8AD2BECAB995AF61FDDBC7 --entitlements /Users/pileqiageqiu/Library/Developer/Xcode/DerivedData/xxth-gtcppysvgvzcfkdqgyuvmrytyqfp/Build/Intermediates.noindex/ArchiveIntermediates/xxth/IntermediateBuildFilesPath/xxth.build/Debug-iphoneos/xxth.build/xxth.app.xcent --generate-entitlement-der /Users/pileqiageqiu/Library/Developer/Xcode/DerivedData/xxth-gtcppysvgvzcfkdqgyuvmrytyqfp/Build/Intermediates.noindex/ArchiveIntermediates/xxth/InstallationBuildProductsLocation/Applications/xxth.app

RegisterExecutionPolicyException /Users/pileqiageqiu/Library/Developer/Xcode/DerivedData/xxth-gtcppysvgvzcfkdqgyuvmrytyqfp/Build/Intermediates.noindex/ArchiveIntermediates/xxth/InstallationBuildProductsLocation/Applications/xxth.app (in target 'xxth' from project 'xxth')
    cd /Users/pileqiageqiu/Desktop/Project/xxthios/xxth
    builtin-RegisterExecutionPolicyException /Users/pileqiageqiu/Library/Developer/Xcode/DerivedData/xxth-gtcppysvgvzcfkdqgyuvmrytyqfp/Build/Intermediates.noindex/ArchiveIntermediates/xxth/InstallationBuildProductsLocation/Applications/xxth.app

Validate /Users/pileqiageqiu/Library/Developer/Xcode/DerivedData/xxth-gtcppysvgvzcfkdqgyuvmrytyqfp/Build/Intermediates.noindex/ArchiveIntermediates/xxth/InstallationBuildProductsLocation/Applications/xxth.app (in target 'xxth' from project 'xxth')
    cd /Users/pileqiageqiu/Desktop/Project/xxthios/xxth
    builtin-validationUtility /Users/pileqiageqiu/Library/Developer/Xcode/DerivedData/xxth-gtcppysvgvzcfkdqgyuvmrytyqfp/Build/Intermediates.noindex/ArchiveIntermediates/xxth/InstallationBuildProductsLocation/Applications/xxth.app

Touch /Users/pileqiageqiu/Library/Developer/Xcode/DerivedData/xxth-gtcppysvgvzcfkdqgyuvmrytyqfp/Build/Intermediates.noindex/ArchiveIntermediates/xxth/InstallationBuildProductsLocation/Applications/xxth.app (in target 'xxth' from project 'xxth')
    cd /Users/pileqiageqiu/Desktop/Project/xxthios/xxth
    /usr/bin/touch -c /Users/pileqiageqiu/Library/Developer/Xcode/DerivedData/xxth-gtcppysvgvzcfkdqgyuvmrytyqfp/Build/Intermediates.noindex/ArchiveIntermediates/xxth/InstallationBuildProductsLocation/Applications/xxth.app

**Comment by nwainwright** [comment]
Hi, we moved our CircleCI from Xcode 13.2.1 to 14.2.0 and ended up with an "Exit status: 65" too @plkgq 

Have you figured out the problem?

**Comment by plkgq** [comment]
> Hi, we moved our CircleCI from Xcode 13.2.1 to 14.2.0 and ended up with an "Exit status: 65" too @plkgq
> 
> Have you figured out the problem?


I haven't found a solution yet

**Comment by plkgq** [comment]
At present, I can confirm that my configuration environment is correct. I just created a new empty project, using the same certificate and other configurations, and it can be packaged normally.

**Comment by plkgq** [comment]
In addition, executing the following scripts can also be packaged successfully

**Comment by plkgq** [comment]
> In addition, executing the following scripts can also be packaged successfully

#!/bin/sh
export LANG=en_US.UTF-8

#项目、scheme名称
PROJECT_NAME="xxth"
SCHEME_NAME="xxth"


# debug 和 release 区分
BUILD_CONFIG="Debug"
EXPORTPLIST_PATH="/Users/pileqiageqiu/Downloads/packge/DevelopmentExportOptions.plist"



#ipa 路径
IPA_PATH="/Users/pileqiageqiu/Downloadss/packge/build/ipa/"
PROD_IPA_PATH="/Users/pileqiageqiu/Downloadss/packge/build/ProdIpa/"
XCARCHIVE_PATH="/Users/pileqiageqiu/Downloadss/packge/build/Debug_$branch"

ENVIRONMENT="beta"

# 蒲公英
USER_KEY=""
API_KEY="6472c7a4918fc80b14772bf9fdba972e"
PGY_URL=""

DATE=$(date +%m%d-%H-%M-%S)

ARRAY_NAME=('zhumingfu')
IS_COPY=false

cd ./xxth-ios/$PROJECT_NAME/$PROJECT_NAME
pod install

if [ $prod == "是" ]; then
  BUILD_CONFIG='Debug'
  EXPORTPLIST_PATH='../AdHocExportOptions.plist'
  XCARCHIVE_PATH="../build/Release_$branch"
  ENVIRONMENT="Prod"
fi

# master 的ipa 路径
# PROD_IPA_MASTER="../build/Release_origin/master"
# echo -e $PROD_IPA_MASTER
# if [[ -d "$PROD_IPA_MASTER" ]]; then
#   rm -r $PROD_IPA_MASTER
#   echo -e "删除已经存在的文件"
# fi

if [ ! -d "$XCARCHIVE_PATH" ]; then
    mkdir -p $XCARCHIVE_PATH
fi
#清除上次archive结果
xcodebuild -workspace  /Users/pileqiageqiu/Downloads/package/xxth-ios/xxth/xxth.xcworkspace -scheme $SCHEME_NAME -configuration $BUILD_CONFIG clean

PROJECT_BUILD=$(xcodebuild -project  /Users/pileqiageqiu/Downloads/package/xxth-ios/xxth/xxth.xcodeproj -scheme $SCHEME_NAME -showBuildSettings | grep -i 'CURRENT_PROJECT_VERSION' | sed 's/[ ]*CURRENT_PROJECT_VERSION = //')
echo $PROJECT_BUILD
#进行archive
xcodebuild -workspace  /Users/pileqiageqiu/Downloads/packge/xxth-ios/xxth/xxth.xcworkspace -scheme $PROJECT_NAME -configuration $BUILD_CONFIG -archivePath $XCARCHIVE_PATH/$PROJECT_NAME.xcarchive archive -destination 'generic/platform=iOS'
if [ $? != 0 ]; then
  echo -e "======archive失败======"
  curl -s 'https://oapi.dingtalk.com/robot/send?access_token=00b4f161da743839f2684c2c8154ba143c5b5ad820d7409ff76d482f63ce463b' -H 'Content-Type: application/json' -d '{"msgtype": "markdown", "markdown": {"title":"beta打包失败", "text": "#### '$DATE':iOS beta打包失败\n> ARCHIVE FAILED"}, "at": {"isAtAll": false}}'
  exit -1
fi

# 将archive 拷贝到Prod目录里面，上传appstore时候使用
if [[ $prod == "是" && $branch == "origin/master" ]]; then
  CP_PROD_ARCHIVE_PATH='../../B端_Prod/build/ProdArchive'
  if [[ -d "$CP_PROD_ARCHIVE_PATH" ]]; then
  	#删除archive文件
    rm -r $CP_PROD_ARCHIVE_PATH
   else 
    mkdir -p $CP_PROD_ARCHIVE_PATH
  fi
  # 判断是否符合身份
  for i in ${ARRAY_NAME[@]} 
  do
     if [ $i == $BUILD_USER_ID ];then
       IS_COPY=true
       break;
     fi
  done
  if $IS_COPY ; then
      echo '我去拷贝拉'
      #拷贝archive文件
  	cp -r ./$XCARCHIVE_PATH/  $CP_PROD_ARCHIVE_PATH
  fi
fi


echo -e "======开始打 ipa 包======"
#导出archive结果至指定目录
xcodebuild  -exportArchive -archivePath $XCARCHIVE_PATH/${PROJECT_NAME}.xcarchive -exportPath $IPA_PATH -exportOptionsPlist $EXPORTPLIST_PATH

**Comment by plkgq** [comment]
<img width="684" alt="image" src="https://user-images.githubusercontent.com/11607068/227140376-9c9fcc08-1745-4541-a3d7-72fcf842d148.png">

It worked after modifying it
