### ISSUE TITLE
Use Xcode 14 can't archive, Exit status 65

### ISSUE THREAD

**Issue by karthuszY** [fastlane/fastlane#21161]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 12.6.1                                      |
| Ruby                        | 2.6.10                                      |
| Bundler?                    | false                                       |
| Git                         | git version 2.37.0 (Apple Git-136)          |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane         |
| Host                        | macOS 12.6.1 (21G217)                       |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.10/lib                |
| OpenSSL Version             | OpenSSL 1.1.1q  5 Jul 2022                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 14.0.1                                      |
| Swift Version               | 5.7                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


default_platform(:ios)

platform :ios do
  lane :certificates do
    if ENV["GITHUB_TOKEN"].length == 0
      UI.user_error!("Error: Missing ENV $GITHUB_TOKEN")
    end
    match(git_url: "https://#{ENV["GITHUB_TOKEN"]}@github.com/ArcBlock/apple-certs.git",
          git_branch: "ArcBlock",
          readonly: false)
    match(git_url: "https://#{ENV["GITHUB_TOKEN"]}@github.com/ArcBlock/apple-certs.git",
          git_branch: "ArcBlock",
          type: "appstore",
          readonly: false)
  end

  lane :test do
    run_tests(workspace: "ArcWallet.xcworkspace",
              devices: ["iPhone 8"],
              scheme: "ArcWalletTests")
  end

  lane :local_build do 
    build_app(workspace: "ArcWallet.xcworkspace",
    configuration: "IsDevelop",
    scheme: "ArcWallet",
    include_bitcode: true,
    suppress_xcode_output: false)
  end

  lane :github_keychain do
    create_keychain(
      name: ENV["KEYCHAIN_NAME"],
      password: ENV["KEYCHAIN_PASSWORD"],
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true
    )
  end

  lane :before_deploy do
    if ENV["GITHUB_TOKEN"].length == 0
      UI.user_error!("Error: Missing ENV $GITHUB_TOKEN")
    end

    current_version_number = latest_testflight_build_number(version: get_version_number())
    if current_version_number >= get_build_number.to_i
      puts("Bumping build number")
      increment_build_number(build_number: current_version_number + 1)
      commit_version_bump(message: "bump build number")
      push_to_git_remote(
        local_branch: git_branch,
        remote_branch: git_branch,
        tags: false
      )
      UI.user_error!("Build number updated, exiting currently job...")
    end
  end

  lane :after_deploy do
    tag = "v" + File.read("../version").chop
    puts(tag)
    if git_tag_exists(tag: tag)
      puts("tag already exist")
    else
      puts("adding new tag...")
      add_git_tag(tag: tag)
    	push_git_tags(tag: tag)
    end
  end

  lane :install_pods do
    cocoapods
  end

  lane :beta do
    app_store_connect_api_key(
      key_id: "978LUF76BQ",
      issuer_id: "92d7361b-97b7-47ce-af96-786019700fef",
      key_content: ENV["API_KEY"],
      in_house: false, # optional but may be required if using match/sigh
    )

    sync_code_signing(git_url: "https://#{ENV["GITHUB_TOKEN"]}@github.com/ArcBlock/apple-certs.git",
                      git_branch: "ArcBlock",
                      type: "appstore",
                      keychain_name: ENV["KEYCHAIN_NAME"],
                      keychain_password: ENV["KEYCHAIN_PASSWORD"],
                      readonly: true)
    build_app(workspace: "ArcWallet.xcworkspace",
              configuration: ENV["PACKAGE_CONFIG"],
              scheme: "ArcWallet",              
              include_bitcode: true,
              suppress_xcode_output: false)
    changes = []
    File.read("../CHANGELOG.md").split("\n").each_with_index do |val, index|
      break if val.match(/^\#\#/) and index > 0
      if val.length > 0
        changes.push(val)
      end
    end
    changelog = changes.join('\n')

    ENV['ITMSTRANSPORTER_FORCE_ITMS_PACKAGE_UPLOAD'] = 'true'
    
    upload_to_testflight(localized_build_info: {
                                                  "default": {
                                                    whats_new: changelog,
                                                  },
                                                },
                          skip_waiting_for_build_processing: true)
  end

  lane :upload_symbols do
    download_dsyms(version: "latest")
    flurry_upload_dsym
    clean_build_artifacts
  end

end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("io.abtwallet.ABTWallet") # The bundle identifier of your app
apple_id("karthus@arcblock.io") # Your Apple email address
itc_team_id "120056565"

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.212.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                        | Version | Update-Status |
| ----------------------------- | ------- | ------------- |
| fastlane-plugin-flurry        | 0.1.2   | ✅ Up-To-Date  |
| fastlane-plugin-github_action | 1.0.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.1.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| terminal-table                  | 1.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| gh_inspector                    | 1.1.3        |
| security                        | 0.1.3        |
| rexml                           | 3.2.5        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.1.0        |
| CFPropertyList                  | 3.0.6        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.22.0       |
| unicode-display_width           | 1.8.0        |
| plist                           | 3.7.0        |
| public_suffix                   | 5.0.1        |
| addressable                     | 2.8.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| excon                           | 0.99.0       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| ruby2_keywords                  | 0.0.5        |
| faraday-retry                   | 1.0.3        |
| faraday-rack                    | 1.0.0        |
| faraday-patron                  | 1.0.0        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-net_http                | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-httpclient              | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.10.3       |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| json                            | 2.6.3        |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.8.1        |
| bundler                         | 2.1.4        |
| simctl                          | 1.6.10       |
| jwt                             | 2.7.0        |
| webrick                         | 1.8.1        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| signet                          | 0.17.0       |
| os                              | 1.1.4        |
| memoist                         | 0.16.2       |
| googleauth                      | 1.5.0        |
| mini_mime                       | 1.1.2        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.2        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| google-apis-core                | 0.11.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-apis-androidpublisher_v3 | 0.37.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-apis-storage_v1          | 0.19.0       |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-cloud-errors             | 1.3.1        |
| google-cloud-env                | 1.6.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.44.0       |
| emoji_regex                     | 3.2.3        |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.2        |
| aws-partitions                  | 1.735.0      |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.171.0      |
| aws-sdk-kms                     | 1.63.0       |
| aws-sdk-s3                      | 1.119.2      |
| forwardable                     | 1.2.0        |
| logger                          | 1.3.0        |
| date                            | 2.0.3        |
| stringio                        | 0.0.2        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.0.0        |
| mutex_m                         | 0.1.0        |
| net-http-persistent             | 2.9.4        |
| net-http-pipeline               | 1.0.1        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| io-console                      | 0.4.7        |
| fileutils                       | 1.1.0        |
| etc                             | 1.0.1        |
| rbnacl                          | 7.1.1        |
| ffi                             | 1.15.5       |
| psych                           | 3.1.0        |
| http-accept                     | 1.7.0        |
| netrc                           | 0.11.0       |
| rest-client                     | 2.1.0        |
| fastlane-plugin-flurry          | 0.1.2        |
| sshkey                          | 2.0.0        |
| fastlane-plugin-github_action   | 1.0.0        |
</details>

*generated on:* **2023-03-27**
</details>

<details>
<img width="646" alt="image" src="https://user-images.githubusercontent.com/13864988/227827117-8859bcd3-db2c-4687-be4e-f2157e5f9c9e.png">

</details>

**Comment by supmanyu** [comment]
Hi @karthuszY I'm facing the same error only on Github Actions CI, can you please tell me how were you able to fix this issue?
