### ISSUE TITLE
Android fastlane gradle task generates apk with version code and version name property values specified in build.gradle rather than the ones specified in fast file.

### ISSUE THREAD

**Issue by abhatnagar03** [fastlane/fastlane#21181]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [ x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I have a fast file with gradle task to clean, assemble and generate apk file. It looks like below:
```
gradle_properties = {
      "android.injected.version.code" => 2,
      "android.injected.version.name" => "dummy",
      "android.injected.signing.store.file" => options[:key_store],
      "android.injected.signing.store.password" => options[:key_file_password],
      "android.injected.signing.key.alias" => options[:key_alias],
      "android.injected.signing.key.password" => options[:key_store_password]
    }
    gradle(task: "clean")
    gradle(
      task: "assemble",
      flavor: "#{options[:buildConfiguration]}",
      build_type: "Release",
      project_dir: ".",
      print_command: true,
      print_command_output: false,
      properties: gradle_properties
    )
    apk_file_path = "#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}"
    
    
```
This task is executed using azure pipeline. The apk file used to get generated with correct version name and version code as specified in the fast file. I had gradle version 7.1.3 with plugin 7.0.2. My build.gradle code with default version code and version name looks like this:

```
defaultConfig {
        applicationId = AppConfig.applicationId
        minSdk = AndroidConfig.minSdk
        targetSdk = AndroidConfig.targetSdk

        versionCode = 1
        versionName = "debug"
        multiDexEnabled = true

        testInstrumentationRunner = AndroidConfig.androidTestInstrumentation

        // Redirect Scheme used by OAuth library.
        addManifestPlaceholders(mapOf("appAuthRedirectScheme" to "com.gropyus.bos"))
    }
```
    
    Lately when I upgraded my gradle version to latest plug 7.5, fastlane gradle assemble task has broken. When I run the same pipeline, it generates the apk file with version code and version name set in build.gradle file instead of the values I set in fastlane task. 
    
    In my pipeline, the fastlane task prints the command it executes:
```
    ----------------------------------------
[15:56:27]: --- Step: assembleMobileAlphaRelease ---
[15:56:27]: ----------------------------------------
[15:56:27]: $ /Users/runner/work/1/s/gradlew assembleMobileAlphaRelease -p . -Pandroid.injected.version.code=2 -Pandroid.injected.version.name=dummy -Pandroid.injected.signing.store.file=/Users/runner/work/_temp/alpha_release_key_store -Pandroid.injected.signing.store.password=*** -Pandroid.injected.signing.key.alias=AlphaSigned -Pandroid.injected.signing.key.password=***
[16:11:47]:
```

It shows that it is using the properties as specified in the fastlane task. However when I analyze the apk generated, it has the version code as 1 and version name as debug.

**Comment by ygalustov** [comment]
It's an old Gradle issue: https://issuetracker.google.com/issues/242730594.
Downgrade it back to 7.1.3 and it will start working again.

```
dependencies {
        classpath 'com.android.tools.build:gradle:7.1.3'
}
```

**Comment by abhatnagar03** [comment]
You are right, this is not a fastlane issue but a gradle issue. However, I would not agree to the solution to downgrade the gradle. Instead I tried many things and found one workaround for my project settings, sharing it here in case it helps anyone else too:

I was able to fix the same issue for my project (it has latest gradle wrapper 7.5,  gradle version 7.4.2). I tried the below settings which worked:

1. In my build.gradle file, I changed the default config to read from gradle.properties file:

```
defaultConfig {
        ......
        versionCode = rootProject.ext.get("versionCode").toString().toInt()
        versionName = rootProject.ext.get("versionName").toString()
        ......
}
```

2. In my gradle.properties file (which exists in the root directory), I defined the default values for these 2 properties:
```
versionCode=1
versionName=debug
```

3. Then run the assemble/bundle command using flags to modify these properties will generate apk/aab with required values (2, test):

` ./gradlew assembleMobileAlphaDebug -PversionCode=2 -PversionName=test`

Please note I used versionCode and versionName as property names in all places, the property name should match.
