### ISSUE TITLE
Can't get match to work with `Mac Installer Distribution` certificate.

### ISSUE THREAD

**Issue by BirjuVachhani** [fastlane/fastlane#21189]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I am trying to write a fastlane script to automate macOS deployment. I am using `match` to store my certs and provisioning profiles in a private repo.

I ran `fastlane match import --platform macos --type mac_installer_distribution` and it asked me to provider `.cer`, `.p12` and provisioning profile for it. I provided `.cer` and `.p12` files but not the profile since there is no specific option on developer.apple.com to create a provisioning profile for `Mac Installer Distribution` certificate. This succeeds without any errors.

I have following match code in my `Fastfile` and I am using `build_mac_app` action:

```ruby
platform :mac do
  desc "Publishes a new version to the App Store"
  lane :release do
    setup_ci if ENV['CI']

    # 1. Get distribution certificate
    match(
      type: "appstore",
      app_identifier: DEFAULT_APP_IDENTIFIER,
      readonly: true,
      platform: "macos",
    )

    # 2. Get installer distribution certificate
    match(
      type: "mac_installer_distribution",
      app_identifier: DEFAULT_APP_IDENTIFIER,
      readonly: true,
      platform: "macos",
      skip_provisioning_profiles: true,
    )

    ...
end
```

1. If I don't provided 2nd `match` step then it fails saying that no installer certificate was provided.
2. If I remove `skip_provisioning_profiles` from 2nd `match` step then it fails saying no provisioning profile found for installer cert.
3. If I use it as it is, it fails with following exception.

```
[16:30:00]: Generated plist file with the following values:
[16:30:00]: ▸ -----------------------------------------
[16:30:00]: ▸ {
[16:30:00]: ▸   "provisioningProfiles": {
[16:30:00]: ▸     "dev.birju.targetmate": null
[16:30:00]: ▸   },
[16:30:00]: ▸   "method": "app-store",
[16:30:00]: ▸   "signingStyle": "manual",
[16:30:00]: ▸   "installerSigningCertificate": "3rd Party Mac Developer Installer: Birju Vachhani (TQ37FM6DBD)"
[16:30:00]: ▸ }
[16:30:00]: ▸ -----------------------------------------
[16:30:00]: $ /usr/bin/xcrun /usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.212.1/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/gym_config20230410-4276-ob5usn.plist' -archivePath /Users/runner/Library/Developer/Xcode/Archives/2023-04-10/TargetMate\ 2023-04-10\ 16.26.45.xcarchive -exportPath '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/gym_output20230410-4276-wfgivm' 
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/gym_config20230410-4276-ob5usn.plist -archivePath '/Users/runner/Library/Developer/Xcode/Archives/2023-04-10/TargetMate 2023-04-10 16.26.45.xcarchive' -exportPath /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/gym_output20230410-4276-wfgivm
error: Couldn't load -exportOptionsPlist: Failed to decode "dev.birju.targetmate". Expected to decode String but found __NSCFData instead.

IDEFoundation.IDEDistributionExportOptionsError.failedToDecode("Failed to decode \"dev.birju.targetmate\". Expected to decode String but found __NSCFData instead.")

** EXPORT FAILED **
[16:30:01]: Exit status: 70
```

##### Command executed
Just running `fastlane mac release`.

### Environment

<details>
  <pre>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 13.3.1                                                     |
| Ruby                        | 3.1.4                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.40.0                                         |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.212.1/libexec/bin/fastlane |
| Host                        | macOS 13.3.1 (22E261)                                      |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby@3.1/3.1.4/lib                    |
| OpenSSL Version             | OpenSSL 3.1.0 14 Mar 2023                                  |
| Is contained                | false                                                      |
| Is homebrew                 | true                                                       |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
| Xcode Version               | 14.3                                                       |
| Swift Version               | 5.8                                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# Fixes issue: https://github.com/fastlane/fastlane/issues/21125
require 'spaceship'
Spaceship::ConnectAPI::App.const_set('ESSENTIAL_INCLUDES', 'appStoreVersions')

DEFAULT_APP_IDENTIFIER = 'dev.birju.targetmate'

default_platform(:ios)

platform :ios do
  desc "Publishes a new version to the App Store"
  lane :release do
    setup_ci if ENV['CI']

    match(
      type: "appstore",
      app_identifier: DEFAULT_APP_IDENTIFIER,
      readonly: true,
    )

    Dir.chdir '..' do
      sh 'flutter clean && flutter pub get' do |error|
        unless error.exitstatus.eql? 0
          UI.message error
          UI.user_error! 'Unable to run flutter build command'
        end
      end
    end

    # Pod install
    cocoapods(
      clean_install: true,
      podfile: "ios/Podfile",
      use_bundle_exec: false,
    )

    Dir.chdir '..' do
      sh 'flutter build ipa --release --export-method app-store' do |error|
        unless error.exitstatus.eql? 0
          UI.message error
          UI.user_error! 'Unable to run flutter build command'
        end
      end
    end

    build_ios_app(
      workspace: 'ios/Runner.xcworkspace',
      export_method: "app-store",
      clean: false,
      skip_build_archive: true,
      archive_path: "build/ios/archive/Runner.xcarchive",
    )

    app_store_connect_api_key(
      is_key_content_base64: true,
      in_house: false, # if it is enterprise or not
    )

    upload_to_app_store(
      force: true,
      run_precheck_before_submit: false,
      submit_for_review: false,
      ipa: lane_context[SharedValues::IPA_OUTPUT_PATH],
      skip_metadata: true,
      skip_screenshots: true,
    )
  end

  desc "Get certificates for local machine"
  lane :certificates do
    match(
      type: "development",
      app_identifier: DEFAULT_APP_IDENTIFIER,
      force_for_new_devices: true,
      readonly: true,
      platform: "ios",
    )

    match(
      type: "appstore",
      app_identifier: DEFAULT_APP_IDENTIFIER,
      readonly: true,
      platform: "ios",
    )
  end

  desc "Generate new certificates"
  lane :generate_new_certificates do
    match(
      type: "development",
      app_identifier: DEFAULT_APP_IDENTIFIER,
      force_for_new_devices: true,
      readonly: false,
      platform: "ios",
    )

    match(
      type: "appstore",
      app_identifier: DEFAULT_APP_IDENTIFIER,
      readonly: false,
      platform: "ios",
    )
  end
end

platform :mac do
  desc "Publishes a new version to the App Store"
  lane :release do
    setup_ci if ENV['CI']

    match(
      type: "appstore",
      app_identifier: DEFAULT_APP_IDENTIFIER,
      readonly: true,
      platform: "macos",
    )

    match(
      type: "mac_installer_distribution",
      app_identifier: DEFAULT_APP_IDENTIFIER,
      readonly: true,
      platform: "macos",
      skip_provisioning_profiles: true,
    )

    Dir.chdir '..' do
      sh 'flutter clean && flutter pub get' do |error|
        unless error.exitstatus.eql? 0
          UI.message error
          UI.user_error! 'Unable to run flutter build command'
        end
      end
    end

    # Pod install
    cocoapods(
      clean_install: true,
      podfile: "macos/Podfile",
      use_bundle_exec: false,
    )

    Dir.chdir '..' do
      sh 'flutter build macos --release' do |error|
        unless error.exitstatus.eql? 0
          UI.message error
          UI.user_error! 'Unable to run flutter build command'
        end
      end
    end

    build_mac_app(
      workspace: 'macos/Runner.xcworkspace',
      export_method: "app-store",
      clean: false,
      installer_cert_name: "3rd Party Mac Developer Installer: Birju Vachhani (TQ37FM6DBD)",
    )

    app_store_connect_api_key(
      is_key_content_base64: true,
      in_house: false, # if it is enterprise or not
    )

    upload_to_app_store(
      force: true,
      run_precheck_before_submit: false,
      submit_for_review: false,
      ipa: lane_context[SharedValues::IPA_OUTPUT_PATH],
      skip_metadata: true,
      skip_screenshots: true,
    )
  end

  desc "Get certificates for local machine"
  lane :certificates do
    match(
      type: "development",
      app_identifier: DEFAULT_APP_IDENTIFIER,
      force_for_new_devices: true,
      readonly: true,
      platform: "macos",
    )

    match(
      type: "appstore",
      app_identifier: DEFAULT_APP_IDENTIFIER,
      readonly: true,
      platform: "macos",
    )

    match(
      type: "mac_installer_distribution",
      app_identifier: DEFAULT_APP_IDENTIFIER,
      readonly: true,
      platform: "macos",
    )
  end

  desc "Generate new certificates"
  lane :generate_new_certificates do
    match(
      type: "development",
      app_identifier: DEFAULT_APP_IDENTIFIER,
      # force_for_new_devices: true,
      readonly: false,
      platform: "macos",
    )

    match(
      type: "appstore",
      app_identifier: DEFAULT_APP_IDENTIFIER,
      readonly: false,
      platform: "macos",
    )

    match(
      type: "mac_installer_distribution",
      app_identifier: DEFAULT_APP_IDENTIFIER,
      readonly: false,
      platform: "macos",
    )
  end
end

def pod_install
  Dir.chdir '../ios' do
    sh 'pod install' do |error|
      unless error.exitstatus.eql? 0
        UI.message error
        UI.user_error! 'Unable to run pod install command'
      end
    end
  end
  Dir.chdir '../macos' do
    sh 'pod install' do |error|
      unless error.exitstatus.eql? 0
        UI.message error
        UI.user_error! 'Unable to run pod install command'
      end
    end
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("dev.birju.targetmate") # The bundle identifier of your app
apple_id("hyperdesigned@gmail.com") # Your Apple Developer Portal username

itc_team_id("126214212") # App Store Connect Team ID
team_id("TQ37FM6DBD") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.212.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.6        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.7.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.99.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.3       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.6.1        |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.8.1        |
| bundler                         | 2.4.10       |
| simctl                          | 1.6.10       |
| jwt                             | 2.7.0        |
| google-cloud-env                | 1.6.0        |
| google-cloud-core               | 1.6.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.8.1        |
| google-apis-core                | 0.11.0       |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.19.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.44.0       |
| emoji_regex                     | 3.2.3        |
| set                             | 1.0.2        |
| public_suffix                   | 5.0.1        |
| addressable                     | 2.8.3        |
| multi_json                      | 1.15.0       |
| signet                          | 0.17.0       |
| os                              | 1.1.4        |
| memoist                         | 0.16.2       |
| googleauth                      | 1.5.0        |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-apis-androidpublisher_v3 | 0.38.0       |
| google-cloud-errors             | 1.3.1        |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.2        |
| aws-partitions                  | 1.743.0      |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.171.0      |
| aws-sdk-kms                     | 1.63.0       |
| aws-sdk-s3                      | 1.120.1      |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.6        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.2.0        |
| uri                             | 0.12.1       |
| openssl                         | 3.0.1        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.2        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-http                        | 0.3.0        |
| net-protocol                    | 0.1.2        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.11       |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.4        |
</details>

*generated on:* **2023-04-10**
</details>
 </pre>
</details>

**Comment by BirjuVachhani** [comment]
Found out that `--additional_cert_types mac_installer_distribution` can also be used inside the Fastfile and it fixes the issue.

**Comment by tpkowastaken** [comment]
@BirjuVachhani 
Hi, I can't get this to work. It always complains about not having the certificate even though I added the --aditional_cert_tyoes argument. Would you mind sharing the whole functional macos lane with us please?

Thank you for your time.

**Comment by BirjuVachhani** [comment]
@tpkowastaken Here's how I am using it:

For developer ID builds:
```bash
fastlane match developer_id --additional_cert_types developer_id_installer --platform macos
```

For Appstore builds:
```bash
fastlane match appstore --platform macos --additional_cert_types mac_installer_distribution
```

This will install required certificates on your system and will sync `match` repo with it.

This is how you use it in your lane:

```ruby
match(
  type: "appstore",
  app_identifier: DEFAULT_APP_IDENTIFIER,
  readonly: true,
  platform: "macos",
  additional_cert_types: ["mac_installer_distribution"],
)
```

Hope this helps!
