### ISSUE TITLE
Vulnerability in Rouge 2.0.7

### ISSUE THREAD

**Issue by dvelopmberg** [fastlane/fastlane#21192]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
The fastlane release 2.212.1 is conusming xcpretty 0.3.0 
https://github.com/fastlane/fastlane/blob/master/Gemfile.lock

xcpretty 0.3.0 is conusming rouge 2.0.7 and this version has vulnerabilities
https://ossindex.sonatype.org/vulnerability/sonatype-2021-4771?component-type=gem&component-name=rouge&utm_source=dependency-track&utm_medium=integration&utm_content=v4.5.0

I don't know what to do, because the xcpretty project is dead i think? There are no changes since 2018
and the active pull request with the update of rouge is open since end of 2022
https://github.com/xcpretty/xcpretty/pull/383

##### Command executed
Not relevant.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> Not relevant </pre>
</details>

### Environment

<details>
  <pre> Not relevant </pre>
</details>

**Comment by lolezy** [comment]
issue still valid on the latest version

**Comment by DevMobileAS** [comment]
See https://github.com/xcpretty/xcpretty/pull/383#issuecomment-1945525788
Please fix this!

**Comment by DevMobileAS** [comment]
FYI: xcpretty is now at 0.4.0 containing the needed update for rouge to fix the vulnerability.

I'm not sure what exactly I need to update within fastlane to just use the new xcpretty version, but maybe some of the existing contributors could help with this?

**Comment by revolter** [comment]
This will be fixed by #26657.
