### ISSUE TITLE
Deliver fails after updating to Xcode 14.3

### ISSUE THREAD

**Issue by MortenHN81** [fastlane/fastlane#21208]
Hi all

Deliver is failing without any error messages. I can upload fine using Xcode, but i need fastlane to work as i support more than 100 apps that i need to update. The error has happend since i updated to Xcode 14.3. Deliver just fails with no info. Does anybody know how to get some error messenges, logs or anything, have searched everywhere cannot find anything. 

**Im running fastlane: fastlane 2.212.2**

**This is the command failing:**

    deliver(
      force: true,
      skip_screenshots: true,
      skip_binary_upload: false,
      app_identifier: ENV["APP_IDENTIFIER"],
      ipa: "fastlane/ipa/" + ENV["SCHEME"] + ".ipa",
      skip_metadata: false,
    )

**Output from lane:**

fastlane
[✔] 🚀 
[09:46:54]: ----------------------------------------
[09:46:54]: --- Step: Verifying fastlane version ---
[09:46:54]: ----------------------------------------
[09:46:54]: Your fastlane version 2.212.2 matches the minimum requirement of 2.54.0  ✅
[09:46:54]: ------------------------------
[09:46:54]: --- Step: default_platform ---
[09:46:54]: ------------------------------
[09:46:54]: Welcome to fastlane! Here's what your app is set up to do:
+--------+-------------------------------------+------------------------------------------+
|                                 Available lanes to run                                  |
+--------+-------------------------------------+------------------------------------------+
| Number | Lane Name                           | Description                              |
+--------+-------------------------------------+------------------------------------------+
| 1      | ios create_and_release_all          | release new app                          |
| 2      | ios release_update_all              | release app update                       |
| 3      | ios enable_services_all             | Rewrite all release notes, metadata,     |
|        |                                     | description                              |
| 4      | ios update_all_type_of_metadata_all | Rewrite all release notes, metadata,     |
|        |                                     | description                              |
| 5      | ios copy_default_screenshots_all    | Add default screenshots to metadata      |
| 6      | ios upload_all_metadata             | Upload all metadata                      |
| 7      | ios upload_all_screenshots          | Upload all screenshots                   |
| 8      | ios send_to_review_all              | Send all apps to review                  |
| 9      | ios upload_all_app_privacy          |                                          |
| 10     | ios make_provisioning_profiles_all  | Make all provisioning profiles, and set  |
|        |                                     | them in project                          |
| 11     | ios reset_default_metadata_all      | Reset all metadata                       |
| 12     | ios add_test_devices_all            | Add xxxxxx test devices                |
| 13     | ios make_certificates_all           | Make certificates                        |
| 0      | cancel                              | No selection, exit fastlane!             |
+--------+-------------------------------------+------------------------------------------+
[09:46:54]: Which number would you like to run?
2
[09:46:57]: Running lane `ios release_update_all`. Next time you can do this by directly typing `bundle exec fastlane ios release_update_all` 🚀.
[09:46:57]: Driving the lane 'ios release_update_all' 🚀
[09:46:57]: --------------------------------
[09:46:57]: --- These ENV Files are run: ---
[09:46:57]: --------------------------------
[09:46:57]: ▸ xxxxxxx
[09:46:57]: ----------------------------------------------------------
[09:46:57]: --- Step: Switch to ios set_environment_variables lane ---
[09:46:57]: ----------------------------------------------------------
[09:46:57]: Cruising over to lane 'ios set_environment_variables' 🚖
[09:46:57]: Cruising back to lane 'ios release_update_all' 🚘
[09:46:57]: -----------------------------------------------
[09:46:57]: --- Step: Switch to ios release_update lane ---
[09:46:57]: -----------------------------------------------
[09:46:57]: Cruising over to lane 'ios release_update' 🚖
[09:46:57]: ---------------------
[09:46:57]: --- Step: deliver ---
[09:46:57]: ---------------------
[09:46:57]: Successfully loaded '/Users/xxxxxxxxxxxxxx/Documents/opgaver/xxxxxxxxxxxx/fastlane/Deliverfile' 📄

+------------------------------------------+----------------------------------------------------------------------+
|                                  Detected Values from './fastlane/Deliverfile'                                  |
+------------------------------------------+----------------------------------------------------------------------+
| metadata_path                            | fastlane/metadata/xxxxxxx                                            |
| screenshots_path                         | fastlane/metadata/xxxxxx/Screenshots                                |
| ignore_language_directory_validation     | true                                                                 |
| price_tier                               | 0                                                                    |
| copyright                                |                                                    |
| primary_category                         | EDUCATION                                                            |
| trade_representative_contact_information | {:first_name=>"", :last_name=>"",                      |
|                                          | :address_line1=>"", :address_line2=>"",                 |
|                                          | :address_line3=>"", :city_name=>"", :state=>"",              |
|                                          | :country=>"Denmark", :postal_code=>"", :phone_number=>"      |
|                                          |", :email_address=>""}                        |
| app_review_information                   | {:first_name=>"", :last_name=>"",             |
|                                          | :phone_number=>"",                                    |
|                                          | :email_address=>"", :demo_user=>"",       |
|                                          | :demo_password=>"", :notes=>"'"}                                         |
| submission_information                   | {:export_compliance_encryption_updated=>false,                       |
|                                          | :export_compliance_uses_encryption=>false,                           |
|                                          | :content_rights_contains_third_party_content=>false,                 |
|                                          | :add_id_info_uses_idfa=>false}                                       |
| automatic_release                        | true                                                                 |
| phased_release                           | false                                                                |
| app_rating_config_path                   | fastlane/itunes_rating_config.json                                   |
+------------------------------------------+----------------------------------------------------------------------+

[09:46:57]: Login to App Store Connect ()
[09:46:59]: Login successful

+--------------------------------------------------------------------+---------------------------------------------------------------------+
|                                                         deliver 2.212.2 Summary                                                          |
+--------------------------------------------------------------------+---------------------------------------------------------------------+
| force                                                              | true                                                                |
| skip_screenshots                                                   | true                                                                |
| skip_binary_upload                                                 | false                                                               |
| app_identifier                                                     | dk.xxxxxxxxx.xxxxxxx                                        |
| ipa                                                                | fastlane/ipa/xxxxxxx.ipa                                            |
| skip_metadata                                                      | true                                                                |
| app_version                                                        | 5.4.1                                                               |
| username                                                           | xxxxx                                               |
| platform                                                           | ios                                                                 |
| edit_live                                                          | false                                                               |
| use_live_version                                                   | false                                                               |
| metadata_path                                                      | fastlane/metadata/xxxxxx                                           |
| screenshots_path                                                   | fastlane/metadata/xxxxxx/Screenshots                               |
| skip_app_version_update                                            | false                                                               |
| overwrite_screenshots                                              | false                                                               |
| sync_screenshots                                                   | false                                                               |
| submit_for_review                                                  | false                                                               |
| verify_only                                                        | false                                                               |
| reject_if_possible                                                 | false                                                               |
| automatic_release                                                  | true                                                                |
| phased_release                                                     | false                                                               |
| reset_ratings                                                      | false                                                               |
| price_tier                                                         | 0                                                                   |
| app_rating_config_path                                             | fastlane/itunes_rating_config.json                                  |
| submission_information.export_compliance_encryption_updated        | false                                                               |
| submission_information.export_compliance_uses_encryption           | false                                                               |
| submission_information.content_rights_contains_third_party_content | false                                                               |
| submission_information.add_id_info_uses_idfa                       | false                                                               |
| team_id                                                            | xxxxxxxxx                                                           |
| dev_portal_team_id                                                 | xxxxxxxx                                                          |
| run_precheck_before_submit                                         | true                                                                |
| precheck_default_rule_level                                        | warn                                                                |
| copyright                                                          | xxxxxx                                                   |
| primary_category                                                   | EDUCATION                                                           |
| trade_representative_contact_information.first_name                | xx                                                              |
| trade_representative_contact_information.last_name                 | xx                                                            |
| trade_representative_contact_information.address_line1             | xxxx                                                      |
| trade_representative_contact_information.city_name                 | xxxx                                                            |
| trade_representative_contact_information.country                   | xxxxx                                                             |
| trade_representative_contact_information.postal_code               | xxxx                                                                |
| trade_representative_contact_information.phone_number              | xxxx                                                       |
| trade_representative_contact_information.email_address             | xxxxx                                                    |
| app_review_information.first_name                                  | xxx                                                              |
| app_review_information.last_name                                   | xxxx                                                  |
| app_review_information.phone_number                                | xxxx                                                    |
| app_review_information.email_address                               | xxxx                                                    |
| app_review_information.demo_user                                   | xxxx                                                       |
| app_review_information.demo_password                               | ********                                                            |
| app_review_information.notes                                       | ''                   |
| ignore_language_directory_validation                               | true                                                                |
| precheck_include_in_app_purchases                                  | true                                                                |
+--------------------------------------------------------------------+---------------------------------------------------------------------+

[09:47:00]: Making sure the latest version on App Store Connect matches '5.4.1'...
[09:47:00]: '5.4.1' is the latest version on App Store Connect
[09:47:00]: ------------------------------------------------
[09:47:00]: --- Step: Switch to ios move_env_failed lane ---
[09:47:00]: ------------------------------------------------
[09:47:00]: Cruising over to lane 'ios move_env_failed' 🚖
[09:47:00]: Cruising back to lane 'ios release_update' 🚘
[09:47:00]: ---------------------------------------------------
[09:47:00]: --- Step: Switch to ios release_update_all lane ---
[09:47:00]: ---------------------------------------------------
[09:47:00]: Cruising over to lane 'ios release_update_all' 🚖
[09:47:00]: Cruising back to lane 'ios release_update' 🚘
[09:47:00]: --------------------------
[09:47:00]: --- Step: notification ---
[09:47:00]: --------------------------

+------+------------------------------------------+-------------+
|                       fastlane summary                        |
+------+------------------------------------------+-------------+
| Step | Action                                   | Time (in s) |
+------+------------------------------------------+-------------+
| 1    | Verifying fastlane version               | 0           |
| 2    | default_platform                         | 0           |
| 3    | Switch to ios set_environment_variables  | 0           |
|      | lane                                     |             |
| 4    | Switch to ios release_update lane        | 0           |
| 💥   | deliver                                  | 3           |
| 6    | Switch to ios move_env_failed lane       | 0           |
| 7    | Switch to ios release_update_all lane    | 0           |
| 8    | notification                             | 0           |
+------+------------------------------------------+-------------+

[09:47:00]: fastlane.tools finished successfully 🎉

Hope anybody has any idear cause without any feedback, error or logs i have not been able to solved this.

Thanks
Morten

**Comment by brad-thaler** [comment]
We're having the same issue here, but using XCode 14.2 (14C18) and Fastlane 2.212.2.

We get "fastlane finished with errors" but there is no error shown. This occurs immediately after "Successfully uploaded screenshots to App Store Connect".

**Comment by brad-thaler** [comment]
UPDATE: We reverted to 2.212.1 and deliver is working again.

**Comment by Katsz** [comment]
> UPDATE: We reverted to 2.212.1 and deliver is working again.

The only change to `deliver` I can see is further adoption of `altool` pull #20738 .
You can  run `bundle exec fastlane deliver --ipa your_awesome_app.ipa --verify_only --verbose` using fastlane 2.212.2, which will hint you at what's going wrong.

**Comment by MortenHN81** [comment]
I found the issue for me, it was an try/catch that was missing a print. the real issue here was the price_tier issue, thanks to anybody that helped.
