### ISSUE TITLE
Automatic signing not working fails with There are no accounts registered with Xcode. Add your developer account to Xcode 

### ISSUE THREAD

**Issue by lmsmanish** [fastlane/fastlane#21219]
### New Issue Checklist

- [ x] Updated fastlane to the latest version
- [ x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Command executed

fastlane
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> We are using github hosted runner to build and distribute our app using fastlane. We build apps for mulitple bundle id's within same development team. We've enabled automatic provisioning in our project and change the bundle identifier at build time.
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                          |
| --------------------------- | ---------------------------------------------- |
| OS                          | 13.3.1                                         |
| Ruby                        | 3.2.2                                          |
| Bundler?                    | false                                          |
| Git                         | git version 2.37.1 (Apple Git-137.1)           |
| Installation Source         | /opt/homebrew/lib/ruby/gems/3.2.0/bin/fastlane |
| Host                        | macOS 13.3.1 (22E261)                          |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.2.2/lib            |
| OpenSSL Version             | OpenSSL 1.1.1t  7 Feb 2023                     |
| Is contained                | false                                          |
| Is homebrew                 | false                                          |
| Is installed via Fabric.app | false                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/    |
| Xcode Version               | 14.2                                           |
| Swift Version               | 5.7.2                                          |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

# before_all do |lane, options|
#   desc "Checking prerequisites for build"

#   # Docs: http://docs.fastlane.tools/actions/ensure_env_vars/#ensure_env_vars
#   ensure_env_vars(
#     env_vars: [
#     ]
#   )
# end

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do

    if is_ci
      puts "CI Environment: setup fastlane for ci"
      # Docs: http://docs.fastlane.tools/actions/setup_ci/#setup_ci
      setup_ci
    end

    # Docs: http://docs.fastlane.tools/actions/app_store_connect_api_key/#app_store_connect_api_key
    app_store_connect_api_key()

    previous_build_number = latest_testflight_build_number(
      app_identifier: ENV["BUNDLE_IDENTIFIER"]
    )
    
    current_build_number = previous_build_number + 1

    # Docs: http://docs.fastlane.tools/actions/increment_build_number/#increment_build_number
    # Enable auto increment from Xcode
    increment_build_number(
      build_number: current_build_number
    )

   #ensure_temp_keychain 'fastlane_tmp_keychain'

    sync_code_signing(
      type: 'development',
      readonly: false
    )

    # Docs: http://docs.fastlane.tools/actions/sync_code_signing/#sync_code_signing    
    sync_code_signing(
      type: 'appstore',
      readonly: false
    )

    enable_automatic_code_signing(
      path: "App.xcodeproj",
      use_automatic_signing: true,
      targets: ["App"]    
    )

    # Docs: https://docs.fastlane.tools/actions/build_app
    # Use the following ENV vars in your CI:
    # - IPA_OUTPUT_PATH
    # - DSYM_OUTPUT_PATH
    build_app(
      configuration: "Release",
      scheme: "App",
      clean: true,
      export_method: "app-store",
      workspace: "App.xcworkspace",
      xcargs: "-allowProvisioningUpdates",
      export_team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id)
    )


    # Docs: http://docs.fastlane.tools/actions/testflight/#testflight
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )

  end

  # lane :upload_metadata do
  #   upload_to_app_store(
  #     app_identifier: "com.lastmilesolutions.fastlanedemo",
  #     submit_for_review: false,
  #     force: false,
  #     ignore_language_directory_validation: true,
  #     metadata_path: "metadata",
  #     screenshots_path: "metadata/screenshots",
  #     skip_metadata: false,
  #     skip_screenshots: false,
  #     overwrite_screenshots: true,
  #     skip_binary_upload: true,
  #   )
  # end
end


# def ensure_temp_keychain(name)
#   delete_keychain(
#     name: name
#   ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
#   create_keychain(
#     name: name,
#     password: 'temppassword',
#     unlock: true,
#     timeout: false
#   )
# end

```
</details>

<details><summary>`./Appfile`</summary>

```ruby
app_identifier(ENV["BUNDLE_IDENTIFIER"]) # The bundle identifier of your app
apple_id(ENV["DELIVER_USER"]) # Your Apple email address

itc_team_id("2044256") # App Store Connect Team ID
team_id("D3DDA9RWJJ") # Developer Portal Team ID

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.212.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.5.1        |
| did_you_mean                    | 1.6.3        |
| syntax_suggest                  | 1.0.4        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.6        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.3       |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.6.3        |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.8.1        |
| simctl                          | 1.6.10       |
| google-cloud-env                | 1.6.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-storage_v1          | 0.19.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| mini_mime                       | 1.1.2        |
| google-cloud-storage            | 1.44.0       |
| emoji_regex                     | 3.2.3        |
| set                             | 1.0.3        |
| plist                           | 3.7.0        |
| public_suffix                   | 5.0.1        |
| addressable                     | 2.8.4        |
| excon                           | 0.99.0       |
| bundler                         | 2.4.12       |
| jwt                             | 2.7.0        |
| webrick                         | 1.8.1        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| signet                          | 0.17.0       |
| os                              | 1.1.4        |
| memoist                         | 0.16.2       |
| googleauth                      | 1.5.2        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.2        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| google-apis-core                | 0.11.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-apis-androidpublisher_v3 | 0.39.0       |
| google-cloud-errors             | 1.3.1        |
| google-apis-iamcredentials_v1   | 0.17.0       |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.2        |
| aws-partitions                  | 1.748.0      |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.171.0      |
| aws-sdk-kms                     | 1.63.0       |
| aws-sdk-s3                      | 1.120.1      |
| forwardable                     | 1.3.3        |
| logger                          | 1.5.3        |
| pathname                        | 0.2.1        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.6        |
| date                            | 3.3.3        |
| timeout                         | 0.3.2        |
| securerandom                    | 0.2.2        |
| uri                             | 0.12.1       |
| openssl                         | 3.1.0        |
| digest                          | 3.1.1        |
| ipaddr                          | 1.2.5        |
| resolv                          | 0.2.2        |
| time                            | 0.2.2        |
| open-uri                        | 0.3.0        |
| stringio                        | 3.0.6        |
| mutex_m                         | 0.1.2        |
| net-http                        | 0.3.2        |
| net-protocol                    | 0.2.1        |
| connection_pool                 | 2.4.0        |
| net-http-persistent             | 4.0.2        |
| patron                          | 0.13.3       |
| ostruct                         | 0.5.5        |
| english                         | 0.7.2        |
| erb                             | 4.0.2        |
| abbrev                          | 0.1.1        |
| tempfile                        | 0.1.3        |
| delegate                        | 0.3.0        |
| tmpdir                          | 0.1.3        |
| fileutils                       | 1.7.1        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.2        |
| nkf                             | 0.1.2        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.4.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.1        |
| psych                           | 5.1.0        |
</details>

*generated on:* **2023-04-20**
</details>
</details>

### Environment

+---------------+------------------------------+
|              Build environment               |
+---------------+------------------------------+
| xcode_path    | /Applications/Xcode_14.2.app |
| gym_version   | 2.212.2                      |
| export_method | app-store                    |
| sdk           | iPhoneOS16.2.sdk             |
+---------------+------------------------------+

<details>
  <pre> 
Error Logs:
error: There are no accounts registered with Xcode. Add your developer account to Xcode (in target 'App' from project 'App')

error: No profiles for 'com.xxxxx.app' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.xxxxx.app'. (in target 'App' from project 'App')

Fastlane info

![image](https://user-images.githubusercontent.com/89903992/233354476-1137bae3-6a9d-4a31-8f0f-c8c10dcecaa6.png)

 </pre>
</details>

**Comment by gaikwadmanish** [comment]
It looks like fastlane does not set the matched provisioning profile automatically. So, we manually set the provisioning profile after snycing it.

    profile_mapping = Actions.lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING]
    update_code_signing_settings(
      path: "App.xcodeproj",
      use_automatic_signing: false,
      code_sign_identity: 'iPhone Distribution',
      profile_name: profile_mapping[ENV["BUNDLE_IDENTIFIER"]],
    )

You can have a look at this issue for more details.


https://github.com/fastlane/fastlane/issues/18352
