### ISSUE TITLE
Unable to Create Screenshots Due to Missing SUPPORTED_PLATFORMS Build Setting

### ISSUE THREAD

**Issue by bartjacobs** [fastlane/fastlane#21382]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
After setting up fastlane to create screenshots with snapshot, I run into an error (exit status 70) because Xcode isn't able to find the simulator that should be used to create the screenshots. This worked fine in the past, but started giving issues a few days ago.

I think the problem can be found on this line:

```
Could not read the "SUPPORTED_PLATFORMS" build setting, assuming that the project supports iOS only.
```

This is the only difference in output compared to a working project. I have tried to resolve this issue, but the `SUPPORTED_PLATFORMS` build setting is correctly set in the project (to **iOS**). I have been able to recreate this issue with a new project using SwiftUI. I also tried Xcode 14.3, 14.3.1 and the latest Xcode 15 (Beta 3). Using the latest version of fastlane doesn't resolve the issue nor does checking out `master`.

I have spent several days trying to get to the bottom of this, but it's unclear whether this is a fastlane issue or an Xcode issue.

Note that I installed Beta 3 of Xcode 15 _after_ running into this issue (in an attempt to rule out the Xcode version).

##### Command executed
`bundle exec fastlane snapshot`

or

`bundle exec fastlane screenshots`

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>
[07:28:53]: ------------------------------
[07:28:53]: --- Step: default_platform ---
[07:28:53]: ------------------------------
[07:28:53]: Driving the lane 'ios screenshots' 🚀
[07:28:54]: ---------------------------------
[07:28:54]: --- Step: capture_screenshots ---
[07:28:54]: ---------------------------------
[07:28:54]: Successfully loaded '/Users/bartjacobs/Git/MyApp/fastlane/Snapfile' 📄

+----------------------------+----------------------------------------------------------------------------------------------------------+
|                                              Detected Values from './fastlane/Snapfile'                                               |
+----------------------------+----------------------------------------------------------------------------------------------------------+
| devices                    | ["iPhone 8 Plus", "iPhone 14 Plus", "iPad Pro (12.9-inch) (2nd generation)", "iPad Pro (12.9-inch) (6th  |
|                            | generation)"]                                                                                            |
| languages                  | ["en-US"]                                                                                                |
| scheme                     | MyAppUITests                                                                                             |
| clear_previous_screenshots | true                                                                                                     |
+----------------------------+----------------------------------------------------------------------------------------------------------+

[07:28:55]: Resolving Swift Package Manager dependencies...
[07:28:55]: $ xcodebuild -resolvePackageDependencies -scheme MyAppUITests -project ./MyApp.xcodeproj
[07:28:55]: ▸ 2023-07-08 07:28:55.411 xcodebuild[6362:103246] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
[07:28:55]: ▸ Command line invocation:
[07:28:55]: ▸     /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -scheme MyAppUITests -project ./MyApp.xcodeproj
[07:28:55]: ▸ User defaults from command line:
[07:28:55]: ▸     IDEPackageSupportUseBuiltinSCM = YES
[07:28:55]: ▸ Resolve Package Graph
[07:28:55]: ▸ Resolved source packages:
[07:28:55]: ▸   Swinject: https://github.com/Swinject/Swinject.git @ 2.8.3
[07:28:55]: ▸ resolved source packages: Swinject
[07:28:55]: $ xcodebuild -showBuildSettings -scheme MyAppUITests -project ./MyApp.xcodeproj
2023-07-08 07:28:55.973 xcodebuild[6363:103309] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
[07:28:56]: Could not read the "SUPPORTED_PLATFORMS" build setting, assuming that the project supports iOS only.

+--------------------------------------+----------------------------------------------------------------------------------------------------------+
|                                                          Summary for snapshot 2.212.0                                                           |
+--------------------------------------+----------------------------------------------------------------------------------------------------------+
| scheme                               | MyAppUITests                                                                                             |
| project                              | ./MyApp.xcodeproj                                                                                        |
| devices                              | ["iPhone 8 Plus", "iPhone 14 Plus", "iPad Pro (12.9-inch) (2nd generation)", "iPad Pro (12.9-inch) (6th  |
|                                      | generation)"]                                                                                            |
| languages                            | ["en-US"]                                                                                                |
| launch_arguments                     | [""]                                                                                                     |
| output_directory                     | /Users/bartjacobs/Git/MyApp/fastlane/screenshots                                                         |
| output_simulator_logs                | false                                                                                                    |
| skip_open_summary                    | false                                                                                                    |
| skip_helper_version_check            | false                                                                                                    |
| clear_previous_screenshots           | true                                                                                                     |
| reinstall_app                        | false                                                                                                    |
| erase_simulator                      | false                                                                                                    |
| headless                             | true                                                                                                     |
| override_status_bar                  | false                                                                                                    |
| localize_simulator                   | false                                                                                                    |
| app_identifier                       | com.mycompany.MyApp                                                                                      |
| buildlog_path                        | ~/Library/Logs/snapshot                                                                                  |
| clean                                | false                                                                                                    |
| number_of_retries                    | 1                                                                                                        |
| stop_after_first_error               | false                                                                                                    |
| result_bundle                        | false                                                                                                    |
| concurrent_simulators                | true                                                                                                     |
| disable_slide_to_type                | false                                                                                                    |
| skip_package_dependencies_resolution | false                                                                                                    |
| disable_package_automatic_updates    | false                                                                                                    |
| xcodebuild_formatter                 | xcpretty                                                                                                 |
| use_system_scm                       | false                                                                                                    |
| xcode_path                           | /Applications/Xcode.app                                                                                  |
+--------------------------------------+----------------------------------------------------------------------------------------------------------+

[07:28:57]: Clearing previously generated screenshots
[07:28:57]: Building and running project - this might take some time...
[07:28:59]: Patching simulators '/Users/bartjacobs/Library/Preferences/com.apple.iphonesimulator.plist' to scale to 100%
[07:29:12]: Running snapshot on: iPhone 8 Plus, iPad Pro (12.9-inch) (2nd generation)
[07:29:12]: $ set -o pipefail && xcodebuild -scheme MyAppUITests -project ./MyApp.xcodeproj -derivedDataPath /var/folders/ss/p1hbf16x5mz93r0j5qg6b8hw0000gn/T/snapshot_derived20230708-6331-l3w91u -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=16.4' -destination 'platform=iOS Simulator,name=iPad Pro (12.9-inch) (2nd generation),OS=16.4' FASTLANE_SNAPSHOT=YES FASTLANE_LANGUAGE=en-US build test | tee /Users/bartjacobs/Library/Logs/snapshot/App-MyAppUITests.log | xcpretty
[07:29:12]: ▸ Loading...
[07:29:12]: ▸ 2023-07-08 07:29:12.867 xcodebuild[6674:104598] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
[07:29:14]: ▸ 2023-07-08 07:29:14.769 xcodebuild[6674:104598] Writing error result bundle to /var/folders/ss/p1hbf16x5mz93r0j5qg6b8hw0000gn/T/ResultBundle_2023-08-07_07-29-0014.xcresult
[07:29:15]: ▸ xcodebuild: error: Unable to find a destination matching the provided destination specifier:
[07:29:15]: ▸ 		{ platform:iOS Simulator, OS:16.4, name:iPhone 8 Plus }
2023-07-08 07:29:12.867 xcodebuild[6674:104598] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
2023-07-08 07:29:14.769 xcodebuild[6674:104598] Writing error result bundle to /var/folders/ss/p1hbf16x5mz93r0j5qg6b8hw0000gn/T/ResultBundle_2023-08-07_07-29-0014.xcresult
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:iOS Simulator, OS:16.4, name:iPhone 8 Plus }
[07:29:15]: Exit status: 70
[07:29:15]: Tests failed while running on: iPhone 8 Plus, iPad Pro (12.9-inch) (2nd generation)
[07:29:15]: For more detail about the test failures, check the logs here:
[07:29:15]: /Users/bartjacobs/Library/Logs/snapshot/App-MyAppUITests.log
[07:29:15]:
[07:29:15]: You can also find the test result data here:
[07:29:15]: /var/folders/ss/p1hbf16x5mz93r0j5qg6b8hw0000gn/T/snapshot_derived20230708-6331-l3w91u/Logs/Test
[07:29:15]:
[07:29:15]: You can find the incomplete screenshots here:
[07:29:15]: /Users/bartjacobs/Library/Caches/tools.fastlane/screenshots
[07:29:15]: /Users/bartjacobs/Git/MyApp/fastlane/screenshots
[07:29:15]: Caught error... 70
[07:29:16]: Patching simulators '/Users/bartjacobs/Library/Preferences/com.apple.iphonesimulator.plist' to scale to 100%
</pre>
</details>

### Environment
<details>
  <pre> 
🚫 fastlane environment 🚫

### Stack

| Key                         | Value                                                    |
| --------------------------- | -------------------------------------------------------- |
| OS                          | 13.4.1                                                   |
| Ruby                        | 2.6.5                                                    |
| Bundler?                    | true                                                     |
| Git                         | git version 2.39.2 (Apple Git-143)                       |
| Installation Source         | ~/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bin/fastlane |
| Host                        | macOS 13.4.1 (22F82)                                     |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.5/lib                              |
| OpenSSL Version             | OpenSSL 1.1.1q  5 Jul 2022                               |
| Is contained                | false                                                    |
| Is homebrew                 | false                                                    |
| Is installed via Fabric.app | false                                                    |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/              |
| Xcode Version               | 14.3.1                                                   |
| Swift Version               | 5.8.1                                                    |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(scheme: "MyAppUITests")
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.mycompany.MyApp") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple Developer Portal username


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.212.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| bundler                         | 2.3.20       |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.6        |
| public_suffix                   | 5.0.1        |
| addressable                     | 2.8.4        |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.783.0      |
| aws-sigv4                       | 1.6.0        |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.176.1      |
| aws-sdk-kms                     | 1.69.0       |
| aws-sdk-s3                      | 1.127.0      |
| babosa                          | 1.0.4        |
| claide                          | 1.1.0        |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.5        |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.100.0      |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.0.0        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.3       |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.7        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.7.1        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.6.0        |
| httpclient                      | 2.8.3        |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| webrick                         | 1.8.1        |
| google-apis-core                | 0.11.0       |
| google-apis-androidpublisher_v3 | 0.45.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.19.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.1        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.44.0       |
| json                            | 2.6.3        |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.7.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.10       |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
</details>

*generated on:* **2023-07-08**
</pre>
</details>

**Comment by bartjacobs** [comment]
I tried using an **.xcconfig** file to set the `SUPPORTED_PLATFORMS` build setting, but that didn't work either. I'm still seeing the following warning when generating screenshots through fastlane, which I believe is the root cause of the issue.

```
Could not read the "SUPPORTED_PLATFORMS" build setting, assuming that the project supports iOS only.
```

**Comment by bartjacobs** [comment]
I was able to resolve the issue by setting the **Executable** of the scheme to the app. It's unclear why this was set to **None** when the scheme was created.

**Comment by drewolbrich** [comment]
> I was able to resolve the issue by setting the **Executable** of the scheme to the app. It's unclear why this was set to **None** when the scheme was created.

Thank you for posting this. This information saved me a lot of time.

**Comment by dimic-milos** [comment]
This was also causing issues with executions of **UITestScheme** on a GitHub Runner. Couldn't make it past 
`xcodebuild: error: Unable to find a destination matching the provided destination specifier: { platform:iOS Simulator, id: }` until I set the **buildForRunning** on the UITestScheme. After that, everything worked . Thanks for the hint @bartjacobs 

<img width="828" height="395" alt="Image" src="https://github.com/user-attachments/assets/814ade56-d809-4de9-8e01-bcd68a52d293" />
