### ISSUE TITLE
GitHub Actions freezes on "Run Script" when building iOS

### ISSUE THREAD

**Issue by herman-the-worm** [fastlane/fastlane#21411]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
fastlane successfully builds locally but on GitHub Actions is always freezes on "Run Script" step in iOS build. I changed timeout for the workflow anywhere from 40 to 120 minutes and it always stuck

INFO [2023-07-20 04:53:23.25]: ▸     Run script build phase '[firebase_crashlytics] Crashlytics Upload Symbols' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
INFO [2023-07-20 04:53:23.28]: ▸ Running script '[CP] Check Pods Manifest.lock'
INFO [2023-07-20 04:53:23.45]: ▸ Running script 'Run Script'
Error: The operation was canceled.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
platform :ios do
  lane :closed_beta do
    debug
    keychain_name = TEMP_KEYCHAIN_USER
    keychain_password = TEMP_KEYCHAIN_PASSWORD
    ensure_temp_keychain(keychain_name, keychain_password)
    api_key = app_store_connect_api_key(
        key_id: 
        issuer_id: 
        key_content:
        duration: 1200, # optional (maximum 1200)
        in_house: false,
      )
    cocoapods( clean_install: true )
    match(
        type: 'appstore',
        app_identifier: 
        git_basic_authorization: Base64.strict_encode64
        api_key: api_key,
        keychain_name: keychain_name,
        keychain_password: keychain_password,
        readonly: true
      )
    build_app(
        workspace: "Runner.xcworkspace",
        scheme: "dev",
        clean: true,
        export_options: {
            provisioningProfiles: {
              secret => secret,
            },
            signingStyle: "manual"
          },
    )
    pilot(api_key: api_key,skip_waiting_for_build_processing: true,)
    delete_temp_keychain(keychain_name)
  end
end</pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by salemaljebaly** [comment]
@herman-the-worm 
maybe need to reinstall dependencies in iOS
`gem install cocoa-pods
  pod install`

another thing you locally the keychain setup automatically thats make process easy for you in local environment but in CI
you need to do that manually thats make another problems
so use `setup_ci` when prepared lane used Setup the keychain and match to work with CI
https://docs.fastlane.tools/actions/setup_ci/

**Comment by calfonso-zuhe** [comment]
@herman-the-worm I am having the same issue,  the fastlane script is hanging when building the app. The github actions log is stalled at : 

        Running script 'Run Script'

Did you figure out what to do?

**Comment by calfonso-zuhe** [comment]
In case someone reads this post, the issue I had was caused from the build script stuck waiting for a password to open the keychain (The github action log will not tell you that, you have to run it locally). The solution was to add commands to open and unlock the keychain. 

In the Fastfile, try any or all of the following: 
    unlock_keychain(
      path: "~/Library/Keychains/build.keychain",
      password: <keychain password>
    )

    # disable the keychain autolock
    sh "security set-keychain-settings -u ~/Library/Keychains/build.keychain"

    # Allow codesign to access the "cert" key without prompting
    sh "security set-key-partition-list -S apple-tool:,apple: -s -k <keychain password> ~/Library/Keychains/build.keychain"

**Comment by herman-the-worm** [comment]
> In case someone reads this post, the issue I had was caused from the build script stuck waiting for a password to open the keychain (The github action log will not tell you that, you have to run it locally). The solution was to add commands to open and unlock the keychain.
> 
> In the Fastfile, try any or all of the following:
> 
> ```
> unlock_keychain(
>   path: "~/Library/Keychains/build.keychain",
>   password: <keychain password>
> )
> 
> # disable the keychain autolock
> sh "security set-keychain-settings -u ~/Library/Keychains/build.keychain"
> 
> # Allow codesign to access the "cert" key without prompting
> sh "security set-key-partition-list -S apple-tool:,apple: -s -k <keychain password> ~/Library/Keychains/build.keychain"
> ```

This is only applicable if you are building locally but not via GitHub actions

**Comment by JIV-DLS** [comment]
@herman-the-worm did you find a way to solve your problem?

**Comment by JIV-DLS** [comment]
> In case someone reads this post, the issue I had was caused from the build script stuck waiting for a password to open the keychain (The github action log will not tell you that, you have to run it locally). The solution was to add commands to open and unlock the keychain.
> 
> In the Fastfile, try any or all of the following:
> 
> ```
> unlock_keychain(
>   path: "~/Library/Keychains/build.keychain",
>   password: <keychain password>
> )
> 
> # disable the keychain autolock
> sh "security set-keychain-settings -u ~/Library/Keychains/build.keychain"
> 
> # Allow codesign to access the "cert" key without prompting
> sh "security set-key-partition-list -S apple-tool:,apple: -s -k <keychain password> ~/Library/Keychains/build.keychain"
> ```

what is the keychain password I a GitHub runner, is there a default one?

**Comment by ztefanie** [comment]
@JIV-DLS If working with fastlane you can just use the `setup_circle_ci` command.
https://docs.fastlane.tools/actions/setup_circle_ci/

**Comment by tkreuder** [comment]
If you do not use circle_ci in your setup, but e.g. github actions together with fastlane, you can use: [setup_ci](https://docs.fastlane.tools/actions/setup_ci/ ). 

Internally it just creates a keychain entry, which can also be achieved by:

```
bundle exec fastlane run create_keychain name:SOME_KEYCHAIN_NAME password:SOME_KEYCHAIN_PASSWORD default_keychain:true unlock:true timeout:3600
```
OR 
```
 create_keychain(
    name: SOME_KEYCHAIN_NAME,
    password: SOME_KEYCHAIN_PASSWORD,
    default_keychain: true,
    unlock: true,
    timeout: 3600,
  
  )
```

Thanks a lot for @herman-the-worm for bringing this up and @calfonso-zuhe for pointing me to that direction 🙏
