### ISSUE TITLE
Submit an iOS app for review with deliver fails with: There is another reviewSubmissions with id xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx still in progress.

### ISSUE THREAD

**Issue by hborders** [fastlane/fastlane#21482]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
  - I'm still on `2.210.1`
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I had an existing iOS version pending developer release (`15.9.1`), but we discovered a bug, so I cancelled `15.9.1` and then submitted iOS version `15.9.2` for review with `deliver`. `deliver` failed with:
```
ERROR [2023-08-24 16:01:26.85]: Resource state invalid - There is another reviewSubmissions with id xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx still in progress.
```

I tried running the same submission again, but I got a different error:
```
ERROR [2023-08-24 16:11:18.18]: appStoreVersions with id 'yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy' is not in valid state. - This resource cannot be reviewed, please check associated errors to see why.
The request cannot be fulfilled because of the state of another resource. - Version is not ready to be submitted yet, please try again later.
```

My app has an iOS app and a tvOS app in the store. We also have a macOS App in a `1.0 Prepare for Submission` state. 

I was able to submit successfully through the App Store Connect Web UI, though App Store Connect was showing me a lot of server error pages while I used the UI, so maybe this was some kind of App Store Connect bug?

##### Command executed
```
bundle exec fastlane --verbose SUBMIT_TESTFLIGHT_BUILD_FOR_REVIEW \
  build_number:"$app_build_number" \
  app_version:"$app_version" \
  skip_metadata:"$skip_metadata" \
  skip_screenshots:"$skip_screenshots" \
  overwrite_screenshots:"$overwrite_screenshots" \
  submit_for_review:"$submit_for_review"
```

This is the lane that has my deliver call. app_store_api_key is a function that pulls my app store API key out of the CI environment.
```
lane :SUBMIT_TESTFLIGHT_BUILD_FOR_REVIEW do |options|
  api_key = app_store_api_key
  deliver(
    api_key: api_key,
    skip_binary_upload: true,
    app_version: options[:app_version],
    build_number: options[:build_number],
    skip_metadata: options[:skip_metadata],
    skip_screenshots: options[:skip_screenshots],
    overwrite_screenshots: options[:overwrite_screenshots],
    submit_for_review: options[:submit_for_review], 
    phased_release: true,
    precheck_include_in_app_purchases: false
  )
end
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <summary>first attempt</summary>
  <pre>
+------------------------+----------------------+
| Detected Values from './fastlane/Deliverfile' |
+------------------------+----------------------+
!!!!! REDACTED !!!!!!
| automatic_release      | false                |
| phased_release         | true                 |
| force                  | true                 |
| submission_information |                      |
+------------------------+----------------------+

INFO [2023-08-24 15:57:27.74]: Creating authorization token for App Store Connect API

+--------------------------------------------------------------------+--------------------------+
|                                    deliver 2.210.1 Summary                                    |
+--------------------------------------------------------------------+--------------------------+
| api_key                                                            | ********                 |
| skip_binary_upload                                                 | true                     |
| app_version                                                        | 15.9.2                   |
| build_number                                                       | 1592                     |
| skip_metadata                                                      | false                    |
| skip_screenshots                                                   | true                     |
| overwrite_screenshots                                              | false                    |
| submit_for_review                                                  | true                     |
| phased_release                                                     | true                     |
| precheck_include_in_app_purchases                                  | false                    |
| screenshots_path                                                   | ./fastlane/screenshots   |
| metadata_path                                                      | ./fastlane/metadata      |
!!!!! REDACTED !!!!!!
| platform                                                           | ios                      |
| edit_live                                                          | false                    |
| use_live_version                                                   | false                    |
| skip_app_version_update                                            | false                    |
| force                                                              | true                     |
| sync_screenshots                                                   | false                    |
| verify_only                                                        | false                    |
| reject_if_possible                                                 | false                    |
| automatic_release                                                  | false                    |
| reset_ratings                                                      | false                    |
| submission_information.add_id_info_limits_tracking                 | true                     |
| submission_information.add_id_info_tracks_action                   | true                     |
| submission_information.add_id_info_tracks_install                  | false                    |
| submission_information.add_id_info_serves_ads                      | true                     |
| submission_information.add_id_info_uses_idfa                       | true                     |
| submission_information.content_rights_contains_third_party_content | true                     |
| submission_information.content_rights_has_rights                   | true                     |
!!!!! REDACTED !!!!!!
| run_precheck_before_submit                                         | true                     |
| precheck_default_rule_level                                        | warn                     |
| ignore_language_directory_validation                               | false                    |
+--------------------------------------------------------------------+--------------------------+

INFO [2023-08-24 15:57:42.24]: Making sure the latest version on App Store Connect matches '15.9.2'...
INFO [2023-08-24 15:57:45.60]: Successfully set the version to '15.9.2'
INFO [2023-08-24 15:57:45.61]: Loading './fastlane/metadata/cs/description.txt'...
!!!!! REDACTED !!!!!
INFO [2023-08-24 15:57:45.82]: Loading './fastlane/metadata/review_information/notes.txt'...
WARN [2023-08-24 15:57:54.05]: Will begin uploading metadata for '15.9.2' on App Store Connect
INFO [2023-08-24 15:57:54.05]: Uploading metadata to App Store Connect for version
INFO [2023-08-24 15:57:57.48]: Uploading metadata to App Store Connect for localized version 'cs'
!!!!! REDACTED !!!!!
INFO [2023-08-24 15:58:10.92]: Uploading metadata to App Store Connect for localized info 'ja'
Timeout received! Retrying after 3 seconds (remaining: 5)...
INFO [2023-08-24 15:58:10.96]: Uploading metadata to App Store Connect for localized info 'ko'
INFO [2023-08-24 15:58:11.23]: Uploading metadata to App Store Connect for localized info 'id'
INFO [2023-08-24 15:58:11.26]: Uploading metadata to App Store Connect for localized info 'zh-Hant'
INFO [2023-08-24 15:58:11.38]: Uploading metadata to App Store Connect for localized info 'vi'
ERROR [2023-08-24 15:58:12.83]: Category 'MZGenre.Photography' from iTunesConnect has been deprecated. Please replace with 'PHOTO_AND_VIDEO'
ERROR [2023-08-24 15:58:12.83]: Category 'MZGenre.SocialNetworking' from iTunesConnect has been deprecated. Please replace with 'SOCIAL_NETWORKING'
ERROR [2023-08-24 15:58:12.83]: You can find more info at https://docs.fastlane.tools/actions/deliver/#reference
INFO [2023-08-24 15:58:14.47]: Uploading app review information to App Store Connect
INFO [2023-08-24 15:58:15.22]: Running precheck before submitting to review, if you'd like to disable this check you can set run_precheck_before_submit to false
INFO [2023-08-24 15:58:15.22]: Making sure we pass precheck   ‍♀️    before we submit

+--------------------------+--------------------------+
|            Summary for precheck 2.210.1             |
+--------------------------+--------------------------+
| default_rule_level       | warn                     |
| include_in_app_purchases | false                    |
!!!!! REDACTED !!!!!
| platform                 | ios                      |
| use_live                 | false                    |
+--------------------------+--------------------------+
INFO [2023-08-24 15:58:15.23]: Creating authorization token for App Store Connect API
INFO [2023-08-24 15:58:15.23]: Checking app for precheck rule violations
INFO [2023-08-24 15:58:55.91]: ✅  Passed: No negative  sentiment
INFO [2023-08-24 15:58:55.92]: ✅  Passed: No placeholder text
!!!!! REDACTED !!!!!
WARN [2023-08-24 15:58:55.94]:     Failed: No mentioning  competitors-> mentioning other platforms, like Android or Blackberry
INFO [2023-08-24 15:58:55.95]: ✅  Passed: No future functionality promises
INFO [2023-08-24 15:58:55.96]: ✅  Passed: No words indicating test content
INFO [2023-08-24 15:58:56.22]: ✅  Passed: No curse words
INFO [2023-08-24 15:58:56.22]: ✅  Passed: No words indicating your IAP is free
DEBUG [2023-08-24 15:58:56.22]: custom_text excluded because no data was passed to it e.g.: custom_text(data: <data here>)
DEBUG [2023-08-24 15:58:56.23]:     CopyrightDateRule didn't find words "2023"
WARN [2023-08-24 15:58:56.23]:     Failed: Incorrect, or missing copyright date-> using a copyright date that is any different from this current year, or missing a date
WARN [2023-08-24 15:59:20.59]:     Failed: No broken urls-> unreachable URLs in app metadata
+--------------------------------+-------------------------+
|                    Potential problems                    |
+--------------------------------+-------------------------+
| Field                          | Failure reason          |
+--------------------------------+-------------------------+
|  tv privacy policy: (da)      | found: google           |
|  tv privacy policy: (zh-Hans) | found: google           |
|  tv privacy policy: (el)      | found: google           |
|  tv privacy policy: (ms)      | found: google           |
|  tv privacy policy: (ja)      | found: google           |
|  tv privacy policy: (pt-BR)   | found: google           |
|  tv privacy policy: (es-MX)   | found: google           |
|  tv privacy policy: (ko)      | found: google           |
|  tv privacy policy: (vi)      | found: google           |
|  tv privacy policy: (tr)      | found: google           |
|  tv privacy policy: (es-ES)   | found: google           |
|  tv privacy policy: (fr-FR)   | found: google           |
|  tv privacy policy: (it)      | found: google           |
|  tv privacy policy: (no)      | found: google           |
|  tv privacy policy: (zh-Hant) | found: google           |
|  tv privacy policy: (sv)      | found: google           |
|  tv privacy policy: (nl-NL)   | found: google           |
|  tv privacy policy: (th)      | found: google           |
|  tv privacy policy: (pt-PT)   | found: google           |
|  tv privacy policy: (id)      | found: google           |
|  tv privacy policy: (de-DE)   | found: google           |
|  tv privacy policy: (ru)      | found: google           |
|  tv privacy policy: (fi)      | found: google           |
| copyright                      | missing: 2023           |
!!!!! REDACTED !!!!!
+--------------------------------+-------------------------+
WARN [2023-08-24 15:59:20.60]: precheck   ‍♀️     found one or more potential metadata problems, but this won't prevent fastlane from completing   
INFO [2023-08-24 15:59:22.20]: Selecting existing build-number: 1592
INFO [2023-08-24 15:59:23.63]: Selecting build 15.9.2 (1592)...
INFO [2023-08-24 15:59:31.03]: Successfully selected build
DEBUG [2023-08-24 15:59:31.45]: Updating app store version for IDFA status of 'true'
DEBUG [2023-08-24 15:59:31.71]: Updated app store version for IDFA status of 'true'
DEBUG [2023-08-24 15:59:31.71]: Updating IDFA declaration
DEBUG [2023-08-24 15:59:32.23]: Updated IDFA declaration
INFO [2023-08-24 15:59:32.23]: Successfully updated IDFA declarations on App Store Connect
DEBUG [2023-08-24 15:59:32.23]: Updating contents rights declaration on App Store Connect
INFO [2023-08-24 15:59:35.39]: Successfully updated contents rights declaration on App Store Connect
Timeout received! Retrying after 3 seconds (remaining: 5)...
Timeout received! Retrying after 3 seconds (remaining: 4)...
WARN [2023-08-24 16:01:26.85]: Lane Context:
INFO [2023-08-24 16:01:26.85]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios SUBMIT_TESTFLIGHT_BUILD_FOR_REVIEW", :MY_METADATA=>[]}
ERROR [2023-08-24 16:01:26.85]: Resource state invalid - There is another reviewSubmissions with id xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx still in progress.
</pre>
</details>

<details>
  <summary>second attempt</summary>
  <pre>
+------------------------+----------------------+
!!!!! REDACTED !!!!!!
| automatic_release      | false                |
| phased_release         | true                 |
| force                  | true                 |
| submission_information |                      |
+------------------------+----------------------+

INFO [2023-08-24 16:09:03.98]: Creating authorization token for App Store Connect API

+--------------------------------------------------------------------+--------------------------+
|                                    deliver 2.210.1 Summary                                    |
+--------------------------------------------------------------------+--------------------------+
| api_key                                                            | ********                 |
| skip_binary_upload                                                 | true                     |
| app_version                                                        | 15.9.2                   |
| build_number                                                       | 1592                     |
| skip_metadata                                                      | false                    |
| skip_screenshots                                                   | true                     |
| overwrite_screenshots                                              | false                    |
| submit_for_review                                                  | true                     |
| phased_release                                                     | true                     |
| precheck_include_in_app_purchases                                  | false                    |
| screenshots_path                                                   | ./fastlane/screenshots   |
| metadata_path                                                      | ./fastlane/metadata      |
!!!!! REDACTED !!!!!!
| platform                                                           | ios                      |
| edit_live                                                          | false                    |
| use_live_version                                                   | false                    |
| skip_app_version_update                                            | false                    |
| force                                                              | true                     |
| sync_screenshots                                                   | false                    |
| verify_only                                                        | false                    |
| reject_if_possible                                                 | false                    |
| automatic_release                                                  | false                    |
| reset_ratings                                                      | false                    |
| submission_information.add_id_info_limits_tracking                 | true                     |
| submission_information.add_id_info_tracks_action                   | true                     |
| submission_information.add_id_info_tracks_install                  | false                    |
| submission_information.add_id_info_serves_ads                      | true                     |
| submission_information.add_id_info_uses_idfa                       | true                     |
| submission_information.content_rights_contains_third_party_content | true                     |
| submission_information.content_rights_has_rights                   | true                     |
!!!!! REDACTED !!!!!!
| run_precheck_before_submit                                         | true                     |
| precheck_default_rule_level                                        | warn                     |
| ignore_language_directory_validation                               | false                    |
+--------------------------------------------------------------------+--------------------------+

INFO [2023-08-24 16:09:13.47]: Making sure the latest version on App Store Connect matches '15.9.2'...
INFO [2023-08-24 16:09:13.84]: '15.9.2' is the latest version on App Store Connect
INFO [2023-08-24 16:09:13.85]: Loading './fastlane/metadata/cs/description.txt'...
!!!!! REDACTED !!!!!!
INFO [2023-08-24 16:09:14.04]: Loading './fastlane/metadata/review_information/notes.txt'...
WARN [2023-08-24 16:09:18.71]: Will begin uploading metadata for '15.9.2' on App Store Connect
INFO [2023-08-24 16:09:18.71]: Uploading metadata to App Store Connect for version
INFO [2023-08-24 16:09:22.18]: Uploading metadata to App Store Connect for localized version 'cs'
!!!!! REDACTED !!!!!!
INFO [2023-08-24 16:09:26.26]: Uploading metadata to App Store Connect for localized info 'pt-PT'
ERROR [2023-08-24 16:09:27.48]: Category 'MZGenre.Photography' from iTunesConnect has been deprecated. Please replace with 'PHOTO_AND_VIDEO'
ERROR [2023-08-24 16:09:27.48]: Category 'MZGenre.SocialNetworking' from iTunesConnect has been deprecated. Please replace with 'SOCIAL_NETWORKING'
ERROR [2023-08-24 16:09:27.48]: You can find more info at https://docs.fastlane.tools/actions/deliver/#reference
INFO [2023-08-24 16:09:29.12]: Uploading app review information to App Store Connect
INFO [2023-08-24 16:09:31.07]: Running precheck before submitting to review, if you'd like to disable this check you can set run_precheck_before_submit to false
INFO [2023-08-24 16:09:31.07]: Making sure we pass precheck   ‍♀️    before we submit

+--------------------------+--------------------------+
|            Summary for precheck 2.210.1             |
+--------------------------+--------------------------+
| default_rule_level       | warn                     |
| include_in_app_purchases | false                    |
!!!!! REDACTED !!!!!!
| platform                 | ios                      |
| use_live                 | false                    |
+--------------------------+--------------------------+

INFO [2023-08-24 16:09:31.08]: Creating authorization token for App Store Connect API
INFO [2023-08-24 16:09:31.08]: Checking app for precheck rule violations
INFO [2023-08-24 16:09:59.03]: ✅  Passed: No negative  sentiment
INFO [2023-08-24 16:09:59.04]: ✅  Passed: No placeholder text
!!!!! REDACTED !!!!!!
WARN [2023-08-24 16:09:59.06]:     Failed: No mentioning  competitors-> mentioning other platforms, like Android or Blackberry
INFO [2023-08-24 16:09:59.07]: ✅  Passed: No future functionality promises
INFO [2023-08-24 16:09:59.08]: ✅  Passed: No words indicating test content
INFO [2023-08-24 16:09:59.34]: ✅  Passed: No curse words
INFO [2023-08-24 16:09:59.34]: ✅  Passed: No words indicating your IAP is free
DEBUG [2023-08-24 16:09:59.34]: custom_text excluded because no data was passed to it e.g.: custom_text(data: <data here>)
DEBUG [2023-08-24 16:09:59.34]:     CopyrightDateRule didn't find words "2023"
WARN [2023-08-24 16:09:59.34]:     Failed: Incorrect, or missing copyright date-> using a copyright date that is any different from this current year, or missing a date
INFO [2023-08-24 16:10:26.25]: ✅  Passed: No broken urls
+--------------------------------+----------------+
|               Potential problems                |
+--------------------------------+----------------+
| Field                          | Failure reason |
+--------------------------------+----------------+
|  tv privacy policy: (da)      | found: google  |
|  tv privacy policy: (zh-Hans) | found: google  |
|  tv privacy policy: (el)      | found: google  |
|  tv privacy policy: (ms)      | found: google  |
|  tv privacy policy: (ja)      | found: google  |
|  tv privacy policy: (pt-BR)   | found: google  |
|  tv privacy policy: (es-MX)   | found: google  |
|  tv privacy policy: (ko)      | found: google  |
|  tv privacy policy: (vi)      | found: google  |
|  tv privacy policy: (tr)      | found: google  |
|  tv privacy policy: (es-ES)   | found: google  |
|  tv privacy policy: (fr-FR)   | found: google  |
|  tv privacy policy: (it)      | found: google  |
|  tv privacy policy: (no)      | found: google  |
|  tv privacy policy: (zh-Hant) | found: google  |
|  tv privacy policy: (sv)      | found: google  |
|  tv privacy policy: (nl-NL)   | found: google  |
|  tv privacy policy: (th)      | found: google  |
|  tv privacy policy: (pt-PT)   | found: google  |
|  tv privacy policy: (id)      | found: google  |
|  tv privacy policy: (de-DE)   | found: google  |
|  tv privacy policy: (ru)      | found: google  |
|  tv privacy policy: (fi)      | found: google  |
| copyright                      | missing: 2023  |
+--------------------------------+----------------+
WARN [2023-08-24 16:10:26.26]: precheck   ‍♀️     found one or more potential metadata problems, but this won't prevent fastlane from completing   
INFO [2023-08-24 16:10:27.05]: Selecting existing build-number: 1592
INFO [2023-08-24 16:10:28.25]: Selecting build 15.9.2 (1592)...
INFO [2023-08-24 16:10:30.43]: Successfully selected build
DEBUG [2023-08-24 16:10:30.71]: Updating app store version for IDFA status of 'true'
DEBUG [2023-08-24 16:10:31.96]: Updated app store version for IDFA status of 'true'
DEBUG [2023-08-24 16:10:31.96]: Updating IDFA declaration
DEBUG [2023-08-24 16:10:32.50]: Updated IDFA declaration
INFO [2023-08-24 16:10:32.50]: Successfully updated IDFA declarations on App Store Connect
DEBUG [2023-08-24 16:10:32.50]: Updating contents rights declaration on App Store Connect
INFO [2023-08-24 16:10:42.69]: Successfully updated contents rights declaration on App Store Connect
WARN [2023-08-24 16:11:18.18]: Lane Context:
INFO [2023-08-24 16:11:18.18]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios SUBMIT_TESTFLIGHT_BUILD_FOR_REVIEW", :MY_METADATA=>[]}
ERROR [2023-08-24 16:11:18.18]: appStoreVersions with id 'yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy' is not in valid state. - This resource cannot be reviewed, please check associated errors to see why.
The request cannot be fulfilled because of the state of another resource. - Version is not ready to be submitted yet, please try again later.
  </pre>
</details>

### Fastfile

I can't include my whole `Fastfile`, but I included the associated lane where I call `deliver` above

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.210.1 | 💥 Check failed |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status  |
| ----------------------------------------- | ------- | -------------- |
| fastlane-plugin-firebase_app_distribution | 0.3.7   | 💥 Check failed |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| error_highlight                           | 0.3.0        |
| did_you_mean                              | 1.6.1        |
| bundler                                   | 2.3.9        |
| pathname                                  | 0.2.0        |
| rake                                      | 13.0.6       |
| rexml                                     | 3.2.5        |
| CFPropertyList                            | 3.0.5        |
| concurrent-ruby                           | 1.1.10       |
| i18n                                      | 1.12.0       |
| minitest                                  | 5.16.3       |
| tzinfo                                    | 2.0.5        |
| zeitwerk                                  | 2.6.1        |
| activesupport                             | 6.1.7        |
| public_suffix                             | 4.0.7        |
| addressable                               | 2.8.1        |
| httpclient                                | 2.8.3        |
| json                                      | 2.6.2        |
| algoliasearch                             | 1.27.5       |
| artifactory                               | 3.0.15       |
| atomos                                    | 0.1.3        |
| aws-eventstream                           | 1.2.0        |
| aws-partitions                            | 1.644.0      |
| aws-sigv4                                 | 1.5.2        |
| jmespath                                  | 1.6.1        |
| aws-sdk-core                              | 3.159.0      |
| aws-sdk-kms                               | 1.58.0       |
| aws-sdk-s3                                | 1.114.0      |
| babosa                                    | 1.0.4        |
| claide                                    | 1.1.0        |
| fuzzy_match                               | 2.0.4        |
| nap                                       | 1.1.0        |
| netrc                                     | 0.11.0       |
| ffi                                       | 1.15.5       |
| ethon                                     | 0.15.0       |
| typhoeus                                  | 1.4.0        |
| cocoapods-core                            | 1.11.3       |
| cocoapods-deintegrate                     | 1.0.5        |
| cocoapods-downloader                      | 1.6.3        |
| cocoapods-plugins                         | 1.0.0        |
| cocoapods-search                          | 1.0.1        |
| cocoapods-trunk                           | 1.6.0        |
| cocoapods-try                             | 1.2.0        |
| colored2                                  | 3.1.2        |
| escape                                    | 0.0.4        |
| fourflusher                               | 2.3.1        |
| gh_inspector                              | 1.1.3        |
| molinillo                                 | 0.8.0        |
| ruby-macho                                | 2.5.1        |
| nanaimo                                   | 0.3.0        |
| xcodeproj                                 | 1.22.0       |
| cocoapods                                 | 1.11.3       |
| colored                                   | 1.2          |
| highline                                  | 2.0.3        |
| commander                                 | 4.6.0        |
| declarative                               | 0.0.20       |
| digest-crc                                | 0.6.4        |
| unf_ext                                   | 0.0.8.2      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| dotenv                                    | 2.8.1        |
| emoji_regex                               | 3.2.3        |
| excon                                     | 0.93.0       |
| faraday-em_http                           | 1.0.0        |
| faraday-em_synchrony                      | 1.0.0        |
| faraday-excon                             | 1.1.0        |
| faraday-httpclient                        | 1.0.1        |
| multipart-post                            | 2.0.0        |
| faraday-multipart                         | 1.0.4        |
| faraday-net_http                          | 1.0.1        |
| faraday-net_http_persistent               | 1.2.0        |
| faraday-patron                            | 1.0.0        |
| faraday-rack                              | 1.0.0        |
| faraday-retry                             | 1.0.3        |
| ruby2_keywords                            | 0.0.5        |
| faraday                                   | 1.10.2       |
| http-cookie                               | 1.0.5        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.2.0        |
| fastimage                                 | 2.2.6        |
| jwt                                       | 2.5.0        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.4        |
| signet                                    | 0.17.0       |
| googleauth                                | 1.2.0        |
| mini_mime                                 | 1.1.2        |
| trailblazer-option                        | 0.1.2        |
| uber                                      | 0.1.0        |
| representable                             | 3.2.0        |
| retriable                                 | 3.1.2        |
| webrick                                   | 1.7.0        |
| google-apis-core                          | 0.9.0        |
| google-apis-androidpublisher_v3           | 0.29.0       |
| google-apis-playcustomapp_v1              | 0.11.0       |
| google-apis-iamcredentials_v1             | 0.15.0       |
| google-apis-storage_v1                    | 0.19.0       |
| google-cloud-env                          | 1.6.0        |
| google-cloud-errors                       | 1.3.0        |
| google-cloud-core                         | 1.6.0        |
| google-cloud-storage                      | 1.43.0       |
| mini_magick                               | 4.11.0       |
| naturally                                 | 2.2.1        |
| optparse                                  | 0.1.1        |
| plist                                     | 3.6.0        |
| rubyzip                                   | 2.3.2        |
| security                                  | 0.1.3        |
| simctl                                    | 1.6.8        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.8.0        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| word_wrap                                 | 1.0.0        |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.1        |
| fastlane-plugin-firebase_app_distribution | 0.3.7        |
| xcode-install                             | 2.8.1        |
</details>

**Comment by hborders** [comment]
I just submitted an app successfully with `deliver` using the same `Fastfile` and `fastlane` command above, so I think this was an App Store Connect issue, and not a `fastlane` issue.

**Comment by scottasoutherland** [comment]
I wonder if they are A/B testing something or slowly rolling it out, because we just saw the same issue, and the web UI had a slightly different flow for pressing the submit button now.

**Comment by hborders** [comment]
This happened to me again, and I re-ran deliver 5 minutes later and it succeeded. 🤷‍♂️

**Comment by bvirlet** [comment]
Happens to me today, repetitively on one of our apps (the other one succeeds).

**Comment by scottasoutherland** [comment]
Yep. We have 3 apps, 2 of which fail in this way every single time, one of which seems to work. So far I haven't figured out what the difference is.

**Comment by jemersondox** [comment]
I had one app work today and the other did not. A pattern I've noticed is when there is a newer version that's been uploaded, but is not the one we are submitting. For example, I'm submitting `2.0.0`, but we also have a build uploaded under `2.1.0`. Does that match what others are seeing?

**Comment by hborders** [comment]
> For example, I'm submitting 2.0.0, but we also have a build uploaded under 2.1.0. Does that match what others are seeing?

I haven't noticed this state yet, but I'll look for it the next time I get this error. I got this error on my most recent release, but a retry fixed it.
