### ISSUE TITLE
Issue with Fastlane's screenshots.html on iPhone 14 and iPhone 15 using Xcode 15

### ISSUE THREAD

**Issue by isandeepj** [fastlane/fastlane#21551]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm experiencing an issue when trying to generate screenshots for the iPhone 14 using `snapshot`. The process completes, but the screenshots aren't visible in the `screenshots.html` file. This issue doesn't occur when I use the iPhone 13.

##### Command executed
`bundle exec fastlane snapshot --output_simulator_logs`

##### Complete output when running fastlane, including the stack trace and command used
```
...
[15:59:19]: ▸ All tests
[15:59:19]: ▸ Test Suite EastMeetEastUITests.xctest started
[15:59:19]: ▸ EastMeetEastUITests
[16:00:07]: ▸     ✓ testLogin (47.625 seconds)
[16:00:49]: ▸     ✓ testLogout (41.808 seconds)
[16:00:49]: ▸ 	 Executed 2 tests, with 0 failures (0 unexpected) in 89.433 (89.449) seconds
[16:00:49]: ▸ 
[16:00:49]: ▸ 2023-10-05 16:00:49.471 xcodebuild[62875:506790] [MT] IDETestOperationsObserverDebug: 118.105 elapsed -- Testing started completed.
[16:00:49]: ▸ 2023-10-05 16:00:49.472 xcodebuild[62875:506790] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
[16:00:49]: ▸ 2023-10-05 16:00:49.472 xcodebuild[62875:506790] [MT] IDETestOperationsObserverDebug: 118.105 sec, +118.105 sec -- end
[16:00:49]: ▸ Test Succeeded
[16:00:53]: Copying '/Users/yudizsolution/Documents/MyCurrentProject/EME/SourceCode/eme-ios/screenshots/en-US/iPhone 14 Pro-01-1-RootLogin.png'...
[16:00:53]: Copying '/Users/yudizsolution/Documents/MyCurrentProject/EME/SourceCode/eme-ios/screenshots/en-US/iPhone 14 Pro-02-EmailLogin.png'...
[16:00:53]: Copying '/Users/yudizsolution/Documents/MyCurrentProject/EME/SourceCode/eme-ios/screenshots/en-US/iPhone 14 Pro-03-0-Search.png'...
[16:00:53]: Copying '/Users/yudizsolution/Documents/MyCurrentProject/EME/SourceCode/eme-ios/screenshots/en-US/iPhone 14 Pro-03-1-1-Search-Message.png'...
[16:00:53]: Copying '/Users/yudizsolution/Documents/MyCurrentProject/EME/SourceCode/eme-ios/screenshots/en-US/iPhone 14 Pro-03-2-1-SearchProfile.png'...
[16:00:53]: Copying '/Users/yudizsolution/Documents/MyCurrentProject/EME/SourceCode/eme-ios/screenshots/en-US/iPhone 14 Pro-03-2-2-SearchProfile-Message-1.png'...

+-----------------------+
|   snapshot results    |
+---------------+-------+
| Device        | en-US |
+---------------+-------+
| iPhone 14 Pro |  💚   |
+---------------+-------+

[16:00:53]: Generating HTML Report
[16:00:53]: Successfully created HTML file with an overview of all the screenshots: '/Users/yudizsolution/Documents/MyCurrentProject/EME/SourceCode/eme-ios/screenshots/screenshots.html'
```

<details>
  <pre>System and Software Details:

Machine: Apple M1
macOS Version: 13.5.2
Fastlane Version: 2.216.0
Xcode Version: 15
Description:
While conducting tests with Xcode 15 on an Apple M1 machine running macOS 13.5.2 and using Fastlane version 2.216.0, I observed that on the iPhone 14 and iPhone 15, the tests pass and screenshots are successfully captured. However, the preview is absent when trying to view the images via screenshots.html.

Contrastingly, when executing the same tests and process on the iPhone 13, everything functions correctly, and the preview in screenshots.html showcases the screenshots without any issues.

 </pre>
</details>

### Environment

<details>
  <pre> [✔] 🚀 
[16:27:44]: Generating fastlane environment output, this might take a few seconds...
swift-driver version: 1.87.1 <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                                                     |
| --------------------------- | ----------------------------------------------------------------------------------------- |
| OS                          | 13.5.2                                                                                    |
| Ruby                        | 3.1.1                                                                                     |
| Bundler?                    | true                                                                                      |
| Git                         | git version 2.39.3 (Apple Git-145)                                                        |
| Installation Source         | ~/Documents/MyCurrentProject/EME/SourceCode/eme-ios/vendor/bundle/ruby/3.1.0/bin/fastlane |
| Host                        | macOS 13.5.2 (22G91)                                                                      |
| Ruby Lib Dir                | ~/.rbenv/versions/3.1.1/lib                                                               |
| OpenSSL Version             | OpenSSL 3.1.2 1 Aug 2023                                                                  |
| Is contained                | false                                                                                     |
| Is homebrew                 | false                                                                                     |
| Is installed via Fabric.app | false                                                                                     |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                                               |
| Xcode Version               | 15.0                                                                                      |
| Swift Version               | 5.9                                                                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.211.0"
default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci # Setup circle_ci auth
  end
 

  desc "Add a device to the AppStoreConnect developer portal"
  lane :add_device do
    puts "New Device Name:"
    value_name = STDIN.gets.chomp
    puts "New Device Name Selected: #{value_name}"

    puts "UDID:"
    value_udid = STDIN.gets.chomp
    puts "New Device UDID: #{value_udid}"

    register_devices(
      devices: {
        value_name => value_udid
      }
    )
  end
 

  after_all do |lane, options|
    clean_build_artifacts # Delete the local dSYM files
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.216.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.7.4   | ✅ Up-To-Date  |
| fastlane-plugin-versioning                | 0.5.2   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| error_highlight                           | 0.3.0        |
| did_you_mean                              | 1.6.1        |
| bundler                                   | 2.3.11       |
| pathname                                  | 0.2.0        |
| rake                                      | 13.0.6       |
| rexml                                     | 3.2.6        |
| CFPropertyList                            | 3.0.6        |
| concurrent-ruby                           | 1.2.2        |
| i18n                                      | 1.14.1       |
| minitest                                  | 5.20.0       |
| tzinfo                                    | 2.0.6        |
| activesupport                             | 7.0.8        |
| public_suffix                             | 4.0.7        |
| addressable                               | 2.8.5        |
| httpclient                                | 2.8.3        |
| json                                      | 2.6.3        |
| algoliasearch                             | 1.27.5       |
| artifactory                               | 3.0.15       |
| atomos                                    | 0.1.3        |
| aws-eventstream                           | 1.2.0        |
| aws-partitions                            | 1.832.0      |
| aws-sigv4                                 | 1.6.0        |
| jmespath                                  | 1.6.2        |
| aws-sdk-core                              | 3.185.0      |
| aws-sdk-kms                               | 1.72.0       |
| aws-sdk-s3                                | 1.136.0      |
| babosa                                    | 1.0.4        |
| claide                                    | 1.1.0        |
| fuzzy_match                               | 2.0.4        |
| nap                                       | 1.1.0        |
| netrc                                     | 0.11.0       |
| ffi                                       | 1.16.3       |
| ethon                                     | 0.16.0       |
| typhoeus                                  | 1.4.0        |
| cocoapods-core                            | 1.13.0       |
| cocoapods-deintegrate                     | 1.0.5        |
| cocoapods-downloader                      | 1.6.3        |
| cocoapods-plugins                         | 1.0.0        |
| cocoapods-search                          | 1.0.1        |
| cocoapods-trunk                           | 1.6.0        |
| cocoapods-try                             | 1.2.0        |
| colored2                                  | 3.1.2        |
| escape                                    | 0.0.4        |
| fourflusher                               | 2.3.1        |
| gh_inspector                              | 1.1.3        |
| molinillo                                 | 0.8.0        |
| ruby-macho                                | 2.5.1        |
| nanaimo                                   | 0.3.0        |
| xcodeproj                                 | 1.23.0       |
| cocoapods                                 | 1.13.0       |
| cocoapods-check                           | 1.1.0        |
| colored                                   | 1.2          |
| highline                                  | 2.0.3        |
| commander                                 | 4.6.0        |
| declarative                               | 0.0.20       |
| digest-crc                                | 0.6.5        |
| unf_ext                                   | 0.0.8.2      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| dotenv                                    | 2.8.1        |
| emoji_regex                               | 3.2.3        |
| excon                                     | 0.104.0      |
| faraday-em_http                           | 1.0.0        |
| faraday-em_synchrony                      | 1.0.0        |
| faraday-excon                             | 1.1.0        |
| faraday-httpclient                        | 1.0.1        |
| multipart-post                            | 2.3.0        |
| faraday-multipart                         | 1.0.4        |
| faraday-net_http                          | 1.0.1        |
| faraday-net_http_persistent               | 1.2.0        |
| faraday-patron                            | 1.0.0        |
| faraday-rack                              | 1.0.0        |
| faraday-retry                             | 1.0.3        |
| ruby2_keywords                            | 0.0.5        |
| faraday                                   | 1.10.3       |
| http-cookie                               | 1.0.5        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.2.0        |
| fastimage                                 | 2.2.7        |
| jwt                                       | 2.7.1        |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.4        |
| signet                                    | 0.18.0       |
| googleauth                                | 1.8.1        |
| mini_mime                                 | 1.1.5        |
| trailblazer-option                        | 0.1.2        |
| uber                                      | 0.1.0        |
| representable                             | 3.2.0        |
| retriable                                 | 3.1.2        |
| webrick                                   | 1.8.1        |
| google-apis-core                          | 0.11.1       |
| google-apis-androidpublisher_v3           | 0.50.0       |
| google-apis-playcustomapp_v1              | 0.13.0       |
| google-apis-iamcredentials_v1             | 0.17.0       |
| google-apis-storage_v1                    | 0.19.0       |
| google-cloud-env                          | 1.6.0        |
| google-cloud-errors                       | 1.3.1        |
| google-cloud-core                         | 1.6.0        |
| google-cloud-storage                      | 1.44.0       |
| mini_magick                               | 4.12.0       |
| naturally                                 | 2.2.1        |
| optparse                                  | 0.1.1        |
| plist                                     | 3.7.0        |
| rubyzip                                   | 2.3.2        |
| security                                  | 0.1.3        |
| simctl                                    | 1.6.10       |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 2.5.0        |
| terminal-table                            | 3.0.2        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| word_wrap                                 | 1.0.0        |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.1        |
| google-apis-firebaseappdistribution_v1    | 0.3.0        |
| fastlane-plugin-firebase_app_distribution | 0.7.4        |
| fastlane-plugin-versioning                | 0.5.2        |
</details>

*generated on:* **2023-10-05**
</details>
[16:27:50]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[16:27:50]: 🙄  Wow, that's a lot of markdown text... should fastlane put it into your clipboard, so you can easily paste it on GitHub? (y/n)
y
[16:28:14]: Successfully copied markdown into your clipboard 🎨
[16:28:14]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅
 </pre>
</details>

**Comment by getaaron** [comment]
Closed via https://github.com/fastlane/fastlane/pull/21554

**Comment by isandeepj** [comment]
@getaaron Can you please release a new version with fixes?
