### ISSUE TITLE
Archiving fails only with fastlane gym, if the project is using new Swift macros.

### ISSUE THREAD

**Issue by enoktate** [fastlane/fastlane#21582]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Archiving the project fails only if I'm using fastlane gym.
So far I've tried with Xcode 15.0 - 15.0.1 (RC) - 15.1 (Beta). Also tried with another Macbook to see if the problem is with my local environment.
If I use Xcode directly to archive the project everything works as expected. 
If I use command-line and run the same xcodebuild command from fastlane gym logs, it also succeeds. 
But when I run fastlane gym either from my own lane or directly from terminal it fails with Exit status: 65. And log says this;
```
"<unknown>:0: warning: compiler plugin not loaded: '\/Applications\/Xcode.app\/Contents\/Developer\/Platforms\/WatchOS.platform\/Developer\/usr\/bin\/swift-plugin-server; failed to initialize\n\/Users\/name\/Desktop\/Projects\/ProjName\/WatchWidgetsExtension\/WidgetName\/WidgetEntryView.swift:60:1: error: external macro implementation type 'PreviewsMacros.Common' could not be found for macro 'Preview(_:as:widget:timeline:)
``` 

---
To make sure it is possible to replicate the problem I've created a test project with the targets:
- iOS App
- Independent watchOS app
- watchOS Widget extension

When I try to run fastlane gym in this new empty project, I got Exit status: 65 again. With a similar error in log:
```
{
  "kind": "finished",
  "name": "compile",
  "pid": 80495,
  "output": "<unknown>:0: warning: compiler plugin not loaded: '\/Applications\/Xcode.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Developer\/usr\/bin\/swift-plugin-server; failed to initialize\n\/Users\/name\/Desktop\/OpenSource\/FastTestProject\/FastTestProject\/FastTestProject\/ContentView.swift:22:1: error: external macro implementation type 'PreviewsMacros.SwiftUIView' could not be found for macro 'Preview(_:body:)'\n#Preview {\n^\nSwiftUI.Preview:2:41: note: 'Preview(_:body:)' declared here\n@freestanding(declaration) public macro Preview(_ name: String? = nil, body: @escaping @MainActor () -> View) = #externalMacro(module: \"PreviewsMacros\", type: \"SwiftUIView\")\n                                        ^\n",
  "process": {
    "real_pid": 80495
  },
  "exit-status": 1
}
``` 

##### Command executed
❌ `fastlane gym`
✅ `$ set -o pipefail && xcodebuild -scheme FastTestProject -project ./FastTestProject.xcodeproj -destination 'generic/platform=iOS' -archivePath /Users/name/Library/Developer/Xcode/Archives/2023-10-18/FastTestProject\ 2023-10-18\ 14.26.58.xcarchive archive | tee /Users/name/Library/Logs/gym/FastTestProject-FastTestProject.log | xcpretty`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅ (Got this from new empty test project directory mentioned above.)</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 14.0                                        |
| Ruby                        | 2.7.5                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.39.3 (Apple Git-145)          |
| Installation Source         | /usr/local/lib/ruby/gems/2.7.0/bin/fastlane |
| Host                        | macOS 14.0 (23A339)                         |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.7/2.7.5/lib        |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 15.0                                        |
| Swift Version               | 5.9                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.216.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.6.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| faraday_middleware              | 1.2.0        |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.7.1        |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| terminal-notifier               | 2.0.0        |
| terminal-table                  | 3.0.2        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| uri                             | 0.12.1       |
| public_suffix                   | 5.0.3        |
| addressable                     | 2.8.5        |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.6.0        |
| aws-partitions                  | 1.832.0      |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.185.0      |
| aws-sdk-kms                     | 1.72.0       |
| aws-sdk-s3                      | 1.136.0      |
| bundler                         | 2.4.10       |
| rexml                           | 3.2.6        |
| CFPropertyList                  | 3.0.6        |
| excon                           | 0.104.0      |
| ruby2_keywords                  | 0.0.5        |
| faraday-retry                   | 1.0.3        |
| faraday-rack                    | 1.0.0        |
| faraday-patron                  | 1.0.0        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-net_http                | 1.0.1        |
| multipart-post                  | 2.3.0        |
| faraday-multipart               | 1.0.4        |
| faraday-httpclient              | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.10.3       |
| fastimage                       | 2.2.7        |
| webrick                         | 1.8.1        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| signet                          | 0.18.0       |
| os                              | 1.1.4        |
| googleauth                      | 1.8.1        |
| mini_mime                       | 1.1.5        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.2        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| google-apis-core                | 0.11.1       |
| google-apis-androidpublisher_v3 | 0.50.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.5        |
| google-apis-storage_v1          | 0.19.0       |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-cloud-errors             | 1.3.1        |
| google-cloud-env                | 1.6.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.44.0       |
| json                            | 2.6.3        |
| mini_magick                     | 4.12.0       |
| plist                           | 3.7.0        |
| simctl                          | 1.6.10       |
| unicode-display_width           | 2.5.0        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.1.0        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.23.0       |
| forwardable                     | 1.3.3        |
| logger                          | 1.5.3        |
| cgi                             | 0.3.6        |
| date                            | 3.3.3        |
| timeout                         | 0.3.2        |
| stringio                        | 3.0.5        |
| openssl                         | 3.1.0        |
| ipaddr                          | 1.2.5        |
| zlib                            | 3.0.0        |
| mutex_m                         | 0.1.2        |
| connection_pool                 | 2.4.0        |
| net-http-persistent             | 4.0.2        |
| patron                          | 0.13.3       |
| ostruct                         | 0.5.5        |
| strscan                         | 3.0.6        |
| io-console                      | 0.6.0        |
| delegate                        | 0.3.0        |
| fileutils                       | 1.7.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.2        |
| yaml                            | 0.2.1        |
| psych                           | 5.1.0        |
</details>

*generated on:* **2023-10-18**
</details> </pre>
</details>

**Comment by mollyIV** [comment]
Hey @enoktate 👋 

Thanks for reporting the issue. Do you mind attaching a test project you created to help us reproduce the issue? 🙏

**Comment by enoktate** [comment]
Hey @mollyIV, thanks for looking into this. Sure, here is the project I mentioned in the issue.
Just changing the team in signing and running `fastlane gym` replicates the issue for me and my colleague.
[FastTestProject.zip](https://github.com/fastlane/fastlane/files/13040209/FastTestProject.zip)

**Comment by miletliyusuf** [comment]
```
rosetta error: Failed to open libRosettaRuntime
 760
{
  "kind": "finished",
  "name": "compile",
  "pid": 6745,
  "output": "\/Users\/******.swift:49:1: error: external macro implementation type 'PreviewsMacros.SwiftUIView' could not be found for macro 'Preview(_:body:)'\n#Preview(\"****\") {\n^\nSwiftUI.Preview:2:41: note: 'Preview(_:body:)' declared here\n@freestanding(declaration) public macro Preview(_ name: String? = nil, body: @escaping @MainActor () -> View) = #externalMacro(module: \"PreviewsMacros\", type: \"SwiftUIView\")\n                                        ^\n",
  "process": {
    "real_pid": 6745
  },
  "exit-status": 1
}
```
We're also having the same problem with above error. Is there any solution to that, yet ?

**Comment by patrickniepel** [comment]
We're also facing the same issues. In our case, the pipelines at least succeed after a couple of retries though.

**Comment by piotr-dudek** [comment]
I was getting the same error.

In my case it was ruby using x86_64 instead of arm64 architecture that was causing the problem.
It was confusing because the terminal itself was using arm64, but commands run from a ruby script were using x86_64.

I didn’t investigate it further, I just reinstalled ruby, rbenv and brew. I’m guessing the old brew installation might have something to do with it.

You can try to run the `arch` command from a ruby script to see what architecture will be used.

**Comment by bbolchis** [comment]
> I was getting the same error.
> 
> In my case it was ruby using x86_64 instead of arm64 architecture that was causing the problem. It was confusing because the terminal itself was using arm64, but commands run from a ruby script were using x86_64.
> 
> I didn’t investigate it further, I just reinstalled ruby, rbenv and brew. I’m guessing the old brew installation might have something to do with it.
> 
> You can try to run the `arch` command from a ruby script to see what architecture will be used.

This helped me. After prepending the fastlane command with `arch -arm64 bundle exec fastlane...`, it worked. The right fix might be to re-install brew, rbenv and one ruby version, but i will do that next time i have issues with ruby & fastlane.

**Comment by enoktate** [comment]
> I was getting the same error.
> 
> In my case it was ruby using x86_64 instead of arm64 architecture that was causing the problem. It was confusing because the terminal itself was using arm64, but commands run from a ruby script were using x86_64.
> 
> I didn’t investigate it further, I just reinstalled ruby, rbenv and brew. I’m guessing the old brew installation might have something to do with it.
> 
> You can try to run the `arch` command from a ruby script to see what architecture will be used.

Thank you, @piotr-dudek. I reinstalled Brew and rbenv. Previously, I was using Ruby 2.7.5; this time, I've installed 3.2.2. I tried this on two Macs with M1 chips, and Fastlane is working again.

**Comment by houtzager** [comment]
Thanks everyone for the tip that it has to do with the architecture Fastlane is executed from. 🙏 

Our problem was the following: Our build servers (M1 Mac Minis) are Jenkins nodes. Because these nodes ran on Java 11, our shell scripts in our Jenkins jobs were executed over the i386 (x86_64) architecture. Java 11, at least the version we used, runs on Intel only. Installing openjdk 17 over brew resolved the issue. 

More about Java & M1 macs can be found here: https://stackoverflow.com/questions/69497067/java-sdk-reporting-wrong-architecture-on-mac-m1

**Comment by havebeenfitz** [comment]
In my case the same error was caused by Intel `gitlab-runner` executable on the arm machine. Accidentally upgraded from a wrong url. Upgrading gitlab-runner from `sudo curl -o /usr/local/bin/gitlab-runner "https://s3.dualstack.us-east-1.amazonaws.com/gitlab-runner-downloads/latest/binaries/gitlab-runner-darwin-arm64"` solved it.

Previos comment with SO post helped to track down the issue with the Activity monitor 👍
