### ISSUE TITLE
match encryption is outdated and doesn't guarantee it detects invalid passwords. Causes flaky test.

### ISSUE THREAD

**Issue by lacostej** [fastlane/fastlane#21663]
I've seen this fail twice already on master.

E.g. https://app.circleci.com/pipelines/github/fastlane/fastlane/5764/workflows/bec22718-cc50-4a05-9952-1615d1d76389/jobs/92676

```
 1) Match Match::Encryption::OpenSSL raises an exception if invalid password is passed
     Failure/Error:
       expect do
         @e.decrypt_files
       end.to raise_error("Invalid password passed via 'MATCH_PASSWORD'")

       expected Exception with "Invalid password passed via 'MATCH_PASSWORD'" but nothing was raised
     # ./match/spec/encryption/openssl_spec.rb:33:in `block (3 levels) in <top (required)>'
     # ./.bundle/ruby/2.6.0/gems/webmock-3.12.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

Finished in 2 minutes 5.9 seconds (files took 3.34 seconds to load)
7267 examples, 1 failure, 329 pending

Failed examples:

rspec ./match/spec/encryption/openssl_spec.rb:27 # Match Match::Encryption::OpenSSL raises an exception if invalid password is passed
```

Investigating...

**Comment by lacostej** [comment]
Failed again in https://ci.appveyor.com/project/KrauseFx/fastlane/builds/48636131 as part of #21672

**Comment by lacostej** [comment]
Just saw this fail during the last stable release.

I have a WIP branch to reproduce the issue, which can be isolated to that very test.

see https://github.com/lacostej/fastlane/pull/new/fix/investigate_openssl_issue

Run `DEBUG=y bundle exec rspec match/spec/encryption/openssl_spec.rb`

It opens the interactive prompt when the test is about to fail.

<img width="1427" alt="image" src="https://github.com/fastlane/fastlane/assets/24282/1c5d25f6-8531-4926-9a1e-6a388f69f10f">

Not yet sure why.

**Comment by lacostej** [comment]
I’ve found something. It is related to the salt and the password length. For passwords smaller than 8, some given salts will 100% cause decryption to be garbage.

For our 7 letters wrong password, I’ve run the test 100000 times and it generated about 800 salts that break the decryption. The same salts do not break with a different password.

**Comment by lacostej** [comment]
```ruby
require 'openssl'
require 'securerandom'
require 'base64'

class Encryption
	attr_accessor :algorithm

	def initialize
		self.algorithm = 'aes-256-cbc'
	end

	def encrypt(data, password, salt)
		cipher = ::OpenSSL::Cipher::Cipher.new(self.algorithm)
		cipher.encrypt

		cipher.pkcs5_keyivgen(password, salt, 1, "MD5")
		encrypted_data = cipher.update(data)
		encrypted_data << cipher.final
	end
	def decrypt(encrypted_data, password, salt)
		cipher = OpenSSL::Cipher::Cipher.new(self.algorithm)
		cipher.decrypt
		cipher.pkcs5_keyivgen(password, salt, 1, "MD5")
		data = cipher.update(encrypted_data)
		data << cipher.final
	end
end


def run_test0(data)
	password='2"QAHg@v(Qp{=*n^'
	wrong_password="#{password}x"

	salt = SecureRandom.random_bytes(8)
	# test with a specific known broken salt with the given small wrong password
	#salt = [247, 107, 154, 246, 0, 151, 25, 194].pack("C*")

	e = Encryption.new
	encrypted_data = e.encrypt(data, password, salt)

	# uncomment to verify that decryption works
	# decrypted_data = e.decrypt(encrypted_data, password, salt)
	# raise "Wrong data" unless decrypted_data == data

	begin
		decrypted_data = e.decrypt(encrypted_data, wrong_password, salt)
		raise "ERROR: salt #{salt.unpack("C*")}"
	rescue OpenSSL::Cipher::CipherError => e
		# expected "bad decrypt"
		raise "ERROR: #{e} salt #{salt.unpack("C*")}" unless e.to_s == "bad decrypt"
	end
end

text='a text file with multiple lines'
DATA = 10.times.map{|i| text}.join("\n")

RUNS=2000

puts "Running test 0"
RUNS.times do |i|
	begin
		run_test0(DATA)	
	rescue => e
		puts "#{i}: #{e}"
	end
end
```

The password length doesn't matter. This code reproduces the problem, and it fails around 400 times per 100000 runs.

**Comment by lacostej** [comment]
Here’s an incomplete [proposed migration](https://gist.github.com/lacostej/cc33868553e0d57f27681dc887865caa) to our current encryption mechanics. I’ve asked feedback from openssl team to see if the security makes sense.

Anyone else has some feedback?

**Comment by lacostej** [comment]
One thing is that the documentation contains some hints on how to manually decrypt files, which wouldn't work in the new implementation. Is it an important feature to preserve?

https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/docs/sync_code_signing.md#manual-decrypt

**Comment by triplef** [comment]
FYI I got an error `wrong final block length` after updating my certificates using fastlane 2.220.0 but then using that repo with 2.219.0 on our CI. Updating fastlane on the CI fixed this for me. I am guessing this was caused by this change, so I just wanted to leave this here in case anyone else is running into this.

**Comment by kahest** [comment]
This is probably related to ^: https://github.com/fastlane/fastlane/issues/21973

**Comment by airmikec** [comment]
_### **_Azure DevOps API Key Issues for deploying to Apple_**_
To get this to successfully work on Azure DevOps Pipeline with an API Key. I ran into so many problems and tried everything I could find and this finally worked.  Azure DevOps says you need use the base64 key.  Well if you open up the .p8 and copy the base64 encoded string in there, that isn't what they want.  They literally want you to copy all of the contenxt in the .p8 file to a base64 string. Don't modify the .p8 file.  I found the solution at the follow source, and once you get the data.b64 file open it and copy the base64 string in that file.  In the following article is discusses how to do this for Windows, Mac, and Ubuntu.

https://github.com/fastlane/fastlane/issues/21531#issuecomment-1873633417
