### ISSUE TITLE
Deliver fails to create a new app version on App Store Connect

### ISSUE THREAD

**Issue by ArthurAlvarez** [fastlane/fastlane#21705]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Deliver fails to create a new app version on App Store Connect

##### Command executed

```ruby
lane :submit_review do
  deliver(
    submit_for_review: true,
    automatic_release: false,
    force: true, # Skip HTMl report verification
    skip_metadata: true,
    skip_screenshots: true,
    skip_binary_upload: true,
    run_precheck_before_submit: false,
    submission_information: { export_compliance_uses_encryption: false,
                              add_id_info_uses_idfa: false }
  )
end
```

##### Complete output when running fastlane, including the stack trace and command used
```
[17:42:54]: Cannot find edit app store version... Retrying after 10 seconds (remaining: 4)
[17:43:06]: Cannot find edit app store version... Retrying after 10 seconds (remaining: 3)
[17:43:17]: Cannot find edit app store version... Retrying after 10 seconds (remaining: 2)
[17:43:27]: Cannot find edit app store version... Retrying after 10 seconds (remaining: 1)
[17:43:38]: Cannot find edit app store version... Retrying after 10 seconds (remaining: 0)

```
and fails with

> [17:43:48]: Cannot update languages - could not find an editable version for 'IOS'

<details>
Trying to upload a new version of an app to App Store Connect, Deliver fails when it tries to upload metadata because it didn't create a new app version successfully on App Store Connect.
</details>

### Environment

Fastlane 2.217.0

**Comment by yosi-dediashvili** [comment]
Same here, started happening somewhere around yesterday noon (EST). We release updates daily stopped working today.

**Comment by bvirlet** [comment]
I had the issue this morning but not anymore. Probably a temporary issue with App Store Connect? @ArthurAlvarez can you try again?

**Comment by FelixLisczyk** [comment]
Same issue. When I try to create the version in App Store Connect manually, I get an error that the version number is already in use. After a page reload, the new version magically appears.

**Comment by TheWirv** [comment]
My pipelines still fail consistently

**Comment by rogerluan** [comment]
This could be a legitimate issue with App Store Connect API, e.g. http 500 or timeouts. I've been monitoring ASC API on my own an noticed that it's been partially degraded for the past ~9 hours, see: https://x.com/rogerluan_/status/1734206562418258125

My monitoring system didn't detect anything prior to 9 hours ago though (e.g. 3-4 days ago everything seemed fine on their end 😬) so it could be a different issue that is impacting you guys!

Just sharing what I got 😅

**Comment by sumeetp26** [comment]
Still happening. Is there any workaround or fix?

**Comment by rogerluan** [comment]
FWIW I'm still seeing intermittent issues (HTTP 500) with App Store Connect API calls. You can monitor them here:

https://status.statused.com

Or more specifically here (for further downtime details): https://stats.uptimerobot.com/1kzByfnDjz/795501684

**Comment by percula** [comment]
Same issue here. Is there a way to increase the retry interval or number of retries?

**Comment by nwainwright** [comment]
Same issue here. We're delivering builds via Transporter while this is going on. Is this an Apple or a fastlane issue? Any idea of what the resolution would be?

**Comment by rogerluan** [comment]
Looks like an issue on Apple servers

**Comment by nwainwright** [comment]
Hi @rogerluan but the chances of Apple fixing their code anytime soon are pretty low so maybe fastlane can work around it somehow? They did their 10 second retries so maybe something else needs to be incorporated?

**Comment by dcacenabes** [comment]
In an attempt to mitigate this, we have updated our release flows to first trigger an independent call to
[ensure_version!(version_string, platform: nil, client: nil)](https://github.com/fastlane/fastlane/blob/b629b2c157bf6085b7c10d1cdf63c817bd2958c4/spaceship/lib/spaceship/connect_api/models/app.rb#L207),
then we actually build the app and trigger the upload.

Our assumption (that might be totally wrong) is that between the call that Fastlane does to create a new version in the App Store and the upload itself, there is not enough time for ASC to properly propagate the changes. We hope that by introducing a few minutes delay between the 2 operations the release will be successful.

**Comment by nwainwright** [comment]
Hi @dcacenabes, thank you, is is this in the latest fastlane or do we need to call a special version somehow? I'm a bit of a newbie.

**Comment by dcacenabes** [comment]
for this you need to work with the app store connect API directly.

```
Spaceship::ConnectAPI.token = "this_is_your_token"
app = Spaceship::ConnectAPI::App.get(app_id: "your_app_id_in_app_store_connect)
app.ensure_version!("X.Y.Z", platform: Spaceship::ConnectAPI::Platform::IOS) # X.Y.Z is the semantic version of the new release for your app
```

You can find information on how to authenticate in the official docs:
https://github.com/fastlane/fastlane/blob/master/spaceship/docs/AppStoreConnect.md#login

**Comment by nwainwright** [comment]
Thanks @dcacenabes!

**Comment by ArthurAlvarez** [comment]
I was able to mitigate the issue simply by increasing the timeout time to 60 seconds instead of 10. You can check [PR #21740](https://github.com/fastlane/fastlane/pull/21740)
I hope Apple fixes the issue on their side soon. For now, that's the easiest solution.

**Comment by rogerluan** [comment]
> Hi @rogerluan but the chances of Apple fixing their code anytime soon are pretty low so maybe fastlane can work around it somehow? They did their 10 second retries so maybe something else needs to be incorporated?

I've opened a PR that should resolve the issues you guys are seeing: https://github.com/fastlane/fastlane/pull/21742

@ everyone, if you wanna help (and increase the chances of your CI succeeding 😇), you can help test this PR of mine in the wild 🙇 this would be tremendously helpful and I'd be super grateful! ☺️

Looking forward to hearing feedback from the community whether the proposed solution works 🙏 

---

@ArthurAlvarez I reviewed your PR and I proposed a different solution (see PR above), I hope you're okay with that! 🙇 thank you for taking a stab at fixing this issue, though! Super helpful! ❤️

**Comment by kpowelltech** [comment]
This is still a significant issue for us.  I build hundreds of apps using Fastlane and approx. 50% of my builds fail.  I'm using Fastlane version 2.219.0.

**Comment by lukeredpath** [comment]
Just ran into this issue for the first time, running my first release train of the year. Our CI release flow uploads a release build to TestFlight for internal QA and then holds on an approval job - once approved it runs the last CI job that actually submits the build for review using `deliver`. I ran that today and it failed with the error mentioned above. I had to run it three times before it was successful.

**Comment by mregnauld** [comment]
I experienced the same problem today too.

**Comment by BubnovSA** [comment]
I wonder when this will be fixed, because half of the assemblies simply don’t work....

**Comment by ArthurAlvarez** [comment]
Currently there is no working solution to this problem. #21742 adds some retries with exponential backoff to increase the chances of your lane succeeding but it may make your CI/CD task take a long time to complete and even then it may still fail.

Personally, whenever I release a new version of my app on the App Store, I am now manually creating the next app version on App Store Connect and then any subsequent lanes that upload that version will work as always.

**Comment by alex-lechner** [comment]
This issue is still not fixed (at least for Github Workflow. I'm using Fastlane version 2.219.0 (latest as of now) and I still get `Cannot update languages - could not find an editable version for 'IOS'`

**Comment by Dante1349** [comment]
had the same issue as well with the latest fastlane version

**Comment by lukeredpath** [comment]
Still happening for me - every time I run our workflow to submit for review, it fails this way and has to be retried. The job succeeds the second time.
