### ISSUE TITLE
testflight Action Fails with Error -1010 on CI/Jenkins After Updating to Xcode 15

### ISSUE THREAD

**Issue by ilkeyucel** [fastlane/fastlane#21706]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

After updating to Xcode 15 on our Jenkins CI nodes, the testflight action consistently fails with the following error message:
`[altool] 2023-12-08 12:05:45.070 *** Error: Exception caught. *** -[__NSArrayM insertObject:atIndex:]: object cannot be nil (-1010)`

Expected Behavior:
The testflight action should complete successfully, as it did with Xcode 14.3.1.

##### Command executed

```
desc "Submit Nightly Build to TestFlight"
  lane :nightly do |options|
    prepare_deploy_env(build_number: options[:build_number])
    sync_code_signing(type: "appstore")
    gym

    ipa_file_name = "xxxxx.ipa"
    ipa_file_path = "#{ENV["FL_SETUP_JENKINS_OUTPUT_DIRECTORY"]}/#{ipa_file_name}"

    upload_retry_counter = 0
    begin
      testflight(ipa: ipa_file_path, skip_waiting_for_build_processing: true)
    rescue => ex
      upload_retry_counter += 1
      if upload_retry_counter <= TOTAL_UPLOAD_RETRIES
        puts ex.message
        UI.message("Failed, retry nr #{upload_retry_counter}/#{TOTAL_UPLOAD_RETRIES}")
        retry
      else
        raise ex
      end
    end

    upload_dsym_to_crashlytics(gsp_name: xxxxxx.plist")
  end

```

##### Complete output when running fastlane, including the stack trace and command used
```
12:05:28  ------------------------
12:05:28  --- Step: testflight ---
12:05:28  ------------------------
12:05:28  Creating authorization token for App Store Connect API
12:05:29  Ready to upload new build to TestFlight (App:XXXXX)...
12:05:29  Going to upload updated app to App Store Connect
12:05:29  This might take a few minutes. Please don't interrupt the script.
12:05:36  [altool] 2023-12-08 12:05:35.622 *** Error: Exception caught. *** -[__NSArrayM insertObject:atIndex:]: object cannot be nil (-1010)
12:05:36  
12:05:36  [altool]  {
12:05:36  
12:05:36  [altool]     NSLocalizedDescription = "Exception caught.";
12:05:36  
12:05:36  [altool]     NSLocalizedFailureReason = "*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil";
12:05:36  
12:05:36  [altool] }
12:05:36  
```

<details>
- This issue occurs on both Apple silicon and Intel machines. Reverting to Xcode 14.3.1 resolves the issue.
</details>

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                                                    |
| --------------------------- | ---------------------------------------------------------------------------------------- |
| OS                          | 13.6.1                                                                                   |
| Ruby                        | 3.2.2                                                                                    |
| Bundler?                    | true                                                                                     |
| Git                         | git version 2.43.0                                                                       |
| Installation Source         | ~/JenkinsWorkspace/workspace/ios-deploy-testflight/vendor/bundle/ruby/3.2.0/bin/fastlane |
| Host                        | macOS 13.6.1 (22G313)                                                                    |
| Ruby Lib Dir                | ~/.rubies/ruby-3.2.2/lib                                                                 |
| OpenSSL Version             | OpenSSL 1.1.1w  11 Sep 2023                                                              |
| Is contained                | false                                                                                    |
| Is homebrew                 | false                                                                                    |
| Is installed via Fabric.app | false                                                                                    |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                                              |
| Xcode Version               | 15.0.1                                                                                   |
| Swift Version               | 5.9                                                                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
#pilot required for iTunes login in build processing lane
fastlane_require "pilot"
fastlane_require "versionomy"

$:.unshift File.dirname(__FILE__)
require_relative "lib/git_helper.rb"
require_relative "lib/helpers.rb"

import "Fastfile+Actions"
import "Fastfile+Distribution"
import "Fastfile+Testing"

skip_docs
default_platform :ios

platform :ios do
  before_all do |lane, options|
    load_shared_variables
    setup_jenkins(unlock_keychain: options[:sign] || false,
                  keychain_password: options[:pw])

    authenticate_apc(options) if options[:apc_auth]

    reset_git if is_ci?
  end

  # All lanes are imported from Fastfile+* files

  def load_shared_variables
    begin
      import("common_keys")
    rescue => exception
      UI.error("fastlane/keys file not found")
      raise exception
    end
  end

  def authenticate_apc(options)
    key_path = is_ci ? options[:apc_key_path] : "fastlane/AuthKey.p8"

    begin
      app_store_connect_api_key(
        key_id: ENV["APC_API_KEY_ID"],
        issuer_id: ENV["APC_API_KEY_ISSUER_ID"],
        key_filepath: key_path,
        in_house: false,
      )

      UI.message("AppStore Connect - API authenticated")
    rescue => ex
      UI.error("AppStore Connect - Failed to authenticate. Does the AuthKey file exist? (path: #{key_path})")

      raise ex
    end
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
for_platform :ios do
  for_lane :alpha do
    app_identifier "xxxxx"
  end

  for_lane :pr_build do
    app_identifier "xxxxxx"
  end

  for_lane :nightly do
    app_identifier "xxxxxx"
  end

  for_lane :release do
    app_identifier "xxxxx"
  end
end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.217.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                       | Version | Update-Status |
| ---------------------------- | ------- | ------------- |
| fastlane-plugin-appcenter    | 2.1.1   | ✅ Up-To-Date  |
| fastlane-plugin-google_drive | 0.9.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.5.1        |
| did_you_mean                    | 1.6.3        |
| syntax_suggest                  | 1.0.2        |
| bundler                         | 2.4.22       |
| pathname                        | 0.2.1        |
| rake                            | 13.1.0       |
| rexml                           | 3.2.6        |
| CFPropertyList                  | 3.0.6        |
| base64                          | 0.2.0        |
| bigdecimal                      | 3.1.4        |
| concurrent-ruby                 | 1.2.2        |
| connection_pool                 | 2.4.1        |
| ruby2_keywords                  | 0.0.5        |
| drb                             | 2.2.0        |
| i18n                            | 1.14.1       |
| minitest                        | 5.20.0       |
| mutex_m                         | 0.2.0        |
| tzinfo                          | 2.0.6        |
| activesupport                   | 7.1.2        |
| public_suffix                   | 4.0.7        |
| addressable                     | 2.8.5        |
| httpclient                      | 2.8.3        |
| json                            | 2.7.0        |
| algoliasearch                   | 1.27.5       |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.3.0        |
| aws-partitions                  | 1.862.0      |
| aws-sigv4                       | 1.8.0        |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.190.0      |
| aws-sdk-kms                     | 1.74.0       |
| aws-sdk-s3                      | 1.141.0      |
| babosa                          | 1.0.4        |
| blockenspiel                    | 0.5.0        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| cork                            | 0.3.0        |
| nap                             | 1.1.0        |
| open4                           | 1.3.4        |
| claide-plugins                  | 0.9.2        |
| fuzzy_match                     | 2.0.4        |
| netrc                           | 0.11.0       |
| ffi                             | 1.16.3       |
| ethon                           | 0.16.0       |
| typhoeus                        | 1.4.1        |
| cocoapods-core                  | 1.14.3       |
| cocoapods-deintegrate           | 1.0.5        |
| cocoapods-downloader            | 2.1          |
| cocoapods-plugins               | 1.0.0        |
| cocoapods-search                | 1.0.1        |
| cocoapods-trunk                 | 1.6.0        |
| cocoapods-try                   | 1.2.0        |
| escape                          | 0.0.4        |
| fourflusher                     | 2.3.1        |
| gh_inspector                    | 1.1.3        |
| molinillo                       | 0.8.0        |
| ruby-macho                      | 2.5.1        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.23.0       |
| cocoapods                       | 1.14.3       |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.3.0        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| faraday                         | 1.10.3       |
| faraday-http-cache              | 2.5.0        |
| rchardet                        | 1.8.0        |
| git                             | 1.18.0       |
| kramdown                        | 2.4.0        |
| kramdown-parser-gfm             | 1.1.0        |
| no_proxy_fix                    | 0.1.2        |
| sawyer                          | 0.9.2        |
| octokit                         | 8.0.0        |
| unicode-display_width           | 2.5.0        |
| terminal-table                  | 3.0.2        |
| danger                          | 9.4.1        |
| danger-plugin-api               | 1.0.0        |
| danger-swiftformat              | 0.9.0        |
| danger-xcode_summary            | 0.5.3        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.5        |
| domain_name                     | 0.6.20231109 |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.105.0      |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.7        |
| jwt                             | 2.7.1        |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.18.0       |
| googleauth                      | 1.8.1        |
| mini_mime                       | 1.1.5        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| webrick                         | 1.8.1        |
| google-apis-core                | 0.11.2       |
| google-apis-androidpublisher_v3 | 0.53.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.29.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.1        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.45.0       |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.7.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.10       |
| terminal-notifier               | 2.0.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| fastlane-plugin-appcenter       | 2.1.1        |
| google-apis-drive_v3            | 0.45.0       |
| google-apis-sheets_v4           | 0.26.0       |
| racc                            | 1.7.3        |
| nokogiri                        | 1.15.5       |
| google_drive2                   | 3.0.9        |
| fastlane-plugin-google_drive    | 0.9.0        |
| gems                            | 1.2.0        |
| google-apis-discovery_v1        | 0.14.0       |
| thor                            | 1.3.0        |
| google-apis-generator           | 0.12.0       |
| google-api-client               | 0.53.0       |
| liquid                          | 5.4.0        |
| rufo                            | 0.16.3       |
| versionomy                      | 0.5.0        |
| xcpretty-json-formatter         | 0.1.1        |
</details>

*generated on:* **2023-12-08**
</details>
<details>
  
</details>

**Comment by Shiaulis** [comment]
The issue was caused by wrong `CURRENT_PROJECT_VERSION` that was containing string. Apparently, starting from Xcode 15 we cannot submit project versions other than numbers.

**Comment by williamdes** [comment]
> The issue was caused by wrong `CURRENT_PROJECT_VERSION` that was containing string. Apparently, starting from Xcode 15 we cannot submit project versions other than numbers.

Same with `MARKETING_VERSION`, thank you for reporting it !
