### ISSUE TITLE
adding badge issue

### ISSUE THREAD

**Issue by nmanojkoli1997** [fastlane/fastlane#21750]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
<not able to add badge>

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [Fastlane command: bundle exec fastlane run add_badge shield:'nightly-503-red' no_badge:'true' shield_scale:'1.0' shield_io_timeout:'10' 
 [Pipeline] sh
 +-----------------------------------------------------------------------------------------------------------------+
 |                                                  Used plugins                                                   |
 +---------------------------+---------+---------------------------------------------------------------------------+
 | Plugin                    | Version | Action                                                                    |
 +---------------------------+---------+---------------------------------------------------------------------------+
 | fastlane-plugin-lizard    | 1.3.3   | lizard                                                                    |
 | fastlane-plugin-badge     | 1.5.0   | add_badge                                                                 |
 | fastlane-plugin-appcenter | 1.11.1  | appcenter_fetch_devices, appcenter_fetch_version_number, appcenter_upload |
 +---------------------------+---------+---------------------------------------------------------------------------+
 
 Cannot read termcap database;
 using dumb terminal settings.
 [06:11:28]: -----------------------
 [06:11:28]: --- Step: add_badge ---
 [06:11:28]: -----------------------
 [06:11:28]: Start adding badges...
 [06:11:28]: './MercedesMeStories/Resources/Assets.xcassets/AppIcon.appiconset/App_Store_iOS.png'
 2023-12-22 06:11:29.236 rsvg-convert[6097:563534] XType: Using static font registry.
 
 Looking for related GitHub issues on fastlane/fastlane...
 
 ➡️  app_store_connect_api_key no implicit conversion of Hash into String
     https://github.com/fastlane/fastlane/issues/18176 [closed] 2 💬
     23 Apr 2021
 
 ➡️  Can't update fastlane with gem
     https://github.com/fastlane/fastlane/issues/17884 [closed] 3 💬
     08 Mar 2021
 
 ➡️  How to read Shell Curl output into a variable
     https://github.com/fastlane/fastlane/issues/16323 [closed] 3 💬
     20 Jun 2020
 
 and 9 more at: [https://github.com/fastlane/fastlane/search?q=no%20implicit%20conversion%20of%20Hash%20into%20String&type=Issues&utf8=✓](https://github.com/fastlane/fastlane/search?q=no%20implicit%20conversion%20of%20Hash%20into%20String&type=Issues&utf8=%E2%9C%93)
 
 🔗  You can ⌘ + double-click on links to open them directly in your browser.
 bundler: failed to load command: fastlane (/Users/jenkins/.rbenv/versions/3.0.5/bin/fastlane)
 /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/mini_magick-4.9.5/lib/mini_magick/image.rb:105:in `initialize': \e[31m[!] no implicit conversion of Hash into String\e[0m (TypeError)
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/mini_magick-4.9.5/lib/mini_magick/image.rb:105:in `open'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/mini_magick-4.9.5/lib/mini_magick/image.rb:105:in `open'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/mini_magick-4.9.5/lib/mini_magick/image.rb:105:in `open'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/badge-0.13.0/lib/badge/runner.rb:116:in `add_shield'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/badge-0.13.0/lib/badge/runner.rb:80:in `block in run'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/badge-0.13.0/lib/badge/runner.rb:65:in `each'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/badge-0.13.0/lib/badge/runner.rb:65:in `run'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-plugin-badge-1.5.0/lib/fastlane/plugin/badge/helper/badge_helper.rb:10:in `run'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-plugin-badge-1.5.0/lib/fastlane/plugin/badge/helper/badge_helper.rb:26:in `run'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-plugin-badge-1.5.0/lib/fastlane/plugin/badge/actions/add_badge_action.rb:6:in `run'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/one_off.rb:42:in `run'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/one_off.rb:22:in `execute'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/commands_generator.rb:226:in `block (2 levels) in run'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.217.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.217.0/bin/fastlane:23:in `<top (required)>'
 	from /Users/jenkins/.rbenv/versions/3.0.5/bin/fastlane:25:in `load'
 	from /Users/jenkins/.rbenv/versions/3.0.5/bin/fastlane:25:in `<top (required)>'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.5.2/lib/bundler/cli/exec.rb:58:in `load'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.5.2/lib/bundler/cli/exec.rb:58:in `kernel_load'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.5.2/lib/bundler/cli/exec.rb:23:in `run'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.5.2/lib/bundler/cli.rb:451:in `exec'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.5.2/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.5.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.5.2/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.5.2/lib/bundler/cli.rb:34:in `dispatch'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.5.2/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.5.2/lib/bundler/cli.rb:28:in `start'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.5.2/exe/bundle:28:in `block in <top (required)>'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.5.2/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.5.2/exe/bundle:20:in `<top (required)>'
 	from /Users/jenkins/.rbenv/versions/3.0.5/bin/bundle:23:in `load'
 	from /Users/jenkins/.rbenv/versions/3.0.5/bin/bundle:23:in `<main>'
 /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/mini_magick-4.9.5/lib/mini_magick/image.rb:105:in `initialize': no implicit conversion of Hash into String (TypeError)
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/mini_magick-4.9.5/lib/mini_magick/image.rb:105:in `open'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/mini_magick-4.9.5/lib/mini_magick/image.rb:105:in `open'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/mini_magick-4.9.5/lib/mini_magick/image.rb:105:in `open'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/badge-0.13.0/lib/badge/runner.rb:116:in `add_shield'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/badge-0.13.0/lib/badge/runner.rb:80:in `block in run'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/badge-0.13.0/lib/badge/runner.rb:65:in `each'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/badge-0.13.0/lib/badge/runner.rb:65:in `run'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-plugin-badge-1.5.0/lib/fastlane/plugin/badge/helper/badge_helper.rb:10:in `run'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-plugin-badge-1.5.0/lib/fastlane/plugin/badge/helper/badge_helper.rb:26:in `run'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-plugin-badge-1.5.0/lib/fastlane/plugin/badge/actions/add_badge_action.rb:6:in `run'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/one_off.rb:42:in `run'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/one_off.rb:22:in `execute'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/commands_generator.rb:226:in `block (2 levels) in run'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.217.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.217.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.217.0/bin/fastlane:23:in `<top (required)>'
 	from /Users/jenkins/.rbenv/versions/3.0.5/bin/fastlane:25:in `load'
 	from /Users/jenkins/.rbenv/versions/3.0.5/bin/fastlane:25:in `<top (required)>'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.5.2/lib/bundler/cli/exec.rb:58:in `load'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.5.2/lib/bundler/cli/exec.rb:58:in `kernel_load'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.5.2/lib/bundler/cli/exec.rb:23:in `run'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.5.2/lib/bundler/cli.rb:451:in `exec'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.5.2/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.5.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.5.2/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.5.2/lib/bundler/cli.rb:34:in `dispatch'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.5.2/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.5.2/lib/bundler/cli.rb:28:in `start'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.5.2/exe/bundle:28:in `block in <top (required)>'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.5.2/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
 	from /Users/jenkins/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.5.2/exe/bundle:20:in `<top (required)>'
 	from /Users/jenkins/.rbenv/versions/3.0.5/bin/bundle:23:in `load'
 	from /Users/jenkins/.rbenv/versions/3.0.5/bin/bundle:23:in `<main>'] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by rogerluan** [comment]
Hi @nmanojkoli1997, do you have imagemagick installed in the machine? Can you send here the result of `fastlane env` command?

**Comment by lacostej** [comment]
Looking at the stacktrace, it looks like you are using

fastlane 2.217
-> fastlane badge plugin 1.5.0
-> -> badge 0.13
-> -> -> mini_magick 4.9.5

badge 0.13 depends on 4.9.4 <= mini-magick < 5.0 (see https://rubygems.org/gems/badge)

and mini-magick 4.9.5 modified the code that fails https://github.com/minimagick/minimagick/compare/v4.9.4...v4.9.5

Maybe mini-magick 4.9.5 broke your setup. I would try to force the use of mini-magick v 4.9.4 by adding

`gem "mini-magick", "4.9.4"` to your `Gemfile`

This is I think an issue in badge or the fastlane badge plugin.

**Comment by lacostej** [comment]
Closing as this isn't a fastlane issue.
