### ISSUE TITLE
Cannot update languages - could not find an editable version for 'IOS'

### ISSUE THREAD

**Issue by woohyuknrg** [fastlane/fastlane#21755]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When upload ipa file, after logging 'Successfully set the version to xxx', then logging 'Cannot find edit app store version' 5 times.
Finally: Cannot update languages - could not find an editable version for 'IOS'

##### Command executed
upload_to_app_store(
      ipa: "./#{scheme}.ipa",
      automatic_release: false,
      force: true,
      submit_for_review: false,
      run_precheck_before_submit: false,
      app_identifier: "#{bundleId}",
      app_review_attachment_file: nil,
      reject_if_possible: true,
      skip_metadata: false,
      skip_screenshots: true,
      release_notes: {
        "en-US" => "#{releaseNote}"
      },
      submission_information: {
      	add_id_info_uses_idfa: false,
      },
      app_review_information: {
      	demo_user: "xxx",
  	demo_password: "xxx"
      }
    )

##### Complete output when running fastlane, including the stack trace and command used
[16:25:27]: --- Step: upload_to_app_store ---
[16:25:27]: ---------------------------------
[16:25:27]: Creating authorization token for App Store Connect API

+------------------------------------------------------------------------------------------+
|                                 deliver 2.217.0 Summary                                  |
+----------------------------------------------+-------------------------------------------+
| ipa                                          | ./xxx.ipa                            |
| automatic_release                            | false                                     |
| force                                        | true                                      |
| submit_for_review                            | false                                     |
| run_precheck_before_submit                   | false                                     |
| app_identifier                               | xxx                          |
| reject_if_possible                           | true                                      |
| skip_metadata                                | false                                     |
| skip_screenshots                             | true                                      |
| release_notes.en-US                          | Bug fixes |
| submission_information.add_id_info_uses_idfa | false                                     |
| app_review_information.demo_user             | xxx                               |
| app_review_information.demo_password         | ********                                  |
| api_key                                      | ********                                  |
| screenshots_path                             | ./fastlane/screenshots                    |
| metadata_path                                | ./fastlane/metadata                       |
| app_version                                  | 9.23.0                                    |
| username                                     | xxx                        |
| platform                                     | ios                                       |
| edit_live                                    | false                                     |
| use_live_version                             | false                                     |
| skip_binary_upload                           | false                                     |
| skip_app_version_update                      | false                                     |
| overwrite_screenshots                        | false                                     |
| sync_screenshots                             | false                                     |
| verify_only                                  | false                                     |
| phased_release                               | false                                     |
| reset_ratings                                | false                                     |
| team_id                                      | xxx                                 |
| dev_portal_team_id                           | xxx                                |
| precheck_default_rule_level                  | warn                                      |
| ignore_language_directory_validation         | false                                     |
| precheck_include_in_app_purchases            | true                                      |
+----------------------------------------------+-------------------------------------------+

[16:25:31]: Making sure the latest version on App Store Connect matches '9.23.0'...
[16:25:52]: Successfully set the version to '9.23.0'
[16:25:57]: Cannot find edit app store version... Retrying after 10 seconds (remaining: 4)
[16:26:08]: Cannot find edit app store version... Retrying after 10 seconds (remaining: 3)
[16:26:19]: Cannot find edit app store version... Retrying after 10 seconds (remaining: 2)
[16:26:30]: Cannot find edit app store version... Retrying after 10 seconds (remaining: 1)
[16:26:41]: Cannot find edit app store version... Retrying after 10 seconds (remaining: 0)
+--------------------------------------------------------------------------------------------------+
|                                           Lane Context                                           |
+--------------------+-----------------------------------------------------------------------------+
| DEFAULT_PLATFORM   | ios                                                                         |
| PLATFORM_NAME      | ios                                                                         |
| LANE_NAME          | ios release                                                                 |
| IPA_OUTPUT_PATH    | xxx                                 |
| XCODEBUILD_ARCHIVE | xxx  |
|                    | 16.18.07.xcarchive                                                          |
| DSYM_OUTPUT_PATH   | xxx                         |
+--------------------+-----------------------------------------------------------------------------+
[16:26:51]: Cannot update languages - could not find an editable version for 'IOS'

### Environment
swift-driver version: 1.87.1 <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 14.0                                        |
| Ruby                        | 3.0.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.39.3 (Apple Git-145)          |
| Installation Source         | ~/.rvm/gems/ruby-3.0.0/bin/fastlane         |
| Host                        | macOS 14.0 (23A344)                         |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-3.0.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.1u  30 May 2023                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 15.0.1                                      |
| Swift Version               | 5.9                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.217.0 | 💥 Check failed |

### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status |
| ----------------------- | ------- | ------------- |
| fastlane-plugin-bugsnag | 2.3.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| CFPropertyList                  | 3.0.6        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.3       |
| faraday_middleware              | 1.2.0        |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| gh_inspector                    | 1.1.3        |
| google-apis-playcustomapp_v1    | 0.13.0       |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.7.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.10       |
| terminal-notifier               | 2.0.0        |
| terminal-table                  | 3.0.2        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| tsort                           | 0.1.0        |
| set                             | 1.0.1        |
| uri                             | 0.10.1       |
| public_suffix                   | 5.0.4        |
| addressable                     | 2.8.5        |
| aws-eventstream                 | 1.3.0        |
| aws-sigv4                       | 1.8.0        |
| aws-partitions                  | 1.863.0      |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.190.0      |
| aws-sdk-kms                     | 1.74.0       |
| aws-sdk-s3                      | 1.141.0      |
| bundler                         | 2.4.12       |
| rexml                           | 3.2.6        |
| excon                           | 0.105.0      |
| multipart-post                  | 2.3.0        |
| domain_name                     | 0.6.20231109 |
| fastimage                       | 2.2.7        |
| webrick                         | 1.8.1        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| jwt                             | 2.7.1        |
| signet                          | 0.18.0       |
| os                              | 1.1.4        |
| googleauth                      | 1.8.1        |
| mini_mime                       | 1.1.5        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.2        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| google-apis-core                | 0.11.2       |
| google-apis-androidpublisher_v3 | 0.53.0       |
| rake                            | 13.1.0       |
| digest-crc                      | 0.6.5        |
| google-apis-storage_v1          | 0.29.0       |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-cloud-errors             | 1.3.1        |
| google-cloud-env                | 1.6.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.45.0       |
| json                            | 2.7.1        |
| unicode-display_width           | 2.5.0        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.1.0        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.23.0       |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.0        |
| date                            | 3.1.0        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.0        |
| securerandom                    | 0.1.0        |
| openssl                         | 2.2.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.2        |
| io-wait                         | 0.1.0        |
| zlib                            | 1.1.0        |
| resolv                          | 0.2.0        |
| digest                          | 3.0.0        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.0        |
| net-smtp                        | 0.2.1        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.0        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.6        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.1        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| prettyprint                     | 0.1.0        |
| pp                              | 0.1.0        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.0        |
| xml-simple                      | 1.1.9        |
| rchardet                        | 1.8.0        |
| git                             | 1.18.0       |
| fastlane-plugin-bugsnag         | 2.3.0        |
</details>

*generated on:* **2023-12-27**
</details>

**Comment by ErickMaeda** [comment]
Hey 👋 

It's a known issue, which is associated with the Apple servers,

There are some issues opened and this PR to try to avoid this problem: https://github.com/fastlane/fastlane/pull/21742

**Comment by woohyuknrg** [comment]
@ErickMaeda Thanks, I'll follow that way
