### ISSUE TITLE
Can't create provisioning profiles

### ISSUE THREAD

**Issue by Ewaily** [fastlane/fastlane#21770]
### New Issue Checklist

- [ ☑️ ] Updated fastlane to the latest version
- [ ☑️ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ☑️ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ☑️ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm trying to integrate fastlane to my iOS project and I got stuck in creating the provisioning profiles things 

##### Command executed
fastlane match development

##### Complete output when running fastlane, including the stack trace and command used
alprimecap-ios/AlprimeCap on  Development [!?] via 💎 v3.2.0 took 36s 
❯ fastlane match development

[✔] 🚀 
[00:22:17]: Successfully loaded '/Users/ewaily/Development/alprimecap-ios/AlprimeCap/fastlane/Matchfile' 📄

+-----------------------------------------------------------------+
|           Detected Values from './fastlane/Matchfile'           |
+----------------+------------------------------------------------+
| git_url        | git@bitbucket.org:trianglz/fastlane-ios-certi  |
|                | ficates.git                                    |
| storage_mode   | git                                            |
| type           | development                                    |
| app_identifier | ["com.Trianglz.AlprimeCap.Stg"]                |
| username       | muhammad.ewaily@gmail.com                      |
| team_id        | R82929T5X5                                     |
+----------------+------------------------------------------------+

+-----------------------------------------------------------------------------------------+
|                                Summary for match 2.218.0                                |
+----------------------------------------+------------------------------------------------+
| type                                   | development                                    |
| readonly                               | false                                          |
| generate_apple_certs                   | true                                           |
| skip_provisioning_profiles             | false                                          |
| app_identifier                         | ["com.Trianglz.AlprimeCap.Stg"]                |
| username                               | muhammad.ewaily@gmail.com                      |
| team_id                                | R82929T5X5                                     |
| storage_mode                           | git                                            |
| git_url                                | git@bitbucket.org:trianglz/fastlane-ios-certi  |
|                                        | ficates.git                                    |
| git_branch                             | master                                         |
| shallow_clone                          | false                                          |
| clone_branch_directly                  | false                                          |
| skip_google_cloud_account_confirmation | false                                          |
| s3_skip_encryption                     | false                                          |
| gitlab_host                            | https://gitlab.com                             |
| keychain_name                          | login.keychain                                 |
| force                                  | false                                          |
| force_for_new_devices                  | false                                          |
| include_mac_in_profiles                | false                                          |
| include_all_certificates               | false                                          |
| force_for_new_certificates             | false                                          |
| skip_confirmation                      | false                                          |
| safe_remove_certs                      | false                                          |
| skip_docs                              | false                                          |
| platform                               | ios                                            |
| derive_catalyst_app_identifier         | false                                          |
| fail_on_name_taken                     | false                                          |
| skip_certificate_matching              | false                                          |
| skip_set_partition_list                | false                                          |
| verbose                                | false                                          |
+----------------------------------------+------------------------------------------------+

[00:22:17]: Cloning remote git repo...
[00:22:17]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[00:22:20]: Checking out branch master...
[00:22:20]: 🔓  Successfully decrypted certificates repo
[00:22:20]: Verifying that the certificate and profile are still valid on the Dev Portal...
Available session is not valid anymore. Continuing with normal login.
[00:22:25]: Couldn't find a valid code signing identity for development... creating one for you now

+--------------------------------------------------------------------------+
|                         Summary for cert 2.218.0                         |
+-------------------------+------------------------------------------------+
| platform                | ios                                            |
| development             | true                                           |
| generate_apple_certs    | true                                           |
| force                   | true                                           |
| username                | muhammad.ewaily@gmail.com                      |
| team_id                 | R82929T5X5                                     |
| keychain_path           | /Users/ewaily/Library/Keychains/login.keychai  |
|                         | n-db                                           |
| skip_set_partition_list | false                                          |
+-------------------------+------------------------------------------------+

[00:22:25]: Starting login with user 'muhammad.ewaily@gmail.com'
Available session is not valid anymore. Continuing with normal login.
[00:22:29]: Successfully logged in
[00:22:30]: Enter the password for /Users/ewaily/Library/Keychains/login.keychain-db
[00:22:30]: This passphrase will be stored in your local keychain with the name fastlane_keychain_login and used in future runs
[00:22:30]: This prompt can be avoided by specifying the 'keychain_password' option or 'MATCH_KEYCHAIN_PASSWORD' environment variable
[00:22:30]: Password for login keychain: *********
[00:22:35]: Type password for login keychain again: *********
[⠋] Setting key partition list... (this can take a minute if there are a lot of keys installed) keychain: "/Users/ewaily/Library/Keychains/login.keychain-db"
version: 512
class: "inet"
attributes:
    0x00000007 <blob>="fastlane_keychain_login"
    0x00000008 <blob>=<NULL>
    "acct"<blob>=<NULL>
    "atyp"<blob>="dflt"
    "cdat"<timedate>=0x32303234303130333232323233385A00  "20240103222238Z\000"
    "crtr"<uint32>=<NULL>
    "cusi"<sint32>=<NULL>
    "desc"<blob>=<NULL>
    "icmt"<blob>=<NULL>
    "invi"<sint32>=<NULL>
    "mdat"<timedate>=0x32303234303130333232323233385A00  "20240103222238Z\000"
    "nega"<sint32>=<NULL>
    "path"<blob>=<NULL>
    "port"<uint32>=0x00000000 
    "prot"<blob>=<NULL>
    "ptcl"<uint32>=0x00000000 
    "scrp"<sint32>=<NULL>
    "sdmn"<blob>=<NULL>
    "srvr"<blob>="fastlane_keychain_login"
    "type"<uint32>=<NULL>
password has been deleted.
[00:22:38]: 
[00:22:38]: Could not configure imported keychain item (certificate) to prevent UI permission popup when code signing
Check if you supplied the correct `keychain_password` for keychain: `/Users/ewaily/Library/Keychains/login.keychain-db`
security: SecKeychainItemSetAccessWithPassword: The user name or passphrase you entered is not correct.
[00:22:38]: 
[00:22:38]: Please look at the following docs to see how to set a keychain password:
[00:22:38]:  - https://docs.fastlane.tools/actions/sync_code_signing
[00:22:38]:  - https://docs.fastlane.tools/actions/get_certificates
[✔] Setting key partition list... (this can take a minute if there are a lot of keys installed) 
[00:22:38]: Enter the password for /Users/ewaily/Library/Keychains/login.keychain-db
[00:22:38]: This passphrase will be stored in your local keychain with the name fastlane_keychain_login and used in future runs
[00:22:38]: This prompt can be avoided by specifying the 'keychain_password' option or 'MATCH_KEYCHAIN_PASSWORD' environment variable
[00:22:38]: Password for login keychain: *********
[00:22:42]: Type password for login keychain again: *********
[⠋] Setting key partition list... (this can take a minute if there are a lot of keys installed) keychain: "/Users/ewaily/Library/Keychains/login.keychain-db"
version: 512
class: "inet"
attributes:
    0x00000007 <blob>="fastlane_keychain_login"
    0x00000008 <blob>=<NULL>
    "acct"<blob>=<NULL>
    "atyp"<blob>="dflt"
    "cdat"<timedate>=0x32303234303130333232323234355A00  "20240103222245Z\000"
    "crtr"<uint32>=<NULL>
    "cusi"<sint32>=<NULL>
    "desc"<blob>=<NULL>
    "icmt"<blob>=<NULL>
    "invi"<sint32>=<NULL>
    "mdat"<timedate>=0x32303234303130333232323234355A00  "20240103222245Z\000"
    "nega"<sint32>=<NULL>
    "path"<blob>=<NULL>
    "port"<uint32>=0x00000000 
    "prot"<blob>=<NULL>
    "ptcl"<uint32>=0x00000000 
    "scrp"<sint32>=<NULL>
    "sdmn"<blob>=<NULL>
    "srvr"<blob>="fastlane_keychain_login"
    "type"<uint32>=<NULL>
password has been deleted.
[00:22:45]: 
[00:22:45]: Could not configure imported keychain item (certificate) to prevent UI permission popup when code signing
Check if you supplied the correct `keychain_password` for keychain: `/Users/ewaily/Library/Keychains/login.keychain-db`
security: SecKeychainItemSetAccessWithPassword: The user name or passphrase you entered is not correct.
[00:22:45]: 
[00:22:45]: Please look at the following docs to see how to set a keychain password:
[00:22:45]:  - https://docs.fastlane.tools/actions/sync_code_signing
[00:22:45]:  - https://docs.fastlane.tools/actions/get_certificates
[✔] Setting key partition list... (this can take a minute if there are a lot of keys installed) 
[00:22:45]: Successfully generated 428CZYM6Y7 which was imported to the local machine.
[00:22:45]: Verifying the certificate is properly installed locally...
[00:22:45]: Successfully installed certificate 428CZYM6Y7
[00:22:47]: Error setting value '[]' for option 'cached_profiles'
-->

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 14.2.1                                      |
| Ruby                        | 3.2.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.39.3 (Apple Git-145)          |
| Installation Source         | ~/.rvm/gems/ruby-3.2.0/bin/fastlane         |
| Host                        | macOS 14.2.1 (23C71)                        |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-3.2.0/lib                |
| OpenSSL Version             | OpenSSL 3.2.0 23 Nov 2023                   |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 15.1                                        |
| Swift Version               | 5.9.2                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple Developer Portal username


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.218.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.5.1        |
| did_you_mean                    | 1.6.3        |
| syntax_suggest                  | 1.0.2        |
| executable-hooks                | 1.6.1        |
| bundler-unload                  | 1.0.2        |
| rubygems-bundler                | 1.4.5        |
| bundler                         | 2.5.3        |
| pathname                        | 0.2.1        |
| rake                            | 13.1.0       |
| rexml                           | 3.2.6        |
| CFPropertyList                  | 3.0.6        |
| public_suffix                   | 5.0.4        |
| addressable                     | 2.8.6        |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.3.0        |
| aws-partitions                  | 1.877.0      |
| aws-sigv4                       | 1.8.0        |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.190.1      |
| aws-sdk-kms                     | 1.75.0       |
| aws-sdk-s3                      | 1.142.0      |
| babosa                          | 1.0.4        |
| claide                          | 1.1.0        |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.5        |
| domain_name                     | 0.6.20231109 |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.109.0      |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.3.0        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.3       |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.3.0        |
| gh_inspector                    | 1.1.3        |
| google-cloud-env                | 2.1.0        |
| jwt                             | 2.7.1        |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.18.0       |
| googleauth                      | 1.9.1        |
| httpclient                      | 2.8.3        |
| mini_mime                       | 1.1.5        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| webrick                         | 1.8.1        |
| google-apis-core                | 0.11.2       |
| google-apis-androidpublisher_v3 | 0.54.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.29.0       |
| google-cloud-errors             | 1.3.1        |
| google-cloud-core               | 1.6.1        |
| google-cloud-storage            | 1.45.0       |
| json                            | 2.7.1        |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.4.0        |
| plist                           | 3.7.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.10       |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 2.5.0        |
| terminal-table                  | 3.0.2        |
| tty-screen                      | 0.8.2        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.23.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
</details>

*generated on:* **2024-01-04**
</details>

**Comment by barisdemirkap** [comment]
same on me, I think we need to use ci system with and without fastlane.

**Comment by arc-v2** [comment]
Looks like this issue is fixed in https://github.com/fastlane/fastlane/pull/21766.

**Comment by Ewaily** [comment]
> Looks like this issue is fixed in #21766.

@arc-v2  I'm not working with Circle CI at the moment

**Comment by arc-v2** [comment]
> > Looks like this issue is fixed in #21766.
> 
> @arc-v2 I'm not working with Circle CI at the moment

@Ewaily That issue is a regression with 'fastlane match' since 2.218.0, it is not specific to circle CI. Can you try it with an older version of fastlane?

**Comment by Ewaily** [comment]
> > > Looks like this issue is fixed in #21766.
> > 
> > 
> > @arc-v2 I'm not working with Circle CI at the moment
> 
> @Ewaily That issue is a regression with 'fastlane match' since 2.218.0, it is not specific to circle CI. Can you try it with an older version of fastlane?

@arc-v2  thank you! I'll try to downgrade the fastlane version

**Comment by Ewaily** [comment]
@arc-v2  Downgrading to version 2.217.0 did work thank you!

**Comment by EugeneBychkailoIos** [comment]
@arc-v2  @Ewaily  


downgraded to v 2.217.0 - but still have same 


  security create-keychain -p "" /Users/runner/Library/Keychains/login.keychain || echo "login.keychain already exists"
  security unlock-keychain -p "" /Users/runner/Library/Keychains/login.keychain

security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "" /Users/runner/Library/Keychains/login.keychain

security: SecKeychainItemSetAccessWithPassword: The user name or passphrase you entered is not correct.
keychain: "/Users/runner/Library/Keychains/login.keychain-db"
