### ISSUE TITLE
Error: can't satisfy 'google-cloud-env (>= 1.6.0, < 2.0.0)', already activated 'google-cloud-env-2.1.0'

### ISSUE THREAD

**Issue by triplef** [fastlane/fastlane#21788]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: 2.219.0
- Last working version: 2.218.0

### Regression Description

After upgrading to 2.219.0 I’m getting this error when running fastlane:
```
can't satisfy 'google-cloud-env (>= 1.6.0, < 2.0.0)', already activated 'google-cloud-env-2.1.0' (Gem::LoadError)
```

This seems to be caused by https://github.com/fastlane/fastlane/pull/21777. How can I find out what is activating `google-cloud-env-2.1.0`?

<details>
  <pre>/opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/rubygems/specification.rb:1452:in `block in activate_dependencies': can't satisfy 'google-cloud-env (>= 1.6.0, < 2.0.0)', already activated 'google-cloud-env-2.1.0' (Gem::LoadError)
	from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/rubygems/specification.rb:1444:in `each'
	from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/rubygems/specification.rb:1444:in `activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/rubygems/specification.rb:1426:in `activate'
	from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/rubygems.rb:284:in `block in activate_bin_path'
	from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/rubygems.rb:283:in `synchronize'
	from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/rubygems.rb:283:in `activate_bin_path'
	from /Users/me/.gem/bin/fastlane:25:in `<main>'
</pre>
</details>

### Environment

Cannot run `fastlane env` because of the above error.

**Comment by lacostej** [comment]
Do you run fastlane using a package manager? E:g. Bundler.

If not, can you try?
If yes, does `bundle exec fastlane env` works?

**Comment by triplef** [comment]
In this specific setup I’m currently not using a package manager, but I found out the problem seems to be with `googleauth`:

I had `googleauth-1.9.1` installed, which depends on `google-cloud-env (~> 2.1)` and which clashes with the `google-cloud-env (>= 1.6.0, < 2.0.0)` dependency from fastlane. If I install `googleauth-1.8.1` it works fine.

Maybe this dependency needs to be pinned to < 1.9?
https://github.com/fastlane/fastlane/blob/ebd6dafadac4a6aad4811bb32801af0e1f3ef2df/supply/lib/supply/client.rb#L1
