### ISSUE TITLE
`setup_circle_ci` step fails with error "The terminfo database could not be found"

### ISSUE THREAD

**Issue by jRichardeau** [fastlane/fastlane#21794]
Hello,

Since yesterday without changing anything our `fastlane` execution fails on CircleCI with this error : 

```sh
bundler: failed to load command: fastlane (/opt/homebrew/lib/ruby/gems/3.3.0/bin/fastlane)
/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/reline/terminfo.rb:94:in `setupterm':
[!] The terminfo database could not be found. (Reline::Terminfo::TerminfoError)
[...]
require': cannot load such file -- readline.bundle (LoadError) Did you mean? readline
```

Updating `fastlane` to the latest version does not solve the issue.

<details>
<summary>Here is the complete error log</summary>
<blockquote>
bundler: failed to load command: fastlane (/opt/homebrew/lib/ruby/gems/3.3.0/bin/fastlane)
/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/reline/terminfo.rb:94:in `setupterm': [!] The terminfo database could not be found. (Reline::Terminfo::TerminfoError)
	from /opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/reline/ansi.rb:34:in `< class:ANSI>'
	from /opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/reline/ansi.rb:5:in `< top (required)>'
	from < internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from < internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/reline.rb:599:in `< top (required)>'
	from < internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from < internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/readline.rb:4:in `rescue in < top (required)>'
	from /opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/readline.rb:1:in `< top (required)>'
	from < internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from < internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/tty-screen-0.8.1/lib/tty/screen.rb:232:in `size_from_readline'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/tty-screen-0.8.1/lib/tty/screen.rb:66:in `size'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/tty-screen-0.8.1/lib/tty/screen.rb:76:in `width'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:90:in `header'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/actions/actions_helper.rb:68:in `execute_action'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:78:in `block (2 levels) in parsing_binding'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:291:in `execute_flow_block'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:46:in `block in execute'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/bin/fastlane:23:in `< top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.3.0/bin/fastlane:25:in `load'
	from /opt/homebrew/lib/ruby/gems/3.3.0/bin/fastlane:25:in `< top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/bundler-2.4.20/lib/bundler/cli/exec.rb:58:in `load'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/bundler-2.4.20/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/bundler-2.4.20/lib/bundler/cli/exec.rb:23:in `run'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/bundler-2.4.20/lib/bundler/cli.rb:492:in `exec'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/bundler-2.4.20/lib/bundler/cli.rb:34:in `dispatch'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/bundler-2.4.20/lib/bundler/cli.rb:28:in `start'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/bundler-2.4.20/exe/bundle:37:in `block in < top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/bundler-2.4.20/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/bundler-2.4.20/exe/bundle:29:in `< top (required)>'
	from /opt/homebrew/opt/ruby/bin/bundle:25:in `load'
	from /opt/homebrew/opt/ruby/bin/bundle:25:in `< main>'
< internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- readline.bundle (LoadError)
Did you mean?  readline
	from < internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/readline.rb:2:in `< top (required)>'
	from < internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from < internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/tty-screen-0.8.1/lib/tty/screen.rb:232:in `size_from_readline'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/tty-screen-0.8.1/lib/tty/screen.rb:66:in `size'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/tty-screen-0.8.1/lib/tty/screen.rb:76:in `width'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:90:in `header'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/actions/actions_helper.rb:68:in `execute_action'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:78:in `block (2 levels) in parsing_binding'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:291:in `execute_flow_block'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:46:in `block in execute'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-2.216.0/bin/fastlane:23:in `< top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.3.0/bin/fastlane:25:in `load'
	from /opt/homebrew/lib/ruby/gems/3.3.0/bin/fastlane:25:in `< top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/bundler-2.4.20/lib/bundler/cli/exec.rb:58:in `load'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/bundler-2.4.20/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/bundler-2.4.20/lib/bundler/cli/exec.rb:23:in `run'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/bundler-2.4.20/lib/bundler/cli.rb:492:in `exec'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/bundler-2.4.20/lib/bundler/cli.rb:34:in `dispatch'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/bundler-2.4.20/lib/bundler/cli.rb:28:in `start'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/bundler-2.4.20/exe/bundle:37:in `block in < top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/bundler-2.4.20/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/bundler-2.4.20/exe/bundle:29:in `< top (required)>'
	from /opt/homebrew/opt/ruby/bin/bundle:25:in `load'
	from /opt/homebrew/opt/ruby/bin/bundle:25:in `< main>'
</blockquote>
</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                              |
| --------------------------- | -------------------------------------------------- |
| OS                          | 13.2.1                                             |
| Ruby                        | 3.0.6                                              |
| Bundler?                    | false                                              |
| Git                         | git version 2.41.0                                 |
| Installation Source         | ~/.rbenv/versions/3.0.6/bin/fastlane               |
| Host                        | macOS 13.2.1 (22D68)                               |
| Ruby Lib Dir                | ~/.rbenv/versions/3.0.6/lib                        |
| OpenSSL Version             | OpenSSL 1.1.1t  7 Feb 2023                         |
| Is contained                | false                                              |
| Is homebrew                 | false                                              |
| Is installed via Fabric.app | false                                              |
| Xcode Path                  | /Applications/Xcode-14.3.1.app/Contents/Developer/ |
| Xcode Version               | 14.3.1                                             |
| Swift Version               | 5.8.1                                              |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
#### redacted ####

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple Developer Portal username


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.213.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.6        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.7.0        |
| public_suffix                   | 4.0.7        |
| addressable                     | 2.8.4        |
| multipart-post                  | 2.3.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.99.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.3       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.7        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.5.1        |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.8.1        |
| simctl                          | 1.6.10       |
| jwt                             | 2.7.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.5.2        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.8.1        |
| google-apis-core                | 0.11.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-apis-androidpublisher_v3 | 0.42.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.1        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.19.0       |
| rake                            | 13.0.3       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.44.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.6.2        |
| aws-partitions                  | 1.772.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.2        |
| aws-sdk-core                    | 3.174.0      |
| aws-sdk-kms                     | 1.65.0       |
| aws-sdk-s3                      | 1.123.0      |
| set                             | 1.0.1        |
| bundler                         | 2.4.13       |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.2        |
| date                            | 3.1.3        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.0        |
| uri                             | 0.10.2       |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.2.2        |
| digest                          | 3.0.0        |
| io-nonblock                     | 0.1.0        |
| io-wait                         | 0.2.0        |
| zlib                            | 2.0.0        |
| resolv                          | 0.2.1        |
| time                            | 0.1.1        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.1        |
| ostruct                         | 0.3.1        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.7        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| net-http                        | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.2.1        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.2        |
</details>

*generated on:* **2024-01-11**
</details>

Thank you for your help

**Comment by NeilCossorFrollo** [comment]
just hit the same issue, and macos orb 2.4.1 and ruby 2.1.1 did not get around the issue.. 
"`setup_circle_ci` step fails with error "The terminfo database could not be found"

**Comment by airowe** [comment]
> just hit the same issue, and macos orb 2.4.1 and ruby 2.1.1 did not get around the issue.. 
> 
> "`setup_circle_ci` step fails with error "The terminfo database could not be found"

Ruby version should be fixed to 3.2, not 2.1.1 (that's the version of the Ruby orb).

**Comment by Vaidios** [comment]
Locking ruby version to 3.2 works, if anyone is wondering, this can be done through macOS orb:
```      
- macos/switch-ruby:
       version: "3.2"
```

This does seem like a temporary solution to this problem though.

After my quick investigation it indeed seems like tty-screen gem uses readline on line 356:
` ruby/3.3.0/gems/tty-screen-0.8.2/lib/tty/screen.rb:356:in `size_from_readline'`
which s being retired on ruby 3.3.

It seems like the best approach to it would be to fix it in tty-screen gem and then bump this fastlane dependency, is that right?
This is my first time trying to contribute to open source in any way, so I don't really know my way around these problems :D

**Comment by pedrofneves** [comment]
Use the previous macos machine 15.2.0 on CircleCI. It worked for me.

https://circleci.com/docs/using-macos/

**Comment by piotrmurach** [comment]
The `tty-screen` when attempting to detect size from `readline` attempts to load this standard gem. Loading the `readline` gem on Ruby `3.3` will first attempt to load the `readline-ext` C extension when present or fall back to using the pure Ruby `reline` gem.

Therefore, by default `tty-screen` doesn't install or rely on the `readline-ext` gem on Ruby `3.3` as it is no longer part of the installation as noted by @jRichardeau, however, given the log output, it uses `reline` to try to detect terminal size. In turn, the `Reline::TermInfo` module `setupterm` tries to find out if a terminal is attached via the `curses` extension and fails.

I've noticed that the Circle CI setup uses `tty-screen` version `0.8.1`. There is a newer release of `tty-screen`, version `0.8.2`. In this release, I check if the terminal is attached before attempting to load `readline` and following that `reline` dependency. Therefore, my suggestion would be to upgrade `tty-screen` to `0.8.2` on Ruby `3.3` and see if that resolves the issue.

**Comment by ashinkuniyil-well** [comment]
Adding `gem 'rb-readline'` before `gem "fastlane" `in the Gemfile resolved the issue for me.

xcode:
    macos:
      xcode: '15.3.0'
      
 Ruby 3.3.0

**Comment by ashinkuniyil** [comment]
Adding `gem 'rb-readline'` before `gem "fastlane"` in the Gemfile resolved the issue for me.

xcode:
macos:
xcode: '15.3.0'

Ruby 3.3.0

**Comment by PrasathRV** [comment]
Hi @ashinkuniyil,
Adding `gem 'rb-readline'` before `gem "fastlane"` in the Gemfile resolved the issue for me, works for me 👍 Thanks a lot.

In the iOS SDK,
**XCode:** 15.3.0
**Ruby:** 3.3.0
**React native:** 0.65.2

**Adding the Gemfile path in the React Native project:**
You can find the Gemfile inside, `/project_root_directory/Gemfile`

After updating the Gemfile, it looks like this,
```
source "https://rubygems.org"

gem "rexml"
gem 'rb-readline'  # <--This command comes here
gem "fastlane", "2.216.0"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)

```

**Comment by fotos** [comment]
> Therefore, my suggestion would be to upgrade `tty-screen` to `0.8.2` on Ruby `3.3` and see if that resolves the issue.

@piotrmurach we upgraded `tty-screen` to version `0.8.2` and it didn't work:

```
bundler: failed to load command: fastlane (/Users/distiller/project/ios/vendor/bundle/ruby/3.3.0/bin/fastlane)
/Users/distiller/.rbenv/versions/3.3.0/lib/ruby/3.3.0/reline/terminfo.rb:94:in `setupterm': [!] The terminfo database could not be found. (Reline::Terminfo::TerminfoError)
	from /Users/distiller/.rbenv/versions/3.3.0/lib/ruby/3.3.0/reline/ansi.rb:34:in `<class:ANSI>'
	from /Users/distiller/.rbenv/versions/3.3.0/lib/ruby/3.3.0/reline/ansi.rb:5:in `<top (required)>'
	from <internal:/Users/distiller/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/distiller/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/distiller/.rbenv/versions/3.3.0/lib/ruby/3.3.0/reline.rb:599:in `<top (required)>'
	from <internal:/Users/distiller/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/distiller/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/distiller/.rbenv/versions/3.3.0/lib/ruby/3.3.0/readline.rb:4:in `rescue in <top (required)>'
	from /Users/distiller/.rbenv/versions/3.3.0/lib/ruby/3.3.0/readline.rb:1:in `<top (required)>'
	from <internal:/Users/distiller/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/distiller/.rbenv/versions/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/distiller/project/ios/vendor/bundle/ruby/3.3.0/gems/tty-screen-0.8.2/lib/tty/screen.rb:356:in `size_from_readline'
	from /Users/distiller/project/ios/vendor/bundle/ruby/3.3.0/gems/tty-screen-0.8.2/lib/tty/screen.rb:111:in `size'
	from /Users/distiller/project/ios/vendor/bundle/ruby/3.3.0/gems/tty-screen-0.8.2/lib/tty/screen.rb:129:in `width'
	from /Users/distiller/project/ios/vendor/bundle/ruby/3.3.0/gems/fastlane-2.217.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:90:in `header'
        […]
```

Adding `rb-readline` before `fastlane` does the trick, as others have posted above.
