### ISSUE TITLE
upload_to_testflight fails with "This request is forbidden"

### ISSUE THREAD

**Issue by aparajita** [fastlane/fastlane#21797]
### New Issue Checklist

- [ x] Updated fastlane to the latest version
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

`upload_to_testflight` is successfully uploading the ipa, but when trying to notifying testers, it fails with this error:

`This request is forbidden for security reasons - The API key in use does not allow this request
fastlane finished with errors`

##### Command executed

```ruby
upload_to_testflight(
  changelog: changelog,
  expire_previous_builds: true,
)
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>----------------------------------
--- Step: upload_to_testflight ---
----------------------------------
Creating authorization token for App Store Connect API
Ready to upload new build to TestFlight (App: 6446960775)...
Going to upload updated app to App Store Connect
This might take a few minutes. Please don't interrupt the script.
------------------------------------------------------------------------------------------------------------------
--- Successfully uploaded package to App Store Connect. It might take a few minutes until it's visible online. ---
------------------------------------------------------------------------------------------------------------------
Successfully uploaded the new binary to App Store Connect
If you want to skip waiting for the processing to be finished, use the `skip_waiting_for_build_processing` option
Note that if `skip_waiting_for_build_processing` is used but a `changelog` is supplied, this process will wait for the build to appear on AppStoreConnect, update the changelog and then skip the remaining of the processing steps.
Waiting for processing on... app_id: 6446960775, app_version: 5.0.0, build_version: 108, platform: IOS
Read more information on why this build isn't showing up yet - https://github.com/fastlane/fastlane/issues/14997
Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
Waiting for App Store Connect to finish processing the new build (5.0.0 - 108) for IOS
Waiting for App Store Connect to finish processing the new build (5.0.0 - 108) for IOS
Waiting for App Store Connect to finish processing the new build (5.0.0 - 108) for IOS
Waiting for App Store Connect to finish processing the new build (5.0.0 - 108) for IOS
Successfully finished processing the build 5.0.0 - 108 for IOS
Successfully set the changelog for build
+--------------------------------------------------------------------------------------------------------------------+
|                                                    Lane Context                                                    |
+--------------------------------+-----------------------------------------------------------------------------------+
| DEFAULT_PLATFORM               | ios                                                                               |
| PLATFORM_NAME                  |                                                                                   |
| LANE_NAME                      | dev                                                                               |
| LATEST_TESTFLIGHT_BUILD_NUMBER | 107                                                                               |
| LATEST_TESTFLIGHT_VERSION      | 5.0.0                                                                             |
| BUILD_NUMBER                   | 108                                                                               |
| VERSION_NUMBER                 | 5.0.0                                                                             |
| IPA_OUTPUT_PATH                | /Users/aparajita/Developer/projects/clients/willsub/apps-monorepo/apps/subs/ios/  |
|                                | App/subs.ipa                                                                      |
| XCODEBUILD_ARCHIVE             | /Users/aparajita/Library/Developer/Xcode/Archives/2024-01-11/subs 2024-01-11      |
|                                | 13.16.53.xcarchive                                                                |
| DSYM_OUTPUT_PATH               | /Users/aparajita/Developer/projects/clients/willsub/apps-monorepo/apps/subs/ios/  |
|                                | App/subs.app.dSYM.zip                                                             |
+--------------------------------+-----------------------------------------------------------------------------------+
This request is forbidden for security reasons - The API key in use does not allow this request
fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  upload_to_testflight failed with API forbidden error, though ipa sucessfully uploaded to TestFlight
    https://github.com/fastlane/fastlane/issues/14372 [closed] 33 💬
    25 Dec 2019

➡️  [spaceship, pilot] Getting "410 gone"
    https://github.com/fastlane/fastlane/issues/14521 [closed] 177 💬
    22 Jun 2019

🔗  You can ⌘ + double-click on links to open them directly in your browser.

[!] The request could not be completed because:
        This request is forbidden for security reasons - The API key in use does not allow this request
</pre>
</details>

### Environment

Any identifiers set to an empty string.

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 14.2.1                                      |
| Ruby                        | 3.2.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.43.0                          |
| Installation Source         | /usr/local/bin/ruby/3.2.0/bin/fastlane      |
| Host                        | macOS 14.2.1 (23C71)                        |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.2.2_1/lib       |
| OpenSSL Version             | OpenSSL 3.1.1 30 May 2023                   |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 15.1                                        |
| Swift Version               | 5.9.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
require 'json'
import("../../../../fastlane/utils.rb")
default_platform(:ios)

desc 'Push a new dev build to TestFlight'
lane :dev do |options|
  options[:displayName] = ''
  options[:dev] = true
  clear

  if options[:test]
    testme(options)
    next
  end

  build_for_testflight(options)
end

desc 'Push a production build to TestFlight'
lane :prod do |options|
  options[:displayName] = ''
  clear
  build_for_testflight(options)
end

# Push a build to TestFlight
def build_for_testflight(options)
  build(options)

  if !options[:build_only]
    changelog = prompt_for_changelog(options)
    upload_to_testflight(
      changelog: changelog,
      expire_previous_builds: true,
    )
  end

  restore
  notify_done(options)
end

# Builds the app with the given options
def build(options)
  setup_build
  set_version_and_build(options)

  if options[:dev]
    badge_icons
  end

  update_xcodeproj(
    options: { 'INFOPLIST_KEY_CFBundleDisplayName': options[:displayName] }
  )

  banner("Building #{options[:displayName]} #{lane_context[SharedValues::VERSION_NUMBER]} (#{lane_context[SharedValues::BUILD_NUMBER]})")

  build_app(
    xcargs: "-allowProvisioningUpdates",
    silent: true,
    suppress_xcode_output: true,
  )
end

def setup_build
  set_app_store_api_key
  update_app_identifier(app_identifier: bundle_id, plist_path: 'App/Info.plist')
end

def set_app_store_api_key
  app_store_connect_api_key(
    key_id: '',
    issuer_id: '',
    key_filepath: 'key.p8',
    duration: 1200, # optional (maximum 1200)
    in_house: false # optional but may be required if using match/sigh
  )
end

def set_version_and_build(options)
  if options[:build_number]
    build = options[:build_number]
  else
    build = latest_testflight_build_number + 1
  end

  lane_context[SharedValues::BUILD_NUMBER] = build.to_s
  increment_build_number(build_number: build, skip_info_plist: true)

  # Get the current version from package.json
  update_version(options)
end

# Badge dev icons
def badge_icons
  add_badge(dark: true)
end

# Restore everything to its original state
def restore
  #   update_app_identifier(app_identifier: '', plist_path: 'App/Info.plist')
  #   update_xcodeproj(
  #     options: { 'INFOPLIST_KEY_CFBundleDisplayName': '' }
  #   )
  #   `git restore ../App/Assets.xcassets/AppIcon.appiconset/*.png`
  restore_capacitor_config
end

def testme(options)
  puts latest_testflight_build_number(app_identifier: '')
  puts lane_context
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("") # The bundle identifier of your app

for_lane :dev do
  app_identifier("")
end

apple_id("") # Your Apple Developer Portal username

itc_team_id("") # App Store Connect Team ID
team_id("") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.219.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                           | Version | Update-Status |
| -------------------------------- | ------- | ------------- |
| fastlane-plugin-badge            | 1.5.0   | ✅ Up-To-Date  |
| fastlane-plugin-json             | 1.1.0   | ✅ Up-To-Date  |
| fastlane-plugin-versioning       | 0.5.2   | ✅ Up-To-Date  |
| fastlane-plugin-update_xcodeproj | 1.0.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                              | Version      |
| -------------------------------- | ------------ |
| error_highlight                  | 0.5.1        |
| did_you_mean                     | 1.6.3        |
| syntax_suggest                   | 1.0.2        |
| bundler                          | 2.4.10       |
| pathname                         | 0.2.1        |
| rake                             | 13.1.0       |
| rexml                            | 3.2.6        |
| CFPropertyList                   | 3.0.6        |
| concurrent-ruby                  | 1.2.2        |
| i18n                             | 1.12.0       |
| minitest                         | 5.18.0       |
| thread_safe                      | 0.3.6        |
| tzinfo                           | 1.2.11       |
| activesupport                    | 5.2.8.1      |
| public_suffix                    | 5.0.4        |
| addressable                      | 2.8.6        |
| httpclient                       | 2.8.3        |
| json                             | 2.7.1        |
| algoliasearch                    | 1.27.5       |
| artifactory                      | 3.0.15       |
| atomos                           | 0.1.3        |
| aws-eventstream                  | 1.3.0        |
| aws-partitions                   | 1.879.0      |
| aws-sigv4                        | 1.8.0        |
| jmespath                         | 1.6.2        |
| aws-sdk-core                     | 3.190.2      |
| aws-sdk-kms                      | 1.76.0       |
| aws-sdk-s3                       | 1.142.0      |
| babosa                           | 1.0.4        |
| fastimage                        | 2.3.0        |
| colored                          | 1.2          |
| highline                         | 2.0.3        |
| commander                        | 4.6.0        |
| dotenv                           | 2.8.1        |
| emoji_regex                      | 3.2.3        |
| excon                            | 0.109.0      |
| faraday-em_http                  | 1.0.0        |
| faraday-em_synchrony             | 1.0.0        |
| faraday-excon                    | 1.1.0        |
| faraday-httpclient               | 1.0.1        |
| multipart-post                   | 2.3.0        |
| faraday-multipart                | 1.0.4        |
| faraday-net_http                 | 1.0.1        |
| faraday-net_http_persistent      | 1.2.0        |
| faraday-patron                   | 1.0.0        |
| faraday-rack                     | 1.0.0        |
| faraday-retry                    | 1.0.3        |
| ruby2_keywords                   | 0.0.5        |
| faraday                          | 1.10.3       |
| domain_name                      | 0.6.20240107 |
| http-cookie                      | 1.0.5        |
| faraday-cookie_jar               | 0.0.7        |
| faraday_middleware               | 1.2.0        |
| gh_inspector                     | 1.1.3        |
| jwt                              | 2.7.1        |
| multi_json                       | 1.15.0       |
| os                               | 1.1.4        |
| signet                           | 0.18.0       |
| googleauth                       | 1.8.1        |
| mini_mime                        | 1.1.5        |
| declarative                      | 0.0.20       |
| trailblazer-option               | 0.1.2        |
| uber                             | 0.1.0        |
| representable                    | 3.2.0        |
| retriable                        | 3.1.2        |
| webrick                          | 1.8.1        |
| google-apis-core                 | 0.11.2       |
| google-apis-androidpublisher_v3  | 0.54.0       |
| google-apis-playcustomapp_v1     | 0.13.0       |
| google-cloud-env                 | 1.6.0        |
| digest-crc                       | 0.6.5        |
| google-apis-iamcredentials_v1    | 0.17.0       |
| google-apis-storage_v1           | 0.31.0       |
| google-cloud-errors              | 1.3.1        |
| google-cloud-core                | 1.6.1        |
| google-cloud-storage             | 1.47.0       |
| mini_magick                      | 4.12.0       |
| naturally                        | 2.2.1        |
| optparse                         | 0.4.0        |
| plist                            | 3.7.1        |
| rubyzip                          | 2.3.2        |
| security                         | 0.1.3        |
| simctl                           | 1.6.10       |
| terminal-notifier                | 2.0.0        |
| unicode-display_width            | 2.5.0        |
| terminal-table                   | 3.0.2        |
| tty-screen                       | 0.8.2        |
| tty-cursor                       | 0.7.1        |
| tty-spinner                      | 0.9.3        |
| word_wrap                        | 1.0.0        |
| claide                           | 1.1.0        |
| colored2                         | 3.1.2        |
| nanaimo                          | 0.3.0        |
| xcodeproj                        | 1.23.0       |
| rouge                            | 2.0.7        |
| xcpretty                         | 0.3.0        |
| xcpretty-travis-formatter        | 1.0.1        |
| badge                            | 0.13.0       |
| fuzzy_match                      | 2.0.4        |
| nap                              | 1.1.0        |
| netrc                            | 0.11.0       |
| ffi                              | 1.15.5       |
| ethon                            | 0.16.0       |
| typhoeus                         | 1.4.0        |
| cocoapods-core                   | 1.10.2       |
| cocoapods-deintegrate            | 1.0.5        |
| cocoapods-downloader             | 1.6.3        |
| cocoapods-plugins                | 1.0.0        |
| cocoapods-search                 | 1.0.1        |
| cocoapods-trunk                  | 1.6.0        |
| cocoapods-try                    | 1.2.0        |
| escape                           | 0.0.4        |
| fourflusher                      | 2.3.1        |
| molinillo                        | 0.6.6        |
| ruby-macho                       | 1.4.0        |
| cocoapods                        | 1.10.2       |
| colorize                         | 1.1.0        |
| fastlane-plugin-badge            | 1.5.0        |
| fastlane-plugin-json             | 1.1.0        |
| fastlane-plugin-update_xcodeproj | 1.0.1        |
| fastlane-plugin-versioning       | 0.5.2        |
</details>

*generated on:* **2024-01-11**
</details></pre>
</details>

**Comment by asbjornu** [comment]
Try removing `expire_previous_builds: true`. That made it work again for me.

**Comment by aparajita** [comment]
> Try removing `expire_previous_builds: true`. That made it work again for me.

Thanks, will give it a try.

**Comment by lacostej** [comment]
@aparajita here's another [discussion](https://github.com/fastlane/fastlane/discussions/18391) on the topic:

> I just noticed that an API key with a Developer Role is not allowed to create a new version of the app.
> Q: Does that mean if you have a higher-level role (e.g. App Manager) then you can just upload without manually creating a new version?
> Yes

**Comment by aparajita** [comment]
@alex-vasylchenko Yes, my key had Developer access. Will try with an App Manager key, thanks for the tip. If that works I'll close this issue.

**Comment by ropoja** [comment]
Same issue here, so the app manager key is mandatory for avoiding this error?

**Comment by aparajita** [comment]
> Same issue here, so the app manager key is mandatory for avoiding this error?

Yes, creating and using an App Manager key fixed it.
