### ISSUE TITLE
Unable to locate Xcode. Please make sure to have Xcode installed on your machine on GitLab CI

### ISSUE THREAD

**Issue by faizanbutt** [fastlane/fastlane#21796]
Hi, I am trying to do release automation of my react-native ios app.
I am getting this error of GitLab CI even though bundle exec fastlane mylane works fine on my local mac.
Here's my .gitlab-ci.yml file:
`image: reactnativecommunity/react-native-android:v12.0

stages:
  - build_app

cache:
  paths:
    - node_modules/
    - android/.gradle/

before_script:
  - npm install -g react-native-cli
  - npm install --legacy-peer-deps
  - bundle check --path vendor/bundle || bundle install --path vendor/bundle --jobs $(nproc)
deployiOS:
  stage: build_app
  script:
    - cd ios
    - bundle update fastlane
    - bundle exec fastlane beta
  only:
    - production`
    
    And here's my Fastfile inside ios/fastlane folders:
    `
default_platform(:ios)

platform :ios do
  lane :beta do
    gym(scheme: "buggy_admin_app")
    build_app(
      project: "app.xcodeproj",
      scheme: "app",
      configuration: "Release",
      export_method: "app-store"
    )
  end
end`

When the command bundle exec fastlane beta runs on gitlab CI, it throws the error:
Unable to locate Xcode. Please make sure to have Xcode installed on your machine

**Comment by lacostej** [comment]
Hello! This docker image seems to be Debian (Linux) based. It won't have xcode on it. It is made for building android. 

You will most probably use a [mac hardware](https://docs.gitlab.com/ee/ci/mobile_devops.html), either owned or rented, to do your builds. There are alternative ways to do this, such as running MacOS virtualized on a Linux host, but this isn't as far as I know, a setup people really use.

Here's[ an article for ios builds using fastlane using a Mac registered as custom runner for gitlab CI](https://medium.com/@naman.mittal/automate-ios-deployment-process-by-ci-cd-using-gitlab-ci-and-fastlane-547d824ee41a).

I am thus closing this issue. Good luck!
