### ISSUE TITLE
fastlane match development errors on   request = Net::HTTP::Get.new(url.request_uri)

### ISSUE THREAD

**Issue by nat2k5us** [fastlane/fastlane#21843]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                        |
| --------------------------- | ------------------------------------------------------------ |
| OS                          | 14.3                                                         |
| Ruby                        | 3.3.0                                                        |
| Bundler?                    | false                                                        |
| Git                         | git version 2.39.3 (Apple Git-145)                           |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.219.0_2/libexec/bin/fastlane |
| Host                        | macOS 14.3 (23D56)                                           |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.3.0/lib                          |
| OpenSSL Version             | OpenSSL 3.2.0 23 Nov 2023                                    |
| Is contained                | false                                                        |
| Is homebrew                 | true                                                         |
| Is installed via Fabric.app | false                                                        |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                  |
| Xcode Version               | 15.1                                                         |
| Swift Version               | 5.9.2                                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "IOSTest.xcodeproj")
    build_app(scheme: "IOSTest")
    upload_to_testflight
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.219.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.6.0        |
| did_you_mean                    | 1.6.3        |
| syntax_suggest                  | 2.0.0        |
| public_suffix                   | 5.0.4        |
| addressable                     | 2.8.6        |
| artifactory                     | 3.0.15       |
| aws-eventstream                 | 1.3.0        |
| aws-sigv4                       | 1.8.0        |
| aws-sdk-kms                     | 1.76.0       |
| aws-sdk-s3                      | 1.142.0      |
| babosa                          | 1.0.4        |
| bundler                         | 2.5.4        |
| rexml                           | 3.2.6        |
| CFPropertyList                  | 3.0.6        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.109.0      |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.3.0        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.3       |
| faraday_middleware              | 1.2.0        |
| domain_name                     | 0.6.20240107 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| fastimage                       | 2.3.0        |
| gh_inspector                    | 1.1.3        |
| google-apis-androidpublisher_v3 | 0.54.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.1        |
| google-cloud-core               | 1.6.1        |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.31.0       |
| jwt                             | 2.7.1        |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.18.0       |
| googleauth                      | 1.8.1        |
| rake                            | 13.1.0       |
| digest-crc                      | 0.6.5        |
| mini_mime                       | 1.1.5        |
| google-cloud-storage            | 1.47.0       |
| json                            | 2.7.1        |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.4.0        |
| plist                           | 3.7.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.10       |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 2.5.0        |
| terminal-table                  | 3.0.2        |
| tty-screen                      | 0.8.2        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| atomos                          | 0.1.3        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.23.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| set                             | 1.1.0        |
| aws-partitions                  | 1.883.0      |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.190.3      |
| httpclient                      | 2.8.3        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.2        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| google-apis-core                | 0.11.3       |
| forwardable                     | 1.3.3        |
| logger                          | 1.6.0        |
| pathname                        | 0.3.0        |
| shellwords                      | 0.2.0        |
| cgi                             | 0.4.1        |
| date                            | 3.3.4        |
| timeout                         | 0.4.1        |
| securerandom                    | 0.3.1        |
| uri                             | 0.13.0       |
| openssl                         | 3.2.0        |
| digest                          | 3.1.1        |
| ipaddr                          | 1.2.6        |
| resolv                          | 0.3.0        |
| time                            | 0.3.0        |
| stringio                        | 3.1.0        |
| open-uri                        | 0.4.1        |
| mutex_m                         | 0.2.0        |
| net-http                        | 0.4.0        |
| net-protocol                    | 0.2.2        |
| ostruct                         | 0.6.0        |
| english                         | 0.8.0        |
| erb                             | 4.0.3        |
| abbrev                          | 0.1.2        |
| tempfile                        | 0.2.1        |
| delegate                        | 0.3.1        |
| fileutils                       | 1.7.2        |
| tmpdir                          | 0.2.0        |
| base64                          | 0.2.0        |
| singleton                       | 0.2.0        |
| open3                           | 0.2.1        |
| nkf                             | 0.1.3        |
| prettyprint                     | 0.2.0        |
| pp                              | 0.5.0        |
| find                            | 0.2.0        |
| yaml                            | 0.3.0        |
| psych                           | 5.1.2        |
</details>

*generated on:* **2024-01-30**
</details>

/opt/homebrew/Cellar/fastlane/2.219.0_2/libexec/gems/fastlane-2.219.0/match/lib/match/storage/gitlab/client.rb:46:in `files': [!] undefined method `request_uri' for an instance of URI::Generic (NoMethodError)

            request = Net::HTTP::Get.new(url.request_uri)
                                            ^^^^^^^^^^^^
       ---
            request = Net::HTTP::Get.new(url.request_uri)
                                            ^^^^^^^^^^^^
     ---
        from /opt/homebrew/Cellar/fastlane/2.219.0_2/libexec/bin/fastlane:25:in `load'
        from /opt/homebrew/Cellar/fastlane/2.219.0_2/libexec/bin/fastlane:25:in `<main>'

**Comment by lacostej** [comment]
Something is off with your match setup.

This error only happens if the url passed to the gitlab client is invalid.

Your environment and the stack trace you are passing don't seem to be reflecting the full command, so I can't help more here.

Check your `Matchfile` and/or the arguments passed to `match`.

**Comment by nat2k5us** [comment]
The issue seems to be because I have Fastlane installed via homebrew already, then when I ran `bundle exec fastlane match init` it went and downloaded another fastlane and put it in `/usr/local/bin` or `/usr/bin` and so I removed the fastlane in these folders and now I can run `fastlane match development` and it works

**Comment by petrbela** [comment]
fwiw this happened to me when I skipped the custom gitlab URL step during `match init` which added `gitlab_host("")` to Matchfile. Removing that line fixed the issue.
