### ISSUE TITLE
A dependency license is copyleft (highline package)

### ISSUE THREAD

**Issue by nick-morhun** [fastlane/fastlane#21851]
### New Issue Checklist

- [v] Updated fastlane to the latest version
- [v] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [v] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [v] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Projects with proprietary code may have issues with using fastlane since one of the dependency licenses is copyleft: https://github.com/JEG2/highline

**Comment by lacostej** [comment]
According to https://github.com/JEG2/highline/blob/master/LICENSE the user decides of the license 
```
Distributed under the user's choice of the {GPL Version 2}[http://www.gnu.org/licenses/old-licenses/gpl-2.0.html] (see COPYING for details) or the
{Ruby software license}[http://www.ruby-lang.org/en/LICENSE.txt] by
James Edward Gray II and Greg Brown.
```

**Comment by nick-morhun** [comment]
> According to https://github.com/JEG2/highline/blob/master/LICENSE the user decides of the license
> 
> ```
> Distributed under the user's choice of the {GPL Version 2}[http://www.gnu.org/licenses/old-licenses/gpl-2.0.html] (see COPYING for details) or the
> {Ruby software license}[http://www.ruby-lang.org/en/LICENSE.txt] by
> James Edward Gray II and Greg Brown.
> ```

Unfortunately, Ruby license is not present at that location anymore but from what I found https://www.tldrlegal.com/license/ruby-license-ruby it is also "copyleft" - requires users to disclose all their source code.

**Comment by lacostej** [comment]
My understanding is that ruby is provided under the [BSDL](https://github.com/ruby/ruby/blob/master/BSDL) license as per [this document](https://github.com/ruby/ruby?tab=License-1-ov-file).
```
Ruby is copyrighted free software by Yukihiro Matsumoto <matz@netlab.jp>.
You can redistribute it and/or modify it under either the terms of the
2-clause BSDL (see the file BSDL), or the conditions below:
[...]
```

so by extension, highline should also be covered by the BSDL if we wish so. If that's the case, aren't we good?

IANAL.
