### ISSUE TITLE
GitLab Fastlane integration for CICD to deploy TestFlight (for Development) and App Store (for Release) builds.

### ISSUE THREAD

**Issue by JigneshPatel** [fastlane/fastlane#21856]
I want to auto deploy builds (TestFlight & Live App Store) via GitLab CICD feature using Fastlane. For that integration I am not able to go ahead using the steps provided [under](https://about.gitlab.com/blog/2023/06/07/ios-cicd-with-gitlab/) the official documentation of GitLab CICD. It is not allowing me to move ahead when asking for the Apple Store credentials.

Despite of writing working credentials It says:
 	The login credentials for 'abc@xyz.com' seem to be wrong
 	Invalid username and password combination. Used 'abc@xyz.com' as the username.

I want to know the overall process of working CICD concept for our all new iOS applications using GitLab's default recommended Fastlane integration. It will be helpful to know overall process for the 

<img width="1172" alt="Fastlane error 1" src="https://github.com/fastlane/fastlane/assets/1856177/fcfdc086-a32f-4c6d-907f-cf591d619f61">

Any detailed explanation or video for the working steps is highly appreciated and thankful in advance.

**Comment by lacostej** [comment]
> It is not allowing me to move ahead when asking for the Apple Store credentials.

what do you mean here?

A common practice is to use appstore credentials and pass them to your build job. It seems that the official gitlab tutorial does explain what to do here. See their section titled "Apple App Store integration". You should probably follow their tutorial.

**Comment by lacostej** [comment]
@JigneshPatel I'll close this for now. This isn't really an issue in fastlane.
