### ISSUE TITLE
[match] visionOS devices are not included in provisioning profiles

### ISSUE THREAD

**Issue by peter-gyarmati** [fastlane/fastlane#21860]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
visionOS devices are not included in provisioning profiles. 

With visionOS coming out Apple didn't bother to add a new platform to their signing infrastructure and you need to add your VisionPro device to the iOS development provisioning profiles as per their portal (picture attached). 

`match` currently doesn't add these devices to the profile. In case of manually adding them to the appropriate profile the next run of `match` will override the profile and remove the VisionPro device from the list of devices. Override is expected as the profile has been manually modified, however there is no other way to include them at the moment.

<img width="813" alt="image" src="https://github.com/fastlane/fastlane/assets/92735687/b3942faa-a02d-45f1-8d8d-3027ec02b92f">

Probably https://github.com/fastlane/fastlane/blob/26b695f8ed697fa21ca30d57db97d060ce21e631/match/lib/match/profile_includes.rb#L46 should be modified (and the used helper `Match::Portal::Fetcher` to allow the platform) to add Vision Pro devices as well to the profiles when new devices are added.

##### Command executed
`fastlane match` with `force_for_new_devices:true`.

##### Complete output when running fastlane, including the stack trace and command used
N/A

### Environment
N/A

**Comment by BookerE1** [comment]
Hello, peter-gyarmati

As per your post, I give you the best answer please see below and follow the step-by-step information...

Match is a tool that helps you sync your certificates and profiles across your team using a git repo, Google Cloud, or Amazon S3. VisionOS is a new operating system for Apple’s upcoming Vision Pro headset, which is a mixed-reality device that combines augmented reality and virtual reality.

According to your issue description, you are unable to include visionOS devices in your provisioning profiles using Match. This seems to be a bug or a missing feature in the match, as it does not recognize visionOS as a valid platform for code signing. You have also identified the possible source of the problem in the match code, which is the devices_differ. method that compares the devices in the portal profile and the cached devices.


To resolve this issue, you have a few options:

You can file a bug report or a feature request on the match GitHub repository, and provide the details of your issue, such as the command executed, the environment, and the expected and actual results. You can also attach the image of the portal profile that shows the visionOS devices. This will help the match developers and maintainers to investigate and fix the issue, or to add support for visionOS devices in future releases.
You can fork the match repository and modify the code yourself to include visionOS devices in the profiles. You can use the match documentation and the codesigning guide as references. You can also submit a pull request to the original repository with your changes, and contribute to the match community.
You can use another tool or method to create and manage your provisioning profiles for visionOS devices, such as Xcode, fastlane sigh, or Apple Developer Portal. You can also use these tools to download and install the profiles on your devices manually or automatically.


I hope this helps. If you have any other questions, feel free to ask me. Have a great day! 😊.



Best regard,
BookerE1
