### ISSUE TITLE
Unable to deploy iOS app to apple app store using fastlane 

### ISSUE THREAD

**Issue by arpitmishra-eaton** [fastlane/fastlane#21874]
we are using the Azure pipeline which is running the below script.

### pipeline script###

  - script: >-
                
                fastlane ios release apiKeyId: '$(API Key ID)'
                authType: 'ApiKey'
                apiKeyIssuerId: '$(API Issuer ID)'
                apitoken: '$(API Key base 64)'
                build_number: 13
                submit_for_review: 'true'
                automatic_release: 'true'
                skip_screenshots: 'true'
                app_version: 1.2
                team_id: ch51hdn
                app_identifier: 'com.eaton.abc'
                metadata_path: '$(Build.SourcesDirectory)/ios/fastlane/metadata/en-US/release_notes.txt'
                overwrite_screenshots: 'false'
                skip_screenshots: 'true'
              displayName: Promote build to prod release
              workingDirectory: $(Build.SourcesDirectory)/ios/
                      
                
                
 ###Fastlane file ###  
```
platform :ios do
  desc "Release Testflight Build"
  lane :release do |options|
    deliver(
      api_key = app_store_connect_api_key{
      key_id: ENV['API_Key_ID'],
      issuer_id: ENV['API_Issuer_ID'],
      key_filepath: ENV['API_Key_base_64'],
      }
      pilot(api_key: api_key)
      automatic_release: true,
      skip_binary_upload: false, 
      force: true,
      build_number: options[:build_number],
      submit_for_review: true,
      team_id: options[:team_id],
      app_version: options[:app_version],
      app_identifier: options[:app_identifier],
      metadata_path: options[:metadata_path],
      skip_screenshots: true,
      overwrite_screenshots: false,
      precheck_include_in_app_purchases: false,
      # https://github.com/artsy/eigen/blob/faa02e2746194d8d7c11899474de9c517435eca4/fastlane/Fastfile#L131-L149
      submission_information: {
        add_id_info_uses_idfa: false,
        }      
      )
 end
end
```
i'm facing the below error 
```
[12.41.44]:     21:	    deliver(
[12:41:44]:     22:	      api_key = app_store_connect_api_key{
[12:41:44]:  => 23:	      key_id: ENV['API Key ID'],
[12:41:44]:     24:	      issuer_id: ENV['API Issuer ID'],
[12:41:44]:     25:	      key_filepath: ENV['API Key base 64'],

[!] Syntax error in your Fastfile on line 23: Fastfile:23: syntax error, unexpected ':', expecting '}'
      key_id: ENV['API Key ID'],
            ^
Fastfile:24: syntax error, unexpected label, expecting '='
      issuer_id: ENV['API Issuer ID'],
```

Could you please help me to configure API key secrets in order to access from azure pipeline for authentication. ?

**Comment by lacostej** [comment]
Well, this was similar to #21875, except that here you are trying to pass the `api_key` here using env variables.

You have a syntax error in your Fastfile. A Fastfile is a [DSL](https://en.wikipedia.org/wiki/Domain-specific_language) made of ruby code. You have used `{}` instead of `()`.

Check the documentation on how to properly configure the [`app_store_connect_api_key`](https://docs.fastlane.tools/actions/app_store_build_number/).
