### ISSUE TITLE
Having issues with provisioning profiles

### ISSUE THREAD

**Issue by st3fus** [fastlane/fastlane#21870]
### New Issue Checklist

- [y ] Updated fastlane to the latest version
- [ y] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ y] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ y] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
There's a conflict with provisioning profiles, not sure why its creating one, it should pull the one from Appstore, i already have this app up and running

##### Command executed
bundle exec fastlane beta

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [✔] 🚀 
[18:32:30]: ------------------------------
[18:32:30]: --- Step: default_platform ---
[18:32:30]: ------------------------------
[18:32:30]: Driving the lane 'ios beta' 🚀
[18:32:30]: ------------------------------------
[18:32:30]: --- Step: increment_build_number ---
[18:32:30]: ------------------------------------
Current version of project App is: 
    5

/Users/macbookpro/dev/workspaces/smartedv2_frontend/ios/App
[18:32:30]: $ cd /Users/macbookpro/dev/workspaces/smartedv2_frontend/ios/App && agvtool next-version -all && cd -
[18:32:30]: ▸ Setting version of project App to:
[18:32:30]: ▸ 6.
[18:32:30]: ▸ Also setting CFBundleVersion key (assuming it exists)
[18:32:30]: ▸ Updating CFBundleVersion in Info.plist(s)...
[18:32:30]: ▸ Updated CFBundleVersion in "App.xcodeproj/../App/Info.plist" to 6
[18:32:30]: ▸ /Users/macbookpro/dev/workspaces/smartedv2_frontend/ios/App
[18:32:30]: ------------------------------
[18:32:30]: --- Step: get_certificates ---
[18:32:30]: ------------------------------

+---------------------------------------------------------------------------------+
|                            Summary for cert 2.219.0                             |
+-------------------------+-------------------------------------------------------+
| development             | false                                                 |
| force                   | false                                                 |
| generate_apple_certs    | true                                                  |
| username                | REDACTED                             |
| team_id                 | REDACTED                                            |
| keychain_path           | /Users/macbookpro/Library/Keychains/login.keychain-db |
| skip_set_partition_list | false                                                 |
| platform                | ios                                                   |
+-------------------------+-------------------------------------------------------+

[18:32:30]: Starting login with user 'REDACTED'
[18:32:33]: Successfully logged in
[18:32:34]: Found the certificate REDACTED (REDACTED) which is installed on the local machine. Using this one.
[18:32:34]: Verifying the certificate is properly installed locally...
[18:32:34]: Successfully installed certificate REDACTED
[18:32:34]: Use signing certificate 'REDACTED' from now on!
[18:32:34]: --------------------------------------
[18:32:34]: --- Step: get_provisioning_profile ---
[18:32:34]: --------------------------------------

+--------------------------------------------------------------------+
|                      Summary for sigh 2.219.0                      |
+-------------------------------------+------------------------------+
| filename                            | provisioning.mobileprovision |
| adhoc                               | false                        |
| developer_id                        | false                        |
| development                         | false                        |
| skip_install                        | false                        |
| force                               | false                        |
| include_mac_in_profiles             | false                        |
| app_identifier                      | rs.boost                     |
| username                            | REDACTED    |
| team_id                             | REDACTED                   |
| ignore_profiles_with_different_name | false                        |
| cert_id                             | REDACTED                   |
| skip_fetch_profiles                 | false                        |
| include_all_certificates            | false                        |
| skip_certificate_verification       | false                        |
| platform                            | ios                          |
| readonly                            | false                        |
| fail_on_name_taken                  | false                        |
+-------------------------------------+------------------------------+

[18:32:34]: Starting login with user 'REDACTED'
[18:32:36]: Successfully logged in
[18:32:36]: Fetching profiles...
[18:32:37]: Verifying certificates...
[18:32:37]: Found 1 matching profile(s)
[18:32:37]: Downloading provisioning profile...
[18:32:37]: Successfully downloaded provisioning profile...
[18:32:37]: Installing provisioning profile...
/Users/macbookpro/dev/workspaces/smartedv2_frontend/ios/App/builds/provisioning.mobileprovision
[18:32:37]: Setting Provisioning Profile type to 'app-store'
[18:32:37]: -----------------------------------------
[18:32:37]: --- Step: update_project_provisioning ---
[18:32:37]: -----------------------------------------
[18:32:37]: You’re updating provisioning profiles directly in your project, but have you considered easier ways to do code signing?
[18:32:37]: https://docs.fastlane.tools/codesigning/GettingStarted/
[18:32:37]: Parsing mobile provisioning profile from './builds/provisioning.mobileprovision'
[18:32:37]: Going to update project 'App.xcodeproj' with UUID
[18:32:37]: Updating target App...
[18:32:37]: Skipping configuration Debug as it doesn't match the filter 'Release'
[18:32:37]: Updating configuration Release...
[18:32:37]: Successfully updated project settings in 'App.xcodeproj'
[18:32:37]: ---------------------------------
[18:32:37]: --- Step: update_project_team ---
[18:32:37]: ---------------------------------
[18:32:37]: Updating development team (REDACTED) for target `App` in the project 'App.xcodeproj'
[18:32:37]: Successfully updated project settings to use Developer Team ID 'REDACTED' for target `App`
[18:32:37]: -----------------------
[18:32:37]: --- Step: build_app ---
[18:32:37]: -----------------------
[18:32:37]: Resolving Swift Package Manager dependencies...
[18:32:37]: $ xcodebuild -resolvePackageDependencies -workspace App.xcworkspace -scheme App
[18:32:39]: ▸ Command line invocation:
[18:32:39]: ▸     /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -workspace App.xcworkspace -scheme App
[18:32:39]: ▸ User defaults from command line:
[18:32:39]: ▸     IDEPackageSupportUseBuiltinSCM = YES
[18:32:39]: ▸ resolved source packages: 
[18:32:39]: $ xcodebuild -showBuildSettings -workspace App.xcworkspace -scheme App 2>&1
[18:32:42]: Detected provisioning profile mapping: {:"rs.boost"=>"rs.boost AppStore"}

+------------------------------------------------------------------------+
|                        Summary for gym 2.219.0                         |
+----------------------------------------------+-------------------------+
| workspace                                    | App.xcworkspace         |
| scheme                                       | App                     |
| clean                                        | true                    |
| export_method                                | app-store               |
| export_options.provisioningProfiles.rs.boost | rs.boost AppStore       |
| build_path                                   | ./builds                |
| output_directory                             | ./builds                |
| output_name                                  | App                     |
| silent                                       | false                   |
| skip_package_ipa                             | false                   |
| skip_package_pkg                             | false                   |
| result_bundle                                | false                   |
| buildlog_path                                | ~/Library/Logs/gym      |
| destination                                  | generic/platform=iOS    |
| xcodebuild_formatter                         | xcpretty                |
| build_timing_summary                         | false                   |
| skip_profile_detection                       | false                   |
| xcodebuild_command                           | xcodebuild              |
| skip_package_dependencies_resolution         | false                   |
| disable_package_automatic_updates            | false                   |
| use_system_scm                               | false                   |
| xcode_path                                   | /Applications/Xcode.app |
+----------------------------------------------+-------------------------+

[18:32:42]: $ set -o pipefail && xcodebuild -workspace App.xcworkspace -scheme App -destination 'generic/platform=iOS' -archivePath ./builds/App\ 2024-02-13\ 18.32.42.xcarchive clean archive | tee /Users/macbookpro/Library/Logs/gym/App-App.log | xcpretty
[18:32:44]: ▸ Clean Succeeded
[18:32:49]: ▸     Run script build phase '[CP] Embed Pods Frameworks' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'App' from project 'App')
[18:32:49]: ▸ ** ARCHIVE FAILED **
▸ Clean Succeeded
    Run script build phase '[CP] Embed Pods Frameworks' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'App' from project 'App')
** ARCHIVE FAILED **
[18:32:49]: Exit status: 65

+-----------------------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.219.0                 |
| export_method | app-store               |
| sdk           | iPhoneOS17.2.sdk        |
+---------------+-------------------------+

[18:32:49]: ▸ Build description signature: 99e5e439f7681a3eaf194bf0da287938
[18:32:49]: ▸ Build description path: /Users/macbookpro/Library/Developer/Xcode/DerivedData/App-dqqkdgrckwlkgxcvfmrnclczwmvr/Build/Intermediates.noindex/ArchiveIntermediates/App/IntermediateBuildFilesPath/XCBuildData/99e5e439f7681a3eaf194bf0da287938.xcbuilddata
[18:32:49]: ▸ /Users/macbookpro/dev/workspaces/smartedv2_frontend/ios/App/App.xcodeproj: error: App has conflicting provisioning settings. App is automatically signed, but provisioning profile rs.boost AppStore has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor, or switch to manual signing in the Signing & Capabilities editor. (in target 'App' from project 'App')
[18:32:49]: ▸ warning: Run script build phase '[CP] Embed Pods Frameworks' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'App' from project 'App')
[18:32:49]: 
[18:32:49]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[18:32:49]: 📋  For the complete and more detailed error log, check the full log at:
[18:32:49]: 📋  /Users/macbookpro/Library/Logs/gym/App-App.log
[18:32:49]: 
[18:32:49]: Looks like fastlane ran into a build/archive error with your project
[18:32:49]: It's hard to tell what's causing the error, so we wrote some guides on how
[18:32:49]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[18:32:49]: Before submitting an issue on GitHub, please follow the guide above and make
[18:32:49]: sure your project is set up correctly.
[18:32:49]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
[18:32:49]: the full commands printed out in yellow in the above log.
[18:32:49]: Make sure to inspect the output above, as usually you'll find more error information there
[18:32:49]: 
+--------------------------------------------------------------------------------------------------------------------------+
|                                                       Lane Context                                                       |
+---------------------+----------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM    | ios                                                                                                |
| PLATFORM_NAME       | ios                                                                                                |
| LANE_NAME           | ios beta                                                                                           |
| BUILD_NUMBER        | 6                                                                                                  |
| CERT_FILE_PATH      | /Users/macbookpro/dev/workspaces/smartedv2_frontend/ios/App/builds/REDACTED.cer                  |
| CERT_CERTIFICATE_ID | REDACTED                                                                                         |
| SIGH_PROFILE_PATH   | /Users/macbookpro/dev/workspaces/smartedv2_frontend/ios/App/builds/provisioning.mobileprovision    |
| SIGH_PROFILE_PATHS  | ["/Users/macbookpro/dev/workspaces/smartedv2_frontend/ios/App/builds/provisioning.mobileprovision  |
|                     | "]                                                                                                 |
| SIGH_UDID           | a146db58-f5ee-4b9b-8a10-b96e618ead7a                                                               |
| SIGH_UUID           | a146db58-f5ee-4b9b-8a10-b96e618ead7a                                                               |
| SIGH_NAME           | rs.boost AppStore                                                                                  |
| SIGH_PROFILE_TYPE   | app-store                                                                                          |
+---------------------+----------------------------------------------------------------------------------------------------+
[18:32:49]: Error building the application - see the log above

+--------------------------------------------------+
|                 fastlane summary                 |
+------+-----------------------------+-------------+
| Step | Action                      | Time (in s) |
+------+-----------------------------+-------------+
| 1    | default_platform            | 0           |
| 2    | increment_build_number      | 0           |
| 3    | get_certificates            | 4           |
| 4    | get_provisioning_profile    | 2           |
| 5    | update_project_provisioning | 0           |
| 6    | update_project_team         | 0           |
| 💥   | build_app                   | 12          |
+------+-----------------------------+-------------+

[18:32:49]: fastlane finished with errors

[!] Error building the application - see the log above </pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 14.2.1                                      |
| Ruby                        | 3.2.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.39.3 (Apple Git-145)          |
| Installation Source         | ~/.rbenv/versions/3.2.2/bin/fastlane        |
| Host                        | macOS 14.2.1 (23C71)                        |
| Ruby Lib Dir                | ~/.rbenv/versions/3.2.2/lib                 |
| OpenSSL Version             | OpenSSL 3.1.2 1 Aug 2023                    |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 15.2                                        |
| Swift Version               | 5.9.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "App.xcodeproj")
    get_certificates( # Create or get certificate, and install it
      output_path: "./builds" # Download certificate in the build folder (you don't need to create the folder)
    )
    get_provisioning_profile( # Create or get provisioning profile
      output_path: "./builds",  # Download provisioning profile in the build folder
      filename: "provisioning.mobileprovision" # Rename the local provisioning profile
    )
    update_project_provisioning( # Set the project provisioning profile (related in Xcode to the General > Signing Release section)
      xcodeproj: "App.xcodeproj",
      target_filter: "App", # Name of your project
      profile: "./builds/provisioning.mobileprovision",
      build_configuration: "Release"
    )
    update_project_team( # Set the right team on your project
      teamid: CredentialsManager::AppfileConfig.try_fetch_value(:team_id)
    )
    build_app(
      workspace: "App.xcworkspace", 
      scheme: "App", 
      clean: true,
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
            CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier) => CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier) # Value of this parameter is the name of the Provisioning Profile. By default, it will be "{bundleId} AppStore"
        }
      },
      build_path: "./builds",
      output_directory: "./builds")
      upload_to_testflight
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("rs.boost") # The bundle identifier of your app
apple_id("office@pharmasolutions.rs") # Your Apple Developer Portal username

itc_team_id("123232626") # App Store Connect Team ID
team_id("7PSS25J77P") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.219.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.5.1        |
| did_you_mean                    | 1.6.3        |
| syntax_suggest                  | 1.0.2        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| CFPropertyList                  | 3.0.6        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.3       |
| faraday_middleware              | 1.2.0        |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| gh_inspector                    | 1.1.3        |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-cloud-env                | 1.6.0        |
| jwt                             | 2.7.1        |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.10       |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 2.5.0        |
| terminal-table                  | 3.0.2        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| set                             | 1.0.3        |
| public_suffix                   | 5.0.4        |
| addressable                     | 2.8.6        |
| aws-eventstream                 | 1.3.0        |
| aws-sigv4                       | 1.8.0        |
| aws-partitions                  | 1.889.0      |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.191.1      |
| aws-sdk-kms                     | 1.77.0       |
| aws-sdk-s3                      | 1.143.0      |
| bundler                         | 2.4.21       |
| rexml                           | 3.2.6        |
| excon                           | 0.109.0      |
| multipart-post                  | 2.4.0        |
| domain_name                     | 0.6.20240107 |
| fastimage                       | 2.3.0        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| signet                          | 0.18.0       |
| os                              | 1.1.4        |
| googleauth                      | 1.8.1        |
| mini_mime                       | 1.1.5        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.2        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| google-apis-core                | 0.11.3       |
| google-apis-androidpublisher_v3 | 0.54.0       |
| rake                            | 13.1.0       |
| digest-crc                      | 0.6.5        |
| google-apis-storage_v1          | 0.31.0       |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-cloud-errors             | 1.3.1        |
| google-cloud-core               | 1.6.1        |
| google-cloud-storage            | 1.47.0       |
| json                            | 2.7.1        |
| optparse                        | 0.4.0        |
| plist                           | 3.7.1        |
| tty-screen                      | 0.8.2        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.1.0        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.24.0       |
| forwardable                     | 1.3.3        |
| logger                          | 1.5.3        |
| pathname                        | 0.2.1        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.6        |
| date                            | 3.3.3        |
| timeout                         | 0.3.1        |
| securerandom                    | 0.2.2        |
| uri                             | 0.12.1       |
| openssl                         | 3.1.0        |
| digest                          | 3.1.1        |
| ipaddr                          | 1.2.5        |
| resolv                          | 0.2.2        |
| time                            | 0.2.2        |
| stringio                        | 3.0.4        |
| open-uri                        | 0.3.0        |
| mutex_m                         | 0.1.2        |
| net-http                        | 0.3.2        |
| net-protocol                    | 0.2.1        |
| ostruct                         | 0.5.5        |
| english                         | 0.7.2        |
| erb                             | 4.0.2        |
| abbrev                          | 0.1.1        |
| tempfile                        | 0.1.3        |
| delegate                        | 0.3.0        |
| fileutils                       | 1.7.0        |
| tmpdir                          | 0.1.3        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.2        |
| nkf                             | 0.1.2        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.4.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.1        |
| psych                           | 5.0.1        |
</details>

*generated on:* **2024-02-13**
</details> </pre>
</details>

**Comment by lacostej** [comment]
This is probably not a bug in fastlane. I see that you opened a discussion here https://github.com/fastlane/fastlane/discussions/21873, so let's discuss it there.
