### ISSUE TITLE
Fastlane could not find action or lane 'get_certificates'

### ISSUE THREAD

**Issue by multikrd-developer** [fastlane/fastlane#21887]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I have a react-native app automatized in gitlab that was working well until this week that started showing this error:

Could not find action or lane 'get_certificates'. Check out the README for more details: https://github.com/fastlane/fastlane/tree/master/fastlane
+------+--------------------------+-------------+
|               fastlane summary                |
+------+--------------------------+-------------+
| Step | Action                   | Time (in s) |
+------+--------------------------+-------------+
| 1    | default_platform         | 0           |
| 2    | unlock_keychain          | 0           |
| 3    | increment_version_number | 0           |
| 4    | increment_build_number   | 0           |
+------+--------------------------+-------------+
This is the code:

```Dotenv.load ".env"

default_platform(:ios)

platform :ios do

    desc "Push a new beta build to TestFlight"
    lane :build_develop do
        $appBundleIdentifierDev = $identifier
        $workspaceName = $workspace
        $ipaFilename = $filename
        $appleUsername = $username
        $url_repo = $repo

        unlock_keychain(
            path: "login.keychain-db",
            password: ENV['KEYCHAIN_PASS']
        )

        increment_version_number(
            version_number: ENV['APP_VERSION_NAME']
        )

        increment_build_number(
            build_number: ENV['APP_VERSION_CODE']
        )

        get_certificates(
            team_id: $teamid
        )

        gym(
            export_method: 'app-store',
            scheme: $scheme,
            configuration: $configuration,
            clean: true,
            include_bitcode: false,
            workspace: $workspaceName,
            output_name: $ipaFilename,
            xcargs: "ARCHIVE=YES",
            output_directory: "build",
            export_xcargs: "-allowProvisioningUpdates",
        )
    end
end
```
When I check fastlane actions get_certificates is missing in the list.

I didn't change any code in the last days and now it suddenly does not work.

##### Command executed

fastlane get_certificates

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> /Users/multikrdappdeveloper/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-1.92.0/lib/fastlane/runner.rb:101:in `rescue in trigger_action_by_name'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-1.92.0/lib/fastlane/runner.rb:96:in `trigger_action_by_name'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-1.92.0/lib/fastlane/fast_file.rb:140:in `method_missing'
Fastfile:46:in `block (2 levels) in parsing_binding'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-1.92.0/lib/fastlane/lane.rb:33:in `call'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-1.92.0/lib/fastlane/runner.rb:50:in `block in execute'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-1.92.0/lib/fastlane/runner.rb:46:in `chdir'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-1.92.0/lib/fastlane/runner.rb:46:in `execute'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-1.92.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-1.92.0/lib/fastlane/command_line_handler.rb:30:in `handle'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-1.92.0/lib/fastlane/commands_generator.rb:42:in `block (2 levels) in run'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane_core-0.59.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-1.92.0/lib/fastlane/commands_generator.rb:175:in `run'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-1.92.0/lib/fastlane/commands_generator.rb:13:in `start'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-1.92.0/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-1.92.0/bin/fastlane:5:in `<top (required)>'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/bin/fastlane:25:in `load'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/bin/fastlane:25:in `<top (required)>'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:58:in `load'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:58:in `kernel_load'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:23:in `run'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/cli.rb:451:in `exec'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/cli.rb:34:in `dispatch'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/cli.rb:28:in `start'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.5.6/exe/bundle:28:in `block in <top (required)>'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.5.6/exe/bundle:20:in `<top (required)>'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/bin/bundle:25:in `load'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/bin/bundle:25:in `<main>' </pre>
</details>

### Environment

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 12.6.1                                      |
| Ruby                        | 3.1.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.43.2                          |
| Installation Source         | ~/.rbenv/versions/3.1.4/bin/fastlane        |
| Host                        | macOS 12.6.1 (21G217)                       |
| Ruby Lib Dir                | ~/.rbenv/versions/3.1.4/lib                 |
| OpenSSL Version             | OpenSSL 3.1.0 14 Mar 2023                   |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 14.2                                        |
| Swift Version               | 5.7.2                                       |

<details>
  <pre>
### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.219.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| addressable                     | 2.8.6        |
| artifactory                     | 3.0.15       |
| jmespath                        | 1.6.2        |
| aws-partitions                  | 1.893.0      |
| aws-eventstream                 | 1.3.0        |
| aws-sigv4                       | 1.8.0        |
| aws-sdk-core                    | 3.191.2      |
| aws-sdk-kms                     | 1.77.0       |
| aws-sdk-s3                      | 1.143.0      |
| babosa                          | 1.0.4        |
| bundler                         | 2.5.6        |
| CFPropertyList                  | 3.0.7        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.109.0      |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.3       |
| faraday_middleware              | 1.2.0        |
| domain_name                     | 0.6.20240107 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| fastimage                       | 2.3.0        |
| gh_inspector                    | 1.1.3        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| mini_mime                       | 1.1.5        |
| httpclient                      | 2.8.3        |
| google-apis-core                | 0.11.3       |
| google-apis-androidpublisher_v3 | 0.54.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.1        |
| google-cloud-core               | 1.6.1        |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.31.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.5        |
| google-cloud-storage            | 1.47.0       |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.2.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.10       |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 2.5.0        |
| terminal-table                  | 3.0.2        |
| tty-screen                      | 0.8.2        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| atomos                          | 0.1.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.24.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| set                             | 1.0.2        |
| public_suffix                   | 5.0.4        |
| base64                          | 0.2.0        |
| rexml                           | 3.2.6        |
| nkf                             | 0.2.0        |
| multipart-post                  | 2.4.0        |
| uber                            | 0.1.0        |
| retriable                       | 3.1.2        |
| multi_json                      | 1.15.0       |
| jwt                             | 2.8.0        |
| signet                          | 0.19.0       |
| os                              | 1.1.4        |
| googleauth                      | 1.8.1        |
| json                            | 2.6.1        |
| plist                           | 3.7.1        |
| claide                          | 1.1.0        |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.6        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.2.0        |
| uri                             | 0.12.1       |
| openssl                         | 3.0.1        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.2        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-http                        | 0.3.0        |
| net-protocol                    | 0.1.2        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.11       |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.4        |
</details>

*generated on:* **2024-02-21**
 </pre>
</details>

**Comment by lacostej** [comment]
Hello

according to the stack trace, you are running an old version of fastlane (v1.92.0)

```
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/fastlane-1.92.0/bin/fastlane:5:in `'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/bin/fastlane:25:in `load'
/Users/multikrdappdeveloper/.rbenv/versions/3.1.2/bin/fastlane:25:in `'
```

A best practice is to add a `Gemfile` and `Gemfile.lock` version to your project, and run fastlane through `bundle exec fastlane...` to ensure you lock down your build environment.
