### ISSUE TITLE
`fastlane build_app` is trying to access Development provisioning profiles when run for `appstore` only with Github Actions

### ISSUE THREAD

**Issue by RogyMD** [fastlane/fastlane#21891]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Encountered a persistent build failure during fastlane ship_to_testflight due to a provisioning profile mismatch. Despite successful execution of fastlane match, which synchronizes certificates and provisioning profiles correctly, the build_app step fails, erroneously seeking an iOS App Development provisioning profile for '****' instead of the expected App Store Distribution profile. 
Locally everything works well. The problem is only on CI.
I've also installed the provisioning profile locally and everything is alright.
Any help is very much appreciated 🙏🏽 

##### Command executed

```
lane :ship_to_testflight do
    # + 18 is added because xcode cloud already used some build numbers
    increment_build_number(build_number: (ENV["CIRCLE_BUILD_NUM"].to_i + 18).to_s)
    last_merged_pr_body = "test build"
    is_ci = ENV['IS_CI'] == 'true'
    if is_ci
      setup_ci
      app_store_connect_api_key()
    end
    match(
      type: "development",
      readonly: is_ci,
      verbose: true
    )
    match(
      type: "appstore",
      readonly: is_ci,
      verbose: true
    )
    keychainList = sh "security list-keychains"
    puts keychainList
    output = sh "security find-identity -v -p codesigning fastlane_tmp_keychain"
    puts output # Print the output to the console
    build_app(
      scheme: "BestTimer", 
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "*****" => "match AppStore *****",
        }
      },
      verbose: true)
    upload_to_testflight(changelog: last_merged_pr_body)
  end
  ```
##### Complete output when running fastlane, including the stack trace and command used

 [output.txt](https://github.com/fastlane/fastlane/files/14394765/output.txt)

### Environment

<details>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 13.6.4                                           |
| Ruby                        | 3.3.0                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.43.2                               |
| Installation Source         | ~/hostedtoolcache/Ruby/3.3.0/x64/bin/fastlane    |
| Host                        | macOS 13.6.4 (22G513)                            |
| Ruby Lib Dir                | ~/hostedtoolcache/Ruby/3.3.0/x64/lib             |
| OpenSSL Version             | OpenSSL 3.2.0 23 Nov 2023                        |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode_15.2.app/Contents/Developer/ |
| Xcode Version               | 15.2                                             |
| Swift Version               | 5.9.2                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:
| did_you_mean                    | 1.6.3        |
| syntax_suggest                  | 2.0.0        |
| public_suffix                   | 5.0.4        |
| addressable                     | 2.8.6        |
| artifactory                     | 3.0.15       |
| jmespath                        | 1.6.2        |
| aws-partitions                  | 1.892.0      |
| aws-eventstream                 | 1.3.0        |
| aws-sigv4                       | 1.8.0        |
| base64                          | 0.2.0        |
| aws-sdk-core                    | 3.191.2      |
| aws-sdk-kms                     | 1.77.0       |
| aws-sdk-s3                      | 1.143.0      |
| babosa                          | 1.0.4        |
| rexml                           | 3.2.6        |
| CFPropertyList                  | 3.0.7        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.109.0      |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.4.0        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.3       |
| faraday_middleware              | 1.2.0        |
| domain_name                     | 0.6.20240107 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| fastimage                       | 2.3.0        |
| gh_inspector                    | 1.1.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.5        |
| jwt                             | 2.7.1        |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.19.0       |
| googleauth                      | 1.8.1        |
| httpclient                      | 2.8.3        |
| google-apis-core                | 0.11.3       |
| google-apis-androidpublisher_v3 | 0.54.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.1        |
| google-cloud-core               | 1.6.1        |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.31.0       |
| rake                            | 13.1.0       |
| digest-crc                      | 0.6.5        |
| google-cloud-storage            | 1.47.0       |
| json                            | 2.7.1        |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.4.0        |
| plist                           | 3.7.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.10       |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 2.5.0        |
| terminal-table                  | 3.0.2        |
| tty-screen                      | 0.8.2        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| atomos                          | 0.1.3        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.24.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| set                             | 1.1.0        |
| bundler                         | 2.5.6        |
| nkf                             | 0.2.0        |
| forwardable                     | 1.3.3        |
| logger                          | 1.6.0        |
| pathname                        | 0.3.0        |
| shellwords                      | 0.2.0        |
| cgi                             | 0.4.1        |
| date                            | 3.3.4        |
| timeout                         | 0.4.1        |
| securerandom                    | 0.3.1        |
| uri                             | 0.13.0       |
| openssl                         | 3.2.0        |
| digest                          | 3.1.1        |
| ipaddr                          | 1.2.6        |
| resolv                          | 0.3.0        |
| time                            | 0.3.0        |
| stringio                        | 3.1.0        |
| open-uri                        | 0.4.1        |
| mutex_m                         | 0.2.0        |
| net-http                        | 0.4.0        |
| net-protocol                    | 0.2.2        |
| ostruct                         | 0.6.0        |
| english                         | 0.8.0        |
| erb                             | 4.0.3        |
| abbrev                          | 0.1.2        |
| tempfile                        | 0.2.1        |
| delegate                        | 0.3.1        |
| fileutils                       | 1.7.2        |
| tmpdir                          | 0.2.0        |
| singleton                       | 0.2.0        |
| open3                           | 0.2.1        |
| prettyprint                     | 0.2.0        |
| pp                              | 0.5.0        |
| find                            | 0.2.0        |
| yaml                            | 0.3.0        |
| psych                           | 5.1.2        |
</details>

*generated on:* **2024-02-25**
</details>

**Comment by Hamikchandra** [comment]
Thanks for this information.  [hernia surgery](https://drgastro.in/services/)

**Comment by blueelvis** [comment]
@RogyMD - I am facing this exact same issue! I am trying to run the builds on an AWS Mac M1 dedicated host and running into this exact issue. Any chance you found something more on this?

**Comment by RogyMD** [comment]
@blueelvis , not really (( I'm still waiting for help 🤷🏽

**Comment by lacostej** [comment]
Could you check how your xcode project is configured after running the 2 match steps? If you don't have access to the box, just zip the xcode project and archive it as part of the build.

In particular you should follow https://docs.fastlane.tools/codesigning/troubleshooting/

Maybe you configured the project with the wrong signing settings https://docs.fastlane.tools/codesigning/xcode-project

I sometimes use the `update_code_signing_settings` action between `match` and `build_app` to override whatever was set in the project and enforce reproducibility even if the project settings are modified.

**Comment by anirudhsharma392** [comment]
@RogyMD Thanks u just saved my entire day of debugging.

**Comment by france-workmail** [comment]
@RogyMD what part of signing section did you have to remove?
