### ISSUE TITLE
gym export_options : {method} resolves into empty string

### ISSUE THREAD

**Issue by Erodotos** [fastlane/fastlane#21908]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I am using build_app function to build an iOS app. The execution fails due to the following error:

```
There seems to be a mismatch between your provided `export_method` in gym
and the selected provisioning profiles. You passed the following options:
export_method:      
```

The export method seems to be resolved as an empty string or a " " character.

The weird think is that "Summary for gym 2.219.0" shows a correct input with all values completed as expected. For disclosure I tried executing with `method` being "ad-hoc" or "app-store".

Is there any reason for `gym` translating the input to an empty string?

##### Command executed
```
disable_automatic_code_signing(
            team_id: options[:team_id],
            profile_name: options[:provisioning_profile],
            code_sign_identity: options[:code_sign_identity]
        )
```

```
  increment_build_number(
            build_number: ENV["BUILD_NUMBER"]
        )
```

```
build_app(
            derived_data_path: options[:derived_data_path],
            workspace: options[:workspace],
            scheme: options[:scheme],
            include_symbols: true,
            toolchain: "com.guardsquare.ixguard",
            output_directory: options[:output_directory],
            output_name: options[:output_name],
            clean: true,
            codesigning_identity:options[:codesigning_identity],
            export_options: {
                teamID: options[:team_id],
                method: 'app-store'
            }
        )
```

##### Complete output when running fastlane, including the stack trace and command used

```
There seems to be a mismatch between your provided `export_method` in gym
[17:39:20]: and the selected provisioning profiles. You passed the following options:
[17:39:20]:   export_method:      
[17:39:20]:   Bundle identifier:  com.xxxxxxxx.qa
[17:39:20]:   Profile name:       com.xxxxxxxx.qa AppStore
[17:39:20]:   Profile type:       app-store

```

**Comment by Kevin498Vasquez** [comment]
Great post. It was much needed. Love your simplistic style of explanation.

**Comment by Erodotos** [comment]
Removing this line of code solved my issue. 

`codesigning_identity:options[:codesigning_identity],`

Looks like there was double definition of signing identity which was causing the issue

**Comment by Erodotos** [comment]
Removing this line of code solved my issue.

codesigning_identity:options[:codesigning_identity],

Looks like there was double definition of signing identity which was causing the issue
