### ISSUE TITLE
Fastlane `2.219.0` was published without changes.

### ISSUE THREAD

**Issue by ValentynKhylchukTiltingPoint** [fastlane/fastlane#21903]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Fastlane 2.219.0 does not contain changes from 2.219.0 release on github.
While I was attempting to generate provisioning profiles for tvos I got error:

`A parameter 'filter[platform]' has an invalid value : 'Empty filter values are not supported.'`

I did investigation and found that freshly installed Fastlane `2.219.0` does not contain changes (at least some) that are present in release archive.
file: `spaceship/lib/spaceship/connect_api/models/device.rb`
comparison: [https://github.com/fastlane/fastlane/compare/2.219.0...master](https://github.com/fastlane/fastlane/compare/2.219.0...master)

I temporary solved my issue by copying changes from repository info local file.

<details>
<img width="1287" alt="image" src="https://github.com/fastlane/fastlane/assets/81572182/0c8ce1ae-2a3a-4011-bad4-f447ebf66f0f">
</details>

##### Command executed
`sync_code_signing `

<details>
  <pre> 
`/usr/local/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/spaceship/lib/spaceship/connect_api/api_client.rb:218:in `handle_response': [!] { (Spaceship::UnexpectedResponse)
  "errors" : [ {
    "id" : "fbb4d190-2156-4f6a-bf9e-e8f282be46fd",
    "status" : "400",
    "code" : "PARAMETER_ERROR.INVALID",
    "title" : "A parameter has an invalid value",
    "detail" : "A parameter 'filter[platform]' has an invalid value : 'Empty filter values are not supported.'",
    "source" : {
      "parameter" : "filter[platform]"
    }
  } ]
}
	from /usr/local/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/spaceship/lib/spaceship/connect_api/api_client.rb:114:in `get'
	from /usr/local/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/spaceship/lib/spaceship/connect_api/provisioning/client.rb:31:in `get'
	from /usr/local/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/spaceship/lib/spaceship/connect_api/provisioning/provisioning.rb:170:in `get_devices'
	from /usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/forwardable.rb:240:in `get_devices'
	from /usr/local/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/spaceship/lib/spaceship/connect_api/models/device.rb:56:in `all'
	from /usr/local/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/spaceship/lib/spaceship/connect_api/models/device.rb:113:in `devices_for_platform'
	from /usr/local/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/match/lib/match/portal_fetcher.rb:53:in `devices'
	from /usr/local/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/match/lib/match/portal_cache.rb:97:in `devices'
	from /usr/local/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/match/lib/match/generator.rb:110:in `generate_provisioning_profile'
	from /usr/local/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/match/lib/match/runner.rb:279:in `fetch_provisioning_profile'
	from /usr/local/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/match/lib/match/runner.rb:106:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/match/lib/match/runner.rb:105:in `loop'
	from /usr/local/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/match/lib/match/runner.rb:105:in `block in run'
	from /usr/local/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/match/lib/match/runner.rb:104:in `each'
	from /usr/local/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/match/lib/match/runner.rb:104:in `run'
	from /usr/local/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/actions/sync_code_signing.rb:19:in `run'
	from /usr/local/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /usr/local/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /usr/local/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /usr/local/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /usr/local/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:196:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/lane.rb:41:in `call'
	from /usr/local/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /usr/local/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	from /usr/local/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/3.2.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /usr/local/lib/ruby/gems/3.2.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /usr/local/lib/ruby/gems/3.2.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /usr/local/lib/ruby/gems/3.2.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /usr/local/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /usr/local/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /usr/local/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /usr/local/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.2.0/bin/fastlane:25:in `load'
	from /usr/local/lib/ruby/gems/3.2.0/bin/fastlane:25:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:58:in `load'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:23:in `run'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/cli.rb:451:in `exec'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:[127](https://github.com/TiltingPoint/github-actions-ios-provisioning/actions/runs/8098250802/job/22131216720#step:11:128):in `invoke_command'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/cli.rb:34:in `dispatch'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/cli.rb:28:in `start'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/exe/bundle:28:in `block in <top (required)>'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/exe/bundle:20:in `<top (required)>'
	from /usr/local/opt/ruby/bin/bundle:25:in `load'
	from /usr/local/opt/ruby/bin/bundle:25:in `<main>'
Error: Process completed with exit code 1.`
</pre>
</details>

**Comment by lacostej** [comment]
2.219.0 came with the following changes https://github.com/fastlane/fastlane/compare/2.218.0...2.219.0 

The device changes you are pointing to were introduced post 2.219.0, in #21828

If you need to use `master`, which will eventually becomes 2.220.0, use [bundler git repository support](https://bundler.io/guides/git.html).

**Comment by ValentynKhylchukTiltingPoint** [comment]
@lacostej Thank you )
