### ISSUE TITLE
[match] undefined local variable or method `profile` when running match with `output_path`

### ISSUE THREAD

**Issue by TheMetalCode** [fastlane/fastlane#21945]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: 2.220.0
- Last working version: 2.219.0

### Regression Description

As of the 2.220.0 release, I'm unable to run `match` in CI. Near as I can tell, I hit a `undefined local variable or method `profile`` simply on account of using the `output_path` option.

```bash
/Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.220.0/match/lib/match/runner.rb:359:in `fetch_provisioning_profile': [!] undefined local variable or method `profile' for #<Match::Runner:0x0000000111f9dd48 @files_to_commit=[], @files_to_delete=[], @storage=#<Match::Storage::GitStorage:0x0000000112037308 @git_url=REDACTED, @shallow_clone=true, @skip_docs=false, @branch="master", @git_full_name=nil, @git_user_email=nil, @clone_branch_directly=false, @git_basic_authorization=nil, @git_bearer_authorization=nil, @git_private_key=nil, @type="adhoc", @platform="ios", @working_directory=nil>> (NameError)

        installed_profile = FastlaneCore::ProvisioningProfile.install(profile, keychain_path)
                                                                      ^^^^^^^
Did you mean?  profiles
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.220.0/match/lib/match/runner.rb:108:in `block (2 levels) in run'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.220.0/match/lib/match/runner.rb:107:in `loop'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.220.0/match/lib/match/runner.rb:107:in `block in run'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.220.0/match/lib/match/runner.rb:106:in `each'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.220.0/match/lib/match/runner.rb:106:in `run'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/actions/sync_code_signing.rb:19:in `run'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        from Fastfile:433:in `block (2 levels) in parsing_binding'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/lane.rb:41:in `call'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        from Fastfile:181:in `block (2 levels) in parsing_binding'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/lane.rb:41:in `call'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.220.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/commands_generator.rb:363:in `run'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.220.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.220.0/bin/fastlane:23:in `<top (required)>'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bin/fastlane:25:in `load'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bin/fastlane:25:in `<top (required)>'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.4/lib/bundler/cli/exec.rb:58:in `load'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.4/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.4/lib/bundler/cli/exec.rb:23:in `run'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.4/lib/bundler/cli.rb:451:in `exec'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.4/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.4/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.4/lib/bundler/cli.rb:34:in `dispatch'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.4/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.4/lib/bundler/cli.rb:28:in `start'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.4/exe/bundle:28:in `block in <top (required)>'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.4/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /Users/jhagglund/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.5.4/exe/bundle:20:in `<top (required)>'
        from /Users/jhagglund/.rbenv/versions/3.2.2/bin/bundle:25:in `load'
        from /Users/jhagglund/.rbenv/versions/3.2.2/bin/bundle:25:in `<main>'
```

Relevant match action:

```ruby
 match(
      git_url: REDACTED,
      type: "adhoc",
      app_identifier: REDACTED
      force_for_new_devices: true,
      include_all_certificates: true,
      force_for_new_certificates: true,
      shallow_clone: true,
      readonly: true,
      output_path: "/tmp/match_certs",
      keychain_name: REDACTED
    )
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>### Captured Output

Command Used: `adhoc_build --capture_output`
<details><summary>Output/Log</summary>

```

DEBUG [2024-04-04 10:39:13.06]: Checking if there are any plugins that should be loaded...
DEBUG [2024-04-04 10:39:13.07]: Loading 'fastlane-plugin-firebase_app_distribution' plugin
INFO [2024-04-04 10:39:13.07]: gem 'fastlane-plugin-firebase_app_distribution' is already installed
DEBUG [2024-04-04 10:39:13.09]: Loading 'fastlane-plugin-bugsnag' plugin
INFO [2024-04-04 10:39:13.09]: gem 'fastlane-plugin-bugsnag' is already installed


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                    |
| --------------------------- | -------------------------------------------------------- |
| OS                          | 14.4.1                                                   |
| Ruby                        | 3.2.2                                                    |
| Bundler?                    | true                                                     |
| Git                         | git version 2.44.0                                       |
| Installation Source         | ~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bin/fastlane |
| Host                        | macOS 14.4.1 (23E224)                                    |
| Ruby Lib Dir                | ~/.rbenv/versions/3.2.2/lib                              |
| OpenSSL Version             | OpenSSL 1.1.1w  11 Sep 2023                              |
| Is contained                | false                                                    |
| Is homebrew                 | false                                                    |
| Is installed via Fabric.app | false                                                    |
| Xcode Path                  | /Applications/Xcode-15.3.0.app/Contents/Developer/       |
| Xcode Version               | 15.3                                                     |
| Swift Version               | 5.10                                                     |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.220.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status  |
| ----------------------------------------- | ------- | -------------- |
| fastlane-plugin-firebase_app_distribution | 0.9.0   | ✅ Up-To-Date   |
| fastlane-plugin-bugsnag                   | 2.3.0   | ✅ Up-To-Date   |

<details><summary><b>Loaded gems</b></summary>

| Gem                                         | Version      |
| ------------------------------------------- | ------------ |
| error_highlight                             | 0.5.1        |
| did_you_mean                                | 1.6.3        |
| syntax_suggest                              | 1.0.2        |
| bundler                                     | 2.5.4        |
| pathname                                    | 0.2.1        |
| rake                                        | 13.2.0       |
| base64                                      | 0.2.0        |
| nkf                                         | 0.2.0        |
| rexml                                       | 3.2.6        |
| CFPropertyList                              | 3.0.7        |
| public_suffix                               | 5.0.5        |
| addressable                                 | 2.8.6        |
| artifactory                                 | 3.0.17       |
| atomos                                      | 0.1.3        |
| aws-eventstream                             | 1.3.0        |
| aws-partitions                              | 1.907.0      |
| aws-sigv4                                   | 1.8.0        |
| jmespath                                    | 1.6.2        |
| aws-sdk-core                                | 3.191.6      |
| aws-sdk-kms                                 | 1.78.0       |
| aws-sdk-s3                                  | 1.146.1      |
| babosa                                      | 1.0.4        |
| claide                                      | 1.1.0        |
| climate_control                             | 1.2.0        |
| colored                                     | 1.2          |
| colored2                                    | 3.1.2        |
| highline                                    | 2.0.3        |
| commander                                   | 4.6.0        |
| declarative                                 | 0.0.20       |
| digest-crc                                  | 0.6.5        |
| domain_name                                 | 0.6.20240107 |
| dotenv                                      | 2.8.1        |
| emoji_regex                                 | 3.2.3        |
| excon                                       | 0.110.0      |
| faraday-em_http                             | 1.0.0        |
| faraday-em_synchrony                        | 1.0.0        |
| faraday-excon                               | 1.1.0        |
| faraday-httpclient                          | 1.0.1        |
| multipart-post                              | 2.4.0        |
| faraday-multipart                           | 1.0.4        |
| faraday-net_http                            | 1.0.1        |
| faraday-net_http_persistent                 | 1.2.0        |
| faraday-patron                              | 1.0.0        |
| faraday-rack                                | 1.0.0        |
| faraday-retry                               | 1.0.3        |
| ruby2_keywords                              | 0.0.5        |
| faraday                                     | 1.10.3       |
| http-cookie                                 | 1.0.5        |
| faraday-cookie_jar                          | 0.0.7        |
| faraday_middleware                          | 1.2.0        |
| fastimage                                   | 2.3.1        |
| gh_inspector                                | 1.1.3        |
| jwt                                         | 2.8.1        |
| multi_json                                  | 1.15.0       |
| os                                          | 1.1.4        |
| signet                                      | 0.19.0       |
| googleauth                                  | 1.8.1        |
| httpclient                                  | 2.8.3        |
| mini_mime                                   | 1.1.5        |
| trailblazer-option                          | 0.1.2        |
| uber                                        | 0.1.0        |
| representable                               | 3.2.0        |
| retriable                                   | 3.1.2        |
| google-apis-core                            | 0.11.3       |
| google-apis-androidpublisher_v3             | 0.54.0       |
| google-apis-playcustomapp_v1                | 0.13.0       |
| google-cloud-env                            | 1.6.0        |
| google-apis-iamcredentials_v1               | 0.17.0       |
| google-apis-storage_v1                      | 0.31.0       |
| google-cloud-errors                         | 1.4.0        |
| google-cloud-core                           | 1.7.0        |
| google-cloud-storage                        | 1.47.0       |
| json                                        | 2.7.2        |
| mini_magick                                 | 4.12.0       |
| naturally                                   | 2.2.1        |
| optparse                                    | 0.4.0        |
| plist                                       | 3.7.1        |
| rubyzip                                     | 2.3.2        |
| security                                    | 0.1.5        |
| simctl                                      | 1.6.10       |
| terminal-notifier                           | 2.0.0        |
| unicode-display_width                       | 2.5.0        |
| terminal-table                              | 3.0.2        |
| tty-screen                                  | 0.8.2        |
| tty-cursor                                  | 0.7.1        |
| tty-spinner                                 | 0.9.3        |
| word_wrap                                   | 1.0.0        |
| nanaimo                                     | 0.3.0        |
| xcodeproj                                   | 1.24.0       |
| rouge                                       | 2.0.7        |
| xcpretty                                    | 0.3.0        |
| xcpretty-travis-formatter                   | 1.0.1        |
| rchardet                                    | 1.8.0        |
| git                                         | 1.19.1       |
| xml-simple                                  | 1.1.9        |
| fastlane-plugin-bugsnag                     | 2.3.0        |
| options                                     | 2.3.2        |
| progress_bar                                | 1.3.3        |
| terrapin                                    | 1.0.1        |
| google-apis-firebaseappdistribution_v1      | 0.3.0        |
| google-apis-firebaseappdistribution_v1alpha | 0.2.0        |
| fastlane-plugin-firebase_app_distribution   | 0.9.0        |
| table_print                                 | 1.5.7        |
</details>

*generated on:* **2024-04-04**
</details></pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                    |
| --------------------------- | -------------------------------------------------------- |
| OS                          | 14.4.1                                                   |
| Ruby                        | 3.2.2                                                    |
| Bundler?                    | true                                                     |
| Git                         | git version 2.44.0                                       |
| Installation Source         | ~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bin/fastlane |
| Host                        | macOS 14.4.1 (23E224)                                    |
| Ruby Lib Dir                | ~/.rbenv/versions/3.2.2/lib                              |
| OpenSSL Version             | OpenSSL 1.1.1w  11 Sep 2023                              |
| Is contained                | false                                                    |
| Is homebrew                 | false                                                    |
| Is installed via Fabric.app | false                                                    |
| Xcode Path                  | /Applications/Xcode-15.3.0.app/Contents/Developer/       |
| Xcode Version               | 15.3                                                     |
| Swift Version               | 5.10                                                     |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.220.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status  |
| ----------------------------------------- | ------- | -------------- |
| fastlane-plugin-firebase_app_distribution | 0.9.0   | ✅ Up-To-Date   |
| fastlane-plugin-bugsnag                   | 2.3.0   | ✅ Up-To-Date   |

<details><summary><b>Loaded gems</b></summary>

| Gem                                         | Version      |
| ------------------------------------------- | ------------ |
| error_highlight                             | 0.5.1        |
| did_you_mean                                | 1.6.3        |
| syntax_suggest                              | 1.0.2        |
| bundler                                     | 2.5.4        |
| pathname                                    | 0.2.1        |
| rake                                        | 13.2.0       |
| base64                                      | 0.2.0        |
| nkf                                         | 0.2.0        |
| rexml                                       | 3.2.6        |
| CFPropertyList                              | 3.0.7        |
| public_suffix                               | 5.0.5        |
| addressable                                 | 2.8.6        |
| artifactory                                 | 3.0.17       |
| atomos                                      | 0.1.3        |
| aws-eventstream                             | 1.3.0        |
| aws-partitions                              | 1.907.0      |
| aws-sigv4                                   | 1.8.0        |
| jmespath                                    | 1.6.2        |
| aws-sdk-core                                | 3.191.6      |
| aws-sdk-kms                                 | 1.78.0       |
| aws-sdk-s3                                  | 1.146.1      |
| babosa                                      | 1.0.4        |
| claide                                      | 1.1.0        |
| climate_control                             | 1.2.0        |
| colored                                     | 1.2          |
| colored2                                    | 3.1.2        |
| highline                                    | 2.0.3        |
| commander                                   | 4.6.0        |
| declarative                                 | 0.0.20       |
| digest-crc                                  | 0.6.5        |
| domain_name                                 | 0.6.20240107 |
| dotenv                                      | 2.8.1        |
| emoji_regex                                 | 3.2.3        |
| excon                                       | 0.110.0      |
| faraday-em_http                             | 1.0.0        |
| faraday-em_synchrony                        | 1.0.0        |
| faraday-excon                               | 1.1.0        |
| faraday-httpclient                          | 1.0.1        |
| multipart-post                              | 2.4.0        |
| faraday-multipart                           | 1.0.4        |
| faraday-net_http                            | 1.0.1        |
| faraday-net_http_persistent                 | 1.2.0        |
| faraday-patron                              | 1.0.0        |
| faraday-rack                                | 1.0.0        |
| faraday-retry                               | 1.0.3        |
| ruby2_keywords                              | 0.0.5        |
| faraday                                     | 1.10.3       |
| http-cookie                                 | 1.0.5        |
| faraday-cookie_jar                          | 0.0.7        |
| faraday_middleware                          | 1.2.0        |
| fastimage                                   | 2.3.1        |
| gh_inspector                                | 1.1.3        |
| jwt                                         | 2.8.1        |
| multi_json                                  | 1.15.0       |
| os                                          | 1.1.4        |
| signet                                      | 0.19.0       |
| googleauth                                  | 1.8.1        |
| httpclient                                  | 2.8.3        |
| mini_mime                                   | 1.1.5        |
| trailblazer-option                          | 0.1.2        |
| uber                                        | 0.1.0        |
| representable                               | 3.2.0        |
| retriable                                   | 3.1.2        |
| google-apis-core                            | 0.11.3       |
| google-apis-androidpublisher_v3             | 0.54.0       |
| google-apis-playcustomapp_v1                | 0.13.0       |
| google-cloud-env                            | 1.6.0        |
| google-apis-iamcredentials_v1               | 0.17.0       |
| google-apis-storage_v1                      | 0.31.0       |
| google-cloud-errors                         | 1.4.0        |
| google-cloud-core                           | 1.7.0        |
| google-cloud-storage                        | 1.47.0       |
| json                                        | 2.7.2        |
| mini_magick                                 | 4.12.0       |
| naturally                                   | 2.2.1        |
| optparse                                    | 0.4.0        |
| plist                                       | 3.7.1        |
| rubyzip                                     | 2.3.2        |
| security                                    | 0.1.5        |
| simctl                                      | 1.6.10       |
| terminal-notifier                           | 2.0.0        |
| unicode-display_width                       | 2.5.0        |
| terminal-table                              | 3.0.2        |
| tty-screen                                  | 0.8.2        |
| tty-cursor                                  | 0.7.1        |
| tty-spinner                                 | 0.9.3        |
| word_wrap                                   | 1.0.0        |
| nanaimo                                     | 0.3.0        |
| xcodeproj                                   | 1.24.0       |
| rouge                                       | 2.0.7        |
| xcpretty                                    | 0.3.0        |
| xcpretty-travis-formatter                   | 1.0.1        |
| rchardet                                    | 1.8.0        |
| git                                         | 1.19.1       |
| xml-simple                                  | 1.1.9        |
| fastlane-plugin-bugsnag                     | 2.3.0        |
| options                                     | 2.3.2        |
| progress_bar                                | 1.3.3        |
| terrapin                                    | 1.0.1        |
| google-apis-firebaseappdistribution_v1      | 0.3.0        |
| google-apis-firebaseappdistribution_v1alpha | 0.2.0        |
| fastlane-plugin-firebase_app_distribution   | 0.9.0        |
| table_print                                 | 1.5.7        |
</details>

*generated on:* **2024-04-04**
</details></pre>
</details>

**Comment by TheMetalCode** [comment]
@nekrich This would seem to have been introduced here: https://github.com/fastlane/fastlane/pull/21691/files#diff-8cd09d7ab3f4398e3160f603839ac2891e3cdf60e7f09930a1288ce33ab8fc1fR359

**Comment by afern247** [comment]
I've been scratching my head all morning trying to see what was the problem, I'm glad I'm not the only one or the runner.

Can someone please add a fix for this? Deployment is paused because of this

**Comment by TheMetalCode** [comment]
@afern247 I would say the short term fix is to pin to fastlane 2.219.0 and not use the latest version until this is resolved.

I did open https://github.com/fastlane/fastlane/pull/21946 but it's in draft mode because I had questions about the code that caused the error.

**Comment by TheMetalCode** [comment]
https://github.com/fastlane/fastlane/pull/21946 is now ready for review

**Comment by tiennguyen1203** [comment]
Hi guys, anyone here? I still got the issue.

I'm running it on self-hosted (MacBook M1 Pro) github action.

**Comment by jakub-przy** [comment]
Same issue with match on my end as well (still)

**Comment by mortenholmgaard** [comment]
I have the same issue

**Comment by kasa-ailleron** [comment]
I have the same problem on my end as well
