### ISSUE TITLE
Individual API Key not supported

### ISSUE THREAD

**Issue by palmerc** [fastlane/fastlane#21959]
### Issue Description
Attempted to use an Individual API Key for the Account Holder to manage the Developer ID Certificate.  It is not possible to do so through a regular API Key.

##### Command executed
match with JSON key path

##### Complete output when running fastlane, including the stack trace and command used
```
[!] The request could not be completed because:
	Authentication credentials are missing or invalid. - Provide a properly configured and signed bearer token, and make sure that it has not expired. Learn more about Generating Tokens for API Requests https://developer.apple.com/go/?id=api-generating-tokens
```

**Comment by Darionti88** [comment]
I'm experiencing the same issue with `fastlane@2.220.0`. Normal Team API Key worked perfectly, but if I try to use an individual Key it fails on the `upload_to_tesflight` step.
`app_store_connect_api_key` step does not throw any error.
This is the error I get if I run with `--verbose`
```
Authentication credentials are missing or invalid. - Provide a properly configured and signed bearer token, and make sure that it has not expired. Learn more about Generating Tokens for API Requests https://developer.apple.com/go/?id=api-generating-tokens
Token has expired, issued-at-time is in the future, or has been revoked! Trying to refresh...
```

**Comment by mitchboettcher** [comment]
The process for generating a token from an Individual API Key is a little different, so the `app_store_connect_api_key` step will probably need changes. The important difference is that Individual API Keys don't use the `iss` key in the JWT payload, and requires the `sub` key instead.

https://developer.apple.com/documentation/appstoreconnectapi/generating_tokens_for_api_requests

**Comment by FapL0rd** [comment]
same issue here

**Comment by airmikec** [comment]
_### **_Azure DevOps API Key Issues for deploying to Apple_**_
To get this to successfully work on Azure DevOps Pipeline with an API Key. I ran into so many problems and tried everything I could find and this finally worked.  Azure DevOps says you need use the base64 key.  Well if you open up the .p8 and copy the base64 encoded string in there, that isn't what they want.  They literally want you to copy all of the contenxt in the .p8 file to a base64 string. Don't modify the .p8 file.  I found the solution at the follow source, and once you get the data.b64 file open it and copy the base64 string in that file.  In the following article is discusses how to do this for Windows, Mac, and Ubuntu.

https://github.com/fastlane/fastlane/issues/21531#issuecomment-1873633417

**Comment by neorth** [comment]
Did you manage to upload builds using an individual API key? If I omit issuer_id I get an error from altool: 
`[altool] 2024-06-11 09:56:44.263 *** Error: Unable to upload archive. You must specify both '--apiKey' and '--apiIssuer'. (-1011)`
Adding back issuer_id gives me an authentication error instead:
`[altool] 2024-06-11 10:20:08.361 *** Error: Unable to upload archive. Failed to authenticate for session`
I get a feeling uploading apps using an individual API key isn't supported?

**Comment by manicmaniac** [comment]
@neorth 

> I get a feeling uploading apps using an individual API key isn't supported?

Currently, spaceship supports individual API key but deliver doesn't.

See https://github.com/fastlane/fastlane/issues/22115 for the detail.

**Comment by neorth** [comment]
@manicmaniac 

I was trying to upload to Testflight (using the pilot command). Got an official response from Apple that altool (that's used by pilot) doesn't support individual API keys: https://forums.developer.apple.com/forums/thread/756929

I guess spaceship and/or deliver dosn't support uploading to Testflight?

**Comment by manicmaniac** [comment]
@neorth 

> I guess spaceship and/or deliver dosn't support uploading to Testflight?

Although `altool` doesn't seem to support Individual API Keys, it is possible to upload builds using an app specific password.
The above issue (#22115) shows how to do this as a workaround.

**Comment by airmikec** [comment]
I did use an individual API key, using the direction I posted above.

**Comment by manicmaniac** [comment]
@neorth

Right now I opened a draft PR to resolve the issue. #22128

However I think it needs some more testing in real world so I will do it in the next some weeks.
If you want to use deliver or pilot with Individual API Key soon, try it and give me feedback, thank you.

**Comment by neorth** [comment]
That's great news, good job! I will be on vacation for the next few weeks and unfortunately won't be able to test until late July at the earliest.

**Comment by OdNairy** [comment]
The `match` and `sigh` – two another tools that do not support individual keys yet

**Comment by manicmaniac** [comment]
I've tested https://github.com/fastlane/fastlane/pull/22128 and the test passed. The PR is now ready for review.

**Comment by Valentin-Rault** [comment]
Do we have a timeline on when the other tools (`match`, `sigh`) are going to support individual key?
