### ISSUE TITLE
JEG2/highline should be updated to avoid warning of abbrev missing in standard lib for ruby 3.3.0

### ISSUE THREAD

**Issue by einar-notland** [fastlane/fastlane#21962]
### New Issue Checklist

- [ x ] Updated fastlane to the latest version
- [ x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I get this warning, stating that `abbrev` is no longer part of standard library in ruby 3.3.0. 

[⠹] 🚀 /opt/homebrew/lib/ruby/gems/3.3.0/gems/highline-2.0.3/lib/highline.rb:17: warning: abbrev was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add abbrev to your Gemfile or gemspec. Also contact author of highline-2.0.3 to add abbrev into its gemspec.

This has been resolved by removing abbrev in JEG2/highline v3.0.1 (See commit: https://github.com/JEG2/highline/pull/268/commits/29f25e10e78754883cbd1fcd1b0cc102877570bd)

Any chance highline dependency can be updated?

##### Command executed
fastlane

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>% fastlane
   [✔] 🚀 /opt/homebrew/lib/ruby/gems/3.3.0/gems/highline-2.0.3/lib/highline.rb:17: warning: abbrev was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add abbrev to your Gemfile or gemspec. Also contact author of highline-2.0.3 to add abbrev into its gemspec.
+-------------------------------------------------------------------------------------------------------------------+
|                                                   Used plugins                                                    |
+-------------------------------------------+---------+-------------------------------------------------------------+
| Plugin                                    | Version | Action                                                      |
+-------------------------------------------+---------+-------------------------------------------------------------+
| fastlane-plugin-appcenter                 | 2.1.1   | appcenter_codepush_release_react, appcenter_fetch_devices,  |
|                                           |         | appcenter_fetch_version_number, appcenter_upload            |
| fastlane-plugin-update_build_settings_key | 0.1.3   | update_build_settings_key                                   |
+-------------------------------------------+---------+-------------------------------------------------------------+
 </pre>
</details>

### Environment

<details>
  <pre> [⠙] 🚀 /opt/homebrew/lib/ruby/gems/3.3.0/gems/httpclient-2.8.3/lib/httpclient/auth.rb:11: warning: mutex_m was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add mutex_m to your Gemfile or gemspec. Also contact author of httpclient-2.8.3 to add mutex_m into its gemspec.
[⠼] 🚀 /opt/homebrew/lib/ruby/gems/3.3.0/gems/highline-2.0.3/lib/highline.rb:17: warning: abbrev was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add abbrev to your Gemfile or gemspec. Also contact author of highline-2.0.3 to add abbrev into its gemspec.
[✔] 🚀 
[08:28:50]: Generating fastlane environment output, this might take a few seconds...
/opt/homebrew/lib/ruby/gems/3.3.0/gems/fastlane-plugin-appcenter-2.1.1/lib/fastlane/plugin/appcenter/actions/appcenter_fetch_devices_action.rb:2: warning: csv was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add csv to your Gemfile or gemspec. Also contact author of fastlane-plugin-appcenter-2.1.1 to add csv into its gemspec.
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                          |
| --------------------------- | ---------------------------------------------- |
| OS                          | 14.4.1                                         |
| Ruby                        | 3.3.0                                          |
| Bundler?                    | true                                           |
| Git                         | git version 2.39.3 (Apple Git-146)             |
| Installation Source         | /opt/homebrew/lib/ruby/gems/3.3.0/bin/fastlane |
| Host                        | macOS 14.4.1 (23E224)                          |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.3.0/lib            |
| OpenSSL Version             | OpenSSL 3.2.0 23 Nov 2023                      |
| Is contained                | false                                          |
| Is homebrew                 | false                                          |
| Is installed via Fabric.app | false                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/    |
| Xcode Version               | 15.3                                           |
| Swift Version               | 5.10                                           |

 </pre>
</details>

**Comment by TheMetalCode** [comment]
What might make this non-trivial is that `highline` 2.x is not only [a direct dependency](https://github.com/fastlane/fastlane/blob/master/fastlane.gemspec#L92), but a downstream one of `commander` 4.6: 
- https://github.com/fastlane/fastlane/blob/master/fastlane.gemspec#L79|
- https://rubygems.org/gems/commander/versions/4.6.0

In my experience though, there is no harm done by adding `abbrev` directly to your `Gemfile` alongside `fastlane`.

**Comment by peterkos** [comment]
Wouldn't the ideal solution here be to update `highline` to no longer be a major version out of date? Looks like it's now on v3.0.1: https://rubygems.org/gems/highline/

**Comment by bartekpacia** [comment]
[Latest `commander` depends on highline 3.0](https://github.com/commander-rb/commander/blob/98dee54912730397d06eca9132dbfd2ec3bbd4b0/commander.gemspec#L29).

I agree with @peterkos above; it's worth updating.

**Comment by vanniktech** [comment]
My build is also failing, so yes, this should be reopened.

```
        FastlaneCore::UpdateChecker.show_update_status('fastlane', Fastlane::VERSION)
                    ^^^^^^^^^^^^^^^
	from /Users/niklas/.gem/ruby/3.3.0/gems/fastlane-2.226.0/bin/fastlane:23:in '<top (required)>'
	from /Users/niklas/.gem/ruby/3.3.0/bin/fastlane:25:in 'Kernel#load'
	from /Users/niklas/.gem/ruby/3.3.0/bin/fastlane:25:in '<top (required)>'
	from /Users/niklas/.gem/ruby/3.3.0/gems/bundler-2.5.23/lib/bundler/cli/exec.rb:58:in 'Kernel.load'
	from /Users/niklas/.gem/ruby/3.3.0/gems/bundler-2.5.23/lib/bundler/cli/exec.rb:58:in 'Bundler::CLI::Exec#kernel_load'
	from /Users/niklas/.gem/ruby/3.3.0/gems/bundler-2.5.23/lib/bundler/cli/exec.rb:23:in 'Bundler::CLI::Exec#run'
	from /Users/niklas/.gem/ruby/3.3.0/gems/bundler-2.5.23/lib/bundler/cli.rb:456:in 'Bundler::CLI#exec'
	from /Users/niklas/.gem/ruby/3.3.0/gems/bundler-2.5.23/lib/bundler/vendor/thor/lib/thor/command.rb:28:in 'Bundler::Thor::Command#run'
	from /Users/niklas/.gem/ruby/3.3.0/gems/bundler-2.5.23/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in 'Bundler::Thor::Invocation#invoke_command'
	from /Users/niklas/.gem/ruby/3.3.0/gems/bundler-2.5.23/lib/bundler/vendor/thor/lib/thor.rb:527:in 'Bundler::Thor.dispatch'
	from /Users/niklas/.gem/ruby/3.3.0/gems/bundler-2.5.23/lib/bundler/cli.rb:35:in 'Bundler::CLI.dispatch'
	from /Users/niklas/.gem/ruby/3.3.0/gems/bundler-2.5.23/lib/bundler/vendor/thor/lib/thor/base.rb:584:in 'Bundler::Thor::Base::ClassMethods#start'
	from /Users/niklas/.gem/ruby/3.3.0/gems/bundler-2.5.23/lib/bundler/cli.rb:29:in 'Bundler::CLI.start'
	from /Users/niklas/.gem/ruby/3.3.0/gems/bundler-2.5.23/exe/bundle:28:in 'block in <top (required)>'
	from /Users/niklas/.gem/ruby/3.3.0/gems/bundler-2.5.23/lib/bundler/friendly_errors.rb:117:in 'Bundler.with_friendly_errors'
	from /Users/niklas/.gem/ruby/3.3.0/gems/bundler-2.5.23/exe/bundle:20:in '<top (required)>'
	from /opt/homebrew/bin/bundle:25:in 'Kernel#load'
	from /opt/homebrew/bin/bundle:25:in '<main>'
/opt/homebrew/Cellar/ruby/3.4.1/lib/ruby/3.4.0/bundled_gems.rb:82:in 'Kernel.require': cannot load such file -- abbrev (LoadError)
```

**Comment by vanniktech** [comment]
This is what you need:

```
source "https://rubygems.org"

gem "fastlane", "2.226.0"
gem "abbrev"
gem "mutex_m"
```

With those, fastlane is working for me again.

**Comment by giaotuancse** [comment]
> This is what you need:
> 
> ```
> source "https://rubygems.org"
> 
> gem "fastlane", "2.226.0"
> gem "abbrev"
> gem "mutex_m"
> ```
> 
> With those, fastlane is working for me again.

Can you share your env here? Is it working with ruby 3.4.1?
