### ISSUE TITLE
Can fastlane support filling in China’s ICP registration number?

### ISSUE THREAD

**Issue by JohnRyanTsai** [fastlane/fastlane#21981]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

Currently, apps in mainland China need to fill in the ICP registration number before being put on the App Store. Can fastlane support automatic filling in?

**Comment by david265d** [comment]
Thanks for sharing. I found a lot of interesting information here.

**Comment by max-ott** [comment]
Feel free to open a pull request and I’m more than happy to review it.
