### ISSUE TITLE
iOS: The specified resource does not exist - There is no resource of type 'AppsV1' with id '...' when passing changelog

### ISSUE THREAD

**Issue by ir-fuel** [fastlane/fastlane#22037]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When uploading a build to testflight, and passing a changelog, the build is correctly uploaded, however applying the changelog fails with the following error:

```
 The specified resource does not exist - There is no resource of type 'AppsV1' with id '.....'
```

##### Command executed

```
    changelog = File.read("../Changelog.txt")

    upload_to_testflight(
      changelog: changelog,
      username: "----",
      apple_id: "----",
      skip_waiting_for_build_processing: false,
      skip_submission: true  # only upload
    )

```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 14.4.1                                      |
| Ruby                        | 2.7.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.39.3 (Apple Git-146)          |
| Installation Source         | ~/.rbenv/versions/2.7.2/bin/fastlane        |
| Host                        | macOS 14.4.1 (23E224)                       |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.2/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 15.4                                        |
| Swift Version               | 5.10                                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  
  desc "Push a new test build to TestFlight"
  lane :test do
    
    # setup_ci()
    
   # app_store_connect_api_key()
    
    
    match(
      type:"appstore",
      readonly: true
    )

    increment_build_number(xcodeproj: "***.xcodeproj")
    
    build_ios_app(
      scheme: "***",
      configuration: "Release",
      clean: true
    )
    
    changelog = File.read("../Changelog.txt")

    upload_to_testflight(
      changelog: changelog,
      username: "***@***.com",
      apple_id: "***",
      skip_waiting_for_build_processing: false,
      skip_submission: true  # only upload
    )
    
    commit_version_bump(
      message:"[skip ci] version bump",
      force: true,
      xcodeproj: "***.xcodeproj"
    )
    
    add_git_tag

    push_to_git_remote
    
    create_pull_request(
      repo: "***/***",
      title: "Version Bump"
    )    
  end
  

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("***") # The bundle identifier of your app
apple_id("***") # Your Apple email address
team_id("***")
itc_team_id("***")

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.220.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                        | Version | Update-Status |
| ----------------------------- | ------- | ------------- |
| fastlane-plugin-github_action | 1.0.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.6.1        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| emoji_regex                     | 3.2.3        |
| faraday_middleware              | 1.2.0        |
| faraday-cookie_jar              | 0.0.7        |
| gh_inspector                    | 1.1.3        |
| google-cloud-env                | 1.6.0        |
| http-cookie                     | 1.0.5        |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.5        |
| terminal-notifier               | 2.0.0        |
| terminal-table                  | 3.0.2        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| uri                             | 0.11.0       |
| public_suffix                   | 5.0.4        |
| addressable                     | 2.8.5        |
| aws-eventstream                 | 1.3.0        |
| aws-sigv4                       | 1.7.0        |
| aws-partitions                  | 1.859.0      |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.188.0      |
| aws-sdk-kms                     | 1.73.0       |
| aws-sdk-s3                      | 1.140.0      |
| bundler                         | 2.3.20       |
| rexml                           | 3.2.6        |
| CFPropertyList                  | 3.0.6        |
| dotenv                          | 2.8.1        |
| excon                           | 0.104.0      |
| ruby2_keywords                  | 0.0.5        |
| faraday-retry                   | 1.0.3        |
| faraday-rack                    | 1.0.0        |
| faraday-patron                  | 1.0.0        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-net_http                | 1.0.1        |
| multipart-post                  | 2.3.0        |
| faraday-multipart               | 1.0.4        |
| faraday-httpclient              | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.10.3       |
| fastimage                       | 2.2.7        |
| webrick                         | 1.8.1        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| jwt                             | 2.7.1        |
| signet                          | 0.18.0       |
| os                              | 1.1.4        |
| googleauth                      | 1.8.1        |
| mini_mime                       | 1.1.5        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.2        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| google-apis-core                | 0.11.2       |
| google-apis-androidpublisher_v3 | 0.53.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| rake                            | 13.1.0       |
| digest-crc                      | 0.6.5        |
| google-apis-storage_v1          | 0.29.0       |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-cloud-errors             | 1.3.1        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.45.0       |
| domain_name                     | 0.6.20231109 |
| json                            | 2.6.3        |
| mini_magick                     | 4.12.0       |
| optparse                        | 0.2.0        |
| plist                           | 3.7.0        |
| simctl                          | 1.6.10       |
| unicode-display_width           | 2.5.0        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.1.0        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.23.0       |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.1        |
| cgi                             | 0.3.2        |
| date                            | 3.2.2        |
| timeout                         | 0.3.0        |
| stringio                        | 3.0.2        |
| openssl                         | 3.0.0        |
| ipaddr                          | 1.2.4        |
| zlib                            | 2.1.1        |
| mutex_m                         | 0.1.1        |
| connection_pool                 | 2.2.5        |
| net-http-persistent             | 4.0.1        |
| patron                          | 0.13.3       |
| ostruct                         | 0.5.5        |
| strscan                         | 3.0.4        |
| io-console                      | 0.5.11       |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| rbnacl                          | 7.1.1        |
| ffi                             | 1.15.5       |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nokogiri                        | 1.13.8       |
| racc                            | 1.6.0        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.4        |
| sshkey                          | 2.0.0        |
| fastlane-plugin-github_action   | 1.0.0        |
</details>

*generated on:* **2024-05-17**
</details></pre>
</details>

### Environment

<details>
  <pre><details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 14.4.1                                      |
| Ruby                        | 2.7.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.39.3 (Apple Git-146)          |
| Installation Source         | ~/.rbenv/versions/2.7.2/bin/fastlane        |
| Host                        | macOS 14.4.1 (23E224)                       |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.2/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 15.4                                        |
| Swift Version               | 5.10                                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new acceptance build to TestFlight"
  lane :acceptance do
    
    # setup_ci()
    
   # app_store_connect_api_key()
    
    
    match(
      type:"appstore",
      readonly: true
    )

    increment_build_number(xcodeproj: "DKV.xcodeproj")
    
    build_ios_app(
      scheme: "DKVAcceptance",
      configuration: "Release",
      clean: true
    )

    changelog = File.read("../Changelog.txt")
    
    upload_to_testflight(
      changelog: changelog,
      username: "technical@devside.com",
      apple_id: "1541803697",
      skip_waiting_for_build_processing: true,
      skip_submission: true  # only upload
    )
    
    commit_version_bump(
      message:"[skip ci] version bump",
      force: true,
      xcodeproj: "DKV.xcodeproj"
    )
    
    add_git_tag

    push_to_git_remote
    
    create_pull_request(
      repo: "DKV-Belgium/dkv-ios",
      title: "Version Bump"
    )    
  end

  desc "Push a new test build to TestFlight"
  lane :test do
    
    # setup_ci()
    
   # app_store_connect_api_key()
    
    
    match(
      type:"appstore",
      readonly: true
    )

    increment_build_number(xcodeproj: "DKV.xcodeproj")
    
    build_ios_app(
      scheme: "DKVTest",
      configuration: "Release",
      clean: true
    )
    
    changelog = File.read("../Changelog.txt")

    upload_to_testflight(
      changelog: changelog,
      username: "technical@devside.com",
      apple_id: "1541803697",
      skip_waiting_for_build_processing: false,
      skip_submission: true  # only upload
    )
    
    commit_version_bump(
      message:"[skip ci] version bump",
      force: true,
      xcodeproj: "DKV.xcodeproj"
    )
    
    add_git_tag

    push_to_git_remote
    
    create_pull_request(
      repo: "DKV-Belgium/dkv-ios",
      title: "Version Bump"
    )    
  end
  
  desc "Push a new release build to TestFlight"
  lane :release do
    
#    setup_ci()
    
 #  app_store_connect_api_key()
    
    
    match(
      type:"appstore",
      readonly: true
    )

    increment_build_number(xcodeproj: "DKV.xcodeproj")
    
    build_ios_app(
      scheme: "DKV",
      configuration: "Release",
      clean: true
    )
    
    upload_to_testflight(
      username: "technical@devside.com",
      apple_id: "1541803697",
      skip_waiting_for_build_processing: true,
      skip_submission: true  # only upload
    )
    
    commit_version_bump(
      message:"[skip ci] version bump",
      force: true,
      xcodeproj: "DKV.xcodeproj"
    )
    
    add_git_tag

    push_to_git_remote
    
    create_pull_request(
      repo: "DKV-Belgium/dkv-ios",
      title: "Version Bump"
    )    
  end
  
  lane :certificates do
    match(app_identifier: ["be.dkv.dkvbelgium"], type:"development", force_for_new_devices: true)
    match(app_identifier: ["be.dkv.dkvbelgium"], type:"appstore")
    match(app_identifier: ["be.dkv.dkvacceptance"], type:"development", force_for_new_devices: true)
    match(app_identifier: ["be.dkv.dkvacceptance"], type:"appstore")
    match(app_identifier: ["be.dkv.dkvtest"], type:"development", force_for_new_devices: true)
    match(app_identifier: ["be.dkv.dkvtest"], type:"appstore")
  end
  
  lane :nuke do
    match_nuke(app_identifier: ["be.dkv.dkvbelgium"], type:"development")
    match_nuke(app_identifier: ["be.dkv.dkvbelgium"], type:"appstore")
    match_nuke(app_identifier: ["be.dkv.dkvacceptance"], type:"development")
    match_nuke(app_identifier: ["be.dkv.dkvacceptance"], type:"appstore")
    match_nuke(app_identifier: ["be.dkv.dkvtest"], type:"development")
    match_nuke(app_identifier: ["be.dkv.dkvtest"], type:"appstore")
  end  
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("be.dkv.dkvbelgium") # The bundle identifier of your app
apple_id("technical@devside.com") # Your Apple email address
team_id("4WL2RK6QU3")
itc_team_id("105255801")

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.220.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                        | Version | Update-Status |
| ----------------------------- | ------- | ------------- |
| fastlane-plugin-github_action | 1.0.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.6.1        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| emoji_regex                     | 3.2.3        |
| faraday_middleware              | 1.2.0        |
| faraday-cookie_jar              | 0.0.7        |
| gh_inspector                    | 1.1.3        |
| google-cloud-env                | 1.6.0        |
| http-cookie                     | 1.0.5        |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.5        |
| terminal-notifier               | 2.0.0        |
| terminal-table                  | 3.0.2        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| uri                             | 0.11.0       |
| public_suffix                   | 5.0.4        |
| addressable                     | 2.8.5        |
| aws-eventstream                 | 1.3.0        |
| aws-sigv4                       | 1.7.0        |
| aws-partitions                  | 1.859.0      |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.188.0      |
| aws-sdk-kms                     | 1.73.0       |
| aws-sdk-s3                      | 1.140.0      |
| bundler                         | 2.3.20       |
| rexml                           | 3.2.6        |
| CFPropertyList                  | 3.0.6        |
| dotenv                          | 2.8.1        |
| excon                           | 0.104.0      |
| ruby2_keywords                  | 0.0.5        |
| faraday-retry                   | 1.0.3        |
| faraday-rack                    | 1.0.0        |
| faraday-patron                  | 1.0.0        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-net_http                | 1.0.1        |
| multipart-post                  | 2.3.0        |
| faraday-multipart               | 1.0.4        |
| faraday-httpclient              | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.10.3       |
| fastimage                       | 2.2.7        |
| webrick                         | 1.8.1        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| jwt                             | 2.7.1        |
| signet                          | 0.18.0       |
| os                              | 1.1.4        |
| googleauth                      | 1.8.1        |
| mini_mime                       | 1.1.5        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.2        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| google-apis-core                | 0.11.2       |
| google-apis-androidpublisher_v3 | 0.53.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| rake                            | 13.1.0       |
| digest-crc                      | 0.6.5        |
| google-apis-storage_v1          | 0.29.0       |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-cloud-errors             | 1.3.1        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.45.0       |
| domain_name                     | 0.6.20231109 |
| json                            | 2.6.3        |
| mini_magick                     | 4.12.0       |
| optparse                        | 0.2.0        |
| plist                           | 3.7.0        |
| simctl                          | 1.6.10       |
| unicode-display_width           | 2.5.0        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.1.0        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.23.0       |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.1        |
| cgi                             | 0.3.2        |
| date                            | 3.2.2        |
| timeout                         | 0.3.0        |
| stringio                        | 3.0.2        |
| openssl                         | 3.0.0        |
| ipaddr                          | 1.2.4        |
| zlib                            | 2.1.1        |
| mutex_m                         | 0.1.1        |
| connection_pool                 | 2.2.5        |
| net-http-persistent             | 4.0.1        |
| patron                          | 0.13.3       |
| ostruct                         | 0.5.5        |
| strscan                         | 3.0.4        |
| io-console                      | 0.5.11       |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| rbnacl                          | 7.1.1        |
| ffi                             | 1.15.5       |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nokogiri                        | 1.13.8       |
| racc                            | 1.6.0        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.4        |
| sshkey                          | 2.0.0        |
| fastlane-plugin-github_action   | 1.0.0        |
</details>

*generated on:* **2024-05-17**
</details></pre>
</details>

**Comment by hilary687** [comment]
It seems like this issue has been encountered by others using fastlane. One user reported that adding demo account details resolved the error. Check if all required fields are filled in your App Store Connect account. For more detailed troubleshooting, you can refer to the fastlane documentation or seek help on their GitHub issues page

**Comment by ir-fuel** [comment]
@max-ott what resolves this issue?

**Comment by max-ott** [comment]
See the above comment
