### ISSUE TITLE
🐛 Fastlane `sh` with `log:false` replacing `step_name` to `Step: shell command` instead of step_name parameter

### ISSUE THREAD

**Issue by flixyudh** [fastlane/fastlane#22072]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Currently, everytime I passing `log:false` into `sh` actions, the `step_name` didn't show the message I've set

example lane:

```ruby
desc 'Listing Directory'
lane:wakwaw do |options|
  sh(
    "ls",
    step_name:"\e[1;94mList current directory\e[0m"
  )
end
```

showing output:

```
Driving the lane 'wakwaw' 🚀
-----------------------------------------------
--- Step: List current directory ---
-----------------------------------------------
$ ls
**List of directory in cwd**
fastlane.tools finished successfully 🎉
```

but when I add `log:false` like this:

```ruby
desc 'Listing Directory'
lane:wakwaw do |options|
  sh(
    "ls",
    step_name:"\e[1;94mList current directory\e[0m",
    log:false
  )
end
```

the output of Step name seems to use default value `Step: shell command`

```bash
Driving the lane 'wakwaw' 🚀
---------------------------
--- Step: shell command ---
---------------------------
fastlane.tools finished successfully 🎉
```

I expecting the Step name output should use `step_name` value even when the `log` parameter is passed.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by mollyIV** [comment]
Hi @flixyudh , 

thanks for reporting the issue. I implemented the fix: https://github.com/fastlane/fastlane/pull/22151

Feel free to take it for a spin. Just point your `fastlane` to the branch with the fix: 

```ruby
// Gemfile

gem 'fastlane', git: 'https://github.com/fastlane/fastlane.git', branch: 'sh-log-false-step-name'
```

**Comment by mollyIV** [comment]
The fix has been merged 🚀  Closing the ticket.
