### ISSUE TITLE
Fastlane snapshot doesn't work on iOS

### ISSUE THREAD

**Issue by StanislavHT** [fastlane/fastlane#22109]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Command executed

```
bundle exec fastlane snapshot
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
      [09:28:39]: ▸ Loading...
      [09:28:41]: ▸ 2024-06-26 09:28:41.494 xcodebuild[36567:747887] Writing error result bundle to /var/folders/ql/6nqcs2nd68n3bvxg0q5fbgg40000gn/T/ResultBundle_2024-26-06_09-28-0041.xcresult
      [09:28:42]: ▸ xcodebuild: error: Unable to find a destination matching the provided destination specifier:
      [09:28:42]: ▸ 		{ platform:iOS Simulator, OS:17.5, name:iPhone 15 }
      2024-06-26 09:28:41.494 xcodebuild[36567:747887] Writing error result bundle to /var/folders/ql/6nqcs2nd68n3bvxg0q5fbgg40000gn/T/ResultBundle_2024-26-06_09-28-0041.xcresult
      xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		      { platform:iOS Simulator, OS:17.5, name:iPhone 15 }
      [09:28:42]: Exit status: 70
      [09:28:42]: Tests failed while running on: iPhone 15, iPhone 15 Plus, iPhone 15 Pro, iPhone 15 Pro Max, iPad Air (5th generation)
      [09:28:42]: For more detail about the test failures, check the logs here:
      [09:28:42]: /Users/achilles/Library/Logs/snapshot/App-first_responder_fcUITests.log
  </pre>
</details>

### Environment

<details>
  <pre>
    <summary>✅ fastlane environment ✅</summary>
    
    ### Stack
    
    | Key                         | Value                                                                |
    | --------------------------- | -------------------------------------------------------------------- |
    | OS                          | 14.5                                                                 |
    | Ruby                        | 3.3.2                                                                |
    | Bundler?                    | true                                                                 |
    | Git                         | git version 2.43.1                                                   |
    | Installation Source         | ~/xx/xx/vendor/bundle/ruby/3.3.0/bin/fastlane |
    | Host                        | macOS 14.5 (23F79)                                                   |
    | Ruby Lib Dir                | ~/.rbenv/versions/3.3.2/lib                                          |
    | OpenSSL Version             | OpenSSL 3.3.1 4 Jun 2024                                             |
    | Is contained                | false                                                                |
    | Is homebrew                 | false                                                                |
    | Is installed via Fabric.app | false                                                                |
    | Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                          |
    | Xcode Version               | 15.4                                                                 |
    | Swift Version               | 5.10                                                                 |
    
    
    ### System Locale
    
    | Variable | Value       |   |
    | -------- | ----------- | - |
    | LANG     | en_US.UTF-8 | ✅ |
    | LC_ALL   |             |   |
    | LANGUAGE |             |   |
    
    
    ### fastlane files:
    
    <summary>`./fastlane/Fastfile`</summary>
    
    ```ruby
    # This file contains the fastlane.tools configuration
    # You can find the documentation at https://docs.fastlane.tools
    #
    # For a list of all available actions, check out
    #
    #     https://docs.fastlane.tools/actions
    #
    # For a list of all available plugins, check out
    #
    #     https://docs.fastlane.tools/plugins/available-plugins
    #
    
    # Uncomment the line if you want fastlane to automatically update itself
    # update_fastlane
    
    default_platform(:ios)
    
    platform :ios do
        desc "Install certificates, provisioning profiles"
        lane :install_certificates do
            match(type: "development", readonly: true)
            match(type: "appstore", readonly: true)
        end
    
        desc "Push a new beta build to TestFlight"
        lane :beta do
            if ENV["STAGE"] == "dev"
                # We are updating patch version to easily check which app version users use.
                # increment_build_number(xcodeproj: "xx.xcodeproj")
                increment_version_number_in_xcodeproj(
                    bump_type: "patch",
                    xcodeproj: "xx.xcodeproj"
                )
            end
            build_app(
                workspace: "xx.xcworkspace",
                scheme: "xx",
                export_method: "app-store",
                export_options: {
                    provisioningProfiles: {
                        ENV["APP_IDENTIFIER"] => "match AppStore " + ENV["APP_IDENTIFIER"],
                        ENV["APP_IDENTIFIER"] + ".ImageNotification" => "match AppStore " + ENV["APP_IDENTIFIER"] + ".ImageNotification",
                    }
                }
            )
            upload_to_testflight
        end
    end
    
    ```
    
    <summary>`./fastlane/Appfile`</summary>
    
    ```ruby
    app_identifier(ENV["APP_IDENTIFIER"]) # The bundle identifier of your app
    apple_id("xx@xx.com") # Your Apple Developer Portal username
    
    itc_team_id(ENV["ITC_TEAM_ID"]) # App Store Connect Team ID
    team_id(ENV["TEAM_ID"]) # Developer Portal Team ID
    
    # For more information about the Appfile, see:
    #     https://docs.fastlane.tools/advanced/#appfile
    
    ```
    
    ### fastlane gems
    
    | Gem      | Version | Update-Status |
    | -------- | ------- | ------------- |
    | fastlane | 2.221.1 | ✅ Up-To-Date  |
    
    
    ### Loaded fastlane plugins:
    
    | Plugin                     | Version | Update-Status |
    | -------------------------- | ------- | ------------- |
    | fastlane-plugin-versioning | 0.5.2   | ✅ Up-To-Date  |
    
    
    <summary><b>Loaded gems</b></summary>
    
    | Gem                             | Version      |
    | ------------------------------- | ------------ |
    | error_highlight                 | 0.6.0        |
    | did_you_mean                    | 1.6.3        |
    | syntax_suggest                  | 2.0.0        |
    | bundler                         | 2.5.11       |
    | pathname                        | 0.3.0        |
    | rake                            | 13.2.1       |
    | base64                          | 0.2.0        |
    | nkf                             | 0.2.0        |
    | strscan                         | 3.1.0        |
    | rexml                           | 3.2.9        |
    | CFPropertyList                  | 3.0.7        |
    | concurrent-ruby                 | 1.3.3        |
    | i18n                            | 1.14.5       |
    | minitest                        | 5.23.1       |
    | tzinfo                          | 2.0.6        |
    | activesupport                   | 7.0.8.4      |
    | public_suffix                   | 4.0.7        |
    | addressable                     | 2.8.6        |
    | httpclient                      | 2.8.3        |
    | json                            | 2.7.2        |
    | algoliasearch                   | 1.27.5       |
    | artifactory                     | 3.0.17       |
    | atomos                          | 0.1.3        |
    | aws-eventstream                 | 1.3.0        |
    | aws-partitions                  | 1.946.0      |
    | aws-sigv4                       | 1.8.0        |
    | jmespath                        | 1.6.2        |
    | aws-sdk-core                    | 3.197.2      |
    | aws-sdk-kms                     | 1.85.0       |
    | aws-sdk-s3                      | 1.152.3      |
    | babosa                          | 1.0.4        |
    | claide                          | 1.1.0        |
    | fuzzy_match                     | 2.0.4        |
    | nap                             | 1.1.0        |
    | netrc                           | 0.11.0       |
    | ffi                             | 1.17.0       |
    | ethon                           | 0.16.0       |
    | typhoeus                        | 1.4.1        |
    | cocoapods-core                  | 1.15.2       |
    | cocoapods-deintegrate           | 1.0.5        |
    | cocoapods-downloader            | 2.1          |
    | cocoapods-plugins               | 1.0.0        |
    | cocoapods-search                | 1.0.1        |
    | cocoapods-trunk                 | 1.6.0        |
    | cocoapods-try                   | 1.2.0        |
    | colored2                        | 3.1.2        |
    | escape                          | 0.0.4        |
    | fourflusher                     | 2.3.1        |
    | gh_inspector                    | 1.1.3        |
    | molinillo                       | 0.8.0        |
    | ruby-macho                      | 2.5.1        |
    | nanaimo                         | 0.3.0        |
    | xcodeproj                       | 1.24.0       |
    | cocoapods                       | 1.15.2       |
    | colored                         | 1.2          |
    | highline                        | 2.0.3        |
    | commander                       | 4.6.0        |
    | declarative                     | 0.0.20       |
    | digest-crc                      | 0.6.5        |
    | domain_name                     | 0.6.20240107 |
    | dotenv                          | 2.8.1        |
    | emoji_regex                     | 3.2.3        |
    | excon                           | 0.110.0      |
    | faraday-em_http                 | 1.0.0        |
    | faraday-em_synchrony            | 1.0.0        |
    | faraday-excon                   | 1.1.0        |
    | faraday-httpclient              | 1.0.1        |
    | multipart-post                  | 2.4.1        |
    | faraday-multipart               | 1.0.4        |
    | faraday-net_http                | 1.0.1        |
    | faraday-net_http_persistent     | 1.2.0        |
    | faraday-patron                  | 1.0.0        |
    | faraday-rack                    | 1.0.0        |
    | faraday-retry                   | 1.0.3        |
    | ruby2_keywords                  | 0.0.5        |
    | faraday                         | 1.10.3       |
    | http-cookie                     | 1.0.6        |
    | faraday-cookie_jar              | 0.0.7        |
    | faraday_middleware              | 1.2.0        |
    | fastimage                       | 2.3.1        |
    | jwt                             | 2.8.2        |
    | multi_json                      | 1.15.0       |
    | os                              | 1.1.4        |
    | signet                          | 0.19.0       |
    | googleauth                      | 1.8.1        |
    | mini_mime                       | 1.1.5        |
    | trailblazer-option              | 0.1.2        |
    | uber                            | 0.1.0        |
    | representable                   | 3.2.0        |
    | retriable                       | 3.1.2        |
    | google-apis-core                | 0.11.3       |
    | google-apis-androidpublisher_v3 | 0.54.0       |
    | google-apis-playcustomapp_v1    | 0.13.0       |
    | google-cloud-env                | 1.6.0        |
    | google-apis-iamcredentials_v1   | 0.17.0       |
    | google-apis-storage_v1          | 0.31.0       |
    | google-cloud-errors             | 1.4.0        |
    | google-cloud-core               | 1.7.0        |
    | google-cloud-storage            | 1.47.0       |
    | mini_magick                     | 4.13.1       |
    | naturally                       | 2.2.1        |
    | optparse                        | 0.5.0        |
    | plist                           | 3.7.1        |
    | rubyzip                         | 2.3.2        |
    | security                        | 0.1.5        |
    | simctl                          | 1.6.10       |
    | terminal-notifier               | 2.0.0        |
    | unicode-display_width           | 2.5.0        |
    | terminal-table                  | 3.0.2        |
    | tty-screen                      | 0.8.2        |
    | tty-cursor                      | 0.7.1        |
    | tty-spinner                     | 0.9.3        |
    | word_wrap                       | 1.0.0        |
    | rouge                           | 2.0.7        |
    | xcpretty                        | 0.3.0        |
    | xcpretty-travis-formatter       | 1.0.1        |
    | fastlane-plugin-versioning      | 0.5.2        |
  </pre>
</details>

**Comment by StanislavHT** [comment]
I could upload iOS app to TestFlight using `bundle exec fastlane ios beta` command, but not sure why `snapshot` command doesn't work.

**Comment by g-campbell** [comment]
Have you attempted the resolution found in this issue: https://github.com/fastlane/fastlane/issues/21382

**Comment by StanislavHT** [comment]
It was a stupid mistake.
We are using different bundle ids, when create target for UI tests, I used wrong bundle id.

**Comment by muhasturk** [comment]
I've same issue. Xcode UI Test target builds and runs without any problem on Xcode itself. However;

When I run 
```
bundle exec fastlane snapshot
```

Fastlane gives following error
```
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
[01:22:44]: ▸ 		{ platform:iOS Simulator, OS:17.5, name:iPhone 15 Pro Max }
[01:22:44]: Exit status: 70
```

But I already have a specified destination on the machine so
```
xcrun simctl list

iPhone 15 Pro Max (3D813EB9-F8CD-4F5E-B0FF-C1B41A4270DA) (Booted)
```

iOS 17.5 platform already installed
![Screenshot 2024-06-28 at 01 24 37](https://github.com/fastlane/fastlane/assets/4077401/aad3e18d-3395-4cd0-95e0-23366be36061)


### Snapfile
```
+-------------------------------------------------------------------------------------------+
|                               Summary for snapshot 2.221.1                                |
+--------------------------------------+----------------------------------------------------+
| project                              | ./AutoMeta.xcodeproj                               |
| devices                              | ["iPhone 15 Pro Max"]                              |
| languages                            | ["en-US", "tr-TR"]                                 |
| launch_arguments                     | [""]                                               |
| output_directory                     | /Users/hasturk/Documents/Code/autometa/screenshots |
| output_simulator_logs                | false                                              |
| skip_open_summary                    | false                                              |
| skip_helper_version_check            | false                                              |
| clear_previous_screenshots           | true                                               |
| reinstall_app                        | false                                              |
| erase_simulator                      | false                                              |
| headless                             | true                                               |
| override_status_bar                  | true                                               |
| localize_simulator                   | false                                              |
| app_identifier                       | dev.hasturk.autometa                               |
| buildlog_path                        | ~/Library/Logs/snapshot                            |
| clean                                | false                                              |
| scheme                               | AutoMetaUITests                                    |
| number_of_retries                    | 1                                                  |
| stop_after_first_error               | false                                              |
| result_bundle                        | false                                              |
| concurrent_simulators                | true                                               |
| disable_slide_to_type                | false                                              |
| skip_package_dependencies_resolution | false                                              |
| disable_package_automatic_updates    | false                                              |
| xcodebuild_formatter                 | xcpretty                                           |
| use_system_scm                       | false                                              |
| xcode_path                           | /Applications/Xcode-15.4.0.app                     |
+--------------------------------------+----------------------------------------------------+
```
### Env
Xcode Version 15.4 (15F31d)


**I thinks there is a some problem with fastlane snapshot, it can not detect the given destination**
