### ISSUE TITLE
[spaceship] update_availability using Deprecated API

### ISSUE THREAD

**Issue by mic-ioki** [fastlane/fastlane#22123]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I tried running the command below on the Spaceship playground. The Spaceship `tunes_client` uses deprecated ASC API which does not exist anymore.

##### Command executed

```
app = Spaceship::ConnectAPI.get_app(app_id: <app-id>).first
availability = Spaceship::Tunes::Availability.from_territories(["US"])
Spaceship::AppVersion.client.update_availability!(app.id, availability)
```

##### Complete output when running fastlane, including the stack trace and command used

```
Spaceship::UnexpectedResponse: <?xml version="1.0" encoding="UTF-8"?>
<String>There is no route for the path 'apps/<app-id>/pricing/intervals'.</String>

from /Users/<username>/.gem/gems/fastlane-2.221.1/spaceship/lib/spaceship/client.rb:793:in `parse_response'
```

**Comment by monixca345** [comment]
Ohk i want to know more

**Comment by max-ott** [comment]
Feel free to check out https://github.com/fastlane/fastlane/pull/22243/files as a first pointer. Always appreciating pull requests that add this functionality.
