### ISSUE TITLE
[!] Google Api Error: Invalid request - You must let us know whether your app includes any health features

### ISSUE THREAD

**Issue by Marcus-Hurlbut** [fastlane/fastlane#22204]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
After making the declaration in Google Play Console's App Content, where I stated my Flutter app does not use any health features, I still receive this error. This issue does not occur if I manually build the application & submit it to the Google playstore OR manually submit the app build that fastlane creates in this script (this is currently how we're still keeping the app updated). 

Additionally, the google publishing API calls that are failing 100% of the time in this scenario are google.play.publishingapi.v3.EditService.Commit & google.play.publishingapi.v3.EditService.Validate. I've tried reaching out to Google regarding this, but they are unable to assist due to this occuring within fastlane. We've been experiencing this issue for a couple weeks now & still having trouble getting past what might be causing it. 

Listed below is the output of fastlane env with some potential sensitive data removed.

##### Command executed
`upload_to_playstore`

##### Complete output when running fastlane, including the stack trace and command used
[10:33:34]: Validating all changes with Google Play...
+--------------------------------------------------------------+
|                         Lane Context                         |
+-------------------------------------+------------------------+
| DEFAULT_PLATFORM                    | android                |
| PLATFORM_NAME                       | android                |
| LANE_NAME                           | android internal_track |
| GRADLE_BUILD_TYPE                   | Release                |
| GRADLE_ALL_APK_OUTPUT_PATHS         | []                     |
| GRADLE_ALL_AAB_OUTPUT_PATHS         | []                     |
| GRADLE_ALL_OUTPUT_JSON_OUTPUT_PATHS | []                     |
| GRADLE_ALL_MAPPING_TXT_OUTPUT_PATHS | []                     |
+-------------------------------------+------------------------+
[10:33:35]: Called from Fastfile at line 75
[10:33:35]: ```
[10:33:35]:     73:	    build_release_aab()
[10:33:35]:     74:	
[10:33:35]:  => 75:	    upload_to_play_store(
[10:33:35]:     76:	      validate_only: true,
[10:33:35]:     77:	      track: 'internal',
[10:33:35]: ```
[10:33:35]: Google Api Error: Invalid request - You must let us know whether your app includes any health features.
+------------------------------------------------------------------------------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | default_platform                                              | 0           |
| 2    | Switch to android build_release_aab lane                      | 0           |
| 3    | Switch to android prepare lane                                | 0           |
| 4    | fastlane update_fastlane                                      | 9           |
| 5    | flutter clean                                                 | 3           |
| 6    | flutter channel stable                                        | 21          |
| 7    | flutter pub get                                               | 29          |
| 8    | flutter pub upgrade win32                                     | 3           |
| 9    | flutter pub upgrade flutter_mailer                            | 3           |
| 10   | flutter pub upgrade                                           | 17          |
| 11   | rm -rf C:\Users\Builder\Gitlab-Runner\builds\yAmf3ZFVB\0\ | 0           |
| 12   | flutter build appbundle                                       | 398         |
| 13   | cd ../                                                        | 0           |
| 14   | bundleRelease                                                 | 205         |
| 💥   | upload_to_play_store                                          | 49          |
+------+---------------------------------------------------------------+-------------+
[10:33:35]: fastlane finished with errors
[!] Google Api Error: Invalid request - You must let us know whether your app includes any health features.
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit status 1

### Environment

<details><summary>✅ fastlane environment ✅</summary> 

### Stack

| Key                         | Value                                      |
| --------------------------- | ------------------------------------------ |
| OS                          | UNKNOWN                                    |
| Ruby                        | 3.2.3                                      |
| Bundler?                    | false                                      |
| Git                         | git version 2.15.1.windows.2.1.g603511c649 |
| Installation Source         | C:/Ruby32-x64/bin/fastlane                 |
| Host                        | Unknown  ()                                |
| Ruby Lib Dir                | C:/Ruby32-x64/lib                          |
| OpenSSL Version             | OpenSSL 3.2.0 23 Nov 2023                  |
| Is contained                | false                                      |
| Is homebrew                 | false                                      |
| Is installed via Fabric.app | false                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |                                                                                                                                                     
| LC_ALL   | en_US.UTF-8 | ✅ |                                                                                                                                                     
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform(:android)

platform :android do
  desc "Build Signed Release AAB"
  lane :build_release_aab do
    prepare()
    sh("flutter build appbundle")
    sh("cd ../")
    gradle(task: 'bundle', build_type: 'Release')
  end

  desc "Build & Deply to Play Store - Internal Track"
  lane :internal_track do
    build_release_aab()

    upload_to_play_store(
      validate_only: true,
      json_key: "C:\\Users\\Builder\\fastlane_json_key.json",
      track: 'internal',
      package_name: "<package-name>",
      skip_upload_apk: true,
      changes_not_sent_for_review: true,
      version_code: get_version_code(),
      aab: aab_file_path(),
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("<json-key-filepath>")
package_name("<package-name")

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.222.0 | ✅ Up-To-Date  |                                                                                                                                             

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.5.1        |
| did_you_mean                    | 1.6.3        |
| syntax_suggest                  | 1.1.0        |
| public_suffix                   | 5.0.5        |
| addressable                     | 2.8.6        |
| artifactory                     | 3.0.17       |
| jmespath                        | 1.6.2        |
| aws-partitions                  | 1.913.0      |
| aws-eventstream                 | 1.3.0        |
| aws-sdk-core                    | 3.191.6      |
| aws-sdk-kms                     | 1.78.0       |
| aws-sdk-s3                      | 1.146.1      |
| babosa                          | 1.0.4        |
| bundler                         | 2.4.19       |
| rexml                           | 3.2.5        |
| nkf                             | 0.1.2        |
| base64                          | 0.1.1        |
| CFPropertyList                  | 3.0.7        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.110.0      |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.4.0        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.3       |
| faraday_middleware              | 1.2.0        |
| domain_name                     | 0.6.20240107 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| fastimage                       | 2.3.1        |
| gh_inspector                    | 1.1.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.5        |
| jwt                             | 2.8.1        |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.19.0       |
| googleauth                      | 1.8.1        |
| httpclient                      | 2.8.3        |
| google-apis-core                | 0.11.3       |
| google-apis-androidpublisher_v3 | 0.54.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.4.0        |
| google-cloud-core               | 1.7.0        |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.31.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.5        |
| google-cloud-storage            | 1.47.0       |
| json                            | 2.6.3        |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.3.1        |
| plist                           | 3.7.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.5        |
| simctl                          | 1.6.10       |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 2.5.0        |
| terminal-table                  | 3.0.2        |
| tty-screen                      | 0.8.2        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| atomos                          | 0.1.3        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.24.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| set                             | 1.0.3        |
| aws-sigv4                       | 1.9.1        |
| forwardable                     | 1.3.3        |
| logger                          | 1.5.3        |
| pathname                        | 0.2.1        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.6        |
| date                            | 3.3.3        |
| timeout                         | 0.3.1        |
| securerandom                    | 0.2.2        |
| uri                             | 0.12.2       |
| openssl                         | 3.1.0        |
| digest                          | 3.1.1        |
| ipaddr                          | 1.2.5        |
| resolv                          | 0.2.2        |
| fiddle                          | 1.1.1        |
| time                            | 0.2.2        |
| stringio                        | 3.0.4        |
| open-uri                        | 0.3.0        |
| mutex_m                         | 0.1.2        |
| net-http                        | 0.4.1        |
| net-protocol                    | 0.2.1        |
| ostruct                         | 0.5.5        |
| english                         | 0.7.2        |
| erb                             | 4.0.2        |
| abbrev                          | 0.1.1        |
| tempfile                        | 0.1.3        |
| delegate                        | 0.3.0        |
| fileutils                       | 1.7.0        |
| tmpdir                          | 0.1.3        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.2        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.4.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.1        |
| psych                           | 5.0.1        |
</details>

*generated on:* **2024-08-27**
</details>

**Comment by Marcus-Hurlbut** [comment]
I have confirmed that we do have the Health Apps declaration complete in the app content section of the app. 

Although, from the link you sent, I found a sub-link that lists the other permissions in the health apps scope (including ACTIVITY_RECOGNITION): https://support.google.com/googleplay/android-developer/answer/13996367?sjid=10541869973483384753-NC#zippy=%2Cwhat-permissions-are-in-scope-of-the-health-apps-policy

My app **does** contain the RECORD_AUDIO permission, a permission in the list from the link above. I will reach out to Google on this and declare this. It does seem odd that Google doesn't give us this error when manually uploading the app bundle in the Google console.

Thank you for your response & guidance @cavasinf

**Comment by kenmaca** [comment]
We're having the same issue, despite having the Health Apps declaration complete (but using some of the permissions in scope). Did you receive any resolution from Google? How did you reach out to them?

**Comment by juanevp** [comment]
We also had this problem. Our app does not have health features and so it was stated in the app content declaration. But then we included one library that required ```android.permission.ACTIVITY_RECOGNITION```. And we started getting this submit error, but still could submit manually to the internal testing track. Only when we tried to promote the release to a more public did track Play Store point out the inconsistency forcing us to modify the app content declaration.
We ended up removing the library and expo submit started working again. Otherwise I think would have had to send the app content changes for review to fix things.

**Comment by cavasinf** [comment]
@juanevp if you are using expo, you can "block" any permission you don't want.
In your `app.json` like this:
```json
{
  "android": {
    "blockedPermissions": ["android.permission.ACTIVITY_RECOGNITION"]
  }
}
```

See: https://docs.expo.dev/versions/latest/config/app/#blockedpermissions

**Comment by bbjay** [comment]
@Marcus-Hurlbut have you been able to resolve the api issue with Google? I also have the RECORD_AUDIO permission and declaring it in the health features was not enough...

**Comment by owenadley** [comment]
Any updates here? Experiencing this issue as well

**Comment by stesvis** [comment]
I am getting this today:
```
Google Api Error: Invalid request - You must let us know whether your app uses any photo and video permissions
```
My app doesn't use the camera.

**Comment by RyanKingWorkrise** [comment]
> I am getting this today:
> 
> ```
> Google Api Error: Invalid request - You must let us know whether your app uses any photo and video permissions
> ```
> 
> My app doesn't use the camera.
Looks like google made a change to how this works. 
https://support.google.com/googleplay/android-developer/answer/14115180?hl=en

**Comment by jonymusky** [comment]
Please check your project dependencies. 
For example, if you are using `expo-image-picker`, you can see in the changelog (https://github.com/expo/expo/blob/main/CHANGELOG.md#5200–2024-11-08) how the latest version fixes this issue. 
This might be causing the failure.

**Comment by Spokplacenta** [comment]
`Google Api Error: Invalid request - You must let us know whether your app uses any photo and video permissions`
Same error and i don't use camera too. 
i don't have any new dependancies since last upload.

**Comment by miodrage** [comment]
> Google Api Error: Invalid request - You must let us know whether your app uses any photo and video permissions

Same error...

**Comment by Spokplacenta** [comment]
Google asks to fill out a form since yesterday...
https://support.google.com/googleplay/android-developer/answer/14115180?sjid=6522950558168634975-EU

**Comment by stesvis** [comment]
> Google asks to fill out a form since yesterday... https://support.google.com/googleplay/android-developer/answer/14115180?sjid=6522950558168634975-EU

Thanks, but in my play console i don't have any notifications about it and i can't find where to answer that...

**Comment by maecy25** [comment]
> > Google asks to fill out a form since yesterday... https://support.google.com/googleplay/android-developer/answer/14115180?sjid=6522950558168634975-EU
> 
> Thanks, but in my play console i don't have any notifications about it and i can't find where to answer that...

Hi, I just ran into the same issue just now. Took me a while before I can find where I need to go Just in case you haven't found it yet, this is what I did:

1. Login to your Google Play Console
2. Go into your app dashboard
3. On the sidebar, click Monitor and Improve > Policy and programs > App Content

from the App Content, you should be able to start filling out the form required. Hope this helps!

**Comment by stesvis** [comment]
> > > Google asks to fill out a form since yesterday... https://support.google.com/googleplay/android-developer/answer/14115180?sjid=6522950558168634975-EU
> > 
> > 
> > Thanks, but in my play console i don't have any notifications about it and i can't find where to answer that...
> 
> Hi [@stesvis](https://github.com/stesvis) , I just ran into the same issue just now. Took me a while before I can find where I need to go Just in case you haven't found it yet, this is what I did:
> 
> 1. Login to your Google Play Console
> 2. Go into your app dashboard
> 3. On the sidebar, click Monitor and Improve > Policy and programs > App Content
> 
> from the App Content, you should be able to start filling out the form required. Hope this helps!

Thank you! That page says "You are all caught up", and my app doesn't use the camera, so I really don't know why I get that error:
```
Google Api Error: Invalid request - You must let us know whether your app uses any photo and video permissions
```

**Comment by maecy25** [comment]
@stesvis it says you're all caught up with me too but when I clicked on the App Content under the Policy, that's when it showed the declaration forms for media and health features. :)

**Comment by stesvis** [comment]
@maecy25 yeah i can see where the health features are, and mine have no issues:

![Image](https://github.com/user-attachments/assets/9d03a0a1-d77a-48fa-a423-2134ab77b4c0)

but as far as camera features, i don't see a section for it.
