### ISSUE TITLE
Sign is NOT spelled 'sigh' 

### ISSUE THREAD

**Issue by davidakoontz** [fastlane/fastlane#22213]
### New Issue Checklist

- [ x] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I've noticed a mispelling of 'sign' in your docs and also in the tooling.  
  Ex: "In the gif we used cert && sigh, which will first create an iOS code signing certificate ..."
  As an English speaker this really freaks me ... sigh - an audible breath expressing sadness.

##### Command executed
fastlane sigh

##### Complete output when running fastlane, including the stack trace and command used
[20:52:19]: fastlane detected a Gemfile in the current directory
[20:52:19]: However, it seems like you didn't use `bundle exec`
[20:52:19]: To launch fastlane faster, please use
[20:52:19]: 
[20:52:19]: $ bundle exec fastlane sigh
[20:52:19]: 
[20:52:19]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

<details>
  <pre> sigh - is misspelled - you mean 'sign' </pre>
</details>

### Environment

<details>
  <pre> I've noticed a mispelling of 'sign' in your docs and also in the tooling.  
  Ex: "In the gif we used cert && sigh, which will first create an iOS code signing certificate ..."
  As an English speaker this really freaks me ... sigh - an audible breath expressing sadness.
   </pre>
</details>

**Comment by iBotPeaches** [comment]
The tool IS called "Sigh" - https://github.com/fastlane/fastlane/tree/master/sigh

![Screenshot 2024-09-06 at 9 21 41 AM](https://github.com/user-attachments/assets/36053a47-4972-46f9-8c59-0752c542412d)

**Comment by davidakoontz** [comment]
Oh WOW!  Well I wonder how many people think like I do…  maybe a note about the reason for the sigh name would be nice.

**Comment by jbehrens94** [comment]
It's called `sigh`, because that what everybody does around signing.

**Comment by davidakoontz** [comment]
Cute. But not very sustainable/ friendly for a mass audience of professionals. David Koontz     Email: ***@***.***     (360) 259-8380     http://about.me/davidakoontzOn Sep 10, 2024, at 9:12 AM, Johann Behrens ***@***.***> wrote:﻿
It's called sigh, because that what everybody does around signing.
