### ISSUE TITLE
Use `fastlane match appstore` command without apple account password 

### ISSUE THREAD

**Issue by AcarFurkan** [fastlane/fastlane#22249]
Can I log in to fastlane match without apple password with API key?

I run the fastlane match appstore command and it asks for the repo and I give the link. Then it asks for the information of the apple account. Is there an option that I can continue by giving an api key instead of username and password? For example, we use google auth and almost no one has a password.

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by arc-v2** [comment]
@AcarFurkan Yes, check [the docs](https://docs.fastlane.tools/app-store-connect-api/#using-fastlane-api-key-json-file).
