### ISSUE TITLE
Xcode 16 Release xcov fail as xcresulttool get object is deprecated

### ISSUE THREAD

**Issue by kanokporn-w** [fastlane/fastlane#22262]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Getting error when running xcov on Xcode16 Release 

##### Command executed

```ruby
xcov(...)
```

##### Complete output when running fastlane, including the stack trace and command used

```
[02:37:37]: Derived content from ["{path}/Logs/Test//LogStoreManifest.plist", "{path}.xcresult"]
Error: This command is deprecated and will be removed in a future release, --legacy flag is required to use it.
Usage: xcresulttool get object [--legacy] --path <path> [--id <id>] [--version <version>] [--format <format>]
  See 'xcresulttool get object --help' for more information.
[02:37:37]: Error occured while exporting xccovreport from xcresult '{path}.xcresult'
[02:37:37]: Make sure you have both Xcode 11 selected and pointing to the correct xcresult file

.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/fastlane-2.223.1/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': \e[31m[!] Failed to export xccovreport from xcresult'\e[0m (FastlaneCore::Interface::FastlaneCrash)
Failed to execute - xcrun xcresulttool get --format json --path {path}.xcresult (RuntimeError)
```

### Environment

Xcode 16 Release
MacOS 14.5 (23F79)
Fastlane 2.223.1
ruby 3.1.0
<details>
  <pre> 
Xcode 16 Release
MacOS 14.5 (23F79)
Fastlane 2.223.1
ruby 3.1.0 </pre>
</details>

**Comment by kanokporn-w** [comment]
my bad, turn out my xcresult was outdated

**Comment by Keuha** [comment]
could you elaborate on `xcresult was outdated` I am facing the exact same issue at the moment

**Comment by kanokporn-w** [comment]
fastlane support this issuesince version 2.222.0. However you should also update xcresult to version 0.2.2. Could check it via gem list. Mine was 0.2.1 when I open this issue.
