### ISSUE TITLE
Match: build fails on CI when specifying appstore type only

### ISSUE THREAD

**Issue by Sega-Zero** [fastlane/fastlane#2297]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When running on a CI (like Travis for example), where no codesign identities installed (totally clean state), specifying just `appstore` in match leads to build&archive failure
> ❌ Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) were found.

(More output could be seen in #1989)

### Configuration Files

Fastfile:
```ruby
desc "Perform a build, upload to crashlytics"
private_lane :build do |options|
    version = "#{ver_major}.#{ver_minor}.#{build_num}"     
    increment_version_number(version_number: version)
    increment_build_number(build_number: version)

    match_type = options[:beta] ? "development" : "appstore"
    match(type: match_type, app_identifier: proj_id, verbose: true)
    
    ENV["PROFILE_UDID"] = ENV["sigh_#{proj_id}_#{match_type}"]

    scheme = (options[:beta] ? "Release" : "Appstore")
	
    gym(
        workspace: 'Project.xcworkspace',
        scheme: scheme,
        clean: true, 
        output_directory: ".",
        output_name: "Project.ipa",
        use_legacy_build_api: true
    )
	
    crashlytics(
        ipa_path: './Project.ipa',
        groups: "test-group",
        notifications: false
    )
end

lane :deploy do
    build(beta:false)
    pilot(skip_submission:true, app_identifier: proj_id)
end
```

### Environment

fastlane version (fastlane -v): 1.66.0, bundler.

### Workaround
Since there is no local codesigning identities, the issue resolves by downloading development certificates prior to appstore ones.
Right now I had to add this to `:deploy` lane
```ruby
lane :deploy do
    match(type: "development", verbose: true)
    build(beta:false)
    pilot(skip_submission:true, app_identifier: proj_id)
end
```

Wouldn't it be more correct if `match` could verify local development codesign identities existence and, if doesn't, download it, even if appstore type is specified? 

[New machine](https://github.com/fastlane/fastlane/tree/master/match#new-machine) section in Readme.md states that a developer should download development certificates before work.  And it makes sence: `appstore` identity is of distribution type. To be able to build the project before archiving, I need development one.

**Comment by simoncoulton** [comment]
Can also confirm that this is happening with Gitlab CI.

**Comment by Sega-Zero** [comment]
The issue is still still there

**Comment by TKBurner** [comment]
Hi @Sega-Zero Thanks for following up. The current behavior follows the documentation, which states you need to run `match development` before you can use the appstore profile. Thanks!
