### ISSUE TITLE
Show version and build number in log and messages

### ISSUE THREAD

**Issue by ealeksandrov** [fastlane/fastlane#237]
I want to display in my HipChat message something like `Deployed build v#{version_number} (#{build_number}) to Apple TestFlight`, but I am unable to find an access to these values.

Tried:
```ruby
version_number = Actions.lane_context[Actions::SharedValues::VERSION_NUMBER]
build_number = Actions.lane_context[Actions::SharedValues::BUILD_NUMBER]
version_name = "v#{version_number} (#{build_number})"
```
but they are empty. `agvtool` is useless in my case, because I set build number with `PlistBuddy` this way: [Gist with script](https://gist.github.com/ealeksandrov/3ba818789bf0fd29bb87)

The only way I know - unzip ipa and see `Info.plist` (example: [ProvisionQL/GeneratePreviewForURL.m#L23](https://github.com/ealeksandrov/ProvisionQL/blob/master/ProvisionQL/GeneratePreviewForURL.m#L233))

Maybe I am missing something?

**Comment by eytanbiala** [comment]
Currently the VERSION_NUMBER is only set if you use `increment_version_number`, and BUILD_NUMBER is set by `increment_build_number`.

In your versioning script you can set environment variables with the version build and version number, and then in your Fastfile access them like this: `ENV['MY_VERSION_NUMBER']`

Let me know if this helps!

**Comment by ealeksandrov** [comment]
Tried to export in shell script and access ENV in fastlane - no luck.
Will think about some action to obtain version and number from built project.

**Comment by siemensikkema** [comment]
I wanted to to automate storing IPAs with version/build number in the filename. This is what I came up with to get the the numbers:
```ruby
version = `/usr/libexec/plistbuddy -c Print:CFBundleShortVersionString '../Project/Project-Info.plist'`.strip
build_number = `cd ..;agvtool what-version -terse`.strip
```
Hope this helps!

**Comment by JaviSoto** [comment]
I'm going to go ahead and close this issue for now since it's been inactive for a long time. Feel free to reply if you'd still like to get some help with this and we'll reopen it!

**Comment by pheuberger** [comment]
I would actually prefer if the version string was available through fastlane. I consider the solution of @siemensikkema a workaround. My use case is to tag the build with version and build number, so when I need to go back and look for a specific version, I don't have to keep track which build is the most current build for that version. Anyway, I can understand if you don't support this if it takes more effort than is reasonable for such a minor feature.

**Comment by ndbroadbent** [comment]
For anyone else who finds this issue while Googling, this is how you can get the build and version numbers:

```
build   = get_build_number()
version = get_version_number()
```

**Comment by TKBurner** [comment]
@ndbroadbent Thanks for sharing! Hope you have a great week 👍

**Comment by false** [comment]
I also needed the build and version numbers to name the generated ipas.
Unfortunately get_build_number() / get_version_number() won't work if you have multiple targets.
A simple fallback is to use the get_info_plist_value fastlane action : 
```
version_number = get_info_plist_value(path: "./XXX-Info.plist", key: "CFBundleShortVersionString")
build_number = get_info_plist_value(path: "./XXX-Info.plist", key: "CFBundleVersion")

```

**Comment by KrauseFx** [comment]
Thanks for sharing @false 👍
