### ISSUE TITLE
[Feature] Dash Support

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/fastlane#259]
Show fastlane action documentation in Dash :+1:

**Comment by milch** [comment]
Ha, you took my comment seriously. :+1: to this feature!

**Comment by KrauseFx** [comment]
I take all ideas seriously. I'm very serious :wink:

**Comment by KrauseFx** [comment]
But I'm not working on this feature, I just added this issue.

**Comment by ohwutup** [comment]
this would be sweet, but going to close it for now as it's been inactive for a while. :ocean:

**Comment by KrauseFx** [comment]
:cry:

**Comment by ohwutup** [comment]
i know :( this would be sweet. :heart: dash :runner:
