### ISSUE TITLE
Actions for git-flow support

### ISSUE THREAD

**Issue by duemunk** [fastlane/fastlane#263]
[Git-flow](https://github.com/nvie/gitflow)

I might get around to making this one myself.

**Comment by KrauseFx** [comment]
What do you want to do with it?

**Comment by duemunk** [comment]
I want to make a lane where I 1) create release branch, 2) increment build, 3) commit, 4) push to test flight, 5) finish release branch. 
1 and 5 is related to git-flow. 
I could do it with simple git commands, but thought I would wrap it in an action so it could be re-used.

**Comment by DominicFrei** [comment]
@duemunk Why would you want to push that release to test flight AND finish that newly generated release branch immediately in one action? Shouldn't that be mutually exclusive as you want to wait for the test feedback?

**Comment by jcampbell05** [comment]
Should be able to do this via git and custom actions or sh if you use the git flow tool

**Comment by ohwutup** [comment]
Hey everyone! I am going to close this issue for now as it seems a bit stale without discussion for some time. please feel free to reopen the issue or continue discussion and we will keep this in mind down the road. Thanks again!! :octopus: !
