### ISSUE TITLE
Invoking multiple lanes

### ISSUE THREAD

**Issue by frobichaud** [fastlane/fastlane#265]
Hi,
just upgraded to 1.0.0 and I previously invoked fastlane with multiple lanes on the same line, such as:
```
$ fastlane pods beta
```
I now get the following:
```
Could not find lane 'pods beta'. Available lanes: ...
```

Do I need to invoke fastlane multiple times to achieve the same result?
```
fastlane pods
fastlane beta
```

**Comment by KrauseFx** [comment]
Unfortunately I had to remove this feature with the addition of multiple platforms. You can now run `fastlane pods && fastlane beta` with the same result :+1:

**Comment by frobichaud** [comment]
Thanks, we use a script in our CI environment that invokes fastlane with multiple lanes through an ENV variable.
It used to be
```
bundle exec fastlane $FASTLANE_LANES
```
We now replaced it with the following bash script:
```
IFS=' ' read -a array <<< "$FASTLANE_LANES"
for element in "${array[@]}"
do
  bundle exec fastlane $element
done
```

**Comment by KrauseFx** [comment]
Sorry for the troubles.

**Comment by bgerstle** [comment]
@KrauseFx would it be feasible to specify a platform and then multiple lanes? or at least some syntax to arbitrarily combine them?  for example:

``` shell
fastlane --platform ios lane1 lane2
fastlane ios.lane1 mac.lane2
```

Or, the ability to declare "multi tasks" a la Rake.  I don't see an enhancement ticket for this, though I recall seeing something similar a while back..  Should I create one?

**Comment by KrauseFx** [comment]
@bgerstle Thanks for your feedback. There is no ticket for it yet, so I re-opened this one again. Why do you need this exactly? Doesn't chaining multiple lanes generate the same result for you? 

```
fastlane ios test && fastlane ios beta
```

Would like to understand your use case so we can work out a good solution :+1:

**Comment by bgerstle** [comment]
@KrauseFx it's a minor concern, but things can quickly become verbose if you're using `bundle exec` (as the original reporter was).  Aside from that, Rake-like functionality would be cool:

- [Task prerequisites](http://rake.rubyforge.org/doc/rakefile_rdoc.html#label-Tasks+with+Prerequisites)
- [Multitasks](http://rake.rubyforge.org/doc/rakefile_rdoc.html#label-Tasks+with+Parallel+Prerequisites)

I would enjoy taking a stab at this, but can't be sure when I'll be able to get around to it.  Happy to provide more feedback if desired, though.

**Comment by KrauseFx** [comment]
I guess it was not a good idea from me to use a space as a separator for the platform/lane. I'll think about a better solution. :+1:

**Comment by bgerstle** [comment]
@KrauseFx Actually, Rake does this with [namespaces](http://rake.rubyforge.org/doc/rakefile_rdoc.html#label-Namespaces), if you're looking for inspiration. Can't think of any other tools with similar features off the top of my head.

**Comment by bgerstle** [comment]
Also, for being so responsive: :cake: :beers: :pizza: :smile:

**Comment by KrauseFx** [comment]
@bgerstle I have the feeling we should do a bigger rewrite to cover the following:

1) Dependencies between lanes (I think you mentioned that above)
2) Endless nested lanes. Right now it's only 2 levels with the platform + lane

On the other hand we have to keep everything simple, as the target group is non Ruby devs who just want to specify their build steps.

**Comment by bgerstle** [comment]
Good call on KIS(S).  This seems like it will also break backwards compatibility with a couple things:

- Old syntax of invoking lanes: `fastlane $platform $lane`
- Per-platform/lane config in the Appfile `lane 'ios beta' do ...`

OTOH, I guess a power user could use Rake directly and shell out to fastlane when necessary, but it's suboptimal to use two separate tools.

**Comment by KrauseFx** [comment]
Is this issue resolved from your side? Anything that needs to be done here?

**Comment by bgerstle** [comment]
What was the relevant change?

**Comment by JaviSoto** [comment]
@bgerstle is this still something that you think could be improved beyond just doing `fastlane action1 && fastlane action2`?

**Comment by bgerstle** [comment]
Probably not, since you can invoke lanes within other lanes now.

**Comment by JaviSoto** [comment]
Great! Glad to hear :)

**Comment by manuyavuz** [comment]
Sorry for adding this to a closed issue but I couldn't find a documentation for invoking a lane inside another lane, and this issue was the closest one. 

> Probably not, since you can invoke lanes within other lanes now.

How can we start another lane from within a lane? cc/ @bgerstle

**Comment by bgerstle** [comment]
@manuyavuz it's documented under [Advanced#Switching Lanes](https://github.com/fastlane/fastlane/blob/master/docs/Advanced.md#switching-lanes). you can see how we at Wikipedia are using this feature to [from the `alpha` lane, run the `bump` lane to increase the build number & use the return value to push a tag after everything succeeds](https://github.com/wikimedia/wikipedia-ios/blob/master/fastlane/Fastfile#L64)

**Comment by manuyavuz** [comment]
I read the Advanced section but somehow overlooked the section 😞 Thank you very much @bgerstle  for the fast feedback!

**Comment by twobitlabs** [comment]
Docs moved. Updated link to [Advanced#SwitchingLanes](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Advanced.md#switching-lanes).
