### ISSUE TITLE
sudo gem install fastlane -NV  | I am trying to install this but it take tooo much time after 1 hours still installing....

### ISSUE THREAD

**Issue by mohhomadfarman** [fastlane/fastlane#26518]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> 

Its look like runing in looop. instaling............... need to fix this.

200 OK
GET https://rubygems.org/quick/Marshal.4.8/jwt-2.3.0.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/jwt-2.4.0.gemspec.rz
200 OK 
GET https://rubygems.org/quick/Marshal.4.8/jwt-2.4.1.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/jwt-2.5.0.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/jwt-2.6.0.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/jwt-2.7.0.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/jwt-2.7.1.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/jwt-2.8.0.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/jwt-2.8.1.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/jwt-2.8.2.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/jwt-2.9.0.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/jwt-2.9.1.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/jwt-2.9.2.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/jwt-2.9.3.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/public_suffix-2.0.2.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/public_suffix-2.0.3.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/public_suffix-2.0.4.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/public_suffix-2.0.5.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/public_suffix-3.0.0.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/public_suffix-3.0.1.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/public_suffix-3.0.2.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/public_suffix-3.0.3.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/public_suffix-3.1.0.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/public_suffix-3.1.1.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/public_suffix-4.0.0.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/public_suffix-4.0.1.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/public_suffix-4.0.2.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/public_suffix-4.0.3.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/public_suffix-4.0.4.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/public_suffix-4.0.5.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/public_suffix-4.0.6.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/public_suffix-4.0.7.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/public_suffix-5.0.0.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/public_suffix-5.0.1.gemspec.rz
200 OK
GET https://rubygems.org/quick/Marshal.4.8/public_suffix-5.0.3.gemspec.rz
200 OK

 </pre>
</details>

**Comment by mohhomadfarman** [comment]
I need answer?

**Comment by max-ott** [comment]
Then please follow our community guidelines on opening a ticket.
